### ISSUE TITLE
Provide a url for finding more templates on `dotnet new --help`

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/cli#10002]
help for dotnet new obviously displays only the installed templates. 

Add a URL to either docs with a further link to NuGet or directly to NuGet to find additional templates.

**Comment by livarcocc** [comment]
I don't know if nuget can filter packages to package templates. And I don't believe there is one package type for such a thing. In any instance, I would move this issue to dotnet/templating. Could you do that?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1660
