### ISSUE TITLE
Windows 10 can not uninstall dotnet 4.7.2 , and can not reinstall it either.

### ISSUE THREAD

**Issue by netroby** [dotnet/cli#10004]
Windows 10 can not uninstall dotnet 4.7.2 , and can not reinstall it either.

I have no idea how to deal with it.
![qq 20180914120640](https://user-images.githubusercontent.com/278153/45529260-d52baa00-b816-11e8-80cc-3fb42dda25dc.png)
![qq 20180914120703](https://user-images.githubusercontent.com/278153/45529261-d52baa00-b816-11e8-874a-5b9ae1fc0645.png)
![qq 20180914120730](https://user-images.githubusercontent.com/278153/45529262-d52baa00-b816-11e8-82e4-543991d1b504.png)

**Comment by livarcocc** [comment]
This repo does not contain installers for net472.

This is a repo for .NET Core. So, I will close this issue.

However, @AlexGhiondea do you know who the right person is to look into this in MS?

**Comment by AlexGhiondea** [comment]
@netroby which version of Win10 are we talking about? Could you file an issue with more information in the https://github.com/microsoft/dotnet repo?
