### ISSUE TITLE
Possible to display version on dotnet/cli page?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1000]
Is it possible for you to display the current version ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12534372/a480d12c-c20b-11e5-991e-cee6d0d8f7b1.PNG)

... in the vicinity of the CI build info ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/12534375/c94a5a50-c20b-11e5-8de0-0fb4d74e940a.PNG)

... which would speed me up a bit and keep me a bit more current. OR ... is there someplace (some webpage) were I can get that info?

**Comment by piotrpMSFT** [comment]
The version number == number of commits in the history of that build along the shortest path.

We would like to display the version on the page but that would mean each commit updating the markdown file which would be awfully noisy... Other approaches?

**Comment by GuardRex** [comment]
Idk .... It's an automated process. Just how may commits are there in a day ... several dozen but not hundreds, right?

I'd be fine if there was any place ... any feed page ... anywhere ... that I could just find out that a new MSI is available for the "latest" link. I think you see where I'm going with this: The changes to `dotnet cli` are so rapid right now and the fixes are coming so crazy fast that it would be nice to jump on new releases several times a day as they arrive. As it stands, I have to download the MSI to see if it's new (or just happen to catch the page when the build is running ... and know that when it's done that I'll have access to a new one).

**Comment by piotrpMSFT** [comment]
@GuardRex let's leave this issue open. This is a common enough problem I expect others have solved it already. As @Petermarcu mentioned offline, something akin to CI badges should be fairly straightforward to implement. In fact, I just took a quick look around the web and found shields.io. We should be able to produce something like this as part of our build output just by downloading from them:

![sample badge](https://img.shields.io/badge/Version-1.0.0.1234-brightgreen.svg)

Thoughts?

**Comment by GuardRex** [comment]
@piotrpMSFT Ok ... helps me get `dotnet cli` apps into production asap ... I'm all for it.

Side Note: I close issues I open in a few hours without response b/c many/most of my ideas are plumb stupid. If I don't get a positive response from a team member, I assume (usually correctly) that the idea is ... uh ... not up to par and perhaps the product of either too much :beer: ... or :alien: influences. Where is my tinfoil hat??!! :smile:

**Comment by GuardRex** [comment]
@piotrpMSFT We're done here, right? [btw- Thanks for adding that. It rocks!]

**Comment by piotrpMSFT** [comment]
Did you notice that switching to 'master' shows the right Dev stream numbers? :) @guardrex

**Comment by GuardRex** [comment]
@piotrpMSFT Thanks for mentioning ... I didn't know that. I was looking at `rel/1.0.0`, so I set it to `master`.

**Comment by piotrpMSFT** [comment]
Rel/1.0.0 is the stabilization branch for 1.0, so keep your tools pointed there. Once we move onto vnext, however, tooling is already in place :)

**Comment by kwaclaw** [comment]
Version badges are not correct, though. The current Windows x64 shows version badge 1.0.0.001880, but the actual installer has been at version 1.0.0.001840 for a day or so.
