### ISSUE TITLE
Patch roll-forward support for .NET Core 3.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10009]
As of .NET Core SDK 2.1.300, we [use the latest patch of the runtime](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection) for self-contained publish.  There are a few issues with the way it currently works:

- The "latest version" used is defined by the current version of the .NET Core SDK which is being used.  Installing a new patch to the runtime doesn't update the version used for self-contained publish- you need an update to the .NET Core SDK which knows about the updated runtime patch.
- The version of the runtime used is selected at restore time.  So you can get errors if you try to do a self-contained publish with the `--no-restore` option, because the original restore didn't roll forward to the latest patch.

For .NET Core 3.0, we would like to take the maximum of the following as the latest version:

- The latest installed patch of the targeted Major.Minor Shared Framework.  This means that installing an updated Shared Framework is enough for self contained deployments to include it.
- The version from a list of latest patches which ships in the .NET Core SDK.  The list should include the latest patch for each Major.Minor version of each Base Shared Framework and Optional Component.  This helps self-contained publish use the latest Runtime Pack patch for apps that target prior versions of .NET Core which aren't currently installed as Shared Frameworks.
- The `MinimumRuntimeFrameworkVersion` property for the Base Shared Framework, or the `MinimumVersion` metadata on a `SharedFrameworkReference` item (property and metadata names subject to change).  This allows a project to specify that a given patch level is required without relying on whether the desired patch has been installed on the build machine.  In contrast to the current `RuntimeFrameworkVersion` property, it doesn't lock to exactly that version, but allows the patch version to roll forward to later patches if a later patch is found via other means.

**Comment by livarcocc** [comment]
I am closing this issue as we have another one in core-sdk to discuss this. We are trying a different approach there with not tying this to the SDK nor to the runtime installed in the box.
