### ISSUE TITLE
Issue with Debian: Not resolving packages in Jessie

### ISSUE THREAD

**Issue by codemonkeyrawks** [dotnet/cli#1001]
Debian "Jessie" has no package "liblldb-3.6". When it trys to install it fails.
https://packages.debian.org/search?keywords=liblldb-3.6

Here is what I get running:
#sudo dpkg -i dotnet-ubuntu-x64.latest.deb 

#dpkg: dependency problems prevent configuration of dotnet-nightly:
 dotnet-nightly depends on liblldb-3.6; however:
  Package liblldb-3.6 is not installed. ( this is resolved)
 dotnet-nightly depends on liblttng-ust0; however:
  Package liblttng-ust0:amd64 is not installed.

One fix might be to use: http://llvm.org/apt/

{
/etc/apt/sources.list
deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main
deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main

#sudo apt-get -f install 

OR:

#sudo apt-get update && apt-get install liblldb-3.6
#sudo dpkg -i dotnet-ubuntu-x64.latest.deb
}

**Comment by codemonkeyrawks** [comment]
I will take a look into this more tomorrow if I get a chance. It may be something that can be added to the deb file in resolving the package. It would be nice to have a built package something like what nodejs does: https://packages.debian.org/jessie/nodejs to where you could just install it.

**Comment by brthor** [comment]
@codemonkeyrawks Our debian package is currently targeted at Ubuntu 14.04, however it should still work on debian Jessie. 

These error messages would be expected when using dpkg to configure your package. 
If you use `apt-get install dotnet-nightly` do you see the same issues?

**Comment by codemonkeyrawks** [comment]
@brthor : Is there a deb-src line I should be adding in for installing dotnet-nightly.

**Comment by piotrpMSFT** [comment]
@codemonkeyrawks have you tried http://dotnet.github.io/getting-started/? The feed setup instructions are all there. The dotnet-nightly package comes on the same feed [dotnet package does not exist yet. It will come to life when we ship Beta]

**Comment by codemonkeyrawks** [comment]
@piotrpMSFT : I was following (http://docs.asp.net/en/latest/getting-started/installing-on-linux.html) and (http://docs.asp.net/en/latest/dnx/console.html).I will look at the getting started you provided.

**Comment by jeremymeng** [comment]
Same issue after installing `dotnet-nightly` on Debian.  Had to add the llvm feed manually.  Worse that http://llvm.org/apt/ no longer lists version 3.6.  Users might have hard time finding out how to add a source feed to have `liblldb-3.6` package available on Debian.

**Comment by moozzyk** [comment]
Just hist this as well. Looks like you can add the following package source:
`deb [arch=amd64] http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main`
to work the issue around but it's hacky...

**Comment by brthor** [comment]
Until we are publishing a debian:jessie specific .deb @moozzyk 's workaround is probably the best way to go

**Comment by codemonkeyrawks** [comment]
I found my answer for now: Feel free to port it however fit.

# Toolchain Update for Debian:
sudo sh -c 'echo "deb http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main" > /etc/apt/sources.list.d/llvm-toolchain.list' && sudo sh -c 'echo "deb-src http://llvm.org/apt/jessie/ llvm-toolchain-jessie-3.6 main" > /etc/apt/sources.list.d/llvm-toolchain.list'
sudo apt-get update && sudo apt-get install liblldb-3.6

# .Net Core for Debian
sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet=1.0.0.001598-1

**Comment by piotrpMSFT** [comment]
Thanks for the workaround, @codemonkeyrawks. This should hold folks over until we have native DEB packages available. #3944

**Comment by brthor** [comment]
A note here, the liblldb-3.6 dependency has been removed for the WIP debian deb packages so this issue won't surface again.
