### ISSUE TITLE
Nit: Dark red exceptions on a black console background are not easy to read ...

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1002]
![capture](https://cloud.githubusercontent.com/assets/1622880/12534649/a01df328-c218-11e5-9174-0c10348ff545.PNG)

**Comment by piotrpMSFT** [comment]
@GuardRex just turn up your screen brightness!

:trollface:

**Comment by piotrpMSFT** [comment]
That color is pretty annoying against most background colors. Care to make a PR with something equally menacing but more readable?

**Comment by GuardRex** [comment]
@piotrpMSFT 

So looking at https://github.com/dotnet/cli/blob/4f18f938d4fe8a8420339ae9c120b09a4e9c2a2f/src/Microsoft.DotNet.Cli.Utils/AnsiConsole.cs#L41
```c#
Console.ForegroundColor = 
    (ConsoleColor)(((int)Console.ForegroundColor & 0x08) | ((int)color & 0x07));
```
... was the point there to modify the intensity depending on the current foreground color [depending on white (full color), gray (muted), or black (muted)]?

![capture](https://cloud.githubusercontent.com/assets/1622880/12705525/fcdbc72e-c827-11e5-8370-3c89263a5933.PNG)

 ... or is this just a flat-out bug ... was the intention to do something for `Console.BackgroundColor` and the property is set incorrectly? It turns out that if you change that to `Console.BackgroundColor`, it has the effect of muting colors regardless of foreground color set ... leading me to believe this was an attempt to mute colors on a black background across the board. [Not a good idea IMHO, but it makes more sense compared to the result above.] Here's what happens when basing the line on `Console.BackgroundColor` ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/12705620/02c75610-c82a-11e5-8dbb-6dc1e3eab4ff.PNG)

Either way, there is obviously interaction with the foreground color being set elsewhere here or somewhere (Nuget?).

A draconian approach is to set the background to black at the outset and set the colors explicitly. If it went that way, you'd probably need to force reset the background to black every write; because at any given time, the user may manually change the color on their own.

If there is a concern about color contrast and preserving the user profile setting for the background and/or manual changes on-the-fly by the user, then perhaps the user's current background color should be taken into account when setting the colors. For example, if a yellow background has been set by any means, warnings are provided in orange.

**Comment by piotrpMSFT** [comment]
related to #3687 

The text coloring will get cleaned up once we move to MS Build.
