### ISSUE TITLE
why is HKEY_USERS\.DEFAULT\Environment Path modified by the sdk setup?

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#10038]
@rgl commented on [Fri Sep 14 2018](https://github.com/dotnet/core/issues/1942)

why is the `HKEY_USERS\.DEFAULT\Environment` `Path` registry key value (of the `SYSTEM` account) modified by the [sdk setup](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.4/2.1.4.md)?

before installing the sdk, the registry is:

![image](https://user-images.githubusercontent.com/43356/45577223-d094df00-b872-11e8-9ceb-8123a822c397.png)

then after installing the sdk, the registry is changed into:

![image](https://user-images.githubusercontent.com/43356/45577251-ee624400-b872-11e8-912d-bb8569515510.png)

As you can see it modified the value and its type. Why?

This is causing me problems in this scenario:

1. I'm running the [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) windows service (which runs as `SYSTEM`)
2. I login into the `jenkins` account tru the [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) service
3. I notice that the `PATH` is inherited from the `SYSTEM` account `PATH`
4. I execute the [cake build script](https://cakebuild.net/) (which will be running in the `jenkins` account)
4.1. It iterates the `PATH` environment variable and crashes because it does not have permissions to iterate any of the `C:\Users\vagrant\AppData\Local\Microsoft\WindowsApps` or `C:\Users\vagrant\.dotnet\tools` directories (because they can only be used by the `vagrant` user -- the user that installed the dotnetcore sdk).

**Comment by livarcocc** [comment]
We modify the path to add the global tools shim location to your path. This allows a transparent invocation of the installed global tools.

@wli3 can you double check and validate that we are modifying the path of the right account?

**Comment by wli3** [comment]
@rgl you mentioned "iterates". it crashes due to "reading" the value or adding the extra value?

could you also send me the error message when it crashes?

It is using 
https://github.com/dotnet/cli/blob/c4bfa1376e9c95d1ff5d213b7f9a33aa538c5065/src/dotnet/ShellShim/WindowsEnvironmentPath.cs#L51

EnvironmentVariable.SetEnvironmentVariable( . EnvironmentVariableTarget.User) API, the only option is process/user/machine.

However, in any case I think it should catch that exception like the following line. https://github.com/dotnet/cli/blob/c4bfa1376e9c95d1ff5d213b7f9a33aa538c5065/src/dotnet/ShellShim/WindowsEnvironmentPath.cs#L57

**Comment by wli3** [comment]
close due to no response

**Comment by wli3** [comment]
@rgl I think I still need detail in this sentence 

> That Path environment variable has directories in it which the normal user account has no filesystem permissions

That means the user account don't have the read access to `C:\Users\vagrant\.dotnet\tools`?

However, `app/cakebuild` will iterate whatever on the PATH? (is the iteration related to dotnet tools or just a routine of the build process)

**Comment by wli3** [comment]
@rgl and I hope to get a repro. It will crash if I build anything using cake? And you install cake as admin or user? via `Invoke-WebRequest https://cakebuild.net/download/bootstrapper/windows -OutFile build.ps1`?

**Comment by rgl** [comment]
@wli3 yes, the user account (e.g. the jenkins user account at c:\users\jenkins) does not have access to other account home directory (e.g. to c:\users\vagrant).

I think cake is installed as a user, I will confirm this tomorrow.
