### ISSUE TITLE
SSL issues after running nuget locals --clear

### ISSUE THREAD

**Issue by aeos** [dotnet/cli#10035]
## Steps to reproduce
We have a mono project which consists of multiple projects structured like so:
/root
/root/nuget_packages
/root/ProjectA/ProjectA.csproj
/root/ProjectB/ProjectB.csproj
/root/ProjectC/ProjectC.csproj

we build each project, pack them and push them to the /root/nuget_packages folder so that they can depend on each other. Any change we make in a dependency requires a new build/pack/push however we don't update the version number in the csproj because we are doing local development. If another project pulls a dependency, nuget cache sees the same version number and returns the cached package. To avoid this, we first run `dotnet nuget locals all --clear`. Then when we restore it gets the updated package. This might be a bad practice, there may be a better way.

However, this has worked fine up until we moved to 2.0. 

## Expected  behavior
Prior to dotnet 2.0 this worked without problems

## Actual behavior
After updating to 2.0 we receive a stream of errors and a long delay before the restore completes. The errors look like this:

`Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.azurekeyvault/index.json'.
  The SSL connection could not be established, see inner exception.
    Authentication failed because the remote party has closed the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json'.
  The SSL connection could not be established, see inner exception.
    Authentication failed because the remote party has closed the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.keyperfile/index.json'.
  The SSL connection could not be established, see inner exception.`

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7321
