### ISSUE TITLE
Issues with #dotnet restore command

### ISSUE THREAD

**Issue by codemonkeyrawks** [dotnet/cli#1003]
Running #dotnet restore results in not finding the package. Yet I followed this guide using dnx and it works: https://docs.asp.net/en/latest/dnx/console.html

info : NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 837ms
info : NotFound https://api.nuget.org/v3-flatcontainer/netstandard.platform/index.json 818ms

Is this also the official documentation:
https://docs.asp.net/en/latest/getting-started/installing-on-linux.html and https://docs.asp.net/en/latest/dnx/console.html?

**Comment by xanather** [comment]
I think thats normal, it will get those packages from the other nuget sources (based on the NuGet.config file), dev builds are not available on the official nuget.org source yet (they're on myget).

**Comment by codemonkeyrawks** [comment]
Gotcha,

I went and deleted the nuget.config file still runs into issues.

info : All packages are compatible with DNXCore,Version=v5.0.
error: Microsoft.Win32.Primitives 4.0.1-rc2-23704 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Console 4.0.0-rc2-23704 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Diagnostics.Debug 4.0.11-rc2-23704 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Diagnostics.Process 4.1.0-rc2-23704 provides a compile-time reference assembly for System.Diagnostics.Process on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.IO.FileSystem 4.0.1-rc2-23704 provides a compile-time reference assembly for System.IO.FileSystem on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Net.Primitives 4.0.11-rc2-23704 provides a compile-time reference assembly for System.Net.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Net.Sockets 4.1.0-rc2-23704 provides a compile-time reference assembly for System.Net.Sockets on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Runtime.Extensions 4.0.11-rc2-23704 provides a compile-time reference assembly for System.Runtime.Extensions on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-23704 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: System.Threading 4.0.11-rc2-23704 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (debian.8-x64).
info : Committing restore...
info : Restore failed in 882ms.

**Comment by GuardRex** [comment]
@codemonkeyrawks Same issue here. Had to go with `dnu restore` via VS, then copy from `.dnx\packages` to `.nuget\packages`, then ran into package nightmares :skull: after that ... same general outcome as my experience with this a couple of days ago. I had a successful console app experience this morning https://github.com/dotnet/cli/issues/468#issuecomment-174220308, but calling on many normal web app packages (e.g., MVC) derailed me. @davidfowl told me that with the upheaval in moving completely to Nuget that things would be very unstable for a bit. I'm going to try again in a few days.

**Comment by codemonkeyrawks** [comment]
No Worries. I may play with it for a few days to see if there are any other bugs besides the other I have posted. This at least lets me run .net web applications without having to use a virtual machine :+1:

**Comment by xanather** [comment]
@codemonkeyrawks 

Do you have


    "NETStandard.Library": "1.0.0-rc3-23722",

included in the dependencies part of the project.json? That pulls in the runtime libraries.

**Comment by GuardRex** [comment]
Interesting ... @davidfowl sample doesn't have that, but it was required for the successful console test this morning. I'm going to try again now with that package.

**Comment by GuardRex** [comment]
No ... no ... my bad ...
```json
"dependencies": {
    "NETStandard.Library": "1.0.0-*",
```
It's there. I've either had too many :beers: or not enough :beers:

**Comment by xanather** [comment]
Yea, not sure then. CLI is pretty unstable right now with breaking changes (as expected). I had to play around with it alittle to get my projects working (I couldn't get net461 compiling, only dnxcore50).

**Comment by GuardRex** [comment]
@xanather My :tophat: is tipped in your direction. I'm glad I saw the console app running this morning; but as it was for me two days ago, a more package-dependent MVC6 app just goes nuts with package problems. Even when it successfully compiles, it chokes when it's run.

**Comment by GuardRex** [comment]
I have no worries on this. @anurse is on the case ... and you know what @anurse does when the Earth quakes, and the poison arrows fall from the sky, and the pillars of Heaven shake ... yeah ... @anurse just looks that big ol' storm right square in the eye and he says, "Give me your best shot, pal. I can take it!"

**Comment by GuardRex** [comment]
@xanather Is this supposed to be live: http://www.xanather.com/

**Comment by anurse** [comment]
:blush: aww shucks

**Comment by piotrpMSFT** [comment]
The `Not Found` was expected but overly verbose output from the tool [DNU would have found the same, but didn't print it since it's noise]. We took new NuGet bits that address this earlier tonight so...

Fixed by #1057
