### ISSUE TITLE
Different types of objects in a variable couldnot be displayed in correct format except for the 1st type of object

### ISSUE THREAD

**Issue by shidouli** [dotnet/cli#10033]
## Steps to reproduce
PS C:\windows\system32> $vars = @($vm, $vmhost)
PS C:\windows\system32> $vars

Name                 PowerState Num CPUs MemoryGB
----                 ---------- -------- --------
test                 PoweredOff 1        0.250
WARNING: The 'State' property of VMHost type is deprecated. Use the 'ConnectionState' property instead.
WARNING: PowerCLI scripts should not use the 'DatastoreIdList' property of VMHost type. The property will be removed in a future release.

State                 : Connected
ConnectionState       : Connected
PowerState            : PoweredOn
VMSwapfileDatastoreId :
VMSwapfilePolicy      : Inherit
ParentId              : ClusterComputeResource-domain-c7
IsStandalone          : False
Manufacturer          : VMware, Inc.
Model                 : VMware Virtual Platform
NumCpu                : 2
CpuTotalMhz           : 4794
CpuUsageMhz           : 44
LicenseKey            : 
MemoryTotalMB         :
MemoryTotalGB         : 
MemoryUsageMB         : 
MemoryUsageGB         : 
ProcessorType         : Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
HyperthreadingActive  : False
TimeZone              : UTC
Version               : 6.8.1
Build                 : 
Parent                : cl
VMSwapfileDatastore   :
StorageInfo           : HostStorageSystem-storageSystem-12
NetworkInfo           : 
DiagnosticPartition   : mpx.vmhba0:C0:T1:L0
FirewallDefaultPolicy : VMHostFirewallDefaultPolicy:HostSystem-host-12
ApiVersion            : 6.7.1
MaxEVCMode            : intel-broadwell
Name                  : 
CustomFields          : {[AutoDeploy.MachineIdentity, ]}
ExtensionData         : VMware.Vim.HostSystem
Id                    : 
Uid                   :
DatastoreIdList       : {Datastore-datastore-13, Datastore-datastore-14, Datastore-datastore-15, Datastore-datastore-16...}

PS C:\windows\system32> $vars = @($vmhost, $vm)
PS C:\windows\system32> $vars

Name                 ConnectionState PowerState NumCpu CpuUsageMhz CpuTotalMhz   MemoryUsageGB   MemoryTotalGB Version
----                 --------------- ---------- ------ ----------- -----------   -------------   ------------- -------
10.10.10.10       Connected       PoweredOn       2          44        4794           1.202           7.999   6.8.1
WARNING: The 'Version' property of VirtualMachine type is deprecated. Use the 'HardwareVersion' property instead.

Name                    : test
PowerState              : PoweredOff
Notes                   :
Guest                   : test:
NumCpu                  : 1
CoresPerSocket          : 1
MemoryMB                : 256
MemoryGB                : 0.25
VMHostId                : HostSystem-host-12
VMHost                  : 
VApp                    :
FolderId                : Folder-group-v3
Folder                  : vm
ResourcePoolId          : ResourcePool-resgroup-8
ResourcePool            : Resources
HARestartPriority       : ClusterRestartPriority
HAIsolationResponse     : AsSpecifiedByCluster
DrsAutomationLevel      : AsSpecifiedByCluster
VMSwapfilePolicy        : Inherit
VMResourceConfiguration : CpuShares:Normal/1000 MemShares:Normal/2560
Version                 : v14
HardwareVersion         : vmx-14
PersistentId            : 502014c2-3fd8-50c5-1a2e-493f429dd1f7
GuestId                 : winXPProGuest
UsedSpaceGB             : 0.0390625
ProvisionedSpaceGB      : 1.4974369313567876815795898438
DatastoreIdList         : {Datastore-datastore-14}
ExtensionData           : VMware.Vim.VirtualMachine
CustomFields            : {}
Id                      : VirtualMachine-vm-23
Uid                     : 

## Expected  behavior
Both the $vm and $vmhost should be displayed in its own correct format, not be shown with the full properties

## Actual behavior
The object after the 1st type object would be shown with full properties, not with its own defined format.

## Environment data
`dotnet --info` output:

PS C:\windows\system32> dotnet --info
.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by livarcocc** [comment]
This issue was moved to PowerShell/PowerShell#7839
