### ISSUE TITLE
TreatWarningsAsErrors option is not respected in F# projects

### ISSUE THREAD

**Issue by samuela** [dotnet/cli#10044]
## Steps to reproduce
* Create an F# project.
* Elicit a build warning.
* Run `dotnet build`, verifying that the build succeeds with a warning.
* Add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` in `PropertyGroup` to your `Foo.fsproj` file, documented here: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2017.
* Run `dotnet build` again.

## Expected  behavior
The build to fail with the warning escalated to be an error.

## Actual behavior
The build still succeeds with the warning.

## Environment data
`dotnet --info` output:
```
fsharp [master ?] -> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
@KevinRansom can you please take a look?

We use that flag in our own builds without issue.

@samuela what warning exactly are you getting? Can you share a more detailed repro?

**Comment by KevinRansom** [comment]
@livarcocc 

This is not about the fsharp compiler.  it is about this:

````
/usr/local/share/dotnet/sdk/2.1.402/Microsoft.Common.CurrentVersion.targets(1879,5): warning : The referenced project 'asdfasdf.csproj' does not exist. [/Users/samuelainsworth/Development/grpc-polyglot/fsharp/src/Client/Client.fsproj]
````

Which is produced somehow by the dotnet build.  It's not a compiler warning.

**Comment by samuela** [comment]
@KevinRansom I see. How can I elevate this to be an error then?

**Comment by nguerrera** [comment]
@samuela You can use `<MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>` to treat warnings from MSBuild targets other than compilation as errors.

See https://github.com/Microsoft/msbuild/pull/1928

**Comment by samuela** [comment]
@nguerrera Great, thank you!
