### ISSUE TITLE
Install tool for other OS.

### ISSUE THREAD

**Issue by nojaf** [dotnet/cli#10045]
I'd like to install any tool locally for a specified OS.

>`dotnet tool install --tool-path .fake fake-cli`

On Windows it creates a file `fake.exe` and on Linux a file `fake`.
it be nice if I could install the tool on Windows to later use on Linux.
Perhaps create both `fake` and `fake.exe` files when installing the tool.

**Comment by livarcocc** [comment]
We have no plans of doing something like this. This would add some considerable complications into the install/build process.

Today, we carry the apphost for a particular OS inside the the CLI that targets that OS, we don't fetch it on demand.
