### ISSUE TITLE
Microsoft.DotNet.Cli.Build.DownloadFile has no retry logic and will fail CLI build for any loss of connection to server

### ISSUE THREAD

**Issue by MattGal** [dotnet/cli#10050]
@dotnet-mc-bot commented on [Wed Sep 26 2018](https://github.com/dotnet/core-eng/issues/4241)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2063339
  - **Agent:** DDVSOWINAGE015
  - **Error log:** 1>E:\A\_work\0\s\build\Prepare.targets(0,0): error MSB4018: The "DownloadFile" task failed unexpectedly. [E:\A\_work\0\s\build.proj]...

@jcagme, @markwilkie

---

@MattGal commented on [Wed Sep 26 2018](https://github.com/dotnet/core-eng/issues/4241#issuecomment-424754206)

This is a failure in code trying to download a blob in https://github.com/dotnet/cli/blob/release/2.1.2xx/build_projects/dotnet-cli-build/DownloadFile.cs#L51, hitting a temporary network interruption (`Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abnormally'`)and choosing to throw an exception instead of retry. 

As the code is all in the cli's repo itself, there's nothing DncEng can do about this so I will migrate this to their repo for triage.

**Comment by livarcocc** [comment]
@wli3 can you cook up a quick fix for this one?
