### ISSUE TITLE
Running build.sh or build.cmd should clean artifacts folder

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1005]
Running build twice in a row doesn't work. Seems to stall at the crossgen phase without any error messages. It's pretty bad. We should do 2 things:

1. Make sure it fails properly when it fails.
2. Clean the artifacts out before building to make sure it's a clean build.

**Comment by brthor** [comment]
What if we add a "clean" parameter to the build script?

In general I don't think I'd want the build to force clean my artifacts directory. We don't get incremental compilation and many times I will be reusing pieces of the build to test other pieces.

**Comment by cdmihai** [comment]
True, we would loose incremental compilation. I'm also in favor of the clean parameter. 

I also played with a `-Dev` parameter that just does stage2 and tests. It allows me to go faster through: edit code + build + edit code + build, etc

Ideally we could have a set of flags: restore, stage0, stage1, stage2, test, pack, all. While coding one could just call build -stage2 -test. For a clean build one could do build -all. Or something like that.

**Comment by piotrpMSFT** [comment]
@cdmihai can you open another issue for turning build steps on/off?

for this one, how about just `git clean -Xdf`` from root when build --clean is invoked?

**Comment by brthor** [comment]
@piotrpMSFT I don't think we should be forcing a git clean on the repo for a build. This is a really easy way to lose hours of work. Oftentimes I'll leave files untracked until I have finished testing them.

It will be tough to remember that for every build you need to ensure you don't have any untracked files.

**Comment by moozzyk** [comment]
:-1: on bare `git clean -xdf` - I even committed once [this](https://github.com/moozzyk/MSBuild-Tasks/blob/master/common.targets#L4)

**Comment by brthor** [comment]
@davidfowl @piotrpMSFT 
I envision a clean build as doing the following steps:
1. Remove artifacts folder to ensure we are building clean bits and nothing gets reused
2. Delete Stage0 folder
3. Delete all project.lock.json recursively (not sure if this is really necessary but it will force a restore)

I would not want to touch anything where a dev might have work.

Thoughts?

**Comment by brthor** [comment]
ping, any thoughts here?

**Comment by livarcocc** [comment]
@brthor sounds good to me. This is about what I do when I want clean, though I don't delete the lock files. However, I would check with @anurse to see where he stands with his build changes and work it there directly,

**Comment by davidfowl** [comment]
Why do you care about incremental build for build.cmd? Better question, why do you run the build script during dev?

**Comment by cdmihai** [comment]
During dev I run the build script with everything commented out except tests and stage2. I do this because I just want one way of doing things, not a bunch. 

Ideally, I wouldn't even want to leave visual studio just to get a build, I'd want to just press ctrl+shift+b and kick off an incremental build.

**Comment by cdmihai** [comment]
@brthor 

During work on xplat MSBuild, I found deleting the lock files mandatory when massaging nuget package versions or when restore fails. Otherwise I get random failures at RAR or runtime with missing / missmatching references. Each one takes a lot of time to debug and get to the source of the failure, so I prefer to just delete the lock files.

**Comment by brthor** [comment]
@anurse #1265 will run a clean build every time.
