### ISSUE TITLE
dotnet run, how to disable info: request details?

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/cli#10058]
Hi,

This is not an issue, it's a question.

## Steps to reproduce
- `dotnet new web`
- `dotnet build`
- `dotnet run`

Every time I refresh the browser, in cmd, I get (for ex.)

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 10.0268ms 200
``` 

How I can disable this behavior?

Thanks!

**Comment by livarcocc** [comment]
This is really a question for asp.net (this log is being printed by your application, not by the CLI).

**Comment by livarcocc** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1

**Comment by dehghani-mehdi** [comment]
@livarcocc I didn't add anything to `Hello world` project that `dotnet new web` created for me. as I mentioned in my first post, I just use CMD and that 3 commands.

So, I mentioned that is a question and not an issue, just I could find anything that can helps to disable that logs. would you help me on this? it will be great.

**Comment by livarcocc** [comment]
This is all covered in the link that I put in the comment above. There is a section about configuration where it discusses a appsettings.development.json file that you can put at the root of your project.

You can then set the logging level for different things. For instance, if you only want to see error messages for everything, you can see a file like this:

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Error",
      "System": "Error",
      "Microsoft": "Error"
    },
    "Console":
    {
      "IncludeScopes": true
    }
  }
}
```

Hope this helps.

**Comment by dehghani-mehdi** [comment]
Actually I tired `appsettings` before and it doesn't work for me, I used your mentioned json, but no success, (I don't know which part that I did wrong).

Anyway I just tired [Default minimum level](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#default-minimum-level) and it works as I expected.

Thanks for the help.
