### ISSUE TITLE
dotnet tool install of local tool fails due to NU1212

### ISSUE THREAD

**Issue by chrismetz** [dotnet/cli#10055]
## Steps to reproduce
* `dotnet new console -o testconsole`
* Modify testconsole.csproj to include `<PackAsTool>True</PackAsTool` and `<PackageOutputPath> ./nupkg</PackageOutputPath>`
* `dotnet restore testconsole.csproj`
* `dotnet build testconsole.csproj`
* `dotnet pack testconsole.csproj`
* `dotnet tool install -g -v n --add-source ./nupkg testconsole`

## Expected  behavior
testconsole will install as global tool

## Actual behavior
Tool install fails with below error as `dotnet tool install` is installing https://www.nuget.org/packages/TestConsole/ instead of installing testconsole from local ./nupkg

`NU1202: Package dotnet-watch 2.1.1 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package dotnet-watch 2.1.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
NU1212: Invalid project-package combination for dotnet-watch 2.1.1. DotnetToolReference project style can only contain references of the DotnetTool type`

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by wli3** [comment]
@nkolev92 in this case an list of sources are send to nuget. I recall local source will take the precedent of remote, should it also happen to nuget.org?

**Comment by nkolev92** [comment]
The only precedence defined is that of like-type sources. 

Namely, it's 
- Global Packages Folder and Fallback Folders
- All Local file feeds
- All network feeds.

**Comment by livarcocc** [comment]
We follow the same precedence here for global tools as exists for any packages today. We have as a goal, not to special case global tools in that sense. So, I am going to close this issue.

@chrismetz if you believe there should be a way to set precedence or to change the current precedence rules, please file an issue at nuget/home. Please note, that this is a conversation that in that case should happen for all packages, not just for dotnet tools packages.
