### ISSUE TITLE
update year in license

### ISSUE THREAD

**Issue by rahulkumaran** [dotnet/cli#10069]
## Steps to reproduce
Check the license in the repo.

## Expected  behavior
The year should be 2018.

## Actual behavior
Currently, the year is 2015. Would like to work on this.

**Comment by livarcocc** [comment]
@richlander do we need to update this?

**Comment by sharwell** [comment]
@livarcocc @richlander Let's talk offline about this

**Comment by peterhuene** [comment]
@sharwell was there any result of that discussion?  If there's nothing to do regarding updating the year, then I'd like to close this issue.  Thanks!

**Comment by livarcocc** [comment]
I have a PR out here for this: https://github.com/dotnet/cli/pull/10760.

I want to pull this to the other repos as well.

**Comment by livarcocc** [comment]
We updated the license across ours repos. Arcade helped us do that.
