### ISSUE TITLE
dotnet test verbosity level for test output only

### ISSUE THREAD

**Issue by codefactorydevelopment** [dotnet/cli#10063]
If we want to have a list of tests passed in test suite (only overall stats), we need to use at least
`dotnet test -v n` 
verbosity level. But, that one comes with a whole bunch of build output info also.

It would be nice to have a verbosity level that would show tests that were run in suite but without all the build info.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1773
