### ISSUE TITLE
Duplicate Targetframework attribute

### ISSUE THREAD

**Issue by Adrug** [dotnet/cli#10065]
I have similary problems with that  [issue](https://github.com/dotnet/cli/issues/9197). 
It started when i run ` npm install`.  Packages  installation finished with error then `dotnet build` got error
I tried deleting the obj and use `dotnet clean`. It is not helped me.

## Steps to reproduce

```
npm install
dotnet build
```

## Expected  behavior

Successful build

## Actual behavior

```
/tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [/root/betprofit-server/VFL.Web/VFL.Web.csproj]
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.402/

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.2 [/usr/share/dotnet/sdk]
  2.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by Adrug** [comment]
My project very old. The project was successfully compiled  before use `npm install`.
I notice that in project root folder create autogenerate file `.NETCoreApp,Version=v2.1.AssemblyAttributes.cs`. If I delete it the compilation is successful but then created again

Cat  `.NETCoreApp,Version=v2.1.AssemblyAttributes.cs`

```
// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v2.1", FrameworkDisplayName = "")]
```

**Comment by Adrug** [comment]
No, i think that no. Before the advent of have this error i added one new npm package in my project. 

Okay, can I leave a direct link here?
> Without a binlog or a repro we can reproduce ourselves, there isn't much we can do.

Yes, this help me
> You can try setting <GenerateAssemblyInfo>false</GenerateAssemblyInfo> in your project, so see if the file stops being generated and your build succeeds.

**Comment by livarcocc** [comment]
Yes, you can leave a link here.

So, setting the property above fixed the issue for you?

**Comment by Adrug** [comment]
Yes, it helped

**Comment by Adrug** [comment]
LOL! After setting the property and next successful build. I try remove the property but `dotnet build` again successful. It is MAGIC! Yesterday, i ran three times `dotnet build` then every time i had to delete assembly generate file.

**Comment by livarcocc** [comment]
I am going to close this issue then. Thanks.
