### ISSUE TITLE
Change help to show dotnet build instead of compile

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1007]
Compile should really never be used directly anymore.

**Comment by blackdwarf** [comment]
@davidfowl did you fix this already? Most of the MD files use `dotnet build` now.

**Comment by davidfowl** [comment]
Not yet https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Cli/Program.cs#L30

**Comment by blackdwarf** [comment]
Ah, I read "documentation" instead of "help". :)

**Comment by blackdwarf** [comment]
This issues has been resolved in #1030.
