### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80070008

### ISSUE THREAD

**Issue by sgentile** [dotnet/cli#10071]
I'm running on OSX, latest core.

It works but then something wasn't building in our project which then causes the dotnet core to crash - working inside Visual Code

Requires a complete reboot to restore to work

**Comment by livarcocc** [comment]
Can you provide us with a dump? I don't believe just he HRESULT is enough. Given that this is inside VS Code, @rchande any ideas?

**Comment by sgentile** [comment]
one thing to add - I recently upgraded to Mojave.   (I'm not sure if there is a problem with dotnet core on mojave)

**Comment by sgentile** [comment]
Then I rebooted and ran it again ok - so it's not consistent

**Comment by sgentile** [comment]
ok, working fine for awhile.   I change some code, rebuild and then I get this

Stevens-MacBook-Pro:CLP.Web sgentile$ dotnet run
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error MSB3883: Unexpected exception:  [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : System.IO.IOException: Failed to create a temporary file. Temporary files folder is full or its path is incorrect. Too many open files in system ---> System.IO.IOException: Too many open files in system [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at System.IO.File.WriteAllText(String path, String contents) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Build.Shared.FileUtilities.GetTemporaryFile(String directory, String extension, Boolean createFile) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : --- End of inner exception stack trace --- [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Build.Shared.FileUtilities.GetTemporaryFile(String directory, String extension, Boolean createFile) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Build.Utilities.ToolTask.GetTemporaryResponseFile(String responseFileCommands, String& responseFileSwitch) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.HandleResponse(BuildResponse response, String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]
/usr/local/share/dotnet/sdk/2.1.402/Roslyn/Microsoft.CSharp.Core.targets(52,5): error : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/Users/sgentile/Workspaces/CLP/CLP/CLP.Web/CLP.Web.csproj]

The build failed. Please fix the build errors and run again.

dotnet cli continues to have issues with 'too many files open' - and this crashed the dotnet with the same dialog again

**Comment by livarcocc** [comment]
have you tried increasing the open file limit on your mac? ulimit -n? What is the current value?

**Comment by sgentile** [comment]
it's set at 2048

What would you recommend I set it too ?

**Comment by livarcocc** [comment]
Mine is 4864, though I don't remember particularly why this number.

**Comment by livarcocc** [comment]
Did updating the ulimit solve the problem for you?

**Comment by sgentile** [comment]
I updated, seemed ok at end of the day, but tomorrow I'll see how it goes and let you know - thanks

**Comment by sgentile** [comment]
It's been stable all morning - going to close this.

If it pops up again, I'll create a new item.

I was having all sorts of system instability (ie. Chrome was crashing as well) with this.   I believe I had setup this previous to Mojave upgrade, and I'm wondering if Mojave upgrade reverted it back.

Thanks for the help!
