### ISSUE TITLE
Always support current versions of ubuntu

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/cli#1009]
I've seen some language on the dotnet sites and documentation that seems to hint that you're only planning on supporting LTS releases of Ubuntu.

I'd really like to encourage you to take the same approach as many other runtime and software package vendors and maintain support for all versions of Ubuntu, up to the last LTS release.

I would really hate for my choice of language to limit my ability to upgrade my operating system, especially in the all-too-common scenario that a non-LTS release introduces vital hardware support and improvements.

**Comment by piotrpMSFT** [comment]
The .NET Core roadmap is defined here: https://github.com/dotnet/core/blob/master/roadmap.md

It shows how platform support will be expanded.

**Comment by atrauzzi** [comment]
Why are you only supporting LTS releases of Ubuntu?

Developers are almost always going to be running the most current releases (LTS or not) on their workstations.
