### ISSUE TITLE
Support build logic in SDK which was previously in package closure of Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10093]
For .NET Core 3.0, there will be a targeting pack for ASP.NET Core, which will be a flattened package with reference assemblies for everything in Microsoft.AspNetCore.App.  In previous versions, some of the packages transitively referenced by Microsoft.AspNetCore.App included build logic (I believe, for example, for Razor compilation).

For .NET Core 3.0, we don't want this build logic to be part of the targeting pack.  So probably we want to include this functionality in the .NET SDK.  (This would be via inserting the necessary logic as part of the build, not by adding it to the dotnet/cli or dotnet/sdk repos).

**Comment by dsplaisted** [comment]
FYI @natemcmaster

**Comment by livarcocc** [comment]
Replaced by https://github.com/aspnet/AspNetCore/issues/3611.
