### ISSUE TITLE
Resolve runtime pack to use for self-contained publish (including RID)

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10095]
For .NET Core 3.0, we plan to use [runtime packs](https://github.com/dotnet/cli/issues/10007) to deliver runtime assets for self-contained publish.

We expect to use ["download only" packages](https://github.com/NuGet/Home/issues/7339) to acquire the appropriate runtime pack.  This means that the SDK will need to select the correct runtime pack.

We can use a naming convention or a table of packages in the .NET Core SDK to help select the runtime pack.  However, we still need to determine which RID to use.  This may not be an exact match with the RID used for publish, for example we will want to use the Linux portable (linux-x64) RID for the runtime pack, even if the publish RID is more specific.

To do this, we may want to include the RID graph as part of the SDK, as well as a list of RIDs that there are runtime packs for.  Then we can walk the graph to find the best match of available runtime packs to the publish RID.

We should also have some way of opting into a runtime pack for a RID that wasn't in the list of available runtime packs.

**Comment by livarcocc** [comment]
For now, we should have an implicit reference to `Microsoft.NETCore.Platforms` so that we can use it to resolve RIDs.

**Comment by livarcocc** [comment]
- [ ] Depends on #10104
