### ISSUE TITLE
tool install cannot install on culture "en-US-POSIX"  -- `dotnet tool install` cannot install on ubuntu 18.04

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#10101]
https://github.com/NuKeeperDotNet/NuKeeper/issues/433
https://github.com/dotnet/cli/issues/9974

on WSL ubuntu 18.04

Run `dotnet tool install --global NuKeeper` on WSL ubuntu 18.04. Get error `The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'nukeeper' failed to install. Please contact the tool author for assistance.`

**Comment by wli3** [comment]
I believe the following is the problem
https://github.com/dotnet/cli/blob/d0881898575c61a672d1f643efb70956a020e281/src/dotnet/ToolPackage/ToolPackageInstance.cs#L215

Console.WriteLine(string.Compare("nukeeper", "NuKeeper", StringComparison.CurrentCultureIgnoreCase) == 0);

if false here

**Comment by wli3** [comment]
`en-US-POSIX` vs `en-US`

**Comment by wli3** [comment]
Minimal repro

```
private static void Main(string[] args)
        {
            CultureInfo.CurrentCulture = new CultureInfo("en-US-POSIX");
            Console.WriteLine("CurrentCulture is {0}.", CultureInfo.CurrentCulture.Name);
            Console.WriteLine(string.Compare("nukeeper", "NuKeeper", StringComparison.CurrentCultureIgnoreCase) == 0);
        }
```

**Comment by wli3** [comment]
#### Description

Change package id comparison for dotnet tool install from CurrentCultureIgnoreCase to OrdinalIgnoreCase

#### Customer Impact

The user has culture "en-US-POSIX" cannot successfully install global tools. So far the reported systems have default culture "en-US-POSIX" are Ubuntu 18.04 on AWS  https://github.com/NuKeeperDotNet/NuKeeper/issues/433#issuecomment-426949525 and Ubuntu 18.04 on WSL on desktop windows

#### Regression?

No.

#### Risk
Low. The production change is only from string comparison CurrentCultureIgnoreCase to OrdinalIgnoreCase. And OrdinalIgnoreCase is the correct string comparison for ids.

#### Link to issue
https://github.com/dotnet/cli/issues/10101

**Comment by wli3** [comment]
verifying this is by design on corefx side https://github.com/dotnet/corefx/issues/32699

**Comment by wli3** [comment]
verified, https://github.com/dotnet/corefx/issues/32250#issuecomment-420749205

cc @KathleenDollard @nguerrera

**Comment by livarcocc** [comment]
@wli3 you marked this issue for 3.0, if so, it does not require shiproom approval. If you want this to be considered for 2.1.4xx or 2.1.5xx, please mark it as so.

**Comment by wli3** [comment]
@livarcocc sorry i for get to change the milestone after finding the root cause. I marked it 2.1.4xx now

**Comment by wli3** [comment]
Changed the target milestone to 2.1.500

**Comment by danmosemsft** [comment]
cc @tarekgh
