### ISSUE TITLE
dotnet-sdk-2.1 fails to install Debian 9

### ISSUE THREAD

**Issue by danielbarrios76** [dotnet/cli#10103]
## Steps to reproduce
$ sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1 : Depends: dotnet-runtime-2.1 (>= 2.1.5) but it is not going to be installed
                  Depends: aspnetcore-runtime-2.1 (>= 2.1.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

How do I correct this problem?

**Comment by livarcocc** [comment]
@leecow

**Comment by leecow** [comment]
Works fine on a green Debian 9 Docker image for me so let's figure out what you're missing. Can you try to install the dependency package by itself? This will tell us which system dependency you're not getting to. 

`sudo apt install dotnet-runtime-deps-2.1`

**Comment by danielbarrios76** [comment]
i try that but i get this error:

sudo apt install dotnet-runtime-deps-2.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-deps-2.1 : Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by danielbarrios76** [comment]
and i get this error

$ sudo apt-get install libicu57
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libicu57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu57' has no installation candidate

why i get this error?

**Comment by leecow** [comment]
Interesting. According to https://packages.debian.org/search?keywords=libicu57, the package is available in the stable repo which is what I see on my machine and I would expect to be accessible in any default install unless it's deliberately blocked or removed.

```
root@8e8c6d6375ce:/etc/apt# apt search libicu57
Sorting... Done
Full Text Search... Done
libicu57/stable,stable 57.1-6+deb9u2 amd64
  International Components for Unicode

libicu57-dbg/stable,stable 57.1-6+deb9u2 amd64
  International Components for Unicode (debug symbols)
```

Run: `find /etc/apt -type f -exec grep "debian stretch main" '{}' \; -print`. If you don't  something like following is not returned, you'll need to add `deb http://deb.debian.org/debian stretch main` to `/etc/apt/sources.list`.

```
deb http://deb.debian.org/debian stretch main
/etc/apt/sources.list
```

**Comment by danielbarrios76** [comment]
i dont find in my machine the file libicu57 but i find libicu60!!

$ sudo apt search libicu57
Sorting... Done
Full Text Search... Done


$ sudo apt search libicu60
Sorting... Done
Full Text Search... Done
libicu60/stable,now 60.2-6 amd64 [installed]
  International Components for Unicode


and I do not know how to correct this

**Comment by livarcocc** [comment]
Have you tried @leecow's suggestion above to add the source.list?

**Comment by leecow** [comment]
According to https://packages.debian.org/search?keywords=libicu60, libicu60 is only available on a testing and unstable repo. Seems like you may not have stable registered on your system. Checking your sources.list contents will give us this answer.

**Comment by danielbarrios76** [comment]
this is the content of my sources.list file

deb http://deb.debian.org/debian/ stretch main non-free contrib
deb-src http://deb.debian.org/debian/ stretch main non-free contrib

deb http://security.debian.org/debian-security stretch/updates main contrib non$
deb-src http://security.debian.org/debian-security stretch/updates main contrib$

deb http://ftp.us.debian.org/debian/ stretch-updates main contrib non-free
deb-src http://ftp.us.debian.org/debian/ stretch-updates main contrib non-free

deb http://www.deb-multimedia.org stretch main non-free

there  is something wrong in this file?

i gonna try remove all dependency files and purge, and i try install again.

**Comment by danielbarrios76** [comment]
I do this and I can not solve this problem.

I close this problem because I download binary files, installs and works well

**Comment by leecow** [comment]
You need to add `deb http://deb.debian.org/debian stretch main` then it will work as expected.

**Comment by cheesemacfly** [comment]
@leecow running into the same issue here and I have this line in the sources.list


Any other idea?

**Comment by leecow** [comment]
@cheesemacfly - same issue meaning unable to install because libicu57 cannot be found when attempting to install on Debian 9? 

Could you also let me know how you acquired Debian 9? That will give me a better chance at seeing what you are encountering.  

cc @rakeshsinghranchi
