### ISSUE TITLE
Add test coverage for referencing multiple shared frameworks

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10102]
For .NET Core 3.0, we will have optional shared frameworks for ASP.NET Core as well as "Desktop UI" (WPF and Windows Forms).  An app should be able to reference and both of these shared frameworks.

We've already done work to support this, so it may already work.  We need to make sure we've done all the work needed and add test coverage.

It would also be nice to do some E2E / scenario testing for an app that has a WPF or WinForms UI and uses ASP.NET Core.

**Comment by livarcocc** [comment]
Once we have real targeting packs and runtime packs, we need to add E2E tests for this.

**Comment by dsplaisted** [comment]
We have unit test coverage of this, and we are also going to validate the scenario with app building.
