### ISSUE TITLE
Dotnet tool ef, showing error when installed in the same version

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/cli#10112]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/13505 filed by @alanrezendee

Operating system used:
ArchLinux

Dotnet version that presents the error: 2.1.4.
Dotnet ef version that presents the error: 2.1.4.

When I run the simple "dotnet ef" command, where everything is OK with the tool, I should return for example "Entity Framework Core .NET Command-line Tools 2.1.2-rtm-30932", and command-line options of the tool, is displaying the error below:

Error message: A Fatal Error occurred, the required library libhostfxr.so could not be found
If this is a self-contained application, that library should exist in [some path here.
If this is a framework-dependent application, install the runtime in the default location [default location] or use the DOTNET_ROOT environment variable to specify the runtime location.

Before this error I researched a solution that worked for me, but solving the error message reported above, and presenting a new error as per message below, when again running the "dotnet ef" command. Since then I have researched various solutions and none have satisfied my need. Considering this context I was able to make a solution of my own by installing a smaller version of the tool dotnet ef, and this way it worked.

Error Message: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.5' was not found.
 - Check application dependencies and target a framework version installed at:
     / opt / dotnet
 - Installing .NET Core prerequisites might help solve this problem:
     http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
 - The .NET Framework and SDK can be installed from:
     https://aka.ms/dotnet-download
 - The following versions are installed:
     2.1.4 at [/opt/dotnet/shared/Microsoft.NETCore.App]

My doubts are as follows:
Why does dotnet version 2.1.4 and dotnet ef 2.1.3 work, and does it not work with the same 2.1.4 versions?

**Comment by livarcocc** [comment]
Can you provide us a repro of how you are getting to this situation? Are you using the dotnet ef command that ships with the CLI itself? And if so, how are you installing new ones?

The libhostfxr error usually happens when your application is missing a runtimeconfig.json file, indicating which runtime we should use. But you don't explain how you could have gotten yourself in this situation.

How did you install the .NET Core SDK? How did you install ef, if at all?

**Comment by livarcocc** [comment]
@alanrezendee

**Comment by alanrezendee** [comment]
> Can you provide us a repro of how you are getting to this situation? Are you using the dotnet ef command that ships with the CLI itself? And if so, how are you installing new ones?
> 
> The libhostfxr error usually happens when your application is missing a runtimeconfig.json file, indicating which runtime we should use. But you don't explain how you could have gotten yourself in this situation.
> 
> How did you install the .NET Core SDK? How did you install ef, if at all?

The dotnet installs were made directly by the archlinux yay package manager, and the specifications of these facilities are as follows:

* community / dotnet-sdk 2.1.4;
* community / dotnet-runtime 2.1.4;
* community / dotnet-host 2.1.4;

After installing the three packages above, I followed the following flow until the error pointed to me was presented:

1 - Installation of the dotnet f and the command:
      $ dotnet tool install -g dotnet-ef

2 - After this installation when running the command dotnet ef, presented the error already reported, related to DOTNET_ROOT, where when correcting this, presented new error already reported, and as I informed I ended up solving it by uninstalling dotnet ef and installing it again only in version 2.1.3, that is, it is currently running dotnet 2.1.4 and dotnet ef 2.1.3.

Apparently there is an incompatibility between the version of dotnet 2.1.4 with dotnet-ef  2.1.4. which forced me to work as I reported.
@livarcocc

**Comment by wli3** [comment]
i create this issue. dotnet-ef 2.1.4 is targeting runtime 2.1.5

https://github.com/aspnet/EntityFrameworkCore/issues/13544

**Comment by wli3** [comment]
per aspnet/EntityFrameworkCore#13544 , dotnet-ef version does not relate to runtime version. sdk 2.1.4xx  has runtime 2.1.4 while dotnet-ef sdk 2.1.4 is targeting 2.1.5. You need higher version of dotnet sdk to run it. As of today there is no release version of it, you need to use preview version

**Comment by alanrezendee** [comment]
Understood! 
Thank you guys!

**Comment by alanrezendee** [comment]
> per [aspnet/EntityFrameworkCore#13544](https://github.com/aspnet/EntityFrameworkCore/issues/13544) , dotnet-ef version does not relate to runtime version. sdk 2.1.4xx has runtime 2.1.4 while dotnet-ef sdk 2.1.4 is targeting 2.1.5. You need higher version of dotnet sdk to run it. As of today there is no release version of it, you need to use preview version



> per [aspnet/EntityFrameworkCore#13544](https://github.com/aspnet/EntityFrameworkCore/issues/13544) , dotnet-ef version does not relate to runtime version. sdk 2.1.4xx has runtime 2.1.4 while dotnet-ef sdk 2.1.4 is targeting 2.1.5. You need higher version of dotnet sdk to run it. As of today there is no release version of it, you need to use preview version

@wli3 
Understood! 
Thanks for the importance and the speed in the answers! Big hug!

**Comment by ajcvickers** [comment]
@wli3 EF Core 2.1.4 was released as part of .NET Core 2.1.5, which was a coordinated release across all of .NET Core. If it is targeting a _preview runtime_ then something has gone _very wrong_ in product construction.
/cc @livarcocc @natemcmaster

**Comment by natemcmaster** [comment]
dotnet-ef 2.1.4 looks fine to me. https://www.nuget.org/packages/dotnet-ef/2.1.4. It's runtimeconfig.json contains this:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.5"
    }
  }
}
```
This means you must have the .NET Core 2.1.5 runtime installed to run dotnet-ef 2.1.4.
