### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80070057

### ISSUE THREAD

**Issue by thmulvany** [dotnet/cli#1011]
This may be due to all the recent [name] changes but thought I'd post nonetheless.
This one is real easy to repro.
Base Win10 (nothing installed, no dev tools, no dnvm, no dnx, nothing but base OS), was working thru @DamianEdwards / @davidfowl labs (https://github.com/DamianEdwards/aspnet5-workshop/blob/master/Labs/.NET%20CLI.md), followed steps here: http://dotnet.github.io/getting-started/ , (incl C++ 2015 redist), mkdir c:\projects\cliapp, cd into that dir, dotnet new, dotnet restore yields error: `Failed to initialize CoreCLR, HRESULT: 0x80070057`.

**Comment by GuardRex** [comment]
@thmulvany https://github.com/dotnet/cli/issues/969#issuecomment-174042192

**Comment by thmulvany** [comment]
Thanks. It works, closed it.
