### ISSUE TITLE
Publish self-contained solution without replicating all files

### ISSUE THREAD

**Issue by lorenzo93** [dotnet/cli#10119]
## Steps to reproduce
Run `dotnet publish -c release -r linux-x64 -o testExport` on a solution folder (a folder with inside a .sln file and folders for each project in the solution)

## Expected  behavior
It would be better if it creates a single folder with all the common files (e.g. the dotnet framework) and the compiled projects. It can reduce a lot the space used on disk.
Now I have a solution with 6 project inside, compiling with portable options each project is like 2MB, while compiling with self-contained each project is like 100MB, but most of the files across the different projects are redundant

## Actual behavior
It creates inside each project a folder named "testExport" with the self-contained export. So each folder now contains a copy of all (or maybe just the part used) of dotnet framework

## Environment data
`dotnet --info` output:
.NET Core SDK (che rispecchia un qualsiasi file global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by dasMulli** [comment]
Cross-linking the SO question here: https://stackoverflow.com/questions/52660241/dotnet-publish-sln-having-projects-with-multiple-target-frameworks-fails

My recommendation is to not call `dotnet publish` on solution files because it has a lot of dangerous side effects. This has come up a few times and there was even a discussion about issuing a warning when publishing a solution.

**Comment by lorenzo93** [comment]
@dasMulli No, that wasn't my question (my fault!).

I have 6 projects all targeting the same framework (.NET Core 2.1).
I have to deliver them all together and I have to deliver them self-contained (so with -r and --self-contained options). With actual behaviour I need to deliver something about 600MB.

But the projects are very small, so if I build them with the portable option they are less than 10MB all together. This because the command `dotnet publish` puts a copy of the .NET Core framework inside the output folder so they can run without the framework installed locally.

Across my projects the 90% of the framework is just copied (the other part are the different libraries used by the projects), putting that part in common you can reduce A LOT the output folder size.

**Comment by dasMulli** [comment]
So the goal for 3.0 is also to be able to trim the size of self-contained executables and embed the runtime into single outputs. You may see the sizes of the individual self-contained outputs go down drastically and have no other runtime assets in the publish output if things are implemented as advertised. Maybe this will already solve your problems.

You can also try out the ILLinker task preview described at https://github.com/dotnet/core/blob/master/samples/linker-instructions.md to reduce the size of the individual self-contained outputs.

Did you consider shipping portable applications together with a private copy of the .NET Core runtime? You'd have to call `dotnet` from a folder that you ship and not have the entry points be executables but rather shell scripts that call the command but it may be an option.

**Comment by lorenzo93** [comment]
@dasMulli I've tried this morning the ILLinker preview and the output size was reduced from 100MB each project to 70MB, not as I expected.

Could you explain with more details how can I do to ship the private copy of .NET Core runtime and create the shell scripts? Maybe this can solve my problem :)

**Comment by livarcocc** [comment]
Also noticed that at the moment this is not something that we intend to support. Publishing multiple projects is a dangerous practice with no guarantee of success. For instance, if any of these projects have dependencies that differ in versions and this assembly gets laid over in a single folder, one of the apps will not work as an assembly dependency won't be fulfilled.

I am going to close this issue as a change we have no plans of making, but fell free to continue the discussion.

However, reinforcing what @dasMulli mentioned above, the linker and a single executable might be a solution for you when they become officially available.

@peterhuene FYI.
