### ISSUE TITLE
Add fsi tool

### ISSUE THREAD

**Issue by hez2010** [dotnet/cli#10118]
Currently in order to use fsi, we have to install Visual Studio. Why not integrate fsi into dotnet cli as a tool?

Then we can use:
```
> dotnet fsi

Microsoft (R) F# Interactive version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
```

**Comment by dasMulli** [comment]
See https://github.com/Microsoft/visualfsharp/issues/4060

**Comment by livarcocc** [comment]
This is being tracked in the issue linked above.

**Comment by tobia** [comment]
I'm using a shell alias to launch the F# repl that is already shipping with the dotnet sdk:

    alias fsi='/usr/bin/dotnet /usr/share/dotnet/sdk/*/FSharp/fsi.exe'

I don't know why there is no shortcut to do that from the dotnet tool (like `dotnet fsi`) or where is the proper place to open an issue about it.
