### ISSUE TITLE
vs code .Net console template does not exists HELP PLEASE

### ISSUE THREAD

**Issue by kaskubla** [dotnet/cli#10122]
I have donwloaded .net core 2.1 and sdk from microsoft and when i try to create new console program in vs code error comes up:     dotnet new console -o MyApp
output:
No templates matched the input template name: console.

Templates      Short Name      Language      Tags
-------------------------------------------------

when i try to download it from internet it downloaded 1.1 version that does not work with my 2.1

------------------------------------------
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
Can you tell us how you are trying to create a new console app? Which command are you using?

it seems like you have SDK 2.1.403, which is the latest one released, so you should be good there.

**Comment by kaskubla** [comment]
with command dotnet new console -o <name>

**Comment by kaskubla** [comment]
>           Can you tell us how you are trying to create a new console app? Which command are you using?
> it seems like you have SDK 2.1.403, which is the latest one released, so you should be good there.

with command: dotnet new console -o name

**Comment by livarcocc** [comment]
Any chance you can give us a screenshot of the attempt to run that command?

cc @mlorbetske @vijayrkn in case they have any ideas on why this would happen and how to fix it.

**Comment by livarcocc** [comment]
Can you try running `dotnet new --debug:reinit` to see if that fixes your problem? It seems like your templates are busted, as you can see from the fact that no templates are listed in the table.

**Comment by kaskubla** [comment]
> Can you try running `dotnet new --debug:reinit` to see if that fixes your problem? It seems like your templates are busted, as you can see from the fact that no templates are listed in the table.

yea that help thank you so much
