### ISSUE TITLE
Support versionless PackageReference for AspNetCore when targeting .NET Core 3.0

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10124]
In .NET Core 3.0, the syntax for depending on the ASP.NET Core shared framework is:

```
<FrameworkReference Include="Microsoft.AspNetCore" />
```

In .NET Core 2.1 and 2.2, a versionless `PackageReference` is used instead:

```
<PackageReference Include="Microsoft.AspNetCore.App" />
```

In order to support retargeting 2.x apps to 3.0, we should also support the `PackageReference` syntax  when targeting 3.0.  We might also want a warning or info message suggesting a change to the newer syntax.

**Comment by natemcmaster** [comment]
I think a PackageReference to aspnetcore in 3.0 should be an error. It's not an actual package reference anymore, right? 

If that's all we did, the upgrade experience would be a bummer. How hard would it be to have VS switch the item type for us when users upgrade to .NET Core 3.0?

**Comment by DamianEdwards** [comment]
Can't we support it but make it a warning?

**Comment by dasMulli** [comment]
to clarify: the scenario is using 3.0 *tools* to build a 2.1/2.2 app?

**Comment by dsplaisted** [comment]
@dasMulli That's not the scenario for this bug.  The scenario for this bug is that you have a 2.1/2.2 app with a versionless AspNetCore `PackageReference`, and then you change the `TargetFramework` to `netcoreapp3.0`.  Per @DamianEdwards' suggestion, current POR is to build correctly but generate a warning.
