### ISSUE TITLE
Add "!~" operator to test filter

### ISSUE THREAD

**Issue by mano-cz** [dotnet/cli#10149]
## Steps to reproduce
run "dotnet test Some.csproj --filter FullyQualifiedName!~Some.Namespace"

## Expected  behavior
Not contain operator will work.

## Actual behavior
Not contain operator is not implemented yet.

## Use case
Parallelization of test execution according to namespaces e.g.:
#1 thread - filter on few namespaces
#2 thread - filter on other few namespaces
#3 thread - filter on remaining (dynamic) namespaces (with usage of !~ operator on namespaces from previewous threads)

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1794
