### ISSUE TITLE
Setting environment variables for tests

### ISSUE THREAD

**Issue by bbc2** [dotnet/cli#10150]
Environment variables can be set for `dotnet run` with `launchSettings.json`.  However, I couldn't find an equivalent for `dotnet test`.  Does that exist?  If not, would adding it be considered?

My use case is the setting of `CORECLR_*` environment variables for attaching a profiler to the CoreCLR.  You can set the variables before calling `dotnet` but then you end up also profiling the CLI itself, not just your executable or your tests.  That's why the `--launch-profile` option is useful in this case, but it only applies to `dotnet run` as far as I'm aware.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1795
