### ISSUE TITLE
Doc for missing dotnet command

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#10162]
The following is the experience when cannot find command. Due to the added complicity of local tools, we need a link for more detail. The second session is proposed the message. And the aka.ms need a doc with detailed information.

```shell
dotnet noexists
No executable found matching command "dotnet-noexists"
```

```
No executable found matching command "dotnet-noexists". See https://aka.ms/missing-command for more information.
```

- [ ] As well as https://aka.ms/motw -- Mark of the Web

**Comment by wli3** [comment]
@KathleenDollard I added this issue for track the doc for the aka.ms link, it is pointing to microsoft.com right now.

**Comment by danmosemsft** [comment]
@KathleenDollard I tried global tools for the first time today and this was my experience:
```
c:\git>cd dotnet tool install -g dotnet-versioninfo
The system cannot find the path specified.

c:\git>dotnet tool install -g dotnet-versioninfo
You can invoke the tool using the following command: versioninfo
Tool 'dotnet-versioninfo' (version '1.0.2') was successfully installed.

c:\git>dotnet versioninfo
No executable found matching command "dotnet-versioninfo". See https://aka.ms/missing-command for more information.
```

And I go to that page and it says nothing. So this was a bit of a failed experience. Can we get this page added?

**Comment by wli3** [comment]
@danmosemsft for the intermediate problem, that page has different command name (versioninfo) than package id (dotnet-versioninfo).

Note this line `You can invoke the tool using the following command: versioninfo`

@KathleenDollard but we do need to have this page before 3.0 release

**Comment by danmosemsft** [comment]
Thanks @wli3 - I figured that out - I wonder how common it will be to try `dotnet command` instead of `command`?

```
C:\git>dotnet versioninfo
No executable found matching command "dotnet-versioninfo"
```
Perhaps it could say, 
```
C:\git>dotnet versioninfo
No executable found matching command "dotnet-versioninfo". There is a tool "versioninfo", did you mean that?
```

**Comment by martincostello** [comment]
I just came across this issue having followed `https://aka.ms/missing-command` from the shell. Can it be updated to at least point to something more relevant (like this repo)?

**Comment by wli3** [comment]
We will remove the link and use the text in https://github.com/dotnet/cli/issues/10911 instead. We think the text can cover all the case now
