### ISSUE TITLE
Dotnet publish publish:Framework script parameter passes incorrect framework name to script

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1016]
%publish.OutputPath%/%publish:Configuration%/%publish:Framework%  results in  C:\Temp\WebApp6IIS/Debug/DNXCore  but the project was actually published to  C:\Temp\WebApp6IIS\Debug\dnxcore50 

Thanks @moozzyk for pointing this out.

**Comment by piotrpMSFT** [comment]
@brthor, can you pick this up?

**Comment by brthor** [comment]
@livarcocc Is the issue that %publish:Framework% is giving incorrect data?

**Comment by livarcocc** [comment]
Yes, it gives dnxcore instead of dnxcore50. It is probably using the a property from NugetFramework instead of the extension method.

**Comment by brthor** [comment]
The fix for this will provide the following variables, standardizing between compile and publish.

`TargetFramework` will be the short name like `dnxcore50`
`FullTargetFramework` will be the full name like `DNXCore, v=5.0`

```
{ "compile:TargetFramework", context.TargetFramework.GetShortFolderName() },
{ "compile:FullTargetFramework", context.TargetFramework.DotNetFrameworkName },

{ "publish:TargetFramework", context.TargetFramework.GetShortFolderName() },
{ "publish:FullTargetFramework", context.TargetFramework.DotNetFrameworkName },
```

cc @anurse for visibility
