### ISSUE TITLE
Multi-target ported PresentationBuildTasks

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#10174]
Make it so that the new, ported PresentationBuildTasks are used from both `msbuild` (msbuild on full framework) and `dotnet build` (msbuild on .NET Core).

**Comment by nguerrera** [comment]
This is in PR now (closed source).

**Comment by onovotny** [comment]
Fantastic! Any rough idea when it'll be in the core-sdk setup (not sure what the current latency is)?

**Comment by nguerrera** [comment]
Update: closed PR is merged. Now waiting for build to insert.

**Comment by nguerrera** [comment]
This is merged into core-sdk. Should appear in build 9748 or later.
