### ISSUE TITLE
Should compile fail when compiling for a tfm not supported in the project.json?

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1017]
If we try to compile a project for a tfm that it does not support (not present in the project.json), should we fail a pre-check? Or should we wait for it to fail due to missing dependencies for that tfm?
we currently do the later. Trying to see what is the best experience here.

Also, what if it support a Tfm for which we can map the passed one, say, it supports dotnet5.4 but we ask for it to be built for dnxcore50, should we fail this or should we build it using the dotnet5.4 references?

CC @davidfowl @piotrpMSFT

**Comment by davidfowl** [comment]
> If we try to compile a project for a tfm that it does not support (not present in the project.json), should we fail a pre-check? Or should we wait for it to fail due to missing dependencies for that tfm?
we currently do the later. Trying to see what is the best experience here.

It should fail up front. We support this but we aren't currently flowing the diagnostics properly:

https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.ProjectModel/ProjectReader.cs#L425

It broke when we ported from DNX.

> Also, what if it support a Tfm for which we can map the passed one, say, it supports dotnet5.4 but we ask for it to be built for dnxcore50, should we fail this or should we build it using the dotnet5.4 references?

Fail the build. The TFM passed in must be declared in `project.json`.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
