### ISSUE TITLE
ToolsError build failures in 'prodcon/cli/release/2.1.5xx/' - '20181013.01'

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/cli#10170]
@dotnet-mc-bot commented on [Sat Oct 13 2018](https://github.com/dotnet/core-eng/issues/4387)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2115061
  - **Agent:** DDVSOWINAGE017
  - **Error log:** 1>E:\A\_work\0\s\bin\2\win-x64\dotnet\sdk\2.1.500-preview-009365\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File 'E:\A\_work\0\s\TestAssets\TestPackages\dotnet-portable-v1-prefercli\bin\pl...

@jcagme, @markwilkie

---

@ChadNedzlek commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4387#issuecomment-429964132)

I can't tell if this is a tooling problem or a product build failure... I think it's some custom build goo in the CLI that's failing.

---

@ChadNedzlek commented on [Mon Oct 15 2018](https://github.com/dotnet/core-eng/issues/4387#issuecomment-429990552)

Seems like two targets are attempting to write to the same location here.

**Comment by livarcocc** [comment]
@johnbeisner could you please investigate this failure?
