### ISSUE TITLE
Can't create nuget package from .Netcore2.1 project

### ISSUE THREAD

**Issue by JonyTek** [dotnet/cli#10184]
## Steps to reproduce
Rund dotnet pack against .netcore2.1 project

## Expected  behavior
Create a nuget package

## Actual behavior
CLI runs restore and then exists

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Dotnet pack output:
Restore completed in 66.59 ms for D:\Working\DXC.PactTests\src\DXC.PactTests.Core\DXC.PactTests.Core.csproj.

I am trying to create a nuget package from a .netcore2.1 xunit test project. When I run dotnet pack the cli runs a successful restore but then exits and continues no further.

**Comment by dasMulli** [comment]
What kind of project is it?

ASP.NET Core projects aren't packable by default, since you should use Razor class libraries instead.
(Which you could work around by setting `<IsPackable>true</IsPackable>` inside a `<PropertyGroup>`)

**Comment by JonyTek** [comment]
@dasMulli You my friend are a legend! 

It's an xUnit project which looks like the issue - https://github.com/xunit/xunit/issues/1520

The above was the first result in google after searching IsPackable.

I couldn't found this documented anywhere so thank you very much.
