### ISSUE TITLE
Publish directory inconsistent between Windows and Ubuntu

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1019]
Ubuntu CLI is publishing to temp2, but Windows publishes to temp2/Debug/dnxcore50.

**Repro**
```
dotnet new
dotnet restore
dotnet publish -o temp2 -f dnxcore50 --runtime ubuntu.14.04-x64
dotnet.exe publish -o temp2 -f dnxcore50 --runtime win7-x64
```

Could you please fix it to be consistent? Is this by design?

Needed for:
https://github.com/dotnet/corert/pull/717

```
dotnet publish -o temp2 -f dnxcore50 --runtime ubuntu.14.04-x64
Publishing temp for DNXCore,Version=v5.0/ubuntu.14.04-x64
Compiling temp for DNXCore,Version=v5.0
...
Published to temp2
Published 1/1 projects successfully
```

```
dotnet.exe publish -o temp2 -f dnxcore50 --runtime win7-x64
Publishing temp for DNXCore,Version=v5.0/win7-x64
Compiling temp for DNXCore,Version=v5.0
...
Published to temp2\Debug\dnxcore50
Published 1/1 projects successfully
```

**Comment by brthor** [comment]
@schellap The windows behavior you are seeing will be the correct behavior
Ubuntu builds are down in master on VSO currently which is the reason for the disconnect. #1029 should bring us closer to fixing that but there are some other issues as well.

**Comment by andschwa** [comment]
We're hitting this, broke our Windows CI build and also appears to have regressed on OS X.

@brthor Why is `--output` going to be (essentially) ignored? Is there a new command to tell it to publish the flat list of DLLs to the folder we specify?

**Comment by davidfowl** [comment]
I'm fixing this as part of https://github.com/dotnet/cli/issues/987

**Comment by moozzyk** [comment]
:clap:

**Comment by andschwa** [comment]
I am against this new behavior. We *really* liked that `--output bin` gave me `./bin/program`. Very easy to use. Changing this means changing scripts, documentation, CI, and updating our developers and previewers for the new behavior.

Is there going to be a better way to publish?

**Comment by davidfowl** [comment]
@andschwa It's going to be flat. The changes I'm making will make it the way it was. If you publish multiple runtimes to the same output folder it'll tell you or fail or something.

**Comment by andschwa** [comment]
@davidfowl Perfecto! Thank you.

**Comment by piotrpMSFT** [comment]
@livarcocc
