### ISSUE TITLE
support --interactive credential usage for dotnet sln add when adding csproj's with custom build sdks

### ISSUE THREAD

**Issue by karkatic** [dotnet/cli#10197]
## Steps to reproduce
create a custom build sdk
publish the nupkg to an authenticated feed
reference the sdk/ver in a csproj
add the csproj to a sln using "dotnet sln add <csprojpath>

## Expected  behavior
credentials are used, or --interactive can be supplied, to download the sdk nupkg

## Actual behavior
error output stating sdk can't be found

## Environment data
`dotnet --info` output:

**Comment by jeffkl** [comment]
We'd to enable interactivity in MSBuild before evaluating the project [here](https://github.com/dotnet/cli/blob/95c6eff6daa1a69f29c42b2d405400ad44bdec91/src/dotnet/SlnFileExtensions.cs#L45).  This can currently be done by setting the global property `NuGetInteractive` to `true` or using an overload that takes `BuildParameters` with the `Interactive` property set to `true`.  [More info](https://github.com/Microsoft/msbuild/blob/40e45d2305fc415a7209d56ae4dd93267883f0aa/src/Build/Evaluation/Evaluator.cs#L259)

**Comment by livarcocc** [comment]
There was a decision a while ago not to enable the interactive flag outside of nuGet. I believe the NuGet team has documented this somewhere.

**Comment by karkatic** [comment]
> e

so what use is authenticated feeds then, if we can't use them for adding projects to a solution, or installing dotnet tools from?
