### ISSUE TITLE
For .NET Core 3.0, create a .net core ASP.NET Core web/webapi/mvc project via CLI, dotnet restore failed with error NU1102: Unable to find package Microsoft.AspNetCore.App with version (>= 3.0.0-alpha1-10062).

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#10194]
## Steps to reproduce
Using CLI : Create a .net core ASP.NET Core web/Web API/Web App (Model-View-Controller) project

## Expected  behavior
dotnet restore and build succeed without errors or warnings.

## Actual behavior
dotnet new web/webapi/mvc --> succeed
dotnet restore -->Failed with error NU1102: `Unable to find package Microsoft.AspNetCore.App with version (>= 3.0.0-alpha1-10062)
`
Open .csproj file, use .netcore3.0 as default.
![3 0web](https://user-images.githubusercontent.com/33921754/47139243-e4a68300-d2ed-11e8-858b-6ab510c3f0a7.png)
Note: Add localfeed package source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json doesn’t work.
## Environment data
CLI/SDK - 3.0.100-alpha1-009676 against d16.0stg
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-alpha1-009676
 Commit:    e5ae52d155

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-alpha1-009676\

Host (useful for support):
  Version: 3.0.0-preview1-27016-04
  Commit:  3b8753ee45

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  3.0.100-alpha1-009676 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10062 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27006-1 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview1-27016-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by baby7305** [comment]
I have the problem too.I used in mac

**Comment by livarcocc** [comment]
Closing this issue.

This was due to a missing feed. Since preview1, there is a published version on nuget.org for 3.0.0-preview1 of asp.net.
