### ISSUE TITLE
More failures due to duplicate runtimeconfig.json in release/2.2.1xx/ branch

### ISSUE THREAD

**Issue by MattGal** [dotnet/cli#10209]
@dotnet-mc-bot commented on [Sat Oct 20 2018](https://github.com/dotnet/core-eng/issues/4435)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2137635
  - **Agent:** DDVSOLINUXAGE007
  - **Error log:** [39;49m[36m     1>[39;49m[39;49m[31m/opt/code/bin/2/linux-musl-x64/dotnet/sdk/2.2.100-rtm-009543/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File '/opt/code/TestAssets/TestPackages/dot...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2137636
  - **Agent:** DDVSOWINAGE016
  - **Error log:** 1>E:\A\_work\0\s\bin\2\win-x86\dotnet\sdk\2.2.100-rtm-009543\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File 'E:\A\_work\0\s\TestAssets\TestPackages\dotnet-portable-v1-prefercli\bin\platfo...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2137637
  - **Agent:** DDVSOWINAGE017
  - **Error log:** 1>E:\A\_work\0\s\bin\2\win-x64\dotnet\sdk\2.2.100-rtm-009543\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File 'E:\A\_work\0\s\TestAssets\TestPackages\dotnet-portable-v1-prefercli\bin\platfo...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2137630
  - **Agent:** DDVSOLINUXAGE003
  - **Error log:** [39;49m[36m     1>[39;49m[39;49m[31m/opt/code/bin/2/linux-x64/dotnet/sdk/2.2.100-rtm-009543/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File '/opt/code/TestAssets/TestPackages/dotnet-p...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2137633
  - **Agent:** DDVSOMACAGE009
  - **Error log:** 1>/Users/buildagent/agent/_work/0/s/bin/2/osx-x64/dotnet/sdk/2.2.100-rtm-009543/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File '/Users/buildagent/agent/_work/0/s/TestAssets/TestPackages/d...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2137634
  - **Agent:** DDVSOLINUXAGE006
  - **Error log:** [39;49m[36m     1>[39;49m[39;49m[31m/opt/code/bin/2/rhel.6-x64/dotnet/sdk/2.2.100-rtm-009543/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(0,0): error NU5118: File '/opt/code/TestAssets/TestPackages/dotnet-...

@jcagme, @markwilkie

---

@MattGal commented on [Mon Oct 22 2018](https://github.com/dotnet/core-eng/issues/4435#issuecomment-431887406)

This is the same issue as https://github.com/dotnet/cli/issues/10170, will move it over to CLI as the fix apparently needs to be ported to more places.  @johnbeisner FYI.

**Comment by livarcocc** [comment]
@mmitche The change is already in 2.2.1xx. Are we sure we are building the latest SHA from dotnet/cli?

**Comment by MattGal** [comment]
Ah.  We have been having issues with mirroring, likely related to the GitHub outage.  If you're certain this is already fixed in this branch, we can just kick off a manual mirror to make sure it's picked up and close.

**Comment by MattGal** [comment]
Yup the VSTS one is behind (3399427524cf46c15c62a5b3983fc342e001644b) . I'll run the mirror manually, but the Github outage is younger than the commits so there may be a maestro issue at play too.

**Comment by MattGal** [comment]
Mirrored 2.2.1xx via https://devdiv.visualstudio.com/DefaultCollection/DevDiv/DevDiv%20Team/_build/results?buildId=2142141&view=logs, feel free to close this issue .
