### ISSUE TITLE
dotnet restore failed

### ISSUE THREAD

**Issue by TanukiSharp** [dotnet/cli#1020]
Hello,

When I run `dotnet restore` (after running `dotnet new`) I get the following error:

    Failed to initialize CoreCLR, HRESULT: 0x80070057

Hereafter is the `dotnet --version` of my current installation:

    .NET Command Line Tools (1.0.0)
    Runtime Environment:
    OS Name:     Windows
    OS Version:  10.0.10240
    OS Platform: Windows
    Runtime Id:  win10-x64

This is my very first installation of `dotnet` CLI.
I installed using the .msi provided at this link: https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi

Here is the version of the installer I used: `1.0.1.001032 dev`

Running on Windows 10 Pro (full version 10.0.10240.16392)

I've installed Visual Studio 2015 Community Edition with Update 1, meaning I have version 14.0.24720.00 of redistributable, which is greater than the one pointed by this link https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145 found from the page http://dotnet.github.io/getting-started/

It is working on my CentOS 7 server, but took quite long to restore

    info : Running restore with 16 concurrent jobs.
    ...
    info : All packages are compatible with DNXCore,Version=v5.0.
    info : All packages are compatible with DNXCore,Version=v5.0 (centos.7-x64).
    info : Committing restore...
    info : Restore completed in 143283ms.

and I could run it to get `Hello World!` printed.

**Comment by davidfowl** [comment]
Set `COREHOST_TRACE=1` and re run the windows version.

**Comment by BillWagner** [comment]
I'm having the same problem. I turned out COREHOST_TRACE, and attached the log file. 

[output.zip](https://github.com/dotnet/cli/files/103447/output.zip)

**Comment by BillWagner** [comment]
I'm wondering if some of the problem might be that I'm getting a mix of the new dotnet core and older versions of dnx / dnu dlls. This machine has been used for dnx projects from beta 4 on. At the moment, the latest DNX bits are RC 1 (Nov 2015). Does that offer any clues @davidfowl ?

**Comment by brthor** [comment]
This is most likely resolved via #525. We were seeing similar issues due to a space in the default install path of the MSI.

@TanukiSharp Please try with the latest msi

**Comment by BillWagner** [comment]
@brthor That did fix it for me. I did not to uninstall the previous MSI, and then install the new one. (Install over the previous version did not work).

**Comment by brthor** [comment]
Glad to hear it @BillWagner 

cc @Sridhar-MS on the MSI issue. Also hit that today but I had a very old version

**Comment by Sridhar-MS** [comment]
@BillWagner I recently enabled build-to-build upgrades in MSI - https://github.com/dotnet/cli/pull/836.  How old is the MSI that you had to uninstall?

**Comment by BillWagner** [comment]
@Sridhar-MS I don't have the version number handy. It was the MSI available at this link: https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi on Sunday. I'm sorry I don't have more details.

**Comment by piotrpMSFT** [comment]
Seems like this is fixed. Please re-open if needed.

**Comment by TanukiSharp** [comment]
Sorry for the late reply.

Thank you, I could get it to work using the MSI version 1.0.1.001109.
However `restore` is still very long the first time (`info : Restore completed in 219039ms.`)
