### ISSUE TITLE
dotnet-sdk-2.1 not found on WSL Ubuntu 18.04.1

### ISSUE THREAD

**Issue by Coalpha** [dotnet/cli#10204]
## Steps to reproduce
Enable WSL
Install [Ubuntu (for windows)](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6)
Open bash somehow
Run
```sh
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1
```

## Expected  behavior
The dotnet cli installs

## Actual behavior
```
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'
```
Picture of output:
![image](https://user-images.githubusercontent.com/22552895/47261858-b52e7c80-d48d-11e8-9e01-2d887acf1026.png)
I've seen several other similar issues but their fixes didn't seem to work for me.
I looked at [this issue](https://github.com/dotnet/core/issues/1889) but following these instructions didn't work
![image](https://user-images.githubusercontent.com/22552895/47261883-2ec66a80-d48e-11e8-8a27-552d87dab68a.png)

**Comment by livarcocc** [comment]
@leecow

**Comment by joseangelmt** [comment]
I have the same problem in a brand new Ubuntu 18.04.1 LTS (GNU/Linux 4.14.43-138 armv71) installation in a Odroid device.

If I run the `apt search dotnet-sdk-2.1` command, it is able to locate the packages, but when trying to install them, I get the same error message.

![problemaalinstalardotnetcoreodroid](https://user-images.githubusercontent.com/3158109/47775706-b8790200-dcf0-11e8-88be-7236c79eea6a.PNG)

**Comment by joseangelmt** [comment]
I have the same problem in a brand new Ubuntu 18.04.1 LTS (GNU/Linux 4.14.43-138 armv71) installation in a Odroid device.
If I run the apt search dotnet-sdk-2.1 command, it is able to locate the packages, but when trying to install them, I get the same error message.

![problemaalinstalardotnetcoreodroid](https://user-images.githubusercontent.com/3158109/47775834-23c2d400-dcf1-11e8-9df3-fe733afedc2a.PNG)

**Comment by livarcocc** [comment]
@leecow any idea?

**Comment by leecow** [comment]
I have no idea. Do the other packages found with `apt search` act the same way?

**Comment by joseangelmt** [comment]
Yes, as you can see in the next gif:

![dotnet-core-linux](https://user-images.githubusercontent.com/3158109/47814186-484c9980-dd4d-11e8-8f3a-9363e0a9428f.gif)

**Comment by joseangelmt** [comment]
I tried with all of them and I got the same results.  Then I searched for pngtools for example and it installed without any problem as you can see in the next gif:

![dotnet](https://user-images.githubusercontent.com/3158109/47814900-379d2300-dd4f-11e8-82f1-9e39683d970e.gif)

**Comment by joseangelmt** [comment]
Finally I decided to:

```
wget https://download.visualstudio.microsoft.com/download/pr/4d555219-1f04-47c6-90e5-8b3ff8989b9c/0798763e6e4b98a62846116f997d046e/dotnet-runtime-2.1.5-linux-arm.tar.gz
mkdir -p $HOME/dotnet && tar zxf dotnet-runtime-2.1.5-linux-arm.tar.gz -C $HOME/dotnet
export PATH=$PATH:$HOME/dotnet
```

and it is working correctly.

**Comment by livarcocc** [comment]
Closing this issue as we don't really have enough information to know why it is not working and the you seem to be unblocked.

**Comment by Coalpha** [comment]
Thanks, joseangelmt. Going about this the long way works. I installed dotnet-runtime 2.1.6. Just in case someone else wants to do this at some point, go to [the dotnet downloads page](https://www.microsoft.com/net/download). 
![image](https://user-images.githubusercontent.com/22552895/48737391-ba085c80-ec02-11e8-9bab-ce1e3721a3b0.png)
![image](https://user-images.githubusercontent.com/22552895/48737582-461a8400-ec03-11e8-9686-9bc221767f7c.png)
If you want the `x64` version, click `ARM64`. I'm not sure why they're switched but they are. Clicking one of these links will download the binary onto the "windows side" of your computer which you can just cd into.
![image](https://user-images.githubusercontent.com/22552895/48737910-30598e80-ec04-11e8-98f4-a1baac34a611.png)
and then just add the directory of the extracted tar.gz to your $PATH
