### ISSUE TITLE
version manager story

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/cli#1022]
Whats the long term vision in terms of versioning the tools? 

https://github.com/dotnet/cli/blob/master/Documentation/beta-install-experience.md#local-install

How can I be sure that if I checkout an older tag it will be build using the exact same versions of all the commands?

**Comment by piotrpMSFT** [comment]
@Mpdreamz we thus far only publish nightlies. Once we have named releases [e.g. Beta, RTM, etc] each of these will have unique URLs that you can use in order to request consistent versions from build to build.

**Comment by Mpdreamz** [comment]
That's part of the story and what I already assumed as a given :) what if I develop two applications in tandem on my local box?

Application X requires dotnet-cli 1.1 and Y dotnet-cli 1.0 (or 2.0 if the toolings is semver backwards compatible). 

How can we avoid having to manually set and call `%DOTNETCLI20%\dotnet`.

It's be nice if the OOTB experience of `dotnet compile ` in any folder took this into account. 

That way my source could jump to dotnet cli 2.0 and all my downstream maintainers would be prompted to update. 

Is there a long term story around this?

**Comment by piotrpMSFT** [comment]
We've discussed a story for this but haven't closed.

The basic idea is that, when invoked, CLI would scan up the directory hierarchy for a .dotnet folder. If it finds one with a different CLI inside it would let that CLI win. Build scripts can then download a specific CLI version into the repo root and any Machine Wide install of CLI (MSI, pkg, etc) would hook the PATH and redirect. As a final measure, CLI version would be specified in global.json to permit a great error message if the build script hadn't run yet.

**Comment by Mpdreamz** [comment]
Thanks for the heads up this is on the roadmap/backlog :+1:  appreciated :smile: 

Ideally the dotnet command itself  can bootstrap different versions into %APPDATA%, the current package is 130mb it be nice if multiple projects can share these downloads. 

The `.dotnet` special would still be great for development purposes of dotnet commands.
