### ISSUE TITLE
Dotnet Tool Install should support --interactive

### ISSUE THREAD

**Issue by JCanlett** [dotnet/cli#10231]
## Steps to reproduce
Using a private feed, run dotnet tool install -g <ToolName hosted in private feed> --interactive

## Expected  behavior
dotnet tool install passes the interactive flag to dotnet restore during the installation to support authentication

## Actual behavior
dotnet tool fails with unknown command --interactive

Honestly feel the entire auth workflow needs some attention when dealing with Azure DevOps feeds. Currently the only working flow to get this to install is this: 
1. dotnet nuget locals -c all
2. dotnet restore --interactive (this gives me a URL & code to open in a browser to complete auth) ??
3. dotnet tool install -g <%toolname%> 

If I don't clear all nuget cache first, the tool install command doesn't seem to look outside the cache folders and simply fails with a package not found error. 

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jonstelly** [comment]
I just ran into this trying to install a global tool.  As a workaround I used `dotnet add package [PRIVATE_PACKAGE_NAME] --interactive` in a throwaway project to authenticate.

Even if adding the package to the throwaway project fails (framework mismatch, etc...), the authentication succeeds and is valid for the global tool install.  Something like this in powershell:

```
$packageId = '[PRIVATE_PACKAGE_NAME]'
push-location;
try {
  cd $env:TMP;
  mkdir fakenugetauth | cd;
  dotnet new classlib;
  dotnet add package $packageId --interactive;
  dotnet tool install -g $packageId;
}finally {
  pop-location;
  rm -recurse "$($env:TMP)/fakenugetauth";
}
```

**Comment by wli3** [comment]
Add --interactive flag is easy, however, current default nuget restore verbosity is _quiet_ or it will show the confusing temp project path. That means the authentication message won't show and it completely hangs. Need to discuss this issue with nuget next monday

**Comment by wli3** [comment]
https://github.com/NuGet/Home/issues/7647
