### ISSUE TITLE
Issue with Test Category Integration

### ISSUE THREAD

**Issue by chantianu** [dotnet/cli#10230]
I found an issue with dotnet cli code to run tests. 
## Steps to reproduce
Do not have any Integration Test filter 

> example: [Trait("Category", "Integration")]

 and run this command in command prompt 

> dotnet test MyApp.Tests/MyApp.Tests.csproj --filter Category !=Integration

## Expected  behavior
When the Category is not equal to Integration then it should check if that category exists.
**if exists:** then exclude those tests and run remaining tests
**else:** then it should run all the tests normally.

## Actual behavior
But instead of running other tests normally when "Integration" category doesn't exists, it is considering all the tests as integration tests and doesn't run anything.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1819
