### ISSUE TITLE
New dotnet publish command not working as advertised

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1024]
I'm getting 
```
'C:\PLATFORM_ISSUE\src\PlatformIssue' cannot be published  for 'dnxcore50' 'osx.10.10-x64'
```
... with ...
```
dotnet publish -f dnxcore50 -r osx.10.10-x64
```
... for ...
```json
  "frameworks": {
    "dnxcore50": {}
  },
```
or
```
"frameworks": {
  "dnxcore50": { 
    "imports": "portable-net45+win8"
}
```
... as @davidfowl has in his sample for `dotnet cli`.

It's not clear what the problem is, and can the error message be more specific? I may have seen a ref somewhere that a package is required to make this work, but I've lost the ref.

Also, could you say why `"imports": "portable-net45+win8"` is required. This is for .NET Core on Nano Server testing btw.

[EDIT] It looks like the defaults (that were working yesterday) no longer work. The docs should be updated if that's the case.

**Comment by blackdwarf** [comment]
@GuardRex seems like you're on Windows, correct? The cross-platform publishing is not working yet, so the thing you're trying will fail.

**Comment by GuardRex** [comment]
Yes. Local dev box is Windows 10 and the proj is for Nano Server. This is a
temp regression? ... Workaround? .... can I `dotnet build` my way around
this?

**Comment by brthor** [comment]
@GuardRex  I usually see this error when I haven't yet run restore on a project

**Comment by GuardRex** [comment]
I ran restore twice. The only thing I changed was going from Aspnet to Core
packages for things like Mvc and Diagnostics. Wherever I had a
Microsoft.AspNet.X, I changed to Microsoft.AspNetCore.X ... restore seemed
fine with those changes.

**Comment by GuardRex** [comment]
This has simply turned out to be a package restore issue.

Conflicting comments are making it difficult to understand what package names, package sources, and command settings should be used (e.g., https://github.com/aspnet/Home/issues/1255#issuecomment-174515262).

@blackdwarf You asked elsewhere about doc troubles ...

* https://github.com/dotnet/cli
* http://dotnet.github.io/getting-started/
* https://github.com/dotnet/corert/blob/master/Documentation/how-to-build-and-run-ilcompiler-in-console-shell-prompt.md
* https://github.com/dotnet/corert/blob/master/Documentation/how-to-build-and-run-ilcompiler-in-visual-studio-2015.md
* https://github.com/dotnet/cli/blob/master/Documentation/known-issues.md
* https://github.com/dotnet/cli/tree/master/src/Microsoft.DotNet.Tools.Publish

Nothing can be done about this situation now, but it sure will be nice when its all coalesced and organized under docs.asp.net.
