### ISSUE TITLE
How to uninstall SDK on OSX and Linux?

### ISSUE THREAD

**Issue by turowicz** [dotnet/cli#10240]
I see plenty of information on how to uninstall old SDKs via Powershell or Windows Apps.

Can we get the same guide on how to do this for OSX and Linux?

**Comment by turowicz** [comment]
https://willich.io/blog/2017/09/10/uninstall-net-core-sdks-on-macos/

**Comment by wli3** [comment]
For mac, you could use `pkgutil` as in the script. For Linux, you could uninstall it via distro's package manager. Like `apt-get remove` or `rpm -e`.

**Comment by turowicz** [comment]
It would be good to have that in the docs @wli3
