### ISSUE TITLE
`dotnet new manifestfile` or `dotnet tool install package id --create-new-manifest-file`

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#10259]
A way to create manifest file since we will throw when `dotnet tool install` cannot find a manifest file

**Comment by dasMulli** [comment]
Could a default also be to create a new manifest file at the working directory if no one is found?

**Comment by wli3** [comment]
> Could a default also be to create a new manifest file at the working directory if no one is found?

We talked about this. But the problem is if you are in a directory like /obj or /bin it won't make sense.

> pass an argument

This could also work.

**Comment by dasMulli** [comment]
> /obj or /bin it won't make sense.

well.. problem between keyboard and chair? 😂 

alternatives: check for any known source control root, say .git or top-level .svn directory and if not found use the cwd.
You've surely discussed this as well so I'm interested in that result.

**Comment by wli3** [comment]
PR https://github.com/dotnet/templating/pull/1714

**Comment by wli3** [comment]
We went `dotnet new tool-manifest`
