### ISSUE TITLE
For .NET Core 2.2, create a .net core ASP.NET Core web/webapi/mvc project via CLI, dotnet restore succeeded with warning NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.ObjectPool (>= 2.2.0-rtm-181029-01 && < 2.3.0)...

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#10250]
## Steps to reproduce
Using CLI : Create a .net core ASP.NET Core web/Web API/Web App (Model-View-Controller) project

## Expected  behavior
Dotnet restore and build succeed without errors or warnings.

## Actual behavior
dotnet new web/webapi/mvc --> succeed
dotnet restore -->succeeded with` warning NU1603: Microsoft.AspNetCore.App 2.2.0-rtm-35586 depends on Microsoft.Extensions.ObjectPool (>= 2.2.0-rtm-181029-01 && < 2.3.0) but Microsoft.Extensions.ObjectPool 2.2.0-rtm-181029-01 was not found. An approximate best match of Microsoft.Extensions.ObjectPool 2.2.0-rtm-35537 was resolved.
`
![111](https://user-images.githubusercontent.com/33921754/47711534-6abcb500-dc70-11e8-8888-b02939459d07.PNG)
Note: Add localfeed package source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json or https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-2/20181029-01/final/index.json doesn’t work.

## Environment data
CLI/SDK - 2.2.100-rtm-009571 against d16.0
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100-rtm-009571
 Commit:    6078c6e7a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100-rtm-009571\

Host (useful for support):
  Version: 2.2.0-rtm-27029-02
  Commit:  49bbd209e5

.NET Core SDKs installed:
  2.1.500-preview-009335 [C:\Program Files\dotnet\sdk]
  2.2.100-rtm-009571 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-rtm-35586 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-rtm-35586 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-rtm-27029-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
@natemcmaster any idea why we would be missing some dependency in the lzma?

**Comment by natemcmaster** [comment]
I think this maybe a mistake I introduced to the prodcon misconfiguration. We added a new leg to the build. I think I missed the step that joins all outputs into the final feed. Cc @mmitche

**Comment by mmitche** [comment]
Okay I'll take a look

**Comment by natemcmaster** [comment]
I think this fixes it https://devdiv.visualstudio.com/DevDiv/_git/DotNet-BuildPipeline/pullrequest/148794?_a=overview.

I'm going to close as this was external to dotnet/cli and it should be resolved on the next build.
