### ISSUE TITLE
Produce MSBuildExtensions nupkg for insertion into VS from core-sdk repo

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10260]
The MSBuildExtensions package includes MSBuild targets which light up .NET Standard support on .NET Framework and the MSBuild SDK resolver.  These components come from various repos:

- MSBuildExtensions build logic from dotnet/sdk
- .NET Framework support package (facades, partial facades, etc) from corefx
- MSBuild SDK resolver from dotnet/cli
- Hostfxr (for MSBuild SDK resolver to use) from core-setup

We'd like to keep the versions of MSBuildExtensions and the .NET Core SDK that are inserted into Visual Studio in sync.  So the MSBuildExtensions NuGet package which is inserted into VS should be created in the core-sdk repo, so it can have the same version number as the .NET Core SDK.

**Comment by livarcocc** [comment]
Fixed by https://github.com/dotnet/core-sdk/pull/2991.
