### ISSUE TITLE
Run fsharp tests in the test suite

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#1026]
I think the tests inside `test/FSharpTestProjects` should run in the ci test suite.

I added the F# tests inside `test/FSharpTestProjects` with the same structure and behaviour as `test/TestProjects`, to make it easier to run the same test as C#. 
I'll complete with all test project types soon in the `rel/1.0.0` branch.

The tests project source are [copied](https://github.com/dotnet/cli/blob/ea434825513226c6a95f5f46d2c311f3a3cdffab/scripts/test/runtests.ps1#L52) from `tests/TestProjects` to a temp test directory. 

```powershell
cp -rec -Force "$RepoRoot\test\TestProjects\*" "$TestBinRoot\TestProjects"
```

The tests in E2E, etc only use the temp test directory and expect test projects inside a `TestProjects` directory.

I think it's possibile to parametrize `scripts/test/runtests.ps1` , to run the same test suite as c# (easier maintenance and compatibility). 

A possible solution is: 

- rename `scripts/test/runtests.ps1` to `scripts/test/runtests-lang.ps1`
- add `$TestProjectsDir` parameter to to `scripts/test/runtests-lang.ps1`
- create `scripts/test/runtests.ps1` (same name, no need to change ci script), and call:
     - `scripts/test/runtests-lang.ps1 -TestProjectsDir = "TestProjects"`
     - `scripts/test/runtests-lang.ps1 -TestProjectsDir = "FSharpTestProjects"`
- final exit code depends on both runs

Same for the .sh version

It's also possibile to loop inside the test script, but it's worse.

I can do the changes, after your feedback (i understand is an important build script) and maybe there is a better way. 

Run the fsharp suite inside the ci can help a lot!

**Comment by piotrpMSFT** [comment]
@enricosada can you hold off until Monday? We're doing a pretty big test infra revamp and don't want to build more debt. We'll want to use the dotnet-test command for this.

**Comment by enricosada** [comment]
Sure, thx @piotrpMSFT for ping, i wrote how to add tests to current scripts but was only a possible solution, i was waiting for your feedback.

I'll wait the infra revamp before complete the f# test projects, and after we can discuss how to include fsharp scripts in the suite. 

If you can, pls take a note about run f# tests with same structure/behaviour of c# in `test/TestProjects`, while improving test suite with dotnet-test.

Obv i can do the work of aligning f# test to dotnet-test after revamp, no problem about that.

If possible ping this issue after revamp, i follow dotnet/cli commits but are a lot :smile:

**Comment by piotrpMSFT** [comment]
@enricosada let's look at this again once fsproj conversion is complete.

**Comment by enricosada** [comment]
sure
