### ISSUE TITLE
Include command for upgrading SDK version

### ISSUE THREAD

**Issue by parrainc** [dotnet/cli#10270]
### Description
I've been working with .net core for a while now, and never had to upgrade the .net core SDK from the CLI because i was doing so through VS. But, what if i don't have VS installed, and i just depends of another editor/IDE (maybe vs code?).

So, I would like to see a new command in the CLI to allow the users to upgrade the installed SDK versions with no need of going [here](https://www.microsoft.com/net/download), downloading the latest SDK installer, waiting for it to complete the download (maybe not a problem for people with high net connectivity) then installing it, and going next..next through the wizard.

Instead, it would be great if I could just do something like:

> dotnet update [--latest] [--pre] [--version]

_where:_ 
`[--latest]` could be default for getting latest version of the sdk. 
`[--pre]` could be specify if i'd like to get preview versions.
`[--version]` could be specified if i'd like to get specific version (i.e. I'm in 1.0, but would like to upgrade to 2.0 instead of latest 2.1).

And maybe any other additionals paramters that need to be specified.

Hope it's possible you can consider adding this command to the CLI.

If any additional info is required, let me know.

**Comment by livarcocc** [comment]
We have been discussing this.

Let's continue the conversation here: https://github.com/dotnet/cli/issues/10176.

**Comment by parrainc** [comment]
Awesome. 
Subscribed to that issue in case new updates are provided
