### ISSUE TITLE
dotnet add library

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/cli#10286]
We need `dotnet add library` . Adding library will make the library exports available to us without using any DLLImport.

**Comment by livarcocc** [comment]
Can you give us more details to us about your ask? I for one don't quite follow what you mean by that.

**Comment by aaabbbcccddd00001111** [comment]
`dotnet add library` add library reference to a project. So that we can add any OS library reference, and all the OS library exports are available to the project without DllImport.

**Comment by livarcocc** [comment]
What would be the equivalent if you had to edit the csproj by hand? What would that look like?

**Comment by 0xd4d** [comment]
That wouldn't work since the compiler doen't know the function signature of exported functions.

If it's Windows only, you can try https://github.com/AArnott/pinvoke . Just add the nuget package you need and you don't have to manually add the dllimports yourself.

**Comment by livarcocc** [comment]
We don't really have plans to support this at the moment. If it were just a gesture to modify the csproj, it would be more feasible, though, it would still go to backlog.

But it seems like that's not just need and that additional machinery would be necessary. Given that, I am inclined to just close this issue as "Won't do".
