### ISSUE TITLE
Failure to restore MSTest and XUnit projects

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#10296]
## Steps to reproduce
Install latest d16.0 vs build with Net Core workload (no optional components)
Install latest 3.0.x runtime from https://github.com/dotnet/core-sdk
Open developer command prompt
Run dotnet new mstest -n mstest1

## Expected  behavior
The MSTest project builds and restores correctly

## Actual behavior
The project creates but fails to restore properly:
***
The template "Unit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on mstest\mstest.csproj...
  Restoring packages for c:\Users\v-masche\Downloads\mstest\mstest.csproj...
c:\Users\v-masche\Downloads\mstest\mstest.csproj : error NU1103: Unable to find a stable package Microsoft.NETCore.App with version (>= 2.2.0)
c:\Users\v-masche\Downloads\mstest\mstest.csproj : error NU1103:   - Found 816 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 3.0.0-alphautf8string-26831-02 ]
c:\Users\v-masche\Downloads\mstest\mstest.csproj : error NU1103:   - Found 46 version(s) in nuget.org [ Nearest version: 2.2.0-preview3-27014-02 ]
c:\Users\v-masche\Downloads\mstest\mstest.csproj : error NU1103:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  Generating MSBuild file c:\Users\v-masche\Downloads\mstest\obj\mstest.csproj.nuget.g.props.
  Generating MSBuild file c:\Users\v-masche\Downloads\mstest\obj\mstest.csproj.nuget.g.targets.
  Restore failed in 2.04 sec for c:\Users\v-masche\Downloads\mstest\mstest.csproj.

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
***

Manually running "dotnet restore" fails. XUnit projects fail with a similar error but NUnit projects work correctly.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-009736
 Commit:    d273cdc5af

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-009736\

Host (useful for support):
  Version: 3.0.0-preview-27106-02
  Commit:  410cba8501

.NET Core SDKs installed:
  2.1.500-preview-009398 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-009736 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 3.0.0-alpha1-10663 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-alpha1-10663 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.DesktopUI.App 3.0.0-alpha-27106-4 [C:\Program Files\dotnet\shared\Microsoft.DesktopUI.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27106-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This happens because the 3.0 SDK does not have implicit versions for netcoreapp2.2, so we default to 2.2.0, which does not exist yet.

@dsplaisted can you add implicit versions for 2.2 in the 3.0 SDK?

**Comment by dsplaisted** [comment]
This is tracked here: https://github.com/dotnet/cli/issues/10125

My plan was to wait for the non-prerelease version of 2.2.0 to be released before enabling this, unless there is a sufficient need to get it working ahead of then.

**Comment by livarcocc** [comment]
I think we can wait. We are very close to that. Will close this issue in favor of the one you mentioned above.
