### ISSUE TITLE
Multi Targeting with Global Tools

### ISSUE THREAD

**Issue by normj** [dotnet/cli#10297]
I'm looking for suggestions on how to handle multiple target frameworks. I have a tool that will be inspecting some target assemblies and I want the global tool to be using the same framework as the target assemblies were complied for.

I had tried the following csproj file where I conditionally set the `ToolCommandName` based on the TFM
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1;netcoreapp2.2</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <PackAsTool>true</PackAsTool>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp2.1'">
    <ToolCommandName>dotnet-tfm-test-2.1</ToolCommandName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'netcoreapp2.2'">
    <ToolCommandName>dotnet-tfm-test-2.2</ToolCommandName>
  </PropertyGroup>
</Project>
```

But it looks like the ToolCommandName is not evaluated at build time but instead at pack time so in my nuget package the netcoreapp2.1 and netcoreapp2.2 file DotnetToolSettings.xml is setting command name to dotnet-tfm-test-2.2 for both the netcoreapp2.1 and netcoreapp2.2 version.

So far the best plan I have come up with is to create two different projects and publish two separate global tools.

**Comment by normj** [comment]
To give more context here is the tool that I have this problem.

https://github.com/aws/aws-lambda-dotnet/tree/master/Tools/LambdaTestTool

It loads the selected project build code into its process and I need to make sure the tool is using the same version of .NET Core the selected project is using. My solution for now was to add a -2.1 suffix since it only supports .NET Core 2.1. In the future when we have other supported runtimes I would create a new package with a new suffix for the target framework.

**Comment by wli3** [comment]
Sorry for the delay. To have a different command name for different tfms is not a supported scenario. And it is not very common.

I think you solution might be the easiest way. And you could reduce the duplication in different csproj by importing a common prop file.

**Comment by normj** [comment]
Yes, I agree my scenario is uncommon. I'm fine closing the issue, I was just hoping there would have been a better approach.
