### ISSUE TITLE
Looking for 2.1.500+dependencies tag

### ISSUE THREAD

**Issue by vellozzi** [dotnet/cli#10318]
The other repos have the *-dependencies tags.
But this one doesn't have it for the latest release.

**Comment by mmitche** [comment]
Mid-morning on getting the dependency updates.  Need help from a team member to push some packages.

**Comment by vellozzi** [comment]
Thanks for the update.

**Comment by livarcocc** [comment]
Here you go: https://github.com/dotnet/cli/releases/tag/v2.1.500%2Bdependencies.
