### ISSUE TITLE
`dotnet test --blame` does not always find the right test to blame

### ISSUE THREAD

**Issue by peterzeller** [dotnet/cli#10344]
## Steps to reproduce

1. Write an xunit test method that produces a stackoverflow (For example as in this project: [blameprob.zip](https://github.com/dotnet/cli/files/2586390/blameprob.zip))
2. Run `dotnet test --blame`

## Expected  behavior

Actually I expected to get a stack trace as I get in other programming languages like Java or C.

But according to the documentation, I would at least expect something like:

```
The active Test Run was aborted because the host process exited unexpectedly while executing following test(s):
Tests.example B
```

## Actual behavior

Sometimes the failing test is not detected and in other cases it even blames a wrong test.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1841
