### ISSUE TITLE
Can't resolve packages

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1034]
OK... After resolving the issue regarding spaces in the path that was causing dotnet-cli to crash immediately on launch, I now ran into _another_ issue. When I run `dotnet restore`, it fails to resolve any of the NuGet packages specified in my `project.json`. Here's the console output when I try:

```
info : Running restore with 16 concurrent jobs.
info : Restoring packages for C:\Users\William\Documents\GitHub\ChocolateyApps\Core\Wix.Core\project.json...
error: Unable to resolve Microsoft.CSharp (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve Microsoft.Win32.Primitives (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Collections (>= 4.0.10) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Collections.NonGeneric (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.IO (>= 4.0.10) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.IO.FileSystem (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Linq (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Reflection (>= 4.0.10) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Reflection.TypeExtensions (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Runtime.InteropServices (>= 4.0.20) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Threading (>= 4.0.10) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Threading.Thread (>= 4.0.0) for .NETPlatform,Version=v5.4.
error: Unable to resolve System.Xml.ReaderWriter (>= 4.0.11) for .NETPlatform,Version=v5.4.
info : Committing restore...
info : Restore failed in 398ms.
```

Can anyone help me? @wtgodbe is waiting for my input to triage [coreclr#2143](https://github.com/dotnet/coreclr/issues/2143), and I cannot provide him any feedback due to this issue. He has asked twice now, and I do not want to keep him waiting much longer.

(On an aside: Not to be mean, but whose idea was this large, breaking change, anyway? .NET CLI used to _just work_ for me, but now I cannot even restore packages successfully. This is really annoying because I cannot continue working on my .NET Core app until these issues are resolved!)

**Comment by shahid-pk** [comment]
what feeds are you using ? what does your nuget.config look like ?

**Comment by wjk** [comment]
AFAIK, only the official (nuget.org) one. I don't have a `nuget.config` file in my solution, either.

**Comment by shahid-pk** [comment]
create a NuGet.Config and add this to it.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line be$
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/in$
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
 
```
If you are non-windows the name of NuGet.Config should be as is. Another way is to create a new project using "dotnet new" and copy the nuget.config to your project.

**Comment by wjk** [comment]
Thanks! That did it! The packages are now restoring. Just FYI, the code block your above post is garbled; the lines ending with `$` have been truncated. Thanks so much!

**Comment by patrickjamesbarry** [comment]
Does this mean you have to have a nuget.config file, local to the project? Or can you continue to rely only on your global one that exists under the users home directory?
