### ISSUE TITLE
dotnet pack fails with paket and .NET Core 2.1.500

### ISSUE THREAD

**Issue by dbrattli** [dotnet/cli#10345]
## Steps to reproduce

Add Paket to any project and run `dotnet pack` will fail after installing .NET Core 2.1.500. The error message is `The provided SymbolPackageFormat value  is invalid.`. It seems to be breaking since the new property does not have a default.

This issue is tracked in the Paket manager at: https://github.com/fsprojects/Paket/issues/3427 

## Expected  behavior

`dotnet pack` should succeed.

## Actual behavior

Fails with error:

```
➜  classlib dotnet pack                  
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  shasum: /Users/dbrattli/Developer/GitHub/classlib/.paket/../paket-files/paket.restore.cached: 
  Paket version 5.188.1
  Starting full restore process.
  Performance:
   - Disk IO: 17 milliseconds
   - Runtime: 2 seconds
  Restoring packages for /Users/dbrattli/Developer/GitHub/classlib/classlib.csproj...
  Restore completed in 178.88 ms for /Users/dbrattli/Developer/GitHub/classlib/classlib.csproj.
  Paket version 5.188.1
  The last restore is still up to date. Nothing left to do.
  Performance:
   - Runtime: 60 milliseconds
  classlib -> /Users/dbrattli/Developer/GitHub/classlib/bin/Debug/netstandard2.0/classlib.dll
  Paket version 5.188.1
  Performance:
   - Runtime: 644 milliseconds
/Users/dbrattli/Developer/GitHub/classlib/.paket/Paket.Restore.targets(226,5): error : The provided SymbolPackageFormat value  is invalid. Allowed values : 'snupkg', 'symbols.nupkg'. [/Users/dbrattli/Developer/GitHub/classlib/classlib.csproj]
```

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.500/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7514
