### ISSUE TITLE
Help needed: Using VSTS CI to build and package shared libraries that project reference themselves

### ISSUE THREAD

**Issue by lukasvosyka** [dotnet/cli#10358]
Hi,

I am wondering what the intended approach is, when I want to have multiple projects within a repository being built and packaged using nuget (or dotnet pack) that have project references, but are not built all at the same time, but on a per project base. An important side note might be that I want to have the *build number being part of the nuget package version*.

We have one Git repository (dotnetShared) that contains many shared library projects. Some of those projects have project references to other projects. Let say the repository looks like the following:

/dotnetShared
/dotnetShared.Models
/dotnetShared.Db
/dotnetShared.Messaging
etc.

Now lets say /dotnetShared/dotnetShared.csproj has following contents in regards to references:

`
<ItemGroup>
    <ProjectReference Include="..\dotnetShared.Models\dotnetShared.Models.csproj" />
    <ProjectReference Include="..\dotnetShared.Db\dotnetShared.Db.csproj" />
</ItemGroup>
`

I want to create a VSTS build definition for each of those projects using Path Filters, so only projects get built and packages, that have changed.

My build definition in VSTS looks like this
- Exec Powershell script to read major and minor version from csproj and append VSTS $buildnumber) and set the new $(buildnumber).
- dotnet build
- dotnet test
- dotnet pack
- dotnet push

Now I realized that when, for example, the dotnetShared project builds, the resulting dotnetShared nuget package (let say in version 1.0.6435) has dependencies to
- dotnetShared.Models version >= 1.0.6435
- dotnetShared.Db version >= 1.0.6435

But this is wrong, because for example the latest dotnetShared.Models version that is available via nuget is 1.0.6400 (because changes to that project are some time ago and has not changed, nor has dotnetShared.Db). 

The only way I see it working currently is that the whole repository projects get built together and pushed together, but this is sub-optimal. 

I could not find any documention about how to tackle this very scenario. I tried looking into aspnet/extensions repository because I thought they might have the same problem there but it looked like they also have to do some MSBuild stuff.

I am wondering if someone could point me in the right direction on either documentation or how to do this? As I said, the package version is determined during VSTS CI build and ideally the project references get looked up in my package feed what the latest version is and set as dependency.

Thanks for any info about this!

Cheers,
Lukas

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7525
