### ISSUE TITLE
Regression in .NET SDK 500: 'dotnet tool install' fails with 401 (Unauthorized) when there is a private feed in NuGet.config

### ISSUE THREAD

**Issue by hrumhurum** [dotnet/cli#10356]
## Steps to reproduce

1. Ensure .NET SDK 2.1.500 is installed
2. Ensure there is a private feed in NuGet.config that requires authentication
3. dotnet tool install -g Contoso.FooBar

## Expected  behavior
Tool 'contoso.foobar' (version '1.2.3') was successfully installed.

## Actual behavior
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error : Failed to retrieve information about 'contoso.foobar' from remote source 'https://rd.contoso.com:12345/nuget/feed/FindPackagesById()?id='contoso.foobar'&semVerLevel=2.0.0'. [C:\Users\Tester\AppData\Local\Temp\h2vj5tjo.mmy\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error :   **Response status code does not indicate success: 401 (Unauthorized).** [C:\Users\Tester\AppData\Local\Temp\h2vj5tjo.mmy\restore.csproj]
The tool package could not be restored.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

## Notes
The issue is not present in .NET Core SDK 2.1.400, e.g. it goes away when .NET Core SDK 2.1.500 is uninstalled, and reappears when SDK 2.1.500 is installed again.

Here is the sample `NuGet.config` from `C:\Users\Tester\Application Data\NuGet` folder:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="Contoso R&amp;D" value="https://rd.contoso.com:12345/nuget/feed" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
  <packageSourceCredentials>
    <Contoso_x0020_R_x0026_D>
      <add key="Username" value="tester" />
      <add key="Password" value="..." />
    </Contoso_x0020_R_x0026_D>
  </packageSourceCredentials>
</configuration>
```

**Comment by livarcocc** [comment]
Does it work if you just run `dotnet restore` on a project? Could you try that and let us know what happens.

Alternatively, if this is a VSTS feed, can you run `dotnet restore --interactive` to authorize the feed and then try to tool install?

**Comment by hrumhurum** [comment]
`dotnet restore` results in a similar error:

>  Restoring packages for C:\Temp\Repro\ContosoConsumer\ContosoConsumer\ContosoConsumer.csproj...
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://rd.contoso.com:12345/nuget/feed/FindPackagesById()?id='contoso.foobar'&semVerLevel=2.0.0'.
  **Response status code does not indicate success: 401 (Unauthorized).**
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error : Failed to retrieve information about 'Contoso.FooBar' from remote source 'https://rd.contoso.com:12345/nuget/feed/FindPackagesById()?id='contoso.foobar'&semVerLevel=2.0.0'. [C:\Temp\Repro\ContosoConsumer\ContosoConsumer.sln]
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Temp\Repro\ContosoConsumer\ContosoConsumer.sln]

`https://rd.contoso.com:12345/nuget/feed` is not a VSTS feed. It's a [NuGet.Server](https://www.nuget.org/packages/NuGet.Server/) proxied behind an IIS with HTTP basic/digest authentication turned on.

**Comment by hrumhurum** [comment]
A small reproduction sample that shows the error with an existing authenticated MyGet feed:

[NuGetAuthRepro.zip](https://github.com/dotnet/cli/files/2591681/NuGetAuthRepro.zip)

It does not work with .NET SDK 2.1.500.
It does work with .NET SDK 2.1.400.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7524
