### ISSUE TITLE
Publish does not copy all dependencies leading to runtime exception

### ISSUE THREAD

**Issue by gallivantor** [dotnet/cli#10381]
(see also StackOverflow post: https://stackoverflow.com/questions/53422385/net-core-published-app-fails-with-filenotfoundexception )

## Steps to reproduce
1. Create a .net core console app
2. Reference Microsoft.Windows.Compatibility nuget package
3. Add some code to call a WCF service 
4. Build & run the app through VS or with `dotnet dllname.dll` - succeeds!
5. Publish the app and try to run it from the published .exe file

## Expected  behavior
Published app works just the same as running it with `dotnet dllname.dll`

## Actual behavior
Published app throws exception:
`System.IO.FileNotFoundException: Could not load file or assembly 
'System.Private.ServiceModel, Version=4.1.2.1, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`
The file `System.Private.ServiceModel.dll` has not been copied to the publish output

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
How are you publishing your app? Also, which folder are you copying the contents of the app from?

**Comment by gallivantor** [comment]
Publishing with VS 2017 (15.9.2) right-click Publish, but same result with `dotnet publish` command line.

I'm then trying to run it from the folder that I published to (and I tried copying that publish folder to another machine but with same result)

The publish command line I used was
`dotnet publish --self-contained --runtime win-x64`

**Comment by livarcocc** [comment]
It seems like `System.Private.ServiceModel` only has runtime assets for win7. When I publish using win7-x64, I see the dll binplaced there.

cc @terrajobst @ericstj is this expected of this package?

**Comment by gallivantor** [comment]
If that's the case, then there seem to be at least two problems here:

1. The latest Windows Compatibiltiy Pack (2.0.1) is referencing an old (4.1.2.1) version of WCF DLL so even apps that reference the latest Compat Pack can't be published

2. If the publish logic can't find an assembly, shouldn't it report an error or something, rather than just silently failing to publish anything?
Luckily I noticed this problem straight away as the code path affected was part of the app startup. But it seems very dangerous that the publish could omit a DLL such that some part of application functionality is broken and you wouldn't even realise until that code path got activated at runtime?
Who knows what other packages might be similarly affected and would just be missing from an app publish, only to be discovered later when somebody activates that code path?

**Comment by livarcocc** [comment]
For issue 1, I would probably file an issue at dotnet/wcf, though it seems they have fixed it already in subsequent versions of the package.

For issue 2, we don't really know. We rely on the packages to tell us what is needed and what isn't. If our source of information is wrong, we can't really tell.

Given that, I am going to go ahead and cloe this issue.
