### ISSUE TITLE
Running all tests in a solution in parallel

### ISSUE THREAD

**Issue by mixandmatch025** [dotnet/cli#10389]
Hi, I'm trying to run all tests in a given .sln file in parallel, using either ```dotnet test``` or ```dotnet vstest```.

Using https://dasmulli.blog/2018/01/20/make-dotnet-test-work-on-solution-files/ I managed to run all the tests, but they are running sequentially.

I did manage to use vstest to run tests in parallel, but only using .dll files.

Is there any way to achieve this?

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1851
