### ISSUE TITLE
SOS DLL is missing in .NET Core for Windows

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/cli#1039]
When you install .NET Core on Windows, the SOS file which is a key binary to debug any coreclr issues is missing from the installation folder. It does ship with Linux and OSX repositories but NOT with Windows. 

Not having this binary on Windows makes it difficult to debug the apps especially when the issue is around .NET Core. Please address this ASAP.  

Another thing noticed is, when you do a “dotnet run” on Linux or OSX, the output folder will have appname.dll, appname.exe, *sos*.so/dylib and other files. Where as on Windows, the output folder will have all but sos binary.

**Comment by gkhanna79** [comment]
This needs to be part  of .net core ask package and not runtime package.

@blackdwarf is there such sdk?

**Comment by blackdwarf** [comment]
@gkhanna79 have no idea. Do we then move this then to dotnet/coreclr?

**Comment by piotrpMSFT** [comment]
@Petermarcu seems this should go into one of the SDK installers. Who can provide guidance?

**Comment by ellismg** [comment]
Is this the same as #905?

**Comment by Raviuppa** [comment]
@ellismg , Yes, seems like the same issue.

**Comment by gkhanna79** [comment]
Does SOS from the tools folder not suffice @Raviuppa ?

**Comment by ellismg** [comment]
@gkhanna79 When you run dotnet under the debugger and it loads coreclr.dll, there should be an SOS SxS with it, so that you can do `.loadby sos coreclr` in windbg.  Looking at the MSI and ZIP today for windows that isn't the case for the runtime the dotnet commands themselves run on.

**Comment by gkhanna79** [comment]
@ellismg Given that CoreCLR nuget package contains SOS, you can do ".load <path to SOS under tools folder". If you dont find them in the CLI MSI/ZIP, then we need to figure out why that is the case.

**Comment by piotrpMSFT** [comment]
@gkhanna79 this is true, though not intuitive, on dev machines. It's a non-solution in production.

**Comment by piotrpMSFT** [comment]
Also, CLI zip contents are in no way coupled to the runtime used by the app. If we had an SOS in the CLI zip, it would only be usable to debug the CLI and apps that happen to use the same runtime. If we gave folks guidance to use it to debug their apps we'd generally provide only confusion and angst.

If we want to debug apps produced by CLI, we need to have an easy path to correlate that app to its own SoS.dll. The only easy way I know to do this is by including sos with the runtime dependencies of the app.

**Comment by gkhanna79** [comment]
We could package SOS netx to the runtime so thta ".loadby sos coreclr" will pick it up. However, your response above brings up another interesting question - what is the production debugging experience for CLI? Using SOS to debug managed app requires you to know fair bit of runtime internals - I  have not seen folks outside the product team and CSS use SOS for common place production debugging. So, even if package it next to coreclr.dll, it will only help folks like @Raviuppa (who, at that point in time, also know how to load from tools) and not the managed code developers at large.

> If we want to debug apps produced by CLI, we need to have an easy path to correlate that app to its own SoS.dll.

To confirm, is SOS (present in the runtime package under tools folder) not published to the app folder as part of "dotnet publish"?

**Comment by piotrpMSFT** [comment]
sos.dll is now in the shared framework packages. Closing this issue.

**Comment by HppZ** [comment]
where is "shared framework packages" ? how to find specific version of sos.dll?

**Comment by HppZ** [comment]
I use Windbg to debug my UWP app(in Debug mode), lm command shows that coreclr is loaded from C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.1.1_1.1.25305.1_x64__8wekyb3d8bbwe, but no sos.dll exist in this folder, and Windbg did not download it from MS symbol server automatically.
so is there a way to download specific version of those debugging dlls? really need it.

**Comment by Petermarcu** [comment]
That runtime is for UWP apps and not for .NET Core Apps. @zamont can you give pointers on where to get SOS that matches the runtime shipped for UWP?

**Comment by HppZ** [comment]
@zamont I need your help, please.
