### ISSUE TITLE
`dotnet build -n` fails with LNK1112 on x64 machine

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#1040]
On 64-bit Windows 10, with VS 2015 U1 installed and ".NET Command Line Tools (1.0.0)":

```
dotnet new
dotnet restore
dotnet build -n
```

The last command fails with this output:

```
Project test2 will be compiled because expected outputs are missing.

Compiling test2 for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.4449956
Input Assembly: C:\temp\test2\bin\Debug\dnxcore50\test2.dll
Microsoft (R) Incremental Linker Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : warning LNK4044: unrecognized option '/NOLOGO /ERRORREPORT:PROMPT /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT'; ignored
Linking of intermediate files failed.
msvcrt.lib(std_nothrow.obj) : fatal error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'
```

**Comment by livarcocc** [comment]
Are you running from a VS2015 x64 Native Tools Command Prompt? If not, can you try that?

**Comment by brthor** [comment]
:+1: @livarcocc 's answer.

**Comment by AArnott** [comment]
I was not using that window. After 3 attempts at picking the right window (I first found VS2012 x64 Cross Tools command Prompt, then found VS2015 x64 x86 Cross Tools Command Prompt), I finally got a successful run. Note that it still produces a build warning, as shown below.

I had no interest in compiling 32-bit or 64-bit in particular. I just wanted to create a native binary. The fact that I'm on a 64-bit OS making it fail with the VS command prompt that I normally use seems unfortunate. An error that helps me understand what I need to do to solve the problem would be far preferable.

```
Microsoft (R) Incremental Linker Version 14.00.23506.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : warning LNK4044: unrecognized option '/NOLOGO /ERRORREPORT:PROMPT /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT'; ignored
```

**Comment by brthor** [comment]
@AArnott Native is still very much in the early stages. 
Thanks for the feedback on the UX there though :smile: 

The Native Tools cmd prompt issue is unfortunate for usability, and is being tracked here: #301

**Comment by GuardRex** [comment]
@AArnott 

> VS2015 x64 x86 Cross Tools Command Prompt

Where is that? Perhaps, it's an option that I didn't install with VS2015.

@brthor

> Native is still very much in the early stages

... you're referring to the tooling, correct? I mean you don't necessarily expect a Native version of an app that runs fine as an IL version to fail. I was just about to take my Core IL app that ran on Nano last night (perfectly! :tada:) and see if I could get it running as a Native app on Nano.

**Comment by brthor** [comment]
> ... you're referring to the tooling, correct? I mean you don't necessarily expect a Native version of an app that runs fine as an IL version to fail. I was just about to take my Core IL app that ran on Nano last night (perfectly! :tada:) and see if I could get it running as a Native app on Nano.

I am referring to the native portion of the toolchain as a whole. There is no guarantee your app will work.

> Where is that? Perhaps, it's an option that I didn't install with VS2015.
Comes up in search for me.

@AArnott can we close this out?

**Comment by AArnott** [comment]
Yes. Thanks.
