### ISSUE TITLE
`dotnet build -n` skips after `dotnet build`

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#1041]
After building an IL assembly with `dotnet build`, if I decide I want a native image instead of an IL one, I try and it skips because it thinks it has already done the work:

```
dotnet new
dotnet restore
dotnet build
dotnet build -n
```

```
Project test2 was previously compiled. Skipping compilation.
```

**Comment by davidfowl** [comment]
Yes, I'm finding a bunch of bugs with incremental build as well. It's a little aggressive.

/cc @cdmihai

**Comment by cdmihai** [comment]
This means that build would need to check if native output is there when it receives the -n flag. What would be the best way to check if native output exists in the output folder?

**Comment by brthor** [comment]
@cdmihai Native currently outputs to the `native` subdirectory wherever the IL output usually is.

This is to prevent stomping on the IL binary. 

I think you could look in this directory for the binary to determine if you should rebuild.

**Comment by cdmihai** [comment]
Sounds good.

**Comment by cdmihai** [comment]
Is this change still needed, or will the separation of native out of compile address this issue?

**Comment by cdmihai** [comment]
After a discussion with @piotrpMSFT and @davidfowl, native would get pulled out of compile and get called by the user.

This means it is no longer an issue with build, and we can close this issue, right?

**Comment by cdmihai** [comment]
According to the meeting we had, for RTM the users will have to manually call native, MCG, and other compilation pipeline commands. Post RTM we need to design a mechanism where commands can hook to each other to form a build execution graph.
