### ISSUE TITLE
Remove <clear/> from new nuget.config template

### ISSUE THREAD

**Issue by zivkan** [dotnet/cli#10420]
I couldn't find where the nuget.config template is, so I hope creating this issue here is good enough.

`dotnet new nugetconfig` creates a `nuget.config` file with the following content:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="git" value="https://api.git.org/v3/index.json" />
 </packageSources>
</configuration>
```

I propose that the `<clear />` element be commented out by default and the comment above amended appropriately. Consider also commenting out the sample package source.

The reason I ask for this is because using `dotnet new nugetconfig` is a great way to create the file in a test script, which I can then edit using `nuget.exe config -set ....` or `nuget.exe sources -configfile nuget.config add -name ... -source ...`. However, I can't find an easy way to script removing the `<clear />`. Using myself as anecdotal evidence, even if it's not data, I only want to clear the package sources on work projects when I get packages from a curated feed. But for every one of these I create, I create a hundred throw-away projects to investigate/test something where I want to use nuget.org, and therefore don't want to clear the sources list. In these cases the first thing I always do is edit the file and remove the package sources element and children.

Therefore, by not clearing package sources, this becomes a great tool for automation, as nuget.exe doesn't support editing an empty file, so scripts need a way to bootstrap the root element creation.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7581

**Comment by dasMulli** [comment]
Shouldn't this be for https://github.com/dotnet/templating? That's where the template comes from..
and personally, totally agree! first thing I do with it is always to remove the `<clear/>` line..

**Comment by livarcocc** [comment]
That's true that that's where the templates live, but I would appreciate NuGet's opinion on this.
