### ISSUE TITLE
dotnet build Performance not Fast Enough

### ISSUE THREAD

**Issue by aaabbbcccddd00001111** [dotnet/cli#10423]
`dotnet build` performance is not fast enough. It takes up to 4 seconds to build a exe.

If it takes less than 1 second it is fast enough.

**Comment by livarcocc** [comment]
This issue does not really have enough information for us to be actionable.

Usually, perf logs go a long way is helping us understanding what is going on. Also, what version of the SDK are you using.

We did a bunch of perf improvements in the 2.1 timeframe and ended up with a 10x improvement in that release. However, in any particular build, there may be any things (including beyond our control) that may impact your build times.

**Comment by aaabbbcccddd00001111** [comment]
The SDK is .NET Core 2.1 . The Time Elapsed that `dotnet build` write to console after "Build succeeded." can be 00:00:05.78  (5.78 seconds) . It does 7 restores for 7 csproj when it builds. 

For it to be fast enough, Time Elapsed need to be less than 1 second.

**Comment by livarcocc** [comment]
@dsplaisted do we have instructions on how to share perf logs with us?

@aaabbbcccddd00001111 that's still not enough information. Also, saying it should take 1 second is kind of meaningless in the performance context. Again, we need to know where the build time is going as far as msbuild tasks/targets go and see if any of them is taking longer them reasonable given your build and your projects. And then, if so, consider if it is worth optimizing.

Like I said, we saw 10x build time improvements with projects with around 100 P2P references and multiple package references.

Also, is this a fresh build, is this an incremental build when building a leaf project?
