### ISSUE TITLE
dotnet restore failed on private (authenticated) feeds on .NET SDK > v2.2.100

### ISSUE THREAD

**Issue by DoCode** [dotnet/cli#10448]
## Steps to reproduce
`dotnet restore project.proj`

## Expected  behavior
NuGet restore is successful.

## Actual behavior
```
Retrying 'FindPackagesByIdAsyncCore' for source 'https://xxx.xxx.xxx/f/core-dev/api/v2/FindPackagesById()?id='xxx'&semVerLevel=2.0.0'.
Response status code does not indicate success: 401 (Unauthorized).
```

It works with all version before 2.2.100!  
All other versions, also 3.x failed.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7603
