### ISSUE TITLE
dotnet tool aspnet-codegenerator looks for executable at wrong path

### ISSUE THREAD

**Issue by seancpeters** [dotnet/cli#10459]
_From @tbureck on December 8, 2018 23:16_

I'm currently following [this guide](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli#scaffold-identity-into-an-empty-project) in order to scaffold Identity in my existing ASP.NET Core project. When trying to run the scaffolder command with the help option, though, I'm getting this error message:

```
> dotnet aspnet-codegenerator --help
The application to execute does not exist: 'C:\Users\Tim\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.0-rtm-35687\dotnet-aspnet-codegener
ator\2.2.0-rtm-35687\tools\netcoreapp2.1\any\dotnet-aspnet-codegenerator.dll'.
```

I've checked the .dotnet\tools\.store directory and the tool seems to be installed correctly. BUT, it is installed in a `2.2.0` directory instead of the `2.2.0-rtm-35687` directory, which dotnet tool is looking in.

I've opened [a thread on Stackoverflow](https://stackoverflow.com/questions/53676499/dotnet-tool-aspnet-codegenerator-looks-for-executable-at-wrong-path) as well and someone else seems to have the same issue, which is why I'm creating this issue.

Why is it that `dotnet tool` is looking in the `2.2.0-rtm-35687` sub directory instead of the `2.2.0` where it is actually installed?

Edit: my dotnet version is `2.2.100`

_Copied from original issue: aspnet/Scaffolding#932_

**Comment by seancpeters** [comment]
_From @maliming on December 9, 2018 9:37_

I also encountered the same problem.

**Comment by seancpeters** [comment]
_From @guardrex on December 9, 2018 13:25_

I just hit this one, too.

**Comment by tdykstra** [comment]
I hit the same error running through the Razor Pages intro tutorial, except mine is looking for 2.1:

> ~\source\repos\RazorPagesMovie> dotnet tool install --global dotnet-aspnet-codegenerator
> You can invoke the tool using the following command: dotnet-aspnet-codegenerator 
> Tool 'dotnet-aspnet-codegenerator' (version '2.2.0') was successfully installed.

>~\source\repos\RazorPagesMovie> dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
> The application to execute does not exist: 'C:\Users\tdykstra\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.0-rtm-35687\dotnet-aspnet-codegenerator\2.2.0-rtm-35687\tools\netcoreapp2.1\any\dotnet-aspnet-codegenerator.dll'.

**Comment by wli3** [comment]
it should be caused by this https://github.com/dotnet/sdk/issues/2698

Seems 2.2.0 is out, the immediate problem should be fixed.

let me follow up on the authoring side

**Comment by seancpeters** [comment]
@wli3 - I see that dotnet/sdk#2698 is closed due to the fix we worked on. I'd like to close the issue on aspnet/scaffolding, but don't want to close it until this is closed.

**Comment by wli3** [comment]
@seancpeters 
dotnet/sdk#2698 is closed due to https://github.com/dotnet/sdk/pull/2739 is merged (the fix for root cause in SDK) and it will be in 2.1.600 and 2.2.200

The new package has not been pushed yet. Do you think we should close this issue until it is pushed?

**Comment by seancpeters** [comment]
Oh, in that case, let's leave it open for now. Since the sdk issue was closed, I was thinking we could close the entire chain, but open is probably better for now.

**Comment by guardrex** [comment]
Hello @wli3 ... Can you state the workaround/fix for a user prior to the released patch? We're getting a few pings in doc issues as devs try to follow one of our tutorials and hit this.

**Comment by wli3** [comment]
@guardrex use an older version as the following
` dotnet tool install --global dotnet-aspnet-codegenerator --version 2.1.6`

**Comment by drowhunter** [comment]
I was pulling my hair out trying to solve the same problem.  So many issues with net core im almost regretting not staying with Net Framework.

**Comment by wli3** [comment]
2.2.1 is shipped with the fix. Closing
