### ISSUE TITLE
dotnet 2.1.6 publish with --self-contained false produces apphost.exe that does not work

### ISSUE THREAD

**Issue by xavierjohn** [dotnet/cli#10465]
Trying to publish a .net core exe without the runtime using the following command

## Steps to reproduce
dotnet publish --configuration Release --runtime win7-x64 --self-contained false --output c:\outputfolder

## Expected  behavior
Produces a {application}.exe

## Actual behavior
Produces apphost.exe that does not work.

I can run the program using
dotnet.exe application.dll

## Environment data
`dotnet --info` output:

Runtime Environment:
OS Name: Windows
OS Version: 10.0.17134
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
Version: 2.1.6
Commit: 3f4f8eebd8

.NET Core SDKs installed:
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.500 [C:\Program Files\dotnet\sdk]

**Comment by livarcocc** [comment]
This feature only works and is supported starting with 2.2.100.

Please, try with that build and let us know.

**Comment by xavierjohn** [comment]
It works with 2.2 thanks.

.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
