### ISSUE TITLE
Tests besides E2E should not call restore.

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1046]
In general (for most of our tests) a restore step is not necessary.

The test projects which are being restored have already been restored at the beginning of the build.

This issue is tracking removing the unnecessary restores to decrease build times.

cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
:+1:

**Comment by brthor** [comment]
This is checked in. Additionally E2E only calls restore once.
