### ISSUE TITLE
NETSDK1007 error when building solution with ProjectReference tags in specific order

### ISSUE THREAD

**Issue by allanrodriguez** [dotnet/cli#10484]
## Steps to reproduce
1. Build the [attached solution](https://github.com/dotnet/cli/files/2688002/NetSdk1007.zip). It should build successfully.
2. In the NetSdk1007/NetSdk1007.csproj file, switch the position of the two ProjectReference tags such that they look like this:
```
<ItemGroup>
  <ProjectReference Include="..\Dependency.Mocks\Dependency.Mocks.csproj" />
  <ProjectReference Include="..\LibraryUnderTest\LibraryUnderTest.csproj" />
</ItemGroup>
```
3. Rebuild the solution using `dotnet build --no-incremental`.

## Expected  behavior
The solution should build successfully for the .NET Core 2.1 and .NET Framework 4.7.1 platforms as in step 1.

## Actual behavior
Building the solution fails with the error `NETSDK1007: Cannot find project info for 'C:\Projects\NetSdk1007\Dependency\Dependency.csproj'. This can indicate a missing project reference.` The .NET Core build fails but the .NET Framework build succeeds.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.502\

Host (useful for support):

  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:`
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
Strange. I can't repro this. I tried on two separate machines already.

**Comment by livarcocc** [comment]
In your case, can you try running a dotnet restore again and then building to see if this fixes it for you?

**Comment by allanrodriguez** [comment]
My bad, I can't reproduce it either with a clean copy of the repro.

Nevertheless, if I start from step 2 and build the solution, I'll get the error. Switching the ProjectReferences from there will result in the project building successfully.

[Attached](https://github.com/dotnet/cli/files/2688506/NetSdk1007v2.zip) is the above repro starting from step 2; building this from scratch for sure gives me the error on my machine. Running `dotnet restore` didn't help with NETSDK1007 popping up.

**Comment by livarcocc** [comment]
We have been having issues with solution building. Does it repro if you build the NETSDK1007 project directly?

**Comment by allanrodriguez** [comment]
Yeah, I can reproduce it by building only the project.

**Comment by Philippe85** [comment]
Some news on this problem, which causes problems also on .NET 2.2 with Standard 2.0 projects.
See this ticket : [](https://developercommunity.visualstudio.com/content/problem/427643/error-netsdk1007-when-publishing-without-build-a-n.html)
