### ISSUE TITLE
Cannot use `dotnet new` to target older runtimes

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#10492]
I have both .NET Core 3 Preview 1 and .NET Core 2.2 SDKs installed. I want to do this:

```console
dotnet new console --framework netcoreapp2.2 -o app22
```
It doesn't work. I'm not happy using global.json for this scenario. I should be able to target any .NET Core version that I want. If that version isn't supported on my machine currently, I should get instructions on what to do.

Something like this: https://github.com/dotnet/templating/blob/master/README.md#info-for-dotnet-new-users

**Comment by livarcocc** [comment]
This is an old limitation of `dotnet new`.

cc @KathleenDollard @vijayrkn @mlorbetske

**Comment by KathleenDollard** [comment]
+ @Angelos Petropoulos<mailto:angelpe@microsoft.com> and @Sean Peters<mailto:sepeters@microsoft.com>

It is possible to install other versions of templates into a given instance of the CLI. Sean can provide details.

Longer term, we’ve been thinking on ways to have a single “new” experience across CLI versions and better share between the CLI’s installed templates and VS. Such an experience would likely take the form of a global tool. Without getting in to too many details (as I am oof), we’ll need to discuss some of the shipping mechanics for it to be viable.

Also, Sean is the owner of all of the code generation experiences in our group, it’d be better to direct such things to him rather than me.

Thanks,
Mike

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by KathleenDollard** [comment]
Sean,


Are you here this week? I think Angelos is here another day or two. I'd love to whiteboard the parts that might make sense to deliver independently here to align with other discussions about packaging (for example our packing in Visual Studio).


Kathleen

________________________________

**Comment by seancpeters** [comment]
For installing a specific version of a template, using the specific example @richlander indicated in the original post in this thread, run this command:

`dotnet new --install Microsoft.DotNet.Common.ProjectTemplates.2.2::1.0.0-*`

Then if you run `dotnet new console -h`, the framework option section of the output should look like this (assuming you're working with a 3.0 sdk):
```
Options:
  -f|--framework  The target framework for the project.
                      netcoreapp3.0    - Target netcoreapp3.0
                      netcoreapp2.2    - Target netcoreapp2.2
                  Default: netcoreapp3.0
```
Then you'll be able to run the original desired command.

Each sdk ships with only 1 version of each template pack, and each template pack typically only contains support for one framework (but this is up to the author of the pack). With the above, we installed the pack which contains the console template with netcoreapp2.2 support.

**Comment by seancpeters** [comment]
@KathleenDollard - I am here for the rest of the week, but a bit busy. Perhaps we can get together after the holiday? I'll be back on the 2nd.

**Comment by angelos** [comment]
As cool as this feature is, I’m pretty sure you found the wrong @angelos .
The real one would be thrilled to be involved, I’m sure!

**Comment by mairaw** [comment]
Probably this is the right @AngelosP 

Also, what if the person wants to target .NET Framework? Is it possible to install a template for that too?

It would probably be good to cover this scenario in the docs.

**Comment by KevinCathcart** [comment]
The bug for documenting installing older version templates into a new SDK, and using them to target older frameworks is: dotnet/docs#14572

As for if the person wants to target .Net Framework, well that would work if anybody ever created template packages for them. After all `dotnet new nunit --framework net47` works just fine.

Of course, all the usual limitations with regard to building framework targeted packages from the dotnet CLI would apply to trying to build the template result.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#2115
