### ISSUE TITLE
Determine how to version in-box RID graph

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#10496]
For initial bring-up, we will have exactly one version of the RID graph in the .NET Core SDK.

We need to figure out how to prevent breaking changes. By this we mean that we don't want the assets selected in a build to change with an sdk change and no project change. We thought about versioning it by TFM, but there's just one Platforms package today with increasing version for all TFMs.

cc @dsplaisted

**Comment by dsplaisted** [comment]
We decided to stay with a single version of the RID graph in the .NET Core SDK, and assume that we won't make breaking changes to it.  If we do need to make breaking changes in the future, then we could consider conditioning the graph on the target framework.
