### ISSUE TITLE
Install the .NET SDK on Windows Subsystem Linux Ubuntu 18.04 - Reading package lists... Error!

### ISSUE THREAD

**Issue by TothZoltan2018** [dotnet/cli#10505]
## Steps to reproduce
I try to install Install .NET SDK ([instruction here)](https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial#install) to WSL Ubuntu 18.04 ([instruction here](https://docs.microsoft.com/en-us/windows/wsl/install-win10)) ([package here](https://www.microsoft.com/hu-hu/p/ubuntu-1804-lts/9n9tngvndl3q?activetab=pivot%3Aoverviewtab))

## Expected  behavior
Successfull installation of .Net SDK on Ubuntu WSL

## Actual behavior

I could install Ubuntu but I can not install .NET SDK. It looks as if something is wrong with permissions althought the commands I copied from the tutirial use sudo... 
<pre>
tothz@hp-PC:~/repos$ wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
tothz@hp-PC:~/repos$ sudo dpkg -i packages-microsoft-prod.deb
[sudo] password for tothz:
(Reading database ... 28498 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.1) over (1.0-ubuntu18.04.1) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.1) ...
tothz@hp-PC:~/repos$ sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.
tothz@hp-PC:~/repos$ sudo apt-get install apt-transport-https
Reading package lists... Error!
E: Problem renaming the file /var/cache/apt/srcpkgcache.bin.peXWA6 to /var/cache/apt/srcpkgcache.bin - rename (13: Permission denied)
E: Could not open file /var/lib/dpkg/status - open (2: No such file or directory)
E: Problem opening /var/lib/dpkg/status
E: The package lists or status file could not be parsed or opened.
tothz@hp-PC:~/repos$
</pre>

I got some tips such as:
$ sudo rm -fr /var/cache/apt
$ sudo mv /var/lib/dpkg/status /var/lib/dpkg/status-bak  #could fail if it doesn't exist
$ sudo touch /var/lib/dpkg/status
$ sudo apt clean
$ sudo apt update && sudo apt upgrade
$ # try again, probably starting with sudo apt install apt-transport-https,
$ # if that's what you are after

However, all in vain.

## Environment data

My Windows bulid number is: "Microsoft Windows [Version 10.0.17134.471]"

**Comment by livarcocc** [comment]
This looks more like an issue in WSL than the SDK itself. It fails deep inside the dpkg process. Also, this `packages-microsoft-prod.deb` package is not the .NET Core SDK package. Not sure what that is.

**Comment by TothZoltan2018** [comment]
Yes, installation steps failed before SDK package installation. But I copied everything from the microsoft site:
![sdk install steps](https://user-images.githubusercontent.com/44849632/50387561-8fc52580-06ff-11e9-8834-cbfa2a0daf3d.JPG)

**Comment by livarcocc** [comment]
@leecow is case he knows of anything.

**Comment by TothZoltan2018** [comment]
**After I disabled all functions of the third-party antivirus software and firewall**, I reinstalled Ubuntu and executed the "official" steps to install SDK. And it finally **succeeded**. (This process took for almost 40 minutes and during this period my laptop was unprotected, so it's not a perfect way to do it.)

Thank you for your support.

**Comment by leecow** [comment]
@TothZoltan2018 - is the antivirus and firewall software running on Windows or in the WSL environment? Either way, there are likely whitelists in both which can be maintained to enable access to specified domains/uris such as packages.microsoft.com.

**Comment by TothZoltan2018** [comment]
Yes, might be whitelists but I wanted a solution quickly and I disabled
both temporarily for the time of installation.
By the way it was not obvious from the error messages that it was the
trouble. But next time I will check them first! ;-)

Lee Coward <notifications@github.com> ezt írta (időpont: 2019. jan. 2.,
Sze, 19:03):
