### ISSUE TITLE
--build-profile flag should mention if no preconditions exist

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#1050]
If build is run with the `--build-profile` flag and no incremental preconditions are broken, then no message is printed. There should be a message saying all checks were fine.

Observed by @pranavkm here: https://github.com/dotnet/cli/issues/232#issuecomment-175208472

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
