### ISSUE TITLE
Unbound variable `DOTNET_INSTALL_DIR` in `eng/restore-toolset.sh`

### ISSUE THREAD

**Issue by peterhuene** [dotnet/cli#10513]
## Steps to reproduce

1. `git clone https://github.com/dotnet/cli`
2. `cd cli`
2. `./build.sh`
3. `./build.sh`

## Expected  behavior

The second build should succeed.

## Actual behavior

`eng/restore-toolset.sh: line 46: DOTNET_INSTALL_DIR: unbound variable`

## Workaround

`DOTNET_INSTALL_DIR=$(pwd)/.dotnet ./build.sh`

## Environment data

Repros on macOS 10.14 and Ubuntu 16.04.

**Comment by dsplaisted** [comment]
I hit a similar issue on Windows.  I think this was a breaking change in arcade, but the workaround/fix (for Windows at least) is to call InitializeBuildTool before you need to consume the DOTNET_INSTALL_DIR environment variable.

@peterhuene @livarcocc @tmat

**Comment by wli3** [comment]
@livarcocc what is the problem you are aware of? i can also try to fix it

**Comment by livarcocc** [comment]
Arcade has changed to not always call the InstalllDotnetCli function (or something like that) and now we need to call that function explicitly to have this variable always set.

**Comment by livarcocc** [comment]
whatever @dsplaisted said above. I read his comment after I wrote mine.

**Comment by livarcocc** [comment]
This should have been fixed by https://github.com/dotnet/cli/pull/10653.

**Comment by wli3** [comment]
Wait that check in is to disable flaky test. this is for cannot run ./build.sh twice wrong number?

**Comment by livarcocc** [comment]
There is another commit there. I just fixed it together in the same PR, but separate commits. This was the commit for the CLI: https://github.com/dotnet/cli/pull/10653/commits/01303586fc03aedfd5d703cdc7a858fa9a7a798c
