### ISSUE TITLE
File lists in targeting packs and runtime packs

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#10537]
In dotnet/sdk#2774, we are starting by globbing all of the reference assemblies. In the past, this has been a source of performance problems so we should instead be consuming a file list like the traditional redist list.

We can also leverage this to allow for the WindowsDesktop targeting pack to provide distinct profiles for WPF, Winforms, or both: #10536

**Comment by nguerrera** [comment]
We likely also want a file list in the runtime pack.

**Comment by nguerrera** [comment]
The current globbing of runtime pack has caused us to put incorrect files into deps.json a couple of times.

**Comment by dsplaisted** [comment]
Issues tracking adding manifests:

- .NET Core and WindowsDesktop runtime packs: https://github.com/dotnet/core-setup/issues/6409
- ASP.NET targeting pack: https://github.com/aspnet/AspNetCore/issues/10215
- ASP.NET runtime pack: https://github.com/aspnet/AspNetCore/issues/10216

**Comment by natemcmaster** [comment]
What is the timeframe for getting this done? preview6 is already overbooked, and I'm looking to punt work to preview7 if we can.

**Comment by nguerrera** [comment]
I think preview 7 is fine for ASP.NET IMHO. I would really like the targeting pack info with the profiles in preview 6 if possible for the windows desktop SDK. That changes the experience so it is better to have customers try it sooner.

**Comment by dsplaisted** [comment]
Closing this in favor of #10581 for targeting packs and #10442 for runtime packs
