### ISSUE TITLE
"dotnet.exe test" by default looks for test dll under "bin\Release" even for x64 projects.

### ISSUE THREAD

**Issue by ShiveshSuman** [dotnet/cli#10539]
## Steps to reproduce

Build a A dotnet core project with x64 build configuration. Try to run tests using the following command:

"c:\program files\dotnet\dotnet.exe" test <full path to project file ending with .csproj> --configuration Release --no-build Category=<Test category> --logger trx --results-directory <path to results directory>

## Expected  behavior

Test should run. If there is something wrong the output of '"c:\program files\dotnet\dotnet.exe" test' should be printed out on the command prompt.

## Actual behavior

We see the following error and help output:

The test source file "C:\InstallKits\VsBuildAgent\_work\r1\a\_abcd-Nightly Build\drop\tests\Integration\abcdefg.abc.Tests.Integration\bin\Release\netcoreapp2.1\XYZ.ABC.Tests.Integration.dll" provided was not found.
Usage: vstest.console.exe [Arguments] [Options] [[--] <RunSettings arguments>...]]

Description: Runs tests from the specified files.

Arguments:

[TestFileNames]
      Run tests from the specified files. Separate multiple test file names
      by spaces.
      Examples: mytestproject.dll
                mytestproject.dll myothertestproject.exe

Options:
.
.
.
--Platform|/Platform:<Platform type>
      Target platform architecture to be used for test execution.
      Valid values are x86, x64 and ARM.

<other command line options for VSTest.console.exe

There are clearly two things wrong here:

* There is not support for --Platform switch by the 'dotnet test' tool. (though obviously the help output, which was that for VStest.Console listed this option.)

* The help output is obviously misleading and perhaps incorrect. It is not clear if this is by design or an oversight.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## Workaround

We found the following workaround: since there was no way to specify the build platform on the command line (we did not explore the test settings file option), we tried to set configuration to 'x64\Release' instead of 'Release'. And this seemed to do the trick. However, this at best seems like a workaround or a stopgap measure. Is the lack of support for platform switch intentional? And why does the help output for VStest.Console gets printed upon the failure?

**Comment by livarcocc** [comment]
Yes. The platform is intentionally left out. You can use -p:Platform=x64 as a parameter to set the msbuild property directly if you want.

As for why the vstest.console output is displayed, please file an issue under github.com/microsoft/vstest.
