### ISSUE TITLE
latest 3.0 sdk has issue resolving project argument

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#10554]
## Steps to reproduce

```
cd /tmp
mkdir lib
cd lib
dotnet new classlib
cd ..
dotnet build lib
```

## Expected  behavior

lib project should build

## Actual behavior

project isn't properly resolved, note: `lib/lib/lib.csproj`
```
/tmp/lib/lib/lib.csproj : error MSB4025: The project file could not be loaded. Could not find a part of the path '/tmp/lib/lib/lib.csproj'.
```
## Additional info

This regression occurs on 3.0 daily since 5 Dec.

**Comment by livarcocc** [comment]
This is a regression on msbuild that was fixed here: https://github.com/Microsoft/msbuild/pull/4039.
