### ISSUE TITLE
dotnet build don't perform "restore" anymore

### ISSUE THREAD

**Issue by DGuidi** [dotnet/cli#10555]
## Steps to reproduce

1. Using Visual Studio 2017, clear nuget cache
![screenshot_44](https://user-images.githubusercontent.com/216627/50827257-48b17400-133e-11e9-9117-81d35a1ae7fa.png) or delete manually `X:\Users\me\.nuget` folder
1. execute `dotnet build MySolution.sln` from a command line

## Expected  behavior
nuget cache restored correctly - see [docs](https://docs.microsoft.com/it-it/dotnet/core/tools/dotnet-build?tabs=netcore2x) - and build successfully completed

## Actual behavior
nuget cache not restored correctly and build errors. 

## Additional info
Visual Studio 2017 build works correctly, and after vs build all subsequent command line builds works as expected.  
I've verified this issue also with a colleague of mine, and I'm pretty sure that sdk 2.1 worked.

## Workaround
using `dotnet build --force` instead of regular `dotnet build` fixed problem

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
This seems like incremental restore is kicking in and avoiding the restore. Will move to nuget to be further investigated.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7677

**Comment by rrelyea** [comment]
@DGuidi  - can you give us a repro project?

but first, this sounds like one of the projects may use packages.config.
Packages.config only can be restored by nuget.exe restore or VS restore.
dotnet restore doesn't support packages.config.

(we are working to make a better error experience to at least give you a heads up when trying to restore any projects w/ packages.config)

thoughts?
