### ISSUE TITLE
Use finalized targeting pack format

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10581]
With https://github.com/dotnet/sdk/pull/2774, we are resolving assets from "targeting packs", but we are using the existing packages (such as Microsoft.NETCore.App) as the targeting packs.  We plan to use different packages with different layouts as the real targeting packs.  Along with that, we will need to update the asset resolution logic to account for this.

See [dotnet/designs#50](https://github.com/dotnet/designs/pull/50/files?short_path=ebf265d#diff-ebf265d0476041dd8cab82fa24ab5b0e) for the current design for the targeting pack layout.

Items that should be resolved from targeting packs:

- [x] Assembly references (from `data/FrameworkList.xml`)
- [x] Platform manifests for conflict resolution (from `data/PlatformManifest.txt`)
- [x] Remove code for `PackageConflictPreferredPackages` (use `PackageConflictOverrides` instead)
  - See this comment: https://github.com/dotnet/sdk/issues/2937#issuecomment-463420216
- [x] `PackageConflictOverrides` (from `data/PackageOverrides.txt`)

Status of having these items in targeting packs:

- Microsoft.NETCore.App.Ref
  - [x] `FrameworkList.xml`
  - [x] `PlatformManifest.txt`
  - [x] `PackageOverrides.txt` - https://github.com/dotnet/core-setup/issues/6507
- Microsoft.WindowsDesktop.App.Ref
  - [x] `FrameworkList.xml`
  - [x] `PlatformManifest.txt`
  - [x] `PackageOverrides.txt` - https://github.com/dotnet/core-setup/issues/6507
- NETStandard.Library.Ref (v2.1)
  - [x] `FrameworkList.xml`
  - [x] ~~`PlatformManifest.txt`~~ (doesn't apply to .NET Standard)
  - [x] `PackageOverrides.txt` - https://github.com/dotnet/core-setup/issues/6507
- Microsoft.AspNetCore.App.Ref
  - [x] `FrameworkList.xml` - https://github.com/aspnet/AspNetCore/issues/10215
  - [x] `PlatformManifest.txt`
  - [x] `PackageOverrides.txt`

**Comment by nguerrera** [comment]
* Platform manifest is already found by convention.
* https://github.com/dotnet/sdk/issues/2937 tracks the packageconflict items.

**Comment by livarcocc** [comment]
@dsplaisted to check and close if done. Otherwise specify left over work.
