### ISSUE TITLE
Command Output Forwarding misses some output

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1059]
During NuGet push we faced an issue where NuGet was returning '1' despite no error messages. It was later discovered that this was due to a WriteLine from NuGet not being forwarded out through the CLI. I suspect this has to do with stream flushing behavior near process exit. We need to improve StreamForwarderTests to cover these scenarios.

**Comment by bricelam** [comment]
Possibly related to #925

**Comment by piotrpMSFT** [comment]
@brthor, can you take a pass at this once #999 goes in?

**Comment by brthor** [comment]
Looking at this and #925 now

**Comment by brthor** [comment]
Tried to repro this in the following ways:
* A command which throws unhandled exceptions, WriteLining before
* A command which handles exceptions and prints messages, with Writes before and after
* Interleaving StdOut and StdErr in a command
* Nesting a command two processes deep and printing 100,000+ Lines

In all cases I compared output to the output of the process if run directly (`dotnet cmd` vs `dotnet-cmd.exe`). 

I did not see messages being dropped in any cases. I did see significant misordering of the writes, more in line with the issue in #925 

Would recommend closing this out unless we see it repro again.

**Comment by brthor** [comment]
Giving this more thought,

With the issue I found in StreamForwarder, where the Read operation would block until it's buffer was full, it is possible that a message would get dropped if the driver or coreclr crashed before that read stopped blocking (Which is when child process exits). 

Although unlikely, in all of the craziness in that week I wouldn't be very surprised.

**Comment by brthor** [comment]
#925 is tracking the fix currently in PR. 

Let's reopen this if we see it happen again.
