### ISSUE TITLE
dotnet-api

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#106]
dotnet-api
===========

**NAME** 
dotnet-api -- Prints basic API-level documentation for a given namespace(s), type or member.

**SYNOPSIS**
dotnet api [options]

**DESCRIPTION**
The api command provides a convenient and low-tech and offline (!) way of getting documentation for a given set of restored NuGet packages (whatever you have on your machine). When you are developing an app or library and are not sure about the set of APIs available, it is very useful to see the set of types or members that you can use, printed to the console/terminal.

I'm a cheapskate, too. I'm not going to pay for wifi on the airplane when all I need is the set of API signatures for System.String.

By default, this command doesn't rely on an external API service. It can provide more API information if you opt into the `--online` mode. In that mode, it doesn't rely on the arbitrary set of NuGet packages you have on your machine, but provides with information about "the world".

**Options**

-n, --namespaces
Prints the list of namespaces

[namespace]
Prints out the list of types for a given namepspace.

[type | member]
Prints out the list of members and/or signtures/overloads for a give type/member.

-o, --online
By default, the tool relies on locally resident NuGet packages for metadata. Given this command, the tool can provide access to a much broader set of metdata, provided by a .NET Foundation-provided service.

**Comment by krwq** [comment]
For the online version we can use this:
http://packagesearch.azurewebsites.net/Search/?searchTerm=XmlReader

**Comment by krwq** [comment]
Online version since practically no work: https://github.com/dotnet/cli/pull/475

**Comment by blackdwarf** [comment]
Closing this as command such as this would be an excellent candidate for an extension. If needed, please reopen.
