### ISSUE TITLE
Support SemVer2.0.0 for SDK resolution

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/cli#10608]
Arcade has started the transition to using SemVer2.0.0 versions.

Current SDK resolution does not yet support SemVer2.0.0

https://github.com/dotnet/cli/blob/f38d1472d05573158f52ec30f5163fe0316ede7b/src/Microsoft.DotNet.MSBuildSdkResolver/FXVersion.cs#L6-L9

See also dotnet/core-setup#4952 & dotnet/core-setup#4953

**Comment by sdmaclea** [comment]
@livarcocc @nguerrera I am think of using C# regex to implement this.  Is there any reasons I should not use regex in this code?

**Comment by nguerrera** [comment]
I think we should keep it as a mostly straight forward port of fx_ver_t. 

In my opinion, regexes are hard to maintain over the long haul and often lead to poor performance.

**Comment by sdmaclea** [comment]
> I think we should keep it as a mostly straight forward port of fx_ver_t.
> In my opinion, regexes are hard to maintain over the long haul and often lead to poor performance.

I was half way through writing the test cases for the regex implementation. When your comment appeared.

Below is the regex parser implementation.  It feels very clean and maintainable to me.  Of course the regex expression is the most complicated part.

The regex is long, but with an editor with parenthesis matching it is relatively easy to parse.

```C#
public static bool TryParse(string fxVersionString, out FXVersion version)
{
    version = null;
    
    // Match string to SemVer2.0.0 rules
    // X.Y.Z{-<prerelease>}{+<build>}
    // X, Y, Z are unsigned integers w/o leading zeros
    // prerelease and build non-empty set of non-empty identifiers separated by '.'
    // prerelease identifiers must alpha numeric or unsigned integers w/o leading zeros
    // build identifiers must alpha numeric or unsigned integers
    Regex v = new Regex(@"^(?<Major>(?:[1-9][0-9]*)|0)\.(?<Minor>(?:[1-9][0-9]*)|0)\.(?<Patch>(?:[1-9][0-9]*)|0)(?<Pre>-(?:(?:[1-9a-zA-Z\-][0-9a-zA-Z\-]*)|(?:0(?:[0-9]*[a-zA-Z\-][0-9a-zA-Z\-]*)?))(?:\.(?:(?:[1-9a-zA-Z\-][0-9a-zA-Z\-]*)|(?:0(?:[0-9]*[a-zA-Z\-][0-9a-zA-Z\-]*)?)))*)?(?<Build>\+[0-9a-zA-Z\-]+(?:\.[0-9a-zA-Z\-]+)*)?$");
    
    Match m = v.Match(fxVersionString);
    bool success = m.Success;
    
    if (success)
    {
        int major = int.Parse(m.Groups["Major"].Value);
        int minor = int.Parse(m.Groups["Minor"].Value);
        int patch = int.Parse(m.Groups["Patch"].Value);
        string pre = m.Groups["Pre"].Value;
        string build = m.Groups["Build"].Value;

        version = new FXVersion(major, minor, patch, pre, build);
    }

    return success;
}
```

I tried to make it performant with by using no backtracking.  It is possible hand written code would be faster, but I suspect performance here is irrelevant.

If you wanted simpler regex expressions, we could make it multiple passes closer to the new `fx_ver_t`

**Comment by nguerrera** [comment]
> It feels very clean and maintainable to me

This is obviously subjective, but I do not. 😆

**Comment by nguerrera** [comment]
What is wrong with just porting the code from fx_ver_t to here as we did the first time around? Correctness here is defined by interpreting the sdk versions same as hostfxr.

Why doesn't https://github.com/dotnet/core-setup/pull/4953 use https://en.cppreference.com/w/cpp/regex/regex_match ?

> I was half way through writing the test cases for the regex implementation

The test cases should be the same regardless of implementation, right?

**Comment by sdmaclea** [comment]
> What is wrong with just porting the code from fx_ver_t to here as we did the first time around?

C# has more high level constructs it seems the code could be simpler if we weren't forced to exactly match.
 
> Why doesn't dotnet/core-setup#4953 use https://en.cppreference.com/w/cpp/regex/regex_match ?

I failed to consider it because I forgot it was introduced in C++11.  
If it worked reasonably well with pal::string_t, I would prefer it.  I am guessing pal::string_t adds enough complexity that it is not worth it.

> The test cases should be the same regardless of implementation, right?

Correct.  I was porting the C++ tests to C#, copying the cases verbatim.

**Comment by sdmaclea** [comment]
I am drafting code closer to the C++ code to see what it will look like.

**Comment by sdmaclea** [comment]
Here is the code with a more direct port from C++

```C#
private static bool validIdentifier(string id, bool buildMeta)
{
    if (string.IsNullOrEmpty(id))
    {
        // Identifier must not be empty
        return false;
    }

    if (id.FindFirstNotOf("-0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", 0) != -1)
    {
        // ids must be of the set [0-9a-zA-Z.-]
        return false;
    }

    if (!buildMeta && id.Substring(0,1) == "0" && id.Length > 1 && id.FindFirstNotOf("0123456789", 1) == -1)
    {
        // numeric identifiers must not be padded with 0s
        return false;
    }
    return true;
}

private static bool validIdentifiers(string ids)
{
    if (string.IsNullOrEmpty(ids))
    {
        return true;
    }

    bool prerelease = ids.Substring(0, 1) == "-";
    bool buildMeta = ids.Substring(0, 1) == "+";

    if (!(prerelease || buildMeta))
    {
        // ids must start with '-' or '+' for prerelease & build respectively
        return false;
    }

    foreach (string id in ids.Substring(1).Split("."))
    {
        if (!validIdentifier(id, buildMeta))
        {
            return false;
        }
    }

    return true;
}

public static bool TryParse(string fxVersionString, out FXVersion FXVersion)
{
    FXVersion = null;
    if (string.IsNullOrEmpty(fxVersionString))
    {
        return false;
    }

    int majorSeparator = fxVersionString.IndexOf(".");
    if (majorSeparator == -1)
    {
        return false;
    }

    int major = 0;
    if (!int.TryParse(fxVersionString.Substring(0, majorSeparator), out major))
    {
        return false;
    }
    if (major != 0 && fxVersionString.Substring(0, 1) == "0")
    {
        return false;
    }

    int minorStart = majorSeparator + 1;
    int minorSeparator = fxVersionString.IndexOf(".", minorStart);
    if (minorSeparator == -1)
    {
        return false;
    }

    int minor = 0;
    if (!int.TryParse(fxVersionString.Substring(minorStart, minorSeparator - minorStart), out minor))
    {
        return false;
    }
    if (minor != 0 && fxVersionString.Substring(minorStart, 1) == "0")
    {
        return false;
    }

    int patch = 0;
    int patchStart = minorSeparator + 1;
    int patchSeparator = fxVersionString.FindFirstNotOf("0123456789", patchStart);
    if (patchSeparator == -1)
    {
        if (!int.TryParse(fxVersionString.Substring(patchStart), out patch))
        {
            return false;
        }
        if (patch != 0 && fxVersionString.Substring(patchStart, 1) == "0")
        {
            return false;
        }

        FXVersion = new FXVersion(major, minor, patch);
        return true;
    }

    if (!int.TryParse(fxVersionString.Substring(patchStart, patchSeparator - patchStart), out patch))
    {
        return false;
    }
    if (patch != 0 && fxVersionString.Substring(patchStart, 1) == "0")
    {
        return false;
    }

    int preStart = patchSeparator;
    int preSeparator = fxVersionString.IndexOf("+", preStart);
    
    string pre = (preSeparator == -1) ? fxVersionString.Substring(preStart) : fxVersionString.Substring(preStart, preSeparator - preStart);

    if (!validIdentifiers(pre))
    {
        return false;
    }

    string build = "";
    if (preSeparator != -1)
    {
        build = fxVersionString.Substring(preSeparator);
        if (!validIdentifiers(build))
        {
            return false;
        }
    }
        
    FXVersion = new FXVersion(major, minor, patch, pre, build);

    return true;
}
```

**Comment by nguerrera** [comment]
Looks fine to me. I would just capitalize `valid` to match C# convention.

**Comment by nguerrera** [comment]
Now might be a good time to push on https://github.com/dotnet/corefx/issues/13526

**Comment by nguerrera** [comment]
Aside: There is a lot of allocation in this routine, but I suspect it is already this way from the previous port. Spans could help, but this code needs to run on net472 without any non-BCL dependencies.
