### ISSUE TITLE
Add scaffolding for Vue.js SPA

### ISSUE THREAD

**Issue by snobu** [dotnet/cli#10615]
Please consider adding [Vue.js ](https://vuejs.org/) SPA scaffolding. Vue is popular enough to deserve its own scaffolding entry in the dotnet CLI. Right now only React and Angular SPAs are being generated.

```bash
$ dotnet new | grep SPA
ASP.NET Core with Angular                      angular            [C#]          Web/MVC/SPA
ASP.NET Core with React.js                     react              [C#]          Web/MVC/SPA
ASP.NET Core with React.js and Redux           reactredux         [C#]          Web/MVC/SPA
```

**Comment by livarcocc** [comment]
This issue was moved to aspnet/AspNetCore#6762
