### ISSUE TITLE
Insert new nuget with NuGet.Packaging.Core breaking change

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#10628]
- [x] dotnet-migrate branding update
- [x] Finish update of dotnet-migrate
- [x] Queue SDK 2.2.2xxx without test
- [x] Insert SDK 2.2.2xxx to CLI SDK 2.2.2xxx with new nuget and new dotnet-migrate
- [x] Update stage 0 in SDK 2.2.2xxx in new nuget insertion https://github.com/dotnet/sdk/pull/2917
- [x] Update SDK back to CLI  https://github.com/dotnet/cli/pull/10745

--------------
- [x] Queue SDK 2.1.6xxx without test
- [x] Insert SDK 2.1.6xxx to CLI SDK 2.1.6xxx with new nuget and new dotnet-migrate
- [x] Update stage 0 in SDK 2.1.6xxx in new nuget insertion
- [x] Update SDK back to CLI https://github.com/dotnet/cli/pull/10741 
--------------
- [x] Queue SDK 3.0.1xx without test 
- [x] Insert SDK 3.0.1xx to CLI SDK 3.0.1xx with new nuget and new dotnet-migrate https://github.com/dotnet/cli/pull/10818
- [x] Insert CLI to ToolSet
- [x] Insert ToolSet to core-sdk
- [x] Update stage 0 in SDK 3.0.1xx in new nuget insertion https://github.com/dotnet/sdk/pull/2968

**Comment by wli3** [comment]
We will not take this nuget change right before preview 2. But i will do the same dance after preview 2 is shipped

**Comment by nguerrera** [comment]
Set milestone to logically earliest impacted release.

**Comment by jainaashish** [comment]
Created new set of  NuGet PRs for preview3 of 2.1.6xx and 2.2.2xx branches. Let us know if we also need to create another PR for 3.0.

**Comment by wli3** [comment]
preview 2 is out, i can start to work on it again

**Comment by wli3** [comment]
New PRs

.NET Core CLI

https://github.com/dotnet/cli/pull/10680

https://github.com/dotnet/cli/pull/10681

 

.NET Core SDK

https://github.com/dotnet/sdk/pull/2891

https://github.com/dotnet/sdk/pull/2892

**Comment by livarcocc** [comment]
This isn't arcade, this is RepoToolset, which is not being maintained anymore. It is arcade's predecessor.

**Comment by wli3** [comment]
So repotoolset(pre arcade) -> Microsoft.DotNet.Build.Tasks.Feed (in arcade repo) -> https://github.com/dotnet/buildtools 

I need to update the world

**Comment by wli3** [comment]
Update https://github.com/dotnet/buildtools is also not easy. new nuget require netstandard2.0+ and net472+. I need to update all project to it

**Comment by ViktorHofer** [comment]
Why do you want to update buildtools? Most repos won't use it anymore.

**Comment by wli3** [comment]
@ViktorHofer repotoolset used package `Microsoft.DotNet.Build.Tasks.Feed`. I believe it is from buildtools no?

**Comment by wli3** [comment]
@ViktorHofer for get one later, `Microsoft.DotNet.Build.Tasks.Feed` reference  `Microsoft.DotNet.VersionTools` which is in buildtools

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/pull/2899 is for master CLI
