### ISSUE TITLE
Update dotnet-install.sh (and https://dot.net/v1/dotnet-install.sh) to allow other distros

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#10645]
_From @danmosemsft on January 21, 2019 6:3_

Repos using Arcade bootstrap with `eng/common/tools.sh` which bootstraps dotnet using a script from `https://dot.net/v1/dotnet-install.sh`. The script will fail on ubuntu 18.10.

corefxlab has its own (out of date) copy of this file, which I already updated here
https://github.com/dotnet/corefxlab/pull/2636

A similar change needs to go into `https://dot.net/v1/dotnet-install.sh` but I do not know where that file comes from. It is referenced here:

```
eng/common/tools.sh:  local install_script_url="https://dot.net/v1/dotnet-install.sh"
```
buildtools has its own
```
buildtools/bootstrap/bootstrap.sh:    download "https://raw.githubusercontent.com/dotnet/cli/$dotNetInstallBranch/scripts/obtain/dotnet-install.sh" "$dotnetInstallPath"
```

_Copied from original issue: dotnet/arcade#1848_

**Comment by livarcocc** [comment]
I am not sure this script, which is an official install vehicle, should support acquisition of bits on unsupported distros. Unless we are saying that the distro agnostic bits are supported on said distros. Is that the case?

**Comment by danmosemsft** [comment]
I didn't realize this script is for production use also. I don't want to increase the support matrix. But I think it should be OK to work in our repos on arbitrary distros if you support yourself. As well, that helps give us indirect coverage of possible upcoming problems with new distro versions.

Maybe this script should have a flag `--include_unsupported_distros` or similar that the arcade machinery could set, but would not be set in regular deployment.

**Comment by johnbeisner** [comment]
https://dot.net/v1/dotnet-install.sh does indeed support Ubuntu 18.10

Command:
jbeisner@jbeisnerU1810-001:~$ ./dotnet-install.sh -version 3.0.100-preview6-011829 -verbose

Partial Output:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-011829/dotnet-sdk-3.0.100-preview6-011829-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-011829/dotnet-sdk-3.0.100-preview6-011829-linux-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/jbeisner/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
```
