### ISSUE TITLE
.NET Core 3.0 SDK preview breaks dependencies

### ISSUE THREAD

**Issue by firelizzard18** [dotnet/cli#10644]
I have a project that has `System.Runtime.InteropServices` in its dependency graph. I can't share the 
project itself. Below is part of the `csproj`.

If I build this project (on Windows) with .NET Core 2.2 SDK, everything works. If I build it with .NET Core 3.0 SDK (preview), the build artifacts are missing `System.Runtime.InteropServices.dll`, which breaks my application.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <Reference Include="System.ServiceProcess" />
    <Reference Include="System.Transactions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.Elm" Version="0.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.HttpSys" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.1.1" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.4" />
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.5.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- lots of <ProjectReference>s -->
  </ItemGroup>

</Project>
```

**Comment by peterhuene** [comment]
Hi @firelizzard18.  Thank you for reporting this issue to us.  I'll investigate and see if I can determine the cause.

**Comment by peterhuene** [comment]
I am seeing `System.Runtime.InteropServices.dll` in both my build and publish output with `3.0.100-preview-009812`.

Steps I took:

* `dotnet new console`
* replaced project file with the above project file
* `dotnet build` or `dotnet publish`

Are you able to reproduce it with just the project file you've provided?

If so, would you mind following my repro steps to create a new project with the above contents and append the `/bl` option to either the `dotnet build` or `dotnet publish` and then emailing the resulting `MSBuild.binlog` file (found in the project directory) to me at pehuene@microsoft.com?  Be aware that the binlog will contain your environment variables, so please ensure there is no sensitive information in your environment prior to collecting the binlog.

Thanks!

**Comment by peterhuene** [comment]
Hi @firelizzard18.  Are you still able to reproduce this issue?

Thanks!

**Comment by firelizzard18** [comment]
No, I have not been able to reproduce the issue. I'll reopen the issue if it reoccurs.
