### ISSUE TITLE
dotnet command line argument to terminate remaining build processes that are finished but dont exit

### ISSUE THREAD

**Issue by CreativeHouseDotOrg** [dotnet/cli#10642]
### Is your feature request related to a problem? Please describe.
I'm am trying to `build` and `publish`... but unfortunately there are hanging processes in Task Manager .NET Core Host that lead to a publish error if i try to `dotnet publish`

### Describe the solution you'd like
I want the Remaining Tasks to close after the build OR publish process has ended.

### Describe alternatives you've considered
Since now i've been terminating them by hand, it would be good to have a `dotnet <command>` to terminate all open .Net Core Hosts that remain.

### Additional context

Here is a Screenshot of the remaining Tasks:

![1](https://user-images.githubusercontent.com/4038603/51504064-f1e87780-1dde-11e9-8ebd-1424a7654113.PNG)

![unbenannt](https://user-images.githubusercontent.com/4038603/51504000-9f0ec000-1dde-11e9-8419-0216e6945290.PNG)

**Comment by livarcocc** [comment]
This is by design.

These are our long running processes (MSBuild node reuse, VBCSCompiler and Razor compiler). They are used to improve performance by avoiding paying for startup time all the time.

What errors are you getting that you believe this is the cause?

cc @peterhuene

**Comment by peterhuene** [comment]
@CreativeHouseDotOrg 

Does the command `dotnet build-server shutdown` help terminate these processes?

**Comment by CreativeHouseDotOrg** [comment]
@livarcocc 
I am building my apps in NPM Console inside Visual Studio Community 2017 and everytime i try to call the publish command after the build command (that seems to be finished) but the output shows an error that another process is being used and it tries to "retry" with a time counter (trying again in #Seconds)

**Comment by CreativeHouseDotOrg** [comment]
@peterhuene You are a Hero!! +1 +1 +1

`dotnet build-server shutdown` is exactly what I'm looking for!

Thank you very much!

Creative regards!
