### ISSUE TITLE
MacOS runtime pkg installer does not include AspNetCore runtime

### ISSUE THREAD

**Issue by spozniak** [dotnet/cli#10649]
## Steps to reproduce
Download and install 
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.1-macos-x64-installer
or
https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.1-macos-x64-installer

## Expected  behavior
Should contain two AspNetCore runtimes
`Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]`
`Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]`

## Actual behavior
No AspNetCore shared runtimes installed. Because of that DotNetCore application fails with an error:

> It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.All', version '2.2.0' was not found.
>  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/
>  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download

As workaround it is possible to get them from binaries https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-2.2.1-macos-x64-asp.net-core-runtime-binaries
This issue is similar to: https://github.com/dotnet/cli/issues/8529 but is related to runtime installer.

## Environment data
`dotnet --info` output:

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This is by design at the moment. We don't have a runtime installer that contains all the runtimes. They must be acquired separately.

If you would like to discuss this further, please, file an issue under dotnet/core-setup, that's the repo where the runtime installers are produced.

cc @leecow

**Comment by leecow** [comment]
To clarify a little. The aspnet-core-runtime packages and installers do contain both the asp and netcore runtimes. Because the aspnetcore runtime is primarily an execution package and the Mac a development platform, we haven't created a single runtime installer for the Mac. The aspnet-core-runtime tar.gz for Mac does carry both.

**Comment by spozniak** [comment]
Ok, thank you for clarification.
