### ISSUE TITLE
dotnet/cli Installation Bundle

### ISSUE THREAD

**Issue by robmen** [dotnet/cli#1064]
The [Getting Started](http://dotnet.github.io/getting-started/) page has these two "Oh, by the way..." requirements for installing:

1. You will need to install Visual C++ Redistributable for Visual Studio 2015 as well.
2. If you are using Windows 7 or Windows Server 2008 you will also need to install Visual C++ Redistributable for Visual Studio 2012 Update 4 too.

Also, the dotnet/cli MSI package embeds the cabinet to have a single file for internet distribution. The embedded cabinet are a complete waste of space on the users machine.

To fix both issues, I'd like to develop a Bundle (based on the WiX Burn technology) for the dotnet/cli to wrap the MSI package and download+install the pre-reqs for the appropriate OS.

If that sounds good, please feel free to assign this issue to me.

**Comment by piotrpMSFT** [comment]
@schellap @gkhanna79 do we still require VC++ to be installed? Or has @schellap removed these dependencies through static linking.

Even if they're not needed, I'd be quite happy to have @robmen take a pass at our MSI. Thanks for the offer!

@robmen have you found any reliable technology for testing MSIs in CI that doesn't require flattening the VM when we're done? I was hoping to use App-V to do this, but it seems that creating an AppContainer both requires Admin access and mutates machine state during the installation...

**Comment by piotrpMSFT** [comment]
@robmen, I cannot assign the issue to you because of github organization requirements. @joshfree is there a trick for assigning issue to folks from outside our org?

**Comment by robmen** [comment]
Forgot about not being able to assign outside of the team. Frustrates me on [wixtoolset/issues](http://github.com/wixtoolset/issues) as well.

Anyway, if you're interested in a Bundle (and I do highly recommend it when shipping software over the internet), let me know and I can get the MSI wrapped up over the next couple days. Then any remaining CRTs can be added.

**Comment by robmen** [comment]
Oh, and I don't have anything better for testing MSIs than VMs at this point. Save/check points are your friend.

**Comment by piotrpMSFT** [comment]
Thanks. Save/checkpoint adds a lot of complexity to CI... someday/maybe...

**Comment by piotrpMSFT** [comment]
@Petermarcu, @Sridhar-MS  can  you weigh in on bundle?

**Comment by Sridhar-MS** [comment]
We longer require to chain VC++ redist MSI. @schellap has made changes to statically link any CRT dependencies. So we may not need to bundle the MSI with pre-reqs.

@blackdwarf Can you remove the VC++ redist pre-reqs from getting started doc?

@robmen But still take a pass at our MSI. I feel it is very rudimentary at this stage (but helped to get us going quickly). If we can optimize on embedded cabinets to save user space I am all for it.

/cc: @joeloff @jhendrixMSFT

**Comment by gkhanna79** [comment]
@schellap I thought you were yet to make ILC side of changes and then make changes for static linking for the output of --native. Is this work done? 

@Sridhar-MS Without the above, we cannot remove the dependency.

**Comment by brthor** [comment]
@gkhanna79 Does Native no longer have the dependency on a full VS2015 install?

**Comment by schellap** [comment]
We still compile and link with VS for dotnet native. Only the corehost dependency on VS is not there, as it is self contained now with the CRT.

**Comment by robmen** [comment]
I believe the Bundle will add value independent of VCRedist (although Bundle adds **a lot** of value if/while VCRedist is still needed).

If you're good shipping a Bundle (.exe) instead of naked .msi (something I recommend on the internet anyway) then I'd be happy to get it built for you real quick... but someone else would probably need to update the publish scripts (I don't have great way to test them).

PS: I took a spin through much of the MSI. Sent some recommended fixes. Still some other stuff could probably be done. :smile_cat:

**Comment by Petermarcu** [comment]
@robmen , Thanks for jumping in! :) Having a bundle would be a great addition in my mind.

**Comment by joeloff** [comment]
Is this a bundle for just the CLI? We are currently working on a bundle that will carry the CLI and tooling though that's primarily geared toward VS2015, though without VS it should just end up dropping the CLI

**Comment by robmen** [comment]
@joeloff I would recommend creating a Bundle for the pieces you expect users to install. If you only expect a user to install the CLI with the tooling, then a single Bundle with both is great. But I would recommend changing the Getting Started documentation to indicate installing that Bundle instead of just the CLI.

If installing the CLI as a standalone "thing" the a Bundle for the CLI is a very good idea. In fact, it's an even more important idea if you're going to start sharing the CLI with other Bundles. Bundles appropriately reference track their contained packages (the CLI MSI package, in this case). 

For example, If the CLI is available as standalone MSI, then someone installs the tooling Bundle (that contains the CLI) then decides they don't want the tooling... the CLI standalone MSI would be removed. A Bundle for "standalone CLI" avoids that problem.

So it gets back to:

> I would recommend creating a Bundle for the pieces you expect users to install.

**Comment by joeloff** [comment]
@robmen 100% agree. That's why the CLI MSI should already have dependency provider keys to support bundle reference counting. I just wasn't aware of the separate CLI only distribution.

**Comment by Petermarcu** [comment]
@joeloff , the CLI Msi will definitely be something we want people to be able to install without having to get the VS tooling.

**Comment by piotrpMSFT** [comment]
Alright @robmen, all yours!

**Comment by schellap** [comment]
> @schellap I thought you were yet to make ILC side of changes and then make changes for static linking for the output of --native. Is this work done?

Since the CRT changes need to be fixed in both the repos, we need this issue https://github.com/dotnet/cli/issues/1019 fixed, so we no longer need to pin the CLI version to `1.0.0.000973` in CoreRT. Then we can push a new ILC package and make corresponding CLI changes.

**Comment by schellap** [comment]
I can get an ILC Package for the CLI just compiled with MT MTd without passing the CI though. I will do that for bootstrapping.

**Comment by gep13** [comment]
@robmen piotrpMSFT once this is complete, and hosted "somewhere" if you let me know, I would be happy to wrap this in a chocolatey package, so would then be as simple as:

`choco install dotnet`

to get the necessary tooling installed on a Windows based machine (assuming they have Chocolatey already, obviously :smile: )

**Comment by gep13** [comment]
@piotrpMSFT on a side note, how were you able to assign @robmen to this issue?  That is something we run into all the time.  Did you have to add him to your organisation on GitHub?

**Comment by khellang** [comment]
@gep13 GitHub lets you add people as "outside collaborators", i.e. not a member of the organization; https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/

**Comment by factormystic** [comment]
@gep13 even better would be to publish via powershell package management. Add the project's package source, then something like `install-package dotnet-cli`. No third party dependencies required

**Comment by gep13** [comment]
>@factormystic said...
even better would be to publish via powershell package management.

Certainly another option. No harm in having both though :+1:

**Comment by khellang** [comment]
@gep13 @factormystic Isn't Chocolatey a default source for "powershell package management" (aka. OneGet?)?

**Comment by akoeplinger** [comment]
@khellang it's not there by default, but can be easily installed: http://www.hanselman.com/blog/AptGetForWindowsOneGetAndChocolateyOnWindows10.aspx

**Comment by gep13** [comment]
@khellang it is also fair to say that the current Chocolatey Provider for Package Management needs some work, it is on the list...

**Comment by robmen** [comment]
The bundle is now out there and working.

**Comment by gep13** [comment]
@robmen can you provide a link? Where can I get the bundle? Thanks!

**Comment by DeanVanGreunen** [comment]
unable to install dotnet cli on ubuntu 14.04 LTS
