### ISSUE TITLE
What's the equivalent of `dotnet publish -r win-x64`  in MSBuild

### ISSUE THREAD

**Issue by John0King** [dotnet/cli#10658]
the msbuild version won't restore during publish and cause a error when I separate the `dotnet restore` and `dotnet publish`
this is what I try 

```
1. dotnet restore -r win-x64
2. msbuild /p:RuntimeIdentifier=win-x64 /p:configuration=release
then  there is a error
The project was restored using Microsoft.NETCore.App version 2.2.0, but with current settings, version 2.2.1 would be used instead
```

how do I solve this problem ?

**Comment by livarcocc** [comment]
Invoke it with 'msbuild /restore /t:Publish /p:RuntimeIdentifier=win-x64 /p:configuration=release'

**Comment by livarcocc** [comment]
Let me know if that works for you.

**Comment by John0King** [comment]
@livarcocc Thanks ,  It works

-------------
I saw you put a "Discussion" lable on this ,  Is that mean you are consider to make the `msbuild /t:publish`  as same as the `dotnet publish` ?

**Comment by livarcocc** [comment]
> I saw you put a "Discussion" lable on this , Is that mean you are consider to make the msbuild /t:publish as same as the dotnet publish ?

@John0King not at all. We move all issues that are not clearly a bug to discussion. That means the issue is a question or a feature conversation, etc. We have no plans to add implicit restore to msbuild /t:publish.
