### ISSUE TITLE
dotnet --version should display a 4-part version number + git hash

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1065]
The current --version output, 1.0.0 is not sufficient to understand what's in the binary and what came in a later version. We need to update this command to list the 4-part version and, ideally, the SHA that produced it.

**Comment by enricosada** [comment]
:+1: about that, it's really useful

**Comment by davidfowl** [comment]
@piotrpMSFT can we get somebody to work on this? Small thing that will go a long way :smile:

**Comment by muratg** [comment]
:+1:

**Comment by tugberkugurlu** [comment]
:+1:

**Comment by enricosada** [comment]
I can see version and sha now, @piotrpMSFT can be closed?

**Comment by livarcocc** [comment]
Yeah. We have it now. Closing.
