### ISSUE TITLE
.NET Core runtime management (ex DNVM)

### ISSUE THREAD

**Issue by dtretyakov** [dotnet/cli#1066]
Since in the asp.net core [1.0-rc2](https://github.com/aspnet/Home/wiki/Roadmap#user-content-rc2---move-to-net-core-cli-and-net-platform-standard) DNX infrastructure will be superseded by [CLI toolchain](https://github.com/dotnet/cli) we have no ideas how DNVM runtime management use cases will be replaced.

We are considering case with automation of dotnet runtime installation on the build servers in the CI workflow. And it looks like except platform-specific packages CLI will support custom [installation options](https://github.com/dotnet/cli/blob/master/Documentation/beta-install-experience.md#local-install) via `install.sh`/`install.ps1` scripts, but page does not contain any details about it.

Could you shed some light on these scripts? Will they be ready on the time of asp.net core rc2 arrival?

**Comment by davidfowl** [comment]
> Since in the asp.net core 1.0-rc2 DNX infrastructure will be superseded by CLI toolchain we have no ideas how DNVM runtime management use cases will be replaced.

There's no more runtime. `dotnet` is a tool chain only. The runtime is included with packages as part of the NETStandard.Library. There's no dnvm equivalent for the tool chain itself.

> We are considering case with automation of dotnet runtime installation on the build servers in the CI workflow. And it looks like except platform-specific packages CLI will support custom installation options via install.sh/install.ps1 scripts, but page does not contain any details about it.

> Could you shed some light on these scripts? Will they be ready on the time of asp.net core rc2 arrival?

There no more information other than that document. Yes, we'll have it by RC2.

**Comment by dtretyakov** [comment]
Ok, thanks for explanation. Waiting for that part of toolchain.
