### ISSUE TITLE
Usability of 'dotnet new'

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#10665]
The usage experience with `dotnet new` is honestly a bit painful when working locally with custom templates. Specifically, I would like to ask for:

- having the opportunity to uninstall templates by short name (I think that's unique)
- being able to see a version in the list of installed templates
- getting a _clear_ notification, whether a template was installed or uninstalled, instead of printing all available templates

**Comment by livarcocc** [comment]
Issue moved to [dotnet/templating #1750](https://github.com/dotnet/templating/issues/1750) via [**ZenHub**](https://www.zenhub.com/)
