### ISSUE TITLE
dotnet-install.sh and dotnet-install.ps1 do not work as advertised with respect to printing a repeatable command line (`-DryRun`)

### ISSUE THREAD

**Issue by mklement0** [dotnet/cli#10664]
## Steps to reproduce

Note: Assumes the presence presence of [`dotnet-script.ps1`](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1) (Windows) and [`dotnet-script.sh`](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh) (Unix) in the current dir.

On Unix:

```sh
./dotnet-install.sh -dryrun -runtime dotnet
```

On Windows:

```powershell
./dotnet-install.ps1 -dryrun -runtime dotnet
```

## Expected  behavior

Both platforms (except for the filename extension):

```none
dotnet-install: Repeatable invocation: ./dotnet-install.ps1 -Runtime dotnet -Version 2.1.7
```

That is:

* The implied `latest` `-Version` should be reflected in an _explicit, resolved_ `-Version` argument.

* All explicitly specified parameters should appear, except for `-dryrun`, with `-Version` _resolved_, if an _abstract_ value such as `latest` or `coherent` was specified.

* Aside from `-Version`, no _omitted_ parameters should appear.

## Actual behavior

Unix:

```none
# ...
dotnet-install: Repeatable invocation: ./dotnet-install.sh --version 2.1.7 --channel LTS --install-dir <auto>
```

That is:

* the `-runtime` argument is lost.

* parameters that were at their default are now needlessly hard-coded; as an side `<auto>` used _unquoted_ will break the invocation.

Windows:

```none
#...
dotnet-install: Repeatable invocation: .\.\dotnet-install.ps1 -dryrun -runtime dotnet
```

That is:

* the `.\` is unexpectedly doubled (because the script blindly prepends `.\`

* otherwise, the input command line is blindly echoed, which means that:
  * `-dryrun` is needlessly present
  * no version resolution is performed.

## Environment data

Using the aforementioned scripts directly from this repo's master branch, as of 27 Jan 2019.

**Comment by mklement0** [comment]
@johnbeisner: A fix can be taken from (WIP) PR #10646:

```powershell
# The version text returned from the feeds is a 1- to 2-line string:
# for the SDK and the dotnet runtime (2 lines):
#   Line 1: # commit_hash (e.g., '4c506e0f35ce663f28fcb758387a98daa544e070')
#   Line 2: # 3-component version number (e.g., 2.1.503)
# for the aspnetcore runtime (1 line):
#   Line 1: # 3-component version number
function Get-Version-Info-From-Version-Text([string]$VersionText) {
    Say-Invocation $MyInvocation

    $Data = -split $VersionText

    $VersionInfo = @{
        CommitHash = $(if ($Data.Count -gt 1) { $Data[0] })
        Version = $Data[-1] # last line is always the version number.
    }
    return $VersionInfo
}
```

**Comment by livarcocc** [comment]
@johnbeisner is this still an issue?

**Comment by johnbeisner** [comment]
Resolved...
