### ISSUE TITLE
dotnet-install.ps1: `-Runtime aspnetcore` is broken

### ISSUE THREAD

**Issue by mklement0** [dotnet/cli#10663]
## Steps to reproduce

On Windows, assumes the presence of [`dotnet-script.ps1`](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1) in the current dir.:

```powershell
.\dotnet-script.ps1 -DryRun -Runtime aspnetcore
```

## Expected  behavior

The usual `-DryRun` output, listing the resolved download links.

## Actual behavior

The following error occurs:

```na
Index was outside the bounds of the array.
```

The reason is that the version information reported by the feed has only _1_ line  in the case of `asspnetcore` (only a version number, not preceded by  another line with the commit hash), whereas the code assumes the presence of _2_ lines.

## Environment data

Using the [script directly from the repo](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1) as of 27 Jan 2019.

**Comment by mklement0** [comment]
@johnbeisner: A fix can be taken from (WIP) PR #10646:

```powershell
# The version text returned from the feeds is a 1- to 2-line string:
# For the SDK and the dotnet runtime (2 lines):
#   Line 1: # commit_hash (e.g., '4c506e0f35ce663f28fcb758387a98daa544e070')
#   Line 2: # 3-component version number (e.g., 2.1.503)
# For the aspnetcore runtime (1 line):
#   Line 1: # 3-component version number
function Get-Version-Info-From-Version-Text([string]$VersionText) {
    Say-Invocation $MyInvocation

    $Data = -split $VersionText

    $VersionInfo = @{
        CommitHash = $(if ($Data.Count -gt 1) { $Data[0] })
        Version = $Data[-1] # last line is always the version number.
    }
    return $VersionInfo
}
```

**Comment by livarcocc** [comment]
@johnbeisner is this still an issue?

**Comment by johnbeisner** [comment]
Resolved...
