### ISSUE TITLE
dotnet add local package -> error: Value cannot be null. error: Parameter name: path1

### ISSUE THREAD

**Issue by gdillen** [dotnet/cli#10668]
## Steps to reproduce
I'm on macOS 10.14.2
dotnet version 2.2.103

1. Create a C# class library project
2. Add package metadata to the project file
- inside the existing <PropertyGroup> tag,
`<PackageId>mylib</PackageId>
<Version>1.0.0</Version>
<Authors>MyName</Authors>
<Company>MyCompany</Company>`

3. Run the pack command
$ dotnet pack
4 $ nuget add mylib.nupkg -source /Users/myname/nuget_repo
5 $ dotnet nuget push mylib.1.0.0.nupkg -s my-nuget
In my ConsoleApp project try to add my nuget package:
6 $ dotnet add package mylib -s /Users/myname/nuget-repo

## Expected  behavior
Successfully adding my Nuget package.

## Actual behavior
myname:MyConsoleApp myname$ dotnet add package mylib
  Writing /var/folders/cr/4pk4646d1_x5tl_tbbbbvqkw0000gn/T/tmpyagAXi.tmp
info : Adding PackageReference for package 'mylib' into project '/Users/myname/Projects/MyConsoleApp/MyConsoleApp.csproj'.
log  : Restoring packages for /Users/myname/Projects/MyConsoleApp/MyConsoleApp.csproj...
info : Package 'mylib' is compatible with all the specified frameworks in project '/Users/myname/Projects/MyConsoleApp/MyConsoleApp.csproj'.
error: Value cannot be null.
error: Parameter name: path1

**Comment by livarcocc** [comment]
@wli3 can you take a look?

**Comment by guydillen** [comment]
Any progress?

Thanks.

**Comment by wli3** [comment]
sorry I don't have any update

**Comment by Rakiah** [comment]
I have the same problem but using a remote private NuGet server, any updates please ??

**Comment by wli3** [comment]
@nkolev92 anything on the top of your head

**Comment by nkolev92** [comment]
Where are you trying to install the package? 

How did you generate the console app? 

I've seen this goo get spewed when it detects a cycle. 

Basically you are trying to install the package in the project that generated it.

**Comment by ransagy** [comment]
I've come across this myself. Is there any way for us to nail it down further? some diagnostic/verbose output to understand which path is it tripping on?

I tried adding the --verbosity diag and --diagnostics flags, but the cli doesn't accept those in any way i could add them coupled with the add package command.

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#8543
