### ISSUE TITLE
Linux ARM32 RID Incorrect

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#10676]
```console
pi@raspberrypi:~/webapp3 $ uname -a
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
pi@raspberrypi:~/webapp3 $ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     raspbian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview-010184/
```

RID should be `linux-arm` on this platform.

The Linux ARM64 RID is correct (on an ARM64 install).

**Comment by peterhuene** [comment]
@livarcocc should this be `core-sdk`?   Perhaps a host rid is ending up in the version file for an arm cross-build?

**Comment by livarcocc** [comment]
I have been trying to concentrate .NET Core SDK issues here on the CLI. So that we don't have to look all over for issues. I agree with your assessment of the potential cause though.

**Comment by livarcocc** [comment]
@richlander this should have been fixed now. Could you try the latest build from core-sdk and let us know. We will close the issue once you confirm it is addressed.

**Comment by richlander** [comment]
Fixed! Thanks so much.
