### ISSUE TITLE
Unable to push multiple packages at the same time

### ISSUE THREAD

**Issue by jkdey** [dotnet/cli#10683]
## Steps to reproduce
`dotnet nuget push *.nupkg -k <username>:<password> -s <source_uri>`

## Expected behavior
push all packages as shown in the last [example](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore2x#examples)

## Actual behavior
pushes first package only

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.7
 OS Platform: Linux
 RID:         alpine.3.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.503/

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  2.1.503 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
@wli3 would you mind checking if this is an issue on our side or on NuGet's side?

**Comment by wli3** [comment]
This issue was moved to NuGet/Home#7756
