### ISSUE TITLE
`dotnet add package` fails when --packages-directory has spaces

### ISSUE THREAD

**Issue by neville-nazerane** [dotnet/cli#10685]
I am running the latest release version 2.2. I tried running the following: 

    dotnet add package packageName --package-directory "D:\Cloud\Dropbox\codes\dotnet samples\nugets"

I get the error: 

> error: Unrecognized command or argument 'samples\nugets'

The error is gone when the folder has no spaces.

**Comment by livarcocc** [comment]
@peterhuene can you take a look?

**Comment by Jalalx** [comment]
I think this is the reason:
https://github.com/dotnet/cli/blob/3035b8536b72dcc2a0db6d617d8e4af5a3c81fb1/src/dotnet/commands/dotnet-add/dotnet-add-package/Program.cs#L144-L146

Spliting with `a.Split(' ')` makes another extra element in the result array.

I suggest this:

```csharp
            args.AddRange(_appliedCommand
                .OptionValuesToBeForwarded()
                .SelectMany(a => SingleSpaceSplit(a)));
```
and
```csharp
        private string[] SingleSpaceSplit(string argument)
        {
            var firstSpaceIndex = argument.IndexOf(' ');
            if (firstSpaceIndex > 0)
            {
                return new[]
                {
                    argument.Substring(0, firstSpaceIndex),
                    argument.Substring(firstSpaceIndex + 1)
                };
            }
            else
            {
                return new[] { argument };
            }
        }
```

**Comment by peterhuene** [comment]
Hi @Jalalx,

I'd have to track down why this particular command is splitting the forwarded arguments like this as I don't think it should.

Additionally, the forwarded argument should probably have quotes around the argument in `$"--package-directory {o.Arguments.Single()}"`.

**Comment by peterhuene** [comment]
Hi @Jalalx.  I haven't looked into it yet, but we should be able to remove the `.SelectMany` split being done when adding the option values to be forwarded to `args`.  I think that and double quoting the `--package-directory` argument in the command parser should solve this issue.

Did you want to attempt a fix for this?

**Comment by Jalalx** [comment]
Hello @peterhuene 
I think your solution will make `args` like this:
![image](https://user-images.githubusercontent.com/1018975/54978172-1f0efd00-4fbd-11e9-8013-7acdb85d98fc.png)

But `--package-directory` and the value must be in separate items.

Here are my changes using `git diff`:
```diff
diff --git a/src/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs b/src/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
index 1f4dbfb35..80c2eaf59 100644
--- a/src/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
+++ b/src/dotnet/commands/dotnet-add/dotnet-add-package/AddPackageParser.cs
@@ -47,7 +47,7 @@ public static Command AddPackage()
                               LocalizableStrings.CmdPackageDirectoryDescription,
                               Accept.ExactlyOneArgument()
                                     .With(name: LocalizableStrings.CmdPackageDirectory)
-                                    .ForwardAsSingle(o => $"--package-directory {o.Arguments.Single()}")),
+                                    .ForwardAsSingle(o => $"--package-directory \"{o.Arguments.Single()}\"")),
                 Create.Option("--interactive",
                               LocalizableStrings.CmdInteractiveRestoreDescription,
                               Accept.NoArguments()
diff --git a/src/dotnet/commands/dotnet-add/dotnet-add-package/Program.cs b/src/dotnet/commands/dotnet-add/dotnet-add-package/Program.cs
index 9f9f0cf34..813de478c 100644
--- a/src/dotnet/commands/dotnet-add/dotnet-add-package/Program.cs
+++ b/src/dotnet/commands/dotnet-add/dotnet-add-package/Program.cs
@@ -142,8 +142,7 @@ private string[] TransformArgs(string packageId, string tempDgFilePath, string p
             };
 
             args.AddRange(_appliedCommand
-                .OptionValuesToBeForwarded()
-                .SelectMany(a => a.Split(' ')));
+                .OptionValuesToBeForwarded());
 
             if (_appliedCommand.HasOption("no-restore"))
             {
```

**Comment by glitch100** [comment]
For those looking to get around this you can replace the space(s) in the path with `%20` as a work around until such time this is resolved.

**Comment by peterhuene** [comment]
@Jalalx those changes look good to me!  Would you like to submit a PR?

**Comment by peterhuene** [comment]
Oh I didn't fully look at your comment.  Let me look more closely as to why this command was implemented this way, as it shouldn't be.

**Comment by peterhuene** [comment]
Ok, so I now see why this command was implemented this way.  It's invoking another command that is expecting an `argv`, so it's (poorly) attempting to do so.

The fix can be simply splitting with a max of 2 substrings.  We can remove the quotes around the `--package-directory` option and instead just change the `SelectMany` call to: `.SelectMany(a => a.Split(' ', 2))`.  This will guarantee that we get an argument for the option and an argument for the option's value; the rest of the command line handling logic will properly quote the option value for us.
