### ISSUE TITLE
Consider removing ANSI Code Console Pass-Through

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#1068]
`System.Console` now has [good Unix support](https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/ConsolePal.Unix.cs). The workaround of passing the ANSI escape sequences through in `AnsiConsole` (and `Reporter`) can be probably be removed now.

**Comment by brthor** [comment]
Took a look into this. 

The AnsiConsole class gives us a convenient way of outputting colors to the console without needing to Console.SetColor() for each string we want to print. It also gives us capability to preserve the colors of messages as they pass up through the command process chain.

**Comment by brthor** [comment]
Going to close this out for now.

**Comment by bricelam** [comment]
Ah cool, I hand't considered how it could help with the process chaining.
