### ISSUE TITLE
Add support for `dotnet test` to have JUnit style output

### ISSUE THREAD

**Issue by wordshaker** [dotnet/cli#10698]
## The Problem

Using CircleCI as a build tool, there are some features you can only get access to if your test output is in a JUnit format. XUnit provides a `-junit` argument to transform XUnit output to a JUnit style of output and it seems similar functionality used to be supported: https://stackoverflow.com/questions/39542533/xunit-dotnet-test-cli-to-output-to-nunit-xml-so-that-bamboo-can-read-the-results/47073101 

I've tried using the `--logger` option in a few ways, but can't find a way of achieving what I want without using another package. 

Is it possible to use the [XUnit Transforms](https://github.com/xunit/xunit/blob/master/src/xunit.console/Utility/TransformFactory.cs) out the box with `dotnet test`?

## Expected  behavior

- To be able to run an argument as part of `dotnet test` that enables the test output to be transformed into an expected format.

## Actual behavior

- Can use the `--logger` argument to output to xml or trx, but the tool I'm using explicitly needs a trx with JUnit formatting

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1911
