### ISSUE TITLE
ProjectContext.CreateLoadContext can't load source Projects.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#1071]
Assume we have a compiled class library that has the source format of:
```
/A
 - project.json
```

And we do
```C#
var projectContext = ProjectContext.CreateContextForEachFramework("./A/project.json").First();
var loadContext = projectContext .CreateLoadContext();

loadContext.Load("A"); // Explodes. Could have been a transitive source dependency too.
```

Investigated this and it turns out when accumulating a projects exports [here](https://github.com/dotnet/cli/blob/e013deadd4d7ad19934fd0831c9574a32a2ef4cf/src/Microsoft.DotNet.ProjectModel.Loader/LoaderProjectContextExtensions.cs#L18) it doesn't take into account source projects.

Pulled @anurse in to investigate and found that the logic that used to do this was removed in [this](https://github.com/dotnet/cli/commit/b5ebe855ada39362a45c46c90fb03b3e10611cad#diff-3662f57e5d025e396a241875143115d7L154) commit.

**Comment by anurse** [comment]
Looks like @davidfowl might have a fix for this in #1067

**Comment by blackdwarf** [comment]
@anurse is this fixed?

**Comment by anurse** [comment]
Yes, I believe this is fixed. @NTaylorMullen can you confirm?

**Comment by NTaylorMullen** [comment]
Yes it is.
