### ISSUE TITLE
fsi help is misspelled

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#10728]
## Steps to reproduce

`dotnet --help`

## Expected  behavior

fsi help is spelled correctly

## Actual behavior

fsi help is misspelled

```
  fsi               Start F# Interective / execute F# scripts.
````

s/Interective/Interactive/

@KevinRansom

**Comment by livarcocc** [comment]
Let's fix it. It is loc only, should be absolutely fine getting this through shiproom.

**Comment by livarcocc** [comment]
Closing this bug as the PR that fixes it has been merged.
