### ISSUE TITLE
Add an extra line after first run experience message

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/cli#10722]
Clean Linux machine.
Install .NET Core SDK 2.2 per the instructions on the web.
Run
`dotnet tool install -g dotnetsay`

Now from the same terminal run
`dotnetsay`

This will fail saying that it can't find `dotnetsay` command.

Starting a new terminal and running `dotnetsay` will now work.

This is confusing, if we can't make this work in the original terminal, we should at last write out a warning that a new terminal needs to be started.

**Comment by livarcocc** [comment]
@wli3

**Comment by wli3** [comment]
It is there. But if `tool install` is the first command that runs. It will be mixed with first run experience message

**Comment by wli3** [comment]
![screen shot 2019-02-07 at 10 23 19 am](https://user-images.githubusercontent.com/6993335/52433786-b0381c00-2ac2-11e9-8985-b7cd0b1161ee.png)

**Comment by vitek-karas** [comment]
Thanks, totally missed that  - thanks a lot a sorry for the confusion.
