### ISSUE TITLE
Windows installer uses 'Dotnet' instead of '.NET' in Add/Remove programs

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#1072]
Repro steps:
1. Install the .NET CLI installer from http://dotnet.github.io/getting-started/
2. Go to Control Panel->Add/Remove programs

Result:
All the old .NET stuff is called '.NET' but the new CLI installer is called 'Microsoft Dotnet CLI for Windows'.

**Comment by piotrpMSFT** [comment]
@blackdwarf I believe this is bydesign. Can you confirm?

**Comment by blackdwarf** [comment]
@piotrpMSFT for now, yes.

**Comment by gregg-miskelly** [comment]
Looks like this is now fixed.
