### ISSUE TITLE
Why dotnet sln cound not create solution folder under added project?

### ISSUE THREAD

**Issue by LightVolk** [dotnet/cli#10730]
I have very big solution (500+ projects) and Visual Studio can not open it fast. Ok.
I know about command **dotnet sln Solution.sln add NewProject.csproj**.

But i want to have command arguments of Solution Folder hierarchy.

For example: **dotnet sln Solution.sln add NewProject.csproj  -hier FirstSolutionFolder\SecondSolutionFolder** and command add it into FirstSolutionFolder\SecondSolutionFolder\NewProject.csproj  

Can you add this functionality in next versions of dotnet cli?

**Comment by peterhuene** [comment]
Hi @LightVolk.

This functionality will be in a future release of the .NET Core 3.0 SDK.

Look for an option `--solution-folder` option for the `sln add` command that can specify a hierarchy like `FirstSolutionFolder\SecondSolutionFolder`.  It is being implemented in PR #11000.

Thanks for the suggestion!
