### ISSUE TITLE
dotnet clean also supports solution files

### ISSUE THREAD

**Issue by mairaw** [dotnet/cli#10744]
## Steps to reproduce
`dotnet clean --help` says that the argument is a project but it seems that the command accepts solution as well.
Running on a folder with no solution or project gives the following error message:
`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.`

## Expected  behavior
`dotnet clean --help` would say it supports solution files as well.

## Actual behavior
`dotnet clean --help` says it supports project files.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.300-preview1-008174 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview1-26216-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment]
This also applies to `dotnet restore`, `dotnet build`, `dotnet publish`, and `dotnet test` (basically all the MSBuild-based commands.

**Comment by Jalalx** [comment]
I would like to implement this. @peterhuene can you give me a general view on this? In which order projects should be cleaned?

**Comment by peterhuene** [comment]
Hi @Jalalx,

Like the other issue you worked on, this issue is just a fix for the `--help` output.  Currently, the `dotnet restore`, `dotnet build`, `dotnet publish`, and `dotnet test` commands all use `CommonLocalizableStrings.ProjectArgumentName` and `CommonLocalizableStrings.ProjectArgumentDescription` when they should be using `CommonLocalizableStrings.SolutionOrProjectArgumentName` and `CommonLocalizableStrings.SolutionOrProjectArgumentDescription`.

Thanks for offering to help out with this issue!  Let me know if you run into any difficulties.

**Comment by Jalalx** [comment]
Oh, I took it the wrong way 🤦‍♂️. I'll send a PR tonight

**Comment by peterhuene** [comment]
@Jalalx thanks very much for offering to help fix this!  It appears, however, that @potapy4 put up a PR already to fix.
