### ISSUE TITLE
[Feature] Allow `dotnet add package` command to add a reference without setting the version 

### ISSUE THREAD

**Issue by alirezajm** [dotnet/cli#10757]
Allow adding package references via the cli without it setting the version in the project file.
This is useful when a **Directory.build.targets** file is present and it is used to manage package versions.

## Feature behavior
Considering there is a Directory.Build.targes file present, containing the following
`<PackageReference Update="Microsoft.Orleans.Core" Version="2.1.2" />` 
running
`dotnet add package Microsoft.Orleans.Core --use-targets-version`
will add
 `<PackageReference Include="Microsoft.Orleans.Core" />` in the .csproj file.
All compatibility checks are intact.

If no reference is present in the .targets file, it should result in an error. Or maybe add an `<PackageReference Include="...` item.

Additional feature:
Enable adding and removing packages to .targets file. This of course is a bit more complex as currently **dotnet add package** command adds/upgrades package references, which will not work quite well with .target files

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7785
