### ISSUE TITLE
Not able to push packages to DevOps artifacts using Dotnet Nuget Push

### ISSUE THREAD

**Issue by mdmoura** [dotnet/cli#10778]
## Steps to reproduce

I tried to push a package to Azure Devops Artifacts, after creating a feed, in two ways:

    dotnet nuget push 
       --source https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v3/index.json 
       MyPackage.nupkg

    dotnet nuget push 
       --source https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2
       --api-key MyPAT 
       MyPackage.nupkg

I created the PAT as follows:
https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops

Just it case I gave it full access ...

## Expected behavior

I would expect the package to be pushed to the feed.

## Actual behavior

When using version 3 I got the following error:

     error: Unable to load the service index for source 
                https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v3/index.json 
     error: Response status code does not indicate success: 401 (Unauthorized).

When using version 2 I got the following error:

    info : Pushing MyPackage.nupkg to 
             'https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2'...
    info :   PUT https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2
    info :   Unauthorized https://pkgs.dev.azure.com/MyOrganization/_packaging/MyFeed/nuget/v2 563ms
    error: Response status code does not indicate success: 401 (Unauthorized).

Using the browser I can access both version 2 and 3 urls (for version 3 I needed to sign in on Azure)

## Environment data

.NET Core SDK (reflecting any global.json):
Version:   2.2.104
Commit:    73f036d4ac

Runtime Environment:
OS Name:     Mac OS X
OS Version:  10.14
OS Platform: Darwin
RID:         osx.10.14-x64
Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
Version: 2.2.2
Commit:  a4fd7b2c84

.NET Core SDKs installed:
2.2.104 [/usr/local/share/dotnet/sdk]

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7792
