### ISSUE TITLE
'dotnet publish' should generate exe.config as needed too

### ISSUE THREAD

**Issue by weidazhao** [dotnet/cli#1079]
Repro steps:
1. Unzip [repro.zip](https://github.com/dotnet/cli/files/107642/repro.zip). The project references two packages, and the two packages have dependencies on different versions of Newtonsoft.Json.
2. If run dotnet restore & dotnet publish, repro.exe.config is not generated.
3. If run dotnet restore & dotnet compile, repro.exe.config is generated next to the executable.

Expected:
Publish should behavior the same as compile.

**Comment by davidfowl** [comment]
This should have been fixed a while ago. If you don't see it then reopen.

/cc @anurse @pakrym
