### ISSUE TITLE
DEB installer only, for SDK 3.0.100-preview3-010278, aspnetcore-runtime 3.0.0-preview3-19113-07's installation depends on runtime 3.0.0-preview-27408-1 rather than 3.0.0-preview3-27414-8

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#10792]
## Steps to reproduce
1. With DEB installer, install runtime 3.0.0-preview3-27414-8, aspnetcore-runtime 3.0.0-preview3-19113-07 and sdk 3.0.100-preview3-010278 in order

## Expected  behavior
All packages are installed normally, below screenshot is the installation with RPM installer
![image](https://user-images.githubusercontent.com/1578239/52844803-685b6980-3140-11e9-855f-e8b455e9d79d.png)

## Actual behavior
With DEB installer, aspnetcore-runtime 3.0.0-preview3-19113-07's installation depends on runtime 3.0.0-preview-27408-1 rather than 3.0.0-preview3-27414-8
![image](https://user-images.githubusercontent.com/1578239/52844893-9fca1600-3140-11e9-9fa1-bbef127e814c.png)

##Note
As workaround, install runtime 3.0.0-preview-27408-1, aspnetcore-runtime 3.0.0-preview3-19113-07, runtime 3.0.0-preview3-27414-8 and sdk 3.0.100-preview3-010278 in order
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010278
 Commit:    3d17f286de

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview3-010278/

Host (useful for support):
  Version: 3.0.0-preview3-27414-8
  Commit:  2c740c0ea8

.NET Core SDKs installed:
  3.0.100-preview3-010278 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview3-19113-07 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27414-8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
I believe this is because the build in incoherent. I don't see what we could do here.
