### ISSUE TITLE
dotnet telemetry off by default

### ISSUE THREAD

**Issue by ZenoArrow** [dotnet/cli#10816]
As mentioned in issues #3093 and #10497, there are significant concerns with having telemetry enabled by default. I understand why Microsoft is looking for telemetry data to understand what to focus development efforts on, but I would suggest that it's not a suitable feature for production releases and should be limited to only be enabled by default on prerelease builds. Is there any flexibility on this at all?

**Comment by livarcocc** [comment]
This has been discussed in the issues you linked.
