### ISSUE TITLE
dotnet build places the "obj" folder in the current directory

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1081]
1. Create a project
2. Go in one of the parent folders (can be the repo's root or the drive's root)
3. Run `dotnet build <path to project>` (e.g. `dotnet build test\Microsoft.Extensions.Options.Test`)

Notice:

1. The `bin` folder is placed under the project's folder.
2. The `obj` folder is placed under the current folder instead of the project's folder.

**Comment by davidfowl** [comment]
@victorhurdugaci can you retry this now that https://github.com/dotnet/cli/commit/4ebc704e670f3c0addb0d7e19d9d4b72d169faea is in

**Comment by blackdwarf** [comment]
@victorhurdugaci did you try it again and does it repro still?

**Comment by blackdwarf** [comment]
Will close this due to a lack of feedback. Also, this behavior will most likely change when we replat on msbuild.
