### ISSUE TITLE
ToolsError build failures in 'prodcon/cli/release/2.2.1xx/' - '20190214.01'

### ISSUE THREAD

**Issue by robertborr** [dotnet/cli#10832]
@dotnet-mc-bot commented on [Fri Feb 15 2019](https://github.com/dotnet/core-eng/issues/5249)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=2420496
  - **Agent:** DDVSOMACAGE009
  - **Error log:** Total tests: 2. Passed: 0. Failed: 0. Skipped: 2....

@robertborr

---

@robertborr commented on [Tue Feb 19 2019](https://github.com/dotnet/core-eng/issues/5249#issuecomment-465236089)

15>RunTest:
         Executing - /Users/buildagent/agent/_work/455/s/bin/2/osx-x64/dotnet/dotnet restore   --disable-parallel -  in pwd /Users/buildagent/agent/_work/455/s/bin/3/osx-x64/test/dotnet-list-package.Tests/ItDoesNotAcceptInvalidFramework/MSBuildAppWithMultipleFrameworks
    15>RunTest:
         VSTest: Exit code: 0
    15>RunTest:
         [xUnit.net 00:01:15.1643891]     Microsoft.DotNet.Cli.List.Package.Tests.GivenDotnetListPackage.AssetsPathExistsButNotRestored [FAIL]
         Failed   Microsoft.DotNet.Cli.List.Package.Tests.GivenDotnetListPackage.AssetsPathExistsButNotRestored
    15>DOTNETTEST : error Message:  [/Users/buildagent/agent/_work/455/s/build/test/RunTest.proj]
          Expected command to pass but it did not.
         File Name: /Users/buildagent/agent/_work/455/s/bin/2/osx-x64/dotnet/dotnet
         Arguments: list /Users/buildagent/agent/_work/455/s/bin/3/osx-x64/test/dotnet-list-package.Tests/AssetsPathExistsButNotRestored/NewtonSoftDependentProject package 
         WorkingDir:: 
         Exit Code: 139
         StdOut:
         
         StdErr:
         
         
         Stack Trace:
            at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
            at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
            at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() in /Users/buildagent/agent/_work/455/s/test/Microsoft.DotNet.Tools.Tests.Utilities/Assertions/CommandResultAssertions.cs:line 32
            at Microsoft.DotNet.Cli.List.Package.Tests.GivenDotnetListPackage.AssetsPathExistsButNotRestored() in /Users/buildagent/agent/_work/455/s/test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:line 120

Testing on the build machine is advised against, this test had a segmentation fault and should be investigated by the test owner.

**Comment by livarcocc** [comment]
This is a seg fault. The CLI is purelly managed. So, this must be the host crashing. Please move the issue to core-setup.

**Comment by robertborr** [comment]
Issue moved to [dotnet/core-setup #5206](https://github.com/dotnet/core-setup/issues/5206) via [**ZenHub**](https://www.zenhub.com/)
