### ISSUE TITLE
dotnetcore on linux reads assembly contents, even if loaded

### ISSUE THREAD

**Issue by force-net** [dotnet/cli#10830]
We're using .netcore on linux and using next deploy algorithm: update content of folder with dll's and restart application. It is impossible on windows (because dll's is locked), but works fine on linux at .net core 2.0. When we've switched to 2.1, this workflow become unusable due sporadic crashes when dll's are updated for running application. 2.2 version has same issue. 

I've found that this problem is related to exceptions (stackframes) or reflection. Simple app reproduces this behavior.

## Steps to reproduce
1. Create a simple console app with this code:
```
class Program
{
	static void Main(string[] args)
	{
		while (true)
		{
			try
			{
				System.Threading.Thread.Sleep(1000);
				throw new System.InvalidOperationException();
			}
			catch (System.Exception e)
			{
				System.Console.WriteLine(e);
			}
		}
	}
}
```
2. publish it and deploy to Linux system (Ubuntu 16.04 and 18.04 was checked)
3. Run it `dotnet ConsoleApp1.dll`
4. Edit ConsoleApp1.dll by removing some symbol in a dll body

## Expected  behavior

Nothing changed, application continue working

## Actual behavior

Crash with `Segmentation fault (core dumped)` or `BadImageFormatException` or `no string associated with token` or something else.

## Environment data

```
Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
Issue moved to [dotnet/core-setup #5205](https://github.com/dotnet/core-setup/issues/5205) via [**ZenHub**](https://www.zenhub.com/)
