### ISSUE TITLE
Fail with graceful error message when trying to build WindowsDesktop project on non-Windows

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#10842]
The Microsoft.NET.Sdk.WindowsDesktop SDK is only available on Windows.  This means that you will get an error that the SDK can't be found if you try to build a project that uses WindowsDesktop on Mac or Linux.  We should have a better error here, for example by having a "stub" version of the WindowsDesktop SDK on Mac and Linux that generates an error indicating that the SDK isn't supported on the current operating system.

Related: https://github.com/dotnet/wpf/issues/57#issuecomment-464415785

**Comment by daviddenis-stx** [comment]
As a matter of fact compiling is not executing. See my tentative described in https://github.com/dotnet/wpf/issues/57#issuecomment-491918057

It seems that compiling under Unix works just fine, if it is confirmed we could merge the proposed code and enjoy cross compiling (and close the current "issue")

**Comment by dsplaisted** [comment]
@daviddenis-stx Yes, it would be nice to support building a WPF app on all OS's.  Currently we're planning to not support this for the initial .NET Core 3 release, but hopefully we can add support for it later.

**Comment by daviddenis-stx** [comment]
we're testing the outputs currently, will let you know if the produced assemblies execute correctly

**Comment by daviddenis-stx** [comment]
@dsplaisted I filed https://github.com/dotnet/wpf/issues/688 for future reference

**Comment by peterhuene** [comment]
This issue was fixed with dotnet/sdk#3275.
