### ISSUE TITLE
Incorrect sdk selected

### ISSUE THREAD

**Issue by aateeque** [dotnet/cli#10865]
## Steps to reproduce
Create a new dotnet app from CLI

```
D:\>mkdir a & cd a

D:\a>dotnet new webapp
The template "ASP.NET Core Web App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.

Processing post-creation actions...
Running 'dotnet restore' on D:\a\a.csproj...
C:\Program Files\dotnet\sdk\2.1.104\sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK d
oes not support targeting .NET Core 2.2.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [D:\a\a.
csproj]

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

## Expected  behavior
Should work just fine; there is __no__ _global.json_ in D:\

## Actual behavior
Reports missing SDK

## Environment data
```
`dotnet --info` output:
D:\>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment]
@nguerrera Have we seen any SDK resolution issues where we'd pick up a 2.0 SDK like this without a global.json present?

**Comment by livarcocc** [comment]
@aateeque do you, by any chance, have MSBuildSDKsPath environment variable set and pointing to your 2.1.104 SDK? That would explain why we were using props/targets from that location instead of from the latest SDK.

**Comment by aateeque** [comment]
Indeed - that fixed it @livarcocc. Is this documented? If so, perhaps we need to document better...because this is the first I've come across the EnvVar. 

Also, it'd be useful for dotnet cli to report where it resolved the SDK from (i.e. global json, this env var), what do you think?

**Comment by livarcocc** [comment]
I don't think that's documented and you are welcome to file an issue on microsoft/docs for that.

I don't expect many people should be setting this though, if at all. Note that this is not the same as a global.json resolution. The .NET Core SDK hive that was resolved depends on the global.json. If you don't set this env var, the sdk props/targets are resolved next to the .NET Core SDK.

However, if you set that env var, then props/targets are going to be found based on that location. At this point in time, I don't believe this would be a change we would make, given all the other things we are working on.

I will take this as a data point though, if we see this more often, we will consider additional logging.

**Comment by peterhuene** [comment]
The environment variable is mostly used for our dogfooding and automated testing. I'm curious how this would have been set in your environment.

@livarcocc did we ever ship anything that sets this variable?

**Comment by nguerrera** [comment]
If we add any documentation, it should simply say that setting this variable is unsupported.

There are a few issues on the omnisharp repo where people are recommending this to work around issues they had there. I've tried and failed to get to the bottom of that. I will start posting advice against this.

**Comment by nguerrera** [comment]
Technically, we shipped the CLI itself that sets it for msbuild child processes (by design), but nothing that sets it permanently.

**Comment by nguerrera** [comment]
The omnisharp issues seem to come down to mono installations without the sdk resolver (or without a working sdk resolver?). @rchande has not been able to repro them, unforuntately.

**Comment by nguerrera** [comment]
> If we add any documentation, it should simply say that setting this variable is unsupported.

This is a bit of an overstatement. If you are using MSBuild API, on core without going through CLI, then you need to set it like CLI does. MSBuildLocator does this. But nothing should be setting it permanently for other proceseses that aren't bound to a particular MSBuild/SDK.

**Comment by nguerrera** [comment]
(I see this report is on Windows, so probably not from seeing the advice on an omnisharp issue.)

**Comment by aateeque** [comment]
This was probably picked up a mechanism to specify which sdk to load for TeamCity build agents; as I found the source in our stack to be in our agent deployment script. The script was setting this variable after installing an sdk version.
