### ISSUE TITLE
Replace MIT License with .NET Library EULA in Windows installer

### ISSUE THREAD

**Issue by peterhuene** [dotnet/cli#10868]
## Steps to reproduce

1. Install a 3.0.100 SDK preview for Windows using the installer.

## Expected  behavior

The link for "MIT License" should be replaced with ".NET Library EULA".

## Actual behavior

The link for the "MIT License" remains.

**Comment by vivmishra** [comment]
Related: https://github.com/dotnet/core-setup/pull/4588

**Comment by livarcocc** [comment]
@johnbeisner
