### ISSUE TITLE
Creating nuget package using dotnet pack command and <NuspecFile> tag creates a package targeting .Net Framework

### ISSUE THREAD

**Issue by shai-glat** [dotnet/cli#10861]
## Steps to reproduce
1. Create a csproj and generated a nuget package from it - works as expected
2. Open the package and take out the generated nuspec file.
3. Add the following tag to csproj:
`	<PropertyGroup>
		<NuspecFile>nuspec\MyProj.nuspec</NuspecFile>
	</PropertyGroup>
`
4. Add the `files` tag to nuspec file as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
..... (unmodified)
  </metadata>
	<files>
		<file src="<Path>/MyProj.dll" target="lib" />
		<file src="<Path>/OtherFile.dll" target="lib" />
	</files>
</package>
```
5. run `dotnet pack MyProj.csproj -o out /p:Version=1.0.1`
## Expected  behavior
Generated package is a valid .NET Core package

## Actual behavior
Package contents are all .NET Core dlls, but when adding the package visual studio it states the package was restored using .NetFramework 4.6 instead of .Net Core 2.1

## Environment data
`dotnet --info` output: 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

## Additional notes
I had the same problem when adding NuspecFile via dotnet CLI, as well as when i started with an empty nuspec file and simply added the files tag as stated above

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7825
