### ISSUE TITLE
Uninstalling Preview 2 Does Not Clean Up After Itself

### ISSUE THREAD

**Issue by scottsauber** [dotnet/cli#10882]
## Steps to reproduce
Running Windows 10 and uninstalled Preview 2 (2.1.600-preview-009497) via Add/Remove Programs.  Rebooted and now when I run dotnet --info I get:

```Found dotnet SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\2.1.600-preview-009497\dotnet.dll]```

I had to delete the C:\Program Files\dotnet\sdk\2.1.600-preview-009497 folder to get the .NET CLI to work

## Expected  behavior
It removes C:\Program Files\dotnet\sdk\2.1.600-preview-009497 for me

## Actual behavior
It does not

## Environment data
`dotnet --info` output:

Found dotnet SDK, but did not find dotnet.dll at [C:\Program Files\dotnet\sdk\2.1.600-preview-009497\dotnet.dll]

**Comment by scottsauber** [comment]
I should add... I got the pop up that I had dotnet.exe was still running and did it want to close automatically for me or leave open and reboot.  I chose close automatically.

**Comment by Liversage** [comment]
I hit this issue today after uninstalling preview 7. I also was asked about "close automatically/leave open?" two times and being impatient waiting for "close automatically" I manually killed several dotnet.exe processes the second time which allowed the installer to proceed but alas without removing the folder for the SDK that was uninstalled.
