### ISSUE TITLE
dotnet restore does not use NuGetDefaults.Config on Linux

### ISSUE THREAD

**Issue by kpstolk** [dotnet/cli#10897]
According to the [NuGet documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#nuget-defaults-file) it is possible to store a `NuGetDefaults.Config` file in `~/.local/share` or `/usr/local/share` to configure global settings.

We currently use a Windows machine and using this file (on `%ProgramFiles(x86)%\NuGet\Config` of course) works just fine with `dotnet restore`.

However now I'm setting up an Ubuntu 18.04 build server and have installed [dotnet](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current) but the `NuGetDefaults.Config` doesn't seem to be used as I get an error from `dotnet restore`.

I also tried to install NuGet directly using `sudo apt-get install nuget` but this doesn't work either with `nuget restore`, I get the same error. It does work however when I store the file in  `~/.config/NuGet/NuGet.Config` (so not at Computer but [User level](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses)).
Even configured at user level `dotnet restore` still fails.

So how else can I configure my custom [package source](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesources)?

## Steps to reproduce
1. Install .NET Core SDK on Linux Ubuntu 18.04 x64
1. Create a `NuGetDefaults.Config` in both `~/.local/share` or `/usr/local/share` with content as shown below
1. Clone Git repo containing .NET Core project and `cd` to it
1. Run `dotnet restore`
1. Error NU1101 is shown

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <packageSources>
        <add key="MySource" value="http://my/custom/source/" />
    </packageSources>
</configuration>
```

## Expected  behavior
`dotnet restore` to restore packages from my custom package source defined in `NuGetDefaults.Config`.

## Actual behavior
Error from `dotnet restore`:

```
/home/user/devops/_work/1/s/src/path/to/my.csproj : error NU1101: Unable to find package My.Custom.Package. No packages exist with this id in source(s): nuget.org
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by kpstolk** [comment]
[This issue](https://github.com/dotnet/docs/issues/6496) seems related regarding the (lack of) documentation of `dotnet restore`.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7839
