### ISSUE TITLE
When referencing a project directly allow content to be copied on publish.

### ISSUE THREAD

**Issue by xanather** [dotnet/cli#1090]
When referencing a project directly make it possible to allow content to be copied on publish. For example, I have Project A reference Project B and both projects are on the local disk within the same directory. When compiling/publishing the source code of Project B is used instead of nuget packages since its a local reference. The problem is the content/asset files of Project B won't be copied over when Project A is published.

I have developed a 2D graphics framework on .NET Core which uses a few image/shader asset files as part of the framework. It would be nice if these assets were included in projects that reference the game engine when publishing.

Right now having "content" in a project.json of a locally referenced library with source code does not get included in the publish.

**Comment by xanather** [comment]
Would be nice if NuGet packages in general could support copying content over too on publish, just like how files in /runtimes/win7-x64/native of NuGet packages get copied.

**Comment by xanather** [comment]
Re-reading what I wrote seems complicated, trying to simplify:

**Any files:**
Using "content" of project.json when referencing as NuGet package results in:
Not contained within the .nupkg file so won't be included on publish.

Using "content" of project.json when referencing project as source code directly results in:
Not copied on publish.

**Native library files (related to https://github.com/dotnet/cli/issues/710):**
Using "packInclude": { "runtimes/win-x64/native/": "location" } of project.json when referencing as NuGet package results in:
Libraries are copied on publish.

Using "packInclude": { "runtimes/win-x64/native/": "location" } of project.json when referencing project as source code directly results in:
Libraries are not copied on publish.

**Comment by xanather** [comment]
Native library copying from project references doesn't seem supported on purpose. Due to requiring formal design on how it should work inside the project.json?
https://github.com/dotnet/cli/blob/d53b405ebd451b537636c7fcafa8697b69c85cf2/src/Microsoft.DotNet.ProjectModel/Compilation/LibraryExporter.cs#L200

Copy contents is also only ran on the project being published.
https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L138

Content copying detection logic should be moved into LibraryExporter.cs? I would try craft a PR but design issues need to be sorted first (https://github.com/dotnet/cli/issues/792 https://github.com/dotnet/cli/issues/710 related) and I'm not sure if supporting copying content from other projects/packages is something that is wanted.

**Comment by Northgates-Systems** [comment]
I think it would good. I have a pkg lib that would be referenced from a developer's project and it includes js, css, a readme (how to...). I would also like to do some checking and updating the developer's project for example, adding a line in the Startup.cs, _ViewImports.cshtml etc... Not sure, it may already be possible.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
