### ISSUE TITLE
Support installing a particular version of the CLI

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1091]
It would be nice if the install scripts under `scripts\obtain` would support installing a particular version of the CLI, not only the latest. It would help us when we find a blocking bug and we need to stick to a particular version of the CLI for a while

**Comment by piotrpMSFT** [comment]
:+1:

**Comment by pranavkm** [comment]
Fixed in https://github.com/dotnet/cli/commit/ed1177a664106ee312003983474b55f0e3bc627f
