### ISSUE TITLE
Enable MSI tests in CI

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#1092]
https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/testmsi.ps1#L50-L65

Investigate to find a reliable way to run MSI tests in CI.

**Comment by piotrpMSFT** [comment]
@eerhardt you already fixed this, no? Can you associate the PR and close the issue?

**Comment by eerhardt** [comment]
Yes, I fixed this with #1499 and #1526.  Closing.
