### ISSUE TITLE
Build fails for build time dependencies

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1093]
Clone the aspnet/common repo and build `Microsoft.Extensions.Primitives`. 

That repo has a dependency on `Microsoft.Extensions.HashCodeCombiner.Sources` which is a build time dependency. `HashCodeCombiner` is also a sources packages so it shouldn't produce any binaries.

However, `build` expect a dll from it:

```
D:\aspnet\common\src\Microsoft.Extensions.Primitives>dotnet build
Compiling Microsoft.Extensions.Primitives for .NETFramework,Version=v4.5.1
C:\Users\victorhu\AppData\Local\Microsoft\dotnet\cli\bin\dotnet-compile-csc.exe "@D:\aspnet\common\src\Microsoft.Extensions.Primitives\obj\Debug\net451\dotnet-compile.rsp" returned Exit Code 1
D:\aspnet\common\src\Microsoft.Extensions.Primitives\error CS0006: Metadata file 'D:\aspnet\common\src\Microsoft.Extensions.HashCodeCombiner.Sources\bin\Debug\net451\Microsoft.Extensions.HashCodeCombi
ner.Sources.dll' could not be found
```

Side note, probably related:

If you run `dotnet pack` on a sources package you get the correct nupkg but if you run `dotnet build` you get binaries. In the case of source packages, there should be no binaries.

**Comment by anurse** [comment]
This isn't specific to build-time dependencies. This is just an issue with project-to-project references of sources projects.
