### ISSUE TITLE
#882 still can repro

### ISSUE THREAD

**Issue by weidazhao** [dotnet/cli#1094]
I'm using the following version of DotNet CLI:

d53b405ebd451b537636c7fcafa8697b69c85cf2
1.0.1.001134

The build still can repro https://github.com/dotnet/cli/issues/882.

Repro steps:
1. Unzip [repro.zip](https://github.com/dotnet/cli/files/108695/repro.zip)
2. dotnet restore
3. dotnet compile

Check out bin\Debug\net451\Microsoft.Extensions.DependencyModel.dll. It is not compatible with .NET 4.5.1.

**Comment by piotrpMSFT** [comment]
@davidfowl it looks like this may have been regressed by #1067. This scenario was validated after #989

**Comment by davidfowl** [comment]
@weidazhao if it still repros, reopen this issue.
