### ISSUE TITLE
Adding child processes to job objects prevents them from creating job objects of their own

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#10947]
We are hitting an issue while trying to test AspNetCore Module for IIS Express on Windows 7/2008R2 after taking and SDK with https://github.com/dotnet/cli/pull/10720 change.

In the test, we start IIS Express process that spawns new indstance of dotnet.exe, tries to attach it to a job object and fails because the entire process tree is already attached to the job object that CLI has created.

I see couple possible solutions:
1. Disable process tracking using job objects on Windows 7
2. Set `JOB_OBJECT_LIMIT_BREAKAWAY_OK` flag set on the job object.

cc @peterhuene @danmosemsft

**Comment by peterhuene** [comment]
Which process are you attempting to add to a job object? IIS, dotnet, or the process spawned by dotnet?

I assume this is via a `dotnet run`?

**Comment by peterhuene** [comment]
We should probably be setting `JOB_OBJECT_LIMIT_BREAKAWAY_OK` anyway to better support Windows 7 (later versions support nesting jobs) so if a child process really is trying to break away, we allow it to do so.

Regardless, depending on what this test is expecting, that might not help this test's scenario.

**Comment by pakrym** [comment]
> Which process are you attempting to add to a job object

dotnet.exe spawned by IIS Express

> I assume this is via a dotnet run?

dotnet test -> test assembly -> IIS Extpress -> CreateProcess(dotnet.exe)

> Regardless, depending on what this test is expecting, that might not help this test's scenario.

It wouldn't immediately help because we are not actively trying to break away but would at least allow us to do something to get the test working.

**Comment by pakrym** [comment]
> later versions support nesting jobs

I'm not able to find info about this anywhere

**Comment by peterhuene** [comment]
For reference: https://docs.microsoft.com/en-us/windows/desktop/procthread/nested-jobs

**Comment by pakrym** [comment]
> For reference: https://docs.microsoft.com/en-us/windows/desktop/procthread/nested-jobs

It says "Windows 7, Windows Server 2008 R2, Windows XP with SP3, Windows Server 2008, Windows Vista and Windows Server 2003: A process can be associated with only a single job. Nested jobs were introduced in Windows 8 and Windows Server 2012."

**Comment by peterhuene** [comment]
Right, versions later than 7 (i.e. 8+) support nested jobs.

**Comment by pakrym** [comment]
> Right, versions later than 7 (i.e. 8+) support nested jobs.

Sorry, I misread.

**Comment by peterhuene** [comment]
I'd have to have to change how IIS express creates process to fix the test.

I think given Windows 7's impending EOL (9 months to go :tada), limiting the job object usage to 8+ would be acceptable.

**Comment by peterhuene** [comment]
I'll get that fix ready.

**Comment by pakrym** [comment]
Thank you!

**Comment by peterhuene** [comment]
I've put up PR #10949.

**Comment by peterhuene** [comment]
The fix to limit the job object usage to Windows 8+ is now in master, which is currently our preview 4 branch.
