### ISSUE TITLE
SDK should use Microsoft.Net.Compilers.Toolset package

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#10948]
The Roslyn team is deprecating the Microsoft.NETCore.Compilers package which contained only CoreCLR binaries and moving to Microsoft.Net.Compilers.Toolset which contains desktop and CoreCLR binaries. The SDK should switch to using this package when taking new Roslyn drops. 

@nguerrera is aware of this change.

**Comment by livarcocc** [comment]
We have made this change on dotnet/toolset.

**Comment by nguerrera** [comment]
@livarcocc We have? I'm not finding the change. Can you link to it?

**Comment by nguerrera** [comment]
We're still using Microsoft.NETCore.Compilers. Putting in 3.1.2xx and self-assigning.

**Comment by livarcocc** [comment]
@nguerrera this is now done, right? Should we close this issue?

**Comment by nguerrera** [comment]
Yeo
