### ISSUE TITLE
dotnet Release Metadata 3.0.0-preview3-27503-5 missing hash

### ISSUE THREAD

**Issue by tonycoelho** [dotnet/cli#10941]
The latest 3.0 release listed in the release metadata json file located at the link below, 3.0.0-preview3-27503-5 (aka 3.0.0-preview3), is missing the hash value on every file listed in the runtime, sdk, and aspnetcore-runtime file collections.

https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.0/releases.json

The hash property should contain the SHA256 hash for the file provided at the URL. Example of the issue below.
```json
{
  "name": "dotnet-runtime-linux-arm.tar.gz",
  "rid": "linux-arm",
  "url": "https://download.visualstudio.microsoft.com/download/pr/61afd68a-0079-45a3-917a-b8cb679fdc43/d3b8792106bbcc4b790407365fd025ac/dotnet-runtime-3.0.0-preview3-27503-5-linux-arm.tar.gz",
  "hash": ""
}
```

@leecow

**Comment by leecow** [comment]
@vivmishra

**Comment by leecow** [comment]
https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/3.0/releases.json good to go. Vivek, the github copy needs to be fixed and additional specific validation of the data needs to be added to the process.
