### ISSUE TITLE
dotnet pack does not support RepositoryCommit

### ISSUE THREAD

**Issue by JanEggers** [dotnet/cli#10965]
## Expected  behavior

dotnet pack --RepositoryCommit 123 

nuget seems to support it

https://github.com/NuGet/docs.microsoft.com-nuget/pull/708

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7866

**Comment by JanEggers** [comment]
why is this nuget and not dotnet?

**Comment by livarcocc** [comment]
Because even though this is surfaced through dotnet, the code for it is owned by the NuGet team.
