### ISSUE TITLE
dotnet pack does not support owners property

### ISSUE THREAD

**Issue by rjgotten** [dotnet/cli#10964]
## Steps to reproduce
Try to create a package with `dotnet pack` based on `csproj` metadata properties.
Try to define owners separate from authors. E.g. where a package has a wide group of contributors but a limited set of core maintainers (or a company or other entity) that have full ownership.

## Expected  behavior
There should be an `<Owners>` metadata property in the `csproj` format which maps to the `<owners>` node in the `nuspec` format.

## Actual behavior
There is no way to set owners separate from authors without resorting to using an external `nuspec` file.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.504
 Commit:    91e160c7f0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.504\

Host (useful for support):
  Version: 2.1.8
  Commit:  209f8aa25c
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7865
