### ISSUE TITLE
Self Contained Publish & MacOS Store Submission (System.Security.Cryptography.Native.OpenSsl.dylib)

### ISSUE THREAD

**Issue by warrenbuckley** [dotnet/cli#10977]
## Background
I am currently building a cross platform Electron app that uses a .NET Core and Kestrel for a localhost WebAPI for .NET Core to do the lifting & processing that will communicate over HTTP in the HTML/JS of the Electron application.

Building the application and running this works perfectly fine, however when the application is submitted to Apple's AppStore for Review I get the following error from them.

## Response from Apple's App Review Team 🍎 
>Your app uses or references the following non-public APIs:
>Symbols: _EVP_sha384, _EVP_sha256, _EVP_sha512
>From framework: @rpath/libcrypto.1.0.0.dylib
>In binary: >Contents/Resources/LogViewer.Server/bin/dist/osx/System.Security.Cryptography.Native.OpenSsl.dylib

As `System.Security.Cryptography` is part of the .NET Core framework that I need to ship & bundle as part of the application (as I have no guarantee of .NET Core being installed on users machines)

Are there any suggestions on what I can do?
Thanks :)

## Steps to reproduce ⚒ 
If you wish you can clone my repository for the project here
https://github.com/warrenbuckley/Compact-Log-Format-Viewer/

In the `LogViewer.Server` folder run the dotnet CLI publish command as follows:
`dotnet publish --runtime osx-x64 --output bin/dist/osx`

### CSProj & Nuget References
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <PropertyGroup>
    <!--<RuntimeIdentifiers>win10-x64;osx.10.11-x64</RuntimeIdentifiers>-->
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
    <PackageReference Include="Serilog.Filters.Expressions" Version="2.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact.Reader" Version="1.0.3" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
  </ItemGroup>

</Project>
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by warrenbuckley** [comment]
## Update
So I have tried to do some work on this in the hope that I was not going to include the OpenSSL

I updated my CSProj to be more specific with which Nuget packages/references I add. In the hope that when it gets created as a self contained application, that this was an extra dependancy and not a part of the full .NETCore runtime in `Microsoft.AspNetCore.App`

My CSProj looks like so:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.2.0" />
    <PackageReference Include="Serilog.Filters.Expressions" Version="2.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact.Reader" Version="1.0.3" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
  </ItemGroup>

</Project>
```

I added Mvc.Core to my project as opposed to just MVC as from what I could tell it was `Microsoft.AspNetCore.Mvc` that contained a NuGet reference to `System.Security.Cryptography.OpenSsl`

After republishing the project on OSX, I still get the same file on disk which the Apple AppStore review team will complain about.

**Comment by livarcocc** [comment]
How are you publishing your application? Are you publishing a self-contained app? I am not sure there is much we can do here though. That's how the framework is defined.

**Comment by warrenbuckley** [comment]
@livarcocc yes I am publishing as a self contained .NET Core app to be included in the Electron application which is then packaged up ready for Mac Store submission.

It works lovely but just means I can't ever submit an Electron MacOS app that uses .NET Core

Niave question, is it possible to exclude parts of the framework when packing as self contained app that I am not using, such as the OpenSSL stuff, as I am not doing anything with SSL in Kestrel as its a http call from the Electron UI layer to the .NET Core app.

**Comment by warrenbuckley** [comment]
But to answer your question @livarcocc I use the following command on OSX to publish

`dotnet publish --runtime osx-x64 --output bin/dist/osx`

**Comment by livarcocc** [comment]
I guess you could try a trimmer, something like this:

```
dotnet add package Microsoft.Packaging.Tools.Trimming -v 1.1.0-preview1-25818-01
dotnet publish -runtime osx-x64 --output bin/dist/osx /p:TrimUnusedDependencies=true
```

But as you can see, it is currently a preview and hasn't an official release, but maybe solves your problem.

**Comment by warrenbuckley** [comment]
Thanks @livarcocc I have given that a go and it seems to have removed it
If anyone comes across this issue or similar later on - documentation for **Microsoft.Packaging.Trimming** is here

https://github.com/dotnet/standard/blob/release/2.0.0/Microsoft.Packaging.Tools.Trimming/docs/trimming.md

I will re-submit this to Apple AppStore & see what they say now :)

**Comment by livarcocc** [comment]
Do you want us to wait before closing this issue or Ok to close now?

**Comment by warrenbuckley** [comment]
@livarcocc would you mind waiting until I hear back, as I have a gut feeling that their may complain about some other bits that are shipped for the .NET Core framework.

As soon as I have an answer I will update & or close the issue

**Comment by livarcocc** [comment]
@warrenbuckley sure thing. Let me know if anything else comes up.

**Comment by warrenbuckley** [comment]
@livarcocc closing this up. As Apple seemed happy once Package Trimming was done. I may re-open this if they have any other concerns thats related to the files shipped as part of .NET Core Framework

**Comment by dasMulli** [comment]
This worries me a little..
In an ideal world, doing a `dotnet publish` on an "empty" application shouldn't contain things that don't get through the App Store review process. The problem will still exist in netcoreapp3.0.

The use case for Electron-based apps is very appealing and I hope we will see this being used a lot more, esp. with razor components.

The problem here is that the native library used for OpenSSL interop is still included in netcoreapp3.0 AND uses symbols that apple deems private API, although I'm pretty confident that there isn't any private API usage here, just symbols that OpenSSL has that also exist in Apple's crypto stack internally (Apple's symbol screening only looks at names, not actual usage - this has bitten me before writing ordinary iOS apps and just naming properties "uniqueIdentifier" 😢).

cc @karelz who I hope can help in routing this.

**Comment by karelz** [comment]
@bartonjs do you know why we include OpenSSL on Mac? I thought we rely on only on native APIs these days ...

**Comment by bartonjs** [comment]
We have lightup support for using OpenSSL as an optional component via RSAOpenSsl, DSAOpenSsl, ECDsaOpenSsl and ECDiffieHellmanOpenSsl.

Unless a project is using those types specifically OpenSSL won't get touched.
