### ISSUE TITLE
'Exec format error' when running global tool on ARM32

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#10985]
Installing a global tool on ARM32 doesn't run.  Fails with `cannot execute binary file: Exec format error`.

# Repro Steps
1. Requirement - run from an ARM32 machine.  
1. docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:3.0
1. dotnet tool install --tool-path /mytool <some tool>
1. cd /mytool 
1. execute installed tool

# Results

cannot execute binary file: Exec format error`

# Expected Results

The tool should run

# Observations
1. I verified this scenario works for 2.1 but not 3.0.
1. The app will run if you path down to the .store/.../tools folder and run dotnet/tool.dll
1. This was discovered with testing installing PowerShell as a global tool - https://github.com/dotnet/dotnet-docker/pull/960#discussion_r266060183.  PowerShell in this case is built against 2.1 but has a custom roll forward policy defined - https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md.  I don't know if that is a factor or not.  It works just find in amd64.

**Comment by livarcocc** [comment]
@wli3

**Comment by wli3** [comment]
i need to dig a bit. And how do you get a ARM32 machine btw?

**Comment by MichaelSimons** [comment]
A couple other points.

1. I saw the same behavior if the tool was installed as a global tool.
2. I was able to repo the same behavior on ARM32 with dotnetsay.  Note however dotnetsay is expected to fail resolving the runtime version.

Regarding an ARM32 machine, the easiest is to find a Raspberry PI.  I have one I could grant you access to although I am remote so access is a little slower.  I think @richlander could also help you out as well.

**Comment by richlander** [comment]
This could be related ... https://github.com/dotnet/coreclr/issues/23296

I have a number of Pi machines on my desk. You can just grab one if you'd like.

**Comment by adityapatwardhan** [comment]
@adityapatwardhan Tagging myself to get notifications on this issue.

**Comment by MichaelSimons** [comment]
@wli3 - Any update on this?  This is blocking a 3.0-preview4 .NET Docker feature.

**Comment by wli3** [comment]
sorry i have no update. I'll look into it today

**Comment by richlander** [comment]
I just tried running a tool on ARM32 (no containers). It works.

**Comment by MichaelSimons** [comment]
I tried the PS global tool scenario in an ARM32 container and this issue no longer reproduces.  

This issue appears resolved.

**Comment by wli3** [comment]
Awesome, thanks @richlander
