### ISSUE TITLE
Understanding use of Nuget.exe in restore command

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/cli#11005]
From documentation of [dotnet restore](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x), it says:

>The dotnet restore command uses NuGet to restore dependencies 

Does `dotnet`
* uses `nuget.exe` found in `PATH` or 
* ships `nuget.exe` with itself or 
* consumes nuget as library in dotnet binary ?

I need this information to understand if failure of dotnet restore can be changes in my `PATH` corruption or not ?

**Comment by dasMulli** [comment]
`dotnet` uses a NuGet version local to the installation of the .NET Core SDK.

No change in `PATH` should (🤞) affect the restore once the SDK is resolved by dotnet.exe.

Internally, this is done via MSBuild targets that use NuGet as a library. `dotnet restore` is equivalent to calling `dotnet msbuild -t:Restore` (with additional translation of parameters into msbuild property parameters).

**Comment by ashishnegi** [comment]
@dasMulli Thanks for info.
Is NuGet a binary or library in dotnet restore case ?

**Comment by livarcocc** [comment]
It is a library.
