### ISSUE TITLE
DotnetCliTool references don't work if BaseIntermediateOutputPath is changed in a Directory.Build.props file.

### ISSUE THREAD

**Issue by JeremyMorton** [dotnet/cli#11006]
## Steps to reproduce
I have a hard time coming up with a public repro, since I don't know of public DotnetCliTools; I'm hitting this with an internal one.

I tried debugging dotnet.exe, but build.cmd doesn't make a dotnet.pdb and I can't build in VS nor Rider in order to be able to run under a debugger (nor does `dotnet build` work, ironically).

* Add a reference to a DotnetCliTool and a target to run it to your .csproj:
```XML
  <ItemGroup>
    <DotNetCliToolReference Include="MyDotnetCliTool" Version = "1.0.0" />
  </ItemGroup>

  <Target Name="RunMyDotnetCliToolForTargetFramework" DependsOnTargets="RunMyDotnetCliTool" BeforeTargets="BeforeBuild" Condition="'$(TargetFrameworks)' == ''" />
  <Target Name="RunMyDotnetCliToolForTargetFrameworks" DependsOnTargets="RunMyDotnetCliTool" BeforeTargets="DispatchToInnerBuilds" Condition="'$(TargetFrameworks)' != ''" />
  <Target Name="RunMyDotnetCliTool">
    <Exec WorkingDirectory="$(MSBuildProjectDirectory)" Command="dotnet -d mydotnetclitool" />
    <Message Text="Ran dotnet -d mydotnetclitool" Importance="High" />
  </Target>
```
* Run `dotnet build` and it will find and run `dotnet -d mydotnetclitool` successfully.
* *IMPORTANT* Delete the `obj` subdirectory that the above, successful run created.
* Create a Directory.Build.props, as that is the mechanism to override BaseIntermediateOutputPath.
```XML
<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>c:/build_directories/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```
* Create the `c:/build_directories/obj/` directory.
* Run `dotnet build` and it will fail to find `dotnet-mydotnetclitool.dll` when it tries to run `dotnet -d mydotnetclitool`

## Expected  behavior
That it finds the `dotnet-mydotnetclitool.dll` that the DotnetCliToolReference brought down to the machine.
```
  Persisting no-op dg to C:\projects\MyProgram\src\Project1\Project1.csproj.nuget.dgspec.json
  Restore completed in 829.89 ms for C:\projects\MyProgram\src\Project1\Project1.csproj.
  Restore completed in 902.96 ms for C:\projects\MyProgram\src\Project1\Project1.csproj.
  Telemetry is: Enabled
  projectfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\2.2.104\MSBuild.dll
  projectfactory: MSBuild project path = C:\projects\MyProgram\src\Project1\Project1.csproj
  projecttoolscommandresolver: resolving commandspec from 1 Tool Libraries.
  projecttoolscommandresolver: Attempting to resolve command spec from tool MyDotnetCliTool
  projecttoolscommandresolver: nuget packages root:
  - C:\Users\jmorton\.nuget\packages\
  - C:\Program Files\dotnet\sdk\NuGetFallbackFolder
  projecttoolscommandresolver: found tool lockfile at : C:\Users\jmorton\.nuget\packages\.tools\MyDotnetCliTool\1.0.0\netcoreapp2.2\project.assets.json
  projecttoolscommandresolver: expect deps.json at: C:\Users\jmorton\.nuget\packages\.tools\MyDotnetCliTool\1.0.0\netcoreapp2.2\MyDotnetCliTool.deps.json
  projecttoolscommandresolver: attempting to create commandspec
  packagedcommandspecfactory: attempting to find command dotnet-mydotnetclitool in MyDotnetCliTool
  PackagedCommandSpecFactory: Looking for prefercliruntime file at `C:\Users\jmorton\.nuget\packages\MyDotnetCliTool\1.0.0\lib\netcoreapp2.0\..\..\prefercliruntime`
  Running C:\Program Files\dotnet\dotnet.exe exec --depsfile C:\Users\jmorton\.nuget\packages\.tools\MyDotnetCliTool\1.0.0\netcoreapp2.2\MyDotnetCliTool.deps.json --additionalprobingpath C:\Users\jmorton\.nuget\packages --additionalprobingpath "c:\Program Files\dotnet\sdk\NuGetFallbackFolder" C:\Users\jmorton\.nuget\packages\MyDotnetCliTool\1.0.0\lib\netcoreapp2.0\dotnet-mydotnetclitool.dll
  Process ID: 12708
  Ran dotnet -d mydotnetclitool
  Project1 -> C:\projects\MyProgram\src\Project1\Project1\bin\Debug\netcoreapp2.1\Project1.dll
```

## Actual behavior
It fails to find `dotnet-mydotnetclitool.dll` if, and only if, the `dotnet restore` was ran with `BaseIntermediateOutputPath` redirected to another location:
```
  Persisting no-op dg to C:\projects\MyProgram\src\Project1\Project1.csproj.nuget.dgspec.json
  Restore completed in 829.89 ms for C:\projects\MyProgram\src\Project1\Project1.csproj.
  Restore completed in 902.96 ms for C:\projects\MyProgram\src\Project1\Project1.csproj.
  Telemetry is: Enabled
  projectfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\MSBuild.dll
  projectfactory: MSBuild project path = C:\projects\MyProgram\src\Project1\Project1.csproj
  projecttoolscommandresolver: resolving commandspec from 1 Tool Libraries.
  projecttoolscommandresolver: Attempting to resolve command spec from tool MyDotnetCliTool
  projecttoolscommandresolver: nuget packages root:

  projecttoolscommandresolver: failed to resolve commandspec from library.
  Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-mydotnetclitool". See https://aka.ms/missing-command for more information.
     at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
     at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
     at Microsoft.DotNet.Cli.Program.Main(String[] args)
C:\projects\MyProgram\src\Project1\Project1.csproj(126,5): error MSB3073: The command "dotnet -d mydotnetclitool" exited with code 1. [C:\projects\MyProgram\src\Project1\Project1.csproj]

Build FAILED.
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
This also occurred without a global.json:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19153-02 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview3-27503-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview3-27504-2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by JeremyMorton** [comment]
BTW, https://aka.ms/missing-command redirects to https://www.microsoft.com/en-us/ for me, so that may need to be fixed/updated.

**Comment by livarcocc** [comment]
@wli3 can you take a look?

**Comment by wli3** [comment]
Sorry for the delay.

I cannot reproduce it with my hello world project tools. However, from you log, 
```projecttoolscommandresolver: nuget packages root:```

It is empty. Did you also override other properties like `globalPackagesFolder` of nuget or `RestorePackagesPath`?

**Comment by JeremyMorton** [comment]
No, I don't override those.

**Comment by wli3** [comment]
@JeremyMorton maybe it is the SDK version? I find you "actual case" uses "3.0.100-preview3-010431". And we did have a bug in early 3.0.1xx SDK related to project tools. Could you try to update it to the latest preview or try to restore it with global.json?

**Comment by JeremyMorton** [comment]
It has the same result with the global.json set to 2.2.104.
Also, that's the latest 3.0 preview version.

**Comment by wli3** [comment]
Sorry. I still have not method to repro. What is the exact project tool you are using? And where is your `Directory.Build.props` created? Under C:\projects\MyProgram\src\Project ?

If is ok, could you send me the binlog (run dotnet build /bl and it will generate a .binlog file) to wul at microsoft.com ?

**Comment by wli3** [comment]
close due to the lack of a repro

**Comment by rezna306601261** [comment]
Hi wli3, I would like to reopen that issue as I have ran into the same situation. I'm attaching a minimalistic solution for repro.

[TestProjForRepro.zip](https://github.com/dotnet/cli/files/3578775/TestProjForRepro.zip)

I'm using .NET core 2.2.106 to build it. Now the repro. I always assume I start in the directory where *.sln is, and that the 'bin' and 'obj' folders are deleted -> so I have a clear environment for the test

1) success for the debug build
`dotnet build -c Debug`
`cd TestProjForRepro`
`dotnet dotcover test -c Debug`

this works perfectly normal

2) failure for the release build
`dotnet build -c Release`
`cd TestProjForRepro`
`dotnet dotcover test -c Release`

this is were I fail

> c:\SB\TestProjForRepro\TestProjForRepro>dotnet -d dotcover test -c Release
> Telemetry is: Enabled
> projectfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\2.2.106\MSBuild.dll
> projectfactory: MSBuild project path = c:\SB\TestProjForRepro\TestProjForRepro\TestProjForRepro.csproj
> projecttoolscommandresolver: resolving commandspec from 1 Tool Libraries.
> projecttoolscommandresolver: Attempting to resolve command spec from tool JetBrains.dotCover.CommandLineTools
> projecttoolscommandresolver: nuget packages root:
> 
> projecttoolscommandresolver: failed to resolve commandspec from library.
> Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-dotcover"
>    at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
>    at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)

3) success if I build both
`dotnet build -c Debug`
`dotnet build -c Release`
`cd TestProjForRepro`
`dotnet dotcover test -c Release`

runs perfectly normal.

I assume the issue lies somewhere here - https://sourcegraph.com/github.com/dotnet/cli@0eaf15fbd50fc04fc702034618b1a104b710ef17/-/blob/src/dotnet/CommandFactory/CommandResolution/MSBuildProject.cs#L167:21

Can you have a look? I would like to help by being able to output the complete set of properties that are available during the 'dotnet dotcover' execution because the problem lies somewhere there. What I might try to do to circumvent this situation is to set `ProjectAssetsFile` in Directory.Build.props file as well.

Thanks a lot, Milan

**Comment by rezna306601261** [comment]
I was wondering what's happening and why 'Debug' works, here's what procmon sees. Even though I'm trying to run Release version it searches the Debug folder

![procmon](https://user-images.githubusercontent.com/18053378/64342930-d63b8580-cfeb-11e9-964f-63729c771dd0.PNG)

**Comment by rezna306601261** [comment]
Continued debugging the dotnet.exe tool 2.2.106 and here it comes

`CommandResult result = Command.Create(`
`                        "dotnet-" + topLevelCommandParserResult.Command,`
`                        appArgs,`
`                        FrameworkConstants.CommonFrameworks.NetStandardApp15)`
`                    .Execute();`

Command.Create actually has more argument and one of them is Configuration, which this way is being set to 'Debug' as default. And from command-line I cannot fix it :(

**Comment by rezna306601261** [comment]
A workaround I have found is to set also 

`<MSBuildProjectExtensionsPath>$(SolutionDir)\obj\Shared\$(MSBuildProjectName)\</MSBuildProjectExtensionsPath>`

So the extensions path is configuration agnostic. Then it works.
