### ISSUE TITLE
"dotnet restore" doesn't work with VSO (VSTS) package feeds

### ISSUE THREAD

**Issue by neilhuiz** [dotnet/cli#1102]
I originally filed this against DNU (https://github.com/aspnet/dnx/issues/3314). The same issue exists in the latest bits when you run "dotnet restore". The logging is not nearly as verbose, but still a 401 when using a plain text password and "Specified method is not supported" when using an encrypted password. Nuget.exe does not display the same behavior and succeeds in restoring packages for the project.json with either plain text or encrypted passwords.

I can see that the dotnet-restore project relies on the NuGet XPlat library so its possible that's where the issue lies. Even with verbose output, I can't be sure, though.

**Comment by brthor** [comment]
I ran into this issue a while back and it looked like the method NuGet XPlat relied on in CoreCLR for crypto simply was not implemented.

**Comment by neilhuiz** [comment]
For the encrypted password, that sounds like a good explanation. The behavior when using a plain text password is also broken, though and I don't see a workaround. Is there a divergence between the XPlat library and NuGet.exe?

**Comment by brthor** [comment]
I would expect so, though I'm not too familiar with that code. 

@emgarten Could provide much better information :smile:

**Comment by emgarten** [comment]
Auth support in NuGet xplat is in the works.
https://github.com/NuGet/Home/issues/1988

**Comment by blackdwarf** [comment]
Should we close this and/or move it to nuget repo?

**Comment by blackdwarf** [comment]
OK, closing this since this is Nuget work and @emgarten mentioned that it is being tracked at Nuget.

**Comment by emgarten** [comment]
Basic auth has been added to dotnet restore. Encrypted passwords in nuget.config are not supported, the libraries needed do not exist in the CLI yet, but NuGet is looking at ways to fix this.

**Comment by DamianReeves** [comment]
This still seems to be an issue (any updates)? Plain text and authenticated feeds are failing.

**Comment by emgarten** [comment]
@DamianReeves please open a new issue on http://github.com/NuGet/Home/issues if you are still having trouble using basic auth with dotnet restore.
