### ISSUE TITLE
Signing of the CoreHost

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1103]
A publishable version of the CoreHost should not be signed, but the dotnet-commands corehost have to be signed. The signed corehost should load only signed command DLLs.

**Comment by schellap** [comment]
Cc @piotrpMSFT and @livarcocc

**Comment by schellap** [comment]
Moving to RTM.

**Comment by gkhanna79** [comment]
@Sridhar-MS Assigning this to you per our discussion today.

**Comment by piotrpMSFT** [comment]
@schellap has the work to:
>  The signed corehost should load only signed command DLLs.
been done? Are we ready to have dotnet.exe signed?

**Comment by schellap** [comment]
dotnet.exe cannot be signed because the process has to load arbitrary user DLLs.
Example: `dotnet user-app.dll`

This bug was before the Shared Framework days when we only had standalone applications and is obsolete in the new model.

**Comment by schellap** [comment]
@leecow, @piotrpMSFT, @gkhanna79 if there are no objections with the reasoning above, I will close this out.

**Comment by gkhanna79** [comment]
Sounds fine to me.
