### ISSUE TITLE
dotnet restore --interactive: 401 Unauthorized on Windows with Azure DevOps feed

### ISSUE THREAD

**Issue by dylank** [dotnet/cli#11055]
## Steps to reproduce

dotnet restore always fails on Windows when connecting to a private feed hosted on ADO.

```
>dotnet restore --interactive
  Restoring packages for ....csproj...
  Restoring packages for ...csproj...
C:\Program Files\dotnet\sdk\2.2.104\NuGet.targets(114,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/microsoft/_packaging/something/nuget/v3/index.json. [....sln]
C:\Program Files\dotnet\sdk\2.2.104\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [....sln]
```

## Expected  behavior
Running `dotnet restore --interactive` should prompt for code auth, like it does on macOS. Alternatively, running `dotnet restore` should behave like `nuget restore` does, and prompt for credentials allowing you to enter a PAT.

## Actual behavior
On Windows 10, running `dotnet restore --interactive` or `dotnet restore` will always fail when connecting to a private feed on ADO.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by dylank** [comment]
As a workaround, running `nuget restore` in the dotnet core project will take a PAT token, and allow you connect to a private feed.

**Comment by peterhuene** [comment]
@wli3 and @nkolev92 can you take a look at what might be going wrong here?

**Comment by nkolev92** [comment]
> Running dotnet restore --interactive should prompt for code auth, like it does on macOS.

Do you have a plugin configured? How did you configure the plugin?

> Alternatively, running dotnet restore should behave like nuget restore does, and prompt for credentials allowing you to enter a PAT.

This is something that dotnet.exe doesn't do. No interactive prompts that prompt for commandline input. This was a conscious decision.

**Comment by dylank** [comment]
No I don't have any plugins configured.

Can we add support for accepting credentials via a switch?

**Comment by nkolev92** [comment]
@dylank 

Is your provide feed azure devops? 

If it is, then you need to install the credential provider from https://github.com/Microsoft/artifacts-credprovider.

**Comment by dylank** [comment]
Thanks, I'll IM you the feed I'm using. Still unsure why `--interactive` works on macOS but not on Windows.

**Comment by dylank** [comment]
Turns out I had the cred provider plugin already installed on macOS, which is why --interactive was working.
