### ISSUE TITLE
Comments in .runtimeconfig.dev.json dont seem to work

### ISSUE THREAD

**Issue by Meai** [dotnet/cli#11059]
## Steps to reproduce
Comments in the json file make it not find assemblies in the `/home/pc/.nuget/packages/` folder.
But Visual Studio 2019 community edition does not complain about the comments in the .json file. So you can decide who here made the mistake and give somebody else this issue but at least by default print out the used probing paths if an assembly wasn't found, in my opinion that is the least that the cli should be doing. Because my suspicion is that whatever JSON parser you are using is erroring out internally and then you just use the default nuget folders and then it wont find everything it needs to run - silently...

```
{
  "runtimeOptions": {
    "additionalProbingPaths": [
      //"/home/pc/workarea/software/dotnet/sdk/NuGetFallbackFolder",
      "/home/pc/.nuget/packages"
    ]
  }
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /home/pc/workarea/software/dotnet/sdk/2.2.105/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [/home/pc/workarea/software/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/home/pc/workarea/software/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/home/pc/workarea/software/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/home/pc/workarea/software/dotnet/shared/Microsoft.NETCore.App]




```

**Comment by peterhuene** [comment]
Issue moved to [dotnet/core-setup #5661](https://github.com/dotnet/core-setup/issues/5661) via [**ZenHub**](https://www.zenhub.com/)

**Comment by peterhuene** [comment]
Hi @Meai.  Thanks for reporting this to us.  This file is used by the .NET Core host which is in the `dotnet/core-setup` repo.  I'm going to move this issue there.
