### ISSUE TITLE
CLI build scripts: add ability to turn individual build steps on / off to enable quick dev cycle

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#1106]
It would be nice to have a set of flags that trigger different build stages: restore, stage0, stage1, stage2, test, pack, all. While coding one could just call build -stage2 -test. For a clean build one could do build -all. Or something like that.

The dev cycle would become much easier: `...write code...` + `build.cmd -stage2 -test` + `...write more code` + `build.cmd -stage2 -test`

**Comment by livarcocc** [comment]
We will get that with MSBuild. You can specify any target. We have that in the feature/msbuild branch. Plus, our current one, using CSharp also allows for some degree of target specification.
