### ISSUE TITLE
Dotnet not rolling forward

### ISSUE THREAD

**Issue by michaelveloz** [dotnet/cli#11066]
## Steps to reproduce
I created a simple app that targeted .net core 2.1.0 using Visual Studio under windows and used "publish" to produce a framework dependent app, which I then copied over to a unix machine which has .net core 2.1.105 installed.

## Expected  behavior
I expected dotnet to run my 2.1.0-targeted app against 2.1.105 as per this doc: https://docs.microsoft.com/en-us/dotnet/core/versions/selection which describes apps rolling forward

## Actual behavior
Error message "Microsoft.NETCore.App version 2.1.0 was not found... check depdenceies.. or install framework 2.1.0

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  19
 OS Platform: Linux
 RID:         linuxmint.19-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by peterhuene** [comment]
Hi @michaelveloz.  Unfortunately there's some confusion with older versions of the .NET Core SDK here (not your fault as the SDK version numbers were not consistent with the .NET Core version).

The 2.1.105 SDK is actually a .NET Core *2.0* SDK (specifically, as you'll see in your `--info` output, 2.0.7 is the host version).

The first .NET Core SDK that is meant for .NET Core 2.1 is `2.1.300`.   If you install a 2.1-based .NET Core SDK or runtime, you should observe the correct roll-forward behavior.

I'm going to close this issue for now.  Please reactivate if you're still having problems after updating to a 2.1.300 or later SDK (currently, [2.1.505 is the latest .NET Core 2.1 SDK](https://dotnet.microsoft.com/download/dotnet-core/2.1)).
