### ISSUE TITLE
global nuget.config not being used on run

### ISSUE THREAD

**Issue by kavitachana** [dotnet/cli#11073]
## Steps to reproduce
I created a tool path for Jenkins to use ( /opt/jenkins/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/DotNet_2.1.403/xdgDataHome) and set the environment variable XDG_DATA_HOME to that tool path.

## Expected  behavior
When I run restores without a Nuget.config in the project or workspace, I expect it to use the global nuget.config I created in xdgDataHome which contains the location I want the dependencies pulled.

## Actual behavior
On run, I get multiple failures, and it does not use the nuget.config I created. Instead it tries to pull dependencies from the default location (https://api.nuget.org/v3/index.json ).

Shouldn't this work with a dotnet cli on a linux server?

**Comment by dnbr2002** [comment]
I wonder if this XDG_DATA_HOME env var even applies to the dotnet cli?  It's listed in the nuget docs [here](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) but when running restores with dotnet cli will is use this same Global env var or is this only for use with nuget cli commands?

**Comment by dnbr2002** [comment]
This may be a linked issue?? 

https://github.com/NuGet/Home/issues/7839

**Comment by peterhuene** [comment]
Hi @kavitachana.  To me, this sounds like a NuGet issue.  As such, I'm going to move this issue to their issue tracking repository.  Thank you!

**Comment by peterhuene** [comment]
This issue was moved to NuGet/Home#7980
