### ISSUE TITLE
flaky test ItIgnoresSIGINT

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#11088]
I need to rerun the test to keep auto merge go though. ItIgnoresSIGINT happens several times

**Comment by wli3** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=145868&view=ms.vss-test-web.build-test-results-tab

**Comment by wli3** [comment]
Expected command to exit with 42 but it did not.\nFile Name: /Users/vsts/agent/2.149.2/work/1/s/artifacts/tmp/Release/dotnet/dotnet\nArguments: run \nWorkingDir:: /Users/vsts/agent/2.149.2/work/1/s/artifacts/tmp/Release/test/dotnet-run.Tests/ItIgnoresSIGINT/TestAppThatWaits\nExit Code: 130\nStdOut:\n2448\nInterrupted!\nStdErr:\n\n

**Comment by peterhuene** [comment]
Hmm, the fix for the flakiness went in weeks ago to master.  I'm not sure why it'd become flaky again.

**Comment by peterhuene** [comment]
See https://github.com/dotnet/cli/pull/10921.  I haven't seen the problem in master since.

**Comment by wli3** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=145868&view=ms.vss-test-web.build-test-results-tab this is a test in master failed 4 hours ago. And I manually kicking retry test this week. I did see this test several times in master.

**Comment by peterhuene** [comment]
Now that the fix is in all 3.0 branches, let's keep an eye out for more flakiness.  I'm surprised that it suddenly cropped back up.

**Comment by peterhuene** [comment]
Saw the test fail again with https://dev.azure.com/dnceng/public/_build/results?buildId=158319

**Comment by peterhuene** [comment]
I haven't seen this fail in a while and I haven't disabled the test.  Perhaps the failing CI didn't have the fix at the time.  I'm going to close for now but keep my eyes out.

**Comment by peterhuene** [comment]
Just saw another failure here: https://dev.azure.com/dnceng/public/_build/results?buildId=221133&view=ms.vss-test-web.build-test-results-tab&runId=5439940&resultId=100032&paneView=debug

I will disable the test tomorrow and see if I can figure out why it's still flaky.  The timing issue should have been fixed.

**Comment by peterhuene** [comment]
And another: https://dev.azure.com/dnceng/public/_build/results?buildId=224742&view=ms.vss-test-web.build-test-results-tab&runId=5538498&resultId=100032&paneView=debug
