### ISSUE TITLE
DOTNET_REFERENCE_ASSEMBLIES_PATH required when building on OS X?

### ISSUE THREAD

**Issue by scionwest** [dotnet/cli#1109]
I downloaded the [.net core bits](https://dotnet.github.io/getting-started/) tonight and got it installed on OS X 10.11. I then cloned down a .Net Core project I had created and been working on from within Visual Studio 2015. When I run `dotnet build` it fails with the error below.

    Johnathons-MacBook-Pro:Lightmap.Core johnathonsullinger$ dotnet build
    Compiling Lightmap.Core for .NETFramework,Version=v4.5.1
    /Users/johnathonsullinger/Source/GitHub/Scionwest/Lightmap/Source/Lightmap/Lightmap.Core/project.json(10,15): error DOTNET1012: The reference assemblies directory was not specified. You can set the location using the DOTNET_REFERENCE_ASSEMBLIES_PATH environment variable.

    Compilation failed.
        0 Warning(s)
        1 Error(s)

    Time elapsed 00:00:00.0201664

It looks like it's related to the 4.5.1 framework; am I wrong in assuming that `dotnet build` knows that it can compile the `dotnet5.4` framework and ignore the `4.5.1` framework?

This is my `project.json`

    {
        "version": "1.0.0-*",
        "description": "Lightmap.Core Class Library",
        "authors": [ "johna" ],
        "tags": [ "" ],
        "projectUrl": "",
        "licenseUrl": "",

        "frameworks": {
            "net451": { },
            "dotnet5.4": {
            "dependencies": {
                "Microsoft.CSharp": "4.0.1-beta-23516",
                "System.Collections": "4.0.11-beta-23516",
                "System.Linq": "4.0.1-beta-23516",
                "System.Runtime": "4.0.21-beta-23516",
                "System.Threading": "4.0.11-beta-23516"
            }
            }
        }
        }

This can be reproduced by [cloning my project](https://github.com/scionwest/lightmap) and running `dotnet build` within the `Lightmap.Core` directory.

Is there a path I am supposed to add to my `bash_profile`, and if so what goes into that path?

**Comment by davidfowl** [comment]
When you target mono (which is what you are doing) you need to set `DOTNET_REFERENCE_ASSEMBLIES_PATH`, it will never ignore those targets. You either need to set it to the mono installation (if you have it) or remove that target entirely.

**Comment by scionwest** [comment]
I can't conditionally compile a 451 framework based on the environment i'm in? For instance, compiling in Visual Studio for both 451 and dotnet5.4, then only compiling against dotnet5.4 while on my Mac?

Is the guidance at the moment, if you want to target n-frameworks, then all platforms must have a runtime/bcl for those frameworks? It's not a big deal to install Mono, I'm kind of surprised I forgot to install it with this latest OS X install. I just want to make sure I understand the limitations or requirements of multi-targeting in project.json. With PCLs I would typically just have a new .sln file that held the truly cross-plat projects, and the Windows specific stuff lived in another .sln that had all of my .csproject files under one roof

**Comment by davidfowl** [comment]
> I can't conditionally compile a 451 framework based on the environment i'm in? For instance, compiling in Visual Studio for both 451 and dotnet5.4, then only compiling against dotnet5.4 while on my Mac?

Nope.

> Is the guidance at the moment, if you want to target n-frameworks, then all platforms must have a runtime/bcl for those frameworks? It's not a big deal to install Mono, I'm kind of surprised I forgot to install it with this latest OS X install. I just want to make sure I understand the limitations or requirements of multi-targeting in project.json. 

Yes, you currently need to install mono to compile for those other platforms (non dotnet/netstandard).

> With PCLs I would typically just have a new .sln file that held the truly cross-plat projects, and the Windows specific stuff lived in another .sln that had all of my .csproject files under one roof

PCLs don't really exist as they have before in this new world and those can be built anywhere. We're still discussing if we're going to ship reference assemblies as packages to allow compilation on other platforms.

**Comment by scionwest** [comment]
> PCLs don't really exist as they have before in this new world and those can be built anywhere. We're still discussing if we're going to ship reference assemblies as packages to allow compilation on other platforms

Thinking about it after I posted, I guess it makes sense. I keep forgetting that `project.json` isn't "solution-wide". I'll just break the `451` specific stuff into it's own project and have it reference the dotnetcore50 package.

**Comment by scionwest** [comment]
@davidfowl If I were to install mono, does mono add the `DOTNET_REFERENCE_ASSEMBLIES_PATH` to my `bash_profile` or do I have to? If so, what mono path is it expecting?

**Comment by davidfowl** [comment]
osx?

export DOTNET_REFERENCE_ASSEMBLIES_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks/

**Comment by scionwest** [comment]
@davidfowl yeah OS X, thanks! I'll get those installed. 

It would be awesome if you guys do end up shipping reference assemblies as packages. I'd like to remove my dependency on Mono altogether. They do a lot of good work but lag behind to much.

**Comment by the404** [comment]
you juest remove net451 from  framework section in package.json
and dotnet build ,and dotnet run or publish,then it will be ok.
