### ISSUE TITLE
dotnet publish ignores conditions with PublishWebpack of csproj

### ISSUE THREAD

**Issue by netbitshift** [dotnet/cli#11098]
## Steps to reproduce
(1) Start a new .NET Core 2.2 web app w/angular template
(2) Add the following settings in the .csproj file (change to reflect your build configurations)

```
  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <!-- Use conditional builds based on build target setting eg.  debug, dev, prod etc -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build " Condition=" '$(Configuration)' == 'Debug' " />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build --prod false --configuration=dev" Condition=" '$(Configuration)' == 'Test' " />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build --prod true --configuration=prod" Condition=" '$(Configuration)' == 'Release' " />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:ssr --configuration=prod" Condition=" '$(BuildServerSideRenderer)' == 'true' And  '$(Configuration)' == 'Release' " />

(3) run dotnet publish -c Test
```

## Expected  behavior
correct npm command with corresponding flags (eg 
`npm run build --prod false --configuration=dev`
should be run

## Actual behavior
only `ng build` is run, seemingly ignoring the Condition attribute?

## Environment data
`dotnet --info` output:

**Comment by netbitshift** [comment]
I think I manged to find a solution.  Instead of using the extra switches in the csproj file, I made seperate npm scripts in my package.json file.  eg.

    "build": "ng build",
    "build-dev": "ng build --prod=false --configuration=dev",
    "build-prod": "ng build --prod=true --configuration=production",

This seems to be working

**Comment by peterhuene** [comment]
Hi @netbitshift.  If this is still an issue for you, would you mind including the `dotnet` command line you're using to publish your project?  Additionally, what is the output of your `dotnet --info`?

**Comment by netbitshift** [comment]
Update I posted above fixes the problem.  Not an issue with dotnet cli

**Comment by ztorstri** [comment]
> I think I managed to find a solution. Instead of using the extra switches in the csproj file, I made seperate npm scripts in my package.json file. eg.
> 
> ```
> "build": "ng build",
> "build-dev": "ng build --prod=false --configuration=dev",
> "build-prod": "ng build --prod=true --configuration=production",
> ```
> 
> This seems to be working

How do you tell the publish profile to use a different command?
