### ISSUE TITLE
dotnet add package should use use correct defaults at evaluation time

### ISSUE THREAD

**Issue by sharwell** [dotnet/cli#11101]
## Steps to reproduce

> dotnet add package coverlet.msbuild

## Expected  behavior

The default values for `IncludeAssets` and `PrivateAssets` are determined automatically during the build:

```xml
<PackageReference Include="coverlet.msbuild" Version="2.5.0" />
```

## Actual behavior

The default values for `IncludeAssets` and `PrivateAssets` clutter the project file:

```xml
<PackageReference Include="coverlet.msbuild" Version="2.5.0"> 
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets> 
  <PrivateAssets>all</PrivateAssets> 
</PackageReference> 
```

## Environment data

Unknown (filed in response to https://github.com/dotnet/winforms/pull/702#issuecomment-480903415)

**Comment by peterhuene** [comment]
The `dotnet add package` functionality actually responsible for modifying the project file lives in NuGet (in `NuGet.CommandLine.XPlat.dll`).

I'm going to move this there.

**Comment by peterhuene** [comment]
This issue was moved to NuGet/Home#7972
