### ISSUE TITLE
[loc][Query][dotnet_cli] Localizability of string: 0; "RollForwardOnNoCandidateFxDefinition"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11109]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Roll forward on no candidate shared framework is enabled.

File Name:
dotnet\commands\dotnet-help\xlf\LocalizableStrings.xlf

Resource ID:
0; "RollForwardOnNoCandidateFxDefinition"

Query:
Please, explain this sentence for our translator . Thanks

**Comment by peterhuene** [comment]
Hi @PDostalek,

The string is describing the `--roll-forward-on-no-candidate-fx` host option for `dotnet`.

It means if the option is specified, the host will roll forward to a newer shared .NET Core runtime if a candidate .NET Core runtime could not be found.

This text wasn't very descriptive, so this changed in `master` and `release/3.0.1xx` to `Roll forward on no candidate framework (0=off, 1=roll minor, 2=roll major &amp; minor).` to also include the valid values for the option.

**Comment by PDostalek** [comment]
Thanks!
