### ISSUE TITLE
dotnet add package -s

### ISSUE THREAD

**Issue by Wscar** [dotnet/cli#11114]
## Steps to reproduce
I use "dotnet add package xxx -s https://api.nuget.org/v3/index.json
 " the command to install the specified package, which has been accessing my private package source instead of https://api.nuget.org/v3/index.json

## Environment data
`dotnet --info` output:
info : 正在将包“Newtonsoft.Json”的 PackageReference 添加到项目“F:\MyProject\测试\MogoDb更新数据\MogoDb更新数据\MogoDb更新数据.csproj”。
log  : 正在还原 F:\MyProject\测试\MogoDb更新数据\MogoDb更新数据\MogoDb更新数据.csproj 的包...
info :   GET http://192.168.1.197:8082/repository/nuget-hosted/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
info :   CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
log  : 对源“http://192.168.1.197:8082/repository/nuget-hosted/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0”重试“FindPackagesByIdAsyncCore”。
log  : 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
info :   GET http://192.168.1.197:8082/repository/nuget-hosted/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
log  : 对源“http://192.168.1.197:8082/repository/nuget-hosted/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0”重试“FindPackagesByIdAsyncCore”。
log  : 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
info :   GET http://192.168.1.197:8082/repository/nuget-hosted/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0
error: 未能从远程源“http://192.168.1.197:8082/repository/nuget-hosted/FindPackagesById()?id='Newtonsoft.Json'&semVerLevel=2.0.0”检索有关“Newtonsoft.Json”的信息。

**Comment by peterhuene** [comment]
This issue was moved to NuGet/Home#7983

**Comment by peterhuene** [comment]
Hi @Wscar.  As this is related to NuGet, I am moving the issue to their issue repository.  Thank you!
