### ISSUE TITLE
[loc][Query][dotnet_cli] Localizability of string: 0; "NoReferencesFound"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11110]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
There are no {0} references in project {1}. ;; {0} is the type of the item being requested (project, package, p2p) and {1} is the object operated on (a project file or a solution file). 

File Name:
dotnet\xlf\CommonLocalizableStrings.xlf

Resource ID:
 0; "NoReferencesFound"

Query:
Is this punctuation a symbol that will be replaced ". ;; "??
We leave it as source by now.

**Comment by peterhuene** [comment]
@PDostalek which branch is the localization team working from currently?

This string has been recently fixed in master (and release/3.0.1xx as of yesterday) to be `There are no {0} references in project {1}.`

The old form was some sort of typo in the string and was not desired.

**Comment by PDostalek** [comment]
Hi @peterhuene , string is coming from master. But there might be a slightly delay between git and our VSTS repo. Thanks for you information about.
