### ISSUE TITLE
[loc][Query][dotnet_cli] Localizability of string:  0; "UnexpectedTypeInJson"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11132]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Expected a {0} for property '{1}'.

File Name:
dotnet\ToolManifest\xlf\LocalizableStrings.xlf

Resource ID:
0; "UnexpectedTypeInJson"

Query:
Could you provide the meaning of the placeholders?

**Comment by wli3** [comment]
An example

`Expected a Number for property 'version'`.

This is an error message when validating local tool manifest file (a json). It will be displayed when there is a mismatch for json types. For example, it should be a Number `1`, but what in the user's json file is a string `"1"`.

**Comment by PDostalek** [comment]
THanks!
