### ISSUE TITLE
dotnet test --runtime linux-x64 copies wrong nuget dependencies into ouput folder

### ISSUE THREAD

**Issue by danielancich** [dotnet/cli#11148]
## Steps to reproduce
1. Have a nuget package with .dll in the lib/netcoreapp2.2 folder. And the respective .dll and .so in the runtimes/{os}/native folders. 
2. Run 'dotnet test --configuration Release --runtime linux-x64 --logger:trx $csprojFile'

## Expected  behavior
The output folder 'bin/Release/netcoreapp2.2/linux-x64/' should contain the .so files and run the tests.

## Actual behavior
The output folder 'bin/Release/netcoreapp2.2/linux-x64/' contains .dll files and cannot run the tests.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
Version:   2.2.105
Commit:    7cecb35b92
Runtime Environment:
  OS Name:     amzn
  OS Version:  2018.03
  OS Platform: Linux
  RID:         linux-x64
  Base Path:   /var/build/workspace/core-unit-tests/dotnet/cli/sdk/2.2.105/
Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6
.NET Core SDKs installed:
  2.2.105 [/var/build/workspace/core-unit-tests/dotnet/cli/sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/var/build/workspace/core-unit-tests/dotnet/cli/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/var/build/workspace/core-unit-tests/dotnet/cli/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [/var/build/workspace/core-unit-tests/dotnet/cli/shared/Microsoft.NETCore.App]

**Comment by peterhuene** [comment]
Hi @danielancich.  Would it be possible to share with us a repro project with the package?  Is the package published to NuGet?  If so, the package name might help us diagnose the problem.

What are sub-directories of the `runtimes` directory in your package, specifically?

**Comment by danielancich** [comment]
The package is published on an internal nuget server. Here is the package directory tree.

package:
  lib:
    netcoreapp2.2:
      .dll files
  runtimes:
    linux:
      native:
        .so files
    win:
      native:
        .dll files

**Comment by peterhuene** [comment]
Oh sorry, I completely missed that you're running `dotnet test` and not `dotnet publish`.

If you set the `CopyLocalLockFileAssemblies` property to `true` in your test project file, does that help?

By default, .NET Core 2.2 will not copy assets on build, only on publish.  With .NET Core 3.0, this now happens by default on build.

**Comment by danielancich** [comment]
That did help get the correct dependencies in the build folder. I also have to build the project first, then set the LD_LIBRARY_PATH to the output directory, and then run dotnet test with the no-build toggle.

Thanks for the help!
