### ISSUE TITLE
How to disable "System.GC.Server" ?

### ISSUE THREAD

**Issue by mattiasw2** [dotnet/cli#11151]
I want to disable the server GC, since it isn't aggressive enough and ends up using 100% of the 512 Mb the machine has. The application is a small kestrel apps, reads blobs up to size 300kb, and most likely the large object heap is the reason.

However,  `` "System.GC.Server": false, ``  is ignored, how to I change that value?

I created a file called runtimeconfig.template.json and put it on the root

```
{
  "configProperties": {
    "System.GC.Server": false,
    "foobar":  true 
  }
}
```

I added the foobar stuff to make sure the template is used.

However, the resulting <prject>.runtimeconfig.json in the published folder is

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.1"
    },
    "configProperties": {
      "System.GC.Server": true,
      "foobar": true
    }
  }
}
```

**Comment by kevingosse** [comment]
Check if there's the `<ServerGarbageCollection>true</ServerGarbageCollection>` property in your csproj. In which case, set it to false.

**Comment by alefranz** [comment]
Hi Mattias,
this is documented in https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#runtimeoptions

**Comment by mattiasw2** [comment]
Thanks! Added 

``` 
  <PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
</Project>
```

to the end of the .csproj file. No difference.

Maybe there is not way to get rid of the server GC?

**Comment by alefranz** [comment]
In which kind environment are you running on? is it a container? or arm?

**Comment by alefranz** [comment]
Also try to do a clean, I believe there was an issue that the settings didn't get properly propagated on incremental builds.

**Comment by mattiasw2** [comment]
Yes, clean + deleting contents of /bin/ folder fixed it.
