### ISSUE TITLE
[loc][Query][dotnet_cli] Localizability of string: 0; "RollForwardOnNoCandidateFxDefinition"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11168]
Hi,
please help localization team to answer question from translator.

In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.

Could you help please? Thanks!**

Source:
Roll forward on no candidate framework (0=off, 1=roll minor, 2=roll major & minor).

File Name:
dotnet\commands\dotnet-help\xlf\LocalizableStrings.xlf

Resource ID:
0; "RollForwardOnNoCandidateFxDefinition"

Query:
Please define the meaning of "no candidate framework".

**Comment by peterhuene** [comment]
Hi @PDostalek.

It means that if the application cannot find a .NET Core framework that matches the required version for the application, it would attempt to roll forward to a newer .NET Core framework based on this setting (off = no roll forward, 1 = roll forward to the next minor version found, 2 = roll forward to the next major and minor version found).

**Comment by PDostalek** [comment]
Perfect, thanks!
