### ISSUE TITLE
dotnet tool restore is missing a --tool-path option to support CI helix scenarios

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/cli#11167]
We recently switched to .NET Core SDK 3.0.0-preview3 in **corefx** and want to make use of the new repo tools feature. As we test with helix we need to be able to restore the tools upfront **from the tool’s manifest**, archive them and submit the archive as a helix payload.

The dotnet-tools.json contains all the necessary information but I’m missing a `--tool-path` option in `dotnet tool restore`. If we can’t restore from the manifest to a certain location then this solution can’t be used which would be unfortunate.

cc @ericstj @safern @wli3

**Comment by wli3** [comment]
local tools restore to nuget [global package folder](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders). You could override that by creating a nuget.config in the same folder(or use NUGET_PACKAGES environment variable) of the manifest file with the following content. Note, that folder share with normal nuget packages.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="globalPackagesFolder" value="C:\work\temp\localtools\sub\packages" />
  </config>
</configuration>
```

**Comment by wli3** [comment]
You should also set `DOTNET_CLI_HOME` environment variable during CI to avoid sharing state between different CI runs.

https://github.com/dotnet/sdk/commit/d313ae6c5b78d8451d5ea7c500c5b2b9914141e0

**Comment by ViktorHofer** [comment]
I see that you don't produce shims for restoring tools anymore. Instead of generat config files that tell the host which file to invoke:

```
[{"Version":"1.5.0","TargetFramework":"netcoreapp3.0","RuntimeIdentifier":"any","Name":"coverlet","Runner":"dotnet","PathToExecutable":"C:\\git\\corefx\\.packages\\coverlet.console\\1.5.0\\tools/netcoreapp2.2/any/coverlet.console.dll"}]
```

How should that work on CI as the path is hardcoded in here? We need a solution to invoke global tools on CI without restoring them there. On Helix we don't restore anything as that would take too long and instead just package everything up that is necessary for execution (i.e. test folder, test runtime, sdk, globaltools folder with the shims) and upload it.

I think a `--tool-path` option make sense here to restore the manifest AND generate the shims - same as when you do `dotnet tool install --tool-path`?

**Comment by wli3** [comment]
> How should that work on CI as the path is hardcoded in here?

This is a cache file. You should run restore after a new machine.

I agree `--tool-path` suit here better. However, `--tool-path` does not work with manifest file. You have total control of where the package assets goes. And you will also take the responsibility to put it on PATH. It is better with scripts. You can 

```dotnet tool install --tool-path ./tools mytool```
```dotnet tool install --tool-path ./tools mytool2```
and run it like
```./tools/mytool```

It will be safe from the bulk transfer from machine to machine.

I think Helix is not a direct scenario for local tools. Local tools help the user to obtain the package. However, in Helix, it is transferred in bulk already.

**Comment by ViktorHofer** [comment]
Is it too much of an ask to add a `--tool-path` option to `dotnet tool restore`? It would generate the shims as with `dotnet tool install`. Additionally when using `dotnet tool run` it would use the produced shims.

**Comment by KathleenDollard** [comment]
@ViktorHofer Your suggestion is interesting, but it mixes two approaches in a way that we aren't ready to do. 

- Local tools: Uses a manifest, restores to a NuGet cache, and requires `dotnet` command and does not use a shim. The major user story is a repo easily supplying tools to build or contributors and this approach is explicitly different than placing tools on the path. 
- Tool path tools: A variation of global tools that gives control of the tool location and finding the tool to the tool consumer. A shim is created and the tool can be called without `dotnet`.

Restore is only valid for local tools, where a tool path is not relevant. There really isn't crossover between these scenarios. We also had some security concerns with restore, although we are hoping signing will reduce that. 

For what you need, what would you gain in a manifest over a tool-path based script that created the directory contents you need?

**Comment by wli3** [comment]
close via Kathleen's comment
