### ISSUE TITLE
Add command line usage help for the new --roll-forward option

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/cli#11213]
The new roll forward feature introduces a new command line option `--roll-forward`. It's implemented by the host, but the command line help is sometimes shown from the code in CLI repo.

The feature is added in dotnet/core-setup#5891

**Comment by wli3** [comment]
you mean dotnet --help will give the help from CLI instead of the host? How could you get the help from host directly? I don't think we merge any text in dotnet --help

**Comment by vitek-karas** [comment]
Unfortunately there are two ways to get to a command line help in `dotnet.exe`.
One is `dotnet --help` which is handled by CLI.
The other one (less known) is `dotnet exec` (no arguments). This will print out command line help as well, something like this:
```
Usage: dotnet [host-options] [path-to-application]

path-to-application:
  The path to an application .dll file to execute.

host-options:
  --additionalprobingpath <path>         Path containing probing policy and assemblies to probe for.
  --depsfile <path>                      Path to <application>.deps.json file.
  --runtimeconfig <path>                 Path to <application>.runtimeconfig.json file.
  --fx-version <version>                 Version of the installed Shared Framework to use to run the application.
  --roll-forward-on-no-candidate-fx <n>  Roll forward on no candidate framework (0=off, 1=roll minor, 2=roll major & minor).
  --additional-deps <path>               Path to additional deps.json file.
  --list-runtimes                        Display the installed runtimes
  --list-sdks                            Display the installed SDKs

Common Options:
  -h|--help                           Displays this help.
  --info                              Display .NET Core information.
```

This other way is fully handled by `dotnet.exe` itself, it never calls into CLI. Since the `--roll-forward` is the muxer setting, it needs to show up in both.
