### ISSUE TITLE
Sentinel and cache files not removed when uninstalling .NET Core SDK

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#11214]
@scottaddie commented on [Fri Apr 19 2019](https://github.com/dotnet/core-setup/issues/5946)

## Steps to reproduce
1. Uninstall the .NET Core SDK via Win10's Control Panel:

![image](https://user-images.githubusercontent.com/10702007/56444142-2a540080-62bd-11e9-8cf6-d151044d78b8.png)

2. Navigate to the _%USERPROFILE%/.dotnet_ directory. Notice that _sentinel_ and _*.dotnetUserLevelCache_ files are left behind. The following screenshot shows the files are left behind after uninstalling .NET Core SDK 2.2.104:

![image](https://user-images.githubusercontent.com/10702007/56444039-b3b70300-62bc-11e9-937b-727badeaf062.png)

## Expected  behavior
The version-specific files depicted in the screenshot above should be deleted.

## Actual behavior
The version-specific files depicted in the screenshot above aren't deleted.

## Environment data
Win10 v1809

---

@dagood commented on [Fri Apr 19 2019](https://github.com/dotnet/core-setup/issues/5946#issuecomment-485028320)

The SDK installer is created in https://github.com/dotnet/core-sdk, but these files look to me like they're created during SDK usage (or first run) rather than placed directly by the installer. Moving to https://github.com/dotnet/cli with that in mind.

**Comment by peterhuene** [comment]
@johnbeisner @wli3 is this something we could do on an uninstall action (i.e. invoke the SDK to let it know to clean up any sentinel files)?

**Comment by wli3** [comment]
I lean toward to not do any action. `.dotnet` is all implementation detail. The user should not care about the content inside. 

It is ideal to clean it up. But they are empty files, it won't take too much space. Also It is hard to implement in current wix. (need to dup the same code in CLI to find user home directory to wix) and we also has mac, deb, rpm. I don't think it worth the effort.

**Comment by wli3** [comment]
close pre reason above

**Comment by scottaddie** [comment]
@wli3 I appreciate the response and would encourage the team to at least leave this issue open and move it to the backlog.

Customers, both internal and external, expect a clean uninstall of the product. If the CLI is responsible for creating the files, the CLI has a responsibility to remove them too. On my Windows machine, this has resulted in 152 empty files in my user profile.
