### ISSUE TITLE
DotNet New -n is not renaming custom template

### ISSUE THREAD

**Issue by jkears** [dotnet/cli#11230]
## Steps to reproduce
1. In a folder D:\\ProjectTemplates\SomeCo.DomainTemplate.CSharp copy in a working c# class library project and rename it to **DomainTemplate.csproj**
2. Add new subfolder in project root folder called .**template.config**
3. Create a new **template.json** file in the .template.config folder with the following content ...
{
    "$schema": "http://json.schemastore.org/template",
    "author": "Me",
    "classifications": [ "Domain", "Class Library"],
    "identity": "SomeCo.DomainTemplate.CSharp",
    "name": "SomeCo Domain Class Library",
    "shortName": "scdomain",
    "sourceName": "SomeCo.DomainTemplate",      
    "preferNameDirectory" : true
   
}

4. Install template as follows
**dotnet new -i D:\ProjectTemplates\SomeCo\DomainTemplate\CSharp**
verify custom template is installed

5. Create new project in a known empty folder
**dotnet new scdomain --name domaina -o domaina** 

## Expected  behavior
That a new subfolder is created called domaina containing my custom template was created and renamed to domaina.csproj

## Actual behavior
A new subfolder is created called domaina and although the csproj that my custom template was created based upon is there it has the name of the project that my template had, in my case  DomainTemplate.csproj

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by wli3** [comment]
This issue was moved to dotnet/templating#1869
