### ISSUE TITLE
macOS Startup System.ComponentModel.Win32Exception (13): Permission denied

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#11231]
@tn-5 commented on [Sat Apr 20 2019](https://github.com/dotnet/coreclr/issues/24146)

With the latest nightly build of netcore 3 (3.0.100-preview5-011505) it is not possible to run a net core application on macos, it give an exception on startup:
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

---

@danmosemsft commented on [Mon Apr 22 2019](https://github.com/dotnet/coreclr/issues/24146#issuecomment-485573014)

Based on the linked issue, this seems to depend on install location. I'm pretty sure this isn't runtime. May not be CLI either but moving there seems a better bet.

**Comment by wli3** [comment]
The apphost does not have enough permission (need a chmod u+x after copying). This is exposed by we switching to apphost pack. Before that, we relied on a nuget behavior.

**Comment by danmosemsft** [comment]
@danroth27

**Comment by wli3** [comment]
@danmosemsft thanks. We just find the cause

**Comment by dagood** [comment]
I submitted a PR to Core-Setup `master` here that sets `x` in the original pkg so tooling won't have to set permissions later: https://github.com/dotnet/core-setup/pull/6003. I'll create a `release/3.0` PR as well to get a head start on CI for the change there.

**Comment by wli3** [comment]
Only install's permission are missed while tar.gz has the correct permission. And CI always downloads tar.gz version, that's why CI did not catch it.

**Comment by peterhuene** [comment]
@wli3 is this now resolved?

**Comment by dagood** [comment]
https://github.com/dotnet/core-setup/pull/6004 was the fix, and it flowed through: installing the latest 3.0 SDK macOS pkg (`3.0.100-preview5-011562`) installs the file with the right permission and `console` and `mvc` templates are able to run. I think that covers it.

**Comment by alexzandros** [comment]
Same problem when trying to run the default F# console app
dotnet --version
3.0.101
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
Running inside a container created from the latest image present in MS images repository.

**Comment by mduu** [comment]
Same issue here with final 3.0.0.100 on macOS Catalina. I used the 3.0.0 macOs x64 installer. That permissions do I need to fix?

**Comment by dagood** [comment]
@mduu Can you please clarify what you installed? 3.0.100, 3.0.101? For example, https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.0.101-macos-x64-installer

I would recommend opening a new issue with more info, including your command, the console output, and an example repro project, in case it's a different issue that appears the same.

**Comment by krwq** [comment]
I'm getting identical failure on Ubuntu 18.10. This was just a `dotnet new console` and `dotnet run`

my `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.10
 OS Platform: Linux
 RID:         ubuntu.18.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  2.1.403 [/usr/share/dotnet/sdk]
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100-preview-010184 [/usr/share/dotnet/sdk]
  3.0.101 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by krwq** [comment]
Ok, was able to repro again, it seems there is some issue when directory with files is not a physical drive and I have moved files in between first and second time I run:

- mount onedrive with i.e. rclone - this likely will work with any fuse based file system
- create new directory with any name somewhere in the mounted dir
- `dotnet new console` + `dotnet run`
