### ISSUE TITLE
Common abstraction for specifying, extending, and parsing command arguments

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#1125]
The CLI needs a common abstraction for specifying command arguments.

These abstractions need to be able to:
- be shared by multiple commands (command A and command B share some core arguments)
- be extended by commands (command A takes the arguments of command B with some extra ones)
- parse and provide the actual value at runtime
- construct their own tool arguments

I've seen multiple implementations on various parts of this idea throughout the CLI.

I tried an initial idea of this with Compiler and Build. Build has the same arguments as Compiler plus some extra ones:
Compile's args: https://github.com/dotnet/cli/blob/master/src/dotnet-compile/CompilerCommandApp.cs
Build's args: https://github.com/dotnet/cli/blob/master/src/dotnet-build/BuilderCommandApp.cs

The values are available at runtime: https://github.com/dotnet/cli/blob/master/src/dotnet-compile/Program.cs#L67

Unfortunately, they do not construct their own arguments, leading to nasty client side code like this: https://github.com/dotnet/cli/blob/master/src/dotnet-build/CompileContext.cs#L295

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

Most of the 'common params' are those which drive project builds.
