### ISSUE TITLE
dotnet-restore does not work when published Standalone

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1126]
Discovered this yesterday. New NuGet builds may fix this issue already.

Filing this issue to track.

This is happening because beta Managed Libraries are getting mixed with rc3 native shims during restore/publish. Errors in the lock file are present.

**Comment by blackdwarf** [comment]
@brthor what is the status of this?

**Comment by brthor** [comment]
Now that dotnet-restore is published as part of the same assembly as the other commands, this is no longer relevant.
