### ISSUE TITLE
.NET Core 3.0 SDK on FreeBSD: The current .NET SDK does not support targeting .NET Standard 2.1. Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1.

### ISSUE THREAD

**Issue by joperator** [dotnet/cli#11262]
I've followed the steps described in [22124](https://github.com/dotnet/coreclr/issues/22124#issuecomment-460359445) to build a .NET Core project targeting .NET Standard 2.1 with the latest .NET Core 3.0 SDK for FreeBSD provided by the daily builds.

When using the `dotnet build` command on FreeBSD, I get the following error NETSDK1045:
The current .NET SDK does not support targeting .NET Standard 2.1. Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1.

When using the `dotnet build` command from the corresponding .NET Core 3.0 SDK on Windows or Linux, the build succeeded without errors.

Also targeting other frameworks like netcoreapp2.0, netcoreapp3.0 or netstandard2.0 works on FreeBSD using the latest .NET Core 3.0 SDK.
However, I need at least netstandard2.1, but no netcoreapp3.0 features, so that I can reference my .NET Core project in other libraries that target .NET Standard 2.1.

`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010021
 Commit:    d5c97b7c2a

Runtime Environment:
 OS Name:     FreeBSD
 OS Version:  12
 OS Platform: FreeBSD
 RID:         freebsd-x64

Host (useful for support):
  Version: 3.0.0-preview-27218-01
  Commit:  d40b87f29d

.NET Core SDKs installed:
  3.0.100-preview-010021

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.0.0-preview-27218-01
```

**Comment by dasMulli** [comment]
The first public preview to support .NET Standard 2.1 was `3.0.100-preview3-010431` with earlier previews (`3.0.100-preview-010184`) not containing it, so I guess your `3.0.100-preview-010021` also doesn't yet support it.

**Comment by joperator** [comment]
Thanks for the quick reply.
Is there a public preview available that supports .NET Standard 2.1 on FreeBSD?
From the [daily builds](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries) I only get `3.0.100-preview-010021` for FreeBSD x64.

**Comment by dasMulli** [comment]
Maybe @wfurt or @livarcocc know what happened to FreeBSD CI builds?..

**Comment by wfurt** [comment]
that is long story @dasMulli. FreeBSD was pushed out of 3.0. It boils down to priorities and infrastructure support. I was hoping to resurrect FreeSBD builds at some point  but I'm getting distracted with 3.0 issues.

**Comment by livarcocc** [comment]
I am going to close this for now. We track additional OSes separately and can file a new issue for FreeBSD later if necessary.
