### ISSUE TITLE
https://aka.ms/missing-command is broken

### ISSUE THREAD

**Issue by karann-msft** [dotnet/cli#11264]
```
C:\WINDOWS\System32>dotnet install -h
No executable found matching command "dotnet-install". See https://aka.ms/missing-command for more information.
```

**Comment by peterhuene** [comment]
@KathleenDollard @mairaw do we know where this link should be going?

**Comment by mairaw** [comment]
I don't. I wasn't involved with that but happy to help fix this! @KathleenDollard?

**Comment by KathleenDollard** [comment]
I have no idea.  Where do we want it to go?


Strawman: Can we make a section (or a page) near the list of valid commands that says "You get this message if the command you type isn't recognized."


What else would we say in the page we linked to?


________________________________

**Comment by mairaw** [comment]
This is our page that lists the valid commands:
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet

**Comment by wli3** [comment]
We removed the aka.ms link from the error message recently https://github.com/dotnet/cli/pull/10914
