### ISSUE TITLE
Dotnet SDK not Found on Windows Server 2016

### ISSUE THREAD

**Issue by mattbaumann** [dotnet/cli#11263]
# General

| Component | Name | Version |
| --------------|--------|---------- |
| Operating System | Windows Server 2016 Std |  10.0.14393 |
| Shell | Powershell |

Since the update of my windows server software up to Build 14393, I cannot access the .net Core SDK via the command line. 

I did the following, unsuccessful attempt to resolve the issue:

* Install newest Version of .Net Core SDK 2.2.106
* Check
* Remove all versions
* Install version of .Net Core SDK 2.2.203
* Install version of .Net Core SDK 2.2.106
* Restart of the server
* Check

Still getting the following error when executing a build on the command line:

```bash
 Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Response when I run ``dotnet --info`

```bash

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Obviously, It cannot compile without finding the actual SDK, but why does the installation with the _official Installer_ yield in an partially installed State? (files are copied correctly in c:/program files/dotnet/sdk/<version> though). 

Please let me know, whether you need additional information and I will answer promptly.

**Comment by livarcocc** [comment]
It seems you are running dotnet.exe from `c:\Program Files (x86)\dotnet`. Can you confirm that you are install x86 SDKs as well? Check what is the content of the `c:\Program Files (x86)\dotnet\sdk` folder.

If is possible that you are installing x64 SDKs but the path is still pointing to x86.

**Comment by mattbaumann** [comment]
Awesome, thank you, that's it.

So, as of my understanding, the Runtime installer installs the PATH variable and the SDK installs itself alongside of the runtime. The CLI is only able to invoke SDK's with the same processor architecture.
