### ISSUE TITLE
pre-jitting result of `dotnet publish`

### ISSUE THREAD

**Issue by mabead** [dotnet/cli#11275]
The [dotnet store](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-store) command has the ability to optimize the assemblies for the target platform:

> By default, assemblies are optimized for the target runtime and framework. For more information, see the runtime package store topic.

As said in https://github.com/dotnet/cli/issues/11270, it is not clear what is optimized. But if I read between the lines of [this post](https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/), it looks like the `dotnet store` command pre-jits the assemblies for the target environment. This is something quite usefull to speed-up the startup of applications.

Would it be possible to provide the same optimizations through an `--optimize` option to `dotnet publish`? This would make it easier than having to manage runtime package stores to optimize assemblies for the target platform. 

I would use it for sure to pre-jit assemblies of AWS lambdas thus minimizing the cold start time overhead.

**Comment by fadimounir** [comment]
@mabead Can you try the following publish command:
`` console
dotnet publish -r <RID> /p:PublishReadyToRun=true
``

Currently, this is enabled via a project property.

**Comment by livarcocc** [comment]
Closing as the question has been addressed.
