### ISSUE TITLE
What is optimized through `dotnet store`? Are assemblies pre-jitted?

### ISSUE THREAD

**Issue by mabead** [dotnet/cli#11270]
When we read the documentation of the [dotnet store](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-store) command, we can read that:

> By default, assemblies are optimized for the target runtime and framework. For more information, see the runtime package store topic.

Unfortunately, the "runtime package store topic" does not provide more details on the optimizations that take place.

My question is: what are the optimizations that take place? In particular, are the assemblies pre-jitted for the target environment?

**Comment by livarcocc** [comment]
They are crossgenned. That's the extent of the optimizations we do as part of dotnet store.
