### ISSUE TITLE
Unable to install any dotnet tool

### ISSUE THREAD

**Issue by HizzyCO** [dotnet/cli#11272]
## Steps to reproduce
Open Command line and run 
dotnet tool install --global Amazon.ECS.Tools --version 3.0.0

Using this tool as a specific value for a tool but happens with any tool.
## Expected  behavior
States tool installed

## Actual behavior
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error : Failed to retrieve information about 'amazon.ecs.tools' from remote source 'https://www.nuget.org/FindPackagesById()?id='amazon.ecs.tools'&semVerLevel=2.0.0'. [C:\Users\***\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.505\NuGet.targets(114,5): error :   Response status code does not indicate success: 404 (Not Found). [C:\Users\**\restore.csproj]

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.1.505
 Commit:    b220231234

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.505\

Host (useful for support):
  Version: 2.1.9
  Commit:  dcedc87d22

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by wli3** [comment]
What is the nuget feed are you targeting to? Is there a nuget.config in the directory? What is the content?

**Comment by HizzyCO** [comment]
I thought when doing a global install it would use the nuget config in %appdata% 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="Nuget" value="https://www.nuget.org/" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
</configuration>

**Comment by HizzyCO** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="Nuget" value="https://www.nuget.org/" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
</configuration>

**Comment by HizzyCO** [comment]
<packageSources>
    <add key="Nuget" value="https://www.nuget.org/" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>

**Comment by HizzyCO** [comment]
key="Nuget" value="https://www.nuget.org/"
key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"

**Comment by HizzyCO** [comment]
"<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="Nuget" value="https://www.nuget.org/" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
</configuration>"

**Comment by HizzyCO** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="Nuget" value="https://www.nuget.org/" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
</configuration>`

**Comment by wli3** [comment]
Your nuget.org feed url is wrong. It should be `<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />`
