### ISSUE TITLE
Run dotnet tool run t-rex -- -h, it doesn't show help from t-rex.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#11288]
## Steps to reproduce
1. Create empty directory
2. Copy the following and create file called dotnet-tools.json
 
{
    "version": 1,
    "isRoot": true,
    "tools": {
        "t-rex": {
            "version": "1.0.53",
            "commands": ["t-rex"]
        },
        "dotnetsay": {
            "version": "2.1.4",
            "commands": ["dotnetsay"]
        }
    }
}

3. cd to the directory with manifest file
4. Run  dotnet tool run t-rex -- -h
5. It should show error. Follow the instruction from the error
6. Run dotnet tool run t-rex -- -h again

## Expected  behavior
It should show help from t-rex

## Actual behavior
Run dotnet tool run t-rex -- -h, it doesn't show help from t-rex.
![image](https://user-images.githubusercontent.com/33921754/57220293-5f867f80-702d-11e9-8ae3-1f3e76372612.png)

## Environment data
D16.1/28902.138(16.1.0 preview3.0)+ CLI/SDK: 3.0.100-preview6-011765
`dotnet --info` output:
```
.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview6-011765
 Commit:    fffa58a7df

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-011765\

Host (useful for support):
  Version: 3.0.0-preview6-27705-13
  Commit:  ccea80903e

.NET Core SDKs installed:
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010067 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-011765 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6-19255-03 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27705-13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27705-13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by wli3** [comment]
I cannot repro on 3.0.0-preview6-27706-07

What is the instruction printed per step 5? For me it is `Run "dotnet tool restore" to make the "t-rex" command available.` And did you run `dotnet tool restore`?

**Comment by YunWeiaa** [comment]
@wli3 Thanks. After running `dotnet tool restore`, it can work well.
