### ISSUE TITLE
[loc][Query][Cli] Localizability of "LocalOptionDescription"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11306]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Update the tool and update from the local tool manifest.

File Name:
dotnet\commands\dotnet-tool\update\xlf\LocalizableStrings.xlf

==========================================
Query:
Does this simply mean "Update the tool from the local tool manifest."?

**Comment by livarcocc** [comment]
@wli3

**Comment by wli3** [comment]
It should be "Update the tools installed in the local tool manifest." I'll correct it in the code

**Comment by wli3** [comment]
@KathleenDollard It is confusing, especially after a while and read it again. We want to point out two things 1. the tool's dll etc will be updated 2. the entry in the manifest file will be updated. Uninstall's counterpart is more clear"Uninstall the tool and remove it from the local tool manifest." I guess we have only "update" to mean "update"?

@mairaw could you help us here?

**Comment by KathleenDollard** [comment]
Should this be:

Update the tool and update the local tool manifest.

or

Update the tool and the local tool manifest.

**Comment by mairaw** [comment]
I'd go with the latter: "Update the tool and the local tool manifest."

**Comment by PDostalek** [comment]
Thanks for your replies!
