### ISSUE TITLE
dotnet pack version

### ISSUE THREAD

**Issue by VidyaKukke** [dotnet/cli#11307]
I have a .csproj

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>$(RootNamespacePrefix)CLI</RootNamespace>
    <AssemblyName><myassemblyName></AssemblyName>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <RuntimeFrameworkVersion>$(RuntimeFxVer)</RuntimeFrameworkVersion>
    <Version>0.2.0</Version>
  </PropertyGroup>
...
</Project>
```

I'm trying to use dotnet pack Myproj.csproj. It is producing a random version. How do I specify the right version?

I have tried adding 
<VersionPrefix>0.2.0</VersionPrefix>
<VersionSuffix>$(VersionSuffix></VersionSuffix>

and doing a 
dotnet pack myproj.csproj --version-suffix "-somethinghere"

Nothing seems to work. What am I missing here?

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.505
 Commit:    b220231234

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.505\

Host (useful for support):
  Version: 2.1.9
  Commit:  dcedc87d22

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
We usually set a versionprefix in the csproj or somewhere as a msbuild property, like `<VersionPrefix>1.1.0</VersionPrefix>`.

That means that you package will always start 1.1.0 until you make a code change for it. And then you can pass the `--version-suffix` parameter to the pack command to append something to the prefix you set.

For instance, running `dotnet pack --version-sufffix preview1-0098` would give you version 1.1.0-preview1-0098.

Let me know if this does not work for you and we can continue the conversation.

**Comment by VidyaKukke** [comment]
Tried it does not work. 
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>$(RootNamespacePrefix)CLI</RootNamespace>
    <AssemblyName>myasmname</AssemblyName>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <RuntimeFrameworkVersion>$(RuntimeFxVer)</RuntimeFrameworkVersion>
    <VersionPrefix>0.2.0</VersionPrefix>
  </PropertyGroup>

and did a 
dotnet pack sdk\SDK.csproj --version-suffix preview1-1

my output is asm.0.5.12-beta.4a0d2a6094.nupkg

**Comment by livarcocc** [comment]
Do you have any sort of customization in your project? Could you share a binlog with us. Do read on what is logged on a binlog and make sure it is safe for you to do so: https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b

I tried my suggestion above on a vanilla library and it behaved as expected. This indicates to me that you have your own build logic that may be impacting this. Also, any particular reason why you are setting RuntimeFrameworkVersion? It should not be necessary. Also, unless you are multi-targeting, as in, you are building a library for netstandard and net46, for example, you should just set `<TargetFramework>netstandard2.0</TargetFramework>`.

**Comment by livarcocc** [comment]
We chatted offline. Nerdbank.GitVersioning was being used and was setting the version. Going to close this issue now.
