### ISSUE TITLE
`content` copied on build

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1131]
`dotnet build` copies items specified in the `content` section. These file should only be copied on publish but not on build.

**Comment by andschwa** [comment]
These files aren't copied on `publish` at all (not on Ubuntu 14.04 at least).

**Comment by blackdwarf** [comment]
@andschwa just tried it, copies it for me. Is this fixed? Here is my PJ:

```console
{
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "content": ["quotes.txt"],

  "dependencies": {
      "NETStandard.Library": "1.0.0-rc2-23704"
  },
  "frameworks": {
    "dnxcore50": {}
  }
}
```

**Comment by andschwa** [comment]
I tried this morning, instead it deleted the file! I'll update and try
again.

**Comment by andschwa** [comment]
I think I might know why it's not working: I'm trying to copy files that are `../path/to/imported/source/tree/content.blah`, and I want `content.blah` copied to the publish output. I don't think the current implementation of `contentFiles` allows for this, per this [line](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Files/ContentFiles.cs#L42), but I'll admit, in on my phone and so didn't follow through that function call.

**Comment by andschwa** [comment]
Yup, that's what repros it. When the file is a relative link outside of the directory containing `project.json`, it fails with `The process cannot access the file '/home/andrew/src/README.md' because it is being used by another process.` as in dotnet/cli#753.

```json
"content": [ "../README.md" ],
```

**Comment by andschwa** [comment]
Okay, I can work with this for now! At least gets a dozen `cp` commands out of our Windows and Linux build scripts.

Ideally we could specify content files that live outside of the directory that contains the `project.json`, and add the `content` key to the library that actually depends on them, not the executable host above it.

**Comment by andschwa** [comment]
Actually, if we could handle relative links outside the directory sooner rather than later, that would be ideal, as I also have folders that I'd like to handle with this.

**Comment by andschwa** [comment]
Sorry for having usurped the issue!

We are using `content` now, with a script to update the files from the real source tree (as they only need to be updated when merges are brought in from the other SCM). Our build scripts are way simpler now.

I'll make a new issue for handling locations of content files better.

**Comment by livarcocc** [comment]
We support relative paths under content right now. We are actually using it heavily for our tests. Look at https://github.com/dotnet/cli/blob/rel/1.0.0/test/dotnet-build.Tests/project.json, for instance. Maybe I misunderstood your ask.

**Comment by andschwa** [comment]
Hm... That sure looks like what I'm trying to do. I'm on Ubuntu 14.04 using dotnet-publish, but get the above cannot access error.

**Comment by livarcocc** [comment]
Hum, we haven't had a successful CI from Ubuntu in a while for various reasons, maybe this is indeed broken in ubuntu. Though, it works fine in OSX.

**Comment by andschwa** [comment]
Ah! Then we need a bug report, as it reproed pretty simply on today's nightly. I can file when I'm off my phone, with steps and versions.

Is there an issue tracking Ubuntu CI? I would be willing to help get that back up and running as it's vital to our project. We have CI up on Travis testing our project that uses CLI extensively :smile:

**Comment by livarcocc** [comment]
File an issue for the relative path in Ubuntu. We already have an issue for the Ubuntu CI, though I don't have it handy right now.

**Comment by livarcocc** [comment]
I am closing this one since we have an issue tracking the Ubuntu problem already.
