### ISSUE TITLE
Add `dotnet -v` in addition to `dotnet --version`

### ISSUE THREAD

**Issue by brettrowberry** [dotnet/cli#11316]
## Steps to reproduce
`dotnet -v`

## Expected  behavior
`3.0.100-preview5-011568`

## Actual behavior
`Unknown option: -v`

**Comment by livarcocc** [comment]
`dotnet -v` is used in other commands for verbosity level setting. We don't want to confuse these options.

As such, we have no plans to add that short hand for version. Please continue using `--version`.
