### ISSUE TITLE
dotnet pack version not working

### ISSUE THREAD

**Issue by VidyaKukke** [dotnet/cli#11310]
I have updated this thread - https://github.com/dotnet/cli/issues/11307 

I'm confused with the Issue workflow. I looked 3 hrs later. A solution is proposed (which does not work) but the original thread is closed. Not sure why. Typically you wait for an ACK or at least for a day before closing.  Can we keep this thread opened for 24hrs at least or until you get a confirmation (whichever happens first) of whether the proposed solution actually worked and unblocked customer!

**Comment by livarcocc** [comment]
I have re-activated the original issue and will close this one.
