### ISSUE TITLE
dotnet compile does not work with net451 with --output and --temp-output

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#1132]
1. Get the latest dotnetcli from http://dotnet.github.io/getting-started/
    -- I got version 1.0.1.001141

2. Open command prompt, cd C:\Projects\Project1
3. dotnet new
4. Change project.json to use net451 instead of dnxcore50
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
    },

    "frameworks": {
        "net451": { }
    }
}

5. dotnet compile with --output and --temp-output -- This is what we do when building from Visual Studio

ACTUAL
![image](https://cloud.githubusercontent.com/assets/8246794/12692056/2e232a70-c6a7-11e5-95cb-174e02570b91.png)

**Comment by livarcocc** [comment]
@balachir Did you run restore after updating the project.json? Also, you shouldn't use compile directly, you want to use dotnet build instead, as it resolves and builds any other dependences (project to project) that you might have.

**Comment by BillHiebert** [comment]
@livarcocc But from a VS perspective we need to call compile since VS coordinates the builds of the projects in the solution. In either case, It seems the error above is a bug.

**Comment by livarcocc** [comment]
@BillHiebert Did you run a restore after changing the project.json?

**Comment by BillHiebert** [comment]
@livarcocc It still repro's after a restore

**Comment by BillHiebert** [comment]
I can't repro this anymore

**Comment by piotrpMSFT** [comment]
@balachir since @BillHiebert said this no longer repros, I'm closing the issue. If it's still blocking you please reopen.
