### ISSUE TITLE
"dotnet build" for mvc failed with error  MSB4064

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#11372]
## Steps to reproduce
1. Install .NET core SDK 3.0.100-preview6-011991
2. Run "dotnet new mvc -o mymvc"
3. Run "dotnet build" to observe the result

## Expected  behavior
1. Dotnet build works fine.

## Actual behavior
1. dotnet build failed with error MSB4064

/usr/share/dotnet/sdk/3.0.100-preview6-011991/Sdks/Microsoft.NET.Sdk.Razor/build                                  /netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets(156,10): error MSB40                                  64: The "NullableContextOptions" parameter is not supported by the "Csc" task. V                                  erify the parameter exists on the task, and it is a settable public instance pro                                  perty. [/home/nicole/mymvc/mymvc.csproj]
/usr/share/dotnet/sdk/3.0.100-preview6-011991/Sdks/Microsoft.NET.Sdk.Razor/build                                  /netstandard2.0/Microsoft.NET.Sdk.Razor.Compilation.targets(120,5): error MSB406                                  3: The "Csc" task could not be initialized with its input parameters.  [/home/ni                                  cole/mymvc/mymvc.csproj]
![image](https://user-images.githubusercontent.com/1578239/57913940-3b922c00-78c0-11e9-8bb0-3583cc136408.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-011991
 Commit:    c4f1cf02c2

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview6-011991/

Host (useful for support):
  Version: 3.0.0-preview6-27716-10
  Commit:  6defcc2f37

.NET Core SDKs installed:
  3.0.100-preview6-011991 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6-19265-03 [/usr/share/dotnet/shared/Mic                                  rosoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27716-10 [/usr/share/dotnet/shared/Micros                                  oft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by dasMulli** [comment]
Looks like an instance of https://github.com/aspnet/AspNetCore/issues/10218

**Comment by livarcocc** [comment]
Yep. Dup of the issue @dasMulli linked above. It should be fixed very soon.
