### ISSUE TITLE
.NET CLI vs. Visual Studio

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1139]
Today I just noticed that DNX has been retired, and all users of it should migrate to .NET CLI. This presents a bit of a problem for me. Due to past problems with .NET CLI, I am currently using DNX to build my app. (Due to being a GUI app with a custom C++-based entry point, my build procedure is quite complex.)

However, my main concern is Visual Studio's integration with DNX. As far as I know, Visual Studio knows nothing about .NET CLI, and using .NET CLI alongside Visual Studio will result in considerable project churn due to them continuously overwriting each other's `project.lock.json` files. Is there/will there be Visual Studio integration for .NET CLI? There have been issues filed (such as #967) concerning Visual Studio integration when .NET CLI is involved. Is there a timeline for this to be fully resolved, or should I continue using DNX in the short-term while these issues are figured out?

**Comment by wjk** [comment]
Apparently, through informal testing, running `dotnet restore` on an otherwise DNX-managed project produces _no churn whatsoever_ (`git status` reports no changes to `project.lock.json` or any other file). However, it seems I must keep DNX around if only because Visual Studio takes a dependency on it. No harm done there.

**Comment by Petermarcu** [comment]
Were in the middle of the transition but the high level answer is yes. You will see vs tooling on top of the. net CLI similar to your current DNX experience. Were still figuring out timeframes for when we be able to complete all the work. For now, the only vs experience we have is the RC1 of ASP.net.

**Comment by davidfowl** [comment]
@wjk We're updating DNX just enough to continue working with the CLI changes until we have a public VS release.

**Comment by zhouyongtao** [comment]
这个问题估计得等好久了，首先现在官方的文档基于VS2015都还是DNX的，CLI的迁移工作估计还是等3月份后才会有新的进展，也就是中国年后 ，哈哈。

**Comment by zhouyongtao** [comment]
https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/

**Comment by enricosada** [comment]
@davidfowl there is repo of the new vs integration i can clone, build an try?

I'd like to try vs and dotnet cli (not dnx), it's not a problem if it's an alpha atm

**Comment by davidfowl** [comment]
Nope. Nothing is ready yet

**Comment by enricosada** [comment]
thx @davidfowl i'll wait :smile:

**Comment by jamesqo** [comment]
Will this integration be released in time for VS 2015 Update 2?

**Comment by GuardRex** [comment]
@jamesqo Reading the tea leaves, it looks like something will be delivered at Build time (around 3/30), but everything official is TBD (To Be Determined) right now. https://github.com/aspnet/Home/wiki/Roadmap

**Comment by blackdwarf** [comment]
Seems like the answer for the original question the issue poses has been answered. I will close this issue. If you believe this has been in error, please reopen.

**Comment by ciel** [comment]
I've been able to get Visual Studio to recognize the packages downloaded and give me intellisense back, and *sometimes* the NuGet *Restore Packages* command works - but in general I still have to do things from the command line - especially building and running.

**Comment by BeelzeBu** [comment]
@ciel How did you do that??

**Comment by dazinator** [comment]
Any news on when we may be able to expect an update for VS 2015 that delivers dotnet cli and gets rid of dnu? I am having nothing but problems with `dnu` at present.. eager to get rid of it.

**Comment by GuardRex** [comment]
@dazinator The comments in the Standup on the 21st put their guesstimate at that time between 3-6 weeks; therefore, we'd have 2-5 weeks left to go.

**Comment by dazinator** [comment]
@GuardRex - ok lovely - cheers :)

**Comment by dazinator** [comment]
@GuardRex - In terms of the VS move to dotnetcli - any ideas how this is going to be released - i.e will we see an update for VS 2015? Or will this be some preview version of the next version of VS that we will have to download and install seperately? I'm just trying to get a handle on what the upgrade path may be for the team :)

**Comment by Petermarcu** [comment]
@dazinator , The Preview tools that just released on Monday on top of VS 2015 are built on top of the CLI. Over time, you will see more and more integration. There is a link to the installer here. https://www.microsoft.com/net/core#windows

**Comment by GuardRex** [comment]
@dazinator Reports at Slack are very good about the VS experience with RC2. I'm **still** using VS Code, and I don't have a firm switch-back-to-VS date for myself yet.

Here's the sign-on to Slack: http://tattoocoder.com/aspnet-slack-sign-up/ ... pretty much everyone is over there. A few us still bop around at JabbR (the cool people anyway :sunglasses: lol). I have an #iis channel at Slack with helpful IIS-related notes.

**Comment by dazinator** [comment]
@Petermarcu - ahh wow I had totally missed this. Installing now ;)
@GuardRex - brilliant i'll sign up! - cheers ;)
