### ISSUE TITLE
Installation components are over translated on sdk installation wizard with Chinese

### ISSUE THREAD

**Issue by AriNuer** [dotnet/cli#11398]
## Steps to reproduce
1. Open SDK 3.0.100-preview6-012031 on Win10-x64 CHN
2. Observe the installation completion page of the installation wizard 

## Expected  behavior
The installation components should show in English rather than Chinese

## Actual behavior
Over translation occurs on installation components
![image](https://user-images.githubusercontent.com/42136111/58154354-0745b380-7ca4-11e9-80a3-2a074812c838.png)

Note:
Related components show in English during installation, take .net core runtime for example
![image](https://user-images.githubusercontent.com/42136111/58154466-4116ba00-7ca4-11e9-9ae6-3988eccd72d3.png)

## Environment data
`dotnet --info` output:

.NET Core SDK（反映任何 global.json）:
 Version:   3.0.100-preview6-012031
 Commit:    f84d1b7f66

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.0.100-preview6-012031\

Host (useful for support):
  Version: 3.0.0-preview6-27720-09
  Commit:  c3145b06ba

.NET Core SDKs installed:
  3.0.100-preview6-012031 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview6-19271-01 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27720-09 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27720-09 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by janbaltus** [comment]
overtranslation issue fixed. File need to be checked-in
