### ISSUE TITLE
Button "install" is truncated on the SDK installation wizard with Japanese

### ISSUE THREAD

**Issue by Jepson109** [dotnet/cli#11397]
## Steps to reproduce
1.Open the sdk installation file (.NET core sdk 3.0.100-preview6-012031).
2.Observe the button "インストール" .

## Expected  behavior
Button content isn't truncated

## Actual behavior
Button content is truncated
![image](https://user-images.githubusercontent.com/38854445/58152836-23dfec80-7ca0-11e9-8d90-c524ea6022cc.png)
![image](https://user-images.githubusercontent.com/38854445/58152967-73261d00-7ca0-11e9-9b51-58181604cb22.png)

## Environment data
VS Version: 16.2.0 Preview 2.0 [28921.339.d16.2stg]
`dotnet --info` output:
.NET Core SDK (global.json を反映):
 Version:   3.0.100-preview6-012031
 Commit:    f84d1b7f66

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012031\

Host (useful for support):
  Version: 3.0.0-preview6-27720-09
  Commit:  c3145b06ba

.NET Core SDKs installed:
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010195 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012031 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6-19271-01 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27720-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27720-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by johnbeisner** [comment]
![image](https://user-images.githubusercontent.com/24683167/58359245-57a14a80-7e37-11e9-8bb8-ad90a9fd6831.png)
