### ISSUE TITLE
DotNetCoreInstaller@1` task failed with non-zero exit code when switch to 1

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#11406]
From @AArnott 

Actually, [my PR to switch to use `UseDotNet@2`](https://github.com/microsoft/vs-streamjsonrpc/pull/283) can't complete because 3 PR builds in a row have failed in the `dotnet test` step. [All tests pass, but `dotnet.exe` returns a nonzero exit code](https://dev.azure.com/azure-public/vside/_build/results?buildId=6240&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&taskId=ea74d3ec-af51-57bf-65e6-f50dd234a1e5&lineStart=1163&lineEnd=1177&colStart=1&colEnd=1).

```

Total tests: 246. Passed: 246. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 10.1186 Seconds
     1>Done Building Project "d:\a\1\s\src\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:22.63
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
##[warning]Invalid results file. Make sure the result format of the file 'd:\a\_temp\VssAdministrator_fv-az48_2019-05-22_04_51_17.trx' matches 'VSTest' test results format.
##[error]Dotnet command failed with non-zero exit code on the following projects : d:\a\1\s\src\StreamJsonRpc.Tests\StreamJsonRpc.Tests.csproj
```

As you can see it also emits a warning about the .trx file. None of this happens when I use the `DotNetCoreInstaller@0` task. I wonder why in the world switching installer tasks would cause this problem.

**Comment by wli3** [comment]
Is it hard to read but there is an error in the log

```
Starting test execution, please wait...
Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\hostedtoolcache\windows\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.2.2 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]

Results File: d:\a\_temp\VssAdministrator_fv-az48_2019-05-22_04_51_17.trx
```

**Comment by wli3** [comment]
@AArnott I think since mutilevel look up is disabled, we can no longer find the runtime version in preinstalled location. You will also need to install 1.x runtime

**Comment by AArnott** [comment]
I see. Ya, with my workaround the multi-level lookup was only disabled for the `dotnet tool` command. Now with this new task it's an env var that applies everywhere.

I hope I can run that task several times and have the results be cumulative. I'll give it a try.

**Comment by wli3** [comment]
It used to install different SDK versions in different location, so it cannot accumulate . And there was an bug for that. Looks like the install location is "C:\hostedtoolcache\windows\dotnet\" without extra subfolder. It should be fixed

**Comment by AArnott** [comment]
Awesome. Yes, I remember the task on OSX couldn't accumulate, which really limited what I could do. I see in my Windows box at least that accumulation works. So I can complete my PR and we can close this issue.
Thanks for your help.
