### ISSUE TITLE
[loc][Query][Cli] Localizability of "ValueMustBeAnObject" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11401]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The property '{0}' must be an object if it is specified.

File Name:
dotnet\commands\dotnet-run\xlf\LocalizableStrings.xlf

==========================================
Query:
Please clarify if "it" stands for the property or the object.

**Comment by livarcocc** [comment]
@peterhuene can you help disambiguate?

**Comment by peterhuene** [comment]
@PDostalek I can't find that string anywhere.  What branch is it and what is the property key?

**Comment by peterhuene** [comment]
Never mind, I found it.  Too much servicing work, not enough time in master, apparently (needed a pull).

**Comment by peterhuene** [comment]
@PDostalek It apparently refers to the property.

**Comment by peterhuene** [comment]
@PDostalek Please let me know if that didn't answer the question. Thanks!
