### ISSUE TITLE
 [loc][Query][Cli] Localizability of "CouldNotConvertToString" 

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#11402]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Could not convert the value of property '{0}' to a string.

File Name:
dotnet\commands\dotnet-run\xlf\LocalizableStrings.xlf

==========================================
Query:
Please, define what will placeholder be replaced by.

**Comment by livarcocc** [comment]
@peterhuene

**Comment by peterhuene** [comment]
It looks like the placeholder might be replaced with any of the expected string property names, which appear to be:

* `CommandLineArgs`
* `LaunchUrl`
* `ApplicationUrl`

**Comment by peterhuene** [comment]
@PDostalek Please let me know if that didn't answer the question.  Thanks!
