### ISSUE TITLE
Quick guidance request on pair of .pdb and .dll files in published output

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1142]
Just checking the most recent design and see that the publish output for a test app of mine appears to be ...
```
bin
   --- Debug
      --- dnxcore50
         --- myapp.dll
         --- myapp.pdb
         --- win7-x64
            --- refs
            --- Views
            --- wwwroot
            --- the DLL's
            --- myapp.dll
            --- myapp.exe
            --- myapp.pdb
```
Why (and what's relevant about) the presence of two `myapp.dll` and `myapp.pdb` files?

As I test with such an app's published output, I need to know is it cool to only move the contents of the `win7-x64` folder to the IIS hosting server? Are the outer `.dll` and `.pdb` files relevant?

**Comment by davidfowl** [comment]
> Why (and what's relevant about) the presence of two myapp.dll and myapp.pdb files?

Project to project compile time assets are found in `bin\{configuration}\{tfm}\*`, while platform specific assets are put in `bin\{configuration}\{tfm}\{rid}\*`.

> As I test with such an app's published output, I need to know is it cool to only move the contents of the win7-x64 folder to the IIS hosting server? Are the outer .dll and .pdb files relevant?

That's correct. Runnable assets will always be platform specific. We're still working on this and if it ends up being too confusing we might see if we can do something else but it's the cleanest thing to do right now. It allows project to project dependencies to resolve compile time assets in a consistent way.

**Comment by GuardRex** [comment]
Thanks.
