### ISSUE TITLE
Relevant or irrelevant exception?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1143]
Is this relevant or irrelevant given the present work? I'll provide a repro if you want more. Otherwise, I'll close and shove it in my :ear: if it's a "Luke, WAIT! please." issue.

![capture](https://cloud.githubusercontent.com/assets/1622880/12693827/b7dffbec-c6cc-11e5-9166-cd8adf785ea4.PNG)

**Comment by davidfowl** [comment]
@pakrym Fixed this today

**Comment by GuardRex** [comment]
I'll shove it in my :ear: now. thx.

**Comment by GuardRex** [comment]
@pakrym Can I ping back on the "fix" for this. I was clued in by @davidfowl to add ...
```
"Microsoft.Extensions.DependencyModel": "1.0.0-dev-001186"
```
... and everything was good for a day or two. I get this warning now ...
```
project.json(33,49): warning NU1012: Dependency conflict. 
Microsoft.AspNetCore.Mvc.Core 1.0.0-rc2-17011 expected 
Microsoft.Extension.DependencyModel >= 1.0.0-dev-1452673922 but got 1.0.0-dev-001186
```
Attempts to use `-rc2-*` or `-rc2-1452673922` have failed.

The app seems to run fine with `-001186`.

Question is: Is this a "hold on, we're working on it" thing, or is this a bonafide issue that I can/should do something about on my end?

**Comment by GuardRex** [comment]
Ah! Nevermind. The warning just went away with `-dev-*`. I think I'm good. Sorry for the bother.

**Comment by GuardRex** [comment]
I'm BACK. It choked with `-dev-*` when I ran it. The warning went away, the original exception came back ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12835140/57bcaf72-cb62-11e5-9fb1-9e20cb63d41a.PNG)

**Comment by moozzyk** [comment]
Did you install the latest cli? There was a bug where dotnet publish did not copy `refs` folder which is required to compile views. Not having refs resulted in exactly the same exception you posted.

**Comment by GuardRex** [comment]
@moozzyk Yes, I have refs in published output ...

![capture](https://cloud.githubusercontent.com/assets/1622880/12855522/d055c058-cbf4-11e5-9fcd-1a8dd9957797.PNG)

I'm using the latest MSI-based CLI ... ver `1.0.1.001200-dev`.
