### ISSUE TITLE
Improve dotnet pack command to create templates

### ISSUE THREAD

**Issue by Thraka** [dotnet/cli#11457]
The current CLI requires users to install and use `nuget pack`  to create a template for the dotnet SDK. This incurs a penalty on non-Windows computers where the user will have to install Mono and get nuget.exe running just to create templates.

The existing `dotnet pack` command should support targeting a nuspec (or something.props?) and look for the settings that `nuget pack` does and output a template.

Docs bug: dotnet/docs#11066

**Comment by Thraka** [comment]
@KathleenDollard Per your request, I've filed this issue.

**Comment by livarcocc** [comment]
I believe this issue should go into nuget/home.

**Comment by Thraka** [comment]
It seems this may be related to NuGet/Home#8018

**Comment by Thraka** [comment]
I'm closing this as I got it to run successfully. I'll be updating the documentation around this scenario.
