### ISSUE TITLE
Advice for "Could not load file or assembly ..."

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1146]
For an exception following `dotnet publish` with 0 Warnings and 0 Errors ...
```
Could not load file or assembly 'System.Runtime.Extensions, Version=4.1.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest 
definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
![capture](https://cloud.githubusercontent.com/assets/1622880/12694037/0330a0fe-c6d4-11e5-9e36-5c57898cf882.PNG)
... and `project.lock.json` shows ...

System.Runtime.Extensions Reference | Count of Requests
-------------------------------- | -----------------
System.Runtime.Extensions 4.0.0 | 27
System.Runtime.Extensions 4.0.10 | 71
System.Runtime.Extensions 4.0.10-beta-23109 | 3
System.Runtime.Extensions 4.0.11-beta-23225 | 3
System.Runtime.Extensions 4.1.0-rc2-23728 | 21
System.Runtime.Extensions 4.1.0-rc3-23729 | 3
runtime.win7.System.Runtime.Extensions 4.1.0-rc3-23729 | 2

What's a boy :boy: to do?

`project.lock.json` has been described as the "dev's friend" in package version issue problems, but I'm not sure how to troubleshoot. Is there general advice for a situation like this? ["Please WAIT! We're still breaking stuff." is a good answer, too, btw.]

**Comment by davidfowl** [comment]
There's tons problems with the existing BCL packages and @ericstj is working on fixing that. In the mean time, it's likely that you need to update your Standard.Library reference.

**Comment by ericstj** [comment]
@davidfowl I'd say that the current package dependencies stress NuGet a bit more than we need to.  We're changing them.  That will reduce the number of different versions in the graph.  The way to decode all those references is many different packages you're bringing in referenced different versions of S.R.E, but the NuGet should have chosen latest implementation rc3-23729.

@GuardRex the way to trouble shoot this is to look for the targets section for DNXCore,Version=v5.0/win7-x64 and find the package (or packages) contributing a `runtime:` asset for System.Runtime.Extensions.dll.  Also when looking at `project.lock.json` the dependencies sections are usually not the first thing to look at.  Examine the `DNXCore,Version=v5.0` section to find the packages that NuGet chose for compile, you'll see a single entry for the final package providing System.Runtime.Extensions.dll to the compiler.  Then examine `DNXCore,Version=v5.0/win7-x64` and you should find a single package contributing System.Runtime.Extensions.dll at runtime.

Now based on the data you shared, I'm guessing that package is runtime.win7.System.Runtime.Extensions 4.1.0-rc3-23729.  I double checked and that package does have S.R.E version 4.1.0.0 inside it.

What you might be hitting is an older version of the CLI that is still picking up System.Runtime.Extensions.dll implementation from the CLI itself (like DNX did with its 'bin' folder) in that case you'd see this error.  What CLI version are you using?  /cc @piotrpMSFT

**Comment by davidfowl** [comment]
> @davidfowl I'd say that the current package dependencies stress NuGet a bit more than we need to. We're changing them. That will reduce the number of different versions in the graph. The way to decode all those references is many different packages you're bringing in referenced different versions of S.R.E, but the NuGet should have chosen latest implementation rc3-23729.

Very diplomatic :wink: 

I didn't notice the exception was happening during publish itself. Are you using the latest CLI bits? I'm not sure if you're using the right branch since we split rel/1.0.0 and master, fixes just landed in both but I don't know if the places that have download links are giving you the right thing.

**Comment by GuardRex** [comment]
`"NETStandard.Library": "1.0.0-*"` resolved to `1.0.0-rc3-23729`.

@ericstj I checked the section you mention, and yes, it's showing ...
```json
"System.Runtime.Extensions/4.1.0-rc3-23729": {
"type": "package",
"dependencies": {
    "System.Runtime": "4.0.20",
    "runtime.win7.System.Runtime.Extensions": "4.1.0-rc3-23729"
},
"compile": {
    "ref/dotnet5.4/System.Runtime.Extensions.dll": {}
}
},
```
I've posted the `project.lock.json` file here:https://gist.github.com/GuardRex/f074d0c7f2351af62e8e

Let me know if I should put the full proj up.

I use the MSI to obtain the CLI. The CLI was pulled down last night. It was `1.0.1.001186 dev` and is still current this morning.

I have the following feed sources (derived from @davidfowl example `HelloMvc` for `dotnet cli`) ...
```xml
<add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
<add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
<add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
<add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
<add key="AspNetvNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
```
Although this isn't really blocking me in any cosmic sense, if there turns out to be a quick-fix, I'd like to keep testing with `dotnet cli`.

**Comment by GuardRex** [comment]
@ericstj @davidfowl @moozzyk 

I just discovered something interesting about this exception. The exception we're discussing here is ...
```
Could not load file or assembly 'System.Runtime.Extensions, Version=4.1.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest 
definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
![capture](https://cloud.githubusercontent.com/assets/1622880/12834810/5c41de12-cb5f-11e5-9e70-13415fb08927.PNG)

... on a `dotnet publish`. I was using ...
```json
"scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath%"
},
"tools": {
    "dotnet-publish-iis": "1.0.0-*"
},
```
... in `project.json` blindly following `cli-samples`; however, I've come to realize that for my dev process, I don't need to run this script. [My `web.config` is in my project and will not require creating or mods or checks by the CLI tooling (at least for now).] I removed the `postpublish` script execution and the `tools` section from `project.json`, and behold the result ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/12834834/a6b45a2e-cb5f-11e5-9175-006d7b1b30e1.PNG)


Message gone! Vanished. Aliens?? :alien: ... possibly. What do you think?

**Comment by ericstj** [comment]
Not aliens, it sounds to me like it was a downgrade in the dotnet-publish-iis tool.  If it were to specify a lower version of S.R.E than one of its dependencies this would happen.  I didn't see this problem with the latest dotnet-publish-iis.  If you're still reproing it maybe share the version of the tool and it's lock file.

**Comment by GuardRex** [comment]
Is the latest tool ver the same as `dotnet cli` ver itself? ... It would be the last one available by MSI ... `1.0.1.001200-dev`. As for it's lock file, I don't see that in my `dotnet` folder where `dotnet cli` was installed. Where is it?

**Comment by ericstj** [comment]
So that tool entry is like a package dependency. You should see a dotnet-publish-iis package in your packages cache.  I believe the lock file gets placed in the tool's package directory but @piotrpmsft would know for sure.

**Comment by GuardRex** [comment]
I see `.nupkeg` files, `.nuspec` ... then in `lib\dnxcore50` ... `.deps`, `.dll`, and `.xml`.

**Comment by ericstj** [comment]
The .deps has the package list.

**Comment by moozzyk** [comment]
@GuardRex dotnet-publish-iis that is on the feed is currently broken. I committed a change today that fixes that today but it might be early next week until the new version is on the feed due to converting repos to dotnet from dnx.

**Comment by GuardRex** [comment]
Cool ... thanks. I'm good.

**Comment by moozzyk** [comment]
the lock files for tools go to artifacts/tools/{tool-name}/project.lock.json
