### ISSUE TITLE
Intrinsic CLI commands should be in a single project

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1149]
Today we're doing something pretty ridiculous, making each of the built in commands and making them separate projects and then publishing them to a single folder which ends up stomping all over each other. Instead of this madness, we should have a single project for the intrinsic commands and separate projects for the commands that aren't `built in`. Here's an example of what that could look like:

```
src/
   dotnet/
      commands/
         dotnet-compile/
         dotnet-compile-csc/
         dotnet-build/
         dotnet-new/
         dotnet-pack/
         dotnet-publish/
         dotnet-projectmodel-server/
         dotnet-resgen/
         dotnet-restore/
         dotnet-run/
         dotnet-test/
         dotnet-repl/
         dotnet-repl-csi/
         dotnet-compile-fsc/
```

Today, everything that ships with the dotnet CLI tools would be in the commands folder. Other commands can already be added as nuget packages so there's no blocker there. If we end up with another global install mechanism then we can revisit then.

/cc @piotrpMSFT @brthor @livarcocc

**Comment by davidfowl** [comment]
Added benefits:
- Simpler install
- Conflicts will be detected during restore and compile
- Faster builds

**Comment by blackdwarf** [comment]
@davidfowl this makes sense, but we should first go through the exercise of figuring out which commands go into the "core package" and which are extensions and then do this bit of work. 

/cc @piotrMSFT @Petermarcu

**Comment by davidfowl** [comment]
Instead of waiting on that, the non core commands can be ripped out when we figure out what those are

**Comment by anurse** [comment]
> the non core commands can be ripped out when we figure out what those are

This. It's been a bit difficult to keep things going when we have a bit of a mix of random new commands. Perhaps we need a separate cli-labs repo where we can work on the non-core commands? IMO, `repl` should be in a separate repo. I'd even suggest F# support be separate **for now** at least. I think F# is awesome and should be fully supported and maintained, but it feels too soon to be piling everything on into one repo. It slows down our development when we have to keep maintaining a large set of other unrelated projects...

**Comment by davidfowl** [comment]
Yes agreed, my only point was that we need a single project.json (aka set of dependencies) per executable. So a single project for built in things instead of pretending like we have separate executables and then stomping dependencies like crazy.

**Comment by blackdwarf** [comment]
@davidfowl but why do the double work? Or is it not double work? 

@anurse agreed wholeheartedly (jesus, I actually spelled that right on the first go). This is why I've been working on a proposal on how to do this last week and will share soon some ideas on how we can do this.

**Comment by davidfowl** [comment]
> @davidfowl but why do the double work? Or is it not double work?

It won't be double work for us. Just for the commands that need to move need to do more work.

**Comment by blackdwarf** [comment]
@davidfowl ok. @Petermarcu @piotrpMSFT you guys have any thoughts?

**Comment by brthor** [comment]
Will this make all the core commands in one .exe? Or will the `command` based pattern be preserved?

I really like that this will solve the dependency stomping in a simple way, and hopefully make bumping library versions less painful.

**Comment by anurse** [comment]
The core commands would be a single exe. We would still allow new commands to be provided by packages/path exes, and would also allow some of the core commands to be updatable (`dotnet-compile-csc` for example)

**Comment by davidfowl** [comment]
The code that symlinks the executables is probably broken

**Comment by piotrpMSFT** [comment]
@davidfowl open an issue for that one

**Comment by piotrpMSFT** [comment]
@davidfowl can we close this?

**Comment by brthor** [comment]
@davidfowl Symlinks should be easy enough to change.

just edit the debian configs in `packaging/debian` 

Remove everything but dotnet?

**Comment by dsyme** [comment]
>  I'd even suggest F# support be separate for now at least. I think F# is awesome and should be fully supported and maintained, but it feels too soon to be piling everything on into one repo. It slows down our development when we have to keep maintaining a large set of other unrelated projects...

I'm trying to understood what is meant by this.  The .NET CLI tools need F# support that is ultra-simple to use - there is no doubt about that. I assume it is part of the intended specification of the tools.  So what's the change in plan here and why?  The functionality shouldn't be optimized and reduced only for the benefit of the developers of the CLI tools....  We think of the users first, right?
