### ISSUE TITLE
dotnet-compile performance

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#115]
Right now the compilation performance is slow, even after we crossgen roslyn it'll still be slow. Here's  brain dump of some ideas on how to speed it up after we have crossgened everything:

- [ ] - Incremental compilation. If no inputs changed, don't recompile.
- [ ] - Out of process compilation server (like DTH and VBCSCompiler). Caches metadata references and syntax trees for a long time. Huge performance benefits here.

**Comment by cdmihai** [comment]
Incremental compilation and concurrent builds should increase performance.

Issue #232 discusses (status, specs, etc) incremental compilation.

**Comment by Petermarcu** [comment]
This is tracked in the other mentioned issues and PR's. Closing
