### ISSUE TITLE
CommandResolver should only be used by the dotnet driver command

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1150]
Today, commands are taking a dependency directly on `Microsoft.DotNet.Cli.Utils` in order to achieve the same resolution for dotnet commands as the driver does. Instead, extensions should just invoke dotnet blah and let the driver do the resolution. The biggest downside to this is that there's an extra process hop, but it keeps other extensions clean and doesn't leak the command resolution logic (which may change version to version).

/cc @piotrpMSFT

**Comment by davidfowl** [comment]
Another downside is that it would only work for `dotnet-{commands}`. We use it for `csc` etc.

**Comment by bricelam** [comment]
I'm trying to follow this guidance in dotnet-Ed. How do I find dotnet.exe? Using my parent process's path?

**Comment by bricelam** [comment]
Should we flow it in using CommandContext and environment variables?

**Comment by brthor** [comment]
@bricelam any reason you couldn't use the path?

**Comment by bricelam** [comment]
Will it always be on the path? (It isn't on my local dev box :smile:)

**Comment by brthor** [comment]
I think our targeted installation experiences will generally put it on the path. I guess it depends on exact scenarios.

cc @krwq Are there any installation mechanisms which don't use the path?

**Comment by bricelam** [comment]
Sounds like using `Env.GetCommandPath("dotnet")` should work. This will look first next to `corehost.exe`, then search the path.

**Comment by blackdwarf** [comment]
@brthor you're right, all of our proposed installation experiences (see #1482 for details) will put the tools on the path. 

@davidfowl is this OK to be closed or do we need this for tracking still?

**Comment by piotrpMSFT** [comment]
@bricelam We have a utility class which provides a first-class host path resolution. It prefers the host used even if it's different than the first host on the PATH!

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/Muxer.cs
