### ISSUE TITLE
Source-build patch removal for CLI

### ISSUE THREAD

**Issue by crummel** [dotnet/cli#11518]
Source-build has some patches that we are currently applying to your repo.  This issue tracks removing the patches.  These patches can be found at https://github.com/dotnet/source-build/tree/release/3.0/patches/cli.

Patches that have the responsibility "Repo" and the Disposition "Incorporate" are patches that we believe are valid source-build fixes that should be moved into your repo.  Please let us know if these don't seem like good patches.  Any changes with the responsibility "source-build" is something that we plan to keep going forward or integrate in another way - please also let us know if you think there may be problems with those patches.

Patch name | Type | Disposition | Responsibility | Notes
-- | -- | -- | -- | --
cli/0001-Implement-PVP-repo-API.patch | Flow | Incorporate | Repo |  
cli/0002-Exclude-test-projects-from-source-build.patch | ProjRemoval | Incorporate | Repo |  
cli/0003-Add-repo-specific-target-emptying-file.patch | Build | Incorporate | Repo |  
cli/0004-Consolidate-Newtonsoft.Json-versions.patch | No-op | Remove | source-build | Rebased after CLI took the fix but due to a whitespace diff this patch   remained although it does nothing.
cli/0005-Disable-signing.patch | Build | Remove | source-build | Tomas suggested that we should be able to open-sign things in   source-build.  Needs investigation.
cli/0006-Remove-keys-from-InternalsVisibleTo.patch | Build | Remove | source-build | This shouldn't be necessary if CLI correctly doesn't build tests in   source-build.  Could be either of our   problems.
cli/0007-Consolidate-CommandLine-versions.patch | Bug | RepoRemoval | Repo | This was an additional workaround for the cli-migrate signing issue and   should go away when that does.
cli/0008-Add-LangVersion-to-CLI.patch | ToolCompat | Remove | source-build |  
cli/0009-Revert-to-using-Newtonsoft.Json.patch | ToolCompat | Remove | source-build |

**Comment by crummel** [comment]
Hi Nick, I was just wondering if you had a chance to look at these or the other sdk/toolset/core-sdk patches yet.  Thanks!

**Comment by tmat** [comment]
@crummel @nguerrera 
Re [0005-Disable-signing.patch](https://github.com/dotnet/source-build/blob/release/3.0/patches/cli/0005-Disable-signing.patch) - why do we need to changes signing settings here?

Arcade sets the values for all projects here:
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/StrongName.targets

Are these projects special in some way?

**Comment by tmat** [comment]
Re [0006-Remove-keys-from-InternalsVisibleTo](https://github.com/dotnet/source-build/blob/release/3.0/patches/cli/0006-Remove-keys-from-InternalsVisibleTo.patch), I'd suggest using `InternalsVisibleTo` item group instead of attributes.

**Comment by nguerrera** [comment]
I think we wouldn't need to remove keys if we weren't changing signing. I think both patches should be removed. Agree on using InternalsVisibleTo, but I don't understand why this matters for source build. Seems like outdated change.

**Comment by nguerrera** [comment]
I have not had a chance to look these over. I will do so tomorrow.

**Comment by nguerrera** [comment]
> https://github.com/dotnet/source-build/blob/release/3.0/patches/cli/0001-Implement-PVP-repo-API.patch

> This is most likely temporary until we have a way to change dependencies using Arcade, or Arcade supports the repo API itself.

@crummel, why is that "incorporate". I assume Arcade handles this now?

**Comment by nguerrera** [comment]
> cli/0002-Exclude-test-projects-from-source-build.patch

Do we need this or will https://github.com/dotnet/arcade/pull/3034 handle it?

**Comment by nguerrera** [comment]
> Tomas suggested that we should be able to open-sign things in source-build.  Needs investigation.

It is a source build bug if source build removes PKT from any assemblies. Source build must produce matching identities as standard build.

**Comment by crummel** [comment]
Yes, Arcade should handle the PVP import now, and that should take care of 0002 as well.  I think the signing issues will go away with the removal of cli-migrate, that was causing several issues.
