### ISSUE TITLE
dotnet test should build the project

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1152]
Create a test project like the one from https://github.com/piotrpMSFT/dotnet-test-samples.
Do a dotnet restore in the test project
Do a dotnet test in the test project

Result:
dotnet crashes when it fails to locate an assembly, likely because it can't find the deps file.

Expected:
Either dotnet test should build the test project or it should fail with a message indicating that it can't find the deps file and that's likely because the project hasn't been built (or some other better error message).

I prefer one, with incremental build and all, this shouldn't be a problem.

**Comment by blackdwarf** [comment]
`dotnet test` should build the tests. We cannot make users run dotnet build on their tests every single time they want to run them. Hell, I would even say that `dotnet test` should detect and build the project as well if needed, but that is a different discussion.

**Comment by livarcocc** [comment]
@blackdwarf We are in agreement!

**Comment by blackdwarf** [comment]
@lajones weird, ain't it? :)

**Comment by blackdwarf** [comment]
@livarcocc @piotrpMSFT so what is the plan here? I think this is an important experience enhacement for using `dotnet test`.

**Comment by livarcocc** [comment]
@blackdwarf I just finished the VS debugging work for dotnet test, my next step is a series of improvements to dotnet test to support additional parameters. I will include the build work in there too. So, we should have it sometime this coming week.

**Comment by livarcocc** [comment]
Fixed by https://github.com/dotnet/cli/pull/1853
