### ISSUE TITLE
Improvements to global.json.

### ISSUE THREAD

**Issue by peterhuene** [dotnet/cli#11523]
This epic tracks the work for improving the SDK versioning in global.json.

**Comment by vbfox** [comment]
Is there any hope for the resolution of https://github.com/dotnet/core-setup/issues/679 to avoid the constant pain that is SDK versioning in the OSS world ?

**Comment by peterhuene** [comment]
@vbfox for 3.0 preview 8, we've implemented a slew of new functionality that gives more fine-grained control over how the .NET Core SDK resolution works.  Here is the [design document](https://github.com/dotnet/designs/pull/71) for the feature.

Unfortunately, version ranges were not in scope for the feature.  However, you can now pin to specific versions without any roll-forward and also prevent the resolution of preview versions if desired (two big asks from the community).

**Comment by peterhuene** [comment]
Closing epic now that dotnet/core-setup#6953 has been merged.
