### ISSUE TITLE
PublishSingleFile with RuntimeIdentifiers fail to publish

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#11543]
@johnlarfour commented on [Tue Jun 11 2019](https://github.com/dotnet/core/issues/2851)

`linux/amd64 dotnet 3.0.100-preview5-011568`

Step to reproduce:
```
dotnet new console -o app
```
Replace csproj with:
```
﻿<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64;win-x86;osx-x64</RuntimeIdentifiers>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup> 
</Project>
```
```
cd app
dotnet publish
```

Error:
```
/home/john/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(133,5): error NETSDK1097: It is not supported to publish an application to a single-file without specifying a RuntimeIdentifier. Please either specify a RuntimeIdentifier or set PublishSingleFile to false. [/home/john/Desktop/app/app.csproj]

```

**Comment by livarcocc** [comment]
You need to specify a single RuntimeIdentifier when publishing with Single File. The error message is correct and accurate in this case.

You can try to either edit your csproj to contain a single RuntimeIdentifier, like this
```
<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
```
Or, you can pass the -r parameter to the dotnet publish command.

**Comment by Sean-Driscoll** [comment]
@livarcocc - this is still unclear to me. Per the doc [here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#runtimeidentifiers), RuntimeIdentifier**s** exists to publish multiple self-contained deployments (i.e. it's akin to publishing several times with different RuntimeIdentifier values). By that logic I assumed it would publish multiple singles files, one per target RID. The part that is unclear to me is why it is not allowed.

**Comment by secana** [comment]
This is really unexpected behavior. Any plans to change it? Running a *dotnet publish* for each runtime seems unnecessary if a `RuntimeIdentifiers` exists which could build for multiple runtimes at once.

**Comment by livarcocc** [comment]
The way it works currently is that the RuntimeIdentifiers (plural) servers to inform NuGet that it should fetch all the necessary assets for all the Rids. Then, we you want to publish to a particular RId, you will need to do so one by one. We have a bug somewhere else to consider implementing the behavior of publishing for multiple rids, but I couldn't find it with a quick search, sorry.

**Comment by dasMulli** [comment]
RuntimeIdentifiers (plural) was removed elsewhere on the docs for a few reasons, mainly the restore not fetching the right versions anyway - see https://github.com/dotnet/docs/issues/9239

cc @mairaw do you think it is reasonable to remove it from the above mentioned doc as well?

**Comment by thomasd3** [comment]
This is an issue when using docker; for example I develop using a mac, but I deploy for docker / linux. By forcing a single identifier, I can't use the same project for developing and for deployment.

**Comment by dasMulli** [comment]
You can. Just don't set `RuntimeIdentifiers` in the project file. Adding `-r the-rid` to the publish command will create the correct output for the specified runtime.

**Comment by patanne** [comment]
There is a problem with @dasMulli's suggestion. I'll explain, but first the issue.

I am writing a utility that will run on Windows, Mac, & Linux. Requiring a project for each platform is almost as stupid as .NET Core not running on Intel 32-bit, almost. Yet that is what it seems is needed.

If I create a publish profile within Visual Studio 2019 or JetBrains Rider for that matter, even if I set deployment mode to "self-contained", the publishing process will ignore the setting unless the project file contains the <PublishSingleFile> tag. That can't happen unless it also contains the <RuntimeIdentifier> tag. And as this thread has demonstrated, the <RuntimeIdentifiers> tag is not valid.

I have smashed into Microsoft's "this is the intended behavior" excuse many times. Whatever their thinking here, they are wrong. One project. Multiple platforms. All single-file binary.

**Comment by Thraka** [comment]
@patanne  There can't be a single **executable** binary because each platform uses a different binary format that is based on the os+architecture. However, there is a single **library** binary that is generated by .NET Core which can be shared, the `<projectname>.dll`. Which you invoke with `dotnet file.dll`. Whenever you publish you'll see (with 3.0) both a platform-specific executable and a platform-agnostic library.

**Comment by patanne** [comment]
@Thraka What I am asking for is same as what I do in C/C++. Using cmake I can build a different binary for each os/architecture combo given I have the appropriate toolchain installed. The same should be possible in .NET. I am not asking for a single binary "to rule them all", just a single project... with multiple build configs. I am ok with multiple binaries.

**Comment by Thraka** [comment]
Gotcha! Yeah, I want that too. I guess I was confused by the `One project. Multiple platforms. All single-file binary.` part of your message :)

I think #10087 is the issue to track this request. Looking in that issue though I see https://github.com/onovotny/MSBuildSdkExtras as an interesting alternative until this gets implemented into .NET Core.

Cheers!
