### ISSUE TITLE
Getting started new app does not restore on OSX

### ISSUE THREAD

**Issue by bryanmacfarlane** [dotnet/cli#1154]
Installed latest OSX pkg:

$ dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64

Then:
```
dotnet new
dotnet restore
```
failed so I did ulimit -n 512 workaround.
again...
```
dotrestore
```

Failed on System.Security.Principal.Windows

```
...
info : Installing runtime.osx.10.10.System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc3-23720.
info : Installing runtime.osx.10.10.System.Diagnostics.Process 4.1.0-rc3-23720.
info : Installing runtime.unix.Microsoft.Win32.Primitives 4.0.1-rc3-23720.
error: System.Security.Principal.Windows 4.0.0-rc3-23720 provides a compile-time reference assembly for System.Security.Principal.Windows on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.11-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (osx.10.11-x64).
info : Committing restore...
info : Restore failed in 22557ms.
```

**Comment by christianhuening** [comment]
The same here, Get a lot of these:
```
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/.
An error occurred while sending the request.
```

**Comment by blackdwarf** [comment]
+1 on Ubuntu 14.04  Server (Azure VM):

```console
nfo : Restoring packages for /home/blackdwarf/new/project.json...
warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23727) but ended up with NETStandard.Library 1.0.0-rc3-23720.
warn : Dependency specified was NETStandard.Library (>= 1.0.0-rc2-23727) but ended up with NETStandard.Library 1.0.0-rc3-23720.
error: System.Security.Principal.Windows 4.0.0-rc3-23720 provides a compile-time reference assembly for System.Security.Principal.Windows on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64.
error: Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64).
info : Committing restore...
info : Restore failed in 3162ms.
```

Moving to `"NETStandard.Library": "1.0.0-rc3-23727"` actually made restore work for me. Does `dotnet new` need a new reference or not a fixed reference?

**Comment by christianhuening** [comment]
@blackdwarf I also tried to switch to RC3, but that didn't do the trick (OSX 10.11.3 here).
Also: Where can I find the available versions of NETStandard.Library?

**Comment by shahid-pk** [comment]
@christianhuening try with "NetStandard.Library": "1.0.0-rc3-*" and see if that solves the problem.

**Comment by christianhuening** [comment]
@shahid-pk I just did, didn't to anything to the problem. Still the same.

**Comment by shahid-pk** [comment]
@christianhuening  i was getting the same issue on ubuntu trusty and * solved it for me. may be its osx specific

**Comment by bryanmacfarlane** [comment]
Note that the error message is benign - things appear to work for me after that.  I'm on OSX 10.11.1 here.

**Comment by brthor** [comment]
On the release branch we've moved to core-rel based packages and I expect that is at least one cause of this failure. 

We should update the NuGet.config dropped by dotnet-new to point to core-rel feed.

**Comment by brthor** [comment]
PR should fix this: https://github.com/dotnet/cli/pull/1170

**Comment by livarcocc** [comment]
Tried it on OSX.
