### ISSUE TITLE
Linker warning LNK4044

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1156]
When I run `dotnet compile --native`, I get the following warning from the Visual C++ linker:

```
LINK : warning LNK4044: unrecognized option '/NOLOGO /ERRORREPORT:PROMPT /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /Debug /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT'; ignored
```

It seems that the arguments are all quoted together, resulting in the linker interpreting them as one long string.

**Comment by dionbr** [comment]
I'm getting the same issue.

**Comment by wjk** [comment]
@dionbr #1157 should have fixed this. Could you please retest with the latest version of .NET CLI?

**Comment by shahid-pk** [comment]
@wjk that commit did not went into the rel/1.0.0 branch so it will not be included in .net cli latest installers.

**Comment by wjk** [comment]
Oh, OK. Do you have any idea of when that commit will be released, or do we need to build from source to use it?

**Comment by shahid-pk** [comment]
the nightly build installers are build from rel/1.0.0 daily [sometimes not] . master is also merged into rel/1.0.0 but a team member should know the exact timing as when that happens.
And to answer your question yes right now build from source seems to be the only way to get that commit.

**Comment by dionbr** [comment]
@wjk That worked. Thanks

**Comment by blackdwarf** [comment]
@wjk @dionbr seems like there is a solution for this issue, so I will close this. Please reopen if needed.
