### ISSUE TITLE
'Dotnet.exe publish' silently creates bad format for mis-matching architectures

### ISSUE THREAD

**Issue by peterhuene** [dotnet/cli#11564]
@jjxtra commented on [Thu Jun 13 2019](https://github.com/dotnet/core/issues/2869)

When using `dotnet.exe publish` for specific runtimes, say win-x86, if using the 64 bit dotnet.exe, this runs without error, but when running the result executable, a `BadImageFormatException `is thrown. Same with target win-x64 from 32 bit dotnet.exe

It should be an error to create a runtime with the wrong 32 bit or 64 bit dotnet.exe, there should be an exception clearly stating that you need to run the dotnet.exe with the same architecture as the runtime you are targetting.

After two days of pain, I finally realized I had to fully qualify the path to dotnet.exe as I had both 32 bit and 64 bit sdk installed. So now for my 32 bit runtime targets, I use the 32 bit dotnet.exe, for the 64 bit targets, the 64 bit dotnet.exe. All run fine without errors.

Please add this as an error condition and save many, many people a lot of pain, headaches and frustration.

Example that fixes the problem in powershell:

```powershell
& "c:/program files/dotnet/dotnet.exe" publish Project.csproj -f netcoreapp2.2 -o package/linux-x64 -c Release -r linux-x64
& "c:/program files (x86)/dotnet/dotnet.exe" publish Project.csproj -f netcoreapp2.2 -o package/win-x86 -c Release -r win-x86
```

---

@karelz commented on [Fri Jun 14 2019](https://github.com/dotnet/core/issues/2869#issuecomment-502213331)

@livarcocc @nguerrera does it belong to CLI or core-setup?

---

@livarcocc commented on [Fri Jun 14 2019](https://github.com/dotnet/core/issues/2869#issuecomment-502213616)

CLI would be a good starting point. We can move it to core-setup if the issue was in the production of the apphost.

cc @peterhuene

**Comment by peterhuene** [comment]
@jjxtra what version of the SDK are you using?

**Comment by jjxtra** [comment]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment]
So with both a 64-bit and 32-bit `2.2.300` SDK, I get the expected behavior when publishing:

For `win-x86`:
```
C:\Users\Peter\tmp\repro>file bin\Debug\netcoreapp2.2\win-x86\publish\repro.exe
bin\Debug\netcoreapp2.2\win-x86\publish\repro.exe: PE32 executable (console) Intel 80386, for MS Windows

C:\Users\Peter\tmp\repro>file bin\Debug\netcoreapp2.2\win-x86\publish\coreclr.dll
bin\Debug\netcoreapp2.2\win-x86\publish\coreclr.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```

For `win-x64`:
```
C:\Users\Peter\tmp\repro>file bin\Debug\netcoreapp2.2\win-x64\publish\repro.exe
bin\Debug\netcoreapp2.2\win-x64\publish\repro.exe: PE32+ executable (console) x86-64, for MS Windows

C:\Users\Peter\tmp\repro>file bin\Debug\netcoreapp2.2\win-x64\publish\coreclr.dll
bin\Debug\netcoreapp2.2\win-x64\publish\coreclr.dll: PE32+ executable (DLL) (GUI) x86-64, for MS Windows
```

Would it be possible for you to determine which dll in your published application is of a mismatched format that would cause `BadImageFormatException` when loaded?

**Comment by peterhuene** [comment]
Also, does your project make use of the `PlatformTarget` property?

**Comment by jjxtra** [comment]
The .exe did look to be the correct architecture, so it must have been one of the other .dll files. I am using Microsoft.Data.Sqlite, perhaps the problem is there?

**Comment by jjxtra** [comment]
`<PlatformTarget>AnyCPU</PlatformTarget>`

**Comment by peterhuene** [comment]
From a 64-bit SDK publishing for `win-x86` (referencing `Microsoft.Data.Sqlite` version `2.2.4`):

```
C:\Users\Peter\tmp\repro>file bin\Debug\netcoreapp2.2\win-x86\publish\e_sqlite3.dll
bin\Debug\netcoreapp2.2\win-x86\publish\e_sqlite3.dll: PE32 executable (DLL) (console) Intel 80386, for MS Windows
```

Did the exception indicate which assembly (and its dependencies) to look at?

**Comment by jjxtra** [comment]
Unfortunately it just gave the exception and no other details, nothing in log files, console, stack trace or event viewer...

**Comment by peterhuene** [comment]
The SDK being x86 or x64 shouldn't impact this particular scenario since you're publishing for a specific RID and the host / runtime / native dependencies that are deployed with your application should match that RID.

I would need to figure out which of your dependencies is the wrong architecture when published.  It should be possible to use Visual Studio to debug the published application and hopefully get some more context.  Otherwise, would it be possible to obtain a minimal repro project that demonstrates the problem?

I could also look at your deps.json file in your publish folder for the broken publish output, if you would like (you can email me at pehuene@microsoft.com).  That file contains a list of your application's dependencies and file names, so be aware of that for privacy reasons and only share it with me if it is permissible to do so.

**Comment by jjxtra** [comment]
I'll send you an email

**Comment by jjxtra** [comment]
Ok I've played for several hours and now cannot reproduce this. Feel free to close and I will post back if I find a reliable way to reproduce this.

**Comment by jjxtra** [comment]
I believe this was a problem using latest .NET SDK with Visual Studio 2017. I had installed 2019 a while ago but uninstalled it. So I recently downgraded to the latest VS 2017 compatible .NET core SDK and that seems to have gotten things back in order.

**Comment by peterhuene** [comment]
@jjxtra thanks for following up.  I also have had no luck reproducing this either.  If you run into the problem again, let me know and we'll try to figure out the steps to reproduce.  I appreciate your assistance in trying to diagnose the problem via email!
