### ISSUE TITLE
dotnet publish recursivly publishes its own output

### ISSUE THREAD

**Issue by chrisbecke** [dotnet/cli#11575]
## Steps to reproduce
create a new dotnet core application, and publish it multiple times using the -o option

```
mkdir aspnetpublishtest
cd aspnetpublishtest
dotnet publish -o publish
dotnet publish -o publish
```

## Expected  behavior
The publish folder should be unaltered on the 2nd call to publish

## Actual behavior
The publish folder contains a copy of the publish folder for each call to publish.

## Discussion
While the problem doesn't occur in the default (bin/) output location, this seems an easy situation to end up in as it seems a common practice in CI/CD to use a folder with a stable name in the project tp publish to.

**Comment by livarcocc** [comment]
This is by design because of globbing. When globing content we can't distinguish the publish folder that was created by the publish operation from other folders in the application. So, it ends up being globed.

We exclude bin/obj from globbing, which is why if you use the regular publish folder, this does not happen.

You can edit the DefaultItemExcludes property to exclude your publish folder if you want.

**Comment by chrisbecke** [comment]
And there I thought that I needed to explicitly *add* asset folders I wanted to have published to the project.

**Comment by chrisbecke** [comment]
Ok, so heres a question:
Using an absolute path to publish to would break a CI/CD scenario where a server has multiple runners. So thats not a good idea.
Using a relative path via -o means you need to take steps to keep this folder clean between  publishes / excluded from publishing, but that violates the principal of least surprise as that introduces a hidden dependency between the CI/CD scripts choice of publish location and not-very-visible settings in a csproj.
Using the default folder is therefore attractive, but, its not well, or at all, documented, how one can coerce the dotnet cli into emitting the build path its going to use such that devops can write build scripts that don't randomly fail if the -c configuration changes and/or when netcoreapp2.2 changes to netcoreapp3.0 or some platform specific signifier.
