### ISSUE TITLE
Current 3.0 Preview 7 SDK can't build projects targeting lower SDK versions in the 16.3 Release channel build.

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#11585]
## Steps to reproduce
1. Install 16.3.0 [29018.65.master]([Release Channel](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/710819d747beda09ce59cbbbf69a82db4090fcab/258a92b4-1d34-4fee-88e3-fbb419f25336%3bchannels/internal/Release/bootstrappers/fixed/Enterprise/vs_Enterprise.exe))
2. Open an existing .NET Core 2.1/2.2 console application with reference to a .NET Standard class lib via VS. Build and run

## Expected  behavior
Build and run succeeded

## Actual behavior
![image](https://user-images.githubusercontent.com/33921754/59756414-3e67ae80-92bc-11e9-8ada-345ff0663665.png)
Output info:
error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

Note: Open an existing .NET Core 2.1/2.2 console application with reference to a .NET Standard class lib via CLI. Build and run succeeded.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012323
 Commit:    46c4932822

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012323\

Host (useful for support):
  Version: 3.0.0-preview7-27809-09
  Commit:  b2a369fb53

.NET Core SDKs installed:
  3.0.100-preview7-012323 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19307.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27809-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27809-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by richaverma1** [comment]
@YunWeiaa, where is the failure happening? when opening the project in VS? or when building the project? or when running the project? Also, do you have 2.1/2.2 checked in the installer?

**Comment by livarcocc** [comment]
Also, do you have a global.json for your project?

**Comment by livarcocc** [comment]
Also, I imagine this is happening on @johnbeisner 's private bits only.

**Comment by YunWeiaa** [comment]
@richaverma1 , the failure is happening when opening the project in VS. Yes, I have 2.1/2.2 checked in the installer.
![image](https://user-images.githubusercontent.com/33921754/59827582-af19d400-936b-11e9-814c-a8e7f1a0a926.png)

**Comment by YunWeiaa** [comment]
Thanks @livarcocc , today I try to dotnet new global.json for my project, it can work well.

**Comment by johnbeisner** [comment]
@YunWeiaa 
The 3.0 SDK insertion in the PR was at fault. I will update the SDK component versions and rebuild.

**Comment by YunWeiaa** [comment]
Not repro on “[[Release Channel](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/2ec8efc9df21f30b8d843c8d4b025b213f299ccf/4c37020a-8abf-8cb8-6b2b-b5fb2898982c%3bchannels/internal/Release/bootstrappers/fixed/Enterprise/vs_Enterprise.exe)]”( 16.3.0 [29021.39.master]).
