### ISSUE TITLE
Where can I find the code that discovers Host version printed by dotnet --info

### ISSUE THREAD

**Issue by SergeyKleyman** [dotnet/cli#11599]
I would like to log .NET Core runtime version and it seems there is no easy way to do it until [this change](https://github.com/dotnet/corefx/issues/35573) that is available only from .NET Core 3.0 Preview 4. On the other hand I see that `dotnet --info` does print

        Host (useful for support):
          Version: 2.1.8

So I was wondering if I can use the code in `dotnet` utility that discovers Host version in my application.

In the source code I see [`PrintInfo() method`](https://github.com/dotnet/cli/blob/master/src/dotnet/Program.cs#L299) but it misses the part in which I'm interested (Host version). Could you please point me as to where I can find it? Thank you in advance.

**Comment by livarcocc** [comment]
I believe this is what you are looking for: https://github.com/dotnet/core-setup/blob/aec6c77a664561249ecf763a642c6429c7891cdd/src/corehost/cli/fxr/command_line.cpp#L282.
