### ISSUE TITLE
was http CLI for API testing dropped.

### ISSUE THREAD

**Issue by bigpod98** [dotnet/cli#11597]
There is still no HTTP CLI for testing of APIs that was shown in build 2018 by scott hunter and scot hanselman

**Comment by livarcocc** [comment]
This repo is not the right place to ask these questions.

I don't believe we have plans on shipping the tool as a inbox verb on the CLI at this point in time. I believe the plan is to ship it OOB as a global tool.

If you want more information about it, a better repo to ask questions is probably here: https://github.com/aspnet/httprepl/issues.
