### ISSUE TITLE
Error occurred when min-code is specific on VAL 16.0 with CLI/SDK: 2.1.605(runtime- 2.1.12)

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#11616]
## Steps to reproduce
1. Create a new console app in VS(D16.0/[28803.527](https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/32dd098c5e3741ac40f9633ff8f4c1523c08ccbf/deb176a6-aec3-e88e-c5a3-7372e1785305%3Bbootstrappers/Enterprise/vs_enterprise.exe)(16.0.6 preview 1.0))
2. Modify the csproj with the following: `<Project Sdk="Microsoft.NET.Sdk/min=9999"> 
`
It shows as below:
![image](https://user-images.githubusercontent.com/33921754/60006380-dd1c5280-96a2-11e9-8e2a-3de3f88fab55.png)
3. Reload the project,

## Expected  behavior
There's a error in error list window:
 "The current .NET SDK does not support targeting .NET Core 2.1. Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."

## Actual behavior
Reload the project, it shows the error:
![image](https://user-images.githubusercontent.com/33921754/60006546-3dab8f80-96a3-11e9-8a94-4c4589608d98.png)

Note:
Then, close the project and reopen it, reload the project again, it shows as below:
![image](https://user-images.githubusercontent.com/33921754/60006712-8ebb8380-96a3-11e9-82ce-6a5ecd6f5024.png)
Output info:
```
error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
Version 2.1.605 of the .NET Core SDK is smaller than the minimum version 9999 requested. Check that a recent enough .NET Core SDK is installed, increase the minimum version specified in the project, or increase the version specified in global.json.


```

Note: Not repro on val 15.9 with CLI/SDK: 2.1.508(runtime- 2.1.12).
## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.605
 Commit:    6758443bff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.605\

Host (useful for support):
  Version: 2.1.12
  Commit:  ccea2e606d

.NET Core SDKs installed:
  2.1.605 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.
```1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by YunWeiaa** [comment]
Repro on D16.1/29020.173(16.1.4 preview 1.0) with CLI/SDK: 2.2.301(runtime:2.2.6).

**Comment by richaverma1** [comment]
The test steps seem to be missing the modification to the csproj file. I believe the modification is to add - <Project Sdk="Microsoft.NET.Sdk/min=9999">

**Comment by livarcocc** [comment]
@johnbeisner can you take a look?

**Comment by johnbeisner** [comment]
I can repro this error using VS(D16.0/28803.527(16.0.6 preview 1.0)) using SDK **2.1.604**
This behavior is not new.

**Comment by livarcocc** [comment]
@johnbeisner what is the conclusion here?

**Comment by nguerrera** [comment]
The expected behavior here is based on a prior bug. The new behavior is the correct behavior.

**Comment by nguerrera** [comment]
I'm following up to fix the instructions.

**Comment by nguerrera** [comment]
This expectation

> "The current .NET SDK does not support targeting .NET Core 2.1. Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."

Was only due to the 1.1 fallback SDK which was removed in VS 2019, getting in the way of this error, which is much more direct about the actual error:

> Version 2.1.605 of the .NET Core SDK is smaller than the minimum version 9999 requested.

**Comment by nguerrera** [comment]
I fixed up the test instructions on this.
