### ISSUE TITLE
Feature change: Update the dotnet new template acquisition story

### ISSUE THREAD

**Issue by seancpeters** [dotnet/cli#11619]
The delivery of dotnet new templates with the SDK is changing. The template acquisition logic in the dotnet new first run code will need to change accordingly.

The changes will need to be made here:
https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-new/NewCommandShim.cs

But we'll first need to fully define what the behavior should be.

**Comment by livarcocc** [comment]
This is done now.
