### ISSUE TITLE
dotnet-install.sh fail with a `Text file busy` error when dotnet process is running in background

### ISSUE THREAD

**Issue by damageboy** [dotnet/cli#11626]
## Steps to reproduce
run dotnet-install.sh on linux while a background dotnet process is running (for example background compiler)

## Expected  behavior
dotnet-install.sh should succeed

## Actual behavior
dotnet-install.sh will fail during the `cp -R` phase with a `Text file busy` error:

```bash
dotnet-install.sh -c master -i ~/dotnet/
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview7-012601/dotnet-sdk-3.0.100-preview7-012601-linux-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview7-012601/dotnet-sdk-3.0.100-preview7-012601-linux-x64.tar.gz
cp: cannot create regular file '/home/dmg/dotnet/dotnet': Text file busy
```

This is pretty common in Unix, and normally, to avoid this, most installers (such as dpkg, for example) will first remove the file (delete it) only then copy a new file instead of it.

I will submit a PR for this, I just wanted to report this separately and close via PR

## Environment data
`dotnet --info` output:
```bash
.NET Core SDK (reflecting any global.json): Version:   3.0.100-preview7-012601
 Commit:    6fedcd8ebd
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.04 OS Platform: Linux
 RID:         ubuntu.19.04-x64
 Base Path:   /home/dmg/dotnet/sdk/3.0.100-preview7-012601/
Host (useful for support):
  Version: 3.0.0-preview7-27824-03  Commit:  e1d780539e

.NET Core SDKs installed:  2.1.700 [/home/dmg/dotnet/sdk]
  3.0.100-preview6-012264 [/home/dmg/dotnet/sdk]
  3.0.100-preview7-012601 [/home/dmg/dotnet/sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.10 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.All]  Microsoft.AspNetCore.All 2.1.11 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.10 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19324.10 [/home/dmg/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.10 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]  Microsoft.NETCore.App 2.1.11 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27824-03 [/home/dmg/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
```

**Comment by damageboy** [comment]
I think the issue is with:
https://github.com/dotnet/cli/blob/7a96d9cb1a40d80b9ec99181fdd0fbb9458a94b9/scripts/obtain/dotnet-install.sh#L615

When I run the script with bash -x it's clear it's performing something like:
```bash
cp -R /tmp/dotnet.cBaYo4N8w/dotnet /home/dmg/dotnet/dotnet
```

This will fail if there is a `dotnet` process running...


The proper way to handle this would be to change the command like from `cp -R ...` to `cp -R --remove-destination`

Would you be interested in a PR for this?

**Comment by livarcocc** [comment]
@johnbeisner can you comment?

**Comment by johnbeisner** [comment]
@damageboy 
"This will fail if there is a dotnet process running" Wouldn't the deletion of 'dotnet' before the copy negatively impact the ongoing 'dotnet' process? In this instance, the correct outcome should be a failure of the new 'dotnet' installation.

**Comment by damageboy** [comment]
Not on unix systems.

Unix has this thing where you can delete open/mmap'd files and while the last reference pointing to that file/inode does disappear (e.g. you can't open that file from that moment on) running processes still have access to the file.. (also technically there is still "something" pointing to that file through /proc, but that's a bit nit-picky so lets skip that for now).

It's a rather well known oddity although people still find it surprising (esp. coming from windows):
https://serverfault.com/questions/232525/df-in-linux-not-showing-correct-free-space-after-file-removal

This is why most installers (like `dpkg` or `rpm` for instance) always delete before creating a new file during upgrade operations and so on...

I hope this clarifies a bit why this should be a decent approach on *nix system, and pretty "default" in the way that most *nix users expect things to work...

**Comment by damageboy** [comment]
@johnbeisner Any thoughts?

I'm no sure if my answer provided you with enough information to make a decision...

**Comment by johnbeisner** [comment]
@damageboy 
Your comments seem very resonable. How would I prove or dis-prove the above assertions?

**Comment by damageboy** [comment]
Good question, I guess my best bet is for you to try and either use my PR and replace the `dotnet` executable while there's some process running...

I did the following just now as a test:

1. Installed `dotnet-serve` as a global-tool: `dotnet tool install --global dotnet-serve`
2. Ran it from some directory
3. Test that it's serving on `http://localhost:8080` for example
4. Find the `pid` for the top-level dotnet process: `ps auxw | grep "dotnet serve" | grep -v grep`:
```bash
dmg     31101  0.3  0.0 3580664 76868 pts/7   Sl+  11:43   0:00 dotnet serve
```
5. Verify that it's actually pointing the the `dotnet` executalbe I'm about to replace: `ls -al /proc/<insert-pid-here>/exe`
```
ls -al /proc/31101/exe             
lrwxrwxrwx 1 dmg dmg 0 Jul  2 11:43 /proc/31101/exe -> /home/dmg/dotnet/dotnet
```
6. Check the current sha1sum for dotnet executable before we replace it: `sha1sum ~/dotnet/dotnet`
```
61552acb7360274cfed313780ce6682edd2df4e5  /home/dmg/dotnet/dotnet
```

7. Replace it with my patched dotnet-install.sh script from the PR, running it with bash -x to verify it uses the cp switch I suggested: `bash -x `which dotnet-install.sh` -c master -i ~/dotnet/`
```bash
...
+ local path=dotnet
+ local target=/home/dmg/dotnet/dotnet
+ '[' true = true ']'
++ dirname dotnet
+ mkdir -p /home/dmg/dotnet/.
+ cp -R --remove-destination /tmp/dotnet.VzLoY7sHN/dotnet /home/dmg/dotnet/dotnet
...
```

8. Check the new dotnet exectuable with: `sha1sum ~/dotnet/dotnet`:
```bash
8c48d6b003c51854e04c680b42b90600a02b6119  /home/dmg/dotnet/dotnet
```
9. Recheck that dotnet serve is still working / respoding (does in my case)

10. You can even recheck using the command we used in (5): `ls -al /proc/<insert-pid-here>/exe`
```bash
lrwxrwxrwx 1 dmg dmg 0 Jul  2 11:43 /proc/31101/exe -> '/home/dmg/dotnet/dotnet (deleted)'
```

**Comment by damageboy** [comment]
ping?

**Comment by johnbeisner** [comment]
@damageboy 
I've run a similar test like the one you have described; we are going to take this change. Thank you for your contribution.

**Comment by TravisEz13** [comment]
This change doesn’t work on macOS.  This switch doesn’t exist.  Can we revert or switch around the OS?

**Comment by damageboy** [comment]
Sure thing!

**Comment by johnbeisner** [comment]
https://github.com/dotnet/cli/pull/11974

**Comment by TravisEz13** [comment]
@damageboy yeah, I submitted #11974 to fix this
