### ISSUE TITLE
dotnet-nightly debian package conflicts with mono-runtime-common

### ISSUE THREAD

**Issue by shahid-pk** [dotnet/cli#1162]
..while trying to run hello world program.
dotnet nightly package version 1.0.1.001186-1
dotnet --version output
```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

dotnet --verbose run output
```

Running /usr/share/dotnet-nightly/bin/dotnet-build "--output" "/home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b" "--temp-output" "/home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b" "--framework" "DNXCore,Version=v5.0" "--configuration" "Debug" "/home/shahid/practise/csfirst"
Process ID: 4176
Project csfirst (DNXCore,Version=v5.0) will be compiled because expected outputs are missing.
 /home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b/Debug/dnxcore50/csfirst.dll
 /home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b/Debug/dnxcore50/csfirst.pdb

Running /usr/share/dotnet-nightly/bin/dotnet-compile "--framework" "DNXCore,Version=v5.0" "--configuration" "Debug" "--output" "/home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b" "--temp-output" "/home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b" "/home/shahid/practise/csfirst"
Process ID: 4192
Compiling csfirst for DNXCore,Version=v5.0
Running /usr/share/dotnet-nightly/bin/dotnet-compile-csc "@/home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b/dotnet-compile.rsp"
Process ID: 4208
Running /usr/share/dotnet-nightly/bin/csc "-noconfig" "@/home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b/dotnet-compile-csc.rsp"
Process ID: 4224

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:13.4302655
 

Running /home/shahid/practise/csfirst/bin/.dotnetrun/274f6a74c92447ea9024f9aefd57099b/Debug/dnxcore50/csfirst 
Process ID: 4248
Could not resolve coreclr path

```

**Comment by shahid-pk** [comment]
Note that `/home/shahid/practise/csfirst/bin/.dotnetrun/` is empty where it is trying to find the host probably its content got deleted during the compilation stage.
Also if i publish this app then it works.

**Comment by brthor** [comment]
@shahid-pk I am unable to repro this on a clean machine.

Can you provide any more details which might help narrow this down?

**Comment by shahid-pk** [comment]
@brthor 
After uninstalling mono-runtime-common package it works fine.  So i think its the conflict with mono issue. 
Should i close this issue ?

**Comment by brthor** [comment]
Let's change the issue and track this.

**Comment by shahid-pk** [comment]
I also noticed that mono-runtime-common package creates an empty dir named "dotnet" in /usr/share so installing dotnet-nightly does'nt complain and this problem occurs.
Strangely if you go and delete /usr/share/dotnet dir then installing dotnet-nightly installation fails with 
a conflict error message.
I am using ubuntu native package manager apt-get

**Comment by RichiCoder1** [comment]
I had the same error with the same resolution.
```text
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name: Ubuntu
 OS Version: 14.04
 OS Platform: Linux
 Runtime Id: ubuntu.14.04-x64
```
Running Linux Mint 17.3 Cinnamon 64-Bit.

The issue is that `mono-runtime-common` creates the folder `/usr/share/dotnet`, and doesn't allow `dotnet-nightly` to override it, as pointed out by @shahid-pk. The `mono-runtime` is installed by default on Linux Mint Cinnamon to power Banshee, a mono-build music player.
