### ISSUE TITLE
dotnet publish should give a better error message when the project has no lock file

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1163]
Today, when you try dotnet publish on a project without a lock file, we fail saying can't publish for tfm rid. We should say we can't publish because there is no lock file and the user should run dotnet restore.

**Comment by blackdwarf** [comment]
@livarcocc agreed, we should have better error message in this case.

**Comment by livarcocc** [comment]
We have a better error message now:

The current project is not valid because of the following errors:
/Users/livarcocc/Documents/git/temp/project.lock.json(1,0): error NU1009: The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.
