### ISSUE TITLE
program hangs unexpectedly

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/cli#11643]
## Steps to reproduce

Clone https://github.com/dotnet/coreclr (to say d:/repos/coreclr)
Clone https://github.com/AndyAyersMS/jitutils (to say d:/repos/jitutils)
  change to the MutateTest branch of jitutils
Install 3.0 Preview 6 

cd to d:/repos/jitutils/src/MutateTest

dotnet run -c Release --  --ehStress --recursive d:\repos\coreclr\tests\src\jit\jit64 --quiet

Processing 537 test files
// d:\repos\coreclr\tests\src\jit\jit64\eh\basics\loopEH.cs: 29 variants, all passed
// d:\repos\coreclr\tests\src\jit\jit64\eh\Common\common.cs: did not compile successfully
// d:\repos\coreclr\tests\src\jit\jit64\eh\FinallyExec\nestedTryRegionsWithSameOffset1.cs: did not compile successfully
...  more output like this ...

## Expected  behavior

Program processes all 537 files and exits

## Actual behavior

Hangs eventually, amount of progress before hang varies

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18917
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-010309 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview3-19111-10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27412-2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27411-23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by peterhuene** [comment]
@AndyAyersMS why do you think this belongs in the CLI rather than runtime?  Would it be possible to capture stacks of the hang?

**Comment by AndyAyersMS** [comment]
@livarcocc asked me to open this here based on some email discussion.

I have a dump I can share.

**Comment by peterhuene** [comment]
Ah, didn't know @livarcocc already had some context on the issue.  From first glance it seems the CLI isn't involved with the hang since we've successfully exec'd the target test assembly, but I can take a look at the dump.

**Comment by peterhuene** [comment]
Thanks @AndyAyersMS for forwarding the mail thread.  The `dotnet exec` / apphost process appears to terminate, so it is the `dotnet run` process that is hanging and it appears related to telemetry.  Assigning to @wli3 to do the preliminary investigation.

**Comment by wli3** [comment]
@peterhuene as you suggested. We looked at the main thread. It is waiting for `System.Diagnostics.Process.WaitForExit` so that is the running the app itself is blocking.

```
08 00007ff8`26ce1946 : 000001f3`ad815970 00000000`ffffffff 000001f3`accc77f0 000001f3`ab030360 : System_Diagnostics_Process!System.Diagnostics.Process.WaitForExitCore(Int32)+0x88 [/_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs @ 170] 
09 00007ff8`26deb954 : 000001f3`ad815970 00000000`00000008 000001f3`accc77f0 000001f3`ab030360 : System_Diagnostics_Process!System.Diagnostics.Process.WaitForExit()+0x16 [/_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs @ 1351] 
0a 00007fff`ee2413e5 : 000001f3`ad815a88 0000008b`d437e260 00000000`00000008 00000000`00000000 : Microsoft_DotNet_Cli_Utils!Microsoft.DotNet.Cli.Utils.Command.Execute()+0x2c4 [/_/src/Microsoft.DotNet.Cli.Utils/Command.cs @ 63] 
0b 00007fff`ee2410f6 : 000001f3`aceac4e8 000001f3`aceac560 000001f3`aaf30930 00000000`00000008 : dotnet!Microsoft.DotNet.Tools.Run.RunCommand.Execute()+0x85 [/_/src/dotnet/commands/dotnet-run/RunCommand.cs @ 56] 
0c 00007fff`ee263963 : 000001f3`ace989a8 000001f3`ace989a8 00007fff`87205ab8 000001f3`acccb008 : dotnet!Microsoft.DotNet.Tools.Run.RunCommand.Run(System.String[])+0x16 [/_/src/dotnet/commands/dotnet-run/Program.cs @ 
```
