### ISSUE TITLE
Trusty apt feed is broken (again)

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#1165]
Our CI system (and developers) are having problems because the feed is again broken.

Repro steps:

```sh
sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet-nightly
```

Results in:

```
E: Failed to fetch http://apt-mo.trafficmanager.net/repos/dotnet/pool/main/d/dotnet-nightly/dotnet-nightly_1.0.1.001186-1_amd64.deb  404  Not Found
```

We're depending on this feed as part of our build/test process. While we could work around this by instead downloading and manually installing the Debian packages, this would be less than ideal as we wouldn't be testing the latest CLI each build (to make sure our projects don't break each other).

/cc @blackdwarf @piotrpMSFT

**Comment by blackdwarf** [comment]
/cc @brthor 

@andschwa this has been a known issue with the feeds, @brthor is working with the relevant folks to try and fix this. If you need the latest, can't you use the local install to unblock?

**Comment by andschwa** [comment]
I'm contemplating that, updating our CI build to `wget` the package and `dpkg -i` it, but then we'd stop testing the feed (which is listed in our readme for previewers to use in order to build).

Developers are unblocked.

**Comment by andschwa** [comment]
@blackdwarf Feed is working now, thanks!

**Comment by andschwa** [comment]
It's really hit and miss, but it seems to work enough times that retrying the build is fixing it.

**Comment by brthor** [comment]
Thanks for the visibility on this @andschwa .

Working with the appropriate team to try and get this issue resolved.
