### ISSUE TITLE
x86 build configurations are missing

### ISSUE THREAD

**Issue by vsccarl** [dotnet/cli#11656]
## Steps to reproduce
1. Create a .NET Core 3.0 project
2. Change build configuration to x86 in Configuration manager
3. Build

## Expected  behavior
Projects are built as expected.

## Actual behavior
Unable to build the project.
```
NU1102	Unable to find package Microsoft.NETCore.App.Host.win-x86 with version (= 3.0.0-preview7-27826-20)
  - Found 2 version(s) in nuget.org [ Nearest version: 3.0.0-preview6-27804-01 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages	WpfApp3	C:\Users\v-sccarl\source\repos\WpfApp3\WpfApp3\WpfApp3.csproj	1	
```
And when opening the WPF designer this error shows up:
```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\v-sccarl\AppData\Local\Microsoft\VisualStudio\16.0_4660ea3a\Designer\Cache\11878078826x86DA\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files (x86)\dotnet] or use the DOTNET_ROOT(x86) environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation].
```
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
Version:   3.0.100-preview7-012688
Commit:    84048fc1ff

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.17763
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012688\

Host (useful for support):
  Version: 3.0.0-preview7-27826-20
  Commit:  ee0c7ead1a

.NET Core SDKs installed:
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.400-preview-010219 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012688 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19326.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27826-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27826-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by livarcocc** [comment]
This is by design.

We only carry packages offline for the architecture that the SDK targets itself, so, x64 SDK brings with it x64 packages. Likewise for x86. So, you will need to add package feeds (until we release the packages to nuget.org) to be able to restore.

You will also need to install the x86 runtime separately in order to run the application.

We intend to install both x86 and x64 runtimes in VS 16.3, but not sure yet in which preview this will land.

**Comment by peterhuene** [comment]
For the feeds to use, check out this section in [the dotnet/core-sdk README](https://github.com/dotnet/core-sdk#installers-and-binaries).
