### ISSUE TITLE
dotnet publish (pack?) should be extensible to allow for other packaging/installer techs to plug in.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#1166]
The output of publish by default is a self contained folder of assets to be able to run on a target. Creating a "package" out of those things using various technologies should be something that can get put in the pipeline. For example, with additional metadata, there is no reason an MSI, appx, rpm, or deb couldn't also be an output of publish.

Definitely needs more thought but wanted to get this tracked.

**Comment by Petermarcu** [comment]
@robmen FYI

**Comment by blackdwarf** [comment]
@Petermarcu love this idea, actually. Will take a stab on how this could look like.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
