### ISSUE TITLE
Dotnet new a project returns some errors with .Net Core 3.0 Preview 7

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#11700]
## Steps to reproduce
1.  Install SDK 3.0.100-preview7-012769
2. Dotnet new a console APP and observe the result
3. Dotnet new a UnitTest or web APP and observe the result

## Expected  behavior
On step2,3, dotnet new a project works normally

## Actual behavior
1. On Step2, returns some errors
![image](https://user-images.githubusercontent.com/1578239/60494497-7c63ca00-9ce1-11e9-85bf-03e7d09be6bc.png)
2. On step3, take mvc app for example, it will returns "Could not find install descriptor for template: Microsoft.Web.Mvc.CSharp.3.0"
![image](https://user-images.githubusercontent.com/1578239/60494592-addc9580-9ce1-11e9-8515-46664f98e3fb.png)

##Note
Dotnet build, restore, run works succeed.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012769
 Commit:    3d1e17251c

 

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012769\

 

Host (useful for support):
  Version: 3.0.0-preview7-27901-06
  Commit:  df2b1489de

 

.NET Core SDKs installed:
  3.0.100-preview7-012769 [C:\Program Files\dotnet\sdk]

 

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19351.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27901-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27901-06 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/templating/issues/1979.
