### ISSUE TITLE
dotnet build complain the the lock file is not up to date

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1171]
1. Clone EF from aspnet/entityframework.
2. `dotnet restore` in the root
3. Go to `test\Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests`
4. `dotnet build` 

Result:

```
Compiling Microsoft.EntityFrameworkCore for .NETFramework,Version=v4.5.1
D:\aspnet\entityframework\src\Microsoft.EntityFrameworkCore\project.lock.json(1,0): warning NU1006: Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.
```

**Comment by anurse** [comment]
Is this not actually an issue or did you just adopt the workaround I suggested?

**Comment by victorhurdugaci** [comment]
Your workaround fixed the issue. Reopened to fix the root cause

**Comment by anurse** [comment]
Yeah, there's still an issue here, in that we shouldn't be seeing the project file as different. Thanks for re-opening :)

**Comment by natemcmaster** [comment]
See also https://github.com/dotnet/cli/issues/970#issuecomment-178163678

**Comment by natemcmaster** [comment]
Compile started failing for Microsoft.Data.Sqlite due to NU1006. CI just started using 1.0.0.001183 (previously using on 1.0.1.001200)

**Comment by davidfowl** [comment]
@anurse what's the bug here?

**Comment by anurse** [comment]
The problem was that some framework assemblies were being rendered differently (not just `fx/` but also version number issues). I'm not sure exactly if @natemcmaster is hitting the same issue.

**Comment by anurse** [comment]
@natemcmaster That failure is not caused by NU1006. NU1006 is a warning and won't halt the build. That failure is due to csc crashing:

> C:\Users\appveyor\AppData\Local\Microsoft\dotnet\cli\bin\dotnet.exe "compile-csc" "@C:\projects\microsoft-data-sqlite\src\Microsoft.Data.Sqlite\obj\Debug\net451\dotnet-compile.rsp" returned Exit Code -1073741819

We see that on builds with broken crossgen bits, so make sure you're using the latest bits and that issue might fix itself.

@victorhurdugaci @natemcmaster If either of you can provide a simple repro project that displays this behavior (NU1006, even though you just restored), that would help a lot. I need to look at the exact difference between the expected output and the actual output to try and track this down.

**Comment by piotrpMSFT** [comment]
@victorhurdugaci @natemcmaster is this still blocking-partner? If so, can we please get a repro to investigate?

**Comment by natemcmaster** [comment]
I haven't seen this error in the latest updates of cli. @victorhurdugaci okay to close this?

**Comment by victorhurdugaci** [comment]
Yup

**Comment by andschwa** [comment]
We're intermittently gettings failed builds with the error:

```
dotnet-compile.rsp returned Exit Code -1073741819
```

Which led me here. We are using `frameworkAssemblies` for our FullCLR build, and using recent 1.0.0 builds. What's the correct solution? (Sounds like several were discussed.)

**Comment by anurse** [comment]
`frameworkAssemblies` should be working. Are you building on Windows or non-Windows?

**Comment by andschwa** [comment]
@anurse Both. The issue appears when building for `dnx45` on Windows, and it is *only* intermittent.

I will get the target framework updated as it really shouldn't be using `dnx45` and update.

**Comment by andschwa** [comment]
Tried targeting `net451` (no other changes), still intermittently (but frequently) fails.

```
Unhandled Exception: 
  
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\cli\bin\dotnet.exe compile-csc @C:\projects\secret\src\dependency\obj\Debug\net451\dotnet-compile.rsp returned Exit Code -1073741819
```

It's super annoying because re-running the exact same build can be successful. Any clues?

**Comment by vors** [comment]
Should we open a separate issue for it, since it's not exposed as warning about lock file anymore?

**Comment by andschwa** [comment]
@vors Yes I think so.
