### ISSUE TITLE
bump NuGet dependency to -569

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1174]

**Comment by davidfowl** [comment]
Can we make this a * I think we want to grab daily nuget builds until it's stable

**Comment by piotrpMSFT** [comment]
@davidfowl let's talk about it tomorrow. We can do it in the next pr.

**Comment by davidfowl** [comment]
Is this the highest versioon?

**Comment by moozzyk** [comment]
:+1: for *
