### ISSUE TITLE
dotnet test should work when passed both a project.json or a dll

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1183]
We need to allow dotnet test to run when passed the test dll to it.

**Comment by blackdwarf** [comment]
@livarcocc you mean something like `dotnet test path/to/test.dll`?

**Comment by lpodolak** [comment]
I wonder why this has been closed?

I'm giving a .net core a try and I'm trying to build a basic CD pipeline, according to the rules from "the CD bible". One of the rule is that you should build your binaries once, and only once. Each stage should get the binaries and do some verifications on them. One of early stages should be running your unit tests against ALREADY BUILT binaries. 

This is what we can't achieve in dotnet core right now, or am I missing something?
Currently, to run any tests, you need to compile binaries again, which is definitely against this (very good) rule.

**Comment by livarcocc** [comment]
You don't say which version of the CLI you are using. Anyways, if you are using preview3, you can use dotnet test to run tests for a project file or you can use dotnet vstest to run tests against a dll. So, your scenario should be covered.

**Comment by lpodolak** [comment]
Sorry, I should have stated that, I'm using: 1.0.0-preview2-1-003177. I've looked at the docs of preview3 CLI and I don't see anything like vstest command (https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/layering). Is this a new command that isn't yet described in docs? Can you please shed me some light on this before I decide to migrate to preview3? Thanks

**Comment by blackdwarf** [comment]
@lpodolak yes, this is a new command and the docs about it are incoming. Sorry about that. You can get more info if you install Preview 3 and run `dotnet --help`. By installing here I don't mean installing globally. You can use the ZIPs/tarballs to install to a specific, isolated place on disk and then try it out.

**Comment by piotrpMSFT** [comment]
@lpodolak let us know once you've had a chance to try this out.

**Comment by lpodolak** [comment]
guys, thanks for an instant help. 
I didn't try the preview 3 yet, as it is not that easy. As far as I understand, using preview 3 CLI obliges me to port my projects to csproj from json/xsproj firstly. This requires me however to move from VS 2015 (which doesn't support the new-old format) to VS 2017 RC. 
Using the RC is something I'd rather avoid at this point of time, as I try to minimize (the already large) set of uncertainties that I need to face on my roadmap. 

If my understanding is wrong however, can you please advice how can I achieve runnning tests on dll without the need to use VS 2017 RC?

BTW, it may be obvious to you, but I struggle to find a download link to dotnet CLI preview 3. The download links on https://github.com/dotnet/cli page point to preview4 and I don't see any option to see any historical builds to get the RIGHT preview 3 binaries.

**Comment by blackdwarf** [comment]
@lpodolak for the last bit, here is the link for the doc with all of the links for Preview 3: https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md
