### ISSUE TITLE
dotnet test fails to find dotnet-test-xunit when called with dotnet test path/to/project.json

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1184]
This also repros when we call dotnet test path/to/folder/with/project.json.

It fails with an error "No executable found matching command "dotnet-test-xunit"". It works if you run dotnet test from the project folder directly.

We probably need to adjust the command resolving code.

**Comment by brthor** [comment]
To note here, ProjectTools and ProjectDependencies command resolvers take a ProjectDirectory as input so this scenario is open from the resolver perspective.

**Comment by livarcocc** [comment]
@brthor I know, just didn't get to it yet.

**Comment by livarcocc** [comment]
It is working now after all the changes we did to the Resolvers.
