### ISSUE TITLE
dotnet run does not support path with spaces

### ISSUE THREAD

**Issue by YEVHENO** [dotnet/cli#1189]
I perform following steps in the command line:

cd: C:\Test\My Folder
dotnet new
dotnet run

"dotnet run" returns "Unrecognized command or argument 'Folder'"

See console output below:

```
C:\Test\My Folder>dotnet new
Created new project in C:\Test\My Folder.

C:\Test\My Folder>dotnet run
Unrecognized command or argument 'Folder'
```

**Comment by YEVHENO** [comment]
OS: Microsoft Windows [Version 6.1.7601]
.NET CLI: win-x64.latest

**Comment by brthor** [comment]
@YEVHENO How did you install the cli?
Also what version of windows? Win10/Win7? Version 6.1 seems foreign to me :smile:

**Comment by YEVHENO** [comment]
I have downloaded https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi and run installer.

Version 6.1 is "Windows 7":
```
c:\>ver
Microsoft Windows [Version 6.1.7601]
```

**Comment by blackdwarf** [comment]
@brthor did your fix for quoting paths fix this as well?

**Comment by brthor** [comment]
@blackdwarf yes this issue should be fixed. I am unable to repro, although I haven't tested on Win7. Test machines there are coming online soon.

@YEVHENO Can you please update to the latest CLI and see if you are still hitting this.

**Comment by piotrpMSFT** [comment]
Dotnet --version?

**Comment by blackdwarf** [comment]
This is not reproing for me anymore. Will close. If this still reproes, please reopen.
