### ISSUE TITLE
dotnet test coverage with partially failed tests

### ISSUE THREAD

**Issue by saxenark** [dotnet/cli#11914]
Hi,

I am using .net core 2.2 in my ASP.NET core application. My command line to invoke tests is like so:

dotnet test -v n <path_to_test_csproj> -c Release --no-build --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=\"opencover,lcov,Cobertura\" /p:CoverletOutput=<path_to_coverage_results> --results-directory <path_to_test_results>

I have added reference to coverlet like so:
dotnet add package coverlet.collector
dotnet add package coverlet.msbuild

When I run the dotnet test command line (as above), there are 3 of my tests which fail and no code coverage file is geneated. I however, want the code coverage report to be generated even if the tests fail (something that Visual Studio IDE based code coverage does).

How can I achieve code coverage results even if some of my tests fail?

Thanks,

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2095
