### ISSUE TITLE
Restore  with waning NETSDK1080 after target the project(mvc/web/webapi) framework from 2.1 to 3.0

### ISSUE THREAD

**Issue by Jepson109** [dotnet/cli#11930]
## Steps to reproduce
1.Install .NET Core 3.0 Preview 7 build 3.0.100-preview7-012821
2.Open an existing 2.1 (mvc/web/webapi) project
3.Target the project(mvc/web/webapi) framework from 2.1 to 3.0

## Expected  behavior
Dotnet restore & dotnet build successfully

## Actual behavior
**Dotnet restore  with warning NETSDK1080.** Details as below :
![image](https://user-images.githubusercontent.com/38854445/61362997-cb028e00-a8b5-11e9-8a59-f614eb5228cf.png)
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(154,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
  Restore completed in 158.55 ms for C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj.

**Dotnet build failed with warning and error.** Details as below :
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(154,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(154,5): warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Sdk.Razor.CurrentVersion.targets(404,5): warning RAZORSDK1006: Detected Razor language version downgrade. This is typically caused by a reference to the Microsoft.AspNetCore.Razor.Design package. Consider removing this package reference. [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
Startup.cs(39,56): warning CS0618: 'IHostingEnvironment' is obsolete: 'This type is obsolete and will be removed in a future version. The recommended alternative is Microsoft.AspNetCore.Hosting.IWebHostEnvironment.' [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
Startup.cs(35,55): warning CS0618: 'CompatibilityVersion.Version_2_1' is obsolete: 'This CompatibilityVersion value is obsolete. The recommended alternatives are Version_3_0 or later.' [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
Startup.cs(55,13): warning MVC1005: Using 'UseMvc' to configure MVC is not supported while using Endpoint Routing. To continue using 'UseMvc', please set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices'. [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.1.2\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(69,5): error : The project C:\Users\v-zhuqin\Desktop\mvc23 must provide a value for Configuration. [C:\Users\v-zhuqin\Desktop\mvc23\mvc23.csproj]
    6 Warning(s)
    1 Error(s)

![image](https://user-images.githubusercontent.com/38854445/61363429-9216e900-a8b6-11e9-8a50-1a516eab7c2a.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This is by design and the error message is stating the actions you can take to fix your project. Have you given that a go?

**Comment by Jepson109** [comment]
@livarcocc I remove the unnecessary PackageReferences when targeting .NET Core 3.0, the project can be restore successfully
