### ISSUE TITLE
 dotnet-install.sh does not download correct version on RHEL 6 workstation

### ISSUE THREAD

**Issue by winnieryl** [dotnet/cli#11940]
https://dot.net/v1/dotnet-install.sh
this script, at line 151, it does not consider RHEL 6 Workstation, when I run this on rhel6 workstation, it downloads the wrong version fo dotnet runtime.

## Steps to reproduce
prepare a rhel 6 workstation, run dotnet-install.sh to install dotnet runtime

## Expected  behavior
download dotnet runtime rhel6 version

## Actual behavior
does not download the correct version

## Environment data
`dotnet --info` output:

**Comment by johnbeisner** [comment]
Workstation:
 /etc/redhat-release
 Red Hat Enterprise Linux Workstation release 6.2 Beta

 Client:
 /etc/redhat-release
 Red Hat Enterprise Linux Client release 5.9 (Tikanga)

 Server:
 /etc/redhat-release
 Red Hat Enterprise Linux Server release 5.9 (Tikanga)

**Comment by winnieryl** [comment]
Thanks for the fix, waiting to download it from website.

**Comment by johnbeisner** [comment]
@winnieryl 
We have uploaded this to: https://dot.net/staging/dotnet-install.sh
Can you see if this addresses your issue.

**Comment by winnieryl** [comment]
> @winnieryl
> We have uploaded this to: https://dot.net/staging/dotnet-install.sh
> Can you see if this addresses your issue.

@johnbeisner 
Hi, Yes this works! 
Thanks

**Comment by winnieryl** [comment]
@mairaw Hi, I notice this was closed, but https://dot.net/v1/dotnet-install.sh is not updated.

**Comment by mairaw** [comment]
@winnieryl they will probably release the script soon to the download site. Can you check if the script at https://dot.net/staging/dotnet-install.sh works for you?

**Comment by winnieryl** [comment]
> @winnieryl they will probably release the script soon to the download site. Can you check if the script at https://dot.net/staging/dotnet-install.sh works for you?

yes, staging works for me.
