### ISSUE TITLE
Keyboard input disappears in a Linux terminal window after a .NET Core Application throws an exception.

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/cli#1196]
**Issue**: You have a .NET Core console application that handles input stream from standard input. In a Ubuntu terminal window when that application either crashes or throws an exception and returns the control back to the terminal, the subsequent keyboard input no longer appears in that terminal window.

Same behavior has been observed with **CentOS** and **RHEL**.

**Repro**: Execute the below code by running "**dotnet run**" and observe keyboard activity in the terminal window once the control is back after the exception.

using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            
            String str = "Hello World";
            Console.WriteLine(str.ToUpper());
            Console.WriteLine("Press Any Key(s) to continue and then observe the Keyboard activity");
            Console.ReadLine();
            str=null;
            Console.WriteLine(str.ToLower());
            
        }
    }
}

This appears to be a bug in forwarding I/O streams across processors. 

**Workaround**: Run **"dotnet build"** instead of **"dotnet run"** and execute the compiled binary from ./bin/Debug/dnxcore50/appname

**Comment by blackdwarf** [comment]
@Raviuppa so this only repros using `dotnet run`?

**Comment by Raviuppa** [comment]
Yes, issue happens only with "dotnet run'.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Wed, Feb 3, 2016 at 6:39 AM -0800, "Zlatko Knezevic" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Raviuppa<https://github.com/Raviuppa> so this only repros using dotnet run?

-

**Comment by blackdwarf** [comment]
@Raviuppa can you check the latest stable builds and see if this still repros?

**Comment by Raviuppa** [comment]
Yes, issue still happens with cli build 1.0.0.001331-1 which is now available at http://dotnet.github.io/gettingstarted as stable build.


Thanks,
Ravi.

**Comment by Raviuppa** [comment]
Seems like the bug is fixed. Can not repro the issue with the new CLI tar bits . Closing it for now.
