### ISSUE TITLE
dotnet-install.sh:  fails on macOS

### ISSUE THREAD

**Issue by dtivel** [dotnet/cli#11964]
## Steps to reproduce
On macOS open bash shell and execute:
```
curl -o ./dotnet-install.sh https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh -i ./cli -c 1.0
```
## Expected  behavior
Install will succeed.

## Actual behavior
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-sdk-1.1.11-osx-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-sdk-1.1.11-osx-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-dev-osx-x64.1.1.11.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.11/dotnet-dev-osx-x64.1.1.11.tar.gz
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```

The root problem is [this change](https://github.com/dotnet/cli/commit/7a1afb7e707e44fd3a3c6e0dd81dc92aa9b7f7d9#diff-3385102241bcd3718b9ca13a0c55b9afR615).  On macOS `cp` does not have a `--remove-destination` option.

**Comment by johnbeisner** [comment]
@dtivel 
@zivkan 
Thank you for reporting the BUG

These are the officially supported locations for 'dotnet-install':
https://dot.net/v1/dotnet-install.sh
https://dot.net/v1/dotnet-install.ps1
You can use the versions directly from the CLI repo; however, you will less consistent results as you will be using the 'developmental' versions.

**Comment by johnbeisner** [comment]
Related: https://github.com/dotnet/cli/pull/11974
