### ISSUE TITLE
dotnet restore fails with RuntimeFrameworkVersion specified 

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/cli#11994]
## Steps to reproduce
When specified `<RuntimeFrameworkVersion>3.0.0-preview7-27912-14</RuntimeFrameworkVersion>`, `dotnet restore` fails

## Expected behavior
Downloads `3.0.0-preview7-27912-14` for `Microsoft.NetCore.App.Runtime.linux-arm64` and `3.0.0-preview7.19365.7` for `Microsoft.AspNetCore.App.Runtime.linux-arm64`

## Actual behavior
Errors with 
`Unable to find package Microsoft.AspNetCore.App.Runtime.linux-arm64 with version (= 3.0.0-preview7-27912-14)`

It looks like it is using the `RuntimeFrameworkVersion` to download the associated `AspNetCore.App.Runtime`

From msbuild.binlog, the KnownFrameworkReference knows about `3.0.0-preview7.19365.7`, but once its about to be restored, the version range is replaced and uses `3.0.0-preview7-27912-14`.

**KnownFrameWorkReference:**
![image](https://user-images.githubusercontent.com/3953714/61838220-21834580-ae3d-11e9-8bf0-de6c8a303b6a.png)

**Restore Task:**
![image](https://user-images.githubusercontent.com/3953714/61838407-f3eacc00-ae3d-11e9-98b8-d0ee17cab0ae.png)

## Environment data
<details>
<summary>`dotnet --info` output:</summary>

<p>

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /root/dotnet/sdk/3.0.100-preview7-012821/

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  3.0.100-preview7-012821 [/root/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/root/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/root/dotnet/shared/Microsoft.NETCore.App]
```

</p>

</details>

**Comment by livarcocc** [comment]
@dsplaisted can you comment on the proper way to do this now?

**Comment by dsplaisted** [comment]
If possible, I would recommend simply not setting `RuntimeFrameworkVersion`, and letting the SDK select the version to use.

The problem is that the preview versions for .NET Core and ASP.NET Core don't match.  The SDK knows which versions to use by default, but if you try to specify a specific version, there's no way to look up which version of ASP.NET Core would correspond to the specified .NET Core version.

So if you really need to do this, you need to specify two different versions, by using `RuntimeFrameworkVersion` metadata on each `FrameworkReference`:

```xml
<ItemGroup>
    <FrameworkReference Update="Microsoft.NETCore.App" RuntimeFrameworkVersion="3.0.0-preview7-27912-14" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" RuntimeFrameworkVersion="3.0.0-preview7.19365.7" />
</ItemGroup>
```

**Comment by WardenGnaw** [comment]
We will have to go with the `FrameworkReference` solution while coreclr 3.0 is in preview. 

Sadly, not specifying `RuntimeFrameworkVersion` would make it difficult to diagnose coreclr issues with different debugger releases.
