### ISSUE TITLE
Enable debugging of tests with dotnet test

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1201]
Find a way to allow for debugging when using dotnet test

**Comment by moozzyk** [comment]
A `--debug` flag that allows you to attach to the process might be the first step

**Comment by programatt** [comment]
Currently the only way I was able to get debugging in visual studio was to add `System.Diagnostics.Debugger.Launch();` to the source. Is that seriously the only way to debug anything right now?

**Comment by moozzyk** [comment]
@programatt - you can also do `Console.WriteLine()` :imp:

**Comment by cdmihai** [comment]
+1

**Comment by blackdwarf** [comment]
@livarcocc is this being worked on?

**Comment by livarcocc** [comment]
We have added a dotnet test debug experience in VS.

**Comment by masaeedu** [comment]
@livarcocc Is this documented somewhere?

**Comment by RemiBou** [comment]
@livarcocc is this documented ? or is this issue still opened ?

**Comment by livarcocc** [comment]
I am not sure about the documentation. But it is just like any other tests in VS.

**Comment by masaeedu** [comment]
@livarcocc I don't really understand what you mean. If you've added a "dotnet test debug experience", how is a user supposed to invoke it? I'd imagine there's some command line flag or options you have to pass to `dotnet test`, but I can't see this documented anywhere.

**Comment by livarcocc** [comment]
What I mean is that you can do that in VS, but not in the command line.

**Comment by bobbyg603** [comment]
Documentation would be really helpful here! I haven't been able to figure this one out.

**Comment by fedoranimus** [comment]
@livarcocc Why is this issue closed? As far as I can tell, the issue hasn't actually been resolved as described.

**Comment by livarcocc** [comment]
What I mean is that you can discover tests for core in VS and debug them through VS.

**Comment by fedoranimus** [comment]
Ah, okay.

I guess I assumed this issue was more about being able to add a flag such as `--debug` to `dotnet test` in order to allow the debugging of all discovered test cases via the CLI for use in applications like VSCode.

**Comment by NightOwl888** [comment]
> What I mean is that you can discover tests for core in VS and debug them through VS.

And what about tests that don't fail in Visual Studio but fail when running dotnet test? How do we debug those?

**Comment by omarpiani** [comment]
nunit3-console https://github.com/nunit/docs/wiki/Console-Command-Line has --debug option.

I think that's really easy and useful if you want to debug without visual studio or for some other (buggy) reason!

Reopen this!!!

**Comment by fedoranimus** [comment]
I agree that the issue has not been resolved and should be reopened.

**Comment by livarcocc** [comment]
Please, file an issue under microsoft/vstest for this.

**Comment by smbecker** [comment]
I came across this issue because I was looking for a way to debug tests launched from the command line. I came across [this line](https://github.com/Microsoft/vstest/blob/06101ef5feb95048cbe850472ed49604863d54ff/src/vstest.console/Program.cs#L22) that indicates that if you set `$env:VSTEST_RUNNER_DEBUG=1` then you can use `dotnet test` and it will wait for the debugger to attach before continuing execution. I verified that this does work. Hopefully this is helpful for others.

**Comment by YairHalberstadt** [comment]
Setting $env:VSTEST_HOST_DEBUG=1 allows you to debug the actual tests being run

**Comment by hananiel** [comment]
> Setting `$env:VSTEST_HOST_DEBUG=1` allows you to debug the actual tests being run

on linux/mac: `export VSTEST_HOST_DEBUG=1`
