### ISSUE TITLE
dotnet restore usage refers to nuget3 (cosmetic)

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1202]
`dotnet restore` usage refers to `nuget restore` - should be `dotnet restore`:

```
PS C:\Source\IISIntegration> dotnet restore --help

Usage: nuget3 restore [arguments] [options]
```

**Comment by borgdylan** [comment]
I believe that such a change would need to land in NuGet proper. \cc @emgarten

**Comment by piotrpMSFT** [comment]
Restore is intentionally a wrapper around basic nuget3 functionality. Advanced functionality will be exposed through nuget correctly. It's OK for this convenience alias to express that it is just invoking the tool.
