### ISSUE TITLE
dotnet restore fails with an object null exception

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1204]
This happens when the project.json has a reference in it that dotnet cannot find. We should fail with a more graceful error message.

**Comment by emgarten** [comment]
@livarcocc do you have repro steps? This has worked in the past.

**Comment by livarcocc** [comment]
This seems to be an issue inside our dotnet restore and not nuget, just to be clear. the repro is easy, just do dotnet new and add a dependency for something that does not exist.

**Comment by sabastiaan** [comment]
When I add a non existing dependency I get this message

"error: Unable to resolve <NonExistingDependacy>  (>= 1.0.0) for DNXCore,Version=v5.0" 

Isn't this wanted behavior?

**Comment by livarcocc** [comment]
Well, I have a repro at this branch: https://github.com/livarcocc/cli-1/tree/null_pointer_nuget.

Just clone it and run:

1. build.cmd to build the CLI
2. cd {reporoot}/test/argumentforwardingtests
3. dotnet restore

You should see the error: object reference not set to an instance of an object.

This started happening when I added a reference from argumentforwardingtests to reflector. Reflector is in the same folder as the tests.

Also, I debugged out dotnet test command and this error show up immediately after we run nuget xplat.

**Comment by sabastiaan** [comment]
But if it is something that only occurs in your own forked repo, shouldn't this issue be in that repository instead of this one?

**Comment by blackdwarf** [comment]
@livarcocc is this still valid? Also, as @sabastiaan said, I cannot repro. Latests bits on OS X give me a decent message that nonexistent package cannot be restored. I will close for now, and if you are still seeing this, please reopen.
