### ISSUE TITLE
dotnet test LogFileName break change in 2.2.300

### ISSUE THREAD

**Issue by elvisFabian** [dotnet/cli#12124]
The last docker image `mcr.microsoft.com/dotnet/core/sdk:2.2` upgrade **DOTNET_SDK_VERSION** to **2.2.300**

## Steps to reproduce
- Create multiples test projects
- run: `dotnet test --logger "trx;LogFileName=TestResults.trx"`

## Expected  behavior
Create a unique file name per test project 

## Actual behavior

**Using DOTNET_SDK_VERSION=2.2.202**
```
Results File: TestResults_2019-08-02_17-34-32-725.trx
Results File: TestResults_2019-08-02_17-34-36-381.trx
Results File: TestResults_2019-08-02_17-34-39-323.trx
```

**Using DOTNET_SDK_VERSION=2.2.300**
```
WARNING: Overwriting results file: TestResults.trx
result/TestResults.trx

WARNING: Overwriting results file: TestResults.trx
Results File: TestResults.trx

WARNING: Overwriting results file: TestResults.trx
Results File: TestResults.trx
```

## Workaround
Fix the tag of docker image to `FROM mcr.microsoft.com/dotnet/core/sdk:2.2.200`

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2113
