### ISSUE TITLE
Move dotnet-compile-native to CoreRT repo

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1213]
This is a multi-part issue. 

Goal:
We want to deliver the dotnet-compile-native command from the https://github.com/dotnet/corert repo so the command lives along with the rest of the native toolchain. Projects that want to compile to native will reference the command in the `tools` section of their project.son. They will invoke the native compiler by calling `dotnet compile-native` instead of `dotnet compile --native`.

Steps:
- [ ] Make dotnet-compile-native a stand-alone command, moving associated logic out of dotnet-compile
- [ ] Package the dotnet-compile-native command as a nupkg and reference it as a nupkg from associated tests
- [ ] Move appdeps from a build-time dependency to a package dependency of the dotnet-compile-native package
- [ ] Move the command sources to the CoreRT repo
- [ ] Remove dotnet-compile-native tests from CLI repo

Open Issues:
- [ ] What do we want to call the command? `dotnet-compile-native`? @gkhanna79 @schellap @blackdwarf 
- [ ] Do we need to continue forwarding `dotnet-compile --native`?

/cc @gkhanna79 @schellap @blackdwarf @richlander @livarcocc @Sridhar-MS @brthor @anurse @davidfowl

**Comment by blackdwarf** [comment]
For the first question, we could go with build. For the second, I think we should but I need to think some more on the message this surface area sends.

**Comment by aL3891** [comment]
-1 for forwarding dotnet-comple --native moving forward, cli hasnt even rtm:ed and its such a minor change to update the command name anyway

**Comment by livarcocc** [comment]
This has been moved out of the CLI.
