### ISSUE TITLE
Tools restore fails if you have the sources for the tool as reference

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1215]
Create this structure:

- `src\dotnet-mytool\project.json`
- `test\testProj\project.json`
- `global.json`

1. Make `dotnet-mytool` a dotnet tool.
2. Add the tool in the tools section of the test project
3. Add "src" to global.json
4. Restore the test project

Expected: restore works
Actual: null ref exception

The exception happens because the tools restore generates a temporary project with the tool as dependency. Then, upon restore, since the source code for the tool is available, it will restore the tool as a project reference. 

cc @piotrpMSFT @Sridhar-MS

**Comment by piotrpMSFT** [comment]
@victorhurdugaci this gets pretty tricky. how do you suggest we select the build configuration, ensure that a build of the tool exists, and find the output path of the tool if it's non-default?

This seems much easier for users to understand if we could ask NuGet Restore to prefer package references over project references. I think @davidfowl said there is a bug tracking this, but I can't seem to find it on https://github.com/nuget/home...

**Comment by victorhurdugaci** [comment]
Agree it's tricky to get it right as a project reference. Maybe the CLI can detect if it's a project reference and give an actionable error.

**Comment by blackdwarf** [comment]
@piotrpMSFT @victorhurdugaci gents, what is the latest on this?

**Comment by piotrpMSFT** [comment]
We have a workaround were using in a few places. Typically, using the tool in the repo that produces it means that we are testing the tool. To enable testing at the moment we put a global.json in the test's root directory to block p2p references. We then pack the tool during build and restore it to the test.

Tools are undergoing a small redesign right now to compensate for shared framework. Once that is done we can look at further improving this experience.

**Comment by victorhurdugaci** [comment]
We workaround this by having a small test framework that copies the test project in a folder outside the repo root and then runs the tests in that folder.

**Comment by piotrpMSFT** [comment]
Global.json seems much cheaper for the same benefit...

**Comment by piotrpMSFT** [comment]
Tracked in https://github.com/NuGet/Home/issues/2469
