### ISSUE TITLE
Problem installing SDK 3.0.100-preview7-012821

### ISSUE THREAD

**Issue by enricoreich** [dotnet/cli#12207]
Hello,

I tried to install .Net Core SDK 3.0.100-preview7-012821 but the Windows installer completes after 3 seconds without any error and none of the packages are installed at `C:\Program Files\.dotnet`.
If I restart the installer `dotnet-sdk-3.0.100-preview7-012821-win-x64.exe` the dialog gives me options to repair or uninstall. If I click uninstall it completes immediately. If I click repair, the process starts to copy the payload but almost at the end I get this message:

![install_fail](https://user-images.githubusercontent.com/316637/62829856-68c25200-bc03-11e9-99f0-7222612d0a83.png)

after I've confirmed OK 4 times, I get this message:

![install_fail2](https://user-images.githubusercontent.com/316637/62829874-bd65cd00-bc03-11e9-830e-65eae31588c5.png)

Log: [Microsoft_.NET_Core_SDK_3.0.100_-_preview7_(x64)_20190811062155.log](https://github.com/dotnet/cli/files/3489507/Microsoft_.NET_Core_SDK_3.0.100_-_preview7_.x64._20190811062155.log)

Steps I tried:
- checked Windows App & Features to make sure no .Net Core SDK is listed
- deleted `C:\Program Files\dotnet` if existing
- deleted `.dotnet` folder at my Windows profile
- deleted `.templateengine` folder from my Windows profile.
- deleted all files in `AppData\Local\Temp`
- reboot system
- download SDK again
- cried out for help!
- write this issue

Note: .Net Core SDK dotnet-sdk-2.2.401-win-x64.exe setup runs without any problems!

## Steps to reproduce
1. download .Net Core SDK 3.0.100-preview7-012821 for Window 64Bit from https://dotnet.microsoft.com/download/dotnet-core/3.0
2. run the installer

## Expected  behavior
Setup should run normal installation process and do its intended thing!

## Actual behavior
Setup completes after 3 seconds, nothing is installed.

## Environment data
OS: Windows 10 Education 1903 (18326.267)

**Comment by livarcocc** [comment]
@johnbeisner can you please take a look?

@enricoreich I would not recommend deleting files from Program Files manually, but we will look at the logs and come up with a recommendation on how to address this.

**Comment by johnbeisner** [comment]
@enricoreich 
Can you provide the log files for this installation. They should be in your %temp% folder.

**Comment by johnbeisner** [comment]
2578:2AB0][2019-08-11T06:22:17]i301: Applying execute package: AspNetCoreSharedFramework_x64, action: Repair, path: C:\ProgramData\Package Cache\{1D8E1EF4-2D42-3B1D-97B2-099AF85F20A3}v3.0.0.0\AspNetCoreSharedFramework-x64.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" DOTNETHOME="C:\Program Files\dotnet"'
[2578:2AB0][2019-08-11T06:22:55]e000: Error 0x80070643: Failed to run maintanance mode for MSI package.

**Comment by johnbeisner** [comment]
The repair action is failing for one MSI: AspNetCoreSharedFramework-x64.msi
The rest of the MSIs seem to execute a repair just fine.
The odd thing here is the name of the MSI: "AspNetCoreSharedFramework-x64.msi" it doesn't follow the typical naming convention: "netstandard_targeting_pack_2.1.0_preview7_27912_14_win_x64.msi"

Looking further...

**Comment by enricoreich** [comment]
@johnbeisner Thanks for looking into it but I think this issue is obsolete because of the availability of preview8. I mean you don't have to waste your time unless it is of further interest on your part.
The preview8 SDK windows installer `3.0.100-preview8-013656` from [dot.net](https://dot.net) runs without problems.

I close this issue but feel free to reopen if you need further information on this. :)

**Comment by johnbeisner** [comment]
@enricoreich thanks for bringing this up because I think the non-versioned name of the MSI is a potential problem because the repair/uninstall would need to know which MSI to 'call' given that a user might more than 1 SDK. We will look into this further.
