### ISSUE TITLE
Unexpected version of Dotnet SDK when building from v2.1.605+dependencies  

### ISSUE THREAD

**Issue by ForestEckhardt** [dotnet/cli#12219]
## Steps to reproduce
This was was run on cloudfoundry/cflinuxfs3 image:
```
git clone https://github.com/dotnet/cli.git
cd cli/
git checkout v2.1.605+dependencies
apt-get update
apt-get -y upgrade
apt-get -y install 'clang' 'devscripts' 'debhelper' 'libunwind8' 'libpython2.7' 'liblttng-ust0' 'liburcu6' 'libllvm3.9' 'liblldb-3.9'
export DropSuffix=true
export TERM=linux
./build.sh /t:Compile
```

## Expected  behavior

When we go to our build artifacts at `bin/2/linux-x64/dotnet` and run `./dotnet --info`, we see 2.1.605 underneath our .NET Core SDKs installed.

## Actual behavior

The only SDK installed is 2.1.508.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.508
 Commit:    d6ea7c5835

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /cli/bin/2/linux-x64/dotnet/sdk/2.1.508/

Host (useful for support):
  Version: 2.1.12
  Commit:  ccea2e606d

.NET Core SDKs installed:
  2.1.508 [/cli/bin/2/linux-x64/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [/cli/bin/2/linux-x64/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [/cli/bin/2/linux-x64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [/cli/bin/2/linux-x64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
@peterhuene can you take a look at the tag and make sure it is pointing to the right commit?

**Comment by peterhuene** [comment]
It's not.  508 and 605 are pointing at the same commit.  I'll correct.

**Comment by peterhuene** [comment]
@ForestEckhardt thanks for bringing this to my attention.  I accidentally tagged the 2.1.508 commit as it flowed into the `release/2.1.6xx` branch, rather than the previous commit that was to update the dependencies for the `release/2.1.6xx` branch.

If you fetch upstream and check the tag out, you should now see `<VersionPatch>605</VersionPatch>` in `build/Versions.props`.
