### ISSUE TITLE
How to use same dependency (version) in multiple project.json?

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#1223]
A repository usually contains multiple projects and maybe multiple solutions. 
With dotnet cli now there are multiple `project.json` (instead of multiple `csproj`)

I list possible solutions i know if i want to use the same dependency (same version) in multiple project.json (if there are more, ok my bad):

1. create a project.json for each project, and manually update references (and version) each time
2. create a single project.json, if possible. It cannot always be possible, multiple nuget packages, helper app, etc.
3. make `dotnet restore` pluggable, because standard behaviour cannot be not enough in different context. Or use another tool like dotnet restore.
4. ?? 

### A real world example: this repository.

Use of `-*` for dependencies has problems, so a specific version is pinned for the dependencies.
Now each `project.json` should be updated when we need to bump a version of dependancies (like `NETStandard.Library` ).
That's not assure the same version of a shared package, because in two project with different dependancies, dotnet restore may use different version (each project.json is isolated by others).

I think in the dotnet cli the solution applied is the `2`, to use a  single exe. That's how i understood the recent change from multiple .exe to a single exe, i can be wrong.

I really prefer `3` (make `dotnet restore` pluggable), but that's another discussion so below it's my proposal:

## use a shared depedencies list and aliases

The idea it's not mine, it's from multiple working solution in different ecosystem (bundler in ruby, etc)

use a shared global list of dependencies in the root of repo, like aliases, who can be grouped.
Each project **can** use an alias in the dependencies property of project.json, and the generated .lock.json use the same version of the dependency in the shared global list.

something like:

global.json:

```json
"dependencies": {
    "$NETStandard_Library": "1.0.0-rc2-23728",
},
```

project.json:

```json
"dependencies": {
    "NETStandard.Library": "$NETStandard_Library",
},
```

The shared global list of dependencies are all resolved together or in groups, so it's fast (no need for multiple parallel project.json restore) and versions of grouped packages are compatible (so `library-a` use same version of `package1` as `library-b`, but `library-b` can use also others different dependancies).

I wrote **can**, because it's an additional possibility the aliases, current behaviour can continue to exists (like in .csproj a path reference can coexists with nuget reference). 
I think it's a sane default to have all deps version in only one place, and `project.json` use only aliases.
the `project.json.lock` continue to exists, exatcly the current behaviour, no need to change all tools

Pls that's a problem who exists now, it can be ignored but is a common use case not covered by current dotnet cli and project.json project model.
I think the problem was discussed before in dnx, but dotnet/cli it's not dnx, it use only assemblies on disk so it's easier

i think i read something by @blackdwarf thinking about something else for this issue, but i can be wrong ( lots of notifications )

**Comment by davidfowl** [comment]
This is a nuget feature. We're not going to design this in the CLI. It *is* a big problem and we do want to solve it though.

**Comment by enricosada** [comment]
Nuget is the package manager ok, but `project.json` project model it's there. 

We ask nuget to resolve dependancy graph, and download packages.
nuget doesnt read the project.json, dotnet restore do it ( i can be wrong obv ).

It's not bad per se having nuget doing some work and `dotnet restore` doing some other.
A clean split help long term, and implementing alias in the client ( `dotnet restore` ) fix the problem without changing nuget.

**Comment by shahid-pk** [comment]
:+1:  for this   ....... But
i think dotnet/cli uses nuget client libraries for restore which comes from nuget and those libraries are responsible for reading project.json while restoring so i also think this should be fix in nuget instead.

I could be wrong i have not looked into the code in the last few weeks and the code is changing very quickly.

**Comment by davidfowl** [comment]
>i think dotnet/cli uses nuget client libraries for restore which comes from nuget and those libraries are responsible for reading project.json while restoring so i also think this should be fix in nuget instead.

It doesn't. It directly shells into nuget. We should *NOT* diverge from nuget. That was part of the goal moving from dnu to the new CLI. The CLI acts like a driver for other tools and restore is a nuget feature. NuGet tools exist on the command line and in visual studio. It needs to work across different project types in the same solution. Forking will only cause more chaos.

**Comment by shahid-pk** [comment]
@davidfowl thanks for the correction .
But this is still a very good proposal and should happen here or in nuget , i don't care  :smile:

**Comment by davidfowl** [comment]
> But this is still a very good proposal and should happen here or in nuget , i don't care  :smile:

Agreed but I do care and it should be in nuget :smile:

**Comment by blackdwarf** [comment]
@enricosada can we then move this to nuget/home and close this one? I agree with @davidfowl this is a nuget feature.

**Comment by csharpfritz** [comment]
This sounds like an issue we are already tracking on NuGet at: NuGet/Home#1703

**Comment by enricosada** [comment]
@csharpfritz 3 months without discussion is not really encouraging. The world policy 
 Is strange

I wrote about current project.json and dotnet cli becuase is a new start, so maybe we can fix deep problems with old model, no need to fork nuget

I think have a clean separation can help a lot. Nuget client can restore, but should be dotnet restore who parse project.json and create packages list passed as args to nuget client. 
No need for nuget client to understand project json, that only make stuff more complex and fixed. 

I am not speaking about fork nuget. Server is ok, client too but workflow can be improved. Nuget client resolve list of packages, i think passing project.json to nuget client is not the right abstraction

Now there is a real command dotnet restore, that can help a lot

**Comment by csharpfritz** [comment]
Project.Json and transitive dependencies are where we are taking NuGet to.  That feature is already decided and is the future.  This also allows NuGet to resolve package dependencies and write the project.lock.json file that MSBuild can pick up and reference.

As @davidfowl stated: package management and package references are managed by NuGet, which the dotnet CLI will call directly.  Lets continue the conversation over in the NuGet repo.

**Comment by enricosada** [comment]
Sure let's discuss in nuget repo. I'll open tomorrow an issue

I hope the use case now is more clear becuase previous attempts to explain the problem were pretty much ingnored. 

I think project.json.lock is ok but other option are needed for solution/repo level version and reproducible build ( another use case useful in dotnet cli repo too but ignored by nuget, and commit lock file doesnt work otherwise that was done here too i think )

It's not a rant/flame/fud. 

I want to discuss about these problems. And i like dotnet cli. i see the same issue we get with current nuget and csproj and i think was worth a try discuss the use case where people with same problem (dotnet cli team) can read about it and think about a possible solution. 
If answer is discuss in nuget, ok :)

**Comment by csharpfritz** [comment]
Use the issue linked above that discusses this feature directly, no need to
open another issue



Jeff
