### ISSUE TITLE
dotnet dev-certs https --trust --check is ok but client cannot trust development certificate

### ISSUE THREAD

**Issue by mpetrinidev** [dotnet/cli#12251]
## Steps to reproduce

- Create .NET Core 3.0 + Api on VS for Mac
- Call API with postman
  - GET https://localhost:5001/api/session

## Expected  behavior

- Call Api successfullly

## Actual behavior

Postman throws

```
Error: unable to verify the first certificate
Request Headers:
Content-Type:"application/json"
```

If I run `dotnet dev-certs https --trust --check`

- A valid certificate was found.
- A trusted certificate was found.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview8-013656/

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.1.700 [/usr/local/share/dotnet/sdk]
  2.2.301 [/usr/local/share/dotnet/sdk]
  3.0.100-preview6-012264 [/usr/local/share/dotnet/sdk]
  3.0.100-preview7-012821 [/usr/local/share/dotnet/sdk]
  3.0.100-preview8-013656 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]```

**Comment by livarcocc** [comment]
@anurse @javiercn can you take a look? Should I move this to asp.net?

**Comment by sayedihashimi** [comment]
Related (but I think different) issue https://github.com/dotnet/cli/issues/12221

**Comment by anurse** [comment]
Yeah, it looks like a similar problem. @BrennanConroy can you see if you can repro something like this on a Mac and help load balance a bit here (cc @javiercn).

It seems like this should be a clear repro based on the reports we've gotten.

**Comment by BrennanConroy** [comment]
I tried this out on my mac and I had to turn off "SSL certificate verification" in Settings > General because Postman says "Self-signed SSL certificates are being blocked"

**Comment by anurse** [comment]
We investigated and this is *not* related to #12221 in the end.

Safari is showing the certificate as fully trusted in our repro, but Postman still produces this error. This seems to be a limitation in Postman. The certificate is fully trusted, even though it's self-signed, but Postman still refuses to use it. The recommended fix is to toggle the setting @BrennanConroy mentioned ("SSL certificate verification").

@mpetrinidev if you are seeing errors using a standard browser (like Chrome, Firefox, Safari), please let us know. Our `dev-certs` command *should* be automatically configuring the certificate as trusted, which should be sufficient for most clients.

**Comment by anurse** [comment]
I think we can close this now. @mpetrinidev if you have further issues with certificates or ASP.NET Core applications, please file issues in https://github.com/aspnet/AspNetCore so we can help right away!
