### ISSUE TITLE
dotnet tool install fails if user NuGetFallBack folder doesn't exist

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#12255]
```
C:\Users\rlander\Downloads>dotnet tool install -g dotnetsay
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\NuGet.targets(123,5): error : The local source 'C:\Users\rlander\.dotnet\NuGetFallbackFolder' doesn't exist. [C:\Users\rlander\AppData\Local\Temp\hl5bzqvt.3nr\restore.csproj]
The tool package could not be restored.
Tool 'dotnetsay' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

C:\Users\rlander\Downloads>dir ..\.dotnet\n*
 Volume in drive C is Windows
 Volume Serial Number is 384B-0B6E

 Directory of C:\Users\rlander\.dotnet

File Not Found

```

**Comment by livarcocc** [comment]
Did you create that fallback folder? Do you have it configured in a NuGet.Config.

This is not really unique to tools. Restoring a project will likely fail as well. NuGet does not support specifying a source that does not exist.

**Comment by richlander** [comment]
I don't have a nuget.config. I tried the same command at the root of "C" and I get the same error.

**Comment by richlander** [comment]
This is where it is coming from. I don't remember adding that. Any ideas?

![image](https://user-images.githubusercontent.com/2608468/63048570-ab965b00-be8b-11e9-9341-80c15952e9c9.png)

Seems related to: https://github.com/dotnet/cli/issues/7256

**Comment by livarcocc** [comment]
I don't know what would add that. We used to add that at the very beginning of 1.0 when we were experimenting with fallback folders.

The error you are getting is completely expected given that configuration in VS. And that configuration gets reflected on your NuGet.Config file under %appdata%/NuGet if I remember correctly.

**Comment by richlander** [comment]
OK. I'll assume I have a machine in a weird state. If others users see this same problem, please say so on this issue.

**Comment by Thealexbarney** [comment]
I ran into this issue on Win 10 with 3.0.100. Same error when trying to restore with no local nuget.config file. The `.nuget` directory in my user directory is gone for some unknown reason. I assume the fix would be to recreate the folder.
