### ISSUE TITLE
Install .NET Core tool/app without .NET Core SDK on the machine

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/cli#12262]
## Steps to reproduce
I'm migrating an existing .NET Framework app to .NET Core. Since .NET Framework is default windows component installed on all Windows machines, my existing .NET Framework app doesn't need to consider the situation what if .NET Framework is not on the machine. However, for .NET Core app, I can make it as a .NET Core Global tool, but it requires .NET Core SDK installed on the machine. To match with current .NET Framework app experience (run on all Windows machines), looks like I have to make it a self-contained app as well besides a .NET Core Global tool.  

## Expected  behavior
It would be very helpful if there is an way to install .NET Core Global tool without .NET Core SDK prerequisite on the machine.

## Actual behavior
In order to install .NET Core Global tool, .NET Core SDK has to be on the machine.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
I don't follow the relationship you are implying between being self-contained and running by itself in a machine without the shared framework and being a global tool.

Can you clarify that?

If it helps, this link has more information about .NET Core's deployment models: https://docs.microsoft.com/en-us/dotnet/core/deploying/.

 Being self-contained/framework dependent is orthogonal to being a global tool (though currently we only support framework dependent global tools).

**Comment by Lxiamail** [comment]
@livarcocc Today, if my app is .NET Core global tool, it needs .NET Core SDK present on the machine in order to install the global tool. I want my app to be .NET Core global tool for easy deployment and easy use, in the meantime, the customer can install it without their machine already has .NET Core SDK installed. I understand that it is not supported now, I hope the submit the request so that the feature can be considered. Based on my understanding per https://docs.microsoft.com/en-us/dotnet/core/deploying/, to achieve what I want today, I need to build and deploy my app in two forms, one is global tool; the other one is as Self-contained deployments (SCD) in case customer doesn't have .NET Core SDK installed. Is that right?

**Comment by peterhuene** [comment]
Hi @Lxiamail.  The only mechanism for installing .NET Core global tool packages is via an installed .NET Core SDK.  There are no other plans for being able to distribute .NET Core global tools.

Your understanding is correct.  Since global tools are typically just console application projects, you may also distribute your global tool as a self-contained deployment which will not require the target computer to have a .NET Core runtime or SDK installed.  However, you would not install the tool via `dotnet tool install`; instead, you would directly run the application host (i.e. executable) created for the self-contained deployment.

**Comment by livarcocc** [comment]
What @peterhuene is absolutely on point. We have talked about extending global tools to global "apps" and make it available with runtime install alone, but that's not something that we can commit to at this point.

**Comment by Lxiamail** [comment]
@livarcocc @peterhuene Thanks to both of your explanation.
