### ISSUE TITLE
Strange versioning of templates dir in preview 8

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#12275]
I downloaded .NET Core 3.0 Preview 8 from https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview8-linux-x64-binaries

It contains a new directory for templates. The versioning of this templates directory is strange: `DOTNET_ROOT/templates/3.0.0-preview8-013656/`. The version number of this directory (3.0.0-preview8-013656) doesn't match the SDK (3.0.100-preview8-013656) or the .NET Core Runtime (3.0.0-preview8-28405-07) or the ASP.NET Core Runtime (3.0.0-preview8.19405.7).

It seems to me that it should be using the SDK version.

## Environment data

This is the download link I used:

https://download.visualstudio.microsoft.com/download/pr/a0e368ac-7161-4bde-a139-1a3ef5a82bbe/439cdbb58950916d3718771c5d986c35/dotnet-sdk-3.0.100-preview8-013656-linux-x64.tar.gz

**Comment by omajid** [comment]
This also affects source-build.

cc @crummel @dleeapho @tmds

**Comment by livarcocc** [comment]
This is by design.

It is a mix of the SDK version with the runtime version.

The runtime version is used because it depicts which runtime it targets and it revs based on the runtime.

The SDK version is used because this asset is produced (aggregated) at the core-sdk repo and we needed a way to rev it for every SDK build.

**Comment by omajid** [comment]
@livarcocc What would this version look like at 3.0 GA? Will it be `3.0.0` or `3.0.100`?

**Comment by livarcocc** [comment]
3.0.0, matching the runtime that it targets.

**Comment by livarcocc** [comment]
cc @johnbeisner

**Comment by omajid** [comment]
Thanks!
