### ISSUE TITLE
exe is not produced when PackAsTool = true

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#12270]
## Steps to reproduce

- Create a new project
- Add `<PackAsTool>true</PackAsTool>`

## Expected  behavior

You get an exe

## Actual behavior

No exe.

## Environment data
3.0 Preview 8

## Commentary

I think of PackAsTool as a publishing choice. Everything about the dev experience should be the same as regular projects until you act on packing the project as a tool.

I understand that there are some challenges here, in that we don't have a good way of not publishing a build asset.

/cc @vitek-karas

**Comment by livarcocc** [comment]
@wli3 can you take a look?

@richlander as exe produced, I imagine you mean during build?

**Comment by wli3** [comment]
Fixed by https://github.com/dotnet/sdk/pull/3505 should be in preview 9. Is that what you expect?

**Comment by richlander** [comment]
That looks like the same thing, so thanks! I'll repro with P9 and tell you if something is wrong.
