### ISSUE TITLE
dotnet tool commands should work offline for local sources

### ISSUE THREAD

**Issue by orcun** [dotnet/cli#12288]
I noticed that sometimes dotnet tool update hangs and realized that was due to connection issues. However I was not expecting this behavior since I was providing a local source.

## Steps to reproduce
Poor wifi connection (or no connection, I haven't tested)
Use a local nupkg folder as source

## Expected  behavior
Operation to work quickly

## Actual behavior
Operation hangs or waits for a long timeout?
I am not sure if this is due to telemetry or it always checks with server. 
If this is due to telemetry, I think timeout should be very short.
If it checks with nuget server even when using a local folder, it should be lower priority.

I think working offline will be a common scenario, especially in CI environments.

## Environment data
I'm using core 3 preview 8.

**Comment by wli3** [comment]
I believe nuget would prefer local source first. Could your run restore with `-v:diag`, make sure there is no sensitive information and post it here?

 @nkolev92 to verify.

**Comment by nkolev92** [comment]
Yup, that's correct. Local sources are preferred over network sources.

**Comment by orcun** [comment]
I am not sure if I can replicate it (poor wifi connection) easily but I will keep it in mind. Perhaps suggesting this to users when some tasks take a long time would be useful.

**Comment by wli3** [comment]
close per no action item (it should work. and no repro for not working)
