### ISSUE TITLE
net core 3 preview9 does not build testhost and other runner files for tests

### ISSUE THREAD

**Issue by julielerman** [dotnet/cli#12287]
## Description
In an Xunit project with recent preview9 SDKs, dotnet build doesn't pull testhost.dll or any other important files for running tests. The result when running tests is that none are discovered. Error reports testhost.dll can't be found. I was experiencing this with previously working test projects but it was easily reproducible with a default test project.

## Steps to reproduce
In an empty folder, at CLI, run
dotnet new xunit  //same problem with dotnet new mstest
dotnet test

## Expected behavior
Dotnet test should run the test and output test run execution log, then
total tests 1 etc
test run successful

bin/debug/netcoreapp3.0 folder should contain many files including testplatform dlls, visualstudio dlls, Xunit dlls and Xunitrunner dlls.

When I switched global.jdon to use a preview6 version, it worked as expected. I don't have preview7 or 8 on this machine to see where it broke (or where there is some change that I missed and should be going about this differently now... ??)

## Actual behavior
Running dotnet test simply returns a command prompt.

Contents of bin/debug/.netcoreapp3.0 folder are:
projectname.deps.json
projectname.dll
projectname.pdb

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview9-013927
 Commit:    e1f793b16d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview9-013927/

Host (useful for support):
  Version: 3.0.0-preview9-19415-13
  Commit:  127d3f10eb

.NET Core SDKs installed:
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.300-rc1-008673 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.2.100-preview2-009404 [/usr/local/share/dotnet/sdk]
  2.2.100-preview3-009430 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.0.100-preview5-011568 [/usr/local/share/dotnet/sdk]
  3.0.100-preview6-012264 [/usr/local/share/dotnet/sdk]
  3.0.100-preview9-013817 [/usr/local/share/dotnet/sdk]
  3.0.100-preview9-013927 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview2-35157 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview2-35157 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19413.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19415.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview2-26905-02 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19415-13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by julielerman** [comment]
boy I need to clean up those old versions. ;)

**Comment by dasMulli** [comment]
off-topic / fyi try https://github.com/dotnet/cli-lab/tree/master/src/dotnet-core-uninstall

```
$ dotnet build -r osx-x64
$ sudo dotnet run --no-build -r osx-x64 -- --sdk --all-lower-patches
$ sudo dotnet run --no-build -r osx-x64 -- --runtime --all-lower-patches
```

**Comment by julielerman** [comment]
oh thanks . will try that. Build works properly with   3.0.100-preview8-013656 FWIW

**Comment by dasMulli** [comment]
I also just tested it on Mac and linux with the latest preview 9 (preview9-013942) and it seems to work on my machine.. trying to find your exact version now.

**Comment by dasMulli** [comment]
I couldn't reproduce this on my Mac and linux docker images with the exact preview9 version you used as well as the latest preview9..
Could also be an environment issue (env vars, Directory.Build.props/targets/rsp files somewhere in the folder hierarchy etc.) - a binary log could help here (`dotnet build -bl` to create `msbuild.binlog` but be aware that it includes full paths and all environment variables - https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b)

**Comment by julielerman** [comment]
really appreciate the validation @dasMulli. I tried SO MANY THINGS :( for hours.... ahh well. I will check nto these ideas when I return later. THANK YOU

**Comment by julielerman** [comment]
I ended up clearing off all of the versions of 3 (sdk & runtime) from my machine and reinstalling the latest daily build. dotnet build on the test projects is now working properly. Thanks for the hints!
