### ISSUE TITLE
dot.net site is down, cannot download https://dot.net/v1/dotnet-install.ps1

### ISSUE THREAD

**Issue by paveliak** [dotnet/cli#12282]
## Steps to reproduce
curl https://dot.net/v1/dotnet-install.ps1

## Expected  behavior
Can download PS file

## Actual behavior
curl: (7) Failed to connect to dot.net port 443: Timed out

## Environment data
`dotnet --info` output:

N/A

Thanks,
Pavel

**Comment by livarcocc** [comment]
We are aware.

cc @rowanmiller

**Comment by rowanmiller** [comment]
Issue is resolved now, everything is back online

**Comment by markwilkie** [comment]
Tracking issue:  https://github.com/dotnet/core-eng/issues/7463
