### ISSUE TITLE
publishing of heterogeneous solution

### ISSUE THREAD

**Issue by shvez** [dotnet/cli#12296]
Hi, there

we have a solution which contains netstandard assemblies and assemblies targeting netcoreapp and .net classic. 
if I publish the solution using netcoreapp for instance, I get errors that some project do not contain netcoreapp target.

would not it be more logical/convenient to publish netstandard assemblies as netstandard because they should work smooth with netcoreapp.  Of course, there could be ambiguous cases but I believe that in most cases it may work well

what do you think?

best,
ilya

**Comment by livarcocc** [comment]
@shvez how are you publishing your solution?

**Comment by shvez** [comment]
@livarcocc dotnet publish sln_file -f netcoreapp2.1 -r win-x64

**Comment by livarcocc** [comment]
This is a known issue because when you pass these options they are treated as global properties and passed to all projects in the solution, which leads to the issue you are running into.

Could you try publishing a particular project instead of a solution? That might unblock you.

**Comment by shvez** [comment]
> Could you try publishing a particular project instead of a solution? That might unblock you.
yes, that is what we do now. 

how do you plan to resolve the issue with solution publishing and when if you plan?

**Comment by livarcocc** [comment]
The earliest we will address this will be 5.0.

**Comment by shvez** [comment]
OMG!
