### ISSUE TITLE
ProjectModelServer - build 1.0.1.001200 does not respond to any socket requests

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#1229]

**Comment by BillHiebert** [comment]
...
 	[Managed to Native Transition]	
>	System.Net.Sockets.dll!System.Net.Sockets.SafeCloseSocket.InnerSafeCloseSocket.Accept(System.Net.Sockets.SafeCloseSocket socketHandle, byte[] socketAddress, ref int socketAddressSize)	Unknown
 	System.Net.Sockets.dll!System.Net.Sockets.SocketPal.Accept(System.Net.Sockets.SafeCloseSocket handle, byte[] buffer, ref int nameLen, out System.Net.Sockets.SafeCloseSocket socket)	Unknown
 	System.Net.Sockets.dll!System.Net.Sockets.Socket.Accept()	Unknown
 	dotnet-projectmodel-server.dll!Microsoft.DotNet.ProjectModel.Server.Program.OpenChannel() Line 93	C#
 	dotnet-projectmodel-server.dll!Microsoft.DotNet.ProjectModel.Server.Program.Main.AnonymousMethod__0() Line 74	C#
 	dotnet-projectmodel-server.dll!Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(string[] args) Line 260	C#
 	dotnet-projectmodel-server.dll!Microsoft.DotNet.ProjectModel.Server.Program.Main(string[] args) Line 77	C#

**Comment by muratg** [comment]
@troydai

**Comment by troydai** [comment]
I’m investigating this.

**Comment by troydai** [comment]
Fixed in 78a7f6d8d1d1d7d793cfe89cd94767a5ba97fab7
