### ISSUE TITLE
corehost spec deleted but still referenced

### ISSUE THREAD

**Issue by idg10** [dotnet/cli#12299]
## Steps to reproduce

1. Go to https://github.com/dotnet/cli/blob/master/Documentation/README.md
2. Look in **Specifications** section
3. Click on the **Corehost specification** entry

## Expected  behavior

Either: the Corehost specification should load, or: there should be no **Corehost specification** entry in that list.

## Actual behavior

GitHub's 404 page shows because that document does not exist.

## Environment data
This is a documentation issue in this repo, so there is no environment per se. The problem is visible currently on `master`, and at the tag `v3.0.100-preview8.19406.4`

## Notes

The `corehost.md` file was deleted by https://github.com/dotnet/core-setup/pull/5156 (and although there are two commits in there, one deleting this, and one affecting another file, GitHub shows the overall effect of the PR to be only deleting this file).

@vitek-karas noted that the contents of the document were no longer accurate, so I guess removing the reference from the readme is the right thing to do? But this does raise the question: where is the relevant information now documented? This file used to document the Assembly Resolution process. (I was looking for detail on this when I discovered that this file had been deleted.) There seem to be significant differences between .NET Fx and Core here, and it's not clear that the docs in, say, https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfrom?view=netcore-3.0 actually apply in .NET Core.

(In particular, that says that the load-from context "allows dependencies on that path to be found and loaded because the path information is maintained by the context". As far as I can tell, using `Assembly.LoadFrom` in .NET Core 3.0 to load a DLL from somewhere other than the app folder does not enable dependencies to be picked up from that same folder. I think you need to use an `AssemblyLoadContext`, and that there's no reliable way to do this in .NET Standard 2.0 that will work on both .NET Core and .NET Framework, but I've not managed to find definitive documentation for exactly how .NET Core's assembly resolution process is different from .NET Framework's.)

**Comment by vitek-karas** [comment]
Thanks for spotting this. I created #12301 to remove the stale link.

As noted in the removal, almost all of that information is no longer true, or at the very least it's misleading. There are newer docs in the core-setup repo which describe parts of the problem space, for example: https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/host-components.md and https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/host-probing.md.,

The assembly loading as a whole is now being document in this PR (not yet merged though): https://github.com/dotnet/docs/pull/13799. Should go to the main docs soon enough.

Regarding the `Assembly.LoadFrom`  it should resolve dependencies from the same folder. If you're seeing different behavior, could you please file a separate issue for that in dotnet/coreclr? Ideally with a repro, or please provide a bit more details on what you're trying to do, and how it doesn't work the way you would expects it to.
