### ISSUE TITLE
Dotnet build failed after targeting a web project's(mvc/web/webapi) framework from 3.0 to 2.x

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#12300]
## Steps to reproduce
1. Install d16.3 and enable dotnet core 3.0 (3.0.100-preview8-013656 is installed)
2. Install 2.x runtime
3. Create a webapp (targeting 3.0 by default)
4.  Retargeting to 2.1 or 2.2 by edit .csproj file
5. dotnet build

## Expected  behavior
1. This project could be run normally.

## Actual behavior
1. Dotnet build failed with below message
C:\Users\v-zhuqin\myweb30>dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19377-01+dd8019d9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 137.69 ms for C:\Users\v-zhuqin\myweb30\myweb30.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
Pages\Error.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(6,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(9,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(10,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(11,33): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(11,31): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(13,31): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(19,23): error CS0246: The type or namespace name 'IHostBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(13,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(15,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(21,16): error CS0246: The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(24,39): error CS0246: The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(30,31): error CS0246: The type or namespace name 'IApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(30,56): error CS0246: The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(16,24): error CS0246: The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(13,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(15,29): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,6): error CS0246: The type or namespace name 'ResponseCacheAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,6): error CS0246: The type or namespace name 'ResponseCache' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,20): error CS0246: The type or namespace name 'Duration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,34): error CS0246: The type or namespace name 'Location' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,45): error CS0103: The name 'ResponseCacheLocation' does not exist in the current context [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,73): error CS0246: The type or namespace name 'NoStore' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(19,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(21,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]

Build FAILED.

Pages\Error.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(6,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(7,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(5,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(6,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(7,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(8,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(9,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(10,17): error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(11,33): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(11,31): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(13,31): error CS0246: The type or namespace name 'PageModel' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Program.cs(19,23): error CS0246: The type or namespace name 'IHostBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(13,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Index.cshtml.cs(15,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(21,16): error CS0246: The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(24,39): error CS0246: The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(30,31): error CS0246: The type or namespace name 'IApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(30,56): error CS0246: The type or namespace name 'IWebHostEnvironment' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Startup.cs(16,24): error CS0246: The type or namespace name 'IConfiguration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(13,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Privacy.cshtml.cs(15,29): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,6): error CS0246: The type or namespace name 'ResponseCacheAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,6): error CS0246: The type or namespace name 'ResponseCache' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,20): error CS0246: The type or namespace name 'Duration' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,34): error CS0246: The type or namespace name 'Location' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,45): error CS0103: The name 'ResponseCacheLocation' does not exist in the current context [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(12,73): error CS0246: The type or namespace name 'NoStore' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(19,26): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
Pages\Error.cshtml.cs(21,27): error CS0246: The type or namespace name 'ILogger<>' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\v-zhuqin\myweb30\myweb30.csproj]
    0 Warning(s)
40 Error(s)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
Version:   3.0.100-preview8-013656
Commit:    8bf06ffc8d

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.17763
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by richaverma1** [comment]
@yuki233 did you enable .NET Core 2.1 and/or 2.2 from the installer?

**Comment by livarcocc** [comment]
This is not supported. Things have moved around in 3.0 and simply re-targeting the TFM will not be enough to get your project working again in 2.1/2.2.
