### ISSUE TITLE
[Question] How to publish solution to a custom output folder?

### ISSUE THREAD

**Issue by xenalite** [dotnet/cli#12304]
I run `dotnet publish name.sln`. The solution contains project X and Y.
I want the publish output to go to: `C:\sample\X` for project X and `C:\sample\Y` for project Y.
I do not want to run `dotnet publish` for each project (rather than solution), because there may be more projects added in the future.

**Comment by livarcocc** [comment]
I am not sure this is possible today.

@dsplaisted any ideas?

**Comment by dsplaisted** [comment]
`dotnet publish` should work on a solution.  If you want to redirect the output to a different path, you can't do that entirely via the command line.  You can put something like the following in a [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) file in your solution directory to customize the different output folders:

```xml
<Project>
  <PropertyGroup>
    <RootOutputPath>$(MSBuildThisFileDirectory)</RootOutputPath>
    <BaseOutputPath>$(RootOutputPath)$(MSBuildProjectName)\bin</BaseOutputPath>
    <BaseIntermediateOutputPath>$(RootOutputPath)$(MSBuildProjectName)\obj</BaseIntermediateOutputPath>
    <PublishDir>$(RootOutputPath)$(MSBuildProjectName)\publish</PublishDir>
  </PropertyGroup>
</Project>
```

**Comment by xenalite** [comment]
@dsplaisted Thanks. I used this in `Directory.Build.props` file and worked fine.
```
<Project>
  <PropertyGroup>
    <PublishDir>$(RootOutputPath)$(MSBuildProjectName)\publish</PublishDir>
  </PropertyGroup>
</Project>
```
