### ISSUE TITLE
[bug] dotnet build repeats executable extension

### ISSUE THREAD

**Issue by TheButlah** [dotnet/cli#12318]
## Steps to reproduce
1. `mkdir dotnet-bug`
2. `cd dotnet-bug`
3. `dotnet new console`
4. add `<AssemblyName>dotnet-bug.client</AssemblyName>` into `<PropertyGroup>`
5. run `dotnet build dotnet-bug.csproj -r linux-x64`

## Expected  behavior
Should see an executable named `dotnet-bug.client` in `bin/Debug/netcoreapp2.2/linux-x64/`

## Actual behavior
Instead, the extension of the executable is duplicated: `bin/Debug/netcoreapp2.2/linux-x64/dotnet-bug.client.client`

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
## Additional Notes:
This occurs for (at least) RIDs `linux-x64`, `osx-x64`, but does not occur for `win-x64`, as in the latter case, the executable is named `dotnet-bug.client.exe` as would be expected behavior

**Comment by livarcocc** [comment]
We might have a bug for this already. I will try to find it later.

**Comment by peterhuene** [comment]
I believe this was fixed in 3.0, but I can't seem to find the tracking issue.  It does not repro with SDK `3.0.0-preview9-19419-03`.

**Comment by livarcocc** [comment]
I thought so as well.

@TheButlah can you try that with the latest 3.0 preview9 build and see if this repros for you?

**Comment by TheButlah** [comment]
Can I still target .net core 2.2 with that? Sorry I'm new to this whole ecosystem

**Comment by livarcocc** [comment]
@TheButlah yes. You can use the latest SDK to target all TFMs that came before it. So, 3.0, can target 2.2, 2.1, 2.0, 1.1 and 1.0.

**Comment by TheButlah** [comment]
Yep, the following version no longer has the bug:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013656
 Commit:    8bf06ffc8d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100-preview8-013656/

Host (useful for support):
  Version: 3.0.0-preview8-28405-07
  Commit:  d01b2fb7bc

.NET Core SDKs installed:
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.0.100-preview8-013656 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
