### ISSUE TITLE
Update Json.NET version to 8.0.2

### ISSUE THREAD

**Issue by Eilon** [dotnet/cli#1233]
E.g. here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/project.json

Ultimately almost every ASP.NET Core project will use Json.NET 8.0.2 anyway so having a new version here will avoid nasty binding redirects and other shenanigans.

This version also has a lot of new features and enhancements that could be used, such as support for buffer pooling (not sure how much it's useful in here, though).

**Comment by blackdwarf** [comment]
@piotrpMSFT @davidfowl  thoughts on this?

**Comment by piotrpMSFT** [comment]
:+1:

**Comment by JamesNK** [comment]
FYI you can close this issue. CLI is already using 9.0.1
