### ISSUE TITLE
dotnet build Doesn't copy ilasm.exe to app output folder after switching from netstandard1.3 to 2.0

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/cli#12341]
## Steps to reproduce
1. consoleapp3  references to a classlib1 project.
2. consoleapp3  also packagereference to Microsoft.NETCore.ILAsm (`<PackageReference Include="Microsoft.NETCore.ILAsm" Version="2.0.5" />`)
3. classlib1's TargetFramework is netstandard1.3
4. "dotnet build  ConsoleApp3.sln" to build the solution, ilasm.exe is copied to bin/debug output dir of consoleapp3 as expected.
5. change classlib1's TargetFramework from netstandard1.3 to netstandard2.0
6. build solution again, ilasm.exe is missing in bin/debug output dir of consoleapp3.
repro program is at https://github.com/Lxiamail/ilasmpackagerefrepo

## Expected  behavior
expect ilasm,exe is copied to bin/debug output dir of consoleapp3.

## Actual behavior
ilasm.exe is missing in bin/debug output dir of consoleapp3.

## Environment data
`dotnet --info` output:
C:\Users\alicial\source\repos\ConsoleApp3>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by dsplaisted** [comment]
I think this was fixed in the .NET Core 3.0 SDK with https://github.com/dotnet/sdk/pull/3406.

If you need to work around the issue, you can do so by referencing the `Microsoft.NETCore.Platforms` NuGet package for the project targeting .NET Framework.

**Comment by Lxiamail** [comment]
@dsplaisted Thanks!

**Comment by livarcocc** [comment]
Seems like this is addressed. Going to close this issue.
