### ISSUE TITLE
Potential Bug in the way to detect for docker environment

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/cli#12340]
## Steps to reproduce
Use this Environment -> CentOS docker on RHEL7 host

## Expected  behavior
for `docker run --rm centos:centos7 /bin/sh -c 'if grep -q /docker/ "/proc/1/cgroup"; then echo "yes"; fi'` to stdout `yes` but in reality it fails as there is no trailing `/` in the cgroup file for docker on rhel7. In reality it passes with `/docker-` as the check. 

## Actual behavior
The [logic](https://github.com/dotnet/cli/blob/master/src/dotnet/Telemetry/DockerContainerDetectorForTelemetry.cs#L44-L50) fails when host is RHEL7 for the docker 

## Potential fix
Use `"/docker/" OR "/docker-"` instead of `"/docker/"`

**Comment by livarcocc** [comment]
@adaggarwal can you help me understand why do you believe this is a .NET Core CLI issue?

**Comment by adaggarwal** [comment]
I just believe that given that someone is using rhel7 host and if the intention is to detect docker environment, this may fail. I had something similar in source-build for running coreFX tests which failed in my local environment. So I thought it may be a good idea to open to give a heads up here as well.
