### ISSUE TITLE
-->VS 2019 nice to have version control  install

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/cli#12354]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/475347/-vs-2019-nice-to-have-version-control-install.html)._

---
In VS 2017 when loading project if you were missing a framework the VS message box would appear notifying you of this, allowing you to download 
required Framework.
would be nice to have simular situation for SDK reports the error but doesnot allow you to select a different version or download required version

--&gt;VS 2019
Error
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

---
#### Jane Wu [MSFT] on 3/4/2019, 02:44 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by timheuer** [comment]
Can be closed...triaged to this path in error.
