### ISSUE TITLE
dotnet test needs to accept a configuration parameter

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1237]
Otherwise, if we build a project using the configuration parameter and setting it to release, when we try to run the tests by doing dotnet test, it won't find the binaries for the test project, as it always looks for it under debug\tfm.

**Comment by blackdwarf** [comment]
@livarcocc wouldn't it be better to try the well known configurations and then fail if none is found?

**Comment by livarcocc** [comment]
Fixed with https://github.com/dotnet/cli/pull/1253.
