### ISSUE TITLE
 [loc][Query][cli] Localizability of "0; "ToolInstallationFailedWithRestoreGuidance

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#12422]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
Tool '{0}' failed to install. This failure may have been caused by:\r\n\r\n* You are attempting to install a preview release and did not use the --version option to specify the version.\r\n* A package by this name was found, but it was not a .NET Core tool.\r\n* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.\r\n* You mistyped the name of the tool.\r\n\r\nFor more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

File Name:
dotnet\commands\dotnet-tool\install\xlf\LocalizableStrings.xlf

==========================================
Query:
Please explain the meaning of "package naming enforcement".

**Comment by peterhuene** [comment]
Hi @PDostalek.

Sorry for the late reply as I've been on vacation.

@wli3 what would be a good explanation of this text?  "Package naming requirement"?

**Comment by wli3** [comment]
cc @KathleenDollard 
package naming enforcement -- we reference to the policy (not yet implemented) all Microsoft first party global tools package name need to have prefix "microsoft." (_dotnet-mytool_ vs _microsoft.dotnet-mytool_)

**Comment by KathleenDollard** [comment]
OK, now I hate that we are saying that. Will, if no one knows what that means except us, what is the point of saying more than:

> For more reasons this may have occurred, visit https://aka.ms/failure-installing-tool

I know, making text changes in localization is terribly late.
