### ISSUE TITLE
Please add command option --sln to build one single sln file

### ISSUE THREAD

**Issue by Thaina** [dotnet/cli#12433]
For the most part, where we want to write script for autobuild or build the default solution. We might have many proj file in the same folder. So I think we should have some option to infer the single solution without specifying its name

I think we should have `dotnet build --sln` option available. It would find the single sln in the root folder. And still throw `MSB1011` if there is multiple sln file

Alternatively please allow wildcard on the build path option

**Comment by livarcocc** [comment]
Wildcard is not directly implemented by the CLI. It is dependent on the shell that you are using. For instance, on bash, it works without a problem.

I don't believe this is something we will get to and as such I am going to close this issue.

This command work for me on bash though: `dotnet build *.sln` where I had also created a couple of csproj files in the same folder.
