### ISSUE TITLE
Command to bake project.json referenced versions

### ISSUE THREAD

**Issue by benaadams** [dotnet/cli#1245]
A command to convert library references in project.json to current referenced version would be super useful.

e.g. 
Say project.json is referring to packages as:
`"System.Threading": "4.0.11-*"`
It would be nice to be able to run a command that would turn these into the current referenced version
`"System.Threading": "4.0.11-rc2-23728"`

Then you could do dev on latest and create checkpoint builds/versions on the current version so its easy to go back to them.

**Comment by GuardRex** [comment]
> current referenced version

There could be a switch added for (1) whatever resolved into `project.lock.json` tossed back into `project.json`, and (2) latest/highest feed version available.

I :+1: this idea. The longer these dependencies lists get, the more of a pain it is to lock them into a set from `*` references manually.

**Comment by cnblogs-dudu** [comment]
:+1:

**Comment by herecydev** [comment]
:+1: Sounds like a great idea

**Comment by blackdwarf** [comment]
@benaadams we do have the extensibilty support, maybe this could be an additional command that users can pull down if they need? Seems like something that would fit nicely into that scenario.

**Comment by benaadams** [comment]
@blackdwarf quite possibility. 

Caught me out post Core rename as not every package renamed and I was using `1.0.0-*` versions and didn't know what the previous version I referenced was (only .lock file knew it, which wasn't under source control); so was forced to migrate (was just trying to make a small patch).

Wasn't an issue, more a warning :)

**Comment by livarcocc** [comment]
I don't believe this is something that we would do natively in the CLI. I believe the idea of an extension to do this is the right way to go.

Closing the issue here.
