### ISSUE TITLE
Preview version message should not appear when build project with .Net Core 3.0 GA

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#12488]
## Steps to reproduce
1. Install .NET core SDK 3.0.100-rc1-014183(Use release/3.0.1XX branch from https://github.com/dotnet/core-sdk)
2. Run `dotnet new console -o csapp02` via CLI
3. Run `dotnet build` to observe the result

## Expected  behavior
Dotnet build works fine, the preview version message does not appear.

## Actual behavior
It shows that: _`You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview`_
![image](https://user-images.githubusercontent.com/33921754/64316620-eea9a100-cfe7-11e9-8bee-7e5a53598896.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc1-014183
 Commit:    298e4dcf34

 

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-rc1-014183\

 

Host (useful for support):
  Version: 3.0.0-rc1-19454-17
  Commit:  b2d71fc324

 

.NET Core SDKs installed:
  3.0.100-rc1-014183 [C:\Program Files\dotnet\sdk]

 

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-rc1.19453.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19454-17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19454-17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This is still a preview version, although versioned rc1 instead of previewX. It won't show the message when it is final branded, without any suffix in the version.
