### ISSUE TITLE
How to pass parametrized tests into filter for dotnet test?

### ISSUE THREAD

**Issue by OlegYanushkevich** [dotnet/cli#12493]
How I can pass parameterized tests into filter for dotnet test command?

I tried something like:

```dotnet test --filter 'FullyQualifiedName=QAutomation.Tests.NUnit.Fixture.Test2("first",3,4)'```

and

```dotnet test --filter 'FullyQualifiedName=QAutomation.Tests.NUnit.Fixture.Test2\("first",3,4\)'```

but it doesn't work.

I have parameterized tests:

```csharp
 [Test]
 [TestCase("first", 3, 4)]
 [TestCase("second", 1, 5)]
 public void Test(string s, int a, int b)
 {
     Assert.Fail("Fail");
 }
```

**Comment by peterhuene** [comment]
@mayankbansal018 would you know the answer to this question?

**Comment by OlegYanushkevich** [comment]
Found similar question in [doc repository](https://github.com/dotnet/docs/issues/13963), but any answers.

**Comment by mayankbansal018** [comment]
@OlegYanushkevich can you please check https://github.com/microsoft/vstest-docs/blob/master/docs/filter.md, see if that helps. It's possible FQN is not supported by NUnit. If that's the case you will have to follow with NUnit team for that.

**Comment by livarcocc** [comment]
Closing as this does not seem like a CLI issue and there is a follow up issue on NUnit.
