### ISSUE TITLE
Refactor test layout

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#1250]

**Comment by Sridhar-MS** [comment]
The layout of test resources for CLI will be moved to this layout:

```
/%REPOROOT%
|--- /src
        |---/TestFramework
|--- /assets
        |--- /TestProjects
        |--- /TestPackages
|--- /test
        |--- /{commandName}.Tests
        |--- /{libraryName}.Tests
        |--- /Installer
                 |--- /Deb
                 |--- /MSI         
        |--- /EndToEnd
```

**Comment by blackdwarf** [comment]
@Sridhar-MS @eerhardt is this work done? Can this issue be closed?

**Comment by eerhardt** [comment]
The following tests still need to be renamed/moved as appropriate:

- ArgumentForwardingTests
- ArgumentsReflector
- ScriptExecutorTests

But I think that's the only thing left.

**Comment by davidfowl** [comment]
There's also this `https://github.com/dotnet/cli/tree/rel/1.0.0/testapp` that needs to be deleted /cc @troydai

**Comment by troydai** [comment]
It can be moved, but there are projects under `testapp` will fail the `dotnet restore` intentionally. Make sure it doesn't break build script.
