### ISSUE TITLE
dotnet run silently exits if there are build issues

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#1255]
Simple repro: OS X, Mono. Create a syntax error in your code (remove a `;`) and do `dotnet run`.

Expected: Error is displayed 
Result: Dotnet run silently exits

You can see the error(s) if you do `dotnet build` yourself.

**Comment by blackdwarf** [comment]
@muratg I cannot repro this on 1.0.0-beta-001511 on OSX. Can you check to see if newest are reproing this?

**Comment by muratg** [comment]
@blackdwarf Yeah, it looks like all the build output is displayed now so the original issue seems to be fixed.

However, now simple Hello World output with `dotnet run` is like:

```
murats-mbp% dotnet run
Compiling app2 for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3149188


Hello World!
```
or
```
murats-mbp% dotnet run
Project app2 (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Hello World!
```

**Comment by livarcocc** [comment]
Closing since the original issue has been fixed.
