### ISSUE TITLE
dotnet-install.sh not installing the latest SDK version

### ISSUE THREAD

**Issue by natenho** [dotnet/cli#12571]
## Steps to reproduce

```console
[root@centos-181 ~]# ./dotnet-install.sh
dotnet_install: Warning: Unable to locate libunwind. Probable prerequisite missing; install libunwind.
dotnet_install: Warning: Unable to locate libicu. Probable prerequisite missing; install libicu.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.701/dotnet-sdk-2.1.701-linux-x64.tar.gz
```

## Expected  behavior
To install the latest SDK version (2.2)

## Actual behavior
It's installing 2.1.701 version

Original issue: https://github.com/dotnet/docs/issues/10447

**Comment by johnbeisner** [comment]
@natenho 
2.1.701 is indeed the latest LTS version - with no parameters the default 'channel' is LTS; try this:
`./dotnet-install.sh --channel current`
that should get you version: 2.2.301

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#options

**Comment by johnbeisner** [comment]
closing issue...
