### ISSUE TITLE
Do I need to rebuild/redeploy app with every new SDK version (vs update only runtime on host)?

### ISSUE THREAD

**Issue by greenmooseSE** [dotnet/cli#12628]
Hi.

I am wondering how the SDK version vs Runtime version work, related to building an application.
For example, on https://dotnet.microsoft.com/download/dotnet-core/2.1 there are 3 SDK releases (```2.1.509```, ```2.1.606``` and ```2.1.802```) for same runtime version ```2.1.13```. and e.g. 4 SDK versions for runtime ```2.1.12```

Given I am not deploying self-contained applications:
In order to utilize the latest security patches, do I need to rebuild the application with the latest SDK every time it is released, as well as updating the runtime (e.g. ```2.1.12``` => ```2.1.13``` on the host? Or is the SDK versions just different "tooling" versions and my app is safe as long as the runtime is updated on the host environment no matter which SDK it was built with?

Thanks.

**Comment by livarcocc** [comment]
No.

If you are using a Framework Dependent App (FDD), it is always built targeting the lowest possible patch version for that major.minor. This guarantees that the app runs against as many runtimes as possible.

When the app is getting started, the host will find the latest patch version of that major.minor runtime installed in the machine and use that runtime to run your app.

In order for you FDD app to run against the latest runtime, you just need to have it installed in the machine.
