### ISSUE TITLE
https://dot.net/v1/dotnet-install.ps1  does not support `windowsdesktop` `Runtime` 

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/cli#12635]
Support for `windowsdesktop` `Runtime` was added by https://github.com/dotnet/cli/pull/12315 and the website download copy was (I think) updated by https://github.com/dotnet/dotnet-core-website/pull/1458. 

Still, it looks like the copy of dotnet-install.ps1 hosted at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script is the one that seems to be a version prior to when windowsdesktop support was added.

/cc @johnbeisner, @dagood

**Comment by johnbeisner** [comment]
@vatsan-madhavan 
The install-scripts with this feature was recently promoted to: https://dot.net/v1/dotnet-install.ps1
PR: https://github.com/dotnet/dotnet-core-website/pull/1508

Closing...
