### ISSUE TITLE
Which dotnet/cli tag to use to build the cli for .NET 2.1.13

### ISSUE THREAD

**Issue by assyadh** [dotnet/cli#12633]
Hi,

I am seeing 3 different tags for the .NET Cli for the 2.1.13 release:

v2.1.802+dependencies
v2.1.606+dependencies
v2.1.509+dependencies

I am trying to build the CLI that is released with 2.1.13, but I see three different binaries here as well for 2.1.13:

https://dotnet.microsoft.com/download/dotnet-core/2.1

Should I just build the latest one? What is the reasoning behind the three different versions?

Thanks.

H.

**Comment by livarcocc** [comment]
2.1.13 is not a CLI version, it is a runtime version.

It will depend on what version of the CLI you want. All three of the above will carry with it the 2.1.13 runtime.

2.1.509 targets VS 15.9
2.1.606 targets VS 16.0
2.1.802 targets VS 16.2
