### ISSUE TITLE
Unable to download latest SDK 2.2

### ISSUE THREAD

**Issue by PatrickReddy** [dotnet/cli#12632]
## Steps to reproduce
Running the following step in our builds fails due to the "latest" available package not being correct.  From the git repo the version should  be 2.2.402 not 2.2.804.

.\dotnet-install.ps1 -Channel 2.2 -Version latest -Architecture x64

Explicitly adding -Version "2.2.402" does download the sdk.

## Expected  behavior
The correct latest package should be retrieved and downloaded

## Actual behavior
The install script is using version 2.2.804...

=== Install DotNet SDK ===

dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.802/dotnet-sdk-2.2.802-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.802/dotnet-sdk-2.2.802-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.802/dotnet-dev-win-x64.2.2.802.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.802/dotnet-dev-win-x64.2.2.802.zip
powershell.exe : Could not find/download: ".NET Core SDK" with version = 2.2.802

**Comment by forki** [comment]
also link is broken.

![image](https://user-images.githubusercontent.com/57396/64940345-07c21580-d864-11e9-81e7-a3e6a3627cf6.png)

**Comment by johnbeisner** [comment]
@PatrickReddy 
Thank you for telling us about this. The download version has been repaired from 2.2.802 to 2.2.402 for the 2.2 channel.

**Comment by johnbeisner** [comment]
@leecow can you check the downloads page.

**Comment by leecow** [comment]
URL updated

**Comment by johnbeisner** [comment]
Verified the install script download succeeds:
`./dotnet-install.ps1 -Channel 2.2`
