### ISSUE TITLE
dotnet build produces different output in bin folder with latest sdk

### ISSUE THREAD

**Issue by ovebastiansen** [dotnet/cli#12654]
## Steps to reproduce
Pin sdk with global.json
dotnet new webapi -f netcoreapp2.2
Build with sdk 2.2.401 and 3.0.100-preview9-014004
dotnet build and look at bin\debug\netcoreapp2.2 with different value for sdk in global.json

## Expected  behavior
*.json is not copied out to output folder, unless CopyToOutputDirectory is preservenewest or copyalways
only copied to output when using dotnet publish

## Actual behavior
appsettings.json and properties\launchsettings.json is copied to bin folder in 3.0.100-preview9-014004 and not in 2.2.401
dotnet publish with 2.2.401 copies the appsettings.json to outputfolder, as expected
dotnet publish with 3.0.100-preview9-014004 copied the appsettings.json but not the launchsettings to output
![image](https://user-images.githubusercontent.com/17083905/64922654-f2041000-d7d1-11e9-9395-e71b24bebf72.png)
![image](https://user-images.githubusercontent.com/17083905/64922668-16f88300-d7d2-11e9-8c69-cc7e16c26809.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.401\

Host (useful for support):
  Version: 3.0.0-preview9-19423-09
  Commit:  2be172345a

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by livarcocc** [comment]
@vijayrkn was this a change in the web sdk?

**Comment by vijayrkn** [comment]
This was an intentional change made by @davidfowl in WebSdk - https://github.com/aspnet/websdk/commit/7e6b193ddcf1eec5c0a88a9748c626775555273e#diff-edf5a48ed0d4aa5a4289cb857bf46a04

But since then we have moved all the ASP.NET Core specific globs to Razor Sdk 
https://github.com/aspnet/AspNetCore-Tooling/blob/master/src/Razor/src/Microsoft.NET.Sdk.Razor/Sdk/Sdk.Razor.StaticAssets.ProjectSystem.props

**Comment by livarcocc** [comment]
Closing this issue since this was intentional.
