### ISSUE TITLE
Tool restore uses current directory to find projects

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1266]
If you run `dotnet restore src` while you're in the root of the repo, NuGet does constrain it's restore to `src`. However, the follow-up tools restore will scan through the entire repo (because it uses the current directory). This is bad :(

The offending line: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore/Program.cs#L86

/cc @piotrpMSFT

**Comment by livarcocc** [comment]
I believe this is the cause for https://github.com/dotnet/cli/issues/1184. I intend to take a look at it.

**Comment by blackdwarf** [comment]
@livarcocc @anurse is this something that we want to put in for RTM? Or before?

**Comment by livarcocc** [comment]
RTM should be fine, in my opinion.

**Comment by piotrpMSFT** [comment]
tool restore is being moved into NuGet itself. I expect it will then behave much more like what we'd expect from NuGet.

**Comment by piotrpMSFT** [comment]
tools restore is now in NuGet
