### ISSUE TITLE
Can I customize the publish self-contained runtimes path？

### ISSUE THREAD

**Issue by xianyun666** [dotnet/cli#12675]
At present, after publish self-contained, exe sibling directory, generate a lot of dll files and folders, 

such as System.Net.dll, api-ms-won-core-console-l1-1-0.dll, vcruntime140_cor3.dll, etc.
**It's such a mess.**
It is best to publish with a parameter that separates exe from the runtimes directory, 
such as `dotnet publish --self-contained --runtime-packs myruntimes`?
runtime-packs parameter supports absolute and relative paths.

**Comment by livarcocc** [comment]
This is not currently supported and we don't have plans to add support for this at the moment.

Please check on Single file exe publishing, which would generate a single exe as the output for you application. You can use it by setting `PublishSingleFile to true` in your project or through the command line.

This maybe be cleaner for you.
