### ISSUE TITLE
dotnet test is not failing when we fail to run the test because of missing deps file

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1267]
Right now, this is easy to repro, just build your project for release and then run the run the dotnet test.

The test will fail with a message of can't find deps file, but it won't exit with 1 and no xml file will get generated.

I suspect this may be an issue with corehost, it should fail and I suspect it is blissfully passing and returning 0.

cc @schellap @brthor @piotrpMSFT

**Comment by blackdwarf** [comment]
@brthor @livarcocc is this still reproing?

**Comment by schellap** [comment]
In the old corehost model, not having deps file is not an error because the host will try to load whatever is available app local.

**Comment by blackdwarf** [comment]
@schellap what about in the "new" corehost model?

**Comment by livarcocc** [comment]
This seems to be working now. I get the dotnet test command to fail in such a situation.
