### ISSUE TITLE
Help URL for failed dotnet tool installation pointing to wrong page

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/cli#12680]
## Steps to reproduce

When tried to install a wrong version of tool (dotnet-sos in this case) or when the tool unable to find the relevant version of the tool, it errors out with detailed information. However, the [URL ](https://aka.ms/failure-installing-tool)that spits out is pointing to Microsoft Docs [main page](https://docs.microsoft.com/en-us/) instead to the actual tool failure assistance page.

Remember, today the RC2 tool is not there yet so the error happens. Once Rc2 or RTM too chain is up for consumption, you may not see the error but the Issue here is about the URL in the error message.

- Open a Command Window
- Execute dotnet tool install -g dotnet-sos --version 3.0.100-rc2-014234
- Check the error message for the URL.

## Expected  behavior
The [help URL](https://aka.ms/failure-installing-tool) should point to the tooling doc page

## Actual behavior

Help URL pointing to the Docs [main page](https://docs.microsoft.com/en-us/).

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-rc2-014234
 Commit:    118e4306cb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-rc2-014234\

Host (useful for support):
  Version: 3.0.0-rc2-19460-02
  Commit:  4421cfb105

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100-rc2-014234 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc2.19460.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc2-19460-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc2-19460-02 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
@wli3

**Comment by wli3** [comment]
Thank you for the issue. The help documentation is still work in process https://github.com/dotnet/cli/issues/12004 cc @KathleenDollard
