### ISSUE TITLE
CommandResolver is using Constants.DefaultConfiguration when resolving from project.json

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1268]
CommandResolver is using Constants.DefaultConfiguration when resolving from project.json

This causes the issue "Unable to locate deps file" when using `dotnet test` on a project built with `dotnet build -c Release`

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolver.cs#L72

cc @piotrpMSFT @livarcocc

**Comment by piotrpMSFT** [comment]
We've been meaning to look at CommandResolver for some time. I like that we're getting this unblocked, but let's see if we can find some way to simplify the interface... it's turning into a grab bag of parameters.
