### ISSUE TITLE
Please publish SDK 3.0.100+dependencies

### ISSUE THREAD

**Issue by Zanadar** [dotnet/cli#12692]
Hello! 
Very excited about this new release. Congrats!
When you get a chance can we get a `+dependencies` release, please? 
Thanks you.

**Comment by livarcocc** [comment]
3.0.100 does not need the +dependencies.

It is built at the HEAD of the repo. Go to dotnet/core-sdk and use the 3.0.100 tag.

**Comment by Zanadar** [comment]
Thanks!
