### ISSUE TITLE
dotnet tools and runtime versions

### ISSUE THREAD

**Issue by RobSwDev** [dotnet/cli#12693]
## Steps to reproduce
We are using sgen to generate Xml Serialization assemblies. We've started to use the dotnet tool [microsoft.xmlserializer.generator](https://www.nuget.org/packages/Microsoft.XmlSerializer.Generator/2.1.0).  This worked initially. However, after installing net core 3.0, it stopped working on some machines, while continuing to work on others.

The issue *seems* to be this:
The tool asks for runtime 2.1.0
If that runtime does not exist, it will roll forward to the first available 2.1.x or 2.2.x
However, once we installed net core 3 sdk, the "roll forward" behaviour is disabled. 
After this, it seems to choose the lowest 2.x.

On my machine, my earliest 2.x is 2.1.6, which works.
On other build machines that have runtime 2.0.9, it fails.
I can get it to work on these machines by removing the 2.0.9 runtime, so that the lowest 2.x is > 2.1.

The tool fails with
`Method 'System.Xml.Serialization.XmlSerializer.GenerateSerializer' was not found. This is likely because you are using an older version of the framework. Please update to .NET Core v2.1 or later.`

Output from the tool diagnostics:
```
PackagedCommandSpecFactory: Looking for prefercliruntime file at `C:\Users\user\.nuget\packages\microsoft.xmlserializer.generator\2.1.0\lib\netstandard2.0\..\..\prefercliruntime`
PackagedCommandSpecFactory: Ignoring prefercliruntime file as the tool target framework (2.0.0) has a different major version than the current CLI runtime (3.0.0-preview8-28405-07)

```

**Comment by RobSwDev** [comment]
One obvious question: Why is the tool target framework 2.0.0, when it clearly requires at least 2.1.0?

But also, I'd like to understand why installing dotnet 3.0 caused/uncovered the problems it did.

**Comment by livarcocc** [comment]
Regarding why the tool targets the TFM it targets, you would have to check with the authors of the tool. It was not created by us on this repo.

As to why installing 3.0 changed it, it is because 3.0 changed the roll forward policies for apps. You can read more about it in the 3.0 announcement blog post: https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/. Look for .NET Core runtime roll-forward policy update
