### ISSUE TITLE
`Project cannot be packaged` warning even when `<IsPackable>true</IsPackable>` in project file has defined

### ISSUE THREAD

**Issue by javadparvaresh** [dotnet/cli#12695]
## Steps to reproduce
I have a `netcoreapp2.2` project which i'm trying to build by using `dotnet (3.0.100)` getting the `warning` for `warning : This project cannot be packaged because packaging has been disabled. Add <IsPackable>true</IsPackable> to the project file to enable producing a package from this project.`

## Expected  behavior
Ignore projects which has defined `<IsPackable>true</IsPackable>`.

## Actual behavior
Now cli prints out a warning which should not.

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.105 [/usr/share/dotnet/sdk]
  2.1.503 [/usr/share/dotnet/sdk]
  2.2.103 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
What is your project like? Could you share you csproj? Could you share a small repro repo on github we could use to try the issue?

**Comment by javadparvaresh** [comment]
sure, 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <PackageId></PackageId>
    <Description></Description>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <Import Project="./../../project.props" />
....
```

and `project.props file includes 
```
 <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Label="Compilation">
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn></NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <PropertyGroup Label="Debug signing" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DelaySign>false</DelaySign>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <PropertyGroup Label="Release Signing" Condition="'$(Configuration)|$(Platform)'=='Relase|AnyCPU'">
    <DelaySign>true</DelaySign>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <!-- Product -->
  <PropertyGroup>

  </PropertyGroup>


  <!-- NUGET -->
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Relase|AnyCPU'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>


  <!-- Compilation -->
  <PropertyGroup Label="Compilation">
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn></NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <PropertyGroup Label="Debug signing" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DelaySign>false</DelaySign>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <PropertyGroup Label="Release Signing" Condition="'$(Configuration)|$(Platform)'=='Relase|AnyCPU'">
    <DelaySign>true</DelaySign>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>

  <!-- Versioning -->
  <PropertyGroup>
    <PackageVersion Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">$(VersionPrefix)</PackageVersion>
    <PackageVersion Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">$(VersionPrefix)</PackageVersion>
  </PropertyGroup>

  <!-- Coverlet -->
  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="2.6.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
```

**Comment by livarcocc** [comment]
I am sorry, I think I misunderstood your original issue. It seems that the problem here is that there is a warning when there wasn't one before. Is that correct?

@nkolev92 is this warning coming from NuGet? Is it new in 16.3?

**Comment by livarcocc** [comment]
By the way, while breaking, I do believe warning here is the right behavior, as it might be surprising for a dotnet pack command to run on a project, do not fail or warn and you end up without a nupkg for it.

Have you tried to NOWARN that particular error?

**Comment by javadparvaresh** [comment]
I'm sorry, maybe that's because of my english.

There no error is printing out just Warning, but also the project is not compiling. when i add `<IsPackable>true</IsPackable>` it works, but if you don't it will print out the warning and assembly will not created. 

in older dotnet-cli it was working, but after installing new version ( dotnet cli 3 ), this problem occurred.

**Comment by dasMulli** [comment]
Am I correct in assuming that you relied on the side effect of calling `dotnet pack` on a non-packable project also built the project but then stopped before packing and now no longer causes this side effect (since it figures out that there is no need to pack earlier)?

**Comment by javadparvaresh** [comment]
@dasMulli no `dotnet pack`. the problem is in `dotnet build` command. when i'm trying to build the solution which contains multiple projects, some of them has `<IsPackagable>true</IsPackagable>` some of them not. but build process fails for the `netcoreapp` projects.

**Comment by dasMulli** [comment]
I can reproduce the warning, however in my case the assemblies (.dll files) are created. Maybe this can be an issue with the treat-warnings-as-errors configuration.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

It has to be the web sdk though. With the `Microsoft.NET.Sdk` no warning is triggered.

**Comment by javadparvaresh** [comment]
actually the project sdk is `Microsoft.NET.Sdk.Web`

My project file is like this :
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <PackageId>xxx.Keystone.Server</PackageId>
    <Description>xxx Keystone Server</Description>
    <IsPackable>true</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
```

if you need i can past the detail build logs

**Comment by nkolev92** [comment]
This warning has been around for a while, so it shouldn't be a new behavior. 

@javadparvaresh 

In your latest project you have IsPackable set to true. 

detailed logs/binlog would be great, but keep in mind that the binlog would contain the environment variables etc.
