### ISSUE TITLE
Package dependency directory has changed since preview

### ISSUE THREAD

**Issue by Kinematics** [dotnet/cli#12701]
## Steps to reproduce
Build project with any of various Microsoft.Extensions.XYZ packages (eg: Microsoft.Extensions.Configuration) using .NET Core 3.0 release.

## Actual behavior

The `Appname.deps.json` file that is produced on build points to reference directories such as "lib/**netcoreapp3.0**/Microsoft.Extensions.Configuration.dll".

## Expected  behavior

Previously, when using preview builds of .NET Core 3, and also what I would normally expect, the `.deps.json` file that is produced on build pointed to reference directories such as "lib/**netstandard2.0**/Microsoft.Extensions.Configuration.dll".

If I check in the packages repository on my drive, there are subdirectories for both `netstandard2.0` and `netcoreapp3.0`.  Since these extensions are just .dll libraries, and not full apps, I would expect the dependencies to be referenced using netstandard rather than netcoreapp.  If there are dependencies on anything that is netstandard2.1 dependent (corresponding to netcoreapp3.0), I would expect a netstandard2.1 subdirectory to be used instead.

This introduces uncertainty regarding usage and accessibility of dependency files, since some other packages still point to `netstandard2.0` directories.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by livarcocc** [comment]
From what kind of project are you referencing this package?

If your project targets netcoreapp3.0, then this is behaving as expected. We are finding the best possible match to your project's TFM and using it.

if you were targeting netstandard2.0 or if you project needed netstandard2.0, say, it targeted netcoreapp2.1, then you would see netstandard2.0 being picked.

If it is behaving as I explained above, then this is by design. The change here is that  the package now provides a more specific TFM and we are selecting it.

**Comment by Kinematics** [comment]
The primary project is netcoreapp3.0.  The primary component of the solution (which is where the vast majority of the references are made from) is a netstandard 2.1 assembly.

I'm still uncomfortable with this, as it requires manual updates to the .csproj file in order to work around other .NET Core limitations.  In particular, I don't know why it's `netcoreapp3.0` instead of `netstandard2.1`.  But if it's a deliberate choice, and not likely to change again, I can work with it.
