### ISSUE TITLE
"dotnet new -l" using a 3.1.100 preview SDK welcomes me to .NET Core 3.0 instead

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#12713]
(Copying from mail) Encountered by scenario testing on .NET Core 3.1.100-preview1-014066 SDK:

![welcome](https://user-images.githubusercontent.com/12819531/65627984-1e6c1900-df96-11e9-92f6-756a8ef87408.png)

It looks like this string controls it:

https://github.com/dotnet/cli/blob/5dd9784ad7f75ee4ebd74f7a177667470c9ec36e/src/Microsoft.DotNet.Configurer/LocalizableStrings.resx#L121

**Comment by livarcocc** [comment]
@wli3 seems like a simple and small fix. Can you take care of that?

**Comment by wli3** [comment]
good catch

**Comment by Lydia-Shi** [comment]
Verified this bug with .Net core 3.1.100-preview1-14455 from release branch, the issue has been fixed.
Result as below image:
![ShowCore3 1](https://user-images.githubusercontent.com/54019172/66379209-97805d00-e9e7-11e9-947d-6a84f735973f.PNG)

**Comment by Amy-Li02** [comment]
"dotnet new -l" using a 5.0 SDK welcomes me to still .NET Core 3.0 instead.
![image](https://user-images.githubusercontent.com/49627022/66693414-225ca280-ecdb-11e9-9abb-1be959a03803.png)

**Comment by livarcocc** [comment]
@wli3 seems like we missed this for 5, can you take care of it?

**Comment by wli3** [comment]
I think it did not flow to the branch. Now it is derived from the version below (SDK version)

**Comment by livarcocc** [comment]
Can you check where the code flow stands and push it through?! 😄
