### ISSUE TITLE
Settings for a self-contained WinForms goes into new folders for every publish

### ISSUE THREAD

**Issue by felizk** [dotnet/cli#12749]
## Steps to reproduce
 * Publish a self contained WinForms app. 
 * Run it.
 * Change and save some Settings (using the WinForms style .settings)
 * Notice settings are saved in LocalAppData ultimately in a folder with this kind of postfix: "_Url_2z3wslwxp2unr2f2llkyxtrbrq3rb5cd"
 * Repeat, notice the postfix has changed and settings are not reused

## Expected  behavior
To be able to persist settings between versions of the application.

## Actual behavior
Every time you publish, settings are effectively wiped.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/winforms#1996
