### ISSUE TITLE
Should we have a dotnet new test for dotnet new

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1275]
dotnet test with xunit right now requires a couple of extra feeds and requires the project.json to have a particular set of things in there.

I had a couple of people reach me over the week for help on getting dotnet test working for them. We should consider adding a template for tests to dotnet new and we need to update the sample.

**Comment by blackdwarf** [comment]
@livarcocc @enricosada introduced the `--type` option. One of the options could be `test` to allow for testing projects. However, we would also have to include all possible test runners which would become really crowded at some point. Or would it?

**Comment by enricosada** [comment]
@blackdwarf `test.xunit` is better than `test` because xunit it's not the only one, nunit 3.0 works too.

About crowded, i think it's possibile to add something like : 

- download template from url (or path): `dotnet new --type http://xunit.github.io/dotnetcli/1.0` 
- download template from nuget package

I'll add these to dotnet new enhancement issue, maybe can be useful

**Comment by blackdwarf** [comment]
@enricosada could we do something like `dotnet new c#/test/xunit` in keeping with our plan for other types? 

Also, not sold on the downloading template bit, honestly. Could be a good extension command, but would like to keep `dotnet new` in the core package close to the things we ship in there. Hope it makes sense.

**Comment by enricosada** [comment]
Sure @blackdwarf `test/xunit` is better as `--type` :+1:, i'll check my pr for `lang/type` probably the triple `/` doesnt work but should. 
If you want i can send the pr for `test/xunit`

I understand downloaded template mean versioning etc and provide types only for what's used there is ok.

**Comment by livarcocc** [comment]
-t xunittest
