### ISSUE TITLE
Publish produce empty runtimeconfig

### ISSUE THREAD

**Issue by kvpt** [dotnet/cli#12751]
Since DotNetCore 3.0 release, my CI/CD pipeline is broken because runtimeconfig.json file is now empty. My pipeline worked fine with 2.x release.

Is it intended ? 
I doesn't found any breaking changes documentation for the 3.0 cli.

## Steps to reproduce
> dotnet new console -n MyApp

> Replace the PropertyGroup of the csproj with the one below

> dotnet restore MyApp.csproj

> dotnet build MyApp.csproj --configuration Release --no-restore

> dotnet publish MyApp.csproj --configuration Release --output d:\output --self-contained False --no-restore --no-build

## Expected  behavior
runtimeconfig.json not empty

## Actual behavior
runtimeconfig.json empty

Using the all in one command produce the right output.
> dotnet publish MyApp.csproj --configuration Release --output d:\output --self-contained False

## Environment data
The problem occur in AzureDevOps build container and also on my machine which use the latest VisualStudio version (16.3.1 at the moment).

`dotnet --info` output:

>  SDK .NET Core :
>  Version:   3.0.100
>  Commit:    04339c3a26

My csproj :
```xml
<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
</PropertyGroup>
```

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by dsplaisted** [comment]
@knpt I think the issue will be fixed if you add `--self-contained False` to the `dotnet build` command line.

I also think this will probably be fixed when we fix https://github.com/dotnet/sdk/issues/2787

**Comment by kvpt** [comment]
@dsplaisted It doesn't work. 
> Error MSB1001: Unknown switch.

**Comment by dsplaisted** [comment]
@kvpt Try `-p:SelfContained=false` instead

**Comment by kvpt** [comment]
@dsplaisted I tried with `-p:Self Contained=false` which doesn't work, 
but `-p:SelfContained=false` works.  👍

Thanks.

**Comment by livarcocc** [comment]
Closing as there is a work-around available and a better bug tracking this.
