### ISSUE TITLE
Suggestion - dotnet CLI Tools User Installer

### ISSUE THREAD

**Issue by JaimeStill** [dotnet/cli#12764]
Most of the work that I do is in an environment that has no internet connection. I routinely need to transfer packages from my internet connected environment to the offline environment.

Would it be possible to have a user profile based installer for the `dotnet` CLI, similar to how VS Code has a user installer? If not this, then would it be possible to have an executable download with a subset of features, similar to how the `nuget` CLI can just be downloaded as an executable?

While I am authorized to transfer between both networks, I can't install the .NET Core SDK. I was looking into trying to use the `nuget` CLI to package missing dependencies, but ran into this:

![image](https://user-images.githubusercontent.com/14102723/65997274-0f3e0d00-e467-11e9-9f01-e67543bfd106.png)  
> From [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#cli-tools)

Any feedback would be greatly appreciated!

**Comment by livarcocc** [comment]
I am sorry. I don't quite follow your ask here. dotnet.exe on itself does very little. For instance, dotnet restore, is actually implemented by the SDK. Under the cover, dotnet.exe restore gets translated into dotnet dotnet.dll restore.

So, providing you a package that ships only dotnet.exe would do nothing, really.

**Comment by JaimeStill** [comment]
I would like to be able to prepare .NET Core 3 dependencies to be added to `%USERPROFILE%\.nuget\packages` similar to how the `nuget` CLI allows you to for .NET Framework / .NET Standard dependencies via:

```
nuget install <package> -Source <source> -OutputDirectory <path-to-output>
```

This way, I can capture the dependencies, in the format expected for .NET Core based projects, and transfer them to my offline environment.

Currently, the only way I can accomplish this is by doing a `dotnet add package {package}` in a project on my computer at home, then capturing the updated resources from the global nuget cache.

**Comment by livarcocc** [comment]
This sounds more like a nuget feature. Please, file an issue for this at nuget/home.

**Comment by JaimeStill** [comment]
Please re-open due to [NuGet CLI being retired](https://github.com/NuGet/Home/issues/8654#issuecomment-537627101)

**Comment by livarcocc** [comment]
This is still an issue that needs to be looked at by NuGet. They own dotnet restore, even though it is surfaced through the CLI. They also own package restore and what you are asking is a variation of that.
