### ISSUE TITLE
Docs/reference for project.json/global.json/build in general

### ISSUE THREAD

**Issue by aL3891** [dotnet/cli#1276]
Hello, I've been looking around at the project json and what it can do but i havent found a lot of docs so I've been digging in the code. So now I'm thinking, since I'm looking around there anyway, maybe i can help out documenting it? 

I have a few questions though, 

- Is anyone working on this already? what parts? 
- Where should i put such a document? there are some docs in this repo but there is also the core-docs repo that i understand is connected to the http://dotnet.github.io/ site. what docs should go where?

**Comment by GuardRex** [comment]
The official docs are at https://docs.asp.net/en/latest/ and there are contributing instructions at the bottom of the nav menu on the left.

**Comment by aL3891** [comment]
right, but should the cli docs really be on the asp.net docs repo?

**Comment by shahid-pk** [comment]
yes i think dotnet/cli docs should be on dotnet.github.io  , but @blackdwarf  will know better , i think he is the relevant person here.

**Comment by blackdwarf** [comment]
@shahid-pk yep, I will be putting up the reference docs and "what is CLI" soon on https://dotnet.github.io/docs/. 

@aL3891 dotnet/core-docs is the repo that "feeds" the docs on dotnet.github.io/docs/. Can you please file an issue there for `project.json` reference? Thanks!

**Comment by aL3891** [comment]
Allright, sure :)

**Comment by aL3891** [comment]
closing this one
