### ISSUE TITLE
dotnet test, azure devops. Not working on with csproj and devops artifacts

### ISSUE THREAD

**Issue by generik0** [dotnet/cli#12777]
Hi
I have seen other issues (closed) regarding this matter. However none of them adress azure devopops (cload) and build agent.

The basic issue =

When trying to run a dotnet test on a csproj, with personal nugets on devops artifacts, even though the source is added to the build agent, the nuget fail for dotnet test.

This is even is there are adde previous tasks:
- dotnet restore (with nuget.config file)
- dotnet build (which needs --configfile switch)

## Steps to reproduce
* Have a csproj that uses a nuget from devops artifacts
* Have a pipleing with tasks:
- dotnet restore with a **/*test.csproj search, and nuget.config including the devop artifacts
- dotnet build with a **/*test.csproj search, and  --configfile swtich to the nuget.config including the devop artifacts
- dotnet test **/*test.csproj 

## Expected  behavior

I expect it not to fail for the dotnet test

## Actual behavior

It fails because of nuget packages, even thought the restore and build was before

![image](https://user-images.githubusercontent.com/2411563/66038507-9a281180-e512-11e9-82fa-8fde670a6da3.png)

![image](https://user-images.githubusercontent.com/2411563/66038495-93010380-e512-11e9-85e7-0755648cc35b.png)

![image](https://user-images.githubusercontent.com/2411563/66038353-30a80300-e512-11e9-8c19-0c24faff5eeb.png)

Attached is the raw log:

[rawlog.txt](https://github.com/dotnet/cli/files/3680715/rawlog.txt)

**Comment by livarcocc** [comment]
I am sorry. This is not the right repo for this issue. I would try nuget/home.

**Comment by generik0** [comment]
@livarcocc how can this be nuget home?:

- It is the dotnet test that does not allow a configfile parameter
- it is the dotnet buidl not understanding that the nugets are installed.

Sounds like the dotnet build is running from its responsibility., 
Are you sure we ewant to start a finger pointing contest beteen the MS nuget dudes and the MS dotnet build dudes?

**Comment by generik0** [comment]
@livarcocc anyway i found what i needed was "dotnet test --no-build" the "--no-restore" is not good enough as the build will trigger the restore. But the "dotnet test --no-build" does the job ;-)

**Comment by livarcocc** [comment]
dotnet build invokes dotnet restore under the covers (quite, but not exactly). That piece of code is owned by NuGet and is better investigated by them. Which is why I suggested an issue there.

as for the `dotnet test --no-restore` not honoring the no restore because of build does sound like a bug on our side. Could I trouble you to file a separate issue for that. The no-restore flag should be passed down to our build invocation to prevent build from doing an implicit restore.
