### ISSUE TITLE
dotnet tool install fails behind authenticated proxy on linux

### ISSUE THREAD

**Issue by los93sol** [dotnet/cli#12795]
## Steps to reproduce
export http_proxy=<proxy info here>
export https_proxy=<proxy info here>
dotnet tool install --global dotnet-trace

## Expected  behavior
It should install the dotnet-trace tool

## Actual behavior
It fails with
/dotnet/sdk/3.0.100/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/tmp/nmcypofv.dnl/restore.csproj]
/dotnet/sdk/3.0.100/NuGet.targets(123,5): error :   Response status code does not indicate success: 407 (authenticationrequired). [/tmp/nmcypofv.dnl/restore.csproj]

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by los93sol** [comment]
If i add http_proxy to the config section in /root/.nuget/NuGet/NuGet.Config I get the following
/dotnet/sdk/3.0.100/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/tmp/54carrug.d2x/restore.csproj]
/dotnet/sdk/3.0.100/NuGet.targets(123,5): error :   GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate). [/tmp/54carrug.d2x/restore.csproj]

**Comment by los93sol** [comment]
Also worth noting that I have also tried installing gssntlmssp package as well but that doesn't resolve the issue either

**Comment by wli3** [comment]
Could you repro it with nuget restore? Like using dotnet add package ? Since dotnet tool use nuget underneath.

**Comment by los93sol** [comment]
Not sure what you mean exactly, like dotnet restore on a project?  nuget seems to be encapsulated within dotnet tool so unless I manually install the mono version of nuget I'm not sure how I would go about that

**Comment by wli3** [comment]
No, I mean setting `export http_proxy=` etc first. And then run an add package for a random nuget package like

`dotnet add package Newtonsoft.Json --version 12.0.2` see if you cannot download any thing from nuget

**Comment by los93sol** [comment]
Results coming shortly.  I'm doing this in a docker container so it's trivial for me to start fresh, really just need to get this working as I have an app I need to do some performance profiling on

**Comment by los93sol** [comment]
It's just hanging with no error so far

**Comment by los93sol** [comment]
I ended up getting it working, not sure what exactly I did that finally got it to go, but it's working now, probably going to open a new issue with CoreFx repo as a feature request to have parity with other things in Linux like curl where this worked as expected without all the additional fuss
