### ISSUE TITLE
dotnet restore fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by luhis** [dotnet/cli#12808]
I have updated my site to dotnet core 3.0, but it fails to restore the packages.  Dotnet restore just hangs.  Reverting back to my old core 2.2 version worked.  I tried using a brand new Ubuntu Server 16.04 image and it restored just fine.  It looks like a similar issue to this https://github.com/dotnet/cli/issues/11560 however setting MSBUILDDISABLENODEREUSE=1 made no difference

## Steps to reproduce
git clone https://github.com/luhis/CodeGolf.git
cd CodeGolf
dotnet restore

## Expected  behavior
nuget packages would be restored

## Actual behavior
Process hangs and never completes

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.                                                              App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#8667
