### ISSUE TITLE
RESX compilation can't handle spaces

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1280]
Whenever I try to compile my project, and it includes a `*.resx` file, the compilation fails with weird errors if the full path to the RESX file contains a space. Move the project to a full path that has no spaces in it, and it compiles cleanly. Note that a project that does not contain any `resources` or `namedResources` always compiles correctly, even if its full path contains a space.

**Comment by brthor** [comment]
@wjk Can you please provide a repro?

Also what platform are you on?

**Comment by wjk** [comment]
Windows 10; .NET CLI version output:

```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

I'll provide a test case tonight.

**Comment by wjk** [comment]
@brthor [wjk/dotnet-cli-1280](https://github.com/wjk/dotnet-cli-1280). Download, `dotnet restore`, `dotnet compile`.

**Comment by brthor** [comment]
Thanks @wjk I am seeing the same behavior. 

I'll take a look at this.

**Comment by brthor** [comment]
Going to wait for #1300 to go in before investigating further. 

Looks like that issue is related.
