### ISSUE TITLE
Strange Included value passed to `dotnet test`

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/cli#12821]
Hi I'm Marco from Coverlet.

I've a question about the verb test.
In coverlet we allow to users to pass some parameters to specify an "include" filter(globbing).
Sometime for some project I found that also if user doesn't pass anything I find some strange filter, for instance:
```
F:\git\coverletissues\Xunit.StaFact\src (HEAD detached at 6d1a5e6 -> origin)
λ dotnet test --filter "TestCategory!=FailureExpected" -v:m /p:CollectCoverage=true
```
I get this "Include" filter(the switch to pass to coverlet include is for instance `/p:Include:[asm*]*` https://github.com/tonerdo/coverlet/blob/master/src/coverlet.msbuild.tasks/InstrumentationTask.cs#L33)

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.24.28117\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.24.28117\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt
```
My suspect is that `Include` is already used by some build part so it's an unhappy name choice, can you confirm?

cc: @tonerdo @petli

**Comment by 0xd4d** [comment]
Do you run that command inside of a VS command prompt? It sets an `INCLUDE` environment variable.

Coverlet shouldn't use common names such as Include, Exclude etc, but should add some prefix eg. CoverletInclude etc to minimize problems like this. I think there's an issue already.

**Comment by MarcoRossignoli** [comment]
> Coverlet shouldn't use common names

I agree...

**Comment by MarcoRossignoli** [comment]
@0xd4d thank's for the hint...I didn't think about...and yes usually I work on vs command prompt, confirm you thesis.
