### ISSUE TITLE
dotnet test has exit code 0 despite BadImageFormatException

### ISSUE THREAD

**Issue by bender2k14** [dotnet/cli#12842]
## Steps to reproduce and Environment data
When using the [pool](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pool) with VM image label [`windows-2019`](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent), the relevant part of the `dotnet --info` output is
```
RID: win10-x64
```

Therefore, it is no surprise that executing
```
dotnet test Tests\Tests.fsproj --runtime win-x86
```
doesn't work since the [RID](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)s are incompatible.  Specifically, the relevant part of the logs when "Enable system diagnostics" is checked is
```
Test run for D:\a\1\s\src\Tests\bin\Debug\netcoreapp3.0\win-x86\Tests.dll(.NETCoreApp,Version=v3.0)
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:02.06] Exception discovering tests from Tests: System.BadImageFormatException: Could not load file or assembly 'Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
File name: 'Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at // ... stack track omitted

No test is available in D:\a\1\s\src\Tests\bin\Debug\netcoreapp3.0\win-x86\Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
Results File: D:\a\_temp\VssAdministrator_fv-az604_2019-10-07_18_48_39.trx

##[debug]Exit code 0 received from tool 'C:\Program Files\dotnet\dotnet.exe'
```

## Expected  behavior
I expected `dotnet test` to return a nonzero exit code since it encountered a `BadImageFormatException`.

## Actual behavior
`dotnet test` to returned an exit code of 0 despite encountering a `BadImageFormatException`.

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2217
