### ISSUE TITLE
dotnet-sdk-5.0 depends on dotnet-apphost-pack-5.0, dotnet-targeting-pack-5.0. Do those packages exist?

### ISSUE THREAD

**Issue by naricc** [dotnet/cli#12846]
I am trying to install the latest build on unbutu, using dpkg, but there are some packages I can't find any where linked on the github page. Specifically otnet-apphost-pack-5.0, dotnet-targeting-pack-5.0.  Are these packages available somewhere?

For reference, here is the command I am using, and the output:

$ sudo dpkg -i dotnet-sdk-latest-x64.deb 
(Reading database ... 115796 files and directories currently installed.)
Preparing to unpack dotnet-sdk-latest-x64.deb ...
Unpacking dotnet-sdk-5.0 (5.0.100-alpha1-014854-1) over (5.0.100-alpha1-014854-1) ...
dpkg: dependency problems prevent configuration of dotnet-sdk-5.0:
 dotnet-sdk-5.0 depends on dotnet-targeting-pack-5.0 (>= 5.0.0~alpha1.19507.3); however:
  Package dotnet-targeting-pack-5.0 is not installed.
 dotnet-sdk-5.0 depends on dotnet-apphost-pack-5.0 (>= 5.0.0~alpha1.19507.3); however:
  Package dotnet-apphost-pack-5.0 is not installed.

dpkg: error processing package dotnet-sdk-5.0 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dotnet-sdk-5.0

**Comment by livarcocc** [comment]
Try looking for them at dotnet/core-setup.

More instructions can be found there: https://github.com/dotnet/core-sdk. It contains a link to https://github.com/dotnet/core-setup#daily-builds
