### ISSUE TITLE
'dotnet publish' ignores file name casing.

### ISSUE THREAD

**Issue by voroninp** [dotnet/cli#12849]
## Steps to reproduce
Create a project named with Pascal casing style and DO NOT set `<AssemblyName>` element explicitly.
In my case project's name is  `Luscii.Identity.Service.csproj`.

Then call `dotnet publish Luscii.Identity.Service.csproj`
You'll end up with published application containing `Luscii.Identity.Service.dll` file.

Delete `publish` folder !

Now call `dotnet publish luscii.identity.service.csproj`

You'll end up with published application containing `luscii.identity.service.dll` file. lowercased!

On Linux you are going to have great fun because of that.

## Expected  behavior
I expect CLI to use the casing of the file, not the argument.

## Actual behavior
It looks like CLI uses casing of the argument.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

**Comment by livarcocc** [comment]
@wli3 could you help @sfoslund gain some more understanding of this code and fix this issue? If possible?

**Comment by rainersigwald** [comment]
The ideal fix would be at the MSBuild layer: microsoft/msbuild#3665.

**Comment by wli3** [comment]
Agree, so close this one and prefer microsoft/msbuild#3665
