### ISSUE TITLE
new Ping(); fails on .NET Core 3.0 Trimmed Build 

### ISSUE THREAD

**Issue by sourcetonuts** [dotnet/cli#12853]
## Steps to reproduce

Building in .NET and trimming causes new Ping() to throw an exception

Unhandled exception. System.TypeLoadException: Could not load type 'System.Net.NetworkInformation.Ping' from assembly 'System.IO.FileSystem, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

## Expected  behavior

It shouldn't throw an exception when built with .NET and trimmed.

## Actual behavior

Exception thrown.
Unhandled exception. System.TypeLoadException: Could not load type 'System.Net.NetworkInformation.Ping' from assembly 'System.IO.FileSystem, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

## Environment data

%1 is project
%2 is win-x64 

::FAILS dotnet publish %1 -r %2 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true -o .\publish\%2\%1

:: THIS works
dotnet publish %1 -r %2 -c Release /p:PublishSingleFile=true  -o .\publish\%2\%1

**Comment by livarcocc** [comment]
@jeffschwMSFT since this is related to trimming.

**Comment by jeffschwMSFT** [comment]
In this case, hopefully the exception provides the detail that will help get it working.  Can you try adding the following?

```
<ItemGroup>
  <TrimmerRootAssembly Include="System.IO.FileSystem" />
</ItemGroup>
```

We are evaluating all the areas of NetCoreApp that are not linker friendly and are considering our options.

cc @sbomer

**Comment by sourcetonuts** [comment]
Added suggested <ItemGroup> to the project file and I'm still receiving the same exception. Removing trimming option on the build and all's well. Ping, I don't think , is part of that assembly.

**Comment by sourcetonuts** [comment]
Adding the following does seem to do the trick.

	<ItemGroup>
		<TrimmerRootAssembly Include="System.Net.Ping" />
	</ItemGroup>

**Comment by livarcocc** [comment]
Closing this since the issue seems to have been addressed.

**Comment by sourcetonuts** [comment]
@livarcocc I wouldn't call that closed but a workaround to something that's broken. But that's me.

**Comment by sbomer** [comment]
@sourcetonuts this is likely one instance of a broader class of issues where the linker doesn't catch reflection uses, which is what @jeffschwMSFT mentioned we're thinking about. Would you be able to share the full stack trace just on the off chance that this is a different kind of issue?
