### ISSUE TITLE
Consdering Adding dotnet sln sort

### ISSUE THREAD

**Issue by aolszowka** [dotnet/cli#12858]
## Steps to reproduce
Have The following:

1.  One Solution File (`Common.sln`)
2.  Two Branches (`FeatureA` / `FeatureB`)
3.  Two Projects (`A.csproj` / `B.csproj` )

On `FeatureA` Branch Developer X realizes that they need to add components `A.csproj` and `B.csproj` to `Common.sln` to support a feature they are working on. They perform an `dotnet sln add` in the order `A.csproj` and `B.csproj`

On `FeatureB` Branch Developer Y realizes that they also need to add components `A.csproj` and `B.csproj` to `Common.sln` to support their feature. They perform an `dotnet sln add` in the order `B.csproj` and `A.csproj`.

When they go to merge this change they now have a conflict that needs to be resolved, whereas if there had been some deterministic sort order you'd give your merging tool a better chance to resolve this (and at very least allow the human using the tool a clearer picture of what happened).

Our scenarios are obviously much more complex (due to the deep dependency tree) but the above is a simple illustration.

The below commands will simulate this:

```
dotnet new sln -n Common
dotnet new sln -n Common2
dotnet new console -n A
dotnet new console -n B
dotnet sln Common.sln add A\A.csproj
dotnet sln Common.sln add B\B.csproj
dotnet sln Common2.sln add B\B.csproj
dotnet sln Common2.sln add A\A.csproj
```

Try comparing `Common2.sln` to `Common.sln` (simulating a branch merge).

## Expected  behavior
A deterministic sort to Solution files. The sort really doesn't matter so long as it is deterministic across files (you sort both sides before committing/comparing).

## Actual behavior
`dotnet sln add` will perform appending operations (this is the same behavior in Visual Studio). A long time ago there was a UserVoice (and before that a Connect) issue to ask for this feature as well within Visual Studio.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.507
 Commit:    e8520940d7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.507\

Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240

.NET Core SDKs installed:
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
While interesting, this is not something that we plan to invest in for the foreseeable future. Based on that, I am going to close this issue.

**Comment by aolszowka** [comment]
Thanks for the feedback!

**Comment by livarcocc** [comment]
@aolszowka thanks for reaching out. Please, keep these coming!

**Comment by aolszowka** [comment]
FWIW Closing the loop on this we have open sourced (MIT Licensed) our tooling https://github.com/aolszowka/VisualStudioSolutionSorter
