### ISSUE TITLE
dotnet restore fails with NotSupportedException (DecryptString)

### ISSUE THREAD

**Issue by mgravell** [dotnet/cli#1286]
Identical report (not by me, different time and project) on stackoverflow: http://stackoverflow.com/questions/35069022/dotnet-restore-nuget-commandline-xplat-program-exception

A console says a thousand words:

```
d:\Dev\dapper-dot-net>where dotnet
C:\Program Files\dotnet\bin\dotnet.exe

d:\Dev\dapper-dot-net>dotnet restore

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NuGet.CommandLine.XPlat.Program' threw an exception. ---> System.NotSupportedException: Specified method is not supported.
   at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.Configuration.PackageSourceProvider.ReadCredential(String sourceName)
   at NuGet.Configuration.PackageSourceProvider.ReadPackageSource(SettingValue setting, Boolean isEnabled)
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSources()
   at NuGet.Protocol.Core.v3.CachingSourceProvider..ctor(IPackageSourceProvider packageSourceProvider)
   at NuGet.CommandLine.XPlat.Program..cctor()
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.XPlat.Program.EnsureLog(CommandOption verbosity)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass7_0.<Main>b__0(CommandLineApplication restore)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Command(String name, Action`1 configuration, Boolean throwOnUnexpectedArg)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```

There is a nuget.confg in the folder that restricts things to api.nuget.org:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <!--
    <add key="CoreCLR" value="https://www.myget.org/F/dotnet-coreclr/api/v3/index.json" />
    -->
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

Note: `dnu restore` works fine for this project.

**Comment by mgravell** [comment]
Update: it does it for new projects too, so it isn't the project itself:

```
d:\Dev>md FooDotNet

d:\Dev>cd FooDotNet

d:\Dev\FooDotNet>dotnet new
Created new C# project in d:\Dev\FooDotNet.

d:\Dev\FooDotNet>dir
 Volume in drive D is Data SSD
 Volume Serial Number is A8CA-6024

 Directory of d:\Dev\FooDotNet

08/02/2016  16:47    <DIR>          .
08/02/2016  16:47    <DIR>          ..
08/02/2016  16:47               392 NuGet.Config
08/02/2016  16:47               214 Program.cs
08/02/2016  16:47               241 project.json
               3 File(s)            847 bytes
               2 Dir(s)  500,095,254,528 bytes free

d:\Dev\FooDotNet>dotnet restore

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NuGet.CommandLine.XPlat.Program' threw an exception. ---> System.NotSupportedException: Specified method is not supported.
   at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
   at NuGet.Configuration.PackageSourceProvider.ReadCredential(String sourceName)
   at NuGet.Configuration.PackageSourceProvider.ReadPackageSource(SettingValue setting, Boolean isEnabled)
   at NuGet.Configuration.PackageSourceProvider.LoadPackageSources()
   at NuGet.Protocol.Core.v3.CachingSourceProvider..ctor(IPackageSourceProvider packageSourceProvider)
   at NuGet.CommandLine.XPlat.Program..cctor()
   --- End of inner exception stack trace ---
   at NuGet.CommandLine.XPlat.Program.EnsureLog(CommandOption verbosity)
   at NuGet.CommandLine.XPlat.Program.<>c__DisplayClass7_0.<Main>b__0(CommandLineApplication restore)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Command(String name, Action`1 configuration, Boolean throwOnUnexpectedArg)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)


```

**Comment by davidfowl** [comment]
@mgravell check your global nuget.config. Encrypted passwords aren't supported.

**Comment by mgravell** [comment]
@davidfowl firstly: I can confirm that this solves the issue. But:

Is that a "yet" or an "ever"? and in either case: can it not just **ignore it**?

In particular, it shouldn't care about something it *isn't being asked to use* - see the first example where the only feed is the open nuget.org one, which does *not* have a credential in the global config.

To add insult to injury, the one with an encrypted password is actually one of the ones in `<disabledPackageSources>` - so there's **two separate** reasons why it shouldn't have cared about that password.

**Comment by sklivvz** [comment]
This just bit me too, and I was merely following the [official getting started guide](https://dotnet.github.io/getting-started/). I found that this is a terrible first experience with the product, as it looks like it's *my fault* instead of the product's.

* The tutorial should always work or it should cover this.
* If encrypted passwords are not supported, `dotnet` should explain how to fix and not crash with a stacktrace

**Comment by phenixdotnet** [comment]
Hi.

We run into the same errors and now we have the same question: Is it will be supported in future release ? We are working with package management in VSTS and it required encrypted password.

dnu command support it, I guess dotnet cli will support it too

**Comment by blackdwarf** [comment]
@yishaigalatzer for this.

@sklivvz just to fully understand (so I can fix the getting started) you had a global nuget.config on your machine that had a feed in it that required credentials, you installed the CLI, did the `dotnet new` and then `dotnet restore` and it failed with the same error as in the issue?

**Comment by yishaigalatzer** [comment]
Encrypted credentials will not be supported in the current form in the near future. We could do something about the error message. Let's open an issue in nuget

**Comment by blackdwarf** [comment]
@yishaigalatzer (why the hell can I not just @ you???) thanks!

@mgravell if its ok with you, I would close this issue out and continue tracking on NuGet. @sklivvz I would open up an issue at dotnet/dotnet.github.io to fix the getting started to warn about this problem. This sound ok?

**Comment by mgravell** [comment]
Sure, close it if there's a better home for it - as long as someone
somewhere has some plan to make it less of a trap, because at the moment it
is not obvious what has happened. Just about anything would be better than
the current "fail with a misleading and non-obvious error".

On 26 February 2016 at 15:20, Zlatko Knezevic <notifications@github.com>
wrote:

> @yishaigalatzer <https://github.com/yishaigalatzer> (why the hell can I
> not just @ you???) thanks!
>
> @mgravell <https://github.com/mgravell> if its ok with you, I would close
> this issue out and continue tracking on NuGet. @sklivvz
> <https://github.com/sklivvz> I would open up an issue at dotnet/
> dotnet.github.io to fix the getting started to warn about this problem.
> This sound ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/cli/issues/1286#issuecomment-189320384>.
>



-- 
Regards,

Marc

**Comment by sklivvz** [comment]
@blackdwarf yes: the global config had encrypted credentials, and the local config had a "clear", so I don't know why it needed them anyways.

Also, opening this somewhere else is fine by me, thank you!

**Comment by blackdwarf** [comment]
Thanks guys, closing this, two new issues opened in their respective repos! :)
