### ISSUE TITLE
Calling dotnet test from a shell script fails on Ubuntu server with net core 3

### ISSUE THREAD

**Issue by stuartd** [dotnet/cli#12860]
We have a shell script that runs our .net core 3 integration tests on a Ubuntu server: it was running just fine, but since upgrading to .net core 3 it has stopped working.

It still works on OSX and in WSL using net core 3 (and the equivalent .bat file works on Windows). 

I have reinstalled .net core 3 on the server but to no effect.

There are two problems, which are detailed below:

1. Calling `dotnet test` from a shell script fails with a permissions error in net core 3, but when calling it from the command line it will run - however..
2. Parameters to `dotnet test` are somehow mangled when running from the command line.

## Permissions error

The shell script is just this:

```bash
# this works just fine
git pull

# run the project which gets the repo path, CDs to the test project folder, 
# and runs the tests, passing along any parameters as a test filter
dotnet run --project TestRunner/TestRunner.csproj $@ 

# run the project which analyzes the test results and generates a results page
dotnet run --project TestResultAnalyzer/TestResultAnalyzer/TestResultAnalyzer.csproj 
```

The first issue is a permissions error calling `dotnet test` from the script: this is the diagnostic output of the TestRunner project:

```
Current directory: /home/username/code/codename/src/API/App/App.Tests
Test command:
dotnet test --filter skeleton -l:trx;LogFileName=App_Test_Run_2019-10-10-11-40.trx -r /home/username/code/codename/src/API/TestRuns/App
Starting process
```
And this is the error which occurs when starting the process:

> Unhandled exception. System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at TestRunner.Program.Main(String[] args) in /home/username/code/codename/src/Misc/TestRunner/Program.cs:line 77
   
And this is the code:

```cs
process = new Process {
	StartInfo = {
		Arguments = $"test {arguments} -l:trx;LogFileName={testRunName}.trx -r {testResultFolder}",
		FileName = "dotnet",
		UseShellExecute = false
	}
};
                      
var commandDebug = $"{process.StartInfo.FileName} {process.StartInfo.Arguments}";

Console.WriteLine("Test command");
Console.WriteLine(commandDebug);
Console.WriteLine("Starting process");
process.Start(); // boom
```
   
So, my first issue is:

Why is calling `dotnet test` from a shell script resulting in a permissions error, when calling it from the command line does not?

## Test parameter mangling

And that leads to my second issue.

If I run the above from the command line (note we are using NUnit as the test runner)

`dotnet test --filter skeleton -l:trx;LogFileName=App_Test_Run_2019-10-10-11-40.trx -r /home/username/code/codename/src/API/TestRuns/App`

Then the tests run, but I get this error message:

> -r: command not found

As per [the documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test), `-r` specifies the location of the test output file:
 
> Directory in which to find the binaries to run.
> -r|--results-directory <PATH>

And indeed the file is not put in the right place, it ends out here, instead of in the `TestRuns/App` folder as specified:

> /home/username/code/codename/src/API/App/App.Tests/TestResults/_servername_2019-10-10_11_46_36.trx

And thus the analyzer can't find it, as it's not in the right place.

Now as I said above, this exact same code works in Windows, OSX and WSL and worked on Ubuntu with net core 2.2 - but on the Ubuntu server it Just. Will. Not. Work. with net core 3.

So the second issue is:

Why is this test syntax not working on Ubuntu under net core 3?

Supplementary info:

#### Output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/49/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/snap/dotnet-sdk/49/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/snap/dotnet-sdk/49/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/snap/dotnet-sdk/49/shared/Microsoft.NETCore.App]
```
  
#### Package references in the test project

```xml
<ItemGroup>
  <PackageReference Include="FluentAssertions" Version="5.9.0" />
  <PackageReference Include="JetBrains.DotMemoryUnit" Version="3.0.20171219.105559" />
  <PackageReference Include="nunit" Version="3.12.0" />
  <PackageReference Include="NUnit.ConsoleRunner" Version="3.10.0" />
  <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.3.0" />
</ItemGroup>
```  

### Server culture

The server culture is en-US-POSIX (which hates humans and their puny case-sensitivity, but I digress..)

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2223
