### ISSUE TITLE
X509Extension.Format() doesn't work well in macOS system

### ISSUE THREAD

**Issue by shidouli** [dotnet/cli#12873]
## Steps to reproduce
MacOs:
PS > $ext.Format($false)
3042304006082B06010505073002863468747470733A2F2F73632D7072642D636F6D702D76633035342E656E672E766D776172652E636F6D2F6166642F766563732F6361

While the same certificate in Ubuntu:
PS > $ext.Format($false) CA Issuers - URI:https://sc-prd-comp-vc054.eng.vmware.com/afd/vecs/ca

## Expected  behavior
In the MacOs, it should return the same result with the one in Ubuntu

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
I am not sure how this is a CLI issue. This is either a corefx issue, if the issue is with the API (you can probably write some c# code to validate that) or with powershell.

**Comment by shidouli** [comment]
Hi livarcocc,

In the macos powershell, it could be reproduced. so I think it's the issue in .net core or powershell core. It's a valid issue, if it's not in cli, could you please share me the right place? or help to point this issue to the right place?

Thanks and BR,
Carrie

**Comment by livarcocc** [comment]
For corefx, it would be `dotnet/corefx`. For powershell, I would imagine `PowerShell/PowerShell`

**Comment by shidouli** [comment]
Thanks Livar!

-Carrie
