### ISSUE TITLE
Running "dotnet Some.NonExistent.dll" for an FDD app tells me "dotnet-Some.NonExistent.dll" doesn't exist

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#12895]
## Steps to reproduce

Run `dotnet Some.NonExistent.dll`, where `Some.NonExistent.dll` doesn't exist. My intent here is to use the `dotnet` host to run an FDD app.

## Expected  behavior

The error message tells me `Some.NonExistent.dll` doesn't exist (if I meant to run a program).

## Actual behavior

The error message tells me `dotnet-Some.NonExistent.dll` doesn't exist (if I meant to run a program):
(Note the `dotnet-` prefix!)

```
$ dotnet Some.NonExistent.dll
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-Some.NonExistent.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

I remember the `dotnet-` prefix being used to build/find SDK commands, maybe that's what the message means by "a .NET Core program"? I'm not sure, I may just not understand the message.

## Environment data

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     fedora
 OS Version:  30
 OS Platform: Linux
 RID:         fedora.30-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
When the host does not find the dll it passes the command down to the CLI. The CLI tries to resolve it using its resolvers. The last one checks if there is a dotnet-<something> in the path. When that fails it returns that error message.

I guess we could check for .dll and improve the message, but I would argue that in those cases, maybe the host should not even pass it forward to the CLI.

In any case, I don't believe this is something we will get to and therefore, I am going to close this issue.
