### ISSUE TITLE
SingleFile Publish Win10-x64 doesnt run on newer windows version than the one it was build on

### ISSUE THREAD

**Issue by TclasenITVT** [dotnet/cli#12892]
## Steps to reproduce
publish a dotnet core 3.0 console app on windows 10.0.14393.
Try running it on a Windows PC 10 x64 1803 (17134.1069).

## Expected  behavior
The Software executes.

## Actual behavior
Not starting but outputting this message (German System Language):

> Die Version von ITVT.Tool.exe ist mit der ausgeführten Windows-Version nicht kompatibel. Überprüfen Sie die Systeminformationen des Computers, und wenden Sie sich anschließend an den Herausgeber der Software.

Rough translation:
This version of the ITVT.Tool.exe is incompatible with the current windows-version. Check the systeminformation of the computer and then talk to the creator of the software.

## Environment data
BuildAgent OS Version: Windows_NT 10.0.14393
On the build agent the dotnet core 3.0.100 sdk is installed.
User Win 10 x64 1803 (17134.1069) here the dotnet core 3.0.100 sdk ist not installed. Also no other dotnet sdk/runtime.

PublishProfile:
```
 <PropertyGroup>
     <PublishProtocol>FileSystem</PublishProtocol>
     <Configuration>Release</Configuration>
     <Platform>Any CPU</Platform>
     <TargetFramework>netcoreapp3.0</TargetFramework>
     <PublishDir>bin\Release\netcoreapp3.0\publish\</PublishDir>
     <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
     <SelfContained>true</SelfContained>
     <PublishSingleFile>true</PublishSingleFile>
     <PublishTrimmed>true</PublishTrimmed>
</PropertyGroup>
```

--

**Comment by dasMulli** [comment]
@vitek-karas @swaroop-sridhar which windows version is the bundle host built for?.. support doc says Version 1607+ should be supported so it should be reasonable to expect it to work on 1803

**Comment by TclasenITVT** [comment]
@dasMulli what do you mean with bundle host? The runtime identifier that it should be build for is win10-x64.

**Comment by dasMulli** [comment]
The executable is actually pre-built and the publish process edits it to add the custom dll files and resources.

**Comment by TclasenITVT** [comment]
The arguments for the publish step are :  publish ITVT.Tool.csproj --configuration release /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml

**Comment by livarcocc** [comment]
@jeffschwMSFT and @nguerrera as well.

**Comment by nguerrera** [comment]
Does the ITVT.Tool.csproj specify `<ApplicationManifest>`? What are the contents of the manifest if so? The manifest is copied from the managed dll to the apphost.

**Comment by TclasenITVT** [comment]
No it does not. It has only propertygroup and itemgroup nodes. Inside the propertygroup it has these nodes:
```
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <Version>3.0.1</Version>
```
and inside the itemgroup these packagerefernces:
  ```
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="4.6.0" />

```

**Comment by nguerrera** [comment]
OK, weird. I'm seeing if anyone has an 1803 box ready to go that I can test with.

**Comment by nguerrera** [comment]
Can you run

`sigcheck -m ITVT.Too.exe` using https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck and paste the result?

I am seeing a default manifest as provided by https://github.com/dotnet/roslyn/blob/fab7134296816fc80019c60b0f5bef7400cf23ea/src/Compilers/Core/Portable/Resources/default.win32manifest

**Comment by TclasenITVT** [comment]
sure, here is the dump:
```
        Verified:       Unsigned
        Link date:      17:05 13.09.2019
        Publisher:      n/a
        Company:        ITVT
        Description:    ITVT.Tool
        Product:        ITVT.Tool
        Prod version:   3.0.1
        File version:   3.0.1.0
        MachineType:    64-bit
        Manifest:
´╗┐<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" name="MyApplication.app"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

**Comment by dasMulli** [comment]
Quickly created a Win10 Pro 1803 VM in azure and uploaded a pre-built file (`dotnet new console; dotnet publish -c Release -r win10-x64 -p:PublishSingleFile=True -p:PublishTrimmed=True`) does work. No software installed on top of the azure image:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/6129250/66861611-a2129780-ef8f-11e9-9f48-b6809946c50e.png">
Also if I try to do it with a publish profile..

**Comment by nguerrera** [comment]
> sure, here is the dump:

Ok, that fully rules out the issue being with the manifest. That's the same default manifest I get.

**Comment by TclasenITVT** [comment]
@dasMulli what was the Version of the Machine you build the app on?

**Comment by TclasenITVT** [comment]
Wow, The Problem was with Git LFS and not with DotNetCore. Closing this sry for the trouble
