### ISSUE TITLE
dotnet compile - all artifacts dropped are +x

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#129]
When running dotnet compile, all of the artifacts that it drops in the bin/ directory (including, for instance, pdb file) are marked as executable (+x). This should not happen, only the actual binary should be executable.

**Comment by piotrpMSFT** [comment]
@blackdwarf can you validate?

**Comment by blackdwarf** [comment]
This still repros. The deps file is +X. However, since the core functions are still working, I will punt this to Feb milestone, since it is not a huge priority.
