### ISSUE TITLE
dotnet pack command doesn't include dependencies

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [dotnet/cli#1290]
Hello,

I have a question related to building nuget package. 

My solution look like:

- AppName.Client
- AppName.Shared
- AppName.Server

Shared project is referenced to Client and Server - like a common, shared library.

`dotnet pack `
generated the nupkg without AppName.Shared.dll

I want to build nuget package of Client with included Shared library. Is it possible?

**Comment by lukasz-pyrzyk** [comment]
Any idea? This issue is a blocker :(

**Comment by RichardSilveira** [comment]
Hi Lukasz, i am having this same issue, and after a lot of research i can´t found a reasonable solution for it...
You closed your issue, but you solved this?
I saw that project.json file has one property called ""packInclude", but i am working on this rigth now...

**Comment by davidfowl** [comment]
Can you be more specific? What do you mean?

**Comment by lukasz-pyrzyk** [comment]
@davidfowl - I've updated the description

**Comment by RichardSilveira** [comment]
Hi @davidfowl, so...i would like to include an dll file from an internal referenced project in my nuget package...
I do have a class library project that is referenced in my main project, that is class library too, and this "main project" that will be packaged as nuget.
I can´t find a way to include this dll inside the nuget package, because i don´t want to create two packages for this, just one, to main project...
Using dotnet cli, by the way...
Thank´s!

**Comment by blackdwarf** [comment]
To me this seems also like a guidance question. What is the process when you build a Nuget package out of a solution with multiple projects in which some are P2P dependencies? Is the guidance that everything should be separately packaged as a NuGet package?

/cc @piotrpMSFT

**Comment by ivanz** [comment]
For those of us using tooling preview 2 - how can I achieve the below (include a project dependency in the nuget only for a certain framework)? Currently "ProjectA.dll" is not included for the "net40" framework in the .nuget...

```
  "frameworks": {
        "net35": { },
        "net40": {
            "dependencies": {
                "ProjectA": {
                    "target": "project"
                }
            }
        },
```

**Comment by piotrpMSFT** [comment]
@blackdwarf the CLI repo is a good example of this. Each P2P project gets "packed" and pack is given a "--version-suffix" to ensure that the P2Ps get a matching replacement for * in both their version numbers and their nuspecs.

@ivanz this seems like a different issue. Can you open one, provide more detail on what you want to do, ideally with a repro?

**Comment by ivanz** [comment]
@piotrpMSFT Done - opened #3959
