### ISSUE TITLE
dotnet pack doesn't work for referenced project

### ISSUE THREAD

**Issue by stsrki** [dotnet/cli#12905]
I have an issue with `dotnet pack` when I try to pack projects that have a reference to the base .csproj.

I have already reported this issue on AspNetCore repo https://github.com/aspnet/AspNetCore/issues/14467 but I think this should be the better place to report the problem.

## The problem

Here is a quick overview:

- I have root project named `Blazorise.csproj`
- I also have sub-project named `Blazorise.Bootstrap.csproj` that have a reference to `Blazorise.csproj`
- When I run dotnet pack for `Blazorise.Bootstrap.csproj` the final package will include `content` and `contentFiles` folders that should not be included.
- Those folders will also have `Blazorise.Bootstrap.StaticWebAssets.xml` that point to my local directory.

## Workaround

I had to come up with some hacky `.nuspec` files to overcome this limitation. The workaround can be seen on PR https://github.com/stsrki/Blazorise/pull/317

- `content` and `contentFiles` folders had to be removed
- `build`, `buildMultiTargeting` and `buildTransitive` had to be copied from `.nupkg` generated from `dotnet pack` so that they could be included in the final package

**Comment by livarcocc** [comment]
@nkolev92 can you help us understand if this is us doing something wrong or provide better guidance?

**Comment by nkolev92** [comment]
@stsrki Can you please provide a repro so we can understand the scenario better?

**Comment by stsrki** [comment]
Hi @nkolev92 

Everything can be found on https://github.com/stsrki/Blazorise in the folder `NuGet`. Just run the `dotnet-pack.bat`.

**Comment by stsrki** [comment]
Hi @nkolev92 

Is there any progress regarding this issue? tnx

**Comment by nkolev92** [comment]
I just tried the repro you provided. 

I see Blazorise.Bootstrap.csproj is created without any content/contentFiles which was suggested to be the original problem.

Does the repro need updated?
Or did I miss something?

Thanks.

**Comment by stsrki** [comment]
@nkolev92 It seems the original problem is gone. I re-checked all the files and could not found any issue. Maybe it was fixed with the latest  update(s) version of Visual Studio.

Anyways, thank you for your time. If anything comes up I will reopen.
