### ISSUE TITLE
Should we make dotnet restore do a transitive restore for P2P references?

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1291]
For instance, when we have project A depend on project B and we do a dotnet restore on A, should it also automatically do a restore on B.

**Comment by blackdwarf** [comment]
@livarcocc what happens if B depends on C? Go until there are no more P2P references?

**Comment by bricelam** [comment]
This would be nice. It's a little awkward that build will try and build transitive projects, but restore won't try and restore them.

**Comment by billwert** [comment]
We need this. Once you get to real projects not using VS, it turns into a real mess. I'm trying to integrate the CLI into a build system right now. There are many different sets of .NET Core projects in it. The only way I can be sure that everything is restored before any individual piece tries to build is to jam a restore from the root before anything else happens. I'd really like to see either this or #1742 very soon.

**Comment by piotrpMSFT** [comment]
Please move this issue to `nuget/home`
