### ISSUE TITLE
Improve error message to dotnet build when it fails to find the project.json file to a P2P dependency

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1292]
Right now, when you do a build and we fail to find the project.json file of the dependency we fail with a null pointer exception, we should fail with a more graceful message.

You can repro this by cloning this repo: https://github.com/livarcocc/cli-1/tree/null_pointer_nuget.

Just remove all dependencies from Reflector, leave only NetStandard, but don't run dotnet restore on it.

Then go to ArgumentsForwardingTests and do a restore there followed by a build.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
