### ISSUE TITLE
dotnet-build: toolset version should be an input to incremental compile

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1294]
Today, Stage1 and Stage2 are built using two different versions of the toolset. DotNet-Build does not pick up on the fact that the toolset has changed, however, and considers the existing compilation outputs to be valid.

This initially seemed like a build script bug, but it's a legitimate scenario. However, this will get hit any time someone updates their toolset and rebuilds.

**Comment by cdmihai** [comment]
How can build detect which toolset it is from? Can it look at args[0] to see where it comes from and add the path as incremental input? One problem here is if args[0] changes. Build would measure the timestamp of a different file.

Besides the toolset, what other implicit dependencies (that do not come from the lock file) should be considered? Here could be some potential ones:
- compiler
- runtime host
- xunit?

**Comment by livarcocc** [comment]
PR https://github.com/dotnet/cli/pull/1847 is fixing this.
