### ISSUE TITLE
dotnet publush for .NET Core 3.x doesn't set execute flags for executables

### ISSUE THREAD

**Issue by ww898** [dotnet/cli#12951]
## Steps to reproduce
`dotnet publish --self-contained true -f netcoreapp3.0 -r linux-x64`
`dotnet publish --self-contained true -f netcoreapp3.0 -r osx-x64`

## Expected  behavior
The compiled executable should be ready to be executed after publishing.

## Actual behavior
.NET Core 3.0/3.1 doesn't set execute flags for executables during publishing. Previous version of .NET Core do it.

## Environment data
- Linux qqq 4.15.0-65-generic #74~16.04.1-Ubuntu SMP Wed Sep 18 09:51:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- macOS Mojave version 10.14
- macOS Catalina version 10.15

**Comment by livarcocc** [comment]
I just tried this on Mojave with the 3.0.100 SDK and I do see the executable flags being set correctly.

Is there any other information you could provide us regarding this? I would I would maybe suggest, is clearing your nuget cache and trying again.

**Comment by ww898** [comment]
@livarcocc I have just reproduced the bug on MacOs Mojave and Ubuntu 16.04 LTS. My configuration is following:
- both computes have no additional software installed - they are clean because they are build agents.
- .NET Core SDK 3.x unzipped into temp directory.
- assigned following environment variables: `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1` and `DOTNET_MULTILEVEL_LOOKUP=0` before execute `dotnet`.
- following command is used to compile and publush: `<absolute path>/dotnet publish -o <absolute path to output dir> --self-contained true -c Release -f netcoreapp3.0 -r linux-x64 <absolute path to project file>`
- executable in `<absolute path to output dir>` doesn't have `X` attribute. Files such as `System.Buffers.dll` or `SOS.NETCore.dll` and many others has 'X' attribute. The difference between .NET Core 2.x and .NET Core 3.x is only 'X' attribute on executable.

**Comment by livarcocc** [comment]
Thanks for letting us know.
