### ISSUE TITLE
Telemetry in `dotnet new console` fully not disabled .net core 3.0

### ISSUE THREAD

**Issue by ichensky** [dotnet/cli#12959]
## Steps to reproduce
1. Set environment variable:
```
    echo "export DOTNET_CLI_TELEMETRY_OPTOUT=1"
```
2. Execute 
```
    dotnet new console
```
## Actual behavior
If there is internet, then 
`dotnet` util will make several HTTP requests.
1. https://go.microsoft.com/fwlink/?linkid=2087906&clcid=0x409
2. https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwebpifeed.blob.core.windows.net%2Fwebpifeed%2FPartners%2FNuGetTemplateSearchInfo.json&data=02%7C***%7Cangelpe%40microsoft.com%7C***%7C***%7C***%7C***%7C***&sdata=***%3D&reserved=0
3. https://webpifeed.blob.core.windows.net/webpifeed/Partners/NuGetTemplateSearchInfo.json

`dotnet` util make 3 HTTP requests just to get `NuGetTemplateSearchInfo.json` file. 

Seems, `dotnet` util sends private data in the first request in the part of url:
 `clcid=0x409`
and in the second request in this part of the url: 
 `&data=02%7C***%7Cangelpe%40microsoft.com%7C***%7C***%7C***%7C***%7C***&sdata=***%3D&reserved=0`

## Expected  behavior
Do not make HTTP request at all or make direct HTTP request to the  `NuGetTemplateSearchInfo.json` file.

**Comment by livarcocc** [comment]
This is not for sending telemetry.

dotnet new checks for templates online to see if there is a newer version of the template.
