### ISSUE TITLE
Can't install tools targeting 3.1

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#12963]
## Steps to reproduce

```sh
dotnet tool install dotnet-ef --version 3.1.0-preview1.19506.2
```

## Expected  behavior

```
Tool 'dotnet-ef' (version '3.1.0-preview1.19506.2') was successfully installed.
```

## Actual behavior

```
error NU1202: Package dotnet-ef 3.1.0-preview1.19506.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package dotnet-ef 3.1.0-preview1.19506.2 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100-preview2-014486
 Commit:    343b2cba36

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\brice\AppData\Local\Microsoft\dotnet\sdk\3.1.100-preview2-014486\

Host (useful for support):
  Version: 3.1.0-preview2.19517.10
  Commit:  3daa0867ab

.NET Core SDKs installed:
  3.1.100-preview2-014486 [C:\Users\brice\AppData\Local\Microsoft\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview2.19517.21 [C:\Users\brice\AppData\Local\Microsoft\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19517.10 [C:\Users\brice\AppData\Local\Microsoft\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19517.10 [C:\Users\brice\AppData\Local\Microsoft\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

cc @ajcvickers @Pilchie

**Comment by ajcvickers** [comment]
@bricelam Does this mean that EF tooling is broken for the 3.1 preview 2 release? Do you know the root cause?

**Comment by bricelam** [comment]
Yes, broken in Preview 1 too. Needs a NuGet update??

**Comment by wli3** [comment]
There is an extra lib folder inside the root of the nupkg

**Comment by bricelam** [comment]
Thanks, I'll work to remove it.

cc @aspnet/build (@dougbu @JunTaoLuo @wtgodbe)

**Comment by bricelam** [comment]
Wait, shouldn't https://github.com/aspnet/EntityFrameworkCore/pull/18214 have resolved this?

**Comment by bricelam** [comment]
Ah, https://github.com/aspnet/EntityFrameworkCore/pull/17658 is where it all went wrong. Other PR is just additional churn of the problem

**Comment by bricelam** [comment]
Working now. Thanks, @wli3! Closing.

**Comment by bricelam** [comment]
Note @wli3, NuGet is erroneously issuing warning NU5128 (missing lib folder) for tools packages? Are there any plans to suppress it?

**Comment by wli3** [comment]
The "default" experience is add `<packastool>true</packastool>` instead of using nuspec. So I think it is ok to for savvy nuspec user to suppress the warning. Although it is a new warning? @nkolev92

**Comment by nkolev92** [comment]
That's a new warning. 

@zivkan did we disable the 5128 validation for different package types?
Did that happen actually happen in code, cause I know we did discuss it :)

**Comment by zivkan** [comment]
We talked about it, but haven't made the change yet.

However, when I do `dotnet new console`, `dotnet add package newtonsoft.json`, edit the csproj to use `PackAsTool` and then run `dotnet pack`, I don't get the warning because the generated nupkg doesn't have any dependencies.

This suggests that @bricelam's package does have NuGet dependencies, which itself doesn't make a lot of sense for a tool as they're supposed to be self-contained, right?

**Comment by bricelam** [comment]
I have an empty dependency group. Is that causing it?

**Comment by zivkan** [comment]
yes. In the scenario when I create a new console app then pack it as a tool, the nupkg doesn't get any dependencies groups, not even an empty one.  Are you using a custom nuspec, rather than letting pack autogenerate one?

**Comment by wli3** [comment]
@zivkan packastool used [this](https://github.com/NuGet/NuGet.Client/pull/2237) flag
