### ISSUE TITLE
dotnet-build fails when a project sub-folder is passed as "--build-base-path"

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#1298]
cd into a project folder and run 
`dotnet.exe build --build-base-path ./foo`

Now `foo` is a sub-folder of the project and `build` fails with compilation errors

**Comment by piotrpMSFT** [comment]
What are the errors?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
