### ISSUE TITLE
Output Verbosity

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#13]
How do we want to handle verbosity of what is written by the CLI?

**Comment by blackdwarf** [comment]
We have this in places. We should review all ofthe cases at some point.

**Comment by dougbu** [comment]
@blackdwarf I'm curious about the "in places" where "we have" is true. The only `dotnet` command I see w/ `--verbosity` support is `dotnet restore`. (That command also has `--quiet` but that's not currently working -- nuget/home#2068.) What other subcommands have varying output levels and are they consistent with `dotnet restore`?

BTW the base `dotnet --verbose` option confuses the issue e.g. what _should_ `dotnet --verbose restore --verbosity error` mean? I know `--verbose` turns up subcommand discovery while `--verbosity error` turns down the subcommand itself. But I'm not sure that will make sense to customers.

**Comment by blackdwarf** [comment]
@dougbu sorry, I cannot seem to remember. My comment could be a triage comment. I need to rewind my brain back to this situation and figure it out. 

The other question is pretty good. Lemme think about it for a spell. Ideally, once you use a verb (command) with a driver, all of the options become the command options, not the driver ones.

**Comment by ericwj** [comment]
Can I explicitly request that building with `dotnet` is by default less verbose than `dnu build`?

It seems from the above my other question asking for more levels apart from quiet and verbose will be covered.

I'm on RC1 and haven't really done anything with dotnet so far, yet I find DNX is annoying me especially running some builds over RDP as the console is 10+ times slower already on a wired GbE link, or keeping me completely in the dark. It might imho be worth engineering it such that there is a way to 1) be completely quiet unless there are errors and 2) only show project names (top level progress) and errors or warnings (actionable stuff) on top of the verbosity of dnu build today.

**Comment by piotrpMSFT** [comment]
Verbosity has been resolved.
