### ISSUE TITLE
dotnet build/publish should pick content transitively

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1301]
I mean, if A depends on B and B has Content its project.json, when building project A, we should copy B's content to the output folder as well.

**Comment by davidfowl** [comment]
We may need to discuss this a bit before implementing it. It's possible there might be collisions

**Comment by andschwa** [comment]
We would want to adopt this behavior.

**Comment by pakrym** [comment]
Closing in favor of https://github.com/dotnet/cli/issues/66
