### ISSUE TITLE
My internet is acting weird.

### ISSUE THREAD

**Issue by XmaXStalker** [dotnet/cli#13038]
For a long time (about 1 year) I cannot create servers at all. Every time, on every game if I create a server I get timed out. The server is lagging and everything is teleporting all over the place, then after 5 minutes I time out. 

My port is forwarded, I got my DMZ Adress set and I have Inbound rules on my firewall with the required port.

![forwarded ports](https://user-images.githubusercontent.com/57114913/68481839-eb799e00-0240-11ea-946d-dfd64197e41f.png)

![DMZ](https://user-images.githubusercontent.com/57114913/68481844-eddbf800-0240-11ea-8932-26cbca4d39a3.png)

Can I get some help please? I can't do any server on my PC.

**Comment by XmaXStalker** [comment]
One side note I forgot to mention is that I have an amazing internet trough optic fibers. 

![internet speed](https://user-images.githubusercontent.com/57114913/68486642-30560280-024a-11ea-94ad-2354cd06865e.png)

**Comment by livarcocc** [comment]
Not sure why this issue was filled here.
