### ISSUE TITLE
Preserve compilation context unusable for test projects

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/cli#1303]
If a test assembly requires preserving compilation context and it is run via the xunit test runner, the compilation context will not be found since the entry point assembly was the xunit runner. 

For example, I ran into this issue in https://github.com/aspnet/Performance/pull/26. The test `Microbenchmarks.Tests.Mvc.MvcRoutingTests.RouteToAction` requires dynamic compilation since it has a view to render. However, even if you set the `preserveCompilationContext` flag in `project.json` of the `Microbenchmarks.Tests`, running the test will produce the exception "System.InvalidOperationException : Entry assembly was compiled without `preserveCompilationContext` enabled". You may want to set the fields `Iteration = 1, WarmupIterations = 0` on the `Benchmarks` attribute to avoid the spew.

cc @davidfowl @pakrym

**Comment by muratg** [comment]
Marking as `blocking-partner` as I believe this blocks some ASP.NET repos from building.

**Comment by jruckert** [comment]
We also seem to be hitting this issue when trying to run Kestrel, 

however this is after doing a 

dotnet publish 
dotnet publish-iis

![image](https://cloud.githubusercontent.com/assets/4064588/12970037/5b4e27d4-d0d9-11e5-8947-e6afacdbd884.png)

**Comment by GuardRex** [comment]
@jruckert Was that with it specified?
```json
    "compilationOptions": {
        "preserveCompilationContext": true,
        "emitEntryPoint": true 
    },
```

**Comment by piotrpMSFT** [comment]
@GuardRex, though that is necessary it is not sufficient. The entry point application in both cases is not the library being built. The application is instead dotnet-test-xunit or dotnet-publish-iis. 

We need @pakrym to define a pattern for loading the right compilationContext when the default is not appropriate.

**Comment by davidfowl** [comment]
This shouldn't matter anymore. There's a PR out to MVC to fix this by using the `IApplicationEnvironment.Name` instead of the EntryAssembly.
