### ISSUE TITLE
Compilation library location for package is overridden by framework assembly path

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/cli#1304]
When running a project, the compilation library may be not found on full clr since a package's location is overridden by the location of the framework reference assembly. 

I ran into this in https://github.com/aspnet/Performance/pull/26 and this can be reproduced by running the project in `testapp/StarterMvc` with `dotnet run` with full clr on the path. The following error is produced "An unhandled exception has occurred: Can not find compilation library location for package 'System.Collections'
System.InvalidOperationException: Can not find compilation library location for package 'System.Collections'"

I'm not too familiar with the deps file and what it entails so the description may be inaccurate here.
cc @pakrym

**Comment by muratg** [comment]
Marking as `blocking-partner` as I believe this blocks some ASP.NET repos from building.
