### ISSUE TITLE
cmd commands in scripts can't be executed

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1306]
if a project.json contains a script that uses regular cmd commands e.g. https://github.com/dotnet/cli/blob/3673e5e12e1e806e6a0cedfefc254a5928cbeb74/test/TestProjects/TestAppCompilationContext/project.json#L19 executing the scripts fails with a message similar to:

```
'"echo"' is not recognized as an internal or external command,
```

This seems to be an issue with how commands and arguments are being escaped

This is related to https://github.com/dotnet/cli/issues/1216

**Comment by brthor** [comment]
@moozzyk For the moment, built in commands like `echo` are not supported.

This is easy enough to work around by creating a file (.cmd or .sh) which calls echo.

There is some semblance of x-plat here through extension inference as well, see example here:
https://github.com/dotnet/cli/tree/rel/1.0.0/TestAssets/TestProjects/TestAppWithScripts

**Comment by galmok** [comment]
This is still an issue. Also, these script commands claims gulp is unavailable (not found):

"postcompile": [ "cmd /c echo after building", "gulp build"],
"postcompile": [ "cmd /c echo after building", "cmd /c gulp build"],

But this entry has no issues with gulp (nor npm or bower):

"prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],

**Comment by brthor** [comment]
@galmok Is gulp on the path in the first instances?

**Comment by galmok** [comment]
@brthor Obviously gulp is not in the path and that is the bug. The path during setup during postcompile does not include a path to gulp. The same is not a problem with the prepublish step. Shouldn't the path for postcompile and prepublish both include a path to gulp (and bower, npm, and maybe more)?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
