### ISSUE TITLE
Global Nuget.config not found

### ISSUE THREAD

**Issue by patrickjamesbarry** [dotnet/cli#1307]
We wasted alot of time that I am hoping to help others with.  Our new dotnet project was not recognizing our global nuget.config file. Turns out that our global nuget.config file was not getting parsed correctly because we had special characters in the passwords.  There were no warnings or errors thrown which, made this very hard to trouble shoot.  

Can this be changed to let the developer know there is a problem with parsing the xml in the nuget.config file?

**Comment by blackdwarf** [comment]
@patrickjamesbarry I believe that this issue should be filed against nuget/home repo, since parsing of Nuget.config is done in the nuget client. 

/cc @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Can you file and have a sample of what chars are not working? Does it work on desktop?

**Comment by patrickjamesbarry** [comment]
I understand that nuget is probably used under the covers, but I was issuing a "dotnet restore" command and my repos/feeds were not  getting found (with no errors showing the reason).  Since I was interacting with dotnet cli, that is why I logged the ticket here.  Are you saying this is because that nuget is not throwing an error for dotnet cli to catch?   The character in our password was an astericks "*"

**Comment by yishaigalatzer** [comment]
Yes dotnet restore is a thin wrapper on nuget.

**Comment by blackdwarf** [comment]
@patrickjamesbarry yup, I'm just trying to get the issue routed to the best place for it to be taken care of. :)

**Comment by patrickjamesbarry** [comment]
https://github.com/NuGet/Home/issues/2158

**Comment by blackdwarf** [comment]
Thanks @patrickjamesbarry, closing this one.
