### ISSUE TITLE
dotnet vs dnx and dnu

### ISSUE THREAD

**Issue by cheers00** [dotnet/cli#1311]
Do I still need to use ```dnu install``` and and ```dnu use``` to install and use new runtimes?

**Comment by shahid-pk** [comment]
no. the runtime is now a nuget package.

**Comment by cheers00** [comment]
thanks. wondering how to get new runtime nuget package.

**Comment by shahid-pk** [comment]
netstandard.library is a meta package that contains the run time and a few other fundamental packages.

**Comment by fredyfx** [comment]
this change is making a lot of sound on internet!

**Comment by blackdwarf** [comment]
@cheers00 I think @shahid-pk's answer solves this particular question/issue so will close. If you have more questions, feel free to reopen.
