### ISSUE TITLE
Publish to Zip File

### ISSUE THREAD

**Issue by normj** [dotnet/cli#1322]
I'm constantly hitting the windows max path length error. I can get around it by setting the output folder for publish to somewhere under c:\temp but that is awkward for tooling's point of view. I was thinking it would be useful to have the ability for publish to write straight to a zip file instead of a folder structure. This avoids the max path length error and I'm betting the next step after publish is normally zip and send the app somewhere.

I'm happy to send a pull request if this is something the cli team would use.

**Comment by piotrpMSFT** [comment]
@normj this sounds like a cool extension to add. I would suggest waiting until we finish the move to MSBuild as I would imagine folks wanting to wire this in as a Task/Target. There's no need to ship this from the CLI repo since folks can get extensions from NuGet packages. Let us know if we can help!

**Comment by RehanSaeed** [comment]
Please also consider publishing to a nupkg file. The two scenarios I think this would greatly help with are:

# Continuous Integration
This would be particularly useful for continuous integration scenarios where artifacts need to be published somewhere. A zip file is ok but a NuGet package would contain the name, version, description, *release notes* and other metadata for that particular build of the application.

Being able to differentiate and see the differences between different builds of the app is a killer feature in my opinion.

# Octopus Deploy
For anyone using Octopus Deploy, it contains the `octo pack` tool which when used with ASP.NET Core, is used to package the published output into a nupkg.

**Comment by blackdwarf** [comment]
@RehanSaeed there is a `dotnet pack` command that you can use for this scenario.

**Comment by RehanSaeed** [comment]
@blackdwarf `dotnet pack` does not contain the entire published output. It only contains the compiled project DLL.

**Comment by blackdwarf** [comment]
@RehanSaeed ah, sorry, missed that part. :) Have you tried playing with `packOptions` and seeing if that helps you?

**Comment by RehanSaeed** [comment]
`packOptions` would work for loose content like views but not reference assemblies or native OS specific runtime DLL's.
