### ISSUE TITLE
dotnet build should copy all contents from compilation output folder to executable folder

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1323]
This will account for things like content and post compile scripts that may move things into a dependency compilation output folder.

**Comment by moozzyk** [comment]
does this mean that it is no longer necessary to include `wwwroot` in the `content` and it will end up with the published app?

**Comment by blackdwarf** [comment]
@livarcocc @pakrym what is the status of this?

**Comment by pakrym** [comment]
@blackdwarf I think this should be closed, @davidfowl was against doing it this way

**Comment by pakrym** [comment]
Closing in favor of https://github.com/dotnet/cli/issues/66
