### ISSUE TITLE
A way to graceful shutdown a process chain

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1327]
`dotnet run` creates 2 processes: (1) `dotnet` and (2) the app being run.
If you kill `dotnet` the app being run (the exe) is orphaned.

For `dotnet watch` we need a way to tell the parent process to terminate the child processes before exiting.

Not sure if this should be addressed at the CLI level, or lower..

cc @piotrpMSFT

**Comment by victorhurdugaci** [comment]
Options so far:
1. Have an API exposed from CLR to kill a process tree
2. Have the cli create a file or write to std out the child process ID
3. Crazy idea: run spawns a process that watches itself and the child process. If one of them dies, it kills the other.
4. Crazy idea: make corehost aware of the parent process and stop if the parent is gone

cc @davidfowl

**Comment by victorhurdugaci** [comment]
This is a much broader issue. If you do "dotnet run" and kill the process from Task Manager, you have the same issue. Maybe corehost should watch for the parent?

**Comment by victorhurdugaci** [comment]
I have to mark this as blocking. Our tests fail because there are processes left orphaned and subsequent compiles fail.

**Comment by victorhurdugaci** [comment]
Removing the blocking flag. We found a workaround using `taskkill`/`pkill`

**Comment by davidfowl** [comment]
@stephentoub new API? `Process.KillAll()`?

**Comment by blackdwarf** [comment]
@anurse @livarcocc  wasn't there a discussion on how to solve this?

**Comment by victorhurdugaci** [comment]
There's a workaround by invoking taskkill/pkill but it's hacky and it doesn't work everyone. For example nano server doesn't have `taskkill`

**Comment by muratg** [comment]
:eyes:

**Comment by victorhurdugaci** [comment]
Just found out that `pkill -TERM -P <id>` kills only the first generation child of `<id>`. If you want to kill an entire tree you have to recursively `pgrep` or something similar and then `kill`. cc @stephentoub

**Comment by brthor** [comment]
@victorhurdugaci did you make any progress in solving this issue? cc @Sridhar-MS is hitting a similar issue

**Comment by victorhurdugaci** [comment]
I ended up writing a helper that kills a process tree. Not the perfect solution but it works for us. https://github.com/aspnet/Common/blob/dev/src/Microsoft.Extensions.Process.Sources/ProcessHelper.cs#L22

**Comment by piotrpMSFT** [comment]
It doesn't look like there is any remaining CLI work being tracked in this issue.

**Comment by muratg** [comment]
@piotrpMSFT What's the recommended way of doing this? (Killing a whole process tree, cross platform)

**Comment by sandorfr** [comment]
@muratg I'm wondering the same... Have you got an answer? 

Would be nice to have an xplat process management API.

**Comment by omajid** [comment]
See also https://github.com/dotnet/cli/issues/7426

**Comment by bgribaudo** [comment]
@muratg 
> What's the recommended way of doing this? (Killing a whole process tree, cross platform)

There's now a [Process.Kill() overload](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=netcore-3.0#System_Diagnostics_Process_Kill_System_Boolean_) for terminating the entire process tree.

**Comment by muratg** [comment]
@bgribaudo perfect! Thanks!
