### ISSUE TITLE
Wrong working directory when dotnet publish executes prepublish script

### ISSUE THREAD

**Issue by bruceyclee** [dotnet/cli#1329]
I have a sample web app in the directory - C:\temp\RC2-WebApp\src\WebApplication3
The content is shown as follows,

 Directory of C:\temp\RC2-WebApp\src\WebApplication3

02/08/2016  09:32 AM    <DIR>          .
02/08/2016  09:32 AM    <DIR>          ..
02/04/2016  09:41 AM                36 .bowerrc
02/04/2016  09:41 AM               416 appsettings.json
02/05/2016  09:49 AM    <DIR>          artifacts
02/05/2016  10:34 AM    <DIR>          bin
02/04/2016  09:41 AM               207 bower.json
02/05/2016  11:03 AM    <DIR>          Controllers
02/05/2016  09:50 AM    <DIR>          Data
02/04/2016  09:41 AM             1,382 gulpfile.js
02/04/2016  10:19 AM                60 hosting.json
02/05/2016  09:50 AM    <DIR>          Models
02/05/2016  09:50 AM    <DIR>          node_modules
02/08/2016  09:32 AM    <DIR>          obj
02/04/2016  09:41 AM               213 package.json
02/04/2016  10:58 AM               937 Program.cs
02/08/2016  09:31 AM             2,507 project.json
02/08/2016  09:31 AM           752,029 project.lock.json
02/04/2016  09:41 AM             7,006 Project_Readme.html
02/08/2016  09:42 AM    <DIR>          Properties
02/05/2016  09:50 AM    <DIR>          Services
02/04/2016  10:37 AM             3,784 Startup.cs
02/05/2016  09:50 AM    <DIR>          Views
02/04/2016  10:00 AM             1,542 WebApplication3.xproj
02/08/2016  09:42 AM               329 WebApplication3.xproj.user
02/05/2016  09:50 AM    <DIR>          wwwroot

The following shows the content of project.json
`
{
  "userSecretsId": "aspnet5-WebApplication3-156d9c4f-9c06-4412-8068-c2c7daef6e89",

  "description": "This is a web app sample on RC2 and dotnet.exe",

  "version": "1.0.0-*",

  "compilationOptions": {
    "preserveCompilationContext": true,
    "emitEntryPoint": true
  },

  "content": [
    "wwwroot",
    "Views",
    "node_modules",
    "appSettings.json"
  ],

  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNetCore.Authorization": "1.0.0-*",
    "Microsoft.AspNetCore.DataProtection.Extensions": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Identity": "1.0.0-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Tooling.Razor": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-*",
    "Microsoft.Extensions.DependencyModel": "1.0.0-*",
    "Microsoft.Extensions.Logging": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-*",
    "Microsoft.NETCore.Platforms": "1.0.1-*",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-*"
  },

  "commands": {
    "web": "WebApplication3",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {

    "dnxcore50": {
      "imports": "portable-net451+win8"
    }
  },

  "tools": {
    "dotnet-publish-iis": "1.0.0-*"
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],

  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath%"
  }
}
`

I have an environment variable, PATH=C:\temp\RC2-WebApp\src\WebApplication3\node_modules\.bin; .........
So this allows me to run "npm install", "bower install", "gulp clean", "gulp min" in my console window.

When I run the following command,
dotnet.exe publish "C:\temp\RC2-WebApp\src\WebApplication3" -o "c:\temp\Output\"
it gave me the following error messages,

> Publishing WebApplication3 for DNXCore,Version=v5.0/win7-x64
The system cannot find the path specified.
The system cannot find the path specified.
module.js:340
    throw err;
          ^
DNX(0,0): Error : Cannot find module 'C:\temp\RC2-WebApp\src\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
module.js:340
    throw err;
          ^
DNX(0,0): Error : Cannot find module 'C:\temp\RC2-WebApp\src\gulp\bin\gulp.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
Illegal characters in path.
Parameter name: path

Looks like that the working directory is wrong so gulp.js cannot be found. 
The working directory should be C:\temp\RC2-WebApp\src\WebApplication3 and gulp.js is under C:\temp\RC2-WebApp\src\WebApplication3\node_modules\gulp\bin

**Comment by bruceyclee** [comment]
I looked at the source code of Execute method of Command class and I found that the prepubish script will be exeucted by cmd.exe. In my sample above, prepublish will execute -> cmd.exe /s /c ""npm" "install""   , this will cause the error message of "The system cannot find the path specified.". 
However, if I removed the quotes of npm and then tried  cmd.exe /s /c "npm "install"" . npm install will be rum with no error message. So it looks like that the quote of npm caused this problem.

in the prepublish script, npm, bower and gulp are .cmd files in windows.
Will be anyone in CLI team to fix this issue ?

**Comment by moozzyk** [comment]
Looks like a dupe of https://github.com/dotnet/cli/issues/1306 and should be fixed by now by @brthor

**Comment by brthor** [comment]
Thanks @moozzyk 

@bruceyclee Can you try this using the latest cli bits? This should be fixed.

**Comment by bruceyclee** [comment]
@moozzyk Thanks for helping.
@brthor  Yes. The problem is fixed in the latest bits. Thanks.

**Comment by brthor** [comment]
Great :smile:
