### ISSUE TITLE
Consider writing errors to the error stream

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#1331]
We've set up our CI to read any output written to the error stream and format it so that errors get highlighted in the CI's summary and build failure emails. This worked well with `dnu build` \ `dnu pack` \ `dnu restore` since errors generated by these tools were written to standard error.
Unfortunately this is not the case with `dotnet` tools. The `build` and `compile` commands write errors to standard out and color codes them.

![image](https://cloud.githubusercontent.com/assets/174281/12933782/cb5f3b68-cf3e-11e5-9186-7faa8f6c2e22.png)

 `dotnet restore` on the other hand writes errors to standard out but prefixes them with the log level:
```
info :   NotFound https://api.nuget.org/v3-flatcontainer/sfkldsjfkljdklf/index.json 309ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/sfkldsjfkljdklf/index.json 452ms
error: Unable to resolve sfkldsjfkljdklf (>= 3.3.0-beta) for DNXCore,Version=v5.0.
```

What's the recommended way to digest these errors in automated systems?

**Comment by yishaigalatzer** [comment]
We are going to keep the info label, but we should write errors to the error stream.

**Comment by pranavkm** [comment]
:+1:

**Comment by blackdwarf** [comment]
@yishaigalatzer since this pertains to NuGet, do we move it to the NuGet repo for tracking?

**Comment by yishaigalatzer** [comment]
It was moved, see the link above

**Comment by pranavkm** [comment]
This is tracked via https://github.com/NuGet/Home/issues/2176
