### ISSUE TITLE
'dotnet run' should execute 'restore' as appropriate

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#1334]
According to http://www.hanselman.com/blog/ExploringTheNewNETDotnetCommandLineInterfaceCLI.aspx, @shanselman wants the following experience for new developers learning a language/platform:

> It should be just as easy - or easier - to use .NET.

> apt-get install mylang #where mylang is some language/runtime
#write or generate a foo.fb hello world program
mylang foo #compiles and runs foo

This should translate into the following commands for dotnet:

```
apt-get install dotnet
dotnet new
dotnet run
```

However, `dotnet run` fails because the user hasn't run `dotnet restore` yet.

I don't feel this is the best experience. As a user, I feel I shouldn't have to run `dotnet restore`. The tooling should know when it needs to be executed, and call it when appropriate. This makes the developer experience easier and therefore better.

There are a handful of other situations that issuing `dotnet run` will print a warning like:

```
warning NU1006: Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.
```

Again, the tooling knows enough to tell me to run this command, it should just run it for me.

**Comment by krwq** [comment]
Hi Eric,

I know and agree it's not ideal to require restore for basic scenarios like 'dotnet new' and ideally should not be required for any code which is only using .NET framework. Currently there is no distinction between framework nuget packages and any other nuget package which causes a problem that you could possibly unintentionally restore unsafe packages or few gigabytes of data.

Once we have a mechanism in place we should whitelist some libraries and act appropriately.
@davidfowl @piotrpMSFT @Petermarcu - are we planning to add this anytime soon?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
