### ISSUE TITLE
'dotnet run' doesn't have the same project.json defaults used by 'dnx run'

### ISSUE THREAD

**Issue by DavidObando** [dotnet/cli#1336]
According to the documentation on [project.json](https://github.com/aspnet/Home/wiki/Project.json-file) the `"content"` property source should have a default value of `"**/*"`.

When running `dotnet build` followed by `dotnet run` on an ASP.NET application we'll see runtime exceptions when MVC can't find the view files it expects. That is, the output binaries are placed in a location but the web application content (the approot) isn't copied as content during the build.

There are fundamental differences between `dotnet run` and `dnx run`, so I understand when defaults aren't the same. That said, there should be a "pitfall of success" path for ASP.NET projects around this very core scenario. We should be more intentional about this.

A workaround to this runtime error is to manually add `"content": "**/*"` and `"contentExclude": "bin/**;obj/**;*.kproj"` to the project.json file. This is not ideal but it unblocks ASP.NET developers.

**Comment by blackdwarf** [comment]
@davidfowl @anurse you guys want to chime in?

**Comment by anurse** [comment]
/cc @DamianEdwards 

There are some differences between dotnet and dnx, and this is one of them. We're looking at tidying this up in a few ways, but for now this is the expected behavior.

**Comment by DamianEdwards** [comment]
Yep. We're still working through this but it's fair to say there will be some default boilerplate in `project.json`, `Program.cs` and `Startup.cs` of an ASP.NET Core app to make this work.
