### ISSUE TITLE
Incremental compilation doesn't when referencing a project with emitEntryPoint : true

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#1337]
ProjectA depends on ProjectB where ProjectB has `emityEntryPoint: true`. When running `dotnet build` on ProjectA, the results of ProjectB are written to `bin\Debug\dnx451\ProjectB.exe`. However, incremental compilation calculates the expected path as `bin\Debug\dnx451\win7-x64\ProjectB.exe` and consequently results in recompilation.

**Comment by piotrpMSFT** [comment]
Why is compilation looking for the exe? The expected path for the exe is correct and should include rid in the path. The dll, however, should be in the tfm path...

@cdmihai

**Comment by pranavkm** [comment]
Compiling for desktop produces a solitary exe. 

> The expected path for the exe is correct and should include rid in the path

Should I change the bug title to state `dotnet build` should always includes rids in the output path including building dependency exes that are referenced?
