### ISSUE TITLE
Executables produced with "dotnet compile --native" cant find third party DLLs

### ISSUE THREAD

**Issue by jamesioppolo** [dotnet/cli#1339]
Running "dotnet compile --native" works fine for the "Hello world!" example command line application produced by "dotnet new" on ubuntu 14.04 LTS.

However, if we try and build some extra functionality by adding a third party library like AWSSDK or Autofac ([example.zip](https://github.com/dotnet/cli/files/124299/example.zip)), the following error occurs when attempting to execute:

>ILCompiler failed generating code for this method; execution cannot continue.
>This is likely because of a feature that is not yet implemented in the compiler.
>Method: [testAutofac]ConsoleApplication.Program.Main
>
>Reason: Assembly not found: Autofac

**Comment by shahid-pk** [comment]
This is a known issue , the native tool chain is long way away from doing anything productive on linux. But you can file this issue on dotnet/corert repo , their the team members can answer you better. But the native tool chain will not come before version 1 of  .net core.

**Comment by shahid-pk** [comment]
version 1 is slated for sometime before summer this year while .net native will come after that.

**Comment by blackdwarf** [comment]
@jamesioppolo will close this, as @shahid-pk explained you can file this against the CoreRT repo.
