### ISSUE TITLE
dotnet run issues

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#134]
- [x] The application base path ends up being the temp directory. We'd need to copy assets so that config files are found (mini publish) or make the app base the original project folder
- [x] Support mono
- [x] Pipe standard input
- [ ] Embed .deps file in the PE file
- [ ] Support passing packages (that could be resolved from global.json or nuget.config)
- [x] P2P references should be compiled in the temporary folder

**Comment by piotrpMSFT** [comment]
@davidfowl @anurse is this issue up to date? Do we need it for Beta?

**Comment by anurse** [comment]
The embedded deps file one is definitely not needed for Beta. We still have a bunch of open questions and it's really just a nice optimization.

@davidfowl can comment on the other one (about passing the packages directory). I think it is still valuable.

**Comment by Petermarcu** [comment]
@davidfowl , where are we on this whole issue? Can it be closed? Can we just open an issue tracing specifically what is left?

**Comment by piotrpMSFT** [comment]
This hasn't had activity for a long time. Closing.
