### ISSUE TITLE
dotnet build cannot pass define(s)

### ISSUE THREAD

**Issue by bryanmacfarlane** [dotnet/cli#1344]
At least I couldn't figure out how.  I even tried ilcargs

I need to pass in contextual defines on the build command line.  The project.json won't suffice because I need to build different variants and the configs would explode.  csc offers this.

**Comment by davidfowl** [comment]
What variants are you trying to build. One of the ideas behind the project.json based projects is that you can only pivot as you would in a nuget package.

**Comment by bryanmacfarlane** [comment]
I'm building debug and release for OSX, Linux and Windows

I want to be able to #if def OS_OSX, OS_LINUX, etc... in our code.  I wanted to avoid exploding configurations out (DebugLinux, ReleaseLinux).  

Is there another way to achieve this without exploding configs and not passing defines on the CLI?

**Comment by bryanmacfarlane** [comment]
I'm also fine with setting the define in the project.json in a conditional on a property (msbuild style) But, I need a way to pass in the property on the build cli for that ??

**Comment by davidfowl** [comment]
There's no way to achieve this today. I'm also not a huge fan of passing things like this on the command line, it doesn't actually work. You can define configurations in project.json if you need to set compilation settings. 

Can you show me an end to end example of what you're doing? I'd like to get an idea.

**Comment by piotrpMSFT** [comment]
https://github.com/aspnet/Home/wiki/Project.json-file

Defines are supported under the buildOptions node.

**Comment by bryanmacfarlane** [comment]
@piotrpMSFT - I wasn't asking for it in a file that's checked in.  I was asking for the ability to be passed on the cmdline as properties like msbuild can do.  I need to invoke a build and for this instance of the build, define something.  You can do this with msbuild.

**Comment by bryanmacfarlane** [comment]
Can you reactivate and address with won't fix or a way to achieve?
