### ISSUE TITLE
dotnet CLI should have a 'last known good' version

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#1349]
Currently [http://dotnet.github.io/getting-started/](http://dotnet.github.io/getting-started/) points at the daily builds for .NET CLI and there is no 'last known good' build that we can point people to. We need this in order to be able to give bits out to early adopters and have them be able to evaluate the experience without running into random issues that happened in any particular day's build.

**Comment by piotrpMSFT** [comment]
@gregg-miskelly thanks for opening. We're planning to produce an LKG build, though not officially name it as a preview or anything, once our remaining known cross-plat blocker issue is fixed. Are you planning to reference this in a named release? Or just use it as an LKG for stable experiences?

**Comment by gregg-miskelly** [comment]
Just as an LKG for stable experiences.

**Comment by piotrpMSFT** [comment]
Cool. I expect to have a signed, unnamed, stable build this week. Will share links here.

**Comment by piotrpMSFT** [comment]
@blackdwarf FYI

**Comment by enricosada** [comment]
It's possibile to have stored all builds by day (if it's nightly)? Not only lastest lkg or latest built.

Maybe a build it's ok for c#, but has problem with f# or can have problem with specific bugs

So if a build is not ok for me, i can download **my** latest working and i can tell people to try a specific **built** version. Like  "you can try f# with dotnetcli/1.0.0.20160131/package.zip binaries".

**Comment by blackdwarf** [comment]
This is good. As soon as we produce it, we will update all of the relevant information to point to the LKG as a default install release.

**Comment by blackdwarf** [comment]
@gregg-miskelly @piotrpMSFT I believe we have this now, correct?

**Comment by gregg-miskelly** [comment]
I don't know the answer for sure. I can tell you that [http://dotnet.github.io/getting-started/](http://dotnet.github.io/getting-started/) still points at daily builds. But I am not sure if there is another place I should point to. Furthermore I can also say that we haven't run into the quality issues that we were having. But I don't know if that is because we have done a better job of not publishing builds that are DOA, or because we have gotten better about keeping the build from going to hell in the first place.

**Comment by blackdwarf** [comment]
@gregg-miskelly the GS content should change today to point to a versioned build (now that all the packages for all platforms are called the same).

**Comment by gregg-miskelly** [comment]
Thanks. What version will be used? I think I would like to request today's build if possible.

**Comment by blackdwarf** [comment]
@gregg-miskelly I think I will use the latest version, since we upped our test coverage and they are all pretty stable. Makes sense?

**Comment by gregg-miskelly** [comment]
Sounds good to me.

**Comment by gregg-miskelly** [comment]
@blackdwarf can we move the Linux version to whatever the LKG build you picked also? Currently the Windows/OSX pages point to daily builds, but the Linux instructions point to an LKG build which is before a feature we need + breaking changes to debugging interfaces.

**Comment by piotrpMSFT** [comment]
@krwq, this is all about your active links feature. Can you share a link and make sure that your design covers these scenarios?

**Comment by blackdwarf** [comment]
@gregg-miskelly this is now done, the GS page is pointing to a version across the board. Should we close this?

**Comment by gregg-miskelly** [comment]
Sounds good
