### ISSUE TITLE
Remove RID detection override

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1352]
In order to work around https://github.com/NuGet/Home/issues/1941, I added this override: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore/Program.cs#L41 to our dotnet-restore wrapper. We need to remove that now, as it a) no longer necessary and b) causing issues when a `project.json` defines a `runtimes` section.

/cc @piotrpMSFT - I didn't have cycles to get this done right now but @dagood needed it for porting some repos. It should just be a matter of removing that entire section from the Program.cs, but it would require a little testing and verification to make sure restore still works for projects that don't specify `runtimes`

**Comment by dagood** [comment]
Thanks. A bit of elaboration: until this is removed, we can't upgrade the version of CLI in corefx/wcf.

/cc @weshaggard @ericstj

**Comment by davidfowl** [comment]
I also filed https://github.com/NuGet/Home/issues/2114

**Comment by piotrpMSFT** [comment]
this should be done today.

**Comment by piotrpMSFT** [comment]
PR is out...
