### ISSUE TITLE
Latest dotnet-win-x64.latest.msi is broken.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#1353]
The latest msi linked from the readme appears broken (1.0.0.001281 beta).

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.msi

When run, you get an error stating dnet-1.cab cannot be found.

**Comment by Sridhar-MS** [comment]
This has been fixed with https://github.com/dotnet/cli/commit/56e3d8f903320ed721aa442e7b139e9df1512ffa

The download link will now point to a bundle instead of MSI.
https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe

FYI @robmen
