### ISSUE TITLE
dotnet restore has different default verbosity between platforms

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#1356]
On Windows, dotnet restore has different default output levels on Windows. Mac and Ubuntu are very similar. These should report the same information regardless of platform.

The Ubuntu/Mac output contains a lot of things that look like failure but aren't actually problems, for example.
[dnr_out_mac.txt](https://github.com/dotnet/cli/files/125675/dnr_out_mac.txt)
[dnr_output_unix.txt](https://github.com/dotnet/cli/files/125676/dnr_output_unix.txt)
[dnr_output_windows.txt](https://github.com/dotnet/cli/files/125677/dnr_output_windows.txt)

**Comment by Sridhar-MS** [comment]
@billwert The output depends on the state of the nuget packages cache. If the packages have been previously downloaded then `restore` does not do a http request. Hence you wont see the requests in the output.

I would suggest trying `dotnet restore --verbosity minimal` if you want similar output.

**Comment by billwert** [comment]
@Sridhar-MS I used --packages, hoping it would make it ignore the existing cache, to try and get similar behavior across platforms. Is that a bad assumption?

**Comment by blackdwarf** [comment]
@billwert can you please move this issue to Nuget/Home?
