### ISSUE TITLE
unhelpful message when you publish without restoring first

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1359]
When you try publish without restoring the packages first the message gives an impression that the agrs are incorrect - e.g.
```
PS C:\Source\cli-samples\HelloWeb> dotnet publish -o app
'C:\Source\cli-samples\HelloWeb' cannot be published  for '<no framework provided>' '<no runtime provided>'
```

Even if you provide correct arguments you still get:
```
PS C:\Source\cli-samples\HelloWeb> dotnet publish -o app -f dnxcore50 -r win7-x64
'C:\Source\cli-samples\HelloWeb' cannot be published  for 'dnxcore50' 'win7-x64'
```

It should contain a hint saying that the packages were not restored for the given framework/rid and if the framework/rids were not provided it should also say what were the default ones that were tried instead of `<no framework provided>` `<no runtime provided>`

**Comment by livarcocc** [comment]
Same as https://github.com/dotnet/cli/issues/1163. Closing this one.
