### ISSUE TITLE
Build does not work on Ubuntu because of System.CommandLine lacking a strong name

### ISSUE THREAD

**Issue by AustinWise** [dotnet/cli#1360]
It looks like the System.CommandLine version currently used does not have a strong name. But for some reason it builds fine on Windows. And on Ubuntu it builds fine using the stage 0 but not stage 1.
```
*** Compiling stage2 dotnet using just-built stage1 ... ***

Compiling Microsoft.DotNet.Compiler.Common for DNXCore,Version=v5.0
/home/austin/cli/artifacts/ubuntu.14.04-x64/stage1/bin/dotnet "compile-csc" "@/home/austin/cli/src/Microsoft.DotNet.Compiler.Common/obj/Debug/dnxcore50/dotnet-compile.rsp" returned Exit Code 139
/home/austin/cli/src/Microsoft.DotNet.Compiler.Common/warning CS8002: Referenced assembly 'System.CommandLine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Compilation failed.
```

It looks like the version of System.CommandLine was switched [reletivly recently](https://github.com/dotnet/cli/commit/f190fa08956879f8cebd2597b2e57ed1be088c80).

**Comment by piotrpMSFT** [comment]
The warning and error are unrelated. The error is due to a CoreCLR issue that is fixed and coming in tomorrow's build. The warning is something that has been ongoing for some time. We will fix.
