### ISSUE TITLE
`content` errors with relative paths on Ubuntu 14.04

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#1361]
Per #1131, the following `project.json` (with a minimal `main.cs`) will error:

```json
{
    "name": "repro",

    "compilationOptions": {
        "emitEntryPoint": true
    },

    "content": [ "../foo" ],

    "frameworks": {
        "dnxcore50": {
            "dependencies": {
                "NETStandard.Library": "1.0.0-rc3-23729"
            }
        }
    }
}
```

Steps and versions:

```sh
$ touch ../foo

$ dotnet restore

$ dotnet publish
Publishing repro for DNXCore,Version=v5.0/ubuntu.14.04-x64
Compiling repro for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.3001789


The process cannot access the file '/home/andrew/src/foo' because it is being used by another process.

$ dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

$ uname -orv
3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 GNU/Linux

$ aptitude show dotnet-nightly
Version: 1.0.1.001252-1
```

Expected result:

That `../foo` gets copied to `bin/Debug/dnxcore50/ubuntu.14.04-x64/foo`.

/cc @livarcocc

**Comment by livarcocc** [comment]
@andschwa I just tried this and it worked.

I did
``` 
dotnet new
touch ../foo
modified project.json by adding "content": "../foo"
dotnet build
```

This was a version of the CLI that I built myself in the Ubuntu machine.

**Comment by andschwa** [comment]
@livarcocc It gets even funnier. Newest package does not error... but it places the content at `bin/Debug/dnxcore50/../`, that is, `bin/Debug`. How can I specify the destination of the content, without it being inferred from the path to the source?

**Comment by andschwa** [comment]
Also, the original failure continues to repro for `dotnet publish`, just not `dotnet build`.

**Comment by livarcocc** [comment]
@andschwa I need to check for publish. As for the bin/debug, that is also strange as I have fixed this a few weeks ago and the build I tried actually put it under bin/config/tfm/rid.

**Comment by andschwa** [comment]
That is strange indeed. We've worked around for now, but it's far from ideal. In this particular case... we copied the files from their original location into the project's tree. But they still live outside the tree, so we have to be careful about manually updating the copies.

**Comment by blackdwarf** [comment]
@andschwa @livarcocc what is the status of this? Does it still repro?

**Comment by andschwa** [comment]
@blackdwarf Quick test this morning with 1.0.0.001504-1 no longer seemed to repro. I will test with the main project soon and update!

**Comment by andschwa** [comment]
@blackdwarf The error is gone on both Ubuntu 14.04 and OS X.

However, it copies the file to the full path (so if I say `../foo/bar/baz` I get `output/foo/bar/baz`, but I need just `output/baz`). Will there be support for specifying the destination of the file?
