### ISSUE TITLE
Dotnet build without first doing a restore shows double error

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#1368]
C:\cli\MyApp>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 3218-B9FD

 Directory of C:\cli\MyApp

02/11/2016  11:02 AM    <DIR>          .
02/11/2016  11:02 AM    <DIR>          ..
02/11/2016  11:02 AM               395 NuGet.Config
02/11/2016  11:02 AM               214 Program.cs
02/11/2016  11:02 AM               241 project.json
               3 File(s)            850 bytes
               2 Dir(s)  386,222,112,768 bytes free

C:\cli\MyApp>dotnet build
Project MyApp does not have a lock file.
Project MyApp does not have a lock file.

**Comment by drewnoakes** [comment]
You can repro this with these steps:

    mkdir tmp && cd tmp
    dotnet new
    dotnet build

**Comment by blackdwarf** [comment]
Yeah, this still repros. My data:

```console
.NET Command Line Tools (1.0.0-beta-001511)

Product Information:
 Version:     1.0.0-beta-001511
 Commit Sha:  211f0e7af3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

**Comment by VanCoding** [comment]
While trying to compile the Kestrel SampleApp, I've got a similar error message on my Windows 7 x64 machine.

I tried 
```
git clone git@github.com:aspnet/KestrelHttpServer.git
cd KestrelHttpServer/samples/SampleApp
dotnet restore
dotnet build
```

But even with running `dotnet restore` and it creating a project.lock.json file, I still get the error message:

```
Project Microsoft.AspNetCore.Server.Kestrel does not have a lock file.
Project Microsoft.AspNetCore.Server.Kestrel does not have a lock file.
```

**Comment by sirentek** [comment]
Same behaviour as @VanCoding has.

```
cd KestrelHttpServer/samples/SampleApp
dotnet restore
dotnet build
```

Output
```
Project Microsoft.AspNetCore.Server.Kestrel does not have a lock file.
Project Microsoft.AspNetCore.Server.Kestrel does not have a lock file.
```

**Comment by alemoi** [comment]
We tried the latest `dev` branch and did `dotnet restore` on `KestrelHttpServer\samples\SampleApp` then `dotnet build` and got the same two errors:
```
Project Microsoft.AspNetCore.Server.Kestrel does not have a lock file.
Project Microsoft.AspNetCore.Server.Kestrel does not have a lock file.
```

**Comment by Fodsuk** [comment]
same issue when installing the net dotnet cli (version 1.0.0-beta-001598) and running 'dotnet build' on the MVC samples (e.g. TagHelperSample.Web).

(message appears twice).
>dotnet build
Project Microsoft.AspNetCore.Mvc.Abstractions does not have a lock file.
Project Microsoft.AspNetCore.Mvc.Abstractions does not have a lock file.

**Comment by jchannon** [comment]
Same with Kestrel sample app with `.NET Command Line Tools (1.0.0-rc2-002339)`

**Comment by FatherDougal** [comment]
I have the same issue

**Comment by mregen** [comment]
+1

**Comment by axtens** [comment]
Well, here it is 25 June and, with the latest download, I also have the same problem.

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

Here we are at 002702 but nothing much seems to have changed since 002677

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

**Comment by mregen** [comment]
A workaround is to run `dotnet restore` in the root folder of a project. It restores all subfolder projects, saves some time compared to walking through all subfolders and restoring them.
