### ISSUE TITLE
dotnet restore fails on latest Windows from dotnet.github.io site

### ISSUE THREAD

**Issue by cartermp** [dotnet/cli#1371]
Got latest from here: http://dotnet.github.io/getting-started/

```
> dotnet new
> dotnet restore
```

result:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.PlatformAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.DotNet.Tools.Restore.Program.Main(String[] args)
```

![dotnet-new-crash-2016-02-11](https://cloud.githubusercontent.com/assets/6309070/12988230/91ee2976-d0b4-11e5-8afc-736154768c50.PNG)

**Comment by benaadams** [comment]
```
>dotnet restore

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Program' 
or one of its dependencies. The system cannot find the file specified.
```

**Comment by davidfowl** [comment]
Whats the version of dotnet?

**Comment by benaadams** [comment]
Mine's super helpful...
```
> dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14267
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by davidfowl** [comment]
That's an old version. Uninstall and reinstall the version worked now.

**Comment by cartermp** [comment]
I just downloaded the latest version and still have the same issue:

![dotnet-failed-again](https://cloud.githubusercontent.com/assets/6309070/13234995/75ef19e6-d970-11e5-98e3-d1e7f0cd55c8.PNG)

**Comment by benaadams** [comment]
/grumble grumble... installers

works for me after an uninstall of the multiple versions and a re-install

**Comment by GuardRex** [comment]
@cartermp Do you have the `DOTNET_HOME` env var set on your system? If so, uninstall `dotnet cli` from Programs and Features, delete the env var, then re-install. https://github.com/dotnet/cli/issues/1429

**Comment by cartermp** [comment]
@GuardRex thanks, that worked!
