### ISSUE TITLE
Remove mscorlib.ni patch work in dotnet-build

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1374]
PR #1243 is patching mscorlib to be side-by-side of coreclr.dll to workaround non-inclusion of mscorlib.ni.dll next to CLR in the currently shipping packages. Once @gkhanna79 is able to fix it in the internal builds and new nupkgs are uploaded either remove the patching code if need be or retain for backward compat.

**Comment by davidfowl** [comment]
Can this be done yet?

**Comment by gkhanna79** [comment]
This is waiting on https://github.com/dotnet/coreclr/pull/3214 to go through. @ellismg Were you able to validate your PR in the closed build?

**Comment by ellismg** [comment]
There is additional closed work that needs to be done.  I'm going to try to get it it by EOW, but I have some higher priority CLI stuff that need to be wrapped up first.

**Comment by gkhanna79** [comment]
@schellap PTAL if anything is required to be done.

**Comment by schellap** [comment]
Mscorlib is next to CLR packages and the patch work that was done as part of `DOTNET_HOME` has been removed. So closing this issue...
