### ISSUE TITLE
IDE Integration for dotnet-test

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1376]
- [X] Support extra parameters in dotnet test.
- [X] Implement new communications protocol.

# dotnet-test IDE API
[ ] IDE passes -b | build-base-path directory path to dotnet-test AND IDE passes --framework --runtime and --configuration to dotnet-test
[ ] OR IDE passes -o | output
[ ] IDE passes project.json path to dotnet-test
[ ] IDE passes --port which is the port on which to communicate test discovery/execution/control messages
[ ] IDE passes --parent which is the parent process ID. dotnet-test will terminate if that process terminates.

dotnet-test -b|build-base-path -f -r -c [-p path to PJ] --port [--parent-process-id]
dotnet-test -o [-p path to PJ] --port [--parent-process-id]

# Communications Protocol
## Test Execution
When we want to execute tests under the debugger:
1. Start dotnet-test
2. Once socket communication is established. Dotnet Test will connect as a client to the supplied port:
 - d-t: TestSession.Connected
 - IDE: VersionCheck (optional)
 - d-t: VersionCheckResponse
 - IDE: TestExecution.GetTestRunnerProcessStartInfo
 **  Starting listening on Port before returning
 - d-t: TestExecution.TestRunnerProcessStartInfo {dotnet-test-runner params port} - the whole command line
 ** d-t needs to handle test results now coming from the socket.
 - d-t: TestExecution.TestStarted {...}
 - d-t: TestExecution.TestResult {...}
 - d-t: TestExecution.Completed {}
 - d-t: TestExecution.RunnerUnreachable {}
 - IDE: TestSession.Terminate {}
3. dotnet-test shuts down at this time.

## Test Runner Test Execution
This documents the message exchange between dotnet test and the test runner during the test execution. dotnet test job will be to send the list of tests to the runner and then mainly to forward these received messages to the adapter.
 - t-r: TestRunner.WaitingCommand
 - d-t: TestRunner.Execute { Tests }
 - t-r: TestExecution.TestStarted {}
 - t-r: TestExecution.TestResult {...}
 - t-r: TestRunner.TestCompleted {}

## Test Discovery
When we want to execute tests under the debugger:
1. Start dotnet-test
2. Once socket communication is established. Dotnet Test will connect as a client to the supplied port:
 - d-t: TestSession.Connected
 - IDE: VersionCheck (optional)
 - d-t: VersionCheckResponse
 - IDE: TestDiscovery.Start
 - d-t: TestDiscovery.TestFound {...}
 - d-t: TestDiscovery.Completed {}
 - IDE: TestSession.Terminate {}
3. dotnet-test shuts down at this time.

## Test Runner Test Discovery
This documents the message exchange between dotnet test and the test runner during the test discovery. dotnet test job will be mainly to forward these messages to the adapter.
 - t-r: TestDiscovery.TestFound {...}
 - t-r: TestRunner.TestCompleted {}

**Comment by livarcocc** [comment]
Test Execution

When we want to execute tests under the debugger:
1. Start dotnet-test
2. Once socket communication is established:

IDE: VersionCheck
d-t: VersionCheckResponse
IDE: TestExecution.Start { debug=true;...}
if (debug == true )
d-t: TestExecution.AwaitingDebugger { ProcessID=12345; }
IDE: TestExecution.DebuggerAttached {}
d-t: TestExecution.TestStarted {...}
d-t: TestExecution.TestResult {...}
d-t: TestExecution.Completed {}
IDE: TestSession.Terminate {}
dotnet-test shuts down at this time.

**Comment by citizenmatt** [comment]
Can I just confirm that I understand this correctly? In order to debug, the IDE first starts `dotnet-test`, then asks for the process start info. The IDE will then use this command line to launch the actual runner, under the debugger. The actual runner will send messages to `dotnet-test`, which will relay them back to the IDE.

If the actual runner exits successfully, the debugging session will end, as will `dotnet-test` and everything is good. If the actual runner crashes, the debugging session will end, and the IDE can send `dotnet-test` the `TestSession.Terminate` message. The same happens if the debugging session is terminated - the actual runner process goes away, and the `dotnet-test` process is sent the `TestSession.Terminate` message.

Is this right?

Also, how does the IDE handle cancelling a test run when not debugging? Does it send `TestSession.Terminate`, and `dotnet-test` will kill the child process?

**Comment by livarcocc** [comment]
Everything but the last part. At least so far, dotnet test won't be able to kill the child process as we don't really know what it is. We could add a message for it to send us its PID, but given that VS started it, should we be the ones to stop it?

We just need to discuss this last piece a bit.

**Comment by citizenmatt** [comment]
I guess it depends who starts the child process (`dotnet-test-xunit`). I was assuming that VS would only start it when debugging, and `dotnet-test` would start it when VS was just running tests, but that doesn't have to be the case, right? VS could *always* start the child process, for debugging and running tests, couldn't it?

**Comment by livarcocc** [comment]
Yes, I believe that's the current design.

**Comment by sayedihashimi** [comment]
FYI I've added `blocking-partner` to this issue. From discussions that I've had internally we are hoping to have a dogfood bulid with debuging unit testing available by next Friday 3/4. I think we'll need this fixed and have some extra time to review/try it out.

cc @barrytang @vijayrkn

**Comment by livarcocc** [comment]
@sayedihashimi I have provided a private build of the CLI that has all the communication protocol implemented. The code has been checked in, but our official builds have a minor issue right now.

**Comment by sayedihashimi** [comment]
@livarcocc thanks, that sounds great

**Comment by livarcocc** [comment]
https://github.com/dotnet/cli/pull/1609 should unblock the debugging experience and is the last bit in the communications protocol implementation. There is still work left to support extra parameters in dotnet test though.

**Comment by citizenmatt** [comment]
BTW, how does the IDE (Visual Studio, or A.N.Other, such as ReSharper) find the right `dotnet.exe` to invoke? Does it just assume it's on the path?

**Comment by livarcocc** [comment]
@vijayrkn Can you answer this? As far as I know, it uses a registry key, but I don't know which one.

**Comment by vijayrkn** [comment]
Yes, ProjectSystem looks at the following regkey for dotnet installpath. I think there are more changes happening in this space to handle multiple versions, but for now this is the path:

HKEY_LOCAL_MACHINE\SOFTWARE\dotnet\Setup\InstallDir

**Comment by citizenmatt** [comment]
Cool, thanks. Can this be included in the documentation write up (#1803), please? Also, similar instructions for cross-platform would be really useful in the not-too-distant future.

**Comment by livarcocc** [comment]
Remaining parameters added by https://github.com/dotnet/cli/pull/1853.
