### ISSUE TITLE
Unresolved P2P dependency throws Cast Error in ProjectModel

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1380]
To Repro:
See this issue: https://github.com/NuGet/Home/issues/2106

`dotnet publish`

Output: 
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.DotNet.ProjectModel.LibraryDescription' to type 'Microsoft.DotNet.ProjectModel.ProjectDescription'.
```

This is on Windows 10 using the latest dotnet cli

**Comment by moozzyk** [comment]
Is this a dupe of https://github.com/dotnet/cli/issues/1288?

**Comment by davidfowl** [comment]
Yap
