### ISSUE TITLE
Are these restore exceptions "normal" right now ...

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1381]
These types of exceptions started cropping up mid-day today (and I still can't shake them). Are they "normal" right now with the churn in packages?
```
info :   OK https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/
microsoft.aspnetcore.mvc.core/1.0.0-rc2-17051/microsoft.aspnetcore.mvc.core.1.0.0-rc2-17051.nupkg
 93762ms
warn : The file 'C:\Users\guard\AppData\Local\NuGet\v3-cache\
a3f7996bd74fb18cce048733dd07221a97fca25d$spnetcidev_api_v3_flatcontainer_\
nupkg_Microsoft.AspNetCore.Mvc.Core.1.0.0-rc2-17051.dat' is corrupt.
error: End of Central Directory record could not be found.
```

```
info :   GET https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/
microsoft.aspnetcore.mvc.apiexplorer/index.json.
error: End of Central Directory record could not be found.
```

**Comment by GuardRex** [comment]
I have it on good authority that this probably shouldn't have been happening.

This morning, I have the same result of a standard `dotnet restore` ...
```
warn : The file 'C:\Users\guard\AppData\Local\NuGet\v3-cache\
1056d04834fe87fc73aefc5ef9e9970721403410$_api.nuget.org_v3-flatcontainer_\
nupkg_WindowsAzure.Storage.6.2.2-preview.dat' is corrupt.
error: End of Central Directory record could not be found.
```

I'm going to kill the package cache and see how it goes.

**Comment by davidfowl** [comment]
The cache should never make restore fail

/cc @emgarten

**Comment by ToddThomson** [comment]
I have tried to get the cli-samples to work. The "basic" sample will restore and run. The web samples will not restore. I get the same "corrupt" messages and just plain failed downloads:

```
info : Retrying 'FindPackagesByIdAsync' for source https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/.
A task was canceled.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/.
A task was canceled.
info : Failed to download package from 'https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/system.collections.c
oncurrent/4.0.12-rc2-23805/system.collections.concurrent.4.0.12-rc2-23805.nupkg'.
A task was canceled.
info : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/system.collections.conc
urrent/4.0.11-rc2-23727/system.collections.concurrent.4.0.11-rc2-23727.nupkg'.
A task was canceled.
info : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/system.appcontext/4.1.0
-rc2-23727/system.appcontext.4.1.0-rc2-23727.nupkg'.
A task was canceled.
info : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/system.reflection.typee
xtensions/4.1.0-rc2-23727/system.reflection.typeextensions.4.1.0-rc2-23727.nupkg'.
A task was canceled.
info : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/system.text.encoding/4.
0.11-rc2-23727/system.text.encoding.4.0.11-rc2-23727.nupkg'.
A task was canceled.
info : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.netcore.runti
me/1.0.1-rc2-23727/microsoft.netcore.runtime.1.0.1-rc2-23727.nupkg'.
A task was canceled.
```

**Comment by GuardRex** [comment]
Dumped cache at ...
```
C:\Users\guard\.nuget\packages
C:\Users\guard\AppData\Local\NuGet\v3-cache
C:\Users\guard\AppData\Local\dnu\cache
```
(If this is relevant ...) I'm still seeing the word "CACHE" on some of these packages during restore ...
```
info : CACHE https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/
microsoft.aspnetcore.tooling.razor/
index.json
```
... and hit another one ...
```
warn : The file 'C:\Users\guard\AppData\Local\NuGet\v3-cache\
a3f7996bd74fb18cce048733dd07221a97fca25d$spnetcidev_api_v3_flatcontainer_\
nupkg_System.Text.Encoding.Extensions.4.0.11-rc2-23805.dat' is corrupt.
error: End of Central Directory record could not be found.
log  : Failed to download package from 'https://api.nuget.org/v3-flatcontainer/
system.dynamic.runtime/4.0.0/system.dynamic.runtime.4.0.0.nupkg'.
A task was canceled.
```
Win10 x64 using VS Code
`dotnet cli` version: 1.0.0.001306 beta
Running `dotnet restore` as a VS Code Task, so I'm watching the restore in the VS Code Output. Tried yesterday running `dotnet restore` from cmd prompt ... same general result: "... End of Central Directory record ..." eventually hit on a package. It's frequently a different package that it chokes on each time I restore.
```json
"dependencies": {
    "Microsoft.AspNetCore.Antiforgery": "1.0.0-*",
    "Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.Razor": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Tooling.Razor": "1.0.0-*",
    "Microsoft.Extensions.Configuration": "1.0.0-*",
    "System.Runtime.Serialization.Primitives": "4.1.0-*",
    "NETStandard.Library": "1.0.0-*",
    "System.Net.Http": "4.0.1-*",
    "System.Net.Security": "4.0.0-*",
    "System.Net.Sockets": "4.1.0-*",
    "WindowsAzure.Storage": "6.2.2-preview",
    "Microsoft.Extensions.Logging": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Logging.Tracesource": "1.0.0-*",
    "Microsoft.Extensions.DependencyModel": "1.0.0-dev-001200"
},
```
```json
"frameworks": {
    "netstandardapp1.5": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
```
... and that was working yesterday morning ... restore, publish, running on IIS 8.5. It stopped restoring sometime yesterday afternoon. I tried clearing package caches yesterday (and again this morning), but I can't shake this fever off.
```xml
<packageSources>
  <clear />
  <add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
  <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
  <add key="dotnet-cli" value="https://www.myget.org/F/dotnet-cli/api/v3/index.json" />
  <add key="AspNetvNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
</packageSources>
```

**Comment by ToddThomson** [comment]
I installed dotnet cli with an msi. Is there a going to be an "update-self" command?

**Comment by GuardRex** [comment]
@ToddThomson They said "no" to that: https://github.com/dotnet/cli/issues/511

**Comment by GuardRex** [comment]
I tried to go back from ...
```json
"frameworks": {
    "netstandardapp1.5": {
        "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
},
```
... to ...
```json
"frameworks": {
    "dnxcore50": {
        "imports": "portable-net45+win8"
    }
},
```
... and another one (diff package, too) ... so that's apparently not the problem.
```
warn : The file 'C:\Users\guard\AppData\Local\NuGet\v3-cache\
a3f7996bd74fb18cce048733dd07221a97fca25d$spnetcidev_api_v3_flatcontainer_\
nupkg_System.IO.FileSystem.4.0.1-rc2-23727.dat' is corrupt.
error: End of Central Directory record could not be found.
```
I'm broken! "Help Me, Obi-Wan Kenobi. You're My Only Hope"
![helpme](https://cloud.githubusercontent.com/assets/1622880/13015362/7ed2ce1e-d16d-11e5-8a36-05059cc8fa1a.gif)

**Comment by ToddThomson** [comment]
@GuardRex I guess with the dnx to dotnet cli change there was a management/philosophy change too. I don't mind having the dotnet CLI delivered by an MSI on Windows.

**Comment by ToddThomson** [comment]
Ok. I got the cli-sample HelloWeb to work ( restore, build, run) by first deleting the project.lock file! I did bring the cli-samples up with vs2015 first so maybe that was causing the grief.

Please note that "dotnet run" produces no error messages if the "build" step errors.

**Comment by blackdwarf** [comment]
I tried to get the cli-samples to work on Ubuntu 14.04 machine. The restore of `HelloMvc` failed with the following error:

```console
An error occurred while sending the request.
error: Unable to load package 'Microsoft.AspNetCore.IISPlatformHandler'.
info :   OK https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading.timer/4.0.1-rc3-23811/system.threading.timer.4.0.1-rc3-23811.nupkg 4649ms
*** Error in `/usr/share/dotnet-nightly/bin/corerun': free(): invalid pointer: 0x00007f79e3297540 ***
```

The last bit I'm pretty sure should not be happening. 

The CLI bits are the latest, updated via apt-get prior to running `dotnet restore`.

**Comment by GuardRex** [comment]
I run restore, it breaks on this ...
```
warn : The file 'C:\Users\guard\AppData\Local\NuGet\v3-cache\
a3f7996bd74fb18cce048733dd07221a97fca25d$spnetcidev_api_v3_flatcontainer_\
nupkg_System.Threading.Tasks.Parallel.4.0.1-rc2-23805.dat' is corrupt.
error: End of Central Directory record could not be found.
```
I re-run restore a few times, it breaks each time within a minute on that `.dat` file.

I manually delete the `a3f7996bd74fb18cce048733dd07221a97fca25d` folder in `C:\Users\guard\AppData\Local\NuGet\v3-cache`. I re-run restore, it runs quite a long time (several minutes), then breaks on this ...
```
info :   OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracing/4.0.20/
system.diagnostics.tracing.4.0.20.nupkg 408221ms
warn : The file 'C:\Users\guard\AppData\Local\NuGet\v3-cache\
1056d04834fe87fc73aefc5ef9e9970721403410$_api.nuget.org_v3-flatcontainer_\
nupkg_System.Diagnostics.Tracing.4.0.20.dat' is corrupt.
error: End of Central Directory record could not be found.
```
... I go look and `a3f7996bd74fb18cce048733dd07221a97fca25d` folder is there ... inside `nupkg_System.Threading.Tasks.Parallel.4.0.1-rc2-23805.dat` is there ... perhaps downloaded correctly on this pass.

I'm going to do the same thing, but this time, I'm going to only delete the `nupkg_System.Diagnostics.Tracing.4.0.20.dat` and try restore again.

**Comment by GuardRex** [comment]
It ran for several minutes and briefly paused on this ...
```
log  : Failed to download package from 'https://www.myget.org/F/aspnetcidev/api/v3/
flatcontainer/microsoft.csharp/4.0.1-rc2-23805/
microsoft.csharp.4.0.1-rc2-23805.nupkg'.
Error while copying content to a stream.
```
... and ...
```
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.linq.expressions/4.0.0/
system.linq.expressions.4.0.0.nupkg
log  : Failed to download package from 'https://dotnet.myget.org/F/
dotnet-core/api/v3/flatcontainer/system.runtime.handles/4.0.0/
system.runtime.handles.4.0.0.nupkg'.
Error while copying content to a stream.
```
... but it continued to restore and finally completed ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/13017755/fecabe62-d17a-11e5-8f69-25e177b3b8e2.PNG)

... It publishes ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/13017760/0544281e-d17b-11e5-814a-a9570e08742b.PNG)

... that was rough.

**Comment by ToddThomson** [comment]
@GuardRex I noticed that you are using vscode with dotnet cli. I would like to try this myself, but am not familiar with how to set this up. Can you share?

**Comment by GuardRex** [comment]
@ToddThomson Here's a gist for my `tasks.json` file, which you drop into the `.vscode` folder of the app. You can see here that I'm using the arguments with a dropped task name to fire off the commands. https://gist.github.com/GuardRex/19868ad5dc0a8c5f9473

To run a command, I just hit "F1" on the keyboard, "T" for tasks, select "Tasks: Run Task," then click the command that I want to run. There is probably a faster way to trigger them, but I'm a bit of a :monkey: and not too smart. I usually just randomly bang the keys on the keyboard until my app runs! :smile:

**Comment by GuardRex** [comment]
This has all been cleared up by clearing the package cache and moving on with new `dotnet cli` install(s).

@ToddThomson Just to wrap our quick-chat on VS Code ... check this out ... https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks

**Comment by natemcmaster** [comment]
The issue here appears to be with NuGet. See https://github.com/NuGet/Home/issues/2133
