### ISSUE TITLE
Unable to embed file as resource in assembly

### ISSUE THREAD

**Issue by soeron** [dotnet/cli#1383]
Greetings,

I am experimenting with dotnet cli and trying to embed a file as resource in the assembly.
In project.json I use:
`"resource": [ "file.txt" ]`
The expected result is that the resource should be embedded in the assembly.
But the dotnet build command fails with error message CS2001: Source file 'PATH\file.txt' could not be found.

When looking into generated dotnet-compile.rsp file I find this line:
`--resource:"D:\Projects\Visual Studio\Solution With Space In Name\src\ProjectName\file.txt,ProjectName.file.txt"`

Note that quotes are present and there is no problem with the path with spaces in it.
Further on looking in dotnet-compile-csc.rsp there is a line at the end like this:

`-resource:D:\Projects\Visual Studio\Solution With Space In Name\src\ProjectName\file.txt,ProjectName.file.txt`

Note that the quotes are trimmed, and the path with spaces is not handled properly.

If I add quotes manually and use `csc @dotnet-compile-csc.rsp` the error becomes: error CS1566: Error reading resource and -- 'Could not find file ...'

Now the problem here is
> ,ProjectName.file.txt

If I remove this part then compilation with `csc @dotnet-compile.rsp` then everything passes and after inspecting the assembly the file is embedded as resource.

The fix for this behavior is relatively easy:

In file `commands/dotnet-compile/Compiler.cs` at AddNonCultureResources the else block on line 76-80
`
else
{
    compilerArgs.Add($"--resource:\"{resgenFile.InputFile},{Path.GetFileName(resgenFile.MetadataName)}\"");
}
`
should be changed like this:
`
else
{
    compilerArgs.Add($"--resource:\"{resgenFile.InputFile}\",{Path.GetFileName(resgenFile.MetadataName)}");
}
`
The block before this else handles .Resx files.

The second change that needs to be done is in `commands/dotnet-compile-csc/Program.cs` in the Run method on line 104 which looks like this:
`allArgs.AddRange(resources.Select(resource => $"-resource:{resource.Trim('"')}"));`
and should be like this:
`allArgs.AddRange(resources.Select(resource => $"-resource:\"{resource}\""));`

There are missing quotes that can handle spaces in the path.

I am using W10, VS2015, and dotnet v1.0.0.001297 which is the latest at the moment of writing.

Edit: fixing proposed fixes after more investigation.

**Comment by soeron** [comment]
Greetings again,
With dotnet new and targeting dnxcore50 I was able to embed the file as resource, but dnx451 fails.

**Comment by shahid-pk** [comment]
@soeron dnx451 support just got in today and may be is still not included in the recent installers. its net451 support actually but i think they are the same now.

**Comment by soeron** [comment]
Greetings Again,
A little update on the issue: installed dotnet v.1.0.0.001306
The problem is there too. But I managed to edit the dotnet.dll assembly and fix the problem for me. The fixes are almost the same as I described in the first post.
The problem comes from escaping spaces in paths in windows environment and targeting dnx451.

**Comment by brthor** [comment]
Also tracked here, #1280 . going to close this as a duplicate, but thanks for the great investigation into this @soeron 

I'll work on adding a test for this case and check in a fix this morning.
