### ISSUE TITLE
Use ".NET" instead of "dotnet" in all user facing text 

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#1388]
To keep our web search relevancy clean we should only ever use “dotnet” is when specifically referring to “dotnet.exe”. In all user facing text we should refer to .NET as ".NET" or ".NET Core"

We should update the .NET Core MSI accordingly:

![dotnet_cli_installer](https://cloud.githubusercontent.com/assets/1874516/13017802/3f3a136c-d17b-11e5-848d-142e35e4b79c.png)

**Comment by robmen** [comment]
@danroth27 can you provide the exact text you want displayed? That should allow us to do one update.

**Comment by danroth27** [comment]
@blackdwarf @richlander 

I believe the MSI should be named "Microsoft .NET Core for Windows"

**Comment by blackdwarf** [comment]
@danroth27 it needs to include either the "SDK" or "CLI tools" somewhere in there, since you are getting slightly more. We will have the full name this week, I believe, so I will update this issue with it.

**Comment by piotrpMSFT** [comment]
#1891 is fixing the branding [dotnet --> .NET and the logo change]. Please take a look and let me know if we need any other changes.

**Comment by piotrpMSFT** [comment]
@danroth27 the Windows Installer now reads:

`Microsoft .NET CLI for Windows ($(var.DisplayVersion) $(var.ReleaseSuffix))`

I think we should reserve the .NET Core branding for a package that does not include the SDK.

**Comment by danroth27** [comment]
As long as it says .NET instead of dotnet in the branding than I am happy :smile:.

**Comment by piotrpMSFT** [comment]
fixed by #1891
