### ISSUE TITLE
Dotnet CLI and compatibility with .net 451

### ISSUE THREAD

**Issue by ToddThomson** [dotnet/cli#1389]
I have successfully restored, built and run the basic web sample (from cli-samples repo).
If I modify the project.json file to add 

"frameworks": {
        "net45":{},
        "dnxcore50": { }
    }

I then need to run dotnet restore. This fails with a number of compatibility errors:

PS C:\src\temp\dotnetcli\basic> dotnet restore
info : Restoring packages for C:\src\temp\dotnetcli\basic\project.json...
info : Installing runtime.win7.System.Net.Primitives 4.0.11-rc2-23727.
info : Installing runtime.win7.System.Runtime.Extensions 4.1.0-rc2-23727.
error: Microsoft.Win32.Primitives 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.AppContext 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.Console 4.0.0-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.Diagnostics.Process 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.Globalization.Calendars 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.IO.FileSystem 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.IO.FileSystem.Primitives 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.Net.Sockets 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.Reflection.TypeExtensions 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: System.Runtime.Handles 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1.
error: Some packages are not compatible with DNX,Version=v4.5.1.
error: Microsoft.Win32.Primitives 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.AppContext 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.Console 4.0.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.Diagnostics.Process 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.Globalization.Calendars 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.IO.FileSystem 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.IO.FileSystem.Primitives 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.Net.Sockets 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.Reflection.TypeExtensions 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: System.Runtime.Handles 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x64).
error: Some packages are not compatible with DNX,Version=v4.5.1 (win7-x64).
error: Microsoft.Win32.Primitives 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.AppContext 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.Console 4.0.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.Diagnostics.Process 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.Globalization.Calendars 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.IO.FileSystem 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.IO.FileSystem.Primitives 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.Net.Sockets 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.Reflection.TypeExtensions 4.1.0-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: System.Runtime.Handles 4.0.1-rc2-23727 is not compatible with DNX,Version=v4.5.1 (win7-x86).
error: Some packages are not compatible with DNX,Version=v4.5.1 (win7-x86).
info : Committing restore...
info : Restore failed in 70687ms.
PS C:\src\temp\dotnetcli\basic>

**Comment by ToddThomson** [comment]
OK. If you remove the "dnxcore50" from the project.json file:

```
"dependencies": {
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
        "Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*"
    },
    "frameworks": {
        "net451":{}
    },
```
The basic web cli sample will restore, build and run. 

It is worth noting that when removing "dnxcore50", the restore operation completes in a reasonable amount of time ( around 5 seconds ). This is in comparison to 10 or more minutes for the "dnxcore50" restore.

Now to see if I can somehow get debugging to work...

**Comment by davidfowl** [comment]
Yes this is by design. You should reference NetStandard.Library in dnxcore50, see the sampels at https://github.com/aspnet/cli-samples
