### ISSUE TITLE
dotnet-publish not publish system dependency

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/cli#1390]
Hi,

Here is  what i did:
1. create a new folder, then run "dotnet new"
2. open the project.json created by "dotnet new".
3. remove "NETStandard.Library" from dependencies, since i notice the NetStandard.library contains lots of other .dll by default.
4. add "System.Runtime" and "System.Console" to dependencies, since these are the 2 dlls that the hellowwold project actual required.
5. "dotnet restore"
6. "dotnet publish"
7. after "dotnet publish", i noticed the system.runtime and system.console dlls are not copied to the output folder. the output folder only has the helloword.exe/dll/pdb and hostpolicy.dll

Is this behavior correct?

Thanks,
Ting

**Comment by davidfowl** [comment]
You're likely looking in the wrong folder. Try specifying the output path and looking in there.

**Comment by TingluoHuang** [comment]
@davidfowl i played with it a little bit more. looks like if my project.json take dependencies on "system.runtime":"4.0.20", then dotnet publish will copy that system.runtime.dll to output folder. however, when i take dependencies on "4.1.0-rc3-23803", system.runtime.dll is not been copied.

**Comment by davidfowl** [comment]
Try using the standard library instead of referencing individual packages.

**Comment by TingluoHuang** [comment]
@davidfowl  i am sure the NETStandlibrary works fine, but i don't want to package any library that i am not using. is this scenario not support?

**Comment by blackdwarf** [comment]
Given the oldness of the issue as well as the answer, I am going to go ahead and close this. If more info is needed, please reopen.
