### ISSUE TITLE
Project model server is throwing an invalid cast exception open the Microsoft.DotNet.Cli sln

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#1391]
Clone the DotNet.Cli repository
Open the Microsoft.DotNet.Cli.sln file

Restore, intellisense doesn't work because the project model server is returning the following global error:
  "Message": "Unable to cast object of type 'Microsoft.DotNet.ProjectModel.LibraryDescription' to type 'Microsoft.DotNet.ProjectModel.ProjectDescription'.",

@troydai

**Comment by troydai** [comment]
It happened when we try to get exports when lock file is missing. The `LibraryDescription` created with type `Project` but not in `ProjectDescription` type. Working on a fix now.

**Comment by moozzyk** [comment]
dupe of #1288, #1380?

**Comment by troydai** [comment]
Proposed fix this here: https://github.com/dotnet/cli/tree/troy/1391

I'm adding a tests to cover it.

**Comment by davidfowl** [comment]
Ah I thought you merged it

**Comment by troydai** [comment]
No. I didn't. I can send a PR let the CI spin first.

**Comment by troydai** [comment]
Fixed in cf2cf83ff36d637008033b04980266c2baf36274
