### ISSUE TITLE
Publish break binding redirect.

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1394]
The `dotnet-publish` doesn’t create config for binding redirect. That essentially break the application where there are multiple versions of same dependencies are referenced.

/cc @pakrym

**Comment by davidfowl** [comment]
The config file should be part of the runtime assets that get copied to output

**Comment by pakrym** [comment]
This requires LibraryExporter to know what are we building now, and add .config, .deps and other runtime outputs only to one library.

**Comment by davidfowl** [comment]
That's already the case. Did your change break that? That was the point of runtime assets and get build outputs...

**Comment by blackdwarf** [comment]
@troydai @pakrym what is the status of this?

**Comment by troydai** [comment]
It is fixed in latest dotnet build. Just verified. I close this one.
