### ISSUE TITLE
The Shoreham Hotel in Manhattan is on .NET Core

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1399]
I just updated the Shoreham Hotel in NYC to .NET Core `netstandardapp1.5`. You're doing a great job and your hard work is paying off for customers. Props to the .NET teams and community! 

:tada: :balloon: Thanks and congratulations! :balloon: :tada:

![capture](https://cloud.githubusercontent.com/assets/1622880/13038561/7a8e16dc-d349-11e5-914e-a8b8da20ef25.PNG)

**Comment by shahid-pk** [comment]
this could be a nice article :smile:
