### ISSUE TITLE
Make Release the default run configuartion

### ISSUE THREAD

**Issue by benaadams** [dotnet/cli#1403]
Rather than debug

So if someone types `dotnet run` it is in release mode; if you run it in a debugger it can be Debug mode. If you run it as `dotnet run --configuration Debug` it can be in debug mode if you want to attach a debugger later; but by default it should be `dotnet run --configuration Release`

Else people will get the wrong idea about the performance or forget to use `--configuration Release`

e.g. https://github.com/atemerev/skynet/pull/40

**Comment by GuardRex** [comment]
ditto on `dotnet publish` ... the default is `Debug`

**Comment by ctolkien** [comment]
:+1:

**Comment by piotrpMSFT** [comment]
@davidfowl you felt strongly debug should be default across the board. Thoughts?

**Comment by davidfowl** [comment]
dotnet run is a dev time thing...

**Comment by benaadams** [comment]
Maybe just publish then? (If its not the default as @GuardRex suggests)

**Comment by GuardRex** [comment]
Cross-referencing the discussion on Development vs. Production: https://github.com/dotnet/cli/issues/1403

**Comment by piotrpMSFT** [comment]
Defaults are aligned with csproj at this point.

**Comment by PureKrome** [comment]
@piotrpMSFT Hi :wave: can you please elaborate on what you mean by this:

>Defaults are aligned with csproj

do you mean that there's a setting in your csproj files or something?
