### ISSUE TITLE
command to list dependencies for a project

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/cli#1404]
This is similar to what `dnu list` did. Are there plans to do this?

**Comment by blackdwarf** [comment]
@tugberkugurlu we are looking into it, but maybe we would expose it differently.

**Comment by tugberkugurlu** [comment]
could this be up for grabs?

**Comment by blackdwarf** [comment]
@tugberkugurlu I believe this will be covered by the newly proposed `dotnet ref` command. See #4521. 

Will close this issue. Please comment on #4521. Thanks!
