### ISSUE TITLE
[Docs] Import property in project.json

### ISSUE THREAD

**Issue by aL3891** [dotnet/cli#1407]
Hello there, 
i'm working on the some reference docs for proejct json over at the core-docs repo. i've been looking though the code to find all the properties that can be used and what they do, but one i cant find is the "import" property. 

I can see it being used in lots of project.jsons but i cant find any references to it in the code, am i just not looking in the right places or is this property no longer used? if anyone has any pointers i'd be grateful :)

**Comment by aL3891** [comment]
Anyone?

**Comment by GuardRex** [comment]
http://docs.nuget.org/consume/projectjson-format

**Comment by aL3891** [comment]
I'm aware of that page. My question is if it is still supported since i cant didn't any reference to it in the [cli] code, and if so, where its implemented. The docs on nuget also don't provide a lot of information on what can be put in there.

**Comment by GuardRex** [comment]
yes ... https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json

**Comment by aL3891** [comment]
Well again, as i said in my original post, i can see it being used in various project.json files, but i have not found any references to it in the cli code, hence my question.

**Comment by GuardRex** [comment]
Did you check in https://github.com/dotnet/corert

**Comment by aL3891** [comment]
Not yet, are you saying that is where its being used?

**Comment by GuardRex** [comment]
Looks favorable ... https://github.com/dotnet/corert/blob/7ae0ee55ca2eaaa62fb7e3fdca217b1aac337598/src/System.Private.CoreLib/src/MembersMustExist.AnalyzerData#L81

**Comment by aL3891** [comment]
Are you sure you linked to the correct file..? But sure, i can take a look in that repo..
In any case, based on the description of this property, id expect it to be used elsewhere than corert, so if anyone has any insights with regards to this property please feel free to fill them in.

**Comment by shahid-pk** [comment]
it is in nuget i have found its tests here https://github.com/NuGet/NuGet.Client/blob/4094086a0b6588dbc9c21dbd3ac8efecf93dac80/test/NuGet.Core.Tests/NuGet.ProjectModel.Test/ImportFrameworkTest.cs

**Comment by GuardRex** [comment]
Looks more NuGet-ish ... check these out ...

https://github.com/NuGetArchive/NuGet3/pull/42

https://github.com/NuGetArchive/NuGet3/blob/061a6365fd65fc5c18f218c3373f08242a043790/src/NuGet.Frameworks/DefaultPortableFrameworkMappings.cs

I'm guessing along and checking, but I don't see anyone else trying to help you strike gold.

The ID's are there, so it looks NuGet-ish in terms of where it is in the code.

**Comment by shahid-pk** [comment]
@GuardRex  nice timing :smile:

**Comment by GuardRex** [comment]
@shahid-pk Truly ... It's a hunt in the wild.

**Comment by aL3891** [comment]
Thanks, i'll check it out. it still seems a little strange to me though. From what i understand, cli produces packages with dotnet-pack, and there are no references to "imports" there. Either they havent ported it over yet or its deprecated..

i'll just leave it in for now until we can get some official word.

**Comment by blackdwarf** [comment]
@aL3891 you are reffering to the "import" property under "frameworks"?

**Comment by aL3891** [comment]
Yes, thats the one, @blackdwarf

**Comment by blackdwarf** [comment]
@aL3891 that one is used to essentially tell NuGet that assembiles from that framework will work in the target framework. So:

```json
{
    "frameworks": {
        "dnxcore50": {
           "import": "somethingelse"
        }
    }
}
```
Tells Nuget that any package that is for "somethingelse" will work for your target of "dnxcore".

**Comment by aL3891** [comment]
i see, and "somethingelse" can be anything? or only valid tfms?
Also, how come this not found in dotnet-pack? (just curious)

**Comment by blackdwarf** [comment]
@aL3891 only valid stuff. I don't undertand the `dotnet pack` question?

**Comment by aL3891** [comment]
My question is why there is no reference to the import property (as far as i've been able to find) in the source code for `dotnet-pack` or anywhere else in the cli repo. That is why i wondered if this was still supported or not.

**Comment by blackdwarf** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
