### ISSUE TITLE
Emit warning in CoreHost when file referenced in 'deps' cannot be found

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1409]
When a file referenced in the `deps` file cannot be found, it would be extremely useful if the host could emit a warning. Right now, you just get an assembly load error and you have to scan the `deps` file to diagnose it

**Comment by schellap** [comment]
@anurse should this be a fail fast instead? When you say warning, do you mean continue to run the app but emit a visible message or do you mean to see this tracing on?

**Comment by anurse** [comment]
Yeah, I think a fail-fast might be appropriate here. Effectively it's a preemptive assembly load failure. If the app ever tries to load that assembly, it's going to fail. In theory, if the app never loads the assembly it's not a problem, but I think that's a pretty odd case. Thoughts @davidfowl @pakrym ?

**Comment by pakrym** [comment]
If it's in `deps` it should be resolved, i'm for fail-fast.

**Comment by schellap** [comment]
Fixed by https://github.com/dotnet/cli/pull/3020
Files not resolved will fail fast.
