### ISSUE TITLE
Auto add all reference assemblies for PCL targets

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1413]
For PCL targets, the user should never have to add a reference assembly and is more consistent with what MSBUILD does for these types of projects.

**Comment by scottdorman** [comment]
Yes, that would be extremely helpful and is definitely more consistent with what happens for `csproj` based projects.

**Comment by piotrpMSFT** [comment]
@nguerrera it seems like this belongs in `sdk`?

**Comment by nguerrera** [comment]
Is this still a priority? We have done no testing of targeting PCL profiles using the SDK.

**Comment by onovotny** [comment]
IMO, we must be able to cross-compile to any and all targets for cross-compiling to be considered complete. It has to be a replacement for having a multi-headed project.

**Comment by nguerrera** [comment]
cc @srivatsn, @davkean

**Comment by davidfowl** [comment]
Does this work in msbuild land?

**Comment by davkean** [comment]
Yeah, we should do this. I reckon that we just reference all assemblies by default for all frameworks, unless opt'd out ("desktop")

**Comment by piotrpMSFT** [comment]
Moved to SDK
