### ISSUE TITLE
Error: No HOME path available

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1422]
When attempting to upload build artifacts to Azure during VSO builds we see `Error: No HOME path available` on Windows. This is because the Azure x-plat CLI is not meant to be used within PowerShell. PowerShell provides first-class Azure CmdLets which are recommended. 

Given that our scripts are currently built around the CLI I'm going to try to work around this issue by setting $env:HOME on Windows CI builds. If this proves to be a rats nest, however, we should consider moving to PS CmdLets.

**Comment by blackdwarf** [comment]
@piotrpMSFT is this solved? Should we close?
