### ISSUE TITLE
CentOS Release Builds are built as Debug

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1425]
CentOS VSO Release builds are interpreting their Configuration as Debug. This does not repro on our Jenkins PR nodes. I suspect it is something in ci_build.sh, likely here:

````
while [[ $# > 0 ]]; do
    lowerI="$(echo $1 | awk '{print tolower($0)}')"
    case $lowerI in
        "release" | "--release")
            export CONFIGURATION=Release
            ;;
        "debug" | "--debug")
            export CONFIGURATION=Debug
            ;;
````

The variable is passed to the script as `Release` so perhaps local configuration [locale, etc.] is preventing it from being interpreted correctly.

**Comment by blackdwarf** [comment]
@piotrpMSFT who should be assigned to fix this?

**Comment by piotrpMSFT** [comment]
Fixed
