### ISSUE TITLE
Dependency specified 'xxx' but ended with 'yyy'

### ISSUE THREAD

**Issue by cechovsky** [dotnet/cli#1427]
I have a lot of problems to add references/nuget packages to my project (see screenshot)

![image](https://cloud.githubusercontent.com/assets/2878125/13082750/42921a0a-d4d2-11e5-8fc5-42844c320c2d.png)

How could I fix it. Do I need to edit project.lock.json file and replace wrong dependencies or there is more appropriate way?

**Comment by davidfowl** [comment]
Do you have a single project?

**Comment by cechovsky** [comment]
No I have multiple projects in one solution. I deal with this issue very often.

**Comment by davidfowl** [comment]
There's a known issue in DNX where warnings show up incorrectly when you have a project reference with the same dependency.

**Comment by cechovsky** [comment]
Do you know how could I solve this issue? Or should I ignore it? 

I'm trying to migrate older .NET 4.5 project to new .NET Core solution a I have a lot of more critical issues. The most common is references. I reference some project but I can't use classes from it.

**Comment by livarcocc** [comment]
Is this still happening? If so, please re-activate and if possible, with a repro.
