### ISSUE TITLE
dotnet crossgen support

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#1437]
The "dotnet" command infrastructure should provision for allowing the user to crossgen the compiled binary or output of publish.

**Comment by davidfowl** [comment]
I have a PR for this as part of publish but it needs some love

**Comment by gkhanna79** [comment]
Thanks @davidfowl. Please keep @JohnChen0, @jkotas and me in loop of the PR.

**Comment by Petermarcu** [comment]
@davidfowl did you even finish the PR?

**Comment by Petermarcu** [comment]
Moving this into 2.1 so it isn't lost. This request has come up many many times. Let's see what we can do.

**Comment by agocke** [comment]
I'll second this. It's very difficult to both find the list of assemblies we need for shared libraries and find the proper crossgen.exe.

**Comment by tmds** [comment]
This feature is definitely interesting for [serverless](https://martinfowler.com/articles/serverless.html). A process doesn't live long, it is launched for each _function_ invocation. So the cost of JIT can be high compared to the actual work being done.

**Comment by jkotas** [comment]
https://github.com/dotnet/sdk/issues/593 is duplicate. Does this feature request belong to SDK or CLI repos? I would think that it should be SDK.

BTW: SDK has a bunch of crossgen plumbing already: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets . It is used by `dotnet store` https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store feature.

**Comment by livarcocc** [comment]
This belongs here in the CLI. The SDK repo will be merged with the CLI repo in the medium feature. Having said that, this did not make the 2.1 timeline. As such, I am moving it to the backlog.

**Comment by dasMulli** [comment]
There may be two separate concerns here:

1. Have a `dotnet crossgen` command (global tool?) that can be used on any assembly. Could be run on portable applications as part of a deployment process on a target server (so the r2r assemblies match the current version of the runtime).
2. Crossgen on publish(/build) as part of the build process.

**Comment by jkotas** [comment]
I have just learned that [ILLinker](https://github.com/dotnet/core/blob/master/samples/linker-instructions.md) has its own crossgen targets that pretty much does "crossgen on publish". It was introduced in https://github.com/mono/linker/pull/192 .

**Comment by sbomer** [comment]
mono/linker has the ability to run crossgen: https://github.com/mono/linker/pull/192. This could probably be used as a starting point. https://github.com/dotnet/sdk/issues/1814 may also be relevant whenever this is implemented.

**Comment by zamont** [comment]
@fadimounir can you self-assign?

**Comment by fadimounir** [comment]
Crossgen has been integrated with the SDK starting from the 3.0 Preview 5 release, and it is now possible to compile assemblies into readytorun images during publishing

**Comment by tmds** [comment]
@fadimounir awesome! Is there some documentation on how to do this?

**Comment by fadimounir** [comment]
@tmds you can enable crossgen by setting the PublishReadyToRun property (either command line or in your project file). Example command line:
```console
dotnet publish -r win10-x64 /p:PublishReadyToRun=true
```
For Preview 5, it only works for self-contained applications. Also, you have to provide a target RID.

@richlander is putting together some documentation/blog with more info on the things that got enabled in Preview 5. Richard, could you please point @tmds to your doc?

**Comment by dasMulli** [comment]
```
/usr/local/share/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(247,5): error NETSDK1095: Optimizing assemblies for performance is not supported for the selected target platform or architecture. Please verify you are publishing a self-contained application using a supported runtime identifier, or set the ReadyToRun property to false. [/Users/martin/tmp/testcons/testcons.csproj]
```

1. Thanks for enabling this.
2. Please make it actually cross-crossgen :) is there a tracking issue for this? e.g. crossgen for different platforms/architecures - e.g. optimising for ARM when compiling on macOS / windows

**Comment by fadimounir** [comment]
@dasMulli We currently don't support cross-platform crossgen. There are some cross-architecture scenarios that we support though. You can compile for ARM from Windows and Linux.
Which platform/architecture are you trying to target?

**Comment by dasMulli** [comment]
That's fine (for now?), just wanted to ask, there's no immediate need.
Scenarios i can see is crossgen for *nix on windows build agents (not everyone uses linux build agents, esp. when self-hosting or mixed solutions with also some UI integration testing going on) and crossgen for edge devices (ARM/ARM64) from x64 agents.

**Comment by fadimounir** [comment]
Thanks for the feedback regarding cross-platform.
Now, you can compile for arm/arm64 from a x64 machine, as long as it’s the same platform (windows x64 to compile for windows arm/arm64, and Linux x64 to compile for Linux arm/arm64)

**Comment by Tragetaschen** [comment]
I would love cross-platform crossgen: I'm developing on Windows x64 and deploy with `-r linux-arm`. By using WSL, I was able to build an R2R version, which reduced startup time from 23s to 17s. However, this pretty much messed up my restore state and doesn't work with VS being open
