### ISSUE TITLE
Update our WiX tools to 3.10.2 and do not use v.3.x NuGet packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#1445]
See https://github.com/wixtoolset/issues/issues/5213#issuecomment-184901098

From @barnson

> Note that there are no official WiX v3.x NuGet packages. You should avoid them in general.

> BTW, it's important that you use WiX v3.10.2 because it mitigates DLL hijacking vulnerabilities in Windows.

We should update our WiX tools dependencies and stop using the unofficial NuGet packages.

**Comment by Sridhar-MS** [comment]
Fixed https://github.com/dotnet/cli/pull/1522
