### ISSUE TITLE
Define platform support matrix for CLI

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1446]
Our support matrix is currently defined by where we run CI. We need to make sure that the matrix covers all the places where our partners expect to be able to ship. In particular, what versions of Windows do we intend to support? Win7?

**Comment by blackdwarf** [comment]
Win7 SP1 should be supported, yes.

**Comment by piotrpMSFT** [comment]
@blackdwarf what is the full matrix?

**Comment by blackdwarf** [comment]
This is now in PR: #1923 . Some comments on those would be welcome.

**Comment by blackdwarf** [comment]
This is actually done. The OS matrix is in https://github.com/dotnet/core/blob/master/roadmap.md.
