### ISSUE TITLE
.NET CLI binaries all have version '1.0.0.0'

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#1450]
.NET CLI binaries should have a version resource so that it is easy to tell what version people have installed. For example:
PS C:\dd\vs1\src\debugger\concord> filever -v "C:\Program Files\dotnet\bin\dotnet-publish.dll"
--a-- W32i   APP   -         1.0.0.0 shp     32,256 02-01-2016 dotnet-publish.dll
        Language        0x0000 (Language Neutral)
        CharSet         0x04b0 Unicode
        OleSelfRegister Disabled
        FileDescription
        InternalName    dotnet-publish.dll
        OriginalFilenam dotnet-publish.dll
        ProductVersion  1.0.0
        FileVersion     1.0.0.0
        LegalCopyright
        OleSelfRegister Disabled

        VS_FIXEDFILEINFO:
        Signature:      feef04bd
        Struc Ver:      00010000
        FileVer:        00010000:00000000 (1.0:0.0)
        ProdVer:        00010000:00000000 (1.0:0.0)
        FlagMask:       0000003f
        Flags:          00000000
        OS:             00000004 Win32
        FileType:       00000001 App
        SubType:        00000000
        FileDate:       00000000:00000000

dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by davidfowl** [comment]
Old yes yah know what I'm just going to fix this tonight 😀

**Comment by davidfowl** [comment]
Fixed via https://github.com/dotnet/cli/commit/8645031db8b6a62a10071578f4949b7094293bdc. Though we could probably match the MSI version on the file version.

**Comment by piotrpMSFT** [comment]
MSI version has to be special since only the first three parts matter. 

We opted to match the file version == NuGet package version == debian package version == PKG version.

**Comment by davidfowl** [comment]
We still don't set the assembly file version
