### ISSUE TITLE
Integration of xunit tests (xprojs) with visual studio online (TFS)

### ISSUE THREAD

**Issue by ip28** [dotnet/cli#1453]
Hi Team,
I don't see option to configure xunit unit tests for MVC 6 projects (xproj extension) in visual studio online.
I also couldn't find any relevant article explaining the same.
Can you please help me configure unit tests in vso?

![image](https://cloud.githubusercontent.com/assets/8371740/13105837/1d470918-d58b-11e5-93ab-16162159d04b.png)

**Comment by piotrpMSFT** [comment]
Visual Studio integration for DotNet CLI is not ready yet. Let's revisit once it is ready!
