### ISSUE TITLE
Ordering of args in dotnet test affects how they pass through to runner

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1456]
This is easy to repro with a current build:

Inside the cli repo

```
cd test/EndToEnd
dotnet build

dotnet test --configuration debug                                   [SUCCESSFUL]
...

dotnet test -xml somefile.xml --configuration debug      [FAILURE]
error: unknown option: --configuration

```

I expect this is not an issue with test but with the command line parser.

cc @livarcocc @piotrpMSFT

**Comment by livarcocc** [comment]
This is now being handled in VSTEST and we no longer have runner specific parameters in MSBuild world.
