### ISSUE TITLE
Could someone explain what is necessary to build this repo?

### ISSUE THREAD

**Issue by PhilipDaniels** [dotnet/cli#1459]
I have VS2015 installed. Followed the instructions in developer-guide.md. Was told I already have later versions of WebToolsExtensionsVS14.msi and DotNetVersionManager-x64.msi. Installed CMake and added it to the path. Also have git on the path (via Cygwin). Confirmed they both work from a CMD prompt.

Mentioned in the "Building from source" section is "ensure DOTNET_HOME" is set. It is. I also have DNX_HOME, for some reason. They are both set to %USERPROFILE%\.dnx. There is a shedload of packages in there.

Cloned the repo. Ensured I had branch rel/1.0.0 checked out. Ran build.cmd. Very last line it prints "Build succeeded."

Opened the solution in Visual Studio, still, it will not compile. Some projects are marked as unavailable (e.g. Microsoft.DotNet.Runtime because "The project file or web cannot be found") and others seem to be missing loads of dependencies, e.g. src/dotnet shows reference "DNX Core 5.0" not found.

Did I miss something?

**Comment by brthor** [comment]
The build is primarily run from the command line. You did not miss anything.

VS Tooling is on the roadmap as I understand it.

You should have usable binaries now inside `artifacts\{RID}\stage2\bin` where {RID} is dependent on your OS. :smile:

**Comment by PhilipDaniels** [comment]
I do, thanks :-) I am thinking of trying to contribute a new command, but maybe my first pull request will be a slight documentation tweak to make this obvious.

**Comment by davidfowl** [comment]
@PhilipDaniels we're not adding any new commands in the core CLI. We are however working on an extension model so that other tools can plug in.

You can use the DNX tooling or VS code with DNX if you want to get a basic editing experience.

**Comment by piotrpMSFT** [comment]
@PhilipDaniels regarding the confusion from `DOTNET_HOME`, @schellap and I just finished PR #1478  to clean up our docs and code.
