### ISSUE TITLE
DependencyContext should function without preserveCompilationContext: true

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1472]
The dependency context should first try to get the embedded deps file and then fallback to the deps file on disk. When in the latter mode, there's only runtime information, no compile time data.

/cc @pakrym

**Comment by pakrym** [comment]
What about changing format of.Deps file to json, are we still doing it? Or it needs to read csv deps?

**Comment by davidfowl** [comment]
@anurse tells me that someday it's going to change to JSON, in the short term, we can just read the csv file. I'm not sure what the timeline for the format change is.
