### ISSUE TITLE
dotnet-win-x64.latest.exe can't be installed

### ISSUE THREAD

**Issue by OlegKi** [dotnet/cli#1473]
One get the error

![dotnetclierror](https://cloud.githubusercontent.com/assets/249117/13143238/d8979996-d642-11e5-8674-8ebbed323f08.png)

during the installation of the current `dotnet-win-x64.latest.exe` (from https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe, referenced on http://dotnet.github.io/getting-started/). The log files contains very strange error description:

>Error 0x8002000a: Failed to convert version: 1.0.0.1451843354 to DWORD64 for ProductCode: {ACA07EB6-39BD-4125-AE2C-52E644BED1FF}

Probably one uses wrong value of the `ProductVersion` property? It should have the format `major.minor.build` in Windows Installer (see [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370859(v=vs.85).aspx)). The value `1451843354` for the build number looks vary strange too. 

The full log is below
[Microsoft_Dotnet_CLI_for_Windows_(1.0.0.001468_)_20160218131215.log.txt](https://github.com/dotnet/cli/files/136169/Microsoft_Dotnet_CLI_for_Windows_.1.0.0.001468_._20160218131215.log.txt)

In any way it's an error, which I want to report.

**Comment by akoeplinger** [comment]
See https://github.com/dotnet/cli/issues/1401. You need to uninstall the older version of the .NET CLI that you have installed first before installing the new one.

**Comment by OlegKi** [comment]
@akoeplinger : Sorry, but the main goal of my issue is in not the help of the installation of `dotnet-win-x64.latest.exe` on *my computer*. I want to report the bug in the installer. The requirement to uninstall the previous version could not be the standard way. "The official MSI installer" (see text on the "Step 1" on the page http://dotnet.github.io/getting-started/) can't have so dirty errors. Even if the uninstallation is really required and the main installer can't start the uninstallation itself, then it have to display more clear error message as "0x8002000a - Out of present range".

**Comment by akoeplinger** [comment]
Going forward the installer will recognize the older version and uninstall it automatically, so this is only required once because the version format changed.

**Comment by OlegKi** [comment]
@akoeplinger : I'm sorry, but the detection of the old versions and different scenarios of upgrading are basics of Windows Installer technology. The properties `UpgradeCode`, `PackageCode`, `ProductCode`, `UPGRADINGPRODUCTCODE`, tables like `Upgrade` table, actions like `FindRelatedProducts` and many other standard features of Windows Installer technology allows to detect old versions and to implement upgrade typically without uninstalling of the previous versions. (Locked files for example can be easy replaced, because the files can be renamed and moved in another directory.) See [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370579(v=vs.85).aspx) for example the description of the most upgrade scenarios: Minor Upgrades, Small Updates, Major Upgrades. The most of the information is unchanged since more as 15 years. If you would look at the setup of Microsoft Office 2000 (created at 1999), it had all the features already.

I'm absolutely sure that Microsoft is able to create good Dotnet CLI Setup and the described problem is just a bug in one build of the setup. One should just know the problem and fix it.

**Comment by robmen** [comment]
@OlegKi you are fundamentally correct. There was an attempt to do play some very complex games with the version number in older builds that ultimately created a string of issues. I believe the version number has been sorted out now so hopefully things will run smoothly now (once the older builds are cleared out).

The moral of the story is don't play around with your version numbers. They are more important to your future self than your current self.

**Comment by OlegKi** [comment]
@robmen : I full agree with you. Everybody, who have experience with setups, knows that playing around with your version numbers is the worst thing, which one can do in setup. 

I posted [the issue](https://github.com/aspnet/Home/issues/1222), where I warned about the flood of renaming of *packages*, which will be used de facto as **id** of the component in a lot of dependencies of existing projects of community. I started seriously work with ASP.NET 5 after publishing RC1 and I could read on the stackoverflow, how many people have problems because one find in Google an code example with the old package name, which is wrong now. Later Microsoft has renamed the product to ASP.NET Core, which is absolutely OK, but one started to rename all *packages* and **even have reset the version number of the packages**. *Such changes are very unfriendly to the community*, to the people, who started porting his productive projects to ASP.NET 5 / ASP.NET Core. One have till today 29 official announcements about *breaking changes* between RC1 and RC2 (see [here](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2+label%3A%22Breaking+change%22)). [The documentation](https://docs.asp.net/en/latest/) is far from to be full and it's really difficult to switch it from RC1 information to RC2 at the day of publishing RC2. Such deep changes are very untypical for RC phase of the project. It's typical that one changes the product name because of marketing purpose, but one didn't renamed the DLLs of the product during RC phase and one never reset there version number. I decided for me to pause my activity in ASP.NET 5 / ASP.NET Core till the end of renaming actions and version changes. Moreover I can't porting the productive projects to ASP.NET Core if [the Roadmap](https://github.com/aspnet/Home/wiki/Roadmap) is changed to TBD and the time schedule is absolutely unknown.

Nevertheless, I find the main ideas of ASP.NET Core very good and I try to help to make it better. I know about problems with the Setup of RC1 (see [the post](https://github.com/aspnet/Home/issues/1085)) and I wish to have better setup for RC2. Only because of that I posted the issue about the problem with the setup of Dotnet CLI. I hope that the problem can be easy fixed.

**Comment by piotrpMSFT** [comment]
@OlegKi thanks for posting. We do appreciate the importance of versioning and are very focused on getting our versioning story right before shipping our first release of CLI. The original CLI versions were generated fairly arbitrarily as we got bits on their feet. We since then invested rather heavily (#668) in aligning our version numbers across installation vectors and providing a great experience between branches. 

Please do let us know if you see issues in installation moving forward. We very much want to have a solid upgrade story by the time we ship!
