### ISSUE TITLE
dotnet-resgen is called before precompile event

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#1474]
I use the [dotnet-fssrgen tool](https://github.com/fsprojects/FsSrGen/tree/master/src/dotnet-fssrgen) to generate a .resx resource file from another file.

This tool runs in the `precompile` script and create a .resx file, but dotnet-resgen runs before the event, so in the final build, my generated resx it's ignored.

``` json
    "tools": {
        "dotnet-fssrgen": { "version": "2.0.0" }
    },

    "scripts": {
        "precompile": [
            "dotnet fssrgen \"%project:Directory%\\..\\FSComp.txt\" \"%project:Directory%\\FSComp.fs\"  \"%project:Directory%\\FSComp.resx\"",
        ],
    },
```

It's possibile to run the dotnet-resgen (called [there](https://github.com/dotnet/cli/blob/61489aef6c8743abdcc6271912f02c949adb2138/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L121) ) after the precompile event?

**Comment by enricosada** [comment]
I think that's a bug because the resgen command is builtin, so should be called after the precompile event to make it easier to create and use generated files

If it's ok, i can implement the fix

**Comment by piotrpMSFT** [comment]
@davidfowl thoughts? This seems right, but we may already have dependencies here...

**Comment by enricosada** [comment]
this issue question is: can i generate a resx file in precompile event?
if not, it's not a problem because i can run `dotnet fssrgen` MANUALLY BEFORE the build, because atm there is not event to subscribe and do that as part of `dotnet build` run

Run it outside precompile is better, because precompile stop incremental compilation. 
but it's manual in a build script. And i need to remember to do it if template file change.

Maybe the root question is:

## how .NET cli handle generated files?

- what's the best way to generate files **each build**? like a t4 template, or a custom tool like fssrgen, or a `cmd /c echo class > file.cs"`
- bonus point: incremental compilation support, like mark source files as generated, and compare it to skip build?
- how can i mark the file as generated so the dotnet build doesnt expect it? ref #1475 . Atm i need to:
   - run the files generator in precompile event but commit empty files. but that doesnt work with resx (this bug).
   - dont commit empty files, and manually run generator before `dotnet build`

**Comment by cdmihai** [comment]
I would say that for now, calling it manually is the way to go since there's no verb composability ability yet. Once there is a verb composability mechanism (wild guess here, something like putting `"pipeline": ["restore", "fssrgen", "build", "test", "pack"]` in project.json).

**Comment by piotrpMSFT** [comment]
the scripts have been deprecated along with project.json
