### ISSUE TITLE
dotnet compile fails for net20 target, because of TargetFrameworkAttribute in AssemblyInfo.cs

### ISSUE THREAD

**Issue by discostu105** [dotnet/cli#1480]
How to reproduce:
 * dotnet new
 * change configure project.json to target .net 2.0: _"frameworks": { "net20": { } }_
 * dotnet restore
 * dotnet build

Then the following error pops up:
> C:\Program Files\dotnet\bin\dotnet-compile-csc.exe "@D:\dev\coretestx\obj\Debug\net20\dotnet-compile.rsp" returned Exit Code 1
> D:\dev\coretestx\obj\Debug\net20\dotnet-compile.assemblyinfo.cs(4,37): error CS0234: The type or namespace name 'TargetFrameworkAttributeAttribute' does not exist in the namespace 'System.Runtime.Versioning' (are you missing an assembly reference?)
D:\dev\coretestx\obj\Debug\net20\dotnet-compile.assemblyinfo.cs(4,37): error CS0234: The type or namespace name 'TargetFrameworkAttribute' does not exist in the namespace 'System.Runtime.Versioning' (are you missing an assembly reference?)

> Compilation failed.
    0 Warning(s)
    2 Error(s)

When looking into _\obj\Debug\net20\dotnet-compile.assemblyinfo.cs_, obviously there's a _TargetFrameworkAttribute_ which is only available .net 4.0+.

**Comment by blackdwarf** [comment]
@piotrpMSFT who to assign this to?

**Comment by davidfowl** [comment]
The community
