### ISSUE TITLE
LibraryManager return diagnostics for missing DOTNET_REFERENCE_ASSEMBLIES_PATH

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1481]
`DOTNET_REFERENCE_ASSEMBLIES_PATH` is used to assist `FrameworkReferenceResolver` to find full CLR assemblies on platforms other than Windows. Missing the environment variable will cause all full CLR references become unresolved. It is misleading for tooling (OmniSharp in this case).

If a specific error is returned stating that this environment variable is missing tooling / IDE can feed user will helpful message.

**Comment by piotrpMSFT** [comment]
What sets DOTNET_REFERENCE_ASSEMBLIES_PATH?

**Comment by troydai** [comment]
I think we can close this issue: https://github.com/dotnet/cli/blob/8645031db8b6a62a10071578f4949b7094293bdc/src/Microsoft.DotNet.ProjectModel/ProjectContextBuilder.cs#L231. It is actually already implemented.

Now we usually set the variable in build script.

**Comment by blackdwarf** [comment]
@troydai IIUC, this issue is ok to be closed so will close. If I'm completely missing what you said above, please reopen. :)
