### ISSUE TITLE
DotNet build: specifying "--runtime win7-x86" still produces a 64 bit assembly

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#1485]
...
1. DotNet new
2. DotNet restore
3. DoteNet build --runtime win7-x86
4 Run application. It is built to a win7-x86 folder but the runtime executable is 64 bit

@Sridhar-MS

**Comment by piotrpMSFT** [comment]
@BillHiebert @Sridhar-MS is working on 32-bit support in CLI

**Comment by blackdwarf** [comment]
@piotrpMSFT @Sridhar-MS do we have another issue for tracking the x32 support?

**Comment by Sridhar-MS** [comment]
@blackdwarf Do you mean xplat building/publishing support for x86 using x64 dotnet tools?

**Comment by blackdwarf** [comment]
@Sridhar-MS nope, I meant just having a 32-bit installer/bits on disk.

**Comment by Sridhar-MS** [comment]
https://github.com/dotnet/cli/issues/783

**Comment by Sridhar-MS** [comment]
https://github.com/dotnet/cli/issues/2343 is tracking cross-plat build. So closing this issue.
