### ISSUE TITLE
[MSI]: Rename 'DOTNETHOME' id to something more conventional like 'INSTALLDIR'

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#1486]
https://github.com/dotnet/cli/pull/1478/files#r53383383

**Comment by robmen** [comment]
What do you want it to be? `INSTALLFOLDER` or `INSTALLDIR`?

**Comment by Sridhar-MS** [comment]
Thanks @robmen, that will be very helpful. I am ok with either.

**Comment by livarcocc** [comment]
We don't have this anymore.
