### ISSUE TITLE
RESX compilation still can't handle spaces

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1489]
This is a followup to #1280. Following the merge of #1434, I have redownloaded and reinstalled .NET CLI, and attempted to compile the test case [wjk/dotnet-cli-1280](https://github.com/wjk/dotnet-cli-1280). However, I still get errors relating to spaces in RESX paths. Here is the full output of `dotnet compile`:

```
Compiling dotnet-cli-1280 for DNXCore,Version=v5.0
C:\Users\William\Documents\Visual Studio 2015\Projects\dotnet-cli-1280\project.json(9,27): warning NU1007: Dependency specified was System.Console >= 1.0.0-rc2-23704 but ended up with System.Console 4.0.0-beta-22231.

error CS2001: Source file 'C:\Users\William\Documents\Visual Studio 2015\Projects\dotnet-cli-1280\Studio' could not be found.
error CS2001: Source file 'C:\Users\William\Documents\Visual Studio 2015\Projects\dotnet-cli-1280\2015\Projects\dotnet-cli-1280\obj\Debug\dnxcore50\dotnet-cli-1280.Strings.resources,dotnet-cli-1280.Strings.resources
Compilation failed
    1 Warning(s)
    2 Error(s)

Time elapsed 00:00:01.2806006
```

The first of the two errors is the _exact same_ issue that prompted me to file #1280. I am not certain what causes the second error (about the `*.resources` file), but suspect it is the same issue that causes the first error.

I noted that #1434 was merged into `rel/1.0.0`. This implies that it will be included in the latest MSI (which as of this writing is version 1.0.0.001483), but I have just installed that version, and have seen no change with regards to RESX compilation. However, I cannot be certain that the MSI was really updated, because the `dotnet --version` output does not include the build number. Here is the `dotnet  --version` output:

```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

Can anyone point out why this is happening? I would also be appreciative if `dotnet --version` can be amended to print the build number as well. Thanks!

**Comment by davidfowl** [comment]
The latest version `1.0.0.001483` does have changes that print the version as part of the CLI `dotnet --version`:

```
.NET Command Line Tools (1.0.0-beta-001483)

Product Information:
 Version:     1.0.0-beta-001483
 Commit Sha:  f81ba05a7c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

/cc @piotrpMSFT @Sridhar-MS

**Comment by wjk** [comment]
As it turned out, when I updated .NET CLI, I didn't realize that I had to uninstall the old version manually first. I will file a separate issue on this. The RESX compilation issue is officially resolved.
