### ISSUE TITLE
WiX bundle doesn't handle updates correctly

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1493]
When running the WiX-based installer on a system that already has an older version of .NET CLI installed, it succeeds nearly instantaneously, but doesn't actually change anything on disk; the old version is still what will be used. I must manually uninstall .NET CLI through Programs and Features before installing the new version will succeed.

I don't know if this is because I was upgrading from a pre-bundle version of .NET CLI (when it was distributed as a raw `*.msi` file), or if any upgrade will present this problem.

**Comment by robmen** [comment]
Can you look in %TMP% for a log file and attach that here? That will allow us to understand exactly what is going wrong.

Note: There have been several bugs in the upgrade logic because older releases of .NET Core CLI used improper version numbers that could not be upgraded.

**Comment by wjk** [comment]
I found six logs in `%TMP%`; [here is a gist containing all six](https://gist.github.com/wjk/929ae1118707df7ed74b).

**Comment by robmen** [comment]
It looks like you have a pretty old .NET Core CLI on your machine before the version reset to 1.0. You'll want to uninstall that old package first, then you should be able to roll forward with upgrades smoothly (assuming there isn't some other SNAFU with version numbers again).

**Comment by blackdwarf** [comment]
@wjk I think this is solved now so will close. If you can still repro this with newer installs of the CLI, please reopen the issue.
