### ISSUE TITLE
dotnet restore with --packages fails for tools

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1494]
1. Create a project with a tool dependecy
2. Make sure the tool is not installed in the global packages folder.
3. Run `dotnet restore --packages <some folder>`

You'll get an error after restore: `Could not find a part of the path.`

I believe the code looks in the global packages folder for the tool instead of the folder specified in the argument.

cc @brthor @Sridhar-MS

**Comment by brthor** [comment]
This would be a quick fix, but there are significant design changes coming to this whole experience.

I'm not sure if we want to hold off or get the quick fix in? cc @piotrpMSFT

**Comment by blackdwarf** [comment]
@brthor @piotrpMSFT I think we should fix this as part of the new changes. Thoughts?

**Comment by brthor** [comment]
@joelverhagen
Something to consider here. Not sure how this would affect the feature but if it's not a big impact maybe we could get it in v1?

**Comment by piotrpMSFT** [comment]
@krwq, can you add a test for this scenario and make sure it passes?

Take one of our existing PackagedCommand tests and modify it to restore using --packages. This should restore the tool to a new packages root [inside the test's directory] and put in the project lock file the path to that cache. Let's be sure we can then invoke the tool.

Per @victorhurdugaci's comment, we'll probably want to add a new packaged command here that is only used by the test and that we can safely delete from the repo-level cache if present.

**Comment by krwq** [comment]
I did some manual testing on new dotnet project:
`dotnet restore --packages test\` - works
`dotnet restore --packages test2` - works
`dotnet restore --packages full\path\here\` - works
`dotnet restore --packages full\path\here` - works
`dotnet restore --packages ..\some\other\path` - works
`dotnet restore --packages ..\..\idonotexist\foo\` - works

@victorhurdugaci - are you still seeing this issue? I believe this is fixed already. please reopen if you do and please share some more info about your setup

**Comment by krwq** [comment]
Actually reopening - I will add some tests for that

**Comment by krwq** [comment]
Ehh.. I just noticed this was saying "for tools"

**Comment by piotrpMSFT** [comment]
The overall experience you were going after in #5008 is still useful to keep a test around. I'm particularly interested to see if `test` scenarios work this way. Adding a tool to the mix is also interesting, of course.

**Comment by krwq** [comment]
This might be related to: https://github.com/dotnet/cli/issues/5019
I'm seeing similar error there but I'll test separately as this is hard to write a test reliably with following issue https://github.com/dotnet/cli/issues/5020
