### ISSUE TITLE
Add support for analyzers as project references

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#1495]
Add support for using an analyzer from a project reference.

Currently analyzers can only be included from a package reference. This relies on library file structure `<nupkg root>/analyzers/dotnet/cs/*.dll` to identify the package as an analyzer reference. This doesn't work for project references.

Loading a project-reference as an analyzer will require adding some way to identify a project as a analyzer reference. Possible solutions:
- Add a new dependency type "analyzer". E.g. `"EFCore.Analyzers.Internal": {"type": "analyzer", "target": "project"}`
- Add a key to the analyzer project itself, identifying that it is an analyzer project. Could be in [supports](https://docs.nuget.org/consume/projectjson-format#supports) or somewhere else e.g. `"supports": { "dotnet.analyzer": {} }` (Side note: this could also be useful for dotnet-pack so it creates a nupkg with the right structure.) 
- Some combination of above options

**Comment by piotrpMSFT** [comment]
@natemcmaster I believe we can close this after the move to csproj. Can you confirm?

**Comment by natemcmaster** [comment]
Yes, we can close this.
