### ISSUE TITLE
latest dotnet-nightly silently failed when restoring on Debian

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#1496]
I installed the latest version `1.0.1.001569-1` on Debian Jessie.  After `dotnet new` I ran `dotnet restore` but it exited silently.  Nothing in the output after the following line
```
log  : Restoring packages for /home/azureuser/apps/hello/project.json...
```

I noticed that `dotnet -v restore` doesn't print out the runtime anymore as previous versions do

```
Running /usr/share/dotnet-nightly/bin/corerun /usr/share/dotnet-nightly/bin/NuGet.CommandLine.XPlat.dll restore
```

Compare to dotnet-nightly 1.0.1.001252-1
```
Running /usr/share/dotnet-nightly/bin/corerun "/usr/share/dotnet-nightly/bin/NuGet.CommandLine.XPlat.dll" "restore" "--runtime" "debian.8.2-x64"
```

The strace show an exit code of 139 (0x8b).

If I downgrade to `dotnet-nightly=1.0.1.001252-1` everything works fine.

**Comment by blackdwarf** [comment]
@jeremymeng can you try the build on http://dotnet.github.io/getting-started/ and see if it still repros?

**Comment by jeremymeng** [comment]
@blackdwarf yes, `dotnet=1.0.0.001331-1` was the build we tried first but had the same issue.

**Comment by jeremymeng** [comment]
Now saw another failure with exit code 137 this time
```
exit_group(137)                         = ?
+++ exited with 137 +++
```
It is with `1.0.1.001252-1` on a 1 Core 3.5 GB Azure VM.  This version works fine on another Debian VM.

**Comment by jeremymeng** [comment]
This turns out to be a dependency issue.  The user and I both have a higher version of `libssl1.0.2` installed, side-by-side with `libssl1.0.0`.  This caused `corerun` to crash when restoring packages.

How did I come to this state is unknown. I may have used `sid` feed before.  The customer did have `testing` deb feed in their `sources.list`.  So in theory the dotnet installer could pull down higher versions from the `testing` source? After fighting with purging and re-installing many packages, the latest version of `dotnet` runs fine on the customer's machine.

1. Is it possible to detect incompatible versions of dependencies from the deb installer?  It is time-consuming to get back to the right state after higher versions are installed.

1. The dotnet itself exits silently (with a error code that is not very helpful) when corerun crashed.  We should provide better information to the user when this happens.

**Comment by brthor** [comment]
> The user and I both have a higher version of libssl1.0.2 installed, side-by-side with libssl1.0.0

Was this installed via apt-get? Did they have the same package id or are they separate?

> Is it possible to detect incompatible versions of dependencies from the deb installer? It is time-consuming to get back to the right state after higher versions are installed.

We can specify exact version dependencies, and can specify conflicts for packages.

@jeremymeng As we light up debian support I think we will need to produce an separate package with targeted dependencies/conflicts information for that distribution. That should (hopefully) solve these issues. It remains to be seen whether the needed dependencies will be available via default package feeds though.

**Comment by jeremymeng** [comment]
> Was this installed via apt-get?

It could be, for example, when following the instructions to install Dnx.  I had the following on my machine at one time

```
libcurl4-openssl-dev/now 7.47.0-1 amd64 [installed,local]
libgnutls-openssl27/now 3.4.9-2 amd64 [installed,local]
libssl-dev/now 1.0.2f-2 amd64 [installed,local]
libssl-doc/now 1.0.2f-2 all [installed,local]
libssl1.0.0/stable,now 1.0.1k-3+deb8u2 amd64 [installed,upgradable to: 1.0.1k-3+deb8u4]
libssl1.0.2/now 1.0.2f-2 amd64 [installed,local]
openssl/stable,now 1.0.1k-3+deb8u2 amd64 [installed,upgradable to: 1.0.1k-3+deb8u4]
```


> That should (hopefully) solve these issues. It remains to be seen whether the needed dependencies will be available via default package feeds though.

lldb-3.6 is not available in stable Debian feed. #1001

**Comment by blackdwarf** [comment]
@jeremymeng is this still valid/reproing?

**Comment by jeremymeng** [comment]
Closing now since the installation method for RC2 is different.
