### ISSUE TITLE
dotnet --version NRE on Ubuntu 14.04

### ISSUE THREAD

**Issue by shahid-pk** [dotnet/cli#1498]
happens both on dotnet and dotnet-nightly package.
for repro just do this with latest nightly or dotnet

`dotnet --version`

this comes out

>  .NET Command Line Tools (1.0.0-dev-001569)
> 
>   Product Information:
>   Version:     1.0.0-dev-001569
> 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.DotNet.Cli.Program.PrintVersionInfo()
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)
> Aborted (core dumped)

caused by i think https://github.com/dotnet/cli/pull/1471

**Comment by davidfowl** [comment]
I'll fix this but where is the version file?

**Comment by brthor** [comment]
#1867
