### ISSUE TITLE
dotnet cli publish command doesn't support publishing content files

### ISSUE THREAD

**Issue by joperezr** [dotnet/cli#1505]
Some packages have a root folder named content which according to nuget conventions may contain any type of folders and files. Currently, dotnet publish doesn't copy this assets over which then requires workarounds like going manually to the package and copying those files out

**Comment by joperezr** [comment]
Cc: @weshaggard

**Comment by livarcocc** [comment]
CC: @pakrym This seems to be around your area of interest.

**Comment by davidfowl** [comment]
Nuget has support for a new type of content called contentFiles that will be supported in the CLI. The other content folder isn't supported.

**Comment by joperezr** [comment]
@davidfowl I see, when will this contentFiles support come online? Is there an issue tracking the work for it for reference?

**Comment by davidfowl** [comment]
https://github.com/dotnet/cli/pull/1468
