### ISSUE TITLE
dotnet-test fails to find the xunit runner if the tfm of the test project is netstandard1.5

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1506]

**Comment by andschwa** [comment]
This is becoming a bigger issue with the new .NET Core packages targeting `netstandard1.5` instead of `dnxcore50`; it means the runner won't work once we upgrade our packages.

**Comment by livarcocc** [comment]
I have updated  the version of the xunit runner to be netstandardapp1.5.
