### ISSUE TITLE
Please use Announcements for breaking changes on published output

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1507]
There was a change recently for published output (payload lands in a `publish` folder now) that I missed in the issues. I had an app go down due to the change (staged only ... no big deal). Please give us a heads up on breaking changes in Announcements, where it's less likely this would have gotten by me.

![capture](https://cloud.githubusercontent.com/assets/1622880/13194051/67b22ed8-d739-11e5-9e8a-af5bab941fef.PNG)

**Comment by piotrpMSFT** [comment]
@pakrym
