### ISSUE TITLE
Add coreclr dependencies check to build for OSX

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1508]
#1504 Added Coreclr dependency checks for Ubuntu and CentOS.

OSX should be added as well.

libssl is currently the only known dependency. Need to investigate to see if there are others.

**Comment by brthor** [comment]
CoreCLR docs list homebrew as the method of acquisition for it's openssl dependency.

https://github.com/dotnet/coreclr/blob/master/Documentation/building/osx-instructions.md

Should we consider requiring homebrew for our build on OSX?

cc @livarcocc @piotrpMSFT @Sridhar-MS

**Comment by blackdwarf** [comment]
@brthor homebrew is the only sane way, I think, to update OpenSSL. I'm putting this for RTM, is that fine?

**Comment by ellismg** [comment]
As of today there are no additional dependencies aside from libssl that are not present in box.  I do not expect we would add any additional ones before RTM, either.

**Comment by natemcmaster** [comment]
Probably a naïve question, but is there a reason we can't bundle libssl in the pkg installer for osx?

**Comment by ellismg** [comment]
> Probably a naïve question, but is there a reason we can't bundle libssl in the pkg installer for osx?

From a technical standpoint, we could make this work.  The concerns are around servicing (there's a bug in libssl and we are on the hook for servicing it) and there's some additional internal procedure we'd need to go through to try to get approval to do this (and it's not even a given).

**Comment by livarcocc** [comment]
There are no more native dependencies that we need to guard against. Closing.
