### ISSUE TITLE
appsettings.json not found

### ISSUE THREAD

**Issue by chrisjmccrum** [dotnet/cli#1509]
After moving to dotnet cli - my project can't seem to find the appsettings.json file when i run it from the command line.  I have my connection string stored for each env in seperate files and call it dynamically in my startup.  Below my snippet is the error I get now that didn't exist when my project was pure dnx.

```
        public IConfigurationRoot Configuration { get; set; }
        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            IConfigurationBuilder builder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);


            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }
```

![image](https://cloud.githubusercontent.com/assets/1857216/13194539/15a84832-d763-11e5-9ba6-0b2ef9b3a03b.png)

**Comment by chrisjmccrum** [comment]
needed to add set base path to the Configuration Builder.

```
        public IConfigurationRoot Configuration { get; set; }

        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            IConfigurationBuilder builder = new ConfigurationBuilder()
                .SetBasePath(appEnv.ApplicationBasePath)
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }
```

**Comment by ericwj** [comment]
I'm having this same issue after adding `builder.SetBasePath(appEnv.ApplicationBasePath)` on dotnet `1.0.0-rc2-002357` and I found 
`Console.WriteLine($"{nameof(appEnv.ApplicationBasePath)}: {appEnv.ApplicationBasePath}");` 
to write 
`ApplicationBasePath: C:\Users\Eric\Source\Playground\AspNetCoreRC2\src\Web\bin\Debug\netcoreapp1.0` 
That folder only contains files starting with `Web.` after running `dotnet build`

Am I missing something, or is this a problem with that build of the CLI?

**Comment by alexlau811** [comment]
@ericwj, could you try using `IHostEnvironment.ContentRootPath` ?

```
        public Startup(IHostingEnvironment env)
        {
            _env = env;

            // Set up configuration sources.
            var builder = new ConfigurationBuilder()
                .SetBasePath(_env.ContentRootPath)
                .AddJsonFile("appsettings.json")
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

            builder.AddEnvironmentVariables();
            Configuration = builder.Build();
        }
```

**Comment by ericwj** [comment]
Ah yes, I have noticed that this is what the templates do nowadays. I believe I had stuff running doing `Directory.GetCurrentDirectory()` although that seemed a hack of sorts.

But thanks for dropping me a line 👍
