### ISSUE TITLE
Question : is it possible to create a separate project to build a nuget from multiple other projects?

### ISSUE THREAD

**Issue by StefH** [dotnet/cli#1512]
Question : is it possible to create a separate project to build a nuget from multiple other projects?

I've the following projects (dnx452 and dnxcore50):

- Library1
- Library2
- Library3

Is it posibble to use another project **Final** which creates a nuget package containing all the artifact outputs from Library1,2 and 3, but not any artifacts from Final? (I don't want any Final.dll or Final.pdb in the nuget package)

I tried deleting the Final.* using a **prepack** command, but could not get this working.

**Comment by davidfowl** [comment]
Are those components only ever used in a single package? Is it an internal implementation detail that is never embedded in any other package?

**Comment by StefH** [comment]
The purpose is to create a single nuget package which contains the artifacts (dll's) from these 3 Libraries.
The code is split into 3 projects to make the logic more separated, but all 3 dll's are needed when using this Final nuget.

Another solution would be to create a Final project which just includes and compiles the source files from all 3 projects and just creates 1 Final.dll, but I would like to investigate if my original question could be solved.

**Comment by davidfowl** [comment]
I understand what you're trying to do, I'm just asking what you plan to do with the package. If you include those dlls in other packages then all hell will eventually break loose. If they are only ever used in this single package (as an implementation detail), then it's fine.

**Comment by StefH** [comment]
These 3 dll's are always and only used together.

So the question is if there is a way to achieve this using a dummy project **Final** ?

**Comment by davidfowl** [comment]
There's no first class support for this in the project system. You can use packInclude to include files from other projects: 

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/project.json#L58

**Comment by StefH** [comment]
For this moment I just combined all source files into 1 dll using :
```c#
"compile": [
]
````

Issue can be closed.

**Comment by davidfowl** [comment]
Nice!
