### ISSUE TITLE
.NET CLI Incompatible with Visual Studio

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#1514]
Following a recent update to my copy of .NET CLI, I am now getting errors when building a .NET Core project from within Visual Studio. Every project in my dependency tree now gives me the following error:

```
DNX Core 5.0 error NU1006: Dependencies in project.json were modified. Please run "dnu restore" to generate a new lock file.
```

These projects all compile correctly using `dotnet compile` or `dotnet publish`. It seems that the concerns that prompted me to file #1139 have finally come to pass: .NET CLI and Visual Studio are no longer compatible.

Here is my .NET CLI version output:

```
.NET Command Line Tools (1.0.0-beta-001483)

Product Information:
 Version:     1.0.0-beta-001483
 Commit Sha:  f81ba05a7c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by davidfowl** [comment]
> Following a recent update to my copy of .NET CLI, I am now getting errors when building a .NET Core project from within Visual Studio. Every project in my dependency tree now gives me the following error:

The VS tooling for the .NET CLI isn't ready yet.

In the mean time, try updating your DNX tools to the latest. 

```
set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/api/v2
dnvm upgrade -u
```

We're going to keep the DNX tooling as in sync as we can until the CLI tooling in VS is public.

**Comment by wjk** [comment]
@davidfowl Didn't work; I still get NU1006. Doesn't really matter, though, because all this affects is a quick syntax-check of my project by doing a Build > Build in the IDE. When I build for debugging or release, I always use .NET CLI. If it's OK with you, I'm going to close this.
