### ISSUE TITLE
dotnet run looking in wrong place (missing hashed foldername) - "Could not find a part of the path '...exe'"

### ISSUE THREAD

**Issue by replete** [dotnet/cli#1515]
* 1.0.0-rc1-update1
* .NET Command Line Tools (1.0.0), win10-x64

As you can see below, I am unable to run my project because `dotnet` forgets all about the hash subfolder when trying to find the executable it just compiled.

```ps1
PS A:\CuroApp\src\Curo.Web> dotnet -v run -c kestrel -t
Running C:\Program Files\dotnet\bin\dotnet-build.exe "--output" "A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82" "--temp-output" "A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82" "--framework" "DNX,Version=v4.6" "--configuration" "kestrel" "A:\CuroApp\src\Curo.Web"
Process ID: 11060
Project Curo.Web (DNX,Version=v4.6) will be compiled because expected outputs are missing.
 A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82\kestrel\dnx46\Curo.Web.exe
 A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82\kestrel\dnx46\Curo.Web.pdb

Running C:\Program Files\dotnet\bin\dotnet-compile.exe "--framework" "DNX,Version=v4.6" "--configuration" "kestrel" "--output" "A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82" "--temp-output" "A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82" "A:\CuroApp\src\Curo.Web"
Process ID: 7648
Compiling Curo.Web for DNX,Version=v4.6
Running C:\Program Files\dotnet\bin\dotnet-compile-csc.exe "@A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82\dotnet-compile.rsp"
Process ID: 8352
Running C:\Program Files\dotnet\bin\csc.exe "-noconfig" "@A:\CuroApp\src\Curo.Web\bin\.dotnetrun\af0e5cd59ac84a31bdab508f66136c82\dotnet-compile-csc.rsp"
Process ID: 11144

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.6343090
Could not find a part of the path 'A:\CuroApp\src\Curo.Web\bin\kestrel\dnx46\Curo.Web.exe'.
PS A:\CuroApp\src\Curo.Web>
```

**Comment by davidfowl** [comment]
> .NET Command Line Tools (1.0.0), win10-x64

Update your CLI install. Uninstall the old one before installing the new one. There's been a few installer problems.

**Comment by replete** [comment]
@davidfowl I thought I'd done this, but on closer inspection I realised that _two_ version of dotnet CLI were installed - one was a dev1200 version. 

This has worked for me, although now I have other compile errors. Thanks.

**Off-topic aside:**
I know this isn't the right place, but I really feel like the wider vnext project needs someone to _own_ a global _'Getting started with RC1'_ manual - perhaps on [docs.aspnet.org], that is directed to from all current documentation areas/packages. 

I know a lot is going on with the move to dotnet, but I have literally spent hours and hours and hours trying to make sense of everything. From what I've seen of the milestones, RC2 is months away and therefore this would probably be worthwhile.

It took me hours to realize:
* RC1-final is easiest to work with right now due to (good) changes across the board
* `AspNetCore.*` dependencies use a new namespace for RC2+, and I shouldn't be using them
* RC2 packages need a custom package provider setting up
* `dotnet` replaces `dnx, dnvm` etc
* `dotnet` is essential for RC2+
* `dotnet` is not essential for RC1, can use dnx etc at the time (not clear from package repos)
* `dnx46`,`dnx451` are .NET Native frameworks
* `dnxcore50` is RC1* name for .NET Core
* `project.json` schemas documented had slight differences between RC1, RC2

What would clear this up:
* Explain how and why RC1 is what most people should use right now
* Getting started with RC1
* Explain who should use RC2
* Getting started with RC2

**I'll post this response somewhere relevant, any suggestions?**
