### ISSUE TITLE
Nit: Installer logo doesn't reflect .NET ... in any way apparently

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1519]
The MSI installer logo is ...

![capture](https://cloud.githubusercontent.com/assets/1622880/13226970/1e2ef50e-d949-11e5-9d81-1ef8c5a6172e.PNG)

There is no ASP.NET logo at http://www.asp.net/; however, it seems the (official?) logo is at the .NET website at https://www.microsoft.com/net ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/13226987/3a8726ae-d949-11e5-9ffa-abdd9f7c6880.PNG)

[EDIT]
> in any way

... except perhaps color. The logo structure lends nothing to maintaining the .NET brand. Would you consider changing that logo?

**Comment by GuardRex** [comment]
I was just informed by @blowdart that this cannot be changed.

Personally, I would have rejected the installer technology if it couldn't support my brand.

**Comment by robmen** [comment]
It totally can be changed. I grabbed the only image I could find in the repository. Happy to work with anyone more graphically-inclined than I.

**Comment by Eilon** [comment]
Should definitely use an official logo in any installer.

**Comment by robmen** [comment]
@Eilon where were you when I asked for feedback on the installation UI? :smile_cat:

**Comment by Eilon** [comment]
I was, umm... busy? :smile: 

@richlander off to you to decide which is the fairest logo of them all.

**Comment by blackdwarf** [comment]
@Eilon @robmen I believe the dotnet bot was something we put in back when we were starting. An official logo should be something to put in there (though I would leave the dotnetbot for kicks :)). 

@richlander I believe we do have official logos somewhere we can use for this, no?

/cc @piotrpMSFT

**Comment by robmen** [comment]
Fine by me. Let me be real clear. I'm not a designer. If someone provides the layout for the pages, I am happy to make them look like that (within reason). However, don't just say, "Here's a logo, make it look good."

My graphic-design-fu isn't strong enough to spend time doing all the layout, "wordsmithing", etc. :smile_cat:

**Comment by blackdwarf** [comment]
@robmen of course, of course, I meant we will provide all the necessary details. Just need to figure which details are those (pesky branding stuff and all that :)). 

Which brings an interesting point...you mentioned above "layout for the pages"...can you elaborate? I don't know much about building installers/bundles, so I thought that there is just a logo (image) in there...

**Comment by robmen** [comment]
Click through the install if the latest package for Windows. Then click through the uninstall. You'll see 4 or so different pages that need layout. You can go pretty far with a layout for the welcome page (EULA, stuff to look at like version number, etc) and the rest (something that looks nice minimal controls... like just a progress bar and cancel button or success message and close button).

**Comment by blackdwarf** [comment]
These pages are...HTML pages or just "pages" as in, generic term? PKG uses HTML pages (or RTF I believe).

**Comment by robmen** [comment]
"pages" in generic terms. The [pages are defined in XML](https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/bundle.thm) to create GDI based forms. Basically, no dependency UI (i.e. runs on WinXP and later) but pretty flexible. It can do owner draw as well if you want to go all in on graphics... not that I recommend that :smile_cat:

**Comment by akoeplinger** [comment]
> (i.e. runs on WinXP and later)
Unrelated to this issue, but the installer should probably block on < Win7 since afaik that's the minimum supported OS by the CLI/.NET Core.

**Comment by blackdwarf** [comment]
@akoeplinger this is actually very true. :)

**Comment by GuardRex** [comment]
Fixed by https://github.com/dotnet/cli/pull/1891
