### ISSUE TITLE
Is assembly info still needed

### ISSUE THREAD

**Issue by Jupakabra** [dotnet/cli#1520]
Got redirected form https://github.com/aspnet/Home/issues/1318.

Just wanted to know if assembly info file should be included in new dnx/dotnet cli projects or project.json will be sufficient for all our needs?

**Comment by blackdwarf** [comment]
@davidfowl @anurse any insight on this?

**Comment by davidfowl** [comment]
@Jupakabra depends on what assembly metadata you need. The `project.json` metadata maps to specific assembly attributes and nusepc metadata.

**Comment by Jupakabra** [comment]
I usually used
```C#
[assembly: ComVisible(false)]
[assembly: AssemblyCompany("Company")]
[assembly: AssemblyTitle("Product")]
[assembly: AssemblyProduct("Product")]
[assembly: AssemblyCopyright("Copyright © Company")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyVersion("1.0.0.0")]
```
And some times one or two xunit attributes, but the question is more about is it "completely not needed" or it will not be needed, unless used in advanced scenarios?

**Comment by MichaCo** [comment]
Following things will be set via project.json (if defined) now as far as I know:

```csharp
[assembly: AssemblyVersion("0.7.5.0")]
[assembly: AssemblyCopyright("...")]
[assembly: AssemblyDescription("...")]
[assembly: AssemblyFileVersion("0.7.5.20221")]
[assembly: AssemblyInformationalVersion("0.7.5-t160221124614")]
```

If you need additional stuff, you can manually add an assembly info file later. In general, for the version etc, you don't need one at all.

If you want to mark your assembly as CLS compliant again for example, you have to add one.

**Comment by Jupakabra** [comment]
Got it, thanks.
