### ISSUE TITLE
OutOfMemoryException when `dotnet restore` on an Azure Debian Jessie VM with 1-CPU and 3.5 GB RAM

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#1521]
Hit it a few times.  It does not always reproduce.  I noticed that CPU usage and memory usage are close to 100%.  Many `dotnet restore` processes, and `corerun "/usr/share/dotnet-nightly/bin/NuGet.CommandLine.XPlat.dll" "restore" "--runtime" "debian.8-x64"` processes spawned.

**Comment by blackdwarf** [comment]
@jeremymeng so with increased memory/cpu pressure a `dotnet restore` fails with the OOM exception? Can you share your `project.json` that you are using?

**Comment by jeremymeng** [comment]
@blackdwarf I was using a customer's project, but I just reproduced it using `HelloMvc` from https://github.com/aspnet/cli-samples.git.
```
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.aspnetcore.diagnostics.abstractions/index.json 5253ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json 5190ms

Unhandled Exception: OutOfMemoryException.
```

**Comment by emgarten** [comment]
@jeremymeng is this only on Debian 8 or are you seeing it on other OSes also?

**Comment by jeremymeng** [comment]
@emgarten I haven't as I don't have other machines with limited resources.

**Comment by Emyr42** [comment]
Adding options to dotnet-restore to limit parallelism would be helpful, but that'd probably need changes in nuget3.

On my Acer Aspire One (Atom CPU, 1GB? RAM) with Ubuntu 14.04 LTS, I can't do restores using nuget.org or myget. I have to do the restore on a different machine then copy the .nupkg files to a local repo.

**Comment by emgarten** [comment]
@Emyr42 ``--disable-parallel`` turns off concurrency

**Comment by blackdwarf** [comment]
@jeremymeng can you move this to NuGet/Home please?
