### ISSUE TITLE
Is receiving the Stack Trace normal for a failed xUnit test?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1527]
I'm experimenting with xUnit in a Core project (`dotnet cli` latest, VS Code)

When an test fails, the Stack Trace is shown ...
```
xUnit.net DNX Runner (64-bit win7-x64)
  Discovering: deviceservice
  Discovered:  deviceservice
  Starting:    deviceservice
    deviceservice.Tests.UtilityTests.RequestHeaders_ValidMac(mac: "01:23:45:67:89:XX", 
data: "data_value", remoteIpAddress: "68.225.66.144", expectedResult: True) [FAIL]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        c:\_APPLICATIONS\deviceservice\Tests\UtilityTests.cs(60,0): 
at deviceservice.Tests.UtilityTests.RequestHeaders_ValidMac(String mac, String data, 
String remoteIpAddress, Boolean expectedResult)
  Finished:    deviceservice
=== TEST EXECUTION SUMMARY ===
   deviceservice  Total: 18, Errors: 0, Failed: 1, Skipped: 0, Time: 1.341s
```
Is that normal? ... or did I configure something incorrectly? If it is normal can I stop the `Assert` from generating the Stack Trace but preserve the test failure? I would prefer to receive output like this (less chatty) ...
```
xUnit.net DNX Runner (64-bit win7-x64)
  Discovering: deviceservice
  Discovered:  deviceservice
  Starting:    deviceservice
    deviceservice.Tests.UtilityTests.RequestHeaders_ValidMac(mac: "01:23:45:67:89:XX", 
data: "data_value", remoteIpAddress: "68.225.66.144", expectedResult: True) [FAIL]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
  Finished:    deviceservice
=== TEST EXECUTION SUMMARY ===
   deviceservice  Total: 18, Errors: 0, Failed: 1, Skipped: 0, Time: 1.341s
```

**Comment by GuardRex** [comment]
I have a good answer on this from @BradWilson on JabbR: It does two things ...

- It provides the line number. If there are many tests, it obviously helps you get to the method where the failure occurred.
- VS has an additional advantage in that it can jump you right to the failed test method in the VS UI, because VS can recognize the presence of the Stack Trace and enable this extra navigation functionality.

For those reasons, it's apparently a good idea to keep it, especially where VS is used.

For everyone else (VS Code users, non-VS users), can/should there be a way to silence the Stack Trace to reduce the output? Could the line number be rolled in with the failure? ...
```
deviceservice.Tests.UtilityTests.RequestHeaders_ValidMac(mac: "01:23:45:67:89:XX", 
data: "data_value", remoteIpAddress: "68.225.66.144", expectedResult: True) [FAIL] [Line: 60]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
```

A further output-related question is why expend the vertical space with the test failure result and conditions, how about this? ...
```
deviceservice.Tests.UtilityTests.RequestHeaders_ValidMac(mac: "01:23:45:67:89:XX", 
data: "data_value", remoteIpAddress: "68.225.66.144", expectedResult: True) [FAIL] [Line: 60]
      Assert.Equal() Failure     Expected: True     Actual: False
```

**Comment by bradwilson** [comment]
> For everyone else (VS Code users, non-VS users), can/should there be a way to silence the Stack Trace to reduce the output?

Open a feature request. This would be a change in the runner. 

> Could the line number be rolled in with the failure?

We don't parse the stack frames (primarily because they vary by language), so we likely wouldn't do this.

> A further output-related question is why expend the vertical space with the test failure result and conditions, how about this?

UX. It puts values in a predictable place at a glance. Also, we use fixed pitch output in our messages to help even further:

```
Assert.Equal() Failure
                                 ↓ (pos 36)
Expected: ··· long string with a slight misspelling in the middle of it an···
Actual:   ··· long string with a light misspelling in the middle of it and···
                                 ↑ (pos 36)

```

**Comment by GuardRex** [comment]
@bradwilson Thanks ... thoroughly answered and I understand the reasoning here.
