### ISSUE TITLE
Publish fails for packages with placeholders in lib/ref actual files in native

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#1528]
Consider a package with
```
lib\dotnet5.1\_._
runtimes\any\native\foo.dll
```
When published, foo.dll is not copied to the output directory.

This is happening because publish ends up calling [PackageDependencyProvider.GetDescription](https://github.com/dotnet/cli/blob/0bde93b57308172fac34a950267b1a3f3d06cbfe/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L27) more than once.  The first time through this method it correctly calculates that the package is compatible, but the second time it calculates compatible as false, since the first time through mutated the source `targetLibrary` removing the placeholder files.  The result is that publish treats the package as unresolved because PackageDescription.Resolved is set to false.

For a repro use https://gist.github.com/ericstj/8569be4495c13d060e02
Run 
```
dotnet restore --source https://www.myget.org/F/dotnet-core/ --source https://www.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json
dotnet -v publish -f dnxcore50 -r win7-x64 -o ".\published"
```

Note that the published folder is missing all the files from the Microsoft.Build.Targets package even though the package was resolved and all files appear in the lock file,

/cc @dagood @davidfowl

**Comment by ericstj** [comment]
This appears to have been a regression caused by https://github.com/dotnet/cli/commit/2807db8044397558208f986c147fdbb6244dadf5.

**Comment by davidfowl** [comment]
Resolved

**Comment by ericstj** [comment]
LGTM. Thanks for the quick fix.
