### ISSUE TITLE
Copy paste a line with \\\" in the project.json in Visual Studio 2015 removes a \" ?

### ISSUE THREAD

**Issue by StefH** [dotnet/cli#1531]
Copy paste a line with \\\" in the project.json in Visual Studio 2015 removes a \" ?

Project.json before:
![2016-02-23_18h21_56](https://cloud.githubusercontent.com/assets/249938/13260163/9f8326c2-da5a-11e5-9b34-d4263afb1093.png)

Selecting the green part and doing a Ctrl-C , Ctrl-V on another line removes the \" ?
![2016-02-23_18h22_11](https://cloud.githubusercontent.com/assets/249938/13260204/c4912676-da5a-11e5-9fbd-b3e3d6a11f77.png)

**Comment by jasonwilliams200OK** [comment]
Steps to repro

Copy the following:

```json
{
  "scripts": {
    "prebuild": "echo \"commencing prebuild\""
  }
}
```

and paste in project.json in VS2015.

It will result in:

```json
{
  "scripts": {
    "prebuild": "echo \"commencing prebuild"
  }
}
```

(workaround is to press Ctrl+Z once after the paste)

**Comment by blackdwarf** [comment]
An interesting problem, however, this sounds like a VS2015 issue rather than a CLI issue. Was this something that started to happen when you installed CLI bits?

**Comment by StefH** [comment]
@blackdwarf , indeed, this seems more like a VS2015 issue, and is probably not related to CLI.

Can you move this problem to the right issue list ?

**Comment by blackdwarf** [comment]
@StefH I can try, but VS2015 issues are not on GH that I know of. :) Will close this and route where needed.
