### ISSUE TITLE
Stabilize CLI Dependency Package Flow

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1544]
## Objective
dotnet/cli needs to achieve and maintain a stable dependency surface area while keeping up with improvements in dependency components. Moving to a private dependency myget feed was a big step in the right direction, ensuring consistent retention policy and fast build times, but is insufficient for CLI to reach production.

## Requirements
- [ ] CLI build times cannot regress
- [ ] CLI must have control over its build time dependencies so builds are stable.
Changing dependency versions must require going through CI, and existing dependencies cannot disappear from feeds.

## Enhancements
- [ ] CLI must have immediate access to new builds of external dependencies.
Once a CoreFx build with an important fix comes out then it can immediately be used in CLI.
- [ ] CLI must have a cohesive closure of dependencies.
Any project in the CLI repo referencing System.Foo must be referencing the same version of System.Foo
- [ ] CLIs closure of dependencies must be intentional.
CLI repo should be able to specify that it depends on NETStandard.Library version X, and the build should ensure that only that version is used.
[e.g. NuGet currently downgrading many of our libraries]

**Comment by gkhanna79** [comment]
CC @jkotas

**Comment by eerhardt** [comment]
To solve `CLI must have immediate access to new builds of external dependencies.`, I plan on using the Web Hooks feature in MyGet to push new packages from dotnet-core (and any other feed we need immediate access to) into our private dependency feed as they come out.

See:  http://docs.myget.org/docs/reference/webhooks#Package_added and http://blog.myget.org/post/2014/10/16/Implementing-custom-package-retention-using-webhooks.aspx

This will also have the ability to filter out certain packages. For example, we don't want CoreFX's "rc3" packages in our private dependency feed right now.

**Comment by piotrpMSFT** [comment]
/cc @agocke @emgarten @jaredpar 

To truly fix this issue we're going to need to finish work already under way regarding getting CLI dependencies onto NETStandard.Library and keep those versions in sync.

**Comment by davkean** [comment]
@piotrpMSFT can you expand on this? When designed the entire contract system that ".netstandard" is built on, it was always compatible to build against a lower version of a given contract and run against a higher version. It seems that the impression is being given to Roslyn that this isn't the case. Can you help me understand this?

**Comment by davkean** [comment]
Are are you only talking about pre-release dependencies?

**Comment by eerhardt** [comment]
> Or are you only talking about pre-release dependencies?

Yes, the main issue here is pre-release dependencies. For example, when building the dotnet/cli repo today, we download 15 different versions of the `System.Runtime` package, each of which is between 30-60 MBs. It is a huge waste during our build to restore these multiple versions.

**Comment by davkean** [comment]
Okay, so the ask is to unify pre-release dependencies, but Roslyn _does not_ have to upgrade dependencies on packages that are already released? Is a correct statement?

**Comment by eerhardt** [comment]
> but Roslyn does not have to upgrade dependencies on packages that are already released?

I didn't think that was possible. Once you release a package, the dependencies are fixed - right?  I don't think we are asking to upgrade dependencies on already released packages.

But, for example, we should upgrade the dependencies in Microsoft.Net.Compilers.netcore 1.2.0-beta1* packages to use the NETStandard.Library.

**Comment by piotrpMSFT** [comment]
Correct. The requirement will be that when new Roslyn [and NuGet and etc.] packages are PR'd into CLI then their mutual dependencies are version-identical.

**Comment by davkean** [comment]
Hold on, now we're talking about two different things.

**Comment by piotrpMSFT** [comment]
CLI installers should ship only one version of each library per target. Today we have 15 System.Runtimes that run just atop corefx/coreclr. That needs to be fixed.

So long as folks are referencing common libraries correctly [e.g. use the Metapackage where available] CLI can override their dependencies to unify. This will mean, though, that we will need to add false dependencies next to `roslyn` and `nuget` to hoist their dependencies, but that may be the lowest-cost thing to do at the moment.

**Comment by davkean** [comment]
@piotrpMSFT That's exactly how I would expect the system to work. You must unify dependencies to the highest version - that's just normal dependency management.

**Comment by davkean** [comment]
@ericstj can you weigh in on this? There's a massive confusion on the Roslyn side - the compiler is being told to upgrade dependencies we have on stable releases of framework packages, which goes against everything we worked on for the last 5 years.

**Comment by piotrpMSFT** [comment]
@davkean this issue is intended to figure out the right answer. We know we need for CLI to ship on a consistent version, the question is how we get there. Agreed we need to work with @ericstj to determine the right guidance.

The thing that makes CLI dependencies 'special' is that we need to unify them across multiple projects. NuGet does this for us for any given project, but we ship many projects in one package so there is added complexity.

**Comment by davkean** [comment]
Your case is not that special, it's extremely common for packages to have binaries with different dependencies. Any package containing both a desktop and portable binary is that situation.

**Comment by ericstj** [comment]
There are two issues to consider here:  
1. CLI needs to be able to upgrade to latest implementation and have a consistent set of packages at runtime & in the CLI package.
2. CLI needs to have a minimal restore footprint.

1 is a given and is the natural behavior for NuGet.  NuGet walks the entire graph to find the best version that satisfies all consumers.  So long as CLI is using a single resolution scope this should work fine.  @davkean this agrees with everything that we've worked on over the years.

2 is what @piotrpMSFT and @eerhardt are trying to do.  It's not so much a statement about compatibility or what must be done.  It's more about optimizing the CLI product/package/repo.  Due to the way NuGet evaluates dependencies it will always download the old packages if no library in the parent chain specifically referenced a newer version.  So peer conflicts that can be resolved aren't a problem, its just additional download overhead.  I think we should think more about the best way to address this problem.  With a product like the CLI that is consuming bits from multiple repos I think it's going to be very difficult to get everyone coordinating on the same versions all the time.  As David mentioned CLI isn't special.  Really the only repro that can effectively coordinate is CoreFx since it is at the bottom.  

I think we should see if there is nuget feature / build pattern we can follow to achieve the goal without imposing requirements on folks outside the repo.  @davidfowl wasn't there a NuGet feature discussed at one point where a global.json could lift up a version of a package referenced without actually forcing a reference to that package?

**Comment by davidfowl** [comment]
> I think we should see if there is nuget feature / build pattern we can follow to achieve the goal without imposing requirements on folks outside the repo. @davidfowl wasn't there a NuGet feature discussed at one point where a global.json could lift up a version of a package referenced without actually forcing a reference to that package?

Yes, but that's not happening right now. I agree that would be a nice way to solve this problem but it's just not a good short term solution.

**Comment by eerhardt** [comment]
> CLI isn't special

What makes CLI special is the fact that we want to release 4 separate repos (corefx, roslyn, nuget, cli) at the same time and in the same package (in this case an .msi or apt-get package). Normally, separate repos ship independently of each other.

It would be unfortunate if we shipped corefx-version823 in the same package as nuget and roslyn, where nuget referenced corefx-version818 and roslyn referenced corefx-version820.

What really needs to happen is corefx needs to ship v1.0 (the blessed release version). And then nuget and roslyn uptake corefx v1.0 and ship their "vX.0" (whatever version that happens to be for them). And then cli take all 3 of those packages and wrap them in a redist and ship that.

**Comment by davkean** [comment]
To summarize, Roslyn needs to upgrade their existing dependences on shipped .NET packages because NuGet downloads packages that are never actually used?

**Comment by eerhardt** [comment]
> Roslyn needs to upgrade their existing dependences on shipped .NET packages because NuGet downloads packages that are never actually used?

That is one reason. But the more important reason is this: when Roslyn ships its official version, it shouldn't have a dependency on a pre-release version of .NET. It should be dependent on the same version of .NET that is shipping in the official installer.

One issue we are trying to figure out is: how do we get daily builds to act more like how the officially shipped build is going to work? How can we smoothly and efficiently flow packages between these 4 repos?

**Comment by davkean** [comment]
I'm not talking about pre-release packages; that makes sense to me, if we ship dependencies on pre-release packages we should agree on them due to breaking changes, etc that happens during releases.

However, I'm talking about non-prerelease packages such as [System.Runtime](http://www.nuget.org/packages/System.Runtime/4.0.10).

**Comment by eerhardt** [comment]
@piotrpMSFT @ericstj - please confirm the following statement:

"It is **not** required that Roslyn upgrade their existing dependencies that are to previously released CoreFX packages."

For example, if a Roslyn project has a reference to "System.Runtime 4.0.0", (note no -prerelease), that dependency is 100% correct.

**Comment by blackdwarf** [comment]
@piotrpMSFT @eerhardt what is the story here? Did we do this?

**Comment by eerhardt** [comment]
I think this is done.  Closing.
