### ISSUE TITLE
`dotnet publish /path/to/project` fails to parse JSON

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#1548]
Ubuntu 14.04, CLI version 1.0.0.001509-1.

Works when run from the folder that contains the `project.json`.

```sh
$ dotnet publish src/scratch/project.json
Publishing repro for .NETStandardApp,Version=v1.5/ubuntu.14.04-x64
Invalid JSON end. Unprocessed token {.
Published 0/1 projects successfully

$ dotnet publish src/scratch/project.json
Publishing repro for .NETStandardApp,Version=v1.5/ubuntu.14.04-x64
Invalid JSON end. Unprocessed token {.
Published 0/1 projects successfully

$ cd src/scratch/ && dotnet publish
Publishing repro for .NETStandardApp,Version=v1.5/ubuntu.14.04-x64
Project repro (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Published to /home/andrew/src/scratch/bin/Debug/netstandardapp1.5/ubuntu.14.04-x64/publish
Published 1/1 projects successfully
```

```json
{
    "name": "repro",

    "compilationOptions": {
        "emitEntryPoint": true
    },

    "content": [ "../foo" ],

    "frameworks": {
        "netstandardapp1.5": {
            "imports": [ "dnxcore50", "portable-net45+win8" ],
            "dependencies": {
                "NETStandard.Library": "1.0.0-rc3-23817"
            }
        }
    },

    "runtimes": {
        "ubuntu.14.04-x64": { }
    }
}
```

**Comment by victorhurdugaci** [comment]
You have an extra comma in the `runtimes` property: `"ubuntu.14.04-x64": { },`

**Comment by andschwa** [comment]
I caught that removed it, same result. Running it through a full linter right now (but was experiencing this with other valid `project.json` files.

**Comment by andschwa** [comment]
JSON linter says it's valid (given the edit).

**Comment by andschwa** [comment]
Something *has* to be up with my machine I think, this used to work just fine, and it repros with every version of dotnet and dotnet-nightly I tried (and all the `project.json` files I have laying around).

**Comment by andschwa** [comment]
It has to be something effed up on my machine, I couldn't repro on a new VM. Time to make a new VM I guess.

**Comment by andschwa** [comment]
Major case of PEBKAC. I had a malformed `project.json` in my home directory (where I was running from), which dotnet was picking up before the one in the folder. Sorry for filing!

**Comment by victorhurdugaci** [comment]
Curious... Why was that project picked up?

**Comment by andschwa** [comment]
Well, my `cwd` was my home directory. CLI probably ought to ignore anything in `cwd` entirely if a path to a `project.json` file (or project folder) is specified.

I'm refactoring a build script to be location agnostic, which is why I was running outside of the project tree.

**Comment by brthor** [comment]
@andschwa sounds like there's a real bug with publish picking anything else up but the project you specified
