### ISSUE TITLE
Difference between dnx/dnu and dotnet?

### ISSUE THREAD

**Issue by StefH** [dotnet/cli#1555]
Probably this question has been asked before, but I'm kind of lost here.

Is the **dnu/dnx** deprecated, and will the **dotnet** be the final solution?

**Comment by davidfowl** [comment]
> Is the dnu/dnx deprecated, and will the dotnet be the final solution?

In RC2 yes. The .NET CLI will supersede dnx and dnu.

**Comment by blackdwarf** [comment]
The question has been answered and our plans are known for some time now. For additional context I suggest reading the [roadmap blog post](https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/) as well as ["Changes to project.json" blog post](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/).
