### ISSUE TITLE
Visual Studio 2015 integration?

### ISSUE THREAD

**Issue by StefH** [dotnet/cli#1556]
Is there already integration from dotnet with VS 2015 ?

**Comment by davidfowl** [comment]
Nope. It'll be released with RC2

**Comment by StefH** [comment]
What will be the release plan after RC2, will there a final version after this?
Or some more RC versions ?

Can you share more details about the release plan?

**Comment by Eilon** [comment]
@richlander this is your territory.

**Comment by blackdwarf** [comment]
There is a roadmap written on the [.NET Blog](https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/) that should answer all of these questions. Will close this issue.
