### ISSUE TITLE
Easy text file / list defining all the supported frameworks

### ISSUE THREAD

**Issue by StefH** [dotnet/cli#1557]
Some time ago I tried to create a simple list in a text-file which defines all the possible frameworks which are supported.

See this location for that text file:
https://raw.githubusercontent.com/StefH/UZipDotNet/master/UZipDotNet/src/UZipDotNet/_frameworks.txt

Can somebody please review and comment if something is missing or wrong ?

Many thanks !

**Comment by piotrpMSFT** [comment]
@StefH thanks for the list you referenced. It seems reasonable for the frameworks it lists. TargetFrameworks are intentionally unbounded so I'm not sure that an authoritative and exhaustive document is feasible, but I think this list will be a useful reference for many!
