### ISSUE TITLE
dotnet build with emitEntryPoint = true doesn't product an exe

### ISSUE THREAD

**Issue by ayende** [dotnet/cli#1558]
I  have the following project, as you can see, it is set to emit an entry point:

https://github.com/ayende/ravendb/blob/temp/src/Raven.Server/project.json#L12

I'm pretty sure that I'm missing something fundamental, but I can't get this to produce an executable.
```
D:\ravendb-4.0\src\Raven.Server> dotnet -v run
Project Sparrow (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Raven.Client (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Voron (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Raven.Server (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Running D:\ravendb-4.0\src\Raven.Server\bin\Debug\dnxcore50\win7-x64\Raven.Server.exe
The system cannot find the file specified
```

The code compiles file (that is, dotnet build reports no error).

**Comment by ayende** [comment]
Also: 
```
.NET Command Line Tools (1.0.0-beta-001517)

Product Information:
 Version:     1.0.0-beta-001517
 Commit Sha:  3be6ca2b0a
````

**Comment by akoeplinger** [comment]
The reason is that the ".exe" in the dnxcore50 case is a native bootstrapper that boots coreclr and then runs the entrypoint in <name of exe>.dll, e.g. on OSX the native bootstrapper doesn't even have the .exe extension.

You need to build for e.g. "frameworks: net451" to get a managed .exe that contains IL.

**Comment by akoeplinger** [comment]
Oh, I missed the fact that it says "cannot find the file specified" (== the native bootstrapper), that looks like a bug.

**Comment by pakrym** [comment]
https://github.com/dotnet/cli/issues/1560

**Comment by ayende** [comment]
@akoeplinger Yes, the issue isn't so much that the exe isn't being created.
It is that I can't run anything, because it doesn't find the right file.

Also, please note that I'm trying this on Windows.

This same code run fine when running it using dnx.

**Comment by ayende** [comment]
Just to add to this, based on the notes about dnx wrap, I stopped using a dll wrapped project and just used the source directly.
That gave me the ability to properly compile and generate an executable
