### ISSUE TITLE
add CentOS builds to CI

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#156]

**Comment by brthor** [comment]
If we could get unblocked on `dotnet restore` in docker, this would be much easier. We wouldn't need to spin up any CentOS CI machines.

**Comment by piotrpMSFT** [comment]
We already have CentOS CI machines for CoreFx [and openSUSE, in fact], just like we do for Ubuntu. We're going to piggyback on that infrastructure again.

**Comment by Sridhar-MS** [comment]
But we have some hard-coded reference to runtime identifiers. One place I know of is [here](https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Compiler/Program.cs#L385). We need to make sure that the CLI is aware of this new [centos](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json#L168) runtime identifier or if possible make the CLI completely agnostic of runtime identifiers.

**Comment by piotrpMSFT** [comment]
These are the bugs we need to shake out.

**Comment by piotrpMSFT** [comment]
@Sridhar-MS once we enable tests on CentOS this should be complete. Otherwise, CI is running there already. Thanks for pushing this forward, @Sridhar-MS!

**Comment by brthor** [comment]
Fixed #722
