### ISSUE TITLE
Wrapper project pdb outputs location is resolved based on wrong base directory

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#1560]
`D:\github\ravendb\src\Raven.Server\dnxcore50\GeoAPI.pdb'` instead of `d:\github\ravendb\libs\GeoAPI\dnxcore50\GeoAPI.pdb`
https://github.com/dotnet/cli/issues/1558

**Comment by davidfowl** [comment]
Which wrapper project? This a `dnu wrap` thing?

**Comment by pakrym** [comment]
@davidfowl https://github.com/ayende/ravendb/blob/temp/libs/GeoAPI/project.json

**Comment by davidfowl** [comment]
Ah I see. This is dnu wrap left over :smile:

**Comment by pakrym** [comment]
We support this? Should i fix it?

**Comment by ayende** [comment]
What would be the _proper_ way to handle such things in dotnet cli now?

**Comment by davidfowl** [comment]
I just took a look, we'll need to support this until we have a replacement for raw assembly refs.
