### ISSUE TITLE
Produce "portable app" publish layout

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1561]
In order to produce "portable apps", we need to adjust the publish behavior somewhat.

First, when publishing without the `--runtime` switch, we are no longer going to select an appropriate RID. Rather we will publish in the "portable app" mode, using only a TFM target. If `--framework` is specified, we will use that, however if it is not, we will default to the most appropriate TFM as we do today.

Next, we will take all the assets defined in the `runtime` and `native` sections of the RID-less target of the lock file and publish them to the output directory (as we do with normal RID-ful publishing).

Finally, we will take all `subtargets` defined in the packages contained in the RID-less target and publish them into a folder structure that preserves their runtime-specific data. For example, consider the following target library in the lock file:

```json
{
  "targets": {
    ".NETStandardApp,Version=v1.5": {
      "System.Data.SqlClient/4.0.0": {
        "compile": {
          "ref/netstandard1.5/System.Data.SqlClient.dll": {}
        },
        "subtargets": {
          "runtime": {
            "runtimes/unix/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "unix" },
            "runtimes/win7-x64/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "win7-x86" }
          },
          "native": {
            "runtimes/win7-x64/native/sni.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/native/sni.dll": { "rid": "win7-x86" }
          }
        }
      }
    }
  }
}
```

The publish output for this package would be as follows:

```
OUTPUTDIR/
    runtimes/
        unix/
            lib/
                netstandard1.5/
                    System.Data.SqlClient.dll
        win7-x64/
            native/
                sni.dll
            lib/
                netstandard1.5/
                    System.Data.SqlClient.dll
        win7-x86/
            native/
                sni.dll
            lib/
                netstandard1.5/
                    System.Data.SqlClient.dll
```

/cc @davidfowl @piotrpMSFT @pakrym

**Comment by GuardRex** [comment]
@anurse Are `Debug` and `Release` relevant in the published output for the portable app projects?
```
OUTPUTDIR/
    Debug
        runtimes/
            ...
    Release
        runtimes/
            ...
```

**Comment by anurse** [comment]
No, Debug/Release will be pivoted as different `OUTPUTDIR`s altogether

**Comment by xanather** [comment]
Does this mean it will be possible to publish linux/mac binaries on windows (a nice feature of the older DNX/DNVM)?

**Comment by anurse** [comment]
@xanather That was always possible, this doesn't break that. But yes, you can publish apps for all platforms on all platforms. It just takes some command line tweaks.
