### ISSUE TITLE
Where are the symbol files for the native components?

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/cli#1566]
The dotnet installer seems to drop a random set of pdb files for native components, but not useful ones. Eg I see `ryujit.pdb`  but not `coreclr.pdb`.

Is there a separate symbol package somewhere? Or are the windows PDBs indexed?

**Comment by piotrpMSFT** [comment]
Symbols will be published to symbol server and stripped for MSI. Zip should contain all symbols.

**Comment by piotrpMSFT** [comment]
CLI no longer builds any native components. Those we consume come from the dotnet/core-setup repo.
