### ISSUE TITLE
[DotNet.ProjectModel.Server] Exception when global.json has a syntax error

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1569]
I am opening existing project (simplest class lib), that has following global.json:

{
    "sources": [ "src", "test" ]1
}

DTH does not send any events and trace log contains this exception below. It blocks project completely, since we base on DTH event to initialize project (no references, no restore etc). It used to initialize OK, and sent a global error pointing to global.json error (compare with dnx behavior)

	info: OpenChannel[0]
	      Process ID 22444
	info: OpenChannel[0]
	      Listening on port 5580
	info: OpenChannel[0]
	      Client accepted 127.0.0.1:5580
	info: Microsoft.DotNet.ProjectModel.Server.ProcessingQueue[0]
	      Start
	info: Microsoft.DotNet.ProjectModel.Server.ProcessingQueue[0]
	      OnReceive ((2cf042dc2dd443c3bd6e6bedc410b7e5, ProtocolVersion, 0) -> {
	        "Version": 4
	      })
	info: Microsoft.DotNet.ProjectModel.Server.ProtocolManager[0]
	      Initializing the protocol negotiation.
	info: Microsoft.DotNet.ProjectModel.Server.ProtocolManager[0]
	      Protocol negotiation successed. Use protocol 4
	info: Microsoft.DotNet.ProjectModel.Server.ProtocolManager[0]
	      Respond to protocol negotiation.
	info: Microsoft.DotNet.ProjectModel.Server.ProcessingQueue[0]
	      OnSend ((2cf042dc2dd443c3bd6e6bedc410b7e5, ProtocolVersion, 0) -> {
	        "Version": 4
	      })
	info: Microsoft.DotNet.ProjectModel.Server.ProcessingQueue[0]
	      OnReceive ((2cf042dc2dd443c3bd6e6bedc410b7e5, Initialize, 1) -> {
	        "Configuration": "Debug",
	        "ProjectFolder": "D:\\dd\\WTE\\Main\\TestResults\\Deploy_antonpis 2016-02-24 13_40_08\\Out\\MS.VS.PS.DotNet\\TestSolution\\Restore\\GlobalJsonError\\ProjectA",
	        "Version": 4
	      })
	info: Microsoft.DotNet.ProjectModel.Server.ProjectManager[0]
	      Begin draining inbox.
	info: Microsoft.DotNet.ProjectModel.Server.ProjectManager[0]
	      Received Initialize
	info: Microsoft.DotNet.ProjectModel.Server.ProjectManager[0]
	      Set context protocol version to 4
	info: Microsoft.DotNet.ProjectModel.Server.ProjectManager[0]
	      Finish draining inbox.
	Unhandled Exception: System.AggregateException: An error occurred while writing to logger(s). (Input string was not in a correct format.) ---> System.FormatException: Input string was not in a correct format.
	   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
	   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
	   at System.String.Format(IFormatProvider provider, String format, Object[] args)
	   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
	   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
	   --- End of inner exception stack trace ---
	   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
	   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
	   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, String message, Object[] args)
	   at Microsoft.DotNet.ProjectModel.Server.ProjectManager.ProcessLoop()
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
	   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by abpiskunov** [comment]
Same problem I see when I have global.json OK, but project.json have syntax error on one of the projects in solution. Note: something is wrong there since error in one project breaks whole model.server and other projects which are fine also don't receive any events from the DTH.

My project.json: 

{
  "version": "1.0.0-*",
  "dependencies": {
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
      }
    },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-*",
        "System.Collections": "4.0.11-*",
        "System.Linq": "4.0.1-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-*"
      }
    }
  }
}
}

(it has extra ] at the end of the file)

**Comment by troydai** [comment]
Ok. I take this.

**Comment by troydai** [comment]
Fixed in b63705198c0a043f5dc09f6df56906b43d2e79ad

**Comment by abpiskunov** [comment]
After fixing syntax error in global.json, global error that was sent before never cleaned after successful restore. When there is a syntax error we now receive :

info: Microsoft.DotNet.ProjectModel.Server.ProcessingQueue[0]
      OnSend ((11ba360640764df197a89e9c6a7ba95e, Error, 2) -> {
        "Message": "Invalid JSON object syntax. Expected ',' or '}'.",
        "Path": "D:\\dd\\WTE\\Main\\TestResults\\Deploy_antonpis 2016-03-09 06_05_20\\Out\\MS.VS.PS.DotNet\\TestSolution\\Restore\\GlobalJsonError\\global.json",
        "Line": 2,
        "Column": 33
      })

But when error is fixed we don't receive a new empty Error that dnx used to send to clean global error state.

**Comment by troydai** [comment]
What's the clean global error state VS is expected? An error message with payload been empty?

**Comment by troydai** [comment]
Behaviour updated in 628f54c77cba64849bddbaec2bd1f0a46cd685b4
