### ISSUE TITLE
Replacement for dnx clr 

### ISSUE THREAD

**Issue by cheers00** [dotnet/cli#1571]
In one of our projects, we are using couple of CLR classes like ```System.Timer``` and ```System.IO.Pipes```. We were able to run the project using dnx clr runtime.

example
```
dnvm use 1.0.0-rc2-16541 -r clr -arch x64
dnu restore
dnx run
```
Now, how can we access clr runtime using new dotnet cli? ```dotnet build``` fails to compile our code.

Thanks

**Comment by blackdwarf** [comment]
@cheers00 did you add proper packages that contain those APIs?

**Comment by cheers00** [comment]
@blackdwarf. Thanks. I found that corefx has ```System.IO.Pipes``` and nuget package is also available.
Wondering if I should use ```System.Threading.Timer``` instead of ```System.Timers```

**Comment by piotrpMSFT** [comment]
That question will be better answered in CoreFx :)
