### ISSUE TITLE
Remove compile as a top level command

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1574]
It's no longer supposed to be used by anyone but `dotnet build` and since it's intrinsic, shouldn't be replaceable.

/cc @piotrpMSFT @blackdwarf

**Comment by blackdwarf** [comment]
@davidfowl agreed, people are getting confused. Who do we assign this to?

**Comment by davidfowl** [comment]
I'll do it. Let's see what breaks!

**Comment by blackdwarf** [comment]
Go for it! Ya canna fix it unless its broken. :)

**Comment by davidfowl** [comment]
Done
