### ISSUE TITLE
dotnet /? --> ArgumentException

### ISSUE THREAD

**Issue by bendono** [dotnet/cli#1575]
Wanting to see what arguments are available, I tried "dotnet /?", which resulted in an ArgumentException.
![error](https://cloud.githubusercontent.com/assets/846533/13310512/e6880b94-dbc9-11e5-8cfa-644cfe7fdf38.png)

Environment: Windows 10, English

**Comment by blackdwarf** [comment]
Sounds like we should fail a bit more gracefully for this case. However @bendono CLI supports only - || -- style switches. The cmd-like /<arg> switches are not supported. 

/cc @piotrpMSFT @brthor

**Comment by brthor** [comment]
I agree this should be handled more gracefully. Ultimately we should just decide what the proper error message is here.

We could show a CommandUnknownError fairly cheaply by simply try catching the ResolveExecutablePath function. (If it throws it didn't find a command)

Detecting that this is an old style switch would take some more thought and likely come with some caveats.

**Comment by blackdwarf** [comment]
@brthor nope, no detection, just a graceful failure. We should not be surfacing exceptions to users for such small things. :)

**Comment by bendono** [comment]
Hi @blackdwarf  and @brthor. I have retested using the latest CLI installer.
This issue seems to be resolved now.

Here is the new output:
   C:\Users\Ben\foo2>dotnet /?
   No executable found matching command "dotnet-/?"

This can probably be closed now.
Thanks.

**Comment by blackdwarf** [comment]
@bendono thanks! Closing this.
