### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by bendono** [dotnet/cli#1576]
After the crash in #1575, I decided to review the dump. (I have procdump (SysInternals) setup on my machine to create a full (/ma) dump on any application crash). First things first, I checked the coreclr details in hopes of finding a compatible SOS.
![coreclr](https://cloud.githubusercontent.com/assets/846533/13310720/d0fe82a6-dbcb-11e5-99ff-33ecba7b2019.png)

Unknown to me, it turns out that it was being executed from Program Files\dotnet\bin folder. So I searched there for SOS.dll. I found it in Program Files\dotnet\bin\dnx. So I loaded it, but found that the version was not correct.
![sos](https://cloud.githubusercontent.com/assets/846533/13310729/ef2b420a-dbcb-11e5-9af3-d3514bbfbcea.png)

Luckily some of the SOS commands still work, but incompatible versions is a recipe for trouble. Can I expect that the correct SOS will be an future update?
Also, as in full framework dumps, SOS.dll is in the same folder as CLR.dll, so many people are used to doing ".loadby sos clr", which will load SOS.dll from the same folder as CLR.dll is being executed from. For CoreCLR, is there any reason that SOS.dll cannot be located in the same folder as CORECLR.dll is in? If it is not, then we will need to manually load it from a specific path, which is undesirable.

**Comment by noahfalk** [comment]
@mikem8361 @gkhanna79 
I believe Gaurav recently put SOS into the coreclr NuGet packages adjacent to coreclr, and Mike can confirm that sos is being correctly duplicated from there into the final output produced for a CLI app.

**Comment by mikem8361** [comment]
I installed the version 1.0.0.001540 msi which seems to be the latest on the cli GitHub page and sos.dll wasn't installed anywhere.  I assume that this is because it is older than the Ubuntu package because the Ubuntu version does have the libsos.so (and libsosplugin.so) files.

**Comment by livarcocc** [comment]
Please, re-activate if you are still hitting this.
