### ISSUE TITLE
Commands to be reviewed for the future

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#1578]
This issue lists the overall commands that need review and design on how they work. 
## Commands
- [x] dotnet-commands (#2)
- [x] dotnet-clean (#16)
- [x] dotnet-install-package (#76)
- [x] dotnet-api (#106)
## Intra-command interaction
- [x] Dotnet + Nuget interaction (#32)

**Comment by benrr101** [comment]
What's the status on these commands? I see dotnet-install-package and dotnet-commands have checks beside them, but neither of them appear to be in the latest build (preview3-003592)

**Comment by gulshan** [comment]
If `dotnet install` can be restricted to donet cli tools only, it be very useful IMHO.

**Comment by livarcocc** [comment]
All the other tracking issues have been closed. Closing this one as well. We are working on dotnet install tools for the .NET Core 2.1 release.
