### ISSUE TITLE
dotnet run generate System.BadImageFormatException

### ISSUE THREAD

**Issue by ayende** [dotnet/cli#1579]
To reproduce, get: github.com/ayende/ravendb - temp branch.

Go to `src/Raven.Server`.

Run dotnet restore.

run dotnet run

```
D:\ravendb-4.0\src\Raven.Server [v4.0 +1 ~0 -0 !]> dotnet run
Project Lucene.Net (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Sparrow (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Raven.Client (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Voron (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Project Raven.Server (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'Raven.Server.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
```

Using version:

```
Version:     1.0.0-beta-001517
Commit Sha:  3be6ca2b0a
```

**Comment by ayende** [comment]
This is on Windows machine, by the way

**Comment by blackdwarf** [comment]
@ayende just for additional info, which version of Windows?

/cc @davidfowl @anurse

**Comment by ayende** [comment]
Windows 8 64 bits

**Comment by ayende** [comment]
@blackdwarf Anything on this? Is there any workaround? Something we can do?
This is blocking our move to dotnet CLI entirely.

**Comment by blackdwarf** [comment]
@ayende I believe @davidfowl is taking a look at this, but I haven't got the latest.

**Comment by davidfowl** [comment]
I tried it and it works! I'm on windows 10 though.

**Comment by ayende** [comment]
Correct, I'm able to run this successfully on Windows 10.


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by piotrpMSFT** [comment]
Can you try deleting your package cache? We will get a win8 image and investigate, but this may unblock you...

**Comment by ayende** [comment]
C:\Users\Ayende\.nuget\packages ? Right?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
Right now, on Windows 8, I've deleted all the packages, run dotnet restore from scratch on the project root dir, and tried to run dotnet run. I'm getting:

```
D:\ravendb-4.0\src\Raven.Server [temp...origin/temp]> dotnet --verbose run
Object reference not set to an instance of an object.
```

This is on `1.0.0-beta-001517`, I wasn't able to find a way to make it give a better error message.

**Comment by ayende** [comment]
Okay, I run dotnet restore on each individual folder in the solution.
And I was finally able to run it again. 
On Windows 8, after clearing all the packages are restoring from scratch, I'm still getting bad format exception

**Comment by davidfowl** [comment]
@ayende is this resolved?

**Comment by ayende** [comment]
On Windows 8, still using:
https://github.com/ayende/ravendb/tree/temp

I run the following sequence of commands:

rdb> dotnet restore
rdb\src\Sparrow> dotnet restore
rdb\src\Sparrow> dotnet build
rdb\src\Voron> dotnet restore
rdb\src\Voron> dotnet build
rdb\src\Raven.Client> dotnet restore
rdb\src\Raven.Client> dotnet build
rdb\src\Raven.Server> dotnet restore

Then I get:

```
error: Unable to load package 'System.Diagnostics.StackTrace'.
error: Failed to download package from 'https://www.myget.org/F/aspnetvnext/api/v2/package/System.Console/4.0.0-rc2-2382
6'.
error: An error occurred while sending the request.
error:   The connection with the server was terminated abnormally
D:\ravendb-dnx\src\Raven.Server [temp]> dotnet build
Project Raven.Server does not have a lock file.
Project Raven.Server does not have a lock file.
D:\ravendb-dnx\src\Raven.Server [temp]>
```

Running restore multiple times always errors on _something_.

I don't mind throwing the whole branch again and moving from DNX to CLI again, but are there any documentation about how to do that?
What nuget feeds to use, what is the available packages, etc?

**Comment by ciel** [comment]
Has there been any update on this? I'm encountering this same problem.

**Comment by davidfowl** [comment]
@ciel and @ayende If you can reproduce with the final RC2 bits reopen the issue
