### ISSUE TITLE
NO_PUBLICKEY B02C46DF417A0893

### ISSUE THREAD

**Issue by GeertVL** [dotnet/cli#1580]
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

gpgkeys: HTTP fetch error 7: couldn't connect: eof
gpg: no valid OpenPGP data found
gpg: Total number processed: 0

Is this changed and so the installation instructions not updated?

**Comment by blackdwarf** [comment]
@GeertVL which distro? Also, did you retry, sounds like it could be transient (as in, gpgkeys has problems reaching the HTTP server).

/cc @brthor

**Comment by brthor** [comment]
@GeertVL Can you please provide distro information, and the output of 
`ping apt-mo.trafficmanager.net`

**Comment by leors75** [comment]
Same problem here. In my case, ping returns:

PING apt-eus.cloudapp.net (191.237.88.25) 56(84) bytes of data.
Request timed out.
^C
--- apt-eus.cloudapp.net ping statistics ---

My distro is Ubuntu.
