### ISSUE TITLE
Publish folder structure

### ISSUE THREAD

**Issue by soeron** [dotnet/cli#1581]
Greetings,
Currently when publishing app using either `dotnet build` or `dotnet publish` and using `-o switch` flattens everything in single directory.
But I think there should be a way to copy the solution hierarchy in the published folder. Some more organization is always welcomed.
For example if I have sample solution folder structure:

```
|Solution Folder
\_Logical Sub-Folder
  \__Libraries
  |  \___Lib 1 Project
  |  \___Lib 2 Project
  \__Executable Project
```

When `dotnet build -o build\SomeApp "Executable Project"` is executed will be nice if the current solution structure be copied to the output directory for examele:

```
|build\SomeApp
  \__Libraries
  |  \___Lib1.dll
  |  \___Lib2.dll
  \__SomeApp.exe
```

The dependency redirection can still be made with SomeApp.exe.config files.
Even further the project.json should include option to set absolute/relative publish destination per project. Because some of the projects in the sub-folders may not be referenced directly by the executing application and should be loaded runtime. That way a developer can set per project its output destination and then just build all the projects in the solution (which kind of makes publish useless?)
I am using build scripts currently to get that behavior but if it is part of the supported scenarios will be much better way of doing it.
Also I think there should be option to set runtime assemblies output directory to the publish command.
For example: `--runtime-path runtime` which should be relative to the output folder.

**Comment by piotrpMSFT** [comment]
@soeron, I think what you're asking for is exactly what -b does [not -o]. Can you take a look and confirm?

@pakrym FYI

**Comment by davidfowl** [comment]
Why should we support this?

**Comment by soeron** [comment]
Greetings,
@piotrpMSFT -b doesn't do what I was asking for. It produces something like this:
```
|build
 \_src
  \_Logical Sub-Folder
   \_SomeApp
    \_bin
     \_Release
      \_dnx451
       \__SomeApp.exe
       \__win7-x64
           \___Lib1.dll
           \___Lib2.dll
           \__SomeApp.exe
```
Just a deeper nesting, and the same structure for the other projects.
That is on `dontnet build`.
Using `dotnet publish` gives and error

> Could not find a part of the path 'd:\Projects\Visual Studio\SomeApp\src\Logical Subfolder\SomeApp\bin\Release\dnx451\win7-x64\SomeApp.exe'.
Using `dotnet compile` doesn't compile dependencies and gives and error, that they can't be found. When compile the dependencies earlier it outputs the .exe only in the deeper structure.

@davidfowl I think that this is mainly project organizational issue. It could be done with command scripts but feeling lousy, while having great IDE to ease the job. Imagine large suite of software, which share common libraries, but may depend on different items. It will be far more organized in logical folder than in flatten one.

**Comment by piotrpMSFT** [comment]
With the move to csproj we have access to the same output directory controls as available in classic dotnet. The dotnet/sdk repo does a nice job of using this to create a fairly custom layout structure for all of their projects.
