### ISSUE TITLE
Generate RID fallback graph in app.deps.json

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#1584]
Based upon https://github.com/dotnet/cli/blob/anurse/update-deps-json-spec/Documentation/specs/runtime-configuration-file.md#portable-deployment-model, app.deps.json needs to have the RID fallback graph for the host to consume to handle FAT packages.

CC @davidfowl @anurse @glennc @schellap @ericstj

**Comment by piotrpMSFT** [comment]
@gkhanna79 is this a duplicate of #1562?

**Comment by gkhanna79** [comment]
No, this is about generating RID fallback graph and I didn't see that reference in the issue you pointed to.

**Comment by davidfowl** [comment]
We decided that we didn't need this today

**Comment by gkhanna79** [comment]
@davidfowl can you share more details on what came out of the discussion?

**Comment by piotrpMSFT** [comment]
@gkhanna79 did you and @davidfowl sync? Can we close this issue?

**Comment by gkhanna79** [comment]
@piotrpMSFT Yes, the POR is that RID fallback graph is going to be part of the .deps.json file for the SharedFramework REDIST. I believe @ellismg is working on it. I am assigning this issue to him.

**Comment by ellismg** [comment]
I believe that @anurse is doing this as part of his work in .NET Publish?  (https://github.com/dotnet/core-proposals/pull/9/files#r54605276)

**Comment by anurse** [comment]
Yep, I filed https://github.com/dotnet/cli/issues/1688 to track that work.
