### ISSUE TITLE
API for OS<->RID Mapping

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#1586]
This will be required by the universal host to commence RID fallback processing for FAT packages. Blocks https://github.com/dotnet/cli/issues/1585. 

See https://github.com/dotnet/cli/issues/1584 for details.

**Comment by ericstj** [comment]
Simple solution is to burn in the same RID that the host is being packaged with.  That'll work fine for the cases where we have granular hosts for every RID.

This is already not the case with RHEL/Centos, so I do think there is a need for something more here.

@anurse you've been maintaining an algo in the CLI and previously DNX that did this, what are your thoughts on what this should be?
/cc @ellismg

**Comment by piotrpMSFT** [comment]
@gkhanna79 any API we have will be managed. How can the host take advantage of it?

**Comment by piotrpMSFT** [comment]
chatted with @gkhanna79 and this is no longer needed.
