### ISSUE TITLE
run-build.ps1 uses DOTNET_INSTALL_DIR to install stage0, the build program should use the env variable as well

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1587]
Right now, if something else redefines DOTNET_INSTALL_DIR, it breaks the build script, as run-build.ps1 will check for stage0 using the environment variable, but the build script itself has that hard coded based on the root of the script.

**Comment by livarcocc** [comment]
To be clear, this is the part that does not use the environment variable:

[Target]
        public static BuildTargetResult LocateStage0(BuildTargetContext c)
        {
            // We should have been run in the repo root, so locate the stage 0 relative to current directory
            var stage0 = DotNetCli.Stage0.BinPath;

            if (!Directory.Exists(stage0))
            {
                return c.Failed($"Stage 0 directory does not exist: {stage0}");
            }

            // Identify the version
            var version = File.ReadAllLines(Path.Combine(stage0, "..", ".version"));
            c.Info($"Using Stage 0 Version: {version[1]}");

            return c.Success();
        }

**Comment by livarcocc** [comment]
Fix can probably go here: https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/Utils/DotNetCli.cs#L34

**Comment by brthor** [comment]
@livarcocc Given that this is the build, I feel that it should generally stick things in the same place.

What do you think of explicitly unsetting that environment variable prior to calling install.ps1 in the build scripts?

**Comment by livarcocc** [comment]
That would work for me as well. I guess my point is that the two "scripts" should be looking at the same place, no matter what. Given that, unsetting the variable or not becomes orthogonal. We should avoid duplication of code, which is what this is and it has bitten me just now.

**Comment by piotrpMSFT** [comment]
@krwq is working on a rebuild of the scripts. 

@krwq, can you link to the design doc + issue tracking your work?
