### ISSUE TITLE
Running dotnet restore on a project which has tools, creates an artifacts folder in the project directory.

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#1588]
1. Create a new project 
2. Add a tool (eg dotnet-publish-iis)  to the project.json
3. Run dotnet restore. 

This ends up creating a artifacts folder in the project directory with the below hierarchy 
 artifacts -> Tools -> dotnet-publish-iis -> project.lock.json
On VS this shows up as a folder under the project hierarchy on the solution explorer. 

![artifacts in project folder](https://cloud.githubusercontent.com/assets/1521254/13330224/bfaa234e-dbac-11e5-8e2b-0e0ef04b4260.JPG)

**Comment by prafullbhosale** [comment]
cc @BillHiebert @sayedihashimi

**Comment by blackdwarf** [comment]
@prafullbhosale what is the issue? The fact that VS shows this?

**Comment by BillHiebert** [comment]
Yes, and as much as possible VS is moving towards getting temporary files out of the project directory especially with the move to using .tfsignore\.gitignore. Every time a temporary file is dropped into the project folder these files need to be manually updated, and the project system needs to be updated to exclude this folder\file. Control over the location of temporary outputs is really important.

**Comment by blackdwarf** [comment]
@BillHiebert is there a convention on names of things that VS hides by default?

**Comment by brthor** [comment]
There is a new design coming in for the tools experience which will ultimately remove this directory.

**Comment by blackdwarf** [comment]
@prafullbhosale can you provide more details on how is this blocking you?

**Comment by prafullbhosale** [comment]
Its not a blocking issue.

**Comment by piotrpMSFT** [comment]
@brthor can you resolve this against the issue you mentioned?

**Comment by blackdwarf** [comment]
This is not reproing anymore, `.artifacts` is not created anymore. Closing.
