### ISSUE TITLE
Blank lines missing

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#1589]
`dotnet-ef` does something similar to the following.

``` C#
Reporter.Output.WriteLine("hello");
Reporter.Output.WriteLine();
Reporter.Output.WriteLine("world");
```

But the output unexpectedly looks like this:

```
hello
world
```

I would expect a blank line to be printed between the lines.

```
hello

world
```

**Comment by piotrpMSFT** [comment]
@brthor, can you take a look?

**Comment by blackdwarf** [comment]
This is still reproing, `dotnet run` is swallowing newlines.

**Comment by svick** [comment]
@blackdwarf It does repro for me on preview2, but not on latest CLI. I believe this was fixed by https://github.com/dotnet/cli/pull/3808.

**Comment by piotrpMSFT** [comment]
closing per @svick
