### ISSUE TITLE
Investigate source indexing in dotnet-compile

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#159]
During `dotnet-compile` we should try to index the source code into the PDBs, including Git metadata and source code download paths where possible (additional metadata in project.json might be required). I talked with @ctaggart at the MVP summit about this (see also aspnet/Universe#131) and we decided to put this down as a potential dotnet-compile feature. Once this repo goes public we can co-ordinate more with him (he has a tool that can do this already, it would fit reasonably well into the whole small-tools ecosystem :))

**Comment by piotrpMSFT** [comment]
Interesting idea. I'd like to look into this when we have some free time.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

Compile invocation will be moving to csharp.targets.
