### ISSUE TITLE
re-enable build tests for net2, net40 and net461

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1591]
I disabled these as part of https://github.com/dotnet/cli/pull/1590.

need to enable them back once we have net2, net40 and net461 installed in the VSO windows machines that run our builds.
# test/dotnet-build.Tests/BuildOutputTests.cs

Just add net20, net40 and net461 back.

```
[Theory]
          [InlineData("net20", false, true)]
          [InlineData("net40", true, true)]
          [InlineData("net461", true, true)]
          [InlineData("dnxcore50", true, false)]
          public void MultipleFrameworks_ShouldHaveValidTargetFrameworkAttribute(string frameworkName, bool shouldHaveTargetFrameworkAttribute, bool windowsOnly)

```

**Comment by livarcocc** [comment]
I actually think that once we re-enable these tests, we should add having these frameworks as part of the pre-requisites of the cli, otherwise, people who try the build without having them are going to end up having a frustrating build failure.

Also, I do NOT think the right approach is to skip them if the frameworks are not installed, as that could lead to a false sense of security.

**Comment by livarcocc** [comment]
cc @pakrym

**Comment by piotrpMSFT** [comment]
@blackdwarf is this a real scenario? why is net20 and net40 at all in the picture?

**Comment by davidfowl** [comment]
Not sure it should be a prerequisite. We're actually looking at ways to show targeting packs as packages so this won't be needed just to compile

**Comment by livarcocc** [comment]
The compile piece is fine, the problem is that the test would later fail and stop the build. Which for unaware users of the repo would be frustrating.

**Comment by blackdwarf** [comment]
@livarcocc is this still a thing? How does this change with msbuild work?

**Comment by piotrpMSFT** [comment]
This responsibility now sits in https://github.com/dotnet/sdk. The SDK supports down to net40. If we need support for older Frameworks then please file a feature request there.
