### ISSUE TITLE
dotnet-clean command

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#16]
We need to determine what this does. Is it project specific?

**Comment by blackdwarf** [comment]
I will add a new overall issue to track all of these that cover commands that are not yet implemented. Closing this for that.

**Comment by sayedihashimi** [comment]
@blackdwarf is there a new issue? We are interested in integrating the `clean` command into the .xproj file. I'd like to get details on what's the status of `clean` so that we can plan accordingly on our side.

**Comment by blackdwarf** [comment]
@sayedihashimi it is referenced above (#1578). :) As it looks now, we will not be making `dotnet clean` for v1.

**Comment by niemyjski** [comment]
This functionality needs to be removed from vs if it's not going to be supported on the command line :)

**Comment by GiorgioG** [comment]
@blackdwarf why isn't it making it into v1?
