### ISSUE TITLE
dotnet run applicationBasePath incorrect

### ISSUE THREAD

**Issue by Gillardo** [dotnet/cli#1601]
Updated my project to use latest rc2-16551, and installed the dotnet cli.

Now upon running my website, using the command `dotnet run`, my application base path seems to include the directories `\bin\Debug\dnx451\win7-x64\`

So instead of my application base path being C:\Website\wwwroot, it is now C:\Website\wwwroot\bin\Debug\dnx451\win7-x64\

In my project.json file i have added

```
"webroot" : "wwwroot"
```

which just adds wwwroot onto the path, which aint right.  I have tried setting the applicationBasePath using `WebHostBuilder.UseApplicationBasePath = "wwwroot";` but that does the same.

Running `dnx web` would return the correct path, such as C:\Website\wwwroot

Is this a bug?  Or am i doing something wrong?  Or is this expected?

**Comment by davidfowl** [comment]
Yes it's expected. See https://github.com/aspnet/cli-samples. Also please file these types of bugs on the aspnet repository
