### ISSUE TITLE
How to "find" referenced class libraries

### ISSUE THREAD

**Issue by ToddThomson** [dotnet/cli#1603]
Since we cannot yet use VS2015 to build with dotnet cli, how do you reference class library packages ( these aren't coming from Nuget - they are created internally ) that are part of the overall project? I'm building from the command line.

**Comment by brthor** [comment]
Check out an example here:
https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/TestProjects/TestAppWithWrapperProjectDependency/TestLibrary/project.json

You create a project wrapping these dlls and then reference the project.

**Comment by ToddThomson** [comment]
@brthor Thank-you. To be clear, I want to reference Nuget packages that were originally created as "Class Library Packages" in VS2015. With DNX these were referenced as dependencies and were located using the "projects" property in the global.json file.
With your example, is it the case that I only reference the package dll ( and pdb ) and remove the dependency reference from the main project?

**Comment by blackdwarf** [comment]
Given the age of this issue and the move to csproj, I am going to close this issue, since referencing projects and assemblies will be different than DNX and project.json. Thanks!
