### ISSUE TITLE
The CLI commands do not work well with non ASCII paths

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/cli#1604]
Try creating a folder named - Vigenère

Run command line dotnet restore/build/new

Result:
C:\temp>dotnet build C:\temp\Vigenère
Could not find a part of the path 'C:\temp\Vigen├â┬¿re\project.json'.

**Comment by blackdwarf** [comment]
@yishaigalatzer which version of Windows?

**Comment by yishaigalatzer** [comment]
Win 10 @billhiebert

**Comment by gkhanna79** [comment]
@schellap Can you please confirm if this is the same issue as the one you are looking into?

**Comment by blackdwarf** [comment]
@piotrpMSFT did this got solved? I cannot repro this using the latest Preview 3 bits.

**Comment by blackdwarf** [comment]
Closing this as I cannot repro it using the latest bits. If it still repros, please reopen.
