### ISSUE TITLE
dotnet --version-minimal

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#1607]
For our CoreClr gating mechanism and for anywhere else we want to machine read the version it would be very helpful if there was a "--version-minimal" which only returned the version without the OS version and everything else.

So, instead of
```
.NET Command Line Tools (1.0.0-beta-001540)

Product Information:
 Version:     1.0.0-beta-001540
 Commit Sha:  6aeed1f52d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```
it would output
```
1.0.0-beta-001540
```

**Comment by victorhurdugaci** [comment]
Just my 2c: `--version` should return strictly the CLI version and then there should be a second option `--extended-version` (?) that displays what `--version` shows today.

**Comment by davidfowl** [comment]
Just parse the output.

**Comment by blackdwarf** [comment]
@ryanbrandenburg is parsing the output acceptable for now?

**Comment by blackdwarf** [comment]
@victorhurdugaci also, I would actually leave `--version` to show just the version string and provide a `--info` to give you the full shebang.

**Comment by factormystic** [comment]
`--version` should accept additional params for the part of the info you want to see. Then you could have `--version rid` ([same request here](https://github.com/dotnet/cli/pull/1235#issuecomment-186403648)), `--version x.y`, etc to your heart's content.

Or one param that indicates you'd like all the output in a parseable format, like `--version parseable` or whatever.

**Comment by blackdwarf** [comment]
@factormystic ugh, dunno...dislike it. I can understand the need to get **just** the version string, but I would really not like to have a `--version` subsystem of parsing out stuff for various special cases.

**Comment by anurse** [comment]
It sounds kinda scary to start going too deep down the path of complicating the `--version` switch. We have a file in the root of the CLI (`.version`) which has this data in a more easily-parseable way, could you just read that?

**Comment by ryanbrandenburg** [comment]
@anurse this all started because I was unable to locate the .version file on linux. If it is available on all OS's that would be OK too, though slightly less nice since we'd have to special case things for each OS.

**Comment by anurse** [comment]
The `.version` file definitely should be there on Linux... of course you have to use `ls -a` because it starts with `.` and is thus hidden by default

**Comment by ryanbrandenburg** [comment]
I don't see it under usr/share/dotnet/, usr/share/dotnet/bin, usr/share/dotnet/runtime or usr/share/dotnet/debian, even when using ls -a. Could someone else confirm it's there on their linux machine to see if I just have a bad install somehow?

**Comment by blackdwarf** [comment]
@ryanbrandenburg I don't see it either on Ubuntu with the latest installed.

**Comment by brthor** [comment]
Clean docker image, with cli installed via .deb package:

```
root@c11d96627891:/hey# ls /usr/share/dotnet
bin  debian
```

**Comment by eerhardt** [comment]
A discussion between @blackdwarf and @anurse produced the recommendation that `dotnet --version` will output just the version of the CLI with no formatting:  ex. `1.0.0-beta-001880`.  Any "long" version and outputting other information can be handled later as the scenarios for the information arises.

**Comment by ryanbrandenburg** [comment]
Cool. Although, if I might push my luck here, the format that's stored in the .version file on windows and that a couple of our tools expect is "1.0.0.001880", without the "-beta-". It's a small thing to fix on our end, but it seems like whatever the "proper" format is it should be that way everywhere. Unless I'm missing some distinction.

**Comment by eerhardt** [comment]
> the format that's stored in the .version file on windows and that a couple of our tools expect is "1.0.0.001880", without the "-beta-". It's a small thing to fix on our end, but it seems like whatever the "proper" format is it should be that way everywhere. Unless I'm missing some distinction.

@ryanbrandenburg - the new "proper" version format is with the `-beta-` going forward.  New .version files have this format as well.
