### ISSUE TITLE
Missing dll when running MVC functional tests on linux

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#1612]
https://travis-ci.org/aspnet/Mvc/jobs/112065869#L5582

`System.InvalidOperationException : Can not find reference assembly 'System.Collections.dll' file for package System.Collections`

Assigning to @pakrym as he requested.

**Comment by muratg** [comment]
:eyes: :)

**Comment by pakrym** [comment]
https://github.com/dotnet/cli/issues/1613
