### ISSUE TITLE
DependencyModel compilation assembly resolution doesn't work on mono

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#1613]
Because it lacks `FrameworkList.xml` support.

@davidfowl

**Comment by davidfowl** [comment]
Hmmmmm

**Comment by akoeplinger** [comment]
We do have FrameworkList.xml in Mono, or do you mean the CLI doesn't read it yet?

**Comment by pakrym** [comment]
dotnet build reads it, but Microsoft.Extensions.DependencyModel (it's used for dynamic compilation) doesn't

**Comment by blackdwarf** [comment]
@pakrym what is the status of this?

**Comment by pakrym** [comment]
Tracking issue, don't know if we want to fix it right now

**Comment by blackdwarf** [comment]
@pakrym thanks, let's keep it in the RTM milesone and we can triage later.

**Comment by piotrpMSFT** [comment]
I'm pushing this to backlog. We don't have much time left, so pushing out stuff that's not blocking for the time being.

**Comment by blackdwarf** [comment]
Mono is not supported by CLI. Once we add support we will go through all the things.
