### ISSUE TITLE
Will there also be a Cloud Foundry container be available?

### ISSUE THREAD

**Issue by StefH** [dotnet/cli#1617]
Currently I see that Docker is supported, are there also plans to support Cloud Foundry container?

**Comment by blackdwarf** [comment]
@StefH we don't have any plans right now, honestly.

**Comment by piotrpMSFT** [comment]
@StefH what would we need to do to enable such a container to be created from outside CLI repo? I don't think we can support every container/packaging format out there, but I want to be sure we are not blocking the community from building these experiences.

**Comment by piotrpMSFT** [comment]
Closing the issue. If there is work that needs to be done in CLI to unblock this scenario, please do let us know!
