### ISSUE TITLE
Update DNX tools to support netstandard targets

### ISSUE THREAD

**Issue by xanather** [dotnet/cli#1618]
Recently corefx updated its packages to no longer target dnxcore50.
This means intellisense in VSCode and visual studio broke.
Really difficult to write code with .net core at the moment due to this change.

Or release a preview of visual studio CLI tool integration :)

**Comment by davidfowl** [comment]
https://github.com/aspnet/dnx/pull/3367

**Comment by davidfowl** [comment]
Also, omnisharp support is in the dev branch https://github.com/OmniSharp/omnisharp-roslyn/tree/dev

**Comment by xanather** [comment]
Omnisharp support looks interesting might actually use that otherwise regarding DNX VS support how do we install the changes (come through Extensions & Updates in visual studio) so intellisense works again?

**Comment by GuardRex** [comment]
btw - I tried building `omnisharp-roslyn` this morning (being on the edge with latest `dotnet cli`), and it wouldn't build cleanly. The `build` that comes with it broke badly on my unstable feed override (apparently). There were restore issues under `dnxcore50` when I tried `dotnet restore`, and when I stripped out all of the `dnxcore50` framework entries going for a `dnx451` version, it would restore and build, but all I got out of it was a `dll` file and a `pdb` file ... no executable. I really wish that had a known-good CI-type binary that I could rock on.

If you go for it in VS Code @xanather I hope you have better luck than I.

**Comment by davidfowl** [comment]
> Omnisharp support looks interesting might actually use that otherwise regarding DNX VS support how do we install the changes (does it come through Extensions & Updates in visual studio?) so intellisense works again?

You update the DNX. You don't have to update VS tooling.

> btw - I tried building omnisharp-roslyn this morning (being on the edge with latest dotnet cli), and it wouldn't build cleanly. The build that comes with it broke badly on my unstable feed override (apparently). There were restore issues under dnxcore50 when I tried dotnet restore, and when I stripped out all of the dnxcore50 framework entries going for a dnx451 version, it would restore and build, but all I got out of it was a dll file and a pdb file ... no executable. I really wish that we had a known-good CI-type binary that I could rock on.

You used the dev branch right?

**Comment by GuardRex** [comment]
@davidfowl Yes ... I used it from the link that @troydai provided in https://github.com/aspnet/Home/issues/1255#issuecomment-189524280 ... so yes, dev branch. Didn't go so well. However, I'm not blocked. I'm ok ... I can hold on until a VS Code update sets me right.

**Comment by xanather** [comment]
The dev branch of omnisharp-roslyn doesn't even finish properly building for me. Can't work on any of my .net core projects for the time being because of it since I can't handle not having intellisense.

**Comment by piotrpMSFT** [comment]
Since this is tracked in aspnet/dnx#3367, closing this issue.

**Comment by troydai** [comment]
Hi @GuardRex. We pinned the packages version and clone the feed for `omnisharp-roslyn` dev branch. Does it break even when you do __not__ override the feed?

**Comment by GuardRex** [comment]
@troydai I'll try that again and get back to you. But let me ask this: Many team comments seem to indicate that DNX has been almost completely removed from just about everything for those of us on RC2 nightly. @davidfowl said VS Code was similarly close to having its DNX-dependency removed. Is there any even rough timeframe for VS Code to get free of DNX ... a few days? ... a week? ... any idea?
