### ISSUE TITLE
Is there a way to change name of exe from project.json

### ISSUE THREAD

**Issue by KyleGobel** [dotnet/cli#1620]
My standard folder structure is normally

```
MyApp\
    src\
    scripts\
    anythingElse\
    .gitignore
     ect...
```

When running a ``dotnet build`` or ``dotnet publish`` this produces a .exe with the name ``src.exe``.

Is there an option I can pass to dotnet, or something I can put in ``project.json`` to change the name of the generated binaries?

edit:  Also side question, is this the place to ask general questions or would asking on StackOverflow be the better platform.  I checked but there were only 3 questions tagged dotnetcli, so wasn't sure

**Comment by blackdwarf** [comment]
@KyleGobel yes, you can put in a top-level `name` property. Also, our [gitter channel](https://gitter.im/dotnet/cli) is a much better place to get help on these kinds of information.
