### ISSUE TITLE
CLI shouldn't be dependent on corefxlab

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#1624]
The CLI code currently gets the System.CommandLine package from https://github.com/dotnet/corefxlab.  However, the corefxlab "is for experimentation and exploring new ideas that may or may not make it into the main corefx repo."

The official production bits from dotnet/cli shouldn't depend on code from a repo that is for experimentation.

To fix this, we will have to do one of the following:
- Move System.CommandLine into dotnet/corefx.
- Move System.CommandLine into some other, official repo that dotnet/cli can depend on.
- Move System.CommandLine into dotnet/cli. There are two flavors of doing this:
  - Make it a publicly consumable package that is produced by dotnet/cli
  - Keep it "internal" to dotnet/cli, so only the CLI can use the code in its implementation.

@davidfowl @anurse @piotrpMSFT

**Comment by piotrpMSFT** [comment]
We're going to take a copy of System.CommandLine in CLI. We'll rev on it here to get it up to CLI needs and then contribute back.

**Comment by eerhardt** [comment]
This is now fixed #2594
