### ISSUE TITLE
Generating fallback chain for shared framework

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#1625]
We've discussed dropping a file in the shared framework which describes the set of probing rids from the most specific all the way up to `any` that will be used when probing for assets in fat packages.

What process will actually generate this fallback list?  Is it something that will be generated by `dotnet publish` when the `--runtime` argument is published?  Will there be some other tool that does this?

I will need this to include in the shared framework layouts.

**Comment by anurse** [comment]
I don't know of any plans on how this will be generated yet. In theory publish could do it, but we would only want to do it when publishing a shared framework, so we'd perhaps want a separate command/switch.
