### ISSUE TITLE
Chain in VC++ 2015 REDIST for Windows CLI MSI

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#1627]
It is required to ensure uCRT dependencies are available across all platforms. The C++ REDIST MSI is available at https://www.microsoft.com/en-us/download/details.aspx?id=48145.

**Comment by piotrpMSFT** [comment]
We will also need to create a ZIP equivalent of these things:

https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/

**Comment by piotrpMSFT** [comment]
This is a dupe of #1907
