### ISSUE TITLE
dotnet-custom cli

### ISSUE THREAD

**Issue by cheers00** [dotnet/cli#1629]
Question. How to build custom dotnet cli?

Followed the `custom-dnx` steps to build `dotnet custom cli`.
1. Clone and build coreclr repository
2. Copy `coreclr\bin\Product\Windows_NT.x64.Release\*.dll` to `dotnet\bin`
3. Delete `*.ni.dll` in `dotnet\bin`
4. Restore, build and publish MyConsoleApp
5. Use symbols from `coreclr\bin\Product\Windows_NT.x64.Release\PDB`

I can run the app but symbols are not matching in WPF.

**Comment by piotrpMSFT** [comment]
This story will become significantly easier in the next few weeks.Stay tuned!

**Comment by cheers00** [comment]
@piotrpMSFT wondering if you have any update on custom-cli for symbols support.

**Comment by livarcocc** [comment]
The way to do that today is to use source-build. Look at dotnet/source-build.
