### ISSUE TITLE
Build output should use "AMD64" instead of "x64"

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#1631]
There is more than one 64bit architecture (AMD64, IA64, ... ?). We should make filenames match what environmental variable PROCESSOR_ARCHITECTURE is using.

**Comment by davidfowl** [comment]
What folder do you mean?

**Comment by mellinoe** [comment]
AMD64 and x64 are two names for the same thing. There's a bit of ambiguity regarding "x64", but as far as I can tell in  in CLR-land, "x64" has always referred to AMD64/x86-64.

**Comment by piotrpMSFT** [comment]
x64 is an existing convention that means AMD64.

**Comment by krwq** [comment]
Already heard few opinions that we use x64 as alternative name for AMD64
