### ISSUE TITLE
`dnx restore` System.Security.Cryptography.Native exception fix on OSX with Macports

### ISSUE THREAD

**Issue by lynxluna** [dotnet/cli#1632]
I think it'll be beneficial for people who do not have homebrew in their OSX system, I know plenty of users still using macports.

So whenever I install dotnet/cli I need to link the OpenSSL 1.0.2. But how to do it without using homebrew?

First of all, this is true for all system with homebrew or not, the installer will install to `/usr/local/share/dotnet` and the installer is missing one script so we need to add some compilers to the `PATH`

```console
% sudo ln -s /usr/local/share/dotnet/bin/{dotnet,fsc,vbc,csc} /usr/local/bin/
```

and then create a directory and then link the `libcrypto` and `libssl`

```
% sudo mkdir -p /usr/local/opt/openssl/lib
% sudo ln -s /opt/local/lib/{libcrypto.1.0.0.dylib,libssl.1.0.0.dylib} \
    /usr/local/opt/openssl/lib
```

And `dotnet restore` command will runs as expected.

**Notes**
I got the path by using `otool` against the compiled dylib:

```console
 % otool -L /usr/local/share/dotnet/bin/System.Security.Cryptography.Native.dylib
/usr/local/share/dotnet/bin/System.Security.Cryptography.Native.dylib:
	@rpath/System.Security.Cryptography.Native.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by blackdwarf** [comment]
This is now part of the docs as well as the [known issues](https://github.com/dotnet/core/blob/master/cli/known-issues.md#openssl-dependency-on-os-x) so closing.
