### ISSUE TITLE
Update build output to match portable apps

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1642]
When building a portable app (no `runtimes` section), `dotnet build` output should be as follows:

```
bin/[config]/[tfm]/
  MyApp.dll
  MyApp.deps.json
  MyApp.runtimeconfig.json
  MyOtherProject.dll
```

The `.deps.json` file here is specific to the TFM portable target.

The output will be runnable via `dotnet MyApp.dll` and will load package dependencies out of the global packages location, or the shared runtime.

When building a standalone app (`runtimes` section is present), `dotnet build` will build the following output:

```
bin/[config]/[tfm]/
  MyApp.dll
  MyOtherProject.dll
  [rid]/
    MyApp.dll
    MyApp.deps.json
    MyApp.runtimeconfig.json
    MyOtherProject.dll
```

The `.deps.json` file here is specific to the TFM/RID pair.

Both `MyApp.dll` and `MyOtherProject.dll` files in this example are identical and are just copied from the base directory into the RID-specific directory. There is one `[rid]` directory for each RID in `runtimes`.

Optionally, the user can use `dotnet build --runtime [rid]` to specify a **single** RID to be built. In that case, the folder structure will be identical, but only the RIDs specified via `--runtime` will be produced.

Specifying `--output` for a standalone app requires that `--runtime` be specified as well. Alternatively, `-b` can be used to specify the base directory, under which folders for each RID will be created.

**Comment by blackdwarf** [comment]
@piotrpMSFT I don't think `dotnet build` currently supports building a specific output per RID. Correct?
