### ISSUE TITLE
Could a dependency conflict provide a little more detail?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1646]
A dependency conflict currently displays this information ...
```
<PATH>\project.json(42,30): warning NU1012: Dependency conflict. 
NETStandard.Platform 1.0.0-rc3-23901 expected System.AppContext >= 4.1.0-rc3-23901 but got 
4.1.0-rc3-23829
```
Could this information also state which package (or packages) requested the lower version?

btw- Nit ... "but got" ... perhaps "but received" would be better.

**Comment by piotrpMSFT** [comment]
@emgarten

**Comment by emgarten** [comment]
Reading project.lock.json and searching for the lower version to find dependencies on it is usually the easiest way to explore what happened.

Having the next level of packages in the message could help, the issue I've seen with this is that often times this can quickly become a large list that turns into an intimidating warning with too much information.

**Comment by cdmihai** [comment]
I would really like it if a --verbose option told me why a package got a version it did not expect. This would hopefully save me from rummaging through the lock file.

```
Dependency conflict for dependency X
Package A depends on X.V1
Package B depends on X.V2
Package C depedends on X.V3

A, B, and C got X.V3 because V3 is the highest version
```

**Comment by GuardRex** [comment]
@cdmihai That sample output you show ... :+1: excellent if something like that would be possible to get.

@piotrpMSFT Should I open a separate issue on the "nit?" That would read better as "received" regardless of detail in the output.

**Comment by moozzyk** [comment]
There should be a global command similar to `dnu list`. Looking at the project.lock.json file is difficult - especially if you have a lot of transitive dependencies.

**Comment by piotrpMSFT** [comment]
@emgarten this seems like an issue for nuget/home?

**Comment by emgarten** [comment]
Moving this to the nuget repo: https://github.com/NuGet/Home/issues/2238
