### ISSUE TITLE
Fix dotnet-projectmodel-server.Tests

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1647]
3 tests are failing under dotnet-projectmodel-server.Tests.
Also, add it as part of the TestTargets at https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/TestTargets.cs so that these tests are executed as part of CI.

## Steps to reproduce
clone the cli repo
do a build
navigate to root/tests/dotnet-projectmodel-server.Tests
do a dotnet build
do a dotnet tests

## Expected  behavior
All tests should pass.

## Actual behavior
3 tests are failing:

C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests [update_xunit_runner]> dotnet test
xUnit.net DNX Runner (64-bit win7-x64)
  Discovering: dotnet-projectmodel-server.Tests
  Discovered:  dotnet-projectmodel-server.Tests
  Starting:    dotnet-projectmodel-server.Tests
    Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthDependencies_UpdateGlobalJson_RefreshDependencies [SKIP]
      Require dotnet restore integration test
    Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthNegative_BrokenProjectPathInLockFile [FAIL]
      Assert failed on FormattedMessage.
      Expected: True
      Actual:   False
      Stack Trace:
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\Helpers\JObjectExtensions.cs(77,0): at Microsoft.DotNet.ProjectModel.Server.Tests.JObjectExtensions.AssertProperty[T](JObject json, String propertyName, Func`2 assertion, Func`2 errorMessage)
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\Helpers\JObjectExtensions.cs(61,0): at Microsoft.DotNet.ProjectModel.Server.Tests.JObjectExtensions.AssertProperty[T](JObject json, String propertyName, Func`2 assertion)
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\DthTests.cs(161,0): at Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthNegative_BrokenProjectPathInLockFile()
    Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthCompilation_Initialize_UnresolvedDependency(referenceType: "Project", testProjectName: "UnresolvedProjectSample", expectedUnresolvedDependency: "EmptyLibrary", expectedUnresolvedType: "Project") [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\Helpers\JArrayExtensions.cs(31,0): at Microsoft.DotNet.ProjectModel.Server.Tests.JArrayExtensions.AssertJArrayCount(JArray array, Int32 expectedCount)
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\DthTests.cs(112,0): at Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthCompilation_Initialize_UnresolvedDependency(String referenceType, String testProjectName, String expectedUnresolvedDependency, String expectedUnresolvedType)
    Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthCompilation_Initialize_UnresolvedDependency(referenceType: "Package", testProjectName: "IncompatiblePackageSample", expectedUnresolvedDependency: "Microsoft.Web.Administration", expectedUnresolvedType: "Package") [FAIL]
      Assert.Equal() Failure
      Expected: Package
      Actual:   (null)
      Stack Trace:
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\Helpers\JObjectExtensions.cs(54,0): at Microsoft.DotNet.ProjectModel.Server.Tests.JObjectExtensions.AssertProperty[T](JObject json, String propertyName, T expectedPropertyValue)
        C:\Users\licavalc\git\cli-1\test\dotnet-projectmodel-server.Tests\DthTests.cs(131,0): at Microsoft.DotNet.ProjectModel.Server.Tests.DthTests.DthCompilation_Initialize_UnresolvedDependency(String referenceType, String testProjectName, String expectedUnresolvedDependency, String expectedUnresolvedType)
  Finished:    dotnet-projectmodel-server.Tests
=== TEST EXECUTION SUMMARY ===
   dotnet-projectmodel-server.Tests  Total: 11, Errors: 0, Failed: 3, Skipped: 1, Time: 18.751s

**Comment by troydai** [comment]
Just discussed with @livarcocc . I committed changes to fix the tests yesterday. Rebase and they will pass. I'll close this issue now.
