### ISSUE TITLE
Make Project Dependency Command Resolution not a default

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1649]
## Overview
Today, a core scenario for the `dotnet-test` is to have a test runner available as a command which unifies it's dependencies with the dependency graph of the project under test.

This runs into problems when the project under test is built with `-c`, `-b`, or `-o`. As a solution we should not make these commands available through the driver. 

The only scenario for these commands usage is through `dotnet test` currently, so this shouldn't have any impact on existing users.

## Details

A basic example:
```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library" : "1.0.0-rc2-23811",
        "xunit": "2.1.0",
        "dotnet-test-xunit": "1.0.0-dev-48273-16"
    },

    "frameworks": {
        "dnxcore50": {}
    },

    "testRunner": "xunit"
}
```

In this project.json, the `dotnet-test-xunit` package exposes a command you could invoke from the command line like so:
`dotnet test-xunit`

In order to unify the dependencies of this command with the dependencies of the project under test, the command resolution strategy is dependent on being able to find the deps file for the project under test. 

This quickly runs into problems when a user does: 
`dotnet build -c Release -o ../bin`

The deps file is no longer in a predictable location (`./bin/Debug/dnxcore50/{RID}`), and calling `dotnet test-xunit` would be impossible as the configuration, output path information are not present.

This issue is fundamental to this scenario, and as a solution we should not make this a default command resolution strategy available through the driver.

As a result `dotnet test-xunit` would exit with a polite `Command Unknown`.

`dotnet test` would still have access to the command by calling the appropriate command resolver at the code level.

cc @livarcocc @piotrpMSFT @Sridhar-MS @krwq

**Comment by livarcocc** [comment]
How will other package commands work? They won't be able to identify custom paths? Maybe we should add support for the resolver to take these extra parameters in if they are passed.

**Comment by brthor** [comment]
What are other package commands?

Tools don't require this information because they are not dependent on the output deps file, custom paths don't come into the picture at all there.

Only Project Dependency tools are and they would work through the command resolver only, not through the driver.
