### ISSUE TITLE
Automatically sign pkg on ci builds

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#165]

**Comment by glennc** [comment]
There is a team inside Microsoft that are building a facility to get pkgs automatically signed for our releases, we will end up doing whatever we have to to integrate with that. I don't know exactly how that is going to play out yet.

**Comment by piotrpMSFT** [comment]
We need signing online in January. How's this going?

@Sridhar-MS, can you link the related MSI issue?
@brthor, can you link the related Debian issue?

**Comment by brthor** [comment]
@piotrpMSFT 
Debian signing is tracked here. #30

**Comment by Sridhar-MS** [comment]
#304

**Comment by blackdwarf** [comment]
Tracking this in #500 so closing it.
