### ISSUE TITLE
Nit: Word change suggestion in dependency conflict output ("got" to "received")

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1650]
A dependency conflict currently displays this output ...
```
<PATH>\project.json(42,30): warning NU1012: Dependency conflict. 
NETStandard.Platform 1.0.0-rc3-23901 expected System.AppContext >= 4.1.0-rc3-23901 but got 
4.1.0-rc3-23829
```
Suggestion: Change "got" to "received" ...
```
<PATH>\project.json(42,30): warning NU1012: Dependency conflict. 
NETStandard.Platform 1.0.0-rc3-23901 expected System.AppContext >= 4.1.0-rc3-23901 but received
4.1.0-rc3-23829
```
The packages and the message itself can be thought of as formal language in this context, and "received" is formal relative to "got."

**Comment by blackdwarf** [comment]
@GuardRex should this be better place on Nuget repo?

**Comment by GuardRex** [comment]
Oh, I see. I wasn't aware this message was generated by Nuget. I'll open there.

**Comment by GuardRex** [comment]
This is in `LibraryManager.cs` code ...

https://github.com/dotnet/cli/blob/a7f438f85d5a68c8f4c61bb422c39bbf3c1e1822/src/Microsoft.DotNet.ProjectModel/Resolution/LibraryManager.cs#L160

**Comment by blackdwarf** [comment]
This is in the `ProjectModel` piece of code which will be removed most likely as we progress towards the [MSBuild integration](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/).
