### ISSUE TITLE
Publish signed MSI for daily builds.

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#1654]

**Comment by blackdwarf** [comment]
@Sridhar-MS what is the timeline of this?

**Comment by Sridhar-MS** [comment]
Working on it right now. Hit some certificate issues. Early next week (3/7 or 3/8) I expect we can produce signed bundles.

**Comment by blackdwarf** [comment]
@Sridhar-MS thanks! :)

**Comment by livarcocc** [comment]
The cert issue should be fixed now. I had the account updated with the right certs.

**Comment by piotrpMSFT** [comment]
Any updates on this?

**Comment by Sridhar-MS** [comment]
As soon as #https://github.com/dotnet/cli/pull/1739 goes in we can have signed builds.

**Comment by Sridhar-MS** [comment]
We are producing signed installers every builds.
