### ISSUE TITLE
[DotNet.ProjectModel.Server] Incorrect version format is sent when project.config contains dependencies with versions 1.0.0-* 

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1655]
## Steps to reproduce

- Create a simple console app and add some dependencies having references of a format 1.0.0-* with star.
- close project
- remove project.lock.json
- Add DNX_TRACE=1
- Open project and see output for DependenciesDiagnostics and Dependencies messages

## Expected  behavior

version in correct sematic version format

## Actual behavior

returns for DependencyDiagnostics
            "ErrorCode": "NU1001",
            "SourceFilePath": "D:\\dd\\WTE\\Main\\TestResults\\Deploy_antonpis 2016-03-01 12_09_39\\Out\\MS.VS.PS.DotNet\\TestSolution\\References\\AddDllReferenceTest\\ConsoleApp\\project.json",
            "Message": "The dependency System.Threading >= 4.0.11-* could not be resolved.",
            "Severity": 2,
            "StartLine": 21,
            "StartColumn": 29,
            "EndLine": 21,
            "EndColumn": 29,
            "FormattedMessage": "D:\\dd\\WTE\\Main\\TestResults\\Deploy_antonpis 2016-03-01 12_09_39\\Out\\MS.VS.PS.DotNet\\TestSolution\\References\\AddDllReferenceTest\\ConsoleApp\\project.json(21,29): error NU1001: The dependency System.Threading >= 4.0.11-* could not be resolved.",
            "Source": {
              "Name": "System.Threading",
              "Version": "4.0.11**--**"
            }

returns for Dependencies
  "Dependencies": {
          "ConsoleApp": {
            "Name": "ConsoleApp",
            "DisplayName": "ConsoleApp",
            "Version": "1.0.0",
            "Path": "D:\\dd\\WTE\\Main\\TestResults\\Deploy_antonpis 2016-03-01 12_09_39\\Out\\MS.VS.PS.DotNet\\TestSolution\\References\\AddDllReferenceTest\\ConsoleApp\\project.json",
            "Type": "Project",
            "Resolved": true,
            "Dependencies": [
              {
                "Name": "Microsoft.CSharp",
                "Version": "**4.0.1--"**
              },
              {
                "Name": "System.Collections",
                "Version": "4.0.11--"
              },
              {

This incorrect version format results in parsing exception in WTE and blocks further restore tasks since no new messages coming (task flow link broken because of first parsing exception).

## Environment data
`dotnet --version` output:

**Comment by troydai** [comment]
@abpiskunov 

The string representation is sent by __NuGet__. Version like `1.0.0-*` is transformed to `1.0.0--`. The `NuGetVersion` can correctly parse `1.0.0--` back to a `NuGetVersion` instance. 

What’s the API used in VS tooling to parse version string?

**Comment by abpiskunov** [comment]
We don't consume nuget API for now, we use our own parsing. I could fix it too if needed, but in dnx we did not have versions in this format and as soon as we support both dnx and dotnet, I would stick with same format. 
(even when we consume nuget API, there would be a chance that user doesnot have latest nuget installed and we would fall back to our own implementation, which again would not understand it..)

**Comment by troydai** [comment]
@abpiskunov per our discussion there isn’t any action for project model server to take on. I’ll close this issue by the end of the day. Thanks.

**Comment by abpiskunov** [comment]
As discussed this is fixed on tooling side.
