### ISSUE TITLE
How to handle conditional compilation with dotnet-cli?

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/cli#1658]
We are currently evaluating our options to migrate to .net core when it launches.

However we used to conditionally compile files by compiler constant for either a single or multi tenant server project as the difference is just a few files.
As xml itemgroups are gone and it's an all or nothing game now as I understand

```xml
<ItemGroup Condition="$(DefineConstants.Contains('MULTI_TENANT'))">
```

How should I go about this story with dotnet-cli? Should we just hook into prebuild and postbuild to change what is compiled by outputting a temp project.json?

There is quite a lot of guarantee that unreferenced (internal) classes do not end up in the final IL right? So making sure that all references are wrapped by compiler directives should also do the trick, correct?

**Comment by piotrpMSFT** [comment]
Can you #ifdef the contents of the files?

**Comment by davidfowl** [comment]
project.json files are declarative and there are no conditions allowed outside of configurations or frameworks. You can define custom defines but they need to be static. 

Can you describe what you're porting?

**Comment by NinoFloris** [comment]
@piotrpMSFT Yes was also considering that, it's not pretty but it works :)

@davidfowl Yes, the simple version. We're porting a product what we host as a SaaS and we have multi tenant support. It resolves sites based on a custom header and pulls/resolves the context belonging to that site (sitecontext, container, credentials, etc) from a cache class. For this project we have around 5 classes that we rather not have compiled in because we distribute the single tenancy version to our customers for on-premise hosting. 

This sort of logic is also in other projects in this solution as certain classes and management tools etc are swapped out.

The fact that the defines need to be static is no problem as this is the only switch we have. We currently just have Debug ST/MT and Release ST/MT configurations.

**Comment by blackdwarf** [comment]
This issue will be mitigated with the move to [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/).
