### ISSUE TITLE
Website links to msi with trojan Win32/Peals.B!plock

### ISSUE THREAD

**Issue by Jonathan727** [dotnet/cli#1659]
## Steps to reproduce
Download the *Official MSI installer* from http://dotnet.github.io/getting-started/ which links to https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001598/dotnet-win-x64.1.0.0.001598.exe and is detected as a trojan.

**Comment by blackdwarf** [comment]
@Jonathan727 we are aware of it, it is a false positive. #1644 was reported. #1654 will be the solution.

**Comment by Jonathan727** [comment]
@blackdwarf thanks!
