### ISSUE TITLE
Add --version switch to cli

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#166]
For comparison:

Mono
```
Mono JIT compiler version 4.3.0 (master/b73f81c Tue Nov  3 09:24:07 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```

Node
```
v5.0.0
```

Golang
```
go version go1.5.1 darwin/amd64
```

Personally, I Iike seeing the commit sha in there as well as the version.

**Comment by davidfowl** [comment]
Why is this RTM?

**Comment by piotrpMSFT** [comment]
We shouldn't ship RTM without it, but this is fit & finish relative to other work we're tracking.

**Comment by natemcmaster** [comment]
+1 for sooner than RTM. Would help make aspnet build scripts cleaner

**Comment by natemcmaster** [comment]
...not to mention it will save on each bug report when you need to ask the issue author "which version of cli are you using?"

**Comment by davidfowl** [comment]
It's there now

**Comment by natemcmaster** [comment]
Can we add revision number? "1.0.0.xxxx"

**Comment by Mpdreamz** [comment]
+1 to more descriptive --version 

```
> dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

Does not indicate i'm on `000992-dev`

**Comment by livarcocc** [comment]
So, are we going to add the commit sha to it? I would love to see that there.

**Comment by davidfowl** [comment]
Yea I think we should just read the version file

**Comment by muratg** [comment]
:+1: to revision number, ideally matching the build number.

**Comment by moozzyk** [comment]
Wouldn't it be better to stamp the version into dotnet during build (if possible - not sure how the .version file is generated)? Reading from .version feels fragile.

**Comment by anurse** [comment]
It looks like the logic for determining the snapshot version has been changed and no longer pulls from the environment variable, which is probably why it's not being properly baked in. The logic to bake it in to the assembly is there but the project.json version is just being truncated: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/ProjectReader.cs#L106 (`settings.VersionSuffix` is always `null` when this is called via `dotnet-compile` as far as I can tell)

**Comment by blackdwarf** [comment]
@davidfowl did you not add this in? If yes, can you please close this one out?

**Comment by piotrpMSFT** [comment]
This is done.
