### ISSUE TITLE
Visual Studio Solution contains hundreds of errors

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#1661]
I'm attempting to use the [Microsoft.Dotnet.Cli.sln](https://github.com/dotnet/cli/blob/rel/1.0.0/Microsoft.DotNet.Cli.sln) for development today.  Right now it's mostly unusable because it has ~800 errors.  Many of them are inability to find core packages like `System.Runtime`:  

> 8>MSBUILD : DNX Core 5.0 error CS1705: Assembly 'NuGet.Frameworks' with identity 'NuGet.Frameworks, Version=3.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Lacking a definition for types like `object` and `Console` significantly downgrades the VS experience.  

Is there an extra step I need to take in order to make VS usuable?  I looked through the developer guide and didn't see anything.  I can successfully `build.cmd` from the command line so it doesn't appear to be an enlistment issue.

**Comment by wjk** [comment]
@jaredpar My first thought is: have you run `dotnet restore` from the top directory of the CLI checkout? This command writes out the `project.lock.json` files that tell Visual Studio exactly where to find the referenced assemblies. These files are in the gitignore, so they won’t be present in a fresh clone.

In my experience, you need to run `dotnet restore` before you can do much of anything with a solution containing a `*.xproj` file. If you have already done this, I don’t know what else to suggest. Just my 2¢.

**Comment by jaredpar** [comment]
@wjk tried that suggestion and still seeing the same result. 

Given that I already ran build.cmd in this clone is there a reason you expect `dotnet restore` to do extra work here?  My understanding is that restore is done as a part of build hence I would expect this work to already have been done.  Maybe I'm missing something subtle here.

**Comment by piotrpMSFT** [comment]
@jaredpar what VS extension are you using? DNX?

**Comment by jaredpar** [comment]
@piotrpMSFT I'm using the setup that is described in the [developer guide](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/developer-guide.md).  I verified that all extensions listed there are already installed.

**Comment by livarcocc** [comment]
The solution file won't work with the current extensions, they use DNX. There are private versions of the extensions that use the dotnet CLI and the CLI solution works with those.

**Comment by jaredpar** [comment]
@livarcocc shouldn't we document this is the developer guide?

**Comment by piotrpMSFT** [comment]
PJ issue. closing.
