### ISSUE TITLE
CommonCompilerOptions equality logic is incorrect

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#1662]
This type overrides `Equals(object)` to give the type value equality semantics.  Yet it has the following override of `GetHashCode`:

``` csharp
public override int GetHashCode()
{
    return base.GetHashCode();
}
```

This violates the equality guidelines as it's possible for two values to be equivalent according to `Equals(object)` but have different values for `GetHashCode`.

**Comment by piotrpMSFT** [comment]
This is an internal type, so moving to backlog. Would be great to get it fixed, tho.

**Comment by piotrpMSFT** [comment]
This type is only used for migration at this point, and we don't want to adjust the code that parses project.json's. We'll eventually resolve this when we remove migration. Since this is not product code that we will fix, closing the issue.
