### ISSUE TITLE
Unexpected error message "Version cannot be null. Parameter name: o” in project model server.

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1665]
## Steps to reproduce
1. Create new project in `dotnet new`
2. Open in VS with Project Model Server

## Expected  behavior
No error message is expected

## Actual behavior
Unexpected error message "Version cannot be null. Parameter name: o” in project model server.

## Environment data
`dotnet --version` output:

**Comment by troydai** [comment]
I’m not able to spot this error message in the pmserver responses.

**Comment by BillHiebert** [comment]
We have a repro and @troydai  has a fix

**Comment by troydai** [comment]
Fixed in 81baacd64128f00f87ad5304fab9f490fb88ea24
