### ISSUE TITLE
Assemblies are being read from app directory even though DOTNET_PACKAGES_CACHE is set

### ISSUE THREAD

**Issue by shhsu** [dotnet/cli#1669]
This happens when I am testing the HelloWorldMvc app under aspnet/performance branch. I am seeing that some assemblies are being read from both the DOTNET_PACKAGES_CACHE and app directories. (For example Microsoft.AspNetCore.Cors.dll)

## Steps to reproduce
Restore and publish HelloWorldMvc 
* https://github.com/aspnet/Performance/tree/dev/testapp/HelloWorldMvc
* Set DOTNET_PACKAGES_CACHE to .nuget folder so the application can load from it.
* Launch the published application and observe files being read on process monitor

## Expected  behavior
Cached assemblies such as Microsoft.AspNet.Cors.dll would be read from the nuget cache location. The same assembly from the app folder is not read at all

## Actual behavior
Assemblies from both locations are read

## Environment data
.NET Command Line Tools (1.0.0-beta-001540)

Product Information:
 Version:     1.0.0-beta-001540
 Commit Sha:  6aeed1f52d

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 Runtime Id:  win81-x64

**Comment by shhsu** [comment]
This is the call stack where the application is reading the wrong file. This has to do with Razor engine not aware of the assembly caches

Name
 |    |  |      |           |             + microsoft.aspnetcore.mvc.viewfeatures!Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
 |    |  |      |           |              + microsoft.aspnetcore.mvc.viewfeatures!ViewResultExecutor.FindView
 |    |  |      |           |              |+ microsoft.aspnetcore.mvc.viewfeatures!CompositeViewEngine.FindView
 |    |  |      |           |              | + microsoft.aspnetcore.mvc.razor!RazorViewEngine.FindView
 |    |  |      |           |              |  + microsoft.aspnetcore.mvc.razor!RazorViewEngine.LocatePageFromViewLocations
 |    |  |      |           |              |   + microsoft.aspnetcore.mvc.razor!RazorViewEngine.OnCacheMiss
 |    |  |      |           |              |    + microsoft.aspnetcore.mvc.razor!RazorViewEngine.CreateCacheResult
 |    |  |      |           |              |     + microsoft.aspnetcore.mvc.razor!DefaultRazorPageFactoryProvider.CreateFactory
 |    |  |      |           |              |      + microsoft.aspnetcore.mvc.razor!CompilerCache.GetOrAdd
 |    |  |      |           |              |       + microsoft.aspnetcore.mvc.razor!CompilerCache.CreateCacheEntry
 |    |  |      |           |              |        + microsoft.aspnetcore.mvc.razor!RazorCompilationService.Compile
 |    |  |      |           |              |        |+ microsoft.aspnetcore.mvc.razor!DefaultRoslynCompilationService.Compile
 |    |  |      |           |              |        ||+ mscorlib.ni!?
 |    |  |      |           |              |        |||+ system.linq!Enumerable.ToList
 |    |  |      |           |              |        ||| + mscorlib.ni!?
 |    |  |      |           |              |        |||  + system.linq!System.Linq.Enumerable+SelectEnumerableIterator`2[System.__Canon,System.__Canon].MoveNext()
 |    |  |      |           |              |        |||   + microsoft.aspnetcore.mvc.razor!DefaultRoslynCompilationService.CreateMetadataFileReference
 |    |  |      |           |              |        |||   |+ system.collections.concurrent!System.Collections.Concurrent.ConcurrentDictionary`2[System.__Canon,System.__Canon].GetOrAdd(!0,class System.Func`2)
 |    |  |      |           |              |        |||   ||+ microsoft.aspnetcore.mvc.razor!Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService+<>c__DisplayClass19_0.<CreateMetadataFileReference>b__0(class System.String)
 |    |  |      |           |              |        |||   |||+ microsoft.codeanalysis!ModuleMetadata.CreateFromStream
 |    |  |      |           |              |        |||   ||||+ system.reflection.metadata!System.Reflection.PortableExecutable.PEReader..ctor(class System.IO.Stream,value class System.Reflection.PortableExecutable.PEStreamOptions,value class System.Nullable`1)
 |    |  |      |           |              |        |||   |||||+ system.reflection.metadata!StreamMemoryBlockProvider.ReadMemoryBlockNoLock
 |    |  |      |           |              |        |||   ||||||+ system.reflection.metadata!StreamExtensions.CopyTo
 |    |  |      |           |              |        |||   |||||| + system.io.filesystem!Win32FileStream.Read
 |    |  |      |           |              |        |||   ||||||  + system.io.filesystem!Win32FileStream.ReadCore
 |    |  |      |           |              |        |||   ||||||   + system.io.filesystem!Win32FileStream.ReadInternalCoreAsync
 |    |  |      |           |              |        |||   ||||||    + system.io.filesystem!Win32FileStream.ReadFileNative
 |    |  |      |           |              |        |||   ||||||     + system.runtime.extensions!dynamicClass.IL_STUB_PInvoke(pMT: 00007FFF9C2AF140,unsigned int8*,int32,int,pMT: 00007FFF9C258958*)

**Comment by pakrym** [comment]
You can't set `DOTNET_PACKAGES_CACHE` to `.nuget` because it doesn't have hash files (`{PackageName}.{PackageVersion}.nupkg.{HashAlgorithm}`).
See https://github.com/dotnet/cli/blob/rel/1.0.0/src/corehost/cli/deps_resolver.cpp#L226

**Comment by pakrym** [comment]
I was wrong, it does have it, ill check tat logic

**Comment by shhsu** [comment]
Yeah, the files are present in nuget cache. Incidentally it makes things easy to test.

**Comment by glennc** [comment]
This might not be corehost failing. It could be from when MVC is loading assemblies to compile views at runtime.

**Comment by pakrym** [comment]
@shhsu fix should be in the latest build.

**Comment by shhsu** [comment]
Thanks. Could you share the PR?

**Comment by pakrym** [comment]
https://github.com/dotnet/cli/pull/1671

**Comment by shhsu** [comment]
@SajayAntony fyi
