### ISSUE TITLE
Windows defender finds mailware in the donet-win-x64.latest.exe installer

### ISSUE THREAD

**Issue by Tasteful** [dotnet/cli#1675]
This morning Windows Defender found mailware in the Windows installation package for the dotnet-cli, see image.

![image](https://cloud.githubusercontent.com/assets/357589/13488167/d95eefc2-e11f-11e5-9cb3-0e96b68c83f5.png)

![image](https://cloud.githubusercontent.com/assets/357589/13488087/66a5e256-e11f-11e5-978d-1d2b080c84a0.png)

**Comment by blackdwarf** [comment]
@Tasteful we are aware of the issue, it is a false positive. #1644 describes it. #1654 is tracking the solution.
