### ISSUE TITLE
Support content files in project.json projects

### ISSUE THREAD

**Issue by kevinkuszyk** [dotnet/cli#1677]
Moved from aspnet/dnx#3354:

> As discussed in aspnet/Home#272, tools like T4MVC require files to be added to the project root.

> Please consider bringing back this feature.

**Comment by blackdwarf** [comment]
Given the move to [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) this issue becomes non-applicable.
