### ISSUE TITLE
Building multi-project solution in VS results in concurrency failures.

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/cli#1680]
## Steps to reproduce

Clone https://github.com/dotnet/corefxlab
Open .\corfxlab.sln in VS (dogfood builds)
Build, if succeeds re-build (this bug does not always repro)
## Expected  behavior

Build succeeds
## Actual behavior

Build fails with errors about files being locked, similar to the following:

C:\git\corefxlab\dotnet\bin\dotnet.exe compile-csc @C:\git\corefxlab\src\System.Text.Http\obj\Debug\dotnet5.2\dotnet-compile.rsp returned Exit Code 1
26>  C:\git\corefxlab\src\System.Text.Http\error CS0009: Metadata file 'C:\git\corefxlab\src\System.Slices\bin\Debug\dotnet5.1\System.Slices.dll' could not be opened -- The process cannot access the file 'C:\git\corefxlab\src\System.Slices\bin\Debug\dotnet5.1\System.Slices.dll' because it is being used by another process.
26>
26>  Compilation failed.
26>      0 Warning(s)
26>      1 Error(s)
## Environment data

`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001540)

Product Information:
Version:     1.0.0-beta-001540
Commit Sha:  6aeed1f52d

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.10586
OS Platform: Windows
Runtime Id:  win10-x64

**Comment by KrzysztofCwalina** [comment]
I did some more digging into this one. Three processes compete for the same file: csc.exe, ildasm.exe, and windows defender. I have heard that msbuild goes into retry look when this happens. Do we do such retry too?

**Comment by KrzysztofCwalina** [comment]
BTW, the ildasm issue maybe can be mitigated by running the script at a different time. Today we run the script at:
  "scripts": {
    "postcompile": "re_write_il.cmd %compile:OutputDir% %compile:OutputFile%"
  }
Is there another event (besides postcompile) that would work better?

@livarcocc, @davidfowl

**Comment by KrzysztofCwalina** [comment]
In some runs other files (e.g. response files) are being locked, and so it is not specific to idasm/asm running on system.Slices.dll

**Comment by piotrpMSFT** [comment]
Does this repro from command line? Can you show a more complete log output? I'm curious what is calling compile-csc.

**Comment by KrzysztofCwalina** [comment]
I have not seen it at command line.

**Comment by piotrpMSFT** [comment]
This codepath was replaced entirely by the move to msbuild.
