### ISSUE TITLE
dotnet test should send the tests to run in a message to the test runner

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1685]
Today, we send the list of tests to run as part of the arguments to the ProcessStartInfo, however, we have a character limit of out 32K characters for the command line of the PSI. Well, we are actually hitting this limit with some of the tests in the asp.net/mvc branch.

The solution to this is to not send the list of tests to run inside arguments, but instead as part of a StartRunningTests message using out established socket channel.

I will update the message protocol here (https://github.com/dotnet/cli/issues/1376) with the additional message and information.

The idea is to keep dotnet test compatible with older versions of the runner though.

cc @vijayrkn

**Comment by rynowak** [comment]
Adding the Partner Blocking label here - this is a significant pain point

**Comment by livarcocc** [comment]
I just merged this. You need to wait for a MSI with this change and then update your dotnet-test-xunit version to 1.0.0-dev-91790-12 and you should be good.

**Comment by rynowak** [comment]
Can you update here when you know what version of dotnet cli will have this?

**Comment by livarcocc** [comment]
Already intended to!

**Comment by livarcocc** [comment]
1.0.0.001653 should have it.
