### ISSUE TITLE
Color usage in AnsiConsole

### ISSUE THREAD

**Issue by Peter-Schneider** [dotnet/cli#1686]
## Steps to reproduce
1. `Reporter.Output.WriteLine("Yellow".Yellow());`
2. `Reporter.Output.WriteLine("Bold Yellow".Bold().Yellow());`

## Expected  behavior
1. Output the string in DarkYellow
2. Output the string in Yellow (high-intense)

## Actual behavior
Currently the behavior is the opposite. Bold darkens the color.

**Comment by brthor** [comment]
cc @krwq and @Sridhar-MS 

You guys had thoughts inline with this

@anurse what are your thoughts?

**Comment by anurse** [comment]
Sounds good to me.

**Comment by piotrpMSFT** [comment]
@brthor how do we put a test on this?

**Comment by brthor** [comment]
@piotrpMSFT 
We can write Unit tests for this. I don't think this is a bug, just a change in what we consider the right behavior.
