### ISSUE TITLE
Ubuntu initial experience

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#1689]
## Steps to reproduce
clean ubuntu server 14.04
./build.sh

## Expected  behavior
Expected error: Unable to find Clang Compiler

## Actual behavior
line 67: error: command not found

Seems that command "error" is not recognized and thus I'm not seeing an actual error.

**Comment by piotrpMSFT** [comment]
@brthor I thought we had a pre req check for this?

**Comment by brthor** [comment]
@krwq error is a convenience function. Seems no one has checked this error path in a while. Nice!

@piotrpMSFT we forewent a check on clang in the c# build because it's already checked here (which is where this problem is):
https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/run-build.sh#L67
