### ISSUE TITLE
Produce deps signature for servicing

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1690]
## Steps to reproduce
dotnet publish

## Expected  behavior
The deps.json file should contain a signature field along with "libraries" or per "target" a signature of "package/version" sub-nodes.

```
        {
            "NETCoreApp/Version=1.5": {
                "A.B.C/1.0.0" : { ... }
                "D.E.F/1.0.0" : { ... }
            }
            "signature": "sha512-Ke7n2IN/RnNZWYsjsrdj/XRTToX9ly1b5YBojKA9RvqlNPBZFU90DkqVIa/fTpaNEN27IsrSC2s+6AfDI9jzWQ=="
        }
```

## Actual behavior
There is none.

This is for the host to decide to leave breadcrumbs for this instance of app launch instead of leaving it on each launch of every app.

`json.targets[0].signature = HASH(json.targets[0].packages.keys)`

**Comment by schellap** [comment]
@anurse, @piotrpMSFT

**Comment by anurse** [comment]
Looks good! Thanks for clarifying the format!

**Comment by schellap** [comment]
This is done.
