### ISSUE TITLE
Ensure CLI version is SemVer compatible

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1693]
Make sure CLI's release versions are "1.0.0" and not "1.0.0-001571", i.e., without the prerelease or the build tags.

As per the shared FX spec for SDK, the host is supposed to choose the latest `production` CLI when a CLI version cannot be inferred from a `global.json` probe. The keyword here is `production`. The host needs a way to know to pick a `production` release in a directory.

Example:

```
- dotnet\
    - SDK\
        + 1.0.0\
        + 1.0.1\
        + 1.0.2-001573\
```

The host will choose `1.0.1` unless a `global.json` specified otherwise. The host chose `1.0.1` because it did not have `prerelease` or `build` tags and is the latest version.

**Comment by schellap** [comment]
@piotrpMSFT, PTAL, the CLI versioning contract for the host.

Cc @gkhanna79

**Comment by piotrpMSFT** [comment]
As we approach RTW we'll need to ensure CLI has a pretty version [1.0.0!]

**Comment by livarcocc** [comment]
We have a pretty version being produced and will put it in the right places.
