### ISSUE TITLE
Guidance for using DependencyContext.CompileLibraries when P2P reference is type: build

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#1694]
Reproduced as part of Mvc. ProjectA references ProjectB with `type: build`. The DependencyContext for ProjectA includes this reference. However, invoking `ResolveReferencePath` on this reference fails at runtime. This is because ProjectB binary isn't part of the publish directory. Should `DependencyContext` ignore `type: build`? Alternatively, should `preserveCompilationContext` add `type: build` binaries to the refs directory?

**Comment by pranavkm** [comment]
Note: in this case, ProjectB is a shared src project. So it would never produce an output.

**Comment by pakrym** [comment]
Since https://github.com/dotnet/cli/commit/7df754be36ffc43a08220d8b7f0215980d1ff044 we are filtering out build dependencies.
