### ISSUE TITLE
error CS0246: The type or namespace name 'Thread' could not be found

### ISSUE THREAD

**Issue by dhnnjy** [dotnet/cli#1698]
I installed Dotnet on ubuntu.14.04-x64 by following instructions at "http://dotnet.github.io/getting-started/". Then I wrote a simple code for threading,

     using System;
     using System.Threading;

       namespace mythread
        {
              public class threader
                 {
                    public static void thread1()
                      {
                          for (int i = 0; i < 10; i++)
                                 {
                                      Console.WriteLine("Thread1 value: {0}.", i);
                                 }
                       }
                    public static void thread2()
                       {
                            for (int j = 0; j < 10; ++j)
                                 {
                                       Console.WriteLine("Thread2 value: {0}.", j);
                                 }
                         }
                  }

             public class class1
             {
                   public static void Main()
                   {
                        ThreadStart t1 = new ThreadStart(threader.thread1);
                        ThreadStart t2 = new ThreadStart(threader.thread2);
                        Thread tr1 = new Thread(t1);
                        Thread tr2 = new Thread(t2);
                        tr1.Start();
                        tr2.Start();
                   }
              }
     }

After running this code I'm getting error "error CS0246: The type or namespace name 'Thread' could not be found (are you missing a using directive or an assembly reference?)". Can anybody help me resolve it?

My project.json is

    {
        "version": "1.0.0-*",
        "compilationOptions": {
            "emitEntryPoint": true
        },

        "dependencies": {
            "NETStandard.Library": "1.0.0-rc2-23811"
        },

        "frameworks": {
            "dnxcore50": {
                "dependencies": {
          "System.Threading": "4.0.11-rc2-23811",
            "System.Threading.Tasks": "4.0.11-rc2-23811"
                }
            }
        },
        "configurations": {
        "Debug": {
          "compilationOptions": {
            "define": ["DEBUG", "TRACE"]
          }
        },
        "Release": {
          "compilationOptions": {
            "define": ["RELEASE", "TRACE"],
            "optimize": true
          }
        }
      }
    }

Thanks in advance.

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

**Comment by davidfowl** [comment]
You need to add `System.Threading.Thread`

**Comment by dhnnjy** [comment]
Ok, now the error is, Error CS0234: The type or namespace name 'Thread' does not exist in the namespace 'System.Threading' (are you missing an assembly reference?)

**Comment by akoeplinger** [comment]
David meant you should add it as a dependency in project.json, not a `using`.

**Comment by dhnnjy** [comment]
You mean like this?

        "frameworks": {
            "dnxcore50": {
                "dependencies": {
            "System.Threading": "4.0.11-rc2-23811",
            "System.Threading.Thread": "4.0.11-rc2-23811",
           "System.Threading.Tasks": "4.0.11-rc2-23811"
                }
            }
        },

Am I specifying correct version?

**Comment by dhnnjy** [comment]
I did that too, after running dotnet restore command, restore fails.

> log  : Restoring packages for /home/dhananjay/thread1/project.json...
info :   GET https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading.thread/index.json
info :   OK https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading.thread/index.json 3294ms
error: Unable to resolve System.Threading.Thread (>= 4.0.11-rc2-23811) for DNXCore,Version=v5.0.
info : Committing restore...
log  : Restore failed in 7894ms.

Errors in /home/dhananjay/thread1/project.json
    Unable to resolve System.Threading.Thread (>= 4.0.11-rc2-23811) for DNXCore,Version=v5.0.

NuGet Config files used:
    /home/dhananjay/thread1/NuGet.Config
    /home/dhananjay/.nuget/NuGet/NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

**Comment by akoeplinger** [comment]
System.Threading.Thread needs to be version 4.0.**0**-rc2-23811.

**Comment by dhnnjy** [comment]
Great, thanks, that solved the problem. but how did you determine the version?

**Comment by akoeplinger** [comment]
I looked at the myget dev feed for the package: https://dotnet.myget.org/gallery/dotnet-core. I think more docs about how this is all made is coming as part of https://github.com/dotnet/corefx/issues/5453.

**Comment by dhnnjy** [comment]
Thanks a lot.
