### ISSUE TITLE
clrcompression.dll missing after installing cli from 1.0.0.001632 msi package

### ISSUE THREAD

**Issue by mmalolepszy** [dotnet/cli#1700]
## Steps to reproduce
- install dotnet-win-x64.1.0.0.001632.exe
- run `dotnet new`
- run `dotnet restore`

## Expected  behavior
Packages restored correctly.

## Actual behavior
```
error: The underlying compression routine could not be loaded correctly.
error:   Unable to load DLL 'clrcompression.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

## Environment data
`dotnet --version` output:
```
.NET Command Line Tools (1.0.0-beta-001632)

Product Information:
 Version:     1.0.0-beta-001632
 Commit Sha:  049bd17ed2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

## Additional info
- clrcompression.dll is present in latest zip package, it's missing only when installing from msi package
- copying file from zip package to `C:\Program Files\dotnet\bin` folder makes everything work again
- file is present when installing from dotnet-win-x64.1.0.0.001627.exe

**Comment by Sridhar-MS** [comment]
Upgrade is broken again :( More info coming.

**Comment by Sridhar-MS** [comment]
@mmalolepszy Meanwhile as a workaround can you uninstall any previous CLIs and retry installing dotnet-win-x64.1.0.0.001632.exe?

**Comment by Sridhar-MS** [comment]
There has been a version downgrade for clrcompression.dll from `4.6.23123` to `1.0.23901`. And this happened when we moved to a new corefx build `rc2-23901` #1645. This is breaking the upgrade for clrcompression.dll.

**Comment by Sridhar-MS** [comment]
We need to add E2E tests to run after a major upgrade to catch these kind of issues. 

But at the same time we have been thinking to disable upgrades and allow side-by-side installation. In that case we will not hit this issue.

/cc: @piotrpMSFT

**Comment by mmalolepszy** [comment]
@Sridhar-MS Thanks, but as I mentioned in my post, after copying file manually from zip package everything works fine, so I just copied it and it's OK for now ;)

**Comment by mmalolepszy** [comment]
After upgrading from 1.0.0-beta-001638 to 1.0.0-beta-001661 clrcompression.dll stayed at its place.

**Comment by Sridhar-MS** [comment]
SharedFx bundle is now side-by-side and we should be not be facing any upgrade issues.
