### ISSUE TITLE
Cannot reference an xproj project, restore shows no errors, build and project.model.server show dependency cannot be resolved

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1705]
## Steps to reproduce
1. Create a new console app and a class library , both in src folder, having same target frameworks
2. add project reference console -> class library
3. Wait for restore

## Expected  behavior
Restore successful and build works fine

## Actual behavior

Restore console does not show errors, however project.model.server shows: NU1001: The dependency ConsoleApp7 >= 1.0.0-* could not be resolved.
and
build also shows same error: 

 C:\Program Files\dotnet\bin\dotnet.exe build "C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp7\src\ClassLibrary1" --configuration Debug --no-dependencies --build-base-path "C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp7\artifacts"
2>  Compiling ClassLibrary1 for .NETStandard,Version=v1.5
2>  Compilation failed.
2>      0 Warning(s)
2>      1 Error(s)
2>  Time elapsed 00:00:01.2913292
2>C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp7\src\ClassLibrary1\project.json(5,20): error NU1001: The dependency ConsoleApp7 >= 1.0.0-* could not be resolved.

## Environment data
`dotnet --version` output:

![image](https://cloud.githubusercontent.com/assets/1592091/13538368/218b012a-e218-11e5-94bf-2cf923f026f4.png)

**Comment by abpiskunov** [comment]
.NET Command Line Tools (1.0.0-beta-001614)

Product Information:
 Version:     1.0.0-beta-001614
 Commit Sha:  78dbbfc83d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by abpiskunov** [comment]
Here is restore output: 
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Program Files\dotnet\bin\dotnet.exe restore "C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp7\src\ClassLibrary1" -f "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages" -f "C:\Program Files (x86)\Microsoft WCF Data Services\5.6.4\bin\NuGet" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Stack 5\Packages" -f "C:\Program Files (x86)\Microsoft SDKs\Microsoft Azure\Mobile Services\2.0\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages" -f "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\NuGet Packages" -f "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Packages" -f "C:\Program Files (x86)\Microsoft SDKs\Application Insights" -f "C:\Program Files (x86)\Microsoft Web Tools\Packages"
log  : Restoring packages for C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp7\src\ClassLibrary1\project.json...
info : Committing restore...
log  : Restore completed in 919ms.
NuGet Config files used:
    C:\Users\antonpis\AppData\Roaming\NuGet\NuGet.Config
Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
    C:\Program Files (x86)\Microsoft WCF Data Services\5.6.4\bin\NuGet
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Stack 5\Packages
    C:\Program Files (x86)\Microsoft SDKs\Microsoft Azure\Mobile Services\2.0\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\NuGet Packages
    C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Packages
    C:\Program Files (x86)\Microsoft SDKs\Application Insights
    C:\Program Files (x86)\Microsoft Web Tools\Packages

**Comment by livarcocc** [comment]
This is working now. Besides, since restore worked, this seemed more like an issue with VS.

**Comment by abpiskunov** [comment]
it is not VS , it is ProjectModel.Server and @troydai  is working on it now
