### ISSUE TITLE
dotnet restore: base directory is expected to be first argument, but not enforced

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#1709]
After investigating it looks like this is caused by https://github.com/dotnet/cli/blob/6468b14/src/dotnet/commands/dotnet-restore/Program.cs#L73-L96, which special-cases the first argument passed to `restore`. I can't quite tell what it's for (is it a workaround for restore programs that don't support recursive restore?) but it should be fixed. If you agree, the rest of this description isn't very important. :smile:

Here's a repro case, thanks @gkhanna79 for discovering this bug:

## Steps to reproduce

Have the following directory structure:
* `a\project.json`
```
{
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-23712"
  },
  "frameworks": { "dnxcore50": { } }
}
```
* `b\project.json`
```
{
  "dependencies": {
    syntax error!
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-23712"
  },
  "frameworks": { "dnxcore50": { } }
}
```
* `dotnet-win-x64.latest` extracted zip, version 1.0.0.001614

Then run these two commands (order doesn't matter, I will just be comparing results):
```
(1) dotnet-win-x64.latest\bin\dotnet restore a\project.json --packages packages --source https://dotnet.myget.org/F/dotnet-core
(2) dotnet-win-x64.latest\bin\dotnet restore --packages packages a\project.json --source https://dotnet.myget.org/F/dotnet-core
```

## Expected  behavior

Both commands have the same behavior, where `a\project.json` is restored successfully and the syntax error in `b\project.json` is ignored because the CLI doesn't attempt to read the file.

## Actual behavior

Both commands successfully restore `a\project.json`, but command 2 also outputs an error:
```
Illegal character 's' (Unicode hexadecimal 0073).
```

You can also observe in procmon that dotnet.exe recursively searches the working directory for project.json files for command 2. This search causes a significant delay in large repositories with `.git`, `bin`, `packages`, and source folders.

**Comment by blackdwarf** [comment]
@dagood  this should be moved to Nuget/Home if it still repros, as `dotnet restore` uses NuGet to restore depedencies and read the project.json.

**Comment by dagood** [comment]
No repro on `1.0.0-preview3-003208`.
