### ISSUE TITLE
Installer completes successful without installing or crashes

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#1713]
https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001636/dotnet-win-x64.1.0.0.001636.exe (latest at time of writing)

Running this on different machines I've encountered 2 different errors:

1. Installer does not actually place dotnet binaries on disk. It creates a swidtag file in C:\Program Files\dotnet\swidtag but C:\Program Files\dotnet is otherwise empty. If a different location is specified ("Options" button when installing), nothing is placed into that directory.
2. On other machines, the installer crashes. (error output below)

```
e000: Error 0x8002000a: Failed to convert version: 1.0.0.1450479037 to DWORD64 for ProductCode: {F0AD14D0-0232-48CC-86DA-79000B12A1C0}
e151: Detect failed for package: dotnet_win_x64.1.0.0.001636.msi, error: 0x8002000a
i101: Detected package: dotnet_win_x64.1.0.0.001636.msi, state: Unknown, cached: None
i199: Detect complete, result: 0x8002000a
```

**Comment by Sridhar-MS** [comment]
@natemcmaster You previously had a very old (pre-Dec'15) version of CLI installed `1.0.0.1450479037`. We did a breaking change so you cannot update from that. Uninstall the old version and retry the setup.

**Comment by natemcmaster** [comment]
Thanks @Sridhar-MS. Uninstalling the old version fixes the issue for installing not adding files. But now the installer will only install to C:\Program Files\dotnet. It does not respond to setting a different install location in "Options".

**Comment by piotrpMSFT** [comment]
As Shared Framework lights up, we'll be restricting the install location to PFiles\dotnet. We need to coordinate multiple installers to the same directory, and this is the fastest path forward. 

@natemcmaster is specifying the installation directory a high-pri scenario for you? Help me understand why?

**Comment by natemcmaster** [comment]
> is specifying the installation directory a high-pri scenario for you?

It's important but not blocking. I am working with multiple versions of dotnet side-by-side.

**Comment by Sridhar-MS** [comment]
@natemcmaster please reopen the issue if your still facing it.
