### ISSUE TITLE
DependencyContextJsonReader.Read throws FileNotFoundException for 'System, Version=2.0.5.0...'

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1719]
Note that it works if the test project is still dnxcore50 with an import for netstandardapp1.5

## Steps to reproduce
Clone the coreclr.xunit repo at git@github.com:dotnet/coreclr.xunit.git.
Modify the test project.json to change is framework to netstandardapp1.5
Run build.ps1

## Expected  behavior
dotnet test runs without problems.

## Actual behavior
When the tests are executed, we get this.
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
at Microsoft.Extensions.DependencyModel.DependencyContext.Load(Assembly assembly)
at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
at Xunit.Runner.DotNet.Program.Run(String[] args)
at Xunit.Runner.DotNet.Program.Main(String[] args)

**Comment by pranavkm** [comment]
cc @pakrym

**Comment by pakrym** [comment]
It was wrong imports on projects that caused loading of wrong portable target of `Newtonsoft.Json`
