### ISSUE TITLE
Is there a plan when release the VS2015 tooling for asp.net 5?

### ISSUE THREAD

**Issue by endink** [dotnet/cli#1720]
We have a large web project, develop it  more than half a year, we love asp.net 5 and happy to help to improve asp.net5, we go from Beta4 to RC2, and play with bleading edge.
We are looking forward to release RC2 tooling, a bunch of wrong every day see the design time host very uncomfortable.

thanks asp.net5, thanks dotnet cli!

LOL!

**Comment by xanather** [comment]
I think this is related to https://github.com/dotnet/cli/issues/1556

https://www.youtube.com/watch?v=qPz3E8Ij2KQ&index=2&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF mentions that there may be a possible VS tooling release before RC2 as an intermediary release.

I see that .net CLI VS tools are already being used by Microsoft internally.

Is there a chance such tools could be released to the public as alpha/indev? 

I am sure many using the latest bits of .NET Core have hit a snag with the recent DNX -> CLI changes.

**Comment by mikes-gh** [comment]
+1 for a pre rc2 release version of rc2 tooling.
May help iron out any last minute issues that may not be picked up internally.

**Comment by blackdwarf** [comment]
Well, I believe that this issue is not longer valid as we have released the Preview 1 tooling as well as the Preview 2 tooling so will close this issue.
