### ISSUE TITLE
Install script on Linux in Travis has error with default "Latest" version.

### ISSUE THREAD

**Issue by hal-ler** [dotnet/cli#1725]
## Steps to reproduce

Download (https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh) and run install script within Travis using "sh -C .dotnet/install.sh".
## Expected  behavior

Updates dotnet installation to latest version.
## Actual behavior

.dotnet/install.sh: 164: [: Latest: unexpected operator

.dotnet/install.sh: 178: [: Latest: unexpected operator

dotnet_install: Downloading dotnet-ubuntu-x64.Latest.tar.gz from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest
## Assumption

The double equality for the version number is not compatible in the shell used by Travis.

**Comment by hal-ler** [comment]
Solved it by running the script using bash instead of sh, but the file header does state:
"This script should be compatible with the dash shell used in Ubuntu. So avoid bashisms!"

**Comment by piotrpMSFT** [comment]
@krwq can you make sure this scenario [bash vs. sh] is covered in the productization of these scripts?

**Comment by livarcocc** [comment]
@johnbeisner can you pick this up?

**Comment by omajid** [comment]
See https://github.com/dotnet/cli/pull/6069 for the fix pushed to master.

**Comment by livarcocc** [comment]
I am happy with that. Closing this issue then.
