### ISSUE TITLE
ilasm and ildasm are not included

### ISSUE THREAD

**Issue by edmundmk** [dotnet/cli#1727]
## Steps to reproduce

Install the prebuilt package from http://dotnet.github.io.
Look in `/usr/local/share/dotnet/bin`.
Notice that ilasm and ildasm are not included in the toolset.
If you build CoreCLR from source then these tools are built.
## Environment data

`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

**Comment by piotrpMSFT** [comment]
Added to an extensions backlog.
