### ISSUE TITLE
corehost does not support cross-build

### ISSUE THREAD

**Issue by mylibero** [dotnet/cli#1728]
I'm trying to use CLI on ARM.
After a series of struggles, I could run cli on ARM. 
It crashes for errors from coreclr, though. (this is another issue that we are working on)

Soon, I will be sending pull-requests about my work.
One of issues is that corehost does not support cross-build.
Since CLI does not build on ARM yet without an ARM CLI version, I had to cross-build on x64.
Alternatively, I could do native-build corehost on ARM and copy those back to x64, 
but I found it easier if corehost supports cross-build.

I changed 'src/corehost/build.sh' to take an architecture option. (x64 by default)
Any other idea? suggestion?

**Comment by mylibero** [comment]
corehost is too simple program to have a proper cross-build script.
I'm thinking of taking a cross compiler as an argument along with 'cross' option, instead of the architecture option.

**Comment by mylibero** [comment]
@Sridhar-MS This issue may be closed now. https://github.com/dotnet/cli/pull/1747 has been merged.

**Comment by shootdaj** [comment]
@mylibero Can you tell me how I can use the dotnet CLI to build/publish a .NET Core RC2 application to Raspberry Pi with Windows IoT? I read that you have to actually build the CLI on the ARM platform itself for the output to be compatible with ARM. It seems that you were able to cross-build it on the x64 platform. How were you able to do that? And is the output dotnet.exe runnable on a Raspberry Pi? I'm a little confused. Bottom line is, I want to be able to run an ASP.NET Core RC2 application on Raspberry Pi running Windows 10 IoT. Thank you.

**Comment by mylibero** [comment]
@shootdaj dotnet.exe is just a rename of corehost. Note that corehost is now moved to core-setup.
Compiling corehost for ARM is possible now. Other files except dotnet.exe are platform independent.
So, you can run dotnet-cli on ARM, but I doubt if it would build your project for ARM yet.
Alternatively, if your project does not have native code, you can just build it on x64 and run it on RPi.
