### ISSUE TITLE
Any plans to distribute binaries for ARM?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/cli#1730]
I'm trying to compile the CoreFX repo natively from an ARM Linux laptop, and it's giving me something about a binary format error. I eventually realized the issue came down to the fact it downloaded the [x64 binaries](https://github.com/dotnet/corefx/blob/master/init-tools.sh#L30) from the `dotnet` feed, which can't be used from ARM.

Are there any plans to distribute binaries of the CLI for ARM, so that it can be used on those devices? Thanks.

**Comment by blackdwarf** [comment]
@jamesqo at this point, for v1, we will not be doing an ARM port.

**Comment by DanTup** [comment]
Are there any future plans for the cli on ARM at all (even if not binaries)? I thought it was supported, but hit the same error as @jamesqo when running `build.sh`.
