### ISSUE TITLE
Confusing experience when after modifying project.json in VS Code

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#1733]
Please assign this issue to @NumberByColors 

## Steps to reproduce
1. Download VS Code + new C# extension with preview of .NET Core Debugging
2. Create a .NET CLI project and get it to work
3. Decide that you need to add a new reference or switch versions of the .NET Framework, so modify project.json
4. Hit F5 to start debugging again

## Expected  behavior
Either 'restore' should automatically get run, or something somewhat obvious should happen to indicate that it should be run

## Actual behavior
A warning gets generated, but the program immediately starts, so its not very obvious what is going on.

## Possible resolutions
1. Make it like Visual Studio - VS Code invokes the new ‘dotnet build –allow-restore’ which does the build, and in whatever condition it issues that warning it instead does the restore.
2. Make it an error - VS Code invokes ‘dotnet build’ as before, but instead of making it a warning that no one is likely to notice, it becomes an error. 'dotnet build' could be made to take a '--skip-restore-checks' (or whatever we want to call it) switch for anyone who really wants to build with old dependencies.
3. Leave things as-is (user needs to do a ‘dotnet restore’ manually, but we aren’t real upfront about it)

**Comment by NumberByColors** [comment]
Could this be as simple as adding "restore" as a preLaunchTask in the three .NET Core launch.json profiles? Could we add a new property to the launch.json objects for .NET Core called "buildIfProjectChanged" or something? As long as the behavior isn't unconfigurable magic, the right thing to do is to automatically do a dotnet restore at debugger launch if the user forgets.

**Comment by gregg-miskelly** [comment]
I agree with --
   "...the right thing to do is to automatically do a dotnet restore at debugger launch if the user forgets"
But I think the right way to do that is with a .NET CLI change -- 'dotnet build' should do a restore automatically, at least if some new command line argument is specified.

Reasons:
1. Perf - always running 'dotnet restore' and then 'dotnet build' would be considerable slower than having dotnet build do a restore in the case that it detects that a restore should be done. 'dotnet build' already feels a bit sluggish. So I don't think we should make it slower by launching another cascade of processes.
2. VS Code restrictions - VS Code only supports one pre-launch task. Obviously they could add this, but since it seems like the wrong fix anyway...

**Comment by NumberByColors** [comment]
I agree. I'll create an issue.

**Comment by blackdwarf** [comment]
@gregg-miskelly wouldn't VS Code detect that `project.json` was modified and prompt the user to run a restore? This is the way it is doing things now with dnx support.

**Comment by gregg-miskelly** [comment]
There is some logic in VS Code to detect missing references and ask the user to do a restore. From what I can tell, it will not ask the user to do a restore just because the file changed. I don't think it works super well today, but maybe it will work better once the VS Code C# extension pulls in a newer OmniSharp. @DustinCampbell what do you think?

**Comment by piotrpMSFT** [comment]
#1742 is the right approach here. I'm closing this issue as a dupe. Let me know if you feel that 1742 is not sufficient.
