### ISSUE TITLE
CompilationOptions is holding on a bunch of JObject objects

### ISSUE THREAD

**Issue by rynowak** [dotnet/cli#1736]
## Steps to reproduce
Create an MVC site and run some requests (https://github.com/aspnet/Performance/tree/dev/testapp/BasicViews used for this). See https://github.com/aspnet/Mvc/issues/4175

## Expected  behavior
`CompilationOptions` doesn't hold on to a bunch of `JObject` objects :laughing: 

## Actual behavior
The `defines` argument passed [here](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/CompilationOptions.cs#L49) is a lazy `IEnumerable<string>` holding on to a bunch of parsed JSON data. 

For this tiny MVC site, it's about 1.5mb per `CompilationOptions` instance of extra memory retained (we have 2 copies for some reason) of 14.7mb total.

![image](https://cloud.githubusercontent.com/assets/1430011/13579363/12ae59f4-e452-11e5-9972-ec4a4e4a6c33.png)

## Environment data
`dotnet --version` output:
```
.NET Command Line Tools (1.0.0-beta-001634)

Product Information:
 Version:     1.0.0-beta-001634
 Commit Sha:  3ed9361763

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

Using `"Microsoft.Extensions.DependencyModel": "1.0.0-beta-001584",`

**Comment by pakrym** [comment]
Fixed: https://github.com/dotnet/cli/pull/2264
