### ISSUE TITLE
Re-enable portable PDB as Windows default

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#1743]
Once #1735 is fixed we should re-enable Windows as the default on Windows.  Essentially revert #1712.

**Comment by piotrpMSFT** [comment]
Is this going to make rc2?

**Comment by jaredpar** [comment]
@piotrpMSFT it can't make it unless #1735 is fixed which it doesn't appear to be.

**Comment by ManishJayaswal** [comment]
@jaredpar #1735 was fixed. You can re-enable this.

**Comment by krwq** [comment]
Hey @jaredpar, are you still planning this for rc2?

**Comment by jaredpar** [comment]
@krwq it's being discussed at the moment.  I'm going to issue a PR for it and let ship room decide.

**Comment by shanselman** [comment]
Whether this is the default or not, can the VSIX on VSCode automatically notice if it's not? If you're on Windows and you're debugging and this is NOT set, then the VSIX or the error should at least **lead you to the pit of success**. That means, either fix it for me, or tell me in the error.

We can do this in the VSIX today, without waiting.

/cc @glennc @DustinCampbell

**Comment by DustinCampbell** [comment]
Sound like a good idea. Send an issue our way in https://github.com/OmniSharp/omnisharp-vscode.

**Comment by livarcocc** [comment]
I believe this is now being set in the SDK.

**Comment by rkeithhill** [comment]
Sadly this still seems not to be the pit of success in 2019.  Debugging a .NET Core app on Windows in VSCode and the only indication I get is this message buried in a sea of output in the Debug Console:
```
... blal.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.
```
