### ISSUE TITLE
no warning in dotnet build if there are build error

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1744]
## Steps to reproduce

Create a new console project and in program.cs past this:

```
public class Program
{,
    public static void Main(string[] args)
    {
        int i;
    }
}
```

and build project.
## Expected  behavior

in the output pane  should be 1 error and 1 warning saying variable I is never used. Intelisense does show warning and error, also dnx did show a warning too (we had an integration test that expected that for dotnet too and failed)
## Actual behavior

Only error is showing up in the dotnet build output
## Environment data

`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001636)

Product Information:
 Version:     1.0.0-beta-001636
 Commit Sha:  42a17b5d98

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by piotrpMSFT** [comment]
@abpiskunov I just checked this in the msbuild implementation and found that:
- with the syntax error in play, only the error is presented
- with the error fixed, the warning is presented

It looks like the compiler stops parsing when the error is found and ignores the warning until a subsequent pass. If you feel this is an issue please file a bug with the Roslyn team. We'll be glad to take an updated compiler once ready.
