### ISSUE TITLE
dotnet-nightly builds are unreliable (and currently broken)

### ISSUE THREAD

**Issue by colemickens** [dotnet/cli#1745]
## Steps to reproduce
1. Download the latest from the `dotnet-nightly` apt repo.
2. Try to run `dotnet compile`

## Expected  behavior
1. It compiles.

## Actual behavior
1. It hangs. Really hard.

## Environment data
`dotnet --version` output:

Working:
```
.NET Command Line Tools (1.0.0-dev-001589)

Product Information:
 Version:     1.0.0-dev-001589
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

Not working: (The same output as above, but for versions `1.0.0-dev-{001598, 001606, 001598}`)

Are dotnet-nightly builds tested before being pushed to apt?

If not `-nightly` builds, are there any stability guarantees for non-nightly builds? What is the CI story for the linux cli builds?

**Comment by brthor** [comment]
dotnet-nightly builds will soon be renamed to dotnet-future to represent their intention a little better.

dotnet-nightly comes out of our master branch which is tested but not guaranteed to have the same stability as rel. The `dotnet` package comes out of rel.

**Comment by blackdwarf** [comment]
As @brthor mentioned, the actual apt feed that needs to be used should be `dotnet` for dev releases and `dotnet-release` for named (stable) releases.
