### ISSUE TITLE
How to version Packages and assemblies?

### ISSUE THREAD

**Issue by dhnnjy** [dotnet/cli#1746]
I've installed dotnet on ubuntu 14.04. I'm clueless how to version assemblies. I'm trying to include 
> "System.Net.Security":  "4.0.0-beta-23516"

in project.json. DOTNET RESTORE output is
`warn : Detected package downgrade: System.Security.Cryptography.Algorithms from 4.0.0-rc2-23811 to 4.0.0-beta-23516 
warn :  hwapp (>= 1.0.0) -> Npgsql (>= 3.1.0-alpha6) -> System.Security.Cryptography.X509Certificates (>= 4.0.0-rc2-23811) -> System.Security.Cryptography.Algorithms (>= 4.0.0-rc2-23811) 
warn :  hwapp (>= 1.0.0) -> Npgsql (>= 3.1.0-alpha6) -> System.Security.Cryptography.Algorithms (>= 4.0.0-beta-23516)
warn : Detected package downgrade: System.Security.Cryptography.Algorithms from 4.0.0-rc2-23811 to 4.0.0-beta-23516 
warn :  hwapp (>= 1.0.0) -> Npgsql (>= 3.1.0-alpha6) -> System.Net.Security (>= 4.0.0-rc2-23811) -> runtime.unix.System.Net.Security (>= 4.0.0-rc2-23811) -> System.Security.Cryptography.Algorithms (>= 4.0.0-rc2-23811) 
warn :  hwapp (>= 1.0.0) -> Npgsql (>= 3.1.0-alpha6) -> System.Security.Cryptography.Algorithms (>= 4.0.0-beta-23516)
`

DOTNET RUN output is
`Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.Net.Security.SslStream.AuthenticateAsClient(System.String, System.Security.Cryptography.X509Certificates.X509CertificateCollection, System.Security.Authentication.SslProtocols, Boolean)'.
`

How do I determine which version of packages are supported in my DNX V5.0?

## Environment data
    ~$ dotnet --version output: .NET Command Line Tools (1.0.0-beta-001598)
    Product Information: Version: 1.0.0-beta-001598 Commit Sha: N/A
Runtime Environment: OS Name: ubuntu OS Version: 14.04 OS Platform: Linux Runtime Id: ubuntu.14.04-x64

## Environment data
    ~$ dnx --version output
    Microsoft .NET Execution environment Version: 1.0.0-rc2-16551 Type: CoreClr Architecture: x64 OS Name: ubuntu OS Version: 14.04 Runtime Id: ubuntu.14.04-x64

**Comment by blackdwarf** [comment]
@dhnnjy can you please include `dotnet --version` output? You included `dnx --version`.

**Comment by dhnnjy** [comment]
@blackdwarf Here's my Project.json.

        {
            "version": "1.0.0-*",
            "compilationOptions": {
                "emitEntryPoint": true
            },

            "dependencies": {
                "NETStandard.Library": "1.0.0-rc2-23811",
                "Npgsql": "3.1.0-alpha6"
            },

            "frameworks": {
                "dnxcore50": {
                    
                
                }
            }
        }

I removed all the dependencies, yet I'm getting same error, which is I think because of Npgsql 3.1.0-alpha6 dependencies  [https://www.nuget.org/packages/Npgsql/3.1.0-alpha6](url).

**Comment by dhnnjy** [comment]
@blackdwarf 
I did an update today.
previous dotnet --version output :

     .NET Command Line Tools (1.0.0-beta-001598)
     Product Information: Version: 1.0.0-beta-001598 Commit Sha: N/A

current dotnet --version output :

    .NET Command Line Tools (1.0.0-beta-001675)

    Product Information:
    Version:     1.0.0-beta-001675
    Commit Sha:  N/A
    Runtime Environment:
    OS Name:     ubuntu
    OS Version:  14.04
    OS Platform: Linux
    Runtime Id:  ubuntu.14.04-x64

After running 'dotnet new' and then 'dotnet restore' commands, restore fails.
Project.json is 

    {
        "version": "1.0.0-*",
        "compilationOptions": {
            "emitEntryPoint": true
        },

        "dependencies": {
            "NETStandard.Library": "1.0.0-rc2-23901"
        },

        "frameworks": {
            "netstandardapp1.5": {
                "imports": "dnxcore50"
            }
        }
    }


output is..


> error: Unable to resolve runtime.unix.Microsoft.Win32.Primitives (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.AppContext (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Collections (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.Console (>= 4.0.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.Diagnostics.Debug (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Diagnostics.Tools (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Diagnostics.Tracing (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Globalization (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Globalization.Calendars (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.IO (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.IO.FileSystem (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.Net.Primitives (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.Net.Sockets (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Reflection (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Reflection.Extensions (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Reflection.Primitives (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Reflection.TypeExtensions (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Resources.ResourceManager (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Runtime (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.Runtime.Extensions (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Runtime.Handles (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Runtime.InteropServices (>= 4.1.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.unix.System.Runtime.InteropServices.RuntimeInformation (>= 4.0.0-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Text.Encoding (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Text.Encoding.Extensions (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Threading.Tasks (>= 4.0.11-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.any.System.Threading.Timer (>= 4.0.1-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
error: Unable to resolve runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR (>= 1.0.2-rc2-23901) for .NETStandardApp,Version=v1.5 (ubuntu.14.04-x64).
info : Committing restore...
log  : /home/dhanajay/test/project.json
log  : Restore failed in 1301ms.

**Comment by dhnnjy** [comment]
However if I change
 "NETStandard.Library": "1.0.0-rc2-23901" 
to
"NETStandard.Library": "1.0.0-rc2-23811"

restore is successful.

**Comment by blackdwarf** [comment]
The last scenario reported failed because of pre-release packages. In the current release, Preview 2 (1.0.0-preview2-003121) this is not reproing. Closing this issue. If it is still needed please update it and reopen.
