### ISSUE TITLE
dotnet restore: temporary directory is expected to be user specific

### ISSUE THREAD

**Issue by songdongsheng** [dotnet/cli#1748]
## Steps to reproduce

In Ubuntu 14.04 or CentOS 7.2, run dotnet restore with the user1, then run dotnet restore with the user2 failed.

$ dotnet restore -v verbose

error: Access to the path '/tmp/NuGetScratch/lock' is denied.
trace: System.AggregateException: One or more errors occurred. (Access to the path '/tmp/NuGetScratch/lock' is denied.) ---> System.UnauthorizedAccessException: Access to the path '/tmp/NuGetScratch/lock' is denied.

## Expected  behavior

All user should run dotnet restore successes in the same system.

## Actual behavior

Only one user can run dotnet restore successes in the same system.

## Environment data
`dotnet --version` output:

$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001661)

Product Information:
 Version:     1.0.0-beta-001661
 Commit Sha:  2b90a2f831

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

## Cause and Solution
During the restore, all user use the same temporary directory '/tmp/NuGetScratch/', this is absolutely wrong, we need use the user specific directory, e.g. '/tmp/NuGetScratch-${USER}/'.

**Comment by mmalolepszy** [comment]
I confirm this problem still exists on 1.0.0-beta-001933.

**Comment by victory2009** [comment]
me too .
Environment:
OS : centos-release-7-2.1511.el7.centos.2.10.x86_64
CLI:1.0.0-preview2-003121

**Comment by blackdwarf** [comment]
Closing in favor of Nuget/home issue.
