### ISSUE TITLE
dotnet build fails on nfs

### ISSUE THREAD

**Issue by damageboy** [dotnet/cli#1749]
## Steps to reproduce

(On a nfs mount)

dotnet new
dotnet restore
dotnet build
## Expected  behavior

build succeeds
## Actual behavior

build fails with:
`Access to the path '/home/damageboy/projects//dotnet-sample/obj/Debug/dnxcore50/dotnet-compile.rsp' is denied.`
## Environment data

`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-dev-001698)

Product Information:
 Version:     1.0.0-dev-001698
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```
## More information:

I thinks this boils down to some weird locking behavior on nfs vs local file systems:
### Bad run (NFS)

Here's a snippet of `strace -o bad.log dotnet build` output of a run done to produce the same error:

```
open("/home/damageboy/projects/dotnet-sample/obj/Debug/dnxcore50/dotnet-compile.rsp", O_WRONLY|O_CREAT|O_TRUNC, 0700) = 77
fstat(77, {st_mode=S_IFREG|0700, st_size=0, ...}) = 0
flock(77, LOCK_SH|LOCK_NB)              = -1 EBADF (Bad file descriptor)
```

Notice the bad flock() return value, it's pretty clear it all goes down hill from there, here's the full strace: [bad.log](https://gist.github.com/damageboy/22ccf2480bdb6e46b381#file-bad-log)
### Good run (/tmp)

Again, here's a snipped of `strace -o good.log dotnet build` output that succeeds:

```
open("/tmp/dotnet-sample/obj/Debug/dnxcore50/dotnet-compile.rsp", O_WRONLY|O_CREAT|O_TRUNC, 0700) = 77
fstat(77, {st_mode=S_IFREG|0700, st_size=0, ...}) = 0
flock(77, LOCK_SH|LOCK_NB)              = 0
```

Notice how flock() successfully

Again here is the full strace output: [good.log](https://gist.github.com/damageboy/22ccf2480bdb6e46b381#file-good-log)

**Comment by blackdwarf** [comment]
@damageboy interesting problem. What is the scenario for using the NFS mount?

**Comment by damageboy** [comment]
Nothing in particular,  we are a large organization and we have 100+
machines,  all using home directories on nfs,  which is a fairly common
practice to keep dot files and projects readily accessible from all
machines..

**Comment by ah-** [comment]
I'm running into the same issue. Sharing one home directory on a NetApp between Linux and Windows, and can't build using dotnet cli on Linux where it's mounted via NFS.

Have you looked into fcntl to do the locking?

**Comment by blackdwarf** [comment]
Guys, there is an issue opened on the dotnet/core#15120 as this is really something we should track and discuss there. Will close this one.
