### ISSUE TITLE
Migrate DTH experience

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#175]
_Updated on 12/9_:

Brief:
* [x] Establish `WorkspaceContext` in `Microsoft.DotNet.ProjectModel`. It manages `ProjectContext` among projects under same workspace
* [x] Slim the original DTH mechanism into APIs.
* [x] Establish internal mechanism to cache `ProjectContext` and `Project` for a design time experience
* [x] Integration with OmniSharp.
* [x] Establish `dotnet-designtimeserver` as replacement of dth for Visual Studio

Working branch:
https://github.com/dotnet/cli/tree/trdai/dth

OmniSharp integration work:
https://github.com/OmniSharp/omnisharp-roslyn/tree/trdai/cli

**Comment by troydai** [comment]
Done in 935cd4e2812f37cd9293506b84676fa6889a3200

**Comment by piotrpMSFT** [comment]
Thanks!
