### ISSUE TITLE
dotnet test - Could not resolve coreclr path

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1751]
## Steps to reproduce
I cloned a repo (https://github.com/aspnet/Configuration) and restored packages. From one of the test projects I just ran `dotnet test`

## Expected  behavior
Tests are being run.

## Actual behavior
```
dotnet test
Could not resolve coreclr path
```

## Environment data
`dotnet --version` output:
```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

The application is "netstandardapp1.5"

**Comment by livarcocc** [comment]
You need to build the project first.

We have an issue tracking making dotnet test build before running the tests. I am looking for the issue.
