### ISSUE TITLE
dotnet run in a project without a Main method fails badly

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1752]
## Steps to reproduce
Go to a test project and run `dotnet run`. I assume this happens not only on test projects but basically on any project that does not have "emitEntryPoint: true"

## Expected  behavior
No pop-ups. A user friendly error message. If we can infer that this is a test project a hint to use dotnet test?

## Actual behavior

Popup indicating a crash +

```
Project Microsoft.Extensions.Configuration.Abstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration.FileExtensions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration.Test.Common (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration.Test (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'Microsoft.Extensions.Configuration.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by livarcocc** [comment]
Project temp (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling temp for .NETCoreApp,Version=v1.0
Documents/git/cli/artifacts/osx.10.11-x64/stage2/dotnet compile-csc @Documents/git/temp/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
Documents/git/temp/error CS5001: Program does not contain a static 'Main' method suitable for an entry point
