### ISSUE TITLE
dotnet build creates exe if no "entryPoint: true" in project.json

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1753]
## Steps to reproduce
Run `dotnet build` on a project that does not have  "entryPoint: true". If you run this .exe you wil get output similar to the one described in #1752. 

## Expected  behavior
If there is "entryPoint: true" in the project.json the .exe should not be created. 

## Actual behavior

Popup indicating a crash +

```Project Microsoft.Extensions.Configuration.Abstractions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration.FileExtensions (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration.Test.Common (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Project Microsoft.Extensions.Configuration.Test (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'Microsoft.Extensions```

+ an Error entry in the event log: 
```
Faulting application name: Microsoft.Extensions.Configuration.Test.exe, version: 0.0.0.0, time stamp: 0x56d53c10
Faulting module name: KERNELBASE.dll, version: 10.0.10586.103, time stamp: 0x56a8489c
Exception code: 0xe0434352
Fault offset: 0x0000000000071f08
Faulting process id: 0x39f4
Faulting application start time: 0x01d17962d3c568e8
Faulting application path: C:\Source\Configuration\test\Microsoft.Extensions.Configuration.Test\bin\Debug\netstandardapp1.5\win7-x64\Microsoft.Extensions.Configuration.Test.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: b989f29b-eb69-4f77-8e32-0ebf49ddaf56
Faulting package full name: 
Faulting package-relative application ID: 
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by livarcocc** [comment]
dotnet build is no longer generating an exe when emitentrypoint: true is not present.
