### ISSUE TITLE
Hard to run tests from outside of the test project folder for netstandard app

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1754]
## Steps to reproduce
- Publish your tests 
- Try to run dotnet-test in the published folder (I did provide a path to the project json)

(providing the path to the project.json for a published project is kind of unexpected since the original project can be on a different machine)

## Expected  behavior
The tests are run. 
-or-
there is a different, user friendly (see "additional notes" below) way of running tests.

## Actual behavior

```
PS C:\Temp\tests> dotnet test  C:\Source\Configuration\test\Microsoft.Extensions.Configuration.Test\project.json
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration) in D:\vsoagent\_work\16\s\src\Microsoft.DotNet.Cli.Utils\Command.cs:line 79
   at Microsoft.DotNet.Tools.Test.TestCommand.RunConsole(ProjectContext projectContext, CommandLineApplication app, String testRunner, String configuration) in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-test\Program.cs:line 97
   at Microsoft.DotNet.Tools.Test.TestCommand.<>c__DisplayClass0_0.<Run>b__0() in D:\vsoagent\_work\16\s\src\dotnet\commands\dotnet-test\Program.cs:line 73
```
## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64 
```

## additional notes
Note I was able to run the published tests with:

`corehost .\dotnet-test-xunit.dll .\Microsoft.Extensions.Configuration.Test.dll`

but it is kind of horrible and I don't think we tell users to use corehost directly?

**Comment by livarcocc** [comment]
We already have an issue tracking this: https://github.com/dotnet/cli/issues/1184.

Also, if you want to run tests with binaries in a different location from the root of the test project, specify the output path pointing to where the bits are using the -o param. So, do something like dotnet test path/to/project.json -o path/to/binaries/tfm/rid

**Comment by moozzyk** [comment]
I did not know I could use the `-o` option - `dotnet test --help` does not show it as an option: 

```
.NET Test Driver

Usage: dotnet test [arguments] [options]

Arguments:
  <PROJECT>  The project to test, defaults to the current directory. Can be a path to a project.json or a project directory.

Options:
  -?|-h|--help                        Show help information
  --parentProcessId                   Used by IDEs to specify their process ID. Test will exit if the parent process does.
  --port                              Used by IDEs to specify a port number to listen for a connection.
  -c|--configuration <CONFIGURATION>  Configuration under which to build
```

**Comment by livarcocc** [comment]
Which version of the CLI are you using. I can see it in mine:

```
C:\users\licavalc\git\cli-1 [projects_to_pack]> dotnet test --help
.NET Test Driver

Usage: dotnet test [arguments] [options]

Arguments:
  <PROJECT>  The project to test, defaults to the current directory. Can be a path to a project.json or a project directory.

Options:
  -?|-h|--help                        Show help information
  --parentProcessId                   Used by IDEs to specify their process ID. Test will exit if the parent process does.
  --port                              Used by IDEs to specify a port number to listen for a connection.
  -c|--configuration <CONFIGURATION>  Configuration under which to build
  -o|--output <OUTPUT_DIR>            Directory in which to find the binaries to be run
```

**Comment by moozzyk** [comment]
I installed mine yesterday - it's .NET Command Line Tools (1.0.0-beta-001598)

**Comment by livarcocc** [comment]
Where are you finding these builds? This is pretty old. We are on 1.0.0-beta-001669 now.

**Comment by moozzyk** [comment]
I installed it from the link on http://dotnet.github.io/. I am pretty sure I did it yesterday:
![image](https://cloud.githubusercontent.com/assets/1438884/13617857/b11c033c-e535-11e5-9364-a2ecfd0da5b9.png)

**Comment by livarcocc** [comment]
@blackdwarf Have we been updating github.io?

@moozzyk Get it from https://github.com/dotnet/cli. Scroll down and you will see a bunch of links to get a more up to date installer.

**Comment by blackdwarf** [comment]
@livarcocc the getting started page points to a LKG build, not to the latest anymore. That is by design. Next update will be when we get the signed installers. 

/cc @piotrpMSFT
