### ISSUE TITLE
Missing packages on the feed

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1755]
`Microsoft.DotNet.ProjectModel.Workspace` depends on `Microsoft.DotNet.Compiler.Common` which depends on `Microsoft.DotNet.Files`.

The first one is published on https://dotnet.myget.org/gallery/dotnet-cli but the dependencies are missing.

cc @brthor

**Comment by livarcocc** [comment]
cc @eerhardt

**Comment by livarcocc** [comment]
I just realized they are not in the list of packages to publish: https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/package/projectsToPack.ps1. I will have a fix for this in a few.

**Comment by prafullbhosale** [comment]
@livarcocc any update on when these would be available?

**Comment by livarcocc** [comment]
@prafullbhosale I have been trying to merge the change for a while, but haven't been having much success.

**Comment by livarcocc** [comment]
This should be available now.
