### ISSUE TITLE
Resolvers Prefer exe on the path regardless of resolution strategy.

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1759]
We have had this existing behavior in our command resolvers for some time now. I'm opening this issue to call out what I see as incorrect behavior and close on what should be happening.

When we find a command via:
- AppLocal (local to .dll file)
- PATH Environment Variable Search
- Project.json Local

If the command is a `.cmd` (only) we then do a subsequent search of the PATH environment variable for a command with the same name but `.exe` extension.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolution/WindowsExePreferredCommandSpecFactory.cs#L25

I think at a minimum, the subsequent search for the `.exe` should be constrained in the same way the original search was (applocal, projectlocal, etc...).

But before digging into the solution:
1 . Why do we prefer .exe over .cmd?
2. If this is the right behavior why don't we have some list defining precedence of extensions? It seems like limiting to .exe and .cmd is pretty limiting and doesn't even cover similar scenarios like .bat.

cc @livarcocc @piotrpMSFT @Sridhar-MS @krwq

**Comment by livarcocc** [comment]
This hasn't really come up as a problem so far. So, I am closing this issue. If someone finds a case where our current policy breaks them, we can re-activate this.
