### ISSUE TITLE
Dotnet CLI v1.0.0 docs

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#1760]
## Steps to reproduce
Try to find the docs

## Expected  behavior
Find docs

## Actual behavior
Few docs

## Environment data
N/A

Documentation being produced in CLI is being tracked by these issues:
- [x] CLI Reference https://github.com/dotnet/core-docs/issues/304
- [x] project.json & global.json reference https://github.com/dotnet/core-docs/issues/256
- [ ] Scenario-focused documentation
  - [ ] Build a Shared Framework App
  - [ ] Build a Standalone App, including targeting non-local RIDs
  - [ ] Build a library
  - [ ] Add & localize resources
  - [ ] Sign your app
  - [x] Using CI with CLI
- [x] Conceptual docs
  - [x] CLI Overview
  - [x] Migrating to CLI from DNX
  - [x] CLI App Types [Standalone vs. Portable]
  - [x] RID & TFM Catalogue

**Comment by blackdwarf** [comment]
This is now in motion. The relevant PR is dotnet/core-docs#391 and it has many of these.

**Comment by blackdwarf** [comment]
This is now done and docs exist on docs.microsoft.com/dotnet. Closing.
