### ISSUE TITLE
"Restore --packages" behavior changed. Intentional?

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1764]
`dotnet restore <project> --packages <folder>`

- in CLI version `1.0.0.001540` restores the packages in `<folder>` relative to the current directory.
- in CLI version `1.0.0.001669` restores the packages in `<folder>` relative to the `<project>`'s folder.

Is this an intentional change? It seems very strange to restore relative to the project

cc @emgarten

**Comment by ryanbrandenburg** [comment]
It seems that this behavior is windows only? When I tried the repro steps that worked on windows on Ubuntu it did not work.

**Comment by emgarten** [comment]
This looks like a bug in nuget from a recent change. Resolving this path relative to the current directory seems correct.

**Comment by cheers00** [comment]
I am getting the following error for 
```
dotnet.exe new
dotnet.exe restore
```
Error:
```
C:\Projects\dotnetApp>dotnet.exe restore
log  : Restoring packages for C:\Projects\dotnetApp\project.json...
error: Unable to resolve NETStandard.Library (>= 1.0.0-rc2) for .NETStandardApp,Version=v1.5.
info : Committing restore...
log  : C:\Projects\dotnetApp\project.json
log  : Restore failed in 160ms.

Errors in C:\Projects\dotnet\del\project.json
    Unable to resolve NETStandard.Library (>= 1.0.0-rc2) for .NETStandardApp,Version=v1.5.

NuGet Config files used:
    C:\Users\myname\AppData\Roaming\NuGet\NuGet.Config

```

**Comment by emgarten** [comment]
@cheers00 that looks unrelated to this. If you have a NuGet.Config that contains your sources in the project folder then you might be hitting https://github.com/NuGet/Home/issues/2265  From what I see the restore failed because there are zero package sources.

**Comment by victorhurdugaci** [comment]
@cheers00 please open a different issue and share with us what you have in the `Nuget.config` file

**Comment by victorhurdugaci** [comment]
Marking this as partner blocking because we cannot take the new CLI until this is fixed

**Comment by emgarten** [comment]
The fix for this is in progress.

**Comment by TimBarham** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/3b3fcc8c4eb18e86b336609f337cdcfa0ce34ae5.

**Comment by victorhurdugaci** [comment]
@ryanbrandenburg once this gets through the CI, can you please undo the workaround from KoreBuild?

**Comment by piotrpMSFT** [comment]
The fix here is blocked by https://github.com/NuGet/Home/issues/2304

**Comment by livarcocc** [comment]
@victorhurdugaci This does not repro anymore.
