### ISSUE TITLE
Dependency duplication in project export targeting net451

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#1771]
## Steps to reproduce

Reference `System.Collections` in `dependencies` section and `frameworkAssemblies`

https://github.com/aspnet/Mvc/blob/ac58e8433c88f6a02029a5aed8806d60b2ba33ea/src/Microsoft.AspNetCore.Mvc.Razor/project.json
## Expected  behavior

`System.Collections` package reference gets transformed into `ReferenceAssembly` and `Microsoft.AspNetCore.Mvc.Razor` has only one `System.Collections` dependency.
## Actual behavior

`Microsoft.AspNetCore.Mvc.Razor` has dependency to `System.Collections` package and `System.Collections` `ReferenceAssembly`
## Environment data

`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001674)

Product Information:
 Version:     1.0.0-beta-001674
 Commit Sha:  b71e18e1fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

/cc @davidfowl

**Comment by piotrpMSFT** [comment]
@pakrym given how much the system has changed and that we didn't need to fix this for the previous N releases I'm assuming this issue is no longer needed. Please re-open with a description/repro in terms of MSBuild CLI if you feel that's not the right call.
