### ISSUE TITLE
`dotnet new` should not set executable mode on generated files; also, obey umask

### ISSUE THREAD

**Issue by wyoung** [dotnet/cli#1774]
## Steps to reproduce

```
$ ssh some-mac-box
$ mkdir foo
$ cd foo
$ dotnet new
$ ls -l
```
## Expected  behavior

Given the OS X default `umask` = 0022, the output of the `ls -l` command should be:

```
-rw-r--r--  1 wyoung  staff  386 Mar  9 10:54 NuGet.Config
-rw-r--r--  1 wyoung  staff  202 Mar  9 10:54 Program.cs
-rw-r--r--  1 wyoung  staff  227 Mar  9 10:54 project.json
```
## Actual behavior

All three generated plain text files have their executable bit set, and the default permissions selected by the user with their [`umask` setting](https://en.wikipedia.org/wiki/Umask) are ignored:

```
-rwx------  1 wyoung  staff  386 Mar  9 10:54 NuGet.Config*
-rwx------  1 wyoung  staff  202 Mar  9 10:54 Program.cs*
-rwx------  1 wyoung  staff  227 Mar  9 10:54 project.json*
```
## Environment data

`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 Runtime Id:  osx.10.10-x64
```

This also affects the current Ubuntu 14.04 build as well:

```
.NET Command Line Tools (1.0.0-beta-001668)

Product Information:
 Version:     1.0.0-beta-001668
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

**Comment by blackdwarf** [comment]
This is still happening and we should really not be doing this. 

@livarcocc @mlorbetske we should keep this in mind as we progress to our new `new` work. 

/cc @piotrpMSFT @sayedihashimi

**Comment by charlieman** [comment]
Looking through the new command code, it seems like it just extracts a zip file with the template structure in it. So, maybe re-zip the template with the correct permissions?

**Comment by blackdwarf** [comment]
@mlorbetske @seancpeters will `new3` also have this problem?

**Comment by mlorbetske** [comment]
@seancpeters lets try this out on in the morning to make sure the files in the archive have the right permissions set

**Comment by mlorbetske** [comment]
Looks like this has been fixed with https://github.com/dotnet/coreclr/pull/7995 and will be shipped with a future release to the runtime. `new3` has this behavior of setting the executable bit in the mask as well as we use `File.Create` to make the target files (the behavior came from FileStream itself)

**Comment by blackdwarf** [comment]
Thanks @mlorbetske, will close this one then since the fix is not in the CLI and we have dotnet/coreclr#7995.
