### ISSUE TITLE
Can not add property System.Collections to Newtonsoft.Json.Linq.JObject

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#1779]
## Steps to reproduce
[MinimumReproProject.zip](https://github.com/dotnet/cli/files/166172/MinimumReproProject.zip)
With the latest CLI (1672 at this writing) dotnet restore then dotnet pack the above project.

## Expected  behavior
Packaging should complete without issue.

## Actual behavior
```
Compiling MusicStore for DNX,Version=v4.5.1
Can not add property System.Collections to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
```

## Environment data
`dotnet --version` output:
```
.NET Command Line Tools (1.0.0-beta-001672)

Product Information:
 Version:     1.0.0-beta-001672
 Commit Sha:  12dd8d6112

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by muratg** [comment]
Seems to be the same as https://github.com/dotnet/cli/issues/1775 

@piotrpMSFT Can someone look into this please?

**Comment by livarcocc** [comment]
This worked at 1.0.0-beta-002071.
