### ISSUE TITLE
[dotnet restore] Xplat restore fails with exception: Access to the path 'C:\Windows\system32\appmgmt\MACHINE' is denied.

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1780]
## Steps to reproduce
- open solution \\vwdbuild01\Temp\antonpis\repro\xplat-restore\ConsoleApp10.zip 
- run dotnet restore <solutionroot\sample.dg>  (edit dg file to point to your paths for projects before restore)

(note it might not repro everytime, but sometimes)

## Expected  behavior

restore to work
## Actual behavior

exception:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Program Files\dotnet\bin\dotnet.exe restore "C:\Users\antonpis\AppData\Local\Temp\tmpB869.tmp.dg" -f "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages" -f "C:\Program Files (x86)\Microsoft WCF Data Services\5.6.4\bin\NuGet" -f "C:\Program Files (x86)\Microsoft SDKs\Microsoft Azure\Mobile Services\2.0\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages" -f "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\NuGet Packages" -f "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Packages" -f "C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Stack 5\Packages" -f "C:\Program Files (x86)\Microsoft SDKs\Application Insights" -f "C:\Program Files (x86)\Microsoft Web Tools\Packages"
log  : Restoring packages for C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp10\src\ConsoleApp10\project.json...
info : Committing restore...
log  : C:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp10\src\ConsoleApp10\ConsoleApp10.xproj
log  : Restore completed in 824ms.
NuGet Config files used:
    C:\Users\antonpis\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
    C:\Program Files (x86)\Microsoft WCF Data Services\5.6.4\bin\NuGet
    C:\Program Files (x86)\Microsoft SDKs\Microsoft Azure\Mobile Services\2.0\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\NuGet Packages
    C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Stack 5\Packages
    C:\Program Files (x86)\Microsoft SDKs\Application Insights
    C:\Program Files (x86)\Microsoft Web Tools\Packages
Access to the path 'C:\Windows\system32\appmgmt\MACHINE' is denied.

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001673)

Product Information:
 Version:     1.0.0-beta-001673
 Commit Sha:  628f54c77c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by emgarten** [comment]
@abpiskunov NuGet xplat is listing out all of the environment variables or that is a command you performed first?  I'm confused as to why NuGet would try to access this random path.

**Comment by abpiskunov** [comment]
env variables are listed by us, they are passed to dotnet process and are just for information so user would know in what environment we called dotnet restore

**Comment by emgarten** [comment]
It looks like an invalid feed is being passed into restore. Was DNU ignoring bad sources? Are these being read from the registry or where does the path ``C:\Windows\system32\appmgmt\MACHINE`` come from?

**Comment by abpiskunov** [comment]
I don't know where this path is coming from , it is not a feed it is an exception message. Here are feeds that it outputs when I run vs as Admin (i.e. in successful restore scenario):
NuGet Config files used:
    C:\Users\antonpis\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages
    C:\Program Files (x86)\Microsoft WCF Data Services\5.6.4\bin\NuGet
    C:\Program Files (x86)\Microsoft SDKs\Microsoft Azure\Mobile Services\2.0\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v2.0\Packages
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Entity Framework Tools\NuGet Packages
    C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\Packages
    C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Stack 5\Packages
    C:\Program Files (x86)\Microsoft SDKs\Application Insights
    C:\Program Files (x86)\Microsoft Web Tools\Packages

There no that path in the feeds.

**Comment by emgarten** [comment]
Try running dotnet restore with ``--verbosity verbose`` to get the full stack trace.

**Comment by abpiskunov** [comment]
Actually I see that in command line there no such exception, so it might be something in VS printing to that output pane. I am closing this issue for now and open a TFS bug for us to investigate.

**Comment by abpiskunov** [comment]
I am reactivating this issue. This error happens when tools are restored and Vs is not elevated. This did not happen for me in console since tools are not restored when I run same command in console. Tools are restored only in VS.

Note: there are several tools that are restored , some of them in web templates. Why they are restored for my console or class library apps?

**Comment by emgarten** [comment]
@abpiskunov you are seeing the same error as before? Where are you expecting a fix to be made here?

**Comment by abpiskunov** [comment]
This is in the code that restoring tools. Hold in with this , Joel tested latest dev bits in dotnet and issue did not repro, I am waiting on official latest installer to try things out with that.

**Comment by abpiskunov** [comment]
Closing - I tried latest dev installer and this error is gone, so assume it was fixed.
