### ISSUE TITLE
[dotnet restore] xplat restore does restores for template tools everytime 

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1781]
## Steps to reproduce

- open solution \\vwdbuild01\Temp\antonpis\repro\xplat-restore\ConsoleApp10.zip 
- run dotnet restore (edit dg file to point to your paths for projects before restore)

## Expected  behavior
If tools restore is needed, it might happen only first time and then when something changed , but not everytime... 

## Actual behavior

Several tools are also restored with the project everytime manual restore is triggered. Is it really necessary to restore them everytime? I have a very small project and it's restore takes a fraction of some mysterious tools ... it can be done first time only ?

Writing 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\StarterWeb\obj\b0c8fdb6-4e51-4f74-888c-6d1bc508b65d\bin\project.lock.json' to 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\StarterWeb\artifacts\Tools\dotnet-publish-iis\project.lock.json'
Restoring Tool 'dotnet-razor-tooling' for 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\StarterWeb\obj\56c5ca4b-91d2-4210-9951-a35a02798466\bin\project.json' in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\StarterWeb\obj\56c5ca4b-91d2-4210-9951-a35a02798466\bin'
log  : Restoring packages for C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\StarterWeb\obj\56c5ca4b-91d2-4210-9951-a35a02798466\bin\project.json...
log  : Restoring packages for C:\Users\antonpis\documents\visual studio 2015\Projects\ConsoleApp10\src\ConsoleApp10\project.json...
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.dynamic.runtime/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.runtime.loader/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.security.cryptography.algorithms/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.csharp/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.xml.xdocument/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.reflection.metadata/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.filesystemglobbing/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.io.filesystem/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.linq/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.runtime/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/system.reflection/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.platformabstractions/index.json
info : Committing restore...
log  : C:\Users\antonpis\documents\visual studio 2015\Projects\ConsoleApp10\src\ConsoleApp10\ConsoleApp10.xproj
log  : Restore completed in 315ms.
info : Committing restore...
log  : C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\WebTemplates\DNX\CSharp\1033\StarterWeb\obj\56c5ca4b-91d2-4210-9951-a35a02798466\bin\project.json
log  : Restore completed in 1127ms.
NuGet Config files used:
    C:\Users\antonpis\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

## Environment data
`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001673)

Product Information:
 Version: 1.0.0-beta-001673
 Commit Sha:  628f54c 

Runtime Environment:
 OS Name: Windows
 OS Version: 10.0.10586
 OS Platform: Windows
 Runtime Id: win10-x64

**Comment by abpiskunov** [comment]
Addition to the issue with multiple tools restores:

-	When restore starts it restores all requested projects from the dg file. Then after that tools are restored. For each tool projects are restored again and project.lock jsons are updated every time. So for each restore request project ends up restoring X times depending how many tools are there.

**Comment by joelverhagen** [comment]
There are actually two things going on here. The first iteration of tool restore that was implemented in NuGet (by me) does not read in the existing lock file and therefore does not do all the no-op that a normal project does. Another thing that could be happening is that @brthor's existing tool restore code is running.

**Comment by abpiskunov** [comment]
I am using whatever is merged to dotnet and on last week i was told it is not ready and real working xplat restore was not merged yet to dotnet.

Is it merged now? If not is it possible to test latest and merge to dotnet along with the change to output project.lock.json in default verbosity?

Thanks,
Anton

On Mar 16, 2016, at 6:37 PM, Joel Verhagen <notifications@github.com<mailto:notifications@github.com>> wrote:


There are actually two things going on here. The first iteration of tool restore that was implemented in NuGet (by me) does not read in the existing lock file and therefore does not do all the no-op that a normal project does. Another thing that could be happening is that @brthor<https://github.com/brthor>'s existing tool restore code is running.

-

**Comment by brthor** [comment]
Fixed via #1920
