### ISSUE TITLE
AccessUnhandled exception: Access violation reading location

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#1785]
## Steps to reproduce

1. Clone the latest MVC.
2. If you already have one delete your .build folder so that you get 1672.
2. build.cmd

## Expected  behavior
No exceptions.

## Actual behavior
Exception `Unhandled exception at 0x00007FF85F6EB108 (coreclr.dll) in csc.exe: 0xC0000005: Access violation reading location 0x000001C71F9FC8D0.` is thrown when we reach compilation of Microsoft.AspNetCore.Mvc.Core for NetStandard1.3.

## Environment data
`dotnet --version` output:
```
.NET Command Line Tools (1.0.0-beta-001672)

Product Information:
 Version:     1.0.0-beta-001672
 Commit Sha:  12dd8d6112

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```
Here's (\\RyanB-01\Shared\Microsoft.AspNetCore.Mvc.Core.dmp) a dump.

**Comment by pakrym** [comment]
Seems related: https://github.com/dotnet/roslyn/issues/9632

**Comment by davidfowl** [comment]
Seems like crossgen.

/cc @jaredpar @gkhanna79 @JohnChen0 @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@jkotas as well

**Comment by piotrpMSFT** [comment]
@ryanbrandenburg is the repro 100%?

**Comment by pranavkm** [comment]
It reproed pretty consistently on our build machine. We deleted all the .ni.dlls and that got the build working.

**Comment by piotrpMSFT** [comment]
Ok. With a consistent repro, I think @jkotas and @gkhanna79 should be able to help us track down the issue fairly quickly.

**Comment by muratg** [comment]
:eyes:

**Comment by gkhanna79** [comment]
@JohnChen0 Can you please take a look at the dump above?

**Comment by gkhanna79** [comment]
@JohnChen0 Looks like this maybe same as to https://github.com/dotnet/roslyn/issues/9632

**Comment by gkhanna79** [comment]
CC @fadimounir

**Comment by gkhanna79** [comment]
What is the MVC repo url?

**Comment by pakrym** [comment]
https://github.com/aspnet/Mvc/
