### ISSUE TITLE
Proxy param is unavailable

### ISSUE THREAD

**Issue by HalfLegend** [dotnet/cli#1788]
## Steps to reproduce
My computer is behind a proxy, and the proxy is correctely configuared in IE settings.
"dotnet restore":
error: Object reference not set to an instance of an object.
and some compilation problem is there

and there is no Proxy parameter which used to be there

## Expected  behavior
restored successfully

## Actual behavior

error: Object reference not set to an instance of an object.
trace: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
trace:    at System.Net.Http.WinHttpAuthHelper.SetWinHttpCredential(SafeWinHttpHandle requestHandle, ICredentials credentials, Uri uri, UInt32 authScheme, UInt32 authTarget)
trace:    at System.Net.Http.WinHttpAuthHelper.PreAuthenticateRequest(WinHttpRequestState state, UInt32 proxyAuthScheme)
trace:    at System.Net.Http.WinHttpHandler.<StartRequest>d__102.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.HttpRetryHandler.<SendAsync>d__13.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.HttpSource.<SendWithCredentialSupportAsync>d__25.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at NuGet.Protocol.HttpSource.<GetThrottled>d__20.MoveNext()

## Environment data
`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001661)

Product Information:
 Version:     1.0.0-beta-001661
 Commit Sha:  2b90a2f831

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64

**Comment by Oger-Me** [comment]
you can try use the profixer proxy soft. and then I think MS will be support proxy parameter config.

**Comment by blackdwarf** [comment]
@HalfLegend if this still reproes, it should be moved to Nuget/Home repo as this is a Nuget issue.
