### ISSUE TITLE
[Suggestion] Rename precompile/postcompile to prebuild/postbuild

### ISSUE THREAD

**Issue by mmalolepszy** [dotnet/cli#1790]
Considering removal of `dotnet compile` as a top level command (#1574) wouldn't it be better to rename precompile/postcompile events to prebuild/postbuild? I find it a little bit confusing now.

**Comment by blackdwarf** [comment]
This is actually changed in `project.json` AFAIK. Also, this is not applicable in the msbuild world since this kind of data will go into `csproj`.
