### ISSUE TITLE
dotnet restore fails to find sibling project when attempting to use sibling's 'name' instead of the directory

### ISSUE THREAD

**Issue by fearthecowboy** [dotnet/cli#1794]
## Steps to reproduce
I have a solution with two projects, 'lib1' and 'lib2' :
``` text
\---src
    +---lib1
    \---lib2
```

lib1's project.json
``` json
{
    "name": "fearthecowboy.library1",
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23909"
    },

    "frameworks": {
        "netstandardapp1.5": {
            "imports": [ "dnxcore50", "portable-net45+win8" ]
        }
    }
}
```

lib2's project.json
``` javascript
{
    "name": "fearthecowboy.library2",
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23909",
        // actual reference  this is needed to reference the sibling project: */
        "lib1": "1.0.0-*"
        
        // but it would be nicer if I could use it's actual name
        // because if I split them up and reference lib1 it as a package
        // I have to change it to it's actual name 
        // desired reference :
        "fearthecowboy.lib1": "1.0.0-*"
    },

    "testRunner": "xunit",

    "frameworks": {
        "netstandardapp1.5": {
            "imports": [ "dnxcore50", "portable-net45+win8" ],
        }
    }
}
```
## Expected  behavior
I expected that dotnet-restore for `lib2` would find the sibling project `lib1`, look in the project.json and discover it's `name` (`fearthecowboy.library1`) so that when I referenced by it's actual name, dotnet restore would find the right one. 

## Actual behavior
dotnet restore can't find the sibling project `fearthecowboy.library1` and I've been forced to reference it by `lib1` ( the folder name )

``` text
error: Unable to resolve fearthecowboy.library1 (>= 1.0.0) for .NETStandardApp,Version=v1.5.
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001685)

Product Information:
 Version:     1.0.0-beta-001685
 Commit Sha:  c33c2ff127

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14282
 OS Platform: Windows
 Runtime Id:  win10-x64

```

**Comment by emgarten** [comment]
The name property in project.json is not used when resolving project references.

**Comment by davidfowl** [comment]
Yes that property will be removed until we do a feature here

**Comment by fearthecowboy** [comment]
> Yes that property will be removed until we do a feature here

**Seeking Clarification: **Uh, are you saying that you're going to **remove **the ability to name the output assembly from `dotnet-cli` until more feature work ?

... just want to know what to expect ...

**Comment by davidfowl** [comment]
No that will be doable. There another PR adding outputname to the compilationOptions. You can't change the project name though

**Comment by fearthecowboy** [comment]
> You can't change the project name tho' ... 

You mean that the folder name will have to be the same as the desired output package name? (at the moment `name` currently overrides that behavior)

...to be clear, I actually *liked* that, but ... certain elements in my team have made `Exceedingly.Long.Package.Names.For.SomeLibraries` and when building them ... in some places, we've been bumping up against `MAX_PATH` (with all the `.\bin\debug\framework\win7-x64\Exceedingly.Long.Package.Names.For.SomeLibraries.dll` type names...

**Comment by davidfowl** [comment]
Yea and I agree it should be fixed but it's not going on anybody's radar right now and requires nuget changes

**Comment by fearthecowboy** [comment]
Ok, no worries. I'll work around it. :)

**Comment by blackdwarf** [comment]
I think this can be closed now since there is a workaround in the issues not to mention that with msbuild work this will be completely different. 

@fearthecowboy if you think this should still be tracked, it should be filed in Nuget/Home since `dotnet restore` uses nuget under the covers to do the restore.
