### ISSUE TITLE
Can't target `net20`, `net30`, `net35` on non-Windows

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1799]
When targeting desktop framework versions on non-Windows, the `DOTNET_REFERENCE_ASSEMBLIES_PATH` variable is required. However, when this variable is set, **and** the project targets a "Legacy" framework (older than 4.0), we try to read the `WINDIR` environment variable and sadness happens.

The easiest fix is to probably just avoid using this Legacy model on non-Windows, by just adding an `IsWindows` check here https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Resolution/FrameworkReferenceResolver.cs#L210. I didn't have time to work that through the pipeline so I'm filing a bug :).

/cc @troydai

**Comment by troydai** [comment]
Fixed in 429625061dc64bf1b8a53d140486b301612b2727
