### ISSUE TITLE
Enable xunit test execution

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#18]
https://github.com/piotrpMSFT/dotnet-test-samples/

That will show you how to start playing with the prototype xunit runner. If you find issues, please feel free to open them here:

https://github.com/dotnet/coreclr.xunit

**Comment by andschwa** [comment]
Yes please, we could use this very much :+1:

**Comment by stankovski** [comment]
+1

**Comment by andschwa** [comment]
+100

**Comment by piotrpMSFT** [comment]
FYI, we have a working prototype xunit runner. I'm working on PR to xunit and will try to share a "pre-alpha" package.

**Comment by andschwa** [comment]
That would be fantastic.

**Comment by piotrpMSFT** [comment]
Okie folks, here it is!

https://github.com/piotrpMSFT/dotnet-test-samples/

That will show you how to start playing with the prototype xunit runner. If you find issues, please feel free to open them here:

https://github.com/dotnet/coreclr.xunit

Thanks, @livarcocc for test-driving the sample and reviewing the readme content!

**Comment by andschwa** [comment]
Sweet! Will try it out first thing tomorrow morning :D

**Comment by muratg** [comment]
Nice, thanks @piotrpMSFT!

**Comment by victorhurdugaci** [comment]
@piotrpMSFT found a bug: https://github.com/dotnet/cli/issues/895

**Comment by brthor** [comment]
too cool!

**Comment by victorhurdugaci** [comment]
Ignore my previous message

**Comment by piotrpMSFT** [comment]
did anyone have a chance to play with this today? Or did broken CLI packages slow us down?

**Comment by andschwa** [comment]
I had a couple issues getting the right feeds added (needed aspnetvnext/ci
for MEPA). Had a runtime error in the test runner but still debugging. So
far looks promising!

**Comment by victorhurdugaci** [comment]
I was able to run the samples but couldn't get any ASPNET test to run. It fails to discover the runner. Still investigating



On Tue, Jan 19, 2016 at 10:11 PM -0800, "Andy Schwartzmeyer" <notifications@github.com<mailto:notifications@github.com>> wrote:

I had a couple issues getting the right feeds added (needed aspnetvnext/ci
for MEPA). Had a runtime error in the test runner but still debugging. So
far looks promising!
On Jan 19, 2016 8:33 PM, "Piotr Puszkiewicz" <notifications@github.com>
wrote:

> did anyone have a chance to play with this today? Or did broken CLI
> packages slow us down?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/dotnet/cli/issues/18#issuecomment-173084383>.
>

-

**Comment by piotrpMSFT** [comment]
sounds good. Let me know if you want help debugging. I just started converting CLI tests, hoping I beat you to issues...

**Comment by victorhurdugaci** [comment]
The test runner fails when the project targets `dnx451` in addition to `dnxcore50`: https://github.com/dotnet/cli/issues/913

**Comment by piotrpMSFT** [comment]
It should just skip the dnx451. Taking a look...

**Comment by ealexjordan** [comment]
This does not yet work for the internal project @andschwa and I are working on.

Even getting the sample working failed. I bumped NETStandard.Library to "1.0.0-rc3-23726", included `"imports": "portable-net45+win8"` to the `dnxcore50` framework, and included the `aspnetvnext feed in `nuget.config` to get `dotnet restore` to bring in `"xunit": "2.1.0"` and `"dotnet-test-xunit": "1.0.0-dev-*"` correctly.

I am using `dotnet-nightly` version 1.0.1.001022 package on Ubuntu 14.04. 

Error I am receiving after restoring the packages and running `dotnet test` is: 

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)

It appears that the `"testRunner": "xunit"` is wanting a different `System.Runtime.Extensions` version than the restored packages provide.

My [fork](https://github.com/ealexjordan/dotnet-test-samples) repros.

Any further information or pointers for me?

**Comment by piotrpMSFT** [comment]
Thanks for reporting. I'm seeing this in the samples project. Working on an update.

**Comment by piotrpMSFT** [comment]
Looks like our recent package madness broke dotnet-test... @piotrpmsft neglected to add unit tests for dotnet-test test test test.

I'll work on a fix asap.

**Comment by victorhurdugaci** [comment]
@piotrpMSFT got a new build by any chance?

**Comment by andschwa** [comment]
@piotrpMSFT any movement on this? My bosses are asking again. I don't see a new package.

**Comment by victorhurdugaci** [comment]
There was a new package a few days ago and we (asp.net) were able to use it. @kichalla actually does the conversion right now

**Comment by andschwa** [comment]
@victorhurdugaci Which feed? I checked all those in the sample's Nuget.Config, perhaps I missed it.

**Comment by piotrpMSFT** [comment]
@livarcocc can you share the feed?

**Comment by zach-folwick** [comment]
@livarcocc,  @piotrpMSFT-  is that feed posted anywhere?

**Comment by andschwa** [comment]
Sorry to bug you again, but what's the status here? We've been unable to run our unit test suite since switching to CLI, this issue should probably be considered blocking partner (blocking our ability to test).

The [coreclr-xunit feed](https://www.myget.org/F/coreclr-xunit/api/v2) is now inaccessible. Can I get an ETA to give to my bosses?

**Comment by andschwa** [comment]
By a massive stroke of luck, I have found the new home of `dotnet-test-xunit`. The [cli-deps feed](https://dotnet.myget.org/gallery/cli-deps/) has it.

It indeed works on Linux, though it requires some fixing of our use of CLI (all necessary needs to be controlled by CLI so the runner can access it).

**Comment by andschwa** [comment]
@piotrpMSFT @livarcocc Please update the examples and documentation for the new feed, so others don't have to hunt it down.

**Comment by MichaelSimons** [comment]
Per the documentation on the the [cli-deps feed](https://dotnet.myget.org/gallery/cli-deps/), "This feed is used internally for dotnet/cli. Please don't consume it from other projects."  It looks like the true source of the dotnet-test-xunit package is https://www.myget.org/F/coreclr-xunit/api/v3/index.json.  This would be a better location to reference it from.

**Comment by tinchou** [comment]
What about [the aspvnext feed](https://www.myget.org/gallery/aspnetvnext)? It contains the `dotnet-test-xunit` package too, but with this [Nuget.config](https://github.com/dotnet/coreclr.xunit/blob/79e0afc921e9e9b5a0ffb5ede791564b4f74e7ff/NuGet.Config) and a very simple `project.json` file I'm getting

```
xunit.abstractions 2.0.0 is not compatible with DNXCore,Version=v5.0
```

**Comment by shayhatsor** [comment]
@tinchou, this works:
```json
 "dnxcore50": { 
       "dependencies": { 
         "dotnet-test-xunit": "1.0.0-dev-*" 
       }, 
       "imports": "portable-net451+win8" 
     }, 
```

**Comment by andschwa** [comment]
@MichaelSimons, the coreclr-xunit feed does not contain the package's dependencies, requiring you to use, say, aspnetvnext, which many people don't want. Likewise we don't to have to use cli-deps either.

The better fix would be to add the necessary dependences to coreclr-xunit still that it's standalone, and figure out why its gallery doesn't work.

**Comment by victorhurdugaci** [comment]
@tinchou the ASP.NET team clones the packages on their feed. That's why you see it there too. Also, the package is only for coreclr; it doesn't work on desktop clr.

**Comment by tinchou** [comment]
Thanks, I managed to run some tests by adding `"imports": "portable-net451+win8"` as @shayhatsor mentioned!

**Comment by frapontillo** [comment]
This is related to https://github.com/xunit/coreclr.xunit/pull/1, but it looks like it's not being accepted nor considered.

**Comment by natemcmaster** [comment]
@frapontillo xunit is waiting for RC2 to make any changes or updates. https://twitter.com/xunit/status/702918824769662976

**Comment by piotrpMSFT** [comment]
@livarcocc adding dependencies to the CoreCLR-xunit feed seems reasonable. Thoughts?

**Comment by piotrpMSFT** [comment]
Right. We are stabilizing the xunit runner. We don't want to churn xunit folks while the dotnet-test story locks down.

Package for 4.5.1 is a second concern. There is a PR to the xunit runner repo which starts adding 451 support, though it hasn't been finished.

**Comment by piotrpMSFT** [comment]
This is done for a while now...
