### ISSUE TITLE
apt-get install dotnet on Debian Jessie fails with error

### ISSUE THREAD

**Issue by pieandcakes** [dotnet/cli#1800]
## Steps to reproduce
sudo apt-get install dotnet

## Expected  behavior
installs dotnet
## Actual behavior
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
** dotnet : Depends: liblldb-3.6 but it is not installable**

## Environment data
`dotnet --version` output:

**Comment by pieandcakes** [comment]
I'm using Debian 8.2 and followed the instructions for Ubuntu and tried to install both through apt-get or the .deb package.

**Comment by branciat** [comment]
The Debian Jessie install by default the llvm-3.5 which is conflict with the liblldb-3.6 that require the llvm 3.6, it seems. On sid it's alright.

**Comment by jeremymeng** [comment]
see the workaround in https://github.com/dotnet/cli/issues/1001.

**Comment by blackdwarf** [comment]
The workaround in #1001 will solve this problem, so closing this issue. Please reopen if you are still seeing this. 

Also, be aware that we have Debian-specific instructions on https://dot.net/core.
