### ISSUE TITLE
Process.WaitForExit in Command.Execute should have a timeout

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#1805]
The underlying issue might be related to #1785, but we saw an issue on our build agent where `dotnet restore` was stuck on the `WaitForExit` for over 3 hours. Seems like it should timeout after some reasonable duration.

**Comment by brthor** [comment]
The hang itself being a separate issue, I'm not sure if the cli should be timing out child processes.

We have no idea how long it is expected to take or if it should actually never go down (thinking server applications).

**Comment by piotrpMSFT** [comment]
This hasn't come up for quite some time, so closing.
