### ISSUE TITLE
CoreCLR not present in dotnet.deps.json

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1811]
## Steps to reproduce
build repo

## Expected  behavior
Since `dotnet` is a fully published app as of now, `dotnet.deps.json` should contain an entry for coreclr.dll similar to `dotnet.deps`

`artifacts\win10-x64\stage2\bin\dotnet.deps.json`

@anurse @pakrym @piotrpMSFT @gkhanna79 

XUnit tests are breaking in #1792 CI because, `dotnet build` doesn't drop coreclr and `dotnet test` is supposed to use `--additionalprobingpath` to load up the CoreCLR.

**Comment by schellap** [comment]
Not needed for now.

**Comment by schellap** [comment]
This is needed for the corehost changes to be checked in...

If you issue, `dotnet build`, the deps.json file doesn't contain an entry to coreclr.dll

**Comment by schellap** [comment]
@pakrym, pls take a look at this when you get a chance...

**Comment by schellap** [comment]
@anurse is looking into this...

**Comment by anurse** [comment]
Yep, #1828
