### ISSUE TITLE
dotnet restore exception on OS X 10.10.5 

### ISSUE THREAD

**Issue by aguacongas** [dotnet/cli#1813]
## Steps to reproduce
I installed `dontnet CLI` from http://dotnet.github.io/getting-started/.   
I installed `openSSL` with `brew install openssl` command.  
I run `dotnet new` in a new folder under my documents the command works well.  
I run `dotnet restore` the console display this message.  

> Exception has been thrown by the target of an invocation.
## Expected  behavior
I expect the `dotnet restore` command restores packages

## Actual behavior
> Exception has been thrown by the target of an invocation.

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 Runtime Id:  osx.10.10-x64

**Comment by coldacid** [comment]
I get the same issue with build 1661 on Windows after installing through the MSI.

Version output:
```
.NET Command Line Tools (1.0.0-beta-001661)

Product Information:
 Version:     1.0.0-beta-001661
 Commit Sha:  2b90a2f831

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 Runtime Id:  win81-x64
```

**Comment by remms** [comment]
Same happens to me, following instructions from: http://dotnet.github.io/getting-started/

```
dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by blackdwarf** [comment]
This issue references a very old version of the CLI. You can see all of the instructions for macOS installation on https://www.microsoft.com/net/core#macos. I will close this issue, but if you still have problems after following the installation instructions on the link, please reopen and update the issue.
