### ISSUE TITLE
El Capitan commentary on "known issues" page is obsolete

### ISSUE THREAD

**Issue by tangentsoft** [dotnet/cli#1815]
The [known issues](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/known-issues.md) page references two GitHub issues preventing `dotnet` from working correctly on El Capitan, but both of those issues are now closed with committed fixes. That whole section can probably be removed.

(I say "probably" because I don't have any machines running El Capitan yet.)

**Comment by blackdwarf** [comment]
@tangentsoft good catch.
