### ISSUE TITLE
Unverified publisher when installing CLI

### ISSUE THREAD

**Issue by mertozturk80** [dotnet/cli#1816]
## Steps to reproduce
When downloading dotnet-win-x64.1.0.0.001598.exe -  DotNet CLI - I got a warning like "The publisher of dotnet-win-x64.1.0.0.001598.exe couldn't be verified. Are you sure you want to run the program. " Message.

BTW, The EXE is certainly not digitally signed, which may be “by design” at this stage in the process..

## Expected  behavior

This exe can be digitally signed, not to get this warning.

## Actual behavior

When downloading dotnet-win-x64.1.0.0.001598.exe -  DotNet CLI - I got a warning like "The publisher of dotnet-win-x64.1.0.0.001598.exe couldn't be verified. 

## Environment data
`dotnet --version` output: Microsoft DotNet CLI for Windows(1.0.0.001598)

**Comment by blackdwarf** [comment]
@mertozturk80 we are working towards signing. The work is tracked in #1654

**Comment by mertozturk80** [comment]
Ok thank you.
