### ISSUE TITLE
[dotnet restore] xplat restore to change format for tools to be able to track progress

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1818]
## Steps to reproduce
This is a feature request, not really a bug..

dnu restore used to output projects in order of their restore completion:
project1 restore started...
...
project1.lock.json generated 

project2 restore started 
...
project2 lock file generated
...

We used that order to determine project restore completion and update a progress bar in VS. 

Now xplat restore does not have a format that we could recognize.. Notice that we are not really parsing text but referred to number of times \project.lock.json was printed. What options we have now? Is it possible to adjust output to some trackable format?

## Environment data
`dotnet --version` output:

**Comment by joelverhagen** [comment]
We write the lock file progress at the `debug` level. This can be view by executing the restore with `--verbosity debug`. Code here: [RestoreResult.cs](https://github.com/NuGet/NuGet.Client/blob/272b41b8234e3a241da012e88fd45d0b639e9083/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreResult.cs#L131).

The pattern that we use before writing the lock file is:
```
Writing lock file to disk. Path: {LockFilePath}
```

Note that if we detect that the lock file has not changed, we write:
```
Lock file has not changed. Skipping lock file write. Path: {LockFilePath}
```

Simply counting the `\project.lock.json` will not work any more. You will have to exclude some or include others (depending on your approach).

**Comment by abpiskunov** [comment]
Well this means you would need either to change how you print project.lock.json or provide us with some other marker in the output. 

Why don't you print by default at the end of each project restore : "Generated ...project.lock.json" as it was before in default verbosity level and "Lock file was not changed .." stays under verbosity=Debug which we never call from VS. In this case we would always have what we need without duplications.

(Also, why user needs to know exactly a path to project.lock.json that was changed? Why don't just print: "Project X appears to be up to date, skipping restore etc ... ", or something like that. Isn't that message about that?

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/NuGet/Home/issues/2413. This is a nuget issue and should be tracked there.
