### ISSUE TITLE
Why 'dotnet repl'?

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#182]
Can we change it to something a normal user can understand without using a search engine like "run" "code" "exec" or something which actually means something and not an abbreviation? Wasn't second word supposed to be a verb?

**Comment by piotrpMSFT** [comment]
Looks like we're keeping dotnet-repl.

**Comment by akoeplinger** [comment]
FWIW, `csharp` launches Mono's C# REPL.

So does `dotnet repl` imply C# now? Or will we get `--lang vb | fsharp` eventually?

**Comment by Petermarcu** [comment]
@ManishJayaswal, reopening and assigning to Manish to weigh in.

**Comment by ManishJayaswal** [comment]
C# will be the default. We do plan to add dotnet  repl --language vb | fsharp later.

**Comment by piotrpMSFT** [comment]
@ManishJayaswal, can you close out this issue once it's resolved?

**Comment by ManishJayaswal** [comment]
@kuhlenh FYI

**Comment by ManishJayaswal** [comment]
@kuhlenh FYI

**Comment by ManishJayaswal** [comment]
@kuhlenh FYI

**Comment by kuhlenh** [comment]
Alternatives we had discussed were: "dotnet play", "dotnet interactive", and "dotnet code".

**Comment by piotrpMSFT** [comment]
Do we plan to change?

**Comment by ManishJayaswal** [comment]
At this time we do not plan to change it unless we get feedback from previews. The term repl is getting adopted by industry in general so it will not be a surprise for everyone. Although I agree that folks who have not used it will find it surprising.

**Comment by blackdwarf** [comment]
This issue is not valid anymore, so closing it out. If it is still needed, please reopen.

**Comment by adamralph** [comment]
I would expect to just type `dotnet` to get a REPL, just like I type `node` to a REPL.
