### ISSUE TITLE
dotnet restore is case sensitive of project file name on Windows.

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1821]
## Steps to reproduce
1. `dotnet new`
2. Rename `project.json` to `Project.json`
3. `dotnet restore`

## Expected  behavior
Restore successfully

## Actual behavior
```
$ dotnet restore
log  : Restoring packages for D:\dev\repo\np\Project.json...
info : Committing restore...
log  : D:\dev\repo\np\Project.json
log  : Restore completed in 24604ms.

NuGet Config files used:
    C:\Users\troyd\AppData\Roaming\NuGet\NuGet.Config
Could not find a part of the path 'D:\dev\repo\np\Project.json\project.json'.
```

## Environment data
`dotnet --version` output:

**Comment by anurse** [comment]
This should probably go to NuGet/Home.

**Comment by anurse** [comment]
Never mind, I think it might be in our code after we return from NuGet

**Comment by akoeplinger** [comment]
Supporting `Project.json` seems like a bad idea in general IMHO, it just sets people up with a bad layout that's going to cause issues when the project is taken to a case-sensitive file system. I still have less than fond memories of `NuGet.Config` vs `Nuget.config` vs `Nuget.Config` etc :smile:

**Comment by troydai** [comment]
Bottom line is the error message should make sense.

**Comment by piotrpMSFT** [comment]
=> Nuget/Home?

**Comment by troydai** [comment]
Link: https://github.com/NuGet/Home/issues/2306

Close this one? @piotrpMSFT @anurse

**Comment by anurse** [comment]
Are we still positive this is a NuGet issue? The log shows the restore completing successfully above and **then** the error is raised. Do we still have our secondary tools-restore stuff in there? That might be the one using the wrong case comparison.

**Comment by troydai** [comment]
@anurse the `project.json` created by `dotnet new` doesn't have `tools` section in it.

**Comment by anurse** [comment]
Right, but we still need to read that file to determine that it doesn't have a `tools` section. I'm pretty sure it's this: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/ProjectContext.cs#L76

**Comment by troydai** [comment]
Hum, looks like to be the case.

**Comment by troydai** [comment]
I'll assign this to myself for now.

**Comment by troydai** [comment]
@piotrpMSFT @anurse went through this issue as well as the codes again, I don't think we should fix this. It's beneficial to be case sensitive for cross-platform. It is also hard to determine if a given file system is case sensitive or not. CoreFx doesn't provide this API yet.

I'll close this issue now.

**Comment by anurse** [comment]
> CoreFx doesn't provide this API yet

I don't even know if it could provide that API :). It's file-system-dependent, not OS-dependent. Even on Linux you can have a case-insensitive file system (and on Mac you can have a case-sensitive FS). Short of having an API to get the File System type and a big giant table of "Is this FS case-sensitive", I think we have to assume we'll always be in an environment of unknown case-sensitivity :)

**Comment by akoeplinger** [comment]
> short of having an API to get the File System type and a big giant table of "Is this FS case-sensitive"

@anurse not necessarily. You could imagine an API where you pass in a path and it returns whether the file system on that path is case sensitive or not :)
