### ISSUE TITLE
dotnet restore is not honoring local NuGet.config

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#1826]
## Steps to reproduce
Install latest installer on Windows.

```console
mkdir hwapp && cd hwapp
dotnet new
dotnet restore
```

## Expected  behavior
Restore succeeds. 

## Actual behavior
Restore fails with the below error. It is clear from the error that the `NuGet.config` file that `dotnet new` drops is not used in the restore call.

```console
log  : Restoring packages for /home/blackdwarf/hwapp/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 407ms
error: Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23901) for .NETStandardApp,Version=v1.5.
info : Committing restore...
log  : /home/blackdwarf/hwapp/project.json
log  : Restore failed in 1240ms.

Errors in /home/blackdwarf/hwapp/project.json
    Unable to resolve NETStandard.Library (>= 1.0.0-rc2-23901) for .NETStandardApp,Version=v1.5.

NuGet Config files used:
    /home/blackdwarf/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

## Environment data
`dotnet --version` output:

```console
.NET Command Line Tools (1.0.0-beta-001675)

Product Information:
 Version:     1.0.0-beta-001675
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

**Comment by blackdwarf** [comment]
Needless to say adding the correct feed to the global `NuGet.config` makes the restore successful, but this is not per spec. 
/cc @piotrpMSFT

**Comment by davidfowl** [comment]
This is fixed in the latest nuget. It was a break that happened recently. We need to update our nuget /cc @anurse @emgarten

**Comment by mrmeek** [comment]
fyi #1770 

the work around is to put the nuget.config one directory level up, even if it's outside the project folder (as in the case of dotnet new)

**Comment by blackdwarf** [comment]
@mrmeek this works. @davidfowl @anurse @piotrpMSFT when will the new Nuget come in? This also repros on latest.

**Comment by emgarten** [comment]
@blackdwarf it should have gone in yesterday.

**Comment by blackdwarf** [comment]
@emgarten ah, ok, wil try with the latest tonight to see if this repros again. At least now I can restore on my home machine (with disabiling network devices).
