### ISSUE TITLE
dotnet ef Failed to initialize CoreCLR 

### ISSUE THREAD

**Issue by Cuiqs76** [dotnet/cli#1827]
`  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
    "Microsoft.NETCore.Platforms": "1.0.1-*"
  },

  "tools": {
    "dotnet-ef": "1.0.0-*"
  },

  "frameworks": {
    "dnx451": { },
    "netstandardapp1.5": {
      "dependencies": {
        "NETStandard.Library": "1.0.0-*"
      },
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
   }
`
## Steps to reproduce
dotnet restore - success
dotnet build - success
dotnet ef migrations add initial
## Actual behavior
dotnet ef - Failed to initialize CoreCLR, HRESULT: 0x80004005

## Environment data
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
Version: 1.0.0-beta-001598
Commit Sha: 7582649f88

Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
Runtime Id: win10-x86

**Comment by mrmeek** [comment]
Did you put a nuget.config in your project root? If so, what's in it?

**Comment by Cuiqs76** [comment]
Yes. put a nuget.config created by dotnet new and add 2 package source.
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

`
and another one meet same issue:[https://github.com/aspnet/EntityFramework/issues/4647](url)

**Comment by blackdwarf** [comment]
@Cuiqs76 can you try installing the CRT for VS2015 and seeing if that helps?

**Comment by bruceyclee** [comment]
I have the same issue and C++ Redistributables(VS 2015) was installed on my machine.

**Comment by Cuiqs76** [comment]
I re-install windows 10 and VS2015， the problem is still there.

**Comment by SkyKnight** [comment]
I have same issue even on latest docker container.

**Comment by piotrpMSFT** [comment]
Is this still an issue? If so, I expect the issue is the dependency to NetStandard.Library. Tools in the test directory depend on 

````
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-23931"
        }
````

**Comment by danroth27** [comment]
Dup of #1970
