### ISSUE TITLE
deps.json file does not contain `native` assets

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1828]
These should be present in runtime-specific targets, primarily for the standalone app case.

I've almost got a fix ready but wanted to merge the stuff I had so far and track this so we don't forget.

/cc @schellap @pakrym

**Comment by schellap** [comment]
@anurse, do you mind sharing the branch for the fix? I can uncover any other issues with my host changes.

**Comment by anurse** [comment]
It's not quite working yet, I'm finishing it up this morning. Will open a PR as soon as I have something and you can use that branch to try it out
