### ISSUE TITLE
dotnet new should not create a nuget.config file

### ISSUE THREAD

**Issue by yishaigalatzer** [dotnet/cli#1829]
## Steps to reproduce
dotnet new

## Expected  behavior
Do not create a nuget.config, this was removed from previous versions because it causes trouble in managing nuget settings. Was clearly discussed and we decided to take it out. Not sure how it came back

CC @troydai @piotrpMSFT 

## Actual behavior
It does

## Environment data
`dotnet --version` output:

**Comment by blackdwarf** [comment]
@yishaigalatzer @piotrpMSFT how will people then restore? Are all of the dependencies on nuget.org or is there something else?

**Comment by yishaigalatzer** [comment]
There is a default nuget.config with nuget.org auto created  if nothing is available

**Comment by davidfowl** [comment]
It needs a nuget.config right now because the packages it uses aren't on nuget.org as yet

**Comment by blackdwarf** [comment]
@yishaigalatzer @davidfowl then we cannot remove it yet. We also have another issue, #656, for tracking this work.
