### ISSUE TITLE
Error segmentation

### ISSUE THREAD

**Issue by branciat** [dotnet/cli#1832]
Hi,

I installed the latest package deb of dotnet on my debian machin, i create a directory test and execute the command dotnet new, then the command dotnet restore whose output is 

log  : Restoring packages for /home/jerome/source/MediagralV2.Net/test/project.json...
Erreur de segmentation

The dotnet --version output 

.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 Runtime Id:  debian.-x64

**Comment by branciat** [comment]
The log show 

Mar 14 11:53:33 PC-FOX kernel: [10602.575245] traps: dotnet[10402] general protection ip:7f4b681d3ddd sp:7f4b01768ac0 error:0 in libcrypto.so.1.0.0[7f4b68063000+230000]
Mar 14 11:54:02 PC-FOX kernel: [10631.524017] traps: dotnet[10423] general protection ip:7f79e128eddd sp:7f79c7ffdac0 error:0 in libcrypto.so.1.0.0[7f79e111e000+230000]

My os is sid debian, libssl package version is 1.0.2.

**Comment by branciat** [comment]
Is it possible to have access to the source code of stage0 to make compatible with debian ?

**Comment by branciat** [comment]
I find an assembly System.Security.Cryptography.Native.so into the directory bin of corefx master zip  project that passed on debian.

**Comment by Skywalker13** [comment]
I don't understand why you have closed this issue; the problem persists with debian stretch and the current preview1 of dotnet cli.

**Comment by branciat** [comment]
The runtimes is compatible with the [debian 8.2](https://www.microsoft.com/net/core#debian) version only.
