### ISSUE TITLE
dotnet.deps.json missing in stage1

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#1833]
## Steps to reproduce
build repo

I built using ubuntu.14.04-x64.

## Expected  behavior
`dotnet.deps.json` present in `stage1`

## Actual behavior
Only `dotnet.deps` is present

@anurse or @pakrym PTAL. This is also blocking my PR https://github.com/dotnet/cli/pull/1792 from getting a green CI.

Cc @gkhanna79 @piotrpMSFT

**Comment by pakrym** [comment]
Fixed by https://github.com/dotnet/cli/commit/dc11ed2ba81f4994e8bef2785dd3da441c1355f0
