### ISSUE TITLE
deps.json format changes

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1834]
#### Compilation options section should use boolean values for booleans, not strings.

``` JSON
"compilationOptions": {
    "defines": [
      "DEBUG",
      "TRACE",
      "NETSTANDARD1_5"
    ],
    "optimize": "False",
    "emitEntryPoint": "True"
  },
```

Should be:

```
"compilationOptions": {
    "defines": [
      "DEBUG",
      "TRACE",
      "NETSTANDARD1_5"
    ],
    "optimize": false,
    "emitEntryPoint": true
  },
```
#### There's no need to repeat the sha512 in the sha512 property

``` JSON
    "Microsoft.AspNetCore.Antiforgery/1.0.0-rc2-20143": {
      "type": "package",
      "serviceable": false,
      "sha512": "sha512-nK77WaOvJA13Wqm0nLWEPuuTX3CEfIeAKiL25GE6nb+JA4Jkcvn4n3vjCnTOJXN1jWyfWMM+QW8m29jNGTD0nQ=="
    },
```

should be

``` JSON
    "Microsoft.AspNetCore.Antiforgery/1.0.0-rc2-20143": {
      "type": "package",
      "serviceable": false,
      "sha512": "nK77WaOvJA13Wqm0nLWEPuuTX3CEfIeAKiL25GE6nb+JA4Jkcvn4n3vjCnTOJXN1jWyfWMM+QW8m29jNGTD0nQ=="
    },
```

/cc @anurse @pakrym

**Comment by pakrym** [comment]
Agreed with first point. As for the second I'd prefer renaming `sha512` to `hash` and keeping algorithm name inside because corehost seem to support any hash kind,or keeping it like it is, because it mirrors `.lock.json` format.

**Comment by blackdwarf** [comment]
@davidfowl did we fix this in the end? Can we close this issue?

**Comment by piotrpMSFT** [comment]
Deps file format is fairly locked down at the moment. If you still want to pursue this please open a new issue that includes developments since this was openend.
