### ISSUE TITLE
toolchain name

### ISSUE THREAD

**Issue by cheers00** [dotnet/cli#1837]
What is the official name for this toolchain?

- dotnet cli
- .net cli
- .net core cli

Thanks

**Comment by blackdwarf** [comment]
@cheers00 we should have the official naming soon.

**Comment by ciel** [comment]
I am hoping they go with `.net cli` so it isn't confusing between standard and core.

**Comment by blackdwarf** [comment]
I believe this is now done via #2147 . Will close this one, reopen if the referenced PR did not solve this issue.
