### ISSUE TITLE
Latest Ubuntu feed version is out-of-date

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#1839]
## Steps to reproduce

Install via apt-get feed:

```sh
sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet
```

Or alternatively, using the obtain script:

```
wget https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh
chmod +x install.sh
./install.sh -c beta
```

## Expected  behavior

Install the version of CLI available on the home page, 1.0.0.001718.

```sh
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64
```

## Actual behavior

```sh
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001675)

Product Information:
 Version:     1.0.0-beta-001675
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

$ ./install.sh -c beta
dotnet_install: Preparing to install .NET Tools from 'beta' channel to '/usr/local'
dotnet_install: Latest Version: 1.0.0.001675
```

## Why this is a problem

We're trying to bump our CI system's pinned versions of CLI, and prefer to keep the Linux and Windows systems in sync. We need to upgrade the Windows system to fix #1783. But ran into the Linux packages being woefully behind. Oddly, downloading deb file from the "latest" link on the home page provides a package that gives the actual behavior.

**Comment by hal-ler** [comment]
For me install.sh gives the right version, but "https://dotnetcli.blob.core.windows.net/dotnet/beta/dnvm/latest.ubuntu.version" returns version number 1675.

Output from install.sh for me (after running it once already):
```
dotnet_install: Latest Version: 1.0.0.001675
dotnet_install: Local Version: 1.0.0.001752
dotnet_install: Downloading dotnet-ubuntu-x64.latest.tar.gz from https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest
```

**Comment by andschwa** [comment]
Yeah it's still stuck on 1675, but the latest binary on the homepage is 1760.

**Comment by brthor** [comment]
taking a look

**Comment by brthor** [comment]
Looks like we regressed publishing this to the feed recently. Putting a fix in.

**Comment by andschwa** [comment]
Awesome, thanks @brthor

**Comment by andschwa** [comment]
@brthor We should re-open this, the feed is now stuck at 1.0.0.001793-1.

**Comment by andschwa** [comment]
Hm, this seems separate. That's the same version as the installer on the home page (i.e. what `wget https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-ubuntu-x64.latest.deb` gives you), but does not match the version reported on the home page (1.0.0.001973).

**Comment by brthor** [comment]
@andschwa testing the fixes now. Debs were temporarily disabled with the shared fx changes.
