### ISSUE TITLE
Not enough context for some errors reported by dotnet 

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#1848]
## Steps to reproduce

Quiz: 
Anyone knows what is the root cause here? 

```
PS C:\Source\cli-samples\HelloWeb> dotnet build
Illegal character 'd' (Unicode hexadecimal 0064).
PS C:\Source\cli-samples\HelloWeb> dotnet run
Illegal character 'd' (Unicode hexadecimal 0064).
```
## Expected  behavior

A more detailed error
## Actual behavior

```
PS C:\Source\cli-samples\HelloWeb> dotnet run
Illegal character 'd' (Unicode hexadecimal 0064).
```
## Environment data

`dotnet --version` output:

PS C:\Source\cli-samples\HelloWeb> dotnet --version
.NET Command Line Tools (1.0.0-beta-001673)

Product Information:
 Version:     1.0.0-beta-001673
 Commit Sha:  628f54c77c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
## Answer to the quiz:

The issue is caused by a malformed project.json file where there is an extraneous letter after the closing '}'.

**Comment by piotrpMSFT** [comment]
This is already vastly improved, particularly in msbuild-based preview3
