### ISSUE TITLE
Update `dotnet new` template for portable app model

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1863]
See https://gist.github.com/anurse/63b063f27384806c53b9

We need to change the output of `dotnet new` so that it matches the portable app expectation. **NOTE**: The use of `netstandard1.5` as the TFM is **temporary** due to RID-inference in NuGet. It will be replaced by `netcoreapp1.0` soon.

/cc @piotrpMSFT

**Comment by blackdwarf** [comment]
@anurse I will take this, I have a change for class libraries already, so will finish and send a PR for this for now. Also, we may do something nicer with `dotnet new` and so on.

**Comment by blackdwarf** [comment]
@anurse what is the current TFM for class lib?

**Comment by anurse** [comment]
`netstandard`

**Comment by blackdwarf** [comment]
@anurse why did you close this? :)

**Comment by anurse** [comment]
Because it's done
