### ISSUE TITLE
Replace entities in Testing.Abstractions with entities from TestPlatform from VS

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1864]
Stop using our own home made abstractions and instead use the VS one defined here: http://www.nuget.org/packages/MSTest.ObjectModel/.

**Comment by davidfowl** [comment]
does it target netstandard?

**Comment by davidfowl** [comment]
Also:

> The owner has unlisted this package. This could mean that the package is deprecated or shouldn't be used anymore.

Why would we use this?

**Comment by livarcocc** [comment]
There is a different effort going on around this. Closing this one.
