### ISSUE TITLE
Question: AppContext base directory for project tools is set to nuget installation directory

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#1876]
When a project tool (for example dotnet-tool-name) is launched, `AppContext.BaseDirectory` will is the location of dotnet-tool-name.dll. In most cases, this will be the nuget package install directory. (On my machine, this is means`AppContext.BaseDirectory == %USERPROFILE%\.nuget\packages\dotnet-tool-name\version\lib\dnxcore50`)

**Question:** was this intentional design? If not, what should basedir be? And is it possible to make basedir settable by the tool or user?

Because AppContext.BaseDirectory is not settable. If the project tool needs to invoke anything that relies on AppContext.BaseDirectory, the location will be nuget folder, not the project the tool is operating on.

**Example issue**:
https://github.com/aspnet/EntityFramework/issues/4765. When dotnet-ef connects to a SQLite database, Microsoft.Data.Sqlite uses AppContext.BaseDirectory to locate the file. This means it will search `%USERPROFILE%\.nuget\packages\dotnet-tool-name\version\lib\dnxcore50` when it should have used `${projectContext}\bin\Debug\dnxcore50\win7-x64` to open the database file. 

Fortunately, we (the EF team) own dotnet-ef's dependencies and can [alter the way SQLite finds the base directory](https://github.com/aspnet/Microsoft.Data.Sqlite/pull/238). But what about developers cannot change their dependencies?

**Comment by davidfowl** [comment]
The best bet here is to use the working directory instead of the app base to find the project being invoked on. The ApplicationBase might be being used by the tool itself to find configuration files relative to it and other things like this (resource assemblies etc).

**Comment by natemcmaster** [comment]
Thanks for clarifying. We worked around this by using `ProjectContext.GetOutputPaths()` and setting an environment variable. https://github.com/aspnet/EntityFramework/pull/4873. Closing now.
