### ISSUE TITLE
Duplicate errors when a parse error occurs in project.json

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/cli#1881]
![image](https://cloud.githubusercontent.com/assets/1414993/13795067/5b7a2044-eabc-11e5-9d58-c85034515c6a.png)

I have a broken project.json and I ran build and my error list looked like the above picture. I expected a single error to show up.

/cc @davidfowl

**Comment by troydai** [comment]
One is from DTH and the other comes from VS's json schema checker.

**Comment by mlorbetske** [comment]
@troydai neither of those messages come from VS's schema checker which is part of the JSON editor (the one that does is the highlighted line in the screenshot below). One comes in on file save (or project open as the case may be) and one happens on build, the errors show up without ever opening the JSON editor.

![image](https://cloud.githubusercontent.com/assets/1414993/13865368/e6ccce56-ec67-11e5-9f6e-7eb5d253e6a4.png)

Error list when opening a project with a project.json with a parse error in it (JSON editor never opened)
![image](https://cloud.githubusercontent.com/assets/1414993/13865398/3c5e50a6-ec68-11e5-9c07-88f29fb99d6d.png)

Error list after building a project with a project.json with a parse error in it (JSON editor never opened)
![image](https://cloud.githubusercontent.com/assets/1414993/13865405/5376fdec-ec68-11e5-9584-396263c71652.png)

**Comment by troydai** [comment]
I see. I was wrong. The error is returned from project model server for invalid JSON. It seems to me that the errors are accumulated in build tasks. I need to validate who's accumulate the errors CLI or VS. (@BillHiebert any thoughts? What additional action VS take for build?)

The second error probably comes from `dotnet build` command execution:
```
D:\dev\repo\np [1.0.0.001840]
$ dotnet build
Unexpected token '}'. Expected '{', '[', true, false, null, JSON string, JSON number, or the end of the file.
```

**Comment by troydai** [comment]
I'll assign this to myself although I believe it is a tooling bug. I'll sync up with @BillHiebert

**Comment by troydai** [comment]
@BillHiebert is tracking this issue in TFS.
