### ISSUE TITLE
Need a way to obtain the current runtime id from the CLI

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#1882]
We need a way of asking the .NET CLI what is the runtime id for the current computer. It looks like it may be possible to do this by scrapping the output of 'dotnet.exe --version'. As long as we don't care about localizing 'runtime id', and as long as restoring for 'win10-x64' will restore 'win7-x64' packages (for example) then I think we are already good.

Otherwise I would propose a 'dotnet.exe --runtimeId' which will list the current runtime id that we should use for restoring.

**Comment by factormystic** [comment]
Previous discussion on this topic includes a request for just the "version" part (https://github.com/dotnet/cli/issues/1607#issuecomment-189930471) and a request for the machine rid (https://github.com/dotnet/cli/pull/1235#issuecomment-186403648).

I believe the most elegant & scaleable solution to all of these scenarios (and more that people might invent in the future) is to enhance `--version` with more args. In this case, `--version rid`.

**Comment by blackdwarf** [comment]
@factormystic the solution with overloading `--version` seems wrong. I'm gonna say it again. Ideally, we should have a short version string that contains the needed data and that is much easier to parse out. 

@gregg-miskelly I don't know of a case where we would localize rids. They are machine-consumable strings AFAIK. Also, is this something that CLI needs to support or is there a configuration/data somewhere that you could read?

**Comment by gregg-miskelly** [comment]
@blackdwarf - not localize the rid itself, but rather localize the string "Runtime Id:", so we can do the equivalent to:

` dotnet --version | grep "Runtime Id:" | head -1`

To find the current rid.

**Comment by blackdwarf** [comment]
@gregg-miskelly that's a different matter. Yeah, for that, we may need to do it, but for now it is safe.

Again, I guess all of this would be solved with a short version string that would be something like `dotnet-cli;1.0.0.001598;win7-x64` (off the top of my head) that has well-known positions for stuff.

**Comment by gregg-miskelly** [comment]
Sure. That works too, as long as we can fix it before RTM. It looks like I will need to take a dependency on this, so lets not change it after RTM :)

**Comment by blackdwarf** [comment]
@gregg-miskelly what about having a data file that would contain this info or something similar in a well-known location? Would that work? Just exploring options here.

**Comment by gregg-miskelly** [comment]
Sure. Also, all we are going to do with the runtime id is pass it to dotnet restore/publish. So if these commands took a '--runtime current' (or whatever) that would also work.

**Comment by eerhardt** [comment]
Closing with #2035 

@gregg-miskelly - there are 2 breaking changes here you will need to react to.

1. Instead of `--version` you will need to call `--info`
2. Instead of searching for `Runtime Id:`, parse it for `RID:`

This will be the stable way of getting the runtime id going forward.  (Even when we localize, we won't localize "RID" in the output.)
