### ISSUE TITLE
Support compilationOptions per runtime

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#1888]
There are a few scenarios with cross-platform code that a runtime OS switch isn't enough. When changing the name of the library to a `DllImport` statement, or when changing the type given to `MarshalAs`, the switch *must* be done at compile-time, as enforced by C# (please tell me if I'm wrong, that would be delightful).

Our two big use cases are: 1) a reimplementation of a Windows shared library with a new one on Linux, that does not / cannot share the same name, but shares the same interfaces, thus the string given to `DllImport` must change; and 2) marshaling strings as `LPStr` is *much* easier than as `LPWStr` when reverse P/Invoking, and changing the `UnmanagedType` again must be done at compile time.

To enable this, we use a compile time constant, `LINUX` that must be defined for `netstandard1.5` builds on Linux, but not on Windows, so adding a `"compilationOptions": { "define": "LINUX" }` to `frameworks` is a no-go.

We think it would be reasonable to support adding this like so: `"runtimes": { "ubuntu.14.04-x64": { "compilationOptions": { "define": "LINUX" } } }`. However, the `runtimes` section only exists in the top-level project, the `netstandardapp1.5` with `"emitEntryPoint": true`, and our libraries need it defined as well. If the dependent projects could support a runtimes section for the sole reason of having a `compilationOptions` object, that would work.

Regardless, we need a better solution than adding:

```json
    "configurations": {
         "Linux": {
             "compilationOptions": {
                 "define": [ "LINUX" ]
             }
         }
     }
```

And building/publishing with `--configuration Linux`, as it eliminates the Debug/Release configurations (though it's a viable work around right now).

**Comment by davidfowl** [comment]
This is the same as https://github.com/dotnet/cli/issues/465 and I can tell you this isn't happening for RTM. The workaround for now is to use different `project.json` (I'm assuming this is an application not a project?)

**Comment by andschwa** [comment]
Ah I *thought* we had an issue, just couldn't find it.

Multiple project.jsons is not a work around when you have a half dozen interdependent projects that all need this.
