### ISSUE TITLE
An unhandled exception has occurred: Sequence contains no matching element

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#1897]
## Steps to reproduce
Build and run MusicStore attached.
[MusicStore-dev.zip](https://github.com/dotnet/cli/files/175978/MusicStore-dev.zip)

##Error
![dotnet_err](https://cloud.githubusercontent.com/assets/6814395/13813034/2e665772-ebba-11e5-8cb8-2477f8290999.png)

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001806)

Product Information:
 Version:     1.0.0-beta-001806
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by blackdwarf** [comment]
Music Store should be buildable now with the latest version of the Music Store code and the build tools. Will close this, if you encounter any issues please reopen.
