### ISSUE TITLE
Absence of shared runtime is not reported correcly

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#1904]
## Steps to reproduce
Run portable app targeting one version of runtime with dotnet that doesn't have it.

## Expected  behavior
Meaningful error message like "Runtime version 1.0.1132213 not found"

## Actual behavior
```
Could not load host policy library []
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001806)

Product Information:
 Version:     1.0.0-beta-001806
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by schellap** [comment]
This should be fixed now to report a better error message.
