### ISSUE TITLE
Chain in VC++ 2015 REDIST 

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#1907]
SharedFramework REDIST installer, on windows, should chain in VC++ 2015 REDIST installation as well.

CC @blackdwarf @piotrpMSFT @mellinoe @joshfree

**Comment by ellismg** [comment]
@robmen Can you confirm my understanding that the right way to do this is via the bundle (through the use of `<ExePackage>`?)

**Comment by gkhanna79** [comment]
Needs to happen for both x86 and x64 installers.

**Comment by robmen** [comment]
@ellismg yep. ExePackage with a `DetectCondition` and `InstallCondition` should be enough. I'd mark it permanent since removing the VC Redist generally isn't something an app should do.

**Comment by Petermarcu** [comment]
@ellismg , I just emailed you a sample of how another product does it.

**Comment by ellismg** [comment]
Fixed with #1939
