### ISSUE TITLE
Corehost doesn't mux properly on Unix

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1908]
## Steps to reproduce
1. Be on a Mac (maybe Linux too?)
2. Download and unpack the latest package from here: https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-combined-framework-sdk-host-osx-x64.latest.tar.gz
 1. `curl -O https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-combined-framework-sdk-host-osx-x64.latest.tar.gz`
 2. `tar -xf dotnet-combined-framework-sdk-host-osx-x64.latest.tar.gz`
3. Run `./dotnet --help` from that directory

## Expected  behavior
To see the `dotnet` CLI help

## Actual behavior
No output.

With `COREHOST_TRACE` on:

```
› COREHOST_TRACE=1 ./dotnet --help
Tracing enabled
--- Invoked host main = {
./dotnet
--help
}
Exists /Users/anurse/Scratch/dotnet.dll
Checking if CoreCLR path exists=[/Users/anurse/Scratch/libcoreclr.dylib]
Host operating in Muxer mode
Considering fxr dir=[/Users/anurse/Scratch/dotnethost/fxr]...
Considering fxr dir=[/Users/anurse/Scratch/dotnethost/fxr]...
Resolved fxr [/Users/anurse/Scratch/libhostfxr.dylib]...
Tracing enabled
Found cli sdk in:
```

/cc @schellap

**Comment by schellap** [comment]
Looking...

**Comment by anurse** [comment]
FYI, same result on CentOS (there isn't a Ubuntu build out yet). For that, you'd use `curl -O https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-combined-framework-sdk-host-centos-x64.latest.tar.gz` and `tar -xf dotnet-combined-framework-sdk-host-centos-x64.latest.tar.gz`

**Comment by anurse** [comment]
Confirmed that Windows does not exhibit this behavior (and in fact, works just fine :smile: )

**Comment by schellap** [comment]
As per spec, the shared folder should be `Shared` case sensitive :)

**Comment by schellap** [comment]
The error code gives 0x97. May be a better print message is needed.

**Comment by schellap** [comment]
That is not the actual problem but one of the potential problems.

**Comment by anurse** [comment]
That looks really strange on a Unix system. Why was `Shared` chosen rather than `shared`?

**Comment by schellap** [comment]
In any case, the bug is in the usage of `readdir` as it only lists files in unix.

**Comment by schellap** [comment]
Should we just use `shared` on all platforms? @gkhanna79

**Comment by anurse** [comment]
Ok, sounds good. The CLI packaging uses `shared` right now. I think it'd be best to do that for consistency. If you fix the underlying issue I can work around the casing for now though.
