### ISSUE TITLE
No code file => 0 bytes nupkg

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1914]
create a folder with the following `project.json` file in it:

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
    },

    "frameworks": {
        "net451": { 
            "frameworkAssemblies": {
                "System.Runtime": { "type": "build" },
                "System.Security": { "type": "build" },
                "System.Xml": { "type": "build" }
            }
        }
    }
}
```

Run `dotnet restore` and then `dotnet pack` on it. 

Result: a 0 bytes nupkg

If you add a code file without an entry point it will complain but without any code file it seems that there's no error.

**Comment by piotrpMSFT** [comment]
If this is still an issue in preview3 please re-open in /nuget/home.
