### ISSUE TITLE
FrameworkAssemblies are transitive for project dependencies but not for packages 

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1916]
Get this repro code: https://github.com/victorhu-msft/deps-leak
1. In the root run `dotnet restore`
2. Go to `src\ref.xxx` and run `dotnet build` => success
3. Notice that the `project.json` file references `proj.xxx`
4. Go to `src\proj.xxx` and run `dotnet pack` => success
5. Notice that the `project.json` file has some build-time framework assembly references
6. Copy the nupkg produced by the build and delete this project
7. Go back to `src\ref.xxx` and restore => fail (expected because `proj.xxx` is missing)
8. Restore by including the folder where the nupkg from step 6 is (`dotnet restore -f <folder>`)
9. `dotnet build` => fail (unexpected)

Error: `leak\src\ref.xxx\Program.cs(2,36): error CS0234: The type or namespace name 'Xml' does not exist in the namespace 'System.Security.Cryptography' (are you missing an assembly reference?)`

It seems that the framework assemblies that were transitively included from the project reference are not included through a package reference.

I'm not sure if the behavior should be that you always have to add framework assemblies or they should be brought transitively but the behavior should be consistent and not get different results when building with projects or packages.

cc @anurse @davidfowl @pakrym

**Comment by piotrpMSFT** [comment]
We don't have any planned future releases of project.json CLI, so closing this issue.
