### ISSUE TITLE
Publish fails with unclear error if LockFileReader fails

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#1917]
## Steps to reproduce

Manually change the lock file so LockFileReader fails (e.g. replace a string value with an int)
## Expected  behavior

Publish should fail with a clear error like: `"Failed to read lock file <file path>. Try to restore the project."`
## Actual behavior

Publish fails with: `'C:\...\project' cannot be published for '<no framework provided>' '<no runtime provided>'`

This is because exceptions are swallowed and a dummy LockFile is created: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Graph/LockFileReader.cs#L54 
## Environment data

`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001817)

Product Information:
 Version:     1.0.0-beta-001817
 Commit Sha:  dfe985fa4c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by piotrpMSFT** [comment]
Moved to SDK repo.
