### ISSUE TITLE
Cannot Build A Linux Targeted App on Windows

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#1924]
## Steps to reproduce
1. dotnet new
2. Edit the project.json file to include a Linux RID (e.g. ubuntu.14.04-x64)
3. dotnet restore
4. dotnet build -r ubuntu.14.04-x64
5. Navigate to the bin\Debug\dnxcore50\Ubuntu.14.04-x64 directory.
## Expected  behavior

Expect to see Linux specific files (e.g. libhostpolicy.so and an ELF executable for the app).
## Actual behavior

Only Windows specific files are created, and thus the app doesn't actually run on Linux.
## Environment data

`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001803)

Product Information:
 Version:     1.0.0-beta-001803
 Commit Sha:  711e9a8e53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by brianrob** [comment]
@piotrpMSFT, can you confirm that this workflow is expected to work?

**Comment by blackdwarf** [comment]
@brianrob does this still repro with the newest version of the tooling (Preview 2)?

**Comment by piotrpMSFT** [comment]
I just tried this with preview3 and it worked just fine :)
