### ISSUE TITLE
dotnet.exe should consider an empty argument set as an SDK invocation

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1925]
When the `dotnet` muxer is executed with no arguments, it should consider that an SDK invocation and mux to the SDK as appropriate (same as it would with `dotnet --help`, etc.). That way, typing `dotnet` on the command line will give the help text from the SDK (which can include help for the muxer itself).

Currently, typing `dotnet` produces no output at all, which is definitely not a good user story :)

/cc @schellap @piotrpMSFT

**Comment by mellinoe** [comment]
:+1:

**Comment by anurse** [comment]
> :+1:

Psh, clearly **someone** didn't read about the new [reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) ;P

**Comment by schellap** [comment]
> > :+1:

> Psh, clearly **someone** didn't read about the new [reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) ;P

Psh, clearly **someone** didn't read about the new [reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) ;P

**Comment by schellap** [comment]
We have more activation models than just CLI, we print an useful message now. So closing...
