### ISSUE TITLE
dotnet restore fails with bogus missing config file error on some computers

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#1928]
Moving issue from https://github.com/OmniSharp/omnisharp-vscode/issues/96

## Steps to reproduce
1. Install VS Code on a Ubuntu
2. Try to restore the CLR debugger in the same way that VS Code will --

    cd ~/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug
    dotnet --verbose restore --configfile NuGet.config

## Expected  behavior
Restore succeeds

## Actual behavior
On some machine, restore fails with --

    ~/.vscode/extensions/ms-vscode.csharp-0.3.7/coreclr-debug$ dotnet --verbose restore --configfile NuGet.config
    error: File '/home/dhanajay/.vscode/extensions/ms-vscode.csharp-0.3.7/NuGet.config' does not exist.

**NOTES**:

1. The error message at least indicates that dotnet restore is looking in the wrong directory (the current directory is ...\coreclr-debug)
2. We had someone internal run into this on OSX. That time it turned out to be due to junk left over from an older version. But @dhnnjy tried uninstalling/reinstalling with no success.

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001675)

Product Information:
 Version: 1.0.0-beta-001675
 Commit Sha: N/A

Runtime Environment:
 OS Name: ubuntu
 OS Version: 14.04
 OS Platform: Linux
 Runtime Id: ubuntu.14.04-x64

**Comment by shealey** [comment]
I'm also experiencing the same problem on the same operating system following a fresh install of the latest version of the coreclr.

I'm unable to build any auto generated dot net core projects in Visual Studio Code because of it.

**Comment by mightea** [comment]
I have a similar issue on OS X 10.11.4. I reinstalled VS Code (deleted the app and the ~/.vscode folder). The issue persists.

### Actual Behavior
```
Downloading and configuring the .NET Core Debugger...
Running /usr/local/share/dotnet/bin/corerun "/usr/local/share/dotnet/bin/NuGet.CommandLine.XPlat.dll" "restore" "--configfile" "NuGet.config" "--runtime" "osx.10.11-x64"
Process ID: 6489
Specify --help for a list of available options and commands.
error: Unrecognized option '--configfile'
dotnet exited with error code 1
Error while installing .NET Core Debugger.
```
### Environment Data
```
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

**Comment by ytimenkov** [comment]
I observed similar issue on WIndows with CoreCLR when I had custom package sources in machine-wide nuget.config. (They are https and have packageSourceCredentials entries).

    dotnet restore
    Exception has been thrown by the target of an invocation.

However `dnu restore` gives more details about the problem:

    dnu restore
    Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16609

    ----------
    System.NotImplementedException: The method or operation is not implemented.
       at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[]     optionalEntropy, DataProtectionScope scope)
       at NuGet.EncryptionUtility.DecryptString(String encryptedString)
       at NuGet.PackageSourceProvider.ReadCredential(String sourceName)
       at NuGet.PackageSourceProvider.<>c__DisplayClass13_0.<LoadPackageSources>b__1(SettingValue p)
       at System.Linq.Enumerable.SelectListIterator`2.ToList()
       at NuGet.PackageSourceProvider.LoadPackageSources()
       at Microsoft.Dnx.Tooling.PackageSourceUtils.GetEffectivePackageSources(IPackageSourceProvider sourceProvider, IEnumerable`1 sources, IEnumerable`1 fallbackSources)
       at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
    ----------
    Restore failed
    The method or operation is not implemented.

If I remove sources which require https authentication restore works.

## Environment Data
    dotnet --version
    .NET Command Line Tools (1.0.0-beta-001598)

    Product Information:
     Version:     1.0.0-beta-001598
     Commit Sha:  7582649f88

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14295
     OS Platform: Windows
     Runtime Id:  win10-x64

**Comment by erdeszt** [comment]
I'm having the same issue on Win8. `dotnet --version`:
```
$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 Runtime Id:  win81-x64
```
Removing the https nuget sources as @ytimenkov suggested solves the issue(although I don't get the nice detailed error with `dnu restore` as he did).

**Comment by toptensoftware** [comment]
Having a similar issue, but no reported errors:

```
Brads-MacBook-Pro:ms-vscode.csharp-1.0.3-rc2 brad$ dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
Brads-MacBook-Pro:ms-vscode.csharp-1.0.3-rc2 brad$ dotnet --verbose restore --configfile NuGet.config
Brads-MacBook-Pro:ms-vscode.csharp-1.0.3-rc2 brad$ 

```

When I run VSCode, "Error while installing .NET Core Debugger", clicking View Log shows empty Extensions Output panel.

**Comment by gregg-miskelly** [comment]
@toptensoftware the 1.x-rc2 builds of the extension are meant for more recent builds of .NET CLI than the 1598 build. If you want to move to newer builds of the CLI -- http://aka.ms/vscclrdogfood.

Otherwise I would suggest sticking with the version of the extension from the gallery.

**Comment by toptensoftware** [comment]
@gregg-miskelly Thanks Gregg.  Tried that and the debugger installed, but now I can't run even a basic `dotnet new` `dotnet restore`.  

Logged it here: https://github.com/dotnet/cli/issues/2611

**Comment by blackdwarf** [comment]
@gregg-miskelly is this still an issue? If so, I believe it should be moved to NuGet/Home.

**Comment by gregg-miskelly** [comment]
@blackdwarf I never had this as an issue myself - it was reported by user's of the VS Code C# extension. We haven't had any recent users run into this.

**Comment by blackdwarf** [comment]
Thanks @gregg-miskelly I will close this down then. We can reopen on NuGet/Home if it surfaces again.
