### ISSUE TITLE
Corehost should give a better error message when the dll path is too long

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1933]
## Steps to reproduce
Just invoke corehost.exe passing to it a dll whose path is bigger than 255 characters.

## Expected  behavior
We get an error saying that path is too long or something like that.

## Actual behavior
The error message says that coreclr could not be found.

**Comment by ellismg** [comment]
Is there a plan to support long paths?

**Comment by schellap** [comment]
The host isn't built that way as of now, we would be adding support to long path during ask mode. Cc @gkhanna79

**Comment by schellap** [comment]
Also see #1695

**Comment by gkhanna79** [comment]
Closing as dup of https://github.com/dotnet/cli/issues/1933
