### ISSUE TITLE
corehost does not return an error code in unix when it fails to find coreclr

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1935]
Use this branch: https://github.com/livarcocc/cli-1/tree/more_test_params
## Steps to reproduce

Change the test It_returns_a_failure_when_it_fails_to_run_the_tests at GivenThatWeWantToRunTestsInTheConsole. Change the WindowsFactOnly to Fact and run the test.
## Expected  behavior

The test should pass because the command result should indicate a failure.
## Actual behavior

It does not fail, even though the execution of the test command did fail.

**Comment by schellap** [comment]
This is on ubuntu?

**Comment by anurse** [comment]
Also, it looks like on Windows, a missing deps file is causing a crash:

```
> corehost.exe C:\Users\anurse\.nuget\packages\dotnet-test-xunit\1.0.0-dev-91790-12\lib\netstandardapp1.5\dotnet-test-xunit.dll --depsfile C:\does\not\exist.deps.json


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

![image](https://cloud.githubusercontent.com/assets/7574/13970921/486e1d60-f049-11e5-9596-f45fd457f85d.png)

**Comment by schellap** [comment]
Moving to RTM.

**Comment by blackdwarf** [comment]
@schellap what is the status of this?

**Comment by piotrpMSFT** [comment]
If this is still an issue, it should be tracked in core-setup.
