### ISSUE TITLE
Dotnet Run PortableAppWithNative Test Project Fails

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1940]
## Steps to reproduce
from cli repo root
dotnet run test/TestAssets/TestProjects/PortableTests/PortableAppWithNative

## Expected  behavior
runs successfully

## Actual behavior
fails

```
Did not find fallback rids for package Microsoft.AspNetCore.Server.Kestrel/1.0.0-rc2-20113 for the host rid osx.10.11-x64
Invalid .deps file
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001858)

Product Information:
 Version:     1.0.0-beta-001858
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

Putting this issue in place to track test skip.

**Comment by schellap** [comment]
@brthor, could you help me understand if this is blocked on the host packaging work?

**Comment by piotrpMSFT** [comment]
Moving this test-only fix to preview3.

**Comment by livarcocc** [comment]
This works now.
