### ISSUE TITLE
Should `dotnet compile` be a builtin command?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/cli#1944]
It seems a bit strange that `compile-csc`, `compile-fsc`, and `compile-native` are builtins, but plain old `compile` is not. I'm running into a problem with this on my machine, where I'm getting an error about `dotnet-compile` not being found. Should we make the latter a builtin as well?

**Comment by mmalolepszy** [comment]
@jamesqo According to #1574 compile was removed intentionally.

**Comment by jamesqo** [comment]
Ah, that makes more sense then. I was wondering why there was both a build and compile command.
