### ISSUE TITLE
Dotnet run not working on OSX

### ISSUE THREAD

**Issue by glennblock** [dotnet/cli#1948]
## Steps to reproduce
- Installed dotnet cli version: 1.0.0-beta-001844
- `dotnet build` on an ASP.NET 5.0 app.
- `dotnet run` 
## Expected  behavior

App builds and launches successfully.
## Actual behavior

App builds but gives the following error when launching.`Could not resolve coreclr path`
## Environment data

`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001844)

Product Information:
 Version:     1.0.0-beta-001844
 Commit Sha:  e847c449bf

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 Runtime Id:  osx.10.10-x64

**Comment by miguellira** [comment]
What does your `dnvm list` output look like? Have you tried upgrading to the latest DNX? `dnvm upgrade -u -r corelcr`

**Comment by glennblock** [comment]
```
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
  *    1.0.0-rc1-update1    coreclr x64          darwin          default
       1.0.0-rc1-update1    mono                 linux/osx
```

**Comment by glennblock** [comment]
Trying now

**Comment by miguellira** [comment]
I'm assuming your ASP.NET app is currently targeting RC1 bits, not ASP.NET Core - correct? If so, you should just stick with DNX/DNU commands until RC2 goes live.

**Comment by miguellira** [comment]
BTW, if you run the upgrade command, remember to switch back to RC1 if your ASP.NET targets that framework.

`dnvm use 1.0.0-rc1-update1 -p`

**Comment by glennblock** [comment]
The app targets RC1 yeah.

**Comment by glennblock** [comment]
In either case, trying the newer version didn't make the error go away when I ran "dotnet".

**Comment by glennblock** [comment]
Thank you for the responsiveness @miguellira!

**Comment by miguellira** [comment]
Yeah, I'm following your thread on Twitter.

I would stick with DNX/DNU for your demo and wait for RC2 to go out then move that app to ASP.NET Core. dotnet-cli should be a lot more stable by then.

Curious though, where is your dotnet currently installed `which dotnet`?

I'm currently on `1.0.0-beta-001842` which is an earlier build than yours and I'm able to build *most* RC2 beta projects.

**Comment by glennblock** [comment]
Thanks for the advice. I'll wait. I can still show it and show what it will enable.

It is installed here:  `/usr/local/share/dotnet/bin/dotnet`

I installed it downloading the OSX pkg from the `readme.md`

**Comment by david-driscoll** [comment]
looks like the actual tarball for osx is wrong, when compared to linux/mac layouts.  Specific `bin` folder is missing.

![image](https://cloud.githubusercontent.com/assets/1269157/13885106/512c6e38-ed07-11e5-8ffb-e95f475b1ecb.png)

**Comment by brthor** [comment]
@david-driscoll 
Had some large changes to the layout of tarballs last week, the absence of a bin folder is expected, the cli now lives in `sdk`

**Comment by blackdwarf** [comment]
@glennblock is this still reproing?
