### ISSUE TITLE
Possible race condition in finding open port for dotnet test?

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/cli#1949]
Looking at the way dotnet-test works, it expects a port that it will start listening on, and the IDE will connect to and pass in commands. This means the IDE needs to find an open port, with code like:

```csharp
TcpListener tcpListener = new TcpListener(IPAddress.Loopback, 0);
tcpListener.Start();
int port = ((IPEndPoint) tcpListener.LocalEndpoint).Port;
tcpListener.Stop();
return port;
```

Is there a chance of a race condition here, that the port that the IDE gets is then reused by another app running similar code, before `dotnet test` gets chance to open the port itself? While I think it would be highly unlikely, would it be better to invert the responsibilities, and have the IDE control the port, listening all the time, and the child process connects to the IDE, rather than the IDE connecting to the child process?

**Comment by livarcocc** [comment]
We have made that change a while ago.
