### ISSUE TITLE
Error when executing dotnet run in a folder with a "." on OSX

### ISSUE THREAD

**Issue by miguellira** [dotnet/cli#1950]
If you rename the `HelloMvc` sample application (https://github.com/aspnet/cli-samples) to `HelloMvc.Web` dotnet run does not properly execute the app.

## Steps to reproduce
```
git clone https://github.com/aspnet/cli-samples.git
cd cli-samples/
mv HelloMvc HelloMvc.Web
cd HelloMvc.Web
dotnet restore
dotnet build
dotnet run
```
## Expected  behavior
App builds and launches successfully.
## Actual behavior

App builds but gives the following error when launching:
```
Miguels-MBP:HelloMvc.Web miguellira$ dotnet run
Project HelloMvc.Web (.NETStandardApp,Version=v1.3) was previously compiled. Skipping compilation.
Usage: dotnet [--help | app.dll]
```
## Environment data
dotnet --version output:
```
.NET Command Line Tools (1.0.0-beta-001842)

Product Information:
 Version:     1.0.0-beta-001842
 Commit Sha:  778e63a5a6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```
dnx --version output:
```
Microsoft .NET Execution environment
 Version:      1.0.0-rc2-16595
 Type:         CoreClr
 Architecture: x64
 OS Name:      Mac OS X
 OS Version:   10.11
 Runtime Id:   osx.10.11-x64
```

**Comment by anurse** [comment]
/cc @schellap @brthor @Sridhar-MS @piotrpMSFT 

It looks like when `dotnet run` is invoking the host, it's doing something wrong:

> `Usage: dotnet [--help | app.dll]`

**Comment by blackdwarf** [comment]
I cannot repro this on Preview 2 (1.0.0-preview2-003121) tooling. Will close. If this still reproes, please reopen.
