### ISSUE TITLE
Dotnet build refuses to rebuild if switches change

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/cli#1956]
## Steps to reproduce

```
dotnet new
dotnet restore
dotnet build --native
dotnet build --native --cpp
```
## Expected  behavior

The latest binaries will be produced by CppCodegen backend of .NET Native.
## Actual behavior

Nothing gets compiled by the second `dotnet build`.

```
Project dotnet (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
```

The CLI should remember the compiler switches that were used to produce output and if they change, the project should not be considered up to date. (E.g. `--cppcompilerflags` could have changed as well).

**Comment by piotrpMSFT** [comment]
Just verified this does not repro in preview3
