### ISSUE TITLE
Restore fails with NotFound since a few days

### ISSUE THREAD

**Issue by cpx** [dotnet/cli#1957]
On a fresh installation, run:
dotnet new
dotnet restore

This fails with a "NotFound" error from nuget.org. As a workaround running restore with "-s  https://myget.org/f/dotnet-core" does find the packages, as suggested in other GH issues. If this is how it's supposed to be though, that should be stated in the docs.

Note that this was working fine just a few days ago. It was only today that I found it was broken, when I ran restore in a fresh environment where I didn't have the packages cached.

**Comment by blackdwarf** [comment]
This is covered in the [known issues guide](https://github.com/dotnet/core/blob/master/cli/known-issues.md#on-dev-builds-of-the-tools-restoring-default-project-from-dotnet-new-fails) now.
