### ISSUE TITLE
Version badges on dotnet/cli page are wrong

### ISSUE THREAD

**Issue by kwaclaw** [dotnet/cli#1961]
## Steps to reproduce
Open https://github.com/dotnet/cli page at branch rel/1..0.0.
Download Windows x64 installer.

## Expected  behavior
Downloaded package version matches version badge.

## Actual behavior
As of right now: version badge shows 1.0.0.001887
Downloaded version: 1.0.0.1840

**Comment by Sridhar-MS** [comment]
I updated the readme.md links. Can you try the latest links?

**Comment by abpiskunov** [comment]
it is still 1840

**Comment by Sridhar-MS** [comment]
Did you try https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe? Thats what is there on the readme.md file.

And I get this
```
C:\Users\sridhper>dotnet --version
.NET Command Line Tools (1.0.0-beta-001888)

Product Information:
 Version:     1.0.0-beta-001888
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by kwaclaw** [comment]
Just tried. Version badge ending in 1897, commit count is 1897, downloaded file at version 1897.
Still one inconsistency: The windows builds are in "failed" status (have been for a quite few days).

**Comment by Sridhar-MS** [comment]
We have been switching over to a different build definition internally. I am fixing it now.

**Comment by enricosada** [comment]
@Sridhar-MS i can repro too

- badge version: 1977
- downloaded version:  1937

**Comment by Sridhar-MS** [comment]
@enricosada We are facing very slow upload speeds to azure blob. This is causing the links to be out of date. I am looking into it.

**Comment by blackdwarf** [comment]
I think the badges are working fine now. If you see any more problems with them, please update this issue and reopen.
