### ISSUE TITLE
Error messages should be more prescriptive

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/cli#1962]
I know these things are documented, but nobody wants to read the documentation. The `git` command line tools do a pretty good job at explaining what the user should do to fix a problem - I think `dotnet` should take lessons from it:
### Project dotnet does not have a lock file

```
D:\dotnet>dotnet new
Created new C# project in D:\dotnet.

D:\dotnet>dotnet run
Project dotnet does not have a lock file.
Project dotnet does not have a lock file.
```

_Hey dummy, you need to run `dotnet restore`!_ (Also, I'm not sure why are we printing this twice.)
### fatal error LNK1104: cannot open file 'kernel32.lib'

```
D:\dotnet>dotnet build --native
Compiling dotnet for .NETStandard,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.2017591
Input Assembly: D:\dotnet\bin\Debug\netstandard1.5\dotnet.dll
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
Linking of intermediate files failed.
```

_Hey dummy, run this from the Visual Studio x64 Native tools command prompt!_

**Comment by livarcocc** [comment]
We now show an error saying that restore is needed. However, this message needs some improvements. That part of the work is currently being tracked here: https://github.com/dotnet/sdk/issues/540.
