### ISSUE TITLE
Console app with cmd line args

### ISSUE THREAD

**Issue by mattwarren** [dotnet/cli#1965]
What is the guidance for an application that wants to have it's own command line arguments? It seems that `dotnet run ...` will not allow any arguments that are prefixed with `--`, even if they should be passed through to the application that `dotnet` it is running/hosting (i.e. they are not argument for `dotnet` itself, such as `--framework` or `--help`)

## Steps to reproduce

``` csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
			Console.WriteLine($"There are {args.Length} args\n\t{String.Join("\n\t", args)}");
			foreach (var arg in args)
			{
				if (arg == "--someArg")
					Console.WriteLine("Processing --someArg...");
			}            
        }
    }
}
```

and the following `project.json`:

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "frameworks": {
		"dnx451": {}
    }
}
```

## Expected  behavior

If I run the cmd line `dotnet run --framework Dnx451 --someArg`, I would expect the following to be printed:

```
There are 1 args
        --someArg
Processing --someArg...
```

## Actual behavior

Instead this is printed:

```
C:\Users\blah\Desktop\dotnet issue>dotnet run --framework Dnx451 --someArg
invalid option --someArg
usage:  [-f <arg>] [-c <arg>] [-p <arg>] [-h] [--] <args>...

    -f, --framework <arg>        Compile a specific framework
    -c, --configuration <arg>    Configuration under which to build
    -p, --project <arg>          The path to the project to run
                                 (defaults to the current directory).
                                 Can be a path to a project.json or a
                                 project directory
    -h, --help                   Help for compile native.
    <args>...                    Arguments to pass to the executable or
                                 script
```

Note that `dotnet run --framework Dnx451 someArg` works, i.e. **without** the `--` prefix. Is this the only way that command line applications can accept arguments when running with `dotnet`?

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64
```

## Comparision with dnx

FWIW `dnx` lets you do this, i.e. if you run `dnx run --framework Dnx451 --someArg`, you get:

```
There are 3 args
        --framework
        Dnx451
        --someArg
Processing --someArg...
```

However the problem here is that it passes through all the args, even the ones that were meant for `dnx run` itself. So `dotnet` is better in this regards as it strips the args out and doens't make them available to the program that it is hosting.

**Comment by akoeplinger** [comment]
Seems like a duplicate of https://github.com/dotnet/cli/issues/1385.

**Comment by mmalolepszy** [comment]
@mattwarren There is a workaround allowing you to pass `--` prefixed arguments into your app:
```
dotnet run --framework Dnx451 -- --someArg
```

**Comment by mattwarren** [comment]
@akoeplinger sigh I completely missed #1385, yeah this is a dupe, I'll close it.

**Comment by hbb0b0** [comment]
it  solve my proplems.
thanks .
