### ISSUE TITLE
The latest .NET CLI bits crash on Windows 7

### ISSUE THREAD

**Issue by PinpointTownes** [dotnet/cli#1966]
## Steps to reproduce

Install the latest CLI bits on Windows 7 or download the latest "portable CLI" .zip and run any command.

## Expected  behavior

No error should be displayed.

## Actual behavior

![image](https://cloud.githubusercontent.com/assets/6998306/13919767/b9f30976-ef6f-11e5-8440-7733ab906d3f.png)

![image](https://cloud.githubusercontent.com/assets/6998306/13919783/ccfa4048-ef6f-11e5-9855-7a801dfc2fd7.png)

## Environment data
`dotnet --version` output: N/A.

**Comment by PinpointTownes** [comment]
Same issue with 1887:

![image](https://cloud.githubusercontent.com/assets/6998306/13929483/a101bf4a-ef9a-11e5-9366-30ac64beae57.png)

**Comment by mikes-gh** [comment]
I confirm win 7 x64

**Comment by PinpointTownes** [comment]
FWIW, I'm still seeing this bug with 1.0.0-rc2-23929.

**Comment by mikes-gh** [comment]
If I download the binary package and set the path it works for me.
It seems to be a problem with the MSI(which I install via the UAC prompt).

**Comment by PinpointTownes** [comment]
@mikes-gh looks like both the latest binaries and the installer now work fine on Windows 7. Can you confirm it also works for you?

**Comment by mikes-gh** [comment]
@PinpointTownes 
Sorry for delay been on hols.
I confirm all fixed using x64 sdk installer 
```
.NET Command Line Tools (1.0.0-rc2-002339)

Product Information:
 Version:     1.0.0-rc2-002339
 Commit Sha:  2be5e84f87

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```
