### ISSUE TITLE
Project.json configuration split into separate files

### ISSUE THREAD

**Issue by onovotny** [dotnet/cli#1967]
Right now project.json files have to be self-contained. This could get messy and also precludes the use of generated configuration values easily.

My suggestion is to have a `project.<configuration>.json` file that is sparsely populated and each provided section overrides a matching element in the parent. Thus, I could cherry-pick and replace a specific `compilationOptions` value, etc.

For rules, I'd say that objects could be cherry-picked - to reset to blank, user could use { }. Arrays and scalars would be replaced entirely, no merging.

Then the dotnet command line could apply the transform when supplied a configuration. This would enable different values for release/debug/environment/whatever.

If you wanted to get really fancy, there could be some way of nesting multiple config layers, but that's probably not necessary.

**Comment by davidfowl** [comment]
Why do you need this?

**Comment by enricosada** [comment]
With a single file it's easier to see the base values and specific configuration overrides. I like project.json it's self contained

Using multiple files add complexity, and using `project.<configuration>.json` doesnt help to share configuration options with multiple project.json in same repository.
i think global.json can help to share some options, but it's a tradeoff about make it easier to read (self-contained) and maintance (change a option in a single place).

**Comment by onovotny** [comment]
Initially I was thinking it'd be a place that covers almost every element in the project.json, going beyond what the configurations node does. It'd be a way to override/replace existing values. Based on a file naming convention, the file could also be generated and not checked in to source control.

A few scenarios come to mind:

  - programmatically setting a version number in a pre-build step. I'd really prefer not to modify the "real" project.json file in a pre-build step. Generating a build-time override file seemed cleaner. It reduces the chance of accidently committing the change on a dev machine where the build script was run.
  - I've seen requests for ways to include/exclude specific files based on configuration. This could enable this by either replacing the existing glob or adding an exclude glob in that one configuration.

There's likely other uses too but those two come to mind right now.

**Comment by piotrpMSFT** [comment]
@onovotny <Import> away :) [in preview3]
