### ISSUE TITLE
Dotnet CLI Tools Changes FYI

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1970]
Last week the changes implementing this spec: `https://github.com/brthor/cli-nuget-extensions` went in.

There are some notable changes to the way tools behave here and how they interact with the shared framework. 
- Tools are now expected to be portable apps
- Tools are expected to have a [runtimeconfig.json](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md#appnameruntimeconfigjson) packaged next to the dll, changes were made in dotnet pack to automatically pick this up for portable projects
- Tools should target netstandard1.5
- `"imports"` no longer fully supported, changes will be coming in nuget to support this at the tool consumer level cc @joelverhagen 

Opening this issue primarily to let everyone know who may be affected. Let me know if anything is unclear.

Some folks I know are working on tools, please tag anyone I might've missed.

@moozzyk `dotnet-publish-iis`
@bricelam `dotnet-ef`
@NTaylorMullen `dotnet-razor-tooling`
@prafullbhosale `dotnet-aspnet-codegenerator`

**Comment by muratg** [comment]
:eyes:

**Comment by enricosada** [comment]
i add myself with ( for notifications :smile: )

- `dotnet-fssrgen` ( working, ref https://github.com/fsprojects/FsSrGen ) 
- `dotnet-fslexyacc` ( WIP,  ref https://github.com/fsprojects/FsLexYacc )

after #1823 also `dotnet-compile-fsc`

**Comment by muratg** [comment]
@moozzyk When you look into `dotnet-publish-iis` changes, could you also take care of the other tools?

Full list is here:
```
dotnet-aspnet-codegenerator	
dotnet-ef	
dotnet-publish-iis	
dotnet-razor-tooling	
dotnet-sql-cache	
dotnet-user-secrets	
dotnet-watch
```

**Comment by moozzyk** [comment]
Yes, I will.

**Comment by enricosada** [comment]
`dotnet-test-xunit` @piotrpMSFT @livarcocc

because it's nice to see examples of tools :smile:

**Comment by bricelam** [comment]
BTW, ASP.NET will need CoreCLR build `23910` or newer for this to work.

**Comment by brthor** [comment]
`dotnet-test-xunit` is a special class of tools which merge with the package graph of the project under test. 

These types of tools (which are listed in the dependencies section rather than tools) should not need any changes.

@piotrpMSFT @livarcocc

**Comment by ciel** [comment]
So does this mean that libraries that target `dnxcore50` will no longer work with the newest toolchain?

**Comment by brthor** [comment]
@ciel This change is specific to project tools and doesn't affect libraries. 
`dnxcore50` libraries should still work with an appropriate project.json

**Comment by ciel** [comment]
I'm a bit confused, then.

I was using **RavenDB** fine up until yesterday. It targets `dnxcore50`. I had my `asp.net mvc` app targeting `netstandardapp1.5` and things ran fine.

I installed the new CLI, and updated my app to `netstandard1.5`, downloaded the newest `asp.net mvc` builds - which worked fine on that - but when I tried to add `RavenDB` back in, it balked at me and said `could not locate coreclr`. It was only when I tried to use the `imports` array.

I tested this in the app created by using `dotnet new` as well. It worked fine until I added something targeting `dnxcore50` and tried to add that to the `imports: [ "dnxcore50" ]` array.

Am I misunderstanding what this change means?

**Comment by brthor** [comment]
@ciel is RavenDB a project tool?

**Comment by ciel** [comment]
well nevermind. it must have been a bug in the specific version of the cli I was using. I tried it today with the latest build and it works.

**Comment by brthor** [comment]
@ciel  :smile: glad it's working

**Comment by ciel** [comment]
oh yes, getting completely new errors now!

**Comment by brthor** [comment]
please file issues :frowning:

**Comment by natemcmaster** [comment]
>  "Tools are now expected to be portable apps"

@brthor the project.json spec seems to be changing continually. How can we ensure our tools are compiled as portable apps, not standalone?

**Comment by brthor** [comment]
@natemcmaster There are some example projects here:
https://github.com/dotnet/cli/tree/rel/1.0.0/TestAssets/TestProjects/PortableTests

Make sure to reference `Microsoft.NETCore.App` and not to add rids to the project.

**Comment by natemcmaster** [comment]
@brthor so if I understand this correctly, somewhere CLI does this kind of check ?

```
var isPortable = (project.json.dependencies.Microsoft.NetCore.App.type == "platform") 
                  && (project.json.runtimes.length == 0)
```

Are there any other conditions?

**Comment by brthor** [comment]
cc @anurse @pakrym  made the changes to build and will have the best answer for that

**Comment by moozzyk** [comment]
@natemcmaster - see: https://github.com/aspnet/IISIntegration/compare/pawelka/tools
I gues you are asking about the 

+      "dependencies": {
+        "Microsoft.NETCore.App": {
+          "type": "platform",
+          "version": "1.0.0-rc2-23911"
+        }

bit

**Comment by natemcmaster** [comment]
@moozzyk so, TFM's also play a role? is this right?

```
var isPortable = (project.json.dependencies.Microsoft.NetCore.App.type == "platform") 
                  && (project.json.runtimes.length == 0)
                  && project.json.frameworks.length == 1
                  && project.json.frameworks[0] == "netstandard1.5"
```

**Comment by anurse** [comment]
In general, no TFM's do not matter. In the short term (while we land all the things in the right places) `netstandard` is requires for portable apps.
