### ISSUE TITLE
latest dotnet installer brings old version of dotnet

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#1973]
## Steps to reproduce

I am trying to download this installer

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-win-x64.latest.exe

and it brings me dotnet version 1840, when I know that there are much newer builds available , for example https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.001887/dotnet-dev-win-x64.1.0.0.001887.zip  

Is that broken or just changed? What that zip file means? How to get latest installer?

## Environment data
`dotnet --version` output:

**Comment by piotrpMSFT** [comment]
Where are you seeing version 1840 reported?

**Comment by abpiskunov** [comment]
programs and features.

In command line I see: 10.0.10586. Ijust checked zip that I mentioned and it has changes that I need, but current latest doe snot have them for a while (a week?)

**Comment by kwaclaw** [comment]
I think related to #1961 .

**Comment by brthor** [comment]
@abpiskunov links on the readme have been updated to reflect the new link to latest zips on Windows.

The name of the zip changed with the shared fx changes last week.

**Comment by Sridhar-MS** [comment]
The latest installer is @ https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe

Can you give that a try? I have updated the readme.md links too.

**Comment by abpiskunov** [comment]
That worked yes.
