### ISSUE TITLE
'dotnet restore --help' missing information about explicitly setting 'lock' ON

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#1976]
## Steps to reproduce
I would like to lock the lock.json file that gets generated so that I can ship my project with lock.json file and share with others and they also get the same package versions that worked for me. While I see there is an entry in lock.json saying `"locked": false`, I do not see any command line way of setting the lock to `true`.

(**Unrelated**: the usage says `nuget3` instead of `dotnet`?)
```
C:\> dotnet -v restore --help


Usage: nuget3 restore [arguments] [options]

Arguments:
  [root]  List of projects and project folders to restore. Each value can be: a path to a project.json or global.json file, or a folder to recursively search for project.json files.

Options:
  -h|--help                       Show help information
  -s|--source <source>            Specifies a NuGet package source to use during the restore.
  --packages <packagesDirectory>  Directory to install packages in.
  --disable-parallel              Disables restoring multiple projects in parallel.
  -f|--fallbacksource <FEED>      A list of packages sources to use as a fallback.
  --configfile <file>             The NuGet configuration file to use.
  --no-cache                      Do not cache packages and http requests.
  -v|--verbosity <verbosity>      The verbosity of logging to use. Allowed values: Debug, Verbose, Information, Minimal, Warning, Error.
```

## Expected  behavior
Providing command line options to lock the generated lock.json file

## Actual behavior
No options provided by the tool to lock the json file. Workaround is to manually modify the lock.json file.

## Environment data
`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  5b0afe7880

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by blackdwarf** [comment]
@kichalla I believe that this issue should be filed on NuGet/Home since we are using NuGet xplat client to work with dependencies. Will close this issue. 

/cc @harikmenon
