### ISSUE TITLE
Build downloading stage0 every time on ubuntu.

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#1979]
## Steps to reproduce
clone repo 
`./build.sh`
`./build.sh`

## Expected  behavior
Downloads stage0 only the first time

## Actual behavior

Downloads both times.

## Environment data
`dotnet --version` output:

N/A, as of commit 1887

**Comment by Sridhar-MS** [comment]
I fixed the commit issue #1971

**Comment by brthor** [comment]
Is the commit issue related?

**Comment by Sridhar-MS** [comment]
Nope.

**Comment by Sridhar-MS** [comment]
The `.version` file location has moved to `<install root>/sdk/<nugetversion>/.version` from  `<install root>/.version`. 

Relevant code
https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/install.sh#L146

cc: @krwq

**Comment by krwq** [comment]
there is no way of reliably checking versions right now since there is more than one versioned folder inside zip. I will fix it once this story is figured out

**Comment by brthor** [comment]
@krwq this should now be possible as of #2022 

http://dotnetcli.blob.core.windows.net/dotnet/beta/dnvm/latest.sharedfx.osx.x64.version

Would really speed up dev cycles with this in :smile:

**Comment by krwq** [comment]
Should be solved with https://github.com/dotnet/cli/pull/2041
