### ISSUE TITLE
'dotnet run' without 'dotnet restore' prints "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#1981]
## Steps to reproduce
1. dotnet new
2. dotnet run

## Expected  behavior
Run project or display an error message that 'dotnet restore' must be executed before 'dotnet run'.

## Actual behavior
Prints "Object reference not set to an instance of an object."

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  5b0afe7880

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 Runtime Id:  win81-x64

**Comment by coffeecup-winner** [comment]
I have the same behavior on 1.0.0-preview2-003112 (Win7 x64).

**Comment by blackdwarf** [comment]
This is fixed in the latest version(s). `dotnet run` will now print:

```console
The current project is not valid because of the following errors:
/Experiments/new/project.lock.json(1,0): error NU1009: The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.
```
