### ISSUE TITLE
Add samples to repo

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#199]
We need some simple samples in the repo that people can kick the tires with. This should be similar to: https://github.com/aspnet/Home/tree/dev/samples. This isn't the same as #192.

/cc @blackdwarf

**Comment by blackdwarf** [comment]
@richlander @piotrpMSFT could the dotnet/core repo samples work here?

**Comment by piotrpMSFT** [comment]
Whatever repo hosts the samples should also build the samples x-plat to make sure we don't regress.

**Comment by blackdwarf** [comment]
@richlander we have samples in the core repo (dotnet/core) so I will close this. If you think we should have some directly here, please reopen.
