### ISSUE TITLE
Project Model Server Error An item with the same key has already been added. Key: System.Runtime ConsoleApp1

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1993]
__@BillHiebert, please fill in the description.__

Moved from #1602 (The description is by the end of the comments)

**Comment by troydai** [comment]
@BillHiebert I'll assign this issue to you for now. Please assign it back to me when we have the details.

**Comment by PinpointTownes** [comment]
@troydai FYI, I'm seeing a similar thing when adding `"System.Runtime": { "type": "build" }` under frameworks/net451/frameworkAssemblies.

**Comment by troydai** [comment]
Thanks @pinpointTownes. You see that in VS or during command line `dotnet build` or `dotnet restore`?

**Comment by PinpointTownes** [comment]
During `dotnet build` (`dotnet restore` works fine):

![image](https://cloud.githubusercontent.com/assets/6998306/13970841/b093ff62-f08b-11e5-9d24-7c8054e2e2b0.png)

If I specify an explicit version, it works fine:

```json
"System.Runtime": {
    "type": "build",
    "version": "4.0.10.0"
}
```

**Comment by troydai** [comment]
@PinpointTownes thank you. the repo is very helpful. I'll look into this.

**Comment by PinpointTownes** [comment]
I've finally managed to find how to make both DNX and CLI happy: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/pull/224/files

DNX requires the `frameworkAssemblies` references and CLI crashes if I don't add the `System.Runtime`/`System.ComponentModel`/`System.IO` packages in the global dependencies:

```
error: System.Runtime 4.0.20 provides a compile-time reference assembly for System.Runtime on DNX,Version=v4.5.1, but there is no run-time assembly compatible with win7-x64.
error: System.Runtime 4.0.20 provides a compile-time reference assembly for System.Runtime on DNX,Version=v4.5.1, but there is no run-time assembly compatible with win7-x86.
```

**Comment by troydai** [comment]
@PinpointTownes I have a broader question here. If you only need to support _CLI_ would it make easier to right the `project.json`?

**Comment by PinpointTownes** [comment]
Assuming you want to know whether CLI works fine when removing the ugly DNX/CLI hacks, then the answer is no.

If I remove **all the workarounds**, running `dotnet restore` with the [`Mvc.Server` sample](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/tree/vNext/samples/Mvc/Mvc.Server) fails with this message:

![image](https://cloud.githubusercontent.com/assets/6998306/13971759/2831fb30-f093-11e5-951f-b2530dece990.png)

To make CLI happy, these dependencies must be added in `project.json`:

```
"System.ComponentModel": "4.0.1-*",
"System.IO": "4.1.0-*",
"System.Runtime": "4.1.0-*"
```

**Comment by troydai** [comment]
@PinpointTownes this is expected. The `System.Runtime/4.0.20` is pulled in by one of the dependencies, however it directly conflict with `Microsoft.NETCore.Platforms` since it is an old package without `RID` defined in it. When you List `System.Runtime 4.1.0-*` in the dependencies, it overrides the `4.0.20` and pulled in the new defined package (which is compatible with the tfm we're using today).

One of the solution is to reference `NETStandard.Library` ([Example](https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json#L23)). It not only pull in `Microsoft.NETCore.Platforms` but also the most used packages include `System.Runtime`. You can have it under the `netstandardapp1.5` framework.

**Comment by troydai** [comment]
Ping @BillHiebert can you provide a repo?

**Comment by PinpointTownes** [comment]
@troydai ahhhhh, fantastic. I'll give it a try ASAP, thanks! :smile:

**Comment by PinpointTownes** [comment]
@troydai I'm probably doing something wrong, but removing the explicit `System.*` references and replacing `Microsoft.NETCore.Platforms` by `NETStandard.Library` doesn't work :cry: 

Here's the CI log: https://ci.appveyor.com/project/aspnet-contrib/aspnet-security-openidconnect-server/build/1.0.0-beta5-647
And the updated project.json: https://github.com/PinpointTownes/AspNet.Security.OpenIdConnect.Server/blob/dependencies/samples/Mvc/Mvc.Client/project.json

**Comment by PinpointTownes** [comment]
Could that be related to the fact `Microsoft.AspNetCore.Mvc.Dnx` explicitly references these packages at the global level?

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Dnx/project.json#L20-L22

**Comment by troydai** [comment]
Well just base on the name `Microsoft.AspNetCore.Mvc.Dnx` I won't be surprised if it cause when the project is built with `dotnet`. Will this break your application's functionality if you drop it?

**Comment by PinpointTownes** [comment]
Well yeah, because MVC won't be able to build the Razor views or locate the controllers if I don't use this compat' package when running on DNX. And since CLI no longer works on Windows 7 (https://github.com/dotnet/cli/issues/1966), I'm pretty much stuck :smile: 

Luckily, the buggy references should be removed when the ASP.NET team migrates to the latest CLI builds, that include the NuGet fix.

**Comment by troydai** [comment]
Let's wait till ASP.NET's new packages.

Well, the issue we discussed so far has been different from the original subject :P.

@BillHiebert can you provide more details for the original issue?

**Comment by troydai** [comment]
@BillHiebert did you see this anymore?

**Comment by troydai** [comment]
Talked with @BillHiebert. We didn't see this issue for awhile.
