### ISSUE TITLE
Remove DependencyModel RuntimeLibrary hacks for xunit

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#1998]
#1932 will introduce some small hacks to DependencyModel in order to allow coreclr.xunit to run. Once that's in, fix xunit and remove the hacks

**Comment by davidfowl** [comment]
@anurse @pakrym Can we remove this now?

**Comment by anurse** [comment]
Yes, I believe so.

**Comment by blackdwarf** [comment]
@pakrym @anurse did we do this work?

**Comment by pakrym** [comment]
No, https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/RuntimeLibrary.cs#L44-L46

**Comment by piotrpMSFT** [comment]
Moved to CoreSDK repo
