### ISSUE TITLE
'dotnet commands' command

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2]
dotnet-commands should enumerate all executables on the path that match the 'dotnet-' preamble. The preamble should not be displayed in the output. So, if we have:

    dotnet-restore
    dotnet-commands
    dotnet-compile

then we should see:

    $ dotnet commands
      compile
      commands
      restore

**Comment by blackdwarf** [comment]
Closing this since #1578 s opened. We will track the work there.
