### ISSUE TITLE
What templates will ship with dotnet new 

### ISSUE THREAD

**Issue by jchannon** [dotnet/cli#2000]
When the cli tools hit RTM what are the proposed templates for dotnet new command? Will it be just a console app or MS web framework templates or will there be OSS ones too?

**Comment by blackdwarf** [comment]
@jchannon the `dotnet new` command will be different than its current incarnation. There is an issue that outlines how it will work. Basically, the templates will be separated from the implementation. If/when that happens, we aim to have multiple templates.

**Comment by jchannon** [comment]
Not just MS fwk ones? Would be nice to get some OSS templates in out of the
box. Maybe a Nancy template?

**Comment by enricosada** [comment]
@jchannon see #2052 you can install templates from url, so you can provide a nancy template and ppl can install and use it

**Comment by jchannon** [comment]
And that's great so will do that but my other point is why not ship some OSS templates out of the box or ship none and let people find them so all is equal

**Comment by enricosada** [comment]
i think ootb should be a **minimal showcase of use case supported** by .NET CLI team

- library
- console
- test proj? `dotnet test`
- tool proj? `dotnet-mytool`

Nice for demo, and bootstrap simple proj.

About asp.net, it's not directly of cli but it's a good complete use case and is supported, so ok.

If a template is really used a lot (telemetry?), can be added later as ootb.

About ootb vs discover:
I prefer to tune dotnet-new to make it easier to discover/install templates than ootb

I think `dotnet-new --list` can **show a link to a gallery** (a simple website), to explain how templates works and make it easier to discover additional templates ( list of templates? ).

And add something like `--list --remote` to list templates (from a static json in the gallery website?)

With `--list --remote` it's like ootb

**Comment by blackdwarf** [comment]
The work that is described in #2052 will make this issue slightly obsolete as `dotnet new` will have a way to list out templates. Closing.
