### ISSUE TITLE
sdk/<Version> is Nuget version instead of cli version

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#2001]
Currently when extracting dotnet-dev zip I'm seeing following folder:
```
sdk\1.0.0-beta-001937
```

instead of:
```
sdk\1.0.0.001937
```

I believe sdk is referring to a cli version.

**Comment by brthor** [comment]
cc @Sridhar-MS What is this supposed to be?

for the deb packages the version is the same format: `1.0.0-beta-001937` is this right?

**Comment by krwq** [comment]
Talked offline, version is correct
