### ISSUE TITLE
Ubuntu Latest links are not getting updated with recent builds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#2007]
The installer links on the [Readme](https://github.com/dotnet/cli/blob/rel/1.0.0/README.md) for Ubuntu are out of date.  The readme indicates the current version is 1.0.0.001971 yet the installers are for 1.0.0.001793.

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-ubuntu-x64.latest.deb
https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-dev-ubuntu-x64.latest.tar.gz

I took a cursory look and it appears this regression may have been introduced during the refactoring work to replace the scripts with build targets.  I do not see any logic that is updating the latest installer links for ubuntu builds - https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/PublishTargets.cs

**Comment by MichaelSimons** [comment]
@brthor, @naamunds - this is affecting the dotnet-preview docker builds.  New builds are getting triggered in Docker Hub from the dotnet CI builds but they are all pointing to the same version - 1793.

**Comment by brthor** [comment]
I'll take a look at this today
