### ISSUE TITLE
Project directories containing a dot cannot resolve coreclr path

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/cli#2009]
Project directories containing a dot cannot resolve coreclr path. A folder name without a dot (a.k.a. period, full stop) works just fine.

I used the `1.0.0-beta-001937` Windows x64 installer from the README:
https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe

This seems like a really basic problem, so perhaps it is a silly user issue :smile:.

## Steps to reproduce

```
mkdir foo.bar
cd foo.bar
dotnet new
dotnet restore
dotnet run
```

## Expected  behavior

```
Hello World!
```

## Actual behavior
```
Could not resolve coreclr path
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001937)

Product Information:
 Version:     1.0.0-beta-001937
 Commit Sha:  3616378130

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by colemickens** [comment]
I was experiencing this but was unaware that it was due to the period. This affects 1.0.1.001589-1 for Linux as well.

**Comment by brthor** [comment]
fairly strange cc @schellap any ideas?

**Comment by schellap** [comment]
This is a corehost bug. Thanks for reporting it. PR #2021 should address this.

**Comment by mmalolepszy** [comment]
@schellap Will this also address #1988?

**Comment by schellap** [comment]
Can this be closed now?

**Comment by joelverhagen** [comment]
Yup, I've tried with newer builds and things seem to be working. Feel free to close.
