### ISSUE TITLE
Capitalization of build folders names in case sensitive OS's

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#2010]
Moved from https://github.com/dotnet/corefx/issues/7173 on behalf of @dmportella

> HI everyone
> 
> Not sure if this is the right place to post this request but I wanted to ask for a change in the build folder setup for dotnet applications, I would like bin/Debug, bin/Release to be by default lower case. I know sounds lazy and all changing this would have no effect on a windows platform but would go be so cool not having to keep reminding yourself that the debug folder name is {caps}Debug and not debug.
> 
> ![image](https://cloud.githubusercontent.com/assets/676817/13982643/21b3c73e-f0e3-11e5-98eb-9ad067917332.png)
> 
> Anyway
> 
> peace

**Comment by dmportella** [comment]
thank you! yes please!

**Comment by piotrpMSFT** [comment]
Moved to SDK repo

**Comment by dmportella** [comment]
thank you
