### ISSUE TITLE
Include crossgen in the shared framework.

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#2013]
@brianrob Would like us to include crossgen as part of the shared framework so that during profiling it's possible to generate symbols for NGEN and R2R images, which requires the matching version of crossgen.

**Comment by ellismg** [comment]
/cc @gkhanna79 @weshaggard @piotrpMSFT 

I think there were some discussions going on about how folks could pick up the correct version of crossgen (since it's in the tools folder, correct?).  Could we just include it as part of the the runtime so any application that deployed (either via shared framework or published standalone) can have it?

**Comment by brianrob** [comment]
@ellismg, I think that's exactly what we should do.  Makes discovery super-simple, and ensures that crossgen is always available in all scenarios (both development and production).

**Comment by weshaggard** [comment]
This is @gkhanna79 call since he owns the tool and the runtime package but I know there were some concerns from folks like @jkotas about always including crossgen by default. I'm not sure what the best option is here but it seems like it should be part of the SDK in someway.

**Comment by gkhanna79** [comment]
We dont need crossgen deployed by default. For SharedFX, dont know the CoreCLR nuget package at composition time so as to extract crossgen from there to include as part of the REDIST package?

**Comment by ellismg** [comment]
> We dont need crossgen deployed by default.

Brian's concern is that without crossgen present when an app is deployed standalone, profiling it becomes impossible because we can't generate symbols for native images.  This would be a problem even if we add it to Shared Framework.

**Comment by brianrob** [comment]
Matt is right.  If there is a scenario where you deploy an app, we need crossgen there as well or we can't generate symbols for native images.

**Comment by jkotas** [comment]
I think that the symbols should be generated during the build and then copied to the target machine - if they are needed for profiling, etc.

It should be no different from how the unmanaged code works: You need to generate symbols during the build to get good symbols for unmanaged code, and then deploy them next to the app.

If we do something creative that is different from what one would do for unmanaged code, it will need to be likely redone as our AOT compilation will be getting more and more similar to how regular unmanaged code works.

**Comment by brianrob** [comment]
That sounds like a good plan for images that we ship.  Are we supporting apps to be completely crossgen'd?  If so, we'd need a story for that too.

**Comment by brianrob** [comment]
To be clear, I like a plan that puts symbol generation in the build and simplifies what we have to do to collect performance data  - I just want to make sure that the full set of scenarios is covered.

**Comment by gkhanna79** [comment]
> Are we supporting apps to be completely crossgen'd? 

I am not aware of this. But we should not built anything that wouldnt work if this gets enabled.

**Comment by brianrob** [comment]
I could see us doing this in a couple of different ways - one would be to ship crossgen, and another would be to have crossgen automatically produce the symbol files at image generation time, and then there's just a question of how they get packaged and made available.  You could imagine them being part of the nuget package.

**Comment by piotrpMSFT** [comment]
Moved to Core-Setup repo
