### ISSUE TITLE
"Dependency" type of tools for EF and Razor tooling (and possibly others)

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#2020]
In addition to regular "tools", we'll need an additional tool type for the tools that require to access the project. One example is EF tooling for migrations, which need to access DbContext of the given project. 

EF and Razor tools from ASP.NET Core will be of this new type.  Publish-IIS, dotnet-watch etc. will be of the current type.

Here are the requirements/design proposal for this:
- Tools that reason about and/or load the project must be declared as a dependency of the project, rather than as a tool (put it in the “dependencies” section, not the “tools” section)
  This will include the Razor & EF tools packages
- Tools referenced in the “tools” section must target “netcoreapp1.0” as they will be loaded on Core CLR
  Tools that reason about and/or load the project may target “netcoreapp1.0” or “net4x”, or even cross-compile to both, as they will be declared in the project’s “dependencies” section and restored as such (see above)
- Tools that target “net4x” will ship a compiled EXE in the appropriate TFM folder in the NuGet package
- If the tool is referenced as a dependency, “dotnet tool-name” will determine how to run the tool based on the tool’s and project’s TFMs:
  - If the project targets a single TFM, it will execute the tool image corresponding to that TFM
  - If the intersection of the project and tool’s TFMs is a single TFM, it will execute the tool for that TFM
  - If the intersection of the project and tool’s TFMs is multiple TFMs, and one is “netcoreapp1.0”, it will execute the tool image for “netcoreapp1.0”, i.e. The “netcoreapp1.0” TFM is preferred, unless a TFM was specified via the “-f” cmd line flag
  - If the intersection of the project and tool’s TFMs is multiple TFMs, and none is “netcoreapp1.0”, the execution will fail unless the specified TFM was passed via the “-f” flag at the cmd line, e.g. “dotnet -f net46 my-tool”
- In the case the executing tool is targeting a desktop TFM (“net4x”), the CLI will:
  - Build the project
  - Run the tool EXE from the project’s build output folder (it will be there because the tool was declared as a project dependency and thus copied over as part of build in the case of  applications targeting desktop)

Let me know if you have any questions!

cc @piotrpMSFT @DamianEdwards @davidfowl @Eilon

**Comment by muratg** [comment]
@piotrpMSFT could you please triage? I believe this is tracked in the war room so filing this bug to track the work.

**Comment by piotrpMSFT** [comment]
@muratg The core of this feature already exists. The most important missing component is the ability to bypass dotnet.exe when calling a command in the desktop context. We'll get this done tomorrow.

The 2nd and 3rd main bullets are inconsistent with CLI patterns, something we want to avoid. 

For TFM selection, this command resolution strategy already works but requires the TFM to be specified with -f to clear up ambiguity. We want to avoid the sort of magic described in the issue as it is very difficult to explain and maintain over time. I'd like to sync with you offline to understand why choosing a single TFM is ever the right thing to do [it is not for unit testing, for example].

For what the CLI will do during tool execution, it should not automatically call build when invoking another command. We'll look into providing a clear error message, but it is very unexpected that running a tool would automatically cause a build to happen.

**Comment by piotrpMSFT** [comment]
Chatted with @muratg offline. For the moment, we'll light up this scenario with basic -f scenario [tfm must be specified when invoking a tool that is a direct dependency of the project]. We'll look at improving UX as we learn more about usage patterns, etc.

@blackdwarf @brthor @livarcocc

**Comment by blackdwarf** [comment]
@piotrpMSFT so, these types of tools would be invoked like `dotnet ef scaffold -f net45` or similar?

**Comment by piotrpMSFT** [comment]
so you bring up a neat issue, @blackdwarf. Sadly, no. These tools would be invoked as:

`dotnet -f net45 -c Release -r win7-x64 -b C:\my\output\dir\ ef scaffold`

**Comment by DamianEdwards** [comment]
Yeah that's not going to work. It needs to be as simple as @blackdwarf's sample

**Comment by piotrpMSFT** [comment]
yea agreed :) we need to make some simplifying assumptions. I'll find time...

**Comment by blackdwarf** [comment]
Yup, this needs to be better.

**Comment by piotrpMSFT** [comment]
Ok, chatted with @bricelam offline and we came up with a plan. In order to keep the user experience clean, we'll have commands that require project-specific execution to behave like dotnet-test + dotnet-test-xunit. This is a bit more work for tools implementers, but hides the complexity associated with commands that resolve with the project.

**Comment by DamianEdwards** [comment]
I don't quite understand what that means. Could you provide some more detail please?

**Comment by piotrpMSFT** [comment]
EF will provide a tool called dotnet-ef which is referenced in the 'tools' section. There will also be a TFM specific package which is referenced in the dependencies section. The `tools` tool will follow usual invocation conventions `dotnet ef` which includes redirection like `dotnet ef -c Release -...`. 

With this approach, the user follows a consistent calling convention for tools. For example:
* dotnet build
* dotnet ef
* dotnet publish

will work, as will a custom build:
* dotnet build -c Release -f dotnet451 -r win7-x64 -o C:\artifacts
* dotnet ef -c Release -f dotnet451 -r win7-x64 -o C:\artifacts
* dotnet publish -c Release -f dotnet451 -r win7-x64 -o C:\artifacts

Behind the scenes, the top level dotnet ef tool will take in these parameters and use them to help find the real dotnet ef implementation in the C:\artifacts\bin\Release\dotnet451\win7-x64 directory, then invoke that tool.

If we didn't do this, we'd need to tell the user to do something like
* dotnet build -c Release -f dotnet451 -r win7-x64 -o C:\artifacts
* dotnet -c Release -f dotnet451 -r win7-x64 -o C:\artifacts ef  -c Release -f dotnet451 -r win7-x64 -o C:\artifacts 
* dotnet publish -c Release -f dotnet451 -r win7-x64 -o C:\artifacts

**Comment by muratg** [comment]
What will be the package that's referenced in the dependencies section? 

So with this, let's say I have both netcoreapp1.0 and net451 in my app. I and I have the ef tool in tools. 

When I say dotnet ef, which version will be executed?  (I assume netcoreapp1.0 version... If that's the case, do I still need to provide -c -f -r -o to execute the net451 version?)

(Also, I assume you meant net451 instead of dotnet451 above. :smiley_cat:  Otherwise, if there's another TFM change, please let me know!)

**Comment by piotrpMSFT** [comment]
`dotnet ef` executes teh 'tools' section version. This one acts like dotnet-test.

The tools section version decides what's next, really. By default, it can copy dotnet-test in its logic. However, we can figure out a more interesting EF-specific policy. 

If we want to share logic with dotnet-test, that has already been split into utils.

**Comment by piotrpMSFT** [comment]
You will need to provide -c -f -r -o just like it was provided to build. Otherwise, we have no way of finding the TFM-specific output directory --> TFM specific tool.

**Comment by DamianEdwards** [comment]
So basically it's up to the tool to handle the dispatching logic, yes? But the CLI will still support dispatching to CLI-based tools in "dependencies", or are we removing that completely to make this more clear-cut?

I'd like to see some sample `project.json` files here with what this would look like for a typical ASP.NET Core application, with EF and Razor tools. Is there any reason we can't have the same package be declared in both the "tools" and "dependencies" section and have it carry everything required?

**Comment by muratg** [comment]
OK thanks. So this proposal saves us from providing the parameters when you run against netcoreapp1.0, right?

**Comment by bricelam** [comment]
My ideal `project.json` for EF would look like this:
```JSON
{
    "tools": {
        "dotnet-ef": "1.0.0"
    },
    "dependencies": {
        "Microsoft.EFCore.SqlServer": "1.0.0",
        "Microsoft.EFCore.Design": { "version": "1.0.0", "type": "design" }
    }
}
```

**Comment by DamianEdwards** [comment]
What is `"type": "design"`? Does NuGet already understand that? Do you mean `"type": "build"`?

**Comment by bricelam** [comment]
I made up `design`. I think `build` might work. The lines between build, publish, pack, and deploy are blurry in my mind. I'll play with it and see.

**Comment by DamianEdwards** [comment]
Any new value there requires changes to NuGet so the bar is extremely high there. The design we came up with for this already used "build" so I think that should be fine, as long the CLI ensures dependencies marked as "build" are copied to the build output but not the publish output.

**Comment by DamianEdwards** [comment]
And you made up at least one of those verbs :)

**Comment by DamianEdwards** [comment]
Based on my current understanding, and fleshing it out a bit more, it will end up looking like this:

``` json
{
    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0",
        "Microsoft.Extensions.UserSecrets.Tools": "1.0.0",
        "Microsoft.DotNet.Watch": "1.0.0"
    },
    "dependencies": {
        "Microsoft.NETCore.App": { "version": "1.0.0", "type": "platform" },
        "Microsoft.AspNetCore.Mvc": "1.0.0",
        "Microsoft.AspNetCore.Razor.Design": { "version": "1.0.0", "type": "build" },
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
        "Microsoft.EntityFrameworkCore.Design": { "version": "1.0.0", "type": "build" },
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0"
    },
    "frameworks": {
        "netcoreapp1.0": { }
    }
}
```

**Comment by muratg** [comment]
@DamianEdwards wouldn't the `dependencies` references have `.tools` in their package names as well?

**Comment by davidfowl** [comment]
So how did this fix anything? Are we just generally going to stop dispatching from dependencies and instead just use the tools section? I don't understand.

**Comment by bricelam** [comment]
@davidfowl Yes, the tools (e.g. `dotnet-ef`) will contain logic to dispatch to the dependencies (e.g. `Microsoft.EFCore.Design`). The tool will only target `netcoreapp` while the dependency can target any number of frameworks.

**Comment by bricelam** [comment]
cc @NTaylorMullen @prafullbhosale

**Comment by DamianEdwards** [comment]
But will the CLI actually stop discovering and invoking tools in dependencies too?

**Comment by davidfowl** [comment]
@bricelam so we "fixed it" by making each tool dispatch to another tool in the project. Are we basically going to copy the command resolver to each tool?

**Comment by brthor** [comment]
The `ProjectDependenciesCommandResolver` and `ProjectDependenciesCommandFactory` are both available via the cli Utils nupkg, so copying them to each tool shouldn't be necessary

**Comment by bricelam** [comment]
To clarify some of my comments: I'm not advocating any particular implementation of this feature. We just talked about **one way** it could work. If the CLI team wants to add more first-class support for this scenario, I'll use it; otherwise, I'm happy to put the logic in `dotnet-ef`.

**Comment by DamianEdwards** [comment]
@murat yeah I was wondering whether should just do that, i.e. have the "Tools" package appear in both "tools" and "dependencies" and carry all it needs to be run. But as @davidfowl said, this seems like we're just back to where we started. I'm not sure I quite understand why we couldn't have the CLI dispatch to tools in the project output, given we're now just asking the tool itself to do it.

**Comment by piotrpMSFT** [comment]
We already have a model for these types of tools.
