### ISSUE TITLE
Build for dnxcore50 entrypoint does not include dependent assembly in its output

### ISSUE THREAD

**Issue by marono** [dotnet/cli#2025]
When building an app (entrypoint) for dnxcore50, dependent assemblies are not included in the output. This is different from building the same project for net451, which will copy all dependencies to the output directory.

Is this by design?
And if so, how do I run my code on a production machine, if I want to ship the binaries and not rebuild it there?

MO

**Comment by enricosada** [comment]
You can use `dotnet publish` to create a directory with all binaries ready to be copied on production machine.

**Comment by borgdylan** [comment]
If on ubuntu 15.10, publish still leaves stuff behind like System.Console (excluding having to copy coreclr manually).

**Comment by marono** [comment]
Thanks @enricosada, that's what I was after.
