### ISSUE TITLE
Add support for .devruntimeconfig.json

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2027]
This will be generated only during non-publish scenarios and contains absolutePath to a cache that host can use for resolving dependencies.

It contains the property "additionalProbingPaths" that are semicolon delimited.

CC @schellap @blackdwarf

**Comment by schellap** [comment]
Why do you need a change from a single path to multiple paths?

Why a devruntimeconfig? It seems we are reading too many files. I see you want it to be really explicit, but you can do this with a section in runtimeconfig itself with an explicit name. If a user moves build output to another machine, code may not run today and in both cases whether we have this section or not.

**Comment by livarcocc** [comment]
Closing this in favor of https://github.com/dotnet/cli/issues/2090.
