### ISSUE TITLE
"Could not load host policy library" after updates

### ISSUE THREAD

**Issue by ciel** [dotnet/cli#2037]
When I try to run an application that includes the `Microsoft.NETCore.App` library, such as the one created by `dotnet new`, I get the error message...

> "Could not load host policy library"

## Steps to reproduce

- Install the latest `dot net cli` build (as of 3/24/2016 - 4:11 PM CST, it is version `1.0.0-beta-001986`)

- create a new folder anywhere
- open a command line in the new folder
- in the command line, run `dotnet new`
- in the `project.json`, change `Microsoft.NET.Core.App` to use version `1.0.0-rc-*`
- in the command line, run `dotnet restore`
- in the command line, run `dotnet run`

## Expected  behavior
The app should run as expected; `Hello World!` ought to be printed to the console.

## Actual behavior
The following is printed to the console.

```
NuGet Config files used:
    C:\Users\Ciel\Documents\Visual Studio 2015\Projects\n\NuGet.Config
    C:\Users\Ciel\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
PS C:\Users\Ciel\Documents\Visual Studio 2015\Projects\n> dotnet run
Compiling n for .NETStandard,Version=v1.5
C:\Users\Ciel\Documents\Visual Studio 2015\Projects\n\project.json(7,30): warning NU1007: Dependency specified was Microsoft.NETCore.App >= 1.0.0-rc-* but ended up with Microsoft.NETCore.App 1.0.0-rc2-23910.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.2376827


Could not load host policy library [C:\Users\Ciel\Documents\Visual Studio 2015\Projects\n\bin\Debug\netstandard1.5]
```

## Environment data
`dotnet --version` output:

```
.NET Command Line Tools (1.0.0-beta-001986)

Product Information:
 Version:     1.0.0-beta-001986
 Commit Sha:  f0fd9ae901

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

```

**Comment by ciel** [comment]
This also happens if you remove the `Microsoft.NETCore.App` completely. However, using it at the version that it pulls by default, which is listed as...

```
  "dependencies": {
    "Microsoft.NETCore.App": { "type": "platform", "version": "1.0.0-rc2-23911" }
  },
```

Yields a different error after the run begins;

`Unexpected error writing debug information -- 'Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Cci.ISymUnmanagedWriter5'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{DCF7780D-BDE9-45DF-ACFE-21731A32000C}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).'`

**Comment by miguellira** [comment]
@ciel Ran into the same issue on OS X.

FYI, I noticed you requested `1.0.0-rc-*` instead of `1.0.0-rc*` which will always result in the warning included in your output.

Nevertheless, I also get the `Could not load host policy library` error will appear unless I pin it to the default included in `dotnet new` namely `1.0.0-rc2-23911`

Have you tried updating your [CLI](https://github.com/dotnet/cli)? Looks like the Windows version is up to `1.0.0-beta-002019` now.

**Comment by ciel** [comment]
Yeah, I just tried the newest cli. Still no luck.

**Comment by miguellira** [comment]
@ciel As was pointed out in the thread I referenced above, it looks like unless you pin it you're going to bring down rc3 bits and the interplay with depencies will generated errors.

Is there a reason why you want `-rc*` bits?

I installed the latest CLI on my Windows 10 setup and noticed it now uses `"1.0.0-rc2-23925` - I'd stick with that version for console apps.

**Comment by miguellira** [comment]
@ciel  BTW... I attemped to run the HelloMvc sample app from https://github.com/aspnet/cli-samples on my Windows 10 setup with the latest CLI and ran into the same issue I logged here: https://github.com/aspnet/Mvc/issues/4349 so although neither works at lease both my Mac and Windows machine are on par :confused:

FYI, in order to get the HelloMvc app to run against the latest CLI I updated the `project.json` to this:
```json
"frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            },
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    }
```
NOTE: I used `netcoreapp1.0` instead of `netstandardapp1.5` based on this thread:  https://github.com/NuGet/Home/issues/2299

**Comment by tugberkugurlu** [comment]
I am getting the same:

```
tugberk@ubuntu:~/apps/cli-samples/HelloMvcApi$ dotnet run
Project HelloMvcApi (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Could not load host policy library from [/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0-rc2-3002426]
This may be because the targeted framework ["Microsoft.NETCore.App": "1.0.0-rc2-3002426"] was not found.
tugberk@ubuntu:~/apps/cli-samples/HelloMvcApi$ dotnet run
Project HelloMvcApi (.NETCoreApp,Version=v1.0) will be compiled because some of its inputs were newer than its oldest output.
Compiling HelloMvcApi for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.5604112
 

Could not load host policy library from [/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0-rc2-3002426]
This may be because the targeted framework ["Microsoft.NETCore.App": "1.0.0-rc2-3002426"] was not found.
```

info:

```
tugberk@ubuntu:~/apps/cli-samples/HelloMvcApi$ dotnet --info
.NET Command Line Tools (1.0.0-rc2-002416)

Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

```

**Comment by GuardRex** [comment]
@tugberkugurlu Show your `project.json`

**Comment by tugberkugurlu** [comment]
@GuardRex https://github.com/aspnet/cli-samples/blob/28a8dd10a0f7660ff4528f576081d7c34f69722f/HelloMvcApi/project.json

**Comment by GuardRex** [comment]
@tugberkugurlu That's cool. You're using the CI release feed, right? I can't repro that here. You might want to nuke your package cache.

**Comment by miguellira** [comment]
@tugberkugurlu Might also want to make sure you pull the latest of that repo. The reference to the meta package (`Microsoft.NETCore.App`) was recently updated to grab latest (`1.0.0-*`)

**Comment by tugberkugurlu** [comment]
@GuardRex nice, thx! running `dotnet restore --no-cache` [made it work](https://twitter.com/tourismgeek/status/723440947678208000).

Where is the package cache is stored? or is there a command to nuke the package cache?

**Comment by nil4** [comment]
@tugberkugurlu you can use the [nuget locals](https://docs.nuget.org/consume/command-line-reference#locals-command) commands (I'm using nuget.exe 3.3):
- list all package cache locations: `nuget.exe locals all -list` 
- clear all package caches: `nuget.exe locals all -clear`

**Comment by tugberkugurlu** [comment]
@nil4 thanks. It confusing to have nuget.exe and dotnet.exe at the same time.

**Comment by GuardRex** [comment]
@tugberkugurlu ^^ Great tip from @nil4 ... I've been doing it the stupid :monkey: way: Dump them in  `c:\Users\<user>\AppData\.nuget\packages`. Now that @nil4 set me straight on that, I can stop the iNsAnIty.

@tugberkugurlu ^^ **Great idea!**

**Comment by blackdwarf** [comment]
I'm going to close this issue because it is based on a very old version of the tooling and also it seems that the original issue has been worked around. If you believe this to be an error, please reopen.
