### ISSUE TITLE
install scripts are no longer "incremental"

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#2039]
Previously, the install scripts used to check the latest version number and if it matched the version already installed, it exited successfully without downloading anything. Now it appears to wipe out and reinstall the existing version. We should reintroduce the ability to detect the version and no-op, since the download and unpacking of the ZIP is significantly slower and now happens on every invocation of a build script that uses the install script.

/cc @blackdwarf @piotrpMSFT @krwq

**Comment by krwq** [comment]
Did this https://github.com/dotnet/cli/pull/2041 solve it?

**Comment by anurse** [comment]
Looks like it.
