### ISSUE TITLE
Package names in apt-mo look wrong

### ISSUE THREAD

**Issue by colemickens** [dotnet/cli#2047]
This is using https://apt-mo.trafficmanager.net/repos/dotnet

```
$ apt-get update
$ apt-cache search dotnet

libgtk-dotnet3.0-cil - GTK.NET library
libgtk-dotnet3.0-cil-dev - GTK.NET library - development files
dotnet - .NET Core & command line tools
dotnet-dev - .NET Core & command line tools
dotnet-dev-1.0.0-rc2-23911 - .NET Core & command line tools
dotnet-host - .NET Core Shared Host
dotnet-nightly - Unstable Developer Build of .NET Core & command line tools
dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-23911 - .NET Core Shared Framework Microsoft.NETCore.App 1.0.0-rc2-23911
```

Looks like the version string got put in the package name string...

* dotnet-dev-1.0.0-rc2-23911

* dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-23911

**Comment by colemickens** [comment]
For context: I'm trying to emulate [this PR on dotnet-docker-preview](https://github.com/dotnet/dotnet-docker-preview/pull/7) because I prefer to pull from apt (mostly because I can pin a specific version rather than dotnet-docker-preview where I don't really know what build I'm getting). But I ran into this...

**Comment by colemickens** [comment]
CC: @brthor (I think, sorry for the noise if not)

**Comment by brthor** [comment]
#2043 Is fixing some of the deb versions inconsistencies (the wrong version is actually in that name), but the version being part of the name is part of the new side by side strategy 

The older dotnet-dev, dotnet-nightly, and dotnet packages will all be cleaned up from the feed soon.

(cc @blackdwarf  @piotrpMSFT )

**Comment by colemickens** [comment]
Stiill seeing new builds in apt-mo that don't look right even though your fix was merged 3 days ago.

Also, the CLI has no --version flag, and the version listed in dpkg doesn't align with the version that shows up in the package filename, so it's very hard to tell what version(s) are in play at any given time.

**Comment by brthor** [comment]
@colemickens Known issue with the feeds currently. Publishing of the shared framework broke something. Chuan is telling me there is an aptly error on the repo side. Am following up with him.

**Comment by brthor** [comment]
As a note here, the latest available packages are as below:

```
dotnet-dev-1.0.0-beta-002111
dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-23928
dotnet-host
```

cc @MichaelSimons @naamunds 

any of the dev and shared framework versions can be installed side by side.

Going to close this out for now

**Comment by colemickens** [comment]
Sorry, I should've commented earlier. Are you intentionally putting the version name in the package name? That's not normal as far as I know.

I would expect to see:
```
# apt-cache search dotnet

dotnet-dev - .NET Core & command line tools
dotnet-host - .NET Core Shared Host
dotnet-nightly - Unstable Developer Build of .NET Core & command line tools
dotnet-sharedframework-microsoft.netcore.app - .NET Core Microsoft.NETCore.App

# apt-cache policy dotnet-dev

[ lists out lots of versions ]
```

**Comment by brthor** [comment]
Decision was made that we would support Side by side installations with the cli and the shared framework.

To support this we followed the model clang uses where you'd do `apt-get install clang-3.5`

Currently the package names are about impossible to remember and type out, but the intention is that come 1.0.0, it will be much easier.

cc @blackdwarf

**Comment by colemickens** [comment]
Got it. Thanks.

**Comment by colemickens** [comment]
One more question -- some packages have 'beta' in the name, others have 'rc2'. Are there separate branches building two sets of packages? In fact in your reply this morning where you note the latest packages available, one is a "beta" and one is an "rc"?

Thanks for all the help on this.

**Comment by brthor** [comment]
No problem.

The reason for the difference is that the shared framework package contains corefx and coreclr, so it follows their versioning scheme. The dev package contains only the cli so it follows our versioning.

The random `rc2` dotnet-dev package was a mistake. I'll be going through and cleaning up the feed soon, but want to give a chance for things to settle first.

It is somewhat confusing, but as the branding fleshes out i hope it will become more apparent what is going on.
