### ISSUE TITLE
Need breadcrumb store ACL'ed by installer

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#2050]
@mellinoe @ellismg 

On Unix and Mac OS, need known paths that will be ACL'ed for

1. Host breadcrumbs
2. Servicing location.

On Windows it is:
C:\ProgramData\Microsoft\NetFramework\BreadcrumbStore

The host's fallback order:
1. `/opt/dotnet_servicing/breadcrumbs` (this needs to be ACL'ed user writable)
2. `$DOTNET_SERVICING/breadcrumbs`
3. `$HOME/.dotnet_servicing/breadcrumbs`

**Comment by schellap** [comment]
The setup should create the folder if they don't exist and ACL them to be user-write-once on windows and on Unix make it user write.

**Comment by ellismg** [comment]
Can we change the order to prove $DOTNET_SERVICING location before the others?

**Comment by schellap** [comment]
@gkhanna79 can close this?

**Comment by gkhanna79** [comment]
Yes, it can be closed.
