### ISSUE TITLE
.NET Core Installer vs .NET Core Cli Installers is confusing

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2057]
I installed `.NET Core Installer` and wanted to confirm that I have the latest version and got:

```
PS C:\WINDOWS\system32> dotnet --version
Could not resolve SDK directory from [C:\Program Files\dotnet]
```

I did see that `--help` options in the new thing were limited but was not aware that I need a different installer to do my dev work. This is quite confusing since the tutorials say you should do `dotnet build`, `dotnet run` etc. but if you install just the Core Installer nothing of this works. The message and `--help` is very unhelpful either.

**Comment by brthor** [comment]
@moozzyk The Core Installer is intended to place the shared framework and host only on your machine. 

In this way it can be used for running apps, but not building them.

The `.NET Core Cli` Installer is what you are looking for

**Comment by moozzyk** [comment]
Yes, @anurse explained it too me. But users don't have @anurse or you around - the message should make it possible to figure it out on my own. At the moment is is not helpful.

**Comment by brthor** [comment]
Totally agree! any suggestions there?

cc @blackdwarf

**Comment by shahid-pk** [comment]
the .net core one should be called something like .net core runtime.

**Comment by anurse** [comment]
I prefer "Runtime" and "SDK" as distinctions. Also, the muxer should be capable of responding to `--version` at some point before RTM :)

**Comment by enricosada** [comment]
:+1: about `.NET Core Runtime`

And maybe `.NET Core CLI` can be just `.NET CLI`, because it can build all targets, not only `.NET Core`.
It's already a good name, short

![image](https://cloud.githubusercontent.com/assets/147243/14051122/cfefd8ea-f2c0-11e5-815b-57a5837878e7.png)

**Comment by xoofx** [comment]
> I prefer "Runtime" and "SDK" as distinctions. Also, the muxer should be capable of responding to --version at some point before RTM :)

:+1:  for  `.NET Core Runtime` and `.NET Core SDK` installers.

**Comment by piotrpMSFT** [comment]
@richlander @blackdwarf regarding branding. 

@schellap regarding --version in the muxer

**Comment by brthor** [comment]
I think Tools is confusing because we have a separate concept of cli tools in the project.json.

It's not too bad, but every time we talk about tools we'll need to point out which tools we're talking about.

**Comment by akoeplinger** [comment]
You could call it `.NET Core Command Line Interface (CLI)` similar to the SDK. I agree that Tools is more confusing even though there are different CLI meanings.

**Comment by blackdwarf** [comment]
@brthor @akoeplinger good, I actually would like to leave it as CLI. :) Grew on me, we are all using it, the people outside are using it and there is **a lot** of precedent in other products.

**Comment by blackdwarf** [comment]
There is a PR where you can share your opinions: #2147

**Comment by blackdwarf** [comment]
Actually, this is solved now I believe, since we have a different branding in place. :) Will close, please reopen if the issue still persists.
