### ISSUE TITLE
Newest build (2019) seems to break ASP.NET

### ISSUE THREAD

**Issue by kwaclaw** [dotnet/cli#2061]
See https://github.com/aspnet/Mvc/issues/4349

**Comment by Eilon** [comment]
This isn't really a CLI bug, is it? ASP.NET just needs to accept a newer CLI (which they are doing).

**Comment by piotrpMSFT** [comment]
Read through aspnet/Mvc#4349 and agree with @Eilon. need to move ASP.NET to latest CLI + NuGets. Please re-open if there is a CLI issue here.
