### ISSUE TITLE
Need to fix the version suffix of coreclr-xunit so that new packages show up before older ones

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#2070]
A package generated today had version 1.0.0-dev-121848-00 which shows after the previous version 1.0.0-dev-91790-12.

**Comment by livarcocc** [comment]
@victorhurdugaci I have done a workaround by removing the old package. So, all the packages currently in the feed are in the right order.

**Comment by victorhurdugaci** [comment]
Sounds good :)

**Comment by pranavkm** [comment]
Couldn't you change the min version of the package? Removing this would require us to remove it from aspnetcidev which would leave our dev branches broken.

**Comment by livarcocc** [comment]
@pranavkm I could. This was just faster. Can't you manually updated to the latest one? If it is a problem, I can manually generate a package.

**Comment by pranavkm** [comment]
Hmm, we'd have to update all our project.jsons to react to the version change, so I think it might be simpler to try and get the latest version you have now. We can live with it :smile:

**Comment by piotrpMSFT** [comment]
Is this still an issue, then?

**Comment by pranavkm** [comment]
This can be closed. The build of the CLI that we have does not support restoring tools with `netstandardapp`, so we can't upgrade one without the other. Waiting to sort the two out.
