### ISSUE TITLE
CoreCLR crashes on initialization: Ubuntu 15.10 (wily)

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#2072]
## Steps to reproduce
`dotnet --help`

## Expected  behavior
Help output

## Actual behavior
Crashes with output:
`Failed to initialize CoreCLR, HRESULT: 0x80131500`

Full log with trace on: https://gist.github.com/natemcmaster/55ada183b40f894aff91

## Environment data
`dotnet --version` output:
(doesn't work....)

But, it would probably contain

Version: 1.0.0-beta-002028
RID: ubuntu.15.10-x64

Likely due to CoreCLR, not cli: https://github.com/dotnet/coreclr/issues/3271

**Comment by moozzyk** [comment]
[This](https://github.com/aspnet/dnx/issues/3059#issuecomment-150672608) works around the issue.

**Comment by blackdwarf** [comment]
According to the [official roadmap](https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps) we support Ubuntu 14.04 and 16.06, that is the LTS releases. Also @moozzyk has linked to a workaround so I will close this issue. If you believe this is an error, please reopen.
