### ISSUE TITLE
[MSI]: Registry keys are not removed on  uninstall for the dotnet-dev bundle

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2073]
## Steps to reproduce
Install the latest dotnet-dev bundle - https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe

## Expected  behavior
Remove the reg keys at SOFTWARE\dotnet\Setup

## Actual behavior
Reg keys are not getting removed.

## Environment data
`dotnet --version` output:

**Comment by robmen** [comment]
Can you attach a log file from the uninstall of the MSI?

**Comment by piotrpMSFT** [comment]
Moving to rtm.

**Comment by Sridhar-MS** [comment]
This no longer repros.
