### ISSUE TITLE
"dotnet restore" fails when local folder used as nuget source

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#2081]
## Steps to reproduce

create a folder and put some packages in it. For an example:

```
<configuration>
  <packageSources>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="mynuget" value="C:\temp\nuget" />
  </packageSources>
</configuration>

```
## Actual behavior

Restoring fails even if package does exist. But 'dnu restore" works in the same situation.
## Environment data

`dotnet --version` output:
dotnet --version
1.0.0-beta-002058

dotnet --info:
.NET Command Line Tools (1.0.0-beta-002058)

Product Information:
 Version:     1.0.0-beta-002058
 Commit Sha:  e418371e2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment]
We do this regularly in our builds, can you provide any more info that might help diagnose? 

Error output would be a good start

**Comment by xatabhk** [comment]
@brthor 

NuGet.Config:
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="mynuget" value="C:\temp\nuget" />

The package folder layout:
![local_package](https://cloud.githubusercontent.com/assets/6814395/14095526/dbb2c6c6-f593-11e5-8135-40cdf35b8146.png)


The output message:
[restore_err.txt](https://github.com/dotnet/cli/files/192736/restore_err.txt)



The issues:
  (1). Paypal is not restored to C:\Users\xxxxx\.nuget\packages.
  (2). Package in C:\temp\nuget is not restored.

Workaround:
  Run "Dnx restore" first, then "dotnet restore".
  That is "dotnet restore" cannot do the full restoring and dnx is still required on my PC.

**Comment by emgarten** [comment]
@xatabhk I am not able to repro this issue. Will you check that the casing of the package id in licensedotnetlib.dll is all lowercase and matches the casing you in your project.json file?

Are you overriding the global packages folder? Running DNU restore (there is no DNX restore) should have no effect on NuGet since they use different packages folders.

Is the PayPal package also in your folder, or are you saying that you cannot restore it from nuget.org?

**Comment by xatabhk** [comment]
@emgarten Yes. it is all lowercase and matches the casing in project.json. And no paypal package in C:\Users\xxxx\.nuget\packages after "dotnet restore".

But "DNU restore" fixes all the issues. The latest DNX (20221) puts packages in C:\Users\xxxx\.nuget\packages instead of C:\Users\xxxx\.dnx\packages.

**Comment by xatabhk** [comment]
The latest Dotnet.exe is still not able to restore all packages for me.

**Comment by piotrpMSFT** [comment]
I just verified that this scenario works with preview3 CLI. If you still see the issue, please open in https://github.com/nuget/home.
