### ISSUE TITLE
`dotnet test` says it is the "DNX runner"

### ISSUE THREAD

**Issue by dougbu** [dotnet/cli#2082]
## Steps to reproduce
1. Restore a test project
2. Build
3. Execute `dotnet test --configuration debug` (if you built for debug configuration)

## Expected  behavior
Command starts with a description of the current runtime.

## Actual behavior
Command starts with a description of some old DNX runtime.
![dotnet](https://cloud.githubusercontent.com/assets/6431421/14064134/4c311e1a-f3ab-11e5-90a3-acd722a14618.png)

## Environment data
```
.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
 Version:     1.0.0-beta-001718
 Commit Sha:  5b0afe7880

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 Runtime Id:  win81-x64
```

**Comment by davidfowl** [comment]
I have no idea if this is fixed but you are using an extremely old dotnet

**Comment by livarcocc** [comment]
@davidfowl It is not. This is something that the runner prints. Easy fix. How about xUnit.net Dotnet Runner? The double dotnet seems weird. My second option would be simply xUnit.net Runner. Any opnions?

**Comment by livarcocc** [comment]
https://github.com/dotnet/coreclr.xunit/pull/19

**Comment by dougbu** [comment]
>  you are using an extremely old dotnet

FYI this is the `dotnet` version that ASP.NET builds are currently pinned to use. See [`cli.version.darwin`](https://github.com/aspnet/KoreBuild/blob/23f04b626f5da557fa8b96842532b4c740d772e7/build/cli.version.darwin) for example.

**Comment by livarcocc** [comment]
Fixed the runner.
