### ISSUE TITLE
Create a dotnetextensions path in platform installer

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2089]
Platform installer for SharedFX redist should also crete a "dotnetextensions" folder, sibling to the "dotnet" folder. On Windows, this should be created next to the "dotnet" folder in ProgramFiles(x86) folder.

CC @blackdwarf @richlander @Petermarcu @schellap @piotrpMSFT

**Comment by mellinoe** [comment]
From the discussion in the email, we should be able to have the other installers/servicing components install to this directory even if it doesn't exist yet and avoid adding extra stuff to the existing installers to handle this.
