### ISSUE TITLE
CLI Needs to be a portable app

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#2093]
In order to properly exercise the portable app model, the CLI really needs to be a portable app itself. ASP.NET is waiting on this before converting it's own projects to portable because there were a number of issues in the initial port that converting the CLI would clear up.

**Comment by pakrym** [comment]
Fixed by https://github.com/dotnet/cli/pull/2036 I suppose

**Comment by anurse** [comment]
:+1:
