### ISSUE TITLE
Install specific dotnet cli version from install.ps1 or install.sh

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#2099]
## Steps to reproduce

Using the script https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1 ( or [install.sh](https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.sh) ) to install a specific version

The `Latest` version works, the specific version doesnt works /cc @Sridhar-MS @krwq

The issue is the same for all os

That's really important for ci scenario, so it's possibile to pin a specific version

For example win:

```powershell
$env:CLI_VERSION="1.0.0.002071"
$env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
& .\scripts\obtain\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath
```

## Expected  behavior

Install version `1.0.0.002071` in  `$env:DOTNET_INSTALL_DIR`

## Actual behavior

WIN ( ref [appveyor](https://ci.appveyor.com/project/enricosada/fsharp-dotnet-cli-samples/build/0.0.1.126/job/8nlp38javw9j4p61#L10) ):

```
dotnet_install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.002071/dotnet-dev-win-x64.1.0.0.002071.zip 
BlobNotFoundThe specified blob does not exist. RequestId:e136e965-0001-0021-3047-890bb4000000 Time:2016-03-28T23:11:24.5135295Z
```

OSX (ref [travisci](https://travis-ci.org/enricosada/fsharp-dotnet-cli-samples/jobs/119115935#L49-L51) ):

```
dotnet_install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0.002071/dotnet-dev-osx-x64.1.0.0.002071.tar.gz
dotnet_install: Error: Download failed
```

## Environment data

Latest source

**Comment by Sridhar-MS** [comment]
@enricosada We switched over to using nuget-semantic version `1.0.0-beta-002071`. The version badge should reflect this but it does not and needs to be fixed.

**Comment by enricosada** [comment]
thx @Sridhar-MS that works, really thx.

btw i think the [install.ps1](https://github.com/dotnet/cli/blob/8df6f5405d5a2356beddff71da105a7e953ac46d/scripts/obtain/install.ps1#L21) need to be changed.

```
.PARAMETER Version
    Default: latest
    Represents a build version on specific channel. Possible values:
    - 4-part version in a format A.B.C.D - represents specific version of build
```

**Comment by krwq** [comment]
version description update: https://github.com/dotnet/cli/pull/2197
