### ISSUE TITLE
Add C# class lib and xunittest templates to dotnet new

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#2104]
Add C# class library template as well as xUnit test template to dotnet new. To be invoked with `dotnet new -t lib` and `dotnet new -t xunittest` respectively.

**Comment by enricosada** [comment]
@blackdwarf adding myself for notification, i can add f# and xunit works with f# too

**Comment by piotrpMSFT** [comment]
@blackdwarf this was discussed in shiproom today and punted to rtm.

**Comment by blackdwarf** [comment]
@piotrpMSFT then we should close it. This was specific to RC2 and "old-style" `dotnet new` since RTM will se the "new & improved" `dotnet new`. Essentially, a stopgap measure.
