### ISSUE TITLE
CLI VSO Builds broken due to corehost packaging

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2110]
## Steps to reproduce
Run VSO Build

## Expected  behavior
Build passes

### On Windows x86:
builds are failing with long path:
`'src/corehost/packaging/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00228-02/lib/portableTargets/packages/Microsoft.Portable.Targets/0.1.1-dev/contentFiles/any/any/Extensions/Microsoft/Portable/v4.0/Microsoft.Portable.Common.targets': Filename too long
warning: Could not stat path `

### On Windows x64:
Unable to resolve 'Microsoft.DotNet.BuildTools (>= 1.0.25-prerelease-00228-02)' for 'DNXCore,Version=v5.0'.

### On OS X, CentOS:
there is a failure when attempting to upload the package:
`Build failed: System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/ddjoin/vsoagent.0228/_work/build/f71e62a7cd640de3be469f22e475a39d03b107588cf866ccebea4c00cdfe5194/repo/artifacts/osx.10.10-x64/corehost/*.nupkg'.

## Environment data
`dotnet --version` output:

**Comment by piotrpMSFT** [comment]
@schellap please priorotize this and take a first stab. It's strange that the same change seems to be causing so many different symptoms.

I'm also curious why this passed Jenkins CI but is failing so badly in VSO...

**Comment by schellap** [comment]
I'll probably undo the change.
