### ISSUE TITLE
While getting started: Could not load file or assembly 'System.Runtime, Version=4.1.0.0

### ISSUE THREAD

**Issue by cjaeckel** [dotnet/cli#2112]
## Steps to reproduce
1. Installed latest dotnet-win-x64.1.0.0.001598.exe
2. In an empty directory I entered:

--    
    >dotnet new
    >dotnet restore
    >dotnet run
    Compiling core for DNXCore,Version=v5.0
    
    Compilation succeeded.
        0 Warning(s)
        0 Error(s)
    
    Time elapsed 00:00:01.2474332
    
    
    Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

## Environment data
    &gt;dotnet --version
    .NET Command Line Tools (1.0.0-beta-001598)
    
    Product Information:
     Version:     1.0.0-beta-001598
     Commit Sha:  7582649f88
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.10586
     OS Platform: Windows
     Runtime Id:  win10-x64

[project.lock.json.zip](https://github.com/dotnet/cli/files/193231/project.lock.json.zip)

**Comment by piotrpMSFT** [comment]
Whoa... where did you get that CLI version? 1598 is VERY old. Try latest from https://github.com/dotnet/cli!

**Comment by sunsided** [comment]
That is what gets downloaded from http://dotnet.github.io/

**Comment by cjaeckel** [comment]
Well, I got that CLI from [.NET Core Getting Started](http://dotnet.github.io/getting-started/) by just following the the link [official MSI installer](https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001598/dotnet-win-x64.1.0.0.001598.exe)...

Thank you for you hint, I now tried the win x64 installer from https://github.com/dotnet/cli but with no better luck.  
Now even the dotnet.exe does not work anymore:
```
>dotnet --version

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

Uninstallation of the "Microsoft .NET Core CLI for Windows (1.0.0.002169 beta)" via Settings/Apps & features and re-installation did not change the situation.  

Any recommended steps for a manual setup?

**Comment by sunsided** [comment]
`2169`? I just got the `2171` version from the GitHub repo here. However I couldn't even install the `dotnet-win-x64.latest.exe` one on Windows 10, but had to use `dotnet-dev-win-x64.latest.exe` ... with that, Kestrel won't start because it misses `libuv`.

**Comment by cjaeckel** [comment]
There seems to happen continuous building...  

- I uninstalled my current `2169` build.  
But the uninstall is leaving the `sdk` folder in the `dotnet` installation folder. (So, I manually deleted the `dotnet` folder.)
- Installation of `2171` shows the same problem:

```
>dotnet

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
Again: Any recommended steps for a manual setup?

**Comment by cjaeckel** [comment]
After uninstall of previous CLI versions and some cleanup of the mess being leftover I fetched version 2188.
Congratulations:
```
>dotnet new
>dotnet restore
>dotnet run
```
...is now showing `Hello world!`
