### ISSUE TITLE
Allow specifying a path to a project.json

### ISSUE THREAD

**Issue by glennc** [dotnet/cli#2120]
The ability to do `dotnet build --project /app/project.json` instead of being forced to set the workingdir to `/app`. e.g. I could do something like this: `dotnet publish -p ../myapp/project.json -o ./ && ./myapp`

I am mostly requesting it for the ability to build a project that is in a different directory, I don't know that we would allow a filename other than project.json so perhaps it can just be a directory rather than a path to a `project.json`.

**Comment by davidfowl** [comment]
This needs to be just like dnx so that you can point the muxer to the right script so it can find the right version of dnx (if that matters). 

`dotnet --project /app/project.json build`

**Comment by piotrpMSFT** [comment]
You guys are describing two scenarios. @glennc's should already work: `dotnet build {path to project dir}`. @davidfowl's is a new one in that it sets the 'address' of the project context prior to issuing a command. We also need this to find e.g. tools which are defined in a project outside the current one. @livarcocc thoughts?

**Comment by piotrpMSFT** [comment]
We support passing paths to csproj files.
