### ISSUE TITLE
Home for CLI / VS integration tests

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#2123]
@abpiskunov @davidfowl @troydai 

Automated integration tests for the xproj / csproj interoperability scenario require test assets with artifacts that are only obtainable / interpretable via VS (project.json with csproj references, lock files with missing dependencies, fragment file, binaries for csproj projects). 
These tests and test assets cannot live in the CLI repo because it would mean committing dlls and lock files. In addition, it would be hard to maintain VS code and CLI test assets (with binaries) in sync.

Where should these tests live?

**Comment by cdmihai** [comment]
I assume that VS has integration tests for many sample projects. Ideally, the xproj / csproj integration tests should live alongside those, so they can get restored, built with msbuild, etc

**Comment by abpiskunov** [comment]
Yes , we do have integration tests and I could run yours, but there will be a lag for reporting issues in dotnet since we don't update dotnet installer every day in our enlistments. If you are ok with it , I can port your tests

**Comment by cdmihai** [comment]
I propose 2 ways:
- VS should have a lot of xproj/csproj samples that test many scenarios and p2p shapes
- CLI could keep one small sample to guard against regressions. This still means committing the dlls and lock files for it. If VS breaks the format, it won't be that much of a pain to update. Yes, it will get downloaded on each CLI repo clone, but it should be small.

**Comment by piotrpMSFT** [comment]
Why do we need to check in dll's? Unless I'm missreading this code, CLI does not have explicit knowledge of VS. what it has is the ability to have a fragmet.json which describes additional paths at which it might find build/runtime dependencies. These need not be produced by VS and in fact can be the output of other cli-produced projects [with global.json preventing normal p2p behavior].

CLI should not allow VS-specific code to creep in. This is an extensibility model which acknowledges the presence of other build orchestrators and gives them a way of interacting with CLI. We should have tests which validate this contract and not tests that are VS specific.

Why not build a test asset which has e.g. two solutions in one directory. e.g. testasset/p1/global.json, testasset/p2/global.json. Test then copies a fragment.json into one of these and builds both in the right order. This validates CLIs contract while depending on VS to validate its implementation of the same.

**Comment by abpiskunov** [comment]
I think MIhai was not speaking about VS specific dlls, but output dlls for csproj test projects that should be used for dotnet build/publish tests.. In VS, dotnet tools take care about building , restoring everything right, when at runtime you would need to simulate that...

**Comment by cdmihai** [comment]
@piotrpMSFT 

What Anton said :)

The CLI cannot build those test assets, so we would have to build the assets in VS and then commit them in. This would enable us to the test dotnet build being called in the presence of fragment files and guard against regressions.

**Comment by piotrpMSFT** [comment]
Given some recent bugs, I wish we had gotten to this issue :) However, as we're moving to csproj, we're not going to have an opportunity to fix this.
