### ISSUE TITLE
dotnet run passing ` --additionalprobingpath` to standalone app

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2127]
## Steps to reproduce

dotnet run standalone app
## Expected  behavior

It get executed only with arguments passed to `dotnet run` command
## Actual behavior

`--additionalprobingpath` gets passed to standalone app

```
xiaota-mac:Microsoft.AspNetCore.Server.Kestrel.GeneratedCode asplab$ ~/.dotnet/dotnet -v run
Project Microsoft.AspNetCore.Server.Kestrel.GeneratedCode (.NETStandardApp,Version=v1.5) was previously compiled. Skipping compilation.
Running /Users/asplab/Documents/buildAgent/work/169923259d6dcfec/Universe/KestrelHttpServer/tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode/bin/Debug/netstandardapp1.5/osx.10.10x64/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode --additionalprobingpath /Users/asplab/.nuget/packages
Process ID: 82740
Could not resolve SDK directory from [/Users/asplab/Documents/buildAgent/work/169923259d6dcfec/Universe/KestrelHttpServer/tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode/bin/Debg/netstandardapp1.5/osx.10.10-x64]
```
## Environment data

`dotnet --version` output:

```
~/.dotnet/dotnet --version
1.0.0-beta-002113
```

**Comment by pakrym** [comment]
will break any tool that uses dotnet run and arguments

**Comment by brthor** [comment]
Why would this break?

Wouldn't additionalProbingPath be used for any packages which can't be found app local? Which is all of them in the dev scenario?

cc @schellap @Sridhar-MS

**Comment by pakrym** [comment]
Wouldn't app get additionalProbingPath  in args?

**Comment by brthor** [comment]
Okay I see, so the ordering of additionalProbingPath is the issue here?

**Comment by pakrym** [comment]
No, their presence. Lets take `Standalone` app on windows, which will produce `Standalone.exe`, corehost in standalone mode should forward app arguments to app itself and now you get `additionalProbingPath` in `public static void Man(string[] args)`

**Comment by brthor** [comment]
After doing a dotnet build, how could dependencies be resolved without `--additionalProbingPath`?

@schellap @gkhanna79 we talked about this at length yesterday

**Comment by pakrym** [comment]
Via new devruntimecontig.json?

**Comment by brthor** [comment]
Sure, the plan is to move `additionalProbingPath` there, but we still need that information available somehow was the point I was making. I understand what you're saying now. 

Can we track this bug in the devruntimeconfig.json bug?

**Comment by gkhanna79** [comment]
> now you get additionalProbingPath in public static void Man(string[] args)

This shouldnt happen. The argument is only for the host and not passed to the application.

**Comment by pakrym** [comment]
@gkhanna79 isn't corehost in standalone mode just passing all arguments to manages app without reading/filtering anything?

**Comment by brthor** [comment]
dotnet run is using the muxer, not corehost. Not sure if that affects your expectations @pakrym

**Comment by pakrym** [comment]
@brthor no, it runs executable directly. https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-run/RunCommand.cs#L165

**Comment by brthor** [comment]
The fact that you are executing an exe directly is not apparent from your example.

I'm somewhat confused actually, what invocation of dotnet run is failing?

**Comment by piotrpMSFT** [comment]
`dotnet run` should be invoking the muxer with --additionalProbingPath. The muxer should be taking data out of --additionalProbingPath and stripping the parameter from the args which get passed along to the app. Like `--depsfile`, this is an option that is passed to the muxer for its own use and should not get passed along to the app.

@pakrym, is your concern that `dotnet.exe` is passing along the --additionalprobingpath` to the muxer? Or you're concerned about this due to inspection of the invocation site?

**Comment by piotrpMSFT** [comment]
ping

**Comment by schellap** [comment]
First, it looks like the standalone app.exe is run with --additionalprobingpath and not using the muxer.

`/Users/asplab/Documents/buildAgent/work/169923259d6dcfec/Universe/KestrelHttpServer/tools/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode/bin/Debug/netstandardapp1.5/osx.10.10x64/Microsoft.AspNetCore.Server.Kestrel.GeneratedCode --additionalprobingpath /Users/asplab/.nuget/packages`

**Comment by davidfowl** [comment]
That's expected right? It is standalone...

**Comment by schellap** [comment]
@gkhanna79 had it clear in his spec that `--additionalprobingpath` is only for dev scenarios and the muxer will be used to activate the build exe using the `dotnet exec` keyword.

Why would you expect it to be standalone when it isn't published yet with its dependencies next to it?

**Comment by schellap** [comment]
Secondly, how and why did you get the native app.exe if you just did build? Isn't build supposed to just produce the entry.dll and its project dependency dlls?

**Comment by davidfowl** [comment]
> @gkhanna79 had it clear in his spec that --additionalprobingpath is only for dev scenarios and the muxer will be used to activate the build dll using the dotnet exec keyword.

That doesn't make any sense. The muxer only applies for shared framework scenarios, not standalone ones.

> Why would you expect it to be standalone when it isn't published yet, with its dependencies next to it?

Because standalone doesn't mean published. It means everything comes from packages instead of a shared framework.

> Secondly, how and why did you get the native app.exe if you just did build? Isn't build supposed to just produce the entry.dll and its project dependency dlls?

Because when you're standalone, that is, when you have a RID specified, you get a native executable in the build output so that you can run.

PS: This is how things have been working since before the shared framework existed.

**Comment by schellap** [comment]
> Because when you're standalone, that is, when you have a RID specified, you get a native executable in the build output so that you can run.

From where?

**Comment by schellap** [comment]
I mean if dotnet cli is a fully portable app with no rid specific artifacts and build doesn't know about locations of the nuget dependencies how did the native executable appear by just doing build.

**Comment by davidfowl** [comment]
@schellap Are you asking how you specify a RID? The `project.json` file or a command line switch.

**Comment by davidfowl** [comment]
> I mean if dotnet cli is a fully portable app with no rid specific artifacts and build doesn't know about locations of the nuget dependencies how did the native executable appear by just doing build.

That's not what this bug is about. This bug is about standalone applications, not shared ones. When the app is shared there is no executable.

**Comment by schellap** [comment]
No just help me understand where you got the native exe from. That is where the problem is.

**Comment by schellap** [comment]
Cc @blackdwarf

**Comment by schellap** [comment]
As an aside, @piotrpMSFT, for standalone it sounds like we are going to copy `corehost` to run the build output whether it is from the CLI or from the nuget cache. `dotnet build` might eventually copy it from the cache, so I guess hostpolicy should be just copied as well. If build can do that, it doesn't make sense for the host to resolve it out of the cache.

**Comment by schellap** [comment]
@gkhanna79 please sync with @davidfowl and @piotrpMSFT on this one.

**Comment by gkhanna79** [comment]
@davidfowl Do you expect being "portable/shared" or "standalone" be a characteristic that is expected to be known at app build time or app publish time? From what you are describing above, it sounds like it is not a deployment artifact and the app developer would need to know at app build time. Is that correct?

That said, @schellap we did discuss yesterday that we will be able to maintain status quo and support it, given that runtimeconfig.dev.json support is checked in and that will alleviate the need for app invocation (both via the muxer and App.exe)  to specify --additionalProbingPath.

**Comment by piotrpMSFT** [comment]
Closing in favor of #2129.

**Comment by piotrpMSFT** [comment]
Moved to Coresetup repo
