### ISSUE TITLE
dotnet run fails when running from a certain directories

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#214]
# Repro Steps
1. Create a Dockerfile with the following contents
```
FROM buildpack-deps:jessie-scm

RUN echo "deb [arch=amd64] http://tux-devrepo.corp.microsoft.com/repos/dotnet-dev/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list \
 && apt-key adv --keyserver tux-devrepo.corp.microsoft.com --recv-keys 008C0E6C \
 && echo "deb [arch=amd64] http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" > /etc/apt/sources.list.d/llvm.list \
 && wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|apt-key add - \
 && apt-get update \
 && apt-get install -y dotnet

RUN echo "using System;\n \
using System.Diagnostics;\n \
\n \
namespace TestApp\n \
{\n \
    public class Program\n \
    {\n \
        public static void Main(string[] args)\n \
        {\n \
            Console.WriteLine("\""This is a test app"\"");\n \
        }\n \
    }\n \
}" > Program.cs

RUN echo "{\n \
    "\""version"\"": "\""1.0.0-*"\"",\n \
    "\""compilationOptions"\"": {\n \
        "\""emitEntryPoint"\"": true\n \
    },\n \
\n \
    "\""dependencies"\"": {\n \
        "\""Microsoft.NETCore.Runtime"\"": "\""1.0.1-beta-23409"\"",\n \
        "\""System.IO"\"": "\""4.0.11-beta-23409"\"",\n \
        "\""System.Console"\"": "\""4.0.0-beta-23409"\"",\n \
        "\""System.Runtime"\"": "\""4.0.21-beta-23409"\"",\n \
        "\""System.Diagnostics.Process"\"": "\""4.1.0-beta-23409"\"",\n \
    },\n \
\n \
    "\""frameworks"\"": {\n \
        "\""dnxcore50"\"": { }\n \
    }\n \
}" > project.json

RUN mkdir /app/
RUN cp Program.cs /app/
RUN cp project.json /app/
WORKDIR /app/
RUN dotnet restore --runtime ubuntu.14.04-x64

RUN mkdir /app1/
RUN cp Program.cs /app1/
RUN cp project.json /app1/
WORKDIR /app1/
RUN dotnet restore --runtime ubuntu.14.04-x64

RUN mkdir -p /dot/net/
RUN cp Program.cs /dot/net/
RUN cp project.json /dot/net/
WORKDIR /dot/net/
RUN dotnet restore --runtime ubuntu.14.04-x64

RUN mkdir /dotnetapp/
RUN cp Program.cs /dotnetapp/
RUN cp project.json /dotnetapp/
WORKDIR /dotnetapp/
RUN dotnet restore --runtime ubuntu.14.04-x64
```
2. Build the docker image using an Ubuntu.14.04-x64 machine - docker build -t nestedBug .
3. Run the docker image - docker run -it nestedBug
4. Within the docker container run 'dotnet run' from the various application directories

# Actual Results
dotnet run succeeds for the dotnetapp and app1 directories.  When run from other directories it fails with the following error:

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::compare: __pos (which is 18446744073709551615) > this->size() (which is 3)

The same results happen if you 'dotnet publish' the app and then try to execute the app.

# Expected Results
dotnet run should successfully run from all of the directories.

## Note
The dotnet debian package version I had installed was 0.0.1-alpha-20151115-171248-1

**Comment by piotrpMSFT** [comment]
@MichaleSimons, @dleeapho mentioned this might be Debian specific. Have you seen this repro on Ubuntu?

**Comment by MichaelSimons** [comment]
@piotrpMSFT, per my comments, this did repro on both Ubuntu and Debian.  That being said, I pulled the latest dotnet package and the issue no longer repros in either environment.  Based on this, I am closing this issue.
