### ISSUE TITLE
Error publishing on a maching in private domain

### ISSUE THREAD

**Issue by sivagms** [dotnet/cli#2140]
## Steps to reproduce
I'm using this app - https://github.com/aspnet/Performance/tree/dev/testapp/HelloWorldMvc
This app restores and publishes fine on all other machines except on a set of machines that are on a private domain. - Not sure if the domain thing is the issue but just an observation.
Windows server 2012 datacenter.

## Expected  behavior
publish should work.

## Actual behavior
d:\git\Performance\testapp\HelloWorldMvc>D:\Users\INDGAUNT\AppData\Local\Microso
ft\dotnet\cli\bin\dotnet.exe publish -c release
Publishing HelloWorldMvc for .NETStandardApp,Version=v1.5/win7-x64
Compiling HelloWorldMvc for .NETStandardApp,Version=v1.5
D:\Users\INDGAUNT\AppData\Local\Microsoft\dotnet\cli\bin\dotnet.exe compile-csc
@d:\git\Performance\testapp\HelloWorldMvc\obj\release\netstandardapp1.5\dotnet-c
ompile.rsp returned Exit Code 1
d:\git\Performance\testapp\HelloWorldMvc\error CS0041: Unexpected error writing
debug information -- 'Unable to cast COM object of type 'System.__ComObject' to
interface type 'Microsoft.Cci.ISymUnmanagedWriter5'. This operation failed becau
se the QueryInterface call on the COM component for the interface with IID '{DCF
7780D-BDE9-45DF-ACFE-21731A32000C}' failed due to the following error: No such i
nterface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).'

Compilation failed.
    0 Warning(s)
    1 Error(s)

d:\git\Performance\testapp\HelloWorldMvc>D:\Users\INDGAUNT\AppData\Local\Microso
ft\dotnet\cli\bin\dotnet.exe --version
.NET Command Line Tools (1.0.0-beta-001718)

Product Information:
Version:     1.0.0-beta-001718
Commit Sha:  5b0afe7880

Runtime Environment:
OS Name:     Windows
OS Version:  6.3.9600
OS Platform: Windows
Runtime Id:  win81-x64

## Environment data
`dotnet --version` output:

**Comment by blackdwarf** [comment]
@sivagms does this still repro with the latest bits?

**Comment by sivagms** [comment]
this doesn't repro anymore (had installed few things that Gaurav mentioned). closing this.
