### ISSUE TITLE
Stand alone executables are published for the platform they are produced on, not the target

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#2141]
When performing a stand alone publish, the stand alone executable is published for whatever platform you are publishing from. For example, publishing for Ubuntu.14.04-x64 from my Windows machine, I still end up with myapp.exe, not just 'myapp'. @blackdwarf sees the same thing publishing for Windows from OSX, he ends up with 'myapp', not 'myapp.exe'.

To reproduce, publish Windows for Ubuntu, or on OSX/Ubuntu for Windows.

**Comment by blackdwarf** [comment]
@billwert is correct, this is a behavior that I've seen.

**Comment by piotrpMSFT** [comment]
Would it be possible to get a repo with a repro? We'll fix the bug, but having a project that captures what you're seeing will make the team much more able to write a unit test and fix the bug...

**Comment by gkhanna79** [comment]
@brthor and @Sridhar-MS mentioned in a discussion today that this is a known issue for RC2.

**Comment by GuardRex** [comment]
Are these two related? https://github.com/dotnet/cli/issues/317
