### ISSUE TITLE
Publish should clean the output folder

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#2142]
If you publish into a folder that has binaries in it, the existing binaries aren't removed. For example, if you had a build system publishing to a specified folder with --output, were publishing stand alone, and switch to shared framework, your output folder will still have all the stand alone binaries in it.

**Comment by blackdwarf** [comment]
@billwert hm, looks like a switch to me, something like `--remove-existing` or similar. Similar to the way publish in VS works, you have that little checkbox.

**Comment by piotrpMSFT** [comment]
Moved to SDK repo
