### ISSUE TITLE
Compilation errors include an error that the compiler returned Exit Code 1. This isn't helpful to the developer.

### ISSUE THREAD

**Issue by barrytang** [dotnet/cli#2146]
## Steps to reproduce

1) Make a new .NET Core CLI project
2) Introduce some syntax error into Program.cs (missing ;, whatever.)
3) Build

You're left with your expected error in the error list, along with this:

`Error  C:\Program Files\dotnet\sdk\1.0.0-beta-002071\dotnet.exe compile-csc @<pathtoproj>\obj\Debug\netstandardapp1.5\dotnet-compile.rsp returned Exit Code 1 FeedbackPreparer C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets 206 Severity Code Description Project File Line Suppression State`
## Environment data

`dotnet --version` output:

**Comment by barrytang** [comment]
Opened on behalf of Bill Wert.

**Comment by Petermarcu** [comment]
on build 2117 I get this:
c:\dotnet\dotnet.exe compile-csc @c:\samples\App2\obj\Debug\netstandard1.5\dotnet-compile.rsp returned Exit Code 1
c:\samples\App2\Program.cs(9,46): error CS1002: ; expected

**Comment by piotrpMSFT** [comment]
What is the bug here? `dotnet compile` issues several sub-commands like `dotnet resgen` and `dotnet compile-csc`. Knowing which one failed is useful, particularly when you choose a non-default compiler. What is the desired/expected output?

**Comment by billwert** [comment]
The desired/expected output is that whatever contract you have with VS doesn't cause VS to show an error message stating that the compiler returned 1. It's entirely unhelpful to the developer.

The error is coming from dotnet compile-csc as shown in the text @Petermarcu and I (through @barrytang, thanks Barry!) put in the issue.

**Comment by piotrpMSFT** [comment]
Fixed in preview3.
