### ISSUE TITLE
Windows MSI installer

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#215]
To do list
- [X] Make sure no machine restart is required to update the environment variables (%patth%, %dotnet_home%).
- [ ] Make the MSI upgradable.
- [X] Enable machine wide installation for all users
- [ ] Chain VC++ redistributable.
- [X] Add dependency provider keys
- [X] Add registry keys to detect installation

**Comment by piotrpMSFT** [comment]
x86 is a non-goal for now

**Comment by brthor** [comment]
Other work items are tracked #195 #251
