### ISSUE TITLE
Dotnet run should not pass ` --additionalprobingpath` to net45 apps

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2152]
## Steps to reproduce
1. Build `net451` app that dumps its argumets
2. `dotnet run` it

## Expected  behavior
Managed app gets no arguments

## Actual behavior
Managed app gets ` --additionalprobingpath` argument

/cc @pranavkm @brthor @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@schellap

**Comment by schellap** [comment]
What is a net451 app? I have this in my project.json and I couldn't repro it.

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-23930"
    }
  },
  "frameworks": {
    "netstandardapp1.5": {}
  }
}
```

**Comment by brthor** [comment]
@schellap set framework to `net451` and it will target desktop

**Comment by schellap** [comment]
Well, in that case corehost is not even involved.

**Comment by davidfowl** [comment]
This is blocking us. It's a bug in `dotnet-run`, not corehost. It always passes in those flags regardless of target framework, we just need to check.

**Comment by Petermarcu** [comment]
Is this one complete now that the linked PR is merged?
