### ISSUE TITLE
dotnet restore will only use a local NuGet.Config

### ISSUE THREAD

**Issue by nuevoalex** [dotnet/cli#2154]
## Steps to reproduce

Following the steps from https://dotnet.github.io/getting-started/

get to the `dotnet restore` step and either run

`dotnet restore`

or

`dotnet restore --configfile [NUGET CONFIG FILE PATH]`

## Expected  behavior

The resulting restore call includes the default roaming and/or the explicitly specified NuGet.Config and its feeds.

## Actual behavior

The dotnet restore only uses the project local NuGet.Config file and the feeds specified there.

## Environment
`dotnet --version` output:

.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64

**Comment by piotrpMSFT** [comment]
your version output seems to be dotnet, but the bug claims that you're using dnu. is the command in question `dnu restore` or `dotnet restore`?

**Comment by nuevoalex** [comment]
My bad, editing now. It should be dotnet. I've been switching back and forth to test.

**Comment by emgarten** [comment]
Only the config file passed in is used. To use multiple config files add them to the directory hierarchy above the project so that they will all be picked up along with the machine wide config.
https://github.com/NuGet/Home/issues/2087

**Comment by nuevoalex** [comment]
@emgarten The bug I'm observing is that:

The config file passed in is NOT used

and

the machine wide config is not used.

Whether or not there is a local config or config files in the directory hierarchy above the project does not seem to affect those issues.

**Comment by emgarten** [comment]
> The dotnet restore only uses the project local NuGet.Config file and the feeds specified the

Which file does this refer to then? It will use the first one it finds the project directory when using ``--config-file``?

Are you able to repro this with the latest build?

**Comment by nuevoalex** [comment]
> Which file does this refer to then? It will use the first one it finds the project directory when using --config-file?

It will find and use the config file in the directory which I am running `dotnet restore` from. I want it to find my default machine wide config as this is where all the feeds and authentication information my projects need is kept.

I am able to repro this with the latest MSI version on my work computer but not from my home computer where it correctly pulls both the project local config and the machine wide %AppData% config.

**Comment by emgarten** [comment]
The correct behavior for --configfile is that only that file will be used. Would you provide more repro steps to help track this down?

* dotnet --version output
* Working directory
* dotnet restore arguments passed in 
* Config file paths in and above the project, project layout
* Summary output from restore containing the list of config files used

**Comment by nuevoalex** [comment]
## dotnet --version output

.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 Runtime Id:  win7-x64

## Working Directory

 Directory of C:\Users\achapman\Desktop\test

03/30/2016  06:04 PM    <DIR>          .
03/30/2016  06:04 PM    <DIR>          ..
03/30/2016  06:04 PM               292 NuGet.Config
03/30/2016  06:04 PM               214 Program.cs
03/30/2016  06:04 PM               241 project.json
03/30/2016  06:46 PM           240,519 project.lock.json
               4 File(s)        241,266 bytes
               2 Dir(s)  365,062,574,080 bytes free

## dotnet restore with no arguments

`dotnet restore`

log  : Restoring packages for C:\Users\achapman\Desktop\test\project.json...
info : Committing restore...
log  : Restore completed in 950ms.

NuGet Config files used:
    C:\Users\achapman\Desktop\test\NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json


## dotnet restore with my default config passed in explicitly

`dotnet restore --configfile C:\Users\achapman\AppData\Roaming\NuGet\NuGet.Config`

log  : Restoring packages for C:\Users\achapman\Desktop\test\project.json...
info : Committing restore...
log  : Restore completed in 850ms.

NuGet Config files used:
    C:\Users\achapman\Desktop\test\NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json

**Comment by nuevoalex** [comment]
FWIW my original behavior on initial dotnet CLI install was that `dotnet restore` raised an `Exception has been thrown by the target of an invocation` error.

I temporarily commented out parts of my default config which made that problem go away but have since had this problem.

**Comment by emgarten** [comment]
> Version: 1.0.0-beta-001598

The latest version is ``1.0.0-beta-002202``. Are you able to repro the issue after updating?

**Comment by nuevoalex** [comment]
I'll try that tomorrow and update here. Thanks for the help so far!

**Comment by nuevoalex** [comment]
This problem does seem to be resolved in the latest version. I'm now getting authentication errors for my private feeds but that's another issue.

Thanks!
