### ISSUE TITLE
002125 -> 002136 - no binary is produced on publish

### ISSUE THREAD

**Issue by colemickens** [dotnet/cli#2155]
I was on `dotnet-dev-1.0.0-beta-002125`. Thing were working. I could publish and would get a directory with `/bin/Release/netcoreapp1.0/ubuntu.14.04-x64/MY_EXECUTABLE` (or maybe `/bin/Release/netcoreapp1.0/ubuntu.14.04-x64/publish/MY_EXECUTABLE`, I think that was a different bug)

I upgraded to `dotnet-dev-1.0.0-beta-002136` and now I no longer get a `ubuntu.14.04-x64` directory, and I no longer get `MY_EXECUTABLE`. Instead I get `MY_EXECUTABLE.dll` which I can't launch.

**Comment by alfhenrik** [comment]
I'm having the same issue running `dotnet publish --runtime win81-x64 --framework netcoreapp1.0 --configuration Release` on OSX. Run the same command on my Windows box works just fine.

`project.json`
```
"dependencies": {
        "Microsoft.Extensions.Logging.Console": "1.0.0-*",
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
        "Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.Core": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
        "System.Runtime.Serialization.Primitives": "4.1.0-*",
        "System.Xml.XDocument": "4.0.11-*"
    },
    
    "frameworks": {
        "net451": {
            "dependencies": {
                "System.IO.FileSystem.Primitives": "4.0.0"
            }
        },
        "netcoreapp1.0": {
            "dependencies": {
                "NETStandard.Library": "1.5.0-*"
            },
            "imports": [
                "dnxcore50"
            ]
        }
    },
    
    "runtimes": {
        "win81-x64": {},
        "osx.10.11-x64": {}
    }
```

```
.NET Command Line Tools (1.0.0-beta-002169)

Product Information:
 Version:     1.0.0-beta-002169
 Commit Sha:  164a235a20

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

```
.NET Command Line Tools (1.0.0-beta-002167)

Product Information:
 Version:     1.0.0-beta-002167
 Commit Sha:  9c67627b43

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by colemickens** [comment]
I just moved to 002196 and added `"runtimes": { "ubuntu.14.04-x64": {} }` and I seem to be back to as I was before. I get the ubuntu.14.04-x64 directory and an executable inside.

**Comment by colemickens** [comment]
Relevant: https://github.com/dotnet/cli/issues/1642

Is that behavior desirable in `publish` scenarios though? I thought `publish` was meant to produce output that was pretty standalone?

**Comment by davidfowl** [comment]
Yes this is by design. You now have to add runtimes to the `project.json` to get the old behavior or use the `dotnet restore --infer-runtimes`.

**Comment by colemickens** [comment]
Alright. I'd close this but it seems like @alfhenrik is still having issues despite specifying the runtime as a cli option.

**Comment by alfhenrik** [comment]
I've got a workaround for now, so I have no problem with this being closed.

**Comment by colemickens** [comment]
I don't know what cli version changed this, but I'm back to not getting a binary, even with the RID specified in project.json.

**Comment by colemickens** [comment]
Looks like this was caused  by removing this from my dependencies:

```
"NETStandard.Library": "1.5.0-*"
```

and replacing it with:

```
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
```

removing the `"type": "platform"` has restored my desired behavior.
