### ISSUE TITLE
Guidance for migrating DNX --> BCL APIs

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#216]
We want folks to move off of IApplicationEnvironment as part of move to CLI. This issue tracks recommended replacement APIs.

|  IApplicationEnvironment   |   BCL   |   Notes   |
|-------------------------|----|-------------|
|  ApplicationName |    |  dotnet/corefx#1784, dotnet/corefx#4146, dotnet/corefx#4314   |
|  ApplicationVersion |    |  Replacement not found.  |
|  ApplicationBasePath |  AppContext.BaseDirectory   |   |
|  Configuration |  N/A  |  Deprecated  |
|  RuntimeFramework |  RuntimeInformation.FrameworkDescription  |  https://github.com/dotnet/corefx/issues/4137  |

|  IApplicationShutdown|   BCL   |   Notes   |
|-------------------------|----|-------------|
|  RequestShutdown  |   Environment.Exit()  |  |
|  ShutdownRequested  |    |  Replacement not found.  |

CC @davidfowl, @anurse, @weshaggard

**Comment by weshaggard** [comment]
I've updated the table with a couple more options. As for GetEntryAssembly it isn't added yet but we do have plans to include it.

**Comment by piotrpMSFT** [comment]
Thanks Wes. We have two members that have no path forward right now. What are your thoughts? Are these capabilities we can add in BCL?

**Comment by davidfowl** [comment]
I've been laughing these into the BCL where it makes sense. Some of them have been taking longer than expected go in though

**Comment by piotrpMSFT** [comment]
I've linked the issues you created where I ran across them. Can you add any others?

**Comment by AlexGhiondea** [comment]
In the process of implementig/moving ApplicationName to CoreFx I have ran into a bunch of questions around the actual scenario where this API would be necessary.

So far, as I have outlined [here](https://github.com/dotnet/corefx/issues/4314#issuecomment-157537025), the only scenario where this would be useful are hosting scenarios. 
And even in those cases, the relationship between host and hosted app defines how this property is going to be used. 

Are there any other scenarios than the hosting one where this API can be used? 

/cc @piotrpMSFT @davidfowl

**Comment by AlexGhiondea** [comment]
@piotrpMSFT can you help identify the scenarios where AppContext.ApplicationName would be used? As it stands today there is only 1 scenario that would benefit from it and all use cases in that scenario are somewhat domain specific.

**Comment by piotrpMSFT** [comment]
@brthor @anurse @krwq @Sridhar-MS @livarcocc 

Adding some more folks who can comment. Display name is the most obvious, though I can imagine using this to find paths to related artifacts [exe/dll/deps/pdb] as well.

**Comment by piotrpMSFT** [comment]
@glennc as well. Glenn, do you have context on how ApplicationName was used in DNX?

**Comment by AlexGhiondea** [comment]
@piotrpMSFT I think the way the ApplicationName would be used would depend on the contract between the host and the app. If the host does not put in that value something that the app expects, the app won't be able to use it.

**Comment by blackdwarf** [comment]
I believe this is not needed anymore so will close. If any if you disagree, please reopen.
