### ISSUE TITLE
`dotnet build` claims `dotnet restore` is necessary even when it is not

### ISSUE THREAD

**Issue by brendandixon** [dotnet/cli#2164]
## Steps to reproduce

This occurs for my project (see attached) running in a Docker Ubuntu 14.04 container under Mac OS X (El Capitan). I run `dotnet restore` which appears to successfully complete. A subsequent `dotnet build`, which compiles successfully, claims I need to run `dotnet restore.`
## Expected  behavior

`dotnet build` only complains when it should.
## Environment data

`dotnet --version` output:
root@2d9efeeca938:~/osx/portable/protocols# dotnet --version
.NET Command Line Tools (1.0.0-dev-001698)

Product Information:
 Version:     1.0.0-dev-001698
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

**Comment by blackdwarf** [comment]
@brendandixon does this repro on the latest (Preview 2) tooling?

**Comment by piotrpMSFT** [comment]
Looks like the repro is gone. However, I did some tests in preview3 and did not see this issue come up.
