### ISSUE TITLE
The output from `dotnet build` snakes instead of having correct line breaks

### ISSUE THREAD

**Issue by brendandixon** [dotnet/cli#2165]
## Steps to reproduce
- Run `dotnet build` in a Docker container under Mac OS X.
## Expected  behavior

One line per line.
## Actual behavior

The lines snake across the screen. Line breaks are not honored. New lines do not begin at the left edge. Etc. I've attached a screen shot.
![screen shot 2016-03-31 at 10 21 29 am](https://cloud.githubusercontent.com/assets/305205/14184504/5e3a4bf4-f72a-11e5-9c12-a361bd845b4c.png)
## Environment data

`dotnet --version` output:
root@2d9efeeca938:~/osx/portable/protocols# dotnet --version
.NET Command Line Tools (1.0.0-dev-001698)

Product Information:
 Version:     1.0.0-dev-001698
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

**Comment by brthor** [comment]
I have seen this in docker as well.

**Comment by piotrpMSFT** [comment]
I've not seen repros of this since moving to MSBuild. Just failed to repro with 1.0.0-rc3. Let us know if you're seeing this on the new tools implementation by opening a new issue.
