### ISSUE TITLE
Dev channel CLI package acquisition fails

### ISSUE THREAD

**Issue by nattress** [dotnet/cli#2166]
The CLI script to obtain dev channel packages from Master fails. With x64 it discovers 1.0.1.001606 is latest but that blob doesn't exist.

scripts\obtain\install.ps1 -Verbose -Channel dev -Architecture x64

Verbose output:

VERBOSE: dotnet_install: Get-Azure-Channel-From-Channel -Channel "dev"
VERBOSE: dotnet_install: Get-CLIArchitecture-From-Architecture -Architecture "x64"
VERBOSE: dotnet_install: Get-Specific-Version-From-Version -AzureFeed
"https://dotnetcli.blob.core.windows.net/dotnet" -AzureChannel "dev" -CLIArchitecture "x64" -Version "Latest"
VERBOSE: dotnet_install: Get-Latest-Version-Info -AzureFeed "https://dotnetcli.blob.core.windows.net/dotnet"
-AzureChannel "dev" -CLIArchitecture "x64"
VERBOSE: GET https://dotnetcli.blob.core.windows.net/dotnet/dev/dnvm/latest.win.x64.version with 0-byte payload
VERBOSE: received 59-byte response of content type application/octet-stream
VERBOSE: dotnet_install: Get-Version-Info-From-Version-Text -VersionText
"﻿399b3ee4700b46dcf5312c71fcfd69622520f9ee
1.0.1.001606
"
VERBOSE: dotnet_install: Get-Download-Links -AzureFeed "https://dotnetcli.blob.core.windows.net/dotnet"
-AzureChannel "dev" -SpecificVersion "1.0.1.001606" -CLIArchitecture "x64"
VERBOSE: dotnet_install: Constructed payload URL:
https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/1.0.1.001606/dotnet-dev-win-x64.1.0.1.001606.zip
VERBOSE: dotnet_install: Resolve-Installation-Path -InstallDir "<auto>"
VERBOSE: dotnet_install: Get-User-Share-Path
VERBOSE: dotnet_install: InstallRoot: C:\Users\simonn\AppData\Local\Microsoft\dotnet
VERBOSE: dotnet_install: Is-Dotnet-Package-Installed -InstallRoot
"C:\Users\simonn\AppData\Local\Microsoft\dotnet" -RelativePathToPackage "sdk" -SpecificVersion "1.0.1.001606"
VERBOSE: dotnet_install: Is-Dotnet-Package-Installed: Path to a package:
C:\Users\simonn\AppData\Local\Microsoft\dotnet\sdk\1.0.1.001606
VERBOSE: dotnet_install: .NET SDK installed? False
dotnet_install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/1.0.1.001606/dotnet-dev-win-x64.1.0.1.001606.zip
VERBOSE: GET
https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/1.0.1.001606/dotnet-dev-win-x64.1.0.1.001606.zip
with 0-byte payload
Invoke-WebRequest : BlobNotFoundThe specified blob does not exist.

**Comment by krwq** [comment]
Seems like some versioning changes did not make it to master:
```
399b3ee4700b46dcf5312c71fcfd69622520f9ee
1.0.1.001606
```
this should have nuget version

also I can't see any folders with nuget versions in azure. the last uploaded version seem to be  1.0.1.001808 and seems like it didn't update the latest.version file.

**Comment by krwq** [comment]
This should work right now

**Comment by Sridhar-MS** [comment]
thanks @krwq for doing this.
