### ISSUE TITLE
Can't pass "a.cs" as argument to my console app via dotnet run

### ISSUE THREAD

**Issue by ljw1004** [dotnet/cli#2173]
## Steps to reproduce

Do "dotnet new", "dotnet restore", then write this code inside Main:
```csharp
foreach (var s in args) Console.WriteLine(s);
```
Now run it in two different ways:
```
dotnet run -- hello world
dotnet run -- Program.cs
```

## Expected  behavior

The first run should print "hello world" on two separate lines.
The second run should print "Program.cs"

## Actual behavior

The first run works fine.

The second run gives an error "Not found - d.cs"

Basically, I need a rock-solid reliable way of passing command-line arguments to my utility, one that isn't subject to the whim of dotnet's command-line parsing. I think that "--" should mean that everything after that gets passed in as `string[] args` to my console app. I think that `dotnet run -h` should document this fact.

## Environment data
`dotnet --version` output: 1.0.0-beta-002133 on OSX

**Comment by blackdwarf** [comment]
This does not repro for me on the latest version of the tooling. Closing. If you find it still repros, please reopen.
