### ISSUE TITLE
dotnet pack produces a zip with no read-permissions on its file contents

### ISSUE THREAD

**Issue by ljw1004** [dotnet/cli#2175]
## Steps to reproduce

`dotnet new` then `dotnet restore` then `dotnet build` then `dotnet pack`

Go into the `bin/Debug` directory and `unzip Project.1.0.0.nupkg`

Try to view the contents of the nuspec: `more Project.nuspec`
## Expected  behavior

It should show me the contents of the file
## Actual behavior

It says `Project.nuspec: Permission denied`
## Rationale

I'm working on OSX. I need a way to inspect the contents of the nupkg that has been generated. Currently, the permission bits of the nuspec inside the nupkg zip file are "------". I have to do `chmod +rw Project.nuspec` to make the file readable. It's pretty unconventional to have to do this. You should create a zip which has the correct permissions from the get-go.
## Environment data

`dotnet --version` output: 1.0.0-beta-002133 on OSX

**Comment by blackdwarf** [comment]
Moving this to Nuget/Home, but yes, this is still reproing.
