### ISSUE TITLE
dotnet build -n doesn't build native

### ISSUE THREAD

**Issue by ljw1004** [dotnet/cli#2176]
## Steps to reproduce

`dotnet new` then `dotnet restore` then `dotnet build` then `dotnet build -n`

## Expected  behavior

It should do a native build

## Actual behavior

It doesn't do a native build! It merely says
```
Project t (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation
```
Also, the bin/Debug directory doesn't contain any native output files.

## Environment data
`dotnet --version` output: 1.0.0-beta-002133 on OSX

**Comment by brthor** [comment]
`native` binaries are placed in a native subdirectory in build output, possibly in a rid specific folder (not sure)

**Comment by ljw1004** [comment]
No directories contain any native files anywhere when I do this.

**Comment by cdmihai** [comment]
See #1041

**Comment by blackdwarf** [comment]
This is not applicable anymore, since building native binaries has been decoupled from the CLI.
