### ISSUE TITLE
CoreHost reads env variable ProgramFiles

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#2179]
This works because of:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa384274(v=vs.85).aspx

Instead, this should come from:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx

**Comment by piotrpMSFT** [comment]
@schellap I'm closing this issue. If still necessary, please reopen in core-setup.
