### ISSUE TITLE
What is the recommended way to create portable tests?

### ISSUE THREAD

**Issue by hal-ler** [dotnet/cli#2183]
## Steps to reproduce

The project.json files of the unit tests specify `netstandard1.5` as the framework without any specific runtime (code is meant to be portable and I would prefer having not to repeat a large list of runtimes in every test-related project.json).

Run `dotnet test` in the test project folder.

## Expected  behavior

Test runs as previously.

## Actual behavior

`No executable found matching command "dotnet-test-xunit"`

## Environment data
`dotnet --info` output:

`.NET Command Line Tools (1.0.0-beta-002175)`

`Product Information:`
 `Version:     1.0.0-beta-002175`
 `Commit Sha:  429eb93cd9`

`Runtime Environment:`
 `OS Name:     Windows`
 `OS Version:  10.0.10586`
 `OS Platform: Windows`
 `RID:         win10-x64`

Using `netcoreapp1.0` as framework with `--infer-runtimes` would solve it (without it I get the same error), but I understood that `--infer-runtimes` is a temporary solution and should be avoided.

**Comment by natemcmaster** [comment]
@hal-ler your project needs to be a "runnable" tfm, i.e. `netcoreapp1.0`. Simplest way to do this is run `dotnet new` and then add testRunner and dotnet-test-xunit to project.json.

```
// project.json
{
    "testRunner": "xunit",
    "dependencies": {
       "dotnet-test-xunit": "1.0.0-*",
     ...
     the rest of the stuff from dotnet-new

```

If you want to share test code between projects, this can be [in a library](https://github.com/aspnet/DependencyInjection/tree/d3359dfc540a123f1a687c75aa97ece296268e4a/src/Microsoft.Extensions.DependencyInjection.Specification.Tests), but the actual runner needs to be in a `netcoreapp1.0` [project](https://github.com/aspnet/DependencyInjection/blob/d3359dfc540a123f1a687c75aa97ece296268e4a/test/Microsoft.Extensions.DependencyInjection.Tests/project.json#L11). Example of this: https://github.com/aspnet/DependencyInjection

Running tests on a true, library only project (i.e. `netstandard1.5` only) is not currently supported as far as I know. In theory, this scenario is the same as https://github.com/dotnet/cli/issues/2645

**Comment by hal-ler** [comment]
Thank you very much for the clarifications. I see that in the latest versions using`"type": "platform"` in the dependencies with `netstandardapp1.0` creates portable apps. This can also be a solution to #2201 then.

**Comment by blackdwarf** [comment]
This issue seems to be resolved. Closing.
