### ISSUE TITLE
xUnit CoreCLR runner doesn't handle xunit config properly

### ISSUE THREAD

**Issue by onovotny** [dotnet/cli#2184]
The xunit runner should not parse the xunit config from the command line. It should use the following logic to determine the correct config file for the assembly:

https://github.com/xunit/visualstudio.xunit/blob/master/xunit.runner.visualstudio.testadapter/VsTestRunner.cs#L228-L248

This change should happen in the CommandLine.cs in the Parse method. Around line 100.

**Comment by piotrpMSFT** [comment]
The `dotnet-test-xunit` runner no longer exists.
