### ISSUE TITLE
Key 417A0893 can't be retrieved from keyserver for apt

### ISSUE THREAD

**Issue by kkokosa** [dotnet/cli#2189]
## Steps to reproduce

During adding the new apt-get feed:

`sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893`
## Actual behavior

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.P0TjF2Xu2x --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
gpgkeys: key 417A0893 can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```
## Environment data

`uname -a` output:

`Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux`

`curl apt-mo.trafficmanager.net --head` output (besides being behind corporate proxy):

```
HTTP/1.1 200 OK
Date: Fri, 01 Apr 2016 10:58:11 GMT
Server: Apache/2.4.7 (Ubuntu)
Last-Modified: Mon, 29 Sep 2014 19:32:50 GMT
ETag: "2cf6-50439550f3c1c"
Accept-Ranges: bytes
Content-Length: 11510
Vary: Accept-Encoding
Content-Type: text/html
```

And `gpg --keyserver hkp://apt-mo.trafficmanager.net -v --list-keys` output:

`gpg: using PGP trust model`

And `more /etc/apt/sources.list.d/dotnetdev.list` output:

`deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main`

**Comment by alexbfr** [comment]
Same problem here:

```
vagrant@redrock:/home/vagrant$ sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.OJzlZm8c7n --no-auto-check-trustdb --trust-model always --k
eyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/ansible-ansible.gpg --keyring /etc/apt/trusted.gpg
.d/apt.postgresql.org.gpg --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

`uname -a:`
`Linux redrock 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

`curl apt-mo.trafficmanager.net --head`
```
HTTP/1.1 200 OK
Date: Wed, 06 Apr 2016 14:21:48 GMT
Server: Apache/2.4.7 (Ubuntu)
Last-Modified: Mon, 29 Sep 2014 19:32:50 GMT
ETag: "2cf6-50439550f3c1c"
Accept-Ranges: bytes
Content-Length: 11510
Vary: Accept-Encoding
Content-Type: text/html

```

**Comment by manu-silicon** [comment]
Could we get this fixed? This actually prevents installation of .NET Core in most companies that disallow anything outgoing on something else than http/https protocol. Usually there is a way to retrieve the key over port 80, checkout how mono does their key retrieval:

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
```

**Comment by akoeplinger** [comment]
Since keyservers are synchronizing keys you can actually use any other keyserver like the Ubuntu one for getting the MS key:

`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893`

I agree that it's a good idea to switch the docs for apt-mo.trafficmanager.net to port 80 too (on Mono we did this because users were constantly running into firewall issues).

**Comment by blackdwarf** [comment]
Is this still reproing? I'm not having any problems obtaining the key server these days.

**Comment by akoeplinger** [comment]
@blackdwarf if the network doesn't allow outgoing connections to port 11371 (the default for HKP) then the instructions still fail. Given how often this is the case we switching to `hkp://host:80` on Mono and haven't heard a complaint since.

**Comment by AdrianBathurst** [comment]
failed:
`sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893`

worked:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893`

**Comment by shanselman** [comment]
I'm hitting this from a hotel in Denmark right now @blackdwarf. Seems like it's reasonable to change the instructions to something that uses Port 80. Is there any reason NOT to?

**Comment by blackdwarf** [comment]
@shanselman not that I see, no.

**Comment by shanselman** [comment]
OK, @blackdwarf can you update the dot.net site instructions?

**Comment by huchim** [comment]
In my case I needed to configure my corporate proxy and add the modifier -E in order to download the key.

export http_proxy="http://<proxy>:<port>"
sudo -E apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893

Thanks @AdrianBathurst.

**Comment by ZackTech** [comment]
I have enetered this command on Ubuntu16.04.1 Desktop

 sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'

and sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

And got gpgkeys: key 417A0893 partially retrieved (probable corrupt)
gpg: no valid OpenPGP data found

Is this something that can be fixed?
Does .Net Core only work on 64bit machines?

**Comment by piotrpMSFT** [comment]
@blackdwarf will this be fixed with the next dot.net site refresh?

**Comment by blackdwarf** [comment]
Yep, the PR is merged and it will be visible next week with the overall website refresh.

**Comment by blackdwarf** [comment]
This is now done and the new instructions are on the website. Closing down.
