### ISSUE TITLE
Support Multiple Test Frameworks

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#219]
We will be adding a top-level TestRunner(s) property to project.json to allow for folks to select the runners that should be executed when they *dotnet test*. I don't see any reason why folks could not use multiple runners/frameworks in a given project [xunit + nunit, for example]. Supporting this, however, means that the property would be an array of 0+ elements:

```
{
    TestRunners: ["xunit.runner.dotnet", "nunit.runner.dotnet"]
}
```

The common scenario, however, will be a single runner, making the array syntax a bit of overhead. What do folks think?

/cc @davidfowl @anurse @brthor @Sridhar-MS @livarcocc @krwq @blackdwarf

**Comment by anurse** [comment]
I figured someone just needed to say it ;P. Let's go with one, and we can always expand later. It's easy to have the test runner property be a single string now and add support for it being an array later.

As for command line arguments, I think we should work like DNX commands worked, just add the command line arguments to the string that is used for the runner. For example:

```json
{
    "test": "xunit.runner.dotnet --someoption somevalue"
}
```

What if we used the existing `scripts` section to do this? In DNX we supported arbitrary commands for simple lifecycle events, and while `dotnet` does not support this yet, I'm adding it in now:

```json
{
    "scripts": {
        "precompile": [ "echo About to compile...", "echo Preparing to compile...", "echo Now engaging compiler" ]
    }
}
```

What if we added a `test` script option? The tricky thing there is figuring out how to treat the value. Normally, the scripts in this section are shell commands, but for test we want it to identify a package dependency that has the entry point...

**Comment by piotrpMSFT** [comment]
okie, I'm making this a single-runner-per-project. Thanks for inptu!

**Comment by thirkcircus** [comment]
@piotrpMSFT , sorry to resurrect an old issue.
I have used different test frameworks within a single test project several times.  I tend to write mostly bdd style tests (mspec) but sometimes i'll also add in (for eg) xunit if I need theories or approvaltests for comparing result snapshots.

Is dotnet test supporting multiple test frameworks per project likely to happen at all or should i just create separate projects per test framework?

cheers

**Comment by piotrpMSFT** [comment]
@thirkcircus let's ask the @dotnet/vstest folks!
