### ISSUE TITLE
Missing string replacement on Mac .NET cli installer {version}

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2192]
<img width="614" alt="screen shot 2016-04-01 at 8 36 04 am" src="https://cloud.githubusercontent.com/assets/9561583/14211978/a40cb89a-f7e5-11e5-85f7-153d68152164.png">

{version} should be replaced with the latest version.

**Comment by slackmoehrle** [comment]
Also, here:

![screen shot 2016-04-01 at 11 45 30 am](https://cloud.githubusercontent.com/assets/7491758/14212099/49b46e0a-f7ff-11e5-887b-fe3a2c0257e4.png)

**Comment by mellinoe** [comment]
Looks like it will be fixed by https://github.com/dotnet/cli/pull/2163

@Sridhar-MS

**Comment by Sridhar-MS** [comment]
yup
