### ISSUE TITLE
dotnet restore Unrecognized option '--infer-runtimes'

### ISSUE THREAD

**Issue by slackmoehrle** [dotnet/cli#2193]
## Steps to reproduce
(jtsm @ 15 ~/.vscode/extensions/ms-vscode.cpptools-0.4.2)  $ dotnet restore --configfile NuGet.Config --infer-runtimes
Specify --help for a list of available options and commands.
error: Unrecognized option '--infer-runtimes'
(jtsm @ 15 ~/.vscode/extensions/ms-vscode.cpptools-0.4.2)  $ dotnet restore --help

Usage: nuget3 restore [arguments] [options]

Arguments:
  [root]  List of projects and project folders to restore. Each value can be: a path to a project.json or global.json file, or a folder to recursively search for project.json files.

Options:
  -h|--help                       Show help information
  -s|--source <source>            Specifies a NuGet package source to use during the restore.
  --packages <packagesDirectory>  Directory to install packages in.
  --disable-parallel              Disables restoring multiple projects in parallel.
  -f|--fallbacksource <FEED>      A list of packages sources to use as a fallback.
  --runtime <RID>                 List of runtime identifiers to restore for.
  --configfile <file>             The NuGet configuration file to use.
  -v|--verbosity <verbosity>      The verbosity of logging to use. Allowed values: Debug, Verbose, Information, Minimal, Warning, Error.
(jtsm @ 15 ~/.vscode/extensions/ms-vscode.cpptools-0.4.2)  $

## Expected  behavior
it works

## Actual behavior
it fails: error: Unrecognized option '--infer-runtimes'

## Environment data
`dotnet --info` output:
$ dotnet --info
Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001598)

**Comment by emgarten** [comment]
@slackmoehrle ``--infer-runtimes`` was added recently and does not exist in 1.0.0-beta-001598. With the build you are using it is on by default and does not need to be passed as a flag. If you upgrade to the latest beta build you will need to pass it in however.

**Comment by blackdwarf** [comment]
I will close this issue since the original issue is of a very, very old build and the `dotnet restore --help` correctly lists out this option.
