### ISSUE TITLE
dotnet build should print out a more helpful message when no lock file is present

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#2199]
## Steps to reproduce

git clone https://github.com/dotnet/cli
cd cli\test\dotnet.Tests
dotnet restore && dotnet test
## Expected  behavior

Failing run  of tests with the message that the referenced P2P dependency was not restored. 
## Actual behavior

...\cli\test\dotnet.Tests>dotnet restore && dotnet test
Project Microsoft.DotNet.InternalAbstractions does not have a lock file.
Project Microsoft.DotNet.InternalAbstractions does not have a lock file.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-beta-002192)

Product Information:
 Version:     1.0.0-beta-002192
 Commit Sha:  47530fce56

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
## Issues
- [ ] Really bad error messages - this is too cryptic what needs to happen to fix it (cc: @blackdwarf)

**Comment by livarcocc** [comment]
This is not a problem with dotnet test. This is a problem of you trying to build a project dependency that has not been restored.

What you are kind of asking here is for transitive restore. I am closing this.

**Comment by brthor** [comment]
I think the restore issues aside there is a UX issue here and we could rename the issue to reflect it.

Basically when you see a project doesn't have a lock file, it might be helpful for the error message to say "go publish that project" 

What do you think @blackdwarf ?

**Comment by livarcocc** [comment]
Just to be clear, this message is coming from Build. dotnet test invokes build before running the tests, so whatever we decide, if we want to improve messaging, we need to do so at dotnet build.

**Comment by brthor** [comment]
Sure, that's reasonable, so how about we reopen this as:
"dotnet build message for unrestored projects is confusing" or something similar @krwq ?

**Comment by blackdwarf** [comment]
@richlander also had this idea. I'm reopening this for tracking and renaming it.

**Comment by blackdwarf** [comment]
The actual message should say something along the lines of "The project ${PROJECT} doesn't have a lock file. Try running dotnet restore first.".

**Comment by brthor** [comment]
I honestly think a path to the project you need to restore would be immensely helpful at alleviating confusion.

**Comment by blackdwarf** [comment]
That's the `${PROJECT}` part above. Anything can go there. We could do: ""The project ${PROJECT} (in ${PROJECT_PATH}) doesn't have a lock file. Try running dotnet restore first."

**Comment by blackdwarf** [comment]
So let's say that this is the message we want: 

> The project ${PROJECT} (in ${PROJECT_PATH}) doesn't have a lock file. Try running dotnet restore in ${PROJECT_PATH}.

Who should change the message?

**Comment by danmosemsft** [comment]
The message also shows twice. If this is your first use of the CLI you likely won't know what a lock file is, and get discouraged.

```
C:\play\hello2>dotnet --info
.NET Command Line Tools (1.0.0-beta-002192)

Product Information:
 Version:     1.0.0-beta-002192
 Commit Sha:  47530fce56

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

C:\play\hello2>dotnet new
Created new C# project in C:\play\hello2.

C:\play\hello2>dotnet build
Project hello2 does not have a lock file.
Project hello2 does not have a lock file.

```

**Comment by marspd** [comment]
I'm doing the Hello World app on the getting started and have this exact problem. Can someone tell me how to resolve this issue when you do get this error message?

**Comment by livarcocc** [comment]
This is still relevant for MSBuild.

Running dotnet build without restoring gives us the error below, which is pretty bad.

```
dotnet build
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/10/16 4:26:28 PM.
     1>Project "/Users/livarcocc/Documents/git/temp/another/another.csproj" on node 1 (Build target(s)).
     1>/Users/livarcocc/Documents/git/cli/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview4-004078/Microsoft.Common.CurrentVersion.targets(1107,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/livarcocc/Documents/git/temp/another/another.csproj]
     1>_CleanRecordFileWrites:
         Creating directory "obj/Debug/".
     1>Done Building Project "/Users/livarcocc/Documents/git/temp/another/another.csproj" (Build target(s)) -- FAILED.

Build FAILED.

       "/Users/livarcocc/Documents/git/temp/another/another.csproj" (Build target) (1) ->
       (GetReferenceAssemblyPaths target) ->
         /Users/livarcocc/Documents/git/cli/artifacts/osx.10.11-x64/stage2/sdk/1.0.0-preview4-004078/Microsoft.Common.CurrentVersion.targets(1107,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/livarcocc/Documents/git/temp/another/another.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.28
```

**Comment by blackdwarf** [comment]
@livarcocc yes, it is still quite relevant.

**Comment by livarcocc** [comment]
Which is why I moved to preview4.

**Comment by blackdwarf** [comment]
Just to add to this, the behavior on a Windows machine is even weirder since it will not fail, but will produce something unexepcted. On Windows, I guess that .NET 4.0 ref assemblies exist or MSBuild ends up using the GAC, so without a restore you will not see an error and an assembly will get produced, but it will not be what the user expects.
