### ISSUE TITLE
ProjectModel.Server sends null versions when csproj is just added to project.json and there was no restore

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2200]
## Steps to reproduce

          "ClassLibrary1": {
            "Name": "ClassLibrary1",
            "DisplayName": "ClassLibrary1",
            "Version": null,
            "Path": null,
            "Type": "Project",
            "Resolved": false,
            "Dependencies": [],
            "Errors": [
              {
                "ErrorCode": "NU1001",
                "SourceFilePath": "C:\\Users\\antonpis\\Documents\\Visual Studio 2015\\Projects\\ClassLibrary5\\src\\ConsoleApp1\\project.json",
                "Message": "The dependency ClassLibrary1 could not be resolved.",
                "Severity": 2,
                "StartLine": 13,
                "StartColumn": 28,
                "EndLine": 13,
                "EndColumn": 28,
                "FormattedMessage": "C:\\Users\\antonpis\\Documents\\Visual Studio 2015\\Projects\\ClassLibrary5\\src\\ConsoleApp1\\project.json(13,28): error NU1001: The dependency ClassLibrary1 could not be resolved.",
                "Source": {
                  "Name": "ClassLibrary1",
                  "Version": null
                }
              }
            ],
            "Warnings": []
          },

It is new , we never received nulls for versions and it breaks our code, since this is a Type=Project , could you please send a conventional default “1.0.0” for their version?

## Environment data
`dotnet --info` output:

**Comment by abpiskunov** [comment]
@troydai

**Comment by troydai** [comment]
/cc @muratg @Eilon @piotrpMSFT @davidfowl 

Since we're in ask mode, please help me to triage this bug. The fix is straightforward: filling a default version value in place to avoid the null value in project.json. The change will be low risk as well. On the other hand @abpiskunov here can help fill in the impact of this bug.

**Comment by davidfowl** [comment]
Seems fine.

**Comment by muratg** [comment]
Looks fine to me too. Email @Eilon and @DamianEdwards for RC2 approval.

**Comment by troydai** [comment]
Fixed in cb14076b38a59c30176b887d0a0fb1318a58c54e
