### ISSUE TITLE
SDK Debian Packages cannot be installed SxS

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2202]
Manpages like `dotnet-publish` are conflicting.

to get this unblocked we will version the manpages in the immediate term @piotrpMSFT 

cc @blackdwarf

**Comment by piotrpMSFT** [comment]
Eta?

**Comment by brthor** [comment]
This is in PR

**Comment by brthor** [comment]
Awaiting approval from Shiproom

**Comment by brthor** [comment]
https://github.com/dotnet/cli/pull/2215

Been there since friday, waiting on approval
