### ISSUE TITLE
dotnet-osx-x64.1.0.0.001598 error 'Could not resolve SDK directory from [/usr/local/share/dotnet]'

### ISSUE THREAD

**Issue by rongriffin** [dotnet/cli#2204]
## Steps to reproduce

Installed dotnet-osx-x64.1.0.0.001598. When I try to run 'dot net --version' (or any other command), i get 'Could not resolve SDK directory from [/usr/local/share/dotnet]' .

## Expected  behavior

print version information

## Actual behavior

Could not resolve SDK directory from [/usr/local/share/dotnet]

## Environment data
`dotnet --info` output:  Could not resolve SDK directory from [/usr/local/share/dotnet]

**Comment by brthor** [comment]
how did you install?

Can you try picking up a later build? 1598 was weeks ago :smile:

**Comment by rongriffin** [comment]
I grabbed the package from http://dotnet.github.io/getting-started/

**Comment by brthor** [comment]
Please try downloading one of the latest from the github page and let us know if you still see the issue :smile:

**Comment by rongriffin** [comment]
Ok, I got the latest linked from the README.  

version 1.0.0-beta-002194 is working.  Thanks!

**Comment by brthor** [comment]
np, glad it worked!

**Comment by brthor** [comment]
cc @blackdwarf it looks like our LKG pkg is busted

**Comment by blackdwarf** [comment]
@brthor how can this be busted? It should not even know about the SDK. 1598 is before the shared fx stuff. There is no concept of SDK .

**Comment by brthor** [comment]
My naive guess is somehow it is getting the new host. I don't know how that's possible though.

**Comment by blackdwarf** [comment]
@brthor just installed it, cannot repro. @rongriffin did you install later then 1598 builds on your machine **prior** to installed the 1598?
