### ISSUE TITLE
dotnet restore is far too verbose

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#2211]
## Steps to reproduce

dotnet restore

## Expected  behavior

On success, either no output (and success result code), to be very "unix-y", or VERY SMALL amount of output.
On failure, just print the error.

## Actual behavior

gobs and gobs of incomprehensible output

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-beta-002196)

Product Information:
 Version:     1.0.0-beta-002196
 Commit Sha:  389c405ed0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by BruceForstall** [comment]
After all, there is a "--verbose" switch you could use to output all the current info.

**Comment by blackdwarf** [comment]
We are already tracking this as #1623. Closing down this one as a duplicate.
