### ISSUE TITLE
dotnet build is too verbose

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#2212]
## Steps to reproduce

dotnet build
## Expected  behavior

On success (clean build), no output.
On failure, or compile had warnings, just that output.
## Actual behavior

from a compilation:

```
brucefo@BruceFoUbuntuVM10:~/src/mcgdiff$ dotnet build
Compiling mcgdiff for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.9494220


brucefo@BruceFoUbuntuVM10:~/src/mcgdiff$
```
1. Compilation succeeded. You don't need to tell me 0 warnings, 0 errors. You don't even need to tell me "compilation succeeded". I assume you'll tell me if it failed, so I can assume it succeeded if there is no output (this would be very "unix-y")
2. Don't tell me how much time elapsed. I don't care.
3. Why is there so much whitespace (empty lines), especially at the end?
4. You can have a --verbose switch for people that want all this crap.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-beta-002171)

Product Information:
 Version:     1.0.0-beta-002171
 Commit Sha:  1428eb81cf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by piotrpMSFT** [comment]
In preview3 the build output is provided by MSBuild and is controllable by MSBuild verbosity option.
