### ISSUE TITLE
Dotnet publish with -o and multiple targets stomps the output

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2216]
## Steps to reproduce
1. Target net451 and netstandart1.5
2. `dotnet publish -o pub`
## Expected  behavior

It should either throw an error asking for target like build does, or publish one.
## Actual behavior

Published both targets into same directory overwriting files.
## Environment data

`dotnet --info` output:

```
Product Information:
 Version:     1.0.0-beta-002194
 Commit Sha:  a28369bfe0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by pakrym** [comment]
Non blocking
//cc @piotrpMSFT @brthor

**Comment by livarcocc** [comment]
This is now mitigated in MSBuild as it is not allowed to publish a multi-tfm project without specifying the TFM you want to publish for.

You would get
```
/sdk/1.0.0-preview5-004442/Sdks/Microsoft.NET.Sdk/buildCrossTargeting/Microsoft.NET.Sdk.targets(31,5): error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application. [/msbuildapp/msbuildapp.csproj]
```

**Comment by emirhosseini** [comment]
@livarcocc I also have a multi-platform project using RC4 of the CLI.  It's failing with the message you mentioned.  I don't follow what the issue is. The publish profile tells it to use "net461". What does it want from me?!

<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <LastUsedBuildConfiguration>Debug</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <PublishFramework>net461</PublishFramework>
    <UsePowerShell>True</UsePowerShell>
    <publishUrl>C:\web\haCardService</publishUrl>
    <DeleteExistingFiles>True</DeleteExistingFiles>
  </PropertyGroup>
</Project>

**Comment by livarcocc** [comment]
I am not aware of this `PublishFramework` property. Did you mean `TargetFramework`?

**Comment by emirhosseini** [comment]
@livarcocc That property exists in the ".pubxml" file which is the publish file.  What does this error require of me? The publish profile is already targeting one of the two target frameworks through the use of that property which is what VS2017 is generating in the xml of the pubxml file when creating a local File System publish.

**Comment by emirhosseini** [comment]
@livarcocc Looks like a bug with VS2017 (I have the latest Feb 7 release).  When I do a publish in command prompt using the CLI it works. But doing a publish with visual studio is failing.

dotnet publish -o "c:\publishOutputFolder" -f net461

**Comment by xperiandri** [comment]
I get the same error when I publish multi target project from VS 2017 RTM
``` XML
<?xml version="1.0" encoding="utf-8"?>
<!--
This file is used by the publish/package process of your Web project. You can customize the behavior of this process
by editing this MSBuild file. In order to learn more about this please visit https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>MSDeploy</WebPublishMethod>
    <AllowUntrustedCertificate>True</AllowUntrustedCertificate>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <PublishFramework>net462</PublishFramework>
    <EnableMSDeployAppOffline>True</EnableMSDeployAppOffline>
    <ProjectGuid>3c8b317f-dd8b-4621-ad30-f64b548d1cd5</ProjectGuid>
    <MSDeployServiceURL>server ip</MSDeployServiceURL>
    <DeployIisAppPath>path</DeployIisAppPath>
    <RemoteSitePhysicalPath />
    <SkipExtraFilesOnServer>True</SkipExtraFilesOnServer>
    <MSDeployPublishMethod>WMSVC</MSDeployPublishMethod>
    <EnableMSDeployBackup>True</EnableMSDeployBackup>
    <UserName>username</UserName>
    <_SavePWD>False</_SavePWD>
  </PropertyGroup>
</Project>
```

csproj
``` XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>name</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>id</PackageId>
    <UserSecretsId>id</UserSecretsId>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
    <RuntimeFrameworkVersion Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">1.1.1</RuntimeFrameworkVersion>
  </PropertyGroup>
```

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\buildCrossTargeting\Microsoft.NET.Sdk.targets(31,5): Error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application.`

**Comment by xperiandri** [comment]
Why do I come here?
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/buildCrossTargeting/Microsoft.NET.Sdk.targets#L31
Why VS does not use `<PublishFramework>net462</PublishFramework>` from `pubxml`?

**Comment by livarcocc** [comment]
@mlorbetske do you know where this bug should go? It seems to me that VS should use the TFM from the publish profile when invoking the publish target.

**Comment by mlorbetske** [comment]
This should go to the WebSDK, I'll move it there

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/websdk#155
