### ISSUE TITLE
dotnet restore fails on Mac

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#2225]
## Steps to reproduce

dotnet restore

## Expected  behavior

Everything gets downloaded.

## Actual behavior

Fails with "too many open files"

If I use "ulimit -n 2048", it succeeds.

However, that is a terrible user experience, and there is no help from the error message that something so obscure is required. Can't it just stop opening so many files???

## Environment data
`dotnet --info` output:

**Comment by emgarten** [comment]
@BruceForstall there was a recent fix for this, would you try the latest build? 

Your issue does not specify which version of dotnet you are using so I can't tell which version you encountered this problem on.

**Comment by BruceForstall** [comment]
@emgarten Here's the --info output:

.NET Command Line Tools (1.0.0-beta-002198)

Product Information:
 Version:     1.0.0-beta-002198
 Commit Sha:  813049dabe

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 RID:         osx.10.10-x64


Was the fix after this?

**Comment by emgarten** [comment]
There are some fixes that went in after that, I believe in 1.0.0-beta-002202.

**Comment by blackdwarf** [comment]
@BruceForstall does this still repro?

**Comment by BruceForstall** [comment]
I haven't tried in 3+ months

**Comment by blackdwarf** [comment]
Is it OK to close then or will you try it again and close?

**Comment by BruceForstall** [comment]
you can close.
