### ISSUE TITLE
Error when following windows one-liner in docs

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#2231]
## Steps to reproduce
Execute windows one liner found at https://github.com/dotnet/cli/blob/master/Documentation/cli-installation-scenarios.md and https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-installation-scenarios.md#windows-command

## Expected  behavior
CLI to be installed

## Actual behavior
404 file not found.
The url is wrong in the docs. It's pointing to `dotnet-install.ps1` but the file in the repo is `install.ps1`.

## Environment data
`dotnet --info` output: n/a

**Comment by krwq** [comment]
This should work right now

**Comment by sayedihashimi** [comment]
@krwq how does it work? I just pasted the [one liner](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-installation-scenarios.md) into a command prompt and I got the same error that I reported. Here is a screenshot,

![error01](https://cloud.githubusercontent.com/assets/1283154/14342079/e0f0fd56-fc4b-11e5-9ba0-51bc2f0e4566.png)

If you look at the command in the one-liner `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1'))}"` and the contents of the `scripts\obtain` in the `rel/1.0.0` branch https://github.com/dotnet/cli/tree/rel/1.0.0/scripts/obtain its clear that there is no file named `dotnet-install.ps1`.

![content](https://cloud.githubusercontent.com/assets/1283154/14342121/48121aa6-fc4c-11e5-984a-0cf3be7d7ceb.png)

Here are specific steps for you to try:
 1. Go to https://github.com/dotnet/cli
 1. Click on Documentation
 1. Click on cli-installation-scenarios.md
 1. Find Windows one-liner, copy that
 1. Paste into command prompt, and press enter

Reopening

**Comment by krwq** [comment]
True, didn't notice the file name mismatch. I'll check if the file should be renamed or documentation updated

**Comment by krwq** [comment]
https://github.com/dotnet/cli/pull/2340

**Comment by sayedihashimi** [comment]
Marking as `blocking-release`

**Comment by Petermarcu** [comment]
@sayedihashimi , please mark it as either blocking-partner or blocking-release. Partner is all hands on deck getting bits through the system. Release are things we need to get to for the release. Don't want to double count. I moved it to just blocking release and you can switch it if its higher pri than that.

**Comment by Petermarcu** [comment]
@krwq , Didn't you have a fix for this one?

**Comment by piotrpMSFT** [comment]
#2340 resolved this issue.

**Comment by sayedihashimi** [comment]
Thanks, I have verified it.
