### ISSUE TITLE
Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#2233]
## Actual behavior
Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
![host_err](https://cloud.githubusercontent.com/assets/6814395/14229062/a63e3ca2-f95b-11e5-88a0-9f30394bc047.png)

##dotnet --info
.NET Command Line Tools (1.0.0-beta-002202)

Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by davidfowl** [comment]
Where is your web application? You probably need to make some changes for it to work on the latest cli. See the samples here https://github.com/aspnet/cli-samples

**Comment by xatabhk** [comment]
@davidfowl I made the changes I think required but they did not work. The workaround I have found is to run "dnu restore" after "dotnet restore". Here is my sample code:
[zaxitech_core_demo.zip](https://github.com/dotnet/cli/files/201658/zaxitech_core_demo.zip)

**Comment by joshcomley** [comment]
I just got this error. I had run a `dotnet restore`. I then deleted the `project.lock.json` and let Visual Studio do the restore again (which I assume is `dnu restore` until the tooling is updated) and it fixed it. I backed up my old lock file to compare to the new one, and it's massively different (old from `dotnet restore` is 271KB, whereas new is 444KB).

**Comment by davidfowl** [comment]
Yea that's not right. You can't use dotnet and visual studio together yet. So either stick to DNX or wait for the dotnet tooling

**Comment by blackdwarf** [comment]
Since the dotnet tooling came along, I believe this issue is fixed. Will close. If the behavior still repros, please reopen.
