### ISSUE TITLE
dotnet run hides empty lines from output

### ISSUE THREAD

**Issue by svick** [dotnet/cli#2234]
## Steps to reproduce
Per dotnet/corefx#7409, use `dotnet new`, modify the code to contain:

```c#
Console.Write("hello" + Environment.NewLine);
Console.Write(Environment.NewLine);
Console.WriteLine();
Console.Write("world" + Environment.NewLine);
```

Then run it using `dotnet run`.

## Expected  behavior
Two empty lines are shown:

```
hello

world
```

## Actual behavior
No empty lines:

```
hello
world
```

## Cause

This is caused by [this code in `StreamFormwarder`](https://github.com/dotnet/cli/blob/3188d0559bf8c7107ae03f5e2ffe98587045b709/src/Microsoft.DotNet.Cli.Utils/StreamForwarder.cs#L86-L89).

**Comment by brthor** [comment]
Please try this with latest bits

**Comment by jpsingleton** [comment]
Works on the latest preview 2 on OS X

**Comment by svick** [comment]
Yeah, it seems to work now.

**Comment by ben-foster-cko** [comment]
I still have this issue on 1.0.0-preview1-002702

**Comment by jpsingleton** [comment]
It was only fixed in preview2, which is now out.
