### ISSUE TITLE
Error in docs regarding channel names for Nightly/future

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#2237]
In the channel listing at https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-installation-scenarios.md#channels it mentions the following channel names.
- Nightly
- Preview
- Production

The install script at https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/install.ps1#L12 has these as:
 - future
 - preview
 - production

**Comment by blackdwarf** [comment]
This is already being dealt with in #1831 .

**Comment by blackdwarf** [comment]
Closing this as the docs has been merged.
