### ISSUE TITLE
dotnet test needs to support filtering tests based on Traits like Owner/priority etc

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/cli#2252]
## Steps to reproduce
1. Dotnet tests in VS does not support filtering based on owner, priority etc.
2. Dotnet tests needs to support customizations using runsettings file.
## Expected  behavior

Need to support traits and runsettings.
## Actual behavior

Not supported.

Details:
Filtering based on Traits like Owner/priority etc is not currently supported. This is because of two things:
- The ProjectKAdapter Test does not have a Traits Collection field like the ObjectModel TestCase to store this information during discovery.
- The runContext is not passed on by which filtering is actually done. If we have service to get this information this should be unblocked.

Since in 1(b) we do not pass in runContext we also do not have a handle to the runsettings file’s content which essentially means that the adapter does not have access to any adapter/ configuration settings that the user can provider like “Test Run Parameters” etc.. 

To support this, we need changes in both the VS test adapter and dotnet test runner.

**Comment by piotrpMSFT** [comment]
This needs design work on the CLI side. We need to make sure that the design here allows for discovery of traits from arbitrary test frameworks for consumption by arbitrary IDEs. 

It's not clear to me that dotnet-test should have knowledge of runsettings. This seems like a file that should be understood by VS Tooling for CLI but not the CLI directly. It won't be scalable for `dotnet-test` to understand all IDE-specific configuration systems and we'll instead need to rely on adapters to provide these services. If that doesn't seem right, let's have a conversation to better understand the scenario.

**Comment by rprouse** [comment]
I am working on the NUnit runner, so adding a question for whoever ends up implementing this; will a Traits collection be added to `Microsoft.Extensions.Testing.Abstractions.Test` to be populated by the `dotnet-test-*` runner in discovery? I am currently populating the Properties collection with our properties and categories (traits), but I don't see any evidence of them in Visual Studio.

**Comment by piotrpMSFT** [comment]
Fixed in VS Test Console [the back-end for preview4+ `dotnet test`]
