### ISSUE TITLE
Remove commands from our project.json

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#2256]
We still have commands in our project.json, which is something that we got from the dnx code but that the CLI does not support.

**Comment by piotrpMSFT** [comment]
@anurse @pakrym any concerns?

**Comment by pakrym** [comment]
No

**Comment by anurse** [comment]
Sounds good. Better to remove it to avoid confusion :)

**Comment by anurse** [comment]
Update the schema here when this is done: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json

**Comment by livarcocc** [comment]
We don't have project.json anymore.
