### ISSUE TITLE
Composability via NuGet packages with tools

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#226]
This came up today in a discussion and it seemed interesting. We have 2 ways to compose tools today:

- Overwrite tools in the dotnet folder
- Put a tool on the PATH

What if you could add a nuget package with a tools folder, and we respected the tools in there? Crazy?

**Comment by anurse** [comment]
The node community is even moving away from heavy tools in global install (https://nodejs.org/en/blog/npm/npm-1-0-global-vs-local-installation/). When you `npm install -g grunt-cli`, you don't get the full CLI, instead you get a shim that launches the cli from your local project directory. Having `dotnet` go one step further and implement that "shimming" itself doesn't seem like a bad idea to me at all.

**Comment by bricelam** [comment]
@davidfowl asked
> What if you want to run different versions of the xunit runner in different solutions?

The xunit runner is actually independent from the xunit framework. Any version of the runner can run any version of framework. The runner could be installed (and updated) globally, and each project could have the version of the framework they want to use.

**Comment by piotrpMSFT** [comment]
Can you have 7.0 and 7.1 both in a single project.json?

**Comment by bricelam** [comment]
@piotrpMSFT No, it needs to be separate projects. Otherwise, you'll get assembly and type conflicts.

**Comment by cdmihai** [comment]
In addition to allowing projects to run different versions of the same tool, keeping tools local to the Nuget package that depend on them would also help incremental compilation. It makes it possible to detect when a tool changed (which would trigger re-compilation).

**Comment by blackdwarf** [comment]
@piotrpMSFT what is the status of this?
