### ISSUE TITLE
Installer at http://dotnet.github.io/ is bringing down dotnet cli -1598

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2263]
The MSI link at http://dotnet.github.io/getting-started/
![capture](https://cloud.githubusercontent.com/assets/1622880/14265843/7f3901b2-fa89-11e5-81db-544119f44199.PNG)
Is bringing down `dotnet-win-x64.1.0.0.001598.exe`, which is rather old (by nightly bits standards). A few folks have run into this and come to JabbR for help, and we re-direct them to the GH repo for `rel/1.0.0` current nightly MSI. Was this the version you wanted linked there?

**Comment by piotrpMSFT** [comment]
This is the right version at the moment. CLI took on significant changes in the past few weeks and they've not yet stabilized throughout the system. We locked back to an earlier build to minimize confusion for folks learning about CLI @//build/

@blackdwarf
