### ISSUE TITLE
dotnet publish standalone without a runtime or framework publishes something (but it is incomplete)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2265]
## Steps to reproduce

dotnet new
edit project.json (remove "type": "platform" from Microsoft.NETCore.App"
dotnet publish
## Expected  behavior

It would be great if this 'just worked' but I guess I would expect this to error and say the app needs a "runtimes" declaration and -r and -f need to be specified at publish time.
## Actual behavior

bin/Debug/netstandard1.5/publish contains some but not all the necessary dependencies to have a standalone app
## Environment data

`dotnet --info` output:
1.0.0-beta-002192

**Comment by GuardRex** [comment]
> and say the app needs a "runtimes" declaration and -r and -f need to be specified at publish time.

Side Note on "-r and -f need to be specified at publish time": I'm working with standalone apps, and my testing indicates that publish will default to the RID you specify in `project.json` if the switch isn't present. I also don't need to specify the `-f` at publish if I only have one TFM (in my case `netcoreapp1.0`) ... seems to pick that up ok as well.

**Comment by blackdwarf** [comment]
Hmmm, yes. In this case the absence of `runtimes` node in the project.json **and** the `type: platform` makes this a middle-ground which publish should detect and throw an error saying that one of these two needs to be added to get *something*.

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
