### ISSUE TITLE
"dotnet restore" fails when local package folder is not present

### ISSUE THREAD

**Issue by nattress** [dotnet/cli#2270]
## Steps to reproduce

- dotnet new
- Remove your packages cache. On Linux where I have observed this, I removed ~/.nuget/packages to simulate a clean machine building for the first time.
- dotnet restore

## Expected  behavior
Package cache is silently created

## Actual behavior
log  : Restoring packages for /home/simonn/Documents/repro/project.json...
error: Failed to retrieve information from remote source '/home/simonn/.nuget/packages/'.
info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.app/index.json
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   OK https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.app/index.json 169ms
error: Failed to retrieve information from remote source '/home/simonn/.nuget/packages/'.

## Environment data
.NET Command Line Tools (1.0.0-beta-002131)

Product Information:
 Version:     1.0.0-beta-002131
 Commit Sha:  8816664062

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by piotrpMSFT** [comment]
@emgarten

**Comment by emgarten** [comment]
@nattress This was fixed last week, would you try the latest build?

**Comment by nattress** [comment]
Yep, that did the trick. Thanks!
