### ISSUE TITLE
Publish standalone on Mac for Win10, fails to run on Win10 with "invalid .deps file"

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2276]
Likely related to #2141 
## Steps to reproduce

Publish a standalone app on Mac for Win10-x64
- dotnet new
- "replace project.json with attached"
- dotnet restore
- dotnet publish -r "win10-x64" -f "netstandardapp1.5"

Deploy to Win10-x64

dotnet stalone.dll
## Expected  behavior

Runs
## Actual behavior

Fails with "invalid .deps file"
(A side note, without symbols for hostpolicy.dll, it is nearly impossible to understand why it is failing with this error)
## Environment data

`dotnet --info` output:
1.0.0-beta-002205

[project.json.txt](https://github.com/dotnet/cli/files/204838/project.json.txt)

**Comment by livarcocc** [comment]
I tried this out with preview3 and it worked.
