### ISSUE TITLE
Unable to run assembly from the directory containing it

### ISSUE THREAD

**Issue by shirhatti** [dotnet/cli#2279]
I am unable to run the published dll from within the directory containing it. However, it works fine if I specify an absolute path to my .dll or any relative path that involves a directory walk.

## Steps to reproduce
````
➜  dotnet HelloWebShared.dll
Could not load host policy library [HelloWebShared.dll]

➜  cd ..
➜  dotnet publish/HelloWebShared.dll

Hosting environment: Production
Content root path: /Users/shirhatti/demo/cli-samples/HelloWebShared/bin/Debug/netcoreapp1.0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
````
## Expected  behavior
````
Hosting environment: Production
Content root path: /Users/shirhatti/demo/cli-samples/HelloWebShared/bin/Debug/netcoreapp1.0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
````

## Actual behavior
````
Could not load host policy library [HelloWebShared.dll]
````

## Environment data
`dotnet --info` output:
````
.NET Command Line Tools (1.0.0-beta-002212)

Product Information:
 Version:     1.0.0-beta-002212
 Commit Sha:  cb14076b38

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
````

**Comment by piotrpMSFT** [comment]
@schellap can you take a look?

**Comment by piotrpMSFT** [comment]
@shirhatti is this app shared or standalone?

**Comment by brthor** [comment]
If this is a portable app this behavior would be expected, please share project.json

**Comment by davidfowl** [comment]
> If this is a portable app this behavior would be expected, please share project.json

Not it's not. It should work no matter what the working directory is.

**Comment by brthor** [comment]
@davidfowl you are right, not sure why I was thinking that. HostPolicy should get picked up from the sharedfx. 

Seems like the most likely thing here is that there is no runtimeconfig.json, or it's an unpublished standalone app (which should be run with `dotnet run`)

**Comment by brthor** [comment]
tried to do a quick repro and found it successful with a PortableApp

```
Bryans-MacBook-Pro:netstandard1.5 brthor$ dotnet ./PortableApp.dll
Hello, World!
Bryans-MacBook-Pro:netstandard1.5 brthor$ dotnet --info
.NET Command Line Tools (1.0.0-beta-002199)

Product Information:
 Version:     1.0.0-beta-002199
 Commit Sha:  a5eb211e4e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by shirhatti** [comment]
`dotnet foo.dll` doesn't work, but `dotnet ./foo.dll` does work.

**Comment by jeffschwMSFT** [comment]
This issue should be considered for RC2.  Due to the error it is very hard to know that full path will fix this issue and it was not something wrong with the publish or file transfer.

**Comment by ellismg** [comment]
I agree that we should consider this for RC2.  I feel like this is going to be a common thing and understanding that you need to provide a full path is very odd.  I ran into this today and wasted a bunch of time trying to figure out what was going on (especially since the error message is not helpful in this case)
