### ISSUE TITLE
Dotnet restore for helloworld app pulls down >600 meg

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2281]
## Steps to reproduce
rm ~/.nugget (or clean machine)
dotnet new
dotnet restore

## Expected  behavior
The default new console app is sharedfx and should not need anything restored

## Actual behavior
600+ meg of nuget packages are restored

## Environment data
`dotnet --info` output:
1.0.0-beta-002215

**Comment by Petermarcu** [comment]
We have to decide whether we install a nuget cache with the CLI or not. We're planning on having tools like VS and VS Code have the option of installing a cache.

**Comment by Petermarcu** [comment]
We should also look at what is in the 600MB. A large chunk is likely XML intellisense files.

**Comment by jeffschwMSFT** [comment]
What is the scenario to cache anything?  Is it not preferable to pull down what you need and no more?

**Comment by cmatskas** [comment]
I think there is a good case for caching but we should make it a separate task and an explicit one too.

**Comment by blackdwarf** [comment]
We are now priming the cache on new installs so this is not an issue anymore.
