### ISSUE TITLE
Remove APISet path setting for DLL SearchPath

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2287]
We wouldn't need it for RTM since we will ship from open and link against traditional imports.

We will need to coordinate this, though, we publishing from the open.

**Comment by saurabh500** [comment]
@gkhanna79 Is this issue related to the corefx bug https://github.com/dotnet/corefx/issues/7518 ?

**Comment by gkhanna79** [comment]
Nope, it is about removing some code that would no longer be applicable.

**Comment by piotrpMSFT** [comment]
@schellap if this is still needed, please re-open in core-setup!
