### ISSUE TITLE
dotnet-test: standalone apps cannot resolve BCL libraries on OS X El Capitan

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#2291]
I have only been able to reproduce this on OS X 10.11. Doesn't reproduce on Windows or OS X 10.10.
## Steps to reproduce
1. `dotnet new`
2. Add xunit and dotnet-test-xunit.
3. Change to standalone.
4. `dotnet restore` or `dotnet restore --infer-runtimes`. Bug happens with either.

``` json
{
  "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-*"
  },
  "frameworks": {
    "netstandardapp1.5": {"imports": ["dnxcore50", "portable-net452+win81"]}
  },
  "runtimes": {
    "osx.10.11-x64": { }
  }
}
```

Here is my project lock so you can get the same versions: [project.lock.json](https://gist.github.com/natemcmaster/ea8a8cf347214f5dfd59253a1ec13db7)
## Expected  behavior

`dotnet test`
Compiles.
Launches and runs xunit.
## Actual behavior

`dotnet test`
Compiles.
Attempts to start launches by crashes with:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly
'System.Reflection.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. An internal error occurred.
 (Exception from HRESULT: 0x8007054F)
   at Xunit.EnvironmentHelper.GetEnvironmentVariableMethod()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Xunit.EnvironmentHelper.GetEnvironmentVariable(String variable)
   at Xunit.Runner.Reporters.AppVeyorReporter.get_IsEnvironmentallyEnabled()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xunit.Runner.DotNet.CommandLine..ctor(IReadOnlyList`1 reporters, String[] args, Predicate`1 fileExists)
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
```

This is not limited to System.Reflections.Extensions. Try also `dotnet test --bad-param` and xunit dies with a similar exception, missing "System.Text.Encoding.Extensions".

Here is the corehost_trace=1 log output: 
[log.zip](https://github.com/dotnet/cli/files/205552/log.zip)
## Environment data

`dotnet --info` output:

```
Product Information:
 Version:     1.0.0-beta-002202
 Commit Sha:  60b23d5115

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
## Impact

Compounded by #2278. I cannot execute use dotnet-test at all on on OS X 10.11. 

This error reproduces in bigger projects, such as [Entity Framework](https://github.com/aspnet/EntityFramework).

**Comment by livarcocc** [comment]
@ericstj @piotrpMSFT This is the issue that I was talking to you guys about earlier today.

cc @Sridhar-MS Who has encountered this also.

**Comment by brthor** [comment]
@natemcmaster Your app has no dependency on `Microsoft.NETCore.App`, where is the framework expected to come from?

**Comment by livarcocc** [comment]
@brthor Even with that, I still saw the System.Reflection.Extensions issue repro.

**Comment by brthor** [comment]
Ah alright. Maybe if the app is standalone it expects things app local?

@schellap does `corehost` know how to use --additionalprobingpath for standalone apps?

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
