### ISSUE TITLE
Should LockFileReader use Newtonsoft.Json for parsing?

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2292]
It's currently using the Json parser from DNX. The plan is to stop maintaining DNX going forward which would require moving that code elsewhere where it can be maintained. The alternative is to use Newtonsoft.Json which is already used in ProjectModel.

**Comment by brthor** [comment]
With this: https://github.com/dotnet/cli/pull/1972

Will this concern go away?

**Comment by pranavkm** [comment]
Yup, looks like it.

**Comment by pakrym** [comment]
Wait, we stopped using dnx parser in https://github.com/dotnet/cli/commit/f665c28173ba2eea43c074f61f113882b88edc66

**Comment by pranavkm** [comment]
@pakrym - these types are from DNX's Json parser - https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Graph/LockFileReader.cs#L42

**Comment by pakrym** [comment]
Oh, lock file, my bad, yes then that pr should solve it but it's stale and won't go into RC2.

**Comment by piotrpMSFT** [comment]
preview3 drops support for ProjectModel.
