### ISSUE TITLE
dotnet build -n can't work on win10

### ISSUE THREAD

**Issue by 717009629** [dotnet/cli#2299]
## Steps to reproduce
C:\Users\71700\dotnet>dotnet build -n
Compiling dotnet for .NETStandard,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.1366594
Input Assembly: C:\Users\71700\dotnet\bin\Debug\netstandard1.5\dotnet.dll
Could not find a part of the path 'C:\Program Files\dotnet\sdk\1.0.0-beta-002244\sdk'.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-beta-002244)

Product Information:
 Version:     1.0.0-beta-002244
 Commit Sha:  49fae29b7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by Merlineus** [comment]
Same issue on Win 10 64bit and OS X 10.10 using latest builds
