### ISSUE TITLE
dnvm update to 1.0.0-rc1-update2 caused strange behavior in a VS2015 xproj

### ISSUE THREAD

**Issue by MarkStega** [dotnet/cli#2302]
## Steps to reproduce

1) Use dnvm to update to 1.0.0-rc1-update2 (all architectures and runtimes)

2) Remove the old 1.0.0-rc1-update1 (all architectures and runtimes)

3) Open a VS2015 project that contains an xproj that has references of the form "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final"

## Expected  behavior

1) Nothing should happen as the most recent semantic version of the environment is present

## Actual behavior

1) In the VS output window you see all four 1.0.0-rc1-update1 get installed

2) In the user path statement a reference is added to the erroneous path "c:\users\xxx\.dnx\runtimes\dnxcoreclr-win-x64.1.0.0-rc1-final" which does not exist

## Environment data
`dotnet --info` output:

1) Neither dnvm or dnu have an info command and there is no dotnet command in the path

2) Environment is Win10 x64 up to date with all patches, VS2015 Update 2.

**Comment by blackdwarf** [comment]
@MarkStega this is concerning DNVM. In the future, when we release RC2 of .NET Core, we will transition off of DNX and to CLI and DNVM will not be used anymore.  This repo is housing the CLI tools which you can start exploring to replace DNX in your usage.

**Comment by MarkStega** [comment]
So I take it there will be a coordinated update of VS2015 to also not use DNVM?

**Comment by blackdwarf** [comment]
Yes, there was a release. Will close this issue since the question has been answered.
