### ISSUE TITLE
Add HelloMvc integration test

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2303]
Suggestion from https://github.com/dotnet/cli/pull/2269#issuecomment-206048982

https://github.com/aspnet/Home/tree/dev/samples/latest/HelloMvc

**Comment by muratg** [comment]
Thanks @Sridhar-MS!

**Comment by livarcocc** [comment]
I don't have access to this HelloMvc project. Is that still a thing? In any case, we have tests that build/publish the MVC template project. If that's not enough, please re-activate this issue.
