### ISSUE TITLE
F# projects cannot be built from outside the project directory

### ISSUE THREAD

**Issue by abrodersen** [dotnet/cli#2305]
Currently, F# projects can only be built from the project directory. This is very poblematic for C# projects which reference F# projects.
## Steps to reproduce
1. `git clone https://github.com/abrodersen/fsharp-bug.git`
2. `cd fsharp-bug`
3. `dotnet restore`
4. `cd src/csharp-bin`
5. `dotnet run`
## Expected  behavior

The program should compile and run, producing text output.
## Actual behavior

The compilation fails with the following error:

```
Compiling fsharp-lib for .NETStandard,Version=v1.5
No executable found matching command "dotnet-compile-fsc"
C:\Program Files\dotnet\dotnet.exe compile-fsc @C:\Users\Aaron\dev\dotnet\fsharp-bug\src\fsharp-lib\obj\Debug\netstandard1.5\dotnet-compile.rsp returned Exit Code 1

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.6421334
```

The fsharp project compiles successfully if and only if the current directory is the project directory.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-beta-002203)

Product Information:
 Version:     1.0.0-beta-002203
 Commit Sha:  f6fa1cf060

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by enricosada** [comment]
that's a problem with `compile-fsc` as tool /cc @brthor

**Comment by piotrpMSFT** [comment]
@enricosada is this still an issue with your new implementation? Given our earlier conversation I assume 'yes'...

**Comment by enricosada** [comment]
@piotrpMSFT @abrodersen i tried and with dotnet `1.0.0-preview2-003131` and is fixed.
i tried using same structure/repro steps using c# console and f# lib created from `dotnet new`
i didnt seen that before, so maybe was fixed long time ago (`preview1`?).

Anyway to be sure, i added https://github.com/dotnet/netcorecli-fsc/issues/37 to add a test to current test suite, to avoid in next `preview3` (we are moving from `dotnet-compile-fsc` to using an msbuild task)

@piotrpMSFT can be closed

**Comment by piotrpMSFT** [comment]
Thanks for confirming @enricosada !
