### ISSUE TITLE
dotnet should print LibraryManager diagnostics when reading lock file for tool

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2309]
Right now when reading tools `lock.json` file we are ignoring all the diagnostics `LibraryManager` contains about unresolved libraries and fail only in runtime with assembly not found issues.

/cc @brthor @davidfowl

**Comment by brthor** [comment]
We are using the LockfileReader, should it throw in these scenarios or is there some explicit error checking that needs to happen?

**Comment by pakrym** [comment]
You get these errors in `ProjectContext.LibraryManager.GetAllDiagnostics()` and it doesn't throw them, see https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L50 on how we handle them.

**Comment by brthor** [comment]
Might it be worthwhile to move this logic into some `SafeLockfileReader` which will print any errors and then throw, or do we generally want to continue when we hit these errors?

**Comment by pakrym** [comment]
Some of them are warnings, like `Dependency specified was {FormatLibraryRange(range)} but ended up with {library.Identity}`

**Comment by brthor** [comment]
Sure, the core of what I'm asking is if you see value in a `LockFileReader` abstraction that has warning/error handling. Could potentially accept delegates for onError or onWarning for custom behavior on each. 

The value I see is that it wasn't immediately apparent to me that this would need to happen when using the LockFileReader, and I expect that would be true in the future for other folks. Having this would force anyone reading the lock file to have the proper error handling.

**Comment by pakrym** [comment]
It's not `LockFileReader` its `ProjectContextBuilder` I think we should not extend it, just add another class that validates `ProjectContext` you got and throws or prints errors.

**Comment by brthor** [comment]
Why not have the errors handled in `ProjectContextBuilder`? 

Are there situations where we want to continue with the ProjectContext despite it having errors?

**Comment by pakrym** [comment]
It's not errors, it's diagnostics, some of them are warnings, and `ManagedCompiler` tries to build even if there are errors.

**Comment by livarcocc** [comment]
This is now being done by NuGet.
