### ISSUE TITLE
dotnet CLI (pack, restore, build) does not work with {projectname}.project.json

### ISSUE THREAD

**Issue by conniey** [dotnet/cli#2311]
## Steps to reproduce
1. Create a PCL that targets ASP.NET Core and .NET 4.6. (ie. MyProject)
2. Rename the project.json to the {projectname}.project.json (ie. MyProject.project.json)
3. Try running `dotnet restore` or `dotnet pack`

In many of our repros, we use {projectname}.project.json because of their resolution for this issue: https://github.com/NuGet/Home/issues/1294

## Expected  behavior
This restores/builds in Visual Studio 2015. I expect it to be able to do the same.

## Actual behavior
![repro](https://cloud.githubusercontent.com/assets/10136526/14329678/7c84a930-fbf1-11e5-9e70-9bb15ae1ccf5.png)

## Environment data
`dotnet --info` output:
```
D:\git\icu-dotnet\source\icu.net [portToNETCore ↑ +0 ~4 -0 !]> dotnet --info
Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001598)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package
```

**Comment by blackdwarf** [comment]
Given the move to [MSBuild and csproj](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) that is planned, I'm closing this issue.
