### ISSUE TITLE
Publish non-Windows CoreHost runtime NuGet packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#2317]
We currently only publish NuGet packages on our Windows build.  But we are now building native CoreHost packages on non-Windows platforms.

We should do something to publish these packages on non-Windows platforms.

**Comment by weshaggard** [comment]
cc @schellap

**Comment by schellap** [comment]
@weshaggard does this have to be solved still?

**Comment by weshaggard** [comment]
No this one is currently working.
