### ISSUE TITLE
Renaming "project.json" to "dotnet.json"? 

### ISSUE THREAD

**Issue by Ciantic** [dotnet/cli#2332]
Since the new tool is "dotnet", this is last chance to rename generally named "project.json" to "dotnet.json". Is there any interest in there?

I think project.json is too generic name for dotnet specific project, and the file itself does not contain identifier inside. This means when project.json projects spread, the IDE's and tools have to go inside this generically named file to see if it's a dotnet project or some other project.json.

I propose dotnet.json. Good example is "tsconfig.json" in TypeScript, it does not confuse tools.

**Comment by ciel** [comment]
Just throwing this out; It works fine right now if you rename the file `dotnet.project.json` - the schema is even carried over to the lock file, getting named `dotnet.project.lock.json`. Perhaps there's no need for a coding change, just an emphasis on best practice.

**Comment by aliozgur** [comment]
:+1:

**Comment by kendaleiv** [comment]
This could potentially reduce confusion between the npm `package.json` vs `project.json`.

**Comment by Ciantic** [comment]
@kendaleiv not to mention "app.json" used by Heroku. Here [is a aspnet app having](https://github.com/aspnet/MusicStore) app.json (for heroku), global.json for dotnet and in subfolder a project.json.

**Comment by blackdwarf** [comment]
Given the move to [MSBuild and csproj](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) that is planned in the future, this issue is not applicable anymore, so will close it.
