### ISSUE TITLE
dotnet run error "An item with the same key has already been added. Key: Microsoft.DotNet.ProjectModel.ProjectContentBuilder+LibraryKey"

### ISSUE THREAD

**Issue by Gillardo** [dotnet/cli#2334]
## Steps to reproduce
run `dotnet restore` which works fine.
Then `dotnet run` and get the error

## Expected  behavior
I would expect it to run the project

## Actual behavior
Reports the error "An item with the same key has already been added. Key: Microsoft.DotNet.ProjectModel.ProjectContentBuilder+LibraryKey"

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-beta-001540)

Product Information:
 Version:     1.0.0-beta-001540
 Commit Sha:  6aeed1f52d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

My project.json is using the following frameworks
```
    "frameworks": {
        "net451": {
            "frameworkAssemblies": {
                "System.ComponentModel": { "type": "build" }
            }
        }
    },
```

**Comment by pranavkm** [comment]
This was a NuGet restore issue that was fixed in later issues of the CLI. Try updating to a [more recent build](https://github.com/dotnet/cli#installers-and-binaries)

**Comment by Gillardo** [comment]
Thank you, i was downloading the wrong installer! duh!

How come my files being referenced (javascript, css etc) are not the ones in the wwwroot folder, but within a sub folder like \bin\debug\net451\win7-x64\wwwroot

Does this mean if i update any javascript or css, i have to run my gulpfile, then stop dotnet from running and rerun it?  Never had to do this with `dnx web` command

**Comment by pranavkm** [comment]
@Gillardo - you can set the content root to your working directory so any changes to your wwwroot during dev time are picked up. The wwwroot under the bin\debug directory will get used if you publish your application. See https://github.com/aspnet/Mvc/issues/4428

**Comment by Gillardo** [comment]
This seems to have worked thank you
