### ISSUE TITLE
project.lock.json: why is it so big

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/cli#2335]
I encountered this:

https://github.com/Krzysztof-Cieslak/KestrelFSharp/blob/3bb81aad259f88957848133e889dfb0bc570387e/project.lock.json

I'd like to understand (as reasonably possible) the reasons why this file has to be so large.

Why does each dependency needs to specify the file contents and sha of the nuget package? this seems to be the bulk of the contents there.

I think this content (which might be needed by some pieces of infrastructure for `dotnet restore`) ought to be stored outside of the repository, probably in the nuget cache folder. Actually most of this is probably already there in the package itself.

`project.lock.json` is necessarilly checked-in for reproducible builds, and if it is so big (and hence not for human consumption/diff tool friendly) there is something to be fixed.

**Comment by GuardRex** [comment]
> is necessarilly checked-in for reproducible builds

Pegged dependency versions will give you reproducible builds without having to retain the file. I know exactly what you mean about the size of the file though ... it is **HUGE**. I exclude it from source control.

**Comment by smoothdeveloper** [comment]
@GuardRex thanks for chiming in

> Pegged dependency versions will give you reproducible builds without having to retain the file.

What does it mean, is it specifying the exact version number till the last place in project.json itself?

That seems like a lots of noise (and work for the user, if you compare to paket workflow) also and churn for minor updates in more places than necessary.

Is it based on hardcoded minimum version dependency resolution? Doesn't this contradict the ship-fast-and-frequently approach and also the assumption that latest and greatest possible compatible dependency is preferable than oldest one (at least for applications)?

> I know exactly what you mean about the size of the file though ... it is HUGE. I exclude it from source control

If it didn't contain so much useless (as a file containing detailed version information, all the rest can go elsewhere out of the repository, heck even the assemblies land outside of it... see #2336) would you version it in your repositories?

**Comment by GuardRex** [comment]
Yes, I meant specifying the versions of packages exactly for guaranteeing reproducible builds.

Yes, this is probably **not** the guidance. @davidfowl has said ...

> Never never never never never freeze package dependencies. You're making it worse for everyone. NuGet always chooses the minimum required dependency ...

... in https://github.com/aspnet/EntityFramework/issues/2996

I don't agree during preview, however, as baking package versions has saved my butt a few times. Even if under some conditions it would be ok to do this, what we'll likely need is some extra tooling from MS or the community for performing several "helper" tasks with the deps, such as baking them in easily from the resolved deps in `project.lock.json` ... see https://github.com/dotnet/cli/issues/1245 ... or perhaps just saving the current known-good set somewhere in the project in case the next set that comes down :boom: explodes :boom: in one's face.

**Comment by smoothdeveloper** [comment]
> as baking package versions has saved my butt a few times

To me, that is the point of the lock file (not project.json), and there is also a point of saving everyone the hassle to specify exact versions of all packages (also if I want transitive dependencies resolved another way than the *"one true way"* decreted by MS) just to be up-to-date.

> extra tooling from MS or the community

There were discussions about how to make paket work with `dotnet restore` (because amazingly paket handles all the scenarios, with a very user/diff friendly file format) but those became stale after (from my understanding) the dotnet cli team explained there was no use for paket because `dotnet restore` does all any user would like to.

Can we get technical explanation about my initial question: why is project.lock.json so big? Can something be done to get rid of all information which doesn't pertain to it (like listing files of all packages, the sha, all but the versions can move to some external location) so it makes sense to version it.

**Comment by blackdwarf** [comment]
This issue should be moved to NuGet/Home if it is still valid. Closing it here.
