### ISSUE TITLE
Use fallback logic when selecting targets to publish

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#2339]
We should use the full `runtime.json` graph walking logic to select appropriate runtimes when publishing. For example, if the project.json has

``` json
{
    "runtimes": {
        "ubuntu.14.04": {}
    }
}
```

If the host RID is `ubuntu.15.04`, this will fail today, and you have to add that RID. Instead, we can use the data from the RIDless graph to load up the `runtime.json` that defines the RIDs and walk it back to allow us to select the `ubuntu.14.04` target, since it is compatible, according to the `runtime.json` data.

/cc @DamianEdwards @davidfowl 

(Not for RC2)

**Comment by piotrpMSFT** [comment]
Rid Inference was removed with the move to msbuild.
