### ISSUE TITLE
corehost should not require DOTNET_HOME

### ISSUE THREAD

**Issue by dleeapho** [dotnet/cli#234]
Install as follows:
wget https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-linux-x64.latest.deb
dpkg -i dotnet-linux-x64.latest.deb

'dotnet run' on an app folder gives:
failed to locate CLR files, set the DOTNET_HOME environment variable

**Comment by anurse** [comment]
:+1: indeed it should. We may also want to consider having `corehost` be able to search default locations though so that setting `DOTNET_HOME` isn't absolutely necessary.

**Comment by blackdwarf** [comment]
@anurse that would be actually a much better solution. So:

* search for a default install 
* if not exists check for env variable
* if not set, fail

Thoughts?

**Comment by anurse** [comment]
Yeah, the point of the `DOTNET_HOME` environment variable is mostly for specific applications and our own development process, so I think that's the best option. The search orders would be as follows:

Windows:

* `%DOTNET_HOME%`
* `%LOCALAPPDATA%\Microsoft\dotnet\cli`
* `%ProgramFiles%\Microsoft .NET Tools?\dotnet\cli?` (we need to finalize the Windows MSI layout)

Unix:

* `$DOTNET_HOME`
* Maybe a user level search path? `~/.dotnet/cli`? While tooling will probably be global-install, I do think we'll want user-installed runtimes
* `/usr/local/share/dotnet/cli`
* `/usr/share/dotnet/cli`

**Comment by brthor** [comment]
@anurse Why the cli after /usr/share/dotnet?

Are we planning to put other things there? And does the PKG already install to that location?

**Comment by anurse** [comment]
I saw other packagers put things in the "cli" subfolder so I duplicated it. I'm happy to remove it!

The PKG currently installs to `/usr/local`. I'd actually suggest it should install to `/usr` instead since it is using the OS-provided packaging mechanism (just like the DEB is today)

**Comment by anurse** [comment]
@Sridhar-MS where does the MSI install to? Have we finalized that path?

**Comment by blackdwarf** [comment]
Program Files\Microsoft\dotnet is the install path I see.

**Comment by anurse** [comment]
I don't know that we should be writing into `%ProgramFiles%\Microsoft` directly... maybe we need to review that path.

**Comment by Petermarcu** [comment]
I agree, we need to review all the paths and registry key locations.

**Comment by piotrpMSFT** [comment]
do we have an ETA for this?

**Comment by anurse** [comment]
I'm working on it now, mostly done. PR to come today probably.
