### ISSUE TITLE
dotnet build should produce runnable outputs for each runtime in project.json

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#2343]
When your project.json has multiple runtimes in project.json, we compile the managed code and then picks the most appropriate RID to make the output "runnable". Instead, it would be pretty easy for build to make runnable outputs for all RIDs provided in the project.json (basically just have to add a loop here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-build/CompileContext.cs#L492). This would simplify a lot of VS scenarios.

/cc @BillHiebert

**Comment by BillHiebert** [comment]
This is needed to make VS work correctly. When the user builds, they will expect all their outputs to be created. This would also make it consistent with the --framework option which builds all frameworks if the option is omitted.

**Comment by BillHiebert** [comment]
@anurse 

Is this on the radar for RC2?

**Comment by piotrpMSFT** [comment]
@anurse, when this was originally brought up you were fairly adament that we should not be looping across all RIDs. Are you ok with the change now?

**Comment by anurse** [comment]
Yeah, I've been convinced it's useful and think I've worked out how best to do it. Also #2428 might end up requiring us to actually invoke `csc` separately for different RIDs, so it may be useful anyway.

**Comment by piotrpMSFT** [comment]
@krwq is starting to work on this tomorrow morning. We may need to throw additional folks at it as this seems like a big workitem.

**Comment by cdmihai** [comment]
As an addition to this, it would be really cool to share the same dll accross multiple tfm / rids whenever possible. This would cut down on compilation times. If a dll looks the same on multiple targets, it really does not need to be re-compiled.

So, if the csc response files for two different tfm/rid combinations is the same, the dll should be reused. Currently the only difference that I see is the tfm moniker symbol passed to csc. I'd make this an optional symbol, settable in project.json, for users that actually need the moniker symbol.

**Comment by anurse** [comment]
Across RIDs sure, but I doubt it'd be worth investing much in cross-TFM sharing of assets. Almost all assets depend on the low-level packages (System.*) which have different implementations for most TFMs. In general, cross-compilation is for targeting multiple disparate frameworks or multiple different versions of a specific framework, so they compile against different assemblies. Obviously it's possible there is a case where the response file could end up the same, but I don't think that's going to be very common.

Across RIDs on CoreCLR, there definitely isn't a different, in fact we copy right now. That's actually the cause of #2428, since on .NET Framework we need to build differently for different RIDs.

**Comment by cdmihai** [comment]
I was talking about TFM. On one side, there are projects that heavily ifdef based on TFM (like net core msbuild). On the other hand, there also projects that do not change. 

The decision to share should not be made by heuristics, but by looking at csc inputs: if all the args and env vars are the same for a csc invocation, then the dll can be shared. Post RTM though.

**Comment by piotrpMSFT** [comment]
@krwq how's this going?

**Comment by piotrpMSFT** [comment]
@BillHiebert this will introduce a breaking change on `dotnet build -o`. Once this is in place, -o will require that you pass a RID:

`dotnet build -o DIR -f TFM -r RID`

@krwq can give you details.

**Comment by piotrpMSFT** [comment]
@Eilon I'm not sure if your team is using `dotnet build -o`. Once this fix goes in, any callers of `dotnet build -o` will need to specify `-r` in addition to `-f`. Who can I coordinate with?

**Comment by Eilon** [comment]
@pranavkm & @victorhurdugaci any idea about @piotrpMSFT 's question about `dotnet build -o`?

**Comment by pranavkm** [comment]
We dont use that in our build scripts: 
* https://github.com/aspnet/KoreBuild/blob/dev/build/shade/_k-standard-goals.shade#L145
* https://github.com/aspnet/KoreBuild/blob/dev/build/shade/_k-standard-goals.shade#L133

**Comment by victorhurdugaci** [comment]
We use it in at least one place in tests:

https://github.com/aspnet/Hosting/blob/12fff1833fdcaa36b6d43bbdeb0465a11d9cf365/src/Microsoft.AspNetCore.Server.Testing/Deployers/ApplicationDeployer.cs#L51

**Comment by anurse** [comment]
@piotrpMSFT To be clear, that's only if you're building a standalone app, yes? If you're building a portable output, `-o` should not require `-r` since there is no RID to put there...

**Comment by krwq** [comment]
@anurse correct

**Comment by piotrpMSFT** [comment]
@krwq continues to find issues as he gets further. He will be adding a PR so we can see the direction of this feature and help if possible.

**Comment by piotrpMSFT** [comment]
@BillHiebert @anurse this was discussed offline today and I understand we can kick it out to RTM. Ping me if I missunderstood something.

**Comment by piotrpMSFT** [comment]
@krwq can you follow up with @BillHiebert to understand the plan for running both 32-bit and 64-bit standalone and portable apps from Visual Studio in RC2?

**Comment by livarcocc** [comment]
This is going to be done very differently in msbuild world.
