### ISSUE TITLE
dotnet test needs to support desktop and netcore frameworks

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/cli#2346]
## Steps to reproduce
dotnet test needs to support the following frameworks:

1. netcoreapp1.0
  "frameworks": {
    "netcoreapp1.0": {
}}

2. netstandard1.5/netcore1.5
  "frameworks": {
    "netstandard1.5": {
    }}

3. net451/net46
  "frameworks": {
    "net451": {
    }}

## Expected  behavior
Should be able to discover and run tests for all these frameworks.

## Actual behavior
restore error

## Environment data
`dotnet test'
1.0.0-beta-002279

**Comment by piotrpMSFT** [comment]
@vijayrkn We have not built an xunit runner for dotnet which supports dotnet desktop. The runner which was developed intentionally unblocks the dotnet core scenario, while the existing xunit console from xunit is able to execute tests for desktop.

To prevent restore errors, add the dependency to dotnet-test-xunit within the netstandard/netcoreapp framework nodes. We can look at porting the xunit runner to desktop in the RTM milestone. If you feel this is immediately blocking please reach out to me offline and let's figure out a plan.

**Comment by barrytang** [comment]
Adding @Petermarcu, @DamianEdwards and @davidfowl 

From today's Core War conservation, I think we agreed that we need a Desktop experience for RC2. I went ahead and moved this to RC2 for now.

**Comment by Petermarcu** [comment]
https://github.com/dotnet/coreclr.xunit/pull/6# is where the work is happening.

**Comment by piotrpMSFT** [comment]
@pranavkm is this ready for code review?

**Comment by pranavkm** [comment]
Yup - https://github.com/dotnet/cli/pull/2527 is the PR for it.

**Comment by piotrpMSFT** [comment]
@pranavkm now that the runner is available, how soon should we expect this to come in?

**Comment by piotrpMSFT** [comment]
Just chatted with @pranavkm. There are test failures on Windows x86 that are being inspected. This is expected to be fixed today/tomorrow.

**Comment by piotrpMSFT** [comment]
This is already closed by #6 in coreclr.xunit
