### ISSUE TITLE
Cannot use tools without adding additional imports

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2347]
Before in a project that uses a tool my tool section looked like this:

```
    "tools": {
      "dotnet-publish-iis": "1.0.0"
    },
```
after I moved the tool to `netcoreapp1.0` the tool no longer works. 

## Steps to reproduce
```
PS C:\Source\cli-samples\HelloMvc> dotnet publish-iis
No executable found matching command "dotnet-publish-iis"
```

## Expected  behavior
The tool runs just fine.

## Actual behavior
No executable found matching command "dotnet-publish-iis"

## Workaround
You can work around the issue by modifying the tools section like this:

```
    "tools": {
      "dotnet-publish-iis": {
            "imports": "netcoreapp1.0",
            "version": "1.0.0-*"
        },
    },
```

but this should not be needed. 

## Environment data
`dotnet --info` output:

```
PS C:\Source\cli-samples\HelloMvc> dotnet --info
.NET Command Line Tools (1.0.0-beta-002256)

Product Information:
 Version:     1.0.0-beta-002256
 Commit Sha:  f49d95c47d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
#2350

**Comment by piotrpMSFT** [comment]
@emgarten is a new build of NuGet available?

**Comment by emgarten** [comment]
@piotrpMSFT  Yes, the PR is here: https://github.com/dotnet/cli/pull/2345

NuGet 1160 uses NetCoreApp as the TFM for Tools

**Comment by pakrym** [comment]
Assigned to @anurse because he does this as part of updating nuget.

**Comment by anurse** [comment]
:+1:

**Comment by Petermarcu** [comment]
@anurse , Anything left on this one or can we close it?

**Comment by anurse** [comment]
Should be fixed with the latest CLI that took new NuGet bits.
