### ISSUE TITLE
Make desktop publishing "half-portable" by default

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#2357]
Desktop frameworks (`net45`, etc.) do not support the full portable layout because we can't intercept native library loading. As a result, if you have an app that targets `net451` and uses Kestrel, you need to put RIDs in your project.json. In order to smooth the experience, we should actually infer a RID during publish and publish for that runtime using the "half-portable" model. For example, given:

```json
{
    "dependencies": { "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*" },
    "frameworks": { "net451": {} }
}
```

Today we would publish:

```
bin/Debug/net45
  MyApp.exe
  runtimes/
    .../
      libuv.dll
```

However, the .NET Framework can't load `libuv` properly from there. So, instead we would infer a RID based on the host machine and publish as though the `--runtime [host RID]` flag had been specified by looking at the RID-less target and scanning for `runtimeTargets` entries to publish only certain binaries.

As a result, the layout would be:

```
bin/Debug/net45
  MyApp.exe
  libuv.dll
```

This can be done entirely during publish so it doesn't require NuGet changes.

/cc @davidfowl @DamianEdwards @piotrpMSFT @pakrym 

This is needed for RC2 in order to support ASP.NET deployment and tooling scenarios. It only affects Desktop, so the impact is pretty minimal.

**Comment by anurse** [comment]
FYI, @pakrym is working on a fix.

**Comment by piotrpMSFT** [comment]
This is currently blocked on an x86 issue. @pakrym believes this will come in Tuesday or Wednesday morning.
