### ISSUE TITLE
Shared Framework not working on 2012R2

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2362]
## Steps to reproduce
1. Install the shared framework with either the .NET Core Installer or the .NET Core Binaries from the `dotnet/cli` repo.
2. Create and configure a shared framework .NET Core app in IIS with the AspNetCoreModule on the server.

## Expected  behavior
It works.
## Actual behavior
After installing with the MSI (both straight install and with install+restart), the app fails with 502.3 (browser), "Process '0' failed to start." (OS Application log), created but empty module log (AspNetCoreModule log).

If you open a command prompt and run `dotnet --version` or if you place the binaries on the server and run `dotnet --version` from the decompressed folder, you get "Could not resolve SDK directory ..."
![capture](https://cloud.githubusercontent.com/assets/1622880/14371529/41ad787e-fcfe-11e5-98d7-e32e8e7287a2.PNG)
![capture1](https://cloud.githubusercontent.com/assets/1622880/14371531/45dd8420-fcfe-11e5-85cc-ece0a72d6285.PNG)
## Environment data
`dotnet --info` output:
See above. The installer is -2296. Server: Azure WS2012R2

**Comment by davidfowl** [comment]
The cli isn't the place to file a bug like this. It's hard to know if things are even setup correctly. What does your web.config look like?

**Comment by GuardRex** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add
        name="aspNetCore"
        path="*"
        verb="*"
        modules="AspNetCoreModule"
        resourceType="Unspecified"/>
    </handlers>
    <aspNetCore
        processPath="dotnet"
        arguments="run .\testshared.dll"
        stdoutLogEnabled="true"
        stdoutLogFile=".\logs\test"
        startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```

**Comment by GuardRex** [comment]
If I navigate to the decompressed binary folder and try `dotnet --version` and it throws that exception. That seems more basic than anything wrong with my `web.config` file.

**Comment by GuardRex** [comment]
Moved to https://github.com/aspnet/IISIntegration/issues/125
