### ISSUE TITLE
Can't be upgrade to a 'nightly' build

### ISSUE THREAD

**Issue by Cuiqs76** [dotnet/cli#2364]
## Steps to reproduce
remove the older dotnet from control panel
install the latest version (1.0.1.002317  x64)

## Expected  behavior
right install

## Actual behavior
fail to install

you have installed 'release' build of .net core cli, it cannot be upgraded to a 'nightly' build of .net core cli. pliease uninstall it and re-run setup

## Environment data
can't execute

**Comment by brthor** [comment]
@Cuiqs76 where are you acquiring the latest version?

**Comment by Cuiqs76** [comment]
this repository: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe

**Comment by Cuiqs76** [comment]
the latest version (002317) is Ok.

**Comment by Cuiqs76** [comment]
![20160422084005](https://cloud.githubusercontent.com/assets/13130628/14728353/5780fbee-0866-11e6-933f-bdac79f12308.png)  the issue come again when install the latest version.

**Comment by GuardRex** [comment]
@Cuiqs76 Try this ... that is referenced here: https://github.com/dotnet/cli/issues/1919#issuecomment-209433994
