### ISSUE TITLE
hwapp do not run on other PC

### ISSUE THREAD

**Issue by kinguru** [dotnet/cli#2367]
## Steps to reproduce
Create hwapp as described in manual for Ubuntu.
https://dotnet.github.io/getting-started/ 

Publish it with "dotnet publish" command
Copy artifacts to another Ubuntu PC and run.

## Expected  behavior
Hello World!

## Actual behavior
Failed to initialize CoreCLR, HRESULT: 0x80131500

## Environment data
`dotnet --info` output:
it is not installed on target PC

**Comment by blackdwarf** [comment]
By default, the `dotnet new` command will create what we call a [portable application](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#portable-applications) and that will require .NET Core to be installed on the machine you wish to run the application on.

Please refer to the linked document for more context.
