### ISSUE TITLE
No executable found matching command "dotnet-test-xunit"

### ISSUE THREAD

**Issue by pafuent** [dotnet/cli#2372]
I'm trying to start using ASP.NET and I can't get my unit tests executed.
The KokoAPI project is based on https://github.com/aspnet/cli-samples/tree/master/HelloMvcApi.
BTW, I'm getting the exact same error in Ubuntu 14.04.

## Steps to reproduce
[KokoAPI.zip](https://github.com/dotnet/cli/files/210561/KokoAPI.zip)
cd KokoAPI
dotnet restore
cd test\KokoAPI.Tests
dotnet test

## Expected  behavior
The unit tests are executed

## Actual behavior
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String
tFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String con
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002302)

Product Information:
 Version:     1.0.0-rc2-002302
 Commit Sha:  0954049575

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by muratg** [comment]
Dup of this (https://github.com/dotnet/cli/issues/1858) ?

**Comment by pafuent** [comment]
I tested making KokoAPI and KokoAPI.Tests using the same target framework than dotnet-test-xunit but I got it the same error, so I'm not sure if this issue is a duplicate of #1858, because the mentioned workaround didn't work for me.

**Comment by piotrpMSFT** [comment]
Please pass `--infer-runtimes` to dotnet restore in order to fix this issue.

**Comment by piotrpMSFT** [comment]
@pafuent if `--infer-runtimes` does not fix, please reopen this issue.
