### ISSUE TITLE
dotnet does not work with forward slashes on windows

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2373]
## Steps to reproduce

```
PS C:\temp\HelloMvc\wwwroot> & 'C:\Program Files\dotnet\dotnet.exe' ../HelloMvc.dll
Could not load host policy library [../HelloMvc.dll]
```
## Expected  behavior

Forward slashes should be treated as path separator on windows
## Actual behavior

Could not load host policy library [../HelloMvc.dll]
## Important because?

When you publish you application on Mac/Linux it will put forward slashes into paths (the scenario I tired was to use publish-iis on non-Windows box)
## Environment data

`dotnet --info` output:

PS C:\temp\HelloMvc\wwwroot> & 'C:\Program Files\dotnet\dotnet.exe' --info
.NET Command Line Tools (1.0.0-beta-002256)

Product Information:
 Version:     1.0.0-beta-002256
 Commit Sha:  f49d95c47d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by moozzyk** [comment]
Related: https://github.com/aspnet/IISIntegration/issues/104

**Comment by danroth27** [comment]
@piotrpMSFT This seems like an annoyance for users. I don't think this blocks RC2, but should this be in for RTW?

**Comment by blackdwarf** [comment]
Is this something that is actually a corefx issue? 

/cc @piotrpMSFT

**Comment by blackdwarf** [comment]
This does not repro for me on PowerShell. The following command runs the app `dotnet ./bin/Debug/netcoreapp1.0/gjs.dll`.
