### ISSUE TITLE
Move debian packaging tools and scripts to packaging folder

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#238]
Hey @brthor, now that we have a `packaging` folder with `windows` and `osx` folders to hold the packaging tools, can we move the `package_tool`, `debian_config.json` and other necessary components to a `packaging/debian` folder?

**Comment by brthor** [comment]
Makes sense, the package_tool directory does look a little weird next to src and scripts :+1:

**Comment by anurse** [comment]
Coolio
