### ISSUE TITLE
dotnet-test-xunit does not target net451

### ISSUE THREAD

**Issue by thecodejunkie** [dotnet/cli#2380]
## Steps to reproduce
Add `dotnet-test-xunit` to a project with a `net451` target and 

## Expected  behavior
Looking at the [readme](https://github.com/dotnet/coreclr.xunit/blob/6ff4619831e2385d2fe664c64b0d28d95e5726ee/README.md) of the project states that

> This runner supports xUnit.net tests for **dotnet 4.5.1+**, and dotnet Core 5+ (this includes ASP.NET 5+).

so I would expect the package to be able to be used with a `net451` TFM. How else are we supposed to run xunit tests in a project that uses `project.json` and has a `net451` target? We can't use the
`xunit.runners.dnx` package anymore

## Actual behavior
It will fail with an error message saying that the dependency cannot be resolved. The [project.json](https://github.com/dotnet/coreclr.xunit/blob/6ff4619831e2385d2fe664c64b0d28d95e5726ee/src/dotnet-test-xunit/project.json#L17) for the project does not define the `net451` TFM 

Is this a bug, a missing TFM or something that won't be supported?

## Environment data
`dotnet --info` output:

**Comment by joplaal** [comment]
Also net46

**Comment by joplaal** [comment]
I think that's being addressed at https://github.com/dotnet/coreclr.xunit/pull/6

I expect that soon the dotnet-test-xunit will target net451 and net46

**Comment by blackdwarf** [comment]
Closing this one as the referenced PR has been merged. If this still repros, please reopen.
