### ISSUE TITLE
`dotnet run` lacks command-line arguments available in `dotnet test`

### ISSUE THREAD

**Issue by dougbu** [dotnet/cli#2383]
## Steps to reproduce

1. Execute `dotnet run --help`
2. Execute `dotnet test --help`
3. Execute `dotnet run -?` or another option that is listed in the `dotnet test --help` output but not `dotnet run --help`

## Expected  behavior
See similar options related to invoked build available.

## Actual behavior
```
invalid option -?
```

`dotnet test` has support for the following; `dotnet run` does not:
- `-?` # `dotnet run` does at least support `-h` and `--help`
- `-b|--build-base-path <OUTPUT_DIR>`
- `--no-build`
- -`o|--output <OUTPUT_DIR>`
- `-r|--runtime <RUNTIME_IDENTIFIER>`

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-beta-002275)

Product Information:
 Version:     1.0.0-beta-002275
 Commit Sha:  4af7437aa6

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by blackdwarf** [comment]
`dotnet run` and `dotnet test` are different commands used for different things. The help is aligned with their capabilities. I see no issue here, so closing this one.
