### ISSUE TITLE
'dotnet new' generates project referencing wrong package version

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#2386]
## Steps to reproduce
* Install the latest build (2330)
* Create a folder
* dotnet new

## Expected  behavior
Generated project.json should work

## Actual behavior
Generated project.json references bogus package version:

    "dependencies": {
      "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.0.0-rc2-3002330"
      }
    },

## Environment data
`dotnet --info` output:
C:\proj\clicon>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002330)

Product Information:
 Version:     1.0.0-rc2-002330
 Commit Sha:  3af38bf0fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment]
this package version is not bogus, 

The disconnect here is likely that we are not dropping the NuGet.config any longer so until we push RC2 packages to nuget.org, the dotnet new -> dotnet restore flow won't work.

**Comment by gregg-miskelly** [comment]
When I have a nuget.config, I see this
warn : Dependency specified was Microsoft.NETCore.App (>= 1.0.0-rc2-3002330) but ended up with Microsoft.NETCore.App 1.0.0-rc3-23909.

**Comment by gregg-miskelly** [comment]
Here is my nuget.config:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        
        <clear />
        <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
        <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
      </packageSources>
    </configuration>

**Comment by brthor** [comment]
Try Adding
`<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-cli/api/v3/index.json" />`

**Comment by brthor** [comment]
We made a big change to publish this metapackage from the CLI repo, today and yesterday

**Comment by gregg-miskelly** [comment]
Should I drop my dotnet-core myget feed, or do I want both?

This change seems pretty dangerous to me because unless you know about the new nuget feed you are going to wind up testing against main instead of rc2.

**Comment by gregg-miskelly** [comment]
Adding the new myget feed didn't seem to make a difference.

**Comment by brthor** [comment]
You can keep both, the version is compatible. 

I've verified the package is present:
https://dotnet.myget.org/gallery/dotnet-cli

**Comment by brthor** [comment]
Not sure what the long term publishing plan is here:
cc @weshaggard @eerhardt ?

**Comment by gregg-miskelly** [comment]
Adding the cli myget feed wasn't enough. I also needed to change the package version number (to 3002306 as of this moment). Otherwise I would wind up getting an rc3 package from the other repo.

**Comment by eerhardt** [comment]
We need to get our new metapackage published to the dotnet-core myget feed.  Currently that isn't an automated process.  @weshaggard are we going to automate it?

Basically every version of CLI needs the corresponding metapackage published somewhere.

**Comment by weshaggard** [comment]
I've almost got our publishing automated and it is currently pushing this to dotnet-cli feed but I will actually push it to the dotnet-core feed instead (or perhaps both).

**Comment by weshaggard** [comment]
I've published the later builds of the Microsoft.NETCore.App meta-package to the dotnet-core feed, and setup a build definition that should publish the latest builds as they complete.

**Comment by blackdwarf** [comment]
I believe this issue is not longer valid for latest templates. As another thing, with the rework of `dotnet new`, this issue will become not applicable. Will close.
