### ISSUE TITLE
Extract dotnet-compile-fsc tools to new repo

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#2388]
A new home for `dotnet-compile-fsc` is ready in https://github.com/dotnet/netcorecli-fsc.

how can we manage versioning alignment? ref dotnet/netcorecli-fsc#4 
Only a new package built from `netcorecli-fsc` is required to remove `dotnet-compile-fsc` from this repo?

/cc @brthor @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@enricosada still need something here?

**Comment by livarcocc** [comment]
I think this is done now.
