### ISSUE TITLE
Version 1.0.0.2339-beta Windows version doesn't work.

### ISSUE THREAD

**Issue by sirentek** [dotnet/cli#2389]
## Steps to reproduce
Run the installer to setup. After installation, run any dotnet command.
Type: "dotnet --version" or "dotnet --help"

## Expected  behavior
Output: "1.0.0-beta-002339".

## Actual behavior
Ouput: "The structure of init data has changed, do not know how to interpret it".

## Environment data
`dotnet --info` output:
"The structure of init data has changed, do not know how to interpret it".

**Comment by dougbu** [comment]
Found one workaround: `rimraf "$env:LocalAppData\Microsoft\dotnet"` or equivalent then reinstall `dotnet`.

**Comment by piotrpMSFT** [comment]
@schellap

**Comment by piotrpMSFT** [comment]
Was this install done MSI or ZIP?

**Comment by davidfowl** [comment]
I see this same thing on OSX in the asp.net build using the script

**Comment by schellap** [comment]
@davidfowl, There is a mismatch in the interface between hostfxr.dll and hostpolicy.dll. The hostpolicy is probably old. If you cleared out your install and unzipped the contents, do you still repro?

This PR makes the interface backwards compatible:
https://github.com/dotnet/cli/pull/2392

**Comment by schellap** [comment]
This fixes the installer to patch hostfxr even when it is in use.

https://github.com/dotnet/cli/pull/2377

**Comment by dougbu** [comment]
> Was this install done MSI or ZIP?

@davidfowl and I were building aspnet repos e.g. https://github.com/aspnet/Mvc, him on OSx and me on Windows. Those builds use `install.ps1` / `install.sh` scripts. The scripts download the Zip file.

I don't know if @sirentek's case is the same.

**Comment by sirentek** [comment]
@dougbu 
I used the .msi installer (Windows).

**Comment by natemcmaster** [comment]
Dup of https://github.com/dotnet/cli/issues/2194?

**Comment by sirentek** [comment]
I am closing this as this is a duplicate of https://github.com/dotnet/cli/issues/2194
