### ISSUE TITLE
`dotnet test` does not support `--project` command-line argument

### ISSUE THREAD

**Issue by dougbu** [dotnet/cli#2390]
Although it's poorly shown in the command-line help, `dotnet run` and `dotnet test` both support specifying the project to run / test on the command line. They do it in inconsistently, leading to confusion and frustration.
## Steps to reproduce
1. Execute `dotnet run --help`
2. Execute `dotnet test --help`
3. Execute `dotnet test --project test/project/project.json`
4. Execute `dotnet run test/project/project.json`
## Expected  behavior
- `-p, --project <arg>` is listed in both subcommand's help or neither's.
- Step 3 or 4 works.
## Actual behavior
- `test` help lacks information about a `-p, --project <arg>` argument
- Steps 3 and 4 fail, complaining that a `project.json` file does not exist in the current directory
- Doing the opposite of steps 3 and 4 i.e. using --project w/ `dotnet run` and leaving it out for `dotnet test`, works but the second is difficult to determine from the `dotnet test --help` output: The information is there but not as obvious as, say, `Usage: dotnet test [project] [options]`.

Separately, the `test` help also fails to mention mixing command-line arguments for the underlying test runner in with `[options]`.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-beta-002279)

Product Information:
 Version:     1.0.0-beta-002279
 Commit Sha:  76610c4cd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by smbecker** [comment]
Looks like you can now pass in a \<PROJECT\> argument to `dotnet test` but I would think it should be consistent with other command usage in that it is `-p|--project \<PROJECT\>`.

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
