### ISSUE TITLE
`dotnet restore` fails when --packages directory has spaces 

### ISSUE THREAD

**Issue by McNeight** [dotnet/cli#2395]
## Steps to reproduce

Extracted from corefx/init-tools.cmd:
"C:\Users\Neil\Documents\Visual Studio 2015\Projects\dotnet\corefx\Tools\dotnetcli\dotnet.exe" restore "C:\Users\Neil\Documents\Visual Studio 2015\Projects\dotnet\corefx\Tools\1.0.25-prerelease-00307-07\project.json" --packages "C:\Users\Neil\Documents\Visual Studio 2015\Projects\dotnet\corefx\packages\" --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
## Expected  behavior

Restoring packages for project.json. Changing the --packages directory to C:\Temp\ results in success.
## Actual behavior

`error: The given path's format is not supported.`
## Environment data

`dotnet --info` output:

```
Unknown option: --info
.NET Command Line Tools (1.0.0-beta-001598)
Usage: dotnet [common-options] [command] [arguments]
```

I realize that's not what you are looking for, so let me know what other information you need.

Possibly related to #948 and #985

-Neil

**Comment by blackdwarf** [comment]
This does not repro on the latest tooling. Will close. If it still repros on the latest from the rel/1.0.0, please reopen.
