### ISSUE TITLE
runtimeconfig.json ending up in class libraries built with the CLI

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#2396]
Just noticed this looking at the packages we generate with ASP.NET

![image](https://cloud.githubusercontent.com/assets/95136/14419608/c584f68e-ff7b-11e5-9031-77cc3dc3cc7d.png)

/cc @pranavkm @pakrym

**Comment by livarcocc** [comment]
@davidfowl I started always putting it there because of the project.json runtimeoptions. Should we just create it if the app is portable and/or the app contains a runtime options section in the project.json?

**Comment by livarcocc** [comment]
@davidfowl I started always putting it there because of the project.json runtimeoptions. Should we just create it if the app is portable and/or the app contains a runtime options section in the project.json?
