### ISSUE TITLE
Fix OS X install and uninstall procedure

### ISSUE THREAD

**Issue by alexandru** [dotnet/cli#2398]
## Steps to reproduce

Install the official PKG package for OS X (1.0.0-beta-001598).

## Expected  behavior

I expect OS X to install the pkg without warning of an unsigned package and I expect it to create an item in "Applications" that I can use for uninstalling, or at least see clear instructions for uninstalling in some document on `dotnet.github.io` (currently the subject [doesn't come up](https://www.google.com/search?q=uninstall+site:dotnet.github.io)). Though if it comes from a PKG, then it should be visible in "Applications", because that's the standard (Brew and MacPorts are a different story).

## Actual behavior

I see that it installs some files in `/usr/local/share/dotnet/bin/` (and I noticed that only because my `dotnet` executable is triggering errors on `dotnet run` due to another problem) and deleting files manually from `/usr/local/share` is always a bad idea. Please provide uninstall instructions.

Also, upon installation my system complains that the package isn't signed. Which rings all sorts of bells in my head, as I then start checking whether the download link was secure and try to establish a chain of trust (e.g. do I trust `github.io` to deliver these binaries, etc). I want to know for sure that these packages were built by Microsoft or whomever is in charge of building them.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

Thanks,

**Comment by alexandru** [comment]
Hello, so I really need to uninstall the PKG that I installed. Where can I find some instructions?

**Comment by blackdwarf** [comment]
@alexandru in general, best place to ask these kinds of questions is our Gitter channel, you are more likely to get immediate help there. 

PKGs, unfortunately, do not have an uninstall mechanism. Also, there is no rule that proscribes that PKGs install stuff into `Applications`. On the contrary, Application Bundles install there, while PKGs are free to do what they want/need. Take a look at the official Go PKG for instance which does a similar thing as dotnet one. There are many other examples. 

You can find pointers for uninstalling the PKG in our [known issues page](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/known-issues.md#uninstallingreinstalling-the-pkg-on-os-x). 

I will close this issue. If you think it should be reopened, please reopen.

**Comment by Kapulara** [comment]
A workaround I've found is:

`brew cask install dotnet`

and

`brew cask uninstall dotnet`

since brew has uninstall capabilities for dotnet 😄
