### ISSUE TITLE
Crossgen is failing for windows builds

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#240]
From the build logs
> *** Crossgening Roslyn compiler ... ***
10:39:07 
10:39:07 D:\j\workspace\Private\dotnet_cli_release_windows_nt_prtest>REM Copyright (c) .NET Foundation and contributors. All rights reserved. 
10:39:07 
10:39:07 D:\j\workspace\Private\dotnet_cli_release_windows_nt_prtest>REM Licensed under the MIT license. See LICENSE file in the project root for full license information. 
10:39:23 Crossgen failed...

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_cli_debug_windows_nt/125/console
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_cli_release_windows_nt/126/console

**Comment by anurse** [comment]
I've seen this too. I do like that we don't fail the build on this, at least on dev machines, since the result is still completely usable. Perhaps we should make the CI fail builds if crossgen fails though.

**Comment by agocke** [comment]
Fixed by #252
