### ISSUE TITLE
CLI Win32 Installer Fit and Finish

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#2400]
The CLI installer is rather busy and has some problems that I think can be quickly fixed, mostly via subtraction of elements.

Problems
- Too many font size/boldness/changes/ 
- Install should be the default button and on the right. 
- No need for a close button.
- No need for the weird language on the left under “Beta release”
- Ready? Set? No need for that.
- Even the logo is not needed.
- .NET is not capitalized there in the title.
- Not everyone knows what CLI means.
- Version is in the title, don’t need it in the left.
- Maybe make the title and header just ".NET Core 1.0." There is no CLI and the CLI is included.
- We know we are running Windows

Proposed Solution (Before and After)

BEFORE
![image](https://cloud.githubusercontent.com/assets/2892/14436056/c4ee1300-ffcf-11e5-9099-d360263aa7f8.png)

AFTER (less is more)

![image](https://cloud.githubusercontent.com/assets/2892/14436070/d44fad40-ffcf-11e5-8df7-a3594ba11843.png)

/cc @robmen @blackdwarf @DamianEdwards

**Comment by GuardRex** [comment]
There is a missing space after the privacy statement link in the license terms.

The license terms and the text at the link under "Collection and Use of Personal Data" are not specific enough IMO for `dotnet cli`, where `dotnet` command arguments and details about apps are shared with Microsoft unless the opt-out environment variable is set on the system.

It's also unclear if the automatic opt-in also applies to use of the `dotnet` command under the shared framework on servers.

Reference: https://github.com/dotnet/cli/pull/2145

**Comment by robmen** [comment]
I was talking to @terrajobst  and @richlander at Build saying if they provided a specific design they wanted, I'd be happy to implement it. I'm (unfortunately) the far from a talented UI designer. Is this the desired design?

PS: At some point, there was some desire to inform devs which build/branch they were installing in the UI.

**Comment by blackdwarf** [comment]
@robmen this would be the wanted design. 

Now that I look at what @shanselman wrote there are some changes also that I would make to his suggestion:

* ".NET Command Line" Should become ".NET Command Line Tools" because we are not building a shell.
* If everything on the left-hand side is removed, why not make the EULA window wider a bit? This way it is weird. 
* Is "Close" the same as cancel? If so, can we rename it to Cancel?

That would be it from me.

**Comment by blackdwarf** [comment]
@robmen I will assign to you for now, please re-assign if you think this is in error.

**Comment by piotrpMSFT** [comment]
This is pretty important. Let's get shiproom feedback on this tomorrow. Moving to RC2 for now.

**Comment by robmen** [comment]
Sorry, I'm not getting notifications from GitHub (either email nor on the web). What did shiproom decide?

**Comment by robmen** [comment]
@blackdwarf the difference between is Close and Cancel is that Close closes the window, Cancel prompts you if you want to cancel the operation. Can name them the same if you want.

Also note that @shanselman is proposing to do away with all the Close/Cancel buttons and have users bail by clicking red "X". Which way do you want to go?

Do you want to remove the Cancel button from the progress page (and just let people use the red "X")? Do you want to remove the Close button from the success/failure page?

**Comment by GerjanOnline** [comment]
> Also note that @shanselman is proposing to do away with all the Close/Cancel buttons and have users bail by clicking red "X". Which way do you want to go?

I just checked other installers and it seems 95% uses a "Cancel" button at the start of a wizard
https://www.google.nl/search?q=windows+installer+wizard&source=lnms&tbm=isch

**Comment by robmen** [comment]
@GerjanOnline That is true. If you want to continue to look like installers designed in 1997 then "Cancel" button in the bottom right corner on all pages is the way to go. That's the "Wizard 97" guidelines.

**Comment by blackdwarf** [comment]
@robmen don't know what we decided in the end, but I'm down with whatever @shanselman says. Honestly, the question was more for my education. :) Also, honestly, I click through that thing so fast... :)

**Comment by wli3** [comment]
![windows-1](https://cloud.githubusercontent.com/assets/6993335/26271899/f1dd1c88-3cc0-11e7-82cd-ec95401897ba.gif)

Is that better or worse?

Also can we go this extreme route below? I'm not sure it is enough for legal

![mockup](https://cloud.githubusercontent.com/assets/6993335/26271901/04785498-3cc1-11e7-9449-ac6bc83a2576.png)

**Comment by terrajobst** [comment]
I'm totally in love the single page mockup. We can chase up whether that's compliant with CELA.

**Comment by wli3** [comment]
The latest version of Windows installer is a lot simpler. Please reopen this issue if further discussion is needed
https://github.com/dotnet/cli/pull/6900
