### ISSUE TITLE
Dev builds fail unless rebased 

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2405]
## Steps to reproduce
Clone rel
`git reset --soft HEAD~1`

(This puts HEAD one commit behind master)

`build.cmd -Targets Prepare,Compile`

## Expected  behavior
Builds

## Actual behavior
`Could not load host policy library from [C:\Users\brthor\code\cli\artifacts\win10-x64\stage1\shared\Microsoft.NETCore.App\1.0.0-rc2-3002340]
This may be because the targeted framework [Microsoft.NETCore.App 1.0.0-rc2-3002340] was not found.`

Interestingly I see Microsoft.NETCore.App version `1.0.0-rc2-3002338` in my shared directory.
It seems like there is some mismatch in where the version comes from throughout the build.

## Environment data
`dotnet --info` output:

Not applicable. Using a branch a 2 or 3 commits behind.
On Windows 10.

**Comment by brthor** [comment]
@eerhardt Assigned you because you built this out. Feel free to redirect as necessary.

**Comment by eerhardt** [comment]
I'm not 100% sure I understand why this is a problem that needs to be fixed... We've made many breaking changes from build to build that require getting the latest code in order to build with Stage0.

**Comment by brthor** [comment]
This slows down the developer workflow. 

Right now every commit to rel will break the build in every branch until it's rebased. Sure we do make breaking changes, but not at that frequency.

If we get into a place where we are checking in 20 commits a day again (even if they're unrelated to the build), everyone will be spending half the day rebasing just to be productive.

**Comment by eerhardt** [comment]
It looks like an issue is that Stage0 is using its current Shared FX version when writing the dotnet.runtimeconfig.json out to the Stage1 sdk folder:

```JSON
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.0.0-rc2-3002339"
    }
  }
}
```

What controls writing this .json file?

**Comment by brthor** [comment]
The Executable class in Utils.

He's on vacation but maybe he'll see this @livarcocc

**Comment by eerhardt** [comment]
Looks like the project.lock.json file for src\dotnet says:

```
 "Microsoft.NETCore.App/1.0.0-rc2-3002339":
```

probably that is the highest number in my nuget cache, and since we are using * versions, it uses that one.

**Comment by brthor** [comment]
Ah, that's for sure an issue. Should we clean that package location at the beginning of the build? We do a similar thing for the test packages

**Comment by eerhardt** [comment]
yea, maybe.  I cleaned and am rebuilding now...

**Comment by eerhardt** [comment]
Even cleaning isn't going to help, since the package is on our cli-deps feed.  Maybe we also shouldn't be writing it there... @weshaggard ?

**Comment by eerhardt** [comment]
Another (terrible) option is to generate all the project.json files that use Microsoft.NETCore.App to have the current version in it...

**Comment by eerhardt** [comment]
I'm going to remove the `Microsoft.NETCore.App` package from our cli-deps feed, clean my cache, and then see if I can get past this error.

**Comment by eerhardt** [comment]
OK, I think what needs to happen is:

1. We never push Microsoft.NETCore.App to our cli-deps feed. @weshaggard to verify this is OK, and we aren't doing it anymore.
2. We clean the .nuget cache of Microsoft.NETCore.App during our build.  I will get a PR sent out for this today.

**Comment by weshaggard** [comment]
I'm not publishing that package to cli-deps feed I'm only publishing it to dotnet-core feed. 

I'm not entirely sure I understand why this is a problem. I would expect that if you go back in time you would still get the local built version of this package. To me this is a side-effect of using the `*` versioning which we might need to figure out if we want to use a specific version instead.

**Comment by eerhardt** [comment]
> I'm not entirely sure I understand why this is a problem.

This is a problem because if you switch branches, repos, etc you are going to start consuming the wrong Microsoft.NETCore.App package.  Even if you did something like:

1. commit 2 commits.
2. Build
3. squash your 1 commits into 1.
4. Build <-- This is now broken.

**Comment by brianrob** [comment]
Has there been any more movement here?  I've been hitting this over the last several days trying to develop a single change.

**Comment by gwicksted** [comment]
I got the same mysterious version number.  Noticed after installing the latest [CLI](http://dotnet.github.io/getting-started/#/windows) on Win 10 (previously had dnvm, dnu, dnx & about 6 versions of clr / coreclr previously installed).  Uninstalled all runtimes and tools, re-installed dotnet, cleared nuget cache and ran `dotnet new` + `dotnet update` and the problem still persists.  The new project file gets `3002339` which has a 3 in front so it can't be found.  Manually deleting the "3" from the version in the `project.json` + a `dotnet restore` fixes the issue enough that `dotnet run` is successful.  `dotnet` reports its version as `.NET Command Line Tools (1.0.0-rc2-002339)` while running the project reports: `project.json(7,31): warning NU1007: Dependency specified was Microsoft.NETCore.App >= 1.0.0-
rc2-002339 but ended up with Microsoft.NETCore.App 1.0.0-rc2-23931.`

**Comment by eerhardt** [comment]
Closing. Now that Microsoft.NETCore.App is getting built out of core-setup, we no longer have this issue.
