### ISSUE TITLE
Feedback on dotnet build for CI scenarios

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#2407]
I'm working on a real project, and for my CI scenarios here is what I'm doing.
1. Install dotnet cli 
2. Restore packages (_for .csproj and project.json_)
3. Build projects
4. Build NuGet package
5. Publish NuGet package to nuget.org

With .csproj I've used this pattern for several other projects and it's worked well for me. I'm also very experienced with build technologies.

On step #2 I build my .csproj projects to `OutputRoot\vs` and my `project.json` to `OutputRoot\dotnet`. I also copy my `.nuspec` file to `OutputRoot` so that I can use `nuget.exe pack` to produce the `.nupkg`.

On step #2 I'm calling the following to build my dotnet project.

```
dotnet build --configuration Release --build-base-path C:\Data\mycode\mutant-chicken\OutputRoot\dotnet --no-incremental
```

This results in the following directory structure in the `dotnet` folder.

```
OutputRoot
│   mutant-chicken.nuspec
│
├───dotnet
│   ├───Mutant.Chicken
│   │   ├───bin
│   │   │   └───Release
│   │   │       └───netstandard1.5
│   │   │               Mutant.Chicken.dll
│   │   └───obj
│   │       └───Release
│   │           └───netstandard1.5│
├───vs
        Mutant.Chicken.dll
```

After files are built into `OutputRoot` I copy the .nuspec to `OutputRoot` and then call `nuget.exe pack` to pack it.

The contents of the .nuspec file originally included the following.

```
  <files>
      <file src="vs\Mutant.Chicken.dll" target="lib\Mutant.Chicken.dll" />
      <file src="vs\Mutant.Chicken.pdb" target="lib\Mutant.Chicken.pdb" />
      <file src="vs\Replacements.json" target="tools\Replacements.json" />
      <file src="vs\Example.html" target="tools\Example.html" />

      <file src="dotnet\Mutant.Chicken\bin\Release\netstandard1.5\Mutant.Chicken.dll" target="lib\dotnet\Mutant.Chicken.dll" />
      <file src="dotnet\Mutant.Chicken\bin\Release\netstandard1.5\Mutant.Chicken.pdb" target="lib\dotnet\Mutant.Chicken.pdb" />
  </files>
```

Here you can see that I had to add a path of `dotnet\Mutant.Chicken\bin\Release\netstandard1.5\Mutant.Chicken.dll` to get the file included into the nuget package.

I ran into a situation where we have some tests cases failing on the CI server. So I switched my config to build using `Debug`. When I did that the step to create the .nupkg file failed obviously because the path in the .nuspec has `Release`.

I played around with options `--build-base-path` to see if I could prevent this but didn't see any options that would help me. I also tried to use `--output` but this requires that I pass `--frameworks`. I'd rather not do that because then it ties my build script to one or more specific frameworks. I also don't want to do that because I'd like to build once and get all my output files in the same go like I do with `--build-base-path`.

In my case I had to add special logic into my build script to move folders under `Release`/`Debug` to the `bin` folder directly.

I understand if this is the desired default behavior for VS customers, but this new behavior makes it more difficult when automating scenarios. Minimally there should be a flag to avoid creating the `Release`/`Debug` folder.

cc @davidfowl @BillHiebert

**Comment by piotrpMSFT** [comment]
This behavior was deprecated along with project.json
