### ISSUE TITLE
Stop using corehost to activate apps

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#2408]
## Steps to reproduce
`dotnet test` uses `corehost` to activate test xunit.dll

## Expected  behavior
`dotnet test` always uses the muxer to activate xunit.dll

## Actual behavior
corehost in `sdk` is being used.

## Environment data
`dotnet --info` output:

**Comment by brthor** [comment]
I thought we decided to leave this in for RC2?

The issue was resolving hostpolicy.dll from the nuget cache for standalone apps when we decided.

Do we still need to do that or no longer required?

**Comment by schellap** [comment]
I've added this for RTM. @gkhanna79

**Comment by brthor** [comment]
Going to work on this tomorrow, @schellap do you expect that the host should handle this scenario fine?

**Comment by schellap** [comment]
@brthor, we are RTM-ing. Let me know if you find anything busted. It should work as is.

**Comment by brthor** [comment]
Fixed in #3346
