### ISSUE TITLE
Some files are missing AuthentiCode signatures

### ISSUE THREAD

**Issue by joeloff** [dotnet/cli#2413]
Some of the runtime.win7-x64.* packages seem to have DLLs that are missing Authenticode signatures, e.g. runtime.win7-x64.Microsoft.NETCore.DotNetHost.1.0.0-rc2-00001, \runtimes\win7-x64\native\dotnet.exe is missing an Authenticode signature. Not sure if this is intentional.
Other files are hostfxr.dll, hostpolicy.dll and Microsoft.DotNet.Watcher.Core.dll and runtimes\win7-x64\lib\netstandard1.0\mscorlib.dll

**Comment by gkhanna79** [comment]
CC @weshaggard @joperezr @markwilkie - shouldn't the Windows mscorlib.dll be signed?

@piotrpMSFT @schellap can you please look into signing of hostfxr.dll and hostpolicy.dll?

@Sridhar-MS dotnet.exe signing sounds like https://github.com/dotnet/cli/issues/1103.

**Comment by ericstj** [comment]
@joeloff can you point us at the exact package you're seeing an unsigned mscorlib.dll in?  If I check https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc2-24008 I see that mscorlib.dll is SHA256 authenticode signed.

**Comment by weshaggard** [comment]
Yes I expect that mscorlib should be properly signed but the host assemblies may not be getting signed correctly. @schellap please follow-up on that.

**Comment by joeloff** [comment]
Talked to @ericstj The mscorlib came from a package we don't want to ship: Microsoft.TargetingPack.Private.CoreCLR.1.0.0-rc2-23931.nupkg

**Comment by gkhanna79** [comment]
@Sridhar-MS were you able to fix signing of hostfxr.dll and hostpolicy.dll?

**Comment by Sridhar-MS** [comment]
I have a PR out for this - https://github.com/dotnet/cli/pull/2439

**Comment by piotrpMSFT** [comment]
#2439 has been merged. This bug will get closed once VSO definition is updated by @Sridhar-MS

**Comment by Petermarcu** [comment]
@Sridhar-MS , have the VSTS definitions been updated?

**Comment by Sridhar-MS** [comment]
I have updated the VSTS definitions. Waiting for a build to complete successfully. I can close this issue after that.

**Comment by Sridhar-MS** [comment]
With the latest version (1.0.0-rc2-002392 x64 and x86) hostfxr.dll and hostpolicy.dll are both signed.
