### ISSUE TITLE
[dotnet publish] publish fails with ne --no-build flag

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2418]
## Steps to reproduce

from https://github.com/weidazhao/Hosting and follow the instruction in readme.md to setup Service Fabric SDK. After opening the Hosting.sln in VS, you can right-click Hosting.sfproj -> Package to repro the issue. 

## Expected  behavior

Publish to succeed.

## Actual behavior

1>------ Build started: Project: Microsoft.ServiceFabric.AspNetCore.Hosting, Configuration: Debug Any CPU ------
2>------ Build started: Project: Microsoft.ServiceFabric.AspNetCore.Gateway, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\Hosting\Microsoft.ServiceFabric.AspNetCore.Hosting" --configuration Debug --no-dependencies --build-base-path "C:\Repos\Hosting\artifacts"
2>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\Hosting\Microsoft.ServiceFabric.AspNetCore.Gateway" --configuration Debug --no-dependencies --build-base-path "C:\Repos\Hosting\artifacts"
1>  Compiling Microsoft.ServiceFabric.AspNetCore.Hosting for .NETFramework,Version=v4.5.2
2>  Compiling Microsoft.ServiceFabric.AspNetCore.Gateway for .NETFramework,Version=v4.5.2
1>  Compilation succeeded.
1>      0 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:00:04.3782632
1>
3>------ Build started: Project: Counter, Configuration: Debug Any CPU ------
4>------ Build started: Project: Sms, Configuration: Debug Any CPU ------
4>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\Hosting\Sms" --configuration Debug --no-dependencies --build-base-path "C:\Repos\Hosting\artifacts"
2>  Compilation succeeded.
2>      0 Warning(s)
2>      0 Error(s)
2>  Time elapsed 00:00:05.2997171
2>
5>------ Build started: Project: Gateway, Configuration: Debug Any CPU ------
4>  Compiling Sms for .NETFramework,Version=v4.5.2
4>  Compilation succeeded.
4>      0 Warning(s)
4>      0 Error(s)
4>  Time elapsed 00:00:07.7961812
4>
5>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\Hosting\Gateway" --configuration Debug --no-dependencies --build-base-path "C:\Repos\Hosting\artifacts"
3>  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\Hosting\Counter" --configuration Debug --no-dependencies --build-base-path "C:\Repos\Hosting\artifacts"
5>  Compiling Gateway for .NETFramework,Version=v4.5.2
3>  Compiling Counter for .NETFramework,Version=v4.5.2
5>  Compilation succeeded.
5>      0 Warning(s)
5>      0 Error(s)
5>  Time elapsed 00:00:05.2837549
5>
3>  Compilation succeeded.
3>      0 Warning(s)
3>      0 Error(s)
3>  Time elapsed 00:00:05.7480350
3>
6>------ Build started: Project: Hosting, Configuration: Debug x64 ------
========== Build: 6 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
-------- Package started: Project: Hosting, Configuration: Debug x64 ------
  C:\Program Files\dotnet\dotnet.exe build "C:\Repos\Hosting\Counter" --configuration Debug --no-dependencies --build-base-path "C:\Repos\Hosting\artifacts"
  Project Counter (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation.
  Environment variables:
  Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\extensions\microsoft\web tools\external;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\AegisTools\Bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Users\dazhao\.dnx\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\extensions\microsoft\web tools\external\.git
  **C:\Program Files\dotnet\dotnet.exe publish "C:\Repos\Hosting\Counter" -o "C:\Users\dazhao\AppData\Local\Temp\PublishTemp\Counter38" -c Debug --no-build
  Publishing Counter for .NETFramework,Version=v4.5.2/win7-x64
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(154,5): error : Could not find a part of the path 'C:\Repos\Hosting\Counter\bin\Debug\net452\win7-x64\Counter.exe'.**
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Service Fabric Tools\Microsoft.VisualStudio.Azure.Fabric.ApplicationPackage.targets(306,5): error : C:\Users\dazhao\AppData\Local\Temp\Counter doesn't exist.
-------- Package: Project: Hosting failed, Time elapsed: 00:00:08.8312220 --------

## Environment data
`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-beta-002275)

Product Information:
 Version:     1.0.0-beta-002275
 Commit Sha:  4af7437aa6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

C:\Windows\system32>

**Comment by cdmihai** [comment]
After some quick testing, it seems that dotnet publish does not know the --build-base-path very well. If build is called with --build-base-path, then publish --no-build trips over:

```
C:\projects\tests\proj> dotnet new
Created new C# project in C:\projects\tests\proj.
C:\projects\tests\proj> dotnet restore
log  : Restoring packages for C:\projects\tests\proj\project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: C:\projects\tests\proj\project.lock.json
log  : C:\projects\tests\proj\project.json
log  : Restore completed in 1326ms.

NuGet Config files used:
    C:\Users\micodoba\AppData\Roaming\NuGet\NuGet.Config
C:\projects\tests\proj> dotnet build --build-base-path ../base
Compiling proj for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.4255910

C:\projects\tests\proj> dotnet publish --no-build
Publishing proj for .NETCoreApp,Version=v1.0
Could not find file 'C:\projects\tests\proj\bin\Debug\netcoreapp1.0\proj.dll'.
C:\projects\tests\proj> dotnet publish --no-build --build-base-path ..\base
Publishing proj for .NETCoreApp,Version=v1.0
Could not find file 'C:\projects\tests\proj\bin\Debug\netcoreapp1.0\proj.dll'.
```

**Comment by cdmihai** [comment]
@pakrym, how should publish work when --build-base-path is used with build?

**Comment by pakrym** [comment]
@cdmihai `dotnet publish --no-build --build-base-path ..\base` should work fine, I'll take a look why it doesn't work.

**Comment by abpiskunov** [comment]
I just updated tooling to add --build-base-path and also see publish still failing. For me error was Could not find a part of the path 'C:\Users\antonpis\Documents\Visual Studio 2015\Projects\WebApplication7\src\WebApplication7\bin\Release\netcoreapp1.0\WebApplication7.dll'.  

where correct path should be 'C:\Users\antonpis\Documents\Visual Studio 2015\Projects\WebApplication7\**artifacts**\src\WebApplication7\bin\Release\netcoreapp1.0\WebApplication7.dll'
