### ISSUE TITLE
Can not find runtime target for framework '.NETFramework,Version=v4.5.1' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#2423]
## Steps to reproduce
Test sample
[zaxitech_core_demo.zip](https://github.com/dotnet/cli/files/215480/zaxitech_core_demo.zip)

## Actual behavior
C:\downloads\web\projects\zaxitech_core_demo\src\tbweb>dotnet run
Can not find runtime target for framework '.NETFramework,Version=v4.5.1' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by Kukkimonsuta** [comment]
I've encoutered similiar error, see my answer in #2442 for possible solution

**Comment by xatabhk** [comment]
I find the issue has got fixed in 1.0.0-rc2-002392.
