### ISSUE TITLE
Microsoft.NETCore.App references wrong version of Microsoft.NETCore.DotNetHostPolicy

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2424]
## Steps to reproduce
Restore app targeting `Microsoft.NETCore.App/1.0.0-rc2-24011`

## Expected  behavior
Microsoft.NETCore.App references latest corehost packages it was built agains

## Actual behavior
```
"Microsoft.NETCore.App/1.0.0-rc2-24011": {
    "dependencies": {
      ...
       "Microsoft.NETCore.DotNetHostPolicy": "1.0.0-rc2-00001",
      ...
    }
}
```
@Petermarcu @eerhardt @schellap @piotrpMSFT @pranavkm

**Comment by pakrym** [comment]
This is general cause of https://github.com/dotnet/cli/issues/2421

**Comment by eerhardt** [comment]
This is a wrong package version.  Valid `Microsoft.NETCore.App` versions look like `1.0.0-rc2-3` + the CLI version.

So you want to use `1.0.0-rc2-3002339` or something similar.

(Also - rc2-24011 was a bad/mistake build).  @ellismg @joshfree - can we get those packages taken down from the dotnet-core feed?
