### ISSUE TITLE
Project.json Dependencies renamed to Framework in runtimeconfig.json

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2425]
<img width="553" alt="screen shot 2016-04-12 at 10 16 21 am" src="https://cloud.githubusercontent.com/assets/9561583/14469058/b15998be-0097-11e6-82e2-6dce418ad8ab.png">
## Steps to reproduce

dotnet new
dotnet restore
dotnet build

cat /bin/Debug/netcoreapp1.0/app.runtimeconfig.json
## Expected  behavior

Please don't reuse names like "Frameworks" (in project.json) vs "Framework" (in runtimeconfig.json) and changing meaning (Dependencies become Framework) is confusing.

It would be great if the runtimeconfig.json setting for Dependencies was called Dependencies and not Framework.
## Actual behavior

Confusion on why the _dependency_ "Microsoft.NETCoreApp" lives in a hive called _framework_ in the runtimeconfig.json settings file.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by piotrpMSFT** [comment]
closing as there is no more project.json
