### ISSUE TITLE
No way to set '32BITREQ' flag when compiling desktop exes

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#2428]
## Steps to reproduce
1. Write an app that targets `net451` and takes a dependency on a native library
2. Publish the app for `win7-x86`
3. Run the output with `dotnet run`
## Expected  behavior

The application runs
## Actual behavior

```
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```

This affects both `dotnet run` and `dotnet build / exec`. The user has to manually run `corflags` to set the necessary bit on the output.

**NOTE**: If the user is on a 32-bit Machine, this issue does not occur, since the framework initializes the application as a 32-bit process. The problem occurs when launching the 32-bit publish output on a 64-bit machine.

**Comment by anurse** [comment]
Note there are tests in the PublishDesktopTests file in dotnet-publish.Tests which had to be disabled because of this.

**Comment by anurse** [comment]
Discussed this with @DamianEdwards and @davidfowl. This is a pretty broken scenario. It will mean that any application published for `net451/win7-x86` that uses native binaries will **only** work on a true 32-bit OS, it won't work on WoW.

I have some ideas for quick low-impact fixes, I'll work them out and post back to this thread.

**Comment by anurse** [comment]
We came up with a low-impact initial fix for RC2. For desktop builds, we will send the `/platform` switch to csc even if no value is provided. It will default to `anycpu32bitpreferred` in the 32-bit CLI and to `x64` in the 64-bit CLI. This does mean that if I want to build a 64-bit app on 32-bit Windows, I'm going to have a problem, but this was the best model we could come up with that would work in RC2. Leaving this bug open to evaluate it post-RC2 based on customer feedback. /cc @DamianEdwards @pakrym

**Comment by piotrpMSFT** [comment]
@anurse looks like this can be closed, then?

**Comment by anurse** [comment]
It would be something handled over in MSBuild land. I think it's safe to close this issue though.
