### ISSUE TITLE
Trying to dotnet run with framework from non-project.json directory causes `Object reference not set to an instance of an object.` error.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#2429]
## Steps to reproduce
1. Go to directory without a project.json
1. Type dotnet run -f .NETStandardApp1.5

## Expected  behavior
Some appropriate error about the current directory not having a project.json

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/2008729/14470112/9dbc1138-009c-11e6-9bf6-5cc1766c2211.png)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by enricosada** [comment]
without `-f` fails as expected

```
e:\noproj>dotnet run
Could not find file 'e:\noproj\project.json'.
```

**Comment by smbecker** [comment]
I see the same exception when trying to build [cli-samples/HelloWeb](https://github.com/aspnet/cli-samples/tree/master/HelloWeb) after changing the framework to 'net451'

**Comment by smbecker** [comment]
Also seeing this on a project that I am currently attempting to upgrade to rc2. I can build the app using `-f netcoreapp1.5` but when I try to use `net46`, I get this exception.

**Comment by smbecker** [comment]
Turns out that I had a bad dependency but the error message did not help me diagnose that at all.

**Comment by smbecker** [comment]
It looks like this issue happens whenever you have an issue anywhere in your dependency hierarchy. It gives no clues as to where that issue might be. Better diagnostics or messaging would be much appreciated.

**Comment by roji** [comment]
Using 1.0.0-rc2-002678, simply trying to execute `dotnet run` in an empty directory gives an NRE.

**Comment by AArnott** [comment]
I just installed 'latest' from the readme and got 1.0.0-preview1-002702. Where are folks getting the newer rc2?
With the version I have, 'dotnet build' produces a folder without an .exe and without a project.json file. "dotnet run" in that folder produce this same NRE.

**Comment by eerhardt** [comment]
> I just installed 'latest' from the readme and got 1.0.0-preview1-002702. Where are folks getting the newer rc2?

That is the correct version of the CLI tools for ".NET Core 1.0 RC2 - SDK Preview1".  The CLI is "preview1", the runtime is "RC2".

> With the version I have, 'dotnet build' produces a folder without an .exe and without a project.json file. "dotnet run" in that folder produce this same NRE.

`dotnet run` is a dev-time command, you call it from the same folder as your `project.json` file, not your output directory.  If you want to run your app directly call `dotnet your-app-name.dll` from the output folder.

**Comment by eerhardt** [comment]
> Using 1.0.0-rc2-002678, simply trying to execute dotnet run in an empty directory gives an NRE.

This was logged as issue #2965, which didn't make it into "Preview1".  Instead it was fixed with #2980 in "Preview2".

**Comment by AArnott** [comment]
> If you want to run your app directly call dotnet your-app-name.dll from the output folder.

That doesn't work either:

```
 dir


    Directory: C:\git\dotnettry3\bin\Debug\netcoreapp1.0\publish


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        5/16/2016   9:49 PM          84264 dotnettry3.deps.json
-a----        5/16/2016   9:49 PM           4608 dotnettry3.dll
-a----        5/16/2016   9:49 PM          11776 dotnettry3.pdb
-a----        5/16/2016   9:49 PM            137 dotnettry3.runtimeconfig.json


C:\git\dotnettry3\bin\Debug\netcoreapp1.0\publish> dotnet run .\dotnettry3.dll
Object reference not set to an instance of an object.
```

**Comment by piotrpMSFT** [comment]
Closed, since fixed in preview2.
