### ISSUE TITLE
[dotnet publish] Passing in bogus --runtime does not throw an error (or warning)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2430]
## Steps to reproduce

dotnet new
dotnet restore
dotnet publish -r "garbage_blah"
## Expected  behavior

An error saying RID "garbage_blah" was either ignored or not understood.
## Actual behavior

It publishes without an error or warning.

BTW, I noticed this since I had mistyped "osx.10.11-x64" and did not notice it was wrong because dotnet did not complain.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by livarcocc** [comment]
This is now being tracked here: https://github.com/dotnet/sdk/issues/324.
