### ISSUE TITLE
[dotnet publish] Publishing NETStandard.Library includes non-referenced assemblies in publish output

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2431]
## Steps to reproduce
dotnet new
vi project.json
{
  "version": "1.0.0-*",
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-23931"
  },
  "runtimes" : {
    "osx.10.11-x64": {}
  },
  "frameworks": {
    "netstandard1.5": {}
  }
}
dotnet restore
dotnet publish -r "osx.10.11-x64"
ls bin/Debug/netstandard1.5/publish

## Expected  behavior
Only the app.dll and pdb should be published

## Actual behavior
find bin/Debug/netstandard1.5/publish/ -name "*" -print
bin/Debug/netstandard1.5/publish/
bin/Debug/netstandard1.5/publish//d.lib_f.standard.dll
bin/Debug/netstandard1.5/publish//d.lib_f.standard.pdb
bin/Debug/netstandard1.5/publish//runtimes
bin/Debug/netstandard1.5/publish//runtimes/linux
bin/Debug/netstandard1.5/publish//runtimes/linux/lib
bin/Debug/netstandard1.5/publish//runtimes/linux/lib/netstandard1.3
bin/Debug/netstandard1.5/publish//runtimes/linux/lib/netstandard1.3/System.IO.FileSystem.Watcher.dll
bin/Debug/netstandard1.5/publish//runtimes/osx
bin/Debug/netstandard1.5/publish//runtimes/osx/lib
bin/Debug/netstandard1.5/publish//runtimes/osx/lib/netstandard1.3
bin/Debug/netstandard1.5/publish//runtimes/osx/lib/netstandard1.3/System.IO.FileSystem.Watcher.dll
bin/Debug/netstandard1.5/publish//runtimes/unix
bin/Debug/netstandard1.5/publish//runtimes/unix/lib
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.3
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.3/System.IO.Compression.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.3/System.Security.Cryptography.Csp.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.3/System.Security.Cryptography.Encoding.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.3/System.Threading.Overlapped.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.4
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.4/System.Security.Cryptography.Algorithms.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.4/System.Security.Cryptography.Cng.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.4/System.Security.Cryptography.OpenSsl.dll
bin/Debug/netstandard1.5/publish//runtimes/unix/lib/netstandard1.4/System.Security.Cryptography.X509Certificates.dll
bin/Debug/netstandard1.5/publish//runtimes/win
bin/Debug/netstandard1.5/publish//runtimes/win/lib
bin/Debug/netstandard1.5/publish//runtimes/win/lib/netstandard1.3
bin/Debug/netstandard1.5/publish//runtimes/win/lib/netstandard1.3/System.Security.Cryptography.Csp.dll
bin/Debug/netstandard1.5/publish//runtimes/win/lib/netstandard1.3/System.Threading.Overlapped.dll
bin/Debug/netstandard1.5/publish//runtimes/win/lib/netstandard1.4
bin/Debug/netstandard1.5/publish//runtimes/win/lib/netstandard1.4/System.Security.Cryptography.Cng.dll
bin/Debug/netstandard1.5/publish//runtimes/win/lib/netstandard1.4/System.Security.Cryptography.OpenSsl.dll
bin/Debug/netstandard1.5/publish//runtimes/win7
bin/Debug/netstandard1.5/publish//runtimes/win7/lib
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.3
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.3/System.IO.Compression.dll
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.3/System.IO.FileSystem.Watcher.dll
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.3/System.Net.Http.dll
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.3/System.Security.Cryptography.Encoding.dll
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.4
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.4/System.Security.Cryptography.Algorithms.dll
bin/Debug/netstandard1.5/publish//runtimes/win7/lib/netstandard1.4/System.Security.Cryptography.X509Certificates.dll
bin/Debug/netstandard1.5/publish//System.Buffers.dll
bin/Debug/netstandard1.5/publish//System.Collections.Concurrent.dll
bin/Debug/netstandard1.5/publish//System.Diagnostics.DiagnosticSource.dll
bin/Debug/netstandard1.5/publish//System.IO.Compression.ZipFile.dll
bin/Debug/netstandard1.5/publish//System.IO.FileSystem.Primitives.dll
bin/Debug/netstandard1.5/publish//System.Linq.dll
bin/Debug/netstandard1.5/publish//System.Net.Http.dll
bin/Debug/netstandard1.5/publish//System.ObjectModel.dll
bin/Debug/netstandard1.5/publish//System.Runtime.InteropServices.PInvoke.dll
bin/Debug/netstandard1.5/publish//System.Runtime.Numerics.dll
bin/Debug/netstandard1.5/publish//System.Security.Cryptography.Primitives.dll
bin/Debug/netstandard1.5/publish//System.Text.RegularExpressions.dll
bin/Debug/netstandard1.5/publish//System.Threading.dll
bin/Debug/netstandard1.5/publish//System.Threading.Tasks.Extensions.dll
bin/Debug/netstandard1.5/publish//System.Threading.Thread.dll
bin/Debug/netstandard1.5/publish//System.Xml.ReaderWriter.dll
bin/Debug/netstandard1.5/publish//System.Xml.XDocument.dll

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
[project.json.txt](https://github.com/dotnet/cli/files/215646/project.json.txt)

**Comment by cdmihai** [comment]
I think you have to add "type": "Platform" for dependency subgraphs that should be retrieved from the shared framework and not copied on publish.

**Comment by jeffschwMSFT** [comment]
I am not looking to 'fix' this case by changing it, but rather see it working in as a standalone project.  Adding "type": "platform" will make it sharedfx again.

**Comment by blackdwarf** [comment]
Well, this issue is not valid anymore since the guidance is to depend on `netcoreapp1.0` and its associated metapackage. Closing this. Reopen if more input is needed.
