### ISSUE TITLE
Provide a way to disable the package downgrade warnings

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#2434]
Those messages create a lot of noise and sometimes we're okay with the downgrade. But there are so many messages of that type that finding any useful information between them is a pain. Here's an example: https://ci.appveyor.com/project/aspnetci/dnx-watch/build/1.0.229 (more than 30K messages just about that).

**Comment by victorhurdugaci** [comment]
Also, our logs are 10 times the regular size because of these messages http://aspnetci/viewLog.html?buildId=81701&buildTypeId=UniverseCoherence&tab=buildLog&state=&expand=none#_

**Comment by blackdwarf** [comment]
This has to do with the default verbosity levels in `dotnet restore` as well. This is covered in #1623 I believe. 

/cc @piotrpMSFT

**Comment by blackdwarf** [comment]
Will close this since `dotnet restore` sets a different, less verbose level in its call to Nuget.
