### ISSUE TITLE
Move TestAsset Apps from NETStandard.Library to Microsoft.NETCore.App

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2438]
This is cleaning up Test Debt.

To do this we must generate stub NuGet packages for each of the host packages for each rid they support other than the rid of the current platform.

This is needed for 2 reasons:
- `--infer-runtimes` in nuget restores both x86 and x64 rids on windows platforms, but we only build a host for one of those rids
- `--infer-runtimes` does not override or filter rids which exist in a project.json. As a result of this, our standalone test assets are restored against all rids they list, and we need stub host packages for each of these rids.

cc @eerhardt @piotrpMSFT

**Comment by piotrpMSFT** [comment]
Migrating to NetCoreApp forces us to resolve build/restore failures project-by-project. This will likely take another day since we need to iterate over many issues.

**Comment by brthor** [comment]
TestAssets are converted
TestAssets are building

After getting test runs last night we had 69 test failures.

Reduced this to 38, and working through them.

**Comment by piotrpMSFT** [comment]
This PR should be getting merged tonight.

**Comment by piotrpMSFT** [comment]
This is approved by @Petermarcu in my office. Let's merge once this is CR'd.

**Comment by brthor** [comment]
Changes are green, but given the Post code review concerns around the stub nuget packages getting published to our feed, this is more likely coming tomorrow morning.

**Comment by brthor** [comment]
This is merged.
