### ISSUE TITLE
Project.json with dependency "Microsoft.NETCore.App" and framework "NetStandard1.5" should be disallowed

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2440]
## Steps to reproduce

dotnet new
vi project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002349"
    }
  },
  "runtimes" : {
     "osx.10.11-x64": {}
  },
  "frameworks": {
    "netstandard1.5": {}
  }
}
dotnet restore
## Expected  behavior

This should give an error message that says this combination does not make sense and offer a suggestion.  
1) If you want a .NET Core App then use framework "netcoreapp1.0".  
2) If you want a portable .NET library use dependency "NETStandard.Library"
## Actual behavior

dotnet-restore and dotnet-build work, but dotnet-run, dotnet-publish, dotnet-pack all return incorrect results due to the mix match of dependencies and frameworks.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by gulbanana** [comment]
what if I want a nonportable library- a library which only works on .net core?

**Comment by anurse** [comment]
This shouldn't be handled specially. If we want to make it an error, we should apply the necessary framework conditions on dependencies/packages. We shouldn't be special-casing this. I believe Microsoft.NETCore.App was designed this way intentionally, and changing it's framework restrictions would be a discussion for dotnet/corefx.

**Comment by livarcocc** [comment]
Now, you actually get an error message during restore that M.NC.App is not compatible with the netstandard TFM.
