### ISSUE TITLE
Can not find runtime target for framework '.NETFramework,Version=v4.5.1'

### ISSUE THREAD

**Issue by jcsotoo92** [dotnet/cli#2442]
i get this error when i try to run my app with the command dotnet run

Can not find runtime target for framework '.NETFramework,Version=v4.5.1' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run dotnet restore
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.

**Comment by Kukkimonsuta** [comment]
I have encountered same error, but noticed on fresh machine everything worked. I managed to make work on my old build by removing package cache (on windows located in `%SYSTEMDRIVE%%HOMEPATH%\.nuget\packages`) and reinstalling .net cli (not sure whether the second step was required).

**Comment by jcsotoo92** [comment]
it works thanks @Kukkimonsuta

**Comment by sapan-desai** [comment]
Nopes, still does not work for me. Any help anyone?

**Comment by oviwankenobi** [comment]
same problem here

error : Can not find runtime target for framework '
1>.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x6
1>4, win81-x64, win8-x64, win7-x64'. Possible causes:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 1. The project has not been restored or res
1>tore failed - run `dotnet restore`
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 2. The project does not list one of 'win10-
1>x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 3. You may be trying to publish a library,
1>which is not supported. Use `dotnet pack` to distribute libraries.

the 1st one listed for sure is not the culprit, running donet restore there's no error.
the 3rd one...? I am not sure.
who to approach verifying the 2nd and 3rd?

thank

**Comment by svick** [comment]
@oviwankenobi Can you post your project.json?

**Comment by oviwankenobi** [comment]
{
    "dependencies": {
        "Microsoft.EntityFrameworkCore.Tools": {
            "version": "1.0.0-*",
            "type": "build"
        },
        "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
        "Microsoft.AspNetCore.Mvc": "1.0.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.Extensions.Caching.Abstractions": "1.0.0",
        "Microsoft.Extensions.Caching.Memory": "1.0.0",
        "Microsoft.Extensions.Configuration": "1.0.0",
        "Microsoft.Extensions.Configuration.Binder": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.NETCore.App": "1.0.0",
        "Microsoft.AspNetCore.Authentication": "1.0.0"
    },

    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": {
            "version": "1.0.0-*",
            "imports": "portable-net452+win81"
        }
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    },

    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    },

    "publishOptions": {
        "include": [
            "wwwroot",
            "Views",
            "appsettings*.json",
            "web.config"
        ]
    },

    "tooling": {
        "defaultNamespace": "testAPI"
    }
}
//--------------------------------------------------------------------------------
UPDATE:
if I add the lines below 
    "runtimes": {
        "win10-x86": {},
        "win10-x64": {}
    },
and then run "dotnet restore" and "dotnet build" is building fine.
but if I want to target linux runtime or mac runtime what are the correct values then?
also an empty project generated by the asp.net MVC (.net core) template is not writing in project.json "runtimes" section and it builds fine. how come?

**Comment by svick** [comment]
@oviwankenobi See [the *.NET Core App Types* article in .Net Core docs](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types). You either need to specify `"Microsoft.NETCore.App"` as `"type": "platform"` or you need to specify all the `"runtimes"` you want to build for.

And you don't target Linux in general, you have to target each distribution separately.  The available values [are listed here](https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog#using-rids).
