### ISSUE TITLE
Remove Publish Fallback behavior when #2220 goes in

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2444]
#2220

Contains fallback behavior so that existing projects without a host dependency can be published as standalone. 

As we move forward a Standalone app will have a requirement to have a host available in it's package graph for publishing.

We should remove the fallback behavior altogether which is blocked on #2438

**Comment by gkhanna79** [comment]
@brthor Is this for RC2?

**Comment by brthor** [comment]
This is in the RC2 Milestone

**Comment by livarcocc** [comment]
I don't think this is an issue anymore.
