### ISSUE TITLE
Changes to shared files in a dependent project don't trigger incremental build

### ISSUE THREAD

**Issue by atanasa** [dotnet/cli#2456]
## Steps to reproduce
1. Create a shared project with this project.json:

```
{
    "name": "DebugConsole.Shared",
    "shared": [ "**/*.cs" ],
    "compileExclude": [ "**/*.cs" ],
    "frameworks": {
        "net451":{},
        "netstandard1.3":{
            "dependencies": {
                "System.Runtime": "4.1.0-rc3-23907"
            }
        }
    }
}
```
1. Add a .cs file to that project
2. Create a project to consume the above project like this:

```
{
    "name": "DebugConsole",
    "dependencies": {
        "DebugConsole.Shared": "*"
    },
    "frameworks": {
        "net451":{}
    }
}
```
1. Build the two projects with dotnet restore => dotnet build
2. Modify the shared .cs file in a way that fails the compilation.
3. Build the second project (DebugConsole) by running dotnet build
## Expected  behavior

The build fails as the shared .cs files to compile.
## Actual behavior

The build is skipped.
The output of the build is:
Project DebugConsole (.NETFramework,Version=v4.5.1) was previously compiled. Skipping compilation.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002347)

Product Information:
 Version:     1.0.0-rc2-002347
 Commit Sha:  5f2183489f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

The full sample code to reproduce it:
[SharedProjectSample.zip](https://github.com/dotnet/cli/files/217023/SharedProjectSample.zip)

**Comment by piotrpMSFT** [comment]
I wanted to test this in preview3 but found that `shared` is not being migrated yet. I opened https://github.com/NuGet/Home/issues/3914 to determine where the property should go. @livarcocc we need to make sure this gets to a conclusion.

**Comment by piotrpMSFT** [comment]
Once we migrate `shared` to content per NuGet/Home#3914 this should be resolved.

**Comment by piotrpMSFT** [comment]
I just tried repro'ing this and found it is fixed in preview5. Steps followed:

1. mkdir app
2. mkdir lib
3. cd lib
4. dotnet new -t lib
5. dotnet restore
6. dotnet build
7. cd ../app
8. dotnet new
9. dotnet add p2p ../lib/lib.csproj
10. dotnet restore
11. dotnet build 
12. echo "asdf" > ../lib/asdf.cs
13. dotnet build

Result:
asdf.cs(1,1): error CS0116: A namespace cannot directly contain members such as fields or methods [/Users/piotrp/code/repro/r2456/msbuild/lib/lib.csproj]
