### ISSUE TITLE
Debugger fails when you have special characters in your home path

### ISSUE THREAD

**Issue by xal1983** [dotnet/cli#2458]
Hi
I installed the latest insiders release of vscode, then RC2 for 4/8 of omnisharp.
Opened a project and vs code reported it was getting the debugger bits.
It successfully downloaded a bunch of nuget packages, but then it failed at this step (log):

```
Installed:
    128 package(s) to C:\Users\Andrés\.vscode-insiders\extensions\ms-vscode.csharp-1.0.1-rc2\coreclr-debug\project.json
Publishing dummy for .NETStandardApp,Version=v1.5/win7-x64
Error: Access to the path 'C:\Users\AndrÃ©s\.vscode-insiders....
```

You can see there that nuget respects the "é" character but then publishing uses a wrong encoding and fails.

.NET Command Line Tools (1.0.0-rc2-002374)

Product Information:
 Version:     1.0.0-rc2-002374
 Commit Sha:  f82da07fc4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
I'm closing this as duplicate. I know this issue was first, but we have already marked #2486 during triage.
