### ISSUE TITLE
Enable dotnet compile --native for Mac

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#246]
We should get the basic pieces in for Mac and test the CPP mode. We will enable the JIT mode once we have the supporting packages made available tracked by https://github.com/dotnet/corert/issues/327.

**Comment by natemcmaster** [comment]
Until then, we should consider showing an error that says "not supported". At the very least, fix the error message (which complains about `Unrecognized option '--output'` when "--native" is the issue).

```
$ dotnet compile --native     
Compiling ConsoleApp for .NETPlatform,Version=v5.4

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.9028840

Specify --help for a list of available options and commands.
Microsoft.Dnx.Runtime.Common.CommandLine.CommandParsingException: Unrecognized option '--output'
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.Native.Program.ExecuteApp(CommandLineApplication app, String[] args)
```

**Comment by gkhanna79** [comment]
These are known issues @brthor and @livarcocc are working upon to fix.

**Comment by brthor** [comment]
@gkhanna79 @schellap 

Are Mac Versions of ILCompiler Available on your feed? If not when should we expect them?

As this is coming up the Mac ILCompiler package should not declare a dependency on ObjectWriter or Ryujit until those packages are also available, or restore will break.

**Comment by schellap** [comment]
@kyulee1, do you have an objwriter and ryujit for OSX for Mac?

**Comment by gkhanna79** [comment]
@brthor @schellap - we will have them tomorrow. However, can we validate that Mac CPP works?

**Comment by brthor** [comment]
@gkhanna79 We just need the mac version of the toolchain package available somewhere that doesn't depend on Ryujit or ObjectWriter

**Comment by kyulee1** [comment]
https://github.com/dotnet/corert/issues/327 @russellhadley is working on ryujit/objwriter packages for OSX.

**Comment by brthor** [comment]
@kyulee1 @russellhadley @gkhanna79 Are these packages available currently?

**Comment by piotrpMSFT** [comment]
@Sridhar-MS is going to work with @anurse and others to figure out the story for where runtimes come from and how they're referenced.

**Comment by gkhanna79** [comment]
@piotrpMSFT I am not sure I follow your comment. Can you please elaborate?

For Mac, CPP compilation was enabled last week before Thanksgiving break. 

CC @schellap

**Comment by gkhanna79** [comment]
@blackdwarf Isnt this dup of https://github.com/dotnet/cli/issues/441?

**Comment by blackdwarf** [comment]
@gkhanna79 seems like it. Or rather, the other way around since this one was first. Closing it out then.

**Comment by gkhanna79** [comment]
Resolved with https://github.com/dotnet/cli/pull/413
