### ISSUE TITLE
Building a standalone app by picking and choosing packages is easy to get wrong

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2460]
## Steps to reproduce

dotnet new
vi project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24008",
    "Microsoft.NETCore.Runtime": "1.0.0-rc2-002349"
  },
  "runtimes" : {
    "osx.10.11-x64": {}
  },
  "frameworks": {
    "netcoreapp1.0": { }
  }
}
dotnet restore
dotnet build
dotnet run
## Expected  behavior

It would be nice if restore, build, or run highlighted that the project had a entrypoint or was a netcoreapp and did not have the coreclr package referenced and provide an error or warning.

A working project.json would look like the following:
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24008",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.0-rc2-002349"
  },
  "runtimes" : {
    "osx.10.11-x64": {}
  },
  "frameworks": {
    "netcoreapp1.0": { }
  }
}

Knowing to pick DotnetHostPolicy as opposed to Runtime is not very obvious.  The best place to verify how to build this up is the Microsoft.NETCore.App.deps.json in the shared framework folder - but that is not documented.
## Actual behavior

Could not resolve coreclr path
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002359)

Product Information:
 Version:     1.0.0-rc2-002359
 Commit Sha:  b0588fc4be

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by blackdwarf** [comment]
@jeffschwMSFT we are working on docs and tests as well as better error messages for RTM timeframe for this issue. 

/cc @eerhardt

**Comment by piotrpMSFT** [comment]
@blackdwarf are these docs done yet?

**Comment by blackdwarf** [comment]
Yes, they are and they are on https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/ for Preview 2 and https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/deploying/ for MSBuild-based tooling (Preview 3 and above). With this, will close this issue.
