### ISSUE TITLE
Project restores successfully ONLY IF a previous project successfully restored Microsoft.NETCore.App with a matching RID

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2461]
This issue is a bit nuanced, but important given the implications.  The thing I noticed is that an incomplete (missing a rid) project.json can successfully restore, build on a machine that had another project successfully restore the matching dependency.  Why is it that state from another project can mask an error in this project.json?  This imply's that 'order-matters' to nuget restores which likely has much broader impact than this simple case.
## Step 1

rm -f -r ~/.nuget/ (start from a clean cache)
cd first/
dotnet new
vi project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002349"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
dotnet restore

Result: 
Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002349)' for '.NETCoreApp,Version=v1.0'.

(At this point, it would be nice if this error message said - add a RID to successfully restore)
## Step 2

cd ../second
dotnet new
vi project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002349"
    }
  },
  "runtimes" : {
     "osx.10.11-x64": {},
     "win10-x64": {}
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
dotnet restore

Result: success
## Step 3

cd ../first
dotnet restore
## Expected  behavior

Restore fails with a message saying you need to specify a rid
## Actual behavior

Restore succeeds (because of the state of the nuget cache)
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002359)

Product Information:
 Version:     1.0.0-rc2-002359
 Commit Sha:  b0588fc4be

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by blackdwarf** [comment]
@jeffschwMSFT I was able to repro the above not with `dotnet restore` but with `dotnet run` with the latest. Also, this is the error message I get:

```console
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.11-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.11-x64' in the 'runtimes' section.
```

Seems pretty decent to me. Also, failure on `run` would imply that it will **always** fail on running regardless of whether NuGet cache contains the item or not, that is, whether the cache allows restore to write a lock file and succeed the restore operation. 

/cc @anurse

**Comment by piotrpMSFT** [comment]
@jeffschwMSFT for the nuget restore issue, can you open on https://github.com/nuget/home? I'm not sure we have the right folks looking at this here...

**Comment by ardalis** [comment]
I'm getting this today on a project I'm trying to update to RC2. Same behavior on Windows and on Mac (only difference is the runtime listed in option 2):
dotnet build

> Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.11-x64'. Possible causes:
> 1. The project has not been restored or restore failed - run `dotnet restore`
> 2. The project does not list one of 'osx.10.11-x64' in the 'runtimes' section.

Any idea how to get past this? I'm using this nuget feed: https://www.myget.org/F/aspnetrc2/api/v3/index.json
if that matters.

**Comment by eerhardt** [comment]
> Any idea how to get past this? I'm using this nuget feed: https://www.myget.org/F/aspnetrc2/api/v3/index.json
if that matters.

The RC2 packages are now on nuget.org, so you shouldn't need to be using any `myget.org` feed.

**Comment by ardalis** [comment]
@eerhardt thanks. Switched feeds/sources, but doesn't help with the underlying issue.

**Comment by eerhardt** [comment]
1. Can you list your project.json file?
2. Can you list the exact set of commands you executed?

**Comment by ardalis** [comment]
Sure, I'm trying to update this sample to RC2 (from RC1): 
https://github.com/aspnet/Docs/tree/ardalis/config-rc2/aspnet/fundamentals/configuration/sample

My commands to reproduce the issue are:
dotnet restore
dotnet build

Restore succeeds. Build shows this:
Steves-MBP:CustomConfigurationProvider stevesmith$ dotnet build
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'osx.10.11-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'osx.10.11-x64' in the 'runtimes' section.

This is for the CustomConfigurationProvider project - the other two projects I have upgraded to RC2 successfully. I'm guessing my project.json isn't correct, but I'm not sure what needs to change. Here it is for reference (see above URL for any other files you might want to see):

{
  "version": "1.0.0-*",
  "description": "CustomConfigurationSource Console Application",
  "authors": [ "daroth" ],

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027",

    "Microsoft.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}

**Comment by eerhardt** [comment]
Looking at your project.json, you are picking a "Self-contained App" (see the ".NET Core App Types" section of https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2).

Since you are not referencing "Microsoft.NETCore.App" and using a "type: platform" dependency, you are a self-contained app.  In order for self-contained apps to work, they need a "runtimes" section listing all the RIDs of the runtimes they will support.

so to fix this, add the following as a top-level property to your project.json:

```JSON
  "runtimes": {
    "win7-x64": {},
    "win7-x86": {},
    "osx.10.11-x64": {},
    "ubuntu.14.04-x64": {},
    "centos.7-x64": {},
    "rhel.7.2-x64": {},
    "debian.8-x64": {}
  },
```

Note, you can remove any of the RIDs you don't plan on running on.  You will need 'osx.10.11-x64' though.

After editing, `dotnet restore` again, and build.

**Comment by ardalis** [comment]
I previously tried adding some different runtimes, but didn't get that working, either. I'm guessing I'm using the wrong kind of project for what would just be a class library in the old world.

**Comment by eerhardt** [comment]
> I'm guessing I'm using the wrong kind of project for what would just be a class library in the old world.

Oh, I didn't know you were trying to build a "class library". Your project.json had:

```JSON
"description": "CustomConfigurationSource Console Application",
"authors": [ "daroth" ],

"buildOptions": {
"emitEntryPoint": true,
```

The "description" said "Console Application" and "emitEntryPoint: true" usually means "console app".

In that case, you don't need a "runtimes" section.  Instead, you should change your "framework" section from `netcoreapp1.0` to `netstandard1.x` where `x` is the lowest level you need. 0-5.  You will probably want netstandard1.5.

**Comment by ardalis** [comment]
Thanks, @eerhardt, this got me sorted out.

**Comment by piotrpMSFT** [comment]
restore does not require passing a RID in this scenario anymore.
