### ISSUE TITLE
.NET Core SDK Installer still shows 1.0.0.002374-beta in Programs and Features

### ISSUE THREAD

**Issue by weidazhao** [dotnet/cli#2463]
## Steps to reproduce
Install the latest .NET Core SDK Installer x64, go to "Programs and Features" and search CLI. The SDK still shows "beta" instead of "rc2" in the name.

**Comment by krwq** [comment]
cc: @Sridhar-MS

**Comment by piotrpMSFT** [comment]
fixed by #2530
