### ISSUE TITLE
[dotnet publish] Cross rid sharedfx publish failing with "Could not load host policy library"

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2465]
Using a build with #2141 fixed enables x-rid standalone publish!!!  Though sharedfx is failing with "could not load host policy library".

## Steps to reproduce
(On Mac)
dotnet new
dotnet restore
dotnet publish
(Copy bin/Debug/netcoreapp1.0/publish/* to Windows)
(install matching .NET Core)
dotnet app.dll

Note: I also tried declaring {"runtimes": "win10-x64": {}} and publishing explicitly for this rid, but that resulted in the same outcome.

## Expected  behavior
Runs

## Actual behavior
Could not load host policy library from [app.dll]

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002374)

Product Information:
 Version:     1.0.0-rc2-002374
 Commit Sha:  f82da07fc4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by jeffschwMSFT** [comment]
The root cause is #2279

**Comment by piotrpMSFT** [comment]
@jeffschwMSFT can we close as duplicate?

**Comment by jeffschwMSFT** [comment]
No longer an issue
