### ISSUE TITLE
Suggestion for project.json: allow paths to txt/md files for long form text fields such as description & release notes

### ISSUE THREAD

**Issue by michaelherndon** [dotnet/cli#2466]
## Expected  behavior
use a relative path to a releasenotes.md  or txt file for meta fields like releaseNotes or description

{
    description: "readme.md",
    releaseNotes: "releaseNotes.md"
}

## Actual behavior
{
    description: "really long text in json is a pain to deal with at times."
    releaseNotes: "dito"
}

**Comment by MaximRouiller** [comment]
Maybe change the name of the properties however. Otherwise, hard to differentiate between text and a filename without doing a check on disk. `releaseNotesFile` / `descriptionFile` or something along those line would work nicely.

**Comment by piotrpMSFT** [comment]
@davidfowl can comment on this. Moving to backlog for the time being. I'm not sure that release notes are appropriate in the project.json. This really feels like a transient pack-time artifact.

**Comment by blackdwarf** [comment]
The team is hard at work on a move to [MSBuild and csproj](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/). I believe that work makes this issue not-applicable. Closing.
