### ISSUE TITLE
[MSI]: Remove the check for any previous installation.

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2467]
In the MSI we check for any previous installation and we prevent any installation of 'Release' version on top of 'Nightly' version and vice versa. This is no longer needed since CLI SxS now. This is reminiscent of pre-sharedFx CLI.

https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/clisdk/checkbuildtype.wxs

**Comment by Sridhar-MS** [comment]
Folks installing RC2 on top of 1.0.0.001598 (version in the getting started page) or older version may hit this issue. See issue https://github.com/dotnet/cli/issues/1919#issuecomment-209433994.

This is a less risky change for RC2 since it is just removal of a feature.

**Comment by Sridhar-MS** [comment]
cc: @piotrpMSFT @Petermarcu for RC2 approval.

**Comment by piotrpMSFT** [comment]
Fixed by #2530
