### ISSUE TITLE
Add environment variable to show stack trace for CLI errors.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#2469]
## Steps to reproduce
- Create a tool
- Have the tool throw an error when run
- dotnet my-tool
## Expected  behavior
- An error with enough information to diagnose what's going on. Aka stacktrace
## Actual behavior
- You just get the error message.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002349)

Product Information:
 Version:     1.0.0-rc2-002349
 Commit Sha:  ed9309b90b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by NickCraver** [comment]
Please make this a thing very soon. We're hitting exceptions and wasting a lot of time back and forth debugging for lack of this simple feature. `Object reference not set to an instance of an object` in a console is not helpful. Please let us easily enable traces without a custom CLI build.

**Comment by jskeet** [comment]
Absolutely. I don't expect a pre-release tool to work in all situations, but I *do* expect it to give me more error information than we're currently getting.

**Comment by krwq** [comment]
Items to do here:
- [ ] tests for `dotnet run`
- [ ] tests for `dotnet <toolname>`
- [ ] should there be opt in or opt-out switch?

@blackdwarf @piotrpMSFT - my intuition tells me that we should always display stack trace for tools and run - is that correct or do we actually want some opt-in/opt-out mechanizm (IMO i can't see situation when stack trace is not useful in those cases - the only not desirable place for stack is when stack is coming from our toolchain but that's not the case here)

**Comment by piotrpMSFT** [comment]
@krwq #5076 is likely very related :D

**Comment by piotrpMSFT** [comment]
@krwq are these just dupes? Can we close this one in favor of https://github.com/dotnet/cli/issues/5076?

**Comment by krwq** [comment]
Yes, it is a dupe
