### ISSUE TITLE
CLI Binaries are Not Pre-Compiled

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2474]
CLI binaries JIT for over 1 second when doing a dotnet build.  There is also significant JIT time in dotnet new and dotnet run.

This can be resolved by pre-compiling the CLI binaries using crossgen.

**Comment by piotrpMSFT** [comment]
We're going to give this a shot, but may need to revert the change if we see stability issues.

**Comment by brianrob** [comment]
Awesome.  Thanks!

**Comment by piotrpMSFT** [comment]
Fixed by #2517
