### ISSUE TITLE
Elapsed Time Emitted by dotnet build is lower than the actual process execution time

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2475]
You can measure this using your measurement method of choice (PowerShell "Measure-Command", ETW, Linux "time", etc.)  The dotnet build process runs for at least 1 second longer than the emitted time.

While this is currently due in part to JIT time, we should consider how accurate this time should be (or remove it).

**Comment by piotrpMSFT** [comment]
* Ticks since process start
* calculate "end" after telemetry is done

**Comment by piotrpMSFT** [comment]
Dotnet-build was swapped out for msbuild, so this code no longer exists.
