### ISSUE TITLE
dotnet pack fails for the first time but succeeds in the next call

### ISSUE THREAD

**Issue by hovsepm** [dotnet/cli#2479]
## Steps to reproduce
1. Clone https://github.com/hovsepm/AutoRest.git
2. switch to netcore branch
3. go to ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime folder
4. dotnet restore
5. dotnet pack
6. dotnet pack (again)

## Expected  behavior
step 5 should not fail

## Actual behavior
step 5 fails however step 6 succeeds. 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-beta-002288)

Product Information:
 Version:     1.0.0-beta-002288
 Commit Sha:  9efebf8ef9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86

**Comment by piotrpMSFT** [comment]
@cdmihai can you take a look? To add more detail, during the first `build` we see a message telling us that compilation failed. On the next run `build` claims that that target has already been built and happily continues along its way. It looks like we are not correctly detecting a previous build failure.

**Comment by cdmihai** [comment]
Can't repro with the head of of the rel branch. Dotnet pack succeeds on the first try, no errors.

**Comment by cdmihai** [comment]
```
C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime> dotnet restore
log  : Restoring packages for C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime\project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime\project.lock.json
log  : C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime\project.json
log  : Restore completed in 1196ms.

NuGet Config files used:
    C:\projects\tests\AutoRest\ClientRuntimes\CSharp\NuGet.Config
    C:\Users\micodoba\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://dotnet.myget.org/F/cli-deps/api/v3/index.json
    https://api.nuget.org/v3/index.json
PS C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime> dotnet pack
Compiling Microsoft.Rest.ClientRuntime for .NETFramework,Version=v4.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:04.1000286


Compiling Microsoft.Rest.ClientRuntime for .NETStandard,Version=v1.1

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.7822558


Compiling Microsoft.Rest.ClientRuntime for .NETStandard,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.9650691


Producing nuget package "Microsoft.Rest.ClientRuntime.3.0.0" for Microsoft.Rest.ClientRuntime
Microsoft.Rest.ClientRuntime -> C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime\bin\Debug\Microsoft.Rest.ClientRuntime.3.0.0.nupkg
Producing nuget package "Microsoft.Rest.ClientRuntime.3.0.0.symbols" for Microsoft.Rest.ClientRuntime
Microsoft.Rest.ClientRuntime -> C:\projects\tests\AutoRest\ClientRuntimes\CSharp\Microsoft.Rest.ClientRuntime\bin\Debug\Microsoft.Rest.ClientRuntime.3.0.0.symbols.nupkg
```

**Comment by hovsepm** [comment]
@cdmihai do I need to update anything on my machine? e.g. core clr tools? It repros on my machine and I don't know how to narrow down the real issue and find out what may cause this.

**Comment by piotrpMSFT** [comment]
@cdmihai any updates on this issue?

**Comment by cdmihai** [comment]
@hovsepm I can't repro this issue (see my previous cmd line printout). Please install new dotnet CLI tools and see if you still run into the issue.

**Comment by piotrpMSFT** [comment]
@hovsepm have you had a chance to try this with latest? We really need a repro to be able to investigate this.

**Comment by hovsepm** [comment]
@piotrpMSFT , @piotrpMSFT I'm setting up a new dev box to try this on a different PC than mine. Will update this thread.

**Comment by hovsepm** [comment]
@piotrpMSFT , @cdmihai, after upgrading to 
```
.NET Command Line Tools (1.0.0-rc2-002429)

Product Information:
 Version:     1.0.0-rc2-002429
 Commit Sha:  612088cfa8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
it builds from the first attempt.
