### ISSUE TITLE
*.runtimeconfig.json file is not persisted by `dotnet build`

### ISSUE THREAD

**Issue by swgillespie** [dotnet/cli#2485]
## Steps to reproduce
1. Create a project with the following object in their `project.json` file:

```
    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    },
```

2. `dotnet build`. Verify that the generated `Project.runtimeconfig.json` file in the build output directory contains the supplied runtime object with the same keys given in the `project.json` file.
3. Split the runtime objects from the `project.json` file in accordance with [these docs](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md#appnameruntimeconfigjson):

Project.runtimeconfig.json:

```
{
    "runtimeOptions": {
        "configProperties": {
            "System.GC.Server": true
        }
    }
}
```

3. `dotnet build`. The `Project.runtimeconfig.json` file in the output directory is now missing the keys
that we added:

```
{
  "runtimeOptions": {}
}
```
## Expected  behavior
The configuration specified in `Project.runtimeconfig.json` should be persisted to the `Project.runtimeconfig.json` configuration generated by the build.

## Actual behavior
`runtimeOptions` is an empty object in the configuration generated by the build.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002376)

Product Information:
 Version:     1.0.0-rc2-002376
 Commit Sha:  9d71cce383

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by adityamandaleeka** [comment]
Just checked on OS X and this seems to be working (my CLI version is 1.0.0-rc2-002392). I'll check on Windows too.

**Comment by adityamandaleeka** [comment]
Just checked on Windows (same CLI version) and it seems to be working there as well. The runtimeconfig.json I'm checking is the one in bin/Debug/netcoreapp1.0.

**Comment by Petermarcu** [comment]
@sokket

**Comment by sokket** [comment]
Taking a look

**Comment by sokket** [comment]
Taking a look

**Comment by piotrpMSFT** [comment]
@sokket has a fix and is finishing up tests. This should be in tomorrow.

**Comment by piotrpMSFT** [comment]
This is blocked by #2613

**Comment by Petermarcu** [comment]
@socket , can we get this in today?

**Comment by sokket** [comment]
@Petermarcu this is blocked right now by the build break and Jenkins failures. @brthor is taking a look at the PR to make sure it is still ready to merge once the world is green

**Comment by brthor** [comment]
Taking ownership here, to fix test failures associated with the PR

**Comment by brthor** [comment]
cc @livarcocc 

Taking a second look at these docs, 
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md#what-produces-the-files-and-where-are-they

The runtimeconfig.json is specified as being a file output by build, and not something which exists in your source directory. 

It's explicitly stated that the content of this file is copied from project.json:
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/specs/runtime-configuration-file.md#sections

Where is the context coming from that the cli should fallback to finding this file in your source directory if runtimeOptions are not present in project.json?

**Comment by piotrpMSFT** [comment]
@blackdwarf we may want to call this out in the docs. {app}.runtimeconfig.json is not a source artifact. It is a projection of project.json. Like the lock file and the deps file, these are artifacts that can be useful for debugging some classes of problems but are not intended to be produced manually.
