### ISSUE TITLE
dotnet build fails if the directory contains unicode characters

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#2486]
## Steps to reproduce
    cd /d %USERPROFILE%
    mkdir Tést
    cd Tést
    dotnet new
    dotnet restore
    dotnet build

## Expected  behavior
Build succeeds

## Actual behavior

    Response file 'C:\Users\greggm\T├â┬⌐st\obj\Debug\netcoreapp1.0\dotnet-compile.rsp' doesn't exist.
    C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Users\greggm\T├⌐st\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
    
    Compilation failed.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002330)

Product Information:
 Version:     1.0.0-rc2-002330
 Commit Sha:  3af38bf0fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by gregg-miskelly** [comment]
NOTE: I see the same behavior if the Unicode/High ascii character is anywhere on the path to the app. So I believe this will block acquiring the VS Code debugger extension on any user who has accents in their user name. Though it is possible that that is really a different CLI bug. See https://github.com/OmniSharp/omnisharp-vscode/issues/186 for the original bug.

**Comment by xal1983** [comment]
Sorry, I had already filed one here too: #2458

**Comment by brthor** [comment]
A PR with tests exhibiting the failure is windows only is here: 
https://github.com/dotnet/cli/pull/2610

Corefx issue filed here:
https://github.com/dotnet/corefx/issues/7935

**Comment by eerhardt** [comment]
@Petermarcu approved in email
