### ISSUE TITLE
After installing dotnet-sdk-ubuntu-x64.latest.deb, a wild libhostpolicy.so mismatch appears

### ISSUE THREAD

**Issue by damageboy** [dotnet/cli#2487]
## Steps to reproduce
wget https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sdk-ubuntu-x64.latest.deb
dpkg -i dotnet-sdk-ubuntu-x64.latest.deb
apt-get -f install

## Expected  behavior
`dotnet --version` should work

## Actual behavior
`dotnet --version` gives out:
```
dans@scumbag:~$ dotnet --version
The version of the data layout used to initialize libhostpolicy.so is [0x0000]; expected version [0x16041101]
```

## Environment data
`dotnet --info` output:
```
The version of the data layout used to initialize libhostpolicy.so is [0x0000]; expected version [0x16041101]
```

`dpkg -l | grep dotnet`:
```
dans@scumbag:~$ dpkg -l | grep dotnet
ii  dotnet-dev-1.0.0-rc2-002374                                    1.0.0-rc2-002374-1                                 amd64        .NET Core CLI
ii  dotnet-host                                                    1.0.1-dev-002315-1                                 amd64        .NET Core Host
ii  dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-3002374 1.0.0-rc2-3002374-1                                amd64        .NET Core Microsoft.NETCore.App 1.0.0-rc2-3002374
```

`sudo updatedb && locate hostpolicy.so | xargs sha1sum`:
```
dans@scumbag:~$ locate hostpolicy.so | xargs sha1sum
26eb8f447b5228d1f4320ecf671b6248c563c28f  /usr/share/dotnet/sdk/1.0.0-rc2-002374/libhostpolicy.so
26eb8f447b5228d1f4320ecf671b6248c563c28f  /usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.0-rc2-3002374/libhostpolicy.so
```

**Comment by Petermarcu** [comment]
@schellap , Can you take a look?

**Comment by schellap** [comment]
@krwq is the installer overwriting libhostfxr.so?

**Comment by schellap** [comment]
It should overwrite the libhostfxr.so.

**Comment by brthor** [comment]
This is because a package from master was pushed to our feed with a higher version. I have put off cleaning up the feed in favor of other high priority work but can prioritize this.

**Comment by schellap** [comment]
Oooo sounds creepy :)

**Comment by brthor** [comment]
Specifically this version of dotnet-host is the issue: `1.0.1-dev-002315-1`

As an immediate workaround:
`apt-get install dotnet-host=1.0.0-rc2-002392-1`

**Comment by brthor** [comment]
Packages don't seem to be getting deleted from the feed. Contacted our repo partner for help on this.

**Comment by damageboy** [comment]
@brthor You suggestion seems to have fixed this, should I close the issue?

**Comment by brthor** [comment]
Let's keep this open, and I'll close it once these packages are cleared from the feed.

**Comment by piotrpMSFT** [comment]
@brthor any update?

**Comment by brthor** [comment]
There is a bug in the deletion of these using the API.

They are currently still available on the feed and I've followed up on how to get them removed.

**Comment by brthor** [comment]
this is fixed.

Btw like the pokemon reference in the title 😄
