### ISSUE TITLE
Find the correct default install location for dotnet windows MSI

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#249]
Right now the dotnet MSI installs by default into `%programfiles%\Microsoft\dotnet`. 

- Is `%programfiles%` the right place to install dotnet? This is where users typically expect files to be after installation. But the user needs admin privileges.
- Is `%LOCALAPPDATA%\Programs` the right place to install? This becomes a per-user installation,  though it can follow the user around the network. The user does not need admin privileges to install.

I like to get some feedback on this.
cc: @Petermarcu @piotrpMSFT @blackdwarf @anurse

**Comment by piotrpMSFT** [comment]
I'd prefer %ProgramFiles%\dotnet\cli as our root. Let's not become yet another product [dotnet] that dumps on %ProgramFiles% as it grows.

Our Native installer packages are all in-place updates right now, so omitting a version number seems fine.

**Comment by anurse** [comment]
So do we want the `cli` suffix in there? Other threads have discussed removing it... I think we don't really need it. The layout would look something like:

```
%ProgramFiles%\
    dotnet\
        bin\
            dotnet.exe
            ...
        runtime\
            coreclr.dll
            ...
```

**Comment by Sridhar-MS** [comment]
`dotnet` node in `%ProgramFiles%\dotnet\cli` may confuse people with Desktop .Net.

**Comment by anurse** [comment]
So serious question: Why couldn't `dotnet` be used to interact with Desktop .NET? `dotnet compile` can already compile things. `dotnet run` is pretty easy to implement as well (just don't copy the stub)

**Comment by blackdwarf** [comment]
@anurse don't know, that is a good question. I guess because we don't want to add more code for something that alrady has significant tooling support, esp. on Windows? Though it is something that could be considered for the future (once we have other things baking). 

+1 to not having version numbers and removing \cli. It makes not sense, this is the actual product you are installing, so it seems reduntant. Putting stuff in %ProgramFIles% in this case actually makes sense a lot, so I would also +1 that.

**Comment by anurse** [comment]
I'm pretty sure `dotnet run` actually supports Desktop .NET already, and I think that given that we are trying to build a whole new .NET CLI, we should look to try and support the legacy world where we can. Obviously I wouldn't advocate bending over backwards to replace the entire existing ecosystem, but maintaining the ability to build `netNN` projects would be valuable for ensuring the toolchain can be used as people move forward, regardless of how far they are in porting to .NET Core.

**Comment by Sridhar-MS** [comment]
I think we need the `\cli` sub-folder. I am thinking people can use the `dotnet` node to pivot other dotnet tools - maybe a debugger.

**Comment by Sridhar-MS** [comment]
I am ok with having no version numbers which means no SxS for the MSI installer.

**Comment by Petermarcu** [comment]
So in place updates forever?

**Comment by Sridhar-MS** [comment]
Yes. And SxS is enabled by downloading zip packages.

**Comment by Petermarcu** [comment]
Just took a quick look.

Node.js has no version and goes under program files.
Python has a version and installs per user.
Go has no version and installs in C:\go.
Elm goes under program files and has a version.

Do we know the pro's and con's? My worry is that people will depend on the default location and if we ship changes in the future that break people, we'll be in a weird place.

**Comment by Sridhar-MS** [comment]
I feel like versioned installation support should be its own issue. Its not specific to windows. 

Lets decide the root path in this issue. We can add version to the root path based on whether we want to support multiple version installations or not. 

Created #271

**Comment by Petermarcu** [comment]
Ok, we can discuss versions on the other issue. My vote would be to have symmetry across platforms. If we have a cli folder on one, we should have it on all and vice versa. Looking around at other things, many of them seem to have something like `dotnet/bin` where they put a bunch of the tools that need to go on the path for that ecosystem.

**Comment by piotrpMSFT** [comment]
Please make sure we keep consistency across:
- Mac
- Linux
- Windows
- Registry
- CoreHost defaults

**Comment by weshaggard** [comment]
I like `%ProgramFiles%\dotnet\bin`
I know we plan to discuss versioning in another issue but I do believe we should consider including the version because I think side-by-side will be more sustainable.

**Comment by piotrpMSFT** [comment]
@Sridhar-MS I believe this is now resolved. Can we close?

**Comment by Sridhar-MS** [comment]
Tracking OSX #390
