### ISSUE TITLE
CLI should not depend on DNX 

### ISSUE THREAD

**Issue by lt72** [dotnet/cli#2490]
It appears that CLI depends on DNX for command line parsing. 
It seems that being CLI the default build tool going forward, it should not depend on anything other than corefx, so that we can ensure a better servicing story and no circular dependencies.

**Comment by piotrpMSFT** [comment]
The CLI depends on libraries that were originally developed for DNX, not DNX itself. If we want to reduce external dependencies then this issue should grow to include everything in the Microsoft.Extensions namespace as well.

/cc @eerhardt who is investigating how we can reduce CLIs dependencies.

**Comment by Eilon** [comment]
JoC was going to set up a mtg at some point with the dev managers to figure out code flow between repos, so this will come up when that happens.

**Comment by piotrpMSFT** [comment]
CLI no longer depends on DNX
