### ISSUE TITLE
Add assembly load path tests for Standalone and Shared scenarios

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2492]
CLI tests currently do not validate that Shared Framework applications are actually loading their dependencies from the Shared Framework location, and the same for Standalone. We should add a test which parses CoreHost output and ensures that the paths match expectations.

/cc @gkhanna79 @schellap

**Comment by gkhanna79** [comment]
@schellap We should add a test for this as part of your adding tests work.

**Comment by piotrpMSFT** [comment]
If this is still needed, please reopen in core-setup @schellap.
