### ISSUE TITLE
CLI should share build graph information across command invocations

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2495]
## Steps to reproduce

`dotnet new`
`dotnet restore`
`dotnet build`
## Expected  behavior

A given Project Context is generated once and shared across requests, potentially spanning multiple process invocations
## Actual behavior

Even in this simple scenario project contexts are created rampantly, leading to multiple parsings of project.json and project.lock.json

**Comment by piotrpMSFT** [comment]
@troydai @anurse @pakrym can we somehow leverage ProjectModelServer to reduce parsing of the graph?

**Comment by pakrym** [comment]
I don't think we should share it across invocations, but if we move builtin commands to be inproc we can share it with them.

**Comment by pakrym** [comment]
And we should consider creating project contexts and doing other things slow things like `LibraryExporter.GetAllExports()` in less places, ideally ones per project.

**Comment by livarcocc** [comment]
We don't have ProjectModel anymore.
