### ISSUE TITLE
Consider using a separate long-lived process for Project Model cache and telemetry 

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2497]
An anecdotal performance measurement by @pakrym found that ~14% of CLI runtime is spent within telemetry reporting. We need to prevent the benefit of telemetry from having such a high impact on CLI runtime performance. This will likely require a significant design change.
## Initial Proposal

Similarly to #2495, there is likely a need for a coordinator process which manages these expensive IO-bound operations. We can consider having the 'root' invocation of CLI create both the telemetry client and the Project Model cache and make it available for consumption by subordinate processes. This would minimize the cost of setting up https channels, clients, etc. If we find this is still too expensive we'll want to move this facility into a separate process which is able to exit after reporting is complete, independently of CLI shutdown.

**Comment by livarcocc** [comment]
We don't have ProjectModel anymore.
