### ISSUE TITLE
discover test fails to discover tests in visual studio 2015

### ISSUE THREAD

**Issue by ibrmohammed** [dotnet/cli#2498]
I am getting this issue when i build my test project.

------ Discover test started ------
------ Test started: Project: bb.bcd.Tests ------
Starting Microsoft.Dnx.TestHost [C:\Users\abcd.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20222\bin\dnx.exe --appbase "C:\Users\abcd\Source\Workspaces\xxx\bcd\test\Aaa.bcd.Tests" Microsoft.Dnx.ApplicationHost --port 49709 Microsoft.Dnx.TestHost --port 49730 --parentProcessId 732]

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
at Microsoft.Dnx.TestHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.b__0()
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value HKLM\Software\Microsoft\Fusion!EnableLog to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Unable to start Microsoft.Dnx.TestHost
========== Discover test finished: 0 found (0:00:10.6286079) ==========

following is my project.json file

  "dependencies": {
    "xunit": "2.1.0",
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },
  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.ComponentModel": "",
        "System.Threading.Tasks": ""
      }
    }
  }

**Comment by Petermarcu** [comment]
This is all DNX based. If this repro's with a CLI based solution once we have VS tools available, please let us know.

**Comment by ibrmohammed** [comment]
we are using xunit.runner.dnx which is dnx based.
  "commands": {
    "test": "xunit.runner.dnx"
  }
Is there a runner for Xunit which is CLI based.
