### ISSUE TITLE
TestCommand (in dotnet-test) command always invokes test method on the first TFM listed in the project.json

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2506]
Ran into this when I was working on #2346.  `dotnet test` does not honor the `-f` parameter. Might have similar issues with other parameters.

**Comment by piotrpMSFT** [comment]
@pranavkm when do you expect this to land? Today?

**Comment by pranavkm** [comment]
https://github.com/dotnet/coreclr.xunit/pull/6 needs to go in first which requires a fix in the CLI first. This will take a bit to go in

**Comment by piotrpMSFT** [comment]
dotnet/coreclr.xunit#6 is fixed. What's the ETA for this one?

**Comment by pranavkm** [comment]
Waiting for sign off.

**Comment by piotrpMSFT** [comment]
Just chatted with @pranavkm. There are test failures on Windows x86 that are being inspected. This is expected to be fixed today/tomorrow.

**Comment by piotrpMSFT** [comment]
@pranavkm can you share an update here?

**Comment by pranavkm** [comment]
Waiting on ask mode approval for https://github.com/dotnet/coreclr.xunit/pull/28
