### ISSUE TITLE
[dotnet build] Build fails for Nuget.Core solution, test projects fail to find src binaries

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2509]
## Steps to reproduce
1. Get Nuget.Core enlistment https://github.com/NuGet/NuGet.Client 
2. Open NuGet.Core.sln and wait for restore to complete
3. Right click on NuGet.Client.Test project and select "Rebuild"
## Expected  behavior

Everything to build fine
## Actual behavior

All src projects build fine, but NuGet.Core.Tests fails to find dependent projects binaries:

C:\Program Files\dotnet\dotnet.exe build "D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test" --configuration Debug --no-dependencies --build-base-path "D:\git\ms\nuget\NuGet.Client\artifacts" --no-incremental
12>  Compiling NuGet.Client.Test for .NETCoreApp,Version=v1.0
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : C:\Program Files\dotnet\dotnet.exe compile-csc @D:\git\ms\nuget\NuGet.Client\artifacts\NuGet.Client.Test\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Client\bin\Debug\netstandard1.5\NuGet.Client.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Common\bin\Debug\netstandard1.5\NuGet.Common.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.ContentModel\bin\Debug\netstandard1.5\NuGet.ContentModel.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Frameworks\bin\Debug\netstandard1.5\NuGet.Frameworks.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Packaging\bin\Debug\netstandard1.5\NuGet.Packaging.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Packaging.Core\bin\Debug\netstandard1.5\NuGet.Packaging.Core.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Packaging.Core.Types\bin\Debug\netstandard1.5\NuGet.Packaging.Core.Types.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Repositories\bin\Debug\netstandard1.5\NuGet.Repositories.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.RuntimeModel\bin\Debug\netstandard1.5\NuGet.RuntimeModel.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Test.Utility\bin\Debug\netstandard1.5\NuGet.Test.Utility.dll' could not be found
12>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test\error CS0006: Metadata file 'D:\git\ms\nuget\NuGet.Client\src\NuGet.Core\NuGet.Versioning\bin\Debug\netstandard1.5\NuGet.Versioning.dll' could not be found
12>  Compilation failed.
12>      0 Warning(s)
12>      11 Error(s)
12>  Time elapsed 00:00:01.7895584
## Environment data

`dotnet --info` output:

D:\git\ms\nuget\NuGet.Client>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002392)

Product Information:
 Version:     1.0.0-rc2-002392
 Commit Sha:  880dcf2fc8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

D:\git\ms\nuget\NuGet.Client>

**Comment by abpiskunov** [comment]
Also see the format of those errors - project path is specified in front - this also needs to be fixed.

**Comment by piotrpMSFT** [comment]
Does the same repro from the cmd line?

**Comment by Petermarcu** [comment]
@abpiskunov , can you get us a more targeted repro on the command line?

**Comment by abpiskunov** [comment]
Same steps repro from command line.

Thanks,
Anton

On Apr 14, 2016, at 7:11 PM, Peter Marcu <notifications@github.com<mailto:notifications@github.com>> wrote:


@abpiskunov<https://github.com/abpiskunov> , can you get us a more targeted repro on the command line?

-

**Comment by abpiskunov** [comment]
Tooling calls same dotnet cli, so for command line it will be the same steps:

1. Get Nuget.Core enlistment https://github.com/NuGet/NuGet.Client 
2. dotnet restore from solution root
3. C:\Program Files\dotnet\dotnet.exe build "D:\git\ms\nuget\NuGet.Client\test\NuGet.Core.Tests\NuGet.Client.Test" --configuration Debug --no-dependencies --build-base-path "D:\git\ms\nuget\NuGet.Client\artifacts" --no-incremental

**Comment by DovydasNavickas** [comment]
Hmm... guys? Still having these errors on a large project. Also, rc1 version with DNX works perfectly fine.

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
