### ISSUE TITLE
[MSI] Associate the PATH Environment variable with dotnet[executable]

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#251]
So that if that versioned file is uninstalled the environment variables are also removed.

https://github.com/dotnet/cli/blob/master/packaging/windows/envvars.wxs

Here are the comments from @Petermarcu in #211
>This doesn't seem quite right. I don't recall all the rules but I think you are better off handling things that are "unversioned" by putting them in a component that has a versioned file. Perhaps we need to drop a dummy versioned file that triggers when these things are written and removed. I'm not sure I trust MSI's environment variable support either.

>I think because its tied to TARGETDIR, the "" guids don't work and we'll have to remember to change these giuds version to version. If Wix lets you have a versioned file and then the Environment nodes and use a "" guid, I think we'll be in better shape.

**Comment by piotrpMSFT** [comment]
@Sridhar-MS is this coming in today? Can we bump to RC2?

**Comment by Sridhar-MS** [comment]
This is already fixed. Environment variables are associated with the registry keys (https://github.com/dotnet/cli/blob/master/packaging/windows/registrykeys.wxs#L14). Build-to-build major upgrades do reset these environment variables correctly. Uninstall also removes them correctly.
