### ISSUE TITLE
how to use xunit and dotnet test

### ISSUE THREAD

**Issue by rohitshrivastava04** [dotnet/cli#2513]
Trying to run tests from https://github.com/dotnet/cli/tree/master/TestAssets/TestProjects/ProjectWithTests
when I run dotnet restore it says

    Errors in c:\Users\*****\Documents\coretest\project.json
        Unable to resolve 'Microsoft.Extensions.CommandLineUtils (>= 1.0.0-rc3-20565
    )' for '.NETStandardApp,Version=v1.5'.

Following is my nuget.config
```
<configuration>
  <packageSources>
    <add key="cli-deps" value="https://dotnet.myget.org/F/cli-deps/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

## Expected  behavior
expecting a successful restore

## Actual behavior
    Errors in c:\Users\*****\Documents\coretest\project.json
        Unable to resolve 'Microsoft.Extensions.CommandLineUtils (>= 1.0.0-rc3-20565
    )' for '.NETStandardApp,Version=v1.5'.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002392)

Product Information:
 Version:     1.0.0-rc2-002392
 Commit Sha:  880dcf2fc8

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by rohitshrivastava04** [comment]
if I change Nuget.config to just have aspnetvnext it successfully restores but then gives error while executing dotnet test
`c:\Users\rohit1647\Documents\coretest\error CS0041: Unexpected error writing deb
ug information -- 'Windows PDB writer is not available -- could not find Microso
ft.DiaSymReader.Native.amd64.dll'`

**Comment by piotrpMSFT** [comment]
@blackdwarf @bleroy can you guys look at this?

**Comment by blackdwarf** [comment]
@rohitshrivastava04 can you try to run this from the rel/1.0.0 branch? That is https://github.com/dotnet/cli/tree/rel/1.0.0/TestAssets/ProjectWithTests?

**Comment by livarcocc** [comment]
cc @eerhardt Shouldn't the dependency above be available in the cli-deps feed?

**Comment by eerhardt** [comment]
1. I don't see any place in the rel/1.0.0 branch that is using the "Microsoft.Extensions.CommandLineUtils" package.  I see places using "Microsoft.Extensions.CommandLineUtils.Sources", however.
2. I do see the package and version that error is talking about in the cli-deps feed:  https://dotnet.myget.org/feed/cli-deps/package/nuget/Microsoft.Extensions.CommandLineUtils/1.0.0-rc3-20565

**Comment by piotrpMSFT** [comment]
Moving to backlog. There are docs coming with the RC2 release for building xunit tests. The CLI repo's tests themselves are not great candidates since we do a lot of atypical stuff to test the underlying infrastructure.

**Comment by blackdwarf** [comment]
Closing this as there are many documents on how to work with `dotnet test` now on https://docs.microsoft.com/en-us/dotnet/articles/.
