### ISSUE TITLE
Static Caching for ProjectContext

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2520]

**Comment by davidfowl** [comment]
- Refactor dotnet build to use the a single build graph structure
- Support passing multiple projects to build (and globs)
- Add ProjectContext caching (use WorkspaceContext)
- Make ProjectContext lighter (based on measurements)
 - Pool strings during lock file parsing
 - LibraryExporter needs to cache exports 
- Pass project context to dotnet-compile

## Measure
- MVC 
- Single hello world console (dotnet new)

**Comment by piotrpMSFT** [comment]
@davidfowl when is this coming in?

**Comment by piotrpMSFT** [comment]
@davidfowl ping

**Comment by anurse** [comment]
I have a PR coming that addresses some of these. We're going to be iterating quickly on this, producing smaller changes that keep working so this may trigger multiple PRs.

**Comment by anurse** [comment]
The bulk of this is now done. We're going to keep investigating build perf and iterating as needed.
