### ISSUE TITLE
Dotnet Build accepts multiple projects in single invocation

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2521]

**Comment by piotrpMSFT** [comment]
@davidfowl when is this coming in?

**Comment by piotrpMSFT** [comment]
@davidfowl ping

**Comment by pakrym** [comment]
@piotrpMSFT I'm working on it, should have a PR tomorrow or day after.

**Comment by piotrpMSFT** [comment]
@pakrym:

> ![image](https://cloud.githubusercontent.com/assets/2379589/14802672/8538d36a-0b07-11e6-8358-390b29bfd064.png)

Is this ready to go?

**Comment by anurse** [comment]
This is done.
