### ISSUE TITLE
add basic performance monitoring

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/cli#2522]

**Comment by piotrpMSFT** [comment]
@brianrob what's the status of this issue?

**Comment by brianrob** [comment]
I've made a little bit of progress here, but this has been blocked by some high-pri performance measurements that I've needed to do.  I should have something by EOW.

**Comment by piotrpMSFT** [comment]
This will be fixed by https://github.com/dotnet/cli/pull/2681

**Comment by brianrob** [comment]
#2681 is merged.  Waiting on dev script to run performance tests for CLI.

**Comment by piotrpMSFT** [comment]
Since the basic tests are in, pushing this out to RTM

**Comment by livarcocc** [comment]
We have added these tests now in the SDK.
