### ISSUE TITLE
Issues dotnet build when targeting net35 with frameworkAssemblies

### ISSUE THREAD

**Issue by eByte23** [dotnet/cli#2525]
## Steps to reproduce
Create a library targeting net35 where you include frameworkAssemblies

## Expected  behavior
Builds correctly providing you setup everything correctly

## Actual behavior
Errors out with lots of 
'Predefined type 'System.Void' is not defined or imported'
etc...

I believe the issue to be that when dynamically creating the dotnet-compile-csc.rsp and dotnet-compile.rsp

When targeting net40 or net45 
with similar dependencies they include 
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\...System.Data.dll"

Net35 was not, on manually adding the required references i could successfully build the package.
these were my references
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\mscorlib.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.Core.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.Data.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.configuration.dll"
-r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.XML.dll"

**Comment by JamesNK** [comment]
I also get this.

**Comment by anurse** [comment]
I have a fix. I'm going to ask for RC2 approval for this since it's a regression.

**Comment by JamesNK** [comment]
Hi! Is this available now in the public build server .NET CLI version?

**Comment by eByte23** [comment]
@JamesNK Not sure about the 'public build server?' but I downloaded the .NET Core SDK Installer build 002457 and it works as expected

**Comment by JamesNK** [comment]
That's what I meant. Ok!

**Comment by anurse** [comment]
Yeah, should be there. Glad to hear it seems to have fixed the issue!
