### ISSUE TITLE
Tools deps file is not regenerated when imports change

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#2528]
## Steps to reproduce
- Delete your `%UserProfile/.nuget/packages/.tools` folder
- Add the following to your `project.json`:

``` JSON
"dotnet-razor-tooling": {
      "version": "1.0.0-*",
      "imports": [ "portable-net40+sl5+wp80+win8+wpa81" ]
    }
```
- Restore & build your project.
- Change the import statement above to be: `"imports": [ "portable-net45+wp80+win8+wpa81+dnxcore50" ]`
- Restore & build your project.
## Expected  behavior

The .deps file in the .tools dir for dotnet-razor-tooling will have its newtonsoft pointing to the `portable-net45+wp80+win8+wpa81+dnxcore50` binary.
## Actual behavior

The .deps file in the .tools dir for dotnet-razor-tooling has its newtonsoft pointing to the `portable-net40+sl5+wp80+win8+wpa81` binary.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002374)

Product Information:
 Version:     1.0.0-rc2-002374
 Commit Sha:  f82da07fc4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
## Workaround

Fix your import statement and nuke your `%UserProfile/.nuget/packages/.tools` folder

**Comment by brthor** [comment]
@NTaylorMullen right next to the deps file is a lock file, does this update when imports change?

**Comment by NTaylorMullen** [comment]
@brthor Yes it does.

**Comment by brthor** [comment]
Okay, we currently default to not regenerating the deps file when it already exists. A simple integrity check should be simple to add in ProjectToolsCommandResolver.

**Comment by livarcocc** [comment]
We no longer support imports for tools.
