### ISSUE TITLE
muxer should support --fx-version and remove shared framework's dotnet.exe

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2529]
## Steps to reproduce
N/A

## Expected  behavior
- Can specify a Shared Framework version against which to run an application.
`dotnet.exe --fx-version 1.0.0-rc2-123456 bin/Debug/netcoreapp1.0/myapp.dll`

- No dotnet.exe in the Shared Framework directory

## Actual behavior
N/A

**Comment by eerhardt** [comment]
@piotrpMSFT @gkhanna79 @schellap - do we want this for "Preview2"?

**Comment by eerhardt** [comment]
Similarly, we should remove the `corehost.exe` file from the Shared Framework directory.  Currently this is being used by `dotnet test` to execute the test runner. And looks like it can be used for other 'extension' commands as well.

**Comment by schellap** [comment]
`corehost` removal has another bug to be removed. #2408

**Comment by eerhardt** [comment]
Thanks, @schellap, I moved that bug to "preview2" as well.

Do we have a bug to support `dotnet test` using the muxer?

**Comment by schellap** [comment]
Fixed by #3106

**Comment by schellap** [comment]
See expected behavior of #2408. Can use the same bug to track.
