### ISSUE TITLE
dnu pack --out doesn't support forward slash on windows

### ISSUE THREAD

**Issue by sebastienros** [dotnet/cli#253]
Try to use `dnu pack --out ./MyTarget` from windows.

Since rc1 the resulting nupkg contains `/lib/dnxcore50/dnxcore50` which will fail to restore from nuget.
With `dnu pack --out .\MyTarget` it works fine.

**Comment by anurse** [comment]
FYI, this isn't where `dnu` bugs should go, but since the packaging code in `dotnet` is copied, I expect the bug is still there ;P

**Comment by sebastienros** [comment]
Exactly why it's open here as the other one is deprecated ;) and I am also following @davidfowl 's orders. Thanks.

**Comment by anurse** [comment]
Psh, I don't know if I would trust that guy :D

**Comment by livarcocc** [comment]
Just tried this out with dotnet pack --output and both ./MyTarget and .\MyTarget on windows. In both cases, the nupkg were generated correctly.

Closing this.
