### ISSUE TITLE
Shared apps cannot have a custom exe

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/cli#2531]
## Steps to reproduce
Shared apps currently, can only be run using the following commandline
dotnet [pathToAppdll]

This completely breaks branding.

## Expected  behavior
There should be some way of giving these a custom name. Going the standalone apps route and having to build for all supported runtimes that shared apps support just to get a custom name is a painful trade off. 

## Actual behavior
dotnet [pathToAppDll]

## Environment data
1.0.0-rc2-002353

**Comment by gkhanna79** [comment]
CC @schellap

**Comment by gkhanna79** [comment]
@piotrpMSFT Is this about having portable apps that can be executed with a formal "myapp.exe"? If so, are they expected to run against machine wide FX or a downloaded zip version of FX or both? 

Can you please share more details on the scenario?

**Comment by gkhanna79** [comment]
Closing this since as it is no longer actionable.
