### ISSUE TITLE
Standalone apps are slower than shared apps

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/cli#2532]
## Steps to reproduce

Standalone apps currently are not built for .Net native and hence are much slower than shared apps because the host (dotnet.exe) is already crossgen'd. 
## Expected  behavior

There should be some switch to build standalone apps in .Net native so they have the same performance as shared apps.
## Actual behavior

Standalone apps are slower because everything is being Jit'ed.
## Environment data

1.0.0-rc2-002353

**Comment by gkhanna79** [comment]
> Standalone apps currently are not built for .Net native

@AbhitejJohn @piotrpMSFT I presume this means not crossgened, right? If so, we should first address https://github.com/dotnet/cli/issues/2541 as that will improve the experience without requiring apps to be crossgened.

**Comment by AbhitejJohn** [comment]
@gkhanna79 that's true. This is #2541 + process bootstrap optimization. Wouldn't #2541 increase the size of standalone apps installers though? We would just need a subset of the sharedFX that the standalone app uses. #2533 is similar but that covers user assemblies only.

**Comment by gkhanna79** [comment]
@AbhitejJohn The only way to make standalone apps faster is to crossgen - and that will increase size of the apps (due to the presence of native code). Additionally, it will also make them (more) platform specific.

**Comment by gkhanna79** [comment]
> We would just need a subset of the sharedFX that the standalone app uses

I dont believe there is a way to compute this for an app right now.

CC @weshaggard @ericstj

**Comment by blackdwarf** [comment]
This work is tracked in #2541 so will close this one.
