### ISSUE TITLE
User assemblies cannot be as fast as the shared framework

### ISSUE THREAD

**Issue by AbhitejJohn** [dotnet/cli#2533]
## Steps to reproduce

User assemblies currently cannot be crossgen'd and hence are not as fast as the shared framework itself. 
## Expected  behavior

A user should be able to native compile his assemblies if needed to better performance.
## Actual behavior

There isn't an option to crossgen user assemblies. This could hamper performance even if these are run in shared apps.
## Environment data

1.0.0-rc2-002353

**Comment by gkhanna79** [comment]
This is about the scenario of precompiling user apps. @richlander @blackdwarf Do you want to drive the scenario definition for this?

CC @piotrpMSFT @Petermarcu @brthor @jkotas @schellap

**Comment by blackdwarf** [comment]
@gkhanna79 sure.

**Comment by eerhardt** [comment]
We have the `dotnet store` command now.  It will crossgen assemblies by default. Will that work?

**Comment by Petermarcu** [comment]
I think we need to provide an option during publish to crossgen the content of the users folder.

**Comment by dasMulli** [comment]
I've logged a similar feature request on the SDK repo for crossgen-on-publish: https://github.com/dotnet/sdk/issues/593

**Comment by Petermarcu** [comment]
Closing this one to track it here: https://github.com/dotnet/cli/issues/1437
