### ISSUE TITLE
[dotnet publish] Azure Web Site support

### ISSUE THREAD

**Issue by rsbavaresco** [dotnet/cli#2535]
Hello!

I am not able to deploy my application to Azure Web App.

## Steps to reproduce
1) `dotnet publish` at my dir, generating path `bin\Debug\dnxcore50\win7-x64\publish`
Obs: (at this step I can run with sucess from compiled .exe)
2) Change web.config to:

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/>
    </handlers>
    <httpPlatform processPath="..\..\MyApp.exe" arguments="" stdoutLogEnabled="true" startupTimeLimit="3600"/>
  </system.webServer>
</configuration>
```
Also I change to:

```
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="..\..\MyApp.exe" arguments="" stdoutLogEnabled="true" stdoutLogFile="..\logs\stdout" />
  </system.webServer>
</configuration>
```
3) Publish it via FTP

## Expected  behavior

Run successfully on Azure `(azurewebsites.net)`

## Actual behavior

Nothing happens when access URL. None specific log file with error, even with diagnostic enabled. (Maybe someone can help me where get this log file)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc2-002394)

Product Information:
 Version:     1.0.0-rc2-002394
 Commit Sha:  3a423b1080

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
Web Host Builder used extensions:
```
 var host = new WebHostBuilder()
                    .UseWebRoot("..\\Presentation\\wwwroot")
                    .UseDefaultHostingConfiguration(args)                    
                    .UseIISPlatformHandlerUrl()                    
                    .UseKestrel()
                    .UseIIS()
                    .UseStartup<Startup>()
                    .UseUrls("http://localhost:54501")
                    .Build();

            host.Run();

```

**Comment by piotrpMSFT** [comment]
@DamianEdwards @davidfowl can you please make sure this is being tracked in the right place?

**Comment by rsbavaresco** [comment]
@piotrpMSFT I agree. I am a little confusing where to post it. It seems to be a "problem" at Azure but it is a lot of new information, so it is not clear for me yet. Sorry.

**Comment by GuardRex** [comment]
@rsbavaresco Keep in mind that the `AspNetCoreModule` hasn't been rolled out to Azure Apps yet. They're working on it, but there is no ETA yet. RE: Using `HttpPlatformHandler` ... not with that project you're using. Hosting bits are not compatible. You would probably need to go back to rc1-final for the best experience; and with rc2-final so close, you might want to wait it out. In the meantime, consider going with the preview `AspNetCoreModule` on an Azure VM/IIS ... that works great.

**Comment by davidfowl** [comment]
@rsbavaresco please move this to the ASP.NET repository.
