### ISSUE TITLE
Libraries targetting netstandard1.5 cannot be restored for RIDs

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2536]
This is a current problem in NuGet which prevents libraries from having rid specific assets if published. 

Being tracked here:
https://github.com/NuGet/Home/issues/2553
This issue will be used for tracking test skips.

**Comment by piotrpMSFT** [comment]
When this is fixed, please re-enable all tests that are "skipped" due to this issue.

**Comment by piotrpMSFT** [comment]
@emgarten when do you expect this to come in?

**Comment by emgarten** [comment]
@piotrpMSFT the fix is checked into the nuget repo but there is no plan to integrate it into the CLI currently. It could be taken soon if you need the change.

**Comment by piotrpMSFT** [comment]
@emgarten we need the CLI PR. This bug is blocking RC2. There were also tests that had to be disabled because of this issue, so the same PR should re-enable those tests. Please create the PR today/tomorrow to update CLI's 3.5 build of NuGet.

**Comment by piotrpMSFT** [comment]
@emgarten any updates here?

**Comment by emgarten** [comment]
NuGet has been updated: https://github.com/dotnet/cli/commit/7509e4d1750d8fb471c276874c18f8c8a1715765

It looks like the tests weren't re-enabled as part of this, but you should be able to turn them back on now.
