### ISSUE TITLE
Only AppLocal binaries, present in app.deps.json, should be setup by the host

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2537]
Currently, host would add any appLocal binary, which is not in app.deps.json, as part of the app graph when constructing the TPA list.

It should exclude any binaries not in app.deps.json.

CC @jkotas

**Comment by schellap** [comment]
Cc @anurse and @davidfowl. Effectively, `deps.json` will no longer be an optional artifact, i.e., whatever is specified in the deps file will only be setup in the probe paths. App local assemblies just dropped/copied in the app base will not be loaded.

**Comment by jkotas** [comment]
> deps.json will no longer be an optional artifact

I do not think the intend of this issue is to make deps.json non-optional. If you do not have deps.json, it is fine to just pick up everything in the app directory. However, if you do have deps.json, we should pick up just what is in deps.json and not other random stuff that may be laying around.

**Comment by gkhanna79** [comment]
I concur with @jkotas.

**Comment by schellap** [comment]
Fixed by #3195
