### ISSUE TITLE
Add documentation comparing and contrasting with dnx+dnu+dnvm

### ISSUE THREAD

**Issue by mikehaas763** [dotnet/cli#254]
I suspect that many more people will have the same questions I had wondering how this compares to dnx commands.

I did see in the readme: "This toolchain is independent from the DNX-based .NET Core + ASP.NET 5 RC bits" but I can interpret that several ways and I think some more thorough documentation will be helpful.

**Comment by anurse** [comment]
I'm pretty sure this documentation will be forthcoming, but this is a good reminder :). Here's a brief summary of the way things are changing:

| DNX (rc1) | dotnet (post-rc1) |
|----|----|
|`dnx run`|`dotnet run` **OR** `dotnet compile` + `./bin/[config]/[tfm]/MyProject`|
|`dnu build`|`dotnet compile`|
|`dnu pack`|`dotnet pack`*|
|`dnu restore`|`dotnet restore`|
|`dnu publish`|`dotnet publish`*|

(*) Some of these commands don't yet have parity with what DNX/DNU had.

/cc @richlander @DamianEdwards

**Comment by blackdwarf** [comment]
Good catch @mikehaas763 and a good suggestion. I will be making these documents in the upcoming weeks. Just curious, how would you interpret that sentence from the readme? If it is not clear, we should change it.

**Comment by spboyer** [comment]
@anurse missing `dnx web` from your table...?

**Comment by mikehaas763** [comment]
@spboyer Good point. Unless the run command is going to be smart enough to know that a project is an asp.net project and therefore start up a server etc. Right now I believe that command comes from being configured in the project.json file so maybe that's why it's not listed?

Along the same lines I think that a watch or --watch command built in to the dotnet cli tool would be awesome so there is no separate install command for it like we currently need with the dnx cli.

@blackdwarf 

Hard to say what I was originally thinking because I know more now :smile: but I think it sounds like there is a separate dnx/dnu/dnvm commands that work together separately from the dotnet command. That just leads to a lot of deeper questions like:

- Will there always separate dnx+dnu+dnvm commands?
- Which one should I use? (I want to use just a single `dotnet` entry point command that contains other subcommands).

**Comment by spboyer** [comment]
@mikehaas763 - there is a new entry point in the Startup.cs in web apps now, 
``` 
public static void Main(string[] args) => Microsoft.AspNet.Hosting.WebApplication.Run<Startup>(args);
```
which solves the need perhaps as to not need to read the commands section in project.json

**Comment by davidfowl** [comment]
> @spboyer Good point. Unless the run command is going to be smart enough to know that a project is an asp.net project and therefore start up a server etc. Right now I believe that command comes from being configured in the project.json file so maybe that's why it's not listed?

Take a look a the RC1 templates, they have a Main that calls `WebApplication.Run`. There's no need for `dnx web` which was just a shortcut to do the same thing.

> Will there always separate dnx+dnu+dnvm commands?

Neither

> Which one should I use? (I want to use just a single dotnet entry point command that contains other subcommands).

Currently we don't have commands support (and may not have any).

The gist of the change is that the tool chain and runtime are decoupled.

**Comment by mikehaas763** [comment]
> there is a new entry point in the Startup.cs in web apps now
That's interesting. Will have to look into it more.

> Currently we don't have commands support (and may not have any).
Not sure what you mean by this. If you took it as I want to have commands support in project.json that's not what I was getting at.

**Comment by anurse** [comment]
FYI, I updated my table.

We probably won't end up with a watch command in the core dotnet package, but the idea is that other commands can be added from additional packages. Since `dotnet foo` just runs `dotnet-foo`, if someone provides a `dotnet-watch` executable, that will be usable as `dotnet watch`. We're looking at porting the existing https://github.com/aspnet/dnx-watch application to work with `dotnet`, so we'll probably have something here.

**Comment by blackdwarf** [comment]
This is now being done via the CLI docs PR on dotnet/core-docs#391.

**Comment by shawnwildermuth** [comment]
Do you have any info on what is replacing dnvm? Is it going to be part of the dotnet cli toolchain or something separate?

**Comment by piotrpMSFT** [comment]
@blackdwarf can you add this table to our docs and close the issue?

**Comment by blackdwarf** [comment]
All of this exists in the docs now. The migration guide covers this: http://dotnet.github.io/docs/core-concepts/dnx-migration.html. Closing, please file an issue on dotnet/core-docs if more info is needed.
