### ISSUE TITLE
Could not resolve coreclr path

### ISSUE THREAD

**Issue by joffreykern** [dotnet/cli#2547]
Hi, i'm trying to build and run an application (simple app developped by myself). I have the same issue in windows-10-x64 and ubuntu 14.04-x64, when i'm using `dotnet run`, I got `Could not resolve coreclr path` in my console output.

Here is the project.json:
```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Formatters.Json": "6.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnxcore50": {
    }
  },

  "runtimes": {
    "ubuntu.14.04-x64": { },
    "win10-x64": {}
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

## Steps to reproduce
I used `dotnet restore`, then `dotnet build` and to finish `dotnet run`.
Output : 
```
Joffrey@Joffrey-Laptop  ~/Documents/Visual Studio 2015/Projects/AspNetCoreWebApi/src/AspNetCoreWebApi (master)
$ dotnet build
Compiling AspNetCoreWebApi for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.0903549

Joffrey@Joffrey-Laptop  ~/Documents/Visual Studio 2015/Projects/AspNetCoreWebApi/src/AspNetCoreWebApi (master)
$ dotnet run
Project AspNetCoreWebApi (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Could not resolve coreclr path
```

## Environment data
`dotnet --info` output win10-x64:

```
$ dotnet --info
.NET Command Line Tools (1.0.0-rc2-002416)

Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

`dotnet --info` output ubuntu-14.04-x64:
`1.0.0-rc2-002392`

**Comment by piotrpMSFT** [comment]
I don't see a reference to Microsoft.NetCore.App. Your dependencies also suggest this is an RC1/DNX app that is now being restored by CLI. You will need to port the App onto the current toolset. One of these guys should be able to give you access to pre-release guidance docs:

/cc @blackdwarf @davidfowl @glennc

**Comment by davidfowl** [comment]
@joffreykern Please use https://github.com/aspnet/cli-samples as a starting point for ASP.NET Core with the CLI

**Comment by joffreykern** [comment]
@davidfowl @piotrpMSFT I was trying to start a project from an Visual Studio 2015 Update 2 templates, it was a mistake. 

Thanks for your help !
