### ISSUE TITLE
Unable to compile UWP project when referencing NETStandard project v1.4

### ISSUE THREAD

**Issue by binoypatel** [dotnet/cli#2549]
## Steps to reproduce
```
1. Create NETStandard project and make sure to target NETStandard1.4
2. Make sure to add myget.org so that NETStandard.Libarary restored correctly (project.json shows "NETStandard.Library": "1.0.0-rc2-23910")
3. Compile the project and make sure there is no error
4. Create UWP project and make sure to target 10.0.10586
5. Reference the assembly that you created in step 1
6. Compile the UWP project and you will get following errors:
Failed to resolve conflicts for UAP,Version=v10.0.
Failed to resolve conflicts for UAP,Version=v10.0.
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets': Microsoft.NETCore.Targets (>= 1.0.0) (via package/Microsoft.NETCore 5.0.0), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24008) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24008)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets': Microsoft.NETCore.Targets (>= 1.0.0) (via package/Microsoft.NETCore 5.0.0), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24008) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24008)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets.UniversalWindowsPlatform': Microsoft.NETCore.Targets.UniversalWindowsPlatform (>= 5.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Platforms': Microsoft.NETCore.Platforms (>= 1.0.1-rc2-24008) (via package/NETStandard.Library 1.0.0-rc2-23910), Microsoft.NETCore.Platforms (>= 1.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Platforms': Microsoft.NETCore.Platforms (>= 1.0.0) (via package/Microsoft.NETCore.Targets 1.0.0), Microsoft.NETCore.Platforms (>= 1.0.1-rc2-24008) (via package/NETStandard.Library 1.0.0-rc2-23910)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets.UniversalWindowsPlatform': Microsoft.NETCore.Targets.UniversalWindowsPlatform (>= 5.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
NuGet package restore failed.
```
## Expected  behavior
Should not have conflict and compile correctly

## Actual behavior
Unable to compile UWP project with NETStandard assembly 

## Environment data
C:\Program Files (x86)\Microsoft Visual Studio 14.0>dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by davidfowl** [comment]
A few things:
- Can you share your project on github?
- Can you update to the latest CLI here https://github.com/dotnet/cli#installers-and-binaries (SDK installer)

/cc @ericstj @emgarten

**Comment by binoypatel** [comment]
Thanks David for the prompt reply, I tried with the latest cli but same compilation issue, and I cannot share the code on GitHub as it has some proprietary code, here are the compilation issues:

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Failed to resolve conflicts for UAP,Version=v10.0.
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets': Microsoft.NETCore.Targets (>= 1.0.0) (via package/Microsoft.NETCore 5.0.0), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24008) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24008)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets.UniversalWindowsPlatform': Microsoft.NETCore.Targets.UniversalWindowsPlatform (>= 5.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Platforms': Microsoft.NETCore.Platforms (>= 1.0.0) (via package/Microsoft.NETCore.Targets 1.0.0), Microsoft.NETCore.Platforms (>= 1.0.1-rc2-24008) (via package/NETStandard.Library 1.0.0-rc2-23910)
Failed to resolve conflicts for UAP,Version=v10.0.
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets': Microsoft.NETCore.Targets (>= 1.0.0) (via package/Microsoft.NETCore 5.0.0), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24008) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24008)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Platforms': Microsoft.NETCore.Platforms (>= 1.0.1-rc2-24008) (via package/NETStandard.Library 1.0.0-rc2-23910), Microsoft.NETCore.Platforms (>= 1.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets.UniversalWindowsPlatform': Microsoft.NETCore.Targets.UniversalWindowsPlatform (>= 5.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
NuGet package restore failed.

Thanks,
Binoy

**Comment by davidfowl** [comment]
Can you show the `project.json`? Seems like you're using Visual Studio and not the CLI.

**Comment by binoypatel** [comment]
sure, here it is:
This is from NETStandard project:
{
  "supports": {},
  "dependencies": {
    "NETStandard.Library": "1.0.0-rc2-23910"
  },
  "frameworks": {
    "netstandard1.4": {}
  }
}

This is from UWP project:
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Microsoft.OneDriveSDK": "1.1.29",
    "Newtonsoft.Json": "8.0.2"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}

**Comment by ericstj** [comment]
In the UWP project try  "Microsoft.NETCore.UniversalWindowsPlatform" : "5.2.0-rc3-24015-00" instead.

**Comment by binoypatel** [comment]
Thanks Eric, it worked after updating UWP project as you suggested

**Comment by anders9ustafsson** [comment]
@ericstj I am running into the same issue with RC2:

>Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets': Microsoft.NETCore.Targets (>= 1.0.0) (via package/Microsoft.NETCore 5.0.0), Microsoft.NETCore.Targets (>= 1.0.1-rc2-24027) (via package/Microsoft.NETCore.Platforms 1.0.1-rc2-24027)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Platforms': Microsoft.NETCore.Platforms (>= 1.0.1-rc2-24027) (via package/NETStandard.Library 1.5.0-rc2-24027), Microsoft.NETCore.Platforms (>= 1.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)
Unable to satisfy conflicting requests for 'Microsoft.NETCore.Targets.UniversalWindowsPlatform': Microsoft.NETCore.Targets.UniversalWindowsPlatform (>= 5.0.0) (via package/Microsoft.NETCore.Targets 1.0.0)

My UWP app is dependent upon *Microsoft.NETCore.UniversalWindowsPlatform*, 5.1.0, but I get same build result with version 5.0.0.

For the .NET Core class library, I have tried with frameworks *netstandard* 1.0, 1.3 and 1.4 with the same result. For 1.5, it claims that *uap10.0* is not compatible with *netstandard1.5*.

If I change *Microsoft.NETCore.UniversalWindowsPlatform* version to the release candidate proposed above (5.2.0-rc3-24015-00), the dependency cannot be resolved at all. Is there another Universal Windows Platform release candidate for RC2?

**Comment by ericstj** [comment]
RC2 should not be used for targeting UWP.  There was a long list of bugs that didn't meet the bar for fixing in RC2 so we fixed them in RC3.

To use the RC3 packages make sure you pull them from the https://dotnet.myget.org/F/dotnet-core/api/v3/index.json feed.
