### ISSUE TITLE
dotnet compile --native should pass app dependencies to ILC.exe

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#255]
This functionality was taken out because the CoreRT framework libraries are currently only included in the AppDepSDK Nuget package. 

We need to think about where the framework libraries will eventually come from, and how we deal with third party app dependencies.

/cc @gkhanna79 @schellap @livarcocc

**Comment by gkhanna79** [comment]
@brthor - To confirm, are you saying that "-r" is only passed for System.Private.Corelib.dll and AppDepSDK?

**Comment by schellap** [comment]
@gkhanna79, we need more libraries in AppDepSDK like EntityFramework. If there are third party libraries, how is ILC supposed to work? Will we do -r ThirdPartyApp.dll or our goal is to have a native image for each IL binary?

**Comment by gkhanna79** [comment]
Longterm, acquisition of 3rd party libraries would be part of restoring the app which would declare dependency on such libraries. At that point in time, dotnet compile native should be passing -r for all libraries constituting the app to ilc.

**Comment by schellap** [comment]
--ilcargs "-r reference1.dll -r reference2.dll" can be passed in such a case as of now.

**Comment by davidfowl** [comment]
this includes packaging for aot things. Today projects only target dnxcore50 but the aot things are netcore50 and this needs to be sorted

**Comment by brthor** [comment]
@gkhanna yes currently only appdepsdk/*.dll and System.Private.CoreLib are passed as references

**Comment by gkhanna79** [comment]
@davidfowl - I agree. Who is driving that? @richlander may have some context on who maybe driving the transition to netcore50.

**Comment by piotrpMSFT** [comment]
@brthor can you start linking issues for the pre-requisites of this issue?

**Comment by brthor** [comment]
@piotrpMSFT Child issues have been created. 

#402 
#404 
#405 
#406 

@schellap @gkhanna79 
Please review these issues to ensure we are still on the same page. Feel free to offer any corrections.

**Comment by brthor** [comment]
@schellap You have been working on this. Want to take this issue?

**Comment by blackdwarf** [comment]
@schellap do we want to move this over to dotnet/corert?

**Comment by gkhanna79** [comment]
@nattress Can you please create an issue to reference this and close this one?

**Comment by piotrpMSFT** [comment]
@nattress ping

**Comment by nattress** [comment]
See https://github.com/dotnet/corert/issues/1584
