### ISSUE TITLE
Resouces with a space in the name cannot be compiled by dotnet cli

### ISSUE THREAD

**Issue by thecodejunkie** [dotnet/cli#2551]
## Steps to reproduce

Add an embedded resource, with one or more spaces in the filename

``` json
"resource": [
    "Resources/Nancy Testing Cert.pfx"
],
```
## Expected  behavior

To have the file embedded in the assembly. It worked with `dnx` but not with `dotnet`
## Actual behavior

It seems that ends up splitting the filename on the spaces

```
<path>\Nancy\src\Nancy.Testing\error CS2001: Source file '<path>\Nancy\src\Nancy.Testing\Testing' could not be found.
<path>\Nancy\src\Nancy.Testing\error CS2001: Source file '<path>\Nancy\src\Nancy.Testing\Cert.pfx' could not be found.
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002416)

Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
setting to 1.0.0-rtm since this bug has an obvious workaround. Thanks for catching it, @thecodejunkie

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
