### ISSUE TITLE
Add support for FX_DEPS_JSON property

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2558]
The host should specify the path to deps.json corresponding to the one that the app is being activated against. This can be used by apps (e.g. CLI) as appropriate.

CC @brthor @piotrpMSFT @schellap

**Comment by brthor** [comment]
In the case of deps.json's being merged, which file path will be available via this property?

**Comment by gkhanna79** [comment]
Are you referring to standalone apps? If so, then this should be path of the standalone app's deps.json.

**Comment by schellap** [comment]
We should use a property called FX_BASE_DIRECTORY. Why FX_DEPS_JSON?

**Comment by gkhanna79** [comment]
> Why FX_DEPS_JSON?

Once you have the path to the deps.json, you can compute the path to Shared FX. Also, this alleviates the need to introduce a new property in future to point to the FX's deps.json, if required.

**Comment by piotrpMSFT** [comment]
@gkhanna79 @schellap I'm not sure we can absorb consuming this property for RC2. Let's give it a shot, but if you get other blocking work then I'd prioritize this lower since it really creates benefit when CLI-side of the work is also done.

**Comment by gkhanna79** [comment]
@piotrpMSFT Is this not required for RC2?

**Comment by gkhanna79** [comment]
My understanding is that we need this for RC2 to ensure CLI can pickup the FX path correctly incase binaries get serviced.

**Comment by piotrpMSFT** [comment]
ok. Sounds like @schellap is also picking up #2489 to test the fix for this one.

**Comment by piotrpMSFT** [comment]
@schellap any update here?

**Comment by schellap** [comment]
Part of the fix is in PR #2546

**Comment by schellap** [comment]
Fixed by #2546
