### ISSUE TITLE
Compiler exit code string should not be sent to stderr

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#2561]
When VS does a build using dotnet build, it hooks stdout and stderr and assumes every string sent to stderr is an error which needs to go to the error list. The problem is that if the csc compiler generates an error (which is correctly output to stderr), dotnet build is also outputting the following string indicating the csc compiler returned an error.

`"C:\\Program Files\\dotnet\\dotnet.exe compile-csc \"@c:\\users\\billhie\\documents\\visual studio 2015\\Projects\\ConsoleApp12\\artifacts\\src\\ConsoleApp12\\obj\\Debug\\netcoreapp1.0\\dotnet-compile.rsp\" returned Exit Code 1"`

Since the string is output to stderr this gets added to the error list. 

Ideally, this would be output to stdout as informational since csc Is already outputting errors correctly. Without this change, VS will need to somehow detect this string and filter it out.

**Comment by piotrpMSFT** [comment]
@BillHiebert RC2 or RTM?

**Comment by BillHiebert** [comment]
RTM - I am going to put in a work around for RC2

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.

VS no longer invokes MSI to get the error list.
