### ISSUE TITLE
Cryptic error message when using netstandard1.5 moniker for a runnable target

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2562]
The app was supposed to be runnable but targeted `netstandard1.5` and not `netcoreapp1.0`. Trying to run the app results in a cryptic error: `Could not load host policy library from [C:\Users\\Documents\Visual Studio 2015\Projects\dotnet-scratch\bin\Debug\netstandard1.5]
`

Instead the message should made it clear what's wrong and how to fix this.

More details in https://github.com/dotnet/cli/issues/2555

**Comment by piotrpMSFT** [comment]
This issue is not very clear cut. We encourage folks to use netcoreapp1.0 for executable applications but there is no technical reason why they must use that framework to build a valid application. This feels like a real opportunity for enhancement but we will need to identify a clean solution.

**Comment by blackdwarf** [comment]
Actually, this is fixed in the latest tooling, since it will specify what the user should do.

**Comment by livarcocc** [comment]
Yep, this is fixed. This is what happens now:

```
$ dotnet run
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Library'.
```

**Comment by moozzyk** [comment]
Actually "The current OutputType is 'XXXX'." can be totally confusing. If you look at [this](https://github.com/aspnet/SignalR/blob/2fff96311b5a740c23f1a2e1ddadd6127459ba24/test/Microsoft.AspNetCore.SignalR.Test.Server/Microsoft.AspNetCore.SignalR.Test.Server.csproj) csproj you will see that it is targeting both `netcoreapp1.1` and `net46`  and the OutputType is Exe. I tried running the netcoreapp1.1 and there was something wrong and I got an error with the message reading: `The current OutputType is 'Exe'.`. I thought it was the source of the problem because I wanted to run netcoreapp1.1 which should be Library given that I was using shared runtime.

**Comment by livarcocc** [comment]
I am not sure what you mean by this statement:
> I thought it was the source of the problem because I wanted to run netcoreapp1.1 which should be Library given that I was using shared runtime.

Can you clarify? From what I can see in that project, it is an app and it is runnable.

**Comment by moozzyk** [comment]
If I am running an app with a shared runtime (and not standalone) my application should be compiled to a .dll. The message said `The current OutputType is 'Exe'` so I thought something was wrong with my csproj and it generated exe instead of dll. 
In general I am not sure why/when this message is helpful. In this particular scenario the message should say something like: your application is targeting more than one framework and you did not provide the framework you want to use to run this application.

**Comment by livarcocc** [comment]
OutputType is a well known property from MSBuild, which is why we chose to use it.

**Comment by moozzyk** [comment]
How does it apply to apps targeting netcoreapp?

**Comment by livarcocc** [comment]
You can have a library that targets netcoreapp but that is still a library. Which is why you need both.

**Comment by moozzyk** [comment]
Then it is probably fine. When I filed this bug netcoreapp libraries were not the thing. I need to try this scenario again to see how things behave but most likely it will be possible just to close this bug without any further action.

**Comment by livarcocc** [comment]
Ok. Re-activate if something else comes up.
