### ISSUE TITLE
Add installer support for Debian

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#2565]
When the initial work was done to support [Debian](https://github.com/dotnet/cli/issues/212) in RC2, a decision was made for scoping reasons to not include the work to produce Debian packages.  This work should include the necessary publish changes to produce Debian packages so that dotnet can be acquired via apt-get on Debian just like what can be done on Ubuntu today.

**Comment by brthor** [comment]
@chuan recently enabled the capability in our repo to publish packages for specific distributions.

Can you comment on what work might be involved to take advantage of that feature @chuan?

**Comment by Daniel15** [comment]
Is there some difference between Ubuntu and Debian that mean you need to build separate Debian packages instead of just reusing the Ubuntu packages?

**Comment by piotrpMSFT** [comment]
Yea, the native bits in CoreFx are currently not portable across Linux distros...

**Comment by fsateler** [comment]
Having a .deb package that installs on debian would be great. Is there any way I could help move this forward?

**Comment by livarcocc** [comment]
Tracking this in #6113. Closing this one.
