### ISSUE TITLE
Commands cannot execute from a desktop .NET process

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#2566]
## Steps to reproduce
Create a command using Microsoft.DotNet.Cli.Utils.
Call Command.Execute()
Example:
```c#
Command.CreateDotNet(
                "build",
                new[] { projectPath })
                .Execute();
```
## Expected  behavior
Starts process "dotnet.exe build {projectPath}". 
Process begins to execute successfully.
Process can forward stderr/stdout

## Actual behavior
```
Running dotnet.exe build ..\DesktopStartup
System.InvalidOperationException: The Process object must have the UseShellExecute property set to false in order to redirect IO streams.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
```

## Environment data
Microsoft.DotNet.Cli.Utils/1.0.0-rc2-002416

```
Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

This is blocking https://github.com/aspnet/EntityFramework/issues/4577

**Comment by natemcmaster** [comment]
cc @divega

**Comment by brthor** [comment]
@natemcmaster Am I understanding this right that you are using this:
```
Command.CreateDotNet(
                "build",
                new[] { projectPath })
                .Execute();
```

from inside a desktop application?

Would it be possible to post a full project to help repro this?

**Comment by brthor** [comment]
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Windows.cs#L50

Pretty sure this is the issue.

On Desktop it is true by default and we don't explicitly set a value. The fix is simple but I am also going to add a test here.

**Comment by natemcmaster** [comment]
Here is a repro. [issue2566.zip](https://github.com/dotnet/cli/files/225026/issue2566.zip)
Try `dotnet -v run ./`

**Comment by brthor** [comment]
thanks @natemcmaster !
