### ISSUE TITLE
CLI must reference the aspnet packages from 'aspnetrelease' feed

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2567]
@eerhardt The 1.0.0-rc2* aspnet packages in the `cli-deps` feed seem to be from `aspnetcidev` (the assemblies are not signed correctly). We must be picking those packages from the `aspnetrelease` feed.

**Comment by Sridhar-MS** [comment]
List of assemblies that ship with the CLI

Microsoft.Extensions.CommandLineUtils.Sources.dll,
Microsoft.Extensions.Configuration.Abstractions.dll,
Microsoft.Extensions.DependencyInjection.Abstractions.dll,
Microsoft.Extensions.FileSystemGlobbing.dll,
Microsoft.Extensions.Logging.Abstractions.dll,
Microsoft.Extensions.Logging.Console.dll,
Microsoft.Extensions.Logging.dll,
Microsoft.Extensions.PlatformAbstractions.dll,
Microsoft.Extensions.Primitives.dll,

**Comment by eerhardt** [comment]
We need to get our WebHook on the aspnetrelease feed.  I emailed the ASP.NET team about it.

@Eilon @muratg

**Comment by muratg** [comment]
@Sridhar-MS you guys should use aspnetrelease feed for your "RC2" branches (I believe rel/1.0.0)..  Your RTM branches (I believe master ) should continue to use aspnetcidev feed. 

This would reflect our usage of the feed. 

@eerhardt @Eilon added the WebHook.

**Comment by eerhardt** [comment]
@muratg - I assume `aspnetcidev` and `aspnetrelease` have different version numbers, right?  ex. `aspnetrelease` creates package versions `rc2-12345` and `aspnetcidev` creates package versions `rc3-12345`. If not, how can you tell the packages apart?

One thing to note is that ALL the CLI dependencies get aggregated into a single feed - dotnet.myget.org/F/cli-deps - and both CLI `master` and `rel/1.0.0` branches use that single feed.

**Comment by muratg** [comment]
First of all let me correct myself.  Please do NOT use `aspnetcidev` feed.  Our development branch feed is `aspnetvnext`.

| aspnet branch | cli branch | aspnet feed| 
|--------------------|--------------|---------------|
| release            | rel/1.0.0    | aspnetrelease| 
| dev                  | master      | aspnetvnext |

@eerhardt yes, currently packages in `aspnetrelease` are `-RC2-1234`, and `aspnetvnext` are `RC3-1234`.

**Comment by piotrpMSFT** [comment]
We won't be creating a separate RC2 branch unless we need to service. Everyone is working on RC2 so the cost of new CI doesn't make much sense. rel/1.0.0 will point to aspnetrelease until we snap RC2, then will get redirected to aspnetvnext.
