### ISSUE TITLE
What is Microsoft.DotNet.Tools.Pack?

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#257]
It is showing in my VS as some broken project

**Comment by davidfowl** [comment]
@anurse Added it recently. It makes a nuget package from a project.

**Comment by anurse** [comment]
What's broken about it? Is there an error in it?

**Comment by krwq** [comment]
It won't open in VS but is displayed. Am I missing some tool in VS?

**Comment by anurse** [comment]
Not sure why, but the xproj for that project got removed. I regenerated it and checked it in to master.
