### ISSUE TITLE
dotnet build scripts fail when the script command file is written with UTF-8+BOM

### ISSUE THREAD

**Issue by dleeapho** [dotnet/cli#2573]
## Steps to reproduce

1. Add "scripts" to a project.json, eg. [https://github.com/dotnet/cli/tree/rel/1.0.0/TestAssets/TestProjects/TestAppWithScripts](url)
2. Create the script file (echoscript.sh or echoscript.cmd) using an editor that saves with a BOM (byte order marker) like the Visual Studio 2015 code editor.
3. `dotnet build` 

## Expected  behavior
The script command file is invoked at precompile and postcompile and there are no build errors.

## Actual behavior
In Ubuntu the scripts are not run, there are no errors.

In Visual Studio 2015, there are errors in the errorlist with the following output:
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : '﻿@echo' is not recognized as an internal or external command,
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : operable program or batch file.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : '﻿@echo' is not recognized as an internal or external command,
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : operable program or batch file.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002416)

Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.10
 OS Platform: Linux
 RID:         ubuntu.15.10-x64

**Comment by brthor** [comment]
do these scripts run from the command line with the bom introduced?

**Comment by dleeapho** [comment]
Yes I see what you are getting at @brthor . The shell is not liking the BOM either so the "scripts" invocation can't be expected to be resilient to BOM.

**Comment by brthor** [comment]
My intuition here is that for unix scripts, the BOM is going to mess with the hashbang at the beginning. I'm not sure how we can work around that.

**Comment by piotrpMSFT** [comment]
Since the script is also not working from the shell, this is not a CLI issue. We can only kick off scripts that work :trollface: 

Does the message we pass through match what the OS tells you? Or do we need a better UX?

**Comment by piotrpMSFT** [comment]
Please re-open if we need a better message.

**Comment by dleeapho** [comment]
Makes sense. There might be an issue with the VS tooling scenario. I'll investigate how the BOM got introduced by the tooling.
