### ISSUE TITLE
Occasional locking of the `project.lock.json` file

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2577]
## Steps to reproduce
1. Open a project in VS Code.
2. Immediately `dotnet restore` the project.
3. Sometimes (rarely) a process locks the `project.lock.json` file.
4. Running `dotnet restore` again has been successful ~100% of the time.

## Expected  behavior
The `project.lock.json` file is written at the end of the restore. Re-restoring a 2nd time is never necessary.

## Actual behavior
```
log  : Writing lock file to disk. Path: c:\_APPLICATIONS\teststandalone\project.lock.json
error: The process cannot access the file 'c:\_APPLICATIONS\teststandalone\project.lock.json' 
because it is being used by another process.
```
Could this be due to a VS Code or OmniSharp background task that locks the file for a few seconds when the project is open? I feel it happens more frequently when I open a project and immediately restore, which has been especially easy and fast with my [Status Bar Tasks](https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks) extension.

## Environment data
```
.NET Command Line Tools (1.0.0-rc2-002416)

Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
@GuardRex I believe this should be reopened on Nuget/Home if it still repros as `dotnet restore` is using Nuget under the covers to do the restore.

**Comment by micdenny** [comment]
`nuget restore -DisableParallelProcessing` worked for me
