### ISSUE TITLE
Build DotNetHostPolicy packages with serviceable attribute

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#2582]
Since we decided not to mark assemblies as serviceable, instead, the packages as serviceable, the host policy package needs to be marked so as well.

@gkhanna79, just filing a tracking issue for RTM.

**Comment by schellap** [comment]
Packages should be serviceable.

**Comment by schellap** [comment]
@anurse, I'd like to close this one out, once you have a fix for #2523

**Comment by schellap** [comment]
This bug is blocked on #2523

**Comment by gkhanna79** [comment]
CC @leecow who is driving #2523

**Comment by piotrpMSFT** [comment]
Moved to core-setup
