### ISSUE TITLE
Enable MutlicoreJIT to Further Reduce Critical Path JIT Time for Dotnet.exe

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2584]
In addition to using crossgen to reduce JIT time of the CLI binaries, I'd also recommend using Multi-Core JIT to reduce the critical path JIT time.  Multi-Core JIT works by keeping track of which methods get used, persisting that to a file, and then on the subsequent run, JIT compiling those methods on a background thread (hopefully) before they're actually needed by the program.

In prototyping that I did, I was able to reduce the foreground JIT time for dotnet build of HelloWorld by 50%.

**Comment by piotrpMSFT** [comment]
@brianrob is this just a change to the runtime options for dotnet.dll?

**Comment by brianrob** [comment]
This is a change that gets made in the application.  The goal is to make it as early as possible, but it needs to be done once the binding model (default AssemblyLoadContext) isn't going to change.  I don't believe you set it in dotnet.dll, so you should be able to set it in the entrypoint.

`AssemblyLoadContext.Default.SetProfileOptimizationRoot(<path to writable directory for profile>);
AssemblyLoadContext.Default.StartProfileOptimization(<profile name that you make up>);`

**Comment by piotrpMSFT** [comment]
@brianrob `dotnet.dll` is the entry point dll for the CLI :)

@gkhanna79 @schellap is this setting already captured in runtimeconfig.json? What do we need to set to turn this on?

**Comment by gkhanna79** [comment]
@brianrob Should this be opted in or out? Based upon the answer, @piotrpMSFT runtimeconfig.json should contain the correct opt-in/out and dotnet.dll implementation should consume it to enable/disable Multi-CoreJIT.

**Comment by brianrob** [comment]
Multi-Core JIT requires that you opt-in.  By default it is off, so you'd want to opt-in.

**Comment by piotrpMSFT** [comment]
I see, this is a managed API. How do you recommend testing that Multi-Core JIT is working? Shall we just check the ProfileOptimizationRoot for content? Or is there a stronger validation we can do?

**Comment by brianrob** [comment]
Checking for the profile after process shutdown is likely the best one (at least for automation).  If you want to do a one-off validation, you can hook a debugger and see the background thread start compiling.  We can (and will) also take a trace and see how many / which methods get background compiled.

**Comment by piotrpMSFT** [comment]
Automation is what I was after. This sounds good.

**Comment by piotrpMSFT** [comment]
@brianrob @gkhanna79 should the profile optimization root be distinct across invocations or unique?

**Comment by piotrpMSFT** [comment]
Also, is the feature designed to have multiple processes use the same root path? Do apps need to worry about the state of files written in that directory? What sorts of validation/management is the app responsible for?

**Comment by piotrpMSFT** [comment]
I'm planning to put the optimization data in:

Windows: $env:LocalAppData\Microsoft\dotnet
Non-Windows: /usr/local/share/dotnet

**Comment by piotrpMSFT** [comment]
Though a PR is ready for this issue, @brianrob is validating if this is a fix we want to bring forward in RC2. Moving to backlog for the time being.
