### ISSUE TITLE
Append `-1` to debian upload_json

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#2589]
Currently we produce our debian packages with `-1` appended to the suffix. 

This is a debian best practice so that debian package only hot fixes may happen. 

This is currently breaking our package uploads since a strict enforcement of matching the declared version (without -1) and the actual version was implemented. 

For a quick fix we should consider appending -1 to our declared version when uploaded.

cc @chuan

**Comment by piotrpMSFT** [comment]
@Petermarcu approved this fix in my office.
