### ISSUE TITLE
Move Telemetry out of process from dotnet CLI

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/cli#2595]
Telemetry reporting takes ~15% of runtime for some CLI usage scenarios. Reporting needs to be moved into an asynchronous process.

**Comment by anurse** [comment]
What's the status of this? It's impacting build times because we're seeing a ~1sec pause at the end of build due to telemetry.

/cc @pakrym @davidfowl

**Comment by piotrpMSFT** [comment]
@LakshanF started looking into this today.

**Comment by vancem** [comment]
Note that the first line of attack here is to cut the amount of telemetry data being logged.   In particular we certainly should be logging every build.

Also 1 second is a VERY long time to upload telemetry in an average case (I would have expected 1/10th that).   

It may be reasonable to have the uploader be a separate process, but I would not introduce this complexity proactively.   First create a good sampling story (and sample 1/1000) and figure out why the upload is so slow before introducing the complexity.

**Comment by ctolkien** [comment]
>Also 1 second is a VERY long time to upload telemetry in an average case (I would have expected 1/10th that). 

Please bear in mind users (such as myself) located on the other side of the world with crappy internet,  high latency and heavily constrained connections.

**Comment by livarcocc** [comment]
This is not something we have plans on doing anymore.
