### ISSUE TITLE
An item with the same key has already been added. Key: System.Runtime

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#2596]
## Steps to reproduce

I'm trying to build docfx from their [net462 branch](https://github.com/dotnet/docfx/tree/net462) at this commit: https://github.com/dotnet/docfx/commit/18b96381e4e6cb7abca365dcb09a641f65f75313. 

I ran `dotnet restore` from the `src` folder and `dotnet build` form the `src/docfx` folder.

## Expected  behavior

Successful build or a meaningful build error

## Actual behavior

```
C:\Users\daroth\Documents\GitHub\docfx\src\docfx [net462]> dotnet build
An item with the same key has already been added. Key: System.Runtime
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by danroth27** [comment]
Possible dup of #2552

**Comment by danroth27** [comment]
@qinezh

**Comment by danroth27** [comment]
Might be because I tried to build without .NET 4.6.2 installed. Still, the error message is bad.

**Comment by davidfowl** [comment]
Dupe!
