### ISSUE TITLE
Add RID ubuntu.16.04-x64 support

### ISSUE THREAD

**Issue by songdongsheng** [dotnet/cli#2598]
## Steps to reproduce

Runing build.sh in ubuntu.16.04-x64:

root@ubuntu-1604-01:~/vcs/git/dotnet/cli# ./build.sh

## Actual behavior

Many errors 'there is no run-time assembly compatible with ubuntu.16.04-x64', e.g.

error: Microsoft.Win32.Primitives 4.0.1-rc2-24018 provides a compile-time reference assembly for Microsoft.Win32.Primitives on .NETStandardApp,Version=v1.5, but there is no run-time assembly compatible with ubuntu.16.04-x64.

error: System.AppContext 4.1.0-rc2-24018 provides a compile-time reference assembly for System.AppContext on .NETStandardApp,Version=v1.5, but there is no run
-time assembly compatible with ubuntu.16.04-x64.

error: System.Collections 4.0.11-rc2-24018 provides a compile-time reference assembly for System.Collections on .NETStandardApp,Version=v1.5, but there is no
run-time assembly compatible with ubuntu.16.04-x64.

error: System.Console 4.0.0-rc2-24018 provides a compile-time reference assembly for System.Console on .NETStandardApp,Version=v1.5, but there is no run-time
assembly compatible with ubuntu.16.04-x64.

...

## Environment data
`dotnet --info` output:

root@ubuntu-1604-01:~/vcs/git/dotnet/cli/.dotnet_stage0/Linux# ./dotnet --version
1.0.0-rc2-002439

root@ubuntu-1604-01:~/vcs/git/dotnet/cli/.dotnet_stage0/Linux# ./dotnet --info
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

**Comment by piotrpMSFT** [comment]
Ubuntu 16.04 is not yet supported by CoreFx. This will be done as part of 16.04 bring-up.

**Comment by atrauzzi** [comment]
Is there anywhere for people to keep an eye on progress?

**Comment by jaylittle** [comment]
++

I'm pretty eager to get this resolved on Ubuntu 16.04.  In addition I wonder whether limiting Linux distribution support in such a specific way is that great of an idea.  There are a lot of Linux distributions out there... just saying.

**Comment by songdongsheng** [comment]
Yes, I'm also wondered why not just running with general distribution name (Linux-x64, linux-arm64, Windows-x64, etc) like Java?

**Comment by tmds** [comment]
@songdongsheng https://github.com/dotnet/cli/issues/2727
