### ISSUE TITLE
[dotnet restore] --configfile is relative to project dir instead of the cmd dir

### ISSUE THREAD

**Issue by phenixdotnet** [dotnet/cli#2599]
## Steps to reproduce
Assume this solution structure:
- MySol
    - nuget.config
    - src
         - MyProject

Open a cmd prompt and move to MySol directory

## Expected  behavior
Relative path are evaluated from the current prompt directory and not from the project directory

## Actual behavior
When running ```dotnet restore --configfile .\nuget.config``` from a cmd in ```MySol``` dir the command fail with this output:
```error: File 'c:\dev\MySol\src\MyProject\.\nuget.config' does not exist.```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14316
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Can you please open this bug in https://github.com/nuget/home?

/cc @yishaigalatzer @emgarten

**Comment by phenixdotnet** [comment]
Sure, Thanks for the quick response
