### ISSUE TITLE
CLI repo cannot be build when offline

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#260]
Building CLI repo attempts to download the latest CLI dotnet tools - this operation will fail when the machine is offline. Is there a specific reason we always download the latest tools to build the repo? Why can we not use the tools downloaded by a previous build, or explicitly installed by the developer?

**Comment by Sridhar-MS** [comment]
The dotnet commands/contents/layout of the packages are constantly changing and building against the latest builds is a  good feedback loop we are using now. 

I guess we can detect offline mode and as a fallback use the installed/older version of dotnet. But still such a build may be very different to the CI/official builds and may be prone to failure. 

But anyways you may need to be connected when restoring nuget packages for the CLI repo.

**Comment by gkhanna79** [comment]
@Sridhar-MS Does that mean I cannot build CLI repo if the packages are already restored?

**Comment by Sridhar-MS** [comment]
Well, we do specify `no-cache` when restoring. https://github.com/dotnet/cli/blob/master/scripts/compile.ps1#L49
https://github.com/dotnet/cli/blob/master/scripts/compile.sh#L54

Let me try without the `no-cache` option.

**Comment by anurse** [comment]
`no-cache` only affects the HTTP cache, if the requested version of a package is already installed it will not be reinstalled.

**Comment by Sridhar-MS** [comment]
We still need to use `ignore-failed-sources` for restore to work offline (provided the packages are already locally installed).

**Comment by piotrpMSFT** [comment]
Was on a plane. Had to work offline. Fixed the issue [on Windows]. @brthor, can you port this to Linux?

**Comment by brthor** [comment]
Working on it

**Comment by enricosada** [comment]
:+1: also because are this zip is big ( dunno you internally at ms, but outside is really a big download )
the build.cmd is really nice to test a change

**Comment by anurse** [comment]
It is pretty fast internally, but I totally agree about making it a skippable part of the build :). We intend to shrink the ZIP down a lot more, right now it has three complete copies of the CoreCLR (one for apps to use, one for the tools to use and one for the embedded DNX we use to hackily implement `dotnet restore` :)) so there's a lot of duplication to remove :)

**Comment by brthor** [comment]
See #544 

This will be great for developer builds :smile:
