### ISSUE TITLE
apt repo may not contain latest dotnet-cli builds (?)

### ISSUE THREAD

**Issue by colemickens** [dotnet/cli#2604]
Latest package in apt: dotnet-dev-1.0.0-rc2-002416

Latest package on README (according to the badge, at least): 1.0.0-rc2-002439

Looks like last deb available in the repo was modified on the 17th (three days ago).

Not sure if this is expected.

**Comment by brthor** [comment]
This is a result of #2589 

Our repo partners added some additional validation which we needed to account for, the fix was merged this morning.

**Comment by colemickens** [comment]
This is fixed. Thanks.
