### ISSUE TITLE
Mysterious Newtonsoft.Json conflict when depending on a library from a Web app

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2605]
## Steps to reproduce
ungzip downgrade.tar.gz
tar -xf downgrade.tar

There are two projects in the tar ball: 1) a web app and 2) library which depends on Newtonsoft.Json.

App/project.json:
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-20507",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-20507",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002359"
    },
    "lib" : "1.0.0-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": ["dnxcore50", "portable-net45+win8"]
    }
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-rc2-20507"
  }
}

lib/project.json
{
  "version": "1.0.0-*",
  "dependencies": {
    "NETStandard.Library" : "1.5.0-rc2-23931",
    "Newtonsoft.Json": "8.0.3",
    "System.Runtime.Serialization.Primitives" : "4.1.1-rc2-*",
    "System.Dynamic.Runtime": "4.0.10",
    "WindowsAzure.Storage": "7.0.1-preview",
    "System.Net.Requests": "4.0.0-rc2-*"
  },
  "frameworks": {
    "netstandard1.5": {
      "imports" : [
        "dnxcore50",
        "portable-net45+netcore45+wpa81+MonoAndroid1+MonoTouch1"
      ]
    }
  }
}

cd lib
dotnet restore
cd ../app
dotnet restore

## Expected  behavior
Success!

## Actual behavior
Errors in /Users/xyz/Documents/Projects/bug/downgrade/app/project.json
    Package Newtonsoft.Json 7.0.1 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Newtonsoft.Json 7.0.1 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
      - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

First question: There is no explicit dependency on Newtonsoft.json 7.0.*, how are you supposed to know why it is pulled in and how to fix it?  (It turns out it is the IIS tool, but how do you discover that?  Further, why is that tool depending on such an old version?)

Second question: Why do these restore successfully individually (eg. remove the lib dependency from app) but fail when dependent?

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
[downgrade.tar.gz](https://github.com/dotnet/cli/files/228546/downgrade.tar.gz)

**Comment by eByte23** [comment]
@jeffschwMSFT you need to add imports property in the iis dependency in tools. This will be fixed soon when the tools dependencies are updated.

E.g.

   
tools": {
 "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
"version":"1.0.0-rc2-20507",
"imports":["portable-net40+sl5+win8+wp8+wpa81"]
 }

**Comment by jeffschwMSFT** [comment]
@eByte23 thanks for the point-in-time workaround.  I am still a little baffled why the app restores successfully without these imports and without the lib dependency.  It seems like there is a warning/error case missing.

**Comment by piotrpMSFT** [comment]
Can you please open this bug in https://github.com/nuget/home?

/cc @yishaigalatzer @emgarten

**Comment by yishaigalatzer** [comment]
It is because one of the dependencies asked for a different version. Not sure there is a bug to open

**Comment by jeffschwMSFT** [comment]
@yishaigalatzer here is how I see it.  Project A restores and builds fine and Project B restores and builds fine.  If A depends on B, A stops restoring.  I have not tried @eByte23 workaround, by why would adding a new imports to A make this work, when the dependency that is failing is part of A.  If A worked standalone it should work when it depends on B.

The bug is around discoverability of what to do to fix this issue.  This one is particularly bad because the import is implicit from another dependency.
