### ISSUE TITLE
dotnet publish doesn't take argument to point to restored packages

### ISSUE THREAD

**Issue by joperezr** [dotnet/cli#261]
Here is my scenario:

I want to restore some packages specified on my project.json and then I want to publish the runtime for a specific framework and runtime into one folder. The issue is that when I restore the packages, I want to be able to specify where to restore the packages, like:
```
> dotnet.exe restore project.json --packages C:\repoRoot\packages
```

If then I try to run publish, it won't work as it looks for the restored packages in %UserProfile%\.dnx\packages folder and there is no way for me to specify where to get them from. The desired argument would look like:

```
> dotnet.exe publish project.json -f dnxcore50 -r win7-x64 --packagesRoot C:\repoRoot\packages\
```

**Comment by joperezr** [comment]
cc @brthor

**Comment by brthor** [comment]
/cc @piotrpMSFT 

I think this functionality would be useful. Since restore supports custom locations, it makes sense that the rest of our tools would.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
