### ISSUE TITLE
CLI Builds should publish when all builds are finished

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2613]
## Steps to reproduce
go to https://github.com/dotnet/cli

## Expected  behavior
All versions are the same

## Actual behavior
Builds get out of sync, so you will have fixes on one OS but not on others.

**Comment by muratg** [comment]
:eyes:

**Comment by Petermarcu** [comment]
@socket, should this be closed now that your change went in?

**Comment by sokket** [comment]
It is closed? :)

**Comment by Petermarcu** [comment]
Ha ha
