### ISSUE TITLE
dotnet test fails if --no-build and --base-build-path is passed and assemblies are present in the base build path folder

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/cli#2615]
## Steps to reproduce
"C:\Program Files\dotnet\dotnet.exe" test "E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\project.json"  --no-build --base-build-path E:\git\mvc\artifacts\bin\ --configuration Debug --framework netcoreapp1.0

Fails with error : Deps file [E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.deps.json] specified but doesn't exist

Dotnet is supposed to look at E:\git\mvc\artifacts\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.deps.json

but instead it is looking in the wrong path.
E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.deps.json

## Expected  behavior
dotnet test passes

## Actual behavior

TRACE info
Launch host: C:\Program Files\dotnet\dotnet.exe app: C:\Program Files\dotnet\sdk\1.0.0-rc2-002439\dotnet.dll, argc: 9 args: test,E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\project.json,--no-build,--base-build-path,E:\git\mvc\artifacts\bin\,--configuration,Debug,--framework,netcoreapp1.0,
Tracing enabled
--- Invoked host main = {
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002439\corehost.exe
--runtimeconfig
E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.json
--depsfile
E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.deps.json
--additionalprobingpath
C:\Users\vramak\.nuget\packages
C:\Users\vramak\.nuget\packages\dotnet-test-xunit\1.0.0-rc2-151950-39\lib\netcoreapp1.0\dotnet-test-xunit.dll
E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.dll
--base-build-path
E:\git\mvc\artifacts\bin\
--configuration
Debug
--framework
netcoreapp1.0
}
Resolved fxr [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002439\hostfxr.dll]...
Loaded library from C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002439\hostfxr.dll
Tracing enabled
Own DLL path=[C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002439\corehost.dll]
Checking if CoreCLR path exists=[C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002439\coreclr.dll]
Detecting mode... CoreCLR present in own dir [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002439] and checking if [corehost.deps.json] file present=[0]
--- Executing in split/FX mode...
Parsed known arg --runtimeconfig = E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.json
Parsed known arg --depsfile = E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.deps.json
Parsed known arg --additionalprobingpath = C:\Users\vramak\.nuget\packages
App not in standalone mode, so expecting more arguments...
App C:\Users\vramak\.nuget\packages\dotnet-test-xunit\1.0.0-rc2-151950-39\lib\netcoreapp1.0\dotnet-test-xunit.dll runnable=[1]
Specified runtimeconfig.json from [E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.json]
Runtime config is cfg=E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.json dev=E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.dev.json
Attempting to read runtime config: E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.json
Attempting to read dev runtime config: E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.dev.json
Runtime config [E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.runtimeconfig.json] is valid=[1]
Deps file [E:\git\mvc\test\Microsoft.AspNetCore.Mvc.Abstractions.Test\bin\Debug\netcoreapp1.0\Microsoft.AspNetCore.Mvc.Abstractions.Test.deps.json] specified but doesn't exist

## Environment data
`dotnet --info` output:

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@vijayrkn is this blocking VS for RC2?

**Comment by vijayrkn** [comment]
Right now VS is passing the --no-build flag, so this is not a blocking issue at this point but we have a bug to remove the --no-build option passed to dotnet-test. If we decide to take that bug, then this will be blocking issue.

**Comment by brthor** [comment]
I am unable to repro this @vijayrkn

This is the command I'm executing against a test project:
`dotnet -v test .\project.json --no-build --build-base-path C:\hey\ --framework netcoreapp1.0 --configuration Debug`

One note is the correct option is `--build-base-path` was that just a typo above?

Are you able to provide a self-contained repro of this bug? Sharing a project.json/Program.cs or a repo with these included would be preferable.

**Comment by brthor** [comment]
okay, so when the assemblies are **not** present in `--build-base-path` I run into this error

Deps file [C:\hey\\test\EndToEnd\bin\Debug\netcoreapp1.0\EndToEnd.deps.json] specified but doesn't exist

This error is expected since the files aren't present but the error experience is not great. This seems like a fit n' finish issue.

**Comment by vijayrkn** [comment]
It was a typo. I was using --base-build-path instead of --build-base-path. I can't repro this issue with the correct argument. Will close this issue.

**Comment by brthor** [comment]
😄
