### ISSUE TITLE
dotnet init fails on Linux

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#262]
Repro steps:

1. Install the package on Ubuntu
2. mkdir start
3. cd start
4. dotnet init

Expected result: Program.cs and project.json are dropped in the directory.
Current result: A Win32Exception is thrown:
`Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)`

/cc  @krwq

**Comment by brthor** [comment]
@blackdwarf Can confirm, dotnet-init is not on the path and also is not in the package root folder.

@krwq Is dotnet init included in the build?

**Comment by brthor** [comment]
@krwq Dotnet Init should be added here

https://github.com/dotnet/cli/blob/master/scripts/build/build-stage.sh

and in the windows equivalent

**Comment by blackdwarf** [comment]
@brthor @krwq is the error above caused by dotnet-init not being among the bits? This is a very poor error for that. :)

**Comment by brthor** [comment]
@blackdwarf 
Yup, this is basically command not found. Agreed we should be catching this and outputting some error message that makes sense.

**Comment by brthor** [comment]
This is in the latest deb packages now. Closing this.
