### ISSUE TITLE
dotnet compile - no matching command

### ISSUE THREAD

**Issue by john-hidey** [dotnet/cli#2622]
## Steps to reproduce
```
dotnet compile --help  
```

## Expected  behavior
Output the command line options for `dotnet compile`

## Actual behavior
```
No executable found matching command "dotnet-compile"
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002457)

Product Information:
 Version:     1.0.0-rc2-002457
 Commit Sha:  d06418509d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by gitchomik** [comment]
Same problem on Ubuntu 14.04 x64

```
.NET Command Line Tools (1.0.0-dev-002317)

Product Information:
 Version:     1.0.0-dev-002317
 Commit Sha:  e4d7fa5bc4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

```


```
.NET Command Line Tools (1.0.0-rc2-002468)

Product Information:
 Version:     1.0.0-rc2-002468
 Commit Sha:  a2f3c531fb

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by eerhardt** [comment]
Use `dotnet build` instead.  We should remove `dotnet compile` from any documentation, it isn't a public facing command.

**Comment by piotrpMSFT** [comment]
correct. `dotnet compile` is no longer a public-facing command.

@blackdwarf a number of our .md files still reference dotnet-compile. Can you take a pass at cleaning these out?

**Comment by gitchomik** [comment]
@eerhardt : what about native compilation ? dotnet build doesn't support it

**Comment by eerhardt** [comment]
native compilation isn't an officially supported scenario yet. We plan on adding full support for it after RC2.

@schellap

**Comment by john-hidey** [comment]
Sorry @eerhardt, I mistakenly closed the issue without noticing you had assigned it to @blackdwarf

**Comment by blackdwarf** [comment]
@piotrpMSFT I believed I already did that...I cannot seem to find any reference to `dotnet compile` anymore. But will take another pass.

**Comment by ethanhann** [comment]
@blackdwarf [Markdown files that reference "dotnet compile" in this repo](https://github.com/dotnet/cli/search?l=markdown&q=%22dotnet+compile%22&type=Code&utf8=%E2%9C%93)
