### ISSUE TITLE
Create Breadcrumb Location when it is absent

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2623]
If the required .NET FX is not installed on a machine (e.g. clean Win7), then BreadCrumb location will not be present. This needs to be addressed for two scenarios:

1) Create it, if it does not exist, when installing the SharedFX Redist
2) Have a mechanism to create it when standalone apps are executed on a machine that does not contain SharedFX redist.

CC @leecow @schellap @mellinoe @ericstj @ellismg

**Comment by ellismg** [comment]
What is the exact location and and set of ACLs that should be put on the breadcrumb location?

**Comment by ericstj** [comment]
(programdata folder)Microsoft\NetFramework\BreadcrumbStore
sddl="D:(A;OICI;CCDCSWWPLORC;;;WD)(A;OICI;FA;;;BA)(A;OICI;FA;;;SY)"

**Comment by gkhanna79** [comment]
@leecow and I were chatting. It maybe a better idea to have this ACLed BredCrumb location creation (after the existence check) be in its own installer so that both the above scenarios can be addressed. This installer can be used by itself (e.g. for standalone apps) and chained by SharedFX Redist installer to create on machines where it does not exist (e.g. Win7). 

Thoughts?

A question that comes to mind is that once this location is created by the Breadcrumb installer, and later .NET FX is installed, will the latter setup keep the location intact? And if the .NET FX were to get uninstalled, will it still keep the location intact?

@ericstj Do you have insights into the above?

**Comment by schellap** [comment]
@gkhanna79 I was thinking about this and it may help alleviate your NET FX conflict concerns. Now that we have an opportunity to create one, can we create one for ourselves: `CoreBreadcrumbs` inside `NetFramework`?

> It maybe a better idea to have this ACLed BredCrumb location creation (after the existence check) be in its own installer so that both the above scenarios can be addressed. 

It is easier to say if you install `dotnet` you get servicing irrespective of what app you are, than say, go get this special installer to get servicing if you are a standalone app (i.e., it is not obvious to me that I have to get this installer if I am standalone only.)

**Comment by piotrpMSFT** [comment]
#2546

**Comment by piotrpMSFT** [comment]
#2662

**Comment by piotrpMSFT** [comment]
Fixed by #2662
