### ISSUE TITLE
[ProjectModel.Server] Error can not find project.json when there is a syntax error

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2625]
## Steps to reproduce

Repro:

Create a new ClassLibrary
Wait for restore and replace text in project.json with following:
{
"version": "1.0.0.0",

"dependencies": {
},

"frameworks": {
"frameworks": {
"netcoreapp1.0": {
"imports": [
"dotnet5.6",
"dnxcore50",
"portable-net45+win8"
]
}
}
}
}
## Expected  behavior

Error about some wrong syntax or missing target frameworks
## Actual behavior

Severity    Code    Description Project File    Line    Suppression State
Error       Unable to find project.json in 'c:\users\antonpis\documents\visual studio 2015\Projects\ClassLibrary17\src\ClassLibrary17'  ClassLibrary17      1   

which is definitely wrong
## Environment data

`dotnet --info` output:
C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002392)

Product Information:
 Version:     1.0.0-rc2-002392
 Commit Sha:  880dcf2fc8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

C:\Windows\system32>

**Comment by blackdwarf** [comment]
This issue is not applicable to the new csproj based tooling.
