### ISSUE TITLE
dotnet test - Test runner fails to run the tests correctly if there is a dependency on extenal folders 

### ISSUE THREAD

**Issue by vijayrkn** [dotnet/cli#2628]
## Steps to reproduce
1. Clone the aspnet/Mvc repo
2. .\build.ps1 --quiet initialize # to restore all packages
3. Open Mvc.sln in VS
4. Open the Test Explorer tab
5. Build Solution (F6)
6. Wait for test discovery to complete # surprisingly slow but that's not the bug here
7. Run a functional test that uses views e.g. AntiforgeryTests.Antiforgery_HeaderNotSet_SendsBadRequest (in Microsoft.AspNetCore.Mvc.FunctionalTests.AntiforgeryTests)

## Expected  behavior
When the test is executed with just >dotnet test from commandline it works fine. It errors out only in the design time mode. 

## Actual behavior
Observed: Test fails, unable to find the first .cshtml file it looks for.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

(copied from tfs bug : https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=208723)

**Comment by piotrpMSFT** [comment]
@vijayrkn what is the working directory in which VS spawns the test process? It needs to match the expected working directory.

**Comment by vijayrkn** [comment]
Currently the working directory returned in ProcessStartInfo message is null, so it is getting set the project json path. I tried setting it to outputPath, still I get the same error.

[VSTestAdapter]: Received ((, TestExecution.TestRunnerProcessStartInfo) -> {
  "FileName": "C:\\Program Files\\dotnet\\dotnet.exe",
  "Arguments": "exec --runtimeconfig E:\\git\\mvc\\artifacts\\bin\\test\\Microsoft.AspNetCore.Mvc.FunctionalTests\\bin\\Debug\\netcoreapp1.0\\Microsoft.AspNetCore.Mvc.FunctionalTests.runtimeconfig.json --depsfile E:\\git\\mvc\\artifacts\\bin\\test\\Microsoft.AspNetCore.Mvc.FunctionalTests\\bin\\Debug\\netcoreapp1.0\\Microsoft.AspNetCore.Mvc.FunctionalTests.deps.json --additionalprobingpath C:\\Users\\vramak\\.nuget\\packages C:\\Users\\vramak\\.nuget\\packages\\dotnet-test-xunit\\1.0.0-rc2-157751-46\\lib\\netcoreapp1.0\\dotnet-test-xunit.dll E:\\git\\mvc\\artifacts\\bin\\test\\Microsoft.AspNetCore.Mvc.FunctionalTests\\bin\\Debug\\netcoreapp1.0\\Microsoft.AspNetCore.Mvc.FunctionalTests.dll --designtime --port 5489 --wait-command"
})


This is the commandline invoked for running the test 

"C:\\Program Files\\dotnet\\dotnet.exe" "exec --runtimeconfig E:\\git\\mvc\\artifacts\\bin\\test\\Microsoft.AspNetCore.Mvc.FunctionalTests\\bin\\Debug\\netcoreapp1.0\\Microsoft.AspNetCore.Mvc.FunctionalTests.runtimeconfig.json --depsfile E:\\git\\mvc\\artifacts\\bin\\test\\Microsoft.AspNetCore.Mvc.FunctionalTests\\bin\\Debug\\netcoreapp1.0\\Microsoft.AspNetCore.Mvc.FunctionalTests.deps.json --additionalprobingpath C:\\Users\\vramak\\.nuget\\packages C:\\Users\\vramak\\.nuget\\packages\\dotnet-test-xunit\\1.0.0-rc2-157751-46\\lib\\netcoreapp1.0\\dotnet-test-xunit.dll E:\\git\\mvc\\artifacts\\bin\\test\\Microsoft.AspNetCore.Mvc.FunctionalTests\\bin\\Debug\\netcoreapp1.0\\Microsoft.AspNetCore.Mvc.FunctionalTests.dll

from commandline also I get the same error.

@pranavkm - how should this test be executed to get the Views folder?

**Comment by pranavkm** [comment]
The problem is that Mvc expects the application BasePath to be /test/Microsoft.AspNetCore.Mvc.FunctionalTests/bin/debug/netcoreapp1.0 but VS sets the base-output-path to /artifacts. We can fix this in Mvc's tests to look for the repo root and make our paths relative from there.

**Comment by vijayrkn** [comment]
Thanks @pranavkm 

@piotrpMSFT - Can we use this bug to fix the working directory returned in the TestRunnerProcessStartInfo message. 

[VSTestAdapter]: Received ((, TestExecution.TestRunnerProcessStartInfo) -> {
 "FileName": "C:\Program Files\dotnet\dotnet.exe",
 "Arguments": "exec --runtimeconfig ....

**Comment by livarcocc** [comment]
@vijayrkn You mean you want to have the working directory included in the TestRunnerProcessStartInfo message?

And how should we find it? Should it be the directory under which VS invoked dotnet test? The designtime one?

**Comment by vijayrkn** [comment]
I already have the project.json directory. We need the directory where the test dll is present and if you can pass it in the TestRunnerProcessStartInfo  message, I can use that as the working directory while starting the test runner process.

**Comment by livarcocc** [comment]
@vijayrkn Do we understand why it works from the command line but not from VS? I imagine from the command line, we run it from the folder containing the project.json, therefore, that folder becomes the working directory. I am curious because you mentioned that you are setting the working directory to the folder containing the project.json and still it doesn't work. Weird.

Having said that, it should be ok to sent this information in the message, I just want to make sure that it is the right thing and not a work around for a problem we don't fully comprehend. At least, I don't think I do, yet.

**Comment by vijayrkn** [comment]
The reason the tests are failing in VS because in the tests, it is assumed that the dll is present in the /bin folder and not /artifacts/bin folder (VS always writes output to the artifacts folder). To fix the test, they need to fix the path here - https://github.com/aspnet/Mvc/blob/1f93977729f9998c3971567268e025ef4ae76ed6/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs

@pranavkm told that he will fix the tests.

Passing the working directory in the message won't fix this specific issue. As you mentioned, it seems right to leave the behavior as is because dotnet test uses the project.json path as working directory and we should have the same behavior for design time too.. We can close this issue.

**Comment by livarcocc** [comment]
Closed per comment.
