### ISSUE TITLE
Support Protobuild packages in the "dependencies" section

### ISSUE THREAD

**Issue by hach-que** [dotnet/cli#2629]
I'm the developer of [Protobuild](https://github.com/Protobuild/Protobuild), a cross-platform project generator and package management system for C#.  It focuses on platforms ("windows"/"mac"/"linux"/etc) instead of frameworks ("net40"/"net45"/etc) which allows code to be written that references native APIs without expensive runtime checks.  Protobuild is used by projects such as MonoGame.

I want to make sure that as .NET moves towards `project.json` files that this system can still work.  One aspect of this is allowing developers to depend on Protobuild packages through the "dependencies" section.

I'd go ahead and submit a PR myself, but I think there's a discussion on how to approach the resolution of packages in the "dependencies" section when there's multiple package managers - how does the system know which package management system should handle which package, or should the CLI just query both systems in an attempt to resolve the package (and what happens then if both packaging systems have a package with the same name).

One difference is the versioning; while NuGet uses `X.X.X.X` format, Protobuild tracks Git commit hashes and branches.  This feature also means that Protobuild supports "swap to source" and "swap to binary" workflows, where developers can with one command replace a package in it's binary format with the source code of that package, with all of the referencing handled automatically.  So we could use the difference in versioning formats to distinguish what the package management system is, but this doesn't help other package providers in the future if their versioning systems are similar.

Thoughts?

**Comment by piotrpMSFT** [comment]
@blackdwarf @yishaigalatzer can you guys share some thoughts on this?

**Comment by yishaigalatzer** [comment]
My initial thought is that it doesn't belong here under dependencies

**Comment by hach-que** [comment]
What section would you suggest is appropriate?  The packages are dependencies of the software, and I think it would feel odd or confusing to list it under another similar named section like "dependsOn" or "platformDependencies" or "platformPackages" etc.

**Comment by yishaigalatzer** [comment]
I'm saying it doesn't belong in the lock file or nuget.

**Comment by hach-que** [comment]
No, I don't think it does belong in NuGet - it's not NuGet, and it has a different set of features available to developers than NuGet does.

I'm not necessarily talking about the lock file here, my interest is in `project.json` and allowing people to reference Protobuild packages in the dependencies section of this file.

**Comment by yishaigalatzer** [comment]
I figured that 5 seconds after I replied, :). I would suggest to hold on to that thought for a little while longer while we lock down the rc2 release and revisit when in a few weeks.

**Comment by hach-que** [comment]
Fair enough :)

**Comment by hach-que** [comment]
So now that RC2 is out, can we revisit this?

**Comment by yishaigalatzer** [comment]
This is going to completely change, we are moving away from project.json to msbuild for dependencies, so at point you need your own entries in msbuild and your own tool chain through something like an msbuild task.

We are just starting the design, so not much to talk about but in general whatever you have that works for msbuild should work with minor changes.

**Comment by hach-que** [comment]
Oh okay.

In Protobuild, we actually generate the MSBuild projects that are then used in IDEs / build tools.  The package resolution occurs before MSBuild or xbuild ever gets invoked.  The goal of this task was that because the .NET Core tools were using `project.json` and not MSBuild, we wanted to ensure that package dependencies could be resolved correctly when .NET Core projects were built.

We generate the MSBuild projects because the format of them varies wildly between different target platforms (iOS / Android vs desktop vs JSIL vs old platforms, etc).

However, if MSBuild is now being used as the underlying project format, it looks like I'll just need to update the XSLTs to target the new project structure and everything else can continue as normal.
