### ISSUE TITLE
MSI: Change branding to Microsoft .NET Core SDK

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2633]
## Steps to reproduce
run MSI

## Expected  behavior
ARP/Installer name is Microsoft .NET Core SDK

## Actual behavior
ARP/Installer name is Microsoft .NET CLI for Windows

## Environment data
`dotnet --info` output:

**Comment by Eilon** [comment]
Can we also fix the product name shown in the MSI:
![msi-title](https://cloud.githubusercontent.com/assets/202643/14837097/70335aa8-0bca-11e6-8d13-22dcf71a661a.png)

Note that it says `Microsoft .Net CLI for Windows` (`.Net` is Pascal Case, but should be `.NET` upper case).

**Comment by robmen** [comment]
See #2400. When the open questions are answered, I think that will resolve most of these issues.

**Comment by Sridhar-MS** [comment]
Fixed by #2704
