### ISSUE TITLE
Remove IsPackageBased helper method

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#2635]
Once this goes in and we get it https://github.com/NuGet/NuGet.Client/pull/529

/cc @emgarten

**Comment by anurse** [comment]
The change has gone in. Is there a NuGet build we can take for this? /cc @eerhardt @emgarten

**Comment by piotrpMSFT** [comment]
ping. When do we anticipate getting this fix from NuGet to CLI? @emgarten

**Comment by emgarten** [comment]
I see this bug is marked for RC2, we could integrate the new nuget packages with just this fix.  /cc @rrelyea

**Comment by Petermarcu** [comment]
@rrelyea , @emgarten , Can we get this and the update to you using the latest CoreFX build in today?

**Comment by emgarten** [comment]
@Petermarcu sure, I'll get a new set of packages with those changes

**Comment by emgarten** [comment]
The NuGet change is in, the workaround can be removed.
