### ISSUE TITLE
dotnet publish command throwing error on publishing net451 framework based application

### ISSUE THREAD

**Issue by ibrmohammed** [dotnet/cli#2637]
dotnet publish --configuration Release --runtime win81-x64

![image](https://cloud.githubusercontent.com/assets/5870046/14734666/9f963eee-0889-11e6-9bfc-2ac6420b42bd.png)

Project.json
"frameworks": {
    "net451": { }
  }
## Environment data

`dotnet --info

![image](https://cloud.githubusercontent.com/assets/5870046/14734714/eff0c968-0889-11e6-9359-af840dce9f1e.png)

**Comment by davidfowl** [comment]
@ibrmohammed 2 questions:
1. Is that your full project.json?
2. Can you try the latest version?

**Comment by ibrmohammed** [comment]
My Project.json

{
  "userSecretsId": "aspnet5-Idp-149e9283-fb72-416b-bf12-4bc1df27d486",
  "version": "1.0.0-*",
  "description": "Aps.Idp.Web Project",
  "authors": [ "IPPCS" ],
  "commands": {
    "web": "Aps.Idp.Web",
    "ef": "EntityFrameworkCore.Commands"
  },
  "content": [
    "wwwroot"
  ],
  "compilationOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "dependencies": {
    "Aps.Idp": "1.0.0-*",
    "Aps.Idp.Repository": "1.0.0-*",
    "Aps.Idp.Repository.EF": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-*",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-*",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*"
  },
  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "frameworks": {
    "net451": { }
  },
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
  }
}

**Comment by piotrpMSFT** [comment]
This project.json looks like is copied from a DNX solution. You'll need to port this to CLI. We'll take a look at the error message for RTM.

**Comment by piotrpMSFT** [comment]
This is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
