### ISSUE TITLE
Potential hidden bugs due to file system case sensitivity and test ToLower normalization

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#2646]
Test assets are normalizer to lower case: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.TestFramework/Microsoft.DotNet.TestFramework.TestInstance.cs
There might be other parts in the testing framework depending on this normalization too.

This might hide case sensitivity bugs on case sensitive file systems.

**Comment by livarcocc** [comment]
I believe we are no longer doing this. At least I couldn't spot it.
