### ISSUE TITLE
dotnet restore filename.json fails if the file name is not explicitly project.json

### ISSUE THREAD

**Issue by javiercn** [dotnet/cli#2647]
## Steps to reproduce
1) Create a project.json file, name it project.something.json
2) Run dotnet restore project.something.json (other args)

## Expected  behavior
dotnet restore restores the packages in project.something.json into the target folder using the given sources in (other args)

I expect that if I explicitly give the tool the file with the packages, it trusts my input instead of throwing just because the file is not named project.json, that should be a default when no file is specified (not a requirement) in the same way that when no path at all is specified, it looks in the current directory.

## Actual behavior
error: Invalid input 'C:\work\Tests\netcoreapp\split\ship\project.noimports.json'. The file type was not recognized.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002439)

Product Information:
 Version:     1.0.0-rc2-002439
 Commit Sha:  ef0c3b2cee

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
This is by-design in CLI. Since NuGet provides the restore capability, you could propose the idea of restoring something other than project.json in https://github.com/nuget/home.
