### ISSUE TITLE
dotnet restore usage issues

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#2652]
## Steps to reproduce

dotnet restore --help
## Actual behavior
1. The usage line says:

Usage: nuget3 restore [arguments] [options]

(a) it should say "dotnet", not "nuget3".
(b) The "--verbosity" line should state which the default verbosity level is. It should also state that the levels are in order of increasing information (if that is true).
(c) Consistency: some help lines end with periods, some don't.
(d) Ordering: it seems like the options are in a random order. They are not alphabetically sorted, for instance.
(e) More consistency: <FEED> is capitalized, but other arguments are not.
(f) grammar: why shouldn't <packagesDirectory> be <packages directory>?
(g) More consistency: in most cases, multiple words are separated by "-", but that's not true for `--configfile`. Shouldn't it be `--config-file`? Same for `--fallbacksource` => `--fallback-source`.
(h) bad grammar: "--ignore-failed-sources         Only warning failed sources if there are packages meeting version requirement". Maybe "--ignore-failed-sources         Only warn on failed sources if there are packages meeting a version requirement"? That still doesn't make sense to me, but the grammar is better.
(i) minor: why so many newlines before the "Usage" line?
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002476)

Product Information:
 Version:     1.0.0-rc2-002476
 Commit Sha:  1a8d393b9b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by 18583690825** [comment]
I remind there was a command like `dotnet restore -xx 23811`, it used to replace the asterisk into specified version number. But i cannot find the information of how to use it or what the argument is.Does this command exists?
