### ISSUE TITLE
dotnet build usage issues

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#2656]
## Steps to reproduce

dotnet build --help
## Actual behavior

There are several issues with the help text:
1. The title is ".NET Builder". That seems unnecessarily concise. How about ".NET Command Line Build Tool".
2. The "Arguments" says:

```
  <PROJECT>  The project to compile, defaults to the current directory. Can be one or multiple paths to project.json, project directory or globbing patter that matches project.json files
```

There is poor grammar, no line breaking, and a typo ("patter" => "pattern"). "globbing patter" is jargon that should probably read "wildcard pattern". Also, `<PROJECT>` is singular, but apparently you can pass multiple projects.
3. The options seem to appear in no order; they certainly are not alphabetized.
4. Why are all the option arguments SHOUTING AT ME (in ALL CAPS)?
5. There is inconsistency between this and "dotnet restore --help", which doesn't capitalize arguments (mostly), and adds periods at the end of every option.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002476)

Product Information:
 Version:     1.0.0-rc2-002476
 Commit Sha:  1a8d393b9b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by livarcocc** [comment]
Most of the issues here have been addressed. I believe the only ones missing are the line break in the description and the title for the verb.

We are having a conversation about fixing these descriptions. So, closing this one.
