### ISSUE TITLE
CLI repo build partial failures on Ubuntu

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#266]
Attempting to build CLI repo on Ubuntu results in the following failures towards the end of the build:

/home/gkhanna/Github/gkhanna79/cli/package_tool/package_tool: line 45: debuild: command not found
*** Testing debian package ***
fatal: destination path '/tmp/bats' already exists and is not an empty directory.
/tmp/bats ~/Github/gkhanna79/cli
mkdir: cannot create directory ‘/usr/local/libexec’: Permission denied
mkdir: cannot create directory ‘/usr/local/share/man/man1’: Permission denied
mkdir: cannot create directory ‘/usr/local/share/man/man7’: Permission denied
~/Github/gkhanna79/cli
/home/gkhanna/Github/gkhanna79/cli/scripts/package/package-debian.sh: line 76: bats: command not found
*** Publishing package ***

**Comment by brthor** [comment]
This is the debian package build failing. This needs to be run as root to succeed, or inside a docker container.

It will not affect the build of your actual bits, you just won't get a debian package as a part of it.

**Comment by gkhanna79** [comment]
We should detect this and making it a warning/message as opposed to have failures displayed like this.

**Comment by brthor** [comment]
Add prereq check for debian package build dependencies.

**Comment by brthor** [comment]
#832 is tracking the work here. Closing this one out.
