### ISSUE TITLE
Terrible error message: "Invalid .deps file"

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#2664]
## Steps to reproduce

Hard to know what details to give. Probably, on Windows 8.1:

1. git clone https://github.com/russellhadley/mcgdiff
2. cd mcgdiff
3. build.cmd -p -f
4. bin\mcgdiff\mcgdiff.exe
5. get: "Invalid .deps file"

unless Russell fixes the project.json, or something else, and makes this repo not reproduce the problem.

This is an app built/published with "dotnet publish". I presume there's some dependency problem, but I don't know how to debug it, especially from this error message.

## Expected  behavior

no error

## Actual behavior

"Invalid .deps file"

General comment:

**This is an absolutely terrible and useless error message.** Which ".deps" file is it referring to? Why is it invalid? What can I do to make it valid?

I notice there are several other cases in the dotnet/cli issue list referring to this error, and in all cases people were complaining about how useless it was and how difficult it was to determine what the actual problem was.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002476)

Product Information:
 Version:     1.0.0-rc2-002476
 Commit Sha:  1a8d393b9b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by piotrpMSFT** [comment]
@schellap can you take a look at this? Can we make the message a bit more verbose? Perhaps: `Failed to launch <path to app>: <path to deps> is invalid` ?

**Comment by schellap** [comment]
@BruceForstall hi!

I tried the steps but I couldn't repro. I got this:

```
g:\mcgdiff>bin\mcgdiff\mcgdiff.exe
error: Specify --base and/or --diff.
```

1. Could you please zip up your repo (as is on your machine) and the dotnet root folder (with the FX) and share these zips?
2. Rename dotnet.exe relative `shared\Microsoft.NETCore.App\1.0.0-rc2-23931` folder to `foo`
3. Next, can you target "Microsoft.NETCore.App": "1.0.0-rc2-002476" in your project.json and see if this goes away?

@piotrpMSFT The places where we mark deps as invalid we emit an error message. I'll add the paths to the error message. This looks like some corruption (`1.0.0-rc2-23931` seems suspect which has the non-compatible interface in `hostpolicy.dll` for the newer `hostfxr.dll`)

**Comment by russellhadley** [comment]
I've been developing these tools (mcgdiff + etc.) and I've updated to a new CLI and I'm getting the same error.  I've been looking around trying to find the .deps file to noodle out what's going wrong but no luck as of yet.  Should I update the version numbers of the dependencies?  Is there a workaround?

**Comment by schellap** [comment]
@russellhadley can you target the latest netcore.app?

> Can you target "Microsoft.NETCore.App": "1.0.0-rc2-002476" in your project.json and see if this goes away?

Here:
https://github.com/russellhadley/mcgutils/blob/master/src/mcgdiff/project.json#L8

Also, I would like your app folder zipped up and attached to this issue to investigate.

**Comment by schellap** [comment]
The Microsoft.NETCore.App version is: `1.0.0-rc2-3002476` with `30`

**Comment by schellap** [comment]
If you are trying this right now, the one on the feed is: `1.0.0-rc2-3002471`.

The `1.0.0-rc2-3002476` hasn't made its way to the feed yet.

**Comment by russellhadley** [comment]
Updating worked for me.  I seem to be unblocked.

**Comment by BruceForstall** [comment]
@piotrpMSFT your suggested error message, `Failed to launch <path to app>: <path to deps> is invalid`, is better, but insufficient. The next, and very important, question, is _why_ is it invalid?

**Comment by BruceForstall** [comment]
@schellap are you trying to repro with the same version of dotnet as me?

**Comment by BruceForstall** [comment]
@schellap I sent you zip files privately. Let me know if you need more.

**Comment by schellap** [comment]
@BruceForstall, the parser prints the error messages when it encounters errors and then a check for validity of the parsing result produces this message. This looks like some garbage value printing the secon d message without the first message, so it is confusing. The garbage is due to an interface break that exists between 1.0.0-rc2-23931 and the later hostfxr.dll. From CLI and netcore.app 2349, we made the versions to be backward compatibe.

**Comment by davidfowl** [comment]
@schellap so the claim is this error message will never happen again?

**Comment by piotrpMSFT** [comment]
@schellap is saying there are multiple issues involved and that one of them has been fixed.

**Comment by piotrpMSFT** [comment]
@schellap did you send approval mail?

**Comment by schellap** [comment]
Closing...
