### ISSUE TITLE
What C# support is there going to be when adding custom commands to "dotnet"

### ISSUE THREAD

**Issue by jchannon** [dotnet/cli#2666]
## Steps to reproduce
Create a executable script as highlighted here https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/intro-to-cli.md but with csharp code `Console.WriteLine("Hello");`

## Expected  behavior
When executing `dotnet hello` I expect to see output in the terminal

## Actual behavior
Command is executed but no output

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002339)

Product Information:
 Version:     1.0.0-rc2-002339
 Commit Sha:  2be5e84f87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by piotrpMSFT** [comment]
@jchannon can you share your repro?

**Comment by jchannon** [comment]
OK got a bit further, using `chmod +x` lowercase seemed to change it to executable however when executed the output is now:

```
/usr/local/share/dotnet/dotnet-helloworld: line 2: syntax error near unexpected token `"hello world"'
/usr/local/share/dotnet/dotnet-helloworld: line 2: `Console.WriteLine("hello world");'
```

**Comment by piotrpMSFT** [comment]
This example is mixing models a bit. If you want for `dotnet-helloworld` to be a script then it is just that... a script. `dotnet` will simply shell-execute it. Since bash doesn't understand C# the example is failing. To use a script, simply remove the C#-ism and replace it with a bash equivalent e.g. `echo Hello World`.

**Comment by jchannon** [comment]
Understood but my initial question was is there going to be c# support?

For example have a tool "dotnet fixusings" which using roslyn loops over
source files and removes and sorts using statements.

**Comment by piotrpMSFT** [comment]
Yes absolutely. I think the script example may be a bit misleading. If your tool is a console application whose name starts with 'dotnet-' then it will work like the script. You can even 'dotnet-pack' that application and reference it from the 'tools'section of project.json to use it from other projects. It will get downloaded and installed by 'dotnet restore'!
