### ISSUE TITLE
Cannot set CPU type (X64 or X86) when publishing an app in Windows

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#2668]
I guess we cannot install X64 and X86 tools on the same machine. So this seems a bug.

**Comment by piotrpMSFT** [comment]
What is blocking this installation for you, @xatabhk ?

**Comment by xatabhk** [comment]
@piotrpMSFT I have not tried to install both on the same machine. As I was wondering which dotnet.exe to be started by system if both installed.

**Comment by peter172sp** [comment]
You can install both x64 and x96 dotnet core SDKs, but only the first one in your path is used.
see https://github.com/dotnet/cli/issues/3091, https://github.com/dotnet/cli/issues/2343 and https://github.com/aspnet/Home/issues/1624.

**Comment by piotrpMSFT** [comment]
Since installig both is supported already, closing this issue.
