### ISSUE TITLE
dotnet cli and vscode task arguments funny business

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/cli#2671]
## Steps to reproduce
Create more advanced build task in vscode:

````json
{
	// See http://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "0.1.0",
	"command": "dotnet",
	"isShellCommand": true,
	"args": [],
	"suppressTaskName": true,
	"tasks": [
		{
			"taskName": "Build (Debug)",
			"args": ["build", "src/MyProject/project.json", "--configuration Debug"],
			"showOutput": "always",
			"echoCommand": true,
			"problemMatcher": "$msCompile"
		}
	]
}
````

## Expected  behavior
It works.

## Actual behavior
````
Specify --help for a list of available options and commands.
Unrecognized option '--configuration Debug'
````

This also happens with ``-c Debug``.
What doesn't work at all also was concatenating all the args into one big string ``"build src/MyProject/project.json --configuration Debug"``.
And the error coming with it:
````
No executable found matching command "dotnet-build src/MyProject/project.json --configuration Debug"
````
So vscode does insert all the args some way other than concatenating it with the command and running it in a shell.
Does vscode use some special way of inserting the commandline args?
At least dotnet cli does not handle this well then.
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002485)

Product Information:
 Version:     1.0.0-rc2-002485
 Commit Sha:  d3c65aee87

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by 717009629** [comment]
"--configuration" , " Debug"  ,  it can work

**Comment by piotrpMSFT** [comment]
This should fix the issue. Please reopen if that's not the case!
