### ISSUE TITLE
Trim application deps file for dependencies already in shared framework

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#2672]
Today we trim the output for things that already exist in the shared framework. We could do the same thing with the deps file and it would reduce the size and complexity of it for most applications.

/cc @anurse @schellap @pakrym

**Comment by schellap** [comment]
We are doing this already for assets. Are you suggesting for libraries and dependencies? Even then this suggestion should speed up parsing times.

**Comment by davidfowl** [comment]
@schellap Right, it's going to be beautiful 😄 and the deps files for most applications will be tiny.

**Comment by pakrym** [comment]
@davidfowl what are we doing with `preserveCompilationContext`? We would need to have libraries to put 'compile' section into.

**Comment by schellap** [comment]
Thank you for resolving and getting this in short notice.
