### ISSUE TITLE
dotnet restore after 100000ms return for all request error message 'has timed out after 100000ms'

### ISSUE THREAD

**Issue by Gormy** [dotnet/cli#2674]
## Steps to reproduce
Windows Server 2012 x64
I have solution with 4 projects. When I try run 'dotnet restore' from TeamCity runner, don`t load all packages,

## Expected  behavior
Load all packages from nuget

## Actual behavior
Load packages only in first 100 seconds.

## Environment data
`dotnet restore` output:
before 10000ms:
...
[repo-initialize] info :   OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.fileproviders.embedded/1.0.0-rc1-final/microsoft.aspnet.fileproviders.embedded.1.0.0-rc1-final.nupkg 93953ms
[repo-initialize] info :   OK https://api.nuget.org/v3-flatcontainer/system.console/index.json 95377ms
[repo-initialize] info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.fileproviders.abstractions/index.json
[repo-initialize] info :   GET https://api.nuget.org/v3-flatcontainer/system.reflection/4.0.10/system.reflection.4.0.10.nupkg
[repo-initialize] info :   GET https://api.nuget.org/v3-flatcontainer/system.console/4.0.0-beta-23516/system.console.4.0.0-beta-23516.nupkg
[repo-initialize] info :   OK https://api.nuget.org/v3-flatcontainer/entityframework.relational.design/index.json 97882ms
[repo-initialize] info :   GET https://api.nuget.org/v3-flatcontainer/entityframework.relational.design/7.0.0-rc1-final/entityframework.relational.design.7.0.0-rc1-final.nupkg
...

after 100000ms

...
[repo-initialize] info : An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.linq.queryable/index.json';. The request will now be retried.
[repo-initialize] info : The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.linq.queryable/index.json'; has timed out after 100000ms.
...

**Comment by piotrpMSFT** [comment]
This is a NuGet issue. Can you please re-open this bug in https://github.com/nuget/home?

/cc @yishaigalatzer @emgarten

**Comment by joelverhagen** [comment]
Moved to https://github.com/NuGet/Home/issues/2657.
