### ISSUE TITLE
Restore fails for the default project created by dotnet new

### ISSUE THREAD

**Issue by atanasa** [dotnet/cli#2675]
## Steps to reproduce

dotnet new
dotnet restore

## Expected  behavior

Restore without errors.

## Actual behavior

error: Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002485)' for **'.NETCoreApp,Version=v1.0'.**

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002485)

Product Information:
 Version:     1.0.0-rc2-002485
 Commit Sha:  d3c65aee87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

Maybe have a CI test for the basic workflow of new -> restore -> build? These steps are listed as "Getting started" on the .Net Core site. Considering the lack of communication for breaking changes and scarce documentation, I'm using it as a way to discover the latest "the way to create a basic app on .net core".

Also improve the message if possible - add info on what are the supported frameworks for that package.

**Comment by atanasa** [comment]
Seems like `dotnet new` does not create a NuGet.Config file anymore and this is causing the error. Is this intentional?

**Comment by GuardRex** [comment]
Dup https://github.com/dotnet/cli/issues/2545

**Comment by piotrpMSFT** [comment]
Closed as dup.
