### ISSUE TITLE
Files in Use dialog showed a process that did not exist "A"

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2678]
## Steps to reproduce
Install .NET CLI tools
With, apparently, a process holding a file in use (I really am not sure which).

## Expected  behavior
The Files In Use dialog show the full process name

## Actual behavior
The Files In Use dialog shows only the first letter (Unicode vs Ascii issue?)

## Environment data
`dotnet --info` output:

![dialog](https://cloud.githubusercontent.com/assets/9561583/14789993/11549a62-0ac4-11e6-9a0f-5bac1181e6d7.png)

**Comment by Sridhar-MS** [comment]
I am seeing the `FilesInUse` page hardcoding `A` - https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/clisdk/bundle.thm#L50

@robmen Any idea on how to display the process list which are using the files?

**Comment by Sridhar-MS** [comment]
I am also seeing the `ShowFilesInUse` getting set correctly here - https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/windows/clisdk/bundle.wxs#L17

**Comment by Sridhar-MS** [comment]
Fixed by #2764
