### ISSUE TITLE
ASP.NET 5 RC vs. planned RC2

### ISSUE THREAD

**Issue by rh78** [dotnet/cli#2686]
At our company some time ago we started a new project, and we chose ASP.NET 5 RC as our way to go as we liked the idea of a new, slimmed down version of ASP.NET very much. Given that it was a RC version, we did not expect major changes to the implementation so it seemed to be a good bet, given that the release of our solution would be quite some time in the future, and it would be very likely that ASP.NET 5 would release during that time.

We're using DNX 4.5.1 and we're hosting the site in IIS. Some 3rd party component of our application also uses Entity Framework 6 which is working great.

Now some time ago you announced a change from DNX to CLI. What does this actually mean to our project? 

a) Will we still be able to use the code or will it change completely? 
b) Will we still be able to use the project in IIS or not?
c) Will there be an issue with the 3rd party component which is dependent on the non-Core Entity Framework? Or will there be a conflict (package renames, class conflicts etc.)?
d) Will it still be possible to run our solution in DNX vs. the CLI approach?

Thanks for your help!

**Comment by GuardRex** [comment]
> a) Will we still be able to use the code or will it change completely? 

It won't completely change, but there are many deltas for RC2. You can get a rundown of the main changes by looking at the [RC2 milestones in Annoucements](https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2)

> b) Will we still be able to use the project in IIS or not?

Of course! There are hosting changes for an app headed to RC2, and you will use a new module with IIS called the `AspNetCoreModule` ("ANCM"), which is a port of the `HttpPlatformHandler`. It's a special flavor of HPH with features needed by ASP.NET Core apps. See: https://github.com/aspnet/Announcements/issues/164 Yes, you can run RC1 apps with HPH side-by-side with RC2 apps with ANCM. You don't need to convert every app you have from RC1 to RC2 simultaneously.

> c) Will there be an issue with the 3rd party component which is dependent on the non-Core Entity Framework? Or will there be a conflict (package renames, class conflicts etc.)?

I doubt that if you're moving the app from full framework under RC1 to full framework under RC2 that you'll have any major problems. However, you'll probably need to take the plunge to find out.

> d) Will it still be possible to run our solution in DNX vs. the CLI approach?

Even if that is possible (and I don't see why it wouldn't be possible), RC1 will be technically "depreciated" when RC2 releases (AFAIK; matches the MS pattern for preview releases); therefore, RC1 apps will be technically "unsupported" by MS (AFAIK, but they need to tell you that for sure); however, I'm certain no one around here would leave you hanging while you're making a move to RC2. What would happen down the road (RTM-time) is that if you were to ask about an RC1 app at RTM, then you'd probably get the cold shoulder.

**Comment by piotrpMSFT** [comment]
@blackdwarf @glennc it looks like we need docs describing how folks should transition from RC

**Comment by blackdwarf** [comment]
@piotrpMSFT this is already in the works. @danroth27 is in charge of the ASP.NET Core migration documentation.

**Comment by danroth27** [comment]
Yes, we will have porting docs for both DNX -> .NET Core and ASP.NET 5 RC1 to ASP.NET Core RC2. They are in the works here:
                https://github.com/aspnet/Docs/pull/1161
                https://github.com/dotnet/core-docs/pull/391/files#diff-b76e7e5efd65cec0d968e260eb08ea41

**Comment by danroth27** [comment]
> a) Will we still be able to use the code or will it change completely? 

Most of your code will be unchanged. The biggest changes are: 
- Package IDs and namespaces have been updated to reflect the new ASP.NET Core branding
- DNX has been replaced with the new .NET Core CLI with various updates to the project model
- ASP.NET Core apps are now just a console app, so you need a Main entry point that wires up ASP.NET Core hosting
- Other changes are listed in our [RC2 announcements](https://github.com/aspnet/announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-rc2).

> b) Will we still be able to use the project in IIS or not?

Absolutely, via the new [ASP.NET Core Module](https://github.com/aspnet/Announcements/issues/164)

> c) Will there be an issue with the 3rd party component which is dependent on the non-Core Entity Framework? Or will there be a conflict (package renames, class conflicts etc.)?

You can keep compatibility with EF6 components by running your ASP.NET Core app on the full .NET Framework. @rowanmiller.

> d) Will it still be possible to run our solution in DNX vs. the CLI approach?

You will need to migrate off of DNX and onto the new .NET Core CLI.

**Comment by rh78** [comment]
Hi thanks for this quick and extensive feedback! Now I have a better feeling :-) Just suggesting: you should write a blog article about that. Users that are thinking about using ASP.NET Core or who are using RC1 are very likely asking the same questions as I am - and are probably afraid and because of this not using the new versions...

PS: so it is still possible to run ASP.NET 1.0 Core RC2 on the full .NET framework?

**Comment by danroth27** [comment]
Yes, you will be able to run ASP.NET Core RC2 on both .NET Core and on the full .NET Framework.

**Comment by blackdwarf** [comment]
This is now complete as there are docs on migration from DNX to the CLI on https://docs.microsoft.com/en-us/dotnet/articles/core/migrating-from-dnx.
