### ISSUE TITLE
Changing --version-suffix should trigger a new build

### ISSUE THREAD

**Issue by mcliment** [dotnet/cli#2687]
## Steps to reproduce

* Having a `project.json` with `"version": "1.0.0-*"`.
* Run `dotnet build --version-suffix 1`
* Run `dotnet build --version-suffix 2`

## Expected  behavior

To build twice and have a `.dll` with version 1.0.0-2

## Actual behavior

The build is not triggered and the message `Project MyProject (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.` is shown. The generated `.dll` version is 1.0.0-1.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc2-002426)

Product Information:
 Version:     1.0.0-rc2-002426
 Commit Sha:  08ee6dedd9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@mcliment where are you seeing a side-effect of passing --version-suffix to dotnet build? The bug seems to be that build accepts a --version-suffix option without actually using it. Can you confirm?

**Comment by piotrpMSFT** [comment]
Aha, I see `--version-suffix` got added as part of recent perf improvements. @anurse can you pick this up, then?

**Comment by anurse** [comment]
It's not related to the perf changes, this bug would have existed since incremental compilation was added. The command line used to build is not considered as part of the incremental inputs. Changing that is not going to be trivial, but I can try to look at it for RC2.
