### ISSUE TITLE
Build of CLI Repo Fails Looking for hostpolicy.dll from Invalid Location

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2688]
## Steps to reproduce
1. Clone the repo.
2. Make some changes and commit them.
3. Wait for more changes to be committed and build in the main repo (to increase the commit count).
4. Build your changes.

## Expected  behavior
Build succeeds.

## Actual behavior
Build fails because it can't find host policy DLL.

[TARGET     <] [ OK ] [00:04:13.045] CompileStage1                                         (Microsoft.DotNet.Cli.Build.CompileTargets.CompileStage1)
[TARGET     >] [....] [00:04:13.045] CompileStage2                                         (Microsoft.DotNet.Cli.Build.CompileTargets.CompileStage2)
Skipping completed target: Init
[EXEC       >] [....] [00:04:13.139] C:\src\cli\artifacts\win10-x64\stage1\dotnet.exe "restore" "--verbosity" "verbose" "--disable-parallel" "--infer-runtimes" "--fallbacksource" "C:\src\cli\artifacts\win10-x64\corehost"
Expected to load hostpolicy.dll from [C:\src\cli\artifacts\win10-x64\stage1\shared\Microsoft.NETCore.App\1.0.0-rc2-3002496]
This may be because the targeted framework ["Microsoft.NETCore.App": "1.0.0-rc2-3002496"] was not found.
[EXEC       <] [FAIL] [00:04:13.483] C:\src\cli\artifacts\win10-x64\stage1\dotnet.exe "restore" "--verbosity" "verbose" "--disable-parallel" "--infer-runtimes" "--fallbacksource" "C:\src\cli\artifacts\win10-x64\corehost" exited with -2147450749
[TARGET     <] [FAIL] [00:04:13.498] CompileStage2                                         (Microsoft.DotNet.Cli.Build.CompileTargets.CompileStage2)
[TARGET     <] [FAIL] [00:04:13.498] Compile                                               (Microsoft.DotNet.Cli.Build.CompileTargets.Compile)
[TARGET     <] [FAIL] [00:04:13.514] Default                                               (Standard Goals)
Build failed: Microsoft.DotNet.Cli.Build.Framework.BuildFailureException: Command failed with exit code -2147450749: C:\src\cli\artifacts\win10-x64\stage1\dotnet.exe "restore" "--verbosity" "verbose" "--disable-parallel" "--infer-runtimes" "--fallbacksource" "C:\src\cli\artifacts\win10-x64\corehost"
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in C:\src\cli\scripts\Microsoft.DotNet.Cli.Build.Framework\CommandResult.cs:line 48
   at Microsoft.DotNet.Cli.Build.CompileTargets.PublishSharedFramework(BuildTargetContext c, String outputDir, DotNetCli dotnetCli) in C:\src\cli\scripts\dotnet-cli-build\CompileTargets.cs:line 459
   at Microsoft.DotNet.Cli.Build.CompileTargets.CompileStage2(BuildTargetContext c) in C:\src\cli\scripts\dotnet-cli-build\CompileTargets.cs:line 321
   at Microsoft.DotNet.Cli.Build.Framework.BuildContext.ExecTarget(BuildTarget target) in C:\src\cli\scripts\Microsoft.DotNet.Cli.Build.Framework\BuildContext.cs:line 144
Build failed
At C:\src\cli\scripts\run-build.ps1:86 char:27
+ if($LASTEXITCODE -ne 0) { throw "Build failed" }
+                           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed

**Comment by brianrob** [comment]
cc: @Sridhar-MS

**Comment by brthor** [comment]
Instance of https://github.com/dotnet/cli/issues/2405?

**Comment by Sridhar-MS** [comment]
yes.. It is indeed. Closing it
