### ISSUE TITLE
Win10bash: "Could not load host policy library" error when trying to run C# app

### ISSUE THREAD

**Issue by karlti** [dotnet/cli#2689]
Env: Win10 Build 14328, "Bash on Ubuntu on Windows" subsystem.

## Steps to reproduce
- setup `'dotnet-dev-Ubuntu-x64.1.0.0-beta-002071'`
- create new default dotnet C# app
- build the app

try to run it, either via "dotnet test.dll" or with absolute path

my project.json is:

project.json:
-------------

`{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
  },
  "frameworks": {
    "netstandard1.5": {
      "imports": [
        "portable-net45+win8",
        "dnxcore50"
      ]
    }
  }
}
`
## Expected  behavior
`"Hello world!" `printed

## Actual behavior
`Could not load host policy library [/root/DEV/stuff/shared/Microsoft.NETCore.App/1.0.0-rc2-23929]
`
## Environment data
`dotnet --info` output:

```
Product Information:
 Version:     1.0.0-beta-002071
 Commit Sha:  cf616770ca

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

```

[project.lock.zip](https://github.com/dotnet/cli/files/237159/project.lock.zip)

**Comment by brthor** [comment]
How are you installing? 2071 is a fairly old version at this point

**Comment by GuardRex** [comment]
@karlti ... and change your framework to `netcoreapp1.0`.

**Comment by karlti** [comment]
@brthor first I had followed the steps from "https://dotnet.github.io/getting-started" had several problems. read in another issue that this build should be fine. so downloaded 2071 from `https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries` and setup locally.

is `1.0.0-rc2-3002498 `the current one? 

@GuardRex Thanks, but does not change. same issue.

my Linux is rusty, but I think I will try `1.0.0-rc2-3002498`

**Comment by GuardRex** [comment]
Yeah ... I meant in addition. You have a mismatch between your cli version and what your wildcard package dep is pulling down.

**Comment by karlti** [comment]
ok. finally I got it to work...
I apt-get version `dotnet-dev-1.0.0-rc2-002498`
and now I see tat friendly `"Hello world!"`
(after` execstack -c libcoreclr.so `& `rm libcoreclrtraceptprovider.so `)

Thanks!
