### ISSUE TITLE
"dotnet test project.json" fails in a directory with a test project.json in it

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#2691]
## Steps to reproduce
1. Make a test project somewhere
2. cd into that directory
3. Run `dotnet test project.json`

## Expected  behavior
The "project.json" file in the same directory is used and tests are run.

## Actual behavior
An error is given:
````
dotnet-test Error: 0 : System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.GetFullPath(String path)
   at Microsoft.DotNet.ProjectModel.WorkspaceContext.NormalizeProjectPath(String path)
   at Microsoft.DotNet.ProjectModel.WorkspaceContext.GetProjectContextCollection(String projectPath)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
````

NOTE: This works if I pass `dotnet test .\project.json`.

## Environment data
`dotnet --info` output:

````
.NET Command Line Tools (1.0.0-rc2-002498)

Product Information:
 Version:     1.0.0-rc2-002498
 Commit Sha:  55e561bfb3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
````

**Comment by eerhardt** [comment]
FYI - I have a fix for this.  It is a simple 2 line fix.

**Comment by piotrpMSFT** [comment]
@eerhardt did you send approval mail?

**Comment by eerhardt** [comment]
> @eerhardt did you send approval mail?

Just did.
