### ISSUE TITLE
dotnet --help is not functional when only installing .Net Core

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#2697]
## Steps to reproduce
1. Install the .Net Core your favorite Linux distro.  Note this is **not **installing the .Net Core SDK
2. Run `dotnet`
3. Observe the output `Usage: dotnet [--help | app.dll]`
4. Run `dotnet --help`

## Expected  behavior
I would not expect the Usage to display commands that are invalid.

## Actual behavior
`Could not resolve SDK directory from [/usr/share/dotnet]`

## Environment data
.Net Core 1.0.0-rc2-3002485 on Debian Jessie.

**Comment by piotrpMSFT** [comment]
@schellap we'll need to think about how to show host-specific help.

**Comment by schellap** [comment]
Displaying help is dependent on whether CLI is present or not actually.

Also, we should probably reword the CLI resolution error message as well in the CLI actually absent case.

**Comment by Tratcher** [comment]
`Did not find a suitable dotnet SDK at 'C:\Program Files\dotnet'. Install dotnet SDK from https://github.com/dotnet/cli` on Windows7 with 1.0.0-rc2-3002673.
`--version` doesn't work either.

help and version should have native defaults if the CLI is not installed.
