### ISSUE TITLE
Simplify build scripts

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#270]
Build scripts kept growing and it's time to clean up

**Comment by brthor** [comment]
@krwq They are somewhat complicated right now, but there is a lot going on too. 

What do you suggest should be simplified?

**Comment by anurse** [comment]
Agree entirely. Also, we have different scripts for Windows and Unix, which is unfortunate. We started with the simplest thing that would work and it's grown organically to be quite complicated (which was, to be honest, both expected and inevitable). Ideally we want the following:

* Simplicity. No big XML files (*cough* MSBuild *cough*), just simple steps
* Easy to edit. Ideally a language we're already using (i.e. CSharp)
* Cross-platform. One set of scripts for all platforms (with platform-specific behaviors if needed)

Some options include:

* MSBuild - It had to be mentioned, but I think many of us really don't want it :). It's got big complicated build files, it's hard to edit, it's not cross-platform (yet), etc.
* [Sake](https://github.com/sakeproject/sake) - It's what DNX uses, but it's very much just a side-project of one of the devs on the team. Not really a long-term viable project
* [ScriptCS](http://scriptcs.net/) - Not really designed with "build system" stuff in mind, but certainly cross-platform and easy to edit...
* [Cake](http://cakebuild.net/) - Designed to be a build system, cross-platform, easy to edit, etc.

Cake is possibly my personal favorite, with ScriptCS a close second.

**Comment by piotrpMSFT** [comment]
@anurse, can you pick this up? You have a great understanding of our scripts.

**Comment by anurse** [comment]
I should be able to replace the scripts with `dotnet run`. We'll use C# scripting and then use the stage 0 CLI we download to run the build scripts. However, I am currently blocked on #320 which should be getting resolved next week.

**Comment by shahid-pk** [comment]
:+1:  for cake

**Comment by devlead** [comment]
:+1: for Cake

**Comment by gep13** [comment]
:+1: for Cake

**Comment by piotrpMSFT** [comment]
The build script complexity is making development quite expensive. I don't want to take on migrating to Cake or similar just yet since this will likely require a CoreCLR port. For the time being, I want to enable a few common scenarios:
* Full builds are predictable
* On a dev box, expensive tasks can be minimized in execution. Once a build is done, portions of the build should be repeatable without re-running the full build. Portions include:
  * Install Pre-Req's
     * Stage 0
     * Dnx
  * Restore Packages
  * Build Stage 1
  * Build Stage 2
    * CrossGen
  * Run Tests
  * Package

We are pretty close to this already. I'm noticing two big issues:
- These steps are a bit leaky. Our runtest script, for example, does not run stand-alone
- The implementations are not encapsulated. These need to get teased apart.

**Comment by cdmihai** [comment]
It would be also nice for build.cmd to propagate dotnet arguments for dotnet like --verbose. It would be easier than editing the script in plance and then stashing that change :)

Another useful argument for build.cmd would be to just redo stage2

**Comment by piotrpMSFT** [comment]
@brthor why do Linux build scripts consider Compile and Package in Docker as independently configurable? This adds complexity I'd love to do away with. Can we make docker an all/nothing proposition?

**Comment by anurse** [comment]
The plan we originally discussed was to switch to `.csx` scripts and use `dotnet run`, but as far as I know C# interactive is still broken on .NET Core because of conflicts between runtime and reference assemblies.

**Comment by devlead** [comment]
@anurse as soon as Roslyn scripting is supported xplat on CoreCLR, then it's just a matter of time before @Cake-Build will utilize it. Cake's already available xplat on platforms you can build CoreCLR on via .Net or Mono so don't see why @piotrpMSFT  thinks it has to be ported to CoreCLR to be able to use it and for it to provide value.

Any build system like Cake, Fake, Bau, etc. will bring allot of pluming for free, going with just CSX would likely mean that allot if boiler plate code and tests unrelated to CoreCLR would've to be reinvented. Might be perfectly valid to do so, haven't seen an convincing argument just yet though :wink:

**Comment by piotrpMSFT** [comment]
This is a step in that direction. Unifying the build architecture x-plat makes it easy to move to single source as soon as it's available.

**Comment by piotrpMSFT** [comment]
@devlead, I'd love to avoid adding back a mono dependency if we can help it. Porting to CoreCLR means we can build anywhere that CoreCLR is available. Since that is a good indicator of where CLI should be available, it's a good dependency for us to have :)

Do you know if anyone considered the porting effort? I'd imagine that reducing platform dependencies could be beneficial for everyone!

**Comment by devlead** [comment]
@piotrpMSFT yes totally agreeing reducing dependencies would be beneficial :+1: 

Ran the .NET Portability analyzer on Cake, TLDR; shouldn't be an gigantic effort to port Cake to CoreCLR.

### Portability Summary 
| Assembly                         | .NET Core,Version=v5.0 | .NET Framework,Version=v4.6.1 | Note                                                      |
|----------------------------------|------------------------|-------------------------------|-----------------------------------------------------------|
| Cake, Version=0.7.0.0            | 99.11 %                | 100.00 %                      | Suggested workarounds exist for most, very little rewrite |
| Cake.Common, Version=0.7.0.0     | 96.39 %                | 100.00 %                      | WebClient -> HttpClient, System.Security.Cryptography, System.Xml now in separate nuget packages |
| Cake.Core, Version=0.7.0.0       | 94.12 %                | 100.00 %                      | System.AppDomain remove usage, System.Data split into several assemblies |


### Cake Dependencies Portability summary
| Assembly                                                  | .NET Core,Version=v5.0 | .NET Framework,Version=v4.6.1 | Note                                                                  |
|-----------------------------------------------------------|------------------------|-------------------------------|-----------------------------------------------------------------------|
| Autofac, Version=3.5.0.0                                  | 97.11 %                | 100.00 %                      | Version 4 fixes this, in RC now                                       |
| NuGet.Core, Version=2.8.60717.93                          | 89.32 %                | 100.00 %                      | V3 split into a set of nuget packages, need to investigate which assemblies needed starting with NuGet.Client |
| Microsoft.CodeAnalysis, Version=1.1.0.0                   | 100.00 %               | 99.70 %                       | 4.6 stuff in NuGet dependencies, CoreCLR not a supported platform yet |
| Microsoft.CodeAnalysis.Scripting, Version=1.1.0.0         | 100.00 %               | 97.61 %                       | 4.6 stuff in NuGet dependencies, CoreCLR not a supported platform yet |
| Microsoft.CodeAnalysis.Scripting.CSharp, Version=1.1.0.0  | 100.00 %               | 98.92 %                       | 4.6 stuff in NuGet dependencies, CoreCLR not a supported platform yet |

To summarize if Microsoft choose to support scripting on CoreCLR that would be key for starting a Cake port, when analyzing the code it doesn't look like allot is left for doing so. So feels very likely for that to happen :wink:

And Cake itself has very little code that wouldn't just work and most issues have documented workarounds, some things need to be references as NuGet packages and the few thing's not supported on CoreCLR yet could probably be ifdef/rewritten if it makes sense for CoreCLR. When dependencies in place, it would be a little more than a weekends work, but not a gigantic effort.

Regardless we would long term want Cake to support CoreCLR so we could support things like Nano Server and unify around one scripting engine. That said don't see why you couldn't adopt now, have it build xplat and then port when you know what's used, needed and dependencies are CoreCLR ready.

**Comment by brthor** [comment]
@piotrpMSFT 
Initially the build was fully happening in docker, but we ran into a GC deadlock issue during restore causing pretty frequent hangs. 

The issue is tracked here:
https://github.com/dotnet/coreclr/issues/2215

**Comment by piotrpMSFT** [comment]
@devlead @anurse thanks, this is interesting. Let's see where scripting stands when we reach RTM milestone... I'm not sure we'll be able to evolve the build scripts before then... I hope we can then have a full-on CoreCLR conversation.

@brthor, thanks for the detailed explanation. I didn't intend to disable docker, was only curious if we needed to maintain a build/package split. I ended up maintaining the current capability.

 #650 resolved this issue through refactoring of our scripts. I think this will set us up nicely both for fast iteration in the short term as well as for tackling #670 when we get time.
