### ISSUE TITLE
Should we support side by side installations in our installers?

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#271]
The default installation location is 
- windows - `%programfiles%/dotnet/cli`
- linux - `/usr/share/dotnet`
- Osx - `/usr/local/share/dotnet`

None of the installation paths are versioned. Should we support installing multiple versions of the CLI?

**Comment by blackdwarf** [comment]
I still think that SxS of the actual toolchain is something that most people will not do. For those that need it, as @piotrpMSFT mentioned corefx for instance, we have the ZIPs and they can package the toolchain they need (or more than one) themselves.

Thoughts?

@piotrpMSFT @Petermarcu

**Comment by weshaggard** [comment]
@blackdwarf do you ever run with SxS VS instances? I think a number of people do primarily because they are using the existing version of the tools to do the day jobs and then installing a new preview version of the tools that are still in preview mode for testing or playing around with. I think having multiple SxS versions of these tools will be more common then we might think.

**Comment by piotrpMSFT** [comment]
#341 should address our SxS concerns. Projects can reference packages that include the commands they care about. @weshaggard thoughts?

**Comment by weshaggard** [comment]
I do finding the commands in the packages does help with the sxs problems, at least for individual tools, it will still not help for the dotnet.exe shim itself but assuming we can keep that 100% compatible (not sure if that is possible) then it doesn't matter as much.

As for the tool packages it wasn't clear to me how those actually get discovered. Will they have to explicitly be listed in the project.json as dependency? It seems out to have to manually add a reference to a dotnet-compile package to get a compile command for example.

**Comment by brthor** [comment]
For native installers closed on not supporting SxS.

Local install will support sxs

**Comment by weshaggard** [comment]
>For native installers closed on not supporting SxS.

Is there further discussion around this? I'm curious what the thinking is about that decision as I suspect we will have to alter that in the future as most other tools, including C++ compiler, do SxS because it is almost impossible to guarantee back compat forever when doing in-place updates.
