### ISSUE TITLE
Relative paths in compilationOptions/additionalArguments don't work as expected when running build from a different folder

### ISSUE THREAD

**Issue by davunderscorei** [dotnet/cli#2710]
## Steps to reproduce
Given the following folder structure
```
- global.ruleset
- src
| - project
  | - project.json
```

With `project.json` including:
```
"compilationOptions": {
    "emitEntryPoint": true,
    "debugType": "portable",
    "additionalArguments": [ "/ruleset:../../global.ruleset" ]
  },
```

## Expected  behavior
Running `dotnet build` from the `\src\project` folder compiles the project.
Running `dotnet build .\src\project` from root folder compiles the project.

## Actual behavior
Running `dotnet build` from the `\src\project` folder compiles the project.
Running `dotnet build .\src\project` from root folder fails with error:
> C:\some\path\src\project\error CS8035: Error reading ruleset file C:\some\path\src\\..\\..\global.ruleset - File not found.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002498)

Product Information:
 Version:     1.0.0-rc2-002498
 Commit Sha:  55e561bfb3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by davidfowl** [comment]
@piotrpMSFT This is a @jaredpar @agocke issue

**Comment by Eilon** [comment]
Un-assigning from @ajaybhargavb as this is not related to his work.

**Comment by piotrpMSFT** [comment]
@jaredpar can you confirm that this is an issue your team should look at?

**Comment by jaredpar** [comment]
@piotrpMSFT in the `dotnet` model how does setting of the current directory function?  Should `csc` assume it's being executed with current directory set to `src\project`?

**Comment by agocke** [comment]
Also, I should note that `additionalArguments` are, by design, applied verbatim. Parsing is explicitly *not* applied to the compiler arguments, since one of the things it's supposed to support is arguments and argument formats that `dotnet` doesn't necessarily understand.

**Comment by Petermarcu** [comment]
@piotrpMSFT , try to get this in for today.
