### ISSUE TITLE
DotNet restore supports --packages but build and publish do not

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#2712]
Seems like a gap in functionality.  Is the expectation that folks use global.json here?
## Steps to reproduce

dotnet restore --packages c:\myPackages ...
dotnet build --packages c:\myPackages ...
dotnet publish --packages c:\myPackages ...
## Expected  behavior

Build and publish work using the specified packages folder
## Actual behavior

Build and Publish fail with `Unrecognized option '--packages'`
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002468)

Product Information:
 Version:     1.0.0-rc2-002468
 Commit Sha:  a2f3c531fb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14318
 OS Platform: Windows
 RID:         win10-x64

/cc @schaabs

**Comment by piotrpMSFT** [comment]
This is closely related to #2714

**Comment by brthor** [comment]
A workaround for this is to set the environment variable 
`NUGET_PACKAGES` to the packages directory before running the `dotnet build` process.

**Comment by livarcocc** [comment]
This is now supported across the verbs.

**Comment by patoncrispy** [comment]
This isn't in the CLI help options.

**Comment by s0n1cm** [comment]
Still not working for me?
