### ISSUE TITLE
After uninstall DotNetCoreCli newer version, new AspNetCore web application, meet error 'System cannot find file specified'

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#2713]
## Install Steps
Win7 Sp1 x64 ENU
DotNetCoreRedist (rc2-3002392) 
Dev14 U2 RTW VSE (with Web checkbox)
DotNetCoreTools RC2 (release.b104 includes DotNetCoreCli rc2-002426) 
Install DotNetCoreCli newer version (latest: rc2-002514)
Uninstall DotNetCoreCli newer version (latest: rc2-002514)

## Steps to reproduce
After uninstall DotNetCoreCli newer version, 
File > New AspNetCore web application

## Expected  behavior
It just works

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/8246794/14860209/8dca82c0-0c5c-11e6-87a0-6943ebbfb3e5.png)

Looks like the muxer has gone missing in this state

![image](https://cloud.githubusercontent.com/assets/8246794/14860387/79e9e538-0c5d-11e6-9b5c-1a945527e3a9.png)

**Comment by barrytang** [comment]
cc @Petermarcu and @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@balachir do you have a repro machine? I have a feeling this has to do with packaging + invocation in VS.

When you say you `uninstall DotNetCoreCLI` can you show what item you actually uninstalled? I understand that VS, at some point, considered the three CLI MSIs as a unit, which is incorrect. Assuming you just uninstalled the CLI MSI, which has its own ARP entry, I would expect your `shared` subfolder to contain a sub-directory for rc2-002514. If that's gone then 'something' is uninstalling more than the CLI and apparently is uninstalling the host as well.

I'm also curious where VS got the version number listed in the dialog box above. It should absolutely not be making any correlations between installed Shared Framework versions and CLI versions.

**Comment by balachir** [comment]
@piotrpMSFT, I sent you email with repro machine and exact build locations we used. 

Regarding the version number shown in dialog box, it sounds like this should be a bug on our side. @BillHiebert, where do we get this version info from?
![image](https://cloud.githubusercontent.com/assets/8246794/14867343/ea5f6cd8-0c7c-11e6-93fb-056970ec42d8.png)

**Comment by piotrpMSFT** [comment]
FYI, @Sridhar-MS was able to repro the issue and verify it is a bug in the CLI bundles. Fix coming.

**Comment by Petermarcu** [comment]
@Sridhar-MS , get this in today.

**Comment by piotrpMSFT** [comment]
Fixed by #2789
