### ISSUE TITLE
dotnet restore | build | publish do not respect nuget.config repository path

### ISSUE THREAD

**Issue by schaabs** [dotnet/cli#2714]
## Steps to reproduce

use cli to restore | build | publish a project which has a nuget.config with a specific repository path.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
...
  <config>
    <add key="repositoryPath" value=".\utpackage" />
  </config>
...
</configuration>
```

however if you create the following global.json in the same directory it functions as expected:

```
{
  "packages": "utpackage"
}
```
## Expected  behavior

dotnet cli should respect both global.json packages property and nuget.config repositoryPath
## Actual behavior

if only the nuget.config is present packages are restored to and referenced from the global packages cache
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002468)

Product Information:
 Version:     1.0.0-rc2-002468
 Commit Sha:  a2f3c531fb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14318
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@yishaigalatzer @davidfowl @emgarten  your thoughts on this? Can you point me to an API in NuGet to get the resolved repositoryPath?

**Comment by yishaigalatzer** [comment]
We should deprecate the duplicate global.json property it just adds confusion.

You will need to use nuget.configuration package for this

**Comment by emgarten** [comment]
``repositoryPath`` refers to the packages.config ``packages`` folder, not to the global package folder.

The issue for tracking the API for the global folder is here: https://github.com/NuGet/Home/issues/2403

**Comment by yishaigalatzer** [comment]
@emgarten can you provide a current code sample?

**Comment by brthor** [comment]
Given that this is scheduled for RC2 on the cli side, will you guys @emgarten @yishaigalatzer be providing the NuGet global api in that timeframe or do we need to do something temporary?

**Comment by yishaigalatzer** [comment]
We can bring it up in shiproom but you should be able to do it without a new API. Let's post the use sample here and decide

**Comment by brthor** [comment]
@emgarten Should we ignore `repositoryPath` altogether then in the cli, or should it be used as a pointer to the global packages location?

**Comment by schaabs** [comment]
I think there must be some way to configure where build and publish pull packages from.  The only way to do this currently is through global.json (or through repositoryPath once this is fixed), unless you take suggestion https://github.com/dotnet/cli/issues/2712

**Comment by brthor** [comment]
I think we'll do `--packages` #2712 but an important question is should we support both and with what precedence?

**Comment by emgarten** [comment]
The order should be:

1. ``--packages``
1. ``NUGET_PACKAGES``
1. ``globalPackagesFolder`` from nuget.config
1. default location

dotnet restore reads the packages parameter first here:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/RestoreArgs.cs#L68-L80

Then checks the environment variable and settings here:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L127-L154

The global folder path in ``global.json`` was deprecated and is not used by NuGet. 

``repositoryPath`` refers to to the packages folder for packages.config and should not be used with project.json

**Comment by brthor** [comment]
Thanks @emgarten !

**Comment by brthor** [comment]
@emgarten Is there any api available in NuGet to ready the NuGet.config? Looking through NuGet.Client I don't see anything obvious

**Comment by emgarten** [comment]
Use ``SettingsUtility.GetGlobalPackagesFolder`` from NuGet.Configuration

**Comment by piotrpMSFT** [comment]
With preview3+, you can `restore --packages {path to packages dir}` and subsequent commands will find the right folder based on the packages directory path written to project.assets.json by restore!

**Comment by piotrpMSFT** [comment]
I reread the issue and realized I offered a workaround instead of a fix. Will open an issue on nuget/home instead, link to this one, and then close this one. It is up to nuget xplat to honor this configuration.
