### ISSUE TITLE
dotnet needs a command that works with project tools/commands

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2715]
dotnet needs a command that allow list, install, remove tools from the project.

e.g. `dotnet tools list` would list all the tools installed into project.

**Comment by piotrpMSFT** [comment]
@yishaigalatzer is this a capability that should be exposed through NuGet xplat?

**Comment by yishaigalatzer** [comment]
I would think so

**Comment by svick** [comment]
Is this a duplicate of #917?

**Comment by blackdwarf** [comment]
@svick yes, it is. Closing as a dupe of #917.
