### ISSUE TITLE
In VS changing project.json TFM from 'netstandard1.5' to a different 'netstandard1.x' tries to restore both 

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#2718]
## Steps to reproduce
- File/New Project
- NetCore ClassLib
- In project.json change 'netstandard1.5' to 'netstandard1.0'

RESULT:
VS thinks I'm using *both* 'netstandard1.5' *and* 'netstandard1.0':
References node shows both frameworks

I turned on project model server trace and it is returning both the old and the new framework.

**Comment by troydai** [comment]
It's a regression. I'm looking into this.

**Comment by piotrpMSFT** [comment]
@troydai please make sure we have a test for this once fixed.

**Comment by troydai** [comment]
@piotrpMSFT thanks for reminding. I'll begin any work with at least one test to cover the scenario I intends to impact.

**Comment by Petermarcu** [comment]
@anurse , @troydai is this fixed now? Can it be closed?

**Comment by troydai** [comment]
@Petermarcu the fix was merged 22 hours ago so the latest build has it. The fix comes with a test case covering the scenario. Now @BillHiebert is verifying it in VS.

**Comment by anurse** [comment]
Assigning to @BillHiebert to verify and close. If this is still occurring, please reassign to me and ping this!

**Comment by BillHiebert** [comment]
Verified it works on 1.0.0-rc2-002611

**Comment by Eilon** [comment]
Tried on the final RTM bits, confirmed works there too. Thanks!

**Comment by Eilon** [comment]
Sorry final RC2 / Preview1 bits I meant 😄
