### ISSUE TITLE
dotnet pack/packInclude not working with absolute paths

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#2720]
When passing absolute path to packInclude  in project.json, dotnet pack produces invalid content:
- target file does not exist,
- different file shows up instead,
- no error or warning is reported

Exactly the same setup with relative paths to project.json works fine.
I didn't test if the same repros with packOptions but assuming it is since this is the same logic.

example project.json:

```
{
  "version": "1.0.0-*",
  "name": "dupa",
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },
  "frameworks": {
    "netstandard1.5": {},
    "netcoreapp1.0": {}
  },
  "runtimes": {
    "rhel.7-x64": {}
  },
  "packInclude": {
    "runtimes/rhel.7-x64/native/": [ "C:\\someabsolutepath.txt" ]
  }
}
```

add run `dotnet pack`.

**Comment by ajaybhargavb** [comment]
@krwq, Could you check if this works on a previous version of dotnet cli? That is before the project model changes.

**Comment by krwq** [comment]
I believe @brthor just tested it and he was also seeing it, @brthor could you confirm?

**Comment by ajaybhargavb** [comment]
I investigated more and I can confirm that this is not a regression from the recent changes. `packInclude` had the same behavior for a long time. It never supported absolute paths.

As a workaround using the new schema you can do,
```json
"packOptions": {
  "files": {
    "mappings": {
      "runtimes/rhel.7-x64/native/": {
        "includeFiles": [ "C:\\someabsolutepath.txt" ]
      }
    }
  }
}
```
And this will throw an exception,
`System.InvalidOperationException: The 'includeFiles' property cannot be a rooted path.`

**Comment by brthor** [comment]
Also confirmed this was happening prior to to @ajaybhargavb 's changes

**Comment by Petermarcu** [comment]
So is this an RC2 issue anymore?

**Comment by piotrpMSFT** [comment]
@krwq confirmed we don't need this for RC2

**Comment by Eilon** [comment]
Un-assigning from @ajaybhargavb as this is not related to his work.

@piotrpMSFT can you find another engineer for this? Thanks!

**Comment by blackdwarf** [comment]
@krwq can you try to repro this with the latest tooling?

**Comment by piotrpMSFT** [comment]
This was an issue in the project.json-based pack command. Now that CLI is using xplat nuget client, if this is still an issue for anyone then please open in nuget/home.
