### ISSUE TITLE
Reintroduce "operands/parameters before options" support in the command line parser

### ISSUE THREAD

**Issue by PinpointTownes** [dotnet/cli#2728]
_Moved from https://github.com/dotnet/cli/issues/2643#issuecomment-215351732:_

---
## Steps to reproduce

Run `dotnet run server.urls=http://localhost:53507/ --framework net451`
## Expected  behavior

The `--framework net451` option should be recognized and should allow running the console app using .NET Framework, [exactly like it used to work before moving away from `System.CommandLine`](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine#parameters).
## Actual behavior

`--framework net451` is silently ignored, due to its position in the command line.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002531)

Product Information:
 Version:     1.0.0-rc2-002531
 Commit Sha:  a9621eb469

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by PinpointTownes** [comment]
_Moved from https://github.com/dotnet/cli/issues/2643#issuecomment-215445196:_
___________

@PinpointTownes - this behavior is by design. The first syntax is incorrect according to:

http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02

> Guideline 9:
All options should precede operands on the command line.
It may have worked before, but it wasn't intended to work.

**Comment by PinpointTownes** [comment]
_Moved from https://github.com/dotnet/cli/issues/2643#issuecomment-215351732:_
______

Well, it's not really incorrect since specifying options before operands/arguments is just "recommended", not mandatory (it's a *should*, not a *must*). And IIRC, the command lines stack already goes beyond what POSIX requires (e.g double dash support).

The "old" syntax feels more natural (IMHO) and is supported by many programs like git or all the GNU utilities.

**Comment by PinpointTownes** [comment]
_Moved from https://github.com/dotnet/cli/issues/2643#issuecomment-215462529:_
______

Feel free to log a separate issue, as the scenario you are asking for is in direct conflict with this issue.

This issue says:

> Create a command-line app that accepts more than one argument (eg. "Hello" -p) try to a pass the arguments as operands the run command, ie your command-line app.

> Actual behavior
dotnet run "Hello" -p
Specify --help for a list of available options and commands.
Missing value for option 'project'

You are asking to allow -p after "Hello". If that was allowed, failing for an empty -p argument would be the correct behavior.

**Comment by piotrpMSFT** [comment]
Thanks @PinpointTownes. Lets take a broader look at parser behavior for RTM. I have a feeling we'll be collecting a few similar issues as folks experiment with the unified parser.

**Comment by livarcocc** [comment]
We added a separator to the run command to separate arguments passed to the dotnet run command and arguments passed to the application being executed.

Like this, `dotnet run -- -c Debug -f netcoreapp2.0 portable`.

I believe this addresses this issue. If that's not the case, please re-activate.
