### ISSUE TITLE
Problems with installer on Windows

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#2730]
## Steps to reproduce
1. Download windows installer from here: http://dotnet.github.io/getting-started/ and install.
2. Uninstall.
3. Re-Install

## Expected  behavior
Can use `dotnet` cli from command line.

## Actual behavior
Can't find dotnetcli anywhere. Can't run dotnet cli from command line. It doesn't appear to have re-installed dotnet cli.

## Environment data
`dotnet --info` output: 
![image](https://cloud.githubusercontent.com/assets/3176632/14891509/e2184b84-0d5e-11e6-9f8f-b6d180a451d1.png)

**Comment by Sridhar-MS** [comment]
@dazinator Which windows version are you using?

**Comment by dazinator** [comment]
Windows 10, latest update :)

**Comment by dazinator** [comment]
Oh wait.. sorry - this problem was actually when installing on our build server which is windows server 2012.

**Comment by Petermarcu** [comment]
@Sridhar-MS , Can you get this in today?

**Comment by piotrpMSFT** [comment]
I just tested this with 
````
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86
````

And did not have any issues. Please re-open with a specific version of CLI if you're still seeing an issue.

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x86.latest.exe

**Comment by dazinator** [comment]
@piotrpMSFT - Looks like your test was on Windows 10 with x86? I am having the problem on Windows Server 2012 (x64). - this is the installer I downloaded from the getting started io site: https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0.001598/dotnet-win-x64.1.0.0.001598.exe

No matter how many times I run this installer, uninstall, repair etc - It always completes successfully, but dotnet is not being installed..

**Comment by dazinator** [comment]
@piotrpMSFT - I would reopen this based on the above comment, but I don't have that power!

**Comment by piotrpMSFT** [comment]
Thanks. Do you also have x64? We found and are fixing an issue which repros if you install both.

**Comment by Sridhar-MS** [comment]
@dazinator Can you give the installer log files in the %tmp% directory?

**Comment by dazinator** [comment]
@Sridhar-MS I can, I will probably have a lot of files in the temp directory though - how do I find the log files for the installer?

**Comment by Sridhar-MS** [comment]
Can you also try the latest x64 installer - https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe?

**Comment by Sridhar-MS** [comment]
Something like `Microsoft_Dotnet_CLI_for_Windows_(1.0.0.001598_)*.log` in the temp folder.

**Comment by dazinator** [comment]
@Sridhar-MS ok, ill send the logs and try new installer at some point tomorrow, thanks.

**Comment by dazinator** [comment]
@Sridhar-MS I just ran the problematic installer (build 001598) and did a "Repair". It says it completed successfully, but no `dotnetcli` available on the command line - and here is the log you asked for: https://gist.github.com/dazinator/0867728f86c0a145680c4a8838b87358

`

**Comment by dazinator** [comment]
@Sridhar-MS 
> Can you also try the latest x64 installer - https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe?

I just tried this and this installer did successfully install dotnetcli. However it has also left the broken install in place:

![image](https://cloud.githubusercontent.com/assets/3176632/14989969/69922160-1152-11e6-9709-0f03470e3a19.png)

Perhaps that is meant to happen. I'll manually remove the old install now.

**Comment by piotrpMSFT** [comment]
Thanks for confirming. @sridhar-ms fixed this behavior only recently so what you saw is expected when uninstalling older builds. It is fixed moving forward.
