### ISSUE TITLE
EULA link in README.md points to an RTF file in GitHub, can't read it

### ISSUE THREAD

**Issue by Eilon** [dotnet/cli#2731]
The default readme shown at https://github.com/dotnet/cli/ has a link a the bottom that points at the EULA. The link is to https://aka.ms/dotnet-cli-eula, which redirects to https://github.com/dotnet/cli/blob/master/packaging/osx/sharedframework/resources/en.lproj/eula.rtf.

Unfortunately GitHub doesn't have a viewer for RTF files, so all you see is garbled curly braces and backslashes with some text scattered around.

Is there a TXT or HTML version of the EULA that this could point to instead?

**Comment by piotrpMSFT** [comment]
@blackdwarf was looking at adding EULAs to https://dotnet.github.io. Those are supposed to handle our web-readable EULA needs.

**Comment by blackdwarf** [comment]
This is now fixed.

**Comment by Eilon** [comment]
Looks good, thanks!
