### ISSUE TITLE
[dotnet build] regression: latest cli fails to build xproj->csproj saying that TFMs are incompatible

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#2737]
## Steps to reproduce

1. create a new core console app
2. remove default framework and package dependencies and substitute it with "net46"
3. Create new windows classlibrary with target 4.5.1
4. Wait for restore (it is workiing fine and restores csproj ok)
5. Build

## Expected  behavior

Build fine

## Actual behavior
Build error:  Compiling ConsoleApp19 for .NETFramework,Version=v4.6
2>c:\Users\antonpis\Documents\Visual Studio 2015\Projects\ConsoleApp19\src\ConsoleApp19\project.json(13,27): error NU1002: The dependency ClassLibrary1 1.0.0 does not support framework .NETFramework,Version=v4.6.

It used to work until i installed latest dotnet cli

## Environment data
`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002520)

Product Information:
 Version:     1.0.0-rc2-002520
 Commit Sha:  7c504b2456

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@abpiskunov can you share your repro?

**Comment by abpiskunov** [comment]
Use this zip: \\vwdbuild01\Temp\antonpis\repro\DotNetBuildFailed.zip

**Comment by brthor** [comment]
@abpiskunov Are you able to provide any command line repro here or is this VS only?

**Comment by piotrpMSFT** [comment]
@brthor I have a cmd line repro
