### ISSUE TITLE
Dotnet publish now fails for netcore50 when no run-time assemblies are present in the nuget packages

### ISSUE THREAD

**Issue by jterry75** [dotnet/cli#2739]
## Steps to reproduce

``` json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "runtimes": {
    "win10-x64": {}
  },
  "frameworks": {
    "netcore50": {
      "dependencies": {
        "System.IO": "4.0.0"
      }
    }
  }
}
```

Using dotnet restore on the above project.json now fails when before the RC2 release this would succeed.
## Expected  behavior

The restore succeeds without failure and I can publish the app using dotnet publish
## Actual behavior

Restore fails with the error:

Errors in D:\gowork\src\github.com\Microsoft\Docker-PowerShell\src\Docker.DotNet\testapp\project.json
    System.IO 4.0.0 provides a compile-time reference assembly for System.IO on .NETCore,Version=v5.0, but there is no run-time assembly compatible with win10-x64.
    System.Runtime 4.0.0 provides a compile-time reference assembly for System.Runtime on .NETCore,Version=v5.0, but there is no run-time assembly compatible with win10-x64.
    System.Text.Encoding 4.0.0 provides a compile-time reference assembly for System.Text.Encoding on .NETCore,Version=v5.0, but there is no run-time assembly compatible with win10-x64.
    System.Threading.Tasks 4.0.0 provides a compile-time reference assembly for System.Threading.Tasks on .NETCore,Version=v5.0, but there is no run-time assembly compatible with win10-x64.
    One or more packages are incompatible with .NETCore,Version=v5.0 (win10-x64).
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002533)

Product Information:
 Version:     1.0.0-rc2-002533
 Commit Sha:  3742f5c4a8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14332
 OS Platform: Windows
 RID:         win10-x64

**Comment by jterry75** [comment]
I also later tried to update to the nuget feed:

    <add key="nuget.org" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />

So that I could try the 4.1.0-* binary and it fails the same way even for the RC3 beta releases. How are we expected to do this?

**Comment by piotrpMSFT** [comment]
@ericstj can you take a look at this issue and give guidance?

**Comment by ericstj** [comment]
@jterry75 what are you intending to do here?  `netcore50` is the TFM for UWP apps which aren't supported at all by dotnet CLI (its missing the APPx packaging, .NETNative toolchain, etc).

The CLI would have failed restore for this project ever since it move from using DNX to NuGet so this isn't a recent regression.  NuGet is correctly failing restore here since this app is compiling as standalone and missing an implementation for something it is referencing.

**Comment by jterry75** [comment]
@ericstj Oddly enough this wasn't failing when using CLI beta (1.0.0-beta-002252) before any of the people on my team updated to the RC2 release of the dotnet cli (1.0.0-rc2-002533). Either way maybe that is a red herring.

I was under the impression that as of  [NuGet 3.1](http://blog.nuget.org/20150729/Introducing-nuget-uwp.html) project.json support was available for UWP apps? Are you saying that even though that is supported dotnet cli does not yet support building an application that is targeting that TFM?

Our only goal is to build an application that works for net45/net45/.netcore50 (uap10)/coreclr. There have been an incredible amount of changes to TFM's lately so its possible that we are doing something wrong on our side. How would you best approach building such an application?

**Comment by ericstj** [comment]
@jterry75 build a portable library targeting (NETStandard) [https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms].  If you want to go to .NET 4.5 you need to target NETStandard1.1 or lower.  If that doesn't provide enough API you can cross-compile for .NET 4.5 and target a higher version of NETStandard for the PCL implementation.

**Comment by blackdwarf** [comment]
Given the thread and the solutions presented, as well as lack of activity I will close this issue.
