### ISSUE TITLE
Tantalisingly slow download from dotnetcli.blob.core.windows.net

### ISSUE THREAD

**Issue by haf** [dotnet/cli#2740]
## Steps to reproduce
Go to Sweden.

Alternatively use a VPN like [IPredator](https://ipredator.se/) which has 3 days for free on signup.

Run `curl -o tools/dotnet-dev-ubuntu-x64.1.0.0-beta-002071.tar.gz -L https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-beta-002071/dotnet-dev-ubuntu-x64.1.0.0-beta-002071.tar.gz`

Count sheep, fall asleep, cut some leek, gaze at a speed very meek.

## Expected behaviour

Blazingly fast downloads. I have 1Gbps symmetric fiber direct to Skanova's AS.

## Actual behaviour
Rather slow such.

## Environment data
`dotnet --info` output: nope, because I finished filing this issue before the download completed... So far at 56% and 10 min 50 seconds.

**Comment by piotrpMSFT** [comment]
Thanks @haf. I have a half dozenz engineers excited to repro this issue :)

I'm going to rename the issue. CLI builds do not get pushed to a CDN today, and so I expect this problem to exist globally. We need to fix.

**Comment by Petermarcu** [comment]
For our RC2 build, we need to make sure it gets on an existing CDN. We should also make sure people downloading from our Azure storage have a good experience but its not blocking the RC2 release.

**Comment by piotrpMSFT** [comment]
RTM/Preview2 bits will be on the download center which is CDN'd. We'll get our blob storage updated for RTM of tools.

**Comment by livarcocc** [comment]
We are publishing to a CDN now.

**Comment by darkguy2008** [comment]
What is the CDN? I'm having the same issue from Costa Rica, I have 100mbps optic fiber and most I get is 1Mb/s... which is ridiculous.
