### ISSUE TITLE
dotnet test throws exception if it cannot find project.json

### ISSUE THREAD

**Issue by thecodejunkie** [dotnet/cli#2752]
## Steps to reproduce

Invoke `dotnet test` in a folder that does not contain a `project.json` file
## Expected  behavior

To get a message informing me that it could not find any tests or perhaps that it has to be invoked from a path that contains a `project.json` file
## Actual behavior

```
> dotnet test

dotnet-test Error: 0 : System.InvalidOperationException: <path>\project.json does not exist.
   at Microsoft.DotNet.Tools.Test.TestCommand.GetProjectPath(String projectPath)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by scionwest** [comment]
Is there an update on this? I'm hitting this same issue now, where I'm executing `dotnet test -p Path/To/Test/Project.json` and getting this exception. I'm using VSCode tasks to try and run my test project.

{
        // See https://go.microsoft.com/fwlink/?LinkId=733558
        // for the documentation about the tasks.json format
        "version": "0.1.0",
        "command": "dotnet",
        "isShellCommand": true,
        "args": [],
        "tasks": [
            {
                "taskName": "build",
                "args": [ 
                    "Source/Runtime/MudDesigner.Engine", 
                    "Source/Runtime/MudDesigner.Adapters.Commanding",
                    "Source/Runtime/MudDesigner.Adapters.BasicRules",
                    "Source/Runtime/MudDesigner.Adapters.Server",
                    "Source/Tools/MudDesigner.ConsoleServer",
                    "Tests/Runtime/MudDesigner.Engine.Tests"
                    ],
                "isBuildCommand": true,
                "showOutput": "always",
                "problemMatcher": "$msCompile"
            },
            {
                "taskName": "restore",
                "args": [ ],
                "showOutput": "always",
                "problemMatcher": "$msCompile"
            },
            {
                "taskName": "run",
                "args": [ "-p", "Source/Tools/MudDesigner.ConsoleServer" ],
                "showOutput": "always",
                "problemMatcher": "$msCompile"
            },
            {
                "taskName": "test",
                "args": [ "-p", "Tests/Runtime/MudDesigner.Engine.Tests" ],
                "showOutput": "always",
                "problemMatcher": "$msCompile"
            }
        ]
    }

**Comment by piotrpMSFT** [comment]
`dotnet test` will be undergoing significant changes post-preview2 so pushing this out.

**Comment by thecodejunkie** [comment]
@piotrpMSFT what changes are these?

**Comment by blackdwarf** [comment]
This is fixed in the latest, MSBuild-based tooling. Invoking `dotnet test` in an empty directory does not throw and you can pass in a path to the project to run tests from which works. Closing the issue,
