### ISSUE TITLE
Modify RuntimeEnvironment to use System.Runtime.InteropServices.RuntimeInformation 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2754]
The code ported from `Microsoft.Extensions.PlatformAbstractions` contains a bunch of pinvokes for APIs that are available via the RuntimeInformation package. However the package has issues in RC2 where it does not bring in runtime binaries in desktop applications. This is fixed in RTM (https://github.com/dotnet/corefx/issues/7863).

**Comment by piotrpMSFT** [comment]
I looked at the dependencies of Microsoft.Extensions.PlatformAbstractions. It does not have any dependencies back into CLI, so as long as the package references shipping CoreFx packages I don't have concern about the cycle for RC2.

**Comment by piotrpMSFT** [comment]
since the PR is out, let's leave this in :)

**Comment by piotrpMSFT** [comment]
Per conversation with @pranavkm this is tracking remaining work for RTM which will enable using RuntimeInformation in desktop projects. This is dependent on dotnet/corefx#7863 and so will be fixed in RTM once that is fixed.

**Comment by pranavkm** [comment]
I was looking at this again and there's a bunch of APIs in `RuntimeInformation` that we require (Unix distro name, OsVersion) that are internal to corefx. I'll file a work item to see if they are willing to make these APIs usable to us.

**Comment by pranavkm** [comment]
https://github.com/dotnet/corefx/issues/9011 bug.

**Comment by piotrpMSFT** [comment]
The CoreFx issue is still open, so moving this out of RTM.

**Comment by livarcocc** [comment]
We don't ship this out of the CLI anymore.
