### ISSUE TITLE
If a project only targets a single framework, `dotnet build -o` shouldn't require user to pass --framework

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#2755]
## Steps to reproduce
1. Have a project that only targets a single TFM.  (A good one is the src\dotnet project in this repo.)
2. `dotnet build -o C:\temp`
## Expected  behavior

The project should be built with its output in the specified location.
## Actual behavior

An error occurs with the following message:
`When the '--output' option is provided, the '--framework' option must also be provided.`
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
This does not repro on Preview 4 bits which means it is mitigated by the move to MSBuild. Will close, if it comes up again, please reopen.
