### ISSUE TITLE
Please document known failure in dotnet restore (#2545)

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/cli#2758]
Following the basic instructions available in several locations, `dotnet restore` fails out of the box for what to the uninitiated appear to be absurd reasons.  I believe this is issue #2545.  If we aren't going to fix this yesterday, at the very least the workaround should be documented front and center on the CLI GitHub home page, if not in other places. 

## Steps to reproduce
Unpack dotnet RC2 candidate (1.0.0-rc2-002543 as of now) and put it in your path.  I did this on Windows.  I'm not sure if it is specific to Windows.
```
mkdir demo
cd demo
dotnet new
dotnet restore
```

## Expected  behavior
Restores successfully

## Actual behavior
```
log  : Restoring packages for C:\Users\russellk\demo\project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json 155ms
error: Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002543)' for '.NETCoreApp,Version=v1.0'.
info : Committing restore...
log  : Writing lock file to disk. Path: C:\Users\russellk\demo\project.lock.json
log  : C:\Users\russellk\demo\project.json
log  : Restore failed in 338ms.

Errors in C:\Users\russellk\demo\project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002543)' for '.NETCoreApp,Version=v1.0'.

NuGet Config files used:
    C:\Users\russellk\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by leecow** [comment]
Acquisition feedback - @blackdwarf

**Comment by Petermarcu** [comment]
We should add instructions on the repo for people using dev builds to make sure they know exactly the NuGet.Config they need to have to be successful.

**Comment by radu-matei** [comment]
Having the same behavior in OS X, environment info:

`
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
`

**Comment by blackdwarf** [comment]
@leecow good one. Previously, `dotnet new` dropped a NuGet.config that had the configurations, but we removed it getting ready for RC2. This guidance won't be needed for any official release, since the packages for that release will be on NuGet.org.
