### ISSUE TITLE
"refs" and "runtimes" in the output folder could potentially conflict with the app's own content

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/cli#2762]
## Steps to reproduce

Create a project that references a "fat package" (one that includes platform-specific native assemblies, e.g. `Microsoft.AspNetCore.Server.Kestrel`) and sets the `"compilationOptions": { "preserveCompilationContext": true }`" configuration option.
## Expected  behavior

Implicit assets (one's added by the tool-chain) in my project's output should have a low risk of conflicting with the project's own content.
## Actual behavior

The "refs" and "runtimes" folders created in the output have no mitigation to lower the risk of conflicts (e.g. prefixing the folder names, etc.)  
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002498)

Product Information:
 Version:     1.0.0-rc2-002498
 Commit Sha:  55e561bfb3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by Petermarcu** [comment]
@DamianEdwards , RC2 blocking or RTM?

**Comment by DamianEdwards** [comment]
RTM

**Comment by blackdwarf** [comment]
@DamianEdwards is this still a problem in the latest tooling (MSBuild-based)?

**Comment by livarcocc** [comment]
Closing as I don't believe this applies anymore.
