### ISSUE TITLE
dotnet build dumps a single error across 3 lines which causes 3 error list items to be created

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#2763]
## Steps to reproduce
1. Install dotnet 1.0.0-rc2-002543
2. From VS create a console application
3. Remove type:platform from dependency
   4 Add a win7-x64 runtime
   build

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : 1. The project has not been restored or restore failed - run `dotnet restore`
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : 2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
## Expected  behavior

Expect a single error with this information.

**Comment by krwq** [comment]
try calling `dotnet restore` before building

**Comment by mellinoe** [comment]
I think the issue is more about three errors being "generated" (or interpreted at such) rather than one, because they're on separate lines.

**Comment by dkent600** [comment]
in any case, "dotnet restore" doesn't get rid of the error, for me.  :-(

**Comment by blackdwarf** [comment]
With the introduction of MSBuild, I believe this is not a problem anymore. @BillHiebert can you confirm?

**Comment by piotrpMSFT** [comment]
This doesn't seem to repro any longer in CLI [rc3]. Furthermore, VS now interacts with these commands through direct MSBuild invocations, making the multi-line output far less important for providing a great UX.
