### ISSUE TITLE
Console.ReadLine() doesn't display input

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#2775]
(From dotnet/corefx#8184, opened by @omajid)

On RHEL 7, when I run the following program (using `dotnet run`) and type some input, I don't see what I am typing until I hit ENTER. Then everything I have typed appears at once:

    public static void Main(string[] args)
    {
        Console.WriteLine("Name: ");
        var name = Console.ReadLine();
    }

    $ dotnet --version
    1.0.0-rc2-002538

**Comment by ellismg** [comment]
We confirmed that if you used `dotnet` to invoke the MSIL directly, you don't hit this issue, so @stephentoub and I suspect this is related to how dotnet run captures output.

**Comment by brthor** [comment]
This is the same issue as #2777 that the Streamforwarder buffers output of the child process by line, going to close this as a duplicate.
