### ISSUE TITLE
Strange behavior with Process creation and termination

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#2776]
## Steps to reproduce

Consider this program:

``` CSharp
public static void Main(string[] args)
{
    ProcessStartInfo psi = new ProcessStartInfo("ping", "github.com");
    psi.RedirectStandardOutput = true;
    Process.Start(psi);
    Console.WriteLine("Process started.");
}
```

NOTE: This is just an easy example, my use case is slightly different (using xdg-open to launch a browser). Ping works here because it usually takes a while to exit.
## Expected  behavior

The program starts a process, prints out "Process started", and terminates.
## Actual behavior

When executed via `dotnet run`, the program does not terminate until the "ping" process terminates. Executing `killall ping` causes the `dotnet` process to terminate, as well, once `ping` has been killed.

When I run the same program using corerun or coreconsole, the above behavior is not exhibited. A ping process is started, but the program immediately terminates. Ping continues in the background.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.04
 OS Platform: Linux
 RID:         ubuntu.15.04-x64
```

**Comment by mellinoe** [comment]
Another point of data: If I execute `dotnet <test.dll>`, then the correct behavior is exhibited.

**Comment by brthor** [comment]
It seems like we should be a little more robust in how we manage child processes in `dotnet run` here, it sounds like we are waiting for the entire process tree instead of the immediate child.

I don't think this is a blocker for RC2 though, comment if you feel otherwise.

**Comment by livarcocc** [comment]
@mellinoe I just tried this in 1.0.1 and I hit the same thing, except that when I published the app and run it using dotnet <dll> it exhibited the same delay there. So, wondering if that's an issue with dotnet.exe, since that's also what we use during dotnet run.

I will move this issue to core-setup.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#1762
