### ISSUE TITLE
dotnet-compile-native --help crashing...

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#278]
I'm getting "application stopped working" just after the help is printed.

**Comment by livarcocc** [comment]
I will take a look at it.

**Comment by krwq** [comment]
https://github.com/dotnet/corefxlab/blob/master/src/System.CommandLine/src/System/CommandLine/ArgumentSyntax.cs#L59

**Comment by krwq** [comment]
https://github.com/dotnet/corefxlab/pull/471
I want to workaround it by disabling help by default and manually displaying it - I need IsHelpRequested from commandline parser. For failfast issue - currently Im not aware of any portable workarounds except for Process.GetCurrentProcess().Kill() which is exiting with NZEC

**Comment by livarcocc** [comment]
3b9828404eab0aa07bfa266549fd37fa1acd5eff
