### ISSUE TITLE
Console.WindowWidth fails with IOException

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#2780]
moved from https://github.com/dotnet/corefx/issues/7858
/cc @twsouthwick 

Try the following:

Program.cs:

``` csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine($"Width: {Console.WindowWidth}");
        }
    }
}
```

project.json:

``` json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002424"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
```

The fails with the following exception:

```
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_WindowWidth()
   at System.Console.get_WindowWidth()
   at ConsoleApplication.Program.Main(String[] args)
```

**Comment by brthor** [comment]
Going to put this for RTM for now, this could be worked around by executing the assembly directly using `dotnet` rather than `dotnet run` for the moment.

If you feel it should be RC2 please comment.

**Comment by williamthiago** [comment]
Same behavior/exception for:
``` csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.Clear();
        }
    }
}
```

**Comment by billboga** [comment]
I have the same problem, but only when running the app. in Cygwin. Things are fine using Windows Command Prompt/PowerShell.

**Comment by blackdwarf** [comment]
This does not repro for me in either of the following (using the Preview 4 tooling):

* PowerShell
* CMD
* iTerm2
* Default terminal on the Mac

Therefore, closing this. If it repros again, please reopen.

**Comment by Zexuz** [comment]
```csharp
int x = Console.CursorLeft;
int y = Console.CursorTop;
Console.CursorTop = Console.WindowTop + Console.WindowHeight - 1;
Console.Write(s);
Console.SetCursorPosition(x, y);
```

I had the above code in a project that was running in Azure as a web app with ASP.NET Core 2.1.

It gave me the the same error.
After removing this code it works flawless. I did not check what piece of code was throwing the error and I don't really know why this is happening.

It only occurred when running on Azure.

**Comment by livarcocc** [comment]
I would file a new issue on dotnet/corefx for it.
