### ISSUE TITLE
[Perf] Use read and write on JObject directly

### ISSUE THREAD

**Issue by JamesNK** [dotnet/cli#2782]
https://github.com/dotnet/cli/blob/eb793c5cf85b2c6f611db7b7542a6651a863d9fd/scripts/dotnet-cli-build/Utils/JsonUtils.cs

Change these helper methods to use JObject.Load and JObject.WriteTo. They're what JsonSerializer uses internally with JObject.

Edit: Also use WriteTo here - https://github.com/dotnet/cli/blob/91fb67835d11f60bbe4763f0de6d3859236cb07a/src/dotnet/commands/dotnet-build/IncrementalCache.cs#L36

**Comment by brthor** [comment]
Putting this to RTM, as it is not a current blocker.

**Comment by livarcocc** [comment]
We are currently not using this anymore.
