### ISSUE TITLE
[Perf] Use JObject.Load instead of JObject.Parse

### ISSUE THREAD

**Issue by JamesNK** [dotnet/cli#2783]
https://github.com/dotnet/cli/blob/91fb67835d11f60bbe4763f0de6d3859236cb07a/src/dotnet/commands/dotnet-build/IncrementalCache.cs#L61

This is unnecessarily loading the string into memory. Use JObject.Load with the StreamReader.

Edit: Also here - https://github.com/dotnet/cli/blob/ac4c6702d5d345dc9c397f80290f105fedebe98b/src/Microsoft.DotNet.ProjectModel/RuntimeConfig/RuntimeConfig.cs#L40

And here - https://github.com/dotnet/cli/blob/ed05e164fbe0f046de53d7ccab343ec562bb107f/src/Microsoft.DotNet.ProjectModel/GlobalSettings.cs#L70

**Comment by brthor** [comment]
Putting this to RTM, as it is not a current blocker.
