### ISSUE TITLE
[Perf] Use System.Buffers with Json.NET

### ISSUE THREAD

**Issue by JamesNK** [dotnet/cli#2784]
Anywhere JSON is being read or written can be updated to use System.Buffers. It will avoid allocating the buffer arrays that JsonTextReader and JsonTextWriter use internally.

http://james.newtonking.com/archive/2015/12/20/json-net-8-0-release-1-allocations-and-bug-fixes

**Comment by JamesNK** [comment]
Example: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonOutputFormatter.cs#L98

**Comment by brthor** [comment]
Putting this to RTM, as it is not a current blocker.

**Comment by livarcocc** [comment]
@JamesNK Are you going to provide a real implementation of IArrayPool? Or should we just copy your fake one and use it? Is that even enough?

**Comment by JamesNK** [comment]
Up to you to provide an implementation

**Comment by livarcocc** [comment]
We have since removed usages of NewtonSoft.Json from the CLI.
