### ISSUE TITLE
[Perf] Consider using JsonTextReader and JsonTextWriter

### ISSUE THREAD

**Issue by JamesNK** [dotnet/cli#2785]
There are places where JSON is being loaded into a JObject and then the JObject is being read to return a strongly typed class.

e.g. https://github.com/eerhardt/cli/blob/77da06b392190b1a952fd299236505f989d92f25/src/Microsoft.DotNet.ProjectModel/Graph/LockFileReader.cs

Using JsonTextReader to build the strongly type class will save allocating the intermediary JObject.

In cases where JSON is being written, JsonTextWriter can be used directly rather than creating a JObject and then writing that, again saving allocating intermediary objects.

**Comment by brthor** [comment]
Putting this to RTM, as it is not a current blocker.
