### ISSUE TITLE
Switch to Running Performance Tests via Dotnet Test

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2786]
For RTM, we'd like build and run of performance tests to occur via the dotnet test mechanism rather than a scripting layer on top.

This issue tracks switching the dotnet CLI performance tests to use this instead of the current python script.

**Comment by livarcocc** [comment]
The performance tests have been removed from the CLI, as we though they didn't make much sense anymore given that the logic is now in MSBuild/SDK.
