### ISSUE TITLE
dotnet.exe rc2 build (1.0.0-rc2-002531) doesn't rebuild project upon Source file changes in some cases

### ISSUE THREAD

**Issue by smile21prc** [dotnet/cli#2788]
## Steps to reproduce
1. Create a new dotnet.exe RC2 app, restore and patch workaround NuGet.Config to make it buildable.
2. build the app.
3. Back up Program.cs into backup\Program.cs.
4. Make another copy of Program.cs under changed\Program.cs. Edit the file with notepad, for example, add a dummy function to the class like below:

using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

```
public void test()
{
}
}
```

}
1. Copy changed\Program.cs to overwrite the Program.cs in the app top folder, and rebuild. This time it detects file change and successfully rebuilds, which is correct.
2. Copy backup\Program.cs to overwrite the Program.cs in the app top folder, and rebuild. This time it should rebuild again, while it does NOT.
3. Copy changed\Program.cs to overwrite the Program.cs in the app top folder again, and rebuild. Different from step #5, this time it does NOT rebuild any more.

Seems dotnet.exe has some "memory" on the file. If an individual source file is built once, it's internally marked as "built already", which is what happen in #2 and #5. However, that internal tag is INCORRECT. As step #6 and #7 does NOT rebuild any more, where they should.
## Expected  behavior

Rebuild should be triggered in above step #6 and #7.
## Actual behavior

Rebuild are not triggered in above step #6 and #7.
## Environment data

`dotnet --info` output:

**Comment by brthor** [comment]
Updated title, this seems like a fairly serious issue if we are not rebuilding upon source changes.

**Comment by cdmihai** [comment]
Going to look into it. 

At face value, this might be caused due to how file timestamps are handled by file systems around copying files (not update timestamps):
1) is rebuilt because you changed the file in changed/Program.cs and thus updated the timestamp
2) is not rebuilt because you are copying the file from backup/Program.cs and thus do not get an updated timestamp
3) is not rebuilt because the timestamp from changed/Program.cs is now older than the timestamp of the output files that got built during 1)

**Comment by cdmihai** [comment]
I verified it on Windows and NTFS via the file browser (copy paste, yes to override) and powershell (copy-item). In both cases the file's last modified timestamp is preserved, so file copies in windows on NTFS will cause false negatives with dotnet build's timestamp incremental mechanism

**Comment by blackdwarf** [comment]
@cdmihai would this happen with MSBuild as well?

**Comment by cdmihai** [comment]
@blackdwarf 
Yes, same issue. MSBuild uses timestamp based incrementality, just like old CLI did, so if you do things to your files that does not update the timestamps (like copying and such), then you might get false negatives.

**Comment by blackdwarf** [comment]
@cdmihai should this move to the MSBuild repo then as an issue? Seems like something that, if we indeed do solve it, would be solved at that layer rather than the CLI?

**Comment by cdmihai** [comment]
Yes, the layer at which this would be solved is MSBuild. Created an issue and linked it to this one. Closing this one.
