### ISSUE TITLE
Publish the console host in its own nuget package

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#279]
This is needed for xplat publish. #185 discusses the scenario of publishing for all runtimes when `--runtime` switch is not specified by the user.

**Comment by piotrpMSFT** [comment]
@gkhanna79 this is dependent on the outcome of our host conversations. Assigning to you until that story fleshes out a bit.

**Comment by gkhanna79** [comment]
@piotrpMSFT Is this about the shared host?

**Comment by piotrpMSFT** [comment]
@gkhanna79 yes, this is regarding shared host
@schellap started a conversation about this today. I'm curious if NuGet is really the right answer... Or should these be zip files. Will they really behave like NuGets?

**Comment by gkhanna79** [comment]
What is the design for cross-architecture compilation for CLI as that will influence what this shapes up to be?

**Comment by schellap** [comment]
@anurse, how will you be consuming the host? 

@piotrpMSFT, I asked this mainly for servicing  the host using the dotnet servicing methods.

I am thinking two types of servicing:

1. Explicit COREHOST_LIBPATH to load custom hosts like corerun and also clihost (current host)

2. Use the DOTNET_SERVICING/PackageName/PackageVersion to load a serviced host dll if 1 doesn't exist. PackageName and PackageVersion will be baked into the host at build time.

**Comment by schellap** [comment]
Also, ILC and other folks can start using the unified host without dependency on dotnet through the Nuget package.

**Comment by anurse** [comment]
These really don't sound like NuGet packages, but I am totally in favor of the idea of distributing them as versioned artifacts on a feed that is consumed by the CLI somehow. In general, I don't want to create the impression that an application takes a **dependency** on the host.

I think the best way to do this would be to work out how we will be packaging runtimes (which should **NOT** be in NuGet packages, IMHO ;)), and include the host in that package. That means that for x-plat publishing, you would use `dotnet` CLI commands to fetch and install a runtime package for a different platform and then `dotnet-compile` and `dotnet-publish` can use those.

**Comment by gkhanna79** [comment]
> I don't want to create the impression that an application takes a dependency on the host.

I agree. That said, servicing of the host is independent of how cross-compilation/publishing is going to work. 

Let us use https://github.com/dotnet/cli/issues/438 to discuss how servicing of the host should work and use this to have a base package inplace for the host (something that we can do right now).

**Comment by gkhanna79** [comment]
@Sridhar-MS Can you confirm you still need this issue to be addressed (i.e. need a nuget package for the universal host)?

**Comment by schellap** [comment]
> I don't want to create the impression that an application takes a dependency on the host.

Currently, the app takes a dependency on NETStandard.Library NuGet package which brings in the runtime. We can make an entry for the host nupkg in the standard library package.

@gkhanna79, moving forward, I believe we need the nupkg for both aquisition and servicing. For now, we can assume the host would come from the dotnet CLI, but like @anurse also suggests, it should come from NETStandard.Library just like the CLR.

As far as servicing is concerned, there are two models:
1. DOTNET_SERVICING location to support ASP .NET/CLI servicing models
2. App local copy to support a pull model by the user
3. Lastly, user can themselves replace the corehost.exe as *last resort* from the host nupkg feed.

Cc @ericstj

**Comment by gkhanna79** [comment]
> We can make an entry for the host nupkg in the standard library package.

Host is an implementation detail that shouldn't be reflected in the standard library since it is not part of the library (and we shouldn't use standard library as means to deliver the host).

> it should come from NETStandard.Library just like the CLR.

@anurse Can you please elaborate on why this is required?

**Comment by anurse** [comment]
>> it should come from NETStandard.Library just like the CLR.
> @anurse Can you please elaborate on why this is required?

not really, since I agree with you that it should not be part of the Standard Library, neither should the CLR itself IMO. The runtime (and probably the host) should come using their own packaging mechanism.

**Comment by gkhanna79** [comment]
@schellap What are the next steps on this?

**Comment by schellap** [comment]
@piotrpMSFT could you please move this to RTM? For RC, I am thinking about having the user pull the latest corehost from the dotnet/cli servicing drop.

**Comment by piotrpMSFT** [comment]
This is done.

**Comment by ericstj** [comment]
Are we happy with how this is done?  Right now there is a circular dependency here (CLI repo produces package, corefx consumes it, CLI consumes corefx).
