### ISSUE TITLE
dotnet run throws error in startup.cs

### ISSUE THREAD

**Issue by ibrmohammed** [dotnet/cli#2791]
## Steps to reproduce
did a dotnet restore and a dotnet run.

## Expected  behavior
The application should run successfully

## Actual behavior
the application gets compiled but nothing happens after that
log.txt has the following error

The configuration file 'appsettings.json' was not found and is not optional.   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Aps.Idp.Web.Startup.Main(String[] args) in C:\Users\ibrmohammed\Source\Workspaces\SbmAps\Idp\src\Aps.Idp.Web\Startup.cs:line 32

## More Info
I have observed in cli samples that every project has 2 files program.cs and startup.cs
In my application i have every thing inside startup.cs
Is the folder structure important?

## Environment data
`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/5870046/14933521/d4972146-0eae-11e6-81da-25d48f79b38f.png)

**Comment by kerryjiang** [comment]
It seems your code tried to load a configuration file which doesn't exist.

Add the optional parameter true when you add a configuration file:

`.AddJsonFile($"app.{env.EnvironmentName}.json", optional: true);`

**Comment by brthor** [comment]
This file `appsettings.json` is not a cli artifact. 

You may have a bug in your program, or perhaps it is in the aspnet stack, I haven't seen this file before. 

Closing this out as this is not a cli issue.

**Comment by ibrmohammed** [comment]
I have the connectionstring stored in appsettings.json
I did see in a few latest projects, they are using config.json. Is this what you are expecting to use instead of appsettings.json
