### ISSUE TITLE
latest update breaks publishOptions

### ISSUE THREAD

**Issue by ciel** [dotnet/cli#2793]
## Steps to reproduce
use `dotnet new` to create a new application.
add a file called `config.json` to the root of the application directory.
add the following to the `project.json`
```
  "publishOptions":{
    "files": {
      "include": [
        "config.json"
      ]
    }
  }
```
on the command line, run the following;
`dotnet restore` `dotnet publish`

## Expected  behavior
An output directory should be produced that also contains `config.json`.

## Actual behavior
`config.json` is not copied to the output directory.

## Environment data
`dotnet --info` output:

````
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
````

**Comment by GuardRex** [comment]
@ajaybhargavb You might want to revise this ... https://github.com/dotnet/cli/issues/792#issuecomment-215529055 ... in case someone accidentally comes across that.

We just learned that it should be ...
```json
"publishOptions": {
    "include": [
        "Views", "wwwroot", "Logs"
    ]
},
```
