### ISSUE TITLE
Need to add warnings for content and compile

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/cli#2794]
Using `content` and `compile` in the root of project.json should show deprecated warnings as they have been renamed/moved.

**Comment by brthor** [comment]
@ajaybhargavb Marked as RC2 since the PR is out. Is this intended for RC2?

**Comment by ajaybhargavb** [comment]
Yes it is.

**Comment by ajaybhargavb** [comment]
a4487db94934136d4c787efd5674048ac0cd24b5
