### ISSUE TITLE
the given key was not present in the dictionary

### ISSUE THREAD

**Issue by dmpx** [dotnet/cli#2799]
## Steps to reproduce
dotnet run

## Actual behavior
the given key was not present in the dictionary

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
Version: 1.0.0-rc2-002543
Commit Sha: 38d0c28a1e

Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
RID: win10-x64

**Comment by davidfowl** [comment]
@dmpx you need to provide better steps than this. Where's the repro project?

**Comment by dmpx** [comment]
first: dotnet new
second: dotnet restore
third: dotnet run

project.json file content
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002543"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

error message:
the given key was not present in the dictionary

**Comment by GuardRex** [comment]
@dmpx You probably don't have a default NuGet config in your user profile (e.g., `C:\Users\<USER>\AppData\Roaming\NuGet\NuGet.Config`). Add a `NuGet.config` file to the project ...
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
Also ... change `compilationOptions` to `buildOptions` ... that was just updated but it hasn't hit `dotnet new` outputs yet.

**Comment by brthor** [comment]
Thanks for the report @dmpx 

This is an effect of #656 and will go away after the RC2 release. 

Making the error message better is tracked here: https://github.com/dotnet/cli/issues/2504

Going to close this out for now.

**Comment by licinioamendes** [comment]
Tried the fix @GuardRex and did not work. My projects were working ok until last windows update, maybe something changed.

```
λ dotnet build
Project XXXX.Yyyyy.Api (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling XXXX.Yyyyy.Api for .NETCoreApp,Version=v1.0
The given key was not present in the dictionary.

λ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```
