### ISSUE TITLE
dotnet publish --out parameter doesn't support path that ends with slash

### ISSUE THREAD

**Issue by joperezr** [dotnet/cli#280]
The following fails:
```
> dotnet.exe publish project.json -f dnxcore50 -r win7-x64 -o C:\publishDir\
....
The given path's format is not supported.
```
While if I remove the last backslash it succeeds.
```
> dotnet.exe publish project.json -f dnxcore50 -r win7-x64 -o C:\publishDir
...
Publish succeeded.
```

It's annoying to have to remove the trailing backslash because sometimes you are using properties in a script to pass in as the output path, and since those sometimes get passed in it's annoying that this is a requirement. I would expect the --out param to support both scenarios.

**Comment by piotrpMSFT** [comment]
We need to make sure all of the tools are consistent with this request, not just publish.

**Comment by livarcocc** [comment]
I checked across publish, build and compile. They are all working.
