### ISSUE TITLE
Dotnet restore uses global temporary directory

### ISSUE THREAD

**Issue by Inumedia** [dotnet/cli#2806]
## Steps to reproduce

- Setup Ubuntu 14.04 instance to test on
- Install latest dotnet runtime
- Create new project as root
- Execute `dotnet restore`
- Login as another user
- Create new project as other user
- Attempt to execute `dotnet restore`
- You will see a permission error, attempting to access /tmp/NuGetScratch/lock

## Expected  behavior
`dotnet restore` should work as expected and my project's dependencies should be restored.

## Actual behavior
`dotnet restore` attempts to re-use the /tmp/NuGetScratch/lock causing a permissions error and failing out.

## Environment data
`dotnet --info` output:

(Attempting to run `dotnet --info` yields no helpful information, I ran `dotnet --version`)

`dotnet --version` :
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  N/A

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 Runtime Id:  ubuntu.14.04-x64

**Comment by Inumedia** [comment]
As a note, attempting to run `dotnet restore` with the packages argument still tries to lock the global tmp folder:

`dotnet restore --packages ~/.NuGet` :
log  : Restoring packages for /home/.../builds/aec560d5/0/.../.../project.json...
error: Access to the path '/tmp/NuGetScratch/lock' is denied.

**Comment by brthor** [comment]
Please move this over to https://github.com/nuget/home as we do not control this behavior in the cli. 

dotnet restore simply uses nuget.
