### ISSUE TITLE
Win x64 SDK Installer downloaded version doesn't match repo label version

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2810]
## Steps to reproduce
Download the `.NET Core SDK Installer` (MSI) for Windows x64

## Expected  behavior
Get version -2586
![capture](https://cloud.githubusercontent.com/assets/1622880/14958039/3f13670a-104e-11e6-9cd2-f31e6347d5b9.PNG)

## Actual behavior
Receive version -2543
![capture2](https://cloud.githubusercontent.com/assets/1622880/14958108/8f813f46-104e-11e6-8887-0731476eb195.PNG)

## Environment data
```
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by brthor** [comment]
cc @sokket @Sridhar-MS 

This seems like a potential finalizer issue of some sort.

**Comment by Sridhar-MS** [comment]
This has been fixed with https://github.com/dotnet/cli/pull/2816

**Comment by brthor** [comment]
Can we close this out?

**Comment by Sridhar-MS** [comment]
Lets wait till we get a new build.

**Comment by brthor** [comment]
Wasn't sure who to assign, thanks for reassigning 😄

**Comment by sokket** [comment]
Looks like the version information inside the .version file is correct but the overlay on the svg image is incorrect....looking now

**Comment by sokket** [comment]
Looks like a GitHub caching problem...all the data is correct and we have the right no-cache flags set to prevent caching. Closing as external

**Comment by brthor** [comment]
@sokket Why would the higher version be cached over the lower version? Isn't this the desired behavior?

the weird thing to me is that we are getting a lower msi version than the badge.

**Comment by Sridhar-MS** [comment]
I verified that the latest installer link was indeed pointing to the right version.

**Comment by GuardRex** [comment]
The (even weirder) thing that happened to me was that I came back about an hour ago and the badge was still showing -2586, then I received a -2600 MSI. I just re-checked, and now the badge and MSI do match. Some kind'a funky GH image caching I presume.

I just hope we don't go back to the days of having to always download because whatever is shown isn't the correct version ... or frequently an incorrect version. Perhaps, this issue should simmer (be left open) for anther 24-48 hours just to make sure it's all good.

**Comment by Sridhar-MS** [comment]
GH does cache image a bit aggressively. We do [set](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/Publishing/AzurePublisher.cs#L83) the `no-cache` property in the image header. 

But @piotrpMSFT suggested some time back that
> no-cache is not sufficient. We need to also set etag, expires, or last modified.

**Comment by GuardRex** [comment]
> We need to also set etag, expires, or last modified.

I know that you know: All of which ^^^ GH may ignore. Perhaps better to store the images in Azure where you can be sure they will not be cached.

**Comment by GuardRex** [comment]
Not happening ...

I just tried again ... the label is ... -2600

![capture1](https://cloud.githubusercontent.com/assets/1622880/14970641/68a4e034-1090-11e6-8e28-43cd64685bcd.PNG)

.... the MSI that came down ... -2604

![capture2](https://cloud.githubusercontent.com/assets/1622880/14970647/71b9db0c-1090-11e6-9846-d8ea97be59bd.PNG)

**Comment by sokket** [comment]
Yeah, it looks like it is all 2604 for me on the site, so you're hitting it during the GitHub cache invalidation it seems :(

**Comment by GuardRex** [comment]
Apparently it isn't very long ... it isn't more than an hour or two. Therefore, it's inconsequential to working with the latest bits. I'm good.

**Comment by sokket** [comment]
Cool, thanks for helping us validate everything! :)
