### ISSUE TITLE
Running `dotnet restore` hangs

### ISSUE THREAD

**Issue by DonSchenck** [dotnet/cli#2811]
## Steps to reproduce
`dotnet new`
`dotnet restore`

## Expected  behavior
Packages are downloaded

## Actual behavior
Hangs at first output line `Restoring packages for ....`

## Environment data
`dotnet --info` output:
`.NET Command Line Tools (1.0.0-rc2-002586)

Product Information:
 Version:     1.0.0-rc2-002586
 Commit Sha:  ac5432bff2

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.2
 OS Platform: Linux
 RID:         rhel.7.2-x64`

Note: This is RHEL running in a Hyper-V VM on Windows 10 Professiona.

**Comment by DonSchenck** [comment]
Also;

[dschenck@localhost helloworld_cli]$ cat project.json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002586"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

**Comment by DonSchenck** [comment]
After waiting a long time, this:

error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms.

**Comment by brthor** [comment]
Recommend to check DNS and connectivity from your VM. 

Anyways, this is a nuget issue, please move to https://github.com/nuget/home

Thanks!

**Comment by vmrocha** [comment]
I don't agree that its a nuget issue. I believe that it is more likely that dotnet cli is misusing nuget somehow.

**Comment by stanislavromanov** [comment]
`rm -rf /tmp/NuGet`
`rm -rf /tmp/NuGetSearch`

If this does not help reboot the system.

**Comment by pavlosmcg** [comment]
@stanislavromanov Rebooting (the docker host in this case) did the trick

**Comment by hack2root** [comment]
reboot the system.

problem is that you have max-out to you limit for open handles fordotnet process (build, kesterl, nginx, etc)
