### ISSUE TITLE
Default compiler defines

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/cli#2815]
In previous versions of DNX (and K before) some compiler defines were added automatically (`DNXCORE`, `NET451`, `DNX451`, etc) depending on the framework being compiled for. Is this happening in DotNet CLI and if so, is there a list available?

**Comment by am11** [comment]
Based on https://github.com/dotnet/cli/search?l=csharp&q=NETSTANDARD1+OR+NETCOREAPP&utf8=%E2%9C%93:

>
For library project: `NETSTANDARD1_3`, `NETSTANDARD1_4,`, `NETSTANDARD1_5` etc.
For console project: `NETCOREAPP1_0`, `NETSTANDARD1_3`, `NETSTANDARD1_4` etc.

**Comment by twsouthwick** [comment]
Awesome! Are there plans to add this to the documentation?

**Comment by brthor** [comment]
Yes this is happening in the CLI, there is some algorithm to convert framework names to a define. 

All caps, `.` replaced with `_` IIRC. 

cc @blackdwarf Think we should update this in the docs?

**Comment by blackdwarf** [comment]
The same search now returns only test assets. Also, I'm pretty sure that whatever defines there are in the tools in MSBuild-based world, they would be in the SDK. Closing this and opening dotnet/sdk#694 to track it, if it is valid. Thanks!
