### ISSUE TITLE
dotnet-test runs tests per lock file target instead of per framework

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2817]
## Steps to reproduce

Noticed this as part of fixing updating coreclr.xunit. 
1. Restore a test project targeting `netcoreapp1.0` and `net451` with `--infer-runtimes`
2. Run `dotnet test`
## Expected  behavior

Test runs once per TFM
## Actual behavior

Test runs 3 times (twice for `netcoreapp1.0` and once for `net451`. 

When I debugged this, `BuildWorkdSpace.GetProjectContextCollection(projectPath).FrameworkOnlyContexts` contained 3 items.
## Environment data

`dotnet --info` output:
dotnet version: 1.0.0-rc2-002586

**Comment by pranavkm** [comment]
cc @anurse \ @pakrym

**Comment by brthor** [comment]
@pranavkm This doesn't seem like it's breaking anything so bumping out to RTM, please comment if you feel it should be in RC2.

**Comment by pranavkm** [comment]
RTM should be fine.

**Comment by anurse** [comment]
I actually think I ran into something similar and might be fixing it as part of #2818. So we should come back and check on this when we have a build with that change in it.

**Comment by piotrpMSFT** [comment]
This was an issue with the project.json-based `dotnet test`. We're not seeing this anymore since moving to csproj/vstest implementation.
