### ISSUE TITLE
Add remote source code support to dotnet-publish

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#282]
Something like 
>dotnet publish https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Cli/project.json

This should compile and publish the binaries similar to local source code. Also add support for tags/branches to let users point to the latest stable releases.

Developers can just have CLI installed in their production machines and simply publish their latest stable release into that machine.

**Comment by blackdwarf** [comment]
So, essentially, provide support for project.json to be eslewhere and be accessible over network?

**Comment by davidfowl** [comment]
Uh what? I'm not understanding the use case. Publish is about producing deployable bits. It's not responsible for deploying anything

**Comment by blackdwarf** [comment]
The way I understood it is that dotnet publish can access source code artifacts over the network. Deployable bits are produced locally. But, if this is allowed, CLI can be on the prod machine and invoked thus effectivelly using it for a kind of deployment.

**Comment by Petermarcu** [comment]
Sounds like a possible future/backlog item to discuss but not for v1.

**Comment by davidfowl** [comment]
Sounds like it won't work at all. Publish is going to clone the repository, run restore, and publish and expect that to just work?

**Comment by blackdwarf** [comment]
@davidfowl who? Dev? For sure, depending on their code, right? It *could* work if all is well.

**Comment by davidfowl** [comment]
Lots of things could work and lots of things are also theoretically possible with enough code and constraints. This is one of those things that sounds nice but is harder and more error prone than you can imagine.

**Comment by blackdwarf** [comment]
@davidfowl for sure. :)

**Comment by Sridhar-MS** [comment]
@blackdwarf yes, your understanding is right. But apart from this I see more possibilities 
- a developer can just do dotnet-publish on any netcore-based repo and get runnable binaries out of it. No need to download the code and run any custom build scripts. 
- A simplified CI where a developer just needs to run a bunch of dotnet commands like dotnet-restore, dotnet-publish, dotnet-test and dotnet-pack.

@davidfowl I really did not think through the complexities involved. But felt that this feature may help ease the developer workflow. And also as a developer is nuget the only way to publish my package? Can I just use my source code for publishing? Will that help me to ship faster?

**Comment by blackdwarf** [comment]
I don't think we will be doing this any time soon really, so closing.
