### ISSUE TITLE
global.json in same directory as app doesn't override package with sources

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#2823]
## Steps to reproduce
1. Create an application with all files in a single directory (`NuGet.config`, `Program.cs`, `project.json`)
2. `dotnet restore` and `dotnet run` work fine.
3. Add a `global.json` pointing to sources which should override a package.  For example:

```
{
    "projects": [
        "C:/Temp/KestrelHttpServer/src"
    ]
}
```
## Expected  behavior

`dotnet restore` followed by `dotnet run` should build the reference from sources.
## Actual behavior

The reference is still loaded from packages.  The scenario works if `global.json` is placed in the directory above the application.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by blackdwarf** [comment]
In the MSBuild-based world, the `projects` setting in global.json doesn't really have any semantics. Closing this.
