### ISSUE TITLE
dotnet pack doesn't preserve directory structure for included files. 

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#2829]
## Steps to reproduce
Run `dotnet pack` on the below project which has 
```
"packOptions": {
    "files": {
      "mappings": {
        "Templates/": "Templates/"
      }
    }
  }
``` 
https://github.com/prafullbhosale/PackRepro

## Expected  behavior
The generated nupkg has the directory structure 

```
/Templates
      |__ Folder1
                |__File.txt
      |__ Folder2
                |__File.txt
```

## Actual behavior
```
/Templates
      |__File.txt
      |__File.txt
```

## Environment data
`dotnet --info` output:

```
D:\Projects\pack>dotnet --info
.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@prafullbhosale what is this blocking? Do you think this should hold back RC2? Why is the bug coming so late?

**Comment by pranavkm** [comment]
We switched from using `packInclude` to `packOptions` today. This was discovered as part of the issue. With the incoming change to add additional warnings (https://github.com/dotnet/cli/commit/241175dcc398170d328358235ecc47c3fc7ff59a), there would be no way to avoid the warnings unless the issue is addressed.

**Comment by pranavkm** [comment]
We're working around the issue by switching back to `packInclude` in places that use globbing patterns.

**Comment by piotrpMSFT** [comment]
Ok, so we can move this to rtm?

**Comment by ajaybhargavb** [comment]
Another workaround for this without switching back to `packInclude` is to add a mapping for each folder. So for the above example,
```json
"packOptions": {
    "files": {
      "mappings": {
        "Templates/Folder1/": "Templates/Folder1",
        "Templates/Folder2/": "Templates/Folder2"
      }
    }
  }
```

**Comment by piotrpMSFT** [comment]
Since we have ample workarounds, putting in rtm milestone.

**Comment by prafullbhosale** [comment]
Thanks, I removed the blocking-partner label.

**Comment by pranavkm** [comment]
@ajaybhargavb - also noticed that this affects symbol package creation when we use globbing patterns in compile include. Could you make sure that you verify that's also covered when you sort this out?

**Comment by ajaybhargavb** [comment]
Spoke to @pranavkm. Symbol packages have been using the wrong folder structure before the schema changes and using compile include actually fixes the problem but also breaks the assumptions. So no change is currently needed for this other that to add a test to verify this scenario. I'll file an issue in repos that need to be updated to use the new structure.
