### ISSUE TITLE
Create Test for Full Workflow after Build

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#283]
In our builds today, even though we are self-hosted we primarily exercise `dotnet-compile` and `dotnet-restore`. After the build we run a simple smoke test which only exercises the same two commands. 

We should create a test which exercises the mainline suite of commands we expect to be available. The workflow would look like this:

1. dotnet init
2. dotnet restore
3. dotnet compile
4. dotnet compile --native
5. dotnet compile --native --cpp
5. Verify Managed and Native outputs run correctly
6. dotnet publish
7. Verify publish outputs run correctly
8. dotnet pack

Any thoughts or suggestions?

/cc @piotrpMSFT @schellap @krwq

**Comment by krwq** [comment]
Ideally it would be nice to use our own stack to implement this although that would be a bad proof that the stuff is working without any prior simple validation. I think we should at minimum create some simple shell script which tests some simple proof that we are working. Something like that (I don't know if errorlevel would be set when command not found):
```
dotnet
REM if %errorlevel% != 0 then echo "Test Failed" && exit 1
mkdir test1
dotnet init
REM if %errorlevel% != 0 then echo "Test Failed" && exit 1
dotnet restore
REM if %errorlevel% != 0 then echo "Test Failed" && exit 1
dotnet run > out.txt
REM if %errorlevel% != 0 then echo "Test Failed" && exit 1
if content_of_out.txt != "Hello World!" then echo "Test Failed" && exit 1
```

**Comment by brthor** [comment]
@krwq I think we are on the same page. Let me know if that's not true.
