### ISSUE TITLE
windows x64 .net core installer cli version doesn't match install version

### ISSUE THREAD

**Issue by Varorbc** [dotnet/cli#2830]
## Steps to reproduce
install dotnet-win-x64.latest.exe(1.0.0-rc2-002609)
dotnet --info

## Expected  behavior
cli version is 1.0.0-rc2-002609

## Actual behavior
cli version is 1.0.0-rc2-002372

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002372)

Product Information:
 Version:     1.0.0-rc2-002372
 Commit Sha:  bde7d72b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14295
 OS Platform: Windows
 RID:         win10-x64

**Comment by 717009629** [comment]
Maybe you have another dotnet  in diffrent path.  
you can try to enter "where dotnet" in CMD.

**Comment by Varorbc** [comment]
@717009629 Thank you,i find at C:\Program Files\dotnet\sdk have two versions of the command line tool,maybe the last uninstall and residue

@piotrpMSFT If you can support the update command instead of downloading and installing each time

**Comment by piotrpMSFT** [comment]
@Varorbc can you share the contents of your C:\Program Files\dotnet\sdk directory? Specifically, what versions do you see? Unless you have a global.json file that specifies an sdkVersion, you should see the latest dotnet [e.g. highest version] win.

**Comment by piotrpMSFT** [comment]
@Varorbc I just tested this with two recent installers [2611 and 2668] and did not repro the issue. If you're still seeing this with recent builds then please open a new issue. Closing no-repro for now.
