### ISSUE TITLE
Add support to consume JIT Nuget package

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#2831]
We intend to load the JIT dynamically, as opposed to static linking, for the defaults. Thus, the following needs to happen:

1) CLI will need to be updated to consume the same when it invokes crossgen to precompile the SharedFX

2) SharedFX Meta package would need to be updated to ensure it carries clrjit.dll

3) Publish of standalone application also publishes clrjit.dll

CC @schellap @piotrpMSFT @pgavlin @russellhadley

**Comment by gkhanna79** [comment]
Doing this change also depends upon whether we are picking up the new build pipeline (which publishes CoreCLR package that depends upon JIt package) or using the Closed build for rtm (which carries JIT inside coreclr package).

**Comment by gkhanna79** [comment]
@markwilkie Do we have clarity on whether we will be using the new build pipeline or the closed build?

**Comment by gkhanna79** [comment]
@piotrpMSFT @Sridhar-MS Have you picked up post-RC2 SharedFW package within CLI?

**Comment by markwilkie** [comment]
@gkhanna79, yes - we should use the new build pipeline if at all possible.  Confirming that this is a CoreCLR pipeline update?  I'm not 100% sure the status of that bringup by Wil.  We are wanting to switch over to the new pipeline for CoreFx today, and intend to have a good tested build by Monday assuming the product and tests build at all after forking.  (We are also building from TFS over the weekend as a backstop)

cc @weshaggard

**Comment by gkhanna79** [comment]
@schellap This also requires the host to be updated to pass the JIT path to the runtime if there is a case of loading CoreCLR when clrjit is *not* next to it. See https://github.com/dotnet/coreclr/commit/2385b697ea4eeaa7314fafd32415e943601211cf#diff-6202e77c14df46ab42fe3b629083b3a9 for details.

**Comment by gkhanna79** [comment]
@schellap Is this addressed?

**Comment by schellap** [comment]
This is addressed, yes, left it open for end to end validation to go through.

**Comment by eerhardt** [comment]
The Crossgen change has been address in both core-setup and CLI repos.  See:

https://github.com/dotnet/core-setup/pull/106/commits/a2857af7e34d5b2fceb2cdc5ea6c3b46a6f3e6d6
and
https://github.com/dotnet/cli/pull/3425/commits/82ef0304bb2289f36a18c718b3e9f07d01992115

**Comment by gkhanna79** [comment]
Thanks @eerhardt. Is there anything outstanding for this issue?

**Comment by eerhardt** [comment]
The only thing that I can think of is @schellap's comment above for end to end validation.

@schellap has this occurred?

**Comment by piotrpMSFT** [comment]
@schellap?

**Comment by schellap** [comment]
Closing... since CLI is consuming the rc3 bits with this change.
