### ISSUE TITLE
Update CLI Branding and Versioning

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#2833]
Update CLI version numbers and branding strings.

## THIS IS A BREAKING CHANGE
Anyone testing with an older build of CLI may be broken by this change. The SDK version is moving from `rc2` to `preview1`, a lower preview version string. Please uninstall/delete any older installation of dotnet prior to using a new version that includes this change.

Also note that folks depending on CLI-produced NuGet packages will be affected. Tools NuGet packages will also be affected. Anyone depending on `1.0.0-*` version of CLI produced NuGet packages will need to include the updated version suffix e.g. `1.0.0-preview1-*` to get the latest packages. See the table below for details.

### Branding changes
- Microsoft .NET Core SDK --> Microsoft .NET Core 1.0 RC2 - SDK Preview 1
- Microsoft .NET Core --> Microsoft .NET Core 1.0 RC2 - Runtime
- Microsoft .NET Core Host --> Microsoft .NET Core 1.0 RC2 - Host

### Versioning changes
The version update is less straightforward. The Shared Framework and its dependencies will remain RC2. The ProjectModel and its dependencies will also remain RC2. The remaining packages produced in this repo, namely the CLI and its dependencies, will have their version updated to `preview1`.

| Component | Old Ver Suffix | New Ver Suffix |
| ------------- | ------------- | ------------- |
| Host | rc2  | rc2 |
| Shared Framework  | rc2  | rc2 |
| SDK | rc2 | preview1 |
| dotnet-compile-fsc.nupkg | rc2 | preview1 |
| Microsoft.DotNet.Cli.Utils.nupkg | rc2 | preview1 |
| Microsoft.DotNet.Compiler.Common | rc2 | preview1 |
| Microsoft.DotNet.Files | rc2 | preview1 |
| Microsoft.DotNet.InternalAbstractions | rc2 | rc2 |
| Microsoft.DotNet.ProjectModel | rc2 | rc2 |
| Microsoft.DotNet.ProjectModel.Loader | rc2 | preview1 |
| Microsoft.DotNet.ProjectModel.Workspaces | rc2 | preview1 |
| Microsoft.Extensions.DependencyModel | rc2 | rc2 |
| Microsoft.Extensions.Testing.Abstractions | rc2 | preview1 |

**Comment by piotrpMSFT** [comment]
@Sridhar-MS let's use this bug to track adding `1.0.0-rc2` feature key to the MSI. We won't rev the NuGet Version Numbers.

**Comment by schellap** [comment]
`1.0.0-rc2` is SemVer < `1.0.0-rc2-*`, I suggest 1.0.0-rz2 :wink: or something like `1.0.0-rc2-final`

**Comment by piotrpMSFT** [comment]
;)

**Comment by piotrpMSFT** [comment]
Will be fixed by https://github.com/dotnet/cli/pull/2877

**Comment by Sridhar-MS** [comment]
> Microsoft .NET Core SDK --> Microsoft .NET Core 1.0 RC2 - SDK Preview 1

SDK branding still has `RC2`. Should that be dropped?

**Comment by piotrpMSFT** [comment]
no, that is the exact string we want to use.

**Comment by khellang** [comment]
Seriously? What's the reasoning behind this?

**Comment by FransBouma** [comment]
A preview of the **second** release candidate. And not 'the' preview, but the first, so more will follow. Is this the equivalent of a beta of a release candidate? If so, perhaps you guys/gals should look up what the term 'release candidate' is used for ;). 

My suggestion would be to go back to beta -> RC1 -> RCn -> RTM and don't change the world after Beta anymore, so trust in this release policy (if you can call it that) can be restored. I mean... what does 'preview1' even mean? Especially for people who want to start using coreFX when RC2 drops: do they have to wait till the preview days are over and RC2, the GA version that is of RC2, hits the streets? Confusing.

**Comment by CoreyKaylor** [comment]
Or just acknowledge that ship has sailed and there might be many more rc* releases until it's ready.

**Comment by filipw** [comment]
so for example `Microsoft.DotNet.ProjectModel` will be `rc2` but `Microsoft.DotNet.ProjectModel.Workspaces` will be `preview1`, this is quite confusing

**Comment by forki** [comment]
It's not just confusing - it's breaking. 
Just admit the rc mistake and go on with rc3, rc4, ..,  rc5023. It's still better than to break package managers.

**Comment by DamianEdwards** [comment]
My apologies, this change got communicated a little earlier than we intended without the context that it needs. We're working to put together the full communication around these (and related changes) so we can share it (with the required context) in the next few days. Thanks in advance for understanding.

**Comment by enricosada** [comment]
Please use rc2. Or rc4 if rc3 was already used. 
It's ok, it's just a number. 

If you like preview, use `preview` next iteration, after rtm.

But beta -> rc -> rtm it's easy to understand. Preview of what?

**Comment by niemyjski** [comment]
I think you guys should stop being so scared to increment a number suffix and call it beta 3 or rc 3. doesn't make you a failure. increment the number and lets stop confusing end users before we all give up.

**Comment by DamianEdwards** [comment]
While we appreciate the feedback, as I stated above there is some more context coming soon that will hopefully clarify the changes. Until then, might I suggest we leave this issue to track the specific change it was intended to manage, rather than turn it into a general conversation regarding the versioning of .NET Core. Thanks again.

**Comment by ejsmith** [comment]
I don't care what the context is, please don't do this. You're just making a bad situation worse. This is a great product, but people are losing confidence quickly. It's already been like 6 months and a crazy number of breaking changes from "RC1". I know you guys are think that you are going to release RC2 and it will be a real RC, but there have been WAY too many changes to just jump to that. You need to let the community tell you when it's ready and not try to follow some schedule. Start cranking out "RC"s every few weeks until the community is having success with the framework and let that tell you when it should be deemed 1.0.

**Comment by coolcsh** [comment]
Eric, as Damian has said you are not seeing the entire story, just a small piece of something that showed up in GitHub a little too early. We are very aware that the tooling has changed considerably since we shipped the RC1 release and we don't expect it to magically be done overnight. Please wait until we get the blog post out. It will explain the entire state of the project, our upcoming schedule for when and how we plan to release the frameworks and tools.

**Comment by ryzewu** [comment]
I believe that it is necessary to maintain a version of a sexual, it's simple and easy to understand. If changes will seem very confusing. So please do not change, pleading.

**Comment by Varorbc** [comment]
Why not spend more time to fix issues, but to rename and update, please also clear schedule

**Comment by coolcsh** [comment]
Here is the blog post that explains the renaming: https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

**Comment by davidfowl** [comment]
Microsoft.DotNet.ProjectModel -> This should be preview as well, it's all tooling

/cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@davidfowl I'll take this offline with you.
