### ISSUE TITLE
CLI should fail if scripts in the `scripts` section don't exit with code 0

### ISSUE THREAD

**Issue by mcliment** [dotnet/cli#2836]
## Steps to reproduce

Add a scripts section to `project.json` with this content (assuming there's a global npm installed on the system):

```
"scripts": {
    "prepublish": [
      "npm foo",
    ]
  }
```
## Expected  behavior

`dotnet publish` should fail, as it does if the command does not exist. At least optionally. 

If using a CI tool to do the publish and something fails it's difficult to detect.
## Actual behavior

Silently continues the publish process (only shows the errors on std output).
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002611)

Product Information:
 Version:     1.0.0-rc2-002611
 Commit Sha:  bf8f0edd89

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by eerhardt** [comment]
seems like a dupe (or at least highly related to) #443

**Comment by mcliment** [comment]
I agree, probably is the same. Anyway if script support is being dropped, this problem will not exist.

**Comment by piotrpMSFT** [comment]
We're avoiding breaking changes like this for RC2 but I'm adding this bug to RTM.

**Comment by blackdwarf** [comment]
This is a project.json-specific issue. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
