### ISSUE TITLE
dotnet-test attempts to run tests for net451 on Linux \ OSX

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2840]
## Steps to reproduce
1. Create a project that targets `netcoreapp1.0` and `net451`. Add a `testRunner` and `dotnet-test-xunit` as a shared dependency.
2. Restore and run `dotnet test`
## Expected  behavior

Test runs for only `netcoreapp1.0`
Alternatively, test successfully runs for `netcoreapp1.0` and `net451` 
## Actual behavior

Test fails for `net451`:

```
Compiling Microsoft.AspNetCore.Razor.Runtime.Test for .NETFramework,Version=v4.5.1
Compilation succeeded.
    0 Warning(s)
    0 Error(s)
Time elapsed 00:00:04.9572019
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
```
## Environment data

`dotnet --info` output:: `1.0.0-rc2-002543`

**Comment by pranavkm** [comment]
This can be addressed in RTM.

**Comment by natemcmaster** [comment]
I wonder if this is a more general bug. I've hit an issue with `OutputPathCommandResolver`. It tries to look for a command in `bin/$config/$tfm/$rid` when the library is actually in `bin/$config/$tfm`.

**Comment by piotrpMSFT** [comment]
`dotnet test` should not make assumptions about availability of TFMs on given platforms. This can be worked around by passing `-f` for whatever TFMs are desired.
