### ISSUE TITLE
dotnet restore failed on OSX

### ISSUE THREAD

**Issue by mikowiec** [dotnet/cli#2845]
## Precondition
OSX 10.9.2
.NET Command Line Tools (1.0.0-beta-001598)

## Steps to reproduce
- make new test project: dotnet new
  generated files: NuGet.Config Program.cs   project.json
- dotnet restore
  failed, due to not compatible assembly with OSX 10.9

## Actual behavior
log  : Restoring packages for /Volumes/TM/prjTmp/sharpc/photoGalAng2/yo/gal1/project.json...
error: Microsoft.Win32.Primitives 4.0.1-rc2-23811 provides a compile-time reference assembly for Microsoft.Win32.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.AppContext 4.1.0-rc2-23811 provides a compile-time reference assembly for System.AppContext on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Collections 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Collections on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Console 4.0.0-rc2-23811 provides a compile-time reference assembly for System.Console on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Debug 4.0.11-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Debug on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Tools 4.0.1-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tools on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.
error: System.Diagnostics.Tracing 4.1.0-rc2-23811 provides a compile-time reference assembly for System.Diagnostics.Tracing on DNXCore,Version=v5.0, but there is no run-time assembly compatible with osx.10.9-x64.

**Comment by piotrpMSFT** [comment]
1.0.0-beta-001598 is a very old build. We will be updating the LKG link soon. If you want to try out a newer build, you can install from https://github.com/dotnet/cli.

**Comment by mikowiec** [comment]
- Installed .NET CLI 1.0.0-rc2-002659
- make link: ln -s /usr/local/share/dotnet/dotnet /usr/local/bin
➜  clrtest1 dotnet --version
1.0.0-rc2-002659
➜  clrtest1 dotnet new
Created new C# project in /Volumes/TM/prjTmp/sharpc/clrtest1.
➜  clrtest1 dotnet restore
log  : Restoring packages for /Volumes/TM/prjTmp/sharpc/clrtest1/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json 1675ms
Errors in /Volumes/TM/prjTmp/sharpc/clrtest1/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002659)' for '.NETCoreApp,Version=v1.0'.
