### ISSUE TITLE
--build-profile hint text in dotnet is confusing

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#2852]
I happened to run a build with --no-incremental, which included this in the output at the end:

``` console
(The compilation time can be improved. Run "dotnet build --build-profile" for more information)
```

When I saw this, and then ran 'dotnet build --build-profile', I was just informed that my project was up to date. 

While I'm at it, this line:

``` console
Project test (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
```

appears at the beginning of compilation, even if the user passes --build-profile.

Instead of having both messages, how about if the first message just says:

``` console
Project test (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. 
```

and the final message says

``` console
(Incremental build was disabled. Build with the -build-profile argument for more information)
```

**Comment by memark** [comment]
Maybe I'm missing something here. Why is it telling me `Run "dotnet build --build-profile" for more information`, when running that exact command gives me no additional information whatsoever?

**Comment by billwert** [comment]
@piotrpMSFT @cdmihai does this feature even survive into the msbuild implementation? I don't see the option at all in build's code, but I don't know if it got plumbed through in msbuild somewhere as a passthrough.

**Comment by piotrpMSFT** [comment]
This feature is not needed in MSBuild as MSBuild has its own incrementality mechanism which can be diagnosed via `/v:diag` [there is logged output that tells us why incrementality optimizations failed e.g. an input is newer than an output.
