### ISSUE TITLE
Specified mapping of content directories does not match the build and publish outputs

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/cli#2861]
According to https://github.com/aspnet/Announcements/issues/175, I can use `mappings` nodes to specify how my content files are to be placed in the build and publish output. For example, if I want to reference out of directory content, I can specify custom mappings to the output files like so:
```
  "publishOptions": {
    "mappings": {
      "./folder/": "../Resource/folder/",
      "./file.txt": "../Resource/file.txt"
    }
  },
```
This works as expected for individual files but not directories. In my build and publish outputs, I see that the files are located directly beside the executable but the folder still resides under the Resource subdirectory. See below for an example.

## Steps to reproduce
```
git clone https://github.com/JunTaoLuo/ContentFilesRepro
cd ./Project/
dotnet restore
dotnet publish
```
## Expected  behavior
build output structure
```
bin/Debug/netcoreapp1.0
 \-- Project.dll
 \-- file.txt
 \-- folder
    \-- fileInsideFolder.txt
 \-- other files ...
```
publish output structure
```
bin/Debug/netcoreapp1.0/publish
 \-- Project.dll
 \-- file.txt
 \-- folder
    \-- fileInsideFolder.txt
 \-- other files ...
```
## Actual behavior
build output structure
```
bin/Debug/netcoreapp1.0
 \-- Project.dll
 \-- file.txt
 \-- Resource
    \-- folder
        \-- fileInsideFolder.txt
 \-- other files ...
```
publish output structure
```
bin/Debug/netcoreapp1.0/publish
 \-- Project.dll
 \-- file.txt
 \-- Resource
    \-- folder
        \-- fileInsideFolder.txt
 \-- other files ...
```
## Environment data
`dotnet --info` output: 
```
.NET Command Line Tools (1.0.0-rc2-002611)

Product Information:
 Version:     1.0.0-rc2-002611
 Commit Sha:  bf8f0edd89

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

@ajaybhargavb has more details on why this issue is happening

cc @muratg I think we need to fix this for rc2, there is a workaround to specify files instead of directories but it could be infeasible in some cases. Feel free to re-assign the milestone if you disagree.

**Comment by ajaybhargavb** [comment]
This is closely related to https://github.com/dotnet/cli/issues/2829. Fixing this should also fix that issue.

**Comment by piotrpMSFT** [comment]
#2829 is slated for rtm. I'm moving this to the same milestone. @muratg if you think this needs to be in rc2 please put back to that milestone ASAP and ping me.

**Comment by muratg** [comment]
cc @Eilon @danroth27 @DamianEdwards

**Comment by ajaybhargavb** [comment]
b6e3224387e6d66fac982250d88783ae4289657d
