### ISSUE TITLE
Update to Debian 8.4

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#2866]
This is related to https://github.com/dotnet/corefx/issues/8228.  CLI should be updated accordingly as well.  This includes the readme, CI, and Jenkins.

**Comment by livarcocc** [comment]
I don't believe we have explicit work here, really. Please, re-activate if I am mistaken,

**Comment by MichaelSimons** [comment]
@livarcocc, I agree there isn't any explicit work for you.  I will point out however the readme is indicating the builds are happening on `debian 8.2` which technically isn't correct.  Seems like these badges should be updated accordingly.

**Comment by livarcocc** [comment]
@MichaelSimons Jenkins is targeting debian8.2. In VSO we build on docker using the debian:jessie image. What do you expect us to update in the documentation?

**Comment by MichaelSimons** [comment]
@livarcocc,  You have a mismatch IMO.  If you are building with Docker debian:jessie, then I believe you are building on 8.7.  Perhaps changing the badge to Debian 8 would be more appropriate.
