### ISSUE TITLE
Confused about dotnet new --type

### ISSUE THREAD

**Issue by svick** [dotnet/cli#2867]
I'm confused about the option `--type` of `dotnet new`:

* [`dotnet help new`](https://github.com/dotnet/cli/blob/44483dd/src/dotnet/commands/dotnet-new/Program.cs#L86) doesn't say anything about the possible values
* [README.md](https://github.com/dotnet/cli/blob/44483dd/src/dotnet/commands/dotnet-new/README.md#options) says the possible values are `console`, `lib` and `xunittest`
* [the actual possible value](https://github.com/dotnet/cli/blob/44483dd/src/dotnet/commands/dotnet-new/Program.cs#L91-L92) is just `console`

My guess is that `lib` and `xunittest` are planned, but not included yet. Should they be removed from README.md? Or maybe even remove the documentation of `--type` from everywhere for now, since it's not useful?

**Comment by blackdwarf** [comment]
@svick ah, good catch on the README.md. Yes, the only available option is the console. We had an idea of adding more (like the ones you see in there), but `dotnet new` will be redone for RTM so it will be a lot different. You can see how in #2052 .

**Comment by Neutrino-Sunset** [comment]
Why is this closed. Dotnet help new _still_ doesn't give any indication what project types can be created. Shouldn't bugs be closed only when they are fixed?

**Comment by davidfowl** [comment]
It does. 

1.0.0-preview4-004233

```
Davids-MBP-3:~ dfowler$ dotnet new --help
.NET Initializer

Usage: dotnet new [options]

Options:
  -h|--help             Show help information
  -l|--lang <LANGUAGE>  Language of project    Valid values: C#, F#.
  -t|--type <TYPE>      Type of project        Valid values for C#: Console, Web, Lib, Mstest, Xunittest. Valid values for F#: Console, Web, Lib, Mstest, Xunittest.
```
