### ISSUE TITLE
"Project <name> does not have a lock file" when referencing csproj

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#2869]
Duplicating the issue from [here](https://github.com/aspnet/Tooling-Internal/issues/513) because I believe this might be a CLI issue. I can reproduce it (after doing all the repro steps) by running `dotnet build` from the command line

----

[Scenario](https://github.com/aspnet/Release/issues/88) item: xproj -> csproj -> csproj 

Do these steps in VS:

1. Create a dotnet (451) web app
2. Create a classic C# library Lib1
3. Create a second classic C# library Lib2
4. Add a reference from Lib2 -> Lib1
5. Build everything
6. Add a reference from WebApp -> Lib2
7. Restore the packages
8. Build

Expected: everything builds
Actual error: 

```
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Project WebApplication13 does not have a lock file.	WebApplication13	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	241	Build	
```

If you cannot reproduce from the first try, remove the WebApp -> Lib2 reference, restore and then repeat steps 5 -> 8

PS: The lock file exists, I'm not sure why it's not picked up. The 3 files (project, lock, and fragment) are attached: [files.zip](https://github.com/aspnet/Tooling-Internal/files/247878/files.zip)

---

VS: 14.0.25123.00 Update 2
Tooling: 14.1.20425.0
CLI: 1.0.0-rc2-002426

**Comment by brthor** [comment]
We made changes just yesterday related to this scenario, please try with the latest cli.

**Comment by victorhurdugaci** [comment]
What's the build number that has the fix?

**Comment by brthor** [comment]
2665 should have it

**Comment by piotrpMSFT** [comment]
@victorhurdugaci please re-open if this is still an issue in 2665 or later.

**Comment by niemyjski** [comment]
I'm seeing this issue locally, but it's a very simple project.
