### ISSUE TITLE
Successful build despite visible errors

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#287]
I just noticed that in some cases you are getting successful build despite errors.

Here is what I did (not sure if it repros as is):
```
# start from clean repo
build
# change code to not compile in one of the tools
build
# observe error on the console and successful build and a command not in the output
```

**Comment by brthor** [comment]
@krwq What platforms does this repro on?

**Comment by piotrpMSFT** [comment]
yep, can you include a gist with project.json + Program.cs?

**Comment by krwq** [comment]
it's faster to fix than answering these questions:
https://github.com/dotnet/cli/pull/310

**Comment by krwq** [comment]
#310 merged
