### ISSUE TITLE
Installing both 64bit and 32bit versions defaults to 32bit

### ISSUE THREAD

**Issue by jonmill** [dotnet/cli#2881]
## Steps to reproduce
1. Install x64 Core
2. Install x86 Core
3. Run `dotnet`
## Expected  behavior

The `dotnet` command would follow the machine bitness and default to x64 version
## Actual behavior

Defaults to x86 version

**Comment by piotrpMSFT** [comment]
The CLI bitness is selected by the OS before we start executing code. Whatever wins on the PATH wins. We can spend some more time thinking about this in the future but will need to involve more folks from the team as well as from various IDEs.

**Comment by robmen** [comment]
@sokket can you share your PATH environment variable after each installation?

**Comment by livarcocc** [comment]
Closing as this is not something that we would address on the CLI. This support needs to happen in the host. An issue like this belongs in dotnet/core-setup now.
