### ISSUE TITLE
Basic type resolution fails if compat problems are worked around using imports

### ISSUE THREAD

**Issue by bleroy** [dotnet/cli#2882]
## Steps to reproduce

Add a PCL library that is not yet compatible with netstandard, such as JSON.NET 8, add the "imports": ["portable-net40+sl5+win8+wp8+wpa81", "dotnet"] to the project.json.
Using basic types such as object and string fails: it asks for mscorlib to resolve basic types.
## Expected  behavior

The error message identifies the actual cause and provides a suggestion on how to fix.
## Actual behavior

The error message only conveys failure to resolve types through mscorlib, but doesn't explain why nor provides guidance on how to fix.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002543)

Product Information:
 Version:     1.0.0-rc2-002543
 Commit Sha:  38d0c28a1e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@rrelyea @srivatsn is this something that should be addressed in NuGet or in SDK?

**Comment by livarcocc** [comment]
OId project.json bug. Closing.
