### ISSUE TITLE
dotnet should verify parameters before using them

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2883]
dotnet should verify parameters before using them otherwise the errors may be not clear or refer to actual arguments
## Steps to reproduce

```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -c ????
Publishing HelloMvc for .NETCoreApp,Version=v1.0
Illegal characters in path.
Parameter name: path
```

```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -o "c:\temp\publishout???" --no-build -b "C:\temp\buildout???" -c Release
Illegal characters in path.
Parameter name: path
```
## Expected  behavior

dotnet tells exactly which parameter is not correct
## Actual behavior

```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -c ????
Publishing HelloMvc for .NETCoreApp,Version=v1.0
Illegal characters in path.
Parameter name: path
```

`path` does not relate to any argument I provided.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002655)

Product Information:
 Version:     1.0.0-rc2-002655
 Commit Sha:  3e96a05f9c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
If you try this now, this is what you get:

```
C:\Program Files\dotnet\sdk\2.0.0-preview1-005972\Microsoft.Common.CurrentVersion.targets(279,5): error MSB4184: The expression "[System.IO.Path]::GetFullPath(E:\webapp\bin\????\netcoreapp1.1\)" cannot b
e evaluated. Illegal characters in path. Parameter name: path [E:\webapp\webapp.csproj]
```

I believe this is good enough. If you have any concerns, please re-activate.

**Comment by neridonk** [comment]
New update(15.3) vs studio 2017 shows me this

 8/16/2017 12:39:49 PM Error] Illegal characters in path.
[8/16/2017 12:39:49 PM Informational] ========== Discover test finished: 0 found (0:00:00.0875625) ========== 

can anyone tell my why i dont want to cry
