### ISSUE TITLE
Updating dotnet versions on OS X does not upgrade

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#2885]
## Steps to reproduce
1. Have an old version of dotnet (I had beta-001598)
2. Download the new SDK installer + install
3. Restart terminal
4. Run dotnet --version

## Expected  behavior
The new version is displayed

## Actual behavior
The old version is displayed. Running ```ls /usr/local/share/dotnet/sdk``` shows that only the new version is installed

## Environment data
`dotnet --info` output:

jonmill-macbook:~ jon$ dotnet --version
warning: this version of the dotnet tools is using the old layout!
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64

**Comment by piotrpMSFT** [comment]
This is a known issue. Any pre-Shared Framework installers must be removed before a post-shared-framework installer is added. https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/known-issues.md has a pointer to details.

**Comment by brthor** [comment]
Is `1.0.0-beta-001598` pre shared framework? If so, we don't support upgrades. 

Does this repro between later PKGs?
