### ISSUE TITLE
OSX installer does not drop uninstaller

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#2886]
## Steps to reproduce
1. Install OS X SDK
2. Look in the drop folder for an uninstaller
## Expected  behavior

An uninstall script should exist
## Actual behavior

No way to uninstall the OS X installation

**Comment by blackdwarf** [comment]
@sokket what is the form of the uninstaller script? Just a bash script that does what is needed to remove dotnet?

**Comment by sokket** [comment]
A bash script that will remove all the files as well as remove the package from the package listing....or we do the whole /Applications and /Frameworks thing, but that's a bigger change

**Comment by blackdwarf** [comment]
@sokket nope, that is a bigger change. OK, we could do this easily for RTM. In the meantime, there is a workaround, that is, the known issues page lists out stuff to do to uninstall.

**Comment by sokket** [comment]
@blackdwarf the problem with the documentation around using ```pkgutil --files``` is that the file list isn't rooted; meaning the files are all relative to the installation location but the user has no way of finding the installation root without other commands

**Comment by blackdwarf** [comment]
@sokket I will be making a PR to do this as soon as we finish the current work of shipping. So, ideally, I guess, the uninstall script should be placed in the root of the drop folder? Called something like "remove-dotnet.sh" or similar?

**Comment by sokket** [comment]
That would be a good start; there still isn't a good way to find that script though :(

**Comment by blackdwarf** [comment]
@sokket ok, so where should it be then? Would symlinking it to `/usr/local/bin` help?

**Comment by sokket** [comment]
That would help on Ubuntu...on OS X I'm not entirely sure where would be a good place for it. Maybe in the User's Applications folder?

**Comment by blackdwarf** [comment]
Well...there is another option. We put everything in the `/etc/paths.d` anyway, so that means that users will be able to invoke it from wherever. We document the command in the installer and the rest of the docs. Then it doesn't matter where it lives.

Applications are "ok" I guess, though I don't know what is the policy for shell scripts in that dir/

**Comment by blackdwarf** [comment]
@sokket thoughts? I want to maybe tackle this soon...

**Comment by sokket** [comment]
Sure, whatever we can do to make it easily discoverable and allow people to remove us from their system easily

**Comment by livarcocc** [comment]
I am going to close this issue as this is something we haven't had customers ask for so far. If that changes, we can revisit.
