### ISSUE TITLE
Need Project System API for filtering project.json build-type dependencies out.

### ISSUE THREAD

**Issue by mlacouture** [dotnet/cli#2888]
This is for the WCF Connected Service, a VS extension for adding SOAP service references (client proxy code) to Net Core projects.  Types from the project dependencies are considered when generating the proxy code.  The extension uses the Project System API to get the list of project dependencies (IFrameworkReferences.References), the problem is that build-time dependencies are included in the list and there is no way to filter them out because it is a list of strings.
## Environment data

`dotnet --info` output:

**Comment by piotrpMSFT** [comment]
@troydai let's try getting this into RTM?

**Comment by troydai** [comment]
@mlacouture do you have a work around for this issue?

**Comment by mlacouture** [comment]
@troydai - yes, but it is very ugly, do you have an ETA for a fix? thanks

**Comment by piotrpMSFT** [comment]
The work is scheduled for tools rtm.

**Comment by troydai** [comment]
I would recommend close this as well since we're going to change the direction of tooling interface. /cc @piotrpMSFT .
