### ISSUE TITLE
dotnet-publish: Unknown runtime identifier

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#289]
I am trying to run `dotnet-publish.exe` to build my .NET Core project, but no matter what I runtime argument I pass to it, it keeps saying "Unknown runtime identifier" and exits immediately. I have tried `win7-x64`, `ubuntu.14.04-x64`, and `osx.10.10-x64`; none of them works. Why does this happen?

(I am running the version of dotnet-cli available from the MSI installer on the repo home page, if it helps.)

**Comment by wjk** [comment]
In perusing the documentation in this repo, I find no mention of `dotnet-publish.exe`. This makes me think that this feature is not yet fully implemented. Unfortunately, I cannot build my project correctly without this feature. @Sridhar-MS @piotrpMSFT Any clue as to why this is happening? Thanks!

**Comment by davidfowl** [comment]
Nothing is fully implemented yet.

**Comment by Sridhar-MS** [comment]
@wjk This is still a work in progress very much. Can you let me know if you also specified the right `--framework` parameter too? We are also tracking an issue #185 where we are making `runtime` and `framework` parameters optional.

There is documentation for publish [here](https://github.com/dotnet/cli/tree/master/src/Microsoft.DotNet.Tools.Publish/README.md).

**Comment by wjk** [comment]
I am using the value `coreclr` for `--framework`. I assume that’s correct, as I have seen no documentation to the contrary. Also, that README you linked is where I found the runtime identifiers I listed above as nonfunctional.

**Comment by Sridhar-MS** [comment]
`--framework` input must be a [framework]((https://github.com/aspnet/Home/wiki/Project.json-file#frameworks)) targeted in your project.json. For example - `dnx451` or `dnxcore50`. 

But I understand that the error message is misleading.

**Comment by wjk** [comment]
Using `dnxcore50` as the `--framework` input fixed it for me. Thanks! However, even though `dotnet publish` completes successfully, the CoreCLR native runtime files are not copied to the output directory, as far as I can tell. Is this supposed to happen? (My guess is that it isn’t, based on the information in that README linked above.)

**Comment by wjk** [comment]
Note that the program will still run as long as the `DOTNET_HOME` environment variable is set.

**Comment by brthor** [comment]
@wjk Do you reference the Nuget Package `Microsoft.NETCore.Runtime` in your project.json ? This is the dependency for CoreCLR runtime files

**Comment by Sridhar-MS** [comment]
`dotnet publish` is just going to copy all the dependencies found in the project.json. If you want the CoreCLR native runtime files to be published you need to add `Microsoft.NETCore.Runtime` as a dependency in your project.json.

**Comment by wjk** [comment]
@brthor That did it. All needed dependencies are now copied. Thank you!

**Comment by piotrpMSFT** [comment]
@blackdwarf it looks like the docs might have a gap. Can you take a look?
