### ISSUE TITLE
Version range for dependencies produced by dotnet-pack should use legacy format

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2893]
`dotnet pack` takes a dependency of the format `ClassLibrary: "1.0.0"` and embeds it in the nuspec in the format `<dependency id="ClassLibrary" version="[1.0.0-build-1000, )" />`. Although this is correct, it's more common to represent this as `<dependency id="ClassLibrary" version="1.0.0-build-1000" />`

**Comment by pranavkm** [comment]
cc @emgarten

**Comment by piotrpMSFT** [comment]
dotnet-pack is going to be replaced by nuget pack, similarly to how restore works today. We're not making further investments in dotnet-pack, so closing this issue.
