### ISSUE TITLE
NuGet packages created with dnu pack --out option are not visible when added to another project

### ISSUE THREAD

**Issue by okutlubay** [dotnet/cli#2905]
I have a ps script that packs all the projects in the solution and sends to nuget server. And a separate project references them in the project.json. The command I use is:
`dnu pack --configuration Release`
This creates all the output `.nupkg` files under `($projectDir)\bin\Release` folder.

I then decided to consolidate all output under `($solutionDir)\artifacts\Release` folder. So I changed my script to:
`dnu pack --configuration Release --out "$solutionDir\artifacts"`

Now, interestingly, this creates the `.nupkg` files inside the desired folder. When I add the reference (with the correct version number) to other project and run `dnu restore`, it adds the references (no errors or whatsoever; besides, I can see them inside the References folder in the Solution Explorer, all look fine). But when I try to add it in my code (i.e using `CompanyName.MyPackage` etc), it does not recognize.

And again; the only difference is the `--out` parameter in the `dnu pack` command. Everything else is same.

Am I missing something or may this be a bug?

**Comment by brthor** [comment]
@okutlubay 

We appreciate the issue, but `dnu` is a separate product than the one in this repo. 

Could you please try installing the `dotnet` cli, trying out with `dotnet pack` and reopening if you still find issues 😄

**Comment by okutlubay** [comment]
Oh, snap. I Sorry about bringing this issue to the wrong place. So; can this new tool compile dnx46 framework projects?

**Comment by brthor** [comment]
I haven't personally seen the tfm `dnx46` used, but that doesn't mean it won't work :) It all depends on the packages. 

There is another moniker `net46` which may be equivalent.

**Comment by okutlubay** [comment]
thanks alot.
