### ISSUE TITLE
Grammar bug in CLI output

### ISSUE THREAD

**Issue by brendandixon** [dotnet/cli#2907]
## Steps to reproduce
- Compile anything
- Read the message

## Expected  behavior
`Project <redacted> (.NETCoreApp,Version=v1.0) will be compiled because some of its dependencies changed`

The message should use "its" vs. the contraction "it's".

## Actual behavior
`Project <redacted> (.NETCoreApp,Version=v1.0) will be compiled because some of it's dependencies changed`

## Environment data
.NET Command Line Tools (1.0.0-rc2-002468)

Product Information:
 Version:     1.0.0-rc2-002468
 Commit Sha:  a2f3c531fb

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by piotrpMSFT** [comment]
Great catch!

**Comment by livarcocc** [comment]
This is the current message:

```
Project Microsoft.DotNet.Cli.Utils (.NETFramework,Version=v4.5.1) will be compiled because dependencies changed
```
