### ISSUE TITLE
The exception for invalid paths in project.json is too generic

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2910]
## Steps to reproduce

Use the following `include` `publishOptions`:

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views", 
      "a>bc"
    ]
  },
```
## Expected  behavior

```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -f net451
Illegal characters in path.
Parameter name: path
```
## Actual behavior

The error message should say that the error is in project.json in the publishOptions section (ideally should also point to the property name and call out the value).
## Environment data

`dotnet --info` output:
1.0.0-rc2-002670

**Comment by blackdwarf** [comment]
This does not repro in the latest msbuild-based tooling. An appropriate error is thrown that there are illegal characters in the path. Closing.
