### ISSUE TITLE
dotnet publish should copy empty folders if they are specified in the include and exist on the disk

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2911]
## Steps to reproduce

If you include an empty folder in the publish options but the folder on the disk is empty it is not published.

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views", 
      "logs/"
    ]
  },
```
## Expected  behavior

Empty folders are published. 

This is very useful when you want to enable logging in IIS. IIS by default won't create a folder for you so even if logging is enabled no logs are written. Creating a log folder in the app and publishing it with the app makes the life of a developer easier - they don't have to go to the application and create the folder for logs each time the application is published.
## Actual behavior

The folder is not published.
## Environment data

`dotnet --info` output:

```
1.0.0-rc2-002670
```

**Comment by GuardRex** [comment]
@moozzyk Beat you to it bro ... dup of https://github.com/dotnet/cli/issues/1396

**Comment by blackdwarf** [comment]
With the move to MSBuild, the way data files are copied during build is governed by their behavior. I've opened a new issue on their repo (Microsoft/msbuild#1586) to track this. Will close this one. Thanks!
