### ISSUE TITLE
Building an app using dotnet cli without Microsoft.NETCoreApp dependency

### ISSUE THREAD

**Issue by dsgouda** [dotnet/cli#2913]
## Steps to reproduce

When trying to build an app with an entrypoint using the minimum set of dependencies (NETStandard.Library instead of the whole Microsoft.NetCoreApp), dotnet cli generates the following error

```
Can not find runtime target for framework '.NETStandard,Version=v1.3' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
```

A sample project.json looks like:

```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-23931"
  },
  "frameworks": {
    "netstandard1.3": {  }
  },

}

```
## Expected  behavior

dotnet cli should be able to generate a cross-plat dll with an entrypoint 
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002520)

Product Information:
 Version:     1.0.0-rc2-002520
 Commit Sha:  7c504b2456

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

cc: @lt72

**Comment by piotrpMSFT** [comment]
@blackdwarf @gkhanna79 @glennc can you guys weigh in on this one? Enabling the creation of libraries with emitEntryPoint seems quite reasonable and enables app entry points to come in as dependencies instead of having to be the core application itself. 

However, I'm concerned that the library produced can be expected to be a runnable application though its dependency closure is not sufficient to actually produce a runnable output.

What are your thoughts?

**Comment by blackdwarf** [comment]
@piotrpMSFT yeah, this is interesting. If we believe that the scenario is worthwhile, then guidance should be that these artifacts are not runnable and should not be ran on their own. Of course, that could lead to some confusion.

**Comment by glennc** [comment]
We talked once about making emitEntryPoint automatic. Did we decide not to do that for a reason?

**Comment by blackdwarf** [comment]
@glennc I thought that is a thing that needs Roslyn work, no?

**Comment by livarcocc** [comment]
I don't believe this applies to MSBuild anymore.

Now, you can determine that through the OutputType: exe. Though, you will need to reference Microsoft.NetCore.App to make it work for Core.
