### ISSUE TITLE
dotnet publish should warn if include globbing patterns did not catch anything

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2914]
## Steps to reproduce

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views", 
      "abcdef"
    ]
  }
```

`abcdef` does not exist on disk. 
## Expected  behavior

A warning saying that no files/folders were found for this pattern. It would be useful to catch typos or incorrect globs after the application was restructured but before it is deployed/run
## Actual behavior

No warning.
## Environment data

`dotnet --info` output:

```
1.0.0-rc2-002670
```

**Comment by andschwa** [comment]
Just a heads up: this cannot be fatal. We use `*.so` and `*.dylib` to pick our libraries, one of which will not glob anything depending on if we're building and publishing on Linux or OS X. I think a warning is fine, but it must not be a fatal error.

**Comment by GuardRex** [comment]
btw - If an engineer is sitting down to do this one, perhaps, a fix for https://github.com/dotnet/cli/issues/1396 could be squared away at the same time?

**Comment by blackdwarf** [comment]
This is project.json specific issue. In MSBuild-based tools, we are beholden to whatever MSBuild does with the globs. If this issue is to be raised in that case as well, I guess it should be raised directly to MSBuild on Microsoft/MSBuild. Will close this one therefore.
