### ISSUE TITLE
Unable to resolve 'Microsoft.NETCore.App on OSX

### ISSUE THREAD

**Issue by mikowiec** [dotnet/cli#2917]
## Precondition
OSX 10.9.2
.NET CLI 1.0.0-rc2-002659

## Actual behavior
- Installed .NET CLI 1.0.0-rc2-002659
- make link: ln -s /usr/local/share/dotnet/dotnet /usr/local/bin
➜  clrtest1 dotnet --version
1.0.0-rc2-002659

## Steps to reproduce
- make new test project: dotnet new
  generated files: NuGet.Config Program.cs   project.json
- dotnet restore
     error result obtained.

log  : Restoring packages for /Volumes/TM/prjTmp/sharpc/clrtest1/project.json...
Created new C# project in /Volumes/TM/prjTmp/sharpc/clrtest1.
➜  clrtest1 dotnet restore
log  : Restoring packages for /Volumes/TM/prjTmp/sharpc/clrtest1/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json 1675ms
Errors in /Volumes/TM/prjTmp/sharpc/clrtest1/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002659)' for '.NETCoreApp,Version=v1.0'.

**Comment by BeelzeBu** [comment]
which nuget packages are you using? please post your Nuget.config

**Comment by mikowiec** [comment]
I've created the test project with "dotnet new" command. There are 2 files: Program.cs and project.json

--------------
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002659"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

"Nuget.config"  not created

**Comment by dasMulli** [comment]
You need to create a NuGet.config to use the CI builds. See https://github.com/dotnet/cli/issues/2545#issuecomment-211062041

**Comment by mikowiec** [comment]
created "NuGet.config"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        
        <clear/>
        <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"/>
        <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json"/>
    </packageSources>
</configuration>

-------------------------------
Installed:
    113 package(s) to ....../clrtest2/project.json

➜  clrtest2 dotnet build
Project clrtest2 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling clrtest2 for .NETCoreApp,Version=v1.0
......./clrtest2/project.json(3,26): warning DOTNET1015: The 'compilationOptions' option is deprecated. Use 'buildOptions' instead.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

➜  clrtest2 dotnet run
Project clrtest2 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hello World!

-------------------------------------
Thanks, it works fine.

Please, tell me, can be build this little project to ".exe" file?
I see ".dll" extension only, for build and publish commands.

It'is not possible to run "dot net clrtest.dll" without clrtest2.runtimeconfig.json file.

 "publish       Publishes a .NET project for deployment (including the runtime)"
I've performed "dotnet publish", but runtime not linked to target .dll
Is it possible to publish this project correct?

**Comment by dasMulli** [comment]
To publish a standalone app (including all dependencies), you need to remove the `"type": "platform"` part from the `Microsoft.NETCore.App` dependency and add a runtime section like the following to the root level of project.json:

```json
  "runtimes": {
    "osx.10.10-x64": {}
  }
```

then when you publish (e.g. `dotnet publish -r osx.10.10-x64`) it should put an OS X executable into `bin/Debug/netcoreapp1.0/osx.10.10-x64/publish` (no `exe` extension - that you would get with a windows runtime like `win7-x64`).

**Comment by piotrpMSFT** [comment]
Thanks for resolving this issue, folks!
