### ISSUE TITLE
buildOptions>platform bitness mismatch with self-contained publish RID will compile/publish but will fail to run

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2922]
## Steps to reproduce
1. Add `"platform": "x86"` to `buildOptions`
2. Set the RID to a different bitness ... e.g, `x64` flavor RID, `win81-x64` in my case
3. Restore
4. `dotnet publish -r win81-x64`
5. Deploy
## Expected  behavior

At least a warning that this is going to fail ... but probably an error should be produced at compile/publish.
## Actual behavior

Application successfully compiles/publishes. When you deploy the app, :boom: ...

Browser:

```
No response until the request times out.
```

ANCM Log: 

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 
'teststandalone.dll' or one of its dependencies. An attempt was made to load a program with 
an incorrect format.
```

Application log (via Event Viewer): 

```
Faulting application name: teststandalone.exe, version: 0.0.0.0, time stamp: 0x572a8e4a
Faulting module name: KERNELBASE.dll, version: 10.0.10586.162, time stamp: 0x56cd45b4
Exception code: 0xe0434352
Fault offset: 0x0000000000071f28
Faulting process id: 0xce4
Faulting application start time: 0x01d1a7acfa2b3ce2
Faulting application path: C:\_APPLICATIONS\teststandalone\bin\Release\netcoreapp1.0\win81-x64\publish\teststandalone.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: a413017d-cc75-4899-a1c9-00773bfc90a8
Faulting package full name: 
Faulting package-relative application ID: 
```
## Environment data

```
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:
 Version:     1.0.0-rc2-002678
 Commit Sha:  3b2ea9d14b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by krwq** [comment]
cc: @piotrpMSFT

**Comment by piotrpMSFT** [comment]
This seems to be a configuration issue in project.json. We should add a better warning/error to help folks track this down. Let's look at this for RTM.

**Comment by blackdwarf** [comment]
@GuardRex does this apply to the MSBuild-based tooling?

**Comment by GuardRex** [comment]
@blackdwarf I'll test it right now and get back to you shortly.

**Comment by blackdwarf** [comment]
Thanks much! :)


Thanks,
Z
________________________________

**Comment by GuardRex** [comment]
@blackdwarf Yes, it's still there with MSBuild. The setup is like this ...

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp1.2</TargetFramework>
  <OutputType>Exe</OutputType>
  <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
  <PlatformTarget>x86</PlatformTarget>
</PropertyGroup>
```
It will compile without any indication of a problem using `dotnet publish -r win10-x64` ...

![capture](https://cloud.githubusercontent.com/assets/1622880/22138730/b364e37c-dea7-11e6-95ac-70a6d0de0a77.PNG)
When you try to run the app, it :boom: with ...
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 
'testselfcontained.dll'. An attempt was made to load a program with an incorrect format.
```

**Comment by piotrpMSFT** [comment]
Moved to SDK repo as that will be the right place to fix.
