### ISSUE TITLE
An item with the same key has already been added. Key: Microsoft.DotNet.ProjectM odel.ProjectContextBuilder+LibraryKey

### ISSUE THREAD

**Issue by mikeandersun** [dotnet/cli#2925]
`dotnet`build produces this error :
`An item with the same key has already been added. Key: Microsoft.DotNet.ProjectM odel.ProjectContextBuilder+LibraryKey
`

**Comment by krwq** [comment]
Hey @mikeandersun,

Please share following:
- `dotnet -v build` output
- `dotnet --info` output
- some repro (project.json + Program.cs)
- your OS information

**Comment by mikeandersun** [comment]
dotnet -v  output:
```
.NET Command Line Tools (1.0.0-beta-001598)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  repl          Launch an interactive session (read, eval, print, loop)
  pack          Creates a NuGet package
```

**Comment by mikeandersun** [comment]
@krwq  I re-install last wervion on .NETCore SDK and the error go away. but this is  a new error when i run  `dotnet run` :
`Object reference not set to an instance of an object.
`

**Comment by piotrpMSFT** [comment]
@mikeandersun what --info produced that error?

**Comment by mfbasha** [comment]
Use this command 
dotnet restore --no-cache

**Comment by blackdwarf** [comment]
I believe that this has been fixed in the latest tooling. Also, this is a project.json-specific bug. We don't have plans to ship additional project.json updates now that we've transitioned to msbuild. Closing the issue, therefore.
