### ISSUE TITLE
dotnet-test NetCoreApp1.0 throws FileNotFoundException on win7-x64

### ISSUE THREAD

**Issue by mikary** [dotnet/cli#2926]
## Steps to reproduce

run `dotnet test` in project with `netcoreapp1.0` target framework on Windows 7-x64

project.json:

``` json

  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027",
    "dotnet-test-xunit": "1.0.0-rc2-157751-46",
    "xunit": "2.1.0"
  },

  "testRunner": "xunit",

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002426"
        }
      },
      "imports": [ "portable-net45+win8", "dotnet" ]
    }
  }
}
```
## Expected  behavior

Unit tests run with NetCoreApp1.0 TFM
## Actual behavior

opens dialog "dotnet.exe has stopped working"

Console output:

```
Project SingleNetCoreApp10 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling SingleNetCoreApp10 for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.5007757


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=
neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file
specified.
   at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadEntryAssemblyContext()
   at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
   at Xunit.Runner.DotNet.Program.GetAvailableRunnerReporters()
   at Xunit.Runner.DotNet.Program.Run(String[] args)
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:
 Version:     1.0.0-rc2-002678
 Commit Sha:  3b2ea9d14b

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by brthor** [comment]
Try: "dotnet-test-xunit": "1.0.0-rc2-173361-36"

**Comment by mikary** [comment]
Is there a different package source for that? Doesn't appear to resolve from nuget.org

```
error: Unable to resolve 'dotnet-test-xunit (>= 1.0.0-rc2-173361-36)' for '.NETCoreApp,Version=v1.0'.
warn : Detected package downgrade: System.Runtime from 4.1.0-rc2-24018 to 4.1.0-rc2-24008 
warn :  SingleNetCoreApp10 (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.0.0-rc2-3002426) -> Microsoft.CodeAnalysis.CSharp (>= 1.3.0-beta1-20160410-01) -> Microsoft.CodeAnalysis.Common (= 1.3.0-beta1-20160410-01) -> System.Threading (>= 4.0.11-rc2-24008) -> System.Runtime (>= 4.1.0-rc2-24018) 
warn :  SingleNetCoreApp10 (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.0.0-rc2-3002426) -> Microsoft.CodeAnalysis.CSharp (>= 1.3.0-beta1-20160410-01) -> Microsoft.CodeAnalysis.Common (= 1.3.0-beta1-20160410-01) -> System.Runtime (>= 4.1.0-rc2-24008)
```

**Comment by brthor** [comment]
@Sridhar-MS @piotrpMSFT Is there a package source for dotnet-test-xunit?

**Comment by piotrpMSFT** [comment]
The issue here is likely the order of the imports. Please put dotnet first.

@mikeray already has a NuGet.config pulling an older dotnet-test-xunit from somewhere. I don't think we need to update here to fix the issue.

**Comment by mikary** [comment]
Moving `"dotnet-test-xunit": "1.0.0-rc2-173361-36"` to the first dependency doesn't appear to change the behavior

```
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/dotnet-test-xunit/index.json 273ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json 251ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json 270ms
error: Unable to resolve 'dotnet-test-xunit (>= 1.0.0-rc2-173361-36)' for '.NETCoreApp,Version=v1.0'.
warn : Detected package downgrade: System.Runtime from 4.1.0-rc2-24018 to 4.1.0-rc2-24008 
```

**Comment by brthor** [comment]
@mikary @piotrpMSFT 
I remember seeing issues with older dotnet-test-xunit pulling in an old dependency model, I suspect that is the issue here.

**Comment by piotrpMSFT** [comment]
@mikary can you replace your imports with this? It's the exact imports we use in the CLI repo:
````
      "imports": [
        "dotnet5.4",
        "portable-net451+win8"
      ]
````

If you need `dotnet` and not `dotnet5.4` then please maintain the order as depicted: let `dotnet` come first.

The error shows us that a v2.0.5.0 assembly is being pulled in. This typically occurs when imports statements enable NuGet to pull in an incompatible [read: desktop] assembly dependency.

**Comment by GuardRex** [comment]
> The error shows us that a v2.0.5.0 assembly is being pulled in. This typically occurs when imports statements enable NuGet to pull in an incompatible [read: desktop] assembly dependency.

I still suggest a warning on restore ... `imports` is tooooo graceful on bringing packages in so transparently. https://github.com/dotnet/cli/issues/2585#issuecomment-212479040

**Comment by smitpatel** [comment]
Using following imports works fine.
```
"imports": [
        "dnxcore50",
        "portable-net452+win81"
      ]
```

**Comment by livarcocc** [comment]
What is expected of the CLI in this case? It is up to NuGet how it handles the imports.

**Comment by GuardRex** [comment]
Terrible when this happens, b/c the exception doesn't make it clear what's happening. Thank goodness for Github Fu.

Reference to another example I just hit and solved by fixing `imports`: https://github.com/Azure/azure-storage-net/issues/289

**Comment by blackdwarf** [comment]
The root cause of the issue has been solved. If we want to have better behavior with imports, as @livarcocc said we should create an issue on NuGet/Home and have a discussion there.

**Comment by piotrpMSFT** [comment]
https://github.com/NuGet/Home/issues/4349 might be related. It also looks at handling of imports, asking that nuget's package add command handle imports management on user's behalf.
