### ISSUE TITLE
Microsoft.NETCore.App type: platform can be restored but not built for netcore50 projects

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#2927]
## Steps to reproduce
- Create a project with the `project.json`:
```json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-*"
    }
  },
  "frameworks": {
    "netcore50": {
    }
  }
}
```
- Add a class
```C#
public class Anything
{
}
```
- Run dotnet restore (completes successfully, but shouldn't).
- Run dotnet build

## Expected  behavior
Restore should have failed with
```
Package System.Runtime.Loader 4.0.0-rc2-24027 is not compatible with netcore50 (.NETCore,Version=v5.0). Package System.Runtime.Loader 4.0.0-rc2-24027 supports:
      - net462 (.NETFramework,Version=v4.6.2)
      - netstandard1.5 (.NETStandard,Version=v1.5)
    One or more packages are incompatible with .NETCore,Version=v5.0.
```

## Actual behavior
Restore succeeds and build fails with:
`error NU1002: The dependency System.Runtime.Loader 4.0.0-rc2-24027 does not support framework .NETCore,Version=v5.0.`

## Environment data
```
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:                      
 Version:     1.0.0-rc2-002678            
 Commit Sha:  3b2ea9d14b                  

Runtime Environment:                      
 OS Name:     Windows                     
 OS Version:  10.0.10586                  
 OS Platform: Windows                     
 RID:         win10-x64 
```

## Extra
If you remove `"type": "platform"` from `Microsoft.NETCore.App` restore fails as expected.

/cc @Eilon @pranavkm @pakrym

**Comment by piotrpMSFT** [comment]
@NTaylorMullen is the issue here NuGet behavior? Or NetCore.App NuGet configuration?

**Comment by NTaylorMullen** [comment]
@piotrpMSFT I'm not entirely sure where the issue lies due to my lack of knowledge of how the inner cli bits are split but the issue is that trying to restore `Microsoft.NETCore.App` in a `netcore50` project should always fail (on restore) despite it having a `"type": "platform"`.

**Comment by piotrpMSFT** [comment]
@weshaggard @emgarten @rrelyea can you guys take a look? I'm not familiar with the netcore50 TFM but if we should fail at restore here then we likely need to change the NetCore.App package authoring or think about our handling of "type": "platform" in NuGet.

**Comment by weshaggard** [comment]
This is partly a manifestation of https://github.com/dotnet/cli/issues/2924 because restore should have probably failed because the meta-package doesn't support netcore50 and does contain references to things like System.Runtime.Loader which isn't supported on netcore50.

@ericstj any ideas why this didn't fail at restore time but instead at build time?

**Comment by ericstj** [comment]
@weshaggard i believe it is not failing because NuGet doesn't do any compat checks for things marked "platform" they just make sure that packages have some applicable asset.

**Comment by AndriySvyryd** [comment]
restore fails as expected on 1.0.0-preview2-003118:
```
    Package Microsoft.NETCore.App 1.0.0 is not compatible with netcore50 (.NETCore,Version=v5.0). Package Microsoft.NETCore.App 1.0.0 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
    One or more packages are incompatible with .NETCore,Version=v5.0.
```

**Comment by NTaylorMullen** [comment]
Awesome, so this seems to have been fixed since the filing of this issue then @AndriySvyryd ?

**Comment by AndriySvyryd** [comment]
That would be my guess @NTaylorMullen

**Comment by ericstj** [comment]
I believe @weshaggard fixed this as of https://github.com/dotnet/core-setup/commit/42b00aa3b269f598853d1e3cdfbf20e66429d7d1

**Comment by weshaggard** [comment]
Yes this has been fixed.
