### ISSUE TITLE
libcurl should be added to Debian package dependencies

### ISSUE THREAD

**Issue by adrian17** [dotnet/cli#293]
If `libcurl3`package is not installed, `dotnet restore` fails:

    dotnet restore --no-cache
    Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

    ----------
    System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libcurl.so.4': The specified module could not be found.
    (...stack trace here...)

**Comment by natemcmaster** [comment]
Could we add *all* native dependencies to the deb package? `libunwind8 gettext libssl-dev libcurl4-openssl-dev zlib1g libicu-dev uuid-dev` (list from dnx rc1)

**Comment by Sridhar-MS** [comment]
I think any direct runtime dependencies like libunwind is detected automatically and added by debian packaging scripts. But any framework assembly dependency (example - System.Security.Cryptography dependency on libssl and System.Net.Http dependency on libcurl) is not automatically detected and needs to be manually added to the [debian config file](https://github.com/dotnet/cli/blob/20f5ba4a5edd518bd012aa6ccee9a899f1bf70ff/packaging/debian/debian_config.json#L31).

**Comment by adrian17** [comment]
> I think any direct runtime dependencies like libunwind is detected automatically and added by debian packaging scripts.

Ah, true, I just took a look at the control file from my package and it contains definitely more than [the config file](https://github.com/dotnet/cli/blob/master/packaging/debian/debian_config.json#L31):

    Depends: libc6 (>= 2.15), libcurl3-gnutls (>= 7.28.0), libgcc1 (>= 1:4.1.1), libicu52 (>= 52~m1-1~), liblldb-3.6, liblttng-ust0, libssl1.0.0 (>= 1.0.1), libstdc++6 (>= 4.8), libtinfo5, libunwind8, libuuid1 (>= 2.16), zlib1g (>= 1:1.2.0), libssl-dev

And although it *does* depend on `libcurl3-gnutls`, it does not depend on `libcurl3`, which is the provider of the `libcurl.so.4` library mentioned in the error. By the way, it does seem a bit weird to depend on two SSL backends in one package.

**Comment by brthor** [comment]
@adrian17 Thanks for the great detail! Will work to repro this today on a clean machine and add in that dependency. 

Are you on Ubuntu.14.04?

**Comment by adrian17** [comment]
I'm on Debian Stretch, but I just checked on a Ubuntu 14.04 VM and it seems to look the same there.

**Comment by brthor** [comment]
@adrian17 Thanks for the quick reply! 

Taking a look now

**Comment by adrian17** [comment]
Oh, on Debian Stretch `curl` depends on `libcurl3-gnutls`, but on Debian Jessie and Ubuntu it depends on `libcurl` - so it's very hard to accidentally encounter this issue on most systems unless you don't have curl installed at all. (although the issue of missing dependency exists nonetheless).

**Comment by brthor** [comment]
I was able to reproduce this on a clean Ubuntu 14.04 only by explicitly uninstalling libcurl3, so it shouldn't be an issue in most cases. 

Still going to fix it as it is a missing dependency though.

**Comment by paulmey** [comment]
Actually ran into this as well on my clean minimal Ubuntu server as well as the ubuntu:14.04 docker image. Not everyone likes a fat server...? :-)

**Comment by brthor** [comment]
Thanks @paulmey didn't realize this was breaking the docker image.

Like @Sridhar-MS typically executables which depend on dynamic libraries will automatically have the packages containing those libraries added as dependencies. It seems this doesn't work for managed executables and is ultimately root cause here.
