### ISSUE TITLE
shared Microsoft.NETCore.App folder commands are silent

### ISSUE THREAD

**Issue by lodejard** [dotnet/cli#2931]
## Steps to reproduce
Download dotnet-dev-win-x64.latest.zip
cd `shared\Microsoft.NETCore.App\1.0.0-rc2-3002692`
Run various dotnet.exe and corehost.exe `--version` and `--help` switches

## Expected  behavior
Version and help information

## Actual behavior
```
C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>dotnet
Usage: dotnet [--help | app.dll]

C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>corehost
Usage: dotnet [--help | app.dll]

C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>dotnet --version

C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>dotnet --help

C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>corehost --version

C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>corehost --help

C:\Users\lodejard\Programs\dotnet-dev-win-x64@1.0.0-preview1-002692\shared\Microsoft.NETCore.App\1.0.0-rc2-3002692>
```

**NOTE** these are not typos - this is literally cut and paste from a cmd prompt. The corehost.exe said "Usage: dotnet". And the sdk version and shared host version are not the same.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-preview1-002692)

Product Information:
 Version:     1.0.0-preview1-preview1-002692
 Commit Sha:  8c902a1954

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by piotrpMSFT** [comment]
The CoreHost and Dotnet.exe in the SxS directory have both been superseded by the muxer in the root directory. After the next release we have a plan to remove both of these artifacts since they're not adding value and are creating considerable confusion.

**Comment by lodejard** [comment]
@piotrpMSFT how will someone specify exactly which coreclr they want to run directly? it sounds like this decision is different than any SxS runtime I've seen before (java, ruby, node, etc, etc, etc).

**Comment by piotrpMSFT** [comment]
@lodejard this will be done via muxer param. Yep, it's different and simplifies a bunch of scenarios.
