### ISSUE TITLE
dotnet pack does not support the "suppressParam" flag

### ISSUE THREAD

**Issue by dsgouda** [dotnet/cli#2937]
## Steps to reproduce

When trying to build a cross plat app using dotnet cli with reference to Microsoft.NETCoreApp with a  `"suppressParent": "all"` set, the NETCoreApp dependency is not suppressed. It would be helpful in scenarios where we do not wish to take a dependency on the entire NETCoreApp framework as described here https://github.com/dotnet/cli/issues/2913
## Expected  behavior

NETCoreApp dependency should be suppressed
## Actual behavior

NETCoreApp dependency is not suppressed
## Environment data

`dotnet --info` output:

cc: @ericstj

**Comment by livarcocc** [comment]
You can set `<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>` and then not add a reference to the M.NC.App package to achieve this.

Also, if you want to depend on it but not have that dependency flow, you can set PrivateAssets="All" as metadata to your package reference. Though, this is set implicitly for you as well.
