### ISSUE TITLE
Error is printed twice with "dotnet build" without "dotnet restore" first

### ISSUE THREAD

**Issue by am11** [dotnet/cli#2944]
Found this while reproducing #2942 with `v1.0.0-preview1-preview1-002693`.

## Steps to reproduce

```bash
mkdir test
cd test

dotnet new
dotnet -v build
```

## Expected  behavior

>
Telemetry is: Enabled
Project test does not have a lock file.

## Actual behavior

>
Telemetry is: Enabled
Project test does not have a lock file.
Project test does not have a lock file.

Issue: error is printed twice.
Note that there is only one framework specified in the brand new project.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-preview1-002693)

Product Information:
 Version:     1.0.0-preview1-preview1-002693
 Commit Sha:  7821df9bd3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by jburger** [comment]
I think this error should also be more descriptive to better inform newcomers of the expected workflow. E.g.
Project XYZ's project.json has changed recently, please run 'dotnet restore' first.

**Comment by livarcocc** [comment]
Fixed.
