### ISSUE TITLE
Regression in dotnet publish of self-contained apps? ... or new self-contained publishing model?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2947]
## Steps to reproduce
```
dotnet publish --configuration Release --runtime win81-x64
```

## Expected  behavior
Usual self-contained output (with an `.exe`)

## Actual behavior
Looks like you want to bundle `dotnet.exe` for the self-contained app now and trigger it `dotnet .\myapp.dll`?? This was done on purpose?? If that's the case, did I miss a **major announcement**? If this is the new self-contained publishing model, this is a breaking change and opens up a security risk.

![capture](https://cloud.githubusercontent.com/assets/1622880/15093452/61edbfb0-144e-11e6-9ffe-850677988e01.PNG)

## Question
If this was done on purpose, how can I get prior output back (`.exe`)?

## Environment data
```
.NET Command Line Tools (1.0.0-rc2-002392)

Product Information:
 Version:     1.0.0-rc2-002392
 Commit Sha:  880dcf2fc8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
```json
{
  "buildOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true,
    "nowarn": [ "CS1591" ],
    "xmlDoc": true,
    "outputName": "dotnet-publish-iis"
  },
  "dependencies": {
    "Microsoft.Extensions.CommandLineUtils": "1.0.0-*",
    "Microsoft.DotNet.ProjectModel": "1.0.0-*",
    "System.Diagnostics.Process": "4.1.0-*",
    "NETStandard.Library": "1.5.0-*",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-dnxcore50+net45+win8+wp8+wpa81"
      ]
    }
  },
  "runtimes": {
    "win81-x64": {}
  },
  "version": "1.0.0"
}
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="AspNetCI" value="https://www.myget.org/F/aspnetcirelease/api/v3/index.json" />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by eerhardt** [comment]
Your CLI is a little old 2392 and we are on 2697 now.

Can you try this with the latest version?

**Comment by GuardRex** [comment]
@eerhardt I updated that this morning. Something strange here ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/15093552/5612d420-1451-11e6-8c04-242a620a12db.PNG)

... but `dotnet --info` is giving me that ^^ version. Any ideas?

**Comment by GuardRex** [comment]
Oh, wow ... look at all this stuff ...

![capture2](https://cloud.githubusercontent.com/assets/1622880/15093579/f7ac3b8c-1451-11e6-8bf1-ebc7756e6c82.PNG)

**Comment by GuardRex** [comment]
Uninstall didn't get all of the old registry keys out either ...

![capture3](https://cloud.githubusercontent.com/assets/1622880/15093611/89f653d8-1452-11e6-81c1-d8ea1dca4606.PNG)

I'm going to manually clean all of this up and install fresh and see if I can fix this.

**Comment by eerhardt** [comment]
If you delete all the old ones out do the repro steps work as expected?

Can you open a new issue for the upgrade/uninstall/install over the top not picking up the latest version?

**Comment by GuardRex** [comment]
@eerhardt Ok ... will do. I'll drop a note here and close this in a sec.

**Comment by GuardRex** [comment]
Opened issue at https://github.com/dotnet/cli/issues/2948
