### ISSUE TITLE
Upgrade/Uninstall/Install over the top not picking up the latest version

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2948]
## Steps to reproduce
Remove prior `dotnet cli` via `Programs & Features` ... remove them all, which only leaves the current one showing from an install of the latest `dotnet cli` from MSI ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/15093686/6dcf4bae-1454-11e6-921d-7a3f412e2d3b.PNG)

## Expected  behavior
Old registry keys and SDK shared frameworks are removed.

## Actual behavior
Old registry keys and SDK shared frameworks remain, which can lead to an old `dotnet cli` being used on the machine. This was breaking my publish, and I didn't notice the version until @eerhardt spotted it in https://github.com/dotnet/cli/issues/2947.

![capture2](https://cloud.githubusercontent.com/assets/1622880/15093679/44a21b9e-1454-11e6-8694-fd0f308425fc.PNG)

![capture3](https://cloud.githubusercontent.com/assets/1622880/15093680/46add2c0-1454-11e6-9067-6110082e19aa.PNG)

## Environment data
Was showing ...
```
.NET Command Line Tools (1.0.0-rc2-002392)

Product Information:
 Version:     1.0.0-rc2-002392
 Commit Sha:  880dcf2fc8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
... prior to my manually deleting old registry keys, deleting old SDK shared frameworks, uninstalling the latest SDK, restarting the machine, then installing the latest SDK. Now, it shows correctly ...
```
.NET Command Line Tools (1.0.0-preview1-preview1-002697)

Product Information:
 Version:     1.0.0-preview1-preview1-002697
 Commit Sha:  08b3ad9e88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
... and publishing has gone back to normal expected behavior.

**Comment by Sridhar-MS** [comment]
@GuardRex Can you share one of the unsuccessful uninstall logs from the %temp% directory?

**Comment by GuardRex** [comment]
@Sridhar-MS Sure, but there's a ton of these files in there tho. Which one (or ones) would you like?

![capture1](https://cloud.githubusercontent.com/assets/1622880/15096209/fd02f7ca-14b4-11e6-9ac1-0f9bb69a2375.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1622880/15096210/0034d986-14b5-11e6-9b88-d1eaa468e6dc.PNG)

![capture3](https://cloud.githubusercontent.com/assets/1622880/15096211/03396dc2-14b5-11e6-934d-6ecd572df5ad.PNG)

**Comment by piotrpMSFT** [comment]
@GuardRex I noticed that the affected uninstalls are all from fairly old builds of CLI. @Sridhar-MS did a bunch of installer cleanup work last week which should have helped with some of these issues. I've not seen similar behavior when testing with recent CLI builds.

Do you see similar behavior with recent builds>

**Comment by GuardRex** [comment]
I don't think so with recent builds. I've made a note to manually check the registry and the installed sdk's next weekend. I'll close, then if things don't go well, I'll re-open next weekend.
