### ISSUE TITLE
Add new command "dotnet pkg" for installed package manipulation 

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#295]
Today (11/22/2015) I was fixing the samples, wondering why they were working on one of my machines but not on a brand new machine. Of course, the reason is that the old machine had a bunch of stuff in the NuGet cache. This lead me, in turn, to thinking about overall package manipulation using our CLI toolchain. We already have two ways of getting packages to the machine specified/planned (`dotnet install-package` and `dotnet restore`), but no way of interacting with the packages or cache.

I was thinking of introducing another command that would be `dotnet pkg` that would allow something along the lines of:

* `dotnet pkg --clear-cache` - clears the cache that exists in a well known location; this way, we don't force the users to know where this location is
* `dotnet pkg --remove [pkg-id]` - remove the package from project.json and disk (or just disk)

Some others that I'm considering but that could be not so useful are `dotnet pkg --info [pkg-id]` to get basic package information (though you should already know this if you specified it in your project.json).

Thoughts?

/cc @piotrpMSFT @davidfowl @Sridhar-MS @brthor @anurse @richlander

**Comment by davidfowl** [comment]
I think not. We should avoid duplicating nuget commands in the dotnet cli. We keep the most critical ones but nuget already has something for this. I really don't want this tool to be used for advanced scenarios like that.

**Comment by piotrpMSFT** [comment]
@davidfowl Is the idea that we'd have a dotnet-{foo} that would pass through to NuGet?

**Comment by blackdwarf** [comment]
@piotrpMSFT @davidfowl I'm not talking about implementation, I leave that to your capable hands. :) I just want to see if we think that there is value in this scenario, that we have commands that allow users to interact with the package cache. We have a way to get the packages in there (restore & install-package) but no way to remove them, clear the cache, list it out etc.

**Comment by anurse** [comment]
I really think that commands for manipulating packages should remain under `nuget`. I'd rather see `nuget restore` rather than `dotnet restore` and similarly, commands that manipulate the package cache should live there as well.

As much as I like a "unified" CLI, `nuget` has an existing ecosystem and community around it and we should build around that as well rather than hiding everything behind `dotnet`

**Comment by anurse** [comment]
But yeah, the general concept of having more commands to manipulate packages and package caches, I'm down with that ;)

**Comment by blackdwarf** [comment]
@anurse I could go both ways. Honestly, there are times when working with other platforms where I get super frustrated that their package managers are a separate thing from the rest of the toolchain (python & pip, perl & cpan, ruby & gem, node & npm...go seems the only one that doesn't do this), so I can see the value in having an unified toolchain for users. 

So, from what I gather from the comments, we **do want** to have the capability/scenario, we **don't want** to replicate NuGet behavior from scratch. Am I reading this correctly?

**Comment by davidfowl** [comment]
Dotnet should be for the core commands required to get something working. Debug, restore, compile, run, test (and repl I guess). dotnet install or dotnet pkg sub commands should just not exist as they need replicate the underlying thing they are driving. We shoulda avoid inventing specs for how the command should behave outside of the underlying thing.

I'm also ok with non conflicting commands like format.

**Comment by blackdwarf** [comment]
@Petermarcu I believe that you had a similar idea?

**Comment by blackdwarf** [comment]
This will not be happening, so closing.
