### ISSUE TITLE
dotnet build outputs wrong file paths in errors

### ISSUE THREAD

**Issue by jstarks** [dotnet/cli#2950]
When building projects not in the current directory, dotnet build prints the wrong filenames in error messages. This makes it impossible to consume the error output in editors.

## Steps to reproduce
```
mkdir foo
cd foo
dotnet new
dotnet restore
<change Program.cs to have a compilation error, e.g. remove using System;>
cd ..
dotnet build foo
```

## Expected  behavior
```
C:\Users\jstar\Documents\GitHub\tmp\foo\Program.cs(7,13): error CS0103: The name 'Console' does not exist in the current context
```

## Actual behavior
```
C:\Users\jstar\Documents\GitHub\tmp\foo\foo\Program.cs(7,13): error CS0103: The name 'Console' does not exist in the current context
```

Notice that the path contains `foo\foo\Program.cs` when in fact the path should just be `foo\Program.cs`.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc2-002339)

Product Information:
 Version:     1.0.0-rc2-002339
 Commit Sha:  2be5e84f87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by am11** [comment]
This issue appears to be resolved in latest preview 002697.

**Comment by jstarks** [comment]
Interesting, I just downloaded and installed the latest preview today, but it seems that 2339 somehow was left behind from an earlier installation and took precedence. Looks like another case of Windows installer technology problems.

After deleting it manually from Program Files and reinstalling 2697, I can confirm that this fixes the issue. Thanks.
