### ISSUE TITLE
Need machine servicing prereq script 

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#2952]
A script is needed which applies servicing prerequisites to Windows machines to enable Microsoft Update for "clean" machines which do not have either .NET Framework or the Shared Framework installed.   

@gkhanna79 @ericstj

**Comment by piotrpMSFT** [comment]
What's the consumption plan for this script? Can't we just point folks to existing docs for enabling MU on their machines?

**Comment by piotrpMSFT** [comment]
Moving to rtm milestone. I see we really want #2953 in the CLI. If we do provide a guided solution for folks before that installer feature is built then this will be a sample/doc change and shouldn't be tracked against CLI RC2 milestone.

**Comment by gkhanna79** [comment]
@leecow This is a pretty simple (effectively, a single line) batch script. Shouldnt the docs suffice instead of this?

**Comment by leecow** [comment]
@gkhanna79 I think documenting the short script will be fine for RC2. Wouldn't mind thinking through possible options which could enable what is needed on first app launch.

**Comment by schellap** [comment]
These are the steps that are needed AFAIK:

1. BreadcrumbStore should be [ACL'ed as in](https://github.com/dotnet/cli/blob/cb9ece20490747f52fa6e3f54b55a93a0eef8796/packaging/windows/sharedframework/sharedframework.wxs#L16)  PR #2662 
2. MU should be enabled on the machine.

**Comment by piotrpMSFT** [comment]
@leecow is this still planned for 1.0.0?

**Comment by livarcocc** [comment]
I don't think there is anything here that is required from the CLI. If I am mistaken and that is not the case, please re-activate with the expected CLI work.
