### ISSUE TITLE
Implement MU Opt-In as part of setups

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#2953]
If Microsoft Update is not turned on in the box by default, the installing dotnet should allow to turn this on machine wide as part of installing Shared FX or perhaps any of our installers.

This would allow us to service all our components through MU.

@gkhanna79, @piotrpMSFT, @ericstj, @ellismg, @leecow.

**Comment by piotrpMSFT** [comment]
@leecow let's chat about this offline. We need to consider the User Experience here along with UI changes.

**Comment by leecow** [comment]
@piotrpMSFT sounds good. The key consideration is that not every installation will have the Shared FX nor happen using an installer. An xcopied portable application is a prime example.

**Comment by piotrpMSFT** [comment]
Moved to core-setup
