### ISSUE TITLE
microsoft/dotnet-preview images no longer contain the latest builds.

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#2955]
The microsoft/dotnet-preview images are supposed to contain the latest CLI builds.  Currently the images contain the latest -1 CLI bits.  The [logic](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/PublishTargets.cs#L49) in the CLI builds that trigger the building of the new docker images is getting invoked before the "latest" tagged images are uploaded to Azure.  This looks to be a result of [this](https://github.com/dotnet/cli/commit/c4d7251efbf87c35b4a1529cbdca8d3af030fc1b#diff-f91e0ab8a46aea2258ed4da8a1315ee4) change.

@naamunds

**Comment by livarcocc** [comment]
@MichaelSimons Is this blocking preview1? Can we trigger these builds manually for now?

**Comment by MichaelSimons** [comment]
@livarcocc, No I don't see this as blocking preview1.  I had already triggered a manual build once I discovered this problem.

**Comment by MichaelSimons** [comment]
This needs to be fixed before RTM.  Moving to preview2.

**Comment by eerhardt** [comment]
This should be fixed now with a combination of @MichaelSimons's move to using Maestro, and my change #3442, which moved updating dotnet/versions during FinalizeBuild.

I'm going to close because this should be fixed.  @MichaelSimons please re-open if this isn't the case.
