### ISSUE TITLE
Add Fedora 23 CLI Build / Packages for Preview 2

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#2958]
Related: 
https://github.com/dotnet/corefx/issues/5990 - tracking Fedora 23 for CoreFX/CoreCLR

cc: @ellismg @piotrpMSFT

**Comment by nmilosev** [comment]
Hello, I don't know if it helps, but I wrote a guide how to run the CentOS package on latest Fedora 23 here:

https://nmilosev.svbtle.com/running-net-core-rc2-on-fedora-23

The only thing that wasn't working out of the box was the ```libicu``` library which is at version 50 in CentOS and 54 in Fedora 23. Once I got ```libicu``` 50 in my ```lib``` folder everything worked.

Hope this helps!

Cheers.

**Comment by piotrpMSFT** [comment]
Fixed by #3184
