### ISSUE TITLE
rc2 CLI used even if preview1 is installed

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2959]
https://github.com/dotnet/cli shows that the available version is 1.0.0-preview1-002700 but when I download I only get  `1.0.0-rc2-002670`. 
Where do I get the latest preview1 version? 
The links should be updated so that it can be downloaded.

**Comment by moozzyk** [comment]
Probably version ordering. I did install preview1 sdks but dotnet kept picking up rc2. Once I deleted rc2 sdks the latest preview1 one was picked.

**Comment by moozzyk** [comment]
There will be need some guidance about this because it will cause issues for early adopters - reopening. I think @davidfowl just hit this as well.

**Comment by vcsjones** [comment]
I hit this too on OS X. I torched everything and installed from scratch, then everything worked correctly.

**Comment by oold** [comment]
Might be connected to this bug -> #2988

**Comment by GuardRex** [comment]
Cross ref in case someone hits that one I opened (and is closed now) and should be directed here: https://github.com/dotnet/cli/issues/2948

**Comment by piotrpMSFT** [comment]
This is a dupe of #2833.
