### ISSUE TITLE
Error for unknown command has terminal escape codes

### ISSUE THREAD

**Issue by rynowak** [dotnet/cli#2963]
## Steps to reproduce

type `dotnet rebuild` at the command line on win10

```
[1m[31mNo executable found matching command "dotnet-rebuild"[39m[22m
```
## Expected  behavior

Output doesn't have terminal escape codes
## Actual behavior

It does
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002673)

Product Information:
 Version:     1.0.0-rc2-002673
 Commit Sha:  c0aeb91d61

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
This has been fixed in the latest tooling. Closing.
