### ISSUE TITLE
dotnet publish allows publishing for random RIDs when publishing for net451

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2964]
## Steps to reproduce

`dotnet publish -f net451 -r win19-x12`

project.json:

```
{
  "buildOptions": {
    "preserveCompilationContext": true,
    "emitEntryPoint": true,
    "debugType": "portable"
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views"
    ]
  },
  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "StringProvider": "1.0.0-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          // "type": "platform",
          "version": "1.0.0-*"
        }
      },
      "imports": [
        "portable-net45+wp80+win8+wpa81+dnxcore50",
        "portable-net451+win8"
      ]
    },
    "net451": {
      "dependencies": {
        "Microsoft.NETCore.Platforms" : "1.0.1-*"
      }
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  },
  "runtimes": {
    "win7-x86": {},
    "win8-x64": {},
    "ubuntu.14.04-x64": {},
    "rhel.7.2-x64": {},
    "osx.10.10-x64": {}
  }
}
```

![image](https://cloud.githubusercontent.com/assets/1438884/15126674/e7b31182-15e7-11e6-9a5a-0d6d25ae8752.png)

The application is not functional - libuv.dll is not published:
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
## Expected  behavior

If RID is ignored then there should be a warning. Also the folder should not contain RID if this is the case? If RID is needed (as it appears to be) an error saying that the provided RID is invalid.
## Actual behavior

RID is used as the folder name and the published application is not functional because libuv.dll is not getting published.

![image](https://cloud.githubusercontent.com/assets/1438884/15126674/e7b31182-15e7-11e6-9a5a-0d6d25ae8752.png)

The application is not functional - libuv.dll is not published:
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'libuv': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.AspNetCore.Server.Kestrel.Networking.Libuv.NativeMethods.uv_loop_size()
   at Microsoft.AspNetCore.Server.Kestrel.Networking.UvLoopHandle.Init(Libuv uv)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelThread.ThreadStart(Object parameter)
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by moozzyk** [comment]
Kind of related issue: https://github.com/dotnet/cli/issues/2956

**Comment by livarcocc** [comment]
@moozzyk I don't think this blocks RC2 right? Marking this for RTM.

**Comment by moozzyk** [comment]
@livarcocc - no, this is not rc2

**Comment by GuardRex** [comment]
@moozzyk I see you have the  `NETStandard.Library` under the `net451`  TFM. Does it still exhibit this behavior if you add the `Microsoft.NETCore.DotNetHostPolicy` package to the `net451` along with `NetStandard.Library`?

**Comment by moozzyk** [comment]
Related: https://github.com/dotnet/cli/issues/3656

**Comment by blackdwarf** [comment]
So, in the latest tooling we will throw an error if the RID is not in the project file because the assets file will not contain the proper bits to wire them all up. However, adding a fictional RID to the project and then restoring and publishing works. However, we need a different issue to track this and I've created dotnet/sdk#690 to track the discussion of this work.

Will close this one.
