### ISSUE TITLE
`dotnet run` gives null reference exception when it cannot find a project.json file.

### ISSUE THREAD

**Issue by vcsjones** [dotnet/cli#2965]
## Steps to reproduce

Run `dotnet run --project path/to/non/existent/project.json`

## Expected  behavior

Indicates that the project.json file cannot be found.

## Actual behavior

>Object reference not set to an instance of an object.

is printed the console. That is the error message in its entirety.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by livarcocc** [comment]
I don't think this is blocking RC2, so moving this to RTM.

**Comment by vcsjones** [comment]
So the issue is a little different than I anticipated, perhaps the issue needs to be renamed.

The null ref is when it cannot find a project.json in the current directory if `--project` is not specified or if `-- project` is specified to a file that does not exist. If I run `dotnet run /dsf/sdfsd/sdf` and there happens to be a project.json in the current directory, it will run that.

I think the new issue is that it should not `NullReferenceException` if it cannot find a project.json file. Another thing to consider is what should be done with input into `dotnet run`? Right now it looks like it happily ignores anything that isn't part of a named command input.

This makes the usage of `dotnet run` a little confusing.

**Comment by vcsjones** [comment]
I pull down the source and compiled in debug. Here is the stack:

>System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tools.Run.RunCommand.CalculateDefaultsForNonAssigned()
   at Microsoft.DotNet.Tools.Run.RunCommand.RunExecutable()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)

**Comment by vcsjones** [comment]
This is fixed by #2980.
