### ISSUE TITLE
dotnet.exe doesn't work on Nano. (unless three dlls are copied advapi32.dll, kernel32.dll and shell32.dll)

### ISSUE THREAD

**Issue by sivagms** [dotnet/cli#2967]
## Steps to reproduce
Nano Machine - TP5 build
Unzip https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-rc2-002678/dotnet-dev-win-x64.1.0.0-rc2-002678.zip
dotnet --version

## Expected  behavior
command should return success. 
## Actual behavior
[10.209.36.6]: PS C:\tmp\dotnet> .\dotnet.exe --version
.\dotnet.exe : Failed to load the dll from
[C:\tmp\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002678\hostpolicy.dll], HRESULT: 0x8007007E
    + CategoryInfo          : NotSpecified: (Failed to load ...ULT: 0x8007007E:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

An error occurred while loading required library hostpolicy.dll from
[C:\tmp\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002678]

## Environment data
1.0.0-rc2-002678

Bascially dotnet.exe doesn't work on Nano as is. However this works if three dlls are copied to the dotnet folder: advapi32.dll, kernel32.dll and shell32.dll

**Comment by gkhanna79** [comment]
@refaati Why is this an issue if reverse forwarders are present?

**Comment by gkhanna79** [comment]
@sivagms Which build of Nano are you using and where are you copying those 3 binaries from?

**Comment by gkhanna79** [comment]
CC @schellap @piotrpMSFT

**Comment by sivagms** [comment]
Nano Version: 10.0.14338.1000
I'm copying the dlls from C:\Windows\System32\forwarders\

**Comment by gkhanna79** [comment]
@sivagms Are you copying them from Nano image itself?

**Comment by sivagms** [comment]
I did remote powershell and copied the dlls - 
FROM "C:\Windows\System32\forwarders\ on the nano machine" 
TO "dotnet folder on nano machine"

**Comment by gkhanna79** [comment]
@sivagms Are you able to run HelloWorld version of an app on Nano after making this change?

**Comment by gkhanna79** [comment]
Also, @sivagms, which version of .NET Core are you using?

**Comment by sivagms** [comment]
.NET version: 1.0.0-rc2-002678
yes, I'm able to run Helloworld and Musicstore as well after copying the dlls.

**Comment by sivagms** [comment]
@SajayAntony

**Comment by gkhanna79** [comment]
This is confirmed to be an issue with the Nano Server build.

**Comment by ericeil** [comment]
I ended up having to copy more than the three dlls listed here.  Copying everything from c:\windows\system32\forwarders next to CoreCLR seemed to work.

Note that if you "publish" an application, you'll need to copy the forwarders to the publish location as well.

**Comment by schellap** [comment]
@ericeil which version of the CLI are you using?

`dotnet --info`

**Comment by schellap** [comment]
@ericeil which version of the Shared FX are you using and is this a recent nano build?

**Comment by ericeil** [comment]
```
[40.78.96.241]: PS C:\l1> C:\dotnet\dotnetnano\dotnet --info
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14300
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by ericeil** [comment]
Also, got my NuGet.config from here: https://gist.github.com/mellinoe/7580563f9850466ac44352d2b1972c7c

**Comment by gkhanna79** [comment]
Sounds like a Nano config issue that reverse forwarders are not setup correctly?

**Comment by schellap** [comment]
dotnet publish and running app in standalone/portable, worked fine against `14339`. See below.

```
.NET Command Line Tools (1.0.0-preview2-003030)

Product Information:
 Version:            1.0.0-preview2-003030
 Commit SHA-1 hash:  c39fbd37d3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14339
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by gkhanna79** [comment]
@joshfree I dont believe there is any bug here - see @schellap email above and my responses from last month. This is a Nano configuration issue.

**Comment by joshfree** [comment]
@Priya91 please review

**Comment by gkhanna79** [comment]
Please see response from @refaati at https://github.com/dotnet/cli/issues/468#issuecomment-217322904

**Comment by Priya91** [comment]
@gkhanna79 The issue repros on TP5 which has reverse forwarders package turned on.

**Comment by gkhanna79** [comment]
@Priya91 How does your finding map to what Senthil has validated? Are they on different versions of Nano server? Also, CoreFX runs are also passing on Nano using the product from open build.

How have you confirmed that Reverse Forwarders are enabled?

**Comment by gkhanna79** [comment]
@Priya91 What is the version of the OS that you are using and version of dotnet (similar to what @schellap shared above)?

**Comment by Priya91** [comment]
The TP5 image was created following the blogpost [here] (https://blogs.technet.microsoft.com/nanoserver/2016/05/27/nano-server-tp5-iaas-image-in-azure-updated/)
This is the dotnet version
```
.NET Command Line Tools (1.0.0-preview2-003030)

Product Information:
 Version:            1.0.0-preview2-003030
 Commit SHA-1 hash:  c39fbd37d3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14300
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by gkhanna79** [comment]
@Priya91 you are using the same dotnet as @schellap did for his validation. The only difference I see is that OS version you have is 14300 while @schellap used 14339.

According to https://blogs.iis.net/davidso/nano/aspnet, the following should be used to validate presence of reverse forwarders:

_After installing Reverse Forwarders package (whether offline or online), verify that IIS and Reverse Forwarders are correctly installed by running ‘dism /online /get-packages’_

Can you confirm that they are installed?

**Comment by Priya91** [comment]
This is the output from dism, i can't find reverse forwarders here, pasting output for confirmation.

```
[40.118.166.174]: PS C:\Users\bb\Documents> dism /online /get-packages

Deployment Image Servicing and Management tool
Version: 10.0.14300.1000

Image Version: 10.0.14300.1000

Packages listing:

Package Identity : Microsoft-NanoServer-Azure-Provisioning-Package~31bf3856ad364e35~amd64~en-US~10.0.14300.1000
State : Installed
Release Type : Language Pack
Install Time : 4/21/2016 10:01 PM

Package Identity : Microsoft-NanoServer-Azure-Provisioning-Package~31bf3856ad364e35~amd64~~10.0.14300.1000
State : Installed
Release Type : Feature Pack
Install Time : 4/21/2016 10:01 PM

Package Identity : Microsoft-NanoServer-Guest-Package~31bf3856ad364e35~amd64~en-US~10.0.14300.1000
State : Installed
Release Type : Language Pack
Install Time : 4/21/2016 10:01 PM

Package Identity : Microsoft-NanoServer-Guest-Package~31bf3856ad364e35~amd64~~10.0.14300.1000
State : Installed
Release Type : Feature Pack
Install Time : 4/21/2016 10:00 PM

Package Identity : Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~10.0.14300.1000
State : Installed
Release Type : Foundation
Install Time : 3/25/2016 10:25 AM

Package Identity : Microsoft-Windows-ServerDatacenterNano-LanguagePack-Package~31bf3856ad364e35~amd64~en-US~10.0.14300.1000
State : Installed
Release Type : Language Pack
Install Time : 3/25/2016 10:31 AM

Package Identity : Package_for_RollupFix~31bf3856ad364e35~amd64~~14300.1010.1.0
State : Installed
Release Type : Security Update
Install Time : 4/21/2016 10:02 PM

The operation completed successfully.
```

**Comment by gkhanna79** [comment]
@Priya91 There was a loader bug in Nano build prior to 14339 which was fixed starting 14339. I sent you an email about it offline.

Please create an image, which is 14339 or higher, and validate against it.

**Comment by Priya91** [comment]
@gkhanna79 is the 14339 version publicly available? If not, we'll have to add about this patch to the release notes, as people will be running dotnet on 14300 nano.

**Comment by gkhanna79** [comment]
Nano folks should share an updated Nano build that contains the fix. @refaati When do you expect Nano build, with the loader fix, to be publicly available?

**Comment by Priya91** [comment]
Verified that this is working with 14339 vhd that was shared. Closing this issue, as @blackdwarf has been notified to include this in the release notes.
