### ISSUE TITLE
Update dot-new templates to move NetCoreApp Dependency into tfm-specific dependendencies

### ISSUE THREAD

**Issue by rustd** [dotnet/cli#2970]
## Steps to reproduce
We are updating the Web templates for RC2. See this issue for details https://github.com/aspnet/Templates/issues/544
The class/ console templates for dotnet new should follow the same pattern

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
@piotrpMSFT @blackdwarf Should we take this for RC2? Seems like a change that is happening in ASP.NET.

**Comment by blackdwarf** [comment]
For preview 2? Sure, why not, this is a very small change. I will do it (since I've already been doing the work there).

**Comment by blackdwarf** [comment]
@piotrpMSFT @rustd so, to be more clear, this change can only come in RC2 - Preview 2, not the current one (Preview 1), since it would reset the escrow build and I don't think the change is that important.

**Comment by piotrpMSFT** [comment]
Updating milestone to rtm.

**Comment by livarcocc** [comment]
@piotrpMSFT Yes. Though we probably need a preview2 milestone.

**Comment by piotrpMSFT** [comment]
yep, will set one up today.

**Comment by blackdwarf** [comment]
Yep.

**Comment by piotrpMSFT** [comment]
@blackdwarf can this come in today??

**Comment by piotrpMSFT** [comment]
Chatted with @blackdwarf. He will get this PR working tonight.

**Comment by blackdwarf** [comment]
The PR is updated, @eerhardt change makes all of this a breeze. :)
