### ISSUE TITLE
Executing stand alone app with sudo gives Failed to initialize CoreCLR, HRESULT: 0x8007001F

### ISSUE THREAD

**Issue by joepeer** [dotnet/cli#2971]
## Steps to reproduce

dotnet new
Modify project.json to make a standalone app:
1.  Remove type: "platform" for Microsoft.NETCore.App"
2.  Add runtimes section.  Ex:

```
 "runtimes": {
    "ubuntu.14.04-x64":{}
  },
```
1.  dotnet restore
2.  dotnet publish -r ubuntu.14.04-x64
3.  sudo ./bin/Debug/netcoreapp1.0/ubuntu.14.04-x64/publish/helloworld
## Expected  behavior

Hello World! should be printed in console
## Actual behavior

Failed to initialize CoreCLR, HRESULT: 0x8007001F
## Environment data

`dotnet --info` output:
dotnet --info
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

If I do chmod -R 777 on the output dir, sudo ./bin/Debug/netcoreapp1.0/ubuntu.14.04-x64/publish/helloworld will give expected results

**Comment by Sridhar-MS** [comment]
Can you try?
1. dotnet restore
2. sudo dotnet publish -r ubuntu.14.04-x64
3. sudo ./bin/Debug/netcoreapp1.0/ubuntu.14.04-x64/publish/helloworld

**Comment by joepeer** [comment]
Yes doing sudo dotnet publish works also.

**Comment by livarcocc** [comment]
@joepeer I don't think this is an RC2 issue so I am parking it under RTM. Let me know if you disagree.

**Comment by brthor** [comment]
My first guess is that we only set up permissions for the current user, which I'm not sure is wrong here.

@joepeer Could you share `ls -l` of your output directory.

**Comment by joepeer** [comment]
ls -l ./bin/Debug/netcoreapp1.0/ubuntu.14.04-x64/publish/
total 49760
-rwxrw-r-- 1 da da 8294560 Apr 26 21:09 libcoreclr.so
-rwxrw-r-- 1 da da  673656 Apr 26 21:09 libcoreclrtraceptprovider.so
-rwxrw-r-- 1 da da 1007272 Apr 26 21:09 libdbgshim.so
-rwxrw-r-- 1 da da  910658 May  8 21:23 libhostfxr.so
-rwxrw-r-- 1 da da 1139345 May  8 21:23 libhostpolicy.so
-rwxrw-r-- 1 da da 3544504 Apr 26 21:09 libmscordaccore.so
-rwxrw-r-- 1 da da 2252464 Apr 26 21:09 libmscordbi.so
-rwxrw-r-- 1 da da   69280 Apr 26 21:09 libsosplugin.so
-rwxrw-r-- 1 da da  529208 Apr 26 21:09 libsos.so
-rwxrw-r-- 1 da da 4204456 Apr 29 11:35 Microsoft.CodeAnalysis.CSharp.dll
-rwxrw-r-- 1 da da 2027416 Apr 29 11:35 Microsoft.CodeAnalysis.dll
-rwxrw-r-- 1 da da 5056432 Apr 29 11:35 Microsoft.CodeAnalysis.VisualBasic.dll
-rwxrw-r-- 1 da da  446664 Apr 26 21:18 Microsoft.CSharp.dll
-rwxrw-r-- 1 da da  188120 Apr 26 21:18 Microsoft.VisualBasic.dll
-rwxrw-r-- 1 da da   25328 Apr 26 21:18 Microsoft.Win32.Primitives.dll
-rwxrw-r-- 1 da da   24296 Apr 26 21:18 Microsoft.Win32.Registry.dll
-rwxrw-r-- 1 da da 2189824 Apr 26 21:09 mscorlib.dll
-rwxrw-r-- 1 da da 9446408 Apr 26 21:09 mscorlib.ni.dll
-rwxrw-r-- 1 da da   61414 Apr 26 21:09 sosdocsunix.txt
-rwxrw-r-- 1 da da   21856 Apr 26 21:18 System.AppContext.dll
-rwxrw-r-- 1 da da   29008 Apr 26 21:18 System.Buffers.dll
-rwxrw-r-- 1 da da   92912 Apr 26 21:18 System.Collections.Concurrent.dll
-rwxrw-r-- 1 da da   98000 Apr 26 21:18 System.Collections.dll
-rwxrw-r-- 1 da da  198896 Apr 26 21:18 System.Collections.Immutable.dll
-rwxrw-r-- 1 da da   88472 Apr 26 21:18 System.Collections.NonGeneric.dll
-rwxrw-r-- 1 da da   45464 Apr 26 21:18 System.Collections.Specialized.dll
-rwxrw-r-- 1 da da   82856 Apr 26 21:18 System.ComponentModel.Annotations.dll
-rwxrw-r-- 1 da da   21720 Apr 26 21:18 System.ComponentModel.dll
-rwxrw-r-- 1 da da   92864 Apr 26 21:18 System.Console.dll
-rwxrw-r-- 1 da da   40840 Apr 26 21:18 System.Diagnostics.Debug.dll
-rwxrw-r-- 1 da da   31152 Apr 26 21:18 System.Diagnostics.DiagnosticSource.dll
-rwxrw-r-- 1 da da   28432 Apr 26 21:18 System.Diagnostics.FileVersionInfo.dll
-rwxrw-r-- 1 da da   88464 Apr 26 21:18 System.Diagnostics.Process.dll
-rwxrw-r-- 1 da da   22936 Apr 26 21:18 System.Diagnostics.StackTrace.dll
-rwxrw-r-- 1 da da   22408 Apr 26 21:18 System.Diagnostics.Tools.dll
-rwxrw-r-- 1 da da   36752 Apr 26 21:18 System.Diagnostics.Tracing.dll
-rwxrw-r-- 1 da da  112864 Apr 26 21:18 System.Dynamic.Runtime.dll
-rwxrw-r-- 1 da da   22432 Apr 26 21:18 System.Globalization.Calendars.dll
-rwxrw-r-- 1 da da   22384 Apr 26 21:18 System.Globalization.dll
-rwxrw-r-- 1 da da   30464 Apr 26 21:18 System.Globalization.Extensions.dll
-rwxrw-r-- 1 da da   56944 Apr 26 21:09 System.Globalization.Native.so
-rwxrw-r-- 1 da da   86744 Apr 26 21:18 System.IO.Compression.dll
-rwxrw-r-- 1 da da   12930 Apr 26 21:09 System.IO.Compression.Native.so
-rwxrw-r-- 1 da da   29080 Apr 26 21:18 System.IO.Compression.ZipFile.dll
-rwxrw-r-- 1 da da   39232 Apr 26 21:18 System.IO.dll
-rwxrw-r-- 1 da da   95088 Apr 26 21:18 System.IO.FileSystem.dll
-rwxrw-r-- 1 da da   21920 Apr 26 21:18 System.IO.FileSystem.Primitives.dll
-rwxrw-r-- 1 da da   52984 Apr 26 21:18 System.IO.FileSystem.Watcher.dll
-rwxrw-r-- 1 da da   50928 Apr 26 21:18 System.IO.MemoryMappedFiles.dll
-rwxrw-r-- 1 da da   42400 Apr 26 21:18 System.IO.UnmanagedMemoryStream.dll
-rwxrw-r-- 1 da da  126792 Apr 26 21:18 System.Linq.dll
-rwxrw-r-- 1 da da  461024 Apr 26 21:18 System.Linq.Expressions.dll
-rwxrw-r-- 1 da da  223448 Apr 26 21:18 System.Linq.Parallel.dll
-rwxrw-r-- 1 da da   69840 Apr 26 21:18 System.Linq.Queryable.dll
-rwxrw-r-- 1 da da   92766 Apr 26 21:09 System.Native.a
-rwxrw-r-- 1 da da   74748 Apr 26 21:09 System.Native.so
-rwxrw-r-- 1 da da  271704 Apr 26 21:19 System.Net.Http.dll
-rwxrw-r-- 1 da da   20142 Apr 26 21:09 System.Net.Http.Native.so
-rwxrw-r-- 1 da da   68488 Apr 26 21:19 System.Net.NameResolution.dll
-rwxrw-r-- 1 da da  307928 Apr 26 21:18 System.Net.Primitives.dll
-rwxrw-r-- 1 da da   55152 Apr 26 21:19 System.Net.Requests.dll
-rwxrw-r-- 1 da da  223080 Apr 26 21:19 System.Net.Security.dll
-rwxrw-r-- 1 da da   14065 Apr 26 21:09 System.Net.Security.Native.so
-rwxrw-r-- 1 da da  219848 Apr 26 21:18 System.Net.Sockets.dll
-rwxrw-r-- 1 da da   39680 Apr 26 21:19 System.Net.WebHeaderCollection.dll
-rwxrw-r-- 1 da da  157056 Apr 26 21:19 System.Numerics.Vectors.dll
-rwxrw-r-- 1 da da   48848 Apr 26 21:19 System.ObjectModel.dll
-rwxrw-r-- 1 da da  125280 Apr 26 21:18 System.Private.Uri.dll
-rwxrw-r-- 1 da da   37784 Apr 26 21:19 System.Reflection.DispatchProxy.dll
-rwxrw-r-- 1 da da   22888 Apr 26 21:18 System.Reflection.dll
-rwxrw-r-- 1 da da   22392 Apr 26 21:19 System.Reflection.Emit.dll
-rwxrw-r-- 1 da da   22440 Apr 26 21:19 System.Reflection.Emit.ILGeneration.dll
-rwxrw-r-- 1 da da   21936 Apr 26 21:19 System.Reflection.Emit.Lightweight.dll
-rwxrw-r-- 1 da da   24824 Apr 26 21:18 System.Reflection.Extensions.dll
-rwxrw-r-- 1 da da  429296 Apr 26 21:19 System.Reflection.Metadata.dll
-rwxrw-r-- 1 da da   22264 Apr 26 21:18 System.Reflection.Primitives.dll
-rwxrw-r-- 1 da da   28584 Apr 26 21:19 System.Reflection.TypeExtensions.dll
-rwxrw-r-- 1 da da   32992 Apr 26 21:19 System.Resources.Reader.dll
-rwxrw-r-- 1 da da   22280 Apr 26 21:18 System.Resources.ResourceManager.dll
-rwxrw-r-- 1 da da   39768 Apr 26 21:18 System.Runtime.dll
-rwxrw-r-- 1 da da   73440 Apr 26 21:18 System.Runtime.Extensions.dll
-rwxrw-r-- 1 da da   22904 Apr 26 21:18 System.Runtime.Handles.dll
-rwxrw-r-- 1 da da   32160 Apr 26 21:18 System.Runtime.InteropServices.dll
-rwxrw-r-- 1 da da   29632 Apr 26 21:19 System.Runtime.InteropServices.PInvoke.dll
-rwxrw-r-- 1 da da   27112 Apr 26 21:18 System.Runtime.InteropServices.RuntimeInformation.dll
-rwxrw-r-- 1 da da   21720 Apr 26 21:19 System.Runtime.Loader.dll
-rwxrw-r-- 1 da da   70872 Apr 26 21:19 System.Runtime.Numerics.dll
-rwxrw-r-- 1 da da   57208 Apr 26 21:19 System.Security.Claims.dll
-rwxrw-r-- 1 da da   65976 Apr 26 21:19 System.Security.Cryptography.Algorithms.dll
-rwxrw-r-- 1 da da   29608 Apr 26 21:19 System.Security.Cryptography.Cng.dll
-rwxrw-r-- 1 da da   24328 Apr 26 21:19 System.Security.Cryptography.Csp.dll
-rwxrw-r-- 1 da da   49432 Apr 26 21:19 System.Security.Cryptography.Encoding.dll
-rwxrw-r-- 1 da da   96031 Apr 26 21:09 System.Security.Cryptography.Native.so
-rwxrw-r-- 1 da da   50456 Apr 26 21:19 System.Security.Cryptography.OpenSsl.dll
-rwxrw-r-- 1 da da   44992 Apr 26 21:19 System.Security.Cryptography.Primitives.dll
-rwxrw-r-- 1 da da  161600 Apr 26 21:19 System.Security.Cryptography.X509Certificates.dll
-rwxrw-r-- 1 da da   21224 Apr 26 21:19 System.Security.Principal.dll
-rwxrw-r-- 1 da da   28936 Apr 26 21:19 System.Security.Principal.Windows.dll
-rwxrw-r-- 1 da da  759552 Apr 26 21:19 System.Text.Encoding.CodePages.dll
-rwxrw-r-- 1 da da   22376 Apr 26 21:18 System.Text.Encoding.dll
-rwxrw-r-- 1 da da   22432 Apr 26 21:18 System.Text.Encoding.Extensions.dll
-rwxrw-r-- 1 da da  112896 Apr 26 21:19 System.Text.RegularExpressions.dll
-rwxrw-r-- 1 da da   50016 Apr 26 21:19 System.Threading.dll
-rwxrw-r-- 1 da da   23280 Apr 26 21:19 System.Threading.Overlapped.dll
-rwxrw-r-- 1 da da  177568 Apr 26 21:19 System.Threading.Tasks.Dataflow.dll
-rwxrw-r-- 1 da da   26488 Apr 26 21:18 System.Threading.Tasks.dll
-rwxrw-r-- 1 da da   24488 Apr 26 21:19 System.Threading.Tasks.Extensions.dll
-rwxrw-r-- 1 da da   58112 Apr 26 21:19 System.Threading.Tasks.Parallel.dll
-rwxrw-r-- 1 da da   22400 Apr 26 21:19 System.Threading.Thread.dll
-rwxrw-r-- 1 da da   22416 Apr 26 21:19 System.Threading.ThreadPool.dll
-rwxrw-r-- 1 da da   21880 Apr 26 21:18 System.Threading.Timer.dll
-rwxrw-r-- 1 da da  600800 Apr 26 21:19 System.Xml.ReaderWriter.dll
-rwxrw-r-- 1 da da  110800 Apr 26 21:19 System.Xml.XDocument.dll
-rwxrw-r-- 1 da da  137080 Apr 26 21:19 System.Xml.XmlDocument.dll
-rwxrw-r-- 1 da da  187232 Apr 26 21:19 System.Xml.XPath.dll
-rwxrw-r-- 1 da da   36752 Apr 26 21:19 System.Xml.XPath.XDocument.dll
-rwxrw-r-- 1 da da  128766 May  8 21:23 tata
-rwxrw-r-- 1 da da  110232 May 10 16:54 tata.deps.json
-rwxrw-r-- 1 da da    4608 May 10 16:54 tata.dll
-rwxrw-r-- 1 da da     400 May 10 16:54 tata.pdb
-rwxrw-r-- 1 da da      26 May 10 16:54 tata.runtimeconfig.json

**Comment by joepeer** [comment]
As soon as I do chmod +X to my binary (here it's tata) it works.

It's really the error message that didn't make it clear that it was missing the executable permission on my binary.

**Comment by alistair** [comment]
I ran into this issue in a docker container.   I dont believe this has anything to do with sudo as I was just running omnisharp (and hitting this) as root

**Comment by jdluzen** [comment]
I just got this as well in an interactive docker container. The difference for me is that I was running with `-u 999:999`. The same workaround works.

**Comment by livarcocc** [comment]
The host (dotnet) needs to have its permissions changed to allow this. The SDK does not alter the host's permissions, it has it's permissions set from the nupkg we consume for it. I am moving this issue to core-setup for it to be considered there.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3823

**Comment by AsianJohnBoi** [comment]
commands like docker and dotnet require you to run them on root. These commands create a new group when installed so adding your user to the group will escalate your privileges. 

Check the groups on your system `sudo cat /etc/group`
You can check this by going to location of the installed .net package. 
(In my case the group I had was `netdev:x:118` 
My package was stored in ~/.dotnet and inside contained
```
drwxr-xr-x 32 jsantias netdev 4096 Nov 10 21:23 ..
-rw-r--r--  1 netdev netdev    0 Nov 10 21:22 3.0.100.aspNetCertificateSentinel
-rw-r--r--  1 netdev netdev    0 Nov 10 21:22 3.0.100.dotnetFirstUseSentinel
-rw-r--r--  1 netdev netdev    5 Nov 10 21:22 3.0.100_IsDockerContainer.dotnetUserLevelCache
-rw-r--r--  1 netdev netdev   64 Nov 10 21:22 3.0.100_MachineId.dotnetUserLevelCache
-rw-r--r--  1 netdev netdev    0 Nov 10 21:22 3.0.100.toolpath.sentinel
drwxr-xr-x  3 netdev netdev 4096 Nov 10 21:22 corefx
drwxr-xr-x  3 netdev netdev 4096 Nov 10 21:17 optimizationdata
drwxr-xr-x  2 netdev netdev 4096 Nov 10 22:04 TelemetryStorageService
```

So running `sudo usermod -g netdev <username>` will allow you to run the dotnet without root. 
NOTE: this won't remove root access for your current projects. This will work with new projects you create after running this. (From my observation)
