### ISSUE TITLE
Runing a Tool with dependency on a different version of Newtonsoft.Json gives FileNotFoundException

### ISSUE THREAD

**Issue by lajones** [dotnet/cli#2972]
## Steps to reproduce
1 File|New Project|.NET Core|Console Application (.NET Core)
2 Call it `dotnet-ToolWithDependencyNetCore1_0`
3 Install-Package `Newtonsoft.Json -Version 7.0.1`
4 Add dependency on e.g. `JsonSerializer` into `Program.Main()` so that the tool depends on `Newtonsoft.Json v7.0.1`and also add a `Console.WriteLine("Hello from dotnet-ToolWithDependencyNetCore1_0")` so you can tell if the tool runs correctly.
5 `dotnet restore` and `dotnet pack` this project and place the `.nupkg` in a local feed.
6 Add that local feed to your `Nuget.config` so VS can pick up the tool in the next steps.
7 File|New Project|.NET Core|Console Application (.NET Core)
8 Call this one `Using-dotnet-ToolWithDependencyNetCore1_0`
9 Open the project.json and add a) a dependency on `"dotnet-ToolWithDependencyNetCore1_0": "1.0.0"` and b) add a `tools` section which looks like this:
```
  "tools": {
    "dotnet-ToolWithDependencyNetCore1_0": {
      "version": "1.0.0",
      "imports": [ "dnxcore50" ]
    }
  }
```
10 Install-Package `Newtonsoft.Json -Version 8.0.3`
11 Add dependency on e.g. `JsonSerializer` into `Program.Main()` so that the tool depends on `Newtonsoft.Json v7.0.1`and also add a `Console.WriteLine("Hello from Referencing Project")` so you can tell if the tool runs correctly.
12 Add a `Console.WriteLine()` in the `Program.Main()` method.
13 `dotnet restore` this project
14 `dotnet ToolWithDependencyNetCore1_0` (runs correctly - not sure if this step is needed for the repro)
15 `dotnet run` this project 

## Expected  behavior
`Hello from Referencing Project` written to the command line.

## Actual behavior
C:\work\RC2ReleaseTest\Using-dotnet-ToolWithDependencyNetCore1_0\src\Using-dotnet-ToolWithDependencyNetCore1_0>dotnet run
Project Using-dotnet-ToolWithDependencyNetCore1_0 (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Using_dotnet_ToolWithDependencyNetCore1_0.Program.Main(String[] args)

## Environment data
.NET Command Line Tools (1.0.0-rc2-002673)

Product Information:
 Version:     1.0.0-rc2-002673
 Commit Sha:  c0aeb91d61

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x86

**Comment by davidfowl** [comment]
This isn't a cli bug the tool is broken because dependencies are missing

**Comment by lajones** [comment]
Note: You can solve this problem by adding the `aspnetrelease` feed to your `Nuget.config` and adding a dependency on `"System.Runtime.Serialization.Primitives": "4.1.1-rc2-24018"` but I would have thought that that should not be necessary?

**Comment by lajones** [comment]
Note: this happens on Windows 10 x86 but not on Windows 10 x64.
