### ISSUE TITLE
Reenable publishing debian packages to the debian Repo feed

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2973]
As we move to preview2 I am disabling publishing the *.deb files into the debian repo. Because we do not want higher version (preview2) to override the preview1 builds. Once we find the right production feed for the preview1 *.deb file we can start publishing the preview2 *.deb files into the debian repo feed.

**Comment by brthor** [comment]
cc @blackdwarf

**Comment by blackdwarf** [comment]
@Sridhar-MS this means that users will ever only be able to get preview 1 bits from the apt-get feed?

**Comment by brthor** [comment]
@blackdwarf My understanding is that would the plan for the prod feed right? Until we release preview2?

The preview feed would just have whatever the latest is after we re-enable this.

**Comment by Sridhar-MS** [comment]
The idea is to not override the preview1 with preview2 build in the apt-get feed. At least until we are ready to ship preview2.

**Comment by brthor** [comment]
@Sridhar-MS we will override preview 1 in the preview apt-get feed I thought? In prod it will not be overridden?

**Comment by Sridhar-MS** [comment]
But do we have a prod feed yet?

**Comment by piotrpMSFT** [comment]
@brthor need the CLI version of this change today.

**Comment by brthor** [comment]
@piotrpMSFT This is in that giant PR along with ubuntu 16 deb packages

**Comment by brthor** [comment]
Looks like that went in, Fixed via #3555
