### ISSUE TITLE
Update the Microsoft.NETCore.App dependency from rc2 to rc3 for tests

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#2975]
The following tests need to be updated from rc2 to rc3 for the Microsoft.NETCore.App dependency

>cli\TestAssets\NonRestoredTestProjects\TestProjectWithUnresolvedDependency\project.json
cli\TestAssets\TestProjects\PortableTests\StandaloneApp\project.json
cli\TestAssets\TestProjects\ProjectsWithTests\MultipleFrameworkProject\project.json
cli\TestAssets\TestProjects\ProjectsWithTests\NetCoreAppOnlyProject\project.json

Since they need real RC3 package from the myget feed they have to be updated once https://github.com/dotnet/cli/pull/2954 goes in.

**Comment by piotrpMSFT** [comment]
@brthor is pretty sure this is done. He's validating, then closing.

**Comment by brthor** [comment]
There are a couple here which need updating.

**Comment by brthor** [comment]
EDIT: I was on an old commit, this is done.
