### ISSUE TITLE
CLI is buffering console output on 'dotnet run'

### ISSUE THREAD

**Issue by BillWagner** [dotnet/cli#2976]
## Steps to reproduce

Run the finished tutorial for this sample: https://github.com/dotnet/core-docs/tree/master/docs/tutorials/getting-started-with-csharp/console-teleprompter

It's been updated for RC2 on this fork / branch: https://github.com/BillWagner/core-docs/tree/RC2UpdatesForCSharpTutorials
## Expected  behavior

Each word should be echoed, with a pause between each word. You can see this if you use

```
dotnet .\bin\Debug\netcoreapp1.0\console-teleprompter.dll
```

instead of `dotnet run` to execute the sample.
## Actual behavior

When you run with `dotnet run`  the output comes line-by-line instead of word-by-word. The delays are also longer.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

/cc @blackdwarf

**Comment by billwert** [comment]
This is probably #2777

**Comment by piotrpMSFT** [comment]
Just tried atop rc3 bits and found this no longer repros for:

```
using System;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            while(true){Console.WriteLine(Console.ReadLine());}
        }
    }
}
```
