### ISSUE TITLE
dotnet restore does not update lock file for tools when imports are modified

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2977]
Restore caches the lock file and does not rebuild it if imports changes (which might cause the dependency graph to be rebuilt).

`dotnet --version`: `1.0.0-preview1-002700`

**Comment by livarcocc** [comment]
@pranavkm This seems like a NuGet bug. Can you open a bug there and close this one in favor of it?

**Comment by brthor** [comment]
@pranavkm Is it definitely the lock file and not deps file which is not being rebuilt?

**Comment by pranavkm** [comment]
Sorry, I think it's the deps file. @pakrym might have more info on this.

**Comment by pakrym** [comment]
`deps` file is not rebuild

**Comment by piotrpMSFT** [comment]
This is then a dupe of #2978
