### ISSUE TITLE
Tools deps file should not be cached in global location

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2978]
Changing tool imports produce different lock file but `deps` file is never regenerated. Customer need to remove deps file manually to force regeneration.

@davidfowl @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@brthor can you look into this?

**Comment by brthor** [comment]
@piotrpMSFT We have a discussion going in #2979

We will need to make some design changes.

**Comment by piotrpMSFT** [comment]
@brthor do we need both #2978 and #2979?

**Comment by livarcocc** [comment]
Imports are not longer supported for tools. Also, we are de-emphazising project tools in favor of global tools.
