### ISSUE TITLE
Tools lock file should not be written to global location

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#2979]
Changing tools import would produce different lock files which will conflict if storing in global location.
@davidfowl  @piotrpMSFT

**Comment by brthor** [comment]
cc @joelverhagen @emgarten 

This is a design issue with imports in tools. The package graph of an individual tool is dependent on the project and is not global because of imports. 

As long as we have imports I think we must move the lock file/deps file to be project local to solve this issue.

**Comment by joelverhagen** [comment]
@brthor, is the global lock file really needed? Can't the hosting project's lock file be inspected for the interesting bits of information, i.e. the `"tools"` and `"projectFileToolGroups"` sections in the lock file.

**Comment by brthor** [comment]
@joelverhagen That's a good solution but wouldn't we then need an entire lock file for the tool inside the lock file for the project?

**Comment by piotrpMSFT** [comment]
We need to figure out how to get rid of imports. What is being suggested here won't scale for global commands.

**Comment by brthor** [comment]
Removing import support would be ideal for retaining the current design. The issue there being many of the tools rely on imports for bringing in packages like IxAsync.

**Comment by piotrpMSFT** [comment]
Let's make the plan to remove imports by the time we RTM the CLI?

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5196
