### ISSUE TITLE
dynamic attribute not in netstandard? What package is required.

### ISSUE THREAD

**Issue by btrepp** [dotnet/cli#2982]
## Steps to reproduce

dotnet restore
dotnet build

in project that uses dynamic 

## Expected  behavior

Project compiles

## Actual behavior

```
error CS1980: Cannot define a class or member that utilizes 'dynamic' be
cause the compiler required type 'System.Runtime.CompilerServices.DynamicAttribu
te' cannot be found. Are you missing a reference?
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002416)

Product Information:
 Version:     1.0.0-rc2-002416
 Commit Sha:  37f00f24e9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

I've tried to add the dynamic attributes in via below. But that doesn't seem to work.
What package is required to use dynamic in netstandard?.
```
    "netstandard1.4": {
      "dependencies": {
        "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc3-20831",
        "NETStandard.Library": "1.5.0-rc3-24110-00",
        "runtime.any.System.Dynamic.Runtime": "4.0.10-rc3-23915",
        "System.Runtime.Serialization.Primitives": "4.1.1-rc3-23910"
      }
    }

```

**Comment by btrepp** [comment]
So apparently I needed "System.Dynamic.Runtime":"4.0.11-rc3-24110-00"

**Comment by dora-gt** [comment]
@btrepp how did you solve it?

**Comment by btrepp** [comment]
Afaik I just added that package in dependencies. Not even sure what project I used this in and I'm using the 2.0 SDK everywhere now instead :(
