### ISSUE TITLE
Localization files are not bin placed

### ISSUE THREAD

**Issue by ramarag** [dotnet/cli#2983]
When a .net "legacy" library is referenced from an application targeting net46, the localized resources are not working properly, and neutral culture resources are being used.

Steps to reproduce: https://gist.github.com/joplaal/5e7399d126f2bd79336a65569932fbd1

(A console app using FluentValidator, that has resources in spanish)

Targeting dnx46, with dnx run, works properly. But targeting net46 and using dotnet run, it doesn't.

/cc @joplaal

**Comment by piotrpMSFT** [comment]
chatted with @ramarag. This is not a release blocker.

**Comment by nguerrera** [comment]
This has been fixed in the csproj tooling as of https://github.com/dotnet/sdk/pull/1224.
