### ISSUE TITLE
Unable to load DLL 'sqlite3': The specified module could not be found. On CentOS7.2  using corecli.

### ISSUE THREAD

**Issue by 18583690825** [dotnet/cli#2984]
## Steps to reproduce
As the title:

> ......
Compilation succeeded.
    132 Warning(s)
    0 Error(s)
Time elapsed 00:00:06.5318837
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'sqlite3': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at ConsoleApplication.Program.Main(String[] args)
[root@localhost TestEntry]# 

And this is my project.json:

> {
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "TestReference": { "target": "project" },
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-*"
    },
    "System.Runtime": "4.1.0-rc2-23811",
    "Microsoft.Data.SQLite": "1.0.0-rc1-final",
    "System.IO": "4.1.0-rc2-23811",
    "System.IO.FileSystem": "4.0.1-rc2-23811"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
	"centos.7-x64": {}
  }
}

In fact, i can't find the `sqlite3.dll` from the folder `/root/.nuget/packages/Microsoft.Data.SQLite/1.0.0-rc1-final/build/netcore50/CentOS/native` .Actually there weren't a directory named 'CentOS', i could only find win10-arm,w10-x86 & win10-x64.
And then i tried installed a Sqlite on my system,and i tried to create a file link to my project directory or copy the sqlite.dll to the `.nuget` directory, but it didn't work either.

> [root@localhost TestEntry]# sqlite3
SQLite version 3.12.2 2016-04-18 17:30:31
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

Where do the program goes to search the dll?Could anyone give me a hand..Thanks a lot!

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002701)

Product Information:
 Version:     1.0.0-preview1-002701
 Commit Sha:  11492c7fac

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64

**Comment by jeremymeng** [comment]
This seems unrelated to dotnet/cli.

You probably need to install libsqlite3-dev package as sqlite3.dll is a native dll.  On Linux I'd expect a `.so` library corresponding to that.  Even with that I am not sure about the Linux support of `Microsoft.Data.Sqlite`.

**Comment by 18583690825** [comment]
@jeremymeng Exactly,THX a lot ! `yum install sqlite-devel` had solved it.
However,under Windows,i only added a reference to the `project.json` like: ` "Microsoft.Data.SQLite": "1.0.0-rc1-final"` and then every thing had been nicely prepared ,even as the sqlite3.dll, had been restored into the .nuget directory. But under Linux, it didn't restore the sqlite package so that maybe we should install it by ourself. If this, how do i know which library would be restored as a .nuget package under Win but the one wouldn't be under Linux.Doesn't the package should be restore automatic?

**Comment by jeremymeng** [comment]
@18583690825 I guess it is hard or infeasible to package native dependencies for various Linux distros and versions, as it is very likely to hit incompatible dependency issue.  On Windows it's much easier (probably just need to care about x64 and x86 and that's all).

**Comment by 18583690825** [comment]
@jeremymeng Oh i see.You're right.It is difficault to unified such many linux operation systems.😂Perhaps i need to prepare variety kinds of libraris for different linuxs in order to run apps on them.Thank you again!
