### ISSUE TITLE
Installing packages appends many times to /etc/paths.d/dotnet

### ISSUE THREAD

**Issue by vcsjones** [dotnet/cli#2988]
## Steps to reproduce

Run the .pkg for the SDK installer multiple times. Can be the same version, can be different ones.

## Expected  behavior

The `/etc/paths.d/dotnet` file contains a single line to the path of where the CLI tools are run.

## Actual behavior

Every time the package installer is run, another path line is added:

```
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
/usr/local/share/dotnet
..etc
```

I only discovered this because it looks like at some point, the path was once `/usr/local/share/dotnet/bin`, which was getting added to my path and causing problems.

## Environment data
`dotnet --info` output:

>.NET Command Line Tools (1.0.0-preview1-002700)
>
>Product Information:
> Version:     1.0.0-preview1-002700
> Commit Sha:  0336f6bb34

>Runtime Environment:
> OS Name:     Mac OS X
> OS Version:  10.11
> OS Platform: Darwin
> RID:         osx.10.11-x64

**Comment by oold** [comment]
Apparently, it also doesn't clean old versions. My old dotnet binary still exists in the bin directory.

**Comment by vcsjones** [comment]
Migrated to dotnet/core-setup#18.
