### ISSUE TITLE
Razor not copied to folder on change

### ISSUE THREAD

**Issue by BeelzeBu** [dotnet/cli#2989]
When I change only a razor (cshtml) page and build/rebuild the solution I do not see the changes applied, files dont get copied to build folder. need to remove bin folder or change a controller to copy all new razor content.
## Steps to reproduce

modify a razor page (.cshtml)
## Expected  behaviour

always copy content files even if they are not changed
## Actual behaviour

Does not copy Views unless a .cs file has been modified.
## Environment data

`dotnet --info` output:

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by GuardRex** [comment]
@BeelzeBu Sort of a dup of my https://github.com/dotnet/cli/issues/1614 ... however ... I thought that this was fixed. I re-opened that issue as there is some MS Team communication on that one. These issues are cross-linked now.

**Comment by blackdwarf** [comment]
Since this issue is the same as #3176 and that one is verified to not repro in MSBuild, I took a look at this one as well. Also does not repro in the Preview 4 (MSBuild-based) tooling. I will close this issue as well. If this should repro, please reopen.
