### ISSUE TITLE
Simple project(.json) Format

### ISSUE THREAD

**Issue by oaiey** [dotnet/cli#2992]
After hearing the msbuild announcement and the feedback on Twitter by @davidfowl, @DamianEdwards and @davkean and @terrajobst , I wonder whether there would be space for a simple project format. Something which could be automatically converted into a full fledged msbuild project file in-memory before going to the msbuild pipeline? Since there is already some project.json tooling it would be even have some support in VS. A file based convert option would even allow a seamless growing into a better tooling.

That would make the web crowd and command line people happy and would allow to still reach the goals of the msbuild switch.

**Comment by shederman** [comment]
Just keep in mind a lot of the noise is less to do with XML, and more to do with going back to MSBuild...

**Comment by livarcocc** [comment]
This is not something that we have been looking at and we have no plans to move into something different from msbuild.
