### ISSUE TITLE
Optimize common patterns, specificially in this case x%2 where x is an integer.

### ISSUE THREAD

**Issue by SunnyWar** [dotnet/cli#2994]
## Steps to reproduce
compare how the compile deals with x%2 versus x&1. It should be the same but isn't.

`for (var i = 0; i < iterations; i++)
            {
                var x = i%2;
                if (x == 0)
                {
                    count++;
                }
            }`

 Look at the generated assembly for the i%2 part:
00DE2E13  mov         eax,edx  
00DE2E15  and         eax,80000001h  
00DE2E1A  jns         00DE2E21  
00DE2E1C  dec         eax  
00DE2E1D  or          eax,0FFFFFFFEh  
00DE2E20  inc         eax  
00DE2E21  test        eax,eax  
00DE2E23  jne         00DE2E26  

compare it to this:
`for (var i = 0; i < iterations; i++)
            {
                var x = i & 1;
                if (x == 0)
                {
                    count++;
                }
            }`

00672E9B  test        edx,1  
00672EA1  jne         00672EA

## Expected  behavior
recognized the %2 pattern and replace it with &1 so that it can be optimized.

## Actual behavior
It's not optimal.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This is a compiler improvement, not a CLI one. Please open this issue at the roslyn repo.

**Comment by SunnyWar** [comment]
[https://github.com/dotnet/roslyn/issues/11261](url)

**Comment by svick** [comment]
@SunnyWar I expect [CoreCLR](https://github.com/dotnet/coreclr/) is the right repo, since CLR is what actually generates assembly.

**Comment by SunnyWar** [comment]
@svick This isn't about machine code. it's about substituion. The machine code that I showed is to demonstrate the x&1 IS OPTIMIZED. So Roslyn just has to do the substitution.
