### ISSUE TITLE
Project Model Server should change types of dependencies back to package when corresponding path is removed from global.json

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#2995]
_This issue is reported by @abpiskunov . I haven't start reproducing this without tooling yet._

## Steps to reproduce

1. User adds a path to global.json and new projects are picked up after restore
2. The Project Model Server sends them as project references
3. User removes path from global.json
4. Restore starts and tooling passes all project references to *.dg file which creates a lock file with projects that should not be there since global.json does not have a path pointing to them.
 
## Expected  behavior
Some dependencies types are revert back to `package`.

## Actual behavior

Tooling still receives project references from project model server after path was removed from `global.json` and sends them to restore.

## Environment data
`dotnet --info` output:

**Comment by abpiskunov** [comment]
in step 3, if restore did not start - start it manually (there is another bug in TFS on that)

**Comment by abpiskunov** [comment]
@troydai any updates on this issue?

**Comment by troydai** [comment]
PR is out waiting for sign off. It's preview3 issue now.

**Comment by troydai** [comment]
Fixed in https://github.com/dotnet/cli/commit/c321323dff7e397801fface8795027339e234d15
