### ISSUE TITLE
Should dotnet publish take more than 20 mins - very slow publish

### ISSUE THREAD

**Issue by jamesgibbs100** [dotnet/cli#2997]
It is taking ages to publish a standalone app - upward of 20 mins on Windows and more on Linux. 
The Linux build server is now approaching an hour of runtime of which all but 7 minutes is the publish step.

I am wondering what factors might make this take such a long time ?

Is there a trace flag I can turn on or some such ??

On it took about 7 min. on the same Linux box with this version of dotnet cli

_UPDATE : Linux build machine returned with about 50 min publish time for both win7-x64 and ubuntu10.04-x64 runtimes_

.NET Command Line Tools (1.0.0-rc2-002600)
Product Information:
Version:     1.0.0-rc2-002600
Commit Sha:  c907d52451
Runtime Environment:
OS Name:     ubuntu
OS Version:  14.04
OS Platform: Linux
RID:         ubuntu.14.04-x64
## Steps to reproduce

Take a non trivial project (this is a port of an existing application)
Restore it : dotnet restore
Publish it  :dotnet publish
## Expected  behavior

The publish should occur in a reasonable timeframe
## Actual behavior

It takes 20 mins on Windows and on Linux its still running and I will expect to timeout
There is also no information on progress which makes it a bit unnerving.
## Environment data

.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by jamesgibbs100** [comment]
Update :

I moved to the portable app model as opposed to the standalone model and publish times came down to something workable.

This was prompted by the above but also realizing that native dependencies were not included into the publish - therefore some form of specialized platform was still necessary even in a "standalone" model.

**Comment by piotrpMSFT** [comment]
I've not been able to repro this. If this is still an issue for you, could you open a new issue with a pointer to a repro?

**Comment by jonjomckay** [comment]
@piotrpMSFT there's a bit more information inside #4148 if it helps?

**Comment by piotrpMSFT** [comment]
thanks @jonjomckay I'm working through the backlog and will try to look at it when i get to 4148 :)
