### ISSUE TITLE
Produce a file with the versions for packages produced as part of build

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#2999]
There's a file at https://raw.githubusercontent.com/dotnet/versions/master/build-info/dotnet/cli/rel/1.0.0-preview1/Latest_Packages.txt that contains the versions for packages produced by the CLI build. @eerhardt created one for preview1 but there's none available for preview2. This is required for AspNet to pick up the right set of CLI packages.

**Comment by eerhardt** [comment]
I'm working on fixing this.

**Comment by eerhardt** [comment]
This issue is now fixed with #3092 and adding the appropriate build steps.

See https://github.com/dotnet/versions/blob/master/build-info/dotnet/cli/rel/1.0.0/Latest_Packages.txt
