### ISSUE TITLE
dotnet -? should list --help as a subcommand for each command

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#300]
Today, -? is this: 
.NET Command Line Interface
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output

Common Commands:
  compile       Compiles a .NET project
  publish       Publishes a .NET project for deployment
  run           Compiles and immediately executes a .NET project

dotnet <common command> --help is a valid command that lists options for each common command, but there's nothing to tell the user that.

**Comment by piotrpMSFT** [comment]
`-?` is no longer a supported option.
