### ISSUE TITLE
dotnet publish of a netcoreapp contains files that are part of netcoreapp cache

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#3000]
## Steps to reproduce

dotnet new
vi project.json  (this is a simplification of the app I have)
{
  "version" : "1.0.27-*",
  "compilationOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "dependencies": {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-20507",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-20507",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002359"
    },
    "Newtonsoft.Json": "8.0.3",
    "System.Runtime.Serialization.Primitives" : "4.1.1-rc2-_",
    "System.Dynamic.Runtime": "4.0.10",
    "WindowsAzure.Storage": "7.0.1-preview",
    "System.Net.Requests": "4.0.0-rc2-_",
    "System.Diagnostics.Process": "4.1.0-rc2-24008"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "content": [
    "wwwroot"
  ],

  "exclude": [
    "node_modules"
  ]
}
dotnet publish
## Expected  behavior

the publish directory should have 171 files (45 in the top directory)
## Actual behavior

There are 221 files (70 in the top directory) including a number that are in the netcoreapp cache

System.Buffers.dll
System.Collections.Concurrent.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.StackTrace.dll
System.Dynamic.Runtime.dll
System.IO.FileSystem.Primitives.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Numerics.Vectors.dll
System.ObjectModel.dll
System.Reflection.Emit.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.TypeExtensions.dll
System.Runtime.InteropServices.PInvoke.dll
System.Runtime.Numerics.dll
System.Security.Claims.dll
System.Security.Cryptography.Primitives.dll
System.Security.Principal.dll
System.Text.RegularExpressions.dll
System.Threading.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
## Environment data

`dotnet --info` output:

Shared\Microsoft.NETCore.App
- 1.0.0-rc2-300246
- 1.0.0-rc2-3002700

.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@jeffschwMSFT I just tried to repro this on preview3. First, I moved the project.json to preview2 format:

```
{
  "version": "1.0.27-*",
  "dependencies": {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-20507",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-20507",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002359"
    },
    "Newtonsoft.Json": "8.0.3",
    "System.Runtime.Serialization.Primitives": "4.1.1-rc2-",
    "System.Dynamic.Runtime": "4.0.10",
    "WindowsAzure.Storage": "7.0.1-preview",
    "System.Net.Requests": "4.0.0-rc2-",
    "System.Diagnostics.Process": "4.1.0-rc2-24008"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  "buildOptions":{
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": "wwwroot"
  },
  "publishOptions":{
    "include":[
      "wwwroot"
    ],
    "exclude": [
      "node_modules"
    ]
  }
}
```

Next, I ran 
- `dotnet migrate`
- `dotnet restore`
- `dotnet publish`
- cd to publish directory
- `ls -l ** | wc -l`

This gave me a figure of 205 files. Though I did find some of the overlapping content you mentioned, it existed in the refs directory which is needed for compilation of razor views. This is enabled through the PreserveCompilationContext setting. I then flipped that setting to `false` and re-published. This gave me 116 files without the aforementioned overlap.
