### ISSUE TITLE
unable to resolve 'System.Threading.Thread (>= 4.0.0-rc2-23811)' for 'DNXCore,Version=v5.0 (ubuntu.14.04-x64)

### ISSUE THREAD

**Issue by mutex007** [dotnet/cli#3006]
Hi, could you please advice if what i am doing is currently supported.

.NET Command Line Tools (1.0.0-preview1-002701)

Product Information:
 Version:     1.0.0-preview1-002701
 Commit Sha:  11492c7fac

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

This is the project.json file.

{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true,
	"allowUnsafe": true
    },

    "runtimes": { 
	"ubuntu.14.04-x64": {}
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23811", 
        "runtime.linux.System.Diagnostics.Process": "4.1.0-beta-23516", 
  	"runtime.linux.System.IO.FileSystem.Watcher": "4.0.0-beta-23516", 
	"runtime.linux.System.Net.Http": "4.0.1-beta-23516",
   	"Newtonsoft.Json": "8.0.2", 
	"runtime.unix.System.Net.Requests": "4.0.11-beta-23516", 
	"System.IO": "4.0.10",
	"runtime.unix.System.Threading": "4.0.11-beta-23516", 
	"System.Threading.Thread": "4.0.0-beta-23516"
    },

    "frameworks": {
	"dnxcore50":{}
    }
}

Regards

**Comment by eerhardt** [comment]
@mutex007 your dependencies are for old versions of CoreFX.  Can you update them to the latest RC2?

Also, you should not have to reference any "runtime.XXX" package.  I think your project.json could look like this:

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true,
	"allowUnsafe": true
    },

    "runtimes": { 
	"ubuntu.14.04-x64": {}
    },

    "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-24027", 
   	"Newtonsoft.Json": "8.0.2", 
	"System.Threading.Thread": "4.0.0-rc2-24027"
    },

    "frameworks": {
	"dnxcore50":{}
    }
}
```

**Comment by mutex007** [comment]
Thanks, will try it out tonight.

**Comment by blackdwarf** [comment]
@mutex007 this @eerhardt suggestion solve your problem?

**Comment by herikx2k3** [comment]
Works now, however byte* gives me a CLS compliant error too many of them filling up the terminal no way to actually see the actual compile errors to fix. Is there a way to disable these warnings. dotnet run --help does not appear to have an option to disable warnings.

Thanks once again.

**Comment by mutex007** [comment]
Works now, however byte* gives me a CLS compliant error too many of them filling up the terminal no way to actually see the actual compile errors to fix. Is there a way to disable these warnings. dotnet run --help does not appear to have an option to disable warnings.

Thanks once again.

**Comment by mellinoe** [comment]
That is most likely because you have declared your assembly as CLS Compliant. Pointer types are not CLS compliant.

**Comment by mutex007** [comment]
Thanks. it appears a third party lib i download had declared cscompliant in the assembly.cs file. Removing it solved the problem.
