### ISSUE TITLE
New version file has a commit hash on first line and version on second

### ISSUE THREAD

**Issue by am11** [dotnet/cli#3008]
When `-version Latest` is passed as argument, the install.ps1 and install.sh1 call the following URL to get a latest number, . https://dotnetcli.blob.core.windows.net/dotnet/preview/dnvm/latest.win.x64.version

The file produced for latest commit in blob has a commit hash on the first line and version on the second, instead of just one line with version.

Therefore, at the moment, `install.ps1` is failing with:

```powershell
C:\Users\Adeel\source\repos\dotnet-cli [rel/1.0.0]> scripts/obtain/install.ps1 -Channel preview -version Latest -InstallDir ./.dotnetcli -NoPath
C:\Users\Adeel\source\repos\dotnet-cli\scripts\obtain\install.ps1 : Cannot convert argument "bytes", with value:
"9b9ddd2e43dc40627094a776c0d18a1da5e0281a
1.0.0-preview2-002720
", for "GetString" to type "System.Byte[]": "Cannot convert value "9b9ddd2e43dc40627094a776c0d18a1da5e0281a
1.0.0-preview2-002720
" to type "System.Byte[]". Error: "Cannot convert value "9b9ddd2e43dc40627094a776c0d18a1da5e0281a
1.0.0-preview2-002720
" to type "System.Byte". Error: "Input string was not in a correct format."""
At line:3 char:1
+ .\scripts\obtain\install.ps1 -Channel preview -version Latest -InstallDir "$ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [install.ps1], MethodException
    + FullyQualifiedErrorId : MethodArgumentConversionInvalidCastArgument,install.ps1
```

If this is intentional to keep commit on the first line, should the install.ps1 and install.sh be changed accordingly (and parse the second line)?

**Comment by livarcocc** [comment]
This issue was not due to the file having the commit hash and version on it. The install script handles that. This issue happened because of a change in mime type of the version file.

This PR fixed it: https://github.com/dotnet/cli/pull/3011

**Comment by Sridhar-MS** [comment]
@am11 can you try using the install scripts to get the latest? https://github.com/dotnet/cli/commit/d906524dec52f2a89836399943aa02e0514c2c13 fixed it.

**Comment by am11** [comment]
It worked. Thanks for the quick fix! 🎉
