### ISSUE TITLE
Fix nupkg publishing for DotNetHost and Microsoft.NETCore.App packages

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3012]
There are 2 problems with our publishing of the corehost and meta package:

1. Currently we are pushing the corehost and NETCore.App packages to a folder in Azure storage under the CLI version: https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/dotnet-cli-build/PublishTargets.cs#L230.  This is incorrect because the corehost and NETCore.App packages have a different versioning scheme (`rc3` vs. `preview2`).
 - When we fix this, we need to fix the publishing script as well: https://github.com/dotnet/cli/blob/weshaggard-PublishPackagesToNuget/scripts/dotnet-cli-build/PublishTargets.cs#L349-L352
 - Honestly, this publishing script should get merged into our real branch, and not hanging out in this private branch.

1. More importantly, our `rc3` package aren't being pushed to MyGet right now.  This is because we changed our {Channel} from `beta` to `preview`.  The publishing script is still on the old `beta` channel and needs to be upgraded to `preview`.  (Again we should move the publishing script into the real branch so it picks these kinds of changes up automatically.)

@piotrpMSFT @weshaggard @brthor @Sridhar-MS @livarcocc

**Comment by weshaggard** [comment]
I agree with all the statements. However I'm less clear about which Azure storage blob to use, as long as it is logically part of the CLI I would expect it to be in the same blob as the rest of CLI. If we move these to another repo or build then we should definitely use a different blob.

**Comment by eerhardt** [comment]
> If we move these to another repo or build then we should definitely use a different blob.

Agreed. When we move these to another repo, moving them to another azure storage blob makes sense.  But we can't wait until we move to another repo to fix this. We need the `rc3` packages to be published to myget now so people can start consuming them.

**Comment by weshaggard** [comment]
Assuming the rel/1.0.0 branch is open for changes now, I'm not sure if it is or not, then we should just get this merged into that branch. I pinged @sokket to try and get this into the same publish pipeline as we are publishing the rest of the CLI. I think that is the best thing to do until we ultimately split them into another repo.

**Comment by eerhardt** [comment]
> Assuming the rel/1.0.0 branch is open for changes now

It is open for "Preview2" work.  So we should be good there.
