### ISSUE TITLE
Add missing `userSecretsId` property to the `project.json` schema

### ISSUE THREAD

**Issue by dougbu** [dotnet/cli#3014]
## Steps to reproduce
1. Open VS in an existing .NET Core web project
2. Open the `project.json` file
3. Attempt to add the `userSecretsId` property

## Expected  behavior
- A suggestion once I've typed `u` for the property name.
- Addition of double quotes around the value once I've typed the `:` between name and value.

## Actual behavior
Nope, no help at all.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by am11** [comment]
It seems like this key was only present in beta4 schema: [project-1.0.0-beta4.json#L417](https://github.com/SchemaStore/schemastore/blob/0207d3ea8c1e28f93638f679e205d3e161cb6a7a/src/schemas/json/project-1.0.0-beta4.json#L417) and missing from current [`project.json`](https://github.com/SchemaStore/schemastore/blob/0207d3ea8c1e28f93638f679e205d3e161cb6a7a/src/schemas/json/project.json).

**Comment by Eilon** [comment]
@dougbu I think this bug would go in our own UserSecrets repo because there's nothing in CLI to fix for this. Every team owns their own schema. Recommend closing this bug.

**Comment by dougbu** [comment]
@Eilon isn't the `project.json` schema hosted here then uploaded to http://json.schemastore.org/ ?

**Comment by Eilon** [comment]
Talked to @dougbu in person, this bug should move. No bug for CLI on this.

**Comment by dougbu** [comment]
This issue was moved to aspnet/UserSecrets#80
