### ISSUE TITLE
Improve schema for `tools` property in the `project.json` schema

### ISSUE THREAD

**Issue by dougbu** [dotnet/cli#3015]
## Steps to reproduce
1. Open VS in an existing .NET Core web project
2. Open the `project.json` file
3. Add a `tools` property
4. Add a `Microsoft.Extensions.SecurityManager.Tools` property in the `tools` object
5. Choose the `{}` option
6. Fill in the suggested `version` property in the `Microsoft.Extensions.SecurityManager.Tools` object
7. Add a comma after the `version` property
## Expected  behavior
- A suggestion to add an `imports` property
## Actual behavior

Nope, no help at all. The schema supports `imports` only within `frameworks`.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by Eilon** [comment]
ASP.NET does not own `project.json` schema. However, @ajaybhargavb recently did a bunch of fixes for project.json schema in SchemaStore, but I don't think this was included.

**Comment by piotrpMSFT** [comment]
Starting with preview3, the `tools` node capabilities were migrated to `<DotNetCliToolReference>` items. These items do not support imports. Tools need to be netcoreapp1.0 compatible and their dependencies must as well. If a dependency is needed which does not have a compatible nupkg then it will need to ship with the tool.
