### ISSUE TITLE
Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll'

### ISSUE THREAD

**Issue by smitpatel** [dotnet/cli#3016]
## Steps to reproduce
project.json
```
{
  "version": "1.0.0-*",
  "dependencies": {
    "dotnet-test-xunit": "1.0.0-*",
    "xunit": "2.1.0"
  },
  "testRunner": "xunit",
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net45+win8" ],
      "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.0.0-*"
      }
    },
    "net451": { },
    "net452": { },
    "net46": { },
    "net461": { }
  }
}
```
Commands to run:
```
dotnet restore --infer-runtimes
dotnet test
```
## Expected  behavior
Tests are run for all frameworks (there are 5 of them)

## Actual behavior
Tests run for only netcoreapp. For other frameworks it throws exception:
```
xUnit.net Runner (64-bit win7-x64)
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

## Environment data
`dotnet --info` output:
Machine 1:
```
.NET Command Line Tools (1.0.0-rc2-002673)

Product Information:
 Version:     1.0.0-rc2-002673
 Commit Sha:  c0aeb91d61

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```
Machine 2:
```
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:
 Version:     1.0.0-rc2-002678
 Commit Sha:  3b2ea9d14b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

What am I missing here?

**Comment by smitpatel** [comment]
Adding dependency to `"Microsoft.NETCore.Platforms": "1.0.1-*"` or `"NETStandard.Library": "1.5.0-*"` make it work. Which one to use and why?

**Comment by smitpatel** [comment]
Dependency to `Microsoft.NETCore.Platforms` needed for RID graph which was missing. Any package which has transitive dependency on it (like `NETStandard.Library`) could also make things work.

**Comment by alexandru-calinoiu** [comment]
@smitpatel do you mind eloborating on your explanation, I hit the same issue today and adding `Microsoft.NETCore.Platforms` worked.

What is `RID` graph?

**Comment by natemcmaster** [comment]
@alexandru-calinoiu it's one of those magical, internal, undocumented things. http://www.natemcmaster.com/blog/2016/05/19/nuget3-rid-graph/

**Comment by mkumar100** [comment]
I am working on TesseractEngine in a Console application.
I have added Microsoft.NETCore.Platforms to the solution, through Nuget.
While building it, I get the error:
Unable to load DLL 'Microsoft.DiaSymReader.Native.amd64.dll
I have attached Program.cs as Program.txt for your reference.
[Program.txt](https://github.com/dotnet/cli/files/2327802/Program.txt)
Please help here.
