### ISSUE TITLE
problem with NETStandard.Library >= 1.5.0-rc2-24027 could not be resolved

### ISSUE THREAD

**Issue by joganet** [dotnet/cli#3017]
## Steps to reproduce

I have a project that have a dependency with a custom library, the library target the framework netstandard1.5 and have the dependency of NetStandard.Library": "1.5.0-rc2-\* that is ok so far.
 that project is a console app, it target the netcoreapp1.0 and have a dependency "Microsoft.NETCore.App": {
          "version": "1.0.0-rc2-*",
          "type": "platform"
        }

the project.json of the console app is
`
{
  "version": "1.0.0-alpha-*",
  "description": "MySql.Data.MySqlClient.Test Console",
  "authors": [ "Oracle" ],
  "copyright": "Copyright © 2016, Oracle and/or its affiliates. All rights reserved.",

  "buildOptions": {
    "define": [ "DNXCORE50" ],
    "warningsAsErrors": false,
    "copyToOutput": {
      "contentFiles": [ "appsettings.json" ]
    }
  },

  "commands": {
    "MySql.Core.Test.Console": "MySql.Core.Test.Console"
  },

  "dependencies": {
    "NetStandard.Library": "1.5.0-rc2-_",
    "System.Data.Common": "4.0.1-rc2-_",
    "Microsoft.NETCore.Platforms": "1.0.1-*",
    "MySql.Data.MySqlClient": "1.0.0-alpha"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-rc2-*",
          "type": "platform"
        }
      }
    }
  }
}
`

when compiles throw an exception

Project MySql.Data.MySqlClient (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project MySql.Core.Test.Console (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling MySql.Core.Test.Console for .NETCoreApp,Version=v1.0
C:\Wex\Cnet 610 netcore\Source\MySql.Data.Core\src\MySql.Core.Test.Console\project.json(33,35): error NU1001: The dependency NETStandard.Library >= 1.5.0-rc2-24027 could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)
## Expected  behavior

Compiles with out a problem, but looks like it trying to look for a NetStandard.Library version 1.5.0-rc2-24027 but it has already downloaded the latest version (that is not that 24027), so probably is a fixed version or the name is incorrect because is named NETStandard and is specified NetStandard
## Actual behavior

is throwing the exception given before
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002611)

Product Information:
 Version:     1.0.0-rc2-002611
 Commit Sha:  bf8f0edd89

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by dasMulli** [comment]
did `dotnet restore` work? what puget-feeds are you using (`nuget.config`).
btw if you depend on `Microsoft.NETCore.App`, you shouldn't need to add `NETStandard.Library` as a dependency.

**Comment by joganet** [comment]
dotnet restore work, at least I didn't see any error, but when I try to compile the error show up, I just added the library to see if that solve the problem but no, the library that I add use the NetStandard.Library

let me share the custom library project.json

the restore and the build in the custom library works like a charm
the custom library is "MySql.Data.MySqlClient": "1.0.0-alpha" a port for the core framework

{
  "version": "1.0.0-alpha-*",
  "description": "MySql.Data.MySqlClient .Net Core Class Library",
  "authors": [ "Oracle" ],
  "copyright": "Copyright © 2016, Oracle and/or its affiliates. All rights reserved.",

  "packOptions": {
    "projectUrl": "http://dev.mysql.com/downloads/",
    "licenseUrl": "http://www.gnu.org/licenses/old-licenses/gpl-2.0.html",
    "iconUrl": "http://www.mysql.com/common/logos/logo-mysql-170x115.png",
    "tags": [ "MySql", ".NET Connector", "MySql Connector/NET", "netcore", ".Net Core", "MySql Conector/Net Core", "coreclr", "C/NET", "C/Net Core" ],
    "content": "content/Readme.txt",
    "releaseNotes": "Review Readme.txt for details.",
    "requireLicenseAcceptance": true
  },

  "buildOptions": {
    "define": [ "DNXCORE50" ],
    "warningsAsErrors": false,
    "embed": [ "Properties/ReservedWords.txt" ],
    "exclude": [ "Extensions/Net40/**/*.*" ]
  },


  "dependencies": {
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-*",
    "NetStandard.Library": "1.5.0-rc2-*",
    "System.Collections.NonGeneric": "4.0.1-rc2-*",
    "System.ComponentModel": "4.0.1-rc2-*",
    "System.ComponentModel.Annotations": "4.1.0-rc2-*",
    "System.ComponentModel.Primitives": "4.0.1-rc2-*",
    "System.ComponentModel.TypeConverter": "4.0.1-rc2-*",
    "System.Data.Common": "4.0.1-rc2-*",
    "System.Data.SqlClient": "4.1.0-rc2-*",
    "System.Diagnostics.Process": "4.1.0-rc2-*",
    "System.Diagnostics.TextWriterTraceListener": "4.0.0-rc2-*",
    "System.IO.Compression": "4.1.0-rc2-*",
    "System.IO.FileSystem.Primitives": "4.0.1-rc2-*",
    "System.Linq.Expressions": "4.0.11-rc2-*",
    "System.Net.NameResolution": "4.0.0-rc2-*",
    "System.Net.Security": "4.0.0-rc2-*",
    "System.Net.Sockets": "4.1.0-rc2-*",
    "System.Reflection": "4.1.0-rc2-*",
    "System.Reflection.TypeExtensions": "4.1.0-rc2-*",
    "System.Security.Principal.Windows": "4.0.0-rc2-*",
    "System.Text.Encoding.CodePages": "4.0.1-rc2-*",
    "System.Threading.Timer": "4.0.1-rc2-*"
  },

  "frameworks": {
    "netstandard1.5": { 
        "imports": "DNXCORE50" 
    }
  }
}

**Comment by piotrpMSFT** [comment]
I just tried to repro this with preview2 and it restored successfuly. I also migrated to csproj and restored with preview3 and that also worked. This was probably an issue with packages not having been on NuGet yet.
