### ISSUE TITLE
Document and trim dependencies for --native

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#302]
Using compile --native adds additional dependencies [linker, potentially cpp compiler] that need to be explained, validated, and ideally removed.

**Comment by brthor** [comment]
On Linux/Mac our additional Dependency is `clang-3.5`

On Windows there is a dependency on a Full VS2015 Install with c++ tools.

/cc @schellap Am I missing anything?

**Comment by blackdwarf** [comment]
@piotrpMSFT @brthor should we move this to CoreRT repo now?

**Comment by blackdwarf** [comment]
Since the CoreRT bits are not in the box with the CLI now, this is obsolete. Closing.
