### ISSUE TITLE
Project.json schema warnings aren't working

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#3021]
I'm pretty sure this broke at #2980, looking at CI history.

## Steps to reproduce
dotnet new
edit project.json, change "buildOptions" to "compilationOptions"
dotnet restore
dotnet build

## Expected  behavior
warning DOTNET1015: The 'compilationOptions' option is deprecated. Use 'buildOptions' instead.

## Actual behavior
No warning is printed

## Environment data
`dotnet --info` output:

**Comment by eerhardt** [comment]
Yes, that change broke this behavior.  Working on a fix (and a test) now.
