### ISSUE TITLE
Rename 'master' branch to be 'feature/native-compile'

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3023]
Or some similar name.

The 'master' branch is no longer the 'master' branch. Instead it is really a feature branch that contains the native compile feature.  As of now `rel/1.0.0` is really our "master"/"develop" branch that is the main  branch people should be contributing to.

We should also consider turning off Jenkins and VSO CI runs for the 'master' branch.

**Comment by piotrpMSFT** [comment]
@nattress and I chatted yesterday. I think we're just going to move the `dotnet-compile-native` work to the CoreRT repo altogether.

@nattress are you ok with us deleting `master`?

**Comment by nattress** [comment]
Yes you can go ahead and delete it and we'll sort things out in CoreRT.

**Comment by eerhardt** [comment]
> Yes you can go ahead and delete it and we'll sort things out in CoreRT.

You sure we shouldn't just rename it for a while, in case you want to look at the commits?

**Comment by nattress** [comment]
Aren't the interesting commits in RC2 branch from the last several months?  A renamed master is fine with me, too just incase.

**Comment by piotrpMSFT** [comment]
I crated branch `feature/compile-native` and deleted `master.

**Comment by eerhardt** [comment]
Should I delete the VSO build definitions for master?
