### ISSUE TITLE
Running `dotnet-install.ps1` more than once returns non-zero exit code

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3024]
## Steps to reproduce
Place a ps1 file with the content below in your repo root.

```
Write-Host "Installing .NET Core CLI Stage 0 from branchinfo channel"
& "scripts\obtain\dotnet-install.ps1" -Channel "preview" -Architecture x64 -Verbose
if($LASTEXITCODE -ne 0) { throw "Failed" }

Write-Host "Installing .NET Core CLI Stage 0 from branchinfo channel"
& "scripts\obtain\dotnet-install.ps1" -Channel "preview" -Architecture x64 -Verbose
if($LASTEXITCODE -ne 0) { throw "Failed" }
```

## Expected  behavior
First invocation installs cli, second exits successfully saying there's already an installation.

## Actual behavior
second invocation exits with failure saying there's already an installation.

## Environment data
`dotnet --info` output:
N/A

cc @krwq @blackdwarf

**Comment by blackdwarf** [comment]
@brthor the script should not exit with an error code. The second behavior is perfectly valid and is not an error, more of a warning/info.
