### ISSUE TITLE
[ProjectModel.Server] when package version changed in project.json very quickly, PMS sends Dependencies with old package version, which breaks restore

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#3026]
## Steps to reproduce
1. Set PMS trace env var PROJECTMODELSERVER_TRACE=1
2. Create a console app
3. add Newtonsoft.Json 7.0.1 to roject.json, wait for restore
4. Go to Project Model Server output pane and clean it
5. Open Nuget Package Manager dialog
6. Go to updates tab and update Newtonsoft.Json to 8.0.3
## Expected  behavior

Restore to be triggered
## Actual behavior

No restore

What happens is 
- Nuget Package manager  dialog deletes old Newtonsoft.Json dependency from project.json and then adds new one with version 8.0.3. File is upadted very quickly. 
- PMS receives a FileChanged event from tooling
- but Dependencies snapshot returning back to tooling does not contain new Newtonsoft.Json version 8.0.3 but old one 7.0.1 with diagnostic :
  
  "Newtonsoft.Json": {
      "Name": "Newtonsoft.Json",
      "DisplayName": "Newtonsoft.Json",
      "Version": "7.0.1",
      "Path": "C:\Users\antonpis\.nuget\packages\Newtonsoft.Json\7.0.1",
      "Type": "Package",
      "Resolved": true,
      "Dependencies": [],
      "Errors": [],
      "Warnings": [
        {
          "ErrorCode": "NU1007",
          "SourceFilePath": "C:\Users\antonpis\Documents\Visual Studio 2015\Projects\1\GlobalJsonSources\ConsoleApp7\src\ConsoleApp7\project.json",
          "Message": "Dependency specified was Newtonsoft.Json >= 8.0.3 but ended up with Newtonsoft.Json 7.0.1.",
          "Severity": 1,
          "StartLine": 12,
          "StartColumn": 31,
          "EndLine": 12,
          "EndColumn": 31,
          "FormattedMessage": "C:\Users\antonpis\Documents\Visual Studio 2015\Projects\1\GlobalJsonSources\ConsoleApp7\src\ConsoleApp7\project.json(12,31): warning NU1007: Dependency specified was Newtonsoft.Json >= 8.0.3 but ended up with Newtonsoft.Json 7.0.1.",
          "Source": {
            "Name": "Newtonsoft.Json",
            "Version": "7.0.1"
          }
## Environment data

`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x86

**Comment by piotrpMSFT** [comment]
project-model-server is deprecated with the preview3 release. MSBuild can be queried directly for relevant state.
