### ISSUE TITLE
Remove build dependency on VSO NuGet Publisher 

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3031]
Currently our builds have a dependency on the VSO NuGet publisher in order to push our packages to myget. 

This dependency is only available on Windows and forces us to workaround with separate build definitions only for handling publishing of our nuget packages. 

NuGet.Xplat has the push command available and we should consider switching to that to remove this dependency and the need to work around it.

cc @Sridhar-MS @piotrpMSFT @eerhardt @sokket

**Comment by eerhardt** [comment]
I don't think we can do this for our managed assemblies.  The .nupkgs we package and publish need to be signed, and signing only happens on Windows builds.
