### ISSUE TITLE
DependencyModel uses wrong package cahce environment variable name

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#3034]
In PR https://github.com/dotnet/cli/pull/2156 `DOTNET_PACKAGES_CACHE` variable name was changes to `DOTNET_HOSTING_OPTIMIZATION_CACHE`
https://github.com/dotnet/cli/pull/2156/files#diff-76ff25fcb7bb5726c0738b88686cf16dR111

But DependencyModel usage (https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.Extensions.DependencyModel/Resolution/PackageCacheCompilationAssemblyResolver.cs#L71) was not updated, so MVC Razor compiler won't use package cache for view compilation when only `DOTNET_HOSTING_OPTIMIZATION_CACHE` is set.

@schellap @muratg

**Comment by piotrpMSFT** [comment]
Moved to core-setup
