### ISSUE TITLE
May add a selfupdate option ?

### ISSUE THREAD

**Issue by jeff-wu** [dotnet/cli#3036]
May add a `selfupdate` option ? run `dotnet selfupdate` command will upgrade to the latest version for dotnet SDK and CLI.

**Comment by Varorbc** [comment]
I think so too

**Comment by GuardRex** [comment]
@lywujie Duplicate: https://github.com/dotnet/cli/issues/511

TL;DR: This suggestion was rejected by the team.

**Comment by blackdwarf** [comment]
And with @GuardRex comment I'm closing this. I think I'm going to start working on actually having an user voice site up for suggestions like these so we keep the issues list for bugs and such.
