### ISSUE TITLE
License.txt needed for tar.gz and zip archives

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#3037]
We need to ensure proper licensing is include with all archive packages. License is the same EULA as displayed by native installers. File should be LICENSE.TXT and placed in the root of the archive.

**Comment by brthor** [comment]
@leecow Can I assume this is the proper EULA?

https://github.com/dotnet/cli/blob/rel/1.0.0/packaging/osx/clisdk/resources/en.lproj/eula.rtf

Should this be converted to plain text or left as rich text? 

Thanks

**Comment by leecow** [comment]
@brthor - yep, that looks correct and need to be plain text (utf8).

**Comment by piotrpMSFT** [comment]
@mellinoe please prioritize this.

**Comment by joshfree** [comment]
We'll need a dummy check-in to CLI to trigger a build and consume the (in progress) core-setup build once it's finished.

**Comment by brthor** [comment]
@joshfree maybe https://github.com/dotnet/cli/pull/3538 ? It's just a readme

**Comment by joshfree** [comment]
@brthor thanks.  @mellinoe needs to verify and close next.

**Comment by mellinoe** [comment]
This is complete. Changes were made in https://github.com/dotnet/core-setup/pull/173
