### ISSUE TITLE
dotnet.exe should have proper file information embedded in it

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#3041]
## Steps to reproduce

Run dotnet and look at the view in task manager on Windows.
## Expected  behavior

All the information about the process and its brand should be there. It should show up as something like ".NET Application Host" with all the details about versions, product names, etc should be complete.
## Actual behavior

 It just shows up as dotnet and all the detailed file info is blank.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Moved to core-setup
