### ISSUE TITLE
Need visibility into the Nuget feeds being used

### ISSUE THREAD

**Issue by vancem** [dotnet/cli#3049]
I was trying to dogfood the RC2 release

https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0-preview1-002700/dotnet-dev-win-x64.1.0.0-preview1-002700.exe

And when I tried 

dotnet new
dotnet restore
dotnet run

It was failing.  I ultimately tracked it back to the fact that my Nuget.config did not have the feed for the https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.    I believe most people could not have figured that out however.  

In general anytime the dotnet.exe takes a dependency on configuration information it should log that (at least when you use --verbose option, but for really important cases, maybe all the time).   One huge dependency that donet has is on Nuget and in particular Nuget.config.   

We need logging that 
    1) Allows people to find their Nuget.config (it is after all buried in AppData\Roaming\Nuget.config
    2) Tells them the feeds that you are using when it can't find packages (since a likely issue is that you don't have the correct feed).

My recommendation is that you do fairly verbose logging when --verbose is given, and at least some terse logging unless users explicitly suppress it (e.g. you can have a --quite option).

**Comment by dasMulli** [comment]
Isn't `dotnet restore` logging feeds and configs already? at least on os x it prints those:

```
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: /Users/martin/Documents/build-repository/src/build-repository/src/BuildRepository/project.lock.json
log  : /Users/martin/Documents/build-repository/src/build-repository/src/BuildRepository/project.json
log  : Restore completed in 16675ms.

NuGet Config files used:
    /Users/martin/Documents/build-repository/src/build-repository/NuGet.Config
    /Users/martin/.nuget/NuGet/NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json
    https://api.nuget.org/v3/index.json

Installed:
    1 package(s) to /Users/martin/Documents/build-repository/src/build-repository/src/BuildRepository/project.json
```

**Comment by vancem** [comment]
I have opened this issue in error.  My main problem was that dotnet restore is now required before a dotnet run will succeed (and it gives a cryptic error in that case).   I have opened a separate issue for that and will close this issue.

**Comment by eerhardt** [comment]
I logged https://github.com/dotnet/cli/issues/1334 a while ago to try to address this issue.  IMO - the developer shouldn't be forced to call 'restore'.  Instead the tooling should recognize when a restore is needed and restore as appropriate.  (Just like how you don't need to execute `dotnet build` before you call `dotnet run`. If the project needs to be built, the tooling does it for you).
