### ISSUE TITLE
Command line parsing should have an option to "collect all args from now on"

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#305]
Since we use forwarding command line args in many places we should have an ability to forward them.

Currently we choose to use System.CommandLine which has issues with this. I.e:
```
dotnet --help anything
```
should print help for dotnet and ignore "anything" while this:
```
dotnet anything --help
```
should run "anything" and pass --help to it

currently both options are equivalent. The cause of this is that you can't simply express:
"When you encounter first argument which is not part of any named argument stop processing and give me anything else after".

**Comment by blackdwarf** [comment]
This is a System.CommandLine issue, so it should be filed on dotnet/corefxlab. Closing this.
