### ISSUE TITLE
Extensibility only looks in the Path, not the local directory

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/cli#3050]
## Steps to reproduce

Create a console app named 'dotnet-foo'. 
Publish the app.
Open the publish directory in a console window
type "dotnet foo" (no quotes)
## Expected  behavior

Runs dotnet-foo.exe with dotnet as extensibility function
## Actual behavior

"Can't find executable called dotnet-foo"
## Environment data

`dotnet --info` output:
D:\working\firstcmd\bin\Release\netcoreapp1.0\win81-x64\publish>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by shawnwildermuth** [comment]
Note, adding the directory to the path and it works.

**Comment by blackdwarf** [comment]
@shawnwildermuth currently, as designed, we do not search in the local directory. What would be the scenario for this?

**Comment by piotrpMSFT** [comment]
We haven't seen a scenario for this yet. If we're in the directory we can invoke the executable directly. I'd be glad to hear about what this enables, though!

**Comment by shawnwildermuth** [comment]
The use-case is for tools that are project specific. Any reason why I'd need to globally install a tool that is just for the current project. For example, imagine a data migration tool that is run by the developers and deployers, but is only used by the project not externally.

**Comment by piotrpMSFT** [comment]
@shawnwildermuth why does `dotnet path/to/dotnet-tool.dll` not suffice?

**Comment by shawnwildermuth** [comment]
It should, as long as I can do ./dotnet-tool.dll just feel unmagical. But perhaps not enough to change it.
