### ISSUE TITLE
Better Dianostic if you don't do a dotnet restore before a dotnet build

### ISSUE THREAD

**Issue by vancem** [dotnet/cli#3051]
When I was dogfooding the RC2 bits  https://go.microsoft.com/fwlink/?LinkId=798481 

I issued the following command 

mkdir app
cd app
dotnet new 
dotnet run

Produces the following diagnostic.  

Project hello does not have a lock file.
Project hello does not have a lock file.

I realize this is now an error, as you are now required to do the dotnet restore, however the current diagnostic does nothing to lead the user in the correct direction.   At the least it should suggest that 
a dotnet restore will solve the problem. 

This is particularly bad because dotnet restore did not need to be done in RC1, so it is likely that it will be a common mistake.

**Comment by colemickens** [comment]
It's also confusing if you have a lock file already but haven't restored packages yet (or cleared your cache, etc). I don't have the exact error, but it's not super user friendly.

**Comment by blackdwarf** [comment]
This is now fixed in #3150 . @vancem can you verify and close if it behaves correctly? This is on the latest.
