### ISSUE TITLE
Disable Partial NGEN

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#3053]
#2517 enables crossgen for SDK binaries.  However, it does not actually disable partial NGEN.  This is my fault, as I provided the wrong COMPLUS variable.  Instead, the variable specified - COMPLUS_ZapDisable - disables NGEN usage during crossgen, but not at runtime.

@JohnChen0, can you please provide instructions on how to disable partial NGEN at crossgen time so that it can be done during the CLI build?

cc: @piotrpMSFT, @Sridhar-MS, @gkhanna79

**Comment by JohnChen0** [comment]
To disable partial NGen, please set the following environment variable: `COMPlus_PartialNGen=0`

**Comment by brianrob** [comment]
@Sridhar-MS, is this something that you can fix-up for preview2?

**Comment by Sridhar-MS** [comment]
Why does the title mention `Roslyn` only? Note we crossgen all the binaries in the SDK with the same parameters.

**Comment by brianrob** [comment]
Yes, you're right.  Roslyn is the only one that uses partial NGEN today.  I've updated the title to reflect that the change will affect all binaries that get crossgen'd.

**Comment by Sridhar-MS** [comment]
The fix is pretty simple. Add the environment variable here - https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L91.

**Comment by brianrob** [comment]
Yes, it should be that simple.  Is this something that you can take care of?  Thanks.

**Comment by Sridhar-MS** [comment]
Fixed by #3116

**Comment by brianrob** [comment]
Thanks much @Sridhar-MS!
