### ISSUE TITLE
Add openSUSE 13.2 CLI build / packages for Preview2

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#3054]
related https://github.com/dotnet/corefx/issues/8584
/cc @ellismg @livarcocc

**Comment by thild** [comment]
Please, add package authoring for openSUSE Tumbleweed to.

**Comment by thild** [comment]
Please, add openSUSE Tumbleweed support also.

**Comment by piotrpMSFT** [comment]
Fixed by #3054

**Comment by eerhardt** [comment]
@piotrpMSFT - I think you meant a different #, you just linked the issue with itself.

Did you mean #3278?

I think this issue can be closed now.  Any objections?
