### ISSUE TITLE
Get InitializeComponent and System.Runtime.InteropServices.PInvoke errors when referencing .NET Core RC2 Class DLL with WPF app

### ISSUE THREAD

**Issue by shaggygi** [dotnet/cli#3057]
## Steps to reproduce

Using .NET Core RC2 and VS Tools Preview1, create a new C# Class project and compile.  Then create a new WPF application in the same solution.  Reference the Class project DLL by right-clicking Add References... > navigate to DLL > check DLL > click OK.  Now rebuild WPF application.  I tried with .NET 4.5.2 and 4.6.1 with same results.
## Expected  behavior

Should be able to build with no errors.
## Actual behavior

1>------ Rebuild All started: Project: WpfDemo, Configuration: Debug Any CPU ------
1>C:\windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MC1000: Unknown build error, 'Cannot resolve dependency to assembly 'System.Runtime.InteropServices.PInvoke, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.' 
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

Any one seen this with RC2 and know of the fix?  Thx

**Comment by piotrpMSFT** [comment]
Moved to ASPNET/Tooling repo which tracks VS2015 tooling for .net core
