### ISSUE TITLE
Re-enable crossgen for windows

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#3059]
When moving the CLI corefx dependency from RC2 to RC3 there was an issue in crossgen for windows. The CLI builds failed with an InvalidCastException in the Newtonsoft.Json library. 

CoreCLR issue - https://github.com/dotnet/coreclr/issues/5064

**Comment by pranavkm** [comment]
cc @javiercn \ @victorhurdugaci - this probably affects us too.

**Comment by piotrpMSFT** [comment]
Blocked by #3260

**Comment by piotrpMSFT** [comment]
This fix needs to go in to both CLI and dotnet/core-setup repos.

**Comment by eerhardt** [comment]
Now unblocked by #3260.

**Comment by eerhardt** [comment]
This has been fixed.  Crossgen is enabled in both the Shared Framework and CLI for all platforms.
