### ISSUE TITLE
Console.Write behaviour differs when running dotnet run

### ISSUE THREAD

**Issue by glennc** [dotnet/cli#306]
This is probably something to do with the way we are redirecting things when doing run.

```c#
class Program
{
    static void Main(string[] args)
    {
        Console.Write("prompt>");
        var input = Console.ReadLine();
        Console.WriteLine("echo " + input);
        Console.ReadLine();
    }
}
```

Running the exe generated `dotnet compile`:
 ```
prompt>hello
echo hello
```
Using `dotnet run` I get this:
```
hello
prompt>echo hello
```
I haven't dug very far into what `dotnet run` is doing that breaks this. Maybe something to do with stdin.

**Comment by piotrpMSFT** [comment]
@glennc sounds like you're going to take a look so assigning.

**Comment by livarcocc** [comment]
Hey Glenn, I tried this on windows and on OSX (zsh) and it worked normally for me. I will close. Please re-open if you see it again, in which case, please tell us where it happens.
