### ISSUE TITLE
Installation failure on Windows 8.1

### ISSUE THREAD

**Issue by harumph** [dotnet/cli#3067]
## Steps to reproduce
I installed the .Net Core SDK from the official page: https://www.microsoft.com/net/core#windows
The installer failed at first try but succeeded on second.

```
dotnet new
dotnet restore
dotnet run
```

## Expected  behavior

Compile and execute the example project

## Actual behavior

```
C:\dev\hwapp\error CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'

Compilation failed.
    0 Warning(s)
    1 Error(s)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

## My investigation so far

I tried reparing C++ 2015 Redistributable package, it failed.
[Gist with the installer log](https://gist.github.com/harumph/67d6b3274455eeb162b14291dc530ff9)

`[AF24:5DC8][2016-05-17T09:28:23]i301: Applying execute package: Windows81_x64, action: Install, path: C:\ProgramData\Package Cache\3ACBF3890FC9C8A6F3D2155ECF106028E5F55164\packages\Patch\x64\Windows8.1-KB2999226-x64.msu, arguments: '"C:\windows\SysNative\wusa.exe" "C:\ProgramData\Package Cache\3ACBF3890FC9C8A6F3D2155ECF106028E5F55164\packages\Patch\x64\Windows8.1-KB2999226-x64.msu" /quiet /norestart'`

I tried running the update package myself, it fails with the following message:

`The update is not applicable to your computer`

I'm on an Enterprise version of Windows, updates are handled by domain admins. I'm guessing that's where the issue is.

**Comment by blackdwarf** [comment]
@Sridhar-MS want to take a look at this?

**Comment by piotrpMSFT** [comment]
#3226 is related

**Comment by tmat** [comment]
Likely due to the fact that the reported dll is actually missing from the Shared FX: https://github.com/dotnet/core-setup/issues/72

**Comment by tmat** [comment]
It's fixed in the latest dotnet cli build by https://github.com/dotnet/cli/pull/3140.
