### ISSUE TITLE
Run ICE validation for the MSI package

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#307]
https://msdn.microsoft.com/en-us/library/aa372423(v=vs.85).aspx

**Comment by Petermarcu** [comment]
@robmen , how is WiX on covering ICE errors these days? Should we even bother with ICE?

**Comment by robmen** [comment]
Sadly the project to replace ICEs is stalled so running the heavy ICE validation process is the only option at the moment. light.exe will run them for you automatically, if you do no suppress it.
