### ISSUE TITLE
can not update core preview 1 to RC2

### ISSUE THREAD

**Issue by melsayed** [dotnet/cli#3071]
## Steps to reproduce
I installed .NET Core (RC2) from https://www.microsoft.com/net/download 
but when open CMD and check version of Core it still get preview1 

need to know what is the problem?

**Comment by KrzysFR** [comment]
I had a similar issue, but on OSX. I installed some nightly version released during NDC London earlier this year that may not be recognized by the uninstall script, as well as the 1.0.0 version of dotnet cli.

I found the offending locations by looking at my PATH env variable, and testing each one, and removing all the old ones

I had to do the following to make it work on OSX (YMMV):
- run the uninstall script `dotnet-uninstall-pkgs.sh'
- remove all the `dotnet` and `dotnet-*` links in `/usr/local/bin` that were pointing to `/usr/local/share/dotnet/bin/dotnet-XXX` _(note: the new package installs stuff in `/usr/local/share/dotnet/` one folder up)_
- edit my `.bash_profile` to remove the line that mentions dnvm
- remove the `/usr/local/share/dotnet` folder completely
- reinstall with the .pkg
- close all terminal windows
- relaunch a terminal, and type `dotnet`, it should print only `Usage: dotnet [--help | app.dll]`

Was then able to `dotnet new`, `dotnet restore` and `dotnet run` the hello world app (though it took 10+ minutes to restore all the 110+ nuget packages via the lousy hotel internet connection :( )

If you are on Windows, maybe a similar approach is possible. Look at your installed programs and remove ASP .NET 5 stuff or ASP.NET core RC1 manually?

**Comment by blackdwarf** [comment]
@melsayed you need to uninstall **all** of the Pre-RC2 versions of the CLI. However, you can still have DNX installed and it shouldn't matter. I'm not sure what are you seeing as a problem?

**Comment by GuardRex** [comment]
@melsayed Here's some help on finding and getting rid of the old bits: https://github.com/dotnet/cli/issues/2948

... and don't forget to run a `nuget locals all -clear` to nuke your package caches.

**Comment by piotrpMSFT** [comment]
Also please note that, though rc2 > preview1, the preview1 CLI is in fact newer. The repo got ahead of the product in version suffixes, I'm afraid.

If `dontet --version` is preview1 then you have the latest!
