### ISSUE TITLE
How to run SSL on RC2 from console? 

### ISSUE THREAD

**Issue by dlebedynskyi** [dotnet/cli#3072]
## Intro
We need to run app on https for development since it integrates with other services that are https/wss only. 
in RC1 in project.json we had
```
"commands": {
"express": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.WebListener"
}
```
that allowed us to run command in console `dnx express -- server.urls https:\\localhost:43431\`. 

## Steps to reproduce
Current dotnet has run  and with new Visual Studio project on RC2 you can get launchSettings.json that allows you to specify sslPort for IISExpress. So there is  way to run standart app on iis express with ssl. 
But there is no way (at least documented) to do it from console. We would like to stay away from VS as far as possible. 

Documentation is saying that 
`dnx command`	 is N/A in `CLI command` and it is by design. 

So what is design to do same:
1. how do launch WebListener with SSL form console now? 
2. Is there a way to run it on mac/linux with ssl suppot ?

**Comment by blackdwarf** [comment]
@anurse @DamianEdwards care to weigh in? Maybe this issue is supposed to be on the ASP.NET Core repo(s)?

**Comment by davidfowl** [comment]
@dlebedynskyi file this bug on aspnet/home

**Comment by dlebedynskyi** [comment]
@davidfowl not sure that is right point. Visual Studio canrun IIS Express with SSL or  Kestrel  on custom ports. For that it is using launchSettings.json. There is no way (or no documented way) to do same with cli command  `dotnet run`. Basically all we need is to have to start app the same way vs does with ssl and custom ports
