### ISSUE TITLE
Add a flag to dotnet build to only show errors

### ISSUE THREAD

**Issue by jchannon** [dotnet/cli#3076]
## Steps to reproduce

Run `dotnet build` this will give warnings and errors.  

When migrating code you only want to see errors to start with.  You can then solve the warnings once it compiles and turn on "Warning as errors"
## Expected  behavior

Output only showing errors
## Actual behavior

Shows errors and warnings
## Environment data

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

```

**Comment by blackdwarf** [comment]
This issue is actually solved by MSBuild. It contains the `clp` switch which can accept various logging parameters, one of which is `ErrorsOnly` which will show only errors.

**Comment by blackdwarf** [comment]
With the above, I will close this issue as "mitigated by the move to MSBuild". If needed, please reopen.
