### ISSUE TITLE
dotnet test documentation steps error

### ISSUE THREAD

**Issue by james-uffindell-hpe** [dotnet/cli#3077]
## Steps to reproduce
The dotnet-test documentation here: http://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-test.html has a sample project.json that looks as follows:
{
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.0.0-*",
        "xunit": "2.1.0-*",
        "dotnet-test-xunit": "1.0.0-*"
    },
    "testRunner": "xunit",

    "frameworks": {
        "netstandard1.5": {
        }
    }
}

Using this as a project json does not work on my system.

To reproduce, create a new dotnet project with this as the project.json and try to restore/build/test.

## Expected  behavior
"dotnet restore", "dotnet build", and "dotnet test" should not error

## Actual behavior
"dotnet restore" fails with the following error:
error: Package dotnet-test-xunit 1.0.0-rc2-build10015 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package dotnet-test-xunit 1.0.0-rc2-build10015 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
error: Package xunit.assert 2.1.0 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package xunit.assert 2.1.0 supports:
error:   - dotnet (.NETPlatform,Version=v5.0)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error: One or more packages are incompatible with .NETStandard,Version=v1.5.

"dotnet build" and "dotnet test" both fail because "dotnet restore" cannot successfully run.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by brunobelarmino** [comment]
:+1:

**Comment by blackdwarf** [comment]
@james-uffindell-hpe yeah, that needs to change. Will update the sample which went out of sync with the implementation.

**Comment by blackdwarf** [comment]
This is fixed via dotnet/core-docs#449. The changes will be online tomorrow in the docs. Closing this, please reopen if the docs are still not correct.

**Comment by james-uffindell-hpe** [comment]
There seems to be a missing comma in the json example there now (after the Microsoft.NETCore.App object), but other than that the updated json works fine for me with dotnet restore/test.
