### ISSUE TITLE
Order the warnings and errors

### ISSUE THREAD

**Issue by jchannon** [dotnet/cli#3078]
## Steps to reproduce

Run `dotnet build`

This gives warnings and errors as it compiles each file.
## Expected  behavior

Errors and Warnings to be reported separately
## Actual behavior

Errors and Warnings mixed together
## Environment data

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
In the new MSBuild world, we get the errors and warnings form MSBuild. AFAIK, MSBuild by default first outputs warnings and then errors as a summary (depending on the verbosity level as well as what parameters are passed to the default console logger). I think this fixes the issue. Will close this one. If you think this was in error, please reopen.
