### ISSUE TITLE
CLI help documentation should list `help` as a command

### ISSUE THREAD

**Issue by tstringer** [dotnet/cli#3079]
## Steps to reproduce

1. `dotnet --help`
2. Notice no `help` entry under `Common Commands`

## Expected  behavior

When running `dotnet --help` it should explicitly state that `help` is a command.  I.e. something like this:

```
Common Commands:
  help           Display command information and parameters for a command
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
```

Without knowing (or digging through online information, which isn't desired with a CLI) that you can run `dotnet help <command>`.  Whereas it is also possible to run `dotnet <command> -h|--help` there is also no clear indication of this in the CLI root help.

## Actual behavior

The current behavior shows no mention of `help` as a possible command:

```
Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@brthor can we add a `Common Options` with a single entry that is `--help`?

**Comment by blackdwarf** [comment]
@tstringer I'm not sure what the ask is here. `--help` is a common switch for the in-box commands. It is not a command on its own.

**Comment by tstringer** [comment]
@blackdwarf my issue here is that there is no obvious way to get specific help for each command.  For instance, the general flow of "command discovery" would is as follows:

```
$ dotnet
Usage: dotnet [--help | app.dll]

$ dotnet --help
.NET Command Line Tools (1.0.0-preview1-002702)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Number
  --info        Display .NET CLI Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
```

Now say I want to find out the params for `dotnet new`.  If you run `dotnet new` then of course you wouldn't get a param menu, you would create a new .NET Core project.  So without assuming that you can run `dotnet new --help` or `dotnet help new` then there's no way to discover this "help".

Let me know if that explanation makes more sense!

**Comment by blackdwarf** [comment]
@tstringer makes some more sense. Essentially, you would like a line in that help screen that says something like "You can use `--help` with any of the commands below"?

**Comment by brthor** [comment]
I'm thinking help is somewhat of a special case here since it's the only common option that we have between commands, and is critical for discovering how to use the commands themselves, so why not give it it's own section.

This is what I have in mind

```
.NET Command Line Tools (1.0.0-preview1-002702)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Number
  --info        Display .NET CLI Info

Common Commands Help:
  dotnet [command] --help

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
```

Thoughts? @blackdwarf

**Comment by blackdwarf** [comment]
@brthor like it, with a nit: `--help` is not really a command but an option. This is crucial so we don't confuse the concept of a command (verb). Otherwise, this would be good.

**Comment by brthor** [comment]
I agree, I didn't mean to imply `--help` was a command:

> Common Commands Help:

Do you think this implies that? What do you suggest instead?

**Comment by blackdwarf** [comment]
@brthor I would suggest "Common options (applicable to all commands):". This way we leave space for adding something more tomorrow (for instance, `set` or `destroy` or my favorite `--desolate` :))

**Comment by brthor** [comment]
We already have a common options section which has a different purpose, it'd be confusing to have two such sections. 

Perhaps we could have this:
```
Dotnet Options: dotnet [dotnet-option] [command] 
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Number
  --info        Display .NET CLI Info

Common Commands Options: dotnet [command] [command-option]
  --help    See usage details of a specific command

```

**Comment by blackdwarf** [comment]
Wait, if we have common options, why not just stick it in there? :)

**Comment by brthor** [comment]
because help isn't passed before the command

> Common Options (passed before the command):

**Comment by tstringer** [comment]
Not to mention, you can use help as a command: i.e. `dotnet help run`

And to answer your original question, @blackdwarf, yes that would be sufficient.  Although I'd rather see it in a command/param fashion instead of a sentence, I think that's better than the current availability for help discovery.

**Comment by blackdwarf** [comment]
Ah, you can use it as a command because it is implemented as a `HelpCommand`. Interesting...

@brthor well, let's follow the pattern we have and do `Common Options passed after the command`.

**Comment by brthor** [comment]
@blackdwarf 
This is terrible and confusing. It's so easy to miss the only difference which is the word **after**

```
Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Number
  --info        Display .NET CLI Info

Common Options (passed after the command):
  --help    See usage details of a specific command
```

**Comment by blackdwarf** [comment]
@brthor wait...ok, I need to think about this. The common options is not a good thing, because these options are not "common". They are the muxer's/host options.

**Comment by brthor** [comment]
Yeah I agree that was my line of thought with `Dotnet Options` but admittedly that's not too great either.

**Comment by blackdwarf** [comment]
OK, maybe something like this?

```console
.NET Command Line Tools (1.0.0-preview1-002700)
Usage: dotnet [host-options] [command] [arguments] [common-options]

Arguments:
  [command]                   The command to execute
  [arguments]                  Arguments to pass to the command
  [host-options]              Options specific to dotnet (host)
  [common-options]      Options common to all commands

Common options:
  -v|--verbose  Enable verbose output
  -h|--help        Show help 

Host options (passed before the command):
  -v|--verbose  Enable verbose output
  --version         Display .NET CLI Version Number
  --info               Display .NET CLI Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
```

**Comment by brthor** [comment]
LGTM

**Comment by blackdwarf** [comment]
Do you have a PR open for this change @brthor ?

**Comment by brthor** [comment]
https://github.com/dotnet/cli/pull/3353
