### ISSUE TITLE
Ubuntu 15.10 can't install dotnet

### ISSUE THREAD

**Issue by jgowdy** [dotnet/cli#308]
root@ubuntu:~# apt-get install dotnet
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet : Depends: libicu52 (>= 52~m1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jgowdy** [comment]
Installation on 15.04 works fine.

**Comment by piotrpMSFT** [comment]
@brthor, FYI. We are not ready for Ubuntu 15 yet, but be aware this is coming. Easy fix?

**Comment by brthor** [comment]
Thanks for the heads up @piotrpMSFT and thanks for pointing this out @jgowdy 

Have not done any testing for this yet but I have a few ideas on the cause.

**Comment by adrian17** [comment]
For the record (I don't know what's the priority on Debian support compared to Ubuntu), there is a similar issue on Debian: Debian 8 (Jessie) can't install because it lacks liblldb-3.6, and on the testing release (Stretch) there is the same libicu52 issue as on Ubuntu 15.10.

**Comment by anurse** [comment]
Ubuntu 15.10 is not supported by the CoreCLR. Sounds like there are no plans to support it at this time: https://github.com/dotnet/corefx/issues/4324#issuecomment-159373852

**Comment by anurse** [comment]
There are some hacks you can do to get it working though: https://github.com/aspnet/dnx/issues/3059#issuecomment-150670962

**Comment by jgowdy** [comment]
Okay, it looks like as of now there's language on the getting started page that specifies Ubuntu 14.04.  I don't recall seeing that before.  :)

**Comment by vaelen** [comment]
Is there a guide to easily building from source?

**Comment by coshkun** [comment]
There may be a WORKAROUND with:

> 
> Install libicu55 instead:
> 
> sudo apt-get install -y libicu55
> 
> You can also search for this package:
> 
> sudo apt-get update
> apt-cache search libicu
> 
> If the latter command gives you some results (eg. libicu with version number other than 52) you can check if installing it suits your needs.
[Source is here..](http://askubuntu.com/questions/722075/no-installation-candidate-for-libicu52-on-15-10)

**Comment by tmds** [comment]
@coshkun after installing libicu52 things still won't work as you'll hit this issue: https://github.com/dotnet/cli/issues/1179
@vaelen documentation request: https://github.com/dotnet/corefx/issues/6770

**Comment by szogun1987** [comment]
I have fixed it by adding entry in etc/apt/sources.list
I have followed this article http://packages.ubuntu.com/trusty/amd64/libicu52/download
