### ISSUE TITLE
Performance tests fail unexpectedly on CI

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3081]
Microsoft.DotNet.Tools.Builder.Tests.BuildPerformanceTest.IncrementalRebuildWithRootChangedInGraph_TwoTargetGraph failed in my CI run.

http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/release_ubuntu_x64_prtest/1926/

```
MESSAGE:
Expected command to pass but it did not. File Name: /opt/code/artifacts/ubuntu.14.04-x64/stage2/dotnet Arguments: --verbose build "/opt/code/test/Performance/bin/Release/netcoreapp1.0/IncrementalRebuildWithRootChangedInGraph_TwoTargetGraph/PerformanceTestProjects/TwoTargetGraph/TwoTargetP0" Exit Code: 134 StdOut: StdErr:
+++++++++++++++++++
STACK TRACE:
at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message) at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) at Microsoft.DotNet.Tools.Test.Utilities.CommandResultAssertions.Pass() at Microsoft.DotNet.Tools.Builder.Tests.BuildPerformanceTest.IncrementalRebuildWithRootChangedInGraph(TestInstance[] instances)
```

**Comment by piotrpMSFT** [comment]
@lt72 can you take a look? We need to have these tests be repeatable...

**Comment by lt72** [comment]
@piotrpMSFT: these tests were added by Pavel. Also perf tests are maintained by the feature team, not the RAP team. This does not look like a perf infra/tooling issue. It seems like the dotnet executable path the test uses is wrong: /opt/code/artifacts/ubuntu.14.04-x64/stage2/dotnet

**Comment by livarcocc** [comment]
Did we turn this off?
