### ISSUE TITLE
Running build from rel/1.0.0 will create a sdk without assemblies but optimization data

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#3083]
## Steps to reproduce
1. Install preview1 build by running `dotnet-install.sh`
2. Sync to latest `rel/1.0.0` branch
3. Run `build.sh`

## Expected  behavior
1. dotnet already installed should be intact;
2. or the newly installed dotnet works;

## Actual behavior
1. A new folder is created under `sdk` folder, named `1.0.0-preview2-002769`, under which there is nothing but optimization data
2. Cause the dotnet to fail from terminal because it shadows older sdk.

## Environment data
`dotnet --info` output:

**Comment by brthor** [comment]
cc @piotrpMSFT 

Is there a way to redirect the location of the multicorejit data? If we did that in our build, it should solve this issue.

**Comment by troydai** [comment]
This is still bothering me. Do we have a quick solution?

**Comment by brthor** [comment]
If we were to just append something to this path, that might be a quick fix. I don't see any workaround currently.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/MulticoreJitProfilePathCalculator.cs#L37
