### ISSUE TITLE
"runtimeOptions" are not supported under the "frameworks" or "configurations" project.json sections

### ISSUE THREAD

**Issue by halter73** [dotnet/cli#3085]
## Steps to reproduce

Add a "runtimeOptions" section under a specified framework or configuration in a project.json.

    "configurations": {
      "Release": {
        "runtimeOptions": {
          "configProperties": {
            "System.GC.Server": true
          }
        }
      },
      ...

## Expected  behavior

The runtimeOptions would take affect for the specified configuration or framework much like buildOptions do today.

## Actual behavior

The runtimeOptions have no affect since nothing is added to the runtimeconfig.json.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
This is currently by-design. As the project system matures we should address this scenario.
