### ISSUE TITLE
Is x86 support for Linux planned?

### ISSUE THREAD

**Issue by devhammer** [dotnet/cli#3087]
Wanted to test .NET Core RC2 on Linux Mint 17.3, but the build I'm running is x86, and it looks like the current .NET Core bits are x64 only. 

Is x86 support planned at some point, or is x64 the only option?

**Comment by RussKeldorph** [comment]
I would say it's likely "at some point," but can't provide any details right now.  If you look in https://github.com/dotnet/coreclr, you'll see we are actively porting RyuJIT to x86 on Windows.  That would open the door to Linux/x86, but there's still a bunch of JIT work in addition to the runtime work to make that happen.

**Comment by blackdwarf** [comment]
@devhammer at this point, we don't have any real plans to have an x86 release for Linux. However, as with all things, we will listen to customer feedback and re-evaluate that decision if feedback indicates it is a needed/wanted thing.

**Comment by devhammer** [comment]
OK. Thanks for the feedback. I don't know that I'd prioritize it over other work...more trying to understand the roadmap.

**Comment by piotrpMSFT** [comment]
CLI's platform matrix is largely driven by CoreFx & CoreCLR matrix. I'm closing this issue since there is not action we can take in CLI today. Let's move this conversation into dotnet/coreclr if interest grows.

**Comment by markusschaber** [comment]
Just for reference: CoreCLR tracks this at https://github.com/dotnet/coreclr/issues/9265
