### ISSUE TITLE
Go through the DEB dependencies with a fine-tooth comb

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#3088]
We need to go through all of the dependencies on our DEB packages and fix all of the dependencies to be only the set we really need.

**Comment by brthor** [comment]
Can we create separate issues for each of the packages and use this to track cleaning the dependencies of the deb package?

**Comment by blackdwarf** [comment]
Sure thing. Though, we have just this one for now. :)

**Comment by brthor** [comment]
The only thing on deb which should need to be removed is the `clang-3.5` dependency.

**Comment by blackdwarf** [comment]
@brthor we should also go through the runtime and fx debs and see if those need updating. 

/cc @ellismg for that as well.

**Comment by brthor** [comment]
@blackdwarf The dependencies of the runtime/fx debs are auto detected by matching the exports of the .so files against packages on the build machine. 

Except for libssl1.0.0 and libcurl3 which we have established previously that needed to be there.

**Comment by blackdwarf** [comment]
@brthor ah, ok. Then I was misinformed. We need liblldb-3.6 as well for sharedfx?

**Comment by ellismg** [comment]
> liblldb-3.6

This is necessary if you want to load the SOS plugin in LLDB.  If there's a way to say it's "optional", we should do that.  The runtime will function fine without it, but using lldb to debug the runtime will be harder (this does not impact using VS to debug managed code).

**Comment by brthor** [comment]
##dotnet-host
```
  Depends: libc6
  Depends: libgcc1
  Depends: libstdc++6
  Conflicts: dotnet
  Conflicts: dotnet-nightly
```

#dotnet-sharedframework
```
  Depends: libc6
  Depends: libcurl3
  Depends: libgcc1
  Depends: libgssapi-krb5-2
  Depends: libicu52
  Depends: liblldb-3.6
  Depends: liblttng-ust0
  Depends: libssl1.0.0
  Depends: libstdc++6
  Depends: libunwind8
  Depends: libuuid1
  Depends: zlib1g
  Depends: dotnet-host
```

#dotnet-dev 
```
  Depends: libc6
  Depends: libgcc1
  Depends: libstdc++6
  Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-3002702
  Depends: clang-3.5
```

**Comment by brthor** [comment]
@ellismg We can do this by manually setting liblldb-3.6 to an recommended dependency and passing a `-X` argument to [dpkg-shlibdeps](http://manpages.ubuntu.com/manpages/wily/man1/dh_shlibdeps.1.html) in the rules file of the runtime package.

**Comment by ellismg** [comment]
>  to prevent the auto-detection on whatever library is bringing in the depdency

The library bringing in the dependency is `libsosplugin.so`.

**Comment by degrim** [comment]
@brthor I don't see gettext in that list, but the dotnet-install.sh script checks for it.  Is gettext actually required on debian-based systems?

**Comment by ellismg** [comment]
That is a bug in the script.  The gettext dependency is a compile time dependency and not a runtime one (the runtime support is present in glibc).

**Comment by brthor** [comment]
Filed issue #3108 for the install script.

What I'm seeing here, is that we need to remove `clang3.5` dependency, and do some work to make `liblldb-3.6` an optional dependency. 

Do all other dependencies look appropriate? 

`libgssapi-krb5-2` What is this one?

**Comment by ellismg** [comment]
> `libgssapi-krb5-2` What is this one?

It's used by some of the networking code to talk to either Kerberos or NTLM servers, or something related. It's a newer dependency (we added it back in the middle of march).

**Comment by ellismg** [comment]
> Do all other dependencies look appropriate?

They look correct to me.

**Comment by brthor** [comment]
The clang-3.5 dependency has been removed here. 

Going to keep this open for tracking lldb as an optional dependency but retarget for preview3

**Comment by brthor** [comment]
lldb got removed as a dependency
