### ISSUE TITLE
OS X: dotnet-compile outputs error that it cannot copy corehost to the output directory 

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#309]
In https://github.com/dotnet/cli/pull/299 we added a workaround to unblock dotnet compile failing on OS X with the error of not being able to copy corehost. The crux of the issue is explained in dotnet/coreclr#2128. The workaround was to add a postinstall copy step for corehost to /usr/local/bin instead of a symlink.

We need to solve this properly so this issue is for tracking the proper conclusion and removal of the postinstall step.

**Comment by piotrpMSFT** [comment]
@blackdwarf, still an issue?

**Comment by brthor** [comment]
@blackdwarf do you know if we're still doing this?

**Comment by blackdwarf** [comment]
I'm pretty sure that we're not, we can close this. We are now adding the path into `paths.d` and nothing is being symlinked anymore.
