### ISSUE TITLE
project json schema is refereing to pre/postbuild and code to pre/postcompile

### ISSUE THREAD

**Issue by Tasteful** [dotnet/cli#3094]
## Steps to reproduce
Create a project.json that includes 
```
  "scripts": {
    "postbuild": "echo postbuild"
  }
```
That regarding to http://json.schemastore.org/project-1.0.0-rc2 (http://json.schemastore.org/project) are the correct script-name for build (pre/post).

## Expected  behavior
The script should be executed

## Actual behavior
The script is not executed,
regarding to https://github.com/dotnet/cli/blob/ac4c6702d5d345dc9c397f80290f105fedebe98b/src/Microsoft.DotNet.Cli.Utils/ScriptNames.cs the name of the different script should end with "compile" and not "build". If changing to `postcompile` the script is executed.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@ajaybhargavb can you comment?

**Comment by ajaybhargavb** [comment]
Nothing changed here as part of the recent changes to the project.json schema. I am guessing this has always been the case. It could just be that the schemastore had the wrong values. @anurse, do you recall any changes made in this part?

**Comment by anurse** [comment]
Yeah, I think schemastore just had the wrong values. We changed it during the dotnet cli work.

**Comment by ajaybhargavb** [comment]
schemastore/schemastore@b8f5a46d61975041ca8febab92687b0dcfe45455
