### ISSUE TITLE
version of dotnet core

### ISSUE THREAD

**Issue by melsayed** [dotnet/cli#3095]
hello all,

what should be the right version after install RC2?

because after installed i always got version 1.0.0-preview1-002702
not version 1.0.0-RC2

need help of this

**Comment by tverboon** [comment]
It's .Net Core RC2 and .NET Core SDK Preview 1.

So dotnet --version should show: 1.0.0-preview1-002702. It is the right version.

https://blogs.msdn.microsoft.com/dotnet/2016/05/16/announcing-net-core-rc2/

**Comment by blackdwarf** [comment]
@tverboon is right. Closing this with that answer.
