### ISSUE TITLE
dotnet restore does not prompt for authentication

### ISSUE THREAD

**Issue by james-uffindell-hpe** [dotnet/cli#3097]
## Steps to reproduce
When using a Nuget repository that requires authentication, dotnet restore fails with a 401 Unauthorized unless the password is provided in cleartext in the Nuget config file. The underlying issue seems to be similar to #2510 - as mentioned in that ticket, a cleartext password in the Nuget config file works.

However, having cleartext passwords in the config file isn't great, and with the original (non-dotnet) workflow, if there were no passwords in the config file, "nuget restore" on the command line would prompt for username/password credentials. Doing a nuget restore from within VS2015 would pop up a dialog box asking for username/password credentials as well.

Running "dotnet restore" does not prompt for any credentials at all, but just instantly fails after getting the 401 Unauthorized. This is also the case when restoring within a VS2015 ".NET Core" project - no credential dialog appears.

## Expected behavior
If the Nuget repository requires authentication and there are no credentials in the config file, "dotnet restore" should prompt for credentials when run from the command line or from within VS2015, the same way that "nuget restore" does.

## Actual behavior
"dotnet restore" does not prompt for credentials and just fails with 401 Unauthorized.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

I'm using NuGet version 3.4.3.855.

**Comment by davidfowl** [comment]
It's a known limitation of NuGet right now. /cc @yishaigalatzer

**Comment by piotrpMSFT** [comment]
@yishaigalatzer @rrelyea can you link the associated NuGet issue? Closing CLI issue as external, but a pointer would be nice for folks that run across this.

**Comment by cwe1ss** [comment]
w00t? is there any other way to use authenticated feeds with dotnet cli in the meantime? 

A pointer to the nuget issue would be great. haven't found anything in the nuget repo.

**Comment by alpaix** [comment]
@cwe1ss Plaintext passwords is the only supported method of authenticating NuGet feeds with dotnet cli. Interactive credential acquisition is not enabled. Encrypted passwords support is blocked due to missing `ProtectedData.Protect` API on CoreCLR.

**Comment by Jose-CF** [comment]
Any updates in here? Terrible...

**Comment by livarcocc** [comment]
Please, follow up on this on the NuGet issue linked above. Here again it is again: https://github.com/NuGet/Home/issues/2887.
