### ISSUE TITLE
Does DependencyContext loads libraries from the current build?

### ISSUE THREAD

**Issue by ivaylokenov** [dotnet/cli#3099]
## Steps to reproduce

I have the following project.json file in a project called "MyTested.Mvc.Test":

```json
{
  "authors": [ "Ivaylo Kenov" ],
  "packOptions": {
    "projectUrl": "https://github.com/ivaylokenov/MyTested.Mvc",
    "licenseUrl": "https://github.com/ivaylokenov/MyTested.Mvc/blob/master/LICENSE"
  },

  "buildOptions": {
    "warningsAsErrors": true
  },

  "testRunner": "xunit",

  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "MyTested.Mvc": {
      "version": "1.0.0-*",
      "type": "build"
    },
    "dotnet-test-xunit": "1.0.0-*",
    "xunit": "2.1.0"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        },
        "System.Diagnostics.Process": "4.1.0-*",
        "System.Diagnostics.TraceSource": "4.0.0-*"
      }
    },
    "net451": { }
  }
}
```

Then in a test I call

```c#
var library = DependencyContext
    .Default
    .RuntimeLibraries
    .FirstOrDefault(c => c.Name == "MyTested.Mvc.Test");

var dependency = library.Dependencies.FirstOrDefault(d => d.Name == "MyTested.Mvc");
```

## Expected  behavior

I expect to find the dependency with type "build".

## Actual behavior

The dependency is null. If I change it to "Microsoft.AspNetCore.Mvc", which is an external library, it works correctly. Is this expected behavior?

Also if I run the following:

```c#
var library = DependencyContext
    .Default
    .RuntimeLibraries
    .FirstOrDefault(d => d.Name == "MyTested.Mvc");
```

Then the library is found but as I mentioned above, it is not listed as a dependency on the "MyTested.Mvc.Test" while it should be.

**Comment by ivaylokenov** [comment]
I changed the project.json file from this:

```c#
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "MyTested.Mvc": {
      "version": "1.0.0-*",
      "type": "build"
    },
    "dotnet-test-xunit": "1.0.0-*",
    "xunit": "2.1.0"
  },
```

To this:

```c#
"dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "dotnet-test-xunit": "1.0.0-*",
    "xunit": "2.1.0",
    "MyTested.Mvc": "1.0.0-*"
  },
```

It seems that now the dependency is loaded correctly and everything works fine, however I believe the above is a bug.

**Comment by davidfowl** [comment]
It's not a bug. Dependencies of type build don't make it into the output. There are 2 APIs:

- DependencyContext - Used at runtime (relies on {app}.deps.json)
- ProjectContext - Used a design time (relies on `project.json`)

The deps file has a trimmed down dependency set that reflects the things that are required at runtime only. If you want to get at project information, then use the ProjectContext

**Comment by ivaylokenov** [comment]
@davidfowl Thank you for the answer, it is much clear now. :+1:
