### ISSUE TITLE
CLI Test Runner returns different ApplicationName than the DNX one

### ISSUE THREAD

**Issue by ivaylokenov** [dotnet/cli#3101]
I am opening this issue here because the test runner repository cannot have issues.

## Steps to reproduce

Create test project named "MyApp.Test" (or whatever name you like).

Somewhere in the tests call:

```c#
var applicationName = PlatformServices.Default.Application.ApplicationName;
```

## Expected  behavior

In DNX we received "MyApp.Test".

## Actual behavior

In CLI we receive "dotnet-test-xunit".

While I know this is not a bug and completely understand why "dotnet-test-xunit" is received, I believe it is not useful enough and it is somehow a breaking change. It will be better to get the test project's name. Is there any way to get it without traversing and searching in the DependencyContext?

**Comment by davidfowl** [comment]
You're correct, it's not a bug and there's no easy way to get the project name. What are you trying to do?

**Comment by ivaylokenov** [comment]
@davidfowl Thank you for the answer. I am writing a testing framework for ASP.NET Core MVC similar to this one: https://github.com/ivaylokenov/MyTested.WebApi

I want the developer who use it to be able to add TestStartup file at the root of the project, define his/her services there by inheriting the original web Startup class and replace the ones who need mocks. For example:

```c#
public class TestStartup : Startup
{
    public void ConfigureTestServices(IServiceCollection services)
    {
        base.ConfigureServices(services); // register base services from original web project
        services.Replace<IDb, MockedDb>(); // replace with mocks
    }
}
```

And then in the test:

```c#
MyMvc
    .Controller<MyController>()
    .WithServiceSetup<IDb>(s => s.SomeSet.Add(someTestObject))
    .Calling(c => c.MyAction())
    .ShouldReturn()
    .View()
    .WithModel<MyModel>()
    .Passing(m => m.SomeProperty == someTestObject.SomeProperty);
```

This way `MyController` will be instantiated with the registered at startup mocked services, without the developer writing ones for every single test. I want the framework to get the TestStartup class and use it before running the first test. In DNX my idea was working fine with the ApplicationName, but now I will just search in the DependencyContext and try to find a library that references "MyTested.Mvc" which is the testing framework I am writing.

I was hoping for an easier and more optimized solution without searching over a lot of dependencies but will use it and see how it behaves.

I am closing the issue. Thank you again!
