### ISSUE TITLE
dotnet.exe locks web application .dll file, prevents re-deployment

### ISSUE THREAD

**Issue by dg9ngf** [dotnet/cli#3102]
## Steps to reproduce

* Deploy an ASP.NET Core 1.0 RC2 web application to an IIS web server
* Open the web page in a browser
* Deploy the app again

## Expected  behavior

* .dll file is copied to IIS application path

## Actual behavior

* dotnet.exe (started by w3wp.exe) locks the main web application .dll file and msdeploy can't overwrite it

## Environment data
`dotnet --info` output:
> Did not find a suitable dotnet SDK at 'C:\Program Files\dotnet'. Install dotnet SDK from https://github.com/dotnet/cli

**Comment by davidfowl** [comment]
File this issue on aspnet/Home

**Comment by dg9ngf** [comment]
404 - Where's that?

**Comment by vcsjones** [comment]
@dg9ngf https://github.com/aspnet/Home/issues

**Comment by dg9ngf** [comment]
Duplicate of https://github.com/aspnet/Home/issues/694, still unresolved

**Comment by Gopi1993** [comment]
after a long search , killing the exe in task manager - details resolves the issue.

**Comment by Chrispy555** [comment]
Still happening in VS Community 2019, can`t find dotnet.exe in task manager!
