### ISSUE TITLE
dotnet-test.Tests block infinitely if one of the tests fail

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#3109]
And thereby blocking the entire builds.

Example Build failures
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/debug_centos7.1_x64_prtest/1950/console
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/debug_debian8.2_x64_prtest/788/console
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/release_osx_x64_prtest/2000/console
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/release_rhel7.2_x64_prtest/1944/

**Comment by piotrpMSFT** [comment]
@livarcocc can you take a look?
