### ISSUE TITLE
dotnet (1.0.0-preview1-002702) publish doesn't include runtime (with Microsoft.NETCore.Runtime nuget package)

### ISSUE THREAD

**Issue by waynesi** [dotnet/cli#3110]
I'm used to dnu/dnx toolchain but new to dotnet cli, so my question may be stupid although I did my homework on the github and stackoverflow with no luck.

## Steps to reproduce
1. Installed .Net Core 1.0.0 RC2 - SDK Preview 1 (x64) and -VS 2015 Tooling Preview 1
2. Create a Console Application (.Net Core) project
3. As Sridhar-MS suggested in https://github.com/dotnet/cli/issues/289, add Microsoft.NETCore.Runtime as a dependency in project.json, so the file looks like 
```
  "dependencies": {
    "Microsoft.NETCore.App": {
        "type": "platform",
        "version": "1.0.0-rc2-3002702"
    },
    "Microsoft.NETCore.Runtime": "1.0.2-rc2-24027"
  },
```
4. Use ```dotnet publish -c Release -f netcoreapp1.0 -r win10-x64``` to make a release build. ```dotnet publish -c Release``` also tried and yielded same result. 

## Expected  behavior
Expected some sort of executable and the runtime in the netcoreapp1.0\publish folder

## Actual behavior
Only one .dll plus two .json and one .pdb file

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by waynesi** [comment]
Very coincidentally found the solution following [the official documentation](http://dotnet.github.io/docs/core-concepts/app-types.html). Thanks for the info but have to say it's not that easy to dig some useful and up-to-date info out of a pile of yet-to-construct articles. :-)

**Comment by jkristia** [comment]
how did you resolve this?. I'm not able to get the runtime dlls copied into the publish folder.
