### ISSUE TITLE
dotnet-install.ps1 should work on NanoServer

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#3113]
Download and run https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1 on a NanoServer.

**Actual Results:**
powershell : new-object : Cannot find type [net.webclient]: verify that the assembly 
    + CategoryInfo          : NotSpecified: (new-object : Ca...t the assembly :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
containing this type is loaded.
At line:1 char:9
+ &{iex ((new-object net.webclient).DownloadString('https://raw.githubu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentExcepti 
   on
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewOb 
   jectCommand

**Expected Results:**
Script should install the dotnet cli successfully.

The script is using Invoke-WebRequest which is based on net.webclient.  I believe you need to use HttpClient in order for it to work on Nano.

**Comment by piotrpMSFT** [comment]
Moving to preview3

**Comment by mellinoe** [comment]
@Priya91 were you going to take this one over? The version I gave you should actually work on nano if you install the latest CLI. The missing file I mentioned to you was actually another issue with CLI that has since been fixed. The only work remaining would be to get the script to work on both nano and regular powershell at once.

**Comment by Priya91** [comment]
@mellinoe I didn't get time to get it working, this is pushed to preview3 :(

**Comment by naamunds** [comment]
The Nano Server team has stated that the Invoke-WebRequest PS cmdlet will be supported in RTM of Nano Server, so that should make this task easier.
