### ISSUE TITLE
Add installer support for NanoServer

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#3115]
Installing dotnet cli on NanoServer is not trivial.  We should have installer support for this.  Possibly create an [APPX or WSA installer](https://blogs.technet.microsoft.com/nanoserver/2015/11/18/installing-windows-server-apps-on-nano-server/).

**Comment by blackdwarf** [comment]
@piotrpMSFT I filed this in the future 1.1.0 milestone because I'm not sure what is the priority of this one.

**Comment by MichaelSimons** [comment]
With the interest in Nano, it would sure be nice to have a one line installation story sooner rather than later.

cc @dleeapho

**Comment by piotrpMSFT** [comment]
@MichaelSimons does the `dotnet-install.ps1` vector not suffice for a one-line installation story here?

**Comment by piotrpMSFT** [comment]
related to #3113

**Comment by MichaelSimons** [comment]
@piotrpMSFT, `dotnet-install.ps1

**Comment by MichaelSimons** [comment]
@piotrpMSFT, `dotnet-install.ps1` does not satisfy the requirement IMO because the acquisition part of the story.  How do you easily get the installer onto the machine?  Being able to install from a store such as a chocolatey package would get us to having a true one liner.

**Comment by blackdwarf** [comment]
@MichaelSimons wait, can't you do `Invoke-WebRequest` or something similar from PowerShell on Nano? I admit, I have 0 knowledge of Nano server. :)

**Comment by MichaelSimons** [comment]
@blackdwarf - Unfortunately not.  Using `Invoke-WebRequest` is the source of https://github.com/dotnet/cli/issues/3113.  The alternative is using something like HttpClient which is cumbersome IMO.
```
        $httpClient = New-Object System.Net.Http.HttpClient;
        $stream = $httpClient.GetAsync($uri).Result.Content.ReadAsStreamAsync().Result;
        $file = [System.IO.File]::Create($dotnetFileName);
        $stream.CopyTo($file);
        $file.Close();
```

**Comment by blackdwarf** [comment]
Well, I never...ok, but Chocolatey exists on Nano?

**Comment by MichaelSimons** [comment]
There is a Chocolatey provider but upon further reading it doesn't look like it is officially supported by msft.  I think part of this issue is to do further research and figure out what would be the best option for CLI.

**Comment by naamunds** [comment]
After further investigation, we have decided that the dotnet-install.ps1 script is sufficient.  https://github.com/dotnet/cli/issues/3113 tracks this script supporting Nano Server.

As the Nano Server usage grows and the ecosystem matures, there may be a demand for a WSA installer, at which point it should be considered.
