### ISSUE TITLE
no executable found matching command microsoft.entityframeworkcore.tools.cli

### ISSUE THREAD

**Issue by shivajiraot** [dotnet/cli#3117]
Project.json:
I have a class library project set to run on `net452` (not `netcoreapp1.0` or `netstandard1.5`). Migrations used to work on this framework earlier with rc1 but not with rc2.

```
{
  "version": "1.0.0",
  "description": "A Class Library",

  "dependencies": {
    "Microsoft.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Newtonsoft.Json": "8.0.3",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Azure.Search": "1.1.1",
    "Microsoft.AspNetCore.Http.Extensions": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Tools": {
      "type": "build",
      "version": "1.0.0-preview1-final"
    }
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net452+win81"
      ]
    }
  },
  "frameworks": {
    "net452": {
    }
  }
}
```

When I try to add a migration, I get below error:
`no executable found matching command "Microsoft.Entityframeworkcore.Tools.Cli" The preview of Entity Framework Framework tools does not support targeting a class library in ASP.NET Core and and .NET Core applications.`
I thought this restriction is only when targeting `netcoreapp1.0`, isn't it? What's wrong I am doing here?

**Comment by ajtowf** [comment]
Same thing for an aspnet core rc2 app, can't add migrations anymore:

>dotnet ef --verbose
Using project 'x'.
Using framework 'netcoreapp1.0'.
Using configuration 'Debug'.
Running x\project.json --configuration Debug --framework netcoreapp1.0
Process ID: 14292
Project x (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Invoking dependency command 'Microsoft.EntityFrameworkCore.Tools.Cli' in project 'x'
No executable found matching command "Microsoft.EntityFrameworkCore.Tools.Cli"
Could not invoke this command on the project. Check that the version of Microsoft.EntityFrameworkCore.Tools in "tools" and "dependencies" are the same. See http://go.microsoft.com/fwlink/?LinkId=798221 for more details.
>

**Comment by bastienJS** [comment]
I experience the same problem with asp.net core rc2 + EFCore and .net 461.

The workarounds on that site: https://github.com/aspnet/EntityFramework.Docs/blob/master/docs/cli/dotnet.rst

does not work!  

See: https://github.com/aspnet/EntityFramework.Docs/issues/174

**Comment by PivotalAnimal** [comment]
Same.
"Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc2-final",
"tools": {
    "Microsoft.EntityFrameworkCore.Tools.Core": {
      "version": "1.0.0-preview1-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    }
}
  "frameworks": {
    //"netcoreapp1.0": {
    //  "imports": [
    //    "dotnet5.6",
    //    "dnxcore50",
    //    "portable-net45+win8"
    //  ]
    //},
    "netstandard1.5": {
      "imports": [
        "dnxcore50",
        "portable-net452+win81"
      ]
    }
  },

When I try to change the "tools" section to reference rc2 that fails as well.

**Comment by Akimi** [comment]
It seems it is known issue, see [this](https://docs.efproject.net/en/latest/cli/dotnet.html#preview-1-known-issues) for more details. Or [here](http://stackoverflow.com/questions/37371091/migrations-in-ef-core-rc2).

The workaround is temporary conversion of a class library project into an app project. So I added `"emitEntryPoint": true` to project.json and defined empty `static void Main()`. Migrations now working as expected. Here is my `project.json` framgment:

```
"frameworks": {
    "net452": {
    }
},
"buildOptions": {
    "emitEntryPoint": true
},
```

**Comment by nmtoan07** [comment]
@shivajiraot : If you're using window7, try install Windows Management Framework 5.0
https://www.microsoft.com/en-us/download/details.aspx?id=50395

I have the similar too, and i solved that problem by Windows Management Framework 5.0 installed

Hope it helps!

**Comment by bastienJS** [comment]
@piotrpMSFT  Same broken behavior in RTM version...

**Comment by blackdwarf** [comment]
I believe that this is a known issue for EF tools. @bricelam can you comment?

**Comment by bricelam** [comment]
The world has changed a lot with the switch to MSBuild. See aspnet/EntityFramework#7358 for instructions on using the latest bits. If you can't get things working there, please let us know.

**Comment by piotrpMSFT** [comment]
@bricelam can we close this one, then?

**Comment by bricelam** [comment]
Fine with me. ☺
