### ISSUE TITLE
Wrapping dlls using framework->bin->assembly does not work

### ISSUE THREAD

**Issue by elvirb** [dotnet/cli#3118]
## Steps to reproduce
```javascript
{
 "frameworks": {
    "monotouch": {
      "bin": {
        "assembly": "Some.dll"
      }
    }
  }
}
```

## Expected  behavior
The project is built wrapping the supplied dll.

## Actual behavior
There is no output for the build.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by acervantes** [comment]
I think you can solve it by creating your own Nuget local repository:
1. Follow these [steps](https://docs.nuget.org/create/creating-and-publishing-a-package#from-an-assembly) to create a nuget package for your assembly
2. Create a folder at solution level and copy the nuget package into it (for example: c:\mysolution\lib)
3. Add or edit a solution level [NuGet.Config](https://docs.nuget.org/consume/nuget-config-file) file.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="LocalFeed" value="lib" />
  </packageSources>
</configuration>
```

You should be able to add the dependency in the project.json file of any project from that solution.

**Comment by elvirb** [comment]
I don't really want to create a local nuget repo. Any reason why this feature was removed from dotnet rc2+?

**Comment by brthor** [comment]
This feature exists, see this test:

https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/TestProjects/TestAppWithWrapperProjectDependency/TestLibrary/project.json

**Comment by elvirb** [comment]
That's what I'm doing currently sans the pdb reference. It doesn't copy the DLL into the bin/* directory which confuses IDE's such as VSCode.

**Comment by brthor** [comment]
Do you have a referencing project.json?

**Comment by elvirb** [comment]
Yes. This is the project.json for that project. It currently has compilation issues in VSCode - it works fine when using "dotnet build + restore":

`
{
  "version": "1.0.0-*",
  "dependencies": {
  },
  "frameworks": {
    "monotouch": {
      "dependencies": {
        "mscorlib": {
          "target": "project",
          "version": "3.5.0-Unity"
        },
        "System": {
          "target": "project",
          "version": "3.5.0-Unity"
        },
        "System.Core": {
          "target": "project",
          "version": "3.5.0-Unity"
        }
      }
    }
  }
}
`

**Comment by elvirb** [comment]
This is a VSCode bug - closing this issue.
