### ISSUE TITLE
Refactor the Publishing code to be more organized

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#3120]
# Overview
When we publish built code and installers today, compiled units are compressed into archives and put into the same root folder in one Azure Blob Container (ie ```<root>\<cli_version>``` or ```<root>\<other version>```). This requires consumers of the archives (or installers) to understand the product difference between versions 1.0.0-rc2-3002520 and 1.0.0-rc2-002520.

# Proposal
In order to organize the intermediate and final build outputs (archive files and installers, respectively), I propose the following:

1. Abandon the ```beta``` folder and instead have the folder driven by a branch-specific-channel
2. Create two subfolders in every Channel folder: ```Packages``` for build consumables (nupkgs, MSIs, debian packages) and ```Intermediates``` for build intermediates (direct build outputs packaged as archives). This adds a logical separation between the build stage and the packaging stage; this gives us the freedom to rev these two pipelines independently.
3. Both ```Packages``` and ```Intermediates``` would have children folders for the specific products (Shared Framework, Host, SDK). This removes the complexity around knowing which version number means what (mainly around the '3' prefix for the version number means a different product than when the '3' is not present).
4. Each product and package folder will contain the ship train folders: Latest, LKG, Production, which will contain the relevant bits as well as a version badge and version textual file. This will allow automated systems to watch the specific train and take action when necessary, rev'ing individual products independently.

# Changes
The changes to make this happen would be contained entirely in two files: [AzurePublisher.cs](https://github.com/dotnet/cli/blob/rel/1.0.0-preview1/scripts/dotnet-cli-build/Publishing/AzurePublisher.cs) and [PublishTargets.cs](https://github.com/dotnet/cli/blob/rel/1.0.0-preview1/scripts/dotnet-cli-build/PublishTargets.cs)

# Future
Once the switch to use msbuild comes along, the only changes that should be necessary would be to the code to publish the bits to the blob locations; no external or breaking changes should be necessary.

Thoughts / comments / feedback @piotrpMSFT, @Sridhar-MS, @livarcocc, @brthor, @krwq?

**Comment by brthor** [comment]
Aren't our zip packages also consumables? Would it make more sense to group them with other consumables?

**Comment by sokket** [comment]
I was breaking the outputs out into "packages that users will manually get (exes, msis, nupkgs, debian packages)" and and "packages that automation will grab (archives)". Basically, unless someone knows that they should do otherwise, they should grab the installer or packaged bits....that was my goal.

Thoughts?

**Comment by piotrpMSFT** [comment]
What's the benefit of breaking them apart? These are just different projections of the same build artifacts. I'd keep them together.

**Comment by piotrpMSFT** [comment]
Reading closer, this becomes more apparent. The archives are not intermediates and are in fact more mission critical than the native installers. Let's unify. Folks don't have browse access to these directories so unification won't hurt anything.

**Comment by sokket** [comment]
After an offline discussion, we have closed on a slightly modified version of @brthor's feedback.

We will be dropping all build and packaging output into the following blob structure:
```
<root> - 
   Host -
      <version> -
         <all build and package output files>
   Framework
      <version> - 
         <all build and package output files>
   SDK
      <version> -
         <all build and package output files>
```

All pointers (Latest, LKG, Production, etc) will be hosted in the [GitHub repo](https://github.com/dotnet/versions) that @eerhardt has setup to track versioning. There will not be any .version files in the blob storage; only build and packaging outputs.


@brthor @eerhardt @piotrpMSFT does this sound like what we discussed?

**Comment by brthor** [comment]
@eerhardt Can we put a commit hash with the version in the versions repo? Similar to our `.version` file content today?

**Comment by eerhardt** [comment]
We can put any file we want in this repo.  We can put a `.version` file if we want...

The idea is, the versions repo contains the necessary information for your consumers to know about the different build versions of your repo.  If a commit hash is part of that "necessary information", then putting the commit hash is fine.

**Comment by sokket** [comment]
Awesome, I have most of this written now; I'm waiting for #3230 to go in before making more changes since there will be conflicts

**Comment by sokket** [comment]
Closing, not needed

**Comment by eerhardt** [comment]
We still need to fix this issue. Our current publishing story isn't ideal.
