### ISSUE TITLE
Unresolved references when using a PCL dependency

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#3125]
## Steps to reproduce

project.json:

``` json
{
  "version": "1.0.0-*",
  "dependencies": {
    "NetStandard.Library": "1.5.0-rc2-*",
    "Newtonsoft.Json": "7.0.1"
  },
  "frameworks": {
    "netstandard1.0": {
      "imports": [ ".NETPortable,Version=v4.5,Profile=Profile259" ]
    }
  }
}
```

Program.cs

``` csharp
using System;

using Newtonsoft.Json.Linq;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var o = JObject.Parse("{ \"a\": 1 }");
            System.Diagnostics.Debug.WriteLine(o.ToString());
        }
    }
}
```

Commands:

```
dotnet restore
dotnet build
```
## Expected  behavior

A successful build, because [in order to ease transition to .NET Platform Standard, packages targeting it will be able to depend on PCL packages through the imports element](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md).
## Actual behavior

A failed build:

```
Project test (.NETStandard,Version=v1.0) will be compiled because expected outputs are missing
Compiling test for .NETStandard,Version=v1.0
C:\Program Files (x86)\dotnet\dotnet.exe compile-csc @C:\temp\test\obj\Debug\netstandard1.0\dotnet-compile.rsp returned Exit Code 1
C:\temp\test\Program.cs(11,20): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'.
C:\temp\test\Program.cs(11,12): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'.
C:\temp\test\Program.cs(12,41): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'.

Compilation failed.
    0 Warning(s)
    3 Error(s)
```

EDIT: Using either `portable-net45+wp80+win8+wpa81+dnxcore50` or `dnxcore50` works, but `dnxcore50` maps to `dotnet5.4`, and this maps to `netstandard1.3`, which seems dangerous. 
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by troydai** [comment]
@fubar-coder please try add "dnxcore50" to the list of "imports".

**Comment by fubar-coder** [comment]
`dnxcore50` maps to `dotnet5.4`, which in turn maps to `netstandard1.3`, which seems dangerous. Using `portable-net45+wp80+win8+wpa81+dnxcore50` as workaround works as expected.

**Comment by davidfowl** [comment]
@fubar-coder use https://www.nuget.org/packages/Newtonsoft.Json/8.0.4-beta1  it supports netstandard.

**Comment by fubar-coder** [comment]
This does work, but there are other PCLs out there, that don't support netstandard (yet).

**Comment by emgarten** [comment]
This is a known issue with the newtonsoft.json package. portable-net45+wp80+win8+wpa81+dnxcore50 is not a real framework which causes a portable-net40-* folder to be selected, and that hits issues with mscorlib under netstandard.

**Comment by piotrpMSFT** [comment]
Closing as a new newtonsoft package has shipped.
