### ISSUE TITLE
Resgen in dotnet debian package conflicts with resgen in mono-devel

### ISSUE THREAD

**Issue by shahid-pk** [dotnet/cli#313]
This was reported in #125 but that issue was closed without a fix or workaround.

**Comment by brthor** [comment]
@anurse What all is involved in fixing this? Mono and dotnet are likely to be used side by side frequently and I see this as a big issue.

**Comment by anurse** [comment]
We should just rename our `resgen`. It's not intended to be used externally, and is not a complete `resgen` replacement. /cc @davidfowl

**Comment by piotrpMSFT** [comment]
@anurse, @brthor why is our resgen on the path? We should only be exposing dotnet-resgen, right?

**Comment by shahid-pk** [comment]
@piotrpMSFT  resgen is installed into /usr/bin , anything that goes their is automatically on path but if resgen is not intended to be used stand alone than their is not point installing it to /usr/bin , install it to any other place that is not on the path and point dotnet cli tools to that location then renaming resgen will not be required.

**Comment by brthor** [comment]
@piotrpMSFT our dotnet-Resgen is named Resgen. We just need to change the name and places where it's invoked.

**Comment by anurse** [comment]
I'd definitely like to rename `resgen`, at least for now, it is not a full replacement for the actual `resgen` tool, it is extremely limited to specific scenarios. In general we need to resolve the difference between internal tools and externally-visible tools.

**Comment by piotrpMSFT** [comment]
let's rename this tool to dotnet-resgen for the time being. I'd like to keep that name in the long term so the CLI can stay in the loop with these tools and allow for package-based distribution.

**Comment by shahid-pk** [comment]
this is fixed now with the latest .deb package.
