### ISSUE TITLE
RC2 MVC controller edit slower than in RC1

### ISSUE THREAD

**Issue by tatalvit** [dotnet/cli#3130]
## Steps to reproduce

I tested RC1 and RC2. Created new project: "ASP.NET Core Web Application (.NET Core)" and "Empty" as ASP.NET Core template.

Test case A: 1) Run without debugging 2) wait for startup.cs to write "Hello world!" 3) modify text to "Hello world 2!" Ctrl+S 4) Hit F5 in browser.
Test case A results in RC1: IIS Express responds within 4-5 seconds with "Hello world 2!"
Test case A results in RC2: IIS Express responds within 4-5 seconds with "Hello world 2!" and avg compilation time is 2.3 seconds.

Test case B: One simple controller and view. Controller action has ViewData["Message"] = "Hello world!"; and view shows that message. 1) Run without debugging 2) wait for controller to write "Hello world!" 3) modify text to "Hello world 2!" Ctrl+S 4) Hit F5 in browser.
Test case B results in RC1: IIS Express responds within 4-5 seconds with "Hello world 2!"
Test case B results in RC2: IIS Express responds within 9-12 seconds with "Hello world 2!" and avg compilation time is still the same 2.3 seconds.

So what is happening with MVC now in RC2? Where is the extra 5 seconds wasted? It is pain to wait 10 seconds after each change
## Expected  behavior

4-5 seconds response time to see the changes
## Actual behavior

9-12 seconds response time
## Environment data

`dotnet --info` output:

dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@davidfowl @anurse care to weigh in?

**Comment by davidfowl** [comment]
It's slower because of a bunch of reasons. In short we'll be looking at improving this post RC2. It's a combination of tooling and runtime here.

**Comment by muratg** [comment]
@Eilon Move to MVC?

**Comment by muratg** [comment]
cc @SajayAntony

**Comment by piotrpMSFT** [comment]
@muratg @Eilon are we moving this to MVC?

**Comment by Eilon** [comment]
@SajayAntony @davidfowl does this issue come down to things related to R2R/crossgen, or shared runtime, or something else?

I don't know that there's any MVC-specific issue here. It's presumably slow because it's loading Roslyn and compiling code on the fly.

**Comment by tatalvit** [comment]
Or maybe some issue in IIS Express?

**Comment by davidfowl** [comment]
It's likely a couple of things:
- Roslyn is slower because of R2R with missing generics
- There are things going on in VS when running IIS to make dynamic compilation work (we'll need to profile this).

**Comment by tatalvit** [comment]
Is this odd? By setting web.config <compilation profileGuidedOptimizations="None" /> seems to improve browser to respond MVC changes somewhat 1 second

**Comment by tatalvit** [comment]
Core 1.0.0-preview2-003121 slow to view changes: #3883

**Comment by piotrpMSFT** [comment]
This data is still based on project.json which makes it fairly unactionable. Let's see if we hit similar issues in preview3 and address them there.
