### ISSUE TITLE
Publish fails after migration from rc1 to rc2.

### ISSUE THREAD

**Issue by 4nderss** [dotnet/cli#3131]
## Background

I have tried to work out if this is something on my local machine but kind of hard to repro. I have migrated a RC1 project to RC2 using the following guide
https://wildermuth.com/2016/05/17/Converting-an-ASP-NET-Core-RC1-Project-to-RC2

My project has dependencies on older 4.6 class libraries. 
## Steps to reproduce

Either run Publish through Visual Studio or commandline dotnet publish
## Expected  behavior

Publish should succeed or give me detailed info why It does not succeed. 
## Actual behavior

Crash with null reference in Microsoft.DotNet.Publishing.targets(154,5)

`C:\Program Files\dotnet\dotnet.exe publish "C:\Source\Pascal.git\Pascal\src\Pascal" --framework net462 --output "C:\Users\Anders\AppData\Local\Temp\PublishTemp\Pascal51" --configuration Release --no-build`

After prepublish statements are run I get the following:
`C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(154,5): Error : Object reference not set to an instance of an object.`
## Environment data

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64`

```
## project.json

```
{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },
    "dependencies": {
        "Microsoft.NETCore.App": {
            "version": "1.0.0-rc2-3002702",
            "type": "platform"

        },
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-preview1-final",
            "type": "build"
        },
        "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Session": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Authentication": "1.0.0-rc2-final",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
        "Microsoft.IdentityModel.Protocols": "2.0.0-rc2-305061149",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
        "Microsoft.Extensions.Configuration": "1.0.0-rc2-final",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
        "Microsoft.Extensions.WebEncoders": "1.0.0-rc2-final"
    },

    "frameworks": {
        "net462": {
            "buildOptions": {
                "platform": "x64",
                "languageVersion": "csharp6"
            },

            "dependencies": {
                "Pascal.Common": {
                    "target": "project"
                },
                "Pascal.Core": {
                    "target": "project"
                },
                "Pascal.DependencyWrappers": {
                    "target": "project"
                },
                "SAML2.Core": {
                    "target": "project"
                },
                "SecurityFramework.TicketConverter": {
                    "target": "project"
                }
            }
        }
    },

    "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
            "version": "1.0.0-*",
            "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
        },

        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": [
                "portable-net45+win8+dnxcore50",
                "portable-net45+win8"
            ]
        }
    },
    "runtimeOptions": {
        "gcServer": false,
        "gcConcurrent": true
    },
    "publishOptions": {
        "include": [
            "wwwroot",
            "appsettings.*",
            "web.config"
        ]
    },
    "scripts": {
        "prebuild": [ "gulp ts" ],
        "prepublish": [ "npm install", "jspm install", "gulp build" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
}

```

**Comment by vijayrkn** [comment]
Do you see any output from the postpublish section ? 

e.g:
Configuring the following project for use with IIS: 'C:\Temp'
Updating web.config at 'C:\Temp\web.config'

If you don't see this, Can you try running this command manually providing the publishFolder and framework?

"dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"

**Comment by 4nderss** [comment]
It crashes immediately aftert the gulp build command. Checking the output folder C:\Users\Anders\AppData\Local\Temp\PublishTemp\Pascal51 it is empty. So I have no sources to use with donet publish-iis . Before I migrated to rc2(the new targets and props in my xproj) I saw the output you are reffering to, but now It crashes before.

Here is my xproj aswell.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.Props" Condition="'$(VSToolsPath)' != ''" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>937994a0-1f91-44bb-a462-fb13a8179abc</ProjectGuid>
    <RootNamespace>Pascal.UnitTests</RootNamespace>
   <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">.\obj</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">.\bin\</OutputPath>
	<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
  </PropertyGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\external\DosageParser\DosageParser.csproj" />
    <ProjectReference Include="..\..\external\SAML2\SAML2.Core\SAML2.Core.csproj" />
    <ProjectReference Include="..\..\external\SecurityFramework\SecurityFramework.TicketConverter\SecurityFramework.TicketConverter.csproj" />
    <ProjectReference Include="..\..\src\Pascal.Common\Pascal.Common.csproj" />
    <ProjectReference Include="..\..\src\Pascal.Core\Pascal.Core.csproj" />
    <ProjectReference Include="..\..\src\Pascal.DependencyWrappers\Pascal.DependencyWrappers.csproj" />
  </ItemGroup>
  <Import Project="$(VSToolsPath)\DotNet.Web\Microsoft.DotNet.Web.targets" Condition="'$(VSToolsPath)' != ''" />
</Project>
```

**Comment by vijayrkn** [comment]
Can you run each of these commands individually from commandline and see if you get more info on the error (you might have to add them to the path first)?

npm install
jspm install
gulp build

**Comment by 4nderss** [comment]
This is not a problem with the prepublish stuff, we can debug and run the app (which involves the above tasks) but we are unable to publish it for IIS. The gulp build finished task is the last thing logged before crash.

**Comment by 4nderss** [comment]
I went back to use dnx46 and then publish started working.

```
"frameworks": {
		"dnx46": {
			"imports": [
				"netstandard1.3"
			],
			"dependencies": {

				"Pascal.Common": {
					"target": "project",
				},
				"Pascal.Core": {
					"target": "project"
				},
				"Pascal.DependencyWrappers": {
					"target": "project"
				},
				"SAML2.Core": {
					"target": "project"
				},
				"SecurityFramework.TicketConverter": {
					"target": "project"
				}
			}
		}
	}
```
`

**Comment by Malediction** [comment]
I am also seeing this when trying to publish a brand new app created using the VS ASP.NET Core app template. The "target runtime" is "Inferred Runtime (win7-x64)" which seems a bit odd, but this might be a red herring.

**Comment by Malediction** [comment]
The "Publish" task failed unexpectedly.
System.Exception: 
Publishing FooApp for .NETFramework,Version=v4.6.2/win7-x64

Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tasks.Publish.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by vijayrkn** [comment]
@4nderss - Can you set this environment variable (COREHOST_TRACE=1) and run dotnet publish from commandline and share the output. This should tell where it is failing.

@Malediction - Target runtime ("Inferred Runtime (win7-x64)" ) should only show up for projects targeting full .Net framework. Target runtime should show as "Any" for core apps targeting the shared runtime ("type":"platform" for "Microsoft.NETCore.App" ). Can you share your project.json?

**Comment by 4nderss** [comment]
Okay, after setting that environment variable I'm unable to build the project. It gives me 5204 errors which I guess is just lines from dotnet trace.

Don't know if this helps you but here is the error list.

https://gist.github.com/4nderss/dc054ed313bc82ffa8adc49131015a54

**Comment by PeterHageus** [comment]
Same problem. Building for NET46. Have output if needed.

**Comment by PeterHageus** [comment]
Problem solved. Used the wrong template in VS to determine required changes.

Removing the dependency on "Microsoft.NETCore.App" does the trick.

**Comment by piotrpMSFT** [comment]
When targetting multiple frameworks, `Microsoft.NetCore.App` should only appear under `netcoreapp1.0`. 

@blackdwarf we should think about moving the dependency in `dotnet new` templates. I'm seeing this create a lot of confusion. Thoughts?

**Comment by blackdwarf** [comment]
@piotrpMSFT already being done in #3149

**Comment by piotrpMSFT** [comment]
Then closing :)
