### ISSUE TITLE
dotnet build should warn if no files are found to compile

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#3133]
## Steps to reproduce

Clone Dapper prior to [this commit](https://github.com/StackExchange/dapper-dot-net/commit/89908e0f028dcbc7fcf255f3716bb9bb695f438a). The issue was an extra `:` inside here:

``` json
  "buildOptions": {
    "compile:": {
      "include": [
        "../Dapper/**/*.cs"
      ],
```

There was no warning for the invalid field either, but that's a separate issue.
## Expected  behavior

`dotnet build` produces a warning indicating no files were found to build and to check your configuration.
## Actual behavior

`dotnet build` produces no output at all.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by vcsjones** [comment]
I wonder why [CS2008](https://msdn.microsoft.com/en-us/library/swb241d7.aspx) wasn't getting bubbled up from Roslyn, or why Roslyn wasn't producing that error at all.

**Comment by blackdwarf** [comment]
As you probably know, we are moving over to MSBuild and csproj in the CLI tooling. That work is under way and most of the recent Previews are based on that. I've tested the behavior of the new, MSBuild-based tooling to see what happens here and I've filed dotnet/sdk#638 to track its behavior.
