### ISSUE TITLE
dotnet hangs in Docker Container in Azure

### ISSUE THREAD

**Issue by rstropek** [dotnet/cli#3137]
## Steps to reproduce
* Create Azure VM based on *Docker on Ubuntu Server* (`CanonicalandMSOpenTech.DockerOnUbuntuServer1404LTS`)
* Connect to VM using e.g. PuTTY
* Start new Docker container: `docker run -it microsoft/dotnet:latest /bin/bash`
* Run any `dotnet` command (e.g. `dotnet --info` or `dotnet new`)
* The `dotnet` command will print the expected output but hang at the end and never return

## Expected  behavior
`dotnet` should return after doing it's job.

## Actual behavior
The `dotnet` command will print the expected output but hang at the end and never return

## Environment data
`docker version` output:
```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```

`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

**Comment by brthor** [comment]
Why is your rid `debian.8-x64`

Can you show output of:
`cat /etc/os-release`?

**Comment by rstropek** [comment]
It is the standard Azure VM *Docker on Ubuntu Server* provided by Canonical and MS. Here is the output of `cat /etc/os-release`:
```
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

BTW: I built my own Docker image using Microsoft's Dockerfile at https://github.com/dotnet/dotnet-docker/blob/master/1.0.0-preview1/Dockerfile. This locally built images shows the same behavior.

**Comment by rstropek** [comment]
Sorry, this was the output from the Docker host. I assume you wanted to see the output from within the Docker container where `dotnet` runs. Here it is:
```
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by brthor** [comment]
I made a mistake and assumed that dotnet was running on the Ubuntu host for some reason 😄 

the debian rid makes sense in the docker container.

**Comment by MichaelSimons** [comment]
@rstropek - What is the kernel version of the host?  Depending on the kernel version, you may have hit https://github.com/docker/docker/issues/18180 which is a docker issue.  The [solution](https://github.com/docker/docker/issues/18180#issuecomment-193708192) on Ubuntu 15.10 is to Upgrade kernel to 4.2.0-30.35 or later.

**Comment by rstropek** [comment]
@MichaelSimons Yes, that helped. I upgraded to kernel 4.2.8 (http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.2.8-wily/), restarted the host, started a container and now the dotnet CLI works. Thank you for your help!

For RTM, I think it would be great to have a `Docker on Ubuntu` image in Azure that supports running dotnet CLI without prior updating the kernel. However, my current problem is solved. Thank you again.

**Comment by rstropek** [comment]
Just a hint for people who want to demo dotnet CLI on Azure in a Docker container: You can use the Azure ARM Quickstart Template for Docker on Ubuntu (https://github.com/Azure/azure-quickstart-templates/tree/master/docker-simple-on-ubuntu). This will give you an environment where dotnet CLI works inside a Docker container out of the box. No need to update the Linux kernel there.
