### ISSUE TITLE
dotnet-publish must work for libraries too

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#314]
Today for a library project dotnet-publish fails with 
> 'project name' does not have an entry point defined.

xunit test cases are libraries which are reflected over by the xunit runner. And xunit tests are usually not published along with some other application or added as a dependency to an application. So we must provide a way to publish libraries.

**Comment by anurse** [comment]
Yeah, I've hit this too. Out of curiosity though, why would xunit need this? I'd expect xunit tests to be run with a shared-runtime model since they are generally run at development time.

**Comment by Sridhar-MS** [comment]
The xunit runner will be run using a shared host. But I am talking about my xunit test case dll. Let's say it has a dependency on PackageA. Right now I cannot publish my xunit test library along with PackageA to a folder. 

Now if that scenario is enabled then I can call xunit runner on my published xunit test library.

**Comment by anurse** [comment]
The test case dll will also be loaded using the shared host logic. You shouldn't have to publish the tests to run them. @davidfowl has started work on a managed library that xunit can use to facilitate this based on what we did in DNX https://github.com/dotnet/cli/tree/davidfowl/loader/src/Microsoft.DotNet.ProjectModel.Loader

Anyway, that's a separate issue. The core idea of publishing a library is a legit feature. I believe it's just a simple `if` check last time I looked. I'll see about removing it.

**Comment by Sridhar-MS** [comment]
May be I am missing something very obvious here, but in my example above how will PackageA library be loaded by the xunit runner process?

**Comment by anurse** [comment]
The same way the shared host finds it, by reading the test project's lock file and looking it up in the package cache.

**Comment by Sridhar-MS** [comment]
Oh. I thought shared host will be reading the deps file to look up dependencies.

**Comment by piotrpMSFT** [comment]
@anurse, assigning to you the removal of this if check :)

**Comment by anurse** [comment]
Sure.

@Sridhar-MS It could also read that file. There's no reason we can't have managed code to do the same thing the shared host does when setting up a load context for a test runner to operate within :)
