### ISSUE TITLE
DotNet SDK Found, DotNet.DLL not.... but its there

### ISSUE THREAD

**Issue by mvermef** [dotnet/cli#3141]
## Steps to reproduce
Installed SDK Preview

## Expected  behavior
No Error

## Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		The project is configured to use .NET Core SDK version 1.0.0-* which is not installed or cannot be found under the path C:\Program Files (x86)\dotnet. These components are required to build and run this project.	PcasoftMVC	C:\Users\Morgan\Documents\Projects\web\PcasoftMVC\src\PcasoftMVC\GETSDKTOOLINGINFO	1	

from the CLI the result is this....
C:\Users\Morgan\Documents\Projects\web\PcasoftMVC\src\PcasoftMVC>dotnet restore
Found dotnet SDK, but did not find dotnet.dll at [C:\Program Files (x86)\dotnet\sdk\1.0.0-*\dotnet.dll]

## Environment data
`dotnet --info` output:
C:\Users\Morgan\Documents\Projects\web>dotnet --info output
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86

**Comment by mobaba** [comment]
I am getting the same error...

**Comment by Echogp** [comment]
Check your .NET component very carefully, I found my .NET CLI component at the very end of .NET framework component, remove it and remove the RC2 component and re-install the RC2 component, when running HelloWorld sample app, delete the old "hwapp" if you have it, create a new one and follow the steps on MS RC2 download page will work.

**Comment by mvermef** [comment]
Global.json..... Version needs to match, sdk installed

**Comment by rasodu** [comment]
I got these error after I uninstalled old version of SDK.
For me removing SDK folder from program files solved it.

The folder in 'C:\Program Files\dotnet\sdk' for the particular SDK version didn't get deleted when I uninstalled SDK. I think I saw error 'file in use' when I was uninstalling.

It works fine after deleting the folder. For example, I deleted folder 'C:\Program Files\dotnet\sdk\2.1.300'. This was folder for RC release. I think 'dotnet' cli looks for dotnet.dll in SDK folder.

**Comment by malwareoverflow** [comment]
The sdk dll file may be corrupted or lost you can try this on debian to reinstall dotnet core sdk
 sudo apt-get install dotnet-sdk-2.1
or for latest version see 
https://www.microsoft.com/net/download/linux-package-manager/debian8/sdk-current

**Comment by viktorpeacock** [comment]
This is still a problem. Removing 2.200-preview via Programs/Features does not remove the folder in ProgramFiles/dotnet/sdk. I had to remove the folder manually for this to work.

**Comment by robert-skarzycki** [comment]
FYI - same thing after uninstalling preview on `3.0.100` - I had to manually remove preview version folders from `sdk` folder.

**Comment by n-develop** [comment]
I had the same problem after uninstalling SDK 2.2.401. Removing the empty folder made it work again.

**Comment by suadev** [comment]
Same problem for removing sdk version 3.0.100
