### ISSUE TITLE
dotnet-test: expose the help information from the runner when doing dotnet-test --help

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#3143]
We should consider also printing the help from the runner when the user does dotnet test --help. This would make discovering the runner options a lot easier.

**Comment by blackdwarf** [comment]
@livarcocc I think we should do this. First, very easy step, would be to simply inform the user that there is the possibility to pass in `--help` to the runner as well or a link or something. Second, better step, would be to pass in the `--help` to the runner, collect the output and show it on `dotnet test` as well. 

Something like (off the top of my head):

```console
NET Test Driver

Usage: dotnet test [arguments] [options]

Arguments:
  <PROJECT>  The project to test, defaults to the current directory. Can be a path to a project.json or a project directory.

Options:
  -?|-h|--help                        Show help information
  --parentProcessId                   Used by IDEs to specify their process ID. Test will exit if the parent process does.
  --port                              Used by IDEs to specify a port number to listen for a connection.
  -c|--configuration <CONFIGURATION>  Configuration under which to build
  -o|--output <OUTPUT_DIR>            Directory in which to find the binaries to be run
  -b|--build-base-path <OUTPUT_DIR>   Directory in which to find temporary outputs
  -f|--framework <FRAMEWORK>          Looks for test binaries for a specific framework
  -r|--runtime <RUNTIME_IDENTIFIER>   Look for test binaries for a for the specified runtime
  --no-build                          Do not build project before testing
---------------------
xUnit test runner 

Options:
-xml <FILE> Save test results as XML file
```

Thoughts?

**Comment by igatanasov** [comment]
also it will be very easier just to output the xunit.console.exe arguments


dotnet test --help => xunit.console.exe output

xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
Copyright (C) 2015 Outercurve Foundation.

usage: xunit.console <assemblyFile> [configFile] [assemblyFile [configFile]...]
[options] [reporter] [resultFormat filename [...]]

Note: Configuration files must end in .json (for JSON) or .config (for XML)

Valid options:
  -nologo                : do not show the copyright message
  -nocolor               : do not output results with colors
  -noappdomain           : do not use app domains to run test code
  -failskips             : convert skipped tests into failures
  -parallel option       : set parallelization based on option
                         :   none        - turn off all parallelization
                         :   collections - only parallelize collections
                         :   assemblies  - only parallelize assemblies
                         :   all         - parallelize assemblies & collections
  -maxthreads count      : maximum thread count for collection parallelization
                         :   default   - run with default (1 thread per CPU thre
ad)
                         :   unlimited - run with unbounded thread count
                         :   (number)  - limit task thread pool size to 'count'
  -noshadow              : do not shadow copy assemblies
  -wait                  : wait for input after completion
  -diagnostics           : enable diagnostics messages for all test assemblies
  -debug                 : launch the debugger to debug the tests
  -serialize             : serialize all test cases (for diagnostic purposes onl
y)
  -trait "name=value"    : only run tests with matching name/value traits
                         : if specified more than once, acts as an OR operation
  -notrait "name=value"  : do not run tests with matching name/value traits
                         : if specified more than once, acts as an AND operation

  -method "name"         : run a given test method (should be fully specified;
                         : i.e., 'MyNamespace.MyClass.MyTestMethod')
                         : if specified more than once, acts as an OR operation
  -class "name"          : run all methods in a given test class (should be full
y
                         : specified; i.e., 'MyNamespace.MyClass')
                         : if specified more than once, acts as an OR operation
  -namespace "name"      : run all methods in a given namespace (i.e.,
                         : 'MyNamespace.MySubNamespace')
                         : if specified more than once, acts as an OR operation

Result formats: (optional, choose one or more)
  -xml <filename>        : output results to xUnit.net v2 style XML file
  -xmlv1 <filename>      : output results to xUnit.net v1 style XML file
  -nunit <filename>      : output results to NUnit-style XML file
  -html <filename>       : output results to HTML file

**Comment by brthor** [comment]
@blackdwarf With your proposal, the help output would change based on the directory (based on the `testRunner` in `project.json) a user is in, which can be confusing for a first time user of dotnet-test (who need `--help` the most). 

What if we were to contain in the default help message, a set of options for the most commonly used runner, and override this when a user enters a directory with a project.json targeting a test runner other than xunit.

**Comment by blackdwarf** [comment]
@brthor sounds a little messy. Also, wouldn't we want it to change based on the testRunner? :)

**Comment by livarcocc** [comment]
I think I am fine with what @blackdwarf initially suggested.

We show the help for dotnet test and under it, we can put some separation: -------- or ===== or something and say test runner help: <runner> and show the content for the runner, if the project hasn't been restored. Otherwise, we can show a message saying restore to see runner help options?

Would this be ok?

**Comment by brthor** [comment]
Why messy? It provides a default experience that makes sense for 80% of use cases and caters to new users of the toolset, who might not even be aware of the significance of the testRunner property in the project.json. 

It would change based on testRunner when that information is present.

**Comment by blackdwarf** [comment]
@brthor people need to be aware of the significance of the test runner property for now, because it tells them what test runner they are using. I like @livarcocc approach. Consider also one thing: if you mix the two, if people didn't restore, they may try to pass in a switch that fails because the binary is not there to handle it.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#794
