### ISSUE TITLE
Upgrading to DotNet Core RC2 Preview seems to have broken Visual Studio

### ISSUE THREAD

**Issue by joshmouch** [dotnet/cli#3144]
Let me start by saying that I'm receiving errors left and right inside Visual Studio since upgrading to the newest version of DotNet Core.  I'm going to just post one of the problems here in the hopes that they're all related and/or can be fixed the same.  I've tried uninstalling/repairing the packages here (https://www.microsoft.com/net/core#windows) several times, with no luck.

## Steps to reproduce
1. Create New Project
![image](https://cloud.githubusercontent.com/assets/3098820/15410884/4d686734-1dea-11e6-8837-dc542fdcf8bf.png)

2. Select Empty template
![image](https://cloud.githubusercontent.com/assets/3098820/15410889/58b0af20-1dea-11e6-9230-5f565f33be39.png)

3. Get the following error message:

![image](https://cloud.githubusercontent.com/assets/3098820/15410897/627d0102-1dea-11e6-90fd-bdf51528ef52.png)

## Environment data
`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/3098820/15410936/98cb3148-1dea-11e6-9b84-14c777b7d587.png)

## Further issues

If it helps any, when I try to load a project from RC1, in the ActivityLog.xml file, I get an error loading ITelemetry or something like that.  I also get a failure file generated, which contains the following:

=====================
5/19/2016 5:24:26 PM
Recoverable
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader.<<Initialize>b__13_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader.<Initialize>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.UnconfiguredProjectImpl.AutoLoadMethodStateMachine.<<StartExecution>b__6_0>d.MoveNext()
===================

I do not get this error when creating a new project, as I've done above.

**Comment by toddlucas** [comment]
I, too, have been receiving this error. I wasn't sure where to seek help (since VS Tooling doesn't appear to be on Github), so I posted to these two locations:

https://blogs.msdn.microsoft.com/visualstudio/2016/05/16/announcing-updated-web-development-tools-for-asp-net-core-rc2/

https://connect.microsoft.com/VisualStudio/Feedback/Details/2717687

but these have received no attention. I was beginning to think my situation was unique.

I was able to get further down the road (past the 0x80070002 message box) by building the templates myself from https://github.com/aspnet/Templates (and setting $env:KOREBUILD_DOTNET_VERSION = "1.0.0-preview1-002702" beforehand). I installed the templates in the user templates location and removed them from the VS directories. 

Now I no longer get the file not found message box immediately. Instead, the templates create a partial project and I get the error that you're seeing (Microsoft.VisualStudio.ProjectSystem.DotNet.Publish.PublishLoader). The Core templates get partially instantiated--far enough along that I can replace the last remaining template parameters and get going.

**Comment by joshmouch** [comment]
I think I have a fix.

I went to the following folder:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft

And deleted the "DotNet" folder and the "Web Tools" folder.

Then I did a repair (from Programs and Features) of "Microsoft .NET Core 1.0.0 RC2 - VS 2015 Tooling Preview 1".

I'm still testing it, but I'm way further than I was able to get before.

**Comment by joshmouch** [comment]
I should also add that I added the environment variable to "opt out" of the new report-everything-that-you're-doing-to-microsoft (i.e. Telemetry) feature. :)

**Comment by toddlucas** [comment]
Yes! Thank you @joshmouch 

I copied the two directories and ran a diff after the repair. It looks like the only file that is changed in DotNet is cache.bin, so it may not be necessary to remove this directory.

My "Web Tools" directory had a large number of files in it. In particular the "Web Tools" directory had a DNX subdirectory with these two files in it:

11/15/2015  01:06 PM            16,576 Microsoft.VisualStudio.ProjectSystem.DNX.14.0.dll
11/15/2015  01:06 PM            22,720 Microsoft.VisualStudio.ProjectSystem.Wizard.dll

The older Wizard assembly appears to be a possible cause of the file not found issue.

**Comment by piotrpMSFT** [comment]
@barrytang @abpiskunov there are a number of potential tools issues here. Can you take a look, and provide guidance for tools bugs?

**Comment by joeloff** [comment]
Could you send me your installation logs (they should be in %temp%, and will all start with dd_dotnet*)

**Comment by toddlucas** [comment]
Happy to. If you could send me an email (see my profile) I'll send a zip. I'm leaving for the holiday weekend soon.

**Comment by joeloff** [comment]
@toddlucas zip will likely get rejected by mail on my end, so maybe try something like RAR. Otherwise you can just attach the zip with the logs to this issue

**Comment by toddlucas** [comment]
The zip is 42MB. I'd rather not attach since it's a log. If you send me an email I'll upload to S3 and send you a link.

**Comment by joeloff** [comment]
Sure. Just mail the link to me at joeloff at microsoft dot com

**Comment by piotrpMSFT** [comment]
Moved to appropriate repo. Closing CLI copy.
