### ISSUE TITLE
README shouldn't mention DNX

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3156]
On the topic of ASP.NET, README.md says:

> Interested in .NET Core + ASP.NET Core 1.0 RC1 bits?
> ----------------------------------------------------

> This toolchain is independent from the DNX-based .NET Core + ASP.NET Core 1.0 RC1 bits. If you are looking for .NET Core + ASP.NET Core 1.0 RC1 bits, you can find instructions on the http://get.asp.net/.  

I don't think RC1 or DNX should be mentioned anymore. Also http://get.asp.net/ is now just a redirect to https://www.microsoft.com/net.

I would send a pull request, but I'm not sure what should that section say now, if anything.

**Comment by blackdwarf** [comment]
@svick it should just be deleted, I guess. Will create the PR.

**Comment by piotrpMSFT** [comment]
@blackdwarf @svick can we get this PR done today?

**Comment by svick** [comment]
@piotrpMSFT @blackdwarf  PR created.

**Comment by blackdwarf** [comment]
@svick thanks, I was actually doing some more things to the README.md to add more stuff.
