### ISSUE TITLE
Debugger not stopping at breakpoint

### ISSUE THREAD

**Issue by ncave** [dotnet/cli#3158]
## Steps to reproduce
1. Generate new RC2 netcore project with: dotnet new --lang F#
2. Add a line before the entry point so Program.fs looks like this:

```
open System

let a = [""] // <-- if this line is removed, the debugger will attach

[<EntryPoint>]
let main argv = 
    printfn "Hello World!" // <-- put breakpoint here
    printfn "%A" argv
    0

```
## Expected  behavior

Visual Studio debugger will stop at the breakpoint.
## Actual behavior

Not stopping at breakpoint.
## Environment data

`dotnet --info` output:

```
VS2015 with Dotnet Core RC2

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@enricosada can you take a look?

**Comment by enricosada** [comment]
sure @piotrpMSFT

**Comment by ncave** [comment]
@enricosada I tried using the latest visualfsharp CI build (1.0.0-alpha-160523) to see if it will make a difference, but it does not. Still getting the same error:

![breakpoint](https://cloud.githubusercontent.com/assets/777696/15535936/41bc5452-2224-11e6-806a-aaa0fbb47ffc.png)

On a related topic, is it possible to debug with VSCode as you mentioned [here](https://github.com/ctaggart/dotnet-vscode/issues/3#issuecomment-221252209)?

**Comment by piotrpMSFT** [comment]
@enricosada putting in backlog for now. We can bring in once understood.

**Comment by livarcocc** [comment]
Just tried this out. Works with VS 2017 and 2.0 .NET Core SDK.

**Comment by ncave** [comment]
Awesome!
