### ISSUE TITLE
dotnet restore high cpu usage

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#3162]
Moving issue https://github.com/dotnet/corefx/issues/8711 on behalf of @xyting
<img width="313" alt="2016-05-20 14 43 09" src="https://cloud.githubusercontent.com/assets/14950276/15419548/44396168-1e99-11e6-97c3-1bfda94c6a8b.png">

**Comment by piotrpMSFT** [comment]
This issue belongs in nuget/home.

**Comment by piotrpMSFT** [comment]
Created nuget/home#2827
