### ISSUE TITLE
Framework-level build options not used to determine if a project is runnable

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#3164]
## Steps to reproduce

``` json
{
  "frameworks": {
    "netcoreapp1.0": {
      "buildOptions": {
        "emitEntryPoint": true
      },
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-*"
        }
      }
    },
    "netstandard1.5": {
      "dependencies": {
        "NETStandard.Library": "1.5.0-*"
      }
    }
  }
}
```

`dotnet run`
## Expected  behavior

"Hello world"
## Actual behavior

App is not runnable. `dotnet run` dies with

```
Expect required library libhostpolicy.dylib to be present in [/private/tmp/runnable/bin/Debug/netcoreapp1.0]
  - This may be because of an invalid .NET Core FX configuration in the directory.
```
## Workaround

Add a top-level build option with emitEntryPoint = true (and override in other TFMs buildOptions/emitEntryPoint = false).

``` json
{
   "buildOptions": {
      "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.0": {
      "buildOptions": {
        "emitEntryPoint": true
      },
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by patjknott** [comment]
This workaround worked for me.  I created a solution in .NET Core, Created a new project repository for classes that referenced an interface inside the original solution.  Found main causing problems, set the emitEntryPoint to false, and the  dependencyName : target: project parameters... now my solution works...

**Comment by piotrpMSFT** [comment]
This is fixed in csproj. OutputType can be conditioned on TargetFramework.
