### ISSUE TITLE
[xproj->csproj] In dotnet build/publish add support resource/satellite assemblies and CopyToOutput metadata in csproj projects

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#3166]
## Steps to reproduce

We need to add support resource/satellite assemblies and CopyToOutput metadata in csproj projects in RTW.

I gave it a shot and it seems that there is also a third scenario when users have some custom Post-Build scripts that copy some stuff to csproj bin folder without any known metadata.

So there are several approaches that we could take:

All changes actually can happen on dotnet side without tooling changes:
-   Cli build/publish looks at csproj assembly folder (it can be taken from project.fragment.lock.json file, which has path to csproj dll) and copies all files and subfolders from there to xproj output dir.
  This would and copy known CopyToOutput assets, and satellite subfolders and any custom stuff PostBuild steps deploy. Yes, there are corner cases when user deploys something outside bin folder, but we cannot do anything there and it’s up to user to re-configure.
## Environment data

`dotnet --info` output:

**Comment by abpiskunov** [comment]
Tooling changes are in progress and we need matching runtime changes for testing E2E:

Here are changes:

1.	We check UICulture of project and if it is specified we add an item under “runtime” section:

"bin/Debug/<UICulture>/ClassLibrary2.resources.dll": {
          		"outputPath": "en-US/ClassLibrary2.resources.dll"
        }

Items path is similar to what we added before – relative to csproj file path to resource assembly. Notice though that it should be copied under <xproj output path>\<UICulture>\ClassLibrray2.resources.dll  not to the root <xproj output path>. Thus tooling provides a property “outputPath” that contains relative path under <xproj output path> where file needs to be copied.

Note: “outputPath” is the name I just created, there no known property name at runtime that I could find for lock file runtime item. Please let me know if you need this property name to be changed.

2.	We check default msbuild known items collections: None, Compile, Content, EmbeddedResource and get all items with CopyToOutputDiectory metadata. For each such item we specify a runtime element:

        "bin/Debug/aaaa/class2.cs": {
          "outputPath": "aaaa/class2.cs"
        },

	Where outputPath is similar to above.
Note(!): currently runtime assumes that items there are assemblies, not random files. When I specify a *.cs file in the example , I receive a runtime error: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to make the following project runnable: ConsoleApp10 (.NETFramework,Version=v4.6) reason: Could not read assembly info for C:\Users\antonpis\Documents\Visual Studio 2015\Projects\1\GlobalJsonSources\ConsoleApp10\ClassLibrary2\bin\Debug\aaaa\class2.cs	ConsoleApp10	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets	261	

Thus we need:
o	Either change that assumption by specifying some property “isAssembly”(?) 
o	Or specify a completely different section in fragment.lock.json: copyToOutput which would contain such non-assembly assets. However based on current runtime implementation where runtime sections are just merged between lock and fragment.lock jsons it might be more difficult than adding property.

**Comment by piotrpMSFT** [comment]
@abpiskunov setting rtm milestone per your original comment. Let me know if this needs attention sooner. Focused on preview2/3 right now.

**Comment by abpiskunov** [comment]
@piotrpMSFT sorry for confusion, i meant that this should be done sooner (RTW was actually preview 2 or 3 latest). This is missing feature in xproj->csproj flow and since xproj->csproj has higher importance lately, it would be nice if someone form cli team could work on it sooner. 

Could you please assign it to some engineer, so we could finalize design and i could complete changes on tooling end until the end of the week (i will be out for whole next week)..? 

Adding @davidfowl  for design discussion too

**Comment by onovotny** [comment]
This is blocking Humanizer

**Comment by piotrpMSFT** [comment]
Closing as we have no further planned releases of xproj/project.json tooling.
