### ISSUE TITLE
Fail to install with dotnet-install.sh on rel/1.0.0

### ISSUE THREAD

**Issue by CoreyKaylor** [dotnet/cli#3169]
## Steps to reproduce
In a shell script running on ubuntu.
`curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet`

## Expected  behavior
The script will install the dotnet cli on the distribution of Linux.

## Actual behavior
While trying to install dotnet it will fail to pull down https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview1-002702/dotnet-dev-ubuntu-x64.1.0.0-preview1-002702.tar.gz

This has already worked successfully with the rc2 release, but something changed and now causes a 404.

## Environment data
https://travis-ci.org/CoreyKaylor/Lightning.NET
https://github.com/CoreyKaylor/Lightning.NET/blob/master/.travis.yml

**Comment by blackdwarf** [comment]
@CoreyKaylor can you try this instead:

```console
curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702 --install-dir ~/dotnet
```

And see if it solves the problem?

**Comment by CoreyKaylor** [comment]
That worked great, then it looks like I ran into... https://github.com/dotnet/cli/issues/1534

**Comment by CoreyKaylor** [comment]
That was easy to deal with too, just a little different than before where I was only using dnvm use ..., changed to just use dotnet test -f netcoreapp1.0 in my linux script and everything went green again.

Thanks for the help.
