### ISSUE TITLE
Readme contains invalid and outdated content

### ISSUE THREAD

**Issue by ghost** [dotnet/cli#3170]
1. https://github.com/dotnet/cli#release-schedule is stating RC2 release date etc. That ship has already sailed.:ship:  We should have a section about next milestone (RTM?) or no section at all.
2. The [Installers and Binaries](https://github.com/dotnet/cli#installers-and-binaries) and [Ubuntu Installers](https://github.com/dotnet/cli#ubuntu-installers) sections are showing preview1-002702 badges, but the URLs are pointing to latest nightly builds. The nuget badges should show the correct version number (which "latest" actually corresponds to). There should also be a link/section about the stable preview1, so we can use the script to pull it on CI machines. See #3169.
3. > [Interested in .NET Core + ASP.NET Core 1.0 RC1 bits?](https://github.com/dotnet/cli#interested-in-net-core--aspnet-core-10-rc1-bits)
   
   section is undesired. Most likely people would be interested in preview1 / RC2 bits now.

**Comment by blackdwarf** [comment]
@jasonwilliams200OK the "release schedule" thing should be there because it also explains the different versioning between the runtime/fx bits (RC2) and CLI bits (Preview 1). Maybe a different heading would be all right. 

Agreed on all others.

**Comment by jasonwilliams200OK** [comment]
>  it also explains the different versioning between the runtime/fx bits (RC2) and CLI bits (Preview 1).

Usually such differences go in the (bulleted) release notes under https://github.com/dotnet/cli/releases (for example: https://github.com/Polymer/polymer/releases and https://github.com/aspnet/KestrelHttpServer/releases). Such quick release notes can be added for github population, in addition to the MSDN blog links. :)

Then some people also keep a `CHANGELOG.md` within the repo for offline access and achieve purposes. Also this way the distributed code (for example [as a zip](https://github.com/dotnet/cli/archive/rel/1.0.0.zip)) has some notes pointing to the history of code base evolution.

**Comment by piotrpMSFT** [comment]
@jasonwilliams200OK I'm curious about (2). Where are you seeing missmatched version badge/installer links? Both branches, `rel/1.0.0` and `rel/1.0.0-preview1` appear self consistent.

As to stable links, we should be directing folks [here](https://www.microsoft.com/net/download).

@blackdwarf assigning to you so you can implement the right design here. Putting in backlog as we're not blocking release on this, but it would be great to have the readme.md up to date soon :)

**Comment by blackdwarf** [comment]
This has now been fixed. Closing.
