### ISSUE TITLE
How to create application that targets both .Net 4.6.1 and Core RC2?

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3171]
Assume that I'm trying to create a very simple ASP.NET Core RC2 application that takes advantage of a .Net Framework assembly, but can also run without it. The code would look something like this:

```c#
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;

#if NET461
using System.DirectoryServices.AccountManagement;
#endif

namespace CoreWebApplication
{
    public class Startup
    {
        public void Configure(IApplicationBuilder app)
        {
            app.Run(async context =>
            {
#if NET461
                var message = UserPrincipal.Current.ToString();
#else
                var message = "Unknown";
#endif
                await context.Response.WriteAsync(message);
            });
        }
    }
}
```

Here `System.DirectoryServices.AccountManagement.UserPrincipal` is the type from .Net Framework.

What is the right way to write project.json to make this work?

My assumption was that it would be:

```json
"dependencies": {
  "Microsoft.NETCore.App": {
    "version": "1.0.0-rc2-3002702",
    "type": "platform"
  },
  "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final"
},

"frameworks": {
  "net461": {
    "frameworkAssemblies": {
      "System.DirectoryServices.AccountManagement": "4.0.0.0"
    }
  },
  "netcoreapp1.0": {}
},
```

But this fails on `dotnet build` with:

> error NU1002: The dependency System.Runtime.Loader 4.0.0-rc2-24027 does not support framework .NETFramework,Version=v4.6.1.

What I tried next is to move the dependency on Microsoft.NETCore.App to just netcoreapp1.0:

```json
"dependencies": {
  "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final"
},

"frameworks": {
  "net461": {
    "frameworkAssemblies": {
      "System.DirectoryServices.AccountManagement": "4.0.0.0"
    }
  },
  "netcoreapp1.0": {
    "dependencies": {
      "Microsoft.NETCore.App": {
        "version": "1.0.0-rc2-3002702",
        "type": "platform"
      }
    }
  }
},
```

To my surprise, this worked, both with `dotnet run -f net 461` and `dotnet run -f netcoreapp1.0`. And now that I think about it, `Microsoft.NETCore.App` only being compatible with `netcoreapp1.0` kind of makes sense.

My questions are:

* Is this the right way to do it?
* Is it sensible to require this kind of unobvious (at least to me), undocumented (at least I didn't find any documentation on it) project.json manipulation for this?

(This question is to satisfy my curiousity, not any actual requirements. It was inspired by [this SO question](http://stackoverflow.com/q/37342840/41071))

**Comment by am11** [comment]
It seems like `Microsoft.NETCore.App` has dependency on `System.Runtime.Loader` which is only available in netcoreapp. This situation may get resolved in future, when `System.Runtime.Loader` will be added as a 'Desktop contract': dotnet/corefx#8526.

Original issue: dotnet/corefx#8453.

**Comment by piotrpMSFT** [comment]
@svick you have it right. The Microsoft.NetCore.App dependency should only exist under that `framework`. We're playing with a few design changes to make this more straightforward in the future!

**Comment by svick** [comment]
@piotrpMSFT Thanks for confirming.

**Comment by dazinator** [comment]
Can someone confirm - is this the same for `NETStandard.Library` too?

**Comment by dazinator** [comment]
I'll raise a new issue.

**Comment by mehmetilker** [comment]
Doesn't work on classic library reference.

I have MVC project with following project.json configuration.
I added one core library reference and one classic (4.6.1) library reference.
It works without calling any method in other libraries but when I add following code on HomeController/Index for example it doesn't compile anymore...

`   ClassLibrary2Classic.Class1 c = new ClassLibrary2Classic.Class1();
      ViewBag.Classic = c.Test();`

E:\WebApplication1CoreEmpty\Controllers\HomeController.cs(16,49): error CS0246: The type or namespace name 'ClassLibrary2Classic' could not be found (are you missing a using directive or an assembly reference?)


 

`{
  "dependencies": {

    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "ClassLibrary1": "1.0.0-*"

  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {

    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-rc2-3002702",
          "type": "platform"
        }
      },
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    },
    "net461": {
      "dependencies": {
        "ClassLibrary2Classic": {
          "target": "project"
        }

      }
    }

  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
`

**Comment by valcs007** [comment]
Hi,

We are trying to upgrade from RC1 to RC2 but have few issues with some ClosedXML Nuget package. we use that package for exporting to Excel and it was working with RC1. After upgrading to RC2, adding the package throws below exception.

The dependency ClosedXML doesn't support .Net Core 1.0. 

Below is the **Json** file that was generated when i launch Core template

"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final"
},

 "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  }

Any work around?

Thanks

**Comment by claudiobottari** [comment]
I'm getting crazy trying to make it work, having the same issue above. Please share a solution, if you got one.

**Comment by svick** [comment]
@valcs007 The ClosedXML package only supports .Net Framework, so you won't be able to use it on .Net Core.

**Comment by roshantarudkar** [comment]
Guys- I have similar issue but its different i am not sure whether you face the same.
 I have below entries in project.json
` "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.1",
          "type": "platform"
        },
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.0.0-preview2-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Routing": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",      
        "Microsoft.Extensions.Caching.Redis": "1.1.0"
      }
    },
    "net462": {
      "dependencies": {
        "Microsoft.Web.RedisSessionStateProvider": "2.2.2"
      }
    }
  },

`
But when i compile then it gives me compile error:

  
![error1](https://cloud.githubusercontent.com/assets/13056368/20715807/51165e5a-b61e-11e6-8061-02765fb94b36.png)

**Comment by sureshKinta** [comment]
@roshantarudkar have you solved your issue above? i am also experiencing this error and cannot find fix to it,
