### ISSUE TITLE
Improve logging for "dotnet publish"

### ISSUE THREAD

**Issue by tzwlai** [dotnet/cli#3172]
Creating this for @Maoni0:

This was one of the errors I got:

> <E:\tests\benchmark\src\CSharp\GCBenchmark\GCBenchmark>e:\tests\benchmark\runtime\dotnet publish --configuration release project.json>
> Can not find runtime target for framework 'DNXCore,Version=v5.0' compatible with one of the target runtimes: 'win81-x64, win8-x64, win7-x64'. Possible causes:
> 1. The project has not been restored or restore failed - run `dotnet restore`
> 2. The project does not list one of 'win81-x64, win8-x64, win7-x64' in the 'runtimes' section. 

Would it be possible to spell out the syntax in 2), ie:

>  The project does not list one of 'win81-x64, win8-x64, win7-x64' in the 'runtimes' section. Add the following to your project.json
>     "runtimes": {
>         "win7-x64" : {}
>     }

Maybe this is trivial for folks who are familiar with the syntax but it was not obvious to me that I should put {} as the value of win7-x64.

**Comment by blackdwarf** [comment]
This issue does not apply anymore, as the syntax is completely different in csproj world, so closing.
