### ISSUE TITLE
dotnet-test-xunit aborts after failure

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#3173]
## Steps to reproduce

Setup a test project with some _failing_ tests and some passing tests.

``` json
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [ "dnxcore50", "portable-net45+win8" ],
            "dependencies": {
                "xunit": "2.1.0",
                "dotnet-test-xunit": "1.0.0-rc2-192208-24"
            }
        }
    },

    "testRunner": "xunit",

    "runtimes": {
        "ubuntu.14.04-x64": { },
        "centos.7.1-x64": { },
        "win7-x64": { },
        "win81-x64": { },
        "win10-x64": { },
        "osx.10.11-x64": { }
    }
```

``` sh
dotnet restore
dotnet test -xml results.xml -parallel none
```
## Expected  behavior

1) The failing tests (plural) to be reported as such
2) The passing tests to be be reported as such
3) the XML report file to be created
## Actual behavior

The runner aborts with `SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.` but does not say which test(s) failed, nor does it create the requested XML report.

_Everything works as expected if all the tests pass._

Using the `-verbose` switch, it is clear that the runner executes tests, and as soon as it has executed the first failing test, it stops executing tests.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002538)

Product Information:
 Version:     1.0.0-rc2-002538
 Commit Sha:  b98bc1289d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

/cc @livarcocc

**Comment by andschwa** [comment]
Specifically this happens if the test causes an abortion. See [my example](https://github.com/andschwa/netcore-debug/blob/9f6fb65d41d940663fa7dffdfaf75f21125dff9e/Program.cs#L27).

@livarcocc and I think this means there's a bug in the isolation of tests within xUnit, and need to re-file accordingly.

**Comment by piotrpMSFT** [comment]
Can we move this to https://github.com/xunit/dotnet-test-xunit?

**Comment by yatli** [comment]
xUnit does not support process isolation, see: https://github.com/xunit/xunit/issues/1044
