### ISSUE TITLE
Support for Roslyn Analyzers

### ISSUE THREAD

**Issue by duracellko** [dotnet/cli#3175]
How can I use [Roslyn Analyzers](https://github.com/dotnet/roslyn-analyzers) with .NET Core?
## Steps to reproduce
1. Add `"Microsoft.CodeAnalysis.FxCopAnalyzers": "1.2.0-beta2"` into `dependencies` in project.json
2. Add abstract class with constructor.
3. run `dotnet build`
## Expected  behavior

Compilation warning or error CA1012
## Actual behavior

No build warnings nor errors.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by Dresel** [comment]
I also wasted some time on this issue. This information may be helpful for others to track down the problem. `Microsoft.CodeAnalysis.FxCopAnalyzers` is composed of other [nuget packages](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/1.2.0-beta2) which contain the actual analyzers. These analyzers (dependencies of FxCopAnalyzers) do not get added to the compiler options, unless added directly to the project.json.

I tried some of these analyzers directly, some of them fail with errors (e.g. `Text.Analyzers`):

    c:\users\christopher\documents\visual studio 2015\Projects\ClassLibrary\src\ClassLibrary\warning CS8032:
    An instance of analyzer Text.Analyzers.CSharpIdentifiersShouldBeSpelledCorrectlyAnalyzer cannot be created from
    C:\Users\Christopher\.nuget\packages\Text.Analyzers\1.2.0-beta2\analyzers\dotnet\cs\Text.CSharp.Analyzers.dll: 
    Could not load file or assembly 'Text.Analyzers, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
    or one of its dependencies. The system cannot find the file specified.

Others fail silently (e.g. `Microsoft.ApiDesignGuidelines.Analyzers`) and also prevent other analyzers from being executed.

**Comment by piotrpMSFT** [comment]
Using preview3 I reproduced this scenario and migrated it to csproj. I then did a `restore` and `build`. In the output I see:

```
Build succeeded.

       "/Users/piotrp/code/repro/r3175/r3175.csproj" (Build target) (1) ->
       (CoreCompile target) ->
         Program.cs(5,18): warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable [/Users/piotrp/code/repro/r3175/r3175.csproj]
         Program.cs(7,42): warning CA1801: Parameter args of method Main is never used. Remove the parameter or use it in the method body. [/Users/piotrp/code/repro/r3175/r3175.csproj]

    2 Warning(s)
    0 Error(s)
```

So analyzers are certainly active and catching issues. Furthermore, I wanted to see which analyzers got wired in. I checked the contents of obj/r3175.csproj.nuget.g.props [a props file generated by nuget and auto-included in the project] and found:

```
<Import Project="$(NuGetPackageRoot)/text.analyzers/1.2.0-beta2/build/Text.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/text.analyzers/1.2.0-beta2/build/Text.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/system.threading.tasks.analyzers/1.2.0-beta2/build/System.Threading.Tasks.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/system.threading.tasks.analyzers/1.2.0-beta2/build/System.Threading.Tasks.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/system.runtime.interopservices.analyzers/1.2.0-beta2/build/System.Runtime.InteropServices.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/system.runtime.interopservices.analyzers/1.2.0-beta2/build/System.Runtime.InteropServices.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/system.runtime.analyzers/1.2.0-beta2/build/System.Runtime.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/system.runtime.analyzers/1.2.0-beta2/build/System.Runtime.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/system.resources.analyzers/1.2.0-beta2/build/System.Resources.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/system.resources.analyzers/1.2.0-beta2/build/System.Resources.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/system.collections.immutable.analyzers/1.2.0-beta2/build/System.Collections.Immutable.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/system.collections.immutable.analyzers/1.2.0-beta2/build/System.Collections.Immutable.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/microsoft.qualityguidelines.analyzers/1.2.0-beta2/build/Microsoft.QualityGuidelines.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/microsoft.qualityguidelines.analyzers/1.2.0-beta2/build/Microsoft.QualityGuidelines.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/microsoft.net.sdk/1.0.0-alpha-20161104-2/build/Microsoft.NET.Sdk.props" Condition="Exists('$(NuGetPackageRoot)/microsoft.net.sdk/1.0.0-alpha-20161104-2/build/Microsoft.NET.Sdk.props')" />
    <Import Project="$(NuGetPackageRoot)/microsoft.maintainability.analyzers/1.2.0-beta2/build/Microsoft.Maintainability.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/microsoft.maintainability.analyzers/1.2.0-beta2/build/Microsoft.Maintainability.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/microsoft.apidesignguidelines.analyzers/1.2.0-beta2/build/Microsoft.ApiDesignGuidelines.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/microsoft.apidesignguidelines.analyzers/1.2.0-beta2/build/Microsoft.ApiDesignGuidelines.Analyzers.props')" />
    <Import Project="$(NuGetPackageRoot)/desktop.analyzers/1.2.0-beta2/build/Desktop.Analyzers.props" Condition="Exists('$(NuGetPackageRoot)/desktop.analyzers/1.2.0-beta2/build/Desktop.Analyzers.props')" />
```

You can see that all of the nupkgs, not just the top-level, are being pulled in :)
