### ISSUE TITLE
Restore fails with new preview build of CLI

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/cli#3179]
## Steps to reproduce

1. Install 2816 Preview2 build from https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/Latest/dotnet-dev-ubuntu-x64.latest.tar.gz

2. dotnet new
3. dotnet restore

## Expected  behavior
Restore should be success without any errors.

## Actual behavior
Fails with "Unable to resolve 'Microsoft.NETCore.App (1>=1.0.0.rc3-002816)' for '.NETCoreApp, Version=v1.0'

## Environment data
dotnet --version
1.0.0-preview2-002816

## Workaround
Add NuGet.Config to the project folder

https://raw.githubusercontent.com/dotnet/cli/584fdea49ee72834b02c003b48dd5d1a3a76cb28/src/dotnet/commands/dotnet-new/CSharp_Console/NuGet.Config

**Comment by blackdwarf** [comment]
@Raviuppa this is by design. Only releases end up on Nuget.org. This has been added to the [known issues document](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/known-issues.md).
