### ISSUE TITLE
Fedora 23 support

### ISSUE THREAD

**Issue by nmilosev** [dotnet/cli#3184]
While Fedora package isn't officially available yet (see #2958), you can run the CentOS binaries pretty easily today on latest versions of Fedora as described here (my blog):

https://nmilosev.svbtle.com/running-net-core-rc2-on-fedora-23

I've tested a few examples from the examples repo and all are working.

Cheers.

**Comment by AerisG222** [comment]
Thanks @nmilosev, this was very helpful!  I am now able to run my rc2 aspnet site on FC23 w/o having to jump into an ubu vm - nice!

I did run into an error about missing libhostpolicy.so when trying to run an xunit test, but I can always jump back to ubu for that when needed.

**Comment by nmilosev** [comment]
Glad it worked out for you! About the ```libhostpolicy.so```, I believe that's a library in the ```dotnet``` package and maybe it is missing from the CentOS package. Nevertheless you can copy it from your VM to the ```lib64``` folder or to ```~/dotnet/shared/Microsoft.NETCore.App/1.0.0-rc2-3002702/``` and try to see if it works after that.

Cheers!

**Comment by piotrpMSFT** [comment]
Thanks @nmilosev! I'm going to close the issue since there is not action to take here, but I'm sure folks will be glad to find it when searching :)

/cc @livarcocc

**Comment by nmilosev** [comment]
Sure, @piotrpMSFT that was the idea. Glad I can help and thank you guys for everything. :)

I've done some more testing with Fedora, and everything seems to be working perfectly. 

Cheers!
