### ISSUE TITLE
dotnet build erros for .cs files in node_modules folder?

### ISSUE THREAD

**Issue by asadsahi** [dotnet/cli#3190]
## Steps to reproduce
install a node module folder which has some .cs files in it, e.g selenium webdriver has some aspx pages with their code behind.

## Expected  behavior
dotnet build should only compile the project c sharp files

## Actual behavior
error during build:
![image](https://cloud.githubusercontent.com/assets/3470892/15456186/866cbcce-2060-11e6-9946-5028fd43c853.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14295
 OS Platform: Windows
 RID:         win10-x64

**Comment by ayydevara** [comment]
Same error for me as well. Any update on this one?

**Comment by asadsahi** [comment]
It works by removing two files from the error location (Page.aspx and Redirect.aspx with their respective c# files), but this is just a work around. 

There is an option in project.json file:
`  "compileExclude": "node_modules/**",`
.. this excludes the folder, but compileExclude seems deprecated as per compilation message when you run `dotnet run`

`

> .....project.json(81,38): warning DOTNET1015: The 'compileExclude' option is deprecated. Use 'compile' in 'buildOptions' instead.


`

I have added this as per message suggests:

```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "debugType": "portable",
    "compile": "**/*.cs"
  },
```

But I am wondering if this is standard way to compile and whitelist the files manually. Is there a performance implication of this?

**Comment by ayydevara** [comment]
@asadsahi I did this and it worked fine

	 "buildOptions": {
	    "emitEntryPoint": true,
	    "preserveCompilationContext": true,
	    "debugType": "portable",
	    "compile": {
	    	"include" : ["**/*.cs"]
	    	"exclude" : ["**/node_modules/"]
	      }
	  },

**Comment by ayydevara** [comment]
@asadsahi I think I should try just exclude instead of include all cs files.

**Comment by asadsahi** [comment]
Makes sense @ayydevara . Blacklisting using exclude sounds good to me too instead of whitelisting files. Thanks
