### ISSUE TITLE
dotnet restore fails to resolve local dependencies with a certain folder structure

### ISSUE THREAD

**Issue by golf1052** [dotnet/cli#3192]
## Steps to reproduce
1. Create folder `testlib` and `testapp` under the same directory
2. Inside testlib run `dotnet new`
3. Inside project.json change the frameworks from `netcoreapp1.0` to `netstandard1.5`
4. Create folder `src` inside testlib
5. Move Program.cs and project.json inside src
6. Create global.json (not inside src) with contents

    ```json
    {
        "projects": ["src"]
    }
    ```

7. Inside testlib run `dotnet restore`
8. Inside testlib/src run `dotnet build`
9. Now inside testapp run `dotnet new`
10. Create global.json with contents

    ```json
    {
        "projects": [".", "../testlib"]
    }
    ```

11. Inside project.json add testlib as a dependency

    ```json
    "testlib": {
      "target": "project",
      "version": "1.0.0"
    }
    ```

12. Now run `dotnet restore`

Directory structure should look like
```
testlib
  global.json
  /src
    /bin
    /obj
    Program.cs
    project.json
    project.lock.json
testapp
  global.json
  Program.cs
  project.json
```

This also might be related to #3183
## Expected behavior
`dotnet restore` restores dependencies including the local project testlib

## Actual behavior
`dotnet restore` is unable to resolve the local dependecty `testlib`
Example output
```
C:\Users\Sanders\testapp
#! dotnet restore
log  : Restoring packages for C:\Users\Sanders\testapp\project.json...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
error: Unable to resolve 'testlib (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\Sanders\testapp\project.lock.json
log  : C:\Users\Sanders\testapp\project.json
log  : Restore failed in 656ms.

Errors in C:\Users\Sanders\testapp\project.json
    Unable to resolve 'testlib (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

NuGet Config files used:
    C:\Users\Sanders\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14342
 OS Platform: Windows
 RID:         win10-x64
```

## Workaround steps
1. Inside testlib rename src folder to testlib
2. Inside global.json change "src" to "testlib" (this step doesn't seem to matter as dotnet restore seems to ignore global.json)
3. Inside testapp create folder `src`
4. Move project.json and Program.cs inside src
5. Run `dotnet restore`
6. `dotnet restore` can now find and restore testlib

**Comment by blackdwarf** [comment]
I have seen this as well. @emgarten is this by design behavior?

**Comment by emgarten** [comment]
This is expected, global.json needs to be in a parent folder.

**Comment by golf1052** [comment]
I tried poking around for documentation on global.json and I found [this](http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html#structuring-a-solution). Based upon above this doesn't work when referencing local projects. I know everything is in flux right now and is pending change but what would be the best reference to look at for local project references?

**Comment by blackdwarf** [comment]
@golf1052 yes though we have a document in works on the same site that is a reference for `global.json` files: http://dotnet.github.io/docs/project-model/global-json-reference.html.

**Comment by piotrpMSFT** [comment]
@golf1052 for project-to-project references to work the projects must be in the domain of a single global.json. It is the global.json that describes where peer projects can be found. Please restructure your projects like this:

```

global.json
/src
  /testlib
    ~~global.json~~
    /bin
    /obj
    Program.cs
    project.json
    project.lock.json
  /testapp
    ~~global.json~~
    Program.cs
    project.json
```

**Comment by skorunka** [comment]
What "~~global.json~~" means?
