### ISSUE TITLE
Publish not working for self contained app? (rc2)

### ISSUE THREAD

**Issue by xoofx** [dotnet/cli#3193]
## Steps to reproduce
- Create a "Console Application (.NET Core)" from Visual Studio
- Add a runtime "win10-x64" as specified in the documentation [app-types](https://github.com/dotnet/core-docs/blob/master/docs/core-concepts/app-types.md)
- run `dotnet publish --configuration Release --runtime win10-x64`

Final content of the `project.json`:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win10-x64": { }
  }
}
```

## Expected  behavior
The full runtime, dotnet.exe... in the publish folder.

## Actual behavior
There is just there the DLL of the main, but no runtime and exe

![dotnet-cli-pubish](https://cloud.githubusercontent.com/assets/715038/15457928/0e5a28c0-20ce-11e6-8341-0874a7511722.png)

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by xoofx** [comment]
Oops, missed that important part in the doc :sweat_smile: 

> The first is to remove any "type": "platform"

So this `project.json` will generate a proper self contained app:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win10-x64": { }
  }
}
```

**Comment by GuardRex** [comment]
@xoofx fyi the last advice I had from @ericstj on the `win10-x64` RID was that it should be used for UWP apps only at this time. He recommended `win81-x64` for WS2012+. That may have changed in the last few weeks, but he'll let us know if it has. cc/ @blackdwarf

**Comment by xoofx** [comment]
@GuardRex thanks! Is the win7-x64 working as well? (as I would better target this one actually)

**Comment by GuardRex** [comment]
@xoofx Yes, they are forward compat, so you can use `win7-x64` on forward platforms from Win7+ and IIS 7.5+, while `win81-x64` would be Win81+ and IIS 8.5+.

@ericstj will probably tell us if the prior advice holds regarding `win10-x64`, and @blackdwarf might want to change that doc if it makes more sense to make it say either `win7-x64` or `win81-x64`.

I am a little concerned about devs seeing `win10-x64` in various spots and thinking, 'Well ... that would be Win10+ and IIS 10+.' ... and start using it for web apps on WS2016/Nano, where perhaps it really should be `win81-x64`.

**Comment by ericstj** [comment]
The only reason not to use win10-x64 was due to an issue with the CLRCompression package.  @ianhays was working on that.  I believe that is still not fixed in the latest packages so you should avoid using win10 until that is fixed.  https://github.com/dotnet/corefx/issues/7436
