### ISSUE TITLE
How to reference NuGet packages depending on full .net framework from core project?

### ISSUE THREAD

**Issue by PeterJakubik** [dotnet/cli#3196]
Hi
I'm using RC2 and my app depends on other Nugets (NPOI, NLog) that require full .net framework.
What is the best way to reference those Nugets?
Right now I have project.json:
```
"dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    .....
   "NPOI": "2.1.3.1"
  },
   "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "dnx451",
        "portable-net45+win8"
      ]
    }
  }
```

Is it needed to reference the 'portable-net45+win8' together with 'dnx451' ?
Should the frameworks section mention only ''dnx451' like this?
```
 "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "dnx451",
        "portable-net45+win8"
      ]
    }
```

Thank you
Peter

**Comment by am11** [comment]
NLog supports .NET Platform (Core RC2): https://www.nuget.org/packages/NLog/4.4.0-beta8. We can use it like this:

```json
{
  "dependencies": {
    "NLog": "4.4.0-*"
  },
  "frameworks": {
    "netcoreapp1.0": { }
  }
}
```

*(there is also NLog extension package for ASPNET Logging abstraction: https://github.com/aspnet/Logging -- {readme links to} --> https://github.com/NLog/NLog.Extensions.Logging -- {readme links to} --> https://www.nuget.org/packages/NLog.Extensions.Logging)*

For NPOI (or in general, packages which are not yet supporting .NET Core), we can simply use just portable profile: `"imports": ["portable-net45+win8"]` under netcoreapp1.0/netstandard1.x TFMs. But this approach is probably just a convenience to unblock people and does not actually guarantee that the application would work cross platform. We will also need to reference all the nested dependencies of NPOI in our project.json.

I think the vetted approach (which guarantees cross-platform'ness) is that, for example if we are targeting frameworks in our app, we can specify those unsupported dependencies as framework-specific deps:

```json
{
  "dependencies": {
    "NLog": "4.4.0-*"
  },
  "frameworks": {
    "netcoreapp1.0": { },
    "net452": {
      "dependencies": {
        "NPOI": "2.1.3.1"
      }
    }
  }
}
```

Then in the code, we can opt-out of those non-crossplat-supported features using preprocessor directives:

```c#
using System;
#if !NETCOREAPP1_0 // for app or use #if NETSTANDARD1_3 for library
                   // (if the app is targeting netstandard1.3 TFM)
using NPOI.HSSF.UserModel;
#else 
/*
  #else block is optional: here use some alternative library if available?
  otherwise disable everything related to this feature in the rest of the code.
  Or in case the project is library (to be consumed by outsiders), throw
  PlatformNotSupportedException in case of #if NETCOREAPP1_0 etc. from
  the methods (this is what CoreFX libraries are doing for non-cross-plat features)
*/
#endif
```

**Comment by PeterJakubik** [comment]
I came up with following project.json

```javascript
"frameworks": {
    "net451": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "NPOI": "2.1.3.1"
      }
    }
},
```

But this gives me a lot of errors Package System.XY is not compatible with net451 (.NETFramework,Version=v4.5.1)

But when i remove `"Microsoft.NETCore.App"` from dependencies everything compiles and works.

Is this a right way to compile with full Framework?

Thanks
Peter
[project.json.txt](https://github.com/dotnet/cli/files/281909/project.json.txt)

**Comment by am11** [comment]
In full framework, `imports` is usually not required. If the app is targeting `netcoreapp1.0`, there `imports` can be specified for dependencies like NPOI.

> remove `"Microsoft.NETCore.App"`  from dependencies

Yes, removing for net4x is the way to go:  `Microsoft.NETCore.App` is not [yet](https://github.com/dotnet/corefx/issues/8453) supported with full framework. It can be put under `netcoreapp1.0` (if the app is targeting that TFM).
