### ISSUE TITLE
Update Json.NET

### ISSUE THREAD

**Issue by JamesNK** [dotnet/cli#3198]
https://www.nuget.org/packages/Newtonsoft.Json/8.0.4-beta1

Targets netstandard1.0 - no more imports!

**Comment by mikes-gh** [comment]
Your work is much appreciated @JamesNK .

> no more imports!

This is great news.  I guess MS wont touch all their repos until you go 8.0.4 (final) though.  It would be great if you can go 8.0.4 (final) before aspnetcore RTM.

**Comment by Eilon** [comment]
@JamesNK we discussed this today with @leecow @gkhanna79 @davidfowl @danroth27 and we will need to chat with you about how to make this happen cleanly. We'll have to time things with you to ensure we can build on top of each other's RTM-quality packages.

**Comment by piotrpMSFT** [comment]
@Eilon I'm going to close this issue. Once we have RTM packages let's open a new one and CLI will get updated :)

**Comment by mikes-gh** [comment]
@piotrpMSFT This is very disappointing.  Can you not coordinate with @JamesNK  to get 8.0.4 for RTM.
There are some project.json level imports in the tooling for example that really need to vanish to improve the usability of asp.net core.

**Comment by Eilon** [comment]
@mikes-gh yes we are updating to 8.0.4 rtm, don't worry! It's just a bit of a balancing act to make it happen 😄

**Comment by mikes-gh** [comment]
@Eilon
https://github.com/aspnet/EntityFramework/pull/5564/commits/f93b04e2a0785f82fa4788e835421fd5abbf5d0e
We don't want JSON serializing logic leaking into all the packages do we.  That's a bit of a code smell.
