### ISSUE TITLE
"The given key was not present in the dictionary." on dotnet pack

### ISSUE THREAD

**Issue by 0xdeafcafe** [dotnet/cli#3200]
## Steps to reproduce
Run the command `dotnet pack` in the directory that contains the project.json

## Expected  behavior
Create as nuget package.

## Actual behavior
Throws the following error `The given key was not present in the dictionary.`

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14342
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by 0xdeafcafe** [comment]
So I ran `dotnet restore`, and it worked. Maybe it should say this to the user?

**Comment by GuardRex** [comment]
@0xdeafcafe Probably going to need more to go on than that. Can you provide the `project.json` for the project? [However, that does suck as a general exception, since it doesn't tell one what key is missing.]

**Comment by GuardRex** [comment]
Oh ... there is an open issue on that. I'll see if I can track it down.

**Comment by GuardRex** [comment]
https://github.com/dotnet/cli/issues/2504

**Comment by blackdwarf** [comment]
@0xdeafcafe can we close this as a dupe of #2504?

**Comment by 0xdeafcafe** [comment]
Ah awesome, I had a quick look but I guess I wasn't thorough enough. Closing.
