### ISSUE TITLE
Multi-trageting basic class library with VS2015

### ISSUE THREAD

**Issue by gzak** [dotnet/cli#3206]
I have a very barebones class library, and here's its project.json file (it's just a data model with very basic types and so doesn't need any other dependencies):

```
{
  "version": "1.1.0-beta2",
  "description": "My.Models",
  "authors": [ "asdf" ],

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```

I also have a separate solution with a traditional csproj project inside targeting .net 451 (framework assemblies), and when I add a dependency on the `My.Models` package in the csproj I get the following error:

```
Attempting to resolve dependency 'NETStandard.Library (≥ 1.5.0-rc2-24027)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
```

What am I doing wrong here? `My.Models` is as basic a class library as it gets...

**Comment by davidfowl** [comment]
What version of the NuGet client and visual studio are you using?

**Comment by gzak** [comment]
The wrong one, my bad. It was an older 2013 csproj and I forgot to open it with VS2015 (out of habit).

Now I get a different issue, but I think it's because the package targets netstandard1.5, but needs to target at most netstandard1.2 to be compatible with .net 451 according to [this](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms). Is that right?

**Comment by gzak** [comment]
Nope, downgrading didn't fix the issue. Here's the error I get in the Description column of the Error List window:
```
Could not install package 'Microsoft.NETCore.Targets 1.0.1-rc2-24027'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```
I'm using the following versions of software:
VS2015: 14.0.25123.00 Update 2
NuGet Package Manager (VS Extension): 3.4.3.

The package was created on the command line using the `dotnet` command, version 1.0.0-preview1-002702

**Comment by gzak** [comment]
@davidfowl any ideas? I'm sort of stuck...

**Comment by davidfowl** [comment]
I'd file an issue on https://github.com/dotnet/corefx. Looks like NETStandard.Library is broken on packages.config based projects.

**Comment by piotrpMSFT** [comment]
This got moved to https://github.com/dotnet/corefx/issues/8991
