### ISSUE TITLE
Update the JITPath to use the separate package when we move to a new version of the netcore packages

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#3209]
When we moved to the RC3 packages, crossgen now expected to the passed the path to the CoreJIT dll.

The packages of the coreclr that we moved to had this dll in the same package as the coreclr, so I used that to figure out the path.

Newer packages will have the core clr jit dll in a separate package, so we will have to updated the code that calculates this path.

The code is located here: https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/shared-build-targets-utils/Utils/Crossgen.cs.

**Comment by brthor** [comment]
@livarcocc What version of CoreCLR has the JITPath in a different package? When will we be taking it?

**Comment by livarcocc** [comment]
Chat with @schellap

**Comment by eerhardt** [comment]
This is now fixed.  See https://github.com/dotnet/cli/pull/3425/commits/82ef0304bb2289f36a18c718b3e9f07d01992115.

Closing.
