### ISSUE TITLE
dotnet core can not ouput Non-English  characters  correctly

### ISSUE THREAD

**Issue by John0King** [dotnet/cli#3210]
## Steps to reproduce
1 . create a console application with this code  
```C#
public static void Main(string[] args)
        {
            Console.OutputEncoding = System.Text.Encoding.UTF8;
            Console.Write("当前路径");
        }
```
2 . run this application!

## Expected  behavior
ouput four chinese characters with enough letter-space ( 8 english letter width )
## Actual behavior
ouput four chinese characters  but with only 4 english letter width
![dotnet](https://cloud.githubusercontent.com/assets/13639146/15490690/fa19317e-219c-11e6-9109-d9cb104b86f0.png)

## Environment data
`dotnet --info` output:
dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by 717009629** [comment]
[http://www.cnblogs.com/artech/p/encoding-registeration-4-net-core.html](http://www.cnblogs.com/artech/p/encoding-registeration-4-net-core.html)
`            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Console.WriteLine("你好");`
"System.Text.Encoding.CodePages": "4.0.1-rc2-24027"

**Comment by John0King** [comment]
@717009629. 这不是我遇到的问题，你看截图，汉字并不是乱码，而是叠在了一起。

**Comment by 717009629** [comment]
cmd 属性 改下字体试试
