### ISSUE TITLE
Project build system support for ref assemblies (PCL bait-and-switch)

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#3211]
## Steps to reproduce

You want to create a bait-and-switch NuGet package by specifying a build for the `ref` folder instead of the `lib` folder.

## Expected  behavior

A way to specify in the csproj/xproj/project.json that the build output is packaged to the `ref`, instead of the `lib` folder.

## Actual behavior

No way to include it except by using `packInclude` (or similar means).

**Comment by davidfowl** [comment]
We're not going to be doing features like this as we're eventually moving to msbuild based projects. This kinda of feature has far reaching impact of things like tooling, nuget, intellisense, etc.

**Comment by fubar-coder** [comment]
That's why I wrote: "Project build system", not explicitly project.json. There should be a way to do this kind of stuff with msbuild based projects.

**Comment by davidfowl** [comment]
+1000 😄

**Comment by blackdwarf** [comment]
@fubar-coder this should then go into https://github.com/dotnet/roslyn-project-system, since it seems like a much better place for this kind of issue. Can you move it there please and close this one? Thanks!

**Comment by fubar-coder** [comment]
Created a new issue [dotnet/roslyn-project-system#317](https://github.com/dotnet/roslyn-project-system/issues/317).
