### ISSUE TITLE
What is the alternative to DNX_TRACE in dotnet cli?

### ISSUE THREAD

**Issue by guylando** [dotnet/cli#3212]
I always used DNX_TRACE environment variable in dnx asp.net projects.
I can't find information on what is the alternative in dotnet cli for DNX_TRACE?
Also, is there some page which lists all the available environment variables in dotnet cli and their purpose?
Thanks a lot!

**Comment by vcsjones** [comment]
`COREHOST_TRACE` appears to be the replacement of `DNX_TRACE`.

**Comment by guylando** [comment]
Thanks!
