### ISSUE TITLE
Re-enable Kestrel.Tests

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3216]
In order to get on the RC3 builds of CoreFX, we needed to disable the Kestrel.Tests. This is because they were built on ASP.NET RC2, which isn't compatible with CoreFX RC3 assemblies.

We should re-enable the Kestrel.Tests when we get an ASP.NET RC3 build.

**Comment by piotrpMSFT** [comment]
is there a related ASP.NET issue?

**Comment by eerhardt** [comment]
> is there a related ASP.NET issue?

Not an exact one that I know of. We just need a build of Kestrel that is on RC3 of corefx. @pranavkm is working on that right now.

**Comment by livarcocc** [comment]
@eerhardt @pranavkm Do we have this new kestrel build now? It would be nice to re-activate these tests.

**Comment by eerhardt** [comment]
Yes - this has been on my list all day. When I get time I will re-enable them.

**Comment by eerhardt** [comment]
This test has been deleted.  Closing.
