### ISSUE TITLE
Class library compilation fail when targeting netstandard 1.3 with imports net45 reference

### ISSUE THREAD

**Issue by pherbel** [dotnet/cli#3218]
I don't know what I'm doing wrong. 

## Steps to reproduce

Create class librarary with Microsoft.Azure.DocumentDb nuget reference
add build target .netstandard 1.3

  "dependencies": {
    "Microsoft.Azure.DocumentDB": "1.6.3",
    "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc2-final",
    "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-final"
  },
  "frameworks": {
    "net451": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027"
      }
    },
    "netstandard1.3": {
      "dependencies": {
        "NETStandard.Library": {
          "type": "build",
          "version": "1.5.0-rc2-24027"
        },
        "Microsoft.CSharp": "4.0.1-rc2-24027",
        "System.Collections": "4.0.11-rc2-24027",
        "System.Diagnostics.Debug": "4.0.11-rc2-24027",
        "System.Dynamic.Runtime": "4.0.11-rc2-24027",
        "System.Globalization": "4.0.11-rc2-24027",
        "System.IO": "4.1.0-rc2-24027",
        "System.Linq": "4.1.0-rc2-24027",
        "System.Linq.Expressions": "4.0.11-rc2-24027",
        "System.ObjectModel": "4.0.12-rc2-24027",
        "System.Reflection": "4.1.0-rc2-24027",
        "System.Reflection.Extensions": "4.0.1-rc2-24027",
        "System.Resources.ResourceManager": "4.0.1-rc2-24027",
        "System.Runtime": "4.1.0-rc2-24027",
        "System.Runtime.Extensions": "4.1.0-rc2-24027",
        "System.Runtime.Serialization.Primitives": "4.1.1-rc2-24027",
        "System.Text.Encoding": "4.0.11-rc2-24027",
        "System.Text.Encoding.Extensions": "4.0.11-rc2-24027",
        "System.Text.RegularExpressions": "4.0.12-rc2-24027",
        "System.Threading": "4.0.11-rc2-24027",
        "System.Threading.Tasks": "4.0.11-rc2-24027",
        "System.Xml.ReaderWriter": "4.0.11-rc2-24027",
        "System.Xml.XDocument": "4.0.11-rc2-24027"
      },
      "imports": [ "net45" ]
    }

I

## Expected  behavior

complilation without errors like net451 target

## Actual behavior

Build break with this errors:
Error	CS0012	The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by pherbel** [comment]
Any help?

**Comment by piotrpMSFT** [comment]
Can you provide a complete project.json?

**Comment by piotrpMSFT** [comment]
I'm also curious about the scenario. Why add imports net45 to a netstandard target? If the dependencies are not available for netstandard and are not portable, what is the purpose?

**Comment by davidfowl** [comment]
You can;t import net45, that's broken. Imports are powerful but also very hard to get right.

**Comment by pherbel** [comment]
project.json
{
  "version": "1.0.0-*",
  "description": "DocumentDbUtils Class Library",
  "authors": [ "PeterHerbel" ],
  "packOptions": {
    "tags": [ "documentdb" ],
    "projectUrl": "",
    "licenseUrl": ""
  },
  "dependencies": {
    "Microsoft.Azure.DocumentDB": "1.6.3",
    "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc2-final",
    "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc2-final"
  },
  "frameworks": {
    "net451": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027"
      }
    },

    "netstandard1.3": {
      "dependencies": {
        "NETStandard.Library": {
          "type": "build",
          "version": "1.5.0-rc2-24027"
        },
        "Microsoft.CSharp": "4.0.1-rc2-24027",
        "System.Collections": "4.0.11-rc2-24027",
        "System.Diagnostics.Debug": "4.0.11-rc2-24027",
        "System.Dynamic.Runtime": "4.0.11-rc2-24027",
        "System.Globalization": "4.0.11-rc2-24027",
        "System.IO": "4.1.0-rc2-24027",
        "System.Linq": "4.1.0-rc2-24027",
        "System.Linq.Expressions": "4.0.11-rc2-24027",
        "System.ObjectModel": "4.0.12-rc2-24027",
        "System.Reflection": "4.1.0-rc2-24027",
        "System.Reflection.Extensions": "4.0.1-rc2-24027",
        "System.Resources.ResourceManager": "4.0.1-rc2-24027",
        "System.Runtime": "4.1.0-rc2-24027",
        "System.Runtime.Extensions": "4.1.0-rc2-24027",
        "System.Runtime.Serialization.Primitives": "4.1.1-rc2-24027",
        "System.Text.Encoding": "4.0.11-rc2-24027",
        "System.Text.Encoding.Extensions": "4.0.11-rc2-24027",
        "System.Text.RegularExpressions": "4.0.12-rc2-24027",
        "System.Threading": "4.0.11-rc2-24027",
        "System.Threading.Tasks": "4.0.11-rc2-24027",
        "System.Xml.ReaderWriter": "4.0.11-rc2-24027",
        "System.Xml.XDocument": "4.0.11-rc2-24027"
      },
      "imports": [ "net45" ]
    }

  },
  "buildOptions": {
    "embed": [ "StoredProcedures/*.js", "Triggers/*.js" ]
  }
}

**Comment by pherbel** [comment]
@davidfowl @piotrpMSFT 
I just wanted to create my library target to net451 and netstandard and will remove the import net45 if the Azure team provide a netstandard compatible library.
It seemed to me it can work, but I can live only with net451 target until the netstandard lib come.

Is there any public information about Azure team schedule? When do we expect the netstandard compatible SDK?
storage, documentdb and webjob are the most important for us

**Comment by davidfowl** [comment]
The storage SDK now properly supports netstandard.

> Is there any public information about Azure team schedule? When do we expect the netstandard compatible SDK?

Not sure. I'll see what I can find out.

**Comment by pherbel** [comment]
We can close this.
Please share if you have any info about Azure SDK support. 

Thanks
