### ISSUE TITLE
Project model server doesn't update packages' statues after they're restored from missing file statues.

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#3220]
## Steps to reproduce
1. Create a new project in VS, restore, save and close the project.
2. Remove `.nuget/packages` folder
3. Open the project in VS. Missing dependencies are detected and restore is started.
4. Restore finished.

## Expected  behavior
No error.

## Actual behavior
Errors' from the step 3 are not removed even though packages are restored. This is because the package description's resolved field is not reset.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L59

## Environment data
`dotnet --info` output:

**Comment by troydai** [comment]
The root is the issue is that the project model server refresh the project model only after lock files or project files are updated. In this scenario, the lock file is not updated because the dependency graph is not actually updated.

The easiest approach to fix this issue is to touch the lock file after restore to update the "last update time". /cc @piotrpMSFT

**Comment by troydai** [comment]
@piotrpMSFT just pointed out that touch lock file after restore will break the incremental build scenario. So that leaves us following choices.

1. Major changes to [how `DesignTimeWorkspace` invalid the project](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/ProjectContextCollection.cs#L36). To track the changes of resolved path existence flip. The size of the change will be M to L.
2. Add a new request to project model server to allow force refresh all dependencies;
3. Make project model server dispose all cache for every `RestoreComplete` request.

**Comment by abpiskunov** [comment]
I like option 3. since from tooling side if we add new request type to PMS , it would be called at the same time as RestoreComplete, so they would not be different actually.

**Comment by piotrpMSFT** [comment]
Seems reasonable. @troydai is there a scenario where we would not want to dispose the cache on RestoreComplete?

**Comment by piotrpMSFT** [comment]
@troydai can you associate a milestone with this issue?

**Comment by troydai** [comment]
I can't think of one.

**Comment by troydai** [comment]
Fixed in 0d470ecea0ab58aa7d9e74e70777beff51dc3414
