### ISSUE TITLE
How to consume mixed mode/native library in asp.net core? while targeting net461

### ISSUE THREAD

**Issue by leo9223** [dotnet/cli#3233]
## Steps to reproduce

1. Here is the package I have made with a native library that is publicly available https://www.nuget.org/packages/SmileNet/

2. Please make an asp.net core project and target **net461** in project.json

3. Install this package from nuget

4. Try to consume by creating an object of type `Network obj = new Network();` 

## Expected  behavior
It should successfully create an object of type `Network`

## Actual behavior
It gives an error at runtime "Could not load file or assembly"

**Comment by davidfowl** [comment]
NuGet packages with native assets have a very specific layout in NuGet v3 (the one we're rely on). You'll need to re-package to support the new layout. If you want to see examples, take a look at https://www.nuget.org/packages/Libuv/1.9.0-rc2-20896 or https://www.nuget.org/packages/Microsoft.Data.SQLite/1.0.0-rc2-final. 

You'll need this:
http://dotnet.github.io/docs/core-concepts/rid-catalog.html

Also read this:
http://www.natemcmaster.com/blog/2016/05/19/nuget3-rid-graph/

**Comment by piotrpMSFT** [comment]
Thanks @davidfowl!
