### ISSUE TITLE
resx files in sub-folders causes 'MissingManifestResourceException'

### ISSUE THREAD

**Issue by stefan505** [dotnet/cli#3234]
## Steps to reproduce
1. Create a new .NET Core console app targeting `net451` only.
2. Create a new .NET Core class lib targeting `net451` only and reference it in the app.
3. Add folder in the class lib.
4. Add resource file to the folder e.g. `Resource.resx`.
5. Add another resource file to the folder e.g. `Resource.af-ZA.resx`.
6. Add corresponding resource key and value to both resx files.
7. Run the console app, extract of `Main(..)`:
```
Console.WriteLine(Resource.test);

Thread.CurrentThread.CurrentCulture = new CultureInfo("af-ZA");
Thread.CurrentThread.CurrentUICulture = new CultureInfo("af-ZA");

Console.WriteLine(Resource.test);
```
## Expected  behavior
Should print:
```
This is English.
Dit is Afrikaans.
```

## Actual behavior
Got exception:
```
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

# **Note:**
If I move the resx files out of the folder into the root of the project, it works.

**Comment by buzhansky** [comment]
There are problem in generation *.Designer.cs file 
 internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Global.Resources", typeof(Global_Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
If you enter correct namespace with child folder in ""Test.Global.Resources"". 
Everything will works.

**Comment by Xottab-DUTY** [comment]
How to fix this with C++/CLI?
