### ISSUE TITLE
dotnet restore - TeamCity

### ISSUE THREAD

**Issue by CezaryRynkowski** [dotnet/cli#3237]
I have a issue with deploying by TeamCity. When i run C:\Program Files\dotnet\dotnet.exe restore from cmd its going greate, but when i running the same command from TeamCity Agent i getting error:
error: TODO: unknown keyword platform
unknown keyword platform

## Steps to reproduce
Create new project -> dotnet new 
Create new TM project, install .net core plugin from [here](https://github.com/JetBrains/teamcity-dotnet-plugin)
Add build step -> .NET Core (dotnet) restore with no params
Add build step -> dotnet build
## Expected  behavior
Restore packages and create project.json.lock

## Actual behavior
logs:

`
[16:11:39]Step 4/9: Restore packages (.NET Core (dotnet)) (1s)
[16:11:39][Step 4/9] Starting: "C:\Program Files\dotnet\bin\dotnet.exe" restore
[16:11:39][Step 4/9] in directory: C:\TeamCity\buildAgent\work\88e6320ce01d3424
[16:11:40][Step 4/9] error: TODO: unknown keyword platform
[16:11:40][Step 4/9] log  : Restoring packages for C:\TeamCity\buildAgent\work\88e6320ce01d3424\wrap\Collab.Tools\project.json...
[16:11:40][Step 4/9] unknown keyword platform
[16:11:40][Step 4/9] Process exited with code -1
[16:11:40][Step 4/9] Step Restore packages (.NET Core (dotnet)) failed
`
## Environment data
`dotnet -version` output:
1.0.0-preview1-002702

**Comment by blackdwarf** [comment]
@CezaryRynkowski hmm, seems like the plugin is trying to invoke an old version of the dotnet tool. You can see it in the log, since it is trying to invoke `C:\Program Files\dotnet\bin\dotnet.exe` instead of `C:\Program Files\dotnet\dotnet.exe`.

**Comment by piotrpMSFT** [comment]
@CezaryRynkowski take a look at this [doc](http://dotnet.github.io/docs/core-concepts/core-sdk/cli/using-ci-with-cli.html). For CI scenarios we strongly recommend using the dotnet-install scripts so you have total control over the Cli you are using. Just invoke the appropriate script early in your build, either .sh or .ps1. The script will download and PATH the CLI version you expect regardless of what is installed machine wide. This is great for managing your tools dependencies in shared environments!

`dotnet-install --version 1.0.0-preview1-002702 --channel Beta`

If this does not work please let us know. The CI scenario is very important!
