### ISSUE TITLE
project.lock.json file name case

### ISSUE THREAD

**Issue by zygimantas** [dotnet/cli#3238]
"dotnet restore" should take account into how project.json is named and generate project.lock.json accordingly. I personally use Pascal case naming convention for files.

## Steps to reproduce

1. Create file Project.json
2. Execute "dotnet restore"

## Expected  behavior

**P**roject.lock.json

## Actual behavior

**p**roject.lock.json

## Environment data

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@emgarten @yishaigalatzer thoughts on this?

**Comment by yishaigalatzer** [comment]
I disagree, the casing should be predictable (lower case) and no extra magic should be added, and on UNIX we shouldn't support Project.json

**Comment by akoeplinger** [comment]
I agree with @yishaigalatzer, I ran into a similar issue before because of project.json casing: https://github.com/dotnet/cli/issues/561

**Comment by blackdwarf** [comment]
+1 on that. Mixing cases is not good.

**Comment by yishaigalatzer** [comment]
The only thing we will need to support going forward is projectname.project.json and the equivalent lock file, there we should just follow the project casing verbatim

**Comment by blackdwarf** [comment]
@yishaigalatzer what is this?

**Comment by yishaigalatzer** [comment]
The ability to have more than one csproj file in a folder, and a matching project.json connected to it. This might all change depending on how we design the msbuild based integration.

Imho we shouldn't do any improvements of this nature at this point until we lock the msbuild based design. E.g. this file will probably change both its name, content and location

**Comment by piotrpMSFT** [comment]
@zygimantas as this whole space [matures](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) over the next few months we will have an opportunity to think about how these file names relate to one another. For now we're going to keep things stable so we're not driving the product in two directions.
