### ISSUE TITLE
Host Policy to allow roll forward of preview1 -> preview2 sdk version

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#3243]
Tools preview2 will be compatible with projects built against tools preview1. The VS Templates for preview1 included an sdkversion of 1.0.0-preview1-002702. Once preview2 ships, the muxer should allow preview1 projects to roll forward to the preview2 tools.

**Comment by schellap** [comment]
Validated global.json.sdk.version works as follows:

1. Pick specified version in global.json.
2. If not 1, pick maximum production version.
3. If not 2, pick maximum pre-release version.

**Note** step 2 can pick a smaller production version (say, 1.0.0) over a higher pre-release version (2.0.0-prerelease-00001).

Closing for preview 2.
