### ISSUE TITLE
Build-base-path cannot handle trailing slash

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#3244]
## Steps to reproduce
`dotnet build --build-base-path "C:\users\USER\foo\"`

## Expected  behavior
Strips trailing slash and works as expected.

## Actual behavior
`Illegal cahracters in path.` output

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

```

## Notes
This also happens when using tools that utilize `ProjectDependenciesCommandFactory`.

**Comment by brthor** [comment]
This is an issue at the Windows level as it escapes the final quote, and is true for any argument.

The args are delivered in string[] args as not delimited properly when trailing backslashes are used before a quote. 

If you must do this you can escape the trailing backslash like so:
`dotnet build --build-base-path "C:\users\USER\foo\\"`
