### ISSUE TITLE
Resources only work when placed in the default namespace

### ISSUE THREAD

**Issue by ramarag** [dotnet/cli#3247]
Using RC2 version, if a resource is placed outside the default namespace, its ResourceManager throws a MissingManifestResourceException when it tries to get the ResourceSet

Scenario:

```
Project Name: TestResx
Default Namespace: TestResx
Resource file: Resources/Res.resx (namespace: TestResx.Resources)
```

Expected behavior:

```
The resource is embedded as TestResx.Resources.Res.resources
At runtime, it is possible to get a value from this resource
```

Actual behavior:

```
The resource is embedded as TestResx.Resources.Res.resources -> OK
At runtime, a MissingManifestResourceException is thrown
```

Workaround:

Add a namedResource in Project.json to force the resource to be embedded as TestResx.Res.resources

  "namedResource": {
    "TestResx.Res": "Resources\Res.resx"
  }

Demo project: TestResx.zip

I have seen that a quite similar issue have been closed as resolved in RC2. (aspnet/Tooling#311 , dotnet/cli#548) But it seems that it is not resolved. Note, it is not exactly the same case, so maybe the other case is really resolved.

/cc  @srollinet

**Comment by piotrpMSFT** [comment]
why is this preview2 release blocking?

**Comment by fubar-coder** [comment]
@piotrpMSFT It's not fixed and a huge problem for libraries heavily relying on embedded resources.

See also:

- [dotnet/cli#3383](https://github.com/dotnet/cli/issues/3383)
- [aspnet/Tooling#311](https://github.com/aspnet/Tooling/issues/311)
- [dotnet/cli#548](https://github.com/dotnet/cli/issues/548)

**Comment by sepidehMS** [comment]
I'm also hitting this issue when migrating to .NET Core 2.0

**Comment by livarcocc** [comment]
@sepidehMS can you share your csproj?

**Comment by danmosemsft** [comment]
ping @sepidehMS

**Comment by sepidehMS** [comment]
@livarcocc 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001509-00</RuntimeFrameworkVersion>
    <PackageTargetFallback>$(PackageTargetFallback);net461</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

</Project>
```

**Comment by danmosemsft** [comment]
@livarcocc we hit this in several real conversions of the most popular Nuget packages. Example https://github.com/autofac/Autofac but there are others.

We should make migration of these popular packages completely foolproof. Can we do something here?

**Comment by danmosemsft** [comment]
We hit this again migrating BouncyCastle. Some of the tests fail for this reason.
/cc @sepidehMS  @terrajobst

**Comment by livarcocc** [comment]
@danmosemsft we can look into why this is happening, as in, what is missing in the tooling to cause this to happen, but there is not more migration work planned for 2.0, just FYI.

**Comment by danmosemsft** [comment]
I assume you'd take any bug fixes necessary though. Thanks for taking a look!

**Comment by danmosemsft** [comment]
Turns out @sepidehMS 's bug is https://github.com/dotnet/project-system/issues/1933. I'll leave this issue around in case you need it for other folks above...
