### ISSUE TITLE
buildOptions/copyToOutput does not copy folders by relative path

### ISSUE THREAD

**Issue by silverferrum** [dotnet/cli#3250]
## Steps to reproduce

```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": {
      "include": [ "test.html", "Areas" ],
      "mappings": {
        "Areas": "../../wtCMS.Admin/Areas",               **It is not worknig**
        "test.html": "../../wtCMS.Admin/htmlpage3.html"   **This line works fine**
      }
    } 
  }
```
## Expected  behavior

Areas folder appears in `\bin\Debug\net461\win7-x64\` after successful compilation.
test.html file appears in `\bin\Debug\net461\win7-x64\` after successful compilation.
## Actual behavior

Areas folder **does not** appear in `\bin\Debug\net461\win7-x64\` after successful compilation.
test.html file appears in `\bin\Debug\net461\win7-x64\` after successful compilation.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by silverferrum** [comment]
Please, help me! 
```
    "copyToOutput": {
      "include": ["..\\..\\wtCMS.Admin\\Areas\\**\\*.cshtml" ], //creates wtCMS.Admin folder.
```

I need Areas folder.

```
      "mappings": {
        "Areas": "..\\..\\wtCMS.Admin\\Areas\\**\\*.cshtml"  //doesn't work
      }
```

**Comment by Robula** [comment]
I can't get my mappings to work either

```
  "buildOptions": {
    "copyToOutput": {
      "include": [
        "../packages/*OffScreen*/CefSharp/*.*"
      ],
      "mappings": {
        "../packages/*OffScreen*/CefSharp/*.*": "./"
      }
    }
  }
```

Just trying to copy to the root of my runtime directory.

**Comment by blackdwarf** [comment]
I've verified with Preview 4 tooling that this is not a problem anymore. I've created a new Preview 2 project.json as such: 

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true,
    "copyToOutput": {
        "include": ["../includes/*"],
        "mappings": {
            "../includes/*" : "."
        }
    }
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

The `includes` directory is one level above the repro directory. I then migrated the project to csproj and built it. The files from the `includes` directory were copied over. 

With this, I will close this issue as "mitigated y move to MSBuild". Please reopen if you believe this is in error or if the problem reproes with the latest CLI. Thanks!
