### ISSUE TITLE
Add a web template to dotnet new

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#3255]
We should add a web template to `dotnet new` for the June release. The content is [here](https://www.dropbox.com/s/e4o35zbj0qyj31e/WebAppIndAuth.zip?dl=0). After creation the result should be the same as the result from `yo aspnet`. When running `yo aspnet` it will automatically run npm install. We can consider to skip this step if it adds more difficultly here. We can simply print out a message letting the user know what command(s) to run.

**Comment by ajaybhargavb** [comment]
4a88cff1858389960a78ae82c13165f95fad1cd4
