### ISSUE TITLE
How to run dotnet with some target framework other than NetCore 5.0?

### ISSUE THREAD

**Issue by Kimi-Arthur** [dotnet/cli#326]
Most packages in nuget don't support .net core.
Since it's mainly MSIL or CIL code, it should probably work in some way.
Maybe we can specify the target framework to use to check for the compatibility.

**Comment by davidfowl** [comment]
@Kimi-Arthur simply change your project.json to use the framework you want to run. You can run on mono, normal .NET Framework or CoreCLR. `net4x` (e.g. net45)   can be used for .NET Framework 4.5 or mono (as an example), and dnxcore50 is core clr.

**Comment by Kimi-Arthur** [comment]
Is there a document for how to specify the runtime?
Maybe I didn't dig enough, but I didn't find one yet.

**Comment by blackdwarf** [comment]
@Kimi-Arthur you specify it via the "frameworks" node. You can see some examples on https://docs.asp.net/en/latest/dnx/projects.html, just don't use "dnx451" but "net45".

**Comment by ToddThomson** [comment]
I tried this in the basic web sample. I tried:
```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23727",
        "Microsoft.AspNetCore.Hosting": "1.0.0-*",
        "Microsoft.AspNetCore.IISPlatformHandler": "1.0.0-*",
        "Microsoft.AspNetCore.HttpOverrides": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*"
    },

    "frameworks": {
        "net45":{},
        "dnxcore50": { }
    }
}
```
All I added was the "net45": {} . This led to a large number of compatibility errors when issuing dotnet restore.

How does one target the .net 4.5.1 runtime when using dotnet CLI?

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/project.json#L22 shows how to reference net451

**Comment by varcario** [comment]
I see how you can specify to target net45, but can you actually deploy an app that targets net45 onto a .NET Core environment.  I have a net45 class library that references System.SerializableAttribute from a Reference.cs file generated from Visual Studio when I created my proxy classes from a WCF service.  I would like to deploy my ASP.NET Web API to run on .NET core and reference my library that has references to generated proxy classes to make Web Service SOAP calls.
