### ISSUE TITLE
Support referring assemblies from GAC

### ISSUE THREAD

**Issue by PrashanthIBM** [dotnet/cli#3263]
## Steps to reproduce

Hi ,

I am trying to upgrade my project to RC2.
In my previous project.json, i was able to refer gac assemblies using the frameworkassemblies section. But after upgrading to RC2, assemblies in gac are not getting recognized.
Even i tried using the import , but no luck.

Can anyone help me ?

sample project.json :
"frameworks": {
"net451": {
"imports": [ "portable-net452+win81" ],
"frameworkAssemblies": {
"gac-assmebly_name ": {
"version": "1.4.4.4",
"type": "build",
},
I am getting the below error
The dependency gac-assmebly_name >= 1.4.4.4 could not be resolved .

I have verified that the assembly is present in the GAC.
## Expected  behavior

@davidfowl  has told me that , dotnet cli does not support referring assemblies from GAC.
Can you please let me know any work around or can you fix this issue ?
## Environment data

PS C:\Users\praskarn> dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
PS C:\Users\praskarn>

**Comment by dls314** [comment]
@PrashanthIBM Did you find a way to make this work? I'm encountering the same problem today and trying to find my way.

**Comment by PrashanthIBM** [comment]
No.  They have to support it or we should make the dll to be a package and then refer it in project.json.

**Comment by Ermesx** [comment]
I think this part of documentation may help: 
https://docs.microsoft.com/pl-pl/dotnet/articles/core/tutorials/libraries#how-to-use-native-dependencies

**Comment by blackdwarf** [comment]
Since the [move to MSBuild](), the CLI does not do any resolving of dependencies anymore. That work is now being done in the SDK. I've created a new issue to track this: dotnet/sdk#647. Will close this one. If you need more info or you think this was in error, please reopen. Thanks!

**Comment by rainersigwald** [comment]
@dls314 But do note that MSBuild does have NuGet packages: https://www.nuget.org/packages/Microsoft.Build/. If they don't work for you please let us know: https://github.com/Microsoft/msbuild/issues/new
