### ISSUE TITLE
dotnet restore doesn't send authentication info to the proxy server

### ISSUE THREAD

**Issue by AleksSimi** [dotnet/cli#3265]
## Steps to reproduce
My developer machine is behind a corporate proxy. All the traffic goes through the proxy.

I tried to set in Visual Studio 14 /Common7/IDE/**devenv.exe.config** and /v4.0.30319/Config/**machine.config**

```
<system.net>
    <defaultProxy useDefaultCredentials="true" enabled="true">
    </defaultProxy>
</system.net>
```

but it doesn't help to take the proxy user and credentials from the IE settings.

## Expected  behavior
dotnet restore   downloads packages and creates the project.lock.json file correctly.

## Actual behavior
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
**error:   Response status code does not indicate success: 407 (authenticationrequired).**

## Environment data
`dotnet --info` output:

**Comment by tebeco** [comment]
Hi @blackdwarf,
Is there a known workaround until it's fixed ?

**Comment by blackdwarf** [comment]
This should be moved to Nuget/Home.
