### ISSUE TITLE
Script exit codes are ignored 

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#3266]
Script exit codes are ignored

## Steps to reproduce

Setup with a script that fails
```
"scripts": {
    "prepublish": [ "/bin/false" ]
  }
```

## Expected  behavior

publish should fail with an error message and a non-zero exit code

## Actual behavior

script failures are ignored, success message is printed, exit code is zero

**Comment by eerhardt** [comment]
This will be fixed with the move to MSBuild.  MSBuild Exec will fail the build if the command fails.
