### ISSUE TITLE
Be able to set an icon to standalone applications

### ISSUE THREAD

**Issue by Yves57** [dotnet/cli#3267]
When building a standalone application, it would be nice to be able to set an icon (the Roslyn `/win32icon`option in fact).

**Comment by piotrpMSFT** [comment]
@schellap @gkhanna79 @blackdwarf this would have to be added to dotnet.exe after renaming. Thoughts?

**Comment by schellap** [comment]
It sounds like we are going to need two exes

1. The muxer exe that carries dotnet branding.
2. The corehost exe that carries no branding and CLI would post process this for the developer.

For 2, potentially CLI can ask roslyn package expose this capability or CLI carries or depends on rc.exe to bake this into the published corehost exe.

I am not sure if we can overwrite the dotnet branding using rc.exe. If we can then we dont need 2 exes.

**Comment by easyt** [comment]
If this feature will not be in the RTM, is there a post build workaround that can be used to inject an icon into the executable?

**Comment by ayende** [comment]
Anything that can be done here?

**Comment by JustArchi** [comment]
Bump, it'd be really nice if there was an option to do this without resorting to hacks and adding resources in post-compilation steps.

**Comment by nopara73** [comment]
Are there any intentions to fix this (and related issues) within the next couple of years or it'd be smarter to just find lasting workarounds?

**Comment by livarcocc** [comment]
We are looking into this for applications targeting windows in the 3.0 time frame. I have updated the milestone for this issue.

**Comment by livarcocc** [comment]
cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
There is a corresponding issue here https://github.com/dotnet/core-setup/issues/4193.  The work is underway - right now it is scoped to windows only (both from where it is built and what is being built).

**Comment by livarcocc** [comment]
This is being fixed here: https://github.com/dotnet/sdk/pull/2545.
