### ISSUE TITLE
dotnet restore times out in ifs build

### ISSUE THREAD

**Issue by gpcottle** [dotnet/cli#3279]
Hi
I am having trouble trying to get a build to work in a locally hosted Team Foundation Server 2015 on Windows SBS2011/2008R2. I hope I have put this issue in the right place.

The project itself is small, being just the default items created when Visual Studio creates an empty Core Web Application. I can do a manual deploy to my IIS and get it to display - nothing more than "Hello World" at the moment.

I have created a build process, with the first step being a Command Line with `dot net restore -v`
When I start the build, the restore starts and the first few dependencies seem to download OK. Then the time to download an item gets longer and longer and eventually, the requests timeout after 100000ms. The process fails after 15 minutes when it has given up. I tried the --disable-parallel flag, but that made no difference.

I tried running the `dotnet restore` step manually from the build folder where TFS extracts the application from. It ran successfully, but seemed to extract significantly fewer items than the TFS build step. I was then able to build the application and publish it.

`dotnet --info` output:
C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

I have attached the build log file.
[logs_42.zip](https://github.com/dotnet/cli/files/287631/logs_42.zip)

Many thanks
Graham

**Comment by piotrpMSFT** [comment]
@rrelyea thoughts?

**Comment by piotrpMSFT** [comment]
@gpcottle can you move this to the nuget/home repo?

**Comment by gpcottle** [comment]
@piotrpMSFT Many thanks - I have created a new issue at Nuget/Home (not sure whether/how I can move)
