### ISSUE TITLE
"assembly not found" exception while running "dotnet compile --native"

### ISSUE THREAD

**Issue by f0rt** [dotnet/cli#328]
Hi team,
I'm running "dotnet compile --native" that fails with exception: *** Assembly not found: System.Collections. ([Myproject]Myproject.Program.Main).
The command "dotnet compile" completes without exceptions. The project is ASP.NET Console Application (package).
I guess I'm doing something wrong. Any ideas?

Thanks in advance!

**Comment by gkhanna79** [comment]
Can you confirm you followed the steps at https://github.com/dotnet/corert/blob/master/Documentation/how-to-build-and-run-ilcompiler-in-console-shell-prompt.md?

**Comment by f0rt** [comment]
@gkhanna79 Thanks for the link.
I haven't followed the steps. I'm trying to do it now. Do I need to build the ILCompiler or I just need to install the pre-requisites?
Whan I try to build the compiler I'm getting this error:

Commencing CoreRT Repo build

Checking pre-requisites...

'&' is not recognized as an internal or external command,
operable program or batch file.
'digitally' is not recognized as an internal or external command,
operable program or batch file.
'setting' is not recognized as an internal or external command,
operable program or batch file.
The AT command has been deprecated. Please use schtasks.exe instead.
Invalid command.

**Comment by brthor** [comment]
@f0rt You should not need to build CoreRT in order to use `dotnet compile --native`

Keep in mind though this feature is in early stages of development and only works in very simple scenarios. Can you share your project.json ?

**Comment by f0rt** [comment]
Sure. Here it is:
{
  "version": "1.0.0-*",
  "description": "MyProject Console Application",
  "authors": [ "blade" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.Hosting": "1.0.0-rc1-final",
    "MyProjectData": "1.0.0-*",
  },

  "commands": {
    "MyProjectConsoleApp": "MyProjectConsoleApp"
  },

  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}
#########################################
I've also tried to run it against empty project with no dependencies created form VS 2015 Console Application (package) template.

Here is the program class content:
    public class Program
    {
        public static void Main(string[] args)
        {
           "123".ToString();
        }
    }

And here is project.json content:
{
  "version": "1.0.0-*",
  "description": "test123 Console Application",
  "authors": [ "blade" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
  },

  "commands": {
    "test123": "test123"
  },

  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Console": "4.0.0-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}

I'm getting the error:
Compiling test123 for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.7628036

Input Assembly: C:\Users\user123\Documents\Visual Studio 2015\Projects\test123\src\test123\bin\Debug\dnxcore50\test123.dll
Compiling [test123]test123.Program.Main
Compiling [System.Private.CoreLib]System.Object.ToString
Compiling [System.Private.CoreLib]System.String.ToString
Compiling [System.Private.CoreLib]System.Object.GetType
Compiling [System.Private.CoreLib]Internal.Reflection.Core.NonPortable.ReflectionCoreNonPortable.GetRuntimeTypeForEEType
Compiling [System.Private.CoreLib]System.Object.get_EETypePtr
Compiling [System.Private.CoreLib]System.EETypePtr..ctor
Compiling [System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RuntimeTypeUnifier.GetTypeForRuntimeTypeHandle
Compiling [System.Private.CoreLib]System.RuntimeTypeHandle..ctor
Compiling [System.Private.CoreLib]System.EETypePtr.get_RawValue
Compiling [System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RuntimeTypeUnifier.WithDebugName
Compiling [System.Private.CoreLib]System.Collections.Concurrent.ConcurrentUnifierW`2<[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RawRuntimeTypeHandleKey[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RuntimeType>.GetOrAdd
*** SkipJIT ([System.Private.CoreLib]System.Collections.Concurrent.ConcurrentUnifierW`2<[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RawRuntimeTypeHandleKey[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RuntimeType>.GetOrAdd)
Compiling [System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RawRuntimeTypeHandleKey..ctor
Compiling [System.Private.CoreLib]System.Runtime.CompilerServices.CctorHelper.CheckStaticClassConstructionReturnGCStaticBase
Compiling [System.Private.CoreLib]RuntimeTypeHandleToRuntimeTypeCache..cctor
Compiling [System.Private.CoreLib]RuntimeTypeHandleToRuntimeTypeCache..ctor
Compiling [System.Private.CoreLib]System.Runtime.CompilerServices.CctorHelper.CheckStaticClassConstruction
Compiling [System.Private.CoreLib]System.Threading.Interlocked.MemoryBarrier
Compiling [System.Private.CoreLib]System.Runtime.CompilerServices.CctorHelper.Call<[System.Private.CoreLib]System.Int32>
Compiling [System.Private.CoreLib]System.Threading.Interlocked.CompareExchange
Compiling [System.Private.CoreLib]System.Collections.Concurrent.ConcurrentUnifierW`2<[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RawRuntimeTypeHandleKey[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RuntimeType>..ctor
Compiling [System.Private.CoreLib]Container<[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RawRuntimeTypeHandleKey[System.Private.CoreLib]Internal.Reflection.Core.NonPortable.RuntimeType>..ctor
Compiling [System.Private.CoreLib]System.Threading.Lock..ctor
Compiling [System.Private.CoreLib]System.Object..ctor
The system cannot find the file specified

**Comment by brthor** [comment]
@f0rt The supported way of producing a template project for use with the dotnet cli right now is through `dotnet init`

Your shared project.json has a couple dependencies that are still unsupported at this time. For example, Project to Project references are not yet supported but are being worked on.

**Comment by f0rt** [comment]
Thank you for pointing that. Looking forward to your next features. :)

**Comment by piotrpMSFT** [comment]
looks like this is resolved :)

f0rt, please re-open if there is still something we need to look into here!
