### ISSUE TITLE
dotnet run fails if "buildOptions" not specified int the global context

### ISSUE THREAD

**Issue by mrgleba** [dotnet/cli#3280]
## Steps to reproduce

[App.zip](https://github.com/dotnet/cli/files/287709/App.zip)
cd App
dotnet restore
dotnet run
## Expected  behavior

Command is run
## Actual behavior

File not found exception
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
## Cause

Everything starts working ok if we move "buildOptions" from "frameworks/net451" to the global scope of project.json
## Related issue

https://github.com/aspnet/KestrelHttpServer/issues/873

**Comment by piotrpMSFT** [comment]
buildOptions are currently only a global setting. we will revusit before rtm.

**Comment by blackdwarf** [comment]
Since we are moving to MSBuild and csproj, this issue is not applicable anymore. Closing.
