### ISSUE TITLE
Add 'nowarn' schema info to SchemaStore

### ISSUE THREAD

**Issue by Eilon** [dotnet/cli#3282]
## Steps to reproduce

Open project.json, try to get Intellisense for `nowarn` compiler option to suppress compiler warnings.

The option does exist, as seen here: https://github.com/dotnet/cli/blob/f515e80029440847e547e67c19fbb3a3b0907418/src/Microsoft.DotNet.ProjectModel/ProjectReader.cs#L580

It's just not in the schema.

### SchemaStore

The fix is to send a PR to https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json with the updated schema info. This is what VS uses for Intellisense in project.json files.

Should also compare and see if there are any other missing options and add those to the schema.

## Expected  behavior

Intellisense should show the schema for this option.

## Actual behavior

No Intellisense.

## Environment data
`dotnet --info` output:

N/A

**Comment by piotrpMSFT** [comment]
@ajaybhargavb you did the last round of these. can you pick these up?

**Comment by Eilon** [comment]
@ajaybhargavb if you have time for this, go for it. If not, please let me know.

**Comment by Eilon** [comment]
Ok duh, just saw the PR 😄

**Comment by ajaybhargavb** [comment]
schemastore/schemastore@b24ea2f878d3aab8ab290105326ea4b1b6246425
