### ISSUE TITLE
project.json Schema missing default value for preserveCompilationContext

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#3285]
## Issue

Every other `"type": "boolean"` setting in the [`project.json` schema at JSON Schema Store](http://json.schemastore.org/project) has a `"default": false`, except for `preserveCompilationContext`.
## Expected  entry

```
"preserveCompilationContext": {
    "type": "boolean",
    "description": "Set this option to preserve reference assemblies and other context data to allow for runtime compilation.",
    "default": false
},
```
## Actual entry

```
"preserveCompilationContext": {
    "type": "boolean",
    "description": "Set this option to preserve reference assemblies and other context data to allow for runtime compilation."
},
```

This appears in both `buildOptions` and `compilationOptions` (depreciated).

**Comment by piotrpMSFT** [comment]
@ajaybhargavb

**Comment by mairaw** [comment]
That file is also missing some entries like xmlDoc, new structure of configProperties, etc.

**Comment by piotrpMSFT** [comment]
With project.json being replaced by csproj, we won't be pursuing a fix here.
