### ISSUE TITLE
Packages config is not respected

### ISSUE THREAD

**Issue by dneimke** [dotnet/cli#3288]
## Steps to reproduce

Add the following configuration to global.json

`{
  "projects": [ "src", "test" ],
  "packages": "dotnet_packages",
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}`

Restore packages
## Expected  behavior

Packages should restore to the specified path (dotnet_packages) in the root folder of the solution 
## Actual behavior

Packages are restored to %userprofile%.nuget\packages
## Environment data

`dotnet --info` output:

`Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64`

**Comment by piotrpMSFT** [comment]
@rrelyea can you take a look at this one?

**Comment by piotrpMSFT** [comment]
Moved to nuget/home.
