### ISSUE TITLE
Generate NI images for Microsoft.DotNet.ILCompiler that is packaged with dotnet CLI tools.

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#329]

**Comment by brthor** [comment]
Will these NI images be  a part of their respective toolchain packages?

**Comment by gkhanna79** [comment]
Long term, we would like to selfhost the toolchain. that said, this should be used as tracking bug to enable that experience earlier if required.

**Comment by brthor** [comment]
I'm just not clear if we should generate these images in the cli build (like we crossgen roslyn) or if they'll already be there in the packages.

**Comment by gkhanna79** [comment]
We should generate it to be part of the package that the user downloads for faster out of the box experience for --native.

**Comment by schellap** [comment]
For now, @brthor can ILCompiler also be crossgen'ed?

**Comment by brthor** [comment]
@schellap We can try 😀

**Comment by Petermarcu** [comment]
@gkhanna79 , does this still need to be tracked here?

**Comment by gkhanna79** [comment]
@nattress Can you please file an issue for this in the CoreRT repo and close this (since you are looking into moving dotnet-compile-native to CoreRT)?

**Comment by nattress** [comment]
See CoreRT https://github.com/dotnet/corert/issues/1135
