### ISSUE TITLE
Point-in-time Regression? ... or is DotNetHostPolicy not enough?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#3290]
## Steps to reproduce
My self-contained test project restores, compiles, publishes, and runs as an `rc2-final` app with feed ...
```xml
<add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
```
Problem occurs if the feed is set to `aspnetvnext` ...
```xml
<add key="AspNetVNext" value="https://www.myget.org/F/aspnetvnext/api/v3/index.json" />
<add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
```
... which worked a few days ago.

If this is not a point-in-time regression, then I'm wondering if it is related to my minimal use of `NETStandard.Library` + `Microsoft.NETCore.DotNetHostPolicy` to get self-contained apps published.

If I replace those two packages with the mega-meta-package `Microsoft.NETCore.App` (no `"type": "platform"`, of course), the app publishes using the `aspnetvnext` feed.

## Expected  behavior
```
dotnet publish -c Release -r win81-x64
```
Restores and publishes on `aspnetvnext` feed with `NETStandard.Library` and `Microsoft.NETCore.DotNetHostPolicy` packages.

## Actual behavior
```
dotnet publish -c Release -r win81-x64
```
Fails to compile on `aspnetvnext` feed with `NETStandard.Library` and `Microsoft.NETCore.DotNetHostPolicy` packages with exception ...
```
Failed to make the following project runnable: teststandalone (.NETCoreApp,Version=v1.0) 
reason: Expected coreclr library not found in package graph. Please try running dotnet 
restore again.
```

## Environment data
```
.NET Command Line Tools (1.0.0-preview2-002900)

Product Information:
 Version:            1.0.0-preview2-002900
 Commit SHA-1 hash:  f4ceb1f213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
`project.json` particulars ... **BREAKS!** on `aspnetvnext` feed
```json
"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "NETStandard.Library": "1.5.0-*",
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*"
},
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "portable-dnxcore50+net45+win8+wp8+wpa81" ]
    }
},
"runtimes": {
    "win7-x64": {},
    "win81-x64": {},
    "win10-x64": {}
},
```
`project.json` particulars ... **WORKS!** on `aspnetvnext` feed
```json
"dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.NETCore.App": "1.0.0-*"
},
"frameworks": {
    "netcoreapp1.0": {
        "imports": [ "portable-dnxcore50+net45+win8+wp8+wpa81" ]
    }
},
"runtimes": {
    "win7-x64": {},
    "win81-x64": {},
    "win10-x64": {}
},
```

**Comment by jamesqo** [comment]
I seem to be having this same issue as well; simply including `Microsoft.NETCore.DotNetHostPolicy` doesn't seem to make my app runnable for some reason. Is there some way I can do this, without bringing along the whole `NETStandard.Library`? (I'm a corefx contributor so I need to use rc4+ library components for testing, whereas including `Microsoft.NETCore.App` seems to 'downgrade' the dependencies to rc2.)

**Comment by GuardRex** [comment]
Solved by adding `Microsoft.NETCore.Runtime.CoreCLR`. See: https://github.com/dotnet/corefx/pull/9042

Previously, this worked but fails now to compile/publish ...
```json
"NETStandard.Library": "1.5.0-*",
"Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*",
```
Now, using the following will yield successful compile/publish ...
```json
"NETStandard.Library": "1.5.0-*",
"Microsoft.NETCore.DotNetHostPolicy": "1.0.1-*",
"Microsoft.NETCore.Runtime.CoreCLR": "1.0.2-*",
```

**Comment by weshaggard** [comment]
Yes to get a full runnable application you need the libraries (NETStandard.Library), a runtime (Microsoft.NETCore.Runtime.CoreCLR) and a host (Microsoft.NETcore.DotNetHostPolicy). In the RC2 time frame NETStandard.Library incorrectly depended on Microsoft.NETCore.Runtime which is why it used to work but going forward you need to independently reference a runtime, or reference the higher level app-model meta-package Microsoft.NETCore.App which includes all these.
