### ISSUE TITLE
dotnet pack with copyToOutput not working

### ISSUE THREAD

**Issue by xoofx** [dotnet/cli#3294]
## Steps to reproduce
- Create a Class library project dotnet rc2
- Setup some files with `copyToOutput`, here is the `project.json`
- run `dotnet pack`

See attached project: [TestCopyOutput.zip](https://github.com/dotnet/cli/files/290999/TestCopyOutput.zip)

```
{
  "title": "TestCopyOutput",
  "version": "1.0.0-*",
  "packOptions": {
  },

  "buildOptions": {
    "copyToOutput": {
      "include": [ "files" ]
    }
  },

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  }
}
```
## Expected  behavior
- files must be part of the nupkg and an entry with the files to copy should be part of the nuspec.
## Actual behavior
- nothing is stored in the nupkg (no files, no entries in the nuspec)
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@rrelyea once we move `dotnet pack` to use `nuget`'s implementation will this behavior be addressed?

I'm moving the issue to `backlog` since we don't want to impact `pack` until the implementation is swapped.

**Comment by maxim-boligatov** [comment]
I think I can post here link to related issue:

https://github.com/dotnet/cli/issues/4073

**Comment by blackdwarf** [comment]
This issue falls into a class of similar issues and is being tracked on Nuget/Home#3935. Will close this one. If you feel this is in error, please reopen. Thanks!
