### ISSUE TITLE
Getting Started link goes nowhere

### ISSUE THREAD

**Issue by appqui** [dotnet/cli#3296]
Readme.md
Check out our Getting started page.

**Comment by vcsjones** [comment]
Fixed in 5ac3954ee4e2459b655740d0c17dd98bd965424c.

**Comment by vcsjones** [comment]
It looks like it goes to https://aka.ms/dotnetcoregs for me.

**Comment by piotrpMSFT** [comment]
just tested the link and found the same as @vcsjones!
