### ISSUE TITLE
Should imports be checked for validity?

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3306]
If I understand it correctly, having the following in project.json is always wrong, since `netcoreapp1.0` uses System.Runtime, but `net45` uses mscorlib instead:

```json
"frameworks": {
  "netcoreapp1.0": {
    "imports": "net45"
  }
}
```

Would it make sense to make such declarations into errors on `dotnet restore`?

Also, I'm not sure if it makes sense to fix such a relatively minor issue, considering project.json is going away soon.

**Comment by mellinoe** [comment]
I don't think it makes sense. "Imports" are used so you can ignore/bypass NuGet's asset selection algorithm. By using it, you are already opting in to packages that are potentially invalid for you to use. I don't think it's valuable to try to identify some potentially problematic cases and try to prevent you from shooting yourself in the foot.

**Comment by piotrpMSFT** [comment]
Correct. Package owners should be updating their packages so that the new validation mechanisms included in CLI's NuGet can validate package contents without the use of `imports` statements.
