### ISSUE TITLE
Linking Core RC2 "Portable" with full .NET 4.61 within MSVS

### ISSUE THREAD

**Issue by crokusek** [dotnet/cli#3310]
## Steps to reproduce
Wrap and Link a .NET 4.61 project into a .NET Core RC2 portable executable (MvcMovie) using MSVS 2015 Enterprise Update 2.

It was working with the wrapped assembly compiled/wrapped as .NET 46 and Core Framework target "net46".

## Expected  behavior
No build errors.  

## Actual behavior
Build Error:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(241,5): error : Object reference not set to an instance of an object.

Double clicking the error navigates to this line, something must not be set:

 <Dnx
      RuntimeExe="$(SDKToolingExe)"
      Condition="'$(_DesignTimeHostBuild)' != 'true'"
      ProjectFolder="$(MSBuildProjectDirectory)"
      Arguments="$(_BuildArguments)"
      />

## Environment data

[xproj_json.zip](https://github.com/dotnet/cli/files/292475/xproj_json.zip)

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

Any workaround (env variable) would be appreciated.  Apologies if this is not the correct place to post this type of issue.

**Comment by piotrpMSFT** [comment]
Since this is a toolign issue, moved to aspnet/Tooling repo.
