### ISSUE TITLE
Project produced with 'dotnet new' doesn't build

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#3315]
This starts with 2882 and is true today in 2913. It worked in 2877.

## Steps to reproduce
1) unzip/add to path: https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002882/dotnet-dev-win-x64.1.0.0-preview2-002882.zip
2) dotnet new
3) dotnet restore
4) dotnet build

## Expected  behavior
Build succeeds.

## Actual behavior
Build fails

Project 2 (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling 2 for .NETCoreApp,Version=v1.0
D:\work\findit\tests\2\project.json(7,31): error NU1002: The dependency Microsoft.CodeAnalysis.Common 2.0.0-beta1 does not support framework .NETCoreApp,Version=v1.0.
D:\work\findit\tests\2\project.json(7,31): error NU1002: The dependency Microsoft.CodeAnalysis.CSharp 2.0.0-beta1 does not support framework .NETCoreApp,Version=v1.0.
D:\work\findit\tests\2\project.json(7,31): error NU1002: The dependency Microsoft.CodeAnalysis.VisualBasic 2.0.0-beta1 does not support framework .NETCoreApp,Version=v1.0.

Compilation failed.
    0 Warning(s)
    3 Error(s)

Time elapsed 00:00:00.0224491

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-002882)

Product Information:
 Version:            1.0.0-preview2-002882
 Commit SHA-1 hash:  f46be283f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by ericstj** [comment]
Works for me.  Don't know where you're getting a Microsoft.CodeAnalysis.Common **2.0.0-beta1** dependency.  
I suspect you only have the nuget.org feed registered (which has this version) and not the feed with the actual version that MS.NETCore.App depends on.

 /cc @tmat @weshaggard

**Comment by ericstj** [comment]
Hmm I see that the specific version depended on is not on the dotnet-core feed.  https://github.com/dotnet/core-setup/pull/12 changed the version.  @eerhardt should you have also mirrored the packages to https://dotnet.myget.org/gallery/dotnet-core so that folks get a full package set when resolving from this feed?

**Comment by billwert** [comment]
I assume because the Nuget.config in the root of the enlistment has cli-deps in it everything works out in CI. Perhaps the tests in CI should be adjusted to not use this dependency?

**Comment by eerhardt** [comment]
`Microsoft.NETCore.App` has always been published to https://dotnet.myget.org/gallery/dotnet-core.  It gets published there first, and mirrored into cli-deps.

Both `Microsoft.NETCore.App` versions 4306 and 4312 are on https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App.  As well as the latest.

Our EndToEnd CI tests don't use the cli-deps, they generate a NuGet.config file that points to the dotnet-core feed.

https://github.com/dotnet/cli/blob/rel/1.0.0/test/EndToEnd/EndToEndTest.cs#L215

**Comment by ericstj** [comment]
Yep, and that should be broken today, or at least restore with warnings, due to the missing Roslyn package versions from dotnet-core.

**Comment by billwert** [comment]
@eerhardt Ah. But EndToEnd test runs after something else has put 1.3.0-beta1-20160525-03 of the CodeAnalysis packages in the nuget cache. I can repro this on my machine:
1) dotnet new
2) add config file without CLI deps
3) dotnet restore
4) dotnet build, it fails
5) restore using config file with CLI deps
6) dotnet build, it succeeds
7) delete lock file
8) restore with original config file, no CLI deps
9) dotnet build, it succeeds

For EndToEnd test to be actually representative of reality, it should probably use its own package cache. I'll open another issue.

**Comment by eerhardt** [comment]
> Yep, and that should be broken today, or at least restore with warnings, due to the missing Roslyn package versions from dotnet-core.

Shouldn't Roslyn be on dotnet-core? That way the feed contains the closure of its dependencies?

/cc @weshaggard

**Comment by ericstj** [comment]
@eerhardt it is.  I believe folks were manually mirroring to dotnet-core when updating NETCore.App.  You were the last to change it with https://github.com/dotnet/core-setup/pull/12 but you didn't mirror the new version.

**Comment by eerhardt** [comment]
That's the issue with manual processes. How is everyone supposed to know about it?

**Comment by ericstj** [comment]
Agreed @eerhardt , not your fault.  Just needs to get fixed.  If we want to make it automatic we could do something in the core-setup repo's publishing /cc @dagood.

**Comment by weshaggard** [comment]
Yes this is general issue right now when we update the Roslyn version it doesn't end up on the dotnet-core feed. @eerhardt I believe this should be addressed when the Roslyn team adds dotnet-core to their feed webhook.

**Comment by billwert** [comment]
This is still true, seemingly: Just tried with 2793. 
````console
D:\work\2973new>dotnet restore --packages here
log  : Restoring packages for D:\work\2973new\project.json...
````
<snip>
````console
D:\work\2973new>dotnet build
Project 2973new (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling 2973new for .NETCoreApp,Version=v1.0
D:\work\2973new\project.json(10,35): error NU1001: The dependency Libuv >= 1.9.0-rc2-21014 could not be resolved.
D:\work\2973new\project.json(10,35): error NU1001: The dependency Microsoft.CodeAnalysis.Common 1.3.0-beta1-20160602-03 could not be resolved.
... 141 more similar errors ...
````

Even after adding cli-deps to my nuget.config I get a failure, which doesn't make sense:
````console
D:\work\2973new>dotnet build
Project 2973new (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling 2973new for .NETCoreApp,Version=v1.0
D:\work\2973new\project.json(10,35): error NU1001: The dependency System.Threading.Timer >= 4.0.1-rc3-24204-00 could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.0194078
````
Because System.Threading.Timer seems to have restored just fine:
````console
D:\work\2973new>dir here\system.threading.timer\4.0.1-rc3-24204-00
 Volume in drive D is DATADRIVE1
 Volume Serial Number is 36D8-5995

 Directory of D:\work\2973new\here\system.threading.timer\4.0.1-rc3-24204-00

06/06/2016  10:02 AM    <DIR>          .
06/06/2016  10:02 AM    <DIR>          ..
06/03/2016  09:12 PM             9,323 dotnet_library_license.txt
06/06/2016  10:02 AM    <DIR>          lib
06/06/2016  10:02 AM    <DIR>          ref
06/06/2016  10:02 AM            67,390 System.Threading.Timer.4.0.1-rc3-24204-00.nupkg
06/06/2016  10:02 AM                88 System.Threading.Timer.4.0.1-rc3-24204-00.nupkg.sha512
06/03/2016  09:12 PM             2,375 System.Threading.Timer.nuspec
06/03/2016  09:12 PM             1,617 ThirdPartyNotices.txt
               5 File(s)         80,793 bytes
````

I think it is bad that we are publishing new CLI zips that do not work. Can we either make sure they will work or stop publishing them until they do?

**Comment by eerhardt** [comment]
@billwert - if you want to override your NuGet package directory, an easy way to do that is:

`set NUGET_PACKAGES=D:\work\2973new\here`

This env var is used in in the CLI and NuGet to know where to find your NuGet package cache.

From a [comment in the code](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L159-L165):

```
        public static string ResolvePackagesPath(string rootDirectory, GlobalSettings settings)
        {
            // Order
            // 1. global.json { "packages": "..." }
            // 2. EnvironmentNames.PackagesStore environment variable
            // 3. NuGet.config repositoryPath (maybe)?
            // 4. {DefaultLocalRuntimeHomeDir}\packages
```

So just saying `dotnet restore --packages here` doesn't work because restore will put your packages there, but `dotnet build` et.al. won't know where to find them.

The following steps worked for me with the latest CLI (and a NuGet.config file that contains `    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />`

```
mkdir new3315
cd new3315

dotnet.exe new
dotnet.exe restore --packages here
set NUGET_PACKAGES=C:\new3315\here
dotnet.exe build
dotnet.exe run

Hello World!
```

**Comment by ericstj** [comment]
Shouldn't we make any command that needs packages support the --packages switch?

**Comment by eerhardt** [comment]
> Shouldn't we make any command that needs packages support the --packages switch?

Maybe. It would likely be all of them sans `dotnet new`. `build` would need it, and `run`, `test`, `pack` and `publish` all need to call `build.

Another way to think about it is:  why does `dotnet restore` need this option when there are so many other ways to specify where the NuGet packages should be cached? How many ways do we need?

**Comment by eerhardt** [comment]
Is there anything left on this issue to be done for `preview2`? We are automatically publishing the Roslyn packages to the `dotnet-core` feed, so we no longer hit that issue.

I've explained above how to make this scenario work if you are trying to change where your package cache is located.

If we want to add a `--packages` switch to all our commands, I don't think that will happen for `preview2`, and I think that should be open under a separate 'enhancement' issue.

If there are no objections, I'll close this issue since the original problem is fixed with automatically pushing the Roslyn packages to the `dotnet-core` feed.

**Comment by billwert** [comment]
Yeah, we can close this. It happens that today's build can new, restore, and build successfully on a clean machine, so that's great!

FWIW: As you explain it, it's of course obvious that using --packages like that can't work, since project.lock.json doesn't carry path information. However, the fact that it's the only place right now where it exists implies to the user that it *should* work the way I thought it did; otherwise what good is the argument?

This deserves promotion to a top level issue. I'll open one.
