### ISSUE TITLE
OSX installer pkg for preview2-00291 SDK is corrupted

### ISSUE THREAD

**Issue by dleeapho** [dotnet/cli#3317]
## Steps to reproduce
Download https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-dev-osx-x64.latest.pkg and install. Follow the installation steps to the end.

## Expected  behavior
The .NET CLI SDK bits are installed.

## Actual behavior
Error: "Installation failed. The installer can't locate the data it needs to install the software"
Note the pkg is only 8.8mb

## Environment data
OSX El Capitan 10.11.4

**Comment by dleeapho** [comment]
@brthor fallout from the repo split?

**Comment by brthor** [comment]
Thanks for filing this @dleeapho I'll take a look today.

**Comment by brthor** [comment]
There were two issues here. I have a fix incoming for core-setup which will fix the sharedfx installer, then I'll make a PR with the fixes to the SDK installer and bump the version we take from core-setup.

**Comment by brthor** [comment]
Core-setup fix is in, cli fix is out

**Comment by brthor** [comment]
Fixed in #3327 

Core-Setup builds were getting blocked by some ubuntu issues. Leaving this open til those fixes come into cli.

**Comment by brthor** [comment]
Confirmed this is resolved.
