### ISSUE TITLE
Dotnet Pack exiting with Exit Code 1

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#333]
Caught this with the new E2E Test. 

On all platforms `dotnet pack` exits with exit code 1 after seemingly successfully producing a nuget package. There is no output other than the path where the nuget package was produced.

**Comment by davidfowl** [comment]
Glad we have tests now 😀

**Comment by victorhurdugaci** [comment]
I'll fix it because it blocks the KoreBuild porting

**Comment by anurse** [comment]
@victorhurdugaci and I found it, he's submitting a PR and we'll merge it ASAP. It's trivial.

https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Pack/Program.cs#L54

![image](https://cloud.githubusercontent.com/assets/7574/11483896/f0ac2352-975f-11e5-9d7d-079d2a85b83b.png)

![image](https://cloud.githubusercontent.com/assets/7574/11483920/07b00d52-9760-11e5-8764-99f870f89090.png)

![image](https://cloud.githubusercontent.com/assets/7574/11483966/4be5abee-9760-11e5-8e70-3cdc53bde8e5.png)
