### ISSUE TITLE
prebuild/postbuild in project.json should be precompile/postcompile

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#3338]
According the the `project.json` schema, `prebuild/postbuild` are valid; however, it's `precompile/postcompile` that actually work.

http://json.schemastore.org/project shows ...
```json
"prebuild": { "$ref": "#/definitions/script" },
"postbuild": { "$ref": "#/definitions/script" },
```
I thought there was already an open issue on this, but I couldn't find it. This is causing some confusion (e.g., https://github.com/aspnet/Home/issues/1491#issuecomment-222828650).

**Comment by dasMulli** [comment]
i think the active issue is https://github.com/dotnet/cli/issues/3094
