### ISSUE TITLE
Question: How to ensure CLI restores a package from a particular source?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/cli#3339]
Hi, I'd like to use the CLI to restore some corefx/coreclr packages I've built locally for testing purposes. Here is my `NuGet.config` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="corefx.local" value="C:\Users\James\Code\git\corefx\bin\packages\Release" />
    <add key="coreclr.local" value="C:\Users\James\Code\git\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\pkg" />
  </packageSources>
</configuration>
```

and here is my `project.json` (the rc4 packages should come from my local builds):

```json
{
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.NETCore.DotNetHostPolicy": "1.0.1-rc2-*",
    "Microsoft.NETCore.Runtime.CoreCLR": "1.0.2-rc4-*",
    "System.Collections": "4.0.11-rc4-*",
    "System.Console": "4.0.0-rc4-*",
    "System.Runtime": "4.1.0-rc4-*",
    "System.ValueTuple": "4.0.0-rc4-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  "runtimes": {
    "win10-x64": {}
  }
}
```

When I try to run `dotnet restore` on this project after re-building my local copy of `System.Collections`, however, it seems to be unable to restore `runtime.any.System.Collections`:

```
log  : Restoring packages for C:\Users\James\Code\tests\CorefxTesting\project.json...
...
info :   NotFound https://api.nuget.org/v3-flatcontainer/system.valuetuple/index.json 165ms
log  : Installing System.Collections 4.0.11-rc4-24121-0.
info :   CACHE https://api.nuget.org/v3-flatcontainer/runtime.any.system.collections/index.json
error: Unable to resolve 'runtime.any.System.Collections (>= 4.0.11-rc4-24201-0)' for '.NETCoreApp,Version=v1.0 (win10-x64)'.
info : Committing restore...
log  : Writing lock file to disk. Path: C:\Users\James\Code\tests\CorefxTesting\project.lock.json
log  : C:\Users\James\Code\tests\CorefxTesting\project.json
log  : Restore failed in 2099ms.

Errors in C:\Users\James\Code\tests\CorefxTesting\project.json
    Unable to resolve 'runtime.any.System.Collections (>= 4.0.11-rc4-24201-0)' for '.NETCoreApp,Version=v1.0 (win10-x64)'.

NuGet Config files used:
    C:\Users\James\Code\tests\CorefxTesting\NuGet.Config
    C:\Users\James\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Users\James\Code\git\corefx\bin\packages\Release
    C:\Users\James\Code\git\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\pkg

Installed:
    1 package(s) to C:\Users\James\Code\tests\CorefxTesting\project.json
```

I'm assuming what it's doing here (from the line with `CACHE`) is that it assumes I want the version of `runtime.any.System.Collections` from nuget.org, and tries to get that one, but there's no rc4+ version available there. Is there any way to 'point' CLI to my local packages directory in corefx (`corefx.local`) instead?

I checked that the package in question was present in the `packages` directory after rebuilding the project; I also tried clearing the package cache in `~/.nuget/packages` and cleaning the lockfile/bin/obj.

**Comment by brthor** [comment]
@jamesqo What you're doing here is sufficient to point the cli at your local package sources. In fact you can see which feeds were used:

```
Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Users\James\Code\git\corefx\bin\packages\Release
    C:\Users\James\Code\git\coreclr\bin\Product\Windows_NT.x64.Release\.nuget\pkg
```

What is more interesting is the version mismatch between System.Collections (` 4.0.11-rc4-24121-0`) and runtime.any.System.Collections (`4.0.11-rc4-24201-0`). 

I would highly recommend you don't use * and target specific versions in your project.json and see if the error still occurs

**Comment by piotrpMSFT** [comment]
You may also want to reverse the order of feeds so yours is preferred.
