### ISSUE TITLE
HttpClient PostAsync - The server returned an invalid or unrecognized response

### ISSUE THREAD

**Issue by RicardoRazz** [dotnet/cli#3344]
EDITED:

If I run this application on a Windows computer everything works out fine. When I run this application on a Linux (CentOS) computer I get the following exception:

> System.Net.Http.HttpRequestException: The server returned an invalid or unrecognized response. at System.Net.Http.CurlResponseHeaderReader.ReadHeader(String& headerName, String& headerValue) at System.Net.Http.CurlHandler.MultiAgent.CurlReceiveHeadersCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 

I've tried this code on a Windows machine and it is working perfectly. I've also tried to make a SOAP call on CentOS console trough curl and it also works fine (I get the response). In the web application I keep getting the exception saying that the server returned an invalid or unrecognized response.

This is the code - Exception thrown right on the hc.PostAsync().

            Uri uri = new Uri(ServiceConfiguration.SERVICE_URL);

            string sSOAPResponse = String.Empty;

            HttpClient hc = new HttpClient();

            hc.DefaultRequestHeaders.Add("SOAPAction", oRequest.Action);
            
            var content = new StringContent(oRequest.RequestMessage, Encoding.UTF8, "text/xml");

            try
            {
                using (HttpResponseMessage response = await hc.PostAsync(uri, content))
                {

                    sSOAPResponse = await response.Content.ReadAsStringAsync();
                    (...)
                 }
`

## Steps to reproduce
Call post async method with HttpClient on a Linux Server (CentOS 7.1 My case)

## Expected  behavior
Get the SOAP response (Works perfectly on Windows).

## Actual behavior
The server returned an invalid or unrecognized response thrown.

## Environment data

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64

**Comment by piotrpMSFT** [comment]
Moved to https://github.com/dotnet/corefx/issues/9201
