### ISSUE TITLE
Assemblies built out of CLI should set [assembly:System.Reflection.AssemblyMetadata("Serviceable", "True")]

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#3345]
Any Microsoft assembly that can be loaded on desktop and distributed via NuGet should set this if it wants to be targetable by updates through Microsoft Update.

```
[assembly:System.Reflection.AssemblyMetadata("Serviceable", "True")]
```

I reviewed a few packages on https://dotnet.myget.org/gallery/dotnet-cli and found them lacking.

For more info see https://blogs.msdn.microsoft.com/dotnet/2014/01/22/net-4-5-1-supports-microsoft-security-updates-for-net-nuget-libraries/

FWIW we do this automatically via BuildTools in WCF and CoreFx repos.

**Comment by piotrpMSFT** [comment]
@ericstj I assume this needs to happen for preview2?

**Comment by eerhardt** [comment]
Note this attribute is moved into the nuspec now.  Our build should be calling `dotnet pack --serviceable` when build our packages, and that should take care of everything, right?

Or is there a switch in `project.json` than can be set?

**Comment by ericstj** [comment]
As I mentioned, this is for desktop where there is no host to write breadcrumbs.  The NUSPEC element is for .NET Core and the host which writes package-based breadcrumbs.

In the desktop case it's fusion that writes breadcrumbs based on strong name.  It does so based on this assembly attribute.

**Comment by ericstj** [comment]
@piotrpMSFT it needs to happen before you ship any package that could load in desktop as stable.  Not sure which of the packages from CLI Repo are shipping as stable for Preview 2, but those are the candidates.

**Comment by eerhardt** [comment]
OK - I was just going to ask "are both needed?".  It sounds like the answer to that question is "yes".

`dotnet pack --serviceable` only puts the metadata in the nuspec, AFAIK.

So we need to add the assembly attribute to ProjectModel, DependencyModel and InternalAbstractsions, at a minimum, since they will be loaded in net451.

And we need to add `--serviceable` to `dotnet pack` in our build.

I assume we can just turn both of these flags on for all our assemblies.  Is that OK?  Or is there some detrimental behavior if we turn it on for `preview` assemblies?

**Comment by ericstj** [comment]
We've had it on for CoreFx in pre-release.  Technically it only needs to be on for release builds which you intend to service.
Only downside is the accumulation of pre-release breadcrumbs.

**Comment by sokket** [comment]
@eerhardt when we build CLI, do we run ```dotnet pack``` or just ```dotnet build```? I have added the attribute to the AssemblyInfoOptions and the AssemblyInfoFileGenerator files, I just need to find the entry point that we use to make sure we go down the right path

**Comment by piotrpMSFT** [comment]
@sokket we do both. We first build the binaries, then package them with `dotnet pack --no-build`. Take a look at https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/dotnet-cli-build/PackageTargets.cs#L209.
