### ISSUE TITLE
DTH tests timing out 

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3347]
## Steps to reproduce
Make a PR unrelated to DTH

## Expected  behavior
DTH tests pass

## Actual behavior
DTH tests time out

## Environment data
`dotnet --info` output:
N/A

Example here

http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0-preview2/job/debug_fedora23_x64_prtest/13/

@troydai @eerhardt @livarcocc

**Comment by troydai** [comment]
@brthor can you find me a recent case of such failure?

**Comment by eerhardt** [comment]
6 legs failed here:  https://github.com/dotnet/cli/pull/3388

**Comment by troydai** [comment]
Thanks. I'm starting a PR to test my theory here: https://github.com/dotnet/cli/pull/3389

**Comment by troydai** [comment]
Expanding the timeout to 20 seconds pass all the tests run in first try: https://github.com/dotnet/cli/pull/3389

**Comment by troydai** [comment]
@eerhardt @brthor can you please confirm if the tests are still flaky after #3389 is merged?

**Comment by eerhardt** [comment]
I've only seen good builds so far.  Haven't seen a Dth test failure this morning.

So far, so good.

**Comment by troydai** [comment]
Great. Let's keep this issue open for a few more days.

**Comment by piotrpMSFT** [comment]
Is 20s the worst-case execution time for these tests? Or is it a constant 20s?

**Comment by troydai** [comment]
it's just the worst case. the test execution time won't change if all expected requests are sent.

**Comment by piotrpMSFT** [comment]
can we close this?

**Comment by troydai** [comment]
if no one objects, I'll close this tomorrow morning.
