### ISSUE TITLE
Remove `corehost` from the sdk directory

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3349]
This is dependent on
- [ ] https://github.com/dotnet/cli/issues/2444
- [ ] https://github.com/dotnet/cli/issues/3348

@schellap @eerhardt

**Comment by eerhardt** [comment]
Shouldn't this say `Remove corehost from the shared framework and sdk directories`?  It looks like both `corehost.exe` and `dotnet.exe` are in my shared\Microsoft.NETCore.App\version directory, and `corehost.exe` is in sdk\version.

**Comment by blackdwarf** [comment]
@brthor @eerhardt did we do this?

**Comment by eerhardt** [comment]
@blackdwarf - no.

**Comment by livarcocc** [comment]
I can't find these files in 2.0 anymore. Closing.
