### ISSUE TITLE
Remove PlatformAbstractions usages

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/cli#3356]
Today there are couple places where Microsoft.Extensions.PlatformAbstractions is used.

E.g.
https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/dotnet/MulticoreJitProfilePathCalculator.cs#L35

These can all be replaced by classes not built by ASP.NET Core. The plan is to remove this for RTM on our end.

@davidfowl @piotrpMSFT

**Comment by BrennanConroy** [comment]
Here is the issue on NuGet's side https://github.com/NuGet/Home/issues/2890 I think that's where CLI's dependency comes from

**Comment by muratg** [comment]
cc @Petermarcu, @rrelyea

**Comment by piotrpMSFT** [comment]
@sokket can you take a look?

**Comment by muratg** [comment]
@sokket @piotrpMSFT I think the nuget change is on its way (cc @rohit21agrawal, @rrelyea) so you won't be bringing this transitively once you get that particular nuget build.

**Comment by rohit21agrawal** [comment]
NuGet just finished checking in this work to dev and release-3.5.0-beta2 branches.

**Comment by sokket** [comment]
Looking into this now

**Comment by piotrpMSFT** [comment]
@rohit21agrawal what is the NuGet package version that will have the updated surface area?

**Comment by rohit21agrawal** [comment]
@piotrpMSFT We haven't yet published a NuGet package version with the updated surface area to MyGet. We have it on our internal share - do you need that? Will wait for guidance on publishing packages from @rrelyea on how to coordinate this.

**Comment by piotrpMSFT** [comment]
This will be fixed by https://github.com/dotnet/cli/pull/3443

**Comment by pranavkm** [comment]
Fixed in https://github.com/dotnet/cli/commit/acc5528502699bfb83efe59f220ae62569e3f4ff
