### ISSUE TITLE
An item with the same key has already been added. Key: System.Runtime Unspecified

### ISSUE THREAD

**Issue by JakeGinnivan** [dotnet/cli#3360]
## Steps to reproduce

Install the following Serilog packages into a web project targeting `net451` (from file/new) is fine:

```
"Serilog.Settings.Configuration": "2.0.0-rc-8",
```
## Expected  behavior

A better error message would be handy. There was a bit of trouble figuring out how to fix the issue with in another serilog project. See https://github.com/serilog/serilog-extensions-logging/issues/38
## Actual behavior

Build fails with `An item with the same key has already been added. Key: System.Runtime Unspecified`
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by piotrpMSFT** [comment]
@JakeGinnivan what is the command that produces this error message?

**Comment by livarcocc** [comment]
Closing since we haven't heard back in a long time.
