### ISSUE TITLE
packOptions should have a packageName/outputName property

### ISSUE THREAD

**Issue by simsod** [dotnet/cli#3363]
## Steps to reproduce

if the source files (.cs) are located in \MyProject
and the project.json is located in a subdirectory, like \MyProject\build\project.json
The package filename and .nuspec id is forced to be the folder name, in this case build.1.0.0.nupkg and <id>build</id>
## Expected  behavior

It would be useful to be able to set the filename/id of the output to "MyProject" in this case. Just like you can do with the "buildOptions"."outputName" configuration for the .dll output.
## Actual behavior

The output .nupkg and it´s id in the .nuspec is always set to the folder name, in this case 'build'.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

**Comment by soeron** [comment]
Setting output directory should be available for every step and any configuration of the build process. For the obj folder and for compile output, and it should be respected by the dotnet command and not adding things like in https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/OutputPathsCalculator.cs#L33 and few lines down.

**Comment by blackdwarf** [comment]
Since we are [moving to csproj & MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/), this issue is not applicable anymore. Will close. If you believe this was in error, please reopen.
