### ISSUE TITLE
Is there any way to pack all projects in a folder at once?

### ISSUE THREAD

**Issue by ivaylokenov** [dotnet/cli#3366]
## Steps to reproduce
I have the following projects:

![prsrc](https://cloud.githubusercontent.com/assets/3391906/15781720/19ab3e0e-29b0-11e6-970f-cf5e5f88f127.png)

Each project in the `src` folder should be packed as a NuGet package. The `MyTested.Mvc` one has all the others as dependencies.

## Expected  behavior

When I run `dotnet pack --configuration Release` on the `MyTested.Mvc` folder I expect to receive the packed NuGet packages for all dependencies. 

## Actual behavior

When I run `dotnet pack --configuration Release` on the `MyTested.Mvc` folder I receive the packed NuGet package only for that project and not for the dependencies. I need to manually go through all of the packages and run the command.

![build](https://cloud.githubusercontent.com/assets/3391906/15782016/4c1f793a-29b1-11e6-82cf-fa28d763ec9c.png)

## Environment data
.NET Command Line Tools (1.0.0-preview1-002702)

Is there any way to pack the whole solution or only the `src` folder with a single command?

**Comment by ivaylokenov** [comment]
I solved the problem by adding these lines to each `.xproj` file:

```
  <Target Name="AfterBuild">
    <Exec Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" Command="dotnet pack --configuration Release --output ../../artifacts --no-build"/>
  </Target>
```

Still it would be nice to have a built-in solution, because when I add new project, I need to add the above lines manually every time.

**Comment by eerhardt** [comment]
It seems like `dotnet pack` should allow for file globbing, just like `dotnet build` does:

`dotnet pack src/**/project.json` would pack all projects under the `src` folder.

Looking at the code, it looks like `build` supports this, but `pack` doesn't.

**Comment by piotrpMSFT** [comment]
@ivaylokenov has resolved the issue in this bug. I've also opened https://github.com/dotnet/cli/issues/3409 to track the more general `glob all the verbs` concern.
