### ISSUE TITLE
Dotnet and AssemblyInfo.cs

### ISSUE THREAD

**Issue by patrickjamesbarry** [dotnet/cli#3367]
What is the direction for dotnet in relation to AssemblyInfo.cs.  

- Does the need for this class go away?
- Will the entire class get generated on the fly with values provided in project.json/new csproj?
- Will values be automatically inserted into it, if it remains?
- Do I need to provide replacement tokes inside of the class for values that can be provided by project.json/new csproj?

**Comment by blackdwarf** [comment]
@patrickjamesbarry these are good questions. At this point, we are still working through the details of how the alignment towards msbuild and the new csproj project format will work and how will it look, so we don't have a crystal clear answer for these questions. When we have more data we will share, so stay tuned.
