### ISSUE TITLE
Make CI Build NuGet Cache Independent

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3368]
Today our CI build nuget cache is placed in the parent directory of the CI workspace to prevent it from being wiped out in each build to save on caching time. 

This presents multiple issues:
1. If two builds are running on the same machine, with the same number of commits in each build, there is a race condition in the cache as to which version of the packages produced in the build will be present in the cache. This will (and likely is) cause test instability, and overall inexplicable failures.

2. If a build has previously run with the same commit count, it's possible the cache will not be re-hydrated with new packages and tests may be run against old packages (from some PR) with unknown bits.

3. This same method is shared by the Core-Setup repo so number 2 also applies to nuget packages in that repo (Microsoft.NETCore.App).

To solve this we should make the nuget cache of each build independent to that build. Cleaning the cache of each package the build produces at the beginning of the build is not sufficient to solve number 1.

cc @eerhardt @livarcocc @piotrpMSFT

**Comment by brthor** [comment]
Fixed in https://github.com/dotnet/cli/pull/3370

**Comment by piotrpMSFT** [comment]
Fixed in #3370
