### ISSUE TITLE
dotnet build needs to support nuget fallback package folder

### ISSUE THREAD

**Issue by rrelyea** [dotnet/cli#3372]
to work in concert with: https://github.com/NuGet/Home/issues/2899, dotnet build will need to understand the fallback package folder, and look at it after the nuget package folder, and before the app and shared framework.
@ericstj

**Comment by piotrpMSFT** [comment]
@livarcocc @ericstj is this a preview2 issue?

**Comment by schellap** [comment]
Cc @muratg CLI side of work is tracked by this issue.

**Comment by ericstj** [comment]
I believe NuGet is trying to land this for preview2.  We essentially need all commands that evaluate package paths to consider an additional path when evaluating the packages folder here: https://github.com/dotnet/cli/blob/18f9018eb9a5ea100b65170adc25f3ad6752dd2e/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L159

We probably wouldn't even need to do anything if CLI and NuGet didn't have different project models.

**Comment by muratg** [comment]
cc @rohit21agrawal

**Comment by piotrpMSFT** [comment]
Just left a note on the associated NuGet issue. We are waiting on an API in NuGet that can be invoked to obtain a resolved path to an asset. CLI should not be duplicating NuGet's path resolution logic.

**Comment by jchannon** [comment]
Does this relate to if you do a `dotnet restore --packages mynugetdir` and then a `dotnet build` it fails to find the dependencies?

**Comment by eerhardt** [comment]
Actually, I'm pretty sure this feature will fix that scenario. The current design of this feature is to put the "package paths" used into the `project.lock.json` file.  That way `dotnet build` can later find where the packages were restored to.

/cc @emgarten - in case I am missing anything.

**Comment by jchannon** [comment]
I think this highlights the issue too https://github.com/dotnet/cli/issues/2712

**Comment by eerhardt** [comment]
Fixed by a48def9adec26fdc1a9b80efc4d82013156f2884.
