### ISSUE TITLE
Update JSON.NET to 9.0.1

### ISSUE THREAD

**Issue by javiercn** [dotnet/cli#3377]
It has support for NetStandard and allows to remove imports from project.json, we want to update ASP.NET to use it, but it is causing issues with our test runner.

**Comment by javiercn** [comment]
@Eilon @pranavkm

**Comment by Eilon** [comment]
@piotrpMSFT can you have someone take a look at this today? Thanks!

**Comment by sokket** [comment]
Looking now

**Comment by sokket** [comment]
Running a local build + test of the changes

**Comment by sokket** [comment]
Fixed, closing the issue
