### ISSUE TITLE
Get a warning when referencing a package that has a inbox facade on desktop

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#3381]
## Steps to reproduce

Create a project with the following:

```
  "dependencies": {
    "NETStandard.Library": "1.6.0-rc3-24201-00",
    "System.Linq.Parallel": "4.0.1-rc3-24201-00"
  },
  "frameworks": {
    "net45": {},
    "netstandard1.3": {}
  },
```

Restore it, works fine, no warnings.  Build it.
## Expected  behavior

No warnings
## Actual behavior

warning NU1007: Dependency specified was System.Linq.Parallel >= 4.0.1-rc3-24201-00 but ended up with System.Linq.Parallel 4.0.0.0
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-002877)

Product Information:
 Version:            1.0.0-preview2-002877
 Commit SHA-1 hash:  a365414f01

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

/cc @davidfowl @piotrpMSFT

**Comment by piotrpMSFT** [comment]
The check that produces NU1007 is here: https://github.com/dotnet/cli/blame/e68a49e1d52bb4f85f63192d95598e559da1af33/src/Microsoft.DotNet.ProjectModel/Resolution/LibraryManager.cs#L116

@davidfowl can you look at the logic and propose a fix?

**Comment by onovotny** [comment]
Is this still on-track to be fixed for GA on the 27th?

**Comment by blackdwarf** [comment]
This is fixed in the latest tooling. Just tried it and build did not throw this error. Will close, please reopen if it repros on the latest tooling.
