### ISSUE TITLE
How to Enable Randomized Hashes

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/cli#3382]
How can I enable [randomized hashes](https://msdn.microsoft.com/library/jj152924.aspx) in an xproj project. Normally done like so:

```
<?xml version ="1.0"?>
<configuration>
   <runtime>
      <UseRandomizedStringHashAlgorithm enabled="1" />
   </runtime>
</configuration>
```

Do I use the web.config file? Do I use the `runtimeOptions` section of project.json? Is this setting available and working for .NET Core? Lots of questions about this obscure setting.

**Comment by davidfowl** [comment]
Are you asking specifically about .NET Core?

**Comment by RehanSaeed** [comment]
Both .NET Core and .NET Framework in an xproj project using project.json.

**Comment by tarekgh** [comment]
@RehanSaeed UseRandomizedStringHashAlgorithm is already enabled by default in net core so you don't have to do anything to enable it there. for the full/desktop framework, you can use the config file to enable it.

**Comment by piotrpMSFT** [comment]
Thanks @tarekgh !
