### ISSUE TITLE
Adding a file resource to a resx doesn't work as expected

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/cli#3383]
## Steps to reproduce
Create a new project, class library (.netcore).
Add a Resources.resx to the project.
Add a file TestResource.txt to the file, containing "test text".
Open the Resources.resx file.
Select Files from the resource type dropdown.
Drag the TestResource.txt file into the resx designer.
Compile.
Inspect the compiled assembly (ilspy).

## Expected  behavior
The compiled resource contains a name = "TestResource" with value = "test text".

## Actual behavior
The compiled resource contains a name = "TestResource" with value = "TestResource.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8"

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
moved this bug to aspnet/tooling repo
