### ISSUE TITLE
dotnet build with glob throws NRE

### ISSUE THREAD

**Issue by MartinJohns** [dotnet/cli#3392]
## Steps to reproduce

Project layout:
- /src/projectA/project.json
- /src/projectB/project.json

Current folder: **/** (solution root)
Command: dotnet build src/**
## Expected  behavior

Locates all `project.json` within the `src` folder and builds the projects. Ignores not `project.json` files.
## Actual behavior

Error message:
`Object reference not set to an instance of an object.`

Probably because the glob matches non project.json files.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
This usage of globbing is not supported in CLI. However, we do need to fix the error message. 

We do need coverage for this scenario, but it's not on the immediate roadmap.

**Comment by MartinJohns** [comment]
> This usage of globbing is not supported in CLI.

It is not? It seemed to work when using `src/**/project.json`.

**Comment by jasonwilliams200OK** [comment]
I can confirm that `dotnet build **/project.json` works just fine and builds all the projects in the nested directories on Unix and Windows. Globing is definitely supported.

**Comment by MartinJohns** [comment]
@piotrpMSFT Since you say it's not supported in the CLI, yet it works.. Could you provide a link to the specifications of the CLI that describes what it **should** support?

**Comment by dsparkplug** [comment]
Note that the command line help says that it does support "globbing patter":

```
>dotnet build --help
.NET Builder

Usage: dotnet build [arguments] [options]

Arguments:
  <PROJECT>  The project to compile, defaults to the current directory. Can be one or
multiple paths to project.json, project directory or globbing patter that matches project.json files
...
```

**Comment by piotrpMSFT** [comment]
`dotnet build` atop msbuild no longer accepts globs. Instead, we're using sln files to allow coorinating actions atop multiple projects.
