### ISSUE TITLE
dotnet pack --no-compile

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#340]
DotNet pack issues `dotnet compile` by default. Convenient by default, this prevents the implementation of some key post-compile scenarios like signing and localization. The --no-compile flag allows users to opt-out of compilation, allowing them to manipulate the binaries before creating a package.

**Comment by Petermarcu** [comment]
Will we teach publish and pack to pick up localized or signed binaries from alternate paths? Ideally we wouldn't have to modify them in place to then have them picked up by a later stage.

**Comment by davidfowl** [comment]
Why does that need to be a flag? If you want control then just call dotnet compile and then nuget pack. I'm not a fan of decoupling the commands from themselves.

**Comment by piotrpMSFT** [comment]
@davidfowl are you suggesting that localize & sign are things that pubish/pack do in addition to compiling? The current coupling is already causing grief. I'd like to enable postcompile to call pack so folks don't need to remember to regenerate nuget packages in their developer cycle. This is impossible, since it is recursive. compile --> pack --> compile --> pack... It'd be unfortunate to stop using the product to build itself, but remembering to pack some projects is also a big pain.

**Comment by davidfowl** [comment]
What do you mean? Those things are already part of compile (generating resource assemblies needs to be added). What exactly is causing grief where?

**Comment by piotrpMSFT** [comment]
I think there is a difference in expectation around the compile verb. Compile seems to be becoming "do everything to prepare this project for publish/pack". There is another responsibility, "find the right compiler, prepare a rsp file for it, and invoke it", that got pulled in. Invoking the compiler directly is not a good option because it forces folks to re-build all the logic in compile for selecting the compiler and prepping the rsp file. If we tease these responsibilities apart then the grief will go away.

**Comment by davidfowl** [comment]
Thats the point of this tool though. Teasing apart the responsibilities is fine and you can always call each tool if you want to feel all the pain. The point of this tool is to be extremely opinionated about a specific vertical and not allow that vertical to be infinitely configurable.

**Comment by piotrpMSFT** [comment]
Yea, but decomposability is a goal. We need to be able to call compilers without calling all the other stuff. Need a new verb for that one.

**Comment by livarcocc** [comment]
@piotrpMSFT @davidfowl 

We are feeling the need for this flag (or something like it) for the authenticode sign work. Because of compile being invoked by pack immediately before creating the packages, we don't have an opportunity to authenticode sign these binaries, or point pack to signed binaries. What if we added a path to the binaries directory? We could just point to wherever the signed binaries are placed.

Given that, what is the downside of adding such thing?
