### ISSUE TITLE
CLI Windows Installer Title/ARP string still uses `Preview1`

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#3400]
## Steps to reproduce
Run Windows Installer

## Expected  behavior
Product name in title, install UI, ARP, should read 'Preview2'

## Actual behavior
Product name in title, install UI, ARP, reads 'Preview1'

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-002973)

Product Information:
 Version:            1.0.0-preview2-002973
 Commit SHA-1 hash:  512287ec03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@blackdwarf

**Comment by brthor** [comment]
This probably needs to change across all the installers, I will look into it.

**Comment by brthor** [comment]
Fixed in #3464
