### ISSUE TITLE
CLI Windows Installer shows "Dotnet CLI with Signing (Windows) [x64] [rel.1.0.0-preview2] 20160604.2"

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#3401]
## Steps to reproduce
Run the Windows installer and examine `User Account Control` UI

## Expected  behavior
Program Name is `Microsoft .NET Core 1.0.0 RC2 - SDK Preview 2 (x64)`

## Actual behavior
Program Name is `Dotnet CLI with Signing (Windows) [x64] [rel.1.0.0-preview2] 20160604.2`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-002973)

Product Information:
 Version:            1.0.0-preview2-002973
 Commit SHA-1 hash:  512287ec03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment]
That is a weird one. 

Do we want to include the build number in the program name?

**Comment by piotrpMSFT** [comment]
@blackdwarf

**Comment by blackdwarf** [comment]
@brthor nope, .NET Core's next release (the runtime) is RTM. This *is* weird. We should match the product's name and I don't think that the build number in UAC is required.

**Comment by brthor** [comment]
To confirm, this is what the string should be?
`Microsoft .NET Core 1.0.0 RTM - SDK Preview 2 (x64)`

**Comment by blackdwarf** [comment]
Working on it. Need to get the official branding stuff. Based on what I currently know the "RTM" in the string above is not needed.

**Comment by brthor** [comment]
To confirm, this is what the string should be?
`Microsoft .NET Core 1.0.0 - SDK Preview 2 (x64)`

**Comment by brthor** [comment]
FYI to all this is controlled in the Signing step of our VSO definition so we'll need to have the value hard coded there, which sucks, but not much way around it.

**Comment by brthor** [comment]
I've created the `ProductMoniker` build variable which can be editted. Going to wait for a new build before closing this out.

**Comment by brthor** [comment]
Since this is controlled per branch I have only editted definitions for preview2 in cli and rtm in core-setup. 

Please comment on what you'd expect this value to be for `rel/1.0.0` and `master` @blackdwarf

**Comment by piotrpMSFT** [comment]
@brthor is this something we can add tests for? Since the configuration sits in CI we don't have a clean model to prevent humans from forgetting to make updates.

**Comment by brthor** [comment]
I imagine this name sits somewhere in the PE file metadata and we could add a test to verify it. It would take some time to figure out where and how.

Also, we would be adding a class of tests that only run in VSO, which I think is fine.

**Comment by brthor** [comment]
This is fixed, closing this out. Let's open another issue for the tests. I don't see them making it in Preview2
