### ISSUE TITLE
Provide `matching` Shared Framework Deb link in Readme.md

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#3416]
The download links in Readme.md point to the `latest` available installers for all components. Since the Shared Framework builds independently of the CLI, the `latest` Shared Framework is sometimes newer than that which `dotnet new` references in the `latest` CLI. This is typically invisible since folks will use a bundled installer for Mac and Windows. In the case of Ubuntu, however, where users must install all three installers separately, this is an issue because the versions are out of sync.

We should provide a fourth row in the Debian download links to point to the Shared Framework that matches the CLI installer. This will require having a separate channel whose latest matches the latest of CLI.

**Comment by brthor** [comment]
this is required to fix #3320

**Comment by bitcrazed** [comment]
Is there a reason a [PPA](https://help.launchpad.net/Packaging/PPA/InstallingSoftware) can't be created for .NET, ASP.NET, etc. on Ubuntu making installation as simple as `apt-get install dotnet-cli` or similar, as per #2844

**Comment by brthor** [comment]
Hey @bitcrazed We do indeed have a debian feed although not a PPA. 

See https://www.microsoft.com/net/core#ubuntu

There is no reason we couldn't do that, it just hasn't been done yet.

**Comment by bitcrazed** [comment]
It's be awesome to have a PPA; would be great to just be able to use apt 😜

**Comment by brthor** [comment]
You can use apt now no?

What are the primary benefits you see?

**Comment by bitcrazed** [comment]
Ugh! My bad - you're right - looks like builds are already being published to the PPA described in step 1 [here](https://www.microsoft.com/net/core#ubuntu).

However, when I try to install `dotnet-dev-1.0.0-preview2`, I see the following error:

    dotnet-dev-1.0.0-preview2-003072 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc3-004459-00 but it is not installable

... closely followed by ...

    Package dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc3-004459-00 is not available, but is referred to by another package.

Are the Preview2 builds still a work in progress?

**Comment by brthor** [comment]
@bitcrazed We had some issues with preview2 debs in the last day or so. The new builds are installable like so:

`apt-get install dotnet-dev-1.0.0-preview2-003093`

**Comment by bitcrazed** [comment]
WOW WOW WOW! I am so beyond ecstatic to see this! :) 

**Net Core now installs and runs on Bash on Ubuntu on Windows!!!**

Many thanks to all for piling-on and fixing this and related issues 💯 😎 😃 

![2016-06-18](https://cloud.githubusercontent.com/assets/961950/16173331/253b5fc0-3553-11e6-93cd-5d55d547c1f2.png)

**Comment by brthor** [comment]
Nice that's awesome!

**Comment by piotrpMSFT** [comment]
looks like this should have been closed 6 mths ago :D
