### ISSUE TITLE
Platform dependencies not differentiated in lock file

### ISSUE THREAD

**Issue by onovotny** [dotnet/cli#3418]
## Steps to reproduce
Create a new project that includes a dependency of type `platform`. Run nuget restore/dotnet restore to create the lock file.

## Expected  behavior
The dependency type in the lock file should be `platform`

## Actual behavior
The dependency type is `package`.

This loses information from the `project.json` and makes it harder for tools that need to know the difference.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14352
 OS Platform: Windows
 RID:         win10-x64

**Comment by onovotny** [comment]
Ditto with `build` dependencies. In the lock file, they also show up as `package`. I need that information to be expanded/carried along with transitive refs.

**Comment by brthor** [comment]
Thanks for the bug @onovotny we've run into this one before. 

This is tracked in nuget here:
https://github.com/NuGet/Home/issues/2695

And also see previous discussion here:
https://github.com/dotnet/cli/issues/2760

Going to close out as a dupe. Recommend adding the concern for `build` type dependencies to that nuget issue.
