### ISSUE TITLE
dotnet-test

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#342]
dotnet-test
===========

**NAME** 
dotnet-test -- Runs tests in a project using configured test runner.

**SYNOPSIS**
dotnet test [options]

**DESCRIPTION**
The test command identifies a test runner to use based on project.json and uses that runner to execute tests in the library. The test runner is specified in the TestRunner property of project.json

```json
{ 
    "TestRunner": "xunit"
}
```

The test runner is resolved into a command name using the template dotnet-test-{TestRunner}. The runner command can be found either on the PATH or in a referenced NuGet package.

This command relies on the following artifacts: source files, project.json project file, project.lock.json temporary file and restored NuGet dependencies. 

**Options**
-v, --verbose
Prints verbose logging information, to follow the flow of execution of the command.

**Comment by krwq** [comment]
I like it! :+1: My only concern is who should be responsible for knowing what values can be typed in TestRunner? Let's say I want to write my own fancy build system: how do I know what to do with value "xunit"

**Comment by blackdwarf** [comment]
@piotrpMSFT  not bad. Some questions:

* What is the Nuget package thing you mention above? Is that a new way of finding commands? I wasn't aware of that.
* What happens if no command is found? I assume failure, but would be good to document that as well.
* Will the tests themselves be compiled automatically or does this command imply `dotnet compile` on the test source files? 

@krwq I assume your fancy build system would actually know to try and launch the `dotnet-test-xunit` command. As far as responsibility, I would say that it is a job of the project.json author, no?

**Comment by bricelam** [comment]
What value does this command add over just calling (for example) `xunit.console bin/Debug/net45/MyTests.dll`?

**Comment by piotrpMSFT** [comment]
@krwq the runner author specifies their own string. We need to solve lookup for both test runners and for compilers.

@blackdwarf take a look at #341. It enables dotnet.exe to find and prefer commands in referenced nuget packages over PATH. Necessary for specifying per-project runners as was done in VS.

@blackdwarf we need to think about failure cases all up.

@blackdwarf currently this assumes pre-reqs are done. We'll make a policy decision here.

@blackdwarf @krwq project.json lists the TestRunner to use.

@bricelam there are several value adds:
* project.json can be used to specify the runner, so no need for identifying per-project commands
* Combined with looking up commands in NuGet packages, the right flavor of runner is selected automatically [dnxcore50 vs. dnx451 as an example] ensuring tests run vs. the runtime they were compiled for
* IDE integration. IDE calls `dotnet test` and this Command automatically starts the runner in --designtime mode and opens a socket by which to communicate with the IDE.
