### ISSUE TITLE
Hosting Environment not detected

### ISSUE THREAD

**Issue by avikenjale** [dotnet/cli#3420]
I am using Visual Studio code to develop a ASP.NET Core MVC app. I made necessary changes and it application is running fine thru command line. However when I see default it is showing `Hosting environment: Production` . So I added `properties\launchSettings.json` file with following properties
````    
{
  "profiles": {   
    "WebApplication1": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "Hosting:Environment": "Development"
      }
    }
  }
}
````

## Expected  behavior
- This Suppose to change  `Hosting environment: Production` to  `Hosting environment: Development` when command run as `dotnet run`. 

## Actual behavior
However it is still shows  `Hosting environment: Production`.
I tried to change port from 5000 to some other number, but still shows 5000.

I think either `launchSettings.json` is not deteciting - hooked-up or something else is missing.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by piotrpMSFT** [comment]
@danroth27 @sayedihashimi can you help route this to the appropriate repo?

**Comment by sayedihashimi** [comment]
The launchSettings.json is a Visual Studio file. It's used to set environment variables and to configure what gets launched when you F5 in Visual Studio.

**Comment by avikenjale** [comment]
Then, what if I need to apply or change environment variables where I don't have Visual Studio or suppose on Ubuntu?Just I need to change default port from 5000 to something else or hosting environment from Production to Development or Staging ?

**Comment by sayedihashimi** [comment]
@avikenjale here are some links on setting environment variables in the command prompt [linux](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps) and [windows](http://superuser.com/a/79614).

**Comment by piotrpMSFT** [comment]
Thanks @sayedihashimi

**Comment by piotrpMSFT** [comment]
If folks run into other tooling-related issues, including launchSettings.json issues, please do open those in https://github.com/aspnet/tooling repo so we have the right folks look at it ASAP
