### ISSUE TITLE
 Change dotnet build to create portable pdbs by default

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#3422]
The current experience for VS Code users is not ideal for debugging when running on Mac/Linux because you cannot step into a break point until you update `project.json` to produce portable pdbs by default.

When `dotnet build` is executed it should produce portable pdbs by default if it's not already configured in `project.json`.

Related to #3421

**Comment by piotrpMSFT** [comment]
Why is 1.1 the right milestone here? If we mean Runtime 1.1, that will likely map to CLI preview3 or RTM.

**Comment by sayedihashimi** [comment]
I may not have set the right milestone, please update if I got it wrong.

**Comment by smbecker** [comment]
My vote would be to not do this. Changing to portable pdbs caused issues debugging in Visual Studio on Windows. I get that you want to enable cross-platform but a large majority of developers still use Visual Studio.

**Comment by eerhardt** [comment]
> Changing to portable pdbs caused issues debugging in Visual Studio on Windows

Can you elaborate on the issues? Also, shouldn't we be fixing those issues in Visual Studio?

**Comment by smbecker** [comment]
Stack traces never include line numbers of source files and locals and immediate windows were incredibly flakey.

I agree that those should be fixed in VS but until they are...

**Comment by livarcocc** [comment]
Our templates are using portable pdbs by default.
