### ISSUE TITLE
dotnet-pack does not update AssemblyInformationVersion if inputs have already been compiled

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#3424]
## Steps to reproduce
1. `dotnet new`
2. `dotnet pack --version-suffix beta1`
3. `dotnet pack --version-suffix beta2`
## Expected  behavior

The AssemblyInformationalVersion assembly attribute in the "beta2" nupkg should be set to "1.0.0-beta2".
## Actual behavior

dotnet-pack did not recompile because the project was built by the first pack, so it produces a nupkg "beta2" where AssemblyInformationalVersion  is set to "beta1"
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-002990)

Product Information:
 Version:            1.0.0-preview2-002990
 Commit SHA-1 hash:  54cd31b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@cdmihai can you look at this in preview3?

**Comment by onovotny** [comment]
Either that or don't use dotnet pack. DotNet pack cannot filter out granular references after using `netstandard.library`. I'd recommend using a nuspec and then the 2.0 version of my Reference Generator tool -- which does handle creating the granular dependency list. Also then with a nuspec, you can do whatever you want.

**Comment by cdmihai** [comment]
I remember @anurse doing a PR where he added the command line (the value for `--version-suffix` portion of it) to the incremental state, so that build would rebuild when `--version-suffix` changes. This means that dotnet pack is not propagating all the relevant flags to build?

**Comment by anurse** [comment]
Indeed, I did add that to the incremental cache data. As long as `pack` is passing along the flag, it should be triggering a rebuild.

**Comment by livarcocc** [comment]
This should be fixed in the new pack command.

**Comment by blackdwarf** [comment]
This is indeed fixed in the pack command. I cannot get it to repro. Closing.
