### ISSUE TITLE
Update the version of DiaSymReader to 1.0.8-rc2-60606-01

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#3430]
According to `the matrix`, the current consumable build of DiaSymReader packages are:

* Microsoft.DiaSymReader 1.0.8-rc2-60606-01
* Microsoft.DiaSymReader.PortablePdb 1.1.0-beta1-60606-02
* Microsoft.DiaSymReader.Native 1.4.0-rc

Testing.Abstrations uses an older version (https://github.com/dotnet/cli/blob/0b30b148f326dfbeeb45692a06a7d258e2fc08ad/src/Microsoft.Extensions.Testing.Abstractions/project.json#L14) which is not netstandard compatible.

**Comment by eerhardt** [comment]
Isn't this already fixed with this PR:

https://github.com/dotnet/cli/pull/3414

@pranavkm - the link you specified doesn't have the latest code.  See:  https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/Microsoft.Extensions.Testing.Abstractions/project.json#L14

**Comment by eerhardt** [comment]
I'm closing as this is already fixed.  Please re-open if you feel it isn't.

**Comment by pranavkm** [comment]
:+1:
