### ISSUE TITLE
Output of dotnet-cli-build is mangled on Ubuntu

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3431]
I'm building CLI on Ubuntu 14.04 from source. After build scripts are compiled, I start seeing mangled output:

```
Invoking Build Scripts...
Configuration:

uilding .NET Core CLI  *
****************************
arget Package from Standard Goals was overridden in Microsoft.DotNet.Cli.Build.PackageTargets.Package
arget Prepare from Standard Goals was overridden in Microsoft.DotNet.Cli.Build.PrepareTargets.Prepare
arget Compile from Standard Goals was overridden in Microsoft.DotNet.Cli.Build.CompileTargets.Compile
arget Publish from Standard Goals was overridden in Microsoft.DotNet.Cli.Build.PublishTargets.Publish
arget Test from Standard Goals was overridden in Microsoft.DotNet.Cli.Build.TestTargets.Test
GET     >]
          efault                                              icrosoft.DotNet.Cli.Build.PrepareTargets.GenerateVersions
GET     >]enerateVersions
C       >]it "rev-list" "--count" "HEAD"

C       <] ] it "rev-list" "--count" "HEAD" exited with 0

C       >]it "rev-parse" "HEAD"

C       <] ] it "rev-parse" "HEAD" exited with 0
race Branch Info:
race  MAJOR_VERSION = 1
race  MINOR_VERSION = 0
race  PATCH_VERSION = 0
race  RELEASE_SUFFIX = preview3
race  CHANNEL = rel-1.0.0
nfo  Building Version: 1.0.0.002979 (NuGet Packages: 1.0.0-preview3-002979)
nfo  From Commit: 0b30b148f326dfbeeb45692a06a7d258e2fc08ad       icrosoft.DotNet.Cli.Build.PrepareTargets.GenerateVersionsT     <] ] enerateVersions                                  icrosoft.DotNet.Cli.Build.PrepareTargets.CheckPrereqCmakePresent  >]heckPrereqCmakePresent

C       >]make --version

C       <] ]
```

Notice for example that what should be `Target` is just `arget` and what should be `[TARGET     >]` is `GET     >]`.

When I invoke `./build_projects/dotnet-cli-build/bin/dotnet-cli-build` manually, the output is the same.

When I save the output to a file, I can see it contains many ESC characters, which seem to be part of the problem.

[The output.](https://gist.githubusercontent.com/svick/9e5c1d3b6e605d9ac3ebb1ea40b43900/raw/a51a6ac3eff87c7ac2963748919cee4ef27863b5/build.log)

Displayed in vim:

![](http://i.imgur.com/dnpgzg7.png)

**Comment by piotrpMSFT** [comment]
@brthor any ideas? I've not seen this in our Ubuntu 14.04 builds...

**Comment by brthor** [comment]
I only see this on docker, but I do see it there all the time. 

I don't have too many ideas here because our build scripts don't use a streamforwarder. There could be something awry in the event handlers being used to capture the output. It would take some investigation.

**Comment by svick** [comment]
There's something strange going on in `AnsiConsole.Write`. I think this might be caused by https://github.com/dotnet/corefx/issues/9202.
