### ISSUE TITLE
dotnet run doesn't echo Console.ReadLine() as typed and doesn't show colours

### ISSUE THREAD

**Issue by jpsingleton** [dotnet/cli#3434]
## Steps to reproduce
Run a console app that uses `Console.ReadLine()` and changes `Console.ForegroundColor`, with `dotnet run`.

## Expected  behavior
Should behave the same as running via `dotnet MyApp.dll`, echoing input as typed and showing colours.

## Actual behavior
Doesn't show console input until a newline is typed and all text is monochrome.

Tested on zsh and bash on OS X 10.11.5.

Related issues (couldn't find anything exactly matching this problem):
 - https://github.com/dotnet/cli/issues/2976
 - https://github.com/dotnet/cli/issues/2777
 - https://github.com/dotnet/cli/issues/2775
 - https://github.com/dotnet/corefx/issues/8950
 - https://github.com/dotnet/corefx/issues/8184
 - https://github.com/dotnet/corefx/issues/8183

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by jpsingleton** [comment]
Also an empty `Console.WriteLine();` does nothing and no blank line is output.

I've not tried [the latest preview](https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-dev-osx-x64.latest.pkg) as it's not signed, but this might be fixed in that.

**Comment by svick** [comment]
Empty lines not being printed is #2234.

**Comment by jpsingleton** [comment]
Thanks, empty lines do work if you run the DLL directly, same as the other issues.

**Comment by brthor** [comment]
@jpsingleton Please try this with one of the latest preview2 installers. @eerhardt put in a fix for this, and I'm not sure it made it into preview1

**Comment by jpsingleton** [comment]
OK, I'll have a go when I find some time, but I'll have to disable gatekeeper. It would be nice if the previews were signed.

**Comment by jpsingleton** [comment]
This all seems to work fine in preview 2 (read line echo, colours and empty lines).

BTW you can ctrl-click/right-click the installer package and select open to get the option to run it without fully disabling gatekeeper.

**Comment by brthor** [comment]
@jpsingleton What platform are you on? Preview MSIs are indeed signed.

**Comment by jpsingleton** [comment]
:arrow_up: OS X 10.11.5

The released pkg is signed but the latest pkg is not.
