### ISSUE TITLE
Publishing to ~/foo on Linux does not expand ~

### ISSUE THREAD

**Issue by vkichline** [dotnet/cli#3438]
## Steps to reproduce
On Mint Linux, cd to a dotnet asp project and enter `dotnet publish --output "~/foo"`

## Expected  behavior
"foo" directory is created in my home directory and published files go there.

## Actual behavior
A directory named "~" is created in the current directory, "foo" is created in it, and publication continues.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by brthor** [comment]
Is there an api available in .NET Core for expanding the `~` character? Something similar to https://docs.python.org/2/library/os.path.html#os.path.expanduser

I was looking for this a couple other times.  @ellismg

**Comment by ellismg** [comment]
I do not know of one.

**Comment by glennc** [comment]
Is `~` not being expanded by the shell because it is in quotes?

**Comment by mellinoe** [comment]
> Is ~ not being expanded by the shell because it is in quotes?

Yeah, it's probably this. I'm not sure this is actually a bug. For example, if I run `mkdir "~"`, a directory named "~" is created in the current directory. It's a valid folder name.

**Comment by glennc** [comment]
So theoretically removing the quotes would get the desired behavior....

**Comment by brthor** [comment]
`dotnet publish --output ~"/path with/spaces"` should work as well if you need spaces

**Comment by livarcocc** [comment]
indeed. dotnet publish -o ~/foo works as expected. It expands the ~.
