### ISSUE TITLE
dotnet build on a Standalone TestApp drops no hostpolicy.dll

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3440]
## Steps to reproduce

`dotnet new`

change project.json to a standalone test app like:

```
{
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.4",
        "portable-net451+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": "1.0.0-rc3-*",
        "Newtonsoft.Json": "9.0.1-beta1",
        "xunit": "2.1.0",
        "xunit.netcore.extensions": "1.0.0-prerelease-00206",
        "dotnet-test-xunit": "1.0.0-rc2-192208-24"
      }
    }
  },

  "testRunner": "xunit",

  "runtimes": {
    "win7-x64": {},
    "win7-x86": {},
    "win8-x64": {},
    "win8-x86": {},
    "win81-x64": {},
    "win81-x86": {},
    "win10-x64": {},
    "win10-x86": {},
    "osx.10.10-x64": {},
    "osx.10.11-x64": {},
    "ubuntu.14.04-x64": {},
    "ubuntu.16.04-x64": {},
    "centos.7-x64": {},
    "rhel.7.2-x64": {},
    "debian.8-x64": {},
    "fedora.23-x64": {},
    "opensuse.13.2-x64": {}
  }
}
```

 (On Windows 10)
`dotnet build --framework netcoreapp1.0 --runtime win10-x64 --output bin`

look in `./bin`
## Expected  behavior

See `hostpolicy.dll`
## Actual behavior

No host artifacts present
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-002913)

Happens on all platforms.

**Comment by brthor** [comment]
@schellap @eerhardt @livarcocc @piotrpMSFT @sokket

**Comment by livarcocc** [comment]
There is no emitEntrypoint: true. Why would you expect an exe in this case?

**Comment by brthor** [comment]
That's a fair point I overlooked, let me test with that, if I get host artifacts will close out.

**Comment by brthor** [comment]
Yup, thanks @livarcocc

**Comment by brthor** [comment]
Updated to reflect discussions around this. Standalone test app scenarios will be going away.

For now the workaround is to place `emitEntryPoint: True`

**Comment by GuardRex** [comment]
@brthor 

> Standalone test app scenarios will be going away.

Could you clarify what that means?
