### ISSUE TITLE
Replacing multiple repositories with source doesn't work

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#3444]
This is a bit hard to explain so I used my (ahem) awesome (ahem) Paint skills to draw it.

If you reference two projects from two different repositories, as sources instead of packages, and one of them references the other you'll not get all packages replaced with sources

To repro:

1. Clone https://github.com/aspnet/options
2. Clone https://github.com/aspnet/configuration (note: Options references Configuration)
3. Create an application that references: `Microsoft.Extensions.Options.ConfigurationExtensions`
4. Change the `global.json` of that application to reference:

          ["src", "<pathOptions>/src", "<pathConfiguration>/src"]

Build and run the application created at step 3. See the loaded modules.

Expected: 
Since I'm referencing options and configuration, I would expect the packages to be replaced with source for both of them.

Actual:
I've seen two outcomes:
1. Sometimes I get one of them replaced with sources and the other not
2. Other times I get an exception: `error: An item with the same key has already been added. Key:`

Now, if you add an explicit reference in options to configuration (in global.json) everything works.

![untitled](https://cloud.githubusercontent.com/assets/5921642/15914654/8cc62364-2d97-11e6-9900-a0d67e53ddd2.png)

PS: There's a typo in the drawing. The green text should have `<configuration>` not `<options>`

**Comment by piotrpMSFT** [comment]
Nice one!

**Comment by livarcocc** [comment]
Well, in MSBuild you will have to reference the projects directly. So, this won't be an issue.
