### ISSUE TITLE
dotnet restore --packages is confusing.

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#3447]
The existence of this argument suggests to the user that by telling the CLI where to put packages, builds for the project(s) being restored will use the packages from that location. 

@eerhardt points out in #3315 how the algorithm actually works. I can't find any other documentation about how the CLI finds your Nuget dependencies. 

This leaves me to wonder why we have this argument, and suggest one of two courses of action:
1) Remove it. Without a documented use case, it will just lead people to believing things that aren't true.
2) Enhance the system to know the user did this and cause projects that were restored in that way to use packages from the specified location.

**Comment by eerhardt** [comment]
@yishaigalatzer @emgarten @rrelyea to get their thoughts on this issue.

Since the CLI doesn't really save where you restored your packages to in `dotnet restore --packages`, if we wanted to support this feature we'd either have to:

- remember where we put it
- have the user pass the same location through to all other commands (build, pack, publish, run, test)

**Comment by brthor** [comment]
We have a similar issue here https://github.com/dotnet/cli/issues/2712 to support --packages in the cli which was kicked out to RTM.

There's a number of other discovery mechanism nuget supports which cli does not as well, for example via NuGet.Config `globalPackagesFolder`

**Comment by yishaigalatzer** [comment]
I agree it should be dropped, but the issue should go to nuget. CC @rrelyea @harikm86

**Comment by livarcocc** [comment]
@yishaigalatzer Please don't drop it. I am actually using that to restore packages in a particular folder and then I zip that folder to create an archive of packages.

**Comment by eerhardt** [comment]
@livarcocc - you can use the `NUGET_PACKAGES` environment variable instead.

**Comment by yishaigalatzer** [comment]
or you can use nuget.exe to do the same

**Comment by eerhardt** [comment]
> or you can use nuget.exe to do the same

@livarcocc's needs are for all platforms.

**Comment by blackdwarf** [comment]
This should move to Nuget/Home. Closing this issue.
