### ISSUE TITLE
dotnet help run makes dotnet crash

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#345]
- Run: `dotnet help run` => app crashes
- Run: `dotnet help compile` => no crash

**Comment by krwq** [comment]
Thanks for the feedback! I'm currently gathering requirements for similar problems. I.e:
https://github.com/dotnet/cli/issues/300
We will be fixing the command line parsing issues soon altogether, please report if you see anything else which you think should be working or should be working differently.

It is good to know people expect `dotnet help <command>` syntax to work as I actually personally usually use only --help or --?

**Comment by victorhurdugaci** [comment]
I use `help <command>` because it used to work with `dnu`. E.g. `dnu help pack`

**Comment by moozzyk** [comment]
@krwq `--?` or `-?` ? (`dnx` had `-?` (one dash))

**Comment by krwq** [comment]
@moozzyk that was about any command. i.e. git --? That's just about general user experience of how this should be implemented

**Comment by blackdwarf** [comment]
@victorhurdugaci this doesn't repro for me with the latest PKG on OS X El Capitan. Can you specify which OS are you seeing this on?

**Comment by victorhurdugaci** [comment]
It was on Windows 10

**Comment by blackdwarf** [comment]
@victorhurdugaci just checked on a Win10 install as well, I get the following: 

```shell
.NET Executor

Usage: dotnet run [options]

Options:
  -h|--help                           Show help information
  -f|--framework <FRAMEWORK>          Compile a specific framework
  -c|--configuration <CONFIGURATION>  Configuration under which to build
  -t|--preserve-temporary             Keep the output's temporary directory around
  -p|--project <PROJECT_PATH>         The path to the project to run (defaults to the current directory). Can be a path to a project.json or a project directory.
```

**Comment by livarcocc** [comment]
This is the same issue that was happening to compile csc and compile native. I have a fix for it in PR and there is another bug for it. I will close this bug and track it in the other one.

**Comment by livarcocc** [comment]
Tracked in #473.
