### ISSUE TITLE
How to fix One or more packages are incompatible with .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by jindovu** [dotnet/cli#3450]
## Steps to reproduce
I use dotliquid on version .net core ([link](https://github.com/dotliquid/dotliquid)), but I got something wrong with package dotliquid just only support version bellow, How can I Fix it
 Package DotLiquid 1.8.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package DotLiquid 1.8.0 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

## Expected  behavior
compatible with .NET Core App

## Environment data
`dotnet --info` output:
Product Information:
 Version:            1.0.0-preview2-002966
 Commit SHA-1 hash:  b512ddb8b8

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x64

Plz help me, Thank you so much

**Comment by kierenj** [comment]
The message states,

DotLiquid 1.8.0 supports:
- net35 (.NETFramework,Version=v3.5)
- net40 (.NETFramework,Version=v4.0)
- net45 (.NETFramework,Version=v4.5)

....DotLiquid doesn't support .NET Core.  This is nothing to do with the CLI or .NET Core - and everything to do with DotLiquid!

**Comment by jindovu** [comment]
Hi kierenj
       Thank you for quick reply, I want understand enhancement build project to .net core,  How I can convert some project from net45 to .net core, Plz provider me document

Thank you so much

**Comment by piotrpMSFT** [comment]
It's not a problem in your code, @jindovu. DotLiquid is not available on core so it cannot be used during build. You can either get the package owner to ship a compatible build or remove the dependency altogether.

**Comment by jindovu** [comment]
Thank you for your help
