### ISSUE TITLE
Wrong error message when missing emitEntryPoint (first time only): Expect required library hostpolicy.dll to be present in [...\bin\Debug\netcoreapp1.0]

### ISSUE THREAD

**Issue by kierenj** [dotnet/cli#3453]
## Steps to reproduce
1. Create a folder with global.json containing two project folders, xyzzy.MyLib and xyzzy.MyApp
2. Create class library with a single class and a project.json as follows in xyzzy.MyLib:

```
{
    "version": "0.1.0-*",
    "description": "xyzzy.MyLib",
    "dependencies": {
        "NETStandard.Library": "1.6.0-rc4-24207-02"
    },
    "frameworks": {
        "netstandard1.5": { }
    }
}
```
1. Create a console app with a single class and a project.json as follows in xyzzy.MyApp (note missing `emitEntryPoint` build option):

```
{
    "version": "0.1.0-*",
    "description": "xyzzy.MyApp",
    "dependencies": {
        "Microsoft.NETCore.App": { "version": "1.0.0-rc2-3002702", "type": "platform" },
        "xyzzy.MyLib": "0.1.0-*"
    },
    "frameworks": {
        "netcoreapp1.0": {
        }
    }
}
```
1. `dotnet restore` in the xyzzy.MyLib folder
2. `dotnet restore` in the xyzzy.MyApp folder
3. `dotnet build` in the xyzzy.MyApp folder
4. `dotnet run` in the xyzzy.MyApp folder <--- issue here
## Expected  behavior

App should run and print out a banner message.
## Actual behavior

```
Project xyzzy.MyLib (.NETStandard,Version=v1.5) was previously compiled. Skipping compilation.
Project xyzzy.MyApp (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Expect required library hostpolicy.dll to be present in [C:\git\kierenj\issue-demo\src\xyzzy.MyApp\bin\Debug\netcoreapp1.0]
  - This may be because of an invalid .NET Core FX configuration in the directory.
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by kierenj** [comment]
Note that **things change** once I add:

```
  "buildOptions": {
    "emitEntryPoint": true
  },
```

to project.json.  This then causes the project to build and run correctly (yay!).

**But** if I subsequently remove it again, only then do I get the correct error:

`dotnet.exe` crashes ("has stopped working")
-and-
```
Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'xyzzy.MyApp, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'.
```

So TL;DR I think that the first time I try to run without `emitEntryPoint`, I get the incorrect and confusing error message:

```
Expect required library hostpolicy.dll to be present in [...\bin\Debug\netcoreapp1.0]
```

...whereas it should be the second message, right from the first attempt.

**Comment by brthor** [comment]
@kierenj The application dependency graph cannot be loaded without hostpolicy.dll so there is a bit of chicken/egg problem here.

cc @schellap

**Comment by chris-brown** [comment]
@kierenj try changing `buildOptions` to `compilationOptions`

```
"buildOptions": {
    "emitEntryPoint": true
  },
```
to
```
"compilationOptions": {
    "emitEntryPoint": true
  },
```

**Comment by piotrpMSFT** [comment]
This scenario has been cleaned up a lot in preview3. If we try to run a non-runnable project we get:

```
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports this project.
The current OutputType is 'Library'.
```
