### ISSUE TITLE
How to build projects with other project dependencies

### ISSUE THREAD

**Issue by ChantayOsborne** [dotnet/cli#3457]
Create ProjectA, with one class. Create ProjectB with a second class, which has a reference to ProjectA's class.. Save each project in different directories (e.g., "c:\projects\ProjectB\class.cs", and "c:\projects\ProjectA\class.cs". Execute dotnet restore on c:\projects.

Throws errors on the build, even though everything is in that root "projects" class.  

I have a project "Location" stored at code\Location. It uses code for a Google API stored at code\ThirdPartyAPI\Google. When I execute the restore command for Library, I get
"Unable to resolve 'Google (>= 1.0.0)' for 'DNX,Version=v4.5.1'"

When I attempt to build library, I get (obviously)
"NU1001: The dependency Google >= 1.0.0 could not be resolved."

Is there something I need to do to indicate dependencies cross-folders in the projects.json? Are there additional flags that need to be added to scan directories for dependencies?

Thanks!

.NET Command Line Tools (1.0.0-preview1-002702)
Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by piotrpMSFT** [comment]
You need a global.json in the "solution" root. @blackdwarf can point to docs on https://dot.net

**Comment by ChantayOsborne** [comment]
I've looked for documentation on this and can't find anything (either outdated, or dead pages.) ANy better links?

**Comment by blackdwarf** [comment]
@ChantayOsborne please take a look at https://dotnet.github.io/docs/scenarios/solution-authoring/index.html. If you still find that the information is inadequate, please file an issue at dotnet/core-docs for us to improve docs.

With that, I will close this issue.

**Comment by derekgreer** [comment]
https://dotnet.github.io/docs/scenarios/solution-authoring/index.html results in a 404

**Comment by svick** [comment]
@derekgreer The docs were moved and reorganized since then. If you're looking for a tutorial that includes manually writing `global.json`, have a look at https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli.
