### ISSUE TITLE
Mark CLI stable packages as "stable"

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3465]
We need to remove the -rc3 prerelease moniker for the appriopriate packages:

- ~~ProjectModel~~
- DependencyModel
- InternalAbstractions

@piotrpMSFT @ericstj @joshfree

**Comment by piotrpMSFT** [comment]
We need to have this PR ready, but cannot merge until we feel we have a final build. When is CoreFx doing this change?

**Comment by eerhardt** [comment]
FYI - We no longer need ProjectModel as "stable". It was determined that ASP.NET MVC only uses DependencyModel.

Thus DependencyModel and InternalAbstractions need to be "stable".  ProjectModel can go to "preview2"  (or maybe keep it "rc2"???). Either way it can't be marked "stable" because it depends on NuGet packages that aren't going to be marked as "stable".

/cc @pranavkm @davidfowl @anurse

**Comment by pranavkm** [comment]
:+1:

**Comment by anurse** [comment]
FYI, Moving ProjectModel to `preview` will cause new versions to be seen as older than any `rc` version, because SemanticVersion tags are sorted alphabetically.

**Comment by pranavkm** [comment]
Ahh, that would be problematic. (I thought it was currently labeled `preview2`). Could we leave it as rc3 \ rc4?

**Comment by anurse** [comment]
Or `1.0.0-rpreview2` ;)

**Comment by pranavkm** [comment]
`1.0.0-treeview2` FTFY

**Comment by eerhardt** [comment]
My vote is we leave ProjectModel "rc2" and just keep updating the build number.  During 'preview3' timeframe, it can become 'rc3' (or just get deleted by that time, hopefully, with the move to MSBuild).

**Comment by brthor** [comment]
does anything actually need to be done here, seems like a no-op?

**Comment by brthor** [comment]
Noticed DependencyModel, InternalAbstractions still need to be done. Fixing these, going to leave ProjectModel as is
