### ISSUE TITLE
CreateLoadContext(runtimeIdentifier, configuration) Stackoverflows

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#3469]
It calls itself. This is also true for the configuration only overload.

https://github.com/dotnet/cli/blob/cbf5f1ef65a1405403951226474147f5d029601d/src/Microsoft.DotNet.ProjectModel.Loader/LoaderProjectContextExtensions.cs#L23

**Comment by piotrpMSFT** [comment]
@anurse can this be closed?

**Comment by piotrpMSFT** [comment]
confirmed by @eerhardt that this can be closed.
