### ISSUE TITLE
Typo: Install script finishes "successfuly"

### ISSUE THREAD

**Issue by bartonjs** [dotnet/cli#3475]
## Steps to reproduce

> curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh | sudo bash /dev/stdin --version 1.0.0-preview2-002996 --install-dir /opt/dotnet

## Expected  behavior

No typos.  `successfuly` => `successfully`

## Actual behavior

dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002996/dotnet-dev-centos-x64.1.0.0-preview2-002996.tar.gz
dotnet-install: Extracting zip
dotnet-install: Adding to current process PATH: /opt/dotnet. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished __successfuly__.

## Environment data
`dotnet --info` output:

```
[bb@bb-centos72-3 ~]$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-002996)

Product Information:
 Version:            1.0.0-preview2-002996
 Commit SHA-1 hash:  cff4f37456

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
```

**Comment by krwq** [comment]
Fixed with 9d01e3bc
