### ISSUE TITLE
dotnet compile-csc crashes due to file contention on tool lock file

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/cli#3476]
## Steps to reproduce

This is regularly reproducing on ASP.NET coherence CI run. During this run, many `dotnet restore` and `dotnet build` commands are running in parallel. Periodically,
## Expected  behavior

After talking to @brthor and @eerhardt, `dotnet build` should not need to read the tool lock file so any writes occurring from a `dotnet restore` should not collide.
## Actual behavior

The log shows `dotnet-csc` dying with this log:

<pre>
The process cannot access the file 'D:\b\w\a6e561eeb4ed13a7\.packages\.tools\Microsoft.AspNetCore.Server.IISIntegration.Tools\1.0.0-preview2-21282\netcoreapp1.0\project.lock.json' because it is being used by another process.
C:\Users\REDACTED\AppData\Local\Microsoft\dotnet\<b>dotnet.exe compile-csc</b> @D:\b\w\a6e561eeb4ed13a7\Antiforgery\samples\AntiforgerySample\obj\Release\net451\dotnet-compile.rsp returned Exit Code 1
</pre>

## Environment data

Installation log:

```
Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002990/dotnet-dev-win-x64.1.0.0-preview2-002990.zip
Extracting zip from https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-002990/dotnet-dev-win-x64.1.0.0-preview2-002990.zip
Adding to current process PATH: "C:\Users\asplab.REDMOND\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
Installation finished
```

So... Windows x64, 1.0.0-preview2-002990.

**Comment by joshfree** [comment]
@yishaigalatzer @rrelyea could this be related to nuget changes around locking / dotnet restore /etc ?

**Comment by joelverhagen** [comment]
`dotnet restore` does write out this file. However, it only write the file when it has changed (can change due to `imports`) and we write it in a global lock *only observed by NuGet code* (fix was tracked by NuGet bug https://github.com/NuGet/Home/issues/2304).

**Comment by brthor** [comment]
If for some reason compile-csc were executed out of proc it's possible the resolution step could be trying to read this file at the same time nuget is writing it causing some concurrency issue. Have not had time to get this under a debugger yet.

**Comment by pranavkm** [comment]
We have worked around this by unparallelizing the build so exactly one repository is restored \ built at a time at the cost of much slower build times. My guess is that when two restores fire off, one of them assumes the tooling project.lock.json is already in place which causes it to proceed to `dotnet build` resulting in the failure. Perhaps tools restore needs to be hardened?

**Comment by joelverhagen** [comment]
@pranavkm, is it possible to do all of the `dotnet restore` calls in parallel then, only after all of the restores have completed, execute all of the `dotnet build`? Today, the restore code only writes the tool lock file if it has changes and still only does so in a global NuGet lock.

The hint for me is that the error above shows that `dotnet-csc` is crashing (not `NuGet.CommandLine.Xplat` or `dotnet`).

**Comment by pranavkm** [comment]
They're entirely different projects and all we do is run `build` on them individually. It's hard to run restore on all the projects because individual projects might restore things slightly differently.

**Comment by pranavkm** [comment]
Is there a reason compilation reads the tools lock file? I thought it was a runtime-only feature.

**Comment by ElanHasson** [comment]
I am encountering this same issue in 1.0.0-preview2 with on-premise TFS builds on dotnet restore. (Not with Coherence, but with our project).

It is intermittent and "seemingly random".

**Comment by livarcocc** [comment]
We no longer have that verb on the CLI.
