### ISSUE TITLE
Document how references get resolved with project.json

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/cli#3478]
Using project.json is very different from the previous model of referencing assemblies. I found some useful documentation here (https://docs.nuget.org/consume/projectjson-dependency), but someone new to .NET Core may not think to look there when initially confronted with project.json in the .NET Core setting. This issue is to track some sort of documentation wherever the 'Getting Started' stuff is going.

**Comment by blackdwarf** [comment]
@twsouthwick good point. Can you please close this one and open one on dotnet/core-docs and /cc me? Thanks!

**Comment by twsouthwick** [comment]
Done. See here: https://github.com/dotnet/core-docs/issues/509
