### ISSUE TITLE
.net 1.0.0.0 RC2 Visual Studio 2015 Tools installation finishes without installing anything

### ISSUE THREAD

**Issue by hamidshahid** [dotnet/cli#3481]
## Steps to reproduce
Downloaded the latest DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.msi file. Ran it while I still my Visual studio 2015 instance running.

## Expected  behavior
An error message to shut down visual studio

## Actual behavior
The installer finished with a success message. 

## Environment data
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Please move to aspnet/tooling repo.

**Comment by hamidshahid** [comment]
Thanks. Done now

https://github.com/aspnet/Tooling/issues/578
