### ISSUE TITLE
"dotnet new" should automatically do "dotnet restore"

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#3495]
With 1.0.0-preview2-003024 on Debian 8.2

```
bb@bb-debian8:~/hello$ dotnet new
Created new C# project in /home/bb/hello.
bb@bb-debian8:~/hello$ dotnet run
The current project is not valid because of the following errors:
/home/bb/hello/project.lock.json(1,0): error NU1009: The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.
```

The error message is improved (yay) but I don't believe I should get any error at all from simply doing "dotnet new" .. "dotnet run". .. the first two commands I do after installing Core. It reduces my confidence that I've set up correctly. 

Expected: we should do "dotnet restore" automatically as part of "dotnet new".

/cc @livarcocc @piotrpMSFT

**Comment by danmosemsft** [comment]
@ericstj Says this is part of the "offline restore" feature, but meantime it'd be great to make this online scenario work better.

**Comment by enricosada** [comment]
pls dont, it's just a command more, one it's needed a lot to know anyway.
the error message say that, change a bit message, but it's ok.
Also i can use `dotnet new` to create a base, who need changes anyway, before restore. so not opt in the restore.
It's a separate command, just that

**Comment by blackdwarf** [comment]
I agree with @enricosada here. When you run `dotnet new`, we don't know if you want to just get a basic project up and edit it, or if you want to do the `new - restore - run` combo. Thus, running `restore` after `new` would be implying too much. Now, running `restore` before `run` is an interesting thing to consider.
