### ISSUE TITLE
`dotnet new` lib template is broken

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3496]
See the conversation here:

https://github.com/dotnet/cli/commit/85e4ed2b74e8cd262d906f5ec5e6ea59835d2c38#commitcomment-17826417

We don't have a "dependencies" node in our project.json, which isn't valid.

@weshaggard @blackdwarf

**Comment by piotrpMSFT** [comment]
Which pr introduced this issue?

**Comment by blackdwarf** [comment]
#3458 . Fix is in PR.

**Comment by blackdwarf** [comment]
Fixed by #3507
