### ISSUE TITLE
Running dotnet new --type xunittest breaks project

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#3499]
## Steps to reproduce
1) Create a new C# project folder
    a) mkdir Testing
    b) cd Testing
    c) dotnet new
2) Add xunit testing capabilities in the same folder
   a) dotnet new --type xunittest

## Expected  behavior
Unit test files are added

## Actual behavior
```
[bb@bb-oraclelinux72 testing]$ ../dotnet/dotnet new --type xunittest
The file '/home/bb/testing/project.json' already exists.
Creating new C# project failed.
```

The project is then changed such that it no longer compiles

## Environment data
`dotnet --info` output:

[bb@bb-oraclelinux72 testing]$ ../dotnet/dotnet --info
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     ol
 OS Version:  7.2
 OS Platform: Linux
 RID:         ol.7.2-x64

**Comment by ianhays** [comment]
Was just about to post this!

```
[ianha@localhost ~]$ mkdir test
[ianha@localhost ~]$ cd test/
[ianha@localhost test]$ dotnet new
Created new C# project in /home/ianha/test.
[ianha@localhost test]$ ls
Program.cs  project.json
[ianha@localhost test]$ dotnet new --type xunittest
The file '/home/ianha/test/project.json' already exists.
Creating new C# project failed.
[ianha@localhost test]$ ls
Program.cs  project.json  project.json.template  Tests.cs
```

**Comment by livarcocc** [comment]
I am not sure I agree. dotnet new creates projects. If you run dotnet new under in a folder with an existing project, it will fail, independently of it being a unit test or not.

What you should do is go one directory up, create a new folder and run dotnet new again there to contain your tests.

Note that you will need a global.json at that point, because you are no longer dealing with a single project, but actually a "solution".

**Comment by brthor** [comment]
I agree that it should fail earlier though, and not break the current project that exists there.

**Comment by ianhays** [comment]
>If you run dotnet new under in a folder with an existing project, it will fail, independently of it being a unit test or not.

Failing is fine, that makes sense imo. The issue is that it fails *after* modifying the directory.

**Comment by livarcocc** [comment]
@ianhays Ah, yes. I Agree as well.

**Comment by livarcocc** [comment]
Do we know if newing up other project types is failing correct or if they hit the same issue as test? We should fix them all at once.

**Comment by ianhays** [comment]
The inverse is an issue as well i.e. `dotnet new --type xunittest` followed by `dotnet new`.

```
[ianha@localhost test]$ dotnet new --type xunittest
Created new C# project in /home/ianha/test.
[ianha@localhost test]$ ls
project.json  Tests.cs
[ianha@localhost test]$ dotnet new
The file '/home/ianha/test/project.json' already exists.
Creating new C# project failed.
[ianha@localhost test]$ ls
Program.cs  project.json  project.json.template  Tests.cs
[ianha@localhost test]$
```
