### ISSUE TITLE
Add the types to the help text for dotnet new -t

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/cli#3500]
## Steps to reproduce

Dotnet -new --help

Also typing garbage gives the information I am looking for
bash-3.2$ dotnet new -t asdf
Unrecognized type: asdf
Avaiable types for C# :
- Console
- Web
- Lib
- xunittest
## Expected  behavior

I should see the all the values for the switches for new in the help
## Actual behavior

Options:
  -h|--help             Show help information
  -l|--lang <LANGUAGE>  Language of project [C#|F#]
  -t|--type <TYPE>      Type of project

No idea what to set for <TYPE> or <LANGUAGE> for that matter
## Environment data

`dotnet --info` output:

bash-3.2$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by blackdwarf** [comment]
@Chrisboh in the future, `dotnet new` will change and will allow installing of templates as well as listing installed templates (so the `--type` will be whatever you installed). So this will effectivelly take care of this issue. Will leave it for RTM to track.

/cc @sayedihashimi

**Comment by piotrpMSFT** [comment]
This is fixed in the new `dotnet new`. You can preview it as `dotnet new3` and for RTM it will be renamed to `dotnet new`.
