### ISSUE TITLE
Running restore on global.json works but build does not

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#3501]
## Steps to reproduce

1) Have multiple projects under a global.json
2) Run restore, success!
3) Run build
## Expected  behavior

Success!
## Actual behavior

[bb@bb-oraclelinux72 global]$ ../dotnet/dotnet build
Couldn't find 'project.json' in current directory
## Environment data

`dotnet --info` output:

[bb@bb-oraclelinux72 global]$ ../dotnet/dotnet --info
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     ol
 OS Version:  7.2
 OS Platform: Linux
 RID:         ol.7.2-x64

**Comment by blackdwarf** [comment]
This issue is resolved with the new tooling using the SLN (solution files). You are able to do `dotnet build` in a folder with an SLN file and it will work. 

With the latest Preview we've also created a way to add projects to an SLN file.
