### ISSUE TITLE
publishOptions: [ ... ] is not respected

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#3502]
## Steps to reproduce

Per the [schema](https://github.com/aspnet/Announcements/issues/175), this should be supported:

> Note: If a string/string[] is specified instead of an object, it will be considered to be part of include.

> E.g.

```json
"publishOptions": [ "wwwroot", "Views" ]
```

> is same as

```json
"publishOptions": {
  "include": [ "wwwroot", "Views" ]
}
```

## Expected  behavior

A `string[ ... ]` to be picked up as `{ "include": [ ... ] }`.

## Actual behavior

Completely ignored.

## Environment data
`dotnet --info` output:

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-002913)

Product Information:
 Version:            1.0.0-preview2-002913
 Commit SHA-1 hash:  b1b7caac3d

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

and `dotnet-dev-1.0.0-preview1-002702` on our Ubuntu 14.04 CI, and `1.0.0-preview2-003024/dotnet-dev-win-x64.1.0.0-preview2-003024.zip` on our Windows Server 2012 R2 CI.

**Comment by ajaybhargavb** [comment]
Thanks for reporting this. This is a bug. We convert folder names to patterns before running globbing. https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/Microsoft.DotNet.ProjectModel/Files/IncludeContext.cs#L210
But this conversion is not being applied when a `string/string[]` is specified.

Workaround:
`"publishOptions": [ "wwwroot/**/*", "Views/**/*" ]`

**Comment by ajaybhargavb** [comment]
@piotrpMSFT, Do we want to fix this for preview2?

**Comment by GuardRex** [comment]
... and guys, please consider killing two :bird: here with one stone ... https://github.com/dotnet/cli/issues/1396 is backlogged, but having to have a dummy file in a folder just to get that folder honored for `publishOptions` is cheesy.

**Comment by ajaybhargavb** [comment]
@GuardRex, #1396 seems like a limitation in our globbing system and needs an entirely different fix. I don't think that can be combined with this fix.

**Comment by GuardRex** [comment]
@ajaybhargavb Ok ... just wondering. "Backlog" in some non-MS organizations means "Black Hole" lol I was just hoping it didn't fall off the radar. Thx.
