### ISSUE TITLE
We should change Hello World sample to show how to include multiple projects

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/cli#3503]
Here is the basic scenario I would like to know how to do.  Create a product and have a test of tests run against it.  I don't want to manually walk to every project directory to run a dotnet build and then a dotnet run.    I was told, by people in the know, about this special file called global.json which helps stitch these things together.  What I don't know is how in the world I would have discovered this.  

I honestly think there are two things we should do to make this better.  The first would be to write documentation around this as there was nothing obvious on dot.net.  The second thing would be updating the Hello World sample to do this.
## Steps to reproduce

Dotnet -new
## Expected  behavior

Create the following folder structure and have the following behavior

dotnet -restore <- At the root this should restore all projects
dotnet -build <- At the root this should build all projects
dotnet -run <- This should take the name of which project you want to run

global.json
src
  HelloWorld.cs
  HelloWorld.csproj
test
  HelloWorldTest.cs
  HelloWorldTest.csproj
## Actual behavior

I am left with having to manually go to each project and folder know what to build and what order to build it as well as keeping track in my head everything I have already built and need to rebuild.  
## Environment data

`dotnet --info` output:

**Comment by blackdwarf** [comment]
@Chrisboh we have something like that at https://dotnet.github.io/docs/scenarios/solution-authoring/index.html. It should fill your needs. :smiley: We also have docs on global.json reference on the same site as above.

**Comment by Chrisboh** [comment]
My direct feedback here is that we should change the out of the box example to be this example as there are way to many pitfalls for the user to hit when constructing this on their own.  For example it looks like `dotnet build` will pick up code in sub folders even though its not part of the project.

Also where would I find the documentation for global.json on the link above?  i am poking around but all I seem to be able to find is the example telling you to create one.

**Comment by piotrpMSFT** [comment]
Tracking in #4675.
