### ISSUE TITLE
"Cycle detected" error restoring xunittest project on Windows 2016 Nano

### ISSUE THREAD

**Issue by ericeil** [dotnet/cli#3508]
## Steps to reproduce
Create a new xunittest project on Windows 2016 Nano, and restore it:

```
[40.78.96.241]: PS C:\x2> C:\dotnet\dotnetnano\dotnet new -t xunittest
Created new C# project in C:\x2.
[40.78.96.241]: PS C:\x2> C:\dotnet\dotnetnano\dotnet restore
log  : Restoring packages for C:\x2\project.json...
error: Cycle detected:
error:   x2 (>= 1.0.0) -> xunit (>= 2.1.0) -> xunit (>= 2.1.0) -> xunit (>= 2.1.0).
log  : Writing lock file to disk. Path: C:\x2\project.lock.json
log  : C:\x2\project.json
log  : Restore failed in 2781ms.
C:\dotnet\dotnetnano\dotnet :
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Errors in C:\x2\project.json
    Cycle detected:
      x2 (>= 1.0.0) -> xunit (>= 2.1.0) -> xunit (>= 2.1.0) -> xunit (>= 2.1.0)
```

## Expected  behavior
`dotnet restore` works.

## Actual behavior
`dotnet restore` reports "cycle detected" error for xunit.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14300
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@ericstj @rrelyea any ideas?

**Comment by ericstj** [comment]
Did you have another folder in some directory named 'xunit'?

**Comment by ericeil** [comment]
> Did you have another folder in some directory named 'xunit'?

It's possible that there was an "xunit" directory off of the root.  So:

c:\x2   <-- where the project was
c:\xunit   <-- where I'd started a different project (IIRC)

Why would that make a difference?

**Comment by ericstj** [comment]
Because Nuget tries to find local projects that might replace package references.

See https://github.com/NuGet/Home/issues/1428

**Comment by ericeil** [comment]
Ok, that does seem to explain it.  Closing this issue.

**Comment by shanselman** [comment]
I just hit this, just now. We need a better error message. There's literally no way for someone to figure this out except for Google. Is that OK? /cc @blackdwarf @davidfowl

**Comment by blackdwarf** [comment]
@shanselman this is something that we should file on NuGet/Home, since `dotnet restore` pass through to NuGet. The error messages comes from there as well, AFAIK.

**Comment by jlberrocal** [comment]
obviously is too late but maybe this will help someone, i was getting this error and was caused because Rider created a reference into the csproj file to itself, i expend some hours before realize this was the issue, of course it was a terrible face palm
