### ISSUE TITLE
Dotnet run eats newlines

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#3509]
## Steps to reproduce
1) Have a Console.ReadLine() in code
2) dotnet run
3) Enter data

## Expected  behavior
The readline works

## Actual behavior
Program waits for newline even though console shows newline has been entered

## Environment data
`dotnet --info` output:

jonmill-macbook:Testing jon$ ~/Downloads/dotnet-dev-osx-x64.1.0.0-preview2-003024/dotnet --info
.NET Command Line Tools (1.0.0-preview2-003024)

Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by livarcocc** [comment]
I believe this is working now.
