### ISSUE TITLE
dotnet build on a test project won't rebuild referenced project when there are source changes.

### ISSUE THREAD

**Issue by joperezr** [dotnet/cli#3510]
## Steps to reproduce
1.- Create a Library project with a method
2.- Create a test project that references the Library project's method
3.- run dotnet restore on both projects and dotnet build on both projects.
4.- Make a change on Library project's method to make the test fail.
5.- build and run the test again. <-- Test project will still pass

## Expected  behavior
Test project should fail because Library project should be automatically rebuilt

## Actual behavior
Test run succeeds because it is still using the old version of the Library.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003024)
 
Product Information:
 Version:            1.0.0-preview2-003024
 Commit SHA-1 hash:  ef4a8e85ef
 
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by piotrpMSFT** [comment]
Can you share a repro?

**Comment by livarcocc** [comment]
This is working for me right now even without msbuild.
