### ISSUE TITLE
Need an installation script for Windows Nano Server

### ISSUE THREAD

**Issue by Priya91** [dotnet/cli#3515]
Currently msi doesn't work on Windows Nano Server, so we need to create a powershell script to install cli on nano. This script should copy over x64 binaries, and alter the system path. Also preview2 doesn't work on Nano without copying over ```C:\windows\system32\forwarders\*``` to the folder that has ```coreclr.dll``` in the cli installation.

This scenario is broken for Windows Nano customers, and if we are officially supporting Nano for preview2 this experience must be made smooth for the consumers.

cc @krwq @joshfree

**Comment by piotrpMSFT** [comment]
@Priya91 do the existing scripts in `/scripts/obtain/install.[sh|ps1] not suffice for the purpose, forwarders aside?

**Comment by muojp** [comment]
seems same issues have different milestones: #3115

**Comment by Priya91** [comment]
@piotrpMSFT The ps script in cli repo is using the full framework, certain functions there don't work on .NETcore which is used by powershell on Nano.

**Comment by MichaelSimons** [comment]
FYI - https://github.com/dotnet/cli/issues/3113 should address the issues with the ps script not working on Nano.

**Comment by Priya91** [comment]
Will close this issue as dupe of #3113
