### ISSUE TITLE
dotnet ef dbcontext scaffold does not use assembly name

### ISSUE THREAD

**Issue by chassq** [dotnet/cli#3520]
## Steps to reproduce
1- Create a asp.net web project. 
2- Change the default namespace in the project properties to something different than the project name.
2- Set the project up to run ef dbcontext scaffold to create models from a SQL server db
3- Run the scaffolding command line

## Expected  behavior
Output classes use the Default namespace value for namespace names

## Actual behavior
Output classes are using project name for namespace names

## Environment data
Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
I've moved this to aspnet/EntityFramework#6152. Closing this one.
