### ISSUE TITLE
Incorrect exclusion of System.Private.CoreLib for crossgen

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#3522]
See https://github.com/dotnet/core-setup/issues/150 for details.

System.Private.CoreLib.dll does not have “.dll” suffix in both core-setup (https://github.com/dotnet/core-setup/blob/6d22159ebd7508bf223d500593b2740d7d030d66/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L20) and CLI (https://github.com/dotnet/cli/blob/80d3476fd16609a41fde37e4cdaa78e15f659115/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L19).
 
As a result, https://github.com/dotnet/core-setup/blob/6d22159ebd7508bf223d500593b2740d7d030d66/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L186 check fails for System.Private.CoreLib.dll (since there is no such entry in the excluded file list) and we generate the NI and copy it as .dll

@brthor @piotrpMSFT PTAL.

CC @jkotas @eerhardt

**Comment by eerhardt** [comment]
Fixed by #3524
