### ISSUE TITLE
dotnet restore fails with 'Value cannot be null'

### ISSUE THREAD

**Issue by noahfalk** [dotnet/cli#3530]
## Steps to reproduce

```
Usng bash on an OSX machine...
dotnet --version
1.0.0-preview1-002702
mkdir hwapp
cd hwapp
dotnet new
unset HOME
dotnet restore
```
## Expected  behavior

Either give a nice error message or calculate settings without falling back to $HOME\...
## Actual behavior

```
dotnet restore
error: Value cannot be null
error: Parameter name: path1
```
## Environment data

Sorry I only captured dotnet --version when I had this earlier:
1.0.0-preview1-002702

It was running on OSX 10.11
## Notes

I filed another issue here, but they might be dupes: https://github.com/NuGet/Home/issues/2960

In PackagesDependencyProvider.cs (175) I can see some code that is using the HOME variable without null checking it first:

```
        if (string.IsNullOrEmpty(profileDirectory))
        {
            profileDirectory = Environment.GetEnvironmentVariable("HOME");
        }

        return Path.Combine(profileDirectory, ".nuget", "packages");
```

When I experimented setting the HOME environment var for restore, but then removing it before 'dotnet build', the build command also exhibited similar failure behavior.

**Comment by livarcocc** [comment]
We added a better error message for this case:

```
The user's home directory could not be determined. Set the 'DOTNET_CLI_HOME' environment variable to specify the directory to use.
```
