### ISSUE TITLE
Remove namespace from dotnet new artifacts

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#3531]
The namespace just complicates the sample w/o any value.

Current artifact:

```csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

Simplify to:

```csharp
using System;

public class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    }
}
```

**Comment by piotrpMSFT** [comment]
@blackdwarf please follow up with @richlander to see if we need to bring this in.

**Comment by blackdwarf** [comment]
@piotrpMSFT not for Preview 2, no. For Preview 3, maybe.

**Comment by richlander** [comment]
Talked to @MadsTorgersen about this. He was supportive of this direction. He had the same view as me, that namespace is not valuable for simple console apps.

**Comment by blackdwarf** [comment]
@richlander sure, but not for preview 2. :) We are working on a new `dotnet new` anyway, so we will revamp samples when doing that work.

**Comment by blackdwarf** [comment]
This is now fixed.
