### ISSUE TITLE
dotnet does not restore netstandard framework

### ISSUE THREAD

**Issue by xplicit** [dotnet/cli#3532]
## Steps to reproduce
run `dotnet restore` on the following project.json

project.json

    {
      "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-24027"
      },
      "frameworks": {
        "netstandard1.1": { 
            "dependencies" : {
	         "System.IO" : "4.0.0-*",
             }
         }
   
      },
      "version": "4.0.0-*"
    }

## Expected  behavior
project is restored without errors (see compatibility of `System.IO` with netstandard versions
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md)

## Actual behavior
Error.

log  : Restoring packages for C:\Projects\dotneTest\project.json...
warn : Detected package downgrade: System.IO from 4.1.0-rc2-24027 to 4.0.0--
warn :  dotneTest (>= 4.0.0) -> NETStandard.Library (>= 1.5.0-rc2-24027) -> System.IO (>= 4.1.0-rc2-24027)
warn :  dotneTest (>= 4.0.0) -> System.IO (>= 4.0.0)
error: Package System.IO 4.0.0 is not compatible with netstandard1.1 (.NETStandard,Version=v1.1). Package System.IO 4.0.0 supports:
error:   - dotnet (.NETPlatform,Version=v5.0)
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - win8 (Windows,Version=v8.0)
error:   - wp8 (WindowsPhone,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error: One or more packages are incompatible with .NETStandard,Version=v1.1.
log  : Writing lock file to disk. Path: C:\Projects\dotneTest\project.lock.json
log  : C:\Projects\dotneTest\project.json
log  : Restore failed in 1021ms.

Errors in C:\Projects\dotneTest\project.json
    Package System.IO 4.0.0 is not compatible with netstandard1.1 (.NETStandard,Version=v1.1). Package System.IO 4.0.0 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - monoandroid10 (MonoAndroid,Version=v1.0)
      - monotouch10 (MonoTouch,Version=v1.0)
      - net45 (.NETFramework,Version=v4.5)
      - netcore50 (.NETCore,Version=v5.0)
      - win8 (Windows,Version=v8.0)
      - wp8 (WindowsPhone,Version=v8.0)
      - wpa81 (WindowsPhoneApp,Version=v8.1)
      - xamarinios10 (Xamarin.iOS,Version=v1.0)
      - xamarinmac20 (Xamarin.Mac,Version=v2.0)
    One or more packages are incompatible with .NETStandard,Version=v1.1.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003041)

Product Information:
 Version:            1.0.0-preview2-003041
 Commit SHA-1 hash:  cc3d19463d

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

## Comments
If I run `dnu restore` on the same file it is restored without issues
If I change netstandard version to 1.6 `dotnet restore` shows the same error
If I change `System.IO` to other package `dotnet restore` shows the same error

**Comment by piotrpMSFT** [comment]
This issue belongs in the https://github.com/dotnet/corefx repo. @xplicit can you move it there?

/cc @ericstj

**Comment by ericstj** [comment]
That's an old package that doesn't support NETStandard.  You need to use the latest which is 4.1.0-*.
