### ISSUE TITLE
First run experience breaks parsing of dotnet --version

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#3533]
## Steps to reproduce
Run dotnet --version

## Expected  behavior
To just have the version of the CLI in the output.

## Actual behavior
We will print the EULA and the offline progress in the output and after that the version, which means that things that rely on simply getting the version out of this command will fail.

We need to consider if we want to skip the First Run experience in some cases for the CLI and we need to decide exactly which those cases are.

cc @blackdwarf @piotrpMSFT @ericstj

**Comment by brthor** [comment]
Perhaps we only launch first run experience when/if you are also launching a verb? `dotnet new` for example

**Comment by piotrpMSFT** [comment]
@livarcocc we need to do either what @brthor suggested or just special case --version and --info.

**Comment by eerhardt** [comment]
Is this as simple as moving this call:

https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/dotnet/Program.cs#L58

to this line:

https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/src/dotnet/Program.cs#L127

?

Basically --help, --info, --version don't get the "first run" experience.

**Comment by brthor** [comment]
Spoke with @piotrpMSFT offline and it seems there might be more intricacy in ensuring telemetry doesn't run before the message has been shown
