### ISSUE TITLE
Getting a 404 for some of our documentation

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/cli#3534]
## Steps to reproduce
https://dotnet.github.io/docs/getting-started/getting-started/cli-console-app-tutorial.md

## Expected  behavior
I should see the tutorial

## Actual behavior
I get a 404 page

## Environment data
`dotnet --info` output:

**Comment by piotrpMSFT** [comment]
Moved to https://github.com/dotnet/core-docs/issues/525
