### ISSUE TITLE
"Duplicate attribute" error caused by generated assembly info

### ISSUE THREAD

**Issue by jodavis** [dotnet/cli#3540]
## Steps to reproduce
1. Open the attached repro project
2. Restore packages and build

## Expected  behavior
The build generates dotnet-compile.assemblyinfo.cs. This file should not contain an `[AssemblyInformationalVersionAttribute]` because one is already defined in Program.cs,

## Actual behavior
`[AssemblyInformationalVersionAttribute]` is included in dotnet-compile.assemblyinfo.cs, causing the following build error:

> error CS0579: Duplicate 'AssemblyInformationalVersion' attribute

This only happens when my `[AssemblyInformationalVersionAttribute]` is in the `#if VS14` section in Program.cs. It appears there is an initial parse to determine which assembly info attributes are already defined, but the build defines are not being used for this parse.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003041)

Product Information:
 Version:            1.0.0-preview2-003041
 Commit SHA-1 hash:  cc3d19463d

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by livarcocc** [comment]
I don't see an attached project here. Please, attach one and re-activate.
