### ISSUE TITLE
'Dotnet build' doesn't work with <assemblyname>.project.json ('dotnet restore' does)

### ISSUE THREAD

**Issue by EMaher** [dotnet/cli#3546]
## Steps to reproduce
1. Create new .NET Core library.
2. Rename project.json to `<AssemblyName>.project.json`.
3. On the command line run 'dotnet restore' in the appropriate directory.  Restore should succeed.
4. On the command line run 'dotnet build' in the appropriate directory.
## Expected  behavior

Build should succeed.  
'dotnet restore' works with `<assemblyname>.project.json`, so I expect 'dotnet build' to as well.
## Actual behavior

Build fails with message:
"Couldn't find 'project.json' in current directory"
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by ArturKarbone** [comment]
Have the same issue. Trying to port stateless library to .NET Core. Restore works, buid doesn't: ![](https://i.imgur.com/wAGmsb7.png)

**Comment by consigliory** [comment]
+1

**Comment by blackdwarf** [comment]
This is solved in Preview 3 and later tools (MSBuild-based ones). The easiest repro is to simply install the Preview 4 tools, for example, create a folder and run `dotnet new` in it.By default, the csproj name will be the folder name which will be the same as assembly name. You will be able to build this project. 

So, this is mitigated by MSBuild. I will close this issue as such. If in error or this repros on latest CLI, please reopen. Thanks!
