### ISSUE TITLE
Building on macOS exceeds ulimit -n

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#3548]
## Steps to reproduce
1) ./build.sh

## Expected  behavior
Success!

## Actual behavior
Internal Aggregate Exception due to too many open handles based on the default ulimit

**Comment by piotrpMSFT** [comment]
we already raise the ulimit in `/build_projects/dotnet-cli-build/build.sh`. The current ulimit is 1024. If this is blocking you, please raise to 2048.

**Comment by sokket** [comment]
Raising the ulimit requires sudo...we shouldn't require sudo to build and we shouldn't be opening > 1024 handles at one time during the build

**Comment by brthor** [comment]
Do we have a bug for whatever is opening this many file handles?

**Comment by sokket** [comment]
This is the bug; it's for the Archiver

**Comment by brthor** [comment]
Sorry am tired, what I meant is can we make this more targetted so it's apparent that it's the archiver which is the issue here, and get repro details if possible.

:smile:

**Comment by sokket** [comment]
@brthor The repro details are just build on a mac with default settings...the default ulimit of 1024 causes the build to break (unless the build is run as root, which shouldn't happen anyway).

**Comment by ericstj** [comment]
I have a fix for this.  https://github.com/ericstj/cli/commit/ade0d4235be6dff2149cebf8696104dc81eb3ca4

I based it off of Preview 2 and can bring it in if you want.  Otherwise I'll wait till the code hits the 1.0.0 branch and merge there.

**Comment by blackdwarf** [comment]
Is this now fixed?

**Comment by ericstj** [comment]
Yes it was fixed with https://github.com/dotnet/cli/pull/3604, not sure why GH didn't auto-close it.
