### ISSUE TITLE
dotnet-compile-fsc depends on deprecated API in System.Reflection.Metadata

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#3558]
In bringing the CLI onto stable versions of the we have run into an issue with Fsharp loading a type in System.Reflection.Metadata.

It looks like the type was  renamed here:
https://github.com/dotnet/corefx/commit/a9442a6fe0d0d616ce372018c86ff435cf5337c2 

More specifically, that type isn’t even public in MetadataReader 1.3.0.  Looks like FSharp is using the 1.4.0 API of the package and just hit a breaking change made in the API.  https://github.com/fsharp/fsharp/blob/25890f73b7491719a77c2f0014ad9960fca3283e/src/absil/ilwritepdb.fs#L361

Fix here is to get FSharp updated to the latest 1.4.0-rc4* package (knowing it won’t be going stable) and update their source.  If you need to ship a stable FSharp right now then this code will have to be removed.

Is this something that has been seen or dealt with in Fsharp yet?

We’re only seeing this error on Windows, any ideas why that might be the case?

The actual error:
`FS0193: internal error: Could not load type 'System.Reflection.PortableExecutable.ContentId' from assembly 'System.Reflection.Metadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

**Comment by joshfree** [comment]
adding @tmat @nguerrera who can comment further since they made those packaging changes

**Comment by eerhardt** [comment]
Closing.  I am removing these tests from the dotnet/cli repo.
