### ISSUE TITLE
dotnet restore with --ignore-failed-sources fails when DNS for the remote host cannot be resolved

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/cli#3560]
## Steps to reproduce
On Ubuntu 16.04, disable networking
`dotnet restore --ignore-failed-sources`

## Expected  behavior
Restore completes with warnings

## Actual behavior
log   : Restoring packages for {location}...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json
error:    An error occurred while sending the request.
error:    Couldn't resolve host name

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002678)

Product Information:
 Version:          1.0.0-rc2-002678
 Commit Sha:  3b2ea9d14b

Runtime Environment:
 OS Name:       ubuntu
 OS Version:    16.04
 OS Platform:   Linux
 RID:                ubuntu.16.04-x64

**Comment by mlorbetske** [comment]
cc @yishaigalatzer

**Comment by yishaigalatzer** [comment]
This should go to the nuget repo

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jun 14, 2016 at 10:00 AM -0700, "Mike Lorbetske" <notifications@github.com<mailto:notifications@github.com>> wrote:


cc @yishaigalatzer<https://github.com/yishaigalatzer>

-

**Comment by mlorbetske** [comment]
@yishaigalatzer which repo should I open this on under the NuGet org?

**Comment by mlorbetske** [comment]
Moved to NuGet/Home
