### ISSUE TITLE
Running setup fails to install dotnetcore.

### ISSUE THREAD

**Issue by abhidotnet** [dotnet/cli#3571]
I uninstalled the existing version of coreCLR on my machine. I have a windows 7 64 bit machine with professional version of Visual Studio 2015.

When I attempted to install vc_redist.x64.exe (Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026), I got an error in the logs that says
`Condition 'VersionNT64 >= v6.0 OR (VersionNT64 = v5.2 AND ServicePackLevel >= 1)' evaluates to true.`
`Error 0x80070666: Cannot install a product when a newer version is installed.`
When I attempted to install the **DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe**, it throws an error stating that `"Another version of this product is already installed"`

So I am unable to install this.

## Environment data
`dotnet --info` output:
```

'dotnet' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by armydee** [comment]
Same issue. I have VS 2015 Enterprise installed. 

It's incredibly annoying.

**Comment by esargent** [comment]
Same issue here, but with VS 2015 Pro RC3
I had dotnetcore RC2 installed and running, but the Visual Studio integration was weird so I uninstalled everything related to dotnetcore (any version). Then uninstalled Visual Studio and reinstalled.

With that done, Visual Studio is prompting me to upgrade tools and points me to the SDK installer, but when I try to run, I get the `another version of this product is already installed` error. Checking the version yields the `dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.` message. 

I tried running the installer from the command line with the -uninstall option. It reported it was doing that, but it didn't resolve the problem.

Programs and Features doesn't show anything related to dotnetcore being installed.

Installer log is attached.
[Microsoft_.NET_Core_1.0.0_RC2_-_SDK_Preview_1_(x64)_20160615130409.log.txt](https://github.com/dotnet/cli/files/317107/Microsoft_.NET_Core_1.0.0_RC2_-_SDK_Preview_1_.x64._20160615130409.log.txt)

Looks like there was a package left behind by the uninstallers? Can I delete that manually?

**Comment by esargent** [comment]
**FIXED**: I found there was a known issue with Tooling Preview (not explicitly SDK) after installing Visual Studio 2015 RC3 which has the same symptom: https://msdn.microsoft.com/en-us/vs-knownissues/vs2015-update3-rc

Specifically, you have to Repair the Visual C++ 2015 Redistributable (both x86 and x64) via the "Programs and Feature" Window (a.k.a. Add/Remove Programs)

This allowed me to install the SDK and the tooling preview. I hope it helps others as well.

**Comment by abhidotnet** [comment]
Yes. Esargent, This has worked for me. I was able to install the "DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe" after doing a repair just like you've suggested.

**Comment by ekiliqua** [comment]
Hi all, first sorry for my English because isn't my native languaje...

I'm learning with this project and have the same problem. I resolve this searching at Google. 

Quote: abhidotnet
> Yes. Esargent, This has worked for me. I was able to install the "DotNetCore.1.0.0.RC2-VS2015Tools.Preview1.exe" after doing a repair just like you've suggested.

I found this: https://www.microsoft.com/net/core#windowsvs2015 and work for me. Is the same solution but you have here the URL for download it.

**Comment by piotrpMSFT** [comment]
Thanks @ekiliqua. Do also try [VS 2017 RC](https://docs.microsoft.com/en-us/dotnet/) if you get a chance. The tooling has come a long way since Preview 1!
