### ISSUE TITLE
buildOptions does not merge correctly

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#3577]
## Steps to reproduce

Write a `project.json` that uses multiple `buildOptions` objects, one under root, and one under a particular framework, e.g.:

```json
{
    "buildOptions": {
        "compile": {
            "include": [ "some", "goodFiles" ]
        }
    },

    "frameworks": {
        "netstandard1.5": {
            "buildOptions": {
                "compile": {
                    "exclude": [ "other", "badFiles" ]
                }
            }
        }
    }
}
```

## Expected  behavior

Both `include` and `exclude` to be respected for `dotnet build -c netstandard1.5`, that is, the root included files to be included, and the framework excluded files to be excluded (the objects are merged).

This is inline with the proposal https://github.com/dotnet/core-proposals/pull/15 for the schema update https://github.com/aspnet/Announcements/issues/175 implemented in https://github.com/dotnet/cli/pull/2493.

> The `"buildOptions"` section can be defined in:
> - the root of the project file, in which case the properties apply **whenever compiling the project**
> - under an entry in the "`configurations`" section, in which case the properties apply when compiling with that configuration
> - under an entry in the "`frameworks`" section, in which case the properties apply when compiling for that framework

(Added emphasis my own.)

## Actual behavior

Only the `buildOptions` properties under the framework is respected, thus those files are excluded, but the root included files are **not** included.

Currently, the only way to get the intended behavior is to **duplicate** my root include into each of my supported frameworks, so that only one `buildOptions` object specifies everything for a particular build.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003093)

Product Information:
 Version:            1.0.0-preview2-003093
 Commit SHA-1 hash:  f4a8df3a56

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

/cc @ajaybhargavb

**Comment by ajaybhargavb** [comment]
Yes, currently the design is that the framework specific `compile`, `embed` etc has higher precedence and will be overridden as a whole and include/excludes won't be merged.

**Comment by andschwa** [comment]
Ah, I misunderstood the proposal then.

I think I have a common scenario: a project which targets multiple frameworks. The .NET Core and Desktop .NET flavors share a common set of files (`**/*.cs` plus the root `buildOptions: compile: include`), minus different sets of files to exclude for each framework (some files which should not be built for `netstandardapp1.5` and some which should not be built for `net451`).

As of now, I have to instead duplicate the `include` for each framework, and rather than have it inherited from the root.

**Comment by jasonwilliams200OK** [comment]
This is a pain-point and highly non-intuitive to re-include everything in a framework-specific buildOptions object. It should be merged rather replaced.

**Comment by andschwa** [comment]
The whole object should. Now I'm running into the need to exclude yet another subset just from my Linux build (at configuration time, since there is no per-runtime buildOptions, is there...?).

**Comment by andschwa** [comment]
@ericstj any chance we could get a milestone for this?

**Comment by ericstj** [comment]
@piotrpMSFT @blackdwarf  this is a request to layer some/all build options between the generic set and the framework specific set.  Can you please triage?

**Comment by livarcocc** [comment]
@brthor Another one that we should pay attention when migrating.

**Comment by livarcocc** [comment]
We already support this in MSBuild, although differently.

**Comment by brthor** [comment]
Added to tracking.
