### ISSUE TITLE
How to copy files from nuget directory in project.json?

### ISSUE THREAD

**Issue by 303248153** [dotnet/cli#3581]
Hi, I want copy SQLite.Interop.dll from nuget directory to my asp.net core output directory, how can I do that?
I known there are `copyToOutput` and `postbuild` configuration in project.json, just don't known how to use them.
And I can't find the document about project.json (only the out date one).

Also there are a releated question on stackoverflow:
http://stackoverflow.com/questions/36284533/project-json-referencing-sqllite

**Comment by blackdwarf** [comment]
@303248153 if the Nuget package containing that assembly is a direct dependency of your project, the `dotnet publish` command will copy that DLL for you.
