### ISSUE TITLE
dotnet build failed but vscode is succeed

### ISSUE THREAD

**Issue by xiaocen2050** [dotnet/cli#3582]
using dotnet build command is failed vsc debug is succeed 
-Method must have a return type
## Environment data

`dotnet --info` output:
Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by piotrpMSFT** [comment]
If you can share a repro we can take a look at the issue!
