### ISSUE TITLE
CLI and VisualStudio behave differently when testing with DependencyContext

### ISSUE THREAD

**Issue by ivaylokenov** [dotnet/cli#3583]
## Steps to reproduce

The following code returns different dependencies when testing through Visual Studio and when using `dotnet test`. I can see that Visual Studio is calling `dotnet test` behind the scenes but it is strange behavior.

``` c#
DependencyContext.Default.GetDefaultAssemblyNames()
```

Create class library with this `project.json` (note the ASP.NET Core MVC dependency added):

``` json
{
  "buildOptions": {
    "warningsAsErrors": true,
  },
  "dependencies": {
    "dotnet-test-xunit": "1.0.0-*",
    "XUnit": "2.1.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    },
    "net451": { } 
  },
  "testRunner": "xunit"
}
```

Write a test like this one:

``` c#
[Fact]
public void Index()
{
     throw new Exception(string.Join(",", DependencyContext
                .Default
                .GetDefaultAssemblyNames()
                .Select(s => s.Name)));
}
```

Run it through Visual Studio and see the exception message.
Then run it with `dotnet test` and see the exception message.
## Expected behavior

To receive all assembly names like in the Visual Studio test runner.
## Actual behavior

Receiving less dependencies. The ones specified in the `project.json` file are missing. The ASP.NET Core MVC dependencies are listed in VS but not in the console.
## Environment data

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

Am I missing something here?

**Comment by Antaris** [comment]
This might be the same issue as #4037 that I am having. I believe the Visual Studio test runner is only executing the first set of tests against the first listed framework `netcoreapp1.0`, and it won't actually run the tests for `net451`. You can test this yourself by running your unit tests at the command line using `dotnet test -f net451`.

**Comment by piotrpMSFT** [comment]
That's exactly right. The VS 2015 tooling invokes `dotnet test` with the active framework and therefore runs only the tests for that framework!

**Comment by Antaris** [comment]
@piotrpMSFT But with the unit test runner, how do you express **which** framework you want to run tests for?

**Comment by piotrpMSFT** [comment]
`dotnet test --framework netcoreapp1.0` for example.

**Comment by piotrpMSFT** [comment]
The preview2 help experience here is lackluster. We end up just showing the xunit-specific options. This should be fixed soon.

**Comment by Antaris** [comment]
@piotrpMSFT I think this issue specifically relates to the experience using VS's unit test runner. I am already using the `--framework` switch when I run tests as part of my build process, but I don't want to really have to manually run `dotnet test` for each framework when the unit test runner UI should display this for me.

**Comment by piotrpMSFT** [comment]
Yea, agreed that the VS experience needs improvement. This is being tracked, but it'll take longer to get the right model in the IDE.

The UI, btw, is able to test for each framework, just one at a time. You have a drop-down in the IDE for selecting the active framework in the code editor windows. The same drop-down influences the framework used by the test  window. Give it a shot! 

Here is an image I found online that shows the UI:
![image](https://cloud.githubusercontent.com/assets/2379589/20210844/563dd808-a7b0-11e6-8d72-6e9272a67d69.png)

The drop down in the top-left corner of this screen.

**Comment by Antaris** [comment]
Ah yes, sadly there is another annoying bug I've noticed where I select an alternative framework and VS keeps switching back ;-) good call though, didn't realise it was contextual this way.

**Comment by piotrpMSFT** [comment]
For the switching back issue, can you open a bug on https://github.com/aspnet/tooling?

**Comment by Antaris** [comment]
@piotrpMSFT Raised the bug @ https://github.com/aspnet/Tooling/issues/855

**Comment by piotrpMSFT** [comment]
Thanks!
