### ISSUE TITLE
net451 in OSX not working

### ISSUE THREAD

**Issue by chemitaxis** [dotnet/cli#3584]
## Steps to reproduce

1.- Create a project with Yeoman
2.- Target the framework 451 like this:

```
"frameworks": {
    "net451": {            
    }
  }
```

3.- Remove dependency Microsoft.NETCore.App 
4.- Execute dotnet restore
5.- Execute dotnet run
## Expected  behavior

Server is up in localhost:5000 and I can test my web app
## Actual behavior

You view an error like this:

![screen shot 2016-06-15 at 13 16 01](https://cloud.githubusercontent.com/assets/1420409/16077808/56e74674-32fb-11e6-81e0-93d79d7e3108.png)

```
Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
    public class _Views_Home_Index_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
Predefined type 'System.Boolean' is not defined or imported
    public class _Views_Home_Index_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
    public class _Views_Home_Index_cshtml : Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
        public Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
Predefined type 'System.Object' is not defined or imported
        public Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
Predefined type 'System.Void' is not defined or imported
        public Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

Thanks.

**Comment by psulek** [comment]
For Net Core 1.0 (RTM/Final) edit project.json as this:

```
{
xxxxxx
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
xxxxxx
}
```

Where `xxxxxx` is placeholder for your other stuff.

**Comment by chemitaxis** [comment]
I need to add net45 to the frameworks... Thanks!

**Comment by yaSebastian** [comment]
Same here. Targeting "netstandard1.2" works as a fallback, but results in a lot of dependent nugget packages being restored with my library. Targeting net45, net46 etc. does reduce restore time of my package *tremendously*.

**Comment by yaSebastian** [comment]
If you need to target `net45` for the same reason I did, targeting `net standard` version 1.2 and [reducing your dependencies](https://github.com/dotnet/core-docs/blob/master/docs/core/deploying/reducing-dependencies.md) might help. (It didn't solve my problem completely but reduced it's severity a lot.)

Finding a way to compile against .net 4.5 while only depending on `NETStandard.Library` would be great. (e.g. on macOS or Windows without .net 4.5 installed)

**Comment by piotrpMSFT** [comment]
Glad this was solved :)
