### ISSUE TITLE
Issues in porting a .NET library code from RC1 to RC2. Classes such as MarshalByRefObject are missing error

### ISSUE THREAD

**Issue by hovishwa** [dotnet/cli#3586]
## Steps to reproduce

Create a library project which uses classes such as MarshalByRefObject or SerializableAttribute or SecurityAttribute. Target dnxcore50 and have dependencies to RC1 assemblies. Compile and make sure a package is created and consumed in another test application. 
Now, follow the steps to migrate to RC2. Follow the steps such as uninstall dnvm,install dotnet etc. Make the necessary changes to project.json to different sections. Target netstandard1.3 and refer to RC2 binaries. When we compile we start getting exception indicating these classes are missing. I have this code also in my project.json but is not working. 
"frameworks": {
    "netstandard1.3": {
      "imports": [
        "dnxcore50",
        "portable-dnxcore50",
        "portable-net45+wp80+win8+wpa81+dnxcore50"
      ]
    }
## Expected  behavior

Expected behavior is, the library should compile as is or with minimum changes or there should be link helping us where to look for these classes.
## Actual behavior

I am getting a huge number of errors and not able to proceed.
## Environment data

`dotnet --info` output:
C:\VS2015>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

C:\VS2015>

**Comment by ericstj** [comment]
> MarshalByRefObject or SerializableAttribute

These were **never** exposed in DNXCore50 reference assemblies.  @davidfowl was DNX somehow exposing these private implementation types?

**Comment by piotrpMSFT** [comment]
The missing types are missing by-design, so closing.
