### ISSUE TITLE
Using a tool package from a local feed doesn't work

### ISSUE THREAD

**Issue by mrahhal** [dotnet/cli#3587]
I'm building a .NET Core cli tool and I want to test it before uploading a package. Now unfortunately tools can't be referenced from projects in the same solution (as was the case with dnx commands), so I built a package and I'm using a local feed to serve it.

The following is the error I get:

```
No executable found matching command "dotnet-[the path to the project that I'm testing the tool with]"
```

The expected command name should have been `dotnet-[toolname]` but the cli is looking for the name above instead. Everything works great if I use a previous version that I already uploaded to nuget.

So what is the best way to test tools locally?

## Environment data
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by BrainCrumbz** [comment]
@mrahhal when you say *unfortunately tools can't be referenced from projects in the same solution*, is there a reference explaining that? In my team I was trying to reference a dotnet test runner from project source, without passing for a local feed, and it does not work.

**Comment by mrahhal** [comment]
I don't exactly remember, but I think I checked the dotnet docs but found nothing. So I asked about it and someone in the dotnet team stated that it doesn't work, forgot where though. I closed this because local packages *do* work. I just had a problem elsewhere.

Currently I'm still using the local packages approach, but it is a big pain. I wonder what approach the team employs to test their tools (other than unit tests).

**Comment by brthor** [comment]
> Currently I'm still using the local packages approach, but it is a big pain. I wonder what approach the team employs to test their tools (other than unit tests).

The local packages approach should work, as you mentioned Project to Project tool references currently don't. 

In cli we have testing infrastructure that goes and builds our tools prior to restoring the rest of our test assets that may depend on those tools.

**Comment by mrahhal** [comment]
@BrainCrumbz [for your reference](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#targeting-class-library-projects-is-not-supported).

**Comment by BrainCrumbz** [comment]
Thanks. Here's a NuGet issue just about this: https://github.com/NuGet/Home/issues/2469

**Comment by mrahhal** [comment]
Ah sorry, the above reference is for another issue, I got them mixed up. Your link though is good, it appears there are discussions about it so we can hope.

**Comment by BrainCrumbz** [comment]
This other issue in cli project says the same (still by @brthor, thanks): https://github.com/dotnet/cli/issues/3239#issuecomment-243959757
