### ISSUE TITLE
Flakiness in e2e test

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#359]
I just had a PR CI run fail with the following:

````
17:45:30 Published to D:\j\workspace\Private\dotnet_cli_debug_windows_nt_prtest\artifacts\win7-x64\e2etest
17:45:31 foreach : Cannot retrieve the dynamic parameters for the cmdlet. The specified 
17:45:31 wildcard character pattern is not valid: \\n/cc @davidfowl @Sridhar-MS @brthor 
17:45:31 @krwq @anurse @livarcocc @Petermarcu\\n\\n<!-- Reviewable:start -->\\n[<img src
17:45:31 At D:\j\workspace\Private\dotnet_cli_debug_windows_nt_prtest\scripts\test\e2e-t
17:45:31 est.ps1:26 char:1
````

What's interesting here is that the invalid pattern is actually the last line of my initial commit message:

````
Fixes issue #342 
Enables CLI users and Visual Studio both to discover and execute tests given an implementation of dotnet-test-{testrunner}

/cc @davidfowl @Sridhar-MS @brthor @krwq @anurse @livarcocc @Petermarcu
````

I tried repro'ing this in PowerShell to no avail, so it seems something more interesting is going on. The console logs are here:

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_cli_debug_windows_nt_prtest/522/console

I'm going to try updating my commit message to get unblocked.

**Comment by piotrpMSFT** [comment]
Note, I noticed that a Code Review tool I use left this in my comment as well:

````
Fixes issue #342 
Enables CLI users and Visual Studio both to discover and execute tests given an implementation of dotnet-test-{testrunner}

/cc @davidfowl @Sridhar-MS @brthor @krwq @anurse @livarcocc @Petermarcu

<!-- Reviewable:start -->
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/dotnet/cli/344)
<!-- Reviewable:end -->
````

This might be associated with the issue in question.

**Comment by brthor** [comment]
This is interesting. It looks like the workaround for #301 is causing this issue somehow. Will take a look.

**Comment by brthor** [comment]
I believe this is being caused by newlines in environment variable values causing the value to be interpreted as multiple items for the foreach command. Also explains why your workaround in the PR is not working.

**Comment by piotrpMSFT** [comment]
@brthor, yep. But a fix already got merged :) #344

**Comment by brthor** [comment]
Nice @piotrpMSFT I would say this is a workaround not quite a fix. Environment variables in the CI can get created from the commit message in any PR, which is scary.

**Comment by piotrpMSFT** [comment]
The problem was not strictly newlines. The issue is that Set-Item -path treats -path as a pattern expression [e.g. C:\foo\bar\*.cs] and some characters in some EnvVar names ended up causing the Name of those variables to look like malformed patterns. By moving to -LiteralPath we would have dealt with this class of issues since it forces the string to be treated as a literal and not a pattern.
