### ISSUE TITLE
Add dependencies to C# project

### ISSUE THREAD

**Issue by kalmecak** [dotnet/cli#3590]
Hi!

I'm Using OSX El Capitan. 
I've installed all to make it work, I did type on terminal:

`dotnet new && dotnet restore && dotnet run`

And everything went fine, but I can not find how to add dependencies to my project, I have some dll I need to include but there is no documentation about adding custom dll, I've found "solutions" but all of them are solved with an **... right-click and "Include in project"...** but that solutions is not available without using Visual Studio.

When I try to run my project i got errors

My code:

`
using System;
using MyLibrary;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
`

In the project path I've added an "deps" directory which have MyLibrary.dll

And when I do **dotnet run**:

`error CS0246: The type or namespace name 'MyLibrary' could not be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    1 Error(s)`

How do I add this dependency?????

this is the directory:

Test
  |---- bin/
  |---- deps/ (here is my dll)
  |---- obj/
  |----Program.cs
  |----project.json
  |----project.lock.json

**Comment by blackdwarf** [comment]
@kalmecak the way to reference dependencies in .NET Core is either as a project-to-project reference (P2P for short) or as a NuGet package. You can find more information in our docs in the [library authoring article](https://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html#project-to-project-referencing) as well as [solution building article](https://dotnet.github.io/docs/scenarios/solution-authoring/cli-golden-path.html).

With the above, I will close this issue. If you still have questions, please reopen and @ me. Thanks!
