### ISSUE TITLE
First project build fails if --output is specified

### ISSUE THREAD

**Issue by pfedotovsky** [dotnet/cli#3606]
## Steps to reproduce

Sample project to reproduce the problem: http://github.com/pfedotovsky/aspnet-tests
1. Delete **bin** and **obj** folders if any (compile project for the very first time)
2. Run  `dotnet build --output <SomePath> --framework net452`
## Expected  behavior

No errors
## Actual behavior

Error:
_Failed to make the following project runnable: AppConfigIssue (.NETFramework,Version=v4.5.2) reason: Could not read assembly info for C:\Users\userred\Source\Repos\aspnet-tests\AppConfigIssue\src\AppConfigIssue\bin\Debug\net452\win7-x64\AppConfigIssue.exe_
## Environment data

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by stanuku** [comment]
I'm experiencing the same issue with 1.0.0-preview2-003133 (Win 2012 R2) on a build server.

**Comment by piotrpMSFT** [comment]
This didn't repro on preview3 bits. Please give it a shot and let us know if there is a lingering issue.
