### ISSUE TITLE
DependencyContext resolution of deep dependencies

### ISSUE THREAD

**Issue by stephenpope** [dotnet/cli#3608]
## Steps to reproduce

(Apologies for the long setup here !)

`Framework.Abstractions` contains interface `IAmAnInterface`
`Framework` references `Framework.Abstractions` in its `project.json`

`MyLibraryOne` references `Framework` in its `project.json`
`MyLibraryOne` has `ClassOne` that inherits from `IAmAnInterface`

`MyLibraryTwo` references `Framework` in its `project.json`
`MyLibraryTwo` has `ClassTwo` that inherits from `IAmAnInterface`

I am trying to work out all classes that inherit from `IAmAnInterface` .. since `LibraryManager` is no more I am using the `DependecyContext`

I am trying to replicate the `GetReferencingLibraries` that used to exist as part of `LibraryManager` and worked for me before (porting RC1 code -> RC2)
1. Grab the AssemblyName of `IAmAnInterface` (`Framework.Abstractions`)
2. Get `DependencyContext.Default` and loop through `RuntimeLibraries` looking in the `Dependencies` property for dependencies on `Framework.Abstractions`
## Expected  behavior

`DependencyContext` would be able to understand that `MyLibraryOne` and `MyLibraryTwo` have a dependency on `Framework.Abstractions`.
There would be some way to get a more accurate graph of the dependencies in the currently running application.
## Actual behavior / Discussion

I will never find the relationship between `MyLibraryOne` and `Framework.Abstractions` as it is not direct.

I will only find the relationship between `Framework` and `Framework.Abstractions`

I will have to loop through the `RuntimeLibraries` again now looking for dependencies on `Framework` and so on.

If the graph gets more complex (dependencies sit deeper) than this I would have to loop over and over to get the correct result.

In the past there were dependency walkers and other ways to get this relationship out.

It may be that there is a better way to do this (please let me know if there is !) but for now it seems like the `DependencyContext` is missing something for this sort of resolution.
## Environment data

dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by davidfowl** [comment]
It's a pretty simple graph walk but yes it would be a nice feature to add.

**Comment by piotrpMSFT** [comment]
Moved to coresetup repo
