### ISSUE TITLE
PostCompile doesn't work

### ISSUE THREAD

**Issue by pfedotovsky** [dotnet/cli#3611]
## Steps to reproduce

Sample project to reproduce the problem: [http://github.com/pfedotovsky/aspnet-tests](http://github.com/pfedotovsky/aspnet-tests)

It contains PostCompile build action that just copies dlls to another location.
1. Delete **bin** and **obj** folders if any (compile project for the very first time)
2. Run `dotnet build`
## Expected  behavior

PostCompile is run, and dlls are copied
## Actual behavior

DLLs ARE not copied, seems like PostCompile step didn't run.
## Environment data

.NET Command Line Tools (1.0.0-preview1-002702)
Time elapsed 00:00:01.7265386
Product Information:me can be improved. Run "dotnet build --build-profile" for more information)
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225ece\Repos\aspnet-tests\AppConfigIssue\src\AppConfigIssue>

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
postcompile scripts are replaced with AfterTargets in preview3. These are much more flexible and the engine provides better handling than in project.json.

https://msdn.microsoft.com/en-us/library/ee216359.aspx#BeforeTargets and After Targets
