### ISSUE TITLE
Implement dotnet new --lang f# --type lib

### ISSUE THREAD

**Issue by wyoung** [dotnet/cli#3612]
According to [the `dotnet-new` docs](https://github.com/dotnet/cli/tree/rel/1.0.0-preview2/src/dotnet/commands/dotnet-new), C# now has a `lib` type, not yet available in RC2. I would like the same thing to be added for F#, hopefully before the next release.

A `lib` target is more important for F# than for C#, IMHO, since F# is still in the early-adopter phase. Mixing an F# library into an existing C# project or adding an experimental F# module to a new project run by old C# hands is more common than adding a freshly-created C# library for an F# program. 

(Obviously linking old C# libraries to new F# programs is *very* common, but that's a different matter entirely.)

**Comment by enricosada** [comment]
I'll do that

**Comment by wyoung** [comment]
I just found [a guide](https://github.com/dotnet/netcorecli-fsc/wiki/FAQ#user-content-ok-how-do-i-start-converting-a-project) for manually converting the generated console app project to a library target. It looks pretty simple. Without any sense of entitlement express or implied, may I ask what the holdup is? :)

**Comment by enricosada** [comment]
@wyoung waiting for a package to be published on nuget.org

**Comment by wyoung** [comment]
@enricosada Thank you!

**Comment by tlycken** [comment]
Any news on this? I'm struggling on an application where I want to create an F# library and reference it from a C# app (both .NET Core, and mainly as a learning exercise), and with a ready-made template for F# projects intended to use this way it would be much easier for me to rule out possible errors.

Is [this](https://www.nuget.org/packages/System.Reflection.Metadata/1.4.1-beta-24227-04) the package you were waiting for?

**Comment by livarcocc** [comment]
I see we have one now.
