### ISSUE TITLE
DthTests begin timeout randomly on rel/1.0.0 branch

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#3614]
DthTests begin failing randomly on `rel/1.0.0` branch recently. This is after the timeout is expanded to 20 seconds. Tests had been stabled for awhile.

It is known that tests are unstable while run on low performance machines.

It may worth to investigate a alternative approach to run these scenarios other than the current E2E model.

**Comment by piotrpMSFT** [comment]
DTH was removed as part of preview3
