### ISSUE TITLE
dotnet new with 'Web' should generate a different userSecretsId everytime

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#3617]
## Steps to reproduce
- dotnet new -t Web in a folder1
- dotnet new -t Web in a folder2
- compare the generated project.json content and you should notice the same value for `userSecretsId` value
## Expected  behavior

`userSecretsId` value should be different as they are different apps and can have different config values.
## Actual behavior

Not sure if this is hard coded, but I always see `"userSecretsId": "aspnet-WebApplication-0799fe3e-6eaf-4c5f-b40e-7c6bfd5dfa9a",` when creating apps.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003102)

Product Information:
 Version:            1.0.0-preview2-003102
 Commit SHA-1 hash:  0589496b98

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

@ajaybhargavb

**Comment by blackdwarf** [comment]
@danroth27 if we move to the "empty template" as the default template, would this issue still be applicable?

**Comment by kichalla** [comment]
This not be applicable if we move to empty template

**Comment by piotrpMSFT** [comment]
Moved to templating repo

**Comment by Rick-Anderson** [comment]
@TheRealPiotrP  can you supply a link?

**Comment by Rick-Anderson** [comment]
@TheRealPiotrP  I'm guessing they fixed the bug by dropping `userSecretsId` from the dotnet templates while leaving it in the VS generated templates. I need a way to get  `userSecretsId` from dotnet

`dotnet new webapp -o WebPWrecover`

Doesn't generate one, but VS does.
