### ISSUE TITLE
dotnet restore fails for all the assemblies

### ISSUE THREAD

**Issue by KasunKoswattha** [dotnet/cli#3618]
Run: dotnet new
Run: dotnet restore

**dotnet Version:** 
C:\Test>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
## Expected  behavior

Restoring 
## Actual behavior

Fails for all the assemblies
## Environment data

Some of the output data (couldn't post the whole thing since it is so big )

C:\Test>dotnet restore
log  : Restoring packages for C:\Test\project.json...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
info :   CACHE https://tfs/nuget/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
info :   CACHE https://tfs/nuget/nuget/FindPackagesById()?id='Microsoft.NETCore.DotNetHost'
error: Package Microsoft.CSharp 4.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.CSharp 4.0.1-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.0 (.NETStandard,Version=v1.0)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - win8 (Windows,Version=v8.0)
error:   - wp8 (WindowsPhone,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package Microsoft.VisualBasic 10.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.VisualBasic 10.0.1-rc2-24027 supports:
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.1 (.NETStandard,Version=v1.1)
error:   - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
error:   - win8 (Windows,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error: Package System.Buffers 4.0.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Buffers 4.0.0-rc2-24027 supports: netstandard1.1 (.NETStandard,Version=v1.1)
error: Package System.Collections.Immutable 1.2.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Collections.Immutable 1.2.0-rc2-24027 supports:
error:   - netstandard1.0 (.NETStandard,Version=v1.0)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error: Package System.ComponentModel 4.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.ComponentModel 4.0.1-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.0 (.NETStandard,Version=v1.0)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - win8 (Windows,Version=v8.0)
error:   - wp8 (WindowsPhone,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.ComponentModel.Annotations 4.1.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.ComponentModel.Annotations 4.1.0-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.1 (.NETStandard,Version=v1.1)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - netstandard1.4 (.NETStandard,Version=v1.4)
error:   - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
error:   - win8 (Windows,Version=v8.0)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.Diagnostics.DiagnosticSource 4.0.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Diagnostics.DiagnosticSource 4.0.0-rc2-24027 supports:
error:   - net46 (.NETFramework,Version=v4.6)
error:   - netstandard1.1 (.NETStandard,Version=v1.1)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
error: Package System.Diagnostics.Process 4.1.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Diagnostics.Process 4.1.0-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - netstandard1.4 (.NETStandard,Version=v1.4)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.Dynamic.Runtime 4.0.11-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Dynamic.Runtime 4.0.11-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.0 (.NETStandard,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - win8 (Windows,Version=v8.0)
error:   - wp8 (WindowsPhone,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.Globalization.Extensions 4.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Globalization.Extensions 4.0.1-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.IO.FileSystem.Watcher 4.0.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.IO.FileSystem.Watcher 4.0.0-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.IO.MemoryMappedFiles 4.0.0-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.IO.MemoryMappedFiles 4.0.0-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.IO.UnmanagedMemoryStream 4.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.IO.UnmanagedMemoryStream 4.0.1-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.Linq.Expressions 4.0.11-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Linq.Expressions 4.0.11-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.0 (.NETStandard,Version=v1.0)
error:   - netstandard1.3 (.NETStandard,Version=v1.3)
error:   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
error:   - win8 (Windows,Version=v8.0)
error:   - wp8 (WindowsPhone,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.Linq.Parallel 4.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Linq.Parallel 4.0.1-rc2-24027 supports:
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net45 (.NETFramework,Version=v4.5)
error:   - netcore50 (.NETCore,Version=v5.0)
error:   - netstandard1.1 (.NETStandard,Version=v1.1)
error:   - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
error:   - win8 (Windows,Version=v8.0)
error:   - wpa81 (WindowsPhoneApp,Version=v8.1)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error:   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
error:   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
error: Package System.Linq.Queryable 4.0.1-rc2-24027 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package System.Linq.Queryable 4.0.1-rc2-24027 supports:

**Comment by hanigan6** [comment]
New install of dotnet 1.0 getting the same issue but with
**DotNet --info**

-     Version: 1.0.0-preview2-003121

**Runtime Environment**

-     OS NAME: Windows
-     OSVersion: 6.1.7601 (x64)

**Comment by KasunKoswattha** [comment]
@hanigan6 I had to reformat my development PC after I got the initial error. I think when you uninstall previous version, it does not delete all the files or something. I did not get any solid answer from Microsoft. After reformatting, it worked file. :(

**Comment by piotrpMSFT** [comment]
I would have loved to see the nuget.config file summary from the bottom of this. We've seen such restore failures when folks were using the product before the packages hit nuget.org. If it's persistent, there's usually a NuGet.config in the way that is blocking nuget.org.

In general, formatting a machine is never required. The development environment has two stores of artifacts on disk:
 - The NuGet package cache, including various NuGet.config install locations. The cache is typically in a .nuget directory in the user's home directory. The NuGet.configs get printed in the summary of a restore.
 - The dotnet install directory. `where dotnet` will yield the root directory which, once deleted, is gone. Of course, if you used a native installer e.g. Exe on Windows or apt-get on Ubuntu, please use the uninstallation gesture

Thanks for reporting!
