### ISSUE TITLE
warning NU1012: Dependency conflict.

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/cli#362]
Installed CLI via official MSI installer and continued according to the http://dotnet.github.io/getting-started/

init, restore, run

Here is the output:

C:\dd>dotnet run
C:\dd\project.json(9,22): warning NU1012: Dependency conflict. Microsoft.NETCore.Runtime.CoreCLR 1.0.1-beta-23516 expected System.IO 4.0.11-beta-23516 but got 4.0.10-beta-23109
C:\dd\project.json(9,22): warning NU1012: Dependency conflict. Microsoft.NETCore.Runtime.Native 1.0.1-beta-23516 expected System.IO 4.0.11-beta-23516 but got 4.0.10-beta-23109
Hello World!

Note that I previously built NET CORE & FX from source on the same machine (Win10)

**Comment by anurse** [comment]
This can happen when your project.json refers to a version of a package which is not present on the feeds you are restoring with. Sounds like `dotnet init`'s template needs to be updated.

**Comment by anurse** [comment]
FYI, you can work around this by changing those packages to the version that you got anyway: `4.0.10-beta-23109`.

dotnet init should probably only be using packages from NuGet.org, it looks like these are versions that are only present on the dotnet-core MyGet feed.

**Comment by clrjunky** [comment]
Here is the original project.json that the cli generated:

 {
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": { 
        "Microsoft.NETCore.Runtime": "1.0.1-beta-*",
        "System.IO": "4.0.10-beta-*",
        "System.Console": "4.0.0-beta-*",
        "System.Runtime": "4.0.21-beta-*"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

Here is the one after applying the changes::

{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": { 
        "Microsoft.NETCore.Runtime": "4.0.10-beta-23109",
        "System.IO": "4.0.10-beta-*",
        "System.Console": "4.0.0-beta-*",
        "System.Runtime": "4.0.10-beta-23109"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

I did dotnet restore 

Here is the output after running the program:

C:\dd>dotnet run
C:\dd\project.json(8,38): error NU1001: The dependency Microsoft.NETCore.Runtime >= 4.0.10-beta-23109 could not be resolved.
C:\dd\project.json(11,27): warning NU1012: Dependency conflict. System.IO 4.0.10-beta-23109 expected System.Runtime >= 4.0.20-beta-23109 but got 4.0.10-beta-23109

**Comment by piotrpMSFT** [comment]
@clrjunky can you confirm this is fixed once new bits roll out?

**Comment by clrjunky** [comment]
Sure, just ping me when it's ready (I doubt I'll remember :)

**Comment by anurse** [comment]
We should not be using `*` in the template. `*` is designed solely for interconnected packages built by the same team. It is designed for referencing builds directly off build machines only, not for getting the latest version of public feeds like NuGet.

It is also highly dependent upon the feeds the user has configured. We should either a) do what our ASP.NET templates do and fill in the `*` values during the template build or b) replace these with the exact build numbers in the template source.

/cc @davidfowl

**Comment by blackdwarf** [comment]
This work will be tracked by #460 so closing this issue.
