### ISSUE TITLE
Wrong assembly information / exe file details (MVC Core RC2/RC3)

### ISSUE THREAD

**Issue by LukaszDev** [dotnet/cli#3620]
Original issue: [aspnet/Home #1573](https://github.com/aspnet/Home/issues/1573).

## Steps to reproduce

**1.** Create new `ASP.NET Core Web Application (.NET Framework 4.6.1)` / `MVC` / `VS2015 U2`.
**2.** Add project.json info:

```
{
  "title": "Test Title",
  "version": "2.0.2-test",
  "copyright": "Copyright © 2016 Test",
  "description": "Test Description",
  "language": "en-GB",
  ...
```

_(At this step almost all assembly details looks fine after build, except `Product Name` and `Language`)_

**3.** Use following bower components

```
{
  "name": "performance",
  "private": true,
  "dependencies": {
    "bootstrap": "3.3.6",
    "bootstrap-datepicker": "1.6.1",
    "jquery": "2.2.4",
    "jquery-validation": "1.15.0",
    "jquery-validation-unobtrusive": "3.2.6",
    "font-awesome": "4.6.3",
    "animate.css": "3.5.1",
    "pace": "1.0.2",
    "raphael": "2.2.0",
    "morrisjs": "0.5.1",
    "justgage-toorshia": "1.2.2",
    "jqplot": "*",
    "jSignature": "2.0.2"
  }
}
```
**4.** Build
**5.** Check 'Properties -> Details tab` of exe file.

## Expected  behavior
All information on 'Details' tab, should be taken from 'project.json' only - or should be empty.
Any of 3rd-party libs (like as bower components) should have no impact on those information.

## Actual behavior
Some of  3rd-party libs (bower components) cause wrong information about assembly.

Almost all properties are wrong, only `Product Version` seems to be ok:
 - `File Desctiption`  - incorrect
 - `File Version`  - incorrect,
 - `Product Name`  - incorrect,
 - `Product Version`  - ok
 - `Copyright`  - incorrect,
 - `Language`  - incorrect,

Please note that  `jSignature`  in  `Product Name`  and  `File Desctiption` fields is JavaScript library  installed via bower! - I don't have idea from where it can be taken.

The same after compiling as Debug and Release, also after publishing.

Below printscreen how it looks:

![image](https://cloud.githubusercontent.com/assets/17419186/16131953/e27f47dc-3408-11e6-9cd5-7ab049f41b25.png)

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by LukaszDev** [comment]
I found source of problem... `jSignature` component has extra content which contain `AssemblyInfo.cs` !?!?

As far I understand CLI, not using info form `project.json` when `AssemblyInfo.cs` is in project?

It's not intuitive, because should be only one place where we can set those information - in this case it should be 'project.json'...

But ok, I understand idea... and can agreed that `AssemblyInfo.cs` in my project (in `Properties` folder of my project) has higher priority then `project.json` - it's ok if it's documented ;)

But in that case all `wwwroot` (and all 3rd-party libs) should be excluded from this rules - we do not have full control of content those libs.

_(Theoretically I can delete problematic content manually, but this is not a solution - it will be working only to next update of bower components)._

<br>
By the way: **Where I can / should set `Product Name` in ASP.NET Core WebApp ?**

`AssemblyInfo.cs` is not included in default project created from VS template, and there is no `name` property in `project.json` file...

**Comment by LukaszDev** [comment]
cc: @blackdwarf, @GuardRex, @khellang

**Comment by khellang** [comment]
@LukaszDev You should exclude the wwwroot folder from compilation:

```json
"buildOptions": {
  "compile": {
    "exclude": [ "wwwroot" ]
  }
}
```

I'm not sure if that path will work, but something along those lines.

**Comment by LukaszDev** [comment]
> You should talk to the people shipping the jSignature component.

Of course, I will.

However still this is not solution in general case - I have no control what author can include into bower components...

For me better solution is having control on project level, and looks like your suggestion works fine:

>I think you can get around it by excluding the wwwroot folder from compilation:
> ```
> "buildOptions": {
>   "compile": {
>     "exclude": [ "wwwroot" ]
>   }
> }
> ```
> I'm not sure if that path will work, but something along those lines.

Thank you @khellang - this works perfectly for me :)

**Comment by LukaszDev** [comment]
Back to my second question 'Where I can / should set  Product Name  in ASP.NET Core WebApp?'

This field is always empty in my case.

It's not documented (and is not on VS intellisense list), but looks like we can use `name` properties in `project.json` file (without spaces) - this set/change project name & assembly name... however still not set `Product Name` in assembly details.

So my question is still open, if any one know answer :)

Thanks in advance.

**Comment by khellang** [comment]
@LukaszDev Awesome that you figured it out. You can still use the good old assembly attributes to set this information, just like before.

If you don't set the metadata using attributes, the dotnet CLI will generate an AssemblyInfo.cs file for you during compilation, based on project.json metadata.
The mapping from metadata to assembly attributes can be seen [here](https://github.com/dotnet/cli/blob/0708fe095e5198a245bc483a2ee3b44183d1ebaf/src/Microsoft.DotNet.Compiler.Common/AssemblyInfoFileGenerator.cs#L66-L73).

**Comment by LukaszDev** [comment]
@khellang thanks for all tips.

Adding 'AssemblyInfo.cs' is ok as temporary solution, however in long term I will prefer have only 'one place' to do this ;)

> Maybe close this issue and file a new one, more specific to that? Though I guess there won't be a huge willingness to invest much more into project.json since it's going away Very Soon™.

I will ask about this in separated discussion, however I'm not sure about closing this topic yet.

**Original issue is still the issue...** and I know that there is solution to sort this, but it's not documented well - so I would like to draw attention of dotnet/cli team - it's not a big issue - however:

 - it's worth add a note to official documentation about potentially issue and the solution,
 - and maybe it's worth to sort this by default in the new projects templates.

**Comment by LukaszDev** [comment]
> it's worth add a note to official documentation about potentially issue and the solution,
> and maybe it's worth to sort this by default in the new projects templates.

I found a more appropriate place for those discussions, and this issue is solved, so I'm closing.
