### ISSUE TITLE
dotnet publish - NullReferenceException

### ISSUE THREAD

**Issue by CezaryRynkowski** [dotnet/cli#3624]
## Steps to reproduce
dotnet -v publish

## Expected  behavior
Create packages to deploy

## Actual behavior

> Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.ProjectModel.ProjectModelPlatformExtensions.CollectDependencies(IDictionary`2 exports, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.DotNet.ProjectModel.ProjectModelPlatformExtensions.CollectDependencies(IDictionary`2 exports, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.DotNet.ProjectModel.ProjectModelPlatformExtensions.CollectDependencies(IDictionary`2 exports, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.DotNet.ProjectModel.ProjectModelPlatformExtensions.CollectDependencies(IDictionary`2 exports, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.DotNet.ProjectModel.ProjectModelPlatformExtensions.GetPlatformExclusionList(ProjectContext context, IDictionary`2 exports)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishProjectContext(ProjectContext context, String buildBasePath, String outputPath, String configuration, Boolean nativeSubdirectories)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.PublishAllProjects()
   at Microsoft.DotNet.Tools.Publish.PublishCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(String[] args)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-002900)

Product Information:
 Version:            1.0.0-preview2-002900
 Commit SHA-1 hash:  f4ceb1f213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14342
 OS Platform: Windows
 RID:         win10-x64

restore/build/run running without errors

**Comment by blackdwarf** [comment]
@CezaryRynkowski can you please post your `project.json` file?

**Comment by Tazer** [comment]
Hello @blackdwarf , I'm having the same problem. 

here is my `project.json`

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Newtonsoft.Json": "8.0.3",
    "Swashbuckle": "6.0.0-beta9",
    "System.Linq": "4.1.0-rc2-24027",
    "IdentityServer4": "1.0.0-beta2-update1",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "IdentityServer4.AccessTokenValidation": "1.0.0-beta6",
    "RavenDB.Client": "3.0.3781-Unstable",
    "StackExchange.Redis": "1.0.488",
    "NHibernate.Caches.Redis": "2.0.0",
    "ezyCMS": "1.0.0",
    "StructureMap.Dnx": "0.5.1-rc2-final",
    "NHibernate": "3.3.3.4001",
    "Microsoft.Extensions.Caching.Abstractions": "1.0.0-rc2-final",
    "Microsoft.Extensions.Caching.Memory": "1.0.0-rc2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "net461": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ],
      "dependencies": {
        "CsProjProject": {
          "target": "project"
        }

      },
      "frameworkAssemblies": {
        "System.Data.Linq": "4.0.0.0"
      }
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "xmlDoc": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by GuardRex** [comment]
IdentityServer4 at `1.0.0-beta3` https://www.nuget.org/packages/IdentityServer4/1.0.0-beta3 

IdentityServer4.AccessTokenValidation is up to `1.0.0-beta8` https://www.nuget.org/packages/IdentityServer4.AccessTokenValidation/1.0.0-beta8

RavenDB.Client is at `3.5.35125-Unstable` https://www.nuget.org/packages/RavenDB.Client/3.5.35125-Unstable

Wondering if your NRE's are due to old packages ... perhaps others there as well.

**Comment by blackdwarf** [comment]
I think it could do with the fact that `Microsoft.NETCore.App` is put in the dependencies and `project.json` (at least the one posted above, thanks @Tazer) targets `net461`. @Tazer did `dotnet restore` run on that `project.json` successfuly?

**Comment by Tazer** [comment]
I will try to fiddle with my project.json tomorrow.

Yes `dotnet restore works`, but need to run `dotnet restore restore.dg`
(generated in .vs folder ). Else it will complain about the csproj
reference.

**Comment by Tazer** [comment]
Found out my problem at least and it was:
```
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
```

So when removing that as a dep , it works fine. Thanks for the help @blackdwarf  , But not sure if  @CezaryRynkowski  has the same problem as he havn't posted is `project.json`

**Comment by blackdwarf** [comment]
@Tazer yes, you need the metapackage dependency above only if you are targeting `netcoreapp1.0`. If you are targeting the full framework, you don't need it. However, the error does leave something to be desired.

**Comment by Tazer** [comment]
Understand , but yeah , a more friendly error would be awesome :)

**Comment by blackdwarf** [comment]
@CezaryRynkowski did this solution help you as well?

**Comment by CezaryRynkowski** [comment]
This solution unfortunetly no, but new dotnet RTM resolved :)
