### ISSUE TITLE
If i optout the telemetry (using env var), the telemetry cache is built anyway

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#3625]
The telemetry cache is built anyway, ignoring `DOTNET_CLI_TELEMETRY_OPTOUT` env var

I hope this can be improved, because on ci server who reinstall the dotnet sdk each time (like appveyor/travis) some time is wasted to build the telemetry cache for first time (with telemetry optout)

## Steps to reproduce

- Download a new sdk
- set DOTNET_CLI_TELEMETRY_OPTOUT=1
- `dotnet new`

## Expected  behavior

usual `dotnet new` output, and no telemetry cache built

## Actual behavior

The telemetry cache is built anyway

```
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.

...

```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003119)

Product Information:
 Version:            1.0.0-preview2-003119
 Commit SHA-1 hash:  0708fe095e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by enricosada** [comment]
nvm confused the telemetry message with local package cache

**Comment by GuardRex** [comment]
Yes, the env var kills it before anything happens: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/Telemetry.cs#L35-L40
