### ISSUE TITLE
There's no mapping from project.json metadata to the AssemblyProductAttribute

### ISSUE THREAD

**Issue by LukaszDev** [dotnet/cli#3630]
Thanks @khellang for [investigate it](https://github.com/dotnet/cli/issues/3620#issuecomment-226746914) (Original issue: #3620).
## Steps to reproduce

Look [here](https://github.com/dotnet/cli/blob/0708fe095e5198a245bc483a2ee3b44183d1ebaf/src/Microsoft.DotNet.Compiler.Common/AssemblyInfoFileGenerator.cs#L66-L73) or
1. Create new ASP.NET Core Web Application project in VS2015,
2. Don't include `AssemblyInfo.cs` !
3. Optionally: add metadata into `project.json`,
4. Build project
5. Check 'Properties -> Details tab' of your project assembly / exe file
## Expected  behavior

`Product Name` should have some value by default - it can be Project Name, but also it should be possible to define it like as metadata in `project.json`.
## Actual behavior

`Product Name` is empty by default (if project not include `AssemblyInfo.cs` with `AssemblyProduct` attribute).

Adding `AssemblyInfo.cs` is ok as temporary solution, however in long term I will prefer have only 'one place' to do this - and looks like the `project.json` is new way to do this ;)

So, it looks like missing mapping from 'project.json', please look [here](https://github.com/dotnet/cli/blob/0708fe095e5198a245bc483a2ee3b44183d1ebaf/src/Microsoft.DotNet.Compiler.Common/AssemblyInfoFileGenerator.cs#L66-L73) .
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
Moved to SDK repo
