### ISSUE TITLE
Enhance the installation script to support "admin mode"

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#3637]
## Overview

We have designed the installation script from the beginning to not require `sudo`, that is, elevated privileges on the operating system it is ran on. This is a very good thing for various CI environments, for example, where users may not be in the security group that even allows elevated privileges. The effect of this is that the script will check for needed dependencies and it will fail with errors if they are not found. The user has to install these manually. 

However, as we progress towards adding more supported platforms for .NET Core, there is a need to use the script even in setting up users' development environment. So far, we've heard feedback from users that they would like for the installation script to do "all the things", that is, for the script to install dependencies as well.

To support both of the above cases, I propose that we add support to the script for detection of whether it is running in superuser (admin) mode and install dependencies if that is the case.
## Behavior

For the script, there are now two main modes of execution:
1. Non-admin mode
2. Admin mode

In the first mode, the behavior is as it is currently. The only change is to the output of the errors in case of missing dependencies. We would add the line that it is possible to get them if the user runs under admin mode. The exact text is TBD.

In second mode, the script would run the command to get the needed dependencies for the operating system. The user would be able to override this behavior if needed/wanted via a switch (for example, if the user wants to use the script to install in a global location on Linux/macOS but wants to manage dependencies manually).
## Changes to the script
1. Detect whether it is running elevated
2. Automate calling the appropriate package manager and installing the dependencies in the background
3. Add a `--skip-deps` switch to skip step 2 above in admin mode.
4. Add additional text to the error in non-admin mode.

/cc @krwq @piotrpMSFT @eerhardt @brthor

**Comment by livarcocc** [comment]
Closing as something that we do not have plans to do. For global installations, you should use the native installers.
