### ISSUE TITLE
Recent build result in broken Visual Studio experience

### ISSUE THREAD

**Issue by phenning** [dotnet/cli#3638]
## Steps to reproduce
1.  Install 1.0.0-preview2-003118 CLI via the EXE installer
2.  Delete your %UserProfile.nuget\packages folder (as though you were a new user)
3.  Launch VS, create any .NET Core project
## Expected  behavior

Project to be created and start restoring
## Actual behavior

Unable to connect to the project model server process.

I believe this is happening because the initial restore has not happened at this yet. If you manually run dotnet new or similar before launching VS, everything is fine. This is a regression from previous builds
## Environment data

`dotnet --info` output:

**Comment by livarcocc** [comment]
@phenning Which version of the VS core tools are you using? I want to make sure that I have the same when trying a repro.

I wonder if the first run experience has anything to do with this. Is there any log as to why it fails to connect to the project model server process?

**Comment by piotrpMSFT** [comment]
@troydai

**Comment by rainersigwald** [comment]
@livarcocc I hit this on a clean Server 2012 R2 VM with Update 3 slipstream + .NET Core MSI installed from public links (http://dot.net/core).

**Comment by troydai** [comment]
Is the `dotnet` process started for project model server?

**Comment by piotrpMSFT** [comment]
This is a known issue. Take a look at https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md for a workaround.
