### ISSUE TITLE
EULA link in README is broken

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3641]
[README.md](https://github.com/dotnet/cli/blob/rel/1.0.0/README.md) contains a link to the EULA: https://aka.ms/dotnet-cli-eula. That URL redirects to https://github.com/dotnet/cli/blob/master/packaging/osx/sharedframework/resources/en.lproj/eula.rtf, which is incorrect for several reasons:

1. There is no `master` branch.
2. It should be `clisdk`, not `sharedframework`.
3. Per #2731, it points to the RTF source. Using `raw` link instead would mean people would download the file instead.

So, assuming the rest of the link (which looks OS X-specific) is actually correct, https://aka.ms/dotnet-cli-eula should be redirected to https://github.com/dotnet/cli/raw/rel/1.0.0/packaging/osx/clisdk/resources/en.lproj/eula.rtf. Or maybe README should use a non-aka.ms link, for better flexibility.

**Comment by blackdwarf** [comment]
The whole README.md is broken. Will make a PR for this.

**Comment by blackdwarf** [comment]
This is now fixed.
