### ISSUE TITLE
Need a way to know which FX version SDK zips target

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#3646]
Currently we produce Combined SDK_FX zip files for Rapid Update.

With FX stabilizing, the FX version is pinned at 1.0.0 in these zips. This affects deploying these zip files because the FX is always getting overwritten the second time onwards.

We need to have separate FX and SDK zips -- but this creates other issues like version mismatches and roll-forwards (since we don't downgrade), the burden of picking the right combination is left on consumers.

We should produce an "artifacts.txt" file that contains all CLI build outputs and inputs, so consumers can download an SDK.zip and a corresponding FX.zip.

Cc @eerhardt @piotrpMSFT @leecow @gkhanna79 

@piotrpMSFT I am assigning this to you as this ties up with the long term plans you have for producing build artifacts metadata with each build.

**Comment by gkhanna79** [comment]
@schellap Why is the marked for preview2 and which partner is it blocking?

**Comment by schellap** [comment]
Antares, for rapid update unzips of sdk builds.

**Comment by leecow** [comment]
@schellap when we spoke the plan was to hand roll the fx and sdk zip for Antares to get unblocked then work through the automation as a post rtm/preview 2 work item. Is that still the case?

**Comment by schellap** [comment]
Yes, this is for upgrade (second time deployment)

**Comment by gkhanna79** [comment]
> Antares, for rapid update unzips of sdk builds.

@schellap Is this a new requirement since this was not called out in Friday's shiproom?

CC @Petermarcu.

**Comment by schellap** [comment]
We've always supported Antares MSI and zips and their rapid updates since https://github.com/dotnet/cli/pull/2670. The combined FX and zip breaks inzip upgrade for RTM Stable but CLI preview2/preview3 rev up builds.

**Comment by piotrpMSFT** [comment]
@schellap why is this `preview2` blocking?

**Comment by schellap** [comment]
I have manually verified the upgrade scenarios. I haven't been able to sign off on Antares validation exactly in the manner Antares folks would have unzipped, ex: unzip 2 files while apps are running. Their deployment scripts have to tie up with our download storage formats and they would have to update these scripts for whatever we come up with post preview2.

**Comment by piotrpMSFT** [comment]
What needs to happen in preview2?

**Comment by schellap** [comment]
Given an SDK version, the SDK zip url the FX version and zip url that it uses to test and validate needs to be known. For example, two preview2-01 and preview3-02 builds will point to same 1.0.0 FX.

**Comment by brthor** [comment]
Here's an idea for this for which we wouldn't need to spin a new build. It is definitely not ideal for long term but may get this scenario unblocked for preview2. 

1. For a given sdk version download the combined zip and parse the commit hash out of the .version file in the `sdk` directory. (e.g. current latest is `0708fe095e5198a245bc483a2ee3b44183d1ebaf`)
2. Load the commit version of `CliDependencyVersions.cs` ( https://github.com/dotnet/cli/blob/0708fe095e5198a245bc483a2ee3b44183d1ebaf/build_projects/dotnet-cli-build/CliDependencyVersions.cs )
3. Parse SharedFX version from there (regex: `SharedFrameworkVersion\s*=\s*\"(?<version>[^\"]+)\"`)
4. Use `dotnet-install.ps1 -SharedRuntime` option to install this zip or download directly

**Comment by piotrpMSFT** [comment]
for preview2 we have exactly one build. There is no variability. I get the need of automation in preview3+, but it's very unclear to me why any preview2 work is required.

**Comment by schellap** [comment]
We can manually hack together a Latest_Packages.txt file for preview2 and upload to blob storage and do some automated publishing of versions.txt for preview3. I am moving this to preview3.
