### ISSUE TITLE
What is the correlation between netcoreapp and netstandard?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/cli#3647]
What is the correlation between **netcoreapp** and **netstandard** as referencing `netstandard` in `netcoreapp` does not work?

**Comment by aL3891** [comment]
How do you mean? You should be able to reference a netstandard library in your netcoreapp application, otherwise something is wrong. can you post your project.json? also, what error are you getting?

**Comment by GuardRex** [comment]
@xperiandri Also helpful ... https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7

... but in need of an update (`netstandard1.6`) :wink: cc/ @davidfowl

**Comment by xperiandri** [comment]
I'll post a reproduction solution later today

**Comment by xperiandri** [comment]
Tried it with this solution.
https://github.com/xperiandri/ev3dev-lang-csharp

At first it did not build. But then I used `import netstandard1.5` and it built.
So I deleted `import netstandard1.5` and now it builds even without that.
I have no idea what was wrong.

**Comment by brentdavid2008** [comment]
I'm seeing some of the same types of things.  i have a "netcoreapp1.0" referencing a "netstandard1.6", and until i restarted my machine, they built and worked fine. now i can't get them to build or have intellesence between them.  suggestions?

**Comment by brentdavid2008** [comment]
well restarting VS now lets me build and run it with red squiggles in intellesense.  Guess i'll call that a win. lol, it ran though the code and worked as i expected it to.

**Comment by GuardRex** [comment]
@brentdavid2008 

> a "netcoreapp1.0" referencing a "netstandard1.6"

It might just be the brevity of your comment, but that description wasn't clear. If you're creating a CoreCLR application, you would use the `netcoreapp1.0` TFM, which implements `netstandard1.6` (currently). There is no need to have `netstandard1.6` "referenced" explicitly with the `netcoreapp1.0` TFM. `netstandard1.6` would be the TFM to use for creating CoreCLR packages.

**Comment by brentdavid2008** [comment]
I may not have been very clear, sorry about that.

Maybe the way visual studio creates them is causing the confusion.  I created a web app, saw the project.json file was saying the framwork is "netcoreapp1.0"  then created a class library and the project.json's framework node was "netstandard1.6".  When i attempt to reference that class library, and use it with some using statements, i get no intellesense and the build failed.  however, like i said on the last comment, restarting vs fixed it, but i still had no intellensense, but at least it built and let me run it to test it.

**Comment by GuardRex** [comment]
Gotcha. AFAIK Intellisense should work in your scenario. If you don't have it configured, you may need a `global.json` in the project. All of my libs are NuGet packages these days and I'm still using VS Code, so I'll defer to others to assist further. To get more Tooling :eyes: on this, you can close here and open over in the [Tooling repo](https://github.com/aspnet/Tooling/issues), where all of the Tooling :cat:'s hang out.
