### ISSUE TITLE
dotnet publish tries to use wrong framework

### ISSUE THREAD

**Issue by IntelOrca** [dotnet/cli#3648]
After upgrading from preview1 to preview2, my project no longer publishes. publish appears to ignore the framework I specify.

```
$ dotnet build -f netcoreapp1.0
Project MyProject (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
$ dotnet publish -f netcoreapp1.0
The current project is not valid because of the following errors:
.../project.json(18,14): error DOTNET1011: Framework not installed: .NETFramework,Version=v4.6 in
```

If I remove net46 framework from project.json and restore, it works.
## Environment data

```
.NET Command Line Tools (1.0.0-preview2-003119)

Product Information:
 Version:            1.0.0-preview2-003119
 Commit SHA-1 hash:  0708fe095e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  15.10
 OS Platform: Linux
 RID:         ubuntu.15.10-x64
```

**Comment by blackdwarf** [comment]
@IntelOrca can you show us your `project.json` file?

**Comment by IntelOrca** [comment]
I produced a cut down version attached here:
[dotnetcli-3648.zip](https://github.com/dotnet/cli/files/322501/dotnetcli-3648.zip)

When I try to publish ProjectB with `-f netcoreapp1.0`, it complains about not having net46 installed. When I publish it on Windows where I do have net46, it works and only publishes for netcoreapp1.0. So it seems to just be some initial check that fails.

**Comment by piotrpMSFT** [comment]
I just verified that this does not repro with preview3. If you do still see an issue with preview3 please let us know! I ask because there are variables like Mono which make it difficult to say we've tested exhaustively.
