### ISSUE TITLE
Ubuntu update broke dotnet 

### ISSUE THREAD

**Issue by shahid-pk** [dotnet/cli#3651]
## Steps to reproduce

- add Microsoft ppa for dotnet following instructions on dot.net website. 
- install stable rc2 packages as instructed on the website.
- update your Ubuntu 14.04 or may be any supported version , you will receive an update to dotnet-host that is incompatible with shared framework and coreclr.

## Expected  behavior
I don't expect that my system update will break my development tools.

## Actual behavior
Update every package and don't leave packages in a broken state. May be separate ppa for stable and unstable will do or anything that don't break tools or the run time for people who are using the stable packages.

## Environment data
`dotnet --info` output:

Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main
Segmentation fault (core dumped)

**Comment by IntelOrca** [comment]
Related: #3570

In the end I uninstalled all my dotnet packages and installed 1.0.0-preview2-003119.

**Comment by shahid-pk** [comment]
I know it can be fixed through that work around . But that fix brings in unstable packages of the run time and base class library which is not good for someone who wants to stay on actually released rc2 stable packages.

**Comment by manu-silicon** [comment]
Got the same issue. Is there a workaround that does not involve installing a new package?

**Comment by manu-silicon** [comment]
I tried to installed the above preview but I'm on Ubuntu 16.04 and it depends on libicu52 which is not present.

**Comment by blackdwarf** [comment]
@shahid-pk I believe that the recent move to `dotnet-release` feed should fix this issue. Can you please verify? The new instructions are on https://dot.net/core.

**Comment by shahid-pk** [comment]
yes @blackdwarf  this issue is fixed. I forgot to close this. Thanks
