### ISSUE TITLE
Better error message needed when no testRunner configured

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#3652]
## Steps to reproduce

Run `dotnet test` with no  `"testRunner": "xunit"` set in project.json
## Expected  behavior

How about this:

`'You've run dotnet test but there's no configured testRunner in your project.json. Try "testRunner": "xunit"`
## Actual behavior

You get this, which sucks. It's WAY too subtle. It also offers no help.

`no executable found matching command "dotnet-test-"`
## Environment data

`dotnet --info` output:

`.NET Command Line Tools (1.0.0-preview2-003119)`

**Comment by blackdwarf** [comment]
Added to #3147 which tracks all of this work for RTM.

**Comment by piotrpMSFT** [comment]
The test runner attribute has been eliminated in preview3/csproj so this no longer applies.
