### ISSUE TITLE
Native assets not published when publishing for desktop CLR with a bogus RID

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3656]
## Steps to reproduce

Publish a web application with:

`dotnet publish -f net451 -r abc`
## Expected  behavior

An error saying that the RID is not valid.
## Actual behavior

The application is published but native assets are not (probably because no native assets could be found for the RID). 
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003118)

**Comment by blackdwarf** [comment]
Yes, we should output an error if the RID is not found in any of the assets. Though this could be interesting on performance of the publish operation.

/cc @piotrpMSFT @livarcocc @eerhardt

**Comment by blackdwarf** [comment]
With the move to MSBuild, this validation should be done in the targets. I've created dotnet/sdk#690 to track this work/discussion. Will close this one.
