### ISSUE TITLE
ClosedXML package doesn't work after upgrade to RC2. Any work around?

### ISSUE THREAD

**Issue by valcs007** [dotnet/cli#3659]
Hi,

We are trying to upgrade from RC1 to RC2 but have few issues with some ClosedXML Nuget package. we use that package for exporting to Excel and it was working with RC1. After upgrading to RC2, adding the package throws below exception.

The dependency ClosedXML doesn't support .Net Core 1.0.

Below is the Json file that was generated when i launch Core template

"dependencies": {
"Microsoft.NETCore.App": {
"version": "1.0.0-rc2-3002702",
"type": "platform"
},
"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
"Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final"
},

"frameworks": {
"netcoreapp1.0": {
"imports": [
"dotnet5.6",
"dnxcore50",
"portable-net45+win8"
]
}
},
}

Any work around?

Thanks

**Comment by blackdwarf** [comment]
@valcs007 what are the dependencies of ClosedXML? Also, the exception/error happens at restore time, correct?

**Comment by valcs007** [comment]
As per the Nuget webpage (https://www.nuget.org/packages/ClosedXML/), its .Net framework 3.5/4.0  but this was working with RC1 without any issues.

Yes, when i add that Nugetpackage for my project, system restores and i get this exception.

**Comment by ericstj** [comment]
You can try `"imports": ["net4"]` but that's a huge hack.  Looking at this assembly inside the NuGet package it uses WindowsBase.dll, System.Data.dll, and System.Drawing.dll (and others).  None of those have ever existing for .NET Core, even at RC1, so I have a hard time believing this was working.  Perhaps you were targeting .NET Desktop rather than .NET Core?

**Comment by blackdwarf** [comment]
Given the answers on this thread and lack of activity since summer last year, I will close this issue. Please reopen if you need more information. Thanks!
