### ISSUE TITLE
Tons of warnings

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#366]
Is there any reason we get this warnings or can we fix it?
```
X:\oss\cli\src\Microsoft.DotNet.Compiler.Common\project.json(7,27): warning NU1012: Dependency conflict. Microsoft.Extensions.FileSystemGlobbing 1.0.0-rc2-15797 expected System.Runtime >= 4.0.21-beta-23506 but got 4.0.21-beta-23504
Compilation succeeded.
X:\oss\cli\src\Microsoft.DotNet.Compiler.Common\project.json(7,27): warning NU1012: Dependency conflict. Microsoft.Extensions.HashCodeCombiner.Sources 1.0.0-rc2-15898 expected System.Runtime >= 4.0.21-rc2-23601 but got 4.0.21-beta-23504
    4 Warning(s)
X:\oss\cli\src\Microsoft.DotNet.Compiler.Common\project.json(7,27): warning NU1012: Dependency conflict. Microsoft.Extensions.JsonParser.Sources 1.0.0-rc2-16251 expected System.Runtime >= 4.0.21-rc2-23601 but got 4.0.21-beta-23504
```

Half of my build log is covered with this.

I'm just wondering how did this happen that we target non-existing version which happens to be higher than highest existing - did we somehow remove the package from nuget, some typo or is there some obscured bug in `restore` which caused this?

**Comment by anurse** [comment]
Yeah, it's caused by a feed not having the exact version of the package requested. Sounds like we should just go through our project.json's and correct them

**Comment by davidfowl** [comment]
It's a downgrade warning, https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Compiler.Common/project.json#L7 is pulling the version down.

**Comment by anurse** [comment]
It's not just there. DNX took a higher BCL build in the latest feed and that's causing some of our projects to downgrade. We should probably work on moving the DNX code we're using into this repo to avoid that :).

**Comment by krwq** [comment]
How much work are we talking? Can this be done by EOD? :smiley:

**Comment by davidfowl** [comment]
There's other important issues. That said, Andrew is looking into it.

**Comment by anurse** [comment]
Yeah, I'm doing an overhaul of the p-j's (that's how the cool kids say "project.json 's" btw, :sunglasses:). Should be ready for PR shortly.

**Comment by piotrpMSFT** [comment]
It looks like there are less warnings now.

**Comment by anurse** [comment]
Still some though ;). Need stdlib! Stdlib all the things!
