### ISSUE TITLE
dotnet test needs to distinguish its own arguments from test runner arguments, using "--"

### ISSUE THREAD

**Issue by plioi** [dotnet/cli#3661]
@jskeet describes the problem over on an NUnit thread: https://github.com/nunit/nunit/issues/1371#issuecomment-223874292

This may be considered a duplicate of https://github.com/dotnet/cli/issues/1385 , but the name of that issue is somewhat misleading now and may be misinterpreted.

Having a consistent way to unambiguously distinguish "dotnet test" arguments from the arguments of the test runner itself is just as valuable as the "--" behavior already available and documented for dotnet run: https://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-run.html

**Comment by plioi** [comment]
It turns out this would not be feasible unless the architecture change in #3974 gets adopted. Right now, the only way for `dotnet test` integrators to work is to inspect and parse *all* the command line arguments, making it each test framework's responsibility to adopt "--" on their own.

**Comment by pvlakshm** [comment]
As mentioned in https://github.com/dotnet/cli/issues/4921#issuecomment-270606858, we're evaluating bringing this in. Please see PR https://github.com/dotnet/cli/pull/5181.

**Comment by piotrpMSFT** [comment]
Fixed in #5181
