### ISSUE TITLE
If global.json has a B.S. version string for SDK, the CLI doesn't care

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#3662]
## Steps to reproduce

global.json:

> {
>      "projects": [ "src", "test" ],
>      "sdk": {
>         "version": "foofoo"
>      }
> }
## Expected  behavior

A warning? A freak out? Something?
## Actual behavior

It uses the latest SDK/CLI without a whimper.

**Comment by piotrpMSFT** [comment]
Moved to core-setup. This issue exists in the dotnet host despite affecting the CLI.
