### ISSUE TITLE
dotnet new -t web contains unnecessary imports

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#3665]
Using the 1.0.0.preview2-03118 build of project, I noticed that it produces a project.json with imports that are no longer required. For instance:  

``` json
...
"Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8+dnxcore50",
        "portable-net45+win8"
      ]
    },
...
```

**Comment by piotrpMSFT** [comment]
The preview3 web template uses csproj, so we can no longer make this fix.
