### ISSUE TITLE
<exeInstaller> /layout doesn't work

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#3666]
## Steps to reproduce
Download one of the exe installers, eg: https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-dev-win-x64.latest.exe
dotnet-dev-win-x64.latest.exe /layout c:\layout

## Expected  behavior
c:\layout contains all the binaries that make up the install

## Actual behavior
c:\layout cotains only the bootstrapper and vcredist.

This may be a burn bug.
/cc @robmen

**Comment by robmen** [comment]
`/layout` creates a folder with everything you need to `burn a DVD`. It does not extract files from the bundle. There is no command for that today.

**Comment by ericstj** [comment]
I don't think it does that.  The bundle is 40 MB but after running /layout I get a .5 MB file and 14 MB file.  I think I'd be in trouble if I put those on a DVD.

**Comment by robmen** [comment]
Oh, sorry, totally misunderstood! Yes, that sounds like a known bug in v3.10.2 (and maybe in v3.10.1). Try v3.10.3. The current build has a *very* good chance to be the RTM for v3.10.3 on July 4th.

**Comment by ericstj** [comment]
I see.  That said, what I was trying to do was actually get the MSIs out of the bundle, which you are saying is unsupported right?

I was able to do it by executing the installer, but ideally i'd be able to do so in some way that doesn't require elevation/system changes.

**Comment by robmen** [comment]
Then I did understand originally. :smile_cat:

Yes, there is a request for an `/extract` switch (or something like that) in WiX v4 but no one is currently working on it, AFAIK.

**Comment by ericstj** [comment]
ok, I'll close this.
