### ISSUE TITLE
re-building with a base path under the project directory results in a warning

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#3668]
## Steps to reproduce
1. dotnet new 
2. dotnet restore
3. dotnet build -b mybasepath
4. dotnet build -b mybasepath
## Expected  behavior

Second build is a no-op because I've already got a build 
## Actual behavior

A second build happens and emits a warning, because CLI dropped an assemblyinfo.cs into the obj directory.

PS D:\work\basepath>dotnet build -b mybasepath
Project basepath (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling basepath for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.9060571

PS D:\work\basepath>dotnet build -b mybasepath
Project basepath (.NETCoreApp,Version=v1.0) will be compiled because Input items added from last build
Compiling basepath for .NETCoreApp,Version=v1.0
D:\work\basepath\warning CS2002: Source file 'mybasepath\basepath\obj\Debug\netcoreapp1.0\dotnet-compile.assemblyinfo.cs' specified multiple times
about:blank

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.8793682
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003118)

Product Information:
 Version:            1.0.0-preview2-003118
 Commit SHA-1 hash:  7ada53d523

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14362
 OS Platform: Windows
 RID:         win10-x64

**Comment by andreesteve** [comment]
Also in 1.0.0-preview2-003131.
In our team's build system, we treat all warnings as errors - I wanted to keep failing on all other warnings, but suppress this one, while there isn't a solution for this issue.
Is there a way to suppress this particular warning?

**Comment by 01binary** [comment]
@andreesteve - I just hit this today, adding my build folder to `project.json` > `buildOptions` > `compile` > `exclude` array suppressed this warning. This stops `dotnet build` from trying to harvest `.cs` files from the entire tree (thus excluding `assemblyinfo.cs` dropped into intermediate folder from a previous build).

See here for info on how to use the `exclude` option:
https://github.com/aspnet/Home/issues/1464

Example project.json with non-relevant stuff excluded:
`
{
  "buildOptions": {
    "compile": {
      "exclude": ["Build"]
    }
  }
}
`
Thanks to @billwert for the excellent report (above) that included the cause diagnosis.

**Comment by piotrpMSFT** [comment]
MSBuild does not have a -b equivalent, so this option was deprecated in preview3.
