### ISSUE TITLE
Stand alone publishing should change the timestamp of the host binary

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#3670]
## Steps to reproduce

Publish an app stand alone
## Expected  behavior

The timestamp on the host binary (myapp.exe) should be the same as the other binaries that were just produced.
## Actual behavior

The timestamp is from when the host was built.

basepath.dll                6/21/2016 3:39:05 PM
basepath.exe                6/15/2016 3:33:02 PM
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003118)

Product Information:
 Version:            1.0.0-preview2-003118
 Commit SHA-1 hash:  7ada53d523

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14362
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
why is this important? Do you have tools looking at those timestamps? The exe is just a copy of the host that gets renamed in the output of the app. I suppose we could edit the timestamp on the file if necessary.

**Comment by billwert** [comment]
It's a nice to have. More than once I've been momentarily confused as I've gone to copy binaries from somewhere to somewhere by the mismatch here. ("Did one of my things not rebuild? What happened? Oh.")

**Comment by piotrpMSFT** [comment]
the fixed timestamp is consistent with other assets coming from nupkgs. It also destinguishes the generated content from the xcopied content. Finally, fixed timestamps are very useful to incrementality scenarios. Let's leave this as-is.
