### ISSUE TITLE
in what? - the error message is not complete

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3672]
## Steps to reproduce

`dotnet run` on a project targeting a .NET Framework version that is not installed on the machine
## Expected  behavior

Error messages should be full sentences. 
## Actual behavior

The error message is: 

```
error DOTNET1011: Framework not installed: .NETFramework,Version=v4.5.1 in
```

Full output:

```
PS C:\Users\XXXX\source\cli-samples\HelloMvc> dotnet run
The current project is not valid because of the following errors:
C:\Users\XXXX\source\cli-samples\HelloMvc\project.json(30,15):  error DOTNET1011: Framework not installed: .NETFramework,Version=v4.5.1 in

PS C:\Users\XXXX\source\cli-samples\HelloMvc>
```
## Environment data

`dotnet --info` output:

```
PS C:\Users\XXXX\source\cli-samples\HelloMvc> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003118)

Product Information:
 Version:            1.0.0-preview2-003118
 Commit SHA-1 hash:  7ada53d523

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x86
```

**Comment by svick** [comment]
My guess is that the fix is to change [this line](https://github.com/dotnet/cli/blob/ecdb105/src/Microsoft.DotNet.ProjectModel/ProjectContextBuilder.cs#L349) from:

```c#
$"Framework not installed: {TargetFramework.DotNetFrameworkName} in {ReferenceAssembliesPath}",
```

to:

```c#
$"Framework not installed: {TargetFramework.DotNetFrameworkName} in {frameworkReferenceResolver.ReferenceAssembliesPath}",
```

But I didn't manage to reproduce this error, so I don't know if this is the right fix and so I'm not going to submit a PR.

**Comment by piotrpMSFT** [comment]
ProjectModel, along with ProjectContextBuilder, are deprecated in preview3.
