### ISSUE TITLE
Leaving incorrect binding redirects in exe.config file.

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#3674]
## Steps to reproduce

Create a new library project and in project.json add following dependencies and restore:

```

 "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Gluon.Core": "1.0.0-*",
    "NuGet.Core": "2.10.1",
    "NuGet.Client": "3.5.0-beta-final",
    "NuGet.Resolver": "3.5.0-beta-final",
    "NuGet.Repositories": "3.5.0-beta-final",
    "NuGet.Packaging": "3.5.0-beta-final",
    "NuGet.Protocol.Core.Types": "3.5.0-beta-final",
    "NuGet.Protocol.Core.v3": "3.5.0-beta-final",
    "NuGet.Protocol.Core.v2": "3.5.0-beta-final",
    "NuGet.ProjectManagement": "3.5.0-beta-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "NuGet.PackageManagement": "3.5.0-beta-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final"
  },
```

Notice NuGet.Core is downversioned to 2.10.1 and particular packages expect 2.11.1.

Add a new console / web Application project to the same solution, and make it reference the above library project.

Now build the solution in VS (assuming this is the same as doing a `dotnet build`)

In the `output` folder for your application, check the `[Application].exe.config` file - you will see a binding redirect for NuGet.Core:

```
<dependentAssembly>
        <assemblyIdentity name="NuGet.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="2.11.1.812" newVersion="2.10.1.766" />
      </dependentAssembly>

```

Now go back to the project.json file and update the NuGet.Core package to 2.11.1. Again build the solution.

Check the `application.exe.config` file. It's left the old binding redirect in place.
## Expected  behavior

The binding redirect is removed from the application.exe.config file as it is no longer needed.
## Actual behavior

The binding redirect is left in the application.exe.config file. Run the application and it blows up as it is now redirecting to a non existing assembly. Manually deleting the config file and then rebuilding produces a new one which is correct.
## Environment data

Microsoft Windows [Version 10.0.10586](c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Darrell>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

C:\Users\Darrell>

**Comment by niemyjski** [comment]
This caused a huge issue for me today. I was trying to figure out why my package was failing to run with an assembly binding issue.. It had a config file with:

```
<dependentAssembly>
       <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
       <bindingRedirect oldVersion="7.0.0.0" newVersion="8.0.0.0" />
       <bindingRedirect oldVersion="6.0.0.0" newVersion="8.0.0.0" />
       <bindingRedirect oldVersion="7.0.0.0" newVersion="9.0.0.0" />
       <bindingRedirect oldVersion="8.0.0.0" newVersion="9.0.0.0" />
       <bindingRedirect oldVersion="6.0.0.0" newVersion="9.0.0.0" />
       <bindingRedirect oldVersion="9.0.0.0" newVersion="8.0.0.0" />
     </dependentAssembly>
```

I don't have an app.config file defined and I'd expect this file to be regenerated every time. We really need a `dotnet clean`.........

Deleting that file and rebuilding created a new config file that worked.

```
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="6.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
```

**Comment by piotrpMSFT** [comment]
This is a known issue in project.json binding redirects handling. Fortunately, this has been fixed in preview3+ in msbuild. We were able to bring over much of the tried & true binding redirects logic from csproj.
