### ISSUE TITLE
Need a way to see what tools are available in a project

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#3675]
Because tool package IDs may not match the actual assembly name, it is extremely difficult for a user to figure out how to invoke a tool. If I install `Microsoft.Extensions.SecretManager.Tools` in my project, I have to find documentation that tells me I need to invoke `dotnet user-secrets` to use it.

Tools available in the project should be listed either in a separate command (`dotnet tools list` or something) or in `dotnet --help`

**Comment by piotrpMSFT** [comment]
Added to the commands wishlist.

**Comment by livarcocc** [comment]
The future for us is global tools and local tools and both support listing the tools available.
