### ISSUE TITLE
dotnet restore fails on Fedora 23 with nss-3.24.0-1.3.fc23.x86_64

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#3676]
## Steps to reproduce
1. Ensure (via `rpm -q nss`) that you have `nss-3.24.0-1.3.fc23.x86_64` installed.  If not, `dnf update nss`.
2. Install CLI
3. git clone https://www.github.com/dotnet/jitutils
4. cd jituitls
5. dotnet restore
## Expected  behavior

Restore completes.
## Actual behavior

Restore does not complete, and detailed output shows connection and SSL errors.
## Environment data

`dotnet --info` output:

```
[matell@localhost jitutils]$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     fedora
 OS Version:  23
 OS Platform: Linux
 RID:         fedora.23-x64
```

**Comment by ellismg** [comment]
@pgavlin @stephentoub and I have been looking into this a little.  Tracing connections from HttpClient it looks like there are problems when trying to do the SSL connections:

```
[Microsoft-System-Net-Http-6] (1553, 7094, SendAsync, Method: GET, RequestUri: 'https://api.nuget.org/v3-flatcontainer/system.linq.parallel/index.json', Version: 1.1, Content: <null>, Headers:
[Microsoft-System-Net-Http-6] (1553, 7094, HandleIncomingRequests, Type: New).
[Microsoft-System-Net-Http-6] (0, 7094, SetUrl, Url: https://api.nuget.org/v3-flatcontainer/system.linq.parallel/index.json).
[Microsoft-System-Net-Http-6] (0, 7094, SetRedirection, Max automatic redirections: 50).
[Microsoft-System-Net-Http-6] (0, 7094, SetVerb, Verb: GET).
[Microsoft-System-Net-Http-6] (0, 7094, SetVersion, HTTP version: 1.1).
[Microsoft-System-Net-Http-6] (0, 7094, SetDecompressionOptions, Encoding: gzip,deflate).
[Microsoft-System-Net-Http-6] (0, 7094, SetProxyOptions, UseProxy true, Proxy null, using default proxy).
[Microsoft-System-Net-Http-6] (0, 7094, SetCredentialsOptions, Credentials set.).
[Microsoft-System-Net-Http-6] (0, 7094, SetSslOptions, CURLOPT_SSL_CTX_FUNCTION not supported: CURLE_NOT_BUILT_IN).
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: Found bundle for host api.nuget.org: 0x7f9bc807fe30).
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: Hostname api.nuget.org was found in DNS cache).
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: Trying 2606:2800:11f:179a:1972:2405:35b:459...).
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: Connected to api.nuget.org (2606:2800:11f:179a:1972:2405:35b:459) port 443 (#16)).
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: CAfile: /etc/pki/tls/certs/ca-bundle.crt
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: NSS error -5938 (PR_END_OF_FILE_ERROR)).
[Microsoft-System-Net-Http-6] (1553, 7094, CurlDebugFunction, CURLINFO_TEXT: Encountered end of file).
```

We've also discovered that downgrading the version of NSS on the machine to 3.20 via: `sudo dnf downgrade nspr nss-util nss-softokn-freebl nss-softokn nss-sysinit nss nss-tools` allows restore to succeed (which is why we did not see this earlier).

Oddly, using curl directly against the endpoint works as expected.  Tracing shows the SSL handshake is completing.

```
== Info:   Trying 2606:2800:11f:179a:1972:2405:35b:459...
== Info: Connected to api.nuget.org (2606:2800:11f:179a:1972:2405:35b:459) port 443 (#0)
== Info: Initializing NSS with certpath: sql:/etc/pki/nssdb
== Info:   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
== Info: ALPN, server accepted to use http/1.1
== Info: SSL connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
== Info: Server certificate:
== Info:        subject: CN=*.vo.msecnd.net
== Info:        start date: May 25 01:42:01 2016 GMT
== Info:        expire date: Feb 25 01:42:01 2018 GMT
== Info:        common name: *.vo.msecnd.net
== Info:        issuer: CN=Microsoft IT SSL SHA2,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US
=> Send header, 125 bytes (0x7d) 
```

We are trying to produce a repo outside of dotnet restore using just HttpClient directly and are also doing some tcp dumping to better understand what's going on with the SSL handshake.

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by ellismg** [comment]
From some more experimentation, it looks like the problem is either exacerbated or caused by the number of sources in a nuget.config.  For example, if I have just two HTTPS sources in NuGet (nuget.org and a myget feed), restore does not fail.  Looking at a packet capture for the failure cases, I see places where the three way handshake is established, then after 60 seconds, the server sends a [FIN, ACK] packet (which the client ACKs).

51 seconds after that, the client ends a SSL Client Hello message, and the server immediately responds with an RST packet.

Still trying to figure out how to reproduce this outside of NuGet restore...

**Comment by blackdwarf** [comment]
Hm, should this issue be moved to dotnet/corefx or to NuGet/home?

**Comment by ellismg** [comment]
(I opened it here because I figured it was the most likely place folks would look when they hit it).  Once we understand the root cause, I think we can move it.

**Comment by omajid** [comment]
Can we close this? Fedora 23 has been EOL'ed for ages now. `dotnet restore` works fine on recent versions of Fedora.

**Comment by livarcocc** [comment]
Sure.
