### ISSUE TITLE
Custom tool questions

### ISSUE THREAD

**Issue by patrickjamesbarry** [dotnet/cli#3691]
I have created my own tool following: (https://dotnet.github.io/docs/core-concepts/core-sdk/cli/extensibility.html) and can run it. Now I want my tool to do more than just print Hello World.  Looking at examples, it looks like they leverage util projects ie:

```
    "Microsoft.DotNet.ProjectModel": {
      "target": "project"
    },
    "Microsoft.DotNet.Compiler.Common": {
      "target": "project"
    },
    "Microsoft.DotNet.Cli.Utils": {
      "target": "project"
    },

```

The next step I am trying to get thought is:
- Can my tool piggy pack off an existing dotnet command?  Ie: dotnet pack (at then end, my tool will do some extra steps) 
- If I need the project version, do I have to parse the project.json myself and then have the use pass in --version-suffix flag, when calling my custom command?
- Is there any documentation on the packages listed above, besides reading the source code? I am trying to not write code where another package can be leveraged.
- Do I need to do something special to be able to resolve the packages above?  
- Can I call other dotnet commands from within my tool? Like if the user has not run dotnet build yet, my tool could invoke it.

nuget sources used:
api.nuget.org [Enabled]    https://api.nuget.org/v3/index.json
Microsoft Visual Studio Offline Packages [Enabled]     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

c:\repos\dotnet-helloworld>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by brthor** [comment]
@patrickjamesbarry Some answers here:

1. Yes your tool can be invoked via postpublish, postcompile events, I don't know if there's any documentation on these, but you can see an example with `publish-iis` here:

https://github.com/aspnet/cli-samples/blob/master/HelloMvc/project.json

The full list of hooks is here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/ScriptNames.cs#L10

2. If you invoke via scripts there are a number of variables that you can leverage which will get filled out. It doesn't look like version is among them, so you will need some custom solution for this. One idea would be to parse the assemblyinfo.cs generated by `dotnet build` or the nuspec generated by `dotnet pack`
See here for variables: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L169

And here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L108

3. The packages you mentioned are not well documented and reading the source code is currently the best way to leverage their functionality. 

4. No there is a dotnet-cli myget feed where they are available from: `https://dotnet.myget.org/gallery/dotnet-cli` (Be advised these are all pre-release and may undergo breaking changes)

5. Yes, you can call other commands from within your dotnet tool. A pre-requisite to using `dotnet` is that it's on the path. If in your tool you execute `dotnet build` that should work. Additionally you should be able to call other custom tools, as long as you don't change the current working directory.

**Comment by blackdwarf** [comment]
I believe this issue is resolved thanks to @brthor's excellent answers. Will close it. If still needed, reopen.

**Comment by patrickjamesbarry** [comment]
I am having issues getting the version. I am trying to get the current dll/exe version with this code.

```
 String version= typeof(RuntimeEnvironment)
                        .GetTypeInfo()
                        .Assembly
                        .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
                        .InformationalVersion;

            Console.WriteLine("Version: " + version);
```

It is not correct and does not include the build number (ie --version-suffix used to build the exe)

**Comment by brthor** [comment]
are you passing in `--version-suffix` to dotnet build?

**Comment by patrickjamesbarry** [comment]
Yes

**Comment by patrickjamesbarry** [comment]
It is always returning 1.0.0. Even though:
- My tool version is 1.1.0-13
- My library project is version 1.1.0-2

**Comment by brthor** [comment]
@patrickjamesbarry Can you post some sample code to take a look at?
