### ISSUE TITLE
Add support for explicitly initializing dotnet and the NuGet package cache

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#3692]
This is needed for the [.NET Dockerfiles](https://github.com/dotnet/dotnet-docker).  Within the Dockerfiles, it is desirable to initialize the NuGet package cache so that it doesn't have to be done on first use each time the image is run.  Additionally it generates an image layer that is shared by all derived images thus requiring less disk space.

Originally the .NET Dockerfiles where triggering the building of the cache by running the `dotnet --version` command but that was disabled via https://github.com/dotnet/cli/issues/3533.  To workaround this the .NET Dockerfiles now issue a `dotnet new` but have to first create a directory and cleanup the generated artifacts afterwards.  This workaround is less than ideal for a Dockerfile as it is not obvious as to why this is done without having an explicit comment.  I presume there are other usages scenarios outside of Docker in which it would be desirable to explicitly trigger the building of the package cache.

@blackdwarf

**Comment by MichaelSimons** [comment]
@blackdwarf, at one point you had expressed some ideas on how this should be implemented (e.g. a generic utility command).  Can you note those ideas here?  I would like to work on this when I have some free cycles.

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/dotnet/cli/issues/4919, since the conversation happened over there.
