### ISSUE TITLE
resx with (text) files doesn't return file content

### ISSUE THREAD

**Issue by joshfree** [dotnet/cli#3695]
When using a resx file which contains SQL files, the following code: "ResourceManager.GetString("a", resourceCulture)" returns 

> a.sql;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8

Instead of returning the file content.

From @tarekgh https://github.com/dotnet/corefx/issues/8200 :

When compiling as csproj, I am seeing the msbuild target CoreResGen get invoked which will invoke the msbuild task "GenerateResource". this task will convert the .resx file to .resources file this include reading TextFile.txt and getting its contents and embed this content into the .resources file. and that is why is working fine with csproj. 

when loading the attached xproj in VS and compiling it, I am seeing the following:

```
1>Target "CoreResGen: (TargetId:37)" in file "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets" from project "F:\Temp\RemoveIt\remove\src\ResxTestConsoleApp\ResxTestConsoleApp.xproj" (target "ResGen" depends on it):
1>                   Set Property: GenerateResourceMSBuildArchitecture=CurrentArchitecture
1>                   Set Property: ResgenToolPath=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\
1>                   Set Property: GenerateResourceMSBuildRuntime=CurrentRuntime
1>                   Task "GenerateResource" skipped, due to false condition; ('%(EmbeddedResource.Type)' == 'Resx' and '%(EmbeddedResource.GenerateResource)' != 'false' and '$(GenerateResourceMSBuildRuntime)' != 'CLR2') was evaluated as ('' == 'Resx' and '' != 'false' and 'CurrentRuntime' != 'CLR2').
1>                   Task "GenerateResource" skipped, due to false condition; ('%(EmbeddedResource.Type)' == 'Resx' and '%(EmbeddedResource.GenerateResource)' != 'false' and '$(GenerateResourceMSBuildRuntime)' == 'CLR2') was evaluated as ('' == 'Resx' and '' != 'false' and 'CurrentRuntime' == 'CLR2').
1>09:03:18.151     1>
1>Done building target "CoreResGen" in project "ResxTestConsoleApp.xproj".: (TargetId:37)
```

which show the GenerateResource task is skipped. so someone familiar with building xproj need to take a look and figure out why this is happening.

**Comment by piotrpMSFT** [comment]
@joshfree @tarekgh does this still repro for you on preview3 or later? If so, please re-open the issue in the dotnet/sdk issue as that is where resource generation is being handled in the msbuild .NET Core toolchain.
