### ISSUE TITLE
Need to Sign macOS pkg file for release builds

### ISSUE THREAD

**Issue by martinwoodward** [dotnet/cli#3699]
## Steps to reproduce
 - Have a Mac set to default configuration in Gatekeeper (i.e. have your Mac set to allow apps downloaded from Mac App Store and identified developers)
 - Download a release build of the .NET Core SDK PKG file
 - Run it

## Expected  behavior
 - Installer runs without error

## Actual behavior
 - Scary security warning on default Mac configuration and installer fails to run.

Work around is to go to System Preferences, Security & Privacy, General and then press the button to allow you to run that installer once.

Should we be using productsign on the binaries with a third party certificate from Apple.

**Comment by piotrpMSFT** [comment]
We expect to have a fix available later today.

**Comment by martinwoodward** [comment]
Looks like this is still a problem with 1.0.1

**Comment by h3smith** [comment]
@martinwoodward got the issue myself installing on macOS today.

**Comment by martinwoodward** [comment]
Thanks for confirming @h3smith - hoping for a fix very soon. We'll update here once the team in the US come online.

**Comment by leecow** [comment]
Working on this and should be resolved very soon. Sorry for the trouble!

**Comment by leecow** [comment]
Signed pkgs uploaded and live. Verified from https://www.microsoft.com/net/download#core
