### ISSUE TITLE
Typo in the macOS installer welcome screen text

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/cli#3704]
In the 2nd paragraph, seem to have an extra "the":

This package contains all the tools you will need to start writing applications with .NET Core. It includes **the** several tools, including the C# compiler and the NuGet package manager, and a copy of .NET Core for both you and the tools to use.

**Comment by vcsjones** [comment]
@blackdwarf is this issue valid anymore? Should this be fixed here or should it be fixed in dotnet/core-setup?
