### ISSUE TITLE
Telemetry is disabled by default

### ISSUE THREAD

**Issue by Lisaj** [dotnet/cli#3712]
## Steps to reproduce

Install DotNetCore.1.0.0-VS2015Tools.Preview2
run dotnet -v

## Expected  behavior

Telemetry is: Enabled

## Actual behavior

Telemetry is: Disabled

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

In this post blog https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/ i read the telemetry is enabled by default, but in my pc is disabled.
I check my system variables and dont have DOTNET_CLI_TELEMETRY_OPTOUT set.

**Comment by jhudsoncedaron** [comment]
Not a bug! Some things should not be enabled by default.

**Comment by germgerm** [comment]
Is currently as it absolutely should be - OFF but default !

**Comment by Lisaj** [comment]
Telemetry is enabled after command dotnet build automatically.

**Comment by germgerm** [comment]
that's not good
