### ISSUE TITLE
rc2 is still the active toolset after installing dotnet-dev-osx-x64.1.0.0-preview2-003121.pkg

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/cli#3713]
## Steps to reproduce
I have installed `dotnet-dev-osx-x64.1.0.0-preview2-003121.pkg` on my machine but when I run `dotnet --version` I end up with `1.0.0-rc2-002659`.
I have rebooted, reinstalled dotnet and so on.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc2-002659)

Product Information:
 Version:     1.0.0-rc2-002659
 Commit Sha:  11a001706f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by chaskim** [comment]
The same thing happened to me after I installed Preview 2 with the .pkg installer (macOS, El Capitan, 10.11.5). I was in a directory where I had developed a web api using RC2 and Preview 1 tools. Issuing _dotnet --info_ from that directory returned info for Preview 1. 

However, when I did _dotnet --info_ outside of that directory, it returned info for Preview 2. Could it be that the CLI is reading info in project.json to determine which version to use? I haven't had time yet to adjust my project.json for .NET Core 1.0 RTM, so I cannot confirm that this is related to project.json or not.

**Comment by marcuslindblom** [comment]
For me, issuing _dotnet --info_ returns the same info in all directories I have tried.

**Comment by chaskim** [comment]
Actually, after looking at your output again, it shows "rc2" (bolded below):

.NET Command Line Tools (1.0.0-**rc2**-002659)

when it show "preview". So me for, my output is one of the two, depending on the directory that I'm in:

.NET Command Line Tools (1.0.0-preview1-002702)
.NET Command Line Tools (1.0.0-preview2-003121)

Maybe "rc2" is indicating a "pre-preview" release and needs to be removed ([similar issue](https://github.com/dotnet/cli/issues/3064))?

**Comment by marcuslindblom** [comment]
I had some issues removing the old tooling (dnvm, dnx). _dnvm uninstall_ was not available and I could not run _dnvm update-self_. Is it possible to manually uninstall the old tooling?

**Comment by adriangould** [comment]
Similar issued - after installing the latest "1.0.0-preview2-003121" - Visual studio is reporting that version does not exist. When I type "DotNet" the version returned is:  .NET Command Line Tools (1.0.0-beta-001540)

Any help on this???

**Comment by chaskim** [comment]
There was a script available to remove old tooling when RC2 was released. For macOS, the shell script is [here](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh). General info is [here](https://github.com/dotnet/core/blob/master/release-notes/1.0/RC1-RC2_Upgrade.md). Hopefully that helps.

**Comment by marcuslindblom** [comment]
Using the shell script seems to have solved my issue and now _dotnet --info_ returns:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
Thanks for your help @chaskim

**Comment by chaskim** [comment]
@marcuslindblom Awesome!

@adriangould If you're on Windows, you could try removing old tooling via Add/Remove programs in the Control Panel, if you haven't tried already.

**Comment by blackdwarf** [comment]
@adriangould the version you have indicate that it is very old. In your Add/Remove Programs, please uninstall anything with "dotnet" and/or "cli" strings in it. This should remove the very old version and allow a clean install of the Preview 2 bits.

Will close this issue as the main problem has been solved. If still needed, please reopen.

**Comment by adriangould** [comment]
@blackdwarf - Thanks for info, I managed to resolve by manually removing any DOTNET related directories found in the PATH, plus and existing legacy PATH settings for DOTNET. There were no options in ADD/Remove programs, so I had no other option.
I then installed the latest and it now works as expected.
