### ISSUE TITLE
Provide a default linux friendly installer

### ISSUE THREAD

**Issue by gochev** [dotnet/cli#3714]
Currently you have provided downloads for 7-8 linux distributions, however there are 1000 of linux distros out there.

Please provide a unix friendly installation method from source. This way distributions like Arch, Gentoo, Slackware and other non deb,rpm based can use dotnet core.
## Expected  behavior

`wget http://.....source.tar.gz`
`./configure` - should show you if some dependancy is missing 
`make` - should build it if configure was successful
`make install` - should install it on the right folders and should add dotnetcore and other commands in /usr/bin or similar

Also when distribute source or binary always include an md5 checksum of the file.

**Comment by martinwoodward** [comment]
Regarding the hashes, I have a TODO to get them on the download page. I meant to do that for GA but ran out of time to make it look pretty. They raw details are below if you need them quickly:

| Filename | Hash |
|---------------|---------|
| [DotNetCore.1.0.0.Runtime-x64.exe](https://go.microsoft.com/fwlink/?LinkID=809109) | 0953e863f28809901663bd86b0150eae977a31f4 |
| [DotNetCore.1.0.0.Runtime-x86.exe](https://go.microsoft.com/fwlink/?LinkID=809110) | 88581a972cbba8cd0954987fddcc274212eb315d |
| [dotnet-osx-x64.1.0.0.pkg](https://go.microsoft.com/fwlink/?LinkID=809111) | 78215b1d49e39118d5a3b3afbae8b7331526727f |
| [DotNetCore.1.0.0-SDK.Preview2-x64.exe](https://go.microsoft.com/fwlink/?LinkID=809122) | 521ecc4b01b3feda765873a9491717cb0847cbc6 |
| [DotNetCore.1.0.0-SDK.Preview2-x86.exe](https://go.microsoft.com/fwlink/?LinkID=809123) | 37d94330519d7e3afaadc01bcf3fd23fa5520d67 |
| [dotnet-dev-osx-x64.1.0.0-preview2-003118.pkg](https://go.microsoft.com/fwlink/?LinkID=809124) | 9b786c576c3ec93f8bbfe47202a0148532bc1526 |
| [dotnet-sdk-ubuntu-x64.1.0.0-preview2-003118.deb](https://go.microsoft.com/fwlink/?LinkID=809125) | b12c3878406a86a67d9c8799969d59149ca0f0d2 |
| [dotnet-win-x64.1.0.0.zip](https://go.microsoft.com/fwlink/?LinkID=809115) | d96c58eed3c6e40e066e38c5abf6dec71f85ccdf |
| [dotnet-win-x86.1.0.0.zip](https://go.microsoft.com/fwlink/?LinkID=809116) | 4f5a4cef9bceb2d66613f3c4163b69c0111ed163 |
| [dotnet-osx-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809117) | 12694e79eff0443455242f7601765e9f12268e10 |
| [dotnet-ubuntu-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809118) | 1222184c682d56342184750fcd5817543ec9827e |
| [dotnet-debian-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809119) | eba8ceab24cd0ff34f8e58276f33b8268f3fef69 |
| [dotnet-centos-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809120) | 00ae960de0d0f09c1f04e72392100eb179292e35 |
| [dotnet-rhel-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809121) | 76fa1c3f20b79605e41e65fb24b2fe8c2e363aaf |
| [dotnet-fedora.23-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=816874) | 3555c61582e93381637aa4c1e875da8a0838c8a6 |
| [dotnet-opensuse.13.2-x64.1.0.0.tar.gz](https://go.microsoft.com/fwlink/?LinkID=816873) | efcfad9dcb1ce0aa8d2f43b41685513d5f0d41d7 |
| [dotnet-dev-win-x64.1.0.0-preview2-003118.zip](https://go.microsoft.com/fwlink/?LinkID=809126) | 8d750e40b084bbf7feacb7ae2bcf0b7f35bd52fc |
| [dotnet-dev-win-x86.1.0.0-preview2-003118.zip](https://go.microsoft.com/fwlink/?LinkID=809127) | 413e4dc5e0da0badc686a6c4689a0af8afaab96f |
| [dotnet-dev-osx-x64.1.0.0-preview2-003118.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809128) | 19d3473c989ca313781925deb7ca0b3cfb626e8a |
| [dotnet-dev-ubuntu-x64.1.0.0-preview2-003118.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809129) | acd6f98efdef987edec20352176602e89bdf9f06 |
| [dotnet-dev-debian-x64.1.0.0-preview2-003118.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809130) | 667688b6f4f684b0d206b961f9751b2ba9edfded |
| [dotnet-dev-centos-x64.1.0.0-preview2-003118.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809131) | 4e1f9f2c64b4339225d1f895bd571a18a780eee8 |
| [dotnet-dev-rhel-x64.1.0.0-preview2-003118.tar.gz](https://go.microsoft.com/fwlink/?LinkID=809132) | 3d2b6a1c44c45672de0f3fabf2b81cb3009f93b9 |
| [dotnet-dev-fedora.23-x64.1.0.0-preview2-003121.tar.gz](https://go.microsoft.com/fwlink/?LinkID=816869) | 926d6aff17b7d6b5a27f4f176679901a41c7c19d |
| [dotnet-dev-opensuse.13.2-x64.1.0.0-preview2-003121.tar.gz](https://go.microsoft.com/fwlink/?LinkID=816867) | 1ee17f3bea6d042d3813c720dbe1b678a7d253e6 |

**Comment by gochev** [comment]
Thanks for the checksums

**Comment by erick2red** [comment]
I'm willing to work on these, I might need some pointers, but if the team behind dotnet core is willing, I might put some time into it, and the same for all the others, `coreclr` and `corefx`

**Comment by piotrpMSFT** [comment]
Moved to corefx. This issue is not tractable until an appropriate Shared Framework is available.
