### ISSUE TITLE
What versions of the binary SDK zip downloads can I pin to without getting 404?

### ISSUE THREAD

**Issue by maxild** [dotnet/cli#3715]
Short answer: What (subset of) versions of the binary SDK can I pin to without getting 404 when invoking dotnet-install.ps1 -Version $SomePinnedCliVersion? 

I need to clarify (maybe just to me) how to install different 'pinned' versions of .NET Core SDK/CLI (zip, binary). So my question relates to the dotnet-install.ps1 script in the repo. 

Pinned versions could be

* 1.0.0-beta-002071 (preview1 bundled with RC2)
* 1.0.0-preview2-003030 (unofficial, daily)
* 1.0.0-preview3-003171 (unofficial, daily)

So a pinned version is not 'latest'.

By invoking the script with the -DryRun switch I can inspect the URLs pointing to the zip packages to be downloaded. But sometimes I get 404 errors, so zip packages must be revoked, just like packages might be on a myget feed. 

So is the dotnet-install.ps1 install script only good for continually getting the latest preview build, or is there a way for me to 'pin' that version to fixed version, and knowing that I will not get 404's down the line? 

On the same note, I can tell that you guys are publishing builds in two different channels

* [SDK Binaries](https://www.microsoft.com/net/download)
* [Daily SDK Binaries](https://github.com/dotnet/cli#installers-and-binaries)

Does this relate to the scripts -Channel argument?

**Comment by maxild** [comment]
To be more specific. Lets say I want to pin to preview2 x64 windows bits. 

This is the download link announced at this [page](https://www.microsoft.com/net/download) 
```
https://download.microsoft.com/download/1/5/2/1523EBE1-3764-4328-8961-D1BD8ECA9295/dotnet-dev-win-x64.1.0.0-preview2-003121.zip
```

It works.

This is the download link generated by the dotnet-install script

```
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview2-003121/dotnet-dev-win-x64.1.0.0-preview2-003121.zip
```

The server responds with 404.

**Comment by enricosada** [comment]
check urls in the README.md in the corrisponding branch. for example for preview2 the directory is `preview` not `Sdk`
usually is enough to replace `Latest` with the version you need.
That's what i do

**Comment by maxild** [comment]
That is the download link in the [script](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.ps1#L174) when using $SharedRuntime. The doc comments say 

> Installs just the shared runtime bits, not the entire SDK

**Comment by maxild** [comment]
So what is the difference between

* .NET Core Binaries ($SharedRuntime is true)
* .NET Core SDK Binaries ($SharedRuntime is false, the default value)

I want to use the dotnet-installer to either setup CI builds, or temporarily aliasing specific dotnet in my workspace?

**Comment by maxild** [comment]
Okay...I got it. I need the SDK for local dev and CI purposes.

I have fixed my issue by changing this [line](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.ps1#L177) to

```
$PayloadURL = "$AzureFeed/$AzureChannel/Binaries/$SpecificVersion/dotnet-dev-win-$CLIArchitecture.$SpecificVersion.zip"
``` 

This url is in sync with the readme.md links in the rel/1.0.0-preview2 branch.

I will raise new issue, that refs this one, because I suspect substituting the /Sdk/ fragment with /$AzureChannel/Binaries/ will probably not be good for all scenarios, and we need a better fix or advice.

**Comment by maxild** [comment]
See #3728 for reasons why I am closing this issue
