### ISSUE TITLE
Build dotnet on Fedora 24

### ISSUE THREAD

**Issue by rimolive** [dotnet/cli#3717]
I'm trying to build[1] the project in my Fedora 24 laptop but I'm always getting "OS not found". Where should I specifically look to get my OS be detected by the build.sh?

[1]https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/developer-guide.md#buildingrunning

**Comment by sec** [comment]
https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.sh#L59

**Comment by rimolive** [comment]
Even getting a chance to change the script it still tries to download binaries specific to the Fedora version (which there is no binaries yet for F24). Question: Why attach the compilation with a very specific version of libicu? I don't think there is so many changes between version 54(F23) and  56 (F24).

**Comment by guoxiao** [comment]
In Fedora 24 the version of libicu is 56, not 54. So the prebuilt binaries for Fedora 23 cannot be used in Fedora 24 directly. 
We need new binaries for Fedora 24.

**Comment by josteink** [comment]
Is this just a CI-thing which must be done by MS, or can we build this our-selves as well? I really can't seem to find instructions or documentation for this component anywhere...

If we need help, who can help us out getting that done? ellismg? stephentoub?

**Comment by rimolive** [comment]
@guoxiao, that's what I said in my last comment. Sorry for not being very specific.

@josteink, it will be great if we can build those binaries for Fedora 24. I'm still looking for it.

**Comment by mickaelistria** [comment]
https://github.com/dotnet/cli/pull/3813 seems related

**Comment by josteink** [comment]
There's more to it than that, as mentioned in the comments on https://github.com/dotnet/coreclr/issues/6115, but it's a start and probably a required one.

I may be and to chip in some commits and effort in a few weeks when I'm back from my vacation, but I'm not making any promises.

They is of course unless someone else beats me to it.

**Comment by erick2red** [comment]
I'm interested on building those binaries myself. I can put some time to it, as long as someone with the knowledge point me in the right direction. I was able to build `coreclr` and `corefx` repositories on my Fedora 24, the parts than don't depends on the binaries, but from there to the binaries there's a part missing.

**Comment by josteink** [comment]
Whatever steps must be done for Fedora 24, the same probably applies for other new "platforms" which must be bootstrapped.

I've tried raising a discussion about it for FreeBSD here: https://github.com/dotnet/cli/issues/3815

Hopefully there will be some response.

**Comment by josteink** [comment]
@erick2red I think a first start is trying to build `stage0`/`corehost` on Fedora24 and see if that succeeds.

If that succeeds and the resulting binary seems to work fine, I would assume the rest of the SDK should build nicely as well (although as mentioned in the related FreeBSD issue #3815, details and docs on building the SDK are sadly lacking).

After that, it may just be prodding someone at Microsoft, responsible for the CI and build-servers to also create Fedora blobs.

If it already works on Fedora 23, I cannot imagine it taking much effort to get this going on Fedora 24, but as always, there might be some unforeseen roadblocks. Time will tell.

**Comment by agfp** [comment]
Same problem here.

When I try to build the cli for Fedora 24 I get the following error:

`dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003215/dotnet-dev--x64.1.0.0-preview3-003215.tar.gz`
`dotnet-install: Calling: download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview3-003215/dotnet-dev--x64.1.0.0-preview3-003215.tar.gz /tmp/dotnet.FTUQWdJGi`
`dotnet_install: Error: Download failed`

**Comment by rimolive** [comment]
@agfp quit trying to build cli at this moment. Before cli other components must be built before, and that's what I'm working on. I'll let you know if I have any news.

**Comment by josteink** [comment]
Heads up: The following issue has some technical details which may be of help:

https://github.com/dotnet/corefx/issues/10610

**Comment by livarcocc** [comment]
We support Fedora 24 in preview2.1.

**Comment by mickaelistria** [comment]
cool, thanks. Does performing the install steps from https://www.microsoft.com/net/core#fedora get preview2.1 ? I see the download only mention "preview2".

**Comment by carterpants** [comment]
Install steps and links for Fedora 24 have not yet been updated.

**Comment by josteink** [comment]
I'm going to guess preview 2.1 is this one?

https://github.com/dotnet/core/releases/tag/v1.1.0-preview1 (don't mind the name in the link...)
