### ISSUE TITLE
dotnet test returns exit code of 1 for workspace error

### ISSUE THREAD

**Issue by dsparkplug** [dotnet/cli#3723]
Some unit test runners e.g. XUnit return an exit code of 1 to indicate a test failure. When calling test runners from CI, we need to differentiate between test failures and errors due to the command errors.

Line 58 in [/dotnet/commands/dotnet-test/Program.cs](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-test/Program.cs) returns an exit code of 1 for an error:

`
    var projectContext = workspace.GetProjectContext(projectPath, dotnetTestParams.Framework);
    if (projectContext == null)
    {
           Reporter.Error.WriteLine($"Project '{projectPath}' does not support framework: {dotnetTestParams.UnparsedFramework}");
           return 1;
     }
`

Can this be changed to a negative number e.g. -3 so that it does not clash with the exit code from the test runner? Happy to put in a pull request if there is agreement on the number.

**Comment by piotrpMSFT** [comment]
@dotnet/vstest this seems to still be an issue in the current `dotnet test` implementation. Can you open a tracking issue for this?

**Comment by livarcocc** [comment]
This code has changed considerably since we moved to msbuild. Going to close this issue. If this is still a problem, please file a new issue.
