### ISSUE TITLE
Unable to name based Project Reference

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#3724]
## Steps to reproduce
Create an app that references a library project per https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries, under ProjectToProject referencing section.

## Expected  behavior
App is successfully built

## Actual behavior

bash-3.2$ dotnet restore
log  : Restoring packages for /Users/gkhanna/Dev/golden/src/app/project.json...
log  : Restoring packages for /Users/gkhanna/Dev/golden/src/lib/project.json...
error: Unable to resolve 'GreetLib (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
log  : Lock file has not changed. Skipping lock file write. Path: /Users/gkhanna/Dev/golden/src/lib/project.lock.json
log  : /Users/gkhanna/Dev/golden/src/lib/project.json
log  : Restore completed in 636ms.
log  : Writing lock file to disk. Path: /Users/gkhanna/Dev/golden/src/app/project.lock.json
log  : /Users/gkhanna/Dev/golden/src/app/project.json
log  : Restore failed in 742ms.
 
Errors in /Users/gkhanna/Dev/golden/src/app/project.json
    Unable to resolve 'GreetLib (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.

## Environment data
`dotnet --info` output:

bash-3.2$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)
 
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5
 
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
bash-3.2$

**Comment by livarcocc** [comment]
This will be support in MSBuild.
