### ISSUE TITLE
Enable dotnet --clean

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#3725]
## Steps to reproduce

There is no way to do a clean build. The closest is to force non-incremental build
## Expected  behavior

Clean build is supported.
## Actual behavior

Not supported
## Environment data

`dotnet --info` output:

**Comment by kibbled** [comment]
Any update on this feature? This is still not marked complete even though the milestone it was pegged for is complete.

**Comment by blackdwarf** [comment]
This is now done in the latest tooling via the `dotnet clean` command. If you get the bits from the links in the README on this repo, you can try it out! :) 

Will close, please reopen if more info is needed.

**Comment by oliverjanik** [comment]
Except it does not clean the nupkg that the build generated
