### ISSUE TITLE
publish does not show some errors

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3732]
If my `publishOptions` contains a mapping like this: 

```
    "mappings": {
      "./HelloWeb/": "../HelloWeb/"
    }
```

The folder won't be copied. Apparently having `.` in target path is not supported. There is even an error for that: 

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Files/IncludeFilesResolver.cs#L45

The error is not shown to the user so it is hard to figure out why the folder isn't copied.

**Comment by piotrpMSFT** [comment]
`publishOptions` gets translated into MSBuild content in preview3. Error handling subsystem is vastly different, so this issue is not actionable.
