### ISSUE TITLE
Channels documentation is outdated

### ISSUE THREAD

**Issue by naamunds** [dotnet/cli#3733]
The info in https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/cli-installation-scenarios.md#channels is outdated.  It refers to a "Future" channel using the master branch, but the master branch no longer exists.  It's not clear what the current state of the Future channel is, or what the plan is for CLI channels in general.

cc: @blackdwarf @eerhardt @MichaelSimons

**Comment by piotrpMSFT** [comment]
Moving to 2.0.0 when channels become a priority again during the development cycle.

**Comment by johnbeisner** [comment]
Similar: https://github.com/dotnet/cli/issues/6541

**Comment by johnbeisner** [comment]
Addressed via:
https://github.com/dotnet/cli/pull/7330
https://github.com/dotnet/cli/pull/7332
https://github.com/dotnet/cli/pull/7336
https://github.com/dotnet/cli/pull/7342
https://github.com/dotnet/cli/pull/7355
