### ISSUE TITLE
UX improvement: dotnet CLI should automatically restore when necessary

### ISSUE THREAD

**Issue by benjamincburns** [dotnet/cli#3736]
Error messages which instruct the user to carry out some action can generally be replaced with the action itself. In this case, the error `NU1009: The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file` and other similar warnings/errors are annoying and it seems they should be replaced with an automatic run of `dotnet restore.`
## Steps to reproduce

```
dotnet new
dotnet run
```
## Expected  behavior

The `dotnet` cli recognizes that `project.lock.json` is missing or out of date and automatically runs `dotnet restore` without prompting the user to do it.

```bburns@workstation:~/projects/dotnettest$ dotnet run
log  : The expected lock file doesn't exist. Automatically restoring packages to recreate it.
log  : Restoring packages for /home/bburns/projects/dotnettest/project.json...
log  : Writing lock file to disk. Path: /home/bburns/projects/dotnettest/project.lock.json
log  : /home/bburns/projects/dotnettest/project.json
log  : Restore completed in 709ms.
Project dotnettest (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling dotnettest for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.8663525

Hello World!

```

## Actual behavior
```

bburns@workstation:~/projects/dotnettest$ dotnet run
The current project is not valid because of the following errors:
/home/bburns/projects/dotnettest/project.lock.json(1,0): error NU1009: The expected lock file doesn't exist. Please run "dotnet restore" to generate a new lock file.

```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

```

**Comment by benjamincburns** [comment]
If there's agreement that this should be done I'll happily submit a PR.

**Comment by piotrpMSFT** [comment]
Related to #2199

**Comment by benjamincburns** [comment]
@piotrpMSFT, I assume that since this has been assigned there's agreement that it should be done, but you don't need me to submit a PR?

**Comment by piotrpMSFT** [comment]
@benjamincburns the intent is something we want to address but this needs considerable design work before we can look to a PR. Specifically, you don't want to just execute 'restore' before each of the potentially affected verbs all the time due to the huge cost of a network hit + package graph evaluation. @livarcocc will be looking at opportunities to surgically determine that a restore simply hasn't happened in some obvious cases [e.g. there is no project.assets.json yet... but where should it be? What if the user redirected their obj folder?]

**Comment by benjamincburns** [comment]
Perhaps this is overly simplistic, but I'd imagine that whenever it is presently acceptable to print an error message which prompts the user to execute a restore, the tool should just execute the restore rather than print that error message, then carry on with its original task. Otherwise in cases where no error message would be printed, the tool shouldn't automatically execute a restore.

If anything is done which goes beyond this, I'd think there's a fair amount of risk of assuming an implicit action on behalf of the user which may be inappropriate or incorrect.

**Comment by livarcocc** [comment]
It is actually not possible to do the restore and say build in the same msbuild invocation.

Because of that, I will close this one in favor of https://github.com/dotnet/cli/issues/2199.

**Comment by benjamincburns** [comment]
@livarcocc is the goal of #2199 still to provide better error messages in cases like these? If so, I don't see how it does anything to fix this usability issue.

Taking for granted that it's impossible to restore & build in the same msbuild invocation, what prevents the overall process from detecting the need for a restore, performing said restore, then reinvoking msbuild to handle the build?

I don't think this is a high priority issue, so no worries if you'd rather leave it closed. However it is the sort of usability rule which makes the difference between tools which are a pleasure to use, and those which are simply sufficient for the task.

**Comment by livarcocc** [comment]
@benjamincburns I think you are right. I am re-opening this to see if there is anything at all that we can do that won't risk causing more trouble than fixing it.

**Comment by livarcocc** [comment]
We are tracking this work at https://github.com/dotnet/cli/issues/6105. Closing this one as a dup.
