### ISSUE TITLE
Rename dotnet init to dotnet new

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#374]
Based on some of the feedback we've heard in face to face interactions, "init" as a verb is not really intuitive for what it does. The actual functionality is not in question, just the naming of the command.

Some suggestions:

* `dotnet template`
* `dotnet create`
* `dotnet new`

The last one, `dotnet new` is, I think, the strongest contender for the new name. It is pretty clear. 

/cc @richlander @piotrpMSFT @Petermarcu @davidfowl

**Comment by khellang** [comment]
`dotnet scaffold`?

**Comment by davidfowl** [comment]
+1 to create or new since it's not customizable.

**Comment by blackdwarf** [comment]
@khellang `dotnet scaffold` is a good one, I just think that maybe it implies a little bit more than what this command is doing.

**Comment by khellang** [comment]
Oh, now I see what it does. Yeah, scaffold should be reserved for something bigger :smile:

**Comment by Petermarcu** [comment]
I like `dotnet new` :)

**Comment by mellinoe** [comment]
`dotnet new` is good. Rust uses `cargo new` for reference, and it seemed natural there. Although `dotnet` is a bit of a general purpose tool so there's slightly more ambiguity, it still seems fine.

**Comment by blackdwarf** [comment]
Seems like "new" is getting traction. :)

**Comment by krwq** [comment]
seems like we all agree on `dotnet new` :+1:

**Comment by joshfree** [comment]
`dotnet new` :+1:

**Comment by brthor** [comment]
+1 for `dotnet new` :)

**Comment by clrjunky** [comment]
dotnet program

**Comment by krwq** [comment]
You can create a symlink for that :)

**Comment by clrjunky** [comment]
@krwq sounds to me pretty straightforward :)
