### ISSUE TITLE
add command that install nuget package

### ISSUE THREAD

**Issue by otakusid** [dotnet/cli#3741]
Looks like there is no command that I can use to **install nuget** package to the project. To perform this I need to use VisualStudio or edit **project.json** file manualy and then run **dotnet restore**

It would be good if I can run **dotnet install Newtonsoft.Json** and receive modified **project.json** with all dependency staff configured.

Without this command I cant manage my project from console and should use IDE or perform borring file editing sings

**Comment by taherchhabra** [comment]
+1

**Comment by blackdwarf** [comment]
This should go to Nuget/Home.
