### ISSUE TITLE
dotnet pack's packOptions should support distinguishing referenced assemblies from design-time assemblies.

### ISSUE THREAD

**Issue by plioi** [dotnet/cli#3743]
This page documents the latest project.json structure, including packOptions used by `dotnet pack`: https://github.com/aspnet/Announcements/issues/175

This page documents NuGet's own handling of explicit assembly references: https://docs.nuget.org/create/nuspec-reference#specifying-explicit-assembly-references

It appears that it's not yet possible to use `dotnet pack` to support such design-time assemblies in the package's lib folder.

**Comment by FransBouma** [comment]
(Preview 2 tooling) yep, dotnet pack ignores the packOptions in the project.json. To use the elements in project.json during dotnet pack you have to use the deprecated elements, they're otherwise ignored.

**Comment by piotrpMSFT** [comment]
Since preview3 moved us from project.json to csproj, these PJ properties won't be getting brought forward. The preview3 CLI includes a `dotnet nuget` command in addition to `restore` and `pack` giving you access to NuGet itself and, bugs aside, removing the blocks we saw with this class of issue.
