### ISSUE TITLE
Unable to restore/run on OSX 10.11.5

### ISSUE THREAD

**Issue by aapis** [dotnet/cli#3746]
I'm unable to restore/run on OSX 10.11.5.  First raised this issue in https://github.com/aspnet/cli-samples/issues/63 but it affects any `dotnet` app on my machine.

## Steps to reproduce
Doesn't matter what project, hello world errors out in the same way.

```
prieber@~/Personal/dotnet-cli-samples$ dotnet restore
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloMvcApi/project.json...
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloMvc/project.json...
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloWebFull/project.json...
log  : Restoring packages for /Users/prieber/Personal/dotnet-cli-samples/HelloWeb/project.json...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Couldn't connect to server
```

## Expected  behavior

Dependency list is created and I am able to execute `dotnet run`.

## Actual behavior

`error: Unable to load the service index for source https://api.nuget.org/v3/index.json.`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

Tried upgrading curl but the issue is present in `7.43.0` and `7.49.1`.  Have already run `brew link --force openssl`.

**Comment by KSubedi** [comment]
Does doing `curl https://api.nuget.org/v3/index.json` give you any errors?

**Comment by aapis** [comment]
@KSubedi `curl: (7) Failed to connect to api.nuget.org port 443: Connection refused`

**Comment by KSubedi** [comment]
Interesting. Could be a lot of reasons, but seems like somehow your firewall or something is blocking you from accessing nuget's api servers. To make sure that not all of your https connections are blocked, could you try `curl https://github.com`. Also, if you have a firewall or antivirus software that could be blocking connections, make sure that api.nuger.org is whitelisted and outbound port 443 is allowed.

**Comment by aapis** [comment]
I've inquired about potential blocking at the network level, thanks for the suggestion.  Nothing I've done locally explicitly blocks 443 or *.nuget.com, queries such as `curl https://github.com` work as expected.  I'll try tethering off my phone too.  Thanks.

**Comment by KSubedi** [comment]
I would also try to open `https://api.nuget.org/v3/index.json` in your browser and see if that gives a more specific error. I would also install `mtr` using `brew install mtr` and try to run `sudo mtr api.nuget.org` and see where the blocking is happening. Also, if you are using a ISP that shared the IP address or rotates IP frequently, there is a possibility that the IP might have been blacklisted on nuget's servers in which case I would try to reset the router and see if it assigns a new IP. Good luck!

**Comment by aapis** [comment]
Ok, problem solved and it was totally on my end!  `mtr` wouldn't install but I ran `traceroute` and the first domain it tries to hit is `cs1.wpc.v0cdn.net`.  I use https://github.com/StevenBlack/hosts for hosts file blocking, and this v0cdn.net domain is located on about line ~27726.  I'll see if I can get that removed from, or at least commented out, from that list.  Thanks for the help!

**Comment by KSubedi** [comment]
Glad it was resolved!
