### ISSUE TITLE
install.sh vs PKG/DEB based installers.

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#375]
See https://github.com/dotnet/cli/pull/331#issuecomment-161401074

Seems like there's an inconsistency between install.sh vs pkg/deb installers. 

This should be either documented or the inconsistency removed.

**Comment by piotrpMSFT** [comment]
@blackdwarf can you pull together a list of our env vars? What they do, when they are required, whether installers set them, etc?

**Comment by muratg** [comment]
Still having issues with this on OS X.  

If I set CLI up using PKG, everything works fine. If I use the scripts under `obtain`, I get the error: 

```
murats-mbp% dotnet build
error: the .NET tools installation appears to be corrupt!
error: specifically, the tools could not be located in the /usr/local/share/dotnet/share/dotnet/cli directory
```

Only way to work around it is having the export `DOTNET_TOOLS=/usr/local/share/dotnet`.

cc @pakrym

**Comment by blackdwarf** [comment]
@muratg I don't think that PKG needs to set up this env variable.

**Comment by blackdwarf** [comment]
@muratg the scripts are being rehauled as part of a larger work. I will close this issue down. Please reopen if needed.
