### ISSUE TITLE
Whaz up with CLI tools docs?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#3751]
@blackdwarf 

It looks like your docs site has been taken down: https://dotnet.github.io/docs/core-concepts/core-sdk/cli/index.html 404's now.

I'm might be looking in the wrong place. :smile: Is this the new CLI tools docs? https://docs.microsoft.com/en-us/dotnet/articles/core/tools/index

If so, how do we search that? ... and will the prior content (e.g., app types) make its way over there?

**Comment by blackdwarf** [comment]
@GuardRex yep, that is the new site. Is there content that was on the old site that didn't make it over? If so, please open up an issue on dotnet/core-docs, this is where we are (still) doing the docs work. :smiley:
