### ISSUE TITLE
How to enable Analyzer ErrorLog on build?

### ISSUE THREAD

**Issue by Dresel** [dotnet/cli#3755]
In standard projects you can add analyzer logging via [errorlog switch](https://github.com/dotnet/roslyn/issues/430).

How can this be done for .NET core projects? I tried adding this flag to the additionalArguments in buildOptions in the project.json file, but this results in a FileNotFoundException.

**Comment by piotrpMSFT** [comment]
Preview3's msbuild support will allow you to use the same errorlog switch. See #3175 for some snippets of how that look in .NET Core.
