### ISSUE TITLE
Files are not included for compilation, and no detail available

### ISSUE THREAD

**Issue by apawsey** [dotnet/cli#3757]
I have a project.json, where I want to include cs files from another project.. I have tried everything to get the files to include, but I get nothing in the output!  I have read https://github.com/aspnet/Announcements/issues/175 and about 20 other pages on project.json format, and I still cannot seem to get it to include the files.  It doesn't seem to care about those values, because the paths can be complete nonsense (by that I mean correctly formatted, but non-existent) and the build still succeeds.

Note this project.json is not my desired configuration, I expected to just have the root buildOptions node, however this is me attempting every possible route, and having no luck.
## Steps to reproduce

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50",
      "buildOptions": {
        "compile": {
          "builtIns": [
            "../EntityFramework.DbContext/*.cs",
            "../EntityFramework.DbContext/Interfaces/*.cs"
          ],
          "include": [
            "../EntityFramework.DbContext/*.cs",
            "../EntityFramework.DbContext/Interfaces/*.cs"
          ]
        }
      }
    }
  },
  "buildOptions": {
    "compile": {
      "builtIns": [
        "../EntityFramework.DbContext/*.cs",
        "../EntityFramework.DbContext/Interfaces/*.cs"
      ],
      "include": [
        "../EntityFramework.DbContext/*.cs",
        "../EntityFramework.DbContext/Interfaces/*.cs"
      ]
    }
  },
  "compile": [
    "../EntityFramework.DbContext/*.cs",
    "../EntityFramework.DbContext/Interfaces/*.cs"
  ]
}

```
## Expected  behavior

The project compiles, including the classes defined in the specified cs files, in the output assembly.
## Actual behavior

Output assembly does not contain the classes defined.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14372
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
Try this out with preview3 bits. I've seen some experiments with using `../` globs successfully pick up files from parent directories. If you see issues, run `dotnet build /v:diag` [preview3+ only] to see how the engine is processing the glob and what content is being included.

**Comment by livarcocc** [comment]
Fixed since we moved to msbuild. Closing old bug.
