### ISSUE TITLE
Change the "dev" substring in the installer/tarballs filename to "sdk"

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#3758]
## Steps to reproduce

Download the installer/zip/tarball and observe the file name. 
## Expected  behavior

See some indication that this is the SDK. For example `dotnet-sdk-win-x64.latest.exe`. 
## Actual behavior

See `dotnet-dev-win-x64.latest.exe`. 
## Environment data

`dotnet --info` output: N/A

**Comment by richlander** [comment]
I'd like to see the first "." converted to a "-", too.

Here's the OS X PKG today: dotnet-dev-osx-x64.1.0.0-preview2-003121.pkg

It should be (ignoring the "dev" -> "sdk" issue): dotnet-dev-osx-x64-1.0.0-preview2-003121.pkg

The "." after "x64" isn't the appropriate separator.

**Comment by livarcocc** [comment]
This has been done for a while now.
