### ISSUE TITLE
Discovering unit tests fail when test project references a second test project 

### ISSUE THREAD

**Issue by niemyjski** [dotnet/cli#3759]
All the code is located here: https://github.com/exceptionless/Foundatio (Windows 10 + RTM Bits)

```
------ Discover test started ------
Discovering tests in 'C:\Code\Foundatio\test\Foundatio.AWS.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Code\Foundatio\test\Foundatio.AWS.Tests\project.json" --output "C:\Code\Foundatio\test\Foundatio.AWS.Tests\bin\Debug\net46\win7-x64" --port 26870 --parentProcessId 16516 --no-build]
'test-xunit' returned '-532462766'.
Discovering tests in 'C:\Code\Foundatio\test\Foundatio.Azure.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Code\Foundatio\test\Foundatio.Azure.Tests\project.json" --output "C:\Code\Foundatio\test\Foundatio.Azure.Tests\bin\Debug\net46\win7-x64" --port 26875 --parentProcessId 16516 --no-build]
'test-xunit' returned '-532462766'.
Discovering tests in 'C:\Code\Foundatio\test\Foundatio.Redis.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Code\Foundatio\test\Foundatio.Redis.Tests\project.json" --output "C:\Code\Foundatio\test\Foundatio.Redis.Tests\bin\Debug\net46\win7-x64" --port 26880 --parentProcessId 16516 --no-build]
'test-xunit' returned '-532462766'.
Discovering tests in 'C:\Code\Foundatio\test\Foundatio.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\Code\Foundatio\test\Foundatio.Tests\project.json" --output "C:\Code\Foundatio\test\Foundatio.Tests\bin\Debug\netcoreapp1.0" --port 26887 --parentProcessId 16516 --no-build]
[xUnit.net 00:00:00.0597555] Skipping: Foundatio.Tests (no reference to xUnit.net)
```

It seems to be occurring when a test project references another one. We do this because we have base classes in the main project and then integrations run those base tests and inject new implementations.

**Comment by niemyjski** [comment]
There is something goofy going on here. I had to run a powershell script to delete all bin obj folders and the tests were discovered.

**Comment by piotrpMSFT** [comment]
Odd. Since we don't have a repro we couldn't investigate this one. If you see it again, please do re-open.

**Comment by niemyjski** [comment]
I haven't tried this since I moved on to let it bake, but you weren't  able reproduce this with the dotnet branch of the above repo? https://github.com/exceptionless/Foundatio

**Comment by piotrpMSFT** [comment]
Reopening. Thanks for the repro. I'll take a look at this soon.

**Comment by eegasai** [comment]
Hi,
i am getting same error code and visual studio is not able to find the unit tests
'test-xunit' returned '-532462766'.
below are the xunit packages that we are using
 "dotnet-test-xunit": "2.2.0-preview2-build1029",
 "xunit": "2.2.0-beta3-build3402",

Is there any  workaround for this issue?

**Comment by piotrpMSFT** [comment]
@eegasai I haven't had a chance to see if this repro's in csproj/preview3 yet. Can you try migrating and giving it a shot?

**Comment by FelschR** [comment]
@eegasai Adding the following dependency into the test projects fixed it for me:

        "Microsoft.DotNet.InternalAbstractions": "1.0.1-beta-003206",

**Comment by Fujivato** [comment]
@FelschR your solution also fixed it for me too, thanks for sharing.

**Comment by minddagap** [comment]
@FelschR  I dont know how you got this. But its brilliant , thanks

**Comment by zfrolov** [comment]
@FelschR 
Thanks! Adding said dependency worked for me.

**Comment by alzuma** [comment]
` "Microsoft.DotNet.InternalAbstractions": "1.0.0"` worked for me.

**Comment by tenshinhan** [comment]
still getting "'test-xunit' returned '-2147450749'" error, using 

`
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "dotnet-test-xunit": "2.2.0-preview2-build1029",
    "xunit": "2.2.0-beta4-build3444",
    "Microsoft.DotNet.InternalAbstractions": "1.0.500-preview2-1-003177"  },

  "testRunner": "xunit",

`
any workaround out there?

**Comment by pvlakshm** [comment]
Since there is an available workaround, we're not planning to investigate this issue. We're focusing on the newer (MSBuild/csproj) based unit test platform, and most of our energy is going there. As @piotrpMSFT asked above, please let us know if it repros on Preview3+ tooling, we will be happy to investigate further.

**Comment by progrish** [comment]
"Microsoft.DotNet.InternalAbstractions": "1.0.1-beta-003206" Fixed XUnit problem..

**Comment by piotrpMSFT** [comment]
Ok, sounds like we have a workaround for project.json and no repro on current tooling. Closing the issue.

**Comment by nukec** [comment]
"Microsoft.DotNet.InternalAbstractions": "1.0.0" helped with issue

**Comment by niemyjski** [comment]
@piotroko I think this is still an issue with RC3, Can you please reopen and take a look at the same branch. None of my netcoreapp tests are discovered. I have to remove all the .net core tests for them to be discoverable :\ 

https://github.com/dotnet/cli/issues/5548

**Comment by piotrpMSFT** [comment]
@niemyjski thanks for opening a new issue. Sorry, I'm only now catching up on notifications...

**Comment by piotrpMSFT** [comment]
Also, the team now has two Piotr's, @piotroko and @piotrpmsft. Not at all confusing 👍
