### ISSUE TITLE
Add `deps` file api

### ISSUE THREAD

**Issue by pakrym** [dotnet/cli#376]
Add a project `Microsoft.Extensions.DependencyModel`
Add a class `DependencyContext` this represents flat list of `.deps` file entries
With `.Load` method that read entries from `{Name}.deps` by default, using format we don't know yet.
Also, should it be able to Write these files?

/cc @davidfowl

**Comment by pakrym** [comment]
https://github.com/dotnet/cli/tree/pakrym/deps

**Comment by piotrpMSFT** [comment]
What's the scenario? Assembly Loading?

**Comment by davidfowl** [comment]
@piotrpMSFT Yep! And getting compilation data at runtime.

**Comment by piotrpMSFT** [comment]
Cool. I was thinking this should just go into ProjectModel but given the runtime usage for non-tools this makes sense.
