### ISSUE TITLE
Broken link in dotnet new -t web README

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3761]
[The README for `dotnet new -t web`](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-new/CSharp_Web/README.md) contains a link to https://go.microsoft.com/fwlink/?LinkID=517853, which redirects to https://dotnet.github.io/docs/core-concepts/core-sdk/cli/index.html, which is 404 since the migration to docs.microsoft.com. The correct new URL is https://docs.microsoft.com/en-us/dotnet/articles/core/tools/index.

I'm assuming the right fix is to fix the fwlink and not just change the link to directly point to docs.microsoft.com, otherwise I would fix it myself.

**Comment by piotrpMSFT** [comment]
The preview3 web template dropped the readme.md file.
