### ISSUE TITLE
Add analyzer support for local project

### ISSUE THREAD

**Issue by nothrow** [dotnet/cli#3765]
https://github.com/dotnet/cli/issues/83 added support for referencing 3rd party code analyzers. 
I am developing solution, where I would like to add my own, solution-specific code analysis. It is not currently possible to reference `project.json`-project and use it as code analyzer.

**Comment by piotrpMSFT** [comment]
In #3175 I showed how analyzers surface in the preview3 msbuild CLI. As you can see, you'll be able to add <Include>s in your project file and pull in other project outputs. Just mimic the pattern I've shown from the nuget.g.props file.
