### ISSUE TITLE
Use default project.json if one is not present

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#377]
If there is no project.json in the application that is currently being ran (or compiled), use the default project.json that is shipped with the CLI and that contains the stdlib. 

/cc @piotrpMSFT

**Comment by krwq** [comment]
I think this should be happening. Also we could make `dotnet new` create project only if there are already files in the directory

**Comment by piotrpMSFT** [comment]
Can we spell out the algorithm here a bit more clearly? Which command(s) check for and create project.json? What are the two operating modes of `dotnet new`?

**Comment by blackdwarf** [comment]
@krwq @piotrpMSFT fair enough, let me take a swing at `dotnet new` at this point. Need to think a little on the rest of them. 

`dotnet new` should, in my mind, always drop a project.json in the dir. If the dir is empty, it should also create some sample code files (i.e. hello world). If it is not empty, it should generate a standard project.json that references stdlib. The reasoning is that by invoking this command, the user is telling us that he wants a "new project". It is also, as we discussed, a good way to provide new users insight into the structure and values of project.json.

**Comment by jasonwilliams200OK** [comment]
@blackdwarf, in addition to your points on algorithm, if `project.json` is already present, overwrite it.
IMO, we can make analogy with `npm init`:

```cmd
:: tip: install latest node from https://nodejs.org/
C:\>mkdir temp ** mkdir temp\test && cd temp\test
C:\temp\test>npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (test) my-test
version: (1.0.0) 0.0.1
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to C:\temp\test\package.json:

{
  "name": "my-test",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes) yes

C:\temp\test>
:: now re-run the same command again with name 'my-test2' and different version,
:: it will overwrite existing package.json
```

**Comment by blackdwarf** [comment]
@jasonwilliams200OK slightly different than what I had in mind. However, my comment above with the "algorithm" may be void in the face of new developments.

**Comment by blackdwarf** [comment]
OK, closing this since we need more discussions on this topic and the stuff in this issue is not valid. I will reopen the issue as the need arises.
