### ISSUE TITLE
Compiling UWP in Release mode return error ILT0040: Type 'System.Runtime.Serialization.DataContract' was not found

### ISSUE THREAD

**Issue by dersteve** [dotnet/cli#3772]
## Steps to reproduce
Build a UWP app with VS2015 Update 2 in release mode with native tool chain. 

## Expected  behavior
Builds successfully.

## Actual behavior
Fails with the following error:
ILT0040: Type 'System.Runtime.Serialization.DataContract' was not found. Check that your build system references Windows.winmd, references .NET for Windows Store Apps, and is configured to use .NET Native.

## Environment data
`dotnet --info` output:

UWP 1.3.1 tools installed. 
Windows 10586 SDK installed.

I see the same behaviour on VS2015 Update 3 and UWP 1.4 tools installed.

**Comment by rogersachan** [comment]
I'm also having this exact same issue, are there any fixes that can be used until this is fixed?

**Comment by blackdwarf** [comment]
@dersteve the CLI toolchain is not used for building UWP applications, so this is definitely not the right repo for this issue.
