### ISSUE TITLE
Provide command to exercise "first run" behaviour explicitly

### ISSUE THREAD

**Issue by jskeet** [dotnet/cli#3774]
When `dotnet new` or similar commands are first run on a brand new dotnet installation, there's a bunch of work performed to basically optimize the experience.

This is great - but the logs of that are undesirable in a CI environment. (Indeed, the backspaces emitted broke a Jenkins log, but that's another matter.)

The solution I've come up with is to force the installation to initialize itself separately before I do any actual work - I can swallow those logs and keep the logs for the *real* work. However, in order to persuade the installation to do all the "first time" work, I need to call something like `dotnet new` or `dotnet restore`. I don't want to restore any actual projects, nor do I want to create a new one - I just want to ensure it's fully initialized.

Could we have a `dotnet ensure-initialized` command or something similar which is a no-op if the work has already been performed, but runs the initialization otherwise?

**Comment by akoeplinger** [comment]
https://github.com/dotnet/cli/issues/3692 seems to be the same. I actually need this for Travis as well, so I upvoted the issue 😄

**Comment by jskeet** [comment]
@akoeplinger Thanks for that - I did a few searches, but didn't find that one before. Will close this now.
