### ISSUE TITLE
How to run F# type providers using .Net Core SDK Preview2?

### ISSUE THREAD

**Issue by svick** [dotnet/cli#3776]
## Steps to reproduce

1. Run `dotnet new -l fs`.
2. Add dependency to `"FSharp.Data": "2.3.1"`.
3. `dotnet restore`, `dotnet build`

## Expected  behavior

`dotnet build` succeeds and I can then go on to use type providers from FSharp.Data.

## Actual behavior

`dotnet build` fails with:

> error FS3031: The type provider 'C:\Users\Svick\\.nuget\packages\FSharp.Data\2.3.1\lib\portable-net45+netcore45\FSharp.Data.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.DesignTime' which cannot be loaded or doesn't exist. Could not load file or assembly 'FSharp.Data.DesignTime, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
warning FS3005: Referenced assembly 'C:\Users\Svick\\.nuget\packages\FSharp.Data\2.3.1\lib\portable-net45+netcore45\FSharp.Data.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

I have also tried it with:

```
.NET Command Line Tools (1.0.0-preview3-003171)

Product Information:
 Version:            1.0.0-preview3-003171
 Commit SHA-1 hash:  da57475105

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

[Originally reported on SO.](http://stackoverflow.com/q/38064056/41071)

**Comment by blackdwarf** [comment]
I thought you are supposed to use the F# compiler for all things F#?

/cc @cartermp @enricosada

**Comment by svick** [comment]
@blackdwarf I don't understand. Are you saying I'm doing something wrong in my Steps to reproduce? Or that I should report this at Microsoft/visualfsharp? Or something else?

**Comment by blackdwarf** [comment]
@svick I don't know, that's why I asked. I assumed that the F# compiler is a tool, right? `dotnet-compile-fsc`?

**Comment by enricosada** [comment]
@svick the `FSharp.Data` doesnt support .net core (netstandard1.6) yet

You can see in this checklist to where report bugs: https://github.com/dotnet/netcorecli-fsc/wiki/FAQ#where-to-report-bugs

or just open it in https://github.com/dotnet/netcorecli-fsc , i'll move it

thx @blackdwarf for ping

**Comment by svick** [comment]
@enricosada Moved as https://github.com/dotnet/netcorecli-fsc/issues/16.

**Comment by enricosada** [comment]
thx @svick !
