### ISSUE TITLE
Embed and serve static files from parent directory

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/cli#3780]
I'm using the following registration to embed and serve static files.

`Startup.cs` :

``` c#
public void Configure(IApplicationBuilder app)
{
  app.UseStaticFiles(new StaticFileOptions
  {
    RequestPath = new PathString("/js"),
    FileProvider = new EmbeddedFileProvider(
      GetType().GetTypeInfo().Assembly,
      baseNamespace = "src.dist.js"
    });
}
```

`project.json`:

``` json
{
  "buildOptions": {
    "embed": {
      "include": ["./dist/**"]      
    }
  }
}
```

This works great but now I'm thinking about changing the structure of my project and put the `dist` directory outside `src`. So, is it possible to register the embedded file provider and embed files in `project.json` from a directory one level up from the `Startup.cs` file?

**Comment by piotrpMSFT** [comment]
you should be able to do this with "../dist/**"
