### ISSUE TITLE
Add ability to specify NuGet package ID other than the project name

### ISSUE THREAD

**Issue by tsvetomir** [dotnet/cli#3782]
Currently the `name` setting is used as:
- Default namespace. [Not overridable](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/CompilerUtil.cs#L146).
- NuGet Package ID. [Not overridable](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-pack/PackageGenerator.cs#L384).
- Assembly name. Overridable through `buildOptions.outputName`

Suppose we want to give the NuGet package a user-friendly ID. Currently this is not possible.
It would be great if it can be overriden in packOptions:

```
"name": "My.Project",
packOptions: {
  "id": "My.Lovely.Project"
}
```

**Comment by maxim-boligatov** [comment]
It can be good idea!

It can solve issues like this one:
http://stackoverflow.com/questions/38407015/net-core-project-json-multiple-projects-with-the-same-name

**Comment by piotrpMSFT** [comment]
Moved to nuget/home to get the right Property to set in csproj.
