### ISSUE TITLE
dotnet publish - please show full path to publish folder

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#3784]
## Steps to reproduce

Run `dotnet publish -o some\relative\folder`
## Expected  behavior

The output in the console shows the absolute path to the publish folder: i.e 

```
publish: Published to C:\SomeDir\SomeFoler\some\relative\folder

```
## Actual behavior

The output in the console shows the relative path - which makes it harder to actually track down where the folder is, when the environment current path isn't set to what you might be expecting. For example on CI servers.

```
publish: Published to some\relative\folder

```
## Environment data

`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/3176632/16591196/a6cdfe62-42d2-11e6-9463-a4ace8f1f898.png)

**Comment by piotrpMSFT** [comment]
moved to the sdk repo
