### ISSUE TITLE
Feature: Add an option so dotnet restore of a project would also restore all project dependencies

### ISSUE THREAD

**Issue by eamodio** [dotnet/cli#3785]
## Steps to reproduce

`dotnet restore /src/foo` only restores for the foo project (assuming there is a `project.json` in there
## Expected  behavior

Add something like:
`dotnet restore /src/foo --includeProjDeps` that would not only restore foo, but also any projects that foo depends on 

This would be useful for CI servers to reduce the amount of work that restore would need to do (e..g in a large repo with many separate projects) and also eliminate the need to re-list the project dependencies to script out `dotnet restore` manually
## Actual behavior

Feature doesn't exist
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by blackdwarf** [comment]
This should be moved to Nuget/Home.

**Comment by livarcocc** [comment]
This capability is now available in the new msbuild based dotnet restore.
