### ISSUE TITLE
Empty define variable

### ISSUE THREAD

**Issue by techcap** [dotnet/cli#3790]
## Steps to reproduce

Use below project.json

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "define": [ "Spe_Host", ""]
  },

  "frameworks": {
    "net451": {
    }
  }
}
```
## Expected  behavior

Build properly
## Actual behavior

Error 
C:\work\SpeCore\Spe\Spe.Host\error CS2006 : Command-line syntax error : Missing '<text>' for '-d:' option
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

I put Conditional Compilation symbols "Spe_Host;" in visual studio, which worked properly in previous csproj, and it generated to "define": [ "Spe_Host", ""] in project.json file. I think it should be generated just ["Spe_Host"] or should be worked properly with ["Spe_Host", ""].

**Comment by piotrpMSFT** [comment]
This is a syntax concern in project.json. csproj has a different syntax for defining conditional compilation symbols so the issue doesn't apply moving forward.

**Comment by techcap** [comment]
I think it looks like a bug.

**Comment by piotrpMSFT** [comment]
I agree @techcap but since we're replacing PJ with csproj all up, we're not pursuing fixes for PJ [project.json]...

**Comment by techcap** [comment]
I think cli should work even in the case of empty string in define list.

**Comment by piotrpMSFT** [comment]
Try it out with preview3 bits. Are you seeing a similar issue?
