### ISSUE TITLE
Question: How to run dotnet.exe with different proccess name ?

### ISSUE THREAD

**Issue by ZOXEXIVO** [dotnet/cli#3792]
I have many .NET Core apps on one machine and i want to specify different name for process for monitoring CPU activity, e.t.c. 
I can rename each dotnet.exe to othername.exe, but i want to set it as options when execute it
Thank you

**Comment by blackdwarf** [comment]
@ZOXEXIVO at this point, we are not planning to enable this functionality. Will close this.
