### ISSUE TITLE
BUG, BUG, BUG (?). Azure Deploy From Source: Github -> error with Views on Areas.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#3795]
Original issue: https://github.com/aspnet/Home/issues/1639

When publising to an azure website using the azure portal / deploy from source:Github.

All files get in their corresponding folders **except** `Views` inside the `Areas` folder.

trying to hit an Area enpoint result in the following error:

```
An unhandled exception occurred while processing the request.

InvalidOperationException: The view 'Index' was not found. 
The following locations were searched:
/Areas/Admin/Views/Home/Index.cshtml
```

Looking at the filesystem i found the views are in folder: `C:\home\site\repository\src\****\Areas\Admin\Views\` but not in: `d:\home\site\wwwroot\Areas\Admin\Views`

so manually invoking this command fixes the problem:

```
xcopy C:\home\site\repository\src\****\Areas\Admin\Views\ 
           d:\home\site\wwwroot\Areas\Admin\Views /s
```

`project.json`:

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },
```

**Comment by iberodev** [comment]
if you include `**/*.cshtml` does it work?

**Comment by piotrpMSFT** [comment]
@Bartmax can you add a small repro so we can validate this is fixed in preview3?

**Comment by piotrpMSFT** [comment]
I built a small repro of this and experimented with globs in both PJ and csproj. In both cases, the Glob you want to use is `Areas/*/Views/**`. The trailing `**` will pull in the underlying files.
