### ISSUE TITLE
Explain use of ProjectContext to reflect over project

### ISSUE THREAD

**Issue by rposener** [dotnet/cli#3798]
## Steps to reproduce

```
        var context = ProjectContext.CreateContextForEachTarget(Directory.GetCurrentDirectory()).First();
        var libs = context.LibraryManager.GetLibraries();
        List<AssemblyName> assemblies = new List<AssemblyName>();
        foreach(var lib in libs)
        {
            Console.WriteLine($"Found {lib.Path} assembly");
            assemblies.Add(AssemblyLoadContext.GetAssemblyName(lib.Path));
        }
```
## Expected  behavior

This is in a custom CLI Command for my project.  I'm trying to use Assembly.Load() over the AssemblyNames to get list of classes in a certain namespace so we can write out typescript interfaces for them.  This is failing every which way.  Not sure how to properly reflect through the project.
## Actual behavior

Errors - not supported.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
ProjectContext is not continuing to evolve due to project.json -> csproj conversion.

**Comment by masaeedu** [comment]
@piotrpMSFT Is the entirety of `Microsoft.DotNet.ProjectModel` obsolete now that the project.json project system has been substituted with MSBuild? If so, what library should be used instead to load/examine MSBuild-based projects?
