### ISSUE TITLE
What compiler is csc.dll?

### ISSUE THREAD

**Issue by UnoSD** [dotnet/cli#3799]
I had a quick glance at the code to see what compiler was using and I notice it references this binary csc.dll

Are there source available for this? Is it a version of Roslyn bespoke for cross-platform compatibility?

If the source code is not public, will it be at some point?

**Comment by livarcocc** [comment]
It comes from this package: Microsoft.Net.Compilers.netcore.

Well, this package has an exe for it. We copy this exe into a dll.

The reference is pulled in from here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/compilers/project.json#L12

We do the copy here: https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/dotnet-cli-build/CompileTargets.cs#L213

And the code for it is here: https://github.com/dotnet/roslyn.

Hope this helps.

**Comment by UnoSD** [comment]
Thank you for the explanation.

I read here: https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/cross-platform.md
that Roslyn for Linux is WIP, does that mean that I shouldn't be relying for now on the output of the compilation? Is it a standard version of Roslyn?

Is the output a native binary for Linux? If not, I assume the JIT is the one I can find on GitHub.

Sorry for the many questions, I'm happy to split it into other issues if needed.

**Comment by livarcocc** [comment]
I think you ask these questions in the Roslyn repo that I posted above. You will get better and faster answers to these questions there.
