### ISSUE TITLE
Dependencies node in deps file for csproj based references is empty

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#3804]
## Steps to reproduce
- Create a project.json based project with `preserveCompilationContext: true`
- Create a csproj based ClassLibrary and add a reference to it in the xproj.
- Install NuGet packages in the csproj based project
- Build everything.
## Expected  behavior

`DependencyContext` for the xproj contains dependency information for csproj
## Actual behavior

The node for ClassLibrary doesn't include dependency information. All it has is a compile node. Consequently `Library.Dependencies` is empty

``` js
"ClassLibrary1/1.0.0": {
  "compile": {
    "bin/Debug/ClassLibrary1.dll": {}
  }
},
```

This affects discovery in Mvc which uses dependency information to determine if it should inspect an assembly for controllers.
## Environment data

`dotnet --info` output: `1.0.0-preview2-003121`

**Comment by pranavkm** [comment]
cc @pakrym

**Comment by piotrpMSFT** [comment]
Won't fix. References defined in an xproj are not honored.
