### ISSUE TITLE
Intellisense in project.json shows incorrect names for script parameters

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#3805]
Seems that project.json was not updated with regards to script parameters. As per https://github.com/aspnet/Home/issues/1648 intellisense still shows `%project:*%` but the names of the parameters changed. https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json#L377. 
Note that parameters for pre/post compile have different names than parameters for pre/post publish. Also postcompile has one more parameter compared to precompile (exitcode).

**Comment by piotrpMSFT** [comment]
You're right, but won't fix at this stage...
