### ISSUE TITLE
Uncomment E2E Tests for Dotnet Debian Package

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#381]
The debian package installation should be tested with End to end tests. 

This functionality is commented out because of https://github.com/dotnet/coreclr/issues/2215 

This issue prevents `dotnet restore` from running properly inside a docker container, which is where we do our package testing.

Before closing, the E2E test should be uncommented in `scripts/package/package-debian.sh`

**Comment by brthor** [comment]
@Sridhar-MS once we have NuGet in, do you know if we'll be able to do this?

**Comment by Sridhar-MS** [comment]
Yes, baring any issues that nuget has in docker.

**Comment by brthor** [comment]
Which are hopefully none :smile:
