### ISSUE TITLE
dotnet publish does not publish files within the wwwroot folder

### ISSUE THREAD

**Issue by jldelsocorro** [dotnet/cli#3810]
## Steps to reproduce
1. Run ng build command in the front end code folder , it will put files in wwwroot folder
2. Run dotnet publish command in the project
3. Everything in wwwroot will be removed except the .npmignore
## Expected  behavior

We expected that if we run the dotnet publish command it will just publish everything including the files within the wwwroot folder
## Actual behavior

Running the dotnet publish removed files that ng build put in the wwwroot folder.
## Environment data

`dotnet --info` output: 
.Net Command Line Tools 1.0.0-preview1-002702

Product Information:
Version: 1.0.0-preview-002702
Commit Sha: 6cde21225e

Runtime Environment:
OS Name: Windows
OS Version: 6.1.7601
Os Platform: Windows
RID: win7-x64

**Comment by dankellett** [comment]
This might be related to an issue I just created [here](https://github.com/dotnet/cli/issues/3833).

You may need to specify to include that directory (in my case, in project.json). If you are using a relative path as your output folder, it still will not copy the directory. If you use a full path, it should copy.

**Comment by piotrpMSFT** [comment]
Yep, @dankellett. Content files need to be specified in project file.
