### ISSUE TITLE
Change "Common commands" in the "--help" screen in dotnet

### ISSUE THREAD

**Issue by hickford** [dotnet/cli#3814]
`dotnet --help` lists seven "common commands." Are there any others? What are they?

	>dotnet --help
	.NET Command Line Tools (1.0.0-preview2-003121)
	Usage: dotnet [host-options] [command] [arguments] [common-options]

	Common Commands:
	  new           Initialize a basic .NET project
	  restore       Restore dependencies specified in the .NET project
	  build         Builds a .NET project
	  publish       Publishes a .NET project for deployment (including the runtime)
	  run           Compiles and immediately executes a .NET project
	  test          Runs unit tests using the test runner specified in the project
	  pack          Creates a NuGet package

I tried `dotnet help commands` but got an error:

> No executable found matching command "dotnet-commands"

**Comment by hickford** [comment]
Git you can use `git help commands` or `git help -a` to list all commands

> 'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept

**Comment by tverboon** [comment]
You can do `dotnet new --help`. It works for all `dotnet [command] --help`.

**Comment by blackdwarf** [comment]
@hickford as @tverboon correctly noted above, you can use the `dotnet [command] --help` to get specific help for each given command. I'll have to admit, I'm not entirely sure I understand this issue.

**Comment by svick** [comment]
@blackdwarf I think the question is: "How do I get the list of all possible commands?" Not sure if that list is supposed to contain commands from tools or not.

As far as I can tell, all the user-facing built-in commands are listed in `dotnet help`, so maybe changing "Common Commands:" to just "Commands:" or perhaps "Built-in Commands:" would help alleviate the confusion.

**Comment by blackdwarf** [comment]
@svick having a listing of the tools would be interesting, but that means that the display would change based on where you are. Could be confusing, could be useful.

As for the wording, I agree, so will fix it.

**Comment by johnciliberti** [comment]
Some more detail on options would be helpful. For example if I do:
dotnet new --help
.NET Initializer

Usage: dotnet new [options]

Options:
  -h|--help             Show help information
  -l|--lang <LANGUAGE>  Language of project [C#|F#]
  -t|--type <TYPE>      Type of project

It would be better if it said

Usage: dotnet new [options]

Options:
  -h|--help             Show help information
  -l|--lang <LANGUAGE>  Language of project [C#|F#]
  -t|--type [Console | Web | Lib | xunittest  ]      Type of project

This information is available if you enter an incorrect value for the template name but it is somewhat counter intuitive to have to trigger an error to see what the options are

**Comment by svick** [comment]
@johnciliberti I agree, which is why I have already fixed that (https://github.com/dotnet/cli/pull/3644). :smile: But that change didn't make it into preview 2, which is why you're still seeing the old version.

And `dotnet new` is also going to be "reimagined" (https://github.com/dotnet/cli/issues/2052), so that help text is likely going to look differently in the next release.
