### ISSUE TITLE
Build dotnet on FreeBSD

### ISSUE THREAD

**Issue by josteink** [dotnet/cli#3815]
Currently dotnet is a required component to build the managed components of CoreFX.

There is however no FreeBSD-version available for download. Could this be built? Where do we need to start to make this happen?

This issue is partially related to https://github.com/dotnet/coreclr/issues/6115.

**Comment by blackdwarf** [comment]
@josteink for clarification, are you talking about the native host ("muxer", the "dotnet" binary) or the entire CLI suite?

**Comment by josteink** [comment]
Obviously the ultimate goal would be "everything" working out of the box on FreeBSD, but obviously we'll have to start somewhere smaller.

As the issue states: Right now corefx cannot be built on FreeBSD, because unlike other supported platforms there is no dotnet sdk blob available for download. 

This breaks the build and this issue is about lack of such blob.

If getting such a blob built and published requires other intermediate steps, I'm fully open to discussing them, but this issue was meant to provide a high level discussion of how we get there.

For now I've fixed one runtime error in corehost in core-setup, but with coreclr's now rather complex self bootstrapping process, it's hard to tell if/what more needs to be done.

Dotnet CLI being the dependency causing issues, I figured it made sense raising the issue here. Was that a mistake?

**Comment by josteink** [comment]
Cc: @stephtoub @janvorli @ellismg

**Comment by erick2red** [comment]
This situation is the same for every distribution not having binaries prebuilt.
The instructions shown in each of the projects assume those binaries are built, which isn't the case for new platform. There should be a more detailed explanation on how to build the SDK as a whole, so people can contribute and add more distributions to it by themselves, contributing the necessary patches.

**Comment by josteink** [comment]
> There should be a more detailed explanation on how to build the SDK as a whole, so people can contribute and add more distributions to it by themselves, contributing the necessary patches.

As someone who was previously able to port coreclr to a new platform without much guidance, and now feeling completely lost, I very much agree with this.

Is anyone working on this? Is this in a backlog somewhere?

**Comment by josteink** [comment]
The following issue is very similar to this one, and has some more technical details: https://github.com/dotnet/corefx/issues/10610

**Comment by piotrpMSFT** [comment]
Let's track on corefx. That repo defines the platform matrix for CLI.
