### ISSUE TITLE
dotnet build gives NU1007 error, then fails

### ISSUE THREAD

**Issue by colin-young** [dotnet/cli#3817]
I have a project that uses `.csproj` and `project.json`. I have dependencies on `System.Runtime.Numerics 4.0.1` and `System.ComponentModel.Annotations 4.1.0`. When I run `dotnet build` I get the following warnings:

```
warning NU1007: Dependency specified was System.ComponentModel.Annotations >= 4.1.0 but ended up with System.ComponentModel.Annotations 4.0.10.0
warning NU1007: Dependency specified was System.Runtime.Numerics >= 4.0.1 but ended up with System.Runtime.Numerics 4.0.0.0
```

And then a bunch of compilation errors related to types from those packages.

I have many other solutions that are using the same csproj/project.json combo that build and package just fine. It wasn't until I tried to add those dependencies to this solution that I ran into trouble.

`project.lock.json` shows the correct versions being referenced, and Visual Studio can build the solution without error. The problem is I'd like to use `dotnet pack` to create my NuGet packages, and that's the point at which it needs to do the build.

Is there some way to force the correct version to be used?

UPDATE: It appears that I needed to update my frameworks like this:

```
"frameworks": {
    "net4.5.2": {
      "frameworkAssemblies": {
        "System.Numerics": "4.0.0.0",
        "System.ComponentModel.DataAnnotations": "4.0.0.0"
      }
    },
    "net4.6": {
      "frameworkAssemblies": {
        "System.Numerics": "4.0.0.0",
        "System.ComponentModel.DataAnnotations": "4.0.0.0"
      }
    }
},
```

It's a bit redundant, in that I need to both add the reference in VS and manually update project.json if I want both VS and CLI to be able to successfully build. Is that the case, or is there a way to have a single definition and have both systems work?
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by stajs** [comment]
The question I have, is why are the framework assemblies overshadowing the explicit dependencies?

**Comment by piotrpMSFT** [comment]
Glad this got resolved :)
