### ISSUE TITLE
DotNet works outside of Visual Studio but not within : Error: project is configured to use .NET Core SDK version 1.0.0-preview2-003121 which is not installed or cannot be found.

### ISSUE THREAD

**Issue by CarlosOnline** [dotnet/cli#3820]
## Steps to reproduce
DotNet installed and works outside of Visual Studio, but not within

**Outside of Visual Studio following commands work**
```
dotnet build
dotnet restore
dotnet run

```
- Installed latest version of .NET Core SDK

- Installed aurelia solution from https://github.com/aurelia/skeleton-navigation/releases/tag/1.0.0-beta.3.0.0

**global.json**
```
{
  "projects": [ "src", "test" ],
    "sdk": {
        "version": "1.0.0-preview2-003121"
    }
}

```
- Open solution.
Visual Studio displays error:  

## Expected  behavior
Solution loads

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/3691895/16708833/cdd85766-45b4-11e6-9b73-8c20cc2fbc39.png)

> project is configured to use .NET Core SDK version 1.0.0-preview2-003121 which is not installed or cannot be found. These components are required to build and run this project. Download the version of .NET Core SDK specified in global.json or update the SDK version in global.json to the version that is installed.	

## Environment data
`dotnet --info` output:

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Visual Studio Version Info**

```
Microsoft Visual Studio Community 2015
Version 14.0.25421.03 Update 3
Microsoft .NET Framework
Version 4.6.01055

Microsoft .NET Core Tools (Preview 2)   14.1.20624.0
Microsoft .NET Core Tools (Preview 2)

```

**Comment by CarlosOnline** [comment]
Found solution:
https://github.com/aspnet/Tooling/blob/master/known-issues.md#missing-sdk

**Comment by fletchsod-developer** [comment]
FYI - The link is now broken

**Comment by blackdwarf** [comment]
@mlorbetske do you happen to know what happened to this file?

**Comment by blackdwarf** [comment]
Actually, scratch that, I believe this is the doc that is needed: https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md#missing-sdk.

**Comment by manishsingh2061** [comment]
this link helped  me to find solution
[http://simplyaspnet.blogspot.in/2017/05/problem-if-you-open-orcreate.html](http://simplyaspnet.blogspot.in/2017/05/problem-if-you-open-orcreate.html)
