### ISSUE TITLE
Is packOptions > repository not working right now? Is this a DNF?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#3823]
@ajaybhargavb
## Steps to reproduce

Create a NuGet package and specify a repository in `project.json > packOptions > repository` ...

``` json
"packOptions": {
    "repository": {
        "type": "git",
        "url": "https://github.com/GuardRex/GuardRex.StyleScriptInliningTagHelper"
    }
},
```
## Expected  behavior

The Url will get into the `nupkg` file and thus be reflected after the file is uploaded at NuGet.org.
## Actual behavior

The `Project Url` entry is blank when the `nupkg` file is uploaded at NuGet.org.

![capture2](https://cloud.githubusercontent.com/assets/1622880/16715384/d9442428-46a3-11e6-829c-50d2a36d5344.PNG)

This might be a DNF due to the move to MSBuild/`csproj`, if so, that's understandable.
## Environment data

```
.NET Command Line Tools (1.0.0-preview3-003171)

Product Information:
 Version:            1.0.0-preview3-003171
 Commit SHA-1 hash:  da57475105

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by svick** [comment]
If you want to specify project URL, I think you should use `"packOptions"` -> [`"projectUrl"`](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#projecturl).

**Comment by piotrpMSFT** [comment]
Yes, DNF. Yes, packOptions :)
