### ISSUE TITLE
dotnet publish should only copy changed files to publish directory

### ISSUE THREAD

**Issue by mitchcapper** [dotnet/cli#3824]
## Steps to reproduce

run dotnet publish
## Expected  behavior

Only files that are changed are copied to the published directory
## Actual behavior

all files are recopied
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14372
 OS Platform: Windows
 RID:         win10-x64

Right now all files are copied. A simple timestamp check comparison of the file and its destination should be better.  Saves IO and makes it easier for apps tracking file changes if the tool is not overriding files with the exact same copy of the file.

Open to feedback otherwise may try to make a PR for it.

**Comment by piotrpMSFT** [comment]
Can you try this with preview3? If still an issue, please open in https://github.com/dotnet/sdk. Thanks!
