### ISSUE TITLE
app without entry point - dotnet run crashes

### ISSUE THREAD

**Issue by lw-schick** [dotnet/cli#3825]
## Steps to reproduce

```
git clone https://github.com/lw-schick/xunit-dotnetcore-sample
dotnet run
```
## Expected  behavior

the compiler sais that this project has no entry point.
## Actual behavior

the dotnet cli crashes
## Environment data

```
> dotnet --info
.NET Command Line Tool (1.0.0-preview3-003180)

Product Information:
  Version: 1.0.0-preview3-003180
  Command SH1 hash: d4193cd5c1

Runtime Environment:
  OS Name: Windows
  OS Version: 6.1.7601
  OS Platform: Windows
  RID: win7-x64

> _
```

![image](https://cloud.githubusercontent.com/assets/19262181/16720816/31a29ff0-473a-11e6-98ba-c5603404e9eb.png)
(sorry, system language is german...)
## 

it is obvious that i made a mistake: the programming code has no entry point. In my view, the cli tool should give a meaningful error and not just crash...

**Comment by shanselman** [comment]
Ya, this is silly. I just hit this with a test. I had a `yo aspnet` generated xunit test, did a `dotnet run` rather than `dotnet test`. I should NOT get a Watson. @blackdwarf

**Comment by blackdwarf** [comment]
Yeah, it should tell that there is no entry point and fail, not crash. 

/cc @piotrpMSFT @eerhardt

**Comment by blackdwarf** [comment]
#2098 has more information.

**Comment by livarcocc** [comment]
This is what you get in MSBuild world:

```
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [/Users/livarcocc/Documents/git/temp/another/another.csproj]

The build failed. Please fix the build errors and run again.
```
