### ISSUE TITLE
dotnet publish does not include wwwroot folder if it does not exist before the process starts

### ISSUE THREAD

**Issue by chris5287** [dotnet/cli#3828]
## Steps to reproduce

`dotnet publish`
## Expected  behavior

A package is created that includes the `wwwroot` contents.
## Actual behavior

As the `wwwroot` is created as part of the `prepublish` script, the process seems to skip over this folder completely. If I create the `wwwroot` folder on the filesystem with no files in it, then run `dotnet publish`, it does publish the folder. This is a problem for our CI systems.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by mcliment** [comment]
As a temporary workaround I've created an empty `_placeholder_.txt` file into `wwwroot` to be able to commit the folder into git and then added this to `project.json` `publishOptions`:

    "exclude": [
        "wwwroot/_placeholder_.txt"
    ],

**Comment by GuardRex** [comment]
This is going to get fixed as part of the move to MSBuild. See: https://github.com/dotnet/cli/issues/1396#issuecomment-235767226

**Comment by piotrpMSFT** [comment]
@chris5287 can you attach a small repro so we can validate this is fixed?

**Comment by piotrpMSFT** [comment]
Since we dont' have a repro, I'm closing this out. If it still repros on preview3+, please open a new issue.
