### ISSUE TITLE
InternalAbstractions and DependencyModel lack Copyright assembly attribute

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#3829]
## Steps to reproduce

Look at properties for `Microsoft.DotNet.InternalAbstractions.dll` and `Microsoft.Extensions.DependencyModel.dll` (1.0.0).
## Expected  behavior

Properties are like these (`System.Collections.dll` shown):

```
Product name = Microsoft® .NET Framework
Product version = 1.0.24212.01. Commit Hash: 9688ddbb62c04189cac4c4a06e31e93377dccd41
Copyright = © Microsoft Corporation.  All rights reserved.
```
## Actual behavior

Properties are these (`Microsoft.DotNet.InternalAbstractions.dll` shown):

```
Product name =
Product version = 1.0.0
Copyright =
```

(In CoreFX, the attributes that provide this data are [generated by Buildtools](https://github.com/dotnet/buildtools/blob/197567b/src/Microsoft.DotNet.Build.Tasks/PackageFiles/versioning.targets#L57).)

**Comment by dagood** [comment]
@eerhardt Ping, to make sure this gets seen. I'm not sure if the buildtools generation can be reused because it's packed up with versioning stuff, but maybe these attributes could at least be centralized in CLI.

**Comment by piotrpMSFT** [comment]
Moved to core-setup
