### ISSUE TITLE
dotnet-build should compile concurrently

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#383]
Having concurrent compilation would address some of the performance concerns in #115 .
This feature depends on the ability to detect when it's not safe to run (#382).

**Comment by piotrpMSFT** [comment]
Concurrent compilation seems like a build orchestrator concern. We're not setting out to make dotnet itself an orchestrator. We should play nicely in environments where that capability is available, however.

**Comment by NikolaiTillmann** [comment]
One could argue that (time-stamp based) incrementality is also a build orchestrator concern. Both incrementality and concurrency deliver huge performance gains and can be implemented rather cheaply --- but only if certain safety guarantees are in place. There seems to be consensus that we want incrementality for dotnet, so I don't see the big deal with some form of concurrency either.

**Comment by piotrpMSFT** [comment]
I think the immediate goal with incremental build is essentially to fail-fast. e.g. dumbly compile everything, but have some of those compiles be no-ops.

We want to opt in to true concurrency/incrementality where possible but it's not something we can mandate for all components. Once folks see the value, they'll jump on board.

**Comment by NikolaiTillmann** [comment]
Agreed on that we can't mandate it for everything. Both incrementality and concurrency only work safely when certain conditions are met. Hence #382. If conditions are not met, no incrementality or concurrency.
