### ISSUE TITLE
System.Net.Http is missing in net461 outputs

### ISSUE THREAD

**Issue by sherlock1982** [dotnet/cli#3830]
I've got a library ClassLibrary1 which references and uses System.Net.Http:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "System.Net.Http": "4.1.0"
  },

  "frameworks": {
    "netstandard1.3": {
      "imports": "dnxcore50"
    }
  }
}
```

I've got a net461 project which references and uses this library:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "ClassLibrary1": "1.0.0"
  },

  "frameworks": {
    "net461": {
    }
  },

  "runtimes": {
    "win7-x64"  : {}
  }
}

```

In the outputs of "dotnet build" or "dotnet publish" I expect to see System.Net.Http 4.1.0 with all it's dependencies.
While actually I see all it's dependences without System.Net.Http itself and application emits an error.

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

Not an issue if using the same structure with .csproj style projects.

**Comment by piotrpMSFT** [comment]
@sherlock1982 glad this isn't an issue with csproj projects. Since CLI is now moved over to MSBuild/csproj, the project.json repro is not something we are going to address. I'm therefore closing this issue. If you see problems with the current CLI [RC3, available from the home page of this repo] please let us know!
