### ISSUE TITLE
Add support for producing NuGet packages with 'contentFiles' section in nuspec

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#3831]
This is primarily for consideration during the MSBuild migration, but I wanted to make sure it was tracked. Right now, we have support for consuming the various types of `buildAction` in a NuGet [`contentFiles` section](https://docs.nuget.org/create/nuspec-reference#contentfiles-with-visual-studio-2015-update-1-and-later) but no way to produce it. The main customer scenario here is producing a shared-sources package (i.e. a package containing source code designed to be embedded the consumer's project) which also provides resources. The `resx` files in the package need to be marked with a `buildAction` of `EmbeddedResource`

/cc @dougbu

**Comment by piotrpMSFT** [comment]
`dotnet nuget` with the nuspec will do the trick :)
