### ISSUE TITLE
xunit traits do not show up for .NET Core tests in Visual Studio

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/cli#3832]
## Steps to reproduce

Set up a test like the following:

``` csharp
using Xunit;

namespace ClassLibrary1
{
    public class TestClass
    {
        [Fact]
        [Trait("trait", "value")]
        public void Test()
        {

        }
    }
}
```
## Expected  behavior

After compilation, VS Test Explorer should show 'trait [value]' when filtered by traits. This works for normal console libraries, but not .NET Core libraries
## Actual behavior

The VS Test Explorer shows 'No Traits' after compilation
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

This was originally posted on xunit/xunit#889 and also on dotnet/core#134 but it appears to be a CLI issue so adding an issue here for visibility.

**Comment by conniey** [comment]
@blackdwarf Do you know who to bubble this up to? None of the traits/categories (for xUnit or NUnit) show up in the Visual Studio Test Runner and there are many issues related to this.

**Comment by piotrpMSFT** [comment]
yep, the VS integration for the PJ test runner is tracked in `aspnet/tooling`. Can you open there?

**Comment by raffaeu** [comment]
Guys this is still not working 😢 
Is there any way to get it done or now that `dotnet test xunit` is dead I just have to wait?

**Comment by piotrpMSFT** [comment]
@raffaeu can you open a new issue? This bug was opened against a very old [project.json-based] CLI and against VS 2015. If you're still seeing a problem it'd be great to get new details [versions, etc.]

Both Command Line and IDE test execution are handled in the https://github.com/microsoft/vstest repo. That's the best place to open the issue to make sure the right folks are looking at it!

**Comment by raffaeu** [comment]
Hi @piotrpMSFT at this point we are waiting for March and VS2017 and the new VSTS coming out, then we will upgrade our solutions and see what's next. It doesn't make sense to invest more time into dotnet test xunit because it has been declared "obsolete" in VS 2017
Thanks
