### ISSUE TITLE
dotnet publish with relative path not respecting PublishOptions Include

### ISSUE THREAD

**Issue by dankellett** [dotnet/cli#3833]
## Steps to reproduce

In an asp.net project add directories into the PublishOptions Include setting in the project.json.
e.g.
`
"publishOptions": {
    "include": [
      "wwwroot",
      "app",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },
`

Then publish using donet CLI.
e.g.
`dotnet publish --framework net46 --output "..\..\..\someRelativeDir" --configuration Debug`
## Expected  behavior

The includes folders are copied across to the publish directory.
The expected output is the same as running the command with a full path.
e.g.
`dotnet publish --framework net46 --output "c:\temp\myFullPathDir" --configuration Debug`
## Actual behavior

The directories specified in the publishOptions includes are not copied.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by dankellett** [comment]
After a little digging, this is what I have found:

It looks like like the IncludesFileResolver currently expects to receive a fully qualified path as a target path. It specifically is checking for this on[ line 45 of Microsoft.DotNet.ProjectModel.Files.IncludesFileResolver](https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/Microsoft.DotNet.ProjectModel/Files/IncludeFilesResolver.cs#L43). It looks like PublishProjectContext calling this without resolving the to a full path on line [187 of Microsoft.DotNet.Tools.Publish.PublishCommand](https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L187).

https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/Microsoft.DotNet.ProjectModel/Files/IncludeFilesResolver.cs

https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/dotnet/commands/dotnet-publish/PublishCommand.cs

**Comment by swernli** [comment]
I am hitting this issue as well... the include files only show up if I use a full path when calling dotnet publish.  However, I didn't start seeing the issue until a recent selfhost build upgrade.  Are you using preview builds of Windows by any chance?

**Comment by dankellett** [comment]
No, this is on a machine running Server 2012 R2.

**Comment by swernli** [comment]
Ah, well in that case it isn't likely to be an operating system issue. Thanks for reporting this; knowing it was an issue of full path vs relative path helped me fix our build scripts!

**Comment by dankellett** [comment]
No problem, glad it helped. We did the same with our build scripts. The side affect being that the build must be run from a specific location because the msbuild context will resolve to full paths from this location.

**Comment by jaredcnance** [comment]
Is there any plan to fix this?

**Comment by piotrpMSFT** [comment]
Yep, MSBuild has a much stronger globbing functionality. I'm unable to repro this in preview3. Please re-open if you still see this.

**Comment by dougloyo** [comment]
I am still having the same issue. 
#Relative Path does not work.
dotnet publish --configuration Release --output ..\published-app
#Full path works...
dotnet publish --configuration Release --output D:\projects\x\published-app

**Seems like this should be fixed**

I just installed .net Core like a week a go:
.NET Command Line Tools (1.0.0-preview2-003131)
Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by adlordy** [comment]
I have another reproduction scenario.

This does not work (wwwroot is not included):
`dotnet publish -c Release -o .\.out`
But this works:
`dotnet publish -c Release -o .out`
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by benscobie** [comment]
I am facing a similar issue on Debian 8.
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

When using the following from within the project directory:
`dotnet publish -c "Release" --output ../../staging/published-website --no-build`

I get the following output:
![image](https://cloud.githubusercontent.com/assets/944312/21743011/daf48b28-d4f1-11e6-9340-0e7f057f2a23.png)

When using the following:
`dotnet publish -c "Release" --output published-app --no-build`

I am getting the correct output:
![image](https://cloud.githubusercontent.com/assets/944312/21742987/8d3b95ca-d4f1-11e6-8083-7163e8ad2663.png)

I was originally passing a relative project path to dotnet publish but I ran into this: https://github.com/dotnet/cli/issues/3528
