### ISSUE TITLE
XML documentation isn't generated

### ISSUE THREAD

**Issue by bradygaster** [dotnet/cli#3834]
## Steps to reproduce
1. Create a .NET project, and add /// comments throughout the code on any public member. 
2. (If in VS) go to the project properties and check the XML Documentation File box.
3. (If building from command line) run dotnet build in the root of the project tree
4. Note that the XML documentation file isn't generated

## Expected  behavior
Step 4 from above would generate the XML documentation file

## Actual behavior
No documentation file exists

## Environment data
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
I am not sure what VS is doing for that, but in a project.json, if you specify 

```
"buildOptions": {
    "xmlDoc": true
}
```

The xml file is generated correctly. Also, if you set 

```
<GenerateDocumentationFile>true</GenerateDocumentationFile>
<DocumentationFile>$(OutputPath)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
```

in your csproj, we will also generate the xml file.
