### ISSUE TITLE
Embedded files with spaces in their paths cause compilation to fail

### ISSUE THREAD

**Issue by tuespetre** [dotnet/cli#3843]
Sort of related to #3221
## Steps to reproduce

Run the following in PowerShell:

```
mkdir C:\temp-project
cd C:\temp-project
dotnet new
dotnet restore
"Hello" | Out-File "test - file.txt"
@"
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true,
    "embed": {
      "include": "*.txt"
    }
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
"@ | Out-File project.json
dotnet build
```
## Expected  behavior

Successful compilation
## Actual behavior

```
Project temp-project (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling temp-project for .NETCoreApp,Version=v1.0
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\temp-project\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
C:\temp-project\error CS2007: Unrecognized option: '-'

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.9420002
```

Running the same experiment using a file name with spaces but no hyphens (or rather, no hyphens that are immediately following a space) yields different errors, but that's it's the same root problem.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by ToddThomson** [comment]
I ran into this issue today. I copied and pasted a view in my embedded views, so I had a filename like:
```filename - Copy.cshtml```
 The spaces around the dash needed to be removed before the project could be built successfully again.

**Comment by blackdwarf** [comment]
I have just validated that this issue is resolved with Preview 4, that is, with MSBuild-based tooling. With this, I will close this issue as "MSBuild mitigated". If you believe this was in error or you see this problem crop up again, please reopen. Thanks!
