### ISSUE TITLE
Use apphost.exe for app-base application activations

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#3850]
## Steps to reproduce

```
dotnet new
# Edit project manifest to be standalone
dotnet build
dotnet publish
```
## Expected  behavior
1. The executable should instead instead be apphost.exe
2. Replace the below string bytes in apphost.exe to `"appname.dll\0"`, (this can be done in managed code as well)

`c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2`

Sample code that replaces the string is present in this commit: dotnet/core-setup@b391644

## Actual behavior

The binary executable is dotnet.exe host.
## Environment data

`dotnet --info` output:

**Comment by gkhanna79** [comment]
@ramarag Is this resolved with your recent feature work?

CC @eerhardt

**Comment by ramarag** [comment]
fixed by https://github.com/dotnet/cli/pull/6085
