### ISSUE TITLE
Can't use dotnet ef command

### ISSUE THREAD

**Issue by ArturKarbone** [dotnet/cli#3860]
## Steps to reproduce

I'm trying to add EF tooling to run migrations, So I bascially add the following section to my project.json

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"   
  },

## Actual behavior

dotnet restore/dotne build commands work just fine, however I keep getting the following error running **dotnet ef**

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Utils.Reporter' threw an exception. ---> System.TypeLoadException: Could not load type 'System.ConsoleColor' from assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.DotNet.Cli.Utils.Reporter..ctor
   at Microsoft.DotNet.Cli.Utils.Reporter..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Cli.Utils.Reporter.get_Error()
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

When i look at mentioned System.Console via reflection tool i see that indeed there is no System.ConsoleColor for some reason

![system console 2016-07-14 12_50_03-ilspy](https://cloud.githubusercontent.com/assets/3705063/16835485/9281ad82-49c1-11e6-8d2b-ba14120bdf46.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by ArturKarbone** [comment]
**Update**:

 I was able to get rid of thet issue  by  running:

-  "nuget.exe locals -clear all"
- dotnet restore
- dotnet ef

I tried the same command yesterday too, but this didn't work out for me. Today I ran the command when Visual studio was closed (maybe just a coincidence but it worked out today).

**Comment by blackdwarf** [comment]
@ArturKarbone does your last comment indicate that this issue can be closed as non-repro anymore?
