### ISSUE TITLE
Error on docker, error if building from source on Ubuntu 16.06

### ISSUE THREAD

**Issue by dstpierre** [dotnet/cli#3861]
## Steps to reproduce
```
docker run ubuntu:16.04
apt-get install git
git clone https://github.com/dotnet/cli.git
apt-get install clang
./build.sh
```

## Expected  behavior
I expected it to build I guess, just trying to get started, and the docker image does not work as well, so I was told to build the cli, yet I cannot seems to succeed at that either.

## Actual behavior
```
...
dotnet-install: Adding to current process PATH: /dl/cli/.dotnet_stage0/Linux. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
Restoring Build Script projects...
log  : Restoring packages for /dl/cli/build_projects/shared-build-targets-utils/project.json...
log  : Restoring packages for /dl/cli/build_projects/Microsoft.DotNet.Cli.Build.Framework/project.json...
log  : Restoring packages for /dl/cli/build_projects/update-dependencies/project.json...
log  : Restoring packages for /dl/cli/build_projects/dotnet-cli-build/project.json...
/dl/cli/build_projects/dotnet-cli-build/build.sh: line 116:  4908 Segmentation fault      (core dumped) dotnet restore

```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
`

Tried to follow the docker simple instructions, I was getting a Segmentation fault as well using the microsoft/dotnet:latest image. What / how can one get started with dotnet on Linux? Should we use the `microsoft/dotnet:1.0.0-preview1` image?

I guess it's not clear, because from this page: https://www.microsoft.com/net/core#docker and that one https://www.microsoft.com/net/core#ubuntu and also trying to build source, I'm getting this `Segmentation error`. How are people using dotnet at all?

Thanks for any clarification / pointer on how. We have a huge time the Go package for Azure SQL, and we are now investigating porting this data access to C#, but geez, not able to get started atm.

**Comment by eerhardt** [comment]
@dstpierre - what Kernel version are you running?  I've seen the same error here:  https://github.com/dotnet/cli/issues/3681.  Are you hitting the same issue?  If so, this has been fixed in builds later than preview2.

**Comment by blackdwarf** [comment]
@dstpierre any update on this?
