### ISSUE TITLE
`dotnet restore` should pass all args straight through to NuGet without changing the args at all

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3862]
The `dotnet restore` command tries to change the "default verbosity" if one isn't set:

https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore/NuGet3.cs#L15-L20

This is wrong.  The CLI code shouldn't be modifying the args list at all.  It should be passing exactly the arguments that the user typed through to NuGet.

We will need the fix for https://github.com/NuGet/Home/issues/3129 before we can remove the code in the CLI, or else we will be regressing the fix made in https://github.com/dotnet/cli/pull/3229.

**Comment by jasonwilliams200OK** [comment]
+1 for transparently pass-through user args to sub process and fix the issue where it belongs. :)

**Comment by piotrpMSFT** [comment]
`dotnet nuget` in preview3 is a transparent passthrough.
