### ISSUE TITLE
Failed to resolve library symbol hostfxr_main on Centos

### ISSUE THREAD

**Issue by ethernet802** [dotnet/cli#3866]
## Steps to reproduce
Followed instructions on https://www.microsoft.com/net/core#centos to install "Install .NET Core SDK" on a fresh copy of centos 7.2 (CentOS-7-x86_64-Minimal-1511.iso)

sudo yum install libunwind libicu
curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=809131
sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin

The dotnet packages I tried:
dotnet-dev-centos-x64.1.0.0-preview2-003121.tar.gz
and
dotnet-dev-centos-x64.1.0.0-preview3-003180.tar.gz

## Expected  behavior
`dotnet --info` 

expected to see version info etc.

## Actual behavior
`dotnet --info` output:
Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main
Segmentation fault

## Environment data
`dotnet --info` output: 
Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main
Segmentation fault

**Comment by ethernet802** [comment]
must have made a mistake, trashed the machine and redid the install and is working as expected.

**Comment by jskeet** [comment]
I'm seeing this behaviour consistently on travis now though... I wonder if some apt packages are messed up somewhere.
