### ISSUE TITLE
dotnet restore fails to access nuget.config when run concurrently

### ISSUE THREAD

**Issue by noahfalk** [dotnet/cli#3868]
## Steps to reproduce

Run dotnet restore on multiple projects concurrently. This may take a fair amount of stress and appears to be a race condition. My scenario invokes dotnet restore on roughly ~100 separate projects and probably achieves about 8 concurrent executions. Occasionally a few projects fail.

## Expected  behavior

dotnet restore completes succesfully

## Actual behavior

This is output from a custom tool, but you can clearly see command used to launch dotnet and the error output it produced.

    Running Process: /tmp/TestRun_2016_07_15_01_47_33_4614/dotnet/dotnet-ubuntu-x64.1.0.0.001504/bin/dotnet restore --configfile /mnt/j/workspace/Private/dotnet_debuggertests/master/ubuntu_dbg_x64_tst_prtest/bin/Linux.x64.Debug/Debuggees/dotnet.1.0.0.001504/dbgbreakthreads/NuGet.config --packages "/tmp/TestRun_2016_07_15_01_47_33_4614/packages"
    Working Directory: /mnt/j/workspace/Private/dotnet_debuggertests/master/ubuntu_dbg_x64_tst_prtest/bin/Linux.x64.Debug/Debuggees/dotnet.1.0.0.001504/dbgbreakthreads
    {
        STDERROR: 00:00.349: Unhandled Exception: System.TypeInitializationException: The type initializer for 'NuGet.CommandLine.XPlat.Program' threw an exception. ---> System.IO.IOException: The process cannot access the file '/home/dotnet-bot/.nuget/NuGet/NuGet.Config' because it is being used by another process.
        STDERROR: 00:00.350:    at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
        STDERROR: 00:00.350:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
        STDERROR: 00:00.350:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
        STDERROR: 00:00.350:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
        STDERROR: 00:00.350:    at NuGet.Configuration.FileSystemUtility.AddFile(String fullPath, Action`1 writeToStream)
        STDERROR: 00:00.350:    at NuGet.Configuration.XmlUtility.CreateDocument(XDocument content, String fullPath)
        STDERROR: 00:00.350:    at NuGet.Configuration.Settings.<>c__DisplayClass15_0.<.ctor>b__0()
        STDERROR: 00:00.350:    at NuGet.Configuration.Settings.ExecuteSynchronized(Action ioOperation)
        STDERROR: 00:00.350:    at NuGet.Configuration.Settings..ctor(String root, String fileName, Boolean isMachineWideSettings)
        STDERROR: 00:00.350:    at NuGet.Configuration.Settings.ReadSettings(String root, String settingsPath, Boolean isMachineWideSettings)
        STDERROR: 00:00.350:    at NuGet.Configuration.Settings.LoadUserSpecificSettings(List`1 validSettingFiles, String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean useTestingGlobalPath)
        STDERROR: 00:00.350:    at NuGet.Configuration.Settings.LoadDefaultSettings(String root, String configFileName, IMachineWideSettings machineWideSettings, Boolean loadAppDataSettings, Boolean useTestingGlobalPath)
        STDERROR: 00:00.350:    at NuGet.CommandLine.XPlat.Program..cctor()
        STDERROR: 00:00.350:    --- End of inner exception stack trace ---
        STDERROR: 00:00.350:    at NuGet.CommandLine.XPlat.Program.EnsureLog(LogLevel logLevel)
        STDERROR: 00:00.350:    at NuGet.CommandLine.XPlat.Program.Main(String[] args)
    }
    Exit code: 134 ( 00:01.045 elapsed)

## Environment data
`dotnet --info` output:

I don't have a Linux VM onhand, but it should be this version on Linux instead of Windows.

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@rrelyea is this something that should be on Nuget/Home?

**Comment by piotrpMSFT** [comment]
moved to nuget/home
