### ISSUE TITLE
The assemblies generated are wrong when we rename the project directory

### ISSUE THREAD

**Issue by J0rgeSerran0** [dotnet/cli#3870]
## Steps to reproduce
STEP 1

I create a new console project with Visual Studio 2015 and .NET Framework
"FooSample"
I compile the project and the assemblies and the compiler generates a "FooSample.dll"

I create the same console project with Visual Studio 2015 and .NET Core
"FooSample"
I compile the project and the assemblies and the compiler generates a "FooSample.dll"

STEP 2

I rename the directory of the console project of .NET Framework to 01.FooSample
"01.FooSample" (the directory only!)
I compile the project and the assemblies and the compiler generates a "FooSample.dll"

I rename the directory of the console project of .NET Core to 01.FooSample
"01.FooSample" (the directory only!)
I compile the project and the assemblies and the compiler generates a "01.FooSample.dll"

## Expected  behavior
When I rename a directory, the assemblies generated should be the same that the namespace.

## Actual behavior
The assemblies generated are equal to the directory name,

## Environment data
`dotnet --info` output:

**Comment by svick** [comment]
You can specify the project name in project.json by using [`"name"`](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#name). Are you effectively asking for the VS template for .Net Core projects to create project.json with `"name"` included?

**Comment by maxim-boligatov** [comment]
"name" property does not make anything and as I know currently is not supported...

you can use this to rename assemblies:

 "buildOptions": {
        "outputName": "OutputName"
 }

But I think it is just a trick and bug is still there. So as workaround it is better to recreate project and move source inside this new.

**Comment by svick** [comment]
@maxim-boligatov It works for me. If I add `"name": "some other name",` to the top of my project.json, then `dotnet build` acknowledges the new name:

```
Project some other name (.NETCoreApp,Version=v1.0) will be compiled because Input items removed from last build
Compiling some other name for .NETCoreApp,Version=v1.0
```

And it produces `some other name.dll`.

**Comment by J0rgeSerran0** [comment]
Thats right svick.

The behaviour between .NET Framework and .NET Core is different.

With the "name" property, the assemblies are compiled with that name, however, and in my opinion, the default name of the assemblies should be respected as ocurrs in NET Framework.

I know that .NET Framework and .NET Core are different, but in this case, the "name" property should be included in the project.json by default... 
Furthemore, I have not tested with MSBuild, but I continue thinking that the default behaviour in .NET Core should be the same that in .NET Framework.

**Comment by piotrpMSFT** [comment]
The original bug here points out a distinction between the csproj and project.json project systems. Fortunately, the team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
