### ISSUE TITLE
Can't run off fresh install.  Unable to load DLL 'libc':

### ISSUE THREAD

**Issue by anandx** [dotnet/cli#3875]
I'm trying to install dotnet on my Mac following the instructions here: 
https://www.microsoft.com/net/core#macos

However when I try the command "dotnet new" I get the following error: 

```
Anands-MacBook-Pro:~ anandx$ dotnet new

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment' threw an exception. ---> System.PlatformNotSupportedException: Error reading Darwin Kernel Version ---> System.DllNotFoundException: Unable to load DLL 'libc': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.sysctl(Int32* name, UInt32 namelen, Byte* oldp, UInt32* oldlenp, IntPtr newp, UInt32 newlen)
   at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.InternalAbstractions.Native.NativeMethods.Darwin.GetKernelRelease()
   at Microsoft.DotNet.InternalAbstractions.Native.PlatformApis.GetDarwinVersion()
   at Microsoft.DotNet.InternalAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.InternalAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Abort trap: 6
```

Any idea whats going on?  I assume since it can't find libc its some path issue?

**Comment by jasonwilliams200OK** [comment]
* What is the output of: `system_profiler SPSoftwareDataType`? (operating system info)
* Does this return path or complain: `ls /usr/lib/libc.dylib`?

**Comment by PatNeedham** [comment]
I'm getting the same error @anandx is getting. When I run the system profiler command my output is:
`Software:

    System Software Overview:

      System Version: OS X 10.11.5 (15F34)
      Kernel Version: Darwin 15.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: MacBookPro (2)
      User Name: Pat Needham (patneedham)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3:28`

And typing `ls /usr/lib/libc.dylib` just returns `/usr/lib/libc.dylib`.

**Comment by jasonwilliams200OK** [comment]
Mine is also `System Version: OS X 10.11.5 (15F34)` and `dotnet new` is working just fine. There was a similar issue with Apple Ruby runtime with El Capitans.

I think I have the fix: jasonwilliams200OK/coreclr@a2e5d99. I will send the PR to CoreCLR, but since I can't reproduce this issue to begin with. if you could  try to apply the patch as following (warning: bit long process):

```sh
git clone https://github.com/jasonwilliams200ok/coreclr -b cli-3875

coreclr/build.sh release

# it may ask you to install cmake, libunwind etc. if you haven't already,
# use "brew install" to get those deps

# make backup of existing libcoreclr.dylib in ahe installed runtime dir first:
mv $(dirname $(which dotnet))/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.dylib \
$(dirname $(which dotnet))/shared/Microsoft.NETCore.App/1.0.0/libcoreclr.dylib.old
# ^ this way, you can always move `libcoreclr.dylib.old` back to `libcoreclr.dylib`

# copy newly built libcoreclr.dylib over to the installed runtime dir
cp coreclr/bin/Product/OSX.x64.Release/libcoreclr.dylib \
$(dirname $(which dotnet))/shared/Microsoft.NETCore.App/1.0.0/
```

Then try if `dotnet new` works. 

/cc @jkotas

**Comment by PatNeedham** [comment]
Thank you for the fix Jason, but it didn't completely work because when I ran `dotnet new` this time, I got a smaller error:
`RestoreState: 1293: thread_set_state(thread) (os/kern) invalid argument
Abort trap: 6`

Also, fyi I had to change `git clone https://github.com/jasonwilliams200ok/coreclr -b cli-3875` to `git clone https://github.com/jasonwilliams200ok/coreclr -b fix/cli-3875` after looking at your active branches.

**Comment by jasonwilliams200OK** [comment]
Thanks, fixed the branch name in prev comment.
Uou would probably need to copy/paste some other stuff like mscorlib (which builds on Windows; see `On Windows (using PowerShell)` section in this comment: https://github.com/dotnet/coreclr/issues/917#issuecomment-231723500).

Or could you just try this simple program and see the result:

`libc-test.c`

```c
#include <stdio.h>
#include <dlfcn.h>

int main()
{
    void *dl_handle = dlopen("libc.dylib", RTLD_LAZY);

    printf("Pass 1:\n\n");

    if (dl_handle == NULL)
        printf("With shortname: Error\n\n");
    else
        printf("With shortname: All good! :)\n\n");

    dl_handle = dlopen("/usr/lib/libc.dylib", RTLD_LAZY);

    printf("Pass 2:\n\n");

    if (dl_handle == NULL)
        printf("With fullname: Error\n\n");
    else
        printf("With fullname: All good! :)\n\n");

return 0;
}
```

then compile and run:

```sh
clang libc-test.c
./libc-test.out
```

**Comment by PatNeedham** [comment]
I ran the simple program and got this:
`Pass 1:

With shortname: Error

Pass 2:

With fullname: All good! :)`

So that means I need to replace the shortname with the full name somewhere?

**Comment by jasonwilliams200OK** [comment]
@PatNeedham, great! This means  jasonwilliams200OK/coreclr@a2e5d99 is good to go. I will send a PR to CoreCLR to fix this. :wink:

**Comment by anandx** [comment]
Sweet!!  I'm a little reluctant to try building this myself, do know when a Mac installer might be available so I can text the fix?  🙏🏾

**Comment by jasonwilliams200OK** [comment]
@anandx, fingers-crossed. If you have access to older mac or info about the location of libc.dylib in various older versions of macOS, then please chime-in to this question: https://github.com/dotnet/coreclr/pull/6302#discussion_r71118194 so the PR could move forwards.

**Comment by m2b** [comment]
Having similar issue with dotnet restore.   Solved it by running sudo dotnet restore

**Comment by m2b** [comment]
Not an acceptable solution after all, everything requires sudo, including run.  Also C# tools for Visual Studio code cannot find the path to the CLI tools and hence is useless.  Please create a new Mac installer.

**Comment by vidstige** [comment]
`DYLD_FALLBACK_LIBRARY_PATH=/usr/lib:/opt/local/lib dotnet new`

**Comment by veeral-patel** [comment]
Can confirm @vidstige's solution works on Mac OS Sierra in Visual Studio Code. Thanks so much!
