### ISSUE TITLE
project.json "entryPoint" property does nothing

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3877]
## Steps to reproduce

create project.json:

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "entrypoint": "ConsoleApplication.Program.Hello",
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

Create Program.cs

```
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Hello(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```
1. dotnet restore
2. dotnet build
## Expected  behavior

Builds successfully
## Actual behavior

`C:\Users\brthor\code\proto\entrypoint\error CS5001: Program does not contain a static 'Main' method suitable for an entry point`
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003253)

Product Information:
 Version:            1.0.0-preview3-003253
 Commit SHA-1 hash:  f63258ebaa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
You would expect it to do nothing and just generate a library?

**Comment by brthor** [comment]
I expect it to use the `Hello` method as the entrypoint rather than looking for a method named `Main`

**Comment by brthor** [comment]
After a brief search, it doesn't look like this property is ever used outside of being read into Project.cs

**Comment by livarcocc** [comment]
Oh, there is an entryPoint property. Had not noticed that.

**Comment by brthor** [comment]
Filing this to use as tracking for the migration docs.
