### ISSUE TITLE
CoreCLR crash in SLES 11 SP3

### ISSUE THREAD

**Issue by FZ14** [dotnet/cli#3880]
Hi!
I try to install dotnet core in SUSE Linux Enterprise Server 11 SP3.

After installing dependencies I have an error, when I try execute command:
`dotnet --version`
or
`dotnet new`

### Failed to initialize CoreCLR, HRESULT: 0x80131500.

[DotnetCoreVersionTrace.txt](https://github.com/dotnet/core/files/359189/DotnetCoreVersionTrace.txt)

For install I use instruction from https://www.microsoft.com/net/core#opensuse:

`sudo zypper install libunwind libicu`
`curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=816867`
`sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet`
`sudo ln -s /opt/dotnet/dotnet /usr/local/bin`

PS:
SUSE Linux Enterprise Server 11 SP3 is officialy supported? Or only openSUSE 13.2?

**Comment by blackdwarf** [comment]
@FZ14 for now, as the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps) shows, openSUSE 13.2 is the supported version. However, just to be sure about the failure, can you tell me what kernel version does SLES 11 SP3 come with?

**Comment by FZ14** [comment]
@blackdwarf 
`uname -r `
3.0.76-0.11-default

**Comment by jasonwilliams200OK** [comment]
@FZ14, would be nice to also attach (or share via a [gist](https://gist.github.com/)) the strace output: `sudo zypper install strace && strace dotnet new`.

**Comment by gkhanna79** [comment]
The hresult corresponds to a managed exception being thrown. @janvorli Can you PTAL?

**Comment by janvorli** [comment]
I'll take a look. I am installing openSUSE now.

**Comment by janvorli** [comment]
It looks like the instructions are missing the libicu prerequisity. The failure is due to the failure to load System.Globalization.Native.so. Running ldd on the System.Globalization.Native.so gets the following, see the "not found":
```
janvorli@janvorli-suse:~/test> ldd /opt/dotnet/shared/Microsoft.NETCore.App/1.0.0/System.Globalization.Native.so
        linux-vdso.so.1 (0x00007ffc774fd000)
        libicuuc.so.53.1 => not found
        libicui18n.so.53.1 => not found
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f7c62858000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f7c62557000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7c6233f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f7c61f98000)
        /lib64/ld-linux-x86-64.so.2 (0x000055586435f000)
```

**Comment by janvorli** [comment]
Actually, I am sorry. The libicu is in the instructions. But the version installed on suse is 52.1 while the System.Globalization.Native.so refers to 53.1

**Comment by janvorli** [comment]
Installing libicu53_1-ledata (https://software.opensuse.org/package/libicu53_1-ledata) and libicu53_1-53 (https://software.opensuse.org/package/libicu53_1) fixed the problem.

**Comment by blackdwarf** [comment]
@janvorli I will update the instructions then. Are both of the mentioned required?

**Comment by janvorli** [comment]
Yes, the libicu53_1-ledata is a prerequisity for installing the actual  libicu53_1

**Comment by blackdwarf** [comment]
@janvorli wouldn't `zipper` then install the both? Also, wait...this is not required for OpenSUSE 13.2, right?

**Comment by janvorli** [comment]
I am not familiar with openSUSE very much, so I might have done it in a too complex way. I have tried to install the libicu53_1 from the opensuse 13.2 machine using the "1 click install" on the page https://software.opensuse.org/package/libicu53_1, but the installation has failed for some reason. But I guess it could have been due to some other issue.

**Comment by janvorli** [comment]
What do you mean by "this is not required for OpenSUSE 13.2"? The libicu53_1 is required for it, the default one installed there is 52_1.

**Comment by blackdwarf** [comment]
The issue specifies that this is a different version of SUSE (and edition), so that's why I asked.

I've tested out SUSE getting started instructions multiple time(s) and never hit this error so I'm wondering what is happening.
Thanks,
Z

Sent from my tricorder

_____________________________

**Comment by piotrpMSFT** [comment]
Looks like the root issue was resolved and docs will be updated. Thanks folks.

**Comment by FZ14** [comment]
Hi!
SLES 11 SP3 will be supported in .NET Core 2.0?

**Comment by boomsya** [comment]
> 
> 
> Hi!
> SLES 11 SP3 will be supported in .NET Core 2.0?

the same question. But we have SLES 11 SP4.
.NET Core 2.0.9 want libicu5  (Problem: nothing provides libicu52_1 needed by dotnet-runtime-deps-2.1-2.1.6-1.x86_64...)
but SLES 11 have only libicu4 :( and I cant found libicu5
