### ISSUE TITLE
Tools for VS '15

### ISSUE THREAD

**Issue by SoonDead** [dotnet/cli#3881]
## Steps to reproduce

Open an ASP.NET Core 1.0 project in Visual Studio '15.

## Actual behavior

The project does not open, since VS does not recognize the project type (`Microsoft.DotNet.Web.targets is missing`) since there is no installer for Visual Studio '15.

This issue is a copy of https://github.com/dotnet/core/issues/220 .

**Comment by piotrpMSFT** [comment]
Moved to `aspnet/tooling`
