### ISSUE TITLE
Windows x64 Preview 3 installer still showing Preview 2 name

### ISSUE THREAD

**Issue by markrendle** [dotnet/cli#3882]
## Steps to reproduce

Download and run the [Windows SDK 1.0.0-preview3-003180](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe) installer

## Expected  behavior

UI for installer should say *SDK Preview 3*

## Actual behavior

UI for installer says *SDK Preview 2*

## Environment data
`dotnet --version` output **before** running latest installer:

`1.0.0-preview2-003121`

`dotnet --version` output **after** running latest installer:

`1.0.0-preview3-003180`

So it's installing the latest version, it's just the name in the UI that's wrong.

**Comment by piotrpMSFT** [comment]
Thanks. `preview3` is presumptive branding. We needed a string > preview2 to keep producing builds and +1 won :) We'll update the installer UI once we know the right strings for the next release.

@brthor
