### ISSUE TITLE
Core 1.0.0-preview2-003121 slow to view changes

### ISSUE THREAD

**Issue by tatalvit** [dotnet/cli#3883]
## Steps to reproduce

Initial setup:
1. In Visual Studio, create new ASP.NET Core Web Application (.NET Core). Use template "Web Application"
2. Run the application without debugging
3. Browse to About page (e.g. http://localhost:50074/Home/About)

Test case A:
4. Edit HomeController.cs About() contoller to 
`ViewData["Message"] = "Hello world 2!";`
and save the change
5. Hit F5 in browser and see how long it takes for IIS Express to respond with the change

Test case B:
4. Edit Startup.cs Configure() by adding a line:
`int foo=1;`
5. Hit F5 in browser

Test case C:
4. Edit Startup.cs Configure() by adding a line:
`app.Run(async (context) => { await context.Response.WriteAsync("Hello World3!"); });`
(requires also: `using Microsoft.AspNetCore.Http;`)
5. Hit F5 in browser

## Expected  behavior

All use cases should respond within 5 seconds.

## Actual behavior

All cases compile within 2.5 seconds
1>  Time elapsed 00:00:02.3853349

But the total response time until IIS Express to view the change:
Case A: around 9-12 seconds
Case B: around 9-12 seconds
Case C:  around 4-5 seconds

So where is the extra 5 seconds wasted here?

Note: Test case A results in Core 1.0 RC1: IIS Express responded within 4-5 seconds as expected.

Also compile time seems oddly long for simple Hello world application (I have fast SSD, 10GB of free RAM, and other CPU usage below 10%)

## Environment data
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Moved to aspnet/toolng

**Comment by tatalvit** [comment]
Link to aspnet/toolng is https://github.com/aspnet/Tooling/issues/690
