### ISSUE TITLE
project.json unused properties present in schema

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3892]
There are a number of properties which are unused in dotnet cli, but are present in the project.json schema. 

(Will update this list as I find more)

```
userSecretsId
libraryIncludeFlag
libraryIncludeFlags
```

https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json

**Comment by brthor** [comment]
These property names are generated on-the-fly and read in a different location than the rest of properties:

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Files/PatternGroup.cs

**Comment by piotrpMSFT** [comment]
@anurse @davidfowl @pakrym any recollection of the purpose of these?

**Comment by anurse** [comment]
`userSecretsId` is read by the https://github.com/aspnet/UserSecrets tools. It is likely this will need to move outside the project (it's already been problematic that it's in there now).

Not sure about the other two.
