### ISSUE TITLE
project.json "preprocess" properties unused

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3893]
These properties in project.json:

```
{
    "preprocess": ["compiler/preprocess/**/*.cs"],
    "preprocessExclude": ["compiler/preprocess/**/*.cs"],
    "preprocessFiles": ["compiler/preprocess/**/*.cs"]
}
```

Are read into this property:
https://github.com/dotnet/cli/blob/04f40f906dce2678d80fb9787e68de76ee6bf57e/src/Microsoft.DotNet.ProjectModel/Files/ProjectFilesCollection.cs#L114

Which is never used.

**Comment by piotrpMSFT** [comment]
@anurse @davidfowl @pakrym any recollection of the purpose of these?

**Comment by pakrym** [comment]
They were used for `ICompileModule` (preprocessor) feature of DNX (http://www.inversionofcontrol.co.uk/meta-programming-with-roslyn-on-aspnet-vnext/). They could be safely removed.

**Comment by piotrpMSFT** [comment]
they did not make it into csproj :)
