### ISSUE TITLE
dotnet run produces 'Error : No hosts found'

### ISSUE THREAD

**Issue by FlameDuck** [dotnet/cli#3897]
## Steps to reproduce
Type 'dotnet run' in bash.

## Expected  behavior
The project is run (this worked a few days ago).

## Actual behavior
I get 'Error : No hosts found' (I am not aware of any changes I have made to the system).

## Environment data
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

## Additional Info

I have tried purging and reinstalling the package without success. I have also googled this extensively and I seem to be the only person with this issue.

**Comment by blackdwarf** [comment]
@FlameDuck can you share the `project.json` that you are trying to run?

**Comment by FlameDuck** [comment]
Sure.

    {
      "version": "1.0.0-*",
      "description": "Zerg Rush Console Application",
      "buildOptions": {
        "emitEntryPoint": true
      },
      "dependencies": {
        "HtmlAgilityPack.NetCore": "1.4.9.2",
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-*"
        },
        "Newtonsoft.Json.NetCore": "9.0.2"
      },
      "frameworks": {
        "netcoreapp1.0": {
          "imports": "dnxcore50"
        }
      }
    }

**Comment by blackdwarf** [comment]
@FlameDuck so, the binaries are dropped after the build in the `bin` folder but on executing the application it throws the error. Can you try to just `dotnet` and path to your assembly to see what is happening?

The only thing I see in your project file is that maybe you want to switch over to the 1.0.0 version of the framework.

**Comment by FlameDuck** [comment]
@blackdwarf Exactly after building I have the following files in /bin/debug/netcoreapp1.0.
    -rwxrw-r-- 1 mikkel mikkel  1780 Jul 25 15:46 zerg-rush.deps.json
    -rwxrw-r-- 1 mikkel mikkel 21504 Jul 25 15:46 zerg-rush.dll
    -rwxrw-r-- 1 mikkel mikkel  5004 Jul 25 15:46 zerg-rush.pdb
    -rwxrw-r-- 1 mikkel mikkel   104 Jul 25 15:46 zerg-rush.runtimeconfig.dev.json
    -rwxrw-r-- 1 mikkel mikkel   118 Jul 25 15:46 zerg-rush.runtimeconfig.json

dotnet and the path to the binary just gives the same ```Error : No hosts found.``` I tried with 1.0.0 and ```dotnet restore```, same thing. :( I'm sorry I'm not really being all that helpful.

**Comment by piotrpMSFT** [comment]
I checked the CLI and Host repos and I don't see any obvious places where we would emit a string of 'Error : No hosts found'.

@FlameDuck, this is a long shot, but is there any chance that the app itself is emitting this string? 

I also noticed that "No hosts found" is a fairly common error message in Python. Can you try `where dotnet` and see if there is something on your PATH that's getting in the way?

**Comment by FlameDuck** [comment]
Hej guys,

Thanks for all the help a ```dotnet-host``` was in my ```apt-get upgrade``` yesterday, and now it seems to be working again, so I'm just going to assume either the Python thing, or something I unintentionally broke. Thanks for all the help, and sorry for wasting your time. Keep up the good work. This whole dotnet core thing is the first thing since docker, that really got me excited about development again.
