### ISSUE TITLE
Binding Redirects generated by build can become stale

### ISSUE THREAD

**Issue by rynowak** [dotnet/cli#3898]
## Steps to reproduce
**Use this `project.json` and `Program.cs` in a Console Application**

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.Extensions.DependencyModel": "1.0.1-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50",
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
      }
    },
    "net451": {
    }
  }
}
```
```
namespace ConsoleApp3
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // Force the assembly to load.
            Microsoft.Extensions.DependencyModel.Dependency d;
        }
    }
}
```

**Do a `dotnet restore` and `dotnet build`.**

This will generate the following `.exe.config` file with correct binding redirect in the `bin\Debug\net451\win7-x64` folder.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.DependencyModel" publicKeyToken="adb9793829ddae60" culture="neutral" />
        <bindingRedirect oldVersion="1.0.0.0" newVersion="1.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

These are needed because `Microsoft.AspNetCore.Mvc` references `"Microsoft.Extensions.DependencyModel": "1.0.0"`.

**Now change the project.json**

Use `"Microsoft.Extensions.DependencyModel": "1.0.0"` instead.

**Do another `dotnet restore` and `dotnet build`**

The old binding redirect is still there in the `.exe.config` even though it is out of date with the project.

This will crash at runtime, but only for desktop (net451):
```
System.IO.FileLoadException was unhandled
Message: An unhandled exception of type 'System.IO.FileLoadException' occurred in Unknown Module.
Additional information: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Deleting the `.exe.config` solves the issue.

## Expected  behavior

`.exe.config` file will be deleted if the binding redirects aren't needed.

## Actual behavior

Binding redirects can get out of date if the project is changed in such a way that they are not needed anymore.

We pretty quickly get into this situation in our unit tests projects when switching between `1.0.1` and `1.1.0` development.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003206)

Product Information:
 Version:            1.0.0-preview3-003206
 Commit SHA-1 hash:  9c6bcb9a83

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by nil4** [comment]
Sounds similar to #2855 which seems to have fallen off the radar.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

The existing targets responsible for building .NET projects in MSBuild have a much more mature implementation of Binding Redirect generation. This issue will be resolved by the transition.
