### ISSUE TITLE
dotnet restore does not check Current User/Trusted People certificate store, only checks Local Computer

### ISSUE THREAD

**Issue by stunney** [dotnet/cli#3899]
## Steps to reproduce
Run your own private NuGet repository only accessible via HTTPS.  Use a self signed certificate or a certificate signed by a CA that isn't currently trusted by the client.

Add a package to your project from nuget. org.  Ensure that package also exists now in your private repo.

Now ensure that a NuGet.config file is present that only allows communication to this private repo and not nuget.org, for example.

Clear out the C:\Users\<user>\.nuget cache

Add the certificate to <user>'s Trusted People certificate store as the old nuget.exe 2.8 would do.

Run:
dotnet restore

## Expected  behavior
The package should be downloaded successfully.

## Actual behavior
error:  An error occured while sending the request.
error:  A security error occured.
info:  Failed to retrieve information from remote source 'http://host/FindPackagesById()?id='Newtonsoft.json'
err

## Work-around
Add certificate to Local Computer (Machine)'s Trusted People store.  This is a security issue if a machine is shared (build machines).

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by blackdwarf** [comment]
@stunney this should be moved to NuGet/Home as it is a NuGet issue. `dotnet restore` uses NuGet for its operation. 

/cc @rrelyea @harikmenon

**Comment by stunney** [comment]
Done.  My apologies.
https://github.com/NuGet/Home/issues/3188
