### ISSUE TITLE
compile and publish commands need handle native compilation in its various forms

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#39]
Today we provide the option to include native images with your output:

--native                         Build and include native images. User must provide targeted CoreCLR runtime versions

We need to reconcile this with all the other scenarios and provide the right knobs/defaults. Should this be a compile or publish option (or both).

Examples of some of the scenarios:
Ngen:
$ dotnet compile --aot=partial
Full AOT:
$ dotnet compile --aot=full
Leave as IL: 
$ dotnet compile --aot=none

**Comment by blackdwarf** [comment]
Since compile native is a separate package now, we will need to solve this differently. I will close this issue. Please reopen if needed.
