### ISSUE TITLE
Remove 'cli' from OSX install root location.

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#390]
Ubuntu - /usr/share/dotnet
Windows - %ProgramFiles%/dotnet
OSx - [/usr/local/share/dotnet/cli]https://github.com/dotnet/cli/blob/master/packaging/osx/package-osx.sh#L46

Lets make it consistent across all platforms. Remove `cli` for the OSX install root.

**Comment by brthor** [comment]
As a part of this let's make sure this is updated in CoreHost.

https://github.com/dotnet/cli/blob/master/src/corehost/src/pal.unix.cpp

**Comment by blackdwarf** [comment]
I believe this is now done, so closing.
