### ISSUE TITLE
dotnet --info should display the path to the dotnet being used

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#3900]
Very useful as a developer of the CLI where usually I have a few versions installed. I believe that would be useful in general as well.

**Comment by brthor** [comment]
This would be really nice :smile:

**Comment by blackdwarf** [comment]
Wait...you can only have one dotnet on the $PATH, correct? The version tells you which version of the SDK you are using, so how would a path help?

**Comment by piotrpMSFT** [comment]
If we do this feature let's be sure to put the path on the bottom of the output so folks can share output so folks can easily share `info` output without sharing e.g. their user name on the path.

@blackdwarf you can have many dotnets on the PATH. The `first` one simply wins.
