### ISSUE TITLE
dotnet ef - No executable found matching command dotnet-ef

### ISSUE THREAD

**Issue by Korigoth** [dotnet/cli#3902]
I Installed VS2015 Update 3 with ASP.Net Core.
Starting a new ASP.Net Core Project with Individual Account.

When trying to update my database to generate my database i'm getting "No executable found matching command dotnet-ef" error.

I tried to clear my nuget/packages and restore with dotnet restore, the restore work great but the error still occur.

I don't know what's wrong! 

Here is my: dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by svick** [comment]
Do you have the EF tool in your project.json? According to [the documentation](http://ef.readthedocs.io/en/latest/miscellaneous/cli/dotnet.html#install-by-editing-project-json), it should look like this:

```json
"tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
}
```

**Comment by Korigoth** [comment]
yep it's present

    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",

**Comment by Korigoth** [comment]
I got it working but in package manage console, i needed to   cd webapplication1 -> to get in the project
then i did  dotnet ef database update and it worked!    but it doesn't work in a class library with the   

"buildOptions": {
    "emitEntryPoint": true
  }, 

so dotnet run  work but couldn't start because it's a library dll but dotnet ef database update doesn't work at all getting the command error

**Comment by blackdwarf** [comment]
@Korigoth the CLI tools require you to be in the context of the project where the tools are defined. You can find more information about these in this document: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/extensibility#per-project-based-extensibility. 

I'm not sure I understand your last comment. Can you clarify a bit?

**Comment by piotrpMSFT** [comment]
For the time being dotnet-ef can only be used on executables, as you noted.

@natemcmaster you are taking a look at alternative approaches to this problem so dotnet-ef can run against libraries. Do you have an issue tracking this?

**Comment by natemcmaster** [comment]
This is tracked by https://github.com/aspnet/EntityFramework/issues/5320

**Comment by blackdwarf** [comment]
Closing this issue in favor of aspnet/EntityFramework#5320
