### ISSUE TITLE
Lower dotnet new library template netstandard version

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#3903]
Let's lower this:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-new/CSharp_Lib/project.json.template#L8

To be more broadly applicable.

**Comment by piotrpMSFT** [comment]
@brthor what netstandard version did we settle on?

**Comment by brthor** [comment]
@richlander @blackdwarf input here?

**Comment by blackdwarf** [comment]
According to @richlander this should be `netstandard1.4`. Of course, final confirmation will be coming by EOD today.

**Comment by brthor** [comment]
Can I assume we've landed on `netstandard1.4`

**Comment by Petermarcu** [comment]
yes
