### ISSUE TITLE
Build time resolution does not work as expected

### ISSUE THREAD

**Issue by nothrow** [dotnet/cli#3908]
On RTM, attached code compiles (`dotnet restore && dotnet build`) without any warning.

```
{
  "version": "1.0.0-*",
  "description": "Ping Test",
  "authors": [ "Vit.Tauer" ],
  "dependencies": {
    "NETStandard.Library": "1.6.0-*",
  },
  "buildOptions": {
    "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        },
        "System.Net.NameResolution": "4.0.0-*",
        "system.net.utilities": "4.0.0-*"
      },
      "imports": [ "dnxcore50" ]
    }
  }
}
```

```
using System;
using System.Net;
using System.Net.NetworkInformation;

public class Program
{
    public static void Main(string[] args)
    {
        var ping = new Ping();
        var result = ping.SendPingAsync(IPAddress.Loopback).Result;
        Console.WriteLine($"{result.Status}");
    }
}
```

But on running:

`Unhandled Exception: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task"1<System.Net.NetworkInformation.PingReply> System.Net.NetworkInformation.Ping.SendPingAsync(System.Net.IPAddress)'. at Program.Main(String[] args).`

I expect the compilation to fail.

(moved from https://github.com/dotnet/core/issues/105).

**Comment by jasonwilliams200OK** [comment]
Replace:

```json
"system.net.utilities": "4.0.0-*"
```

with:

```json
"System.Net.Ping": "4.0.0"
```

and drop `"imports": [ "dnxcore50" ]`. Program.cs will compile.

`System.Net.Utilities` seems to be discontinued with all the funcitonalities moved to different packages.

However, the CLI bug needs to be fixed that it does not give compilation error but failing at runtime.

In my case the runtime error was:

```cmd
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Utilities, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at Program.Main(String[] args)
```

*after* the successful `dotnet restore && dotnet build`.

**Comment by davidfowl** [comment]
What compilation error did you expect?

**Comment by jasonwilliams200OK** [comment]
If the dependency is not found, should it compile and throw at runtime?

**Comment by nothrow** [comment]
@davidfowl: Since there is 'MissingMethodException' for me, I'd expect the method is not found at compile time as well, so CS0117.

**Comment by piotrpMSFT** [comment]
@nothrow MissingMethodExceptions usually occur when reference assemblies and runtime assemblies get out of sync. Build succeeded happily against the references, but their contract was not fulfilled by the runtime assemblies.
