### ISSUE TITLE
Allow host serviceability

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#391]
When operating in the shared-runtime model, `corehost` needs to support some degree of serviceability. We'll need to do a little bit of design here since there are a few open questions:

* Servicing multiple versions: Do we identify the version of the desired runtime and then look for servicing?
* Do we just service the host? That would allow us to simplify things a little. In that case, the host will look and see if the host has been serviced. If it has, it would just load that host. The new host would then be responsible for locating and loading the runtime (possibly by checking if the runtime has been serviced). It also significantly reduces the "unserviceable" code (to just the code that looks for a serviced host)

**Comment by piotrpMSFT** [comment]
We need to decide on host/runtime package relationship

**Comment by anurse** [comment]
I believe @schellap has handled host servicability (or is at least working on it as part of the general servicability story)
