### ISSUE TITLE
Supporting *.project.json

### ISSUE THREAD

**Issue by shhsu** [dotnet/cli#3910]
Just wondering if we are aware that ```dotnet restore``` supports having multiple project files (i.e. project.json and *.project.json) in the same directory. However ```dotnet build``` ```dotnet publish``` does not.

More specifically, I tried creating a project with 2 different project files ```project.json``` and ```mcj.project.json```. Each have slightly different dependencies and compiler flags. When I ```dotnet restore```, both ```project.lock.json``` and ```mcj.project.json``` are created. However if I try to ```dotnet publish``` the app providing the location of ```mcj.project.json``` as project location, I would get an error like this:

 ```
D:\GitHub\dockbench\testapp\BasicKestrel>dotnet publish D:\GitHub\dockbench\testapp\BasicKestrel\mcj.project.json -o .testpublish -c release -f netcoreapp1.0
The current project is not valid because of the following errors:
D:\GitHub\dockbench\testapp\BasicKestrel\mcj.project.json(1,0): error DOTNET1017: Project file does not exist 'D:\GitHub\dockbench\testapp\BasicKestrel\mcj.project.json'.
```

Seems that ```restore``` delegates to NuGet which supports *.project.json but ```build``` and ```publish``` verify the file name to be exactly ```project.json``` i.e.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/ProjectPathHelper.cs#L40

Can we support multiple ```*.project.json``` like NuGet does?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

csproj files already possess file names so this issue will be resolved once we ship with msbuild.
