### ISSUE TITLE
Difference between emitted warnings in dotnet restore and dotnet pack

### ISSUE THREAD

**Issue by DovydasNavickas** [dotnet/cli#3912]
We execute various `dotnet` commands with powershell in VSTS build agent.
`dotnet restore` emits warnings, but they are treated as errors in build reports.
On the other hand, `dotnet pack` emits warnings and they are treated as warnings.
There might be some difference between them `restore` and `pack` behaviours.

## Steps to reproduce
We have CI server which produces packages with versions suffixed with `ci-2253`, where `2253` is a build number.
Then, during other project package restore, we have dependencies versions set to `2.0.0-*` in `project.json`.
Which is where we get warnings from `dotnet restore`:
```
D:\MyProject\project.json(13,41): warning NU1012: Dependency conflict. MyOtherProject 2.0.0-ci-2253 expected MyDependency >= 2.0.0 but received 2.0.0-ci-2253
```

## Expected  behavior
In build report, these warnings should be treated as warnings.
(hence `dotnet pack` behaviour)

## Actual behavior
In build report, these warnings are treated as errors.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by DovydasNavickas** [comment]
By the way, `dotnet pack` emits warning when version in `project.json` is set to `2.0.0-*`.

**Comment by brthor** [comment]
@DovydasNavickas 

Please share the project.json of hte app which references `MyDependency`

**Comment by DovydasNavickas** [comment]
Ok, turns out there were a few misunderstandings on my side, but it does not change how the CLI should report warnings.

First of all, I changed project names from my own ones to artificial ones like "MyProject", "MyOtherProject" and "MyDependency".

Secondly, I tried to create a repro for you to have a clear look. I tried doing that with a local folder as a NuGet feed instead of CI and VSTS packages feed.
While doing that, I analyzed our situation a bit deeper and figured out that warnings that I thought were produced by `dotnet pack` were a simple powershell `Write-Warning` command outputs of ours:
```powershell
Write-Warning "Invalid characters at version property in $($path) file.";
```

So, sorry for the confusion here.

Also, I figured out that my colleague used quite a spectacular way of producing CI versioned packages:
1. All projects were build
2. `project.json` files were read as JSON, their versions updated with CI suffix and written back to original `project.json` files
3. `dotnet pack $path --no-build` was executed and produced the packages

Turns out that updating 2nd step of the rain dance to use `--version-suffix` parameter on `dotnet pack` solved the issue. BUT. (you might have already expected the 'but')

The reason the rain dance appeared in the first place is because [CLI documentation](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-pack#synopsis) is a bit inconsistent.

`--version-suffix` is only mentioned in the **synopsis** and not in **options** paragraphs, which makes it REALLY easy to miss.
I've already created PR to fix this: https://github.com/dotnet/core-docs/pull/836

Another question would be what happens when this kind of rain dance is applied that it gives the mentioned warning:
```
D:\MyProject\project.json(13,41): warning NU1012: Dependency conflict. MyOtherProject 2.0.0-ci-2253 expected MyDependency >= 2.0.0 but received 2.0.0-ci-2253
```

And even though the warnings that were treated as warnings in build report were powershell's `Write-Warning` outputs, having `dotnet restore` and `dotnet build` warnings emitted as actual warnings (and not errors) would still help really much, because now we have to do another rain dance to omit build failure like this:
```powershell
import-module "Microsoft.TeamFoundation.DistributedTask.Task.Internal"
import-module "Microsoft.TeamFoundation.DistributedTask.Task.Common"

$dotnet = Get-Command -Name dotnet -ErrorAction Ignore
$dotnetArguments = " build"
Invoke-Tool -Path $dotnet.Path -Arguments $dotnetArguments -WorkingFolder $project.Directory
```
Which in essence ignores all of the errors, no matter if they were warnings or errors originally.

Also, coming into build report is quite terrifying, because compiler warnings are shown as errors, even though it might be a common:
```
D:\MyProject\Library.cs(18,42): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
```

**Comment by DovydasNavickas** [comment]
After more testing, I see that the `-ErrorAction Ignore` rain dance actually partially solves the problem, because when there are only warnings in `dotnet build`, the CLI return code is successful and when there are errors, it gives this:
```
System.Exception: Unexpected exit code 1 returned from tool dotnet.exe
```

But that still does not change the fact that warnings are emitted as errors into build report and have to be ignored.

**Comment by piotrpMSFT** [comment]
Thanks @DovydasNavickas. The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

MSBuild's output formatting is quite mature so this should be more than adequately addressed!
