### ISSUE TITLE
Why were the C# and F# REPLs removed and when/how will it implemented "as a separate tool"?

### ISSUE THREAD

**Issue by rogersachan** [dotnet/cli#3913]
## Steps to reproduce
`dotnet repl`
`dotnet repl csi`
`dotnet repl fsi`
None of these start a REPL!

## Expected  behavior
REPL opened

## Actual behavior
No executable found matching command "dotnet-repl"

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86

**Comment by jaen** [comment]
Ditto, was the first thing I tried with my `dotnet` command I installed to do some F#.

**Comment by rogersachan** [comment]
Issue #1289 says that it was going to be reimplemented as a separate tool, but I've heard nothing of the sort. Is this going to be available in preview 3 or rtm?

**Comment by piotrpMSFT** [comment]
There is not a timeline for REPL commands at this time.

**Comment by codec-abc** [comment]
I don't know if this is the right place to ask this (please forgive me in case it's the wrong place), but is there any news concerning the repl status for dotnetcore? Is there any chance to get a REPL some day? If yes which languages will be supporte and by when?

**Comment by ShalokShalom** [comment]
I am also interested.

**Comment by rogersachan** [comment]
I don't think it's going to come back unless somebody pull requests it back in

**Comment by ShalokShalom** [comment]
Means there is some fundamental support for both, C# and F# missing in .Net Core and it is still meant to replace both, .Net and Mono?

**Comment by codec-abc** [comment]
What bothers me most is that the last comment before closing the issue is rather vague: "There is not a timeline for REPL commands at this time." 

At this time, could mean that they are thinking about it and a REPL may be added in the (near) future or that there is no intent to implement this feature and it probably never come. I don't blame Microsoft for not implementing it (a REPL is clearly not the most important part of .Net Core) but I would appreciate that they give more precision about what they intent to do on this subject.

**Comment by khowling** [comment]
+1 for REPL support
When learning nodejs, i used REPL all the time to try out snippits, it sped things up a lot. 
I'm learning C# now, and really missing a REPL.

**Comment by livarcocc** [comment]
Meanwhile, you might want to try https://try.dot.net/

**Comment by ShalokShalom** [comment]
Thanks a lot. This seems to be meant to provide C#, while no F#?

The Run button on the down gets easily lost here on FF 57, when a massive stream of errors (20 lines) appear since the scroll button does not work anymore then. 

And I like the REPL, since I can code and simply run it. Here, I would have to add ;; after nearly each command. 

Thanks a lot for your suggestion.

**Comment by ShalokShalom** [comment]
> What bothers me most is that the last comment before closing the issue is rather vague: "There is not a timeline for REPL commands at this time."

I am simply wondering, why 600 commits floated into Mono from Core, as the second one got released. 
Now, as we see such a wonderful and fundamental feature in a coma, does it seem impossible to do the other way around. 

Seems again one of such a microsoftish move is happening?

**Comment by livarcocc** [comment]
@piotrpMSFT @jonsequitur to take a look at the feedback on try.dot.net.

**Comment by jaen** [comment]
A online REPL is not enough at all, one of the benefits of REPL-driven-development is the fact, that you can interactively interact with your whole codebase; that's just not possible with such simplistic online tool.

**Comment by livarcocc** [comment]
This is not a statement of we are not doing REPL because there is this "online" version of it. It is more of a "check that out while we don't have  a REPL in the command" statement. Just want to make that clear.

**Comment by ShalokShalom** [comment]
Is this supposed to do work in F-Sharp?

**Comment by martenlindblad** [comment]
So are you doing a REPL or not? At least for me, when F# programming the use of the fsi is quite important. If you are doing a REPL, then at least link the appropriate issue.

**Comment by ShalokShalom** [comment]
Its in development yeah. A developer confirmed this in another thread.

**Comment by codec-abc** [comment]
@ShalokShalom Can you link the comment please?

**Comment by ShalokShalom** [comment]
https://github.com/Microsoft/visualfsharp/issues/1096#issuecomment-336724862

**Comment by baronfel** [comment]
For those F#-interested folks following along here, as of .Net Core SDK 3.0.100 it's possible to launch fsi via `dotnet fsi` from your terminal. Ionide for VS Code supports this when the `FSharp.useSdkScripts` setting is set to `true` in your `settings.json` file.
