### ISSUE TITLE
publishOptions/mappings and remap to ContentRootPath

### ISSUE THREAD

**Issue by dmcweeney** [dotnet/cli#3919]
## Steps to reproduce

Trying to use the publishOptions/mappings syntax to remap a number of files to the root of the target web ie folder pointed to by ContentRootPath. However the setting seems to be ignored.

"publishOptions": {
	"include": [
		"../Common.Includes/mySettings*.json"
	],
	"mappings": {
		"./": {
			"include": "../Common.Includes/mySettings*.json"
		}
	}
},

## Expected  behavior

What I want is the mySettings*.json files to be deployed to the root of the web.

## Actual behavior

They are being deployed to the "Common.Includes" folder in the web.

## Environment data
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment]
try removing the first `include` block

```
"include": [
"../Common.Includes/mySettings.json"
],
```

**Comment by dmcweeney** [comment]
Hi Bryan,

I think I have tried every possible combination of includes and mappings and all I can get is files from CommonIncludes copied to bin\Release\net452\win7-x64\Common.Includes both for publishOptions and CopyToOutput...

I've upgraded to 1.0.0-preview3-003208 at this stage and no difference...

**Comment by GuardRex** [comment]
I'm sure everyone is aware of the occasional advice to use the `xcopy` "hack" in times like this:
```c#
"scripts": {
    "postpublish": [
        "xcopy C:\\<path to application>\\<assets folder>\\* c:\\<path to application>\\bin\\Release\\netcoreapp1.0\\win10-x64\\publish\\ /s /i"
    ]
},
```
However, someone did just say that it only works when publishing from the command line and not with VS (but I haven't verified it ... I'm still on VS Code! :+1: ). https://github.com/dotnet/cli/issues/3030#issuecomment-231720311

My own experience is that when compilation is skipped the post-publish script approach (and the `publishOptions > include` approach for that matter) doesn't work (the latter still being very annoying btw :smile: and was *cough* *cough* a missed milestone for RTM *cough* https://github.com/dotnet/cli/issues/1614 :smile:).

Therefore, the only reliable way that I've found to get automatic, guaranteed copying and updating of files in published output is by having a Gulp `watch` task set for those files. Something like this might work for you ...
```javascript
gulp.task('includesFileProcessing', function ()
{
    return gulp.src('<path to app>/Common.Includes/*')
        .pipe(gulp.dest('<path to app>/bin/Release/netcoreapp1.0/win10-x64/publish'));
});

gulp.task('watch', function () {
    gulp.watch('<path to app>/Common.Includes/*', ['includesFileProcessing']);
});
```

**Comment by dmcweeney** [comment]
Thanks @GuardRex ... trying the gulp approach only to discover gulp is no longer part of the template and getting the error "'gulp' is not recognized as an internal or external command"... will try and resolve tomorrow...

How hard can it be to do something so simple...

**Comment by ajaybhargavb** [comment]
@dmcweeney, try removing the `.` from the destination path in mappings.
```json
"mappings": {
"/": {
"include": "../Common.Includes/mySettings.json"
}
```

**Comment by dmcweeney** [comment]
Hi @ajaybhargavb , if I set the dest path to "/" I get the following vs build/publish error:

Path cannot be the empty string or all whitespace.
Parameter name: path
   at Microsoft.DotNet.Tasks.Publish.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()


If I set it to something like "wwwroot" or "wwwroot/AppSettings" its just ignored and the files end up under "bin\Release\net452\win7-x64\Common.Includes".

**Comment by dmcweeney** [comment]
Thanks @GuardRex, finally got gulp going and the gulp watch and copy tasks appear to be working for local dev and publish. Have ye to try it on VSTS online build/release but I think it should be possible.

I hope the dotnet team come up with a better solution for doing this sort of thing though!

**Comment by GuardRex** [comment]
> a better solution for doing this sort of thing

If I'm reading the tea leaves correctly, that will be MSBuild/`.csproj`, where placing folders/files in published output, is much more mature.

**Comment by piotrpMSFT** [comment]
@GuardRex right on!

**Comment by dmcweeney** [comment]
Hi @piotrpMSFT , I see this has been closed - has this been fixed in the latest build or is it been dropped in favor of the @GuardRex gulp workaround? This is a very basic need so asp.net core projects need to have some simple means of doing it.

Thanks

Donal

**Comment by Oceanswave** [comment]
Running into this exact same issue. I can use mappings to copy files from a folder to a subfolder of the output folder but not directly INTO the output folder.

Normally, this would be not too bad, but I'm also p/invoking to a native library. On windows, the DllImport attribute will find dlls in subfolders without their extensions - e.g.  [DllImport('nativelibs/mydll')] but this doesn't work on macOS and Linux.

sooo unless I want to have 3+ separate dll import classes each specifying the subdirectory and the platform-specific library file name, the native libraries need to be in the output folder... which doesn't seem possible with the mappings section in project.json


Am I missing something?

**Comment by piotrpMSFT** [comment]
@dmcweeney, @Oceanswave we've not been able to repro this on preview3 with msbuild. If you have a preview3 repro I'm happy to take a look.

This issue is closed because we're not pursuing a fix on pre-preview3 [project.json] CLI's. If we have a preview3 repro please open a new issue and link this one.
