### ISSUE TITLE
Provide an option to preserve compilation graph during compile

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#392]
Much like we preserve the runtime graph during compile via the `deps` file, and in order to support things like Razor dynamic compilation, we need to provide a mechanism to preserve the package graph used for compilation.

This will be disabled by default, since it increases the metadata in the output, and enabled via a boolean project.json property `preserveCompilationContext` (name?). When this property is set to true, the compilation graph will be included in the `deps` file. Since the shared host already filters down to nodes in the deps file with a `runtime` type, this will not affect the shared host. Managed code will be able to load the deps file and use it to reconstruct the compilation graph in order to allow dynamic compilation using the same references as the original project.

This is needed to fully port ASP.NET MVC from `dnx` to `dotnet`

/cc @pakrym @davidfowl

**Comment by krwq** [comment]
Isn't IL the compilation graph?

**Comment by brthor** [comment]
Is this putting the reference assemblies in the deps file or something else entirely? Trying to understand what the compilation graph is.

**Comment by anurse** [comment]
This is about the reference assemblies. We don't want to build against the runtime assemblies because they are not designed for that purpose.

"Compilation Graph" refers to the package dependency graph used during compilation. Currently, the .deps file contains most (but not all, see #393) of the data from the "runtime graph" (which is the package dependency graph used at runtime. This issue tracks adding compilation data so that the final application can compile new code (i.e. Razor views) with the same reference assemblies the original app was compiled against (which is a major scenario in Web applications).

**Comment by dannyvv** [comment]
If we

**Comment by dannyvv** [comment]
sorry, the button next to the green is not cancel ::):

**Comment by dannyvv** [comment]
If we need a runtime.deps and now a buildtime.deps. 
Wouldn't it be simpler to place the libraries section of project.lock.json?

**Comment by anurse** [comment]
It would, wouldn't it? That's basically what we're looking at as a first pass. Stripping down the project.lock.json to what we need in this context and dropping it to the output.

**Comment by dannyvv** [comment]
so isn't that the libraries section?

**Comment by dannyvv** [comment]
I would like to recommend not to invent another format for this information. 
Either the libraries section for which there is already existing parsing logic, or if that results in too big a file, take the csv style syntax and embed that in the project.lock.json
I'm hoping we can avoid this becoming a proliferation of 'custom' formats and files that has to be placed in the output folder. It might start simple with one file, then two files, then n. If it turns out in a short amount of time we need 2, we'll need n. So lets not encourage a proliferation.

**Comment by anurse** [comment]
No, the libraries section is a list of all libraries in the lock file so it includes libraries that are used in only some targets. We'd want the targets section as well, which is filtered to specific framework/runtime pairs. Also, the lock file is designed to isolate others from the NuGet conventions of `lib/[tfm]/[etc.]` so it lists exactly which relative paths are relevant for a specific purpose.

So it's basically a selection of targets from the targets file, and the libraries section with the flat files list removed (we don't need it) and garbage collected to remove libraries that are no longer present (because the targets that reference them have been removed).

**Comment by anurse** [comment]
@dannyvv I'm in agreement and would generally prefer to just transfer the lock file to the output. There were concerns about reading that in `corehost` at runtime start-up though.

**Comment by dannyvv** [comment]
sorry mixed up the sections again. I indeed meant the targets part.
I can see there are memory and potential extra decoding cost at startup for json vs csv. A typical app would do more IO parsing the lock than loading the binary. Although this would hold true for CLI as well and for CLI it is probably more exasperated since it parsed the file over a dozen times.

**Comment by davidfowl** [comment]
Except this is runtime performance and is a tad more critical than build time performance.

**Comment by dannyvv** [comment]
My fear is just where does it stop. At what point will compile generate many derived file formats from the project.(lock).json.
I.e. for this CsHtml. What about the #Defines that gets passed to CSC, the resources files? etc etc.
