### ISSUE TITLE
Embed full runtime graph data in the deps file

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#393]
In order to support various extensibility scenarios (like locating MVC Controllers or Glimpse Plugins), `dnx` had an API called `GetReferencingLibraries` which allowed you to get a list of all the packages in the project which referenced a particular package. This would allow MVC's controller search process to avoid searching all packages and instead search only the package that reference the MVC package.

We can recreate this API on top of `dotnet` by providing a small amount of additional data in the deps file. By adding the names of dependencies between packages, managed code can (at runtime) reconstruct this graph.

/cc @pakrym @davidfowl

**Comment by piotrpMSFT** [comment]
@anurse, is this coming in today or should we bump to RC?

**Comment by anurse** [comment]
No, bump to RC

**Comment by anurse** [comment]
Happening as part of #1562
