### ISSUE TITLE
Debug symbols are generated if debugType is "none"

### ISSUE THREAD

**Issue by drieseng** [dotnet/cli#3931]
## Steps to reproduce

1. Open a command prompt (or a shell).
2. Navigate to a temporary directory.

   For example:
   ```cd c:\temp```

3. Clone the develop branch of SSH.NET:

   ```git clone https://github.com/sshnet/SSH.NET.git -b develop```

4. Navigate to the .NETCore (.NETStandard) project directory of SSH.NET:

   ```cd SSH.NET\src\Renci.SshNet.NETCore```

5. Execute dotnet:

```
  dotnet restore
  dotnet build -c
```

## Expected  behavior

No .pdb file should be generated in **bin/release/netstandard1.3** as the **release** configuration is defined [here](https://raw.githubusercontent.com/sshnet/SSH.NET/develop/src/Renci.SshNet.NETCore/project.json) with **debugType** "none".
More specifically, the file **C:\Temp\SSH.NET\src\Renci.SshNet.NETCore\bin\release\netstandard1.3\Renci.SshNet.pdb** should not have been emitted.

## Actual behavior

The debug symbol is created at **C:\Temp\SSH.NET\src\Renci.SshNet.NETCore\bin\release\netstandard1.3\Renci.SshNet.pdb**.

## Environment data

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
The supported options for debugType are `portable` and `full`. Did you run across a doc that suggested that `none` is also supported? If so, please do open a documentation bug.

The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

**Comment by drieseng** [comment]
Disabling debug symbols has always been possible using the compilers; the "none" option is also documented [here](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#buildoptions). I'll submit issues against the MSBuild based system, if I can still reproduce it at that point.

**Comment by mairaw** [comment]
This is listed as one of the options in the schema file:
https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/project.json

I'll update the doc and I'll update the issue to update the spec too here: https://github.com/SchemaStore/schemastore/issues/201
