### ISSUE TITLE
Simplify dotnet new -t web

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#3934]
There are a couple of issues with the current “dotnet new -t web” experience:
- The generated app is large and complicated. The generated app includes concepts from .NET Core, ASP.NET Core, MVC, EF Core,  Identity, npm, gulp, and bower. That’s too much for a user to absorb in a getting started experience.
- The generated app requires running an EF migration to fully run. And since the default environment is Production you don’t get an error page to tell you how to do that. You do get an error suggesting switching the environment to Development, but if you do that then Bower based styling breaks because the template only uses the CDN links in production.

Because of these issues if you want to get your first “Hello, world” ASP.NET Core app up and running the process is pretty manual. To fix this I’d like to update the output of “dotnet new -t web” to match the ASP.NET Core Empty template in VS. This is a tactical fix – later we hope to have a variety of templates for different ASP.NET Core scenarios. Making this tactical change now would enable us to dramatically simplify the ASP.NET Core getting started steps.

**Comment by danroth27** [comment]
@DamianEdwards @leecow

**Comment by piotrpMSFT** [comment]
@danroth27 @DamianEdwards if there is a different template that we'd prefer to use in CLI, or an additional template, let's get a PR going.

**Comment by r105m** [comment]
@danroth27 i think, `yo` is very useful tool for generating empty projects. 
And this is very bad idea to integrate trash functionality to dotnet/cli. 
`dotnet new` command is more than enough.

**Comment by watashiSHUN** [comment]
so does this mean `dotnet new` will stick with the MVC? 
I don't see any cons of imitating what VS offers:
1. empty web
2. web api
3. mvc

**Comment by r105m** [comment]
I don't think, that creating of projects is responsibility of **dotnet** command.
How often you create a solution? for every month, year? 
And if you have complex solution structure, do you have much more then one webapi/mvc project within it? I think no. Often you have 1 frontend and several backend projects. 

Dotnet command should not be a combine

**Comment by mairaw** [comment]
The new dotnet new generates several different templates:
![image](https://cloud.githubusercontent.com/assets/12971179/22719553/df54ad34-ed5a-11e6-9ad0-e1613b041723.png)

**Comment by watashiSHUN** [comment]
@mairaw thanks, just tried and it worked~
@r105m hmm...I believe creating project is a key functionality of `dotnet core cli` (otherwise, why allow `dotnet new` anyway)
>How often you create a solution? for every month, year?

I believe ever dotnet core developer needs to create at least one project, you don't think that is often?

>And if you have complex solution structure, do you have much more then one webapi/mvc project within it? 

My point exactly, a single MVC template is not enough...for example I want a webAPI project so I can use angular as frontend: I have a simple [repository of angular cli + dotnet core cli](https://github.com/watashiSHUN/.netCore-Angular2-Template) created by VS2017

since VS does not work on linux, dotnet core cli needs to take a lot of its responsibility to honor cross platform, glad to see the new version

**Comment by r105m** [comment]
This is ugliest solution i ever seen. Who approves it? 
Dotnet command has next responsibilities: 
1. build
2. run 
3. restore  nugets 
4. publish
5. create nuget packages
6. manage project templates. 
7. send telemetry
8. ?

This is absolutely not unix-way where one command has one responsibility. Is anybody knows here about SRP principe? Dotnet has a dependency to xUnit now? Please, tell me that updating of templates is not a reason to update dotnet now. I think, **dotnet** command must be выкинута на мороз and replaced whith 3 or more commands.
