### ISSUE TITLE
how to add readme.txt to root when using dotnet pack?

### ISSUE THREAD

**Issue by AnderssonPeter** [dotnet/cli#3935]
when creating a nuget package with dotnet pack how do i add a readme.txtto the root to use the following https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-displaying-a-readme.txt-file-during-package-installation

## Environment data
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by AnderssonPeter** [comment]
i managed to get this working by adding 
`"files": [ "../../Readme.txt" ],` to my project.json under `packOptions`

**Comment by MCKRUZ** [comment]
Can someone post an example with a project?  I can't seem to get this to work

**Comment by MCKRUZ** [comment]
nothing?
