### ISSUE TITLE
Empty \Program Files\dotnet folder after installation

### ISSUE THREAD

**Issue by atuzovic** [dotnet/cli#3938]
After clean installation of Visual Studio 2015 Enterprise with Update 3 from MSDN, I was not able to run any of the projects previously built with ASP.NET Core 1.0.0 final version. Error message that I was receiving was:

<img width="379" alt="ss1" src="https://cloud.githubusercontent.com/assets/5385262/17127119/74ab9db8-5303-11e6-9730-19c69b11b10d.png">

I have investigated forums, checked issues here, tried everything suggested including full reinstall of everything and follow up repairs, however error was still there. In Control Panel there is nothing listed but these two installations:

<img width="719" alt="ss3" src="https://cloud.githubusercontent.com/assets/5385262/17127149/9ca44522-5303-11e6-8dce-ed15fc313332.png">

I would like also to mention that I had to install Tooling Preview 2 with disabling VSU check because it was telling me that my Visual Studio Update 3 was not present. Command that I used was:
`DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1`

Even though installation was successful, dotnet folder remained empty no matter what I would try to do:
<img width="588" alt="ss2" src="https://cloud.githubusercontent.com/assets/5385262/17127188/e2228ba4-5303-11e6-9cb9-3b6e2a2da410.png">

I've also tried to install SDK Preview 2 only (without Tooling), and that installation would also complete with success even though it would last less than 1 second and folder would still remain empty.

Eventually, I've managed to run my projects by copying entire contents of SDK Preview 3 to my \Program Files\dotnet folder from this archive:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip

I would also like to emphasize that installer of SDK Preview 3 has acted weird in a way that it has created sdk\preview-\* folder, but it did not copy other folders including dotnet.exe file so I was still unable to run projects. 

So right now I am able to continue with work but I feel something is at real mess on my PC. I am not getting any errors that I can show here that would indicate what is wrong. Is there a way to gather relevant information that would help figure out why are installers reporting success even though installation did fail?
## Environment data

`dotnet --info` output:

Product Information:
 Version:            1.0.0-preview3-003215
 Commit SHA-1 hash:  eaa771edca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@atuzovic can you share installation logs for the .NET Core SDK?

I suspect that you do have some pre-preview1 gunk left over on your machine that is throwing off the installer. The logs should help figure out what's going on.

**Comment by atuzovic** [comment]
Sure, I am more than willing to help.

Any particular demands or just pure MSI installation logs?

**Comment by piotrpMSFT** [comment]
Pure install log at the moment. There's not enough context here yet to ask for more...
