### ISSUE TITLE
Scaffolding CLI tool update

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/cli#3946]
The scaffolding tool will need to be updated to reason about the new project model.

/cc: @prafullbhosale @davidfowl

**Comment by eerhardt** [comment]
@mlorbetske - What is "The scaffolding tool" you are referring to?  Is it in this repo?  If the code is in another repo, we should move this issue to where the code is contained.

**Comment by prafullbhosale** [comment]
Scaffolding is currently a project dependency tool `dotnet-aspnet-codegenerator`.
I think the question is about how should the `dotnet xxx` tools adapt to the new project model. 

cc @NTaylorMullen @natemcmaster

**Comment by natemcmaster** [comment]
@prafullbhosale @mlorbetske we've been discussing the same issue for dotnet-ef (see https://github.com/aspnet/EntityFramework/issues/6139).

**Comment by prafullbhosale** [comment]
Created an issue in Scaffolding Repo: https://github.com/aspnet/Scaffolding/issues/281

**Comment by eerhardt** [comment]
Closing this issue, since the referenced code doesn't exist in this repo.
