### ISSUE TITLE
dotnet new CSharp_Web template is missing publish wildcard for areas

### ISSUE THREAD

**Issue by rynowak** [dotnet/cli#3949]
## Steps to reproduce

Create a new app with `dotnet new -t Web` 
Add an 'Areas/Views/Shared' folder and put some `.cshtml` files in there
Do a `dotnet publish` - notice that `Areas` and its content is not copied to publish output

This is because the `publishOptions` don't include `Areas` even though this is a standard MVC feature/project organization.

**Current:**

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },
```

We're planning to update the VS project templates to use a different wildcard that's more all-encompassing - https://github.com/aspnet/Templates/issues/654#issuecomment-233504002

**Fixed:**

```
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshml",
      "appsettings.json",
      "web.config"
    ]
  },
```

**Comment by piotrpMSFT** [comment]
@rynowak do you plan to make a PR for this?

**Comment by rynowak** [comment]
https://github.com/dotnet/cli/pull/3950
