### ISSUE TITLE
Consider embedding the deps file

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#395]
The need for a side-car deps file in shared-host mode is a little annoying. We should consider embedding the file in the Managed Resources of the assembly itself. This would mean that the shared-host would need to load the assembly and read the metadata manually, but I would hope there is some code we could borrow from the CLR to do this ;). Also, we'd want to do this in a way that avoids loading two copies of the managed assembly (once to read the metadata and then once to actually load the assembly). My hope is that calling `LoadLibrary`/`dlopen` to load the library might achieve this since the CLR will use the same api(?) and it will no-op(?).

So obviously there are a few open questions :). Filing this to track them and the work. Right now I'm putting this in Backlog since it isn't required for anything.

/cc @davidfowl @pakrym

**Comment by piotrpMSFT** [comment]
The deps file story has matured significantly since this was created. Please reopen if you feel this is tracking some remaining work.
