### ISSUE TITLE
publish command not copying files to specified output directory

### ISSUE THREAD

**Issue by deathrowe** [dotnet/cli#3951]
## Steps to reproduce

`"publishOptions": {
    "include": [ "**/*.json" ]
  }`

`dotnet publish --configuration Release --version-suffix 45 --output ./bin/output`

Basically just override the default output directory
## Expected  behavior

new folders should be created in the specified output directory
## Actual behavior

only dlls/pdbs are being copied. No new folders are being created.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

I am seeing files copied correctly using the default output directory.

**Comment by deathrowe** [comment]
Looks to **only** be an issue if I use a relative path for the output option

**Comment by brthor** [comment]
@ajaybhargavb

**Comment by ajaybhargavb** [comment]
@deathrowe, could you try without the `./`?
`dotnet publish --configuration Release --version-suffix 45 --output bin/output/`

**Comment by deathrowe** [comment]
ok, without the `./` does work.

If I try `/bin/output` I get the error: Access to the path '/bin/output' is denied. Is this expected?

**Comment by deathrowe** [comment]
if I add `../` the folders are not copied/created like I would expect. Only the .dlls and .pdbs are copied. `dotnet publish --configuration Release --version-suffix 45 --output ../bin/output/`

**Comment by u-abramchuk** [comment]
Hi, I have the same issue. 

In project.json I have
`"publishOptions": {
    "includeFiles": [
      "appsettings.json",
      "web.config"
    ]
  }`

When running 
`dotnet publish` or `dotnet publish -c Release` 
these files are copied to publish folder. 

But when I run 
`dotnet publish -o ..\..\output`
 they are not copied like I would expect.

**Comment by severisv** [comment]
The error occurs when the target project is not specified as an argument

Does not work (files specified in publishOptions in project.json are not copied):
`dotnet publish --configuration Release -o myPublishDirectory src/MyProject`

Works: 
`dotnet publish --configuration Release -o myPublishDirectory src/MyProject ./`

**Comment by piotrpMSFT** [comment]
I've not been able to repro this after migrating to csproj in preview3. If someone has a csproj repro, please share and reopen!

**Comment by jonaskello** [comment]
I have the same issue when using the image `microsoft/aspnetcore-build:1.1.1` and running `dotnet publish src/MyProj --output out --configuration Release`. Running on ubutnu. Nothing gets copied and no error messages.

**Comment by stevedesmond-ca** [comment]
I just hit this too -- is there documentation anywhere that says that the output dir is relative to the project file, not the current working dir?

**Comment by urbanhusky** [comment]
The only hint currently is that the defaults are relative to the project.

`dotnet publish -o` did not treat relative paths relative to the project but to the current directory in previous versions (migrated from 1.1 preview 2.1)

**Comment by lantrix** [comment]
@urbanhusky I've also found the same in [.NET Core 1.0](https://github.com/dotnet/core/blob/master/release-notes/download-archive.md#net-core-10).

I migrated from `1.0.2 with SDK Preview 2 build 3148` to the latest full release `1.0.5 with SDK 1.0.4` and the `--output` also changed from relative to current path to the project path.

@mairaw will those commits you did on dotnet/docs#3042 also apply to any newer documentation for  .NET Core 1.0 (for any security release) as well as .NET 2.0 ?

**Comment by mairaw** [comment]
that's the change I made @lantrix. But if that's not correct, I'm happy to review that PR. I'm still waiting for review on that one from either @livarcocc or @nguerrera.

**Comment by dasMulli** [comment]
I made a last-minute PR (https://github.com/dotnet/cli/pull/7166) but that was too late to get into 2.* so it will have to wait for a major version increment to introduce this now breaking change..

**Comment by lantrix** [comment]
@mairaw Your documentation change is correct to document _current_ behaviour.

**Comment by mairaw** [comment]
cool! Thanks for confirming that @lantrix!

**Comment by jwbats** [comment]
This issue may have made a comeback in .Net Core 3.

The following command produces no files in the specifiout output directory for me:

`dotnet publish ..\..\ -c Debug -r win-x64 -o bin\Debug\PublishOutput`
