### ISSUE TITLE
.NETCore web app with docker in centos7 error 

### ISSUE THREAD

**Issue by vae1314** [dotnet/cli#3965]
## Actual behavior

Hosting environment: Production
Content root path: /dotnetapp
Now listening on: http://0.0.0.0:9999
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://10.16.236.87:8899/api/values
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method DotNetCoreWeb.Controllers.ValuesController.Get (dotnetapp) with arguments () - ModelState is Valid'
info: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
      Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
info: Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler[2]
      Executed action DotNetCoreWeb.Controllers.ValuesController.Get (dotnetapp) in 528.7668ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1487.1519ms 200 application/json; charset=utf-8
warn: Microsoft.AspNetCore.Server.Kestrel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60[0]
      Connection processing ended abnormally
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<!0> System.Threading.Tasks.ValueTask`1.op_Implicit(System.Threading.Tasks.Task`1<!0>)'.
   at Microsoft.AspNetCore.Server.Kestrel.Http.MessageBody.ForContentLength.ReadAsyncImplementation(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Http.MessageBody.Consume(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
## Environment data

`dotnet --info` output:

**Comment by svick** [comment]
Could you include a repro of this error? I think that especially your project.json is going to be important.

`ValueTask<T>.op_implicit` used to exist in the RC2 version of `System.Threading.Tasks.Extensions` and it was used by the RC2 version of `Microsoft.AspNetCore.Server.Kestrel`, but it does not exist anymore in the RTM version. Are you using RC2 version of `Microsoft.AspNetCore.Server.Kestrel` with the RTM version of `Microsoft.NETCore.App`?

**Comment by piotrpMSFT** [comment]
Without a repro, this is not actionable. Please re-open with a repro.
