### ISSUE TITLE
.NET Core class library reference --> System.IO.FileNotFoundException (Newtonsoft.JSON 9.01)

### ISSUE THREAD

**Issue by Legends** [dotnet/cli#3967]
**(VS2015 Update 3 + Patch)**

I have a plain .NET console application (.NET 4.6) and reference a .NET core class library that targets NetStandard v1.3. The class library has a reference to Newtonsoft.JSON.

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "Newtonsoft.Json": "**9.0.1**"
  },
  "buildOptions": { "platform": "anycpu" },

  "frameworks": {
    "**netstandard1.3**": {
      "imports": "dnxcore50"
    }
  }
}
```
The referenced NewtonSoft.JSON package is deployed here:

C:\Users\UserAccount.nuget\packages\Newtonsoft.Json*9.0.1*
The Exception:

> An unhandled exception of type '**System.IO.FileNotFoundException**' occurred in DotNetConsoleApplication.exe
> 
> Additional information: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

The console application adds a reference to the .net core class library directly from folder:

> **NetCore46ClassLibrary\bin\Debug\netstandard1.3**\NetC‌​ore46ClassLibrary.dll

**Comment by svick** [comment]
If you directly reference a DLL, its dependencies are not automatically referenced, .Net Core didn't change anything about that.

You have two choices:

1. Reference your library as a NuGet package, which will automatically include its dependencies. To do that, use `dotnet pack` on the library, then copy the resulting package to a directory that's registered as a NuGet package source and finally reference the package.
2. Reference your library as a DLL, and also manually reference all its dependencies.

**Comment by Legends** [comment]
What I did a dotnet build, dotnet pack on my .net core class library, copied the nuget package to public nuget package folder

> C:\Users\Admin\.nuget\packages\NetCore46ClassLibrary\NetCore46ClassLibrary.1.0.0.nupkg

now I run dotnet restore and it works. 
From the console app I reference the .net core project as project reference. And it references the right lib under netstandard1.3.

But what do you mean when you say reference the package?
Do u mean to reference the package from the console app? How do I reference this nuget package,as it's a custom one...?

**Comment by svick** [comment]
> How do I reference this nuget package,as it's a custom one...?

Like I said, I meant that you should [create a package source from a directory](https://docs.nuget.org/create/hosting-your-own-nuget-feeds#creating-local-feeds). Then you can use NuGet to reference the package, as long as you select that package source.

> Do you mean I should reference all dependencies of the core project also in my console app?

Yes, if you want to reference the library as a DLL, like you did at first.

**Comment by blackdwarf** [comment]
What @svick above is the correct solution to this problem. Closing the issue as "resolved".

**Comment by Legends** [comment]
@svick  Ah ok, through a local feed. Actually it works, I just have to install the nuget package for the .net Core project through a local feed Perfect, now all dependencies resolve correctly. Thank you very much !

**Comment by Legends** [comment]
Hm, the problem here is, I also have to add the Newtonsoft.JSON reference to the referencing project, otherwise it will again not found the reference.

**Comment by Legends** [comment]
One thing to mention here.
If I uninstall the package:` uninstall-package MyNetCoreClassLibrary`
It does not remove all dependencies the package added before!

**Comment by Legends** [comment]
[Here](http://stackoverflow.com/questions/38349276/newtonsoft-json-v9-01-filenotfoundexception-net-core-class-library) I explained the steps how I got it working based on the feedback of svick.
