### ISSUE TITLE
Brew refusing to link openssl

### ISSUE THREAD

**Issue by noelitoa** [dotnet/cli#3968]
## Steps to reproduce
brew update
brew install openssl
brew link --force openssl

## Expected  behavior
Symlinks will be created

## Actual behavior
Warning: Refusing to link: openssl
Linking keg-only OpenSSL means you may end up linking against the insecure,
deprecated system version while using the headers from the Homebrew version.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by nbellocam** [comment]
This is duplicated: https://github.com/dotnet/cli/issues/3964
and is related to this PR https://github.com/Homebrew/brew/pull/597

**Comment by blackdwarf** [comment]
Closing this as a dupe to #3964

**Comment by gamedebug** [comment]
When I executed "brew link --force openssl" on my macOS Sierra 10.12.3, stdout as below:
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

How to fix it???
