### ISSUE TITLE
Equivalent of --force-incremental?

### ISSUE THREAD

**Issue by BrianVallelunga** [dotnet/cli#3973]
Is there a way to force an incremental build? I have a site that uses postcompile for front-end build steps only such as npm install, gulp build, etc. Why should this force non-incremental builds? In a CI system the build time is dramatically increased because I'm forced to rebuild once for every step of the process: compilation, packaging, testing, etc.
## Steps to reproduce

Create an ASP.NET Core site that has a postcompile script that only runs front-end build scripts.
## Expected  behavior

Incremental builds work
## Actual behavior

Incremental builds don't work
## Environment data

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Try out preview3. Incrementality is now vastly improved.
