### ISSUE TITLE
Dotnet restore with VSTS feed fails

### ISSUE THREAD

**Issue by janpieterz** [dotnet/cli#3977]
## Steps to reproduce
- Have at least two projects (one classic .net, one .net core)
- Let both depend on a package on a private VSTS package feed
- Use VSTS build to restore using nuget
- Use VSTS to launch dotnet command line (dotnet restore --verbosity Information --configfile NuGet.config )

## Expected  behavior
Both restores (classic and dotnet) work fine

## Actual behavior
nuget restore goes fine
dotnet restore (sometimes) fails on the VSTS feed with:
```
error: Unable to load the service index for source https://xxx.pkgs.visualstudio.com/DefaultCollection/_packaging/yyy/nuget/v3/index.json.
error:   An error occurred while sending the request.
error:   The parameter is incorrect
```
## Environment data
Please keep in mind this is on VSTS hosted servers.
```
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

Locally I can never reproduce with dotnet restore, unsure what parameter would be incorrect. For reference, the NuGet.config used:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
	  <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="yyy" value="https://xxx.pkgs.visualstudio.com/DefaultCollection/_packaging/yyy/nuget/v3/index.json" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>
```

**Comment by blackdwarf** [comment]
This should go to the Nuget/Home repo as `dotnet restore` uses Nuget xplat client to perform the restore.

**Comment by janpieterz** [comment]
Opened it there, thanks.
