### ISSUE TITLE
VS 2015 Enterprise Update 3.4 14.0.25425.1 Aspnet Core project "Exception from HRESULT: 0x80070002"

### ISSUE THREAD

**Issue by babarqb** [dotnet/cli#3985]
I am using Visual Studio Enterpirse 2015 Version 14.0.25425.1 Update 3.4

1. First i cant able to install DotNetCore.1.0.0-VS2015Tools.Preview2. but after search support i use skip vs check flag. After that it install  but i cant able to show this on Vs2015 help info. 
2. Second i cant able to creat aspnet core  project. Every time i create project it through  "Exception from HRESULT: 0x80070002" 

i just install Fresh installation of Vs2015 update 3 

any soultion ???????????

dotnet --version
1.0.0-preview2-003121

Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Enterprise

Architecture and Modeling Tools   00322-90150-00969-AA420
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-90150-00969-AA420
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-90150-00969-AA420
Microsoft Visual Basic 2015

Visual C# 2015   00322-90150-00969-AA420
Microsoft Visual C# 2015

Visual C++ 2015   00322-90150-00969-AA420
Microsoft Visual C++ 2015

Visual F# 2015   00322-90150-00969-AA420
Microsoft Visual F# 2015

Windows Phone SDK 8.0 - ENU   00322-90150-00969-AA420
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   7.1.00719.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20624.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Python Tools for Visual Studio   2.2.40623.00
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Django Integration   2.2.40623.00
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   2.2.40623.00
Profiling support for Python projects.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by blackdwarf** [comment]
This issue should be filed on https://github.com/aspnet/tooling/issues as that is the appropriate repo. Can you please reopen there? Thanks!
