### ISSUE TITLE
xproj cannot reference csproj that have non AnyCpu platform

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/cli#3986]
## Steps to reproduce

1) Open attached project
2) Compile in Windows through msbuild !!!! SPECIFY PLATFORM x64, CONFIGURATION = Release
3) Inspect failure
## Expected  behavior

Build success
## Actual behavior

It tries to compile library "l" but does not pass platform parameter ("x64")
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-
preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

[w.zip](https://github.com/dotnet/cli/files/399322/w.zip)

**Comment by piotrpMSFT** [comment]
Please move to https://github.com/aspnet/tooling
