### ISSUE TITLE
CI build fails when running dotnet restore

### ISSUE THREAD

**Issue by dend** [dotnet/cli#3987]
## Steps to reproduce
1. Run `dotnet restore` as part of the Jenkins CI process in an **Execute Shell** step.
## Expected  behavior

`dotnet restore` will restore the packages.
## Actual behavior

Fails with:

```
06:22:37 log  : Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.runtime.serialization.primitives/index.json'.
06:22:37 log  : An error occurred while sending the request.
06:22:37 log  :   Problem with the SSL CA cert (path? access rights?)
```
## Environment data

```
16:24:43 .NET Command Line Tools (1.0.0-preview2-003121)
16:24:43 
16:24:43 Product Information:
16:24:43  Version:            1.0.0-preview2-003121
16:24:43  Commit SHA-1 hash:  1e9d529bc5
16:24:43 
16:24:43 Runtime Environment:
16:24:43  OS Name:     ubuntu
16:24:43  OS Version:  14.04
16:24:43  OS Platform: Linux
16:24:43  RID:         ubuntu.14.04-x64
```

I've opened an associated [SO question](http://stackoverflow.com/questions/38736096/jenkins-ci-ssl-ca-error) that covers the issue, but was wondering if I have a configuration problem with the CLI.

**Comment by jasonwilliams200OK** [comment]
Seems like SSL certificate on the system are messed up. Does this solution help: http://askubuntu.com/a/636979? Google "Problem with the SSL CA cert" to find more. It isn't .NET Core or NuGet specific issue, it is the OpenSSL error.

**Comment by livarcocc** [comment]
We haven't heard back in a while. Please re-open if you are still hitting this.
