### ISSUE TITLE
Getting Started with .Net Core for OS X 10.11 Fails to Link SSL (updated documentation)

### ISSUE THREAD

**Issue by maor-eini** [dotnet/cli#3988]
## Steps to reproduce

I Followed the new documentation of how to get started with .Net Core on MacOS and also the related issues before that.

```
brew update
brew install openssl
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

The ln -s command fails to run because /usr/local/lib/ does not exist on my specific environment 
and the documentation does not specify how to overcome this situation.

**Comment by blackdwarf** [comment]
@bartonjs

**Comment by bartonjs** [comment]
I guess we can add a defensive `mkdir /usr/local/lib` step in there...

**Comment by bartonjs** [comment]
@maor-eini Assuming you use the default brew paths, you might want to follow the advice at http://stackoverflow.com/a/38706045/6535399; it just has the caveat that you'd need to repeat it after future installs of dotnet.

**Comment by jamesmontemagno** [comment]
Yes, can we please add this step :) 

mkdir -p /usr/local/lib/

-p would be a nice addition as it may exist.

This also effects other docs such as: https://github.com/Microsoft/vsts-agent/edit/master/docs/start/envosx.md

**Comment by piotrpMSFT** [comment]
@blackdwarf is this going into the next docs update?

**Comment by maor-eini** [comment]
@blackdwarf Thanks for updating the documentation.
I'm closing this issue.
