### ISSUE TITLE
Allow opt-in publishing of reference assemblies

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#399]
When we're doing dotnet publish of web apps, we often need the reference assemblies present. 

This can be a project.json option.

**Comment by weshaggard** [comment]
+1 there are a number of scenarios where I would like to be able to publish a set of reference assemblies as well. In particular for building other build systems, where the still require a flat list of reference assemblies to compile.

**Comment by anurse** [comment]
Yep, the current design is a little up in the air, but the idea is to allow, via a project.json setting (`publishReferenceAssemblies`?) for `dotnet publish` to copy the reference assemblies for all packages used by the application to a `refs` folder in the published output.

Publishing a specific set of reference assemblies that differs from the set the application uses isn't part of this work item right now, but in theory you could achieve that using a dummy project once this feature exists (kinda like how we publish the runtime today during dotnet-cli build: https://github.com/dotnet/cli/tree/master/src/Microsoft.DotNet.Runtime)

**Comment by danroth27** [comment]
@Eilon I believe we need this for Razor view compilation.

**Comment by pakrym** [comment]
This was implemented in https://github.com/dotnet/cli/commit/f05b208ad7b1d4d3c855a0213b1f431ee07cf068
refs folder is created on compile and publish 

There is one related issue https://github.com/dotnet/cli/issues/616

**Comment by danroth27** [comment]
@piotrpMSFT Should this issue be closed?

**Comment by muratg** [comment]
@pakrym Good to close?
