### ISSUE TITLE
dotnet restore --packages does not restore to "packages" dir

### ISSUE THREAD

**Issue by dsgouda** [dotnet/cli#3997]
## Steps to reproduce

Create a new dotnet test project
run dotnet restore --packages "<some_location>" 
This restores packages to <some_location> except xunit.*

If we run restore without packages option and setting the NUGET_PACKAGES env to the packages directory instead all packages are restore to the desired location
## Expected  behavior

All packages should be restored to the specified location
## Actual behavior

Some packages are not restored to the --packages directory
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-003223)

Product Information:
 Version:            1.0.0-preview3-003223
 Commit SHA-1 hash:  9d3b727392

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14377
 OS Platform: Windows
 RID:         win10-x64

**Comment by emgarten** [comment]
This sounds like a NuGet bug, @dsgouda would you file this on: https://github.com/nuget/home/issues

**Comment by SerhiiS-in6k** [comment]
Have the same issue when to try built project, after restore with --packages option, some packages is missing.
