### ISSUE TITLE
dotnet publish: Could not load file or assembly 'Microsoft.DotNet.ProjectModel

### ISSUE THREAD

**Issue by qin-nz** [dotnet/cli#4001]
## Steps to reproduce
dotnet publish
I can publish the same code on one of my PC and fail on the second one.

If I use vs2015 update 3 to debug the project on the second PC,  it says  
`Unable to attach to CoreCLR. 拒绝访问。`   (use dotnet)
or
`Unable to attach to application 'iisexpress.exe' (PID: 3260) using 'DH-SP3'. 拒绝访问。`  (use iisexpress)

`"拒绝访问" means "Access Denied" `

## Expected  behavior
publish: Published to C:\Users\dingyuan\Source\qin-nz\email2rss\Email2Rss.Api\bin\Debug\netcoreapp1.0\publish
Published 1/1 projects successfully

## Actual behavior
Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. 绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
File name: 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.PublishIISCommand.Run()
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.<>c__DisplayClass0_0.<Main>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Server.IISIntegration.Tools.Program.Main(String[] args)
publish: Published to C:\Users\dingyuan\Source\qin-nz\email2rss\Email2Rss.Api\bin\Debug\netcoreapp1.0\publish
Published 1/1 projects successfully

`绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆`  is a mess code. (e.g. decode `GBK` using `UTF-8`). So I don't know what this means.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by GuardRex** [comment]
The prob seems to be with your use of the `publish-iis` tooling. Show your `tooling` and `scripts` sections of `project.json`.

Also note that some devs have been able to clear problems like this by clearing their caches. The easiest way is `nuget locals all -clear`. If you don't have `nuget.exe`, you can get it from the `latest nuget.exe` link at nuget.org.

**Comment by qin-nz** [comment]
Thanks   `nuget locals all -clear` works.

(●'◡'●)

By the way, I don't have `tooling` sections but only `tools`.
```
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
```

**Comment by GuardRex** [comment]
:+1: cool

Yeah ... my bad (I edited the post after I put it up and changed it to "tools") ... It's 2am here and I had about 4 hours of sleep last night. I really need to get some :sleeping: :zzz: sleep.

Your `tools` and `scripts` sections are fine. :wink:
