### ISSUE TITLE
Change default .nuget/package folder .NET Core

### ISSUE THREAD

**Issue by SerhiiS-in6k** [dotnet/cli#4003]
Text from documentation:
`
If not specified, the default NuGet package cache is used. It is found in the .nuget/packages directory in the user's home directory on all operating systems (for example, /home/user1 on Linux or C:\Users\user1 on Windows).
`
Can I change .nuget/packages location?

**Comment by GuardRex** [comment]
Perhaps `NuGetCachePath` environment variable ... http://stackoverflow.com/questions/31557893/howto-disable-nuget-machine-wide-cache

**Comment by jcansdale** [comment]
I think the NUGET_PACKAGES environment variable might be what you're after.

**Comment by SerhiiS-in6k** [comment]
Thanks it really works. but I have one more issue dotnet create two folders .nuget/Nuget and .dotnet. How to prevent to create this folder?

**Comment by jcansdale** [comment]
I don't know about the `.dotnet` folder. Where does this appear?

**Comment by SerhiiS-in6k** [comment]
I tried to use dotnet cli without installation(just launch from the path in a script) . But cli creates two folders:
```
/home/<user>/.nuget
/home/<user>/.dotnet
```
I think it will cause an error because of it may add issues to simultaneous builds on CI.

**Comment by blackdwarf** [comment]
@SerhiiS-in6k are you installing using the `dotnet-install.sh` script?

**Comment by blackdwarf** [comment]
Since there was no action here for a while now, I will close this issue. If the problem still repros, please reopen.
