### ISSUE TITLE
excluding files from publish

### ISSUE THREAD

**Issue by deathrowe** [dotnet/cli#4004]
## Steps to reproduce

`dotnet publish`

`"publishOptions": {
    "include": [ "**/*.json" ],
    "exclude": ["bin", "**/*.pdb"]
  }`
## Expected  behavior

Files of type pdb will not be included in the publish directory output
## Actual behavior

Files of type pdb are included in the publish directory. I'm mostly focused on the pdb file of the current project being included in the output directory.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by piotrpMSFT** [comment]
Moved to sdk repo
