### ISSUE TITLE
Cannot resolve runtime and native assets from dependency context of a class library

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#4005]
I am attempting to solve the problem of creating an AssemblyLoadContext from a class library project (https://github.com/aspnet/EntityFramework/issues/5320) with only 3 inputs: dependency context, nuget package directory, and application base path. (NB: no project context)
## Problem

The build trims "runtimeTargets" from the deps.json file. In order to execute code from an ALC, we need all runtime and native assets.
## Steps to reproduce

Create and compile netstandard project

``` c#
public class Class1 {}
```

``` json
{
    "dependencies": {
        "System.Data.SqlClient": "4.1.0"
    },
    "frameworks": {
        "netstandard1.3": {}
    }
}
```
## Expected

``` json
  "runtime.native.System.Data.SqlClient.sni/4.0.0": {
        "dependencies": {
          "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni": "4.0.1",
          "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni": "4.0.1"
        }
      },
      "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni/4.0.1": {
        "runtimeTargets": {
          "runtimes/win7-x64/native/sni.dll": {
            "rid": "win7-x64",
            "assetType": "native"
          }
        }
      },
      "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni/4.0.1": {
        "runtimeTargets": {
          "runtimes/win7-x86/native/sni.dll": {
            "rid": "win7-x86",
            "assetType": "native"
          }
        }
      },
```
## Actual

``` json
      "runtime.native.System.Data.SqlClient.sni/4.0.0": {
        "dependencies": {
          "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni": "4.0.1",
          "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni": "4.0.1"
        }
      },

      "runtime.win7-x64.runtime.native.System.Data.SqlClient.sni/4.0.1": {},
      "runtime.win7-x86.runtime.native.System.Data.SqlClient.sni/4.0.1": {},
```

cc @davidfowl

**Comment by jcansdale** [comment]
I think I might be bumping into the same issue here:
https://github.com/jcansdale/TestDriven.Net-Issues/issues/7

Have you had any luck creating an AssemblyLoadContext? I hit a bug in that when trying to find a workaround for the above issue.

**Comment by natemcmaster** [comment]
@jcansdale I've had success in creating a fully working AssemblyLoadContext from `Microsoft.DotNet.ProjectModel.ProjectContext` and from [`NuGet.ProjectModel.LockFile`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFile.cs), but not from `Microsoft.Extensions.DependencyModel.DependencyContext`. I'm trying to create a tool that is project-model agnostic, but so far have found that DependencyContext doesn't provide enough information on class library projects.

**Comment by jcansdale** [comment]
I'd be interested to see your `AssemblyLoadContext` code if you have it checked in anywhere. :smile:

**Comment by natemcmaster** [comment]
@jcansdale Checkout https://github.com/dotnet/cli/tree/rel/1.0.0/src/Microsoft.DotNet.ProjectModel.Loader for making a load context from Microsoft.DotNet.ProjectModel.ProjectContext. Bear in mind this only works on the "project.json" project system. I have not yet successfully implemented a version that works with the project system work happening on https://github.com/microsoft/msbuild/tree/xplat or one that is project-system agnostic.

**Comment by jcansdale** [comment]
That's great, thanks. It's good to some real world usage of `AssemblyLoadContext`.

**Comment by piotrpMSFT** [comment]
Moved to core-setup to keep close to dependencycontext.
