### ISSUE TITLE
Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main using 1.0.0-preview2-003121 on Fedora 23

### ISSUE THREAD

**Issue by dcorns** [dotnet/cli#4010]
## Steps to reproduce

run dotnet with any option on Fedora 23 64x and the error above will be displayed
## Expected  behavior

dotnet commands should work
## Actual behavior

Failed to resolve library symbol hostfxr_main, error: dotnet: undefined symbol: hostfxr_main is returned to the console
## Environment data

`dotnet --info` output: this command also returns the same error

**Comment by blackdwarf** [comment]
@dcorns how did you install the SDK? Did you intall all the pre-requisites?

/cc @ellismg

**Comment by dcorns** [comment]
Yes, I followed the directions as given on the core site. Everything went smoothly until I tried to use it.

Dale Corns-
Freelance Developer & Tutor
Www.dalecorns.com
________________________________

**Comment by piotrpMSFT** [comment]
Moved to core-setup since the host is failing to activate.
