### ISSUE TITLE
Resource assemblies don't respect "outputName" attribute

### ISSUE THREAD

**Issue by pieceofsummer** [dotnet/cli#4011]
## Steps to reproduce

1) create directory 'test' for a new project, with basic `project.json` (without `outputName` specified) and empty `Main` procedure.
2) drop some `.resx` file with localizable strings at least for one locale.
3) run `dotnet restore` and `dotnet build`, and make sure build was successful, and there are two dlls created: `test.dll` for main executable and `test.dll.resources` in locale subdirectory.
4) clean results by deleting `bin` and `obj` subdirectories.
5) now add `"outputName": "test-prj"` into `buildOptions` and compile again.
## Expected  behavior

there's `test-prj.dll` in output directory, and `test-prj.dll.resources` in locale subdirectory
## Actual behavior

there's `test-prj.dll` in output directory, and `test.dll.resources` in locale subdirectory
## Environment data

`dotnet --info` output:

1) on Mac OS X:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

2) on Windows:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by brthor** [comment]
Hi @pieceofsummer 

Can you share the full text of the project.json you used when hitting this issue?

**Comment by pieceofsummer** [comment]
Hi @brthor 

Sorry for the late reply. Here's [the entire test project](https://github.com/dotnet/cli/files/421666/test.zip), along with sample .resx files.

Change `outputName` in project.json to see the issue.

**Comment by piotrpMSFT** [comment]
Thanks for the repro @pieceofsummer. I just tested with `preview3` by `dotnet migrate`ing , restoring, and building. Glad to say the issue is fixed :)
