### ISSUE TITLE
Support non-LTS versions of Ubuntu

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/cli#4012]
Developers are not always going to be running LTS versions and there is a potential to create some very frustrating scenarios if dotnet is not available for always-current versions of Ubuntu.

I've mentioned this before in previous tickets, but I'm starting to notice a distinct lack of interest in exploring or at least explaining the decision.

This really does fall into the category of "real world use", and not having the cli available on the platforms developers are most likely to be on doesn't quite make sense.

**Comment by jasonwilliams200OK** [comment]
IMO, #1532 is related, there should be a quick path to wrap up the entire tool chain on any given Unix. At least, various known package manager systems should be incorporated to make it happen for correct dependency resolution on the given platform: Debian ([already implemented](https://github.com/dotnet/cli/tree/rel/1.0.0/packaging/deb)), Yum package manager (for Fedora and CentOS), pacman for ArchLinux, Portage for Gentoo, TCE for Tiny Core Linux, pkgsrc (for NetBSD, Solaris, SmartOS etc.) ([CoreCLR package available upstream](https://github.com/NetBSD/pkgsrc-wip/tree/master/coreclr-git)), FreeBSD package manager, aports for Alpine and xbps for Void Linux etc. Eventually all these will reside in their respective package manager repos, but for the acknowledgement purpose, dotnet team can place the latest copy in the packaging folder at root of this repo side by side Debian package (only having Debian there is quite a bias).

TCE, the Tiny Core Linux support is missing some dependencies (last time I tried was few weeks ago). But for rest of them, all dependencies for CoreCLR and CoreFX are available and I have created gist notes on how to compile for some (Void, Alpine, Gentoo, FreeBSD are ready and TCE is wip). We can further the work by actually creating the package config files for each package manager.

**Comment by leecow** [comment]
@atrauzzi @jasonwilliams200OK 

Thanks for the input and we're definitely interested and actively talking through how to 1) unblock and enable folks as soon as possible and 2) how to make it all easier down the road. Will have more to share on the directions soon. 

/cc @richlander @blackdwarf

**Comment by borgdylan** [comment]
I hope that nothing will break come next October when Ubuntu 16.10 will RTM.

**Comment by piotrpMSFT** [comment]
In general, CLI piggybacks on the platform support policy for https://github.com/dotnet/coreclr and https://github.com/dotnet/corefx.

**Comment by livarcocc** [comment]
Since 2.0, we now have a linux portable version of the runtime/cli that can run on multiple different versions of Linux, depending on their native dependencies.
