### ISSUE TITLE
Do not put version information in debian package name

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/cli#4014]
When installing on Ubuntu, we are currently being told to run:

```
sudo apt-get install dotnet-dev-1.0.0-preview2-003121
```

The package ecosystem supports the notion of versions internally without them having to be part of the published package name.  It would be nice if there was just a meta package available to install the latest `dotnet` and all dependencies.  This would also ensure that auto-updaters will pick up on new releases and automatically install them.

What I'd like to see is the install step above to change to this:

```
sudo apt-get install dotnet-dev
```

or perhaps

```
sudo apt-get install dotnet-dev
```

If a specific version is needed, there are other mechanisms to provide and interpret that metadata within the apt package ecosystem.

**Comment by svick** [comment]
If I recall correctly, the version is included in the package name, so that multiple versions of the package can be installed at the same time.

I think the idea of a metapackage that always installs the latest version makes sense. I think I've heard that idea before, but I can't find the issue now.

**Comment by atrauzzi** [comment]
@svick Gotcha.  Just speaking for Debian alone: You can use `update-alternatives` to maintain multiple versions at once.  This is most commonly done with the JDK. Although I think it only locks onto major versions.  Which might be a nice compromise?

Lots more meta packages hiding in here for sure though.

**Comment by blackdwarf** [comment]
@atrauzzi can you share some more details on how that works?

**Comment by atrauzzi** [comment]
@blackdwarf - 100% not trying to "RTFM" you, but I think this link does a pretty good job of introducing things: http://manpages.ubuntu.com/manpages/precise/man8/update-alternatives.8.html

I don't know how it works internally, I'm simply aware of it as an option.

**Comment by blackdwarf** [comment]
@atrauzzi RTFM-ing is perfectly fine. :) Will read through it. I was looking for a decent way to improve the experience.

**Comment by piotrpMSFT** [comment]
@atrauzzi thanks! update-alternatives is not quite what we're after, though. The dotnet host already knows how to select the right framework version and needs to be able to do this on the fly. `update-alternatives`, as I understand, forces the user to figure out which version of `dotnet` they want and then to manually update symlinks with a command. We need both alternatives to be installable at the same time, and that an upgrade does not remove the previous. Any ideas, other than embedding the version numbers as we are?

**Comment by atrauzzi** [comment]
@piotrpMSFT - Right, yeah I've been learning a bit about the platform-type dependencies in `project.json`.

Maybe help me understand for a second -- but aren't frameworks now installed as dependencies?

**Comment by piotrpMSFT** [comment]
These SxS installs ARE that cache :)

Its also possible to package the full framework with the app, but with obvious size and portability drawbacks...

**Comment by atrauzzi** [comment]
I guess what I'm thinking is if `dotnet` is going to download and install the frameworks as part of normal operation, what exactly are we versioning?

The `dotnet` command itself as I understand it is just a suite of bootstrap and should always just be "the latest version".

**Comment by blackdwarf** [comment]
@atrauzzi we are versioning 3 things:

1. The CLI
2. The runtime that the CLI needs
3. The host policy file that the host need

All of the 3 above things can be installed side-by-side in a known location. The host has a convention-based way to find the SDK, the policy file and the shared runtime based on their install location. The install location looks something like this:

```
- dotnet*
- shared/
    - Microsoft.NETCore.App/
        - 1.0.0/
        - 1.0.1/
        - 1.1.0/
- sdk/ 
    - 1.0.0-preview2-003121/
    - 1.0.0-preview3-004056/
- host
```

Every time you install a new version of the shared runtime, for example, we "slot" the new version under the `$prefix/shared/Microsoft.NETCore.app/` directory. This is why we have version numbers in the package.

Now, I seem to remember when I looked a couple of months back on how to fix this that `clang` has a non-versioned package, e.g. `clang` and a versioned one, e.g. `clang3.6`. When you do `sudo apt-get install clang` you get the latest, that is `clang3.6` but you can also install a specific one. 

Does that sound familiar? Did I understand what they are doing properly? Any input here would be very valuable, as I would like to remove the version number from the package name if possible as well, but we need to have the side-by-side described above working.

**Comment by atrauzzi** [comment]
Yeah, this actually happens for a few things. You might also look at the Ruby and Java packages as well.

They version in the repository, but have a metapackage that is always pointing to "latest".  That way if someone just wants to ride the razor's edge, they install the metapackage.  If they need to freeze it, they go for the specific version.

**Comment by piotrpMSFT** [comment]
@atrauzzi we looked into doing the same. The concern is that updating the metapackage would uninstall the previous metapackage's references and break previously running apps. Thoughts on how to manage that?

**Comment by atrauzzi** [comment]
Is it possible that this would fall under "you got what you asked for"?  If someone wants a specific version, they wouldn't install the metapackage at that point as it will be implied that it's going to roll (sometimes only within a major version).

**Comment by svick** [comment]
@piotrpMSFT What if the default templates for .Net Core projects did not depend on a specific version of the SDK? I get that it goes against the currently recommended practice of always specifying versions of packages exactly, but it would avoid this problem and it would also made upgrading to a new SDK easier in general.

**Comment by piotrpMSFT** [comment]
It's not just SDK. The runtime also gets affected. Imagine that you upgrade and your 1.0 CoreFx is replaced with 2.0 :-/

**Comment by blackdwarf** [comment]
@atrauzzi so once you install the metapackage, you would have to always use the specific version named package moving forward?

**Comment by piotrpMSFT** [comment]
This obviously needs to be solved. We just need to identify the right mechanics to do it...

**Comment by blackdwarf** [comment]
@piotrpMSFT yes. We need to investigate more the metapackage behavior, esp. w.r.t installing and removing bits that it installs.

**Comment by atrauzzi** [comment]
The metapackage will install and point to the latest available version -- always.  All the symlinks and paths would constantly resolve to the latest installed version.  When package managers scan for updates, they'll pick up new releases and automatically install them, updating all symlinks.  Nobody would be surprised by this.

If that behaviour is not desired, then you set up a package for every major version.  If someone needs to lock to version `1.0`, they install `dotnet-1.0`.  Not the more general `dotnet` metapackage.  It's just a matter of explicitly selecting the correct one for your needs, attempting to protect users from themselves will just inconvenience other legitimate cases.  You want the least amount of automatic behaviour and you don't want to prematurely corner people into specific options.

**Comment by blackdwarf** [comment]
@atrauzzi we don't want to prematurely corner people, we just want to figure out a solution where they don't accidentally get broken. 

So, if I understand your post above correctly:

1. The user runs `sudo apt-get install dotnet`
2. The user gets 1.0.0
3. We release 2.0.0
4. User runs `sudo apt-get update` followed by `sudo apt-get install dotnet`
5. They get upgraded to 2.0.0

What happens to 1.0.0? Is it uninstalled?

**Comment by atrauzzi** [comment]
If I can just briefly tweak your steps before answering:

1. The user runs `sudo apt-get install dotnet`
2. The user gets 1.0.0
3. We release 2.0.0
4. User runs `sudo apt-get update` followed by `sudo apt-get upgrade`
5. They get upgraded to 2.0.0

In the case of the meta package, 1.0.0 is uninstalled.  If however they explicitly `sudo apt-get install dotnet-1`, it's in there not as a dependency of `dotnet`, but as something the user is requesting directly (the system depends on it, not another package).

**Comment by blackdwarf** [comment]
@atrauzzi sorry to be away from this for a month. 

So, to summarize, the below is something that *could* work for DEB packages:

1. Have a `dotnet` package that is always the latest.
2. Have a `dotnet-<version>` package (the actual format of the name is orthogonal) that would install a specific version encoded in the name.
3. Upon any manipulation of the versionless package, any previous version will get removed.
4. To get more than one version, the user would have to install a specific version. 

One question that pops to my mind w.r.t to the above is the interplay between versioned named package and versionless. That is, let's imagine the following:

1. User installs dotnet-1
2. We then ship a new version
3. User does `sudo apt-get update` and `sudo apt-get install dotnet`
4. ???

I guess that we control, within the package definition, where the package contents/payload end up, right? So in this situation versionless would still end up in the right place. 

Also, @atrauzzi do you think this approach would work for RPMs?

**Comment by atrauzzi** [comment]
Versionless will just be a metapackage that points to the current latest version according to the desired support policy that metapackage title represents.

So you might have (I'm making up version numbers):

`dotnet-lts` -> `dotnet-1.0.0`
`dotnet-current` -> `dotnet-1.1.0`
`dotnet-1.1.0` -> binary goodness
`dotnet-1.0.0` -> binary goodness
`dotnet-2.0.0` -> binary goodness

Some scenarios:

## Specific version installed (your example I believe)
 1. User installs `dotnet-*.*.*`
 2. **Any** new version ships
 3. User updates
 4. Nothing happens.

## Current metapackage installed
 1. User installs `dotnet-current`
 2. `dotnet-1.1.0` is pulled in
 3. New version `dotnet-1.2.0` ships
 4. User updates
 5. `dotnet-1.1.0` is removed
 6. `dotnet-1.2.0` is installed

## LTS metapackage is installed
 1. User installs `dotnet-lts`
 2. `dotnet-1.0.0` is pulled in
---
### Scenario 1
 3. New version `dotnet-1.2.0` ships
 4. User updates
 5. Nothing happens
---
### Scenario 2
 3. New version `dotnet-2.0.0` ships and `dotnet-lts` and `dotnet-current` metapackages are updated
 4. User updates
 5. `dotnet-1.0.0` is removed
 6. `dotnet-2.0.0` is installed

_I'm going under the assumption that major versions remain backwards compatible.  Your policies may differ, in which case, tweak my examples to suit._

The most striking thing here is that users could see themselves automatically rolled up from `1` to `2`.  But this would be because they opted-in to always have the latest and greatest.  Most of the time that's probably the right thing to do as backwards compat is quite strong?  Correct me if I'm wrong :)
If users were concerned about being rolled forward too quickly or to an unsupported version, then they can always skip out the metapackage and install the specific version.  They should also be able to maintain side-by-side installation by installing any combination of specific versions and metapackages.

I hate doing this to him as it's not the first time, but I'm going to ping @directhex as he's well experienced with these things.  Might also be able to correct anything I've got wrong.

**Comment by blackdwarf** [comment]
@atrauzzi wow, this is great, thanks. Let me noodle on it a bit and try to map out what it would take for us to try something like this.

**Comment by piotrpMSFT** [comment]
I'm liking where this is going...

**Comment by blackdwarf** [comment]
@piotrpMSFT thought you might. 😉 Will assign to me since I wanted to go through our code that generates DEB packages anyway.

**Comment by directhex** [comment]
@atrauzzi this seems sane, from a cursory examination. I don't see any glaring errors, at least.

**Comment by tmds** [comment]
https://github.com/dotnet/docs/pull/4538 describes an updated set of packages including packages without version numbers that upgrade.

**Comment by tmds** [comment]
I think this can be closed by the recent update to https://docs.microsoft.com/en-us/dotnet/core/build/distribution-packaging.
