### ISSUE TITLE
PublishEnvironmentName and MSDeploy

### ISSUE THREAD

**Issue by dmcweeney** [dotnet/cli#4015]
## Steps to reproduce

I am trying to publish my ASP.Net Core App to developer account on Azure from VS. 
I have set the PublishEnvironmentName env to Development so that my Development environment is running on the target Azure App Service.

However after deployment the Azure site still thinks it is running Production environment.
## Expected  behavior

I would have expected that the deployment would have set the ASPNETCORE_ENVIRONMENT = Development on the target Azure App Service.
## Actual behavior

However after deployment the Azure site still thinks it is running Production environment.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-003208)

Product Information:
 Version:            1.0.0-preview3-003208
 Commit SHA-1 hash:  76058bea60

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Moved to aspnet/tooling repo
