### ISSUE TITLE
Standardize on a TFM for aot and non-aot Framework Libraries

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#402]
Currently aot libraries exist under the TfM `netcore50`, whilst non-aot libraries exist under the TfM `dnxcore50`

The aot libraries are needed to compile apps with CoreRT. Currently we include a hardcoded list of aot libraries that are compiled into every app when doing native compilation. This is blocking scenarios beyond Hello World.

To move forward with proper framework dependency compilation for `dotnet compile --native` we should consolidate these TfMs. This will reduce the complexity of acquiring these aot libraries, and improve the user experience in doing so.

This will unblock #255 

/cc @piotrpMSFT @weshaggard @gkhanna79

**Comment by weshaggard** [comment]
We need a TFM for for dotnet-cli/netstandadard or what ever we end up with and then we can use that in combination with the aot RID to uniquely select assets for the --native option.

**Comment by brthor** [comment]
Thanks @weshaggard 

Do you know the status of this TFM transition or who I could follow up with?

**Comment by Petermarcu** [comment]
@ericstj who is working with the NuGet team to get support added for the netstandard tfm's. Once NuGet supports them we can move a bunch of the rest of the system to it. For now, I think we can use the dotnet?? tfm's plus the aot RID to get these assets.

**Comment by ericstj** [comment]
Nuget work is being tracked in https://github.com/NuGet/Home/issues/1691. @davidfowl enumerated the work here: https://github.com/dotnet/corefx/issues/4367

Until that is done you can use "dotnetX.Y".  We'll need to do a mop up when the name change happens, but I expect NuGet to support both for some time to aide in transition.

**Comment by blackdwarf** [comment]
Since the TFMs have changed significantly as we approached RC2 and seeing as how CoreRT bits are not shipped with the CLI anymore, I'm closing this. Reopen if still needed.
