### ISSUE TITLE
dotnet pack doesn't include files

### ISSUE THREAD

**Issue by MCKRUZ** [dotnet/cli#4021]
## Steps to reproduce

Create a .net solution that has a readme.md file at the base, then create a project.json file like so

```
                "files": {
                    "includeFiles": ["readme.md"],
                    "mappings": {
                        "readme.md": "readme.md"
                    }
                }
```
## Expected  behavior

Readme.md will be inside the installed project
## Actual behavior

readme.md is NOT inside the installed project
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@MCKRUZ can you try to use `packOptions`?

**Comment by piotrpMSFT** [comment]
Moved to nuget/home
