### ISSUE TITLE
dotnet restore unable to resolve latest dependency

### ISSUE THREAD

**Issue by deathrowe** [dotnet/cli#4026]
I have noticed that after I change the major version of a dependency, running `dotnet restore` will fail trying to resolve the latest dependency. I have verified that the nuget source url does contain the correct version.

If I specify the exact version (2.0.0-45) the `dotnet restore` command will work successfully.

## Steps to reproduce

`"dependencies": {
	"my.package.name": "2.0.0-*"
}`

`dotnet restore` same result with or without the `--no-cache` option

## Expected  behavior
I would expect the latest package of my dependency to be downloaded. (2.0.0-45)

## Actual behavior
the  `dotnet restore` command fails with error:
`Errors in c:\workspace\src\directory\project.json
    Unable to resolve 'my.package.name (>= 2.0.0)' for '.NETFramework,Version=v4.5.1'`

Output:
`trace: Restoring packages for .NETFramework,Version=v4.5.1...
info :   GET http://company.artifactoryonline.com/company/api/nuget/virtual/FindPackagesById()?id='my.package.name'`

I did verify that this URL does return valid xml with 17 different package versions, two of which are greater than 2.0.0.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

I also have seen this fail in a windows 7 environment and on a mac.

I'm also not sure if this is a cli issue or a nuget issue.

**Comment by patrickjamesbarry** [comment]
We have run into this as well. It is concerning because we do not want to always specify the EXACT version of our dependencies, as our build pipeline should be grabbing the latest where desired. Is this a nuget or dotnet issue?  @brthor @emgarten

**Comment by emgarten** [comment]
This is looks like a NuGet issue, it should be filed on https://github.com/NuGet/Home/issues

**Comment by blackdwarf** [comment]
I will close this issue since @emgarten correctly stated that it should be filed under Nuget. Thanks!
