### ISSUE TITLE
dotnet core on fedora 24

### ISSUE THREAD

**Issue by r105m** [dotnet/cli#4029]
Hi, i'm working with fedora 24 and i need dotnet core on it. I don't like 'self builded' apps and i think, we need add builds for f24. I tried to use build from f23, but it looks like new kernel (4.6.*), is not supported by dotnet.

What can i do for support f24 by dotnet core? 
Thanks

**Comment by svick** [comment]
The kernel 4.6 problem in .Net Core 1.0 is known and has already been fixed (https://github.com/dotnet/coreclr/issues/6016), so I *think* you can expect .Net Core to work on kernel 4.6 in [the 1.0.1 version planned for August](https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/#user-content-101-august-2016).

Though it looks like .Net Core CLI does not currently build on Fedora 24 (https://github.com/dotnet/cli/issues/3717). If you're willing to help with that, I think you should focus your attention on that issue.
