### ISSUE TITLE
dotnet pack with --version-suffix option replaces dependency *'s

### ISSUE THREAD

**Issue by deathrowe** [dotnet/cli#4030]
## Steps to reproduce

`dotnet pack  --version-suffix 15`
`"version": "2.0.0-*"
## Expected  behavior

the version of my nuget package will be changed to 2.0.0-15
## Actual behavior

the version of my nuget package is changed to 2.0.0-15 but any dependencies I have using the latest versioning (x.x.x-*) are also changed to version 15.

project.json
`"dependencies": { "my.dependency.name": "1.0.0-*"}`

.nuspec file

```
<dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="my.dependency.name" version="[1.0.0-15, )" />
      </group>
</dependencies>
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003223)

Product Information:
 Version:            1.0.0-preview3-003223
 Commit SHA-1 hash:  9d3b727392

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

Also reproducible on Windows with same version

**Comment by brthor** [comment]
@deathrowe This behavior is intentional to allow a common version suffix to flow through P2P dependencies after they are packed. 

If this behavior is getting in the way, one way you could get around this is to call `dotnet pack

**Comment by plioi** [comment]
I'm not sure we're talking about the same thing. In the bug report, it's not a project dependency that's being garbled, but an attempt to get the most recent build of some arbitrary other third party dependency. Your own version suffix has nothing to do with external dependencies.

**Comment by piotrpMSFT** [comment]
Thanks for clarifying @plioi!

I'm going to move this to the NuGet repo to make sure the scenario is covered.
