### ISSUE TITLE
Add Multiple Source Paths (xproj / updated csproj format)

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/cli#4033]
## Steps to reproduce

Please see https://github.com/dotnet/cli/issues/4022#issuecomment-239043212
## Expected  behavior

I expect to be able to share .cs files across multiple platforms
## Actual behavior

I can't

OK, so the xproj format seems to have been an experimental format that will soon be ditched in favour of xproj like functionality in the csproj format. That's fine. As you can see in the thread I mentioned, the xproj format is fraught with difficulties when you are trying to share .cs files across many different target platforms.

I have a simple proposal that will solve all the issues in one fell swoop.

**The new project format (whatever that may be - xproj, csproj), should allow for multiple source paths.** 

By default, when we create a new xproj project, it automatically includes all the files in that folder. What would be really great in the new format is if it were possible to recursively add folders from other projects. This would make sharing code across platforms much easier. We could store all shared code in one central location, and then we could reference this code from the other platform specific projects. Then, in the platform specific projects we could add the source files which are specific to the platform.

This would neatly wrap up the new xproj style functionality, and solve the issue where we can't have two project files for different platforms in the same folder.

**Comment by piotrpMSFT** [comment]
This is done in preview3. Take a look at the default app template:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Special attention to:

```
<Compile Include="**\*.cs" />
```

You can add additional <Compile> items using fairly arbitrary globbing patterns, including `..\`. Give it a shot and let us know if you find any issues!
