### ISSUE TITLE
dotnet.exe launches in an infinite loop of dotnet is executed from a postcompile script

### ISSUE THREAD

**Issue by joelday** [dotnet/cli#4039]
## Steps to reproduce
1. Add "dotnet pack" to a new "postcompile" script.
2. Attempt to build from Visual Studio

## Expected  behavior
If build fails, build stops. Either way, Visual Studio can cancel the build.

## Actual behavior
Package restore now fails.
Visual Studio hangs indefinitely when attempting to cancel the build.
An infinite number of dotnet.exe processes are started.

## Environment data
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by brthor** [comment]
@joelday You should be able to work around this by adding "--no-build" to your dotnet pack invocation.

**Comment by joelday** [comment]
@brthor Thanks! I figured that out pretty quickly, but yikes, that was a lot of processes... :)

**Comment by brthor** [comment]
Glad you got it figured out, going to close this out :)

**Comment by dzumbuehl** [comment]
@brthor I have the same behavior with dotnet run where I don't have a `--no-build` option

**Comment by piotrpMSFT** [comment]
@dzumbuehl can you open an issue to track adding `--no-build` to run, and expand a bit on the scenario in which we want to be able to invoke `run` from a post-compile script?
