### ISSUE TITLE
Publish CoreRT Framework Libs on Nuget/Myget and remove AppDepSDK

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#404]
Today CoreRT framework libs are included in the `AppDepSDK` NuGet package. This only includes a small subset of libraries, and does not provide any functionality for a user to opt in or out of specific libraries.

We should instead publish these libraries on nuget/myget and allow them to be referenced like other framework libraries in the project.json

The resolution of this is heavily tied to the resolution of #402 and is another step in unblocking #255 

/cc @schellap @gkhanna79 @weshaggard

**Comment by weshaggard** [comment]
I expect a number of these libraries, in particular the System.Private.* libraries, may still remain in some runtime level package, similar to how mscorlib is in the CoreCLR runtime package. However we do still need a TFM/RID combination to be able to ship the higher level assemblies in our other library packages.

**Comment by blackdwarf** [comment]
@brthor I believe this work was done? If not, I think we should move this over to dotnet/corert, yes?

**Comment by brthor** [comment]
I don't recall this work being done, but yes it should move to corert.
