### ISSUE TITLE
'dotnet build' fails on Ubuntu, redstone 1

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#4045]
## Steps to reproduce

On a Windows Anniversary Update machine, follow [the steps for Ubuntu 14](https://www.microsoft.com/net/core#ubuntu) to install dotnet CLI:

```
dotnet new
dotnet restore
dotnet build
```
## Expected  behavior

A successfully built project
## Actual behavior

A failed build:

```
dotnet build
Project dotnet (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling dotnet for .NETCoreApp,Version=v1.0
Success
/usr/share/dotnet/dotnet compile-csc @/home/andrew/dotnet/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.1061670
```

Note that although errors and warnings are 0, there is in fact an error printed, and there is no primary output so 'dotnet run' fails.
## Environment data

`dotnet --info` output:

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by frandi** [comment]
I've experienced the same issue - same environment.

**Comment by soeleman** [comment]
I have similar error on _Bash on Ubuntu on Windows_ 
The fix is install package [mono-complete](http://packages.ubuntu.com/trusty/mono-complete)

**Comment by AArnott** [comment]
@soeleman's workaround worked for me. But why would mono be required for dotnet to work? And if so, why isn't it chained in when I install the dotnet package?

**Comment by aliudmilov** [comment]
@soeleman The workaround did not work for me: I'm .NET Command Line Tools (1.0.0-preview2-003131) and trying to run on _Bash on Ubuntu on Windows_. Any ideas?

**Comment by koenigsbier** [comment]
Same CLI version here: 1.0.0-preview2-003131 and installing mono-complete doesn't fix the issue on Bash on Windows 10

**Comment by likesea** [comment]
same error on Bash on Ubuntu on windows.
dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by zadjii-msft** [comment]
I too ran into this on WSL/Ubuntu 14.04, after a few successful and unsuccessful builds, I would only receive the following when trying to build ANY dotnet project
```
zadjii@migrie-desktop:~/dev/scratch/test-dotnet$ dotnet run 2>&1
Project test-dotnet (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling test-dotnet for .NETCoreApp,Version=v1.0
Success
/usr/share/dotnet/dotnet compile-csc @/home/zadjii/dev/scratch/test-dotnet/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.1138440
```

The solution was as @soeleman said, install `mono-complete`. No idea why though.

**Comment by aliudmilov** [comment]
Guys, after the restart of the machine everything was fine (and after installing mono-complete).
Just to let you know.

**Comment by zadjii-msft** [comment]
So, after coming back to my machine this morning (and after a reboot), I'm finding that once again, `dotnet build` is failing inexplicably, even for a hello world. Creating a brand new directory, and running `dotnet new`; `dotnet restore`; `dotnet run` fails, with the mysterious `Compilation 0 Warning(s) 0 Error(s)` message. I have `mono-complete` installed.
``` sh
zadjii@migrie-desktop:~/dev/scratch/wat$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
zadjii@migrie-desktop:~/dev/scratch/wat$ dotnet --version
1.0.0-preview2-003131
zadjii@migrie-desktop:~/dev/scratch/wat$
```

**Comment by icanhasjonas** [comment]
`sudo apt install build-essential` did the trick for me
(I assume `mono-complete` depends on some of the same packages)

.. (also installed `nodejs` but I believe that's unrelated)

**Comment by livarcocc** [comment]
This is an issue in the Subsystem itself. This SystemNative_ForkAndExecuteProcess is failing with a errno == ENOMEM. The linux subsystem folks will look into this.

**Comment by AArnott** [comment]
Thanks.

**Comment by koenigsbier** [comment]
Any other github issue to follow progression of this issue? I'd like to be aware when this is fixed. Thanks

**Comment by zadjii-msft** [comment]
@koenigsbier I found two BashOnWindows issues that are probably the right ones to look at.

https://github.com/Microsoft/BashOnWindows/issues/520
https://github.com/Microsoft/BashOnWindows/issues/1178 (This is probably a dupe)

Not a whole lot of discussion in there, but something to keep your eye on.
