### ISSUE TITLE
1.0.0-featmsbuild... is "earlier" than 1.0.0-rc2/1.0.0-preview

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#4048]
## Summary

When using builds in the `1.0.0-featmsbuild...` line of releases, Semantic Version comparisons think that they predate `1.0.0-preview...` releases. Specifically, Visual Studio thinks that the version number refers to a DNX version (since all SDK versions less than `1.0.0-preview` represented DNX versions) and tries to locate a DNX runtime.

I'm concerned this may just be one symptom of the underlying semantic version ordering problem. The problem will go away once these changes land in a `1.0.0-previewN` release (or later), but for now it's somewhat disruptive.
## Steps to reproduce
1. Create a .NET CLI project
2. Put a global.json above it with `sdk.version` set to `1.0.0-featmsbuild-003395`
3. Open the project in VS
## Expected  behavior

The project opens
## Actual behavior

The below error message, and IntelliSense, etc. are broken

![image](https://cloud.githubusercontent.com/assets/7574/17682564/37195fa4-6301-11e6-8daf-5ca4614e6869.png)
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-featmsbuild-003395)

Product Information:
 Version:            1.0.0-featmsbuild-003395
 Commit SHA-1 hash:  308f49c32e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14894
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by anurse** [comment]
This is actually pretty hard to work around since the Tooling doesn't have a way to disable it's check (@BillHiebert can correct me, but it sounds like there isn't a way to do this). Would it be feasible to look at changing the version suffix to something that sorts AFTER "r"? What's the ETA on moving this to the main "preview" branch? Also, we'll need to keep this in mind when setting the tag for "RC", since I believe tooling treats "rc1" as a DNX release.

/cc @davidfowl @piotrpMSFT

**Comment by livarcocc** [comment]
We have moved to rel/1.0.0 and this is shipping as preview3.
