### ISSUE TITLE
Figure out where Native shims will be published and how to consume them.

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#405]
For Context https://github.com/dotnet/corefx/issues/4572

Native shims in the form of static libraries need to be published somewhere and consumable for the `dotnet-compile-native` and `ilcompiler` toolchains.

These libraries need to be linked into the application during native compile.

This is another step in unblocking #255 

/cc @schellap @gkhanna79

**Comment by andschwa** [comment]
I ran into this in #505. It would appear that the shim I need is at least published in `runtime.ubuntu.14.04-x64.runtime.native.system`, but I can't depend directly on that long-term.

**Comment by brthor** [comment]
@andschwa This issue is tracking publishing the native shims in static library format. This is separate from the issue in #505

**Comment by gkhanna79** [comment]
@brthor The shim plan should account for both the static and dynamic versions of the shim libraries.

**Comment by blackdwarf** [comment]
Since this is unblocking #255 and that will move to dotnet/corert, I will be moving this as well.
