### ISSUE TITLE
Update to latest NuGet

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#4052]
CLI should update the nuget libraries it's using to 3.5.0-rc1.  This is needed for the latest framework mappings.

/cc @rrelyea @piotrpMSFT @weshaggard

**Comment by livarcocc** [comment]
We have been updating the Nuget Libraries in the CLI quite frequently lately. Today we just moved to 3.6.0-rc-1954

**Comment by ericstj** [comment]
Thanks.
