### ISSUE TITLE
Problem updateing dotnetcore

### ISSUE THREAD

**Issue by AndrewKralovec** [dotnet/cli#4056]
## Steps to reproduce
Followed steps [here](https://www.microsoft.com/net/core#ubuntu) 

## Expected  behavior
suppose to have dotnet preview2

## Actual behavior
Shows i have dotnet preview1

## Environment data
andrew@andrew-PC:~$ dotnet --version
1.0.0-preview1-002702
andrew@andrew-PC:~$ dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
andrew@andrew-PC:~$

**Comment by blackdwarf** [comment]
@AndrewKralovec did the installation succeed?

**Comment by AndrewKralovec** [comment]
andrew@andrew-PC:~$ sudo apt-get install dotnet-dev-1.0.0-preview2-003121
Reading package lists... Done
Building dependency tree        
Reading state information... Done
The following package was automatically installed and is no longer required:
  gradle-2.14.1
Use 'apt-get autoremove' to remove it.
The following extra packages will be installed:
  dotnet-host dotnet-hostfxr-1.0.1
  dotnet-sharedframework-microsoft.netcore.app-1.0.0
The following NEW packages will be installed:
  dotnet-dev-1.0.0-preview2-003121 dotnet-host dotnet-hostfxr-1.0.1
  dotnet-sharedframework-microsoft.netcore.app-1.0.0
0 upgraded, 4 newly installed, 0 to remove and 14 not upgraded.
Need to get 0 B/39.7 MB of archives.
After this operation, 108 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package dotnet-host.
(Reading database ... 1080244 files and directories currently installed.)
Preparing to unpack .../dotnet-host_1.0.1-1_amd64.deb ...
Unpacking dotnet-host (1.0.1-1) ...
Selecting previously unselected package dotnet-hostfxr-1.0.1.
Preparing to unpack .../dotnet-hostfxr-1.0.1_1.0.1-1_amd64.deb ...
Unpacking dotnet-hostfxr-1.0.1 (1.0.1-1) ...
Selecting previously unselected package dotnet-sharedframework-microsoft.netcore.app-1.0.0.
Preparing to unpack .../dotnet-sharedframework-microsoft.netcore.app-1.0.0_1.0.0-1_amd64.deb ...
Unpacking dotnet-sharedframework-microsoft.netcore.app-1.0.0 (1.0.0-1) ...
Selecting previously unselected package dotnet-dev-1.0.0-preview2-003121.
Preparing to unpack .../dotnet-dev-1.0.0-preview2-003121_1.0.0-preview2-003121-1_amd64.deb ...
Unpacking dotnet-dev-1.0.0-preview2-003121 (1.0.0-preview2-003121-1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up dotnet-host (1.0.1-1) ...
Setting up dotnet-hostfxr-1.0.1 (1.0.1-1) ...
Setting up dotnet-sharedframework-microsoft.netcore.app-1.0.0 (1.0.0-1) ...
Setting up dotnet-dev-1.0.0-preview2-003121 (1.0.0-preview2-003121-1) ...
This software may collect information about you and your use of the software, and send that to Microsoft.
Please visit http://aka.ms/dotnet-cli-eula for more information.
andrew@andrew-PC:~$ dotnet --version
1.0.0-preview1-002702
andrew@andrew-PC:~$

**Comment by blackdwarf** [comment]
Hm. Did you by any chance create a manual symlink? can you do a `which dotnet` to see where it is resolving from?

/cc @brthor

**Comment by AndrewKralovec** [comment]
andrew@andrew-PC:~$ which dotnet
/usr/local/bin/dotnet

**Comment by brthor** [comment]
`/usr/local/bin/dotnet`

The debian package places the symlink at `/usr/bin/dotnet`

Did you previously install with another mechanism?

**Comment by AndrewKralovec** [comment]
Nope, the same way as I'm doing now. I'm just trying to get the new version 'preview2' .

**Comment by brthor** [comment]
@AndrewKralovec Can you show me the output of a few commands so I get an idea what is going on?

`ls /usr/share/dotnet`
`ls -l /usr/bin  |  grep dotnet`
`ls -l /usr/local/bin | grep dotnet`

**Comment by AndrewKralovec** [comment]
andrew@andrew-PC:~$ ls /usr/share/dotnet
dotnet  host  LICENSE.txt  sdk  shared  ThirdPartyNotices.txt
andrew@andrew-PC:~$ ls -l /usr/bin | grep dotnet
lrwxrwxrwx 1 root   root          22 Jun 15 19:28 dotnet -> ../share/dotnet/dotnet
andrew@andrew-PC:~$  ls -l /usr/local/bin | grep dotnet
lrwxrwxrwx 1 root   root         26 May 17 14:54 dotnet -> /home/andrew/dotnet/dotnet
andrew@andrew-PC:~$

**Comment by brthor** [comment]
whatever you have installed in `/home/andrew/dotnet/dotnet` is taking precedence over your deb installation. 

I imagine you used the dotnet-install.sh at some point because I believe that is the default install location. 

`rm /usr/local/bin/dotnet` should do the trick and you'll be able to use the version installed by the deb

**Comment by blackdwarf** [comment]
Thanks @brthor . @AndrewKralovec please try this out and let us know if it fixes the issue.

**Comment by AndrewKralovec** [comment]
Yeah that did the trick. Thanks everyone!
