### ISSUE TITLE
Advice on DependencyContext and Assembly loading in custom CLI tool

### ISSUE THREAD

**Issue by Antaris** [dotnet/cli#4057]
I'm developing a framework on top of .NET Core/ASP.NET Core that is designed to be highly modular. My module system is built along the same lines as ASP.NET Core's ApplicationPartManager where I used the `DependencyContext` to discover dependencies that reference a core set of my framework libraries. Modules are included by package references, therefore the application has everything it needs at compile time. I am not performing any runtime assembly loading for an application, but I am trying to achieve it for a custom CLI tool.

One of the features of my framework is the ability to support multiple database contexts which can target multiple databases through logical groups. A set of `DbContext` instances can target one group. E.g., my`SecurityDbContext` and `SettingsDbContext` (both separate modules) target the `Core` logical group. The logical group has a one-to-one mapping to a connection string.

To support database migrations, I couldn't use EF's approach to database migrations as it doesn't support multiple contexts using the same database. So I've built my own migrations service which used embedded `.sql` script files and using the modules which compose the applications, I know which databases to apply the scripts to.

I want to build a custom `dotnet-*` tool to execute these migrations in two different scenarios
- At design time from the current project directory
- At runtime
  - As part of an automated deployment
  - Standalone against an application

Because of the requirement on `DependencyContext` to discover assemblies that compose my application, I need to determine the `DependencyContext` for my application when the CLI tool runs.

The current debugging experience for CLI tools is difficult, so I've taken a different approach in that I set my CLI tool (in the same solution as a test application) to be my startup project, with a target directory pointing to my test application root path. I also provide any arguments to invoke the correct command.

The `DependencyContext.Default` in this instance will be that of my CLI tool, _not_ my test application. Therefore, I've devised this class to determine my `DependencyContext` for my test application when running from my CLI tool:

```
public static class DependencyContextResolver
{
    public static DependencyContextResult ResolveDependencyContext()
        => ResolveDependencyContext(Directory.GetCurrentDirectory());

    public static DependencyContextResult ResolveDependencyContext(string path)
    {
        Ensure.ArgumentNotNull(path, nameof(path));

        string projectFile = Path.Combine(path, "project.json");
        if (File.Exists(projectFile))
        {
            return ResolveProjectDependencyContext(projectFile);
        }

        string[] depsFiles = Directory.EnumerateFiles(path, "*.deps.json", SearchOption.TopDirectoryOnly).ToArray();
        if (depsFiles.Length == 0)
        {
            throw new OperationErrorException("No '.deps.json' file was found in the application path.");
        }

        if (depsFiles.Length > 1)
        {
            throw new OperationErrorException("Multiple '.deps.json' file was found in the application path.");
        }

        return new DependencyContextResult
        {
            Context = GetDependencyContextFromDepsFile(depsFiles[0]),
            ApplicationName = Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(depsFiles[0])),
            LibraryPath = Directory.GetCurrentDirectory()
        };
    }

    public static DependencyContextResult ResolveProjectDependencyContext(string projectFile)
    {
        // MA - Get the project context.
        var projectContext = ProjectContext.CreateContextForEachFramework(projectFile)
           .Where(pc => pc.TargetFramework.GetShortFolderName() == "netcoreapp1.0")
           .SingleOrDefault();

        if (projectContext == null)
        {
            throw new OperationErrorException("Unable to get project context for framework 'netcoreapp1.0'");
        }

        // MA - Get the path to the target file.
        string depsFile = projectContext.GetOutputPaths("Debug").RuntimeFiles.DepsJson;
        if (!File.Exists(depsFile))
        {
            // MA - Determine if the 'preserveCompilationContext' flag is set:
            bool? hasPreserveFlag = projectContext.ProjectFile
                .GetCompilerOptions(projectContext.TargetFramework, "Debug")?
                .PreserveCompilationContext;

            if (!hasPreserveFlag.GetValueOrDefault(true))
            {
                throw new OperationErrorException($"Missing dependencies file '{depsFile}'. You must have 'preserveCompilationContext' set in your project file?");
            }

            // MA - File doesn't exist, let's try a build.
            int buildExitCode = CommandFactory.CreateBuildCommand(projectFile, "Debug", projectContext.TargetFramework)
                .ForwardStdErr()
                .ForwardStdOut()
                .Execute()
                .ExitCode;

            if (buildExitCode != 0)
            {
                throw new OperationErrorException($"Failed to build project: {projectContext.ProjectFile.Name}");
            }

            if (!File.Exists(depsFile))
            {
                throw new OperationErrorException($"Missing dependencies file '{depsFile}'. Do you have 'preserveCompilationContext' set in your project file?");
            }
        }

        return new DependencyContextResult
        {
            ApplicationName = projectContext.ProjectFile.Name,
            LibraryPath = projectContext.GetOutputPaths("Debug").CompilationOutputPath,
            Context = GetDependencyContextFromDepsFile(depsFile)
        };
    }

    public static DependencyContext GetDependencyContextFromDepsFile(string depsFile)
    {
        Ensure.ArgumentNotNullOrEmpty(depsFile, nameof(depsFile));

        using (var reader = new DependencyContextJsonReader())
        using (var stream = File.OpenRead(depsFile))
        {
            return reader.Read(stream);
        }
    }

    public class DependencyContextResult
    {
        public string ApplicationName { get; set; }

        public DependencyContext Context { get; set; }

        public string LibraryPath { get; set; }
    }
}
```

This correctly gives me my closure over all the dependencies that make up the application. 

The problem I am finding, my logic to load assemblies using an `AssemblyName` in my `CandidateAssemblyProvider` (which is based ON MVC's method of loading application parts) only returns those libraries which are loaded by the CLI tool (because the CLI tool has them as it's own dependencies)

```
return GetCandidateLibraries(_context, _referenceAssemblies)
    .SelectMany(l => l.GetDefaultAssemblyNames(_context))
    .Select(Assembly.Load);
```

For example, here might be the `project.json` for my test application:

```
{
  "dependencies": {
    "ModuleA": "1.0.0-*",
    "ModuleB": "1.0.0-*",
    "Data.Abstractions": "1.0.0-*"
  }
}
```

And for my CLI tool:

```
{
  "dependencies": {
    "Data.Abstractions": "1.0.0-*"
  }
}
```

In this instance, only the dependency `Data.Abstractions` is loaded because it is used by both the test application and the CLI tool. Remember at this stage we're debugging the CLI tool, but targeting the test application.

Because of this issue, I thought I might be able to tackle this by loading in the set of assemblies detailed by the `DependencyContext`, using something like this:

```
public static class DependencyContextResultExtensions
{
    public static void LoadAssemblies(this DependencyContextResolver.DependencyContextResult result)
    {
#if NETSTANDARD1_6
        foreach (var library in result.Context.RuntimeLibraries)
        {
            Func<AssemblyLoadContext, AssemblyName, Assembly> resolver = (alc, an) => Resolve(alc, an, result.LibraryPath, library);
            AssemblyLoadContext.Default.Resolving += resolver;

            var names = library.GetDefaultAssemblyNames(result.Context);
            foreach (var name in names)
            {
                AssemblyLoadContext.Default.LoadFromAssemblyName(name);
            }

            AssemblyLoadContext.Default.Resolving -= resolver;
        }
#endif
    }

#if NETSTANDARD1_6
    public static Assembly Resolve(AssemblyLoadContext context, AssemblyName name, string basePath, RuntimeLibrary library)
    {
        string assemblyLocalSource = Path.Combine(basePath, Path.GetFileName($"{name.Name}.dll"));
        if (File.Exists(assemblyLocalSource))
        {
            name = AssemblyLoadContext.GetAssemblyName(assemblyLocalSource);
            return context.LoadFromAssemblyPath(assemblyLocalSource);
        }

        string assemblyPackageSourceRelativePath = library.Assemblies.SingleOrDefault(a => a.Name.Equals(name.Name))?.Path;
        if (assemblyPackageSourceRelativePath != null)
        {
            string packageSource = $"%USERPROFILE%/.nuget/packages/{library.Name}/{library.Version}/";
            string assemblyPackageSource = Environment.ExpandEnvironmentVariables(Path.Combine(packageSource, assemblyPackageSourceRelativePath));

            if (File.Exists(assemblyPackageSource))
            {
                return context.LoadFromAssemblyPath(assemblyPackageSource);
            }
        }

        return null;
    }
#endif
}
```

But what I am finding, is that it fails to load any assemblies that are not the test application assembly itself. Something similar to:

```
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.ni.dll

Additional information: Could not load the specified file.
```

My code checks that the file exists (either in the local path or the NuGet package source), but it just doesn't want to load.

So I have a few questions:
1. Can you offer any recommendations on loading assemblies from a target application by a CLI tool?
2. Is there an easier method of locating assemblies, perhaps using some lower level mechanism to load an assembly based on a `Library` instance and have it resolve automatically to either the NuGet package root or the local path?
3. Do you see anything glaringly obvious that I am missing in trying to tackle this?

Sorry, it's a long question, but I'm struggling to find any concrete methodology on tackling these issues, so I figured I would just ask you guys directly on here.

**Comment by Deren-Liao** [comment]
Seems to me I am facing the same problem.   Please help confirm this is what you are trying to solve.

Assuming I have a myAspNetApp.dll that hosting an ASP.NET core web site.  There is another dll that will be loaded dynamically, it has name DynamicLoadTest and is under a separate folder.  The following is a sample folder structure.

--- myAspNetApp
     myAspNetApp.dep.json
     myAspNetAp.dll
--- DynamicLoadTest
     dynamicLoadTest.dep.json
     dynamicLoadTest.dll
     dependencyOfdynamicLoadTest.dll

the site will be started as  
dotnet    myAspNetApp\myAspNetAp.dll

May you suggest the best way loading DynamicLoadTest.dll ?   It has dynamicLoadTest.dep.json together with it's dependencies like dependencyOfdynamicLoadTest.dll  too.

**Comment by olivier-spinelli** [comment]
@Antaris I'm facing the same kind of issue (and in the same context, except I don't use EF). Even with netcore2 this kind of stuff seems awful... Did you make any progress on this?

**Comment by Antaris** [comment]
@olivier-spinelli 

Yes, but my approach was to go back to the model of DNX, where instead of creating `dotnet-` commands that are fed from the drive, instead I turn my app into a host of commands, giving me access to the same dependency context as the application itself.

So, with my new model, I can do the following:

```
using static Fx.Tools.ToolAwareEntryPoint;
```
```
public static void Main(string[] args)
{
    RunToolOrApp("SampleWeb", args, BuildWebHost());
}

public static IWebHost BuildWebHost() =>
    WebHost.CreateDefaultBuilder()
        .UseStartup<Startup>()
        .Build();
```

The `ToolAwareEntryPoint` type is something I have created which basically maps from a `CommandLineApplication` to an `ITool` in framework world.

Essentially, the workflow for me is now:
- Try and match `string[] args` to an existing tool`
- If tool exists, execute tool
- If tool doesn't exist, fallback to booting Kestrel and running the website

So, from the command line, I can do:

```
> dotnet run migrate
```

Which runs my custom database migrations solution

or, perhaps:

```
> dotnet run services-diagnostics
```

Which spits out the contents of the `IServiceCollection` for my application so I can diagnose what services are registered and debug issues.

Or if I do this:

```
> dotnet run
```

It just runs the web application

DNX handled this real nicely, but obviously migrating back to dotnet (whilst that is a very good thing), has left its own challenges.

Happy to share a more concrete example, or happy if this simply points you in the right direction

**Comment by hvanbakel** [comment]
@Antaris this might be fixed with https://github.com/dotnet/core-setup/issues/3634 but this is only coming in 2.1

**Comment by livarcocc** [comment]
Closing as this is an old issue still talking about project.json. Plus, the host now has ways to load more assemblies which might solve this problem.
