### ISSUE TITLE
Include 3rd party and P2P dependencies during native compile.

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#406]
Implementation assemblies for 3rd party and P2P dependencies should be passed to `ilc.exe` as references. 

An open question is how to handle the runtime identifier in this case. 3rd Party dependencies may not be targeting the `-aot` runtime identifier suffix that native libs are currently under. For this reason this is somewhat tied to #402 

This is another step in unblocking #255 

/cc @schellap @gkhanna79 Is this how you envision handling these dependencies?

**Comment by gkhanna79** [comment]
@brthor I would not expect upstack 3rd party libraries to have anything AOT specific unless there is a good reason for them to have one. Most of the upstack (1st and 3rd party) should be the general purpose netfcore TFM libs.

CC @weshaggard

**Comment by weshaggard** [comment]
@gkhanna79 While I agree with you in general I do think there will likely be cases where upstack libraries will need to make this distinction. Particularly ones that generally rely on Ref.Emit and have to do something different for the aot case.

**Comment by gkhanna79** [comment]
@weshaggard Can you please elaborate on the nature of things they have to do differently?

**Comment by weshaggard** [comment]
An example are libraries like System.Linq.Expressions where when they have Reflection.Emit they will use it but in the AOT case they cannot they have to do interpretation instead of runtime codegen. There are other 3rd party libraries in the ecosystem that will need to do something similar.

**Comment by blackdwarf** [comment]
Should we move this to dotnet/corert?

**Comment by blackdwarf** [comment]
Moved, closing this one.
