### ISSUE TITLE
TFS throws an error when trying to find the core sdk

### ISSUE THREAD

**Issue by onethread** [dotnet/cli#4060]
I've also tried disabling the building of the project in all configurations, but it will still throw the error on build.
## Steps to reproduce

Install SDK Preview 2 on TFS build server
Install VS 2015 Tooling Preview 2 on build server
Creat build definition with step type Visual Studio Build
Kick off the build
## Expected  behavior

Successful build
## Actual behavior

Throws `GETSDKTOOLINGINFO(0,0): Error : The .NET Core SDK is not installed or cannot be found. These components are required to build and run this project.`
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by shadowii** [comment]
Looks like it only fails when the build step is of type "Visual Studio Build". I changed it to a regular MSBuild step and it works fine. I've updated the above repro steps.

**Comment by shadowii** [comment]
This actually might be a non-issue. The solution has mixed project types (Core and .Net 4.6). I just noticed that if I blank out the platform field in the build step (either type), it works.

**Comment by livarcocc** [comment]
Please re-open if this is still an issue.
