### ISSUE TITLE
dotnet restore do not restore a local dependency

### ISSUE THREAD

**Issue by noliar** [dotnet/cli#4065]
## Steps to reproduce
I create several project in a folder(structure is as follow).
```
global.json
src
--BTempAnother
----Library.cs
----project.json
samples
--A
----Program.cs
----project.json
```
global.json's content is :
```
{
  "projects": [ "src", "samples" ],
  "sdk": {
    "version": "1.0.0-preview3-003223"
  }
}
```
A's project.json(refer `project BTempAnother`):
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "BTempAnother":{
          "target": "project"
        }
      },
      "imports": "dnxcore50"
    }
  }
}

```

BTempAnother's project.json:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {},
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NETStandard.Library": "1.6.0"
      }
    }
  }
}

```

And if I run `dotnet restore` at the folder of project A, it only restored the project A, not restoring project BTempAnother automatically. 
![dotnet-bug-or-feature](https://cloud.githubusercontent.com/assets/5773982/17795340/35c9f956-65ea-11e6-8096-3f9a1d43c043.gif)

## Expected  behavior
`dotnet restore` will restore that project automatically.

## Actual behavior
`dotnet restore` don't restore that local-reference project. `project.lock.json` doesn't exist in `BTempAnother` folder after restoring at the folder of project A.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003223)

Product Information:
 Version:            1.0.0-preview3-003223
 Commit SHA-1 hash:  9d3b727392

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
@noliar this behavior is by design. Restore operation will not restore all of the P2P dependencies' dependencies. That is, the behavior I can see in the animated GIF above is correct. If you wish to restore all of the dependencies for all your projects in one go, so to speak, just run `dotnet restore` at the root of your solution (where you have the `global.json` file).

**Comment by pksorensen** [comment]
I am using same structure, the problem of apps in sample folder cant resolve libraries from src when doing dotnet restore
