### ISSUE TITLE
dotnet test uses incorrect working directory when multiple frameworks are specified

### ISSUE THREAD

**Issue by gulbanana** [dotnet/cli#4067]
## Steps to reproduce
1. Create a unit test project with multiple frameworks or clone https://github.com/gulbanana/repro-dotnettest-workingdirectory
2. cd src/TestProject
3. dotnet test 
   observe that all tests pass 
4. cd ..
5. dotnet test TestProject 
   observe that tests fail for netcoreapp1.0
## Expected  behavior

The test should pass.
## Actual behavior

When run from another directory, one framework's worth of tests run with the wrong working directory and hence fail.  Using "-f" also sets the wrong WD sometimes, but is harder to reproduce.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by pvlakshm** [comment]
This is a bug. We'll fix this in an upcoming release.

**Comment by piotrpMSFT** [comment]
@pvlakshm will this make RTM?

**Comment by piotrpMSFT** [comment]
This is tracked by #4708
