### ISSUE TITLE
Microsoft.Extensions.DependencyModel 1.0.0 is not compatible with .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by harshjain2** [dotnet/cli#4068]
I am observing this issue when trying to restore nuget.exe restore on .sln file.
I get this error with "Microsoft.Extensions.DependencyModel": "1.0.0" but not with "Microsoft.Extensions.DependencyModel": "1.0.0-rc2-002702"
## Steps to reproduce

nuget.exe restore "D:\Code\github\harshjain2\abc.sln" -Source https://api.nuget.org/v3/index.json;https://dotnet.myget.org/F/cli-deps/api/v3/index.json;https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -NoCache
## Expected  behavior

Restore should complete without any error.
## Actual behavior

Microsoft.Extensions.DependencyModel 1.0.0 is not compatible with .NETCoreApp,Version=v1.0.
Some packages are not compatible with .NETCoreApp,Version=v1.0.
## Environment data

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
## prjoect.json file

{
  "version": "99.99.99-dev",
    "warningsAsErrors": true
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet",
        "portable-dnxcore50+net45+win8+wp8+wpa81",
        "portable-net45+win8"
      ],
      "dependencies": {
        "NETStandard.Library": "1.6.0",
        "System.Threading.ThreadPool": "4.0.10",
        "Microsoft.Extensions.DependencyModel": "1.0.0"
      }  
    }
  }
}

**Comment by davidfowl** [comment]
> I am observing this issue when trying to restore nuget.exe restore on .sln file.

What version of nuget.exe? You probably need to update it.

**Comment by harshjain2** [comment]
I am using the latest version of nuget.exe available. [nuget.exe - latest (v3.4.4)](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe)

**Comment by davidfowl** [comment]
I believe you need `3.5.0-*` to work with .NET Core. See https://dist.nuget.org/index.html

/cc @rrelyea @emgarten

**Comment by piotrpMSFT** [comment]
Closing since we've not had traction since August. This issue, though, should be re-opened in https://github.com/nuget/home if we still need to do something.
