### ISSUE TITLE
dotnet new causes segmentation fault at Expanding

### ISSUE THREAD

**Issue by pspierce** [dotnet/cli#4069]
## Steps to reproduce

dotnet new
## Expected  behavior

Initialize a basic .NET project
## Actual behavior

 dotnet new
## Welcome to .NET Core!

Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
## Telemetry

The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
## Configuring...

A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 2320 ms
Expanding 0%Segmentation fault (core dumped)
## Environment data

`dotnet --info` output:

dotnet --info
.NET Command Line Tools (1.0.0-preview3-003223)

Product Information:
 Version:            1.0.0-preview3-003223
 Commit SHA-1 hash:  9d3b727392

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

**Comment by svick** [comment]
What kernel version are you using? There is a known issue with running .Net Core 1.0.0 on Linux kernel 4.6 (https://github.com/dotnet/coreclr/issues/6016).

**Comment by piotrpMSFT** [comment]
@schellap @gkhanna79 FYI

Closing as we haven't had traction on this in over two months, but feel free to reopen if it's still an issue.
