### ISSUE TITLE
dotnet-test aborts on Ubuntu 14.04

### ISSUE THREAD

**Issue by andschwa** [dotnet/cli#407]
## Versions
``` sh
$ uname -a
Linux magrathea 3.19.0-37-generic #42~14.04.1-Ubuntu SMP Mon Nov 23 15:13:51 UTC 2015 x86_64 x86_64 x86_64 GNU/LinuxLinux magrathea 3.19.0-37-generic #42~14.04.1-Ubuntu SMP Mon Nov 23 15:13:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ aptitude show dotnet
Package: dotnet                          
New: yes
State: installed
Automatically installed: no
Version: 1.0.16772.1449108444-1
```
## `project.json`
```json
{
    "version": "1.0.0.0",
    "description": "Project xUnit Tests",
    "authors": [ "andschwa" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "xunit": "2.1.0-*",
        "xunit.runner.dnx": "2.1.0-*"
    },

    "frameworks": {
        "dnxcore50": {
        }
    }
}
```
## Error
```sh
$ dotnet restore
Microsoft .NET Development Utility CoreClr-x64-1.0.0-rc1-16048

  CACHE https://www.myget.org/F/aspnetrelease/
  CACHE https://www.nuget.org/api/v2/
Restoring packages for /home/andrew/monad-linux/src/Microsoft.PowerShell.Linux.UnitTests/project.json
  CACHE https://www.myget.org/F/aspnetrelease/FindPackagesById()?id='xunit'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='xunit'
  CACHE https://www.myget.org/F/aspnetrelease/FindPackagesById()?id='xunit.runner.dnx'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='xunit.runner.dnx'
Writing lock file /home/andrew/monad-linux/src/Microsoft.PowerShell.Linux.UnitTests/project.lock.json
Restore complete, 1431ms elapsed

NuGet Config files used:
    /home/andrew/.config/NuGet/NuGet.config
    /home/andrew/monad-linux/nuget.config

Feeds used:
    https://www.myget.org/F/aspnetrelease/
    https://www.nuget.org/api/v2/

$ dotnet test
dotnet-test Error: 0 : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Test.Program.RunConsole(ProjectContext projectContext, CommandLineApplication app, String testRunner)
   at Microsoft.DotNet.Tools.Test.Program.<>c__DisplayClass0_0.<Main>b__0()
```

Also have tried with with `"Microsoft.NETCore.Runtime": "1.0.1-beta-*",` as a dependency, and with `"TestRunner": "xunit",` and `"commands": { "TestRunner": "xunit" },`. @blackdwarf Any clue?

**Comment by piotrpMSFT** [comment]
@andschwa did dotnet-test get installed on your machine?

**Comment by andschwa** [comment]
@piotrpMSFT Yes:
```sh
$ which dotnet-test
/usr/bin/dotnet-test
```

It could very well be that I'm not using `dotnet-test` properly, please point me to docs if that's case :smile: However, it also seems that its internal error reporting is... broken.

**Comment by anurse** [comment]
I think there is a CoreFX bug here in that the error should not be `Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.`. I'm pretty sure we're getting the right implementation of System.Diagnostics.Process since it works on Unix, yet it still seems to be trying to P/Invoke to windows APIs.

**Comment by blackdwarf** [comment]
@anurse can you link the corefx issue here for tracking? Thanks!

**Comment by anurse** [comment]
This wasn't a corefx issue and the specific exception has been resolved. @andschwa are you still encountering an error using `dotnet test`?

**Comment by andschwa** [comment]
Nada:

```
$ dotnet-test
dotnet-test Error: 0 : System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Test.Program.RunConsole(ProjectContext projectContext, CommandLineApplication app, String testRunner)
   at Microsoft.DotNet.Tools.Test.Program.<>c__DisplayClass0_0.<Main>b__0()
```

Using `dotnet` Ubuntu package version: 1.0.16779.1449740690-1

When I get some time, I'll try building from source and see if I can capture the error message it's trying to print another way (before it fails to print the error).

**Comment by anurse** [comment]
The error in this case is almost always that dotnet-test is trying to invoke something and it can't find the executable. Maybe you don't have `dotnet-test-xunit`? /cc @piotrpMSFT

**Comment by andschwa** [comment]
You're right, I don't have `dotnet-test-xunit`. Am I missing a package, what dependencies do I need for this?

**Comment by venkthi1** [comment]
Hi,
I am hitting the same issue when trying to run my windows app on ubuntu.
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
ubuntu@ip-172-31-19-163:~/duplo-code/discovery$

**Comment by andschwa** [comment]
@venkat-raman251 It's an unhandled error that (usually) simply means the sub-binary you tried to call (i.e. `dotnet <tool>`) wasn't in your path (what you're seeing is an error thrown when it's trying to report another error).

Can you post the exact command you were running?

**Comment by venkthi1** [comment]
Hi @andschwa , This is command and I am running this from the same folder where my exe is

sudo dotnet ./ContainerManagement.Discovery.exe 1

I even tried to copy the api-ms-win-core-localization-l1-2-0.dll' from my windows server to the same folder in Ubuntu with the exe but still fails with the same.
This is ContainerManagement.Discovery.exe is an exe that I compiled in VS2015 with a regular csproj. It runs fine in Windows server 2012 R2. I am trying to containerize this and hence first tried to run it in Ubuntu VM.
Thanks

**Comment by venkthi1** [comment]
@andschwa I might have misunderstood the usage of dotnet cli. What I really want is that I have an existing application that was already compiled in VS2015 in windows via csproj files which has a bunch of dependencies on other csproj files. 
I want to run it in Linux (without re-compiling via project.json). So basically instead of mono <EXE Name> I was hoping for an equivalent in dotnet core.

**Comment by andschwa** [comment]
@venkthi1 Ah, no, that is not the use of `dotnet`. It's simply a front-end to .NET build tools; it's not a native host.

You will be very unlikely to to run an executable compiled on Windows without using Mono on Linux. While CoreFX does have a `corerun` executable (similar to `mono` in that it's a native host for .NET apps), the assumptions made on Linux about DLL locations (and other things) is very different than on Windows.

If you want your existing app to be cross-platform, I would recommend trying to first compile it on Windows targeting CoreCLR (using  the `dotnet-cli` / `project.json` tools, because DNX will fade away), and if it works on that framework, it will very likely also compile and work on Linux.

But believe me, I understand switching build systems is difficult, especially when the tools themselves are in beta. :smile:

**Comment by piotrpMSFT** [comment]
@andschwa, @venkthi1 the ugly error message should be fixed as of #697 

With that change in [it also fixed our ability to load commands from NuGet packages], dotnet-test-xunit is not far behind.

**Comment by andschwa** [comment]
That is fantastic news @piotrpMSFT, thanks for the update!

**Comment by piotrpMSFT** [comment]
@andschwa, at this point this is blocked only on the xunit runner package being published which will happen from xunit's repo [though we'll try to share a prototype sooner]. Closing the issue.
