### ISSUE TITLE
No way to include text files in package using dotnet pack command

### ISSUE THREAD

**Issue by maxim-boligatov** [dotnet/cli#4073]
## Steps to reproduce

put the following text in project.json:

"buildOptions": {
      "copyToOutput": [ "MyOwnTextFile.config" ]
   },

run dotnet pack
## Expected  behavior

nupkg contains "MyOwnTextFile.config" file
## Actual behavior

nupkg does not contain "MyOwnTextFile.config" file
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by giggio** [comment]
You should use `packOptions`, not `buildOptions`.

**Comment by brthor** [comment]
```

**Comment by maxim-boligatov** [comment]
Unfortunately it does not work...
File is placed inside root of package.
But it should appear near my output dll like it is during build.

DLL is placed in lib/net461/MyAssembly.dll

Do you have any suggestions?

**Comment by giggio** [comment]
If you want to place it somewhere else you have to use `mappings`.

**Comment by brthor** [comment]
something like this

```
"packOptions": {
    "files": { 
        "mappings" :  {
            "lib/net461": {
                "include": [ "MyOwnTextFile.config" ]
            }
        }
}
```

**Comment by maxim-boligatov** [comment]
Nice! Now it has correct place in package. 

But how to tell that this file should be placed in project and copied on build to output?

In other words setup "_contentFiles_":   
https://docs.nuget.org/create/nuspec-reference#contentfiles-with-visual-studio-2015-update-1-and-later

**Comment by piotrpMSFT** [comment]
This question will be best answered by NuGet folks :) I moved the issue to their repo to help get traction.
