### ISSUE TITLE
'dotnet new -t web' project doesn't run correctly in development mode without 'bower install'

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#4076]
## Steps to reproduce
1. dotnet new -t web
2. dotnet restore
3. dotnet build
4. Open directory in VS Code (or set `ASPNETCORE_ENVIRONMENT=Development` in some other way)
5. Launch the project
## Expected  behavior

The page should render correctly, or direct users to run 'bower install'
## Actual behavior

It renders incorrectly (see screen shot at the end)
## Problem

In _Layout.cshtml, in development mode, the code references bootstrap.css, but bootstrap.css isn't part of the project unless the user has run 'bower install', and 'bower install' isn't part of the build, and there are no other errors if it is skipped.
## Work around

Either run `bower install` --

Install Node.js from https://nodejs.org/
Install git from https://git-scm.com/

```
npm install -g bower
bower install
```

Or open _Layout.cshtml, and change line 9 to:

```
<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.css" />
```
## Screen shot

![VS Code browser screen capture](https://cloud.githubusercontent.com/assets/19626732/17759979/fb517e4c-6536-11e6-92f8-77ac44511d1a.png)
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
What happens if you do `bower install` prior to running? Bower is supposed to install the bootstrap, I think. 

/cc @danroth27

**Comment by gregg-miskelly** [comment]
@blackdwarf you are correct. This can be fixed by running `bower install`. I updated the repo steps to reflect this.

**Comment by blackdwarf** [comment]
@gregg-miskelly hm, it seems that the `prepublish` script will actually run this. I guess VS Code actually does `dotnet run`? I wonder why does this work from the command line but not from VS Code? Is it that the env variable is not getting set properly?

**Comment by gregg-miskelly** [comment]
@blackdwarf VS code cannot use `dotnet run` as that will run the app in a child process. Instead we do `dotnet build` and then `dotnet <path-to-dll>`. Though I think the real difference between the command line scenario is that we enable ASPNETCORE_ENVIRONMENT=Development. I believe if one did the same at the command line, the same problem would happen. The other possibility is if there is code that detects if bower is installed or not, as I didn't have bower installed initially.

**Comment by danroth27** [comment]
@sayedihashimi 

This is a known issue. The current web template for dotnet new has an NPM and Bower dependency.

**Comment by sayedihashimi** [comment]
Yes this will be fixed

**Comment by piotrpMSFT** [comment]
@danroth27 @sayedihashimi @mlorbetske 

Can we link a tracking issue for the template? We can't act on this issue in CLI and I want to be sure @gregg-miskelly can track the root fix.

**Comment by blackdwarf** [comment]
Created the issue on dotnet/templating. Closing this one as it is not something we can act on in the CLI.
