### ISSUE TITLE
Cannot reference PCL from netcoreapp1.0

### ISSUE THREAD

**Issue by jnm2** [dotnet/cli#4082]
## Steps to reproduce
1. Create a new .NET Core console app.
2. Add a new PCL project to the src folder and select: .NET Framework 4, Windows8, Windows Phone Silverlight 8, Silverlight 5, Windows phone 8.1, Xamarin.Android, Xamaron.iOS, Xamarin.iOS (Classic)
3. Change the imports under the netcoreapp1.0 framework to `.NETPortable,Version=v4.0,Profile=Profile328`
4. Add a reference to the Core project to consume the PCL project
5. Write code in the Core project that references the PCL's `Class1` type (or any type it contains)
## Expected  behavior

The Core project compiles and runs.
## Actual behavior

The Core project acts as though no reference had been added to the PCL. It does not give an error indicating an issue with project.json or the PCL reference itself. The only error is that `Class1` could not be found.

My actual problem is not with a brand new PCL but with an old one. I searched for hours online and in these repos to try to find documentation or issues addressing this problem. The solution seems to be "wait until a netstandard version is available", but this is an old library. In addition to that, I'm fairly sure old PCLs were supposed to be allowed to be referenced from Core. The PCL API surface is so restricted that I can't imagine that the problem is that Core is incapable of running this PCL project.

In any case, it should be possible to find complete documentation on this particular issue so that it isn't necessary to search though and file issues like this one.
## Environment data

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@jnm2 can you attach a small repro project? There is a lot of IDE-generated code above and it's easy to build an improper repro through UI.

**Comment by jnm2** [comment]
New OS installation (faster SSD now) but the same issue is repro'd. dotnet:
  Version  : 1.0.1
  Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12

https://github.com/jnm2/misc-codesamples/raw/master/Bug%20reports/.NET/Profile328%20Core%20reference%20issue.zip

**Comment by livarcocc** [comment]
This is an old issue and the repro still uses xproj and project.json. Could you try using the new csproj files?

**Comment by jnm2** [comment]
I'm positive this is no relevant to me. 😆 Good call!
