### ISSUE TITLE
MSBuild does not follow P2P reference after renaming .xproj

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#4086]
## Steps to reproduce
1. git clone https://github.com/jeremymeng/P2PRepro.git
2. nuget restore
3. MSBuild

The project should build clean. Note that the log shows MSBuild knows to build dependencies first

```
Project "e:\working\P2PRepro\P2PRepro\Library\Library.xproj" (2) is building "e:\working\P2PRepro\P2PRepro\Library.C
onfig\Library.Config.xproj" (3) on node 1 (default targets).
```
1. git checkout rename-xproj
2. git clean -xdf
3. nuget restore
4. MSBuild
## Expected  behavior

build succeeds
## Actual behavior

MSBuild does not build project reference first, which results in build error.

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : e
:\working\P2PRepro\P2PRepro\Library\error CS0006: Metadata file 'e:\working\P2PRepro\P2PRepro\Library.Config\bin\Deb
ug\netstandard1.5\Library.Config.dll' could not be found [e:\working\P2PRepro\P2PRepro\Library\Library.NetStandard.x
proj]
```
## Environment data

`dotnet --info` output:

**Comment by jeremymeng** [comment]
It's useful to rename the xproj to avoid project name conflicts when adding new .NET Standard projects to existing solutions.

**Comment by piotrpMSFT** [comment]
xproj project system is tracked in /aspnet/tooling, jeremyment. CLI didnt know anything about xproj, nor did it interact with desktop msbuild.
