### ISSUE TITLE
Question: How to remove previous versions of .NET Core from Linux (CentOS 7.1)

### ISSUE THREAD

**Issue by stevo-knievo** [dotnet/cli#4088]
I hope that is the right repo.. 

I would like to install the current .NET Core SDK on my Linux server (CentOS 7.1). Currently the RC2 version is installed. [The instruction on the official website are](https://www.microsoft.com/net/core#centos):

> Before you start, please remove any previous versions of .NET Core from your system.

But I don't know how... I found this [script](https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh)... but my Linux skills are not great and I won't make it worst.

Thanks a lot! Stefan

**Comment by blackdwarf** [comment]
@stevo-knievo that script is for macOS so you should not run it on CentOS (it will most likely fail as it depends on some macOS specific commands). 

In order to remove the previous installation, simply remove the `dotnet` folder from where you installed it on disk.

**Comment by stevo-knievo** [comment]
Thanks a lot Zlatko!! Will try it first thing tomorrow morning! Thank you so much!

**Comment by stevo-knievo** [comment]
It's done and it works!! For precautionary reasons I deleted the .dotnet and .aspnet folder at the home directory as well.

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
```

Thanks again!!
