### ISSUE TITLE
Resource generation uses Library name, not Default Namespace

### ISSUE THREAD

**Issue by nullcat0** [dotnet/cli#4089]
## Steps to reproduce
Create new Class Library (.NET Core).
Go to project Properties, Application tab, and change Default Namespace.
Add to project a new Resources (.resx) file.
Reference an entry in the resx file in your Class1.cs.
Add a second project (type doesn't matter).
Add a reference to the first project.
Rebuild.

## Expected  behavior
Successful build.

## Actual behavior
Build error:

System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture. Make sure "MyCorp.Strings.resources" was correctly embedded or linked into assembly "MyCorp.Lib" at compile time, or that all the satellite assemblies required are loadable and fully signed.
at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
I tried various google results, and discovered that the problem is that the .resources file was produced under the name of "MyCorp.Lib.Strings.resources". The error though is looking for "MyCorp.Strings.resources".

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

See: https://github.com/aspnet/dnx/issues/3422

The resources file appears to get created as part of the build process using the wrong name.  Either it should be based on the default namespace, but is instead based on the library name; or the mechanism that is searching for the resources file is looking with the wrong name.

Regards,
Rob.

**Comment by atanasa** [comment]
It's not exactly the library name. If you specify buildOptions -> outputName in the project.json, it would use the "name" value instead. It must match the code-behind which I think uses the "default namespace" to generate the code.

**Comment by nullcat0** [comment]
I'm not 100% certain, but I think this was due to the lack of the latest version of the .NET Core SDK toolkit.  This behaviour may only occur when you first install VS2015 without the tools.

Since installing the tools, I can now remove the project.json configurations and the resx file behaves as expected by default, and I do not get any exceptions.

Regards,
Rob.
