### ISSUE TITLE
Build for target .NETFramework 4x on Linux fails.

### ISSUE THREAD

**Issue by Lakritzator** [dotnet/cli#4091]
I'm actually a bit confused, and can't seem to find a statement on my wish to be able to do a "dotnet build" on linux and get a Windows executable. Am sorry if this is documented somewhere, but I really couldn't find anything concrete...

What I would love to have, is a possibility to build a Windows exe for the .NET Framework (4.5 or higher) on linux, by using Jenkins. That the exe can't run is okay and logically, but I could imagine that it should be possible to at least compile. This would dramatically reduce the problems for a company which uses mostly Java and linux on the servers, and has Windows desktops with strict policies which make running Jenkins on Windows pretty much impossible. And probably for a lot of other scenarios too...

Maybe I just forgot something in the project.json..
## Steps to reproduce
1. I installed dotnet via the steps here: https://www.microsoft.com/net/core#ubuntu
2. `dotnet new`
3. changed the project.json to:

```
{
    "version": "1.0.0-*",
    "buildOptions": {
        "emitEntryPoint": true
    },
    "dependencies": {},
    "frameworks": {
        "net46": {
            "dependencies": {}
        }
    },
    "runtimes": {
        "win7-x64": {}
    }
}
```
1. `dotnet restore`
2. `dotnet build`

```
Project dotnetdemo (.NETFramework,Version=v4.6) will be compiled because expected outputs are missing
Compiling dotnetdemo for .NETFramework,Version=v4.6
/usr/share/dotnet/dotnet compile-csc @/root/dotnetdemo/obj/Debug/net46/dotnet-compile.rsp returned Exit Code 1
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(2,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(3,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(4,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(5,11): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(2,58): error CS0518: Predefined type 'System.String' is not defined or imported
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(3,54): error CS0518: Predefined type 'System.String' is not defined or imported
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(4,67): error CS0518: Predefined type 'System.String' is not defined or imported
/root/dotnetdemo/obj/Debug/net46/dotnet-compile.assemblyinfo.cs(5,62): error CS0518: Predefined type 'System.String' is not defined or imported
/root/dotnetdemo/Program.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
/root/dotnetdemo/Program.cs(5,18): error CS0518: Predefined type 'System.Object' is not defined or imported
/root/dotnetdemo/Program.cs(7,33): error CS0518: Predefined type 'System.String' is not defined or imported
/root/dotnetdemo/Program.cs(7,23): error CS0518: Predefined type 'System.Void' is not defined or imported

Compilation failed.
    0 Warning(s)
    12 Error(s)

Time elapsed 00:00:01.7890351
```
## Expected  behavior

Not "**Compilation failed**".
## Actual behavior

**Compilation failed.**
## Environment data

> dotnet --info
> .NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

**Comment by svick** [comment]
The problem is that to compile, you need reference assemblies. And .Net Core on Linux normally does not have reference assemblies for .Net Framework.

You can work around that by installing a recent mono-devel, which includes mono's version of reference assemblies for .Net Framework (though probably not for .Net 4.6, you will need to use an older version).

But, depending on what you want to do, producing a .Net Core executable might be a better choice. If you make it [a self-contained application](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types#self-contained-application), your Windows users won't even have to install .Net Core to run it.

**Comment by borgdylan** [comment]
mono supports up to net461.

**Comment by Lakritzator** [comment]
Will that work, if I use WPF? I thought Mono doesn't have WPF.
Are there any workarounds, maybe manually copy the libraries on the system?

**Comment by borgdylan** [comment]
No WPF will not work. WPF is a windows only thing.

**Comment by piotrpMSFT** [comment]
as stated, this is not possible at the moment due to reference assemblies.
