### ISSUE TITLE
[Question] Using Program class from a class library

### ISSUE THREAD

**Issue by BadriL** [dotnet/cli#4092]
I have a .NET Core Console application referencing a .NET Core class library (My.Commons). The class library contains the `Program` class with the `Main` method. The reason for this arrangement is that the `Main` method basically starts running our own framework and the console apps using our f/w just need to specify the "commands" section like this.

"commands": {
    "runpgm": "My.Commons"
}

With that, when we run the console app, the entry point in My.Commons is used in the DNX world.

With RTM1 (dotnet CLI), can I accomplish this at all? If I set "emitEntryPoint" to true in project.json, I cannot even build, since the `Program` class is expected in that project. If I set "emitEntryPoint" to false, it cannot be executed.

**Comment by piotrpMSFT** [comment]
You would need to put a dummy entrypoint into the class that emits it. Perhaps even by deriving from your Program class in the console app project.
