### ISSUE TITLE
dotnet pack should include files from shared src projects in symbol packages

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#4094]
## Steps to reproduce
- Create a ClassLibrary project
- Add a reference to a shared src project. For instance https://dotnet.myget.org/feed/aspnetcore-master/package/nuget/Microsoft.Extensions.ActivatorUtilities.Sources.
- Run dotnet pack
## Expected  behavior

The symbol package contains shared cs files from the sources package.
## Actual behavior

Shared cs files are missing.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
Moved to NuGet/Home#3934
