### ISSUE TITLE
[Question/FeatureRequest] Support of semantic versionning while resolving dependencies

### ISSUE THREAD

**Issue by franknarf8** [dotnet/cli#4095]
Hello,

I was wondering if there are any plans on the road-map to support semantic versionning while resolving nuget packages.

i.e. In NPM, bower and many other resolvers, you have the concept of a `twiddle-wakka operator` (`~>`, `~`, `^`, depending on the platform) or some kind of range support.

e.g. `"MyNugetPackage" : "~>2.3"` would resolve to the highest version from the version 2.3 inclusively to 3 exclusively (`[2.3,3.0[`). So if 2.3, 2.4 and 3.1 were available, the previous condition would resolve to 2.4.

e.g. `"MyNugetPackage" : ">2.3"` would resolve to the highest version available from version 2.3 exclusively

Other conditions like `">=2.3"`, `"~>2.3.4"`, `">2.3,<2.6"` are left to the dev's fantasies and are handy in certain scenarios.

I know [Paket](https://github.com/fsprojects/Paket) is doing a pretty good job for resolving nuget package for the old projects formats.

**Comment by blackdwarf** [comment]
This is more of a NuGet question and I think it should go to Nuget/Home repo. 

/cc @yishaigalatzer @emgarten

**Comment by yishaigalatzer** [comment]
Top level dependencies support today the following

Minimal version >=X which is expressed as "X"
Latest version expressed in "1.*" and "1.0.0-*" for latest 1.X or latest beta

We plan to add support for "1.*-*" syntax as well.

Resolving sub dependencies as higher than minimal is still being debated, both NuGet 2.X and Paket do support it.

**Comment by franknarf8** [comment]
@yishaigalatzer 

I tried to put `1.` in one of my `project.json`'s dependencies, but `dotnet restore` gives me an error :

`'1.' is not a valid version string.`

How is the "latest version" supported exactly?

**Comment by emgarten** [comment]
@franknarf8 try ``1.*``

**Comment by piotrpMSFT** [comment]
Looks like this is resolved. If not, please re-open in https://github.com/nuget/home.
