### ISSUE TITLE
build.sh is failing in the CI builds

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#41]
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_cli_linux_debug_prtest/2/console

> mkdir: cannot create directory '/.local': Permission denied
10:12:01   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
10:12:01                                  Dload  Upload   Total   Spent    Left  Speed
10:12:01 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /.local/share/nuget.latest.exe: No such 
10:12:01 Warning: file or directory
10:12:01 
  0 3656k    0 16383    0     0   152k      0  0:00:24 --:--:--  0:00:24  152k
10:12:01 curl: (23) Failed writing body (0 != 16383)
10:12:01 curl: (3) <url> malformed
10:12:01 cp: cannot stat '/.local/share/nuget.latest.exe': No such file or directory
10:12:01 Cannot open assembly '.nuget/nuget.exe': No such file or directory.
10:12:01 Cannot open assembly '.nuget/nuget.exe': No such file or directory.
10:12:01 ./build.sh: line 33: packages/KoreBuild/build/dnvm.sh: No such file or directory
10:12:01 ./build.sh: line 37: dnvm: command not found
10:12:01 Cannot open assembly 'packages/Sake/tools/Sake.exe': No such file or directory.
10:12:01 Build step 'Execute shell' marked build as failure
10:12:01 [BFA] Scanning build for known causes...
10:12:01 [BFA] No failure causes found
10:12:01 [BFA] Done. 0s
10:12:01 Setting status of 619050ffe27dda00f6b4d55220c4c1dd675e4d56 to FAILURE with url http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_cli_linux_debug_prtest/2/ and message: 'Build finished. No test results found.'
10:12:01 Using context: Linux Debug Build
10:12:02 Finished: FAILURE

**Comment by blackdwarf** [comment]
@Sridhar-MS can we close this issue?
