### ISSUE TITLE
Deepin15.2 failure

### ISSUE THREAD

**Issue by bubifengyun** [dotnet/cli#4109]
## Steps to reproduce
Linux Deepin 15.2 is based on Debian sid. So Here no exact *.deb for it.
I try download all SDK file in 
**Ubuntu 14.04, Ubuntu 16.04, Debian 8.2** with version **1.0.0 preview 2** or**1.0.0 preview 3**, There are all failure. Here is my steps.

### 1, download sdk
from this link: https://github.com/dotnet/cli
### 2, tar sdk

```bash
sudo mkdir -p /opt/dotnet && sudo tar zxf /path/to/dotnet.dev.debian.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin
sudo apt-get install curl libunwind8 gettext libicu52
```

### 3, simple example

```bash
    mkdir hwapp
    cd hwapp
    dotnet new
```

when i input

```bash
    dotnet restore
```

it will pops
>log  : Restoring packages for /xx/project.json...
Segmentation fault

Any suggestion? THank you.

**Comment by blackdwarf** [comment]
@bubifengyun what kernel version are you using? This looks like an issue that is already tracked with 4.6.x family of Linux kernels (#3681 is the issue tracking it).

**Comment by shahmuratov** [comment]
Same bug on Ubuntu 14.04

**Comment by bubifengyun** [comment]
Thank you, soloved.

```bash
uname -a
Linux xx-pc 4.4.0-2-deepin-amd64 #1 SMP Deepin 4.4.6-4 (2016-07-01) x86_64 GNU/Linux
```

use #3185 downgrade libcurl3, it is OK.

>aptitude versions libcurl3
Package libcurl3:                              
i   7.38.0-4+deb8u3                                                              100 
p   7.47.0-1                                        <NULL>                       500 


```
dotnet --info
.NET Command Line Tools (1.0.0-preview3-003246)

Product Information:
 Version:            1.0.0-preview3-003246
 Commit SHA-1 hash:  6f974e2fed

Runtime Environment:
 OS Name:     deepin
 OS Version:  15.2
 OS Platform: Linux
 RID:         deepin.15.2-x64
```

**Comment by shahmuratov** [comment]
And what libcurl version did you used?

**Comment by bubifengyun** [comment]
7.38.0-4+deb8u3 download from debian

**Comment by bubifengyun** [comment]
@shahmuratov it is `libcurl3_7.38.0-4+deb8u3_amd64.deb`, you can google and download it.
I use `sudo dpkg -i libcurl3_7.38.0-4+deb8u3_amd64.deb` to install it. Then `dotnet restore` will not pops error.

**Comment by shahmuratov** [comment]
It seems that dotnet-dev-1.0.0-preview2-003121 depends on 7.35.0 version. So when I install 7.38 version it uninstalls dotnet. So it seems that there are only 2 ways to solve this on Ubuntu 14.04
1) Build dotnet from sources
2) Wait for fix in previewN
Besides it may be different bug.  #3185 says that there are problems in versions **higher** than 7.38 and I have bug in **lower** version. It would be interesting to see gdb stack trace of higher version. Maybe it doesn't crash inside X509_verify_cert

**Comment by bubifengyun** [comment]
Sorry, I find that even my dotnet version is `1.0.0-preview2-003121`,  and libcurl 7.38.0-4+deb8u3.
it still works well. so

> dotnet-dev-1.0.0-preview2-003121 depends on 7.35.0 version

This is wrong, it does not depend on 7.35.0
My Computer has two OS. one of them is Linux Mint 17. I test it, it works well, too.
I download dotnet for Linux Minit 17 from row `Ubuntu 14.04 / Linux Mint 17` in https://github.com/dotnet/cli .
I am not familar with dotnet core. 
I am newbee. This is my blog written in Chinese, and it may be useful. 
http://my.oschina.net/bubifengyun/blog/738634
