### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80004005 when deploying on sandstorm

### ISSUE THREAD

**Issue by pgrm** [dotnet/cli#4111]
## Steps to reproduce
- [Install vagrant-spk](https://docs.sandstorm.io/en/latest/vagrant-spk/installation/)
- clone the sample repository [pgrm/sandstorm-asp-net-core-test](https://github.com/pgrm/sandstorm-asp-net-core-test)
- inside the repository run
  
  ```
  vagrant-spk vm up
  vagrant-spk dev
  ```
- open the browser and go to http://local.sandstorm.io:6080/
- sign in with sample developer account (I always use alice)
- go to http://local.sandstorm.io:6080/apps and click on example app
- create a new instance
- open the debug log (in the top an icon which looks like a terminal - it's located between the trash bin and download arrow icons)
## Expected  behavior

At least it would be great if I could see the current dotnet version. Actually the yeoman generator default website should show up, but at least in the debug log, I should be able to see the dotnet version
## Actual behavior

```
...** SANDSTORM SUPERVISOR: Starting up grain.
dotnet --version
Failed to initialize CoreCLR, HRESULT: 0x80004005
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

However, this `dotnet --info` was executed inside the `.sandstorm/build.sh` script where dotnet works just fine, and not inside `.sandstorm/launcher.sh` script where the problems show up.

I think the problem is, because sandstorm containers don't have access to `/proc/self/exe` which was introduced with https://github.com/dotnet/coreclr/issues/1774. I tried to fake that file as discussed in https://github.com/sandstorm-io/sandstorm/issues/1582. I've set the link to point to `/usr/local/bin/dotnet` as well as `/opt/dotnet/dotnet` but in both cases I'm getting the same error.

Maybe I'm pointing it to the wrong file, or there is something more missing to make it work. Unfortunately the error message is hard to understand so some help would really be appreciated. Thx

**Comment by gkhanna79** [comment]
@ramarag Can you PTAL?

**Comment by piotrpMSFT** [comment]
any progress here?

**Comment by ramarag** [comment]
i have not tried the to set up the repro yet. Is it possible to get the repro setup which can be investigated immediately ?

**Comment by piotrpMSFT** [comment]
@ramarag, can you move this to the core-setuprepo?

**Comment by gkhanna79** [comment]
Ported to Core-Setup as https://github.com/dotnet/core-setup/issues/636
