### ISSUE TITLE
ClassLibrary reference is not removed from .NET Core project.json

### ISSUE THREAD

**Issue by mafshin** [dotnet/cli#4113]
(I'm not sure if this is the correct repo for this issue. I guess it's more a VS issue than CLI one)
## Steps to reproduce
1. Create a .NET Core app
2. Create a normal class library
3. Set both as dnx46 and .NET 4.6 to be reference-able
4. From .NET Core app add a reference to class library into 
5. Build the solution and everything works
6. Remove the Class library project from the solution
## Expected  behavior

The class library reference in `project.json` should be removed automatically.
## Actual behavior

The class library reference in `project.json` is not removed
## Environment data

.NET Command Line Tools (1.0.0-preview2-003121)

**Comment by piotrpMSFT** [comment]
Moved to VS Tooling repo :)
