### ISSUE TITLE
How do I create a library/package which only supports .NET Core?

### ISSUE THREAD

**Issue by gulbanana** [dotnet/cli#4114]
I've written some code which works on core CLR but not on .NET full. However, if I publish the package as netstandard1.5 or netstandard1.6, then .NET 4.6.2/4.6.3 will erroneously attempt to target it.

It seems that netcoreapp1.0 is only for applications, not libraries. Is there a "netcorelib" or something - a tfm supported by core but not desktop?

**Comment by davidfowl** [comment]
Netcoreapp is the right tfm for netcore only libraries as well. We just discourage it because libraries *should* run we everywhere.

**Comment by gulbanana** [comment]
nice. i'll just do that then
