### ISSUE TITLE
Using different build configurations in a solution causes dotnet build to fail

### ISSUE THREAD

**Issue by jruckert** [dotnet/cli#4117]
## Steps to reproduce

I have a repro here: https://github.com/oconics/BuildConfigRepro
1. Create a Blank dotnet Asp.Net Project using the standard template "TestApplication"
2. Create a Class Library and make sure that the AspNet Project depends on it "TestLibrary"
3. Open Build -> Configuration Manager and Add a new Project Solution Configuration "DebugClient1"
4. Configure the DebugClient1 build to be as follows:

![image](https://cloud.githubusercontent.com/assets/4064588/18071451/fdeb2902-6e94-11e6-9a6d-8fb45e7768c7.png)

AspNet Project Template project.json

```
"configurations": {
    "DebugClient1": {
      "buildOptions": {
        "define": [ "DEBUG", "TRACE", "POSTGRESQL" ],
        "optimize": false
      }
    }   
  },
```

Class Library project.json

```
"configurations": {
    "DebugClient1": {}
  }
```
1. Build the Project from the command prompt and the error occurs
## Expected  behavior

Using dotnet build from the command prompt successfully builds the AspNet Project
## Actual behavior

```
dotnet build --configuration DebugClient1 --no-dependencies
Project TestApplication (.NETCoreApp,Version=v1.0) will be compiled because expected inputs are missing
Compiling TestApplication for .NETCoreApp,Version=v1.0
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Repos\TestApplication\src\TestApplication\obj\DebugClient1\netcoreapp1.0\dotnet-compile.rsp returned Exit Code 1
C:\Repos\TestApplication\src\TestApplication\error CS0006: Metadata file 'C:\Repos\TestApplication\src\TestLibrary\bin\DebugClient1\netstandard1.6\TestLibrary.dll' could not be found

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.9380279
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14905
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by jruckert** [comment]
bump

**Comment by dneimke** [comment]
bump

**Comment by piotrpMSFT** [comment]
Per https://github.com/dotnet/sdk/pull/351, this is fixed in the preview3 CLI.
