### ISSUE TITLE
Pushing to NuGet

### ISSUE THREAD

**Issue by dknaack** [dotnet/cli#4118]
I have installed dotnet core on ubuntu and would like to push a nuget package.
On my mac, the nuget command is available but not on my ubuntu (jenkins-slave)
What is the recommend way ?

**Comment by blackdwarf** [comment]
@dknaack a good place for this issue is on Nuget/Home. 

/cc @emgarten @harikmenon

**Comment by emgarten** [comment]
The current plan is to add a ``dotnet nuget`` command which will allow access to the push command. Currently this command exists in NuGet.Commandline.Xplat.dll (in the sdk dir) but is not exposed.

https://github.com/NuGet/Home/issues/3341

**Comment by blackdwarf** [comment]
With @emgarten's explanation above, I will close this issue. Please do tell if it needs to be reopened.
