### ISSUE TITLE
dotnet -h should document "dotnet mydll.dll"

### ISSUE THREAD

**Issue by ljw1004** [dotnet/cli#4123]
@glennc writes: `dotnet run` is supposed to be for dev time; when running a compiled portable console app you would use `dotnet app.dll` directly.

Therefore: `dotnet -h` should document the ability to do `dotnet app.dll`. This appears to be a mainstream bread-and-butter scenario for the `dotnet` utility.

**Comment by ljw1004** [comment]
#3594 #2174

**Comment by blackdwarf** [comment]
@ljw1004 this has been documented in the docs.microsoft.com for .NET Core for a while and is a known thing. Adding it to the help could be done, of course, however, then we would have to have both `dotnet run` and `dotnet path/to/assembly.dll` in there.

**Comment by ljw1004** [comment]
Having both `dotnet run` and `dotnet path/to/assembly.dll` in the help sounds ideal! Granted, it'll only be valuable to the 99% of folks who don't read the docs in detail :)

**Comment by blackdwarf** [comment]
@ljw1004 well then, looking forward to your PR for this! :)

**Comment by piotrpMSFT** [comment]
Host help output now includes this content.

```
Microsoft .NET Core Shared Framework Host

  Version  : 1.0.1
  Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

To get started on developing applications for .NET Core, install .NET SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```
