### ISSUE TITLE
Question: will dotnet/sdk repo be made public?

### ISSUE THREAD

**Issue by ghost** [dotnet/cli#4129]
In some PRs, there are reference to `dotnet/sdk#$$`, but that's not accessible by public.

Will it be made public/open-source at some point?

**Comment by bleroy** [comment]
Can you point to those pull requests? It'unclear what you're referring to. Is there any part of .NET Core that you are unable to build?

**Comment by wjk** [comment]
@bleroy See for example @eerhardt's comment on #4217. I believe the `dotnet/sdk` repo contains the sources for the `Microsoft.NETCore.Sdk` NuGet package.

**Comment by bleroy** [comment]
OK, so I was able to investigate about this this morning, and the short answer is that yes, of course, this will be public. More details later today. Thanks for your patience.

**Comment by bleroy** [comment]
Finalizing the last details on this. More news later this week. Thanks for bringing this to our attention.

**Comment by bleroy** [comment]
Sorry, this is taking longer than I expected. I'll update when I have new info.

**Comment by bleroy** [comment]
The repo is now public. We also have a new blog post explaining what it's about, among other things: [.NET Core Tooling in Visual Studio "15"](https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/).

**Comment by gulbanana** [comment]
Thanks! Lots of interesting info there.
