### ISSUE TITLE
dotnet gets confused when two packages contain the same dll

### ISSUE THREAD

**Issue by svick** [dotnet/cli#4131]
## Steps to reproduce

Create the following project, where `Dapper` and `Dapper-Async` both contain `Dapper.dll`:

project.json:

``` json
{
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Dapper": "1.50.2",
    "Dapper-Async": "1.3.0"
  },
  "frameworks": {
    "net46": {}
  }
}
```

Program.cs:

``` cs
using Dapper;

public class Program
{
    public static void Main()
    {
        SqlMapper.GridReader result = null;
        result.Read<int>();
    }
}
```

Run `dotnet restore` and `dotnet run`.
## Expected  behavior

One of three options:
1. `dotnet` fails, complaining about conflicting `Dapper.dll`.
2. `dotnet` consistently uses `Dapper.dll` from `Dapper`, the project compiles using `GridReader.Read(bool buffered = true)` and runs as expected (i.e. throws a `NullReferenceException`).
3. `dotnet` consistently uses `Dapper.dll` from `Dapper-Async`, the project compiles using `GridReader.Read()` and runs as expected (i.e. throws a `NullReferenceException`).
## Actual behavior

`dotnet` uses `Dapper.dll` from `Dapper` at build and `Dapper.dll` from `Dapper-Async` at runtime, resulting in a confusing error:

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<!!0> GridReader.Read(Boolean)'.
   at Program.Main()
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

This issue is based on [this SO question](http://stackoverflow.com/q/39011399/41071).

**Comment by blackdwarf** [comment]
@svick can you try to repro this with the latest tooling?

**Comment by livarcocc** [comment]
This works in the latest 2.0 version of the CLI.
