### ISSUE TITLE
dotnet build Can not find runtime target for framework '.NETStandard,Version=v1.6'

### ISSUE THREAD

**Issue by moliveto** [dotnet/cli#4133]
15>------ Rebuild All started: Project: EbookingCoreTest, Configuration: Debug Any CPU ------
15>Build started 31/8/2016 7:42:47 p. m..
15>     1>
15>CoreCompile:
15>         C:\Program Files\dotnet\dotnet.exe build "D:\eBookingV4\tst\EbookingCoreTest" --configuration Debug --no-dependencies --no-incremental
15>         Project EbookingCoreTest (.NETStandard,Version=v1.6) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
15>         Compiling EbookingCoreTest for .NETStandard,Version=v1.6
15>     1>
15>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : Can not find runtime target for framework '.NETStandard,Version=v1.6' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
15>     1>
15>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : 1. The project has not been restored or restore failed - run `dotnet restore`
15>     1>
15>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : 2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
15>     1>
15>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(262,5): error : 3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
15>
15>Build FAILED.
15>

dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by svick** [comment]
Did you restore packages for the project, as point 1 in the error message says? If you did, could you post your project files?

**Comment by moliveto** [comment]
This is eBookingCoreTest.xproj

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
		<VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
	</PropertyGroup>

	<Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.Props" Condition="'$(VSToolsPath)' != ''" />
	
	<PropertyGroup Label="Globals">
		<ProjectGuid>e6763be7-3a97-4251-b572-28fde634c403</ProjectGuid>
		<RootNamespace>EbookingCoreTest</RootNamespace>
		<BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">.\obj</BaseIntermediateOutputPath>
		<OutputPath Condition="'$(OutputPath)'=='' ">.\bin\</OutputPath>
		<TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
	</PropertyGroup>

	<PropertyGroup>
		<SchemaVersion>2.0</SchemaVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
	</PropertyGroup>
	
	<Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.targets" Condition="'$(VSToolsPath)' != ''" />
</Project>

**Comment by svick** [comment]
Could you also post your `project.json`?

**Comment by moliveto** [comment]
Yes, you can see it bellow:
```
{
	"version": "1.0.0-*",
	"buildOptions": {
		"copyToOutput": {
			"include": [ "appsettings.json", "room.json", "project.json" ]
		},
		"warningsAsErrors": true
	},
	"dependencies": {
		"NETStandard.Library": "1.6.0",
		"dotnet-test-xunit": "2.2.0-*",
		"xunit": "2.2.0-*",
		"Moq": "4.6.38-*",
		"EBookingCoreNew": "1.0.0-*",
		"EBookingRepository": "1.0.0-*",
		"ExpediaRepository": "1.0.0-*"
	},

	"frameworks": {
		"netcoreapp1.0": {}
		//"netstandard1.6": { "imports": "dnxcore50" },
	}
}
```

**Comment by gatezy** [comment]
I am facing the same error when I deploy the project to Azure Web App. 
Have you problem solved?

**Comment by piotrpMSFT** [comment]
Test projects need to have both a testRunner attribute and emit an entrypoint. Also, since they are exe's, they must also reference netcoreapp1.0 and not NETStandard.Library.
