### ISSUE TITLE
target dir in project.json

### ISSUE THREAD

**Issue by jackywuxz** [dotnet/cli#4135]
## Steps to reproduce

.net core project, project.json file, "postcompile" in "scripts" section
## Expected  behavior

expect a variable point to the target folder, should have somethin like
%project:TargetDir%\
## Actual behavior

I have to use the following path, but if the build config or target framework change, it will fail:
%project:Directory%\bin\Debug\net451\win7-x64\
## Environment data

`dotnet --info` output:

**Comment by piotrpMSFT** [comment]
in preview3 you can use the `$(OutputPath)` property, along with many other [https://msdn.microsoft.com/en-us/library/bb629394.aspx](new [to .NET Core] properties) :)
