### ISSUE TITLE
dotnet build3 complains about duplicate TF attributes.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/cli#4138]
## Steps to reproduce
Install from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/latest.version
dotnet new -t msbuild
dotnet restore
dotnet build3

## Expected  behavior
Successful build

## Actual behavior
  C:\Users\srivatsn\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,12): error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute [C:\Users\srivatsn\Downloads\dotnet-dev-win-x64.latest\test\test.csproj]

Looks like the TFAttribute is both in the generated assemblyinfo.cs in obj and the file mentioned in the error.

## Environment data
`dotnet --info` output:

**Comment by brthor** [comment]
I can't repro this with the above steps in win10. 
I can repro when I run `dotnet build` and then `dotnet build3`

I was seeing this on OS X as well and 
https://github.com/Microsoft/msbuild/issues/970 was the cause.

It's possible a variant of this is happening on windows. 

if you `rmdir /S /Q obj` does this error go away?

**Comment by srivatsn** [comment]
Yes removing the obj directory made the error go away.

**Comment by eerhardt** [comment]
@nguerrera - who implemented the assembly attribute generation.

I think this issue actually belongs in `dotnet/sdk`...

**Comment by eerhardt** [comment]
Oh, I'm seeing a different error:

```
dotnet new -t msbuild
dotnet restore
dotnet build3     // succeeds
dotnet build3     // fails
```

`error MSB3105: The item "obj\Debug\shhsu.AssemblyInfo.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter.`

**Comment by rainersigwald** [comment]
I think this is a symptom of `Exclude` not working, which @cdmihai is fixing.

First build: success
Second build: picks up assemblyinfo in `Compile` glob (because `obj/**` exclude doesn't work), also unconditionally adds the generated one.

Likewise in the PJ-build, MSBuild scenario it picks up the different flavor of assemblyinfo.cs and complains about duplicate attributes.

**Comment by brthor** [comment]
@rainersigwald Agreed, I can't repro this without having first run an ordinary `dotnet build` which generates under obj

I don't think anything is wrong with @nguerrera 's assembly info generation. 

Being that this issue is tracked in the linked msbuild issue, let's close this out.
