### ISSUE TITLE
Migration: [KNOWNISSUE] Mappings of multiple files to a single target file

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#4140]
filing this to track a known issue. 

In project.json mapping multiple files to a single target file will cause nothing to be copied and no error to be thrown.

In MSBuild, the best we can achieve with the `AssignTargetPaths` mechanism is that the last file resolved is copied to the target path. 

MSBuild discussion tracked here: https://github.com/Microsoft/msbuild/issues/989

**Comment by piotrpMSFT** [comment]
This issue will be fixed in msbuild. There is nothing for migration to do here.
