### ISSUE TITLE
Any way to compile linux dependencies into .net core?

### ISSUE THREAD

**Issue by coderdad** [dotnet/cli#4144]
## Steps to reproduce
1. BootStrap PowerShell (for example) and Compile with -Publish Flag
2. Gzip the publish folder and copy to another 64-bit Linux Host
## Expected  behavior

Executing ./powershell on a new host will open a PowerShell terminal
## Actual behavior

Depending on host, may get missing library errors for libstdc++, libicu and/or libunwind.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-003553)

```
Product Information:
 Version:            1.0.0-preview3-003553
 Commit SHA-1 hash:  c5b2da0db5

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
```

**Comment by blackdwarf** [comment]
@coderdad no, we are not providing the ability to publish native dependencies with your code. You could use the targeted distribution's package manager to install the native dependencies and you can find which ones you need on https://github.com/dotnet/core/blob/master/Documentation/prereqs.md.

**Comment by piotrpMSFT** [comment]
These dependencies should make their way into newer base os images, so the problem will go away with time.
