### ISSUE TITLE
dotnet ef database update failed 

### ISSUE THREAD

**Issue by r105m** [dotnet/cli#4146]
## Steps to reproduce
dotnet ef database update

## Expected  behavior
sqlite base generated

## Actual behavior
Could not invoke this command with the startup project 'WebApplication'. Check that 'Microsoft.EntityFrameworkCore.Design' has been added to "dependencies" in the startup project and that the version of 'Microsoft.EntityFrameworkCore.Tools' in "tools" and 'Microsoft.EntityFrameworkCore.Design' are the same. See http://go.microsoft.com/fwlink/?LinkId=798221 for more details.

## Environment data
.NET Command Line Tools (1.0.0-preview3-003555)

Product Information:
 Version:            1.0.0-preview3-003555
 Commit SHA-1 hash:  a2b861e4c8

Runtime Environment:
 OS Name:     fedora
 OS Version:  24
 OS Platform: Linux
 RID:         fedora.24-x64

reproduced on several versions of packages 'Microsoft.EntityFrameworkCore.Tools'

**Comment by natemcmaster** [comment]
cc @divega 

@r105m EF Core issues are tracked at https://github.com/aspnet/EntityFramework

**Comment by brthor** [comment]
Going to close this issue out for tracking purposes. 

Please migrate to the repo @natemcmaster shared :smile:
