### ISSUE TITLE
Will dotnet cli tools work with class library projects in a future version?

### ISSUE THREAD

**Issue by mrahhal** [dotnet/cli#4147]
I tried searching but found nothing on the subject. I'm sure I don't need to list the use cases for this (one is having migrations in a _real_ DAL library).

Just so we know what we'll have when planning ahead. Will cli tools work with class libraries in the future? (in tooling 1.0.0 perhaps?)

**Comment by blackdwarf** [comment]
@mrahhal you can work with libraries today using the CLI tools. Indeed, this repo already does that. Can you provide more details on what you mean?

**Comment by mrahhal** [comment]
@blackdwarf a quote from [here](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#targeting-class-library-projects-is-not-supported):
> .NET Core CLI does not support running commands on class libraries as of Preview 2.

Trying to use tools inside a **Class Library Project** will throw an error.

**Comment by blackdwarf** [comment]
@mrahhal ah, ok, you meant "tools", as in, CLI extensions, not the overall CLI tools, which is what I understood you meant.

**Comment by mrahhal** [comment]
Oh yeah, sorry if that was misleading. I just saw that the issue is documented [here](https://docs.efproject.net/en/latest/miscellaneous/cli/dotnet.html#targeting-class-library-projects-is-not-supported), and I'm aware of the workarounds. So basically I'm asking if there's anything new about it (a lot of people are asking about it and I myself maintain a tool that would benefit from being used in a Class Library).

**Comment by livarcocc** [comment]
I am not sure if I understand the problem here, but I can run tools referenced inside a lib, like below.

As for EF not running on a library, if that is still the case with the latest version of their tools, please file an issue at https://github.com/aspnet/entityframework.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-portable">
      <Version>1.0.0</Version>
    </DotNetCliToolReference>
  </ItemGroup>

</Project>
```

**Comment by mrahhal** [comment]
@livarcocc this issue was about preview 2 of the tooling, the issue is still there but since all the work right now is on MSBuild it's all good :)
