### ISSUE TITLE
dotnet is too long to type

### ISSUE THREAD

**Issue by chaliy** [dotnet/cli#415]
It is expected to type many times a day. It might be benefitial to make it at max 3 chars long.

**Comment by davidfowl** [comment]
dnx?

**Comment by chaliy** [comment]
@davidfowl dnx was ok.

**Comment by shahid-pk** [comment]
or create a symlink for it , forget 3 chars just one  d instead of dotnet  :wink:

**Comment by chaliy** [comment]
problem with symlinks, links, aliases, etc that everybody on each machine will need to configure them, and what is more important is that it will not be a standard.

P.S. One char is even better.

**Comment by davidfowl** [comment]
I think dotnet is fine tbh. We spent so long trying to name DNX, at least dotnet has a meaning and isn't that bad to type

**Comment by dasMulli** [comment]
What about ".net" - at least as an alias? So you could run `.net compile --native`, `.net restore` etc.
Having a `.something` executable in your PATH should work on all platforms (even with `.cmd` or `.exe` on windows)

**Comment by rhires** [comment]
I think it should be `dnt` - I think that has cachet, panache...and it seems like "tnt" which makes it exciting! Ok, I think `dnt` is reasonable, because it keeps the commands all in the family, as it were: dnx, dnu...(what did the u stand for, anyway?) And it's fairly obvious that `dnt` is a shortened form of dotnet...

**Comment by piotrpMSFT** [comment]
@blackdwarf @richlander let's make sure we RTM with the right name :)

**Comment by tuespetre** [comment]
I think `dotnet` is just fine, but I don't see any existing command called `dn` out there for Windows or Star-nix, either.

**Comment by piotrpMSFT** [comment]
we're going with dotnet for 1.0.0 :)
