### ISSUE TITLE
build.cmd -Targets Prepare,Compile fails

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4157]
## Steps to reproduce

Using [developer-guide.md](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/developer-guide.md) instructions to build the repo

```
build.cmd -Targets Prepare,Compile
```

same error in Prompt or Powershell
## Expected  behavior

build starting...
## Actual behavior

```
e:\github\cli>build.cmd -Targets "Prepare,Compile"
E:\github\cli\run-build.ps1 : Impossibile elaborare la trasformazione degli argomenti nel parametro 'Targets'.
Impossibile convertire il valore nel tipo System.String.
In riga:1 car:42
+ & "e:\github\cli\run-build.ps1" -Targets Prepare,Compile; exit $LastE ...
+                                          ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [run-build.ps1], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,run-build.ps1
```

sry if is in italian
## Environment data

latest `rel/1.0.0` commit ab8e1b707bab7039b1b34b906a9761fd923c37dc

**Comment by piotrpMSFT** [comment]
@enricosada we updated the dev guide a while ago. Closing this issue for bookkeeping. Nice to see our build scripts in Italian!
