### ISSUE TITLE
consecutive `dotnet build3` fails with duplicated {proj}.AssemblyInfo.cs in Sources

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4158]
## Steps to reproduce

```
dotnet new -t msbuild
dotnet build3 #ok
dotnet build3 #fails
```
## Expected  behavior

also the second `dotnet build3` succeed
## Actual behavior

```
"e:\temp\prev3ms\prev3ms.csproj" (default target) (1) ->
(CoreCompile target) ->
  e:\github\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003588\Microsoft.CSharp.Core.targets(67,5): error MSB3105: The item "obj\Debug\prev3ms.AssemblyInfo.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [e:\temp\prev3ms\prev3ms.csproj]
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003588)

Product Information:
 Version:            1.0.0-preview3-003588
 Commit SHA-1 hash:  ab8e1b707b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by enricosada** [comment]
searching msbuild log, i think the issue is

The prev3ms.AssemblyInfo.cs is included by    

```
 <Compile Include="**\*.cs" Exclude="$(GlobalExclude)" />
```

so

```
Compile
    obj\Debug\prev3ms.AssemblyInfo.cs
    Program.cs
```

but later the Task "WriteCodeFragment" (TaskId:15) add it another time (not executed because up to date)

```
  Output Item(s): Compile=obj\Debug\prev3ms.AssemblyInfo.cs (TaskId:15)
```

so

```
      Sources=
          obj\Debug\prev3ms.AssemblyInfo.cs
          Program.cs
          C:\Users\e.sada\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs
          obj\Debug\prev3ms.AssemblyInfo.cs (TaskId:16)
```

**Comment by ArturKarbone** [comment]
What is the purpose of having **dotnet build3** at all? When shoud i use **dotnet build** versus **dotnet build3**? I see some other commands also have been marked with "3" postfix.

**Comment by enricosada** [comment]
`build3` (And others with 3 suffix) run the msbuild version of the commands AFAIK.

**Comment by ArturKarbone** [comment]
> build3 (And others with 3 suffix) run the msbuild version of the commands AFAIK.

Just trying to figure out when should i use msbuild-one version and why? Any use cases or a link to the docs? Thanks

**Comment by enricosada** [comment]
current released `preview2` use `project.json` as project format.
next version `preview3` will use msbuild based projects instead of `project.json`, more info in the [msdn blog](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/)

**Comment by ArturKarbone** [comment]
@enricosada, make sense now. Thanks

**Comment by piotrpMSFT** [comment]
@enricosada this got fixed some time back. I'm closing the issue for bookkeeping.
