### ISSUE TITLE
Assemblies missing after build.

### ISSUE THREAD

**Issue by kazeshini178** [dotnet/cli#4159]
I currently have a project that has a mixture of PCL (.NetStandard) dependencies and normal .net 4.6 Class library dependencies.
When I build the ASP.net MVC project 3 of the required system dll's are not outputted (namely System.Runtime, System.ObjectModel & System.Collection.Concurrent) to the bin directory of the project.  
As seen in the image.
![image](https://cloud.githubusercontent.com/assets/17514276/18339786/c9302cee-75a1-11e6-9137-a7e938bcb20e.png)

When I build one of the normal .net projects, which itself references a .NetStandard PCL the missing dll's are outputted to the ASP.net bin directory even though the class has no reference to this directory and is the only project built as see below:
![image](https://cloud.githubusercontent.com/assets/17514276/18339826/03215626-75a2-11e6-8d03-7e58ddd50ede.png)
![image](https://cloud.githubusercontent.com/assets/17514276/18339834/11dfb7a2-75a2-11e6-8781-c2cae88e1282.png)

How would I be able to get the same result from just building the ASP.net project, which intern causes the class library to build due to being a dependency?
## Steps to reproduce

Create 3 projects a ASP.net MVC project, a .net class library (non portable) and a .NetStandard 1.3 PCL.
The .NetStandard project will need to rely on System.Runtime, System.ObjectModel & System.Collections.Concurrent.

Build the ASP.net project.
## Expected  behavior

All dependencies/needed assemblies should be outputted to the bin folder to allow the application to run and being packaged in a deployment package.
## Actual behavior

System.Runtime, System.ObjectModel & System.Collections.Concurrent are missing till I build the .net class library then all assemblies are present in the bin directory.
## Environment data

`dotnet --info` output:
![image](https://cloud.githubusercontent.com/assets/17514276/18408351/a1bce444-772d-11e6-8389-7fd344f46d38.png)

**Comment by piotrpMSFT** [comment]
Did you find a workaround for this issue?

**Comment by piotrpMSFT** [comment]
@kazeshini178 please create a small repro for this bug and re-open the issue. I'd love to dig into it further but I was not able to reproduce the setup given the description above.

**Comment by odyth** [comment]
@kazeshini178 I'm also having this issue did you ever find a solution?

**Comment by kazeshini178** [comment]
no idea why I didn't get emailed about these replies..
@odyth no, sadly I didn't though I have moved from the company that I discovered the issue at, would of loved to try with the latest .net version (2.0.0) from what I can tell from the release notes is that it might have already been fixed. Will follow up with a colleague that still there and check, else will have to create a sample app and see if I can recreate again.
