### ISSUE TITLE
Can't pass arguments to application using dotnet run anymore

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#416]
Since switching to System.CommandLine this doesn't seem to work anymore:

```
dotnet run --env Development

Unhandled Exception: System.CommandLine.ArgumentSyntaxException: invalid option --env
   at System.CommandLine.ArgumentSyntax.ReportError(String message)
   at System.CommandLine.ArgumentSyntax.Validate()
   at System.CommandLine.ArgumentSyntax.Parse(IEnumerable`1 arguments, Action`1 defineAction)
   at Microsoft.DotNet.Tools.Run.Program.Main(String[] args)
```

Running the application directly works

```
./bin/Debug/dnxcore50/VsCodeAppTest --env Development
Hosting environment: Development
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down
```

**Comment by victorhurdugaci** [comment]
+1 on this. `dotnet-watch` needs it to pass arguments to the watched `dotnet`.

Probably the issue is here:
https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Run/Program.cs#L26

**Comment by victorhurdugaci** [comment]
While I'm at this I should mention that the argument parsing should be positional so you can pass the same arguments to the app being run as to `dotnet`. For example: `dotnet run` should allow me to pass `--project` to my app that's different from `--project` passed to `dotnet`. For example:

```
dotnet --project E:\p1 run --project E:\p2
```

Which will pass the first `--project` to `dotnet` and the second to the application.

Maybe a git-like separator would work too:

```
dotnet --project E:\p1 run -- --project E:\p2
```

Where `--` is the separator between the `dotnet run` arguments and the arguments being passed to the application.

**Comment by brthor** [comment]
Agreed we need positional parameters for dotnet for things like verbose output `dotnet -v ...`, but the git separator adds a lot of complexity in the default case.

Would a user be expected to type: `dotnet run -- --project ...`?

**Comment by victorhurdugaci** [comment]
Agree it adds complexity but you must have a way to distinguish between the arguments with the same name that are for different parts of the stack (the runtime and the app). So, yes, if you want `--project` just for the app then you run `dotnet run -- --project ...`

While you address this bug make sure that you allow multiple `--` because we need it for the `dotnet-watch` command. It's an extreme case but we need 3 sets of arguments: one for dotnet, one for the watcher, and one for the app being watched. So it will be like: `dotnet run <dotnetargs> -- <watcher args> -- <app args>` (ugly, I know).

**Comment by brthor** [comment]
I think this is getting away from the simplicity the cli aims to offer in default cases.

How is the user expected to use `dotnet-watch`?

**Comment by Petermarcu** [comment]
@brthor , is this already fixed?

**Comment by brthor** [comment]
Nothing went in to explicitly fix this as far as I can recall. 

@victorhurdugaci 
Is this still an issue?

**Comment by victorhurdugaci** [comment]
Nah, seems to be fixed
