### ISSUE TITLE
dotnet CLI only available on x64, but this isn't documented

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#4161]
It seems dotnet CLI is only available for amd64. Why isn't it available for 32-bit linux as well?

I followed the [steps for installing on Ubuntu 16](https://www.microsoft.com/net/core#ubuntu) but install ultimately failed. 

```
andrew@andrew-HP-Compaq-nc6320-EN370UAR-ABA:~$ sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list' 
andrew@andrew-HP-Compaq-nc6320-EN370UAR-ABA:~$ sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893Executing: /tmp/tmp.gfUsfAJshR/gpg.1.sh --keyserver
apt-mo.trafficmanager.net
--recv-keys
417A0893
gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
gpg: key 417A0893: public key "MS Open Tech <interop@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
andrew@andrew-HP-Compaq-nc6320-EN370UAR-ABA:~$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease                  
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease               
Get:5 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial InRelease [2,836 B]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [378 kB]
Get:7 https://apt-mo.trafficmanager.net/repos/dotnet-release xenial/main amd64 Packages [1,831 B]
Get:8 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [321 kB]
Fetched 799 kB in 1s (464 kB/s)                           
Reading package lists... Done
andrew@andrew-HP-Compaq-nc6320-EN370UAR-ABA:~$ sudo apt-get install dotnet-dev-1.0.0-preview2-003121 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-dev-1.0.0-preview2-003121
E: Couldn't find any package by glob 'dotnet-dev-1.0.0-preview2-003121'
E: Couldn't find any package by regex 'dotnet-dev-1.0.0-preview2-003121'
andrew@andrew-HP-Compaq-nc6320-EN370UAR-ABA:~$ cat /etc/apt/sources.list.d/dotnetdev.list
deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main
```

Inspecting the steps more closely, I see `[arch=amd64]` is included in the instructions as a package source, yet no mention is made in the same documentation that there is no support for x86. Changing this to `x86` doesn't seem to fix the problem.

Can we get the docs fixed to mention that only amd64 is supported, and consider publishing x86 binaries in the future?

Related to #3936, where at least one user has an amd64 kernel but because some part of linux still registers x86 he too can't install the bits.

**Comment by mellinoe** [comment]
32-bit systems outside of Windows are not supported right now. It's not just a packaging / installation instructions issue, either; The CLR does not actually compile for non-amd64 Unix platforms. It's on the roadmap, but not a main priority.

As for "why not":
* Frankly, not many people have asked for it. We've worked on and added a lot of different distros and versions, but 32-bit hasn't been a common request.
* It will blow up the OS testing / build / support matrix, which is already massive. Obviously this is a price we will have to pay at some point, but I guess it just hasn't reached the level of necessity yet.
* Bringing up new platforms and distros is still very complicated and manual, so adding any single configuration is difficult enough. We're working on various things to improve this, so hopefully a work item like this won't be as daunting in the future.

See https://github.com/dotnet/coreclr/issues/6162

> Can we get the docs fixed to mention that only amd64 is supported, and consider publishing x86 binaries in the future?

@blackdwarf Can we get that updated in some way?

**Comment by blackdwarf** [comment]
@AArnott @mellinoe https://github.com/dotnet/core/blob/master/roadmap.md#technology-roadmaps has only x64 for Linuxes. This is the doc that shows which OS-es are supported for .NET Core.

**Comment by piotrpMSFT** [comment]
Well said folks. Thanks for clarifying.
