### ISSUE TITLE
Build picks dependency's referenced .dll instead of project's referenced .dll

### ISSUE THREAD

**Issue by lostmsu** [dotnet/cli#4168]
Attached sample solution
[BrokenDependency.zip](https://github.com/dotnet/cli/files/468484/BrokenDependency.zip)
## Steps to reproduce

If using solution, from .zip, just build, otherwise:
- create empty solution
- create classic portable library, targeting Profile78
- add nuget reference to PCLStorage-Append package (pre-release)
- create .NET Core console app, targeting 4.6.1
- add project reference to portable library
- add nuget reference to PCLStorage-Append package (pre-release)
- build (
## Expected  behavior

project.lock.json should end up referencing lib/net45/PCLStorage.dll
drop folder (bin\Debug\net461\win7-x64) should contain PCLStorage.dll copied from the path above
## Actual behavior

project.lock.json should end up referencing lib/net45/PCLStorage.dll - that holds
drop folder contains PCLStorage.dll from lib/portable-net45+sl4+wp71+win8
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by lostmsu** [comment]
Also, I noticed, that projects, that rely on Microsoft.Bcl.Async to get the right assembly dropped fail to do so as well. For example, System.IO.Compression.

**Comment by piotrpMSFT** [comment]
Why is `lib/net45/PCLStorage.dll ` more correct? Both claim to target net45...

**Comment by lostmsu** [comment]
@piotrpMSFT it might be a design problem.
I guess current approach is the first matching wins.
Old-style build approach was to pick the library referenced by project currently being built over a reference of a reference. Many packages rely on this to have stubs for portable libraries, that are replaced with concrete implementations of the final platform. System.IO.Compression is an example of that approach.
There's also an option to always pick the most specific matching version.
Or - to have some other mechanism like requiring user to manually solve the dependency.

Old-style resolution allowed a useful pattern for cross-platform nuget packages with specific platform implementation.

**Comment by piotrpMSFT** [comment]
https://docs.nuget.org/ndocs/guides/create-cross-platform-packages

It would be great if PCLStorage-Append could be moved to the new NuGet package format [above]. The tools are much more deterministic in the new design than they were with the PCL portable-++++ format. You could imagine looking at old-style packages differently, but that algorithm is fairly baked and it's limitations were better addressed in the new format.
