### ISSUE TITLE
Question: How do I start Kestrel?

### ISSUE THREAD

**Issue by dealdiane** [dotnet/cli#417]
It seems `dotnet` doesn't have the concept of `commands` any more. When I tried out a vanilla ASPNET 5 RC1 website, for the love of me, I couldn't figure out how to start up kestrel. How do I do this? Does this work with RC1 or do I need RC2 bits? 

The [project.json](https://github.com/aspnet/Home/blob/dev/samples/latest/HelloMvc/project.json) from the Home repo looks like it still has the `web` command in it which doesn't help with the confusion at all.

**Comment by davidfowl** [comment]
The dotnet cli does not work with rc1

**Comment by giggio** [comment]
Will it work with RC2? And any idea when that would be due, the roadmap on aspnet/home does not show any dates yet.

**Comment by davidfowl** [comment]
@giggio Take a look at samples here https://github.com/davidfowl/dotnetcli-aspnet5

**Comment by giggio** [comment]
@davidfowl So we are back to the old model where all apps produce an `.exe` and we run it directly. There will be no more `dnx <command>`? Is this written down anywhere so I can read more about it?

**Comment by shahid-pk** [comment]
@giggio  commands are still their in dotnet/cli not sure how much they are similar to what commands were in dnx.
for example look at this pr https://github.com/dotnet/cli/pull/727.
I think they are packaged applications which you can invoke from dotnet/cli. I may be wrong

**Comment by giggio** [comment]
@shahid-pk Yes, those seem to be dnu commands. It seems there is `tools` value on `project.json`, where you can call for some tools, too, but I am not sure how that is related.
It seems that the old way, with commands for an app, from `project.json`,  where you could have multiple "entry points" to your app are gone.
For example, if your app was named `app`, you could do:

````json
{
    "commands": {
        "dothis": "app foo",
        "dothat": "app bar"
    }
}
````

And after you packaged the app, you would end up with `dothis.cmd` and `dothat.cmd` and, you could call them both after `dnu commands install`. It seems we will not be able to do that, anymore.

**Comment by blackdwarf** [comment]
@giggio since the original question from the issue has been answered, I will close this issue. Please reopen if needed.
