### ISSUE TITLE
dotnet restore with multiple project.json files

### ISSUE THREAD

**Issue by Meir017** [dotnet/cli#4173]
## Steps to reproduce

sample project - https://github.com/Meir017/DotnetRestoreError
## Expected  behavior

running the command `dotnet restore` should not fail
## Actual behavior

dotnet restore
error: Error reading 'D:\Repos\DotnetRestoreError\src\DotnetRestoreError\wwwroot\project.json' at line 295 column 18 : Invalid JavaScript property identifier character: .. Path 'definitions.runtimeOptions.properties.configProperties.properties', line 295, position 18.
error:   Invalid JavaScript property identifier character: .. Path 'definitions.runtimeOptions.properties.configProperties.properties', line 295, position 18.
## Environment data

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

**Comment by mellinoe** [comment]
[This project.json file](https://github.com/Meir017/DotnetRestoreError/blob/master/src/DotnetRestoreError/wwwroot/project.json) is not a valid .NET Core project file; it doesn't look like it is a valid json file at all. The default behavior for `dotnet restore` as you're using it is to recurse in all subdirectories and find "project.json" files to restore. So it tries to handle this file and blows up managing to even parse it. Are you expecting a better error message in this case, or something else?

**Comment by Meir017** [comment]
The project.json that the dotnet cli is complaining about is located in the wwwroot and is intended to be served to the client as static files. It's the schema for project.json files

**Comment by piotrpMSFT** [comment]
The preview3 CLI has moved from project.json to csproj. As part of that move, the recursive behavior described here has been removed. See #3409 for more details.

**Comment by piotrpMSFT** [comment]
#4569 actually has a better explanation.
