### ISSUE TITLE
dotnet restore fail debian 9

### ISSUE THREAD

**Issue by msmaldi** [dotnet/cli#4179]
Is not possible?

## Steps to reproduce
`dotnet -v restore
Telemetry is: Enabled
log  : Restoring packages for /home/msmaldi/Documents/dev/csharp/hwapp/project.json...
Segmentation fault`

## Environment data
NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian.-x64

**Comment by augusteiner** [comment]
what is the output of `uname -a`?
which kernel version?

this is a known bug related to kernel version ~4.x (probably related to #3681)

**Comment by msmaldi** [comment]
@augusteiner nice man, its work
