### ISSUE TITLE
Debugging with CLI

### ISSUE THREAD

**Issue by xanather** [dotnet/cli#418]
Will support for visual studio be coming? Right now is difficult to debug a CLI project, I have been using DNX (for debugging) alongside CLI but it feels like segmented development.

Just wondering if there's any plans for integration with VS for the next .NET Core release candidate?

**Comment by piotrpMSFT** [comment]
Yes, IDE integration is on the roadmap.

**Comment by davidfowl** [comment]
The DNX tooling will morph into cli tooling

**Comment by blackdwarf** [comment]
@xanather seems like the question from the issue has been answered. I will close this issue. Please reopen if needed.
