### ISSUE TITLE
project.json mappings: copyToOutput unable to copy files to the root of destination folder

### ISSUE THREAD

**Issue by jwu-au** [dotnet/cli#4181]
## Steps to reproduce

Having a test project's project.json, try to using mappings copy settings files from other project to its output root folder:

``` json
"buildOptions": {
  "copyToOutput": {
    "mappings": {
      "./": "../../src/ApiProject/appsettings*.json"
    }
  }
}
```
## Expected  behavior

Copied all appsettings*.json files to the root of output folder
## Actual behavior

Didn't copy anything
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003599)

Product Information:
 Version:            1.0.0-preview3-003599
 Commit SHA-1 hash:  4e67459f0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
## Workaround

By specifying file one by one.

``` json
  "buildOptions": {
    "copyToOutput": {
      "mappings": {
        "appsettings.json": "../../src/ApiProject/appsettings.json",
        "appsettings.Development.json": "../../src/ApiProject/appsettings.Development.json"
      }
    }
  }
```

Above is not acceptable for large amount of files.

**Comment by piotrpMSFT** [comment]
in preview3 csproj files you will be able to use globbing to handle large amounts of files.
