### ISSUE TITLE
Can't do git clean on windows, paths too long

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#4182]
## Steps to reproduce
1. Do a fresh clone on a windows box
2. Build
3. git clean -fdx (careful, see step 1)
## Expected  behavior

It works
## Actual behavior

Warnings (1 of many shown below), not everything is cleaned

```
warning: Could not stat path 'test/dotnet-publish.Tests/bin/Debug/netcoreapp1.0/PortableAppWithIntentionalDowngradePublishesDowngradedManagedCode/
PortableTests/PortableAppWithIntentionalManagedDowngrade/bin/Debug/netcoreapp1.0/PortableAppWithIntentionalManagedDowngrade.deps.json': 
Filename too long
```

Guessing CLI team doesn't use Windows much :grin: @eerhardt have you seen this?

**Comment by nguerrera** [comment]
Workaround: move test/ folder out of repo, and git reset --hard to get just the source back

**Comment by luisa123456** [comment]
Long Path Tool is the perfect utility that can solve all the long path issues. Download this software online.

**Comment by piotrpMSFT** [comment]
http://ourcodeworld.com/articles/read/109/how-to-solve-filename-too-long-error-in-git-powershell-and-github-application-for-windows

I haven't tried it, but I'm hopeful :) Can you let us know if this works, @nguerrera ?

**Comment by piotrpMSFT** [comment]
did you get a chance to try that out?

**Comment by nguerrera** [comment]
Not yet. Gotta wonder why this isn't the default.

**Comment by piotrpMSFT** [comment]
agreed. probably worried people have exception-driven logic :-/

**Comment by livarcocc** [comment]
I have used this for a while with success: `git config --system core.longpaths true`. @nguerrera if this does not solve it for you, please, re-activate.

**Comment by Mafii** [comment]
Using mingw/git bash on windows, I had to run `git config --global core.longpaths true`.
