### ISSUE TITLE
Add pretest  and posttest script extension points (feature request)

### ISSUE THREAD

**Issue by comdiv** [dotnet/cli#4189]
For example I want to use ReportUnit to auomatically update HTML from TestResult.xml
## Steps to reproduce

For now It's required to write something like this: dotnet test & ReportUnit.exe .\TestResult.xml
## Expected  behavior

I want to write to project.json something like
{
   "scripts": {
        "posttest" : "ReportUnit.exe .\TestResult.xml"
   }
}
and have this artifact just after "dotnet test"

**Comment by piotrpMSFT** [comment]
@comdiv the new msbuild implementation of `dotnet test` actually just [invokes](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-test/Program.cs#L165) `msbuild /t:VSTest` behind the scenes. You will be able to create your own targets that run before or after this target name and light up exactly these sorts of experiences!
