### ISSUE TITLE
Setup  .NET Core failed

### ISSUE THREAD

**Issue by Innocence** [dotnet/cli#4190]
Setup Failed

One or more issues caused the setup to fail.Please fix the issues and then retry setup.
For more information see the log file.

**Comment by Sridhar-MS** [comment]
@Innocence can you share the log file at  %temp%, something like `Microsoft_.NET_Core_1.0.1_-_Runtime_nnnnnnn.log` and the OS info? We recently hit an issue with the VC++ Redist chaining. The work around for that is

-	Install vc_ redist from http://go.microsoft.com/fwlink/?LinkID=615460&amp;clcid=0x409
-	And then Install the .Net Core

**Comment by GuardRex** [comment]
@Sridhar-MS In the Publish to IIS doc for the troubleshooting item that deals with the VC++ redist, I'm going to update the link from https://www.microsoft.com/en-us/download/details.aspx?id=48145 to the one you posted. Stop me if that's a bad move for some reason. cc/ @Rick-Anderson @spboyer

**Comment by Sridhar-MS** [comment]
The link posted in my workaround is the latest VC++ redist. Thats the right one.

**Comment by GuardRex** [comment]
Cool - thx @Sridhar-MS ... I put in https://github.com/aspnet/Docs/pull/1926 to get the link updated.

**Comment by eerhardt** [comment]
@Sridhar-MS - is this issue fixed?  Can it be closed?

**Comment by Sridhar-MS** [comment]
This is fixed by https://github.com/dotnet/cli/pull/4295
