### ISSUE TITLE
Migration: Dont emit X-Targetting Elements when a project has 1 TFM

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#4194]
If the project has only one TFM, don't emit things like `TargetFrameworks`

**Comment by piotrpMSFT** [comment]
@brthor did #4185 resolve this issue?

**Comment by brthor** [comment]
Decisions here have been flip flopping. 

@livarcocc @eerhardt @nguerrera Is this the behavior folks have landed on?

**Comment by nguerrera** [comment]
Yes. we've landed on using `<TargetFramework>` no S for non x-targeting. And there should be no conditions needed either, etc.

**Comment by brthor** [comment]
Thanks @nguerrera
