### ISSUE TITLE
"dotnet restore" not resolving project

### ISSUE THREAD

**Issue by mmalyska** [dotnet/cli#4197]
## Steps to reproduce

Copy sample from here:
https://github.com/mmalyska/Restore_Problem

run "dotnet restore"
## Expected  behavior

Same as restore from Visual Studio 2015 Update 3
(you can try WebApplication.sln and restore works)
## Actual behavior

Throws error:
"Unable to resolve 'Repositories (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'."
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
I just ran this repro and found that while the `Repositories` project restores successfully, the WebApplication project does not. The reason for this is that the global.json file in the WebApplication directory does not point to the Repositories project directory as a source location. as a result, we cannot find the project dependency and fail to restore.

You can change the global.json in the WebApplication directory to make the restore work:

````
projects": [ "src", "test", "../Repositories/src" ],
````
