### ISSUE TITLE
Visual Studio Debugger unable to start a dotnet-cli project with outputName build Option

### ISSUE THREAD

**Issue by couven92** [dotnet/cli#4198]
## Steps to reproduce

Example `project.json`

``` json
{
  "buildOptions": {
    "emitEntryPoint": true,
    "outputName": "sample"
  },
  "frameworks": {
    "net451": {},
    "netcoreapp1.0": {
      "imports": [ "dnxcore5.0" ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.1-*",
          "type": "platform"
        }
      }
    }
  }
}
```

Note that the `#/buildOptions/outputName` key is set. Given that the project.json file resides in a folder whose name is different from the specified outputName, the build output is not named after the project name.

Now build the project in Visual Studio and Start Debugging the project. (e.g. by pressing F5, klicking the menu item `Debug->Start Debugging`, or any other means of starting the debugger with a project in Visual Studio).
## Expected  behavior

The Visual Studio debugger should start the application and immediately be attached to it. Any Breakpoint placed in the Main method of the entry point class should be hit immediately. Visual Studio should be placed in Debugging mode.

Specifically, the Visual Studio debugger should be able to take the `outputName` property into account and find the appropiate output target debuggee accordingly.
## Actual behavior

After the build completes (or after dotnet decides to skip compilation, because the build targets are up to date), Visual Studio issues an error message: 

> The debug executable '$(ProjectDir)bin\$(Configuration)\$(TargetFramework)\win7-x64\$(ProjectName).exe' specified in the '$(ProjectName)' debug profile does not exist.

Personal information was stripped from the error message above and replaced by the appropiate MSBuild properties. This also demonstrates that the error message consistently shows up regardless of the Configuration or selected Target Framework in the Debug Launch Profile selector.

The error also shows even if I actually bother to create a `launchSettings.json` file. The Visual Studio project properties page suggestively creates the following launch settings file as default:

``` json
{
  "profiles": {
    "$(ProjectName)": {
      "command": "project"
    }
  }
}
```

_Again the project name has been ommitted from the JSON above and been replaced by the appropiate MSBuild property_
## Workaround

Examining the `launchSettings.json` file more closely, and deducing myself to the capabilities of the file by guessing from the suggestions made from IntelliSense (there **SHOULD** be a documentation for `launchSettings.json`), I managed to hard-code the output path in the `executablePath` key for a debug profile.

The file would then look like this:

``` json
{
  "profiles": {
    "$(ProjectName)": {
      "executablePath": "bin/$(Configuration)/net451/win7-x64/sample.exe"
    }
  }
}
```

**NOTE**: The contents of the `executablePath` can be copied verbatim and can include MSBuild properties, Visual Studio can cope with that.

However, this workaround poses several problems:
- Even though the path can adapt to Debug/Release configuration changes, that is the only part I managed to make generic.
- The executable path cannot take the selected target framework into account, as there does not seem to be an appropiate MSBuild property for that. (`$(TargetFrameworkMoniker)` resolves to strings like `.NETCoreApp,Version=v1.0` which is not the same as the framework identifier that is part of the actual executable path)
- The executable path cannot take the runtime id into account, as there does not seem to be an appropiate MSBuild property for that. If the project ever were to be debugged on a different version of Windows (e.g. and x86 version), the debugger would fail again.
- The executable path **MUST** include the file extension. This is problematic when there are different file extensions for full framework vs. .NET Core builds

These problems can be addressed by creating multiple debug profiles, but this defies the purpose of the already existing functionality in Visual Studio, like e.g. the Target Framework selector
### XPROJ

I have verified that the `.xproj` file indeed refers to the Dotnet `.targets` and `.props` files (as opposed to the previous DNX files)
### `dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14926
 OS Platform: Windows
 RID:         win10-x64
```
### Visual Studio product details:

```
Microsoft Visual Studio Enterprise 2015
Version 14.0.24425.01 Update 3
```

Installed products:

```
Microsoft .NET Core Tools (Preview 2) Version 14.1.20810.0
[...]
```

**Comment by piotrpMSFT** [comment]
@couven92 thanks for the detailed issue, repro, and workaround. This looks like an issue in the VS tooling, so I moved to their repo for initial investigation. Thanks!
