### ISSUE TITLE
installed dotnet sdk 1.0.0-preview3-003618 and got a virus response from Windows Defender

### ISSUE THREAD

**Issue by JamesWTruher** [dotnet/cli#4202]
## Steps to reproduce
install dotnet sdk

## Expected  behavior
no virus warning

## Actual behavior
detected: 
Trojan:Win32/Fanoly.F!cl
```
Windows Defender has detected malware or other potentially unwanted software.
 For more information please see the following:
http://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Fanoly.F!cl&threatid=2147696807&enterprise=1
 	Name: Trojan:Win32/Fanoly.F!cl
 	ID: 2147696807
 	Severity: Severe
 	Category: Trojan
 	Path: file:_C:\Users\jimtru\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview3-003618\csc.exe
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	User: REDMOND\jimtru
 	Process Name: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
 	Signature Version: AV: 1.227.2676.0, AS: 1.227.2676.0, NIS: 116.26.0.0
 	Engine Version: AM: 1.1.13000.0, NIS: 2.1.12706.0
```

## Environment data
`dotnet --info` output:

```
PS C:\Users\jimtru\src\github\forks\PowerShell-1> dotnet --info
.NET Command Line Tools (1.0.0-preview3-003618)

Product Information:
 Version:            1.0.0-preview3-003618
 Commit SHA-1 hash:  0ce597a147

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by lzybkr** [comment]
I'm seeing the same thing - machine was rebuilt today so the machine was probably clean to start with.

**Comment by jaredpar** [comment]
Where are you installing the dotnet SDK from?  Want to use the same location when testing out on my VM.

**Comment by JamesWTruher** [comment]
i believe it's coming out of https://dotnetcli.azureedge.net/dotnet

**Comment by lzybkr** [comment]
I received confirmation from the defender team, this is a false positive and they've updated their signatures.

**Comment by lzybkr** [comment]
@JamesWTruher - I think you can close this.

**Comment by svick** [comment]
This just happened to me today when running build.cmd on this repo. Windows Defender (definitions from 12. 10. 2016 19:25) detects csc.exe as Trojan: Win32/Fanoly.F!cl. Based on the output of build.cmd, the file comes from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-003842/dotnet-dev-win-x64.1.0.0-preview3-003842.zip.

This causes build.cmd to fail with:

```
E:\Users\Svick\git\cli\build\Microsoft.DotNet.Cli.Compile.targets(193,7): error MSB4018: The "Crossgen" task failed unexpectedly.\r [E:\Users\Svick\git\cli\build.proj]
E:\Users\Svick\git\cli\build\Microsoft.DotNet.Cli.Compile.targets(193,7): error MSB4018: System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software\r [E:\Users\Svick\git\cli\build.proj]
```

Output from Windows Defender,
> Category: Trojan

> Description: This program is dangerous and executes commands from an attacker.

> Recommended action: Remove this software immediately.

> Items: 
file:E:\Users\Svick\git\cli\.dotnet_stage0\x64\sdk\1.0.0-preview3-003842\csc.exe

**Comment by jaredpar** [comment]
The AV team corrected this issue a week or so ago.  Are your definitions up to date?

**Comment by svick** [comment]
I did check that my definitions were recent (like I said, from 12 October), but didn't think of manually updating them. Now I did and with definitions from 13 October, it's still being detected. So it doesn't look corrected to me.

**Comment by jaredpar** [comment]
@svick thanks for checking.  Going to ping the AV team and see what's going on.

**Comment by livarcocc** [comment]
I think this has been resolved now. Closing this. In case we run in some more cases of this, please, re-activate.
