### ISSUE TITLE
Need to create MSBuild-based "publish" command

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4204]
Today there is no MSBuild-based "publish" command.  We should create one that publishes MSBuild projects and takes the applicable options that `dotnet publish` takes today.

In order to provide the correct behavior for self-contained apps, we need https://github.com/NuGet/Home/issues/3465 to be supported.

**Comment by wjk** [comment]
@eerhardt Using the current preview bits (version 1.0.0-preview3-003618) I can `dotnet restore` and `dotnet build3` a project properly. However, when I `dotnet build3 -t:Publish`, it will not copy the DLLs correctly for a self-contained app. Under all circumstances that I have tested, the `*.deps.json` file required for shared-framework runtimes will be written, even if I configure the `project.json` to specify otherwise, and even if I pass a specific RID using `-p:RuntimeIdentifier=<>`. Legacy (non-MSBuild) CLI does this correctly.

I don’t quite understand how NuGet/Home#3465 factors into this. As far as I know, the implementation of `dotnet restore` does not affect how `dotnet publish` operates. Could you please clarify how that issues factors into this, and what (if anything) can be done to workaround this issue? I have migrated one of my .NET Core projects (private repo) to .NET CLI/MSBuild already, partially due to the legacy CLI framework not fully supporting my application’s specific build requirements, and this is blocking me from being able to debug my application in the environment that it will be run by the end user in.

**Comment by eerhardt** [comment]
@wjk - in the .NET CLI/MSBuild world, all of the build and publish logic is contained in the Microsoft.NETCore.Sdk nuget package that you reference.  If you are/were on an early build of that nupkg, self-contained publish might not be implemented yet.  Can you try upgrading your Sdk dependency to the latest and try again?  `1.0.0-alpha-20160927-1`.

To make it work in the current code, you have to do some special steps that won't be required once all the features are complete.

1. Ensure you don't have `type: platform` on your Microsoft.NETCore.App dependency in your project.json.
2. Ensure you have the correct "runtimes" listed in your project.json.  ex. `win10-x64`.
3. `dotnet restore` your project after making these changes.
4. Use this command line to call publish: `dotnet build3 /t:Publish /p:RuntimeIdentifier=win10-x64` (replace `win10-x64` with the actual RID you are targeting).

>I don’t quite understand how NuGet/Home#3465 factors into this.

We are working on eliminating the project.json from your project completely.  All dependencies will be listed in the .csproj when that happens.  However, there is no place to put the "runtimes" section in a .csproj, and so we need to a way to pass the runtime identifiers into NuGet restore.  Self-contained apps need the runtime-specific assets for the platform you are targeting.

**Comment by wjk** [comment]
@eerhardt When I upgrade a brand-new (as in `dotnet new -t MSBuild` new) project to use the version of the Sdk package you specified, `dotnet restore` fails with the following output:

```
log  : Restoring packages for /Volumes/Sources/tmp/project.json...
error: Unable to resolve 'Nuget.Build.Tasks.Pack (>= 3.6.0-beta.1.msbuild.16)' for '.NETCoreApp,Version=v1.0'.
log  : Lock file has not changed. Skipping lock file write. Path: /Volumes/Sources/tmp/project.lock.json
log  : Restore failed in 1119ms for /Volumes/Sources/tmp/project.json.

Errors in /Volumes/Sources/tmp/project.json
    Unable to resolve 'Nuget.Build.Tasks.Pack (>= 3.6.0-beta.1.msbuild.16)' for '.NETCoreApp,Version=v1.0'.
```

My NuGet.Config file has the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by eerhardt** [comment]
That package exists on "NuGet Build" feed, can you add the following line:

`<add key="nugetbuild" value="https://www.myget.org/F/nugetbuild/api/v3/index.json" />`

To your NuGet.config?

@rrelyea @rohit21agrawal @emgarten - what do you guys think about adding this package to the dotnet-core feed, so every customer doesn't need to add the `nugetbuild` feed to all of their configs?

**Comment by rohit21agrawal** [comment]
@eerhardt makes sense.. i think we'll have to add all *.beta.1.msbuild.* packages to the feed?
@emgarten thoughts?

**Comment by wjk** [comment]
@eerhardt With that feed added, `dotnet restore` completes successfully, but now `dotnet build3` gives the following error:

```
"/Volumes/Sources/tmp/tmp.csproj" (Publish target) (1) ->
(_CopyResolvedFilesToPublishAlways target) -> 
  /Users/wjk/.nuget/packages/microsoft.netcore.sdk/1.0.0-alpha-20160927-1/build/netstandard1.0/Microsoft.NETCore.Publish.targets(132,11): error MSB4064: The "UseSymboliclinksIfPossible" parameter is not supported by the "Copy" task. Verify the parameter exists on the task, and it is a settable public instance property. [/Volumes/Sources/tmp/tmp.csproj]
  /Users/wjk/.nuget/packages/microsoft.netcore.sdk/1.0.0-alpha-20160927-1/build/netstandard1.0/Microsoft.NETCore.Publish.targets(126,5): error MSB4063: The "Copy" task could not be initialized with its input parameters.  [/Volumes/Sources/tmp/tmp.csproj]
```

**Comment by eerhardt** [comment]
Try the latest CLI version - `1.0.0-preview3-003705`.  The feature `UseSymboliclinksIfPossible` just came into MSBuild, and the new SDK is taking advantage of it.  You need the newest CLI which has the newest MSBuild in it.

**Comment by wjk** [comment]
@eerhardt That did it! .NET CLI with MSBuild now publishes successfully.

**Comment by emgarten** [comment]
> what do you guys think about adding this package to the dotnet-core feed, so every customer doesn't need to add the nugetbuild feed to all of their configs?

Sounds like a good idea to me.
