### ISSUE TITLE
Rename the MSBuild-based commands to not have a "3" suffix

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4205]
The following commands are MSBuild-based and are the real commands going forward.  We should start calling them by their official names:

- restore3
- pack3
- run3
- build3

**Comment by piotrpMSFT** [comment]
My plan was to do this after @jgoshi and @livarcocc finish removing PJ from the CLI repo.

**Comment by eerhardt** [comment]
@piotrpMSFT - is there a reason we need to wait?  Why not pin the stage0 CLI, and start the process?  We aren't maintaining the project.json based code in the CLI anyway, so using the latest stage0 doesn't gain us anything.
