### ISSUE TITLE
Need to remove unofficial CSC tooltask package

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4207]
When we first enabled MSBuild support in the CLI, we took a shortcut and used the unofficial CSC task that build-tools was using in order to call the CSC compiler cross platform.  The CLI is currently dependent on this unofficial nuget package:  https://github.com/dotnet/cli/blob/rel/1.0.0/src/tool_msbuild/project.json#L14

```
 "Microsoft.Net.Compilers.Targets.NetCore": "0.1.5-dev",
```

Instead we need to replace this with the official version that came with https://github.com/dotnet/roslyn/issues/9640:  `Microsoft.CodeAnalysis.Build.Tasks`.

A few problems to solve when doing this:

1. Need to update to Roslyn 2.0.0-beta, since this package is only supported with the newest Roslyn.
2. In order to invoke csc on .NET Core, @agocke recommends that we add an executable file named "csc" that will call `dotnet csc $@`.  non-Windows would use a shell script, and Windows could use a .cmd file.

**Comment by livarcocc** [comment]
Blocked by https://github.com/dotnet/roslyn/issues/13966#issuecomment-248772844.
