### ISSUE TITLE
dotnet-restore should use nuget, not dnu

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#421]

**Comment by piotrpMSFT** [comment]
@anurse, I've heard you're on point for this issue. Is this coming in today?

**Comment by anurse** [comment]
Maybe, it depends on a number of things. Mostly there are a few minor issues still with NuGet to resolve. It's pretty close though.

**Comment by piotrpMSFT** [comment]
If there is remaining work here that is not covered by #904 it must be PR'd into the 1.0.0 release branch:

https://github.com/dotnet/cli/tree/rel/1.0.0

**Comment by anurse** [comment]
This is done!
