### ISSUE TITLE
`dotnet new` templates should all be MSBuild based projects

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4210]
We need to switch all our `dotnet new` templates to no longer be project.json-based.  Instead they all should use MSBuild project files.

**Comment by blackdwarf** [comment]
@eerhardt will this require restore to fully work because of tests?

**Comment by eerhardt** [comment]
Yes.

**Comment by piotrpMSFT** [comment]
is anything blocking this work?

**Comment by eerhardt** [comment]
Imports are necessary for converting the xunit test and web project templates.

See https://github.com/dotnet/sdk/tree/master/src/Templates for the templates that will be in VS - we should keep our templates as close to theirs as possible.  (someday we will share)

**Comment by eerhardt** [comment]
@piotrpMSFT - is this work done?

**Comment by livarcocc** [comment]
I will close it when I add the xunit test template.
