### ISSUE TITLE
Add a new CSProjectToolsCommandResolver

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#4213]
This new resolver will read the assets.json file and will:
1. Load the tools using the tools node from the lock file.
2. Take the package directory using the FallbackResolver logic from the SDK.
3. Generate the DepsJson for the tools.

Basically, we are going to have modify/add new implementations of https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolution/ToolPathCalculator.cs and https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolution/ProjectToolsCommandResolver.cs.

**Comment by livarcocc** [comment]
Blocked by https://github.com/NuGet/Home/issues/3472.

**Comment by muratg** [comment]
Looks like NuGet bug is closed: https://github.com/NuGet/Home/issues/3472

What's the status of this one? It's blocking a couple of our tools (linked above).

cc @Eilon

**Comment by muratg** [comment]
@livarcocc is this unblocked now?
