### ISSUE TITLE
Mac OSX 10.12: System.DllNotFoundException: WS2_32.dll

### ISSUE THREAD

**Issue by morethanfire** [dotnet/cli#4219]
## Steps to reproduce
Upgraded OSX to Sierra (10.12). Ran `dotnet run`. Had to install libuv again? Ran `dotnet run` again. 

## Expected  behavior
The app to run normally.

## Actual behavior
```
Unhandled Exception:
System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: WS2_32.dll
```
Full stacktrace output:
[full_stack-msg.txt](https://github.com/dotnet/cli/files/487798/full_stack-msg.txt)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

`mono -V` output:
```
Mono JIT compiler version 4.6.0 (Stable 4.6.0.245/746756c Mon Sep 19 13:58:20 BST 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by antonheryanto** [comment]
had this issue also after upgraded to macOS  Sierra (10.12)
for project using netcoreapp1.0 its running perfectly fine
but for project running full framework (net451 using mono because had library not support coreclr yet) I have to run dotnet cli like this
```sh
MONO_ENV_OPTIONS="--arch=64" DOTNET_RUNTIME_ID="osx" dotnet run
```

**Comment by morethanfire** [comment]
Thank you @antonheryanto, this worked for me.
