### ISSUE TITLE
Dotnet pack on Ubuntu: The underlying compression routine could not be loaded correctly.

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#422]
1. Clone [Common](https://github.com/aspnet/common)
2. Run `dotnet pack` in `src/Microsoft.Extensions.ActivatorUtilities.Sources`

Result:

```
~/dev/aspnet/Common/src/Microsoft.Extensions.ActivatorUtilities.Sources$ ../../packages/cli/bin/dotnet pack
Producing nuget package for Microsoft.Extensions.ActivatorUtilities.Sources
The underlying compression routine could not be loaded correctly.
```

Blocking ASP.NET build.

**Comment by pakrym** [comment]
Resolved by https://github.com/dotnet/cli/commit/3c1c747d9dfd582b34c4ef0eefd2c09c5c498ae4
