### ISSUE TITLE
Cannot build cli on Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by parjong** [dotnet/cli#4226]
I tried to build ``cli`` on Ubuntu 14.04 (x64) machine with ``build.sh``, but encountered the following error:
```
$ ./build.sh

     1>/home/parjong/projects/toolchains/dotnet-cli/build/Microsoft.DotNet.Cli.Prepare.targets(192,5): error MSB6006: "dotnet" exited with code 2. [/home/parjong/projects/toolchains/dotnet-cli/build.proj]
     1>Done Building Project "/home/parjong/projects/toolchains/dotnet-cli/build.proj" (default targets) -- FAILED.

Build FAILED.

       "/home/parjong/projects/toolchains/dotnet-cli/build.proj" (default target) (1) ->
       (RestorePackages target) ->
         /home/parjong/projects/toolchains/dotnet-cli/build/Microsoft.DotNet.Cli.Prepare.targets(192,5): error MSB6006: "dotnet" exited with code 2. [/home/parjong/projects/toolchains/dotnet-cli/build.proj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:43.54
```

Is there any known issue?

I used code from the following commit:
```
$ git log 
commit bf8b588e8b3c330e1fb2852df97c404a047327ee
Author: Rohit Agrawal <ragrawal@microsoft.com>
Date:   Wed Sep 21 16:39:59 2016 -0700

    add includesymbols and includesource to pack3 command as symbols package is not created by default (#4193)
```

**Comment by svick** [comment]
That does not look like the full output of `build.sh` to me, could you post that?

**Comment by parjong** [comment]
[Here](https://github.com/dotnet/cli/files/509665/build.txt) is the output of ``build.sh`` (I captured it via running ``./build.sh &> build.txt``)

**Comment by svick** [comment]
The error message is:

> error CS7027: Error signing output with public key from file '/home/parjong/projects/toolchains/dotnet-cli/tools/Key.snk' -- Could not find file '/home/parjong/projects/toolchains/dotnet-cli/tools/Key.snk'.

[That file comes directly from the repo.](https://github.com/dotnet/cli/tree/bf8b588e8b3c330e1fb2852df97c404a047327ee/tools) Does it exist on your machine? If not, could you try to perform a clean clone of the cli repo and then run build again?

**Comment by parjong** [comment]
@svick I can proceed to the next step with clean repo. Thanks you for your comment.
