### ISSUE TITLE
DotNetCore.1.0.1-VS2015Tools.Preview2.0.2 installation issue

### ISSUE THREAD

**Issue by EmraanSiddiqui** [dotnet/cli#4235]
## Steps to reproduce

try installing DotNetCore.1.0.1-VS2015Tools.Preview2.0.2.exe after downloading from https://visualstudiogallery.msdn.microsoft.com/c94a02e9-f2e9-4bad-a952-a63a967e3935 
and disconnect internet in between(my internet disconnected due to power cut problem).
## Expected  behavior

When i tried after internet is back i got this screen 
![fail0](https://cloud.githubusercontent.com/assets/3264483/18772778/49f8720c-8167-11e6-801e-b018124342d9.png)

usually it should repair this or if i try to uninstall it should uninstall it. 
## Actual behavior

But when i try to repair it it gives me this error
![fail1](https://cloud.githubusercontent.com/assets/3264483/18772806/7adb52e0-8167-11e6-8615-08cb8e7b1d81.png)

and when i click on ok it shows this screen
![fail2](https://cloud.githubusercontent.com/assets/3264483/18772819/883c1258-8167-11e6-90fe-f430a8ca8be9.png)

log file:
[dd_DotNetCoreTools__20160923081633.txt](https://github.com/dotnet/cli/files/488786/dd_DotNetCoreTools__20160923081633.txt)

and if i try to uninstall it from the same screen it just shows a loader for half second and nothing else get done.
If i try to uninstall it from control panel 
![1](https://cloud.githubusercontent.com/assets/3264483/18772941/39785b8a-8168-11e6-952d-0404358fd5d1.png)
it just uninstalling SDK not the previewing tool.
## Environment data

`dotnet --info` output:

**Comment by lednhatkhanh** [comment]
+1 this is what I am facing right now!

**Comment by piotrpMSFT** [comment]
The visual studio tooling is tracked in the aspnet/tooling repo.
