### ISSUE TITLE
Conflicting documentation concerning openssl

### ISSUE THREAD

**Issue by sushihangover** [dotnet/cli#4244]
The main `dotnet` web page:
- https://www.microsoft.com/net/core#macos

States that `libcrypto.1.0.0` is required and provides install and sym-linking instructions for the right(?) version.

The OS-X installer states 1.0.1 or 1.0.2 is required:
-  https://go.microsoft.com/fwlink/?LinkID=827526

**Comment by wjk** [comment]
@sushihangover That’s because versions 1.0.1 or 1.0.2 are binary-compatible with programs built for version 1.0.0. On my system `openssl version` reports that I have version 1.0.2h, the filenames of libcrypto/libssl notwithstanding. The directions on Microsoft’s open-source website are correct.

**Comment by piotrpMSFT** [comment]
Agreed with both comments, but we should have a consistent story.

@blackdwarf can you help us get the right version documented everywhere? @bartonjs may be able to help identify that version if needed.

**Comment by bartonjs** [comment]
The documentation is correct.  We only depend on functions available from 1.0.1, 1.0.2 is binary compatible (and what is currently installed by Homebrew, but I don't know about MacPorts); and both of them use "1.0.0" as their library loader version.

**Comment by piotrpMSFT** [comment]
Thanks @bartonjs
