### ISSUE TITLE
OS-X 10.11.12 : 'System.Security.Cryptography.Native': The specified module could not be found.

### ISSUE THREAD

**Issue by sushihangover** [dotnet/cli#4245]
(Yes, another one ;-)
### Verify openssl symlinks based upon documentation and other closed issues:

```
$> ls -l /usr/local/lib/libssl*
lrwxr-xr-x  1 sushi  admin  45 Sep 23 20:13 /usr/local/lib/libssl.1.0.2.dylib -> /usr/local/opt/openssl/lib/libssl.1.0.2.dylib

$> ls -l /usr/local/lib/libcrypto*
lrwxr-xr-x  1 sushi  admin  48 Sep 23 20:12 /usr/local/lib/libcrypto.1.0.2.dylib -> /usr/local/opt/openssl/lib/libcrypto.1.0.2.dylib
```

Note: These `.dylib`s were installed via `home-brew` (after a `brew update`, so by default I am getting the latest versions, not the 1.0.0 version that the "official" docs state to sym-link)
### Use `dotnet`:

```
$> dotnet restore

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
```
### Check which version and location are being used by `dotnet`:

```
cd $(dirname `which dotnet`)
find . -name "*.dylib" -print0 | xargs -n 1 -0 -J % otool -L % | grep -e libcrypto -e libssl
    @rpath/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    @rpath/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
```
## Which version of OpenSSL should be used and sym-linked?

Since there is no true "RPATH" on OS-X, are you running `install_name_tool` during the installer, but it is failing? Is `install_name_tool` supposed to be run as a post-build step, before the official installer binaries are pkg'd?

Ugly Workaround: 
- Copy the libssl/libcrypt dylibs to the `/usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.0.1`

Better Workaround:
- Use `install_name_tool` to correct the dotnet dylibs to look in the proper directory, but how many users know how to do this... 
## Environment data

```
$> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by piotrpMSFT** [comment]
@blackdwarf @bartonjs we need to get the libssl docs cleaned up to be more bulletproof.

**Comment by bartonjs** [comment]
@sushihangover I've not seen `libcrypto.1.0.2.dylib` as a filename produced by Homebrew (it's always produced `libcrypto.1.0.0.dylib` in my experience).  Did you do a default install, or do you have some sort of brew customization?

**Comment by blackdwarf** [comment]
@bartonjs @sushihangover so, would it help if we explicitly install the version that we need/want via `brew`? If `brew` does change the filenames being installed, then this is going to be a never-ending update cycle...

**Comment by bartonjs** [comment]
@blackdwarf Depends on what you mean be "explicit" and "version".  We don't want a locked patch version, that advises that we don't want security fixes coming down.  The package named "openssl" on homebrew brings down, as of me running `brew update` just now, OpenSSL 1.0.2j.

And `/usr/local/Cellar/openssl/1.0.2j/lib/` contains `libcrypto.1.0.0.dylib` and `libssl.1.0.0.dylib`, but no `libcrypto.1.0.2.dylib` (so everything on my machine as as I'd expect it to be).

I don't think we need to be trying to figure out what in our instructions to change until we can understand why @sushihangover's machine was different.  Since Homebrew is still acting as expected, I think that we've hit a power-user scenario... and power-users are always the bane of any simple instructions... I say as a power-user :smile:.

**Comment by blackdwarf** [comment]
@bartonjs well, to me it looks like, based on the original issue that @sushihangover described, that `brew update` followed by `brew install openssl` can land files which are not named in a way that we expect with our instructions. Following that logic, if we "pin" the version in the instructions, e.g. `brew install openssl/1.0.0` or something similar, we may have reproducible results.

Of course, this is only in the case where this is a general enough issue. So far, this is the only complaint we had on this matter, so I'm inclined to agree with you, especially given your experiment, that this may be a case specific to a single, specially configured machine. 😄

**Comment by blackdwarf** [comment]
@sushihangover any update on this?

**Comment by blackdwarf** [comment]
I will close this as there doesn't seem to be an update to this and we cannot repro the issue. @sushihangover please reopen if this continues behaving.
