### ISSUE TITLE
Report test output in real time

### ISSUE THREAD

**Issue by citizenmatt** [dotnet/cli#4249]
When using the test API protocol with `dotnet test` and ReSharper, there is no message for test output as it happens. Instead, output is reported at the end of a run (actually, it is only reported if the test fails, but that's a separate xunit issue - xunit/xunit#986)

**Comment by piotrpMSFT** [comment]
@codito @Faizan2304 have been doing a lot of work around the test verb for preview3 lately. I think they should be able to comment on this.

**Comment by plioi** [comment]
Is this because of an unintended WaitForExit before processing the background queue of incoming messages?

**Comment by piotrpMSFT** [comment]
With RC3 bits we're not seeing this repro anymore. @citizenmatt let us know if you're still seeing an issue.
