### ISSUE TITLE
Migration: Null refs when migrating dotnet/cli projects

### ISSUE THREAD

**Issue by 333fred** [dotnet/cli#4256]
When attempting to run a `dotnet migrate -s` on all projects in dotnet/cli, the following projects have null ref issues, with the output `Object reference not set to an instance of an object.`

* build_projects\dotnet-cli-build
* tests\dotnet-migrate.Tests
* test\Microsoft.DotNet.ProjectJsonMigration.Tests
* build_projects\update-dependencies

Additionally, https://github.com/dotnet/cli/blob/rel/1.0.0/Microsoft.DotNet.Cli.sln#L29 seems to point to an xproj that doesn't exist?

**Comment by 333fred** [comment]
Tagging @brthor.

**Comment by brthor** [comment]
Not surprised about the non-existent xproj, we have a lot of devs working on OS X
