### ISSUE TITLE
How to run multiple ASP.Net Core projects using dotnet run?

### ISSUE THREAD

**Issue by DreamingDevs** [dotnet/cli#4262]
## Steps to reproduce
Create two ASP.Net Core Projects under same solution. How to run multiple ASP.Net Core 1 projects under same solution using `dotnet run`?

## Environment data
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

I used `Visual Studio Community 2015 Version 14.0.25425.01 Update 3`.

I have installed Visual Studio 2015 Tooling Preview 2 of version `DotNetCore.1.0.1 - VS2015Tools.Preview2.0.2` from https://go.microsoft.com/fwlink/?LinkId=827546

OS - `Windows 10 Enterprise N`

**Comment by svick** [comment]
If you have two projects, then you have two applications. I think that means you will have to call `dotnet run` for each of them. Why do you want to run both of them using a single `dotnet run`?

Or did I misunderstand what you're looking for?

**Comment by DreamingDevs** [comment]
I have one MVC project and other I made a Web API project (MVC consuming Web API). So when I run my MVC project, i wanted my Web API to be started automatically.

**Comment by livarcocc** [comment]
dotnet run will not have this capability for you, since it works in the context of a project and you have two separate projects.

I think a possible approach here would be for you to write a script that would start both apps for you.
