### ISSUE TITLE
Can't run console application directly

### ISSUE THREAD

**Issue by kumpera** [dotnet/cli#4268]
## Steps to reproduce

Install the dotnet SDK, including openssl.
Compile a hello world console app with mono.
run it with `dotnet hello-world.exe`
## Expected  behavior

"Hello World" would be printed or the appropriate error would be printed. It looks like the problem is that my hello world references corlib directly.
## Actual behavior

A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in 'xxxx'
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 RID:         osx.10.10-x64

**Comment by svick** [comment]
Mono emulates .Net Framework, but .Net Core is not .Net Framework.

If you want to use .Net Core, use `dotnet build` to compile your code and `dotnet run` or `dotnet yourapp.dll` to run it (plus `dotnet restore` to restore packages).

If you want to use Mono, use `csc` to compile your code and `mono` to run.

Combining the two is not supported.

**Comment by kumpera** [comment]
Hey @svick,

Whether my scenario is supported or not is beyond the point here.

dotnet should give me an error that hint somewhere in the direction of what I did wrong and `The library 'libhostpolicy.dylib' required to execute the application was not found` doesn't.

It's ok'ish to even fail with a cryptic error message if it is specific enough that I can google my way out of it.

That error message only got me results for problems with nuget.

**Comment by mellinoe** [comment]
From a high-level perspective, it is kind of hard to give specific error messages for scenarios that were never considered, supported, or intended. Flipping this around, `mono` gives a similar un-helpful message if you try to run a .NET Core app with it:

```
Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, ..."
```

What sort of error message were you expecting in this case?

**Comment by kumpera** [comment]
Hey @mellinoe,

While mono doesn't tell you what did you do wrong, it gives an error that is much closer to the underlying issue - granted, mono got lucky on this case. Btw, what ancient version of mono are you on? dotnet core binaries work fine on mono/OSX.

On dotnet's case, a missing libhostpolicy.dylib has very little to do with the actual error.

**Comment by kumpera** [comment]
Hey @mellinoe,

While mono doesn't tell you what did you do wrong, it gives an error that is much closer to the underlying issue - granted, mono got lucky on this case. Btw, what ancient version of mono are you on? dotnet core binaries work fine on mono/OSX.

On dotnet's case, a missing libhostpolicy.dylib has very little to do with the actual error.

Actually. Scrap mono from this whole thing. This problem happens regardless of mono.

I can repro it with the following steps:
`
dotnet new; dotnet build; cp bin/Debug/netcoreapp1.0/hello.exe .
dotnet hello.exe
`

dotnet can't run standard alone binaries at all, irregardless of how they were built.

**Comment by kumpera** [comment]
The problem here is that without the hello.runtimeconfig.json file next to hello.dll, dotnet gets confused and fail.

Maybe that's what it should be checking the presence for and warning about.

**Comment by piotrpMSFT** [comment]
I agree that if we're printing some level of diagnostics, it should be actionable diagnostics. That said, given that taking a partial build output is not a designed-for scenario [at an extreme, why not take the first N bytes of the generated dll], I think that `hello.dll is not a valid application` would be a fine message as well. 

Moved this bug to core-setup repo where the host is maintained.

**Comment by Jose-CF** [comment]
+1 still happening over here.

**Comment by dom3d** [comment]
Hey,

about:
"taking a partial build output is not a designed-for scenario" and "hello.dll is not a valid application would be a fine message as well." 

I believe this is not the right way to think about it. You really want the most understandable and actionable feedback possible. If the one or multiple json files are expected to be found alongside the DLL then say exactly that as error message. An error messages should say: what was expected and what was found (or not found) instead. 

There are many reasons for that but one is you want to make it as accessible for anybody as possible (e.g. for people new to the platform).  It's easier to adopt a platform if as much friction as possible is removed and excellent error feedback makes a difference.

**Comment by tritao** [comment]
Still happens to me, even without copying any partial output but just running the exe directly from the build folder...

**Comment by dasMulli** [comment]
@tritao the issue to display a better error message for this case was moved to https://github.com/dotnet/core-setup/issues/570
