### ISSUE TITLE
Fail dotnet build if there is a conflict between native assemblies

### ISSUE THREAD

**Issue by halter73** [dotnet/cli#4271]
## Steps to reproduce

Creating a project depending on "Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final" and "Microsoft.AspNetCore.Server.Kestrel/1.0.1." and build it. An example repo can be found [here](https://github.com/aspnet/KestrelHttpServer/issues/1117#issuecomment-249288845).

This will bring in two libuv.dll's. One from the rc1 Kestrel package and another from the 1.9.0 Libuv package that the 1.0.1 Kestrel package depends on.
## Expected  behavior

`dotnet build` should fail because there are conflicting libuv.dlls.
## Actual behavior

`dotnet build` succeeds and the old libuv.dll from the rc1 Kestrel package is loaded by the 1.0.1 Kestrel package ultimately leading to cryptic runtime errors.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003206)

Product Information:
 Version:            1.0.0-preview3-003206
 Commit SHA-1 hash:  9c6bcb9a83

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

More context can be found here: https://github.com/aspnet/KestrelHttpServer/issues/1117

**Comment by svick** [comment]
Similar issue for a managed assembly: https://github.com/dotnet/cli/issues/4131.

**Comment by piotrpMSFT** [comment]
Let's try to look at this in preview 4.

**Comment by livarcocc** [comment]
I believe this works now. Please, re-activate if you still run into issues.
