### ISSUE TITLE
dotnet-install.ps1 fails behind a proxy

### ISSUE THREAD

**Issue by mendhak** [dotnet/cli#4273]
## Steps to reproduce

In an environment where Internet access requires an outbound proxy, run:

    dotnet-install.ps1  --version 1.0.0-preview2-003133

Internet Explorer proxy has been set
netsh/winhttp proxy has been set

Is there some other environment variable I should be setting to make this work?

## Expected  behavior

The script should download the binaries for running dotnet.  

## Actual behavior

Download fails:

>D:\BuildAgent\work\11440641e6edc7c0\BuildTools>powershell -executionpolicy bypass -file dotnet-install.ps1  --version 1.0.0-preview2-003133
dotnet-install: Downloading https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2-003133/dotnet-dev-win-x64.1.0.0-preview2-003133.zip
Invoke-WebRequest : Unable to connect to the remote server
At D:\BuildAgent\work\11440641e6edc7c0\BuildTools\dotnet-install.ps1:345 char:13
     $resp = Invoke-WebRequest -UseBasicParsing $DownloadLink -OutFile $ZipPath
`~~~~~~~~~~~~~~
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

## Environment data
`dotnet --info` output:  n/a
Internet Explorer proxy has been set
netsh/winhttp proxy has been set

**Comment by piotrpMSFT** [comment]
@mendhak thanks for reporting this. You're right that install.ps1 has not been tested in proxy scenarios. It looks like we should be passing proxy info when calling Invoke-WebRequest:

https://social.technet.microsoft.com/Forums/office/en-US/1cd75340-c22c-4c37-a2b0-8cd6051473d8/invokewebrequest-and-proxy?forum=winserverpowershell

We won't have cycles to update the script in the near future, but perhaps you would like to experiment with this and create a PR? The change should be fairly straightforward.
