### ISSUE TITLE
Move the CLI to 15.x packages of msbuild

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#4276]

**Comment by jeffkl** [comment]
Work with me if you have any issues.  The big change here is the deprecation of the `MSBuild` and `Microsoft.Build.Targets` packages in favor of a new single `Microsoft.Build.Runtime` package.  Files were moved from `runtimes\any\native` to `contentFiles\any\netcoreapp1.0`.  The hope here is that taking a dependency on the `Microsoft.Build.Runtime` gives consumers everything they need when they do `dotnet publish`.

**Comment by livarcocc** [comment]
Fixed by https://github.com/dotnet/cli/pull/4288.
