### ISSUE TITLE
Self-Contained Deployment doesn't output run-able files for each platform

### ISSUE THREAD

**Issue by Nick-Lucas** [dotnet/cli#4277]
I'm struggling to publish platform specific deployments which can be run on anything other than my Windows machine, as I only seem to get back the Windows build in each folder. 
I would expect to see something other than a .exe file in Mac and Linux, for instance.

I may have the wrong end of the stick here, it's unclear whether you have to actually build from the other platform to receive the correct deployment files.

## Steps to reproduce
Following instructions for SCD here: https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index
Add the following runtimes to project.json:
```
  "runtimes": {  
    "win10-x64": {},
    "osx.10.10-x64": {},
    "ubuntu.14.04-x64": {}
  }
```

Run the following
```
dotnet restore
dotnet publish -r ubuntu.14.04-x64 -c release
dotnet publish -r osx.10.10-x64 -c release
dotnet publish -r win10-x64 -c release
```

## Expected  behavior
A folder for each runtime with self contained files that can run on each platform without dotnet installation

## Actual behavior
A folder for each runtime with the same files (including .exe) in each, as in the Windows runtime folder

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by svick** [comment]
I can see an .exe file in `bin/release/netcoreapp1.0/ubuntu.14.04-x64`, not sure why it's there.

But that's the output of `dotnet build`, the output of `dotnet publish` is in `bin/release/netcoreapp1.0/ubuntu.14.04-x64/publish` and I see an ELF file (with no extension) there, as expected.

Are you sure you're looking into the `publish` directory?

**Comment by Nick-Lucas** [comment]
It's most likely I just don't know what I'm looking for! I didn't see any files I recognised as executable on platforms other than Windows, and it doesn't seem to be documented anywhere!

So the 'project name titled' file without an extension on Linux - I did try to start this directly but without a file format I wasn't sure if there was a command to launch it with. 

Any ideas for Mac? Presumably it's not producing a .app file, and there also seems to be a file without an extension, like on Linux?

Thanks!

**Comment by svick** [comment]
In a Unix shell, you should be able to run it using `./project_name` (assuming the `publish` directory is your current directory). This certainly works on Linux and I'm assuming it should work on Mac too.

If I double click on the executable in Ubuntu file explorer, it does nothing. But that seems to happen for other command-line applications too.

**Comment by Nick-Lucas** [comment]
This is good, thank you!

It appears to need to add the executable attribute, as part of deployment, to these files on Linux and possibly Unix systems.  `chmod +x project_name` 
That's where I was falling over when trying to do it myself.

Thanks a lot for the help!
