### ISSUE TITLE
distribute via powershell package management

### ISSUE THREAD

**Issue by factormystic** [dotnet/cli#428]
Reposting my request from dnx: https://github.com/aspnet/dnx/issues/2337#issuecomment-142664701

At least for Windows, could dotnet cli be delivered via powershell package management? I'm sure someone somewhere enjoys manually downloading and double clicking msi's, but I sure don't. I'd much rather set up your package source once and then do `install-package dotnet.cli`

**Comment by piotrpMSFT** [comment]
Thanks for the suggestion @factormystic 

@blackdwarf can you take a look at how this fits with our packaging goals?

**Comment by qbikez** [comment]
An easy way to install from commandline would be very useful. Maybe a cholocatey package or at least a PowerShell script that can be copy-pasted, like for [asp.net 5](https://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-5-from-the-command-line)?

**Comment by blackdwarf** [comment]
@qbikez this will be coming via the installer.ps1 script. Stay tuned.

**Comment by blackdwarf** [comment]
This is now being solved via the `dotnet-install` script. I will close this issue, since for now we are not planning to do PS package management and @qbikez ask is being addressed.
