### ISSUE TITLE
No executable found matching command "echo" with postcompile scripts

### ISSUE THREAD

**Issue by tsublette** [dotnet/cli#4280]
## Steps to reproduce

Add the following to your project.json

```
"scripts": {
    "postcompile": [
      "echo VERSION_TAG=%project:Version% > verfile.txt"
    ]
  }
```
## Expected  behavior

A file called "verfile.txt" is created with the project version
## Actual behavior

A build error

```
No executable found matching command "echo"
```
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Yep, the scripting system in the project.json CLI had a limitation around intrinsic commands provided by the shell itself. I just did a small test atop msbuild, however, and validated that we won't see this behavior moving forward!

````
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="Build">
   <Exec Command="echo hello!"/>
   </Target>
</Project>
````

Outputs:

````
Build started 10/31/16 10:58:52 PM.
     1>Project "/Users/piotrp/code/repro/echo/foo.proj" on node 1 (default targets).
     1>Build:
         echo hello!
         hello!
     1>Done Building Project "/Users/piotrp/code/repro/echo/foo.proj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.22
````
