### ISSUE TITLE
Make sure it's possible to set base-path on `dotnet run -p`

### ISSUE THREAD

**Issue by stanislavromanov** [dotnet/cli#4282]
## Steps to reproduce

`mkdir app`
`cd app`
`dotnet new -t web`
`dotnet build -c Release`
`cd ..`
`dotnet run -c Release -p ./app`
## Expected  behavior

`Directory.GetCurrentDirectory()` should give `~/app`.
## Actual behavior

`Directory.GetCurrentDirectory()` gives `~/` because it was launched outside of `project.json` directory.

This is very bad if you want to launch your web application using systemd on startup in which case the assets inside `wwwroot` do not work since base path is set to `/etc/systemd/system` since that is the place where `/usr/bin/dotnet run -c Release -p /var/app/mycoolwebapp/Web/project.json` is executed
## Environment data

`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview2-003131)
> 
> Product Information:
>  Version:            1.0.0-preview2-003131
>  Commit SHA-1 hash:  635cf40e58
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64

**Comment by blackdwarf** [comment]
Following the repro and using the MSBuild assets, that is, using the following csproj file:

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161026-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

And the following `Program.cs`:

```cs
using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(Directory.GetCurrentDirectory());
    }
}
```

The output that I get is: `/Users/zlatkoknezevic/Experiments/newm/bin/Debug/netcoreapp1.0`, so a full path to where the application has been executed from, as we can see. 

@stanislavromanov I believe this resolves your issue?

**Comment by blackdwarf** [comment]
OK, given the lack of activity on the issue and the repro above, I will close this issue down as mitigated bty our move to MSBui.d If the core condition still repros and/or more help is needed, please reopen this issue. Thanks!
