### ISSUE TITLE
Could not load file or assembly System.IO.Compression when dotnet-test-xunit is in dependencies list

### ISSUE THREAD

**Issue by DovydasNavickas** [dotnet/cli#4289]
## Steps to reproduce

Copy/paste into git bash

```
git clone https://github.com/DovydasNavickas/DotnetCLI-Bug
cd DotnetCLI-Bug/src
dotnet restore
cd ZipTest
dotnet run -f net46
```
1. Go to [http://localhost:5000/zip](http://localhost:5000/zip) and you'll see an error
2. Go to [http://localhost:5000/ziplocal](http://localhost:5000/ziplocal) and you'll get a zip

Run project with `dotnet run environment=development` if this just hung up.
Shouldn't change anything, but it helped a few times.

There are two files with identical code except for the class name in `src/MyLib/ZippingHelper.cs` and `src/ZipTest/ZipHelperInTheSameProject.cs` and two routes using it: `/zip` and `/ziplocal`.
## Expected  behavior

Both routes give you a zip
## Actual behavior

If identical code is in a separate project (`MyLib` in the repro), it fails with a message:

```
An unhandled exception occurred while processing the request.

FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
```
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
## Notes

To save you time debugging, you can workaround this bug by removing a dependency `"dotnet-test-xunit": "2.2.0-preview2-build1029"` from `src/ZipLib/project.json` and doing a `dotnet restore` and `dotnet run` again. It works then.

But when the `"dotnet-test-xunit": "2.2.0-preview2-build1029"` dependency is in `src/ZipLib/project.json`, it omits the `System.IO.Compression.dll` during the build and fails during the runtime, when it looks for that `.dll`.  I have no idea why one dependency could trigger omitting another dependency's `.dll` during build, but it does.

Have fun, guys... Took me a week to localize to this small solution.

Oh, and it happens only with full framework:
`dotnet run -f net46`
and not with core:
`dotnet run -f netcoreapp1.0`

Tried on my MBP with Windows 10 and our build agent VM with Windows Server 2012 (or whichever one is Windows 8 or 8.1) and the same behavior is in both environments.

**Comment by piotrpMSFT** [comment]
Thanks for the report and the workaround, @DovydasNavickas. 

The test adapter model is changing fairly drastically in preview 3. You can see an example test project [here](https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/TestProjects/VSTestXunitDotNetCore/VSTestXunitDotNetCore.csproj). Since `dotnet-test-xunit` is not going to continue playing a role, I'm going to close this issue.
