### ISSUE TITLE
Package Gembox.Spreadsheet is not compatible with netcoreapp1.0 

### ISSUE THREAD

**Issue by sridhar3525** [dotnet/cli#4290]
## Steps to reproduce

**Package GemBox.Spreadsheet 41.3.30.1000 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package GemBox.Spreadsheet 41.3.30.1000 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net30 (.NETFramework,Version=v3.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.**

I am trying to install Gembox.Spreadsheet in the .NetCoreApp, but it is throwing error. 

My Project.json file has following

{
  "userSecretsId": "aspnet-Vault-b4fbccbe-ec6b-40f5-96bb-5f5737dac1d5",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.1",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0",
    "NuGet.CommandLine": "3.4.3",
    "GemBox.Spreadsheet": "41.3.30.1000",
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [ "portable-net40+sl5+win8+wp8+wpa81" ]
    },
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8",
        "portable-net45+win8+dnxcore50"
      ]
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8",
        "portable-net45+win8+wp8+wpa81"
      ]
    }
  },
 
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

## Expected  behavior
Success

## Actual behavior

Package GemBox.Spreadsheet 41.3.30.1000 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package GemBox.Spreadsheet 41.3.30.1000 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net30 (.NETFramework,Version=v3.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by svick** [comment]
Why would you expect this to work? For a package to work in .Net Core, generally the package author has to update it and that has not been done for this package yet.

I don't think there is anything to be done here, instead, you should contact the package author (GemBox Software).

**Comment by livarcocc** [comment]
Correct. Unfortunately, there is nothing that we can do in the CLI. Your best bet is to reach out to the author of the package.
