### ISSUE TITLE
Microsoft.DotNet.Cli.CommandLine should be public

### ISSUE THREAD

**Issue by mattwarren** [dotnet/cli#4291]
## Steps to reproduce

I'm trying to write a 3rd party command for `dotnet`, reusing as much code as possible

## Expected  behaviour

I'd like to be able to re-use [CommandLineApplication](https://github.com/dotnet/cli/blob/a3a58423d19b01f113af0cc2cc2731c0e6e67082/src/dotnet/CommandLine/CommandLineApplication.cs), [CommandOption](https://github.com/dotnet/cli/blob/a3a58423d19b01f113af0cc2cc2731c0e6e67082/src/dotnet/CommandLine/CommandOption.cs), [CommandArgument](https://github.com/dotnet/cli/blob/a3a58423d19b01f113af0cc2cc2731c0e6e67082/src/dotnet/CommandLine/CommandArgument.cs) and others under [src/dotnet/CommandLine](https://github.com/dotnet/cli/tree/a3a58423d19b01f113af0cc2cc2731c0e6e67082/src/dotnet/CommandLine) (in the same way that [TestCommand](https://github.com/dotnet/cli/blob/a3a58423d19b01f113af0cc2cc2731c0e6e67082/test/Microsoft.DotNet.Tools.Tests.Utilities/Commands/TestCommand.cs) can)

## Actual behaviour

I'm not able to, as all the classes are marked `internal`

## Environment data
`dotnet --info` output:

----

Seem like some work has already been done in this area, for instance #724

**Comment by natemcmaster** [comment]
This API already exists as [Microsoft.Extensions.CommandLineUtils](https://github.com/aspnet/Common/tree/1.0.0/src/Microsoft.Extensions.CommandLineUtils).  See https://www.nuget.org/packages/Microsoft.Extensions.CommandLineUtils/

**Comment by svick** [comment]
@natemcmaster So why isn't CLI using that?

**Comment by natemcmaster** [comment]
They forked it to avoid circular dependencies and to add some custom behavior.

**Comment by livarcocc** [comment]
Please use the API that @natemcmaster is pointing to above.

**Comment by mattwarren** [comment]
@natemcmaster thanks for letting me know about CommandLineUtils, I didn't know that existed

**Comment by moh-hassan** [comment]
There is a [fork ](https://github.com/natemcmaster/CommandLineUtils)for  Microsoft.Extensions.CommandLineUtils, which is active and maintained by @mattwarren 
It has a good [documentation and samples](https://natemcmaster.github.io/CommandLineUtils/index.html)
it can be installed from nuget

               Install-Package McMaster.Extensions.CommandLineUtils
