### ISSUE TITLE
Building an FSharp project doesn't set the file and product version on assemblies

### ISSUE THREAD

**Issue by dustinmoris** [dotnet/cli#4292]
## Steps to reproduce

```
dotnet new --lang=fsharp
dotnet restore
dotnet build
```

Inside the bin/Debug/netcoreapp1.0 folder the DLLs don't have a version set. It works for C# libraries though.
## Expected  behavior

Assembly versions to be set according to the value in `project.json`.
## Actual behavior

Assembly version is not being set.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@KevinRansom @enricosada this needs to be fixed in the F# SDK. Can you create a bug in an appropriate repo?

**Comment by enricosada** [comment]
@piotrpMSFT moved to dotnet/netcorecli-fsc#62 . This can be closed
