### ISSUE TITLE
Need to support additional restore options when restoring for a RID in self-contained publish

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4294]
See https://github.com/dotnet/cli/pull/4286#pullrequestreview-2420079

When we are calling `dotnet restore3` when publishing for a self-contained app, we are not passing in any extra options to `restore3`.  This can be an issue for users who call restore with specific properties.  When we call restore, it will be overwriting the project assets file that was originally restored.

Some options for supporting this:

1. Pass `ExtraMSBuildArguments` into both the restore call and the publish call.
 - This can have issues if you explicitly need different values for the two MSBuild calls.
2. Come up with another way to take both "extra restore args" and "extra publish args" separately in one command-line.
2. The user can use environment variables to set any properties they want passed into MSBuild /t:restore.
3. Save the arguments passed into `dotnet restore3` orginally, and read them during publish's call to restore.
4. The user explicitly restores with the RID + extra restore options before calling publish.  Then we add a new option to `dotnet publish3`: `--no-restore`, which allows publish to use the previously restored assets file, with the RID in it.

@emgarten @blackdwarf @piotrpMSFT @livarcocc @brthor

**Comment by dasMulli** [comment]
Another aspect of this: Could the publish target's dependency on the restore target be modelled in the publish msbuild task itself?
Currently, you need the CLI to perform all necessary actions to produce the published output.
If i had an msbuild project (e.g. `.wixproj` setup project) that depends on the self-contained published output of an app, i would ideally like to reference / call a single publish target on the referenced project.

The only way i can currently ensure the published output using msbuild only is by calling (note the 2 properties needed for the RID):
```
msbuild some.csproj /t:Restore,Publish /p:TargetFramework=netcoreapp1.0 /p:RuntimeIdentifier=win7-x64 /p:RuntimeIdentifiers=win7-x64
```
And that will only work until something changes and i need to reverse-engineer the Publish3Command again.

Another option would be to create an msbuild task that figures out where the dotnet cli executable is (or hope the correct one is on the `PATH`) and call publish through an `<Exec/>` element. This is what i currently use for `project.json` based builds and would like to replace with a plain `<ProjectReference …><Targets>Publish</Targets>…</…>` or a single `<MSBuild />` element in a before-build target.

**Comment by eerhardt** [comment]
> Could the publish target's dependency on the restore target be modelled in the publish msbuild task itself?

Unfortunately, no it can't.  This is because "restore" will install .props and .targets files into your project. But if restore happens in the same MSBuild invocation as 'publish', those new .props and .targets files will not be honored/loaded/used.  In order to get the correct behavior, you always need to restore in a separate MSBuild invocation than when running targets that can be affected by restore.

> (note the 2 properties needed for the RID):

Thanks for pointing this out. @emgarten has fixed it so the Restore target would also honor `/p:RuntimeIdentifier`.  See https://github.com/NuGet/NuGet.Client/pull/927.

**Comment by dasMulli** [comment]
> This is because "restore" will install .props and .targets files into your project.
Of course, totally forgot about that!

**Comment by livarcocc** [comment]
@blackdwarf Please make a call on which experience to use for this. We like option 5 above.

**Comment by emgarten** [comment]
I would expect both 1 and 5, everything that is passed to publish should also get passed to restore, including the non-extra arguments such as RID. And also the option to skip restore.

5 is the easiest to work with and would let the user optimize things if they know the restore is already correct.

My issue with having only 5 is that it sets the user up to have restore and publish evaluate the project in different ways. But maybe that will only be a very rare scenario.

**Comment by blackdwarf** [comment]
After careful consideration, I think #5 above is the only really sane choice. It would pay for us to not be smart here.

Of course, I dislike this because it means that the self-contained app is not a pure publish-only concern, but I believe to err on the side of overall correctness here is much better.

**Comment by eerhardt** [comment]
Hot off the presses, we are actually considering removing the restore during publish in order to fix/workaround https://github.com/NuGet/Home/issues/3768.

If you pass a RID on the command-line it applies to all the P2P references in the graph, which doesn't work.

So [the plan](https://github.com/NuGet/Home/issues/3768#issuecomment-256174805) is

```
I think the best thing we can do here for Dev15 RC is the following plan:

1. RuntimeIdentifiers gets specified in the .csprojs as necessary.
2. dotnet migrate takes the "runtimes" section and puts it in RuntimeIdentifiers in the .csproj.

Now restore will work correctly.

3. We fix dotnet publish --runtime to no longer issue a restore. It will be expected that the project is already restored for the RID you specify. If it hasn't an error is raised telling you to add the RID to the .csproj and run restore again.
```

@jgoshi is working on this plan.  Assigning to him.

**Comment by blackdwarf** [comment]
@eerhardt @jgoshi this is, however, going back to the model we had with project.json, correct?

**Comment by eerhardt** [comment]
It taking a slight step backwards to the model we had with project.json.  However, I think our main goal here (make portable vs self-contained a publish time decision) is preserved because we've gotten rid of `type: platform`.

Here's the explanation:

If you only ever want to publish as a "portable" .NET Core app, you don't have to put RIDs in your .csproj.  You can publish portable all day long.

However, if you want to enable publishing as a self-contained app, you need to declare in your .csproj which RIDs you want to be able to support.  You can still publish as "portable", that will work fine even with RIDs in the .csproj.  But now you can also publish self-contained for one of the RIDs you declared in your .csproj.

If you ever try to publish as self-contained for a RID that doesn't exist in your .csproj, you get an error (whether that was because the RID list was empty, or simply didn't contain what you specified). The error tells you to add the RID and restore if you want to publish for that RID.

**Comment by blackdwarf** [comment]
@eerhardt thanks for the more detailed explanation. Based on the above, I see that P2P references and restoring them for a given RID was the major reason this backing out was done?

While it is true that not having `type: platform` is more towards the goal we wanted, this solution still requires changing your project. With this in mind, we cannot really say that our goal has been met.
