### ISSUE TITLE
dotnet migrate should print an error if no project.json is found

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4313]
## Steps to reproduce
```
mkdir foo
cd foo
dotnet migrate
```

## Expected  behavior
```
No project.json file found in 'foo'
Migration Failed
```

## Actual behavior
```
 
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-003748)

Product Information:
 Version:            1.0.0-preview3-003748
 Commit SHA-1 hash:  7632cd3502

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by sanjayMT** [comment]
I'm facing this issue, any solution for this?

**dotnet --info**
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
