### ISSUE TITLE
copyToOutput do not copy files twice

### ISSUE THREAD

**Issue by ili** [dotnet/cli#4317]
## Steps to reproduce

I do need to copy same source files to different folders
I do have next solution folders structure:

```
--[Data]
----TestData.mdb
----TestData.mdf
----TestData.sqlite
----[Create Scripts]
------<number of *.sql>
```

```
"copyToOutput": {
    "mappings": {
        "Database/": {
            "include": "../../Data/"
        },
        "Data/": {
            "include": ["../../Data/"],
            "exclude": ["../../Data/Create Scripts"]
        }
    }
}
```
## Expected  behavior

In output folder:

```
--[Database]
----TestData.mdb
----TestData.mdf
----TestData.sqlite
----[Create Scripts]
-----<number of *.sql>
--[Data]
----TestData.mdb
----TestData.mdf
----TestData.sqlite
```
## Actual behavior

In output folder:

```
--[Database]
----[Create Scripts]
------<number of *.sql>
--[Data]
----TestData.mdb
----TestData.mdf
----TestData.sqlite
```

My experiments shows that all files are copied once, so if I'll change my 'project.json' like

```
"copyToOutput": {
    "mappings": {
        "Database/": {
            "include": "../../Data/"
        },
        "Data/": {
            "include": ["../../Data/TestData.mdb"],
            "exclude": ["../../Data/Create Scripts"]
        }
    }
}
```

Result would be:

```
--[Database]
----TestData.mdf
----TestData.sqlite
----[Create Scripts]
------<number of *.sql>
--[Data]
----TestData.mdb
```
## Environment data

`dotnet --info` output:

```
D:\job\linq2db\Tests\Linq>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
@ili is it possible to get a repro github repo of this? I would like to see if the move to MSBuild mitigated this.

**Comment by ili** [comment]
@blackdwarf I'll prepare a demo repo today or tomorrow

**Comment by blackdwarf** [comment]
@ili since there was no response in 3 days, I will close this issue down. If you can still repro it with the latest builds from `rel/1.0.0` from the CLI (this) repo, please reopen the issue.

**Comment by ili** [comment]
@blackdwarf sorry here it is: https://github.com/ili/issue4317

after the build in output would only be `Data` folder, while i'm expecting `Data` and `Database`
