### ISSUE TITLE
copyToOutput in frameworks section overrides copyToOutput in the root

### ISSUE THREAD

**Issue by ili** [dotnet/cli#4318]
## Steps to reproduce

`project.json`

```
{
    "buildOptions": {
        "copyToOutput": {
            "mappings": {
                "Database/": {
                    "include": "../../Data/"
                }
        }
    },

    "frameworks": {
        "net40": {
            "buildOptions": {
                "copyToOutput": {
                    "mappings": {
                        "x86/": { "include": "../../packages/System.Data.SQLite.Core.1.0.101.0/build/net40/x86/" },
                        "x64/": { "include": "../../packages/System.Data.SQLite.Core.1.0.101.0/build/net40/x64/" }
                    }
                }
            }
        }
}
```
## Expected  behavior

Three folders in output: `Database`, `x86`, `x64`
## Actual behavior

Two folders in output:  `x86`, `x64`
`copyToOutput` in the root section is ignored if the same is declared in `frameworks`
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by brthor** [comment]
The merging behavior in project.json is "take the latest". 

After you migrate your project to MSbuild, these groups should be merged properly.

**Comment by ili** [comment]
Thanks @brthor 

Where can I read about migration project to MSbuild, i see number of issues tagged `msbuild-mitigated` but it is unclear what to do, what is supposed TBD

**Comment by blackdwarf** [comment]
@ili you can download the latest from `rel/1.0.0` and try it out. Can you please provide us with a GH repo with a repro?

**Comment by ili** [comment]
@blackdwarf I'll prepare a demo repo today or tomorrow

**Comment by blackdwarf** [comment]
@ili since there was no response in 3 days, I will close this issue down. If you can still repro it with the latest builds from `rel/1.0.0` from the CLI (this) repo, please reopen the issue.

**Comment by ili** [comment]
@blackdwarf once again - sorry 
here we go: https://github.com/ili/issue4318

after build in output would be `Data\file2.txt` while i'm expecting `Database\File1.txt` and `Data\File2.txt`
