### ISSUE TITLE
CLI MSI needs to be signed else Windows SmartScreen doesn't recognize it

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#432]
![image](https://cloud.githubusercontent.com/assets/7583839/11663308/55af4b04-9d90-11e5-9b65-310c02a9a2c1.png)

**Comment by Sridhar-MS** [comment]
The MSI needs to be authenticode signed. It has to be automated in the internal VSO CI builds. I have already started conversations regarding this. I am going to use this issue to track this in the open.

**Comment by piotrpMSFT** [comment]
@livarcocc is taking on all of our signing needs.

**Comment by blackdwarf** [comment]
Tracked in #500.
