### ISSUE TITLE
New Project dialog : 'Console Application (.NET Core)' and 'Class Library (.NET Standard)' do not show up under '.NET Core' node

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#4321]
## Steps to reproduce
1. Install WPT.25803.01
2. File > New Project 

## Actual behavior
'Console Application (.NET Core)' and 'Class Library (.NET Standard)' show up under 'Visual C#' node only

## Expected  behavior
They should also show up under '.NET Core' node.

**Comment by livarcocc** [comment]
Please, open this in a Visual Studio bug repo.

@srivatsn
