### ISSUE TITLE
Sort out Project Output Directory for good

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#433]
Right now we recalculate the output directory for a project in a bunch of places. We should sort that out. I think we should actually promote output directory and configuration to properties of `ProjectContext`, since they are related to the context in which a project is viewed. That will have some ripple effects though (OmniSharp/DTH, etc.).

**Comment by brthor** [comment]
Would this be output directory of compilation of the project?

Would this still be able to be overridden by cmd line switches in commands like `dotnet-compile` ?

**Comment by anurse** [comment]
Yes to both. I'd imagine you can provide an override Output Directory to the `ProjectContextBuilder`.

**Comment by anurse** [comment]
@pakrym and @livarcocc did a bunch of output path work, including writing some classes to manage output path. That might cover the concerns I had here. I just didn't like that we kept recalculating it :).
