### ISSUE TITLE
Project file cleanup of migrated projects

### ISSUE THREAD

**Issue by srivatsn** [dotnet/cli#4330]
## Steps to reproduce

dotnet migrate a simple app 

``` json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    },
    "MyLib": "1.0.0-*"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
## Expected  behavior

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160930-1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs"  />
    <EmbeddedResource Include="**\*.resx"  />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyLib\MyLib.csproj" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```
## Actual behavior

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
    <AssemblyName>MyApp</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AutoUnify>true</AutoUnify>
    <DesignTimeAutoUnify>true</DesignTimeAutoUnify>
    <ProjectLockFile>$(MSBuildProjectDirectory)/project.lock.json</ProjectLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160930-1</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <ProjectReference Include="..\MyLib\MyLib.csproj" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)' == '.NETCoreApp,Version=v1.0' ">
    <DefineConstants>$(DefineConstants);NETCOREAPP1_0</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE;TRACE</DefineConstants>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Notable changes needed:
- [x] Drop the xml tag at the top. MSbuild doesn't need it.
- [x] Properties OutputPath, AutoUnify, DesignTimeAutoUnify, AssemblyName should be deleted. The SDK already includes these.
- [x] Don't know what PackageRequireLicenseAcceptance does but it seems very odd to have that. We should put that in the SDK if it's needed.
- [x] PackageReference items should be in the same itemgroup
- [ ] Excludes should be removed. If there are any default exclude globs missing, add that to the SDK.
- [x] The ProjectReference shouldn't be conditioned on the TFM when it's the same as the one that the project is targeting.
- [x] When it needs to be conditioned (because there are multiple TFs say) then it should use the $(TargetFramework) property for brevity and correctness.
- [x] The constants for debug\release are already in the SDK - can be removed.
- [ ] The constants for TFMs should be added to the SDK. 

As a principle, I think it's fine to make these changes and force the SDK to react to the breaks since the SDK is mostly in shape now.

**Comment by brthor** [comment]
> Drop the xml tag at the top. MSbuild doesn't need it.

@rainersigwald Can I do this with ProjectRootElement.Save() or should I just crack open the file?

**Comment by brthor** [comment]
> Properties OutputPath, AutoUnify, DesignTimeAutoUnify, AssemblyName should be deleted. The SDK already includes these.

- OutputPath cannot be removed without breaking the projects when Configuration is set
- AutoUnify, DesignTime are already gone. 
- AssemblyName needs to get deleted.

**Comment by brthor** [comment]
> Don't know what PackageRequireLicenseAcceptance does but it seems very odd to have that. We should put that in the SDK if it's needed.

Covered by https://github.com/dotnet/cli/issues/4120

**Comment by rainersigwald** [comment]
I think MSBuild will always keep the xml tag if it was originally present, and I don't think there's a way to tell us to remove it. @AndyGerlicher is that right?

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/issues/195 tracks the implcit defines

**Comment by nguerrera** [comment]
> OutputPath cannot be removed without breaking the projects when Configuration is set

It only breaks calling restore and passing a configuration or having configuration env var set during restore.  After restore, the output path will be set. https://github.com/dotnet/sdk/issues/203 tracks the issue.

If you want to work around it in the CLI in the meantime, consider passing `/p:SkipInvalidConfigurations=true;_InvalidConfigurationWarning=false` to restore verb invocations. 

Persisting a bug workaround in to every migrated project is more debt that we should avoid.

**Comment by nguerrera** [comment]
The outputpath should be removed from dotnet new too.

**Comment by eerhardt** [comment]
> The outputpath should be removed from dotnet new too.

In general, `dotnet new` should exactly match:

https://github.com/dotnet/sdk/blob/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpConsoleApplication/ProjectTemplate.csproj
https://github.com/dotnet/sdk/blob/master/src/Templates/ProjectTemplates/CSharp/.NETCore/CSharpConsoleApplication/Program.cs

**Comment by brthor** [comment]
Once it's removed from dotnet new it'll be removed from migration, it's being included in the base template. We could scrub it out in migration if it's not going away soon though.

**Comment by brthor** [comment]
https://github.com/dotnet/cli/pull/4242 is cleaning up a few things here.

AssemblyName is gone.
OutputPath is still in the new template, so it's still in migrated projects. This can come separate.

> Excludes should be removed. If there are any default exclude globs missing, add that to the SDK.

This would need to happen in the sdk first and then someone can regenerate the defaults for migration. This entire block is necessary to match the project.json behavior, do we want to include all of these as defaults in the sdk?
