### ISSUE TITLE
dotnet pack - allow "empty" packages to create convenience packages

### ISSUE THREAD

**Issue by danielwertheim** [dotnet/cli#4331]
## Steps to reproduce

Create a `project.json` file that just sits in an empty project folder. Define `title, description, version...`. Include no files. Just add dependencies to other existing NuGet packages.

`dotnet pack`

It will complain about can not create empty package. Then I added a simple `README.md` using `packOptions.files`. The NuGet is then created OK, but the dependencies aren't understood.
## Expected  behavior

I want a NuGet packaged with no content, that just acts as a "convenience" package that will install listed dependencies.

This is possible using `nuget.exe` and `nuspec`.
## Actual behavior

Package with no dependencies is created.
## Environment data

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by blackdwarf** [comment]
Moved to Nuget/Home#4339.
