### ISSUE TITLE
Missing framework message implies specific version was requested

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#4336]
## Steps to reproduce

1. On a machine with only 1.0.0-* versions of Microsoft.NETCore.App installed, create a project which references "Microsoft.NETCore.App": "1.1.0-*" as a type platform.
2. Try to build and run that app.
3. See that we get an error `The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001090-00' was not found.`.

## Expected  behavior
Should complain of being unable to find something matching the provided version string.

## Actual behavior
Complains of being unable to find a _specific_ version of "Microsoft.NETCore.App" that it found (I assume) on NuGet. Giving the un-initiated user the impression that somewhere they've specified a specific version.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
When you do a dotnet restore, the * gets resolved to a specific version.

We are telling you exactly what version we are trying to find and use so that you can go get it.

This is by design.
