### ISSUE TITLE
Remove DependencyModel in preview2.1 branch, and use core-setup's DependencyModel instead

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4340]
The Preview2.1 branch is for creating a CLI compatible with .NET Core 1.1. The .NET Core 1.1 core-setup repo has a new version of DependencyModel library.

The CLI Preview2 branches still contain the old DependencyModel library code.

We should update Preview2.1 to remove its old DependencyModel code and instead use the version from core-setup.

@livarcocc @mellinoe @piotrpMSFT

**Comment by livarcocc** [comment]
I took a stab at it a couple of days ago and I managed to get the code working, the test running, etc. But it required a new test runner and the one I managed to produce also depended on version from xunit that are not on Nuget, but in myget/xunit. Overall, I am dropping this for now, unless we come up with a concrete reason why we should take on this work at this point in time.

**Comment by eerhardt** [comment]
Closing this.  I don't think we plan on servicing 1.0.0-preview2.1 anymore.  If we do, and we need this change, we can re-open and fix.
