### ISSUE TITLE
Do we have to use “--configuration Linux” if want to build for Linux?

### ISSUE THREAD

**Issue by jianyunt** [dotnet/cli#4341]
We use dotnet build for our [OneGet project](oneget.org) for both coreclr and fullclr. Our code is C# based. 
Our goal is to use the donet coreclr build so that our binaries can be run on windows, Linux, Mac, etc.

However we observed that :

If we want to build for Linux, we have to pass in --configuration Linux . The binaries generated then work well on Linux . For example,

dotnet -v build –framework netstandard1.6--configuration Linux

If we build without passing in Linux,

dotnet -v build –framework netstandard1.6

We have trouble to calling into some methods such as using powershel.Invoke().

Question:

Assuming we do not have build options for pre-compile process, is it true any app purely built on top up of CoreCRL should be able to run other Platform like Linux, Mac ?

What sort of special things dotnet build do when a user passes in --configuration Linux?

Per https://github.com/dotnet/buildtools/issues/1101, this may be the place I can get answer from. thx.

**Comment by dasMulli** [comment]
Your project.json files explicitly define the Linux configuration: https://github.com/OneGet/oneget/blob/9ed7c3a60e3b5d04aa4ed160ad633045b1f4e054/src/Microsoft.PackageManagement.ArchiverProviders/project.json.hidden#L13

You could move all `#if UNIX` calls to `#if CORECLR` that you also defined in that file.

**Comment by jianyunt** [comment]
Thanks dasMulli for your response. Yes our project.json contains the Linux buildOptions.  As long as the linux config exists,  even if we do not use #if UNIX in the code, we still need to build with –configuration Linux for Linux?   The best approach is to remove the linux config in project.json so that we can depend on CoreCRL to build a set of binaries that runs on Nano server, Linux, and Mac.  

  "configurations": {
    "Linux": {
      "buildOptions": {
        "define": [ "UNIX" ]
      }
    }
  },

**Comment by dasMulli** [comment]
Exactly. As long as the libraries list `netstandard1.6` in the `frameworks` section and the runnable binaries use `netcoreapp1.0` you should be fine.

**Comment by jianyunt** [comment]
After removing #if Unix section, we have added code for the runtime check, something like below. Will dotnet build link-in Windows libraries during the compile time when it sees PInvoke, register code, even if the dll will be run on Linux? 

If(IsWindows)
{
	Pinvoke …
	Registry …
}
Else
{
}

**Comment by dasMulli** [comment]
That should work AFAIK, at least i have working prototype that calls some win dlls and throws PlatformNotSupportedException on non-windows. But i'm not an expert on when p/invoke calls are actually bound.

**Comment by livarcocc** [comment]
The CLI is not going to implicitly set the Configuration to Linux. This is an unknown value for the CLI.

You can use https://source.dot.net/#System.Runtime.InteropServices.RuntimeInformation/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.cs,f0b94ab083bb10a6 instead of defines in your code.
