### ISSUE TITLE
An unhandled exception has occurred: Can not find compilation library location for package 'microsoft.csharp'

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#4343]
## Steps to reproduce

Build and run  MusicStore sample
## Expected  behavior

No error.
## Actual behavior

An unhandled exception has occurred: Can not find compilation library location for package 'microsoft.csharp'

Full error message:
[error.txt](https://github.com/dotnet/cli/files/515774/error.txt)

![reference_not_found](https://cloud.githubusercontent.com/assets/6814395/19186032/d9ece62c-8cb6-11e6-9743-abb8753e7b8d.png)
## Environment data

`dotnet --info` output:
C:\temp\MusicStore-dev\samples\MusicStore>dotnet --info
.NET Command Line Tools (1.0.0-preview3-003716)

Product Information:
 Version:            1.0.0-preview3-003716
 Commit SHA-1 hash:  bbf9fe92cf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by dasMulli** [comment]
The problem seems to be that the restore fails. Does it work when you run `dotnet restore` and `dotnet build` in the project's directory?

**Comment by xatabhk** [comment]
Both 'dotnet restore' and 'dotnet build' run without any issue. Also 'dotnet run' starts well; no error before the app receives a request.

**Comment by livarcocc** [comment]
Can you run this through dotnet run?

**Comment by xatabhk** [comment]
'dotnet run' starts well; no error before the app receives the first request.

**Comment by piotrpMSFT** [comment]
Since this is a VS2015-only issue, moving to aspnet tooling repo
