### ISSUE TITLE
vstest.console.exe run from MSBuild Exec task hangs when there is more than one platform

### ISSUE THREAD

**Issue by prochan2** [dotnet/cli#4344]
This is based on
https://blogs.msdn.microsoft.com/visualstudioalm/2016/09/01/announcing-mstest-v2-framework-support-for-net-core-1-0-rtm/
## Steps to reproduce

Let's have these files in a project:
- project.json

```
{
  "version": "1.0.0-*",
  "testRunner": "mstest",
  "dependencies": {
    "dotnet-test-mstest": "1.1.1-preview",
    "MSTest.TestFramework": "1.0.1-preview"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },
      "imports": "dnxcore50"
    },
    "net46": {}
  }
}
```
- TestClass.cs

```
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SampleNetCoreUnitTests
{
  [TestClass]
  public class TestClass
  {
    [TestMethod]
    public void TestMethodPassing()
    {
      Assert.IsTrue(true);
    }

    [TestMethod]
    public void TestMethodFailing()
    {
      Assert.IsTrue(false);
    }
  }
}
```
- VSTestTest.proj

```
<Project DefaultTargets="Test"
         xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="Test">
      <Exec Command="&quot;c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe&quot; project.json /UseVsixExtensions:true" />
    </Target>
</Project>
```

To reproduce the issue, run

```
dotnet restore
msbuild VSTestTest.proj
```
## Expected  behavior

All processes should finish in the end of the tests.
## Actual behavior

Two dotnet.exe and one MSBuild.exe processes keep hanging.

Killing the dotnet.exe processes releases the MSBuild.exe.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
cc @Faizan2304 is this something that you are aware of and can help out with?

**Comment by gulbanana** [comment]
could be related to #4067

**Comment by piotrpMSFT** [comment]
In this scenario we're invoking desktop components to run tests. CLI is only here to launch an <Exec> task. As such, closing the bug.
