### ISSUE TITLE
Publish Nuget.Build.Tasks.Pack to dotnet-core myget feed

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#4346]
## Steps to reproduce
* `dotnet new --type msbuild`
* Create a `NuGet.Config` to include feed `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`
* `dotnet restore3`

## Expected  behavior
Should restore cleanly.. 

Previously (preview1/2), latest CI builds would restore using the `dotnet-core` feed only.
The description of `cli-deps` also states:
`This feed is used internally for dotnet/cli. Please don't consume it from other projects`

## Actual behavior
`NuGet.targets(68,5): error : Unable to resolve 'Nuget.Build.Tasks.Pack (>= 3.6.0-rc-1954)' for '.NETCoreApp,Version=v1.0'.`
(Didn't test but i think `Microsoft.CodeAnalysis.Build.Tasks` would also be missing from `dotnet-core`)
Btw i also don't see it in the `dotnet-cli` feed.

### Workaround

Add `cli-deps` feed to `NuGet.Config`

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003786)

Product Information:
 Version:            1.0.0-preview3-003786
 Commit SHA-1 hash:  77e526396c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```
ENV `DOTNET_RUNTIME_ID=osx.10.11-x64`

cc @eerhardt because myget lists you as owner of `cli-deps`

**Comment by eerhardt** [comment]
@rrelyea @emgarten @rohit21agrawal @joelverhagen -

NuGet team, can you start publishing this package to the dotnet-core feed?  Every .NET Core user needs this package.

**Comment by rohit21agrawal** [comment]
@eerhardt can you give me the feed details? api key , feed url etc.

**Comment by rohit21agrawal** [comment]
I have pushed the nuget.build.tasks.pack rc-1954 package to dotnet-core feed, but what should be the plan here?

Should we set it up so that every build of nuget.build.tasks.pack get uploaded to the feed, or every time we do an integration?

**Comment by eerhardt** [comment]
It's up to you, the NuGet team.

At a minimum, you need to update it every time the `Microsoft.NETCore.Sdk` package takes a dependency on a new version of NuGet.Build.Tasks.Pack.

If I were doing it, I would push every new version to dotnet-core. That way it is automated.

**Comment by rohit21agrawal** [comment]
this has been fixed in our CI scripts.
