### ISSUE TITLE
cannot pass various properties to scripts in project.json

### ISSUE THREAD

**Issue by prochan2** [dotnet/cli#4354]
Regarding scripts in project.json (e.g. post-compile script):

I need to pass output directory, configuration and target platform to the script (as arguments) but it seems there's no way.
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@prochan2 with the move to MSBuild, the way to get post-* scripts to work is to create targets that depend on targets after which you want your code to run. There is a whole way how MSBuild allows passing in data to custom targets.

For your examples above here are some of the properties you can use:

* `Configuration`
* `OutputPath`
* `TargetFramework`

You can find more common MSBuild properties on https://msdn.microsoft.com/en-us/library/bb629394.aspx. These should be

With this, I will close this issue. If you need more help, please don't hesitate to reopen it. Thanks!
