### ISSUE TITLE
'dotnet migrate' should check the compiler type

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4358]
`dotnet migrate` doesn't support migrating projects other than C# projects.  It should error out if a user attempts to migrate projects that don't use the C# compiler.

**Comment by eerhardt** [comment]
Oh, this is already done.  @piotrpMSFT made me log this issue and I never checked before logging it.

https://github.com/dotnet/cli/blob/2727b191e39e743aebf5f107b575c9021a67e9cb/src/Microsoft.DotNet.ProjectJsonMigration/ProjectMigrator.cs#L212-L216

**Comment by brthor** [comment]
👍
