### ISSUE TITLE
Move CLI libraries to netstandard1.3

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4360]
With the move to MSBuild, our tooling will only work on `netstandard1.3` supported platforms, since MSBuild targets `netstandard1.3`.

Also, we will be deleting most of our libraries.  Moving to MSBuild will remove the need for the following libraries:

- Microsoft.DotNet.Compiler.Common
- Microsoft.DotNet.Files
- Microsoft.DotNet.ProjectModel
- Microsoft.DotNet.ProjectModel.Loader
- Microsoft.DotNet.ProjectModel.Workspaces

of the two left:

- Microsoft.Extensions.Testing.Abstractions
- Microsoft.DotNet.Cli.Utils

The Testing.Abstractions library also will be removed with our current `dotnet test` strategy.

So that only leaves Microsoft.DotNet.Cli.Utils going forward.

The Cli.Utils library should only be used by the CLI and CLI tools.  So it shouldn't need to support anything before `netstandard1.3`.

In talking with @prafullbhosale, an issue that was raised that the Scaffolding tool may require the user's projects to depend on the Cli.Utils library.  However, after some discussion @prafullbhosale said:

> Scaffolding will de-couple getting the msbuild related information and actual scaffolding operations. 
This way only the ‘tool’ part of it would need to refer to Cli.Utils. 

So we should be free to move Cli.Utils to `netstandard1.3`.

@piotrpMSFT

**Comment by eerhardt** [comment]
AFAIK, no, nothing should be blocking.  /cc @anurse @pranavkm - Do you guys still take newer drops of the CLI rel/1.0.0 and expect no breaking changes?  Some day that is no longer going to be true, we are going to start removing the old project.json-based commands and libraries.

https://github.com/eerhardt/cli/commit/223b8ac1e4518f2a40a167658fb894bf7b9cf5ac - here is a prototype of converting to `netstandard1.3` that is building on my machine.

**Comment by pranavkm** [comment]
We haven't been picking up any new CLI packages (with the exception DependencyModel and anything it depends on). The rest continue to use the builds from NuGet.org (`preview2-003121`)

**Comment by piotrpMSFT** [comment]
@pranavkm any plans to change that?

@eerhardt assuming `no` from @pranavkm, PR your change?

**Comment by pranavkm** [comment]
Not that I know of.

**Comment by eerhardt** [comment]
Fixed with #4369
