### ISSUE TITLE
dotnet migrate ignores type: build in project.json

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/cli#4362]
## Steps to reproduce

1. `dotnet new` (create a project.json)
1. Open the project.json and add a dependency with `"type": "build"`
1. `dotnet migrate`

## Expected  behavior

There should be some indication in the csproj that the dependency is `"type": "build"`.

I think the equivalent in MSBuild world would be `<PrivateAssets>All</PrivateAssets>` metadata on the package reference.

## Actual behavior

The migrate script seems to ignore this property. That means `dotnet pack3` will include this reference in the resulting nupkg.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003786)

Product Information:
 Version:            1.0.0-preview3-003786
 Commit SHA-1 hash:  77e526396c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by brthor** [comment]
Tracked this down to a `==` instead of `.Equals`. 

Fix is incoming for this.
