### ISSUE TITLE
ProjectDependencyCommandResolver does not work with csproj

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4366]
Trying to resolve a dependency declared by a csproj does not currently work. This is due to the underlying `ProjectDependencyCommandResolver` system depending only on a project.json's `ProjectContext`.

**Comment by muratg** [comment]
:eyes:

**Comment by NTaylorMullen** [comment]
@pranavkm We'll need to pull new CLI bits once this fix makes it's way through their CI.
