### ISSUE TITLE
Ensure dotnet-install.sh is able to work with proxy servers

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4368]

**Comment by mendhak** [comment]
Since `dotnet-install.sh` uses `curl`, a user can set their `http_proxy` [environment variable](http://stackoverflow.com/questions/9445489/linux-curl-command-with-proxy) and it should get picked up

**Comment by piotrpMSFT** [comment]
@mendhak thanks. I'll close this issue, then, and point folks to it when the question comes up!
