### ISSUE TITLE
Migration should set a flag to stop generation of AssemblyInfo if the original project had AssemblyInfo.cs

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4378]
User Story : **As an existing developer of .NET Core projects, I can quickly migrate from xproj to csproj based project system and continue development without disruption**

## Steps to reproduce
- Create a project (core class library)  using dev14 (atleast Preview 2) 
- Copy the project folder to a machine with Dev15 installed.
- Double click the solution, this should prompt for a one way migration window and should successfully migrate the project over.
- Build the migrated project 

## Expected  behavior
Builds successfully 

## Actual behavior

1>------ Build started: Project: CoreCL, Configuration: Debug Any CPU ------ 
1>obj\Debug\netstandard1.5\CoreCL.AssemblyInfo.cs(14,12,14,60): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute 
1>obj\Debug\netstandard1.5\CoreCL.AssemblyInfo.cs(17,12,17,54): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute 
1>Done building project "CoreCL.csproj" -- FAILED. 
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

**Comment by jinujoseph** [comment]
Notes from @srivatsn 
The reason is that the SDK generates AssemblyInfo.cs but the project also had one and so there's duplicates. I think we should have a flag for turning off AssemblyInfo generation and dotnet migrate should set that flag in the csproj if the project being migrated has AssemblyInfo.cs.

**Comment by brthor** [comment]
dotnet migrate currently migrates project.json properties that influence AssemblyInfo to their equivalents in MSBuild. 

A simple clean (`rm -r bin obj`) after migration should solve this. 

There's also the issue of this file should be excluded by the sdk by default `obj\Debug\netstandard1.5\CoreCL.AssemblyInfo.cs`

**Comment by srivatsn** [comment]
I believe the issue here was that the original project had an actual AssemblyInfo.cs with attributes in it and so post migration we have the original AssemblyInfo.cs and the one generated by the SDK.

**Comment by brthor** [comment]
It seems strange that the original AssemblyInfo.cs would be in `obj`.

**Comment by srivatsn** [comment]
Not in obj. There's a xproj which had a Properties\AssemblyInfo.cs that's covered by a *.cs glob. Since ASsemblyInfo.cs wasn't generated before it would build. But now since we generate one, there are duplicate attributes.

**Comment by brthor** [comment]
I see, @jinujoseph can you please provide a repro?

**Comment by brthor** [comment]
After some experiments here, it looks like project.json is looking at the existing AssemblyInfo.cs attributes and excluding those from the generated AssemblyInfo.cs.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Compiler.Common/AssemblyInfoFileGenerator.cs#L23

I've filed an issue in the sdk to track this difference in behavior, but am going to leave this issue open until we hash that out.

**Comment by brthor** [comment]
The work for sdk to enable individual knobs for each assemblyinfo attribute is tracked here. After that goes in the migration fix can go in to turn off individual attributes that conflict with what the user has set.

https://github.com/dotnet/sdk/issues/302
