### ISSUE TITLE
Imports in dotnet-new csproj templates 

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4381]
The dotnet-new templates for project.json-based projects included an imports statement for dnxcore50 to enable easy inclusion of older libraries. The current csproj templates do not include any imports and will require manual user interaction to enable adding these libraries. This issue tracks a now-disabled test which will be deleted once we confirm we desire this new behavior.

/cc @blackdwarf @richlander @glennc @Petermarcu

**Comment by livarcocc** [comment]
I think we talked about avoiding adding imports as much as possible. Specially one for dnxcore50.

**Comment by glennc** [comment]
Avoiding imports as much as possible is definitely the goal, but we left them in previously due to package incompatibility.

Even today it takes several imports to use some of our Azure client libraries, like blob storage, and finding out how to make those work with imports was completely non-obvious. It is still a manual process to add an import right?

**Comment by eerhardt** [comment]
@glennc - What would it take to get the Azure client libraries to embrace .NETStandard?

**Comment by fearthecowboy** [comment]
@eerhardt / @glennc  

I'll tell you exactly what it'll take:  
- documentation on how to do some of these things
- stable tools and libraries.

I run the team building AutoRest, which generates the client libraries for .NET/NodeJS/Python/Ruby/Go/Java/etc...

We currently do build a lot of the libraries for netstandard, more every day. 

I'm spending some spare time trying to migrate the build scripts from -preview2 to -preview3 (ie, `project.json` back to `.csproj`) and there's still plenty of gotchas to go around. 

Until I can get everything building and running tests in CI with the tools, and not break or derail other developers, we're still in a bit of a holding pattern.

**Comment by piotrpMSFT** [comment]
@fearthecowboy what's causing other developers to become broken? You can run project.json and csproj tools SxS. Is this what you mean by documentation? Perhaps this will help...

https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md

**Comment by piotrpMSFT** [comment]
We've not had other issues regarding imports being missing from default templates since this change was introduced. I'm going to close this issue and remove the affected tests. I will continue the conversation with @fearthecowboy offline to help get the Azure team unblocked.

**Comment by piotrpMSFT** [comment]
PR is out.
