### ISSUE TITLE
Build of default Fsharp project fails due to missing codeanalysis.common assembly

### ISSUE THREAD

**Issue by pfgherardini** [dotnet/cli#4392]
## Steps to reproduce

```
dotnet new --lang f#
dotnet restore
dotnet build
```
## Expected  behavior

The project should build
## Actual behavior

Compilation fails with the following message

```
Project test-fsharp (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling test-fsharp for .NETCoreApp,Version=v1.0
C:\Program Files\dotnet\dotnet.exe compile-fsc @C:\Users\fgherardini\temp\test-fsharp\obj\Debug\netcoreapp1.0\dotnet-compile.rsp returned Exit Code -2147450740
C:\Users\fgherardini\temp\test-fsharp\Error: assembly specified in the dependencies manifest was not found -- package: 'microsoft.codeanalysis.common', version: '1.3.0', path: 'lib/netstandard1.3/Microsoft.CodeAnalysis.dll'
```
## Environment data

```
.NET Command Line Tools (1.0.0-preview3-003618)

Product Information:
 Version:            1.0.0-preview3-003618
 Commit SHA-1 hash:  0ce597a147

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
FSC is currently broken in preview3. @enricosada has an msbuild-based FSC on the way. Once that's checked in as a template you should be unblocked. @enricosada perhaps you want to share a PR #? :)

**Comment by enricosada** [comment]
@pfgherardini meanwhile you can use these https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3 templates based on msbuild.
I'll send the pr for console/lib in `dotnet new` when the target file will use an msbuild task (atm use `dotnet-compile-fsc`), i am finishing that soon

**Comment by benzsuankularb** [comment]
Also got this in mac, with `dotnet --version` 1.0.4
