### ISSUE TITLE
Builds sometimes clear content of build-info file in versions repo

### ISSUE THREAD

**Issue by naamunds** [dotnet/cli#4399]
## Expected  behavior

If all the CLI builds (for the various platforms) are successful, the last build to finish updates the build-info file in the versions repo (e.g. https://github.com/dotnet/versions/blob/master/build-info/dotnet/cli/rel/1.0.0/Latest_Packages.txt) to contain the latest versions of the packages that CLI is using.
## Actual behavior

The last build to finish instead clears the build-info file's contents. This has happened a few times recently, e.g. in https://github.com/dotnet/versions/commit/0dd87ccc28d9c396c2b4e454e613f795db3d03a7, https://github.com/dotnet/versions/commit/7c5246856a2faaccaddaafa6478eb6b055b3d401, and https://github.com/dotnet/versions/commit/eee403b0be28531f0074426a7d38fd3fb1617257.

**Comment by naamunds** [comment]
From looking at the `VersionRepoUpdater` code, it appears that this would happen when `Dirs.Packages` (`artifacts\<rid>\packages`) doesn’t contain any .nupkg files, but I'm not sure what causes that.

In addition to fixing the underlying issue here, I think we should consider adding a safeguard in having the build not update the versions repo if it doesn’t find any .nupkg files, because I assume that there's no case where we would want it to clear the build-info file.  In that case, the build could either fail or just have a warning for that.

**Comment by piotrpMSFT** [comment]
@naamunds is this still something we need to pursue? I've not seen any infra problems for some time...

**Comment by naamunds** [comment]
@piotrpMSFT It looks like this is still an issue.  https://github.com/dotnet/versions/blob/master/build-info/dotnet/cli/rel/1.0.0/Latest_Packages.txt has been empty since the last change to it, on Nov 4.  dotnet-docker-nightly depends on this file to update its preview3 CLI version, e.g. in https://github.com/dotnet/dotnet-docker-nightly/blob/master/1.0/debian/sdk/msbuild/Dockerfile#L30.

It doesn't appear to be affecting the preview2 or preview2.1 Latest_Packages.txt files, though.

/cc @MichaelSimons
