### ISSUE TITLE
PROPOSED: dotnet CLI command layering

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#44]
# Proposed dotnet CLI command layering
Commands in the dotnet CLI can represent atomic tasks, such as "Compile source to IL with the csc compiler" or more complicated workflows like "dotnet-compile" which should restore dependencies, compile to IL, then compile that IL to native.

We intend for workflows to be decomposable into their base atomic components, allowing for easy modification and integration into other workflow or build management systems.

We would also like for atomic commands to provide users with a common style so they can reason about the commands easily.

Finally, we expect that a single executable can provide the implementation of several commands [consider NuGet restore, install, list]. We shouldn't need multiple copies of the executable to expose these commands, though we prefer to represent them as individual items on the path.

## Requirements
The design of command layering, then, should satisfy the following requirements:
1. End-to-end commands like "dotnet-compile" should be composed of atomic commands
2. Atomic commands should have a single purpose
3. Atomic commands should have a common style
4. Atomic commands should follow the dotnet-<command> naming convention
5. A given tool should be able to expose multiple commands

## Design [proposed]
The base of the layering design is formed of the individual tools provided to dotnet developers. These tools are complemented by scripts representing atomic commands, wherein the scripts follow a similar style and each expose a single responsibility. These commands are then connected with one another via end-to-end scripts.

### Layering Diagram

<table align="center">
<tr><td COLSPAN="3">dotnet-compile</td></tr>
<tr><td>dotnet-restore</td><td>dotnet-compile-csc</td><td>dotnet-compile-il2native</td></tr>
<tr><td>nuget</td><td>csc</td><td>il2native</td></tr>
</table>

### Sample Scripts
The below snippets are trimmed down representations of the aforementioned concepts. They are not intended to capture the full implementation.

#### dotnet-compile
    dotnet restore
    dotnet compile-csc
    dotnet compile-il2native

#### dotnet-compile-csc
    csc /target:library /out:Something.xyz *.cs

**Comment by blackdwarf** [comment]
@piotrpMSFT should we move this to the proper spec in the repo and close this issue?

**Comment by piotrpMSFT** [comment]
This is fairly outdated now.
