### ISSUE TITLE
Raspberry PI 3 (ARM) Windows 10 iot target

### ISSUE THREAD

**Issue by JPBlanc** [dotnet/cli#4400]
Sorry, not a real issue

I perhaps lose something, but I can't find a way to install .Net Core on Raspberry PI3.

Is there a roadmap to target these machines ?

regards.

JPB

**Comment by piotrpMSFT** [comment]
@JPBlanc platform support matrix comes from the https://github.com/dotnet/coreclr repo. Can you  ask those guys about adding support? We'll be glad to target any platform that is supported :)
