### ISSUE TITLE
.NET Core .pkg installer not properly setting up PATH variable on macOS 10.12 (Sierra)

### ISSUE THREAD

**Issue by RPangrle** [dotnet/cli#4404]
## Steps to reproduce
1. Download the .pkg from https://go.microsoft.com/fwlink/?LinkID=827526
2. Install pkg
3. Open a new terminal window
4. Type in `dotnet`

## Expected  behavior

It finds the 'dotnet' CLI tool

## Actual behavior

```
rpangrle-imac:~ rpangrle$ dotnet
-bash: dotnet: command not found
```

## Environment data
`dotnet --info` output: (N/A, see above)

I did not previously have .NET Core installed.

There is no /etc/paths.d folder either, which might also be causing issues with the installer script. When I created the directory and dropped a file with the following in it it seems to work:

```
/usr/local/share/dotnet
```

**Comment by piotrpMSFT** [comment]
@RPangrle can you share the output of `echo $PATH`?

**Comment by akoeplinger** [comment]
This sounds like https://github.com/dotnet/core-setup/pull/362

**Comment by RPangrle** [comment]
Yup, that'd be it.
