### ISSUE TITLE
Passing configuration parameter value to project.json

### ISSUE THREAD

**Issue by rnagpal** [dotnet/cli#4407]
I need to pack configuration specific native dlls in my nuget package. Is there a way for me to pass on the <configuration> value that I pass when running dotnet pack -c <configuration> into project.json so that I can replace it for <configuration> in the below packOptions section of project.json?

"packOptions": {
    "files": {
      "mappings": {
        "runtimes/win10-x64/native/": {
          "includeFiles": [
            "../../../../../../bin/x64/<configuration>/Microsoft.Azure.Documents.ServiceInterop.dll"          
           ]
        }
      }
    }
  }

**Comment by piotrpMSFT** [comment]
@rnagpal this is not supported in project.json but will be quite easy to do with [csproj](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) :)
