### ISSUE TITLE
Custom property for relative paths used in project.json

### ISSUE THREAD

**Issue by rnagpal** [dotnet/cli#4408]
I have several files and I need to use the relative paths like below in my project.json:

"includeFiles": [ "../../../../../../bin/x64//Microsoft.Azure.Documents.ServiceInterop.dll"]

Is there a way in which I can define a variable for "../../../../../../" in project.json and then use it everywhere else in project.json instead of repeating this for all files?

**Comment by piotrpMSFT** [comment]
@rnagpal this is not supported in project.json but will be quite easy to do with [csproj](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) :)
