### ISSUE TITLE
Restore package from private nuget repository with basic authentication

### ISSUE THREAD

**Issue by Kemyke** [dotnet/cli#4410]
## Steps to reproduce

We have a private repo which needs authentication. I would like to build up an ubuntu build agent host. Right now it can't restore the package from our nuget repository. My nuget config looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NexogenNuget" value="https://COMPANY_NUGET_URI/NugetServer/nuget" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSourceCredentials>
    <NexogenNuget>
      <add key="Username" value="NUGETUSER" />
      <add key="ClearTextPassword" value="NUGETPWD" />
    </NexogenNuget>
  </packageSourceCredentials>
</configuration>
```

The nuget server is hosted in IIS and Windows authentication and Basic authentication are enabled. If i try it with curl i can access it with a local user or with my windows account also.

```
curl -u NUGETUSERNUGETPWD "https://COMPANY_NUGET_URI/NugetServer/nuget/FindPackagesById()?id='TestPkg'"
```

Returns

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<feed xml:base="https://COMPANY_NUGET_URI/NugetServer/nuget/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <title type="text">FindPackagesById</title>
  <id>https://COMPANY_NUGET_URI/NugetServer/nuget/FindPackagesById</id>
  <updated>2016-10-14T11:53:16Z</updated>
  <author>
    <name />
  </author>
  <link rel="self" title="FindPackagesById" href="FindPackagesById" />
```

## Expected  behavior

It should download the package from private repo. I read that clear text password is supported.

## Actual behavior

But if i try the dotnet restore it says:

```
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://COMPANY_NUGET_URI/NugetServer/nuget/FindPackagesById()?id='testpkg''.
log  : Response status code does not indicate success: 401 (Unauthorized).
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

**Comment by piotrpMSFT** [comment]
Moved to nuget/home#3664

**Comment by Kemyke** [comment]
I am not sur if its a nuget problem because i experience this when using 'dotnet restore'.

**Comment by Kemyke** [comment]
The first request is my test with the curl and it looks ok:
```
GET /NugetServer/nuget/FindPackagesById()?id='PACKAGE_NAME' HTTP/1.1
Host: nuget.company.com
Authorization: Basic bnGnEDF0RYN0OlRpdG9rMITzNA==
User-Agent: curl/7.47.0
Accept: */*
```
But all the others are not containing the Authorization header and look like this:
```
GET /NugetServer/nuget/FindPackagesById()?id='PACKAGE_NAME' HTTP/1.1
Host: nuget.company.com
Accept-Encoding: gzip,deflate
Accept: application/atom+xml, application/xml
user-agent: NuGet xplat/3.5.0-beta2-1484 (Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016)
```
