### ISSUE TITLE
Build Cli with newly added command

### ISSUE THREAD

**Issue by hishamco** [dotnet/cli#4411]
I already added a new command to `dotnet` project, I wanna to use my newly added command by generating a new version that will bed added in `C:\Program Files\dotnet\sdk` folder, so I can used my command for any project that I want

**Comment by piotrpMSFT** [comment]
Your build on Windows should have produced an installer that you can run on your local machine. The installer should be in `artifacts/<rid>/stage2/package` iirc.

**Comment by piotrpMSFT** [comment]
If you plan on sharing the command, please look at the updated developer guide:
https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/developer-guide.md

it describes some of the models available for making that happen.

**Comment by piotrpMSFT** [comment]
I'll leave this issue open for another day in case this doesn't unblock you.

**Comment by hishamco** [comment]
Should I build the `dotnet` project or build the default project in cli solution, to produce the previous installer?

**Comment by hishamco** [comment]
BTW I got this error while running `build.cmd`

dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-003842/dotnet-dev-win-x64.1.0.0-preview3-003842.zip
Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview3-00
3842/dotnet-dev-win-x64.1.0.0-preview3-003842.zip.
At C:\Users\Dell\Source\Repos\cli\scripts\obtain\dotnet-install.ps1:157 char:13
+             throw $ErrorMsg
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to downl...ew3-003842.
   zip.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to download https://dotnetcli.azureedge.n
   et/dotnet/Sdk/1.0.0-preview3-003842/dotnet-dev-win-x64.1.0.0-preview3-0038
  42.zip.

**Comment by livarcocc** [comment]
You need to run build.cmd.

After that you can either use the generated installer or you can add the stage2 to your path so that when you run dotnet it will actually be running the one that you just build. Just add <repo_root>/artifacts/<rid>/stage2 to your path.

Also, for the failure above, can you confirm that you can reach that URL manually? You should be able to. Are you behind a proxy maybe? If so, you need to set the proxy address in the install script. Though, in order to do that for the CLI build, you will need to update the init_tools.ps1 script.

https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.ps1#L50

**Comment by hishamco** [comment]
Thanks @livarcocc for the detail information, i'm unable to find `/artifacts/stage2`, regarding the Url I can download it manually and I'm not use any kind of proxy

**Comment by livarcocc** [comment]
I meant artifacts/<rid>/stage2

**Comment by hishamco** [comment]
Finally I'm able to run `build.cmd` and I set the `artifacts/win10-x64/stage2` to the system path, but when I run `dotnet --version` it shows the version which is available in `C:\Program Files\dotnet\sdk`

**Comment by livarcocc** [comment]
You need to add the full path to your stage2 folder to the PATH and make sure it comes before `c:\program files\dotnet\sdk`

**Comment by hishamco** [comment]
I move the stage2 folder path before `c:\program files\dotnet\sdk` and it works like a charm 😄 , thanks a lot

**Comment by hishamco** [comment]
I changes some code in `dotnet` project, when I rebuild the entire solution I got **error CS0006: Metadata file '???' could not be found**, so now when I run `dotnet --version` I'm getting **A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Users\Dell\Source\Repos\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003805'.**

**Comment by piotrpMSFT** [comment]
@hishamco did you get past this issue? It sounds like a partial build left the stage2 directory in a bad state...

**Comment by hishamco** [comment]
@piotrpMSFT nope this the first time I see this, because as the beginning I was blocked by the first exception that I posted before.

> It sounds like a partial build left the stage2 directory in a bad state...

So how can I fix it

**Comment by piotrpMSFT** [comment]
I'd commit my changes, run `git clean -xfd` on my clone of the repo, then do a full build. Also, make sure your PATH is pointing to the root of the Stage2 directory. The message above suggests you're trying to invoke dotnet.dll directly from `C:\Users\Dell\Source\Repos\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview3-003805`

**Comment by hishamco** [comment]
Can I do the clean & build in my local repo as well?!!
FYI the path is pointing to `C:\Users\Dell\Source\Repos\cli\artifacts\win10-x64\stage2`

**Comment by hishamco** [comment]
I forked this repo, I fetched the latest updates and I run `build.cmd` again i'm not able to download the **dev-win-x64.1.0.0-preview3-003842.zip** FYI i'm not running behind a proxy, but after several time with running the script it produces `artifacts/<rid>/stage2`
So my question is why this error show up again and again, second thing should I run 'build.cmd' when I modify or create a new dotnet command?

**Comment by hishamco** [comment]
When I run `build.cmd` after any change I made I got this

 "C:\Users\Dell\Source\Repos\cli\build.proj" (default target) (1) ->
       (GenerateArchives target) ->
         C:\Users\Dell\Source\Repos\cli\build\package\Microsoft.DotNet.Cli.Archive.targets(15,5): error : An exception has occured while trying to compress 'C:\Users\Dell\Source\Repos\cli\/artifacts/win10-x64/intermediate/layouts/dotnet-sdk' into 'C:\Users\Dell\Source\Repos\cli\/artifacts/win10-x64/packages/dotnet-sdk-win-x64.1.0.0-preview3-004049.zip'. [C:\Users\Dell\Source\Repos\cli\build.proj]

any idea @piotrpMSFT

**Comment by livarcocc** [comment]
Do you have the zip file opened somewhere so that there is a handle for it preventing the build from overwriting it?

**Comment by hishamco** [comment]
Which zip file you mean?

**Comment by livarcocc** [comment]
The one just mentioned in the error above. We run build.cmd tens of times a day and this error I have never seen. Which makes believe that you may have opened that zip file at some point and left it open. At least I can't think of something else at the moment.

**Comment by piotrpMSFT** [comment]
`C:\Users\Dell\Source\Repos\cli\/artifacts/win10-x64/packages/dotnet-sdk-win-x64.1.0.0-preview3-004049.zip`

this file. Delete it, then try the build again. Something seems to have it locked.

**Comment by hishamco** [comment]
@livarcocc there's no zip file opened
@piotrpMSFT i delete it still the error show up but with new file `https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview4-00
4079/dotnet-dev-win-x64.1.0.0-preview4-004079.zip`

**Comment by piotrpMSFT** [comment]
@hishamco if that is making forward progress, I'd keep following the pattern. It seems something is funny about your local clone. Perhaps commit your work, clean your clone [even create a new one] and re-run the build. I don't know what's keeping files in use for you. Looking at our CI, we're running these builds 100's of times per day and haven't seen this issue.

**Comment by hishamco** [comment]
I will try to remove it from local and pull it again, one last question @piotrpMSFT if I change something in my code shall I run `build.cmd` again or building the solution is enough to reflect the changes to the newly created `dotnet`?

**Comment by piotrpMSFT** [comment]
Solution builds are in no way wired up at this point. We brought up the build system for CLI long before we had access to sln builds and therefore have some... signs of age in the code base to clean up. You will want to run build.cmd.

**Comment by hishamco** [comment]
Thanks to you all for your help
