### ISSUE TITLE
Migration: Promote ProjectReferences and Reference items

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#4414]
Promote ProjectReferences and Reference items all the way up transitive references. 

Workaround for:
https://github.com/dotnet/roslyn-project-system/issues/199

**Comment by brthor** [comment]
Set PrivateAssets All on all promoted refs.

**Comment by livarcocc** [comment]
Project A -> Project B -> Project C, this is not supported by the SDK because it does not handle transitive dependencies.
We need to add Project C as a ProjectDependency of Project A.

**Comment by nguerrera** [comment]
@livarcocc Was https://github.com/dotnet/cli/issues/4414#issuecomment-253925947 addressed with the fix, I'm not seeing it? cc @joelverhagen

**Comment by nguerrera** [comment]
If not and pack is generating too many dependencies, we can infer private assets from FromP2P in the SDK to make things retroactively work on already migrated projects.

**Comment by livarcocc** [comment]
@nguerrera No, it was not added. And that is a mistake. It should have been. I can add this going forward, if necessary. But if you can handle it using the FromP2P, that would be good too.
