### ISSUE TITLE
dotnet restore crashing every time on every project. Message: The given path's format is not supported

### ISSUE THREAD

**Issue by HristoKolev** [dotnet/cli#4415]
Whenever I go to any project and run `dotnet restore` I get error 'The given path's format is not supported'.

Here is the output with --verbosity Debug
http://pastebin.com/iqgMsQWu

* It says 4 concurrent jobs but I have only 2 projects. Running it with --disable-parallel didn't fix it.
* Deleting %userprofile%\.nuget didn't fix it.
* Deleting everything in %temp% didn't fix it.
* System restart didn't fix it.
* Repairing it with DotNetCore.1.0.1-VS2015Tools.Preview2.0.2.exe didn't fix it.

It gives that error even when the project is just created with `dotnet new`.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@HristoKolev this is a NuGet issue. Moving to nuget/home.

**Comment by piotrpMSFT** [comment]
Moved to https://github.com/NuGet/Home/issues/3663
