### ISSUE TITLE
Packages generated by CLI repo have invalid version number

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#442]
From NuGet docs [http://docs.nuget.org/Create/Versioning]:

````
SemVer also introduces the concept of a build number for those creating daily or continuous builds. This is not supported in the public NuGet.org gallery, so while this is allowed:
* 1.0.1-build23

including the SemVer-compatible build number with dot notation is not allowed:
* 1.0.1-build.23
````

Our version number currently comes out as `1.0.0-16778.1449621033` which clearly violates the rule. We should change this to `1.0.0-alpha-16778-1449621033`

@krwq

**Comment by davidfowl** [comment]
Yep

**Comment by brthor** [comment]
What about just:  `1.0.0-alpha-1449621033` ?

Less to type and the two numbers have essentially the same information.

**Comment by krwq** [comment]
What about
```
1.0.0-dev-1449621033 
```
I'm good with `alpha` too although alpha suggest version which you give to users which daily build isn't

**Comment by piotrpMSFT** [comment]
Dev is fine. The we need both numbers for now. First one is date second is time. If we don't keep both we won't have increasing versions.

We need to shorten for release builds. For Dev I think it's fine with the big number.

**Comment by piotrpMSFT** [comment]
I'm working on fixing this now.

**Comment by krwq** [comment]
i have it fixed on my branch already

**Comment by piotrpMSFT** [comment]
send a PR :) I have another feature blocked on this that I need to get done tonight.

**Comment by krwq** [comment]
ok, I was planning to clean this code a little bit tomorrow (i.e. move that settings class to context). let me just remove "WIP" commit and send it

**Comment by piotrpMSFT** [comment]
looks like this is fixed. Can you close it out, @krwq? Also, please include PR number when closing.

**Comment by krwq** [comment]
https://github.com/dotnet/cli/pull/449
