### ISSUE TITLE
Change --no-dependencies to --no-project-refs in all CLI commands where it appears

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4422]
In the `project.json` world we had dependencies and thus we had a `--no-dependencies` switch to allow `dotnet build` to **not** build P2P dependencies. 

In the new csproj and MSBuild world, we have _references_ and P2Ps are denoted with `<ProjectReference>` element within the project file. It makes sense, from a cognitive unification perspective, to rename the `--no-dependencies` switch for those commands that support it to `--no-project-refs`. The actual functionality of the switch remains the same. 

/cc @eerhardt @piotrpMSFT @richlander

**Comment by piotrpMSFT** [comment]
This change will need to be made in `dotnet build` and `dotnet restore`.

**Comment by piotrpMSFT** [comment]
@blackdwarf @richlander do we really want to make this breaking change?

**Comment by blackdwarf** [comment]
@piotrpMSFT no. When I created this issues it *seemed* like the right thing to do, however, on second thought, it is nitpicking on something that is common understanding. That coupled with the breaking change nature of it seems to me like we should close it, so I will do just that.
