### ISSUE TITLE
msbuild 'dotnet new' templates not packable

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#4425]
## Steps to reproduce
* `dotnet new --type lib` /  `dotnet new`
* `dotnet restore3`
* `dotnet pack3`

## Expected  behavior
Should create a `.nupkg` just like preview 2 versions.
In Preview 2, package id, authors and description defaulted to the project name.

## Actual behavior
```
/Users/martin/.nuget/packages/nuget.build.tasks.pack/3.6.0-rc-1973/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(71,5): error MSB4018: System.Exception: Id is required. [/Users/martin/tmp/tmp.csproj]
/Users/martin/.nuget/packages/nuget.build.tasks.pack/3.6.0-rc-1973/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(71,5): error MSB4018: Authors is required. [/Users/martin/tmp/tmp.csproj]
```

Can be easily worked around if add the package id / assembly name and authors field. But since documentation around it is currently very light (except for the wiki article on the nuget/home repo), it is not a very good onboarding experience.

## Options
1.) Keep it as it is, maybe improve the error message (`Add an "<Authors>your name</Authors>" element to your project's <PropertyGroup> element`).
2.) Extend the `dotnet new` templates to emit the required properties.
3.) Add fallbacks to the NuGet targets to derive the properties from the msbuild file name.

## Environment data
`dotnet --info` output (fixed `DOTNET_RUNTIME_ID` macOS sierra workaround):

```
.NET Command Line Tools (1.0.0-preview3-003853)

Product Information:
 Version:            1.0.0-preview3-003853
 Commit SHA-1 hash:  ad19f5ecb7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

/cc @piotrpMSFT @eerhardt

**Comment by eerhardt** [comment]
I think the correct approach here is to default ID and Authors like they were in project.json based projects.

For ID, it just uses the project.Name (which is the same as the assembly name):
https://github.com/dotnet/cli/blob/1278e9d6bf35500e9672fe3f53125df1d08717d8/src/dotnet/commands/dotnet-pack/PackageGenerator.cs#L390

For Authors, if the value isn't set in the PJ, it looks for an environment variable.  If that isn't set, it falls back to the project.Name: https://github.com/dotnet/cli/blob/1278e9d6bf35500e9672fe3f53125df1d08717d8/src/dotnet/commands/dotnet-pack/PackageGenerator.cs#L376-L387

**Comment by eerhardt** [comment]
I'll work on this today.
