### ISSUE TITLE
Requesting support for tools in global.json

### ISSUE THREAD

**Issue by lewislabs** [dotnet/cli#4427]
I'd like to be able to use tools in global.json in the same way it works for project.json, such that it's possible to run custom `dotnet` commands from a root directory.

**Comment by piotrpMSFT** [comment]
@DamianEdwards you're looking at something related...

**Comment by livarcocc** [comment]
We now have local tools that is our answer to this request. It is not in global.json though. It uses its own new tool manifest file.
