### ISSUE TITLE
Running a non-existent tool mutates the console prompt foreground colour

### ISSUE THREAD

**Issue by adamralph** [dotnet/cli#4428]
## Steps to reproduce

Execute `dotnet toolthatdoesnotexist`.

## Expected  behavior

My console prompt foreground colour is preserved.

## Actual behavior

My console prompt foreground colour is not preserved.

![image](https://cloud.githubusercontent.com/assets/677704/19447805/6d4dc978-949f-11e6-95e5-0cef9bc4999d.png)

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
I tried this with 1.0.0-preview2-003121 and could not repro it. I tried it in powershell, cmd, zsh and powershel ISE prompt.

**Comment by adamralph** [comment]
It happens in plain old cmd.exe

![image](https://cloud.githubusercontent.com/assets/677704/19459463/65d71e22-94d3-11e6-9e5c-6b4e999d1c47.png)

Note that I am using `1.0.0-preview2-003131` (see the `dotnet --info` output which I pasted into the description).

**Comment by adamralph** [comment]
If I change my foreground colour to white, it changes it to grey. It seems to be reading the current colour and dimming it to the darker version.

![image](https://cloud.githubusercontent.com/assets/677704/19459508/be66c29a-94d3-11e6-8df7-e436a0eed38d.png)

**Comment by shanselman** [comment]
I also hit this. I have internal emails on it also. I'll talk about it in #4850

**Comment by piotrpMSFT** [comment]
Yep, we're tracking in #4850.
