### ISSUE TITLE
postcompile/precompile doesn't respect exit code of the command

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#443]
compile doesn't fail when the postcompile/pre command failed.

**Comment by piotrpMSFT** [comment]
We expect to be dropping script support, so putting this off for now.

**Comment by anurse** [comment]
Are we still dropping script support? /cc @piotrpMSFT @davidfowl 

If not, this is affecting our own builds because we do a `dotnet build` in a precompile script (for ArgumentForwarderTests) and if it fails, the build doesn't fail.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
