### ISSUE TITLE
dotnet restore times out while building CoreCLR on x64 Ubuntu 16.04

### ISSUE THREAD

**Issue by hadibrais** [dotnet/cli#4431]
## Steps to reproduce

While building CoreCLR using `./build`, the following step is successfully reached:

`Running: /coreclr/Tools/dotnetcli/dotnet restore "/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00809-01/lib/tool-runtime/project.json" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json`

However, the packages are not being successfully restored. I'm getting the following output for every package that needs to be restored:

```
log  : Restoring packages for /coreclr/packages/Microsoft.DotNet.BuildTools/1.0.26-prerelease-00809-01/lib/tool-runtime/project.json...
log  : Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/msbuild/index.json'.
log  : The download of 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-buildtools/nuget/v3/flatcontainer/msbuild/index.json' timed out because no data was received for 60000ms.
log  :   Exception of type 'System.TimeoutException' was thrown.
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

(Even though this shows I've got CLI 1.0.0-preview2-003131, the CLI version that build script is trying to download and install is 1.0.0-preview3-003223. That's strange.)

Not sure if this would be a problem, but I'm behind a web proxy. However, the env variable `http_proxy` is set correctly (`wget` is working perfectly).

**Comment by livarcocc** [comment]
Please, re-open this in the CoreCLR repo.
