### ISSUE TITLE
Make /m default invocation of msbuild in CLI

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4434]

**Comment by livarcocc** [comment]
If we make this the default, how would people turn it off? Should we add a no-parallel option to all our verbs?

**Comment by piotrpMSFT** [comment]
Fixed by #4543 

@livarcocc msbuild honors the last /m passed to it. Our implementation prepends m to other user arguments. This means that users can simply pass `/m:1` to their invocations of CLI commands, and this will reset MSBuild to use a single node.
