### ISSUE TITLE
Installer for framework 1.1.0-preview1-001100-00

### ISSUE THREAD

**Issue by kierenj** [dotnet/cli#4436]
## Steps to reproduce
1. Reference a fairly new nightly build of EF tools, e.g. "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.0.0-preview3-*",
2. This in turn requires `Microsoft.NETCore.App/1.1.0-preview1-*`, so reference that
3. Attempt to run
## Expected  behavior

Success!
## Actual behavior

Failure :(

```
The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-00' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.1
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.
```

...How can I install framework version `1.1.0-preview1-001100-00`, please?
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by kierenj** [comment]
Slight side-note, but, if there's a more official way to "be on nightlies", that would be great.  I'm just using the dev feed and referencing 1.1.0-alpha1-* versions where I can.

**Comment by mauricew** [comment]
The feed is https://dotnet.myget.org/gallery/aspnet-1-1-0-preview1 and nuget.config should be updated accordingly.

**Comment by kierenj** [comment]
@mauricew I have the package - dotnet restore works fine for that version - what I don't have is an installer for the framework.  I'm not sure I understand?

**Comment by mauricew** [comment]
I don't think there's any installer for tooling at the moment, that could be decoupled from the framework/library versions. But the individual framework components download seamlessly and you can switch between netcoreapp1.0 and netcoreapp1.1 (along with feeds & deps) depending what you're working on.

**Comment by kierenj** [comment]
I think I'm still missing something - this works fine for dependencies and nuget packages, but it still wants the new framework to run (see original error message).  That's with that feed only (removed myget.org/F/dotnet-core and dotnet.myget.org/F/aspnetcore-dev), and using netcoreapp1.1 as you say.
As I understand it, the framework is the bit that has to be installed on your machine separately, with an installer.  My C:\Program Files\dotnet\shared\Microsoft.NETCore.App has 1.0.1 (as the error message indicated).  There's no 1.1.0 there, and I'm not convinced that's populated from a nuget feed?

**Comment by mauricew** [comment]
Check %userprofile%\.nuget\packages\Microsoft.NETCore.App and see if you have a 1.1.0-* there

**Comment by kierenj** [comment]
Ah yes, I do - but isnt that the equivalent to reference assemblies, i.e. OK to build against, but not run?  Not trying to be difficult - I want it to work!

**Comment by mauricew** [comment]
I created a repo out of the code + config I had

https://github.com/mauricew/netcoreapp1.1

**Comment by kierenj** [comment]
Thank you, that does indeed install a load of `runtime.*` packages.
It's quite a large codebase I'm playing with, so I'll have some fun finding the point between the two examples next.. it feels like maybe some other dependency (from public nuget) is asking for netcoreapp1.0 perhaps and pulling down the version, or something along those lines.

**Comment by mauricew** [comment]
I may have misunderstood the problem, you were trying to run `dotnet ef` right? See the latest update I made, it has a solution which I believe would work but it is a big hack and I recommend it should be done only if you really want to use the latest EF tools right now

**Comment by piotrpMSFT** [comment]
The Shared Framework installers get built in the https://github.com/dotnet/core-setup/ repo. @gkhanna79 should be able to point you to installer links, if that becomes needed again.

**Comment by jhayotte** [comment]
Hi @kierenj,

> The specified framework 'Microsoft.NETCore.App', version '1.1.0-preview1-001100-00' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
  - Alternatively, install the framework version '1.1.0-preview1-001100-00'.

Any update on your side to fix this ? I don't find any installer to get  the framework installed in `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.1`

**Comment by gkhanna79** [comment]
The installers for 1.1.0-Preview1 are available off https://blogs.msdn.microsoft.com/dotnet/2016/10/25/announcing-net-core-1-1-preview-1/.

CC @leecow
