### ISSUE TITLE
Running `dotnet` command with --verbose looks for executable with `dotnet-` prefix

### ISSUE THREAD

**Issue by RochesterinNYC** [dotnet/cli#4437]
## Steps to reproduce

```
git clone git@github.com:cloudfoundry-incubator/dotnet-core-buildpack.git
cd dotnet-core-buildpack
cd cf_spec/fixtures/asp_web_app_vendored
dotnet --verbose asp_web_app.dll

```
## Expected  behavior

```
Hosting environment: Production
Content root path: /private/tmp/dotnet-core-buildpack/cf_spec/fixtures/asp_web_app_vendored
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```
## Actual behavior

```
Telemetry is: Enabled
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-asp_web_app.dll"
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.9
 OS Platform: Darwin
 RID:         osx.10.9-x64
```

We have a vendored dotnet web app (https://github.com/cloudfoundry-incubator/dotnet-core-buildpack/tree/develop/cf_spec/fixtures/asp_web_app_vendored). We can run it successfully with `dotnet asp_web_app.dll`. However, if we specify the `--verbose` flag like so: `dotnet --verbose asp_web_app.dll`, it fails with the error listed above. Using the `--verbose` flag seems to make the CLI look for the executable we specified but with a `dotnet-` prefix in front. (`asp_web_app.dll` --> `dotnet-asp_web_app.dll`.

**Comment by piotrpMSFT** [comment]
This is by-design. The host, dotnet.exe, does not have a `--verbose` option. What would you expect that option to do? Perhaps we should add it...

**Comment by piotrpMSFT** [comment]
Closing as we don't have any traction here.
