### ISSUE TITLE
Hexadecimal value 0x00, is an invalid character

### ISSUE THREAD

**Issue by rannien** [dotnet/cli#4441]
## Steps to reproduce

1. `yo aspnet`
2. Select Web Application
3. After the install completed `dotnet restore`

## Expected  behavior
Finish the restore and install all the required project dependencies.

## Actual behavior
Error after the start of restore with the message: 
`log  : Restoring packages for F:\WebApplicationBasic\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in F:\WebApplicationBasic\project.json...
error: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.`

## Detailed trace with `dotnet restore --verbosing Debug`
`log  : Restoring packages for tool 'BundlerMinifier.Core' in F:\WebApplicationBasic\project.json...
trace: Restoring packages for .NETCoreApp,Version=v1.0...
trace: Resolving conflicts for .NETCoreApp,Version=v1.0...
trace: Scanning packages for runtime.json files...
error: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
trace: System.AggregateException: One or more errors occurred. ('.', hexadecimal value 0x00, is an i
nvalid character. Line 1, position 1.) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
trace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
trace:    at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
trace:    at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
trace:    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
trace:    at System.Xml.XmlTextReaderImpl.Read()
trace:    at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
trace:    at NuGet.Packaging.Core.NuspecCoreReaderBase.LoadXml(Stream stream, Boolean leaveStreamOpen)
trace:    at NuGet.Packaging.Core.NuspecCoreReaderBase..ctor(Stream stream, Boolean leaveStreamOpen)
trace:    at NuGet.Packaging.NuspecReader..ctor(Stream stream)
trace:    at NuGet.Repositories.LocalPackageInfo.get_Nuspec()
trace:    at NuGet.Commands.LockFileUtils.CreateLockFileTargetLibrary(LockFileLibrary library, Local
PackageInfo package, RestoreTargetGraph targetGraph, VersionFolderPathResolver defaultPackagePathRes
olver, String correctedPackageName, LibraryIncludeFlags dependencyType, NuGetFramework targetFramewo
rkOverride, IEnumerable'1 dependencies)
trace:    at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec pr
oject, IEnumerable'1 targetGraphs, NuGetv3LocalRepository repository, RemoteWalkContext context, IEn
umerable'1 toolRestoreResults)
trace:    at NuGet.Commands.RestoreCommand.BuildLockFile(LockFile existingLockFile, PackageSpec proj
ect, IEnumerable'1 graphs, NuGetv3LocalRepository localRepository, RemoteWalkContext contextForProje
ct, IEnumerable'1 toolRestoreResults, Boolean relockFile)
trace:    at NuGet.Commands.RestoreCommand.<ExecuteToolRestoresAsync>d__13.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext(
)
trace:    --- End of inner exception stack trace ---
trace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
trace:    at System.Threading.Tasks.Task'1.GetResultCore(Boolean waitCompletionNotification)
trace:    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.<>c__DisplayClass68_0.<OnExecute>b__0()
trace:    at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
trace:    at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
trace: ---> (Inner Exception #0) System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
trace:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
trace:    at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
trace:    at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
trace:    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
trace:    at System.Xml.XmlTextReaderImpl.Read()
trace:    at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
trace:    at NuGet.Packaging.Core.NuspecCoreReaderBase.LoadXml(Stream stream, Boolean leaveStreamOpen)
trace:    at NuGet.Packaging.Core.NuspecCoreReaderBase..ctor(Stream stream, Boolean leaveStreamOpen)
trace:    at NuGet.Packaging.NuspecReader..ctor(Stream stream)
trace:    at NuGet.Repositories.LocalPackageInfo.get_Nuspec()
trace:    at NuGet.Commands.LockFileUtils.CreateLockFileTargetLibrary(LockFileLibrary library, LocalPackageInfo package, RestoreTargetGraph targetGraph, VersionFolderPathResolverdefaultPackagePathResolver, String correctedPackageName, LibraryIncludeFlags dependencyType, NuGetFramework targetFrameworkOverride, IEnumerable'1 dependencies)
trace:    at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable'1 targetGraphs, NuGetv3LocalRepository repository, RemoteWalkContext context, IEnumerable'1 toolRestoreResults)
trace:    at NuGet.Commands.RestoreCommand.BuildLockFile(LockFile existingLockFile, PackageSpec project, IEnumerable'1 graphs, NuGetv3LocalRepository localRepository, RemoteWalkContext contextForProject, IEnumerable'1 toolRestoreResults, Boolean relockFile)
trace:    at NuGet.Commands.RestoreCommand.<ExecuteToolRestoresAsync>d__13.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<Execute>d__1.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<>c__DisplayClass0_0.<<Run>b__0>d.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__2.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.Commands.RestoreRunner.<Run>d__0.MoveNext()
trace: --- End of stack trace from previous location where exception was thrown ---
trace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
trace:    at System.Runtime.CompilerServices.TaskAwaiter'1.GetResult()
trace:    at NuGet.CommandLine.XPlat.RestoreCommand.<>c__DisplayClass0_1.<<Register>b__1>d.MoveNext(
)<---`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by livarcocc** [comment]
Please, file this issue in the aspnet repo.

**Comment by rannien** [comment]
Could you tell me in which repository should I file this issue?
