### ISSUE TITLE
Is dotnet generating .csproj file on fly and use it for the dotnet build now?

### ISSUE THREAD

**Issue by jianyunt** [dotnet/cli#4443]
As of Monday, Oct. 17, , we are observing the error like “Failed to create prime the NuGet cache. restore3 failed in dotnet restore”  in our [AppVeyor runs](https://ci.appveyor.com/project/jianyunt/oneget/build/1.0.245/job/tn0dks99fhf28iv2). See details below. Any ideas to resolve it?

Project "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" on node 1 (Restore target(s)).
Project "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (1) is building "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (1:2) on node 1 (_GenerateRestoreGraphProjectEntry target(s)).
Project "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (1:2) is building "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (1:3) on node 1 (_GenerateRestoreGraphWalkPerFramework target(s)).
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview3-003857\Microsoft.Common.CurrentVersion.targets(729,5): error : The OutputPath property is not set for project 'oylpnnlj.dow.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj]
Done Building Project "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (_GenerateRestoreGraphWalkPerFramework target(s)) -- FAILED.
Done Building Project "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (_GenerateRestoreGraphProjectEntry target(s)) -- FAILED.
Done Building Project "C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (Restore target(s)) -- FAILED.
Build FAILED.
"C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (Restore target) (1) ->
"C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (_GenerateRestoreGraphProjectEntry target) (1:2) ->
"C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj" (_GenerateRestoreGraphWalkPerFramework target) (1:3) ->
(_CheckForInvalidConfigurationAndPlatform target) -> 
  C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview3-003857\Microsoft.Common.CurrentVersion.targets(729,5): error : The OutputPath property is not set for project 'oylpnnlj.dow.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Users\appveyor\AppData\Local\Temp\1\oylpnnlj.dow\oylpnnlj.dow.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:00.89
dotnet : Failed to create prime the NuGet cache. restore3 failed with: 1
At C:\projects\oneget\src\build.ps1:91 char:9
+         dotnet restore
+         ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Failed to creat... failed with: 1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
log  : Restoring packages for C:\projects\oneget\src\Microsoft.PackageManagement\project.json...
log  : Installing System.Linq 4.0.0.

**Comment by livarcocc** [comment]
dotnet new has been recently changed to generate msbuild based artifacts given that the whole CLI is moving to msbuild and we won't have support for project.json for much longer.

So, if you run dotnet new, you will also need to run dotnet restore3 and dotnet build3 to have that project built. Though note that soon, the 3 based commands are going to become the default commands.

**Comment by jianyunt** [comment]
thx for your response. What do we need to do to fix the above error for now?
