### ISSUE TITLE
Consider allowing distro auto-detection in dotnet-install.sh

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#4445]
In `dotnet-install.sh`, we have [a variety of distro-name-version checks](https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.sh#L70) in order to control which download URL to use. To allow for more flexibility, we might want to consider allowing the script to just use the "name-version" string that it extracts from /etc/os-release by default. This is the pattern that most of the distros use, and we can just special-case the distros/versions which need a different string (there are a few). On the other hand, this means the script will start to "support" random new distros that we've never tested and which aren't supported. In those cases, you would most likely just get some sort of download error.

@livarcocc

**Comment by livarcocc** [comment]
Will keep it as is.
