### ISSUE TITLE
"dotnet test" crashes if another process or thread has a name with a space

### ISSUE THREAD

**Issue by stephentoub** [dotnet/cli#4452]
See https://github.com/dotnet/corefx/issues/12755

Essentially, "dotnet test" calls Process.GetProcesses():

```
   at System.Diagnostics.Process.GetProcesses()
   at Microsoft.DotNet.Tools.Test.TestCommand.RegisterForParentProcessExit(Int32 id)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```

and GetProcesses has a bug where it throws an InvalidDataException if one of the processes (or one of the threads in one of the processes) has a name that includes a space.

The GetProcesses bug is being fixed, but I suggest that RegisterForParentProcessExit be changed in the interim to catch the exception and treat it as if the parent process could not be found, rather than crashing.

**Comment by piotrpMSFT** [comment]
System.Diagnostics.Process.GetProcesses() is no longer invoked from dotnet-test
