### ISSUE TITLE
dotnet migrate puts generic project references under TFM conditions

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/cli#4457]
## Steps to reproduce

1. Create two project.json projects, one referencing the other. Put the reference under the generic `"dependencies"` section, not under the `"frameworks"` node.
1. Target two or more frameworks in the projects.
1. `dotnet migrate`
1. Inspect the output .csproj that has the project references.

Repro project: [duplicateprojref.zip](https://github.com/dotnet/cli/files/542187/duplicateprojref.zip)

## Expected  behavior

The `<ProjectReference>` element should not be under a framework condition and should only appear once in the .csproj.

## Actual behavior

The `<ProjectReference>` is duplicated under each framework condition.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003886)

Product Information:
 Version:            1.0.0-preview3-003886
 Commit SHA-1 hash:  4b0c2f5ebe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
We are tracking this in here already: https://github.com/dotnet/cli/issues/4330.
