### ISSUE TITLE
Add an option to include VC++ runtime for --native

### ISSUE THREAD

**Issue by xanather** [dotnet/cli#446]
On windows you're required to install the VC++ 2014 runtime to get the native executable working, there should be an option/parameter to include the runtime statically.

**Comment by piotrpMSFT** [comment]
@schellap, can you take a look at this? --native output should have no external dependencies...

**Comment by gkhanna79** [comment]
We are planning to call out VC++ 2015 REDIST as a pre-req and will install this by default as part of the Shared FX installer. Hence, there is no action required.
