### ISSUE TITLE
Branding needs to be updated for .NET Core 1.0.1 - Preview 3 CLI 

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#4464]
## Steps to reproduce
1. Install Dev15 build d15prerel.25820.03
This includes version 1.0.0-preview3-003788 of the CLI

## Actual behavior
Following entries show up in ARP

![image](https://cloud.githubusercontent.com/assets/8246794/19580291/2aab8f14-96da-11e6-8552-b1fe91772e90.png)

## Expected  behavior
- Branding is incorrect for the ARP entry

    1. The ARP entry should say Preview 3 instead of Preview 2
    2. The format should be similar to what we shipped for .NET Core 1.0.1
![image](https://cloud.githubusercontent.com/assets/8246794/19580583/17d70100-96dc-11e6-85ad-7d74c4492b66.png)

- Also, I assume we want to continue showing the entries in ARP even though it is getting installed as part of the Dev15 install. Correct?

**Comment by dasMulli** [comment]
See #4296

**Comment by livarcocc** [comment]
Yep. Duplicate.
