### ISSUE TITLE
After installing Dev15 (.NET Core workload) on Windows 10 x64 machine, both x86 and x64 versions of the CLI get installed

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#4465]
## Steps to reproduce
1. Clean machine with Windows 10 x64 ENU
2. Install Dev15 build d15prerel.25820.03 (.NET Core workload). This includes version 1.0.0-preview3-003788 of the CLI

## Actual behavior
Both x86 and x64 versions of the CLI get installed.
![image](https://cloud.githubusercontent.com/assets/8246794/19580662/93790754-96dc-11e6-82ec-ce536c7427be.png)

## Expected  behavior
Is the above expected? With Dev14, we used to install only x64 version of the CLI on a Windows 10 x64 machine. Shouldn't this behave the same for Dev15 as well?

**Comment by livarcocc** [comment]
it was a by-design decision to avoid problems with having different versions in the two paths if VS only installs one, and the other comes from a direct install.  It makes launching dotnet.exe a somewhat random situation as to which one you’ll get.
