### ISSUE TITLE
Preview1 installer creates sdk with version 1.0.0-preview2.1-003155 which VS is unable to find when loading a solution

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#4466]
## Steps to reproduce
- Install the .NET Preview1 SDK using installer. You should notice a folder with name `1.0.0-preview2.1-003155` under the `sdk` folder.
- Make sure to modify your PATH environment variable so that the above installed location comes earlier any other sdk installed locations.
- Create a .net core console app (you might have the Preview2 VS tools which has earlier dotnet sdk versions and so there would be an error dialog showing up temporarily and disappear...ignore it and VS would proceed to create the project but would not be able to restore the packages).
- Now delete the `sdk` node in `global.json`, save and close the VS solution.
- Try reopening the console app in VS and you should see an error dialog like below

![image](https://cloud.githubusercontent.com/assets/6559784/19581318/f0d81f30-96e0-11e6-898e-85de0810c2a7.png)

## Expected  behavior
If not `sdk` node is present in `global.json` file, the latest sdk should be chosen by VS.

## Actual behavior
Error dialog `.NET Core SDK Not Found`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003155)

Product Information:
 Version:            1.0.0-preview2-1-003155
 Commit SHA-1 hash:  d7b0190bd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

## Workarounds
- Try renaming the sdk folder from `1.0.0-preview2.1-003155` to `1.0.0-preview2-003155` (notice that `.1` was removed) and open up the console app and it would open up fine.
- Explicitly specifying `1.0.0-preview2.1-003155` in global.json seems to work for some projects but not others. I couldn't isolate the problem.

## VS Info
![image](https://cloud.githubusercontent.com/assets/6559784/19581772/7028e6ea-96e4-11e6-9068-a1072e27f8c8.png)

@Eilon

**Comment by livarcocc** [comment]
Just an update here. This only happens if a preview2.1 is the only CLI available in the PATH. So, if you have a preview2 installed in SxS with preview2.1, VS will continue to work.

The issue here is VS not recognizing the preview2.1 as a valid CLI.
