### ISSUE TITLE
Preview 2-003148 on macOS - dotnet run/restore look for project.json, no longer created by dotnet new

### ISSUE THREAD

**Issue by incredibleweirdo** [dotnet/cli#4467]
## Steps to reproduce
Install latest preview on macOS. Create a directory and run 'dotnet new' in the terminal. Program.cs and xxx.csproj are created (where xxx is the directory name). 
Run 'dotnet run' or 'dotnet restore' and receive error message that project.json is missing.

## Expected  behavior
Either a) dotnet new still creates project.json, or b) dotnet run/restore utilize .csproj file.

## Actual behavior
Commands fail due to missing file.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003857)

Product Information:
 Version:            1.0.0-preview3-003857
 Commit SHA-1 hash:  060762090d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by incredibleweirdo** [comment]
Would like to add that after seeing the cli project has a link to a yet newer SDK installer (most recent link from microsoft.com/net/core and github.com/dotnet/core is one noted above), I installed that version and have the very same result. 

.NET Command Line Tools (1.0.0-preview3-003892)

Product Information:
 Version:            1.0.0-preview3-003892
 Commit SHA-1 hash:  5301f08423

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by dasMulli** [comment]
1.) you seem to have a preview3 version installed as well as the preview2 you got if you followed the new announcement links.

2.) "b" is happening (#4456)
In the meantime, you can use `restore3`, `build3`, `run3` etc. if you work with CI / nightly builds.
Note that the installer for preview3 versions still has "Preview 2" in its name (known issue).

**Comment by livarcocc** [comment]
Correct. You picked up the latest preview3, which is our nightly and has our ongoing changes to support msbuild. So, dotnet new has been switched to produce msbuild artifacts. However, we are in the process of changing the verbs. In order to work with the artifacts produced by it, you need to use restore3, build3, run3 and publish3.

If you want to pick up the latest preview2 build, which still has project.json, you can get it from https://www.microsoft.com/net/core.
