### ISSUE TITLE
Migrate does not respect "target": "package" for dependencies

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4470]
## Steps to reproduce
- Create 2 projects in the same src folder (aka they can reference each other as project references if they wanted to): `Project1`, `Project2`
- Have `Project1` depend on `Project2` but only as a package
```JSON
"Project2": {
  "version": "1.0.0",
  "target": "package"
}
```
- dotnet migrate

## Expected  behavior
- `Project1`'s csproj has a package reference to `Project2`:
```XML
<PackageReference Include="Project2">
  <Version>1.0.0</Version>
</PackageReference>
```

## Actual behavior
- `Project1`'s csproj has a project reference to `Project2`:
```XML
<ProjectReference Include="..\Project2\Project2.csproj" />
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003886)

Product Information:
 Version:            1.0.0-preview3-003886
 Commit SHA-1 hash:  4b0c2f5ebe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
@emgarten I think NuGet will resolve this to a project even if you say package. Justin, is correct? My statement?

**Comment by emgarten** [comment]
@livarcocc no, restore will ignore projects if ``target: package`` is set.

I would expect migrate to use the target to determine the reference type if it is set. If not set it will need to determine which type nuget would have resolved it to.

**Comment by livarcocc** [comment]
I see. Ok, We can figure it out in the Migration tool.
