### ISSUE TITLE
ProjectDependencyCommandResolver cannot resolve commands on desktop targeting csproj projects.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4471]
Trying to resolve a dependency declared by a desktop targeting csproj does not currently work.

You get: `No executable found matching command "ToolName"`

/cc @livarcocc @muratg @pranavkm @prafullbhosale

**Comment by NTaylorMullen** [comment]
Here's a repro: 
[PDCR_Repo.zip](https://github.com/dotnet/cli/files/545413/PDCR_Repo.zip)

Cd into the MSBuildSandbox folder and run `test.ps1`

**Comment by muratg** [comment]
Our tools which require an "inside man" won't work for the projects with the following conditions:

- Only target desktop
- Target multiple frameworks but desktop is listed first

So this is a blocker for msbuild based tools work on are end.

**Comment by livarcocc** [comment]
@muratg I know, I am working on it. I am aware of its importance and I agree with it.
