### ISSUE TITLE
How to uninstall dnvm?

### ISSUE THREAD

**Issue by z2xlong** [dotnet/cli#4475]
I've been installed the .net core 1.0.1 on my macOS Sierra, now should I uninstall the dnvm? I think it might be useless anymore. If should, or if can, how to do this? I have forgotten the detailed installation steps, but certainly not via homebrew, so the command 'brew uninstall dnvm' doesn't work. 

Looking forward to your advice, thanks.

**Comment by blackdwarf** [comment]
@z2xlong simply find where you installed DNVM and delete it. DNVM is a shell script.
