### ISSUE TITLE
Unable to resolve 'Microsoft.xunit.netcore.extensions' from external nuget feeds

### ISSUE THREAD

**Issue by parjong** [dotnet/cli#4476]
## Steps to reproduce
1.  Create a csproj file as follows:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard1.7</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.xunit.netcore.extensions">
      <Version>1.0.0-prerelease-00830-02</Version>
    </PackageReference>
    <PackageReference Include="NETStandard.Library"/>
    <PackageReference Include="System.IO.IsolatedStorage"/>
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```
1. Run 'dotnet restore3' as follows:

```
$ dotnet restore3 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
```
## Expected  behavior

All the package is restored.
## Actual behavior

```
$ dotnet restore3 --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
...
"/home/parjong/projects/dotnet/corefx-analyze/System.IO.IsolatedStorage.Tests/System.IO.IsolatedStorage.Tests.csproj" (Restore target) (1) ->
(Restore target) ->
  /home/parjong/projects/dotnet/cli/artifacts/ubuntu.14.04-x64/stage2/sdk/1.0.0-preview3-003904/NuGet.targets(70,5): error : Unable to resolve 'Microsoft.xunit.netcore.extensions (>= 1.0.0-prerelease-00830-02)' for '.NETStandard,Version=v1.7'. [/home/parjong/projects/dotnet/corefx-analyze/System.IO.IsolatedStorage.Tests/System.IO.IsolatedStorage.Tests.csproj]

    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.64
$
```
## Environment data

```
$ dotnet --info
.NET Command Line Tools (1.0.0-preview3-003904)

Product Information:
 Version:            1.0.0-preview3-003904
 Commit SHA-1 hash:  cde0e8e7e8

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by eerhardt** [comment]
@piotrpMSFT @livarcocc - what myget feed is this package hosted on?

**Comment by piotrpMSFT** [comment]
It looks like this one comes from build-tools:
https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.xunit.netcore.extensions/1.0.1-prerelease-00928-02

@dagood may have some suggestions about acquiring this one.

**Comment by dagood** [comment]
The natural way is to add https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json as a package source. There is one version of this package on the dotnet-core feed, but not `1.0.0-prerelease-00830-02`: https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.xunit.netcore.extensions/1.0.0-prerelease-00704-04

In the future, you can check out the galleries to browse the packages each feed has:
https://dotnet.myget.org/gallery/dotnet-core
https://dotnet.myget.org/gallery/dotnet-buildtools

**Comment by blackdwarf** [comment]
@parjong please try out @dagood 's solution described above and let us know if this solves the issue.

**Comment by parjong** [comment]
@blackdwarf ``dotnet restore3 --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json`` works well. Thank you!
