### ISSUE TITLE
Including native libraries in dotnet projects without nuget package

### ISSUE THREAD

**Issue by nicolasr75** [dotnet/cli#4481]
According to the current documentation the packOptions would allow us to specify a native library for inclusion in a nuget package. Wouldn't it be great if we could have something similar for a normal app publish? That would allow us to bypass the creation of a nuget package for simple scenarios.

For example:

```
"packOptions":{
    "files":{
        "mappings":{
            "runtimes/win10-x64/native":{
                "includeFiles":[ "native-lib.dll"]
            }
        }            
    }
}
```

From my tests it looks like packOptions is not considered by _dotnet publish_.

https://docs.microsoft.com/de-de/dotnet/articles/core/tutorials/libraries

**Comment by blackdwarf** [comment]
MSBuild allows this very easily using the `<Content>` element. Is this what is looked for here?

**Comment by tmds** [comment]
> From my tests it looks like packOptions is not considered by dotnet publish.

@nicolasr75 try using `publishOptions` (see https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json)

**Comment by nicolasr75** [comment]
@tmds thanks, indeed it seems to be as easy as

	"publishOptions": {
	    "include": [
			"My.dll"
		]
	}

I somehow thought I'd have to create all the runtime directories dynamically and copy the DLL to all of them. In my case the DLL is the same for all runtimes and it works by simply copying it to the publish base directory.

**Comment by nicolasr75** [comment]
@blackdwarf yes, I guess <Content> may work. I will try it as soon as I port the project to VS2017.

**Comment by blackdwarf** [comment]
@nicolasr75 I will assume that this worked since MSbuild's `<Content>` is tried and true so will therefore close this issue. :) If you run into problems or it doesn't work, please reopen.
