### ISSUE TITLE
F# support for msbuild based projects and preview3

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4484]
Just a note for discussion/info or if someone like the sdk and f# and want to contribute.

F# support it's in progress at https://github.com/dotnet/netcorecli-fsc/issues/19
Examples: https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3

Current status:
- restore3/build3/run3/pack3 are supported for netstandard/netcoreapp/net451 and multi framework (crossgen), types: console and lib.
- the msbuild targets/props are auto-imported on restore from nuget packge `FSharp.NET.Sdk`
- the `CoreCompile` target now temporary invoke the `dotnet-compile-fsc` (as tool, like preview2) instead of the `Fsc` msbuild task (bonus point: because use same dotnet-compile-fsc flow, the VS Code intellisense works with Ionide already). Next iteration the msbuild tasks assembly is going inside the package.

**Comment by piotrpMSFT** [comment]
@enricosada this is great! @KevinRansom FYI

How soon will you be ready with a project template that can be added to `dotnet-new`?

@blackdwarf @livarcocc @jgoshi FYI as well

**Comment by enricosada** [comment]
First i want to replace `dotnet-compile-fsc` with the `Fsc` msbuild task (assembly inside the package) so is more like final version.
Two/three days i think, plus review and ok from visualfharp team (adding @cartermp too).

I have two issues about authoring of the targets, but i'll open another issue and ref this one.

@piotrpMSFT  about `dotnet new`, there was a discussion about adding extensibility (templates from packages). Want help from community about that? There is already the requirements and design, so is just a matter of `up-for-grab`, and a nice one.
It's really important for F# ihmo ( /cc @dsyme ), because last time we got issues with templates and was really hard (impossible?) to update and we needed to wait another release. Also the f# libraries are slowly adding `netstandard` support now, so it's really nice if we can update templates easy and later (adding standard xunit/aspnet/etc but also f# most used libraries like suave). `dotnet new` is a really awesome entry point.

**Comment by ErikSchierboom** [comment]
Totally awesome functionality!

**Comment by piotrpMSFT** [comment]
@enricosada I know that @mlorbetske has started on implementation of `dotnet new` replacement and may be looking for help. I expect that that one is a few weeks away, though, so would love to get a low-cost F# template into the old system and let folks take this work out for a spin!

**Comment by enricosada** [comment]
Nice @piotrpMSFT i'll ask @mlorbetske if need help (because it's really important for f# to have remote templates). And send a pr for old `dotnet-new` templates meanwhile.

As a note, we are starting a group to focus on contributing to the F# and .net core/sdk story ( ref http://fsharp.github.io/2016/10/31/dotnetcore_sdk_group.html ) and improve full ux (from docs to ide).

Because with `preview2` was working, but with `preview3` can be awesome!

**Comment by piotrpMSFT** [comment]
glad to hear, @enricosada! 

/cc @srivatsn @nguerrera @KevinRansom regarding contributions to the sdk.

**Comment by piotrpMSFT** [comment]
@enricosada thanks for the heads up. Since there is no work here and the conversation wound down, I'm going to close the issue. We can reopen if you think we need to do something here.
