### ISSUE TITLE
dotnet migrate does not migrate outputName

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4487]
`dotnet migrate TestAssets/TestProjects/LibraryWithOutputName`

# Expected
the `outputName` property is transferred to the csproj file

# Actual
It is not

**Comment by livarcocc** [comment]
@piotrpMSFT So, what did we decide here? We are going to add the PackageId set to the current folder name to the csproj if the OutputName is different than the current folder name? Please confirm and I will add it.

**Comment by livarcocc** [comment]
I think maybe the right fix is the one described in #4506

**Comment by livarcocc** [comment]
Closing this in favor of  #4506.
