### ISSUE TITLE
dotnet publish does not create .deps.json & .runtimeconfig.json if emitEntryPoint is false

### ISSUE THREAD

**Issue by gokarnm** [dotnet/cli#4495]
## Steps to reproduce

I created a project that uses Microsoft.NETCore.App as a "platform", but the application doesn't have an entry point. In this case, the _dotnet publish_ command does not produce the _{appname}.deps.json_ and _{appname}.runtimeconfig.json_ file in the /publish directory. It does produce these files in the build directory (e.g. bin\Release\netcoreapp1.0) but not in the publish directory (bin\Release\netcoreapp1.0\publish).

I'm implementing a host application that can load plugins. A plugin project need not have an entry point. I think the _.deps.json_ and _.runtimeconfig.json_ should be published in this scenario.

 If the plugin has dependencies which has platform specific implementations, they are published in /publish/runtimes/{RID} folders. The _.deps.json_ file contains metadata about these dependencies that is used by [corehost ](https://github.com/dotnet/cli/blob/3a567e595773b61650f2dcd1c7ec2b53b91cd7a8/Documentation/specs/corehost.md) to build TPA list and resolve dependencies.
 In my case, the host application uses a custom Assembly Load Context to load the plugin and it's dependencies. I'm planning to use the _.deps.json_ file to resolve platform specific dependencies under /publish/runtime folder. I also plan to use the plugins _.runtimeconfig.json_ to set runtime switches.
## Expected  behavior

{appname}.deps.json and {appname}.runtimeconfig.json files published to the /publish folder 
## Actual behavior

{appname}.deps.json and {appname}.runtimeconfig.json file are not published to /publish folder
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by livarcocc** [comment]
cc @eerhardt can you take a look?

**Comment by eerhardt** [comment]
My understanding is that you can't publish a library.  Is that not true?

When I try publishing a project targeting `netstandard1.6`, I get the following error:

```
Can not find runtime target for framework '.NETStandard,Version=v1.6' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.
```

**Comment by gokarnm** [comment]
Thanks for the quick reply! I'm using Microsoft.NETCore.App as a "platform", here is the project.json.

    {
      "version": "1.0.0-*",
      "buildOptions": {
        "emitEntryPoint": false
      },

      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        }
      },

      "frameworks": {
        "netcoreapp1.0": {
          "imports": "dnxcore50"
        }
      }
    }

**Comment by eerhardt** [comment]
Thinking more about your scenario - using the .deps.json file makes sense.  However, I don't think the runtimeconfig.json makes sense for plugins.

The runtimeconfig has configuration settings for which .NET runtime gets loaded.  For example: which version of the Shared Framework (Microsoft.NETCore.App) gets loaded - which CoreCLR.  If plugin #1 says it wants v1.0.0 and plugin #2 says it wants v1.0.1, you are going to have a problem.  Or one plugin setting `System.GC.Concurrent` to true, and another setting it to false.  There really can only be 1 "runtimeconfig" file for a .NET Core application.  (Or is your idea to write a native host that loads multiple CoreCLRs into a single process?)

**Comment by gokarnm** [comment]
Yes, I'm using a native host that loads one or more CoreCLR which then loads a plugin. I would like the plugin to be able to optionally provide a runtimeconfig file mainly to have control over the [host configuration settings](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md). I think there are scenarios where a plugin would want to specify GC settings or min/max threads.
I haven't decided how to handle the Shared Framework version in the runtimeconfig, I could restrict plugins to target a specific framework version, but it seems like it should be possible to start up the version of the CoreCLR specified by the plugin. A plugin could specify the framework version it was built against, and a host can decide how to handle it. So overall I think `dotnet publish` should create the deps.json and the optional runtimeconfig.json irrespective of the `emitEntryPoint` flag. Let me know your thoughts.

**Comment by eerhardt** [comment]
Well the good news is that the current project.json code is all getting removed in favor of MSBuild.  And when using MSBuild you will have the power to set properties in your MSBuild project to force deps.json and runtimeconfig.json generation no matter if `emitEntryPoint` is set or not.

See 
https://github.com/dotnet/sdk/blob/4a6781a0164330b8c4077f8ed1b8b32efe9dd907/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L46
https://github.com/dotnet/sdk/blob/721f161e4477c777e447e1ba3de4ce449916f0b1/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L38

The bad news is the MSBuild work isn't ready yet.  Stay tuned.

**Comment by blackdwarf** [comment]
Well, based on the snippet that @eerhardt shared above and what I just managed to repro, this issue is mitigated with move to msbuild since the deps file will always be generated. The same situation is for the runtime config files. 

Here is the csproj file I used:

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">    
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
                                                                                             
  <PropertyGroup>                                                                            
      <TargetFramework>netcoreapp1.0</TargetFramework>                                       
      <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>            
  </PropertyGroup>                                                                           
                                                                                             
  <ItemGroup>                                                                                
    <Compile Include="**\*.cs" />                                                            
    <EmbeddedResource Include="**\*.resx" />                                                 
  </ItemGroup>                                                                               
                                                                                             
  <ItemGroup>                                                                                
    <PackageReference Include="Microsoft.NETCore.App">                                       
      <Version>1.0.1</Version>                                                               
    </PackageReference>                                                                      
    <PackageReference Include="Microsoft.NET.Sdk">                                           
      <Version>1.0.0-alpha-20161026-2</Version>                                              
      <PrivateAssets>All</PrivateAssets>                                                     
    </PackageReference>                                                                      
  </ItemGroup>                                                                               
                                                                                             
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />                          
</Project>                                                                                   
```

Running just `dotnet publish` with the latest rel/1.0.0 gives me this in the default publish location:

```powershell
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        11/1/2016   4:05 PM            843 new.deps.json
-a----        11/1/2016   4:05 PM           4096 new.dll
-a----        11/1/2016   4:05 PM            404 new.pdb
-a----        11/1/2016   4:05 PM            125 new.runtimeconfig.json
```

One thing to note is that the deps file will be generated **always** unless the user overrides that in the csproj file or on invocation. The runtime files are different, and in this particular situation, I had to manually specify that I wanted them generated via the property in the csproj.

With this, I will close this issue as msbuild mitigated. @gokarnm if this doesn't work for you, please reopen. Thanks!

**Comment by gokarnm** [comment]
Thanks @blackdwarf !
