### ISSUE TITLE
geocoder.GetDescriptionForNumber throws The given key was not present in the dictionary for Curaçao number 

### ISSUE THREAD

**Issue by vaibhavshrivastava** [dotnet/cli#4498]
## Steps to reproduce
Input :
Phone number (+59995221133)   (This number is from Curaçao (region CW) )
Default Country: US 
I am using C# version of this library
number= PhoneNumberUtil.GetInstance().Parse(item.Value, countryCode);
geocoder.GetDescriptionForNumber(number, Locale.ENGLISH)

## Actual behavior
The given key was not present in the dictionary
## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
Please open this in the dotnet/corefx framework. Though, is this for .net core or for full framework?

**Comment by vaibhavshrivastava** [comment]
I am getting this error on .Net full framework.
