### ISSUE TITLE
dotnet publish broken with powershell LanguageMode=ConstrainedLanguage

### ISSUE THREAD

**Issue by ilanc** [dotnet/cli#4500]
## Steps to reproduce

File > New Project > .NET Core app
Create publish profile (e.g. custom, filesystem publish)
Publish
## Expected  behavior

Publish succeeds
## Actual behavior

Build succeeds, but the InvokePowershell part fails - see the Test-publish.ps1 failure part below. If you manually run the powershell part you get a different error which explains that System.IO.FileInfo is not supported in this language type (see next error block)

Now of course there is no way to change the powershell language mode in powershell 5. So the solution is to downgrade to powershell 4. I'm just looking into how to do that now.

At a wider level - wtf is with powershell? It seems like every couple months they invent some new cryptic way to irrevocably F-up the language. Please consider something else for your publish process.
### Visual Studio publish output error

```
1>------ Build started: Project: WebApplication1, Configuration: Release Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\dev\temp\core\2\WebApplication1" --configuration Release --no-dependencies
1>  Project WebApplication1 (.NETFramework,Version=v4.5.2) will be compiled because inputs were modified
1>  Compiling WebApplication1 for .NETFramework,Version=v4.5.2
1>  Compilation succeeded.
1>      0 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:00:01.3064375
1>
2>------ Publish started: Project: WebApplication1, Configuration: Release Any CPU ------
Connecting to c:\deploy\test...
rmdir /S /Q "C:\Users\icopelyn\AppData\Local\Temp\PublishTemp\WebApplication156\"
Environment variables:
Path=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe publish "C:\dev\temp\core\2\WebApplication1" --framework net452 --output "C:\Users\icopelyn\AppData\Local\Temp\PublishTemp\WebApplication156" --configuration Release --no-build
Publishing WebApplication1 for .NETFramework,Version=v4.5.2/win7-x64
Bundling with configuration from C:\dev\temp\core\2\WebApplication1\bundleconfig.json
Processing wwwroot/css/site.min.css
  Bundled
  Minified
Processing wwwroot/js/site.min.js
  Bundled
Configuring the following project for use with IIS: 'C:\Users\icopelyn\AppData\Local\Temp\PublishTemp\WebApplication156'
Updating web.config at 'C:\Users\icopelyn\AppData\Local\Temp\PublishTemp\WebApplication156\web.config'
Configuring project completed successfully
publish: Published to C:\Users\icopelyn\AppData\Local\Temp\PublishTemp\WebApplication156
Published 1/1 projects successfully
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(408,5): Error MSB4018: The "InvokePowerShell" task failed unexpectedly.
System.Management.Automation.CommandNotFoundException: The term 'C:\dev\temp\core\2\WebApplication1\Properties\PublishProfiles\Test-publish.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Microsoft.Web.Publishing.Tasks.InvokePowerShell.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Publish failed due to build errors. Check the error list for more details.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```
### Manual powershell error

```
C:\dev\temp\core\2\WebApplication1>powershell -noprofile -Command "cd C:\dev\tem
p\core\2\WebApplication1; .\Properties\PublishProfiles\Test-publish.ps1 -packOut
put C:\Users\icopelyn\AppData\Local\Temp\PublishTemp\WebApplication156 -pubProfi
lePath Properties\PublishProfiles\Test.pubxml"
C:\dev\temp\core\2\WebApplication1\Properties\PublishProfiles\Test-publish.ps1
: An error occurred during publish.
Cannot process argument transformation on parameter 'packOutput'. Cannot
convert value to type "System.IO.FileInfo". Only core types are supported in
this language mode.
At line:1 char:40
+ ... plication1; .\Properties\PublishProfiles\Test-publish.ps1 -packOutput ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,Test-publish.ps1

```
### Powershell language mode

```
PS C:\Users\icopelyn> $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by piotrpMSFT** [comment]
@mlorbetske @morrisjoe can we get this routed to the right folks?

**Comment by sayedihashimi** [comment]
@ilanc sorry to hear that you are running into this. Just FYI we are moving the VS publish infrastructure from PowerShell to MSBuild so this shouldn't be an issue in the next release.
I don't have a workaround for you at this time, but if this is blocking and you cannot wait for the next release then let me know and I'll see if I can unblock you. To workaround this I believe we can modify the publish .psm1 file and replace `System.IO.FileInfo` with `string` types.

**Comment by ilanc** [comment]
Thanks @sayedihashimi I've managed to get powershell unrestricted in the interim. That's excellent news about moving away from powershell in the build/publish process.

**Comment by sayedihashimi** [comment]
@ilanc ok great, I'm glad you were able to workaround it and that you're happy with our decision to go to MSBuild.

**Comment by lucho1981** [comment]
Hello ilanc and sayedihashimi, I am having the exact same problem so I have a question for both of you

Ilanc: could you share the PowerShell command to set it to unrestricted?

sayedihashimi: Could post or email me the fix to Visual Studio so that it stops utilizing PowerShell and utilizes MSBuild istead?

**Comment by sayedihashimi** [comment]
When you install the latest version of Visual Studio 2017 you'll get the MSBuild experience.

**Comment by sayedihashimi** [comment]
Set-ExecutionPolicy Unrestricted

**Comment by ilanc** [comment]
Powershell has many ways to disable itself. The `Set-ExecutionPolicy` trick applies to a different type of restriction. The problem I encountered was with `ConstrainedLanguage` mode. Turning this off is something that you unfortunately can't do in powershell - you need to change it using [SRP](https://technet.microsoft.com/en-us/library/hh994606(v=ws.11).aspx). If you're on a corporate network then chances are Active Directory domain admins will need to change the SRP for you. Go for VS 2017.
