### ISSUE TITLE
CLI verbs that call into msbuild should control their output

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4508]
## Steps to reproduce

Download latest CLI form rel/1.0.0 and then: 

``` bash
mkdir hw && cd hw
dotnet new
dotnet publish3
```
## Expected  behavior

See `Publish succeeded` in the output. 
## Actual behavior

See the following (end of the output log):

``` bash
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\netcoreapp1.0\new.dll" to "bin\Debug\netcoreapp1.0\new.dll".
  new -> D:\Experiments\new\bin\Debug\netcoreapp1.0\new.dll
  Copying file from "obj\Debug\netcoreapp1.0\new.pdb" to "bin\Debug\netcoreapp1.0\new.pdb".
PrepareForPublish:
  Creating directory "bin\Debug\netcoreapp1.0\publish\".
_CopyResolvedFilesToPublishPreserveNewest:
Skipping target "_CopyResolvedFilesToPublishPreserveNewest" because it has no outputs.
_CopyResolvedFilesToPublishAlways:
  Copying file from "obj\Debug\netcoreapp1.0\new.dll" to "bin\Debug\netcoreapp1.0\publish\new.dll".
  Copying file from "obj\Debug\netcoreapp1.0\new.pdb" to "bin\Debug\netcoreapp1.0\publish\new.pdb".
Done Building Project "D:\Experiments\new\new.csproj" (Publish target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)
```
## Commands that are impacted
- `dotnet publish3`
- `dotnet restore3`
- `dotnet pack3`

**Comment by wjk** [comment]
Personally, I like seeing all the output, even the ridiculously-long `csc.exe` command lines, as they help me get and keep a finger on the state and progress of the build. Without this output, I would not have found and fixed several bugs in the build of one of my projects that were preventing incremental rebuild. As long as there is a flag that allows me to view the full output, I am happy.

**Comment by piotrpMSFT** [comment]
I think we should minimize the default output and in failure cases add a note that says "Rerun with /v:diag for more info"

**Comment by krwq** [comment]
Fixed by https://github.com/dotnet/cli/pull/4719
