### ISSUE TITLE
Add a way to list runtimes installed in a default location from the CLI

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4509]
Add a switch to be able to list all of the runtimes that are installed in the default location.

The "default location" here means next to the muxer that is on the $PATH, that is, that is used to invoke the command.

**Comment by piotrpMSFT** [comment]
@blackdwarf the runtimes are not managed by the CLI. Please move this to the core-setup issue to be fixed in the host. Folks shouldn't need to install CLI just to see what state their Shared Frameworks are in.
