### ISSUE TITLE
Search paths DOTNET_HOME in host

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#451]
We need to add two more default paths to the host:
1. zip/layout
If running dotnet from build artifacts or from zip, the DOTNET_HOME directory for tools in the CLI will be in `..\runtime...`This is a very common scenario so the path should be considered.
2. When a deps file is present it should include a pointer to the runtime [does today if runtime package is referenced]. Host should take this into account when looking for Runtime.

**Comment by blackdwarf** [comment]
@anurse is this part of the corehost spec?

**Comment by anurse** [comment]
Not currently. I'm not a huge fan of it as-is. My concern is that it assumes a lot about the layout of files or adds path information to the deps file, which are both things I'm not a big fan of :).

The tools in `DOTNET_HOME\bin` already have an embedded runtime, so they don't need to use `..\runtime\coreclr` to find it. Also, `dotnet run` ensures `DOTNET_HOME` is set properly before launching the app (there was a bug in that, but it should be fixed now). Finally, there will be OS-specific defaults for the installed version of the runtime. These should mean that only us devs or people doing more complicated things will need to set `DOTNET_HOME`, and I think we can handle it :)

**Comment by anurse** [comment]
`DOTNET_HOME` is going away (/cc @schellap @davidfowl) so this is irrelevant
