### ISSUE TITLE
Version of Microsoft.NET.Sdk.Web package used by "dotnet new -t web" does not match the version in offline package installer

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#4511]
INSTALL STEPS
1. Run preinstall.cmd
2. Install Dev15 RC build d15rel.25827.01 (.NET Core workload)

REPRO STEPS
1. Run "dotnet new -t web" from command-line

ACTUAL
Version of Microsoft.NET.Sdk.Web package used by "dotnet new -t web" does not match the version in offline package installer. Version used by "dotnet new" is 1.0.0-alpha-20161019-1 but the one from offline package installer is 1.0.0-alpha-20161027-2-88

![image](https://cloud.githubusercontent.com/assets/8246794/19783405/af6a7f28-9c46-11e6-8bbf-344f8ac7413f.png)

I'd expect the versions to be in-sync. Since they are not, you get this warning as a result:

![image](https://cloud.githubusercontent.com/assets/8246794/19783505/104da400-9c47-11e6-8677-3c1858d83cf9.png)

**Comment by livarcocc** [comment]
Templates in the CLI need to match the offline packages in the CLI installer. We will need to synchronize CLI and VS before shipping. This is a point-in-time thing as products lock down.
