### ISSUE TITLE
After doing "dotnet new -t web", cannot able to load page in the browser after doing "dotnet run3" 

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#4512]
INSTALL STEPS
1. Run preinstall.cmd
2. Install Dev15 RC build d15rel.25827.01 (.NET Core workload)

REPRO STEPS
1. Run "dotnet new -t web" from command-line
2. Run "dotnet restore3" and "dotnet build3" : both succeed
3. Run "dotnet run3"

ACTUAL
Unable to load page using the browser

![image](https://cloud.githubusercontent.com/assets/8246794/19784315/35712966-9c4a-11e6-8b33-14fdeb94fc57.png)

**Comment by natemcmaster** [comment]
I'm guessing this is related to https://github.com/dotnet/cli/issues/4473. It looks like content root is "bin/debug/netcoreapp1.0" instead of the project directory. This means it won't find the razor views files.

**Comment by livarcocc** [comment]
Which version of the CLI is this? you didn't say in the bug.

This has been fixed in the SDK already. Though, I am not sure we have done an insertion with it yet.

**Comment by piotrpMSFT** [comment]
@balachir Please reopen if latest CLI still repros this issue.
