### ISSUE TITLE
Re-enable binding redirect tests

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4514]

**Comment by krwq** [comment]
This is blocked on sdk bugs

**Comment by livarcocc** [comment]
Links to those bugs?

**Comment by krwq** [comment]
https://github.com/dotnet/sdk/issues/384

**Comment by prafullbhosale** [comment]
@krwq, @livarcocc  is this issue targeted for the RC.2 for VS?

**Comment by prafullbhosale** [comment]
cc @vkichline @mlorbetske

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/issues/4432 was related.

**Comment by piotrpMSFT** [comment]
@krwq, I discussed this with @mlorbetske and @nguerrera and we think this is what needs to happen:
- Force `dotnet build` to generate an app.config for the target project using a property. @nguerrera can provide the right property.
- Extract Binding Redirects from the generated config file
- If the tool did not carry an app.config, create one
- In the app.config [created or carried by the tool] add the extracted binding redirects to the bottom of the file

**Comment by piotrpMSFT** [comment]
Chatted with @prafullbhosale. He had already implemented exactly the same fix in the scaffolding tool. Since the scaffolding tool is the only intended use case for this behavior, closing this PR to prevent destabilization of the scenario.

@mlorbetske FYI.
