### ISSUE TITLE
dotnet-publish does not identify the default current runtime identifier 'centos.7-x64' on centos 7

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#452]
Currently the default runtime identifier on centos is 'ubuntu.14.04-x64'.

**Comment by Sridhar-MS** [comment]
https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.ProjectModel/RuntimeIdentifier.cs

**Comment by piotrpMSFT** [comment]
The RIDs are currently defined by https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

**Comment by brthor** [comment]
Fixed #722
