### ISSUE TITLE
dotnet-compile-native does not work on centos

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#453]
There is no corert packages for centos 7 yet.

/cc: @schellap @brthor

**Comment by gkhanna79** [comment]
@Sridhar-MS @piotrpMSFT I dont see CentOs at https://github.com/dotnet/cli. Is CentOs support for CLI targeted for RC2?

**Comment by Sridhar-MS** [comment]
@gkhanna79 CentOS builds are currently enabled and we are targeting for beta(still working through some bugs). We have pushed native compilation on CentOS to RC2.

**Comment by gkhanna79** [comment]
We are not targeting CoreRT for CentOS yet. It will likely be a post-RTM effort.

**Comment by piotrpMSFT** [comment]
Closing this issue. CLI enables compile-native wherever it's available.
