### ISSUE TITLE
Display checksums for installation artifacts in README

### ISSUE THREAD

**Issue by naamunds** [dotnet/cli#4532]
The checksums for the CLI installation artifacts should be displayed in the README, probably next to the Download links.  The checksums are located in the `dotnetclichecksums` storage account, with ".sha" appended to the filename; for example, the checksum for https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe is at https://dotnetclichecksums.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe.sha.

The checksums should also be included in the download page (https://www.microsoft.com/net/download#core).

Note that core-setup checksums are not yet produced; that work is tracked in https://github.com/dotnet/core-setup/issues/279.

**Comment by livarcocc** [comment]
@blackdwarf Is this something that you are going to be able to do?

@leecow Can you help with the changes to download#core?

**Comment by blackdwarf** [comment]
@livarcocc yes, I should be able to do it on Tue or Wed. I will also take on the changes to the download page as well, though they will need more thinking.

**Comment by piotrpMSFT** [comment]
@blackdwarf is this a dupe of #507 as well?

**Comment by blackdwarf** [comment]
@piotrpMSFT yes, it seems like it is. 

@naamunds just to confirm, the hashes are produced **only** for the CLI, not corefx?

**Comment by naamunds** [comment]
@blackdwarf Correct. https://github.com/dotnet/core-setup/issues/279 tracks adding checksums for core-setup.

**Comment by piotrpMSFT** [comment]
closing dupe
