### ISSUE TITLE
Installation error on Kubuntu 16.10

### ISSUE THREAD

**Issue by Omegastick** [dotnet/cli#4544]
Following the instructions on this page: https://www.microsoft.com/net/core#ubuntu

Running the command: `sudo apt-get install dotnet-dev-1.0.0-preview2-003131` returns:

> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
>  dotnet-dev-1.0.0-preview2-003131 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.1 but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

Looks to be similar to #3855 but I'm running Kubuntu 16.10 and the steps given to fix the problem don't work for me.

**Comment by piotrpMSFT** [comment]
is there any indication why the sharedframework package is not going to be installed? Can you try installing that one directly?

**Comment by blackdwarf** [comment]
@piotrpMSFT I don't think that Preview 2 and Shared FX 1.0.1 work on 16.10, do they?

**Comment by livarcocc** [comment]
Correct. Preview2 does not support 16.10. It supports 14.04 and 16.04.

**Comment by karabaja4** [comment]
You can hack around this issue by manually installing the missing libicu55 dependency on 16.10:

http://packages.ubuntu.com/xenial/amd64/libicu55/download

`sudo dpkg -i libicu55_55.1-7_amd64.deb`
