### ISSUE TITLE
[Question]-Launching portable apps without command line

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#4545]
I'd like to build a portable app, and to distribute it.
As the build outputs an assembly, and not any form of executable, my understanding is that in order for an end user to run the application, they would have to run a command line `dotnet run` ? Is that correct? 

Most of my users won't want to involve themselves with the command line, they will expect a shortcut to double click on!

So, I'd like to provide the end user with an appropriate shortcut to "launch" the app, without them having to do it via command line. What is the recommended approach / solution for this? Does this suggestion sound sensible? Or am I missing something..

It sounds like each platform that supports portable apps, should have some sort of "launcher" application to launch a portable app via a universal shortcut file format. That way when dotnet builds a portable app, it can not only spit out the assembly, but also a shortcut that the dotnet core launcher would recognise!

**Comment by piotrpMSFT** [comment]
@dazinator `dotnet run` is really intended to be a design-time development tool. When a user installs the shared framework they get with it a shared host, `dotnet[.exe]`. This file is automatically added to the path. Invoking your app on a user's machine should be done by invoking `dotnet path/to/app/entry/point.dll`.

To provide the double-click experience you describe I'd suggest to create a small script that does just that: `dotnet pathto.dll`. A user can then simply double-click the script.

**Comment by davidfowl** [comment]
Sounds related to global tools.

**Comment by dazinator** [comment]
Thanks for the clarification!
Ok so for a windows installation I'd create a .bat file, then a windows shortcut to the .bat file can be added to the users start menu to give windows users the experience they expect.

It sounds like for other platforms I'd need different .bat files and shortcut files then?

It would be really cool if there was a universal dotnet "shortcut" file that worked across all the platforms. This hypothetical shortcut could get opened on a platform via  the platforms "dotnet launcher" application which could be associated to open the file type of dotnet core shortcut files. 

At the moment the application itself maybe portable, but it's launching mechanic isn't and would be pretty nice if it were so that a portable app author didn't have to worry about how the app will be started on particular platforms.
