### ISSUE TITLE
Migration should match project.json expectation on unqualified references

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#4548]
In the dotnet cli repo migrate src/redist

## Expected  behavior
Should contain project references to things like dotnet, tool_csc, etc.

## Actual behavior
Contains PackageReference to those projects. This causes the build to fail.

NOTE: This happens when the target is not specified for the dependency in the project.json file.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003980)

Product Information:
 Version:            1.0.0-preview3-003980
 Commit SHA-1 hash:  aced08a7e2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Updating the title a bit. This bug is really about references that PJ interpreted as being P2P instead being migrated as PackageRefs.
