### ISSUE TITLE
Migrated project adds Project Reference as Package Reference.

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4549]
## Steps to reproduce
- Copy this file \\scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip and extract it to your machine
- Open the solution file
- Go through the migration process
- Open the MyApp.csproj 

## Expected  behavior
![image](https://cloud.githubusercontent.com/assets/12449387/19869674/934fa1f2-9f6a-11e6-948c-c49b121323cc.png)

## Actual behavior
you will see this 
![image](https://cloud.githubusercontent.com/assets/12449387/19869579/257274e8-9f6a-11e6-9e8f-3f467d1d3ba1.png)

**Comment by livarcocc** [comment]
Which version of the CLI are you using? I have fixed this bug sometime last week.

**Comment by jinujoseph** [comment]
1.0.0-preview3-003933 (d15rel/25831.0)

**Comment by livarcocc** [comment]
Ok, I see. This is actually a dup of this one: https://github.com/dotnet/cli/issues/4548.
