### ISSUE TITLE
[csproj] dotnet publish does not copy "contentFiles" to output. 

### ISSUE THREAD

**Issue by chuckries** [dotnet/cli#4553]
This seems to be related to project.json -> csproj migration. 

## Steps to reproduce
1. `mkdir scratch`
2. `cd scratch`
3. `dotnet new`
4. open scratch.csproj and add the following snippet below the existing package reference ItemGroup:
    ```Xml
    <PropertyGroup>
        <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
        <PackageTargetFallback>dnxcore50;portable-net45+win8</PackageTargetFallback>
    </PropertyGroup>
  
    <ItemGroup>
      <PackageReference Include="Microsoft.VisualStudio.clrdbg.MIEngine">
        <Version>14.0.31028-preview-1</Version>
      </PackageReference>
    </ItemGroup>
    ``` 
5. `dotnet restore`
6. `dotnet publish -r win7-x64 -o publish`

## Expected  behavior
The published directory contains these files from the Microsoft.VisualStudio.clrdbg.MIEngine package:
- Microsoft.MICore.dll
- Microsoft.MIDebugEngine.dll
- coreclr.ad7Engine.json <comes from contentFiles>
- osxlaunchhelper.scpt <comes from contentFiles>

## Actual behavior
The published directory does not contain `coreclr.ad7Engine.json` or `osxlaunchelper.scpt`

## Additional Info
Attempting to do this same publish against the following project.json works with older CLI's:
```json
{
  "name": "dummy",
  "buildOptions": {
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.VisualStudio.clrdbg.MIEngine": "14.0.30822-preview-1",
  },
  "frameworks": {
    "netcoreapp1.0": {
	  "dependencies": {
	    "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }
	  },
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },
  "runtimes": {
    "win7-x64": {}
  }
}
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003933)

Product Information:
 Version:            1.0.0-preview3-003933
 Commit SHA-1 hash:  6fcbefa4f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by livarcocc** [comment]
cc @nguerrera

**Comment by piotrpMSFT** [comment]
Publish is handled by sdk, so moving to appropriate repo.
