### ISSUE TITLE
dotnet migrate does not overwrite csproj files when running multiple migrations

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4555]
## Steps to reproduce

* Get an old project.json from somehwere
* Run `dotnet migrate`
* Change the project.json to add a new dependency
* Run `dotnet migrate` again

## Expected  behavior
* Migration is successful
* The csproj file has the `<PackageReference>` that corresponds to the new depedency. 

## Actual behavior

* Migration runs and shows it is successful
* The csproj file is not modified

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003930)

Product Information:
 Version:            1.0.0-preview3-003930
 Commit SHA-1 hash:  3be25bbed3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by piotrpMSFT** [comment]
@blackdwarf could we go for a warning here? Overwriting on a second migration can be quite destructive as folks are likely to have modified their csproj after migrating. I'd much rather display a summary that says that a PJ was skipped in migration because foo.csproj already exists. This is enough context for a user to delete the csproj if they really want the migration to take place. Thoughts?

**Comment by livarcocc** [comment]
I agree with @piotrpMSFT. If we overwrite we may delete work the user has already done on the previously migrated csproj. Plus, at this point, why not simply editing the csproj?

**Comment by blackdwarf** [comment]
There are multiple options here:

1. Blindly overwrite - bad for some reasons
2. Produce a warning
3. Produce a warning and let the user continue with a key pres (similar to what happens in zsh if you do `rm -rf *`)
    3.1 Also add a `--force` option to `dotnet migrate` to do the `y` press. 

I'm fine with starting with #2 and seeing what the users tell us is this a problem or not. Ideally, after the first migration the users should not need to re-run it.

**Comment by livarcocc** [comment]
So, now that we are moving the user's artifacts to the backup folder, does this still make sense? After all, the user will have to move the project.json from the backup folder to the original place and add the reference and then migrate.

Won't it be much easier to run dotnet ref add?

**Comment by livarcocc** [comment]
@blackdwarf can you comment based on my last comment? Do we still need this now that we have ref add and that we are moving PJ to a backup folder?

**Comment by blackdwarf** [comment]
Sure, closing this down.
