### ISSUE TITLE
Can't run GenerateResource Task

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4556]
After `dotnet migrate` ing [Microsoft.AspNetCore.Razor.Design](https://github.com/aspnet/RazorTooling/tree/dev/src/Microsoft.AspNetCore.Razor.Design) attempting to restore3/build3 results in the following error:

`
C:\Users\nimullen\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview3-003892\Microsoft.Common.CurrentVersion.targets(2801,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Users\nimullen\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview3-003892\MSBuild.exe" exists and can be run. [C:\Users\nimullen\Documents\GitHub\RazorTooling\src\Microsoft.AspNetCore.Razor.Design\Microsoft.AspNetCore.Razor.Design.csproj]
`

I thought I recalled seeing an issue associated with GenerateResource task being unable to run but I can no longer find it. Feel free to move or close this issue as a duplicate.

Dotnet info:
```
.NET Command Line Tools (1.0.0-preview3-003892)

Product Information:
 Version:            1.0.0-preview3-003892
 Commit SHA-1 hash:  5301f08423

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
cc @nguerrera

**Comment by piotrpMSFT** [comment]
This likely belongs in the SDK repo. @nguerrera do you want me to move it?

**Comment by Eilon** [comment]
@livarcocc @piotrpMSFT BTW as @NTaylorMullen said, we think this is a dup, but we just can't find it.

This is the "resources don't seem to work properly" issue I mentioned at today's 4:30pm standup/sync.

**Comment by nguerrera** [comment]
Go ahead and create a new issue on the SDK. Please provide complete repro steps.

**Comment by Eilon** [comment]
This issue was moved to dotnet/sdk#346
