### ISSUE TITLE
Embedding resx in a custom namespace

### ISSUE THREAD

**Issue by rnagpal** [dotnet/cli#4557]
Hello All,

I’m embedding an existing .resx file in project.json as follows:

"embed": {
      "include": [
        "../../../../Microsoft.Azure.Documents/SharedFiles/RMResources.resx"
      ]
    },

This embeds the resource as Microsoft.Azure.Documents.Client.Core.RMResources where name of my .net core assembly is Microsoft.Azure.Documents.Client.Core

The existing RMResources class in RMResources.Designer.cs is in Microsoft.Azure.Documents namespace.

Is there a way to have RMResources.resx embedded as Microsoft.Azure.Documents.RMResources in the generated .net core assembly so that I can avoid the below #if #else ?

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if NETFX
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Documents.RMResources", typeof(RMResources).GetAssembly());
#else
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Documents.Client.Core.RMResources", typeof(RMResources).GetAssembly());
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

I'm using 1.0.0-preview2-003133

**Comment by ajaybhargavb** [comment]
@rnagpal, you can use mappings to use your preferred name for the resx file.

```JSON
"embed": {
  "mappings": {
    "Microsoft.Azure.Documents.RMResources.resx": "../../../../Microsoft.Azure.Documents/SharedFiles/RMResources.resx"
  }
}
```

**Comment by piotrpMSFT** [comment]
Thanks @ajaybhargavb !!

**Comment by rnagpal** [comment]
Thanks @ajaybhargavb  for the pointer!

I had to tweak it a bit to get this working. Here is what worked:

"embed": {
      "mappings": {
        "Microsoft.Azure.Documents.RMResources.resx": {
          "include": "../../../../Microsoft.Azure.Documents/SharedFiles/RMResources.resx"
        }
      }
    }
