### ISSUE TITLE
Migrated project from command-line migration again prompts migration when opened from VS

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4561]
## Steps to reproduce
- Copy the project from \\scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip
- Extract to some folder in machine 
- Go to VSMigrationDemo and run " dotnet migrate "
![image](https://cloud.githubusercontent.com/assets/12449387/19898579/dbc798d6-a019-11e6-971f-a65ac2be9ea4.png)
- now open the solution in IDE 
## Expected  behavior
Once migrated , the solution should open up in IDE

## Actual behavior

![image](https://cloud.githubusercontent.com/assets/12449387/19898610/ff022bae-a019-11e6-99ab-f33649b925ad.png)

## Environment data
Cli : 1.0.0-preview3-003933
build: d15rel/15.0.25831.0

**Comment by livarcocc** [comment]
Please open this in VS.
