### ISSUE TITLE
Restore fails on migrated project

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4562]
## Steps to reproduce
Copy the project from \scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip
Extract to some folder in machine
Go to VSMigrationDemo and run " dotnet migrate "
![image](https://cloud.githubusercontent.com/assets/12449387/19898900/2db70d38-a01b-11e6-9796-2af99e41fedb.png)

- once migrated run dotnet restore
- Restore failed on solution level 
- Now try restoring from from the project level 
i see both the .csproj and .xproj in the same directory , expected ? 
![image](https://cloud.githubusercontent.com/assets/12449387/19899052/d7efb430-a01b-11e6-8e33-14c7c21b82c0.png)

## Expected  behavior
restore on solution level should work

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/12449387/19898957/67549146-a01b-11e6-8fad-0d77d632e65c.png)

## Environment data
Cli : 1.0.0-preview3-003933
build: d15rel/15.0.25831.0

**Comment by livarcocc** [comment]
@emgarten Justin, can you take a look?

@jinujoseph For the xproj/csproj, we have fixed that in a later build of the CLI, where we move the migrated xproj/PJ to a backup folder.

**Comment by emgarten** [comment]
This error appears to be coming from Microsoft.Common.CurrentVersion.targets, it does not look related to NuGet,

**Comment by livarcocc** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
This would be fixed by https://github.com/Microsoft/msbuild/pull/1280, which I understand is already in latest VS and CLI.

**Comment by nguerrera** [comment]
@livarcocc Was the msbuild update for that after v3933 of CLI? If so, that would explain it.

**Comment by nguerrera** [comment]
Also, has a CLI with the newer msbuild gone in to VS yet?

**Comment by livarcocc** [comment]
@nguerrera Correct. It was updated after that.
