### ISSUE TITLE
Migrate doesn't correctly migrate property content newlines from project.json

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4564]
The incorrect migration results in build errors.

## Steps to reproduce
- Migrate a project.json with the following property: `"description": "Line 1\r\nLine 2\r\nLine 3"`

## Expected  behavior
- csproj has description as:
```XML
<Description><![CDATA[Line 1
Line 2
Line 3]]></Description>
```
Or 
```XML
<Description>Line 1\r\nLine 2\r\nLine 3</Description>
```

Looks like Description doesn't support CDATA out of the box, not sure if this is intended or not. Filed an issue: https://github.com/dotnet/sdk/issues/347

## Actual behavior
- csproj has description as:
```XML
<Description>Line 1
Line 2
Line 3</Description>
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003933)

Product Information:
 Version:            1.0.0-preview3-003933
 Commit SHA-1 hash:  6fcbefa4f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
@jeffkl @raines @cdmihai I don't think we do anything special for it. It is the msbuild API that is doing that. Can you guys comment on it?

**Comment by livarcocc** [comment]
Closing this. Please open one in msbuild, if there isn't one already.

**Comment by NTaylorMullen** [comment]
Curious isn't it the CLI migration logic that should be outputting the CData?

**Comment by NTaylorMullen** [comment]
Ah, nevermind. We want to support newlines in the property outright.
