### ISSUE TITLE
Migrate doesn't respect global.json

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4568]
## Steps to reproduce
- Unzip [Repro.zip](https://github.com/dotnet/cli/files/565236/Repro.zip)
- Run dotnet migrate at the root (or individually, doesn't matter).
- Inspect csproj files

## Expected  behavior
- Project references for Project1 => Project2 => Project3

## Actual behavior
- Package references

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003933)

Product Information:
 Version:            1.0.0-preview3-003933
 Commit SHA-1 hash:  6fcbefa4f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
Ok, with the fix for https://github.com/dotnet/cli/issues/4548 I am seeing the project being migrated correctly:

```
<ItemGroup>
    <ProjectReference Include="../Project2/Project2.csproj" />
    <ProjectReference Include="../Project3/Project3.csproj" />
  </ItemGroup>
```
