### ISSUE TITLE
TestPlatform targets should add themselves to MSBuildAllProjects property

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#4571]
Ideally, all imported project files should add themselves to the `MSBuildAllProjects` property, in order to better support incremental builds.  `Microsoft.TestPlatform.ImportAfter.targets` and `Microsoft.TestPlatform.targets` aren't currently doing this.  These files appear to be included in the .NET CLI, but I'm not sure if they actually live in this repo.  Feel free to move as necessary.

They can do so by adding the following:

```xml
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
```

See also Microsoft/MSBuild#1298

**Comment by livarcocc** [comment]
Closed this one in favor of https://github.com/Microsoft/vstest/issues/175/
