### ISSUE TITLE
Discussion - allow dotnet publish to create a subdirectory for a framework when -f and -o are used

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4577]
## Steps to reproduce
* Have a project with two or more targets. 
* Run `dotnet publish -f <framework1> -o pub`
* Run `dotnet publish -f <framework2> -o pub`

The second call will overwrite the results of the first call and the `pub` directory will contain the published app for `<framework2>`. We should think about whether `dotnet publish` should always create a subfolder named after a target (either the default one from the project if only one is present or specified one on the command line in the multi-targeting case) regardless of whether the user is specifying the output path or not. 

/cc @livarcocc @piotrpMSFT

**Comment by livarcocc** [comment]
I disagree, when I specify the output path, I expect it to be final. I don't want to have to deal with additional conventions to then find out where my files will end up. I am saying where it is.

**Comment by blackdwarf** [comment]
@livarcocc errr, a "discussion" means more than one person can/should weigh in. 😄 However, after discussing with @piotrpMSFT I will move this issue to the SDK for discussion, since the CLI does not control the output paths anymore.
