### ISSUE TITLE
why dotnet exited?

### ISSUE THREAD

**Issue by anobaka** [dotnet/cli#4578]
## Steps to reproduce
It's a web app, and I just use this dockerfile to build an image and run a container
```
FROM microsoft/dotnet:1.0.0-preview2.1-sdk
WORKDIR /app
ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT Development
ENV LTTNG_UST_REGISTER_TIMEOUT 0
ARG source=.
EXPOSE 5000
ENTRYPOINT ["dotnet", "My Project.dll"]
COPY . /app
```
the docker container exits with code 139 randomly(maybe in several minutes or never), I've done some research about it and it seems like the exitance of dotnet caused the docker container to stop. I also checked the console's output and there was none about why dotnet exited, how can I diagnose it?
## Expected  behavior
run forever

## Actual behavior
exit randomly

## Environment data
`dotnet --info` in docker container output:

```
.NET Command Line Tools (1.0.0-preview2-1-003155)

Product Information:
 Version:            1.0.0-preview2-1-003155
 Commit SHA-1 hash:  d7b0190bd4

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

Thanks

**Comment by livarcocc** [comment]
@naamunds Is there a way to get a stack trace of dotnet out of the docker machine?

I suspect that this is a NullPointer somewhere, but there is a very great chance that this is actually in the application itself and not in the host.

**Comment by naamunds** [comment]
@anobaka Have you checked the logs for the container with the [`docker logs` command](https://docs.docker.com/engine/reference/commandline/logs/)?  Does it contain anything about dotnet exiting?

**Comment by anobaka** [comment]
@naamunds  Thanks for your attention.
It's just the console's output of my program and there is nothing about why it exited.
Here's the end of the log:
![qq 20161103140717](https://cloud.githubusercontent.com/assets/2888789/19957127/de3caf78-a1ce-11e6-924d-2037cea84567.jpg)

After I changed `microsoft/dotnet:1.0.0-preview2.1-sdk` to `microsoft/dotnet:1.1.0-preview1-core`, it runs normally(never stops from yesterday to now), maybe there are some problems with `microsoft/dotnet:1.0.0-preview2.1-sdk` image?

I'm not sure whether it's the right solution, so how can I diagnose problems with scenarios like this?

Thanks.

**Comment by Tratcher** [comment]
@anobaka those session cookie errors may just be from outdated cookies. Encryption keys are not persisted across docker runs by default. You can just clear the cookies on the client.
https://github.com/aspnet/MusicStore/issues/716#issuecomment-254967373

**Comment by naamunds** [comment]
@anobaka I don't think that changing from `microsoft/dotnet:1.0.0-preview2.1-sdk` to `microsoft/dotnet:1.1.0-preview1-core` would affect this.  The difference between these two images is that the "sdk" image contains the .NET Core command-line tools, whereas the "core" image just contains the .NET Core runtime and libraries.  The former is recommended to be used for development environments, and the latter is recommended to be used for production environments. See https://github.com/dotnet/dotnet-docker#image-variants for more info.

The tags were recently renamed from "-core" to "-runtime", so for running your app in production, I would suggest using the `1.1.0-preview1-runtime` image if you're using [framework-dependent deployment](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/), or `1.1.0-preview1-runtime-deps` if you're using self-contained deployment.  I wouldn't expect this to address the crash you're seeing here, though.

Let us know if resolving the session cookie errors fixes the crashes you're seeing.

/cc @MichaelSimons @richlander

**Comment by anobaka** [comment]
@Tratcher @naamunds Thanks for your suggestions.

### **About session cookie error**
The session cookie error is caused by there are two versions of our websites online, which one(previous version) is on CoreCLR and using .net452 hosted on windows, and the other(current version, persists keys to redis) is using netcoreapp1.1 and hosted on docker, and they shared the same session cookie name. After I change the the cookie name on current version, the errors are gone.
**And I really don't think the internal errors in website are able to break down the whole app easily.**

### **Something else I've done**
I added some console's output in `Program.cs` in order to capture something when the app exits.
```
public class Program
    {
        public static void Main(string[] args)
        {
	        try
	        {
		        var host = new WebHostBuilder()
			        .UseKestrel()
			        .UseContentRoot(Directory.GetCurrentDirectory())
			        .UseStartup<Startup>()
			        .Build();

		        host.Run();
				Console.WriteLine("Error: Naturally Exit");
	        }
	        catch (Exception e)
	        {
		        Console.WriteLine(e.Message);
				Console.WriteLine(e.StackTrace);
		        var tmp = e.InnerException;
		        var layer = 0;
		        while (tmp != null)
		        {
					Console.Write($"Inner Exception {++layer}: ");
					Console.WriteLine(tmp.Message);
					Console.WriteLine(tmp.StackTrace);
			        tmp = tmp.InnerException;
		        }
	        }
        }
    }
```
The bad news is, I still can't get any of these messages on `docker logs`, it seems like the app is killed by something out of it.

### **Something in process**
I'm trying the `1.1.0-preview1-runtime` image, it makes me feel unsafe without a reason why my app crashes even if the image solved my problem.

Is there a way to find it out? Please help, I've spent much time on it.
Thanks
