### ISSUE TITLE
Problems installing .Net Core on Linux Mint Sarah version (32 Bits)

### ISSUE THREAD

**Issue by LuisAnibalVasquez** [dotnet/cli#4579]
Followin the instruction from:
https://www.microsoft.com/net/core#ubuntu

## Steps to reproduce
sudo sh -c 'echo "deb [arch=i386] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

## Actual behavior
gpg: solicitando clave 417A0893 de hkp servidor apt-mo.trafficmanager.net
gpg: clave 417A0893: clave pública "MS Open Tech <interop@microsoft.com>" importada
gpg: Cantidad total procesada: 1
gpg:               importadas: 1  (RSA: 1)
gpg: almacén editable no encontrado: eof
gpg: error leyendo `[stdin]': error general
gpg: import from `[stdin]' failed: error general
gpg: Cantidad total procesada: 0

## Environment data
`dotnet --info` output:

**Comment by mellinoe** [comment]
Unfortunately, we don't support 32-bit Linux at this time. We do support x86 windows, but only x64 on Linux/macOS.
