### ISSUE TITLE
Dotnet core 1.0.1 runtime error

### ISSUE THREAD

**Issue by skumarvenkat** [dotnet/cli#4582]
I am trying to execute dotnet command from command line it is failed to execute and it showing following error

> api-ms-win-crt-runtime-l1-1-0.dss is missing from computer

Operating system: windows 2012 Rc2 cloud vm.

![untitled1](https://cloud.githubusercontent.com/assets/120073/19942974/e05d9394-a10b-11e6-9631-907cf011d8ad.png)

![untitled2](https://cloud.githubusercontent.com/assets/120073/19942982/e77c1a24-a10b-11e6-8768-546aec6d2e74.png)

What mistake i am doing?, tried all possible ways, dotnet command not working.

**Comment by livarcocc** [comment]
@gkhanna79 @schellap  This seems like a host issue. Can you guys take a look?

**Comment by gkhanna79** [comment]
@schellap @ramarag Can you please help out?

**Comment by schellap** [comment]
Do you have all the pre-requisites installed?

https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites

Esp., 

> .NET Core dependencies
> 
> .NET Core requires the VC++ Redistributable when running on Windows. It is installed for you by the > .NET Core installer. You need to install the Visual C++ redistributable manually if you are installing .NET Core via the installer script (dotnet-install.ps1).
> 
> The Visual C++ Redistributable version differs by Windows version.
> 
> Windows 10
> Visual C++ Redistributable for Visual Studio 2015
> Windows 7+ (not Windows 10)
> Please make sure that your Windows installation is up-to-date and includes hotfix KB2533623 installed through Windows Update.
> Universal CRT update (you can get more info on what Universal CRT is in this blog post)

**Comment by skumarvenkat** [comment]
Finally found root cause, i tried to install .net framework 4.6 in server, installation popped with error message update "2919355" is missing(even though server configured with automatic updates), after installing updates, reinstall vc++ 2015 runtime -> donet core runtime -> works .

Update details available @: https://support.microsoft.com/en-us/kb/2919355

Note: The updates must be installed in the following order: clearcompressionflag.exe, KB2919355, KB2932046, KB2959977, KB2937592, KB2938439, and KB2934018.

I think .net core windows host installer better to show what update missing like .net framework main installer.

**Comment by piotrpMSFT** [comment]
@skumarvenkat can you open an issue in https://github.com/dotnet/core-setup to track the desired installer fixes?
