### ISSUE TITLE
"dotnet new" and "dotnet new -t web" commands throw when using Developer Admin Command Prompt

### ISSUE THREAD

**Issue by bzhu94** [dotnet/cli#4586]
## Steps to reproduce

Install Steps:

1. Install Dev15 RC build d15rel.25901.02. 

Repro steps:

1. Run "dotnet new" or "dotnet new -t web" from Administrator Developer Command Prompt for VS '15 RC

## Expected  behavior

The command completes and creates a new project.

## Actual behavior

The command throws the following error:

![dotnetnewcropped](https://cloud.githubusercontent.com/assets/8541576/19947970/a9cff672-a107-11e6-8c91-68b190eb227a.png)

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.0-preview3-004005
 Commit SHA-1 hash:  d520160ce3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by livarcocc** [comment]
I tried it in Administrator Developer Command Prompt for VS 2015 and dotnet new without a problem.

Can you try that there too, just so we can confirm this is only happening in VS 2017? Narrow down the root cause a bit?

**Comment by piotrpMSFT** [comment]
for those who are blocked, you should be able to avoid this by setting the following Environment variable:

`DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true`

**Comment by piotrpMSFT** [comment]
Let's look at this for RTM. In general, we may want to cleanly block CLI running in admin command prompt... at least without some special user gesture. NuGet packages can bring with them injected tasks/targets which can do gnarly stuff to a machine given the access.
