### ISSUE TITLE
Migrate does not understand transitive project references that have already been migrated.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4591]
## Steps to reproduce
- Unzip [TransitiveMigrationRepro.zip](https://github.com/dotnet/cli/files/567871/TransitiveMigrationRepro.zip). Project3 has already been migrated and the graph is Project1 => Project2 => Project3.
- `cd src/Project1` (can also go into Project2)
- `dotnet migrate`

## Expected  behavior
- Migration succeeds

## Actual behavior
```
Could not find file 'C:\Users\nimullen\Documents\temp\bug\src\Project3\project.json'.
Migration failed.
```
Note: Project2/project.json does exist.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-004007)

Product Information:
 Version:            1.0.0-preview3-004007
 Commit SHA-1 hash:  80ec02b4da

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

/cc @livarcocc

**Comment by livarcocc** [comment]
This means that we didn't have enough context to know what project3 was needed, it migrated successfully and it was then moved to backup. After that, we can't find a project.json for it when migrating project1 and migration fails.

If you want to run migration like that, you can pass the --no-backup to dotnet migrate and we won't move files around.
