### ISSUE TITLE
Put lzma archiver in blob storage so that we don't have to always re-generated it in builds

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#4593]
We should put the lzma archive in blob to avoid rebuilding it everytime.

We can put it in the same folder as core-setup so that it is easy to find and construct the URI for it.

The question is what to do when we have a new M.NC.App version and need a new lzma archive. Should CLI generate it if it can't find one? I believe so, but we should not upload when doing a local dev build.

The upload should happen from VSO in our official builds.

cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
YES!!!!!
