### ISSUE TITLE
dotnet restore failing to resolve package for web project (with updated NuGet.Config)

### ISSUE THREAD

**Issue by pealmeid** [dotnet/cli#4603]
## Steps to reproduce
    dotnet new -t web
    (add NuGet.Config to folder -- see below for NuGet.Config contents)
    dotnet restore

## Expected  behavior
Restore completes successfully.

## Actual behavior
Restore fails with message: 

    Unable to resolve 'Microsoft.NET.Sdk.Web(>= 1.0.0-alpha-20161029-1)' for '.NETCoreApp,Version=v1.0'

## Environment data
    .NET Command Line Tools (1.0.0-preview3-004040)

    Product Information:
     Version:            1.0.0-preview3-004040
     Commit SHA-1 hash:  de5da5870f

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64

## NuGet.Config contents

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        
        <clear />
        <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
        <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
      </packageSources>
    </configuration>

**Comment by livarcocc** [comment]
@pealmeid for web projects you also need:

<add key="dotnet-web" value="https://dotnet.myget.org/F/dotnet-web/api/v3/index.json" />

Can you try that out?

**Comment by pealmeid** [comment]
@livarcocc Thanks for the quick reply, that solved the problem!

I would suggest adding this to the known issues (I can do it if someone helps me with the PR, as I have never done one in a public repository).

Once again, thanks a lot for your help!
