### ISSUE TITLE
Migration for BundlerMinifier.Core

### ISSUE THREAD

**Issue by barrytang** [dotnet/cli#4605]
The scripts section in project json looks like this:
 
```
"scripts": {
 "prepublish": [ "bower install", "dotnet bundle" ]
}
```
 
and should be added to .csproj and look something like this:
 
```
   # after this import element 
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
 
  <Target Name="findAGoodName" BeforeTargets="BeforePublish">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>
```
 
The tools should be added similar to this:
 
```
<ItemGroup>
  <DotNetCliToolReference Include="BundlerMinifier.Core">
    <Version>2.2.301</Version>
  </DotNetCliToolReference>
</ItemGroup>

```

**Comment by sayedihashimi** [comment]
For the target name how about "BundleAndMinify"?

**Comment by madskristensen** [comment]
We should probably do something generic because the name will have to be auto-generated when migrating from project.json to .csproj. So perhaps we should map "prepublish" from project.json to "BeforePublish" in .csproj and then use that as the target name instead of doing "BeforeTarget. Then it would look like this:

```xml
  <Target Name="BeforePublish">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>
```

@sayedihashimi you had reservation about doing it this way, but I think it makes more sense and will solve the migration naming issue as well. Thoughts?

**Comment by livarcocc** [comment]
I don't think we will have a special target name.

I don't intend to special case this and we already have migration in place for pre-publish scripts.

**Comment by madskristensen** [comment]
@livarcocc So what do you call the target name for the pre-publish scripts in the migration?

**Comment by barrytang** [comment]
@madskristensen, I opened a Dev14 xproj web project in Dev15 and after the migration, here is the output. I confirmed with Vijay this should work. We will update our web template accordingly as well.

```
  <Target Name="PrepublishScript" BeforeTargets="Publish" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>

```

**Comment by gulbanana** [comment]
does this work? after restore and build of a project with the DotNetCliToolReference I get "No executable found matching command dotnet-bundle".
