### ISSUE TITLE
dotnet run file contention errors

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#4610]
## Steps to reproduce

1. Download and restore [dotnet-issue-test.zip](https://github.com/dotnet/cli/files/570337/dotnet-issue-test.zip).
1. Run two `dotnet run` commands concurrently, launching each as close to the same time as is possible. (On my system, I can consistently repro this by typing `dotnet run & dotnet run &` at my shell prompt, which launches two copies of .NET CLI, both in the background.)

## Expected  behavior

Two copies of the program should launch, each sleeping for 30 seconds before exiting.

## Actual behavior

I get the following output:

```
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly. [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018: System.IO.IOException: The process cannot access the file '/Volumes/Sources/dotnet-issue-test/bin/Debug/netcoreapp1.0/tmp.runtimeconfig.json' because it is being used by another process. [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported) [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value) [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore() [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
/Users/wjk/.nuget/packages/microsoft.net.sdk/1.0.0-alpha-20161029-1/build/Microsoft.NET.Sdk.targets(107,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/Volumes/Sources/dotnet-issue-test/tmp.csproj]
```

It seems that the two copies of .NET CLI are trying both update the `*.runtimeconfig.json` file at the same time, and one/both are failing due to file-lock contention. It seems to me this issue could be mitigated by not regenerating this file unless it has changed. (AFAIK, the contents of this file only change following a change in dependencies and a `dotnet restore`.)

## Environment data

```
.NET Command Line Tools (1.0.0-preview3-004040)

Product Information:
 Version:            1.0.0-preview3-004040
 Commit SHA-1 hash:  de5da5870f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by wjk** [comment]
Note that the `dotnet.exe` processes running in the background apparently remain alive after emitting the errors described above, and will need to be cleaned up using `killall`.

**Comment by piotrpMSFT** [comment]
This is an interesting bug to fix once we're fully feature complete. In general, run should be a `ctrl+F5` experience and used for quick testing of code. Production scenarios like multiple instances [I know someone will have examples of where it's interesting in development, but that's not the 99% case :) ] should be invoking `dotnet path/to.dll` directly to avoid the extra overhead of `run`.

**Comment by wjk** [comment]
@piotrpMSFT The reason I’m using `dotnet run` in parallel is because I am using it to run a code generator as part of my MSBuild sequence. Several projects are building concurrently, and each of those must run the same tool.

I’ve tried changing my MSBuild target to build the target in a separate step, get the path to the DLL, and then pass that into `dotnet` directly. Unfortunately, I still get the same error. Presumably, the MSBuild targets in `dotnet/sdk` are updating this file on every build, regardless of how I call it. Should I open an issue there?

**Comment by piotrpMSFT** [comment]
If you're invoking the dll directly then it seems that the runtimeconfig.json for that dll should not be being modified... you're not building it, just executing it. Do you think the problem might be, then, that while executing the dll there is an exclusive lock on the runtimeconfig.json file? If that speculation sounds right then we'll want to open the bug in the /dotnet/core-setup repo instead.

**Comment by piotrpMSFT** [comment]
@schellap in case you see this before the bug gets to core-setup :)

**Comment by wjk** [comment]
@piotrpMSFT I am quite sure that this bug is in the MSBuild infrastructure, and is avoidable by invoking the DLL directly. That said, I have managed to workaround this issue by rebuilding the project once, writing the path to the output DLL to a file, and then reading it in again when it is time to run the tool. Since I am only rebuilding the project in question once per complete build cycle (if that), this issue no longer occurs. I’m going to close this now if it’s OK with you.

**Comment by piotrpMSFT** [comment]
> I’ve tried changing my MSBuild target to build the target in a separate step, get the path to the DLL, and then pass that into dotnet directly. Unfortunately, I still get the same error. 

I guess I was confused by this statement. It sounded like the host repro'd the issue without the build infrastructure in the picture. If you're in a good state then I'm happy to leave this closed until we do a concurrency push but if there is a potential host issue I want to let the host folks know as that is a very important scenario :)
