### ISSUE TITLE
PostpublishScript target shouldn't be there after migration

### ISSUE THREAD

**Issue by barrytang** [dotnet/cli#4612]
## Steps to reproduce
1. Create a xproj web project in Dev14
2. Open it in Dev15

## Expected  behavior
PostpublishScript target not there

## Actual behavior

```
  <Target Name="PostpublishScript" AfterTargets="Publish" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="dotnet publish-iis --publish-folder $(TargetDir) --framework $(TargetFrameworkIdentifier),Version=$(TargetFrameworkVersion)" />
  </Target>
```

**Comment by livarcocc** [comment]
The right thing here is that we should not have a dontet publish-iis script anymore, since that tool does not exist in msbuild world.

**Comment by GuardRex** [comment]
> that tool does not exist in msbuild world.

@livarcocc I also asked @natemcmaster over in https://github.com/aspnet/IISIntegration/pull/299#issuecomment-261149435 before I saw this issue.

Are we just going back to a handmade `web.config` and something like ...
```
<Content Include="web.config">
  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
</Content>
```
... to get it into published output?

**Comment by livarcocc** [comment]
@mlorbetske Can you answer @GuardRex's question about web.config? Is this something that the Web.Sdk is handling?

**Comment by GuardRex** [comment]
@livarcocc Thanks ... I'm good. Vijay got me straight on that.
