### ISSUE TITLE
"dotnet build" is not building project targeting net46. Asking for RuntimeIdentifier

### ISSUE THREAD

**Issue by Faizan2304** [dotnet/cli#4619]
## Steps to reproduce
Create any project targeting net46 say project.csproj"
run command "dotnet build project.csproj"

## Expected  behavior
It should build it successfully 

## Actual behavior
Getting following error
*\.nuget\packages\microsoft.net.sdk\1.0.0-alpha-20161029-1\build\Microsoft.NET.RuntimeIdentifierInference.targets(45,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [*\VSTestDesktopAndNetCore\VSTestDesktopAndNetCore.csproj]

Repro project: https://github.com/dotnet/cli/tree/rel/1.0.0/TestAssets/TestProjects/VSTestDesktopAndNetCore

**Comment by Faizan2304** [comment]
In my local development box it is working fine but if a create a new windows 10 machine (Version 1607 (OS Build14393 .0) With visual studio from branch d15rel version 15.0.25903.2, I am hitting this issue.

**Comment by livarcocc** [comment]
This is by design. For Full Framework projects, they need to have RuntimeIdentifiers set inside the project and you need to say for which RID you want to build, otherwise we don't know which native assets to use.

https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/DesktopTestProjects/AppWithProjTool2Fx/App.csproj#L8

**Comment by GuidovTricht** [comment]
I am running into the same problem, even after adding the RuntimeIdentifier in the csproj:
![image](https://cloud.githubusercontent.com/assets/1440052/20640752/d821299a-b3e7-11e6-834e-69cf1ba3f4ff.png)
Is there another fix for this, or am i doing something wrong? It does work on my desktop PC without even adding the RuntimeIdentifiers.

**Comment by belczyk** [comment]
@GuidovTricht I had the same problem. I'm pretty sure @livarcocc quoted specs not actually value to be copied to project file. 
It actually should be <RuntimeIdentifier> (singular) not <RuntimeIdentifiers> (plural). 
For example: `<RuntimeIdentifier>win7-x86</RuntimeIdentifier>`
When I changed it to singular version project builds properly. 

![2016-11-26 15_53_50 visual studio](https://cloud.githubusercontent.com/assets/1131764/20641104/43232780-b3f1-11e6-8329-e08b1bc50947.png)

**Comment by GuidovTricht** [comment]
@belczyk Thanks for your reply!
This is indeed the case, next to the fact that the node was named RuntimeIdentifier**S**, instead of RuntimeIdentifier.
I can now succesfully build my solution, thanks :)

**Comment by wizarrc** [comment]
Does anyone know if this bug is filed for the xproj to csproj migration? I'm not sure if the vs tooling is on GitHub or not. It seems to make it plural every time I migrate. If I knew where to give feedback I could file a bug report.
