### ISSUE TITLE
error: Unable to load the service index for source https://MyAccount.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/MyProject/nuget/index.json.

### ISSUE THREAD

**Issue by kiewic** [dotnet/cli#4624]
## Steps to reproduce

1. Open Visual Studio 2015
2. Go to Tools > Options ....
3. Navigate to NuGet Package Manager > Package Sources
4. Click + button (add package source)
5. Write a name in the Name field
6. Set the Source field to a NuGet source that requires Azure Active Directory authentication, such as, `https://contsoso.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/ContosoNuGet/nuget/index.json`
7. Then do a `dotnet restore .\project.json` on any project.

## Expected  behavior

This should complete with a successful message:

> log  : Restoring packages for D:\repos\Foo\project.json
> ...
> log  : Restore completed in 3679ms.

## Actual behavior

The `dotnet` client fails with a very ambiguous error that could take hours to understand. There is no clue that the failing package source was set on Visual Studio, and it is not referenced by the project we are restoring.

> log  : Restoring packages for D:\repos\Foo\project.json
> error: Unable to load the service index for source https://consotoso.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/ContosoNuGet/nuget/index.json.
> error:   An error occurred while sending the request.
> error:   The parameter is incorrect

Moreover, NuGet package sources with Azure Active Directory authentication work well with traditional desktop solutions when restoring packages from Visual Studio.

## Environment data

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
Moved to nuget repo
