### ISSUE TITLE
Improve preview3+ UX when invoked on non-migrated xproj's

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4628]

**Comment by piotrpMSFT** [comment]
@livarcocc thoughts?

**Comment by livarcocc** [comment]
Nothing comes to mind that would not require new strings to be localized.

But, in the CLI, before invoking any command, we could see if the command is targeting old artifacts (project.json and .xproj) and throw a Graceful exception then with information about how to run migration. I would not want to automatically run migration for the user though. That seems too invasive.

**Comment by piotrpMSFT** [comment]
So:

```
   try
   {
      runSomeCliCommand()
   }
   catch (Exception)
   {
      if (project.json exists in working directory)
      {
           Console.WriteLine(LocalizableStrings.RecommendMigration);
      }
   }
```

?

**Comment by livarcocc** [comment]
Yeah, something along those lines.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#40
