### ISSUE TITLE
Migrating dotnet-test-xunit breaks test execution.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4629]
## Steps to reproduce
- `dotnet migrate` [this super simple project](https://github.com/dotnet/cli/files/572858/TestMigrationProject.zip). Key thing about this project is it has a `dotnet-test-xunit 2.2.0-*` dependency which enabled it to run in project.json land.
- Add `<OutputType>Exe</OutputType>` to top level `PropertyGroup`. This is to workaround a [test execution bug](https://github.com/Microsoft/vstest/issues/191).
- `dotnet restore`
- `dotnet test`

## Expected  behavior
```
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   Tests.Tests.Test1

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.3253 Seconds
```

## Actual behavior
- You get an output that looks something like:
```
Test run for C:\Users\nimullen\Documents\temp\msbuild\bin\Debug\netcoreapp1.0\msbuild.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
```
It never states results of tests being run. You can then get the actual behavior by removing the `dotnet-test-xunit` dependency.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

## Extra
@bradwilson is the original owner of `dotnet-test-xunit` and that contained the xunit runner for the old world. It'd be a good idea to reach out and make sure everyone's on the same page for when it comes to invoking test runners, whether it be ours or third parties. This issue might spawn a different one in SDK to allow runners like Brad's to plug into the CLI test experience. For the interim, migrating all that we do for test projects breaks things 😄

**Comment by bradwilson** [comment]
`dotnet-test-xunit` is going away. The Visual Studio runner is being updated with .NET Core support.

**Comment by bradwilson** [comment]
For what it's worth, I'm seeing the exact same behavior with the new Visual Studio runner. I'm engaged with @hasrshjain2 who [did the work](https://github.com/xunit/visualstudio.xunit/commit/4a852e61b8e2dfb41079a76c63a6e84a582586c1).

**Comment by NTaylorMullen** [comment]
Ah, good to know! Thanks Brad!

**Comment by bradwilson** [comment]
There are 2.2 beta 4 builds of `xunit` and `xunit.runner.visualstudio` on NuGet that should work for you now. (The `dotnet-test-xunit` package is being retired.)

**Comment by livarcocc** [comment]
Migration will now remove the reference to dotnet-test-xunit.

**Comment by harshjain2** [comment]
@livarcocc Migration should also remove the reference of dotnet-test-mstest as well.

**Comment by piotrpMSFT** [comment]
@harshjain2  can you open an issue to track that one?
