### ISSUE TITLE
Migration creates warnings for obsolete but empty properties

### ISSUE THREAD

**Issue by MattGertz** [dotnet/cli#4634]
## Steps to reproduce
Open an old, simple xproj (ask me for my Vigenere project) in VS 25904.02.  Migrate it.

## Expected  behavior
Project migrates with the exception of buildOptions-related stuff.

## Actual behavior

src\Vigenere\Vigenere.xproj: Project Vigenere migration failed (C:\Users\MattGe\Vigenere\src\Vigenere) MIGRATE1011::Deprecated Project: C:\Users\MattGe\Vigenere\src\Vigenere The 'projectUrl' option in the root is deprecated. Use it in 'packOptions' instead.

(line: 6, file: C:\Users\MattGe\Vigenere\src\Vigenere\project.json) The 'licenseUrl' option in the root is deprecated. Use it in 'packOptions' instead.

(line: 7, file: C:\Users\MattGe\Vigenere\src\Vigenere\project.json) The 'tags' option in the root is deprecated. Use it in 'packOptions' instead.

(line: 5, file: C:\Users\MattGe\Vigenere\src\Vigenere\project.json) The 'compilationOptions' option is deprecated. Use 'buildOptions' instead. (line: 9, file: C:\Users\MattGe\Vigenere\src\Vigenere\project.json)

The first three of these properties have null values, and they should simply be ignored. I would expect something like "Obsolete 'projectUrl' property has no value; ignoring." and so on, per our discussion last month. (Perhaps there is a bug on this already?)

I get that we can't currently do anything about guessing the proper value of compilationOptions->buildOptions, but I would really like to do something for that in a subsequent release.

## Environment data
`dotnet --info` output:

**Comment by piotrpMSFT** [comment]
@MattGertz can you share your `project.json`, at least the relevant bits?

**Comment by MattGertz** [comment]
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true, 
    "debugType": "portable"
    },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-24018"
    }
  },
  "frameworks": {
    "netstandard1.5": {}
  }
}

**Comment by livarcocc** [comment]
@MattGertz we are tracking this here already: https://github.com/dotnet/cli/issues/4166. We will get it in.
