### ISSUE TITLE
dotnet on an AWS Linux instance throws a: System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl'

### ISSUE THREAD

**Issue by samuelyounge** [dotnet/cli#4635]
dotnet on an AWS Linux instance throws a: System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl' exception.

Project ran fine before adding HttpContext.Session support which apparently added additional dependencies.  I tried loading different versions of "System.Security.Cryptography.Algorithms":  which did change the error message but was unable run exception free despite the changes. I ended up sticking with "4.3.0-preview1-24530-04" and trying to upgrade openssl on linux box, without success (possible pathing problem, not sure what directories dotnet looks in for libraries and bins).

BTW, project runs fine on Windows 10 development box using Visual Studio Community 2015's debug feature.  It is only when project is migrated to production server that it fails.

All advice is welcome, thanks, Sam.

## Steps to reproduce
On a AWS Linux instance.
project.json:
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "jQuery": "3.1.1",
    "Microsoft.AspNetCore.Session": "1.1.0-preview1-final",
    "Microsoft.Framework.Caching.Memory": "1.0.0-beta8",
    "Microsoft.Framework.Caching.Abstractions": "1.0.0-beta8",
    "Microsoft.Extensions.Caching.Memory": "1.1.0-preview1-final",
    "System.Security.Cryptography.Algorithms": "4.3.0-preview1-24530-04"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

From project directory:
dotnet restore
dotnet run

## Expected  behavior
Download libraries
Compile project
Run project

## Actual behavior
Downloads libraries
Compiles project
Throws exception:
log  : Restoring packages for /var/www/faithmail/project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in /var/www/faithmail/project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in /var/www/faithmail/project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in /var/www/faithmail/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /var/www/faithmail/project.lock.json
log  : /var/www/faithmail/project.json
log  : Restore completed in 3436ms.
Project faithmail (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/var/www/faithmail/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Content root path: /var/www/faithmail
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/  
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The type initializer for 'Crypto' threw an exception.
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.Crypto.GetMaxMdSize()
   at Interop.Crypto..cctor()
   --- End of inner exception stack trace ---
   at Interop.Crypto.GetRandomBytes(Byte[] buf, Int32 num)
   at System.Security.Cryptography.RNGCryptoServiceProvider.GetBytes(Byte[] data)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()

Starts webserver but fails to run project

## Environment data
`dotnet --info` output:
[root@ip-172-30-1-143 ec2-user]# dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     amzn
 OS Version:  2016.09
 OS Platform: Linux
 RID:         amzn.2016.09-x64

yum info openssl
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.1k
Release     : 15.96.amzn1
Size        : 3.6 M
Repo        : installed
From repo   : amzn-updates
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

Available Packages
Name        : openssl
Arch        : i686
Epoch       : 1
Version     : 1.0.1k
Release     : 15.96.amzn1
Size        : 1.5 M
Repo        : amzn-updates/latest
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
License     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.

Also, tried installing OpenSSL 1.1.0b
It had no effect though I am not sure the default pathing allows dotnet to see the 1.1.0b libraries.

**Comment by samuelyounge** [comment]
This seemed like dotnet could not locate the openssl libraries or either they were the wrong version.
So I tried installing OpenSSL 1.10b and pointing dotnet to the new libraries.

If I read this correctly: [](https://github.com/dotnet/corefx/blob/9823256decb60d6824121fb4578e3780698ccd4e/src/Native/System.Security.Cryptography.Native/CMakeLists.txt)

dotnet core openssl library pathing is determined by:
${OPENSSL_CRYPTO_LIBRARY}
${OPENSSL_SSL_LIBRARY}

So I added to my /root/.bash_profile:
OPENSSL_CRYPTO_LIBRARY=/usr/local/lib64/libcrypto.so
export OPENSSL_CRYPTO_LIBRARY
OPENSSL_SSL_LIBRARY=/usr/local/lib64/libssl.so
export OPENSSL_SSL_LIBRARY

I logged out and back in to make the variable available then re-deployed the application, executed dotnet restore, then dotnet run, but received the same error message.

Now, I am a bit at a loss as to what this could be.  Any ideas?

**Comment by halter73** [comment]
I don't think the native openssl library is the issue. System.Security.Cryptography.Native.OpenSsl (the thing that's missing) is a managed shim to the native library.

You can either downgrade your AspNetCore dependencies all to 1.0.0/1.0.1, or upgrade them all to to 1.1.0-preview1-final. We don't test mixing and matching minor versions of AspNetCore. If you updated to 1.1.0-preview1-final AspNetCore packages, you should use Microsoft.NETCore.App 1.1.0-preview1-001100-00.

If you stick to the 1.0.(0|1) train, you should use System.Security.Cryptography.Algorithms 4.2.0, which is the [dependency specified by Microsoft.NETCore.App 1.0.1](https://www.nuget.org/packages/Microsoft.NETCore.App/1.0.1). BTW, do you need to add an explicit  System.Security.Cryptography.Algorithms dependency to your project.json? I figured you'd get it transitively through Microsoft.AspNetCore.Session. Once you align all the AspNetCore package versions and Microsoft.NETCore.App version, you should get the right System.Security.Cryptography.Algorithms dependency automatically.

Hopefully this helps you workaround the issue @samuelyounge, but I agree that the difficulty of figuring out which packages/platforms are truly compatible is a pretty bad experience right now. I don't like that everything restores and builds without so much as a warning only to fail with a DllNotFoundException at runtime.

This seems to me like a recurrence of https://github.com/dotnet/corefx/issues/12517. Maybe we should reopen that issue.

**Comment by samuelyounge** [comment]
Thanks for the good advice halter73.  It worked!
It took me a good two hours fighting with various dependency conflicts and buggy VS2015, but in the end it worked out.

Here is my working project.json in case someone has a similar problem with .net core mvc on aws linux.

{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.Framework.Caching.Memory": "1.0.0-beta8",
    "Microsoft.Framework.Caching.Abstractions": "1.0.0-beta8",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Routing": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.Session": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.Extensions.Caching.Memory": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "System.Security.Cryptography.Algorithms": "4.2.0",
    "System.Security.Cryptography.OpenSsl": "4.0.0",
    "jQuery": "3.1.1"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

Thanks again,
Sam

**Comment by halter73** [comment]
FWIW,, I tried mixing 1.1.0 and 1.0.0 dependencies using the prerelease packages from the [aspnetcore-ci-dev myget feed](https://dotnet.myget.org/gallery/aspnetcore-ci-dev/), and the app ran fine on both Windows and Debian 8.2, so it looks like dotnet/corefx#12517 was fixed but not in time for 1.1.0-preview1.

Here's the sample app I used to test the dependency mixing: https://github.com/halter73/session-sample.
