### ISSUE TITLE
Passing arguments to project.json

### ISSUE THREAD

**Issue by rnagpal** [dotnet/cli#4637]
This is regarding project.json tooling that we have currently.

I need to provide different buildOptions while building locally vs building in the lab. For example, I want to delaySign my assembly when building locally but publicSign when building in the lab.

Also, some of the dependencies that I need to package in my nuget package are located in different locations in local machine vs lab machine, so I need different relative paths to be provided in packOptions/files/mappings/runtimes/includeFiles.

I’m looking for a way to provide arguments to project.json so that I can control what gets passed when building locally vs building in the lab.

Does anyone have any suggestions?

I’d like to avoid maintaining 2 different project.json for this purpose.

## Environment data
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
I don't believe this is possible except with different files, at least in project.json world.

If you migrate to csproj and msbuild, you can pass an arbitrary number of properties through the command line using the /p:propertyname:propertyvalue and you can use that to change/set values differently based on where you are building.

**Comment by atanasa** [comment]
Please update the help documentation of `dotnet help build` to include the syntax for passing arbitrary properties and any other options that might be missing.

**Comment by piotrpMSFT** [comment]
@atanasa 
```
$ dotnet build --help
.NET Builder

Usage: dotnet build [arguments] [options] [args]

Arguments:
  <PROJECT>  The MSBuild project file to build. If a project file is not specified, MSBuild searches the current working directory for a file that has a file extension that ends in `proj` and uses that file.

Options:
  -h|--help                           Show help information
  -o|--output <OUTPUT_DIR>            Output directory in which to place built artifacts.
  -f|--framework <FRAMEWORK>          Target framework to build for. The target framework has to be specified in the project file.
  -r|--runtime <RUNTIME_IDENTIFIER>   Target runtime to build for. The default is to build a portable application.
  -c|--configuration <CONFIGURATION>  Configuration to use for building the project. Default for most projects is  "Debug".
  --version-suffix <VERSION_SUFFIX>   Defines the value for the $(VersionSuffix) property in the project
  --no-incremental                    Disables incremental build.
  --no-dependencies                   Set this flag to ignore project-to-project references and only build the root project
  -v|--verbosity                      Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

Additional Arguments:
 Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.
```

Note the last line. The help info for msbuild is quite extensive, and includes:

```
  /property:<n>=<v>  Set or override these project-level properties. <n> is
                     the property name, and <v> is the property value. Use a
                     semicolon or a comma to separate multiple properties, or
                     specify each property separately. (Short form: /p)
                     Example:
                       /property:WarningLevel=2;OutDir=bin\Debug\
```

**Comment by piotrpMSFT** [comment]
@blackdwarf we should think about adding some examples to each of the `help` messages in a future release. @atanasa's point is a pretty good one: this is a common thing to do, and it's burried past a layer of documentation indirection...
