### ISSUE TITLE
Windows x64 dotnet CLI install location

### ISSUE THREAD

**Issue by Antaris** [dotnet/cli#464]
Following @davidfowl repo: https://github.com/davidfowl/dotnetcli-aspnet5

Example failed because it's looking to bind CoreCLR libs from `C:\Program Files\Microsoft\dotnet\runtime` but the installer dropped them at `C:\Program Files\dotnet\runtime`.

![image](https://cloud.githubusercontent.com/assets/255906/11710781/973a6470-9f19-11e5-9745-7bc4ece9c86c.png)

**Comment by Sridhar-MS** [comment]
@Antaris I am not able to repro the it with the [latest MSI](https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi).

![image](https://cloud.githubusercontent.com/assets/9423246/11727190/65937af6-9f37-11e5-9482-d36e0f5bdf95.png)


There were some breaking changes in the MSI and upgrade from an older daily build may not work. Can you completely uninstall Dotnet CLI and reinstall the latest one?

**Comment by Antaris** [comment]
Hmmm, every time I go to install it...

![snip_20151211080629](https://cloud.githubusercontent.com/assets/255906/11738837/20497a7a-9fde-11e5-854f-da2149d71d1e.png)

I don't ever remember setting the install location when I install this (as in, I haven't ever changed it).

**Comment by blackdwarf** [comment]
@Antaris can you please provide more info on your repro:

* Which Windows version you are using?
* Dump of PATH and DOTNET_HOME env variables after MSI install
* Version of the MSI (displayed in the control panel uninstall programs)

**Comment by Antaris** [comment]
@blackdwarf Sorry for late reply, here's some info:

Windows Version
> Windows 10 Pro Update 1 (not insider, so just on RTM build)

Path
> C:\Program Files (x86)\Pervasive Software\PSQL\bin\;C:\Program Files\Pervasive Software\PSQL\bin\;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Git\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Performance Tools;C:\Program Files (x86)\LINQPad4;C:\downloads\PSTools;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\abbottm\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Java\jdk1.8.0_65\bin;C:\Program Files\Microsoft\dotnet\bin;C:\Applications\Atlassian\atlassian-plugin-sdk-6.1.0\bin

Version
> 1.0.0.1449791651

**Comment by piotrpMSFT** [comment]
@Antaris, the install directory you're seeing is consistent with what @Sridhar-MS was showing. It looks like your Path is listing an older install location. Can you uninstall dotnet, check your path variable for the C:\...Microsoft\dotnet... and remove it if present, and then re-install latest? 

I'm not able to get a report, so I hope we are just seeing a bug from an outdated installer.

**Comment by brthor** [comment]
have not been able to repro. Please reopen if you are still hitting this.
