### ISSUE TITLE
dotnet-install.ps1 robustness / comments

### ISSUE THREAD

**Issue by rs38** [dotnet/cli#4648]
I ran into an issue before adding a disk space guard clause, when running the script on nano server with less disk space than 250 GB.
The script exited somewhere in the extracting step and when repeating the script it claims that all has been installed correctly.

I would suggest to get the needed size a bit more precisely and add a better check for a correctly installed dotnet version.
Not sure if 250 MB is the correct value for current download and expanding and how it will increase in the future.
I also noticed there is a lot of use of `write-host` in the script which already made some trouble if executed on TFS Agents. See this for reference:

http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/

https://github.com/aspnet/Docs/pull/2113
https://github.com/dotnet/cli/pull/4647

**Comment by johnbeisner** [comment]
This was fixed with PR: https://github.com/dotnet/cli/pull/6664
