### ISSUE TITLE
What's the point of `--packages` on restore?

### ISSUE THREAD

**Issue by stanislavromanov** [dotnet/cli#4649]
What is the point of `--packages` option on `restore` if there is no `--packages` on `run` or/and `build`?

## Steps to reproduce
`dotnet new`
`dotnet restore --packages Packages`
`dotnet build/run` 

## Expected  behavior
I expect to pass some parameter which tells where to look for packages.

## Actual behavior
Error, packages not found.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

**Comment by piotrpMSFT** [comment]
Excellent question! I'm sure the option came in because of legacy behavior in `nuget.exe`. @emgarten may be able to tell us about scenarios where this option makes sense in CLI.

@blackdwarf we should figure out how to unify this option's intent across the CLI. Either remove the option from `dotnet restore` or add it to other verbs.

**Comment by emgarten** [comment]
> I expect to pass some parameter which tells where to look for packages.

The value of ``--packages`` is stored in project.assets.json, build/run should be reading it from there.

Setting ``--packages`` to a new folder for restore is a common way to ensure that no previously downloaded packages are used during a CI build.

**Comment by blackdwarf** [comment]
@piotrpMSFT by what @emgarten says above, the build/run/publish commands should read the value from the assets file.

**Comment by livarcocc** [comment]
Closing this in favor of the SDK issue above.
