### ISSUE TITLE
No dotnet repl

### ISSUE THREAD

**Issue by darrenparkinson** [dotnet/cli#4650]
There was talk of a dotnet repl.  This would be useful and it was some time ago these discussions happened, so I wanted to know if there was any update?

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
REPL depends on an expansion of `dotnet extensions` that allows them to run outside the context of a project. Once that feature comes in we will re-evaluate REPL. I don't expect this to happen before the holidays.

**Comment by kidchenko** [comment]
Any news about REPL? Now that we hit the dotnet 2.1

**Comment by livarcocc** [comment]
We still have no plans of adding it at the moment.
