### ISSUE TITLE
Unable to build due to conflicting or unresolved dependencies

### ISSUE THREAD

**Issue by alien-mcl** [dotnet/cli#4652]
## Steps to reproduce
1. Run command _dotnet build_ for [URSA](https://github.com/alien-mcl/URSA/blob/dot-net-core/URSA.Http.Description/project.json) project.
2. Run command _dotnet restore_ for [URSA](https://github.com/alien-mcl/URSA/blob/dot-net-core/URSA.Http.Description/project.json) project.

## Expected  behavior
1. Project compiled.
2. Project dependencies restored

## Actual behavior
1. error NU1001: The dependency Newtonsoft.JSON >= 9.0.1 could not be resolved.
2. Loads of issues like the one below:
    Unable to satisfy conflicting requests for 'System.Runtime.Serialization.Primitives': System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Microsoft.Extensions.Configuration.Json 1.0.0), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Microsoft.Extensions.Configuration.Json 1.0.0), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/System.Runtime.Serialization.Xml 4.1.1), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Newtonsoft.Json 9.0.1), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Newtonsoft.JSON 9.0.1), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Newtonsoft.Json 9.0.1), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Newtonsoft.Json 9.0.1), System.Runtime.Serialization.Primitives (>= 4.1.1) (via package/Newtonsoft.Json 9.0.1)

## Environment data
`dotnet --info` output:
```bash
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

## Summary

In general, I'm trying to move my two projects to .Net Standard platform. One is [RomanticWeb.net](https://github.com/alien-mcl/RomanticWeb) which is already moved (in alpha stage) and generally builds correctly from both Visual Studio and command line tools. I'm struggling to build one of a projects within [URSA](https://github.com/alien-mcl/URSA/tree/dot-net-core) solution. I've noticed, that *RomanticWeb.dotNetRDF* affects the behavior - without it projects restores correctly and fails to build due to missing types. Once added, I'm experiencing issues.
Interesting thing is that I'm able to restore the project with NuGet CLI without problems, but _dotnet build_ still fails.
I've tried to look for some answers and the closes issue I found so far is #2924, but this seems quite old and I didn't find a conclusing fix.
What am I doing wrong? Is there any possibility of having a more details build output? The _--verbose_ option seems not to be working here.

**Comment by piotrpMSFT** [comment]
@alien-mcl I took a quick look and found:
- json-ld.net: project.json requests version 1.0.6, NuGet.org has 1.0.5
- RomatincWeb: project.json requests version 1.0.0, NuGet.org has 0.4.0

It looks like there are packages requested that don't exist on nuget.org [I didn't check the others, but expect it's the same issue based on version numbers.

Is there perhaps a NuGet.config file missing that gives access to these packages? 

I'll close this since the issues seem to be with project configuration. I'd check the version numbers in the project.json and compare them to nuget.org.

I also noticed the repro above suggests to `build`, then `restore`. These steps should be done in reverse order: `restore` then `build`.

**Comment by alien-mcl** [comment]
@piotrpMSFT 
Indeed, there are packages that are yet not available on nuget and I serve them from local repository. Bu that's not the case (I could probably add those to nuget and remat my dependencies, but I don't expect this would resolve the situation).
The thing is - when I build the solution from Visual Studio everything works fine. It complains when restoring, but when I "hack" the nuget's temp directory and put forcibly rejected dependencies, it builds fine. For some reason, command line still complains.

I'll try to setup a standalone project to reproduce the issue - maybe then it won't be closed in such a hurry.

As for the repro - I didn't want to submit two separate issues - I feel these are related to each other.

**Comment by alien-mcl** [comment]
@piotrpMSFT 
I think I've pin-pointed the culprit. Looks like it's related to #2901 and #236. It came that dotNetRDF causes the project.lock.json file to have a dependency on Newtonsoft.JSON@9.0.1 ending up with failed resolution of that dependency. Workaround of that issue in my case is to replace Newtonsoft.JSON to Newtonsoft.Json and it builds correctly.
Can you somehow confirm that this issue is still unresolved?
