### ISSUE TITLE
Migrate errors are not getting put in formatted output

### ISSUE THREAD

**Issue by 333fred** [dotnet/cli#4655]
## Steps to reproduce
Create a bad xproj scenario. The one I've been testing with is having an xproj reference a non-existent project. Run `dotnet migrate -r output.json --format-report-file-json`.

## Expected  behavior
The text
```
The project file could not be loaded. Could not find file 'C:\Users\frsilb\Downloads\VSMigrationDemo\MyApp\MyLib.xproj'. C:\Users\frsilb\Downloads\VSMigrationDemo\MyApp\MyLib.xproj
Migration failed.
```
is put into a formatted json report in output.json as well as being printed to the console.

## Actual behavior
The error is just printed to the console. Migration fails without creating an output.json at all.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14931
 OS Platform: Windows
 RID:         win10-x64
```

@livarcocc

**Comment by krwq** [comment]
Fixed by https://github.com/dotnet/cli/pull/4718
Please create a new issue if you find some other not working cases
