### ISSUE TITLE
`dotnet test` should consider the Tools section when searching for `dotnet-test-<runner>`

### ISSUE THREAD

**Issue by plioi** [dotnet/cli#4658]
## Steps to reproduce

Create a test project which uses xUnit and its dotnet-test-xunit runner. 

Following https://xunit.github.io/docs/getting-started-dotnet-core.html for instance, I have a project.json like so:

```json
{
    "version": "1.0.0-*",
    "testRunner": "xunit",
    "dependencies": {
        "xunit": "2.2.0-beta2-build3300",
        "dotnet-test-xunit": "2.2.0-preview2-build1029"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "type": "platform",
                    "version": "1.0.0"
                }
            }
        }
    }
}
```

At the command line, `dotnet test` runs the tests as normal.

Strange, though, that all the .NET Core test runners place the runner itself in the Dependencies section, as they are design-time tools that need not actually be *referenced*. Move it to the tools section instead:

```json
{
    "version": "1.0.0-*",
    "testRunner": "xunit",
    "dependencies": {
        "xunit": "2.2.0-beta2-build3300"
    },
    "tools": {
        "dotnet-test-xunit": "2.2.0-preview2-build1029"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "type": "platform",
                    "version": "1.0.0"
                }
            }
        }
    }
}
```

Run `dotnet test` again.

## Expected  behavior

As with other design-time tools, dotnet-test-<framework> tools should be locatable when specified in the Tools section.

## Actual behavior

"No executable found matching command "dotnet-test-xunit"

The problem is more extreme when targeting the full .NET Framework, as the runner and many, many transitive dependencies get copied to the build output folder, altering the intended set of assemblies that make up the system under test.

This is **not** limited to xunit.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@plioi this is by-design. The reason is that the runner's dependencies and the test library's dependencies have to be unified into a single graph. `tools` dependencies, on the other hand, get restored with their own graph and don't consider packages that a test library might reference at an incompatible version. Consider a common type like System.Object. If the test references it from a 1.0.1 library and the runner from 1.0.0, the test will fail due to assembly binding since the runner's dependency, at a lower version, would get loaded first.

**Comment by plioi** [comment]
Is this another problem introduced by the lack of AppDomain isolation?
