### ISSUE TITLE
Migration can produce duplicate resource items

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#4667]
Reported to me by @harshjain2. I don't have the original project.json so follow up with him on that

dotnet migrate produced two embedded resource entries: 

``` XML
<EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
<EmbeddedResource Include="Resources\*.resx;compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
```

Notice how resx files in `Resources\` match `**\*.resx` and `Resources\*.resx`

@livarcocc

**Comment by piotrpMSFT** [comment]
@harshjain2 can you share the project that reproduces this behavior?

**Comment by piotrpMSFT** [comment]
@nguerrera is this something that we can and should handle in SDK? de-dupe the EmbeddedResource list? are there valid scenarios where it is desirable to include duplicates? Also in Compile, etc.?

**Comment by livarcocc** [comment]
@harshjain2 can you please share a project.json that would repro this?

**Comment by nguerrera** [comment]
It's possible to dedup in the SDK but there are lots of design considerations:

Do we do this for all items? E.g. Compile too?
If there's differing metadata, which one wins? Do we merge non overlapping metadata?

I'm reluctant to open up those questions and I think it should just remain an error for the user to resolve on a case by case basis.

**Comment by livarcocc** [comment]
This is what we migrate to now:

```
<EmbeddedResource Include="**\*.resx" />
<EmbeddedResource Include="compiler\resources\**\*" />
```

I am not sure what else to do. All these dedup issues would also exist if we tried to do it during migration. I would really like to take  a look at a PJ that reproes this to see what else we could do, both for embedded resources and compile.

Maybe, if a set of files is specified, used that and don't emit the generic all capturing ones?

Ideas?

**Comment by nguerrera** [comment]
Based on that alone, a repro would be to have a .resx file in compiler\resources\**\*.

Consider:

``` diff
<EmbeddedResource Include="**\*.resx" />
-<EmbeddedResource Include="compiler\resources\**\*" />
+<EmbeddedResource Include="compiler\resources\**\*" Exclude="**\*.resx" />
```

**Comment by nguerrera** [comment]
> Maybe, if a set of files is specified, used that and don't emit the generic all capturing ones?

Are the above wildcards always emitted, even when there is an explicit list? Does that actually match the project.json behavior?

**Comment by nguerrera** [comment]
Another idea, if semantically you need the generic ones and the user specified ones:

``` XML
<EmbeddedResource Include="[User specified]" />
<EmbeddedResource Include="**\*.resx" Exclude="@(EmbeddedResource)" />
<EmbeddedResource Include="compiler\resources\**\*" Exclude="@(EmbeddedResource)" />
```

**Comment by harshjain2** [comment]
@livarcocc [project.json](https://github.com/harshjain2/samples/blob/master/ResourceRepro/project.json)

**Comment by livarcocc** [comment]
@nguerrera I like your idea above. I think that will work.
