### ISSUE TITLE
Extension point for languages

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4669]
To have an awesome language agnostic experience it's nice if the sdk (like previous `preview2`) has a clean extension point to add additional languages

Atm works ( ref f# [examples](https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3) and [tests suite](https://github.com/dotnet/netcorecli-fsc/tree/master/test-msbuild) ), but can be improved a bit

An example the [fsharp with preview3](https://github.com/dotnet/netcorecli-fsc/blob/99e22f5413fa0dc7ea16bf92a35fb0048fa99207/examples/preview3/console/ExampleConsoleApp.fsproj#L26-L28)

So:

1. Add a `PackageReference`  to a lang sdk package who contains msbuild target files (example [FSharp.NET.Sdk](https://github.com/dotnet/netcorecli-fsc/tree/master/src/FSharp.NET.Sdk) ) who are auto imported
     - The targets file contains a:
          - `CoreCompile` task => ok, thats usually invoke the compiler to compile
          - `CreateManifestResourceNames` task => why?
2. Import at the end `$(MSBuildToolsPath)\Microsoft.Common.targets` (instead of `Microsoft.CSharp.targets`)

That's ok and works, but with some issues:

- I cannot directly include `Microsoft.Common.targets` inside my target files, because at the first `dotnet restore` doesnt exists, so restore doesnt work (`Common` imports nuget restore target somewhere).
- I think is important to be able to import `Microsoft.Common.targets` inside custom language targets, for example to be able to replicate the .net framework build script (so wildcard include before and after `.Common` import). If i put `.Common` inside the target file is an authoring error because is included two times (on `dotnet restore` is ok, but after that is included two times)
- I can specify to import the target inside nugetpackage at the end of project file, but is annoying atm because i need to do that starting from $NugetPackageCacheRoot directory, so that's going to include version of package. Also doesnt work at first `dotnet restore`, because doesnt exists yet, so i need to conditionally include `Common` anyway

Best experience from project:

- Just include a `PackageReference` with custom targets like `CoreCompile` (compiler can be a dotnet sdk tool :love:)
- No need to include `Microsoft.Common.targets` target at the end, maybe another target who will invoke the auto-imported lang target.

@nguerrera you have some ideas about how to do the extensibility changes?

/cc @piotrpMSFT @livarcocc @blackdwarf 
/cc @cartermp @KevinRansom @cloudRoutine for F#

**Comment by piotrpMSFT** [comment]
I moved this issue to the SDK repo as it pertains primarily to changes in the SDK targets. Let's re-open here if/when there are CLI changes needed.
