### ISSUE TITLE
dotnet-compile should preserve resource assembly info in deps file

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#467]
Right now, the deps file does not contain the resource assemblies. The data is in the lock file, we just need to transfer it to the deps file.

**Comment by piotrpMSFT** [comment]
@anurse, is this coming in today or should we bump to RC?

**Comment by anurse** [comment]
Not today for sure.

**Comment by anurse** [comment]
@pakrym can you make sure these are pulled from the lock file through to the deps file?

**Comment by anurse** [comment]
I don't think we're OK with making things RTM... it would be a regression in behavior since we would be unable to load satellite assemblies for packages that have resources.

**Comment by anurse** [comment]
Note: We're also not able to do project-to-project resource references because of this. I think I've actually got a fix that covers all the these cases though, and it's not super scary. Will discuss and send necessary mails to get approval if we think it's partner-blocking.
