### ISSUE TITLE
Template Wishlist

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4675]
This issue tracks asks for additional CLI Templates that folks would like to have access to. Think of these as Up For Grabs work items for folks that want to build CLI templates. Let us know if you're interested in taking one of these on!

 - [ ] Starter Solution - a library, a test project, and a sln file to match #3503
 - [ ] Self-contained deployment with a Dockerfile
 - [ ] Console application with a Dockerfile
 - [ ] Extensibility with a target
 - [ ] ASP.NET Web API

**Comment by blackdwarf** [comment]
Here are a few more:

- [ ] Self-contained deployment with a Dockerfile
- [ ] Console application with a Dockerfile
- [ ] Extensibility with a target

**Comment by piotrpMSFT** [comment]
@blackdwarf I edited our posts to merge the lists :)

Which impl? TBD.

**Comment by clentfort** [comment]
A "ASP.NET Web API" template for `dotnet new` would be nice. :)

**Comment by piotrpMSFT** [comment]
@mlorbetske

**Comment by blackdwarf** [comment]
Moved this to dotnet/templating#233 as it is the proper place for this. Closing down this one.
