### ISSUE TITLE
Perf: CLI extremely high memory usage and CPU load during restore all packages for corefx

### ISSUE THREAD

**Issue by nietras** [dotnet/cli#4676]
## Steps to reproduce
 * Clone `corefx` repo and follow instructions to build. E.g. commit 4e961640ab618297326575bb70722760115e61d0
 * Run `build.cmd` in git powershell window on Windows 10.
 * Wait until all packages are restored.

## Expected  behavior
 * Restore should be fast, very little cpu usage and low memory usage.

## Actual behavior
 * Memory usage and CPU is extremely high for a long time...

![image](https://cloud.githubusercontent.com/assets/10798831/20171231/03c9c602-a730-11e6-9516-af157fb16753.png)

## Environment data
This uses `build.cmd` in corefx which downloads its own version of CLI tools as far as I understand, so see the given commit.

**Comment by livarcocc** [comment]
Moved this to the NuGet repo.
