### ISSUE TITLE
Publishing .NET Core Web API Project on CentOS 7

### ISSUE THREAD

**Issue by denizalpaslan** [dotnet/cli#4677]
Hi, I've coded a very simple web API Project (with a single controller) and having some issues with publishing.  Am I missing something? Thanks in advance.

## Steps to reproduce

-  I run "dotnet publish" in my project folder, resulting a /bin/Debug/publish folder.
-  Copied the contents of this folder to "/var/www/dotnet_core_poc"
- "dotnet restore"
- "dotnet run"

## Expected  behavior

Expected application to run on specified port.

## Actual behavior

It works in my project folder. But when I copied the published content to the actual folder,

Error message : 
`dotnet exec needs a managed .dll or .exe extension. The application specified was '/var/www/dotnet_core_poc/bin/Debug/netcoreapp1.0/dotnet_core_poc.dll'`

## Environment data

CentOS 7,  nginx configured as described in deployment tutorials.

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64

```

Contents of "/var/www/dotnet_core_poc/" (My app folder) :

```
- appsettings.json
- dotnet_core_poc.deps.json
- dotnet_core_poc.dll
- dotnet_core_poc.pdb
- dotnet_core_poc.runtimeconfig.dev.json
- dotnet_core_poc.runtimeconfig.json
- All dependency DLLs (Microsoft, Newtonsoft.Json.dll etc.)
- refs folder
- runtimes folder
- web.config
- wwwroot folder
```

Contents of web.config : 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!--
    Configure your application settings in appsettings.json. Learn more at https://go.microsoft.com/fwlink/?LinkId=786380
  -->
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\dotnet_core_poc.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```

**Comment by livarcocc** [comment]
Once you publish an application you do not need (or can) restore or use the run command on it anymore.

Both restore and run are development tools and they require your source code to work.

The good news is that once you publish, you can simply run your application in one of two ways, depending on whether you published a portable or a self contained app.

If it is a portable app, you won't see an app.exe in your publish folder. In which case you can invoke it by running dotnet app.dll.

If it is a self contained app, you will see an app.exe in your publish folder. You can run it simply by invoking that exe.

You can see if it is a portable or self-contained app by checking if you have a type: platform under Microsoft.NetCore.App dependency.

**Comment by svick** [comment]
Just a small correction:

> If it is a self contained app, you will see an app.exe in your publish folder. You can run it simply by invoking that exe.

Not on CentOS (or any other Linux). There, a self contained app produces an executable named just `app`, which can be directly invoked (`./app`).

**Comment by piotrpMSFT** [comment]
I'm seeing myself type app[.exe] and myscript.[sh|ps1] all too often :)
