### ISSUE TITLE
Migrations on releases of different runtimes

### ISSUE THREAD

**Issue by MikeRavenelle** [dotnet/cli#4678]
I am attempting to publish my application to win10-x64 from a Ubuntu 16.04 system. I am able to publish it correctly but how do I go about adding the migration and updating the database?

I tried using --configuration release flag for dotnet ef, but it defaults to ubuntu-16.04 runtime and creates the migration and database for it instead of the win10-x64. I tried adding the dotnet ef commands to a postpublish script but it does it for the compiled debug.

Thanks

**Comment by livarcocc** [comment]
Moved it to the aspnet entity framework repo.
