### ISSUE TITLE
Indirect dependency on the framework assembly on .Net core prerelease version

### ISSUE THREAD

**Issue by SamvelS** [dotnet/cli#4685]
## Steps to reproduce
I am doing some experiments with prerelase version of .Net Core.

I am using **1.0.0-preview4-004071** version of .Net Core.
Installed .NET Core SDK, created **1.0.3** folder in **C:\Program Files\dotnet\shared\Microsoft.NETCore.App** and added binaries for same build version (all downloaded from **https://github.com/dotnet/cli#installers-and-binaries**).

My *.csproj file is:
`<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
    <PropertyGroup>
       <OutputType>Exe</OutputType>
       <TargetFramework>netcoreapp1.1</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
       <Compile Include="**\*.cs" />
       <EmbeddedResource Include="**\*.resx" />
    </ItemGroup>
    <ItemGroup>
       <PackageReference Include="Microsoft.NETCore.App">
       <Version>1.0.3</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk">
       <Version>1.0.0-alpha-20161104-2</Version>
       <PrivateAssets>All</PrivateAssets>
    </PackageReference>	
    </ItemGroup>        
	<Reference Include="System.Collections.Specialized"/>
    <Reference Include="System.Collections.NonGeneric">
       <SpecificVersion>False</SpecificVersion>
       <HintPath>Lib\System.Collections.NonGeneric.dll</HintPath>
    </Reference>
    <Reference Include="System.Resources.ResourceManager"> 
       <SpecificVersion>False</SpecificVersion>  
       <HintPath>Lib\System.Resources.ResourceManager.dll</HintPath>
    </Reference>
    </ItemGroup>
    <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
    </Project>
`

Under Lib folder I have copies of DLLs from same build.

I am trying to use **System.Collections.Specialized** and **System.Collections.NonGeneric** DLLs (tried to get from default path and Lib folder) but getting warnings like this:

`C:\Program Files\dotnet\sdk\1.0.0-preview4-004071\Microsoft.Common.CurrentVersion.targets(1909,5): warning MSB3268: The primary reference "System.Collections.NonGeneric" could not be resolved because it has an indirect dependency on the framework assembly "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Collections.NonGeneric" or retarget your application to a framework version which contains "System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".` 
         
`C:\Program Files\dotnet\sdk\1.0.0-preview4-004071\Microsoft.Common.CurrentVersion.targets(1909,5): warning MSB3268: The primary reference "System.Collections.NonGeneric" could not be resolved because it has an indirect dependency on the framework assembly "System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "System.Collections.NonGeneric" or retarget your application to a framework version which contains "System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".`

If I am correct problem is that msbuild can't find correct assemblies and looking into incorrect path.

How can I fix assembly path lookup?

**Comment by piotrpMSFT** [comment]
The error message is spot on. The <Reference> items are pulling in Desktop .NET Framework. Since you're targetting netcoreapp1.0, you'll want the portable versions of these. I checked NuGet.org for the [first one](https://www.nuget.org/packages/System.Collections.Specialized/4.3.0-preview1-24530-04) and found that version 4.3.0-preview1-24530-04 is the latest version and supports `netstandard1.3`, so we can use it in a portable project like this one.

Change that <Reference> to a 

```
<PackageReference Include="System.Collections.Specialized">
  <Version>4.3.0-preview1-24530-04</Version>
</PackageReference>
```

The other <Reference> should be migrated in the same fashion.

Thanks!

**Comment by SamvelS** [comment]
This didn't help me and I did following:
Added DLLs listed in warnings from cpreclr (https://github.com/dotnet/coreclr) build.
After adding reference for System.Runtime getting lots of exceptions such as:

`AssemblyInfo.cs(6,30): error CS0433: The type 'AssemblyCompanyAttribute' exists in both 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' `

But public code for mscorlib.dll (added reference on my side) is different.

**Comment by SamvelS** [comment]
Some of DLLs I am using supports `netstandard1.3` while some support only `netstandard1.0`.
Can issue be because of this?

**Comment by SamvelS** [comment]
Why this issue is closed?
Suggested fix is not working.

**Comment by SamvelS** [comment]
Solution is [here](https://github.com/dotnet/cli/issues/4710)

**Comment by piotrpMSFT** [comment]
The suggested fix addressed the original issue, then exposed a different issue which you're tracking in #4710.
