### ISSUE TITLE
Migration should add rids when it migrates a project with a desktop TFM in it

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#4689]
Without the RIDS, the desktop project won't be able to build.

**Comment by twsouthwick** [comment]
The error I'm seeing (which I'm assuming is being tracked by this issue) is: `RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64` 

I am doing a migration for a project that targets .NET 4.6. The manual fix is to do this for now in the csproj file:

```xml
<PropertyGroup>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by piotrpMSFT** [comment]
Thanks @twsouthwick that's exactly what the migration tool will do. It will likely add both RID's for completeness, though.
