### ISSUE TITLE
dotnet pack is missing --runtime option

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#4691]
If I build a project with --runtime, dotnet pack requires me to pass in an RID. Either:
1. This is a bug with pack because it shouldn't need an RID, or
2. We need to add that option to dotnet pack

**Comment by piotrpMSFT** [comment]
I think Pack should do all available RIDs, not force users to select one. @joelverhagen what are your thoughts?

**Comment by joelverhagen** [comment]
Related: https://github.com/dotnet/cli/issues/4609

**Comment by piotrpMSFT** [comment]
dupe of #4609
