### ISSUE TITLE
Fix the error that happens on running build on a non-restored project

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4693]
## Steps to reproduce

Install the latest MSBuild-based CLI and then do  the following:

```bash
mkdir hwapp && cd hwapp 
dotnet new
dotnet build
```

## Expected  behavior
The build returns the error that there is no assets file and gives clear guidance on what to do, that is, run `dotnet restore`. 

## Actual behavior
This message is produced as an error:

```bash
/opt/dotnet/sdk/1.0.0-preview4-004071/Microsoft.Common.CurrentVersion.targets(1107,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/blackdwarf/hwapp/hwapp.csproj]
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004071)

Product Information:
 Version:            1.0.0-preview4-004071
 Commit SHA-1 hash:  9855dc0088

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

On Windows, it is even more confusing, since some compatible reference assemblies will exist and build will complete, but it will produce a .NET Framework, not .NET Core assembly in the output.

/cc @piotrpMSFT @livarcocc @nguerrera

**Comment by piotrpMSFT** [comment]
For commands that require restore [e.g. anything that drills down to msbuild] we should have a simple check for restore artifacts. If they simply don't exist we should pre-restore OR at least tell the user they should restore.

**Comment by livarcocc** [comment]
This is the same as this: https://github.com/dotnet/cli/issues/2199.
