### ISSUE TITLE
dotnet migrate should add <None Include="App.config" /> when file present

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#4694]
This is low priority since this file is not technically needed for build but it will improve VS experience for migrated projects.

## Steps to reproduce
`dotnet migrate` desktop app with App.config

## Expected  behavior
App.config visible in VS

## Actual behavior
App.config not visible in VS

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004081)

Product Information:
 Version:            1.0.0-preview4-004081
 Commit SHA-1 hash:  2ac1680239

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
I assume you're saying that project.json pack did the same thing?

**Comment by livarcocc** [comment]
@krwq And App.Config was not a part of project.json at all? Can you share an example project?

**Comment by krwq** [comment]
@livarcocc App.Config was not part of project.json.

Any desktop targeting project with App.Config next to it will do. App.Config is being considered during the build but it is not explicitly in the project.json. I believe if you take a look at BindingRedirect TestAssests before they were being migrated that would be a good test case.
