### ISSUE TITLE
dotnet migrate should not add Framework references that the SDK will include by default

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#4695]
dotnet/sdk#379 will make the .NET SDK implicitly include references to assemblies such as `System`, `System.Core`, etc when the project is targeting .NET Framework.  So these references do not need to be in the project file and the migration tool should not add them.

Currently, these are the references that are implicitly included, though it's possible that they will change due to feedback before the PR is merged:

```xml
    <Reference Include="System"/>
    <Reference Include="System.Core"/>
    <Reference Include="System.Data"/>
    <Reference Include="System.Drawing"/>
    <Reference Include="System.IO.Compression.FileSystem" Condition=" '$(_TargetFrameworkVersionWithoutV)' >= '4.5' "/>
    <Reference Include="System.IO.Compression" Condition=" '$(_TargetFrameworkVersionWithoutV)' >= '4.5' "/>
    <Reference Include="System.Net.Http" Condition=" '$(_TargetFrameworkVersionWithoutV)' >= '4.5' "/>
    <Reference Include="System.Numerics" Condition=" '$(_TargetFrameworkVersionWithoutV)' >= '4.0' "/>
    <Reference Include="System.Runtime.Serialization"/>
    <Reference Include="System.Xml.Linq"/>
    <Reference Include="System.Xml"/>
```

**Comment by piotrpMSFT** [comment]
@dsplaisted I'm assigning to you for the moment until you can provide an explicit list of things that need to change. Once that's locked, update the issue and assign to @livarcocc

**Comment by dsplaisted** [comment]
The PR has been merged, and the implicit references are the same as I initially listed in this issue description.

**Comment by livarcocc** [comment]
I believe we are only adding System. I will remove it though.
