### ISSUE TITLE
Test Project not migrated as test project

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4696]
https://github.com/gulbanana/repro-dotnettest-workingdirectory

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/issues/4067 is the source of this one

**Comment by piotrpMSFT** [comment]
I think this may be because the test project targets netcoreapp1.0 and net461.

**Comment by livarcocc** [comment]
I just tried this.

I ran:

```
cd src\TestProject
dotnet migrate
dotnet restore
dotnet test - it passed
cd ..
dotnet test .\TestProject\TestProject.csproj - it passed
```

If you were expecting dotnet test .\TestProject, without specifying a project to work, please, open a separate issue for dotnet test itself to handle that.
