### ISSUE TITLE
Adding vbc.exe & vbc.dll

### ISSUE THREAD

**Issue by hishamco** [dotnet/cli#4698]
I was playing with dotnet Cli stuff, my question from where shall I bring the assemblies `vbc.exe` and `vbc.dll` so I can drop them in the `stage2` folder and use them later on

/cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
Ty come from the same package as CSC, iirc. They may already be in the stage2 directory...

**Comment by hishamco** [comment]
Nope, the only thing is the C# compiler, I already did a lot of changes to create and build VB files, regarding the create new vbproj no problem, but the main issue in the `dotnet build` because the VB assemblies are not found, I tried to use `vbc` which I bring from `nuget` folder with no luck. There's a dependency issue
Any idea?

**Comment by piotrpMSFT** [comment]
Are you doing this work on vbproj or project.json? I heard of a group creating vb support during a hackathon last week. @blackdwarf may know if this got published.

I'd strongly recommend going down the msbuild route. Making this work will be considerable work on project.json and will prevent benefiting from evolution of the cli...

**Comment by hishamco** [comment]
I'm not quite sure about the hackathon
Previously I worked on `project.json` but I move it to the msbuild after the latest changes in the Cli repo. My aim from awhile to enable VB via Cli

**Comment by piotrpMSFT** [comment]
@blackdwarf is the hackathon port on gh somewhere?

**Comment by blackdwarf** [comment]
@piotrpMSFT I haven't gotten anything so far.

**Comment by blackdwarf** [comment]
@cartermp did you have something to do with this?

**Comment by cartermp** [comment]
Nope.

**Comment by hishamco** [comment]
Thanks all, I already did some stuff in the Cli source, but when I bring the vbc.exe from the NuGet package it seems not compatible with the core stuff, AFAIK Roslyn should serve both C# and VB.NET

**Comment by hishamco** [comment]
@piotrpMSFT these are the [MVP Summit projects](https://blogs.msdn.microsoft.com/webdev/2016/11/22/mvp-hackathon-2016/) unfortunately I didn't find a VB support?!! anyhow I will struggle on this, but I need the mentioned files to continue with

**Comment by piotrpMSFT** [comment]
@srivatsn just called out in #587 that VB support should basically be in place and a template is missing. Please do watch that issue :)

**Comment by hishamco** [comment]
Thanks @piotrpMSFT, I already change the `dotnet new` locally and I added VB project template, the problem in the build step, coz the compiler binaries are missed.
I will try to check the compiler bug that @srivatsn mentioned in that issue that you referenced

**Comment by srivatsn** [comment]
@hishamco The [Microsoft.Net.Compilers.netcore](https://github.com/dotnet/roslyn/blob/master/src/NuGet/Microsoft.Net.Compilers.netcore.nuspec) package brings in the vb compiler as well - are you saying that the vb compiler is not working for you? The bug that I mention in the compiler shouldn't block you from building because i'd put in a [workaround](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.VisualBasic.targets#L15) to get build to work. The workaround breaks debugging and other scenarios and hence is not a workable solution but it should get you off the ground.

**Comment by hishamco** [comment]
> are you saying that the vb compiler is not working for you

Nope, I didn't find the VB assemblies, I found some with the same names in my machine but there's a missing dependencies, anyhow i will try to install the package and see what I come up with
thanks @srivatsn

**Comment by Shayan-To** [comment]
@hishamco Any progress?

**Comment by hishamco** [comment]
@Shayan-To really I stuck after that I created a PR #5145 which is closed, still I didn't know why the test is failed

**Comment by livarcocc** [comment]
We now have VB enabled for the 2.0.0 SDK.

**Comment by hishamco** [comment]
Yep, I forgot to close this, but still we have an issue with Razor, that's why I filed an issue in Razor repo

thanks
