### ISSUE TITLE
Ugly formatting of a migrated project

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#4702]
## Steps to reproduce
migrate a project.json to app.csproj

## Expected  behavior
Formatting is nice

## Actual behavior
There are no new lines and opening it up in a text editor is ugly.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
@Petermarcu Which editor did you use? Also, can you paste the csproj. This is unexpected. We have fixed this a while ago.

**Comment by krwq** [comment]
@Petermarcu I haven't seen that and I have migrated couple of projects - is it possible that you were using notepad and `dotnet migrate` used \n instead of \r\n? That still would be a bug on Windows IMO but lower priority.
If there is no actual line endings could you share the project and the output?

**Comment by Petermarcu** [comment]
yes, I opened it in notepad. I opened my project.json in notepad as well and it had line breaks. Its not a bug in Windows that it expects \r\n. The project I migrated was literally one that I created using 'dotnet new' from an older CLI (preview 2). I'll try to repro.

**Comment by Petermarcu** [comment]
Yes, just repro'd it really easily. I'll email it to you.

**Comment by krwq** [comment]
Seems like we only get \n where on windows \r\n is most likely expected as many people use notpad which is not displaying that character properly. If we can't fix it in msbuild yet we should be able to do simply string.Replace("\r\n", "\n") on the output for now to provide better experience - not sure if that is suitable solution.

**Comment by Petermarcu** [comment]
This isn't an immediate problem meaning, I don't think you need to hack to make it work. It should be fixed before you ship though. If that solution is in MSBuild then you can just track it there.

**Comment by jeffkl** [comment]
We have an open issue with comments' line endings being altered: https://github.com/Microsoft/msbuild/issues/1340

But the rest of the file should be correct.  @AndyGerlicher might have fixed this in https://github.com/Microsoft/msbuild/pull/1378

**Comment by piotrpMSFT** [comment]
Using this to track getting a fix to the msbuild issues linked by @jeffkl above.

**Comment by piotrpMSFT** [comment]
Microsoft/msbuild#1340 and Microsoft/msbuild#1378 are both fixed, merged, and inserted into CLI. @Petermarcu let us know if there is still a lingering issue here. I did not see a repro with today's build.
