### ISSUE TITLE
Cannot publish a platform specific shared framework app

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#4704]
## Steps to reproduce
Try to publish for a specific platform but remain runnable on a shared framework

## Expected  behavior
Expect to be able to prevent the pollution of my Windows build with Linux and OSX assets.

## Actual behavior
Everything in the portable app that has platform specific binaries are all copied to my published output making my app have binaries for platforms I don't care about.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@Petermarcu can you add a repro project for your specific scenario?

**Comment by Petermarcu** [comment]
Its just dotnet new with a runtime defined that I want to publish for. As soon as I add the runtime, it acts like I want to be fully standalone.

**Comment by piotrpMSFT** [comment]
@eerhardt you seem to be partially online. Thoughts on this one?

**Comment by piotrpMSFT** [comment]
This was discussed in WAR and we decided not to pursue the scenario at this time.

**Comment by Petermarcu** [comment]
Which WAR? For which release. This will need to come back, should it just be moved out past whatever your current milestone is?

**Comment by Petermarcu** [comment]
When we do need to support this additional dial, do we know who we will do it without a breaking change?

**Comment by eerhardt** [comment]
To enable this you need to add 

```XML
<RuntimeIdentifiers>XXX;YYY;ZZZ</RuntimeIdentifiers>
```

property to your .csproj.

When you want to publish as a shared framework/portable app, just use `dotnet publish`.

When you want to publish as a standalone app for a specific runtime, you say `dotnet publish --runtime YYY`.  You need to pick one of the runtimes listed in the `RuntimeIdentifiers` property you added to the .csproj.

Does this help?

**Comment by Petermarcu** [comment]
Not quite. That is how I publish for a specific RuntimeIdentifier as a standalone app. This is about publishing for a RuntimeIdentifier and still being a "shared framework/portable" app.

**Comment by Petermarcu** [comment]
I think we should keep this open and get it into the next milestone if it's not going to fit into this one. I have seen multiple people using this feature in project.json for two scenarios.

1. Unit testing where they want to ensure they get the right RID assets running on a shared framework for testing.
2. Publishing an app for Windows or Mac and not wanting any of the other OS's assets. They then take the direct output of publish and put it in a pkg for mac and an msi for windows to create an installer.

**Comment by eerhardt** [comment]
How does the project.json look?  Does it have 'type: platform' and have the "runtimes" section filled with a set of RIDs?

Is this the "low-fat app" scenario that @davidfowl talks about?

**Comment by davidfowl** [comment]
> How does the project.json look? Does it have 'type: platform' and have the "runtimes" section filled with a set of RIDs?

That's my guess though we never designed how it would work, we didn't block this either...

> Is this the "low-fat app" scenario that @davidfowl talks about?

Yep.

**Comment by Petermarcu** [comment]
Yeah, I guess its a "low fat" app. :) We need more than one dial for going standalone. Specifying that you want to be RID specific shouldn't also mean that you have to be fully standalone.

**Comment by Petermarcu** [comment]
Whats the right milestone for the May timeframe next year?

**Comment by piotrpMSFT** [comment]
Backlog for the time being...

**Comment by Petermarcu** [comment]
@piotrpMSFT , Thanks!

**Comment by Petermarcu** [comment]
This overloading is now having two negative impacts on the community:

1.       It makes it nearly impossible for components with native assets or cross compiles for different OS’s to ship on NuGet because they have to invent new build infra just to create a single package across all their builds. If they don’t, they are only useful for standalone apps. So they just choose not to publish.
2.       Many of these components have 10+ RID folders for the matrix of (OSX, Windows, and one or more Linux’s) x (x86, x64, arm32, arm64). This means shared apps get 10x the number off assets in their app than they need.

We really need a plan and to get this addressed.

**Comment by Petermarcu** [comment]
Take a look at this package: https://www.nuget.org/packages/SkiaSharp/1.56.2

Looks like a shared "Fat" app today would have to carry 7MB x 6 in their application.

**Comment by Petermarcu** [comment]
Packages above the shared framework should be able to use the runtime.json solution and have split packages.

**Comment by eerhardt** [comment]
> Packages above the shared framework should be able to use the runtime.json solution and have split packages.

Agreed - but this is 2 separate problems right?

1. Tooling to support publishing a "low fat app".
2. Ensure 3rd parties can produce (and apps can consume) split packages, not just "fat packages"

We can solve each independently.

**Comment by Petermarcu** [comment]
Yeah, let's make sure we get the first addressed as it appears to be pretty straight forward. I also noticed this other issue tracking this which is likely a dupe: https://github.com/dotnet/cli/issues/5553

**Comment by livarcocc** [comment]
I believe this was fixed by https://github.com/dotnet/sdk/pull/1053 and https://github.com/dotnet/cli/pull/6234. @eerhardt please, reactivate if there is still something missing.

**Comment by eerhardt** [comment]
This work is done.
