### ISSUE TITLE
dotnet publish without a build or restore should give a good error

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#4705]
## Steps to reproduce
create a project
run dotnet publish

## Expected  behavior
Error that says, please restore your project before publishing or even better, restore just happens for me.

## Actual behavior
     1>Project "c:\temp\arm2\arm.csproj" on node 1 (Publish target(s)).
     1>PrepareForBuild:
         Creating directory "bin\Debug\".
         Creating directory "obj\Debug\".
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Program Files\dotnet\sdk\1.0.0-preview4-004079\RunCsc.cmd /noconfig /nowarn:1701,1702 /nostdlib+ /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /debug:portable /nowin32manifest /out:obj\Debug\arm.exe /target:exe /utf8output Program.cs "C:\Users\Petermarcu\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cs"
       _DeploymentComputeClickOnceManifestInfo:
         Creating directory "bin\Debug\app.publish".
         Copying file from "obj\Debug\arm.exe" to "bin\Debug\app.publish\arm.exe".
     1>C:\Program Files\dotnet\sdk\1.0.0-preview4-004079\Microsoft.Common.CurrentVersion.targets(3715,5): error MSB4062: The "Microsoft.Build.Tasks.ResolveManifestFiles" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\temp\arm2\arm.csproj]
     1>Done Building Project "c:\temp\arm2\arm.csproj" (Publish target(s)) -- FAILED.

Build FAILED.

       "c:\temp\arm2\arm.csproj" (Publish target) (1) ->
       (_DeploymentComputeClickOnceManifestInfo target) ->
         C:\Program Files\dotnet\sdk\1.0.0-preview4-004079\Microsoft.Common.CurrentVersion.targets(3715,5): error MSB4062: The "Microsoft.Build.Tasks.ResolveManifestFiles" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\temp\arm2\arm.csproj]

    0 Warning(s)
    1 Error(s)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Moved to SDK repo
