### ISSUE TITLE
How to get third party console app or package from the url using dotnet cli get | install <url>

### ISSUE THREAD

**Issue by gencebay** [dotnet/cli#4707]
Is there any feature in dotnet cli to get small package or cross platform executable compiled console program from the source (Url or Path) like that:

`dotnet get github.com/<reponame>` 

to install the build output on my local DOTNET_PATH that is already registered on my environment!
Thanks!

**Comment by piotrpMSFT** [comment]
are you tring to add some build-time extension to your current context?

**Comment by gencebay** [comment]
Hi, I want to install a binary (compiled by .NET Core as Console App) to my local path to execute it from console directly. I found something to do [Chocolatey](https://chocolatey.org/) but it just works on Windows platform and required .NET framework dependencies. It would be nice that when I have dotnet cli (.NET SDK) on my local machine so get a binary from source and execute it with compatible .NET Core SDK without huge dependencies!
For example [golang](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies) does.
Thanks!

**Comment by piotrpMSFT** [comment]
@blackdwarf you wrote a CLI extensibility guide at one point. Can  you share? Perhaps a link to your demo as well?

@gencebay we today support wrapping console apps as nuget packages and then restoring them to other machines. It is close to the behavior that you want, though there are some issues [it requires running in the context of a csproj] that make this approach not ideal. @blackdwarf should be able to share guidance.

Another approach you can consider is adding a shim script to your path. This would be a `myapp.[cmd|sh]` that would:

```
dotnet /fully/qualified/path/to/myapp.dll
```

Thoughts?

**Comment by blackdwarf** [comment]
@gencebay here is the Preview 2 (project.json based CLI) extensibility document: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/extensibility. Preview 3 (MSBuild based) extensibility document is on https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/extensibility. 

These should get you going if you wish to write your console app as an extension.

**Comment by blackdwarf** [comment]
@gencebay where you able to make do with these answers?

**Comment by gencebay** [comment]
@blackdwarf sure, thanks!

**Comment by gencebay** [comment]
.NET Core Global Tools work perfectly for me.
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools
