### ISSUE TITLE
Rootfolder for unittests is the folder where "dotnet test" is run

### ISSUE THREAD

**Issue by Larswa** [dotnet/cli#4708]
## Steps to reproduce
For a test project based on netcoreapp1.0:
Run "dotnet tests MySolutionRootFolder\Test\SomeTestProject.UnitTests\project.json"
Same issue for both the xunit and the mstest testrunner.

## Expected  behavior
The root file location when the test is running, should be the output folder .... for instance the \bin\Debug\netcoreapp1.0 folder underneath the test project.

## Actual behavior
The root folder for the test, is the folder from where the "dotnet test" was run.

This is a problem when copying test dependencies for the tests. For the full .net fw one could just copy or create files/folders in the project output folder and they were accessible to the test as it was run from there. With the current implementation, one has to take that into account when running  tests from different locations, for instance from a CI build.

## Environment data
`dotnet --info` output: 
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by pvlakshm** [comment]
This is a bug. We will fix this for MSBuild/csproj based unit tests.

**Comment by piotrpMSFT** [comment]
@pvlakshm do we expect this to land for 1.0.0-rtm?

**Comment by piotrpMSFT** [comment]
Fixed by #5426
