### ISSUE TITLE
Running an SCD on ubuntu

### ISSUE THREAD

**Issue by miladkdz** [dotnet/cli#4709]
## Steps to reproduce
1. start a new project in a new folder
```
dotnet new
```
2. restore the packages
```
dotnet restore
```
3. remove the line specifying the app is of platform type from project.json according to documentation
```
"type": "platform",
```
4. add ubuntu runtime to project.json
```
"runtimes": {    
    "ubuntu.16.04-x64": {}
  }  
```
5. run restore and publish commands
```
dotnet restore
dotnet build -r ubuntu.16.04-x64
```

## Expected  behavior
The binary file should be runnable on ubuntu.

## Actual behavior
When built on macOs, and after running file command on the binary:
```
file app-binary
```
I have this output:
```
app-binary: Mach-O 64-bit executable x86_64
```
which is the signature for mac binary and the binary won't run on linux.
when built on windows, I get this error:
```
./app-binary: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./app-binary)
```
and after installing libstdc++ package:
```
./app-binary: relocation error: ./app-binary: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003148)

Product Information:
 Version:            1.0.0-preview2-003148
 Commit SHA-1 hash:  18ca244551

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by piotrpMSFT** [comment]
Please `dotnet publish` the application after building to make it self-contained.

**Comment by blackdwarf** [comment]
As @piotrpMSFT suggested, `dotnet publish --runtime <rid>` is the command that is needed to produce an SCD. I will close this issue. @miladkdz if you still have problems, please reopen.
