### ISSUE TITLE
Default TFM define is truncated to two version digits

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#471]
If you specify a TFM with a three-digit version, we truncate it to two-digits :(. We do this in our code that is trying to work around a bug in NuGet where TFM short-names have one digit if the second digit is zero. I have a fix already, just filing a bug to track.

**Comment by davidfowl** [comment]
https://github.com/dotnet/cli/commit/b25c2743ca2cbcb925756c37ff6bfd74396bc43b
