### ISSUE TITLE
Globbing not working for project.json "includefiles"

### ISSUE THREAD

**Issue by Larswa** [dotnet/cli#4711]
## Steps to reproduce
"buildOptions": {
    "copyToOutput": {
      "includeFiles": "Credentials/*.json"
    }
  }

## Expected  behavior
On dotnet build, find and copy the .json files in the Credentials folder for the project.
As documented in the project.json documentation
https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#buildoptions

## Actual behavior
dotnet build fails with error:
dotnet : The 'includeFiles' property cannot contain wildcard characters.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
For globs use `include` instead of `includeFiles`.

**Comment by Larswa** [comment]
In that case, it is the documentation that needs to be updated.

**Comment by livarcocc** [comment]
project.json is not being actively supported anymore. Closing this issue.
