### ISSUE TITLE
BuildOptions / IncludeFiles copies folders as well

### ISSUE THREAD

**Issue by Larswa** [dotnet/cli#4713]
## Steps to reproduce
"buildOptions": {
"copyToOutput": {
"includeFiles": "Credentials/MyToken.json"
}
}

## Expected  behavior
On dotnet build, copying the MyToken.json file to the output folder
I was expecting just the file, and not the file under the folder.

## Actual behavior
Copies the entire Credentials folder with the Mytoken.json file to the output folder.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Use mapping:
```
      "mappings": {
        ".version": "../../artifacts/*/stage2/sdk/*/.version"
      }
```
Source:
https://github.com/piotrpmsft/cli/blob/rel/1.0.0/test/Microsoft.DotNet.Cli.Utils.Tests/project.json#L21

**Comment by Larswa** [comment]
Thanks!
