### ISSUE TITLE
dotnet migrate failed on test project that references library project, which was just migrated in the same solution

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#4714]
## Steps to reproduce
1. Clone the repro https://github.com/serilog/serilog-sinks-logentries.git
2. Open the solution serilog-sinks-logentries.sln in VS 2017
3. Click OK to migrate

## Expected  behavior
Success

## Actual behavior

Serilog.Sinks.Logentries.Tests

Message

 test\Serilog.Sinks.Logentries.Tests\Serilog.Sinks.Logentries.Tests.xproj: Failed to migrate XProj project Serilog.Sinks.Logentries.Tests. 'dotnet migrate -s -p "C:\github\jeremymeng\serilog-sinks-logentries\test\Serilog.Sinks.Logentries.Tests" -x "C:\github\jeremymeng\serilog-sinks-logentries\test\Serilog.Sinks.Logentries.Tests\Serilog.Sinks.Logentries.Tests.xproj"' exited with error code 1. 
 test\Serilog.Sinks.Logentries.Tests\Serilog.Sinks.Logentries.Tests.xproj: Could not find file 'C:\github\jeremymeng\serilog-sinks-logentries\src\Serilog.Sinks.Logentries\project.json'. Migration failed. 

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
Can you try migrating from the Command Line. Migration from the new VS is still a work in progress.

**Comment by jeremymeng** [comment]
Migrating from command line works.  Hit an error when running `dotnet test`
```
Test run for /home/dduser/github/serilog-sinks-logentries/test/Serilog.Sinks.Logentries.Tests/bin/Debug/netcoreapp1.0/Serilog.Sinks.Logentries.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...


Error: Could not find testhost.dll for source '/home/dduser/github/serilog-sinks-logentries/test/Serilog.Sinks.Logentries.Tests/bin/Debug/netcoreapp1.0/Serilog.Sinks.Logentries.Tests.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".
```

**Comment by piotrpMSFT** [comment]
@jeremymeng glad cmd line migrate worked.

Can you open an issue with repro for the test problem? Ideally include PJ and csproj.

**Comment by witchdrash** [comment]
@piotrpMSFT 
The order of migration is really important, because, for some reason the dotnet migrate command (and it's VS2017 equivalent) deletes the project.json immediately after it's containing project is migrated, so any project that references the project just migrated and can no longer migrate.

Fortunately when I migrated my project is was in source control so I simply reverted each project.json delete when I hit a migration error and eventually it got there.

It would be better to delete the project.json files after an entire solution has been migrated, not when an individual project has been migrated, as VS2017 seems to be bad at working out the correct order to migrate a solution.

**Comment by piotrpMSFT** [comment]
@witchdrash just run `dotnet migrate` from the root directory of the solution. So long as it has the full context it will migrate everything before cleaning up. It only cleans up when it believes it has addressed the entire closure.

Also, note it does not delete. It creates a `backup` folder where it stashes the deprecated artifacts. There is a bug, however, that the path to backup is miscalculated when running from a sub-folder of the project root.
