### ISSUE TITLE
Authors property is not migrated by `dotnet migrate`

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#4717]
## Steps to reproduce
1. Clone https://github.com/serilog/serilog-sinks-coloredconsole.git
2. Open the solution in VS 2017 RC
3. Run `.\Build.ps1` in a Powershell command prompt
4. Look at the content of the new .csproj file.  Check the generated nupkg file in .\artifacts

## Expected  behavior
Authors/Owners are set to "Serilog Contributors", same as when project.json is used

## Actual behavior
Authors property is missing from the csproj.  As a result, the nupkg has both `Authors` and `Owners` set to `Serilog.Sinks.ColoredConsole`.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by piotrpMSFT** [comment]
@livarcocc may have already opened another bug tracking this. 

https://github.com/NuGet/Home/issues/3914 is related.
