### ISSUE TITLE
Restore packages fail 1.0.0-preview4-004079

### ISSUE THREAD

**Issue by daviatorstorm** [dotnet/cli#4721]
## Steps to reproduce
dotenet new -t web
dotnet restore

## Expected  behavior
Restore packages

## Actual behavior
C:\Program Files\dotnet\sdk\1.0.0-preview4-004079\NuGet.targets(70,5): error : Unable to resolve 'Microsoft.NET.Sdk.Web (>= 1.0.0-alpha-20161104-2-112)' for '.NETCoreApp,Version=v1.0'.

## Environment data
.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
You need to add 

```
<add key="dotnet-web" value="https://dotnet.myget.org/F/dotnet-web/api/v3/index.json" />
```

to your NuGet.Config. And even though, I don't think all the packages for that template are available yet. We just published it like that so that when they do become available, the template will be correct.

**Comment by daviatorstorm** [comment]
It works.
