### ISSUE TITLE
Remove `dotnet-` prefix requirement for sdk tool

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4722]
Lots of console app are already used in existing projects, but the .net sdk tools are awesome because fix some real issues:

- xplat ready
- boostrapping (download exe before execution, to not commit binaries in repo)
- easy discoverability

Atm the package name can be anything AFAIK, but app name should have `dotnet-` prefix.
But having `dotnet-` prefix as requirement is ok for new tools (like `dotnet-watch`, `dotnet-mergenukg`) but is a friction for existing console tools, because require:

- or rename an exist and used console tool and support two versions (with or without `dotnet-`) for compatibility with others users
- or create a wrapper (slow/useless)

So can the `dotnet-` prefix requirement be removed? the tool is already specified in a special section anyway.
If the problem is recognize what dll is the executable, can be solved (at tool author side) for example with text file `.sdktoolname` inside package (maybe alognside expected directory `netcoreapp1.0`) who contains the name (it's easy add the file as content for package authors)

Some examples i can think of:

- compilers like `fsc` (f# compiler)
- build script orchestrator (fake/cake etc)
- doc generators (fsrevel)
- utilities (paket/forge)

**Comment by enricosada** [comment]
maybe is the wrong repo. i didnt understood if should go in `dotnet/sdk`. 
I'll move it if is the wrong one.

**Comment by piotrpMSFT** [comment]
@DamianEdwards

**Comment by enricosada** [comment]
@DamianEdwards sry for ping, but is to continue discussion about that before `preview5` is released 😄

**Comment by DamianEdwards** [comment]
Yeah we spoke about this way back when we first did CLI tools and I'm supportive of it. Really just a scoping question for the next release as this isn't critical to the core scenarios we have to deliver, despite it being a nice and useful feature. Will leave to @blackdwarf to follow up as the CLI PM.

**Comment by enricosada** [comment]
thx @DamianEdwards.

i think main use case for this change is to "easy add existing console app as clitool, without require a change in the name".

@blackdwarf if it's approved i can send a PR.

**Comment by piotrpMSFT** [comment]
@enricosada how are you thinking to put the tools on the path and to invoke dotnet itself?

**Comment by blackdwarf** [comment]
@piotrpMSFT asks a good question. I would like to avoid having `dotnet.dll` (so not the muxer) be a launcher of arbitrary binaries from NuGet packages/cache. 

From a conceptual perspective, I understand the desire but the whole scope of the usage is unclear to me. @enricosada you mention existing tools, which makes sense. However, if I already have the existing tool on the $PATH for whatever reason (for instance, `fsc` some previous version or similar), the semantics would change based on the directory even though the invocation would remain the same. Seems confusing to me.

Thoughts?

**Comment by dasMulli** [comment]
I think that the logic of resolving tools from the $PATH shouldn't change, but for tools referenced explicitly from the csproj, it should be fine. Considering there are already NuGet packages with tools out there and stand-alone `packages.config` files only used to restore them, this could be a quick win for their authors.

**Comment by enricosada** [comment]
@piotrpMSFT @blackdwarf in this issue I am speaking only about "tools" or `<DotnetCliToool` inside msbuild proj. 
The tools in PATH are ok with dotnet- prefix. 

But if you want also to remove prefix from others installed by `dotnet install` the easy way is to add create a directory tools and create symlink there. So `dotnet` can first search there. 
Or add the dir for global commands to PATH (like ruby does)

**Comment by piotrpMSFT** [comment]
@enricosada I'm afraid I don't get it. `dotnet` is the thing on the PATH so it gives us a hook to get into the execution path. Is your concern only that the tools inside of nuget packages not have the `dotnet-` prefix but the invocation convention is `dotnet {toolname}` nonetheless?

**Comment by enricosada** [comment]
Sorry for late reply.

Be able to use `dotnet-snippet.bat` as `dotnet snippet` (if is in `PATH`), is ok and awesome. And shouldnt change, is really nice to create simple extension.(i have bat for snippet or for create to xcopy templates) 
  
My only concern is about tools in packages defined in `DotNetCliToolReference `. Currently the package name can be anything, but my tool need to be named "dotnet-mytool" to be used like `dotnet mytool`, and it's unfortunate, because ecosystem has lots of console app who can use `DotNetCliToolReference ` to fix the boostrapping problem (download a specific version, and after run it). Change the name is annoying the tools are normal console app.

Atm i use a csproj with all my tools PER REPO in a `tools/tools.csproj`. it's useful for tools not specific of a project, but helpers (docs/codegen/aws/etc). It's restored one time, and i can use all tools easy in build script (but i need to be check the working directory, so a bit annoying)

For example i think of `fsc` compiler, or `paket`, or `fsi` or others.

Pratically i like to use tools to fix the boostrapping issue, and install per project/repo/globally useful console app.

@piotrpMSFT My questions is related also on the global/repo `install` command. 
It's not needed also for global/perRepo tools, we just need use a directory (per sdk) added to `PATH`, and:
- symlink there the `mytools.exe` from the published /path/to/installed/tools/mytool/v1/mytool.exe`
- add the bats to invoke commands, who contains like `dotnet /path/to/cache/of/mytool/v1/mytool.dll`
Like that dotnet tools installed are just normal exe/bat/sh in `PATH`. no need for `dotnet mytool`

Per repo works the same, using a `.dotnettools` subdirectory, who contains symlink/bat.
Or there the `dotnet mytool` will search the `.dotnetools` subdirectory.

**Comment by livarcocc** [comment]
I don't believe this is something we will be addressing this. We have allowed this flexibility for global tools and I suggest folks take a look at that. If that does not feel like enough, please, we would like to hear comments.
