### ISSUE TITLE
Add per repo scope to sdk tools

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4723]
The current .net cli tools are per project (csproj) and run only if the working directory is the project directy (scope per project).

But often the tools used in a repo are utilities needed at the repository level for example for build orchestration/documentation/generators/helpers/etc

My wish is to have a list of tools defined in a normal msbuild project, maybe in the root (like `$root/tools.targets` ), and these are in scope when i run commands inside a subdirectory

- `/`
  - `tools.targets` define `dotnet-mytool`
  - `src`
       - `myapp`  (if i run `dotnet mytool` there, works)

As a workaround now i can:
- or include `$root/tools.targets` in all project, but is more work on `dotnet restore`, and manual friction.
- or always specify the working directory for execution of tool and pass the path as argument to change working directory inside app.

I think there are 4 useful levels:

- machine wide: doesnt care about sdk version at all
- sdk wide: global, but depends on current sdk used
- repo wide: nor project specific, but useful for repo itself
- project specific: already exists 😄 

if is not the right repo, i'll move to `dotnet/sdk`

**Comment by piotrpMSFT** [comment]
@DamianEdwards

**Comment by livarcocc** [comment]
We have built local tools to cover this.
