### ISSUE TITLE
Migration: Content include directory hierarchy is not preserved

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#4724]
For a project.json file that has this:
"copyToOutput": {
    "include": [
        "../../TestAssets/TestProjects/AppWithToolDependency/**/*",
        "../../artifacts/*/stage2/sdk/*/.version"
    ],
    "mappings": {
        ".version": "../../artifacts/*/stage2/sdk/*/.version"
    }
}

AppWithToolDependency was copied to the output directory preserving the directory hierarchy from TestAssets, while .version was copied flag to the the output directory (not preserving the directory hierarchy). There seems to be a different behavior either because of the "mappings" entry, or because of the "**" path. We need to figure out the project.json algorithm and mimic this for csproj.

For csproj files, migration currently does this.
&lt;Content Include="..\..\TestAssets\TestProjects\AppWithToolDependency\**\*"&gt;
  &lt;CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory&gt;
  &lt;CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory&gt;
&lt;/Content&gt;
  &lt;Content Include"../../artifacts/*/stage2/sdk/*/.version"&gt;
    &lt;CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory&gt;
    &lt;CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory&gt;
&lt;/Content&gt;

Which copies the files flat (not preserving directory hierarchy). To preserve the hierarchy you can add the &lt;Link&gt; tag like this:
&lt;Link&gt;TestAssets/TestProjects/AppWithToolDependency/%(RecursiveDir)%(Filename)%(Extension)&lt;/Link&gt;

The SDK cannot change behavior because they would break existing projects. But migration should insert the &lt;Link&gt; tags where necessary so we maintain the same behavior as project.json.

**Comment by jgoshi** [comment]
Closing this bug because we are tracking this one instead:
https://github.com/NuGet/Home/issues/3953

**Comment by jgoshi** [comment]
I'm attaching sample projects.
1. TestContentPJ - Sample project.json based project
2. TestContentMsbuild - Migrated project
3. TestAppWithManualFixes.csproj - File that contains the manually added link tags that migration should add.

[Sample.zip](https://github.com/dotnet/cli/files/593106/Sample.zip)

Here is the observed project.json behavior:
1. Anything with a mapping entry specifies the (user-specified) output path. Note that migration already handles this part.
2. Anything without a mapping entry preserves directory hierarchy. Migration needs to add link tags and also needs to exclude files that have an explicit mapping entry. See TestAppWithManualFixes.csproj for more details.

**Comment by jgoshi** [comment]
Looking at this more, I don't think we should fix this. The mappings in project.json all the user to specify directory hierarchy. The implicit stuff seems like it would be a big fix. For example, given this project.json.

"copyToOutput": {
            "include": [
                "testcontentfile.txt",
                "../Content/SubDir1/SubDir2/testcontentfile.txt",
                "../Content/SubDir1/testcontentfile.txt",
                "../Content/SubDir2/testcontentfile.txt",
                "../Content/SubDir3/**/*",
                "../Content/SubDir4/**/*",
                "../Content/SubDir5/**/testcontentfile.txt"
            ],
            "mappings": {
                "dir/testcontentfile.txt": {
                    "include": "../Content/SubDir4/**/testcontentfile.txt"
                },
                "renamed.txt": "../Content/SubDir5/**/testcontentfile.txt"
            }
        }

We produce this:
&lt;Content Include="..\Content\SubDir4\**\testcontentfile.txt"&gt;
      &lt;Link>dir/testcontentfile.txt&lt;/Link&gt;
      &lt;CopyToOutputDirectory>PreserveNewest&lt;/CopyToOutputDirectory&gt;
    &lt;/Content>
    &lt;Content Include="..\Content\SubDir5\**\testcontentfile.txt"&gt;
      &lt;Link>renamed.txt&lt;/Link&gt;
      &lt;CopyToOutputDirectory&gt;PreserveNewest&lt;/CopyToOutputDirectory&gt;
    &lt;/Content>
    &lt;Content Include="testcontentfile.txt;..\Content\SubDir1\SubDir2\testcontentfile.txt;..\Content\SubDir1\testcontentfile.txt;..\Content\SubDir2\testcontentfile.txt;..\Content\SubDir3\**\*;..\Content\SubDir4\**\*"&gt;
      &lt;CopyToOutputDirectory&gt;PreserveNewest&lt;/CopyToOutputDirectory&gt;
    &lt;/Content&gt;

We would have to break up the last Content Include into multiple Content elements each with their own Link element. And project.json maps ..\Content to Content in the output directory. I guess I could specifically look for ..\ at the beginning of a path, but this seems risky.

@piotrpMSFT @livarcocc What do you think?

**Comment by livarcocc** [comment]
I always thought this was too risky. Let's not take it, specially now.

**Comment by jgoshi** [comment]
Ok, I'll move this out to 2.0.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#39
