### ISSUE TITLE
Migration: runtimeconfig.json file is not included with dotnet pack

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#4726]
I need to add something like this to the csproj file:
&lt;ItemGroup&gt;
    &lt;Content Include="$(OutputPath)\dotnet-dependency-tool-invoker.runtimeconfig.json"&gt;
        &lt;Pack>true&lt;/Pack&gt;
        &lt;PackagePath>lib\$(TargetFramework)&lt;/PackagePath&gt;
    &lt;/Content&gt;
&lt;/ItemGroup&gt;

Migration should automatically add that when needed (if the OutputType is exe or if the GenerateRuntimeConfigurationFiles property is set.

**Comment by livarcocc** [comment]
Was this being automatically included by dotnet pack in pj world? If so, why isn't the new dotnet pack including it? Seems like something that every tool will need.

**Comment by jgoshi** [comment]
Yes it was automatically included by dotnet pack in the pj world.

**Comment by livarcocc** [comment]
@rohit21agrawal Should the new pack include this file as well? Otherwise, people who write tools will have to include it in their csproj. Plus, we used to do it in PJ world. Any particular reason why we stopped?

**Comment by rohit21agrawal** [comment]
This is because the output files that are packed depend on msbuild target BuiltProjectGroupOutput. This target does not include runtimeconfig.json file in the list of output files.

**Comment by blackdwarf** [comment]
This bit me as well. We need to figure out a way to do this because otherwise any tool author out there will need to add the above to their csproj files. 

Any suggestions?

**Comment by rohit21agrawal** [comment]
@nguerrera @rainersigwald do we need to file an issue on msbuild for this? BuiltProjectGroupOutput should include runtimeconfig.json in the list of output files wherever appropriate.

**Comment by rainersigwald** [comment]
@rohit21agrawal It should be added to that item wherever it's created. Is it in core (MSBuild) targets, or in the new SDK?

**Comment by rohit21agrawal** [comment]
@rainersigwald not sure i understand your question...going to ping you on skype to discuss.

**Comment by piotrpMSFT** [comment]
@rainersigwald @rohit21agrawal did this issue get figured out? I'm not sure what we're tracking in CLI for this. Please re-open is there is something you would like us to do.
