### ISSUE TITLE
Migration: preserve cases where nuget and assembly name are different

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#4727]
In the situations where the nuget package name is different than the assembly name, migration needs to insert the &lt;PackageId&gt; property in the csproj file. When that property is set it will be used (instead of the assembly name) for the nuget package name.

**Comment by livarcocc** [comment]
How do we know that the casing differs?

**Comment by jgoshi** [comment]
Not casing differences. But cases (situations) where your assembly name is one thing but the nuget package name is something else. I think this has to do with setting outputName in pj?

**Comment by piotrpMSFT** [comment]
@jgoshi do you have a sample PJ file that replicates this scenario?

**Comment by livarcocc** [comment]
Whenever the name is set in PJ, we set that as OutputName. The packageId I believe will stay the folder name.

**Comment by jgoshi** [comment]
If you look at TestAssets\TestPackages\ToolWithOutputName\ToolWithOutputName.csproj you'll see it sets its assembly name to dotnet-tool-with-output-name. In order to get the pack to create the nugget package with name ToolWithOutputName I needed to add the PackageId property to the csproj file.

**Comment by livarcocc** [comment]
Are you saying that dotnet pack is using the assembly name to determine the package name?

**Comment by jgoshi** [comment]
Yes, unless I add PackageId, then it uses that.

**Comment by livarcocc** [comment]
@joelverhagen Is this by design? I remember that at one point we considered changing the csproj file name to change the assembly name, but we didn't because that's what was being used for the package.

Did that change?

**Comment by joelverhagen** [comment]
We default `$(PackageId)` MSBuild property to `$(AssemblyName)`. Not sure how `$(AssemblyName)` is defaulted but empirically that seems to be the .csproj file name without file extension. We then use `$(PackageId)` in restore (apparent in the lock file) and pack (apparent in the `<id>` and file name of the produced .nupkg).

**Comment by livarcocc** [comment]
thanks @joelverhagen. I guess we have a choice to make here. So, should we always emit the PackageId to the folder name when we emit the AssemblyName based on the output name?

This will mean that the dll will match the assembly name and the package will match the folder name. I believe this will maintain the PJ behavior, as @jgoshi suggests.

@piotrpMSFT, any concerns?

**Comment by joelverhagen** [comment]
> So, should we always emit the PackageId to the folder name when we emit the AssemblyName based on the output name?

Correct. The logic of defaulting `$(PackageId)` to `$(AssemblyName)` will yield the wrong result in that case.
