### ISSUE TITLE
Exception is being thrown in when trying to run 'dotnet run --help'

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#473]
I wanted to find out the options available for the `run` command so was trying 'dotnet run --help'

**Comment by brthor** [comment]
Hi @kichalla Thanks for the report. Can you post the exception and what platform you are on?

**Comment by kichalla** [comment]
I am on Windows 10 and I do not have the symbols for coreclr to give you the exception details...where can find the symbols?

**Comment by brthor** [comment]
I'm not sure actually. Could always build it out of the coreclr repo :smile: 

What about just posting the error though?

**Comment by livarcocc** [comment]
This is the same issue I fixed for compiler csc and compiler native. I will look into it.

**Comment by livarcocc** [comment]
Resolved by 64946cf7d75b9143020ea0b69ef4d04e683abd00
