### ISSUE TITLE
CLI should automatically run restore for commands that need it. Like pack, build and publish.

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/cli#4730]
## Steps to reproduce

1) Create a .NET Core application (with preview3+ so you can use csproj, not project.json)
2) `dotnet pack`
3) Observer error

## Expected  behavior

A `.nupkg` is created alongside the `.csproj` (or in the directory specified by -o|--output).

## Actual behavior

`error MSB4057: The target "pack" does not exist in the project.`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004081)

Product Information:
 Version:            1.0.0-preview4-004081
 Commit SHA-1 hash:  6d57ca7e14

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

## Other
The project I observed this in: https://github.com/Phrohdoh/CoreFire/blob/4861f73c43460377122f0d1f0280e7ea7d809e6e/src/CoreFire/CoreFire.csproj

**Comment by livarcocc** [comment]
You need to restore first, to bring down the Pack target. Run dotnet restore and then try dotnet pack.

**Comment by dasMulli** [comment]
@livarcocc on the automatic restore: could the `MSB4057` be mapped to a more helpful error message when invoked through msbuild forwarding commands?

**Comment by livarcocc** [comment]
Possible, I guess. It would help when running something like dotnet msbuild /t:Pack.

**Comment by MattGertz** [comment]
@livarcocc Would it be an existing but different error message or a new one?  Note we are getting close to loc freeze (as we work to move all of the strings to resources), so there is a limited two-week window for a while for any new ones.

**Comment by piotrpMSFT** [comment]
#2199 is related
