### ISSUE TITLE
dotnet test failed to find testhost.dll after migration

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#4734]
## Steps to reproduce
1. git clone https://github.com/serilog/serilog-sinks-logentries.git
2. git checkout d7e9975b3b8c99393b5b8dda0b46372544a0dc73
3. dotnet migrate ./global.json
4. cd test/Serilog.Sinks.Logentries.Tests/
5. dotnet restore
6. dotnet test

## Expected  behavior
No errors.
(Expected: zero tests run since this is an empty test project.)

## Actual behavior
```
Test run for /home/dduser/github/serilog-sinks-logentries/test/Serilog.Sinks.Logentries.Tests/bin/Debug/netcoreapp1.0/Serilog.Sinks.Logentries.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Error: Could not find testhost.dll for source '/home/dduser/github/serilog-sinks-logentries/test/Serilog.Sinks.Logentries.Tests/bin/Debug/netcoreapp1.0/Serilog.Sinks.Logentries.Tests.dll'. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost".


Starting test execution, please wait...
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
```

**Comment by AFimin** [comment]
Hallo,
I'm experiencing same errors.

dotnet --info output:

.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by AFimin** [comment]
Hey @jeremymeng 

Don't know if this will help you. 
But I workaround this issue by this:
1) yo aspnet -> choose console application C#
2) cd to proj directory
3) dotnet migrate
4) add packages: xunit, Microsoft.TestPlatform.TestHost, xunit.runner.visualstudio
5) dotnet restore
6) dotnet build
7) dotnet test

--> output now
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed   someTests.MegaTest.TTT
Error Message:
 System.InvalidOperationException : [Fact] methods are not allowed to have parameters. Did you mean to use [Theory]?


Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.2872 Seconds

**Comment by piotrpMSFT** [comment]
#4696 is related
