### ISSUE TITLE
Migrated Empty Web App on Full Framework Fails to Build

### ISSUE THREAD

**Issue by bzhu94** [dotnet/cli#4736]
## Steps to reproduce
1.Clean Win10 x64 ENU machine
2.Install Dev15 RC from (select .NET Core workload only) :
\\cpvsbuild\drops\VS\d15prerel\products\25913.00\bootstrappers\Enterprise
3. Download the ZIP of the repo https://github.com/balaTest/ProjectKTestProjects.git (
4. Extract the ZIP, then copy Tooling
4. In command prompt, cd into AspNetCoreWeb_OnNet452_Empty_1.
5. Run "dotnet migrate"
6. cd into \src\AspNetCoreWeb_OnNet452_Empty_1
7. Run "dotnet restore"
8. Run "dotnet build"

## Expected  behavior

The build succeeds without any issues.

## Actual behavior

The build fails with the following error:

![image](https://cloud.githubusercontent.com/assets/8541576/20329723/e5d16772-ab4e-11e6-9999-d9a890ad1014.png)

**[This](https://github.com/dotnet/cli/files/593440/EmptyOnFullCLIMigrateLogMessages.txt) is the entire console output.**

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/4689.
