### ISSUE TITLE
Migration: Delete .xproj.user file

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#4739]
## Steps to reproduce
* Have a pj/xproj solution you have worked on in VS
   * Alt: Forget a proper gitignore and end up with *.user files in your source control.
* Run `dotnet migrate`

## Expected  behavior
Only a csproj file in project folder.

## Actual behavior
There is a leftover `.xproj.user` file in the directory

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by piotrpMSFT** [comment]
Sure, we can move this one to backup as well.
