### ISSUE TITLE
Incorrect version of System.Private.CoreLib is loading in .net core

### ISSUE THREAD

**Issue by SamvelS** [dotnet/cli#4742]
## Steps to reproduce
I am using 1.0.0-preview4-004079 version of .net core.
Trying to use `IsInterface` property of `Type`. If I am correct it is located in `System.Private.CoreLib` DLL.
Using ILSpy I can see that  `IsInterface` property is available. I've checked with `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.3\System.Private.CoreLib.dll`.
Other types such as ones in `System.Collections.Specialized.dll` are loading correctly.

I am getting this error during build: 

> error CS1061: 'Type' does not contain a definition for 'IsInterface' and no extension method 'IsInterface' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004079)

Product Information:
 Version:            1.0.0-preview4-004079
 Commit SHA-1 hash:  43dfa6b8ba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
Can you share your CSProj and how you are executing your application?

**Comment by SamvelS** [comment]
@livarcocc 
My csproj file is what was generated by default.
Just try to call IsInterface on any Type instance.
I am building by command line

**Comment by piotrpMSFT** [comment]
I checked the CoreFx repo and found that IsInterface hangs off of TypeInfo, not type:
https://github.com/dotnet/corefx/blob/ce4f75ffa1abf74c6b7a59c93acf23ac5b8b3b1b/src/System.Linq.Expressions/src/System/Dynamic/Utils/TypeUtils.cs#L199

I was able to use this knowledge to generate a working sample in the manner @SamvelS describes. Here is the Main which calls IsInterface:

```
using System;

using System.Reflection;

class Program
{
    static void Main(string[] args)
    {
        var foo = 1;

        var isInterface = foo.GetType().GetTypeInfo().IsInterface;

        Console.WriteLine("Hello World!");
    }
}
```

**Comment by SamvelS** [comment]
Calling `GetTypeInfo().IsInterface` instead of `IsInterface` solved that problem.
But System.Private.CoreLib.dll (C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1 or 1.0.3) which is referenced form mscorlib.dll has `Type` which has `IsInterface`. Also there is `AppDomain` which is missing in my case.
Can I somehow force my app to use DLLs from that path as I need `AppDomain` as well?
I am trying to port .Net project to .Net Core.

**Comment by piotrpMSFT** [comment]
Excellent question for https://github.com/dotnet/corefx repo. CLI just does what the CoreFx nupkg's tell it to :D
