### ISSUE TITLE
dotnet test fails due to missing quotes in the call to dotnet exec

### ISSUE THREAD

**Issue by chausner** [dotnet/cli#4744]
## Steps to reproduce
Create a new, empty xUnit project and attempt to run it:
```
dotnet new -t Xunittest
dotnet restore
dotnet test
```

## Expected  behavior
Test should complete with zero passing and zero failing tests.

## Actual behavior
`dotnet test` outputs:

> Test run for c:\Users\chris\Desktop\test\bin\Debug\netcoreapp1.0\test.dll(.NETCoreApp,Version=v1.0)
> dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'

Process Monitor shows that `dotnet test` fails to quote the path to vstest.console.dll when running `dotnet exec` internally:

> "dotnet" exec C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\vstest.console.dll --framework:".NETCoreApp,Version=v1.0" "c:\Users\chris\Desktop\test\bin\Debug\netcoreapp1.0\test.dll"

Running the command by hand with the path correctly quoted, runs the tests successfully.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.0-preview3-004056)
> 
> Product Information:
>  Version:            1.0.0-preview3-004056
>  Commit SHA-1 hash:  ccc4968bc3
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64

**Comment by thinktainer** [comment]
Seeing the same behaviour in win81-x64:
`dotnet --info`

> .NET Command Line Tools (1.0.0-preview3-004056)
> 
> Product Information:
>  Version:            1.0.0-preview3-004056
>  Commit SHA-1 hash:  ccc4968bc3
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.3.9600
>  OS Platform: Windows
>  RID:         win81-x64

**Comment by piotrpMSFT** [comment]
Thanks folks. The `test` repo isn't public yet, but I'm moving the bug over there. Once the repo is open, issue 231 is what we're tracking. Leaving CLI copy open until that repo is public.

@harshjain2 @Faizan2304

**Comment by piotrpMSFT** [comment]
The Test team followed up with me and pointed out that this should already be fixed in the preview4 nightlies. Can you try the latest installer from https://github.com/dotnet/cli [there is a big table of installer links if you scroll down] and see if this is still an issue?

**Comment by chausner** [comment]
Thanks Piotr, I can confirm that it is fixed for 1.0.0-preview4-004079.
