### ISSUE TITLE
Eliminate cyclic dependencies in CLI [Utils <-- EF Tools <-- templates]

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4745]

**Comment by natemcmaster** [comment]
FWIW I'm made some progress on this for dotnet-watch by removing dependency on Utils altogether. dotnet-user-secrets (aspnet/DotNetTools) will follow soon. dotnet-ef (aspnet/EntityFramework.Tools), and dotnet-aspnet-codegenerator (aspnet/Scaffolding) still have a dependency on Cli.Utils

**Comment by piotrpMSFT** [comment]
@natemcmaster do you have plans to eliminate all of these dependencies? What are you doing instead?

**Comment by natemcmaster** [comment]
You might consider splitting Cli.Utils, as it has become sort of a grab back of APIs. I see basically three distinct groups of APIs in this library:

1. Utilities for command line apps in general (e.g. ArgumentEscaper, StreamForwarding, Reporter, AnsiColors)
1. Utilities for dotnet-CLI's build in commands. (e.g. CommandResolution, CoreHost, PerfTracing, most of the Constants)
1. Abstractions for CLI tool authors to integrate better with CLI (e.g. MuxerPath, CommandContext.Variables.Verbose, Command.CreateDotNet)

For APIs in group 1---I'm working towards adding replacement APIs to Microsoft.Extensions.CommandLineUtils.
APIs in group 2---could be 'internal'...our tools don't really use them.
APIs in group 3---not sure how the break the cycle here.

I'm planning to eliminate the dependency from dotnet-user-secrets as well. It's really only using APIs in group 1. Not sure about the other tools... @bricelam @prafullbhosale ?

**Comment by piotrpMSFT** [comment]
For Group 3 we may need to move to an explicit LKG model. These APIs are fairly well baked at the moment.

**Comment by bricelam** [comment]
I'm also removing the dependency on Utils in dotnet-ef.

**Comment by natemcmaster** [comment]
IIRC aspnet/Scaffolding is the only tool still using ProjectDependenciesCommandFactory. dotnet-ef moved away from this API and dotnet-razor-tooling isn't being ported to msbuild.

**Comment by natemcmaster** [comment]
....(premature form submit).
... but I believe aspnet/Scaffolding has looked into removing this usage as well. cc @prafullbhosale

**Comment by livarcocc** [comment]
@prafullbhosale Any news on whether you moved away from ProjectDependenciesCommandFactory or not? Or better yet, from Cli.Utils?

**Comment by prafullbhosale** [comment]
Haven't started looking into it yet. 
Will update once I have made some progress.

**Comment by piotrpMSFT** [comment]
@livarcocc confirmed there are no remaining cyclic dependencies in the CLI product. This issue is now tracking ensuring that they don't sneak back in, which @livarcocc will do with a simple test.
