### ISSUE TITLE
CSProj & SLN CRUD Commands

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/cli#4746]
This is a tracking issue

### csproj manipulation
 - [x] `dotnet add p2p`
 - [x] `dotnet add package`
 - [x] `dotnet remove p2p`
 - [x] `dotnet remove package`
 - [x] `dotnet list p2ps`
 - [ ] `dotnet list packages`

### sln manipuliation
 - [x] `dotnet add project`
 - [x] `dotnet remove project`
 - [x] `dotnet list projects`

**Comment by blackdwarf** [comment]
Relevant for #4521 and #4513

**Comment by muratg** [comment]
Nice!

**Comment by natemcmaster** [comment]
Would it also be possible to support global-static properties?
```
dotnet add property ...
```
Example:
```
dotnet add property WarningsAsErrors true
dotnet add property UserSecretsId "abc123"
```
Can open a separate issue if this is beyond the scope of what you're trying to accomplish here.

**Comment by blackdwarf** [comment]
@natemcmaster a separate issue would be good, yes. Please provide as much details as you can and cc me. Thanks!

**Comment by natemcmaster** [comment]
Opened that request here: https://github.com/dotnet/cli/issues/5300

**Comment by piotrpMSFT** [comment]
@rrelyea when do we expect list package to land?

**Comment by ektrah** [comment]
Will `dotnet add package` be able to add `<DotNetCliToolReference` references to a project? If not, would it make sense to add `dotnet add tool` / `dotnet remove tool` / `dotnet list tools` commands?

**Comment by blackdwarf** [comment]
@ektrah not in this version. Your suggestion is something that has come up, and it is on our backlog.

**Comment by piotrpMSFT** [comment]
@blackdwarf @rrelyea do we expect `list packages` to land for 1.0.0 rtm?

**Comment by blackdwarf** [comment]
@piotrpMSFT I would like that very much.

**Comment by blackdwarf** [comment]
Unfortunately, it seems that this will not land in 1.0.0, so moving to 2.0.0 milestone.

**Comment by Jonathan34** [comment]
you are missing the `dotnet create my.sln` command to create everything from command line

**Comment by livarcocc** [comment]
@Jonathan34 there is a dotnet new sln.

**Comment by livarcocc** [comment]
cc @richlander @KathleenDollard another NuGet ask:

dotnet list packages

**Comment by livarcocc** [comment]
dotnet list packages has been implemented.
