### ISSUE TITLE
Update all packages on webapi project crashes vs2017

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#4749]
## Steps to reproduce
Open existing solution with api, web, core project
Using the ui, manage packages for solution, updates, select all, update.

## Expected  behavior
restore all packages.

## Actual behavior
Update all solution packages to 1.1 via nuget package restore hangs and crashes vs2017
Update all api packages to 1.1 via nuget package restore hangs and crashes vs2017
Update all web packages to 1.1 via nuget package restore hangs and crashes vs2017
Update all core packages to 1.1 via nuget package restore works ok.

## Environment data
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

![image](https://cloud.githubusercontent.com/assets/3386797/20368939/180323e8-ac35-11e6-808a-ea073d739e97.png)

**Comment by Bartmax** [comment]
doing it in batches of 5 per update worked fine.

**Comment by piotrpMSFT** [comment]
Moved to NuGet repo
