### ISSUE TITLE
annoying dependency mismatch Microsoft.NET.Sdk.Web

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#4751]
after i migrated with lots of problems a solution i keep getting this information message

![image](https://cloud.githubusercontent.com/assets/3386797/20369477/e996e97e-ac37-11e6-9ba4-dab9ed2aa16c.png)

Dependency specified was Microsoft.NET.Sdk.Web (>= 1.0.0-alpha-20161104-2) but ended up with Microsoft.NET.Sdk.Web 1.0.0-alpha-20161104-2-112.

**Comment by daviatorstorm** [comment]
Add NuGet.config file to project root directory with the next text insde
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
then do `dotnet restore ` and `dotnet run`

**Comment by Bartmax** [comment]
@daviatorstorm im using 1.1 and 2017rc. I don't want to use nightly build.

**Comment by daviatorstorm** [comment]
Apparently, you cannot use that dependency :smile:
As i testing VS 2017 RC it uses last installed dotnet sdk. The best solution for your task, I think, use VS 2015.

**Comment by dasMulli** [comment]
I think the -2-112 package was fixed in the template post-release..
New versions seem to be pushed to the [`dotnet-web` feed](https://dotnet.myget.org/gallery/dotnet-web).

**Comment by GuardRex** [comment]
Hit this, too, @bartmax. I solved it by going wildcard on the package ...
```
<PackageReference Include="Microsoft.NET.Sdk">
  <Version>1.0.0-*</Version>
  <PrivateAssets>All</PrivateAssets>
</PackageReference>
<PackageReference Include="Microsoft.NET.Sdk.Web">
  <Version>1.0.0-*</Version>
  <PrivateAssets>All</PrivateAssets>
</PackageReference>
```

**Comment by piotrpMSFT** [comment]
@livarcocc FYI

Oi... migration adds a whole new dimension to "The impact of taking one more fix before locking things down for realz" :-/

@GuardRex I strongly discourage * dependencies. The good thing is they're magical. The bad thing is they're... magical.

@Bartmax please update your csproj file to the 112 version number. Other folks as well.

Leaving this open to fix up release process to account for these hard-coded versions.

**Comment by GuardRex** [comment]
Hardcoding that package tho results in this for me ...
```
Errors in <PATH>\testselfcontained\testselfcontained.csproj
      Unable to resolve 'Microsoft.NET.Sdk (>= 1.0.0-alpha-20161104-2-112)' for 
      '.NETCoreApp,Version=v1.1'.
```

**Comment by GuardRex** [comment]
Maybe a little :sparkles: magic :sparkles: isn't such a bad thing. :smile:

**Comment by piotrpMSFT** [comment]
Restore fails to find the thing it... restores...

Something is fishy here. @rrelyea any ideas?

:EmotionFeltWhenCantFindGuardRex'sEmoji:

**Comment by piotrpMSFT** [comment]
With the introduction of the Sdk attribute, the version of the SDK is now included in the CLI/VS itself and not expressed by migration in the project file. #4916
