### ISSUE TITLE
Weird folder error after migration on vs 2017 rc

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#4752]
this happened on a test project and and mvc project.

![image](https://cloud.githubusercontent.com/assets/3386797/20369512/1c96ee64-ac38-11e6-83a7-6b5fb3da7c15.png)

csproj file:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>ProjectName.Test</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
    <EmbeddedResource Include="compiler\resources\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk">
      <Version>15.0.0-preview-20161024-02</Version>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio">
      <Version>2.2.0-beta4-build1194</Version>
    </PackageReference>
    <PackageReference Include="xunit">
      <Version>2.2.0-beta4-build3444</Version>
    </PackageReference>
    <PackageReference Include="dotnet-test-xunit">
      <Version>2.2.0-preview2-build1029</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.1.0</Version>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by dmirmilshteyn** [comment]
I've been able to get around this by removing:
```
<PackageReference Include="dotnet-test-xunit">
  <Version>2.2.0-preview2-build1029</Version>
</PackageReference>
```
as per #4640

**Comment by Bartmax** [comment]
@dmirmilshteyn unfortunately, i don't have that. :(

**Comment by piotrpMSFT** [comment]
This is a packaging issue in diasmreader where the dll is being pulled in as a content file and the new Globbing feature in the VS UI is displaying the full relative path as best as it can. If anyone has wondered what `../` looks like in a tree view... there it is :)

I'm going to close the issue since it's really by-design given the package's authoring, but hope @tmat and @srivatsn can share some thoughts on how we'll handle this in the future.

**Comment by Bartmax** [comment]
is there any workaround or is something that should be fixed on the ide?

**Comment by piotrpMSFT** [comment]
I believe the IDE is doing the right thing since that Content element is being added to the context of the project. It's a thing that should be fixed in the package. @srivatsn is the right person to comment on the final resolution.

**Comment by srivatsn** [comment]
Yes the IDE is just trying to display the items in the project. The package should be fixed to not include such items. I can't think of any good workarounds. You can add `<Content Remove="path to that file" /> to your project and it will go away but then that file won't get copied to output which is need for runtime. You could maybe then write a target that copies the file to outputpath as well.

**Comment by piotrpMSFT** [comment]
fixed a markdown error in the previous comment
