### ISSUE TITLE
project.lock.json isn't moved out of root folder.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#4753]
## Steps to reproduce
migrate project/solution

## Expected  behavior
all files from previous version that aren't used anymore should be moved into backup folder

## Actual behavior
xproj.user and project.lock.json aren't moved

**Comment by piotrpMSFT** [comment]
xproj.user got fixed last night with #4741 

Updating title to track project.lock.json

**Comment by GuardRex** [comment]
Adding `dotnet migrate` to make this issue discoverable in GH issue search.

**Comment by piotrpMSFT** [comment]
On the priority of this: project.lock.json was always a transient file that should not be in folk's source control systems. If it is, that should be fixed. Cleaning one's repo/enlistment will remove project.lock.json's [unlike project.json, *.xproj]. We'll fix this if there are spare cycles, but it's a low-priority issue at the moment.

**Comment by GuardRex** [comment]
That's cool, but it isn't even a one liner ... https://github.com/GuardRex/cli/blob/guardrex/migration-tool-mod/src/dotnet/commands/dotnet-migrate/MigrateCommand.cs#L153
