### ISSUE TITLE
editing csproj is VERY painfull

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#4754]
## Steps to reproduce
Edit csproj file

## Expected  behavior
good experience

## Actual behavior
**xml warning everywhere**
![image](https://cloud.githubusercontent.com/assets/3386797/20369684/3f72d92e-ac39-11e6-8aa8-1ec42ae6ad15.png)

![image](https://cloud.githubusercontent.com/assets/3386797/20369701/5f935bde-ac39-11e6-9fd7-eb9b3f7352aa.png)

**no intellisense**
![image](https://cloud.githubusercontent.com/assets/3386797/20369725/75f7aa7e-ac39-11e6-9811-f91e4752c659.png)

imposible to discover options, everything is magic strings

etc,etc,etc.

**Comment by piotrpMSFT** [comment]
@MattGertz FYI. Not much we can do here in the CLI, but it's an experience that needs to be improved for sure...

**Comment by mauricew** [comment]
I've got a solution just for tag completion and removal of the warnings, involves adding a bit of extra XML schema.
https://git.io/vX7uW

**Comment by piotrpMSFT** [comment]
@srivatsn regarding the proposal from @mauricew

**Comment by srivatsn** [comment]
Thanks @mauricew. The actual msbuild schema is [here](https://github.com/Microsoft/msbuild/blob/master/src/XMakeCommandLine/Microsoft.Build.CommonTypes.xsd). We've recently [updated it](https://github.com/Microsoft/msbuild/pull/1347) to add PackageReference and TargetFramework but you have more things additions in your schema which are useful. Feel free to send a PR directly to the msbuild repo. If you won't have the time for it, let us know and we can update it.

**Comment by mauricew** [comment]
Great, I'll have a branch up soon, while adjusting a few things to more closely match official documentation style.

**Comment by livarcocc** [comment]
Closing since we have improved the schema a while back and this isn't the right repo to track VS experience improvements.
