### ISSUE TITLE
migration failed with no helpful error messages

### ISSUE THREAD

**Issue by Bartmax** [dotnet/cli#4755]
## Steps to reproduce
open project.json file on vs2017rc

## Expected  behavior
migrate sucessfully

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/3386797/20370159/ee2dbed2-ac3b-11e6-859e-5b6ddef0c5a8.png)

trying to run the command manually:
![image](https://cloud.githubusercontent.com/assets/3386797/20370192/26501134-ac3c-11e6-87fa-70fe3864b85e.png)

removing the -p switch:
![image](https://cloud.githubusercontent.com/assets/3386797/20370224/50b46718-ac3c-11e6-8c76-cdff2ddaadd2.png)

deleting the `runtimeconfig.template.json` file and running the command again:

![image](https://cloud.githubusercontent.com/assets/3386797/20370333/f52a82aa-ac3c-11e6-9840-9ef7a15e08c7.png)

## Environment data
C:\>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by Bartmax** [comment]
in my case was solved by removing the `prepare` command on `scripts` section

**Comment by piotrpMSFT** [comment]
FYI the command line migration experience is significantly further ahead than the IDE integration. If you see migration errors in VS:
- revert
- go to the solution root directory in the command windows
- `dotnet migrate`

**Comment by Bartmax** [comment]
I think you should track the error when having not expected things like `prepare` on the `scripts` section. because neither command line or ide was able to migrate properly.

**Comment by piotrpMSFT** [comment]
Did the command line not notify you that `prepare` is no longer supported? It's not an error to be resolved.

**Comment by livarcocc** [comment]
We are now giving you this error message:
```
Project prepare migration failed (/Users/livarcocc/Documents/git/temp/prepare)
MIGRATE1019::Unsupported Script Event Hook: prepare is an unsupported script event hook for project migration
```

So, I will close this bug in favor of https://github.com/dotnet/cli/issues/4166
