### ISSUE TITLE
dotnet migrate puts the backup project.json file for project to project dependencies in the wrong place.

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#4757]
## Steps to reproduce
1. Create two project.json based projects where one depends on the other via project to project reference.
2. dotnet migrate the root package.
3. Look in the directory of the root package and you'll have a directory with the name of the leaf project that contains its project.json rather than it being in the backup directory of the leaf project directory.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

**Comment by brianrob** [comment]
cc: @piotrpMSFT

**Comment by piotrpMSFT** [comment]
Such a fun bug :D oi, those relative paths...
