### ISSUE TITLE
published app requires DOTNET_HOME

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#476]

**Comment by brthor** [comment]
This shouldn't be true if you have installed one of the native installers.

**Comment by blackdwarf** [comment]
@krwq can you give repro steps? Is it that if I publish the app and then run it on another machine that doesn't have the CLI installed I still have to set DOTNET_HOME?

**Comment by piotrpMSFT** [comment]
@krwq can you include the console output & env vars from the machine where this repros?

**Comment by blackdwarf** [comment]
@krwq can you please change your reference to the shared lib and validate if it repros still? If yes, please reopen.
