### ISSUE TITLE
Fresh Mac Install: "The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found."

### ISSUE THREAD

**Issue by glenn-barnett** [dotnet/cli#4760]
## Steps to reproduce

I'm a first-timer; just installed dotnet-dev-osx-x64.1.0.0-preview2-1-003177.pkg

The hello world sequence worked fine - I ran into problems setting up a webapp via https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-create-web-app-using-vscode

If i do the `dotnet build` or `dotnet ef ...` steps, I get the following output:

<code>The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
</code>

I think the "fix" is for me to trace through project.lock.json, hunt down all the dependencies with NETCore.App 1.0.0 dependencies, and try to modify them to use a newer dependency version.  Still, it's a bit of a downer in the new user onboarding experience, so I'm reporting it here.

## Expected  behavior

dotnet ef and dotnet run commands work without issue

## Actual behavior

<code>The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
</code>

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by glenn-barnett** [comment]
Installing .NET Core 1.0.1 SDK (package) fixed my issue - the problem seems to be the Yeoman templates (`yo aspnet`) are not yet ready for 1.1.0

**Comment by piotrpMSFT** [comment]
Thanks for following up :)

**Comment by kimbaudi** [comment]
The problem isn't the Yeoman template (`yo aspnet`). In fact, it is ready for 1.1.0. I think the issue is that you need to update your .NET Core SDK to version 1.1 (https://www.microsoft.com/net/core#macos), which is the current version.

**Comment by glenn-barnett** [comment]
.NET Core 1.1 was the first thing I installed - on 11/16, which was the day it was released (https://github.com/dotnet/core/releases).  This was my first time trying .NET core.

I encountered the issue described with 1.1.  When I additionally installed 1.01, and reran the dotnet cli commands, things worked properly.

**Comment by threenine** [comment]
Just thought I would add.  I had this same issue.
I did not install .NET Core 1.01

All I did to get this working on my Mac with .NET Core 1.1. is right click on the project file in the Solution Explorer and **Update Nuget Packages** and I was then able to run the application

**Comment by verlyn-texas** [comment]
+1 on threenine's solution.  Update Nuget Packages worked for me as well.

**Comment by VictorHaine** [comment]
I had this same issue, but with visual studio for mac! When I tried to debug it outputs this:
`The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.1.0
  - Alternatively, install the framework version '1.0.1'.`

To fix it, I just needed to update my nugget packages.
Menu Project > Update Nuget Packages

**Comment by KassPerf** [comment]
thanks threenine
I have the same issue 
All i've done is rebooting my mac after installing .NET Core 1.1 + updating Nuget Packages and here we go

**Comment by rubens-senday** [comment]
thanks three nine

Update Nuget Packages worked for me too.

**Comment by glenn-barnett** [comment]
Hey all - I'm hitting this issue again with an install on a new mac.

Where are you seeing the Update Nuget Packages option?

I can't find it in VS Code's menus or command palette.  I only have the ".Net Core Project Manager" extension installed.

**Comment by threenine** [comment]
Try right click in the solution explorer

**Comment by rubens-senday** [comment]
Visual Studio Menu Bar => Project => Update Nuget Packages

**Comment by glenn-barnett** [comment]
So I'm using VS Code - I just have an "Explorer" window, and right-clicking the individual files doesn't present the option.

Sounds like I need to try Visual Studio for Mac?

**Comment by rubens-senday** [comment]
I've never tried coding with VSCode. But there's a tutorial creating a simple web project thru the command line. Check the link below.

https://docs.microsoft.com/en-us/aspnet/core/getting-started

**Comment by dathanb** [comment]
I'm also seeing this problem on macOS Sierra 10.12.2. AFAICT from looking in the project.json, it just seems like the preview versions aren't synced -- I installed the 1.1 preview, but the `dotnet new -t web` template generates a project.json with lots of dependencies that look like `"version": "1.0.0-preview2-final"`. From examining the package.json, it looks like those, naturally, have a dependency on NETCore.App 1.0.0. If I change those dependencies to `1.1.0-preview4-final`, it restores cleanly, and I get a new error: `No executable found matching command "dotnet-ef"` 

So I eventually uninstalled 1.1.0 and installed 1.0.3 instead, and it just works. So I ran `dotnet -v ef database update`, and I get
```
Telemetry is: Enabled
Running /usr/local/share/dotnet/dotnet exec --depsfile /Users/dathan/.nuget/packages/.tools/Microsoft.EntityFrameworkCore.Tools/1.0.0-preview2-final/netcoreapp1.0/Microsoft.EntityFrameworkCore.Tools.deps.json --additionalprobingpath /Users/dathan/.nuget/packages /Users/dathan/.nuget/packages/Microsoft.EntityFrameworkCore.Tools/1.0.0-preview2-final/lib/netcoreapp1.0/dotnet-ef.dll database update
Process ID: 42467
Using target project 'mvc'.
Using startup project 'mvc'.
Using framework 'netcoreapp1.0'.
Using configuration 'Debug'.
Running /usr/local/share/dotnet/dotnet build /Users/dathan/dev/personal/mvc/project.json --configuration Debug --framework netcoreapp1.0
Process ID: 42469
Project mvc (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Setting the data directory to '/Users/dathan/dev/personal/mvc/bin/Debug/netcoreapp1.0/'.
Invoking dependency command 'Microsoft.EntityFrameworkCore.Design' in project 'mvc'
Running /usr/local/share/dotnet/dotnet exec --runtimeconfig /Users/dathan/dev/personal/mvc/bin/Debug/netcoreapp1.0/mvc.runtimeconfig.json --depsfile /Users/dathan/dev/personal/mvc/bin/Debug/netcoreapp1.0/mvc.deps.json --additionalprobingpath /Users/dathan/.nuget/packages /Users/dathan/.nuget/packages/Microsoft.EntityFrameworkCore.Design/1.0.0-preview2-final/lib/netcoreapp1.0/Microsoft.EntityFrameworkCore.Design.dll --assembly /Users/dathan/dev/personal/mvc/bin/Debug/netcoreapp1.0/mvc.dll --startup-assembly /Users/dathan/dev/personal/mvc/bin/Debug/netcoreapp1.0/mvc.dll --dispatcher-version 1.0.0-preview2-21431 --data-dir /Users/dathan/dev/personal/mvc/bin/Debug/netcoreapp1.0/ --project-dir /Users/dathan/dev/personal/mvc --content-root-path /Users/dathan/dev/personal/mvc --root-namespace mvc --verbose database update
Process ID: 42470
Finding DbContext classes...
Using context 'ApplicationDbContext'.
Done.
```

So I uninstalled 1.0.3 and reinstalled 1.1.0, ran `dotnet restore`, and `dotnet -v ef database update`, and I get similar, but with the error:
```
Telemetry is: Enabled
Running /usr/local/share/dotnet/dotnet exec --depsfile /Users/dathan/.nuget/packages/.tools/Microsoft.EntityFrameworkCore.Tools/1.0.0-preview2-final/netcoreapp1.0/Microsoft.EntityFrameworkCore.Tools.deps.json --additionalprobingpath /Users/dathan/.nuget/packages /Users/dathan/.nuget/packages/Microsoft.EntityFrameworkCore.Tools/1.0.0-preview2-final/lib/netcoreapp1.0/dotnet-ef.dll database update
Process ID: 47327
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/local/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
```

So I updated the version numbers as I described earlier, including bumping dependencies to 1.1.0 whenever I got an error about downgraded dependencies, ran `dotnet restore` again, and `dotnet -v ef database update` now gives
```
Telemetry is: Enabled
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-ef"
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
And sure enough, if I go to `/Users/dathan/.nuget/packages/Microsoft.EntityFrameworkCore.Tools/1.1.0-preview4-final/lib`, there is no `netcoreapp1.1` directory, and no EF tooling DLL's.

Seems like the 1.1 preview is still kinda broken in this regard -- both the generator and the dependencies.

**Comment by twinhype** [comment]
glenn-barnet, I have the exact same issue on a Mac OS Sierra. Right clicking on a file gives no option to update Nuget packages. Did you resolve it yet? Or is there a way to do it manually from the command line?

**Comment by twinhype** [comment]
I managed to resolve it by manually editing the project.json file and changing the versions in dependencies and frameworks to 1.1.0. After doing that I was prompted to do a restore, after which it updated the packages and dependencies and rewrote the project.lock.json file. The project now compiles and runs successfully.

**Comment by ebraminio** [comment]
Mac user here also, this probably can take trophy of worst solution ever, but at least, made entityframework command use possible for me after several failed tries, including use `nuget update` package.json, which it seems, it is [not support yet](https://github.com/NuGet/Home/issues/2776),

`cd /usr/local/share/dotnet/shared/Microsoft.NETCore.App/; sudo ln -s 1.1.0 1.0.0`

**Comment by kimbaudi** [comment]
@ebraminio - What version of ASP.NET CLI have you installed (`dotnet --version`)? I'm guessing you have version 1.1.0. The most likely problem is that your `global.json` and `project.json` files have `1.0.0` or `1.0.1` instead of `1.1.0`. Can you post `global.json` and `package.json`? Also, since you mention using `nuget update` are you using Visual Studio for Mac preview?

**Comment by ebraminio** [comment]
`1.0.0-preview2-1-003177`

[package.txt](https://github.com/dotnet/cli/files/753325/package.txt)
[project.txt](https://github.com/dotnet/cli/files/753326/project.txt)

> Also, since you mention using nuget update are you using Visual Studio for Mac preview?

I got it from `brew install nuget`, which is basically from Mono, then updated itself with `nuget update -self` but no hope.

**Comment by kimbaudi** [comment]
@ebraminio - give this a try.

Make sure your `global.json` file looks like this:
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}
```

Also, edit your `project.json` file by replacing "1.0.0" with "1.1.0", replacing "1.0.1" with "1.1.0", and also replacing "1.0.0-preview2-final" with "1.1.0-preview4-final". After you save `project.json` with the new changes, update nuget package. Then go to your project directory where `project.json` is and run `dotnet restore`.

I'm not sure about the nuget update part, but I think updating your `package.json` file and running `dotnet restore` should give you 1.1.0 so you can run your project with `dotnet run`. Let me know if that works out for you.
