### ISSUE TITLE
dotnet build fails for beanio-net after migrate

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#4761]
## Steps to reproduce

1. Clone [beanio-net](https://github.com/FubarDevelopment/beanio-net)
2. Checkout branch `release/4.0.0`
3. Remove the `sdk` entry from the `global.json`
4. Try to open the solutin in VS2016 RC (projects in solutions cannot be converted - no useful error message)
5. Run `dotnet migrate` from the command line (succeeds)
6. Open `BeanIO.sln` (loading projects are failing)
7. Remove and add all projects from the solution
8. Try to build from VS 2017 RC (`StyleCop.Analyzers` warnings and build errors)
9. Try to build using `dotnet build`

## Expected  behavior

1. `dotnet migrate` done by VS 2017 RC succeeds
2. Build succeeds
3. Solution gets converted too
4. Settings for `StyleCop.Analyzers` and rulesets taken from the `additionalArguments` entry

## Actual behavior

Build fails due to missing types (e.g. `XmlNodeType`). The `StyleCop.Analyzers` package emits lots of warnings, because the `additionalArguments` aren't converted.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@fubar-coder so you expect the additionalArguments to be passed to the compiler?

Other issues here are known:
* #4632 tracks migrating the sln file
* VS change is tracked internally

**Comment by fubar-coder** [comment]
What I expect is, that the solution still builds without errors (as stated in the title). The other problems are (IMHO) minor, but still a nuisance.

Regarding the `additionalArguments`: The problem is, that there was no way to specify an `additionalFile` in the `project.json`, which only left the option to use the additional arguments. The other problem, that was only solvable by the additional arguments, was the usage of `.ruleset` files.

**Comment by livarcocc** [comment]
I just tried migrating this.

I ran dotnet migrate <sln_file> and migration ran successfully.

I also managed to build the solution. Though, I had to make two adjustments:

1. Update the version in the GlobalAssembly.cs, I changed it to [assembly: AssemblyVersion("4.1.0")]. 4.1.* is not a valid version.
2. Being on a mac, I removed the net451 TFM from the projects.
