### ISSUE TITLE
Project tools extension cannot target netcoreapp1.1

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#4764]
## Steps to reproduce
Create a sample extension tool (e.g. dotnet-blah).
Target 'netcoreapp1.1' instead of 'netcoreapp1.0'.
Build
Pack
Restore into a new project from "project.json > tools" or csproj/DotNetCliToolReference.

Real life example: https://www.nuget.org/packages/BundlerMinifier.Core/2.2.305

## Expected  behavior
Installed tool. "dotnet blah" runs correctly if .NET Core 1.1 is installed

## Actual behavior
Restore fails.
> error: Package dotnet-blah 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0).

## Environment data
1.0.0-preview2-1-003177 or 1.0.0-preview3-004056

**Comment by natemcmaster** [comment]
cc @emgarten this not sure which layer of the stack (CLI or NuGet or both) this issue belongs to.

**Comment by piotrpMSFT** [comment]
Tools only support netcoreapp1.0 in the current design.

**Comment by natemcmaster** [comment]
FWIW tools that reference Microsoft.NETCore.App/1.1.0 but target netcoreapp1.0 will still run on the .NET Core 1.1 sharedfx.

**Comment by piotrpMSFT** [comment]
Yep, I know. It's an existing design limitation we want to get to before RTM...

**Comment by damtur** [comment]
I had same problem https://github.com/dotnet/cli/issues/4883 (a little bit more detailed example). Closed my ticket and will follow this from now on.

**Comment by livarcocc** [comment]
I think this has been addressed with the prefercliruntime approach, correct?

If you pack a file called prefercliruntime in the root of the package of your tool, the CLI will see that find and understand that you want your tool to be invoked using whatever runtime the CLI itself is using. So, if the CLI is running on 1.1, your tool will be invoked with 1.1. If CLI is using 1.0, the tool will be invoked with 1.0.

**Comment by damtur** [comment]
@livarcocc Can you please direct me to some docs about the `prefercliruntime` file. I just cannot find it on google somehow :/ I'm not sure if the file should go to the root of project (where `global.json` is) or to where `project.json` is. Moreover what should be the content of that file?

**Comment by livarcocc** [comment]
See here: https://github.com/dotnet/cli/tree/rel/1.0.0/TestAssets/TestPackages/dotnet-prefercliruntime

**Comment by damtur** [comment]
But this is using `csproj` and I want to have that in project.json.

**Comment by livarcocc** [comment]
@damtur As you most likely know, there is a plan to move off [project.json to csproj and MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/). With this in mind, the team has been working pretty hard to make sure that we provide the best possible experience in the .NET Core command-line tooling for MSBuild and we are focusing most of our energies into that direction moving forward.
 
This has been added in the MSBuild-based tooling and we have no plans to port it over to project.json. You can check the MSBuild based tooling by downloading the latest build from the repo's [README](https://github.com/dotnet/cli) and trying it out. We suggest that you use the "Binaries" option and install locally to make as little impact to your environment as possible.
 
Thanks!

**Comment by damtur** [comment]
@livarcocc Thank you for your response!
Yeah, I know that we are unfortunately moving to xml/MSBuild which in my opinion is a huge mistake and I still hope that you will move back to neat `project.json` on some point. I understand your reasoning though and thank you for your explanation. I'll have to stop denying reality on some point and move to msbuild with great sadness. Documentation about the feature we are discussing (`prefercliruntime`) would be quite useful though. As reverse-engineering it is not to my liking.

**Comment by livarcocc** [comment]
@blackdwarf can you help put together some documentation for the prefercliruntime file in tools?

**Comment by damtur** [comment]
I've migrated now to csproj, but I still can't find documentation about `prefercliruntime` Now with support to sdk in global.json should we add `prefercliruntime` either there or into the csproj itself? Why does it have to be a separate file
cc @livarcocc / @blackdwarf

**Comment by blackdwarf** [comment]
@damtur @livarcocc will correct me here if I'm wrong, but if I remember correctly, it is a simple file that needs to be dropped together with the payload of your tool. It doesn't have to contain anything, its mere existence is enough. 

This is also the reason why it is not a setting in the `global.json` file, since that doesn't get deployed with your app. Neither is your csproj, but it is a good point that it could be a property in there that th publish/build process could read to generate it. 

For the docs, if you haven't already, please file an issue on dotnet/docs and @mairaw or someone there will pick it up.
