### ISSUE TITLE
Command line parsing does not support all scenarios and causes need to reimplement it

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#4766]
Examples I found:
- `dotnet` and `dotnet (add|list|del|...)` command logic: chaining commands 
- Pending in review `dotnet add` - `<object>` and `<command>`  are both positional args which require `<command>` and do not require `<object>` - to determine which one is which we need a way of giving a parser some predicate which determines if this arg accepts this value
- `dotnet add` - auto generated help puts options after args which is not anywhere to what you would expect

This issue is for finding all the missing scenarios to make it once and for good

**Comment by livarcocc** [comment]
@krwq Do we still need this? Given that we have managed to implement, add/remove/list all right after all?

**Comment by krwq** [comment]
@livarcocc dotnet.exe is still not quite using CommandLineParser
