### ISSUE TITLE
Design: Dotnet (add|del|list|...) - paths: relative, absolute, globs, wildcards

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#4767]
We should determine how should we parse paths in pending dotnet-add dotnet-list and dotnet-del commands.

I'll leave this part out of https://github.com/dotnet/cli/pull/4758 as there is too many unknowns and I believe this will create unwanted design discussion and side feature.

Open questions:
- Should adding absolute path (or overcomplicated relative) convert it to most simplified relative path?
- When absolute path is passed should we search if any of relative paths/globs matches? (i.e. when removing)
- Should we support globs/wildcards? If so: Should they be expanded when adding? (do we even support wildcards for references) If existing project contains a glob should we merge? (should we implement that logic in CLI or somewhere else)
- **[high pri question]** Should the slashes be converted to forward- or back-slashes? Which one?

cc: @blackdwarf

**Comment by livarcocc** [comment]
@krwq Do we still need this issue?

**Comment by krwq** [comment]
@livarcocc wildcard question is not answered but I believe most of the OSes will expand wildcards on the command line so this is most likely not needed so closing
