### ISSUE TITLE
CLI templates should still create global.json

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#4768]
Related: https://github.com/aspnet/Templates/issues/716

Because we have a mixture of project.json and csproj SDKs on various environment (for example, Azure App Service) apps that do not have global.json always use the latest SDK available.

Several folks deploying their PJ based apps to Antares through Kudu hit this already.

**Comment by piotrpMSFT** [comment]
@mlorbetske @davkean who own some of the templates

**Comment by davkean** [comment]
Need some background on this - there's not enough context in linked issue, where does the global.json come into play in the new CLI, has things changed since I've been away?

**Comment by muratg** [comment]
@davkean, I asked if GJ is supported in the new CLI, and @blackdwarf confirmed that it is.  If this is incorrect, what's the mechanism for selecting a particular SDK version nowadays?

The concrete issue that folks are hitting is this:  Antares has a bunch of preview2 SDKs, and as of a couple days, one preview3 SDK, all side-by-side. So consider that you have a project.json based project, but lack a global.json file. When you deploy to Antares (via Kudu), you end up using preview3 SDK and that fails.

**Comment by davkean** [comment]
@blackdwarf @piotrpMSFT How is global.json used in the new CLI?

**Comment by blackdwarf** [comment]
@davkean the global.json is used only for the `sdk` property.

**Comment by blackdwarf** [comment]
I think we backed away from this plan if I'm not mistaken. @DamianEdwards @mlorbetske can you comment?
