### ISSUE TITLE
dotnet-publish does debug configuration by default

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#477]

**Comment by brthor** [comment]
Is this wrong?

**Comment by piotrpMSFT** [comment]
Yes. Publish is meant to produce ship-ready bits --> release.

**Comment by brthor** [comment]
@piotrpMSFT Is publish not thought to be part of the development lifecycle, where I assume you'd need Debug bits?

The disconnect in behavior from other tools feels like it could be confusing.
