### ISSUE TITLE
dotnet publish --runtime followed by dotnet run throws an "bad image" error

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#4773]
## Steps to reproduce

* Create a self-contained application
* Run a `dotnet publish --runtime`
* Follow immediately by `dotnet run`

## Expected  behavior
The application runs.

## Actual behavior
An error is thrown.

Attached to this issue is the zip of the application that uncovered this behavior. 
[testcoreapp.zip](https://github.com/dotnet/cli/files/599067/testcoreapp.zip)

/cc @livarcocc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@nguerrera @dsplaisted this is likely an issue in the build target...

**Comment by livarcocc** [comment]
This is actually failing for me now due to https://github.com/NuGet/Home/issues/4424.

I will try to repro this again once a new NuGet gets inserted into the CLI.

**Comment by livarcocc** [comment]
This no longer reproes on the latest CLI.
