### ISSUE TITLE
Unrecognized language: fsharp when running dotnet new for Preview 3

### ISSUE THREAD

**Issue by jpierson** [dotnet/cli#4774]
## Steps to reproduce

1. Install [.NET Core SDK 1.0 Preview 3 build 004056](https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md) using installer.
2. From a powershell window: 
   1. `> mkdir fsharpproj`
   2. `> pushd fsharpproj`
   3. `> dotnet new -t console -l fsharp`

## Expected  behavior

A new .csproj based console project should be created in the `fsharpproj` folder.

## Actual behavior

No project is created and the following error is output to the console.

> Unrecognized language: fsharp

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by piotrpMSFT** [comment]
@enricosada can help here. We don't yet have an F# template in-box atop msbuild, though @enricosada has a prototype in the works.

**Comment by enricosada** [comment]
@jpierson we were late for templates (`dotnet new` and `migrate`). Atm is wip but works okish for an alpha, see below. 

about preview3 you can find info in the wiki https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-preview3#dotnet-new

Or directly templates in https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3 )

If you find bugs pls open issues in https://github.com/dotnet/netcorecli-fsc/issues

**Comment by piotrpMSFT** [comment]
Thanks!
