### ISSUE TITLE
ResourceManager can't find parent culture resources when built using csproj/msbuild

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#4781]
## Steps to reproduce
1. Clone [this](https://github.com/ryanbrandenburg/ResourceManagerMsbuild) repo
2. Run the project.

## Expected  behavior
Finds the parent culture of "en" and outputs "key1 en" (this is confirmed to work with ".NET Command Line Tools (1.0.0-preview3-003770)" which still used project.json)

## Actual behavior
Unable to find parent culture, so A MissingManifest exception is thrown.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by piotrpMSFT** [comment]
Moved to sdk repo
