### ISSUE TITLE
XUnit2 not finding tests after upgrading to ASP.NET Core 1.1 RTM

### ISSUE THREAD

**Issue by mo-esmp** [dotnet/cli#4784]
after upgrading project when I build test project I get this error:

> Discovering tests in 'X.Tests\project.json' 
> ["C:\Program Files\dotnet\dotnet.exe" test "X\Tests.Implementation\project.json" --output 
> "D:\Workspace\X\Tests\bin\Debug\net462\win7-x64" --port 16573 --parentProcessId 8664 --no-build]
> 'test-xunit' returned '-532462766'.

when I execute `dotnet test` in command prompt it gave me this exception:

> System.IO.FileNotFoundException was unhandled
> Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in dotnet-test-xunit.exe
> Additional information: Could not load file or assembly 'Microsoft.DotNet.InternalAbstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

**Comment by piotrpMSFT** [comment]
Can you add your 'dotnet --info' output from that directory?

**Comment by alsconsulting** [comment]
fixed this by adding  "Microsoft.DotNet.InternalAbstractions" to the test project.json file.

**Comment by piotrpMSFT** [comment]
I see. So these are project.json projects?

**Comment by mo-esmp** [comment]
Here is my info

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
Cool thanks. Glad to see this is preview2 and that there is a workaround. This issue won't apply in preview3 as there is a new test execution model.

**Comment by joacar** [comment]
Just encountered this error using `beta5-build1225`

# csproj
````
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <OutputType>exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
    <PackageReference Include="xunit.runner.console" Version="2.1.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\App\App.csproj" />
  </ItemGroup>
</Project>
````

# dotnet
````
>dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530
````

**Comment by livarcocc** [comment]
@codito @Faizan2304 Please take a look. @joacar I believe you will get a faster answer if you file this issue at the microsoft/vstest repo.

**Comment by Faizan2304** [comment]
@joacar : Can you please share repro project with me. In my machine its working fine. The difference is I am using Visual studio Enterprise but I don't think it will affect here.

**Comment by codito** [comment]
Same issue as https://github.com/xunit/xunit/issues/1080? Can you try latest `xunit.runner.visualstudio` package from https://www.myget.org/feed/xunit/package/nuget/xunit.runner.visualstudio?

**Comment by aammfe** [comment]
Hope its not too late..
just install this [Microsoft.DotNet.InternalAbstractions](https://www.nuget.org/packages/Microsoft.DotNet.InternalAbstractions/) and it start working
