### ISSUE TITLE
No TypeScript files in VS2017

### ISSUE THREAD

**Issue by tinchou** [dotnet/cli#4785]
\[moved from https://github.com/Microsoft/msbuild/issues/1354]

Just downloaded VS2017 and migrated my project.json-based project. This was created using the Angular 2 template that can be found in https://github.com/aspnet/JavaScriptServices.

Now my TypeScript files are not shown and there are many .js and .map.js files created automatically.

What would be the correct configuration to have what I had before this?

-----

After posting the original question I found these settings are enough for my scenario, but the migration experience still wasn't complete and that's a bug in my opinion:

```xml
<PropertyGroup>
  <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
</PropertyGroup>

<ItemGroup>
  <None Include="ClientApp\**\*.scss" />
  <None Include="ClientApp\**\*.ts" />
</ItemGroup>
```

Thanks!

**Comment by piotrpMSFT** [comment]
@mlorbetske I'm not familiar with this aspnet template. Thoughts on how we could migrate more effectively?

**Comment by SteveSandersonMS** [comment]
Seems like it should be possible to migrate:

 * Preserve the `<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>` value if it's is present in the `.xproj` that's being migrated
 * Ensure that all original files show up in solution explorer (`.ts`, `.js`, `.json`, `.css`, `.less`, `.sass`, `.png`, etc.), like they did with `.xproj`

**Comment by piotrpMSFT** [comment]
@SteveSandersonMS thus far migration has been limited to project.json. We'll need to look at opportunities to selectively migrate xproj content for these projects.

**Comment by livarcocc** [comment]
@mlorbetske Is this something that the Web SDK is handling already?

**Comment by mlorbetske** [comment]
The inclusion of the typescript files in the project is handled by the WebSDK. For the actual integration with the Typescript build, we're working with that team to complete the story.

**Comment by livarcocc** [comment]
Ok, seems like migration will get it for free then. I am closing this issue. If there is something else we should do as part of migration for this, please, re-activate.
