### ISSUE TITLE
not intuitive how to publish native binaries

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#479]
`dotnet publish --native` doesn't work
`dotnet publish --help` doesn't help too much

**Comment by krwq** [comment]
related: https://github.com/dotnet/cli/pull/469

**Comment by brthor** [comment]
Native is a single binary. What would `dotnet publish --native` do?

**Comment by krwq** [comment]
Ok, so does that mean that in order to publish my binary as a single exe on Windows I do `dotnet compile --native`? Still feels slightly not intuitive, what if `dotnet publish native` would call the right thing for you?

**Comment by blackdwarf** [comment]
@krwq yup, publishing the native binary is essentially compiling it. We could add the override to `dotnet publish`, but then we would have two commands that do **exactly** the same thing (drop the single binary in a well-known location), which I don't think would be good.

**Comment by brthor** [comment]
Compile output is already single binary.
