### ISSUE TITLE
Packing should not alter nuspec file

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/cli#4790]
## Steps to reproduce

1) Create a project
2) `dotnet pack`
3) Edit the resulting nuspec (fixing license, owner, author, etc)
4) `dotnet pack`

## Expected  behavior

My nuspec should not be written to.
A nupkg is created with the metadata I wrote.

## Actual behavior

A nupkg is created with the incorrect metadata (because the final `pack` overwrites the nuspec)

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004108)

Product Information:
 Version:            1.0.0-preview4-004108
 Commit SHA-1 hash:  706b8a802d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by svick** [comment]
Why would you expect that to work? Since the `nuspec` is used as an intermediate file in `dotnet pack`, I would expect it to be overwritten, to ensure any changes in the project are reflected.

Have you tried using `dotnet nuget pack your.nuspec` in step 4 instead?

**Comment by Phrohdoh** [comment]
Ah I see, I did not know `nuget` was available to me like that.
The help should probably suggest that.

That makes sense, I'll write a build script that uses that instead.

**Comment by svick** [comment]
> The help should probably suggest that.

It will in the next release, see PR https://github.com/dotnet/cli/pull/4763.
