### ISSUE TITLE
Make global.json "sdk/version" support min/max, or wildcards

### ISSUE THREAD

**Issue by kierenj** [dotnet/cli#4794]
Today, I tried to deploy to Azure App Services, but they had updated to the latest tools SDK (preview3).  This broke the build for my project.

Eventually, I found that I can specify an sdk/version to use a different version of the SDK.  However, App Services have a range of versions installed, and the previous version I had (`1.0.0-preview2-003133`) wasn't an option - they have `1.0.0-preview2-003131`.

I had to add a custom deployment script to copy in a different production version of global.json.

It would be great if there was a version range option of some sort here.  I'd love to specify `1.0.0-preview2-*`.

**Comment by davidfowl** [comment]
If there's a breaking change in a preview release, you would be ok getting broken right?

**Comment by piotrpMSFT** [comment]
@schellap @gkhanna79

**Comment by kierenj** [comment]
@davidfowl I see what you mean, it's luck here that the version was bumped along with the breaking change.  But this feels like a positive move and a step in the right direction for me.
