### ISSUE TITLE
Unable to download 1.0.0-preview2-003131 via obtain script

### ISSUE THREAD

**Issue by Kieranties** [dotnet/cli#4795]
## Steps to reproduce

1. [Manual] Save [this](https://github.com/dotnet/cli/blob/91e24d886b04bbb9379c93d625517e0221480dd1/scripts/obtain/dotnet-install.ps1) instance of dotnet-install.ps1 locally
2. `.\dotnet-install.ps1 -Version 1.0.0-preview2-003131`

## Expected  behavior
Version 1.0.0-preview2-003131 of the SDK is download and installed into the users path

## Actual behavior
Output from running the above command:
```
dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003131/dotnet-dev-win-x64.1.0.0-preview2-003131.zip
Failed to download
https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003131/dotnet-dev-win-x64.1.0.0-preview2-003131.zip.
StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  x-ms-request-id: e2f91ab0-0001-0046-7ce5-43b813000000
  x-ms-version: 2009-09-19
  Date: Mon, 21 Nov 2016 10:55:19 GMT
  Server: Windows-Azure-Blob/1.0
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 215
  Content-Type: application/xml
}
At C:\Users\Kieranties\Desktop\dn\dotnet-install.ps1:159 char:13
+             throw $ErrorMsg
+             ~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to downl...lication/xml
}:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003131/dotnet-dev-win-x64.1.0.0-preview2-003131.zip.  StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  x-ms-request-id: e2f91ab0-0001-0046-7ce5-43b813000000
  x-ms-version: 2009-09-19
  Date: Mon, 21 Nov 2016 10:55:19 GMT
  Server: Windows-Azure-Blob/1.0
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 215
  Content-Type: application/xml
}
```

## Environment data
`dotnet --info` output:
N/A - no output as clean machine with no current instance

## Additonal
The sdk version is available for direct download at https://www.microsoft.com/net/download/core
Attempts at versions `1.0.0-preview2-003133` and `1.0.0-preview2-1-003177` also return errors as above.

**Comment by Kieranties** [comment]
If there's an alternative version that supports project.json that should be downloaded instead, please let me know.

**Comment by livarcocc** [comment]
Please, use the script from here: https://github.com/dotnet/cli/blob/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1.

**Comment by jseely** [comment]
I used the above script from master and it's giving the same 404 response for version `1.0.0-preview2-003133`

**Comment by piotrpMSFT** [comment]
@jseely are you able to download that package on the same machine without using the script? The binary itself is present... https://dotnetcli.azureedge.net/dotnet/preview/Binaries/1.0.0-preview2-003133/dotnet-dev-win-x64.1.0.0-preview2-003133.zip

**Comment by piotrpMSFT** [comment]
oi, also just noticed you said you got the script from `master`. Can you use the exact script @livarcocc recommended?

**Comment by testfirstcoder** [comment]
@Kieranties Following version [1.0.0-preview2-003121](https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-003121/dotnet-dev-win-x64.1.0.0-preview2-003121.zip) can be downloaded.

**Comment by piotrpMSFT** [comment]
thanks for confirming.
