### ISSUE TITLE
Replace MSBuild Condition Attributes with Specific Elements

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/cli#4796]
I can see the below conditional properties inside my csproj file:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
   <PackageReference Include="Microsoft.NETCore.App">
     <Version>1.1.0</Version>
   </PackageReference>
</ItemGroup>
```

This is really hard to remember and hand-type. I am not going to get into how this was easy in project.json (opps, I did). At least it would be nice to simplify this like below:

```xml
<Framework name="netcoreapp1.0">
   <Dependencies>
      <PackageReference Include="Microsoft.NETCore.App">
          <Version>1.1.0</Version>
      </PackageReference>
   </Dependencies>
</Framework>
```

## Environment data
`dotnet --info` output:

```
Z:\>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
@blackdwarf

**Comment by blackdwarf** [comment]
/cc @nguerrera @srivatsn @davkean 

This is a good suggestion. I don't know, however, how complex would this be to support in MSBuild.

**Comment by nguerrera** [comment]
This won't be possible without deep changes to msbuild. You'd need to start by engaging on https://github.com/microsoft/msbuild around a general mechanism for putting items in trees.

**Comment by livarcocc** [comment]
If you want, please open an issue for this in the msbuild repo.

**Comment by tugberkugurlu** [comment]
@livarcocc done https://github.com/Microsoft/msbuild/issues/1371
