### ISSUE TITLE
[dotnet build] Build fails, unable to find correct version of dependencies

### ISSUE THREAD

**Issue by LordMike** [dotnet/cli#4798]
## Steps to reproduce
1. Create a solution with three projects:
1a. BugRepro, targets `net452`, depends on `Dependency1`
1b. Dependency1, targets `net40`, depends on `Dependency2`
1c. Dependency2, targets `net40` and `net452`
2. Run `dotnet restore`
3. Run `dotnet build BugRepro`
4. Observe that `Dependency1` cannot find the `net40` edition of `Dependency2`

![image](https://cloud.githubusercontent.com/assets/1027111/20497833/00f25d28-b02b-11e6-8ed9-05a5d3b2feff.png)

## Expected  behavior
That dotnet build the versions:

* BugRepro: net452
* Dependency1: net40
* Dependency2: net40

## Actual behavior
Dotnet built the versions:

* BugRepro: net452 (didn't get this far, but I expect it to)
* Dependency1: net40
* Dependency2: net452

## Environment data
`dotnet --info` output:

    >dotnet --info
    .NET Command Line Tools (1.0.0-preview2-003131)
    
    Product Information:
     Version:            1.0.0-preview2-003131
     Commit SHA-1 hash:  635cf40e58
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64

Related: #2509

**Comment by LordMike** [comment]
Added test solution.

[BugRepro.zip](https://github.com/dotnet/cli/files/604648/BugRepro.zip)

**Comment by piotrpMSFT** [comment]
@LordMike this was a limitation of the project.json build system. I just verified your scenario will work once you move to preview3.

 - install preview3 CLI
 - `dotnet migrate` from your repro root
 - `cd src\BugRepro`
 - `dotnet restore`
 - `dotnet build --runtime win7-x64`

Please reopen if you see issues on preview3!
