### ISSUE TITLE
Change the way to target multiple frameworks inside csproj

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/cli#4799]
Currently, this is the way to target multiple frameworks:

![image](https://cloud.githubusercontent.com/assets/328122/20498277/68a97b7e-b024-11e6-9970-bb235d371109.png)

In addition to what is proposed on #4796, it would be nice to have something similar to below:

```xml
<TargetFrameworks>
    <Framework name="net451" />
    <Framework name="netcoreapp1.0">
      <Dependencies>
          <PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
      </Dependencies>
    </Framework>
</TargetFrameworks>
```

## Environment data
`dotnet --info` output:

```
Z:\>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
Same as the other one. This requires deep msbuild changes. Please, open an issue at https://github.com/microsoft/msbuild for this.

**Comment by tugberkugurlu** [comment]
@livarcocc done https://github.com/Microsoft/msbuild/issues/1372
