### ISSUE TITLE
dotnet cli doesn't work on my Windows 8

### ISSUE THREAD

**Issue by Adaok** [dotnet/cli#4800]
## Steps to reproduce
Install dotnet from : https://www.microsoft.com/net/core#windowscmd
test 
`dotnet new on terminal
`

## Expected  behavior
Create new project

## Actual behavior
`
C:/Program Files/dotnet/dotnet.exe: error while loading shared libraries: api-ms-win-crt-multibyte-l1-1-0.dll: cannot open shared object file: No such file or directory
`

## Environment data
`
C:/Program Files/dotnet/dotnet.exe: error while loading shared libraries: api-ms-win-crt-multibyte-l1-1-0.dll: cannot open shared object file: No such file or directory
`

I have just install Visual Studio Code on my computer with Windows 8. I have already Visual Studio Code and the .NetCore for work on my Mac, but when I install dotnet CLI on my Windows, I have the output above.
If someone have a solution, I take it !
Thanks for your attention.

**Comment by livarcocc** [comment]
@gkhanna79 @schellap Is this something that you guys can help with?

**Comment by gkhanna79** [comment]
@Adaok Did you install the CLI via installer or are using the zip package? Can you please ensure https://www.microsoft.com/en-us/download/details.aspx?id=48145 is installed and try again? VC++ 2015 redist is installed by the CLI installer.

**Comment by Adaok** [comment]
@gkhanna79 Hi ! I have install the CLI via installer and https://www.microsoft.com/en-us/download/details.aspx?id=48145 is install also. I retry but no changes... :(

**Comment by blackdwarf** [comment]
Any update on this?

**Comment by Adaok** [comment]
Hey ! Sorry for the late of the answer. After many try, I 've decided to update Windows 8 for Windows 10 and I haven't more this problem. Thanks for your help !

**Comment by ricardocosta21** [comment]
You need to copy those missing dlls from your 'C:\Windows\System32' folder into your application's Debug folder. Then, just rebuild it. Cheers.
