### ISSUE TITLE
dotnet --version wrong output

### ISSUE THREAD

**Issue by Jipperism** [dotnet/cli#4807]
## Steps to reproduce
Upgrade from `1.0.0` to `1.1.0`

## Expected  behavior
Output `1.1.0`

## Actual behavior
Output `1.0.0-preview2-003177`

## Environment data
`dotnet --info` output:
```
Microsoft .NET Core Shared Framework Host

Version  : 1.1.0
Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

**Comment by vcsjones** [comment]
I think this behavior is correct. This:

>Output 1.0.0-preview2-003177

Is the version of the tooling, not the the runtime or SDK. As you see, `dotnet --info` or just `dotnet` print the SDK version.

**Comment by livarcocc** [comment]
dotnet --version returns the version of the CLI, not the version of the runtime. We will track maybe changing that, no guarantees, in the issue above.
