### ISSUE TITLE
Migrating a solution with multiple libraries using project.json fails

### ISSUE THREAD

**Issue by Bidimus** [dotnet/cli#4809]
## Steps to reproduce
Attempted to migrate a solution with multiple projects that use project.json and have cross project dependencies.

## Expected  behavior
Successful migration of solution.

## Actual behavior
Migration fails because it migrates the projects out of order.  Migrating a project that has a dependency on another project requires that it can read the other projects project.json file.  That file is removed if the other project happens to get migrated first though.  Manually migrating the projects ordered on their interdependencies works. 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
Can you share a repo that reproes this? This is a scenario that we actually test for. Having a project structure like Project A -> Project B -> Project C. If you migrate from Project A, the whole tree should get migrated correctly. However, if you migrate Project C and the Project A, it is expected to fail, as it can't find C anymore.

**Comment by Bidimus** [comment]
I wish I could.  Unfortunately the solution I was testing on is not publicly available.  It was an Asp.Net API solution built under VS2015 using .Net Core 1.0.  It had two class library projects under the src directory for Core and Infrastructure.  There was also another project under the test directory with a xunit test library in it.  The test library referenced Core and Infrastructure while the main API project referenced Infrastructure which in turn referenced Core.  Based on the fact the API and Core migrated but not the others, I suspect it did the API first then Core.

**Comment by piotrpMSFT** [comment]
I assume this failed in VS, @Bidimus. The same migration should succeed from the command line so long as it was initiated from a parent directory of all the projects involved. The VS issue will be fixed in an upcoming release.

**Comment by Bidimus** [comment]
Excellent point.  I'll see if I can find time to verify this today.

**Comment by blackdwarf** [comment]
@Bidimus did you manage to verify this?

**Comment by Bidimus** [comment]
Actually I did not get a chance to verify but I did grab the latest update
to VS 2017 just last week and had a 100% successful conversion of the same
solution that caused me problems originally.  At this point this is no
longer an issue far as I can tell regardless of what the cause was.

---
Jim Davies




Bidi's World <http://www.bidiworld.net/>

"Live every day as if it were your last
 and one day you'll be right!" - *George Carlin*
