### ISSUE TITLE
Colors are broken in some places

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#481]
Colors are broken in some places and linux artifacts for colors are being displayed instead.
I have noticed that mostly happening when displaying warnings. I.e (simply run build for repro):
```
1 File(s) copied
←[1m←[33mX:\oss\cli-2\src\Microsoft.DotNet.ProjectModel\project.json(15,52): warning NU1007: Dependency specified was Microsoft.Extensions.FileSystemGlobbing >= 1.0.0-rc2-15791 but ended up with Microsoft.Extensions.FileSystemGlobbing 1.0.0-rc2-15797.←[39m
```

**Comment by jasonwilliams200OK** [comment]
Probably this is happening:

```sh
echo "\x1B[33mMESSAGE_STRING\x1B[39m"
```

To fix (preferred solution):

```sh
printf "\x1B[33mMESSAGE_STRING\x1B[39m"
```

or (just ok solution):

```sh
echo -e "\x1B[33mMESSAGE_STRING\x1B[39m"
```

**Comment by brthor** [comment]
@krwq What platforms are you seeing these breaks on?

From what I have seen it is Windows only.

**Comment by piotrpMSFT** [comment]
@krwq can you open bugs for specific places where this occurs? This is not specific enough to go after.
