### ISSUE TITLE
adding core project to solution causes msbuild /p:PublishOnBuild to fail

### ISSUE THREAD

**Issue by Spongman** [dotnet/cli#4811]
## Steps to reproduce

- in VS, create a new blank solution.
- add a new ASP.NET 4.x WebApplication project
  - create a new publish profile called "publish" for the Web App (cutsom, filesystem)
- add a new, non-core console app to the solution.
- in a command line prompt:
  - cd to the solution folder
  - MSBuild /p:PublishProfile=publish /p:DeployOnBuild=true
  - notice that it builds fine and deploys the web app
- add a .net core console app
- repeat the MSbuild step

error MSB4025: The project file could not be loaded. Could not find a part of the path 'C:\WebApplication2\ConsoleApp1\Properties\PublishProfiles\publish.pubxml'

it shouldn't fail if there's no publish profile for that project, it should just skip it silently as it does for the non-core console project.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

a workaround would be great, if there is one. this is currently blocking my CI.

**Comment by Spongman** [comment]
here's the project:
[WebApplication2.zip](https://github.com/dotnet/cli/files/607603/WebApplication2.zip)

**Comment by piotrpMSFT** [comment]
Are you running desktop MSBuild on Windows? Or `dotnet msbuild`?

**Comment by Spongman** [comment]
MSBuild on windows

**Comment by Spongman** [comment]
were you able to repro?

**Comment by piotrpMSFT** [comment]
@srivatsn @rainersigwald can you guys take a look? We need some broader-than-cli context here :)

**Comment by srivatsn** [comment]
@nguerrera can you take a look?

**Comment by nguerrera** [comment]
@Spongman I notice that this is using preview2 and xproj/project.json.  When I opened in VS 2017 RC, it migrated the project successfully to csproj and then things worked as you expect: the web app is published to c:\temp\blah and both console apps build as usual.

I think this fixed itself in the move to csproj / preview3. Are you able to move to that?

**Comment by Spongman** [comment]
i'm specifically looking for a VS2015 fix.

**Comment by nguerrera** [comment]
@Spongman OK, it took me some time to get set up to build with VS2015 and Preview2.

Here is one workaround, override WebPublish in the core console project's xproj to do explicitly do nothing:

``` XML di
   ...
  <Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.targets" Condition="'$(VSToolsPath)' != ''" />

  <!-- Don't participate in DeployOnBuild of the rest of the solution -->
  <Target Name="WebPublish" />
</Project>
```

Will that do for you?

**Comment by Spongman** [comment]
thanks, yes, that fixes the problem.
