### ISSUE TITLE
dotnet cli should no longer call into Nuget xplat restore

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#4812]
NuGet has remove xplat restore here: https://github.com/NuGet/NuGet.Client/commit/207589e20f20fe2b33e8f80eae0562c30a6c01b5

But it seems that dotnet restore-projectjson still calls into it: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore-projectjson/NuGet3.cs#L20

Seems like restore should no longer be invoked through NuGet since restore is invoked through msbuild.

**Comment by livarcocc** [comment]
We are using that to keep restoring project.json, which we need for some of our migration tests. Is there a way to do project.json restore still?

**Comment by rrelyea** [comment]
Preview2 CLI is the only way you will be able to do xproj/project.json restore.
You could also use NuGet.exe v3.5.0-rtm

**Comment by piotrpMSFT** [comment]
Good to know. We'll need to change builds to account for this...

**Comment by natemcmaster** [comment]
Does this mean support for `dotnet nuget restore project.json` is removed?

**Comment by piotrpMSFT** [comment]
That's what I understand from @rrelyea's post. It broke some tests for CLI [migration specifically] that we need to compensate for. I was under the impression that PJ restore was in for the long run, but the change reduces concepts and makes sense... Does this diverge from nuget.exe, however? I assume that one needs to maintain PJ support...

**Comment by piotrpMSFT** [comment]
This is fixed.
