### ISSUE TITLE
debugType "full" does not work on OS X

### ISSUE THREAD

**Issue by TimeDelta** [dotnet/cli#4817]
## Steps to reproduce
1. On OS X, check out [this GitHub project](https://github.com/jpopadak/CoreMatchers/) at [this commit](https://github.com/jpopadak/CoreMatchers/commit/23c71ff1503c921e70646b55837d6067f1870097)
1. Run this command: `dotnet restore`
1. Run this command: `dotnet test ./test/CoreMatchers.Tests/project.json`

## Expected  behavior
Compilation should succeed.

## Actual behavior
<pre>
[master]bherman-mbp:~/development/side_projects/CoreMatchers
$ dotnet restore
log  : Restoring packages for /Users/bherman/development/side_projects/CoreMatchers/src/CoreMatchers/project.json...
log  : Restoring packages for /Users/bherman/development/side_projects/CoreMatchers/test/CoreMatchers.Tests/project.json...
log  : Lock file has not changed. Skipping lock file write. Path: /Users/bherman/development/side_projects/CoreMatchers/src/CoreMatchers/project.lock.json
log  : /Users/bherman/development/side_projects/CoreMatchers/src/CoreMatchers/project.json
log  : Restore completed in 314ms.
log  : Writing lock file to disk. Path: /Users/bherman/development/side_projects/CoreMatchers/test/CoreMatchers.Tests/project.lock.json
log  : /Users/bherman/development/side_projects/CoreMatchers/test/CoreMatchers.Tests/project.json
log  : Restore completed in 508ms.
[master]bherman-mbp:~/development/side_projects/CoreMatchers
$ dotnet test ./test/CoreMatchers.Tests/project.json
Project CoreMatchers (.NETStandard,Version=v1.6) will be compiled because Input items removed from last build
Compiling CoreMatchers for .NETStandard,Version=v1.6
/usr/local/share/dotnet/dotnet compile-csc @/Users/bherman/development/side_projects/CoreMatchers/src/CoreMatchers/obj/Debug/netstandard1.6/dotnet-compile.rsp returned Exit Code 1
/Users/bherman/development/side_projects/CoreMatchers/src/CoreMatchers/error CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.9106075

SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
</pre>

## Environment data
`dotnet --info` output:
<pre>
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
</pre>

## Notes
The issue is the [here](https://github.com/jpopadak/CoreMatchers/blob/master/src/CoreMatchers/project.json#L6) where it says, `"debugType": "full",`. Changing this line to `"debugType": "portable",` allows the compilation to succeed.

**Comment by svick** [comment]
I think this is expected. The code for writing PDBs (which is what `"debugType": "full"` means) is Windows-only. Using `"debugType": "portable"`, which writes PPDBs is the right fix.

**Comment by livarcocc** [comment]
Exactly. This is expected. If you want to debug on non-windows, use portable pdbs.

**Comment by jpopadak** [comment]
I believe if this were to occur, there should be a better error message stating that the platform is not compatible with this `debugType`.

**Comment by piotrpMSFT** [comment]
@jpopadak recommendation? 

/cc @blackdwarf

**Comment by jpopadak** [comment]
Honestly, I don't care what the error message states. As long at it explains that the `debutType` of `full` is not supported for non-windows machines. It would have saved my friend hours of searching the web... 

@TimeDelta works strictly on Mac OS, I have someone else who works strictly on Linux, and I work strictly on Windows. They both had the same issue except for me. I thought their CLI tools were broken.

Once I realized that it was attempting to write out the PDB file, I told them to switch up the `debugType` and it all started working again. 

The error message of `CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll'` simply isn't detailed enough to explain to **_first time_** users of .NET / .NET Core when coming from a Java background.

**Comment by piotrpMSFT** [comment]
We should consider adding a persistent warning if `debugType` is not portable, off only if the project targets Desktop TFMs only.
