### ISSUE TITLE
Cannot run unit tests using the new MSBuild Alpha

### ISSUE THREAD

**Issue by kevin-de-coninck** [dotnet/cli#4819]
From within Visual Studio of from the Command Line, it's impossible to run unit tests.

## Steps to reproduce

- Create a new XUnit Test project using the CLI: `dotnet new -t Xunittest`.
- Restore the packages using the CLI: `dotnet restore`.
- Run the tests using the CLI: `dotnet test`

## Expected  behavior

The tests should be executed and reported.

## Actual behavior

An error is raised: `dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

Since unit testing is a key aspect it makes the new preview tooling useless.

**Comment by piotrpMSFT** [comment]
@kevin-de-coninck yea, this is an unfortunate issue that is fixed in the latest nightlies on https://github.com/dotnet/cli. The problem is the space in `Program Files`. A lot of testing happened against cmd-line installed CLI, not the native installer, so this was missed during preview3 end-game. Can you try the latest and confirm that the issue is fixed?

**Comment by kevin-de-coninck** [comment]
Sure,

Can you point me to the correct installer to test it?


Kind regards

**Comment by kevin-de-coninck** [comment]
I've installed `1.0.0-preview4-004110` of .NET Core.
The issue seems to be resolved.

This issue can now be closed.

**Comment by kevin-de-coninck** [comment]
After testing a bit further, running XUnit Tests in Visual Studio does not work, they remain "Inconclusive".
Is there any workaround to make the unit tests behave correctly inside Visual Studio?

**Comment by kevin-de-coninck** [comment]
Seems to be an issue with Resharper. Unit Tests (written in xUnit) does work correctly when running them from within the Test Explorer from inside Visual Studio.
