### ISSUE TITLE
Add support for NuGet 3.3 'contentFiles' in dotnet cli

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#483]
https://docs.nuget.org/create/nuspec-reference#contentfiles-with-visual-studio-2015-update-1-and-later

We should support these by mimicking MSBuild build actions. We can support "Compile" and "EmbeddedResource" in `dotnet-compile` and the "copyToOutput" flag in `dotnet-publish`

**Comment by anurse** [comment]
I think @pakrym is working on this now. Do you have a bug for tracking that already @pakrym ?

**Comment by pakrym** [comment]
Yep, https://github.com/dotnet/cli/issues/66

**Comment by anurse** [comment]
This is a dup then. Thanks!
