### ISSUE TITLE
Error: dotnet exec needs a managed .dll or .exe extension

### ISSUE THREAD

**Issue by djanosik** [dotnet/cli#4832]
## Steps to reproduce

`dotnet test` in a folder with .csproj .NET Core project.

## Expected  behavior

Runs tests defined in the given project and display results.

## Actual behavior

Tests do not run and error message is displayed. It looks like an issue with space in path to some executable (MsBuild?).
```
Test run for H:\Personal\Moon.Libraries\test\Moon.Collections.Tests\bin\Debug\netcoreapp1.0\Moon.Collections.Tests.dll(.NETCoreApp,Version=v1.0)
dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'
```
Tests run in Visual Studio without issues.

## Environment data
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14971
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by djanosik** [comment]
Eh, I see it's already fixed. Sorry, my mistake.

**Comment by piotrpMSFT** [comment]
@djanosik thanks for reporting and also validating :D
