### ISSUE TITLE
dotnet test fails to run after a successful dotnet migrate on Mac and Windows

### ISSUE THREAD

**Issue by duraz0rz** [dotnet/cli#4833]
Sorry if the name is pretty vague. Feel free to rename it. 

I've been playing around with .NET Core as part of doing this kata, and I wanted to try to migrate to the new csproj-based projects just because. I'm running into an issue where I can't get the unit test project to run on my Macbook Pro or my Windows PC. Not sure what I'm doing wrong, either.

## Steps to reproduce
- Grab code from [this repo](https://github.com/duraz0rz/dotnet-migrate-test). It consists of two projects: A library project under src/ and an xUnit test project under test/
- Run `dotnet migrate` in the root directory where global.json is. 
- Attempt to run unit tests by `cd`ing into `test\VendingMachineKata.Tests\` and running `dotnet test`

## Expected  behavior
Unit tests should execute like they did when it was project.json-based.

## Actual behavior
I get the following error on my Windows machine:

```
PS C:\code\vendingmachinekata\test\VendingMachineKata.Tests> dotnet test
Test run for C:\code\vendingmachinekata\test\VendingMachineKata.Tests\bin\Debug\netcoreapp1.1\VendingMachineKata.Tests.dll(.NETCoreApp,Version=v1.1)
dotnet exec needs a managed .dll or .exe extension. The application specified was 'C:\Program'


PS C:\code\vendingmachinekata\test\VendingMachineKata.Tests>
```

I get the following error on my Mac:

`/usr/local/share/dotnet/sdk/1.0.0-preview3-004056/Microsoft.Common.CurrentVersion.targets(1107,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [<path to test csproj>]`

The project reference inside VendingMachineKata.Tests.csproj looks correct:
```
  <ItemGroup>
    <ProjectReference Include="..\..\src\VendingMachineKata\VendingMachineKata.csproj" />
  </ItemGroup
```

The main library project is targeting .NET Standard 1.6.0, whereas the unit test project is targeting .NET Core 1.1.

Main csproj:
```
 <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.6' ">
    <PackageReference Include="NETStandard.Library">
      <Version>1.6.0</Version>
    </PackageReference>
  </ItemGroup
```

Test csproj:
```
<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.1' ">
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.1.0</Version>
    </PackageReference>
  </ItemGroup
```

## Environment data
`dotnet --info` output (Windows):
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14971
 OS Platform: Windows
 RID:         win10-x64
```

`dotnet --info` output (Mac Sierra):
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

**Comment by livarcocc** [comment]
A couple of things here. For the windows issue, this is a known issue in dotnet test where the path to the dll is not being quoted. You can work around it by downloading the binaries zip file and dropping it in a path without spaces and then adding that to your path and trying again.

For the mac issue, did you run dotnet restore before trying dotnet test? dotnet restore is still required.

As for netcoreapp 1.1, did you still that runtime? 1.0.0-preview3-004056 is a version of the CLI that comes with the 1.0.1 version of the shared runtime.

**Comment by duraz0rz** [comment]
@livarcocc Thanks for the pointers! That got me a bit further...just need to change the test runner now.

Also, I thought you could use netcoreapp 1.1 per [the alpha announcement blog](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/#dotnet-cli-tools) under the "Upgrading your project to use .NET Core 1.1" heading.
