### ISSUE TITLE
Update F# templates to latest

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4841]
- [x] `preview2` ref #4827
- [x] `preview2.1` ref #4828 (may fails on restore because `dotnet-compile-fsc` is not on nuget.org yet, can be done later)
- [x] `preview4` ref #4836 

/cc @cartermp @KevinRansom @dsyme @cloudRoutine

fix https://github.com/dotnet/netcorecli-fsc/issues/36

**Comment by rogersachan** [comment]
All three of them were approved. When will they be merged then?

**Comment by enricosada** [comment]
@rogersachan soon, because there is going another release (`preview4` and an update of `preview2` too).
The dotnet/cli is really near code freeze, they are finalizing for next release (that's why the `approved` label) 
Is thanksgiving atm in usa, so lets wait a bit 😄

**Comment by enricosada** [comment]
Closing because all templates are pretty much aligned.

Some newer commit changed templates again a bit, sent PR #4984 and #4985 to align
