### ISSUE TITLE
Cannot restore packages for RID ubuntu.16.10-x64

### ISSUE THREAD

**Issue by simonech** [dotnet/cli#4844]
## Steps to reproduce

Execute ` dotnew new`
Update `.csproj` file adding 
```
    <RuntimeIdentifiers>win10-x64; osx.10.11-x64; ubuntu.16.10-x64</RuntimeIdentifiers>
```
Launch `dotnet restore`

## Expected  behavior

I would expect to able to the same thing I do with the `project.json` based project, like explained in the page [Self-contained deployments (SCD)](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/#self-contained-deployments-scd)

So, being able to restore all packages for all RIDs and then being able to build to all runtimes and having one folder per runtime like here

![image](https://cloud.githubusercontent.com/assets/61557/20629255/d4d99582-b32a-11e6-803e-bfb9578855d2.png)

## Actual behavior

I get error when trying to restore. 100s of such errors (one per dependency I guess)

```
C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\NuGet.targets(70,5): error : System.Text.Encoding.Extensions 4.0.11 provides a compile-time reference assembly for System.Text.Encoding.Extensions on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with  osx.10.11-x64. [C:\Projects\ASPNET-Core-Succinctly\samples\xplatapp\xplatapp.csproj]
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by simonech** [comment]
Ok, nevermind... find the error....
No space allowed in the `RuntimeIdentifiers` property:

This works:

```
 <RuntimeIdentifiers>win10-x64;osx.10.11-x64;ubuntu.16.10-x64</RuntimeIdentifiers>
```

**Comment by blackdwarf** [comment]
For me, with the latest tooling, the restore does not give out an error, but `dotnet publish -r ubuntu.16.10-x64` does not publish anything that looks like it is Linux-specific.

@ericstj is this RID valid? Do we have packages for it up on Nuget?

**Comment by ericstj** [comment]
@blackdwarf : it's in 1.1.0

https://github.com/dotnet/corefx/blob/release/1.1.0/pkg/Microsoft.NETCore.Platforms/runtime.json#L324
https://github.com/dotnet/corefx/commit/cb217c066c93e331059f0273f816074faf3f456c
/cc @mellinoe

**Comment by blackdwarf** [comment]
@ericstj ah, you're right. 16.10 was added for Current, not LTS. For me retargeting the application to `netcoreapp1.1` solves the problem. I will close this issue now since the solution is pretty clear. @simonech please reopen if you run into the same problem with `netcoreapp1.1`. 

Thanks @ericstj!
