### ISSUE TITLE
dotnet restore succeeds from within VS, fails in command line

### ISSUE THREAD

**Issue by carlos-sarmiento** [dotnet/cli#4846]
## Steps to reproduce
I have a solution that implements a library along with its unit tests. Both projects are .NET Core projects, the Class Library points to .NETStandard 1.6, the unit test is .NETCoreApp 1.1

The folder structure is
```
- root
  |- global.json
  |- src
     |- Somesoft.V2.Libs.EventSourcing
	 |- project.json
		|- ...
  |- test
     |- Somesoft.V2.Libs.EventSourcing.Tests
	 |- project.json
		|- ...
```

The `global.json` file is:
```
{
    "projects": [
        "src/Somesoft.V2.Libs.EventSourcing",
        "test/Somesoft.V2.Libs.EventSourcing.Tests"
    ]
}
```

The `project.json` in Somesoft.V2.Libs.EventSourcing.Tests includes a dependency on Somesoft.V2.Libs.EventSourcing like this:

```
"dependencies":{  
  ...,  
  "Somesoft.V2.Libs.EventSourcing":{  
	 "target":"project"
  }
}
```

## Expected  behavior
The expected behavior is that running `dotnet restore` from the command line successfully restores the package.

## Actual behavior
Inside Visual Studio 2015 (Update 3), the project gets restored and built successfully.
But when I do a `dotnet restore` from the command line it fails with the following error:

```
dotnet restore
log  : Restoring packages for E:\Somesoft\libs-event-sourcing\test\Somesoft.V2.Libs.EventSourcing.Tests\project.json...
error: Unable to resolve 'Somesoft.V2.Libs.EventSourcing' for '.NETCoreApp,Version=v1.1'.
log  : Lock file has not changed. Skipping lock file write. Path: E:\Somesoft\libs-event-sourcing\test\Somesoft.V2.Libs.EventSourcing.Tests\project.lock.json
log  : E:\Somesoft\libs-event-sourcing\test\Somesoft.V2.Libs.EventSourcing.Tests\project.json
log  : Restore failed in 699ms.

Errors in E:\Somesoft\libs-event-sourcing\test\Somesoft.V2.Libs.EventSourcing.Tests\project.json
    Unable to resolve 'Somesoft.V2.Libs.EventSourcing' for '.NETCoreApp,Version=v1.1'.
```

## Environment data
`dotnet --info` output:
```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by nanopp** [comment]
I have the exact same situation in Windows 7. This happens when I try "docker build" and fails when docker is trying to restore packages.

**Comment by carlos-sarmiento** [comment]
I'll leave this so if people find this, they know what was going wrong with my environment. The problem was that the global.json file was missing the "sdk" key. 

This global.json works
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177"
  }
}
```

**Comment by nanopp** [comment]
Thanks Carlos, my problem is still not solved, is there any chance I could see the "project.json" of your "Somesoft.V2.Libs.EventSourcing project"?

**Comment by carlos-sarmiento** [comment]
Post your project.json and I can take a look
