### ISSUE TITLE
Tooling issue with microsoft.diasymreader.native

### ISSUE THREAD

**Issue by mcm-ham** [dotnet/cli#4848]
## Steps to reproduce
* run `dotnet new`
* update csproj to target `netcoreapp1.1` and Microsoft.NETCore.App nuget reference to 1.1.0.
* open project in VS2017RC  

## Expected  behavior
Not throw an an error if project located on a different drive other than C:
[VsProjectFault_1f5782a9-94e0-4018-94af-b0462c6fff0c.failure.txt](https://github.com/dotnet/cli/files/614539/VsProjectFault_1f5782a9-94e0-4018-94af-b0462c6fff0c.failure.txt)
[VsProjectFault_eb2e76bc-e4df-4251-af54-162d11af0d32.failure.txt](https://github.com/dotnet/cli/files/614540/VsProjectFault_eb2e76bc-e4df-4251-af54-162d11af0d32.failure.txt)

Not show microsoft.diasymreader.native nuget package in project if on C:
![image](https://cloud.githubusercontent.com/assets/8325692/20645146/ba0d84d2-b48f-11e6-9817-db8ae0299edf.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

I have SDK 1.0.0 Preview 2.1 installed as well.

**Comment by piotrpMSFT** [comment]
@srivatsn

**Comment by srivatsn** [comment]
@tmat - do you think the package can be fixed to not include the <Content> statically?

**Comment by tmat** [comment]
I have fixed it: https://github.com/dotnet/roslyn-internal/pull/1384/commits/b9fc00eb6b5f2a9f918b1a21fbefcd6db68feec1 
Haven't rebuilt and published the new version yet.

**Comment by piotrpMSFT** [comment]
@tmat can you link an issue to track?

**Comment by tmat** [comment]
Published new version of the package with fixed targets file: 
https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/1.5.0-beta2-24728

**Comment by piotrpMSFT** [comment]
Thanks @tmat!
