### ISSUE TITLE
Upgrade fails on a project that contains a relative "includeFiles"

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/cli#4849]
## Steps to reproduce
Open [Rx.NET/Source/Rx.NET.sln](https://github.com/Reactive-Extensions/Rx.NET/commit/548cd01bd6d6f9e5883d67bcc9ba62a7a4579d33#diff-e8e13495843b2818d0f01c89f97daa0d) in `VS2017 RC (15.0.25920.0)`

## Expected  behavior
The migration for all `.xproj` projects to `.csproj` happens correctly.

## Actual behavior
The migration fails because the [GlobalAssemblyVersion.cs](https://github.com/Reactive-Extensions/Rx.NET/commit/548cd01bd6d6f9e5883d67bcc9ba62a7a4579d33#diff-79663cc34d752b2fba12315360f459ccR25) cannot be found.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14971
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
@jeromelaban does this repro if you:
- revert changes from VS
- run 'dotnet migrate' from cmd line from root directory of project with no args?

**Comment by livarcocc** [comment]
I just tried this with the latest rel/1.0.0-rc3 build and I managed to migrate the .sln file successfully, at least the repo at the commit that was pasted here.
