### ISSUE TITLE
Exception on "dotnet restore" when package source doesn't exist

### ISSUE THREAD

**Issue by bdukes** [dotnet/cli#485]
I have a `project.json` with one dependency, which exists on nuget.org (Microsoft.ApplicationBlocks.Data).  However, when I run `dotnet restore`, an exception is thrown because I have an additional package source defined in my `NuGet.Config` file, and that path doesn't exist (it's a network path for a network I'm not currently connected to).  I would expect this package source to be ignored, rather than stop the restore.

```
System.IO.FileNotFoundException: The local package source \\[REDACTED]\VisualStudio\NuGet Packages doesn't exist
File name: '\\[REDACTED]\VisualStudio\NuGet Packages'
   at Microsoft.Dnx.Tooling.Restore.NuGet.PackageFolder.FindPackagesByIdAsync(String id)
```

The full output is available at http://pastebin.com/A2j0YPv0.

Note, this same error happens using a local path that doesn't exist (e.g. `C:\foo`), it doesn't appear to be directly related to network paths.  Also, this error doesn't occur when the package is already in the cache.

**Comment by piotrpMSFT** [comment]
we'll be replacing the current restore mechanism all-up by Beta, so this should not be a problem soon.

**Comment by blackdwarf** [comment]
Since we replaced the `dotnet restore` mechanism to use NuGet, I believe this is fixed. If not, the issue should be opened on NuGet/home.
