### ISSUE TITLE
Migration does not transfer "packOptions -> files" items

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#4852]
My project.json file has some files listed under the "packOptions" header. They aren't migrated at all and no error is given.

**Comment by piotrpMSFT** [comment]
Can you add a repro, @mellinoe?

**Comment by piotrpMSFT** [comment]
@livarcocc

**Comment by livarcocc** [comment]
@mellinoe Can you please share your project.json?

**Comment by mellinoe** [comment]
It's this one:

https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/project.json

**Comment by livarcocc** [comment]
@mellinoe Which version of the CLI did you use?

PackInclude is actually not support in preview2 and if you try to migrate a project with it, it will actually fail with the following:

```
Project ImGui.NET migration failed (/Users/livarcocc/Documents/git/ImGui.NET/src/ImGui.NET)
MIGRATE1011::Deprecated Project: /Users/livarcocc/Documents/git/ImGui.NET/src/ImGui.NET
The 'packInclude' option is deprecated. Use 'files' in 'packOptions' instead. (line: 26, file: /Users/livarcocc/Documents/git/ImGui.NET/src/ImGui.NET/project.json)
The 'projectUrl' option in the root is deprecated. Use it in 'packOptions' instead. (line: 4, file: /Users/livarcocc/Documents/git/ImGui.NET/src/ImGui.NET/project.json)
```

Do you have a version of this project.json where you actually have Files under PackOptions? That should work.
