### ISSUE TITLE
Migration inserts unnecessary elements into the project

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#4853]
I see that all of my projects have a number of unnecessary elements in them. Can we detect if these are necessary and only conditionally include them?

```xml
    <EmbeddedResource Include="**\*.resx" />
    <EmbeddedResource Include="compiler\resources\**\*" />
```

^ Unused; there are no such files.

```xml
    <PackageReference Include="NETStandard.Library">
      <Version>1.6.0</Version>
    </PackageReference>
```
^ I don't want my project to reference this package, and it didn't before.

```xml
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
```

This just seems like cruft.

**Comment by GuardRex** [comment]
```
<Compile Include="**\*.cs" Exclude="wwwroot\**\*;bin\**;obj\**;**\*.xproj;packages\**" />
```
It also doesn't check if these `Exclude` locations or the `.xproj` file exists before tossing this in.

**Comment by svick** [comment]
@mellinoe If you add .resx file to the project directory at some point after the migration, wouldn't you expect the project to pick it up?

**Comment by mellinoe** [comment]
No, not unless I added it to the project myself. But I'm used to regular .NET projects where that doesn't happen.

**Comment by dasMulli** [comment]
related: If you remove `NETStandard.Library` and all resource-related stuff, compile errors may pop up at the moment because the SDK will autogenerate a `NeutralResourcesLanguageAttribute` attribute by default without an assembly referenced that defines it.. https://github.com/dotnet/sdk/issues/382

Also, @davidfowl recently pointed out to me: https://github.com/dotnet/sdk/issues/413#issuecomment-262172023
>>AFAIK it is still recommended to trim your dependencies to the minimum set required when publishing a NuGet for netstandard < 2.0.

>No, that ship has sailed. We're recommending people use NETStandard.Library. Also with netstandard 2.0 it won't be possible to break it down any further as that's the minimal set of dependencies that any valid .NET implementation will need to implement.

**Comment by mellinoe** [comment]
> the SDK will autogenerate a NeutralResourcesLanguageAttribute attribute by default 

Sure, that doesn't mean you need `NETStandard.Library`, though, just one small package that has the attributes.

For .NET Standard 2.0: sure it makes sense to just include the whole thing, since we eliminated the modularity that made it valuable. There's still a lot of value to be granular for the time being, though.

It is probably fine to include it in the default migration, I just find it a bit annoying how much cleanup I need to do after the migration runs, just to get back to where my project was at before.

**Comment by krwq** [comment]
@mellinoe - I think that a lot of the stuff you mentioned here is nice to have feature but I would consider only stuff which create an invalid or non-compiling project as blockers. Everything else I believe is a personal preference and some of the people will want it and some other won't - I do not think we can satisfy everyone with defaults and since dotnet-migrate is a one time operation I do not believe it is worth to provide such options as it is easier to simply modify the project. I personally treat anything which is not pure source code a necessary clutter and completely do not care what's inside and would like the defaults to be anything so that I don't ever have to touch the file again.

**Comment by livarcocc** [comment]
@mellinoe Migration has as one of its goals preserve as much of the behavior of project.json as possible in the csproj world. As such, it adds things that you may not necessarily need, but if you were working in PJ, you could count with. This is the reasoning behind have these extra elements in a migrated CSProj.

I understand that your particular project does not need it, but this is in par with the PJ behavior that you experienced before and that's what we chose to honor with migration.

**Comment by mellinoe** [comment]
Yeah, I understand where you're coming from. Unfortunately, some of the changes, like including extra package references, considerably alter the output of my project. It would be nice if the output of the build was the same before and after, but I guess that isn't a goal.

**Comment by livarcocc** [comment]
Is the problem mainly with NetStandard.Library being added? Or is it all the things you pointed out above? How is the output of your project changing?

**Comment by mellinoe** [comment]
Yes, I mean that adding NETStandard.Library changes the output of my project.

**Comment by livarcocc** [comment]
Let me discuss this with the team and get back to you.

**Comment by livarcocc** [comment]
@mellinoe Also, for these kinds of issues, sharing at least the project.json would be extremely helpful. Could you do that?

**Comment by mellinoe** [comment]
Sure; same as the other issue: https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/project.json

**Comment by ThadHouse** [comment]
I am running into the .NET Standard issue as well, although I have a use case where it definitely breaks things. I have a project.json file located at https://github.com/robotdotnet/NativeLibraryUtilities/blob/master/src/NativeLibraryUtilities/project.json that builds for .NET 4.5 and .NET Standard 1.5. I #ifdef anything from .NET standard that would be used in .NET 4.5 so it compiles completely independently. Running the migrate and adding .NET Standard 1.6 unconditionally actually breaks my builds, and adds an extra DLL dependency `System.Runtime.InteropServices.RuntimeInformation.dll` that is not required, and breaks my running on Mono.

**Comment by livarcocc** [comment]
Migration is no longer adding these elements to your csproj. However, the SDK is implicitly doing so, but that is the plan for all NetCore projects.

**Comment by mellinoe** [comment]
FWIW, the reference to NETStandard.Library is still being inserted in a recent build (the version included when dogfooding VS 2017). 

```
dotnet --info
.NET Command Line Tools (1.0.0-rc3-004517)

Product Information:
 Version:            1.0.0-rc3-004517
 Commit SHA-1 hash:  691189ef91

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004517
```
Now I have all of these when i run `dotnet migrate`:

```
    <PackageReference Include="NETStandard.Library" Version="1.6.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.0.11" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.1.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.0.0" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.1.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.1.0" />
```

**Comment by livarcocc** [comment]
Is this for Imgui.NET project still? If so, I can take a look.

**Comment by mellinoe** [comment]
> Is this for Imgui.NET project still

Yes

**Comment by ThadHouse** [comment]
The project I posted about earlier is still doing this as well. All other dependencies are individualized, however that dependency is still there. Running dotnet restore even spits out the following error.
```
C:\Program Files\dotnet\sdk\1.0.0-rc4-004599\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(101,5): warning : A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs [C:\Users\thadh\Documents\GitHub\robotdotnet\NativeLibraryUtilities\src\NativeLibraryUtilities\NativeLibraryUtilities.csproj]
```

Also noticed that the build for .NET 3.5 is broken with a migrate. Where should I create an issue for that?

For reference, here is my project.json file, and below is the migrated file using 1.0.0-rc4-004599
https://github.com/robotdotnet/NativeLibraryUtilities/blob/master/src/NativeLibraryUtilities/project.json
https://github.com/robotdotnet/NativeLibraryUtilities/blob/prev4/src/NativeLibraryUtilities/NativeLibraryUtilities.csproj

**Comment by livarcocc** [comment]
The .NET3.5 problem is being tracked here: https://github.com/dotnet/sdk/issues/665.

The error you put above is actually a warning and we are tracking addressing it here: https://github.com/dotnet/cli/issues/5346
