### ISSUE TITLE
No mention of NuGet.Client in ThirdPartyNotices.txt

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#4854]
A built cli includes various dlls built from from NuGet.Client project. It also includes a LICENSE file and a ThirdPartyNotices.txt. There's no mention of NuGet.Client or its license (Apache 2.0) in either the main LICENSE file or in ThirdPartyNotices.txt.

**Comment by piotrpMSFT** [comment]
@rrelyea do we need to add?

**Comment by leecow** [comment]
@rrelyea this would potentially be a ship blocker for Red Hat.

**Comment by omajid** [comment]
@leecow It doesn't affect us immediately. We generally look at the set of licenses on the entire RPM - in this case all of .NET Core - and since at least one other piece of code in .NET Core is under Apache 2.0, this license is covered. But the packaging guidelines strongly encourage us to make sure the list of  licenses is complete and all licenses are installed on the user's machine.

**Comment by leecow** [comment]
Thanks for the clarification @omajid !

**Comment by blackdwarf** [comment]
@leecow @omajid do we need to add this for RTM?

**Comment by leecow** [comment]
@blackdwarf yes, let's make sure it's added to whichever file makes the most sense.

**Comment by blackdwarf** [comment]
@leecow ok, not a problem. We follow the same format as existing third party notices, correct?
