### ISSUE TITLE
Version with build number (TFS or VSTS)

### ISSUE THREAD

**Issue by Allann** [dotnet/cli#4859]
This is more a question than an issue.  

Any hints on how to update the version number to use the build number from TFS or VSTS?  Previously I used a powershell script that was run prior to the build step that changed the version number in the assembly information, but now the version is contained in the project json file this script is useless.

Must also include 3 numbers in the version now and star the last (4.6.2.-*) where --version-suffix will change the last part.  This means I can't insert the build number (4.6.16334,03) which represents the major, minor, day and build instance for the day.  This format is very important to us and the way we use CI. 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@Allann please try out the preview3 tooling which moves from project.json to csproj. I'll be curious if you run into issues with using your existing version number generators.

**Comment by Allann** [comment]
I am unable to do that for a while.  unless there is an easy way to upgrade to that version without affecting the remaining applications.  Limited to using 1.0.0-preview2-003131 for now.

**Comment by Allann** [comment]
btw the link in the description for this project doesn't work.  Has a space in the hyperlink that fails to navigate.  (https://docs.microsoft.com/en-us/dotnet)

**Comment by blackdwarf** [comment]
@Allann by default, the tools install side-by-side. You can use a global.json file to constrain the version that a given project needs. More information is on https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md.

**Comment by Allann** [comment]
@blackdwarf It appears to use the preview3 tools I also need to install VS2017RC, this implies it's a little more than a side-by-side install.  To install I also need to add/update the .NET Core and Docker (Preview).
**rant**
It's so hard to try and use old/new versions these days.  IMHO it's like going back to the old COM days with DLL hell.  Semantic versioning seems to be a thing of the past with many of these newer packages updating "requirement" just because they can and not because they need to.  Might just be me, but not being part of the "in-crowd" and trying to support commercial software makes updates and side-by-side installs very nerve racking and our code churn on a single update normally takes at least a couple of days to settle down the development environments let alone our test and staging environments. Days we just can't afford.  I understand I am using bleeding edge components, but they were released as production ready products.
**rant over**

I will create a virtual dev box soon and try VS2017 and Preview3 as soon as I get some time.

**Comment by blackdwarf** [comment]
@Allann that should not be the case. If you just need command line tooling you can install just that. command line tools will tive you acess to  buld tools you need. Of course, for full nice code editing experience, you do need VS or similar.  

Can I ask why did you feel you need to install VS2017 as well? Was there a problem with just installing the CLI tools?

**Comment by Allann** [comment]
It was an assumption.  How I came to that:

1. Clicked on your link, and seeing no instructions on how to install just the cli, 
2. I went to the root page for cli (https://github.com/dotnet/cli), still nothing, but used the Getting started page for Preview 2 bits.
3. There I found the Command line/other link
4. Selected all downloads from step one hoping there would be a an option
5. And there I found the Preview 3 link, chose current
6. From there I clicked Installing .NET core tools, back to install guide again...  round and round

It is quite complicated to find the install instructions for just the tools.  If they are around, I couldn't find it.

**Comment by blackdwarf** [comment]
@Allann sorry for the confusion. I will be making a PR to get the README and that doc updated with the links to Preview 3 and 4 (once it comes out). In the meantime, https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md
 is the link where you can find the Preview 3 pertinent information.

**Comment by csbondeson** [comment]
Was there a resolution to this? I need to do the same thing in Jenkins. I have yet to find a way to set the version number during the build, only the version suffix.

**Comment by dasMulli** [comment]
@csbondeson have a look at https://github.com/dotnet/cli/issues/3778#issuecomment-287556821 and following.

**Comment by dasMulli** [comment]
btw.. with csproj tooling you can also define a completely custom properties to use during build.
e.g.:
```xml
<PropertyGroup>
  <Day Condition=" '$(Day)' == '' ">0</Day>
  <BuildNumber Condition=" '$(BuildNumber)' == '' ">0</BuildNumber>
  <VersionPrefix>4.6.$(Day).$(BuildNumber)</VersionPrefix>
</PropertyGroup>
```

which could be used from CI using:
```sh
dotnet msbuild /t:Restore;Pack /p:Configuration=Release /p:Day=123 /p:BuildNumber=3
```
(note that the restore is necessary because of https://github.com/NuGet/Home/issues/4337)
This may solve @Allann's original issue.

**Comment by csbondeson** [comment]
@dasMulli Thank you for the quick reply. How would your example with BuildNumber be used with the dotnet pack command?

**Comment by dasMulli** [comment]
the pack commands basically is the same as `dotnet msbuild /t:Pack`, the separation i showed is to work around that nuget issue when you want the same version on referenced projects. When you have no project references, `dotnet pack -c Release /p:YourProperty=SomeVaule` works just as fine.

If you only need the version suffix to work, make sure you only have `<VersionPrefix>` defined in your `.csproj` file, not `<Version>`, as mentioned in the other cli issue i linked before.
Then you can use `dotnet pack -c Release --version-suffix beta1-123` or - with multiple package references - `dotnet msbuild /t:Restore;Pack /p:Configuration=Release /p:VersionSuffix=beta1-123`

**Comment by csbondeson** [comment]
Thank you very much @dasMulli I have been looking on and off for the last few days and this has helped a lot.

**Comment by dasMulli** [comment]
You're welcome. While at it, one of the new csproj advantages is that you can condition on anything - so to make sure you don't accidentally publish a dev build. I've found it useful to append `-dev` when in `Debug` configuration to make sure i don't accidentally publish a debug build:
```xml
<VersionSuffix Condition=" '$(Configuration)' == 'Debug' ">dev</VersionSuffix>
```
Any command line parameter will overrule this definition but it's useful when developing.
This also makes the assembly details show `X.Y.Z-dev` as file version in windows explorer (=> `AssemblyInformationalVersionAttribute`)

**Comment by livarcocc** [comment]
It seems like @dasMulli addressed the issue here. Closing, please re-activate if I got this wrong.

**Comment by Allann** [comment]
It appears we are going to have to move our developers onto VS2017 since there is no love for VS2015 or earlier, if we are wanting to do ASP.NET Core development.  
Hopefully this space will start to settle down now so that we can stop doing rework due to changes and get on with some serious production quality development.
We managed to create some PS scripts that did what we needed to change the appropriate files during the build cycle.  It's dirt but it works for our situation.
Happy for this to stay closed as it offers a worthwhile solution for those on the newer release.

**Comment by BoubakrEchieb** [comment]
@dasMulli  After setting VersionPrefix in csproj file, haw can i read it on controller to show it in the footer of my app .

**Comment by dasMulli** [comment]
E.g. via

```c#
var version = Assembly.GetEntryAssembly()
    .GetCustomAttribute<AssemblyInformationalVersionAttribute>()
    .InformationalVersion;
```

or `typeof(MyClass).Assembly.…`

**Comment by BoubakrEchieb** [comment]
@dasMulli , i'm using TFS 2017 for CI, Version defined in csproj file as below should be auto-incremented after evry TFS build, 
```
<PropertyGroup>
    <Major Condition=" '$(Major)' == '' ">1</Major>
    <Minor Condition=" '$(Minor)' == '' ">0</Minor>
    <Patch Condition=" '$(Patch)' == '' ">0</Patch>
    <VersionPrefix>$(Major).$(Minor).$(Patch)</VersionPrefix>
</PropertyGroup>
```
have you any idea how to do this ?

**Comment by dasMulli** [comment]
A few options..

* Use [Nerdbank.GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning) <- go for that one to get good control over the version components

* Replicate roslyn's wildcard pattern or similar https://github.com/dotnet/cli/issues/6923#issuecomment-354095128 which is what "1.0.*.*" did before (ugly but it works, gives you a new version every 2 seconds)

* Do it yourself and read git commit counts during the build and build a version from it - this has to be done in a target (e.g. [this gist](https://gist.github.com/dasMulli/6d9580ba52770d8f1abae1fc8fb1a6dd) but without the padding and suffixes)
  * [Example](https://github.com/dasMulli/dotnet-win32-service/blob/c1941d6bbfaf818f670a7aedd286b1beef17a302/Directory.Build.targets) where this is used in prerelease versioning and a [NuGet package](https://github.com/dasMulli/SimpleGitVersion) containing that but don't use that yet (will require upcoming NuGet 4.6.0 to "really" work)
  * Using it for prerelease versioning will require additional build steps for when you want to build without or with **and** without suffix (e.g. different build, multiple outputs etc.).
