### ISSUE TITLE
dotnet compile and run commands should support a runtime option

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#486]
The `dotnet compile` command depends on a RID in order to produce the .deps file.  The current implementation auto detects the RID.  There should be an option to override the auto detect logic just as there is for the `restore` and `publish` commands.  If this is added for the compile command then it also makes sense to add it to the run command since it wraps the compile command.

**Comment by davidfowl** [comment]
Run and compile are about running on the "current" RID. publish is where you can choose.

**Comment by piotrpMSFT** [comment]
@davidfowl, I agree on `run` but `compile is less clear. 

How do we cross-compile if `compile` doesn't take a runtime?

**Comment by blackdwarf** [comment]
Tracking this in #501.
