### ISSUE TITLE
Linux cannot restore against protocol 2 nuget api

### ISSUE THREAD

**Issue by stvndall** [dotnet/cli#4860]
## Steps to reproduce
~/.nuget/NuGet/NuGet.Config, add an api using v2 of the nuget server. IE Klondike. 
```<add key="raphael" value="http://raphael:6400/api/odata" protocolVersion="2"/>```

## Expected  behavior
Be able to search on the v2 api, and find it a package is on the server. Return package if found. Move on if not found.

## Actual behavior
error: Response status code does not indicate success: 404 (Not found).
error: Failed to retrieve information from remote source 'http://raphael:6400/api/FindPackagesById()?id='Grips.IocContainer''.

It appears to be ignoreing the protocolVersion switch.

This works on windows. But not on linux

## Environment data
 Version:            1.0.0-preview2-1-003155
 Commit SHA-1 hash:  d7b0190bd4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64

**Comment by piotrpMSFT** [comment]
Moved to NuGet repo
