### ISSUE TITLE
.NerCoreApp and .Net 4.6.2 frameworks in same project gives compile error.

### ISSUE THREAD

**Issue by roshantarudkar** [dotnet/cli#4862]
I am trying to get redissessionprovide package from .net 4.6.2 thats the reason i have two framework.. as shown in below project.json..when i compile the project it gives me error as mentioned in below screen shot,..Looks like it is looking for same assembly in both frameworks ,i suspect its conflicting..any resolution on this ? can we make assemblies point to core only default.
 I have below entries in project.json
` "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.1",
          "type": "platform"
        },
        "Microsoft.AspNetCore.Diagnostics": "1.1.0",
        "Microsoft.AspNetCore.Mvc": "1.1.0",
        "Microsoft.AspNetCore.Razor.Tools": {
          "version": "1.0.0-preview2-final",
          "type": "build"
        },
        "Microsoft.AspNetCore.Routing": "1.1.0",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
        "Microsoft.AspNetCore.StaticFiles": "1.1.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
        "Microsoft.Extensions.Configuration.Json": "1.1.0",
        "Microsoft.Extensions.Logging": "1.1.0",
        "Microsoft.Extensions.Logging.Console": "1.1.0",
        "Microsoft.Extensions.Logging.Debug": "1.1.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
        "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",      
        "Microsoft.Extensions.Caching.Redis": "1.1.0"
      }
    },
    "net462": {
      "dependencies": {
        "Microsoft.Web.RedisSessionStateProvider": "2.2.2"
      }
    }
  },

`
But when i compile then it gives me compile error:

  
![error1](https://cloud.githubusercontent.com/assets/13056368/20715807/51165e5a-b61e-11e6-8061-02765fb94b36.png)

**Comment by svick** [comment]
I think you misunderstood what specifying two frameworks does. It's not "I want to use packages from both frameworks at the same time", it's "I want to be able to run on both frameworks, possibly using different packages on each".

So, if you need to use a package that's only on `net462`, then your whole application needs to be on `net462` (and it won't have the advantages of .Net Core like being able to run cross-platform). One way to do that would be:

```json
"frameworks": {
  "net462": {
    "dependencies": {
      "Microsoft.Web.RedisSessionStateProvider": "2.2.2",
      "Microsoft.AspNetCore.Diagnostics": "1.1.0",
      "Microsoft.AspNetCore.Mvc": "1.1.0",
      "Microsoft.AspNetCore.Razor.Tools": {
        "version": "1.0.0-preview2-final",
        "type": "build"
      },
      "Microsoft.AspNetCore.Routing": "1.1.0",
      "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
      "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
      "Microsoft.AspNetCore.StaticFiles": "1.1.0",
      "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
      "Microsoft.Extensions.Configuration.Json": "1.1.0",
      "Microsoft.Extensions.Logging": "1.1.0",
      "Microsoft.Extensions.Logging.Console": "1.1.0",
      "Microsoft.Extensions.Logging.Debug": "1.1.0",
      "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
      "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
      "Microsoft.Extensions.Caching.Redis": "1.1.0"
    }
  }
},
```

**Comment by piotrpMSFT** [comment]
Thanks, @svick
