### ISSUE TITLE
Provide command to summarize packages used, their version and license

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#4863]
Licenses from the open sources packages often require to publish the license text.

It would be great if a single command could create an overview of the packages used used, their version and license. This command should also download the license texts.

**Comment by piotrpMSFT** [comment]
@rrelyea is this something that is already under consideration in NuGet?

**Comment by tmds** [comment]
Extending: also include metadata that points to the source repository and revision used to build the package (e.g. git url, commit id).

**Comment by piotrpMSFT** [comment]
@tmds can you move this to nuget/home repo? CLI doesn't have access to this data and we take drops of NuGet, we don't build it.
