### ISSUE TITLE
dotnet cli doesn't mention the .NET Core version

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#4864]
`dotnet --version` mentions a version, but it doesn't correspond to the .NET Core version. I have had more than one person ask me about why their ".NET Core 1.1" installation is broken and shows "1.0.0-preview-2-1" as the version.

## Steps to reproduce

Run `dotnet --version`

## Expected  behavior

It should show the .NET Core version first and in the most obvious way. The CLI version should be shown too (and probably that of corefx, coreclr and so on), but the overall product version should be first.

## Actual behavior

It shows (just) the cli version

## Environment data
`dotnet --info` output:

    .NET Command Line Tools (1.0.0-preview2-1-003175)
    
    Product Information:
     Version:            1.0.0-preview2-1-003175
     Commit SHA-1 hash:  bb053ed000
    
    Runtime Environment:
     OS Name:     rhel
     OS Version:  7.3
     OS Platform: Linux
     RID:         rhel.7.2-x64

**Comment by vcsjones** [comment]
Related / dupe: #3773

**Comment by piotrpMSFT** [comment]
Let's track in #3773
