### ISSUE TITLE
Preview 2+ tooling appears to ignore include directive in publishOptions

### ISSUE THREAD

**Issue by davidpeden3** [dotnet/cli#4867]
## Steps to reproduce

- Create a project and add a `config.json`
- add a `publishOptions` to `project.json`:

`"publishOptions": {
		"include": "config.json"
	}`

- run `dotnet publish`

## Expected  behavior

The publish folder should contain `config.json`.

## Actual behavior

With SDK 1.0.0-preview1-002702, `config.json` is published.

With the following SDKs:
- 1.0.0-preview2-003131
- 1.0.0-preview2.1-003155
- 1.0.0-preview2-1-003177

`config.json` is not published.

## Environment data
`dotnet --info` output:

**Works:**

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Doesn't work:**

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

.NET Command Line Tools (1.0.0-preview2-1-003155)

Product Information:
 Version:            1.0.0-preview2-1-003155
 Commit SHA-1 hash:  d7b0190bd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by davidpeden3** [comment]
Turns out that the path parameters passed to `dotnet publish` no longer tolerate  a leading `.\`.

doesn't work:	`dotnet publish .\src\Host\project.json --output .\src\Host\bin\release\publish --configuration Release`

works:		`dotnet publish src\Host\project.json --output src\Host\bin\release\publish --configuration Release`

**Comment by piotrpMSFT** [comment]
Thanks @davidpeden3. I'm sure this workaround will help many.
