### ISSUE TITLE
Upgrading Microsoft.NETCore.App from 1.0.1 to 1.1.0 removes type: platform

### ISSUE THREAD

**Issue by HakanL** [dotnet/cli#4869]
## Steps to reproduce

Visual Studio 2015 Update 3, all latest .NET Core tools/extensions installed (including .NET Core 1.1 SDK).

Creating a new .NET Core Command line project adds this dependency to the project.json:
`
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },
`

If you then go under references and upgrade the NuGet packages to the latest (1.1.0) then the type:platform above is removed and the build fails saying runtimes section is missing.

`
   "dependencies": {
       "Microsoft.NETCore.App": "1.1.0"
   },
`

## Expected  behavior
It should keep the type:platform attribute when upgrading the Microsoft.NETCore.App NuGet package.

## Actual behavior
type:platform is removed.

## Environment data

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by davidfowl** [comment]
Seems like a nuget ui bug no?

**Comment by HakanL** [comment]
I apologize if this is not the right place for this issue, I wasn't sure where to report this, if it was related to NuGet or the Microsoft.NETCore.App issue.

**Comment by HakanL** [comment]
Whatever is updating the project.json file when upgrading from within Visual Studio, I guess.

**Comment by davidfowl** [comment]
Using the nuget ui right?

**Comment by HakanL** [comment]
Yes, "Manage NuGet Packages..." menu option in the solution explorer. I just wasn't sure what that ultimately ended up calling.

**Comment by HakanL** [comment]
If you think this belongs to the NuGet project then I'll be happy to move it over?

**Comment by HakanL** [comment]
Somewhat related item: https://github.com/dotnet/core/issues/267

**Comment by davidfowl** [comment]
Yep. The CLI isn't involved here. It's a nuget issue.

**Comment by blackdwarf** [comment]
Closing this one, please reopen on Nuget/Home.
