### ISSUE TITLE
Multiple errors converting .net core to csproj

### ISSUE THREAD

**Issue by jeffkl** [dotnet/cli#4871]
Moving https://github.com/Microsoft/msbuild/issues/1410 on behalf of @gilmishal

> I have opened this [SO](http://stackoverflow.com/questions/40892034/multiple-errors-converting-net-core-to-csproj) question, and decided it might be worth asking here as well.

> basically I have migrated an asp.net core project from xproj to csproj for using VS2017RC. Now everything went to hell... getting a lot of msbuild errors, Visual Studio 2015 can't load nuget packages. VS2017 manages to build the project - but Intellisense is going crazy..

I'm pretty certain that this is a one-way upgrade and that this project won't work in VS2015 any more after migration. This could be a problem with migration, which is owned by the CLI, or it could be an issue with the SDK, which is owned by another team.  The CLI folks should be able to rule out migration.

**Comment by gilmishal** [comment]
Thanks Jeff,

I kinda figured that the update was one way eventually... I must add that I somewhat managed to fix my issue eventually. I changed the .csproj to be exactly like the one of a new core class library, and reloaded the nuget packages. However, now my project only targets the netstandard1.6 and it is necessary that it targets the net461 as well. That however I couldn't fix.

**Comment by gilmishal** [comment]
Also, I am getting an error that it is unable to resolve the project for '.NETStandard,Version=v1.6'
when referencing from an other netstandard project - which is odd The project is there, and they are both .netstandard1.6

**Comment by 333fred** [comment]
Moved to dotnet/sdk#447
