### ISSUE TITLE
Windows and Mac SDK installer branding is incorrect for the 1.0.3 release

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#4872]
Currently "Microsoft .NET Core 1.0.2 - SDK 1.0.0 Preview2-003154"

Should be "Microsoft .NET Core 1.0.3 - SDK 1.0.0 Preview2-003154"

Windows arp entry also needs the update.

**Comment by piotrpMSFT** [comment]
Working on a fix now. Note, the suffix will change from 3154 to something larger.

**Comment by piotrpMSFT** [comment]
Will be fixed by https://github.com/dotnet/cli/pull/4873

**Comment by piotrpMSFT** [comment]
Fixed by #4873
