### ISSUE TITLE
Differentiate telemetry based on what is running dotnet.exe

### ISSUE THREAD

**Issue by jeffkl** [dotnet/cli#4875]
It would be nice if telemetry events had a property indicating what was running dotnet.exe.  For example, VSCode will be executing it and possible Visual Studio.  It would be great if we could differentiate the callers so we could have an idea about usage.

More callers of dotnet:
* Command window (bash or cmd)
* VSCode
* Visual Studio
* VSTS or other hosted build environments

CC @Sarabeth-Jaffe-Microsoft

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@DustinCampbell @piotrpMSFT @blackdwarf

**Comment by piotrpMSFT** [comment]
CLI already offers a [`DOTNET_CLI_TELEMETRY_PROFILE`](https://github.com/dotnet/cli/src/dotnet/Telemetry.cs#L94) environment variable that allows callers to identify the context in which the CLI is running. We treat this as a black-box string so anything can be passed in and will be reported. We typically use it as a `;`-delimited list to aggregate context from multiple components. 

CLI builds use this to help us identify usage from the repo from other usage:
https://github.com/dotnet/cli/build/Microsoft.DotNet.Cli.Prepare.targets#L123

Seems we can have other environments choose to use this as well by appending an element to the string.

**Comment by piotrpMSFT** [comment]
Closing the issue. If there is a gap I'm not seeing, please do reopen.

**Comment by DustinCampbell** [comment]
That's not a terrible solution. :smile:

Is there a particular string you'd like the C# VS Code extension to use, since it's your telemetry reporting.

**Comment by piotrpMSFT** [comment]
`invoker:VSCode;invoker{version|architecture|whatever};` ?
