### ISSUE TITLE
Update CLI to include offline SDKs for Web and Core

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4887]
- [x] Update MSBuild to 15.1.0-preview-000451-02
 - [x] Add Core SDK to CLI layout
 - [x] Add Web SDK to CLI layout
 - [x] Add NuGet Pack SDK to CLI layout
 - [ ] Add Test SDK to CLI layout
 - [x] Update Core Template
 - [x] Update Web Template

/cc @srivatsn @dsplaisted @MattGertz @rainersigwald @AndyGerlicher @Sarabeth-Jaffe-Microsoft  @blackdwarf @livarcocc @mlorbetske @rrelyea

**Comment by rainersigwald** [comment]
Don't forget the NuGet Pack SDK.

**Comment by piotrpMSFT** [comment]
Thanks @rainersigwald. Updated, also adding Test SDK

**Comment by piotrpMSFT** [comment]
If folks could give me versions for all the Adds without versions, I can make fwd progress

**Comment by rainersigwald** [comment]
MSBuild for CLI should be version `15.1.0-preview-000451-02`.

(The off-by-one from the VS version is a long sad story, and we'll fix it before the next prerelease: https://github.com/Microsoft/msbuild/issues/1426. There is no code change between 450 and 451, just a version-number-bump commit that allowed the build to finish indexing symbols.)

**Comment by piotrpMSFT** [comment]
Fixed inline. PR for bumping the version is coming now.

**Comment by spboyer** [comment]
Recommend adding Web API template to the CLI

**Comment by piotrpMSFT** [comment]
@mlorbetske

**Comment by piotrpMSFT** [comment]
#4675 tracks templates folks would like to see added, @spboyer. I'll make sure WebAPI is listed there.

**Comment by livarcocc** [comment]
I don't think there is anything else to be done here. Closing this issue.
