### ISSUE TITLE
DotNetRestore http cache and failed packages

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#4905]
## Steps to reproduce
update project.json and change a dependency to a new version that doesn't yet exist on nuget.org.
do a `dotnet restore`
The restore will fail correctly
now publish that version of the package to nuget.org
do a `dotnet restore`
The restore continues to fail.
Do a `dotnet restore --no-cache`
The restore will pass.

## Expected  behavior
I would not expect the http cache to cache responses to "failures" or missing packages.

## Actual behavior
I can only assume based on the steps above that information about the missing package is being cached in the http cache.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
This issue belongs in https://github.com/nuget/home.

**Comment by dazinator** [comment]
Ok thanks, have raised it there.
