### ISSUE TITLE
dotnet-new doesn't cleanup when project already exists

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/cli#4908]
When running dotnet new multiple times with different templates, it leaves behind extra files instead of doing nothing.

## Steps to reproduce
Let's say our working directory is "install"
`dotnet new -t console`
`dotnet new -t lib`

## Expected  behavior
The working directory is left with the generated files from `dotnet new -t console`:
install.csproj
Program.cs

## Actual behavior
The working directory contains:
$projectName$.csproj
install.csproj
Library.cs
Program.cs

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004178)

Product Information:
 Version:            1.0.0-preview4-004178
 Commit SHA-1 hash:  4311926366

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
Take a look at #4909. Let's pursue the easy fix here, if we can.

**Comment by blackdwarf** [comment]
This is not a problem with `new3`, that is, it is fixed there.
