### ISSUE TITLE
dotnet-new fails if "$projectName$.csproj" exists

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/cli#4909]
## Steps to reproduce
Create a file named "$projectName$.csproj"
Run `dotnet new` in that directory
## Expected  behavior
A new project is generated.

## Actual behavior
Fails with "Creating new C# project failed, directory already contains $projectName$.csproj"

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004178)

Product Information:
Version: 1.0.0-preview4-004178
Commit SHA-1 hash: 4311926

Runtime Environment:
OS Name: Windows
OS Version: 10.0.14393
OS Platform: Windows
RID: win10-x64

**Comment by svick** [comment]
Why would you expect it to succeed? You're trying to create a project in a directory that already contains one. I think doing nothing and showing an error message (so that you can delete the old project, if that's what you wanted) is the right thing to do here.

**Comment by Thealexbarney** [comment]
I would expect it to do nothing if the directory contained a .csproj with the same name as the directory. Here it fails if a file with the literal name "$projectName$.csproj" exists instead of creating a new project with the directory name, which is what it does if a .csproj with any other name already exists.

dotnet-new simply extracts the zip file containing the template to the current directory and then renames the .csproj file, causing the error.

**Comment by danmosemsft** [comment]
I don't know why someone would create a file named `$projectName$.csproj`, but I know that if I do `dotnet new`, then delete the `program.cs`, then do `dotnet new` again, I get such a file created.

**Comment by piotrpMSFT** [comment]
@krwq @seancpeters  @blackdwarf @mlorbetske before this becomes complicated, I'd like for the design to be that `dotnet new` fails if the target directory is not empty. This will deal both with this issue and with #4908.

**Comment by blackdwarf** [comment]
@piotrpMSFT the only issue here being if you want to drop a SLN file using this command, for instance. That would not be OK to fail if the dir is not empty.

**Comment by piotrpMSFT** [comment]
If you're building a solution from sln up, that would be fine, right? It's only if you're retroactively adding a sln that it's a problem?

**Comment by piotrpMSFT** [comment]
VS4M, btw, gets around this by always putting new solutions in a new directory. You can only specify the parent directory of the sln directory. Perhaps that's a better approach?

**Comment by blackdwarf** [comment]
@piotrpMSFT yes, if you, for instance, migrate off project.json and have a bunch of csproj files and you would like to create a new SLN file and use our CRUD commands to populate it with projects. 

Regardless of where you put it, right, you would need to not fail on a non-empty dir (unless we have a different definition of "empty" here 😃 ). For example, this structure:

```shell
├───slnfest
│   ├───proj1
│   ├───proj2
│   ├───proj3
│   └───test
│       ├───unittest1
│       └───unittest2
```

And you want to put the SLN file in the root (`slnfest`) dir above, you don't want it to fail because the dir is not empty.

**Comment by piotrpMSFT** [comment]
ok, what algorithm do you propose for dealing with non-empty directories like in this issue and 4908?

**Comment by blackdwarf** [comment]
@piotrpMSFT since `new3` is coming in for our next release and definitively for RTM, I've taken a look at its behavior and it will fail/not create the template if the dir is not empty. 

As discussed, we will have a different way to generate the SLN file so my comments above do not apply anymore.

**Comment by krwq** [comment]
@piotrpMSFT should empty be defined as "no other files in a directory" (directories allowed)?

**Comment by blackdwarf** [comment]
@krwq if you go down that path, you will have a problem with web templates because they will contain directories for controllers, views etc. I would say empty as in 0 inodes. :) @piotrpMSFT thoughts?

**Comment by blackdwarf** [comment]
Actually, this was wrong assumption on my part. We cannot do the "0 inodes" because there is a valid case of creating a project next to an existing project. 

Regardless, the `new3` command (which will become `new` at 1.0.0) already fails for a full template if the directory is not empty. This solves this issue. Closing. Please reopen if this repros with `new3` in the latest bits.
