### ISSUE TITLE
Permissions issue in PKG installer

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#492]
We've had a report that permissions were incorrectly set by PKG installer. Folks could not use the product without running `sudo chmod -R 555 /usr/local/share/dotnet`. Can you take a quick look?

**Comment by gregg-miskelly** [comment]
I ran into this. I can't say for sure, but the issue may have been triggered for me because the account which setup the box originally is different from my account.

**Comment by blackdwarf** [comment]
@gregg-miskelly ah, that one again. Can you try to test out the PKG installer with the same account and see if it repros?

**Comment by gregg-miskelly** [comment]
I don't have access to that account, so not easily. Can you see if you can repro the issue with a secondary account on your box?

**Comment by blackdwarf** [comment]
OK, will do. This is something very weird with the PKGs and so far I haven't found a better solution for it than to just `sudo chmod 755` the install target in the postinstall script. Which is ugly, but it seems to be the only recourse available.

**Comment by blackdwarf** [comment]
OK, reproed. Will take a look.
