### ISSUE TITLE
dotnet pack detailed log?

### ISSUE THREAD

**Issue by milla** [dotnet/cli#4920]
## Steps to reproduce
dotnet pack

## Expected  behavior
Successfully generate nuget package files

## Actual behavior
throw error:
Sequence contains no matching element
cannot find any other info, not able to identity issue

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  xxx

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by blackdwarf** [comment]
@milla can you share your project? Also, have you ran `restore` beforehand?

**Comment by piotrpMSFT** [comment]
Once you migrate to preview3 you will have access to `dotnet pack /v:diag` which is very informative about what is happening. There is not a detailed log for pack in preview2 and, given the fundamental changes between preview2 and preview3 there won't be an opportunity for us to add one atop the project.json infrastructure.
