### ISSUE TITLE
When running tests via VSTest, only one framework (of multiple) will run

### ISSUE THREAD

**Issue by ekumlin** [dotnet/cli#4927]
## Steps to reproduce
1. Create a .NET Core class library, with a `project.json` containing two frameworks:
    ```
    {
      "version": "1.0.0-*",
      "dependencies": {},
      "frameworks": {
        "net452": {},
        "netstandard1.6": {
          "imports": "dnxcore50",
          "dependencies": {
            "NETStandard.Library": "1.6"
          }
        }
      }
    }
    ```
1. Create a second .NET Core class library as a test project containing MSTest/VSTest tests, also using two frameworks:
    ```
    {
      "version": "1.0.0-*",
      "testRunner": "mstest",
      "dependencies": {
        "dotnet-test-mstest": "1.1.2-preview",
        "MSTest.TestAdapter": "1.1.6-preview",
        "MSTest.TestFramework": "1.0.7-preview"
      },
      "frameworks": {
        "net452": {},
        "netcoreapp1.0": {
          "imports": [
            "dnxcore50",
            "portable-net45+win8"
          ],
          "dependencies": {
            "Microsoft.NETCore.App": {
              "version": "1.0.0",
              "type": "platform"
            },
            "Microsoft.CodeCoverage": "1.0.1"
          }
        }
      }
    }
    ```
1. Add tests to the test library.
1. Run (from a developer prompt in the test library's directory): `vstest.console.exe project.json /UseVsixExtensions:true`

## Expected behavior
All tests in the test project should run once for each framework.

## Actual behavior
All tests in the test project run on only one framework. (In the case above, `netcoreapp1.0`; the tests will **not** be run on `net452`.)

If the tests are run explicitly through `dotnet test`, both frameworks execute.

Upon discussion with the VSTest team and trace logs, it was determined that:

> It looks like an issue while executing the tests in the design time mode (from test adapter). Once the test discovery for a single framework is complete, cli returns a TestDiscovery.Completed message which forces the adapter to stop discovering any more tests. 
> 
> It looks like cli is always discovering .NETStandard tests first irrespective of the order in project.json.

I have provided traces of both the calls to `dotnet test` and `vstest.console.exe` on PasteBin (the project and test names are sanitized): http://pastebin.com/4nNK4YYq

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14971
 OS Platform: Windows
 RID:         win10-x64
```

**Note:** Moving to the new `csproj` model is not a feasible solution. We cannot update our dev team to VS 2017 preview nor our centralized build machines to alpha versions of `dotnet`.

**Comment by livarcocc** [comment]
@Faizan2304

**Comment by ekumlin** [comment]
@livarcocc @Faizan2304 Is this being looked into?

**Comment by livarcocc** [comment]
I just noticed that this is for preview2. Sorry for not realizing that earlier.

I believe this is a limitation of tests in VS 2015. To run multi-tfm tests, you need to use the command line dotnet test.

**Comment by ekumlin** [comment]
My initial impression was that both `dotnet` CLI and `vstest.console.exe` call the same test adapter to run their tests, so the adapter should be able to return the entire suite of tests in both scenarios. But in the logs linked in my original issue, it looks like there is a premature `TestDiscovery.Completed` returned when running under VSTest (but not under `dotnet` CLI).

Is it possible that the adapter can work around this limitation of VSTest?

**Comment by piotrpMSFT** [comment]
In 2015, as in this bug, the adapters were quite different. Once you migrate the project to RC3 [really, anything > preview3] you will move onto the new unified experience, @ekumlin. You can grab a build from the home page of this repo and run `dotnet migrate` to move your project forward.

I'm closing this issue as we don't plan to ship any more updates to project.json/preview2 tooling
