### ISSUE TITLE
Specifying preview 2 SDK in global.json does not effect operation of dotnet commands

### ISSUE THREAD

**Issue by michaeldaw** [dotnet/cli#4935]
I couldn't find an issue that detailed this problem, so maybe I'm just doing something wrong. According to this blog post: https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/ (in the section ".NET Core CLI Tools"), we should be able to create a global.json file in the project folder that indicates the dotnet cli should use the "1.0.0-preview2-003131" sdk. However, if I try to build a project.json project with the necessary global.json, an error occurs.

## Steps to reproduce
Install preview3 sdk.
add global.json to project folder indicating sdk version "1.0.0-preview2-003131" should be used.
```
{
    "sdk": {
        "version": "1.0.0-preview2-003131"
    }
}
```
run dotnet build

## Expected  behavior
The project is built using the data from project.json.

## Actual behavior
The following error:
```
>dotnet build
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
Can you share folder layout? In particular, where is the global.json, where are your project.json files, and where are you invoking the command?

The global.json should be in a common parent of the whole solution, and the command should be executed inside of that directory tree. Finally, you must have the specified version of the tools installed and available on the PATH [e.g. available to the CLI you're actually invoking]

**Comment by michaeldaw** [comment]
I have a single folder with global.json, project.json, and my source code. I thought this would be in line with the description in the blog post ("In order to continue using the earlier project.json-based tools on a per-project basis, create a global.json file in your project directory and add the “sdk” property to it."). 

I have both preview2 and preview3 of the sdk installed. I'm not sure what I would have to add to the path in addition to the path to dotnet.exe (c:\Program Files\dotnet). I tried adding "C:\Program Files\dotnet\sdk\1.0.0-preview2-003131" to the path, but that didn't seem to change anything.

In any case, I've been forcing myself to get used to the .csproj format. If there is in fact a problem, it will only affect people during the period of transition to csproj from project.json. It can probably be closed as irrelevant.
