### ISSUE TITLE
Is .net core support ARM

### ISSUE THREAD

**Issue by AllenMaz** [dotnet/cli#4937]
I have try to install .net core on my ubuntu16.04 on RASPBERRI PI
![image](https://cloud.githubusercontent.com/assets/16220839/20914646/ff8db4ea-bbbb-11e6-8938-42ddd14ea609.png)

But i got the errors:
![image](https://cloud.githubusercontent.com/assets/16220839/20914711/6da1985c-bbbc-11e6-979a-b848f77cf058.png)

Is that .net core not support arm arch?If i want to install or deploy my asp.net core project on RASPBERRY PI (ubun16.04 System) ,what should i do?

**Comment by vcsjones** [comment]
>Is that .net core not support arm arch?

Right now, no it does not official support. It is very much a work in-progress to get the CoreCLR running on ARM32: https://github.com/dotnet/coreclr/issues?utf8=%E2%9C%93&q=is%3Aissue%20ARM32

It is possible to build it and run on a Raspberry Pi at this point https://github.com/dotnet/coreclr/issues/3977#issuecomment-260608276, but to my knowledge it has not been packaged.

You should be able to run it if you build CoreCLR from the latest source.

**Comment by piotrpMSFT** [comment]
Thanks @vcsjones

**Comment by SuperSludge** [comment]
You could use Docker and ship your .netCore app as a container

**Comment by leonpw** [comment]
If you ship it in a container, then it will still not be supported. The underlying host of Docker will also be an ARM CPU.
