### ISSUE TITLE
In help text, include space between .NET and previous word

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#4942]
## Steps to reproduce
Run `dotnet help`

## Expected  behavior
Help text has spaces between words.

## Actual behavior
In some cases, there is no space between `.NET` and the previous word:
```
Commands:
...
  restore       Restore dependencies specified in the.NET project
...
  run           Compiles and immediately executes a.NET project
...
```

https://github.com/dotnet/cli/blob/7b109e4b53d556d1fa01e20245f46e5a3ce0490b/src/dotnet/commands/dotnet-help/LocalizableStrings.cs#L33

@vsccarl Looks like it happened during loc work, just happened to notice when trying out a newer CLI.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview4-004189)

Product Information:
 Version:            1.0.0-preview4-004189
 Commit SHA-1 hash:  29b824a6ff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\1.0.0-preview4-004189\sdk\1.0.0-preview4-004189
```

**Comment by livarcocc** [comment]
@vsccarl Can you please fix this? I imagine your fix will have to go into rel/1.0.0-preview4 and then be back ported to rel/1.0.0.

cc @piotrpMSFT
