### ISSUE TITLE
Build of CLI that supports project.json + NuGet 3.5.0-rc1

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#4946]
This is followup based on the discussion in https://github.com/dotnet/corefx/issues/14203.

The 4.4.0 CoreFx packages rely on the `netcoreapp1.1 => netstandard1.7` mapping added to NuGet as part of their 3.5.0-rc1 release. The `1.0.0-preview2-1-003177` does not support it and results in the package being restored incorrectly and consequently compilation to fail.

Is there a build of the CLI that supports project.json and supports this mapping?

**Comment by piotrpMSFT** [comment]
@pranavkm is the version in the preview2-1 branch too early? or too new?

**Comment by pranavkm** [comment]
We've tried using the following builds and it doesn't work:

```
1.0.0-preview2-003121
1.0.0-preview2-003131
1.0.0-preview2-1-003177
```

**Comment by livarcocc** [comment]
I don't think we have updated the NuGet version for a while in preview2 and preview2-1.

Both Preview2 and Preview2-1 have the below version NuGet.

```
"NuGet.Commands": {
      "version": "3.5.0-beta2-1484",
      "exclude": "compile"
    },
    "NuGet.CommandLine.XPlat": "3.5.0-beta2-1484",
```

These are branches that we haven't been actively developing at, because they are project.json based. Why do you need this? Can't you achieve this using preview3, for instance?

**Comment by pranavkm** [comment]
Does preview3 work with project.json? All I'm trying to do is update AspNet projects to consume CoreFx 4.4.0-* packages. I'd rather not lump it in with MsBuild migration since it would the scope of change and verification more extensive.

**Comment by pranavkm** [comment]
Out of curiosity, is your build capable of producing a one-off based on the preview2-* branch? I'd be open to sending a PR to make the update since it's most likely just a couple of NuGet package version updates.

**Comment by livarcocc** [comment]
When you submit a PR and it gets merged, a build will be automatically produced.

**Comment by pranavkm** [comment]
Great. I'll give it a try!

**Comment by pranavkm** [comment]
Thanks for merging this in!

**Comment by pranavkm** [comment]
Fixed in https://github.com/dotnet/cli/commit/5fbbb40658274a6a971b65141ee00ac681f9e48b

**Comment by pranavkm** [comment]
@livarcocc how would I know when the build is complete? Alternatively, could you point me to the installers \ versions for it once it's done?

**Comment by livarcocc** [comment]
I can paste here once it is done. It is only missing windows, which is currently running.

**Comment by abydal** [comment]
@livarcocc did the build finish?
I'm running into the same problem as @pranavkm 

Any pointers to a solution would be greatly appreciated :)

**Comment by livarcocc** [comment]
This is the build version: 1.0.0-preview2-1-003182.

Link for windows x64: https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/1.0.0-preview2-1-003182/dotnet-dev-win-x64.1.0.0-preview2-1-003182.exe

**Comment by abydal** [comment]
Thanks! Great!

**Comment by kierenj** [comment]
I don't mean to hijack - but I'm getting the same initial error as in https://github.com/dotnet/corefx/issues/14203 , the ambiguous namespaces for `Task<TResult>`.  I'm not running `1.0.0-preview2-1-003182`, my project itself only references NETCore.App 1.1.0 (as it always did).  
Any tips around how I can track down a solution?  For example, how to identify the (presumably) third-party or nightly MS assembly which introduces the problem, and how to resolve?

**Comment by abydal** [comment]
My understanding of this issue is that this is a problem related to the SDK, not the runtime.
Changing the SDK to `1.0.0-preview2-1-003182` in global.json did the trick. This worked for me, but I'm no expert here so I might be wrong.

**Comment by kierenj** [comment]
Ah - I made a typo. "I'm *now* running `1.0.0-preview2-1-003182`" - not "I'm *not*"!  I get the same errors.

**Comment by kierenj** [comment]
OK, by both using that SDK **and** updating my `NETCore.App` to `1.2.0-beta-*` (was 1.1.0), I get it to build locally.

But when I push to an Azure App Service, global.json is ignored (it doesn't have that build), uses `1.0.0-preview4-004233` and fails with xproj/new build system errors.  There's no wildcare spec for global.json (I raised an issue around this).  What are my options? :(
