### ISSUE TITLE
1.1 branch for install scripts for Ubuntu

### ISSUE THREAD

**Issue by brockallen** [dotnet/cli#4954]
Is there a 1.1 branch anywhere? I'm looking for a 1.1 version of the `scripts/obtain/dotnet-install.sh` file.

We're trying to programmatically install .NET Core 1.1 with project.json tooling on Ubuntu.

What's the magic?

**Comment by am11** [comment]
Tag [<kbd>v1.0.0-preview2-1-3177</kbd>]( https://github.com/dotnet/cli/releases/tag/v1.0.0-preview2-1-3177) has .NET Core 1.1 support.

For the script to obtain it, I would do something like:

```sh
git clone https://github.com/dotnet/cli --branch v1.0.0-preview2-1-3177 --single-branch

./cli/scripts/obtain/dotnet-install.sh
```

**Comment by brockallen** [comment]
Perhaps a more visible branch name would help. Thanks :)

**Comment by piotrpMSFT** [comment]
These are really orthogonal concerns. You don't actually care about the .NET Core version included in the SDK. This is just the one that the `dotnet` app runs on, and the one used by `dotnet new` templates. You can update those templates to target any `Microsoft.NetCore.App`... 1.0, 1.1, 1.2, whatever you like. You just need to be sure, if it's not a Standalone application, that you also install the appropriate runtime [unless it happens to match the one that shipped in the CLI]. You can use the same install script, but pass it the Shared Runtime version and the --shared-runtime flag.

**Comment by blackdwarf** [comment]
Given @piotrpMSFT answer above, I think that this issue has been resolved, so I'll close it. If in error, please reopen.

**Comment by JohnRusk** [comment]
See #5773 for what might be an easier alternative.  Namely @blackdwarf 's comment re using 

`--channel release/1.1.0`
