### ISSUE TITLE
Dotnet restore fails on solution level 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4956]
## Steps to reproduce
- Copy the project from \\scratch2\scratch\jinuj\TestSceanrio\VSMigrationDemo.zip
- Unzip to your machine
- run dotnet migrate under VSMigrationDemo\VSMigrationDemo
![image](https://cloud.githubusercontent.com/assets/12449387/20981082/ffae2e30-bc67-11e6-8ead-88b3a27087ac.png)

- run dotnet restore 
![image](https://cloud.githubusercontent.com/assets/12449387/20981096/0cacec16-bc68-11e6-948f-646b7b33bc29.png)
**Note**: dotnet restore on individual projects works

## Expected  behavior
dotnet restore on solution level should work

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/12449387/20981130/2d2a1842-bc68-11e6-9061-b7750be45aa6.png)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004215)

Product Information:
 Version:            1.0.0-preview4-004215
 Commit SHA-1 hash:  7a0d3e255a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004215

**Comment by jinujoseph** [comment]
#4604 looks like same issue ?

**Comment by livarcocc** [comment]
Yes. it is the same issue.

**Comment by jinujoseph** [comment]
want me to reopen that and close this ?

**Comment by livarcocc** [comment]
No. Jinu, this is happening because today dotnet migrate does not update your solution files. It only migrates your project.json/xproj files.

The PR to update the SLN files is currently out: https://github.com/dotnet/cli/pull/4949.

This is really a missing feature that we are working on right now. If you want, you can keep this open until that PR gets merged, and then you can try again. Otherwise. we can just go ahead and close it. However you prefer.

**Comment by jinujoseph** [comment]
lets keep this open , to re-verify once the PR is merged. Thanks.

**Comment by jinujoseph** [comment]
This should also fix the warning on "dotnet build solition " 

![image](https://cloud.githubusercontent.com/assets/12449387/20982278/a1a6dc9c-bc6c-11e6-8b94-179a8ba575f5.png)

**Comment by blackdwarf** [comment]
@livarcocc did we fix this?

**Comment by livarcocc** [comment]
Yes, but you still need to run dotnet migrate sln_file for the sln file to be updated.

**Comment by blackdwarf** [comment]
@jinujoseph does the above fix the issue?

**Comment by livarcocc** [comment]
@jinujoseph if you can still repro this, please re-activate. I have tried this a few times over the last couple days with success.
