### ISSUE TITLE
Migration: Add comprehensive tests when migrating an sln file

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#4958]
Consider the following scenarios:
1. Migrate a directory that already contains a .csproj file. This means after migration you will have two .csproj files in the directory. Ensure that the sln file references the correct one.

2. Migrate an sln file that references an xproj file where the xproj file contains a reference to another csproj file.

3. Migrate an sln file that references an xproj file where the xproj file references a project not in the sln.

**Comment by jgoshi** [comment]
This work will handle more complex cases. The fix for #4632 only handles basic scenarios.

**Comment by livarcocc** [comment]
```
dotnet migrate AspNetCoreWebApp_OnCore_Empty_1.sln
System.Exception: Unable to find any projects in AspNetCoreWebApp_OnCore_Empty_1.sln
  at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<GetProjectsToMigrate>d__26.MoveNext()
  at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
  at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass31_0.<Run>b__0()
  at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
  at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
Migration failed.
```

You can repro this by cloning https://github.com/balaTest/ProjectKTestProjects. Go to Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1 under that repo
and run dotnet migrate <sln_file>

**Comment by livarcocc** [comment]
I think this happens because I have the sln and the project in different folders. I checked our tests, and they have these files collocated.

**Comment by jgoshi** [comment]
@livarcocc Can you try to repro? I am unable to repro with the latest checked in code.

**Comment by piotrpMSFT** [comment]
@jgoshi if it's not repro'ing, please add a test so we know this continues to work. You can probably modify your existing test project with:

```
  /project
    /project.sln
     peerProject.xproj
       /src
         /subdir
           /subdir.csproj
```

**Comment by livarcocc** [comment]
@jgoshi , have you tried the repro I suggested above? I just tried it and hit it again. I wonder if maybe this is a non-windows only issue. Let me try this on windows and report back here.

**Comment by livarcocc** [comment]
This is happening on non-windows only and I believe I know why.

This line is the culprit: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-migrate/MigrateCommand.cs#L410.

It is taking project.FilePath without changing the path separator to the appropriate one for the OS. So, the SLN has project.File with backslash on it. Then when we do a Path.Combine with it, we have a wrong character in the path.

**Comment by livarcocc** [comment]
@jgoshi I tried the project above again in OSX and I am still hitting this.

**Comment by livarcocc** [comment]
@jgoshi I found out what is going on. I had the project.json deleted, but the xproj still around.
