### ISSUE TITLE
Migration should stop raising transitive P2Ps once the project system supports them

### ISSUE THREAD

**Issue by srivatsn** [dotnet/cli#4959]
Once https://github.com/dotnet/roslyn-project-system/issues/199 is implemented, we should stop raising the closure of a project references to the top level.

**Comment by livarcocc** [comment]
Just let me know when we should stop doing it.

**Comment by srivatsn** [comment]
The change to the SDK to treat project refs as transitive has been merged in. SDK build 20161221-2 has the changes. You are unblocked on this now. When you have this change let me know and we can insert that CLI into VS to unblock @333fred from working on https://github.com/dotnet/roslyn-project-system/issues/734
