### ISSUE TITLE
Enable Build/symbol indexing

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#496]
This is being used to track the work we discussed today.

CC @livarcocc @schellap @piotrpMSFT @Petermarcu @russellhadley

**Comment by blackdwarf** [comment]
Tracking code signing separately, #500. 

Also moving to RC2.

**Comment by gkhanna79** [comment]
@blackdwarf Why are we moving this to RC2? Are we not planning to have a story to debug the Jan-Beta deliverables when they crash in the wild?

**Comment by piotrpMSFT** [comment]
Once there is a plan here I'm happy to move it back. Until we hear from @markwilkie on what needs to be done, though, we cannot execute on this. Worst-case, crashes can be investigated by cloning the repo and compiling from source.

When we understand the work let's try to pull this back in.

**Comment by gkhanna79** [comment]
@piotrpMSFT Please ensure you have guidelines published/shared about the tag to sync to for debugging the failures.

**Comment by piotrpMSFT** [comment]
makes sense. I'd really like to get this done properly, of course, so I'm looking forward to hearing from @markwilkie

**Comment by gkhanna79** [comment]
@markwilkie Have you had a chance to think about this?

**Comment by markwilkie** [comment]
Yes - this is on my radar.  Limited folks in the office until the new year, but we'll get the right thoughts together.

**Comment by gkhanna79** [comment]
Happy New Year @markwilkie. Do you think we can get thoughts together mid this week?

**Comment by markwilkie** [comment]
Currently looking further into either:
- providing a separate nugget package w/ the symbols, or
- using the existing MSFT symbol server

The nugget package seems great until you starting thinking about all the current tooling which assumes the symbol server.

Regardless, all published packages should have symbols available.

**Comment by markwilkie** [comment]
Any feedback/comments on potentially using MyGet's solution?  (MyGet doc reference) [http://docs.myget.org/docs/reference/symbols]

**Comment by gkhanna79** [comment]
Looks interesting. Given that publicly released nuget packages will be published to Nuget and dev/daily versions to myget, are we planning to use symbol hosting on both or just one? Also, has someone tried the experience?

**Comment by markwilkie** [comment]
The current high level POR is:
-	Publish symbols to VSTS for internal consumption.
-	Publish symbols to dotnet.myget.org for community consumption.  (http://docs.myget.org/docs/reference/symbols))
-	Publish symbols to the standard msft symbol server for our major official releases

@chcosta is the dev on point and we should know timing in the next few days.  The hope is that the symbols will be available fairly soon, and then we can work through any dev workflow hiccups/twists.

**Comment by piotrpMSFT** [comment]
Any update on this?

**Comment by dagood** [comment]
Not yet, I'm working on finishing up changes related to the CLI upgrade in CoreCLR. Chris has given me documentation on the current symbol publish work, but I haven't gone into enough depth yet to give an estimate on timing.

**Comment by markwilkie** [comment]
@piotrpMSFT, @dagood is working on CLI stuff....   :)

**Comment by cheers00** [comment]
Getting symbols from symbols server or as nuget package is one solution. But we also want to

- Build CoreCLR and CoreFx
- Copy dlls to .Net CLI 
- Build and Deploy
- use my own symbols for debugging.

**Comment by syalachigere** [comment]
Any updates on this?

**Comment by dagood** [comment]
An update and a little clarification of what I'm working on:

So far I have enabled managed symbol package builds for corefx/wcf that will start publishing to the dotnet-core MyGet feed next week. @markwilkie @brianrob and I have thought about a plan for native symbol publishing that I'll be proving out next.

The way I understand it, the current work for this issue is to make it clear how we (dotnet projects) should publish symbols, and how those symbols (native/managed/Windows/xplat) should be consumed. I will probably not do the implementation in CLI but I'll certainly be helping. (I don't have experience with the CLI repository yet.)

**In the short term** the guidance is to publish CLI symbols to Azure, similar to the CLI zips. I don't know what the status is for this.

**Comment by brthor** [comment]
Can you give more details on this guidance? 

What should be in this cli symbols package, pdbs only?
How are developers expected to consume these packages?

**Comment by markwilkie** [comment]
My recommend is to publish "skinny" packages - which are the new one, and then also "fat" packages as well (diff name) that have symbols.





On Fri, Apr 1, 2016 at 12:26 PM -0700, "Bryan Thornbury" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you give more details on this guidance?

What should be in this cli symbols package, pdbs only?
How are developers expected to consume these packages?

-

**Comment by brthor** [comment]
Not too clear on what "skinny" and "fat" packages are in this context. My understanding is those determine which rid specific assets are included in a portable app. 

Is the guidance simply to publish a zip with sdk binaries only and another with sdk binaries and pdbs?

**Comment by markwilkie** [comment]
There are a few options of course. I'm suggestion publishing the binaries without the symbols stripped, and again with them stripped.





On Fri, Apr 1, 2016 at 12:38 PM -0700, "Bryan Thornbury" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not too clear on what "skinny" and "fat" packages are in this context. My understanding is those determine which rid specific assets are included in a portable app.

Is the guidance simply to publish a zip with sdk binaries only and another with sdk binaries and pdbs?

-

**Comment by dagood** [comment]
The reason we don't suggest publishing the pdbs without binaries is that it's not all pdbs: native xplat symbols are (usually) contained within the binary itself and distributed that way. Making a new binary + symbol package seems like the most consistent way to handle this.

**Comment by bryanar** [comment]
Has anyone begun publishing symbols to VSTS yet?

**Comment by brthor** [comment]
Created an issue for the RC2 specific plan here: https://github.com/dotnet/cli/issues/2260

As we come to a more complete plan I think we should update this issue, and track the specific work in it's own issue.

**Comment by cheers00** [comment]
Will there be any support to build CoreCLR\CoreFX locally and use both binaries and symbols in .Net CLI?

**Comment by piotrpMSFT** [comment]
@krwq, can you follow up with @markwilkie to see if there is something we need to do for RTM?

**Comment by krwq** [comment]
Current status for symbols of corefx/coreclr: https://github.com/dotnet/core-eng/blob/master/Documentation/Symbols.md - there does not seem to be any need to do anything about symbols for cli at this point.
I'm trying to get some more info about local builds
