### ISSUE TITLE
dotnet migrate adding dir\**\* in Content Include 

### ISSUE THREAD

**Issue by sm-g** [dotnet/cli#4966]
After installing VS2017RC (1.0.0-preview3-004056)
```
"publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Client",
      "Configuration",
      "web.config"
    ]
  }
```
converted to 
```
<Content Include="wwwroot\**\*;Client\**\*;Views\**\*;Configuration\**\*;web.config"> 
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory> 
</Content>
```

VS cannot load project: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.FileMatcher.GetFiles(String projectDirectoryUnescaped, String filespecUnescaped, IEnumerable`1 excludeSpecsUnescaped, GetFileSystemEntries getFileSystemEntries, DirectoryExists directoryExists)

## Expected  behavior
Do not add `**\*`

**Comment by livarcocc** [comment]
@srivatsn Can you take a look at the NRE coming from VS?

**Comment by srivatsn** [comment]
This seems to be in MSBuild - @cdmihai @raines - does this look familiar?

**Comment by rainersigwald** [comment]
Looks like https://github.com/Microsoft/msbuild/pull/1349 which should be fixed in the next prerelease.

**Comment by livarcocc** [comment]
We have already taken a MSBuild version with the fix in the CLI. Closing this issue now. If this still reproes for you, please, re-activate.
