### ISSUE TITLE
Support Localization Resource Generation & Translation

### ISSUE THREAD

**Issue by hishamco** [dotnet/cli#4967]
> Last few days I started a new `dotnet` CLI tool to generate and translate localization resources called `dotnet resgen` this is the link to my repo https://github.com/hishamco/LocalizationResourceGenerator, it would be nice to support such utility tool during the development phase on all the localization web applications.
FYI the tool is under development, and may it needs a lot of improvements by the time

Moving this https://github.com/aspnet/DotNetTools/issues/203 to home repo

**Comment by enricosada** [comment]
@hishamco maybe you can also copy the issue description from the referenced issue, so is easier to read

**Comment by piotrpMSFT** [comment]
@nguerrera thoughts?

**Comment by piotrpMSFT** [comment]
I'm moving this to the SDK repo as that's where the in-box resgen tool lives.
