### ISSUE TITLE
Help text for dotnet-add-p2p and dotnet-add-proj

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#4968]
`dotnet add p2p` and `dotnet add proj` (PR in progress) produce non-intuitive help text. This is caused by the fact that one of the arguments is implied from the command higher on the stack (i.e. `<project>` will be passed from `dotnet add` and never actually passed explicitly to `dotnet add p2p`).

We need some good help description for that.

Example:
```
Usage: dotnet add proj [arguments] [options] [[--] <arg>...]]

Arguments:

 <SOLUTION>  The solution file to modify. If a solution file is not specified, it searches the current working directory for a file that has a file extension that ends in `sln` and uses that file.Options:

 -h|--help  Show help informationArgs:

 Project to add to solution
```

**Comment by jgoshi** [comment]
Here is the new text from @blackdwarf 

Usage: dotnet add <SOLUTION> proj [options] [args]

Arguments:
  <SOLUTION>  The solution file to modify. If a solution file is not specified, it searches the current working directory for a file that has a file extension that ends in `sln` and uses that file.

Options:
  -h|--help  Show help information

Args:
  Project to add to solution
