### ISSUE TITLE
Dotnet build doesn't display the details any more , expected ? 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#4969]
## Steps to reproduce
Run below command 
dotnet new 
dotnet restore 
dotnet build

## Expected  behavior
RC behavior was this 
![image](https://cloud.githubusercontent.com/assets/12449387/21023650/45aeecf2-bd36-11e6-8aa0-91dbe6c70c46.png)

## Actual behavior
RC.2 Behavior is 

![image](https://cloud.githubusercontent.com/assets/12449387/21023673/5ab81e98-bd36-11e6-82c5-f2f28c75e105.png)

I no more see the details and the build succeeded info , expected ? 
## Environment data
.NET Command Line Tools (1.0.0-preview4-004215)

Product Information:
 Version:            1.0.0-preview4-004215
 Commit SHA-1 hash:  7a0d3e255a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004215

**Comment by livarcocc** [comment]
Yes, this is expected. We set the verbosity to minimal across the board.

**Comment by piotrpMSFT** [comment]
@jinujoseph we respect MSBuild verbosity, just reduced the default. you can pass `/v:diag` if you need some light reading :)

**Comment by jinujoseph** [comment]
👍
