### ISSUE TITLE
Extra space

### ISSUE THREAD

**Issue by hultqvist** [dotnet/cli#4970]
There is an extra space in the URL next to the description in this github repo.

The URL looks like this https://docs.microsoft.com/dotnet/

but links to https://docs.microsoft.com/dotnet/%20

**Comment by piotrpMSFT** [comment]
I didn't see this issue at https://github.com/dotnet/cli/blob/rel/1.0.0/README.md. I searched for ` )` in the md for that file with no hits. Please let me know if you still see it, and at what URL.

**Comment by piotrpMSFT** [comment]
Thanks for the extra detail, @hultqvist. Should be fixed now.
