### ISSUE TITLE
dotnet new .net core app builds against desktop reference assemblies

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#4973]
Surely a dupe but I can't find it easily. I would not expect my new (default) app to build against the desktop reference assemblies (the ones in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0`)

```
C:\play\app2>dotnet new
Created new C# project in C:\play\app2.

C:\play\app2>dotnet build
...
       CoreCompile:
         C:\Program Files\dotnet\sdk\1.0.0-preview3-004056\RunCsc.cmd /noconfig /nowarn:1701,1702 /nostdlib+ /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" /debug+ /out:obj\Debug\app2.exe /target:exe /utf8output Program.cs ....

C:\play\app2>dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
Yeah, we are tracking it here https://github.com/dotnet/cli/issues/3736 and here https://github.com/dotnet/cli/issues/2199

**Comment by danmosemsft** [comment]
@livarcocc that doesn't seem the same issue. When I do `dotnet new` I think I am creating a .NET Core application. However when it compiles it references desktop types, such as `"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll"`. So it will compile even if the type is not in .NET Core.

Am I missing something?

**Comment by danmosemsft** [comment]
I tried preview 4 just now but it doesn't even compile a `dotnet new` app. There seem to be no references going to the compiler:

```
         C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\RunCsc.cmd /noconfig /nowarn:1701,1702,1705 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE;NETCOREAPP1_0 /debug+ /debug:portable /filealign:512 /nologo /optimize- /out:obj\Debug\netcoreapp1.0\app5.dll /target:exe /utf8output /deterministic+ Program.cs "C:\Users\danmose\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs" obj\Debug\netcoreapp1.0\app5.AssemblyInfo.cs
```

**Comment by danmosemsft** [comment]
@piotrpMSFT is there a newer build I can try?

**Comment by danmosemsft** [comment]
Verified fixed in latest bits.
