### ISSUE TITLE
Remove custom SDK NuPkg installation for F#

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4976]
@enricosada this is really an issue for you but I wasn't sure where to open it :)

I don't want to have the pattern of custom build steps for SDK nupkg's become a common one, though was Ok with it for preview4 given the timing. I'd like to get an F# SDK package that contains only that SDK which we can copy during layout creation wholesale. We can then remove custom F# logic from the CLI build. Can you create such a package and update the reference in CLI?

**Comment by enricosada** [comment]
ok! i'll add another package `FSharp.Sdk` with `Sdk` only.

**Comment by piotrpMSFT** [comment]
thanks!
