### ISSUE TITLE
Dotnet restore failed on Bamboo build server

### ISSUE THREAD

**Issue by AnotherDeveloper01** [dotnet/cli#4983]
Hello
I have a dotnet core application and want to build on bamboo. I installed the required on the bamboo build server. The first step is "dotnet restore" and it fails when I run the plan. But, when I login remotely and run the it as cmd, it restores the packages in the project. Bamboo application on the build server is running as user Local System.

Tried the following too
1. add nuget.config to the dotnet core project and give its path in the dotnet restore --configfile "xxxxx"
2. add the corporate http proxy packet url in the nuget.config

**Error:** Unable to load the service index for source https://api.nuget.org/v3/index.json.
09-Dec-2016 09:14:59	error:   An error occurred while sending the request.
09-Dec-2016 09:14:59	error:   A connection with the server could not be established
09-Dec-2016 09:14:59	trace: System.AggregateException: One or more errors occurred. (Unable to load the service index for source https://api.nuget.org/v3/index.json.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A connection with the server could not be established

Thanks

**Comment by krwq** [comment]
@AnotherDeveloper01 - is it possible that this is some intermittent connection issues on the build server?

**Comment by AnotherDeveloper01** [comment]
@krwq , No. We don't see any

**Comment by krwq** [comment]
@AnotherDeveloper01, I believe this will be a NuGet bug. Please go ahead and create an issue in https://github.com/nuget/home/issues

**Comment by AnotherDeveloper01** [comment]
@krwq , we now changed Bamboo application to run as a generic user from LocalSystem account and dotnet restore is working. One thing we observed is, dotnet restore is always looking in %appdata%/roaming/Nuget/Nuget.config, even though we specify a seperate nuget config file in the cmd. 
Btw, we have other apps (.Net 4.6.1) on the build server and **Nuget** restore works there.

Thanks

**Comment by piotrpMSFT** [comment]
Sounds good. Please move this to NuGet/Home so we can get the right team looking at it :)

/cc @rrelyea
