### ISSUE TITLE
dotnet restore ignoring changes in .csproj

### ISSUE THREAD

**Issue by thereapman** [dotnet/cli#4995]
## Steps to reproduce

I can't 100% recall the steps i've done but here is roughly  what i did:

1. Create a dotnet core project in VS2017RC (i've used the asp.net core with auth)
2. Edit the `csproj` to update to the 1.1 runtime in 2 locations:
`<TargetFramework>netcoreapp1.1</TargetFramework>` to
` <TargetFramework>netcoreapp1.1</TargetFramework>`
and
`    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>`
to
`    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.1.0</Version>
    </PackageReference>`

3. Saved and closed the file (VS2017 then did reload the file and did a restore)
4. I've remove the SqlServer Package and added the Npsgl package for postgreSql
5. The dependency tree in VS2017 looks good

### Steps tried to fix the issue

1. removing `bin` and `obj`
2. run `dotnet restore` 
3. run `dotnet restore --no-cache`

## Expected  behavior

1, After removing the SqlServer package and adding the Npsql package, SqlServer code should throw errors for missing assembly and npsql code should work fine.
2. during `dotnet restore` the npsql package should be restored

## Actual behavior

Both VS2017 and `dotnet restore` keep restoring the old state with SqlServer and without Npsql.
The .csproj looks ok to me (see attached) but when i run `dotnet restore` it somehow ignores the changes. When i take a look at the lock file at `obj/project.assets.json` the SqlServer reference is still there and npsql is missing. To me it seems there is somewhere a cached version of the dependency tree and `dotnet restore` doesn't read the actual csproj. Tried deleting the `obj` and `bin` folder, no difference

VS2017 doesn't pick up the new namespaces from Npsql. 
Code that references the SqlServer dependecy still works and compiles during VS build and `dotnet build`

## Attached Files

[DuckHub.csproj](https://github.com/dotnet/cli/files/644063/DuckHub.csproj.txt) - source csproject file
[project.assets.json](https://github.com/dotnet/cli/files/644062/project.assets.txt) - resulting lock file

## Environment data
`dotnet --info` output:
`.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14965
 OS Platform: Windows
 RID:         win10-x64`

**Comment by livarcocc** [comment]
@emgarten Can you take a look?

**Comment by emgarten** [comment]
> the SqlServer reference is still there 

The SqlServer reference is coming from EntityFramework.

```json
      "Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore/1.0.0-msbuild1-final": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Hosting": "1.0.0",
          "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
          "Microsoft.EntityFrameworkCore": "1.0.1",
          "Microsoft.EntityFrameworkCore.SqlServer": "1.0.1",
          "Microsoft.VisualStudio.Web.CodeGeneration.Core": "1.0.0-msbuild1-final",
          "NETStandard.Library": "1.6.0"
        }
     }
```

> and npsql is missing

Npgsql is showing up in the assets file under ``NpgSql/3.1.9`` so the package is being restored and I see references to ``lib/netstandard1.3/Npgsql.dll``

I don't see any issues with the output you've shared here, does restarting Visual Studio help? Are there other npsql packages that should be here?

**Comment by piotrpMSFT** [comment]
@thereapman ?

**Comment by blackdwarf** [comment]
Due to inactivity on the issue, I will close it down. Please reopen if the root problem still repros with the latest tooling.
