### ISSUE TITLE
Authenticode signing and strong name signing

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#500]

**Comment by gkhanna79** [comment]
CC @schellap @russellhadley

**Comment by livarcocc** [comment]
- [ ] Authenticode sign
- [ ] Strong name signing

**Comment by gkhanna79** [comment]
@livarcocc What is the current status on this? We need to get this enabled in CoreRT repo as well and cannot do until you have figured out the overall infrastructure design.

**Comment by piotrpMSFT** [comment]
@livarcocc what's the status here?

**Comment by schellap** [comment]
@livarcocc and @schellap plan to sign ILC/Dependency bits today at 3:30. We need to get the RyuJIT and OW packages signed as well. @kyulee1, I will take care of the JIT this time as @livarcocc has kindly agreed to do this for us.

**Comment by piotrpMSFT** [comment]
Did the dependency signing happen?

**Comment by livarcocc** [comment]
We did the signing on Friday, waiting on the approval of the two approvers we need to to be able to download the CLR bits.

We need the Beta branch for me to do the same for the CLI.

**Comment by piotrpMSFT** [comment]
now tracked as part of Beta release in #668
