### ISSUE TITLE
An item with the same key has already been added. Key: Microsoft.NETCore.App 

### ISSUE THREAD

**Issue by Shadowman4205** [dotnet/cli#5001]
What is this error? After updating my project packages to version 1.1  i cannot restore packages or do any debug on visual studio and i get this error. Any suggestion?
Also i can run from cmd dotnet build/restore/run with success.

**Comment by piotrpMSFT** [comment]
Can you share versions of components in play?

**Comment by Shadowman4205** [comment]
Do you mean in project.json if yes this is 
`{
  "dependencies": {
    "AircraftDailyReport.Dal": "1.0.0-*",
    "Microsoft.AspNetCore.Session": "1.1.0",
    "System.Linq.Dynamic.Core": "1.0.6.8",
    "MimeKit": "1.10.0",
    "BundlerMinifier.Core": "2.2.306",
    "MailKit": "1.10.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "AutoMapper": "5.2.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Identity": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "microsoft.aspnetcore.spaservices": "1.0.0-beta-000021",
    "Microsoft.AspNetCore.Authorization": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "EPPlus.Core": "1.0.2",
    "Microsoft.AspNetCore.Hosting": "1.1.0",
    "Microsoft.AspNetCore.Hosting.Abstractions": "1.1.0"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  },
  "buildOptions": {
    "warningsAsErrors": true,
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "runtimes": {
    "win10-x64": {},
    "debian.8-x64": {}
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "publishOptions": {
    "include": [
      "**/*.cshtml",
      "appsettings.json",
      "ClientApp/dist",
      //"node_modules",
      "Views",
      "web.config",
      "wwwroot"
    ]
  },
  "scripts": {
    "prepublish": [
      //"dotnet bundle",
      "yarn",
      "node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod",
      "node node_modules/webpack/bin/webpack.js --env.prod"
    ]
    //"postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },
  "tooling": {
    "defaultNamespace": "AircraftDailyReport.Mvc"
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  }
}`

**Comment by CRodriguez25** [comment]
I'm having the same issue. It seems as though the only way to get it to actually compile is to go through all the projects and unload/reload them into the solution.

**Comment by Shadowman4205** [comment]
Nothing happend, still the same.

**Comment by piotrpMSFT** [comment]
I see, this is a project.json issue. We don't have any more planned project.json tooling releases so I'm closing the issue. There were a bunch of causes for symptoms like these in project.json system. I recommend grabbing the latest rc3 bits from the root of this repo and `dotnet migrate`ing the project to csproj. If it still repro's there we'll be able to investigate and fix!
