### ISSUE TITLE
"dotnet-publish-iis"

### ISSUE THREAD

**Issue by ravtakhar** [dotnet/cli#5003]
## Steps to reproduce
Try "Publish" within Visual Studio 2015

## Expected  behavior
I have been doing this for over a year now? This suddenly broke... The only thing I can think of being changed is a windows update.

## Actual behavior
Error		No executable found matching command "dotnet-publish-iis"

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

## Project.json File:

{
  "dependencies": {
    "chargify": "1.1.6085.28452",
    "DevDefined.OAuth": "0.2.0",
    "DeveloperForce.Force": "1.3.2",
    "GitLab.NET": "0.0.4",
    "IppDotNetSdkForQuickBooksApiV3": "2.8.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNet.Http.Extensions": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.Net.Http": "2.2.29",
    "System.Data.SqlClient": "4.3.0"
  },
  "tools": {
  },
  "frameworks": {
    "net462": {
      "frameworkAssemblies": {
        "System.Runtime.Serialization": "4.0.0.0",
        "System.ServiceModel": "4.0.0.0",
        "System.Xml": "4.0.0.0"
      }
    }
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },
  "scripts": {
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  }
}

**Comment by ravtakhar** [comment]
Sorry I've also tried adding the following:
"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
To tools but I'm unable to restore?

**Comment by ravtakhar** [comment]
Turns out I had to use the following :
"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
Under tools? Is this issue going to happen once I decide to upgrade because I'm not using .net core?

**Comment by danroth27** [comment]
This looks like a 1.1 project so I think you should be using "1.1.0-preview4-final". What restore error were you seeing?

**Comment by ravtakhar** [comment]
@danroth27  Yeah that's what had me confused. I will try to change the project.json and produce a build with the 1.1.0-preview4-final again the next time I'm on our build machine.

**Comment by piotrpMSFT** [comment]
@ravtakhar any luck?

**Comment by ravtakhar** [comment]
I got it to the point where it now restores from package.json (Just magically worked) but when I try to build I get the following message

![image](https://cloud.githubusercontent.com/assets/17505581/21317953/205cb8d8-c5bc-11e6-8c44-8710a22587af.png)

**Comment by livarcocc** [comment]
Your application is targeting the 1.1.0 runtime. Check what is the version under Microsoft.NetCore.App, however, you don't have that runtime installed.

You can get it here: https://www.microsoft.com/net/download/core#/current/runtime. Or, you can change your application to target one of the runtimes that you do have installed and that is listed in the message above.

**Comment by ravtakhar** [comment]
@livarcocc installing that ended up working!

Why was I missing that?

**Comment by livarcocc** [comment]
I don't know how you setup your environment. But 1.1 is a Current version, not LTS, so, in all likelihood you installed the LTS version of the SDK, which comes with the LTS version of the runtime.
