### ISSUE TITLE
.NET Core Sdk preview4 installer/zip are really hard to find

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#5009]
Dont know if this is the best place to ask, but is related to dotnet cli discovery.

I think if it's confusing for me (i use and show that website a lot, and know exactly what i need), i think is really hard for new users.

Where i do download .net core preview4 sdk installer.zip (without VS 2017) ?
In the website is written to go in this repo for daily drop, and is ok but that's preview5, not latest stable preview4 released.

I understand switch, but is not possible to have a webpage with released package versions, and links?

## Repro

1. go http://dot.net
2. go .NET Core
3. Go command line
4. That's preview2.1

## Excepted

A link to preview4 sdk isntaller/zip for all OS (like LTS/Current switch).

## Current

A link to preview2, preview2.1 and VS 2017 tools.

**Comment by am11** [comment]
+1 would be nice to have a simple dist channel as well like https://nodejs.org/dist/ (easy to predict and script the URLs, enables others to write their own Version Managers like dnvm, nvm etc.)

**Comment by blackdwarf** [comment]
@enricosada working on it. It will be placed next to this doc: https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md and linked from the README.md in this repo.

**Comment by enricosada** [comment]
Meanwhile is possible to run obtain dotnet-install script passing -channel `rel-1.0.0-preview4` and see the url

**Comment by piotrpMSFT** [comment]
Or can hand-craft the URL as described in #5045

**Comment by blackdwarf** [comment]
@enricosada  here are the release notes: https://github.com/dotnet/core/blob/master/release-notes/preview4-download.md. The README.md is in PR.

**Comment by blackdwarf** [comment]
OK, this is now fixed I believe so closing.

**Comment by enricosada** [comment]
thx a lot @blackdwarf , that was perfect!
