### ISSUE TITLE
Design cross compile/publish for CLI

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#501]

**Comment by blackdwarf** [comment]
I believe this should be moved to CoreRT repo. @gkhanna79 thoughts?

**Comment by gkhanna79** [comment]
I used this to track the work for cross compiling/publishing for CLI. Is there a seperate work-item for that?

**Comment by blackdwarf** [comment]
@gkhanna79 not that I know of. OK, if this is used to track the CLI work, that is fine. Can you label it and assign accordingly?

**Comment by gkhanna79** [comment]
@blackdwarf I have renamed the issue. Please assign as appropriate.

**Comment by gkhanna79** [comment]
CC @piotrpMSFT

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
