### ISSUE TITLE
Update cli build configurations for Fedora 24 and 25

### ISSUE THREAD

**Issue by gpiercey** [dotnet/cli#5010]
With Fedora 23 EOL on Dec 20, 2016 the cli build configurations should be updated to support source builds on Fedora 24 and 25. 

rel/1.0.0-previewX:
- there is no branch yet for 1.1 so I looked at the preview branches
- needs build configurations for Fedora 24 and 25
- preview2.1 seems to have support for Fedora 24 but preview3 and preview4 do not. Have those branches been abandoned?
- build status in README.md should include Fedora 24 and 25 instead of 23

rel/1.0.0:
- needs build configurations for Fedora 24 and 25
- build status in README.md should include Fedora 24 and 25 instead of 23

**Comment by livarcocc** [comment]
We now have a linux x64 portable distro that will run on many versions of Linux, exactly so that we don't need to add specific support for each individual distro. Please, try that out.
