### ISSUE TITLE
dotnet run -h incorrectly describes what happens with extra args

### ISSUE THREAD

**Issue by lzybkr** [dotnet/cli#5017]
Help should say args are passed to the application

Help says:

Args:
  Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by blackdwarf** [comment]
@lzybkr true, thanks for reporting this.

**Comment by blackdwarf** [comment]
This should be done when the command line parser localization comes in ( #5067 ).

**Comment by blackdwarf** [comment]
Fixed via #5080
