### ISSUE TITLE
dotnet test -h is misleading on usage of --test-case-filter switch

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/cli#5021]
## Steps to reproduce

`dotnet test -h`

## Expected  behavior

The help text should give a clearer example of usage. The examples given are misleading.

## Actual behavior

```
> dotnet test -h
--test-case-filter <Expression>       Run tests that match the given expression.
                                      Examples:
                                      --test-case-filter:"Priority = 1"
                                      --test-case-filter: "(FullyQualifiedName~Nightly | Name = MyTestMethod)"
```

The command actually requires, for example:

`dotnet test --test-case-filter "FullyQualifiedName=Microsoft.DotNet.Migration.T
ests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences"`

This does not work:

`dotnet test --test-case-filter "Name=ItMigratesRootProjectAndReferences"`

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.0-preview5-004253
 Commit SHA-1 hash:  0caae96daf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\dev\github\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004253

**Comment by blackdwarf** [comment]
@jonsequitur good one. I think we should also rename `--test-case-filter` to plain old `--filter` as part of this "fix".
