### ISSUE TITLE
net451 projects don't find satellite resources if a keyFile is define

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#5026]
## Steps to reproduce
1. Run the project in [this](https://github.com/aspnet/Localization/tree/4ea26fef201a71ab5a7ae12f36c07c7bd57d481d) branch against net451.
2. See that "Hello Hello Hello" is returned instead of french strings.
3. Remove the "keyFile" line from the project.json.
4. See that french strings are returned.

## Expected  behavior
Resource files should be acessable regardless of if the project is signed.

## Actual behavior
Resources files aren't accessible due to an assembly binding error "WRN: Comparing the assembly name resulted in the mismatch: PUBLIC KEY TOKEN"

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003770)

Product Information:
 Version:            1.0.0-preview3-003770
 Commit SHA-1 hash:  09e8877bd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@ryanbrandenburg can you migrate your repo? We're not taking fixes for project.json anymore. Unless there is a blocker, can you close the issue?

**Comment by ryanbrandenburg** [comment]
This does seem to work once converted to csproj/msbuild so sure, I'll close this out.
