### ISSUE TITLE
Add sln should add solution items to the sln file

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#5028]
When we do a dotnet add <sln> <src/project/project.csproj> we should make sure that we have src as a solution item in the sln file.

The sln should look similiar to this: 

```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 14
VisualStudioVersion = 14.0.25420.1
MinimumVisualStudioVersion = 10.0.40219.1
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{CE69E261-F9E9-41E9-A2B2-C7EB547D4231}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{05490A5A-1315-4695-A20E-024EEAD4E97D}"
	ProjectSection(SolutionItems) = preProject
		global.json = global.json
	EndProjectSection
EndProject
Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "AspNetCoreWebApp_NoAuth_1", "src\AspNetCoreWebApp_NoAuth_1\AspNetCoreWebApp_NoAuth_1.xproj", "{485189E1-D720-4123-8CD3-5985E6DD0AB3}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{485189E1-D720-4123-8CD3-5985E6DD0AB3}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{485189E1-D720-4123-8CD3-5985E6DD0AB3}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{485189E1-D720-4123-8CD3-5985E6DD0AB3}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{485189E1-D720-4123-8CD3-5985E6DD0AB3}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(NestedProjects) = preSolution
		{485189E1-D720-4123-8CD3-5985E6DD0AB3} = {CE69E261-F9E9-41E9-A2B2-C7EB547D4231}
	EndGlobalSection
EndGlobal
```

Note the src item in it. Without this, the project will not show properly on VS. Also, if we are already handling this, just close this issue.

**Comment by jgoshi** [comment]
@livarcocc When migrating we always start with an existing sln file. Are you suggesting we add these in if it wasn't present in the existing sln file? Or is this for the template when we implement dotnet new -t sln?

**Comment by piotrpMSFT** [comment]
by default, our `dotnet add <slnfile> project` command should replicate the relateive path hierarchy from disk in the sln file. This will mean inspecting the existing solution file to see if an appropriate hierarchy already exists and creating any missing 'folders'.

**Comment by jgoshi** [comment]
@piotrpMSFT @livarcocc What I noticed for VS 2017 is it automatically picks up directory structure without needing the solution item and src entries in the sln file. Maybe we don't need to do anything?

**Comment by livarcocc** [comment]
@srivatsn Can you confirm @jgoshi findinds? If that is the case, that will be great.

**Comment by piotrpMSFT** [comment]
@srivatsn?

**Comment by srivatsn** [comment]
I don't fully understand VS behavior. @davkean might know.

**Comment by jgoshi** [comment]
For VS 2017 the only time Solution Items and folder hierarchy are added to the sln file is if the user adds a folder through the VS UI. For .NET core projects VS automatically understands the directory structure (because the files are included through a *cs filter). If I create a new .NET framework app and want a directory structure I need to add the folders through VS. So maybe we don't need to do anything for this one?

**Comment by davkean** [comment]
*.cs is completely different from the Solution case. *.cs is controlled by the project and not stored in the solution.

**Comment by jgoshi** [comment]
Yeah but I meant that the only way to create solution items and folder hierarchy in VS is to actually go in an create new folders. If I just add a project this doesn't happen automatically for me. So we shouldn't be doing it either for adding a project through CLI, right?

**Comment by davkean** [comment]
Agreed, but one thing the Solution allows is to add projects to a solution folder - what's the equivalent in CLI world?

**Comment by davkean** [comment]
Maybe it's nothing - and that's fine.

**Comment by jgoshi** [comment]
CLI doesn't have a way to specify adding projects to a solution folder. Add project is always just adding whatever project path you pass in (converting to a relative path first).

**Comment by jgoshi** [comment]
Speaking with @piotrpMSFT I realize that I misunderstood this work item. This is about automating the creation of solution folders. Through the VS UI the user can create solution folders and add projects to those folders. Through the CLI we are going to auto create solution folders using the existing directory hierarchy.
