### ISSUE TITLE
unhandled exception (caused by missing dlls) during the runtime show completely random error message

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#503]
#463

**Comment by livarcocc** [comment]
@krwq Can you give us a more detailed repro for this?

**Comment by krwq** [comment]
I'm not sure how to repro when original issue isn't there. Probably something like this:
- create new project, make sure it has any runtime dependency
- remove the runtime dependency and make sure the exe will fail with missing assembly error
- run same exe using dotnet run and observe error

**Comment by davidfowl** [comment]
I don't understand this issue...

**Comment by piotrpMSFT** [comment]
Closing. If we get  a repro, please re-open.
