### ISSUE TITLE
Failed compilation with false error CS0534 ('X' does not implement inherited abstract member 'Y')

### ISSUE THREAD

**Issue by dprothero** [dotnet/cli#5031]
## Steps to reproduce
1. Clone https://github.com/twilio/twilio-csharp
2. Checkout branch `next-gen-netstandard`
3. `dotnet restore` <-- works fine
4. `dotnet build JWT` <-- works fine
5. `dotnet build Twilio` <-- fails

## Expected  behavior
Should successfully compile the project. It compiles fine within Visual Studio 2015 U3.

## Actual behavior
```
Project JWT (.NETStandard,Version=v1.1) was previously compiled. Skipping compilation.
Project Twilio (.NETStandard,Version=v1.1) will be compiled because expected outputs are missing
Compiling Twilio for .NETStandard,Version=v1.1
C:\Program Files\dotnet\dotnet.exe compile-csc @C:\Users\david\Projects\twilio-csharp\Twilio\obj\Debug\netstandard1.1\dotnet-compile.rsp returned Exit Code 1
C:\Users\david\Projects\twilio-csharp\Twilio\Http\SystemNetClient.cs(7,15): error CS0534: 'SystemNetClient' does not implement inherited abstract member 'HttpClient.MakeRequestAysnc(Request)'

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:03.9889266
```

The error is incorrect. The [abstract member *is* implemented](https://github.com/twilio/twilio-csharp/blob/24f7b78e3103b09ade3224626192916e88df3254/Twilio/Http/SystemNetHttpClient.cs#L36) and the code compiles fine in Visual Studio 2015 U3.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by krwq** [comment]
@dprothero could https://github.com/twilio/twilio-csharp/blob/24f7b78e3103b09ade3224626192916e88df3254/Twilio/Http/SystemNetHttpClient.cs#L1 be related? I'm seeing that this project is not only net40.

If you still think this is a compiler bug please file an issue on https://github.com/dotnet/roslyn

**Comment by dprothero** [comment]
@krwq It's not related, thanks. As you can see, I'm defining that symbol here:

https://github.com/twilio/twilio-csharp/blob/24f7b78e3103b09ade3224626192916e88df3254/Twilio/project.json#L15

As well as the fact that the `MakeRequestAsync` isn't even defined as an abstract member of `HttpClient` unless that symbol is defined:

https://github.com/twilio/twilio-csharp/blob/24f7b78e3103b09ade3224626192916e88df3254/Twilio/Http/HttpClient.cs#L18-L26

**Comment by dprothero** [comment]
Doesn't Visual Studio use the same compiler? Would it be a compiler bug vs. a tooling bug?

**Comment by krwq** [comment]
@dprothero - we can verify that - could you run diagnostics build and see if you can find call to csc.exe there? We can check if the constant is being passed to the compiler. If it is then it will be a compiler bug if not then tooling. Also, did you try with newest CLI version? We are currently at preview5 and you seem to be using preview2.

**Comment by dprothero** [comment]
I will try that. Strange that I'm already behind, as I downloaded it ust yesterday from here:
https://go.microsoft.com/fwlink/?LinkID=835014

**Comment by krwq** [comment]
@dprothero try using the link in this repo under ".NET Core SDK Installer" - I think some of our pages might be out of date. I believe @blackdwarf is working on fixing that right now.

**Comment by dprothero** [comment]
With preview 5, I am getting the following error when trying to run `dotnet restore`:

```
C:\Users\david\Projects\twilio-csharp\Twilio\Twilio.csproj(328,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview5-004232\Microsoft\Portable\v5.0\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by krwq** [comment]
@dprothero, Have you migrated your project? (dotnet migrate) We are not using project.json anymore. Please use `dotnet new` to see the template of how the project should be using Sdk and then add your compile options to that (that should be standard csproj way).

**Comment by dprothero** [comment]
OK, migrated the project and got back to the same compiler error. Running with `-v diag` I see the following early in the output (~line 200):

```
DefineConstants = DEBUG;NET40;NETSTANDARD1_1
```

And then this much later (~line 55,000):

```
                   Task "Csc" (TaskId:52)
                     Task Parameter:DebugType=full (TaskId:52)
                     Task Parameter:DefineConstants=DEBUG;NET40;NETSTANDARD1_1 (TaskId:52)
```

And on the RunCsc.cmd call:
```
C:\Program Files\dotnet\sdk\1.0.0-preview5-004232\RunCsc.cmd /noconfig /nowarn:1701,1702,1705 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;NET40;NETSTANDARD1_1 [truncated rest]
```

So we can see the symbol is defined.

Will file a compiler bug.

**Comment by dprothero** [comment]
@krwq Thanks for all your help troubleshooting. Finally found the problem, and it was me and my eyes... the error says `SystemNetClient` which was a class that already existed but was only intended for our .NET 3.5 library. I surrounded it with the appropriate precompiler checks and all is peachy.

**Comment by piotrpMSFT** [comment]
Thanks for tracking this down, @dprothero && @krwq!
