### ISSUE TITLE
Console.WriteLine calls during dotnet test are not emitted to the console on Windows

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/cli#5033]
## Steps to reproduce

* Add a `Console.WriteLine` call in a test, .e.g `GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences`
* On Windows, `dotnet test --test-case-filter "FullyQualifiedName=Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndR
eferences"`

## Expected  behavior

The string passed to Console.WriteLine appears in console output.

## Actual behavior

```
C:\dev\github\cli\test\dotnet-migrate.Tests [rel/1.0.0 ↓ +0 ~2 -0 !]> dotnet test --test-case-filter "FullyQualifiedName=Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndR
eferences"
Build started, please wait...
Build completed.

Test run for C:\dev\github\cli\test\dotnet-migrate.Tests\bin\Debug\netcoreapp1.0\dotnet-migrate.Tests.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences(projectName: "ProjectB", expectedProjects: "ProjectB,ProjectC,ProjectD,ProjectE")
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences(projectName: "ProjectA", expectedProjects: "ProjectA,ProjectB,ProjectC,ProjectD,ProjectE")
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences(projectName: "ProjectC", expectedProjects: "ProjectC,ProjectD,ProjectE")
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences(projectName: "ProjectE", expectedProjects: "ProjectE")
Passed   Microsoft.DotNet.Migration.Tests.GivenThatIWantToMigrateTestApps.ItMigratesRootProjectAndReferences(projectName: "ProjectD", expectedProjects: "ProjectD")

Total tests: 5. Passed: 5. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 32.2825 Seconds
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview5-004253)

Product Information:
 Version:            1.0.0-preview5-004253
 Commit SHA-1 hash:  0caae96daf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\dev\github\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004253

**Comment by krwq** [comment]
@jonsequitur You should probably be using Xunit's ITestOutputHelper. making Console.WriteLine forward to that might be slightly harder

**Comment by jonsequitur** [comment]
The issue that I was seeing was that this works on OS X but not on Windows.

**Comment by livarcocc** [comment]
I am seeing that too on windows. None of the Console.WriteLine from my tests gets printed out. We should not ask users to use special APIs to print to the console.

@codito @Faizan2304 Can you guys take a look?

I think we should move this bug to the vstest repo.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#799
