### ISSUE TITLE
dotnet test not working when restoring with --packages

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5035]
## Steps to reproduce
- Create a test project
- `dotnet restore --packages pkgs`
- `dotnet test`

## Expected  behavior
Tests being run

## Actual behavior
```
Build started, please wait...
Build completed.

Test run for D:\cli\test\dotnet-test.Tests\bin\Debug\netcoreapp1.0\ItBuildsAndTestsAppWhenRestoringToSpecificDirectory\VSTestDotNetCore\bin\Debug\netcoreapp1.0\VSTestDotNetCore.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Error: Failed to initialize client proxy: could not connect to test process.
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview5-004247)

Product Information:
 Version:            1.0.0-preview5-004247
 Commit SHA-1 hash:  ea90ff4acb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004247
```

**Comment by piotrpMSFT** [comment]
@dotnet/vstest can you guys take a look?

**Comment by codito** [comment]
@krwq vstest uses the `additionalProbingPaths` defined in `bin\Debug\netcoreapp1.0\testapp.runtimeconfig.dev.json` to find testhost. In a local setup, confirmed that this path is same as packages directory in `obj\project.assets.json`. Are these values different in your repro? It appears vstest is able to locate the test host, but launch is failing for some reason.

Can you share diagnostic logs from `dotnet test -d:log.txt`? It should generate a log.txt file in csproj directory.

**Comment by frankbuckley** [comment]
@krwq @codito  @piotrpMSFT 

I am seeing the same error from `dotnet test` with `MSTest.TestAdapter` **but only on our build servers and only for test projects upgraded to `.NETCoreApp,Version=v1.1`**. It works on my local machine.

The output on the build server is:

    PS C:\temp\TestProj> dotnet test -d:log.txt
    Build started, please wait...
    Build completed.
    
    Test run for C:\temp\TestProj\bin\Debug\netcoreapp1.1\TestProj.dll(.NETCoreApp,Version=v1.1)
    Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
    Copyright (c) Microsoft Corporation.  All rights reserved.
    
    Starting test execution, please wait...
    Error: Failed to initialize client proxy: could not connect to test process.

The `log` file is created, but the `log.host` file is never created.

I have attached an [example project, together with the resulting `log.txt`](https://github.com/dotnet/cli/files/668636/TestProj.zip)

On the build server: 

    PS C:\temp\TestProj> dotnet --info
    .NET Command Line Tools (1.0.0-preview4-004233)
    
    Product Information:
     Version:            1.0.0-preview4-004233
     Commit SHA-1 hash:  8cec61c6f7
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

Changing to `<TargetFramework>netcoreapp1.0</TargetFramework>` and `<PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />` on the build server results in successful test runs.

On my local machine:

    PS C:\dsedev\temp\TestProj\TestProj> dotnet --info
    .NET Command Line Tools (1.0.0-preview4-004233)
    
    Product Information:
     Version:            1.0.0-preview4-004233
     Commit SHA-1 hash:  8cec61c6f7
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

Server and local machine have VS2017RC with latest updates.

**Comment by codito** [comment]
@frankbuckley this error message implies `dotnet test` is unable to launch testhost for running tests. Can you confirm if .netcore 1.1 shared runtime installed on the build machine?

What does following command output show (on build machine)?
```
> C:\Program Files\dotnet\dotnet.exe exec --runtimeconfig "C:\temp\TestProj\bin\Debug\netcoreapp1.1\TestProj.runtimeconfig.json" --depsfile "C:\temp\TestProj\bin\Debug\netcoreapp1.1\TestProj.deps.json" "C:\Users\dseadmin\.nuget\packages\microsoft.testplatform.testhost/15.0.0-preview-20161216-01\lib/netstandard1.5/testhost.dll" --port 50114 --parentprocessid 1016 --diag log.host.161222112017.txt'
```

**Comment by frankbuckley** [comment]
Ahh - yes - that is the issue. VS2017 does not install 1.1. Installing it fixes this.

Could the error message be improved?

**Comment by piotrpMSFT** [comment]
@krwq do you have a repro to share with @codito ? or is this a non-issue?

**Comment by krwq** [comment]
@piotrpMSFT @codito https://github.com/dotnet/cli/blob/rel/1.0.0/test/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs#L185

**Comment by codito** [comment]
The test is failing locally with build failure (path of some binaries copied are too long). I tried to run through the scenario manually.

1. Shorten the path manually. Use `G:\dd\gh\dotnet\dotnet-cli\test\dotnet-test.Tests\bin\Debug\netcoreapp1.0\1\VSTestDotNetCore` as working directory`.
2. `dotnet restore --packages pkgs`
3. `dotnet test`

I can run the test run successfully.

**Comment by Faizan2304** [comment]
@piotrpMSFT @livarcocc   Please close this bug. Issue has been resolved.
