### ISSUE TITLE
Add RID option to dotnet-restore

### ISSUE THREAD

**Issue by Thealexbarney** [dotnet/cli#5038]
The build and publish commands have options to specify a target runtime. `-r win10-x64`

To do this for the restore command, you have to manually send the property to msbuild. `/p:RuntimeIdentifier=win10-x64`

It seems like it might make sense to add the same option to the restore command. This looked easy enough, so I went ahead and did it here: https://github.com/Thealexbarney/cli/commit/07db7ccffbc484c1ff97c849d5b142cff7757b89

**Comment by livarcocc** [comment]
dotnet restore will restore all the rids under RuntimeIdentifiers or RuntimeIdentifier in your csproj.

**Comment by Thealexbarney** [comment]
It will, although that requires anticipating all the runtimes you'll publish for, or somebody will have to edit the csproj if they want to publish for another runtime. Being able to specify a new RID via the command line could make that easier.

**Comment by livarcocc** [comment]
cc @blackdwarf @emgarten @rrelyea for their opinions.

**Comment by emgarten** [comment]
I'm all for restore matching the rest of the dotnet commands. Publish takes a RID and then passes it to restore. It is possible a user would want to restore multiple projects at the same time (more efficient) with a single RID and then publish them without restoring again.

**Comment by livarcocc** [comment]
also copying @nguerrera because of potential changes to publish.

**Comment by nguerrera** [comment]
:+1:

**Comment by tmds** [comment]
I think this is an interesting request, it makes me wonder what parts of restore are rid dependent. The nuget downloads aren't I guess? What parts are?

**Comment by Thealexbarney** [comment]
@tmds For restore, it's used to get the runtime packages needed for publishing a standalone application with the .NET Core runtime included. [This](https://www.nuget.org/packages/runtime.rhel.7-x64.Microsoft.NETCore.Runtime.CoreCLR/) is just one example of one of the RID-dependant packages. It might be used for more than that during a restore, but I'm not sure.

**Comment by tmds** [comment]
Right. How does restore find these rid specific packages? Is this a general mechanism or is it something specific to the runtime?

**Comment by emgarten** [comment]
@tmds packages may contain a runtime.json file that contains references to runtime specific implementations. NuGet will only download these if you are restoring for a compatible runtime.

For a portable app the runtime specific system assemblies are in the shared sdk, and all other packages need to contain runtime specific assets in the same package since no runtime is used.

For standalone apps as @Thealexbarney mentioned, it is possible to publish an app for a different OS. In that case the shared sdk would not have the right assemblies, so you need to restore for that runtime and download the needed packages.

**Comment by tmds** [comment]
> @tmds packages may contain a runtime.json file that contains references to runtime specific implementations. NuGet will only download these if you are restoring for a compatible runtime.

Interesting! Is this documented somewhere?

**Comment by Thealexbarney** [comment]
Should I go ahead and submit a pull request?

**Comment by piotrpMSFT** [comment]
@emgarten thoughts on @Thealexbarney's offer? Someone from NuGet will want to be available for design/review of the changes.

**Comment by emgarten** [comment]
> Should I go ahead and submit a pull request?

That would be great :smile:

I'll review it

**Comment by blackdwarf** [comment]
@Thealexbarney since #5079 is merged, I will close this issue. Please reopen if I've done it in error. Thanks!
