### ISSUE TITLE
Inconsistent line endings when we run dotnet migrate and open csproj file in notepad

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5040]
## Steps to reproduce
Using VS 2017 RC.2 (CLI 1.0.0-preview4-004233)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1
dotnet migrate
Open AspNetCoreWebApp_OnCore_Empty_1.csproj in notepad

## Expected  behavior
Proper line endings

## Actual behavior
File does not seem to have the right line-endings

![image](https://cloud.githubusercontent.com/assets/8246794/21242319/97ccde26-c2c8-11e6-804d-6587fa10a911.png)

**Comment by livarcocc** [comment]
This actually seems to be a problem with MSBuild: https://github.com/Microsoft/msbuild/issues/1568.

**Comment by blackdwarf** [comment]
@livarcocc does it seem like we can make this for 1.0.0 if we depend on MSBuild APIs?

**Comment by blackdwarf** [comment]
Based on the discussion on the MSBuild repo, it seems that this will have to get fixed post 1.0.0.

**Comment by rainersigwald** [comment]
Canonical MSBuild issue for this is https://github.com/Microsoft/msbuild/issues/1401.

**Comment by livarcocc** [comment]
If msbuild fixes this post 1.0, we should move this one too to post 1.0. There is nothing for the CLI to do here.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#37
