### ISSUE TITLE
When migrating projects with a single tfm, dotnet migrate should not need to add DefineConstants property 

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5041]
## Steps to reproduce
Using VS 2017 RC.2 (CLI 1.0.0-preview4-004233)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1
dotnet migrate

## Actual behavior
This PropertyGroup gets added to the csproj

```
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
```

## Expected  behavior
Above PropertyGroup should not be needed when the project is targeting a single tfm

**Comment by balachir** [comment]
cc @DamianEdwards

**Comment by livarcocc** [comment]
What does the TFM have to do with this Constant? Release constant is a constant what was defined by default in project.json world and is not defined today in the SDK. To keep parity with PJ behavior, we have to emit it.

**Comment by livarcocc** [comment]
I have created https://github.com/dotnet/sdk/issues/521 in the SDK. If they emit it there, then we can remove it from migration.
