### ISSUE TITLE
Ubuntu 14.04 dotnet restore errors looking for ".metaproj" file

### ISSUE THREAD

**Issue by dprothero** [dotnet/cli#5042]
## Steps to reproduce
*On Ubuntu 14.04:*
1. `git clone https://github.com/twilio/twilio-csharp`
2. `cd twilio-csharp`
3. `git checkout next-gen-netstandard`
4. `dotnet restore Twilio.sln`

## Expected  behavior
Should successfully restore the packages. It works on Windows with the following output:
```
  Restoring packages for C:\Users\david\Projects\twilio-csharp\Twilio\Twilio.csproj...
  Restoring packages for C:\Users\david\Projects\twilio-csharp\JWT\JWT.csproj...
  Writing lock file to disk. Path: C:\Users\david\Projects\twilio-csharp\Twilio\obj\project.assets.json
  Writing lock file to disk. Path: C:\Users\david\Projects\twilio-csharp\JWT\obj\project.assets.json
  Restore completed in 602.5927ms for C:\Users\david\Projects\twilio-csharp\JWT\JWT.csproj.
  Restore completed in 602.6092ms for C:\Users\david\Projects\twilio-csharp\Twilio\Twilio.csproj.

  NuGet Config files used:
      C:\Users\david\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
```

## Actual behavior
On Ubuntu 14.04, it throws the following errors:
```
/usr/share/dotnet/sdk/1.0.0-preview5-004232/NuGet.targets(164,5): error MSB3202: The project file "/home/travis/build/twilio/twilio-csharp/JWT/JWT.csproj.metaproj" was not found. [/home/travis/build/twilio/twilio-csharp/Twilio.sln]
/usr/share/dotnet/sdk/1.0.0-preview5-004232/NuGet.targets(164,5): error MSB3202: The project file "/home/travis/build/twilio/twilio-csharp/Twilio/Twilio.csproj.metaproj" was not found. [/home/travis/build/twilio/twilio-csharp/Twilio.sln]
```

## Environment data
`dotnet --info` output:

**On the Windows machine where it works**:
```
.NET Command Line Tools (1.0.0-preview5-004232)

Product Information:
 Version:            1.0.0-preview5-004232
 Commit SHA-1 hash:  355b6233cb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004232
```

**On the Ubuntu machine where it does NOT work:**
```
.NET Command Line Tools (1.0.0-preview5-004232)
Product Information:
 Version:            1.0.0-preview5-004232
 Commit SHA-1 hash:  355b6233cb
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-preview5-004232
```

**Comment by livarcocc** [comment]
This is happening because your solution is not udpated and still points to xproj files and these xproj files have targets/props, etc that don't know about restore.

if you are using the new CLI with msbuild, try updating your solution to point to your new csproj files and then try restore.

cc @emgarten

**Comment by dprothero** [comment]
Why does it work on Windows but not Ubuntu? Can you clarify what you mean by updating my solution file to point to my new csproj files?

This is my solution file:
https://github.com/twilio/twilio-csharp/blob/next-gen-netstandard/Twilio.sln

As you can see, it is referencing my csproj files.

**Comment by livarcocc** [comment]
I see. I don't think it is what I thought. @emgarten can you please take a look.

**Comment by emgarten** [comment]
I need to do more debugging on this, but NuGet here is just using MSBuild to resolve project references where this failed. It seems like msbuild in dotnet is incorrectly adding .metaproj to the end of project paths from the solution file.

**Comment by narmontas** [comment]
I have the same problem.

**Comment by blackdwarf** [comment]
@emgarten do we have an update for this?

**Comment by emgarten** [comment]
This has been fixed in NuGet.targets

https://github.com/NuGet/NuGet.Client/commit/d927c265e2061bc67bdf4e7eedce6004eba2dacb

**Comment by melston** [comment]
I'm having the same problem on Ubuntu 16.04.

$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
mark@everest:~/Development/Test/UserPlatform$
