### ISSUE TITLE
[question] can I get these DLLs compiled too?

### ISSUE THREAD

**Issue by nictaylr** [dotnet/cli#5047]
I published an ASP.NET Core web application using the native runtime `win10-x64`.
However, the publish directory is full of all the dependency DLLs as well as the native binary. Is there a way I can have these DLLs compiled too and linked into a single binary? I want to ship a directory full of native code rather than a native launcher and a bunch of CIL dependencies.

**Comment by davidfowl** [comment]
Nope. We don't have a toolchain today for this. In the future we'll have something when .NET Native comes to the masses 😄

**Comment by piotrpMSFT** [comment]
The native compilation work is happening [here](https://github.com/dotnet/corert) if you want to follow along :)
