### ISSUE TITLE
on ubuntu14.04 the dotnet restore resove fail

### ISSUE THREAD

**Issue by judypol** [dotnet/cli#5049]
## Steps to reproduce
my folders as below:
AA
     AA-1
          project.json
     BB
         global.json
          src
              bb-1 ----it reference the AA-1 project.json
              bb-2  ----it reference the AA-1
                    project.json

when run dotnet restore AA/BB/bb-1/project.json
then got the AA-1 project is connot restore
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by piotrpMSFT** [comment]
@joelverhagen @emgarten can you take a look?

**Comment by emgarten** [comment]
@judypol would you try with the latest preview4?  It looks like this is an issue with your global.json file not having the path to AA-1, all of this has changed in the latest version however.

**Comment by judypol** [comment]
@emgarten I checked the global.json file,and it can be resoved.thank you very much!
