### ISSUE TITLE
Object reference error on `dotnet build` if `restore` was not run

### ISSUE THREAD

**Issue by BenjaminAbt** [dotnet/cli#5052]
During an internal .NET talk we stumbled over following dotnet cli error.

## Steps to reproduce

* Use a project.json with netcoreapp1.1

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      }
    }
  },
  "runtimes": {
    "win8-x64": {},
    "win10-x64": {},
    "osx.10.10-x64": {}
  }
}
```

* run `dotnet restore`
* run `dotnet build`
-> it works fine

* edit `project.json`  netcoreapp 1.1 to 1.0

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      }
    }
  },
  "runtimes": {
    "win8-x64": {},
    "win10-x64": {},
    "osx.10.10-x64": {}
  }
}
```

* run `dotnet build` (without restore before!)
-> error

## Expected  behavior
A more detailed error message, that a dotnet restore is required, if netcoreapp version has been changed

## Actual behavior
```
C:\Users\username\temp\clitest>dotnet build
Object reference not set to an instance of an object.
```

## Environment data
`dotnet --info` output:

``` 
C:\Users\username>dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

Installed SDKs:
* 1.0.0-preview2-1-003177
* 1.0.0-preview2-003121
* 1.0.0-preview2-003131

**Comment by nguerrera** [comment]
Please, please, please stop it with `catch (Exception ex) { Console.WriteLine(ex.Message); }!`

**Comment by piotrpMSFT** [comment]
@nguerrera what pattern does the compiler use to provide user output on errors? Something elegant?

**Comment by piotrpMSFT** [comment]
@BenjaminAbt Thanks for reporting. Since this is a project.json issue and has a known workaround I'm going to close it. Please do try the latest build from this repo's home page and let us know what you think!

**Comment by nguerrera** [comment]
@piotrpMSFT The compiler logs errors deliberately. It doesn't just catch *arbitrary* exceptions and use only their message.

Look at this bug I filed against csc: https://github.com/dotnet/roslyn/issues/12550

Imagine if the compiler just logged the exception message: it would have printed only "One or more errors occurred" and that would lead to confounding bug reports like this one.

If you have only a System.Exception (you don't know the strong type) and you use only its Message, you are almost certainly handling it wrong.
 
When bugs look like bugs, they get fixed. When we put sloppy catch-alls, they linger.

**Comment by piotrpMSFT** [comment]
Ok, thanks @nguerrera. Opened https://github.com/dotnet/cli/issues/5076 to track.
