### ISSUE TITLE
dotnet restore --source is lacking Username/Password/ClearTextPassword support

### ISSUE THREAD

**Issue by meichtf** [dotnet/cli#5053]
## Steps to reproduce
try to add a username/ClearTextPassword in the dotnet restore --source command

## Expected  behavior
My nuget repository requires authentication and it is not possible to add a username/ClearTextPassword in the dotnet restore command for a source

## Actual behavior
It's not possible to add a username/ClearTextPassword for a ..source

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by BenjaminAbt** [comment]
Workaround: use a NuGet.Config file and patch it during your CI build with a powershell script.

```
param($file, $feedName, $uname, $pass)

$xml =[xml](Get-Content $file)

# intention is to have

# <configuration>
#    <packageSourceCredentials>
#        <feedName>
#            <add key="Username" value="[uname] />
#            <add key="ClearTextPassword" value="[pass]" />
#        </feedName>
#    </packageSourceCredentials>
# </configuration>


# create the username node and set the attributes
$userNameNode = $xml.CreateElement("add")
$userNameNode.SetAttribute("key", "Username")
$userNameNode.SetAttribute("value", $uname)

# create the password node and set the attributes
$passwordNode = $xml.CreateElement("add")
$passwordNode.SetAttribute("key", "ClearTextPassword")
$passwordNode.SetAttribute("value", $pass)

# create the feedName node and attach the username and password nodes
$feedNameNode = $xml.CreateElement($feedName)
[void] $feedNameNode.AppendChild($userNameNode)
[void] $feedNameNode.AppendChild($passwordNode)

# create the packageSourceCredentials node and append the feedName node
$credentialsNode = $xml.CreateElement("packageSourceCredentials")
[void] $credentialsNode.AppendChild($feedNameNode);

# add the packageSourceCredentials node to the document's configuration node
$xml.configuration.AppendChild($credentialsNode);

# save the file to the same location
$xml.Save($file)
```

Then run `dotnet restore --config NuGet.Config`

**Comment by blackdwarf** [comment]
@meichtf Please file this on Nuget/Home. Thanks!

**Comment by meichtf** [comment]
@blackdwarf What should I file there? The nuget.exe commands supports it: https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#restore

**Comment by piotrpMSFT** [comment]
@joelverhagen @emgarten @rrelyea

**Comment by emgarten** [comment]
> @meichtf Please file this on Nuget/Home. Thanks!

👍 this looks like a good command to add to ``dotnet nuget``

**Comment by piotrpMSFT** [comment]
I went ahead and moved this to nuget/home#4126. Closing out the CLI copy.
