### ISSUE TITLE
Cleaner fail message when dotnet-test --framework invoked with bad tfm

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5060]
Invoking `dotnet test --framework netcoreapp2.0` on a test project that targets netcoreapp1.0 produces a wall of red text (e.g. an error for every single usage of System.String, System.Object, etc.)

Would be better to fail faster with a short, cleanr error if the TFM doesn't match a valid TargetFramework(s) in the project instead of trying to build that tfm.

**Comment by piotrpMSFT** [comment]
This likely applies more broadly than test. One problem here is that we'd need to do a design-time evaluation of the project to figure out what tfms are available...

@nguerrera @dsplaisted @rainersigwald @cdmihai @jeffkl is there a pattern by which we could grab properties and itemgroups from an msbuild invocation that failed/is failing? It would be great if we could always try to do what the user asked without perf hit, but catch the failure case and then do some more math to provide a great failure message.

**Comment by cdmihai** [comment]
Couldn't the SDK or the part of the CLI that is implemented in MSBuild check the input args in a `CheckArgsForTestBeforeTesting` target and error out if anything is wrong?

We are also thinking on adding a binary logger for post-mortem build analysis: https://github.com/Microsoft/msbuild/issues/1331
Please +1 the issue with your query (build state at certain point in time) :)

**Comment by piotrpMSFT** [comment]
@cdmihai a method like `CheckArgsForTestBeforeTesting` would need to do a design-time project evaluation to determine that netcoreapp2.0 is not a valid TFM for this project...

**Comment by cdmihai** [comment]
My assumption was that the TFM is available to the `Test` target (some other part of the build computes it (potentially by calling dependencies to check that the entire dependency tree supports a TFM) before `Test`). Isn't this correct? If it's correct, then another validation target can be hooked up just before `Test`.

**Comment by livarcocc** [comment]
@dsplaisted Another one around the same thing we were talking about this morning and that you are working on.

**Comment by livarcocc** [comment]
You will get this now:

`/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file '/test/obj/project.assets.json' doesn't have a target for '.NETCoreApp,Version=v1.0'. Ensure that restore has run and that you have included 'netcoreapp1.0' in the TargetFrameworks for your project. [/test/test.csproj]`
