### ISSUE TITLE
Publish Hash for .deb packages published via download link

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#507]
This is part of the signing plan for debian packages.

**Comment by blackdwarf** [comment]
@brthor we still need this?

**Comment by brthor** [comment]
This was a potential requirement for the release. We never worked out how to get this thing signed in an automated fashion though.

IMO we need it for RTM and should keep this open.

**Comment by blackdwarf** [comment]
Moving to 1.0.0 then. :)

**Comment by blackdwarf** [comment]
We have the hashes now thanks to the work from @naamunds so I'm moving this to Preview 4 and assigning to myself to finish.

**Comment by blackdwarf** [comment]
Closed via #4986
