### ISSUE TITLE
Eliminate cross-project source includes from CLI 

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#5070]
https://github.com/piotrpmsft/cli/blob/piotrpMSFT/locpass/test/Msbuild.Tests.Utilities/Msbuild.Tests.Utilities.csproj#L14

During the addition of the CRUD commands the CLI was updated with the expansion of a cross-project source include pattern. This pattern is terribly fragile and not obvious to debug. Let's strive to eliminate this from our codebase instead of allowing it to proliferate as it did in the recent spike.

@krwq, since you were the last to use this, could you make a pass in the code base and remove it?

**Comment by krwq** [comment]
Here is what's left:
- [ ] build_projects\dotnet-cli-build\dotnet-cli-build.csproj
-- ..\Microsoft.DotNet.Cli.Build.Framework\**\*.cs;..\shared-build-targets-utils\**\*.cs;
- [ ] build_projects\update-dependencies\update-dependencies.csproj
-- ..\..\src\Microsoft.DotNet.Cli.Utils\DebugHelper.cs
- [ ] src\dotnet-archive\dotnet-archive.csproj
-- ..\dotnet\CommandLine\*.cs;..\dotnet\CommonLocalizableStrings.cs;
- [ ] test\Microsoft.DotNet.Cli.Utils.Tests\Microsoft.DotNet.Cli.Utils.Tests.csproj
-- ..\..\src\dotnet\DotnetFiles.cs
- [ ] test\Microsoft.DotNet.Tools.Tests.Utilities\Microsoft.DotNet.Tools.Tests.Utilities.csproj
-- ..\..\src\dotnet\DotnetFiles.cs
- [ ] TestAssets\TestPackages\dotnet-dependency-tool-invoker\dotnet-dependency-tool-invoker.csproj
-- ..\..\..\src\dotnet\CommandLine\*.cs;..\..\..\src\dotnet\CommonLocalizableStrings.cs;
- [ ] tools\Archiver\Archiver.csproj
-- ..\..\src\dotnet-archive\*.cs;..\..\src\dotnet\CommandLine\*.cs;..\..\src\dotnet\CommonLocalizableStrings.cs;

**Comment by krwq** [comment]
Some of those are blocked on changes to resources (we need to generate cs files and be able to extract common localizable strings to seperate assembly)

**Comment by krwq** [comment]
@piotrpMSFT I do not believe the left items are required for preview5 (dependencies on CommonLocalizableStrings.cs)
