### ISSUE TITLE
Setup Failed asp.net core 1.0.1 tools preview 2

### ISSUE THREAD

**Issue by umarsolehri** [dotnet/cli#5073]
Setup Failed
One or more issues caused the setup to fail.Please fix the issues and then retry setup.
For more information see the log file.
[d.txt](https://github.com/dotnet/cli/files/658886/d.txt)

**Comment by piotrpMSFT** [comment]
@mlorbetske this log is from DotNetCore.1.0.1-VS2015Tools.Preview2.0.3.exe. Can you take a look?

**Comment by piotrpMSFT** [comment]
Also, should this bug move to aspnet/tooling?

**Comment by mlorbetske** [comment]
I've moved the issue to https://github.com/aspnet/Tooling/issues/910 and pinged the person who'd be best to look at it. Closing this issue so we track it in one place.

**Comment by umarsolehri** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=53840
install  vc_redist, from above metioned link, my issue solve after this
