### ISSUE TITLE
dotnet and entityframework

### ISSUE THREAD

**Issue by stuartbloom** [dotnet/cli#5082]
Hi there all

I know this issue is somehting I have doen, but I cannot for the life of me figuer it out.  I am trying to include EntityFramework in my application.

My machine is a Ubuntu 16.04 VirtualBox guest machine and I have Visual Studio Code as my IDE.

My project.json file is as follows:

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  "tooling": {
    "defaultNamespace": "test"
  }
}

```

However, when I run dotnet ef add Initial I get the following:

```
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
```

dotnet --version returns
`1.0.0-preview2-1-003177`

Any ideas on what I am doing wrong?

Thanks in advance

Stuart

**Comment by blackdwarf** [comment]
@stuartbloom there is a version of the EF tools that you can use that target 1.1.0 runtime. More details are on https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite. The version to use I believe is `1.0.0-preview4` for EF tools. 

Context: the host is telling you that the version of the EF tools you are trying to run is depending on 1.0.0 version of the runtime, while you have 1.1.0 installed. The `dotnet --version` is telling you the **CLI version** not the framework version.

**Comment by stuartbloom** [comment]
@blackdwarf Thank you so much for your quick reply.  I have amended my project.json file accordingly, using Microsoft.EntityFrameworkCore.Tools 1.1.0-preview4-final.

The only issue now is when I run `dotnet ef migrations add Initial` I get an error (in red) stating `No executable found matching command "dotnet-ef"`

I am almost there, and really appreciate your assistance.

Thanks again in advance

Stuart

**Comment by blackdwarf** [comment]
@stuartbloom did you do a restore after changing the version? 

/cc @bricelam

**Comment by stuartbloom** [comment]
@blackdwarf @bricelam 

Thanks again, cant say how much i appreciate your help, however, I have just tried it again and am getting the same, No executable found matching "dotnet-ef" :(

**Comment by blackdwarf** [comment]
@stuartbloom can you post your project.json that you are using?

**Comment by stuartbloom** [comment]
@blackdwarf here it is :) Note I have added .txt as the extension to more easily upload it ;)
[project.json.txt](https://github.com/dotnet/cli/files/664156/project.json.txt)

**Comment by blackdwarf** [comment]
@stuartbloom this all looks good, so couple of questions:

1. Is the restore of the project successful?
2. Are you sure you're invoking `dotnet ef` in the same directory as the project?

**Comment by stuartbloom** [comment]
@blackdwarf here is a screenshot of what i can see, including files
![dotnet](https://cloud.githubusercontent.com/assets/7871566/21358174/c9b1342c-c6cf-11e6-9aaa-dc5bb6144bbc.png)

**Comment by blackdwarf** [comment]
@stuartbloom ok, can you try to remove `project.lock.json` and re-run `dotnet restore` and see if that helps.

@bricelam is there something different in 1.1 version of the EF tooling for the CLI?

**Comment by stuartbloom** [comment]
@blackdwarf 
Same think I am afraid :(
![dotnet2](https://cloud.githubusercontent.com/assets/7871566/21358496/c7215ed4-c6d0-11e6-8aa5-bb87213ee05f.png)

**Comment by blackdwarf** [comment]
@livarcocc to possibly chime in. 

@stuartbloom let's wait for @bricelam to share his thoughts on this.

**Comment by stuartbloom** [comment]
will do, many thanks :)

**Comment by bricelam** [comment]
Do you have this in your `project.json` now?

```JSON
{
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  }
}
```

**Comment by bricelam** [comment]
Also, make sure the rest of the `EntityFrameworkCore` packages are version 1.1.0.

**Comment by stuartbloom** [comment]
@blackdwarf @bricelam Thanks Gents That was the issue (the missing Tools.DotNet entry)  it runs now although I get an exception but that is more than likely down to my code and that is something I should be able to figure out; hopefully.

Thanks again

Stuart
