### ISSUE TITLE
Preview5 CLI needs to install .NET Core 1.0.3 runtime

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5084]
## Steps to reproduce
1.Clean machine: Win 10 x64 ENU 
2.Install Dev15 RC.3 VSE d15prerel.26017.01
 
## Actual behavior
Clean install of latest d15prerel build does not install the 1.0.3 shared runtime under C:\Program Files\dotnet\shared\Microsoft.NETCore.App. We still only have 1.0.1.

## Expected  behavior
Latest d15prerel builds should install the 1.0.3 runtime instead of 1.0.1

**Comment by piotrpMSFT** [comment]
@eerhardt you're picking this up this week, right?

**Comment by eerhardt** [comment]
> @eerhardt you're picking this up this week, right?

Correct.  I started working on this last night.

**Comment by eerhardt** [comment]
Closing via #5210. The CLI now targets and installs 1.0.3.

Someone will still need to insert the latest CLI into VS.  @srivatsn - are you doing that?

**Comment by srivatsn** [comment]
Sure, let me know the build number.

**Comment by eerhardt** [comment]
The build is in process and the version will be `preview5-004392`.  I'll let you know when it is done.
