### ISSUE TITLE
Thoughts on the DOTNET command usage presentation.

### ISSUE THREAD

**Issue by duncangravill** [dotnet/cli#5091]
The presentation of usage information for the `dotnet` command, within the CLI, seems not to reflect its actual behaviour. There is ambiguity and confusion.

Firstly, usage information for the command is displayed by both the `dotnet` and `dotnet --help`. The usages suggested are dfferent in each case. This is confusing.

Perhaps usage information being displayed in the `--help` output should be the convention throughout the CLI. This way it will become second nature for devs to check the help page. Devs won't have to remember if they will find usage info in a command's outut or on a help page or worst or all spit accross both. If usage is **always and only** displayed on the help page it will be instinctual to check the help page, devs don't have to remember ideosyncracies of the CLI, just the conventon. So perhaps all usages of `dotnet` should collectively be displayed by `--help`

Secondly, the `dotnet [common-options] [[options] path-to application]` usage seems to misrepresent the actual behaviour. It implies that `[common-options]` can be used in combiation with `[[options] path-to-application]` when in actual fact the behaviour seems to be that if a `common-option` is used the rest of the arguments are ignored. It's either or.

So perhaps there should be three usages presented on the help page? Progressing in sophistication...

```
Usage: dotnet [common-options]
Usage: dotnet [options] <path-to-application>
Usage: dotnet [host-options] [command] [arguments] [common-options]
```

However, this makes apparent the problem of lack of convention and confusion within options.

`dotnet` lists `--version` as a `common-option`. `dotnet --help` lists `--version` as a `host-option`. `dotnet` doesn't list `--info`. `dotnet` also doesn't list `--diagnostics`, but used alone: `dotnet -d` seems to only print out `Telemetry is: Enabled` followed by the help page. Incidently `Telemetry is: Enabled` is easily lost in the noise of the help print out. If a dev wants help they should use `--help` otherwise it's just noise..... Then the `common-options` listed by `dotnet --help` are different to those listed by `dotnet`. `dotnet --help` lists `--verbose` as a `common-option`. So `common-options` are not common accross both of the usages presented. One question I have is: Is `--verbose` really a common option or is `--help` in fact the only real `common-option`?

So currently there seems to be real confusion.

Then perhaps the options simply called `options` in the `dotnet` usage presentation could be given a more descriptive name. Perhaps `hosting-options`. `hosting-options` is potentially confusable with `host-options`. I can't think of any other alternatives at the moment.

So perhaps the help page could be something like:

```
Usage: dotnet [host-options] [common-options]
Usage: dotnet [hosting-options] <path-to-application>
Usage: dotnet [host-options] [command] [arguments] [common-options]

Host options (passed before the command):
  -d|--diagnostics      Enable diagnostic output
  --info                Display .NET CLI Info

Hosting Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Common options:
  -v|--verbose          Enable verbose output
  -h|--help             Show help

Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
  migrate       Migrates a project.json based project to a msbuild based project

Project modification commands:
  add           Add items to the project
  remove        Remove items from the project
  list          List items in the project

Advanced Commands:
  nuget         Provides additional NuGet commands
  msbuild       msbuilds a project and all of its dependencies
  vstest        Runs tests from the specified files
```

I've removed the CLI version from the top of the help output, I feel that all version info should be presented on the `--info` page. I have also removed the `--version` from `Host Options` as this seems redundant as `--info` could be a single place to present all version information.

If a single usage description could be presented which encapulates and represents the three usages I have proposed with eloquence then I feel that would be preferable. However it seems there are fundamentally three usages of `dotnet`

1. `dotnet` alone with options.
2. `dotnet` to host a portable app.
3. `dotnet` to execute commands.

Perhaps the usage could be encapsulated in just two usages:
```
Usage: dotnet [hosting-options] <path-to-application>
Usage: dotnet [host-options] [command] [arguments] [common-options]
```

I guess you are probably already aware that there is a problem, but perhaps this helps to highlight it. What are your thoughts on this matter?

cc @blackdwarf @shanselman

**Comment by livarcocc** [comment]
We have since given some thought to this. The changes we made are now reflected starting in the CLI 2.1.300. Mainly, we have decided to use context first commands, like `dotnet tool` with some contexts being implicit.

@KathleenDollard has a great write-up on it and she can post the link if there is interest. It was already discussed on github though, I believe.

**Comment by KathleenDollard** [comment]
Just to flesh this out as we close it...

https://github.com/dotnet/designs/blob/master/accepted/cli-syntax-guideline.md is syntax guidelines

We agree that help is weak and we are on a gradual course to improve it. 

We are still contemplating whether to never have help output when a command requires more and it's not given. For now, we're not making changes here. 

The next release 2.1.400 has a new main help output and fixes to a number of other places in the help experience.

**Comment by KathleenDollard** [comment]
And to be clear, this should be closed because it's out of date. But if anyone sees specific places for better help, please let us know.
