### ISSUE TITLE
migrate fails when project.json contains deprecated options

### ISSUE THREAD

**Issue by ZoolWay** [dotnet/cli#5094]
## Steps to reproduce
Have a project.json which contains a `projectUrl` field at root level instead of inside `packOptions`:
```
{
  "title": "MyProject",
  "description": "MyProject",
  "version": "0.1.0-*",
  "authors": [ "me" ],
  "packOptions": {
    "tags": [ "tag1", "tag2" ],
     ...
  },
  "projectUrl": "http://www.telecomsoftware.com"
  ...
```

## Expected  behavior
Deprecated `projectUrl` generates a warning but the `.csproj` is generated omitting the field.

## Actual behavior
An error is generated and the migration is aborted.

## Workaround
Move `projectUrl` inside `packOptions` or remove.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/4166.
