### ISSUE TITLE
Add/Remove sln needs to modify build configurations

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5097]
Building the sln only respects configurations if they are present in the sln file.

**Comment by blackdwarf** [comment]
Also, restoring. For restore, if the configurations are not present, an error is returned.

**Comment by jgoshi** [comment]
We need to query for conditions in order to figure out which build configurations to add. Where possible we should make sure we end up producing the same sln file that VS would.

**Comment by jgoshi** [comment]
@davkean 

For the build configurations, is it safe to just look at this section:
GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Debug|x64 = Debug|x64
		Debug|x86 = Debug|x86
		Release|Any CPU = Release|Any CPU
		Release|x64 = Release|x64
		Release|x86 = Release|x86
EndGlobalSection

And make sure my new project has all those configurations? And if nothing is there (it’s the first project being added to an empty solution) then I just create the two:
Debug|Any CPU = Debug|Any CPU
Release|Any CPU = Release|Any CPU

Or will that be incorrect? Like I could potentially add a build configuration not meant for my project type or be missing one that my project type expects?

**Comment by jgoshi** [comment]
@davkean 

Experimenting with Visual Studio 2017 it looks like the following algorithm will be correct:
1. For adding a project always ensure (creating if necessary) the following section
GlobalSection(SolutionConfigurationPlatforms) = preSolution
Debug|Any CPU = Debug|Any CPU
Debug|x64 = Debug|x64
Debug|x86 = Debug|x86
Release|Any CPU = Release|Any CPU
Release|x64 = Release|x64
Release|x86 = Release|x86
EndGlobalSection

And ensuring that all projects (even those I didn't add) have configurations for each one. This will ensure that the sln file we generate is what VS is doing.

2. When removing a project I need to remove its build configurations. Additionally, if I remove the last project in the solution I should remove all the entire SolutionConfigurationPlatforms section.

**Comment by jgoshi** [comment]
Ok we discussed this at standup today, and for the first iteration our goal is just to add the bare minimum necessary for the build to work properly, even though this means we rely on VS to fix some things up for us. This way we can be more confident that we aren't breaking anything and will rely on user feedback to fix common cases that people run into.

So this means that whenever we add a new project we simply ensure (creating if necessary) the "Debug" and "Release" build configurations and the "Any CPU", "x64", and "x86" platforms for the project we add. And on remove we remove the projects build configurations. Additionally, if I remove the last project in the solution I should remove the entire SolutionConfigurationPlatforms section.

**Comment by blackdwarf** [comment]
@jgoshi please test with `dotnet restore` on the SLN file as well to see if it works.

**Comment by jgoshi** [comment]
It works. I have a test for that now.
