### ISSUE TITLE
Introduce new verb between compile and publish / Allow users to add functionality between verbs

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#510]
There's a set of build functionality which sits somewhere between compile and publish:
- the logic in the current post compile `place-binaries` scripts
- setting the right file permissions per OS per file
- sign?
- analyze?
- fxcop?

I suggest we introduce a new build verb between compile and publish that covers this responsibility (possible names: `deploy`, `post-build`, `pre-publish`).

A quick scan of issues that will benefit from this:
- incremental compilation (#382): the closer the compile phase is just doing compilation, the better. The `place-binaries` scripts currently break incremental safety checks
- setting the correct file permissions: #129
- deciding what to copy to output: #526 
- handling pre / post compile exceptions #443

**Comment by davidfowl** [comment]
This is what scripts are for. How would this verb work?

**Comment by cdmihai** [comment]
I think the problem needs to be split in 2:
- functionality that absolutely has to be there and CLI should be implement it in c#, within the new `deploy` verb (or maybe even a `PostRestore` verb)
 - e.g. copying compiler output, setting the right permissions per OS, etc
- arbitrary functionality that users want to run after the compilation phase. These represent extension points into the CLI and we need to define some kind of model for it. We could:
 - define an interface that users have to implement and then `deploy` picks it up (like ITask in msbuild)
 - use an analogy of msbuild's BeforeBuild and AfterBuild targets, In CLI's current model where the unit of execution is the script on PATH that starts with "dotnet-", this would translate into users creating `dotnet-prebuild` and `dotnet-postbuild` commands that would aggregate the arbitrary functionality.

Whatever the implementation decision, in the current CLI model these arbitrary scripts that can do anything should not be invoked from / implemented in the built-in CLI verbs (restore, build, compile, run, publish, etc) but should be aggregated in special phases that have the explicit semantics of running user provided functionality. If they are not separated from built-in verbs and contained, CLI will be prone to hard to debug crashes since the happy path of each built-in CLI verb would risk being perturbed by the scripts they invoke during their own execution. This problem is not entirely removed by moving the arbitrary user scripts between built-in verbs, but at least it makes things a bit more sane and debugable.

**Comment by cdmihai** [comment]
I see that issue #237 discussed problem nr. 2 from my previous post: introducing a generic mechanism which allows users to hook up event listeners (or just script runs) on pre / post dotnet verb execution.

This again is different from problem 1. for which we need to create a `deploy` verb that performs actions which most / all projects need (maybe configurable through project.json or flags)

**Comment by NikolaiTillmann** [comment]
Having PreCompile and PostCompile scripts tightly wrapping each actual compiler invocation is problematic for reliable incrementality, so we need to offer something better.

Options are a separate "deploy" verb that runs deployment scripts, or a new concept of a PostBuild script that runs after the entire build is done.

If the goal of the CLI is to tease apart pieces of functionality that are logically different, then I feel that a "deploy" verb would be the cleanest approach. But it's also confusing to have "deploy" and "publish" --- what's the difference? That would speak for PostBuild or PrePublish script. If we expect these scripts to be or become somewhat involved, then maybe PostBuild would be best, and one day we might enhance the "build" verb to perform the tasks that PostBuild scripts tend to do, but in a way that supports incrementality. If we expect the scripts to always remain shallow, than a PrePublish script might be better.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
