### ISSUE TITLE
After migrating a *xproj to *csproj, the referenced project name is not updated.

### ISSUE THREAD

**Issue by ravipal** [dotnet/cli#5101]
## Steps to reproduce
1. In VS 2015 Update 3, install Service Fabric Tools for VS 2015 - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started
2. Create a new Service Fabric application project. New Project -> Cloud -> Service Fabric Application -> ASP.Net Core (Preview). This will create a *sfproj that references *xproj.
3. Now open this solution in VS 2017 and migrate the projects. *.xproj will be converted to *.csproj

## Expected  behavior
ProjectReference in *.sfproj should be updated to refer the migrated projected (*.csproj)

  \<ItemGroup\>
    \<ProjectReference Include="..\Web1\Web1.csproj" /\>
  \</ItemGroup\>

## Actual behavior
ProjectReference in *.sfproj is not updated and still refers the old project, this result into build error.

  \<ItemGroup\>
    \<ProjectReference Include="..\Web1\Web1.xproj" /\>
  \</ItemGroup\>

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by livarcocc** [comment]
This is dup https://github.com/dotnet/cli/issues/4958 in the CLI.

**Comment by ravipal** [comment]
This issue is not fixed in the latest rc3 build (D15Rel.26124.00)

**Comment by livarcocc** [comment]
@ravipal How did you run migration? In order to migrate a sln (update the xprojs to csprojs inside the sln file) you need to invoke dotnet migrate <sln_file>.

Running dotnet migrate on the folder containing the sln file will not update it and will not migrate only the projects in the sln. It will migrate anything it can find in the directory and the sln will not be updated.

Issue https://github.com/dotnet/cli/issues/5238 is taking care of finding the sln and updating it, though the whole folder will still be migrated.

**Comment by ravipal** [comment]
@livarcocc I was simply opening the *sln file created in Dev14 in Dev15, which initiated the conversion of *.xproj to *.csproj, I though this action is the migration. Do I need to explicitly run "dotnet migration <sln_file>" before opening the *.sln file in Dev15?

**Comment by livarcocc** [comment]
I see. Well, that should work, but if you are not in the latest VS2017, that also had issues in the past and I am pretty sure you hit one of those.

**Comment by ravipal** [comment]
I tried "dotnet migrate <sln_file>" as well. It didn't update the reference to *.xproj in *.sfproj.
The build I am using the latest rc3 release build (26124.00).

C:\Users\ravipal\Documents\Visual Studio 2017\Projects\ASP_SF>dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by livarcocc** [comment]
Would it be possible to share the project you are migrating?

**Comment by ravipal** [comment]
It is at \\scratch2\scratch\Ravipal\Issues\cli\5101\ASP_SF.zip

**Comment by ravipal** [comment]
@livarcocc can your please reactivate this issue? I don't have access to reactivate.

**Comment by livarcocc** [comment]
Ah, I understand this now. This is actually an sfproj file. Sorry, I assumed that was a typo and you had meant an xproj.

Migration will not update this file. It does not handle it. It creates new csproj files from project.json/xproj files and it updates .sln files by changing xproj references to the new csproj files.

sfproj is not a file that migration understands and migration does not update any *proj files. In the case of xproj to csproj, it is not an update, a brand new one is actually created.
