### ISSUE TITLE
dotnet add/remove/list p2p should be renamed to dotnet add/list/remove project

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#5103]

**Comment by krwq** [comment]
@blackdwarf, I think that SLN and P2P are quite different concerns and should not be merged this way.

I think we should rather either have a single command for all p2p, pkg, sln (perhaps separate built on top of existing) or have them split completely.

The other reason to have them split is that we don't know what to display when you type `dotnet list project` in a folder which contains both sln and csproj which can become annoying

**Comment by blackdwarf** [comment]
@krwq 

> I think we should rather either have a single command for all p2p, pkg, sln (perhaps separate built on top of existing) or have them split completely.

I don't understand this. What do you mean?

> The other reason to have them split is that we don't know what to display when you type dotnet list project in a folder which contains both sln and csproj which can become annoying

In this case you would have to specify the `object` (as we referred to it) of the operation.

**Comment by krwq** [comment]
> > I think we should rather either have a single command for all p2p, pkg, sln (perhaps separate built on top of existing) or have them split completely.
> 
> I don't understand this. What do you mean?
That now we will have: `dotnet add project` for something as orthogonal as p2p and sln and separate `dotnet add package`. I believe they should be just simply `dotnet <object> add` or something similar to what we already have (perhaps different names)
