### ISSUE TITLE
dotnet publish -r win10-x64 fails

### ISSUE THREAD

**Issue by pwasiewicz** [dotnet/cli#5105]
## Steps to reproduce
1. Create Web Application with Basic Authentication
2. Add `<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>`
3. Run `dotnet restore`
4. Run `dotnet build -r win10-x64`

## Expected  behavior
Project is built successfully.

## Actual behavior
Build fails:

C:\Users\patry\AppData\Local\Temp\.NETCoreApp,Version=v1.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [C:\Users\patry\Documents\Visual Studio 2017\Projects\SquadPlanning\src\SquadPlanning\SquadPlanning.csproj]

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by felix-b** [comment]
The same happens to console application, both in ```dotnet build``` and ```dotnet publish```, no matter what RID I try.  My environment is identical to @pwasiewicz's except for ```OS Version:  10.0.14393```

**Comment by blackdwarf** [comment]
@pwasiewicz can you try using the RC4 bits and see if this still repros?

**Comment by piotrpMSFT** [comment]
@mlorbetske this seems troubling. We may have a template error.

Check out the file for assemblyinfo.cs. It should be {projectname}.AssemblyInfo.cs. It shows up as `Temp.NETCoreApp,Version=v1.0.AssemblyAttributes.cs`. Are we somehow appending the TFM to the project name?

**Comment by mlorbetske** [comment]
@pwasiewicz guessing from the path the project is created under, was this project was created by Visual Studio? If so, and you're still able to repro this, could you add the contents of the `Help -> About` window to the issue please?

**Comment by livarcocc** [comment]
I tried this out just now and it all restore and built successfully for me using CLI 1.0.1. I am closing this issue. If this still repros for you, please re-activate and add additional details to the bug.
