### ISSUE TITLE
Incorrect PackageTargetFallback element after dotnet migrate

### ISSUE THREAD

**Issue by itlackey** [dotnet/cli#5115]
## Steps to reproduce
yo aspnet web example bootstrap
cd example
dotnet migrate
dotnet restore
dotnet build
--dotnet ef database update also fails but that is a different issue
dotnet run

## Expected  behavior
should start webserver on localhost:5000

## Actual behavior
Produces error:
A fatal error was encountered. The library 'libhostpolicy.dylib' required to execute the application was not found in '/Users/itlackey/repos/example/bin/Debug/netcoreapp1.0'.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview4-004233

### Additional Info

XML in created csproj:
```
 <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>example</AssemblyName>
    <OutputType>Exe</OutputType>
    <UserSecretsId>SOME SECRET ID</UserSecretsId>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>
```

Changing the the PackageTargetFallback by removing dotnet5.6; as follows allows the application to run:
```
<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">$(PackageTargetFallback);portable-net45+win8+wp8+wpa81></PackageTargetFallback>
```

This may be related to this issue: https://github.com/dotnet/sdk/issues/527

**Comment by livarcocc** [comment]
After you made this change, does it run successfully 100% of the time? I suspect this may be an instance of this as well: https://github.com/dotnet/cli/issues/5059.

**Comment by itlackey** [comment]
I will check as soon as I get a chance.

**Comment by itlackey** [comment]
It does not and as mentioned in #5059 when it does work there are the example.runtimeconfig.dev.json and example.runtimeconfig.json files created.

Guess this is a dup. Sorry about that :(

**Comment by itlackey** [comment]
Closing, already reported more correctly elsewhere ie. #5059
