### ISSUE TITLE
[loc][Query][DotNet_OSS] Please clarify the placeholders

### ISSUE THREAD

**Issue by mkyjakova** [dotnet/cli#5117]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
{0} `\{1\}` found but is invalid.
{0} `\{1\}` does not exist.
More than one {0} found.
{0} already contains \{1\} `\{2\}`.
{0} already has \{1\} `\{2\}`.
Please specify at least one {0}.

File Name:
CommonLocalizableStrings.es

Query:
Can you please let us know what all the placeholders above stand for? Thanks!

**Comment by livarcocc** [comment]
This can vary.

It is along the lines of Project 'c:\something\something.csproj' found but is invalid. Same for the does not exist.

Or more than one 'project' found.

And it continues along these lines for the others.

Does this help?

**Comment by mkyjakova** [comment]
HI @livarcocc , thanks. It does help, but I need a bit of clarification. The first 3 strings  and the last one are clear, the placeholders will be substituted by "project". 
However, for the 4th and 5th ones, can you clarify what the {1} will refer to? I'm guessing {0} will be "project" as well. Thanks!

**Comment by livarcocc** [comment]
These are general strings that we can use to construct error messages.

For instance, it can mean Folder already has a csproj. Or Project already has reference. Similarly for the other one.
