### ISSUE TITLE
[loc][Query][DotNet_OSS] Please clarify the single word strings

### ISSUE THREAD

**Issue by mkyjakova** [dotnet/cli#5118]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
List
Group

File Name:
CommonLocalizableStrings.es

Query:
Can you please let us know whether there are nouns or verbs in this context? Thanks!

**Comment by livarcocc** [comment]
List is a verb.
I believe Other is a noun.

**Comment by mkyjakova** [comment]
Thanks, @livarcocc . I assume by "Other" you mean "Group", correct?

**Comment by mkyjakova** [comment]
Hi @livarcocc can you please have a look at this bug and reply? Thanks!
