### ISSUE TITLE
dotnet cli on Yocto

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/cli#5120]
The last couple of days, I have been successful in building CoreCLR and CoreFX within my Yocto/OpenEmbedded environment for Linux/ARM (see [Tragetaschen/meta-aspnet](https://github.com/Tragetaschen/meta-aspnet/)). The result at the moment is a `/opt/dotnet` folder with `corerun` and friends and those assemblies from CoreFX that ship with the current Linux tooling on the supported distros.

By using `corerun`, I can run a simple "Hello World" executables (a published `dotnet new` project), and even a `dotnet new -t web` boots and serves static files.
```
root@f500sx:~/HelloWeb# /opt/dotnet/corerun HelloWeb.dll
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using '/home/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Content root path: /home/root/HelloWeb
Now listening on: http://*:80
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://f500sx/css/site.css
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/css/site.css'. Physical path: '/home/root/HelloWeb/wwwroot/css/site.css'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2131.5756ms 200 text/css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://f500sx/css/site.css
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/css/site.css'. Physical path: '/home/root/HelloWeb/wwwroot/css/site.css'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 28.0276ms 200 text/css
```
However, more complicated workloads like Razor view compilation don't work and fail in the `CompilationLibrary.ResolveReferencePaths()` call. As far as I can see, this boils down to the limited package management support in `corerun` compared the much more involved `dotnet` host.

I have also looked at what Tizen is doing, but from what I grasped, they created their own [launcher](https://review.tizen.org/git/?p=platform/core/dotnet/launcher.git;a=tree;f=NativeLauncher;h=f0903fa1ac3685c4f254564bfbfb16c7e5a5762b;hb=refs/heads/tizen) to boot the CLR.

I have already seen that building the CLI is "a bit" more involved, so before running into too many walls:

What would be the next steps here?

**Comment by ernstp** [comment]
Have you seen: https://github.com/dotnet/core-setup/issues/725 ?

**Comment by Tragetaschen** [comment]
Yup, I'm following that as well as most of the linked issues there.

The biggest "problem" I can see is the concept of RIDs which is tailored towards definite distributions like Ubuntu or Tizen with their set of libraries and specific versions as opposed to meta distributions like Yocto/OpenEmbedded where the versions and especially the configuration of the various packages potentially varies greatly. Kestrel for example ships with pre-built compiled versions of libuv based on the RIDs. What would Kestrel ship for "Yocto Morty"?

On the other hand, the Yocto tool chain is certainly capable of creating an environment suitable for e.g. the generic "linux-arm" RID, but AFAIC see, this isn't an environment where the `dotnet` tooling works.

**Comment by piotrpMSFT** [comment]
I'd certainly start with getting core-setup building. You will need a native build of the `dotnet` host executable as well as a properly laid out Shared Framework. Once those components are in-place the CLI should `just work` and we can help you figure out how to bootstrap the CLI build.

**Comment by Tragetaschen** [comment]
The native dotnet host is now available (dotnet/coreclr#1598).

I tried to create a cli build. However, I keep running into walls when it comes to defining the right RIDs at the right places.

**Comment by sam0302** [comment]
I am trying to build coreclr in yocto for raspberrypi and getting following error when i do 
$bitbake coreclr

Log data follows:
| DEBUG: Executing shell function do_compile
| Commencing CoreCLR Repo build
| Setting up directories for build
| Checking prerequisites...
| Restoring the OptimizationData package
| Running init-tools.sh
| Installing dotnet cli...
| curl: (7) Failed to connect to dotnetcli.blob.core.windows.net port 443: Network is unreachable
| tar: /home/patnasa/projectX/pelux_v1.0/ntgx-manifests/build/tmp/work/cortexa7hf-neon-vfpv4-pelux-linux-gnueabi/coreclr/2.0.0-r0/git/Tools/dotnetcli/dotnet.tar: Cannot open: No such file or directory
| tar: Error is not recoverable: exiting now

My yocto env is set up in Ubuntu 16.04. When i try to manually run ./build.sh in Ubuntu, it just works fine. Could anyone please provide some inputs here.

**Comment by livarcocc** [comment]
I am not familiar with yocto, but it seems from the above that you have network problems in your environment and that URL can't be resolved or reach from your environment. Not really specific to the CLI. Try curl on it or something like that, you should get similar results.

**Comment by sam0302** [comment]
Thanks for the response, yes it was proxy issue, i had to add proxy setting to ~/.curlrc and then it worked fine, however, it gives another issue not with dotnet restore. It gives below error when running "init_tools.sh"

Unable to load the service index for source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json.
/coreclr/2.0.0-r0/git/Tools/dotnetcli/sdk/2.0.0-preview1-005724/NuGet.targets(97,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json.

For this I tried adding below lines to ~/.nuget/Nuget/Nuget.config but not luck!!!

 <config>
    <add key="http_proxy" value="http://proxy-<corp proxy>:3128" />
    <add key="https_proxy" value="https://proxy-<corp proxy>:3128" />
</config>

**Comment by livarcocc** [comment]
This still seems like a network issue that is affecting restore.

**Comment by sam0302** [comment]
Ok, finally resolved all proxy issues. There is another issue as below:

 In file included from /build/tmp/work/xxx-linux-gnueabi/coreclr/2.0.0-r0/git/src/debug/createdump/createdump.h:27:
| /build/tmp/work/xxx-linux-gnueabi/coreclr/2.0.0-r0/git/src/inc/cor.h:2210:1: error: __declspec attribute 'selectany' is not supported [-Werror,-Wignored-attributes]
| SELECTANY const mdToken g_tkCorEncodeToken[4] ={mdtTypeDef, mdtTypeRef, mdtTypeSpec, mdtBaseType};
| ^
|/build/tmp/work/xxx-linux-gnueabi/coreclr/2.0.0-r0/git/src/inc/cor.h:2207:41: note: expanded from macro 'SELECTANY'
|     #define SELECTANY extern __declspec(selectany)

**Comment by livarcocc** [comment]
That seems like a CoreCLR failure, not a CLI build issue. I would file an issue there for this.

**Comment by livarcocc** [comment]
I am going to close this issue as it has been a while and this is not something that we are currently looking into supporting ourselves. Besides, the last failure reported seems like a coreclr failure.
