### ISSUE TITLE
publishOptions include files ignored when relative output directory is used.

### ISSUE THREAD

**Issue by cjames9001** [dotnet/cli#5123]
## Steps to reproduce

dotnet new -t web
dotnet restore
dotnet publish --output "..\publishdir"

## Expected  behavior

The project is published to the publishdir folder one level above the current directory and includes all the files and folders listed in the project.json under the publish options:
```
"publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  }
```

## Actual behavior

The project is published to the publishdir folder one level above the current directory and does **not** include any of the files or folders listed under the publish options.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003156)

Product Information:
 Version:            1.0.0-preview2-003156
 Commit SHA-1 hash:  33dabee5d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by cjames9001** [comment]
Since I didn't note above, the workaround is to specify a full path as the output directory instead of a relative path.

**Comment by piotrpMSFT** [comment]
Thanks for the workaround @cjames9001. I'm closing the issue as this only affects the project.json tooling and we have no further releases planned for those tools. Please consider installing the latest RC3 bits from the home page of this repo and running `dotnet migrate` on your project to try out the new experience.
