### ISSUE TITLE
I cannot download ".NET Core 1.1 SDK - Installer for macOS"

### ISSUE THREAD

**Issue by NewGyu** [dotnet/cli#5125]
## Steps to reproduce

1. Access to https://www.microsoft.com/net/download/core#/current
2. Click x64.pkg ( https://go.microsoft.com/fwlink/?LinkID=835011 )
3. Downloaded file name is "dotnet-dev-osx-x64.1.0.0-preview2-1-003177.pkg"

**Comment by lvillavicencio** [comment]
There is not 1.1 SDK.

**Comment by vcsjones** [comment]
This is a matter of the name of the file. `dotnet-dev-osx-x64.1.0.0-preview2-1-003177` is the name of the file with the .NET 1.1 SDK. The version number you see in the file name is the version of the SDK, which is 1.0.0-preview2.

**Comment by NewGyu** [comment]
Ohh I get it.

```
$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576
```

```
$ dotnet 

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

I understand that `1.0.0-preview2-1-003177` is CLI Tool's version.
