### ISSUE TITLE
Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by jdscolam** [dotnet/cli#5129]
## Steps to reproduce

1. Follow the public instructions for installing and configuring .NET core on Mac OSX from [here](https://www.microsoft.com/net/core#macos)
2. Create a directory to host a new application
3. Run "dotnet new -t web" from the terminal
4. Run "donnet restore" from the terminal

## Expected  behavior

All the necessary nuget packages should be installed.

## Actual behavior

A series of errors ending with "Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found."

## Resolution

I had to run a modified version of the install_name_tool command from [this StackOverflow answer](http://stackoverflow.com/a/40448157/292547).  The command that resolved the issue is as follows:

`sudo install_name_tool -add_rpath /usr/local/opt/openssl/lib /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.0/System.Security.Cryptography.Native.OpenSsl.dylib`

This step should be added into the instructions for installing .NET Core on a Mac if possible.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

**Comment by blackdwarf** [comment]
@jdscolam when you followed the instructions, you did create the symlinks to the brew installed openssl files?

**Comment by jdscolam** [comment]
@blackdwarf yes I did, I followed the instructions step by step as listed on the site.  In addition I checked to make sure that the symlinks were listed in the directory as expected.

**Comment by blackdwarf** [comment]
@jdscolam that is weird then, because those instructions have been there for a while. OK, I hope you don't mind me asking a couple of more questions to get to the root cause of this:

1. Which version of OpenSSL did you install?
2. You did use `brew` to install, correct?
3. Can you `ls -al` in the directory where you created the symlinks and share the output?

**Comment by jdscolam** [comment]
@blackdwarf looks like this has been resolved with the more recent updates to .NET Core's Mac installation instructions.  Feel free to close 👍 .
