### ISSUE TITLE
dotnet restore multiple bugs

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#513]
Bug #1: It says it is dnu restore!
Bug #2: Why does publish support "-r" as shortcut for "--runtime" but not restore?

>   
  Usage: dnu restore [arguments] [options]
  
  Arguments:
    [root]  List of projects and project folders to restore. Each value can be: a path to a project.json or global.json file, or a folder to recursively search for project.json files.
  
  Options:
    -s|--source <FEED>          A list of packages sources to use for this command
    -f|--fallbacksource <FEED>  A list of packages sources to use as a fallback
    -p|--proxy <ADDRESS>        The HTTP proxy to use when retrieving packages
    --no-cache                  Do not use local cache
    --packages                  Path to restore packages
    --ignore-failed-sources     Ignore failed remote sources if there are local packages meeting version requirements
    --quiet                     Do not show output such as HTTP request/cache information
    --parallel                  Restores in parallel when more than one project.json is discovered.
    --lock                      Creates dependencies file with locked property set to true. Overwrites file if it exists.
    --unlock                    Creates dependencies file with locked property set to false. Overwrites file if it exists.
    --runtime <RID>             List of runtime identifiers to restore for
    -?|-h|--help                Show help information
/Users/gkhanna/Github/gkhanna79/corert/src/packaging/pack

**Comment by brthor** [comment]
Using dnu as our restore mechanism is a point in time artifact until nuget x-plat comes along. 
My understanding is that this is coming for Beta.

See #421

cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
yep, point in time. xplat nugget is not yet available so this is the stopgap. @gkhanna79 can you open a bug in the NuGet repo to track option naming consistency and close this one out with a pointer to it?

**Comment by davidfowl** [comment]
Better to file individual bugs. We should treat this like a question and file real bugs and assign to devs

**Comment by gkhanna79** [comment]
Filed as https://github.com/dotnet/cli/issues/518
