### ISSUE TITLE
No executable found matching command "dotnet-.....dll"

### ISSUE THREAD

**Issue by daneb** [dotnet/cli#5137]
## Steps to reproduce
Starting a Linux-based WebApi with systemd:
\# **sudo systemctl start kestrel-wolverine.service**

On command line this works (in current directory of dll):
$ dotnet Wolverine.dll
Hosting environment: Production
Content root path: /var/aspnetcore/Wolverine
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

**This doesn't:**
$ /usr/bin/dotnet /var/aspnetcore/Wolverine/Wolverine.dll
No executable found matching command "dotnet-/var/aspnetcore/Wolverine/Wolverine.dll"

## Expected  behavior
Starting up the service for Nginx to interact with on port 5000

## Actual behavior
\# **sudo sudo journalctl -fu kestrel-wolverine.service**
Dec 23 09:47:02 sheltered systemd[1]: Started Example .NET Web API Application running on Debian.
Dec 23 09:47:02 sheltered Wolverine[66237]: _No executable found matching command "dotnet-/var/aspnetcore/Wolverine/Wolverine.dll"_
Dec 23 09:47:02 sheltered systemd[1]: kestrel-wolverine.service: main process exited, code=exited, status=1/FAILURE

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64

**Comment by ellismg** [comment]
If you set `COREHOST_TRACE=1` when this doesn't work is there any relevant output to stdout?  That will cause the host to print what it's doing.

**Comment by livarcocc** [comment]
Can you please move this bug to https://github.com/dotnet/core-setup. This is the dotnet host code, which lives in core-setup.

**Comment by daneb** [comment]
@ellismg as requested.

```
Jan 03 16:20:21 sheltered systemd[1]: Unit kestrel-wolverine.service entered failed state.
Jan 03 16:20:22 sheltered systemd[1]: kestrel-wolverine.service holdoff time over, scheduling restart.
Jan 03 16:20:22 sheltered systemd[1]: Stopping Example .NET Web API Application running on Debian...
Jan 03 16:20:22 sheltered systemd[1]: Starting Example .NET Web API Application running on Debian...
Jan 03 16:20:22 sheltered systemd[1]: kestrel-wolverine.service start request repeated too quickly, refusing to start.
Jan 03 16:20:22 sheltered systemd[1]: Failed to start Example .NET Web API Application running on Debian.
Jan 03 16:20:22 sheltered systemd[1]: Unit kestrel-wolverine.service entered failed state.
Jan 03 16:20:35 sheltered systemd[1]: [/etc/systemd/system/kestrel-wolverine.service:6] Executable path is not absolute, ignoring: COREHOST_TRACE=1 /usr/bin/dotnet Wolverine.dll
Jan 03 16:20:35 sheltered systemd[1]: kestrel-wolverine.service lacks ExecStart setting. Refusing.
```

**Comment by daneb** [comment]
@livarcocc thanks - are you recommending I re-post my initial issue to core-setup or you asking someone internal to move it?

**Comment by blackdwarf** [comment]
@daneb done. I will close this issue here so that the discussion can proceed on dotnet/core-setup#1126.
