### ISSUE TITLE
MSB3243 in empty ASP.Core project (just template + update) - how to deal with it?

### ISSUE THREAD

**Issue by rpokrovskij** [dotnet/cli#5138]
## Steps to reproduce
Get VS 2017 RC .
Update default ASP.Core project (for Standard Framework) using NUGET Update to last versions

## Expected  behavior
no errors, no warnings or warnings that can tell you what should be improoved 

## Actual behavior

```
Warning	MSB3243	No way to resolve conflict between "System.IO.Compression, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089". Choosing "System.IO.Compression, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.	AdminkaV1.Web	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1909	

Warning	MSB3243	No way to resolve conflict between "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.	AdminkaV1.Web	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1909	
```

I understand that I should edit dependencies... but where? It is impossible to remove the dependencies from solution explorer because of error:

![image](https://cloud.githubusercontent.com/assets/11598038/21456700/bd5fc8e0-c932-11e6-9ebe-ff9331b17c62.png)

## Environment data
`dotnet --info` output:

```
PM> dotnet --version
1.0.0-preview2-003131
PM> dotnet --info
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

It is so strange! Wh`y dotnet version` deffers from `dotnet info `??
_Appended:_ after some time I can't repeat it; now both versions and info shows the same preview4. 

**Other:**

Test Project:
[WebApplication1.zip](https://github.com/dotnet/cli/files/671204/WebApplication1.zip)

Updates that was done on template:

![update1](https://cloud.githubusercontent.com/assets/11598038/21459385/5ba246aa-c946-11e6-92e3-648911474b77.PNG)
![update2](https://cloud.githubusercontent.com/assets/11598038/21459386/5ba2e34e-c946-11e6-8ac7-6cae19c67b7b.PNG)

It is also important: is it possible to prepare package list with dotnet cli?

**Comment by mikeesouth** [comment]
I second this. I get the same warnings about assembly references. Have you found any workaround @rpokrovskij ?

The `dotnet --version` shows .NET Core SDK version (1.0.0-preview2-003131) and `dotnet --info` shows the tooling version (1.0.0-preview4-004233).

**Comment by rpokrovskij** [comment]
@mikeesouth No, waiting for MS acknowledge issue. If somebody knows any links with information about how the combination of msbuild/cproj + tooling (priview4)+ .net framework  works, please share it.

**Comment by MoxxNull** [comment]
Same error with my project (both tooling & donet are @1.0.0-preview4-004233).

**Comment by piotrpMSFT** [comment]
@mlorbetske @rrelyea I understand there are known issues in updating packages in ASP.NET projects. Can you guys take a look?

**Comment by mlorbetske** [comment]
@rpokrovskij the test project seems to work (no warnings or errors) with the CLI 1.0.0-rc3-004517 and with the upcoming release of Visual Studio.

@phenning these are the two warnings that we saw previously with the .NET Core on full framework that have been resolved for the upcoming release, correct?

**Comment by dsplaisted** [comment]
This should be fixed in the latest versions of the SDK.

**Comment by rpokrovskij** [comment]
May I ask you to explain what happened, how to read those warnings? I need it just to understand better how tooling works. It is not intersting just to learn that "bug will be fixed in next version..."

**Comment by dsplaisted** [comment]
@rpokrovskij Honestly I wouldn't worry about trying to understand this one.  There are situations where you end up with multiple references to different versions of the same DLL.  There were various issues where MSBuild wouldn't know which one to pick.  See dotnet/sdk#514 and Microsoft/MSBuild#1329 for some of the details.

**Comment by livarcocc** [comment]
This seems to have been fixed already. Closing for now. If there is still something that needs to addressed here, please re-activate.
