### ISSUE TITLE
When migrating projects running on .NET Framework, dotnet migrate adds the full set of RuntimeIdentifiers

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5141]
## Steps to reproduce
Using VS 2017 RC.2 (CLI 1.0.0-preview4-004233)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWeb_OnNet452_Empty_1
dotnet migrate

## Actual behavior
The full set of RuntimeIdentifiers get added, which will cause the project to now be built for all these platforms

```
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    ...
  </PropertyGroup>
```

## Expected  behavior
The project.json we are migrating did not have a RID specified. Can no RuntimeIdentifier be specified in the csproj as well and the RuntimeIdentifier can be inferred based on the platform (similar to how it behaved in the project.json world)?

```
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    ...
  </PropertyGroup>
```

**Comment by balachir** [comment]
cc @DamianEdwards

**Comment by livarcocc** [comment]
cc @nguerrera @dsplaisted @srivatsn If these migrated projects are to work in both CLI and VS, we would need to have the inference happen in the SDK, or in the very least, have VS do the inference as well. Would it be possible for this to happen in the SDK?

One thing that worries me is that inference would only have to happen for full framework TFMs. So, imagine I have a project with netcoreapp1.0 and net452. Should restore always infer runtime then, to allow for build --framework net452 whenever? I guess it wouldn't differ from today's behavior where restore restores packages for all specified rids.

If we made restore also infer runtimes, then it should work everywhere else without the RIDs in the project.

**Comment by dsplaisted** [comment]
I'm not sure this issue is exactly the same as the ones we have filed in the SDK repo (dotnet/sdk#357 and dotnet/sdk#396).  In those issues we're talking about automatically inferring a single `RuntimeIdentifier` when targeting .NET Framework.

@livarcocc What exactly is the behavior of project.json that the migrate tool is replicating by adding the `RuntimeIdentifiers`?  Is it so you can do the following?

```
dotnet restore
dotnet build
dotnet publish -r ubuntu.14.04-x64
```

IE you're publishing for a runtime that wasn't explicitly specified in the project file or as an argument to the restore command.

I'm hesitant to automatically restore for all possible runtimes.  It means that a simple restore and build will download the full closure of packages for all platforms.

**Comment by livarcocc** [comment]
@dsplaisted Migration is adding the runtimes because full framework requires a runtime to build/publish/etc.

Because we don't know which runtime the user was to use for the full framework, we are adding them all.

**Comment by livarcocc** [comment]
@nguerrera and I talked this morning.

Here is the suggestion to address this:
If only full framework, use single TFM with win7-x86
```
<TargetFramework>net46</TargetFramework>
<RuntimeIdentifier>win7-x86</RuntimeIdentifier>
```
if core and full, use RuntimeIds with all and a conditioned RuntimeId with win7-86.
```
<TargetFrameworks>net46;netcoreapp1.0</TargetFrameworks>
<RuntimeIdentifiers>win7-x86;win7-x64;osx10.11-x64...</RuntimeIdentifiers>
<RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net46' ">win7-x86</RuntimeIdentifier>
```

**Comment by livarcocc** [comment]
@blackdwarf This is the info you were looking for.

**Comment by blackdwarf** [comment]
So I'm confused somewhat...if the RID is required **only** for full fx, why do we need to put all of them in for double-targeting between Core and full if we also put in a `win7-x86` one that is conditioned on the full TFM that exists in the project?

I guess I'm missing something here...

**Comment by fubar-coder** [comment]
@livarcocc Is it correct to always specify `win7-x86` even when the x64 CLR is used to run the build?

**Comment by livarcocc** [comment]
Yeah, we will be able to build it. The win7-x86 is simply the best guess we can make for a good experience.

Note though that we will only do this if the user doesn't already have runtimes in his project.json. If runtimes are present in the PJ, we will simply migrate those.

**Comment by fubar-coder** [comment]
My concern isn't about the build, but about the debugging and running where a x64 CLR might be used while a x86 libuv might be copied to the output folder. I really hoped that all DLLs for all runtime identifiers were copied to the output folder (for the build) and that the correct one would be chosen by the runtime. This would've allowed to just use simple xcopy deployment and would've solved the problem on the customers computers where a x86 or x64 Windows might be used.

**Comment by dsplaisted** [comment]
@fubar-coder We don't have support for automatically loading the correct platform-specific native DLLs on .NET Framework.  We could fix this experience either by doing something similar to what .NET Core does (although that would probably require a new version of the .NET Framework), or modifying the libuv/kestrel packages to deploy both versions of libuv and automatically choose the right one in the kestrel code.  The latter option is what [Microsoft.DiaSymReader.Native](https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/) uses.

**Comment by srivatsn** [comment]
The other option is to infer the RID for the current machine so that build and debug works fine. It has the downside that if the built assets are copied to another machine, it may not work and that users will have to publish to copy assets outside the current machine. That's how it's worked in the past and so it's likely fine. https://github.com/dotnet/sdk/issues/357 is tracking that.
