### ISSUE TITLE
When migrating projects with a single tfm, dotnet migrate should not need to add IsCrossTargetingBuild conditions

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5143]
## Steps to reproduce
Using VS 2017 RC.2 (CLI 1.0.0-preview4-004233)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWebApp_NoAuth_1
dotnet migrate

## Actual behavior
Condition for IsCrossTargetingBuild gets added to the csproj

```
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>
```

## Expected  behavior
Condition for IsCrossTargetingBuild are not needed when we know that the project is targeting only 1 tfm

It can simply be:
```
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="bower install" />
    <Exec Command="dotnet bundle" />
  </Target>
```

**Comment by balachir** [comment]
cc @DamianEdwards

**Comment by livarcocc** [comment]
Should be all right to change this.
