### ISSUE TITLE
dotnet not recogonized - possible PATH issue?

### ISSUE THREAD

**Issue by fmorriso** [dotnet/cli#5148]
## Steps to reproduce

1. Install
DotNetCore.1.0.1-VS2015Tools.Preview2.0.3.exe

2. Install
dotnet-win-x64.1.1.0.exe

3. Install 
dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe

4. Open command prompt

5. Type 
dotnet --version

## Expected  behavior
Output of DotNet core version information

## Actual behavior

'dotnet ' is not recognized as an internal or external command

I cannot find anywhere in the documentation or readme information about what needs to be in the PATH and maybe what should NOT be in the PATH and in WHAT ORDER.
[path.txt](https://github.com/dotnet/cli/files/673189/path.txt)

## Environment data
`dotnet --info` output:
(unable to produce)

## PATH
See attached path.txt file which was produced via $env:PATH -split ';' | Out-File path.txt

**Comment by dhruvb14** [comment]
Same issue here. Any help?

**Comment by fmorriso** [comment]
@dhruvb14 : Thanks.  Adding C:\Program Files\dotnet to the path works.
FYI: I used a free tool named Rapid Environment Editor from rapidee.com to make the change.  That tool needs to be launched "As Administrator" in order to change the System Path.

**Comment by piotrpMSFT** [comment]
`dotnet` is put on the PATH by the host which is built from the core-setup repo. Moving the issue there.
