### ISSUE TITLE
Build fails after adding Resources.resx file

### ISSUE THREAD

**Issue by harshjain2** [dotnet/cli#5149]
## Steps to reproduce
1. Create a new Class Library (.net standard) in Visual Studio 2017.
2. Add a Resource1.resx file. 
3. Add a key value pair in .resx file.
4. Build the solution. 

## Expected  behavior
Build should succeed. 

## Actual behavior
Getting error:

> 'Type' does not contain a definition for 'Assembly' and no extension method 'Assembly' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

![image](https://cloud.githubusercontent.com/assets/13763032/21485871/6bc85092-cbd0-11e6-8501-c0d38ba3fc34.png)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

## Workaround
Make this change in the Resource1.designer.cs
Add namespace :
`using System.Reflection;`
Change this 
`typeof(Resource1).Assembly`
to 
`typeof(Resource1).GetTypeInfo().Assembly`

Any further change in the resx file reverts these changes causing the build to fail again.

**Comment by livarcocc** [comment]
@srivatsn This seems to be an issue in VS when the designer.cs file gets generated.

**Comment by srivatsn** [comment]
Yes this is https://github.com/dotnet/roslyn-project-system/issues/747

**Comment by livarcocc** [comment]
ok. Closing this one in favor the roslyn one then.
