### ISSUE TITLE
New csproj, fsproj, vbproj schemas and NuGet package information embedding

### ISSUE THREAD

**Issue by xperiandri** [dotnet/cli#5150]
Where can I find a schema documentation of csproj, fsproj.
In particular NuGet info attachment is the most interesting.
I tried to port some library and I want to create a package using `dotnet pack` but I can't find any info about how to add NuGet related info into project file.

**Comment by svick** [comment]
In general, I think this is not really documented yet, since the schema of the new csproj is still changing.

Specifically, `dotnet pack` delegates to an msbuild target created by NuGet, which is [documented here](https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target).

**Comment by blackdwarf** [comment]
@xperiandri please reopen this issue on dotnet/docs repo as this is a documentation issue that we need to fix. I will close this one. Thanks!
