### ISSUE TITLE
Getting local dependencies to add the correct version when `dotnet pack`ing

### ISSUE THREAD

**Issue by avanderhoorn** [dotnet/cli#5151]
## Steps to reproduce

Executed command
```
dotnet pack .\src\Glimpse.Common\Glimpse.Common.csproj --configuration Release --version-suffix beta2-123
dotnet pack .\src\Glimpse.Server\Glimpse.Server.csproj --configuration Release --version-suffix beta2-123
```
Target Glimpse.Common.csproj
```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <AssemblyTitle>Glimpse Common</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFrameworks>net451;netstandard1.6</TargetFrameworks>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Glimpse.Common</AssemblyName>
  </PropertyGroup>
...
```
Target Glimpse.Server.csproj
```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <AssemblyTitle>Glimpse Server</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFrameworks>net451;netstandard1.6</TargetFrameworks>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Glimpse.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Glimpse.Common\Glimpse.Common.csproj" />
  </ItemGroup>
...
```
Resulting Glimpse.Server.nuspec
```
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Glimpse Server</id>
    <version>2.0.0-beta2-123</version>
    ...
    ...
    <dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="Glimpse.Common" version="1.0.0" exclude="Build,Analyzers" />
        ...
      </group>
...
```

## Expected  behavior
I want the version of the `Glimpse.Common` dependency in above `Glimpse.Server.nuspec` to be `2.0.0-beta2-123` vs instead `1.0.0`. 

Previously with `project.json` this was all taken care of with the with the following [`pack.cmd`](https://github.com/Glimpse/Glimpse.Prototype/blob/43e6ef021473596143883501c47c94cfff77e688/pack.cmd) and by specifying dependencies like [this](https://github.com/Glimpse/Glimpse.Prototype/blob/43e6ef021473596143883501c47c94cfff77e688/src/Glimpse.Server/project.json#L10). But I can't figure out how to replicate these results with the new .csproj setup. Here is my reworked [`pack.cmd`](https://github.com/Glimpse/Glimpse.Prototype/blob/dev/pack.cmd).  

## Actual behavior
Shown above in the resulting Glimpse.Server.nuspec.

## Environment data
```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by livarcocc** [comment]
@joelverhagen @rohit21agrawal

**Comment by rohit21agrawal** [comment]
I am wondering if version metadata needs to be supported on ProjectReference item as well if we want to enable this scenario. Thoughts?

Cc : @rrelyea

**Comment by avanderhoorn** [comment]
I personally thing there needs to be away to support this... otherwise it make doing anything where solution that has multiple projects where those projects are nuget packages very hard to work with as the versions that will automatically be inserted be 1.0.0 which is invariably the wrong default.

**Comment by avanderhoorn** [comment]
Any update on this?

**Comment by rrelyea** [comment]
If this is a nuget issue, let's port it over to http://github.com/nuget/home/issues please.
