### ISSUE TITLE
Unintuitive and inconsistent error when running dotnet with an unsupported verb

### ISSUE THREAD

**Issue by jpierson** [dotnet/cli#5153]
## Steps to reproduce

From PowerShell with dotnet cli installed:

1. `mkdir x-deleteme`
2. `cd x-deleteme`
3. `dotnet badverb`
4. `dotnet new`
5. `dotnet badverb`

## Expected  behavior
In step 3 and 5 I would expect an error along the lines of "no built in verb or extension with a verb of 'badverb' could be found".

## Actual behavior

After step 3:

```
PS x-deleteme> dotnet badverb
No executable found matching command "dotnet-badverb"
```

After step 5:

```
PS x-deleteme> dotnet badverb
Could not find a part of the path 'C:\Users\me\source\x-deleteme\obj\project.assets.json'.
```

## Environment data
`dotnet --info` output:

```
PS x-deleteme> dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by livarcocc** [comment]
Thanks for the issue. We have fixed this already in latest.
