### ISSUE TITLE
README still references project.json samples

### ISSUE THREAD

**Issue by jpierson** [dotnet/cli#5154]
The section on [Basic Usage](https://github.com/dotnet/cli/blob/rel/1.0.0/README.md#basic-usage) in README.md within the `rel\1.0.0 branch` still refer to .NET Core samples that use project.json files. As my understanding is that project.json files are sto be deprecated and are not supported by latest builds of the cli this readme should either be changed to note that the suggested basic usage section is only valid for older builds or point to more updated samples that work with the newer .csproj file format.

**Comment by blackdwarf** [comment]
The samples now contain the csproj files as well so they can work on both. Closing.
