### ISSUE TITLE
dotnet restore not restoring packages correctly

### ISSUE THREAD

**Issue by Baklap4** [dotnet/cli#5155]
## Steps to reproduce
* Create default project with: `dotnet new`
* Add the following `project.config`
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "MySql.Data.EntityFrameworkCore": "7.0.6-IR31"
  },
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

## Expected  behavior
The package `MySql.Data.EntityFrameworkCore` would contain version: `7.0.6-IR31`
Version in Nuspec file within the directory: `7.0.6-IR31`

## Actual behavior
The package `MySql.Data.EntityFrameworkCore` contains version: `7.0.6-ir31`
Version in NuSpec file within the directory: `7.0.6-IR31`.

Note the Captital letters in Expected behavior and the noncapital letters in the actual behavior.
This way references to this package will fail with a `ReferenceNotFoundException`.

On Windows using the same environment it'll find the reference as Windows is not Caste sensitive.
On Windows however it saves to the correct Path: `packages\MySql.Data.EntityFrameworkCore\7.0.6-IR31\`

## Environment data
`dotnet --info` output:

```
~/TestProject$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)
 
Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576
 
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

**Comment by piotrpMSFT** [comment]
This issue should be moved to https://github.com/nuget/home
