### ISSUE TITLE
Implement dotnet cache shim

### ISSUE THREAD

**Issue by ramarag** [dotnet/cli#5161]
Implement the shim with the following shape

dotnet cache --entries packages.proj--tfm netcoreapp2.0 [--output C:\Foo] --rid win7-x64 --fx-version 2.0.0-preview2-00001 [--no-optimize]

--tfm          Specifies the TFM that the package store is applicable to
--output       The output directory to create the package store in (default: %USERPROFILE%\.dotnet or ~/.dotnet)

--no-optimize  Do not perform crossgen of the assemblies after "restore" (optimize is the default)

--rid          The runtime identifier of the target platform where these assemblies will be run
--fx-version   The Microsoft.NETCore.App package version that will be used to run the assemblies

**Comment by krwq** [comment]
what kind of cache this is about? I'm seeing a lot of info about caching here and in other issue but no actual info on what is being cached. It feels like there is noun missing after `dotnet cache`.

**Comment by ramarag** [comment]
See https://github.com/dotnet/core-proposals/pull/33 for more info

**Comment by krwq** [comment]
Thanks @ramarag!

**Comment by dasMulli** [comment]
Since the `core-proposals` repo is private, can one of you share the purpose of this user-facing command?

**Comment by krwq** [comment]
@dasMulli, I haven't read the whole doc but the idea looks like a hybrid of GAC and nuget cache with more options to control it, @ramarag, can we share the doc in cli repo?

**Comment by ramarag** [comment]
The design docs is present here https://github.com/dotnet/core-setup/pull/1281
