### ISSUE TITLE
.dll files in the .NET Core tarball for Linux have incorrect permissions

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/cli#5166]
## Steps to reproduce
Download the latest .NET Core tarball for Linux.
Unpackage the tarball.
The various `.dll` files in the tarball have permission `600`, making the files accessible for the owner, but not any other user.

## Expected  behavior
The files to be readable by any user in the system (I'm guessing that would be `666`)

## Actual behavior
The files have permission level `600`

**Comment by vcsjones** [comment]
This issue probably belongs in https://github.com/dotnet/core-setup. It looks like the packaging is done here: https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/tools/dotnet-deb-tool/tool/package_tool#L166

**Comment by qmfrederik** [comment]
Makes sense, thanks!
