### ISSUE TITLE
dotnet run -p no longer works when passing in folder path

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#5168]
## Steps to reproduce
1. Create a new project (`dotnet new`) and restore it.
2. Run `dotnet run -p <directory where csproj exists>`

## Expected  behavior
Project gets run

## Actual behavior
```
dotnet run -p d:\temp\dotnet-run
MSBUILD : error MSB1009: Project file does not exist.
Switch: d:\temp\dotnet-run

The build failed. Please fix the build errors and run again.
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

It would be nice if the behavior was consistent with `dotnet build` and run a project if it's the only one in the specified directory.

**Comment by FelschR** [comment]
I also noticed this. It's a little annoying.

**Comment by dasMulli** [comment]
I guess this has been fixed by https://github.com/dotnet/cli/pull/6120
