### ISSUE TITLE
dotnet run fails for projects with satellite assemblies when targeting Microsoft.NETCore.App 1.2.0

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#5172]
## Steps to reproduce
1. Create a new project targeting `Microsoft.NETCore.App v  1.1.0`.
2. Add a localized resx file (`Test.fr-FR.resx`)
3. Restore and run it. The app will run fine.
4. Ensure the shared runtime `1.2.0-beta-001202-00` is installed and update the application to target this version of `Microsoft.NETCore.App`
5. Restore and build

## Expected  behavior
The project continues to run

## Actual behavior
`Error: assembly specified in the dependencies manifest was not found -- package: 'test2', version: '1.0.0', path: 'fr-FR/test2.resources.dll'`

## Environment data
`dotnet --info` output:

I'm able to reproduce this with both project.json based project and MSBuild based project:
```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

```
.NET Command Line Tools (1.0.0-preview2-1-003180)

Product Information:
 Version:            1.0.0-preview2-1-003180
 Commit SHA-1 hash:  5fbbb40658

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by livarcocc** [comment]
@srivatsn @nguerrera @dsplaisted I remember seeing something related to this in the SDK repo already.

**Comment by Eilon** [comment]
@livarcocc this issue is blocking ASP.NET Core's Localization tests, do you know who can take a look at this?

**Comment by nguerrera** [comment]
Is the file fr-FR/*.resources.dll on disk? If so, guessing but there was an issue (now fixed) in the SDK where it did not match main assembly signature on satellites. CoreCLR (unlike desktop) was allowing the load to succeed which hid the bug. Perhaps this was changed to match desktop in 1.2? If I've guessed right, latest preview 5 of CLI with up to date SDK should resolve it.

**Comment by pranavkm** [comment]
I'll give the preview5 CLI and report back.

**Comment by pranavkm** [comment]
@nguerrera doesn't look like it's fixed as yet. I do not have any sort of strong name signing enabled in my project.

* The CLI I tried this with:
```
dotnet --info
.NET Command Line Tools (1.0.0-preview5-004384)

Product Information:
 Version:            1.0.0-preview5-004384
 Commit SHA-1 hash:  05b448944c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

* The csproj I have
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.2.0-*" />
  </ItemGroup>
</Project>
```

* The output structure:
```
\resx-test\bin\Debug\netcoreapp1.1 > tree /f
│   Microsoft.DiaSymReader.Native.amd64.dll
│   Microsoft.DiaSymReader.Native.x86.dll
│   resx-test.deps.json
│   resx-test.dll
│   resx-test.pdb
│   resx-test.runtimeconfig.dev.json
│   resx-test.runtimeconfig.json
│
└───fr-FR
        resx-test.resources.dll
```

**Comment by pranavkm** [comment]
Also, we've bumped up to shared runtime version `1.2.0-beta-001269-00`.

**Comment by piotrpMSFT** [comment]
@nguerrera it looks like this issue belongs in the SDK repo, but I don't want to lose the conversation history. Can you help get ASP.NET unblocked?

**Comment by pranavkm** [comment]
Tried this out with `1.0.0-preview5-004468` and now strong name signing fails:

```
\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview5-004468\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(213,5): error : Errors occured when emitting satellite assembly '\Localization\samples\LocalizationSample\obj\Debug\netcoreapp1.1\ja-JP\LocalizationSample.resources.dll'. [\Localization\samples\LocalizationSample\LocalizationSample.csproj]
\AppData\Local\Microsoft\dotnet\sdk\1.0.0-preview5-004468\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(213,5): error : error CS7027: Error signing output with public key from file '\Localization\build\Key.snk' -- Assembly signing not supported. [\Localization\samples\LocalizationSample\LocalizationSample.csproj]
```

Looking at https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/GenerateSatelliteAssemblies.cs, it looks like you might be missing some additional setup required for strong name signing to work: https://github.com/aspnet/MvcPrecompilation/blob/rel/1.1.0-msbuild3/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Internal/ViewInfoContainerCodeGenerator.cs#L65-L77.

**Comment by srivatsn** [comment]
This issue was moved to dotnet/sdk#673
