### ISSUE TITLE
dotnet restore cmd failing - error MSB4019 - \DotNet\Microsoft.DotNet.Props file missing

### ISSUE THREAD

**Issue by dnbr2002** [dotnet/cli#5175]
So I've done some searching most articles suggest installing the Vs2015 tooling.  Which I have installed.  But I am still getting this error when I try to restore a project from Yeomans.  The 'Microsoft.DotNet.Props' file definitely does not exist on my machine. Im running Windows 7 x64 with Vs2015update3 and Vs2015 tools preview 2.0.3.  What am I doing wrong?

**Comment by dnbr2002** [comment]
Not sure if this helps but here is my dotnet --info


Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by MoxxNull** [comment]
I had the same error, i could solve it by creating a new solution and adding my existing project again. In this process they got updated, and the error went away.

**Comment by dnbr2002** [comment]
Are you saying creating a new solution file in the Visual Studio IDE then add the existing project to that solution?

**Comment by MoxxNull** [comment]
Yeah sorry, i meant: Create a new - empty - solution and add the projects one by one., That did it for me!

**Comment by dnbr2002** [comment]
So here's what I did.  It's all posted here (I asked for help in the ASP dotnet forum as well).  Im puerto.   

https://forums.asp.net/t/2113044.aspx?dotnet+restore+failing+error+MSB4019+1+0+0+preview4+004233+Microsoft+VisualStudio+v14+0+DotNet+Microsoft+DotNet+Props+was+not+found+

Essentially I had to switch the dotnet version to the original version the yeomans templae was built with .  I had to update the Global.json to force that.  I then opened the solution in Visual Studio which ran a sucessful build.
