### ISSUE TITLE
dotnet restore does not support "-r"

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#518]
dotnet publish supports "-r" as shortcut for "--runtime" but dotnet restore does not but should.

**Comment by brthor** [comment]
Dotnet restore is just a wrapper for dnu and eventually nuget. 

Changes to include -r would need to happen there. Should this be filed there?

**Comment by gkhanna79** [comment]
This issue is to track mismatch in the current experience. We spent sometime figuring this out in order to address a build break in CoreRT due to issues with restoration of packages on OSX 10.11.

Are you suggesting the actual bug is in DNU/Nuget? If so, feel free to forward the bug ahead.

**Comment by brthor** [comment]
@piotrpMSFT @blackdwarf 

This doesn't seem so much a bug as an inconsistency in our argument design.
I see three options:

1. Remove -r as a shortcut for runtime in publish and wherever else it may exist.
2. Build -r into our `dotnet restore` script which wraps dnx. It would transform this option into `--runtime` This will probably be pretty ugly.
3. Drive adding -r to dnx/nuget

I think 1 is the best way to go if Nuget has no plans for this. We don't gain much from having `-r` and the consistency will cause less headache.

Thoughts??

**Comment by gkhanna79** [comment]
Having shortcuts is a semantic that is commonly used in Unix world (take a look at lldb tutorial as an example or the GIT infrastructure). If the long term plan is to use Nuget, we should get this fixed in there and adopt the corresponding build soon.

**Comment by brthor** [comment]
Agreed that shortcuts are common, but it seems the lack of shortcuts is as well. I'm not sure which is right, or what the convention is but just pointing out that both are viable.

Git as an example.
```bash
azureuser@work:~/bashtest$ git -h
Unknown option: -h
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

**Comment by blackdwarf** [comment]
+1 to what @gkhanna79 said. I like having shortcuts, since it makes some things easier for those troublesome typing. Also, I think GNU says it is good to have shortcuts, no? GNU guidelines that is.

**Comment by brthor** [comment]
If shortcuts are the popular opinon by all means let's bring this over to nuget. Personally, I like them as well, removing them seemed like the easiest option to gain consistency.

P.S. @blackdwarf Where can I find GNU guidelines?

**Comment by piotrpMSFT** [comment]
I have a PR coming with new dotnet restore. I'll add this there.

**Comment by piotrpMSFT** [comment]
This is a nuget/home issue, and it is something they have said is not in scope for NuGet.
