### ISSUE TITLE
Dotnet restore fails

### ISSUE THREAD

**Issue by pcgeek86** [dotnet/cli#5182]
## Steps to reproduce

1. Create a new .NET Core MVC project in Visual Studio 2015
2. Add a NuGet package that isn't supported by .NET Core
3. Remove the NuGet package that isn't supported by .NET Core from Step 2
4. Try to build the project

## Expected  behavior

Solution builds successfully.

## Actual behavior

```
Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:

1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.

```

## Environment data
`dotnet --info` output:

```
PS C:\Windows\system32> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

How do I fix this? It's blocking me right now.

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by fir3pho3nixx** [comment]
Have you tried physically editing the project.json dependencies? Sometimes the NuGet tooling in VS is clunky and does stupid things. 

Also noticed you are running an ever so slightly older build, does upgrading to 1.0.0-preview2-1-003177 help?

I was cruising, until I started porting my project to linux and dotnet restore just completely cranked out on windows. #5186 

Feel your pain!

**Comment by pcgeek86** [comment]
Hey thanks for the advice, @fir3pho3nixx. I did end up finding another thread that mentioned to modify the `project.json`, although I still have no clue how I would have known to do that. I also have no idea how I even got into the state that I did ... that shouldn't be possible, in theory.

**Comment by piotrpMSFT** [comment]
@pcgeek86 thanks for reporting and I'm glad it got resolved. `project.json` had a bunch of quirks like this, but our incrementality mechanisms became much more complete with the transition to msbuild so I expect we won't see this moving forward.
