### ISSUE TITLE
x64 SDK with IISExpress and assembly x86

### ISSUE THREAD

**Issue by kimbell** [dotnet/cli#5185]
I was looking for a slightly more advanced app than 'dotnet new', so I found the MusicStore sample application created by the ASP.NET team. 

After migrating to csproj and doing various other updates, I finally got it to work, but it would have been helpful if the system could give me a few more hints along the way.  

After doing all the csproj changes, launching IISEpress did absolutely nothing. There was an entry in the event log that hinted to what was going wrong.

Failed to start process with commandline '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe" 
-debug -p "C:\Program Files\dotnet\dotnet.exe" -a "exec \"C:\Source\Repos\MusicStore\samples\MusicStore\bin\x86\Debug\netcoreapp1.1\MusicStore.dll\"" 
-pidFile "C:\Users\christopher.kimbell\AppData\Local\Temp\tmpA9A0.tmp" -wd "C:\Source\Repos\MusicStore\samples\MusicStore"', ErrorCode = '0x80004005'.

dotnet.exe is being run from the x64 version of program files
My assembly is x86. 

When I changed my assembly to x64, everything worked, so I'm guessing it was due to platform mismatch. 

When I installed the sdk and runtime last year, I thought "I'm running on an x64 machine, lets choose the x64 version". By default, visual studio uses x86 for projects. 

It would be nice with a specific warning in the logs when dotnet.exe tries to launch an incorrect platform version. Another option would be to combine the x86 and x64 sdk and runtime into one.

**Comment by kimbell** [comment]
I've now installed the x86 versions of the runtime and sdk. After some more fiddling, I got IISExpress to launch correctly, but there is something very weird going on. 

Every second time I launch, it doesn't work. I haven't made any changes to the code or configuration between each run. I just stop debugging, and start IISExpress again. This has been consistent for the last 10-15 attempts. 

The code I'm running can be found here [https://github.com/kimbell/MusicStore](https://github.com/kimbell/MusicStore) It's a fork of the ASP.NET repository.

**Comment by kimbell** [comment]
I started by installing the latest x86 SDK preview

```
C:\windows\system32>dotnet --version
1.0.0-preview5-004384
```
This doesn't seem to make any difference. 
I then noticed that my csproj contained the following

```
<PropertyGroup Label="Configuration">
    <PlatformTarget />
  </PropertyGroup>
```

If I removed that, it would not start at all. 
Also tried installing x64 SDK in case it defaults to machine platform; no change. Did not start at all.

I then added the PlatformTarget that I had removed, and now we are back to 50% success rate.

**Comment by piotrpMSFT** [comment]
We should ensure that MusicStore migrates successfuly.

**Comment by livarcocc** [comment]
We had a separate issue for the music store migration: https://github.com/dotnet/cli/issues/4688. We have been successful in migrating and running it.

Closing this one. If it turns out that this is still a problem with the latest CLI, please re-activate.

**Comment by hazemusa** [comment]
I am a bit new to this so I appreciate some help!

In the current 2017 RC1, I am getting the following:
  
Error		RuntimeIdentifier must be set for .NETFramework executables. 
Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64.	MusicStore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets	64	

Here is my .targets file:

<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  
  
  <Choose>
    <When Condition="'$(PlatformTarget)' != '' or '$(RuntimeIdentifier)' == ''" />

    <When Condition="$(RuntimeIdentifier.EndsWith('-x86')) or $(RuntimeIdentifier.Contains('-x86-'))">
      <PropertyGroup>
        <PlatformTarget>x86</PlatformTarget>
      </PropertyGroup>
    </When>

    <When Condition="$(RuntimeIdentifier.EndsWith('-x64')) or $(RuntimeIdentifier.Contains('-x64-'))">
      <PropertyGroup>
        <PlatformTarget>x64</PlatformTarget>
      </PropertyGroup>
    </When>

    <When Condition="$(RuntimeIdentifier.EndsWith('-arm')) or $(RuntimeIdentifier.Contains('-arm-'))">
      <PropertyGroup>
        <PlatformTarget>arm</PlatformTarget>
      </PropertyGroup>
    </When>

    
    <Otherwise>
      <PropertyGroup>
        <PlatformTarget>AnyCPU</PlatformTarget>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <PropertyGroup>
    
    
    <AppendRuntimeIdentifierToOutputPath Condition="'$(AppendRuntimeIdentifierToOutputPath)' == ''">false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  
  <PropertyGroup Condition="'$(AppendRuntimeIdentifierToOutputPath)' == 'true' and '$(RuntimeIdentifier)' != ''">
    <IntermediateOutputPath>$(IntermediateOutputPath)$(RuntimeIdentifier)\</IntermediateOutputPath>
    <OutputPath>$(OutputPath)$(RuntimeIdentifier)\</OutputPath>
  </PropertyGroup>

  <Target Name="_CheckRuntimeIdentifier" BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
    <NetSdkError Condition="'$(RuntimeIdentifier)' == '' and '$(TargetFrameworkIdentifier)' == '.NETFramework' and '$(OutputType)' == 'Exe'"
                 ResourceName="RuntimeIdentifierMustBeSetForNETFramework" />
  </Target>

</Project>
