### ISSUE TITLE
The output of dotnet pack and publish is confusing

### ISSUE THREAD

**Issue by svick** [dotnet/cli#5187]
## Steps to reproduce

1. `dotnet new -t lib`
2. `dotnet restore`
3. `dotnet pack`

## Expected  behavior

The output of `dotnet pack` clearly shows that it generated the desired `.nupkg` file, ideally with a path.

## Actual behavior

The output shows that a `.dll` file was generated (which is a side-effect of running `pack`, so not that important here), but it does not mention the `.nupkg` file (which is the point of running `pack`):

```
C:\code\tmp\corelib>dotnet pack
Microsoft (R) Build Engine version 15.1.458.808
Copyright (C) Microsoft Corporation. All rights reserved.

  corelib -> C:\code\tmp\corelib\bin\Debug\netstandard1.4\corelib.dll
```

`dotnet publish` also has this issue: its output shows the `.dll` file from `dotnet build`, but not the one in the `publish` directory from `dotnet publish`:

```
C:\code\tmp\coreapp>dotnet publish
Microsoft (R) Build Engine version 15.1.458.808
Copyright (C) Microsoft Corporation. All rights reserved.

  coreapp -> C:\code\tmp\coreapp\bin\Debug\netcoreapp1.0\coreapp.dll
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275
```

**Comment by GuardRex** [comment]
Dup of https://github.com/dotnet/sdk/issues/407 and https://github.com/dotnet/sdk/issues/389

**Comment by livarcocc** [comment]
Given that we have issues tracking these issues already, closing this one.
