### ISSUE TITLE
Installing Preview4/5 SDK on box with existing older 1.0 shared framework leads to dotnet.exe not working

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#5194]
1) uninstalled everything .net core in add remove programs (various previews, 1.0 etc)
2) https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-win-x64.latest.exe 
3) https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe 
4) run <C:\Program Files\dotnet\dotnet.exe> 

```
C:\play>dotnet --info
The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
  - Check application dependencies and target a framework version installed at:
      <C:\Program Files\dotnet\shared\Microsoft.NETCore.App>
  - The following versions are installed:
      1.2.0-beta-001137-00
  - Alternatively, install the framework version '1.0.1'.
```

To fix this I had to install the .NET Core 1.0.3 SDK manually. I'm guessing it should have done that for me.

**Comment by danmosemsft** [comment]
I'm told @eerhardt may be working on this already

**Comment by piotrpMSFT** [comment]
@danmosemsft this is interesting. The installer certainly does bring down the Shared Framework that it requires. Do you have installation logs by chance? @eerhardt will be bumping CLI to shared framework 1.0.3, but your install should have brought ~some~ shared framework with it. I don't know of a CLI installer that brings 1.2.0-beta-...

**Comment by danmosemsft** [comment]
I can uninstall and repeat -- where would I find the logs?

**Comment by eerhardt** [comment]
Can you also try installing them in the reverse order?  First install the installer from step 3 above and then step 2.

**Comment by danmosemsft** [comment]
@eerhardt if I uninstll everything, then just install the SDK (step 3) then it works.

```
C:\WINDOWS\system32>dotnet --info
.NET Command Line Tools (1.0.0-preview5-004445)
```

Updated title.

**Comment by piotrpMSFT** [comment]
Based on the symptoms and @eerhardt's insight, this appears likely to be a Shared Framework issue that happens to repro in CLI since CLI is an app that uses the Shared Framework. It would likely best be investigated by the core-setup folks. However, I've not had time to look into specifics so leaving this open for later investigation...
