### ISSUE TITLE
Compiler extensibility

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#52]
We should add an additional `--compiler` argument to `dotnet compile`. `dotnet compile --compiler {compiler}`. In absence of any compiler we'll use `csc` or sniff some sensible default. It can also be specified in the `project.json` file

```JSON
{
    "version": "1.0.0-*",
    "compileFiles": [
       "Something.fs",
       "Program.fs"
     ],
    "compilationOptions": {
        "emitEntryPoint": true,
        "compiler": "fsc"
    },
    "dependencies": {
        "Microsoft.NETCore.ConsoleHost": "1.0.0-*",
        "Microsoft.NETCore.Runtime": "1.0.1-*",

        "System.Console": "4.0.0-*",
    },
    "frameworks": {
        "dnxcore50": { }
    }
}
```

The above project would be an f# project and we would execute the equivalent of  `dotnet compile --framework dnxcore50 --compiler fsc`. The command line would override whatever was in the file.

/cc @jaredpar @anurse

**Comment by blackdwarf** [comment]
This is probably done. Opportunistic close. Reopen if needed. Fixed by #102.
