### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer

### ISSUE THREAD

**Issue by jchannon** [dotnet/cli#5201]
## Steps to reproduce
Publish a self contained dotnetcore app

`dotnet "publish" "C:\myapp" --configuration Release --framework netcoreapp1.0 --runtime win10-x64 --output C:\output`

Copy the results to a clean Windows 2012 server

Run the exe produced from the publish command

## Expected  behavior
The application to start

## Actual behavior
An error `api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer`
<img width="485" alt="screen shot 2017-01-04 at 11 36 00" src="https://cloud.githubusercontent.com/assets/105126/21641874/8a7b98f8-d276-11e6-95c2-24baf709f65c.png">

## Environment data
`dotnet --info` output: N/A

**Comment by jchannon** [comment]
Going to try Windows Update to see if it fixes it.

Lets Do This!!
<img width="632" alt="screen shot 2017-01-04 at 12 23 28" src="https://cloud.githubusercontent.com/assets/105126/21642235/c7ecb0a8-d278-11e6-9c87-8c0ff10acc42.png">

**Comment by piotrpMSFT** [comment]
@jchannon any luck? Can you also share your `dotnet --version` output? I'm curious what build you're using as these issues haven't been seen since preview2 or so...

**Comment by jchannon** [comment]
All working after running windows update and installing Visual C++ Redistributable.

Linked PRs to update the docs merged for future people
