### ISSUE TITLE
Cannot find ConfigurationRegistrar

### ISSUE THREAD

**Issue by stuartbloom** [dotnet/cli#5202]
I would like to make use of MEF to build up my model configurations as per this site (http://odetocode.com/blogs/scott/archive/2011/11/28/composing-entity-framework-fluent-configurations.aspx), unless there is a better way to separate the entity configurations.

I am therefore trying to create an interface that uses the `ConfigurationRegistrar` class, but I cannot seem to figure out what to add to my project.json file (attached) in order to get access to this.

Any assistance would be most appreciated :)

Thanks

Stuart
[project.json.txt](https://github.com/dotnet/cli/files/685002/project.json.txt)

**Comment by piotrpMSFT** [comment]
@stuartbloom I believe MEF is maintained in https://github.com/dotnet/corefx. This repo doesn't typically have any MEF experts looking over issues.
