### ISSUE TITLE
Re-enable solution building tests

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5205]
The solution building portion of these tests have been disabled
1. WhenValidProjectIsPassedTheSlnBuilds
2. MigrateAndBuild

Tracking an issue on the sdk
https://github.com/dotnet/sdk/issues/545

**Comment by livarcocc** [comment]
@jgoshi Can you follow up with the SDK folks on why this is still failing for us? It seems like @eerhardt was the author of the fix, maybe reach out to him?

**Comment by eerhardt** [comment]
I didn't fix it, I just opened the issue.  @rainersigwald fixed it.
