### ISSUE TITLE
DotnetCLI commands not following same behavior as Application

### ISSUE THREAD

**Issue by shairozan** [dotnet/cli#5207]
## Steps to reproduce
Whenever we try to run a migration, it fails, complaining about the secrets.json file not being in the right location. Our DBContext has an onconfiguring override that allows us to select the connection string dynamically based on the environment variables in order to make Docker deployments more fluid. 

The biggest issue is that since the 1.1 upgrade, dotnet ef database update has been failing complaining about how secrets.json is not in the bin\Debug\netcoreapp1.1\ directory. 

## Expected  behavior
1. Override DBContext to select environment based connection string from secrets.json
2. Run the application this way
3. Perform EF database updates for migrations
4. Update database

## Actual behavior
The application will run fine, but attempting to perform entity operations like running migrations complains about the secrets.json file not being in the netcore1.1 debug directory

## Environment data
$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
Can you please move this issue here: https://github.com/aspnet/EntityFramework?

**Comment by shairozan** [comment]
This issue was moved to aspnet/EntityFramework#7356

**Comment by shairozan** [comment]
Moved and closing here. Thanks for the redirect.
