### ISSUE TITLE
"dotnet publish {ProjectDirectory}" no longer works

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#5211]
## Steps to reproduce
1. Create a new project
2. Restore and run `dotnet publish <directory with proj file>`

## Expected  behavior
Publish succeeds

## Actual behavior
Publish fails with

```
MSBUILD : error MSB1009: Project file does not exist.
Switch: D:\temp\msbuild-test\src2
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview5-004384)

Product Information:
 Version:            1.0.0-preview5-004384
 Commit SHA-1 hash:  05b448944c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by piotrpMSFT** [comment]
That's right. MSBuild accepts input of project by either path to *.*proj or by the working directory. Since the SDK can be executed by CLI, VS, MSBuild.exe, etc. we did not want to bifurcate the user experience by providing a different convention on CLI. We may revisit this post-1.0.
