### ISSUE TITLE
Create simple web api project via dotnet new -t parameter

### ISSUE THREAD

**Issue by tmkn** [dotnet/cli#5213]
I just found out about the seemingly hidden `dotnet new -t web` command to quickly setup a new web project.
Hidden because the official tutorials make no reference to it, instead they have you install yeoman and scaffold the project with `yo aspnet` which appears to actually be the same?

As I'm new to .net core and asp.net I would appreciate a dedicated command that scaffolds a simple web api project.

**Comment by blackdwarf** [comment]
@tmkn this exists already in the latest using the command `dotnet new3`. Please try it out.

**Comment by piotrpMSFT** [comment]
@blackdwarf @mlorbetske what is the right cmd line to execute?

**Comment by spboyer** [comment]
@piotrpMSFT `dotnet new3 webapi`

**Comment by livarcocc** [comment]
Closing this issue as it does not seem like there is anything else we need to do here.
