### ISSUE TITLE
dotnet --help should be more helpful when trying to run a published app

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5216]
This is tracking this comment here: https://github.com/dotnet/core/issues/77#issuecomment-222375863

**Comment by livarcocc** [comment]
We have added documentation in the CLI docs for this. You can see @mairaw's PR if you follow her comments from the link above.

However, I think we should also add the info that you can do dotnet <your_published_app_dll> to the  output of dotnet --help itself.

cc @richlander

**Comment by livarcocc** [comment]
This information has now been added to dotnet --help.
