### ISSUE TITLE
Running dotnet migrate on second solution fails - Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5224]
## Steps to reproduce
Using VS 2017 RC.3 (d15prerel.26105.02 with CLI 1.0.0-preview5-004382)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1
dotnet migrate -- works. Backup folder is created one-level above the solution folder
    
![image](https://cloud.githubusercontent.com/assets/8246794/21701729/4bb26e4e-d35c-11e6-8c9f-610cc3516669.png)

![image](https://cloud.githubusercontent.com/assets/8246794/21701806/c4572fc4-d35c-11e6-8358-5c92a205a9ce.png)

cd Dev14_K101/Tooling202/AspNetCoreWeb_OnNet452_Empty_1
dotnet migrate

## Actual behavior
Migration failed

![image](https://cloud.githubusercontent.com/assets/8246794/21701753/6405c7c0-d35c-11e6-843d-4416fdba6396.png)

## Expected  behavior
Migration of the second solution to succeed

**Comment by balachir** [comment]
This seems to be happening because when I ran the first dotnet migrate, the backup folder got created as a peer to the solution folder rather than inside the solution folder. If I rename or delete this backup folder, then the second dotnet migrate went through fine.

**Comment by piotrpMSFT** [comment]
Why do we need two migrates in this scenario?

**Comment by balachir** [comment]
You don't need a second migrate actually. I mentioned that in the repro mainly to illustrate the severity of the issue.

**Comment by 333fred** [comment]
I can also reproduce this issue with a different repo: https://github.com/robotdotnet/NativeLibraryUtilities. A single run of `dotnet migrate` produces the following output:
```
> dotnet migrate NativeLibraryUtilities.sln
Project NativeLibraryUtilities migration succeeded (C:\Users\frsilb\Documents\git\NativeLibraryUtilities\src\NativeLibraryUtilities)
Summary
Total Projects: 1
Succeeded Projects: 1
Failed Projects: 0

Cannot create a file when that file already exists
Migration failed.
```

Tested with 1.0.0-preview5-004468.

**Comment by DustinCampbell** [comment]
It looks like the problem here is the global.json. This always gets placed in the root of the backup folder. So, if the user migrates another project at the same level in the directory tree, the global.json's collide.
