### ISSUE TITLE
remove newtonsoft.json dependency from TestAssets/DesktopTestProjects/AutoAddDesktopReferencesDuringMigrate/project.json

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/cli#5236]
the test  ItAutoAddDesktopReferencesDuringMigrate  creates a migrated project without any package references and as a result dotnet restore does not generate any assets file.
When the test tries to build the project, it fails because it cannot find an assets file

As part of unblocking https://github.com/dotnet/cli/pull/5214 , a dependency was added to TestAssets/DesktopTestProjects/AutoAddDesktopReferencesDuringMigrate/project.json to get the tests working.

This dependency should be removed when the associated SDK bug https://github.com/dotnet/sdk/issues/537 is fixed

CC: @livarcocc

**Comment by piotrpMSFT** [comment]
Looks to me like dotnet/sdk#537 is closed. We should be able to resolve this now.

**Comment by livarcocc** [comment]
We can't. That's exactly what we are hitting and preventing us from taking a new NuGet right now. We need to fix the MSBuildSDKsPath problem during our build in order to do this.
