### ISSUE TITLE
dotnet publish build fails on expression-bodied property accessors

### ISSUE THREAD

**Issue by Kinematics** [dotnet/cli#5240]
## Steps to reproduce

Create new .NET Core console app in VS 2017.

Add the following to the Program class:

    string myVar1 = "";

    public string MyVar1
    {
        get => myVar1;
        set { myVar1 = value; }
    }

Verify build in VS2017.

Run `dotnet publish` in the project directory.

## Expected  behavior

Expect build to occur normally.

## Actual behavior

Build fails with the following errors:

Program.cs(14,13): error CS1043: { or ; expected [C:\Users\David\documents\Visual Studio 2017\projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj]
Program.cs(14,13): error CS1513: } expected [C:\Users\David\documents\Visual Studio 2017\projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj]
Program.cs(15,13): error CS1002: ; expected [C:\Users\David\documents\Visual Studio 2017\projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj]
Program.cs(17,2): error CS1513: } expected [C:\Users\David\documents\Visual Studio 2017\projects\ConsoleApp2\ConsoleApp2\ConsoleApp2.csproj]

If the accessor is changed to:

    get { return myVar1; }

Then the publish build works normally.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by livarcocc** [comment]
This is actually working on latest. We have updated the version of roslyn there and picked up this feature.

**Comment by fehernyul** [comment]
Sorry but I don't understand the answer. What is the resolution?
I push Ctrl + ., after Enter, and mada the buld will fail.

**Comment by GuardRex** [comment]
He's saying to pull down the latest tooling from https://github.com/dotnet/cli/tree/rel/1.0.0

**Comment by piotrpMSFT** [comment]
@fehernyul I think it was not obvious that you were working in Visual Studio. You will need to wait for the next release of VS2017 to get access to the fix.
