### ISSUE TITLE
`dotnet publish` is outputting a different version of a dependent package than specified in docker build

### ISSUE THREAD

**Issue by Banashek** [dotnet/cli#5245]
## Steps to reproduce
Create a new project via `dotnet new`
Change the `Microsoft.NETCore.App` reference to 1.1.0 from the default 1.0.1
Publish the app
Create a simple dockerfile

```
FROM microsoft/dotnet:1.1-runtime
WORKDIR /app
COPY out .
CMD ["dotnet", "myproj.dll"]
```

Build and run:
docker build -t myproj:0.1 .
docker run -it --rm myproj:0.1

## Expected  behavior
The project should run fine, as it does when running `dotnet myproj.dll` locally

## Actual behavior
The specified framework 'Microsoft.NETCore.App', version '1.0.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.1'.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview5-004460)

Product Information:
 Version:            1.0.0-preview5-004460
 Commit SHA-1 hash:  f2f37729b8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview5-004460

## Notes
I've noticed other odd behavior with this error where it will sometimes happen if I run a project from another directory which previously held a project with a different dependency.

Since the previous sentence is kind of confusing, i'll write it out:

create project A in /foo
project A has dependency `Microsoft.NETCore.App: 1.0.1`
restore packages for project A
delete project A

create project B in /foo/bar
project B has dependency  `Microsoft.NETCore.App: 1.1.0`
restore and run project B 

cd up to /foo
run `dotnet run --project ./bar/out/B.dll`
similar error to above.

As I've been floundering around with this for a bit, I haven't had time to come up with an exact repo outside of the docker situation which happens 100%, but I feel like there's some weird nuget caching joojoo for directories that don't contain an xproj which I don't know about.

**Comment by dasMulli** [comment]
With the new `preview5` versions you should no longer need to reference `Microsoft.NETCore.App` in your `csproj`.
Did you update `<TargetFramework>netcoreapp1.0</TargetFramework>` to `<TargetFramework>netcoreapp1.1</TargetFramework>`?
See https://github.com/dotnet/sdk/pull/450 and https://github.com/dotnet/sdk/issues/596 for reference.

**Comment by livarcocc** [comment]
You can also set the below in your project and keep you reference as is. We are looking at ways to improve this and make it clearer.

```
<DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
```

**Comment by Banashek** [comment]
So it looks like there _might_ be an actual bug here, but I'm not sure.

I looked at the `web.runtimeconfig.json` file and it still had a reference to `1.0.1`.

I blew away the published output folder and republished, and everything works now.

So it looks like that `web.runtimeconfig.json` file didn't get updated after updating the dependency version and building again.

**Comment by Banashek** [comment]
Nevermind, it looks like the deprecated explicit reference does not update the runtime config, but the target node does.

Not sure if the distinction matters since it appears to be implicit from here on forward.

There probably should be some documentation, since changing

```
<PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
```

to 

```
<PackageReference Include="Microsoft.NETCore.App" Version="1.1.0" />
```

and running a new publish **will not** update the runtimeconfig.json file

Thanks for the help!
