### ISSUE TITLE
Incorrect package version at https://www.microsoft.com/net/download/linux

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#5251]
According to https://www.microsoft.com/net/core#linuxubuntu, the latest package for .NET Core 1.1 is `dotnet-dev-1.0.0-preview2.1-003177`.  However, the .NET Core 1.1 package at https://www.microsoft.com/net/download/linux is `dotnet-dev-1.0.0-preview2-003175`.

**Comment by blackdwarf** [comment]
Thanks @mikeharder for catching this.

**Comment by piotrpMSFT** [comment]
@blackdwarf has this been fixed?

**Comment by livarcocc** [comment]
From what I can see, the packages are showing up correctly now.
