### ISSUE TITLE
Migrate needs to turn off default globs if adding globs

### ISSUE THREAD

**Issue by 333fred** [dotnet/cli#5253]
Migrate https://github.com/robotdotnet/NetworkTables, NetworkTables.xproj.sln. The resulting csproj's have include globs with `**\*.cs`, but do not have `<EnableDefaultItems>false</EnableDefaultItems>`. This causes https://github.com/dotnet/sdk/issues/604 to show up in all projects. There are a few issues with the resulting csproj:

* Multiple compile lines - one for the default globs and one for the migrated includes. Not sure how easy it will be to condense them with how we do migration.
* Default items are not turned off, resulting in broken projects.

I'm using 1.0.0-preview5-004468. Tagging @livarcocc. /cc @thadhouse.

**Comment by jgoshi** [comment]
The issue is the globs now come from the SDK. We shouldn't be inserting them into the csproj file. Will make that fix.
