### ISSUE TITLE
dotnet-compile should not copy unnecessary files to the output directory

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/cli#526]
I happened to have some huge files under the project root directory and found that after `dotnet compile` they are copied to the output directory. For example, I did not expected `.xproj.user` and `.etl` files in the screenshot to be copied.

![image](https://cloud.githubusercontent.com/assets/7583839/11855104/0c4fa292-a3fd-11e5-89ae-0efd50b6e763.png)

**Comment by davidfowl** [comment]
Yes we should fix this. We need to implement nuget v3 contest do that we have a replacement

**Comment by davidfowl** [comment]
BTW you can exclude these in the exclude section :smile:

**Comment by blackdwarf** [comment]
Fixed with #767 so closing.
