### ISSUE TITLE
Update MSBuild package version - RC3

### ISSUE THREAD

**Issue by AndyGerlicher** [dotnet/cli#5263]
Approved changes to MSBuild affecting SDK implementation is going into VS today. Can you please update CLI to MSBuild package version `15.1.0-preview-000516-03`.

Package syncs to:
https://github.com/Microsoft/msbuild/tree/40cd4d090dfebddd5417bc4e976feebc081a02ed

**Comment by rainersigwald** [comment]
After the package-references-updated-too-far problem in #5266, version `15.1.0-preview-000517-01` should do the trick. I've confirmed that it doesn't change dependencies for .NET Core from the currently-dropped 503 version, even though the vsix for 517 still deploys the updated Collections.Immutable 1.2.1.

**Comment by piotrpMSFT** [comment]
This was merged last night. Subsequent MSBuild update is tracked in #5283
