### ISSUE TITLE
when i run dotnet command,dotnet alway initialize, 1.0.0-preview4-004233,  on win10 sub system(ubuntu)

### ISSUE THREAD

**Issue by 717009629** [dotnet/cli#5271]
## Steps to reproduce
![jto b teo 0xt9x 14tojom](https://cloud.githubusercontent.com/assets/16289643/21839552/431b7166-d813-11e6-84fd-041585ef6a3e.png)
`lius@DESKTOP-AVBTPSE:/mnt/c/Users/71700/test1$ dotnet new`
`Welcome to .NET Core!`
`---------------------`
`Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.`
`Telemetry`
`--------------`
`The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.`
`You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.`
`You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.`
`Configuring...`
`-------------------`
`A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.`
`Decompressing 100% 2627 ms`
`Expanding 100% 25547 ms`
`Success`
`lius@DESKTOP-AVBTPSE:/mnt/c/Users/71700/test1$ dotnet new`
`Welcome to .NET Core!`
`---------------------`
`Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.`
`Telemetry`
`--------------`
`The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.`
`You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.`
`You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.`
`Configuring...`
`-------------------`
`A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.`
`Decompressing 100% 2597 ms`
`Expanding 100% 25704 ms`
`Success`
`lius@DESKTOP-AVBTPSE:/mnt/c/Users/71700/test1$ ls`
`lius@DESKTOP-AVBTPSE:/mnt/c/Users/71700/test1$`
## Expected  behavior
executive command and only one initialize

## Actual behavior
always initialize and not  executive command 

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-preview4-004233

 the system is win10 sub system

**Comment by piotrpMSFT** [comment]
We're not going to be able to address this with a fix before RTM. However, you can side-step this problem by `export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1` for the time being.

**Comment by 717009629** [comment]
When I update sdk  to 1.0.0-rc4-004553, it is  OK ,thank you

**Comment by piotrpMSFT** [comment]
Great!
