### ISSUE TITLE
Use VersionTools package to update the dotnet/versions repository

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#5276]
Currently CLI uses a custom `VersionRepoUpdater`, and moving to the shared implementation would be helpful to get fixes.

For example, @MichaelSimons manually added a file for the CLI rc3 branch (https://github.com/dotnet/versions/pull/112) and that wouldn't have been necessary if CLI could easily uptake https://github.com/dotnet/buildtools/pull/1287.

/cc @eerhardt

**Comment by piotrpMSFT** [comment]
@dagood we're not familiar with the shared infrastructure, but if it will make cross-repo integration better then I don't see issue in adopting it. Is there someone that could make a PR?

**Comment by eerhardt** [comment]
It should be as simple as replacing our copy of 
https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/shared-build-targets-utils/VersionRepoUpdater.cs
with 
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.VersionTools/Automation/VersionsRepoUpdater.cs using the 

```
    <PackageReference Include="Microsoft.DotNet.VersionTools">
      <Version>1.0.26-prerelease-00615-07</Version>
    </PackageReference>
```

that we already use in the update-dependencies script.  I'm not sure on the version that should be used... I'm assuming the one in update-dependencies is pretty old.

**Comment by dagood** [comment]
Yeah, `00615-07` is just about as old as possible. Going for the most recent (say, `1.0.27-prerelease-01214-01`) should be fine. If there are any issues adopting it, making fixes to buildtools seems better than going back to an old version.

cc @dleeapho Maybe something that we could help with.
