### ISSUE TITLE
Running tests manually after full rebuild requires cleaning TestAssets

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5278]
## Steps to reproduce
```
git clean -fdx
dotnet build
cd test\anyTestProject
dotnet restore
dotnet test
```

## Expected  behavior
Test pass

## Actual behavior
Test fail complaining about problems with TestAssests and recommending to clean that directory, `git clean -fdx` in TestAssets\ in fact fixes the issue

## Environment data
`dotnet --info` output:
```
 Version:            1.0.0-preview5
 Commit SHA-1 hash:  d7aa960a44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004485
```

Also Environement Variables:
```
NUGET_PACKAGES=D:\cli\.nuget\packages
PATH containing `D:\cli\artifacts\win10-x64\stage2`
```

**Comment by piotrpMSFT** [comment]
@krwq I've not seen this as a result of build. I have seen it, however, as a result of `git pull` that affect test assets. Are you sure that the build is the cause here? Do you have a repro  I can look at

**Comment by krwq** [comment]
this is happening after doing `git clean -fdx` and `build` and then building specific test projects. I've seen that on Windows machines and haven't tested any of the non-windows. I'll pull the latest and check if it still repros

**Comment by krwq** [comment]
@piotrpMSFT still repros for me

**Comment by krwq** [comment]
@piotrpMSFT I think I know what might be the issue - we seem to be doing global restore for project.jsons and .tam seems to be picking up additional lock.json and assumes that source files has changed.
