### ISSUE TITLE
The lastest bits for Windows in the .zip file are outdated

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#528]
Repro steps:

1. Download the `install.ps1` file from 
2. Run it
3. Run `dotnet new`

Expected: a `Program.cs` and a `project.json` in the current directory. 

Actual: 'dotnet-new' is not recognized as an internal or external command, operable program or batch file.

**Comment by brthor** [comment]
Is `dotnet init` in that zip?

**Comment by Sridhar-MS** [comment]
@blackdwarf When did you try this? I fixed some issues in CI to push the latest builds on windows today morning. And I also see the latest zip in the blob storage.

**Comment by Sridhar-MS** [comment]
Verified that the latest zip file does indeed have dotnet-new in it.

**Comment by blackdwarf** [comment]
@Sridhar-MS weird, I tried it 1-2hrs ago. I used the install.ps1 script, so could it be that it is pointing to the wrong location?

**Comment by piotrpMSFT** [comment]
Did you run in powershell or CMU? The ps1 does not update cmd's path when run with @powershell

**Comment by blackdwarf** [comment]
Powershell.

**Comment by brthor** [comment]
Fixed
