### ISSUE TITLE
dotnet migrate downgrades 1.1.0 AspNetCore tools to 1.0.0 equivalents

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#5280]
## Steps to reproduce
1. Start with a project.json that references a 1.1.0 AspNetCore tool:

```js
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
      "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final",
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```
2. Run `dotnet migrate`

## Expected  behavior
The tool gets migrated to `1.1.0-msbuild3-final`.

## Actual behavior
The tool gets downgraded to the `1.0.0-msbuild1-final` version

**Comment by pranavkm** [comment]
cc @livarcocc \ @DamianEdwards

**Comment by livarcocc** [comment]
Let's track this here: https://github.com/dotnet/cli/issues/5284.
