### ISSUE TITLE
Enabling Linux ARM32 for SDK

### ISSUE THREAD

**Issue by jyoungyun** [dotnet/cli#5289]
Host: Ubuntu 14.04 x64
Target: Ubuntu 14.04 or(and) 16.04 ARM, Ubuntu 14.04 ARM Softfp and Tizen

**Cli**
- [ ] Support cross-build (#5290)
- [ ] Add RID for arm, armel and tizen
ubuntu.14.04-arm, ubuntu.16.04-arm, debian.8-armel, tizen.4.0.0-armel
- [ ] Version up to netcoreapp1.1 target framework

Related issue: https://github.com/dotnet/core-setup/issues/725

**Comment by jyoungyun** [comment]
Our arm and armel patches we worked on were merged into the master branch in CoreCLR, CoreFX and Core-setup. The master branch of those projects is targeting `netcoreapp1.1`. However, in the case of cli, it targets `netcoreapp1.0` so it does not match our output and version. I would like to suggest creating a new branch for `netcoreapp1.1` like `rel/1.1.0`. Can you share the plans you have about cli?

**Comment by gkhanna79** [comment]
CC @livarcocc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@jonsequitur can you take a look at this tomorrow?

**Comment by livarcocc** [comment]
We now have a linux arm32 build available of the SDK.
