### ISSUE TITLE
Ubuntu/Mac build breaks with spaces in the path

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#529]
Easy to Repro:

```
git clone https://github.com/dotnet/cli "cli space test"
cd "cli space test"
./build.sh
```

Output on Ubuntu 14.04:
```
azureuser@work:~/cli space test$ ./build.sh
./build.sh: line 38: [: too many arguments
*** Building dotnet tools version 1.0.0.1450301551 - Debug ***
./build.sh: line 57: /home/azureuser/cli: Is a directory
```

**Comment by brthor** [comment]
This is causing some CI instability in mac builds. So scheduling for Jan

@Sridhar-MS

**Comment by brthor** [comment]
Plumbed through this today. Basically needed quotes everywhere.

The solution is blocked on #525

**Comment by Sridhar-MS** [comment]
Is it possible to submit a partial PR for the build scripts alone? We can fix #525 independently.

**Comment by brthor** [comment]
Yes, will do. It's hard to verify if there are further issues past where #525 is breaking though. So I would leave this issue open until #525 is closed.

**Comment by brthor** [comment]
@Sridhar-MS see #545

**Comment by blackdwarf** [comment]
I'm pretty sure this works now, so closing. If it still a problem, reopen.

**Comment by brthor** [comment]
This is most likely not fixed
