### ISSUE TITLE
Dotnet migrate is emiting condition rid for libraries. No rid should be emit for libraries unless the PJ already had them.

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5294]
When performing dotnet-migrate in some cases generated project has following combination:
```
    <TargetFrameworks>netcoreapp1.1;net451</TargetFrameworks>
    <RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net451' ">win7-x86</RuntimeIdentifier>
```
which makes RuntimeIdentifier always empty. 

Here is what works in my workaround:
```
<RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net451' or $([System.Text.RegularExpressions.Regex]::IsMatch($(TargetFrameworks), '(^|;)net451($|;)'))">win7-x86</RuntimeIdentifier>
```

This should be plumbed in the dotnet-build.

That is causing the build to fail.

@piotrpMSFT @livarcocc @jonsequitur @piotroko @jgoshi @blackdwarf 
Do we want that behemoth in the csproj or do we plan to clean-up something around the TargetFramework vs TargetFrameworks mess?

**Comment by piotrpMSFT** [comment]
help me understand...

```
<TargetFrameworks>netcoreapp1.1;net451</TargetFrameworks>
```

Note the `s` which makes this the property that drives the outer build. Issuing a `/t:Build` will first do an outer loop which splits that property's value on `;` and uses it to generate a list of `<TargetFramework>` [no `s`]. It then calls the inner build using each  `<TargetFramework>`. The condition on the `RutimeIdentifier` looks at this derived property and should therefore work as-is.

Are you seeing a different behavior?

**Comment by krwq** [comment]
@piotrpMSFT I'm seeing the build is failing and fixing that by hand helps - haven't investigated what causes that exactly

**Comment by piotrpMSFT** [comment]
ok. I'm very curious.

**Comment by livarcocc** [comment]
We did this because net451 requires a rid. If we did not condition that rid to net451, then the portable app (netcoreapp1.0) would always work as a stand alone app.

Also, yeah, we don't need to do the split, because targetframework gets set automatically by the build.

What error are you seeing?

**Comment by krwq** [comment]
@livarcocc that runtime identifier is not specified, I'll try to get some more details

**Comment by livarcocc** [comment]
This is strange, we actually have a test in the CLI already covering this scenario. We use this test asset: https://github.com/dotnet/cli/blob/rel/1.0.0/TestAssets/TestProjects/TestAppMultipleFrameworksNoRuntimes/project.json.

I wonder how your project.json differs from this one. Multiple RIDs should have been added with the conditional RID above.

**Comment by krwq** [comment]
@livarcocc Thanks for pointing me to that test. I'll take a look and try to get repro or see if there is something else wrong

**Comment by krwq** [comment]
@livarcocc , I think the problem might be with dotnet-build or msbuild part.
dotnet-migrate seems to produce something equivalent to below which looks right

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net451</TargetFrameworks>
    <RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net451' ">win7-x86</RuntimeIdentifier>
  </PropertyGroup>

</Project>
```

but this is causing the dotnet-build to fail - seems like the TargetFramework is not being passed to msbuild

**Comment by krwq** [comment]
@livarcocc when running `dotnet build -v d` I'm seeing this in the msbuild log:
```
 Global Properties:
           TargetFramework=net451
```
which seems correct but some reason does not get picked up by `<RuntimeIdentifier Condition=" '$(TargetFramework)' == 'net451' ">win7-x86</RuntimeIdentifier>`

**Comment by livarcocc** [comment]
This is the PJ in question: https://github.com/aspnet/HtmlAbstractions/blob/dev/test/Microsoft.AspNetCore.Html.Abstractions.Test/project.json.

The issue here is that the PJ is a library, for which we do not emit RIDs, however, we should not emit the single conditioned RID either.

@jgoshi you made the change to not emit RIDs, but it seems we have some left over from that work. Can you take a look.

**Comment by livarcocc** [comment]
I just tried this out with the latest build from rel/1.0.0-rc3 and we do not emit the RuntimeIdentifier(s) properties, which is the correct thing to do. Closing this.
