### ISSUE TITLE
dotnet clean for RID enabled projects says it needs a RID, but no way to set a RID outside of MSBuild properties

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#5303]
## Steps to reproduce

1. Create a net46 project
2. Publish or build using the `--runtime` switch
3. Watch it pass
4. Run `dotnet clean`

## Expected  behavior
The command works and the project is cleaned. 

## Actual behavior
`dotnet clean` shows the following:

```bash
C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets(49,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [F:\Experiments\repros\clean\clean.csproj]
```

When I try to use the `--runtime` version to pass in the RID (`dotnet clean --runtime win7-x86`) I get the following:

```shell
Microsoft (R) Build Engine version 15.1.458.808
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: --runtime

For switch syntax, type "MSBuild /help"
```

### Workaround
Use the `/p:RuntimeIdentifier=<rid>` syntax to pass the RID to `dotnet clean`. However, this is neither user friendly nor in accordance to the overall way the CLI works. We need to support `--runtime` on `dotnet clean`. 

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview5-004478)

Product Information:
 Version:            1.0.0-preview5-004478
 Commit SHA-1 hash:  4d3e2872fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15002
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004478
```

/cc @livarcocc @jonsequitur @piotrpMSFT

**Comment by livarcocc** [comment]
It does not show an error anymore, but it does not clean the rid folder either.

```
dotnet restore -r osx.10.12-x64
dotnet build -r osx.10.12-x64
dotnet clean
```
The bin/debug/netcoreapp2.0/osx.10.12-x64 folder should be empty. It is not. In the very least, we still need to add the runtime as an option to clean.

However, if I specify the RID in the project using RuntimeIdentifier, clean works correctly.
