### ISSUE TITLE
Should 'dotnet migrate' respect the "projects" node in global.json?

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5304]
## Steps to reproduce
```
git clone https://github.com/DustinCampbell/omnisharp-roslyn
git checkout -b migrate-bug
dotnet migrate
```

## Expected  behavior

The global.json file is defined like so:

```JSON
{
  "projects": [
    "src",
    "tests"
  ]
}
```

My expectation is that dotnet migrate would only attempt to migrate projects in the "src" and "tests" directories.

## Actual behavior
The projects in the "test-assets" directory were also modified (which definitely should not be changed!).

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview5-004478)

Product Information:
 Version:            1.0.0-preview5-004478
 Commit SHA-1 hash:  4d3e2872fe

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15002
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004478
```

**Comment by DustinCampbell** [comment]
Looking at the help for `dotnet migrate`, it seems pretty clear that it will search the directory. So, this behavior is by design. However, it's definitely initially surprising.

**Comment by livarcocc** [comment]
@blackdwarf What do you think? Should we change the behavior here so that migrate, when finding (or using) a global.json file, if it contains project folders, will only migrate projects under those folders?

The offending line is here, btw: https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectJsonMigration/ProjectDependencyFinder.cs#L230. We always add the folder where dotnet migrate was ran as one of the folder to search for projects. Then, we add additional folders coming from GJ. The fix here is to only add the root folder if no folders exist in PJ.

**Comment by blackdwarf** [comment]
@livarcocc when we encounter the SLN file, we will only migrate the projects referenced in the SLN file, correct?

**Comment by DustinCampbell** [comment]
That wasn't my experience. OmniSharp also has an OmniSharp.sln that in the same directory where I executed 'dotnet migrate'. The sln doesn't include OmniSharp's test asset projects but they were migrated anyway.

**Comment by blackdwarf** [comment]
Then we need to fix that. SLN is the closure of the projects you care about, if we migrate based on it we should only ever migrate the projects in it.

I guess that also should go for `global.json` question seeing as how it is used as a solution-level artifact as well.

**Comment by DustinCampbell** [comment]
Yes, `global.json` was originally envisioned as your .sln replacement.

**Comment by DustinCampbell** [comment]
FYI, it looks like solution file issue is tracked with #5238

**Comment by livarcocc** [comment]
We should respect the Projects node in global.json and we should respect the projects in your SLN file as well.

**Comment by blackdwarf** [comment]
@livarcocc agreed. :)

**Comment by DustinCampbell** [comment]
Which wins if there're both present?

**Comment by livarcocc** [comment]
I put the ordering on this issue: https://github.com/dotnet/cli/issues/5238.

**Comment by livarcocc** [comment]
We are already respecting the projects in global.json, when you do dotnet migrate global.json.

I will double check that we do that for dotnet migrate solution.sln.

We have a separate bug tracking running dotnet migrate in folder migrated the appropriate artifact.
