### ISSUE TITLE
dotnet-migrate should ignore `tags` in project.json

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5309]
## Steps to reproduce
When migrating aspnet/MetaPackages the migration fails because tags element in project.json is unrecognized.

## Expected  behavior
Ignore deprecated element - perhaps show a warning

## Actual behavior
migration fails

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4)

Product Information:
 Version:            1.0.0-rc4
 Commit SHA-1 hash:  cf8fd7dd34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004506
```

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/4166.
