### ISSUE TITLE
Probe for DOTNET_REFERENCE_ASSEMBLIES_PATH on Mono

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#531]
Right now, to build for `net451` on non-Windows, you have to set `DOTNET_REFERENCE_ASSEMBLIES_PATH` to a folder containing the Mono reference assemblies. We should support scanning a few default locations for this.

/cc @victorhurdugaci @davidfowl

**Comment by davidfowl** [comment]
@anurse If you could expand the probing paths then we can just implement this. ASAP

**Comment by anurse** [comment]
Yeah, I should be able to do this before the holidays.

**Comment by weshaggard** [comment]
What paths are you planning to probe? How does this relate to providing a targeting pack in a package? https://github.com/dotnet/cli/issues/191

**Comment by davidfowl** [comment]
> What paths are you planning to probe?

@weshaggard The default mono install locations on each OS. @anurse went on vacation though :smile: 

OSX - `/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks/`
Linux - ???

It's directly related to that bug. Though there's no way to target mono specifically today. If there was, this would be needed for that.

**Comment by victorhurdugaci** [comment]
The paths are here: https://github.com/aspnet/Universe/blob/dev/KoreBuild-dotnet/build/KoreBuild.sh#L48-L56

**Comment by borgdylan** [comment]
```$(dirname `which mono`)/../lib/mono/xbuild-frameworks``` evaluates to right path.

**Comment by borgdylan** [comment]
In the mono fork at https://github.com/borgdylan/dotnet-cli I solved this by setting the environment variable in the dotnet-compile launch script.

**Comment by anurse** [comment]
We probably want to avoid having to shell out to `which`, but we can use a similar process by just probing the `PATH` variable to find the `mono` binary and then apply the relative path as above.

Re #191 - That may remove the need for this, but I haven't heard what the progress/timeline is on that.

**Comment by borgdylan** [comment]
You can also opt to use startup scripts like it is done with mono. The script sets teh environment variable then starts up dotnet-compile using CoreCLR.

**Comment by natemcmaster** [comment]
+1 as this will affect omnisharp running on dotnet. In some scenarios (e.g. VSCode), it can be difficult to set the environment variable before omnisharp starts. cref https://github.com/OmniSharp/omnisharp-roslyn/issues/412

**Comment by victorhurdugaci** [comment]
@troydai mentioned that he's working on this item, this morning

**Comment by anurse** [comment]
Yeah, he was going to do it in OmniSharp, but I suggested he do it here instead since everything needs it

**Comment by troydai** [comment]
Fixed in 429625061dc64bf1b8a53d140486b301612b2727

**Comment by victorhurdugaci** [comment]
@troydai can you please update our build script once this goes through? https://github.com/aspnet/KoreBuild/blob/dev/build/KoreBuild.sh#L61-L70

**Comment by troydai** [comment]
Sure: https://github.com/aspnet/KoreBuild/issues/34
