### ISSUE TITLE
dotnet sln add should not add duplicate solution folders

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5310]
This happens during migration as well in cases where migration detects we should add a project to the solution.

**Comment by krwq** [comment]
dup of https://github.com/dotnet/cli/issues/5224

**Comment by livarcocc** [comment]
Would this happen if I did a dotnet add manually twice for the same project?

**Comment by jgoshi** [comment]
Should not because we check to make sure the project isn't added twice. This is the code for taking a project path (that we add) and ensuring we have solution folders.
