### ISSUE TITLE
Migrating an sln with a xproj with different name results in the wrong csproj path in the sln

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5312]
## Steps to reproduce
migrate and build https://github.com/aspnet/AzureIntegration

## Expected  behavior
build succeeded

## Actual behavior
```
The project file "D:\aspnetsrc\AzureIntegration\test\Microsoft.AspNetCore.AzureAppServicesIntegration.Tests\Microsoft.AspNetCore.AzureAppServicesIntegration.Test.csproj" was not found. [D:\aspnetsrc\AzureIntegration\AzureIntegration.sln]
```

The name of csproj after migration does not have 's' in 'Tests' - name should be coming from xproj name or some attribute inside - it is coming from folder name instead

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4)

Product Information:
 Version:            1.0.0-rc4
 Commit SHA-1 hash:  cf8fd7dd34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\artifacts\win10-x64\stage2\sdk\1.0.0-preview5-004506
```

**Comment by livarcocc** [comment]
Independently of where the name comes from, it should match in the sln file.

**Comment by livarcocc** [comment]
cc @jgoshi who might have some insight on this.

**Comment by livarcocc** [comment]
Btw, we made a call a while ago that the csproj name should match the folder name, since that defined the name in PJ world. We could revisit to maybe use the xproj name if one is found.

cc @blackdwarf

**Comment by DustinCampbell** [comment]
Matching the folder name makes sense to me since the .xproj was never *really* the project. It was always the project.json.

**Comment by livarcocc** [comment]
@DustinCampbell I agree. This means that the bug here is that migration is not putting the right csproj file name/path in the sln when it modifies it.

**Comment by jgoshi** [comment]
This works properly if you do dotnet migrate solution.sln. That is the only time we write the sln file. If you just call dotnet migrate we do not touch the sln file, and this is where we are running into problems.

**Comment by DustinCampbell** [comment]
I think that's tracked with https://github.com/dotnet/cli/issues/5238

**Comment by livarcocc** [comment]
@krwq Can you confirm how you ran migration for this repo? Did you do dotnet migrate or dotnet migrate <sln_file>? If the former, then yes, it is a dup of https://github.com/dotnet/cli/issues/5238 and we can close this one.

**Comment by krwq** [comment]
@livarcocc - I've run the aspnet-migrate project which is running dotnet migrate in the root folder and fixes some stuff in the build script

**Comment by livarcocc** [comment]
Ok, closing this as a dup then.
