### ISSUE TITLE
dotnet sln add shouldn't create redundant solution folder

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5314]
**Repro**
Given file layout
```
Test.sln
src/
    Microsoft.AspNetCore/
         Microsoft.AspNetCore.csproj
```
`dotnet sln add src/Microsoft.AspNetCore/Microsoft.AspNetCore.csproj`

**Expected**
Create a solution with this structure:
```
src/ (solution folder)
    Microsoft.AspNetCore.csproj
```

**Actual**
Created a solution with this structure:
```
src/ (solution folder)
    Microsoft.AspNetCore/ (solution folder)
      Microsoft.AspNetCore.csproj
```

**Using**
1.0.0-preview5-004478

**Comment by livarcocc** [comment]
@jgoshi

**Comment by jgoshi** [comment]
@blackdwarf I just want to make sure that this is what you had in mind? I thought we needed to introduce solution folders for each folder in the hierarchy.

**Comment by blackdwarf** [comment]
@natemcmaster just to make sure I understand, we are talking about the folders in the solution view in VS?

**Comment by natemcmaster** [comment]
Right. along with #5310, you end up with this:
![image](https://cloud.githubusercontent.com/assets/2696087/21948198/632e7336-d99e-11e6-8227-db69a011fb17.png)

**Comment by blackdwarf** [comment]
Nope, we should not do that. :)

**Comment by dasMulli** [comment]
There are two issues here:
1. Don't create a new solution folder every folder in the hierarchy that already exists as solution folder.
2. Collapse solution folders that only contain one project **with the same name** (or look at the hierarchy?)

The first case is pretty serious:
```
$ dotnet sln add **/*/*.csproj
Project `src/testconsole/testconsole.csproj` added to the solution.
Project `src/testlib/testlib.csproj` added to the solution.
```
=> two folders named "src"
```sln
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{7153C119-7909-4B4B-B06A-3E99C292F4DF}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "testconsole", "testconsole", "{F896067B-21D8-4613-8C55-540DF9E5EE7D}"
EndProject
Project("{13B669BE-BB05-4DDF-9536-439F39A36129}") = "testconsole", "src\testconsole\testconsole.csproj", "{43AD1509-6163-49BB-8B5A-D2E045A6B806}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "src", "src", "{CF841002-B1C5-4030-9CB3-85861C5D4B25}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "testlib", "testlib", "{A64ECFE6-E092-4150-97CD-D3FE294458BC}"
EndProject
Project("{13B669BE-BB05-4DDF-9536-439F39A36129}") = "testlib", "src\testlib\testlib.csproj", "{556412A8-EA70-444C-AA51-10034BAC8A77}"
EndProject
```

**Comment by dasMulli** [comment]
oh, just saw that there is already #5310 for my first point

**Comment by jgoshi** [comment]
I'm going to do two things:
1. Don't create a new solution folder every folder in the hierarchy that already exists as solution folder. This is issue #5310 
2. Do not create a solution folder for the folder containing the project.
