### ISSUE TITLE
Migration: explicit compile include *.cs results in a build break

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5316]
If you have the following in your project.json file.
"compile": {
      "include": "*.cs",
}

The migrated file contains the *.cs compile item. But since this is already inserted by the SDK, this results in a build break (saying you have included the same file for compilation multiple times).

**Comment by livarcocc** [comment]
I was trying to avoid this, having to do comparisons with the user's globing and the SDK's implicit globing.

I guess we could have a list and just remove that list of bad globing.
