### ISSUE TITLE
Migration: project.json that includes a non-existent file breaks the migrated csproj

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5319]
See the attached zip.

The project.json file has a compile statement that explicitly includes a file that does not exist. The project is still able to restore and build properly.

When we migrate we port over that compile include (as we should). But that causes the msbuild to fail saying the file does not exist.

**Comment by jgoshi** [comment]
[missingfiles.zip](https://github.com/dotnet/cli/files/705627/missingfiles.zip)

**Comment by livarcocc** [comment]
@jgoshi What do you think we should do here? I am not keen on migration verifying that all files in the PJ's globs exist.

**Comment by jgoshi** [comment]
I'd say this is a won't fix. To me it's ok if we are a little more strict than PJ. If a file doesn't exist and they get a build error they should remove the reference.

**Comment by livarcocc** [comment]
@DustinCampbell Do you have any ideas on how to get around this?

**Comment by DustinCampbell** [comment]
Nope, and I actually think this is fine. I would expect it to be quite rare.

**Comment by livarcocc** [comment]
Ok. Since we all think it is fine for migration to live with this, I am closing this issue.
