### ISSUE TITLE
Extract Build verb from Compile

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#532]
Compile is having two main responsibilities (happy paths):
1. find dependencies and decide which of them to compile
2. know how to invoke the bytecode and the native compiler for a project

In preparing for incremental compilation we need to separate responsibility 1. into a new verb, `Build`.
Eventually, Build needs to also:
- compute incrementality safety checks for the whole dependency tree before doing any compilation (issue #382)
- decide between incremental or non incremental

I'll start with two PRs:
- [x] split Build from Compile. CLI uses build instead of Compile
- [x] add safety checks and --profile flag to Build ()

Here is the updated user experience from issue #232 

![picture1 - copy](https://cloud.githubusercontent.com/assets/2255729/11859311/93f975e4-a41e-11e5-941c-ec653fc9b271.jpg)

![picture2](https://cloud.githubusercontent.com/assets/2255729/11859301/78de022a-a41e-11e5-9021-e7b0d758083a.jpg)

![picture3](https://cloud.githubusercontent.com/assets/2255729/11859303/7e8e882a-a41e-11e5-8e27-1aee8686429d.jpg)

**Comment by blackdwarf** [comment]
@cdmihai we still need to define what this command does all-up. Can you add also a Readme.md that is tailored as with the rest of the commands in the repo that outlines this?

**Comment by cdmihai** [comment]
Sure. I'll edit the readme and add it to the PR.

In short, given a root project, Build expands it into a graph of projects (root project + dependencies) and then compiles that graph either incrementally or non incrementally. For each node in the graph, Build invokes Compile to compile that node. Compile is then responsible for knowing how to setup and call the compiler.

For users, the difference mainly lies in calling build instead of compile

**Comment by dannyvv** [comment]
Agreed we should have. I'm okay if that happens succinctly on a future pull request. Since lots of folks are blocked on this I wouldn't hold off the PR

**Comment by blackdwarf** [comment]
For sure, no need to block the pr on this. Just for tracking.

**Comment by cdmihai** [comment]
I created a readme for Build: https://github.com/cdmihai/cli/wiki/Build-readme
And also modified the readme for compile: https://github.com/cdmihai/cli/wiki/Compiler---readme

I'll include them in my current PR once I'm done resolving conflicts :)

**Comment by blackdwarf** [comment]
Thanks, will take a look at the PR.

Thanks,
Z

Sent from my tricorder




On Fri, Dec 18, 2015 at 4:55 PM -0800, "Mihai Codoban" <notifications@github.com<mailto:notifications@github.com>> wrote:


I created a readme for Build: https://github.com/cdmihai/cli/wiki/Build-readme
And also modified the readme for compile: https://github.com/cdmihai/cli/wiki/Compiler---readme

I'll include them in my current PR once I'm done resolving conflicts :)

-

**Comment by blackdwarf** [comment]
Done in #663
