### ISSUE TITLE
Migration: We need to inject more implicit framework assemblies

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5320]
These are the ones that we've come across when migrating various projects that are not explicitly stated in the project.json file. But they are implicitly used in the build.

System.Security
System.ComponentModel.DataAnnotations
System.Runtime.Serialization

**Comment by livarcocc** [comment]
@dsplaisted It seems like project.json was doing more implicit assemblies for full framework than we currently have in the SDK. Can we review which ones we have in the SDK?

**Comment by jgoshi** [comment]
@dsplaisted Should these assemblies be implicitly included by the SDK?

**Comment by piotrpMSFT** [comment]
@jgoshi can you please open an SDK issue to track this?

**Comment by jgoshi** [comment]
https://github.com/dotnet/sdk/issues/714

**Comment by livarcocc** [comment]
@jgoshi what project did you try to migrate that you hit this? I don't think in project.json the CLI was injecting those. We should instead understand where they were coming from in PJ and see why that is not working in MSBuild world. It may be a explicit difference between PJ and MSBuild.

**Comment by jgoshi** [comment]
https://github.com/aspnet/DataProtection
https://github.com/aspnet/EntityFramework
https://github.com/aspnet/Mvc

**Comment by jgoshi** [comment]
For the DataProtection repo:
1. DataProtection-dev\test\Microsoft.AspNetCore.DataProtection.Test is the failing project
2. It references a project Microsoft.AspNetCore.DataProtection which in turn references System.Xml.dll, System.Xml.Linq.dll, System.Security.dll

For some reason the build is not honoring project reference framework dependencies.

@nguerrera do you have any ideas?

**Comment by livarcocc** [comment]
This does not look like a migration issue. Why is the SDK not using the references in the package dependencies?

**Comment by nguerrera** [comment]
LEt's discuss on dotnet/sdk#714
