### ISSUE TITLE
dotnet restore unable to resolve 'Microsoft.NETCore.App (>= 1.2.0)'

### ISSUE THREAD

**Issue by dopare** [dotnet/cli#5330]
## Steps to reproduce
1. Install `1.0.0-rc4-004527` [tooling](https://github.com/dotnet/cli#installers-and-binaries) - latest is ![](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/Windows_x64_Release_version_badge.svg) at the moment
2. Clone [demo repo](https://github.com/dopare/dotnet-core-nightly) (simple console app targeting .NET Core 1.2). 
3. Run `dotnet restore` 

## Expected  behavior
All packages specified in `.csproj` and its dependencies are downloaded and installed without any error

## Actual behavior
Console output:
```
  Restoring packages for C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\DotnetCoreNightly.csproj...
C:\Program Files\dotnet\sdk\1.0.0-rc4-004527\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 1.2.0)' for '.NETCoreApp,Version=v1.2'. [C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\DotnetCoreNightly.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004527\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 1.2.0)' for '.NETCoreApp,Version=v1.2 (win10-x64)'. [C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\DotnetCoreNightly.csproj]
  Generating MSBuild file C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\obj\DotnetCoreNightly.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\obj\DotnetCoreNightly.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\obj\project.assets.json
  Restore failed in 665.89 ms for C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\DotnetCoreNightly.csproj.

  Errors in C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\src\DotnetCoreNightly\DotnetCoreNightly.csproj
      Unable to resolve 'Microsoft.NETCore.App (>= 1.2.0)' for '.NETCoreApp,Version=v1.2'.
      Unable to resolve 'Microsoft.NETCore.App (>= 1.2.0)' for '.NETCoreApp,Version=v1.2 (win10-x64)'.

  NuGet Config files used:
      C:\Users\Dopare\GitHub\dopare\dotnet-core-nightly\NuGet.Config
      C:\Users\Dopare\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
      https://dotnet.myget.org/F/cli-deps/api/v3/index.json
      https://api.nuget.org/v3/index.json
```

**NOTES**
1. Everything perfectly works with `1.0.0-preview5-004384` version of tooling.
2. Issue also exists in `1.0.0-preview5-004478` version of tooling

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004527)

Product Information:
 Version:            1.0.0-rc4-004527
 Commit SHA-1 hash:  49c2a4b6b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004527

### Attached dotnet restore output with COREHOST_TRACE=1
[dotnet_restore_output.txt](https://github.com/dotnet/cli/files/709397/dotnet_restore_output.txt)

**Comment by blackdwarf** [comment]
@dopare I cannot seem to repro this. I've installed the latest tools and cloned your repo. Ran `dotnet restore` and the project restored correctly. Can you try with the latest tooling? Just download the latest from the README links in this repo.

**Comment by dopare** [comment]
I am using `1.0.0-rc4-004527` tooling.
Have you been able to run the application after `dotnet restore` ?

**Comment by blackdwarf** [comment]
It gave me a normal error for a portable application which is that I don't have 1.2 installed on the machine. If I publish with `dotnet publish -r win10-x64` it produces an exe that I can run, but the actual app fails because it cannot find a csx file of some kind.

**Comment by dopare** [comment]
@blackdwarf  Can you please install 1.2 runtime on your machine an try `dotnet restore`.
P.S.
Actual apps fails, because `dotnet publish` does not copy .csx files. Didn't figure out how setup these files for publish.

**Comment by blackdwarf** [comment]
@dopare installing a runtime on a machine does not impact restore in any way. Are you saying that for you the install of the runtime makes a significant change on the restore operation?

**Comment by dopare** [comment]
Found fix, thanks @dasMulli 
Updated .NET Core app package reference in my .csproj 
`<PackageReference Update="Microsoft.NETCore.App" Version="1.2.0-beta-001304-00" />`
