### ISSUE TITLE
CLI tool can't prompt for input using ReadLine/ReadKey etc. properly

### ISSUE THREAD

**Issue by volkanceylan** [dotnet/cli#5332]
## Steps to reproduce

When you run a dotnet tool (e.g. one that defined in project.json) you can't use ReadLine, ReadKey etc. properly as output is redirected somehow, and you don't see anything until you press Enter.

## Expected  behavior

I'd expect it to print characters while i'm typing

## Actual behavior

You don't see what you wrote until you press Enter.

I've seen some issues about *dotnet run* and suggestion to use *dotnet myapp.dll* but that's not an option as my tool is running from a NuGet package, and if somehow i ask my users to find my tools DLL location and run it from there using dotnet, they'll get error about referenced DLLs / NuGet packages not found.

In some issues, it was also mentioned that it is fixed in Preview2, but i'm using Preview2 and this still exists.

## Environment data

Windows x64 / OSX / Linux, all same.

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@volkanceylan I just tried to repro this with RC3 [available from the home page of this repo]. I used this repro:

```
using System;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
    }
}
```

I executed `dotnet run` and then typed an arbitrary string. The characters I typed appeared on the console even before I pressed `enter`. I'm closing the issue as no-repro. If you find that there is a repro atop rc3 or later please do open a new issue with repro steps for us to try. Thanks!

**Comment by volkanceylan** [comment]
Could you kindly provide information about what is RC3? I don't see any links there about RC3. I see 1.0 SDK Preview 3 but there is no SDK Preview 3 for .NET 1.1. .NET Core versioning is really confusing.

This was an issue about running a tool defined in project.json through "dotnet toolname", not "dotnet run".
