### ISSUE TITLE
"Failed to process project file" using Unity on Sierra

### ISSUE THREAD

**Issue by gegagome** [dotnet/cli#5333]
## Steps to reproduce
Install Unity on macOS Sierra
Install VSCode plugin

## Expected  behavior
Code should autocomplete, show references, etc

## Actual behavior
TextEdit/Notepad behavior, no intellisense, etc

Even after following Kendra Havens's guide and https://github.com/dotnet/cli/issues/4357 Unity project still behaves like TextEdit, meaning no real C# code editor without any functionality other than type text.

## Environment data
`dotnet --info` output:

When running my Unity project named DELETE, using Code I get this:
Starting OmniSharp server at 1/15/2017, 8:52:23 PM
    Target: /Users/garces/Desktop/DELETE/DELETE.sln

OmniSharp server started wth Mono
    Path: /Users/garces/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/run
    PID: 78716

OmniSharp: -s /Users/garces/Desktop/DELETE/DELETE.sln --hostPID 78700 --stdio DotNet:enablePackageRestore=false --encoding utf-8 formattingOptions:useTabs=false formattingOptions:tabSize=4 formattingOptions:indentationSize=4
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/garces/Desktop/DELETE' on host 78700."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/garces/Desktop/DELETE
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] MSBUILD_EXE_PATH environment variable set to /Users/garces/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/msbuild/MSBuild.dll
[INFORMATION:OmniSharp#MSBuild] MSBuildExtensionsPath environment variable set to /Users/garces/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/msbuild
[INFORMATION:OmniSharp#MSBuild] MSBuildSDKsPath environment variable set to /Users/garces/.vscode/extensions/ms-vscode.csharp-1.6.2/bin/omnisharp/msbuild/Sdks
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/garces/Desktop/DELETE/DELETE.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/garces/Desktop/DELETE/Assembly-CSharp.csproj'.
[WARNING:OmniSharp#ProjectFileInfo] Couldn't locate Mono, TargetFrameworkRootPath not specified
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file '/Users/garces/Desktop/DELETE/Assembly-CSharp.csproj'.
/Users/garces/Desktop/DELETE/Assembly-CSharp.csproj

[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/garces/Desktop/DELETE/Assembly-CSharp-Editor.csproj'.
[WARNING:OmniSharp#ProjectFileInfo] Couldn't locate Mono, TargetFrameworkRootPath not specified
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v2.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file '/Users/garces/Desktop/DELETE/Assembly-CSharp-Editor.csproj'.
/Users/garces/Desktop/DELETE/Assembly-CSharp-Editor.csproj

[INFORMATION:OmniSharp.Script.ScriptProjectSystem] Detecting CSX files in '/Users/garces/Desktop/DELETE'.
[INFORMATION:OmniSharp.Script.ScriptProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Configuration finished.

**Comment by gegagome** [comment]
Before Sierra this was never an issue and Code work effortlessly.

**Comment by blackdwarf** [comment]
/cc @DustinCampbell 

This seems to be something that is better for the OmniSharp-vscode repo.

**Comment by piotrpMSFT** [comment]
Moved to omnisharp-vscode

**Comment by DustinCampbell** [comment]
Thanks!

**Comment by gegagome** [comment]
Thank you @piotrpMSFT
