### ISSUE TITLE
dotnet new still project.json-based?

### ISSUE THREAD

**Issue by brgrz** [dotnet/cli#5336]
## Steps to reproduce

Downloaded and installed the latest .NET Core 1.1 SDK with VS Code. 

Entered either dotnet new or dotnet new -t web and both resulted in project.json based project.

## Expected  behavior

Create the new csproj/msbuild based project.

## Actual behavior

project.json is still there.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)
Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

Is the only way to work with the new csproj formats to use VS 2017 RC? I was hoping that would not be the only way.

**Comment by brgrz** [comment]
Oh shit https://github.com/dotnet/cli/issues/5152

**Comment by brgrz** [comment]
Solved this issue by installing the .NET Core SDK installer from this GitHub's repo readme https://github.com/dotnet/cli (the first one Windows x64).

However it makes little sense that the installers at https://www.microsoft.com/net/download/core don't include these latest bits when selecting the Current tab.

**Comment by piotrpMSFT** [comment]
@brgrz thanks for the issue. We'll be flipping the default download on https://www.microsoft.com/net/download/core as we approach RTM of the new tooling.
