### ISSUE TITLE
Migration confusion when two different dotnet.exe are on the machine

### ISSUE THREAD

**Issue by MattGertz** [dotnet/cli#5340]
## Steps to reproduce
Only the x64 version of dotnet.exe gets updated when VS is installed.  But %path% preferentially prefers x86 by default, so whatever version of dotnet is in there actually gets run by default.  Loading the subsequent csproj in VS results in non-intuitive behavior; VS doesn't recognize interim migrations.

This has bit me so many times.  We really need to figure out what to do here.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#34
