### ISSUE TITLE
Importing .xproj Solution file doesn't use .csproj. It still points at .xproj.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#5344]
## Steps to reproduce
1. Grab the Dapper repo here: https://github.com/StackExchange/dapper-dot-net/
2. Open `Dapper.sln` in VS 2017 RC
3. Upgrade all projects when prompted.

## Expected  behavior
The solution file should reference the new `.csproj` files.

## Actual behavior
Solution file is not updated, `.xproj` projects remain. The GUIDs for the projects change, but that's it.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004504)

Product Information:
 Version:            1.0.0-rc3-004504
 Commit SHA-1 hash:  b312fbb176

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004504
```

**Comment by NickCraver** [comment]
cc @livarcocc for migrate tag

**Comment by piotrpMSFT** [comment]
@333fred 

SLN file updates are handled outside of the CLI in this scenario.

**Comment by livarcocc** [comment]
I believe this was happening because of https://github.com/dotnet/cli/pull/5352. I tried dapper yesterday and migration actually failed because of the PR above.

**Comment by piotrpMSFT** [comment]
@NickCraver can you try again with the latest CLI, per @livarcocc's note?

**Comment by livarcocc** [comment]
I am going to install VS2017 and give this a try.

**Comment by livarcocc** [comment]
The solution file was correctly updated.
