### ISSUE TITLE
Migrating project.json improperly converts EntityFramework and other packages to <ProjectReference>

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#5347]
## Steps to reproduce
1. Grab the Dapper repo here: https://github.com/StackExchange/dapper-dot-net/
2. Open `Dapper.sln` in VS 2017 RC
3. Upgrade all projects when prompted.

[This is the previous `project.json` for quick reference](https://github.com/StackExchange/dapper-dot-net/blob/23e6b64c9ff0121ce1c9a9dcf80648be20780d5c/Dapper.Tests/project.json). Specifically:
```json
  "EntityFramework": "6.1.3",
  "NHibernate": "4.0.4.4000",
```

## Expected  behavior
`EntityFramework` and `NHibernate` should be converted to package references, like this:
```xml
<PackageReference Include="EntityFramework" Version="6.1.3"  />
<PackageReference Include="NHibernate" Version="4.0.4.4000" />
```
## Actual behavior
`EntityFramework` and `NHibernate` point to `.csproj` files that don't exist.
```xml
<ProjectReference Include="EntityFramework\EntityFramework.csproj" />
<ProjectReference Include="NHibernate\NHibernate.csproj" />
```
This behavior happens for `EntityFramework` in the `Dapper.EntityFramework` and `Dapper.EntityFramework.StrongName` projects as well.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004504)

Product Information:
 Version:            1.0.0-rc3-004504
 Commit SHA-1 hash:  b312fbb176

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004504
```

**Comment by piotrpMSFT** [comment]
@livarcocc this is a more general problem due to project directories colliding on names with package references. Can you update the title and articulate the general problem?
