### ISSUE TITLE
Migration of `project.json` with compile: { includeFiles } creates extra <Compile> elements. 

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#5349]
## Steps to reproduce
1. Grab the Dapper repo here: https://github.com/StackExchange/dapper-dot-net/
2. Open `Dapper.sln` in VS 2017 RC
3. Upgrade all projects when prompted
4. Fix references as detailed in https://github.com/dotnet/cli/issues/5347
5. Build solution

Original source `project.json` is here, relevant section:
```json
  "buildOptions": {
    "warningsAsErrors": true,
    "compile": {
      "include": [
        "**/*.cs"
      ],
      "includeFiles": [
        "../Dapper/TypeExtensions.cs"
      ] 
    }
  }
```

## Expected  behavior
`Dapper.Contrib\Dapper.Contrib.csproj` should have only this for compile directives:
```xml
  <ItemGroup>
    <Compile Include="..\Dapper\TypeExtensions.cs" />
  </ItemGroup>
```

## Actual behavior
The converted `Dapper.Contrib.csproj` contains the `*.cs` include, unnecessarily:
```xml
  <ItemGroup>
    <Compile Include="..\Dapper\TypeExtensions.cs" />
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>
```
This results in the following build warning:
> Duplicate 'Compile' items were included. The .NET SDK includes 'Compile' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultCompileItems' property to 'false' if you want to explicitly include them in your project file. The duplicate items were: 'Properties\AssemblyInfo.cs'; 'SqlMapperExtensions.Async.cs'; 'SqlMapperExtensions.cs'

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004504)

Product Information:
 Version:            1.0.0-rc3-004504
 Commit SHA-1 hash:  b312fbb176

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004504
```

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/5316.
