### ISSUE TITLE
migrate command not resolving/expanding dot

### ISSUE THREAD

**Issue by scottaddie** [dotnet/cli#5350]
## Steps to reproduce
1. Open a command shell
1. `mkdir C:\working_folder&&cd C:\working_folder`
1. `git clone https://github.com/scottaddie/DotNetCoreSampleApp`
1. `cd DotNetCoreSampleApp`
1. `dotnet migrate .`, and notice the following error occurs:
![period_error](https://cloud.githubusercontent.com/assets/10702007/21999769/829bc954-dbf0-11e6-9cd2-ec35409b7b50.png) 

## Expected  behavior
The dot in this command should expand and resolve to the current directory name. It should work just as well as:
1. `cd C:\working_folder`
1. `dotnet migrate DotNetCoreSampleApp`

## Actual behavior
A misleading error message is returned which leads one to believe that the `migrate` command isn't a recognizable command in the installed CLI.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004504)

Product Information:
 Version:            1.0.0-rc3-004504
 Commit SHA-1 hash:  b312fbb176

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004504
```

**Comment by livarcocc** [comment]
This is happening because you have a global.json in your root that points to preview2 CLI. Please, remove the global.json or edit it to change the SDK version in it or remove that entry entirely and then try migrating.

After doing that, the project did migrate for me.
