### ISSUE TITLE
Migration doesn't cleanup global.json, project.json and .xproj files.

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#5351]
## Steps to reproduce
1. Grab the Dapper repo here: https://github.com/StackExchange/dapper-dot-net/tree/23e6b64c9ff0121ce1c9a9dcf80648be20780d5c
2. Open `Dapper.sln` in VS 2017 RC
3. Upgrade all projects when prompted.

## Expected  behavior
These files should no longer exist in the main or project folders:
- `project.json`
- `project.lock.json`
- `*.xproj`
- `*.xproj.user`
- `global.json`

## Actual behavior
Files are still present, not removed.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004504)

Product Information:
 Version:            1.0.0-rc3-004504
 Commit SHA-1 hash:  b312fbb176

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004504
```

**Comment by livarcocc** [comment]
Can you please move this to https://github.com/dotnet/roslyn-project-system?

**Comment by NickCraver** [comment]
Migrated to https://github.com/dotnet/roslyn-project-system/issues/1184
