### ISSUE TITLE
dotnet migrate should update VisualStudioVersion = and MinimumVisualStudioVersion = 

### ISSUE THREAD

**Issue by NickCraver** [dotnet/cli#5353]
## Steps to reproduce
1. Get the `StackExchange.Redis` repo: `https://github.com/StackExchange/StackExchange.Redis/tree/d881e28c1b3366cc5ba908b74a34289767dd7d86`
2. Migrate via `dotnet migrate StackExchange.Redis.Core.sln`

## Expected  behavior
In `StackExchange.Redis.Core.sln`, `VisualStudioVersion` and `MinimumVisualStudioVersion` should be updated to a 15.x version.

## Actual behavior
`VisualStudioVersion` and `MinimumVisualStudioVersion` are untouched

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004504)

Product Information:
 Version:            1.0.0-rc3-004504
 Commit SHA-1 hash:  b312fbb176

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004504
```

## Discussion
I know dotnet CLI isn't supposed to know about Visual Studio at all, but in the case of a migration and generating new `.csproj` files in a format that only Visual Studio 15+ will understand, we're talking about a 100% breaking change. The `.sln`/`.csproj` combination that is generated is not something a user can open. It will open in Visual Studio 2015 and error in unexpected ways. This isn't very user friendly and I recommend incrementing the attributes accordingly so it opens in Visual Studio 2017 appropriately.

**Comment by piotrpMSFT** [comment]
@srivatsn @333fred thoughts on this? As @NickCraver calls out, I'm not a fan of having CLI make changes to the sln file which affect only VS as I don't want to clash with other migration steps that VS may need to do. We can't have that logic in two places given the complexity of the VS implementation. Is there a way we can provide a good experience in 2015 without breaking upgrade in 2017?

**Comment by jonsequitur** [comment]
@333fred Can you specify the version numbers please?

**Comment by 333fred** [comment]
`VisualStudioVersion = 15.0.26114.2`
`MinimumVisualStudioVersion = 10.0.40219.1`

**Comment by jgoshi** [comment]
@333fred Why does MinimumVisualStudioVersion stay at 10.0? Shouldn't it also be a 15.0 version?

**Comment by jgoshi** [comment]
In order to force the message telling the user to install a later version of VS.

**Comment by jgoshi** [comment]
@piotrpMSFT @livarcocc @333fred Just trying to make sure I understand this issue. Without the minimum visual studio version also being a 15.0 version, attempting to open in an older VS would still repro this issue right? So what should I use as the MinimumVisualStudioVersion?

**Comment by jgoshi** [comment]
Followed up offline. Leaving the minimum version is fine, by updating the VisualStudioVersion we ensure that double-click opens up in VS 2017.
