### ISSUE TITLE
Old version of dotnet.exe used for dotnet migrate by VS2017 (x86 dotnet.exe not updated with VS2017 RC3 install)

### ISSUE THREAD

**Issue by MarkMichaelis** [dotnet/cli#5354]
**Issue:**
After installing Visual Studio 2017 RC3 (Version 15.0.26114.2 D15REL) and running a migrate with either the command line or Visual Studio 2017RC3, the migration fails because an "legacy" dotnet.exe (from x86) is used.  The problem seems to be that there is a "legacy" version of dotnet x86 that appears earlier in my path than the dotnet x64 which VS2017 installs.
**Expectation:**
When installing VS2017 it would upgrade both my dotnet x64 and x86 installs.  Regardless, Visual Studio 2017 and a VS2017 Developer Command Prompt should be using the version of dotnet that VS2017 (or later?) installs.

/cc @blackdwarf, @morrisjoe

**Comment by livarcocc** [comment]
thanks for the bug @MarkMichaelis. We are already tracking this issue through https://github.com/dotnet/cli/issues/5340.
