### ISSUE TITLE
Migration: migrate sln fails to add project if project.json uses outputName

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5360]
See attached project as an example.

outputName forces us to use the AssemblyName attribute, but for some reason causes us to be unable to write the sln file properly

[AssemblyName.zip](https://github.com/dotnet/cli/files/711937/AssemblyName.zip)

**Comment by livarcocc** [comment]
I believe this is a dup of https://github.com/dotnet/cli/issues/5345. It fails to add to the sln projects that have an outputname set on it. @piotrpMSFT fixed this in rc3 yesterday.

**Comment by livarcocc** [comment]
cc @jgoshi

**Comment by jgoshi** [comment]
Yup it's a dup.
