### ISSUE TITLE
dotnet migrate fails if project.json includes deprecated options

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5361]
## Steps to reproduce

1. Download and unzip the following project: [test-project-with-projectUrl-migrate.zip](https://github.com/dotnet/cli/files/711963/test-project-with-projectUrl-migrate.zip).
2. Run `dotnet migrate`

## Expected  behavior
Migration successful but warning is outputted for the user due to deprecated property in project.json.

## Actual behavior
Migration fails due to deprecated warning in project.json. User has to manually tweak their project.json to successfully migrate.

```
Project test-project-with-projectUrl-migrate migration failed (C:\Projects\test-project-with-projectUrl-migrate)
MIGRATE1011::Deprecated Project: C:\Projects\test-project-with-projectUrl-migrate
The 'projectUrl' option in the root is deprecated. Use it in 'packOptions' instead. (line: 3, file: C:\Projects\test-project-with-projectUrl-migrate\project.json)

Summary
Total Projects: 1
Succeeded Projects: 0
Failed Projects: 1
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004527)

Product Information:
 Version:            1.0.0-rc4-004527
 Commit SHA-1 hash:  49c2a4b6b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15007
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004527
```

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/4166.

**Comment by DustinCampbell** [comment]
Ah yes, I'd forgotten. :smile:

Note: I expect customers will hit this quite a bit. There are many who don't keep their projects clean of warnings, and each of these will fail to migrate.
