### ISSUE TITLE
Visual Studio migration experience issues

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5367]
- For almost each project migrated we display a warning which seems weird in context of migration report:
```
Visual Studio needs to make non-functional changes to this project in order to enable the project to open in released versions of Visual Studio newer than Visual Studio 2010 SP1 without impacting project behavior.
```
- Some of the errors are quite not clear:
```
src\Microsoft.AspNetCore.DataProtection.AzureStorage\Microsoft.AspNetCore.DataProtection.AzureStorage.xproj: Could not read post-migration report at 'C:\Users\kwicher.REDMOND\AppData\Local\Temp\3kw3wkoq.5jh'.
```
- Message on failed migration could be improved (i.e. link to cli repo/issues, error code with some normal number or hex instead of negative number)
```
Failed to migrate XProj project Microsoft.AspNetCore.Cryptography.KeyDerivation. 'dotnet migrate --skip-backup -s -x "D:\aspnetsrc3\DataProtection\src\Microsoft.AspNetCore.Cryptography.KeyDerivation\Microsoft.AspNetCore.Cryptography.KeyDerivation.xproj" "D:\aspnetsrc3\DataProtection\src\Microsoft.AspNetCore.Cryptography.KeyDerivation" -r "C:\Users\kwicher.REDMOND\AppData\Local\Temp\zppkug5i.rnc" --format-report-file-json' exited with error code -532462766.
```
- Unhandled exceptions in migration happen, we do display stack trace but it is unclear what is user supposed to do with that -- link to github issues missing
- Unhandled exception is a warning...
- aspnet/Diagnostics migrates without errors. Build fails but there is no errors. Warnings are really cryptic.
- VS automatically starts restoring after migration or upon start - it would be ok if it wasn't making VS partially/fully unresponsive - all the UI buttons like Build are not grayed out while this is happening and it is unclear what's going to happen when you press it

**Comment by livarcocc** [comment]
@333fred 

@krwq I think you should move this bug to dotnet/roslyn-project-system.

Also, for not reading the report, that is because the CLI has not generated one. This is likely a migration ordering problem that we fixed last night for rc3.

**Comment by 333fred** [comment]
This issue was moved to dotnet/roslyn-project-system#1228
