### ISSUE TITLE
dotnet run throws Unhandled Exception: System.IO.FileLoadException

### ISSUE THREAD

**Issue by dopare** [dotnet/cli#5370]
## Steps to reproduce

1. Install `1.0.0-rc4-004530` dotnet cli
2. Install `2.0.0-beta-001368-00` shared runtime
3. Clone [demo app](https://github.com/dopare/dotnet-core-nightly) (simple console app)
4. Run `dotnet restore`
5. Run `dotnet run`

## Expected  behavior

Application runs without any exception.

## Actual behavior

Output:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.Write(String value)
   at DotnetCoreNightly.Program.Main(String[] args)
```

# NOTES
1. Application runs if I remove 
`    <PackageReference Include="Microsoft.DotNet.PlatformAbstractions" Version="2.0.0-beta-001368" />
` from `.csproj`
2. Application runs if I publish it as standalone app

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004530)

Product Information:
 Version:            1.0.0-rc4-004530
 Commit SHA-1 hash:  4f0b7bd58c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004530
```

**Comment by livarcocc** [comment]
I believe this bug belongs in the dotnet/sdk repo. Could you please move it there?

**Comment by livarcocc** [comment]
@dsplaisted

**Comment by dopare** [comment]
Moved to https://github.com/dotnet/sdk/issues/676
