### ISSUE TITLE
Provide guidance in VS 2015 about applying "sdk": "version" in global.json

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5375]
We should add guidance to help users when a newer .NET CLI is on the path that does not support project.json. I expect that project.json and I will be with us for a long while as not everyone will upgrade overnight.

Clearly, this would require servicing VS 2015 tooling which we likely wouldn't do just for this issue. However, if we *do* choose to service VS 2015 tooling, we should consider doing this at the same time.

**Comment by piotrpMSFT** [comment]
Moved to asp.net/tooling repo which tracks VS 2015 tooling.
