### ISSUE TITLE
Migration: https://github.com/aspnet/Mvc

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5378]
1. Go to https://github.com/aspnet/Mvc
2. Download as zip
3. dotnet migrate mvc.sln
4. dotnet restore mvc.sln
5. dotnet build mvc.sln

There are many build errors and I haven't been able to track down the root causes yet.

**Comment by livarcocc** [comment]
I tried this migration. As far as I can see I hit two known issues here:

1. https://github.com/NuGet/Home/issues/4412
2. https://github.com/dotnet/cli/issues/5318

After adding a reference to ViewFeatures to DataAnnotations, I managed to build all projects under src.
Tests continued to fail as I am not sure what I should put in place of the Shared that is causing all tests to fail.

However, given that the issues I have are other known issues, I am closing this one.
