### ISSUE TITLE
Migration: https://github.com/aspnet/MvcPrecompilation

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5379]
1. Go to https://github.com/aspnet/MvcPrecompilation
2. Download as zip
3. dotnet migrate TestApps.sln
4. dotnet restore TestApps.sln
5. dotnet build TestApps.sln

There are many build errors and I haven't been able to track down the root causes yet.

**Comment by livarcocc** [comment]
I got this to migrate, restore and build.

I did a full build using project.json by running build.cmd.

After that, I ran dotnet migrate sln_file, dotnet restore sln_file and dotnet build sln_file. All succeeded. However, I did have to manually delete a runtime.config.json file that had a lock on it. Imagine it came from the build.cmd.

I did run into an issue when running tests. I have filled it here: https://github.com/Microsoft/vstest/issues/368.
