### ISSUE TITLE
Migration: https://github.com/aspnet/Scaffolding

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5380]
1. Go to https://github.com/aspnet/Scaffolding
2. Download as zip
3. dotnet migrate Scaffolding.sln
4. dotnet restore Scaffolding.sln
5. dotnet build Scaffolding.sln

For some reason I needed to manually insert a PackageDependency to System.Diagnostics.Contracts in test\Microsoft.VisualStudio.Web.CodeGeneration.Test.Sources. I don't know where this was coming from in the project.json build.

**Comment by livarcocc** [comment]
@jgoshi this repo has moved to csproj a while ago. Where you using a particular branch for this?

When I tried, I got the result below, which seems correct.

```
dotnet migrate .\Scaffolding.sln
Unable to find any projects in .\Scaffolding.sln
Migration failed.
```

**Comment by jgoshi** [comment]
That's weird. I didn't enlist, I just downloaded a copy (from whatever was the default branch in GitHub). Since it's already done I'll go ahead and close this.
