### ISSUE TITLE
add command 'dotnet-compile-fsc'

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#539]
The project.json has the compilerName property, so i think the idea is to add "fsc" => `dotnet-compile-fsc`

F# is in priority P1, so i want to help with that

i think was easier to do #538 as a starting point of discussion

ref #586

**Comment by iainnicol** [comment]
I presume this can be closed because your PR was merged?  Thanks for implementing this, by the way.

**Comment by enricosada** [comment]
I think so. There see some issues/improvements but these can be fixed with other pr. 
Compiler fsc works

**Comment by blackdwarf** [comment]
Closing because #538 fixed it.
