### ISSUE TITLE
'dotnet migrate' should not delete 'project.json' file if it is to be copied to output

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5400]
This is really very low-pri, but I encountered a customer project where the project.json file copied itself to the output on build like so:

```JSON
  "buildOptions": {
    "copyToOutput": [
      "project.json"
    ]
  }
```

On migration, this results in the .csproj containing a reference to the project.json, but the project.json is missing because it was moved to the backup folder. I don't *think* this is a common pattern, so this should probably get a "won't fix", but I wasn't certain. Does anyone know?

**Comment by livarcocc** [comment]
I haven't seen this being done.

I don't think migration should try to understand this. One of the main goals of migration is to remove the project.json and dependencies on project.json. We shouldn't work around corner cases were we preserve it.

**Comment by DustinCampbell** [comment]
Yup. I totally agree.
