### ISSUE TITLE
The item "Class1.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter.

### ISSUE THREAD

**Issue by enricforn** [dotnet/cli#5404]
## Steps to reproduce

Clone repo https://github.com/enricforn/dotnetcore-webapi-sample-app.git

Use dotnetcore sdk version 1.0.0-rc4-004530

run dotnet restore

run dotnet build -v:n

## Expected  behavior

Compilation successful

## Actual behavior

Runs successfully on Visual Studio 2017RC environment Build 26020.00

Fails compiling in command line.
         C:\Program Files\dotnet\sdk\1.0.0-rc4-004530\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB3105: The item "Class1.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [D:\workspaces\enricforn\dotnetcore-webapi-sample-app\ClassLibraryTest\ClassLibraryTest.csproj]
## Environment data
`dotnet --info` output:

PS D:\workspaces\enricforn\dotnetcore-webapi-sample-app> dotnet --version
1.0.0-rc4-004530

##Possible workaround

I tried to solve the issue using workaround https://github.com/dotnet/sdk/issues/668 but it doesn`t work.

**Comment by livarcocc** [comment]
@enricforn I just tried this and I managed to build the solution.

This is what my ClassLibraryTest.csproj looks like:
```
<Project Sdk="Microsoft.NET.Sdk" >
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="1.6" />
  </ItemGroup>

</Project>
```

If this does not solve your problem, please re-open this issue.

**Comment by enricforn** [comment]
@livarcocc  if I remove these lines, Visual Studio 2017 do not recognize the class as added to the project

**Comment by livarcocc** [comment]
You may have an older version of VS, which does not understand globing yet.

**Comment by enricforn** [comment]
@livarcocc we're reproducing the error on build 26020.00, is there a new downloadable version ?

**Comment by livarcocc** [comment]
@balachir can you help with that?
