### ISSUE TITLE
dotnet restore appears to hang on slow connections

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5406]
## Steps to reproduce
Get slow internet.
Clear nuget caches.
dotnet new.
Add dependencies to lots of packages not in the first-run cache warmup. This can be done in a simple app by adding a bunch of rids to `<RuntimeIdentifiers>`.
dotnet restore.

## Expected  behavior
Show some sign of progress while downloading from the network. A spinner would be great, but even just confirmation that restore has begun would be helpful.

## Actual behavior
No console output appears until NuGet is almost done with the restore. In the screenshot below, restore took over a minute (85 seconds). There was not console output until about 75 seconds after restore began

![screenshot](https://cloud.githubusercontent.com/assets/2696087/22158803/e6344c3e-def2-11e6-9b81-84a04a948f12.png)

## Environment data
`dotnet --info` output: using 1.0.0-rc3

cc @shanselman @blackdwarf

**Comment by livarcocc** [comment]
@natemcmaster I believe this bug belongs in the nuget/home repo. Can you please move it there?

**Comment by natemcmaster** [comment]
This issue was moved to NuGet/Home#4346
