### ISSUE TITLE
dotnet migrate should fail to migrate projects that have "shared" properties in their project.json.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#5407]
## Steps to reproduce
- git clone git@github.com:aspnet/Mvc.git
- git checkout 305748a800bf00573e602905712045cc0bdfd267
- dotnet migrate

## Expected  behavior
- Migration should fail due to [some projects](https://github.com/aspnet/Mvc/blob/305748a800bf00573e602905712045cc0bdfd267/test/Microsoft.AspNetCore.Mvc.TestDiagnosticListener.Sources/project.json#L2) relying on the shared: *.cs behavior of `Microsoft.AspNetCore.Mvc.TestDiagnosticListener.Sources`

## Actual behavior
- Migration succeeds but attempting to build any project that depended on `Microsoft.AspNetCore.Mvc.TestDiagnosticListener.Sources` fails.

A better approach would be to fail at migrate time stating that the property is not supported.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004553)

Product Information:
 Version:            1.0.0-rc4-004553
 Commit SHA-1 hash:  6568113e34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\nimullen\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004553

**Comment by DustinCampbell** [comment]
Wouldn't https://github.com/dotnet/cli/issues/5318 be a better approach? My understanding of "shared" is that those files are essentially linked into the final compilation (like a shared project in VS).

**Comment by livarcocc** [comment]
@NTaylorMullen let's treat this as a dup of #5318, I would like to try the link approach, but if you disagree with it, can we take the discussion there?
