### ISSUE TITLE
TestAssets throws ArgumentException during rebuild when inventory file doesn't exist

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5412]
When fixing some synchronization issues I introduced the bug happening during rebuild when one of the inventory files doesn't exist and TestAssets checks if the inventory has changed.
This was introduced when changing the logic of LoadInventory to throw exception instead of empty list when file doesn't exist. This new logic is correct - ThrowIfAssetSourcesHaveChanged needs to account for that change.

I have a fix pending and will apply it as part of https://github.com/dotnet/cli/issues/5316 

If anyone is blocked by this here is the diff: (TestAssetsInfo.cs / ThrowIfAssetSourcesHaveChanged)
```diff
-  trackedFiles = _inventoryFiles.AllInventoryFiles.SelectMany(f => folder.LoadInventory(f));
+  trackedFiles = _inventoryFiles.AllInventoryFiles.SelectMany(f => {
+      f.Refresh();
+      return f.Exists ? folder.LoadInventory(f) : Enumerable.Empty<FileInfo>();
+  });
```

**Comment by piotrpMSFT** [comment]
I merged a fix in #5403
