### ISSUE TITLE
Update migration process to use "MSBuild RTM" builds of ASP.NET/EF packages

### ISSUE THREAD

**Issue by Eilon** [dotnet/cli#5414]
cc @livarcocc @natemcmaster @muratg @bricelam @NTaylorMullen 

Once we have RTM packages of the ASP.NET/EF tools we need to update the migration logic to use the new versions.

**Comment by piotrpMSFT** [comment]
@Eilon please have this issue updated once ready. Ideally with a list of packages and versions that will be bumped.

**Comment by Eilon** [comment]
@piotrpMSFT will do.

**Comment by Eilon** [comment]
Adding some additional assignees. Can't add @NTaylorMullen because he's not a member of this org, but that's ok.

**Comment by livarcocc** [comment]
@Eilon ping. Any idea when we will have some packages with the final version available in the feed?

**Comment by Eilon** [comment]
@livarcocc I'll add you to a thread. Our team needs RTM packages of Microsoft.Build.* from the MSBuild team, so we're blocked on that.
