### ISSUE TITLE
dotnet run myapp.dll crashes hard

### ISSUE THREAD

**Issue by forki** [dotnet/cli#5422]
* Create a new dotnet app of type console
* run restore and publish 
* go to bin/debug/netcore1.1/publish 
* run "dotnet run myapp.dll" (or whatever project name you had) 

The dotnet cli (rc 4) will crash hard and show stack trace that --project is missing. 

I suggest we catch that crash and show a better message to the user along the line "if you want to run myapp.dll then just call "dotnet myapp.dll""

**Comment by piotrpMSFT** [comment]
Great catch, @forki. We'll want to fix this one for sure!

**Comment by forki** [comment]
Alternatively to the better message you could also just make it run the thing. Not sure if whats better

**Comment by piotrpMSFT** [comment]
We'll fix the message. Having two ways to do a thing would be pretty confusing in the long term!

**Comment by piotrpMSFT** [comment]
@jonsequitur please consider the related repro in https://github.com/dotnet/cli/issues/5524. We should at least not be crashing on that one.
