### ISSUE TITLE
``dotnet nuget push *.nupkg`` doesn't push more than one file

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/cli#5436]
## Steps to reproduce

1. Install dotnet SDK daily build package
2. locate 2 different nupkg files
3. set up NuGet Server and API key as you can push nupkg to NuGet Server
4. run ``dotnet nuget push *.nupkg``

## Expected  behavior
Push all the nupkg files.
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-nuget-push

## Actual behavior
Only one nupkg files is uploaded.

```
$ ls
libuv.1.9.1.nupkg  Microsoft.AspNetCore.WebUtilities.1.0.0.nupkg
$  /opt/dotnet/dotnet nuget push * -k <NuGetKey> -s <NuGetServer>
info : Pushing libuv.1.9.1.nupkg to '<NuGetServer>'...
info :   PUT <NuGetServer>
info :   Created <NuGetServer> 9743ms
info : Your package was pushed.
[end]
```

## Environment data
`dotnet --info` output:
```
$  /opt/dotnet/dotnet --info
.NET Command Line Tools (1.0.0-rc4-004598)

Product Information:
 Version:            1.0.0-rc4-004598
 Commit SHA-1 hash:  1dfee9ead8

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.3
 OS Platform: Linux
 RID:         rhel.7.2-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004598
```

**Comment by livarcocc** [comment]
Please, file this bug at https://github.com/nuget/home.

**Comment by blackdwarf** [comment]
Since this is filed on nuget, closing this one.
