### ISSUE TITLE
dotnet restore generates project.lock.json with xproj instead of csproj

### ISSUE THREAD

**Issue by sm-g** [dotnet/cli#5437]
## Steps to reproduce
Create Core project referencing csproj library:
```
"frameworks": {
    "net461": {
      "dependencies": {
        "Library": {
          "target": "project"
        }
      }  
   }
}
```

Make `dotnet restore`.

## Expected  behavior
project.lock.json as after auto restore in VisualStudio:
```
"Library/1.0.0": {
      "type": "project",
      "path": "../Library/project.json",
      "msbuildProject": "../Library/Library.csproj"
    },
```
## Actual behavior
Created xproj and project.lock.json contains:
```
"Library/1.0.0": {
      "type": "project",
      "path": "../Library/project.json",
      "msbuildProject": "../Library/Library.xproj"
    },
```

`dotnet build --no-dependencies` now returns NRE or sometimes `Export D:\WebApp\project.fragment.lock.json does not provide exports for all the msbuild projects in D:\WebApp\project.lock.json`.

## Environment data
`dotnet --info` output: 
```
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
```

**Comment by piotrpMSFT** [comment]
This is an issue in the VS2015 tooling for project.json. Please open the issue in https://github.com/aspnet/tooling. The team is nearly done with the conversion from csproj to project.json, however. This issue is already fixed in the 1.0.0 wave where xproj/project.json no longer play a role.
