### ISSUE TITLE
test matrix for compatibility with netcoreapp1.0 and netcoreapp1.1 is not systematic

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/cli#5445]
Previous to #5415, we didn't need tests to explicitly check correct functioning when working with apps targeting multiple framework versions. This matrix is introduced by #5415. We do currently test against test projects targeting both netcoreapp1.0 and netcoreapp1.1, so there isn't a test gap, but more explicit, non-incidental tests for this matrix would be a good improvement.

After a brief discussion of how to cover this with @piotrpMSFT and @eerhardt, we decided that adding test variants and test projects for `new` and `test` as well as the tests under `EndToEnd.csproj` should be sufficient.

**Comment by livarcocc** [comment]
We have since added this coverage through the SDK repo.
