### ISSUE TITLE
Conversion mixes up line breaks

### ISSUE THREAD

**Issue by tmat** [dotnet/cli#5450]
## Steps to reproduce

- git clone https://github.com/sethjuarez/numl
- Open Src\numl.sln
- Conversion is offered, convert the solution
- Edit numl.Test project file

## Expected  behavior

Line breaks are consistent.

## Actual behavior

![image](https://cloud.githubusercontent.com/assets/41759/22275517/1dc8faf6-e262-11e6-829f-c5826b4aa228.png)

## Environment data
VS D15PreRel 26124.03

**Comment by piotrpMSFT** [comment]
@livarcocc @rainersigwald I believe this is a known issue in MSBuild. Perhaps you can link [or call out that I'm missremembering :) ]

**Comment by rainersigwald** [comment]
This is https://github.com/Microsoft/msbuild/issues/1401 I believe.

**Comment by livarcocc** [comment]
Yes, we are tracking it as an external issue here: https://github.com/dotnet/cli/issues/5040.
