### ISSUE TITLE
Support Flatpak

### ISSUE THREAD

**Issue by diegobfernandez** [dotnet/cli#5452]
I would like to install the cli on any Linux system without thinking about incompatible libraries and any other sort of problem.

**Comment by livarcocc** [comment]
The CLI will run in whatever platform the shared framework runs. Barring crossgen and currently some build definitions. I believe the right place for this bug is the github.com/dotnet/core-setup repo. Can you move it there?

**Comment by dasMulli** [comment]
Probably related to: https://github.com/dotnet/coreclr/issues/5853, https://github.com/dotnet/cli/issues/2727
For 2.0, there are now `Linux X64 (for glibc based OS)` binaries available, but afaik no CLI + runtime packages.

**Comment by diegobfernandez** [comment]
@livarcocc I didn't know about that repo.
I found this issue dotnet/core-setup#627. I will suggest there to use Flatpak as default linux installer.
