### ISSUE TITLE
Implicit cs globbing not working?

### ISSUE THREAD

**Issue by roji** [dotnet/cli#5455]
[According to this article](https://blogs.msdn.microsoft.com/dotnet/2016/12/12/updating-visual-studio-2017-rc-net-core-tooling-improvements/), it should be OK to omit the `<Compile Include="**\*.cs" />` from the new csproj format.

However, executing `dotnet new` produces a csproj that includes the explicit glob. Build the assembly doesn't seem to include any source files - inspecting the resulting dll with DotPeek shows an empty assembly.

This may a documentation issue, or an actual issue in the implicit globbing not being applied.

Output of `dotnet --info`:
```
C:\projects\test\A>dotnet --info
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by livarcocc** [comment]
You need a newer version of the CLI go leverage that. You can get the latest from the CLI github page.

**Comment by roji** [comment]
OK thanks. The odd thing is that another feature announced in the same post - specifying dependency versions as attributes rather than nested elements - does work.

Maybe consider amending the article to help avoid the confusion...
