### ISSUE TITLE
Solution migrate command should preserve byte-order-mark

### ISSUE THREAD

**Issue by am11** [dotnet/cli#5458]
## Steps to reproduce

```powersehll
git clone https://github.com/MaxMind/GeoIP2-dotnet
cd GeoIP2-dotnet
git checkout db28172

dotnet migrate GeoIP2.sln

git diff GeoIP2.sln
```

yields:

```diff
-<U+FEFF>
+
```

## Expected  behavior

Preserve the BOM: `GeoIP2.sln` has the BOM, `dotnet-migrate <sln>` should not remove it. Conversely, it should not add the BOM, if the SLN file does not contain it.

## Actual behavior

💣 was removed

## Environment data
`dotnet --info` output:

```powershell
.NET Command Line Tools (1.0.0-rc4-004612)

Product Information:
 Version:            1.0.0-rc4-004612
 Commit SHA-1 hash:  41123fadaa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Users\Adeel\Source\Repos\GeoIP2-dotnet\cli\sdk\1.0.0-rc4-004612
```

**Comment by am11** [comment]
@jgoshi, here are few extension methods for detection:

```c#
private static readonly byte[] _bomBytes = Encoding.UTF8.GetPreamble();
private static readonly string _bomString = Encoding.UTF8.GetString(_bomBytes);

// bytes[] overload
public static bool HasBom(this byte[] subject) =>
    subject != null && subject.Length > 2 &&
    subject[0] == _bomBytes[0] && subject[1] == _bomBytes[1] && subject[2] == _bomBytes[2];

// OR if we have System.Linq referenced
// public static bool HasBom(this byte[] subject) =>
//     subject != null && subject.Take(_bomBytes.Length).SequenceEqual(_bomBytes);

// string overload
public static bool HasBom(this string subject) =>
    subject != null &&
    CultureInfo.InvariantCulture.CompareInfo.IsPrefix(subject, _bomString, CompareOptions.Ordinal);
```

**Comment by livarcocc** [comment]
What are the practical impacts of not having this in the sln file?

**Comment by am11** [comment]
@livarcocc, it has minor impact: some applications, such as notepad, recognize the UTF8-ness of file based on presence of BOM. Stripping the BOM sets the encoding to default (ANSI) in notepad. Besides, it gives the unrelated/unwanted diff.

**Comment by krwq** [comment]
@livarcocc If we are always adding BOM then it should be fine (and if something worked before and doesn't now then it was just a pure luck) - if we are removing it then this can cause errors when any of the csproj files have special characters in the name.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#31
