### ISSUE TITLE
dotnet-install.ps1 doesn't run into the Azure Web App sandbox

### ISSUE THREAD

**Issue by davidebbo** [dotnet/cli#5459]
## Steps to reproduce

- Copy `dotnet-install.ps1` into an Azure Web App using Kudu Console, into some folder
- Run `.\dotnet-install.ps1 -installDir Test2`

## Result

It blows up because of the [Get-CimInstance call](https://github.com/dotnet/cli/blob/56d80713614ba60c51c8da88ed39b6c97bd1b28e/scripts/obtain/dotnet-install.ps1#L420-L424) used for checking disk space, which doesn't agree with the [sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox).

```
Get-CimInstance : Access is denied.
At D:\home\tmp\dotnet-install.ps1:420 char:9
+ $free = Get-CimInstance -Class win32_logicaldisk | where Deviceid -eq
"$((Get-It ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (root\cimv2:win32_logicaldisk: String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070005,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
 ```

In addition, after removing this, it blows up because of the `Write-Host` call, also not sandbox friendly.

## Suggestions

- Make the disk check optional. In this day and age, I don't think many people are in a situation where they don't have 250MB free!
- Change `Write-Host` to `Write-Output`

**Comment by johnbeisner** [comment]
Similar: https://github.com/dotnet/cli/issues/4648

**Comment by johnbeisner** [comment]
This was mitigated with PR: #6664
