### ISSUE TITLE
dotnet-publish --runtime RID always uses host os corehost

### ISSUE THREAD

**Issue by teodimache** [dotnet/cli#546]
Hi,

I'm on a Windows 8.1 machine and trying to publish for osx.10. I've installed the latest dotnet tools via dotnet-win-x64.latest.msi.
When running dotnet-publish --framework dnxcore50 --runtime osx.10.10-x64 it runs fine, i get a dnxcore50\osx.10.10-x64\ folder with all the dll's and dylib as expected and a AppName.exe file. And as you probably guessed the exe file is just the windows corehost.exe, same thing if i publish for ubuntu. Basically it always uses the host os corehost.

If i publish from a mac the same bug manifests itself, i get a mac corehost if i target win7-x64.

Is this a known bug, are there any workarounds?
Thanks

**Comment by shahid-pk** [comment]
one work around is manually copying corehost from the package.

**Comment by blackdwarf** [comment]
@teodimache yes the cross-publishing story is not there yet.

**Comment by piotrpMSFT** [comment]
This is fixed.

**Comment by teodimache** [comment]
Good to know, thanks!
