### ISSUE TITLE
Migration: Does not handle compile builtIns

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5467]
See attached project for a repro.

[CompileBuiltIns.zip](https://github.com/dotnet/cli/files/731645/CompileBuiltIns.zip)

"buildOptions": {
        "compile": {
            "builtIns": {
                "include": [ "../IncludeThis.cs", "Program.cs" ]
            }
        }
    }

The presence of the "builtIns" means the default **/*.cs filter no longer applies. So you need to explicitly include the files you want to compile. This would be the same as the "builtIns" for other things like embed, etc. Since migration doesn't handle this properly, the build breaks.

**Comment by jgoshi** [comment]
When this is fixed re-enable this test:
WhenMigratingAProjectWithDeprecatedCompileBuiltInOptionsItSucceeds

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#30
