### ISSUE TITLE
Versioning Questions

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#547]
_From @Fosol on December 4, 2015 15:26_

I used to use MsBuild.Community.Tasks to automate versioning.  It doesn't appear to work anymore.  Is this because the move to project.json?

I noticed that in new projects (since update 1) that Class Libraries now include an AssemblyInfo.cs.  How does this work along side the project.json file?  Is there a connection?

I'm missing the connection between Class Library build versioning and NuGet package versioning.  Is there a connection, or are they entirely separate concerns?

How is anyone performing MsBuild Tasks against these new projects?

_Copied from original issue: aspnet/dnx#3231_

**Comment by muratg** [comment]
_From @davidfowl on December 5, 2015 17:43_

> I used to use MsBuild.Community.Tasks to automate versioning. It doesn't appear to work anymore. Is this because the move to project.json?

Yes. I assume you're hooking an msbuild event that no longer exists? What does the task do and when does it run?

> I noticed that in new projects (since update 1) that Class Libraries now include an AssemblyInfo.cs. How does this work along side the project.json file? Is there a connection?

Just like it used to work. If you use an AssemblyInfo file with attributes, those will be used instead of the `project.json` information. 

You can think of the project.json as a nuspec.

**Comment by muratg** [comment]
_From @Fosol on December 7, 2015 18:36_

I have a number of custom tasks.  
One of them is supposed to automate versioning prebuild, but it no longer works with the new project.json files.  

Another after build copies the nugget packages to a local share so our internal NuGet Package server has access to it.

Another aftercleanup does additional cleaning.

At some point I'll add DNX commands to the list.

Question - If the AssemblyInfo file is used instead of project.json does this mean that NuGet package that is published will use it instead of the project.json?  I suspect it doesn't which means I would need to update version information in two places in the future.

**Comment by piotrpMSFT** [comment]
AssemblyInfo.cs is supported in CLI.
