### ISSUE TITLE
Migration: we cannot migrate the deprecated namedResource option

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5471]
See the attached project as a sample:
[NamedResource.zip](https://github.com/dotnet/cli/files/733226/NamedResource.zip)

For project.json, if you have a statement like this:
"namedResource": { "Test.Named.Resource": "Resources/Strings.resx" },

It means in your source code you can reference it like this:
var resourceManager = new ResourceManager("Test.Named.Resource", thisAssembly);

I don't know what we can do for migration to support this. Currently we fail migration if this deprecated feature is used.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#29
