### ISSUE TITLE
dotnet migrate does not handle project.json embed behavior of the compiler/resources folder

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#5477]
## Steps to reproduce
- Download: [CompilerEmbeddedResources.zip](https://github.com/dotnet/cli/files/734037/CompilerEmbeddedResources.zip)
- cd src/ProjectA
- `dotnet restore`
- `dotnet build`

// Note that if you look at the dll at this point the ShouldBeEmbedded.cs is embeded:
![image](https://cloud.githubusercontent.com/assets/2008729/22357055/91e578d6-e3ea-11e6-9a25-1ea9e0fa9e0e.png)

- cd ../../
- Remove the sdk from global.json
- `dotnet migrate`
- cd src/ProjectA
- `dotnet restore`
- `dotnet build`

## Expected  behavior
- Compilation succeeds just as it did in project.json land.

## Actual behavior
```
compiler\resources\ShouldBeEmbedded.cs(5,13): error CS0116: A namespace cannot directly contain members such as fields or methods [C:\Users\nimullen\Documents\GitHub\TEMP\src\ProjectA\ProjectA.csproj]
compiler\resources\ShouldBeEmbedded.cs(5,13): error CS0548: '<invalid-global-code>.CSharp': property or indexer must have at least one accessor [C:\Users\nimullen\Documents\GitHub\TEMP\src\ProjectA\ProjectA.csproj]
compiler\resources\ShouldBeEmbedded.cs(5,5): error CS0246: The type or namespace name 'INVALID' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\nimullen\Documents\GitHub\TEMP\src\ProjectA\ProjectA.csproj]
```

## Notes
Another way you could solve this issue is re-implementing the compiler/resource behavior but I don't feel like that'd be the better than just handling this scenario in `dotnet migrate`.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004616)

Product Information:
 Version:            1.0.0-rc4-004616
 Commit SHA-1 hash:  56d8071361

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\nimullen\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004616
```

**Comment by livarcocc** [comment]
@NTaylorMullen Migration only looks at your project.json when determining transformation and only apply transformation to your csproj.

What is your suggestion to handle this during dotnet migrate?

**Comment by NTaylorMullen** [comment]
If there is a `compiler/resources` folder in the same directory as the project.json then have the csproj embed `compiler/resources/**`.

**Comment by livarcocc** [comment]
You mean generate a <EmbeddedResources Include="compiler/resources/**" />?

**Comment by NTaylorMullen** [comment]
@livarcocc yes.
