### ISSUE TITLE
resx resources get embedded with the wrong resource identifier if the project's default namespace differs from the project name

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#548]
_From @oliverw on December 1, 2015 9:27_

The compiler currently embeds resx resources with the wrong resource identifier if the project's default namespace differs from the project name.

**Scenario:**

- Project Name: `ConsoleApp1`
- Default Namespace: `ConsoleApp`
- Resource Name: `Resource.resx`

**Expected behavior:**

The resource would be embedded as `ConsoleApp.Resource.resources`

**Actual behavior:**

The resource is embedded as `ConsoleApp1.Resource.resources`

This is especially bad as Designer.cs files generated from .resx resources use the correct identifier when instantiating the resource manager resulting in `MissingManifestResourceException`s thrown at runtime when accessing any of the generated properties.

[Link to demo project](https://onedrive.live.com/redir?resid=754261B3C2015CB0!95771&authkey=!AOguho3aeJSbV3g&ithint=file%2czip)

**Remark:** Since I'm not sure who is to blame here I've also created an identical issue in aspnet/tooling: https://github.com/aspnet/Tooling/issues/311

_Copied from original issue: aspnet/dnx#3219_

**Comment by cesarbs** [comment]
You can work around this by adding the following to project.json:

    "namedResource": {
      "ConsoleApp.Resource": "Resources.resx"
    }

**Comment by michael-x** [comment]
@cesarbs thanks for the hint with the workaround. Unfortunately it doesn't work, if your resource file name is only two characters.
```
"namedResource": {
  "ConsoleApp.SR": "SR.resx"
}
```
will not embed the resource, probably thinking that SR is a language tag. Might be related to aspnet/dnx#2976. I guess this is what @Eilon calls an offending file, even if SR (short for String Resources) has been used for ages and spelled with uppercase characters should not be confused with language tags which use lowercase characters (where 'sr' is the language code for Serbian).

**Comment by piotrpMSFT** [comment]
Closing as the duplicate https://github.com/aspnet/Tooling/issues/311 has been closed as fixed.

**Comment by fubar-coder** [comment]
This is not fixed yet (preview 2). The workaround with "namedResource" isn't usable when you have hundreds of embedded resource files.

**Comment by fubar-coder** [comment]
@piotrpMSFT It's not fixed. A solution would be nice.
