### ISSUE TITLE
build doesn't honour conditional RID when creating project.assets.json

### ISSUE THREAD

**Issue by djfr** [dotnet/cli#5484]
Building won't honour conditional RIDs inside the csproj file, project.assets.json will always have the first one declared, thus failing build with several bad references if the second one is targeted.

## Steps to reproduce

Add a conditional RID to the csproj:
```
  <PropertyGroup Condition=" '$(Configuration)'=='Debug' ">
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)'=='Release' ">
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>
```

## Expected  behavior

In Debug project.assets.json has 

```
    "runtimes": {
      "win7-x86": {
        "#import": []
      }
    }
```

And in Release

```
    "runtimes": {
      "win7-x64": {
        "#import": []
      }
    }
```

## Actual behavior

In Release project.assets.json has

```
    "runtimes": {
      "win7-x86": {
        "#import": []
      }
    }
```

While build is targeting the RID win7-x64, so build fails with several bad references.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004578)

Product Information:
 Version:            1.0.0-rc4-004578
 Commit SHA-1 hash:  93a94e652b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004578

**Comment by livarcocc** [comment]
@emgarten

**Comment by emgarten** [comment]
@djfr how are you calling restore here?

Restore evaluates the project in the same way that build does, so if you are passing a configuration property to build you will also need to pass it to restore.

Example:
``dotnet restore /p:Configuration=release``

**Comment by djfr** [comment]
We're using VS2017RC, both building locally, or in a build rig we get the same outcome.
We don't specifically call dotnet restore first. On the build rig we only have VS2017RC, there's no other version installed.

We just do a nuget restore on a clean source folder, then build the solution.

This is the build definition we're using (from the VSTS apis):
[build.zip](https://github.com/dotnet/cli/files/736069/build.zip)

**Comment by dasMulli** [comment]
I'd suggest just adding the following:
```
<RuntimeIdentifiers>win7-x86; win7-x46</RuntimeIdentifiers>
```
That way, nuget should restore both runtimes and build/publish will select one of them based on the configuration.

**Comment by emgarten** [comment]
@dasMulli's suggestion should fix this, restore will generate all possible graphs you need in the project.assets.json file and build can then use the one it needs (assuming build doesn't hit issues now that both RIDs are given).

**Comment by djfr** [comment]
Thanks @dasMulli and @emgarten 

I tried that, but got an error windows back from VS2017RC:

![image](https://cloud.githubusercontent.com/assets/2116066/22395688/3ec67200-e53d-11e6-9aa9-ae38ec1dbf81.png)

> The project 'RouteEngine.WebApi' has encountered an error. You may 
need reload the project after fixing the problem.
>The "HasTrailingSlash" function only accepts a scalar value, but its argument "$(PublishDir)" evaluates to bin\Debug\net462\win7-x86;win7-x64\publish\" which is not a scalar value.
>C:\ Program Files (x86)\Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

To give a bit more detail, this specific ASP.NET Core App, that targets .Net 462, is being deployed into an Azure App Service Environment. The deployment, indenpendently of the App Pool being x86 or x64 will throw BadImageFormatException when loading libuv if it's not x64. Inside Visual Studio, while debugging, it will throw the same if it's not x86, so I wanted to get to a solution where developers don't need to fidle with their csproj file everytime they want to debug and then make sure then don't commit that into a release.

Because the build will always build in release to get to the web deploy package through dotnet publish and a developer will always be in debug, I thought the conditional RID would be a nice fix.

**Comment by dasMulli** [comment]
@djfr I think you put that into the wrong property.. This "works on my machine" :)
```
  <PropertyGroup>
    <TargetFramework>net451</TargetFramework>
    <RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Configuration)'=='Release'">win7-x64</RuntimeIdentifier>
  </PropertyGroup>
```

However, I don't think that you should need this workaround for a problem with deploying to Azure..

**Comment by djfr** [comment]
Thanks @dasMulli !

This worked perfectly, what I was missing since the start was:
`<RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers>`

I also tested a deployment to the Azure ASE and it runs perfectly.

Oddly enough, at home on my laptop I can't debug in x86, which led me to poke around and I have VS options set to use IISExpress 64bit mode and on the IISExpress config I have all app pools running in 64bit, so here I can only debug against win7-x64.

I'll check our dev box configuration on Monday to see what it looks like, it might be that, for now, we just run IISExpress in 64bit with 64bit app pools and just keep everything using the win7-x64 RID.
