### ISSUE TITLE
Failed to migrate XProj project WinStoreDB.Shared

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#5486]
'dotnet migrate -s -p "C:\GitHub\Project\src\Project.Shared" -x "C:\GitHub\Project\Project.Shared.xproj"' exited with error code 1.

**Comment by DustinCampbell** [comment]
Note that this same issue was reported in VS Feedback: https://developercommunity.visualstudio.com/content/problem/2455/xproj-to-csproj-migration-fails.html

**Comment by livarcocc** [comment]
It seems that there already was one issue in the CLI tracking this issue: #4770. And that issue has been closed. So, closing this one too.

**Comment by DustinCampbell** [comment]
Did we every verify this worked?

**Comment by livarcocc** [comment]
The original bug was fixed in November. Given I don't have the originally failing project, I wasn't sure how to validate it.

**Comment by DustinCampbell** [comment]
Got it. I didn't see any linked merges or tags that indicated it was fixed, so I thought I'd ask.
