### ISSUE TITLE
dotnet migrate incorrectly migrates the "warningsAsErrors" option

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#5487]
## Steps to reproduce
1. Start with a project.json with `buildOptions/warningsAsErrors`: true
2. Run `dotnet migrate` 

## Expected  behavior
The migrated project has `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` (https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L78)

## Actual behavior
The migrated project has `<WarningsAsErrors>true</WarningsAsErrors>` which isn't a property that MSBuild seems to use.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc3-004522)

Product Information:
 Version:            1.0.0-rc3-004522
 Commit SHA-1 hash:  4e0b465093

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by DustinCampbell** [comment]
Yeah, it should be <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
