### ISSUE TITLE
.NET Core 1.1 on Mac: dotnet new -t web creates a project.json referencing 1.0.0 dependencies

### ISSUE THREAD

**Issue by aspnetde** [dotnet/cli#5491]
## Steps to reproduce

1. [Download](https://www.microsoft.com/net/download/core#/current) the .NET Core 1.1 SDK installer for macOS x64 (https://go.microsoft.com/fwlink/?LinkID=835011 => _dotnet-dev-osx-x64.1.0.0-preview2-1-003177.pkg_).
2. Install .NET Core as described [here](https://www.microsoft.com/net/core#macos).
3. Open Terminal and add a new web app with `dotnet new -t web`

## Expected  behavior

Getting a project.json file with 1.1.0 references.

## Actual behavior

Getting a project.json file with 1.0.0 references

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
```

`dotnet` output:

````
Microsoft .NET Core Shared Framework Host

Version  : 1.1.0
Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

**Comment by livarcocc** [comment]
This is by design. The version of the SDK that you installed ships with the 1.1 runtime. Therefore it's templates target 1.1 runtime. If they targeted 1.0, there was no guarantee that they would be runnable in your box.

The latest versions of the SDK now ship with both 1.0.3 and 1.1.0 versions of the runtime.

**Comment by aspnetde** [comment]
> Therefore it's templates target 1.1 runtime.

No. They target 1.0.0 – as described above.

**Comment by aspnetde** [comment]
@livarcocc – would you consider reading again? Thanks 😃

**Comment by livarcocc** [comment]
Ah true, but that was also a decision that the ASP.NET team made. To ship all templates for LTS.

By the way, sorry, too many things going on lately.

**Comment by aspnetde** [comment]
No problem – thanks for clarifying!

**Comment by Misterhex** [comment]
hi, first timer here as well. i'm having a similar issues as described above, how can i create a 1.1.0 project with the new csproj?

**Comment by piotrpMSFT** [comment]
@Misterhex first install the latest CLI from the home page of this repo

You can then run `dotnet new` to see the full list of in-box templates
For each template, you can run `--help` to see the options it supports
As an example, `dotnet new mvc --help`:
```
MVC ASP.NET Core Web Application (C#)
Author: Microsoft
Options:
  -au|--auth           The type of authentication to use
                           None          - No authentication
                           Individual    - Individual authentication
                       Default: None

  -uld|--use-local-db  Whether or not to use LocalDB instead of SQLite
                       bool - Optional
                       Default: false

  -f|--framework
                           netcoreapp1.0    - Target netcoreapp1.0
                           netcoreapp1.1    - Target netcoreapp1.1
                       Default: netcoreapp1.0
```

So if you wanted an mvc application, you'd run `dotnet new mvc --framework netcoreapp1.1`

**Comment by inmallinath** [comment]
dotnet new mvc --help does not provide the option to choose a framework. I tried downloading the latest sdk and it does not provide this option. I am using 2.0.0-preview1-005685 build.

**Comment by livarcocc** [comment]
can you run dotnet --info and share the output of that command here?
