### ISSUE TITLE
Compilation errors from MSBuild are not redirected to stderr

### ISSUE THREAD

**Issue by jamesqo** [dotnet/cli#5497]
## Steps to reproduce

1. Create a project using `dotnet new`
2. Modify the C# file so that it won't compile (e.g. make a typo)

## Expected behavior

When running `dotnet publish >NUL`, the console output should still contain errors that occur during compilation, because those should be printed to stderr.

## Actual behavior

Errors are silenced by redirecting stdout to NUL.

```
C:\Users\james\Code\tests\Dotnet>dotnet publish >NUL

C:\Users\james\Code\tests\Dotnet>dotnet publish
Microsoft (R) Build Engine version 15.1.458.808
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,13): error CS0103: The name 'Run' does not exist in the current context [C:\Users\james\Code\tests\Dotnet\Dotnet.csproj]

C:\Users\james\Code\tests\Dotnet>
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275
```

**Comment by blackdwarf** [comment]
I think this should be moved to Microsoft/MSBuild, since the fix for this would actually go there.

**Comment by rainersigwald** [comment]
Dupe of https://github.com/dotnet/cli/issues/4910, where we had some discussion but didn't really settle anything.

Note that you can accomplish this without redirection using MSBuild's log configuration, say

```
dotnet build /nologo /consoleloggerparameters:ErrorsOnly
```

**Comment by piotrpMSFT** [comment]
Closing dupe of #4910
