### ISSUE TITLE
Clarification - what are the `.cliversion` and `.toolversions` files in the repo root?

### ISSUE THREAD

**Issue by FLGMwt** [dotnet/cli#5508]
I'm trying to figure out as much as I can about the cli repo.

I noticed that the `.cliversion` and `.toolversions` files haven't been touched in a while and I can't find any reference to them in current source (1.0.0 or rc3).

Do they still affect anything CI-related? If they do, can I document this?

EDIT: Ah, just kidding, I see they're referenced in the `https://raw.githubusercontent.com/dotnet/buildtools/master/bootstrap/bootstrap.ps1` which `run-build.ps1` pulls in. 

Should the values in these files be updated to more current versions?

**Comment by piotrpMSFT** [comment]
@FLGMwt these files are used with the cross-repo `build_tools` project. CLI doesn't currently make much use of build_tools, but expects to start taking advantage of it in the 2.0.0 timeframe. It would likely be opportune to clean these out for the time being, but we want to minimize churn in the 1.0 end-game.

**Comment by FLGMwt** [comment]
Got it. Thanks for the context!
