### ISSUE TITLE
Copy runtime libraries from references project

### ISSUE THREAD

**Issue by oryol** [dotnet/cli#5511]
I have Library.csproj with following code:
`<ItemGroup>
    <Content Include="runtimes\win7-x86\native\**\*">
      <PackagePath>.</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>`

When I run dotnet pack, I can see native dll-s in the generated package.
If I reference this NuGet package (using my own feed) in the another project then all libraries are correctly placed into bin folder. But if I reference this project directly then libraries are not copied.

We need to have one uniform way to add native libraries into project and use them in all scenarios:

- Directly in this project
- In other project that references this project
- In the generated NuGet package

**Comment by piotrpMSFT** [comment]
this belongs in `dontet/sdk`

**Comment by piotrpMSFT** [comment]
Moved to SDK repo. Since the CLI just invokes msbuild in this scenario, and we'd really want the same behavior across CLI and VS, we'll get better traction in that repo.
