### ISSUE TITLE
RPMs have insufficiently defined requirements

### ISSUE THREAD

**Issue by volviq** [dotnet/cli#5512]
## Steps to reproduce
Install a fresh Fedora distribution.
Download Centos RPM from: https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-alpha.15
Install the rpm with 
yum install [rpm name]
## Expected  behavior

- yum installation pulls in dependencies and installs them before extracting the downloaded rpm
- In case it doesn't find depending pacakges, installation fails
- running "Powershell" leads to a working powershell instance

## Actual behavior
"Failed to initialize CoreCLR, HRESULT: 0x80131500"

## Environment data
`dotnet --info` output:

dotnet is not installed. This should be clearly shown by the rpm package installation if dependencies are verified correctly.

After installing dotnet for Fedora23 I get the following message:

```
dotnet --info 
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     fedora
 OS Version:  23
 OS Platform: Linux
 RID:         fedora.23-x64

```

See #1882 for similar errors.

**Comment by piotrpMSFT** [comment]
@volviq this issue belongs in the PowerShell repo. CLI is another consumer of the CoreCLR, but the RPMs for PowerShell are not produced here.
