### ISSUE TITLE
After installing standalone RC3 binaries, VS2015 compilation fails

### ISSUE THREAD

**Issue by maartenba** [dotnet/cli#5514]
## Steps to reproduce

* Have a working VS2015 + .NET Core.
* Install RC3 standalone (https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md).
* Compile project that worked fine before, be greeted with errors.

## Expected  behavior

Succesful compilation.

## Actual behavior

Compile error:

```Error	MSB4019	The imported project "C:\Program Files\dotnet\sdk\1.0.0-rc3-004530\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk```

**Comment by gortok** [comment]
You should be able to make that directory manually and pull over the Microsoft.DotNet.Props file from the previous installation path. Sucks, but it would work.

**Comment by dasMulli** [comment]
VS 2015 is only supposed to work with `preview2-*` (incl. `preview2-1-*`) versions of the CLI.
The MSBuild-based versions (e.g. `rc3`) are only supported by VS 2017.

Too keep existing projects using a `project.json` file working in VS 2015 even if a newer version of the CLI or VS are installed, you'll need to add a `global.json` file your solution's directory that specifies the exact version of the CLI to use. [This document](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md) might help you.

**Comment by maartenba** [comment]
Let me give that a try. Would that also mean I have to copy the .Props file in place? As after the RC3 (again, standalone, no VS2017 on machine) it did not seem to exist anymore. To be continued :-)

**Comment by dasMulli** [comment]
> Would that also mean I have to copy the .Props file in place? 

No, you shouldn't need to do that.

**Comment by piotrpMSFT** [comment]
Yea, this should be fixed by @dasMulli's advice. I'll leave this open for a day or two, but there's nothing else we can do for this scenario.

**Comment by maartenba** [comment]
No VS2017; VS2015 + latest (RC2) tooling installed: project compiles.
Same environment, RC3 standalone tooling installed: project does not compile (error same as in issue opening post)

Adding `global.json` indeed fixes the issue (https://github.com/maartenba/CamoDotNet) - I guess this issue can be closed.

**Comment by piotrpMSFT** [comment]
Glad the global.json helped. This issue is likely the biggest pain point we've faced in the project.json->csproj migration to date. Unfortunately by the time the CLI figures out that another version is needed for working with a project.json-style project... a later version is already loaded and it's too late.
