### ISSUE TITLE
Cannot have the same filename in files.mappings for project.json

### ISSUE THREAD

**Issue by jaymedavis** [dotnet/cli#5515]
## Steps to reproduce
Create a project for packing. Use this in project.json - note: the filenames have to match.
```
  "packOptions": {
   
   ...

    "files": {
      "mappings": {
        "lib/netstandard1.6/": {
          "include": [ "./Checkout.dat" ]
        },
        "lib/net452/": {
          "include": [ "./Checkout.dat" ]
        }
      }
    }
  }
```

## Expected  behavior
The file will be included to both directories in the build output. 

## Actual behavior
It only copies the LAST mapping if the filename is the same. If I were to specify another filename for the second mapping, say "blah.dll", it would work. It seems to be an issue with having the same filename

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
We don't have plans for further servicing updates to the project.json CLI. Please try downloading the latest CLI from the home page of this repo. Run the `dotnet migrate` command on your solution to migrate to csproj, and open a new issue if you still see a problem.

**Comment by jaymedavis** [comment]
I fixed this for anyone passing by. I just put a lib folder in the root and included the whole folder - with the right file structure as the nuget package.

@piotrpMSFT thanks. Sorry if I've been in a hole, but is the xproj structure being phased out? Any links would help - appreciate your time. I have some open source projects I should probably convert as well.

**Comment by piotrpMSFT** [comment]
Thanks for following up, @jaymedavis
