### ISSUE TITLE
Global verbose flag isn't recognized

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5516]
## Steps to reproduce
`dotnet --verbose build`

## Expected  behavior
Build with verbose output.

## Actual behavior
Unknown option: --verbose

## Environment data
`dotnet --info` output:

1.0.0-rc3-004530

**Comment by livarcocc** [comment]
The format for this command is `dotnet build --verbose`.

**Comment by natemcmaster** [comment]
That's not the "global" verbose flag. In preview 2, `dotnet --verbose subcommand` flowed verbVerb context to all subcommands and would set CommandContext.Variables.Verbose. Is this not supported anymore?

**Comment by livarcocc** [comment]
That's -d now, as explained in help. The --verbose in under common-options, which comes after command.

```
.NET Command Line Tools (1.0.0-rc4-004709)
Usage: dotnet [host-options] [command] [arguments] [common-options]

Arguments:
  [command]             The command to execute
  [arguments]           Arguments to pass to the command
  [host-options]        Options specific to dotnet (host)
  [common-options]      Options common to all commands

Common options:
  -v|--verbose          Enable verbose output
  -h|--help             Show help

Host options (passed before the command):
  -d|--diagnostics      Enable diagnostic output
  --version             Display .NET CLI Version Number
  --info                Display .NET CLI Info
```

**Comment by natemcmaster** [comment]
cc @mikeharder
