### ISSUE TITLE
dnu pack should pass developmentDependency from project.json into the .nuspec file

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#552]
_From @bradwilson on November 14, 2015 19:50_

The DNX runner (among other things) should be considered a development dependency in NuGet terms. This is a valid value in the .nuspec file as of NuGet 2.8, but project.json doesn't seem to respect it or pass it through into the generated .nuspec file.

Related: xunit/xunit#667

_Copied from original issue: aspnet/dnx#3172_

**Comment by muratg** [comment]
_From @bradwilson on November 14, 2015 19:51_

Example: https://github.com/xunit/dnx.xunit/commit/bbafa29c1ef39d1c8d7174613c4cf2163b7b30dd

**Comment by muratg** [comment]
_From @davidfowl on November 14, 2015 21:43_

While I agree this should be supported (in some form), why would you need it? Who is using the dnx xunit package in this way?

**Comment by muratg** [comment]
_From @bradwilson on November 15, 2015 2:16_

I was doing it for completeness (marking all the runners with this flag) at the request of a user.

**Comment by muratg** [comment]
_From @davidfowl on November 15, 2015 16:31_

That's what I thought 😀

**Comment by muratg** [comment]
@davidfowl I hear pack is moving to nuget, not CLI.  Will talk to @yishaigalatzer later.

**Comment by piotrpMSFT** [comment]
dotnet pack will be replaced by nuget pack.

**Comment by patriksvensson** [comment]
So there is currently no way at all of setting `developmentDependency` in project.json?

**Comment by bradwilson** [comment]
Now that we have `dotnet` instead of `dnu`, I'm back to building my NuGet packages with hand-rolled `.nuspec` files, so my need for this is gone (though it should realistically be done).

**Comment by patriksvensson** [comment]
@bradwilson Thanks for answering. I guess I will have to do the same and use hand-rolled `.nuspec` files.
