### ISSUE TITLE
dotnet add package should allow --version to be anywhere in cli

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/cli#5521]
## Steps to reproduce
`> dotnet add . package Microsoft.AspNetCore.Mvc -v 1.1.0`
Doesn't work
`> dotnet add . package -v 1.1.0 Microsoft.AspNetCore.Mvc`
Works.

## Expected  behavior
Shouldn't matter (as version after package name makes more sense)
Prefer to actually allow just version number after the package name without a flag
`> dotnet add . package Microsoft.AspNetCore.Mvc 1.1.0`
With version # being optional

## Actual behavior
Flag position matters

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530
```

**Comment by piotrpMSFT** [comment]
@shawnwildermuth please update to a newer CLI [home page of this repo, or latest VS RC]. This was fixed in #5296

**Comment by shawnwildermuth** [comment]
This is after that update...no? I just updated VS2017 to the latest. Should I install the CLI separately?

**Comment by piotrpMSFT** [comment]
If you want to validate the fix prior to the next public release of VS2017, yea, you can install CLI separately. This was fixed after RC3.
