### ISSUE TITLE
DotNetCliToolReference doesn't import targets.

### ISSUE THREAD

**Issue by olydis** [dotnet/cli#5522]
## Steps to reproduce
We have a tool that's referenced by `DotNetCliToolReference`.
It installs correctly and will run from the command line.
When it installs, however, it does not put references to the `.targets` file in the tool package (into the `.g.targets` file).
We had to put a package reference in as well.
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-razor" Version="1.0.0" />
    <PackageReference Include="dotnet-razor" Version="1.0.0" /> <!-- I shouldn't have to do this -->
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
</Project>
```

## Expected  behavior
The generated `.g.targets` file should have references to the targets of the referenced `DotNetCliToolReference`.

## Actual behavior
Does not add things to the generated `.g.targets` file.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004707)

Product Information:
 Version:            1.0.0-rc4-004707
 Commit SHA-1 hash:  5aded80a7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004707
```

**Comment by livarcocc** [comment]
If you have that tool as both a tool and a project dependency (package dependency), you have to explicitly add it.

Dependencies in your package dependencies will ship with your application and not all tools (the majority) are needed to run the application.
