### ISSUE TITLE
Ensure dotnet new web and dotnet migrate does not include a runtimeconfig.template.json file to set Server GC

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/cli#5526]
Now that the SDK supports enabling Server GC via an MSBUILD property we need to ensure the templates and migrate output don't drop a runtimeconfig.template.json file in the case they only did so to enable Server GC. The web SDK will be setting this property by default.

**Comment by livarcocc** [comment]
We will check if/who is pulling that file in during migration.

**Comment by livarcocc** [comment]
Migration is moving this file, but it seems that the fix here is to remove the Server GC option from the file before moving it. And, if server GC is the only option, then don't move it at all.

**Comment by jgoshi** [comment]
Actually, migration behavior should remain the same. Because if the user has the Server GC option in their project.json file we should respect it. Migration isn't adding this option. I do need to remove the file from the dotnet new templates though.

**Comment by jgoshi** [comment]
@DamianEdwards What if the project.json file explicitly adds that option in (either explicitly setting it to true or false). Do we still want migration to remove it? Also which versions of Web sdk and other dependencies do we need to use? Does CLI need to update to ensure we still have GC on by default even after I remove things from the template/migration?

**Comment by MattGertz** [comment]
Peter sez this is ready to come today, so approving to bring to Shiproom.
