### ISSUE TITLE
migration didn't remove targe PrepublishScript

### ISSUE THREAD

**Issue by ravipal** [dotnet/cli#5527]
## Steps to reproduce
In VS 2015 Update 3, install Service Fabric Tools for VS 2015 - https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started
Create a new Service Fabric application project. New Project -> Cloud -> Service Fabric Application -> ASP.Net Core (Preview). 
Now open this solution in VS 2017 and migrate the projects. *.xproj will be converted to *.csproj
Then Publish the application

## Expected  behavior
Publish should succeed.

## Actual behavior
Publish fails because the *.csproj has the following target, but the bower is not present on the machine.
\<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish"\>
    \<Exec Command="bower install" /\>
    \<Exec Command="dotnet bundle" /\>
  \</Target\>
 

Error	MSB3073	The command "bower install" exited with code 9009.

## Environment data
`dotnet --info` output:
C:\Windows\System32>dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by livarcocc** [comment]
This is by design for migration. We cannot remove those targets/commands because we don't really know the user is not making use of them.

Specially for cross-platform, if that project.json was working for him, then it will continue to work in msbuild, because that means bower is in the user's path.

**Comment by piotrpMSFT** [comment]
Full discussion on this topic happened here: https://github.com/dotnet/cli/issues/5443
