### ISSUE TITLE
Changing LibraryDependencyType in project.json is not working as expected

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#553]
_From @reliak on November 12, 2015 11:55_

I'm trying to achieve something similar to `devDependencies` in NPM (https://docs.npmjs.com/files/package.json#devdependencies).
In project.json I'm setting the LibraryDependencyType of a dependency as follows:
```
"Autofac.Dnx": {
	"version": "4.0.0-alpha2",
	"type": "build"
}
```
The above dependency is only defined in project.json, but not used anywhere in the code of the program.
By setting the type to `build` I expected that this dependency will not be published to the NuGet package, but that is not the case.

Am I doing something wrong?

_Copied from original issue: aspnet/dnx#3159_

**Comment by muratg** [comment]
_From @davidfowl on November 12, 2015 12:5_

If you have a dependency of type build and you do dnu pack, the package produced will not have that dependency. That's all the build flag does.

**Comment by muratg** [comment]
_From @reliak on November 12, 2015 12:15_

Ok, thanks. But what if I want to use a dependency just for preprocessing as part of the build process?
If it is specified in project.json, it will also be published. Is there a way to use a dependency only in development and ignore it otherwise?

I elaborate my use case a bit. Lets say I have a package that I want to call before every build. Then I would define a command like:
```
"commands": {
    "mypackagecommand": "SomePackageName"
}
```
In the prebuild I then want to execute that command:
```
"scripts": {
    "prebuild": [
        "dnx project.json mypackagecommand"
    ]
}
```
So the dependency to `SomePackageName` is only for build purposes.

**Comment by muratg** [comment]
_From @moozzyk on November 12, 2015 17:56_

@reliak - you may want to take a look at what we do in the [Kestrel](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/project.json#L73-L81) repo

**Comment by muratg** [comment]
_From @reliak on November 12, 2015 20:57_

@moozzyk Thanks for the link to the repo.

However, as far as I can tell, the code does not use any dependencies within the scripts block. It only calls `dnx` to a relative project path.

Maybe there is another way for what I'm trying to do, but again, this is my problem:
1. I want to execute some code from a library (e.g. a package from NuGet) in pre- or post-build
2. For that, I need to put this package in the dependencies section in project.json
3. I don't want this dependency treated as a "normal" dependency, but as a dependency that is only required in development/build stage

As I said in my initial comment, this is similar to `devDependencies` in Node package manager (https://docs.npmjs.com/files/package.json#devdependencies).

**Comment by muratg** [comment]
_From @moozzyk on November 14, 2015 1:2_

@reliak - if you look at Kestrel you will see that libuv is a [build dependency](https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNet.Server.Kestrel/project.json#L16-L23). Then the LibuvCopier operates on these package and copies the contents. So, in a sense it is similar to your scenario with one more level of indirection (the LibuvCopier). It was done mostly like this (instead of using a script) because figuring out where the packages were restored is a bit tricky. I realize that you are looking for something easier and working out of the box but I am not sure if it can be done more easily at the moment.

**Comment by muratg** [comment]
_From @reliak on November 14, 2015 8:32_

@moozzyk The build dependency type works as @davidfowl mentioned when using `dnu pack`.
The only think that bothers me, is that `dnu publish` creates a package in the output's `packages` folder.

According to https://github.com/aspnet/Home/wiki/DNX-utility#publish-dnu-publish:
> The packages directory contains all the packages your application needs to run.

a dependency of type `build` should not be in the packages folder, because it is not required by the application.

The additonal (but unnecessary) package in the packages folder is not a big deal, but it would be nice if build dependencies would be excluded when publishing.

**Comment by piotrpMSFT** [comment]
dnu publish is no longer supported.
