### ISSUE TITLE
Build fails looking for xproj in migrated solution

### ISSUE THREAD

**Issue by martincostello** [dotnet/cli#5530]
## Steps to reproduce

Checkout the ```DotNet-Core-With-MSBuild``` branch of ```https://github.com/martincostello/website.git``` and build on Linux and run ```build.sh```.

## Expected  behavior

Script successfully runs, restoring NuGet packages, compiling the website and tests, runs tests and publishes the website.

## Actual behavior

Script fails at ```dotnet restore``` with error ```MSB4025``` (see [Travis build](https://travis-ci.org/martincostello/website/builds/196931334)):

```sh
/home/travis/build/martincostello/website/src/Website/Website.csproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/home/travis/build/martincostello/website/src/Website/Website.csproj.metaproj'.
/home/travis/build/martincostello/website/tests/Website.Tests/Website.Tests.csproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/home/travis/build/martincostello/website/tests/Website.Tests/Website.Tests.csproj.metaproj'.
```

## Environment data

```sh
$ dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)
Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  10b642bc12
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /home/travis/build/martincostello/website/.dotnetcli/sdk/1.0.0-rc3-004530
```

**Comment by dasMulli** [comment]
Looks like you manually changed the xproj to csproj references.. If you do that, you'll also need to change the project type GUID. Newer versions of the CLI should migrate the sln file correctly..
see https://github.com/dotnet/cli/issues/4632 which if i filed a while ago
If `dotnet migrate` didn't replace the reference by default, it is probably a bug..

**Comment by martincostello** [comment]
Thanks, I'll give that another try. I did try migrating the ```.sln``` file in Visual Studio 2017, but it didn't seem to like that...

**Comment by martincostello** [comment]
Yep, that was the problem. I didn't realise that ```dotnet migrate``` could be run on the solution file, so I'd run it on the ```project.json``` files. Then when Visual Studio made a mess of trying to add the new files to the solution I just left it as-is as I didn't think it would make a difference to the package restore.
