### ISSUE TITLE
Unable to install standalone SDK on top of VS2017RC3

### ISSUE THREAD

**Issue by julielerman** [dotnet/cli#5531]
## Steps to reproduce
Install VS2017RC3 via official links.
Download nightly build SDK installer:
![image](https://cloud.githubusercontent.com/assets/5007120/22467013/e13b23c8-e790-11e6-865e-82901f8fbd42.png)
Execute the installer.
Follow prompts:
![image](https://cloud.githubusercontent.com/assets/5007120/22467237/daff6e50-e791-11e6-8d44-3858fcb22307.png)
![image](https://cloud.githubusercontent.com/assets/5007120/22467263/f0590752-e791-11e6-8831-4182f0392d67.png)

## Expected  behavior
The rc4 version of the SDK is installed.

## Actual behavior
Setup fails with a message that I have to uninstall a previous version. 
![image](https://cloud.githubusercontent.com/assets/5007120/22467301/12f7c21c-e792-11e6-8a1a-b429ce58fae5.png)
I uninstall all other versions of dotnet via Uninstall programs. I do this one at  time (newest) and try install again but it fails each time.
The problem persists.
I have no sdk. "dotnet --version" returns dotnet help, not a version number.
Still I continue getting this message.
I have tried a few different ways of installing:

![image](https://cloud.githubusercontent.com/assets/5007120/22467351/4f43ed9a-e792-11e6-8fa4-fb8f3ccbe734.png)

All had the same result.
I tried to install the SDK through the VS installer and still had the same message 

I am currently attempting a Repair via the VS installer. 

## Environment data
`dotnet --info` output:
```
C:\Users\julie>dotnet --info
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

```
Azure WIndows VM
Windows 10 Enterprise N
v 1607
OS 14393.693

**Comment by piotrpMSFT** [comment]
@julielerman are you able to share your log file?

**Comment by julielerman** [comment]
I have two things for you. first, attaching what I hope is a correct log file 


[Microsoft_.NET_Core_1.0.3_-_SDK_RC_4_(x64)_20170130003813.log.txt](https://github.com/dotnet/cli/files/744772/Microsoft_.NET_Core_1.0.3_-_SDK_RC_4_.x64._20170130003813.log.txt)

I thought I would get a new log file for you by running the installer again but had forgotten about that repair  I started yesterday through the VS installer. That had finally completed and succeeded. So when I ran the following sdk update today, it, too succeeded. I have a ton of log files from the other day though since I tried it so many times. I can zip them all up and share if the one I just included is not useful.
![image](https://cloud.githubusercontent.com/assets/5007120/22506413/d17911ec-e845-11e6-9265-b5878d64ddac.png)

**Comment by piotrpMSFT** [comment]
@julielerman I think you may have had a machine in the state described here: https://github.com/dotnet/cli/issues/3371. In short, there was a VC Runtime installer which did not include the detection registry keys expected by CLI. This got fixed up about six months ago, but if you had a machine which hadn't updated VS in quite some time then we would run into this. Since you installed a newer VS between 1st and 2nd attempt, I expect VC was updated in between, resolving the underlying issue. Does that align with what you saw?

**Comment by livarcocc** [comment]
@julielerman since we have not heard back and you seem to be unblock, I am closing this issue.

**Comment by julielerman** [comment]
sorry about forgetting about this.  I moved onto RC4, RTM etc. Thanks! :)
