### ISSUE TITLE
.net core console app does not run with platform set to x86

### ISSUE THREAD

**Issue by sbaid** [dotnet/cli#5532]
## Steps to reproduce
In Visual Studio 2017 Enterprise RC (15.0.26127.0) 
1. Create a C# .NET Core Console app Project. 
2. Change platform to x86. 
3. Ctrl+F5

## Expected  behavior
to run hello world app

## Actual behavior
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'ConsoleApp1.dll'. An attempt was made to load a program with an incorrect format.

## Environment data
`dotnet --info` output:

## Related 
There was [community feedback](https://developercommunity.visualstudio.com/content/problem/15821/test-explorer-fails-to-discover-test-methods-from.html) for test discovery with platform set to x86. The underlying root cause is this. 

Is setting platform = x86 supported for .NET core projects? do we need x86 version of dotnet.exe in that case?

**Comment by piotrpMSFT** [comment]
@sbaid this issue belongs in the dotnet/Roslyn-project-system repo. Your analysis is correct, the x86 CLI is required to run x86 projects. Currently, VS does not offer a mechanism for switching between x86 and x64 CLI and only installs the 'native' CLI for a given platform. Once the right CLI is selected by the IDE, the issue would go away.

As a workaround, folks can install the x86 CLI and `dotnet run` from the command line.

**Comment by nietras** [comment]
@piotrpMSFT could this also explain why it is impossible to run say x86 unit tests with .NET Core on a x64 machine? Simply could not get this working...

**Comment by piotrpMSFT** [comment]
@nietras yes, I expect that's right. Making this scenario work fully in the IDE will take quite a bit of work so we will have to re-visit post 1.0.0. 

@livarcocc as a +1 on the importance of RID-specific F5 + test in VS.
