### ISSUE TITLE
dotnet-migrate on solution file fails even though individual projects succeeded

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5534]
## Steps to reproduce
Git clone https://github.com/aspnet/Antiforgery.git
Checkout https://github.com/aspnet/Antiforgery/commit/cd4afdc08384fe3fd255ae08fd4c62cdd7c3ee32 (before we upgraded)
dotnet migrate Antiforgery.sln

## Expected  behavior
Migrates projects

## Actual behavior
Migrates projects and dies on last step
```
Project Microsoft.AspNetCore.Antiforgery migration succeeded (C:\dev\Universe\Antiforgery\src\Microsoft.AspNetCore.Antiforgery)
Project Microsoft.AspNetCore.Antiforgery.Test migration succeeded (C:\dev\Universe\Antiforgery\test\Microsoft.AspNetCore.Antiforgery.Test)
Project AntiforgerySample migration succeeded (C:\dev\Universe\Antiforgery\samples\AntiforgerySample)
Project Microsoft.AspNetCore.Antiforgery.FunctionalTests migration succeeded (C:\dev\Universe\Antiforgery\test\Microsoft.AspNetCore.Antiforgery.FunctionalTests)
Summary
Total Projects: 4
Succeeded Projects: 4
Failed Projects: 0

Cannot create a file when that file already exists
Migration failed.
```

## Environment data
`dotnet --info` output:
1.0.0-rc3-004530

**Comment by jgoshi** [comment]
This one no longer repros for RTM. We made a fix in RC4 related to where we create the backup folder (which is probably what was causing this failure).
