### ISSUE TITLE
Migration of xproj with name different from folder leaves ref to old project in solution

### ISSUE THREAD

**Issue by bleroy** [dotnet/cli#5538]
## Steps to reproduce

Clone https://github.com/bleroy/core-imaging-playground/
Open a command-line on the /NetCore subdirectory
`dotnet migrate`

## Expected  behavior

Solution contains only reference to the migrated project. Old project files moved to backup.

## Actual behavior

Solution contains references to old (now gone) and new project. Old project has moved to backup.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004689)

Product Information:
 Version:            1.0.0-rc4-004689
 Commit SHA-1 hash:  c740fa8f43

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004689

**Comment by livarcocc** [comment]
This is a good bug @bleroy, though, at this point in the product cycle, and since strictly speaking it does not break anything. You can still restore and build your solution, I don't see his meeting the bar for RTM.

**Comment by piotrpMSFT** [comment]
Agreed. Folks who find this issue through subsequent searches, please do remove the xproj references from your solutions.

**Comment by mairaw** [comment]
We might want to call this out as part of the migration docs.
