### ISSUE TITLE
Per framework file exclude

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#554]
_From @JamesNK on August 22, 2015 1:45_

Right now exclude is for all frameworks. It would be useful to be able to exclude files for certain frameworks on build.

_Copied from original issue: aspnet/dnx#2540_

**Comment by muratg** [comment]
_From @glennc on August 24, 2015 18:3_

I like the idea, but don't think it fits into any of the milestones we have at the moment. So backlog for now.

**Comment by muratg** [comment]
_From @anurse on August 24, 2015 20:45_

As a workaround, and yes I know it's kinda gross, you can wrap the whole file in `#if`

**Comment by muratg** [comment]
_From @JamesNK on August 24, 2015 21:33_

That's what I did. It was just a pain in the butt getting all files working with all frameworks: https://github.com/JamesNK/Newtonsoft.Json/commit/a9ea63da59cc90b474bee5a6f351e9fad55a44bf

Anyway, not blocking.

**Comment by muratg** [comment]
_From @Mpdreamz on September 14, 2015 12:49_

Huge +1 to this, would reduce the number of needed ifdefs.

**Comment by piotrpMSFT** [comment]
This will be addressed in the new project system.
