### ISSUE TITLE
donet publish always updating web.config

### ISSUE THREAD

**Issue by chrisdrobison** [dotnet/cli#5544]
I'm trying a build a web deploy package that will be deployed to a virtual application in IIS. According to your docs, the aspNetCore handler needs to be defined at the site root and the applications themselves only define the aspNetCore element. But, the even though I comment that handler line out, the dotnet publish-iis command always reinserts the following line:

`<add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>`

## Steps to reproduce
1. Comment out handler line in web.config
2. Run publish

## Expected  behavior
Don't insert something I have commented out

## Actual behavior
Inserts something I want commented out.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
@mlorbetske @danroth27 can you guys help me route this issue?

**Comment by piotrpMSFT** [comment]
Also, so folks don't get confused, this issue is filed against the preview2 [project.json] product, not the current 1.0.0-rc3 product.

**Comment by vijayrkn** [comment]
This is where the handler is getting added - https://github.com/aspnet/websdk/blob/dev/src/Publish/Microsoft.NETCore.Sdk.Publish.Tasks/WebConfigTransform.cs#L38-L55

This does not check for a specific section is commented out in the original web.config. Can you please move this bug to WebSDK repo - https://github.com/aspnet/websdk

**Comment by mlorbetske** [comment]
Moved to aspnet/websdk#115
