### ISSUE TITLE
dotnet build (preview4) produces empty PE binary

### ISSUE THREAD

**Issue by aensidhe** [dotnet/cli#5547]
## Steps to reproduce

1. Install dotnet-preview4-tools on windows10. x64 version from [here](https://github.com/dotnet/core/blob/master/release-notes/preview4-download.md) using msi.
2. Clone this fork of [YamlDotNet](https://github.com/e-vote/YamlDotNet).
3. Run `dotnet restore YamlDotNet.sln`
4. Run `dotnet build YamlDotNet.sln`

## Expected  behavior

Good binaries produced in output folders. VS2017 RC (RC3 26127.3) produces them somehow.

## Actual behavior

Empty binaries (dlls of size 5 kb) produced. 

[net46.zip](https://github.com/dotnet/cli/files/746042/net46.zip) contains "bad" (actual output) and "good" (expected, produced by VS2017)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by aensidhe** [comment]
Can be closed. VS2017 uses [RC3](https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md)

After upgrade all looks good.

**Comment by aensidhe** [comment]
Still have questions:
- Should I pin sdk number in global.json?
- If yes, should I do it on build level of version or some other?

**Comment by piotrpMSFT** [comment]
VS2017 doesn't actually use CLI for most code paths. We share implementation at the SDK MSBuild target level. Given this change, we are not actively recommending pinning CLI in global.json at the moment. That story will be revisited in time for the next side-by-side release of the CLI.
