### ISSUE TITLE
unable to discover netcoreapp1.1 tests.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/cli#5548]
I am trying to upgrade my project from project.json to the new csproj format and hitting roadblocks left and right... (https://github.com/exceptionless/foundatio/tree/feature/dotnet)

It appears that VS2017 RC3 (Latest) is unable to discover or run any tests that have either netcoreapp1.0 or netcoreapp1.1.

When I try to run it from the command line I get

```
Test run for C:\Code\Foundatio\test\Foundatio.Tests\bin\Debug\netcoreapp1.1\Foundatio.Tests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: No test is available in C:\Code\Foundatio\test\Foundatio.Tests\bin\Debug\netcoreapp1.1\Foundatio.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

Even more when I try to run with diagnostics
```
dotnet test .\test\Foundatio.Tests\Foundatio.Tests.csproj -v
Index was outside the bounds of the array.
```

but 

```
dotnet test .\test\Foundatio.Tests\Foundatio.Tests.csproj --no-build /v
:diag
```

works but doesn't give me any diagnostics on why it couldn't connect to test host / run tests.

**Comment by niemyjski** [comment]
It seems to be failing to discover net standard 1.0 tests as well :(

**Comment by piotrpMSFT** [comment]
I looked at some of your csproj's and versions + refs look ok. Do you perhaps have an old CLI version?

Regardless, @dotnet/vstest needs to take a look to help us see how we can shore up the UX.

**Comment by niemyjski** [comment]
I shouldn't as I am inside of a fresh vm with a freshly installed VS2017RC3 .03

**Comment by niemyjski** [comment]
If you pull down the repo and switch to the dotnet branch, you may need to add back the netcoreapp1.0 to one or more test projects ( I need to get this working on a ci ASAP)

**Comment by dasMulli** [comment]
fyi i checked out the feature/dotnet branch today and added back `netcoreapp1.0` to `Foundatio.Tests.csproj` and just changed the `xunit.assert` package reference to `xunit` and then it worked.. it then also worked for `netcoreapp1.1` (only tested in command line, not VS)

**Comment by niemyjski** [comment]
Thanks for this, shouldn't xunit be picked up as a transitive package?

**Comment by dasMulli** [comment]
I couldn't find any noticeable difference in the built output except for the xunit metapackage appearing in `deps.json`.
Even tough `xunit` appears to just be a meta-package, it seems to be required in order for test discovery to work.
Since you split `xunit.core` and `xunit.assert` packages across the logger project (p2p referenced) and the test project itself, the resulting dependencies are identical to the following test project which also doesn't discover tests:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170123-02" />
    <PackageReference Include="xunit.assert" Version="2.2.0-beta5-build3474" />
    <PackageReference Include="xunit.core" Version="2.2.0-beta5-build3474" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
  </ItemGroup>

</Project>
```

I'm unsure if this is expected or an issue with either vstest or the xunit test runner.

**Comment by niemyjski** [comment]
Yeah I added xunit and now it works so some kind of issue here

**Comment by piotrpMSFT** [comment]
I moved this to the microsoft/vstest repo. 

Diagnostics are a bit tough here, given the test platform's intent to be generic to many test frameworks. However, we need to do something. @livarcocc and I have already gone through a few sessions of "Start with `dotnet new xuint` and then add back until we find what was broken in the original project".
