### ISSUE TITLE
unable to find my own library  dependency

### ISSUE THREAD

**Issue by darkgem666** [dotnet/cli#5549]
Hi, I'm having problems when I Crete 2 separated projects and one of them reference the other.

## Steps to reproduce
1.- create a project A folder and execute dot net new -t lib
2.- dotnet restore
3.- dot net pack
4.- add nuget packet created to packages folder via command nuget add  nugetPack -s nugetPackages
5.- create project B folder and execute dotnet new
6.- Add as dependency nuget package A in project.json of project B
7.- dotnet restored

## Expected  behavior
Able to use project A in project B

## Actual behavior
project B is not able to recognize project A

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64

**Comment by darkgem666** [comment]
still can't get this to work

**Comment by piotrpMSFT** [comment]
@darkgem666 I'm not clear on what the intent is here. Are you trying to do a project-to-project reference? or are you sharing packages across solutions?

If this is a new project, I'd suggest grabbing the latest CLI from the home page of this repo and moving to csproj. It's much easier to describe project references in that format.

**Comment by darkgem666** [comment]
@piotrpMSFT I just try to do it again with the latest CLI and still can seem to get this right, I'm just trying to create a library and use it in other projects via nuget package, I'm not able to reference my library anywhere, friend console app or web app an nothing, and I don't get any error when I add the reference to my library and do a dotnet  restore command.

**Comment by piotrpMSFT** [comment]
@darkgem666 why is referencing via nuget package important to you? This should only be impactful when you ship nuget packages which depend on one another, and that will happen automatically based on your project references when you run `pack`.

Try this with the new CLI:
- make and navigate to a new directory
- mkdir Lib
- cd Lib
- dotnet new lib
- cd ..
- mkdir App
- cd App
- dotnet new Console
- dotnet add reference ../Lib/Lib.csproj
- dotnet run [this will run your app]
- cd ../Lib
- dotnet pack [this will create a nuget package]

I know this won't be everything you're looking for, but it should get you close. Let's figure out the remaining gaps!

**Comment by livarcocc** [comment]
Since we haven't heard back in a few days, and we haven't had issues with this scenario in the CLI itself (we do this for our tools), I am going to close this issue.

@darkgem666 Feel free to re-activate with more info if this is still reproing for you with the latest version of the CLI.
