### ISSUE TITLE
project.json net20 - GAC bug

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#555]
_From @JamesNK on August 22, 2015 1:25_

https://github.com/aspnet/dnx/issues/1894#issuecomment-133388423

_Copied from original issue: aspnet/dnx#2539_

**Comment by muratg** [comment]
@davidfowl GAC?  Isn't CLI CoreCLR only?

**Comment by davidfowl** [comment]
No it's .NET

**Comment by piotrpMSFT** [comment]
Closing as the root bug is > 1 yr old. If this is still an issue please open a new bug.
