### ISSUE TITLE
rc3 removed `dotnet nuget pack`

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#5555]
## Steps to reproduce

Maybe is the wrong repo, but it's useful from command line so.

The `preview4` had `dotnet nuget pack` to generate nupkg from a nuspec.
In rc3 the command doesnt exists anymore.

The use case is generate a nupkg with content only, or anyway without a built lib/program

I cannot (AFAIK) use a csproj (i'd like to, instead of author nuspec, one thing less to learn and deps are better) because it always expect and include the build of an assembly.
I tried with `--no-build` but pack fail because expect assemblies anyway.

There is a way to use a csproj like to do packaging only? i tried rename csproj -> proj, but pack expected `GenerateManifest` target.

## Environment data

```
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\dotnetcli\dotnet-dev-win-x64.1.0.0-rc3-004530\sdk\1.0.0-rc3-004530
```

**Comment by darkgem666** [comment]
have you try command 'dotnet pack' ?

**Comment by enricosada** [comment]
@darkgem666 `dotnet pack` build a csproj/fsproj. That mean compile/generate assembly and put assembly generated inside package. i dont want that.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Test.Package</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="build/MyFile.target">
      <PackagePath>.</PackagePath>
      <Pack>true</Pack>
    </Content>
  <ItemGroup>
</Project>
```

nupkg doesnt always contains assemblies (maybe just target files, or content, etc)

**Comment by livarcocc** [comment]
@enricosada I think this belongs in NuGet/Home.

**Comment by enricosada** [comment]
@livarcocc no workaround to use csproj instead of nuspec? i'll move it meanwhile 😄

**Comment by dasMulli** [comment]
looks like there is already one: https://github.com/NuGet/Home/issues/4254

**Comment by enricosada** [comment]
moved as https://github.com/NuGet/Home/issues/4477

**Comment by enricosada** [comment]
thx @dasMulli , closed as dupe.
Also added some comments about us csproj but with `--no-build --no-assemblies` in https://github.com/NuGet/Home/issues/4254#issuecomment-277023306 who can be useful for everyone (no need to lear nuspec sintax, just use csproj/fsproj)
