### ISSUE TITLE
dotnet restore with DotNetCliToolReference causes multiple restores

### ISSUE THREAD

**Issue by jakimber** [dotnet/cli#5556]
I can't see anything obvious in the issues log or stackoverflow already, and not sure if this is by design or not so:

Using the new msbuild .csproj tooling, when i `dotnet restore` my project, the restore happens more than once if i have DotNetCliToolReference entries in my .csproj.

Whilst this is slightly annoying during development, it really slows things down when i publish to Azure (where i wouldn't expect the tools to be restored anyway?)

Any tips to avoid this behavior?

## Steps to reproduce
I just used the template `dotnet new -t web` and added my extra dependencies.

Add one or more `DotNetCliToolReference` entries to the `.csproj` file.  eg,

```
<ItemGroup>
    <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.2.301" />
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0-msbuild3-final" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
```

## Expected  behavior
I would expect the restore to only happen once.

## Actual behavior
A restore happens once + number of times a DotNetCliToolReference is included in the .csproj.  In my case four times.

```
dotnet restore

  Restoring packages for ...\CaseManager\CaseManager.csproj...
  Restoring packages for ...\CaseManager\CaseManager.csproj...
  Restoring packages for ...\CaseManager\CaseManager.csproj...
  Restoring packages for ...\CaseManager\CaseManager.csproj...
  Restore completed in 2458.9338ms for ...\CaseManager\CaseManager.csproj.
  Restore completed in 2458.9296ms for ...\CaseManager\CaseManager.csproj.
  Restore completed in 2458.9352ms for ...\CaseManager\CaseManager.csproj.
  Generating MSBuild file ...\CaseManager\obj\CaseManager.csproj.nuget.g.props.
  Writing lock file to disk. Path: ...\CaseManager\obj\project.assets.json
  Restore completed in 4076.6408ms for ...\CaseManager\CaseManager.csproj.
```

This is also duplicated during a `git push` to azure making the deployment a bit slower than it perhaps could be.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by livarcocc** [comment]
This happens because NuGet actually restores each tool as it finds them so that they can be used through the dotnet <tool> command later on. This is expected.

As for the deployment to Azure, I am not sure why that happens there. In any case, you can file an issue for it at nuget/home.
