### ISSUE TITLE
CLI commands should print SDK version if a different version is picked

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5558]
I was compiling a project that had a global.json with an "sdk": { "version": "1.0.0-preview2-1-003177" } defined, but didn't have SDK 1.0.0-preview2-1-003177 on my machine. So, the latest installed SDK version was picked, which failed to restore or compile because it was on RC4 SDK. The only way to figure out what happened was to look at the output of the tools that failed and guess that I didn't have the right SDK installed. To alleviate this problem, I propose that the CLI prints a message if a different version is picked than the one specified in a global.json.

**Comment by livarcocc** [comment]
This will be addressed by https://github.com/dotnet/core-setup/issues/2334.

If you specify an SKD version and that's not found. We will error out instead of silently picking a different SDK for you.
