### ISSUE TITLE
libhostpolicy.so not found

### ISSUE THREAD

**Issue by sbomer** [dotnet/cli#5559]
## Steps to reproduce

- get the latest cli binaries (see version info below) and put them on the path
- `dotnet new console`
- add rid to the project: `<RuntimeIdentifier>ubuntu.16.04-x64</RuntimeIdentifier>`
- `dotnet restore`
- `dotnet run`

## Expected  behavior
Program runs and prints hello world.

## Actual behavior
```
Could not find required library libhostpolicy.so in 1 probing paths:
  /home/sven/.nuget/packages
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/sven/dotnettest/bin/Debug/netcoreapp1.0'.

```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004755)

Product Information:
 Version:            1.0.0-rc4-004755
 Commit SHA-1 hash:  bffbee2b91

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/1.0.0-rc4-004755

```

**Comment by sbomer** [comment]
Possibly related to [5059](https://github.com/dotnet/cli/issues/5059) or [560](https://github.com/dotnet/sdk/issues/560)

**Comment by livarcocc** [comment]
This is this issue here: https://github.com/dotnet/sdk/pull/811.

We have already taken a new version of the SDK that fixes this. If you try the latest CLI, this would work for you.

I tried it out.

**Comment by sbomer** [comment]
Great, thanks!

**Comment by Jose-CF** [comment]
In which CLI version was that fixed? I am experiencing this problem on 2.0.0-preview1-005977

**Comment by Bersam** [comment]
I'm still experiencing this on 2.0.3.

**Comment by Jose-CF** [comment]
Same here. Any news ?!

**Comment by livarcocc** [comment]
This is fixed in the 2.1.300 CLI, which is currently only available as a nightly build.

**Comment by livarcocc** [comment]
I just tried this on OSX with RID osx-x64.

@Jose-CF can you give us a more detailed repro of your scenario?

**Comment by Jose-CF** [comment]
@livarcocc I follow the steps from the original post and get the same error. Using dotnet sdk 2.0.2

**Comment by livarcocc** [comment]
Can you try with the latest release SDK, 2.1.4?

**Comment by psla** [comment]
I am seeing the same error when running on docker.

> docker logs 679f21c482b02f392e9bb5da197689b42a32e47d41f7b4c6deba3892320d45d9
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.

**Comment by livarcocc** [comment]
The contents of the build folder are not supposed to be runnable in production. The way to distribute your app for production is to publish your app and use the contents of the publish folder.

**Comment by jackal242** [comment]
I'm experiencing this bug in 2.0.6 using Amazon's dotnetcore ami image:
amzn2-ami-hvm-2017.12.0-x86_64-gp2-dotnetcore-2018.03.28 (ami-64a9771b)

--
# dotnet --info
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     amzn
 OS Version:  2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
