### ISSUE TITLE
Can't have files that are both resources as well as compiled

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#556]
_From @pranavkm on August 21, 2015 17:56_

Seems like anything that is listed in the `resources` node gets excluded from `compile` (even if it's explicitly called out). Perhaps we can change the behavior so that anything that is listed as `compile` always gets included?

_Copied from original issue: aspnet/dnx#2536_

**Comment by muratg** [comment]
_From @davidfowl on August 22, 2015 4:40_

What's the scenario?

**Comment by muratg** [comment]
_From @pranavkm on August 26, 2015 5:20_

Unusual scenario in the Razor precompilation tests where I want have the source of the files as well as the compiled types.

**Comment by muratg** [comment]
_From @glennc on August 26, 2015 17:29_

How impact-full is it? Blocking the tests?

**Comment by muratg** [comment]
_From @pranavkm on August 26, 2015 19:36_

No, I worked around it by creating a new project which included the files via `../other-project/resources/*.cs`

**Comment by piotrpMSFT** [comment]
This falls under the new project model.
