### ISSUE TITLE
dotnet publish does not copy the documentation file with csproj

### ISSUE THREAD

**Issue by masterjs** [dotnet/cli#5562]
## Steps to reproduce
Have a solution with multiple projects
The main "web" project has the GenerateDocumentationFile set to true

## Expected  behavior
When I run dotnet publish of the main "web" project, I expect that the XML documentation file is copied into the publishing folder. (Note the build will generate the file as it should.)

## Actual behavior
When I run dotnet publish of the main "web" project, it does not copy the XML documentation file to the psublish folder.

## My workaround
My current workaround is to update the csproj of the main web project and manually copy the file:

```
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
<ItemGroup>
    <DocFile Include="bin\**\**\PROJECT_XYZ.xml" />
</ItemGroup>
<Copy SourceFiles="@(DocFile)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="false"  />
</Target>
```

## Environment data
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by livarcocc** [comment]
I have moved this issue over to the SDK repo: https://github.com/dotnet/sdk/issues/795.
