### ISSUE TITLE
Enable preparing machines for servicing

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#557]
_From @moozzyk on August 20, 2015 18:8_

We would like make it possible to prepare a machine for servicing (e.g. create a script that the user would run before running an ASPNET vNext app that would create the right folder structure etc.). This might be even more important given that it is now possible to set an environment variable that will block running any ASPNET vNext app if servicing is not enabled. The scenario is mostly servers where the user runs an app that was published on a different box.

_Copied from original issue: aspnet/dnx#2526_

**Comment by muratg** [comment]
@glennc Move out of this milestone?

**Comment by piotrpMSFT** [comment]
dnx servicing is not a CLI concern.
