### ISSUE TITLE
dotnet new prints useless (?) content generation time number

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#5570]
This feels like a fit and finish thing, but it was weird to me and I didn't see an existing issue, so I opened one for discussion.

## Steps to reproduce

```
matell@matell-ub:~/git/hello$ ~/bin/dotnet new classlib
Content generation time: 131.0473 ms
The template "Class library" created successfully.
```

## Expected  behavior

I would expect that there was no output (or perhaps just the I generated this library successfully)

## Actual behavior

A message telling me how long it took to generate the template, which I don't care about.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004756)

Product Information:
 Version:            1.0.0-rc4-004756
 Commit SHA-1 hash:  ce59e6b19f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /home/matell/bin/sdk/1.0.0-rc4-004756
```

**Comment by livarcocc** [comment]
cc @mlorbetske. I think we should move this bug to dotnet/templating.

**Comment by mlorbetske** [comment]
Moved to dotnet/templating#244
