### ISSUE TITLE
Links in src/dotnet/README.md are broken

### ISSUE THREAD

**Issue by naamunds** [dotnet/cli#5572]
The links for the commands' documentation in https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/README.md lead to 404 errors.  It looks like the individual commands' READMEs were removed in 2d93968a88a724ec69a3c3cfd0ad92576101cbfe.

/cc @seancpeters @blackdwarf

**Comment by livarcocc** [comment]
@piotrpMSFT You removed these files here: https://github.com/dotnet/cli/commit/6fcbefa4f7a0016a68d3cda52779298a5cd20837#diff-6e3c120ad18acd1ae3d8d15d9870c901. Should we go ahead and just remove those links from the README.md file?

**Comment by piotrpMSFT** [comment]
@blackdwarf where would you like the links to point?

**Comment by blackdwarf** [comment]
Will create aka.ms links today and we can use those. Will update the issue.

**Comment by blackdwarf** [comment]
When is the final deadline when I can change this README for rel/1.0.0? I need to merge more docs and then create aka.ms links for them as well.

**Comment by piotrpMSFT** [comment]
doc bar is loosely defined. This week should be safe.

**Comment by blackdwarf** [comment]
Here are the links:

* https://aka.ms/dotnet-new
* https://aka.ms/dotnet-restore
* http://aka.ms/dotnet-build
* http://aka.ms/dotnet-test
* http://aka.ms/dotnet-run
* http://aka.ms/dotnet-publish
* http://aka.ms/dotnet-pack

**Comment by piotrpMSFT** [comment]
@blackdwarf will you be making the PR?

**Comment by blackdwarf** [comment]
@piotrpMSFT sure.
