### ISSUE TITLE
dotnet migrate ignores xmlDoc setting

### ISSUE THREAD

**Issue by FelschR** [dotnet/cli#5574]
## Steps to reproduce
Migrate a project from project.json to .csproj that contains `"xmlDoc": true` in the `buildOptions`.

## Expected  behavior
New .csproj file contains `<DocumentationFile>` element with default name or file name set in project.json (not sure how that works, I'm only using the default).

## Actual behavior
The created .csproj file doesn't have a `<DocumentationFile>` element at all.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by FelschR** [comment]
The same seems to happen for `copyToOutput`.

**Comment by livarcocc** [comment]
It generates a `GenerateDocumentationFile` property in the csproj. You are not seeing one like this in it?

**Comment by livarcocc** [comment]
And we move `copyToOutput` to `Content` with `CopyToOutputDirectory`.

**Comment by piotrpMSFT** [comment]
@livarcocc can we push this to 2.0.0?

**Comment by FelschR** [comment]
@livarcocc You're right about both `xmlDoc` and `copyToOutput`. I must have overlooked them.
It seems that `<GenerateDocumentationFile>true</GenerateDocumentationFile>` (alone) does nothing though.
I haven't rechecked it but that was the reason why I had to add `<DocumentationFile>` to my project.

**Comment by livarcocc** [comment]
I tried this out, I see a <AssemblyName>.xml in the output of the project that has only `GenerateDocumentationFile`set. You pass `DocumentationFile` when you want to change the xml file name.

Please, re-activate if you are seeing it not working. Or better yet, file an issue for it in the dotnet/sdk repo. As for migration, we are using the appropriate properties.
