### ISSUE TITLE
Cant build project located on UNC path

### ISSUE THREAD

**Issue by shaneray** [dotnet/cli#5576]
I have found that dotnet cli does not like running projects from a UNC path.
It seems using the UNC path breaks the relative path lookup as seen below (note the 'C:\Windows` root path).

```
\\server\Repo\ShaneSpace.Playground.DotNetCore\src\ShaneSpace.Playground.DonNetCore [master ≡ +0 ~2 -0 !]> dotnet build
CSC : error CS2001: Source file 'C:\Windows\Program.cs' could not be found. [\\server\Repo\ShaneSpace.Playground.DotNetCore\src\ShaneSpace.Playground.DonNetCore\ShaneSpace.Playground.DonNetCore.csproj]
```

vs the same project mapped to a drive letter:

```
M:\Shane\Repo\ShaneSpace.Playground.DotNetCore\src\ShaneSpace.Playground.DonNetCore [master ≡ +0 ~2 -0 !]> dotnet build
  ShaneSpace.Playground.DonNetCore -> M:\Shane\Repo\ShaneSpace.Playground.DotNetCore\src\ShaneSpace.Playground.DonNetCore\bin\Debug\netcoreapp1.1\ShaneSpace.Playground.DonNetCore.dll
```

## Steps to reproduce
Try to build a project from the command line using dotnet cli while the working directory is a UNC path.

## Expected  behavior
Should work the same as a local directory

## Actual behavior
Attempts to find files in `C:\Windows` rather than relative UNC path.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by blackdwarf** [comment]
Hmmm...this looks like an MSBuild or SDK error. 

/cc @rainersigwald @srivatsn @nguerrera

**Comment by shaneray** [comment]
Running with --verbosity d I see a message 

```
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

**Comment by jpierson** [comment]
I ran into the same error. Interesting thing is that it doesn't work when running from powershell either. Or perhaps the cmd issue is something run from within `dotnet run`? Either way it would be great that if this cli command isn't supported for UNC paths to see a better message to the user along those lines to help gently guide them into working around the issue without resorting to google.
