### ISSUE TITLE
Large amount of duplicate string content consumes memory

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#558]
_From @troydai on August 20, 2015 17:3_

Open the MVC solution in VS with latest DNX (dnx-clr-win-x86.1.0.0-beta8-15109)

The GC consumption stable around 677M:
![image](https://cloud.githubusercontent.com/assets/1329240/9389810/dea6a3dc-4721-11e5-9e60-27365389c4cd.png)

If we peek into the strings in GC2, you can find a lot of duplicates. Here's the examples stands out:

__File paths__
![image](https://cloud.githubusercontent.com/assets/1329240/9389842/19451276-4722-11e5-948b-192458741ed5.png)

__Version strings__
![image](https://cloud.githubusercontent.com/assets/1329240/9389875/46a8de0a-4722-11e5-9224-27d57d69a98e.png)

__Package names__
![image](https://cloud.githubusercontent.com/assets/1329240/9389916/8dfee9c0-4722-11e5-991d-b94826914cff.png)

__File globbing__
![image](https://cloud.githubusercontent.com/assets/1329240/9389930/af238be2-4722-11e5-900f-9fa173867caa.png)

_Copied from original issue: aspnet/dnx#2524_

**Comment by muratg** [comment]
_From @davidfowl on August 20, 2015 17:13_

Related https://github.com/aspnet/dnx/issues/1446

**Comment by blackdwarf** [comment]
If this is MVC, it should go to Aspnet/Home.
