### ISSUE TITLE
Build fails after migration

### ISSUE THREAD

**Issue by sdmunoz** [dotnet/cli#5583]
## Steps to reproduce
Upgraded to  1.0.0-rc3-004530
dotnet restore
dotnet build

## Expected  behavior
Successful build

## Actual behavior
/usr/local/share/dotnet/sdk/1.0.0-rc3-004530/Microsoft.Common.CurrentVersion.targets(2813,5): error MSB3552: Resource file "**/*.resx" cannot be found. 

I have no resx files in my project so not sure where this reference is coming from.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc3-004530

**Comment by livarcocc** [comment]
Can you share your csproj? Also, you mention migration, but your repro steps do not invoke it. Did you mean update of the CLI?

**Comment by livarcocc** [comment]
Please, re-activate this when you can provide us with additional information. It would be very helpful to have your csproj or, even better, if your code is on github, a link to your repo.

**Comment by geminiyellow** [comment]
@livarcocc same error

```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-preview4-004233
```

when i run `dotnet ef migrations add "OpenIddict" -o "Models\Migrations" -v`

```
/usr/local/share/dotnet/sdk/1.0.0-preview4-004233/Microsoft.Common.CurrentVersion.targets(2810,5): error MSB3552: Resource file "**/*.resx" cannot be found. [/Users/develop/Documents/Sources/server/server.csproj]
```
and i try to find out where is the `resx`, but nothing.

**Comment by geminiyellow** [comment]
and after this, i can not do anything by `ef` cli.
and the project can not build, it alway get this error.
i have to delete the project and create a new one.
please tell me why.

**Comment by Daniel15** [comment]
Did anyone end up resolving this? I'm encountering the same issue (https://github.com/dotnet/cli/issues/6561) and this post is the only useful result in Google for the error message.

**Comment by Daniel15** [comment]
It turns out this happens when any subdirectories have a path that's too long. It's a side-effect of https://github.com/Microsoft/msbuild/issues/406.

Posted more information about it here: https://dan.cx/2017/05/fixing-msb3552-resource-file-resx-cannot-be-found
