### ISSUE TITLE
latest.version reports different version than what the installer provides

### ISSUE THREAD

**Issue by aggieben** [dotnet/cli#5584]
## Steps to reproduce
View https://github.com/dotnet/cli or https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/latest.version

![image](https://cloud.githubusercontent.com/assets/1321/22621829/41bde9ba-eaf2-11e6-856a-6d15f890b513.png)

## Expected  behavior
I would expect one of either:
 - the available installer to install rc4-004767 
 - the reported available version to be rc3-004530

## Actual behavior
The installer and reported `latest.version` mismatch.

**Comment by piotrpMSFT** [comment]
@aggieben I'm afraid the issue isn't repro'ing at the moment so I'm not sure what you saw. At the moment both the reported version on the CLI repo and in the latest.version file for rel/1.0.0 are in-sync. 

We have occasionally seen recurrences of this [github issue](https://github.com/github/markup/issues/224), leaving the version badges a build, or several builds, behind reality.

The intent of `latest.version` is to express the absolute latest build that completed across all OS's. This will almost always be newer than the most recent stable release. We do have an intent of publishing a `stable.version` which would express the latest stable version, but it's not something that we have done to date. The https://dot.net downloads page serves that purpose at the moment.
