### ISSUE TITLE
can't uninstall VS tooling on Win10

### ISSUE THREAD

**Issue by sgwzxg** [dotnet/cli#5585]
## Steps to reproduce
I installed different build VS Tooling, and then **delete** the setup packages,
in the ARP there're 2 entries, 
Microsoft.NET.Core 1.0.1 - VS 2015 Tooling Preview 2 , version: 1.0.20908.53
Microsoft.NET.Core 1.0.0 - VS 2015 Tooling Preview 2 , version: 1.0.20624.39

When double click one of the entry, the dialog let me choose the setup package, but I can't download the specific setup packages...
## Environment data
`dotnet --info` output:
A fatal error occurred, the required library hostfxr.dll could not be found at c:\Program Files\dotnet

**Comment by piotrpMSFT** [comment]
Moved to aspnet/tooling repo
