### ISSUE TITLE
Cannot execute dotnet on Debian 8.7

### ISSUE THREAD

**Issue by jinhale** [dotnet/cli#5586]
## Steps to reproduce
Install Debian version 8.7 Linux (debian 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) i686 GNU/Linux)
Run the steps from https://www.microsoft.com/net/core#linuxdebian, but use su -c "#command" in place of sudo #command. 

## Expected  behavior
dotnet new should initialize a "Hello world!" CLI application.

## Actual behavior
bash: /usr/local/bin/dotnet: cannot execute binary file: Exec format error

## Environment data
`dotnet --info` output: 
bash: /usr/local/bin/dotnet: cannot execute binary file: Exec format error

**Comment by piotrpMSFT** [comment]
[.NET Core supports](https://github.com/dotnet/core/blob/master/roadmap.md) Debian 8.2. The CLI is Yet Another .NET Core Application, so we have the same constraints. I'll move the issue to the dotnet/core repo for tracking.

**Comment by piotrpMSFT** [comment]
Moved to dotnet/core, so closing
