### ISSUE TITLE
Handling for rerun/overrides

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/cli#5587]
## Steps to reproduce
- create project:
```bash
dotnet new3 console
Content generation time: 43.8456 ms
The template "Console Application" created successfully.
```

- change directory and forget about content.
- got to the same directory and run any of `new3` actions

## Expected  behavior
Handle rerun of the command on existing content, any of:
- content is overriden or there is an error about existing contetn
- there is an option to override or skip
- quit command to protect content

## Actual behavior
Code generation `fails`(?):
```bash
dotnet new3 console
Templates      Short Name      Language      Tags
-------------------------------------------------

Examples:
    dotnet new3 nugetconfig
    dotnet new3 console
    dotnet new3 --help
```
or:
```bash
dotnet new3 web
Templates      Short Name      Language      Tags
-------------------------------------------------

Examples:
    dotnet new3 mvc --auth None --framework 1.0
    dotnet new3 nugetconfig
    dotnet new3 --help
```
It looks like something broken without specific reason for the user. 
Why the `dotnet new3 nuget` works at the some directory?

```bash
dotnet new3 nuget
Content generation time: 41.2894 ms
The template "Nuget Config" created successfully.
```

## Environment data
`dotnet --info` output:
```
dotnet --info
.NET Command Line Tools (1.0.0-rc4-004597)

Product Information:
 Version:            1.0.0-rc4-004597
 Commit SHA-1 hash:  0a62481cc0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004597
````
Thanks!

**Comment by piotrpMSFT** [comment]
Moved to https://github.com/dotnet/templating repo
