### ISSUE TITLE
Using dotnet with project.json after installed VS2017RC3

### ISSUE THREAD

**Issue by JamesNK** [dotnet/cli#5591]
## Steps to reproduce
1. Create project.json project
2. Install preview SDK installed for building project.json (my build script installs 1.0.0-preview3-003171)
3. Install VS2017RC3
4. Run `dotnet build` against project.json project

## Expected  behavior
`dotnet build` will build the project.json project

## Actual behavior

> C:\Development\Source\Newtonsoft.Json\Working\Src\Newtonsoft.Json\project.json(1,1): error MSB4025: The project file could not be loaded. Data at the
root level is invalid. Line 1, position 1.

## Environment data
```
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530
```

**Comment by JamesNK** [comment]
I fixed my original issue with https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md and changing the sdk version in the global.json

The issue was the version specified in global.json wasn't installed and the SDK was choosing to use the latest version. Isn't this just going to trip people up?

**Comment by piotrpMSFT** [comment]
@JamesNK glad the workaround worked. 

It's probably time to update that article. With 1.0.0 so close, the real workaround is to `dotnet migrate` and move away from project.json.

Yea, providing a better experience is probably at the top of my list of issues I wish we had had time to address for 1.0.0. However, once VS 2017 ships it will automatically migrate these projects forward to csproj and do away with this point-in-time issue.
