### ISSUE TITLE
Remove Custom install location from Windows SDK installer

### ISSUE THREAD

**Issue by foresterre** [dotnet/cli#5592]
Hi,

Earlier today I tried installing the .NET Core 1.1 SDK preview (from [1]) to a custom location via the Options menu in the GUI installer, which is the most recent 'current' version [2] of the SDK at the time of writing (2017-02-05).

However, the install location given to the options menu in the installer is not used. Instead, a default location at `C:/Program Files/dotnet` is used.

## Steps to reproduce

1. Download 'Current' installer (`.NET Core 1.1 SDK - Installer`, Windows `x64`.exe) from [1].
2. Run installer.
3. Select "Options".
4. Browse to a custom install location (In my case `D:\Tools\dotnet\core_1.1.0_sdk_preview`).

The folder up to and including D:\Tools\dotnet does already exist. `core_1.1.0_sdk_preview` should be created by the installer.

(I've also tested the case where the folder already exists and is empty (created by hand). In this case, the installer still installs to `C:\Program Files\dotnet`)

The folders do have writing rights for both users and admin users (are _not_ limited to reading or executing).

6. Select OK.
5. Agree to license.
6. Select Install.
7. Give UAC permission.

## Expected  behavior

* The dotnet SDK installed at the custom, and provided to the installer, location.

## Actual behavior

* No folder is made in the custom directory.
* Installer succeeds without warnings.
* Installer actually installs to `C:\Program Files\dotnet`

## Environment data

```ps
PS D:\> where.exe dotnet
C:\Program Files\dotnet\dotnet.exe
PS D:\> dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
PS D:\>
```

## Work around

Instead of using the installer one could use the binaries only download instead, extract the files at the right folder and add that folder to the path.

## Thanks!

I hope I've provided sufficient information regarding the issue. If this is not the case, do not hesitate to request more infomation which I will provide if possible.

I also hope, I've reported this issue to the right repository (taken from [3]). If this is not the case, can you please tell me where I've to report it instead.
If the issue has already been reported, I unfortunately have missed it (then, sorry for that!)

Thank you in advance for looking at this issue.

## References

Installer: Microsoft .NET Core 1.1.0 - SDK 1.0.0 Preview 2.1-003177 [1]

[1] https://go.microsoft.com/fwlink/?LinkID=835014 (link to installer)
[2] https://www.microsoft.com/net/download/core#/current/sdk
[3] https://www.microsoft.com/net/community

**Comment by piotrpMSFT** [comment]
Thanks for reporting! The UI element in question is an oversight. Since CLI writes to the PATH we dont want multiple versions fighting with one another. We will remove the option to avoid confusion!
