### ISSUE TITLE
Running dotnet build -f net46 builds and packages packages that contain all frameworks

### ISSUE THREAD

**Issue by niemyjski** [dotnet/cli#5595]
So I was running into tons of issues that have been fixed in the nightlies and just wanted to build and package only .net 46 framework targets so I ran the build with `-f net46`

https://github.com/exceptionless/Foundatio/blob/master/appveyor.yml#L23

But it appears that the nuget package were still built and completed as full framework and net standard targets.

https://www.nuget.org/packages/Foundatio/

I expected the netstandard build and packaging not to take place (I also haven't looked inside the nuget package yet to see what is in the net standard folder).

**Comment by livarcocc** [comment]
Moved this issue over to the dotnet/sdk repo.
