### ISSUE TITLE
Dependent packages version numbers are not updated correctly.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/cli#5596]
I was running my build with `dotnet build -f net46 Foundatio.sln /p:VersionPrefix="$($env:APPVEYOR_BUILD_VERSION)" /p:VersionSuffix="$($env:VERSION_SUFFIX)"` to update the predefined version properties (https://github.com/exceptionless/Foundatio/blob/73b8ee68d611d1521e48eadac1101ea054115e6c/build/version.props). This seemed to create the nuget packages with the correct version numbers but I noticed that packages (project references) didn't have the correct version numbers.

You can see it here (https://www.nuget.org/packages/Foundatio.Redis/4.3.1280), once I started updating the version.props file on disk as a pre build task and stopped updating the properties as a parameter the issue went away as you can see here https://www.nuget.org/packages/Foundatio.Redis/4.3.1282

**Comment by livarcocc** [comment]
Moved this issue over to the dotnet/sdk repo: https://github.com/dotnet/sdk/issues/824.
