### ISSUE TITLE
dotnet new -t (any format) - missing project.json though have .csproj

### ISSUE THREAD

**Issue by avikenjale** [dotnet/cli#5599]
I dotnet core SDK installed. Earlier I was able to create new core apps using `dotnet new -t Console` (e.g.), then folder was having two files, Program.cs & project.json. However I have installed Visual Studio 2017 RC for something else testing purpose and after that `dotnet  new` command messed up and for any template it is creating `.csproj` instead of `project.json`

## Steps to reproduce

- install  dotnet core SDK
- install VS 2017 RC
- restart machine (if needed)
- run command - `dotnet new -t Console`
- Will see `program.cs` & `.csproj` files

## Expected  behavior
- Run command `dotnet new -t Console`
- Should have `Program.cs` & `project.json` files

## Environment data
`dotnet --info` output:

 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by livarcocc** [comment]
We have switched to csproj a while ago. From preview3 onward, our releases are with MSBuild and csproj.

Preview2 and Preview2-1 were the last releases where we supported project.json.

**Comment by avikenjale** [comment]
Fine. In that case how can switch back to previous version without un-installing latest?

**Comment by piotrpMSFT** [comment]
@avikenjale take a look at [this](https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md#how-do-i-work-with-projectjson-and-csproj-on-the-same-machine) as a workaround. 

It's pretty inconvenient, I know, but there is no planned project.json support moving forward, so this is really a stop-gap measure.

You will want the global.json file somewhere above the directory in which you're trying to create a new project.json template.

**Comment by avikenjale** [comment]
Thanks @piotrpMSFT, however I remember there was command line for switching between SDK versions 7-8 months back? Might be I am wrong.

**Comment by piotrpMSFT** [comment]
there was one about 2 yrs back. We moved to a config-file based approach because the command line created a bunch of issues around having the wrong SDK when moving between repos. "Why won't this build? oh yea, I forgot to run the command line... again!"

**Comment by avikenjale** [comment]
Perfect.

Additional reference - http://stackoverflow.com/questions/42077229/switch-between-dotnet-core-sdk-versions/42078060#42078060
