### ISSUE TITLE
Razor View Precompilation is not working for 1.1 MVC web templates

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/cli#5602]
Solution is to remove the Razor View precompilation package until an updated version of the package is available.

**Comment by livarcocc** [comment]
@mlorbetske Is there something that we can/need to do in the CLI to address this? Also, is this in the RC4 version of the CLI?

**Comment by mlorbetske** [comment]
@livarcocc Yep, it's the RC4 version, a pull request with the updated template version numbers will be coming shortly
