### ISSUE TITLE
Handling of incorrectly cased project.json in dnu restore on Linux

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#561]
_From @akoeplinger on August 17, 2015 13:6_

I just tried `dnu restore` on a project that had `Project.json` instead of `project.json` on Linux. Restore just printed nothing. Only after running `dnu build` I found out that the file is incorrectly cased since it complained about not finding `project.json`.

Should `dnu restore` complain similarly?

_Copied from original issue: aspnet/dnx#2497_

**Comment by muratg** [comment]
@davidfowl IMO, this should only go to nuget.  The restore feature in CLI is only temporary.

**Comment by blackdwarf** [comment]
Restore uses NuGet, if this is still an issue, it should go to Nuget/Home.
