### ISSUE TITLE
Dotnet.exe does not support long file path

### ISSUE THREAD

**Issue by jhkimnew** [dotnet/cli#5611]
## Steps to reproduce
1. Enable long file name on Windows 10 or any OS which supports long file name
2. Create a long file path directory such as "d:\1111111111111111111111111111111111111111111111111111111111\1111111111111111111111111111111111111111111
111111111111111\1111111111111111111111111111111111111111111111111111111111\111111111111111111111111111111111111111111111
1111111111111\1111111111111111111111111111111111111111111111111111111111\11111111111111111111111111111111111111111111111
11111111111", of which length should be bigger than 260.
3. Publish any aspnetcore app on the newly created directory and run the aspnetcore app as the following (NOTE: You need to replace AspNetCoreModule.Testes.Standard.dll with the actuall dll name):

cd D:\
dotnet.exe d:\1111111111111111111111111111111111111111111111111111111111\1111111111111111111111111111111111111111111
111111111111111\1111111111111111111111111111111111111111111111111111111111\111111111111111111111111111111111111111111111
1111111111111\1111111111111111111111111111111111111111111111111111111111\11111111111111111111111111111111111111111111111
11111111111\AspNetCoreModule.TestSites.Standard.dll

## Expected  behavior

No error

## Actual behavior

Error message of "Error resolving full path" is shown as the following screenshot:

<><><>
PS D:\> dotnet.exe d:\1111111111111111111111111111111111111111111111111111111111\1111111111111111111111111111111111111111111
111111111111111\1111111111111111111111111111111111111111111111111111111111\111111111111111111111111111111111111111111111
1111111111111\1111111111111111111111111111111111111111111111111111111111\11111111111111111111111111111111111111111111111
11111111111\AspNetCoreModule.TestSites.Standard.dll
Error resolving full path [d:\1111111111111111111111111111111111111111111111111111111111\1111111111111111111111111111111
111111111111111111111111111\1111111111111111111111111111111111111111111111111111111111\111111111111111111111111111111111
1111111111111111111111111\1111111111111111111111111111111111111111111111111111111111\11111111111111111111111111111111111
11111111111111111111111\AspNetCoreModule.TestSites.Standard.dll]
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
<><><>

## Environment data
`dotnet --info` output:

<><><>
D:\Program Files\dotnet>dotnet --version

Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

Use dotnet --help to get help with the SDK
<><><>

**Comment by piotrpMSFT** [comment]
Moved to the core-setup repo where the host is maintained.
