### ISSUE TITLE
Where to start with Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by fearthecowboy** [dotnet/cli#5616]
## Steps to reproduce
I've ported our code base to run on .NET Core, and we've got it working fairly fine on Windows.

I went to run it on Linux (Ubuntu 16.04 ) and I can get it to build, when I go to run it I get `Segmentation Fault (core dumped)` 

Where do I start to figure out whats going wrong?

I added `COREHOST_TRACE=1` when I ran it, and it spit out a bunch of information (nothing looked too telling...)  

it ends with:

![image](https://cloud.githubusercontent.com/assets/133736/22716109/17653836-ed49-11e6-97f5-60fbdb332d4f.png)

## Environment data
`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/133736/22715956/4e135bb6-ed48-11e6-8d0e-ad69481ef5e0.png)

**Comment by piotrpMSFT** [comment]
Moved to core-setup repo where the host is maintained.
