### ISSUE TITLE
cli still using project.json file

### ISSUE THREAD

**Issue by vairamsvsjdo** [dotnet/cli#5619]
## Steps to reproduce
git clone https://github.com/dotnet/cli
git checkout rel/1.0.0-preview4
powershell
.\build.cmd 

The same behavior is observed when building core sample helloworld in core when installing the latest binaries using msi.

## Expected  behavior
log: restoring project files from csproj or something similar. No project.json file is required.

## Actual behavior
 "log  : Restoring packages for C:\v\dotnet\cli\build_tools\project.json..."
note that it still displays "log  : Restoring packages for C:\v\dotnet\cli\build_tools\project.json..."
![dotnetclistillusingprojectjsonandpreview3](https://cloud.githubusercontent.com/assets/22436725/22718268/4b4e055a-ed54-11e6-97f5-1a93bcde5f1d.PNG)
## Environment data
`dotnet --info` output:
PS C:\v\dotnet\cli> dotnet --info
.NET Command Line Tools (1.0.0-preview2-003156)

Product Information:
 Version:            1.0.0-preview2-003156
 Commit SHA-1 hash:  33dabee5d8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by vairamsvsjdo** [comment]
This is resolved when installing rc4 extract from dotnet-dev-win-x64.1.0.0-rc4-004771.zip file and copying into  c:\program files\dotnet

**Comment by piotrpMSFT** [comment]
This is by-design. `build-tools` restores some of its sub-components via project.json. That toolset needs to be upgraded when there is time.
