### ISSUE TITLE
Upon start, DNX should print all environment variables that it uses and their value

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#562]
_From @victorhurdugaci on August 14, 2015 0:7_

When running with `DNX_TRACE`, dnx should show the values of all the environment variables that are used to configure it (like `DNX_SERVICING_ROOT` or `DNX_REQUIRE_SERVICING`). It would help debugging and it would also make them more discoverable.

Example output:

    DNX_SERVICING_ROOT: C:/foo
    DNX_REQUIRE_SERVICING: <not set>

_Copied from original issue: aspnet/dnx#2479_

**Comment by muratg** [comment]
_From @Eilon on August 15, 2015 16:41_

I like this.

**Comment by blackdwarf** [comment]
We have an issue that tracks this for the CLI: #1119
