### ISSUE TITLE
How to create controller in vscode using yo

### ISSUE THREAD

**Issue by MuthiyalLakshmi** [dotnet/cli#5621]
![screenshot 10](https://cloud.githubusercontent.com/assets/25578966/22723110/993e8854-ed70-11e6-92a5-77ae09022f06.png)
## Environment data
`dotnet --info` output:

**Comment by piotrpMSFT** [comment]
@mlorbetske where should this bug be filed? CLI is not the right repo...

**Comment by mlorbetske** [comment]
@piotrpMSFT these should go here https://github.com/OmniSharp/generator-aspnet I'll move it
