### ISSUE TITLE
Unwanted (big) dll in refs after publish

### ISSUE THREAD

**Issue by tbolon** [dotnet/cli#5625]
`dotnet publish` seems to include code analysis dll which are (I think) not necessary at runtime. It increase the size of the files to publish for 6MB.

## Steps to reproduce

```
dotnet new webapi --framework netcoreapp1.1
dotnet restore
dotnet publish -c Release
dir bin\Release\netcoreapp1.1\publish\refs /o:-S
```

## Expected  behavior

Should list only refs libraries, relatively small in size.

## Actual behavior

Two large files which not seems to be required at runtime are visible at the top of the list:

```
13/06/2016  04:31         4 211 112 Microsoft.CodeAnalysis.CSharp.dll
13/06/2016  04:31         2 049 432 Microsoft.CodeAnalysis.dll
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by tbolon** [comment]
As a side note, I am trying to understand if we could trim some libraries before deploying our app.

Regarding the refs folder: I found another issue #4251 which seems to explain the reason behind this folder. But I assume CodeAnalysis does not count as refs assemblies.

I also found the Microsoft.DiaSymReader.Native files in the `publish\` folder. I suppose these libraries are used at runtime to read .pdb files. Can these libraries be considered as optional or not ? Does removing them prevents obtaining details in stacktraces when running ?

Thanks,

**Comment by piotrpMSFT** [comment]
@mlorbetske is this something you expect?

**Comment by mlorbetske** [comment]
This looks like it may be something in the Web SDK, moving the issue to that repo

**Comment by tbolon** [comment]
Thank you @mlorbetske I will follow the new issue then.
