### ISSUE TITLE
Building with sdk 1.0.0 RC4 fails

### ISSUE THREAD

**Issue by skaa** [dotnet/cli#5626]
## Steps to reproduce
Open any solution with core projects in VS 2015. SDK `dotnet-dev-win-x64.1.0.0-rc4-004771.exe` and tooling `DotNetCore.1.0.1-VS2015Tools.Preview2.0.3.exe`.

## Expected  behavior
Solution opened and built.

## Actual behavior
Getting error (message box VS 2015 Update 3):
> The following error occurred attempting to run the project model server process (1.0.0-rc4-004771). 
> Unable to start the process. No executable found matching command "dotnet-projectmodel-server"

`dotnet restore` print error:
>  error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-rc4-004771\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

xproj file has lines:
`<VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>`
and
`<Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.Props" Condition="'$(VSToolsPath)' != ''" />`
Directory `C:\Program Files\dotnet\sdk\1.0.0-rc4-004771` exists, subdir `\Microsoft` doesnt.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by yetanotherchris** [comment]
This is also `latest` on the Docker image, which now fails on CI servers on Linux.

**Comment by yetanotherchris** [comment]
Infact the Docker repo readme does tell you:

> Note: The latest tag no longer uses the project.json project format, but has now been updated to be csproj/MSBuild-based. If you do not wish to migrate your existing projects to MSBuild simply change your Dockerfile to use the 1.1.0-sdk-projectjson or 1.1.0-sdk-projectjson-nanoserver tag. Going forward, new .NET Core sdk images will be MSBuild-based.

Maybe this should be put in the console output error message for a few months, while people upgrade.

**Comment by livarcocc** [comment]
@skaa This happens because you have two version of the CLI installed: preview2 and 1.0.0-rc4. Because RC4 is a newer version, the host you pick this version to execute and this version no longer support this projectmodel-server, which existed only for project.json.

You can set the version of the CLI that you want to use for you project by create a global.json in the root of your solution with the following content:

```
{
  "sdk": {
    "version": "<the preview2 CLI version you have installed>"
  }
}
```

With this file in place, VS will use the preview2 CLI and it will work.

**Comment by MaxxDelusional** [comment]
If you solution contains projects that are not saved within the solution folder, they will need their own global.json file. 

Not sure if this is a bug, or by design.

**Comment by piotrpMSFT** [comment]
@MaxxDelusional this is by-design. Global.json will need to be reconsidered in time for 2.0.0 once we have multiple `released` versions.

**Comment by BharatRajMeriyala** [comment]
So does this mean we cannot use the VS 2015 with dotnet-dev-win-x64.1.0.0-rc4-004771.exe and tooling DotNetCore.1.0.1-VS2015Tools.Preview2.0.3.exe ??

And have to change the global.json entry to 

"sdk": {
    "version": "1.0.0-preview2-1-003177"
  }

?????

**Comment by piotrpMSFT** [comment]
@BharatRajMeriyala correct. any CLI release past 1.0.0-preview2 is only supported in VS2017.

**Comment by cosminpopescu** [comment]
None of the above solutions worked for me. I had to uninstall 1.0.0-rc4-004771 and repair the other version of .net core to make it work.
