### ISSUE TITLE
Passing arguments to project.json

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#563]
_From @JamesNK on August 11, 2015 1:23_

When building a csproj with msbuild you can pass it arguments. For example, treating errors as warnings can be enabled with this argument:

/p:TreatWarningsAsErrors=true

It was be useful to be able to pass arguments to a project.json on build (treat warnings as errors, strong name path, etc)

_Copied from original issue: aspnet/dnx#2450_

**Comment by muratg** [comment]
_From @Eilon on August 11, 2015 5:42_

Hmm, interesting. I think there are a couple ways (at least) to go about this:

1. MSBuild style, where "everything's a variable/list" (you know, the PropertyGroup stuff)
2. Allow some sort of `$(variable)` syntax for variables that are either env-vars, or command-line params

I don't see (1) happening, but (2) is certainly interesting (to me). Might be other reasonable options as well.

**Comment by muratg** [comment]
_From @JamesNK on August 11, 2015 6:9_

You could do option 1 with some kind of path (since Json isn't a flat list)

Eg compilationOptions.treatWarningsAsErrors=true

For now I'm going to have to transform the file myself in my build script and I'll probably use a path to insert the new value.

**Comment by muratg** [comment]
_From @Eilon on August 11, 2015 6:18_

@JamesNK ah interesting. I hope you know a good JSON parser for your transformations :smile: 

With paths we'd have to consider how some more complex items would be persisted, e.g. dictionaries that have complex property names, or arrays. For example, even with setting compilation options, you can have that vary per framework, and the "path name" for those could get ugly (especially when they have weird characters in them).

I do think this would be an interesting feature (whatever it ends up being).

**Comment by muratg** [comment]
_From @JamesNK on August 11, 2015 13:8_

Ok. I'm not a fan of (2) because it would force those params to always be passed it. Optionally passing them in as overrides is more flexible.

I ended up using PowerShell's JSON functionality to modify the project.json so didn't do anything with paths myself.

**Comment by muratg** [comment]
_From @JamesNK on August 11, 2015 23:31_

FYI there are some cases where you can pass settings in via environment variables, e.g. DNX_BUILD_KEY_FILE

https://github.com/JamesNK/Newtonsoft.Json/commit/b7cfafb8ed5223a2cf9ea7a893292edaa63eb27b#commitcomment-12644907

**Comment by muratg** [comment]
_From @moozzyk on August 11, 2015 23:50_

AFAIR we decided to leave DNX_BUILD_KEY_FILE to not break the CI... @davidfowl do you remember?

**Comment by muratg** [comment]
_From @davidfowl on August 12, 2015 0:56_

We added it originally for the NuGet build.

**Comment by muratg** [comment]
_From @anurse on August 14, 2015 0:53_

It's also a useful feature for cases where you want CI builds to do something but not dev builds. Having said that, a general purpose override system is also useful for that...

**Comment by muratg** [comment]
_From @victorhurdugaci on October 2, 2015 19:25_

+1 for this. We need it for feature defines (like disabling the min version check on dev)

**Comment by muratg** [comment]
_From @victorhurdugaci on October 5, 2015 19:43_

Related: https://github.com/aspnet/Home/issues/450#issuecomment-145644823

**Comment by piotrpMSFT** [comment]
Since we're converging with msbuild, this behavior is expected to fall out of the new project model.

**Comment by jefftucker** [comment]
have we converged with msbuild yet?  I need to be able to pass arguments to a script as a precompile step so that it can generate an assembly that's referenced by the compiler.  How do I do that?  The documentation (what little there is) doesn't seem to give me much to work with here.

**Comment by moozzyk** [comment]
It's gross but can you set an environment variable and read the value in the script?

**Comment by jefftucker** [comment]
That's what I ended up doing but I really miss having some of the other visual studio variables (like OutputPath and the one that tells me if it's in Debug or Release and so on).  It would be really useful if I could pass those to my scripts.  It would also be useful if I could read environment variables in the project.json file as well to avoid horrible relative-paths and having to use a bunch of powershell haxin to do things.

**Comment by moozzyk** [comment]
There are some arguments you actually can pass to scripts - see: http://stackoverflow.com/questions/37596115/how-to-run-scripts-based-on-solution-configuration-in-asp-net-core-rc2/37598276#37598276
