### ISSUE TITLE
Strange naming of SDKs!

### ISSUE THREAD

**Issue by freerider7777** [dotnet/cli#5635]
## Steps to reproduce
Hi,

SDK folder names don't give us any sign of the version/smth else - is it 1.0, 1.0.1, 1.1, does it work with project.json or not:

![dotnet_issue](https://cloud.githubusercontent.com/assets/6572573/22773228/ff7bad9e-eeb1-11e6-8c0b-ad5ada8a0ee4.png)

## Expected  behavior
More clear folder names - with 1.0, 1.1 / etc

## Environment data
`dotnet --info` output:

**Comment by piotrpMSFT** [comment]
@freerider7777 yep, agreed. Tooling is lagging behind the Runtime which threw off versioning for a while. We're almost caught up at this point so versioning will get resolved soon.

For the meantime, this should help:
preview1 and preview2 support project.json
preview3 and later are csproj

All current versions of the CLI can build apps for netcoreapp1.0 and 1.1. However, we only recently started shipping netcoreapp1.1 in-box. For older versions, you can just install the relevant shared framework in addition to the CLI.

When we finish up 1.0, it will include both 1.0 and 1.1 to play catchup with the runtime. By the time we get to 2.0 I expect CLI and Runtime will get in sync. Hope this helps!

**Comment by freerider7777** [comment]
ok, thanks! :)
