### ISSUE TITLE
Add f# support to dotnet migrate 

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#5636]
**WORKAROUND:** https://github.com/dotnet/netcorecli-fsc/wiki/How-to-migrate-preview2-projects-to-rc4 for a manual how-to-do-it guide. Pratically workaround is remove fsc compiler and dotnet-migrate + manual changes

Some `up-for-grab` issue with notes on how to implement this in https://github.com/dotnet/netcorecli-fsc/issues/38.
I open the issue there too, because users search there for bug/workaround. I am not asking dotnet/cli team to implement that np 😄 , it's something f# community can do

## Steps to reproduce

- create a project.json based f# project
- `dotnet migrate`

## Expected  behavior

Project is successfully migrated

## Actual behavior

fails because `fsc` is not supported

```
Project fk migration failed (e:\temp\fk)
MIGRATE20013::Non-Csharp App: Cannot migrate project e:\temp\fk\project.json using compiler fsc
```

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#25
