### ISSUE TITLE
Microsoft.Common.CurrentVersion.targets - Found conflicts between different  versions of ...

### ISSUE THREAD

**Issue by mdmoura** [dotnet/cli#5637]
## Steps to reproduce

I have an ASP.NET Core 1.1 XUnit Test project with the following csproj file:

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>    
        <TargetFramework>netcoreapp1.1</TargetFramework>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170125-04" />
        <PackageReference Include="xunit" Version="2.2.0-beta5-build3474" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-beta5-build1225" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="1.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" /> 
      </ItemGroup>

     <ItemGroup>
        <ProjectReference Include="..\..\src\MyClassLibrary\MyClassLibrary.csproj" />
      </ItemGroup>

    </Project>

I am using Visual Studio Code 1.9 and running everything on Command Line.

## Expected  behavior

When I run `dotnet build` there should be no warnings or errors ...

## Actual behavior

However, when I run `dotnet build` I get the following warning:

C:\Program Files\dotnet\sdk\1.0.0-rc4-004771\Microsoft.Common.CurrentVersion.targets(1956,5): warning MSB3277: Found conflicts between different
 versions of the same dependent assembly that could not be resolved ...

## Environment data

`dotnet --info` output:

    .NET Command Line Tools (1.0.0-rc4-004771)

    Product Information:
     Version:            1.0.0-rc4-004771
     Commit SHA-1 hash:  4228198f0e

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

What might be wrong?

**Comment by piotrpMSFT** [comment]
what package has the conflict?

**Comment by nietras** [comment]
I am constantly getting this error too, see detailed [log.txt](https://github.com/dotnet/cli/files/778229/log.txt)

**Comment by piotrpMSFT** [comment]
Ok, I see the issue. CLI's dependency on Microsoft.Extensons.DependencyModel is a bit outdated. We need to fix this. Thanks!

**Comment by dasMulli** [comment]
The dependencies of vstest and xunit have been updated, so you should no longer have this error if you update to:
```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0-preview-20170210-02" />
    <PackageReference Include="xunit" Version="2.2.0-rc2-build3523" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0-rc2-build1249" />
```

**Comment by nietras** [comment]
> dependencies of vstest and xunit have been updated

Yes, that fixed it for me, thanks.

**Comment by livarcocc** [comment]
We have also updated our dependencies to Extensions.DependencyModel.
