### ISSUE TITLE
"dotnet new classlib" uses wrong version for NETStandard.Library 2.0

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#5638]
## Steps to reproduce
Using a 2.0 SDK (one built from master)

```
$dotnet new classlib
$dotnet restore
```

## Expected  behavior
I expect the `NetStandardImplicitPackageVersion` generated into the project is the correct NETStandard.Library version that comes with the SDK.

## Actual behavior
The restore has a warning:

```
F:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-alpha-004830\NuGet.targets(97,5): warning : Dependency specified was NETStandard.Library (>= 2.0.0-beta-001509-00) but ended up with NETStandard.Library 2.0.0-beta-24709-0. [F:\DotNetTest\NewLibrary\NewLibrary.csproj]
```

Because we are using the `Microsoft.NETCore.App` version for the `NETStandard.Library` version, and those versions are not the same.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-alpha-004830)

Product Information:
 Version:            2.0.0-alpha-004830
 Commit SHA-1 hash:  546d62061a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-alpha-004830\
```

**Comment by livarcocc** [comment]
@eerhardt should this be in the SDK repo?

**Comment by eerhardt** [comment]
Nope.  The CLI is the one injecting the version number into the .csproj in `dotnet new`.

**Comment by blackdwarf** [comment]
@eerhardt which `new` you are talking about? If this is the old `new`, that thing doesn't exist anymore, we have the new `new` that can actually take a parameter to inject this on template creation. @mlorbetske for this.

**Comment by mlorbetske** [comment]
@blackdwarf we do inject it in the CLI and the template seems to be honoring the value (as the value included in the template before replacement is `2.0.0-beta-001507` per https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Common.ProjectTemplates.2.0/content/ClassLibrary-CSharp/Company.ClassLibrary1.csproj) here https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-new/NewCommandShim.cs#L56

**Comment by blackdwarf** [comment]
@mlorbetske sorry, I don't understand. I thought that the new `new` allows me to simply use `--framework` to override whatever is in the template. Is this about the default value if that param is not present?

**Comment by mlorbetske** [comment]
@blackdwarf this is a different value that populates a property called `NetStandardImplicitPackageVersion` that governs the version of the implicit package being referenced rather than the TFM

**Comment by blackdwarf** [comment]
@mlorbetske thanks! I guess I should read the issues more closely.

**Comment by eerhardt** [comment]
@mlorbetske - I was mistaken when last we talked.  I thought these version numbers between console and classlib were the same. It turns out we need them to be separate.

Would it be possible to get a separate property for the 2.0 classlib?  And then in the CLI I can set both properties: `RuntimeFrameworkVersion` for console, and this new property for `classlib` in https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-new/NewCommandShim.cs#L56.  Maybe the new property could be called `NetStandardImplicitPackageVersion`?  Or something else if you prefer.

**Comment by mlorbetske** [comment]
@eerhardt we can add a second property, that's easy, `NetStandardImplicitPackageVersion` will work. I'll make the change & send the new template package version as soon as they're ready

**Comment by mlorbetske** [comment]
Template packages are ready - version `1.0.0-beta1-20170209-117`	

To use this version, we'll have to update  https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/dotnet-cli-build/GenerateNuGetPackagesArchiveVersion.cs#L56

to be 

```
var packageRefs = rootElement.Items.Where(i => i.ItemType == "PackageReference" ||  i.ItemType == "DotNetCliToolReference").ToList();
```

in order to pick up tools included in the templates

**Comment by mlorbetske** [comment]
Also, it looks like these two are also missing the 2.0 suffix, they won't resolve to anything as they are https://github.com/dotnet/cli/blob/master/build/Microsoft.DotNet.Cli.BundledTemplates.props#L5-L6

**Comment by eerhardt** [comment]
Thanks for the quick response, @mlorbetske.  I'm working on a PR to fix this now.

> To use this version, we'll have to update https://github.com/dotnet/cli/blob/rel/1.0.0/build_projects/dotnet-cli-build/GenerateNuGetPackagesArchiveVersion.cs#L56

Note that I am only using these new "2.0" templates in the "master" branch.  I haven't updated rel/1.0.0 at all.

> Also, it looks like these two are also missing the 2.0 suffix, they won't resolve to anything as they are https://github.com/dotnet/cli/blob/master/build/Microsoft.DotNet.Cli.BundledTemplates.props#L5-L6

Using the latest CLI, I get:

```
Templates                                 Short Name      Language      Tags
--------------------------------------------------------------------------------------
Console Application                       console         [C#], F#      Common/Console
Class library                             classlib        [C#], F#      Common/Library
Unit Test Project                         mstest          [C#], F#      Test/MSTest
xUnit Test Project                        xunit           [C#], F#      Test/xUnit
Empty ASP.NET Core Web Application        web             [C#]          Web/Empty
MVC ASP.NET Core Web Application          mvc             [C#], F#      Web/MVC
Web API ASP.NET Core Web Application      webapi          [C#]          Web/WebAPI
Solution File                             sln                           Solution
```

And saying `dotnet new mvc` works as expected (it creates a 1.0 app).  Notice that I split the template version properties: the original version for test, web, etc and the "2.0" version.

**Comment by livarcocc** [comment]
I believe this is fixed and aligned now. Please, re-activate if I got it wrong and there is still some work left for it.
