### ISSUE TITLE
Use $(lsb_release -cs) to simplify Ubuntu install instructions

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#5642]
At https://www.microsoft.com/net/core#linuxubuntu, there are currently three different sets of instructions for adding the dotnet apt-get feed.  The only difference is the OS codename, so I would recommend consolidating these to a single set of instructions which dynamically inserts the OS codename via `$(lsb_release -cs)`:

```
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
```

**Comment by mikeharder** [comment]
@blackdwarf: Another issue for the website.

**Comment by blackdwarf** [comment]
Moved to the appropriate repo. We will take a look at this. Thanks @mikeharder! :)
