### ISSUE TITLE
Selecting "Mac" on https://www.microsoft.com/net/core does not update environment

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#5643]
## Steps to reproduce
1. Browse to https://www.microsoft.com/net/core#windowsvs2015, https://www.microsoft.com/net/core#linuxredhat, or https://www.microsoft.com/net/core#dockercmd.
2. Select "Mac" near the top of the page

## Expected  behavior
"Select your environment" section should be hidden.

## Actual behavior
"Select your environment" still shows the environments which apply to the previous OS.

**Comment by blackdwarf** [comment]
@mikeharder we actually have this issue on our repo that houses the website. Will close this one. Thanks!

**Comment by mikeharder** [comment]
@blackdwarf: Is that repo public?  What is the best place to report issues in the website?

**Comment by blackdwarf** [comment]
@mikeharder it is not public, unfortunately. The best repo to report issues on the website would be, for now, dotnet/core and you can @ me to move it where appropriate.
