### ISSUE TITLE
dotnet pack user experience could be better

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#5645]
I am trying to create a single NuGet package using a csproj file and `dotnet pack` that includes more than one output assembly. The process is extremely counterintuitive and in fact contrary to what is outlined on docs.microsoft.com. (I do not have the link to the exact page right now, unfortunately.)

## Steps to reproduce

1. Create `A.csproj` and `B.csproj`.
1. Add a `<ProjectReference />` element to A.csproj that points to B.csproj.
1. Run `dotnet pack`.

## Expected behavior

The generated nupkg file should contain both `A.dll` and `B.dll`.

## Actual behavior

The nupkg only contains `A.dll`. To get the project references' outputs to be included in the nupkg as well I have to add the following code to `A.csproj`:

```xml
<Content Include="$(OutputPath)/*.dll" Pack="true" PackagePath="lib/netcoreapp1.1/" />
```

I should not need to do this; ProjectReferences should be included in the package by default unless overridden in the project file. As I said above, certain pages on docs.microsoft.com indicate that this workaround should not be necessary.

Furthermore, this breaks the expectations of package authors who have a DLL that they are packaging, that requires other DLLs to function. However, those other DLLs are not useful on their own, and so creating one package per DLL is bad design. Without the MSBuild snippet included above, this cannot be done using current .NET CLI.

## Environment data

```
.NET Command Line Tools (1.0.0-rc4-004777)

Product Information:
 Version:            1.0.0-rc4-004777
 Commit SHA-1 hash:  18c01886cd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004777
```

**Comment by blackdwarf** [comment]
/cc @rohit21agrawal @emgarten according to [NuGet specc for pack](https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target#project-to-project-references) there are properties I can set to control this behavior, correct? 

Also @wjk you mention project references but then say "package references should be included". This is a typo?

**Comment by rohit21agrawal** [comment]
Not right now, but we plan to implement this in the next milestone

**Comment by blackdwarf** [comment]
@rohit21agrawal so in order to pack p2ps into the same nupkg, we need a workaround that was described in the starting issue?

**Comment by wjk** [comment]
@blackdwarf Yeah, that's a typo. Sorry about that.

**Comment by wjk** [comment]
Corrected my original post.

**Comment by rohit21agrawal** [comment]
Tracking this at  : https://github.com/NuGet/Home/issues/3891

**Comment by piotrpMSFT** [comment]
Closing in favor of NuGet/Home#3891

**Comment by rohit21agrawal** [comment]
@blackdwarf yes that is the correct workaround as described in the original issue

**Comment by TerribleDev** [comment]
@rohit21agrawal how would that work if you have a multi target build? in the workaround it specifies the framework moniker, which will not work if you have more than one framework moniker
