### ISSUE TITLE
Microsoft.DiaSymReader.Native DLLs unexpectedly included in package

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#5646]
## Steps to reproduce

1. Create `A.csproj`.
1. Set it to target `netcoreapp1.1`.
1. Run `dotnet pack`.

## Expected  behavior

The generated nuget package should only contain `A.dll`, the nuspec, and other miscellaneous metadata files.

## Actual behavior

The generated nuget package includes the following files:

* `content/Microsoft.DiaSymReader.Native.x86.dll`
* `content/Microsoft.DiaSymReader.Native.amd64.dll`
* `contentFiles/any/netcoreapp1.1/Microsoft.DiaSymReader.Native.x86.dll`
* `contentFiles/any/netcoreapp1.1/Microsoft.DiaSymReader.Native.amd64.dll`

These files should not be present. In addition, they are Windows-only and will not function properly if deployed to a non-Windows platform. As far as I can tell, I am in no way referencing these DLLs from my MSBuild project or from my code. Furthermore, `dotnet pack` emits a warning for each of the above files stating that the DLLs are not inside the `lib` folder, and as such will not be added to referencing projects. The offending files should not be there at all.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004777)

Product Information:
 Version:            1.0.0-rc4-004777
 Commit SHA-1 hash:  18c01886cd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004777
```

**Comment by blackdwarf** [comment]
I actually reprod this as well. The interesting part is that it does not repro when targeting the `netcoreapp1.0`.

**Comment by piotrpMSFT** [comment]
According to NuGet.org, [Microsoft.NetCore.App 1.1](https://www.nuget.org/packages/Microsoft.NETCore.App/1.1.0), when used with Target Framework netcoreapp1.1, references `Microsoft.DiaSymReader.Native (>= 1.4.0)`. I downloaded that nupkg and examined the nuspec which shows:

```

    <contentFiles>
      <files include="runtimes\win\native\Microsoft.DiaSymReader.Native.x86.dll" buildAction="Content" copyToOutput="true" />
      <files include="runtimes\win\native\Microsoft.DiaSymReader.Native.amd64.dll" buildAction="Content" copyToOutput="true" />
      <files include="runtimes\win\native\Microsoft.DiaSymReader.Native.arm.dll" buildAction="Content" copyToOutput="true" />
    </contentFiles>
```

It looks like the package is authored to treat these files as output that should be copied to the output of referencing projects. NuGet, CLI, and SDK all seem to be doing exactly the right thing.

**Comment by piotrpMSFT** [comment]
I opened an issue on the diasmreader repo to discuss the packaging concern. Closing this one.

**Comment by rohit21agrawal** [comment]
This is being tracked on the nuget side by   https://github.com/NuGet/Home/issues/4432

The actual fix is being done by aspnet.core team in their package. all related links are in the above nuget bug.

**Comment by tmat** [comment]
Workaround is to add a nuget reference to https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/1.4.2

**Comment by tmat** [comment]
Another option is to update to netcoreapp1.1.1.

**Comment by piotrpMSFT** [comment]
we'll plan to bring 1.1.1 into CLI next week. Assuming all goes well, the issue should be resolved in newer builds. If you can confirm @tmat's suggestion it would help!

**Comment by dasMulli** [comment]
I guess the SDK would need an update to the implicit reference it emits

**Comment by piotrpMSFT** [comment]
yep, opened https://github.com/dotnet/sdk/issues/860 to track.
