### ISSUE TITLE
'dotnet new web' overwrites 'dotnet new console'

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#5651]
## Steps to reproduce
dotnet new console
dotnet new web

## Expected  behavior
The second should fail because a project exists.

## Actual behavior
It happily overwrites. Further, the 'wwwroot' folder is not created.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004777)

Product Information:
 Version:            1.0.0-rc4-004777
 Commit SHA-1 hash:  18c01886cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\work\dotnets\1.0.0-rc4-004777\sdk\1.0.0-rc4-004777

**Comment by mlorbetske** [comment]
@billwert @blackdwarf in this instance it's making a `web.config` not the empty web template

**Comment by piotrpMSFT** [comment]
@mlorbetske does that mean this is by-design?

**Comment by blackdwarf** [comment]
@mlorbetske ooooooh...I see. `web` will resolve as an alias to `webconfig` which is an item template. This will get confusing.

**Comment by mlorbetske** [comment]
Unfortunately yes, this is by design. I wish we had something better to call either the empty web "web" template or the web.config "webconfig" to avoid the ambiguity when switching between project and item contexts

**Comment by mlorbetske** [comment]
@blackdwarf kind of - it's not explicitly aliased to web, this is an artifact of the partial matching that's done - web is an exact match on short name for the project template which is why it gets picked over the other web project templates, for item templates it's a partial match to the webconfig short name but it's unambiguous (no other item context templates contain "web")

**Comment by billwert** [comment]
Interesting. It's also useful context that I just noticed that the list of templates changes depending on the content of the directory - I hadn't noticed that the 'Config' items only appear once a project exists. 

Consider:
```
PS D:\work\scratch\test9>D:\work\dotnets\1.0.0-rc4-004777\dotnet.exe new web
Content generation time: 67.3824 ms
The template "Empty ASP.NET Core Web Application" created successfully.
PS D:\work\scratch\test9>dir


    Directory: D:\work\scratch\test9


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/10/2017  10:24 AM                wwwroot
-a----        2/10/2017  10:24 AM            544 Program.cs
-a----        2/10/2017  10:24 AM           1188 Startup.cs
-a----        2/10/2017  10:24 AM            307 test9.csproj


PS D:\work\scratch\test9>D:\work\dotnets\1.0.0-rc4-004777\dotnet.exe new web
Content generation time: 18.6667 ms
The template "Web Config" created successfully.
```
And highlights of the output from `dotnet new -all`:
```
Templates                                 Short Name       Language      Tags
---------------------------------------------------------------------------------------
Empty ASP.NET Core Web Application        web              [C#]          Web/Empty
Web Config                                webconfig                      Config
```

It is incredibly confusing that in this instance, an already reserved short name for a template is partially matched to another template when the first template fails. 

I'd much rather see this just fail in this instance. These names are incredibly short; perhaps partial match isn't worth it here?

Now that I know about dotnet/templating I'm happy to move the issue there.

**Comment by blackdwarf** [comment]
@billwert please do and thanks for raising this! :)

**Comment by billwert** [comment]
Opened dotnet/templating#302

**Comment by mlorbetske** [comment]
Closing this as the corresponding issue has been filed here https://github.com/dotnet/templating/issues/302
