### ISSUE TITLE
dotnet test project with NUnit runner not working

### ISSUE THREAD

**Issue by anuraj** [dotnet/cli#5654]
## Steps to reproduce

1. Create a unit test project.
2. Modify the project.json file to use NUnit as the test runner and framework.

Change XUnit to NUnit, change in the project.json

```
"testRunner": "nunit",
"dependencies": {
    "NUnit": "3.4.1",
    "dotnet-test-nunit": "3.4.0-beta-2"
}
```
Here is the sample unit test.

```
using NUnit.Framework;
namespace Tests
{
    [TestFixture]
    public class Tests
    {
        [Test]
        public void Test1() 
        {
            Assert.IsTrue(true);
        }
    }
}
```

3. Migrate the project using dotnet migrate command.
4. Restore the packages and re-run dotnet test command

## Expected  behavior

Unit test should run and display the results.

![nunit_test_execution](https://cloud.githubusercontent.com/assets/276411/22815557/2ba09ce2-ef82-11e6-90db-9bf912aaa710.png)

## Actual behavior

Tests are not executing.

![image](https://cloud.githubusercontent.com/assets/276411/22815639/ad3c3388-ef82-11e6-9321-7b835866b697.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by piotrpMSFT** [comment]
I haven't yet seen an nunit runner that we can use post-migration. The good folks @dotnet/vstest would know for sure, however. If there is a package we should be using it would be great to add it.

@anuraj it would be great if you can open an issue on https://github.com/microsoft/vstest and see if there is an available package + template that we can use for nunit! the folks over at https://github.com/nunit may have some updates as well!

**Comment by anuraj** [comment]
@piotrpMSFT I tried to update the package - dotnet-test-nunit, with latest version - 3.4.0-beta-3, but it is not working with dotnet test command. I found one issue in NUnit repo - [101](https://github.com/nunit/dotnet-test-nunit/issues/101), which talks about similar issue.

**Comment by codito** [comment]
@anuraj nunit adapter doesn't support netcore test projects yet (for csproj based projects). It is tracked on https://github.com/nunit/nunit3-vs-adapter/issues/297

**Comment by piotrpMSFT** [comment]
Closing in favor of the nunit bug.
