### ISSUE TITLE
Tracking Issue for #4248 (Error restoring packages in VS2015 when Preview3+ is installed)

### ISSUE THREAD

**Issue by Coruscate5** [dotnet/cli#5658]
Per the last comment on the closed issue #4248, there is a workaround, but it is out-of-proc & pretty annoying.

Can we use this issue to track a better fix, preferably one that works from inside VS2015?

**Comment by piotrpMSFT** [comment]
@Coruscate5 at the moment we don't have a plan for further .NET Core tooling updates in VS2015. The project system has changed fundamentally between project.json and csproj, and it only comes online in VS2017. Unfortunately, this is a `won't fix`.

**Comment by Coruscate5** [comment]
OK, thanks for the quick response - looking forward to VS2017 RTM then
