### ISSUE TITLE
System.Security.Cryptography.Native.so missing in publish output

### ISSUE THREAD

**Issue by sbomer** [dotnet/cli#5664]
Adding a particular packagereference (`System.Xml.XPath/4.3.0`) results in `System.Security.Cryptography.Native.so` not being output in publish step. I haven't tried this with other dependencies.

## Steps to reproduce

- `dotnet new console`
- add package reference: `<PackageReference Include="System.Xml.XPath" Version="4.3.0" />`
- `dotnet restore -r ubuntu.16.04-x64`
- `dotnet publish -r ubuntu.16.04-x64`

## Expected  behavior

`System.Security.Cryptography.Native.so` exists in publish directory.

## Actual behavior

Without the packagereference, everything is fine. With the packagereference, `System.Security.Cryptography.Native.so` is missing. If the app uses this library it crashes at runtime.

## Environment data
`dotnet --info` output:

```

.NET Command Line Tools (1.0.0-rc4-004788)

Product Information:
 Version:            1.0.0-rc4-004788
 Commit SHA-1 hash:  f2ad5a39ab

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/1.0.0-rc4-004788




```

**Comment by piotrpMSFT** [comment]
I suspect this is a case of a missing error message. the default console template targets netcoreapp1.0 which, iirc, did not include Ubuntu 16.04 support. You want to `dotnet new console -f netcoreapp1.1` instead, which should have the appropriate RID-specific artifacts. I'll try to test this speculation later, but give it a shot if you have time @sbomer. 

Assuming my guess is right, we'll want to fix the UX to make the situation more clear.

/cc @blackdwarf

**Comment by sbomer** [comment]
Thanks @piotrpMSFT, that does the trick! :)
I agree that a better error message would improve the experience, considering that the default hello world app targets netcoreapp1.0 and seems to work on Ubuntu 16.04 until it runs into this issue.

**Comment by blackdwarf** [comment]
Actually, this is not really computing. 1.0.3 has support for 14.04 and 16.04 Ubuntu, while 1.1.0 has added also support for 16.10. 

Since moving to 1.1 solved the issue, I will assume that has something to do with the version of the package reference being added since 4.3.0 indicates the 1.1 train.

**Comment by livarcocc** [comment]
If you try this scenario today you will get a series of package downgrades and it won't be possible to restore your project.
