### ISSUE TITLE
Update default project type GUID written to .sln in dotnet migrate

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#5665]
- `dotnet migrate` on a project.json project
- Open solution in Visual Studio
- Right click on project, choose Properties

**EXPECTED**: Roslyn project system properties page comes up:

![image](https://cloud.githubusercontent.com/assets/145043/22846965/15cf5f1c-ef9f-11e6-8cf4-19c2d6c2e2da.png)

**ACTUAL**: Default CPS project properties dialog comes up:

![image](https://cloud.githubusercontent.com/assets/145043/22846989/3daf3b92-ef9f-11e6-9732-cf27f4520e7f.png)

**FIX**: Change [default GUID](https://github.com/dotnet/cli/blob/f8de8d5a809ba0ee7755884051956a0a3c25653e/src/dotnet/ProjectInstanceExtensions.cs#L42) written to .sln from `13B669BE-BB05-4DDF-9536-439F39A36129` to `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC`

**EXPLANATION**: https://github.com/dotnet/roslyn-project-system/pull/1141 moved some capabilities to be "Default Capabilities".  These are keyed off the project type GUID, so if the generic CPS Guid is in the .sln they won't get included.  Changing to the legacy C# Guid will fix this (our selector will redirect to the CPS C# Guid off of which the default capabilities are keyed).

The default capabilities include AppDesigner, HandlesOwnReload, EditAndContinue, OpenProjectFile, and PreserveFormatting, so project editing and reloading and Edit and Continue support would also be broken in addition to the project properties,

@lifengl @333fred FYI

@srivatsn @piotrpMSFT

**Comment by piotrpMSFT** [comment]
@dsplaisted can you open a copy of this issue for `dotnet sln add` as well? We need the fix there as well.

**Comment by natemcmaster** [comment]
I ran into this as well, but hit it using dotnet sln add. @piotrpMSFT https://github.com/dotnet/cli/issues/5688

**Comment by livarcocc** [comment]
Closing this one as a dup of https://github.com/dotnet/cli/issues/5688.
