### ISSUE TITLE
New console app + any dependency in Linux fails to restore

### ISSUE THREAD

**Issue by shiftylogic** [dotnet/cli#5666]
## Steps to reproduce
* Install latest [.NETCore v2 on linux](https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries)
* untar package
* dotnet new console
* Edit .csproj to add Newtonsoft.Json (any version) package reference
* dotnet restore

## Expected  behavior
It restores the packages and then is able to compile.

## Actual behavior
dudeman@trashme:~/goo$ ../dotnet/dotnet restore
  Restoring packages for /home/dudeman/goo/goo.csproj...
/home/dudeman/dotnet/sdk/2.0.0-alpha-004853/NuGet.targets(97,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [/home/dudeman/goo/goo.csproj]
/home/dudeman/dotnet/sdk/2.0.0-alpha-004853/NuGet.targets(97,5): error :   The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/home/dudeman/goo/goo.csproj]
/home/dudeman/dotnet/sdk/2.0.0-alpha-004853/NuGet.targets(97,5): error :   The type initializer for 'Http' threw an exception. [/home/dudeman/goo/goo.csproj]
/home/dudeman/dotnet/sdk/2.0.0-alpha-004853/NuGet.targets(97,5): error :   The type initializer for 'HttpInitializer' threw an exception. [/home/dudeman/goo/goo.csproj]
/home/dudeman/dotnet/sdk/2.0.0-alpha-004853/NuGet.targets(97,5): error :   Unable to load DLL 'System.Net.Http.Native': The specified module could not be found. [/home/dudeman/goo/goo.csproj]
/home/dudeman/dotnet/sdk/2.0.0-alpha-004853/NuGet.targets(97,5): error :    (Exception from HRESULT: 0x8007007E) [/home/dudeman/goo/goo.csproj]

## Environment data
`dotnet --info` output:

dudeman@trashme:~/goo$ ../dotnet/dotnet --info
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/dudeman/dotnet/sdk/2.0.0-alpha-004853/

**Comment by piotrpMSFT** [comment]
@shiftylogic the new project templates in 2.0.0 are still very primitive and designed only to support CLI repo builds. @mlorbetske is working on templates for 2.0.0 all up but they won't be ready for some time.

**Comment by nlowe** [comment]
@piotrpMSFT I'm also experiencing this in migrated projects using `1.0.0-rc4`, is that a separate issue?

```
  The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
    The type initializer for 'Http' threw an exception.
    The type initializer for 'HttpInitializer' threw an exception.
    Unable to load DLL 'System.Net.Http.Native': The specified module could not be found.
     (Exception from HRESULT: 0x8007007E)
/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error : Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json'. [/home/nathan/projects/netcore-multiproject/src/MyProject.Web/MyProject.Web.csproj]
/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/home/nathan/projects/netcore-multiproject/src/MyProject.Web/MyProject.Web.csproj]
/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'Http' threw an exception. [/home/nathan/projects/netcore-multiproject/src/MyProject.Web/MyProject.Web.csproj]
/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The type initializer for 'HttpInitializer' threw an exception. [/home/nathan/projects/netcore-multiproject/src/MyProject.Web/MyProject.Web.csproj]
/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   Unable to load DLL 'System.Net.Http.Native': The specified module could not be found. [/home/nathan/projects/netcore-multiproject/src/MyProject.Web/MyProject.Web.csproj]
/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :    (Exception from HRESULT: 0x8007007E) [/home/nathan/projects/netcore-multiproject/src/MyProject.Web/MyProject.Web.csproj]

```

Environment Info:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004771
```

**Comment by Themodem** [comment]
Same issue here on linux

Linux lappy 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux
dotnet --version = 1.0.0-rc4-004771

My .csproj file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="1.1.0" />
    <PackageReference Include="YamlDotNet.NetCore" Version="1.0.0" />
  </ItemGroup>
</Project>
```

If i run dotnet restore i get the same error as @piotrpMSFT 

If I remove the line `<PackageReference Include="YamlDotNet.NetCore" Version="1.0.0" />` everything restores as expected but obviously without the yaml package.

If I get VS2017 to run the restoration it works and pulls in the correct packages.

**Comment by piotrpMSFT** [comment]
Ok, since we're seeing this on 1.0.0 I'm moving the issue back to that milestone.

@rohit21agrawal @rrelyea can you guys take a look?
@eerhardt as well. I'm wondering if this might be the networking stack trying to load a pre-req and failing with an exception.

**Comment by piotrpMSFT** [comment]
@nlowe @Themodem can you try installing latest CLI from the home page of this repo and see if you get a repro?

**Comment by piotrpMSFT** [comment]
Also, can you guys confirm you followed the installation instructions here: https://www.microsoft.com/net/core#linuxfedora

The more I think about this, and discuss it with @rohit21agrawal offline, I'm becoming convinced that you are missing pre-requisites [likely one of our crypto dependencies] and are therefore seeing a failure. Those installation instructions should provide you with the right steps to get dependencies.

The reason you're only seeing failures if adding a new dependency is because CLI brings with it an offline cache of all packages needed to build ASP.NET apps. It's likely that your restore is causing NuGet to hit the internet for the first time and thereby trying to load the missing dependencies.

**Comment by Denommus** [comment]
I'm also having having this problem, and I don't think it's due to the lack of dependencies, since I have installed from source and it compiled just fine.

.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004771

**Comment by nlowe** [comment]
I don't think it's a dependency problem. Here's what the AUR package marks as dependencies:

```
Depends On      : lldb  libunwind  icu  lttng-ust  openssl  curl
```

I'm going to try building and installing the latest as recommended by @piotrpMSFT .

**Comment by nlowe** [comment]
> can you try installing latest CLI from the home page of this repo and see if you get a repro?
Do you mean as in build from master or pick one of the binaries that's closest to our distribution?

I tried the latest 16.04 binaries (the 14.04 ones failed to execute `dotnet --version` with an exception) and still experience the same problem. Version comparison:

```
[nathan@nathan-arch dotnet-latest-bin]$ dotnet --version
1.0.0-rc4-004771
[nathan@nathan-arch dotnet-latest-bin]$ ./dotnet --version
1.0.0-rc4-004823
[nathan@nathan-arch dotnet-latest-bin]$ ./dotnet --info
.NET Command Line Tools (1.0.0-rc4-004823)

Product Information:
 Version:            1.0.0-rc4-004823
 Commit SHA-1 hash:  4634d0e120

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/nathan/Downloads/dotnet-latest-bin/sdk/1.0.0-rc4-004823
```

**Comment by dasMulli** [comment]
@nlowe been talking on slack with @Denommus and the latest suspect was curl/libcurl version 3 vs 4 on arch...

**Comment by nlowe** [comment]
An update was made to the AUR pkgbuild. I can now restore packages. From looking at the diff, it appears that `System.Net.Http.Native.so` was not being copied to `${_fxdir}/bin/Linux.x64.Release/Native/${file}`

**Comment by Themodem** [comment]
Confirmed, the latest AUR build works as expected.

**Comment by Denommus** [comment]
Also working here.
