### ISSUE TITLE
Package management commands

### ISSUE THREAD

**Issue by lambdakris** [dotnet/cli#5675]
## Steps to reproduce

Install .NET Core SDK 1.0 RC4

## Expected  behavior

I've been playing around with the dotnet cli, thinking things were at a place where it might be a good idea to write some blog posts, but one of the things that I quickly ran into and was legitimately disheartening was that I could not perform common tasks available in other common package managers I'm used to, such as npm, yarn, pip, and paket. Here are some things I figured I would be able to do:

1. list installed packages from the command line
2. list outdated packages from the command line
3. show details and dependency tree for a package from the command line

Are these commands something that could be incorporated in the not too distant future?

## Actual behavior

Unable to list installed packages from the command line, unable to list outdated packages from the command line, unable to show details and dependency tree for a package from the command line.

## Environment data
`dotnet --info` output:

$ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5199
