### ISSUE TITLE
Should be able to suppress creation of default package dependencies

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#5676]
## Steps to reproduce

Following the discussion in #5645, I am using a variant of my suggestion there to pack multiple DLLs into one NuGet package. When I run `dotnet pack`, the dependent assemblies are included in the nupkg file as intended. However, also included are NuGet dependencies for each `<ProjectReference>` item in the csproj file that created the package. I don't want these to be there, and they are causing the package install to fail (because the referenced packages do not, and will never, exist on their own).

## Expected behavior

I should be able to configure `dotnet pack` to not generate NuGet dependencies for `<ProjectReference>`s by default.

## Actual behavior

I can't (or, at least, don't know how to) do this.

## Environment data

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by ThadHouse** [comment]
Definitely looking for a workaround here too. There are a lot of projects in the world that do very similar things to this. This case was supported in VS 2015 and NuGet 3 with the `-IncludeReferencedProjects` parameter. Going to be a showstopper for a bunch of projects attempting to move to .NET Standard and .NET Core.

**Comment by piotrpMSFT** [comment]
Moved to nuget/home
