### ISSUE TITLE
migrate a project.json to csproj with Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4

### ISSUE THREAD

**Issue by damienbod** [dotnet/cli#5678]
## Steps to reproduce

migrate a project.json to csproj with Microsoft.EntityFrameworkCore.Tools.DotNet 1.1.0-preview4

When I migrate to msbuild, the Microsoft.EntityFrameworkCore.Tools.DotNet is not migrated correctly.

## Expected  behavior

dotnet ef migrations add test should work with a csproj
```xml
<DotNetCliToolReference  Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
```

## Actual behavior

```xml
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.1.0-preview4" />
```

This does not work with csproj.

fails

## Environment data
`dotnet --info` output:

**Comment by damienbod** [comment]
https://github.com/aspnet/EntityFramework/issues/7544#event-957690703

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/5632.
