### ISSUE TITLE
dotnet new: "dll" could be an alias for "classlib"

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/cli#5682]
## Steps to reproduce
Want to create a new project, forget exact template name. Guess `dotnet new dll`.

## Expected  behavior
A new project, exactly as if I had typed the formal name `classlib`.

## Actual behavior
```
No templates matched the input template name: [dll]
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by blackdwarf** [comment]
@rainersigwald this should be moved to dotnet/templating since the templates are housed there.

**Comment by rainersigwald** [comment]
Indeed. https://github.com/dotnet/templating/issues/318.
