### ISSUE TITLE
dotnet restore on a solution does not trigger BeforeTargets="Restore" targets

### ISSUE THREAD

**Issue by atanasa** [dotnet/cli#5683]
## Steps to reproduce
1. Create a default .Net Standard (or .Net Core) library project (in Visual Studio or dotnet new)
2. Edit the csproj file to include the following target:
```xml
  <Target Name="PreRestoreCanary" BeforeTargets="Restore">
    <Exec Command="echo Canary" />
    <Copy DestinationFolder="Canary" SourceFiles="Class1.cs" />
  </Target>
```
3. Run `dotnet restore` on the solution file (or in the solution folder)

I've included sample solution files here: 
[PreRestoreRepro.zip](https://github.com/dotnet/cli/files/771834/PreRestoreRepro.zip)

## Expected  behavior
(ideally) The text Canary is printed on the console before the restore details
A folder called Canary with a file Class1.cs is present in the ClassLibrary1 folder.

## Actual behavior
Nothing happens

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by emgarten** [comment]
@atanasa is this specific to the restore target? are you able to get this to run before a target you create yourself?

The restore target for reference is here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L86

**Comment by atanasa** [comment]
Running `dotnet restore` on the project file (csproj) instead triggers the target correctly. The issue is when I run it on the solution file. Also when Visual Studio 2017 RC does restore it does not trigger it.

I am trying to implement a pre-restore event, so the Restore target is significant for my case. According to this documentation https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#target-build-order this should be the way to implement it.

**Comment by emgarten** [comment]
When running Restore on the solution the Restore target in the metaproj is executed, not the Restore target in the project.

Try using ``BeforeTargets="_GenerateRestoreProjectSpec"``, this should execute in the project during both project restore and solution restore.

**Comment by atanasa** [comment]
Thanks, that change worked for dotnet cli. 
I have some questions:
1. Is there some way to make it work in Visual Studio 2017 as well?
2. Is there some place I can read about this metaproj? 
3. Is this `"_GenerateRestoreProjectSpec"` target part of the public contract?
4. Is there some way to enable verbose mode on that restore? It seems the `-v d` option is ignored and the setting for verbosity in VS is also not applied to the restore operation.

**Comment by emgarten** [comment]
> Is there some way to make it work in Visual Studio 2017 as well?

Restore in VS 2017 doesn't execute through MSBuild, it reads the projects using the in memory model instead of through the targets.

> Is there some place I can read about this metaproj?

Set the env var MSBuildEmitSolution=1 to persist the metaproj files to disk

> Is this "_GenerateRestoreProjectSpec" target part of the public contract?

No, but it is currently the only one available and the SDK will referencing this also

> Is there some way to enable verbose mode on that restore?

dotnet.exe restore /v:diag   

Additional parameters are passed directly to msbuild

**Comment by atanasa** [comment]
As it is described in the [documentation](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/cli-msbuild-architecture):

> For example, the next version of Visual Studio will not call into dotnet restore command to restore dependencies for .NET Core projects, it will use the "Restore" target directly. Since these are MSBuild targets, you can also use raw MSBuild to execute them using the dotnet msbuild command. 

Are there plans to make VS call into the Restore target?

**Comment by emgarten** [comment]
> Are there plans to make VS call into the Restore target?

There are no plans for this currently. VS Restore operates using project information already loaded into memory.

Can you explain a bit more about your scenario and what you need to run before restore? It does seem like a general extension point for this could be useful.

**Comment by atanasa** [comment]
I am running a script that "restores" packages from a server that is not NuGet-compatible. Those are later fed to the usual NuGet restore through a directory package source. Essentially extending the restore logical operation to consume a custom source of packages.

**Comment by emgarten** [comment]
@atanasa would you open a nuget issue on https://github.com/nuget/home/issues to track this. Describe your scenario and that you need a hook to run a script before restore in VS that ideally works the same as the target.

**Comment by livarcocc** [comment]
Closing this one in favor of the NuGet one.
