### ISSUE TITLE
dotnet restore failure should list the feeds when it fails to find a package.

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#5684]
I was trying to restore packages in a repo when I ran into an error like below:

```
C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771\NuGet.targets(97,5): error : Failed to retrieve information about 'NETStandard.Library' from remote source 'c:\does-not-exist'. [C:\github\configuration\Configuration.sln]
```
I tried to find more information by doing: `dotnet restore -v diag` but this too didn't give any useful information.

I later realized that I had a temporary package source (pointing to a local folder) added a while back via Visual Studio which was being picked by dotnet restore.

It would be nice to print information about the feeds and the configuration files used for the restore information at least when specifying the verbosity flags like `detailed` or `diagnostic`

## Steps to reproduce
- Clone the repo `http://github.com/aspnet/configuration` and `cd configuration`
- Do a `dotnet restore` on any repo which you would have expected to work usually.
- Open Visual Studio and add a package source like `c:\doest-not-exist`
- Do a `dotnet restore -v diag` and this also doesn't give much information as to where its picking up the sources from. 

## Expected  behavior
Show detailed information of the feeds and NuGet.config source files when using the verbosity flags for 'detailed' or 'diagnostic'

## Actual behavior
Error similar to the following:
`C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771\NuGet.targets(97,5): error : Failed to retrieve information about 'NETStandard.Library' from remote source 'c:\does-not-exist'. [C:\github\configuration\Configuration.sln]`

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by blackdwarf** [comment]
@kichalla `restore` by default tells you which NuGet.config files it used in a restore operation as well as feeds it used, which is an aggregate of the feeds in all of the NuGet.config files the operation uses. A sample output is below:

```bash
  NuGet Config files used:
      /Users/username/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
```

Is this what you meant?

**Comment by kichalla** [comment]
@blackdwarf yes that is what I meant but I wasn't seeing that for the repo that I was working on. I have update the repro steps to use a repo that I had trouble with.

**Comment by piotrpMSFT** [comment]
moved to nuget/home#4594
