### ISSUE TITLE
dotnet build on csproj does not run analyzers consistently if stylecop.json is referenced as AdditionalFiles

### ISSUE THREAD

**Issue by jake-brandt** [dotnet/cli#5685]
## Steps to reproduce
- Create a .NET Core 1.1 class library
- Add StyleCop.Analyzers v1.0.0 as a reference to your netcore1.1 project
- Add or configure an existing code analysis ruleset file to ignore any current SA**** errors/warnings seen in a build. See [https://www.linkedin.com/pulse/supporting-roslyn-analyzers-visual-studio-2017-net-core-jake-brandt](https://www.linkedin.com/pulse/supporting-roslyn-analyzers-visual-studio-2017-net-core-jake-brandt) for information on setting up a ruleset in a Core project
- Add or configure an existing code analysis ruleset file to include SA1203 as an Error
- Add some code to declare a private class variable BEFORE a constant
- (Build 1) Build within Visual Studio 2017 RC
- (Build 2) Run "dotnet build" within project directory
- Add stylecop.json file to project, set build action for file to "C# analyzer additional file"
- Edit stylecop.json such that it contains:
`{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "orderingRules": {
      "elementOrder": [
        "constant"
      ]
    }
  }
}`
- (Build 3) Build within Visual Studio 2017 RC
- (Build 4) Run "dotnet build" within project directory
- Change stylecop.json build action to "None"
- (Build 5) Build within Visual Studio 2017 RC
- (Build 6) Run "dotnet build" within project directory

## Expected  behavior
All 6 builds should report the build error `XXXX.cs(*,**): error SA1203: Constant fields must appear before non-constant fields`

## Actual behavior
It seems as though either VS2017RC is not correctly using the stylecop.json analyzer file, or dotnet CLI is not correctly using the stylecop.json analyzer file.

Build 1 (VS) reports error
Build 2 (dotnet CLI) reports error
Build 3 (VS) reports error
Build 4 (dotnet CLI) reports NO ERROR
Build 5 (VS) reports error
Build 6 (dotnet CLI) reports error

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by jake-brandt** [comment]
This may be due to differing supported versions of Roslyn by Stylecop - updating Stylecop.Analyzers to 1.1beta may have addressed this. Is there perhaps a different version of MSBuild running between VS2017 and dotnet CLI?

**Comment by piotrpMSFT** [comment]
@jake-brandt it depends :) It looks like you're using the RC3 CLI while the latest VS uses RC4. We do keep msbuild in-sync for a given release wave but they diverge if components are installed at different versions.

**Comment by jake-brandt** [comment]
Ah! Thank you Piotr.

**Comment by nover** [comment]
@piotrpMSFT I'm experiencing similar issues with the final version of VS2017 and the dotnet core tooling - the rules are properly applied with compiling via VS, but with `dotnet build` the rules are not applied at all.

Any suggestions?

**Comment by jake-brandt** [comment]
Upgrading to the latest prerelease build of StyleCop.Analyzers improved
things for me - there appears to be improved support in that build.
