### ISSUE TITLE
Should ScriptCommandResolverPolicy implement ICommandResolverPolicy?

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/cli#5687]
As `DefaultCommandResolverPolicy` and `PathCommandResolverPolicy` implement `ICommandResolverPolicy`, it seems odd that `ScriptCommandResolverPolicty` doesn't implement it (and hence that one can't pass a `ScriptCommandResolverPolicy` to `Command.Create`.  Is that an oversight, or am I just misunderstanding what `ScriptCommandResolverPolicy` is for?

**Comment by livarcocc** [comment]
This is a relic from project.json time. It is no longer being used in the latest versions of the CLI. We used to use this to resolve commands in the scripts section of the project.json file.
