### ISSUE TITLE
dotnet sln add uses wrong project type GUID

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5688]
Projects added to a sln file using `dotnet sln add` use the wrong GUID, which means VS doesn't correctly load things like the project properties page.

## Steps to reproduce
dotnet new sln
dotnet new classlib -o SampleProj
dotnet sln add SampleProj/SampleProj.csproj

## Expected  behavior
Solution file contains
```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SampleProj", "SampleProj\SampleProj.csproj", "{9195DDF0-49EA-45F6-9527-7F7DFCA02BCB}"
EndProject
```

## Actual behavior
```
Project("{13B669BE-BB05-4DDF-9536-439F39A36129}") = "SampleProj", "SampleProj\SampleProj.csproj", "{9195DDF0-49EA-45F6-9527-7F7DFCA02BCB}"
EndProject
```

## Environment data
`dotnet --info` output: 1.0.0-rc4-004771

**Comment by livarcocc** [comment]
This is similar to https://github.com/dotnet/cli/issues/5665. I don't think we have closed in what GUID to use just yet.

@srivatsn Let us know when we have closed on this.

**Comment by davkean** [comment]
@livarcocc Who are you talking with on our side on right GUID? 

We were supposed to read this from DefaultProjectTypeGuid property - which in the C# case would be "FAE04EC0-301F-11D3-BF4B-00C04F79EFBC".

**Comment by srivatsn** [comment]
I was waiting until we figure out how we are disabling DPL before saying that CLI should burn in the legacy guid. That has been sorted out now. So yes, @livarcocc we can use the guid that's mentioned in @davkean's comment.

**Comment by jgoshi** [comment]
The work to have the DefaultProjectTypeGuid isn't available yet. Here is the PR:
https://github.com/Microsoft/msbuild/pull/1607

And work also has to be done for F#. What we will eventually do in the CLI is to throw if there isn't an explicit ProjectTypeGuid or a DefaultProjectTypeGuid defined. But until the work for writing DefaultProjectTypeGuid goes in we need to burn in some default. I can change that default to be the C# one. But that means we will be wrong in other cases (like for a VB project or F# project or any other type of project).
