### ISSUE TITLE
Project references: Allow referencing with a name different than the containing folder

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#569]
_From @muratg on July 22, 2015 19:29_

_Copied from original issue: aspnet/dnx#2312_

**Comment by muratg** [comment]
_From @anurse on July 23, 2015 0:9_

Thoughts (just a bit of a brain dump to facilitate discussion/design):
* We could allow a `path` property under the dependency. That starts to smell a lot like `HintPath` though...
* We could allow a project.json to have an **optional** `name` property to change the name of the project. This would mean someone has to scan all the project.json files in scope in order to determine the name of each project. Perhaps we could do that during `dnu restore` and put it in the lock file?

**Comment by muratg** [comment]
I like the second option, although I'm sure @davidfowl will have some (probably reasonable) perf concerns.

**Comment by muratg** [comment]
_From @troydai on July 23, 2015 23:56_

_Based on the discussion I had with @anurse_

Proposal 1: Lock file based project reference map

The motivation behind this change is to allow referencing different projects under folders with same name. With that been said, when referenced projects are indeed identical or different version/iteration of same projects the ambiguous should still be treated as an exception.

Key pillars:

__Project Name__
Refine the concept of project name. Add a property `id` to the project.json schema. The value of the property is used as project name when it presents. The folder name as project name is a fallback strategy.

__Project references map in lock file__
One of the downside of using project.json property to determine project name is the performance hit. 

For runtime, this can be mitigated by introduce a projects reference map in the lock file, which maps from project name to the relative path to the referenced projects' project.json files. 

Scenarios:

__dnu restore__

When `ProjectResolver` is initialized it loads all project.json in the search paths, deserialize them and resolve the actual name. To optimize the performance, the deserialized json objects should be cached.

At this stay with the assistance of property name, if there are still ambiguous names exception will be thrown and procedure will be terminated.

The referenced project names and relative paths will be eventually written in the lock file.

__dnx run / dnu build__

Other than relies on `ProjectResolver` to resolve projects, lock file is load and projects map is used to local the referenced projects.

Issues:

* Further complicate the lock file;
* Changing project name requires a dnu restore;
* Introduce paths in the lock file

Option:

* Avoid touch the lock file. Load name from project.json every time. Using a performance optimized deserializer to read just enough content to determine the name.

**Comment by muratg** [comment]
_From @anurse on July 24, 2015 17:13_

> Introduce paths in the lock file

This is my biggest concern but I don't see a better way if we want to support this.

Looks like a reasonable first pass at design to me. We'll discuss in the meeting :+1:

**Comment by muratg** [comment]
_From @troydai on July 24, 2015 17:22_

I'm not absolutely sure about the `path` in locks file, either.

**Comment by muratg** [comment]
_From @davidfowl on August 6, 2015 22:13_

See https://github.com/aspnet/dnx/issues/1559

**Comment by muratg** [comment]
_From @davidfowl on August 8, 2015 6:11_

Lock file is the way to go here.

**Comment by muratg** [comment]
_From @anurse on August 10, 2015 2:34_

Yeah, it's pretty much the only option, which is what we landed on. It's unfortunate that it makes the lock file no longer portable, but I think that was inevitable (and wasn't really something you could rely on anyway).

**Comment by muratg** [comment]
_From @Eilon on August 14, 2015 20:0_

Moving to Backlog - we are not planning on doing this feature for v1. The workaround for now is to rename the folder to have the desired name.

@troydai can you close out the PR for now? We will revisit in the future.

**Comment by gregbty** [comment]
Is there a reason why this was closed? Is it due to the fact that project.json is going away?
