### ISSUE TITLE
No executable found matching command "dotnet-migrate" - VS2017

### ISSUE THREAD

**Issue by 304NotModified** [dotnet/cli#5692]
## Steps to reproduce

Open VS2015 solution (NLog.Web.AspNetCore.sln, (https://github.com/NLog/NLog.Web/blob/e52d77e96fb23785990af910ef2c8d6883efcac2/NLog.Web.AspNetCore.sln) in VS2017 RC

It needs migration

![image](https://cloud.githubusercontent.com/assets/5808377/22905374/511dd1ea-f240-11e6-951d-faa875e84d6d.png)

reload project and got a upgrade dialog:

![image](https://cloud.githubusercontent.com/assets/5808377/22905396/636af3fa-f240-11e6-86a2-4fc663acef8a.png)

Press, "OK"

## Expected  behavior

Upgrades to new format

## Actual behavior

Fails. Reinstall VS2017 didn't help. 

```
Overview
Project	Path	Errors	Warnings	Messages
NLog.Web.AspNetCore	NLog.Web.AspNetCore\NLog.Web.AspNetCore.xproj	2	1	3
Solution and projects
NLog.Web.AspNetCore
Message
NLog.Web.AspNetCore\NLog.Web.AspNetCore.xproj: Could not read post-migration report at 'C:\Users\j.verdurmen\AppData\Local\Temp\yctk2ww2.npi'.
NLog.Web.AspNetCore\NLog.Web.AspNetCore.xproj: Failed to migrate XProj project NLog.Web.AspNetCore. 'dotnet migrate --skip-backup -s -x "X:\nlog\NLog.Web\NLog.Web.AspNetCore\NLog.Web.AspNetCore.xproj" "X:\nlog\NLog.Web\NLog.Web.AspNetCore" -r "C:\Users\j.verdurmen\AppData\Local\Temp\yctk2ww2.npi" --format-report-file-json' exited with error code 1.
NLog.Web.AspNetCore\NLog.Web.AspNetCore.xproj: No executable found matching command "dotnet-migrate"
```

## Environment data
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

![image](https://cloud.githubusercontent.com/assets/5808377/22905518/ccbe699a-f240-11e6-8e76-d18d4c73488e.png)

**Comment by livarcocc** [comment]
Can you check your path? I suspect that you installed x86 of VS and you had x64 CLI in your PATH already. So, when you run dotnet, it is picking the x64 one, for you have you not installed the latest CLI for.

**Comment by 304NotModified** [comment]
I've got (in this order):
C:\Program Files (x86)\dotnet\ 

 ```
C:\Program Files (x86)\dotnet>dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

and `dotnet` from `C:\Program Files\dotnet\`.

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by livarcocc** [comment]
That's the problem. We are hitting the preview2-1, which does not implement dotnet migrate. You can either install an x64 version of rc4-004771 or update your PATH that version of dotnet come first in the path.

**Comment by 304NotModified** [comment]
Thanks! Was NLog expecting that vs was dependent of the path

Could I still build apps build on preview 2-1 then?

**Comment by livarcocc** [comment]
You can do that by pinning that version using a global.json file with "sdk": { "version": "1.0.0-preview2-1-003177" }. I would still make sure that I have both versions of the CLI (preview2 and rc4) installed for the same platform (x86 and x64) so that you don't have to keep changing your PATH. If you do that, global.json configuration should be enough for you.

Though, at this point, we are recommending that everyone move to the new version of the CLI.

**Comment by livarcocc** [comment]
I am going to go ahead and close this issue. If there is anything else that you want to know, please, just go ahead and re-activate it.

**Comment by 304NotModified** [comment]
Thanks for the support!

**Comment by andegre** [comment]
Why is it so hard to tell where the installer is for this CLI? I installed VS2017, obviously doesn't work. Where's the installer to get the CLI RC3?
