### ISSUE TITLE
dotnet restore timeouts on ubuntu 16.04 

### ISSUE THREAD

**Issue by fvoncina** [dotnet/cli#5696]
## Steps to reproduce
This problem only occurs on AWS Ubuntu 16.04, in other ubuntu installations works fine.
Im working with csproj base projects
- get source from repo
- dotnet restore

## Expected  behavior
Restore of packages

## Actual behavior
Times out with the following message:

/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/home/ubuntu/h2o-dotnet/H2O/H2O.sln]

/opt/dotnet/sdk/1.0.0-rc4-004771/NuGet.targets(97,5): error :   The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms. [/home/ubuntu/h2o-dotnet/H2O/H2O.sln]

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /opt/dotnet/sdk/1.0.0-rc4-004771

**Comment by livarcocc** [comment]
Can you access the URL from within the VM, regularly?

**Comment by fvoncina** [comment]
Yes

**Comment by fvoncina** [comment]
Seems to be a problem in the DNS of api.nuget.org, from inside the aws server it resolves to 72.21.81.200 and the server cannot reach the IP

**Comment by livarcocc** [comment]
Given that this seem to be a problem in VM, I am going to close this issue.

**Comment by CalebMacdonaldBlack** [comment]
I'm having this problem aswell

**Comment by fvoncina** [comment]
@CalebMacdonaldBlack I've managed to workaround it by putting another ip for the host api.nuget.org:
93.184.221.200 api.nuget.org

**Comment by CalebMacdonaldBlack** [comment]
@fvoncina Hey thanks for the reply. How do I set the ip for a host in ubuntu?
