### ISSUE TITLE
[infra] dotnet test should be run against stage0 but should run tests on stage2

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5697]
Here is example of broken scenario which is pretty painful to track because of using stage2 for building test.
We should at minimum set a recommendation to use stage0 for local testing
## Steps to reproduce
- make a bug in dotnet build so that build is broken
- run dotnet-build.Tests

## Expected  behavior
Test failures

## Actual behavior
Tests are not being run - really weird error messages - it is also possible that the tests will pass even though they shouldn't - there is basically no way of saying if the product is working as the test pass may be a bug

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
We have made a change where E2E tests in the CLI will run against whatever CLI was used to run dotnet test verb itself, this way it is clearer to the person running the test which CLI it is using.
