### ISSUE TITLE
dnu publish doesn't exclude output folder

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#570]
_From @anurse on July 17, 2015 20:2_

I was seeing a weird recursive behavior with dnu publish when I did the following:

1. Create a project
2. In the project directory, run `dnu publish -o output`

Expected: dnu publish finishes and publishes the app properly

Actual: dnu publish crashes with a "path too long" error because it got into a recursive loop continually publishing the `output` subdirectory.

I need to sanity check that this repros, but I wanted to file it so it didn't get forgotten.

_Copied from original issue: aspnet/dnx#2288_

**Comment by piotrpMSFT** [comment]
This is not an issue in dotnet publish.
