### ISSUE TITLE
F# updates for .NET Core Sdk 1.0.0 RTW

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#5718]
ref f# roadmap for sdk 1.0.0 https://github.com/dotnet/netcorecli-fsc/issues/72

For .NET Core Sdk 1.0.0 RTW.

It doesnt matter for VS (new fsproj is not supported anyway), and is just for .NET Core Sdk because other editors (VScode/emacs/vim) works with that, so **is supported by community and used already by dev**

Pratically the `dotnet-compile-fsc` is removed, and an msbuild task is used (old `FscTask`).
All `fsc`,`FSharp.Build`,`FSharp.Core` minus sdk integration are signed MS assemblies.

- [x] `FSharp.Core` and `FSharp.Compiler.Tools` v4.1.0 packages are published on nuget.org
- [x] `FSharp.Sdk` and `FSharp.NET.Sdk` v1.0.0 are published on nuget.org
- [x] update template PR ~~https://github.com/dotnet/templating/pull/315~~ https://github.com/dotnet/templating/pull/340 for new template. Done, see PR
- [ ] change pinned version of tempaltes, to merge new templates in this repo

Nice to have, if possibile, because preview4/rc3 was easier than rc4:

- ~~[ ]~~ support aliases (fsharp = f#) in `dotnet new lib -lang fsharp` (ref https://github.com/dotnet/templating/issues/296 ). to avoid bugs. `NOT 1.0 RTM, MOVED TO 2.0`
- ~~[ ]~~ something to set default lang for `dotnet new` as f# (ref issue https://github.com/dotnet/templating/issues/115 and  closed PR https://github.com/dotnet/cli/pull/5679 ). to make dev life nice `NOT 1.0 RTM, MOVED TO 2.0`

Examples of proposed fsproj: https://github.com/dotnet/netcorecli-fsc/tree/master/examples/rc4

/cc @dsyme @cartermp  @KevinRansom 

@livarcocc @piotrpMSFT @mlorbetske i need help/shiproomcheck/approvals to merge the templates.

Default template **is really really important**, because removing dotnet-compile-fsc and using official packages (fsharp.core, fsharp.compiler.tools) in templates, we make it easy for new users, and fix tons of errors, leaving a possibility to update (if needed) all f# components without changing dotnet/cli

@livarcocc before @piotrpMSFT asked me to speak with you about dotnet-compile-fsc, anytime tonight (from now) on skype/slack/gitter?

**Comment by ErikSchierboom** [comment]
Fantastic work!

**Comment by enricosada** [comment]
finished PR with updated templates https://github.com/dotnet/templating/pull/315 . Not a lot of diff but important changes

**Comment by enricosada** [comment]
replaced dotnet/templating#315 with dotnet/templating#340 to rebase it against `rel/vs2017/post-rtw` branch (ref @mlorbetske https://github.com/dotnet/templating/pull/315#issuecomment-280374507 )

**Comment by livarcocc** [comment]
@enricosada Is there anything left for this? Can we close?

**Comment by enricosada** [comment]
@livarcocc everything is awesome!
Thx a lot everyone for help!
