### ISSUE TITLE
Create "dnu patch" commands to allow manual servicing of machines

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#572]
_From @DamianEdwards on July 2, 2015 4:51_

Creation of a new set of commands in `dnu` to enable management of machine-wide patches. This could be used by system admins to manage the installed servicing patches on servers on all platforms. On Windows of course we will be able to push out critical fixes via Windows Update but on Linux we expect machine-wide patches to be managed manually by the server admin. That said, this tool would work everywhere.

Note, this is **not** a machine-wide package redirection feature. It is explicitly only about patching assemblies in accordance to the rules used by https://github.com/aspnet/dnx/tree/dev/src/Microsoft.Framework.Runtime/Servicing

Straw-man list of scenarios to support:
- List all installed patches for:
  - All packages/assemblies machine-wide
  - All packages/assemblies for a given project
  - A given package/assembly
- List available patches for the same as above
- Install all available patches for a give project/package/assembly
- Integration with `dnu publish` to support detection of installed patches at publish time and embed that info into the bundle  to allow various options when the app is launched after published (e.g. fail to run if patches not installed, force-install patches before first run, etc.)

_Copied from original issue: aspnet/dnx#2175_

**Comment by muratg** [comment]
_From @moozzyk on July 8, 2015 23:59_

Should dnu patch also allow removing patches? If we want to use it Windows Update then it might need to be able to for scenarios when an update is uninstalled.

**Comment by piotrpMSFT** [comment]
The CLI servicing mechanisms have been implemented but took a different approach.
