### ISSUE TITLE
Fails to discover unit tests

### ISSUE THREAD

**Issue by 9swampy** [dotnet/cli#5724]
Close replicant of https://github.com/dotnet/cli/issues/4417

## Steps to reproduce
Full Git Repo available at https://github.com/9swampy/Telnet/commit/9f9a73d3bbb70ce4db7e30b79365569ac4e6be62 branch feature/UnitTestNetStandard

```
{
  "version": "1.0.0-*",
  "dependencies": {
    "FluentAssertions": "4.19.0",
    "NETStandard.Library": {
      "type": "platform",
      "version": "1.6.0"
    },
    "PrimS.Telnet.NetStandard": "0.7.1-*",
    "System.Net.NameResolution": "4.0.0",
    "System.Threading": "4.3.0",
    "System.Threading.Thread": "4.3.0",
    "xunit": "2.2.0-rc2-build3523",
    "xunit.runner.console": "2.2.0-rc2-build3523"
  },
  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    },
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  },
  "testRunner": "xunit"
}
```

## Expected  behavior
When NetStandard.CiTests built expect to discover my unit tests.

## Actual behavior
Cannot find unit tests.

Attempted to add dotnet-test-xunit as https://github.com/dotnet/cli/issues/4417 suggested but it doesn't support NetStandard1.6. FWIW consequently I don't think it was a fix for https://github.com/dotnet/cli/issues/4417 either; or maybe I'm missing something?
```
    Package dotnet-test-xunit 2.2.0-preview2-build1029 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package dotnet-test-xunit 2.2.0-preview2-build1029 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
    One or more packages are incompatible with .NETStandard,Version=v1.6.
    Package dotnet-test-xunit 2.2.0-preview2-build1029 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package dotnet-test-xunit 2.2.0-preview2-build1029 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
    One or more packages are incompatible with .NETStandard,Version=v1.5.
```

Trimmed my project path.

```
------ Discover test started ------
========== Discover test finished: 0 found (0:00:00.1085188) ==========
------ Discover test started ------
Discovering tests in '[...]\Telnet\PrimS.Telnet.NetStandard.CiTests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "[...]\Telnet\PrimS.Telnet.NetStandard.CiTests\project.json" --output "[...]\Telnet\PrimS.Telnet.NetStandard.CiTests\bin\Debug\netstandard1.6" --port 47343 --parentProcessId 9920 --no-build]
Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine

```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
@9swampy We are no longer actively developing the project.json version of the tools. We have updated our tools to all work with MSBuild and our test infrastructure has actually changed considerably in the meantime and is now aligned with how VS works.

Would it be possible for you to migrate to the new tooling?

You can download the latest CLI and then run dotnet migrate on your repo_root and it should generate new csproj files for each of your project.jsons.

You can read more about this change here: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md

**Comment by 9swampy** [comment]
Thx for the response. To use later previews seems like I'd also need to get running with VS2017RC, right?

**Comment by livarcocc** [comment]
Yes. VS 2017 is the only one that supports the new csproj format that is also what the CLI uses.

**Comment by 9swampy** [comment]
Yeah, haven't got back to the tests yet but have converted to 2017 & all's looking good. Nice work :)
