### ISSUE TITLE
Visual Studio 2015 template doesn't support .csproj

### ISSUE THREAD

**Issue by pcgeek86** [dotnet/cli#5725]
## Steps to reproduce

1. Install RC4 .NET SDK / Tools
2. Restart Visual Studio 2015 Update 3
3. Create new WebAPI project

## Expected  behavior

Expected VS to create a new .csproj-based .NET Core project.

## Actual behavior

VS creates a project.json-based .NET Core project.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004825)

Product Information:
 Version:            1.0.0-rc4-004825
 Commit SHA-1 hash:  e427bc0d9a

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004825
```

**Comment by krwq** [comment]
@pcgeek86 I think this might be intentional - we support that scenario currently only in VS 2017.
@blackdwarf do we plan to have that in VS 2015?

**Comment by piotrpMSFT** [comment]
.NET Core support will be available starting with VS2017. We do not have plans to make further updates to the .NET Core tooling preview for VS 2015.
