### ISSUE TITLE
Microsoft.DotNet.Tests.GivenDotnetSdk.VersionCommandDisplaysCorrectVersion fails when doing incremental build after pulling changes

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5727]
Microsoft.DotNet.Tests.GivenDotnetSdk.VersionCommandDisplaysCorrectVersion fails when doing incremental build after pulling changes

Repro:
- full build
- git pull
- build (incremental)

**Comment by livarcocc** [comment]
That's is because I changed that test to use the .version file and somewhere along the files (with the incremental build), that file is not being updated. It would be interesting to see if it is the test copy that is not updated or the stage2 copy.

**Comment by livarcocc** [comment]
daniel made changes a while ago to improve the incremental build story of the CLI. I believe this was addressed there.
