### ISSUE TITLE
.NET Core: The folder of WebApplication(XXX) does not contain a project to restore in Ubuntu 16.04

### ISSUE THREAD

**Issue by AparnV** [dotnet/cli#5729]
## Steps to reproduce
Installed .NET core in Ubuntu16.04
Used Yeomen to generate Web Application
The following files /folders got generated
appsettings.Development.json  bower.json         Controllers  Program.cs  README.md   TestYoWebCoreApplication.csproj  web.config appsettings.json              bundleconfig.json  global.json  Properties  Startup.cs  Views      wwwroot

## Expected  behavior
Dotnet restore
dotnet run 

should restore and compile

## Actual behavior

Dotnet restore
dotnet run 

not working
Error "warn : The folder '/home/WebApplication' does not contain a project to restore.

## Environment data
`dotnet --info` output:
dotnet-dev-1.0.0-preview2.1-003177

**Comment by livarcocc** [comment]
It seems that yoman is generating a csproj based project but you are using a CLI that supports only project.json.

Please upgrade to the latest CLI and this should work for you.

Also, you can use our improved dotnet new command, which adds more templates and a lot more capabilities.

**Comment by AparnV** [comment]
I actually picked the Version from https://www.microsoft.com/net/core#linuxubuntu 

csproj based works with the preview version given in the below link... https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md

Thanks you pointed me into the right direction
