### ISSUE TITLE
"dnu pack" fails when using current directory (. or ./project.json) as an argument

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#573]
_From @ChengTian on June 26, 2015 1:28_

While `dnu pack ..\ConsoleApp21\project.json` works fine. (`..\ConsoleApp21\project.json` and `.\project.json` point to the same file)

![capture](https://cloud.githubusercontent.com/assets/1383883/8369010/dd126db6-1b67-11e5-94c2-fa7b48c72fd2.PNG)

_Copied from original issue: aspnet/dnx#2140_

**Comment by blackdwarf** [comment]
DNU (and DNX tooling) has been deprecated. Reopen if `dotnet restore` hits this issue.
