### ISSUE TITLE
Possibility to keep shared targets across major build versions

### ISSUE THREAD

**Issue by per-samuelsson** [dotnet/cli#5732]
## Steps to reproduce
Create a `.targets` file with the following:

```xml
<Project>
  <Target Name="Foo">
    <Message Text="Bar">
  </Target>
</Project>
```

## Expected  behavior
Being able to consume it from both .NET Core (>= RC3) and standard MsBuild 14.0.

## Actual behavior
MsBuild 14.0 won't accept it, because I'm missing the namespacing/tooling thing (MSB4041).

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\Per\Programs\dotnet-dev-win-x64.1.0.0-rc3-004530\sdk\1.0.0-rc3-004530
```

**Comment by per-samuelsson** [comment]
Actually noticed now that adding `xmlns="http://schemas.microsoft.com/developer/msbuild/2003` make this thing pass, under both workloads. If that has no side-effects on 15.0-tooling, I guess it's fine to close this issue as resolved.

**Comment by livarcocc** [comment]
There is no side-effect.
