### ISSUE TITLE
Cannot find Microsoft.NET.Sdk.Web

### ISSUE THREAD

**Issue by stuartbloom** [dotnet/cli#5734]
Hi there, I have just installed the latest dot net, created a new application; the two files attached.
[TestApp.zip](https://github.com/dotnet/cli/files/780653/TestApp.zip)

I intend to make us of WebHostBuilder so 
I changed the csroj to include some references including Microsoft.NET.Sdk.Web, however, i get the following error when doing a restore
`W
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\sbloom\TestApp> dotnet restore
  Restoring packages for C:\Users\sbloom\TestApp\TestApp.csproj...
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk.Web''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk.Web.ProjectSystem''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk.Publish''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk.Web''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk.Web.ProjectSystem''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk''.
  Response status code does not indicate success: 500 (Internal Server Error).
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.syncfusion.com/aspnet/FindPackagesById()?id='Microsoft.NET.Sdk.Publish''.
  Response status code does not indicate success: 500 (Internal Server Error).
C:\Program Files\dotnet\sdk\1.0.0-rc3-004530\NuGet.targets(97,5): error : Failed to retrieve information about 'Microsoft.NET.Sdk' from remote source 'http://nuget.syncfusion.com/aspnet/FindPackagesByI
d()?id='Microsoft.NET.Sdk''.\r [C:\Users\sbloom\TestApp\TestApp.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc3-004530\NuGet.targets(97,5): error :   Response status code does not indicate success: 500 (Internal Server Error). [C:\Users\sbloom\TestApp\TestApp.csproj]
PS C:\Users\sbloom\TestApp`

Any help would be most appreciated

Stuart

**Comment by stuartbloom** [comment]
As additional information, here is the result of dotnet --info.
`PS C:\Users\sbloom\TestApp> dotnet --info
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530
PS C:\Users\sbloom\TestApp>`

Thanks again

Stuart

**Comment by stuartbloom** [comment]
something else, I have added
`        <PackageReference Include="Microsoft.AspNetCore.StaticFiles">
            <Version>1.1.0</Version>
        </PackageReference>`

in order to make use of WebHostBuilder, but i am getting an error when using Microsoft.AspNetCore.Builder.

Thanks again :(

Stuart

**Comment by livarcocc** [comment]
I am not familiar with this package feed: `http://nuget.syncfusion.com`. I don't see how this is an issue with the CLI, since it looks like the feed is the thing that is failing and preventing restore to work.

Could you try using `nuget.org` instead?

cc @emgarten in case there is something that NuGet could do here.

**Comment by stuartbloom** [comment]
i would most certainly try that, but not sure where this is set.  Can you point me in the right direction?

Thanks

**Comment by livarcocc** [comment]
Check your <user_profile>/.nuget/NuGet/NuGet.Config.

**Comment by am11** [comment]
Also, if you can't / don't want to change it globally, you can put a project-specific `NuGet.Config` file in solution directory:

```sh
cd myProject

cat <<EOT >NuGet.Config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
EOT

dotnet restore && dotnet run

# Hello World!
```

**Comment by emgarten** [comment]
It looks like http://nuget.syncfusion.com is having trouble based on the 500 response. I'm not familiar with this feed either.

**Comment by stuartbloom** [comment]
Thanks gents, truns out the syncfunction site was a setting in my VS2017 for work.  Going to clode this ticket now :)
