### ISSUE TITLE
Cross plat servicing

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#574]
_From @muratg on June 24, 2015 17:18_

- [ ] Implement cross plat native code servicing
- [ ] Implement checks in package servicing (Mono case)
- [ ] Verify cross plat package servicing
- [ ] Consider Kestrel servicing

https://github.com/aspnet/dnx/issues/2175

cc: @moozzyk @victorhurdugaci @glennc @DamianEdwards 

_Copied from original issue: aspnet/dnx#2123_

**Comment by muratg** [comment]
@danroth27 FYI, we may have to move this to RC.

**Comment by muratg** [comment]
Higher pri items in Beta 8, moving to RC1.

**Comment by blackdwarf** [comment]
This is implemented in the CLI, closing.
