### ISSUE TITLE
'dnu wrap' does not add the framework assemblies list to the generated project.json files

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#575]
_From @kichalla on June 19, 2015 16:33_

The title of this issue is just my assumption of probably how it should have been. More details below:

I have a regular .Net class library whose references are like below:
Here all references except `Newtonsoft.Json` and `LibraryA` are from the GAC
![image](https://cloud.githubusercontent.com/assets/6559784/8257800/1560a938-1665-11e5-9dc5-0f4a09e95de1.png)

I wrap the following command to wrap this project:
`dnu wrap .\LibraryB\LibraryB.csproj --configuration Release -f dnx451 -i`

Now since my regular .Net project can be used for vNext, I did a `dnu pack --out c:\beta5signoff\dnuwrappackages`
But when I look at the references of the generated .nupkg in package explorer, I see the following:
![image](https://cloud.githubusercontent.com/assets/6559784/8257876/83421c84-1665-11e5-8867-d893e7d65c8a.png)

Note that it does not have `System.Runtime.Serialzation` in the 'framework assembly references` section.

I *think* the problem could be with how the wrapping is generating the `project.json` content. For example, following was the content of project.json:
```json
{
  "version": "1.0.0-*",
  "frameworks": {
    "net451": {
      "wrappedProject": "LibraryB.csproj",
      "bin": {
        "assembly": "obj/{configuration}/LibraryB.dll",
        "pdb": "obj/{configuration}/LibraryB.pdb"
      },
      "dependencies": {
        "Newtonsoft.Json": "6.0.8",
        "LibraryA": "1.0.0-*"
      }
    }
  }
}
```
Notice that this does not have the `"frameworkAssemblies"` section. Should we actually have it?

/cc: @ChengTian

_Copied from original issue: aspnet/dnx#2099_

**Comment by blackdwarf** [comment]
DNU wrap is not a CLI construct anymore so I'm closing this.
