### ISSUE TITLE
error NU1001: The dependency * could not be resolved and i can´t find a solution to fix the problem!

### ISSUE THREAD

**Issue by DrDorianxD** [dotnet/cli#5750]
Hi every Body, 
I try to build a .net Core Project with the help of the dotnet and MSBuild command line tools. 
The problem is that I get every time the ERROR NU1001 for every customer lib I use in the project.  I know that this maybe a reproduce of another Issue but every where I was looking there was no answer of the problems. 
## Steps to reproduce
To publish the project, I took the following steps:

1.  Copy all relevant files from original project to temp directory
1.1. try to build the copied project files with the help of Visual Studio 2015 
 If it can be created, I know that all the necessary files were copied. 
After it was created successfully  I deleted all copied data and make step 1. agian without 1.1. 
So that I have again only the files an no extra from Visual Studio. 
1.2. now I have the following structure:

![image](https://cloud.githubusercontent.com/assets/15774957/23058117/af19f9da-f4f3-11e6-90a6-d2d32c8004fe.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058151/e32bc0c8-f4f3-11e6-8595-c757f80f0835.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058159/f22ced36-f4f3-11e6-8979-1fb989e7d3f6.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058185/0e66406a-f4f4-11e6-8bf6-18d3d7e94728.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058207/2a9dd7ca-f4f4-11e6-92f7-2a72244caa16.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058218/37b1a504-f4f4-11e6-8bf7-1b4182a8e139.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058229/468ef8a6-f4f4-11e6-9d20-2705e60360cf.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058241/52586032-f4f4-11e6-8a11-8e2ade4ca3db.png)
------------------------------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/15774957/23058247/5c49b99c-f4f4-11e6-8efe-8755ebfcb030.png)
------------------------------------------------------------------------------------------------------------
2. now I go to the directories
 - \eWebCore\Libraries\eE.ApplicationDatabase and 
-  \eWebCore\Libraries\eE.ApplicationLogDatabase
and call over the command line "dotnet restore" and get no Error after that I call "dotnet publish -c release" and get the message "Published 1/1 projects successfully" for both. 
3. I go in the directory - BuildCore\Temp\eWebCore\Libraries\eE.Utility
and call over the command line "msbuild /t:build" and get the output message  
"Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.12"
 
4. I go in the directory - BuildCore\Temp\eWebCore\Websites\eWebCoreBase
and call over the commandline "dotnet restore" and get the output 
"Errors in ~\BuildCore\Temp\eWebCore\Websites\eWebCoreBase\project.json
    Unable to resolve 'eE.Utility' for '.NETFramework,Version=v4.6.1'.
    Unable to resolve 'eE.ApplicationDatabase (>= 1.0.0)' for '.NETFramework,Version=v4.6.1'.
    Unable to resolve 'eE.ApplicationLogDatabase (>= 1.0.0)' for '.NETFramework,Version=v4.6.1'."

If I now call "dotnet publish"  I get the output: 

"dotnet publish
Publishing eWebCoreBase for .NETFramework,Version=v4.6.1/win7-x64
No executable found matching command "dotnet-bundle"
Project eWebCoreBase (.NETFramework,Version=v4.6.1) will be compiled because expected outputs are missing
Compiling eWebCoreBase for .NETFramework,Version=v4.6.1
~\eWebCore\Websites\eWebCoreBase\project.json(73,23): error NU1001: The dependency eE.Utility could not be resolved.
~\eWebCore\Websites\eWebCoreBase\project.json(59,42): error NU1001: The dependency eE.ApplicationLogDatabase >= 1.0.0-* could not be resolved.
~\Temp\eWebCore\Websites\eWebCoreBase\project.json(60,39): error NU1001: The dependency eE.ApplicationDatabase >= 1.0.0-* could not be resolved.

Compilation failed.
    0 Warning(s)
    3 Error(s)

Time elapsed 00:00:00.0120521

Published 0/1 projects successfully"

I've really tried a lot.
 Also, I've read a lot to this problem but still found no real answer.
## Expected  behavior
At the beginning I was thinking that to call the dotnet publish -c release command woud be enouth to build the project. 

## Actual behavior

Look steps to reproduce. 
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

`msbuild -version` output:
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

14.0.25420.1

**Comment by livarcocc** [comment]
We are no longer actively supporting the project.json based tools and we have relasead a 1.0 version of the msbuild based tools, I suggest that you migrate your projects to that using the dotnet migrate command and try again.

If that still fails for you, please re-activate this issue with details about how it is failing.
