### ISSUE TITLE
dotnet migrate should migrate packages to the 1.0.4 or 1.1.1 trains

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5756]
When migrating a Dev14 xproj to csproj, running 'dotnet migrate' should update all packages to the version corresponding to the 1.0.4 or 1.1.1 trains.

**Comment by livarcocc** [comment]
@balachir Can you add a list of the packages to be updated to this issue? Or a pointer to a list of packages?

**Comment by balachir** [comment]
@livarcocc I sent this to you over email. Please ping me if you still have questions. Thanks!
