### ISSUE TITLE
Add ability to ignore particular build warnings

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#576]
_From @smudge202 on June 10, 2015 7:24_

There is currently no way to suppress specified compiler warnings akin the Build tab of old project properties.

http://puu.sh/hCNDe/6314b5a5ef.png

Issue first raised here: aspnet/home#564

_Copied from original issue: aspnet/dnx#2042_

**Comment by muratg** [comment]
This is a good idea. Let's try it in beta 6.

**Comment by muratg** [comment]
_From @Eilon on September 13, 2015 3:18_

Moving this out of backlog so we can reconsider.

**Comment by muratg** [comment]
_From @bricelam on October 9, 2015 16:56_

I prototyped something in [bricelam:nowarn](https://github.com/aspnet/dnx/compare/dev...bricelam:nowarn), but it's probably not the design you're looking for...

Format would be
```JSON
{    
  "compilationOptions": {
    "noWarn": ["CS618", "CS1591"]
  }
}
```

**Comment by muratg** [comment]
I actually like @bricelam's design and implementation.  cc: @davidfowl 

If we decide to go with it, I'd like Brice to add some tests :)

**Comment by muratg** [comment]
_From @davidfowl on October 9, 2015 17:28_

Is it just suppressions? Do we want to expose this enum:

`ReportDiagnostic.XX`

**Comment by muratg** [comment]
_From @smudge202 on October 9, 2015 19:34_

Just suppressions as @bricelam implemented looks ideal. Can always improve the model with fanciness later. Suppression is much closer to _need_.

**Comment by muratg** [comment]
_From @Eilon on October 9, 2015 21:27_

I think just suppressions like `/nowarn:X` would be awesome for v1.

Could we just take @bricelam 's code as a PR?

BTW after doing this also need to send a PR to SchemaStore to add the new option to the `project.json` schema: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json

**Comment by muratg** [comment]
_From @bricelam on October 10, 2015 0:29_

I'll add some tests and send an official PR.

**Comment by muratg** [comment]
_From @davidfowl on October 17, 2015 9:49_

@bricelam Lets do it

**Comment by anurse** [comment]
This is blocking some ASP.NET scenarios so I'm going to jump on it. Should be easy

**Comment by Daniel15** [comment]
I don't see "nowarn" in the project.json intellisense in Visual Studio (sorry, wasn't sure where to report Visual Studio tooling bugs)

**Comment by Eilon** [comment]
@Daniel15 yeah I don't see it in the schema that Intellisense uses: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json

But there is indeed a `nowarn` option, as seen here: https://github.com/dotnet/cli/blob/f515e80029440847e547e67c19fbb3a3b0907418/src/Microsoft.DotNet.ProjectModel/ProjectReader.cs#L580

So you should be able to use it just fine.

I logged a bug to track updating the schema: https://github.com/dotnet/cli/issues/3282

Thanks for the report!

**Comment by marcofranssen** [comment]
Wondering what the status of this ticket is...

I'm using dotnet cli `1.0.0-preview2-003121`

Also added to my project.json

```
"compilerOptions": {
    "nowarn": ["CS1591"]
}
```

But it still shows me those warnings for missing XML comments

**Comment by livarcocc** [comment]
compilerOptions has been deprecated a long time ago, ever since we released preview2. Please, use buildOptions.

Also, we are not making improvements to project.json anymore. All our improvements are on top of MSBuild.

**Comment by marcofranssen** [comment]
Awesome thanks... That did the trick `buildOptions` do work.
