### ISSUE TITLE
dotnet restore does not restore P2P references with ReferenceOutputAssembly=false

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#5760]
## Steps to reproduce
1. Create two class library projects, A.csproj and B.csproj
2. Add this to A.csproj:
```XML
  <ItemGroup>
    <ProjectReference Include="..\B\B.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
```
3. Run `dotnet restore A.csproj`, `dotnet msbuild A.csproj`

## Expected  behavior
Both A and B are restored, and both build successfully (because of the P2P reference).

## Actual behavior
Only A is restored. When `msbuild` is called on A.csproj, it attempts to build B.csproj first, because of the ProjectReference. This fails because B.csproj has not been restored yet. If B is manually restored, then A can be built. If `ReferenceOutputAssembly` is set to `true` (default value), then B.csproj is automatically restored when A.csproj is restored.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004777)

Product Information:
 Version:            1.0.0-rc4-004777
 Commit SHA-1 hash:  18c01886cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\dotnets\2-8-17\sdk\1.0.0-rc4-004777
```

**Comment by mellinoe** [comment]
@livarcocc Do you think I should file this somewhere else? I'm not really sure which component this falls under.

**Comment by livarcocc** [comment]
@mellinoe Can you please move this over to nuget/home?

**Comment by mellinoe** [comment]
https://github.com/NuGet/Home/issues/4700
