### ISSUE TITLE
[Question] Use NuGet.config for both VS project and cli commands?

### ISSUE THREAD

**Issue by chuckries** [dotnet/cli#5761]
Is there a way to get the same NuGet.config file to be used from both 'dotnet restore' on the command line and IDE solution build?

```
dotnet --version
1.0.0-rc4-004788
```

I have a .NET Core test project. I have a NuGet.config file in the project directory next to the .csproj. Running dotnet restore works correctly. If, however, I build from VS 2017 RC, the package is not restore because the NuGet.config file is not used. 

Is there a way to make both methods pick up the same NuGet.config by default without using a machine specific setup?

**Comment by chuckries** [comment]
Anybody?

**Comment by piotrpMSFT** [comment]
@chuckries I believe this should work, but the folks at `nuget/home` will know for sure. I'll move the issue for you.

**Comment by piotrpMSFT** [comment]
This issue was moved to NuGet/Home#4669

**Comment by chuckries** [comment]
Thanks!
