### ISSUE TITLE
Not intuitive error message when missing argument (i.e. dotnet sln)

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#5762]
## Steps to reproduce
- dotnet sln

## Expected  behavior
- show help, list of commands, some actionable error

## Actual behavior
Required command was not provided.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-alpha-alpha-004933)

Product Information:
 Version:            2.0.0-alpha-alpha-004933
 Commit SHA-1 hash:  30d281bc4c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\cli\artifacts\win10-x64\stage2\sdk\2.0.0-alpha-004936\
```

**Comment by mikkelbu** [comment]
I think that this issue is the same as #5384 which I've tried to solve in #6506

**Comment by krwq** [comment]
@livarcocc @jonsequitur is this still an issue with new parser?

**Comment by jonsequitur** [comment]
@krwq This behavior is unchanged from V1 to V2 so not related to the new parser. We've been applying the `parser` label to issues that we can resolve using the new parser and this one is a candidate.

**Comment by mikkelbu** [comment]
@krwq #6506 got merged into master, so now `dotnet sln` should give you "Required command was not provided" followed by the help file for the `sln` command.

**Comment by livarcocc** [comment]
Closing since we display help now in this situation.
