### ISSUE TITLE
Dotnet.exe does not exisit under "C:\Program Files\dotnet" after installation

### ISSUE THREAD

**Issue by ferrancg** [dotnet/cli#5764]
## Steps to reproduce
1. I was using VS 2015, and with dotnet sdk version : _1.0.0-preview2-003121_
2. I downloaded a newer version to try out _SDK 1.0 RC3_ 
3. New version sdk does not work with current project, switched back to _1.0.0-preview2-003121_  by changing the endpoint in global.json
4. Things are messed up in dotnet cli with error “A fatal error occured, the required library hostfxr.dll could not be found at C:\Program Files\dotnet”
5. Uninstalled SDK _1.0 RC3_ , error still showing up, when I use dotnet command .
6. Repair/uninstall/re-install .net core sdk and VS2015 tooling, error still persist
7. Deleted folder _C:\Program Files\dotnet_, and reinstalled dotnet sdk version : _1.0.0-preview2-003121_,
new error coming up saying can't find dotnet as the name of a cmdlet. Turned out the dotnet.exe is missing under _C:\Program Files\dotnet_ after the re-install.
8. Found out there is another sdk under C:\User\{user}\AppData\Local\Microsoft\dotnet which is working, but my PATH is also referring to the one under C:\Program Files\dotnet

Step 1-4 is a known [issue ](https://github.com/dotnet/core-setup/issues/572)

## Expected  behavior
After install the https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.0-preview2-download.md, I expect there is Dotnet.exe under the _C:\Program Files\dotnet_

## Actual behavior
Dotnet.exe does not exist under _C:\Program Files\dotnet_

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
@ferrancg is it only dotnet.exe that is missing? are the other files present, like sdk and shared folders?

**Comment by ferrancg** [comment]
right

**Comment by byyyt** [comment]
Same issue for me. Broken installations. Had a bunch of previous versions, tried uninstalling, some stuff was left, so just deleted whole dotnet folder. Then after installing VS 17 with dotnet tooling, I went to install dotnet RC4. 
Now it either installs only partially: sdk and shared are installed, swidtag (or whatever its named) is missing, dotnet.exe is from 2016, and complains about missing hostfxr.dll and does not run.
Or it installs only sdk/shared and dotnet.exe is missing completely.

So frustrating...

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#1987
