### ISSUE TITLE
Updating a newly created CLI project in VS2015 Update 3 breaks after running nuget update

### ISSUE THREAD

**Issue by andybrodie** [dotnet/cli#5767]
## Steps to reproduce

1. Create a new "Console Application (.NET Core)"
1. Go to "Manage Nuget packages for application"
1. Select Updates (1 shown)
1. Select "Microsoft.NETCore.App" v1.1.0
1. Click "Update", which tells you you're going from 1.0.1 to 1.1.0
1. Accept license agreement
1. Attempt to build project

At this point the build fails.  No changes to source code have been made, this is an empty CLI project.

## Expected  behavior

Project continues to compile, any config changes required should be made automatically.

## Actual behavior

Four errors on attempting to rebuild:

Severity|Code|Description|Project|File|Line
--|--|--|--|--|--
Error| |1. The project has not been restored or restore failed - run `dotnet restore`|ConsoleApp1|C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets|262
Error| |2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.|ConsoleApp1|C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets|262
Error| |3. You may be trying to publish a library, which is not supported. Use `dotnet pack` to distribute libraries.|ConsoleApp1|C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets|262
Error| |Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:|ConsoleApp1|C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets|262

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14986
 OS Platform: Windows
 RID:         win10-x64
```
## Output on upgrade:

```
Retrieving package 'Microsoft.NETCore.App 1.1.0' from 'nuget.org'.
Uninstalling NuGet package Microsoft.NETCore.App.1.0.1.
Successfully uninstalled 'Microsoft.NETCore.App.1.0.1' from ConsoleApp1
Installing NuGet package Microsoft.NETCore.App.1.1.0.
Successfully installed 'Microsoft.NETCore.App 1.1.0' to ConsoleApp1
Executing nuget actions took 54.26 ms
========== Finished ==========
Time Elapsed: 00:00:28.8550142
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\Users\Andy\Projects\ConsoleApp1\.vs\restore.dg"
log  : Restoring packages for C:\Users\Andy\Projects\ConsoleApp1\src\ConsoleApp1\project.json...
log  : Writing lock file to disk. Path: C:\Users\Andy\Projects\ConsoleApp1\src\ConsoleApp1\project.lock.json
log  : C:\Users\Andy\Projects\ConsoleApp1\src\ConsoleApp1\ConsoleApp1.xproj
log  : Restore completed in 808ms.
```

**Comment by livarcocc** [comment]
Can you move your projects to the new csproj based tooling that was release as 1.0 a few weeks ago and try this again?

We are no longer actively support the project.json based tooling and the project.json tooling for VS2015 was a preview only.
