### ISSUE TITLE
runtime returns incorrect framework short name when netcore451 is specified in project.json

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#577]
_From @abpiskunov on June 8, 2015 17:28_

See this issue for full details and repro: https://github.com/aspnet/Tooling-Internal/issues/344 

_Copied from original issue: aspnet/dnx#2032_

**Comment by muratg** [comment]
_From @davidfowl on September 20, 2015 1:1_

/cc @anurse

**Comment by muratg** [comment]
_From @anurse on September 21, 2015 2:40_

`win81` is the correct normalized short-form name for `.NETCore, Version=v4.5.1`... The tooling should be using long-form names everywhere since they are unambiguous.

**Comment by muratg** [comment]
_From @abpiskunov on September 21, 2015 14:36_

How do we get this correct-long-form name for each framework moniker ? We take monikers that runtime sends us and don't have our own name resolution logic.

**Comment by muratg** [comment]
_From @abpiskunov on September 21, 2015 14:37_

In any case , runtime should be consistent with the info it sends us.

**Comment by muratg** [comment]
_From @davidfowl on September 21, 2015 15:21_

We should fix this

**Comment by piotrpMSFT** [comment]
@abpiskunov do you still see this issue in ProjectModelServer?

**Comment by abpiskunov** [comment]
no, it does not repro in dotnet cli
