### ISSUE TITLE
vscode tasks.json not checked during "dotnet migrate"

### ISSUE THREAD

**Issue by cwoodruff** [dotnet/cli#5771]
## Steps to reproduce
Have project.json referenced in the .vscode folder's tasks.json file:

`{
    "version": "0.1.0",
    "command": "dotnet",
    "isShellCommand": true,
    "args": [],
    "tasks": [{
            "taskName": "build",
            "args": [
                "${workspaceRoot}\\project.son"
            ],
            "isBuildCommand": true,
            "problemMatcher": "$msCompile"
        },
        {
            "taskName": "bundle"
        },
        {
            "taskName": "clean",
            "args": ["bundle", "clean"],
            "suppressTaskName": true
        },
        {
            "taskName": "watch",
            "args": ["bundle", "watch"],
            "suppressTaskName": true,
            "isWatching": true
        }
    ]
}`

Aftre a "dotnet migrate" the project.json reference still present and errors will occur upon build task execution.

## Expected  behavior
I would expect the project.json would be found and dealt with effectively. I changed project.json to the name of the new csproj file "dotnet migrated" created.

The MigrateCommand should detect is the .vscode folder exists and process the tasks.json accordingly.

## Actual behavior
The tasks.json file is not changed. I suspect that the MigrateCommand does not check to see if .vscode folder exists.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15031
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@cwoodruff you are right, we are not handling the `tasks.json` file at all during migration. I don't think it should, really, seeing as how the job of the migration command is to migrate the `project.json` file to a semantically equivalent `csproj` file, which, it seems from your issue, it actually did.

**Comment by livarcocc** [comment]
Correct. This is a non-goal to dotnet migrate. We just can't handle all the things that are out there effectively.
