### ISSUE TITLE
Need Easy Installation of 1.1, Shared Framework only, on Linux

### ISSUE THREAD

**Issue by JohnRusk** [dotnet/cli#5773]
## Steps to reproduce

Go to https://www.microsoft.com/net/core 

## Expected  behavior

Can easily find instructions on how to install version 1.1 of the Shared Runtime only, on Linux.  Ideally this would be by an RPM, and ideally it would correctly install prerequistes/dependencies.

Secondly, the Linux download page should clearly note the deprecation of any old methods. (E.g. it appears that dotnet-install.sh is not supported for 1.1, shared runtime only, but there's nothing here https://www.microsoft.com/net/download/linux that says so. There ought to be something that says that, so that people accustomed to using that script don't waste time trying to use it with 1.1.)

## Actual behavior

The packages listed here https://www.microsoft.com/net/download/linux are all for the full SDK.  A hour or so of web searching unearthed a suggested package name for the Shared Runtime... but it didn't work.

Tried using the dotnet-install.sh approach, but that is (a) very hard to find for 1.1 (see issue #4954 ) and (b) when you do find it, it turns out that that particular version of dotnet-install.sh does not support the --shared-framework argument.

Only way to install appears to be to download and unzip the tar.gz.  Which is OK for me, but not great for the users who will be testing the upcoming release of my app.  Especially because they'll also have to install dependencies manually.

**Comment by RheaAyase** [comment]
You can actually target and publish applications from any _(supported)_ platform to any _(supported)_ platform without the need of any cli/framework/runtime, on the target platform. In that sense I don't see the exceptional need for this, unless I'm missing something?

**Comment by JohnRusk** [comment]
You mean by doing a self-contained deployment?  In that case, I think the documentation needs to be updated. Specifically this page: https://www.microsoft.com/net/download/linux . It should say something like, "For .NET Core 1.1, all packages listed here are for the SDK. There is no package supplied for Shared Runtime Only.  Instead, if you are building a Framework Dependent Deployment (FDD), deploy the framework using one of the tar.gz files listed on this page. On the other hand, if you are building a self-contained deployment (SCD), your deployment already contains everything you need.  Note also that for 1.1 the dotnet-install.sh script  does not support Shared Runtime-only installs, you need to use the tar.gz files from this page."

Such an addition to the documentation would have saved me about 3 hours of searching for answers.  We should, if at all possible, avoid inflicting such frustration on other .NET Core users.... :-)

Is this issues list the right place to request documentation improvements?

(P.S. In addition to the above, there is actually one tangible disadvantage to not having Shared Runtime RPMs. It is the installation of dependencies.  Without a Shared Runtime RPM, either end users have to install the dependencies themselves, or every app developer of a Framework Dependent app needs to create their own RMP to sort out dependencies.   If the latter, then we have a second documentation issue, since the dependencies issues should them be listed as a disadvantage of FDD deployment here: https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/deploying/ .  Again, rationale for the doco change is to avoid frustrating devs who use .NET Core.)

**Comment by blackdwarf** [comment]
@JohnRusk we do have the installation of the shared framework for 1.1 as well. You should use the installation script from `rel/1.0.0` and pass in the `release/1.1.0` for the `--channel` option (the relevant doc in this repo is being updated in #5766). The whole command should look like this:

```bash
./dotnet-install.sh --channel release/1.1.0 --shared-runtime -i <location_to_install>
```

We only, as of now, produce DEBs for Ubuntu and not RPMs or DEBs for Debian. That means that for any other Linux distro, at this point, you will have to use either the install script or to curl down a tarball as part of your installation script. The Ubuntu feeds have 1.1.0 shared runtime and the package name is `dotnet-sharedframework-microsoft.netcore.app-1.1.0`.

**Comment by JohnRusk** [comment]
Hi @blackdwarf. That's awesome, thanks.  Two quick questions:

1. Any chance of getting that info reflected in, or linked from, this page:  https://www.microsoft.com/net/download/linux    That could save ppl from a lot of searching for channel and package names.

2. Does the Ubuntu package force the install of dependencies/prerequisites?

**Comment by blackdwarf** [comment]
@JohnRusk answers:

1. Sure, will file the issue on the appropriate repo (not open, unfortunately). 
2. Yes.

**Comment by livarcocc** [comment]
@blackdwarf Is there any action for the CLI on this issue? If not, let's close it.

**Comment by blackdwarf** [comment]
@livarcocc nope. Closing.

**Comment by JohnRusk** [comment]
Hi @blackdwarf. I just tried the script-based install that you described.  Got an error that said: `release/1.1.0 is an invalid channel name. Use one of the following: future, preview, production`

**Comment by JohnRusk** [comment]
For anyone else reading this, you may also strike an in-installable dependency on libicu52. See https://github.com/dotnet/cli/issues/2962 for the workaround

**Comment by JohnRusk** [comment]
@livarcocc Can you help with this still not working?  As in my comment of 7 days ago, the script-based install didn't work when I followed @blackdwarf 's instructions.  Do you know a solution?

**Comment by blackdwarf** [comment]
@JohnRusk here is the actual command you can use. Just tested that it works. 

`./dotnet-install.ps1 -Channel 'release/1.1.0' -SharedRuntime -Version '1.1.1'`

**Comment by JohnRusk** [comment]
@blackdwarf Thanks. Does that install version 1.1.0 or 1.1.1?

**Comment by blackdwarf** [comment]
`1.1.1`

**Comment by JohnRusk** [comment]
We haven't tested on that. Have only tested on 1.1.0.  Is there any command to install that - on _Linux_. When I tried --channel release/1.1.0 with the Linux script I got an error about bad channel name. (As above).

**Comment by livarcocc** [comment]
I just tried this:

`./dotnet-install.ps1 -Channel 'release/1.1.0' -SharedRuntime -Version '1.1.0'`

and it ran successfully.

Where are you getting your dotnet-install.ps1 script? And how old is it?

**Comment by JohnRusk** [comment]
Ah, yes, I had an old version of the script.  This one is better, and (almost) works:

`https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh `

I say almost because _on Ubuntu 16.04_ it does give an error about being unable to install the 'libunwind' dependency. I found the workaround is to manually install libunwind8, using 

`sudo apt-get install libunwind8`

Would you be able to arrange for that issue to be fixed in the Linux version of the script?  I have only tested on Ubuntu 16.04. Not sure whether the same package name issue exists elsewhere.

Thanks to you both for your help :-)

**Comment by JohnRusk** [comment]
PS. In addition to the issue I had with libunwind, I also found that the .dotnet directory was on in my path after running the script, even though the script said it had added it to my path. Not sure why...

**Comment by blackdwarf** [comment]
@JohnRusk as of yesterday, I would advise you to use the following two locations for these scripts:

* https://dot.net/v1/dotnet-install.sh
* https://dot.net/v1/dotnet-install.ps1

These will be stable moving forward so you will have most luck with them.

**Comment by JohnRusk** [comment]
Nice! Thanks.
