### ISSUE TITLE
PackageReference that depends on DotNetCliToolReference 

### ISSUE THREAD

**Issue by ctaggart** [dotnet/cli#5774]
Hi, I'm working on tools to help automate the `/sourcelink` option for the compilers. I've packaged the tools as dotnet cli tools with simple MSBuild tools packages that are wrappers. Is it possible to have the MSBuild tools package reference the dotnet cli tool.

Currently, I must tell people to include both:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <DebugType>Portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.GitHub" Version="2.0.0-*" />
    <DotNetCliToolReference Include="dotnet-sourcelink-git" Version="2.0.0-*" />
  </ItemGroup>
</Project>
```

But I really just want to tell people to include one:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <DebugType>Portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.GitHub" Version="2.0.0-*" />
  </ItemGroup>
</Project>
```

Is this possible or will this be possible?

## Environment data
`dotnet --info` output:

```
PS C:\Users\camer\cs\SourceLink> dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by davidfowl** [comment]
No it's not. You're better off writing a task.

**Comment by ctaggart** [comment]
@davidfowl To clarify, `SourceLink.Create.GitHub` **is** a MSBuild task that simply make calls to the `dotnet sourcelink-git` tool.  Users can probably live with adding two lines of dependencies, I hope.

I bet it would be possible if like `<PackageType>DotnetCliTool</PackageType>` you made a `<PackageType>DotnetMSBuildTool</PackageType>` and added some special handling.

**Comment by davidfowl** [comment]
Sure but that's a feature request (not saying it's not a good one). In the short term if you want to have it be a single reference then you need to just have an msbuild task. Or you need to package the tool bits inside of the same package.

**Comment by ctaggart** [comment]
Cool, consider this a feature request. :-) In the short term, I'll find out if users can live with adding two lines.

**Comment by davidfowl** [comment]
Needs to be moved to nuget 😄
