### ISSUE TITLE
Microsoft.AspNetCore.Server.IISIntegration.Tools is moved, resulting in: No executable found matching command "dotnet-publish-iis"

### ISSUE THREAD

**Issue by TinkerWorX** [dotnet/cli#5776]
## Steps to reproduce
Create an empty web app using the Visual Studio template.
Open up the NuGet package manager, include pre releases.
Update Microsoft.AspNetCore.Server.IISIntegration.Tools.
Try and publish.

## Expected  behavior
This should publish the web app.

## Actual behavior
The publish fails with the error: No executable found matching command "dotnet-publish-iis"

## Environment data
N/A

## How to fix?
Open up project.json.
Locate `Microsoft.AspNetCore.Server.IISIntegration.Tools` node inside `dependencies` node.
Move the node from the `dependencies` node to the `tools` node.

## [Example files](https://gist.github.com/TinkerWorX/cced7cabd1afab5e9f3a785355471dfe)

**Comment by GuardRex** [comment]
@TinkerWorX It's a good catch imo; but with the move away from `project.json` (and the `publish-iis` tooling), brace yourself for them hitting you with a "will not fix" on this one. Soon we'll be saying bye-bye to `project.json` forever. They're spending most of their time getting everything running with MSBuild/`csproj`.

**Comment by TinkerWorX** [comment]
Ah. I'm not really following the development, I simply found the bug and figured I'd report it. Moving to msbuild sounds great, I'm really missing being able to add shared projects. Sharing code between projects is a pain at the moment.

**Comment by livarcocc** [comment]
@TinkerWorX yep, what @GuardRex said. We don't even have that tool in msbuild anymore. it is part of the web sdk now.
