### ISSUE TITLE
dotnet pack does not use Directory.Build.targets when multi-targeting 

### ISSUE THREAD

**Issue by enyim** [dotnet/cli#5778]
## Steps to reproduce

1. Create a new project, set `<FrameworkVersions>` to any valid value(s). (Even a single framework will trigger the issue.)
2. Create a `Directory.Build.targets` file in the solution root
3. Define `PackageVersion`, `Version`, or any Nuget specific properties in it (haven't tested with full msbuild functionality, e.g. custom targets)
4. `dotnet pack` the project

## Expected  behavior

I'm expecting to create a nuget package with the version number specified in `Directory.Build.targets`.

## Actual behavior

Output package has the version 1.0.0.

Works fine if the project has only a single target, i.e. `FrameworkVersion` (and not Version**s**)

I have uploaded a sample solution with a repro project to https://www.dropbox.com/s/10mgldydh85d6z7/PackTest.zip

The `PackSingle` project will have all its properties overridden (except AssemblyName, will file a separate bug), while `PackMulti` project will use all values from the csproj.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by jeffkl** [comment]
Possible duplicate of https://github.com/Microsoft/msbuild/issues/1721

**Comment by enyim** [comment]
yep, dupe
