### ISSUE TITLE
dotnet msbuild can't seem to complete Exec commands

### ISSUE THREAD

**Issue by tuespetre** [dotnet/cli#5779]
### ⚠️  Update: Workaround for anyone affected by this issue

The simplest workaround (that works) that I've found so far is to create a separate PowerShell script to run, and use this:

```
<Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
  <Exec Command="powershell.exe -NonInteractive -File prepublish.ps1" />
</Target>
```

Not ideal, but should work for the short-term until this regression is addressed.

--------

## Steps to reproduce

- Create a new console app with `dotnet new console`
- Change the .csproj like so:

```diff
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  
+  <Target Name="TestTarget">
+    <Exec Command="echo hello" />
+    <Exec Command="echo goodbye" />
+  </Target>

</Project>
```
- Run `dotnet msbuild /v:diag /t:TestTarget`

## Expected  behavior

Complete MSBuild output

## Actual behavior

MSBuild dies:

```
                   Using "Exec" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "Exec" (TaskId:2)
                     Task Parameter:Command=echo hello (TaskId:2)
                     echo hello (TaskId:2)
                     hello (TaskId:2)
                   Done executing task "Exec". (TaskId:2)
                   Task "Exec" (TaskId:3)
                     Task Parameter:Command=echo goodbye (TaskId:3)
                     echo goodbye (TaskId:3)
E:\tmp\dotnet-msbuild-exec>
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by piotrpMSFT** [comment]
We use <exec> quite a bit in the CLI repo with no functional issues. I wonder if output is not getting passed through as you'd expect. You can try running something that generates files [e.g. `dotnet new in another directory] to test that theory. @rainersigwald, @jeffkl, @cdmihai should be able to help with understanding this issue better.

**Comment by tuespetre** [comment]
FWIW initially began to notice this issue due to trying to run npm/bower/gulp/etc : https://github.com/aspnet/websdk/issues/135

**Comment by rainersigwald** [comment]
I have a slightly newer CLI handy (1.0.0-rc4-004842), but I don't reproduce the issue with those steps. I see the expected behavior (an error message about `Unknown option: -v` and the CLI help text, and the build succeeds with `warning MSB3073: The command "dotnet -v" exited with code 1.`).

I don't know what would cause MSBuild to silently fail on your machine. A couple of troubleshooting steps:

* What happens when you run `dotnet -v` directly on the command line outside MSBuild?
* When it (silently) fails back to the command prompt, what is `%ERRORLEVEL%`?
* Can you use [ProcMon](https://technet.microsoft.com/en-US/sysinternals/processmonitor.aspx) to get a trace of what happens during the build? Specifically I'm most curious about
  * Does MSBuild attempt to CreateProcess on `dotnet.exe`?
  * If it does, what is its error code?

**Comment by livarcocc** [comment]
Since it has been a while since we saw activity on this issue, and we couldn't repro this ourselves. I am closing the issue.

@tuespetre Please, feel free to re-activate when you have more information for us. Thanks.

**Comment by tuespetre** [comment]
@livarcocc hah, I was just typing up something as you closed it

**Comment by tuespetre** [comment]
@rainersigwald tried to 🔧 around with ProcMon and in my 'real world' scenario (using `npm`) I see `npm` running to completion (a Process Exit operation with an exit code of 0.) I'm not sure what to make of any of the output after that. Eventually `dotnet.exe` exits with a code of `-1073741790`.

@livarcocc I cannot reopen the issue, I can only comment

**Comment by tuespetre** [comment]
Still seeing the issue after installing `1.0.0-rc4-004911`.

**Comment by tuespetre** [comment]
@livarcocc @rainersigwald it seems to be specifically when running more than one `Exec` within the target, as well (as I put in my original comments.) But I've tried breaking them up with `Message` in between and still no luck. In this example, `npm install` completes and `In between Exec` prints, but the `echo hello` never succeeds and MSBuild dies:

```
  <Target Name="TestTarget">
    <Message Text="Before Exec" Importance="high" />
    <Exec Command="npm install" />
    <Message Text="In between Exec" Importance="high" />
    <Exec Command="echo hello" />
    <Message Text="After Exec" Importance="high" />
  </Target>
```

**Comment by tuespetre** [comment]
I put the following target in a 'old-style' .csproj:

```
  <Target Name="TestTarget">
    <Exec Command="echo hello" />
    <Exec Command="echo goodbye" />
  </Target> 
```

Ran MSBuild from the command line (`msbuild /t:TestTarget`) and got the expected result. Put the same target into any 'new-style' .csproj and try to run it via `dotnet msbuild /t:TestTarget` and it only ever prints 'hello'.

**Comment by tuespetre** [comment]
@livarcocc @piotrpMSFT  Is this going to stay a 'discussion' or will it be promoted to a bug? My coworker can reproduce this too, and I still have this problem with the RTM release (and I made sure to remove every trace of any other version of `dotnet` including even the old `dnx` and `dnvm` stuff.) I've updated the main post to reflect the version and the simpler example target from [my comment.](https://github.com/dotnet/cli/issues/5779#issuecomment-282827963)

**Comment by tuespetre** [comment]
Tried on Windows Server 2008 R2 and Windows Server 2012 R2 and they do not have this problem.


```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by tuespetre** [comment]
Alright, so I tried it out on my crappy home win10 laptop and there was no problem. After seeing how the Exec command works (writing batch files to the temp folder for execution) I suspect our corporate AV has something to do with my coworker and I both experiencing the issue. I am going to close this as there is clearly something specific to our workstations here.

**Comment by allan-walpy** [comment]
some verbose output
```
 AfterBuildScript:
         ./script/do event/build/after
         /bin/sh: 2: /tmp/tmpc1716baac62f4fd6b54e038d4c13d219.exec.cmd: ./script/do: not found
     1>/home/walpy/git/vulmy/src/server/server.csproj(45,9): error MSB3073: The command "./script/do event/build/after" exited with code 127.
     1>Done Building Project "/home/walpy/git/vulmy/src/server/server.csproj" (Build target(s)) -- FAILED.
```

**Comment by LanPodder** [comment]
```
  <Target Name="TestTarget">
    <Exec Command="echo hello" />
    <Exec Command="echo goodbye" />
  </Target>
```
works, but doing 
```
<Target Name="TestTarget" BeforeTargets="Build">
    <Exec Command="echo hello" />
    <Exec Command="echo goodbye" />
  </Target>
```
returns an error:

> The command "echo hello" exited with code 1.

**Comment by rainersigwald** [comment]
@LanPodder Can you open a new issue with some more details?
