### ISSUE TITLE
dotnet new xunit displays conflict warnings 

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#5780]
## Steps to reproduce
dotnet new xunit 
dotnet restore 
dotnet build
add a new test 
dotnet test

## Expected  behavior
build and test should not see any warnings

## Actual behavior
Build started, please wait...
C:\Program Files\dotnet\sdk\1.0.0-rc4-004842\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Projects\Test1\Test1.csproj]
Build completed.

## Environment data
1.0.0-rc4-004842

Note: I don't see the warning when created from Visual studio

**Comment by bradwilson** [comment]
Try upgrading the package versions of `xunit` and `xunit.runner.visualstudio` to `2.2.0`, and this warning should go away. This change is already working its way into the final RTM templates for both `dotnet new` and Visual Studio 2017.

**Comment by piotrpMSFT** [comment]
yep. Thanks @bradwilson !

**Comment by livarcocc** [comment]
The new templates in the CLI have been updated.
