### ISSUE TITLE
dotnet restore ignores --verbosity flag

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5783]
## Steps to reproduce
dotnet restore -v quiet
dotnet restore -v detailed
dotnet restore -v diagnostic

## Expected  behavior
Console output should show different levels of verbosity.

## Actual behavior
Always displays minimal output.

## Environment data
Using 1.0.0-rc4-004842

**Comment by piotrpMSFT** [comment]
Moving to nuget/home.

**Comment by piotrpMSFT** [comment]
This issue was moved to NuGet/Home#4670
