### ISSUE TITLE
New CI OS versions affecting CLI Servicing branches

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#5789]
The newly added distros [F24, U16.10, O13.2] are showing up for CLI's servicing branches and causing apparent build breaks. While these can be ignored, we shouldn't build tribal knowledge regarding "the branches on which some red is ok". Let's fix up Jenkins to not point the new distros at old branches.

/cc @livarcocc @naamunds @jonsequitur @krwq @jgoshi 

/fyi @MattGertz 

Until this is fixed, we will need to be careful to inspect failures on PRs against rel/1.0.0 and earlier.

**Comment by eerhardt** [comment]
>  are showing up for CLI's servicing branches and causing apparent build breaks

Can you send some links?  I'm unaware of these build breaks.

**Comment by piotrpMSFT** [comment]
Sure. I'll leave this PR open until tomorrow so you can take a look:
https://github.com/dotnet/cli/pull/5757

Note that we tried to run PR builds for the new distros, though they're clearly not supported by this branch. They should light up only for rel/1.0.1.

**Comment by livarcocc** [comment]
We have handled this by now.
