### ISSUE TITLE
Missing support for plugin projects with csproj projects

### ISSUE THREAD

**Issue by atanasa** [dotnet/cli#5792]
What I mean by a "plugin project" is one that outputs some assembly that is loaded by a plugin host (e.g. PowerShell, dotnet). Using [FDD](https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/deploying/) it was possible to create a project that would specify a package dependency of type "platform" that specified the libraries supplied by the host. Then `dotnet publish` would output only the 3-rd party dependencies that are not provided by the host.
With the new tooling, this no longer seems to be possible for host other than `dotnet`. The migration process (`dotnet migrate`) strips the "platform" information off the dependency in the new csproj.

Is there still a way to specify that a dependency is of type "platform" or some equivalent?

**Comment by livarcocc** [comment]
you don't want these assemblies in the publish output of your project? Is that correct? Are they package references?

If so, you can set the metadata <PrivateAssets>All</PrivateAssets> in your package reference and the package won't be output during publish.

Re-activate if this is not what you are looking for.

**Comment by atanasa** [comment]
What do you mean by "metadata All"? It is a package reference. Setting `<PrivateAssets>All</PrivateAssets>` would probably do it for the package assets, but not recursively for all that package dependencies as is with the case of a platform dependency. And listing all those package references (probably 100+) in each project is not ideal.

After some digging in the source code of the SDK I have managed to work this around by setting the property `MicrosoftNETPlatformLibrary` to the name of the targeting package (the platform package) and setting the property `CopyLocalLockFileAssemblies` to false (to make it work for .Net Framework).
