### ISSUE TITLE
RC4 installer for OSX says its installing .NET Core 1.0.3

### ISSUE THREAD

**Issue by julielerman** [dotnet/cli#5795]
## Steps to reproduce

download latest  Mac OS X version of the dotnet core SDK installer from dotnet cli readme page. 
run the installer
## Expected  behavior
The UI of the  RC4 SDK.

It does install the RC4 SDK though. dotnet --version confirms with 
 julieVM$ dotnet --version
1.0.0-rc4-004849

## Actual behavior
The UI of the installer says its installing .NET Core 1.0.3. It's confusing.
![image](https://cloud.githubusercontent.com/assets/5007120/23224917/17c8ac20-f8fe-11e6-9b6e-7ac68ebe1725.png)

**Comment by blackdwarf** [comment]
@piotrpMSFT this should be fixed with the latest branding change, correct?

**Comment by blackdwarf** [comment]
This is now fixed in the latest builds and the branding has changed. Closing. @julielerman please reopen of you see that the new PKG installer has the same problem.
