### ISSUE TITLE
RC4 dotnet new mvc Individual auth template places EFCore Tools in wrong csproj section

### ISSUE THREAD

**Issue by julielerman** [dotnet/cli#5798]
## Steps to reproduce
run the following command at the command line:

`dotnet new mvc --auth Individual  --framework netcoreapp1.1
`

## Expected  behavior
EF Core and tools will be installed because of the authorication.
EF Core tools in csproj should be included as a DotNetCiToolReference as follows

    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />

## Actual behavior
 The tools package is included as a package reference in the ItemGroup that contains the other package references and it references the powershell version of the package, not the CLI version. (CLI needs ".DotNet" at the end as shown above)

`<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.0.0-msbuild3-final" PrivateAssets="All" />`

This results in an error when trying to run dotnet ef at the command line.

 No executable found matching command "dotnet-ef"

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004849)

Product Information:
 Version:            1.0.0-rc4-004849
 Commit SHA-1 hash:  7dcefb5076

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004849

**Comment by spboyer** [comment]
@julielerman - The templates for those are here, may want to create the Issue there and/or PR the fix.

[Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/Company.WebApplication1.csproj](https://github.com/dotnet/templating/blob/23e94537c75c4b1b4c9170a31c3b6bdcfb3626e9/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/Company.WebApplication1.csproj)

and 

[Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Company.WebApplication1.csproj](https://github.com/dotnet/templating/blob/75dbdb85134eea6255154094acc2d37a8412ee68/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Company.WebApplication1.csproj)

**Comment by julielerman** [comment]
thanks! Will do just that

**Comment by julielerman** [comment]
@spboyer the newer templates reference the correct name (Tools.DotNet) and are listed as CLI References , so it's fixed.

**Comment by livarcocc** [comment]
We just took in new templates earlier today. Closing this.
