### ISSUE TITLE
Allow custom compilers to inject sources into symbol packages

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#580]
_From @Alxandr on May 30, 2015 17:58_

With how my new F# compiler for DNX work, I end up with empty symbol packages. Now, symbolsource doesn't support DNX targets yet so it's not that much of a problem ^^, but I would still like for a way for my compiler to DNU what sources/additional sources to include in the symbols package.

_Copied from original issue: aspnet/dnx#1995_

**Comment by piotrpMSFT** [comment]
@enricosada is this still an issue?

**Comment by enricosada** [comment]
no @piotrpMSFT this issue can be closed, portablepdb or pdb on windows are supported. 
these need to be configured in project.json (like c#)

**Comment by Alxandr** [comment]
I'm not saying this isn't resolved, but @enricosada when I mad this issue, it had nothing to do with portable PDBs.

**Comment by enricosada** [comment]
sry @Alxandr i confused empty symbol package with empty debug symbols assembly (thinking about the empty pdb generated atm by dotnet build with f#)

so about symbol package:

using netcore sdk preview1:

```
dotnet new --lang f#
dotnet restore
dotnet pack
```

output of `dotnet pack`:

```
Producing nuget package "testsy.1.0.0" for testsy
testsy -> E:\temp\testsy\bin\Debug\testsy.1.0.0.nupkg
Producing nuget package "testsy.1.0.0.symbols" for testsy
testsy -> E:\temp\testsy\bin\Debug\testsy.1.0.0.symbols.nupkg
```

and `testsy.1.0.0.symbols.nupkg` contains `Program.fs` (the source file).

```
|   testsy.nuspec
|   [Content_Types].xml
|
+---lib
|   \---netstandard1.5
|           testsy.dll
|           testsy.pdb
|           testsy.runtimeconfig.json
|
+---src
|       Program.fs
|
\---_rels
        .rels
```

That was the issue before @Alxandr ?

**Comment by Alxandr** [comment]
Yes. I believe this was fixed by convention when the F# compiler started using the same fields for what files to compile as the C# compiler did. Still think it should be allowed for the compiler to inject into what goes into the symbols package, but yeah, this works.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
