### ISSUE TITLE
Allow custom compilers to inject dependencies

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#581]
_From @Alxandr on May 30, 2015 17:56_

Any project that is build in F# will as a general rule depend on `FSharp.Core`. `YoloDev.Dnx.FSharp` itself also depends on `FSharp.Core`, but since it's normally added as a build time only dependency, it's dependency on `FSharp.Core` doesn't get transferred to the project produced by it. I think there should either be an API that allows me to inject dependencies into the project being built by the custom compiler, or at least some way to note that `FSharp.Core` should be transfered as a dependency to peer projects even if `YoloDev.Dnx.FSharp` is listed as built-time only.

The problem is that as it stands now, if people forget to add the dependency on `FSharp.Core`, everything will build just fine, but will break at runtime, which is a really bad situation.

_Copied from original issue: aspnet/dnx#1994_

**Comment by piotrpMSFT** [comment]
This is already fixed in dotnet-compile-fsc.
