### ISSUE TITLE
linux-x64 SDK

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#5811]
Move from: https://github.com/dotnet/core-setup/issues/1578

The core-setup includes a linux-x64 build but it does not include an SDK.
Can you provide a linux-x64 SDK?

CC @piotrpMSFT @livarcocc @gkhanna79

**Comment by blackdwarf** [comment]
@eerhardt I assume this is related to 2.0 work?

**Comment by gkhanna79** [comment]
Yes.



Thanks,
Gaurav


-------- Original message --------

**Comment by eerhardt** [comment]
> I assume this is related to 2.0 work?

Yes, the "linux" RID is a new platform we need to support in 2.0.  There are other platforms we need to support for 2.0 as well, ex. Alpine.

See
https://microsoft.sharepoint.com/teams/netfx/CLR/ProjectK/_layouts/OneNote.aspx?id=%2Fteams%2Fnetfx%2FCLR%2FProjectK%2FDocuments%2FTactics%2FNET%20Core%20Release%2Fnet-core-release&wd=target%28net-core-release.one%7C0CF34A20-F342-FA43-8944-18B555589A6B%2F.NET%20Core%202.0%20Build%20and%20Test%20Configurations%7C727EFE44-B735-4CA3-90F4-DFE8A271C67A%2F%29

**Comment by blackdwarf** [comment]
OK, thanks guys, got it. Put it into 2.0 milestone already thinking 'twas so. :)

**Comment by blackdwarf** [comment]
Closing in favor of #5854 which seems to be the same ask.
