### ISSUE TITLE
Building without network access

### ISSUE THREAD

**Issue by abbradar** [dotnet/cli#5815]
Debian, NixOS (my case) and probably other distributions as time moves along work on improving reproducibility of packaging. Among other things it's expected that package can be built without Internet access.

Is it possible currently with .NET CLI? I tried to work on packaging it; I could force bootstrap to skip downloading stage0 by itself but now I have this:
```
Failed to create prime the NuGet cache. restore failed with: 1
```

Can I somehow download what `restore` requires and point it there?

**Comment by piotrpMSFT** [comment]
@abbradar what branch is your stage0 coming from? I wonder if `NixOS` has a different RID than Debian, requiring a different LZMA archive, to be available. If so, you will need to produce a one-time build on NixOS to get a `Stage0` that you can then use on subsequent builds.

I expect that this, by itself, won't be sufficient. You will also need to ensure that the CLI build has access to a shared framework, shared host, and all requisite NuGet packages. Supporting fully Offline builds was not a scenario we pursued in 1.0.0. I expect you will find success in enabling it, but it will be some work yet...

/cc @ellismg who spent some time working on a flavor of this scenario [offline build of CLI, etc.]

/cc @livarcocc

**Comment by abbradar** [comment]
@piotrpMSFT Not sure what do you mean by RID, sorry. I simply took .NET SDK 1.1 for Ubuntu 16.04, it works okay as stage0 for me.

Current problem is indeed with NuGet dependencies. Is there a way to build a snapshot of them and provide it later somehow?

**Comment by ellismg** [comment]
> Current problem is indeed with NuGet dependencies. Is there a way to build a snapshot of them and provide it later somehow?

Once you have the nupkg's that would be restored (which you can get by doing a build once "online" and the copying all the nupkgs downloaded to somewhere safe), you add an addition source to a folder with all the nupkg's in them to the top level `NuGet.Config`.

The build process will also want to download versions of the shared framework, as @piotrpMSFT says.  In the master branch, the DownloadFile task that does this now understands `file://` URLs and setting something like this property `https://github.com/dotnet/cli/blob/master/build/BundledRuntimes.props#L39` would let you point it at things you already have downloaded (note there's some path calculation going on in that file.)

We are working on automation to making building dependent repositories and shuttling artifacts along easier.

**Comment by bergmeister** [comment]
Any updates about this? Nornally I would expect that the NuGet Cache makes it possible to build offline and I was under the impression that this is the case. I am not sure if this is already resolved or if it is a different problem that makes it impossible to compile PowerShell (see referenced issue above) offline?

**Comment by livarcocc** [comment]
Closing as do don't have an official solution for offline build of the product itself. However, for distros building the .NET Core stack, the solution is source build.
