### ISSUE TITLE
dotnet command to clear NuGet cache shouldn't initialize the NuGet cache

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5819]
We sometimes use the command `dotnet nuget locals all --clear` to ensure our tests have a clean caches. On the second run, CLI will first attempt to initialize the cache. Then the command clears it. This wastes a few minutes of time and hard drive activity.

## Steps to reproduce
Run `dotnet nuget locals all --clear` twice.

## Expected  behavior
Second run is a no-op.

## Actual behavior
Second run first initialized cache, then clears it again

**Comment by piotrpMSFT** [comment]
@natemcmaster can you set `DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true`?

**Comment by natemcmaster** [comment]
Yeah, we can suppress the behavior with that variable. But it seems like this should be the default.

**Comment by livarcocc** [comment]
This is no longer the case, as the CLI does not run a restore as part of its first run anymore. We just expand the lzma into the fallback folder.
