### ISSUE TITLE
DTH should pass info about which project was responsible for determining which package version was used within a graph

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#582]
_From @DamianEdwards on May 29, 2015 18:53_

Right now, it's very hard to debug situations whereby multiple versions of a package are referenced in a graph and the version that "wins" is not what was expected. In these cases, it would really useful to know which project determined that a given version "won". As such, the DTH should pass this information over in the reference data.

This could then be shown in the Solution Explorer as an extra glyph overlaid on an accented nuget package icon, that indicates that this node was responsible for this version being used.

_Copied from original issue: aspnet/dnx#1989_

**Comment by blackdwarf** [comment]
DTH has been deprecated. We now have ProjectModel.Server.
