### ISSUE TITLE
dotnet migrate doesn't migrate all runtime/configProperties options to MSBuild properties

### ISSUE THREAD

**Issue by mairaw** [dotnet/cli#5827]
## Steps to reproduce
Have a project.json file to be migrated to csproj that has the runtime/configProperties set such as the following example:
```json
{
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true,
      "System.GC.Concurrent": true,
      "System.GC.RetainVM": true,
      "System.Threading.ThreadPool.MinThreads": 4,
      "System.Threading.ThreadPool.MaxThreads": 25
    }
  }
}
```

## Expected  behavior
All the properties would be migrated to MSBuild properties:
```xml
<PropertyGroup>
  <ServerGarbageCollection>true</ServerGarbageCollection>
  <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  <RetainVMGarbageCollection>true</RetainVMGarbageCollection>
  <ThreadPoolMinThreads>4</ThreadPoolMinThreads>
  <ThreadPoolMaxThreads>25</ThreadPoolMaxThreads>
</PropertyGroup>
```

## Actual behavior
Only ServerGarbageCollection was migrated:
`<ServerGarbageCollection>true</ServerGarbageCollection>`

The other values are migrated to the runtimeconfig.template.json file. However, the SDK already supports those as MSBuild properties, no? (see https://github.com/dotnet/sdk/pull/746).

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004854)

Product Information:
 Version:            1.0.0-rc4-004854
 Commit SHA-1 hash:  899fde25bd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004854

**Comment by RehanSaeed** [comment]
Is the plan to use `runtimeconfig.template.json` for now and the csproj properties after 2.0?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#23
