### ISSUE TITLE
LZMA Cache Hash should use evaluated project references, not explicit references

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#5829]
PR https://github.com/dotnet/cli/pull/5813 showed that, due to implicit references, the SDK version influences the contents of the LZMA cache and therefore needs to be considered during cache hash calculation. That PR accomplished this goal through a workaround: passing the SDK version to the LZMA Hash calculator to be considered explicitly.

Unfortunately, the immediate solution is lacking in two regards:
* It forces excessive cache regeneration due to SDK version changing without affecting the PackageReferences for a project
* It scales poorly to the influences of other SDKs. If WebSDK, for example, adds implicit references then its version will also need to be considered as part of hash computation [cc @mlorbetske to keep this in mind for the time being :)]

Instead, we should change the Hash calculator to do an evaluation for the project in question and to use all of its evaluated package references to compute the hash. This will scale nicely across SDKs and will avoid unnecessary cache regenerations.

/cc @livarcocc

**Comment by livarcocc** [comment]
No longer applicable, now that the CLI no longer produces the lzma archive.
