### ISSUE TITLE
PCL for Windows 8.1 + Windows Phone 8.1 (Profile 32)

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#583]
_From @smudge202 on May 17, 2015 2:41_

In addition to #1837, Profile 32 targeted PCL's are able to work with phone API's such as `Windows.Storage.StorageFolder`.

I believe it does this by referencing the `Windows.winmd` file for the Phone's SDK:
`C:\Program Files (x86)\Microsoft SDKs\Portable\v14.0\110C4FEFF2BA61C0746933A9ED6E248D\`

We are not able to this within a vNext class library targeting the same profile:
`.NETPortable,Version=v4.6,Profile=Profile32`

_Copied from original issue: aspnet/dnx#1883_

**Comment by smudge202** [comment]
The issue mentioned (previously 1837) has been migrated to this repo as issue #584

**Comment by jamesqo** [comment]
It would be nice if we were able to reference it through `frameworkAssemblies`:

```json
"frameworks": {
    ".NETPortable,Version=v4.6,Profile=Profile32": {
        "frameworkAssemblies": {
            "Windows": { "type": "build" }
        }
    }
}
```

**Comment by piotrpMSFT** [comment]
We can look at this once we move to the new project system.
