### ISSUE TITLE
ProjectDependenciesCommandFactory should allow specifying a runtime

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/cli#5830]
As identified in PR https://github.com/dotnet/cli/pull/5813, the SDK now [correctly] adds a RID to a project's output path if that RID is specified to `build`. `Microsoft.DotNet.Cli.Utils` is not yet able to consider a RID during project dependency tool invocation and therefore fails when invoking. We should expose an optional RID parameter to `ProjectDependenciesCommandFactory` so users can invoke tools in a RID-specific directory.

This change is a bit too invasive to pursue for 1.0.0, so opening this issue to track.

**Comment by livarcocc** [comment]
We no longer have that in the product.
