### ISSUE TITLE
Adding support for openSUSE Leap 42.2

### ISSUE THREAD

**Issue by ltines** [dotnet/cli#5834]
## Steps to reproduce
Go to https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md

## Expected  behavior
There's a link to download version for openSUSE Leap 42.2

## Actual behavior
The support for openSUSE 13.2 was dropped in one of the previous previews since the openSUSE release reached EOL. But there is no support for current openSUSE release.

Are there any plans to add the support?

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/tree/rel/1.0.1

We have builds available for OpenSUSE42.1 from that branch. Scroll down on the Readme.md for links.

**Comment by matt-richardson** [comment]
I see that 42.1 has builds available, but 42.1 reached end of life in May 2017.

The question asked above was about 42.2... Can we re-open this issue, but the answer given was related to 42.1.

Can you let us know what the plans are to support the current release?
