### ISSUE TITLE
dotnet restore yield error: "Package X is not compatible with net461 (.NETFramework,Version=v4.6.1). Package X supports: net461 (.NETFramework,Version=v4.6.1)"

### ISSUE THREAD

**Issue by Ashthos** [dotnet/cli#5835]
## Steps to reproduce

The error in the title is occurring for a number of packages in our solution. But **only** for our Win2016 Teamcity Build agents. Our Win2012 build agents restore the package fine. We are using/restoring packages that are deployed to our internal nexus server.

dotnet --version:
win2012 - 1.0.0-preview2-003133
win2016 - 1.0.0-preview2-1-003177

## Expected  behavior

Package restores correctly.

## Actual behavior

Package fails to restore.

```
Errors in .\src\worker\<projectname>.Ioc\project.json
     Package X is not compatible with net461 (.NETFramework,Version=v4.6.1). Package X supports: net461 (.NETFramework,Version=v4.6.1)
     One or more packages are incompatible with .NETFramework,Version=v4.6.1.
```

Where X is "\<packagename\>-v140.net 83.0.0-RC-86057-1"

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
This issue was moved to NuGet/Home#4697

**Comment by piotrpMSFT** [comment]
Moved to `nuget/home` repo
