### ISSUE TITLE
Missing VS2013 support in RC4

### ISSUE THREAD

**Issue by michalsznajder** [dotnet/cli#5836]
The latest `.NET Core SDK 1.0.0 - RC4 (build 004771)` seems to not support VS2013.

Do you plan to add support for VS2013 in future RC?

**Comment by svick** [comment]
See for example [this comment](https://github.com/dotnet/cli/issues/5755#issuecomment-280732145) by @mairaw:

> Visual Studio 2015 only supports up to Preview2. The latest tooling is only supported in Visual Studio 2017 RC.

So, the answer to your question is no. RC4 and future versions only work in VS2017.

(I'm assuming that you mean VS2015 and not VS2013. AFAIK, no version of .Net Core was ever supported on VS2013.)

**Comment by piotrpMSFT** [comment]
@svick is right. .NET Core tooling in Visual Studio will be released as part of VS 2017.
