### ISSUE TITLE
Why does VS2017 RC write Compile elements into the .csproj file

### ISSUE THREAD

**Issue by bruce31** [dotnet/cli#5837]
## Steps to reproduce
Use VSCode and cli tools to create a class library csproj targetting net461 that happens to include a class that inherits from a windows form control.
This builds happily with dotnet build

Open project with VS2017 RC

## Expected  behavior
csproj file should not be altered 
Especially references to .cs files should not be introduced.

## Actual behavior
.csproj file updated with

` <ItemGroup>`
`    <Compile Update="Dialogs\AssemblyDialog.cs">  `
`       <SubType>Form</SubType>  `
`   </Compile> `
`</ItemGroup>`

**Comment by piotrpMSFT** [comment]
What version of VS 2017 RC are you using?

**Comment by livarcocc** [comment]
It does that to update metadata about that particular file.

**Comment by bruce31** [comment]
Using VS Pro 2017 RC
15.0.0-RC.4+26206.0

The metadata (whatever that is) is clearly not required for the build as the dotnet command does not require it. If VS needs to keep track of something about the files in the project surely it can use the .vs folder that it has created which is usually excluded from source control.

The whole point of not requiring lists of .cs files in the project file was to banish forever the .csproj merge conflict issues.

**Comment by bruce31** [comment]
Clicked wrong button!

**Comment by livarcocc** [comment]
Please, move this issue to https://github.com/dotnet/roslyn-project-system.

**Comment by blackdwarf** [comment]
Opened dotnet/Roslyn-project-system#1643 to keep track of this. Closing this one.
