### ISSUE TITLE
SDK Support

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#584]
_From @smudge202 on May 11, 2015 8:10_

In essence, msbuild has a _special_ way of resolving _frameworkAssemblies_ when it comes to SDKs.

There are a series of registry entries located in the following locations:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKS\`
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Microsoft SDKS\`

From these registry entries you can retrieve both SDK installation directories and the appropriate `Reference Assemblies` directory.

DNX will currently only resolve an SDK assembly (for example the Silverlight 5.0 `System.Xml.Linq.dll`) if it is located in the Reference Assembly directory:
`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\Silverlight\v5.0`
**and** the respective entry is present in the `RedistList\Frameworks.xml`.

VS will list and correctly add Silverlight references to a csproj so long as it is present the Reference Assemblies directory (no `Frameworks.xml` entry required).

Because DNX does not respect the SDK directories in the same way MSbuild does, adding a `System.Xml.Linq` `frameworkAssembly` to an `SL5` framework target in `project.json` will result in failed compilation.

This issue _possibly_ exists for more than just the SL5 `System.Xml.Linq` assembly, but I haven't come across the issue elsewhere, _yet_.

Not tested, but one possible workaround or fix would be to supply SL5 assemblies in NuGet packages. Doing so may well allow users to create vNext class libraries that target SL5 without having to install the SL SDK.

_Copied from original issue: aspnet/dnx#1837_

**Comment by muratg** [comment]
_From @onovotny on July 16, 2015 11:48_

During the design of this, please keep Xamarin support (MonoTouch, Xamarin.iOS and MonoAndroid) in mind whatever the solution winds up being. 

Thanks

**Comment by piotrpMSFT** [comment]
Differences between CLI and msbuild will be addressed post preview2 in a broader work item.
