### ISSUE TITLE
dotnet run fails with System.IO.FileNotFoundException if using local class library

### ISSUE THREAD

**Issue by alejiro** [dotnet/cli#5847]
## Steps to reproduce
1. Create a console project `dotnet new console -n MyConsole`
2. Create a class library project `dotnet new classlib -n MyClass`
3. Reference class library project in the console project _MyConsole.csproj_ file using:
```
<ItemGroup>
    <Reference Include="MyClass">
       <HintPath>path_to_library/MyClass.dll</HintPath>
    </Reference>
 </ItemGroup
```
4.Use _MyClass_ in _MyConsole_
```
using System;
using MyClass;

namespace MyConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(MyClass.HelloWorld);
        }
    }
}
```
5. Run MyConsole application `dotnet run`

## Expected  behavior
Application executes 

## Actual behavior
Application crashes with:
```
Unhandled Exception: System.IO.FileNotFoundException: 
Could not load file or assembly
'MyClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
The system cannot find the file specified.
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004893)

Product Information:
 Version:            1.0.0-rc4-004893
 Commit SHA-1 hash:  ca4d0b8fbb

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004893
```

**Comment by livarcocc** [comment]
Is it possible for you to reference the library you depend on with a ProjectReference instead of a direct reference. That will work with the 1.0 version of the tools.

Also, we have added support for direct references in 2.0. So, if you need that, you can try with the 2.0 version of the tooling, but keep in mind that that is an early version preview.

**Comment by Jonathan34** [comment]
Project reference or packagereference which means DotNet pack to create a nuget package until 2.0 is out

**Comment by los93sol** [comment]
I am using the 2.0 version of the tools but this still does not work

**Comment by livarcocc** [comment]
Can you provide a small repro repo? Like on github that we can try running ourselves? Makes debugging these things that much easier.

**Comment by livarcocc** [comment]
The failed scenario is not supposed to work. You can execute the contents of your build folder like that. You can do that with the contents of your publish folder.

**Comment by sidshetye** [comment]
@livarcocc I'm confused. After wiping the `bin` folder (and rebuilding it), `dotnet .\bin\Debug\netcoreapp2.0\repro.dll` or `cd \bin\Debug\netcoreapp2.0` and `dotnet repro.dll` both work just fine. If I look at the [official docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore2x#examples), it seems `dotnet myapp.dll` should indeed work. So why are you saying the failed scenario is not supposed to work? We're new to the new tooling, so genuinely curious.

**Comment by livarcocc** [comment]
Executing `dotnet myapp.dll` is the way to execute Framework Dependent Applications. You are right on that. However, running your app from the build folder is not the way to distribute or execute your app in production.

When ready to move your app into production, you should publish your app and xcopy the contents of the publish folder as a way to distribute it. See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore2x. Hope this helps.
