### ISSUE TITLE
Need a setting in project.json to enable xml doc comments

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#585]
_From @BillHiebert on April 27, 2015 15:6_

This option is needed to allow generation of xml doc comments. It would also be picked up by tooling to provide diagnostics for broken or missing comments.

_Copied from original issue: aspnet/dnx#1717_

**Comment by muratg** [comment]
_From @barrytang on June 2, 2015 20:57_

Happening in beta5?

**Comment by muratg** [comment]
_From @barrytang on June 2, 2015 20:57_

@Eilon, @davidfowl ?

**Comment by muratg** [comment]
When we internalized the JSON parser (and moved away from json.net, we decided not to add comment support on json files, as they are not valid per the RFC.

**Comment by muratg** [comment]
_From @GuardRex on June 2, 2015 23:54_

@BillHiebert If you mean comments in the project.json file, it was discussed here ...
https://github.com/aspnet/Announcements/issues/24
https://github.com/aspnet/dnx/issues/1816

**Comment by muratg** [comment]
Or do you guys mean a switch which would enable/disable XML comment generation on source code?

**Comment by muratg** [comment]
_From @Eilon on June 8, 2015 15:54_

This is about generating the doc XML file. Nothing to do with comments in JSON :smile:

**Comment by muratg** [comment]
_From @Eilon on June 8, 2015 15:54_

And BTW I thought we always generate it now, don't we? At most I think we'd have an option to turn it off (though, do we even need that?).

**Comment by muratg** [comment]
_From @BillHiebert on June 8, 2015 22:2_

@davidfowl  
Looks like that is the case. So I should just enable it by default instead of having it disabled by default.

**Comment by muratg** [comment]
_From @barrytang on June 10, 2015 5:28_

Moved to U1.

@BillHiebert's comment:

I put in a small change to enable document comments in the language service since the runtime is generating the xml file anyway. However, Roslyn does a lot of validation (kind of like fxcop) when doc comments are enabled and I see 260 warnings in the error list for a new Web Application.

**Comment by muratg** [comment]
_From @barrytang on June 10, 2015 5:29_

![foo](https://cloud.githubusercontent.com/assets/1648865/8075595/05d8ba8e-0ef7-11e5-94ad-05b426422cd2.png)

**Comment by muratg** [comment]
_From @davidfowl on June 10, 2015 5:43_

Uhhhh this cannot be on by default.

**Comment by muratg** [comment]
_From @BillHiebert on June 10, 2015 15:45_

Nope. I punted the bug to update1 until there is a way to enable\disable the feature in project.json

**Comment by muratg** [comment]
_From @davidfowl on June 10, 2015 15:46_

Sweet

**Comment by muratg** [comment]
_From @barrytang on July 17, 2015 21:38_

@davidfowl, where are we at with the runtime change?

**Comment by muratg** [comment]
_From @davidfowl on July 17, 2015 21:49_

@barrytang This bug isn't in a milestone and so it doesn't exist :smile:

**Comment by muratg** [comment]
_From @barrytang on July 17, 2015 22:44_

@BillHiebert, can you update it? I don't seem to have permission to.

**Comment by muratg** [comment]
_From @BillHiebert on July 17, 2015 23:39_

How do I do that?

**Comment by muratg** [comment]
_From @BillHiebert on July 17, 2015 23:43_

Looks like I don't have permission either. I assume it is because this is in the Dnx project

**Comment by muratg** [comment]
_From @barrytang on July 18, 2015 5:22_

@davidfowl, what kind of tool is this? :)

Can you set the milestone?

**Comment by muratg** [comment]
_From @davidfowl on July 18, 2015 5:26_

/cc @muratg This needs to go through triage.

**Comment by muratg** [comment]
_From @Anderman on October 22, 2015 10:33_

@muratg  I found a incorrect xml documetation. Is this something that will be fixed later or do must I make a new issue of this
```
/// <summary>
        /// Initalizes a new instance of the <see cref="RoslynCompilationService"/> class.
        /// </summary>
        /// <param name="environment">The environment for the executing application.</param>
        /// <param name="loaderAccessor">
        /// The accessor for the <see cref="IAssemblyLoadContext"/> used to load compiled assemblies.
        /// </param>
        /// <param name="libraryManager">The library manager that provides export and reference information.</param>
        /// <param name="compilerOptionsProvider">
        /// The <see cref="ICompilerOptionsProvider"/> that provides Roslyn compilation settings.
        /// </param>
        /// <param name="host">The <see cref="IMvcRazorHost"/> that was used to generate the code.</param>
        public RoslynCompilationService(
            IApplicationEnvironment environment,
            IAssemblyLoadContextAccessor loaderAccessor,
            ILibraryExporter libraryExporter,
            ICompilerOptionsProvider compilerOptionsProvider,
            IMvcRazorHost host,
            IOptions<RazorViewEngineOptions> optionsAccessor)
```

**Comment by muratg** [comment]
@Anderman That class is in MVC repo, please file a bug in that repo.  This bug in particular tracks ability to generate XML doc comments file for your libraries and apps.

**Comment by jonathansotoan** [comment]
Any hint about when this is going to be implemented?

**Comment by nbarbettini** [comment]
Also wondering about any roadmap status for this. For now, I've been creating a shim .csproj file and adding all my library code to it so I can generate the XML needed for API documentation. Not sure if there's a better way to go about it, but it works.

**Comment by Eilon** [comment]
@nbarbettini I think it's already there, actually. In ASP.NET we started using these options: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/project.json#L12-L13

**Comment by tillig** [comment]
@Eilon does that flag also tell the compiler to generate warnings about missing docs and/or broken `<see cref />` links?

**Comment by Eilon** [comment]
I believe so. And I think that's the warning that is disabled in the link I gave.

**Comment by nbarbettini** [comment]
Can confirm: `dnu build` on 1.0.0-rc1-update1 produces XML output when I have `"xmlDoc": true` in my project.json.

Thanks @Eilon! Does that mean this issue can be closed?

**Comment by Eilon** [comment]
I believe so, but I'll leave it to the dotnet-cli team to close it. Not sure why it's sitting in Backlog, I'll move it out.

**Comment by blackdwarf** [comment]
Closing, verified that it works with the CLI.

**Comment by kyschouv** [comment]
Any chance this could be added to the schema?

http://json.schemastore.org/project

**Comment by muratg** [comment]
@kyschouv https://github.com/dotnet/cli/issues/933

**Comment by niemyjski** [comment]
We really need this for our api consumers.
