### ISSUE TITLE
Poor experience if you forget a dotnet restore step. 

### ISSUE THREAD

**Issue by vancem** [dotnet/cli#5851]
## Steps to reproduce

I am currently just trying out the V2.0 stuff.   It is easy for you to repro by repeating what I did.
First I created a directory called 'hello2' and in that directory ran

    dotnet new console

 Next, I forget to do the dotnet restore, but instead simply type 

    dotnet run

And I get the following spew.  

C:\Users\Vancem\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [C:\Users\Vancem\Documents\hello2\hello2.csproj]
obj\Debug\netcoreapp2.0\hello2.AssemblyInfo.cs(6,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\Vancem\Documents\hello2\hello2.csproj]
....

This is a very bad experience.  While this was user error (although I have never understood why restore can't be just part of the build), we need an error message that leads people to the solution, and the error above does NOT do that.

Note that this particular case is easy to detect because there are NO references yet (presumably not even to the runtime).   I don't know how the Nuget references are remembered, but presumably there is some file in the obj or bin directory that does that and its complete absence would make it clear that a dotnet restore was NEVER done and a suitably helpful message could be output. 

We need to either make dotnet restore optional, or make a better error message if you forget it.

**Comment by davidfowl** [comment]
Agreed. Previously there was a check that compared the project.json contents to the contents of the lock file to make sure things were "up to date". That seems to have gone missing in the msbuild conversion.

**Comment by piotrpMSFT** [comment]
This issue was moved to dotnet/sdk#918

**Comment by piotrpMSFT** [comment]
Agreed. Moving this to the SDK repo as this needs to be addressed regardless of the invoker of our targets.
