### ISSUE TITLE
dotnet migrate incorrectly set RuntimeIdentifier tag in csproj

### ISSUE THREAD

**Issue by Ashthos** [dotnet/cli#5857]
## Steps to reproduce

Execute "dotnet migrate" on a Preview 2 project

## Expected  behavior

Generates csproj file which successfully builds.

## Actual behavior

Add a \<RuntimeIdentifiers\> tag which incorrectly has a trailing 's' (i.e. it is pluralised). This isn't compatible with the "dotnet build" command, which raises an error such as:

```
C:\Program Files\dotnet\sdk\1.0.0-rc4-004771\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets(64,5): error : RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. [D:\apps\teamcity\BuildAgent\work\7adbbe63a1137576\src\worker\Project.Host\Project.Host.csproj]
```

Related to #4619

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by livarcocc** [comment]
We are actually no longer adding a runtime identifier when migrating, unless you already had one or more in your project.json, in which case we will move them over.

**Comment by Ashthos** [comment]
@livarcocc you missing the issue I think. I don't think this should have been closed.

When you **are** adding the runtime identifier (as it may be in the project.json) you are using a tag in the csproj which dotnet build does not accept.

Regardless of whether it needs to be there or not, if you are generating a new csproj file the tags included in the file should be compatible with the dotnet build command.

In my instance, there is a "runtimes" element in the project.json, which is what I am assuming you are migrating.  I do not have any tags which are RuntimeIdentifier or RuntimeIdentifiers
