### ISSUE TITLE
CopyToPublishDirectory Never Does Not Work

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/cli#5858]
I have a `.gitignore` file in the `wwwroot` folder of my project that I am trying to exclude from being published. The following code does not seem to work, when I publish the project, the `.gitignore` file is still found in the output directory.

```
  <ItemGroup>
    <Content Include="wwwroot\.gitignore">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
```

**Comment by livarcocc** [comment]
You should use Content Update="wwwroot\.gitignore" instead of the Include above.

**Comment by RehanSaeed** [comment]
Thanks!
