### ISSUE TITLE
Migrating VS 2015 C# Windows Universal app Missing TargetFrameWorkVersion

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/cli#5859]
_From @WallyZambotti on February 27, 2017 3:38_

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-rc4-004771
VS Code version:
1.9.1
C# Extension version:
1.7.0
## Steps to reproduce
Open a VS 2015 Community Edition Visual C#/Windows/universal Solution/Project
dotnet restore
dotnet build

## Expected  behavior
Build succeeded.
    0 Warning(s)
    0 Error(s)

## Actual behavior
Build FAILED.

/usr/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The refere
nce assemblies for framework ".NETFramework,Version=v4.5.2" were not found. To resolve this, install the SDK or T
argeting Pack for this framework version or retarget your application to a version of the framework for which you
 have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (
GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for
 the framework you intend. [/home/wallyz/DBTransferImportAgent/DropBoxTransferAgent.csproj]
    0 Warning(s)
    1 Error(s)

## Additional comments

I have tried changing the framework to a variety of different versions but none are found.

Pointers to some documentation for supported .Net target frameworks would be appreciated.  I recall reading something on the web but now can't find anything.

Also tried the dotnet msbuild with same results.

_Copied from original issue: OmniSharp/omnisharp-vscode#1263_

**Comment by DustinCampbell** [comment]
Moving over to the .NET CLI repo.

**Comment by livarcocc** [comment]
Can you share your csproj? If this project is being created through VS 2015, it is likely in the old csproj format, which is not really supported by the CLI. I would suggest either modifying the project to the new format. Or creating a new project using either the CLI itself or VS 2017.

**Comment by WallyZambotti** [comment]
@livarcocc 
Thanks for the tip.  Probably a mute point as Windows Universal apps are not supported in CORE yet!
