### ISSUE TITLE
Getting a CLI SDK that supports the 2.0 framework

### ISSUE THREAD

**Issue by challe** [dotnet/cli#5868]
I was asked to create an issue here to drive the discussion about how to get a CLI SDK that supports 2.0 framework after asking about this problem in https://github.com/dotnet/core-setup/issues/725.

I'm simply trying to create a .NET Core Web API for my Raspberry Pi 3 running Ubuntu 16.04 with the `2.0.0-beta-001619.00` runtime. I'm using Visual Studio Code on Windows when developing.

## Steps to reproduce
My current SDK version is `2.0.0-alpha-004853`. I then simply do `dotnet new webapi`. This adds these  package references in my csproj-file:
```
<PackageReference Include="Microsoft.AspNetCore" Version="1.0.3" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.2" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.1" />
```
When I then publish my project using `dotnet publish --runtime ubuntu.16.04-arm`, and later running it on my Raspberry Pi using `usr/bin/dotnet /home/challe/dev/test/test.dll`, I am met by `Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0...`

I was told the reason I am getting this error is because of the package references that was added, and that I need to add 2x compatible ones. Is that the reason why it's currently not working? Is there a way of making this work as of now? If so, how do I include the 2x compatible ones?

## Expected  behavior
I expected to be able to run my published self contained application on my Raspberry Pi using
`usr/bin/dotnet /home/challe/dev/test/test.dll`. 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-004853\

**Comment by gkhanna79** [comment]
@piotrpMSFT @livarcocc PTAL.

Also see https://github.com/dotnet/core-setup/issues/725#issuecomment-283114679.

CC @rahulreddy65

**Comment by livarcocc** [comment]
There are a few things here that are confusing:
1. When you ran dotnet `publish --runtime ubuntu.16.04-arm`, did you also ran `dotnet restore --runtime ubuntu.16.04-arm`? If not, do you have that RID in your csproj?
2. You are publishing your app as a self-contained app (exe), which is indicated by the --runtime flag, but you are trying to run it as a portable app, by using dotnet dll. Just pointing out that you can use the <your_app> executable in the published folder to run the app.

**Comment by challe** [comment]
Thanks for your input. I'm fairly new to this, and right now it's a matter of piecing together github issues to get an understanding of how this all works.

My goal was to follow the guide [here](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction), and use nginx as a reverse proxy for Kestrel. There, in your service, you finally do `ExecStart=/usr/bin/dotnet /var/aspnetcore/hellomvc/hellomvc.dll`.

Should I therefore _not_ publish my app as a self-contained app, in the way I'm currently doing it? When I do `dotnet publish --runtime ubuntu.16.04-arm`, I don't get an exe file out, I just get a bunch of DLLs. Should I just do `dotnet publish`, like in the guide I linked to?

And even if I made that work correctly, wouldn't I still have the problem with using 1.x packages in my csproj-file?

**Comment by rahulreddy65** [comment]
I downloaded the 2.0.0 version without sdk. I need sdk which works with it. Where can I download it.

**Comment by challe** [comment]
@rahulreddy65 I don't remember where I found the link, but I got mine from here:
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.exe

**Comment by challe** [comment]
After adding
```
<add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```
to `C:\Users\challe\AppData\Roaming\NuGet\NuGet.Config`, I'm finally able to use this in my csproj-file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001509-00</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-preview1-23668" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-preview1-23668" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.2.0-preview1-23668" />
  </ItemGroup>
</Project>
```
After a `dotnet restore`, a `dotnet publish`, and copying all of the DLL's in my publish-folder to my Raspberry Pi, I now get `Segmentation fault` when doing `usr/bin/dotnet /home/challe/dev/test/test.dll`.

Any ideas?

**Comment by livarcocc** [comment]
@gkhanna79 Can you help debug this segmentation fault?

**Comment by challe** [comment]
@livarcocc @gkhanna79 I should point out that I'm getting this warning when doing `dotnet publish` as well as when doing `dotnet run` (but the API works just fine on my development machine):

```
C:\Program Files\dotnet\sdk\2.0.0-alpha-004853\Microsoft.Common.CurrentVersion.targets(1951,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [c:\dev\test\test.csproj]
```
Not sure if this is related to the segmentation fault.

**Comment by rahulreddy65** [comment]
@challe  I want the linux arm32 version of sdk. Do you know where I can find it?

**Comment by livarcocc** [comment]
We don't currently produce a CLI for arm. We produce a runtime that you can use to run your applications there, but they need to be developed on a separate OS.

**Comment by rahulreddy65** [comment]
@livarcocc do you mean I can run applications  which are already compiled on another OS? But when I run 'dotnet run' it says "Did you mean to run dotnet SDK commands?"

**Comment by livarcocc** [comment]
run in a CLI command. In order to run the application in arm you need to either publish it as a portable application and run it by invoking dotnet <your_dll>.dll or as a stand alone app and then running it with <your_app>.

To build as a stand alone app you need to either restore and publish with --runtime, passing your rid or having that RID set under <RuntimeIdentifier> in your csproj.

**Comment by rahulreddy65** [comment]
I understand, thank you.

**Comment by rahulreddy65** [comment]
I'm getting `A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/Hello/'.` error when running `dotnet helloworld.dll` command. How to fix that error?

**Comment by livarcocc** [comment]
can you share your csproj for this project? Also, is this when running in arm or in your development box?

**Comment by rahulreddy65** [comment]
I downloaded it from `https://www.dllme.com/dll/files/helloworld_dll.html` and I'm running it on arm.

**Comment by challe** [comment]
@rahulreddy65 I have gotten that error message before on my arm. The simple mistake I made then was that I published the entire `bin/debug/netcoreapp2.0`folder (which does contain a dll-file) instead of the content of `bin/debug/netcoreapp2.0/publish/` (which also contains a dll-file with the same name).

**Comment by challe** [comment]
@livarcocc Do you want me to create separate issue for the `Segmentation fault`-error? Or should I perhaps update my initial comment with my latest problem? When I wrote that comment I didn't even know how to get the 2.x compatible packages.

Also, I have created a wiki page [here](https://github.com/challe/dotnet-core-raspberry-pi/wiki/Setting-up-a-Web-API-on-a-Raspberry-Pi-3-(Ubuntu-16.04)-using-.NET-Core-2.x) describing all of the steps I have taken so far to making this work (currently stuck on the Segmentation fault).

**Comment by livarcocc** [comment]
Please, file an issue for it under dotnet/core-setup.

**Comment by challe** [comment]
I think this can be closed, unless you want to keep it open for a more general discussion? All the problems I have encountered when trying to get the Web API running using .NET Core using 2.x compatible packages are now solved (and my wiki page is updated). We also have [this issue](https://github.com/aspnet/Coherence/issues/166) to follow for other blocking issues.

**Comment by livarcocc** [comment]
Thanks @challe.
