### ISSUE TITLE
VB support

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#587]
_From @muratg on April 24, 2015 18:40_

_Copied from original issue: aspnet/dnx#1706_

**Comment by muratg** [comment]
_From @ErikSchierboom on April 25, 2015 15:54_

Any chance for F# support too?

**Comment by muratg** [comment]
_From @Eilon on April 25, 2015 21:49_

@ErikSchierboom not currently planned but that would be a good project for the community to start up.

**Comment by muratg** [comment]
_From @davidfowl on April 25, 2015 21:52_

VB, F#, dylan.NET (yes this is a real language) support will all be via the same mechanism. This is a generic extensibility point. The real problems come when tooling support is added (intellisense support in Visual Studio etc.)

**Comment by muratg** [comment]
_From @ErikSchierboom on April 26, 2015 7:1_

@davidfowl So the VB support will be like a template for how to do F# integration?

**Comment by muratg** [comment]
_From @davidfowl on April 26, 2015 7:4_

Yes and just FYI this isn't new https://github.com/YoloDev/YoloDev.FSharp.AspNet. https://github.com/davidfowl/vNextLanguageSupport. Language support was refactored a while ago so that we can add more languages. That's not really the big problem, though it still needs to be cleaned up.

**Comment by muratg** [comment]
_From @ErikSchierboom on April 26, 2015 7:12_

That looks promising! Will there be any kind of documentation on how new languages can be added, or will we be able to infer that from the added VB support?

**Comment by muratg** [comment]
_From @davidfowl on April 26, 2015 7:14_

There'll be something documented once the churn ends. Talk to @Alxandr, he's spent a considerable amount of time experimenting with F# and the dnx compilation system (even got it working with in memory assemblies).

**Comment by muratg** [comment]
_From @Alxandr on April 26, 2015 7:41_

Yes, and then, when I started looking at it again like 5 hrs ago, everything has blown up xD.

Well, unstable APIs and all that. I'll try to get F# support working again against beta5 soon~ish.

**Comment by borgdylan** [comment]
I am currently working on dylan.NET support for the CLI (requires net451 so it runs on mono/.NET). IMHO the VB support can be done using a copy/paste/adapt methodology as it would be similar to the csharp case. After all vbc and csc are both bundled together in the roslyn packages.

**Comment by justinmchase** [comment]
How about boo? How can I add boo to this system (and other languages)?

**Comment by nbarbettini** [comment]
:+1: Looking forward to VB.NET support.

**Comment by kolbma** [comment]
Any progress on this?

**Comment by blackdwarf** [comment]
@borgdylan we are moving away from `project.json` system and over to MSBuild and csproj as [this blog post](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) explains.

**Comment by piotrpMSFT** [comment]
The migration to MSBuild is redefining how dotnet interacts with compilers. Since this work is still under development, enabling VB support is blocked for the moment.

**Comment by romrom38** [comment]
Any update on vb support ?
If you intend to have help could you at least please start by giving people pointers ?

**Comment by piotrpMSFT** [comment]
@srivatsn thoughts?

**Comment by srivatsn** [comment]
For VS, there are templates for VB projects [here](https://github.com/dotnet/sdk/tree/master/src/Templates/ProjectTemplates/VisualBasic/.NETCore) We have been blocked on a [compiler bug](https://github.com/dotnet/roslyn/issues/13681) that was causing F5 to fail but that has been recently fixed. With that fix the templates should build and debug. However, we haven't tested the new project system for VB at all and therefore haven't put the templates in VS yet.

For the CLI I don't think VB specific work is needed (apart from an extension to `dotnet new` to spit out a vb project). I think if you grab the project from that template and invoke `dotnet build` that should just work

**Comment by piotrpMSFT** [comment]
@srivatsn do we have a `well known prototype vb template` that folks can `use at their own risk`?

**Comment by srivatsn** [comment]
Yes the ones I point to above are definitely `use at your own risk` :)
