### ISSUE TITLE
First Run Message and LZMA Cache Expansion are intertwined.

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#5873]
## Steps to reproduce

1. Download a CLI drop
2. Delete the .lzma archive that comes in the drop.
3. Run `dotnet help`
4. Run `dotnet help`

## Expected  behavior

The first invocation of `dotnet help` prints the first run message, the second does not.

## Actual behavior

Both commands print the first run goop.  I think this is because the cache priming does not happen (since the LZMA file is missing) and so we never write the sentinel file (and so stuff in `DotnetFirstTimeUseConfigurer` thinks it always needs to write messages)

## Environment data
`dotnet --info` output:

**Comment by ellismg** [comment]
Since the build from source effort will produce CLI's without the lzma files, I'll want to fix this shortly.

**Comment by livarcocc** [comment]
So, your proposal is to simply separate the two behaviors? For instance, register that the message was shown and don't show again? This is not enough. You need to not show the telemetry message, but the priming message should still be shown.

I think maybe what we need is a thing to turn off the nuget cache priming entirely (in some scope). Something like DOTNET_SKIP_NUGET_CACHE_PRIMING. The first run would still run based on the sentinel, we would skip the cache priming, generate the sentinel and things would work from there.

Though, using an env variable would mean this is true for all. If that's enough for the build from source perspective. This is fine by me.

**Comment by ellismg** [comment]
> So, your proposal is to simply separate the two behaviors? For instance, register that the message was shown and don't show again? This is not enough. You need to not show the telemetry message, but the priming message should still be shown.

I think we should be writing a sentinel file for "have we showed the first run message about telemetry collection" and another for "we have primed the cache".  Most of the first run message is tied to the existence of the telemetry sentinel file, the only part that isn't is the "please stand by while we extract some stuff".  The telemetry sentinel file is shared across versions of the CLI (we can include a version number in it if we want the flexibility to re-pop the message if we ever change it).

This means if in the normal case if you download the CLI and do a `dotnet help` it will print two messages, the first run message and the we're going to extract stuff message.  When you download the next build of the CLI that has a new lzma archive in it, we don't print the first run message but we do print the cache priming thing.

**Comment by livarcocc** [comment]
@ellismg However, this does not address the case where we don't have the lzma archive present. For this case, we will show the priming message 100% of the time, which I think for the build from source case, we would not want to.

**Comment by ellismg** [comment]
> @ellismg However, this does not address the case where we don't have the lzma archive present. For this case, we will show the priming message 100% of the time, which I think for the build from source case, we would not want to.

I agree.  I think showing the priming message should be conditional on both the lzma archive being present and the complete sentinel existing.  Does that make sense?

**Comment by livarcocc** [comment]
> I agree.  I think showing the priming message should be conditional on both the lzma archive being present and the complete sentinel existing.  Does that make sense? 

I am actually a bit worried about this approach. As we may have an issue in the build that would be hidden by it. Plus, I would prefer for us to be explicit on choosing this or not.

**Comment by ellismg** [comment]
> I am actually a bit worried about this approach. As we may have an issue in the build that would be hidden by it. Plus, I would prefer for us to be explicit on choosing this or not.

The behavior of the system today when the `.lzma` file does not exist (as well as the sentinel being missing) is to just show the first run message, not do any extraction and continue.  Are you saying that you think that's a bug and we should fix that as well?

**Comment by livarcocc** [comment]
I am saying that today we don't really expect the lzma file to be missing and it is only so when someone tinkers with it explicitly. Now, we are making this a feature and we should put the right safety guards in place so that this feature does not slip in the main build accidentally without us noticing.

**Comment by Petermarcu** [comment]
I think the lzma file missing should be a good reason to skip the nuget cache extraction and it shouldn't really have any impact on whether the first run message shows or not. It should trigger the message of "extracting the cache" if the lzma file is there. We need to make it an option to have a CI friendly SDK.

**Comment by ellismg** [comment]
I think that @livarcocc's point is that for a build where we expect the lzma file to be present, if it's not present, we should error out in some reasonable way instead of just silently skipping over the cache priming step.

I think the wants to guard against some case where the lzma file stopped getting included in the official builds (due to some authoring error somewhere) and then we are blind to the downstream implications.

**Comment by Petermarcu** [comment]
That would just make us have to build binaries twice for these two configurations. If we wanted to test for that. I'd just have a test that verifies the file is in the build we expect it to be in and not in the other. I'm hoping we will produce an SDK zip with caches, templates, and all the getting started materials. I'm also hoping we can just zip up a smaller set of assets into a "minimal" SDK which is great for CI. Nobody needs offline caches, dotnet new templates, etc in their CI.

**Comment by Petermarcu** [comment]
In summary, I need to ability to have an SDK that doesn't have this lzma file in it and have it function without having to build a different set of binaries.

**Comment by livarcocc** [comment]
@Petermarcu I am not disagreeing on your point at all. I just feel like we should be explicit about it by adding a knob that allows us to turn off the cache part of the first run entirely.

Also, for CI, in a sense, we already have all the pieces in place. We have a knob to turn off producing the LZMA archive, which I believe @ellismg added himself and we have the DOTNET_SKIP_FIRST_RUN_EXPERIENCE which could be set for CI that would turn that the whole first run off, which I would argue makes perfect sense in CI.

Though, in some sense, I feel that maybe what we should have is some form of configuration that we could ship with the CLI itself. We talked about this in the past but never gave much thought to it. But it would work well here.

**Comment by Petermarcu** [comment]
Funny, I mentioned config to @piotrpMSFT when I was talking to him about my needs :). 

It would be nice to able to persist in some way with the sdk I'm using that I want a certain behavior without having to set env vars. In the absense of that, I think enabling things like "deleting the lzma file" from a zip to signal that you don't want the cache to be expanded seems like a very reasonable gesture and is easily persisted.

Like I said, i'm hoping we can have the CLI repo start building minimal CI zips that drop all the first run, offline cache, and dotnet new stuff (800MB decompressed :(). Ideally this could just be a matter of just putting less files in that zip.

**Comment by livarcocc** [comment]
@ericstj A failure is not blocking. Has never been blocking, however, we will display the message and attempt to prime the cache over and over again until we succeed. The idea of not having an lzma archive present is new and we need to deal/think through it and make the appropriate changes.

**Comment by livarcocc** [comment]
By the way, these are now separated. The cache expansion sentinel and the first run message sentinel.
