### ISSUE TITLE
Roslyn R2R differences in private vs shared copies.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5874]
I'm looking at the latest build of the SDK in master (2.0). 

Roslyn (CSharp) in the shared frameworks is the 1.3 version and is 10MB when R2R. Roslyn in the CLI's Roslyn folder is version 2.0 and is 7MB. They are both generated from very similar size IL. Something is likely wrong here. We should take a closer look.

**Comment by livarcocc** [comment]
I don't think we need this anymore, since the shared framework no longer carries Roslyn with it. @Petermarcu, if there is anything else you want us to take a look here, please, re-activate.
