### ISSUE TITLE
Can't compile against MonoTouch/MonoAndroid

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#588]
_From @bricelam on April 21, 2015 15:41_

Similar to aspnet/dnx#1679, but it get's a bit further:

    Building Microsoft.Data.Sqlite for MonoTouch,Version=v0.0
      Using Project dependency Microsoft.Data.Sqlite 1.0.0
        Source: C:\Projects\DataCommon.SQLite\src\Microsoft.Data.Sqlite\project.json

      Unable to resolve dependency framework/mscorlib

_Copied from original issue: aspnet/dnx#1680_

**Comment by muratg** [comment]
_From @davidfowl on April 21, 2015 16:16_

I assume you have those frameworks installed? If you do, then it's likely that we just don't recognize the TFM.

**Comment by muratg** [comment]
_From @bricelam on April 21, 2015 16:42_

Yes, they're installed.

**Comment by muratg** [comment]
@anurse.

Are we supporting this (and #1679) in V1?

**Comment by muratg** [comment]
_From @anurse on September 11, 2015 18:50_

It shouldn't be too hard, but to do it right we'll want a CI that has the frameworks installed so we can test it

**Comment by piotrpMSFT** [comment]
At the moment CLI does not support building Mono projects. When this is added as a supported scenario we'll make sure that Compile [as well as restore, publish, run, test, etc.] have a reasonable story.
