### ISSUE TITLE
CLI needs to move to 2.0.0-preview1-XYZ versioning scheme.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5883]

**Comment by piotrpMSFT** [comment]
is the ask here simply to change the suffix from alpha- to preview1-?

**Comment by Petermarcu** [comment]
Generally, yes, folks are still trying to figure this out. People noticed we were beta in core-setup and alpha in CLI and are getting confused. We need to come up with a better plan and I filed this to track that.

**Comment by livarcocc** [comment]
Done.
