### ISSUE TITLE
When scaffolding a data view in VS, I get duplicated key error for DOTNET_SKIP_FIRST_TIME_EXPERIENCE 

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/cli#5887]
Not sure if this is the right repo, but I'll start here:

## Steps to reproduce
- Set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 as an environment variable
- Launch VS (I'm using 15.0.26228.0)
- Create an ASP.NET Core application
- In project view, right click `Controllers ->Add->New Scaffolded Item` and then select `MVC Controller - Empty`
- Fill in name

## Expected  behavior
- New controller should be generated

## Actual behavior
- Get an error:

![image](https://cloud.githubusercontent.com/assets/583206/23484744/0fe74180-fe8d-11e6-9403-b9d1b08665c5.png)

*For searching, the text is:*

```
Error

There was an error running the selected code generator: 'Item has already been added. Key in dictionary: 'DOTNET_SKIP_FIRST_TIME_EXPERIENCE' Key being added: 'DOTNET_SKIP_FIRST_TIME_EXPERIENCE''
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

C:\Program Files (x86)\Microsoft Visual Studio\2017\Internal>
```

**Comment by livarcocc** [comment]
@BillHiebert Can you take a look? Are you the right person?

**Comment by piotrpMSFT** [comment]
This issue was moved to dotnet/roslyn-project-system#1668

**Comment by piotrpMSFT** [comment]
Moved this to the project system repo. It looks like VS is trying to add the key despite it already being present.
