### ISSUE TITLE
Can't compile against Xamarin.iOS

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#589]
_From @bricelam on April 21, 2015 15:33_

Given the following `project.json`...
```JSON
{
    "frameworks": {
        "xamarinios": {
            "frameworkAssemblies": {
                "mscorlib": "2.0.5.0"
            }
        }
    }
}
```
...build succeeds, but there is no assembly for the Xamarin.iOS framework.

_Copied from original issue: aspnet/dnx#1679_

**Comment by muratg** [comment]
Do we need more TFMs? @anurse

**Comment by muratg** [comment]
_From @davidfowl on December 7, 2015 10:32_

@bricelam does this work yet?

**Comment by muratg** [comment]
_From @bricelam on December 7, 2015 18:12_

Haven't tried. @natemcmaster?

**Comment by muratg** [comment]
_From @natemcmaster on December 7, 2015 18:16_

No.

```
$ dnu build --quiet
Microsoft .NET Development Utility Mono-x64-1.0.0-rc2-16249


Building xma for DNX,Version=v4.5.1

/private/tmp/xma/project.json(3,23): error NU1008: "xamarinios" is an unsupported framework.

Build failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.0357848
Total build time elapsed: 00:00:00.0489319
Total projects built: 1
```

**Comment by muratg** [comment]
_From @davidfowl on December 7, 2015 18:20_

Try with the CLI

**Comment by muratg** [comment]
_From @natemcmaster on December 7, 2015 18:30_

What's the cli incantation I need? Whatever I try for `DOTNET_REFERENCE_ASSEMBLIES_PATH` I get the same error:

```
DOTNET_REFERENCE_ASSEMBLIES_PATH=/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/ dotnet compile 
Compiling xma for Xamarin.iOS,Version=v0.0
/private/tmp/xma/project.json(3,23): error DOTNET1011: Framework not installed: Xamarin.iOS,Version=v0.0 in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/2.1/

Compilation failed.
    0 Warning(s)
    1 Error(s)
```

**Comment by piotrpMSFT** [comment]
At the moment CLI does not support building Xamarin projects. When this is added as a supported scenario we'll make sure that Compile [as well as restore, publish, run, test, etc.] have a reasonable story.

**Comment by ghuntley** [comment]
😢 If you need an early adopter/guinea pig nerd snipe me @piotrpMSFT
