### ISSUE TITLE
dotnet build doesn't pinpoint error when build fails

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#5895]
## Steps to reproduce

I cloned `core-setup` and made a few changes there, mostly to study how RIDs are resolved by `Microsoft.DotNet.PlatformAbstractions`. Doing a build in core-setup then fails:

    $ /home/omajid/core-setup/.dotnet_stage0/Linux/dotnet build_projects/dotnet-host-build/ build
    Object reference not set to an instance of an object.

I just get a one-line error message, and no further pointers to where/what might have caused it. No suggestions on how to fix it.

## Expected  behavior

`dotnet build` tells me where the error happened and maybe some sort of stack trace or source information

## Actual behavior

`dotnet build` shows me an error message without any additional information

## Environment data

This version of dotnet was pulled down by core-setup.

`dotnet --info` output:

    .NET Command Line Tools (1.0.0-preview3-003886)
    
    Product Information:
     Version:            1.0.0-preview3-003886
     Commit SHA-1 hash:  4b0c2f5ebe
    
    Runtime Environment:
     OS Name:     rhel
     OS Version:  7.2
     OS Platform: Linux
     RID:         rhel.7.2-x64

**Comment by livarcocc** [comment]
I see you are using preview3. Is this for project.json or msbuild? In any way, can you please move to the latest CLI build (migrating your project.json to csproj if necessary) and try again?

**Comment by omajid** [comment]
This is the current master branch of `dotnet/core-setup` repo here on github, though I made some local changes to get this error. The project uses `project.json` files. Is there any other option for me to debug this with `dotnet` tooling short of migrating? I don't own this project and I am not sure if I know enough to migrate it.

**Comment by livarcocc** [comment]
you can run dotnet -v for verbose mode, which may give you additional information.

**Comment by omajid** [comment]
Thank you! I was using `dotnet build -v` which is quite a bit less useful than `dotnet -v build`. Thanks!

**Comment by livarcocc** [comment]
We are not actively supporting project.json tooling anymore. The msbuild based tooling should give you as good diagnostics as msbuild does.
