### ISSUE TITLE
Trying to standardize a reef project to .net framework standard 2.0, .net framework 4.5

### ISSUE THREAD

**Issue by skanjila** [dotnet/cli#5899]
## Steps to reproduce
Hello,
I am running the portability analyzer on my Org.Apache.REEF.Network project and am targeting .Net Framework 4.5, .Net Standard 2.0, I am running into a bunch of warnings like whats shown below

System.Runtime.Caching.MemoryCache.#ctor(System.String,System.Collections.Specialized.NameValueCollection)
Not supported on .NET Standard,Version=v2.0; ASP.NET Core,Version=v1.0	Org.Apache.REEF.Network	C:\code\reef\lang\cs\Org.Apache.REEF.Network\Naming\NameCache.cs	53	

It looks like a lot of the APIs in the MemoryCache class will change, I was wondering if a) What the replacement for this class is .Net Standard 2.0 b) If there is no replacement then what is the recommended best practice to get past issues like this

## Expected  behavior
One of the two options mentioned above

## Actual behavior
N/A

## Environment data
`dotnet --info` output:

C:\code\localreefwork\lang\cs>dotnet --info output
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by piotrpMSFT** [comment]
Hi @skanjila 

There might be a few issues here. The first, most importantly, is that you're using a CLI which isnt being tested against netstandard2. 1.0.0-rc4-* is only tested against 1.*. Can you install latest from the home page of this repo and see if this still repro's?

**Comment by skanjila** [comment]
Done, here are details, please let me know next steps:
C:\code\localreefwork\lang\cs>dotnet --info output:
.NET Command Line Tools (2.0.0-alpha-005165)

Product Information:
 Version:            2.0.0-alpha-005165
 Commit SHA-1 hash:  4a0724e136

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-alpha-005165\

**Comment by skanjila** [comment]
So I tried to install the following nuget package: Microsoft.Extensions.Caching.Memory and I get the following message:

**Comment by skanjila** [comment]
Following up on this, any updates?

**Comment by livarcocc** [comment]
@skanjila This package targets netstandard1.3, which is compatible with net46. Can you try with that?

The compatibility matrix can be seen here: https://github.com/dotnet/standard/blob/master/docs/versions.md.
