### ISSUE TITLE
Set NuGet minClientVersion to 2.8.5 when using dnx* TFMs

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#590]
_From @anurse on March 30, 2015 17:50_

Older versions of NuGet will be unhappy with these TFMs :). Our packages should require this minimum version of NuGet.

/cc @yishaigalatzer 

_Copied from original issue: aspnet/dnx#1544_

**Comment by muratg** [comment]
_From @glennc on September 4, 2015 17:56_

@anurse Does this still need to happen?

**Comment by muratg** [comment]
_From @anurse on September 4, 2015 18:13_

I think it should. We should ensure we set the minClientVersion appropriately. We'll need similar code to what NuGet has to determine the appropriate version. This can happen in RC though.

**Comment by piotrpMSFT** [comment]
dnx* tfms are no longer supported.
