### ISSUE TITLE
dotnet new creates files with unix-style new lines on Windows

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#5901]
Some editors do not like that `\r`s are missing. 

Is this by design?

**Comment by livarcocc** [comment]
I think there is an issue tracking this already. In any case, this should be moved to dotnet/templating.

@mlorbetske to confirm if we have an issue tracking this over there.

**Comment by sayedihashimi** [comment]
https://github.com/dotnet/templating/issues/350
