### ISSUE TITLE
dotnet add reference help is confusing

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#5902]
The help for `dotnet add reference` says:
```
Arguments:
  <PROJECT>  The project file to operate on. If a file is not specified, the command will search the current directory for one.
```

That led me to believe I could just point to the directory I wanted to reference, which seems untrue. 

## Steps to reproduce
Make two projects, one a classlib and one a console app.
Try to add a P2P reference in the console app to the class lib just by specifying its directory:
dotnet add reference c:\path\to\classlib
Do not specify the csproj directly

## Expected  behavior
It works

## Actual behavior
PS E:\work\scratch\ref2>dotnet add reference ..\ref1
Reference ..\ref1 does not exist.
.NET Add Project to Project reference Command

Usage: dotnet add <PROJECT> reference [options] [args]

Arguments:
  <PROJECT>  The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h|--help                   Show help information
  -f|--framework <FRAMEWORK>  Add reference only when targetting a specific framework

Additional Arguments:
 Project to project references to add

PS E:\work\scratch\ref2>dotnet add reference ..\ref1\ref1.csproj
Reference `..\ref1\ref1.csproj` added to the project.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-alpha-004853)

Product Information:
 Version:            2.0.0-alpha-004853
 Commit SHA-1 hash:  e7689a3116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\work\dotnets\2.0.0-alpha-004853\sdk\2.0.0-alpha-004853\

**Comment by livarcocc** [comment]
@blackdwarf @mairaw can you guys come up with a description for that param that won't have this confusing effect?

**Comment by mairaw** [comment]
With the docs we have more space, so we make that a bit more clear, I think:
https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-add-reference

Perhaps if you said "Project files to reference" for the additional arguments?

**Comment by mairaw** [comment]
Also the other issue that might be causing the confusion here is that the usage is not showing where the first argument is used. Like in our docs we show like this:
`dotnet add [<PROJECT>] reference [-f|--framework] <PROJECT_REFERENCES>`

From reading the usage from --help, if you can't really tell where you put the project file to operate on.

**Comment by jonsequitur** [comment]
I'd like to come to a decision on how the new parser's help output should be formatted. Aligning the format to the online documentation is appealing for the sake of consistency. Is the size of the synopsis output in the CLI a concern? Some tools, like git, have fairly verbose synopses, but I find it significantly easier to understand.

**Comment by livarcocc** [comment]
@richlander can you chime in regarding the format of help and how to address @billwert's concern here?

**Comment by livarcocc** [comment]
Here is what we are doing now:

```
dotnet add reference --help
.NET Add Project to Project reference Command

Usage: dotnet add <PROJECT> reference [options] <args>

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.
  <args>      Project to project references to add

Options:
  -h, --help                    Show help information
  -f, --framework <FRAMEWORK>   Add reference only when targeting a specific framework
```

I believe that's pretty good. So I will close this issue. If there is something specific you want to change, we can discuss it, but this is aligned with other commands now, thanks to the new parser.
