### ISSUE TITLE
dotnet-install scripts description of params and real params don't seem to match 

### ISSUE THREAD

**Issue by mairaw** [dotnet/cli#5908]
## Steps to reproduce
Open https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1

## Expected  behavior
Description talks about a Verbose parameter and doesn't talk about UncachedFeed. It also talks about a 4-part version in the format of A.B.C.D and I though our versions are a 3-part version as in MAJOR.MINOR.PATCH[-PRERELEASE-BUILDNUMBER].

## Actual behavior
cmdletbinding doesn't have a Verbose parameter and does contain an UncachedFeed parameter. Version description would match CLI version scheme.

I'm not an expert on PS, so I could be misunderstanding but noticed that while trying to update the docs for this.

**Comment by johnbeisner** [comment]
"cmdletbinding doesn't have a Verbose parameter" - the 'Verbose' cmdletbinding is included for all PS scripts; we cannot include it explicitly.
