### ISSUE TITLE
Consider moving the .dnx directory on Windows to a subdirectory of %AppData%

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#591]
_From @pranavkm on March 26, 2015 21:54_

On Windows, everything under the `Users` directory with the exception of the `AppData` sub directory is indexed. Consequently restoring packages kicks off the search indexer. It doesn't look like it's actually indexing package contents, but it does index the file names. Moving it would avoid all the extra work.

_Copied from original issue: aspnet/dnx#1507_

**Comment by muratg** [comment]
_From @IRLeif on June 2, 2015 14:13_

I'm not sure if this is related, or if it's a separate issue.

My company limits the Windows profile storage space to 30 MB, and my `.dnx` directory currently takes up 120 MB in my user directory.

It would be very nice if it were possible to somehow move this folder to another location. Is there a config option to change the location of this folder?

I have also posted this question to StackOverflow, here: http://stackoverflow.com/questions/30613404/how-to-move-dnx-directory-out-of-userprofile

**Comment by muratg** [comment]
_From @Suchiman on July 2, 2015 21:42_

This also bugs me, but not only for the reasons already mentioned.

DNX behaves like a badly ported unix application on windows:
* being cmd focused (ok, it's still far away from release, expecting more complete tooling later)
* prefixing folders with `.` which is totally useless on windows, cheats on alphabetical sorting and is ugly
* being in the `%USERPROFILE%` folder where programs don't belong into

So i strongly agree on moving it into one of the `%AppData%` folders and having the `.` removed, e.g. `%AppData%\dnx`

**Comment by muratg** [comment]
_From @ghuntley on August 5, 2015 6:31_

See also https://twitter.com/davkean/status/628456517205823492

**Comment by muratg** [comment]
_From @bitcrazed on August 5, 2015 6:47_

If only GitHub issues had a voting mechanism. I'd give this 100 thumbs up.

**Comment by muratg** [comment]
_From @Suchiman on August 5, 2015 6:55_

I've asked this in a ASP.NET Community Standup and this is unlikely to happen http://blogs.msdn.com/b/webdev/archive/2015/07/07/asp-net-community-standup-july-7-2015.aspx see Q&A or the video

**Comment by muratg** [comment]
_From @shiftkey on August 5, 2015 7:10_

:thumbsup: to this change. Here's the [MSDN reference](https://technet.microsoft.com/en-us/library/cc749104(v=ws.10).aspx) about %USERPROFILE% (well, it's alias %CSIDL_PROFILE%)

<img width="835" alt="screen shot 2015-08-05 at 5 08 25 pm" src="https://cloud.githubusercontent.com/assets/359239/9080170/aabe3686-3b94-11e5-9dab-26cb4b71ccfb.png">

**Comment by muratg** [comment]
_From @RichiCoder1 on August 5, 2015 7:23_

Agree with all the above. I'm all for cross uniformity, but this is explicitly AppData.

**Comment by flipchart** [comment]
Thought I'd weigh in. My .dnx folder is currently sitting at 2.06GB. This makes it a prime target to get off my primary drive (128 GB SSD drive, currently almost full due to the HUGE VS installation, along with the emulator VMs that want to be under AppData as well).

**Comment by xanather** [comment]
@flipchart if you've been using DNX for a while there is no doubt the packages folder within the .dnx directory is full of junk, its safe to delete it and only restore the latest packages your projects need (should clear up some space). Could also delete older runtimes too.

**Comment by jberezanski** [comment]
The dnx folder should ideally be placed under AppData\Local (i.e. %LOCALAPPDATA%), so that it would play nice with roaming profiles and folder redirection.

The fact that other platforms historically did not define conventions for per-user application data placement and applications were free to clutter the user profile directory should not result in importing this mess to Windows. Incidentally, there actually has been a standardization effort in some Linux/Unix circles, leading to [this proposal](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). According to it, dnx on Linux should probably be placed in $HOME/.local/share/dnx.

**Comment by blackdwarf** [comment]
The CLI doesn't create a .dnx directory anymore. The installer properly places files in Program Files on Windows. The install scripts also properly defaults on Windows as well.

**Comment by pranavkm** [comment]
A bit unfortunate because we still have a %UserProfile%/.nuget directory. I guess we can transfer the bug over to to NuGet team.

**Comment by blackdwarf** [comment]
@pranavkm yup.

**Comment by Zoltu** [comment]
Was this bug transferred over to the NuGet team?  I was about to file a bug about the creation of the `.nuget` folder (which should be `%APPDATALOCAL%/NuGet`) when I run `dotnet restore`.  If not I'll create one (application folders in my user profile directory are a pet peve of mine).

**Comment by pranavkm** [comment]
@Zoltu just did - https://github.com/NuGet/Home/issues/2861
