### ISSUE TITLE
Allow dotnet test to work with solution files

### ISSUE THREAD

**Issue by ErikSchierboom** [dotnet/cli#5911]
## Steps to reproduce

Go to a directory in which there is a `.sln` file. Execute the `dotnet test` command.

## Expected  behavior

Running `dotnet test` on all projects in the solution. This already works for `dotnet restore` and `dotnet build`.

## Actual behavior

An error message is displayed:

<pre>
Couldn't find a project to run test from. Ensure a project exists in /<directory>.
Or pass the path to the project
</pre>

## Environment data
`dotnet --info` output:

<pre>
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.0-rc4-004771
</pre>

**Comment by livarcocc** [comment]
Dup of https://github.com/Microsoft/vstest/issues/411.
