### ISSUE TITLE
Migration is not migrating all the DEFINES

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#5914]
## Steps to reproduce
1. git clone https://github.com/exceptionless/Exceptionless.Net
2. dotnet migrate

## Expected  behavior
The define constants should be on both PropertyGroups.

## Actual behavior

```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.2' ">
    <DefineConstants>$(DefineConstants);NO_SQL_CLIENT;NETSTANDARD;NETSTANDARD1_2</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
    <DefineConstants>$(DefineConstants);NETSTANDARD1_3</DefineConstants>
  </PropertyGroup>
```

## Environment data
`dotnet --info` output:

**Comment by niemyjski** [comment]
I'm linking here to the specific commit (https://github.com/exceptionless/Exceptionless.Net/tree/5d063552f395fe8b43402ed7ed3566420d007e95) that should be tested. I may manually upgrade this project :)

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#19
