### ISSUE TITLE
Scaffold-Db returns error, from PowerShell crashes

### ISSUE THREAD

**Issue by glararan** [dotnet/cli#5919]
## Steps to reproduce

1. Uninstall all .NET Core
2. Install .NET Core 1.1 x86, x64, Tools for VS 2015 Preview 2
3. in root do command at "Actual behavior" from Powershell

global.js
> {
>   "projects": [ "src", "test" ],
>   "sdk": {
>     "version": "1.0.0-preview2-1-003177"
>   }
> }
> 

If I run this command in Package Manager Console

> Scaffold-DbContext "Data Source=ADMIN;Initial Catalog=MyDatabase;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entities

I get following error:
**Could not find assembly 'F:\WebApplication1\.\bin\Debug\net461\win7-x64\WebApplication1.exe'.**

I did not configure project as x64. win7-x86 exists.

## Actual behavior

> dotnet ef dbcontext scaffold "Data Source=ADMIN;Initial Catalog=MyDatabase;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite
> ;MultiSubnetFailover=False" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Entities
> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Utils.Reporter' threw an exception. ---> System.TypeLoadException: Could not load type 'System.ConsoleColor' from assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
>    at Microsoft.DotNet.Cli.Utils.Reporter..ctor
>    at Microsoft.DotNet.Cli.Utils.Reporter..cctor()
>    --- End of inner exception stack trace ---
>    at Microsoft.EntityFrameworkCore.Tools.DotNet.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15025
 OS Platform: Windows
 RID:         win10-x86

Thanks for any idea how to resolve it :)

**Comment by livarcocc** [comment]
We are no longer actively support preview2 or preview2-1 (project.json) as we have moved all the tooling to MSBuild. It is very close to RTM and I suggest that you move your project to the lastest build of the CLI from here: https://github.com/dotnet/cli/tree/rel/1.0.1.

If you have a project.json project that you want to move, read about it here: https://github.com/dotnet/cli/blob/rel/1.0.1/Documentation/ProjectJsonToCSProj.md

Otherwise, just create a new one.

Let us know if you run into the same issue with the new version of the tooling.

**Comment by glararan** [comment]
@livarcocc Thanks, was waiting for new Visual Studio 2017 (.csproj from dotnet migrate was not supported by VS2015) and confirm, its working :)
