### ISSUE TITLE
dnu restore/build/pack should allow globbing patterns

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#592]
_From @davidfowl on March 25, 2015 8:12_

dun build/restore/pack should should support globbing patterns so make recursive restore/build easier and more efficient. 

```
dnu build src/** - Build all projects under the src folder recursively.
dnu restore samples/* - Restore all projects directly under samples
```
By default, these commands should only work on the current project or allow passing in a target project.

_Copied from original issue: aspnet/dnx#1495_

**Comment by muratg** [comment]
_From @davidfowl on July 7, 2015 7:54_

Build supports globbing but restore doesn't /cc @ChengTian

**Comment by muratg** [comment]
_From @ChengTian on July 7, 2015 16:50_

Here is the "globbing" currently used by `dnu restore`:
For `dnu restore <path>`,
1. If `<path>` is a `project.json`, only restore for it
2. If `<path>` is a directory which contains a `project.json`, only restore for the `project.json`
3. If `<path>` is a directory which doesn't contain any `project.json`, recursively find all `project.json` and restore for all of them.

I assume we want to remove the logic above because they can be expressed with globbing patterns. Also, having two rules combined can be confusing.

**Comment by muratg** [comment]
@davidfowl Are there any usage patterns you'd like that's not supported with the Wei's explanation above?  To me, it seems to cover all the important cases.  

It's not the same syntax as build but I feel that's fine.

**Comment by muratg** [comment]
_From @0xdeafcafe on October 19, 2015 0:23_

did this go anywhere? Having it behave in the same manor `dnu restore` would he fantastic.

**Comment by muratg** [comment]
_From @khellang on October 19, 2015 8:36_

With all the globbing support being added here and there, is it worth proposing that this functionality is pulled into its own little library, i.e. `System.IO.FileSystem.Globbing` under [corefxlab](https://github.com/dotnet/corefxlab/)? Or has this already been done somewhere?

**Comment by blackdwarf** [comment]
We may want to consider this for the CLI at least for `dotnet build`.

**Comment by piotrpMSFT** [comment]
Chatted with @blackdwarf and we decided to close this.
