### ISSUE TITLE
Pack command for selective TFM needs clarity in help

### ISSUE THREAD

**Issue by am11** [dotnet/cli#5921]
## Steps to reproduce

```sh
dotnet pack -h
[snip]
Additional Arguments:
 Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.

dotnet msbuild -h
[snip]
        MSBuild MyApp.csproj /t:Clean
                             /p:Configuration=Debug;TargetFrameworkVersion=v3.5
```

Assuming this means for .NET Standard v1.6, we must use `/p:TargetFrameworkVersion=v1.6` switch:

```sh
mkdir test && cd $_

# create a basic project file called `test.cspoj` with two two TFMs:
cat <<EOT > test.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net451;netstandard1.6</TargetFrameworks>
  </PropertyGroup>
</Project>
EOT

# restore and build
dotnet restore

# pack for netstandard1.6
dotnet pack /p:TargetFrameworkVersion=v1.6 .
```

## Actual behavior

> /usr/share/dotnet/sdk/1.0.0-rc4-004771/Microsoft.Common.CurrentVersion.targets(1111,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v1.6" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/adeel/test/test.csproj]

## Workaround

If we instead use `TargetFramework`, then it succeeds:

```sh
dotnet pack /p:TargetFramework=v1.6 .

Microsoft (R) Build Engine version 15.1.545.13942
Copyright (C) Microsoft Corporation. All rights reserved.

  test -> /home/adeel/test/bin/Debug/netstandard1.6/test.dll
  Successfully created package '/home/adeel/test/bin/Debug/test.1.0.0.nupkg'.
```

## Expected  behavior

Package creation succeeds. Alternatively, `dotnet msbuild -h` should suggest `TargetFramework` instead of `TargetFrameworkVersion` in the command-line help example.

## Environment data
`dotnet --info` output:

```sh
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-rc4-004771
```

**Comment by livarcocc** [comment]
cc @blackdwarf @mairaw

**Comment by blackdwarf** [comment]
@am11 what is the scenario you are trying out? I believe that NuGet packages are quite happy having assets for multiple target frameworks within one package. This is, I believe, the reason why `dotnet pack` command does not support the `--framework` option ( @emgarten for confirmation and/or more details). 

The MSBuild help *is* confusing, but we need to open the issue on the Microsoft/MSBuild repo to modernize that message or add Core-specific samples.

**Comment by emgarten** [comment]
> NuGet packages are quite happy having assets for multiple target frameworks within one package.

That is correct, packages should contain the complete set of frameworks.

**Comment by am11** [comment]
Thanks for the pointers. I will move the rewording issue to MSBuild repo.

@blackdwarf, I was upgrading a repo for CLI RC4 readiness, and found they had `dotnet pack` in place of `build` in their CI, which executes for each typical build matrix combination: `tfm x configuration`. However, it makes sense to modify the build matrix in such a way that it runs the pack command for each configuration (debug/release), but once for all TFMs.
