### ISSUE TITLE
install .NET Core 1.0.1 fail  (tried SKIP_VSU_CHECK=1 already)

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#5926]
@Innocence commented on [Thu Sep 15 2016](https://github.com/dotnet/coreclr/issues/7215)

.NET Core 1.0.1 - VS 2015 Tooling Preview 2

---

@benaadams commented on [Fri Sep 16 2016](https://github.com/dotnet/coreclr/issues/7215#issuecomment-247579924)

Might be better to raise this here https://github.com/dotnet/cli

**Comment by livarcocc** [comment]
Is this for the VS add-on installer?

if so, we have moved from project.json based tools to msbuild based tools and VS 2017 is very close to shipping.

**Comment by livarcocc** [comment]
This looks like the project.json tooling for VS 2015, which we are not actively supporting.

Please try VS 2017.
