### ISSUE TITLE
Error running dotnet in Travis Ubuntu 14.04

### ISSUE THREAD

**Issue by KodrAus** [dotnet/cli#5929]
I'm trying to run a `dotnet` build in Travis's Ubuntu 14.04 environment and getting issues.

## Steps to reproduce

Install `dotnet` on Ubuntu 14.04. I have a travis config [here](https://github.com/KodrAus/nuget-rs/blob/ci/travis/.travis.yml#L22-L24) that's installing `dotnet-rc4-004771` on Ubuntu 14.04.

Run `dotnet --info`.

## Expected  behavior

Command prints `dotnet` info.

## Actual behavior

```
dotnet: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)
```

## Environment data
`dotnet --info` output:

Travis build output [here](https://travis-ci.org/KodrAus/nuget-rs/jobs/208090759). That version of `GLIBC` is indeed not available:

```
$ sudo strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC

GLIBCXX_3.4

GLIBCXX_3.4.1

GLIBCXX_3.4.2

GLIBCXX_3.4.3

GLIBCXX_3.4.4

GLIBCXX_3.4.5

GLIBCXX_3.4.6

GLIBCXX_3.4.7

GLIBCXX_3.4.8

GLIBCXX_3.4.9

GLIBCXX_3.4.10

GLIBCXX_3.4.11

GLIBCXX_3.4.12

GLIBCXX_3.4.13

GLIBCXX_3.4.14

GLIBCXX_3.4.15

GLIBCXX_3.4.16

GLIBCXX_3.4.17

GLIBCXX_3.4.18

GLIBCXX_3.4.19

GLIBC_2.3

GLIBC_2.2.5

GLIBC_2.14

GLIBC_2.4

GLIBC_2.18

GLIBC_2.3.4

GLIBC_2.17

GLIBC_2.3.2
```

**Comment by KodrAus** [comment]
I'll probably work around this by running my build in one of the `dotnet` containers, but out-of-the-box support for Travis would definitely be nice.

**Comment by livarcocc** [comment]
@gkhanna79 @ellismg Can you help here?

**Comment by gkhanna79** [comment]
Sounds like missing dependencies - what do you think @janvorli ?

**Comment by janvorli** [comment]
@KodrAus are you sure you have really installed dotnet package for Ubuntu 14.04 and not for a higher version of Ubuntu? The package for Ubuntu 14.04 should depend on max glibcxx 3.4.19, so I don't know where the reference to 3.4.21 came from. Could you please share the link that you have downloaded the package from.

**Comment by KodrAus** [comment]
@janvorli sure, the link I've used is https://go.microsoft.com/fwlink/?linkid=841684, which I grabbed from the [downloads page](https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md).

**Comment by janvorli** [comment]
@gkhanna79 the package that we expose on that page for Ubuntu 14.04 is incorrect. I cannot run it on my 14.04 either. It looks like the links are swapped between Ubuntu 16.04 and 14.04. The package for 16.04 refers to max glibcxx version 3.4.18 while the package for 14.04 refers to max glibcxx version 3.4.21.
@KodrAus can you please try to get the package for Ubuntu 16.04 now and see if it works for you?

**Comment by KodrAus** [comment]
@janvorli Switching links does seem to fix that issue.

**Comment by janvorli** [comment]
@KodrAus thank you for confirmation! 
@gkhanna79 who is responsible for updating the links?

**Comment by gkhanna79** [comment]
@leecow @blackdwarf should be able to get RC4 page link fixed.

**Comment by leecow** [comment]
Sorry about that. Fixed!

**Comment by KodrAus** [comment]
No worries, thanks for the quick fix @leecow!
