### ISSUE TITLE
CoreCLR failing to restore build tools on OSX

### ISSUE THREAD

**Issue by janvorli** [dotnet/cli#5930]
@janvorli commented on [Thu Feb 23 2017](https://github.com/dotnet/coreclr/issues/9734)

```
18:08:54 Running init-tools.sh
18:08:54 Installing dotnet cli...
18:09:18 Restoring BuildTools version 1.0.27-prerelease-01209-01...
18:09:19 
18:09:19 Unhandled Exception: System.ArgumentNullException: Value cannot be null.
18:09:19 Parameter name: path1
18:09:19    at System.IO.Path.Combine(String path1, String path2, String path3)
18:09:19    at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider.ResolvePackagesPath(String rootDirectory, GlobalSettings settings)
18:09:19    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
18:09:19    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
18:09:19    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.ShouldPrimeNugetCache()
18:09:19    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
18:09:19    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
18:09:19    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
18:09:19    at Microsoft.DotNet.Cli.Program.Main(String[] args)
18:09:19 /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest@2/tests/../init-tools.sh: line 164: 68854 Abort trap: 6           $__DOTNET_CMD restore "$__PROJECT_JSON_FILE" --no-cache --packages $__PACKAGES_DIR --source $__BUILDTOOLS_SOURCE >> $__init_tools_log
18:09:19 
ERROR: Could not restore build tools correctly. See '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest@2/init-tools.log' for more details.1
```

---

@janvorli commented on [Thu Feb 23 2017](https://github.com/dotnet/coreclr/issues/9734#issuecomment-281945352)

The first build failed with this issue in CI is
https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx_flow_prtest/3149/

---

@janvorli commented on [Thu Feb 23 2017](https://github.com/dotnet/coreclr/issues/9734#issuecomment-281947669)

I am unable to repro the issue on my local OSX machine.

---

@janvorli commented on [Thu Feb 23 2017](https://github.com/dotnet/coreclr/issues/9734#issuecomment-281947729)

CC: @gkhanna79 

---

@gkhanna79 commented on [Thu Feb 23 2017](https://github.com/dotnet/coreclr/issues/9734#issuecomment-282049456)

@livarcocc @piotrpMSFT Can you PTAL?

---

@gkhanna79 commented on [Sat Mar 04 2017](https://github.com/dotnet/coreclr/issues/9734#issuecomment-284175385)

@janvorli Can you please move this issue to CLI repo?

**Comment by eerhardt** [comment]
What version of the CLI are you using? The

```
at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
```

code changed on `7/26/2016` (8 months ago) to no longer call that `PackageDependencyProvider.ResolvePackagesPath` method.

**Comment by eerhardt** [comment]
Also, you can (and probably should) disable the first-run experience in your CI.

```
$env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
```

The CLI will no longer get into that code path that is throwing the error.

**Comment by ellismg** [comment]
There is a very high probability that this was happening on a CI machine where `$HOME` is unset and NuGet null refs.  I've seen crashes like this before in that case.

**Comment by livarcocc** [comment]
Like Eric said, that code has changed when we moved to csproj based tooling. But, you can either set the skip flag to not use that code path (though I suspect it will simply fail further down the road) or check @ellismg suggestion above. We have run into this in a few cases as well where we needed to set $HOME.
