### ISSUE TITLE
Running Gulp before publish?

### ISSUE THREAD

**Issue by MaticLeva** [dotnet/cli#5931]
It seems that dotnet publish runs before gulp tasks even when I specified it should not. Similar to [this](https://github.com/aspnet/live.asp.net/blob/dev/src/live.asp.net/live.asp.net.csproj#L39) my `.csproj` looks like this but doesn't work properly.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Update="css\*.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm install" />
    <Exec Command="gulp sass" />
  </Target>

</Project>
```

## Steps to reproduce
Clone [this repo](https://github.com/MaticLeva/prepublish). Run `dotnet publish -c Release` 

## Expected  behavior
I expect Gulp to run `sass` task and then dotnet publish to compile and publish the app. Since all `css/*.css` files are marked as always copy I expect to see compiled `test.css` in output folder. 

## Actual behavior
App is published before Gulp task.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
 ```

**Comment by dasMulli** [comment]
There is a difference between the "output directory", which will be `bin/Release/netcoreapp1.0/` and the "publish directory", which will be `bin/Release/netcoreapp1.0/publish/`.
If you are not using the Web SDK (`Sdk="Microsoft.NET.Sdk.Web"`), you may need add more metadata to the `<None>` item: `CopyToPublishDirectory="Always"`.

If the file does not exists before the pre-publish target (clean build, generated file not in source control), you'll likely run into https://github.com/aspnet/websdk/issues/114 (workaround: https://github.com/aspnet/websdk/issues/114#issuecomment-280076533).

**Comment by livarcocc** [comment]
@MaticLeva if @dasMulli suggestions does not fix your problem, please re-activate this issue with more information about the problems you are running into.
