### ISSUE TITLE
Excluding folder contents from publish

### ISSUE THREAD

**Issue by ralphking** [dotnet/cli#5934]
Publishing from Visual studio to IIS server on Windows Server 2012 R2

In .csproj:

```
<ItemGroup>
   <Content Include="wwwroot\LicenceFiles" CopyToPublishDirectory="Never" />
</ItemGroup>
```

## Expected  behavior
 For the contents of this directory not to be published

## Actual behavior
The directory contents are being added to the server when publishing

Is there another way in core to stop folders from being published? Specifically, this is a folder that I am writing generated PDF files to. Obviously I don't want to be pushing up any of the files that have been generated in development, so want to retain the folder on the server but just not sync any content.

**Comment by livarcocc** [comment]
Please use 

```
<ItemGroup>
   <Content Update="wwwroot\LicenceFiles" CopyToPublishDirectory="Never" />
</ItemGroup>
```

The Web SDK (assuming that's what you are using) is including these files for you already. So you need to update the files' metadata to prevent them from being published.

**Comment by ralphking** [comment]
Unfortunately that is giving the same behaviour

**Comment by livarcocc** [comment]
@mlorbetske Can you take a look at this?

Also, how are you publishing this? CLI, VS? Which version?

**Comment by ralphking** [comment]
This is in VS 2017 RC, Core 1.1.

If I right click a folder and exclude a file from the project, I can see that in .csproj it will have automatically added an itemgroup to remove the file, and that will work. It only seems to be what I am adding that isn't working with regards to changes to .csproj

**Comment by livarcocc** [comment]
Oh, wwwroot\LicenceFiles is a folder? you need to do wwwroot\LicenseFiles\**\* if you want to update the metadata for everything under that folder.

**Comment by ralphking** [comment]
Is that kind of thing covered in the docs anywhere?

Ie CopyToPublishDirectory, CopyToOutputDirectory and other options

**Comment by livarcocc** [comment]
@blackdwarf @mairaw for documentation.

@ralphking barring additional documentation, is this working for you know? Can we go ahead and close this issue?

**Comment by ralphking** [comment]
No, it doesn't work. There's not much more information that I can give to debug unfortunately.

Is there any documentation for it at all at the moment?

Thanks

**Comment by mlorbetske** [comment]
Cc @vijayrkn

**Comment by vijayrkn** [comment]
@ralphking 
I just tried this on VS 2017 RTW and seems to be working. It is excluding all the files (including sub directories) from wwwroot\images

```xml
  <ItemGroup>
    <Content Update="wwwroot\images\**\*.*" CopyToPublishDirectory="Never" />
  </ItemGroup>
```

If you are publishing from VS, please make sure to check this so that if the files are already present, they will be removed as well.

![image](https://cloud.githubusercontent.com/assets/3981619/23869594/bfb009d8-07e0-11e7-97b1-00f41e0f670d.png)

**Comment by livarcocc** [comment]
I updated my previous comment above about which glob to use. I didn't realize that github that processed it to appear different from what I had typed.

Also, follow up @vijayrkn instructions above and let us know if that works out for you.

**Comment by livarcocc** [comment]
@ralphking I am closing this issue. If this is still not working for you, please re-activate.

**Comment by mairaw** [comment]
I was trying to see if the MSBuild reference had those options but it doesn't seem to have all of them:
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items. 

I'll open an issue in their repo for this.

/cc @kempb

**Comment by max-favilli** [comment]
I have the same problem and tried with:

```
  <ItemGroup>
    <Content Update="wwwroot\images\**\*.*" CopyToPublishDirectory="Never" />
  </ItemGroup>
```

But it doesn't work, it's still publishing wwwroot\images and all it's content

**Comment by vijayrkn** [comment]
@max-favilli - Can you please share a repro project?

If you are publishing from VS, existing files are not deleted by default. You can check the option to 'Delete additional files' in the settings dialog.
