### ISSUE TITLE
web.config file has different content after dotnet publish command on different OS

### ISSUE THREAD

**Issue by mcctomsk** [dotnet/cli#5940]
Hi. For a long time I've been using TeamCity's build agent on Windows to build dotnet projects, but now I'm trying to get the same result with build agent on Linux and found difference which not allow run project on Windows Server with IIS.
Here is my project.json file:
```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Autofac": "4.0.0-rc2-240",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc2-240",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "Microsoft.AspNetCore.Localization": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "IdentityServer4.AccessTokenValidation": "1.0.2",
    "Microsoft.EntityFrameworkCore.Design": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore": "1.0.0",
    "WebApi.Base": "0.1.4",
    "Authorization": "0.1.8",
    "AutoMapper": "5.0.2"

  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "portable-net45+netcore45"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
        "wwwroot",
        "Views",
        "Areas/**/Views",
        "appsettings.json",
        "hosting.json",
        "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```
## Steps to reproduce
`dotnet publish project.json -c Release`
## Expected  behavior
Here is web.config made on Windows:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\WebApi.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
```
## Actual behavior
Here is web.config made on Linux:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>
```

## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

```
```
Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
```

**Comment by livarcocc** [comment]
Hi, we have moved the CLI from project.json to MSBuild and are no longer fixing bugs on the project.json version of the tooling.

Could you maybe pickup the latest CLI from here https://github.com/dotnet/cli/tree/rel/1.0.1 and trying this scenario out.

If you need to migrate your project from project.json to csproj, you can get more info here: https://github.com/dotnet/cli/blob/rel/1.0.1/Documentation/ProjectJsonToCSProj.md.

If this is also an issue in the msbuild version of the tools, please, re-activate this issue.

**Comment by johnkors** [comment]
Still an issue.

Use a web.config with:
```
<aspNetCore processPath="C:\Program Files\dotnet\dotnet" 
```
Call `dotnet publish`.

In the output web.config in the `/publish` folder:
```
 <aspNetCore processPath="dotnet"`
```
Overwritten.

**Comment by livarcocc** [comment]
@mlorbetske is this something that is happening in the Web.SDK?

**Comment by johnkors** [comment]
@dasMulli provided the useful hint of doing

```
<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
```

Also, as a sidenote. This property was until recent known as `IsWebConfigTransformDisabled`.

Not very easy to catch that subtle change from 
`IsWebConfigTransformDisabled` => `IsTransformWebConfigDisabled`

**Comment by mlorbetske** [comment]
cc @vijayrkn

**Comment by vijayrkn** [comment]
We changed the Property name to match the Task name. 
e.g: 
IsTransformWebConfigDisabled to disable transforming web.config
IsTransformAppSettingsDisabled to disable transforming appsettings
IsGenerateEFSQLScriptsDisabled to disable generating EF sql scripts (if EF Migration is enabled).

web.config transform not honoring the ProcessPath in web.config looks like a bug (https://github.com/dotnet/cli/issues/5940#issuecomment-285097731). Can you please create a bug in the web sdk repo for this - https://github.com/aspnet/websdk

**Comment by johnkors** [comment]
Looks like a dup of https://github.com/aspnet/websdk/issues/115 - doesn't it @vijayrkn ?

**Comment by vijayrkn** [comment]
@johnkors Yes, we can track this issue as part of aspnet/websdk#115.
