### ISSUE TITLE
RC3 Download Links page is a broken link

### ISSUE THREAD

**Issue by Ronan-Farrell** [dotnet/cli#5948]
## Steps to reproduce
Go to: https://github.com/dotnet/cli
Click "RC3 download links"

## Expected  behavior
Expect to find a page at: https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md

## Actual behavior
404, page not found

**Comment by blackdwarf** [comment]
@Ronan-Farrell we have shipped v1! 😄 Please go to https://dot.net/core. The link is being removed from the README.md file in #5928
