### ISSUE TITLE
dotnet test

### ISSUE THREAD

**Issue by RassulYunussov** [dotnet/cli#5949]
Interesting thing happening when I add xunit tests to my project.
When I start test using command: dotnet test within Visual Studio Code Terminal - everything goes ok. All tests run.
But when I run dotnet test from a terminal (without Visual Studio Code) I get error message that says that there is no test available.

## Steps to reproduce

dotnet test

## Expected  behavior
(within Visual Studio Code)
Build started, please wait...
Build completed.

Test run for /.../bin/Debug/netcoreapp1.1/SomeProject.Tests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
[xUnit.net 00:00:01.2838115]   Discovering: SomeProject.Tests
[xUnit.net 00:00:01.4470527]   Discovered:  SomeProject.Tests
[xUnit.net 00:00:01.5129059]   Starting:    SomeProject.Tests
[xUnit.net 00:00:01.7132244]   Finished:    SomeProject.Tests

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.7660 Seconds

## Actual behavior
(from terminal)
Build started, please wait...
Build completed.

Test run for /.../bin/Debug/netcoreapp1.1/SomeProject.Tests.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
No test is available in /.../bin/Debug/netcoreapp1.1/SomeProject.Tests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
Moved it to the vstest repo: https://github.com/Microsoft/vstest/issues/578.
