### ISSUE TITLE
Restore errors from the DTH no longer include the line and column number so are not squiggled in project.json

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#595]
_From @BillHiebert on November 12, 2015 18:25_

I verified that the same VS tooling running with Beta8 works fine. Looks like some recent change in DNX broke this feature.

_Updated by Troy_
We narrow down the scenario:
0. Set up a healthy project;
1. Change one reference's name so that the reference can't be resolved.
2. Save, VS restore the project, error message shows correct information.
3. Correct the reference's name. Without saving, change the version to an incorrect value.
4. Save, VS restore the project.
<Error> The dependency diagnostics message returned is not correct. Error locations are not set and message is wrong.

_Copied from original issue: aspnet/dnx#3161_

**Comment by muratg** [comment]
_From @davidfowl on November 12, 2015 18:26_

Nothing changed here AFAIK. Do you have a repro? 

/cc @troydai

**Comment by muratg** [comment]
_From @troydai on November 12, 2015 18:34_

I scanned through the places we created `DiagnosticMessage` and didn't find any obvious change. The format is still [there](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Extensions.PlatformAbstractions/DiagnosticMessage.cs#L19).

The one place that could change the outcome without our change is here: [DiagnosticExtensions](https://github.com/aspnet/dnx/blob/1bb5a1d24fcd7d21d2278528c243e2b9f181c43d/src/Microsoft.Dnx.Compilation.CSharp.Common/DiagnosticExtensions.cs#L25). But I don't think Bill's scenario go through this.

**Comment by muratg** [comment]
_From @davidfowl on November 12, 2015 18:37_

Yea sounds like a tooling issue. @BillHiebert can you paste the DTH response.

**Comment by muratg** [comment]
_From @BillHiebert on November 12, 2015 20:11_

  "Errors": [
    {
      "ErrorCode": "NU1001",
      "SourceFilePath": "C:\\Users\\billhie\\documents\\visual studio 2015\\Projects\\WebApplication1\\src\\WebApplication1\\project.json",
      "Message": "The dependency Microsoft.Extensions.Configuration.Json >= 1.0.0-rc1-final could not be resolved.",
      "Severity": 2,
      "StartLine": 0,
      "StartColumn": 0,
      "EndLine": 0,
      "EndColumn": 0,
      "FormattedMessage": "C:\\Users\\billhie\\documents\\visual studio 2015\\Projects\\WebApplication1\\src\\WebApplication1\\project.json(0,0): error NU1001: The dependency Microsoft.Extensions.Configuration.Json >= 1.0.0-rc1-final could not be resolved.",
      "Source": {
        "Name": "Microsoft.Extensions.Configuration.Json",
        "Version": "1.0.0-rc2-final"
      }
    }
  ],
  "Warnings": []
})

**Comment by muratg** [comment]
_From @troydai on November 12, 2015 20:46_

The error position is indeed in the formatted message.

**Comment by muratg** [comment]
_From @troydai on November 12, 2015 22:15_

Ah, I see what you mean. The value are not set correctly.

**Comment by muratg** [comment]
_From @troydai on November 12, 2015 22:16_

/cc @muratg

**Comment by muratg** [comment]
_From @BillHiebert on November 13, 2015 18:8_

Very unfortunate that the squiggle feature is broken in RC1. Obviously we need better test coverage to catch this sooner.

**Comment by muratg** [comment]
_From @troydai on November 13, 2015 18:45_

I can't repo this on the RC1 test build. Talked with @BillHiebert , he's now narrowing down his repo scenario.

**Comment by muratg** [comment]
_From @troydai on December 4, 2015 0:13_

@BillHiebert @muratg 
Do we still need to fix this in RC2?

**Comment by muratg** [comment]
Yes, let's decide if this is something we'll need to do in the new DTH.

**Comment by muratg** [comment]
_From @davidfowl on December 4, 2015 6:36_

in the new DTH it should be fixed

**Comment by muratg** [comment]
:+1:

**Comment by blackdwarf** [comment]
DTH has been deprecated.
