### ISSUE TITLE
Unable to find a project to restore

### ISSUE THREAD

**Issue by vikas0380** [dotnet/cli#5951]
## Steps to reproduce
dotnet new mvc  --framework netcoreapp1.1
dotnet new sln
dotnet restore

## Expected  behavior
pacakage restore complete

## Actual behavior
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): warning : Unable to find a project to restore! [/Users/vikas/Projects/coretestweb/coretestweb.sln]

## Environment data
`dotnet --info` output:
NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
running `dotnet new sln` does not automatically add projects to your solution file, it simply creates a new sln file.

You then need to run `dotnet sln add <path_to_csproj>'.
