### ISSUE TITLE
dotnet-install scripts for 1.0.0, some questions about args

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#5952]
So, i want to install the .net core tools 1.0 (now is 1.0.1), using the install script (because i have a build matrix to maintain 😄 )

dotnet-install script is really important and described in [docs too](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script)

https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/dotnet-install.ps1

some questions:

- is `https://github.com/dotnet/cli/blob/rel/1.0.0/scripts/obtain/` the right script?  also for `1.0.1`and future patch versions? think so, but just to be sure
- `channel` argument:
   - `production` is listed as value, but [doesnt exists](https://github.com/dotnet/cli/blob/4d66827e01792618bec7875a47adf2b0852576b7/scripts/obtain/dotnet-install.ps1#L204)
  - default in description [is preview](https://github.com/dotnet/cli/blob/4d66827e01792618bec7875a47adf2b0852576b7/scripts/obtain/dotnet-install.ps1#L13) but on args is [undocumented rel-1.0.0](https://github.com/dotnet/cli/blob/4d66827e01792618bec7875a47adf2b0852576b7/scripts/obtain/dotnet-install.ps1#L55), i can understand `1.0` as `1.0.x` (so all patch are ok), but current is `1.0.1`. using branch `1.0.1` default [is the same rel-1.0.0](https://github.com/dotnet/cli/blob/9b699691494d68f3dad5f1dce420f058047a7d90/scripts/obtain/dotnet-install.ps1#L55)
- `version`, docs say `if omitted, it will default to the first global.json file found in the hierarchy above the folder where the script was invoked that contains the version property`. i cannot reproduce it, and connot find code who does that.

To download `1.0.1` (current .net core tools 1.0), i tried to omit channel and use `1.0.1`. It download a zip https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.1/dotnet-dev-win-x64.1.0.1.zip . is ok anyway, with `-dev` ? it's not using `dotnet-1.1.1-sdk-win-x64.zip` like on [core download archive](https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md)
Having the same url help a lot, because i am sure it's the right version.

**Comment by livarcocc** [comment]
@blackdwarf Some of the things we were talking about that we need to clean up in the scripts.

**Comment by blackdwarf** [comment]
@enricosada some answers for you :)

* You should use the following location: https://dot.net/v1/dotnet-install.sh and https://dot.net/v1/dotnet-install.ps1 in the future. 
* In the above the production was added as an argument. We will merge the changes back into `master` at some point, but in general, the above location should be used to get the scripts for v1 tools.
* The above scripts have fixed this and other things as well. 
* Yeah, I need to remove that from the docs, it was an old behavior that we removed at some point.

**Comment by enricosada** [comment]
@blackdwarf awesome have a script url without raw github!

**Comment by livarcocc** [comment]
I believe this has been addressed. In any case, the scripts have changed quite a bit in 2.0, we have pushed them to the location above and their inline documentation is up-to-date. We are also working on updating the online documentation.
