### ISSUE TITLE
README for master still refers to RC3/4

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#5953]
This 
https://github.com/dotnet/cli/blob/master/README.md
talks about being in the process of moving to MSBuild based tools, and RC4. It has download links for RC3.

I assume we shipped? Where would I install final bits that have an MSbuild based CLI, and 1.1 SDK?

**Comment by livarcocc** [comment]
@blackdwarf does this https://github.com/dotnet/cli/pull/5928 address this issue?

**Comment by blackdwarf** [comment]
@livarcocc no, but it could. :) Let me push that change and link to this issue.

**Comment by blackdwarf** [comment]
This is now fixed. Closing.
