### ISSUE TITLE
dll reference support in .NET Core projects

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#5954]
@bartstinson commented on [Wed Mar 08 2017](https://github.com/dotnet/coreclr/issues/10035)

Hello, 

It's my understanding that prior VS 2017, it was impossible to add other .NET Core dll references to .NET Core projects without bundling the dependency in a NuGet package. In VS 2017, I see that the option to add dll references using the IDE but when I run it, the program fails to find the dependent dlls. Is the adding of dll references really now supported in VS 2017 for .NET Core projects or do we still have to go through NuGet?

Thanks

---

@danmosemsft commented on [Wed Mar 08 2017](https://github.com/dotnet/coreclr/issues/10035#issuecomment-285102880)

I'm not sure where this goes, but I"ll move it to CLI who can put it right.

**Comment by eerhardt** [comment]
This is fixed in .NET Core 2.0. It is not available in VS 2017 RTM, but will be in the next release. 

See https://github.com/dotnet/sdk/issues/120
