### ISSUE TITLE
Support globbing in global.json

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#596]
_From @ChengTian on February 19, 2015 22:11_

It's convenient to have
```json
{
    "sources": [
        "src",
        "submodules/*/src"
    ]
}
```
instead of
```json
{
    "sources": [
        "src",
        "submodules/FileSystem/src",
        "submodules/NuGet.Packaging/src",
        "submodules/NuGet.Versioning/src"
    ]
}
```

_Copied from original issue: aspnet/dnx#1248_

**Comment by muratg** [comment]
_From @ChengTian on February 19, 2015 22:20_

WARNING from @davidfowl : if not implemented properly, this globbing can hurt performance. Please remember to expand the pattern at most once in `ProjectResolver`.

**Comment by muratg** [comment]
_From @ChengTian on July 29, 2015 22:0_

Our `FileSystemGlobbing` package doesn't support globbing directories. Although we can implicitly append `/*/project.json`, this workaround leads to suboptimal performance that we want to avoid.

I filed an issue for adding directory globbing: https://github.com/aspnet/FileSystem/issues/118

**Comment by muratg** [comment]
_From @Eilon on August 14, 2015 20:1_

Moving this to the Backlog. We decided not to support this for the initial release. Will revisit in the future.

**Comment by blackdwarf** [comment]
Closing this as we are not going to support this moving forward.
