### ISSUE TITLE
DotNet EF does not load

### ISSUE THREAD

**Issue by spguruguy** [dotnet/cli#5962]
## Steps to reproduce
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
dotnet restore
dotnet ef add Initial
## Expected  behavior
successful installation

## Actual behavior
No executable found matching command "dotnet-ef"

## Environment data
`dotnet --info` output:
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

**Comment by livarcocc** [comment]
We are going to need a little bit more in order to be able to help you out.

First, can you share your csproj file? This seems like you are missing the EF tool in your csproj file.
Second, the dotnet --info output seems to be missing a lot of information about what version of the CLI you are using, your OS, etc.

**Comment by spguruguy** [comment]
I’m following the tutorial here: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model

Here is the csproj file:
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>

This is what I get when I run the dotnet ef commands:
[cid:image001.png@01D2982F.76473A30]

.NET Command Line Tools (1.0.0)

Product Information:
Version:            1.0.0
Commit SHA-1 hash:  e53429feb4

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.14393
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by spguruguy** [comment]
There doesn’t seem to be any mechanism to manually install the ef components of dotnet core. I did a manual install of the CLI SDK, and it doesn’t know about dotnet-ef either. Without any way to install this, the entire stack is seriously broken. I have no idea where to go from here…

**Comment by livarcocc** [comment]
@spguruguy sorry for the trouble.

Here is how tools work in the CLI today: we have this notion of project tools, which are portable applications package up as packages and added to your project as `DotNetCliToolReference`. So, when you restore a project that has a `DotNetCliToolReference` node in it. The tool gets downloaded and placed in your nuget cache.

After that, you can run dotnet ef (or other tool command available from your project) from your project directory and the CLI will find the tool from the `DotNetCliToolReference` in your project and in your nuget cache and execute it.

Today, that's the installation mechanism for tools in the CLI and it only works in the context of projects. So, you can't just run that tool from any folder and it will work, as they are not global tools (yet).

I just tried your project with 1.0.0 of the CLI and EF run. Can you please try again making sure that you are running both restore and ef from your project's folder?

If this is still a problem, please re-activate the issue.
