### ISSUE TITLE
Need to port #5525 to master

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#5964]
The PR #5525 didn't make its way into master. 

/cc @livarcocc

**Comment by livarcocc** [comment]
This PR is not missing in master.

@jonsequitur undid the changes to RunCommand that invoked the DisplayAsError extension method here: https://github.com/dotnet/cli/pull/5618.

@jonsequitur why did you make this change? Without the invoking to the extension method this makes dotnet run crash when a project is not found.

**Comment by livarcocc** [comment]
Though this will likely get fixed with the new parser.

**Comment by jonsequitur** [comment]
With the new parser changes, this appears to be working correctly. I see graceful errors and no crash when either zero or more than one project is found or specified.
