### ISSUE TITLE
Use Matcher to exclude files during bundling

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#597]
_From @troydai on February 14, 2015 5:59_

https://github.com/aspnet/XRE/blob/94add15fefff3484f2204bc977bd7373af5dd022/src/Microsoft.Framework.PackageManager/Bundle/BundleProject.cs#L264

There is logic in bundle to exclude specified files from final output. It looks like a proper candidate or matcher consumer.

_Copied from original issue: aspnet/dnx#1212_

**Comment by muratg** [comment]
_From @troydai on March 5, 2015 16:29_

@glennc @muratg need triage. I think we need this.

**Comment by muratg** [comment]
@ChengTian Would Matcher be applicable for this case?

**Comment by muratg** [comment]
Backlogging for now.  We can bring it back if there's interest and we can get resources to work on it.

**Comment by muratg** [comment]
_From @davidfowl on December 7, 2015 9:54_

@troydai Do we need this?

**Comment by ChengTian** [comment]
@muratg , yes, the idea is whenever we need pattern globbing, we should always use Matcher to do the work. The consistency ensures that users have a single set of rules to follow when they do file inclusion/exclusion for preprocessing/compilation/bundling.
