### ISSUE TITLE
launchsettings.json keeps getting modified

### ISSUE THREAD

**Issue by TravisBoatman** [dotnet/cli#5970]
If you remove the IIS Express profile or IIS settings in launchsettings.json, they will re-appear after you restart VS 2017. I'm not sure if this has to do with dotnet tooling or VS 2017.

## Steps to reproduce
Create a new web app.
Remove IIS Express profile and IIS settings from `luanchsettings.json`.
Add a new profile.
Should look something like this:

```
{
  "profiles": {
    "Kestrel": {
      "commandName": "Project",
      "commandLineArgs": "--environment \"Development\"",
      "launchUrl": "http://localhost:5000"
    }
  }
}
```
Save. Restart VS 2017.
File will now have IIS Profile and settings back in.

## Expected  behavior
Shouldn't be modified at all.

## Additional Notes
This also happened in VS 2015, however it would be modified as soon as you saved the file.

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by livarcocc** [comment]
@BillHiebert do you know anything about this? Also, is there a better repo for this bug? Given that it is exclusively in VS?

**Comment by livarcocc** [comment]
@vijayrkn is this something that you can help with?

**Comment by vijayrkn** [comment]
Similar issue: https://github.com/aspnet/websdk/issues/82

**Comment by livarcocc** [comment]
Closing this one in favor of the one in the websdk.
