### ISSUE TITLE
Downsize core app doesn't update dockerfile

### ISSUE THREAD

**Issue by Gentlehag** [dotnet/cli#5974]
## Steps to reproduce
Create a asp core 1.1 application with docker support
Then downsize the application to core 1.0
Start the docker container

## Expected  behavior
it should start the container as before

The docker file should be updated to target aspnetcore 1.0 (if untouched?) to

`FROM microsoft/aspnetcore:1.0` 

## Actual behavior
it doesn't start because the docker file still cotnains

`FROM microsoft/aspnetcore:1.1`

**Comment by livarcocc** [comment]
How did you downsize the TFM? Also, the CLI will not do that for you. It simply isn't in its capabilities today.

**Comment by Gentlehag** [comment]
Project references and changed the dropdown to 1.0 ;)

**Comment by livarcocc** [comment]
I see. That's an experience in VS, not in the CLI.

@MichaelSimons @BillHiebert do you know who owns this experience in VS?

**Comment by MichaelSimons** [comment]
This looks like it is part of the VS Docker Tooling experience - @dazhao-msft, @SteveLasker should be able to help.

**Comment by livarcocc** [comment]
@dazhao-msft @stevelasker is there a more appropriate repo to move this issue to?

**Comment by livarcocc** [comment]
ping @dazhao-msft @stevelasker @MichaelSimons

**Comment by dazhao-msft** [comment]
@Gentlehag, this is currently not supported by VS. We have it in our backlog. Thanks for the feedback.

**Comment by livarcocc** [comment]
Given that this is a VS experience and is being tracked in VS already. I am closing the issue here.
