### ISSUE TITLE
Error MSB4062

### ISSUE THREAD

**Issue by vadimkhm** [dotnet/cli#5976]
## Steps to reproduce
I have a lot old library projects(4.5.1) that builds correctly with new web site project.
But one project that using some web references cannot be build from dotnet build with different configurations.
For example dotnet build --configuration Debug normally executed but 
 dotnet build --configuration Staging gives following error:
Can someone help with this?
Thanks

## Actual behavior
C:\Program Files\dotnet\sdk\1.0.0\Microsoft.Common.CurrentVersion.targets(3344,5): error MSB4062: The "Microsoft.Build.Tasks.SGen" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\ep\ServiceLayer\ServiceLayer.csproj]

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by vadimkhm** [comment]
there is some wrong references to web services and that was a problem

**Comment by danielwcr** [comment]
Hi @vadimkhm what do you mean by wrong references? I have got similar issue here and still unsure about the cause

**Comment by vadimkhm** [comment]
Hi Daniel, in my case in project file I had some web service references
that pointed in paths that not presented. So that was a problem after
removing that refs everything now working.

Best,
Vadim

**Comment by danielwcr** [comment]
Hi Vadim,

Thanks for replying. In my case I have a project with reference to
Reporting Services in localhost -> http://localhost/ReportServer/
ReportExecution2005.asmx, and I am trying to set up an automatic build on
VSTS.

That address points to nowhere when running in the VSTS Build machine, but
I don't have this web service public and if I change the build
configuration to debug, it works. So no clue what is going on.

Regards,
Daniel

**Comment by Frosthage** [comment]
This might not be exactly related to this issue, but I bumped into the same error when I try to reference an old vb .net project. Building for debug configuration worked, but the same error occurred when building release configuration.

I managed to solve my error by changing the GenerateSerializationAssemblies element for the release configuration from auto to off. Maybe not the best solution but at least my code compiles.

`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <Optimize>false</Optimize>
    <OutputPath>bin\</OutputPath>
    <DocumentationFile>
    </DocumentationFile>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022,42353,42354,42355</NoWarn>
    <DefineConstants>Win32=True</DefineConstants>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    **<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>**
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>`
