### ISSUE TITLE
DTH leaks a thread when clients disconnect

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#598]
_From @jrieken on January 29, 2015 12:54_

@davidfowl - as discussed and exposed by Omnisharp

_Copied from original issue: aspnet/dnx#1148_

**Comment by muratg** [comment]
@troydai please sync-up on @davidfowl if you're not up to date on the leak. We can move this to beta 7 as well.

**Comment by muratg** [comment]
_From @troydai on September 8, 2015 18:45_

@muratg talked to @davidfowl just now, let's move this out of beta8 for now.

**Comment by muratg** [comment]
_From @troydai on October 6, 2015 22:47_

Hi @jrieken , it has been 9 months since this this issue was filed. Do you still repo this issue? If you haven't tried out this issue recently, can you let me know how you repo and detected this issue?

**Comment by muratg** [comment]
_From @jrieken on October 7, 2015 7:44_

You can reproduce this when using OmniSharp and DTH. There is [code in OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp/Dnx/DesignTimeHostManager.cs#L95) that tries to connect to DTH in short intervals such that [this message](https://github.com/aspnet/dnx/blob/6e6d83951a8d80dc43c82140e3cace69b0bc399d/src/Microsoft.Dnx.DesignTimeHost/Program.cs#L84) is printed twice.

<img width="421" alt="screen shot 2015-10-07 at 09 44 27" src="https://cloud.githubusercontent.com/assets/1794099/10331744/0658807c-6cd8-11e5-97a4-115e0cacfc16.png">

**Comment by muratg** [comment]
_From @troydai on October 7, 2015 16:48_

Thanks @jrieken. I'll look into this.

**Comment by blackdwarf** [comment]
DTH is deprecated, we have ProjectModel.Server. Closing this.
