### ISSUE TITLE
Dependencies via project reference are not having versions updated when performing a dotnet pack

### ISSUE THREAD

**Issue by KallDrexx** [dotnet/cli#5984]
## Steps to reproduce
1. Go to a directory
2. `mkdir test1`
3. `mkdir test2`
4. `cd test1`
5. `dotnet new classlib`
6. Edit test1.csproj and add `<VersionPrefix>1.0.1</VersionPrefix>`
7. `dotnet restore` then `dotnet pack`
8. `cd ../test2`
9. `dotnet new classlib`
10. `vim Class1.cs`
11. Change class definition to `public class Class1 : test1.Class1`
12. Edit test2.csproj and add `<VersionPrefix>1.0.0</VersionPrefix>`
13. Edit test2.csproj and add:
```
  <ItemGroup>
    <ProjectReference Include="../test1/test1.csproj" />
  </ItemGroup>
```
14. `dotnet restore` then `dotnet pack`
15. Edit test1.csproj and change version to `1.0.2`, then build and repack it
16. go back to `test2` folder and update the version to `1.0.1`
17. In test2 folder do `dotnet restore` then `dotnet pack`
18. Extract the test2.1.0.1.nupkg
19. View the `.nuspec` file

## Expected  behavior

Dependency should be listed as:
`<dependency id="test1" version="1.0.2" exclude="Build,Analyzers" />` so that any nuget package built against the `test2` library auto-restore test1 to `1.0.2`

## Actual behavior

Dependency is outdated and listed as 

`<dependency id="test1" version="1.0.1" exclude="Build,Analyzers" />`

This is impacting us heavily right now as any time we build a nuget package it has outdated dependencies, which when restored on other projects causes `FileLoadExceptions` due to `dotnet restore` restoring an older dll.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by livarcocc** [comment]
Moved this to nuget/home: https://github.com/NuGet/Home/issues/4779.
