### ISSUE TITLE
dotnet restore does not respect verbosity

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#5989]
`dotnet restore -v q` does not respect the quiet flag.

However, `dotnet msbuild /t:restore /v:q` works fine. 

@livarcocc @emgarten

**Comment by blackdwarf** [comment]
This is true. We need to create a mapping between the restore level of verbosity and MSBuild ones.

**Comment by cdmihai** [comment]
Moreover, if I do dotnet restore -v diagnostic I'd like only restore specific output to show, not the rest of msbuild's diagnostic output :)
