### ISSUE TITLE
Framework Dependent ASP.net Core site on Nano Server Process Failure

### ISSUE THREAD

**Issue by dansta2k** [dotnet/cli#5991]
## Steps to reproduce
https://docs.microsoft.com/en-us/aspnet/core/tutorials/nano-server

Following this tutorial does not add dotnet.exe to the PATH environment variable, so I manually did this and pointed it to C:\Users\[user]\Local Settings\Microsoft\dotnet\shared\Microsoft.NETCore.App\1.1.1 

The site runs fine directly when using dotnet appname.dll, but the site does not run through IIS, this is where i see the 502.5 Process error when i try to browse the page.

When deploying the project as an SCD it works fine through IIS

## Expected  behavior
Asp.net Core 1.1 site loads successfully

## Actual behavior
502.5 Process Error with no logs
Using server manager I see errors but with no details other than it pertaining to: IIS AspNetCore Module 

## Environment data
`dotnet --info` output:   -returns nothing, no error, however
dotnet output:
Microsoft .NET Core Shared Framework Host
  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86

cc/ @guardrex

**Comment by GuardRex** [comment]
@robmen This looked to me like something went wrong during the shared framework/runtime installer on Nano. @dansta2k was able to get an SCD app running, so it wasn't a prob with the ANCM/IIS. IIRC there was no stdout log file created. There were ANCM entries in the Application Log, but they had no messages attached to them (or no obvious messages anyway).

@dansta2k, @robmen might want to see the installer log from the Nano. They might be in `C:\Users\<USER>\AppData\Local\Temp` with obvious naming, like `.NET_Core_SDK_1.0.0_(x64)_Installer_(x64)_20170305125123`. You can Gist the log and then put the Gist link over here on the issue.

**Comment by dansta2k** [comment]
@GuardRex unfortunately when i list the contents of that directory it shows:

    Directory: C:\users\adminVM\AppData\Local\Temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         3/7/2017   6:27 AM                Microsoft.PackageManagement


The Microsoft.PackageManagement subfolder is empty :(

**Comment by GuardRex** [comment]
@dansta2k Not sure ... maybe the log goes somewhere else on Nano.

@robmen can help. He's the 🤴 *Installer King!* 🤴

**Comment by livarcocc** [comment]
Also, you should set your path to C:\Users[user]\Local Settings\Microsoft\dotnet. That's where the dotnet.exe lives.

**Comment by livarcocc** [comment]
Since we haven't heard back on this issue in a while. I am closing it. If this is still a problem, please re-activate.
