### ISSUE TITLE
dotnet add package doesn't honor package type

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#5998]
## Steps to reproduce
1. `dotnet add package Microsoft.EntityFrameworkCore.Tools.DotNet`

## Expected  behavior
```XML
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
```

## Actual behavior
```XML
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
```

## Environment data
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by bricelam** [comment]
This issue is similar to NuGet/Home#4190

**Comment by bricelam** [comment]
## Workaround
Manually add the appropriate `<DotNetCliToolReference>` to your `*.csproj`

**Comment by livarcocc** [comment]
Yes, this needs to be handled in NuGet as the command in the CLI is just a shim. We know this is a missing functionality though.

Let's track it in the NuGet issue.

**Comment by isaac2004** [comment]
This workaround does not work with .Net Standard. If you put the preview version of the tools in .csproj you still get the error message

`
Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0-preview1-final is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.EntityFrameworkCore.Tools.DotNet 2.0.0-preview1-final supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)				


`
