### ISSUE TITLE
Figure out servicing index location on non windows machines

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#600]
_From @davidfowl on December 6, 2014 19:59_

/cc @lodejard @glennc

_Copied from original issue: aspnet/dnx#975_

**Comment by glennc** [comment]
Not sure if there are other issues to talk about the breadcrumb location. But we need to think about permissions on that as well. It has very specific ACLs on Windows and I don't know what the equivalent is on Linux or OS X.

**Comment by blackdwarf** [comment]
We have figured this out for RC2. Closing.
