### ISSUE TITLE
dotnet migrate fails for UWP blank app

### ISSUE THREAD

**Issue by nmklotas** [dotnet/cli#6001]
## Steps to reproduce
Create any Blank UWP app project and run dotnet migrate.

## Expected  behavior
app is migrated

## Actual behavior
app is not fully migrated, csproj looks messed up. When building the app I get errors:

```Severity	Code	Description	Project	File	Line	Suppression State
Error		Cannot infer TargetFrameworkIdentifier and/or TargetFrameworkVersion from TargetFramework='uap10.0'. They must be specified explicitly.	App5	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	84
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v10.0" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	App5	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1111
```	

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by livarcocc** [comment]
The dotnet migrate command is not supposed to handle UWP. It handles only .NET Core projects.

cc @rohit21agrawal who may have something to help out with that.

**Comment by rohit21agrawal** [comment]
@nmklotas support for migrating UWP projects is coming very soon to Visual Studio in the next update.

**Comment by pellea** [comment]
@rohit21agrawal which next version? This is still not supported with dotnet 2.0.0-preview1-005977.

Is there a way to migrate UWP project not manually?

**Comment by rrelyea** [comment]
To clarify @rohit21agrawal's statement -- migrating a UWP/Project.json project to use PackageReferences inside of csproj was coming soon into VS 2017 15.2 (already available when you retarget TPMV to RS2 or later) -- there is no migration of UWP projects to use NetCore SDK projects planned.

**Comment by scott-stoltz** [comment]
rrelyea, what's the process for updating a UWP/project.json?

**Comment by rohit21agrawal** [comment]
if you open your project.json based UWP project in Visual Studio, and change the TPMinV or TPV to 15063 (RS2) or higher, the migration will happen automatically.
