### ISSUE TITLE
dotnet test does not pass additional arguments to xunit

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#6002]
# Steps - 

`dotnet test -- notrait="platform=darwin"`

# Expected - 

`notrait="platform=darwin"` should be passed to xunit.

# Actual - 

`dotnet test` does not seem to be sending this to xunit.

**Comment by livarcocc** [comment]
Please, move this to the microsoft/vstest repo.

**Comment by mishra14** [comment]
ported: https://github.com/Microsoft/vstest/issues/599
