### ISSUE TITLE
dotnet publish is not able to find framework version even though it exists

### ISSUE THREAD

**Issue by alaatm** [dotnet/cli#6013]
## Steps to reproduce
Having the following folders in the system:
C:\Program Files\dotnet
C:\dotnet-sdk

C:\Program Files\dotnet\shared\Microsoft.NETCore.App has the following framework versions:
1.0.1
1.1.0

C:\dotnet-sdk\shared\Microsoft.NETCore.App has the following framework versions:
1.0.4
1.1.1

C:\Program Files\dotnet is on the PATH variable where C:\dotnet-sdk is not.

Create a new project then execute the following:
C:\dotnet-sdk\dotnet restore
C:\dotnet-sdk\dotnet publish

## Expected  behavior

Project is published

## Actual behavior

Restore succeeds but publish fails with the following error:

    The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.

      - Check application dependencies and target a framework version installed at:

          C:\Program Files\dotnet\shared\Microsoft.NETCore.App

      - The following versions are installed:

          1.0.1

          1.1.0

How do I make it use C:\dotnet-sdk instead of C:\Program Files\dotnet ?

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
I feel like there is something else going here. The usage of the CLI that you describe above is exactly how we use the CLI for it to build itself in a daily basis.

How did you populate these directories? What is their content?

I just tried the scenario as you described and it worked for me.

**Comment by alaatm** [comment]
Hmm.. this is weird. I am using Visual Studio Team Services.

The directory in Program Files is already there on the machine.
I download the c:\dotnet-sdk directory using:
dotnet-install.ps1 -version "1.0.0" -installDir C:\dotnet-sdk

and all my dotnet commands are run as C:\dotnet-sdk\dotnet

**Comment by livarcocc** [comment]
@gkhanna79 Why is the host looking at the location in the PATH to find the shared runtime instead of looking next to it? Any ideas?

**Comment by gkhanna79** [comment]
Which version do you see this issue with @livarcocc ?

CC @eerhardt @ramarag

**Comment by gkhanna79** [comment]
Host is not looking at the path - c:\PF\dotnet is the default install location for the installer where dotnet.exe is placed on the path. Thus, when dotnet is invoked and _OS_ invokes c:\pf\dotnet\dotnet.exe, then it looks up the SharedFX next to it, as expected, and how it has happened since Day1.

**Comment by livarcocc** [comment]
Look above.

The user is invoking dotnet by doing `C:\dotnet-sdk\dotnet publish`. This folder contains both 1.0.4 and 1.1.1 installed.

However, that command is failing saying that 1.1.1 is not installed and that instead only 1.0.1 and 1.1.0 are installed, which are the ones under C:\Program files.

Given that the host used is under c:\dotnet-sdk, shouldn't it use the shared framework next to it?

**Comment by gkhanna79** [comment]
> Given that the host used is under c:\dotnet-sdk, shouldn't it use the shared framework next to it?

It will. Are we sure (validated under debugger or procmon) that c:\dotnet-sdk\dotnet.exe was invoked and not the one in c:\pf\dotnet\?

**Comment by gkhanna79** [comment]
@alaatm Can you set COREHOST_TRACE=1 and rerun the command and share the trace that comes out?

**Comment by alaatm** [comment]
@gkhanna79 trace is available here: https://gist.github.com/alaatm/a2dc37fb34819dc4c005ecaf5c2201eb

**Comment by livarcocc** [comment]
Do you have anything special in your csproj? From the traces above, I didn't really see it going to c:\Program Files for the shared runtimes.

I wonder if you have any targets in your project that invokes another dotnet inside of it. Because if you do, that one will happen using the dotnet in the path and not the one you used to invoke the publish in the first place.

**Comment by gkhanna79** [comment]
According to the trace, we are picking up SharedFX from 1.1.1 - see https://gist.github.com/alaatm/a2dc37fb34819dc4c005ecaf5c2201eb#file-gistfile1-txt-L104.

**Comment by gkhanna79** [comment]
I concur with @livarcocc that the error is coming out of a different process. Can you please set COREHOST_TRACE for the machine and then capture the trace out? Or, use ProcMon to determine who is failing?

**Comment by livarcocc** [comment]
Closing this issue for now since we haven't had a reply on it for close to 30 days now. Please, re-activate when you can provide the additional info request above.
