### ISSUE TITLE
dotnet restore places packages in default cache dir but VS2017 does not

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/cli#6022]
## Steps to reproduce
Visual Studio 2017 opening solution with .NET Core project in it.

## Expected  behavior
Visual Studio 2017 should place packages of .NET Core projects inside the default nuget cache directory as "dotnet restore" dotnet-cli does. Reference: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-restore

## Actual behavior
Nuget packages get placed under "$project$/packages" directory.   

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15055
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
@rrelyea @emgarten can you guys take a look? Any idea why this would be happening?

**Comment by emgarten** [comment]
@ViktorHofer can you share the .csproj of the netcore project and the obj\project.assets.json file?

**Comment by ViktorHofer** [comment]
Even better, I created a little sample project which shows what I experienced: https://github.com/ViktorHofer/vs17-package-test

What I noticed in my test solution:

1. Creating a netcore app and adding a nuget package --> no solution package dir created
2. Creating a netstandard app, adding another nuget package and referencing the netstandard app from the netcore app --> no solution package dir created.
3. Creating a UWP app, adding another nuget package and referencing the netstandard app from the UWP app --> no solution package dir created?!?
4. Creating a WPF app, adding another nuget package and referencing the netstandard app from the WPF app --> solution package dir created!

So I guessed that both UWP and WPF will create a local solution package dir as they both use the old csproj format and the local msbuild? I wasn't sure if this is a bug or an expected behavior right now till V16...

**Comment by emgarten** [comment]
packages.config based projects still use the solution directory, this is expected.

UWP project.json will use the same global packages folder as netcore projects.

Note that dotnet CLI only supports NETCore projects. It does not support UWP project.json or packages.config projects.

**Comment by ViktorHofer** [comment]
Alright that makes sense! Thanks for pointing out. I will close this as it is not an issue.
