### ISSUE TITLE
Pushing out updates to https://dot.net/v1/dotnet-install.sh 

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#6023]
I made a change to the `dotnet-install.sh` script in master: https://github.com/dotnet/cli/commit/3fde06faf84161cf8b6d09a0be0ad16e059ec52d. What's the best way to get this changed pushed to the release branches and https://dot.net/v1/dotnet-install.sh?

It's a trivial change that doesn't affect existing operating systems but adds support for additional ones that are known to be backwards compatible.

Without this change, other projects, such as as netcorecli-fsc (see https://github.com/dotnet/netcorecli-fsc/pull/90) regress on support for some operating systems. And with various changes coming down to the version of the script in the master branch, it seems like the version in master may not be safe to use for all cases.

**Comment by omajid** [comment]
cc @ellismg @tmds

**Comment by livarcocc** [comment]
@blackdwarf can you help @omajid.

We should talk about solving this problem in general.

**Comment by tmds** [comment]
@livarcocc @blackdwarf This change is needed to automatically pick up the rhel install. Next to that, would it be possible to add a parameter to the script to specify the rid you want to install? This would bypass the /etc/os-release readout and make it possible to install runtimes which are not the default and runtimes not known to the script.

e.g. install portable linux:
```
./dotnet-install.sh --rid linux
```

**Comment by omajid** [comment]
@tmds I implemented your suggestion as https://github.com/dotnet/cli/pull/6037

**Comment by blackdwarf** [comment]
We will have to figure this out. Currently, the upload is a manual process so once @omajid PR is in, we need to get it to the dot.net location.

**Comment by omajid** [comment]
@blackdwarf What's the process to get both of https://github.com/dotnet/cli/commit/3fde06faf84161cf8b6d09a0be0ad16e059ec52d and https://github.com/dotnet/cli/commit/46a1d6f41ed12eba8703057b4b8f0c5e28628c99 backported and pushed to the `rel/1.0.0` branch as well as https://dot.net/v1/dotnet-install.sh? Should I open a separate PR against `rel/1.0.0` and the sync is done later?

**Comment by blackdwarf** [comment]
@omajid it is manual at this point. Once these are in I or @livarcocc will add the deltas and get the location updated. Are the PRs merged?

**Comment by omajid** [comment]
Ping. Anyone know what the next steps are? Should I open PRs against release branches?

**Comment by livarcocc** [comment]
I will take care of it.

**Comment by omajid** [comment]
Thanks!

**Comment by omajid** [comment]
Hey, any ETA on updating https://dot.net/v1/dotnet-install.sh? https://www.microsoft.com/net/download/linux still points to this script.

**Comment by livarcocc** [comment]
Done. @omajid so very sorry for the long time. Entirely my bad. I pushed it now, though I am not sure exactly how long it takes for it to light up.
