### ISSUE TITLE
`dotnet pack` takes dependency on package version 1.0.0 of a project dependency regardless of --version-suffix or <VersionSuffix>

### ISSUE THREAD

**Issue by ericwj** [dotnet/cli#6025]
I have two projects in my solution which I want to `dotnet pack --version-suffix alphaXYZ` and push to a CI package source. That works. I get two packages in my feed with version 1.0.0-alphaXYZ.

However, I find that the package made from the project with a project reference to the other project will list version `1.0.0` in the package manifest, so after pushing and trying to take dependency on the CI package, installing the package will fail:

```
Installing Package 1.0.0-alphaXYZ .
Unable to resolve 'Package.Abstractions (>= 1.0.0)' for '.NETStandard,Version=v1.6.1'.
Package restore failed. Rolling back package changes for 'Project'.
```

Opening the package with 7-zip, the root folder contains `Package.nuspec` with the following content:
```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Package</id>
    <version>1.0.0-alphaXYZ</version>
    <authors>Package</authors>
    <owners>Package</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETStandard1.6.1">
        <dependency id="Package.Abstractions" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

The exact same happens if I put `<VersionSuffix>alphaXYZ</VersionSuffix>` in the project file for both projects.

I found this 4-year old question [StackOverflow: Creating NuGet package with project referencies](http://stackoverflow.com/questions/13389597/creating-nuget-package-with-project-referencies) which mentions this work item [CodePlex: Provide option in Nuget pack command to add project dependencies as "dependents"](http://nuget.codeplex.com/workitem/2825).

Is that answer still valid? If so, are there plans to fix this? If not, what else is recommended to work around this?

**Comment by xqrzd** [comment]
I had a similar issue, the workaround [NuGet/Home#4337](https://github.com/NuGet/Home/issues/4337) worked for me.

**Comment by livarcocc** [comment]
Closing in favor of the NuGet issue. Where this actually needs to be fixed.
