### ISSUE TITLE
CLI build should not rely on Dockerfile within the repository

### ISSUE THREAD

**Issue by ravimeda** [dotnet/cli#6026]
## Steps to reproduce

Perform an official build.

## Expected  behavior
Rather than consuming (or maintaining) a Dockerfile within a repository, it is more efficient to specify the image name required through PB_DockerImageName variable in a build task, and let PipeBuild pull the appropriate image on behalf of the build.  Investigate the possibility of reusing the shared images in `microsoft/dotnet-buildtools-prereqs`.

Given the scope of this change, do not consider this for existing servicing branches.

## Actual behavior
Builds relies on Dockerfiles located within the repository at `/cli/tree/master/scripts/docker`

**Comment by ravimeda** [comment]
Corresponding issue for core-setup is https://github.com/dotnet/core-setup/issues/1719

**Comment by livarcocc** [comment]
Will this work even if we don't use pipebuild?

**Comment by livarcocc** [comment]
Also, why shouldn't we have these images in the repo? We have had it so for close to 2 years now. What are the drawbacks from it? And the benefits to using the images from pipebuild?

**Comment by livarcocc** [comment]
@ravimeda Is this something that you guys can make a PR for? Or point me to a similar PR on another repo? Like core-setup?

**Comment by MichaelSimons** [comment]
I think the same changes made to https://github.com/dotnet/core-setup/issues/1719 can be copied into CLI.

**Comment by livarcocc** [comment]
That issue is referring to the PR that moved core-setup to a new build it seems. It is not helpful at all, as it is hard to discern exactly what change we need to port.

**Comment by livarcocc** [comment]
I am closing this issue. @ravimeda, please, re-activate when you are ready to make a PR.
