### ISSUE TITLE
dotnet test produces console output that is not in sync with the test execution

### ISSUE THREAD

**Issue by ChristophB125** [dotnet/cli#6031]
## Steps to reproduce
Have e.g. 3 MsTest tests that write to the Console for logging purposes, which is sometimes essential for understanding failures on build machines. The 2nd test fails and later on we want to see the test log of this test.
[TestMethod]
public void TestMethod1()
{
    Console.WriteLine("TestMethod1");
}
[TestMethod]
public void TestMethod2()
{
    Console.WriteLine("TestMethod2");
    Assert.Fail();
}
[TestMethod]
public void TestMethod3()
{
    Console.WriteLine("TestMethod3");
}

## Expected  behavior
I expect to see the log from the failing test 'TestMethod2' together with its failure in the log so that I know they belong together to enable me understand the failure better and make use of the logging to the Console. It should look as follows (ideally, dotnet test should also log successful tests)
TestMethod1
Passed UnitTestProject3.UnitTest1.TestMethod1
TestMethod2
Failed   UnitTestProject3.UnitTest1.TestMethod2
Error Message:
 Assert.Fail failed.
Stack Trace:
   at UnitTestProject3.UnitTest1.TestMethod2() in E:\VSProjects\UnitTestProject3\UnitTestProject3\UnitTest1.cs:line 19
TestMethod3
Passed UnitTestProject3.UnitTest1.TestMethod3

## Actual behavior
All the logs are at the top and in a more realistic scenario I would not be able to tell what the log output of the failing test was:
TestMethod1
TestMethod2
TestMethod3
Failed   UnitTestProject3.UnitTest1.TestMethod2
Error Message:
 Assert.Fail failed.
Stack Trace:
   at UnitTestProject3.UnitTest1.TestMethod2() in E:\VSProjects\UnitTestProject3\UnitTestProject3\UnitTest1.cs:line 19

## Environment data
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by livarcocc** [comment]
Moved over to microsoft/vstest repo.
