### ISSUE TITLE
Dotnet CLI tool fails to build a solution that VS2017 has no problems building.

### ISSUE THREAD

**Issue by AnkHansen** [dotnet/cli#6032]
## Steps to reproduce
As my solution is a bit complex, it's hard to outline exact steps to reproduce. 

I have a solution outlined as below - my real solution has more projects, but I think the small graph is enough to discuss from. 

MySolution.sln
- FoundationClasses (x86, .Net Framework 4.5, csproj (legacy)
- BusinessLogic (x86, .Net Framework 4.5, csproj (legcay)
  - References foundation classes
- WebApi (Dotnet Core WebApi, net452, x86 (runtimes (win8-x86, win10-x86)
  - References BusinessLogic (and thus indirectly FoundationClasses)
- TestProject (Dotnet Core, net452, x86)
  - References WebApi

Visual Studio 2017 builds this fine - everytime.

'dotnet msbuild MySolution.sln' fails though. For me it seems a bit random. 
'dotnet build MySolution.sln' has same errors. 
'dotnet test' only works with --no-build - or it will fail with the same errors. 

## Expected  behavior
I would expect that when code is working, and VS 2017 can build the solution, then I am also able to build it using the Dotnet CLI tools - and thus get my CI setup working. 
I managed to get it working using Preview2 release - but that wasn't easy. 
The tool chain now seems much more mature, and most of it works as it should/expect. 

## Actual behavior
Sometimes it works (I suspect it to be when I have build/run something in Visual Studio - and run dotnet msbuild from PowerShell, but cannot consistently reproduce)
Most of the times it doesn't work and fails with one of two types of errors. 

Something about resources and postive number
`C:\Program Files (x86)\dotnet\sdk\1.0.1\Microsoft.Common.CurrentVersion.targets(2865,5): error MSB3554: Cannot write to the output file "D:\code\mySolution\FoundationClasses\obj\x86\Debug\FoundationClasses.SQLFixUpdateCriticalComponentHistory.resources". Positive number required.\r [D:\code\MySolution\FoundationClasses\FoundationClasses.csproj]`

Or someting about LC task in Common.CurrentVersion.targets cannot be found. 

```
C:\Program Files (x86)\dotnet\sdk\1.0.1\Microsoft.Common.CurrentVersion.targets(2975,5): error MSB4062: The "Microsoft.Build.Tasks.LC" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [D:\code\mySolution\BusinessLogic\BusinessLogic.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'D:\code\MySolution\FoundationClasses\FoundationClasses.csproj'. This can indicate a missing project reference. [D:\code\MySolution\Web\src\WebApi\WebApi.csproj]
```

I would suspect that something about my environment, or the way I call the CLI tools is wrong - since VS 2017 consistently builds this solution. 

But I can't figure it out. 

## Environment data
I need to build for x86, as my legacy classes contains references to some x86 libraries - just for a few months more (hopefully). 
I also have SDK for 1.0.0-preview2-003131 installed. 
Both SDKs are installed as x86 and x64 (the Dotnet folder in Program files(x86) is first in path - in the preview days this was necessary to build for x86 - don't know if it is still a requirement)
I have Visual Studio 2015 Pro and Visual Studio 2017 Pro installed. 

`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\1.0.1`

If any more information is needed please let me know. 

I hope you can help figuring this out, as it really seems the final release and VS 2017 is a great step in the right direction. 

Best regards
/Anders

Small observation on my further quest..
The legacy projects is also part of an legacy solution, e.g. oldSolution.sln. 
If I run 
`msbuild oldSolution.sln /p:Platform=x86 /p:Configuration=Debug /t:Rebuild`
first, and then 
`dotnet msbuild mySolution.sln  /p:Platform=x86 /p:Configuration=Debug /t:Rebuild /p:RuntimeIdentifiers=win10-x86`
afterwards, 
First time it fails with the Positive number required in one project first time. (FoundationClasses)
Second time it fails with the Positive number required error in another project (BusinessLogic)
And third time and forward it faild with the "LC Task" error. 

If I run `dotnet msbuild` with rebuild target - it fails on first Foundation class project. 

New findings about the LC error. 
I have a dll in C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Build.Tasks.Core.dll, v. 15.1.0.0 (Fileversion 15.1.548.43366) 
and another in C:\Program Files (x86)\dotnet\sdk\1.0.1\Microsoft.Build.Tasks.Core.dll, also v 15.1.0.0 (Fileversion 15.1.548.43366)
The latter (dotnet) has targetFramework ".NetStandard, Version=v1.3" where the other has ".NetFramework,Version=v4.6". 
The dotnet version does not have the Microsoft.Build.Tasks.LC class - but the one for .Net v. 4.6 does. 

This could hint that I am missing out on telling msbuild that I build for net452.

**Comment by AnkHansen** [comment]
And... All this writing with myself let me to the conclusion, which I will keep here for reference. 

The issue was that VS2017 uses another build chain (I suspect) than dotnet msbuild does. 

Where VS 2017 uses the msbuild.exe that comes with Visual Studio 2017, dotnet msbuild uses assemblies in C:\Program Files (x86)\dotnet\sdk\1.0.1. 

The final solution (which for now seems to be stable is)

- find location of Visual Studio 2017 (use https://www.nuget.org/packages/vswhere/) for that
- call msbuild in that location on mySolution.sln 

All is happy...

My PSake build step then becomes

`Task BuildApi {
    exec { msbuild ./oldSolution.sln /t:Rebuild /p:Configuration="Release" /p:Platform=x86 /m /verbosity:minimal /nr:false }

    exec { dotnet restore .\mySolution.sln }

    #Find location of VS2017
    $VsPath = .\packages\vswhere.1.0.50\tools\vswhere.exe -latest -property installationPath
    $msBuild17 = "$vsPath\MSBuild\15.0\Bin\MSBuild.exe"

    exec { &$msbuild17 ./mySolution.sln /t:Build /p:Configuration=Release /p:Platform=x86 /m /verbosity:minimal /nr:false }
}`

And I can then run dotnet test on my test projects with --no-build to test the solution.

**Comment by mronnlun** [comment]
For me this was caused by an emtpy resource file.
[http://stackoverflow.com/questions/43233651/vsts-build-for-asp-net-core-solution-fails-with-error-msb3554-cannot-write-to-t]()

**Comment by Metamorphus** [comment]
My *.resx files are not empty, but I still get the same errors.

**Comment by felyperennan** [comment]
I'm looking for a issue to my case, this is not my case though.
I'm going through something a bit similar, I run:
dotnet build -o ..\dist
and it build ok, half of the times. The other half it gives me assembly missing runtime exceptions :\
