### ISSUE TITLE
What's the scheme for SDK urls?

### ISSUE THREAD

**Issue by omajid** [dotnet/cli#6036]
I am trying to modify the `dotnet-install.sh` script. One thing that's hard coded in there is the mapping from RID (computed from `/etc/os-release`) to package names (on https://dotnetcli.azureedge.net/dotnet/Sdk/). Currently that's not a problem, but if we let users provide RIDs as arguments (as suggested as one fix for (https://github.com/dotnet/cli/issues/6023), then we have to redo the mapping between RID and download names within the script.

For example:
- https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004915/dotnet-dev-ubuntu.16.04-x64.1.0.0-rc4-004915.tar.gz which includes the RID `ubuntu.16.04-x64` works
- https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004915/dotnet-dev-rhel.7.2-x64.1.0.0-rc4-004915.tar.gz which includees the RID `rhel.7.2-x64` doesn't work
- https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004915/dotnet-dev-rhel.7-x64.1.0.0-rc4-004915.tar.gz which includees the RID `rhel.7-x64` doesn't work
- https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004915/dotnet-dev-rhel-x64.1.0.0-rc4-004915.tar.gz which includes an RID (without a concrete implementation) `rhel-x64` works

Would it be possible to include the exact RID for each package in the actual package name for the sdk downloads?

**Comment by livarcocc** [comment]
Can't you do the reverse mapping in this case?

We intend to use the RIDs for any new Distro we add, however, we have no plans to change the existing ones right.

Would the reverse mapping work for you? If so, I would like to close this.

**Comment by omajid** [comment]
Sure, I can look into doing the reverse mapping. One question, though. For something `dotnet-dev-rhel-x64....`, would a future rhel 8 version go as `dotnet-dev-rhel.7-x64`? Or would you then redo the scheme to have the `dotnet-dev-rhel-x64` point to the latest release?

**Comment by livarcocc** [comment]
We would only change these RIDs if rhel.8 turns into a brand new RID for the CLI/CoreFX. In which case we would have rhel-x64 and rhel.8-x64.

**Comment by omajid** [comment]
I see. So the download links would be `rhel-x64` and `rhel.8-x64` even if the RIDs are `rhel.7-x64` and `rhel.8-x64`. Got it. 

Thanks.
