### ISSUE TITLE
Enable Background GC

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#604]
_From @alinapopa on November 11, 2014 6:0_

Currently klr.exe runs with non-concurrent garbage collection. Background GC should be enabled by adding STARTUP_CONCURRENT_GC to startup flags in the host.

_Copied from original issue: aspnet/dnx#882_

**Comment by muratg** [comment]
_From @davidfowl on November 11, 2014 6:4_

Looks like #464

**Comment by piotrpMSFT** [comment]
klr.exe has been deprecated. CLI supports Background GC.
