### ISSUE TITLE
[Feature Request] dotnet test on a solution

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/cli#6040]
While chatting on the dotnet gitter channel with another user we noticed that dotnet test on a solution file would help a lot in DevOps scenarios. 

The feature proposal would look like this:
`dotnet test <path to sln>` --> all test class libraries (with the new csproj format) inside the sln would be tested.

I know that you are busy right now with the next release but justed wanted to discuss if that makes sense? ✌️

**Comment by dasMulli** [comment]
Adding a VSTest target to the metaproj would probably improve test times for solutions with lots of test projects.
Currently using a [dedicated "ci build" project file](https://gist.github.com/dasMulli/69f5303aa79a8cd4060e44891c90fd2d) using `dotnet msbuild build.proj` to improve test time and find all the projects to test.
This would probably have to be done by the vstest team by adding target files to [msbuild's extension path](https://github.com/Microsoft/msbuild/issues/920#issuecomment-250495107) in both CLI and VS (this is how restore for solutions works).

**Comment by livarcocc** [comment]
This is a dup of https://github.com/Microsoft/vstest/issues/411.
