### ISSUE TITLE
Wrong dependency versions in the NuGet package after 'dotnet pack' if the project hasn't been rebuilt before

### ISSUE THREAD

**Issue by DmitrySikorsky** [dotnet/cli#6049]
## Steps to reproduce

0. You are using VS2017 and .csproj files.

1. Let's say you have ProjectA version 1.1.1 that has dependency (project dependency with no version specified) to the ProjectB version 1.1.1. You rebuild them and everything is fine.

2. After that you remove 'bin' and 'obj' folders, open the .csproj files and change (manually, in a text editor) VersionPrefix to 1.1.2. Then run 'dotnet pack'. If you open the resulting ProjectA.1.1.2.nupkg file as the archive and look at .nuspec file you will see, that ProjectB dependency version is 1.1.1, not 1.1.2!

3. If you remove 'bin' and 'obj' folders again, open solution in the VS2017 and rebuild, then run 'dotnet pack' and open .nuspec file again, you will see that the dependency version is changed to 1.1.2.

Is it by design? I have created .bat files to pack and then push to nuget and I have never had this behavior before (when used project.json files). So it seems to be not obvious.

I have found this when pushed the packages to the NuGet and then got 'The located assembly's manifest definition does not match the assembly reference' exception when tried to use them. As I have found, both 1.1.1 and 1.1.2 versions are downloaded (1.1.2 are downloaded as primary dependency and 1.1.1 as secondary ones).

Thank you!

**Comment by livarcocc** [comment]
Have you run dotnet restore again after changing the versions?

Dotnet pack uses information based on your project.assets.json file that gets updated only when you run dotnet restore.

In any case, @rohit21agrawal @mishra14 can you guys take a look?

**Comment by DmitrySikorsky** [comment]
No, I didn't. But I didn't run it before too, when used project.json. And it worked as excepted.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4867
