### ISSUE TITLE
how to do the version manage

### ISSUE THREAD

**Issue by geminiyellow** [dotnet/cli#6051]
## Steps to reproduce

is there dotnet version manager like the nvm/rvm or *vm?
i found the `aspnet/dnvm` but it is ** OBSOLETE** , and the REAMME link is point to this project.
but no command like the `upgrade` or `use version` .

## Expected  behavior

i wish swith dotnet version between latest and stable, but i cannot find option in current cli

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
There is no version manager for the CLI today.

However, all CLI versions work side-by-side. So, install as many versions as you want and you get them all.

The CLI will default to the latest release version that you have install. Baring that, it follows semantic versioning for preview versions.

If you want your project(s) to use a specific version, you can create a global.json file at the root of your repo, if you want that for all your projects with the following:

```
{
  "sdk": {
    "version": "cli_version"
  }
}
```
