### ISSUE TITLE
Locale warnings during MVC Core application publish process

### ISSUE THREAD

**Issue by svallis** [dotnet/cli#6052]
## Steps to reproduce

An ASP.NET Core MVC application that self-publishes within its own Docker image based on `microsoft/dotnet:1.1.1-sdk` and sets its locale information using the following commands:

```
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8
```

## Expected  behavior

Publish without errors or warnings.

## Actual behavior

The following warnings, which seem to occur once per project:

```
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.
bash : warning : setlocale: LC_ALL: cannot change locale (en_GB.UTF-8) [/tmp/src/Library/Library.csproj]
Library -> /tmp/src/Library/bin/Release/netcoreapp1.1/Library.dll
bash : warning : setlocale: LC_ALL: cannot change locale (en_GB.UTF-8) [/tmp/src/WebApp/WebApp.csproj]
WebApp -> /tmp/src/WebApp/bin/Release/netcoreapp1.1/WebApp.dll
Razor view compilation for WebApp -> obj/Release/netcoreapp1.1/WebApp.PrecompiledViews.dll
```

They are just warnings, and I haven't noticed any larger issues that I would attribute to them, but I'd like to understand what could be causing them? There were no warnings when using the `project.json` cli to publish.

## Environment data

Docker environment derived from `microsoft/dotnet:1.1.1-sdk`.

**Comment by livarcocc** [comment]
@MichaelSimons I am not sure this has anything to do with the CLI.

**Comment by MichaelSimons** [comment]
@svallis, what does your Dockerfile look like and what does the output of the build look like?  Do you see a warning generated from the `ENV LC_ALL en_GB.UTF-8` command?  I suspect that your locale is not configured correctly for `en_GB.UTF-8`.

**Comment by svallis** [comment]
Apologies if it's in the wrong place, hard to know exactly where the issue is coming from, but as the warning appears once per project compiled, and interspersed between the beginning and end of the `dotnet publish` command this was my best guess.

@MichaelSimons Dockerfile:

```
FROM microsoft/dotnet:1.1.1-sdk

RUN apt-get update && apt-get install -y nodejs && \
    update-alternatives --install /usr/bin/node nodejs /usr/bin/nodejs 100 && \
    curl https://www.npmjs.com/install.sh | sh && \
    npm install gulp -g
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8

ENV PROJECT_NAME WebApp

COPY . /tmp/.

WORKDIR /tmp/src/$PROJECT_NAME/
RUN dotnet restore

RUN npm install && \
	gulp publish && \
	dotnet publish -c Release -o Build && \
    cp -ar /tmp/src/$PROJECT_NAME/Build/. /app/ && \
    rm -rf /tmp/

EXPOSE 5000/tcp
WORKDIR /app/
ENTRYPOINT dotnet /app/$PROJECT_NAME.dll
```

The entire output from a `docker build` is rather verbose, but the bits that relate (i.e. setting the environment variable and the build/publish step) look as follows:

```
Step 3/13 : ENV LANG en_GB.UTF-8
 ---> Running in efe15cc6010e
 ---> 29fea08f608d
Removing intermediate container efe15cc6010e
Step 4/13 : ENV LANGUAGE en_GB:en
 ---> Running in eb3a4f192f24
 ---> 41d36db98f35
Removing intermediate container eb3a4f192f24
Step 5/13 : ENV LC_ALL en_GB.UTF-8
 ---> Running in e35869c33b7f
 ---> b7b372abb4f8
Removing intermediate container e35869c33b7f
```

And then later:

```
Step 9/12 : dotnet publish -c Release -o Build &&     cp -ar /tmp/src/$PROJECT_NAME/Build/. /app/ &&     rm -rf /tmp/
 ---> Running in 91ae86499d79
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.
bash : warning : setlocale: LC_ALL: cannot change locale (en_GB.UTF-8) [/tmp/src/Library/Library.csproj]
Library -> /tmp/src/Library/bin/Release/netcoreapp1.1/Library.dll
bash : warning : setlocale: LC_ALL: cannot change locale (en_GB.UTF-8) [/tmp/src/WebApp/WebApp.csproj]
WebApp -> /tmp/src/WebApp/bin/Release/netcoreapp1.1/WebApp.dll
Razor view compilation for WebApp -> obj/Release/netcoreapp1.1/WebApp.PrecompiledViews.dll
```

The locale is definitely applying correctly. If I remove them the environment variables the warnings disappear and all currency is $; add the environment variables back in and it's back to £.

The warnings are in amongst the build/publish process's output, and didn't occur when performing exactly the same operation using the `project.json` tooling.

**Comment by svallis** [comment]
Dropping the `ENV LC_ALL en_GB.UTF-8` line while leaving `ENV LANG en_GB.UTF-8` and `ENV LANGUAGE en_GB:en` in place seems to maintain the locale correctly and stop the warnings. Why that line caused the warnings within the build/publish process, I'm not sure. It seems in this case that the line was superfluous though, so I'm happy enough assuming I don't bump into any unwanted side effects. Thanks.

**Comment by MichaelSimons** [comment]
@svallis, I don't think `ENV LC_ALL en_GB.UTF-8` is working correctly.  Build and run the following Dockerfile:

```
FROM microsoft/dotnet:1.1-sdk

ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8
```

When I do, I see this immediately after running - 'bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)'.  I believe this is the underlying issue that is surfacing during `dotnet build`  I am not an expert in changing the locale on Debian but from what I was reading, the following seems to work.

```
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales

RUN sed -i -e 's/# en_GB.UTF-8 UTF-8/en_GB.UTF-8 UTF-8/' /etc/locale.gen && \
    echo 'LANG="en_GB.UTF-8"'>/etc/default/locale && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_GB.UTF-8

ENV LANG en_GB.UTF-8
```

**Comment by MichaelSimons** [comment]
Updated Dockerfile to include setting LANGUAGE and LC_ALL.

**Comment by svallis** [comment]
@MichaelSimons Understood and agreed. Appreciate your help, thanks.

**Comment by livarcocc** [comment]
Can we close this issue? Thanks for looking @MichaelSimons
