### ISSUE TITLE
Feature: dotnet add should handle a list of packages

### ISSUE THREAD

**Issue by NCC1701M** [dotnet/cli#6056]
## Steps to reproduce
Type in your console the following:
`dotnet add package Microsoft.AspNetCore.Routing Microsoft.AspNetCore.StaticFiles`

## Expected  behavior
The CLI should install both packages at once.

## Actual behavior
Receiving the following error:
`Please specify one package reference to add.`
For each package you like to install you have to call `dotnet add package <PACKAGE>`. This is cumbersome and should be simplified.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4839
