### ISSUE TITLE
dotnet test [project] should look for csproj

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [dotnet/cli#6057]
My solution looks like:
```
Kronos.Sln
/Src/Kronos.Client
/Tests/Kronos.Client.Tests
```

## Steps to reproduce
`dotnet test Tests\Kronos.Client.Tests`

## Expected  behavior
`dotnet test` should automatically find single csproj in given path

## Actual behavior
> **Couldn't **find** a project to run test from**. Ensure a project exists in C:\Dev\Kronos.
> Or pass the path to the project

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

I would suggest following points:
- Print information about given path
- If user passed a directory, try to find a csproj

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#630
