### ISSUE TITLE
error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1

### ISSUE THREAD

**Issue by husseinsa** [dotnet/cli#6058]
## Steps to reproduce

I was using VS Studio 2015 Professional Edition Update 3 on Windows 10 Professional  Everything was working fine before installing VS 2017 Edition.

Now, When I create a new Class Library or Console app, the dependencies fail to install. Here is the question more elaborated on [SO](http://stackoverflow.com/questions/42844245/dotnet-core-error-msb4025-visual-studio-2015-package-restore-restore-dg) .

**This is the error:**

> C:\Program Files\dotnet\dotnet.exe restore "c:\users\myuser\documents\visual studio 2015\Projects\RedisCache\.vs\restore.dg"
> c:\users\myuser\documents\visual studio 2015\Projects\RedisCache\.vs\restore.dg(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

**global.json**
`{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}

**SDKs Installed:**
 Directory of C:\Program Files\dotnet\sdk

03/14/2017  11:36 PM    <DIR>          .
03/14/2017  11:36 PM    <DIR>          ..
03/14/2017  11:36 PM    <DIR>          1.0.0
09/30/2016  04:56 PM    <DIR>          1.0.0-preview2-003131
01/20/2017  02:14 PM    <DIR>          1.0.0-preview2-1-003177
               0 File(s)              0 bytes
               5 Dir(s)  52,758,339,584 bytes free

`
## Expected  behavior
The dependecies should be installed automatically as it was before.

## Actual Behavior:

If I run dotnet restore the dependencies are installed

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
Please try with the latest SDK and without project.json.
