### ISSUE TITLE
dotnet test -parallel N

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [dotnet/cli#6059]
How to disable parallel run for xunit tests? 

I found similar issues (#1447, #401), but they look out of date. There is no `-diagnostics`` flag.

Should I use `-s` and create some configuration file?

## Steps to reproduce
`dotnet test Project.csproj -parallel None`
or
`dotnet test Project.csproj -parallel none`

## Expected  behavior
Disable parallel execution of the tests

## Actual behavior
```
MSBUILD : error MSB1001: Unknown switch.
Switch: -parallel
```

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#631
