### ISSUE TITLE
After publish to IIS, app does not log to stdout

### ISSUE THREAD

**Issue by mjnorman** [dotnet/cli#6060]
## Steps to reproduce
Target 1.1.1 .net core VS2017.  Deploy app to IIS using standard Program.cs--

```c#
var host = new WebHostBuilder()
                .UseKestrel()
                .UseUrls("http://localhost:5001")
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();
```

enable logging via published web.config file

```c#
stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout"
```

## Expected  behavior
Expect log\stdout_xxxx file to be created and updated when server errors occur.

## Actual behavior
No file is created, no event in event viewer

## Environment data
`dotnet --info` output:
N/A, production IIS machine

**Comment by livarcocc** [comment]
@Eilon would you happen to know a better home for this issue.

**Comment by Eilon** [comment]
@moozzyk does this look like an ASP.NET issue or an ANCM issue?

**Comment by moozzyk** [comment]
Does the folder exists? `.\logs\stdout` tells me they want to log somewhere in the application subfolder but it is neither created or can be published: 
 - ANCM does not create the folder so if it does not exist nothing gets logged (https://github.com/aspnet/AspNetCoreModule/issues/30)
- dotnet publish does not publish empty folders (https://github.com/dotnet/cli/issues/2911, https://github.com/Microsoft/msbuild/issues/1586)

**Comment by livarcocc** [comment]
Closing for now since we haven't had activity here in a while. Please, re-activate if the suggestions above do not work for you.

**Comment by sujithkrish** [comment]
I don't think this issue is resolved. As an alternate, folders will need to be created manually.

**Comment by dasMulli** [comment]
@sujithkrish the documents have been updated with a workaround to be put into the csproj file: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure

See https://github.com/aspnet/websdk/issues/273 and https://github.com/aspnet/AspNetCoreModule/issues/30 for the underlying issues.

**Comment by ferryferry** [comment]
You have to check the folderpermissions of the logs folder. If you are running inside IIS you have a application pool for the application.

You have to grant write permissions for the "IIS APPPOOL\<applicationpoolname>" user on the logs folder.

**Comment by fernandezjose** [comment]
I have everything "in place", including IIS APPPOOL, however, nothing is being outputted.

**Comment by toddlangdon** [comment]
I was having this same problem. Verified that web.config had stdoutLogEnabled="true", that logs folder existed and app pool identity had write permissions but still no log file.  After I manually recycled App Pool it started working - you you might want to try that

**Comment by TheRealFlif** [comment]
I got it to work after manually creating the directory logs.
As explained [here](https://codedocu.com/Net-Framework/ASP_dot_Net-Core/Errors/IIS-AspCore-Errors/Asp-Core-Error_colon_-Could-not-create-stdoutLogFile?2308)
