### ISSUE TITLE
Retry Docker image pull, and cleanup images.

### ISSUE THREAD

**Issue by ravimeda** [dotnet/cli#6061]
## Steps to reproduce

- Run`dockerrun.sh -d docker/centos.7`

## Expected  behavior

- Retry image pull a couple times until successful.
- Cleanup Docker images so that build machines do not run low on disk space causing subsequent builds to fail.

## Actual behavior
There is only a single attempt made to pull the image. If the attempt fails then, there is no retry, and build fails.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  8986198501

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

---
Similar issue was logged on core-setup. See https://github.com/dotnet/core-eng/issues/561
Corresponding PRs https://github.com/dotnet/core-setup/pull/1747 and  https://github.com/dotnet/core-setup/pull/1759

Cc @MichaelSimons

**Comment by livarcocc** [comment]
@ravimeda is this a change that you can now pull into the CLI?

**Comment by ravimeda** [comment]
> Retry image pull a couple times until successful.

For this copy changes from dotnet/core-setup#1747 and dotnet/core-setup#1759 to `dotnet/cli/blob/master/scripts/dockerrun.sh`

> Cleanup Docker images so that build machines do not run low on disk space causing subsequent builds to fail.

Since CLI does not use checked in build definitions, each VSTS build definition needs to be updated to run tasks to initialize and cleanup Docker. Refer to 

- https://github.com/dotnet/core-setup/blob/master/buildpipeline/Core-Setup-Linux-BT.json#L95-L112
- https://github.com/dotnet/core-setup/blob/master/buildpipeline/Core-Setup-Linux-BT.json#L186-L202

Since CLI does not appear to be using BuildTools, `init-docker.sh` and `cleanup-docker.sh` have to be manually copied over from (https://github.com/dotnet/buildtools/tree/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/docker), and checked into CLI so that the VSTS task can consume. 

Please give it a try.

**Comment by livarcocc** [comment]
This hasn't been a problem in quite a while. Closing this issue.
