### ISSUE TITLE
Publishing from Windows to Linux no longer working after upgrading to VS2017 / csproj

### ISSUE THREAD

**Issue by Daniel15** [dotnet/cli#6071]
## Steps to reproduce
I have a website powered by ASP.NET Core 1.1.1: https://github.com/Daniel15/Website. I'm trying to upgrade from VS2015 to VS2017. To publish the site, I'm running a command like this:

```
dotnet publish . -o "c:\TempPublish\site" -c Release -r debian-x64
```

And then `rsync`ing the directory to my Linux server. I specify the target runtime as `debian-x64` to avoid Windows-specific binaries in the output dir (eg. `libuv.so` instead of `libuv.dll`)

## Expected  behavior
Build works. This works fine with the old `project.json` format.

## Actual behavior
When I try it with the converted `csproj` I get:

> C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Assets file 'C:\src\dan.cx\Daniel15.Web\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.5.2/debian-x64'. Ensure you have restored this project for TargetFramework='net452' and RuntimeIdentifier='debian-x64'. [C:\src\dan.cx\Daniel15.Web\Daniel15.Web.csproj]

When I remove `-r debian-x64` from the publish command, the resulting built site doesn't actually run on Mono any more - I get `Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`. It looks like it's copying a Windows build of `System.Runtime.InteropServices.RuntimeInformation` rather than a Linux build, at least judging by the paths in the PDBs (`D:\A\_work\39\s\bin\obj\Windows_NT.AnyCPU.Release\...` vs `D:\A\_work\39\s\bin\obj\Unix.AnyCPU.Release...`).

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15031
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by davidfowl** [comment]
What does your project look like?

**Comment by Daniel15** [comment]
> What does your project look like?

This is what the old `project.json` looked like:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "dependencies": {
    "Daniel15.BusinessLayer": {
      "target": "project"
    },
    "Daniel15.Data": {
      "target": "project"
    },
    "Daniel15.Infrastructure": {
      "target": "project"
    },
    "Daniel15.Shared": {
      "target": "project"
    },
    "Daniel15.SimpleIdentity": "1.2.0",
    "React.AspNet": "2.5.0",
    "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.1",
    "Microsoft.AspNetCore.Diagnostics.Abstractions": "1.1.1",
    "Microsoft.AspNetCore.Http.Abstractions": "1.1.1",
    "Microsoft.AspNetCore.Mvc": "1.1.2",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.1.2",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.1",
    "Microsoft.AspNetCore.Session": "1.1.1",
    "Microsoft.AspNetCore.StaticFiles": "1.1.1",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.1",
    "Microsoft.Extensions.Configuration.Json": "1.1.1",
    "Microsoft.Extensions.Logging.Console": "1.1.1",
    "Microsoft.Extensions.Logging.Debug": "1.1.1"
  },

  "tools": {
    "Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net452": {
      "dependencies": { },
      "frameworkAssemblies": {
        "System.Drawing": "4.0.0.0"
      },
      "imports": [
        ".NetFramework 3.5,Version=v0.0"
      ]
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/Admin/Views",
      "Areas/Gallery/Views",
      "config.json",
      "config.Development.json",
      "config.generated.json",
      "web.config",
      "supervisord.conf",
      "nginx.conf"
    ]
  },
  "scripts": {
    "postpublish": "dotnet razor-precompile --configuration %publish:Configuration% --framework %publish:TargetFramework% --output-path %publish:OutputPath% %publish:ProjectPath%"
  }
}
```

This is the `csproj` that was generated when I migrated to csproj through Visual Studio 2017:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Daniel15.Web</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Daniel15.Web</PackageId>
    <PackageTargetFallback>$(PackageTargetFallback);.NetFramework 3.5,Version=v0.0</PackageTargetFallback>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
  </PropertyGroup>

  <ItemGroup>
    <None Include="App.config" />
    <None Update="wwwroot\**\*;Views\**\*;Areas\Admin\Views\**\*;Areas\Gallery\Views\**\*;supervisord.conf;nginx.conf">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Daniel15.BusinessLayer\Daniel15.BusinessLayer.csproj" />
    <ProjectReference Include="..\Daniel15.Data\Daniel15.Data.csproj" />
    <ProjectReference Include="..\Daniel15.Infrastructure\Daniel15.Infrastructure.csproj" />
    <ProjectReference Include="..\Daniel15.Shared\Daniel15.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Daniel15.SimpleIdentity" Version="1.2.0" />
    <PackageReference Include="React.AspNet" Version="2.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.Abstractions" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.TagHelpers" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
    <Reference Include="System.Drawing" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
```

**Comment by Daniel15** [comment]
I tried removing `-r debian-x64` from the publish command, but the resulting site doesn't actually run on Mono any more 😢 . I get `Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`. It looks like it's copying a Windows build of `System.Runtime.InteropServices.RuntimeInformation` rather than a Linux build, at least judging by the paths in the PDBs (`D:\A\_work\39\s\bin\obj\Windows_NT.AnyCPU.Release\...` vs `D:\A\_work\39\s\bin\obj\Unix.AnyCPU.Release...`) and I guess there's something incompatible in there.

**Comment by Daniel15** [comment]
I tried running `dotnet restore  -r debian-x64` (even though I didn't have to do that with the old version) which got me a bit further, but then I hit this error with the Razor view compilation not working:

>'bin\Release\net452\debian-x64\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.exe' is not recognized as an internal or external command,
  operable program or batch file.
> C:\Users\Daniel\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0\build\net451\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(36,5): error MSB3073: The command "bin\Release\net452\debian-x64\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.exe @"obj\Release\net452\debian-x64\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 9009. [C:\src\dan.cx\Daniel15.Web\Daniel15.Web.csproj]

Disabling view precompilation (`MvcRazorCompileOnPublish`) fixes that, and the built site runs fine.

So, I needed to do two things to get the site building after upgrading from VS2015/project.json to VS2017/.csproj to get the same site building for Linux correctly:

1. Run `dotnet restore  -r debian-x64` as part of my deployment build
2. Disable view precompilation

**Comment by livarcocc** [comment]
@Eilon for view compilation.

If you don't want to do a restore -r debian-x64, you can specify it as a `<RuntimeIdenitifier>debian-x64</RuntimeIdentifier>`if you want to run it only as a self-contained app for debian, or `<RuntimeIdentifiers>debian-x64;other_rid1;other_rid2</RuntimeIdentifiers>`. In this case if will work as a self-contained app for potentially all the rids above and restore will download assets for all of them.

If you want to be able to switch between the different portabla and self-contained app, then you need to do the dotnet restore -r rid and dotnet publish -r rid to make it work.

If you don't indicate a rid to restore, restore won't download rid specific assets for you.

**Comment by Daniel15** [comment]
> If you don't want to do a restore -r debian-x64, you can specify it as a <RuntimeIdenitifier>debian-x64</RuntimeIdentifier>

Should I add that just to my website's `csproj`, or to all the class library projects too?

@livarcocc - Did something change during the migration from `project.json` to `csproj`? Everything seemed to just work fine before.

**Comment by Eilon** [comment]
cc @pranavkm for view compilation - any idea why that might be a problem in this scenario? (Repro app above)

**Comment by Daniel15** [comment]
I filed a separate issue with a standalone repro for the view compilation issue: https://github.com/aspnet/MvcPrecompilation/issues/102

**Comment by Daniel15** [comment]
I filed a separate issue with a standalone repro for the view compilation issue: https://github.com/aspnet/MvcPrecompilation/issues/102

Here's my hacky workaround: Build first for Windows, then build for Linux with view precompilation disabled, then copy across the PrecompiledViews assembly:
```
dotnet restore
dotnet publish -o "C:\TempPublish\site_win" -c Release
dotnet restore -r debian-x64
dotnet publish -o "C:\TempPublish\site" -c Release -r debian-x64 /p:MvcRazorCompileOnPublish=false

copy c:\TempPublish\site_win\Daniel15.Web.PrecompiledViews.dll c:\TempPublish\site\
rd /s /q c:\TempPublish\site\Views
```

After doing this, deploying the site via `rsync` works fine.

**Comment by livarcocc** [comment]
@Daniel15 in project.json it was even more restrictive, where if you wanted to publish a self-contained app you have remove the type:platform from the Microsoft.NETCore.App package and you had to have the RID in the runtimes section of your project.

**Comment by Daniel15** [comment]
@livarcocc - I wasn't using Microsoft.NETCore.App, as I'm targeting .NET Framework 4.5.2 and running it on Linux via Mono. I still have references to "full" .NET Framework assemblies like System.Drawing and Entity Framework 6, so I can't move to .NET Core yet. My entire project.json is in a comment above 😃

**Comment by livarcocc** [comment]
@Daniel15 We currently don't support running on Mono on the new tooling.

**Comment by Daniel15** [comment]
The site runs fine on Mono, it's just running the tooling (which I'm doing on Windows) that's the issue. I'm not sure if Mono has ever been officially supported, but I've been running ASP.NET MVC sites on Mono since MVC 4 (2012) with no issues.

**Comment by livarcocc** [comment]
You mean the MVCPreCompilation? I will let @eilon comment on that on the separate issue that is tracking that.

**Comment by Daniel15** [comment]
I'm the person that opened https://github.com/aspnet/MvcPrecompilation/issues/102, I forgot to close this issue. Let's track it there 😃
