### ISSUE TITLE
Problem restoring basic .NET core xUnit project on OSX

### ISSUE THREAD

**Issue by debo** [dotnet/cli#6073]
## Steps to reproduce
Intall dotnet with the following commands (those are the official packages):
```bash
brew cask install dotnet
brew cask install dotnet-sdk
```
Create the project via CLI
```bash
dotnet new xunit -o xunit
```
Restore it
```bash
dotnet restore
```

## Expected  behavior
I am not sure what the result should be, I am new to .NET but I would assume something along the line of:
```
  Restoring packages for /Volumes/Projects/debo/dotnet/mvc/mvc.csproj...
  Lock file has not changed. Skipping lock file write. Path: /Volumes/Projects/debo/dotnet/mvc/obj/project.assets.json
  Restore completed in 1.01 sec for /Volumes/Projects/debo/dotnet/mvc/mvc.csproj.

  NuGet Config files used:
      /Users/debo/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
```
## Actual behavior
The entire log here
https://gist.github.com/debo/2fedc78c98907bd7541f74e89b81856b

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

To be noted that `dotnet --version` output 1.0.1 but `dotnet` output the following"
```
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
```

**Comment by livarcocc** [comment]
Can you try downloading dotnet from dot.net and trying again.

Brew is not really a supported installation scenario for the CLI.

**Comment by debo** [comment]
@livarcocc I did that too and the result is the same. 

Also for the record brew cask it's slightly different from brew, it downloads and install official packages as you can see here:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/dotnet.rb
https://github.com/caskroom/homebrew-cask/blob/master/Casks/dotnet-sdk.rb

It basically automates a manual download/install and nothing more.

**Comment by livarcocc** [comment]
Ah, got it. Thanks for the info.

@emgarten can you take a look at the restore logs and see if something jumps at you?

**Comment by debo** [comment]
@livarcocc no problem and thanks for looking into this, additional info, I tried on two different OSX systems and got the same behaviour.

**Comment by debo** [comment]
@livarcocc @emgarten further attempts and google search later I did find the real issue and I facepalmed myself.

https://github.com/dotnet/sdk/issues/875

So unfortunate that the stack trace wasn't really meaningful in that regards. I hope it helps.

Feel free to close the issue if you think there is nothing else to add.

Thanks.

**Comment by livarcocc** [comment]
@emgarten do you guys have anything tracking this in nuget?

**Comment by emgarten** [comment]
@debo would you open an issue to track improving this error message on https://github.com/nuget/home/issues

Packages and projects are treated the same, so this behavior is expected, but looking at the log it is a very confusing result.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4852

**Comment by livarcocc** [comment]
I moved it already. Thanks.

**Comment by debo** [comment]
@emgarten well yes, I mean, I guess the behaviour makes perfect sense considering I am basically duplicating a namespace
