### ISSUE TITLE
dotnet publish ignores -o

### ISSUE THREAD

**Issue by severisv** [dotnet/cli#6074]
## Steps to reproduce
From solution root folder (https://github.com/severisv/MyTeam):
dotnet publish --configuration Release -o .deploy src/MyTeam

## Expected  behavior
The project is published to the folder called ".deploy".

## Actual behavior
The project is published to \src\MyTeam\bin\Release\net461\MyTeam.exe

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by jonsequitur** [comment]
Under the latest master, the output is going to src/MyTeam/.deploy.

**Comment by livarcocc** [comment]
Closing as this seems fixed, as @jonsequitur stated.

**Comment by omajid** [comment]
Assuming this is being done in `/home/foo/bar/`, should the `-o .deploy` put the results in `/home/foo/bar/.deploy` or in `/home/foo/bar/src/MyTeam/.deploy`? The latter seems counter intuitive to me.
