### ISSUE TITLE
Copy to publish options

### ISSUE THREAD

**Issue by georgeonofrei** [dotnet/cli#6075]
Hello,

I've upgraded a vs 2015 to 2017 and I'm having an issue with the publish options

## Steps to reproduce
I have an angular app inside the wwwroot which outputs to wwwroot/dist.
I've set up csproj:

```
  <ItemGroup>
    <Content Include="wwwroot\dist\**\*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
```

## Expected  behavior
I expect bin/Debug/netcoreapp1.1/publish/wwwroot to have only dist.

## Actual behavior
bin/Debug/netcoreapp1.1/publish/wwwroot contains all folders like src, node_modules, etc. I think that wwwroot is copied entirely to publish by default, ignoring the rule that I've put there. So what can I do to copy ONLY dist?

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

One other concern I am having is related to the current QoS of dotnet core. Compared to net full, I really don't see how adoption is possible with so many changes.

Thanks,
George

**Comment by livarcocc** [comment]
cc @mlorbetske 

That is correct, by default, all contents of wwwroot will be published.

**Comment by georgeonofrei** [comment]
@livarcocc is there any way to change this behavior from csproj settings or any other config file?

Thank,
George

**Comment by mlorbetske** [comment]
@georgeonofrei this should do what you're looking for

```
  <ItemGroup>
    <Content Update="wwwroot\**\*" CopyToPublishDirectory="Never" />
    <Content Update="wwwroot\dist\**\*" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
```

**Comment by livarcocc** [comment]
Let us know if this does not work for you.
