### ISSUE TITLE
minor peeve: dotnet new Program.cs is unecessarily (!?) "UTF-8 with BOM" encoded

### ISSUE THREAD

**Issue by DazWilkin** [dotnet/cli#6078]
## Steps to reproduce

dotnet new

Either
code Program.cs
Observe "UTF-8 with BOM" encoding (botton right hand corner)

![image](https://cloud.githubusercontent.com/assets/1022400/24109744/d3eaa91c-0d4e-11e7-841c-ab2091369c78.png)

Or
sublime Program.cs
```
>>> view.encoding()
u'UTF-8 with BOM'
```
## Expected  behavior

While it seems the standard does not recommend UTF-8 with BOM, there's much debate about its inclusion/exclusion. 

http://stackoverflow.com/a/2223926

I assume there's a legacy problem in removing it.

## Actual behavior

Some non-Windows (Linux) file viewers attempt to render the unexpected \ufeff (Unicode BOM)

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003182)

Product Information:
 Version:            1.0.0-preview2-1-003182
 Commit SHA-1 hash:  024c726cdd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#445
