### ISSUE TITLE
dotnet publish ignores folders

### ISSUE THREAD

**Issue by uandrei** [dotnet/cli#6079]
This issue occurs if we want to take out of the solution stuff that bower and npm install and kick off the bower/npm restore process just before publishing is triggered.

## Steps to reproduce
- Create a new ASP .NET Core VS 2017 website using the bootstrap template
- delete the lib folder from the wwwroot folder
- in the .csproj file of the web project add the following configuration
<Target Name="PrepublishScript" AfterTargets="PrepareForPublish">
    <Exec Command="bower install --allow-root" />
  </Target>
- run the following command:
dotnet publish WebSite\WebSite.csproj -c Release -o publish
## Expected  behavior
- bower install kicks in before publish and regenerates the lib folder
- the lib folder is shown in the wwwroot folder within the output folder

## Actual behavior
- bower install kicks in before publish and regenerates the lib folder
- the lib folder is NOT present in the wwwroot folder within the output folder

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by livarcocc** [comment]
I believe others have reported this.

@mlorbetske @vijayrkn

**Comment by vijayrkn** [comment]
Yes, tracking issue:  https://github.com/aspnet/websdk/issues/114

**Comment by livarcocc** [comment]
Closing this one then.
