### ISSUE TITLE
Broken project README markdown

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/cli#6082]
After this commit the some project's README section looks broken (this is rich diffs view showing differences while rendering Markdown preview):
https://github.com/dotnet/cli/commit/546d62061acc16d82eac57dbc7b12d1a104c2cf7?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

Thanks!

**Comment by omajid** [comment]
Probably another victim of Github's switch to CommonMark :(

**Comment by svick** [comment]
I have a PR open that fixes the table: https://github.com/dotnet/cli/pull/5995.

**Comment by eerhardt** [comment]
This is fixed with #6084.
