### ISSUE TITLE
Should it be an error for project.json to have duplicate references?

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#609]
_From @Eilon on May 6, 2014 16:10_

Currently it is ignored, e.g.: https://github.com/aspnet/WebFx/blob/40e7fcc9ba9d747149dddf9796a61a582cc64077/test/Microsoft.AspNet.Mvc.Core.Test/project.json (which has since been "fixed")

I tried in a csproj file and it is OK to have dups, but I wonder if it makes sense to be more strict? I presume it's typically user error. I'm not sure what happens if you have two references but with different versions - I'm pretty sure that should be an error (if perhaps it isn't already).

_Copied from original issue: aspnet/dnx#152_

**Comment by muratg** [comment]
_From @glennc on May 27, 2014 21:28_

We should at least add a warning when you have the same thing defined twice

**Comment by muratg** [comment]
_From @Praburaj on January 7, 2015 23:43_

Today tooling shows a squiggle when there are duplicate references within the same `dependencies` node. It does not show a squiggle if the same dependency is defined in both root level dependency and a specific target framework dependency. 

![image](https://cloud.githubusercontent.com/assets/2294732/5655506/cb8ca1ce-9683-11e4-875b-95d1a9cc3945.png)

**Comment by muratg** [comment]
_From @troydai on January 8, 2015 3:41_

The warning may be just caused by duplicate keys in json object.

**Comment by muratg** [comment]
_From @Praburaj on January 8, 2015 3:44_

yeah that's right - its due to the JSON schema validation. I thought of mentioning this as there is something right now rather than nothing.

**Comment by muratg** [comment]
_From @davidfowl on July 7, 2015 4:11_

Yes!

**Comment by piotrpMSFT** [comment]
The current behavior is consistent with msbuild.
