### ISSUE TITLE
.Net Core BasePath problem on Raspberry Pi

### ISSUE THREAD

**Issue by PArpad** [dotnet/cli#6091]
Hello!

I've ran into a problem which i couldn't solve by myself. I was trying to search for a solution, but didn't find it. Sorry if this was already asked somewhere.

ps.: i wasn't sure where to open my issue, so sorry if its in the wrong place.

## Steps to reproduce
Running my app. on a Raspberry pi, while my code looks like:

.csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-beta-001737-00</RuntimeFrameworkVersion>
    <RuntimeIdentifiers>ubuntu.16.04-arm</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\PublishProfiles\FolderProfile.pubxml" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.2.0-preview1-23803" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.2.0-preview1-23803" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.2.0-preview1-23803" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.2.0-preview1-23803" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.2.0-preview1-23803" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
```

main in Program.cs:
```
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                //.UseContentRoot("/home/ubuntu/Projects/CameraWebApp/")
                .UseIISIntegration()
                .UseStartup<Startup>()
                .UseApplicationInsights()
                .Build();

            host.Run();
        }
```

Startup function in Startup.cs:
```
public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                //.SetBasePath("/home/ubuntu/Projects/CameraWebApp/")
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }
```

running with: sudo dotnet Projects/CameraWebApp/RaspberryPi_SecurityC                                                                                        am.dll

## Expected  behavior
Application running without a problem.

note: if i use the commented route manually( .SetBasePath("/home/ubuntu/Projects/CameraWebApp/")), the program runs without any exceptions
## Actual behavior
 

> Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'ap                                                                                        psettings.json' was not found and is not optional. The physical path is '/home/u                                                                                        buntu/appsettings.json'.
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean                                                                                         reload)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 provide                                                                                        rs)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at RaspberryPi_SecurityCam.Startup..ctor(IHostingEnvironment env) in D:\VS201                                                                                        7Projects\RaspberryPi_SecurityCam\RaspberryPi_SecurityCam\Startup.cs:line 23
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.Create                                                                                        Instance(IServiceProvider provider)
>    at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServicePr                                                                                        ovider provider, Type instanceType, Object[] parameters)
>    at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstanc                                                                                        e(IServiceProvider provider, Type type)
>    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServicePr                                                                                        ovider hostingServiceProvider, Type startupType, String environmentName)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0                                                                                        .<UseStartup>b__1(IServiceProvider sp)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso                                                                                        lver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider                                                                                        )
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.V                                                                                        isitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso                                                                                        lver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeReso                                                                                        lver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provide                                                                                        r)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.V                                                                                        isitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass                                                                                        18_0.<RealizeService>b__0(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type s                                                                                        erviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.                                                                                        GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.                                                                                        GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at RaspberryPi_SecurityCam.Program.Main(String[] args) in D:\VS2017Projects\R                                                                                        aspberryPi_SecurityCam\RaspberryPi_SecurityCam\Program.cs:line 14
> fish: 'sudo dotnet Projects/CameraWe...' terminated by signal SIGABRT (Abort)

## Environment data
`dotnet --info` output:

on the RPI:

> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0-beta-001737-00
>   Build    : 0afe15b4ca0717fe96516738084f9d6f7022de3e

On windows: 

> dotnet --info
> .NET Command Line Tools (1.0.1)
> 
> Product Information:
>  Version:            1.0.1
>  Commit SHA-1 hash:  005db40cd1
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.1
>

**Comment by livarcocc** [comment]
@Eilon Can you help figure out why this IHostEnvironment is not working for arm?

**Comment by Eilon** [comment]
I'm guessing that `sudo` is changing the current working directory to `/home/ubuntu` perhaps.

**Comment by Eilon** [comment]
Looks like maybe you want to run `sudo -s ...` ? I just did a quick read of http://unix.stackexchange.com/questions/40719/stay-at-same-working-directory-when-changing-to-sudo and that seems to be what you want here.

**Comment by PArpad** [comment]
I was reading through the post, and tried few things, but still got the same exception.

Also if i just run  
>  dotnet Projects/CameraWebApp/RaspberryPi_SecurityCam.dll 

I get the same, can it be still sudo related?

**Comment by Eilon** [comment]
@PArpad right, that's because in Program.cs it's using `Directory.GetCurrentDirectory()`, which is whatever the current directory is for that process. So, if you run `dotnet` from your shell (e.g. bash, PowerShell, etc.) the directory you're in will be the "current directory." If you use sudo, then based on that StackOverflow post there are rules about what the current directory will be.

**Comment by livarcocc** [comment]
This does not seem to be an issue with the CLI and rather expectations about the API. I am going to close it. If I got it wrong, please, re-activate.
