### ISSUE TITLE
Rectify Crossgen Dependencies in the CLI 

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#6093]
We have 2 places where we are restoring for cross gen:

https://github.com/dotnet/cli/blob/master/build_projects/dotnet-cli-build/dotnet-cli-build.csproj#L11-L12
and
https://github.com/dotnet/cli/blob/master/tools/CrossGen.Dependencies/CrossGen.Dependencies.csproj

We should only have 1, and get rid of the other.

**Comment by ellismg** [comment]
I'm looking at fixing this since I am touching related code.
