### ISSUE TITLE
kpm pack --no-source: should remove unused frameworks from project.json in the packed version

### ISSUE THREAD

**Issue by muratg** [dotnet/cli#610]
_From @borgdylan on October 27, 2014 14:35_

Currently kpm pack only builds dependencies for the frameworks actually used by the packed app. This is ok but should also remove the unused frameworks from the dependency project.json. This means that dependencies of the unused frameworks will not be needed. Currently i have a dependency that uses a particular package only on net40. My app runs on aspnet50 and when i pack only the aspnet50 binaries for the dependency get built. However teh net40 dependencies are still mentioned in the dependency’s project.json while that net40 only package is not mentioned in the produced global.json.  This means that when one runs web.cmd/web.sh on the server that only has KREs installed and requires that all other nupkegs be brought in as part of teh packed app, will get a failure unless this net40 only dependency is installed via kpm.

_Copied from original issue: aspnet/dnx#818_

**Comment by muratg** [comment]
_From @davidfowl on December 7, 2015 9:22_

There's no such thing as an unused framework. Why is it in there in the first place.

**Comment by piotrpMSFT** [comment]
kpm has been deprecated.
