### ISSUE TITLE
dotnet publish needs to resolve a named filter to a path to a filter file

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6103]
This is for publishing with a named filter, like `dotnet publish --filter aspnet` so that the user doesn't need to know the full path to the filter.

CLI should be able to resolve that named filter based on a set of filters installed to a well known location of the CLI.

- [ ] Determine the filters location.
- [ ] Change publish to look for named filters in the filter location. Do we want to be able to override this filter location?
- [ ] How exactly will this work in VS? They do not shell out to the CLI, they invoke the targets themselves, which means that we will need to find a VS location themselves or they will need to resolve the CLI and use the filter location in the CLI.

cc @DamianEdwards @nguerrera @eerhardt @ramarag

**Comment by livarcocc** [comment]
We discussed this today and we arrived at the agreement that asp.net will resolve the filter in its metapackage.

@Eilon can you link the issue tracking that work to this one when you have an issue for it?

**Comment by Eilon** [comment]
@livarcocc - I think it's this issue: https://github.com/aspnet/MetaPackages/issues/20
