### ISSUE TITLE
CLI should run restore implicitly for commands that require restore

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6105]
CLI should just invoke dotnet restore implicitly for commands that require it:

- run
- build
- publish
- pack
- test

**Comment by svick** [comment]
I believe this issue is related: https://github.com/NuGet/Home/issues/4329.

**Comment by livarcocc** [comment]
We should add a parameter to turn this off though. Likely a --no-restore flag.

cc @richlander

**Comment by terrajobst** [comment]
> We should add a parameter to turn this off though. Likely a `--no-restore` flag.

Not that I'm against but what scenarios would require that?

**Comment by Kritner** [comment]
> Not that I'm against that but what scenarios would require that?

I would guess to not restore for each build... i'm guessing it'd only be beneficial for local development, and not a build server scenario.

**Comment by livarcocc** [comment]
PR: https://github.com/dotnet/cli/pull/6762.
