### ISSUE TITLE
CLI-specific roadmap

### ISSUE THREAD

**Issue by markrendle** [dotnet/cli#6107]
## Steps to reproduce

Try to find a roadmap outlining broad goals and planned features for .NET CLI 2.0

## Expected  behavior

Find a roadmap.md file somewhere in the `dotnet/cli` repository.

## Actual behavior

Do not find a roadmap.md file anywhere in the `dotnet/cli` repository, nor in the Wiki.

## Environment data

Web 3.1

**Comment by livarcocc** [comment]
@richlander @bleroy

**Comment by livarcocc** [comment]
This is what we are tracking for the CLI: https://github.com/orgs/dotnet/projects/2.
