### ISSUE TITLE
Assembly.GetEntryAssembly() returns null during integration tests when targeting net462

### ISSUE THREAD

**Issue by nphmuller** [dotnet/cli#6108]
I'm not sure which repository this belongs in, so apologies in advance if it's in the wrong one.

I use Microsoft.AspNetCore.TestHost in a dedicated project for integration tests, which has a reference to the to be tested project (an Mvc Core API).

The following problem occurred after migrating from project.json to MsBuild.

In my startup I have many dependencies that call `Assembly.GetEntryAssembly()`. 
For example: `AutoMapper`, `SeriLog` and  `Microsoft.Extensions.DependencyModel.DependencyContext.Default` all call it internally.

In the project.json structure GetEntryAssembly() returned a reference to the test runner assembly (for me dotnet-test-xunit.exe). Now with the msbuild project structure it returns null. This makes all above dependencies throw an exception.
This happens both with MsTest and xUnit.
This happens only when targeting the full framework (e.g. net462). When targeting netcoreapp, GetEntryAssemby() returns an actual (not null) value.

Am I doing something wrong? Because according to [the officical docs](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing) this is the right way. And in the old project style this worked perfectly.

### Sample
The code described in these steps can be found [here](https://github.com/nphmuller/MsBuildGetCallingAssembly/tree/master).
[This branch](https://github.com/nphmuller/MsBuildGetCallingAssembly/tree/WorkAround) includes also includes the workaround.

### Full steps

We need 2 projects: The MVC API and the test project.

#### API:
1. Run `dotnet new webapi`
2. Edit the csproj file to target both netcoreapp1.1 net462 (`<TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>`)
2. Now add the following code to `Startup.cs` in any method (for example, the constructor):
``` c#
// This returns null during the test when targeting net462.
var entryAssembly = System.Reflection.Assembly.GetEntryAssembly();
// This line crashes.
// It can be replaced by any dependency that calls GetEntryAssembly() internally.
var depModel = Microsoft.Extensions.DependencyModel.DependencyContext.Default;
```
3. Verify that the api starts correctly:
`dotnet restore && dotnet run -f netcoreapp1.1`
`dotnet restore && dotnet run -f net462`

#### Test:
1.  Run `dotnet new xunit`
2. Replace the content of the csproj file with the following:
``` xml
<Project Sdk="Microsoft.NET.Sdk"><Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.1;net462</TargetFrameworks>
  </PropertyGroup>
  
  <!-- Without this appsettings.json cannot be found by Startup.cs -->
  <ItemGroup>
    <Content Include="..\Api\appsettings.json">
      <Link>appsettings.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api\Api.csproj" />
    
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.1" />
  </ItemGroup>

</Project>
```
3. Open UnitTest1.cs and add the following code to Test1()
``` c#
var server = new Microsoft.AspNetCore.TestHost.TestServer(
    new Microsoft.AspNetCore.Hosting.WebHostBuilder().UseStartup<Api.Startup>());
```
4. Run the intergrations tests:
This one succeeds: `dotnet restore && dotnet test -f netcoreapp1.1`.
This one fails: `dotnet restore && dotnet test -f net462`.

## Expected  behavior
`dotnet restore && dotnet test -f netcoreapp1.1` should succeed and the test should pass.
`dotnet restore && dotnet test -f net462`  should succeed and the test should pass.

## Actual behavior
`dotnet restore && dotnet test -f netcoreapp1.1` succeeds and the test passes
`dotnet restore && dotnet test -f net462` fails with a NullReferenceException.

## Workaround
The work around is really ugly and involves reflection. I've taking it from [this](http://stackoverflow.com/a/21888521/5473409) StackOverflow answer.

Call SetEntryAssembly() before creating the TestServer object.
``` c#
        /// <summary>
        /// Use as first line in ad hoc tests (needed by XNA specifically)
        /// </summary>
        public static void SetEntryAssembly()
        {
#if NET462
            SetEntryAssembly(System.Reflection.Assembly.GetCallingAssembly());
#endif
        }

        /// <summary>
        /// Allows setting the Entry Assembly when needed.
        /// Use AssemblyUtilities.SetEntryAssembly() as first line in XNA ad hoc tests
        /// </summary>
        /// <param name="assembly">Assembly to set as entry assembly</param>
        public static void SetEntryAssembly(System.Reflection.Assembly assembly)
        {
#if NET462
            AppDomainManager manager = new AppDomainManager();
            FieldInfo entryAssemblyfield = manager.GetType().GetField("m_entryAssembly", BindingFlags.Instance | BindingFlags.NonPublic);
            entryAssemblyfield.SetValue(manager, assembly);

            AppDomain domain = AppDomain.CurrentDomain;
            FieldInfo domainManagerField = domain.GetType().GetField("_domainManager", BindingFlags.Instance | BindingFlags.NonPublic);
            domainManagerField.SetValue(domain, manager);
#endif
        }
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#649
