### ISSUE TITLE
Migration results in incorrect project type

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/cli#6110]
## Steps to reproduce
1. Clone https://github.com/dotnet/buildtools/tree/master/src/BinaryRewriting/BclRewriter
2. dotnet migrate

## Expected  behavior
csproj having executable output type (<OutputType>Exe</OutputType>)

## Actual behavior
csproj is converted to library

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
This is the same as your other issue. Your project.json gives no indication that it is an app and migration does not look at the csproj for information.
