### ISSUE TITLE
Add native installers for RHEL, Ubuntu and Debian

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6113]

**Comment by TheFlyingCorpse** [comment]
👍 to this, with repositories for simpler updating, preferrably with major versions as its own repositories.

**Comment by omajid** [comment]
When you say "native installers", does that mean packages and package repositories? Or something else?

**Comment by wli3** [comment]
> When you say "native installers", does that mean packages and package repositories? Or something else?

.deb file and publish it to the apt-get feed

**Comment by wli3** [comment]
- [ ] add Fix Debian pipe line
- [ ] adjust document of readme.md, Debian8 user should add _jessie_ feed
- [ ] verify ubuntu 16.04
- [ ] verify ubuntu 16.10
- [ ] verify ubuntu 14.04
- [ ] adjust document for above

**Comment by livarcocc** [comment]
Let's track RPM generation through https://github.com/dotnet/cli/issues/4866.
