### ISSUE TITLE
Installer version 1.1.1 actually installs version 1.0.1 

### ISSUE THREAD

**Issue by markchagers** [dotnet/cli#6116]
## Steps to reproduce
1. download : https://go.microsoft.com/fwlink/?linkid=843455
2. start the installer called: dotnet-1.1.1-sdk-osx-x64.pkg
3. after installation type:
    dotnet --version 
in the terminal
## Expected  behavior
Installer window to display version number 1.1.1 
`dotnet --version` output to be 1.1.1

## Actual behavior
Installer window displays version number 1.0.1
`dotnet --version` output is 1.0.1

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
@leecow Any chance we can fix the file name? This is confusing to people.

**Comment by omajid** [comment]
See https://github.com/dotnet/cli/issues/3773 for more discussion on `--version`.

**Comment by leecow** [comment]
Yes, we can take care of that today.

**Comment by livarcocc** [comment]
Thanks @leecow.

**Comment by leecow** [comment]
The SDK installers and archives have been renamed using the same format as previous releases - `dotnet-dev-[platform]-[arch].[sdk-version]` (eg `dotnet-dev-osx-x64.1.0.1.pkg`). Hopefully we'll be successful unraveling the Gordian knot of versioning for 2.0.
