### ISSUE TITLE
Add a CLI gesture to display installed SDKs/Runtimes in the host location

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6119]
The current suggestion for this verb is `dotnet --versions`

The output for it is:
```
SDKs:
    1.0.0
    1.0.1
Runtimes:
    1.0.4
    1.1.1
```

cc @richlander

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/issues/3773

**Comment by piotrpMSFT** [comment]
This issue probably belongs in Core-Setup. The host should be able to enumerate host versions & runtime versions without installing the CLI.

I think folks on the other issue, #3773, had some thoughts on what the output of this gesture should look like. Perhaps we can aggregate those in this issue?

**Comment by gortok** [comment]
@piotrpMSFT I'm not familiar with Core-Setup; would that provide the ability to (after install) discern the SDKs and Runtime?  If users dont' have to install the CLI to figure this out; what are they installing that tells this information when they need it post install?

**Comment by steveharter** [comment]
Closing this as it is covered by core-setup issue https://github.com/dotnet/core-setup/issues/675

The proposal is to add --list-runtimes and --list-sdks to the host meaning you would type `dotnet --list-runtimes` to display the currently installed runtimes \ frameworks and `dotnet --list-sdks` to display the installed sdks. These commands will be implemented in the host, not forwarded to the SDK\CLI, so they will work without any development tools.
