### ISSUE TITLE
dotnet run creates new process

### ISSUE THREAD

**Issue by lutzroeder** [dotnet/cli#6122]
## Steps to reproduce
dotnet run & PID=$!
kill -9 ${PID}

## Expected  behavior
The PID matches the running app, same as dotnet exec

## Actual behavior
Two processes seem to be getting created and kill will only terminate the first one.
18781 ttys007    0:01.01 dotnet run
18795 ttys007    0:00.40 dotnet exec /foo/bin/netcoreapp1.1/app

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by tmds** [comment]
Does it help if you add minus before the PID argument to signal the process group?

**Comment by lutzroeder** [comment]
It's a workaround but underlying issue remains that the PID returned isn't the one of the binary running. `go run` is similar and returns the proper PID of the started process. `dotnet run` should do the same.

**Comment by dasMulli** [comment]
`dotnet run` is a development tool. it builds the project and executes the resulting binary, using whatever shared framework the project uses, which may differ from the runtime that the CLI runs on. In case of a `net*` application, it needs to execute a full framework `.exe` on windows.

It should work for `dotnet the.dll`.

**Comment by livarcocc** [comment]
Correct, using dotnet the.dll won't spawn new processes and is the way that you should run your portable applications in production.

dotnet run is a development tool only and we have talked about improvements in our documentation to make that clear.
