### ISSUE TITLE
Dotnet publish fails if dependencies are set

### ISSUE THREAD

**Issue by ChristianSauer** [dotnet/cli#6125]
## Steps to reproduce
1. Create an ASP.NET Core Project with Docker Support. Use 1.1.1 Images as base.
2. Add a Class Library, also 1.1.1
3. Add the class library as a dependency of the docker-compose Project.
4. Run dotnet publish, it will fail with 
/src/Upload/Upload.csproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/src/Upload/Upload.csproj.metaproj'.

Note that this works under Windows, but fails in Linux, e. g. the new docker build process.
## Expected  behavior
It should work

## Actual behavior
4. Run dotnet publish, it will fail with 
/src/Upload/Upload.csproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/src/Upload/Upload.csproj.metaproj'.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
Can you share your csproj? I suspect your project has a dependency on the Docker SDK, which is only available on Windows with VS.

The Docker SDK is not supported/shipped cross-plat. You may want to move this issue to https://github.com/Microsoft/dockertools to see about any plans about making this SDK cross-plat.

**Comment by livarcocc** [comment]
Closing this for now since we got no new info back. If my assumptions above are wrong, please re-activate.

**Comment by ChristianSauer** [comment]
@livarcocc  Sorry for my disappearance. The fix is checked in for netcore 2.0, so I think this bug can stay closed.

**Comment by 4tilo2** [comment]
I have the same issue.
Using dotnet sdk 1.0.4.

Docker SDK is not mentioned in any file.
global.json is set correctly, what other post mentioned to the MSB4025 error.

**Comment by 4tilo2** [comment]
@livarcocc can you reopen this issue or should a create a new one?
