### ISSUE TITLE
'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer' and no extension method 'UseSqlServer' accepting a first argument of type 'DbContextOptionsBuilder' could be found

### ISSUE THREAD

**Issue by Smilefounder** [dotnet/cli#6126]
## Steps to reproduce
Run the following command line:
`dotnet ef dbcontext scaffold "Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=...\Database.mdf;Integrated Security=True;Connect Timeout=30"  Microsoft.EntityFrameworkCore.SqlServer --context DbContext --force --output-dir ../_tmp --json`

## Expected  behavior
POCO Generator and build without error.

## Actual behavior
Build error:
`1>_tmp\DbContext.cs(21,28,21,40): error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseSqlServer' and no extension method 'UseSqlServer' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)`

## Environment data
`dotnet --info` output:

>dotnet --info
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
This issue was moved to aspnet/EntityFramework#7970

**Comment by Smilefounder** [comment]
Thanks @livarcocc
