### ISSUE TITLE
dotnet restore: The specified solution configuration "Debug|WINDOWS" is invalid

### ISSUE THREAD

**Issue by epignosisx** [dotnet/cli#6133]
## Steps to reproduce
1- Create new Console App (.NET Core) through VS2017
2- Run ```dotnet restore``` in the solution directory.

## Expected  behavior
Restore to complete successfully.

## Actual behavior
Getting the following error:

C:\Users\alejandroh\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2.sln.metaproj : error MSB4126: The specified solution configuration "Debug|WINDOWS" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Users\alejandroh\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2.sln]

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

## Visual Studio Enterprise 2017
VisualStudio/15.0.0+26228.9

## ConsoleApp2.sln:

```sln
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26228.9
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ConsoleApp2", "ConsoleApp2\ConsoleApp2.csproj", "{9718499E-F274-4407-97F5-DCA08166EE68}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{9718499E-F274-4407-97F5-DCA08166EE68}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{9718499E-F274-4407-97F5-DCA08166EE68}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{9718499E-F274-4407-97F5-DCA08166EE68}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{9718499E-F274-4407-97F5-DCA08166EE68}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

## ConsoleApp2.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4882

**Comment by Legends** [comment]
**What is the cause for this issue?**

> C:\Users\Admin\Source\Repos\Examples\Examples.sln.metaproj : error MSB4126: The specified solution configuration "Debug|X64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Users\Admin\Source\Repos\Examples\Examples.sln]
