### ISSUE TITLE
During apt get update .NET core on Ubuntu 14.04 failing

### ISSUE THREAD

**Issue by aparnaji** [dotnet/cli#6139]
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
-- Success
sudo -E apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
--Success
sudo apt-get update
--Failing with the below error
W: Failed to fetch https://apt-mo.trafficmanager.net/repos/dotnet-release/dists/trusty/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/main/i18n/Translation-en_US  Error reading from server - read (104: Connection reset by peer)

## Environment data

64 bit Ubuntu 14.04

Behind coprate proxy
Proxy set as
export  http_proxy=http://user:pws@proxy:8080/
export  https_proxy=https://user:pws@proxy:8080/		

Edit /etc/apt/apt.conf  add a line 
	 Acquire::http::proxy "http://user:pws@proxy:8080/";
 Acquire::https::proxy "https://user:pws@proxy:8080/";

**Comment by livarcocc** [comment]
Why is this a CLI issue? Are you sure that this isn't a problem with the configuration in your network?

**Comment by livarcocc** [comment]
We have been running our own tests on this and they have been passing. If this is still an issue for you, please re-activate and provide additional information.
