### ISSUE TITLE
dotnet publish The type or namespace name 'Net' does not exist in the namespace 'System'

### ISSUE THREAD

**Issue by sm-g** [dotnet/cli#6140]
## Steps to reproduce
Create Core WebApp on net462, referencing net462 Library with dependency of `System.Net.Http` (Same behavior for `System.ComponentModel.DataAnnotations`).

Migrate to VS2017 (Everything builds in MSBuild, but not by cli.)

run `dotnet publish -f net462`

[zip solution](http://ge.tt/81OmOOj2)

## Expected  behavior
work as is was before upgrade

## Actual behavior
Class1.cs(5,14): error CS0234: The type or namespace name 'Net' does not exist in the namespace 'System' (are you missing an assembly reference?)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by livarcocc** [comment]
I can't repro this anymore using VS 2017 and SDK 2.0.2. Please, re-activate if you can still repro it. Also, I could not download the zip you added. It was blocked to me.

**Comment by sm-g** [comment]
@livarcocc Checked with 2.0.2, still same issue

try https://github.com/sm-g/dotnet-cli-6140

(I'm not sure now, should cli work with such "net462" projects at all... it was never working for me.)

**Comment by livarcocc** [comment]
It should, but you need the targeting pack for it installed in the box. Do you have that?

**Comment by sm-g** [comment]
I installed .NET Framework 4.6.2  Dev Pack from https://www.microsoft.com/net/download/visual-studio-sdks, and `dotnet build -f net462`, but nothing changes.

**Comment by livarcocc** [comment]
Could you share your csproj or a full project where this reproes?

**Comment by sm-g** [comment]
https://github.com/dotnet/cli/issues/6140#issuecomment-345052539 here is the link to github repo
