### ISSUE TITLE
Migrating via VS 2017 (latest) references projects from the backup folder

### ISSUE THREAD

**Issue by christianhuening** [dotnet/cli#6142]
## Steps to reproduce
I tried to migrate a larger solution (57 projects) with VS 2017 and encountered some referencing issues. When investigating the non-resolvable references, I found that these references are pointing to the Backup folder created by the migration process. When manually re-adding the reference to that project from the actual solution, everything is fine again:
![d918482a-106b-11e7-9a36-ecfdba8e7037](https://cloud.githubusercontent.com/assets/738953/24297355/c39c0de2-10a2-11e7-8079-3dff6688369d.PNG)

## Expected  behavior
All project dependencies are linked to the actual projects.

## Actual behavior
Some referenced projects were referenced to the Backup folder

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by wilhen01** [comment]
I've just seen this on VS2017 Professional on Windows 10 migrating a DotNet Core VS2015 project.

**Comment by jstallm** [comment]
Noticed this same issue on 20 + project solution using VS2017 15.1 26403.7. After running `dotnet migrate {solutionName}.sln` it successfully alters the .sln file, but incorrectly forces the solutions to reference backup folder

**Comment by jstallm** [comment]
Solution for me was to simply remove every backup folder that was created, then run dotnet migrate again.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#15
