### ISSUE TITLE
Re-enable Fedora24 in CI

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#6146]
It was taking ~5 retries to get Fedora24 past downloading the stage0 CLI. 

Removing it from CI in #6145. Make sure to get several successes in a row before merging it back in.

**Comment by nguerrera** [comment]
It's possible there's an http stack issue on Fedora because every other OS downlaods stage0 just fine.

**Comment by nguerrera** [comment]
https://ci.dot.net/job/dotnet_cli/job/master/job/release_fedora24_x64_prtest/91/console
```
[‎3/‎24/‎2017 1:50 PM] 
13:17:17 dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005645/dotnet-dev-fedora.24-x64.2.0.0-preview1-005645.tar.gz
13:17:17 dotnet_install: Error: Download failed 
```

https://ci.dot.net/job/dotnet_cli/job/master/job/release_fedora24_x64_prtest/93/console 
13:35:11 + ./build.sh --skip-prereqs --configuration Release --targets Default
13:35:11 dotnet_install: Error: Download failed

**Comment by nguerrera** [comment]
@mmitche Any more thoughts on this? I know you said that if the machine is picking up builds, it's got good network connectivity. 

cc @eerhardt

**Comment by mmitche** [comment]
@nguerrera Are their any more diagnostics you can enable to see why the download fails?

**Comment by nguerrera** [comment]
This has >80% failure rate right now. So I'd prefer to get set up with a Fedora VM and iterate locally then to keep CI on the floor while we add diagnostics with a crazy slow iteration time. Is there a way I can get SSH to a Fedora machine?

**Comment by nguerrera** [comment]
I got a machine from @mmitche and I'm trying to repro

**Comment by nguerrera** [comment]
And it repros!

**Comment by nguerrera** [comment]
So curl execution is just flaky. That rules out a .NET Core product bug. One thing: the curl in run-build.sh has a --retry 10 whereas dotnet-install.sh doesn't so the latter is more likely to fail. The former can take quite a while to download the tiny bootstrap sh files so I imagine it's retrying a bunch. This rules out a .NET CLI or .NET Core product issue.

**Comment by nguerrera** [comment]
This is happening only on the Fedora image and no other OSes so I don't think it's an Azure CDN issue.

**Comment by natemcmaster** [comment]
FYI we [added](https://github.com/aspnet/KoreBuild/commit/f692ca7c8ef8a277b92aef6cfc85ffdda2beafc8) the `-S` option to curl in our dotnet-install.sh script so that we see errors. This is what is failing:

```
curl: (56) SSLRead() return error -36
```

**Comment by nguerrera** [comment]
@natemcmaster Were you also seeing this only on Fedora?

**Comment by nguerrera** [comment]
@livarcocc We should add that -S to our dotnet-install as well.

**Comment by nguerrera** [comment]
And maybe a --retry too.

**Comment by natemcmaster** [comment]
@nguerrera It's only affected macOS so far. But we don't test on Fedora. Just macOS and Ubuntu Trusty.

We tried adding curl --retry, connecting to blob.core.windows.net instead of CDN, and using wget...still having the connection issues.

**Comment by livarcocc** [comment]
We are adding Fedora 27 now. I don't believe we need this CI. Closing.
