### ISSUE TITLE
Drop NuGet.Config with dotnet new

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#615]
Until we RC, it's expected for `NETStandard.Library` to be available via myget.

In order to provide a `dotnet new` template which leverages the StdLib, we should drop a NuGet.config when a user invokes `dotnet new` with an entry for `https://myget.org/f/dotnet-core`

cc @piotrpMSFT @Sridhar-MS

**Comment by prasannavl** [comment]
Should this really use the Nuget.conf? One of the cool things about `dotnet` cli is that every ends up into that one cli and since `project.json` file. Can the nuget repos not be included into the it as well? Will simply developer usage a lot, instead of proliferating config files.

**Comment by prasannavl** [comment]
Also, please rename title. "Drop" seems ambiguous. On first look I though **stop including the file** .

**Comment by piotrpMSFT** [comment]
Once the packages are on nuget.org the config won't be needed.
