### ISSUE TITLE
Add Support for SLES 12.x

### ISSUE THREAD

**Issue by TheFlyingCorpse** [dotnet/cli#6152]
With this I mean prebuilt RPM's and preferably a repo to install from.

There is no current support for SLES 12.x (12.2 is the newest).

Being a user of SLES and it being a Microsoft friendly distribution, I'd have hoped to have this present. This is a must to get PowerShell to SLES.

**Comment by livarcocc** [comment]
Please, file an issue in core-setup first. The runtime needs to be enabled in the distro before the CLI. However, we are enabling a linux x64 portable distro that will make it easier to on-boarding new distros.

**Comment by livarcocc** [comment]
Closing this one since this needs to happen in the runtime. Also, any reason why the portable linux Sdk would not work for you? Have you tried that out?
