### ISSUE TITLE
donet build does not seem to set version via msbuild property ?

### ISSUE THREAD

**Issue by pmcgrath** [dotnet/cli#6154]
## Steps to reproduce
	mkdir /tmp/app && cd /tmp/app
	dotnet new console
	Add a Version element to app.csproj
		 <Version>1.2.3</Version>
	Alter the Program.cs as follows
```
using System;
using System.Reflection;

namespace app
{
    class Program
    {
        static void Main(string[] args)
        {
            var v1 = Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyFileVersionAttribute>();
            var v2 = Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyVersionAttribute>();
            var v3 = Assembly.GetEntryAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>();

            Console.WriteLine($"AssemblyFileVersion = {v1?.Version.ToString()}");
            Console.WriteLine($"AssemblyVersion = {v2?.Version.ToString()}");
            Console.WriteLine($"AssemblyInformationalVersion = {v3?.InformationalVersion}");
        }
    }
}
```
	dotnet restore
	dotnet build --configuration Release /property:Version=5.6.7
	dotnet run /tmp/app/bin/Release/netcoreapp1.1/app.dll

## Expected  behavior
	One of the version attributes would have been set based on "/property:Version=5.6.7"
	This expected behaviour is based on the dotnet build --help output
		Additional Arguments:
		 Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.

## Actual behavior
	AssemblyFileVersion = 1.2.3.0
	AssemblyVersion = 
	AssemblyInformationalVersion = 1.2.3

## Environment data
	.NET Command Line Tools (1.0.1)

	Product Information:
	 Version:            1.0.1
	 Commit SHA-1 hash:  005db40cd1

	Runtime Environment:
	 OS Name:     ubuntu
	 OS Version:  16.04
	 OS Platform: Linux
	 RID:         ubuntu.16.04-x64
	 Base Path:   /usr/share/dotnet/sdk/1.0.1

**Comment by dasMulli** [comment]
Does it work if you do `dotnet clean` before invoking the build command?
If so, you might be experiencing the incremental build issue with the autogenerated AssemblyInfo.cs file https://github.com/dotnet/sdk/issues/967

**Comment by pmcgrath** [comment]
@dasMulli 
No did a clean as you suggested, but got same output 
```
dotnet clean
# Just in case, so it cleans the release build
dotnet clean --configuration Release
dotnet build --configuration Release /property:Version=5.6.7
dotnet run /tmp/app/bin/Release/netcoreapp1.1/app.dll
```

**Comment by pmcgrath** [comment]
Can see the content in the generated app.AssemblyInfo.cs is bieng updated after a clean but does not seem to be included in the generated assembly

```
dotnet clean --configuration Release
dotnet build --configuration Release /property:Version=5.6.9
cat obj/Release/netcoreapp1.1/app.AssemblyInfo.cs 
```

// Generated by the MSBuild WriteCodeFragment class.

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("app")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Package Description")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("5.6.9.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("5.6.9")]
[assembly: System.Reflection.AssemblyProductAttribute("app")]
[assembly: System.Reflection.AssemblyTitleAttribute("app")]
[assembly: System.Reflection.AssemblyVersionAttribute("5.6.9.0")]

**Comment by dasMulli** [comment]
Sry, I see it now: you're running `dotnet run` which also builds and runs the project but does not forward the arguments to the build invocation.

To execute a built assembly, use `dotnet path/to/app.dll`

**Comment by pmcgrath** [comment]
@dasMulli Bingo, silly mistake on my part
