### ISSUE TITLE
How to update to latest versions of transitive dependencies ?

### ISSUE THREAD

**Issue by rwasef1830** [dotnet/cli#6155]
Hello,
My apologies if this comes off as a noob question, but this is confusing to me. I'm not sure whether to post this in the nuget repo, dotnet repo or somewhere else.

Since the new csproj project format in VS2017, it is no longer needed to directly reference transitive dependencies since their references are automatically implicitly added and are accessible the project.

However, this presents a problem to me:
- I add Nuget Package A v1.0 which has a transitive dependency to Package B v1.0
- Package B gets an update v1.1
- I don't know about this unless I had installed Package B manually to the project (making it a primary reference) and VS2017 doesn't show Package B v1.1 as an update because Package B v1.0 is not directly installed in the project but merely referenced as a "transitive" dependency.
- If the author of Package A doesn't release an update that reference Package B v1.1, I will miss out on bug fixes in Package B v1.1 and nothing will alert me to do so in the UI.
- I am being forced into the most conservative dependency handling case and have no recourse except to manually hunt for the entire dependency graph and install it by hand to get the same behavior as VS2015.
- In the past, VS2015 would resolve the whole graph and make everything a primary reference, so I can see and can elect to choose whichever minor versions I want. 

Example of this problem:
The relationship between EntityFramework6.Npgsql and Npgsql nuget packages.

How do I tell nuget to tell me what transitive dependency updates are there ? or how to make it revert to the vs2015 behavior of making everything a primary reference ?

**Comment by livarcocc** [comment]
@srivatsn Is this something that we should enable again in VS?

@rrelyea @emgarten Should we enable this in update-all?

**Comment by emgarten** [comment]
Discovering and making the needed transitive packages top level during ``update-all`` could work.

The current approach NuGet has been investigating is support for floating transitive dependencies: https://github.com/NuGet/Home/issues/3159

**Comment by livarcocc** [comment]
Closing this one and tracking it in the NuGet issue.
