### ISSUE TITLE
dotnet add tool

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#6156]
I wish we could

`dotnet add tool DotnetWatcher:1.0.0`

and get

```
<ItemGroup>
 <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0" />
</ItemGroup>
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4901

**Comment by livarcocc** [comment]
The package add functionality is implemented in NuGet, so moving this one there as well.
