### ISSUE TITLE
Markdown table broken

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#6157]
https://github.com/dotnet/cli/tree/rel/1.0.0

![capture](https://cloud.githubusercontent.com/assets/1622880/24340761/3fbf7674-127a-11e7-9fd9-69bef8bc825a.PNG)

cc/ @livarcocc

**Comment by svick** [comment]
This has been fixed on master by https://github.com/dotnet/cli/pull/6084.

If it makes sense to fix rel/1.0.0, then rel/1.0.1 should be fixed too.

**Comment by livarcocc** [comment]
This has been fixed in rel/1.0.1. rel/1.0.0 is not really being activate maintained anymore. Our servicing branch is rel/1.0.1. I don't think it makes sense to port it to 1.0.0.
