### ISSUE TITLE
"dotnet restore" ignores projects having "Build Dependencies -> Project Dependencies" in VS2017

### ISSUE THREAD

**Issue by andersnm** [dotnet/cli#6158]
## Steps to reproduce
1. Use latest VS2017 w/ASP.NET Core workload
2. Create new ASP.NET Core web app solution
3. Open a cmd.exe and run "dotnet restore" from the solution root, notice it restores packages for the web project
4. Add .NET Core class library to the solution
5. Rclick the ASP.NET project, go to Build Dependencies -> Project Dependencies
6. Tick the checkbox such that the ASP.NET Project depends on the class library project
7. Close the dependencies dialog and save the solution
8. Run "dotnet restore" again from the solution root, notice how it silently ignores the web project

This becomes a problem on our build server with the latest .NET Core SDK installed. Because the web app deps aren't fetched, "dotnet build" fails with a bunch of "The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft'"-type errors. The solution builds and runs on my computer both with "dotnet build" and inside VS2017 - presumably because the packages are already downloaded somewhere.

If I remove the checkbox from "Build Dependencies -> Project Dependencies" and instead add the other library as a regular reference then "dotnet restore" works as expected. Although these two projects should not have a full project reference - I just want to indicate one should build before the other (in our case we have an old csproj Bridge.NET library, adding it as a reference breaks "dotnet build" for other reasons).

## Expected behavior
Restore packages for all projects, or some kind of message/warning about skipped projects

## Actual behavior
Restores packages for all projects except those having "Project Dependencies"

## Environment data
Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
@andersnm It is not clear to me what you are trying here.

You are saying there are no type dependencies between the two projects, correct? Just a build ordering issue?

If so, restoring the solution should restore both projects and building should be fine, though to be honest, I am not sure if the CLI would honor this set ordering.

@rainersigwald do you know if building a solution would respect the project ordering?

**Comment by andersnm** [comment]
@livarcocc There are no type dependencies, correct. But it is not a build ordering issue: VS correctly respects the build ordering if it is set. The problem is "dotnet restore" does not restore packages for the project when build ordering is enabled.

**Comment by livarcocc** [comment]
@emgarten can you take a look?

**Comment by emgarten** [comment]
Tracked on NuGet here: https://github.com/NuGet/Home/issues/4578

**Comment by andersnm** [comment]
Great, closing this one then
