### ISSUE TITLE
dotnet-install.sh fails on ubuntu.16.10

### ISSUE THREAD

**Issue by sbomer** [dotnet/cli#6169]
## Steps to reproduce

- on an ubuntu.16.10 machine
- wget https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
- chmod +x dotnet-install.sh
- ./dotnet-install.sh

## Expected  behavior

This downloads an appropriate cli.

## Actual behavior

https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-rc4-004917/dotnet-dev-ubuntu.16.10-x64.1.0.0-rc4-004917.tar.gz doesn't exist.

## Environment data

ubuntu.16.10

## Additional info

This works on ubuntu.16.04, but not ubuntu.16.10. I also tried downloading the following specific versions. Both work on 16.04 but not 16.10.
- 1.0.0-rc4-004788
- 2.0.0-preview1-005619

I noticed that the install script linked from https://www.microsoft.com/net/download/linux *does* work - it gets version 1.0.1 of the SDK on ubuntu.16.10.

Why do different versions of the SDK artifacts exist for 16.10 but not for 16.04? I find this surprising given that the released SDK does support 16.10.

@swaroop-sridhar

**Comment by livarcocc** [comment]
The versions you specified do not exist for ubuntu 16.10. That's why.

Ubuntu 16.10 was a distro that we added support to 1.0.1 and only recently ported the changes over to 2.0.0.

Try installing 2.0.0-preview1-005673 (latest) for instance and it should work.
