### ISSUE TITLE
TargetFrameworks is unsupported anymore?

### ISSUE THREAD

**Issue by 303248153** [dotnet/cli#6170]
## Steps to reproduce
First, use vs2017 create a new console project. then open csproj and change
```
<TargetFramework>netcoreapp1.1</TargetFramework>
```
to 
```
<TargetFrameworks>net461;netcoreapp1.1</TargetFrameworks>
```
then rebuild.

## Expected  behavior
dotnet run and dotnet build should success, can support output net 461 assemblies when I specific `-f` option

## Actual behavior
```
C:\Users\admin\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1>dot
net run
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports
this project.
The current OutputType is 'Exe'.
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by niltor** [comment]
you should  run: `dotnet restore` first ,have a try!

**Comment by 303248153** [comment]
I already run `dotnet restore`, you should try my steps once.
Also somebody notice me `dotnet run` will give this error but `dotnet run -f net461` work,
so maybe it's a bug or just a unfriendly warning.

**Comment by niltor** [comment]
I have tried your actions;
I think the command `dotnet`  doesn't support framework by default only if you point a special framework with `-f` arguments.
Use VS2017,you can **click Run button**,it will run as net461.But use `dotnet run` command ,it run netcoreapp by default,so the error show as:
```
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports
this project.
The current OutputType is 'Exe'.
```

**Comment by livarcocc** [comment]
When you have multiple frameworks, you need to tell run which framework to use. Both `dotnet run -f net461` and `dotnet run netcoreapp1.1` will work.

The fact that you are not getting a clear message about this was a bug that we have fixed in master already.
