### ISSUE TITLE
Dotnet Migrate searches non-scope directories without cause

### ISSUE THREAD

**Issue by khionu** [dotnet/cli#6171]
## Steps to reproduce
Run `dotnet migrate`

## Expected  behavior
Successful migration

## Actual behavior
https://gist.github.com/khionu/648f363ae0b23c471753433662d12fcd

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

I'm extremely confused why this would need to look outside my project directory. I have no references to anywhere else in the filesystem.

[My project.json](https://gist.github.com/khionu/d4a6bc4f4c1c89784b5dc1d3eedb258f)
I have no `global.json`, and my `NuGet.Config` only has two items, both remote sources.

I'm sorry for the lack of information, I don't know what else you might need. Please let me know of anything else, I will be prompt.

**Comment by livarcocc** [comment]
We won't know that you don't have a global.json unless we go looking for it, which is one of the things that impact here.

Also, and we could optimize this, we could only look for references if your project has any, but in project.json world, any dependency (even though you know it is a package reference), we need to go look for a potential match in your file system. We won't know it is a package reference or a project reference until we search for it.
