### ISSUE TITLE
CLI choose a better term than "expanding" so that isn't a synonym of "decompressing"

### ISSUE THREAD

**Issue by davkean** [dotnet/cli#6172]
Not sure this belongs here or https://github.com/dotnet/core-setup/.

```
>dotnet run

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 4295 ms
Expanding 100% 18824 ms
```

![image](https://cloud.githubusercontent.com/assets/1103906/24387823/226def84-13c3-11e7-9cb9-5d5ddd833800.png)

**Comment by livarcocc** [comment]
They are not really synonyms. In one, we are decompressing the lzma archive using the lzma algorithm. In the other, we are re-hydrating (to use a different word from expanding) the files in the archive again. In order to save the most space, we actually create an index of the files and remove duplicates before compression. In the expanding step we re-construct that.

**Comment by davkean** [comment]
Your saying that the behavior isn't synonymous but doesn't prevent the words from being synonyms...

**Comment by bradwilson** [comment]
Extracting instead of expanding?
