### ISSUE TITLE
dotnet publish fails 

### ISSUE THREAD

**Issue by SrivatsaMarichi** [dotnet/cli#6173]
Hi,

I am trying to publish dotnet core app to Azure from VSTS. I have opted ASP.NET CORE template for the same. During the dotnet publish task, it's failing. Need some help here. PFA logs for the reference.

Thanks,
Srivatsa
[9_Run dotnet.txt](https://github.com/dotnet/cli/files/875235/9_Run.dotnet.txt)

**Comment by livarcocc** [comment]
From logs it seems like you don't have bower in your box:

```
2017-03-28T09:52:58.0185303Z   > bower install --config.interactive=false & gulp
2017-03-28T09:52:58.0185303Z   
2017-03-28T09:52:58.0255294Z   'bower' is not recognized as an internal or external command,
```

Which is something you need for your web app.

**Comment by SrivatsaMarichi** [comment]
Now that it's running fine after installing the bower.  I have 1 more issue. I have Unit Tests which are running as part of my VSTS build using dotnet core commandline. The tests are identified. But i am unable to publish the same test results. Does that create any xml files post execution of tests? Because i don't see that. I am using "Publish Test Results" task and passing the arguments as "**/*TestResults.xml".

**Comment by SrivatsaMarichi** [comment]
@livarcocc PFA logs for the same.
[7_Test.txt](https://github.com/dotnet/cli/files/877855/7_Test.txt)
[8_Publish Test Results.txt](https://github.com/dotnet/cli/files/877856/8_Publish.Test.Results.txt)

**Comment by livarcocc** [comment]
I believe there is a way for it to generate xunit xml results, you should ask at the microsoft/vstest repo for how to do that.

In the CLI itself, we pass --logger:trx to dotnet test so that trx result files are generated.

**Comment by SrivatsaMarichi** [comment]
you mean to say i can lass that to generate the test results file?On Mar 29, 2017 11:21 AM, Livar <notifications@github.com> wrote:I believe there is a way for it to generate xunit xml results, you should ask at the microsoft/vstest repo for how to do that.
In the CLI itself, we pass --logger:trx to dotnet test so that trx result files are generated.

**Comment by livarcocc** [comment]
Yes, if you pass that it will generate trx files as result files.

**Comment by SrivatsaMarichi** [comment]
could you share me the argument please?On Mar 29, 2017 11:30 AM, Livar <notifications@github.com> wrote:Yes, if you pass that it will generate trx files as result files.

**Comment by livarcocc** [comment]
I did. Above.

`dotnet test --logger:trx`

**Comment by SrivatsaMarichi** [comment]
thanks. worked for me 😃On Mar 29, 2017 10:52 PM, Livar <notifications@github.com> wrote:I did. Above.
dotnet test --logger:trx
