### ISSUE TITLE
can't build on a mac

### ISSUE THREAD

**Issue by calvinmetcalf** [dotnet/cli#6175]
## Steps to reproduce
be on a mac, in a new folder run 

```
dotnet new classlib
dotnet restore
dotnet build
```
## Expected  behavior
it to work

## Actual behavior
```
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/local/share/dotnet/sdk/1.0.1/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "/usr/local/share/dotnet/sdk/1.0.1/Roslyn/RunCsc.sh" exited with code 134. [/Users/me/projects/myproject/myproject.csproj]

Build FAILED.

/usr/local/share/dotnet/sdk/1.0.1/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6006: "/usr/local/share/dotnet/sdk/1.0.1/Roslyn/RunCsc.sh" exited with code 134. [/Users/my/projects/myproject/myproject.csproj]
    0 Warning(s)
    1 Error(s)
```
Time Elapsed 00:00:01.48

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

cc @knownasilya and @guidos who are also having this problem

**Comment by livarcocc** [comment]
Can you share the restore output for this?

Also, can you run dotnet build /v:diag and share the output for that as well?

**Comment by calvinmetcalf** [comment]
restore

```
  Restoring packages for /Users/me/projects/myproject/myproject.csproj...
  Lock file has not changed. Skipping lock file write. Path: /Users/me/projects/myproject/obj/project.assets.json
  Restore completed in 260.32 ms for /Users/me/projects/myproject/myproject.csproj.

  NuGet Config files used:
      /Users/cmetcalf/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
```

result from [dotnet build /v:diag](https://gist.githubusercontent.com/calvinmetcalf/32a9a16fb9bb18ca29731c17e17eaf1b/raw/7e88cca577f3ef60ee16c2d9ca1884d5e352fb1a/error.bash)

then I deleted the obj folder because I realized that what first one wasn't very helpful so this is the rerun `dotnet restore`

```
  Restoring packages for /Users/me/projects/myproject/myproject.csproj...
  Generating MSBuild file /Users/me/projects/myproject/obj/myproject.csproj.nuget.g.props.
  Generating MSBuild file /Users/me/projects/myproject/obj/myproject.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /Users/me/projects/myproject/obj/project.assets.json
  Restore completed in 419.05 ms for /Users/me/projects/myproject/myproject.csproj.

  NuGet Config files used:
      /Users/cmetcalf/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
```

**Comment by dasMulli** [comment]
Took a look out of interest. RunCsc.sh fails with:
```
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.2.dylib (TaskId:22)
 Referenced from: /usr/local/bin/bash (TaskId:22)
 Reason: image not found (TaskId:22)
```
What's interesting is that the path to bash (`/usr/local/bin/bash`) isn't the system default one. So I'm speculating you maybe once installed a newer bash version via homebrew and now it may be broken?..

**Comment by calvinmetcalf** [comment]
@dasMulli that does seem to be related, running `/bin/bash` is fine but running `bash` or `/usr/local/bin/bash` causes the error to crop up. 

I think the root may have to do with `RunCsc.sh` which does `#!/usr/bin/env bash` instead of just `#!/usr/bin/bash`

I'd say it was just my issue for me to clean up, but I have to coworkers who also have the exact same issue making me suspect borked bashes like this are fairly common

**Comment by livarcocc** [comment]
I am no bash expert, would setting `#!/usr/bin/bash` solve the problem for everyone?

I am trying to see what the appropriate fix is here.

**Comment by dasMulli** [comment]
On Mac `/usr/bin/bash` wouldn't work, it had to be `/bin/bash` (at least on my 10.12.4). IIRC, some linux distros do ship bash in `/usr/bin` (but usually have a symlink in `/bin`).
This is one of the reasons using `env` to resolve bash is considered more portable as it determines which one the environment prefers based on the `$PATH`. See http://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash

In this case, an installation of bash was registered to replace the system bash so I'd expect all scripts to follow that. It only doesn't work because this installation has become broken. I don't think any effort should be made to work around broken installations that trade off portability.

**Comment by livarcocc** [comment]
Thanks @dasMulli for the explanation. Given that, I am closing this issue.

**Comment by calvinmetcalf** [comment]
Ok that's fine, the only thing is just that as it turns out, my `#!/usr/bin/env bash` has been broken for a long time time and I run a lot of bash scripts and this his the first one where it came up so I don't know how common it actually is in practice
