### ISSUE TITLE
Suggest needed: equivalent API for dotnet add package -s command

### ISSUE THREAD

**Issue by hongdai** [dotnet/cli#6179]
Hi,
I need to use dotnet add package -s to add/restore a nuget package to a .net core project. I need to do it in runtime. Is there an equivalent API I could use so that I do not need to create a process?

Thanks,
Hong

**Comment by livarcocc** [comment]
These APIs are owned by NuGet. So, moving this issue there.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4923
