### ISSUE TITLE
The --shared-runtime flag causes dotnet-install.sh to fail

### ISSUE THREAD

**Issue by kdubau** [dotnet/cli#6183]
I guess `get_latest_version_info` is resolving an incorrect latest.version file url. Maybe the location has changed?
```sh
puppet-sandbox-osx-kw:dotnet builder$ /tmp/dotnet-install.sh --shared-runtime --verbose --dry-run
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_azure_channel_from_channel rel-1.0.0
dotnet-install: azure_channel=rel-1.0.0
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture 
dotnet-install: Calling: get_normalized_architecture_from_architecture x64
dotnet-install: normalized_architecture=x64
dotnet-install: Calling: get_specific_version_from_version https://dotnetcli.azureedge.net/dotnet rel-1.0.0 x64 Latest
dotnet-install: Calling: get_latest_version_info https://dotnetcli.azureedge.net/dotnet rel-1.0.0 x64
dotnet-install: Calling: get_current_os_name 
dotnet-install: get_latest_version_info: latest url: https://dotnetcli.blob.core.windows.net/dotnet/rel-1.0.0/dnvm/latest.sharedfx.osx.x64.version
dotnet-install: Calling: download https://dotnetcli.blob.core.windows.net/dotnet/rel-1.0.0/dnvm/latest.sharedfx.osx.x64.version
dotnet_install: Error: Download failed
```

## Steps to reproduce
1) download https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh
2) run `dotnet-install.sh --shared-runtime --verbose --dry-run`

## Expected  behavior
It get's the version and download url

## Actual behavior
Fails to download the latest.version file

## Environment Info
.NET Command Line Tools (1.0.0-rc4-004917)

Product Information:
 Version:            1.0.0-rc4-004917
 Commit SHA-1 hash:  9a4c2c32f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by kdubau** [comment]
Also, where can I see a list of suitable values to pass to `--version` ?

**Comment by eerhardt** [comment]
It looks like the `rel-1.0.0` channel (which is the default) doesn't have files with `sharedfx` in them:

`Calling: download https://dotnetcli.blob.core.windows.net/dotnet/rel-1.0.0/dnvm/latest.sharedfx.osx.x64.version`

![image](https://cloud.githubusercontent.com/assets/8291187/24468937/72241122-147f-11e7-8403-0612799d9831.png)

But this is the only channel like that.  Maybe the default channel should be bumped up to `master`?

**Comment by livarcocc** [comment]
I think for the runtime, the default channel needs to be release/1.1.0. @eerhardt, can you follow up with @gkhanna79 and figure out the default channel to use when downloading the shared runtime and then make the appropriate changes to the script?
