### ISSUE TITLE
dotnet publish fails to build non core csproj on Team Services

### ISSUE THREAD

**Issue by jpozo20** [dotnet/cli#6186]
I have a solution with one .NET Core web app and four library projects. The project builds fine with the VS 2017 Build but I can't find the output nowhere in order to publish to an Azure slot.
Searching around I found that dotnet publish does copy the files to the build output, or a specificied one with -c path, but dotnet publish fails to build the project complaining about some packages that were restored before.

I've spent the whole day trying different things and none of them work, I leave the log of the dotnet publish for reference:

Starting: Run dotnet publish

==============================================================================
Task : Command Line
Description : Run a command line with arguments
Version : 1.1.2
Author : Microsoft Corporation
Help : More Information

Working directory: 'C:\a\1\s'
Fail on standard error: 'False'
Modify environment: 'False'
C:\Windows\system32\cmd.exe /c "dotnet publish -c release -o C:\a\1\a"
dotnet publish -c release -o C:\a\1\a
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.
C:\Program Files\dotnet\sdk\1.0.0\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "EntityFramework". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\a\1\s\RearSquad.DAL\RearSquad.DAL.csproj]
C:\Program Files\dotnet\sdk\1.0.0\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.AspNetCore.Authorization, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\a\1\s\RearSquad.DAL\RearSquad.DAL.csproj]

And so on...
Process completed with exit code 1.
System.Exception: Process completed with exit code 1.
==============================================================================
Finishing: Run dotnet publish

**Comment by livarcocc** [comment]
Did you run dotnet restore before running dotnet publish? Can you share your csproj file?

**Comment by jpozo20** [comment]
@livarcocc yes, I did. But I don't think it's related to a csproj in particular

I have four projects that must build in this order, each project depends on the one above it:
-Project A (Class Library)
-Project B (Class Library)
-Project C (Class Library)
-.NET Core web app

On the non core projects it said :
`Nothing to do. None of the projects specified contain packages to restore.`

And though it looks like that when reading the core project it's restoring the packages of the entire solution, when building with publish it throws that exception when trying to build the Project A saying EntityFramework and a bunch of references are missing. Although if I try to build Project A stand alone it builds, all the others fails with the missing references.

As I said, when using Visual Studio Build with the Hosted Agent 2017 the solution builds, but doesn't generate any output. The problem happens when trying to publish either with `dotnet restore`  and then `dotnet publish` or with `dotnet msbuild /t:restore /t:publish`.

**Comment by livarcocc** [comment]
What do you mean by non-core projects? Are these targeting full framework? If so, are they using the new csproj file format?

CLI (dotnet publish) does not support old style csproj files. We only support new ones.

Could you share the csproj for one of these non-core projects?

**Comment by livarcocc** [comment]
Closing this for now. But just to re-iterate, CLI (dotnet build) does not support old style csproj projects.

Re-activate if you are not using old style csprojs and still seeing failures.

**Comment by jpozo20** [comment]
Hello, again. It looks like indeed my library projects have the old csproj format. 
But I don't think that's the reason it is failing.

Although it could be due to the csproj, the problem seems to be with the referenced packages, somehow it's not finding them even though I'm restoring the packages and having the reference there on the cproj.

On Team Services though the build works by using the "deprecated" option of restoring Nuget Packages in a Visual Studio build item. I'll try upgrading the libraries csproj some time later, and let you know. 

I'll keep it closed for now, and thanks again for your time.

**Comment by vanthao** [comment]
I faced the same issue. I have a .net core web project and two others .net framework library. I can build and run the application using VS2017. But when I run the command  "C:\Program Files\dotnet\dotnet.exe" publish BRSWebHTML5.sln --configuration Release --output C:\temp\builds this command will build all three projects and publish the files to a folder. But I always get the errors that some dll can not be found. I work around by compiling the libraries and add to the web .net core project as referenced.
