### ISSUE TITLE
Tests no longer running after removing old versions of dotnet cli

### ISSUE THREAD

**Issue by severisv** [dotnet/cli#6187]
## Description
Tests no longer running after removing old versions of dotnet core sdk. Tests did run when old versions of SDK were present, but not in Visual Studio - only in cmd.

## Steps to reproduce
Remove all versions of dotnet SDK.
Install the latest version of dotnet SDK.
`dotnet test` on

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <AssemblyName>SB.Core.Tests</AssemblyName>
    <PackageId>SB.Core.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SB.Core\SB.Core.csproj" />
    <ProjectReference Include="..\..\util\SB.TestUtilities\SB.TestUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
```

## Expected behavior
Tests are run

## Actual behavior
No test is available in C:\Projects\sb\tests\SB.Core.Tests\bin\Debug\net461\SB.Core.Tests.dll. Make sure that installed test discoverers & executor
s, platform & framework version settings are appropriate and try again.

## Environment
C:\Projects\selvbetjening\test\unit\SB.Core.Tests>dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#671
