### ISSUE TITLE
Linking to an xproj file via dotnet sln add

### ISSUE THREAD

**Issue by markolbert** [dotnet/cli#6189]
I have a bunch of C# libraries, built under VS2015, which I used to reference via global.json. I'm trying to do the same thing in VS 2017.

I read online that the command to use is:

`dotnet sln <sln file> add <proj file>
`
The example I saw involved linking to a csproj file.

When I try to use that command and link an xproj file, dotnet crashes with the following message:

> Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files\dotnet\sdk\1.0.0\Microsoft\VisualStudio\v15.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Programming\UtilityLibraries\src\SpecializedCollections\SpecializedCollections.xproj                            
>    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation
> , String resourceName, Object[] args)                                                                                                       
>    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(IElementLocation elementLocation, String resourceName, Object arg0)  
>    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)                                     
>    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, List`1& projects, Boolean throwOnFileNotExistsError)                         
>    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement)      
>    at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)     
>    at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)                               
>    at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()                                                                                     
>    at Microsoft.Build.Execution.ProjectInstance.Initialize(ProjectRootElement xml, IDictionary`2 globalProperties, String explicitToolsVersi
> on, String explicitSubToolsetVersion, Int32 visualStudioVersionFromSolution, BuildParameters buildParameters, ILoggingService loggingService
> , BuildEventContext buildEventContext)                                                                                                      
>    at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection)                                                                                           
>    at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile)                                                                   
>    at Microsoft.DotNet.Tools.Common.SlnFileExtensions.AddProject(SlnFile slnFile, String fullProjectPath)                                   
>    at Microsoft.DotNet.Tools.Sln.Add.AddProjectToSolutionCommand.Run(String fileOrDirectory)                                                
>    at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.<>c__DisplayClass10_1.<RunCommand>b__0()                                               
>    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)                                                        
>    at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)                                                              
>    at Microsoft.DotNet.Tools.Sln.SlnCommand.Run(String[] args)                                                                              
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)                                                   
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)       
> 

I don't understand the reference to a missing SDK file.

Is it possible to link to an xproj file under VS 2017, similarly to how it was done under global.json? If so, how do I do it?

**Comment by livarcocc** [comment]
This is not a supported scenario. xproj is only supported in VS 2015 with the core extension and the last CLI to support that was preview2, which does not have the dotnet sln add command.

In VS 2017 and the latest CLIs, you must use the new csproj format.

You can migrate your xprojs to csproj by using the dotnet migrate command.
