### ISSUE TITLE
dotnet restore ignore's BeforeTargets="Restore" when using sub projects

### ISSUE THREAD

**Issue by schmitch** [dotnet/cli#6190]
Currently we have a project defined like that:
```
├── project1.sln
└── src
    └── project1
        └── project1.csproj
```

now we have defined some Restore Targets inside our project1.csproj:
```
  <Target Name="EnvisiaPreRestoreScript" BeforeTargets="Restore">
    <Exec Command="npm install" />
    <Exec Command="bower install" />
  </Target>
```

However when running dotnet restore from the root folder it does not restore the npm node_modules, we need to explicitly call `dotnet restore src/envisia_cooperate`, which than works.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
I believe there is some issue about the targets firing when restoring a solution versus a project. In any case, moving this issue to NuGet/Home.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4928
