### ISSUE TITLE
dotnet restore picks wrong project file if project path is specified last

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#6191]
## Steps to reproduce
Call `dotnet restore <arguments> <project-path>`

For example, here is a long invocation where I see this issue:

```
"E:\dotnets\3-29-17\dotnet.exe" restore --no-cache --packages "D:\OSS\corefx\packages" --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://api.nuget.org/v3/index.json D:\OSS\corefx\external\runtime/runtime.depproj
```

## Expected  behavior
The project file specified (`D:\OSS\corefx\external\runtime/runtime.depproj`) is restored with the arguments given.

## Actual behavior
The current directory is searched for a project file, and that is restored instead. In my case, there is a file called "build.proj" which is chosen instead of the file I specified.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005683)

Product Information:
 Version:            2.0.0-preview1-005683
 Commit SHA-1 hash:  6866bc2f4a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\dotnets\3-29-17\sdk\2.0.0-preview1-005683\
```

@eerhardt

**Comment by livarcocc** [comment]
@jonsequitur can you take a look?

**Comment by jonsequitur** [comment]
What's happening is that the parser should be requiring that an option be respecified before considering accepting another argument for that option, but this is not happening, causing the final argument to be added into the `--source` option:

```
> dotnet parse "dotnet restore --no-cache --packages D:\OSS\corefx\packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://dotn
et.myget.org/F/dotnet-core/api/v3/index.json --source https://api.nuget.org/v3/index.json D:\OSS\corefx\external\runtime/runtime.depproj"
[ dotnet [ restore [ --no-cache ] [ --packages <D:\OSS\corefx\packages> ] [ --source <https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json> <https://dotnet.myget.org/F/dotnet-core/api/v3/index.json> <https://api.nuget.org/v3/index.json> <D:\OSS\corefx\external\runtime/runtime.depproj> ] ] ]
Option values to be forwarded:
/p:RestoreNoCache=true /p:RestorePackagesPath=D:\OSS\corefx\packages /p:RestoreSources=https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json%3Bhttps://dotnet.myget.org/F/dotnet-core/api/v3/index.json%3Bhttps://api.nuget.org/v3/index.json%3BD:\OSS\corefx\external\runtime/runtime.depproj
```

This is the same root cause as https://github.com/dotnet/cli/issues/6193#event-1021048414.

I've opened the following issue for this: https://github.com/dotnet/CliCommandLineParser/issues/54
