### ISSUE TITLE
dotnet publish incorrectly uses #if DEBUG/RELEASE

### ISSUE THREAD

**Issue by peske** [dotnet/cli#6194]
## Steps to reproduce
1) Use some conditional compilation as follows:
```
#if DEBUG
  Console.WriteLine("Debug detected!");
#else
  Console.WriteLine("Release detected!");
#endif
```
2) Publish (and compile) it with `-c release` configuration as follows:
```
dotnet publish -c release
```
3) Execute

## Expected  behavior
Should write `"Release detected!"`

## Actual behavior
Writes `"Debug detected!"`

## Additional info
Building the project in Visual Studio produces expected results. Only CLI build makes it wrong.

**Comment by livarcocc** [comment]
I can't repro this.

I just tried this out and it works as expected. How are you executing the application?

If you pass the -c Release value, it should publish the app under bin/Release/netcoreapp1.0/publish.

**Comment by peske** [comment]
SORRY, STUPID ME... I've just noticed the following in my `project.json`:
```
"buildOptions": {
    "emitEntryPoint": true,
    "define": [ "DEBUG" ]
  }
```
Obviously Visual Studio has put this because I checked "Define DEBUG constant" option in project properties sometimes earlier...

Thanks for being so fast in trying to help! And sorry again!
