### ISSUE TITLE
Running tests from output directory

### ISSUE THREAD

**Issue by OmarTawfik** [dotnet/cli#6195]
On dotnet cli 1.1.0 (**928f77c4bc3f49d892459992fb6e1d5542cb5e86**), I’m trying to do the following:

```
dotnet new xunit
dotnet restore
dotnet publish
dotnet test
```

The sample project builds successfully, and I can run the sample test, with the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
</Project>
```

Now I want to redirect the output (binaries and obj file) to a custom folder other than the project folder, so I modify the project file to add this:

```xml
    <RepositoryRoot>..</RepositoryRoot>
    <ProjectName>MyProject</ProjectName>
    <OutputPath>$(RepositoryRoot)\Binaries\$(Configuration)\$(ProjectName)</OutputPath>
    <BaseIntermediateOutputPath>$(RepositoryRoot)\Binaries\Obj\$(ProjectName)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\</IntermediateOutputPath>
```

And I run the same commands. I see the following directories created:

1. `Binaries\Obj\MyProject`
* Contains nuget generated props/targets/json files
2. `Binaries\Obj\MyProject\Debug\netcoreapp1.1\`
* Contains obj files and binaries
3. `Binaries\Debug\MyProject\netcoreapp1.1\`
* Contains just the binary and its pdb
4. `Binaries\Debug\MyProject\ netcoreapp1.1\publish\`
* Contains the binary, its pdb, and dependencies (mainly xunit binaries and testhost)

The problem now is that if I try and run `dotnet test`, I get the following error:

`Could not find testhost.dll for source MyProject.dll. Make sure test project has a nuget reference of package "microsoft.testplatform.testhost"`

I’m guessing it is because the test runner is trying to run the tests from the binary in the output directory, not the publish directory, which doesn’t have the required dependencies.

What is the proper properties to set to redirect tests to be run from there? is there a certain flag missing?

**Comment by livarcocc** [comment]
If you are trying to run tests out of a published dll, dotnet vstest in the command you should use.

Something like

```
dotnet publish -o outputdir
dotnet vstest outputdir/your.dll
```

**Comment by OmarTawfik** [comment]
Now I'm getting the following error, even though `testhost.dll` exists in the publish directory:

```
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Testhost process exited with error: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'Binaries\Debug\MyProject\netcoreapp1.1\publish'.
```

**Comment by OmarTawfik** [comment]
@livarcocc any thoughts?

**Comment by codito** [comment]
@OmarTawfik this is likely due to https://github.com/Microsoft/vstest/issues/657. As a workaround, please remove `*.runtimeconfig.dev.json` from the publish directory.

**Comment by livarcocc** [comment]
@OmarTawfik If this is still not working for you, please re-activate, but given that we haven't had activity here in a few days, I am closing this issue.

**Comment by OmarTawfik** [comment]
#codito @livarcocc thanks for the info. Will follow the issue mentioned above.
In the meantime, I hand authored a script that copies the binaries appropriately.
