### ISSUE TITLE
dotnet vstest --help  encoding error

### ISSUE THREAD

**Issue by ShaomingCode** [dotnet/cli#6196]
## Steps to reproduce

dotnet vstest --help

## Actual behavior
 dotnet vstest --help
Microsoft (R) ▒▒▒▒ִ▒▒▒▒▒▒▒й▒▒߰汾 15.0.0.0
▒▒Ȩ▒▒▒▒ (C) Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

▒÷▒: vstest.console.exe [▒▒▒▒] [ѡ▒▒] [[--] <args>...]]

˵▒▒: ▒▒ָ▒▒▒▒▒ļ▒▒▒▒в▒▒ԡ▒

▒▒▒▒:

[TestFileNames]
      ▒▒ָ▒▒▒ļ▒▒▒▒в▒▒ԡ▒ʹ▒ÿո▒ָ▒▒▒▒▒▒▒▒▒ļ▒
      ▒▒▒ơ▒
      ʵ▒▒: mytestproject.dll
                mytestproject.dll myothertestproject.exe

ѡ▒▒:

--Tests|/Tests:<Test Names>
      ʹ▒▒▒▒▒ṩ▒▒ֵ▒▒ƥ▒▒▒▒▒▒▒▒▒▒в▒▒ԡ▒▒▒Ҫ▒ṩ▒▒▒
      ֵ▒▒ʹ▒ö▒▒Ž▒▒▒▒Ƿָ▒▒▒▒▒
      ʾ▒▒: /Tests:TestMethod1
                /Tests:TestMethod1,testMethod2

## Environment data
`dotnet --info` output:

$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005683)

Product Information:
 Version:            2.0.0-preview1-005683
 Commit SHA-1 hash:  6866bc2f4a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005683\

**Comment by codito** [comment]
@ShaomingCode what is the current OS locale? /cc:@Faizan2304

**Comment by Faizan2304** [comment]
@ShaomingCode What is the output of `dotnet --help`

**Comment by livarcocc** [comment]
Given that we haven't had tracking on this issue, closing it for now. Please, re-activate when the information is available.

Also, we will do a loc pass for 2.0 for the CLI, so we will address it if/when we hit this.
