### ISSUE TITLE
dotnet watch test encoding error and always waiting

### ISSUE THREAD

**Issue by ShaomingCode** [dotnet/cli#6197]
## Steps to reproduce
dotnet watch test

## Actual behavior
 dotnet watch test
watch : Started
Build started, please wait...
Build completed.

Test run for D:\code\SMCore\SMCore.XUnitTest\bin\Debug\netcoreapp1.1\SMCore.XUnitTest.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) ▒▒▒▒ִ▒▒▒▒▒▒▒й▒▒߰汾 15.0.0.0
▒▒Ȩ▒▒▒▒ (C) Microsoft Corporation▒▒▒▒▒▒▒▒▒▒Ȩ▒▒▒▒

▒▒▒▒▒▒▒▒▒▒▒▒ִ▒У▒▒▒▒Ժ▒...
[xUnit.net 00:00:01.2167924]   Discovering: SMCore.XUnitTest
[xUnit.net 00:00:01.3112492]   Discovered:  SMCore.XUnitTest
[xUnit.net 00:00:01.3481981]   Starting:    SMCore.XUnitTest
[xUnit.net 00:00:01.4749998]   Finished:    SMCore.XUnitTest

▒ܲ▒▒▒: 1▒▒▒▒ͨ▒▒: 1▒▒ʧ▒▒: 0▒▒▒▒▒▒▒▒: 0▒▒
▒▒▒▒▒▒▒гɹ▒▒▒
▒▒▒▒ִ▒▒ʱ▒▒: 2.4843 ▒▒

watch : Exited
watch : Waiting for a file to change before restarting dotnet...

## Environment data
`dotnet --info` output:
 dotnet --info
.NET Command Line Tools (2.0.0-preview1-005683)

Product Information:
 Version:            2.0.0-preview1-005683
 Commit SHA-1 hash:  6866bc2f4a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005683\

**Comment by livarcocc** [comment]
Do you get the test encoding issue when running just dotnet test, without watch?

**Comment by livarcocc** [comment]
Closing as we haven't had activity here in a long time. If you can still repro this in 2.0.0 or latest, please re-activate and maybe answer my question above.
