### ISSUE TITLE
dotnet sln some.sln remove some.csproj leaves behind project dependencies

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#6198]
## Steps to reproduce
1. In VS, create a new project in a new solution. It doesn't matter what kind of project.
1. Add a new project to that solution. It doesn't matter what kind of project.
1. Project (menu) -> Project Dependencies... -> Check the box in the checklistbox. This adds a solution-level dependency from one of these projects to the other. Let the project with the dependency be "project A" for the next steps.
1. Save and close the solution.
1. At the command line, execute `dotnet sln your.sln list` to see the list of projects. Find "project A"
1. Execute the command `dotnet sln your.sln remove ProjectA.proj`
1. Immediately build your sln from the command line: `msbuild your.sln`

## Expected  behavior

The build succeeds.

## Actual behavior

The build fails:

> C:\Users\andarno\Documents\visual studio 2017\Projects\ClassLibrary10\ClassLibrary10.sln : Solution file error MSB4051: Project {B085B16B-F65B-45EE-B668-9FB1F3DE4691} is referencing a project with GUID {2E1583FD-4B73-47D4-AE17-7BBAA8405A98}, but a project with this GUID was not found in the .SLN file.

This is because the `dotnet sln remove` command only removes the project -- it doesn't remove solution level dependencies that other projects have on it.

Opening the solution in Visual Studio at this point causes the sln file to be updated to remove this extraneous dependency, but without VS, the problem can only be fixed by manually editing the solution to remove the dependency.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  8986198501

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by peterhuene** [comment]
@AArnott I've reproduced the issue out of master and I am working on a fix.  Thank you for your patience and for originally reporting the issue!
