### ISSUE TITLE
Typo in --help documentation: dependented

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#6199]
`dotnet publish --help` prints documentation that mentions "framework-dependented app". I believe it should be "framework-dependent app".

https://github.com/dotnet/cli/search?p=1&q=framework-dependented&type=&utf8=%E2%9C%93

**Comment by mairaw** [comment]
This has been fixed in the master branch already:
https://github.com/dotnet/cli/commit/b6053811653b0e63777be5a856fe448e30c8538b#diff-25cf71eb3cc84f71b57ea7db048a33a3
