### ISSUE TITLE
Error with finding \DNX\Microsoft.DNX.Props

### ISSUE THREAD

**Issue by beckmx** [dotnet/cli#6201]
## Steps to reproduce

I updated my dotnet version to 1.0.1, then I tried to run a simple command:

`dotnet restore `

but it gave me an error

> /Users/xx/src/dotnetstarter/dotnetstarter.xproj(7,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v14.0/DNX/Microsoft.DNX.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

## Expected  behavior

Update from nugget packages

## Actual behavior

An error comes out

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by dsplaisted** [comment]
Is this a project.Jason project still?  You'll need to run `dotnet migrate` to convert it to csproj.

**Comment by livarcocc** [comment]
As @dsplaisted state, 1.0.1 version of the CLI does not support project.json. You will need to migrate your projects to MSBuild to work with that version of the CLI.
