### ISSUE TITLE
dotnet run gives System.BadImageFormatException

### ISSUE THREAD

**Issue by tapanrami** [dotnet/cli#6203]
## Steps to reproduce
Its simple console hello world  default app. no change in default code.

## Expected  behavior
print hello world in console

## Actual behavior
getting exception 
System.BadImageFormatException

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

@danmosemsft

**Comment by livarcocc** [comment]
Can you share your csproj with us? This usually happens when you have a x86 app and you try to run it with the x64 host and vice-versa.

**Comment by tapanrami** [comment]
After restarting the PC it works perfectly so it may be have some issue with installation.
