### ISSUE TITLE
.NET Core project targeting net461 throws runtime error upon startup

### ISSUE THREAD

**Issue by severisv** [dotnet/cli#6204]
Our project has been running .NET Core 1.1 for a while, targeting net461, on all developer machines and in production.
After removing the old .NET Core SDKs it stopped working on my machine, and as it turns out the empty web template from Visual Studio fails to run aswell.
I have tried reinstalling all traces of Visual Studio and .NET Core SDK, but the problem persists.

## Steps to reproduce
In Visual Studio: File -> New -Project (.NET Framework 4.6.1) -> ASP.NET Core Web Application (.NET Framework) -> Empty.
Run solution (fails without an error message)
Open project folder and do `dotnet restore` (works) + `dotnet run`

## Expected  behavior
Application starts

## Actual behavior
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Hosting, Version=1.1.1.0, Culture=neutral, PublicKeyTo
ken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at WebApplication6.Program.Main(String[] args)
```

## Environment data

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by livarcocc** [comment]
@mlorbetske any ideas?

**Comment by mlorbetske** [comment]
@severisv what runtimes do you see under `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`?

**Comment by severisv** [comment]
1.0.4 and 1.1.1. 

To be clear I am able to run netcoreapp1.1-apps, just not net4xx-apps

**Comment by mlorbetske** [comment]
Hmm, perhaps @Eilon has some ideas on this?

**Comment by severisv** [comment]
After formatting my hard drive and installing Windows 10 I no longer have this issue.

**Comment by irowbin** [comment]
Same error here. 👎 
![Uploading Capture.PNG…]()

**Comment by irowbin** [comment]
Same error... 👎 
![capture](https://cloud.githubusercontent.com/assets/13050078/24965644/5f95b150-1fc4-11e7-9967-24a35130de7a.PNG)

**Comment by dasMulli** [comment]
@irowbin `dotnet run` is for projects, `dotnet the.dll` runs built applications.

**Comment by irowbin** [comment]
@dasMulli dotnet run is for published project? Tried all for published project but the error keep throwing.

**Comment by dasMulli** [comment]
does `dotnet WebApplication2.dll` work?

**Comment by irowbin** [comment]
@dasMulli Nope.

**Comment by livarcocc** [comment]
@irowbin what error are you getting? Can you share your csproj?

Also, like @dasMulli pointed out. dotnet run is for projects only. It is a development tool. The most common usage for it is to use dotnet run in the same folder as your csproj.

If you want to run a published app, you do dotnet <path_to_your_app_dll> if it is a portable app. Or <your_app>.[exe] if it is a self-contained app. exe is in square brackets because it is only present for windows.

**Comment by livarcocc** [comment]
Closing since this does not seem to repro for @severisv and I haven't been able to repro either.

And @irowbin seems to be a misunderstanding on how dotnet run works.

Please, feel free to re-activate if there is anything else going on.
