### ISSUE TITLE
Support for 32-bit "dotnet run"

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#6205]
When I create a dotnet app and build to be "portable" (run with the runtime as a dependency instead of publishing for a specific RID), my only option is to "dotnet run" the app, which is always 64-bit. 

Is there no dotnet-x86.exe that I can use to force running as a 32-bit application (at least on Windows)?

**Comment by livarcocc** [comment]
There is an x86 version of the shared framework that carries the x8 version of the host. Likewise, there is an x86 windows SDK.

You can get it here: https://www.microsoft.com/net/download/core.
