### ISSUE TITLE
Verbosity not working

### ISSUE THREAD

**Issue by vdurante** [dotnet/cli#6207]
## Steps to reproduce

dotnet build MyProject.sln /v:d 

## Expected  behavior

Display detailed logs

## Actual behavior

Displays the detailed logs, but non descriptive warnings. For example:

```
 C:\Program Files\dotnet\sdk\1.0.1\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\Projects\MyProject\MyProject.csproj]
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by NickCraver** [comment]
I'm seeing this with `dotnet restore` as well, no verbosity level seems to have any effect on the output - is there a workaround?

**Comment by vcsjones** [comment]
Workaround:

`dotnet restore /ConsoleLoggerParameters:Verbosity=<your verbosity level>`

**Comment by vcsjones** [comment]
@vdurante Does `dotnet build  /ConsoleLoggerParameters:Verbosity=Detailed` work for you?

**Comment by vdurante** [comment]
@vcsjones it does. Thank you!

**Comment by livarcocc** [comment]
This is working on the latest 2.0 tooling.
