### ISSUE TITLE
"dotnet has stopped working" when changing platform target to x86 on project

### ISSUE THREAD

**Issue by CameronAavik** [dotnet/cli#6212]
Apologies if this is the wrong place for this, wasn't sure where it should go but since it was `dotnet` that was crashing, I assume this is the right place.

## Steps to reproduce
1. Clone my repo: https://github.com/CameronAavik/ILject
2. Open in Visual Studio
3. Build all (important since the project which runs next uses the built output of other projects)
4. Change ILject.SamplePatch to x86 platform target in it's properties
5. Run ILject.SamplePatch

Step 4 should have added the following to the SamplePatch csproj

```
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
  <PlatformTarget>x86</PlatformTarget>
</PropertyGroup>
```

## Expected  behavior
The program runs as it does when under Any CPU or x64

## Actual behavior
A window pops up saying:

> dotnet has stopped working

The debug output in visual studio says:

> The program '[19808] dotnet.exe' has exited with code -532462766 (0xe0434352).

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.0)
> 
> Product Information:
>  Version:            1.0.0
>  Commit SHA-1 hash:  e53429feb4
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.0

Note: I am not using the cli directly so I don't know if this is the same version of the cli that gets used by Visual Studio or even if Visual Studio is using the cli or something else.

**Comment by livarcocc** [comment]
This is happening because the host that you are using is x64. So, you are using a x64 host to load an x86 application.

@srivatsn @BillHiebert How does VS chooses which host to use to run the application?

**Comment by livarcocc** [comment]
Btw, if you were in the command line, it would be your responsibility to choose the right host to run your app.

**Comment by srivatsn** [comment]
VS just uses the 'dotnet' that's in PATH.

**Comment by livarcocc** [comment]
I guess in this case you need to change your path to point to an x86 CLI.

**Comment by dsplaisted** [comment]
Who it's the "you" that needs to change the path?  I wouldn't expect developers using VS to have to change the PATH environment variable when they switch configurations.

**Comment by livarcocc** [comment]
If so, then it is an issue that should be tracked somewhere on the VS side. The CLI itself does not go looking for an x86 installation (or x64) of itself in the disk to satisfy the configuration for your project. It is impossible for the CLI to find these other installations. So, it becomes a responsibility of the user to pick the right one.

Granted, we could, maybe do something in VS, but if that's the case, this is the wrong repo to track that.
