### ISSUE TITLE
dotnet run cannot run in background on Linux

### ISSUE THREAD

**Issue by svick** [dotnet/cli#6216]
## Steps to reproduce

1. `dotnet new console`, `dotnet restore`
2. `dotnet run &`
3. `jobs`
4. `fg`

## Expected  behavior

`dotnet run` runs even while it's in the background, `fg` is not necessary to make it run.

## Actual behavior

`dotnet run` does not run in background. `jobs` shows that it's stopped, `fg` is necessary to make it run.

`dotnet myapp.dll &` works fine (contrary to what [this SO question](http://stackoverflow.com/q/42736585/41071) says).

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
@ellismg Can you help me understand why this would happen? dotnet run basically resolves what is the command to run the application (likely dotnet.exe <path_to_dll>) and creates a new process to run that command.

Any idea why that would put that process on hold? I imagine it is some interaction with the ProcessStartInfo. Can you give me a pointer on how to address this issue?

**Comment by ellismg** [comment]
Not sure off the top of my head, /cc @stephentoub @janvorli in case they have theories.

**Comment by janvorli** [comment]
I am looking at it - I can see that the second process is
```
dotnet exec /home/janvorli/dotnet/sdk/1.0.1/MSBuild.dll /m /v:m /home/janvorli/dotnet/test/test.csproj /nologo /verbosity:quiet /Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/home/janvorli/dotnet/sdk/1.0.1/dotnet.dll
```
I believe that for some reason, the process is trying to read from stdin, since if I run it with stdin redirected from a file, it runs in background just fine.

**Comment by janvorli** [comment]
I can also see that it was already running some managed code in the process, there are two threads with managed call stack:
```
00007F7374FF6800 00007F739E21ACB5 System.Threading.WaitHandle.WaitAny(System.Threading.WaitHandle[], Int32, Boolean)
00007F7374FF6840 00007F739EC67D32 Microsoft.Build.BackEnd.InProcNode.Run(System.Exception ByRef)
00007F7374FF68B0 00007F739ECEC7A3 Microsoft.Build.BackEnd.NodeProviderInProc+<>c__DisplayClass29_0.<InstantiateNode>b__0()
00007F7374FF68D0 00007F739E219E71 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```
and
```
00007F7377FFC6C0 00007F739E21A98D System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean)
00007F7377FFC6E0 00007F739E21A8BD System.Threading.WaitHandle.WaitOne(System.TimeSpan, Boolean)
00007F7377FFC710 00007F739E21A931 System.Threading.WaitHandle.WaitOne(System.TimeSpan)
00007F7377FFC730 00007F739F062ED3 Microsoft.ApplicationInsights.Channel.InMemoryTransmitter.Runner()
00007F7377FFC770 00007F739E2699C6 System.Threading.Tasks.Task.Execute()
00007F7377FFC7A0 00007F739E219E71 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
00007F7377FFC7F0 00007F739E269FC7 System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
00007F7377FFC8B0 00007F739E269CE8 System.Threading.Tasks.Task.ExecuteEntry(Boolean)
00007F7377FFC8D0 00007F739E219E71 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

```

**Comment by janvorli** [comment]
Actually, running under strace, it shows
```
[pid 29537] ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
[pid 29537] ioctl(0, SNDCTL_TMR_START or SNDRV_TIMER_IOCTL_TREAD or TCSETS, {B38400 opost isig -icanon -echo ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
[pid 29537] --- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
[pid 29565] --- stopped by SIGTTOU ---
```
That means it was stopped due to trying to set console settings using the ioctl on the STDIN_FILENO.

So I've tried to attach the debugger again to the process when it was stopped waiting for becoming foreground and finally realized what's causing the issue. It was not obvious when I've looked at the stack trace of the main thread before. So, here is the stack trace:
```
#0  0x00007ffff6ec38a3 in __GI_tcsetattr (fd=0, optional_actions=0, termios_p=0x7fffef03e688) at ../sysdeps/unix/sysv/linux/tcsetattr.c:55
#1  0x00007ffff6e0f259 in __run_exit_handlers (status=0, listp=0x7ffff71916c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#2  0x00007ffff6e0f2a5 in __GI_exit (status=<optimized out>) at exit.c:104
#3  0x00007ffff6df4ecc in __libc_start_main (main=0x40b770 <main>, argc=9, argv=0x7fffffffe3d8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe3c8) at libc-start.c:321
#4  0x0000000000409784 in _start ()
```
The process is already exiting, and it is running a handler installed by `atexit`. And the handler is calling tcsetattr on the STDIN_FILENO. Due to the fact that tcssetattr was tailcalled, it is not obvious that this is the atexit handler that we install in SystemNative_InitializeConsole. 
And here is the handler:
```C++
static void UninitializeConsole()
{
    // Put the attributes back to what they were when the console was initially initialized
    if (g_haveInitTermios)
        tcsetattr(STDIN_FILENO, TCSANOW, &g_initTermios); // ignore any failure
}
```
As you can see, it is setting attributes on the STDIN_FILENO and that's what puts the process running in background to stopped mode.

**Comment by janvorli** [comment]
CC: @stephentoub
