### ISSUE TITLE
Install SDK Error in Windows 10

### ISSUE THREAD

**Issue by jQuery2DotNet** [dotnet/cli#6218]
## Steps to reproduce
Download latest version dotnet-dev-win-x64.1.0.1.exe
Also installed VC++ redistributable vc_redist.x64.exe

I try clear %temp% folder. still got same error.

## Error
Error 0x80070570: The file or directory is corrupted and unreadable.

![image](https://cloud.githubusercontent.com/assets/11452784/24578203/510fa5ec-16f9-11e7-9f0b-603728eb52bb.png)

Log file
[.NET_Core_SDK_1.0.1_(x64)_20170401162617.txt](https://github.com/dotnet/cli/files/887557/default.NET_Core_SDK_1.0.1_.x64._20170401162617.txt)

**Comment by livarcocc** [comment]
Have you tried re-downloading the installer? It seems like the installer file is in a bad state.

**Comment by jQuery2DotNet** [comment]
Yes I already do that still that issue face. Lot's of try, after I install vs 2017 the issue is resolve.

**Comment by livarcocc** [comment]
It seems like there was something wrong with the file you downloaded. The one in VS is the same one we have linked in our download pages. Please, re-activate if you still run into this issue.
