### ISSUE TITLE
Q: how can I include additional files in dotnet publish?

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/cli#6219]
Hi,

I've noticed that ever since **project.json** has gone with the wind, I'm having trouble publishing my XML documentation for swagger.

The documentation file is generated during the build `My.Api.dll` --> `My.Api.dll.xml`, and the newly generated file appears in the build output directory.

I'd like to be able to automatically publish it with **dotnet publish** , I'm assuming that changes are needed to my **.csproj** file, but I'm not sure how to approach this. 

Can anyone offer advice?

**Comment by dasMulli** [comment]
There is an issue for publishing the documentation logged at https://github.com/dotnet/sdk/issues/795

The best workaround at the moment is described in https://github.com/dotnet/sdk/issues/795#issuecomment-289782712

**Comment by livarcocc** [comment]
We are tracking this in the SDK side.
