### ISSUE TITLE
How to deploy my ASP.NET application in Visual Studio for Mac preview?

### ISSUE THREAD

**Issue by SkymanOne** [dotnet/cli#6220]
I want deploying my ASP.NET MVC application, how can I do in visual studio for Mac preview?

**Comment by livarcocc** [comment]
@richlander can you help route this to the VS for MAC guys?

**Comment by livarcocc** [comment]
https://blog.xamarin.com/publish-azure-visual-studio-mac/?utm_source=vs_developer_news&utm_medium=referral
