### ISSUE TITLE
Have 2 versions of dotnet core along side each other - Ubuntu 16.10

### ISSUE THREAD

**Issue by Foroughi** [dotnet/cli#6226]
## Steps to reproduce
I am working on 2 projects. the both were using  Dotnet Core version 1.0.0-preview2-1-003177. Till last day I upgraded on of them to use 1.0.1 and now the just the upgraded one is working. Seems when I want to use dotnet build command for the other one, its looking for a .csproj file which it hasn't any. in the mean time my coworker is using windows 10 and he has no problem but I`m using Ubuntu 16.10.

I dont know what kinda information you need, but I can provide, just ask me.

**Comment by livarcocc** [comment]
If you want to use a different version of the CLI (other than latest) in your project, you need to add a global.json somewhere up in your directory structure pinning the version of the CLI.

We do not recommend you having multiple projects that interact with each other using different versions of the CLI. But if these are, say, separate repos, that should be ok.

You can add a file called global.json with the following contents:
```
{
  "sdk": {
    "version": "1.0.0-preview2-003177"
  }
}
```

This will pin the version of the CLI for any projects in a folder below the one containing the file to the version specified above.
