### ISSUE TITLE
Trying to add /v:diag to dotnet add package results in a stack trace

### ISSUE THREAD

**Issue by billwert** [dotnet/cli#6236]
## Steps to reproduce
dotnet add package netwonsoft.json /v:diag

## Expected  behavior
Verbose output or a reasonable error

## Actual behavior
System.NotSupportedException: The given path's format is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at Microsoft.DotNet.Tools.MsbuildProject.GetProjectFileFromDirectory(String projectDirectory)
   at Microsoft.DotNet.Tools.Add.PackageReference.AddPackageReferenceCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Add.AddCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview1-005685)

Product Information:
 Version:            2.0.0-preview1-005685
 Commit SHA-1 hash:  1f8b86d268

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15061
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   E:\work\dotnets\2.0.0-preview1-005685\sdk\2.0.0-preview1-005685\

**Comment by livarcocc** [comment]
Now, you get an error saying that /v:diag project was not found and the help for the command is displayed, where no indication of msbuild additional params is shown.

```
dotnet add package netwonsoft.json /v:diag
Could not find project or directory `/v:diag`.
.NET Add Package reference Command

Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

Arguments:
  <PROJECT>        The project file to operate on. If a file is not specified, the command will search the current directory for one.
  <PACKAGE_NAME>   The package reference to add.

Options:
  -h, --help                                Show help information
  -v, --version <VERSION>                   Version for the package to be added.
  -f, --framework <FRAMEWORK>               Adds reference only when targeting a specific framework.
  -n, --no-restore                          Adds reference without performing restore preview and compatibility check.
  -s, --source <SOURCE>                     Specifies NuGet package sources to use during the restore.
  --package-directory <PACKAGE_DIRECTORY>   Restores the packages to the specified directory.
```
