### ISSUE TITLE
dotnet restore doesn't restore package for projects with dependencies

### ISSUE THREAD

**Issue by jmezach** [dotnet/cli#6239]
## Steps to reproduce
* Create a new Solution in VS2017
* Add two projects to the solution (doesn't seem to matter what type of projects)
* Add a project dependency from one to the other (right click project -> Build Dependencies -> Project dependencies and mark the checkbox)
* Close Visual Studio
* Clear out the bin/obj folders for both projects
* Run dotnet restore from the folder containing the solution

## Expected  behavior
Packages for both projects are restored.

## Actual behavior
Only the packages for the project that doesn't have a project dependency is restored. Here's the output of dotnet restore for a project created as described above (containing a Class Library and ConsoleApplication project, where ConsoleApplication1 has a project dependency on ClassLibrary1):

```
Restoring packages for C:\Projects\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj...
Generating MSBuild file C:\Projects\ConsoleApp1\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.g.props.
Generating MSBuild file C:\Projects\ConsoleApp1\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Projects\ConsoleApp1\ClassLibrary1\obj\project.assets.json
Restore completed in 1,41 sec for C:\Projects\ConsoleApp1\ClassLibrary1\ClassLibrary1.csproj.

NuGet Config files used:
    C:\Users\jmezach\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by dasMulli** [comment]
Seems to be the same as https://github.com/NuGet/Home/issues/4578 and https://github.com/dotnet/cli/issues/6158

**Comment by jmezach** [comment]
Yeah, looks like it. Didn't think to look in the NuGet repo. It says in NuGet/Home#4578 that it has been fixed. Any idea when that will be released?

**Comment by livarcocc** [comment]
We will likely get it in the next NuGet insertion in the CLI.
