### ISSUE TITLE
Add --ilcsdkpath support for native compilation

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#624]
This will enable to consume a custom build of ILCompiler.SDK when compiling an app.

Associated with PR: https://github.com/dotnet/cli/pull/622

**Comment by schellap** [comment]
We are already using the recently built ILC SDK in our build system in the project.json and issuing a publish on the just built SDK. Why is this an issue in the first place and why is this change necessary?

**Comment by schellap** [comment]
If you want to have a cross compiler, this is not the right fix. We should relayout the package such that when we issue publish (with @brthor 's support to publish) we end up with the following structure:

x64\<ILC SDK contents>
x64_arm64\<ILC SDK contents>

**Comment by gkhanna79** [comment]
Fixed (see PR referenced above).
