### ISSUE TITLE
New 'create' command that works like dotnet new <argument> -o <path>

### ISSUE THREAD

**Issue by lambdakris** [dotnet/cli#6240]
After using the dotnet cli for a couple of months, I can't help but feel that it would be more productive to have an explicit command for creating a project/sln along with the directory, essentially an alias to dotnet new <argument> -o <path>.

It just feels more natural (and consistent with git, npm, and other cli tools) to have explicit and separate commands for creating a project with a directory and for initiating a project in an existing directory. I suppose that dotnet new will have to serve as the init command...though I would prefer dotnet init...so adding a dotnet create command would do nicely.

**Comment by livarcocc** [comment]
It is not clear to me exactly what you are asking for. How would this init command work? What would be its parameters? What is the delta between it and dotnet new?

**Comment by dsplaisted** [comment]
I think the idea is that today, you might do something like this to create a project in a solution:

```
mkdir MyProject
cd MyProject
dotnet new console
cd ..
dotnet new sln
dotnet sln add MyProject\MyProject.csproj
```

It would be easier if you could do this instead:

```
dotnet new console -n MyProject
dotnet new sln
dotnet sln add MyProject\MyProject.csproj
```

This would involve changing the behavior so that if the `-n` option is specified, then a folder with that name is created and the project is placed in that folder.  As this would be a change in the behavior, we could consider instead adding a new switch that behaved this way.

**Comment by livarcocc** [comment]
@dsplaisted We have -o for that.

```
dotnet new console -o MyProject
dotnet new sln
dotnet sln add MyProject/MyProject.csproj
```

**Comment by lambdakris** [comment]
I might have muddled things up a bit by mentioning init. What I was essentially going for was that rather than using `dotnet new console -o MyProject`, for whatever reason, I get the feeling that `dotnet create console MyProject` is more cli idiomatic. It seems more intuitive to have one command for creating a directory AND project, and another command for creating a project IN an existing directory, than having a single command that will do one or the other depending on switches/options... does that make sense?

**Comment by livarcocc** [comment]
I have a hard time understanding what exactly is the problem that you are trying to solve here. I would rather keep new as is and don't add a new command. We actually want to keep the number (built-in) of commands on the CLI limited. And I think this is a command that would add very little.

The -o is very consistent with all the other commands in the CLI that allow you to set the output directory for the command, so I think that's something the CLI users are comfortable with.
