### ISSUE TITLE
`dotnet cache` renames

### ISSUE THREAD

**Issue by bleroy** [dotnet/cli#6243]
- [ ] Rename `dotnet cache` command to `dotnet store`, and the `packages` folder to `store`.
- [ ] Rename `-e|--entries` to `-m|--manifest`.
- [ ] The description of the command becomes "Stores the specified assemblies for the .NET Platform. By default, these will be optimized for the target runtime and framework."
- [ ] The description of the `manifest` option (previously `entries`) becomes "The XML file that contains the list of packages to be stored."
- [ ] The description of the `output` option becomes "Output directory in which to store the given assemblies."
- [ ] Rename the `%DOTNET_SHARED_PACKAGES%` environment variable to `%DOTNET_SHARED_STORE%`.

**Comment by eerhardt** [comment]
I'm working on this now.
