### ISSUE TITLE
Rename publish filter option to manifest

### ISSUE THREAD

**Issue by bleroy** [dotnet/cli#6244]
Rename `dotnet publish --filter` to `dotnet publish --manifest`. The description of the `manifest` option (previously `filter`) becomes "The name of the target manifest, or the path to a target manifest file that contains the list of packages to be excluded from the publish step."

**Comment by eerhardt** [comment]
I'm working on this now.

**Comment by eerhardt** [comment]
@bleroy - one correction above:

> "The name of the target manifest, or the path to a target manifest file that contains the list of packages to be excluded from the publish step."

becomes

> "The path to a target manifest file that contains the list of packages to be excluded from the publish step."

Since the core publish logic doesn't support named manifests in 2.0

**Comment by eerhardt** [comment]
Closed with #6270

**Comment by bleroy** [comment]
It should have been manifest to be consistent with `dotnet store`. Modified title and description. Sorry about that.
