### ISSUE TITLE
Possible bug in serializer

### ISSUE THREAD

**Issue by kenjorgensen** [dotnet/cli#6247]
## Steps to reproduce
class that overloads the square bracket operator
class A {
   public B this[Bkey key] {
        get {return MyFunc(key); } 
   }
}
...
var a = new A();
db.Insert(a);

## Expected  behavior
I would expect the serialize to overlook this property by default.

## Actual behavior
Member by the name "Item" is added into the list of members.
An error is thrown ".net operation could destabilize the runtime"
BsonMapper.Serialize.cs
near line 167 
"var value = member.Getter(obj)"

## Fix
added BsonIgnore Attribute to operator

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This does not belong in the CLI repo. I believe this belong in a mongodb repo.
