### ISSUE TITLE
Tarball packages should only contain one folder in top level

### ISSUE THREAD

**Issue by guoxiao** [dotnet/cli#6250]
## Expected  behavior
Traditionally the tarball should only contains a folder of same name in the top level. Thus user can `tar xvf xxx.tar.gz` directly without polluting working directory.

If a tarball has many folder/files in the top level, it's often called [Tarbomb](https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb) and would overwrite user files or pollute working directory if user run `tar xvf` on it.

## Actual behavior
The tarball of dotnet cli has more than many folders/files in the top level

**Comment by livarcocc** [comment]
We can't change these now and we have produced the tarballs like this for months and people are already relying on them having this format. Changing it now would potentially break a lot of people.
