### ISSUE TITLE
bug with dotnet run --project with webapi and appsettings.json file

### ISSUE THREAD

**Issue by jmzagorski** [dotnet/cli#6251]
## Steps to reproduce
```
mkdir test
dotnet new webapi
dotnet restore
dotnet build
cd ..
dotnet run --project .\test\test.csproj
```

## Expected  behavior
the framework should use the appsettings.json file from the project directory  `%userprofile%\Source\Workspaces\test\appsettings.json' ` and not the directory from where` dotnet run `is ran

## Actual behavior
Error thrown:
`Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is %userprofile%\Source\Workspaces\appsettings.json' ` Notice that this is not the path where the webapi was created (also, I changed the path to %userprofile%). 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by dasMulli** [comment]
You can configure any path to an appsettings file when using a `ConfigurationBuilder`, the default for relative paths is looking at the current working directory.
`dotnet run` doesn't change the working directory by default, but you can edit your csproj file to enforce the project directory as working directory by using this inside a `<PropertyGroup>`:
```xml
<RunWorkingDirectory>$(MSBuildThisFileDirectory)</RunWorkingDirectory>
```

**Comment by jmzagorski** [comment]
okay I got it working now. Sorry for the confusion. I guess I never realized that happens with the old CLI and project.json too, but I never would have known about the MSBuild property (not too familiar with MSBuild and csproj files yet). Thanks!
