### ISSUE TITLE
`dotnet restore` does not restore packages of projects with dependencies in .sln file

### ISSUE THREAD

**Issue by hach-que** [dotnet/cli#6258]
## Steps to reproduce
- Create a solution with two .NET Standard projects
- In the solution file, specify dependencies e.g.:
```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "HiveMP.Test.Framework", "HiveMP.Test.Framework\HiveMP.Test.Framework.csproj", "{ED0EB86B-502C-4523-B24F-564620359721}"
	ProjectSection(ProjectDependencies) = postProject
		{F6D6B937-3689-443F-BD20-FE4F7C5E9FCD} = {F6D6B937-3689-443F-BD20-FE4F7C5E9FCD}
		{0F934DF0-7B27-4192-96C5-BE4F81594175} = {0F934DF0-7B27-4192-96C5-BE4F81594175}
	EndProjectSection
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "HiveMP.ClientGenerator", "HiveMP.ClientGenerator\HiveMP.ClientGenerator.csproj", "{0F934DF0-7B27-4192-96C5-BE4F81594175}"
EndProject
```
- Run `dotnet restore`.

## Expected  behavior
- `dotnet restore` should restore packages for `HiveMP.Test.Framework`.
- The `obj` folder inside `HiveMP.Test.Framework` with `project.assets.json` should exist.

## Actual behavior
- `dotnet restore` doesn't process `HiveMP.Test.Framework`, packages aren't restored.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by hach-que** [comment]
To clarify, we specify dependencies here because `HiveMP.Test.Framework` has a Prebuild step which runs `HiveMP.ClientGenerator` to create C# source files.

Both package restore and build for both these projects works fine in Visual Studio 2017, but doesn't work on the `dotnet` CLI (under either Windows or Linux).

**Comment by hach-que** [comment]
For some reason, removing and re-adding the project dependencies in Visual Studio changed all the project type guids in the solution from `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` to `9A19103F-16F7-4668-BE54-9A1E7A4F7556`.  However, `dotnet restore` still doesn't work in this case.  The only way to make `dotnet restore` is to remove the `ProjectDependencies` section from the solution.

**Comment by hach-que** [comment]
So I tried using ProjectReferences in the `HiveMP.Test.Framework` project instead of ProjectDependencies in the solution, like so:

```
  <ItemGroup>
    <ProjectReferenceWithConfiguration Include="..\hivemp\HiveMP.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReferenceWithConfiguration>
    <ProjectReferenceWithConfiguration Include="..\HiveMP.ClientGenerator\HiveMP.ClientGenerator.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReferenceWithConfiguration>
  </ItemGroup>
```

(I also tried `ProjectReference` instead of `ProjectReferenceWithConfiguration`).  This is the recommended way of doing build-time (but not runtime) dependencies as per this MSDN article: https://blogs.msdn.microsoft.com/kirillosenkov/2015/04/04/how-to-have-a-project-reference-without-referencing-the-actual-binary/

However, in .NET Core this doesn't due to the `GetNearestTargetFramework` in `Microsoft.NET.Sdk.Common.targets`, which causes this error:

```
       "C:\Users\June\Documents\Projects\hivemp\hivemp.build.sln" (Publish target) (1) ->
       "C:\Users\June\Documents\Projects\hivemp\HiveMP.Test.Framework\HiveMP.Test.Framework.csproj" (Publish target) (17) ->
       "C:\Users\June\Documents\Projects\hivemp\hivemp\HiveMP.csproj" (GetTargetFrameworkProperties target) (2:2) ->
       (GetTargetFrameworkProperties target) ->
         C:\Program Files\dotnet\sdk\1.0.1\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(73,5): error : Project 'C:\Users\June\Documents\Projects\hivemp\hivemp\HiveMP.csproj' targets '.NETCoreApp,Version=v1.1'. It cannot be referenced by a project that targets '.NETStandard,Version=v1.6'. [C:\Users\June\Documents\Projects\hivemp\hivemp\HiveMP.csproj]
```

Even though this kind of check isn't required because it isn't referencing the output assembly.

The workaround is to make the library a .NET Core library instead of .NET Standard so that this check passes, but preferrably that should not be required.

**Comment by hach-que** [comment]
**So for anyone else running into this issue, this is what I ended up with.**

This allows you to have a .NET Core project whose source code files are generated from another .NET Core project in the same solution.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" DependsOnTargets="ResolveProjectReferences">
    <Exec Command="dotnet &quot;$(SolutionDir)HiveMP.ClientGenerator/bin/$(Configuration)/netcoreapp1.1/HiveMP.ClientGenerator.dll&quot; self-generate $(Configuration)" />

    <ItemGroup>
      <Compile Include="GeneratedClientApis\*" />
    </ItemGroup>
  </Target>

  <ItemGroup>
    <ProjectReferenceWithConfiguration Include="..\hivemp\HiveMP.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReferenceWithConfiguration>
    <ProjectReferenceWithConfiguration Include="..\HiveMP.ClientGenerator\HiveMP.ClientGenerator.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReferenceWithConfiguration>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
  </ItemGroup>

</Project>
```

Important points are:
- The project references must be a compatible framework (i.e. you can't have a .NET Standard library reference a .NET Core project, even with `ReferenceOutputAssembly` set to `false`).
- The prebuild target must have the signature of `Target Name="PreBuild" BeforeTargets="PreBuildEvent" DependsOnTargets="ResolveProjectReferences"`.  This ensures the prebuild step runs after project references have built (which we want to so that we can actually run the program that's going to generate code).
- The generated files then need to be manually included with `<Compile>` in an `ItemGroup` as part of that target, as whatever mechanism scans the project directory to auto-include files runs before this point and thus otherwise the generated files won't be included in the Csc compiler task.

Hopefully this helps someone else in the same situation.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4992

**Comment by thomaslevesque** [comment]
@livarcocc the NuGet issue you created seems to be for a different problem. What about the solution-level dependency problem? Will it be fixed?
