### ISSUE TITLE
.Net Core 1.0.4 mislabeled 1.0.3

### ISSUE THREAD

**Issue by Mattacks** [dotnet/cli#6260]
## Steps to reproduce
Download .Net Core 1.0.4 from main landing page
Install
Accept EULA

## Expected  behavior
UAC control dialog pops up - says it is 1.0.4

## Actual behavior
UAC control dialog pops up - says it is 1.0.3

**Comment by livarcocc** [comment]
Can you provide a link to what you are downloading and installing? I mean, is it  a link to the 1.0.1 SDK or to the 1.0.4 shared framework?

**Comment by Mattacks** [comment]
It's from here https://www.microsoft.com/net/download/core#/runtime
NET Core 1.0.4 runtime (LTS)
Windows (x64) Installer
.exe download
Copy of download link: https://go.microsoft.com/fwlink/?linkid=843412

If you choose to run as administrator you see the error straight away

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#1975
