### ISSUE TITLE
[E2EBlocking] On a machine with clean install of Dev15.3, Fail to load project when you migrate Dev14 xproj web -ASP.NET Core Web Application (.NET Core/.NET Framework) -1.0

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#6262]
## Install Steps
1. Clean machine: Win10 x64 ENU 
2. Install Dev15.3 VSE vsuwpt.26403.01 (includes CLI 2.0.0-preview1-005673)
3. Manually install .NET Core 1.0.4 runtime from https://www.microsoft.com/net/download/core#/runtime

## Steps to reproduce
1. Open Team Explorer, clone the Git repo in VS
    [ProjectKTestProjects](https://github.com/balaTest/ProjectKTestProjects)
2. Select and open solution using VS
Dev14_K101/Tooling202/AspNetCoreWeb_IndAuth_WithAI_1 OR
Dev14_K101/Tooling202/AspNetCoreWeb_OnNet452_IndAuth_1 OR
Dev14_K101/Tooling202/ConsoleApp_Core_1

## Expected  behavior
Able to open and migrate solution from xproj to csproj

## Actual behavior
Migration failed with the error shown below. Same error if I try this from the command-line as well

![image](https://cloud.githubusercontent.com/assets/8246794/24769131/2e9e585e-1aba-11e7-97bc-fd13ef508ac5.png)

![image](https://cloud.githubusercontent.com/assets/8246794/24769138/3a267922-1aba-11e7-931b-931a8ba51ab5.png)

**Comment by livarcocc** [comment]
@wli3 is this something that you can take a look at? I can explain to you how the scenario is supposed to work.
