### ISSUE TITLE
How to create .Net Native output

### ISSUE THREAD

**Issue by dibyendumajumdar** [dotnet/cli#6264]
Hi,

I have a command line application written in .Net Core (server app using Grpc, etc.). I would like to create a .Net Native executable but I cannot find how to do this. I am using Visual Studio 2017 on Windows 10. All instructions for .Net Native I can find appear to be related to UWP apps.

Thanks and Regards
Dibyendu

**Comment by livarcocc** [comment]
Native is not supported by .NET Core at the moment.
