### ISSUE TITLE
Failure to restore packages from file share in Linux in docker

### ISSUE THREAD

**Issue by MortenChristiansen** [dotnet/cli#6269]
## Steps to reproduce
On Windows 10 host machine:
* Create new .net core console application.
* Change it to target `net461`. This should not be necessary but was required by the nuget package I referenced.
* Add a nuget reference from a custom package feed served from a file share (simple nuget files, nothing else)
* Run `dotnet restore` to observe that it works on the host machine
* Run `docker run -it --rm -v "$pwd\:/sln" microsoft/aspnetcore-build:latest` in powershell from the root folder.
* Run `cd sln` in docker.
* Run `dotnet restore -s //uvd-fs1.uvd.local/Install/UVPackages` in docker
   * Replace the network path with a path to a valid folder containing the nuget package.
   * Note that I'm no Linux expert. I have tried a bunch of different network path formats in case this one was actually not supported, but it might just have been that I missed the correct one. However, I could find no resource describing how to do this anywhere.

## Expected  behavior
The package gets restored.

## Actual behavior
This error: `/usr/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Failed to retrieve information about 'UVDiagnostics.Client.Logging' from remote source '/uvd-fs1.uvd.local/Install/UVPackages'. [/sln/ConsoleApp3.sln]`

## Environment data
I'm running the newest Docker for Windows version if it has anything to do with that.

`dotnet --info` output: (inside docker)

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
root@2bffb03ed384:/sln#
```

**Comment by MortenChristiansen** [comment]
A bit more context: http://stackoverflow.com/questions/43139342/how-to-restore-nuget-packages-from-network-share-in-linux-docker-container

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#4998
