### ISSUE TITLE
New mstest project are packaged by 'dotnet pack' by default

### ISSUE THREAD

**Issue by mockjv** [dotnet/cli#6272]
## Steps to reproduce
- Create a new mstest project and add it to a solution
- Run dotnet pack

## Expected  behavior
Would expect a brand new unit test project to either:

1. Not attempt to build a nuget package for unit tests (not immediately sure of the best way this should happen)
or
2. Not produce the warnings

## Actual behavior
[output.txt](https://github.com/dotnet/cli/files/906950/output.txt)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.2)

Product Information:
 Version:            1.0.2
 Commit SHA-1 hash:  54743c8b7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.2

**Comment by livarcocc** [comment]
I don't think pack is doing anything wrong in this case. Your project has valid issues from the pack point of view and it is telling you so.

As for the unit test project, it is not meant to be packaged, and so you get warnings when you try to do so.

What is the scenario that you are trying that you would need to do something like this?

**Comment by mockjv** [comment]
So, for example, I create the following typical project space:

- MySolution.sln
  - MyProbject
    - MyProject.csproj
  - MyProject.Test
    - MyProject.Test.csproj
  - MyProject2
    - MyProject2.Test.csproj

So in this case, if I were to attempt a `dotnet pack` against the solution, I end up with the unit tests packed as well.  Upon thinking about it further, I completely agree that the warnings are perfectly valid but maybe some means of indicating that a project should not be packed could be useful?

As of right now, what I see as by best option is to run `dotnet pack` in each of the projects where I actually want a nuget package produced:
`cd MySolution/MyProject`
`dotnet pack -o C:\LocalPackages`
`cd ..\MyProject2`
`dotnet pack -o C:\LocalPackages`

**Comment by livarcocc** [comment]
Hum, looking at the code, I can see that we have IsPackable property that you can set to prevent your project from being packaged.

However, this property should be set to false automatically for you in the case of TestProjects. I wonder if in the sln case, the test project is not being identified as such appropriately. I will try a local repro here and will collect logs and direct the issue as appropriate.

**Comment by mockjv** [comment]
Now that I know what I'm looking for, it looks like there's been some back and forth as to whether IsPackable=false should be set by default for unit test projects:

[Unit test project templates should set IsPackable as false](https://github.com/Microsoft/vstest/issues/380)
[Add IsPackable=false to test project templates](https://github.com/dotnet/templating/issues/376)

I could potentially see arguments both ways in that regard but I could definitely agree that defaulting to the most common scenario, whichever way that may be, would make the most sense.

**Comment by livarcocc** [comment]
Given that there are conversations going on about this already in different repos, I am closing this issue that we can unify the talks. Please re-activate if there is anything else you want to discuss that is a CLI concern.
