### ISSUE TITLE
SCD for rhel 7.3 and 7.4 does not contain executable (but rhel 7.2 does)

### ISSUE THREAD

**Issue by Knacktus** [dotnet/cli#6273]
## Steps to reproduce
`dotnet new console`

Modify *.csproj file
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <RuntimeIdentifiers>rhel.7.3-x64;rhel.7.2-x64;rhel.7.4-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```

```
dotnet restore
dotnet publish -c Release -r rhel.7.3-x64
dotnet publish -c Release -r rhel.7.4-x64
dotnet publish -c Release -r rhel.7.2-x64
```

## Expected  behavior
`bin\Release\netcoreapp1.1\rhel.7.3-x64` respectivly  `bin\Release\netcoreapp1.1\rhel.7.4-x64` should contain an executable file,

## Actual behavior
There's not executable file in `bin\Release\netcoreapp1.1\rhel.7.3-x64` respectivly  `bin\Release\netcoreapp1.1\rhel.7.4-x64`, but in `bin\Release\netcoreapp1.1\rhel.7.2-x64`.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.2)

Product Information:
 Version:            1.0.2
 Commit SHA-1 hash:  54743c8b7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.2

**Comment by tmds** [comment]
You can publish for `rhel.7-x64`. Minor versions of RHEL are binary compatible.

**Comment by tmds** [comment]
PR to remove the minors from the rid catalog doc: https://github.com/dotnet/docs/pull/1863.

**Comment by livarcocc** [comment]
Closing this issue. If the Rid without minor version does not work for you, please re-activate this issue.
