### ISSUE TITLE
Add option to not restore on `dotnet add`

### ISSUE THREAD

**Issue by sayedihashimi** [dotnet/cli#6274]
I'm in the process of updating a project from an old version. I created a new `.csproj` and then started adding references one by one using `dotnet add`. It's inconvenient that restore is getting called automatically. It would be better to have an option for this. I'd rather add all my dependencies, review the changes, and then call `dotnet restore` on my own.

**Comment by sayedihashimi** [comment]
Now I'm seeing that there is an option to skip the restore. It looks like the syntax to see that included in help is `dotnet add package -h`. From the help output of `dotnet add -h` it's not clear that `dotnet add package -h` would work.

```
PS /Users/sayedhashimi/temp/dotnetnew/PgnViewerWeb> dotnet add -h
.NET Add Command

Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show help information

Commands:
  package <PACKAGE_NAME>   .NET Add Package reference Command
  reference <args>         .NET Add Project to Project reference Command
```

In the help output here it looks like my only "option" is `-h` and to get to the position where I specify the `[command]` it's after a required `<PROJECT>` parameter. I initially tried `dotnet add -h ./PgnViewerWeb.csproj package` which did work but felt very unnatural.

I wonder if we can just move `[options]` to the end in the usage output? If not, and we can't find a better way to convey this, I think it would be good to add an `Examples` section to the help output. For example the default help output could be updated to something like.

```
.NET Add Command

Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show help information

Commands:
  package <PACKAGE_NAME>   .NET Add Package reference Command
  reference <args>         .NET Add Project to Project reference Command

Examples:
  dotnet add package -h
  dotnet add package MyProject.csproj Newtonsoft.Json
```
```

**Comment by livarcocc** [comment]
@jonsequitur @wli3 I assigned you two here because of the help format conversations we have been having.

**Comment by livarcocc** [comment]
The first are options to the add command, while later on, you get options to the add subcommand (package, reference).

Going to keep this as is for now.
