### ISSUE TITLE
Where to find standalone installer for .NET Core SDK 1.0.2?

### ISSUE THREAD

**Issue by DreamingDevs** [dotnet/cli#6278]
## Steps to reproduce
I downloaded and installed latest VS 2017 Update 1. 
Version number : **15.1 (26403.0)**

## Expected  behavior
`dotnet --info` should show version as **1.0.1** as it is the latest version mentioned at .NET CLI Releases [here](https://github.com/dotnet/cli/releases).

## Actual behavior
After installation, when I do `dotnet --info` it is showing .NET SDK Version as **1.0.2**.
![image](https://cloud.githubusercontent.com/assets/5579127/24835062/f3fd6242-1d13-11e7-8f43-e644763dd07c.png)

I am not able to find 1.0.2 release.

**Comment by vcsjones** [comment]
What makes you think there should be a 1.0.2? I don't see an announcement for it, or a download for it.

**Comment by Thealexbarney** [comment]
@vcsjones Because it's the version currently being distributed with Visual Studio

**Comment by vcsjones** [comment]
@Thealexbarney Ah I see, I'm sorry I misunderstood at first. Yes, this is odd.

**Comment by livarcocc** [comment]
Yes, we missed releasing it outside of VS. We will correct this ASAP.

**Comment by devsko** [comment]
Todays VS update 15.1.26403.3 installed SDK 1.0.3
There is nothing about it in [VS release notes](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#15.1.26403.03). Latest standalone SDK version is still 1.0.1. Some kind of information would be great.

**Comment by DreamingDevs** [comment]
@felix-b, can you please let us know why this issue was closed? We are talking about updating [CLI Releases](https://github.com/dotnet/cli/releases) with new release versions.

**Comment by vcsjones** [comment]
@DreamingDevs This issue isn't closed. A closed issue was linked to this one.

**Comment by felix-b** [comment]
@DreamingDevs, I had a related issue for which I found a solution.

**Comment by DreamingDevs** [comment]
@vcsjones, @felix-b It was a mistake from my side that I thought this issue was closed and posted that comment. Sorry for inconvenience. I update my previous comment.

**Comment by leecow** [comment]
Latest CLI release tagged at https://github.com/dotnet/cli/releases/tag/v1.0.3 and all download locations updated. 

* https://www.microsoft.com/net/download/core
* https://github.com/dotnet/core/tree/master/release-notes
