### ISSUE TITLE
Get process description from dll info

### ISSUE THREAD

**Issue by benaadams** [dotnet/cli#6279]
Currently if you run a dotnet program with the shared host its listing in Task manager isn't particularly informative:

![image](https://cloud.githubusercontent.com/assets/1142958/24839744/3780ca9c-1d58-11e7-8b6b-5f72aa67e7dc.png)

They all look the same; with more and more adoption will get harder to distinguish between portable dotnet apps. 

It would be better if it took the description from the entry point dll. While I'm not sure if there is an api to change the running process name; svchost seems to manage it, so it may be possible:

![image](https://cloud.githubusercontent.com/assets/1142958/24839749/4675476c-1d58-11e7-981c-374f79131d45.png)

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2007
