### ISSUE TITLE
Fix target frameworks for Class Libraries

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#628]
Libraries should be targeting a version of `dotnet5.x` TFMS not `dnxcore50` or `dnx451`

/cc @piotrpMSFT @anurse @pakrym

**Comment by blackdwarf** [comment]
@davidfowl is this our "official" TFM as of now?

**Comment by davidfowl** [comment]
The official tfms will be netstandard when they come online. Dotnet5.x is the equivalent right now

**Comment by borgdylan** [comment]
Will the desktop TFMs still be available?

**Comment by davidfowl** [comment]
@borgdylan Not sure what you mean

**Comment by borgdylan** [comment]
Will the net451,net46 etc. TFMs be dropped from support? i.e. will the use of the reference assembly folders that get used by MSBuild be dropped?

**Comment by davidfowl** [comment]
No

**Comment by borgdylan** [comment]
That's great news. I made my mono fork include th4 env var that tells dotnet-compile where those assembly reside part of the boot-up scripts.

**Comment by brthor** [comment]
Delaying this until we have final TfM 
@ericstj @piotrpMSFT

**Comment by ericstj** [comment]
You could move the libs to `dotnet5.x` now, with the plan to move to `netstandard1.x` as soon as nuget adds support.
For the exes we need to wait for concensus on a new app TFM.

The rename from dnxcore > dotnet requires a human to select the right value.

The move from dotnet > netstandard and dnxcore50 > newapptfm are both find-replace.

**Comment by piotrpMSFT** [comment]
we are now on netstandard1.x. This is no longer needed.
