### ISSUE TITLE
dotnet test --list-tests ignored --logger parameter

### ISSUE THREAD

**Issue by kmcgain** [dotnet/cli#6280]
This may be a missing feature rather than an issue.

## Steps to reproduce
dotnet new xunit
dotnet restore
dotnet build
dotnet test --list-tests --logger trx

## Expected  behavior
A TestResults folder created with a single trx file that includes test definitions 

## Actual behavior
The parameter is ignored and the list is displayed in the program output

If trx file is not appropriate for listing the tests then an alternative output should be supported as the regular output is not easily parsable.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#702
