### ISSUE TITLE
The library 'libhostpolicy.so' required to execute the application was not found

### ISSUE THREAD

**Issue by aliakseimaniuk** [dotnet/cli#6281]
## Steps to reproduce
1) Create Console application
2) Publish to separate folder
3) Try to execute published application

.csproj file:
``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <ApplicationIcon />
    <OutputTypeEx>exe</OutputTypeEx>
    <StartupObject />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
    <PackageReference Include="NLog" Version="5.0.0-beta06" />
    <PackageReference Include="runtime.ubuntu.16.04-x64.Microsoft.NETCore.Runtime.CoreCLR" Version="1.1.1" />
    <PackageReference Include="System.Text.Encodings.Web" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```
Publish command:
```
dotnet restore
dotnet publish -c Release -o publish
```

## Expected  behavior
Application runs normally

## Actual behavior
The library 'libhostpolicy.so' required to execute the application was not found exception.
Reproducible on Windows 10 and Ubuntu 16.04

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)
Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

.NET Command Line Tools (1.0.2)
Product Information:
 Version:            1.0.2
 Commit SHA-1 hash:  54743c8b7b
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.2

**Comment by livarcocc** [comment]
This happens because you conditioned your application being an exe on having Config = Debug and you are publishing as Release.

If you want your app to always have the same output type, which is the common case, just move the OutputType declaration into the a unconditioned propertygroup, like the one with the TargetFramework and publish again.

**Comment by aliakseimaniuk** [comment]
@livarcocc Thank you, that helped.
