### ISSUE TITLE
Custom output path & runtime loaded assemblies (re: plugins)

### ISSUE THREAD

**Issue by xgalaxy** [dotnet/cli#6282]
I'm creating .net core app that uses mef to load plugin assemblies. I can't seem to figure out how to get all of the solution assemblies into the same folder so that I can debug loading of these assemblies at run time. To be clear, these plugin assemblies are not hard dependencies of the main application. So there are no project references in the csproj. This means these plugin assemblies are not output in the same folder as the host executable.

Under normal circumstances I could just set the OutputPath to be the same for each assembly. Something like ```..\bin\Debug``` would do it. And all assemblies and executables would end up in the same folder.

With .net core even if I do set a custom OutputPath the framework type is getting appended on the end (ex: ```..\bin\Debug\netcoreapp1.1```) making it impossible for me to use this as a solution for getting all assemblies output to the same folder.

**Comment by dsplaisted** [comment]
You can set `AppendTargetFrameworkToOutputPath` to and `AppendRuntimeIdentifierToOutputPath` to false to prevent the SDK from adding these to your output path.  Note that you probably don't want to do this for projects that target multiple frameworks or Runtime Identifiers, as their outputs would then write over each other.

**Comment by xgalaxy** [comment]
Awesome thank you. Yea, this would just be done for debug configuration. Release and Publishing will be a whole other can of worms I imagine.

**Comment by livarcocc** [comment]
Closing the issue. Re-activate if there is anything else you need.
