### ISSUE TITLE
Localization for CommonOptions.cs

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#6291]
The localization for [CommonOptions.cs](https://github.com/dotnet/cli/blob/0eff67d20768cff90eb125ff0e16e52cfc40ced6/src/dotnet/CommonOptions.cs#L21) is more complicated. All the common options are pulled out from subcommands, like [dotnet-msbuild](https://github.com/dotnet/cli/blob/cc80822c16b955a1f664f8a65ed2c76c3c52a824/src/dotnet/commands/dotnet-msbuild/LocalizableStrings.cs). The localization string should also move "up".

**Comment by nguerrera** [comment]
Can't we just put the strings in https://github.com/dotnet/cli/blob/master/src/dotnet/CommonLocalizableStrings.cs?
