### ISSUE TITLE
dotnet build fails when referencing a project converted to PackageReference

### ISSUE THREAD

**Issue by gulbanana** [dotnet/cli#6294]
This problem prevents us from performing continuous integration or scripted builds.

## Steps to reproduce
1. Clone https://github.com/gulbanana/repro-packagereference-transitive
2. `cd SdkProject`
3. `dotnet restore`
4. Build in Visual Studio
5. `dotnet build`

## Expected  behavior
Both the VS and commandline builds should succeed.

## Actual behavior
Commandline build fails with this error:
`FPClass.cs(5,16): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) [C:\code\repro-packagereference-transitive\FrameworkProject\FrameworkProject.csproj]`
It appears that the PackageReference isn't being resolved properly when built this way.

Visual Studio uses full-framework msbuild, so I also tried just running `msbuild`, which failed with a different error:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(178,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your pr oject.json and then re-run NuGet restore. [C:\code\repro-packagereference-transitive\FrameworkProject\FrameworkProject.csproj]
Seems misleading, since I don't have a project.json file.

## dotnet --info
.NET Command Line Tools (1.0.2)

Product Information:
 Version:            1.0.2
 Commit SHA-1 hash:  54743c8b7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.2

**Comment by gulbanana** [comment]
Note: if I replace the PackageReference with a project.json, `dotnet build` still fails, but full-framework `msbuild` succeeds. The msbuild -version is Microsoft (R) Build Engine version 15.1.1012.6693

**Comment by emgarten** [comment]
Add a ``<RuntimeIdentifier>win</RuntimeIdentifier>`` to your project to match what project.json required. I thought this was already fixed in the latest Visual Studio 15.1, but if not just provide the RIDs in the project.

For legacy csproj projects using PackageReference the errors still refer to project.json, however the same thing applies for the csproj file. Updating this is tracked here: https://github.com/NuGet/Home/issues/4778

**Comment by emgarten** [comment]
Also for non-NETCore SDK projects you will need to use full-framework msbuild.

**Comment by livarcocc** [comment]
Correct, CLI does not support old style csproj.

**Comment by gulbanana** [comment]
The problem with this is that nuget.exe doesn't support new style csproj - so neither dotnet pack nor nuget pack are usable. How are we to pack new style csproj with references to old style csproj?

**Comment by livarcocc** [comment]
@emgarten about nuget.exe not supporting new style csprojs.

**Comment by emgarten** [comment]
@rohit21agrawal for pack

**Comment by StingyJack** [comment]
If this is still happening to you...

1) close the solution
2) delete the .suo and DotSettings.user (if you have that one) files for the solution
3) delete the .csproj.user file for the project with the error

... and then reopen VS.

**Comment by gulbanana** [comment]
@StingyJack, none of that will help as the problem is a design issue rather than a transient bug. 

I'll go figure out what repository is appropriate to open an issue about how to pack this combination of project and we can leave this one closed.

**Comment by rohit21agrawal** [comment]
@gulbanana build related issues can either be filed at github.com/dotnet/sdk or github.com/dotnet/cli
