### ISSUE TITLE
sln add globbing patterns fail

### ISSUE THREAD

**Issue by gforceg** [dotnet/cli#6295]
This pertains to [dotnet/docs #1834](https://github.com/dotnet/docs/pull/1834#issuecomment-293291828)

Per [the documentation](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-sln) this should work.

It is not clear if this is a bug or a documentation problem.

## Steps to reproduce
Given the following file structure:

.
├── Api
│   ├── Api.csproj
│   ├── Controllers
│   └── wwwroot
├── complex-solution.sln
├── Data
│   └── Data.csproj
├── Domain
│   └── Domain.csproj
└── Logging
    └── Logging.fsproj

Add projects to my solution using blobs:
`dotnet sln complex-solution.sln add **/*`

## Expected  behavior

The output for the first task should look something like:

```
Project `Api/Api.csproj` added to the solution.
Project `Data/Data.csproj` added to the solution.
Project `Domain/Domain.csproj` added to the solution.
Project `Logging/Logging.fsproj` added to the solution.
```

## Actual behavior

Output from first task:

```bash
Project `Api/Controllers` does not exist.
Project `Api/obj` does not exist.
Project `Api/wwwroot` does not exist.
Project `Data/obj` does not exist.
Project `Domain/obj` does not exist.
Project `Logging/obj` does not exist.
.NET Add project(s) to a solution file Command

Usage: dotnet sln <SLN_FILE> add [options] [args]

Arguments:
  <SLN_FILE>  Solution file to operate on. If not specified, the command will search the current directory for one.

Options:
  -h|--help  Show help information

Additional Arguments:
 Add a specified project(s) to the solution.

```

The end result is that nothing is adde to the solution:

`dotnet sln complex-solution.sln list`
```
No projects found in the solution.
```
## Side note

The commands work fine when I substitute `**/*` with `**/*.{csproj,fsproj}`

## Environment data

`dotnet --info` output:
```bash
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     fedora
 OS Version:  24
 OS Platform: Linux
 RID:         fedora.24-x64
 Base Path:   /opt/dotnet/sdk/1.0.1
```

**Comment by gforceg** [comment]
an example application:
https://github.com/gforceg/dotnet-sln-issues-app

**Comment by gforceg** [comment]
Tried the above project using Windows 7 this time:

'dotnet sln complex-solution.sln add **/*`

```
Project `**/*` does not exist.
.NET Add project(s) to a solution file Command

Usage: dotnet sln <SLN_FILE> add [options] [args]

Arguments:
  <SLN_FILE>  Solution file to operate on. If not specified, the command will search the current directory for one.

Options:
  -h|--help  Show help information

Additional Arguments:
 Add a specified project(s) to the solution.
```

## Environment data
```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by gforceg** [comment]
The more I think about this, the more I think it is a documentation issue. Why should dotnet-sln-add accept files it isn't supposed to consume? A proper blob "**/*.{csproj,fsproj} is the way to go.

**Comment by Rudithus** [comment]
Is this issue being worked on?

**Comment by livarcocc** [comment]
Globbing is actually a feature of the shell and not of the CLI. For instance, you get globbing at bash, because bash implements it, we have no intention of adding our own globbing at the CLI.

**Comment by Rudithus** [comment]
Yes I've just tried it on bash and globbing is working fine.
It's weird because `ls **/*.csproj` command is working fine on powershell. I would have thought this mean it would work for dotnet cli aswel.
