### ISSUE TITLE
`dotnet --info` fails on osx.10.11-x64 with error "Symbol not found: _clock_gettime"

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/cli#6301]
This happens with dotnet-cli of version "2.0.0-preview1-005724"

## Steps to reproduce
```
dotnet --info
```

## Expected  behavior
Print the tool version and runtime environment information

## Actual behavior
```
PowerShells-MacBook:dotnet psbuildacct$ ./dotnet --info
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/psbuildacct/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview1-001913-00/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/psbuildacct/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview1-001913-00/libcoreclr.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
```

## Environment data
The dotnet-cli package was downloaded from:
https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005724/dotnet-dev-osx-x64.2.0.0-preview1-005724.tar.gz

**Comment by livarcocc** [comment]
2.0 CLI only supports osx.10.12. It no longer supports osx.10.11.

**Comment by daxian-dbw** [comment]
Got it. Thanks @livarcocc
