### ISSUE TITLE
dotnet init command to initialize NuGet properties

### ISSUE THREAD

**Issue by maartenba** [dotnet/cli#6305]
I've been blogging about a simple extension to the `dotnet` CLI over at https://blog.maartenballiauw.be/post/2017/04/10/extending-dotnet-cli-with-custom-tools.html. In essence, the tool (inspired by `npm init`) makes it easier to get started with creating NuGet packages from .csproj. It will walk you through initializing NuGet metadata in the current project. It only covers the most common items, and tries to guess sensible defaults.

Here's a screenshot of it in action:

![](https://blog.maartenballiauw.be/images/2017-04-10-extending-dotnet-cli-with-custom-tools/tool-in-action.png)

Would it make sense to open a PR that adds this functionality into `dotnet` by default? And if so, would it make sense to add a non-CSP fallback that generates a `.nupkg` instead?

Just thought of asking before doing the effort, thoughts welcome!

**Comment by dasMulli** [comment]
This would probably make sense to be part of the templating engine at https://github.com/dotnet/templating

Maybe this can be part of `dotnet new`? `dotnet new lib --ask` or `--interactive`..

**Comment by livarcocc** [comment]
Or maybe even a new template.

@mlorbetske Do you have a pointer to some doc on how people can create/publish templates of their own fabrication?

**Comment by maartenba** [comment]
No need for that, templates look easy to do :-) Thanks! Feel free to close.

**Comment by dasMulli** [comment]
@maartenba some additional input: maybe this could be a template for a `Directory.build.props` file that'll be auto-imported by all projects..
