### ISSUE TITLE
Link to incorrect executable files on MAC OS X

### ISSUE THREAD

**Issue by hunter-xue** [dotnet/cli#631]
dotnet -> /usr/local/share/dotnet/cli/bin/dotnet
But "/usr/local/share/dotnet/cli" is empty.

**Comment by blackdwarf** [comment]
@hunter-xue is this with the latest install?

**Comment by hunter-xue** [comment]
@blackdwarf Yes, I download and install the package from https://github.com/dotnet/cli yesterday.

**Comment by blackdwarf** [comment]
@hunter-xue did you remove all of the symlinks before installing the new package? That is, did you uninstall and then reinstall or just re-ran the PKG?

**Comment by hunter-xue** [comment]
@blackdwarf  No, I did not remove the previous version before I install. But the symbol link in previous version is correct.,

**Comment by blackdwarf** [comment]
@hunter-xue no, we've changed the install location. You can see that in #517. Can you remove all, re-install and see if it repros?

**Comment by hunter-xue** [comment]
@blackdwarf delete the previous version manually and install the latest pkg, the file link was resolved. But "dotnet run" still cannot work, get error below: 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by blackdwarf** [comment]
@hunter-xue thanks for confirmation. The other issue is tracked by different issues here, so I will close this one.
