### ISSUE TITLE
How to make dotnet use a different runtime?

### ISSUE THREAD

**Issue by hadibrais** [dotnet/cli#6314]
I have installed on my Linux system precompiled .NET CLI tools version 2.0.0-beta-001776-00. The runtime libraries (libcoreclr.so and libclrjit.so) and the .NET libraries are installed in the default directory. I made some small changes to the CoreCLR (specifically to the JIT) and verified that my runtime is working correctly. However, I wanted dotnet and all other managed CLI tools including the C# compiler to use my runtime. To do this, I backed up the existing libcoreclr.so and libclrjit.so and copied my versions of these files to the following directory:

/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-beta-001776-00

hoping that by running dotnet, it will just use the new runtime. Unfortunately, it emits the following error:

Failed to initialize CoreCLR, HRESULT: 0x80004005

This error is emitted for any command and even `dotnet --help` emits the same error.

How to I get dotnet (and all .NET CLI tools) to use my runtime?

**Comment by livarcocc** [comment]
What you are changing is not really the CLI, but rather the runtime. I will move your issue to core-setup.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2054

**Comment by hadibrais** [comment]
@livarcocc OK, thanks.
