### ISSUE TITLE
"dotnet run" failed for web (web, webapi and mvc) from CLI

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#6316]
## Steps to reproduce

1. md webTest & cd webTest  --> web project is created succeeded and auto restore succeeded with no warnings;
2. dotnet restore --> completed but with warnings:
- C:\Program Files\dotnet\sdk\2.0.0-preview1-005738\NuGet.targets(97,5): warning : Dependency specified was Microsoft.AspNetCore (>= 1.2.0-preview1-23339) but ended up with Microsoft.AspNetCore 1.2.0-preview1-23565. [c:\CLITesting\webTest\webTest.csproj]
- C:\Program Files\dotnet\sdk\2.0.0-preview1-005738\NuGet.targets(97,5): warning : Detected package downgrade: System.IO.Pipelines from 0.1.0-e170405-5 to 0.1.0-e170221-1 \r [c:\CLITesting\webTest\webTest.csproj]
- C:\Program Files\dotnet\sdk\2.0.0-preview1-005738\NuGet.targets(97,5): warning :  webTest (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.2.0-preview1-23565) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.2.0-preview1-23565) -> System.IO.Pipelines.Text.Primitives (>= 0.1.0-e170405-5) -> System.IO.Pipelines (>= 0.1.0-e170405-5) \r [c:\CLITesting\webTest\webTest.csproj]
- C:\Program Files\dotnet\sdk\2.0.0-preview1-005738\NuGet.targets(97,5): warning :  webTest (>= 1.0.0) -> Microsoft.AspNetCore (>= 1.2.0-preview1-23565) -> Microsoft.AspNetCore.Server.Kestrel (>= 1.2.0-preview1-23565) -> System.IO.Pipelines (>= 0.1.0-e170304-1) [c:\CLITesting\webTest\webTest.csproj]
3. dotnet build --> succeeded with no warnings or errors;
4. dotnet run
## Actual behavior
dotnet run --> failed after input the link to the web and prompt a window "dotnet has stopped working", click the debug button which gives the info "Unhandled exception at 0x00007FF907CB7788 (KernelBase.dll) in dotnet.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131513, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF8E0270000). occurred"
![dotnetrunfailedforweb](https://cloud.githubusercontent.com/assets/22901391/25033698/d04c8f3c-2112-11e7-8c63-73114a321849.PNG)
In addition: "dotnet run" failed as well for webapi and mvc from CLI, with same info "Unhandled exception at 0x00007FF907CB7788 (KernelBase.dll) in dotnet.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131509, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FF8E0270000). occurred".
## Expected  behavior
dotnet restore with no warnings and dotnet run passed with no errors or warnings.

## Environment data
`dotnet --info` output: 2.0.0-preview1-005738
Commit SHA-1 hash:  e1b4556641

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

Test on VSUWPT.26413.02

**Comment by livarcocc** [comment]
can you share the project that you are using to repro this? Maybe publish a small repro repo on github?

@gkhanna79 this seems similar to what we are hitting in the nuget insertion PR.

**Comment by gkhanna79** [comment]
CC @ramarag @kouvel

**Comment by livarcocc** [comment]
cc @dsplaisted too, in case this has anything to do with conflict resolution. Though in the version above we hadn't moved that into the SDK yet.

**Comment by MiaomiaoHuangfu** [comment]
I have put the projects on to https://github.com/MiaomiaoHuangfu/WebFromCLI, which were generated by CLI on build VSUWPT.26413.02.
No change to the code.

**Comment by DanJ210** [comment]
dotnet run no longer works for me either. A project I can run in VS017 and that I have run in VSCode before using dotnet run... No longer works. I can't use Yeoman anymore either.

The screenshot below shows the terminal output. I can dotnet restore, dotnet build, but cannot dotnet run anymore. I don't understand what just happened all of a sudden.

![Terminal Output](https://cloud.githubusercontent.com/assets/16159685/25199939/847bd20a-251a-11e7-9f81-461ee0a7a7aa.PNG)

**Comment by dasMulli** [comment]
@DanJ210 I see two issues:
First you ran `dotnet run` from the solution directory, not the project directory.
Then you specified a full path but from the screen shot I think there is an additional `s` before `.csproj` so the file really doesn't exist.

**Comment by DanJ210** [comment]
@dasMulli I was frustrated yesterday because much is breaking all of a sudden. Yeoman which I used before is now giving all kinds of errors and won't scaffold anything out. So I figured my post here was because of what was going on.

I've never had to change folders to run `dotnet run` before and `dotnet restore` + `dotnet build` all worked so I figured there was a problem when `dotnet run` didn't. But after getting into the right directory it does work.

So thanks and sorry to waste your time.

**Comment by livarcocc** [comment]
I changed the Microsoft.AspNetCore PackageReference to `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-24566" />` and changed the NuGet.Config content to match what gets dropped by dotnet new in the latest CLI version:

```
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="aspnetcore-dev" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="msbuild" value="https://dotnet.myget.org/F/msbuild/api/v3/index.json" />
```

dotnet restore
dotnet run

Hit the website and got the Hello World. I was also using the latest CLI.

Please, apply the changes above and re-activate if you still hit any issues.
