### ISSUE TITLE
Don't show Telemetry message portion during first run when  DOTNET_CLI_TELEMETRY_OPTOUT = 1

### ISSUE THREAD

**Issue by joelharkes** [dotnet/cli#6317]
## Steps to reproduce

i ran:

```
dotnet buidl xxx.csproj -f net35
```

## Expected  behavior

I wouldn't see this message and i wouldn't expect it sets up local cache!

## Actual behavior

I starts running and extracting telemetry stuff:

![image](https://cloud.githubusercontent.com/assets/2960938/25035984/53083358-20f1-11e7-866b-0681f6e55e02.png)

```
Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 6453 ms
Expanding 66%^C
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

**Comment by svick** [comment]
The local cache is unrelated to telemetry, so it's correct that it's populated even if you disabled telemetry.

[Looking at the source code](https://github.com/dotnet/cli/blob/v1.0.3/src/Microsoft.DotNet.Configurer/DotnetFirstTimeUseConfigurer.cs), it seems the telemetry warning is printed even if you disabled telemetry. I agree that such behavior is confusing, the message could probably change when you disabled telemetry.

**Comment by livarcocc** [comment]
If you don't want that message to appear and you don't want the nuget cache to be populated for you by the CLI during first run, you can set DOTNET_SKIP_FIRST_TIME_EXPERIENCE.

cc @bleroy @richlander about not displaying the telemetry portion of the first run message when telemetry is disabled.
