### ISSUE TITLE
"dotnet run" failed for webapi and mvc "Can not find compilation library location for package 'Microsoft.NETCore.App" after installing .NET CORE CLI tools

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#6318]
## Steps to reproduce

- Go to CLI from https://github.com/dotnet/cli, download .NET Core Tools for windows 10 X64 and install it;
- md webapiTest
- cd webapiTest
- dotnet new webapi --> succeeded;
- dotnet restore --> succeeded;
- dotnet build --> succeeded;
- dotnet run 

## Expected  behavior
dotnet run passed with no errors or warnings

## Actual behavior
dotnet run failed with info "Unhandled Exception: System.InvalidOperationException: Can not find compilation library location for package 'Microsoft.NETCore.App'"
![dotnetrunfailedwheninstallnetcorclitools](https://cloud.githubusercontent.com/assets/22901391/25039653/57c004d4-2137-11e7-981a-b2db57a7aaa1.PNG)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005791)

Product Information:
 Version:            2.0.0-preview1-005791
 Commit SHA-1 hash:  2b4992c56d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005791\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-001978-00
  Build    : d197c00dc0f5ca41ac61b6321ebb37d39b63cf80

**Comment by livarcocc** [comment]
This is known issue that is being fixed here:  https://github.com/dotnet/core-setup/pull/2039

**Comment by kichalla** [comment]
cc @pranavkm @mikeharder

**Comment by muratg** [comment]
cc @mlorbetske who also hit this issue recently.

**Comment by mikeharder** [comment]
This issue should be resolved if you use the following versions (or later):

* SDK: 2.0.0-preview1-5817
* Runtime: 2.0.0-preview1-002028-00 (included in SDK 5817)
* ASP.NET: 2.0.0-preview1-24496 from https://dotnet.myget.org/gallery/aspnetcore-dev

There's a related issue which only impacts Ubuntu:

* ASP.NET MVC fails with "Cannot find compilation library location for package 'Microsoft.Win32.Registry'" on Ubuntu
  * https://github.com/dotnet/core-setup/issues/2113

**Comment by eerhardt** [comment]
This is now fixed in the latest builds.

https://github.com/dotnet/core-setup/pull/2039
