### ISSUE TITLE
Unable to restore using CLI on osX

### ISSUE THREAD

**Issue by blackholegalaxy** [dotnet/cli#6321]
## Steps to reproduce
I installed dotnet CLI, SDK and runtime. 

Running a new project, for example through `dotnet new console` works perfectly.

On our existing projet, an error occurs. Our solution contains multiple projects. I want to dotnet restore all projects, then run the web one.
```
dotnet restore
/usr/local/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): warning : Unable to find a project to restore! [/Users/bhole/core/project.sln]
```

I tried to navigate inside the web project within this solution directory and run `dotnet restore` or even `dotnet build`:

```
cd Project.client
dotnet restore
```

> Project.Client.xproj(7,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v14.0/DotNet/Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

## Expected  behavior
I would expect CLI to be able, on macOS, to parse the sln file to be able to restore all packages from the root of solution

Also expect this restore to work. 

On windows I don't encounter any problem, and on Ubuntu it works too.

## Actual behavior
Error restoring package: sln not found, or requiring VisualStudio 14 props.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.1)
> 
> Product Information:
>  Version:            1.0.1
>  Commit SHA-1 hash:  005db40cd1
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.12
>  OS Platform: Darwin
>  RID:         osx.10.12-x64
>  Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
It seems like your sln has xprojs and project.json projects in it. The latest release of the CLI that supported that was preview2. On 1.0.1, we only support msbuild projects.

if that is the case, you can either pin your SDK version using a global.json or you can migrate your xproj/project.json projects to csproj.

Here is a link with more information on it: https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md.

If I got it wrong and you are actually using the new csproj style projects and still failing, please re-activate the issue. In which case, it would be nice if you could share the csproj file for your web project.
