### ISSUE TITLE
Installing latest CLI on OS X has HTML on the success screen

### ISSUE THREAD

**Issue by glennc** [dotnet/cli#6322]
## Steps to reproduce

Install the latest mac installer
go through the wizard until the end

## Expected  behavior

See success message

## Actual behavior

See success message with all the associated HTML markup.

**Comment by livarcocc** [comment]
@eerhardt good chance this is due to the open-ssl removal we did from the installer.

**Comment by eerhardt** [comment]
Yes, this was caused by me.

What if we just removed the conclusion.html all together now?  It doesn't really serve a purpose anymore now that OpenSSL is no longer required.

**Comment by livarcocc** [comment]
Lets remove it.
