### ISSUE TITLE
dotnet pack fails (MSB4018) in release configuration when GeneratePackageOnBuild is set

### ISSUE THREAD

**Issue by StephenCleary** [dotnet/cli#6326]
## Steps to reproduce

1. In VS2017, create a new "Class Library (.NET Standard)".
2. Check the "Generate NuGet package on build" checkbox in the project properties.
3. Run `dotnet pack -c Release` for that project.

[This repository](https://github.com/StephenCleary/DotnetPackErrorRepro) contains a repro project.

Interestingly, this appears to work for debug builds (`dotnet pack` does not error).

## Expected  behavior

The nupkg files are created.

## Actual behavior

MSB4018 error. Actual output:

    PS C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1> dotnet pack -c Release
    Microsoft (R) Build Engine version 15.1.1012.6693
    Copyright (C) Microsoft Corporation. All rights reserved.

    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: The "PackTask" task failed unexpectedly.\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: System.IO.FileNotFoundException: File not found: 'C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\bin\Release\netstandard1.4\ClassLibrary1.dll'.\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.MSBuildProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage(String path)\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage()\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Build.Tasks.Pack.PackTask.Execute()\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]
    C:\Program Files\dotnet\sdk\1.0.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [C:\Work\DotnetPackErrorRepro\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj]

## Environment data
`dotnet --info` output:

    .NET Command Line Tools (1.0.3)

    Product Information:
     Version:            1.0.3
     Commit SHA-1 hash:  37224c9917

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by livarcocc** [comment]
@rohit21agrawal

**Comment by livarcocc** [comment]
Interestingly enough, dotnet build -c Release works just fine, at which point a dotnet pack -c Release will work as well.

Moving to NuGet for now to see why pack is not doing the implicit build.

@StephenCleary It worked for Debug because probably you did a build for Debug before running the pack. Without having a bin folder, when running dotnet pack -c Debug I hit the same issue as above.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5045
