### ISSUE TITLE
Issues restoring packages targetting .NET Standard 1.6 and 1.4

### ISSUE THREAD

**Issue by rnagpal** [dotnet/cli#6331]
## Steps to reproduce
I've a working .NET Standard 1.6 library for our product which is based on the preview tooling(version info at the end) using project.json.

I'm trying to compile this for .NET Standard 1.4 as well(to be used for UWP) but running into several issues during restore.

Here is how my current project.json looks like: https://gist.github.com/rnagpal/5982e242acd5a5ada5228508452236aa 

I tried adding netstandard1.4 to the frameworks section but started getting lots of error like below during the restore:

I tried adding System.AppContext 4.1.0 as dependency under netstandard1.4 but still see these errors related to System.AppContext.

Could someone help me what am I missing here and how can I compile my library targeting 1.4 and 1.6?

error: System.AppContext 4.1.0 provides a compile-time reference assembly for System.AppContext on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Diagnostics.Tracing 4.1.0 provides a compile-time reference assembly for System.Diagnostics.Tracing on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.IO 4.1.0 provides a compile-time reference assembly for System.IO on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Linq 4.1.0 provides a compile-time reference assembly for System.Linq on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Linq.Expressions 4.1.0 provides a compile-time reference assembly for System.Linq.Expressions on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Reflection 4.1.0 provides a compile-time reference assembly for System.Reflection on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Runtime 4.1.0 provides a compile-time reference assembly for System.Runtime on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Runtime.Extensions 4.1.0 provides a compile-time reference assembly for System.Runtime.Extensions on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Runtime.InteropServices 4.1.0 provides a compile-time reference assembly for System.Runtime.InteropServices on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Security.Cryptography.Algorithms 4.2.0 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Security.Cryptography.X509Certificates 4.1.0 provides a compile-time reference assembly for System.Security.Cryptography.X509Certificates on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: System.Text.RegularExpressions 4.1.0 provides a compile-time reference assembly for System.Text.RegularExpressions on .NETStandard,Version=v1.4, but there is no run-time assembly compatible with win.
error: One or more packages are incompatible with .NETStandard,Version=v1.4 (win).

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

/cc @ericstj @davidfowl

**Comment by livarcocc** [comment]
First, you are using runtimes in you project that I am not sure we support, which seems to be the root of your problem. These are runtimes that we supported at the preview2 runtime:

```
"runtimes": {
    "win7-x64": {},
    "win7-x86": {},
    "osx.10.10-x64": {},
    "osx.10.11-x64": {},
    "ubuntu.14.04-x64": {},
    "ubuntu.16.04-x64": {},
    "centos.7-x64": {},
    "rhel.7.2-x64": {},
    "debian.8-x64": {},
    "fedora.23-x64": {},
    "opensuse.13.2-x64": {}
  }
```

Second, we are not supporting the preview2 tooling and project.json anymore. Starting in preview3 we have moved to msbuild and csproj and that's what the 1.0.0 tooling supports. I would migrate your project to csproj and try there with the correct RuntimeIdentifiers.

Please, re-activate if you are still running into problems after trying my suggestions above.
