### ISSUE TITLE
Suggestion: Standardised naming and group into .NET Tools

### ISSUE THREAD

**Issue by richardhallett** [dotnet/cli#6332]
## The Problem

There is a lot of discussion regarding versioning and naming, and I know it is quite confusing, this topic has been brought up in different places, including things like what "--version" should output.
I wanted to raise the general problem of what the CLI and other tools get called when writing documentation, discussing, or referencing in other .NET projects.

I've seen the CLI tools referred to as the SDK (which they are part of), or words like "tooling" which has no clearly defined meaning as far as I can tell (although is closer to what I'm proposing). amongst various others:

* tooling 1.0
* tooling 2.0
* .NET Core tooling
* .NET Core CLI Tools
* .NET Command Line Interface
* .NET Core command line toolchain
* dotnet CLI (yes I consider the word dotnet different to .NET)
* .NET Core SDK

I also note that the term CLI is perhaps misleading in itself because to me it denotes only that it is used as part of a user interface, which is not the only use-case.

## My Suggestion

It occurred to me that there should be some standardised naming and grouping to help reduce confusion. This probably extends largely beyond just the CLI however I thought this was a good place to start.

Unless I am mistaken the .NET CLI is a set of tools that allow you to effectively target either .NET Core or .NET framework or even Mono if on OSX/Linux. With this in mind, it doesn't make sense to group the CLI tools with .NET Core at all and instead should rather be a wider set of tools for .NET.

### Introducing **.NET Tools**

1. .NET Tools should be the overriding "brand" name for what is effectively a package, it should most likely encompass both the CLI and the parts of https://github.com/dotnet/sdk.

2. The versioning should adhere to the major version of the underlying toolset it supports. This means you can have versions of the "dotnet" command as 1.2.23 but the overall .NET Tools version is 1. There should never be a .NET Tools 1.2.23.

#### Other projects to look to for thoughts:
I've had a look for a few other projects that might use similar language, they don't all have exactly same concept or indeed are the same sort of tools, but I do feel they all try to have consistent grouped naming, regardless if they aren't exactly the same.

* LLVM Tools - http://llvm.org/docs/CommandGuide/index.html
* Clang Tools - https://clang.llvm.org/docs/ClangTools.html
* GNU Toolchain - https://en.wikipedia.org/wiki/GNU_toolchain
* Haskell Platform - https://github.com/haskell/haskell-platform
* Visual F# Tools https://github.com/Microsoft/visualfsharp

## How this gets implemented

1. Stop referring to the CLI as anything to do with .NET Core
2. Stop referring to the usage of CLI in general unless actually talking about the CLI.
3. Remove all references to mixed terminology in docs (readme's, wikis, etc)
4. Start using it as a collective term for the .NET ecosystem.
5. **Produce a standardised Definition List** this should explain what .NET Tools is. This is also where I feel this would be good across any .NET product and centralised to understand what we're talking about, it should be adhered to by all contributors either at MS or in the Community.
6. Produce a transitory document that explains that" .NET Core CLI tools" and others are the same thing as .NET Tools - Helps with existing blog posts etc, if they felt so inclined they could even provide an amendment to their post with a link to said document.

## Example Usage

1. Tools docs: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/

Current:
> The .NET Core command-line interface (CLI) is a new cross-platform toolchain for developing .NET applications. The CLI is a foundation upon which higher-level tools, such as Integrated Development Environments (IDEs), editors, and build orchestrators, can rest

Proposed:
> .NET Tools is a new cross-platform toolchain for developing .NET applications. It encompasses a suite of commands upon which higher-level tools, such as Integrated Development Environments (IDEs), editors, and build orchestrators, can rest

2. Github CLI Readme - https://github.com/dotnet/cli/blob/master/README.md

Current: 
> If you are looking for the v1.0.1 release of the .NET Core tools (CLI, MSBuild and the new csproj), head over to https://dot.net/core and download!

Proposed:
> If you are looking for the v1 release of the .NET Tools (CLI, MSBuild and the new csproj), head over to https://dot.net/core and download!

## Challenges

* Search indexes for CLI is everywhere - But honestly it's confusing as to what to search for half the time anyway.
* Existing blog posts, - See transitory document idea above.
* Adoption of everyone to use the same terms - This should be enforced in contributors guidelines and all PR's should adhere to it.

## Summary

This might seem like a minor quibble, but IMHO clear and more importantly consistent language is the only way to help ease understanding.
Hope that all makes sense, if I've misunderstood anything about the current tools set or naming let me know! but I think that might underline my general point about clarity:)

**Comment by livarcocc** [comment]
@richlander

**Comment by livarcocc** [comment]
We have since moved to a new version scheme with a separate version for SDK and the runtime.

@KathleenDollard also has improvements planned for dotnet --info in a separate issue.

As such, I am going to close this issue.

Thanks for the detailed reporting and suggestions.
