### ISSUE TITLE
`dotnet some.dll` randomly fails on Windows with System.IO.FileSystem v4.0.1.0 not found error

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#6333]
This is driving my nutty. There is no consistent repro. When it starts to fail, it seems to continually fail when the `dotnet.exe` is spawned from my (full) MSBuild.exe Task. But once I `dotnet build` (which also spawns my Task but from Core MSBuild Core, it works and then (full) MSBuild will work for a while as well. Then it will start failing again randomly later.

## Steps to reproduce

```
git clone https://github.com/AArnott/libgit2sharp.git
cd libgit2sharp
git checkout portable
MSBuild /t:restore
msbuild
```

## Expected  behavior

The build succeeds.

## Actual behavior

> C:\Users\andarno\.nuget\packages\codegeneration.roslyn.buildtime\0.3.13-gfce1c8ba1e\build\CodeGeneration.Roslyn.BuildTime.targets(20,5): error MSB6003: The specified task executable "dotnet" could not be run. Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [C:\git\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by AArnott** [comment]
This is impacting reliability of Windows builds as part of the work for https://github.com/libgit2/libgit2sharp/pull/1318

**Comment by livarcocc** [comment]
@rainersigwald can you take a look? Also, how is your task is invoking dotnet.exe? Which verb is it using?

**Comment by AArnott** [comment]
This is an MSBuild `ToolTask`-derived type. It invokes a command line like this:

`dotnet.exe path\to\my.dll -mydllswitch1 -mydllswitch2`

The path to my dll is relative to the project directory being built. dotnet.exe is assumed to be on the PATH.

**Comment by rainersigwald** [comment]
@AArnott Did you need to check out a specific branch of that repo? The `vNext` branch that was the default didn't hit this codepath.

I tried on the `portable` branch (at https://github.com/AArnott/libgit2sharp/commit/4e6b2c2e) and don't see this failure.

One thing that _might_ provide some extra information is to set the environment variable `MSBuildDiagnostics=1`, and to build with diag logging turned on, so the next failure will capture more information. Can you try those?

**Comment by AArnott** [comment]
Yes, I missed a `git checkout portable` step. I've updated the repro steps. Thanks for trying that.

It doesn't happen all the time. So I'll set the env var and report back next time it happens.

**Comment by rainersigwald** [comment]
I actually got a repro on a subsequent `msbuild`, and see this detailed logging:

```
"S:\libgit2sharp\LibGit2Sharp.sln" (default target) (1) ->
"S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj" (default target) (2) ->
"S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj" (Build target) (2:2) ->
(GenerateCodeFromAttributes target) ->
: error MSB6003: The specified task executable "dotnet" could not be run. System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003:    at CodeGeneration.Roslyn.Tasks.GenerateCodeFromAttributes.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: \r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\MSBuild.exe\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: --- A detailed error log follows.  [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: \r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: === Pre-bind state information ===\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: DisplayName = System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003:  (Fully-specified)\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/bin/\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Initial PrivatePath = NULL\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: Calling assembly : CodeGeneration.Roslyn.Tasks, Version=0.3.0.0, Culture=neutral, PublicKeyToken=ec41cf4c17a5eaf3.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: ===\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: This bind starts in LoadFrom load context.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\MSBuild.exe.Config\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Using host configuration file: \r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Post-policy reference: System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/bin/System.IO.FileSystem.DLL.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/bin/System.IO.FileSystem/System.IO.FileSystem.DLL.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/bin/System.IO.FileSystem.EXE.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/bin/System.IO.FileSystem/System.IO.FileSystem.EXE.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Users/raines/.nuget/packages/codegeneration.roslyn.buildtime/0.3.13-gfce1c8ba1e/build/netstandard1.3/System.IO.FileSystem.DLL.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Users/raines/.nuget/packages/codegeneration.roslyn.buildtime/0.3.13-gfce1c8ba1e/build/netstandard1.3/System.IO.FileSystem/System.IO.FileSystem.DLL.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Users/raines/.nuget/packages/codegeneration.roslyn.buildtime/0.3.13-gfce1c8ba1e/build/netstandard1.3/System.IO.FileSystem.EXE.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003: LOG: Attempting download of new URL file:///C:/Users/raines/.nuget/packages/codegeneration.roslyn.buildtime/0.3.13-gfce1c8ba1e/build/netstandard1.3/System.IO.FileSystem/System.IO.FileSystem.EXE.\r [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
: error MSB6003:  [S:\libgit2sharp\LibGit2Sharp\LibGit2Sharp.csproj]
```

I suspect this is related to https://github.com/Microsoft/msbuild/issues/1542. Chasing down a theory about why it happens intermittently right now.

**Comment by rainersigwald** [comment]
Ok, I know what's happening, including why this is intermittent.

`GenerateCodeFromAttributes` is a netstandard assembly, compiled against the transitive closure of dependencies of MSBuild's netstandard flavor, which includes `System.IO.FileSystem`. On full framework, that is a facade assembly that forwards types to the installed framework, but it still needs to be reachable in order to load the task.

In cases where the task succeeds, it is because something else has already loaded `System.IO.FileSystem` into memory, so the loader doesn't attempt to find it again. The Roslyn compiler `Csc` task does this, loading it from (on my machine) `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Roslyn\System.IO.FileSystem.dll`. In cases where the failure happens, prior instances of `Csc` have been skipped and the assembly hasn't been loaded into the `MSBuild.exe` process.

At the moment, the "right" way to deliver a portable MSBuild task is to ship two versions--one published for full framework, and one for netstandard--and select the right one via `UsingTask`. That way, the assembly loader can find the facades required to use the task in full framework next to the full framework copy of the assembly (which can be bit-for-bit identical to the netstandard copy, but needs to live in a separate folder).

This is awful, of course. The expected long-term solution is https://github.com/Microsoft/msbuild/issues/1542.

**Comment by rainersigwald** [comment]
One other possible no-good very-bad workaround: find a way to _always_ invoke `Csc` before `GenerateCodeFromAttributes`, purely for the side effect of its loading assemblies that will be used later.

**Comment by AArnott** [comment]
Thanks. I had worked very hard to get my netstandard1.3 task working in both worlds so I didn't have to deal with the complexity you describe. Bummer that it was doomed to fail before I started without my realizing it.

Thanks for the tip.
