### ISSUE TITLE
dotnet test can't test all test projects in a solution

### ISSUE THREAD

**Issue by dhasenan** [dotnet/cli#6338]
## Steps to reproduce
```
dotnet new sln
dotnet new xunit --name Test1
dotnet new xunit --name Test2
dotnet restore
dotnet build
dotnet test
```

## Expected  behavior
All tests in the solution should run.

## Actual behavior
Error message: `Couldn't find a project to run test from.`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
First, you need to add the test projects to the solution by using dotnet sln add <path_to_csproj>.

Second, this is a known limitation. Issue tracking it here: https://github.com/Microsoft/vstest/issues/411
