### ISSUE TITLE
Project broken since upgrade to VS2017

### ISSUE THREAD

**Issue by silkfire** [dotnet/cli#6340]
## Steps to reproduce
Open a .NET Core solution of the 2015 kind (with .xproj files) in VS1017. It asks you to migrate to the new 2017 .csproj format. Accept.

## Expected  behavior
The solution should be able to compile as it was able to do this earlier.

## Actual behavior
Instead I'm getting lots of errors in the form of **Unable to resolve 'C:\Users\.......\documents\visual studio 2017\.........\.........csproj' for '.NETCoreApp,Version=v1.1'**.	 This is a class library used in my solution that some projects have a reference to.

I can't update any NuGet packages either because of this.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by livarcocc** [comment]
Is that library project part of your solution? Has it been migrated to the new csproj format?

**Comment by stonstad** [comment]
I can reproduce this behavior.  I created a vanilla ASP.NET Core Web Application (.Net Framework) project.  I then tried to add a .NET 4.6.2 project (as a project reference) to the solution.  I get the same error -- cannot resolve {project name} on nuget restore.   The nuget restore happens when you try to rebuild or add a new nuget package.  Stated simply, Nuget 4.0 in VS2017 Update 1 (and earlier versions?) is severely broken.

**Comment by stonstad** [comment]
Creating a new csproj (for .NET Framework 4.6.2) and carrying classes across does resolve the behavior.  It seems like an issue internal to nuget.

**Comment by stonstad** [comment]
OK -- I found the cause for the failure in my scenario.  Whichever version of nuget that ships with VS 2017 Update 1 does not like spaces in the file path during package restore with .NET Framework projects added as project references. i.e having "Visual Studio 2017\Projects' will cause the behavior described above ... but "c:\a" for the top level folder works.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#13
