### ISSUE TITLE
Create Solution Template - group of projects

### ISSUE THREAD

**Issue by dyardyGIT** [dotnet/cli#6346]
If we have a solution with a number of projects and want to make a template out of the entire package - can this be done?

I believe the answer is yes.  I have been able to put .template.config/template.json at the root level of an existing project then use dotnet new -i to install the template into the library.

I can then use dotnet new {solutionname} to generate a new solution including the projects however there are some issues that I have not been able to solve.

a) i want to pass in new parameter so that the projects are named given solution name + ".web" or ".api" or ".service" etc.  (currently the projects are just copies of the original project name)

b) is it possible to use a replace parameter to float down to all projects that are a member of the template?

thanks-dave

**Comment by sayedihashimi** [comment]
I have ported this to https://github.com/dotnet/templating/issues/611. Closing this issue.
