### ISSUE TITLE
dotnet pack doesn't generate XML docs

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#635]
`dnu pack` used to generate xml docs. It seems that `dotnet pack` doesn't do the same.

Unless I'm missing something, there doesn't seem to be any way to get xml docs generated with dotnet.

cc @anurse @davidfowl

**Comment by davidfowl** [comment]
Good catch! We should probably implement #312 as part of this.

/cc @pakrym @agocke @jaredpar

**Comment by anurse** [comment]
This was actually already working, `dotnet-compile` just wasn't generating the XML file. Once #312 was fixed this came for free.

**Comment by victorhurdugaci** [comment]
@ajaybhargavb can you please check, once the build completes, that this one fixes the nuget verifier? It should pass now

**Comment by ajaybhargavb** [comment]
I just tried building Common repo. It still doesn't generate the XML files. @anurse could you please check if the latest build has the fix?

**Comment by anurse** [comment]
Figured this out in person, we need to set `compilationOptions.xmlDoc` to `true` in the `project.json`. As in https://github.com/dotnet/cli/blob/master/test/TestProjects/TestLibrary/project.json

**Comment by gregsdennis** [comment]
@davidfowl as of VS2017, project.json has been abandoned in favor of a simplistic XML project model.

I have the XML file in my build output, but I'm not seeing an XML file in my packages.
