### ISSUE TITLE
Getting merged values for use in dotnet pack.

### ISSUE THREAD

**Issue by casperOne** [dotnet/cli#6350]
Before the merging of `packOptions` into the csproj file, `Assembly*` attributes were used (in part) to provide information to be fed into the creation of a NuGet package.

In my setup, I have a [git submodule](https://git-scm.com/docs/git-submodule) which would have a `GlobalAssemblyInfo.cs` file which would look something like this:

```
[assembly: AssemblyCompany("One Frame Link")]
[assembly: AssemblyCopyright("Copyright © 2017 One Frame Link")]
...
```
This makes sense to me; whenever I publish a new package, I pull the submodule and link the above file from the submodule into my project, getting a standard, consistent set of attributes output (and subsequently pulled into the NuGet package).

With the changes to the project format to pull the attributes into the csproj file, I'm at a loss of how to do this as easily in the project itself.

I know I can use the `GenerateAssembly*Attribute` values in the csproj file (and continue to use the linked file), but that only impacts the generation of assembly level attributes in the assembly, it doesn't impact the NuGet package creation.

I can fill in the information manually, but then I lose out on the benefits of having *one* location for this information (e.g. I don't want to update the copyright in 30+ places in 2018).

I can also modify the build process to replace these values, but it feels out-of-band and I'd lose out on being able to version this in source control *along* with the code that it's being applied to.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

**Comment by casperOne** [comment]
Since this is all MSBUILD, I found that [you can import other MSBUILD files into your project file](http://stackoverflow.com/a/157175/50776) with an `Import` element, like so:

**project.csproj**

```
<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\_shared\Ofl._shared.csproj" />
...
```

**shared.csproj**

```
<Project>
  <PropertyGroup>
    <Authors>One Frame Link</Authors>
...
```

Note, it's super important to leave out the `Sdk="Microsoft.NET.Sdk"` attribute in the shared project file.  Not doing so will result in your projects not building correctly.

**Comment by dasMulli** [comment]
With MSBuild 15, you can also name your shared project "properties" file `Directory.build.props` and it will be auto-imported into all `csproj` files in the folder hierarchy beneath its location, no `<Import />` needed.

**Comment by casperOne** [comment]
@dasMulli Oh, that's *very* nice.  Works like a charm.

Also prevents me from having to modify the new csproj file through notepad when setting it up every time.

**Comment by dasMulli** [comment]
In your case, you could even make a `Directory.build.props` that just imports a `submoduleDir\shared.props` file.

Just note that such imported project files aren't considered as inputs for incremental build by default.. so if you change e.g. `VersionPrefix`, some targets (like assembly info generation) might not pick up the change. To avoid this, make sure to include a property definition like [this one](https://github.com/dotnet/sdk/blob/39102ec214514363c6af4cd9d599a35aceb8c745/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets#L15).
