### ISSUE TITLE
TPA passed to the host is incorrect when generating an EXE using 'dotnet build' (dotnet-cli 2.0-preview)

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/cli#6352]
EXE crashes with error "Could not load file or assembly 'System.Runtime, Version=4.2.0.0". When setting `COREHOST_TRACE=1` and get the `TRUSTED_PLATFORM_ASSEMBLIES` property value, I find that the `System.Runtime.dll` passed in is `%HOME%\.nuget\packages\runtime.any.system.runtime\4.3.0\lib\netstandard1.5\System.Runtime.dll`, whose AssemblyName is `System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`. It's a different version, and that's why seeing the load failure.

## Steps to reproduce
```
// Sample.cs
using System;
using System.Reflection;

namespace Sample
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Microsoft.CSharp.RuntimeBinder.CSharpBinderFlags.ConvertArrayIndex);
        }
    }
}

<!--Sample.csproj-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.0.0" />
    <PackageReference Include="System.ValueTuple" Version="4.4.0-preview1-25204-02" />
  </ItemGroup>

</Project>
```
```
dotnet restore
dotnet build
.\bin\Debug\netcoreapp2.0\win10-x64\Sample.exe
```

## Expected  behavior
The sample.exe runs without a problem.

## Actual behavior
When running the EXE produced by `dotnet build`, it crashes with error "Could not load file or assembly 'System.Runtime, Version=4.2.0.0".
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005724)

Product Information:
 Version:            2.0.0-preview1-005724
 Commit SHA-1 hash:  e391b5d5f3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   ...\Microsoft\dotnet\sdk\2.0.0-preview1-005724\
```

**Comment by livarcocc** [comment]
@eerhardt @agocke @nguerrera Seems related to the what we have been discussing the past few days.

**Comment by eerhardt** [comment]
I've reproed this on `sdk\2.0.0-preview1-005724`.

This no longer repos on the latest builds.  @daxian-dbw - can you try the latest?  https://github.com/dotnet/cli#installers-and-binaries

There has been a lot of work in this area recently.  Specifically the conflict resolution work that @dsplaisted has been working on.
