### ISSUE TITLE
dotnet xunit from a different path

### ISSUE THREAD

**Issue by ayende** [dotnet/cli#6357]
## Steps to reproduce

`dotnet xunit -p tests/FastTests/FastTests.csproj`

## Expected  behavior

Should run the relevant project

## Actual behavior

I'm getting:

` No executable found matching command "dotnet-xunit"`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```
I can do the same with `dotnet test`, but I asked about this on the xunit project and was told that this is a dotnet cli limitation (https://github.com/xunit/xunit/issues/1216#issuecomment-295226328)

**Comment by dasMulli** [comment]
The difference between `dotnet test` and `dotnet xunit` is that `test` is baked into the CLI itself, so it is always available, whereas `xunit` is a **project-local** tool, specified via `DotNetCliToolReference`, and can be different for each project.
Unless there is going to be support for global or solution-wide tools, there isn't much that can be done here.. (except for installing a `dotnet-xunit` globally via MSI, RPM, PKG etc.)

**Comment by ayende** [comment]
I'm absolutely fine with installing this globally. How do I make it so it is discoverable by `dotnet` and still execute the project building?

**Comment by dasMulli** [comment]
It is possible to create an executable named `dotnet-xunit` that is somewhere on the $PATH.
On macOS I'm able to create a file `/usr/local/bin/dotnet-xunit ` with the following contents:
```
#!/usr/bin/env bash
dotnet ~/.nuget/packages/dotnet-xunit/2.3.0-beta1-build3642/lib/netcoreapp1.0/dotnet-xunit.dll "$@"
```
But then dotnet-xunit would need an argument to specify which project to run.
(AFAIK, that method will not be able to execute *any* tool because, some arguments like `--additionalprobingpath` on `dotnet exec` can be used as well).

**Comment by livarcocc** [comment]
We have talked about global commands multiple times and it is something that we want to do, though not for 2.0.

I would suggest you use the DotnetCliToolReference.

I am closing the issue as I don't think we can do anything for this right now. Please, re-activate if there is something that the CLI can do, besides global command itself.
