### ISSUE TITLE
Update documentation for self-contained apps with small footprint.

### ISSUE THREAD

**Issue by VanCoding** [dotnet/cli#6364]
## Steps to reproduce
Create a hello world application, like described [here](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/) in the section `Deploying a self-contained deployment with a smaller footprint`. Which results in a csproj file like this:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard1.6</TargetFramework>
    <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="1.0.2" />
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="1.0.1" />
  </ItemGroup>
</Project>
```

Then run `dotnet run`

## Expected  behavior

The projects gets compiled and then started

## Actual behavior

It prints out:
```
Unable to run your project.
Please ensure you have a runnable project type and ensure 'dotnet run' supports    this project.
The current OutputType is 'Exe'.
```

## Environment data
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

## Notes

When I use netcoreapp1.1 instead, it works. But with netstandard1.6 it does not.

**Comment by svick** [comment]
Why would you expect that to work? .Net Standard is not an actual runtime, so it makes sense you can't run apps on it.

A similar issue: https://github.com/dotnet/corefx/issues/18217.

**Comment by VanCoding** [comment]
Well, because I did target it before I upgraded my project.json file to project.csproj today, and it worked. But after the upgrade, it does not.

Plus, if I do `dotnet publish`, I get an exe file, which I can execute.

If I understand that correctly, netstandard not being a runtime is the reason why I have to add those 2 references.

**Comment by dasMulli** [comment]
The issue here is that the SDK targets don't define the necessary values for `RunCommand` and `RunArguments` as they are conditioned the target framework: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L291

Also, I don't think the scenario will still work with 2.0 tooling and netstandard 2.0..

However, this works as a workaround (warning: may cause allergic reactions):
```xml
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard1.6</TargetFramework>
    <RuntimeIdentifier>osx.10.12-x64</RuntimeIdentifier>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Runtime.CoreCLR" Version="1.0.2" />
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="1.0.1" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <RunCommand Condition="'$(RunCommand)' == ''">$(OutDir)/dotnet$(_NativeExecutableExtension)</RunCommand>
    <RunArguments Condition="'$(RunArguments)' == ''">exec &quot;$(TargetPath)&quot; $(StartArguments)</RunArguments>
  </PropertyGroup>
</Project>
```

**Comment by livarcocc** [comment]
@dasMulli Is correct. This won't work in 2.0 and in 1.0 using netstandard1.6 for the small footprint self contained app is not correct. @mairaw this is the issue with documentation that I was telling you about yesterday.

I believe, the correct way to solve this is to use either netcoreapp1.0 or netcoreapp1.1 and <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences> and then add PackageReferences to Microsoft.NETCore.Runtime.CoreCLR, Microsoft.NETCore.DotNetHostPolicy and System.Console.

Meanwhile, I will move this issue to the docs repo.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/docs#1972
