### ISSUE TITLE
dotnet pack solution creates wrong dependency versions 

### ISSUE THREAD

**Issue by JanEggers** [dotnet/cli#6365]
## Steps to reproduce
create solution s
create project a
create project b
b depndens on a

run dotnet pack s.sln --version-suffix beta

## Expected  behavior
created package b depends on package a version 1.0.0-beta

## Actual behavior
created packages b depends on package a version 1.0.0

if package b is now referenced in another solution it cant be restored because no final version of a exists

## Environment data
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by dasMulli** [comment]
See the workaround (using `dotnet msbuild /t:Restore;Pack`) in https://github.com/NuGet/Home/issues/4337

**Comment by JanEggers** [comment]
thx for pointing me in the right direction
