### ISSUE TITLE
"dotnet run" failed for webapi and mvc "error CS1061: 'IWebHostBuilder' does not contain a definition for 'ConfigureConfiguration' and no extension method 'ConfigureConfiguration' accepting a first argument of type 'IWebHostBuilder' could be found" after installing .NET CORE CLI tools

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#6372]
## Steps to reproduce

- Go to https://github.com/dotnet/cli, download .NET Core Tools for windows 10 X64 and install it;
- md webapiTest
- cd webapiTest
- dotnet new webapi --> succeeded;
- dotnet restore --> succeeded
- dotnet build

## Expected  behavior
dotnet build succeeded with no errors or warnings

## Actual behavior
dotnet build failed with info "Program.cs(20,18): error CS1061: 'IWebHostBuilder' does not contain a definition for 'ConfigureConfiguration' and no extension method 'ConfigureConfiguration' accepting a first argument of type 'IWebHostBuilder' could be found (are you missing a using directive or an assembly reference?)"
![dotnetrunfailedforwebapiandmvcwheninstallnetcorclitools](https://cloud.githubusercontent.com/assets/22901391/25269869/108b1322-26b1-11e7-91d2-454455946fee.PNG)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005825)

Product Information:
 Version:            2.0.0-preview1-005825
 Commit SHA-1 hash:  b4a821109d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005825\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002028-00
  Build    : 6d0caecf154d3398b9bc0e637089b6af9e250479

**Comment by svick** [comment]
As far as I can tell, `ConfigureConfiguration` was recently renamed to `ConfigureAppConfiguration` (https://github.com/aspnet/Hosting/pull/1020). `dotnet new` didn't react to that change yet, but there is an open PR to do just that: https://github.com/dotnet/templating/pull/629.

So, if you want to use `dotnet new webapi` on 2.0.0 preview right now, just change `ConfigureConfiguration` to `ConfigureAppConfiguration`. But soon, this shouldn't be an issue anymore.

**Comment by livarcocc** [comment]
This is a known issue with the templates using * versions. We are fixing it as part of https://github.com/dotnet/cli/pull/6362, but that PR is currently blocked due to a segfault when running in Ubuntu, which we are investigating.

**Comment by livarcocc** [comment]
@mlorbetske just close this once we manage to merge your PR.

**Comment by livarcocc** [comment]
The PR got merged.
