### ISSUE TITLE
UseJwtBearerAuthentication is obsolete?

### ISSUE THREAD

**Issue by Venex** [dotnet/cli#6373]
## Steps to reproduce
`dotnet publish -r ubuntu.16.04-arm`

## Expected  behavior
Published application

## Actual behavior

> Microsoft (R) Build Engine version 15.2.93.5465
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Startup.cs(99,11): error CS0117: 'JwtBearerOptions' does not contain a definition for 'AutomaticAuthenticate' [C:\Tools\dotnet 2\webapp\WebApplication.csproj]
> Startup.cs(100,11): error CS0117: 'JwtBearerOptions' does not contain a definition for 'AutomaticChallenge' [C:\Tools\dotnet 2\webapp\WebApplication.csproj]
> Startup.cs(97,7): error CS0619: 'JwtBearerAppBuilderExtensions.UseJwtBearerAuthentication(IApplicationBuilder, JwtBearerOptions)' is obsolete: 'See https://go.microsoft.com/fwlink/?linkid=845470' [C:\Tools\dotnet 2\webapp\WebApplication.csproj]

## Environment data
CLI version: 2.0.0-preview1-005791
TargetFramework: netcoreapp2.0
RuntimeFrameworkVersion: 2.0.0-preview1-002028-00
RuntimeIdentifiers: ubuntu.16.04-arm
Microsoft.AspNetCore.Authentication.JwtBearer: 2.0.0-preview1-002028-00

I can't find information what to use now, is this really obsolete?

**Comment by WernerMairl** [comment]
probably 
https://github.com/aspnet/Home 
is the better place for your issue....
