### ISSUE TITLE
change nuget default 'globalPackagesFolder' path, calling DLL failed

### ISSUE THREAD

**Issue by xgluxv** [dotnet/cli#6385]
## Steps to reproduce
[1]. add new "globalPackagesFolder" path to %APPDATA%\NuGet\NuGet.Config
  
`<config>
    <add key="globalPackagesFolder" value="D:\Cache\nuget\Local\Package" />
</config>`

[2]. delete all files in default 'globalPackagesFolder' path: %userprofile%\.nuget\packages
[3]. use dotnet new command to create an asp.net core mvc site and dotnet restore, dotnet build, dotnet run. all command run ok.
[4]. but use browser visit: http://localhost:5000 ,page error:
![pic1](https://cloud.githubusercontent.com/assets/147598/25301626/be40f1c8-275e-11e7-8fad-0d6da97da1d0.PNG)

**It seems that it cannot find the calling DLL file.**

[5]. If removed custom "globalPackagesFolder", then create new dotnet core app, They are work fine.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

**Comment by livarcocc** [comment]
@Eilon @mlorbetske @emgarten can you guys take a look at this? I don't think this is a template issue. Something in ASP.NET it seems. I CCed @emgarten in case a feed called globalPackagesFolder has special meaning that ASP.NET or us in the SDK (deps.json generation) need to account for.

**Comment by emgarten** [comment]
@xgluxv could you share the value of ``packageFolders`` from ``obj\project.assets.json``?

**Comment by xgluxv** [comment]
@emgarten In `obj\project.assets.json`, `packageFolders`  is new path:
`"packageFolders": {
    "D:\\Cache\\nuget\\Local\\Package": {}
  },`

**Comment by davidfowl** [comment]
I'm not sure DependencyModel supports customer global package folders in in 1.0.x or 1.1.x. https://github.com/dotnet/core-setup/blob/b4bb6cfc7beda3f60aaea0e46df5578d3d7fd74c/src/Microsoft.Extensions.DependencyModel/Resolution/PackageCompilationAssemblyResolver.cs#L41

/cc @pakrym @eerhardt

**Comment by eerhardt** [comment]
This capability is fixed in for 2.0.

See https://github.com/dotnet/core-setup/issues/624 and https://github.com/dotnet/sdk/issues/1002.
