### ISSUE TITLE
Microsoft.Build.Tasks.Core is missing the LC task

### ISSUE THREAD

**Issue by alienisty** [dotnet/cli#6389]
## Steps to reproduce
Just create a project with a licenses.licx file definition and build the project with 

> dotnet build project.csproj 

## Expected  behavior
The project builds and the license information are compiled in the binaries

## Actual behavior
The following error is raised: 

> C:\Program Files\dotnet\sdk\1.0.3\Microsoft.Common.CurrentVersion.targets(2977,5): error MSB4062: The "Microsoft.Build.Tasks.LC" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> decl
aration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
    0 Warning(s)
    1 Error(s)

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.3)
> 
> Product Information:
>  Version:            1.0.3
>  Commit SHA-1 hash:  37224c9917
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.3.9600
>  OS Platform: Windows
>  RID:         win81-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by alienisty** [comment]
Note that building the project with MSBuild provided with Visual Studio 2017 builds the project fine.
I also checked the core tasks dlls from the donet core SDK and VS2017 and the one from the dotnet core sdk is actually missing the LC task, while the VS2017 one has it.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/msbuild#2006
