### ISSUE TITLE
Dotnet restore fails when create a xunit project

### ISSUE THREAD

**Issue by qian6** [dotnet/cli#6391]
## Steps to reproduce
1. Execute the following command to create a xunit project
mkdir xunit-test
cd xunit-test
dotnet new xunit
dotnet restore

## Expected  behavior
It can restore successfully.

## Actual behavior
It have error message as blew:
![capture](https://cloud.githubusercontent.com/assets/20922638/25324652/8dc4e8be-28f9-11e7-89d4-207f212bb9f7.PNG)

  Restoring packages for /home/qian/xunit-test/xunit-test.csproj...
/usr/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Unable to resolve 'xunit (>= 2.2.0)' for '.NETCoreApp,Version=v1.1'. [/home/qian/xunit-test/xunit-test.csproj]
/usr/share/dotnet/sdk/1.0.1/NuGet.targets(97,5): error : Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0)' for '.NETCoreApp,Version=v1.1'. [/home/qian/xunit-test/xunit-test.csproj]
  Generating MSBuild file /home/qian/xunit-test/obj/xunit-test.csproj.nuget.g.props.
  Generating MSBuild file /home/qian/xunit-test/obj/xunit-test.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /home/qian/xunit-test/obj/project.assets.json
  Restore failed in 2.17 sec for /home/qian/xunit-test/xunit-test.csproj.
  
  Errors in /home/qian/xunit-test/xunit-test.csproj
      Unable to resolve 'xunit (>= 2.2.0)' for '.NETCoreApp,Version=v1.1'.
      Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0)' for '.NETCoreApp,Version=v1.1'.
  
  NuGet Config files used:
      /home/qian/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
## Environment data
`dotnet --info` output:
- OS Name: Ubuntu
- OS Version: 14.04
- OS Platform: Linux
- RID: Ubuntu.14.04-x64
- Base Path: /usr/share/dotnet/sdk/1.0.1

OS: LinuxMint 17

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5114
