### ISSUE TITLE
dotnet run failed for webapi and mvc via CLI

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#6392]
## Steps to reproduce
1.md mvcTest & cd mvcTest --> mvc web project is created succeeded and auto restore succeeded with no warnings;
2.dotnet restore --> succeeded;
3.dotnet build --> succeeded with no warnings or errors;
4.dotnet run --> failed as blow:
![dotnetrunfailedformvcandwebapi](https://cloud.githubusercontent.com/assets/22901391/25330973/163cb810-2914-11e7-9960-1b3bdbb8f05b.PNG)

## Expected  behavior
dotnet run passed with no error

## Actual behavior
dotnet run failed

## Environment data
Test on build d15prerel.26421.06
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005738)

Product Information:
 Version:            2.0.0-preview1-005738
 Commit SHA-1 hash:  e1b4556641

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005738\

**Comment by livarcocc** [comment]
We have fixed this in the latest build of the CLI.
