### ISSUE TITLE
Remove Microsoft.VisualStudio.Web.BrowserLink from MVC template

### ISSUE THREAD

**Issue by JosephWoodward** [dotnet/cli#6394]
Before I create a pull request proposing changes I'm interested to know if there's any discussion around whether the `Microsoft.VisualStudio.Web.BrowserLink` should be included in the .NET Core CLI MVC template (this can be seen by running `dotnew new mvc`)

Given the .NET Core CLI supports cross platform and a variety of editors it seems odd that this package (which is specific to Visual Studio) is included by default and referenced within `startup.cs`.

A better solution would be to add the package as a second step if the project is created within Visual Studio. Alternatively whether the BrowserLink package could be made more general, allowing any IDE the ability to integrate with it. If that's the case then I feel a new package name would be in order.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#658
