### ISSUE TITLE
Dotnet new fails: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sbomer** [dotnet/cli#6395]
## Steps to reproduce
dotnet new console

## Expected  behavior
Creates a new console app

## Actual behavior
`Object reference not set to an instance of an object.`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview2-005840)

Product Information:
 Version:            2.0.0-preview2-005840
 Commit SHA-1 hash:  8f2fcef544

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/.sven/sdk/2.0.0-preview2-005840/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```

**Comment by omajid** [comment]
Somewhat unrelated question: when the compiler errors out with `Object reference not set to an instance of an object`, is there any way to ask it to display more information? For example, the name of the object? From what file? If not, is this worth considering as a bug by itself?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#657
