### ISSUE TITLE
dotnet.exe and hostfxr.dll debug symbols could not be found for win-x64 SDK package

### ISSUE THREAD

**Issue by dagood** [dotnet/cli#6400]
## Steps to reproduce

 1. Download the SDK from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.zip (I got 2.0.0-preview2-005840). Extract.
 1. Run `symchk /s SRV*https://dotnet.myget.org/F/dotnet-core/symbols dotnet.exe`.
 1. Run `symchk /s SRV*https://dotnet.myget.org/F/dotnet-core/symbols host\fxr\2.0.0-preview1-002061-00\hostfxr.dll`.

Alternatively: use the VS debugger, and try to use the https://dotnet.myget.org/F/dotnet-core/symbols symbol endpoint to find dotnet.exe or hostfxr.dll on a running app.

@eerhardt also sees this problem with the 1.1 bits. (This is probably expected due to it being an RTM build, which we don't host symbols for on MyGet.)

## Expected  behavior

Debug symbols for both binaries are found in the symbol server and downloaded. If using VS, I can match up sources.

## Actual behavior

Symbols can't be found.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview2-005840)

Product Information:
 Version:            2.0.0-preview2-005840
 Commit SHA-1 hash:  8f2fcef544

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Downloads\dotnet-dev-win-x64.latest(1)\sdk\2.0.0-preview2-005840\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```

Debug symbols for these files **can** be found for the binaries in the Core-Setup package: https://dotnetcli.blob.core.windows.net/dotnet/master/Binaries/Latest/dotnet-win-x64.latest-portable.zip. The MyGet endpoint works with symchk and VS to get them. `dotnet.exe --info` output for the zip I got:

```
.NET Command Line Tools (1.0.2)

Product Information:
 Version:            1.0.2
 Commit SHA-1 hash:  54743c8b7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.2

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002066-00
  Build    : b4bb6cfc7beda3f60aaea0e46df5578d3d7fd74c
```

**Comment by eerhardt** [comment]
`hostpolicy.dll` also has this problem.

Note:  if you just use the installer from core-setup (without the SDK), symbols resolve just fine.  Which leads me to believe that there is something in the CLI build that is causing this issue.

/cc @gkhanna79

**Comment by gkhanna79** [comment]
@dagood Who is looking into this?

**Comment by dagood** [comment]
@gkhanna79 I don't know, someone who's worked with the process that assembles the SDK zip (grabbing the host, hostfxr, hostpolicy) should probably look at it.

@eerhardt is there more you're planning on investigating here?

**Comment by eerhardt** [comment]
> @eerhardt is there more you're planning on investigating here?

I haven't been planning on investigating this.  I think someone from the @dotnet/dotnet-cli should.

**Comment by gkhanna79** [comment]
@chcosta should chime in since he worked on the symbol packaging for all the repos, including core-Setup.

**Comment by chcosta** [comment]
I've never looked at the SDK repo.  I did the work to flow shared framework symbols through core-setup.  I've never heard that providing host symbols was a goal.

**Comment by gkhanna79** [comment]
Host is a shipping component and would need to be debugged like the rest of the FX @chcosta. Where do host symbol packages get pushed to right now?

**Comment by chcosta** [comment]
nupkgs should be available via myget facilities.  I'd **expect** them to be available here - https://dotnet.myget.org/F/dotnet-core/symbols.

**Comment by dagood** [comment]
The host itself, downloaded directly from Core-Setup, *is* debuggable using MyGet. But when you download a CLI/SDK package, that repackaged host *isn't* debuggable using MyGet. That's what I'm trying to point out in the "Environment data" section: the CLI/SDK repackaging process seems to mess with the exe/dlls and make them not match their symbols anymore. So far I don't think this is a Core-Setup problem.

**Comment by livarcocc** [comment]
This might have happened in the past because we were crossgenning more than we should then. We have stopped crossgenning anything other than the SDK by now.

@dagood can you try this out with the 2.1.300 SDK?

**Comment by dagood** [comment]
The symbol lookups from the description (and hostpolicy.dll) now work on `2.1.300-preview2-008347`, closing.
