### ISSUE TITLE
dotnet restore should work for all configurations or have a parameter for specifying the configuration

### ISSUE THREAD

**Issue by stephan-tolksdorf** [dotnet/cli#6404]
The `dotnet restore` command should either restore dependencies and tools for all configurations of a solution/project or support specifying the configuration with a command line parameter. 

The `build` and `clean` commands have the `c|--configuration` parameter for this purpose.  With the `restore` command one currently has to use `dotnet restore /property:Configuration=Release`.

## Steps to reproduce

Create a new project with `dotnet new classlib -lang f#`.

In the created fsproj file replace `<TargetFramework>...</TargetFramework>` with 

```
<TargetFrameworks Condition="'$(Configuration)' == 'Debug'">netstandard1.6</TargetFrameworks>
<TargetFrameworks Condition="'$(Configuration)' != 'Debug'">net45</TargetFrameworks>
```

Then run `dotnet restore` and `dotnet build -c Release`.

## Expected  behavior

dotnet should properly build the project. 

## Actual behavior

The build fails with an error.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5119
