### ISSUE TITLE
dotnet restore doesn't restore Microsoft.NETCore.App package when a fixed RuntimeFrameworkVersion is used

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#6406]
**Scenario:** As part of our mirroring we currently get latest CLI and latest shared runtime. As you know the shared runtime that comes with CLI has been older compared to the one available as a separate download, we have been using `<RuntimeFrameworkVersion>2.0.0-*</RuntimeFrameworkVersion>` property to get the latest version. But we sometimes want to lock into the shared runtime version that comes along with the CLI since this is general user experience

## Steps to reproduce
- Create a `.csproj` file using the following text
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-*</RuntimeFrameworkVersion>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.12-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```
- Run `dotnet restore /p:RuntimeFrameworkVersion=2.0.0-preview1-002028-00 -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --packages c:\temp\packoutput`

## Expected  behavior
Restores `microsoft.netcore.app` package into the package output directory
I see only these packages restored:
![image](https://cloud.githubusercontent.com/assets/6559784/25401306/4234e1e0-29aa-11e7-9064-00982996eb1b.png)

## Actual behavior
Does not restore the `microsoft.netcore.app` package into the package output directory

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005825)

Product Information:
 Version:            2.0.0-preview1-005825
 Commit SHA-1 hash:  b4a821109d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\.dotnet\x64\sdk\2.0.0-preview1-005825\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```
cc @mikeharder

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5120
