### ISSUE TITLE
dotnet-publish: Is there a limitation on what projects are publishable?

### ISSUE THREAD

**Issue by borgdylan** [dotnet/cli#641]
I have managed to run dotnet-publish on the cli projects but not on a simple command line app that runs fine using dotnet-run.

**Comment by krwq** [comment]
I think that's a bug on our side. cc: @piotrpMSFT @blackdwarf @davidfowl

**Comment by blackdwarf** [comment]
@borgdylan can you give us more info? What does your `project.json` look like? What is the OS and what is the version of the CLI you are using?

**Comment by borgdylan** [comment]
I have meaning to close this since yesterday. This occurs only if the project is in a subdirectory of where the CLI is installed. If the project is moved out, publishing carries on normally.

I am using a custom build that targets mono rather than CoreCLR. I will be making all my changes public on github as soon as I get a proper build script fleshed out.

**Comment by borgdylan** [comment]
After updating the code, I can't seem to publish anything but the actual CLI bits. I conducted all tests with my CLI fork that targets mono that I installed using the debian package that the build script made for me.

**Comment by borgdylan** [comment]
The bug was caused due to a context RID not matching the actual RID. The context RID made was ```ubuntu.15.10-x86``` yet the RID made was ```ubuntu.14.04-x64```. The ```dotnet-publish``` command was considering both ```ubuntu.15.10-x86``` and ```ubuntu.15.10-x64``` so I modified the code to ignore the Ubuntu version. That fixes the bug for me.

https://github.com/borgdylan/dotnet-cli/blob/master/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L70
