### ISSUE TITLE
dotnet run failed with "HTTP 500 error"

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#6419]
## Steps to reproduce

- Clone this repo [ProjectKTestProjects](https://github.com/balaTest/ProjectKTestProjects.git)  to your machine and extract it;
- navigate to the root of solution  AspNetCoreWeb_IndAuth_WithAI_1;
- dotnet restore --> succeeded;
- dotnet build  --> succeeded;
- dotnet run 

## Expected  behavior
dotnet run passed with no error
## Actual behavior
dotnet run failed with "HTTP 500 error"
![http500](https://cloud.githubusercontent.com/assets/22901391/25428970/04e58532-2aaa-11e7-89c7-1616ede916ef.png)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005842)

Test on d15prerel.26424.01
Product Information:
 Version:            2.0.0-preview1-005842
 Commit SHA-1 hash:  63832070dd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005842\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09

**Comment by svick** [comment]
The console image seems to show some stack trace. Could you post that here (including other relevant information from the log)?

**Comment by MiaomiaoHuangfu** [comment]
[DotnetRunFailed_AspNetCoreWeb_IndAuth_WithAI_1.txt](https://github.com/dotnet/cli/files/961228/DotnetRunFailed_AspNetCoreWeb_IndAuth_WithAI_1.txt)

**Comment by mathysd** [comment]
I had these 'Can not find compilation library location for package' errors after I changed my nuget.config
(..\AppData\Roaming\NuGet\NuGet.Config).
I changed the default package location from %userprofile%\.nuget\packages to d:\nuget\packages\.

**Comment by sebastienros** [comment]
Got the same issue today, build would work correctly, but at runtime the `ResolveReferencePaths()` call would fail finding an assembly. It appeared this assembly was not in the `.nuget\.packages` folder as expected after the restore. It looks like during build it used `.dotnet\NugetFallbackPackage` and found the package there, but during runtime is looking into `.nuget\.packages` and it was not. 

By clearing my `NugetFallbackPackages` folder, `dotnet restore` correctly downloaded the packages in `.nuget` and then the app was working fine.

**Comment by livarcocc** [comment]
We have made a temporary fix for this issue today. I mean temporary because we "turned off" the fallback folder. But we want to re-enable it again soon, once we find a solution to making it work with web apps. Meanwhile, I am closing this issue.
