### ISSUE TITLE
Package 'NameOfPackage' is incompatible with 'all' frameworks in project

### ISSUE THREAD

**Issue by bsmayer** [dotnet/cli#6428]
## Steps to reproduce

Create a folder named 'Domain'
Create a folder named 'App'

Inside of Domain, run these commands: 
```
dotnet new classlib
dotnet restore
dotnet pack --include-symbols --output '../Nugets'
```

Inside of App, run these commands:
```
dotnet new classlib
dotnet restore
dotnet add package Domain -s '../Nugets'
```

## Expected  behavior

Reference added in the project

## Actual behavior

error: Unable to resolve 'Domain' for '.NETCoreApp,Version=v1.1'.
error: Package 'Domain' is incompatible with 'all' frameworks in project '/{ProjectFolder}/App/App.csproj'.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5127
