### ISSUE TITLE
Support multiple file loggers in addition to console logging

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#643]
It's nice to see CLI output both in console and in a file (easier to search than to keep scrolling up).

I am currently using `& .\build.cmd | Tee-Object -FilePath out | Write-Host` to write to both, but some output still leaks to the console instead of to the file.

I propose the following flags to dotnet:
- `--no-console` - skips console
- `--file-logger <log path>` - prints to the specified file(s) and to console as well

`dotnet --file-logger cli.log publish`

**Comment by enricosada** [comment]
@cdmihai you can redirect output to file only ( both error and output ), and use `tail` or `less` instead of tee

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
