### ISSUE TITLE
Visual Studio fails to discover tests when targeting netcoreapp 2.0

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/cli#6433]
## Steps to reproduce
1. Make new directory for your xUnit test project and go to that directory.
2. Run the command: `dotnet new xunit`.
3. Observe the template UnitTest1.cs and csproj gets created with `<TargetFramework>netcoreapp2.0</TargetFramework>`.
4. Open the csproj in VS 2017 and open the Test Explorer.
5. Click `Run All` in the Test Explorer.

If you repeat the steps from above but change to `<TargetFramework>netcoreapp1.1</TargetFramework>` you get the expected behaviour.

## Expected  behavior
**(1) When csproj is opened in VS, there are no errors:**
Restoring NuGet packages...
Time Elapsed: 00:00:02.4826316
========== Finished ==========

**(2) The tests get discovered and run as expected:**
![image](https://cloud.githubusercontent.com/assets/6527137/25463690/cbf05ca4-2aac-11e7-81cd-5e3c069c1f7d.png)

------ Discover test started ------
[xUnit.net 00:00:00.4868187]   Discovering: MyApp
[xUnit.net 00:00:00.5732655]   Discovered:  MyApp
========== Discover test finished: 1 found (0:00:01.0386907) ==========
------ Run test started ------
[xUnit.net 00:00:00.5002624]   Discovering: MyApp
[xUnit.net 00:00:00.5864145]   Discovered:  MyApp
[xUnit.net 00:00:00.6286026]   Starting:    MyApp
[xUnit.net 00:00:00.7399944]   Finished:    MyApp
========== Run test finished: 1 run (0:00:01.4353808) ==========

## Actual behavior
**(1) When csproj is opened in VS, Error List shows:**
![image](https://cloud.githubusercontent.com/assets/6527137/25463580/389f5298-2aac-11e7-9d0c-36033021af11.png)

Restoring NuGet packages...
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.
NuGet package restore failed.
Time Elapsed: 00:00:01.8173741
========== Finished ==========

**(2) No tests get discovered:**
------ Discover test started ------
[xUnit.net 00:00:00.4868187]   Discovering: MyApp
[xUnit.net 00:00:00.5732655]   Discovered:  MyApp
========== Discover test finished: 1 found (0:00:01.0386907) ==========

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-005858)

Product Information:
 Version:            2.0.0-preview2-005858
 Commit SHA-1 hash:  9593adffc7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Other\dotnet-5858\sdk\2.0.0-preview2-005858\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002081-00
  Build    : 361739f8494aa069bca175533c4ff09b41046fbb

cc @crummel, @shiftylogic, @mellinoe

**Comment by livarcocc** [comment]
I don't know which version of VS you are using, but I don't think anything short of a 15.3 preview VS will be able to handle netcoreapp2.0.

The version of NuGet pre 15.3 does not know about this TFM.

Can you confirm which version of VS you are using? Also, does restoring in the command line work for you?

**Comment by ahsonkhan** [comment]
> Can you confirm which version of VS you are using?

Microsoft Visual Studio Enterprise 2017 Int Preview (2)
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood

> Does restoring in the command line work for you?

Yes.

What about test discovery?

**Comment by livarcocc** [comment]
I don't think this version of VS support netcoreapp2.0, which is why you are hitting this.

**Comment by ahsonkhan** [comment]
I updated to VS version 15.3 (26423.1-Preview) d15prerel and no longer observe unexpected behavior (1) or (2).

Thanks!
