### ISSUE TITLE
Nuget package create/unpack needs to respect unix file permissions [2.0.0]

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#6438]
At 1.x, files created by .NET Core had the execute bit set.
This means that NuGet packages containing executables would work, independent of the bit being set in the zip file.

For 2.x, the execute permission is no longer set. (https://github.com/dotnet/coreclr/pull/7995)
This means NuGet packages need to be created and unpacked with correct permissions.
This is not the case currently.

Most packages contain only dlls and so files, they seem to work fine without the x-bit.
Packages containing executables&scripts are affected.

Once the packing is made permission aware, packages that rely on the 1.x behavior to set the x-bit will need to be repacked for 2.0.

**Comment by dasMulli** [comment]
Dupe of https://github.com/NuGet/Home/issues/4424?

**Comment by tmds** [comment]
@dasMulli indeed, also a dup. Added a comment there.
