### ISSUE TITLE
Why does the Class Library (.NET Core) template exist in VS?

### ISSUE THREAD

**Issue by svick** [dotnet/cli#6439]
I noticed that VS2017 has a "Class Library (.NET Core)" template (under the .NET Core node), which creates a `netcoreapp1.1` class library.

I think such libraries should be pretty rare and people who do need them can edit the csproj manually. On the other hand, people who don't know that they should create .Net Standard libraries are likely to be confused by this and so when they want to create a library for their .Net Core application, they will use the `netcoreapp1.1` template.

Because of that, I think the template should be removed from VS.

**Comment by livarcocc** [comment]
@srivatsn @mlorbetske What do you guys think?

**Comment by srivatsn** [comment]
There's a discussion here about this - https://github.com/dotnet/project-system/issues/1909

**Comment by svick** [comment]
@srivatsn Thanks for the link.

I think it makes sense to close this issue in favor of that one.
