### ISSUE TITLE
1.0.3 - first-run experience should work even with a 2.0 CLI installed.

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#6447]
## Steps to reproduce

1. Cleared NuGet caches (`dotnet nuget locals all --clear`).
2. git clone https://github.com/aspnet/DotNetTools.git --branch rel/1.0.1 && cd DotNetTools
3. Change global.json to sdk 1.0.3
4. dotnet restore

## Expected  behavior
First-run experience primes nuget cache and restore works.

## Actual behavior
First-run fails with
> Failed to create prime the NuGet cache. restore failed with: 1

All calls to `dotnet restore` fail regardless of DOTNET_SKIP_FIRST_TIME_EXPERIENCE setting

> /Users/namc/.dotnet/sdk/1.0.3/NuGet.targets(97,5): error : Failed to retrieve information about 'Microsoft.NETCore.App' from remote source '/Users/namc/.dotnet/NuGetFallbackFol
der'. [/Users/namc/dev/aspnet/DotNetTools/DotNetTools.sln]

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/namc/.dotnet/sdk/1.0.3
```

## Workaround
```
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
mkdir -p ~/.dotnet/NuGetFallbackFolder
```

cc @livarcocc

**Comment by livarcocc** [comment]
I wonder if the fallback folder being deleted but not removed from the NuGet.Config is causing NuGet to fail restore.

@emgarten

**Comment by emgarten** [comment]
> I wonder if the fallback folder being deleted but not removed from the NuGet.Config is causing NuGet to fail restore.

That does look like the reason. Fallback folders must exist, and all sources must exist unless ignored failing sources is set.

@natemcmaster how did the fallback folder get deleted? Did nuget locals delete it? (it shouldn't do this).

**Comment by natemcmaster** [comment]
I was having trouble with my installations so I removed ~/.dotnet manually. It seemed weird that the 1.0 sdk would start using 2.0 features when I have global.json still pointing to 1.0.3. Does 2.0 add something to the machine-level NuGet config?

**Comment by emgarten** [comment]
Fallback folders are a 1.0 feature for restore, they just weren't used until 2.0 by the CLI.

Your user level NuGet.Config should contain the fallback folder entry for this path. Removing it should make this go away. It is similar to if you had a bad source in your config.

**Comment by natemcmaster** [comment]
@emgarten thanks. That explains the NuGet piece. 

@livarcocc how can I figure out what causes `Failed to create prime the NuGet cache. restore failed with: 1`? running `dotnet --diagnostics restore` didn't provide any more detail.

**Comment by livarcocc** [comment]
@natemcmaster have you tried @emgarten's suggestion of removing the fallbackfolder entry from the nuget.config under your user profile as well? Can you set the skip first run flag and try a regular restore and see if that works (or what it fails with)?

**Comment by natemcmaster** [comment]
Yes, restore works fine if I `mkdir -p ~/.dotnet/NuGetFallbackFolder` or edit the global NuGet.config.

NuGet cache warm is still broken though. It appears once you install a 2.0.0-* version of CLI, NuGet cache warmup on 1.x CLI breaks. 

Repro:
Install 2.0.0-preview1 and 1.0.3 CLI. 
Set global.json to 1.0.3.
dotnet new

Result:
As above: "`Failed to create prime the NuGet cache.`"

This looks like a duplicate of what's described here: https://github.com/dotnet/cli/issues/6381

**Comment by livarcocc** [comment]
I believe this is actually a dup of this one here: https://github.com/dotnet/cli/issues/6550. I will track this issue there, as it has a better explanation of what is going on.
