### ISSUE TITLE
Can't publish on OSX 10.11 - Travis-ci

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#645]
Just upped the aspnet/Common repository to run on OSX 10.11 and started encountering odd publish issues. See [here](https://travis-ci.org/aspnet/Common/jobs/98592698#L1662).

Looks like it can't find [matching project contexts](https://github.com/dotnet/cli/blob/568d343de9baa7c30fd1bcd0c26e9354d08f52f8/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L44-L49).

**Comment by blackdwarf** [comment]
Fixed in #747
