### ISSUE TITLE
Dotnet Publish for Linux running on Windows is not renaming dotnet

### ISSUE THREAD

**Issue by matthid** [dotnet/cli#6465]
I hope this is not a duplicate as searching for "dotnet" or "publish" yields to many results, but I couldn't find this.

## Steps to reproduce

`/home/travis/.dotnet/dotnet publish /home/travis/build/fsharp/FAKE/src/app/Fake.netcore/Fake.netcore.fsproj --configuration Release --runtime "ubuntu.14.04-x64" --output "/home/travis/build/fsharp/FAKE/nuget/dotnetcore/Fake.netcore/current"`

Or

`C:\Users\appveyor\AppData\Local\Microsoft\dotnet\dotnet.exe publish C:\projects\fake\src\app\Fake.netcore\Fake.netcore.fsproj --configuration Release --runtime "ubuntu.14.04-x64" --output "C:\projects\fake\nuget\dotnetcore\Fake.netcore\ubuntu.14.04-x64"`

## Expected  behavior

Both folders contain the same output, no matter where I run the command on

## Actual behavior

On travis the binary is called `Fake` while on windows its called `dotnet`.

## Environment data

Working -> I get a renamed "dotnet" executable in the publish directory
`dotnet --info` output:

```
/home/travis/.dotnet/dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /home/travis/.dotnet/sdk/1.0.0-rc4-004771
```

Not working -> Publish folder contains a "dotnet" binary instead of a "Fake" binary.

```
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\dotnet.exe --info
.NET Command Line Tools (1.0.0-rc4-004771)
Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x86
 Base Path:   C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by svick** [comment]
Why are you using SDK version 1.0.0 RC4? I have no idea if it's going to change anything, but could you try updating to the latest version of the SDK (1.0.3)?

**Comment by livarcocc** [comment]
Please, updated to the latest release CLI (1.0.3) and try this out, like @svick suggested. We have fixed quite a few issues since the build you are running.

**Comment by livarcocc** [comment]
This has been open for a few days now without traction, if you can still repro this in the latest release 1.0 CLI, please, re-activate.

**Comment by matthid** [comment]
I updated to 

```
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\dotnet.exe --info
.NET Command Line Tools (1.0.3-rc4-004973)
Product Information:
 Version:            1.0.3-rc4-004973
 Commit SHA-1 hash:  022cc5ebfb
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x86
 Base Path:   C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\1.0.3-rc4-004973
```

And the [workaround](https://github.com/matthid/FAKE/blob/latest_dotnet_sdk/build.fsx#L634-L635) is still triggering, as you can see in [L7929](https://ci.appveyor.com/project/matthid/fake/build/1.0.86#L7929). Can you please open this again?

**Comment by matthid** [comment]
@livarcocc If you want me to try another version please let me know the exact version to retrieve and branch of the `obtain` script such that I can try it out...

**Comment by matthid** [comment]
ping? Sadly I cannot reactivate this myself (only comment) ...

**Comment by livarcocc** [comment]
Can you get the latest CLI (1.0.4) from dot.net?

**Comment by matthid** [comment]
@livarcocc Can you give the full version like 1.0.3-rc4-004973 so I can update my build? is there a good overview to find the full version?

**Comment by matthid** [comment]
Is testing 2.0.0-preview1-005977 ok as well?

**Comment by livarcocc** [comment]
That's what I mean, 1.0.4 is the full version for the 1.0 (released) CLI. You can use the preview1 as well, though, that's a preview release.

**Comment by matthid** [comment]
@livarcocc Thanks, I figured it out after a bit of stubling around... I almost thought the obtain scripts no longer work. Build is running, will report back shortly.

I couldn't make the 2.0.0-preview1-005977 build run, aparently some more stuff needs to be changed to be compatible with it or it's not ready jet.

**Comment by matthid** [comment]
Yes it looks like the issue is still there in
```
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\dotnet.exe --info
.NET Command Line Tools (1.0.4)
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x86
 Base Path:   C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\1.0.4
```

**Comment by matthid** [comment]
For completeness sake: 2.0.0 fails with
```
C:\Users\appveyor\.nuget\packages\fsharp.net.sdk\1.0.3\build\FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet.exe" exited with code -2147450749. [C:\projects\fake\src\app\Fake.Core.Environment\Fake.Core.Environment.fsproj]
C:\Users\appveyor\.nuget\packages\fsharp.net.sdk\1.0.3\build\FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet.exe" exited with code -2147450749. [C:\projects\fake\src\app\Fake.Core.String\Fake.Core.String.fsproj]
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005977\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(94,5): error : Cannot find project info for 'C:\projects\fake\src\app\Fake.Core.Environment\Fake.Core.Environment.fsproj'. This can indicate a missing project reference. [C:\projects\fake\src\app\Fake.Core.BuildServer\Fake.Core.BuildServer.fsproj]
C:\Users\appveyor\.nuget\packages\fsharp.net.sdk\1.0.3\build\FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet.exe" exited with code -2147450749. [C:\projects\fake\src\app\Fake.Core.Context\Fake.Core.Context.fsproj]
C:\Users\appveyor\.nuget\packages\fsharp.net.sdk\1.0.3\build\FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet.exe" exited with code -2147450749. [C:\projects\fake\src\app\Fake.Core.Globbing\Fake.Core.Globbing.fsproj]
C:\Users\appveyor\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview1-005977\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(94,5): error : Cannot find project info for 'C:\projects\fake\src\app\Fake.Core.String\Fake.Core.String.fsproj'. This can indicate a missing project reference. [C:\projects\fake\src\app\Fake.IO.FileSystem\Fake.IO.FileSystem.fsproj]
```

(and several more of these errors) for my project on restore.

**Comment by livarcocc** [comment]
@enricosada @KevinRansom can you guys take a look? This seems to be an issue with F# projects.
Does this happen to you on a c# project?

**Comment by matthid** [comment]
@livarcocc I don't use C# on dotnetcore. So I don't know. But good pointer, it might be a F# SDK problem when this is not part of any shared publishing logic.

**Comment by matthid** [comment]
Note this bug still seems to be there with sdk2.0. As the F# support moved into the CLI can we please re-open this?
/cc @KevinRansom @cartermp

**Comment by matthid** [comment]
ping.

**Comment by dasMulli** [comment]
@matthid are you still having trouble with f# or the executable name? last one should have been fixed by https://github.com/dotnet/sdk/pull/1378, if not, could you build using the `/bl` argument and upload the resulting `msbuild.binlog` file?

**Comment by matthid** [comment]
@dasMulli Thanks, indeed that seems to be the same or a related issue.
