### ISSUE TITLE
teach `dotnet new` how to create f# programs

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#647]
dotnet new should also scaffold f# program.

The template is not a problem.

What's the best way to specify the language?

- command line argument ( `--language F#` ), default `c#` ?
- new command `dotnet-new-fsharp.exe` ( like `dotnet compile` => `dotnet-compile-fsc.exe` )
- new argument `F#` without `--language`

#### A personal feedback

make `c#` explicit like `f#` for new, asking what language use if not specified, is better long term, more `dotnet`, less `c# dotnet`. 
Easier to discover for new user too

**Comment by davidfowl** [comment]
> make c# explicit like f# for new, asking what language use if not specified, is better long term, more dotnet, less c# dotnet. 

I'm pretty sure it'll be hard to convince anyone that c# shouldn't be the default. It is today in all cases.

**Comment by enricosada** [comment]
@davidfowl i know, but i need to ask, now `dotnet` is in beta/rc, after rtm is pretty much impossibile to change this behaviour

I really think it's not much different for csharp

- `--lang c#` explicit
- without args, ask a switch ( `- 1 => C#, -2 => VB, -3 => F# )

but it can be **a really nice move to feel all dotnet languages like first class support in a shared dotnet cli**. 

It's ok to do `--lang F#`, really not a problem, it's more have the feeling of use a shared tool.
If an implementation is subpar the community can help, but **API should be language agnostic**

Atm it's really ok as  `dotnet` not `c# dotnet`, i really like it `compile`, `publish` etc, good work!

Also defaults, when not really needed, are a problem in the future for backward compatibility changes

**Comment by davidfowl** [comment]
There are default source globbing patterns that assume C# as well. It's not just new. When there's no language specified it assume csc is the compiler.

**Comment by enricosada** [comment]
about compilerName, the default is csc, and that's ok for me, let me explain why.

I have not raised a question about that, because `project.json` is generated by tools usually, nobody care about that.

The tool the user run is `dotnet new`, the api for user, and that should be language agnostic.

If it's not possible it should be possible to change the default.
We can read from an `DOTNET_CLI_LANG` env var the default maybe, or an user .config file.
As an user it's easier for me to add this `DOTNET_CLI_LANG` once in the user env var, and forget about it. 
if i need to write a c# program having f# default, i do `dotnet new --lang=c#`, not that bad.

> There are default source globbing patterns that assume C# as well

I'll check these after dotnet-compile-fsc works, but for example that's a problem for vb, or other languages.
F# is going to use `compileFiles`, so i think each community should push to try to make the `dotnet` cli as language anostic as possibile, everyone has an agenda. 
After all, after seven agenda points scored, you win the game ( sry, netrunner addict ).

I really like `dotnet-compile-{compilerName}` for example.

**Comment by davidfowl** [comment]
project.json is not generated by tools, I'm. It sure what you mean. If you if you only care about new (which is pretty much a toy) then sure. It can be as complicated as it needs to be, I don't think it'll be used that much. 

The point of having project.json be minimal and having defaults inferred is so that it is human friendly and can we author it without tools. I'd hate to see this turn into another csproj because it tries to cater to all scenario making it "work" for everything but ends up being verbose to achieve that.

**Comment by enricosada** [comment]
@davidfowl i am ok with minimal project.json ( thx man about that ) and sane default. as i said, i am ok for default compilerName = "csc". I dont want an explicit compilerName on project.json.

i see `dotnet new` as the first OOTB experience of dotnet cli ( http://dotnet.github.io/getting-started/ ) and **it's good** like that. It's not about me and you, but new users.

Maybe yeoman and other scaffolding tools should call `dotnet new`, and add additional info to generated project.json, but that' another issue.

I dont think i ever written by hand a project.json, always copy pasted, but if i can do `dotnet new` i'll do that, because it's easier than copy paste for simple program.

I understand it's a toy, but that's the base experience, as i said, a nice to have as language agnostic.
If not possible, np. 
the `--lang=f#` is required anyway if i need tools to call `dotnet new` so not a problem.

**Comment by enricosada** [comment]
@davidfowl it's only a nice to have, really, i'd like to maintain language agnostic where possibile, the default like this one are a nice to have, but `--lang` is ok. The rest of dotnet suite is really ok

**Comment by shahid-pk** [comment]
:+1:  for dotnet new defaults to c#
 Reason 1 : I estimate almost 90% dotnet devs use c# for better or worse but that is the reality.
 Reason 2 : A tool defaulting to something that has an estimated 90% or more use case doesn't make                              any other use case of the tool less first class citizen. It is only a convenience to majority of the users of the tool.

**Comment by piotrpMSFT** [comment]
@blackdwarf, we've been going back and forth on extending new like this. What's the latest?

**Comment by borgdylan** [comment]
Couldn't dotnet-new just issue a message on the console how to set the compiler that gets used plus a list of know compiler names that comes bundled with the CLI ?

**Comment by enricosada** [comment]
@borgdylan it's not only about compilerName, it's about also the files, Program.cs or Program.fs or Program.vb.
If i choose a language, i can add compilerName for f# ( and vb i think ) and correct source file..
i really think `dotnet new` is the first experience for **some** new developers ( for example `dotnet new` + notepad or vim ), so what's matter is the language ( c#/f#/vb/dylan/etc ).

Anyway sorry all, my bad, it's not a problem, **i'll send a pr with `--lang: F#` ** or something like that.

Default or switch if no `--lang`, etc, is another issue, **i dont want to start a flame war on default**.

**Comment by shahid-pk** [comment]
@enricosada  :+1:  for your work , really excited to use fsharp on linux (the ms version of fsharp).

**Comment by blackdwarf** [comment]
@piotrpMSFT we're pretty much where we were, with some ideas to allow for language overriding (i.e. what this issue is proposing). However, I **do** thing that `dotnet new` could be slightly more powerful without too much added complexity, so will be making a proposal on Mon.

**Comment by piotrpMSFT** [comment]
Thanks @blackdwarf. Looks like folks are excited to light this up, so let's make sure the story matches our plans!

**Comment by enricosada** [comment]
i added f# with `-f#` and `--fsharp` arguments. default is c# ( `-c#` and `--csharp` )

@blackdwarf @piotrpMSFT i have done the implementation before reading your comments, if it's useless np :smile:

**Comment by borgdylan** [comment]
The experience should allow plugins via more binaries being added just like dotnet-compile. The mechanism used by @enricosada requires the CLI to be modified.

**Comment by piotrpMSFT** [comment]
@enricosada the PR here is still in need of rebasing. I'm moving out to RC milestone. Let us know if this can happen today.

**Comment by enricosada** [comment]
i added `--lang` with #1027 , so f#/c# works.
Btw default it's c#, but command line it's pretty for all languages :smile: thx all for feedback.

Further improvement ( like `dotnet new fsharp/console` ) are discussed in #655
