### ISSUE TITLE
dotnet-test: Get machine-readable list of unit tests

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/cli#6473]
Maybe I'm missing something, but I'm trying to get a machine-readable list of unit tests and cannot figure out how.

I've read up on the command-line arguments for `dotnet test` and some of the Issues on here, and discovered that `dotnet test --logger "trx;LogFileName=abcd.trx"` will create an XML file `TestResults\abcd.trx` that I can then read from to read tests, test durations, and test outcomes.

I can also run just one test and get programmatic output by combining it with `--filter`, e.g. `dotnet test --logger "trx;LogFileName=abcd.trx" --filter "FullyQualifiedName=XUnitTestProject1.UnitTest1.Test1"`

However, it I combine it with `--list-tests`, i.e. `dotnet test --logger "trx;LogFileName=abcd.trx"`, no `.trx` file is created and the list of tests are printed to the console along with other human-readable text, i.e:

```
Build started, please wait...
Build completed.

Test run for C:\temp\XUnitTestProject1\XUnitTestProject1\bin\Debug\netcoreapp1.1\XUnitTestProject1.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The following Tests are available:
[xUnit.net 00:00:00.4868587]   Discovering: XUnitTestProject1
[xUnit.net 00:00:00.5949707]   Discovered:  XUnitTestProject1
    XUnitTestProject1.UnitTest1.Test1
    XUnitTestProject1.UnitTest1.Test2



```

Is there a way to get a machine-readable list of unit tests without actually executing them?

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#776
