### ISSUE TITLE
add command `dotnet repl fsi` for F# interactive

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#648]
`dotnet repl fsi` should launch the standard interactive console for f# ( fsi ) 

ref #586

**Comment by blackdwarf** [comment]
Since we are not shipping any REPLs as part of the CLI, I'm going to close this.

**Comment by tobia** [comment]
I'm using a shell alias to launch the F# repl that is already shipping with the dotnet sdk:

    alias fsi='/usr/bin/dotnet /usr/share/dotnet/sdk/*/FSharp/fsi.exe'

I don't know why there is no shortcut to do that from the dotnet tool (like `dotnet fsi`) or where is the proper place to open an issue about it.

**Comment by enricosada** [comment]
@tobia 	while fsi ship internally with .net core sdk, is not production ready yet to use, so a command doesnt exists yet.
