### ISSUE TITLE
TreatSpecificWarningsAsErrors does not work

### ISSUE THREAD

**Issue by dleeapho** [dotnet/cli#6485]
@bungeemonkee commented on [Wed Apr 26 2017](https://github.com/dotnet/buildtools/issues/1456)

I'm having a problem with dotnet build not respecting the TreatSpecificWarningsAsErrors  option in the csproj. It's a .net standard 1.4 project being built with version 1.03 of the cli and msbuild 15.1.1012.6693. If I set TreatSpecificWarningsAsErrors to either 'CS1519' or just '1519' it doesn't treat the warning as an error.

I've tried several other error numbers in TreatSpecificWarningsAsErrors and it seems to ignore the value regardless.

Side note: If I set TreatWarningsAsErrors to 'True' it fails for other warnings but CS1519 is now ignored entirely (not displayed as a warning or an error) regardless of the value of TreatSpecificWarningsAsErrors .

Just for reference, CS1519 is the error 'Missing XML comment for publicly visible type or member...'.

Thanks!

---

@ellismg commented on [Thu Apr 27 2017](https://github.com/dotnet/buildtools/issues/1456#issuecomment-297860929)

/cc @livarcocc Can you move this to the correct place (I'm not sure if it's roslyn, the CLI or msbuild?)

**Comment by dleeapho** [comment]
@livarcocc moved it to CLI for now. Please route.

**Comment by dsplaisted** [comment]
Has the `TreatSpecificWarningsAsErrors` property ever worked?  I don't see any reference to it.

Looking at the CSharp targets, it looks like the `WarningsAsErrors` property may be what you're looking for.

I'm going to close this issue, but feel free to reopen it (or to file a new one in https://github.com/dotnet/roslyn or https://github.com/microsoft/msbuild) if this doesn't resolve it for you.

**Comment by bungeemonkee** [comment]
@dsplaisted Thank you! I was trying to use `TreatSpecificWarningsAsErrors` because when I edited the project properties with the VS 2015 gui that's the property it put in the csporj file. Guess I need to report a separate bug with VS.
