### ISSUE TITLE
Builds are often breaking due to missing roslyn packages

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#649]
Currently all the builds are breaking due to missing Roslyn package - 
Microsoft.CodeAnalysis.CSharp 1.2.0-beta-20151215-01

The required version is not available in the myget feed @ https://www.myget.org/feed/roslyn-nightly/package/nuget/Microsoft.CodeAnalysis.CSharp

Failing builds
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/debug_osx/54/console
http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/debug_ubuntu/61/console

cc: @jaredpar @agocke @piotrpMSFT

**Comment by piotrpMSFT** [comment]
Sounds gross, but maybe we should just take a * dependency until we get stable Roslyn pkgs...

**Comment by Sridhar-MS** [comment]
@agocke Can you confirm that teh roslyn version `1.2.0-beta1-20160108-01` [used in the CLI](https://github.com/agocke/cli/blob/master/src/Microsoft.DotNet.Compiler.Common/project.json#L12) is
- pinned in myget?
- PDBs indexed?
- git tags added to the source code?

**Comment by agocke** [comment]
@Sridhar-MS That build has been uploaded to NuGet: https://www.nuget.org/packages/Microsoft.Net.Compilers.netcore/1.2.0-beta1-20160108-01

As for the rest, @brettfo I know some of the indexing services were down last, how are we doing on that? And do we still need to create a tag for the latest toolset?

**Comment by agocke** [comment]
I've tagged the release myself here: https://github.com/dotnet/roslyn/releases/tag/version-1.2.0-beta1-20160108-01

**Comment by Sridhar-MS** [comment]
@brettfo Any idea about the PDBs indexing?

**Comment by brettfo** [comment]
I'm not sure on the PDB indexing, but I do know that source archiving is still down and I suspect those two systems are related.

**Comment by tannergooding** [comment]
@brettfo, PDB indexing for bits that end up on NuGet (publicly released) is a manual process and is not currently down. Whoever uploaded the netcore package to nuget should have ensured the proper process was kicked off for the public archiving of pdb bits.

**Comment by agocke** [comment]
@tannergooding Do we have documentation on this?

**Comment by brettfo** [comment]
@agocke: Yes, we have some internal notes on this, I'll send you a pointer shortly.

Thanks to @tannergooding who reminded me where these instructions live.  I've started the PDB archiving process and will report back here as soon as it's complete.

**Comment by brettfo** [comment]
The PDB archiving build is now complete for the `1.2.0-beta1-20160108-01` build.

**Comment by Sridhar-MS** [comment]
We moved all our required nuget packages into https://dotnet.myget.org/F/cli-deps/api/v3/index.json feed. So this issue is fixed.
