### ISSUE TITLE
x86 Dotnet crashes when using a private pgo-instrumented coreclr/clrjit 

### ISSUE THREAD

**Issue by adiaaida** [dotnet/cli#6491]
For release, we will be producing PGO data for x64 and x86, which we produce by copying a PGO instrumented coreclr & clrjit into our dotnet shared framework, the creating, building, and running a hello world application. This crash is preventing us from collecting PGO data on x86.

## Steps to reproduce

Install latest dotnet (shared framework and sdk) from master
enlist in coreclr and run:
build.cmd x86 release skiptests skipbuildpackages pgoinstrument
copy coreclr.dll, clrjit.dll, mscordaccore.dll, clretwrc.dll, pgort140.dll, sos.dll, System.Private.Corelib.dll, System.Private.Corelib.ni.dll from <coreclr-root>\bin\Products\Windows_NT.x86.Release to <dotnet>\shared\Microsoft.NETCore.App\<version>
run dotnet new console

## Expected  behavior

Should generate a hello world app

## Actual behavior

Dotnet crashes (popup dialog that says 'something has stopped working...')

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\michelm\.dotnet\sdk\2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1

This was last working at version 2.0.0-preview2-002062-00 (framework) and 2.0.0-preview2-005840 (sdk).

It started failing at or before 2.0.0-preview2-002062-00 (framework) and 2.0.0-preview2-005858 (sdk).

**Comment by adiaaida** [comment]
This appears to also be causing the same sort of failure (dotnet crashing) on RHEL7, where we get a 

> terminate called after throwing an instance of 'HRException*'

failure.

**Comment by livarcocc** [comment]
Can you provide a dump from the crash? Without it, it is difficult to imagine why this would happen. Also, not sure if this is being caused by your instrumentation.

Do other commands work?

cc @gkhanna79 @eerhardt

**Comment by gkhanna79** [comment]
@brianrob or @briansull should be able to help.

CC @russellhadley

**Comment by brianrob** [comment]
@adiaaida, do you have a dump or live repro of the failure?  We can look at this tomorrow.

**Comment by adiaaida** [comment]
I can repro it locally, but it's not producing a stack trace or anything. It just pops up the "dotnet has stopped working" dialog box one windows.

**Comment by gkhanna79** [comment]
@adiaaida If you execute the app under Windbg, it should break upon crash and you can then generate the dump for @brianrob to look into.

**Comment by adiaaida** [comment]
The x86 windows issue has been fixed. This was a coreclr bug.

We are still seeing a failure in linux, but it is likely also a coreclr bug, rather than a dotnet issue, so closing this issue.
