### ISSUE TITLE
Publish a .NET Core 1.0 with .NET Core 1.1 dependencies

### ISSUE THREAD

**Issue by normj** [dotnet/cli#6495]
## Steps to reproduce
1) Create a project targeting netcoreapp1.0
2) Add a dependency that on .NET Core 1.1 like `Microsoft.Extensions.Logging 1,1,1`
3) Execute `dotnet publish`

## Expected  behavior
The publish step fail with an error about dependencies requiring a new version then the target framework. This would keep users informed when they are pulling in libraries out of the LTS.

## Actual behavior
Publish succeeds but the publish folder gets inflated pulling .NET Core 1.1 system packages that are not part of the LTS.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by livarcocc** [comment]
Microsoft.Extensions.Logging targets netstandard1.1 and as such is compatible with netcoreapp1.0.

You can see the compatibility matrix here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard.

All our dependencies and compatibility checks are based on NuGet and the TFM compatibility checks. We have no plans on keeping and enforcing a list of packages on a particular train beyond that.
