### ISSUE TITLE
What to do with dotnet-dev-debian-x64.latest.tar.gz file 

### ISSUE THREAD

**Issue by shiglet** [dotnet/cli#6498]
I followed  [tuto](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md) to try to install cli on my raspberry pi 3 (using Debian 8.2).

I downloaded the binaires from [here](https://github.com/dotnet/cli/tree/master)  but i don't know what to do with this file. I extract it but there is no installer only binairies.

Is there something to do with this ?

I'm big beginner in LINUX/UNIX/etc ... platform, thanks.

**Comment by svick** [comment]
That tutorial guides you on how to write your application on your development machine (Windows, Linux or macOS, all on x64), and then use [self-contained deployment](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/#self-contained-deployments-scd) to run it on a Pi.

That means you have to install the SDK on your development machine but you don't install .Net Core on the Pi at all (you just copy your application and it will include all the necessary parts of .Net Core).

According to the tutorial, the .Net Core CLI does not currently work on a Pi.

**Comment by shiglet** [comment]
It means that i can't execute dotnet core application on my Pi (with Raspbian (Debian 8.2)) ? Or am i wrong ?
If i use a self-contained deployement which targets Debian, it will work ?

Are Ubuntu and Windows IOT the only one available for this tutorial ?

Thanks for your answer.

**Comment by livarcocc** [comment]
You should be able to publish your app as either a portable app (in which case, you will need to have the exact runtime that your app targets installed in the Pi machine) or a self-contained app that targets your Pi RID.

In the first case, you run it by invoking <path_to_dotnet> <path_to_your_dll>. In the second case, you run it by invoking <path_to_your_app>. Please note that in both cases you need to move the publish folder into the Pi in order to be able to execute it.

If you are still running into issues, please re-activate.

**Comment by shiglet** [comment]
Finally I installed ubuntu 16.04 on my Pi. And i installed the sdk on my windows computer.
I followed the instruction on the tutorial bellow. I succeed to publish my application for ubuntu 16.04 arm.
I installed the prerequisites packages and was able to run my application on ubuntu ! Great :)

Now i want to know why i have these following errors on my visual studio : 

![devenv_2017-05-07_14-25-55](https://cloud.githubusercontent.com/assets/18026048/25780932/57c94646-3331-11e7-89d8-ab17e0c115de.png)

I manually changed the .csproj to have this : 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>ubuntu.14.04-arm;ubuntu.16.04-arm</RuntimeIdentifiers>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="1.0.0-rc" />
    <PackageReference Include="Discord.Net.Commands" Version="1.0.0-rc" />
    <PackageReference Include="Discord.Net.Core" Version="1.0.0-rc" />
    <PackageReference Include="Discord.Net.Rest" Version="1.0.0-rc" />
    <PackageReference Include="Discord.Net.WebSocket" Version="1.0.0-rc" />
  </ItemGroup>

</Project>
```
    <TargetFramework>netcoreapp2.0</TargetFramework> especially this line. 

On my visual studio i have only this 2 version available : 

![](http://i.imgur.com/wsu3ThD.png)

How can i do to make Visual Studio aware of the netcoreapp2.0 that i installed before ?
