### ISSUE TITLE
Remove the FrameworkReferenceResolver

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#65]
It's ugly and should be deleted and doesn't work xplatform. Requires https://github.com/dotnet/corefx/issues/3934

/cc @Petermarcu @ericstj @piotrpMSFT

**Comment by blackdwarf** [comment]
@davidfowl is this still an issue?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

ProjectModel will be removed alltogether.
