### ISSUE TITLE
Invalid DependencyContext in test on net452 after upgrade to CSPROJ

### ISSUE THREAD

**Issue by smbecker** [dotnet/cli#6503]
## Steps to reproduce
I created a test project that has `PreserveCompilationContext=true` and has a project reference. When I run the tests in `netcoreapp1.1`, all of the tests pass without issue. However, if I run `dotnet test -f net452`, the tests will fail because the `DependencyContext` is null. I get the same result with `dotnet xunit -framework net452`. I am not sure if this is a bug or if I am just doing something wrong. I created a minimal repro that shows my issue (https://github.com/smbecker/TestNewProject).
* Restore the solution
* CD into DotNetTestProject and run `dotnet test`. See the test failure.
* CD into XunitTestProject and run `dotnet xunit`. See the test failure.

I am also seeing an issue where I cannot debug the test failure because symbols for my project reference never load. Any attempt to manually load the symbols in VS 2017 gives me the message "A matching symbol file was not found in this folder"

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

**Comment by smbecker** [comment]
I did find that if I use `dotnet xunit -noshadow` then the tests pass.

**Comment by livarcocc** [comment]
I believe this is a known issue. @natemcmaster am I right in believing I have seen you talking about this in the microsoft/vstest repo?

**Comment by natemcmaster** [comment]
Yes, this looks like a known issue when using xunit.runner.visualstudio and DependencyContext. The default settings use shadow copy, which means the deps.json file cannot be found. You can disable shadow copy by setting `"shadowCopy": false` in xunit.runner.json. See http://xunit.github.io/docs/configuring-with-json.html

**Comment by smbecker** [comment]
Thanks.

Any idea why the symbols wouldn't load when debugging a test running under net452?

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#782
