### ISSUE TITLE
dotnet-install fails with 'The specified blob does not exist.' for dnvm/latest.sharedfx.win.x64.version

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/cli#6505]
## Steps to reproduce
.\Dotnet-Install.ps1 -SharedRuntime -InstallDir .dotnet -Channel master -Architecture x64

## Expected  behavior
Downloads and installs dotnet

## Actual behavior
error:
```
Failed to download https://dotnetcli.blob.core.windows.net/dotnet/master/dnvm/latest.sharedfx.win.x64.version.
StatusCode: 404, ReasonPhrase: 'The specified blob does not exist.', Version: 1.1, Content:
```

## Environment data
`dotnet --info` output: N/A, trying to run install script
I'm seeing the failure on Windows x64

**Comment by livarcocc** [comment]
@eerhardt @gkhanna79 we should look into a way to get the installer scripts working better (like indicating some possible channels to use). Given that the script needs to comply with the shared runtime blob storage layout, I would prefer if you guys made the changes, if any. 

@JosephTremoulet please, set your channel to release/1.1.0 and it will work.

**Comment by eerhardt** [comment]
See the discussion here: https://github.com/dotnet/cli/issues/6517#issuecomment-299349691.

The fix is in the codebase, but we just haven't gotten an official build out yet.
