### ISSUE TITLE
Re-enable fallback folder

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6507]
Update this line here: https://github.com/dotnet/cli/pull/6504/files/0dc1b53482d4511f834d9c8960977fad45f9c712#diff-b18157ab2f762a76027673bebcf11175R12

Set it back to fallbackfolders

**Comment by emgarten** [comment]
@livarcocc  NuGet will support setting sources and fallback folders through MSBuild properties. Would it work for you to set the packages location as a source in 1.x projects and a fallback folder in 2.x projects?

Spec:
https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild

Here are the related issues:
https://github.com/NuGet/Home/issues/5248
https://github.com/dotnet/project-system/issues/2225

//cc @rrelyea

**Comment by livarcocc** [comment]
The current plan is to expand the fallback folder under the SDK folder and add it as a package source in the NuGet.Config so that 1.0 projects can use it.
Then, for 2.0 projects, we can set the fallback folder using the msbuild property pointing to a location relative to the SDK conditioned on this folder existing.
