### ISSUE TITLE
"dotnet run" cannot work on MAC OS X 10.11.2

### ISSUE THREAD

**Issue by hunter-xue** [dotnet/cli#651]
I created a hello world project with "dotnet new", then execute "dotnet run" get error: 
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

but "/usr/local/share/dotnet/bin/dnx/dnx run" can work well.

**Comment by piotrpMSFT** [comment]
Adding El Cap support needs to happen soon. @blackswarf has a Known Issues doc that should already be merged, and which offers a workaround. You need to explicitly specify the RID for the time being.

**Comment by hunter-xue** [comment]
Understand now. Many thanks for your reply.
