### ISSUE TITLE
Publish to ubuntu.16.04-arm causes files to not be found when running

### ISSUE THREAD

**Issue by 165plo** [dotnet/cli#6510]
## Issue
Attempting to start a published mvc on Raspberry Pi causes error when a file is not found.

## Steps to reproduce
Following the guide below I was able to run a dotnet core app on my Raspberry Pi
https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md
by @Petermarcu 
I also took a look at https://timdows.com/projects/asp-net-core-2-0-0-beta-on-a-raspberry-pi-3/#run-mvc
I am also running this in a docker container, but the guide above ran no problem.

Run:
dotnet new mvc
dotnet restore
dotnet publish -r ubuntu.16.04-arm
Copy publish folder to Raspberry Pi
Attempt to run the published files

## Expected  behavior
There server starts up correctly.

## Actual behavior
Error: assembly specified in the dependencies manifest was not found -- package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.0-preview1-24647', path: 'lib/netstandard1.3/Microsoft.AspNetCore.Antiforgery.dll'

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-005905)

Product Information:
 Version:            2.0.0-preview2-005905
 Commit SHA-1 hash:  2cc5612fec

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/david/Documents/DotNet2.0Preview/sdk/2.0.0-preview2-005905

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-002093-00
  Build    : 1a195046fd92bd73d993d804bea2f4506c2b56f1

a.csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
     <RuntimeFrameworkVersion>2.0.0-beta-001620-00</RuntimeFrameworkVersion>
    <RuntimeIdentifiers>win8-arm;ubuntu.14.04-arm;ubuntu.16.04-arm</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-24647" />
    <!-- PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0-preview1-24647" / -->
  </ItemGroup>

  <!-- ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview1-24647" />
  </ItemGroup -->

</Project>

```

**Comment by livarcocc** [comment]
I am sorry, which of the guides is working for you? Also, please, remove the RuntimeFrameworkVersion from your csproj. You don't need it anymore. It will default to whatever is available with the CLI that you have installed.

Can you also tell us how you are running the application?

**Comment by 165plo** [comment]
The command line application part of both articles works fine. Its when i go to mvc apps that I have issues.

You have a good point on the cli. Im wondering id the fact that i have 2 versions of core might be part of the issue. One i got using apt-get the other is the tar.gz from the githib page. Since the tar,gz didnt have install instructions i assumed i could run everything in parallel. 

As for running the app. I have tried 2 methods. 
1. Part of publish creates a executable that i can run. I generally have to do chmod u+x app. But then do ./app and i get the exception. 
2. I downloaded the, i believe, cli package for arm (no sdk exists yet for arm) and ran dotnet app.dll. At which point i get the same error.

**Comment by livarcocc** [comment]
I believe you were actually hitting a known issue that we have now addressed in the latest CLI. Can you download the latest preview1 CLI (from release/2.0.0 branch) and give this a shot? Please, re-activate the issue if this still repro for you.

**Comment by 165plo** [comment]
@livarcocc I may be doing somthing wrong but I am unable to find preview1 from the release/2.0.0 branch. When I pull the latest I am getting a 2.0.0-preview2-005905 version. Is this expected? If not can you provide a link to the branch that I should be pulling from?
