### ISSUE TITLE
Error attempting to run the project model server proccess (1.0.3)

### ISSUE THREAD

**Issue by LeonardoBluesMan** [dotnet/cli#6514]
Hi
I got an error when I try to load a webApi project which runs properly in some windows machines but not in some others (see attached image for full description) and I cannot figure out what is the difference between them.

Error attempting to run the project model server proccess (1.0.3)

Initially we are using 1.0.0-preview2-003131, and I tried now 1.0.3 with same result.

In addition, when I try to build the project, I got this error, but file paths exists indeed:
MSB4062	The "GetTransitiveNonDotNetProjectDependencies" task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

We have another webapi project which has the same problem and the only way we could run it is adding a global.json at the same folder where my sln file is with the following configuration, and all problems were solved, but this solution doesn't work for the first issue
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}

Thanks
Regards

## Environment data

Visual Studio Version: 2015 update 3

`dotnet --info` output:

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

[project.json.txt](https://github.com/dotnet/cli/files/975405/project.json.txt)
<img width="230" alt="error" src="https://cloud.githubusercontent.com/assets/17742205/25693751/556c1ece-30ab-11e7-8fa3-87bb4ffb3834.png">

**Comment by livarcocc** [comment]
The project model server no longer exists in CLI 1.0.3. That was an artifacts needed only for project.json, which is not longer supported in the CLI, since we moved over to MSBuild.

You can migrate your project.json to csproj (but you will need VS2017), or continue using a global.json and pointing to a preview2 CLI. This article has more info about it: https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md
