### ISSUE TITLE
dotnet restore failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by shimingsg** [dotnet/cli#6523]
## Steps to reproduce
1. on clean VM, sudo apt-get install unzip libunwind8 gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev
2. wget -O ~/20170505-dotnet-dev-linux-x64.latest.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-dev-linux-x64.latest.tar.gz
3. mkdir -p ~/20170505
4. tar -xf 20170505-dotnet-dev-linux-x64.latest.tar.gz -C ~/20170505/
5. export PATH=~/20170505:$PATH
6. dotnet --info
7. mkdir -p ~/HelloWorld
8. cd ~/HelloWorld
9. dotnet new console

## Expected  behavior
Create project successfully and restore succeeded

## Actual behavior
e2euser@E2E-Ubuntu1604s:~/HelloWorld$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/e2euser/HelloWorld/HelloWorld.csproj...
Restore failed.
Output from command:
  Restoring packages for /home/e2euser/HelloWorld/HelloWorld.csproj...
/home/e2euser/20170505/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): error : Un                                                                                                 able to load the service index for source https://dotnet.myget.org/F/dotnet-core                                                                                                 /api/v3/index.json. [/home/e2euser/HelloWorld/HelloWorld.csproj]
/home/e2euser/20170505/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): error :                                                                                                    The type initializer for 'System.Net.Http.CurlHandler' threw an exception. [/hom                                                                                                 e/e2euser/HelloWorld/HelloWorld.csproj]
/home/e2euser/20170505/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): error :                                                                                                    The type initializer for 'Http' threw an exception. [/home/e2euser/HelloWorld/He                                                                                                 lloWorld.csproj]
/home/e2euser/20170505/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): error :                                                                                                    The type initializer for 'HttpInitializer' threw an exception. [/home/e2euser/He                                                                                                 lloWorld/HelloWorld.csproj]
/home/e2euser/20170505/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): error :                                                                                                    Unable to load DLL 'System.Net.Http.Native': The specified module or one of its                                                                                                  dependencies could not be found. [/home/e2euser/HelloWorld/HelloWorld.csproj]
/home/e2euser/20170505/sdk/2.0.0-preview1-005957/NuGet.targets(97,5): error :                                                                                                     (Exception from HRESULT: 0x8007007E) [/home/e2euser/HelloWorld/HelloWorld.cspro                                                                                                 j]

Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview1-005957)

Product Information:
 Version:            2.0.0-preview1-005957
 Commit SHA-1 hash:  056ac0e9cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/e2euser/20170505/sdk/2.0.0-preview1-005957/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

**Comment by eerhardt** [comment]
@shimingsg - can you ensure you have all the pre-reqs installed correctly?

https://github.com/dotnet/core/blob/master/Documentation/prereqs.md#ubuntu

**Comment by wli3** [comment]
@shimingsg this package requires following packages, you can install them in sequence

dotnet-host-ubuntu.16.04
dotnet-hostfxr-ubuntu.16.04
dotnet-sharedframework-ubuntu.16.04

BTW, if you are using dotnet-dev-linux-x64-XXX.deb, dpkg will compile no dependency

**Comment by eerhardt** [comment]
> BTW, if you are using dotnet-dev-linux-x64-XXX.deb, dpkg will compile no dependency

There's a `dotnet-dev-linux-x64-XXX.deb`?  Can you link to it?  I didn't think we had one yet.

**Comment by wli3** [comment]
@eerhardt sorry, it should be dotnet-sdk-xxx

**Comment by shimingsg** [comment]
@eerhardt , yes , I used the command as following to install the pre-reqs:
sudo apt-get install libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip

**Comment by shimingsg** [comment]
works fine on build 2.0.0-preview1-005972

**Comment by shimingsg** [comment]
@wli3 , I didn't install the packages you list and it works fine on build 2.0.0-preview1-005972. I don't know why. 

will re-open this issue if it repro .

**Comment by shimingsg** [comment]
the issue repro on build 2.0.0-preview2-006065 (master branch)

**Comment by shimingsg** [comment]
dotnet --info:

.NET Command Line Tools (2.0.0-preview2-006065)

Product Information:
 Version:            2.0.0-preview2-006065
 Commit SHA-1 hash:  7f50f322d5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/e2euser/20170512/sdk/2.0.0-preview2-006065/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f

**Comment by wli3** [comment]
Looks fine on my Azure machine 🤔

![image](https://cloud.githubusercontent.com/assets/6993335/26015234/065fc39c-3715-11e7-8fb4-a365754ac5a3.png)

```
wul@temp-ubuntu-05-12:~/HelloWorld$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/wul/20170505/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

```

I am using this image from Canonical
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Canonical.UbuntuServer?tab=Overview

History
```
wul@temp-ubuntu-05-12:~/HelloWorld$ history
    1  ls
    2  sudo apt-get install unzip libunwind8 gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev
    3  wget -O ~/20170505-dotnet-dev-linux-x64.latest.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-dev-linux-x64.latest.tar.gz
    4  mkdir -p ~/20170505
    5  tar -xf 20170505-dotnet-dev-linux-x64.latest.tar.gz -C ~/20170505/
    6  export PATH=~/20170505:$PATH
    7  dotnet --info
    8  mkdir -p ~/HelloWorld
    9  cd ~/HelloWorld
   10  dotnet new console
   11  dotnet --info
   12  ls
   13  history
```

**Comment by shimingsg** [comment]
@wli3 , the version 2.0.0-preview1-005977 work fine too on my test machine. since no new build on release/2.0.0, so pick up from master branch, the issue repro on build 2.0.0-preview2-006065

**Comment by shimingsg** [comment]
fixed by re-installing apt-get install libcurl4-openssl-dev. Will verify it on next version.

**Comment by livarcocc** [comment]
We got a green light on the test. So, closing this issue.
