### ISSUE TITLE
dotnet.exe remains even though Visual Studio unit test finishes

### ISSUE THREAD

**Issue by takuya-takeuchi** [dotnet/cli#6528]
## Steps to reproduce
Do unit test in VS 2015. Target project is *.xproj.

And my environmental is 

    dotnet.exe --version
    1.0.3

## Expected  behavior
After finish unit test, all dotnet.exe processes exit.

## Actual behavior
All dotnet.exe remain.
Every time I do unit test, dotnet.exe goes on increasing.

When I saw task manager, there are a lot of dotnet.exe and they consume large memory.
Should we have to kill them by the following command?

    taskkill /f /im dotnet.exe

And this behavior is similar with #5311.

## Others

![anime](https://cloud.githubusercontent.com/assets/6241854/25764869/da4e58f8-3224-11e7-9253-462d79ce89c7.gif)

**Comment by livarcocc** [comment]
@takuya-takeuchi I am not sure how this is possible.

CLI 1.0.3 no longer supports project.json. As in, it won't run it at all. You must have a global.json in your repo with a sdk node pointing to a preview2 CLI.

Either way, we no longer support project.json. Please, migrate your project to msbuild and use VS2017. If this issues still reproes there, please re-activate.
