### ISSUE TITLE
dotnet-install.sh needs to be updated for the Linux distro change

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#6538]
Today in master, the dotnet-install.sh script detects your current distro's name and uses that name to download the distro-specific version of the shared runtime and/or SDK:

See https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh#L58-L109

However, we are moving away from distro specific builds, and instead have a single "linux" portable installer/.tar.gz.

We need to update the install script for this change in our publish assets.

**Comment by rynowak** [comment]
It also looks like I can unblock myself for now by providing the correct rid with `-r`. What's the new unified linux rid?

**Comment by omajid** [comment]
`linux-x64`
