### ISSUE TITLE
Question: Could dotnet-compile pass a project root parameter?

### ISSUE THREAD

**Issue by borgdylan** [dotnet/cli#654]
The DNX compiler provider for dylan.NET used the project root to automatically discover the main file to pass to the compiler. With the CLI I have to force the user to add that file to the ```compileFiles``` list in project.json. It would be nice to get the project root or at least the path to the project.json used.

**Comment by mattnischan** [comment]
I'm not sure I follow.

By default all `**/*.cs` from the location of your project.json are included for compilation. You do not need to use `compileFiles` unless you need to change that behavior.

**Comment by borgdylan** [comment]
I have implemented ```dotnet-compile-dnc``` a provider for my compiler. My compiler expects source files in order and uses ```#include``` to traverse the source tree, as only the root source file gets passed in. With DNX I used a convention for main entry file, so that it could be discovered automatically inside the project root. As things stand with the CLI I have to force the user to specify that file manually. As I understand it, the CLI is meant to be used with all compilers that can interface with it and not just c#.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.

Once we move to MSBuild, dnc projects will need to be migrated to an msbuild [e.g. dnproj] equivalent with appropriate targets and tasks. `dotnet` will end up invoking a moral equivalent of `msbuild /t:Build foo.dnproj` when kicking off a build. Once the dnproj is loaded you'll be able to use well-known properties to find its location.

**Comment by borgdylan** [comment]
I already have a Mono XBuild compatible targets file that interfaces with the compiler. That means no extra work on my end?

**Comment by borgdylan** [comment]
It uses searches based on the AssemblyName property to discover the main input file as things stand.
