### ISSUE TITLE
dotnet-install.sh --shared-runtime --channel production doesn't work

### ISSUE THREAD

**Issue by rianjs** [dotnet/cli#6540]
## Steps to reproduce

1. Download the script from: https://github.com/dotnet/cli/tree/rel/1.0.0/scripts/obtain (This URL is from [the docs](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script))
2. `chmod a+x dotnet-install.sh`
2. Run it with the args `./dotnet-install.sh --shared-runtime --channel production`

The `production` channel is the default when no channel is specified, but it happens to be hard-coded to display an error message when invoked. That seems bad, since [the docs](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script) refer to it as being available, and the script uses it as the default!

You can reproduce it another way, using the URL that I found in issue #5952: https://dot.net/v1/dotnet-install.sh

1. Download it
2. Run it with the same args

I `diff`ed the scripts, and this version of `dotnet-install` doesn't have the `production` channel throwing an error, but it errors nonetheless.

## Expected  behavior

I would expect to that running the documented scripts pulls down a stable version of the runtime, and "just works" as the `master` channel does.

**Comment by johnbeisner** [comment]
Addressed via:
https://github.com/dotnet/cli/pull/7330
https://github.com/dotnet/cli/pull/7332
https://github.com/dotnet/cli/pull/7336
https://github.com/dotnet/cli/pull/7342
https://github.com/dotnet/cli/pull/7355
