### ISSUE TITLE
No executable found matching command "dotnet-migrate"

### ISSUE THREAD

**Issue by Daniel15** [dotnet/cli#6543]
## Steps to reproduce
Clone https://github.com/reactjs/React.NET and try to open `src/React.sln` in Visual Studio 2017

## Expected  behavior
It works

## Actual behavior
```
React.AspNet\React.AspNet.xproj: No executable found matching command "dotnet-migrate"
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16188
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by Daniel15** [comment]
It worked after I deleted the old `global.json` which contained:
```
{
  "sdk": {
    "version": "1.0.0-preview2-003121"
  },
  "projects": [ "src", "test" ]
}
```

Shouldn't it do this automatically?

**Comment by livarcocc** [comment]
No, doing this would mean that we would have had to release a new preview2 CLI, that would know to do that.
