### ISSUE TITLE
[MIGRATION]: NuGet content and tools files not migrated correctly 

### ISSUE THREAD

**Issue by Daniel15** [dotnet/cli#6544]
## Steps to reproduce
Repro project: [nugetbug.zip](https://github.com/dotnet/cli/files/982438/nugetbug.zip)

project.json:
```json
{
  "version": "0.0.1-*",
  "title": "NuGetBugExample",
  "packOptions": {
    "files": {
      "include": [
        "tools",
        "Content"
      ]
    },
  },
  "frameworks": {
    "net40": {}
  }
}
```

global.json:
```json
{
  "sdk": {
    "version": "1.0.0-preview2-003121"
  }
}
```

`Content/README.txt` and `tools/install.ps1` are just placeholders with any content

1. Run `dotnet pack` with the `1.0.0-preview2` tooling, and inspect the generated NuGet package. Notice that the `README.txt` and `install.ps1` are in the right place:
![](http://ss.dan.cx/2017/05/NuGet_Package_Explorer_-_nugetbug.0.0.1_07-22.34.36.png)
2. Delete `global.json`
3. Run `dotnet migrate` and `dotnet restore`
4. Run `dotnet pack` again.

## Expected  behavior
Package should be built exactly the same as it was with the old tooling

## Actual behavior
1. Warning is thrown while packing:
```
warning : Issue found with package 'nugetbug'. [C:\temp\nugetbug\nugetbug.csproj]
warning : Issue: PowerShell file outside tools folder. [C:\temp\nugetbug\nugetbug.csproj]
warning : Description: The script file 'content\tools\install.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package. [C:\temp\nugetbug\nugetbug.csproj]
warning : Solution: Move it into the 'tools' folder. [C:\temp\nugetbug\nugetbug.csproj]
warning : Issue: PowerShell file outside tools folder. [C:\temp\nugetbug\nugetbug.csproj]
warning : Description: The script file 'contentFiles\any\net40\tools\install.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package. [C:\temp\nugetbug\nugetbug.csproj]
warning : Solution: Move it into the 'tools' folder. [C:\temp\nugetbug\nugetbug.csproj]
```

2. `README.txt` and `install.ps1` are in the wrong place: `content/Content/readme.txt` and `content/tools/install.ps1`
![](http://ss.dan.cx/2017/05/NuGet_Package_Explorer_-_nugetbug.0.0.1_07-22.30.35.png)

This is due to an issue in the generated `csproj` file. The following segment is added to the file:
```xml
<ItemGroup>
  <None Update="tools\**\*;Content\**\*">
    <Pack>true</Pack>
  </None>
</ItemGroup>
```

However, it's missing the `PackagePath` to place the files in the right location. The correct XML looks like this, as per the documentation at https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#including-content-in-a-package
```xml
<ItemGroup>
  <Content Include="tools\**\*">
    <Pack>true</Pack>
    <PackagePath>tools\</PackagePath>
  </Content>
  <Content Include="Content\**\*">
    <Pack>true</Pack>
    <PackagePath>content\</PackagePath>
  </Content>
</ItemGroup>
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16188
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

cc @blackdwarf and @livarcocc

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#11

**Comment by Daniel15** [comment]
If migration issues belong in a different repro, you should update the docs at https://aka.ms/coremigration to reflect that 😄
