### ISSUE TITLE
DependencyContext.Default.RuntimeLibraries can't find referenced assemblies !!!

### ISSUE THREAD

**Issue by TimRowe** [dotnet/cli#6545]
## Steps to reproduce

I can't upload the .png file to show the details.

I used the code to find the referenced assemblies.
DependencyContext.Default.RuntimeLibraries.Where(l => l.Name.Contains("rdp")); 

But it can only discover the referenced project assemblies and the nuget assemblies. the dll assemblies which I added to the project can't Find. Why?

## Environment data

`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2307
