### ISSUE TITLE
dotnet-install.ps1 needs a option to manually tell it what zip to download and install.

### ISSUE THREAD

**Issue by johnwc** [dotnet/cli#6549]
When using `dotnet-install.ps1` to try to install a version of 1.0.4 on Nano server, it fails every time. There is not any documentation of the folder structure on the azure blob storage that contains the sdk and binaries. I can find plenty of links on https://www.microsoft.com/net/download/core to manually download the zip, but needed a way to tell the script to use one of those links instead of trying construct it from the azure blob storage. I modified the current version of `dotnet-install.ps1`, as of the date of this writing; to accept a url to download and install from, instead of trying to guess the correct channel and version.

I was able to go to https://www.microsoft.com/net/download/core and find the correct link to the version of the binaries zip file I needed to install. Then pass that into the updated script, telling it to use my link instead of doing the magic url shuffle.

The new command that worked for install 1.0.4.

`dotnet-install.ps1 -DownloadLink https://go.microsoft.com/fwlink/?LinkID=843402 -Version 1.0.0 -SharedRuntime -InstallDir D:\dotnet`

The main update(attached) to the script, other than adding the new param is at around line 393
```powershell
$DownloadLinks = @()
if ($DownloadLink){
  $DownloadLinks += $DownloadLink
  $SpecificVersion = $Version
  $CLIArchitecture = Get-CLIArchitecture-From-Architecture $Architecture
}
else{
  $AzureChannel = Get-Azure-Channel-From-Channel -Channel $Channel
  $CLIArchitecture = Get-CLIArchitecture-From-Architecture $Architecture
  $SpecificVersion = Get-Specific-Version-From-Version -AzureFeed $AzureFeed -AzureChannel $AzureChannel -CLIArchitecture $CLIArchitecture -Version $Version
  $DownloadLinks += Get-Download-Links -AzureFeed $AzureFeed -AzureChannel $AzureChannel -SpecificVersion $SpecificVersion -CLIArchitecture $CLIArchitecture
}
```

[dotnet-install.txt](https://github.com/dotnet/cli/files/985429/dotnet-install.txt)

**Comment by livarcocc** [comment]
@eerhardt Eric, is this one again due to the break in the channel?

**Comment by eerhardt** [comment]
No. This is a new feature ask of the script.

We have some work to do here to:

1. Rectify versions of the runtime and the SDK. There is no 1.0.4 of the SDK (yet). And I don't know if the SDK is supported on Nano or not. I've never tried.
2. Rectify the fwlinks that we document to customers with the dotnet-install script which doesn't work with these fwlinks. Maybe next to the fwlinks in the docs, we could have the dotnet-install command you can call to install the same version.

**Comment by livarcocc** [comment]
I think he meant 1.0.4 of the runtime. He should have been capable of specifying the channel and the version and have it work.

**Comment by johnwc** [comment]
Yes, i meant the runtime. As you can see that I used the SharedRuntime switch. Without this feature there is no way a user can guess what the correct channel and version values should be to get it to install. There's no standardization for the naming convention for channel. Y'all first used rel-1.0.0 and then later mentioned to use release/1.1.0 for current. This url addition needs to be added to the script, or y'all need to well document either the current folder structure for the azure storage blob or the actual list of working channels along with what versions are within each channel. I myself would prefer the documentation of the channels+versions so that we can just use the existing script.

Maybe store this documented channel/version list in a public text file that the the script can pull down and print to the console when say someone uses a -help command line switch. Then you can just update the file when new channels/versions are published.

**Comment by eerhardt** [comment]
The good news is that changes are in the works for the `dotnet-install` script that will eliminate the need to specify both channel and version when installing the shared runtime.  Instead you will be able to just say

`.\dotnet-install.ps1 -SharedRuntime -Version 1.0.3` 

and it will just work. This already works today to install the SDK, we just haven't updated the runtime installers yet.

Also, we are going to fix the "default" channel so you can just say:

`.\dotnet-install.ps1 -SharedRuntime` 

And it will just work, giving you the most appropriate default (probably the latest LTS version - feedback welcome).

**Comment by johnwc** [comment]
That'd be great, when is this update expected?

It was a pain trying to install IIS Administration API because it required 1.0.0, that's what prompted me to make this update. So maybe until that update gets implemented you can update the script with my minor change so that others can successfully install what they need. I attached the updated script, you can do a diff to see the few lines edited. Just a thought.

**Comment by eerhardt** [comment]
This update is expected to ship with .NET Core 2.0.  We will be working on it this week and next week, with the target for the work to be done by the end of next week.

For adding the new feature in the meantime, I'd like to avoid adding a new feature that won't be necessary in 2 weeks.  Then remove it and break someone who started depending on it.
