### ISSUE TITLE
dotnet-new enhancements

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#655]
Currently, as @davidfowl put it, `dotnet new` is a toy thing that helps people get up and running with *something* as soon as possible. What I would like to propose here is to add enhancements to make `dotnet new` slightly more powerful, but without adding too much complexity and also allow its basic scenarios to cover the full range of .NET Core capabilities. 

`dotnet new` should also not become, at least at this point, a full-featured scaffolding tool. We have suggestions to enable this via different commands (#515) but which way we would go with scaffolding, if we even go that way, is still TBD (To Be Determined). 

## Language-based templates
`dotnet new` should support all of the OOB languages in its templates. C# should be the default. However, the `dotnet new` command should accept a `--lang (-l)` parameter to override the language for the template. The `-lang` OOB valid values should be "c#", "f#" and "vb", predicated upon compiler support in the package. The effect is that each of these is that it will drop a source file (`Program.cs`) it the language specified as well as any other files that are needed for successful compilation and running. 

An error condition is raised if the mix between a project type and language is not compatible. 

## Creating an executable or a library
`dotnet new` should allow users to create either an executable or a library. By default, `dotnet new` will create an executable. If a `--lib` switch is specified, it will create a library. This means dropping a source file that doesn't contain a `Main()` method and a `project.json` file that doesn't contain the needed entries to create an executable binary after compile. The source file should only contain a sample public class. 

## Create a web app project.json
Thought not a scaffolding tool, `dotnet new` can help users get a working basic ASP.NET project. This should be done by using the `--web | -w` switch. The output is a valid `project.json` with ASP.NET packages as well as a valid `Startup.cs` with basic "Hello World" code. 

## Examples

`dotnet new`
	Create a simple executable "Hello World" console application that is immediately compilable. 
`dotnet new --lang f#`
	Create a simple executable "Hello World" console application that is immediately compilable using F# as a language. 
`dotnet new --lang c# --lib`
	Create a new C# library. 
`dotnet new --lang f# --lib`
	As above, but with F# as the language. 
`dotnet new --web`
	Create a new web project in C#. 

There are additional discussions in #647. 

/cc @richlander @davidfowl @piotrpMSFT

**Comment by borgdylan** [comment]
Should there be a way for external compilers to provide a dotnet-new-{langaugeName} so that dotnet-new would call that binary if the requested language is not c#/f#/vb?

**Comment by brthor** [comment]
@blackdwarf How does the `--web` param mix with the `--lib` and `--lang` params?

Is `--web` mutually exclusive to the other two?

**Comment by blackdwarf** [comment]
@brthor `--web` is exclusive to `--lib` and to the default (which should be `--bin` really) behavior. The `--lang` is compatible, though we *can* error out for states/combination that don't make sense. I.e. `dotnet new --web --lang f#`.

**Comment by brthor** [comment]
@blackdwarf Would it make sense to then have a `--mode` (or some other name) to which `web, bin, lib` are a parameter?

**Comment by blackdwarf** [comment]
@brthor hm, good suggestion. Though not `--mode` more like `--type`?

**Comment by blackdwarf** [comment]
New stuff based on the discussion above.

## Language-based templates
`dotnet new` should support all of the OOB languages in its templates. C# should be the default. However, the `dotnet new` command should accept a `--lang (-l)` parameter to override the language for the template. The `-lang` OOB valid values should be "c#", "f#" and "vb", predicated upon compiler support in the package. The effect is that each of these is that it will drop a source file (`Program.cs`) it the language specified as well as any other files that are needed for successful compilation and running. 

An error condition is raised if the mix between a project type and language is not compatible. 

## Creating a type of project
`dotnet new` should be capable of creating several different types of applications:
	1. Executable console applications
	2. Library
	3. Simple web application
Do to this, we have the `--type (-t)` switch which can take  the values of `bin`, `lib` and `web`. Each of these will drop a source file and a valid `project.json` with dependencies and configuration options filled in. 

## Options
`--lang | -l`
	Specify a language for the new application. Valid values are `c#`, `f#` and `vb`.
`--type | -t`
	Specify a type of the application to create. Valid values are `bin`, `lib` and `web`. 

## Examples

`dotnet new`
	Create a simple executable "Hello World" console application that is immediately compilable. 
`dotnet new --lang f#`
	Create a simple executable "Hello World" console application that is immediately compilable using F# as a language. 
`dotnet new --lang c# --type lib`
	Create a new C# library. 
`dotnet new --lang f# --type lib`
	As above, but with F# as the language. 
`dotnet new --type web`
	Create a new web project in C#.

**Comment by enricosada** [comment]
I'll do `--lang` as part of #647 .
If we need `dotnet new fsharp` instead of `dotnet new --lang f#` we can change it later. 
I think it's better to have `--lang` instead because `dotnet new` it's not going to be a full scaffolding tool, but as base generator is ok ( other tools can use it, and add more files/etc ).

:+1: for `dotnet new hello_world` to created the app inside `hello_world` directory 

My suggestions:

- put `Program.cs` inside a `src` directory, it's easier to understand and is what lots of people do ( rename a directory is easier and create directory and move ).

**Comment by khellang** [comment]
Is `#` valid in CLI arguments across the board? Could it be interpreted as a comment? I'd vote for `csharp`, `fsharp` and `vb` instead.

**Comment by enricosada** [comment]
@khellang yes, np about #.
I'll do alias to, so `--lang csharp` is the same as `--lang c#` , maybe `--lang cs` too

**Comment by khellang** [comment]
Sounds good :+1:

**Comment by khellang** [comment]
Also, `bin`? Why not `exe`? It is, after all, an executable? `lib` is also `bin`, right? :wink:

**Comment by blackdwarf** [comment]
@khellang yes, the `--lang csharp` was my first thought as well, but wanted to shorten it out (a lot of people on this GH repo think that `dotnet` is too long). So, am all for having language strings spelled out.

Now, for other stuff:

1. I think that for now `dotnet new` **should not** imply any directory structure at least for now. That is not to say that it shouldn't *create* a directory with a given name (a-la what @davidfowl suggested in #687). The reason is because I want to think some more about the implications this has on x-plat .NET console applications. 
2. `bin` is because it is a "binary executable" I guess. True, we could change it to `exe` but that has slightly more Windows-y context to me...any other nouns we can use here? :)

**Comment by enricosada** [comment]
added `--lang` with `csharp`, `c#` or `cs` aliases. same for `f#`

@blackdwarf about folder structure what are possible issues with directories? just curious

another possible solution is like lein:

`lein new [TEMPLATE] NAME`, with optional template name ( so `dotnet new web hello_world` mean web template inside hello_world directory, instead `dotnet new hello_world` generate default ( console? ) in `hello_world` directory

If we choose to have the directory as argument ( like `dotnet new hello_world` ) i think `dotnet new` can be used as console app to explore all templates/languages, with list and user input

**Comment by brthor** [comment]
@blackdwarf 
I think it'd be good if dotnet had some form of an output directory parameter, similar to #687

**Comment by blackdwarf** [comment]
@enricosada there are no issues *per se* just that if we add something by default, we are introducing a certain policy. That is also not bad, but would like to think about that policy some more etc. I am talking about having "src" as a default child of the dir that `dotnet new` creates. 

@brthor yeah, I asked @davidfowl to comment over here, since I would like to use this issue to track. 100% agree with the suggestion. :)

**Comment by blackdwarf** [comment]
New stuff as per discussions:

## Language-based templates
`dotnet new` should support all of the OOB languages in its templates. C# should be the default. However, the `dotnet new` command should accept a `--lang (-l)` parameter to override the language for the template. The `-lang` OOB valid values should be "c#", "f#" and "vb", predicated upon compiler support in the package. The effect is that each of these is that it will drop a source file (`Program.cs`) it the language specified as well as any other files that are needed for successful compilation and running. 

An error condition is raised if the mix between a project type and language is not compatible. 

## Creating a type of project
`dotnet new` should be capable of creating several different types of applications:
	1. Executable console applications
	2. Library
	3. Simple web application
Do to this, we have the `--type (-t)` switch which can take  the values of `bin`, `lib` and `web`. Each of these will drop a source file and a valid `project.json` with dependencies and configuration options filled in. 

## Creating the directory
Currently, `dotnet new` requires the user to create the directory for the new project/application. As part of this enhancement, `dotnet new` should accept a parameter that signifies a name of the new application, which translates into a directory that should be created if it doesn't exist. If the directory exists, the source artifacts should be placed in that directory. If the directory name is omitted, the command should error out. 

## Options
`--lang | -l`
	Specify a language for the new application. Valid values are `c#`, `f#` and `vb`.
`--type | -t`
	Specify a type of the application to create. Valid values are `bin`, `lib` and `web`. 

## Examples

`dotnet new`
	Create a simple executable "Hello World" console application that is immediately compilable. 
`dotnet new --lang f#`
	Create a simple executable "Hello World" console application that is immediately compilable using F# as a language. 
`dotnet new --lang c# --type lib`
	Create a new C# library. 
`dotnet new --lang f# --type lib`
	As above, but with F# as the language. 
`dotnet new --type web`
	Create a new web project in C#.

**Comment by shahid-pk** [comment]
> Creating the directory

> Currently, dotnet new requires the user to create the directory for the new project/application. As part of  this enhancement, dotnet new should accept a parameter that signifies a name of the new application, which translates into a directory that should be created if it doesn't exist. If the directory exists, the source artifacts should be placed in that directory. If the directory name is omitted, the command  should error out.

rust's  `cargo new dir_name` error out if  dir_name already exists if not create it.
ruby's `rails new dir_name` if dir_name exists create new project in it if not create it.

I think rust approach is better because someone could accidentally type name of an already existing directory which could contain another project or some other useful things.

**Comment by justinmchase** [comment]
The languages shouldn't be restricted to just those three. Inevitably other languages will want to plugin. It should accept any token and there should be a system for looking up the generator based on that token instead of just having 3 hard coded options.

**Comment by enricosada** [comment]
we can use prefix to search resource directories
For example `CSharp-Console` -> `CSharp-*` are the templates for c#

So new languages need only to add templates and choose name, alias

**Comment by justinmchase** [comment]
:+1: 

So
```
dotnet new --lang=boo --type=console
```

Would look into and load from a folder called `Boo-Console`? All a language dev would need to do would be to get that folder in that location?

**Comment by enricosada** [comment]
@justinmchase atm it's a folder inside the project, compiler as embedded resource.
But it's the same yes, that's what i have done with F#, add a new folder ( if `--lang` and `--type` is in place, is as simple as that )
If we want to extend dotnet new, there are lot of options, maybe we can download templates from nuget packages, using a list embedded inside `dotnet new`. but that's about extensibility, atm templates are embedded resources.

**Comment by blackdwarf** [comment]
@justinmchase @enricosada that seems like a good idea. For now, however, we want to actually get support for the three ones outlined above in. As @enricosada said, there isn't nothing that prevents this now. 

One thing about supporting new languages though is that they would also need to support all of the types of the projects that the user can specify with `--type`. For now it is console app (exectuable) and a library, so that should be easy enough.

**Comment by justinmchase** [comment]
@blackdwarf Well if the `langs` and the `types` where just by convention directory names then you could have an infinite number of kinds of projects, if it combination doesn't happen to exist then an error coudl be produced. 99% of projects would have the same basic 3 project kinds probably `bin`, `lib`, `web`.

But I could see someone adding a `unity` project template for example... If all it took was to get a folder in the right place and then it works that would be pretty easy.

**Comment by blackdwarf** [comment]
@justinmchase implementation-wise, sure, but I was more thinking about the user experience. If we have a lot of project types and a lot of languages, we can end up in a situation where the resulting matrix of support becomes rather...sparse. If this happens, the user would have a tougher time figuring out what comes with what.

**Comment by enricosada** [comment]
@blackdwarf add `dotnet new --templates`` to show a grouped view of templates by language?

another option is `dotnet new language/type` like you said with `_` ( i like `/` better )
like that `dotnet new fsharp/<TAB>` can expand with autocomplete. 

examples:

- `dotnet new fsharp/web`
- `dotnet new boo/console`
- without `/` the default language is csharp, so `dotnet new console` is like `dotnet new csharp/console`

maybe it's easier than `--lang` and `--type`

works with directory too `dotnet new fsharp/web hello_www`

That's my preferred atm, better than `--lang`

**Comment by blackdwarf** [comment]
@enricosada hmmmm...this is interesting. This could work. How would your autocomplete suggestion work above?

**Comment by GerjanOnline** [comment]
I like the idea of `dotnet new [lang]/[type]` :+1:

**Comment by enricosada** [comment]
@blackdwarf i was speaking about bash completion.
we can autogenerate suggestions ( the list is fixed at compile time ) and because format is `lang/type` is easy to do. partial list of `--type` based on `--lang` is more complicated
also a `--templates` can show the list ( than can be used by completion instead of generated list )

**Comment by justinmchase** [comment]
`dotnet new [lang]/[type]` :+1:

Bash and powershell can do dynamic auto-completion (we're all using bash anyway right?). People using cmd on windows could fallback to `--templates`.

**Comment by blackdwarf** [comment]
@justinmchase @enricosada so, to summarize, your suggestion is the following:

`dotnet new [lang]/[type]` 

Both `[lang]` and `[type]` are optional and they default to C# and console app respectively. We also introduce bash completion to help people find all of the potential options, though for now we will have just two for the types (console application and library) and two for the languages (cs and fs). 

When we add the directory name, it becomes something like this: `dotnet new [dirname] [lang]/[type]`. If the `[dirname]` is omitted, we default to ".". 

This looks good, actually. The only reason while I'm still somewhat on the fence is that this is still somewhat positional. What I mean by that is that if I accidentally switch these arguments, I will get some weird behavior. This is why I like the explicit parameters.

**Comment by akoeplinger** [comment]
I like `dotnet new [lang]/[type]`, it is short and easy to remember :+1:

If you accidentally switch the arguments then you'll just get an error as the combination won't exist.

**Comment by justinmchase** [comment]
@blackdwarf You could possibly leave off the `dirname` too. Until people complain about wanting to make new projects in other directories regularly it's probably fine to just say it only works on the current dir (similar to `npm init`). 

Also, addition of `--templates` option to get a full list of available templates. e.g.:
```
$ dotnet new --templates
csharp/console
csharp/library
fsharp/console
thridparty/testing
...
```

**Comment by cartermp** [comment]
I could easily see someone like myself screwing up the order all the time.  I think that would be fine if there is a helpful error message (e.g. `"library/fsharp" is not a valid combindation.  Did you mean "fsharp/library"?`).

**Comment by blackdwarf** [comment]
@cartermp too many jokes...must resist... :))

But yeah, that's my worry as well. We may end up having an invocation mechanism that is prone to these kinds of errors which leads to user dissatisfaction. 

@justinmchase people already asked for `dirname` which is why I wanted to include it here.

**Comment by enricosada** [comment]
@blackdwarf i have done with `--type` and `--lang` in #647 . 

after is merged i'll do `dotnet new [dirname] [lang]/[type]` .It's fast because it's already half implemented

- dirname:
    - if dir doesnt exists, create it. if exists error. ok @blackdwarf ?
    - `dotnet new .` create it in current directory
- `lang/type` => it's like use `--type` and `--lang`
    - alias, so `c#`, `csharp`, `cs` it's the same, case insensitive (already implemented in `--lang`)
    - if wrong type, a list of all type for this language are shown (like in my pr).
    - default lang is c#, so `dotnet new hello_world console` => c# console
    - default lang is c#, so `dotnet new hello_world invalidtype`:
        - use c#
        - show error `type 'invalidtype' doesnt exist for c#`
        - show list of avaiable types for c# (like now with invalid `--type`)
        ```
        dotnet new --type invalidtype
        Unrecognized type: invalidtype
        Avaiable types for C# :
        - Console
        ```
    - example `dotnet new hello_world fsharp/invalidtype`:
        - use f#
        - show error `type 'invalidtype' doesnt exist for f#`
        - show list of avaiable types for f#
        ```
        dotnet new fsharp/invalidtype
        Unrecognized type: invalidtype
        Avaiable types for F# :
        - Console
        ```

**Comment by justinmchase** [comment]
:+1: 

I think `--all` is ok but I would have probably gone with `--list` or `--ls` or in traditional microsoft robust style `--list-all`

**Comment by enricosada** [comment]
really better @justinmchase i'll update my comment

**Comment by blackdwarf** [comment]
@enricosada looks really good, thanks for the effort, you rock! Go with the error, it is a pretty predictable behavior. I'm worried about "." because it break symmetry with `dotnet run`, as in, `dotnet run` doesn't require a ".". 

Agreed with @justinmchase on `--ls` actually. :)

**Comment by enricosada** [comment]
@blackdwarf the `.` make deterministic the arguments ( first = dir (file), second = lang/type (list) ). 
Maybe it's easier for autocomplete (i dont know, just askin, not really an expert about that)
I'll implement it, let's see, it's not too much a problem

**Comment by blackdwarf** [comment]
@enricosada that is a very good point. OK, let's leave it in. It would make sense, as in, `dotnet run` is bound to a project (i.e. it cannot run without a project) while `dotnet new` is about making a **new** project. :) Symmetry is important... :)

**Comment by enricosada** [comment]
ok, #1027 got merged ( `--type`, `--lang` ).
i'll send another to make `dotnet new hello_world lang/type` as discussed in https://github.com/dotnet/cli/issues/655#issuecomment-173975250 . 
we can discuss about `.` or optional dir in the pr

**Comment by blackdwarf** [comment]
@enricosada thanks! Great to see this come in!

**Comment by enricosada** [comment]
ok added `dotnet new hello_world lang/type` in #1124 , pls review :smile: 

I'll add `-ls` or `--list` after this one

**Comment by blackdwarf** [comment]
Closing this one in favor of the proposal in #2052.
