### ISSUE TITLE
dotnet-dev-1.0.4 package fails to install on Ubuntu

### ISSUE THREAD

**Issue by ed-alertedh** [dotnet/cli#6558]
## Steps to reproduce
(taken from: https://www.microsoft.com/net/core#linuxubuntu )
```
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
sudo apt-get update
sudo apt-get install dotnet-dev-1.0.4
```
## Expected  behavior
dotnet-dev-1.0.4 package installs 

## Actual behavior
```
$ sudo apt-get install dotnet-dev-1.0.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-dev-1.0.4 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

If I run ```cat /var/lib/apt/lists/apt-mo.trafficmanager.net_repos_dotnet-release_dists_yakkety_main_binary-amd64_Packages``` then I can confirm what apt-get is saying. There is no listing for ```dotnet-sharedframework-microsoft.netcore.app-1.1.2```, only for ```dotnet-sharedframework-microsoft.netcore.app-1.1.1```

## Workaround
I can install ```dotnet-dev-1.0.3``` successfully.

## Environment data
I'm on Ubuntu 17.04 (zesty) but apt-get appears to accept the 16.10 packages. I don't think the issue is caused by the newer version of Ubuntu

`dotnet --info` output:
N/A

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2339
