### ISSUE TITLE
Remove Nuget.Config from `dotnet new` drop for release

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#656]
The nuget.config drop was added as a temporary step until the StdLib is available on nuget.org.

When this is true, we should remove the nuget.config drop.

**Comment by Petermarcu** [comment]
@brthor , We need to make sure this happens for RC2

**Comment by brthor** [comment]
@weshaggard 
What is the version that will be available via nuget?

I think it would be best to publish to nuget before dropping the NuGet.config here or I expect we'll see CI failures. 

Does that follow our process or is there another way you think we should go about this?

**Comment by weshaggard** [comment]
@Petermarcu what is the push to remove this for RC2? Doing so will require more end-game coordination which might be tricky.

**Comment by Petermarcu** [comment]
We need people that use dotnet new to use the packages from NuGet and not from the MyGet servers.

We also can't publish to NuGet ahead of time.

**Comment by brthor** [comment]
We'll be taking on a test gap here to make this happen. If folks think that's acceptable, I'll make the changes.
