### ISSUE TITLE
msbuild on Ubuntu is missing?

### ISSUE THREAD

**Issue by dluc** [dotnet/cli#6576]
I'm trying to setup an Ubuntu environment where I can use `dotnet` and `msbuild` for cross platform development.

I've tried several combinations, but I always end up with an environment without the `msbuild` command.
Could you point to the DEB package containing the `msbuild` command please?

Some options I've tried:
* Ubuntu 17.04
* Ubuntu 16.10
* Ubuntu 16.04
* Ubuntu 14.04

Some problems I've encountered
* Dependency on `libicu52` which is not installable
  > dotnet-sharedframework-microsoft.netcore.app-1.1.1 : Depends: libicu52 (>= 52\~m1-1~) but it is not installable
  > dotnet-dev : Depends: libicu52 (>= 52\~m1-1~) but it is not installable
  > Package 'libicu52' has no installation candidate
* `dotnet-dev-1.0.0-featmsbuild-003542` depends on `libstdc++6 (>= 5.2)` which is not available
  > dotnet-dev-1.0.0-featmsbuild-003542 : Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is to be installed
* dotnet-dev-ubuntu.16.04-x64.latest.tar.gz doesn't contain `msbuild`
* https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.1/dotnet-sdk-ubuntu.16.04-x64.latest.deb doesn't contain `msbuild`
* Circular dependency between `dotnet-sharedframework-microsoft.netcore.app-1.1.1` and `dotnet-sharedframework-microsoft.netcore.app-1.0.4` both need to be explicitly installed (`apt-get` should do it automatically)

**Comment by dasMulli** [comment]
msbuild is supposed to be invoked as a sub-command of the `dotnet` command - does that work?:

```
dotnet msbuild your.csproj
```

**Comment by livarcocc** [comment]
@dasMulli is correct. There is no separate msbuild executable cross-plat. You need to invoke it though `dotnet msbuild`.

Also, for the 1.0 CLI, we support up to Ubuntu 16.10. For 2.0 CLI, we have a linux portable x64 distro that works on multiple linux distros.

I am going to close the issue. If dotnet msbuild does not work for you, please re-activate.

**Comment by dluc** [comment]
thanks, I will try that.

In **Ubuntu 16.04** though I cannot install neither `dotnet` or `dotnet-dev`

```
echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
apt-get update
apt-get install dotnet-dev
```

Result:
```
The following packages have unmet dependencies:
 dotnet-dev : Depends: libicu52 (>= 52~m1-1~) but it is not installable
```

I'll try Ubuntu 16.10

**Comment by catb0t** [comment]
in later Ubuntu you have to use `sudo snap install --classic dotnet-sdk`
