### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by jchannon** [dotnet/cli#6591]
## Steps to reproduce
Installed 2.0 preview 1 CLI for OSX and ran `dotnet --info`

## Expected  behavior
It should output info

## Actual behavior
See screenshot: 
<img width="895" alt="screen shot 2017-05-13 at 14 39 41" src="https://cloud.githubusercontent.com/assets/105126/26025977/8522355e-37ea-11e7-9123-5317763e414c.png">

## Environment data
`dotnet --info` output:

Unable to provide as tooling is broken

**Comment by dasMulli** [comment]
OS X 10.12 is required now (which also has `clock_gettime()`)

**Comment by dasMulli** [comment]
Was just talking about it in https://github.com/dotnet/core/issues/640#issuecomment-301248640

**Comment by jchannon** [comment]
OK thanks - didn't see any requirements in release notes or download page. Might be worth adding 😄

**Comment by phillip-haydon** [comment]
@jchannon it says in the message it's built for 10.12! :)

**Comment by dasMulli** [comment]
Depending on where you're coming from you'll get different instructions 😢
