### ISSUE TITLE
Doesn't support packaging pre-release deps as rtm release

### ISSUE THREAD

**Issue by haf** [dotnet/cli#6593]
Given: Proj A-v1.0, dep B-v1.0-beta1.

Then: A cannot be packaged as a nuget with `dotnet pack` despite being v1.0.

Expected: to be packed.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5228

**Comment by haf** [comment]
@livarcocc No, don't close it; it's already been debated for two years and fixed in the nuget repo: https://github.com/NuGet/Home/issues/1365 so it's up to this project to ensure that commit comes into this repo

**Comment by dasMulli** [comment]
Looks like this is already in for 2.0 preview 1. When I try to do this, only warnings are reported and the nupkg is built.
The warnings can be turned off with `<NoPackageAnalysis>true</NoPackageAnalysis>`

**Comment by haf** [comment]
I need it for the non-preview version. This issue can track that.

**Comment by haf** [comment]
PIng, how do I release expecto and make the build pass?? https://github.com/haf/expecto#expecto

**Comment by livarcocc** [comment]
You mean for 1.0? We don't intend to port this change from 2.0 to 1.0.

**Comment by haf** [comment]
@livarcocc Yes, that's correct. Porting; it's open source? Can't we just bump the nuget executable version for v1? It's backwards-compatible, right?
