### ISSUE TITLE
Console encoding is wrong for apps targeting .NET Core 1.1

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#6597]
## Steps to reproduce
- `dotnet new console`
- Change `TargetFramework` to `netcoreapp1.1`
- `dotnet restore`
- Change body of main method to `Console.WriteLine("Bienvenue à .Net!");`
- `dotnet run`

## Expected  behavior
Output is `Bienvenue à .Net!`

## Actual behavior
Output is `Bienvenue ├á .Net!`

## Comments
I don't know if the issue is in the CLI, the host, or what.  I encountered this in https://github.com/dotnet/sdk/pull/1208, which changed the SDK tests to target .NET Core 2.0, so it may have something to do with a .NET Core 2.0 process launching a .NET Core 1.1 process.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview1-005865)

Product Information:
 Version:            2.0.0-preview1-005865
 Commit SHA-1 hash:  57e31a0d13

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\git\dotnet-sdk\.dotnet_cli\sdk\2.0.0-preview1-005865\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002091-00
  Build    : fa62d01e00eaec93f228548f2ee00cd81c148066

**Comment by nguerrera** [comment]
In .NET Core 1.x, you had to register the encoding code pages provider for Console.WriteLine to work with non-ASCII range text. In .NET Core 2.0, Console works without it.

**Comment by nguerrera** [comment]
See https://github.com/dotnet/corefx/issues/14496
