### ISSUE TITLE
MSBuild SDK resolver should probe for dotnet.exe location on PATH instead of searching program files

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#6601]
Currently, the msbuild sdk resolver looks for dotnet.exe in ProgramFiles or ProgramFiles(x86) to pass as the exe_dir to hostfxr.

Instead, it should find the location of dotnet.exe on the PATH and pass that to hostfxr.

**Comment by livarcocc** [comment]
https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.MSBuildSdkResolver/MSBuildSdkResolver.cs#L105
