### ISSUE TITLE
2.0.0 preview errors

### ISSUE THREAD

**Issue by kylesferrazza** [dotnet/cli#6605]
I get the following error message with any dotnet command.
I installed dotnet using the SDK Binaries for the 2.0.0 preview (on [this page](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview1-download.md), row Linux, column SDK binaries)
## Steps to reproduce
`dotnet --version`

## Expected  behavior
`2.0`

## Actual behavior
`Error: assembly specified in the dependencies manifest was not found -- package: 'runtime.linux-x64.microsoft.netcore.app', version: '2.0.0-preview1-002111-00', path: 'runtimes/linux-x64/native/System.Native.a'`

**Comment by livarcocc** [comment]
Which linux distro are you trying to run this at?

**Comment by kylesferrazza** [comment]
Arch

**Comment by livarcocc** [comment]
I believe there is a separate build for arch that is not in that page.

@eerhardt can you confirm that?

**Comment by eerhardt** [comment]
Arch is "supported by the Community" and TBD on our https://github.com/dotnet/core/blob/master/roadmap.md#net-core-20---supported-os-versions page.

We don't have an officially supported build for Arch as far as I am aware.

**Comment by livarcocc** [comment]
I am closing this here. If you want to ask for official support to Arch, I would file an issue under dotnet/core-setup.
