### ISSUE TITLE
Fail to restore a dotnet netstandard 2.0 classlib with latest preview 2 build (6082)

### ISSUE THREAD

**Issue by singlis** [dotnet/cli#6619]
## Steps to reproduce
Install the latest toolset 2.0.0-preview2-006082 using the windows installer.
Open a command line prompt and type:
 * dotnet new classlib
 * dotnet restore

## Expected  behavior
Expected behavior is that the restore should succeed with no errors

## Actual behavior
Restore fails with the following error:
Running 'dotnet restore' on C:\source\dev\test\test.csproj...
Restore failed.
Output from command:
  Restoring packages for C:\source\dev\test\test.csproj...
C:\Program Files\dotnet\sdk\2.0.0-preview2-006082\NuGet.targets(98,5): error : Unable to resolve 'NETStandard.Library (>= 2.0.0-preview2-25303-01)' for '.NETStandard,Version=v2.0'. [C:\source\dev\test\test.csproj]
  Generating MSBuild file C:\source\dev\test\obj\test.csproj.nuget.g.props.
  Generating MSBuild file C:\source\dev\test\obj\test.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\source\dev\test\obj\project.assets.json
  Restore failed in 284.7 ms for C:\source\dev\test\test.csproj.

  Errors in C:\source\dev\test\test.csproj
      Unable to resolve 'NETStandard.Library (>= 2.0.0-preview2-25303-01)' for '.NETStandard,Version=v2.0'.

  NuGet Config files used:
      C:\Users\(xxxUserxxx)\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Users\(xxxUserxxx)\.dotnet\NuGetFallbackFolder
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

## Environment data
`dotnet --info` output:
C:\source\dev\test>dotnet --info
.NET Command Line Tools (2.0.0-preview2-006082)

Product Information:
 Version:            2.0.0-preview2-006082
 Commit SHA-1 hash:  6453cb4e15

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006082\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25309-07
  Build    : 41f5fc94eedc889f086800c23f35bf14a8c75a9f

**Comment by singlis** [comment]
Im assuming the nuget feed needs to be updated to 25303-01? 301 looks to be the latest:

https://www.nuget.org/packages/NETStandard.Library/2.0.0-preview1-25301-01

**Comment by singlis** [comment]
Ah, actually it looks like I need to be referencing:
https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

**Comment by livarcocc** [comment]
This is a known issue where the lzma archive is not matching the runtime inserted into the CLI. We are discussing alternatives on how to get this working again, now that ASP.NET is the one producing the lzma archive.

Meanwhile, adding the dotnet-core feed is the workaround to get unblocked.
