### ISSUE TITLE
Can't Install templates in 2.0.0preview1 with dotnet new -i

### ISSUE THREAD

**Issue by JonathanLoscalzo** [dotnet/cli#6625]
## Steps to reproduce

> Install dotnet 2.0.0preview1 on Win10
> Start a GitBash
> Run the following command in Terminal
> dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

### Expected behavior
The CLI downloads the templates, and reports installing them, then lists them in the available templates for "dotnet new"

### Actual behavior
After a time, show list of Templates, but not install any:
$ dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

## Environment data

> .NET Command Line Tools (2.0.0-preview1-005977)
> 
> Product Information:
>  Version:            2.0.0-preview1-005977
>  Commit SHA-1 hash:  414cab8a0b
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.10240
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#824
