### ISSUE TITLE
CLI should install fallback folder machine-wide when installing machine-wide

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#6636]
## Steps to reproduce
Install machine-wide CLI

## Expected  behavior
Fallback folder is installed for all users.

## Actual behavior
Fallback folder is only installed for current user.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

I know we've discussed this before, so feel free to dup this to another issue if you have one.

The CLI installs to a machine wide location, there is no reason it should place pre-installed packages in a per-user location.  It should register them for all users and put them in a machine wide location.

/cc @livarcocc @jinujoseph

**Comment by livarcocc** [comment]
Our plan is to do that for installers (MSI, pkg or deb). For sure for MSIs. I need to look if NuGet has a machine wide location nuget.config that I can use cross-plat to set the cache.

For zips and tarballs, we will continue to do things on a per-user way.

**Comment by ericstj** [comment]
zips and tarballs-absolutely.

For machine wide on windows, NuGet has [C:\Program Files (x86)\NuGet\Config](https://github.com/NuGet/NuGet.Client/blob/ea1d1395d0c3dd7b5e22b873cfd71bb8cfb9062a/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L26). @jinujoseph and @joeloff have a wixlib that's been shared for folks in VS that want to contribute to this.  Make sure to coordinate with them so that we don't end up with more than one copy of the offline folder.

Not sure the location NuGet checks on non-windows.

**Comment by livarcocc** [comment]
We are already on the same page for 2.0 CLI. For 2.0 packages, VS no longer produces and carries its own offline cache. Only for 1.0. That's the path we will go with.
