### ISSUE TITLE
dotnet build uses DebugType=portable for projects targeting  .NET Framework

### ISSUE THREAD

**Issue by innix** [dotnet/cli#6637]
`dotnet build` by default uses `DebugType` value of `portable` which I believe is only valid for .NET Core projects. When `portable` pdb's are emitted for .NET Framework projects, they just get ignored. This can be confirmed by looking at a stack trace.

## Steps to reproduce
1. Create a new console app:
```
$ mkdir foo
$ cd foo
$ dotnet new console
```

2. In the `.csproj` file, change the `TargetFramework` to `net462` (or whatever full .NET Framework version you have installed).

3. Change `Program.cs` to this:
```csharp
using System;

namespace foo
{
    class Program
    {
        static void Main(string[] args) => A();

        static void A() => B();
        static void B() => C();
        static void C() => throw new Exception("Oh no!");
    }
}
```

4. Run the app:
```
$ dotnet run
```

## Expected  behavior
I expect source file names and line numbers to be present in the stack trace:
```
Unhandled Exception: System.Exception: Oh no!
   at foo.Program.C() in C:\Users\Phil\Desktop\foo\Program.cs:line 11
   at foo.Program.B() in C:\Users\Phil\Desktop\foo\Program.cs:line 10
   at foo.Program.A() in C:\Users\Phil\Desktop\foo\Program.cs:line 9
   at foo.Program.Main(String[] args) in C:\Users\Phil\Desktop\foo\Program.cs:line 7
```

That is the stack trace you get when running it as a `netcoreapp1.1` app, so a stack trace for a `net462` app should be identical, right?

## Actual behavior
This is what you actually get when targeting `net462`:
```
Unhandled Exception: System.Exception: Oh no!
   at foo.Program.C()
   at foo.Program.B()
   at foo.Program.A()
   at foo.Program.Main(String[] args)
```

It can easily be fixed by changing the `DebugType` to `full`/`pdbonly` in your `.csproj` file but the default behaviour seems wrong.

## Environment data
`dotnet --info` output:
```
$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by livarcocc** [comment]
@tmat Is this expected? Should portable PDBs work for full framework TFMs?

**Comment by tmat** [comment]
(by work I mean the stack trace reporting line numbers and file names)

**Comment by livarcocc** [comment]
I think it may still make sense for any full framework that is not 471, to default to a different debug type. I will move this issue to dotnet/sdk.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/sdk#1238
