### ISSUE TITLE
Question: Using a nightly preview, can VS2017 recognize that runtime.

### ISSUE THREAD

**Issue by brentschmaltz** [dotnet/cli#6643]
## Steps to reproduce
Install 2.0 as per https://github.com/dotnet/corefx/blob/ec7735c9f0607fed03eda1e11a79cf147e760b05/Documentation/project-docs/dogfooding.md

Adjust tests to use that runtime.

## Expected  behavior
Unknown, can VS2017 build and run the tests???

## Actual behavior
VS2017 cannot build and run the tests

## Environment data
`dotnet --info` output:

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\brentsch\.dotnet\x64\sdk\2.0.0-preview2-006082\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25317-03
  Build    : 1af49a2602515077f7e1037be808b42f69d30360

**Comment by livarcocc** [comment]
Yes. It is supposed to work. Though I would stick with preview1-005977, which was our preview1 build.

Though, what are you seeing as a failure when trying to build and run tests.

**Comment by brentschmaltz** [comment]
@livarcocc I have to use Preview2 as I am testing a C14n XML that was not in Preview1.

**Comment by livarcocc** [comment]
How did you install the 2.0 CLI? Right now, VS won't find it unless it is under your Program Files. So, for that I would recommend installing the 2.0 CLI through the MSI.

We are fixing that here: https://github.com/dotnet/cli/pull/6669

**Comment by brentschmaltz** [comment]
@livarcocc that was it, thanks.
