### ISSUE TITLE
Common linux runtime target does not pull in dependencies

### ISSUE THREAD

**Issue by yevster** [dotnet/cli#6648]
Per the [release announcement](https://blogs.msdn.microsoft.com/dotnet/2017/05/10/announcing-net-core-2-0-preview-1/) "You can build apps that target Linux as a single operating system." 

This does not seem to work on 64-bit Mint 18.1.

## Steps to reproduce
1. Extract the All-linux download (https://download.microsoft.com/download/0/6/5/0656B047-5F2F-4281-A851-F30776F8616D/dotnet-dev-linux-x64.2.0.0-preview1-005977.tar.gz), add to path, etc.
2. `mkdir ~/test`
3. `cd ~/test`
4. `dotnet new console`
5. `dotnet restore -r Linux`
6. `dotnet dotnet publish -r Linux -c Release`
7. `cd bin/Release/netcoreapp2.0/Linux/publish/`
8. `dotnet test.dll`

## Expected  behavior
"test.dll" should be runnable. The publish folder should contain an executable file and all dependencies. If the runtime ID `linuxmint.18-x64` is substituted for `Linux` in the steps above, everything works. 

## Actual behavior
But with the steps as specified, the publish directory contains only the following contents:
```
-rw-r--r-- 1 yevster yevster  400 May 20 03:26 test.pdb
-rw-r--r-- 1 yevster yevster 4608 May 20 03:26 test.dll
-rw-r--r-- 1 yevster yevster   26 May 20 03:26 test.runtimeconfig.json
-rw-r--r-- 1 yevster yevster 4436 May 20 03:26 test.deps.json
```
Running `dotnet test.dll` inside that directory yields:
```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/yevster/src/test/bin/Release/netcoreapp2.0/Linux/publish/'.
```
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     linuxmint
 OS Version:  18.1
 OS Platform: Linux
 RID:         linuxmint.18.1-x64
 Base Path:   /home/yevster/Downloads/dncpreview/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

```
Apologies in advance if this report is premature or if I'm using the wrong runtime ID. I would imagine, however, that had I attempted anything unwholesome, I would have seen an error message.

**Comment by dasMulli** [comment]
Does `linux-x64` work for you? That's the intended "single linux" runtime identifier.

**Comment by yevster** [comment]
Yep, that works. Thanks.

Question: is it not a bug that I can provide any arbitrary string of garbage to the -r parameter and see no error?

```
yevster@shostakovich ~/test $ dotnet restore -r DonaldTrump
  Restoring packages for /home/yevster/test/test.csproj...
  Writing lock file to disk. Path: /home/yevster/test/obj/project.assets.json
  Restore completed in 141.85 ms for /home/yevster/test/test.csproj.
  
  NuGet Config files used:
      /home/yevster/.nuget/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
      /home/yevster/.dotnet/NuGetFallbackFolder


yevster@shostakovich ~/test $ dotnet publish -c Release -r DonaldTrump
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  test -> /home/yevster/test/bin/Release/netcoreapp2.0/DonaldTrump/test.dll
  test -> /home/yevster/test/bin/Release/netcoreapp2.0/DonaldTrump/publish/

yevster@shostakovich ~/test $ ls bin/Release/netcoreapp2.0/DonaldTrump/
publish         test.dll  test.runtimeconfig.dev.json
test.deps.json  test.pdb  test.runtimeconfig.json
```

**Comment by livarcocc** [comment]
No, any one can create a package with assets for a random rid. We can't really try to guess what are all the available ones for perpetuity. For instance, you could create one for Linux that simply pulled in linux-x64.

**Comment by yevster** [comment]
I am not suggesting restricting the runtimes to a finite set of IDs. I am suggesting erroring out if the specified runtime ID is not defined in `runtime.json` of any referenced package.

**Comment by livarcocc** [comment]
I have a bug for that already: https://github.com/dotnet/cli/issues/2894.
