### ISSUE TITLE
Does package trimming not work for SCD deployments?

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#6653]
A `netcoreapp2.0` app published as a SCD that only requires the following explicitly listed package refs ...

* Microsoft.AspNetCore.Diagnostics
* Microsoft.AspNetCore.Server.Kestrel
* Microsoft.AspNetCore.Server.IISIntegration
* Microsoft.Extensions.Logging.Console
* Microsoft.AspNetCore.StaticFiles
* Microsoft.AspNetCore.Mvc

... comes in at ~57MB. Substituting those packages for a single ref to the `Microsoft.AspNetCore.All` meta-package results in an app of ~78MB with the extra (unnecessary) packages and folders (of packages) shown below.

Does the trimming feature just not work with SCD deployments?

![image](https://cloud.githubusercontent.com/assets/1622880/26280881/50770170-3daa-11e7-99c3-655ee1d52ac7.png)

**Comment by dasMulli** [comment]
What is your expectation here?
I'd expect all dependencies I specify to be part of a self-contained deployment.
FDDs just don't copy things that are expected to already be on the destination machine in e.g. `C:\Program Files\dotnet\store\x64\netcoreapp2.0`

**Comment by GuardRex** [comment]
> What is your expectation here?

That "trimming" as described by @DamianEdwards will remove packages that the app doesn't use. For example, nothing in this app has anything to do with SQLite, but the packages are there. Same for identity, EF, and the others you see there.

@DamianEdwards at //Build https://channel9.msdn.com/Events/Build/2017/C9L18 at 7:48 ...

> We have a new package ... `AspNetCore.All`-of-it, and you reference that and we give you all of the API. And, we built new processes that ensure that we only deploy the parts of it that you would use, effectively, which is nice.

... led me to believe that none of the packages I list above would be deployed (i.e., appear in the *publish* output) for this app. However, it's not clear what the "effectively" language means.

I'm just pointing out that this isn't the behavior I was *hoping* to see for "trimming," and I've ended up going back to listing the six explicit package references that are required for this test app to run.

**Comment by DamianEdwards** [comment]
The feature doesn't apply to SCD. It actually isn't trimming based on use, but rather on a pre-defined manifest of what's already installed in the new "runtime store" on the destination machine. True "package trimming" based on use is coming at a later time. For SCD deployments will recommend you continue to reference just those packages you need.

**Comment by GuardRex** [comment]
Thanks @DamianEdwards for explaining, but you can see how easy it would be to inadvertently assume otherwise.
