### ISSUE TITLE
Unable to clone and open solution

### ISSUE THREAD

**Issue by Mardoxx** [dotnet/cli#6654]
## Steps to reproduce
1. Clone repo
2. Open Microsoft.DotNet.Cli.sln

## Expected  behavior
Solution opens without errors.

## Actual behavior

```
---------------------------
Microsoft Visual Studio
---------------------------
The imported project "C:\Users\Owner\Documents\cli\artifacts\obj\GitCommitInfo.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Owner\Documents\cli\dir.props
---------------------------
OK   
---------------------------
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by Mardoxx** [comment]
Solution for this is to run `build.bat` which pulls missing files into artifacts. Would be good to have some documentation on this or a script which pulled/generated missing files!

**Comment by livarcocc** [comment]
Yes. This is by design for the CLI. You need to run a build from the command line at least once. Though, to be completely honest, we are not really sure how far VS will take you for the CLI due to a bunch of customizations we have in the CLI build. Something we want to address at some point.

**Comment by livarcocc** [comment]
And preview2-1 will definitely not be able to handle the CLI.
