### ISSUE TITLE
WSL dotnet clean "Failed to create prime the NuGet cache. restore failed with: 1"

### ISSUE THREAD

**Issue by ghost** [dotnet/cli#6657]
## Steps to reproduce
Navigate to project root and run dotnet clean

## Expected  behavior
???? Message indicating clean completed???

## Actual behavior
```
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 5411 ms
Expanding 100% 14996 ms
Failed to create prime the NuGet cache. restore failed with: 1
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.
```

This command actually happens everytime I run a dotnet command. Do I not have the WSL environment setup right?

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
```

**Comment by ellismg** [comment]
What version of windows are you on?

As a workaround you can try setting DOTNET_SKIP_FIRST_TIME_EXPERIENCE to 1 in bash.  That will stop the nuget cache priming (but it's possible that some dotnet restore operation will fail later).

**Comment by horney0824** [comment]
encountered same issue under ubuntu 16.04@vmplayer

**Comment by livarcocc** [comment]
I just tried this with SDK 2.1.4 and ubuntu 16.04 and everything worked as expected.

Starting on 2.0, we are now running the cache expansion as part of the native installer run. Also, expanding the cache now is much simpler. We are just expanding an archive, versus running a separate restore for it.

Given that, I am going to close this issue. If this is still a problem, just comment with some details and we can re-activate it.
