### ISSUE TITLE
[Migration] - .DotNet.Props missing after project upgrade

### ISSUE THREAD

**Issue by dmstrat** [dotnet/cli#6658]
## Steps to reproduce
Download Hello World Sample App
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/archive/master.zip
Extract locally
Open Visual Studio 2017 (Enterprise Edition for me)
Open dotnet-docs-samples\appengine\flexible\HelloWorld\HelloWorld.sln
Studio will perform one-way migration

## Expected  behavior
Project should open and be able to start/debug immediately.

## Actual behavior
HelloWord Project unable to load receiving errors about .DotNet.Props files mssing and going to multiple locations to find
error : The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\DotNet\Microsoft.DotNet.Props" was not found. Also, tried to find "DotNet\Microsoft.DotNet.Props" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0" . These search paths are defined in "C:\Users\{userid}\AppData\Local\Microsoft\VisualStudio\15.0_c0954f0f\devenv.exe.config". Confirm that the path in the declaration is correct, and that the file exists on disk in one of the search paths. C:\Users\{userid}\Downloads\rdkafka-dotnet-master\rdkafka-dotnet-master\examples\Benchmark\Benchmark.xproj 

## Workaround
https://developercommunity.visualstudio.com/content/problem/2951/project-doesnot-open-because-of-missing-props.html 
This URL provided the work around required.  Deleting the project.json and HelloWorld.xproj allowed the solution to load, but showed HelloWorld.csproj not loaded.  Removing and adding the project back allowed for the project to work as expected.

## Environment data
Windows 7 Pro with multiple Visual Studio installations. 
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#42
