### ISSUE TITLE
dotnet restore failing in VSTS task

### ISSUE THREAD

**Issue by singharun1990** [dotnet/cli#6659]
## Steps to reproduce
In VSTS Build definition we have a task  to restore one of the dotnet core project  before building it so that we are able to resolve all the dependencies and it fails with following error:
"C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj -v diag
C:\Program Files\dotnet\sdk\1.0.3\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /m /t:Restore /v:m /verbosity:diag d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj
  Restoring packages for d:\a\1\s\UserDataStoreService.Core\UserDataStoreService.Core.csproj...
  Restoring packages for d:\a\1\s\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoftxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxxxx.. [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]

We are using a custom package as well

getting same error from running dotnet restore locally as well

PS C:\Repos\UserDataStoreService\UserDataStoreService> dotnet restore .\UserDataStoreService.csproj
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj...
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService.Core\UserDataStoreService.Core.csproj...
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj...
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\Repos\UserDataStoreService\UserDataStoreService.Persistance\obj\project.assets.json
  Lock file has not changed. Skipping lock file write. Path: C:\Repos\UserDataStoreService\UserDataStoreService.Core\obj\project.assets.json
  Restore completed in 1.28 sec for C:\Repos\UserDataStoreService\UserDataStoreService.Core\UserDataStoreService.Core.csproj.
  Restore completed in 1.28 sec for C:\Repos\UserDataStoreService\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj.
  Restore completed in 3.65 sec for C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj.
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoftxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxxxx.\r [C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj]

## Actual behavior
"C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj -v diag
C:\Program Files\dotnet\sdk\1.0.3\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /m /t:Restore /v:m /verbosity:diag d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj
  Restoring packages for d:\a\1\s\UserDataStoreService.Core\UserDataStoreService.Core.csproj...
  Restoring packages for d:\a\1\s\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoftxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxxxx.. [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5265
