### ISSUE TITLE
additionalDeps should be installed under the SDK folder

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#6668]
In order to keep the root of the dotnet folder simple, we need to avoid adding lots of little folders. In addition, we should aim for the sdk install to be putting things in the sdk folder. Lets come up with a plan to get it out of the root in 2.0 and also make sure we have a plan for what needs to happen when new runtimes ship.

**Comment by nguerrera** [comment]
@livarcocc Where is the path to these additionalDeps consumed? Grep is failing me.

**Comment by Petermarcu** [comment]
@ramarag @gkhanna79 to help.

**Comment by gkhanna79** [comment]
I am not sure I follow the question. In general, the path to the additionalDeps is custom and set up by whoever is setting up the environment.

**Comment by nguerrera** [comment]
What is using dotnet-dir/additionalDeps?

**Comment by gkhanna79** [comment]
In Azure, ASP.NET relies on it for Azure Diagnostics. @davidfowl can comment on VS/SDK/CLI experiences.

**Comment by livarcocc** [comment]
This is not there for 2.1.3xx anymore, as such, I am closing this issue.
