### ISSUE TITLE
Missing dotnetcore.dll

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#6673]
@ddobric commented on [Tue May 23 2017](https://github.com/dotnet/coreclr/issues/11857)

When executing
`dotnet publish -c Release -r win10-x86`
I figured out that assembly _dotnetcore.dll_ is missing.
There is no any issue with this, just want to understand why.

Following
`dotnet publish -c Release -r win10-x64`

generates the named assembly in publish folder.

**Comment by ellismg** [comment]
@ddobric Sorry, I am having problems understanding.

When you publish an application standalone (like the above, where you pass in a specific run-time identifier) the published output should contain everything needed to run your app.  Are you wondering why there's no dll named `dotnetcore.dll`?  If you app is not named `dotnetcore` this is expected.

When you publish your application on windows:

`<AssemblyName>.dll` <-- This is the MSIL of your application.
`<AssemblyName>.exe` <-- This is a native exe that loads .NET Core into memory and then tells it to run `<AssemblyName>.dll`

You'll also get all the files that make up the runtime.  The runtime is split across a few dlls, for example `coreclr.dll` and `clrjit.dll`, but there's no file in the runtime called `dotnetcore.dll`.  The file `coreclr.dll` is an artifact of history (the runtime that was pulled into the dotnet core project is called CoreCLR).

**Comment by livarcocc** [comment]
Closing. If there is anything left unaddressed by @ellismg explanation above, please, re-activate.
