### ISSUE TITLE
Suppress creation of Class1.cs file when running dotnet new <type> --force

### ISSUE THREAD

**Issue by brunzefb** [dotnet/cli#6675]
When converting an old-style .csproj to dotnet core/standard, I typically run 'dotnet new classlib --force' from cmd line to re-create the .csproj file.  If other .cs files are detected in the folder or subfolders, the creation of the Class1.cs file should be suppressed, as it useless.  For a new project, it is useful to have, but not when using --force.

## Steps to reproduce
1. Change directory to an existing project containing .csproj and .cs in folder or subfolders
2. run dotnet new classlib --force

## Expected  behavior
1. The .csproj file is overwritten with a template .net core one  

## Actual behavior
1. the .csproj file is correctly overwritten
2. a Class1.cs template file is produced, but should not be when using --force.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#853
