### ISSUE TITLE
Update SDK Installer [Windows]

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#6683]
Strings and installer steps to be updated. Mac and Windows will receive similar updates and there will be separate issue covering Mac changes. Matching changes will be detailed in another issue for the Runtime installer.

## Screen 1 (intro)

![sdk-1-new](https://cloud.githubusercontent.com/assets/2212879/26418255/5fae66d8-4070-11e7-9a16-fb7a75deef09.png)

* [ ] Window title: `[productname] - [version] [arc] Installer`
* [ ] Remove "You just need a shell ..." text
* [ ] Update Introduction step content as detailed below.

### Intro step text elements
**.NET Core SDK**

.NET Core is a development platform that you can use to build command-line applications, microservices and modern websites. It is open source, cross-platform, and supported by Microsoft. We hope you enjoy it! 

**Learn more about .NET Core**
* [Core Documentation](https://aka.ms/dotnet-docs)
* [SDK Documentation](https://aka.ms/dotnet-cli-docs)
* [Privacy Statement](https://aka.ms/dev-privacy)
* [MIT License](https://aka.ms/dotnet-license)

**Installation note**

A command will be run during the install process that will improve project restore speed and enable offline access. It will take up to a minute to complete. 

## Screen 2 (progress)
* [ ] Window title: `[productname] - [version] [arc] Installer`

## Screen 3 (success)

![sdk-3-new](https://cloud.githubusercontent.com/assets/2212879/26418309/92c6b750-4070-11e7-8b52-369abe31c887.png)

* [ ] Window title: `[productname] - [version] [arc] Installer`
* [ ] Include installation location and list of all components installed
* [ ] Update Summary step content as detailed below.

### Summary step text elements

The following were installed at `C:\Program Files\dotnet`
* .NET Core SDK 2.0.0
* .NET Core Runtime 2.0.0
* ASP.NET Runtime Package Store

**Resources**
* [Core Documentation](https://aka.ms/dotnet-docs)
* [SDK Documentation](https://aka.ms/dotnet-cli-docs)
* [Release Notes](https://aka.ms/20-p2-rel-notes)
* [Tutorials](https://aka.ms/dotnet-tutorials)
* [.NET Core Telemetry](https://aka.ms/dotnet-cli-telemetry)

/cc @richlander @gkhanna79 @livarcocc

**Comment by wli3** [comment]
@leecow screen 3 in Windows cannot use format(plain text only) due to installer tool restriction. The good part is there is only bigger font and bold for style, that ok?

**Comment by leecow** [comment]
@wli3 - whatever formatting tools that are available will be fine to approximate the layout.

**Comment by wli3** [comment]
Sorry for the confusion, the tool we are using won't support rich text on the last page, unless we write the installer ourselves or use a 3rd party installer, so **the screen 3 will be only plain text**

However, it should look ok with tab and new lines
