### ISSUE TITLE
dotnet should provide a way to roll forward to the closest SDK version

### ISSUE THREAD

**Issue by davidebbo** [dotnet/cli#6688]
Let's say the machine has two installed versions, `1.0.4` and `2.0.0-preview1-005977`, and that the project is asking for `1.0.1` via `global.json`.

- the old behavior was: roll forward to the latest, so they'd get `2.0.0-preview1-005977`. This very likely breaks the build.
- the new Preview 2 behavior is: don't roll forward at all, and just hard fail
- the *desired* behavior is: roll forward to `1.0.4`

The reasoning is to be able to remove redundant builds from servers when newer highly compatible build are available, without forcing users to change their `global.json`. This is coming up in particular for Azure App Service, where space on the VM is limited.

**Comment by johnbeisner** [comment]
Is there a global.json that specifies an sdk version:
	    If no, then use latest installed sdk.     Same as today.
	    If yes, then is the version being asked for available:
        	If yes, then use it.     Same as today.
	        If no, then use the lowest installed version that is higher than the specified version.     New behavior!

**Comment by johnbeisner** [comment]
Closing: https://github.com/dotnet/core-setup/pull/2621
