### ISSUE TITLE
Ensure CLI download links have consistent binaries for all platforms

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#669]
I have observed that the CLI download links (used by external developers and our build infrastructure) are often pointing to different set of binaries that may have different changes in them. this is likely due to build failing for platform A but passing for platform B, resulting in publishing of build for B and not A. As a result, folks will experience differences between A and B.

We should ensure that we only publish builds for download if they are available for all platforms.

**Comment by brthor** [comment]
This will be a manual step currently for releases.

**Comment by gkhanna79** [comment]
Is there a reason we cannot ensure VSO publishing does not publish until all 3 builds are clean?

**Comment by piotrpMSFT** [comment]
This was fixed some time ago.
