### ISSUE TITLE
Modernize build scripts

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#670]
dotnet builds are currently orchestrated through bash/ps1 scripts. This is not ideal since it means we have duplicate source code and are re-inventing capabilities already available in existing build systems. Beta milestone's cleanup issue #270 had a great dialogue regarding paths forward. Thanks @devlead!

Once the initial RTM push is finished and we have cycles to rethink our builds, let's follow up on that conversations

**Comment by devlead** [comment]
@piotrpMSFT sounds like a plan :+1:  The CoreCLR bits are on @cake-build's radar (and I  think most other .Net build systems too).
Regardless what direction you choose, unifying to a xplat way makes total sense and would be happy to provide feedback, the work with making Cake cross platform & environment has given us _scar..._ experiences I mean :wink: , that would be useful for any build system. And I'm positive we could learn allot from your efforts too.

Any public RTM roadmap available @piotrpMSFT ?

**Comment by piotrpMSFT** [comment]
@devlead check out this project's milestones :)

**Comment by devlead** [comment]
@piotrpMSFT  Ah RTM Due by March 16, perfect for [Build](http://build.microsoft.com/) then :wink: :+1:

**Comment by piotrpMSFT** [comment]
CLI repo is already migrated to msbuild in the `feature/msbuild` branch.
