### ISSUE TITLE
CLI Error Running dotnet user-secrets set

### ISSUE THREAD

**Issue by isaac2004** [dotnet/cli#6703]
## Steps to reproduce
Following directions at this [Url](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins)

I run this command from cli
`dotnet user-secrets set Authentication:Facebook:AppId <app-Id>`

And get this error

> Failed to create prime the NuGet cache. new failed with: -2147352571

## Expected  behavior
Secret Stored Successfully

## Actual behavior
Above Error and CLI hangs

## Environment data
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

**Comment by livarcocc** [comment]
Did you install the 2.0 runtime separately? How is your SDK 1.0.0 but your runtime 2.0.0-preview1-002111-00?

Do you have a global.json pinning your SDK to 1.0?

Also, check the NuGet.Config file under %userprofile%/appdata/roaming/NuGet. If it has a fallbackFolders session, please remove it. Also, if you have a 2.0 CLI installed, we have a known issue where it will fail the first run. We have fixed it in the latest 1.0 and 1.1 CLIs. You can obtain them by going to github.com/dotnet/cli and changing the branch to rel/1.0.1 or rel/1.1.0 and downloading from there. Remember to update your global.json, if you have one.

**Comment by isaac2004** [comment]
I had a Global Json in a higher folder. That seemed to resolve the issue
