### ISSUE TITLE
dotnet-install.sh: Add ability to override identifiers in /etc/os-release

### ISSUE THREAD

**Issue by juergenhoetzel** [dotnet/cli#6709]
This would allow experencied users do install the *SDK* on officially unsupported platforms like "Arch Linux". My use case is [Omnisharp Roslyn](https://github.com/OmniSharp/omnisharp-roslyn/pull/877).

I suspect that many other projects now use __dotnet-install.sh__  and the ability to override the identifierers would be useful.

On Arch Linux you can   successfully use
[dotnet-cli](https://aur.archlinux.org/packages/dotnet-cli/): A package, based on the Ubuntu binaries (because all required dynamic libaries are installed) :

```
→ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         ubuntu.16.10-x64
 Base Path:   /opt/dotnet/sdk/1.0.4
```

I patched __dotnet-install.sh__, so you can override the identifiers using environment variables:

```bash
if [ -n "${DOTNET_OS_ID:-}" ] && [ -n "${DOTNET_OS_VERSION_ID:-}" ]; then
   ID="$DOTNET_OS_ID"
   VERSION_ID="${DOTNET_OS_VERSION_ID}"
   say "Using environment variables DOTNET_OS_ID and DOTNET_OS_VERSION_ID to specify OS instead of /etc/os-release"      
fi
```

Would you accept such a pull request?

:tropical_drink:

**Comment by omajid** [comment]
You should be able to do that already using the `--runtime-id` flag. For example, try `./dotnet-install.sh --runtime-id linux-x64`.

**Comment by juergenhoetzel** [comment]
> You should be able to do that already using the --runtime-id flag. For example, try ./dotnet-install.sh --runtime-id linux-x64.

Thanks for the hint! :+1:  It would still be useful to use environment variables to specify the the __runtime-id__ without changing code of third-party tools like [OmniSharp](https://github.com/OmniSharp/omnisharp-roslyn/pull/877).

The change would be simple:

```diff
--- a/scripts/obtain/dotnet-install.sh
+++ b/scripts/obtain/dotnet-install.sh
@@ -670,7 +670,7 @@ azure_feed="https://dotnetcli.azureedge.net/dotnet"
 uncached_feed="https://dotnetcli.blob.core.windows.net/dotnet"
 verbose=false
 shared_runtime=false
-runtime_id=""
+runtime_id="${DOTNET_RUNTIME_ID:-}"
 
 while [ $# -ne 0 ]
 do

```

**Comment by livarcocc** [comment]
We won't support distro specific packages very soon for the CLI. Meaning, we will only have the linux portable distro. So, this override isn't really needed.

**Comment by juergenhoetzel** [comment]
> We won't support distro specific packages very soon for the CLI. Meaning, we will only have the linux portable distro. So, this override isn't really needed.

I see. I wasn't aware of *RID* *linux-x64*

Wouldn't it make sense to use *linux-x64* as default *RID* if distro detection fails?

See my related pull request [Handle missing VERSION_ID gracefully](https://github.com/dotnet/cli/pull/6708)

**Comment by johnbeisner** [comment]
This bit of code lives in the method 'get_distro_specific_os_name' which is used to construct legacy type URLs to blob storage. All of the legacy type URLs to blob storage for Linux are distribution specific and **require a version**. Moreover, the portable Linux package [RID linux-x64] is not available in legacy downloads. This change will not modify downloads.

In my opinion, the script should modified to detect that a Linux variant does not have a version and not construct the legacy type URL to blob storage.

**Comment by johnbeisner** [comment]
@juergenhoetzel
This was addressed in PR: https://github.com/dotnet/cli/pull/6839

I would be interested to know if this is working for you after this change.
