### ISSUE TITLE
dotnet publish including all directories with json files by default

### ISSUE THREAD

**Issue by miskiewicz** [dotnet/cli#6710]
In a ASP.NET Core MVC project, when I have json files in any folder and publish with default options, json files get published together with the folders they are in. Even folders such as Controllers get published. It doesn't feel like this is an intended behaviour.

## Steps to reproduce
Recreatable in VS 2017 and VS Code.

1. In VS 2017 create new project from ASP.NET Core Web Application (.NET Core) template with any authentication type.
2. Create new folder A with file A.xml.
3. Create new folder B with file B.json.
4. Create C.json in Controllers folder.
5. Publish to folder with default settings.

## Expected behavior
Only Views and wwwroot folders are published, unless I specify other files and folders in .csproj file.

## Actual behavior
Folder B with file B.json and folder Controllers with file C.json are published.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#209
