### ISSUE TITLE
dotnet restore ignores user-wide config

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#6725]
## Steps to reproduce

- Project with dependencies located on a different source (not nuget)
- Call `dotnet restore XXX.csproj --configfile customfile.config`

## Expected  behavior

- Passed configfile (custom source) and user-wide config `$HOME/.nuget/NuGet/NuGet.config` (default nuget source) should be used to restore packages

## Actual behavior

- All dependencies are resolved
- Note that it works, if I copy/paste the default nuget source from the user-wide config into the `--configfile` config

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/matthias.koch/Desktop/test/IN/.dotnet/sdk/2.0.0-preview2-006127/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d

/cc @emgarten

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5311
