### ISSUE TITLE
[ARM32][PI Zero] Segment Fault - Published app not cli

### ISSUE THREAD

**Issue by eByte23** [dotnet/cli#6726]
## Steps to reproduce
install .net core 2.0 preview or lastest from master
```dotnet new console```
set RuntimeIdentifiers: win7-x64;win-arm;linux-arm

publish using ```dotnet publish -r linux-arm -c Release```
(note also debug has same issue)

copy published app to pi zero and run

## Expected  behavior
The app should output ```Hello World``` to console.

## Actual behavior
Segment Fault

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d

**Comment by livarcocc** [comment]
How are you running the app?

@eerhardt since this seems more like a runtime issue.

**Comment by eByte23** [comment]
I have followed the steps outline here https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

Basically just doing ```./HelloWorld```
Then it returns SegmentFault.

I have ran the exact same app on raspberry pi 2 and it runs successfully.

Could it have anything to do with Software Floating Point vs. Hardware Floating Point, as rpi zero is basically rpi 1 hardware

**Comment by melzoghbi** [comment]
Yes. This is exactly what i am facing. Thanks @eByte23

**Comment by livarcocc** [comment]
Moving this issue to core-setup. I think they can triage it better. This seems like an issue in the runtime and not the tooling.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2601
