### ISSUE TITLE
Manpage Contents should follow Conventions

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#673]
Manpages have a fairly consistent formatting pattern that we should follow in our own.

This page has a pretty good example: http://www.tldp.org/HOWTO/Man-Page/q3.html

Specifically I propose we make the following changes:

1. Include a brief summary of the available options in the SYNOPSIS section. 
(ex. `git [--version] [--help] [-C <path>] [-c <name>=<value>] ...` )

2. Shorten our DESCRIPTION section. In the initial intent to create command descriptions this was appropriate. We could perhaps include some of the information in other sections.

3. Create an OPTIONS section for each of the commands. The purpose of this section would be to describe each of the available options in detail. I expect this is where some of the information in DESCRIPTION could land.

4. Add and ENVIRONMENT section to describe the environment variables which can interact with each of the commands. On the driver manpage, we may consider including manpages which interact with CoreHost.

cc @piotrpMSFT @blackdwarf

**Comment by blackdwarf** [comment]
@brthor makes sense. We will still use the MD files as the source of truth here, since they are much easier to edit and we will have the same effect as for the actual man pages.

**Comment by brthor** [comment]
@blackdwarf That sounds fine. I'm not suggesting to switch away from the md files, only to change contents to be similar to typical manpages.
