### ISSUE TITLE
'dotnet new console' fails to restore nuget packa

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#6730]
## Steps to reproduce
D15PreRel 26601.00
Latest CLI 2.0.0 bits. 2.0.0-preview2-006195

Run 'dotnet new console -n console1' from an admin cmd prompt.

## Expected  behavior
Nuget packages are restored during the creation process

## Actual behavior
Nuget packages fail to restore. Gives prompt to restore manually

## Environment data
`dotnet --info` output:
```
c:\Users\v-masche\projects>dotnet --info output
.NET Command Line Tools (2.0.0-preview2-006195)

Product Information:
 Version:            2.0.0-preview2-006195
 Commit SHA-1 hash:  5a47e7db07

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006195\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25324-03
  Build    : b6c9f8ad69dc3edd601e288198de27975b514306
```

Log:
```

c:\Users\v-masche\projects>dotnet new console -n console1
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on console1\console1.csproj...
Restore failed.
Output from command:
  Restoring packages for c:\Users\v-masche\projects\console1\console1.csproj...
C:\Program Files\dotnet\sdk\2.0.0-preview2-006195\NuGet.targets(98,5): error : U
nable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview2-25324-03)' for '.NETC
oreApp,Version=v2.0'. [c:\Users\v-masche\projects\console1\console1.csproj]
  Generating MSBuild file c:\Users\v-masche\projects\console1\obj\console1.cspro
j.nuget.g.props.
  Generating MSBuild file c:\Users\v-masche\projects\console1\obj\console1.cspro
j.nuget.g.targets.
  Writing lock file to disk. Path: c:\Users\v-masche\projects\console1\obj\proje
ct.assets.json
  Restore failed in 381.76 ms for c:\Users\v-masche\projects\console1\console1.c
sproj.

  Errors in c:\Users\v-masche\projects\console1\console1.csproj
      Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview2-25324-03)' for
 '.NETCoreApp,Version=v2.0'.

  NuGet Config files used:
      C:\Users\v-masche\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Users\v-masche\.dotnet\NuGetFallbackFolder
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\






Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

**Comment by mattscheffer** [comment]
'dotnet restore' fails to run as well. Same error log.

**Comment by dohnuts** [comment]
when using --packages path

> /usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): error : No space left on device

while there is space left on the device.

**Comment by livarcocc** [comment]
@mattscheffer this is a known issue that we are working to fix. This happens because our offline cache is out of sync with the runtime, which means that you need a NuGet.Config with this feed in it to be able to restore: <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />.

@dohnuts I would file an issue at nuget/home for this. I don't believe it is related to this issue here.

**Comment by ramon-garcia** [comment]
What I don't understand: why can't one use the installed sdk as source for  Microsoft.NETCore.App and similar dependencies. Why must one go through nuget.org?

From my installation directory, I have
shared\Microsoft.NETCore.App\2.0.0-preview3-25415-01

Can I list <installation dir>\shared in NuGet.config?

**Comment by livarcocc** [comment]
No, you can't. For many reasons actually, but the system is all built to compile against NuGet packages. Also, the assemblies under shared are not reference assemblies, they are rather runtime assemblies.

By now though, this issue should not happen anymore, as the CLI and ASP.NET are in sync.
