### ISSUE TITLE
Is it supported to build a non-SDK project with the CLI?

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#6732]
## Steps to reproduce
1. File->new project->Windows Classic Desktop->Console App in Visual Studio, targeting .NET framework 4.6.1.
2. Go to commandline and run `dotnet build` on the project.
3. File->new project->Windows Classic Desktop->WPF App in Visual Studio, targeting .NET framework 4.6.1.
4. Go to commandline and run `dotnet build` on the project.

## Expected  behavior
Consistent behavior for legacy project types, either building successfully or failing with a helpful 

## Actual behavior
The console app builds successfully, but its unclear if that's just because I didn't use feature X.
The WPF app not only fails to build but crashes the CLI and triggers windows error reporting.   Bellow is a snippet:
```
f:\cli\latest\sdk\2.0.0-preview1-005977\Microsoft.Common.CurrentVersion.targets(2867,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "f:\cli\latest\sdk\2.0.0-preview1-005977\MSBuild.exe" exists and can be run. [C:\Users\ericstj\Documents\Visual Studio 2017\Projects\testClassic\WpfApp1\WpfApp1.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.31
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Microsoft.Build.BackEnd.TaskHostTask.GetPropertyValue(TaskPropertyInfo property)
   at Microsoft.Build.Execution.TaskFactoryWrapper.GetPropertyValue(ITask task, TaskPropertyInfo property)
   at Microsoft.Build.BackEnd.TaskExecutionHost.GetItemOutputs(TaskPropertyInfo parameter, ElementLocation parameterLocation)
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   f:\testNetfx\cli\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d

I'd like to understand specifically if this is supposed to be supported or not.  It's relevant because it determines if I need to think about running under CLI/CoreCLR for tasks that would be loaded by targets pulled into a classic project.

/cc @dsplaisted @Petermarcu

**Comment by livarcocc** [comment]
No. This is not supported. CLI only supports SDK based projects. Non-sdk based projects need to be built using msbuild.

We have a bug to add full msbuild to the windows versions of the CLI, which would enable this scenario on windows. But not for 2.0.

**Comment by ericstj** [comment]
The CLI ought to fail in a better way then.  You could probably do this by injecting some target into MS.Common.Targets via a hook and fail if the SDK property isn't set /cc @nguerrera

**Comment by ViktorHofer** [comment]
Closing as `dotnet build` on non-sdk projects already works (now).
