### ISSUE TITLE
Ship .NET 4.6.1 support for .NET Standard 2.0 for VS 2015

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#6739]
We need to create an MSI that installs the tasks and targets that support .NET Standard 2.0 in .NET Framework 4.6.1 into Visual Studio 2015's version of MSBuild.

This is a piece of the work required for dotnet/sdk#1267, which tracks the overall work.

**Comment by reyou** [comment]
What is the easy way to run .NET Standard 2.0 for VS 2015 as of today?
Will it be a single click installer? Or, not possible at all?

**Comment by livarcocc** [comment]
Not sure what you mean by "run". But you can reference netstandard 2.0 packages when you install https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.4/dotnet-standard-support-vs2015-2.1.4-win-x86.msi.

Notice that you cannot build netstandard 2.0 projects in VS2015.

**Comment by reyou** [comment]
@livarcocc sorry, I mention build. OK then I will install vs 2017. Thanks.
