### ISSUE TITLE
hostpolicy.dll not found when using dotnet publish

### ISSUE THREAD

**Issue by kinglionsoft** [dotnet/cli#6746]
## Steps to reproduce
1. dotnet new mvc
2. add <RuntimeIdentifiers>linux-arm</RuntimeIdentifiers> to mvc.csproj

``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>
    <UserSecretsId>aspnet-mvc-FBD26BFE-89B7-4A54-830E-1397182F9FD5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview1-final" />
  </ItemGroup>

</Project>
```
3. dotnet restore
4. dotnet publish -r linux-arm

## Expected  behavior
publish mvc project as a self-host app and run at Raspbian.

## Actual behavior

``` bash
E:\mvc>dotnet publish -r linux-arm
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  mvc -> E:\mvc\bin\Debug\netcoreapp2.0\linux-arm\mvc.dll
  Could not find required library hostpolicy.dll in 1 probing paths:

    C:\Users\ykdev\.nuget\packages

  A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'E:\mvc\bin\Debug\netcoreapp2.0\linux-arm\'.
```

## Environment data
`dotnet --info` output:

``` bash
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by livarcocc** [comment]
How are you trying to run the application? invoking dotnet <dll>?

If that's the case, that's the wrong way to run the application. Since you published for a specific rid, you application became a self-contained app. You need to run it by invoking a binary with the same name as your dll, something like mvc.

**Comment by kinglionsoft** [comment]
dotnet run, and dotnet build both work fine.

**Comment by livarcocc** [comment]
But you do not dotnet run/dotnet build in the Raspbian. Also, just to be sure, dotnet run is a development tool only and will not work with your published app.

For a published app, you do to run it by either running dotnet <your_app>.dll (if it is a portable app) or by running <your_app>(.exe if windows) if it is a self-contained app.

**Comment by kinglionsoft** [comment]
I have published a console app to Raspbian following by [https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md). It works fine, but mvc app failed when publishing.

**Comment by livarcocc** [comment]
@kinglionsoft Is it failing when you invoke dotnet publish or is it failing when you try to invoke the app once you have it copied to to the raspbian?

**Comment by kinglionsoft** [comment]
It is failing when invoking dotnet publish. Thanks.

**Comment by kinglionsoft** [comment]
@livarcocc It is failing when invoking dotnet publish. Thanks.

**Comment by livarcocc** [comment]
This is not a problem for linux-arm only. This happens whenever you try to publish the mvc app as a self-contained app.

This is failing when invoking the Microsoft.VisualStudio.Web.CodeGeneration.Tools tool. @mlorbetske can you take a look at this?

**Comment by livarcocc** [comment]
It seems like the tool is expecting to run the app as a portable app, but the reality is that it is self-contained, so, the runtime.config.json won't have the framework in it, which is why it fails with a libhostpolicy missing error.

**Comment by mlorbetske** [comment]
We're investigating

**Comment by mlorbetske** [comment]
Could you try changing view compilation to false to see if that helps?

```
<MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

cc @vijayrkn

**Comment by prafullbhosale** [comment]
> This is failing when invoking the Microsoft.VisualStudio.Web.CodeGeneration.Tools tool 

@livarcocc I am not sure I follow. `dotnet publish` should not be invoking Microsoft.VisualStudio.Web.CodeGeneration.Tools. 

I tried running `dotnet aspnet-codegenerator` and it seems to work fine.

I see `microsoft.aspnetcore.mvc.razor.viewcompilation` failing during `dotnet publish`
This is a different `ProjectDependencyTool` 

cc @NTaylorMullen

**Comment by livarcocc** [comment]
Sorry, I got those wrong, but yeah, that is the problem. ViewCompilation is assuming the project is portable and fails to invoke it when it turns out to be self-contained.

**Comment by Petermarcu** [comment]
We need to make sure self contained applications work before 2.0 ships.

**Comment by pranavkm** [comment]
This is a known issue (https://github.com/aspnet/MvcPrecompilation/issues/102). We're discussing our options for fixing this tomorrow and plan to have a resolution for preview3. FYI @Eilon

**Comment by livarcocc** [comment]
Closing the issue here, since it is already tracked by aspnet.
