### ISSUE TITLE
dotnet-install.ps1 not working on Powershell Core 6.0.0-beta

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/cli#6747]
## Steps to reproduce
Install/use Powershell Core 6.0.0-beta on Windows (!)
load script from https://raw.githubusercontent.com/dotnet/cli/release/2.0.0/scripts/obtain/dotnet-install.ps1
Execute the script 

## Expected  behavior
download and install dotnetcore

## Actual behavior
Exception calling "IsBypassed" with "1" argument(s): "Operation is not supported on this platform."
At ......\dotnet-install.ps1:170 char:20

Line 170:
    if($DefaultProxy -and (-not $DefaultProxy.**IsBypassed**($Uri))){

## Environment data 
($psversiontable)
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Probably a feature request and not a bug !?
Nano Server is using PS-Core !?

**Comment by anoordende** [comment]
This same exception also happens using PS 5.1 whilst creating a docker image from microsoft/iis:nanoserver
~~~~
FROM microsoft/iis:nanoserver

SHELL ["powershell"]

ADD https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1  /tmp/dotnet-install.ps1
RUN /tmp/dotnet-install.ps1 -SharedRuntime $true
~~~~
Following the instructions as per: https://docs.microsoft.com/en-us/aspnet/core/tutorials/nano-server though the install script on that page is different.

**Comment by guardrex** [comment]
@livarcocc The topic is broken right now due to this. Do you think it best to note in the topic that the SDK should be manually installed on Nano or that the dev go with self-contained app deployments for the time being?

**Comment by artisticcheese** [comment]
Here is modified script which works fine on nanoserver. I removed part where local Proxy bypassed for authentication. This is just workaround untill 2.1 comes around. With multistage builds available in docker I found just copying over dotnet executables straight up from images is faster/better solution for me.
https://gist.github.com/artisticcheese/53caa648e0a60dfbea28be1c50554cf2

**Comment by johnbeisner** [comment]
@WernerMairl  
@artisticcheese 
@guardrex 
@anoordende
The install-scripts have been updated and are available at this location:
https://dot.net/v1/dotnet-install.sh (bash, UNIX)
https://dot.net/v1/dotnet-install.ps1 (powershell, Windows)

**Comment by guardrex** [comment]
Thanks @johnbeisner ... the Nano topic was updated. That's the only topic we have in the aspnet/docs that reference the script, so I think we're good here. https://github.com/aspnet/Docs/pull/4234

On the dotnet/docs side, I see one reference to the GH URL in [Using .NET Core SDK and tools in Continuous Integration (CI)](https://docs.microsoft.com/en-us/dotnet/core/tools/using-ci-with-cli). Idk if changes are needed there, but I'll ping @mairaw to see. @mairaw, you can let me know here if you need a quick patch to that PS script example, and I'll knock it out. I'll set that `-Uri` for the `Invoke-WebRequest` to the Url provided above.
