### ISSUE TITLE
`dotnet build` fails when targeting .NET4.6

### ISSUE THREAD

**Issue by mpforce1** [dotnet/cli#6749]
## Steps to reproduce
Create a new project using:

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
There is very little info here. Closing. Please, re-activate when you have repro steps and the CLI version info.

**Comment by mpforce1** [comment]
@livarcocc Sorry, I accidentally ctrl-entered in the description box. I cannot reopen this issue, could you please do so?
