### ISSUE TITLE
OutputType Exe does not lead to .exe in output

### ISSUE THREAD

**Issue by CodeCharm** [dotnet/cli#6760]
## Steps to reproduce
1. Install dotnetcore2 preview 1 (2.0.0-preview1-005977)
2. Create a project directory and go into it(I'm using PowerShell):
`md DotNetCore2ConsoleExe`
`sl DotNetCore2ConsoleExe`
3. Create a new console project
`dotnet new console`
4. Check that the csproj file OutputType setting is set to Exe:
```
gc .\DotNetCore2ConsoleExe.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

</Project>
```
5. Build the project:
```
 dotnet build
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  DotNetCore2ConsoleExe -> C:\Source\Repos\Rulers\DotNetCore2ConsoleExe\bin\Debug\netcoreapp2.0\DotNetCore2ConsoleExe.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.43
```

## Expected  behavior
Output should be executable (DotNetCore2ConsoleExe.exe)

## Actual behavior
Output was a DLL (DotNetCore2ConsoleExe.dll)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by CodeCharm** [comment]
BTW, I read this: https://github.com/dotnet/cli/issues/6237
And, yeah, considering you have millions of .NET Framework developers new to .NET Core who know all about Windows .exe files and not that much about macOS and *nix, calling it an Exe when what you mean is "library that has a standard Main" is misleading to say the least. Call it "app" or something.

**Comment by zunder** [comment]
@CodeCharm How did you fix this issue for you? I am still hopelessly trying to generate an .exe and all I get is a .dll.

**Comment by CodeCharm** [comment]
@zunder It's not really "fixed." Read that thread: #6237 - it's apparently a "by design" feature, although I personally think the design ought to change. After all, every OS has the concept of an executable binary. However, the thing I needed most was to get the exit code from my `static int Main(args[])`, and I was able to do that, even by calling `dotnet.exe` and having it run my (ahem) "executable" DLL.
