### ISSUE TITLE
Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview2-25319-02)' for '.NETCoreApp,Version=v2.0'

### ISSUE THREAD

**Issue by bendono** [dotnet/cli#6763]
## Steps to reproduce
Following the [dogfooding](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md) steps...
1. Download the Windows SDK.
2. Unzip the download.
3. Create a folder for new project. Switch to folder.
4. Run "dotnet new console".

## Expected  behavior
Successful restoration.

## Actual behavior
Screen capture.
![cli-error](https://cloud.githubusercontent.com/assets/846533/26774050/23893f50-4a09-11e7-9a0f-1df29031e8d1.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Dev\sdk\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d

**Comment by livarcocc** [comment]
this is a known issue that we are working to fix. This happens because our offline cache is out of sync with the runtime, which means that you need a NuGet.Config with this feed in it to be able to restore: <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/6730.

**Comment by Tealons** [comment]
@livarcocc : I got a simmilar error, even after adding the correct NuGet.Config reference. What is going wrong?

![image](https://user-images.githubusercontent.com/7141563/27865066-6a2bdb62-6191-11e7-86bb-7b1c68c22f63.png)

**Comment by Tealons** [comment]
@livarcocc Never mind, I was using the wrong docker image....
