### ISSUE TITLE
MSI install drops a build numbered folder containing the store and additionalDeps folders

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/cli#6768]
Rather than having the `store` and `addtionalDeps` folders being dropped at the root of "dotnet home", a folder containing (presumably) the build number of ASP.NET coherence is dropped, containing those two folders.

Before installing from the MSI from release/2.0.0

![image](https://cloud.githubusercontent.com/assets/1414993/26815341/b805bd48-4a40-11e7-8f73-19480cc7d34b.png)

After installing

![image](https://cloud.githubusercontent.com/assets/1414993/26815350/c2f3cc04-4a40-11e7-9100-58dde08802bc.png)

```
>dotnet --info
.NET Command Line Tools (2.0.0-preview2-006341)

Product Information:
 Version:            2.0.0-preview2-006341
 Commit SHA-1 hash:  19d305783b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006341\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25402-02
  Build    : 3c440c8947e7776b2c7772bcb98b3bc73e1b9193
```

cc @joeloff

**Comment by joeloff** [comment]
This is a bug in SetupCrossgen. I'm looking into it

**Comment by livarcocc** [comment]
@mlorbetske and @joeloff I believe we have already ingested a wixlib with a fix for this. So, closing this issue. If I am mistaken, please, re-activate.
