### ISSUE TITLE
.NET CLI segfaults on macOS High Sierra beta

### ISSUE THREAD

**Issue by wjk** [dotnet/cli#6772]
First of all, I’m sorry if I wasn’t supposed to discuss this issue publicly. I checked the Apple developer program agreement and it seems to allow public discussion of bugs in Apple beta software, provided it has been publicly announced at WWDC (which was yesterday). Also, feel free to move this issue to a more suitable repository if required. (I’m filing it here because I don’t quite know which component this bug is occurring in, due to its intermittent nature.)

## Steps to reproduce

1. Install macOS High Sierra Beta (I’m using build 17A264c).
2. Install .NET Core 1.0.4 (I’m using 1.0.4 instead of 2.0 previews to workaround OmniSharp/omnisharp-vscode#1495).
3. Go to an empty directory and run `dotnet new console`.

## Expected behavior

The command completes successfully.

## Actual behavior

`dotnet` segfaults inside of low-level threading and synchronization code in CoreCLR. ([Here is the full crash log.](https://gist.github.com/wjk/cf1d40c0b123fd90a2e29aae17351bc9)) However, it only seems to do this once it has completed running, as all expected outputs are present on the disk.

In addition, this is an intermittent problem; .NET CLI tasks (such as `dotnet build` or `dotnet restore`) crash, while running a DLL directly using `dotnet exec` seems to work fine.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.11-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

**Comment by wjk** [comment]
Unfortunately, my note above about the segfault occurring only as the process is exiting has been proven quite false; `dotnet restore` fails to do anything now, because it segfaults immediately upon launch.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2649
