### ISSUE TITLE
dotnet new --install Microsoft.AspNetCore.SpaTemplates::* fails when multiple packageSources are specified in NuGet.Config

### ISSUE THREAD

**Issue by ganipcanot** [dotnet/cli#6773]
## Steps to reproduce
My NuGet.config looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="SomePrivateFeedKey" value="SomePrivatePackageFeed.json" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```
## Expected  behavior
dotnet new --install Microsoft.AspNetCore.SpaTemplates::* // Should install, not give 401 error

## Actual behavior
401 error seen.
dotnet new --install Microsoft.AspNetCore.SpaTemplates::*
  Restoring packages for C:\Users\brruoff\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj...
C:\Program Files (x86)\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoft.pkgs.visualstudio.com/_packaging/EC.Platform/nuget/v3/index.json.\r [C:\Users\brruoff\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.4\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\brruoff\.templateengine\dotnetcli\v1.0.4\scratch\restore.csproj]

## Environment data
`dotnet --info` output:
C:\Users\brruoff>dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\1.0.4

#Workaround:

Removed 2nd entry
```xml
<add key="SomePrivateFeedKey" value="SomePrivatePackageFeed.json" />
```
 from NuGet.config temporarily --> re-ran the command --> everything installed properly. --> Re-added the 2nd entry back to the NuGet.config.

**Comment by livarcocc** [comment]
I would say this is expected. You have a source in your list of sources to which you have no access.

@emgarten @mlorbetske

**Comment by ganipcanot** [comment]
The private source is one I do have access to, it's just not a public source.  Seems someone might have faced a similar issue as me: https://github.com/dotnet/cli/issues/3330

"It works on another environment I had where there is only **1 package source**.

I was wondering if this is due to the fact that I have private sources? And is there anyway for me to select which sources I want to include / exclude?"

**Comment by livarcocc** [comment]
I am not aware of the capability to select which sources out of the full set of sources will be used. The best work around is the one already suggested in the issue you referenced above.

I will close this issue as I don't believe this is really a problem. Please, re-activate if I got this wrong.

**Comment by ryperl** [comment]
@livarcocc Why would package management fail if one of the sources is valid and does have the package and is not related to the 401.

Example: 
nuget.org is the destination where the package exists
someprivatesource is the 401 but the package wouldn't have existed there anyways.

shouldn't the CLI still succeed in installing this package?

**Comment by emgarten** [comment]
@ryperl if a package depends on a range of ``>= 1.0.0`` and source A has 2.0.0 and source B has 3.0.0 then results will change if source A is missing. Restore fails fast here to avoid giving inconsistent results.

**Comment by spottedmahn** [comment]
I too am facing the same problem.  I don't understand why it wouldn't try the next `source`? I even re-order them in VS to put nuget.org on top and it still failed.

![image](https://user-images.githubusercontent.com/14079228/31358267-e28b77da-ad12-11e7-9bd5-544ce6a160dc.png)

**Comment by Coder3333** [comment]
This is absolutely an issue.  Yes, the stated work around does work, but we shouldn't have to perform a work around (or the Google search to discover the work around) for something that seems like it should be so simple to fix.

**Comment by MaxWilson** [comment]
This affected me too. The workaround unblocks me, but at the very least the guidance in the error message could be improved.
