### ISSUE TITLE
Ability to pass custom compiler option to backend compiler when using --native and --cpp

### ISSUE THREAD

**Issue by tijoytom** [dotnet/cli#678]
For example i want to compile to position independent  shared library instead of an executable . So i need to pass -fPIC and -shared to clang. 

dotnet compile --native  --cpp  --compileoption  shared  --compileoption fPIC

**Comment by blackdwarf** [comment]
@gkhanna79 can you comment on this?

**Comment by gkhanna79** [comment]
There is already such a switch - it is called --cppcompilerflags. Currently it can only take a single value. https://github.com/dotnet/corert/issues/561 tracks enabling it to be specified multiple times on command line.

**Comment by gkhanna79** [comment]
We do not need to add a new switch for this.
