### ISSUE TITLE
"dotnet restore" from SLN dir doesn't trigger associated proj targets

### ISSUE THREAD

**Issue by somewhatabstract** [dotnet/cli#6782]
## Steps to reproduce
1. Create a solution with a project in a subfolder
1. Edit project (csproj) to have a custom build target that depends on the `Restore` target (either before or after target is fine). Something simple like executing an obvious command should be fine as long as the results are visible in the console.
1. Verify that `dotnet restore` from the project folder runs the custom target command
1. Run `dotnet restore` from the sln directory

## Expected  behavior
The custom build target should run as appropriate.

## Actual behavior
The custom build target does not run.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\1.0.4

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5359
