### ISSUE TITLE
Umlauts in exec task fail

### ISSUE THREAD

**Issue by forki** [dotnet/cli#6784]
## Steps to reproduce

md Präsentationen
cd Präsentationen
dotnet new -i Fable.Template.Elmish.React::*
dotnet new fable-elmish-react -n counter
cd counter
dotnet restore

## Expected  behavior

dotnet restore working

## Actual behavior

"file not found"

This is because ä umlaut doesn't work in the Paket.Restore.targets file line 17.

Even reduced call like the following would not work

    <Exec Command='"C:\Präsentationen\counter\.paket\paket.exe" restore ' ContinueOnError="false" />

## Environment data
`dotnet --info` output: 2.0.0-preview2-006127

/cc @davkean

**Comment by nguerrera** [comment]
This issue was moved to Microsoft/msbuild#2187
