### ISSUE TITLE
dotnet-install failing to download SDK for release/2.0.0

### ISSUE THREAD

**Issue by dpodder** [dotnet/cli#6793]
## Steps to reproduce
```bash
wget https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
chmod +x dotnet-install.sh
./dotnet-install.sh -Architecture x64 -Channel release/2.0.0 -InstallDir ./dotnet
```

## Expected  behavior
Successfully downloads the SDK for release/2.0.0

## Actual behavior
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006365/dotnet-dev-2.0.0-preview2-006365-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006365/dotnet-dev-2.0.0-preview2-006365-linux-x64.tar.gz
dotnet-install: Downloading alternate link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006365/dotnet-dev-rhel-x64.2.0.0-preview2-006365.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
```

## Environment data
RHEL 7.2 x64
Also fails due to HTTP/404 on: Ubuntu 14.04 x64, Windows 10 (1703) x64 (using analogous steps)
Note: tested also with dotnet-install script from branch: master. Same error.

**Comment by dpodder** [comment]
@eerhardt This poppued up today and is blocking our work to validate CoreCLR 2.0 perf. Are there any workarounds we could try to get a 2.0 compatible SDK?

**Comment by omajid** [comment]
Should be fixed by https://github.com/dotnet/cli/pull/6785

**Comment by livarcocc** [comment]
@omajid is correct.

@johnbeisner FYI

**Comment by omajid** [comment]
Here's a quick and dirty workaround:

    wget https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
    sed -ie 's/-dev-/-sdk-/g' ./dotnet-install.sh  # new step. no moneyback guarantees!
    chmod +x dotnet-install.sh
    ./dotnet-install.sh -Architecture x64 -Channel release/2.0.0 -InstallDir ./dotnet

**Comment by dpodder** [comment]
Thanks so much @omajid! I can confirm the workaround works and gets at least some of our work unblocked.

+CC: @dotnet/rap-team

**Comment by livarcocc** [comment]
We have merged a fix for this now.
