### ISSUE TITLE
Resolver failures hidden by 1.1 SDK in default fallback location

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6795]
(Edit by @nguerrera: Below is just one example of resolution failing and error message getting hidden. A more common one is global.json pinning to a version that is not available and getting 1.1 instead of a failure with proper error message. Title changed to reflect the general issue.)

## Steps to reproduce
    1.	Create a new console app in VS
    2.	Modify the csproj with the following: <Project Sdk="Microsoft.NET.Sdk/min=9999">
    3.	Reload the project

## Expected  behavior
    The project should fail to load and in the Solution output window you should see something indicating that it failed to find the SDK.

## Actual behavior
The project succeeds to load because the default msbuild resolver will find the 1.1.0 SDK that we ship in the box.

I believe the fix here is to stop shipping an SDK in the box, or, in the very least, validate that the 1.1.0 SDK will not be used for a 2.0 project.

## Environment data
`dotnet --info` output:

**Comment by YunWeiaa** [comment]
Regression on d15.9/28030.00(15.9 Preview 2) + CLI/SDK 2.1.402-preview-009258 
Not repro on d15.8/28010.2019(15.8.3) + CLI/SDK 2.1.402-preview-009258

**Comment by livarcocc** [comment]
@nguerrera to take a look.

**Comment by nguerrera** [comment]
I don't see what we did to prevent it from falling back to 1.1. I would expect that to still be a problem.

**Comment by livarcocc** [comment]
@YunWeiaa can you please file a new issue for this with repro steps and expectations. It is not clear to us from re-using this over year old issue.

**Comment by YunWeiaa** [comment]
@livarcocc ok, I have filed a bug --> #10022 , you can check it.

**Comment by nguerrera** [comment]
Reopening this bug because the issue with falling back to 1.1 SDK still exists.

**Comment by nguerrera** [comment]
@livarcocc I would like to discuss removing the 1.1 fallback SDK in dev16.

**Comment by nguerrera** [comment]
Maybe this isn't the right issue, there aren't any resolver code changes needed, but as long as there is a fallback for the default resolver, all our error messages will be hidden.

**Comment by nguerrera** [comment]
cc @KathleenDollard as we were just discussing this.

**Comment by nguerrera** [comment]
The proposed fix here is:

1. Remove the 1.1 SDK from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks
2. Make the .NET Core SDK a required component of all .NET workloads

The 1.1 SDK was left there because there are workloads that allow you to create .NET Standard libraries but do not install .NET Core SDK for the resolver to find and use.

**Comment by johnbeisner** [comment]
Visual Studio PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/158502
