### ISSUE TITLE
.NET Core 1.0 ASP.NET Dynamic compilation broken after installing .NET Core 2.0 SDK on Linux

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#6805]
## Problem
After installing .NET Core 2.0 preview 1 tooling, the nuget package cache contains lower case names:

    Example: ~/.nuget/packages/microsoft.aspnetcore.antiforgery

But the ASP.NET Core 1.0 runtime expects the same casing as in the package. So if I do a 'dotnet run' on a .NET Core 1.0 app, it will no longer work.

## Approximate repro steps:
1. Install a new Linux box (I was using Ubuntu 16)
2. Install an older CLI (I started off with 1.0)
3. dotnet new mvc
4. Build and run, make sure everything works
5. `wget http://localhost:5000` and make sure the HTTP request succeeds
6. Install the 2.0.0-preview1 build
7. To be safe, nuke your nuget cache again
8. dotnet restore/run your project
9. wget http://localhost:5000

## Actual behavior
Request fails with HTTP 500:
```
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-06-08 12:17:46 ERROR 500: Internal Server Error.
```
If you have logging enabled, you will see something like this:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.InvalidOperationException: Can not find compilation library location for package 'Microsoft.AspNetCore.Antiforgery'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.<SelectManyIterator>d__157`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by livarcocc** [comment]
@eerhardt can you take an initial look?

**Comment by eerhardt** [comment]
I haven't had a chance to debug the issue, but debugging it in my head, a problem I can think of is:

The v1.0 DependencyModel library that is used in 1.0 was shipped out of the dotnet/cli repo in the rel/1.0.0-preview2 branch.  That version of DependencyModel was never updated to support the `Path` property in the .deps.json file.

To workaround this you can either 

1. set a property:

`RestoreLegacyPackagesDirectory=true`

When you do the restore.  This will tell NuGet to not lower case the nuget package directories.

2. Upgrade your DependencyModel reference to `1.1.0` or later by modifying your .csproj to add `<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="1.1.0" />`.


To fix this scenario fully, we would need to port the `Path` change to a new version of Microsoft.Extensions.DependencyModel, and then also update ASP.NET 1.0 to reference this new version.  Or we could just rev ASP.NET 1.0 to reference the `1.1.0` version of DependencyModel.  Or we could just fix the web templates to update the DependencyModel version.

**Comment by livarcocc** [comment]
@Eilon @mlorbetske To see if any of the alternatives above would work.

**Comment by livarcocc** [comment]
This seems to be working now. Re-activate if this does not work with 2.0.0.
