### ISSUE TITLE
can't install package via apt-get on ubuntu server 14.04

### ISSUE THREAD

**Issue by shimingsg** [dotnet/cli#6811]
1. Have a clean machine from official ubuntu iso/ Azure VM
2. Run following command, to add our source
- sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
- sudo apt-get update
3. apt-cache search dotnet-sdk | grep 2.0.0 to list available 
4. sudo apt-get install dotnet-sdk-2.0.0-preview2-006360

**Expected result**: install package success
**Actual result**: install failed, detail message as following 
e2euser@e2e-us1404:~$ sudo apt-get install dotnet-sdk-2.0.0-preview2-006360
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.0-preview2-006360 : Depends: dotnet-runtime-2.0.0-preview2-25406-03 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by livarcocc** [comment]
I believe this is a dup of https://github.com/dotnet/cli/issues/6796.

@wli3 can you confirm and close this one if that's the case?

**Comment by wli3** [comment]
We should test the latest package, the current one is dotnet-sdk-2.0.0-preview2-006394 

The current _dotnet-sdk-2.0.0-preview2-006394_ and the dependency dotnet-runtime-2.0.0-preview2-25407-01 is in the feed (https://github.com/dotnet/core-setup/issues/2657 might already manually pushed). 

@livarcocc Majority old packages in the "daily" feed is in the similar broken state, wrong name or missing dependencies should we clean them up? It is been like this for a long time
