### ISSUE TITLE
Unable to create netcore2 F# project 

### ISSUE THREAD

**Issue by wklm** [dotnet/cli#6813]
## Steps to reproduce
> dotnet new console -lang F# 
> dotnet build

## Expected  behavior
Create a netcore2 project with F#

## Actual behavior
```
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

/root/.nuget/packages/fsharp.net.sdk/1.0.5/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/b/b.fsproj]

Build FAILED.

/root/.nuget/packages/fsharp.net.sdk/1.0.5/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB6006: "dotnet" exited with code 131. [/b/b.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.81
```

## Environment data
docker dotnet:2-sdk image

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by enricosada** [comment]
@wklm MS is replacing `FSharp.NET.Sdk` and bundling needed files in default `Microsoft.NET.Sdk`.

See https://github.com/dotnet/netcorecli-fsc/issues/115 for more info.

So atm doesnt work with 2.0.0-preview1 because is going to be replaced soon.

**Comment by livarcocc** [comment]
@KevinRansom to confirm that this is done for preview2 and close this issue if that's the case.

**Comment by enricosada** [comment]
I tried with `2.0.0-preview2-006391` and F# works.

@livarcocc i am just writing a PR to reeenable [EndToEnd test for F#](https://github.com/dotnet/cli/tree/release/2.0.0/test/EndToEnd) so is easier to be sure, can this be closed with that PR?

**Comment by NinoFloris** [comment]
When will preview 2 be released?

**Comment by livarcocc** [comment]
@enricosada F# tests have already been re-enabled in the CLI.

**Comment by enricosada** [comment]
@livarcocc sorry i cannot find these. where?
i see are skipped for F# and `dotnet new` in https://github.com/dotnet/cli/blob/07b93e9d7cd0901edc391d923de7682915c0fe8e/test/dotnet-new.Tests/GivenThatIWantANewAppWithSpecifiedType.cs#L40-L45

Is `release/2.0.0` the right branch to use for next?

**Comment by livarcocc** [comment]
@enricosada Yes, https://github.com/dotnet/cli/blob/release/2.0.0/test/dotnet-new.Tests/GivenThatIWantANewAppWithSpecifiedType.cs#L29.

**Comment by enricosada** [comment]
Ah yes, that if was evaluated to false, thx @livarcocc

**Comment by livarcocc** [comment]
Seems like we can close this issue, since this is now support in preview2, being developed out of the release/2.0.0 branch.
