### ISSUE TITLE
Ensure support running via bash, etc... on Windows

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/cli#682]
As per these tickets for dnvm: https://github.com/aspnet/dnvm/pull/451 and https://github.com/aspnet/dnvm/issues/280

I wanted to make sure that this use case isn't forgotten or overlooked.

There are many people - especially those who have installed docker-toolbox - who prefer to use bash on Windows rather than PS or cmd.  It would be nice if the new dotnet utilities at least were made aware of these scenarios.  That way they could be integrated into peoples' `.profile` and `.*rc` files.

Here's a list of the environments I'm aware of so far that are likely to come up:

  - msys2
  - cygwin
  - msys via msysgit

**Comment by piotrpMSFT** [comment]
What feature work is needed to light up these scenarios?

**Comment by blackdwarf** [comment]
@atrauzzi what would this item entail Can you provide some more details?

**Comment by atrauzzi** [comment]
You'll likely have to reach out to the msys2 team to get a better idea of things.   Overall, it's bound to be a packaging process.  In the msys2 case, they use pacman.

After that, you'd be effectively setting up the cli to be able to recognize that it's running in a POSIX-style environment on a Windows platform.  And that would apply for all three of the compatibility layers I listed above.

**Comment by blackdwarf** [comment]
As it currently stands, this is not something we will tackle. I will close this issue. If you think this is in error, please reopen.
