### ISSUE TITLE
NullReferenceException when dotnet remove package ...

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/cli#6826]
This is what I get when I try to remove a package:

```
C:\...\HelloWorldLib>dotnet remove package Newtonsoft.Json
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at Microsoft.DotNet.Tools.Remove.PackageReference.RemovePackageReferenceComma
nd..ctor(AppliedOption appliedCommand, String fileOrDirectory, ParseResult parse
Result)
   at Microsoft.DotNet.Tools.Remove.RemoveCommand.<get_SubCommands>b__9_1(Applie
dOption remove)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Remove.RemoveCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemet
ryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
PS C:\Users\onur> dotnet --info
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

PS C:\Users\onur>

**Comment by livarcocc** [comment]
Can you tell us a bit more about how to repro this issue? What are the contents of the HelloWorldLib folder? do you have a project there? Is it an SDK based project? Can you share it with us?

**Comment by OnurGumus** [comment]
@livarcocc , I was trying F# getting started tutorial 
https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/getting-started/getting-started-command-line
with 2.0 Preview 1 SDK.
With Preview 2 the issue does not happen. So I will close the issue.
