### ISSUE TITLE
dotnet restore fails on Windows with .NET Core 2.0-preview1-005977

### ISSUE THREAD

**Issue by martincostello** [dotnet/cli#6828]
## Steps to reproduce

Clone the `DotNet-Core-2.0` branch of https://github.com/martincostello/website.git (see martincostello/website#194).

## Expected  behavior

`dotnet restore` completes successfully, after which the build and tests succeed.

## Actual behavior

On Windows `dotnet restore` fails (see AppVeyor build [ere](https://ci.appveyor.com/project/martincostello/website/build/1.0.365#L108) and [here](https://ci.appveyor.com/project/martincostello/website/build/1.0.365#L340)):

```ps
C:\projects\website\.dotnetcli\sdk\2.0.0-preview1-005977\NuGet.targets(97,5): error : Unable to resolve 'C:\projects\website\src\Website\Website.csproj' for '.NETCoreApp,Version=v2.0'. [C:\projects\website\Website.sln]

Errors in C:\projects\website\tests\Website.Tests\Website.Tests.csproj
    Unable to resolve 'C:\projects\website\src\Website\Website.csproj' for '.NETCoreApp,Version=v2.0'.
```

On Linux (see [Travis build](https://travis-ci.org/martincostello/website/builds/241732947)), the build succeeds as expected.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Coding\website\.dotnetcli\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5386
