### ISSUE TITLE
Provide an installer for msys2

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/cli#683]
This is slightly off the beaten path, but it's gaining some popularity for people who are serious about getting bash on Windows: Why not provide a pacman installer for [msys2](https://msys2.github.io/)?

Here's the repository: https://github.com/Alexpux/MSYS2-packages

I think it would be very cool if I could have the new cli tools integrated fully with the msys2 bash environment.

**Comment by atrauzzi** [comment]
Related: https://github.com/dotnet/cli/issues/682

**Comment by blackdwarf** [comment]
@atrauzzi unfortunately, we don't plan on doing this at least for V1. I will close this issue for now, if you have any new details, please reopen it.
