### ISSUE TITLE
Make reference to `dotnet restore`

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#6831]
Type: `dotnet run`

I see: 
```console
C:\git\dotnet-framework-docker-samples\dotnetapp-4.7>dotnet run
C:\Program Files\dotnet\sdk\2.0.0-preview2-005905\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(132,5): error : Assets file 'C:\git\dotnet-framework-docker-samples\dotnetapp-4.7\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\git\dotnet-framework-docker-samples\dotnetapp-4.7\dotnetapp-4.7.csproj]

The build failed. Please fix the build errors and run again.
```

The reference to `NuGet package restore` should be to `dotnet restore`. The error message should bias towards instructive as opposed to descriptive.

**Comment by nguerrera** [comment]
The error is coming from the SDK targets and can happen in non-CLI usage (VS, VS for Mac, desktop msbuild).

**Comment by nguerrera** [comment]
With latest bits, cli would have implicitly restored with these repro steps. The error will be much less prevalent.
