### ISSUE TITLE
dotnet sln doesn't give good error message

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#6835]
## Steps to reproduce
dotnet sln

## Expected  behavior
Usage information is displayed

## Actual behavior
"Required command was not provided."

## Environment data
`dotnet --info` output:

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

**Comment by livarcocc** [comment]
This is what I see in preview2:

```
Required command was not provided.
.NET modify solution file command

Usage: dotnet sln [options] <SLN_FILE> [command]

Arguments:
  <SLN_FILE>   Solution file to operate on. If not specified, the command will search the current directory for one.

Options:
  -h, --help   Show help information.

Commands:
  add <args>      .NET Add project(s) to a solution file Command
  list            .NET List project(s) in a solution file Command
  remove <args>   .NET Remove project(s) from a solution file Command
```

**Comment by Petermarcu** [comment]
I'm looking to verify on my machine but I'm an hour away from finishing the download of the tar.gz :(

**Comment by Petermarcu** [comment]
Looks like its fixed in preview2.
