### ISSUE TITLE
global.json does not affect dotnet version

### ISSUE THREAD

**Issue by Remleo** [dotnet/cli#6836]
## Steps to reproduce
1. Create new folder
2. Create global.json file with

```
{
  "sdk": { "version": "1.0.4" }
}
```
3. run `dotnet --info` in this folder

## Expected  behavior
`1.0.4`

## Actual behavior
`2.0.0-preview2-006215`

## Environment data
`dotnet --info` output:

```
c:\dotNET\111>dotnet --info
.NET Command Line Tools (2.0.0-preview2-006215)

Product Information:
 Version:            2.0.0-preview2-006215
 Commit SHA-1 hash:  e67962b0de

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\admin\.dotnet\x64\sdk\2.0.0-preview2-006215\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983


c:\dotNET\111>
```

![2017-06-12_12-43-10](https://user-images.githubusercontent.com/10843339/27028838-c43eb406-4f6e-11e7-9b7b-e972965db1ff.png)

**Comment by Remleo** [comment]
If copy the directory `1.0.4` from `c:\Program Files\dotnet\sdk\` to `c:\Users\admin\.dotnet\x64\sdk\` it wokrs 
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\admin\.dotnet\x64\sdk\1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

But the SDK installer is installing files to the `c:\Program Files\dotnet\sdk\`

**Comment by Remleo** [comment]
Is it normal that  `Base Path` was changed from `c:\Program Files\dotnet\sdk\` `C:\Users\admin\.dotnet\x64\sdk\1.0.4`?

**Comment by dasMulli** [comment]
@Remleo have you built any asp.net core projects from source? their build scripts create an installation there AFAIK.. you might want to check your system's PATH environment variable.

**Comment by Remleo** [comment]
@dasMulli Yes! I have run build-script for IdentitySamples

My PATH enveronment variable is:
```
>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;d:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\OpenServer\global\nodejs\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GitExtensions\;C:\Users\admin\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\admin\.dnx\bin;C:\Users\admin\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
```

There is `C:\Program Files\dotnet\`.

Can you advise how to change back the `Base path` for `Runtime Environment` to `c:\Program Files\dotnet\`?

**Comment by dasMulli** [comment]
The base path is just where the `dotnet.exe` muxer is. If your user's and machine's `PATH` settings don't contain the `%USERPROFILE%\.dotnet` folder then i think you should be fine in a new console window.. if not, then it might be a side effect of https://github.com/dotnet/core-setup/issues/2624 and should be fixed in newer builds.. (=> just delete the `%USERPROFILE%\.dotnet` folder if you don't use the asp.net core git repos)
