### ISSUE TITLE
Implement app.config pattern

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#6837]
.NET Framework projects in Visual Studio include a pattern where app.config files get renamed upon build to the correct exe name. If you have an sdk-style project that targets and/or cross-compiles to .NET Framework, you need to implement this pattern manually (see example below).

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="dotnetapp-4.7.exe.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>


</Project>
```

**Comment by livarcocc** [comment]
@richlander you should just create an app.config file in the root of your project and the file will be appropriately copied and renamed to the output folder. You don't need that ItemGroup part in your csproj.
