### ISSUE TITLE
VisualStudio 2017 preview 2 doesn't load Unit tests with .NET Core 2.0.0-preview2-006391

### ISSUE THREAD

**Issue by piolo94** [dotnet/cli#6848]
In the last two days I've had some trouble with Unit Testing in VS 2017 preview 2. Yesterday I've installed the last version of .NET core, I've updated every package inside my project and, since then, I haven't been able to see not a single test in VisualStudio's Test Explorer . If run the command "dotnet test" in the PowerShell everything works and I receive the information of test's execution. What can I do? Thanks!

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#858
