### ISSUE TITLE
How to install .net core through powershell script?

### ISSUE THREAD

**Issue by nishant261989** [dotnet/cli#6849]
The project was using DNVM powershell script to install it on TFS but now as it got obsolete and the url [https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1](https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1) returned as 404 not found. Now the need is to migrate it from DNVM to .Net Core and I was unable to find the exact solution how I can write a powershell script for installing .Net Core. Please help

Also If I tried skipping the DNVM installation task from Build definition then it throws below error:

The "GetBuildOptions" task was not given a value for the required parameter "RuntimeToolingDirectory".

**Comment by omajid** [comment]
Have you seen https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1 ?

**Comment by GuardRex** [comment]
The current doc covering it is at: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

The 2.0 doc (under development) is at: https://github.com/GuardRex/docs-1/blob/5fb54f42f96bd20e44893f2b24cad31e39d659a6/docs/core/preview/tools/dotnet-install-script.md

**Comment by livarcocc** [comment]
cc @johnbeisner

**Comment by livarcocc** [comment]
Closing this issue since I believe the question has been answered. If there is anything else that you need to know or that's blocking you, please re-activate or file a new issue.
