### ISSUE TITLE
README.md and setting DOTNET_HOME

### ISSUE THREAD

**Issue by knarfalingus** [dotnet/cli#685]
I followed the instructions in README.md

Installed on Ubuntu 14.04 using the Debian package, most of the heavy lifting was handled by the Ubuntu software center.

I set the DOTNET_HOME environment variable per instructions.

dotnet run yields **"failed to locate CLR files at /usr/share/dotnet/runtime/coreclr"**

At least for me, the issue is that the DOTNET_HOME directory needed to be set to  /usr/share/dotnet-dev/    **not** /usr/share/dotnet/

**Comment by blackdwarf** [comment]
Thanks for bringing this up, discrepancy in the docs. Will fix.
