### ISSUE TITLE
UX: Simple use cases are failing for testing in multi-targetting projects on VS2017 for win10-x64

### ISSUE THREAD

**Issue by fir3pho3nixx** [dotnet/cli#6856]
## Steps to reproduce

Please clone https://github.com/fir3pho3nixx/nunit-adapter-vs-xunit
Then run: `build.bat`

## Expected  behavior

It does *NOT* kick out: `Make sure test project has a nuget reference of package "microsoft.testplatform.testhost"`. The real problem here would be handy. 

This happens for both NUnit and XUnit. You can observe this by commenting out this [line](https://github.com/fir3pho3nixx/nunit-adapter-vs-xunit/blob/master/build.bat#L4). 

## Actual behavior

It kicks out: `Make sure test project has a nuget reference of package "microsoft.testplatform.testhost"`. 

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## More info

We have an issue here: https://github.com/castleproject/Windsor/issues/243

I am trying to help out here: https://github.com/nunit/nunit3-vs-adapter/issues/324

But in an attempt to create a repro here: https://github.com/fir3pho3nixx/nunit-adapter-vs-xunit I keep getting this error. 

This should be simple on windows(but does not work out of the box). My end game is to get this going on Linux. I can do this and have done it before, I am just thinking of people that discover this for the first time and are left googling the problem for hours on end. Can we make this better?

**Comment by dsplaisted** [comment]
> The real problem here would be handy.

What is the real problem?  Or do you not know?

**Comment by fir3pho3nixx** [comment]
I keep running into this, I am grumpy and tired right now so going to bed but I am sure with more digging I will find the answer. Please look at the code sample ... it is incredibly simple. Night.

**Comment by dasMulli** [comment]
None of these test projects have a package reference to `Microsoft.NET.Test.Sdk` so `dotnet test` isn't going to work.

```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
```

**Comment by fir3pho3nixx** [comment]
@dasMulli - thanks. If this fixes it that is great. 

I still believe the error message is absolutely farcical. It bum steers you to a NuGet that does not have this as a dependency. The reason I raised this was in hope that the error report could be made slightly more intelligable hence why I prefix the issue title with UX.

**Comment by dasMulli** [comment]
I also do agree that the error message should be actionable here (sth like "Make sure your project references the Microsoft.NET.Test.Sdk NuGet package."), which would be an issue for the https://github.com/microsoft/vstest repo owning this code. (care to move?)

**Comment by fir3pho3nixx** [comment]
I will move it, many thanks.

**Comment by fir3pho3nixx** [comment]
@dasMulli - Created issue as promised. Thanks again 👍
