### ISSUE TITLE
Latest bits on OSX crash for dotnet test

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/cli#6858]
## Steps to reproduce
Run `dotnet test` on a project, it will crash with 
```
Unhandled Exception: System.BadImageFormatException: 
Could not load file or assembly '/usr/local/share/dotnet/sdk/2.1.0-preview1-006329/vstest.console.dll'. 
An attempt was made to load a program with an incorrect format.
```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.0-preview1-006329)

Product Information:
 Version:            2.1.0-preview1-006329
 Commit SHA-1 hash:  defa3c3973

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-006329/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by livarcocc** [comment]
This should be fixed now. We are running that multiple times from our own builds in master. Please, re-activate or comment if you run into this again.

Though, the error you are reporting above, usually indicate the wrong bitness between the host and the app being run.
