### ISSUE TITLE
ResourceManager.GetString doesn't return embedded text file on linux

### ISSUE THREAD

**Issue by tarekgh** [dotnet/cli#6866]
@Spongman commented on [Tue Jun 13 2017](https://github.com/dotnet/coreclr/issues/12262)

a (.csproj) project a with an embedded text file, added using the VS2017.2 project properties UI.

[ConsoleApp2.zip](https://github.com/dotnet/coreclr/files/1073187/ConsoleApp2.zip)

on windows, it works fine.

on linux, it just shows:
````
$ dotnet --version
1.0.4
$ uname -a
Linux mybox 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
$ dotnet run
..\Resources\New Text Document.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;Windows-1252
````

---

@danmosemsft commented on [Tue Jun 13 2017](https://github.com/dotnet/coreclr/issues/12262#issuecomment-308318082)

@tarekgh are there any known issues here?

---

@tarekgh commented on [Wed Jun 14 2017](https://github.com/dotnet/coreclr/issues/12262#issuecomment-308475890)

Please take a look at the issue https://github.com/dotnet/cli/issues/3695 this was CLI issue and I believe it is already fixed but I am not sure which release include the fix. I'll move this issue to CLI repo.

**Comment by nguerrera** [comment]
This issue was moved to Microsoft/msbuild#2221
