### ISSUE TITLE
dotnet test should not build if project already built

### ISSUE THREAD

**Issue by ardalis** [dotnet/cli#6868]
## Steps to reproduce
Run dotnet test. It will build.
Run dotnet test again. It will build. It doesn't need to.

## Expected  behavior
Run dotnet test. It will build (if necessary).
Run dotnet test. It will simply run tests.

## Actual behavior
See above.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#863

**Comment by jaime-olivares** [comment]
Doesn't seem like a vstest issue.
The same requirement applies just for building (without testing).

**Comment by livarcocc** [comment]
For building, we have incremental build check, which will skip building unless it is necessary.
