### ISSUE TITLE
dotnet new should require a folder name

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#687]
It's pretty annoying that I have to do:

```
mkdir {name}
cd {name}
dotnet new
```

We should just make it part of the new project experience:

```
dotnet new {name}
```

Ends up with:

```
$/name
  Program.cs
  project.json
```

See http://doc.crates.io/#let’s-get-started for some inspiration :smile: 

/cc @richlander @blackdwarf

**Comment by davidfowl** [comment]
Related to https://github.com/dotnet/cli/issues/686

**Comment by blackdwarf** [comment]
Intrestingly enough, Cargo was somewhat my inspiration for #655. @davidfowl, can you comment on that one with this so we have all of suggestions for `dotnet new` in one place?

**Comment by blackdwarf** [comment]
This is now tracked in #655 so I would close this. @davidfowl any objections?

**Comment by davidfowl** [comment]
Sounds good.
