### ISSUE TITLE
dotnet test -f ... does not work

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#6871]
## Steps to reproduce
- Clone https://github.com/aspnet/Razor
- cd test/Microsoft.AspNetCore.Mvc.Razor.Extensions.Test
- dotnet restore
- dotnet test -f netcoreapp2.0

## Expected  behavior
- Tests are run for netcoreapp2.0

## Actual behavior
![image](https://user-images.githubusercontent.com/2008729/27149130-747d681a-50f7-11e7-81a6-a41794451442.png)

## Extra
This works if you just do `dotnet test` on its own without a TFM.

/cc @livarcocc @eerhardt Not sure if this is the right repo but this is pretty awful.
/cc @Eilon @ryanbrandenburg @mikeharder @kichalla for visibility since the ASP.NET team is currently using this CLI.

**Comment by rrelyea** [comment]
believe this is related to the implicit restore. CLI is planning on not passing -f to implicit restore to fix. Once you use the CLI with that fix, should be fine.

can workaround by doing:
dotnet restore
dotnet test -norestore -f netcoreapp2.0

**Comment by livarcocc** [comment]
Rob is correct. Which version of the CLI are you using? I have merged a change last night that should address this.

**Comment by Eilon** [comment]
CLI 6443 per the screenshot. I think you're right and that doesn't have the `-f` fix thingy.

**Comment by livarcocc** [comment]
The fix is in 2.0.0-preview2-006449. Sorry, it was hard to see the version in the screenshot. We don't all have your sunglasses @Eilon.

**Comment by Eilon** [comment]
Haha no worries, thanks! 😎

**Comment by halter73** [comment]
I saw this same issue running `dotnet build -f netcoreapp2.0` using 2.0.0-preview2-006391. I'll wait for the 6449 build to see if that fixes it.

**Comment by livarcocc** [comment]
@NTaylorMullen did the new build address your issue?

**Comment by NTaylorMullen** [comment]
Verified this works now with build 6461. Thanks all!
