### ISSUE TITLE
Turn off distro specific VSO builds

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6878]
We don't need them anymore.

We may have to update the publish target in the CLI as well, as it checks the legs that have finished successfully to update the version badge.

@johnbeisner can you look into this since you touched this code this week already?

**Comment by livarcocc** [comment]
@wli3 can you turn off the legs we don't need anymore?

**Comment by wli3** [comment]
Done

**Comment by wli3** [comment]
Removed trigger for these build definitions, if no problem this week, I will move them to an achieve folder
