### ISSUE TITLE
Need options for System information

### ISSUE THREAD

**Issue by vnd-edu** [dotnet/cli#6883]
## Steps to reproduce
I am migrating Asp.net web application in .net core. i am not getting any api to find system information.

## Expected  behavior
in .net application i used System.management api to run query and get the all information.

## Actual behavior
how to get system information like processor id , system installed date and time?
Please help me out.
## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to dotnet/corefx#21081
