### ISSUE TITLE
Ensure errors from resolver about mismatched .NET Core SDK versions are surfaced correctly in VS and desktop msbuild

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#6887]
_From @srivatsn on June 15, 2017 15:52_

_From @onovotny on June 15, 2017 15:40_

Here's the scenario: 

Web project that has a global.json with a pinned SDK version. 

Executing an msbuild /pp yields some interesting results for where the SDK's are imported:

If the SDK version is 1.0.0-1.0.3 is:
The import of the Web SDK is from: 
`C:\Program Files\dotnet\sdk\1.0.0\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props`

But then the .NET Sdk is from: 
`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props`

If the SDK version is 1.0.4, both SDK's come from the `C:\Program Files\dotnet\sdk\1.0.4\Sdks\` directory.

Seems like if `1.0.4` is the min version of the SDK that will work correctly with 15.3, then if VS sees an older pinned version, it should use the upgrade wizard functionality to bump the min SDK version to 1.0.4 so things don't act strangely for users unexpectedly.

_Copied from original issue: dotnet/project-system#2450_

_Copied from original issue: dotnet/sdk#1348_

**Comment by nguerrera** [comment]
_From @srivatsn on June 15, 2017 15:53_

Tagging @nguerrera @livarcocc

**Comment by nguerrera** [comment]
_From @srivatsn on June 15, 2017 15:53_

Since the 1.0.0 web SDK imports the Web.ProjectSystem.SDK using MSBuildSdksPath and that's not in VS anymore, web projects are fairly broken.

**Comment by livarcocc** [comment]
We should make sure that if the min version is 1.0.4, if it will work with the 1.1.0 version that will ship with VS Preview3.

**Comment by nguerrera** [comment]
This is one of the aspects of dotnet/cli#6585 that was postponed.

Specifically, this part of the proposal:

Add a manifest file next to the resolver that indicates a global minimum sdk version to the resolver and use the greater version of the global minimum and the import-specific minimum. (See #6555.)
A cheap fix for 15.3 would be to have an implicit global minimum of 1.0.4 always. There is no version < 1.0.4 that can be resolved safely from anything that would ever use the resolver, and that cannot change without a time machine. Mind you, actually declaring 1.0.4 in a manifest file and using it is not all that expensive, so we should probably just do it.

**Comment by srivatsn** [comment]
> I don't see why it wouldn't, but yes, we should test.

If we had taken some dependency on the 1.1 SDK from the project system. I don't think we have though - the nuget errors work is the only one that comes to mind and even there if the errors are not raised from the assets file, then NuGet should fall back to its old way of doing things.

**Comment by nguerrera** [comment]
Oh, I see. I read that backwards.

**Comment by srivatsn** [comment]
Tagging @richaverma1 to note this scenario for validation.

**Comment by livarcocc** [comment]
@MattGertz FYI, this will be a resolver change that will require an insertion into VS.

**Comment by nguerrera** [comment]
Reopening this because customers are still hitting an unhelpful error message in VS that the "Microsoft.NET.Sdk.Web cannot be found". The problem is that when we issue a proper error message from the resolver, desktop msbuild will fall back to c:\Program Files\...\Microsoft Visual Studio\...\MSBuild\Sdks where there is no Web SDK. This suppresses our error message. 

I think we need a way to indicate to MSBuild that we do not want this fallback to occur when we have located the .NET Core SDK, but it is not at an appropriate matching version. cc @AndyGerlicher.

**Comment by vfilenga** [comment]
Guys, any quick workaround until definitive solution? Forgot to create a restoration point and now got my workstation without a way to implement my tasks on web projects constructed under any .NET Core version. Neither can I create new web projects to try to port my old code. Is there any relation with the PATH environment variables?

**Comment by nguerrera** [comment]
@vifilenga The solution here would just give a better error message.

Does your project have a global.json file specifying sdk lower than v1.0.4? If so, you need to either remove global.json (will use latest sdk on machine) or specify v1.0.4 or later in it. Also make sure the version you specify in global.json is installed on the machine.

If that's not the issue, the next thing to check is that you can run dotnet commands in VS developer prompt. And if so, what is the output of `dotnet --info`?

**Comment by pgmolloy** [comment]
Ok this just started happening to me. Can't even start a new .net core web project or open any of my working projects. Major problem. Please advise as I do not have a global.json file any where

**Comment by nguerrera** [comment]
@pgmolloy if you run `dotnet --info` from the VS developer command prompt, what is the output?

**Comment by pgmolloy** [comment]
@nguerrera dotnet --info gives 2.0.0, I have only create one 2.0.0 and have been still developing in 1.1 and everything was fine up until a few hours ago. I uploaded to "Report a Problem" with a recording and screen shot and it is triaged but still trying to find the answer as I am pretty stuck in undevelopment mode.

**Comment by nguerrera** [comment]
@pgmolloy I will look at the feedback report in the morning. Is the error message something like "cannot find Microsoft.NET.Sdk.Web" or something else? Was there something you did to the machine a couple of hours ago that would give a hint as to why things might suddenly stop working?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pgmolloy** [comment]
@nguerrera Yep that is exactly the error. I am trolling all of the logs in the temp directory to see if I can understand exactly when it started. I will let you know if I find it. Have to move current work to another machine quickly see what is happening on that machine with a mirror image.

**Comment by pgmolloy** [comment]
@nguerrera Oh and thanks for the reply by the way. Much appreciated. It is lonely out here in the ether. hahaha. Anyways chat tomorrow.

**Comment by vfilenga** [comment]
Hello @pgmolloy and @nguerrera. Just issued a "dotnet --info" in vs 2k17 command prompt to get back this.
![image](https://user-images.githubusercontent.com/16693247/29772212-13de309a-8bce-11e7-8a62-3013d98c9512.png)

Interesting or not might be this "base path". Am I supossed to have this as one of my environment path variables? Because at the moment there isnt one.

**Comment by natemcmaster** [comment]
cc @davidfowl  - this is the issue we were talking about. VS doesn't show useful errors if the sdk from global.json cannot be found.

**Comment by nguerrera** [comment]
I think I found why the errors get hidden by msbuild (not what I thought above about fallback case). I will send a PR to msbuild early next week and try to get it in for 15.5 if I'm right.

**Comment by nguerrera** [comment]
Turns out the fix was not in msbuild, but there's a project system bug tracking it. I will close this as dupe of it when I find it.

**Comment by nguerrera** [comment]
The remaining issues are tracked as follows:

Removing fallback to 1.1: https://github.com/dotnet/cli/issues/6795
Project system not showing resolver errors: https://github.com/dotnet/project-system/issues/2467
