### ISSUE TITLE
Uninstalling Visual Studio, should uninstall any .NET Core SDK that it installed

### ISSUE THREAD

**Issue by davkean** [dotnet/cli#6896]
I'm forever cleaning up SDK installs in my add/remove, despite only ever installing/upgrading VS. This goes against the goals of the new Willow installer.

Uninstalling VS should uninstall a .NET Core SDK if no other component installed it. Other MSIs in VS uses a ref-count system to implement this - please make the .NET SDK do the same.

**Comment by livarcocc** [comment]
Just to flush things out a bit here, we should ONLY do this when that SDK was indeed installed by VS and only that specific version. What I mean is, if VS wants to install 1.0.4 and it is already installed on the box (and VS skips this install), when uninstalling, it should not remove that SDK.

Still, I would argue that we SHOULD not remove the SDK and if the user wants to do so, he should do it separately. The SDK works independently of VS.

**Comment by davkean** [comment]
All other MSI use a ref-counting. It doesn't matter who installed it or when, the last one to uninstall it installs it.

The SDK is not the only component that works independently of VS.

**Comment by nguerrera** [comment]
This is what ref-counting is supposed to do. The user install would be ref count 1, subsequent VS 2, VS uninstall drops to 1, leaving it installed. 

I don't think the fact that it works independently from VS should matter. Chances are high that user who uninstalls VS wants to uninstall everything it installed (unless something bumped ref count). User can always install CLI again if they want. I think we're optimizing for the uncommon case as-is.

**Comment by livarcocc** [comment]
@davkean can you give me an example of other components in VS that behave like this? It would help with the code.

@nguerrera as long as we treat the user installation as a ref-count, I think we can discuss this.

cc @richlander

**Comment by davkean** [comment]
The portable library targeting pack is an example of this, but basically anything that is installed outside of the VS directory is in this bucket, as it becomes shared with multiple VS versions. Please reach out to the Willow folks on this - my knowledge about ref-counting is based on the previous installer, and it may have changed in the Willow world.

**Comment by onovotny** [comment]
This seems a little excessive. Do we really need to keep every old version around when VS updates?

![image](https://user-images.githubusercontent.com/1427284/33408760-16a27838-d546-11e7-98c9-dfbe88e34ce5.png)

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/6896.

**Comment by davkean** [comment]
My SDK folder still looks like this:
![image](https://user-images.githubusercontent.com/1103906/37948685-fc3cebd8-31dc-11e8-9c56-edafecbc2eb6.png)

**Comment by davkean** [comment]
Time to uninstall the 15 of the 16 SDKs on my machine right now:

![image](https://user-images.githubusercontent.com/1103906/38913846-34005e5c-4320-11e8-8052-346983e7c468.png)

**Comment by davkean** [comment]
![image](https://user-images.githubusercontent.com/1103906/40758896-d96ac8f4-64d2-11e8-9f08-56f4fc9a8a0e.png)

**Comment by AArnott** [comment]
For a VS Update, removing the previous SDK when an update is available could break builds (at least those that use global.json files to specify the SDK). So I'd prefer VS Update *not* remove the prior SDK version when it installs a newer one -- unless the prior one was just a -preview, in which case, remove away!

**Comment by davkean** [comment]
More feedback:
https://twitter.com/xoofx/status/1002221488488017921
https://twitter.com/algorithmsRcool/status/1002696081073934339
https://twitter.com/ArdaCetinkaya/status/1002172471947268096

**Comment by nguerrera** [comment]
Let's get this prioritized. I am asking internally about how to actually make the code change.

**Comment by davkean** [comment]
And another: https://twitter.com/chrismckee/status/1007184230521147392

**Comment by davkean** [comment]
Another one: https://twitter.com/onovotny/status/1011692391311597568.

**Comment by gulshan** [comment]
Can there be CLI tool (built-in or independent) to gracefully uninstall previous SDK and runtimes? There can be options for uninstalling all previews, all-but-last in a minor version etc.

**Comment by taori** [comment]
wasn't there some code back when it was dnx? like dnx upgrade to upgrade the cli. might as well just add options to drop preview sdk/previous minors

**Comment by KathleenDollard** [comment]
I think there are two separate problems: 

VS not uninstalling the SDK: The relationship is complex enough I think we'd want to walk through the permutations carefully. Especially since a missing SDK may be silent if global.json roll forward just runs a different SDK. 

Not uninstalling SDKs: It would be nice to have a `dotnet uninstall` with a few switches, including keeping any SDKs mentioned in global.json on a specified part of your box (with the warning of "patience required"). 

I also like the "uninstall previous" option on SDK install and the default uninstall of previews on release  install.

**Comment by 4creators** [comment]
> default uninstall of previews on release install.

IMHO it would be great if devs could have option to keep previews as well.

**Comment by 333fred** [comment]
@livarcocc any chance this could get assigned? Just freed up another couple of gigs on my machine by uninstalling old SDKs.

**Comment by mackcoding** [comment]
Are we live in 1995? Why is this seriously an issue?

**Comment by parrainc** [comment]
I'm just curious to know what's the status of this issue... @livarcocc @johnbeisner @davkean 
Are you guys working on it? My desktop was almost running out of space, and when I went to `Control Panel > Uninstall Programs`, noticed there were tons of .net sdk versions as shown in above picture.

**Comment by KathleenDollard** [comment]
Yes, we are working on both the issue of old SDKs and easier ways to acquire the SDK.

**Comment by parrainc** [comment]
@KathleenDollard awesome, good to know!! Thanks for the update :+1:

**Comment by absalonv** [comment]
@KathleenDollard any new updates?

**Comment by KathleenDollard** [comment]
Starting in Preview 3 of .NET Core 3.0, the Windows Installer treats each "feature band" as a single product and installs over previous copies. This means all versions of 3.0 will install over each other (preview and release), and then all versions of 3.1. 

We hope to have a global tool that releases older tools later, but for now the existing SDKs must be removed by hand.

**Comment by AArnott** [comment]
> This means all versions of 3.0 will install over each other (preview **and release**), and then all versions of 3.1.

That sounds potentially very disruptive. We use global.json files to "pin" the SDK version used to build our product. Can we express just a major.minor version in that file? Right now [we specify 3 integers in the version](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/global.json). So if 2.2.104 were to be uninstalled automatically when a VS Update or a newer SDK version is installed because 2.2.105 became available, that would break our build.

**Comment by jnm2** [comment]
> Can we express just a major.minor version in that file?

++.

**Comment by nguerrera** [comment]
The new install upgrade behavior stays within the same bands that global.json allows roll-forwar, 3.0.2xx builds will not uninstall 3.0.1xx.

**Comment by nguerrera** [comment]
> So if 2.2.104 were to be uninstalled automatically when a VS Update or a newer SDK version is installed because 2.2.105 became available, that would break our build.

This is not true. If 2.2.104 is not found, it will roll forward to 2.0.1xx > 2.1.104 that can be found.

**Comment by nguerrera** [comment]
See https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#matching-rules

**Comment by johnbeisner** [comment]
Implemented for Visual Studio 16.3 Preview 1
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/186888

**Comment by mrlife** [comment]
@johnbeisner Is this available in Visual Studio for Mac?

**Comment by johnbeisner** [comment]
@mrlife 
Visual Studio for Mac has an uninstall process that should address the removal of an SDK - however, my understanding is that the uninstall is not a single gesture.
@GouriKumari 
Can you point to the Visual Studio for Mac uninstall documentation.

**Comment by GouriKumari** [comment]
You can find the  doc here: https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019

**Comment by GouriKumari** [comment]
@mrlife : This feature is not there for Visual Studio For Mac installer.
