### ISSUE TITLE
Uninstall gives me welcome message and tells me how to disable telemetry

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#6898]
This is running an uninstall, not an install:

![image](https://user-images.githubusercontent.com/75470/27206582-39067942-51ed-11e7-8cbd-597129076df6.png)

**Comment by livarcocc** [comment]
Yes. @wli3 This is the issue that I talked to you a while ago.

**Comment by wli3** [comment]
It was fixed in this pull request.
https://github.com/dotnet/cli/pull/6567

Btw, there is another new UI change, here is the pull request, https://github.com/dotnet/cli/pull/6900
