### ISSUE TITLE
Uninstalling all versions of .NET Core SDK and runtime leaves files behind

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#6899]
I've uninstalled everything and still have the following on disk:

```
C:\Program Files\dotnet\host
C:\Program Files\dotnet\dotnet.exe
C:\Program Files\dotnet\LICENSE.txt
C:\Program Files\dotnet\ThirdPartyNotices.txt
C:\Program Files\dotnet\host\fxr
C:\Program Files\dotnet\host\fxr\1.1.0
C:\Program Files\dotnet\host\fxr\1.1.0\hostfxr.dll
```

I know these are shared between versions, but is there no ref counting system to remove them when the last installation using them is removed?

**Comment by livarcocc** [comment]
Please, move this to core-setup. These are all host files.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/core-setup#2697
