### ISSUE TITLE
Fix daily apt-get feed

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#6907]
![image](https://user-images.githubusercontent.com/6993335/27234372-a4c941bc-5271-11e7-9e3a-ee1237e34aa5.png)

publish failure in azure-apt-cat queue, as missing dotnet-runtime-2.0.0-preview2-25407-01, but this time is our own package dotnet-sdk instead of our dependency. The root cause has not been solved yet.

**Comment by wli3** [comment]
https://github.com/dotnet/core-setup/issues/2715

**Comment by wli3** [comment]
We are testing the deb directly, so it is not an issue currently

**Comment by wli3** [comment]
There is a bug downloading file on apt-cat service. We could implement check sum, or try to upload the package directly instead of sending blob storage URL

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/7384

**Comment by wli3** [comment]
https://github.com/aspnet/MetaPackages/issues/231

**Comment by livarcocc** [comment]
I believe we stopped using the daily apt-get feed. If that's the case, @wli3, can we go ahead and close this?

**Comment by wli3** [comment]
aspnet start to work on daily apt-get feed from last week (https://github.com/aspnet/MetaPackages/issues/231). We should re-enable publish to apt-get feed once they are done. cc @johnbeisner

**Comment by wli3** [comment]
daily debian/rpm feed is no longer supported
