### ISSUE TITLE
xUnit Test-Discovery seems not be working with Preview 2 in VS 2017 Preview (1 and 2)

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/cli#6910]
Not sure where i should post this issue (xUnit, VisualStudio, Cli) => please move on the right place
please advice if i can provide more/other informations/traces

## Steps to reproduce
"Visual Studio Enterprise 2017 Preview (2) Version 15.3.0 Preview 2.0"
plus
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0-preview2/dotnet-sdk-latest-win-x64.exe
## Expected  behavior
Test Explorer should list some tests

## Actual behavior
0 tests
no exception/additional messages in "Show Output from Tests"

## Additional findings:
uninstalling dotnet cli Preview2
re-installing Preview 1 (2.0.0-preview1-005977)
solves the problem i can see all my tests- it looks like the problem correlates with preview 2
Not able to solve the problem by 
- updateing nuget packages , 
- clear some VS-TestExtension Caches
etc..

The same problem with two different projects => Preview1 working, Preview2 not working....
Attention: i'm using the newest VS 2017 Update "Preview 2" ....
But i had the same problem with the VS 2017 Preview 1!

My test.csproj is simple:
[https://gist.github.com/WernerMairl/e8f2728d7717869c8ab3816c68fbe0a0](url)

Pure cli "dotnet test" is working, the issue is about VS-Test Discovery!

## Environment data
`dotnet --info` output:
dotnet --info
.NET Command Line Tools (2.0.0-preview2-006470)

Product Information:
 Version:            2.0.0-preview2-006470
 Commit SHA-1 hash:  4ea3671bbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006470\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#871
