### ISSUE TITLE
F# Project Reference issue on netcore 2.0

### ISSUE THREAD

**Issue by ncave** [dotnet/cli#6912]
The following F# project works fine when TargetFramework is `netstandard1.6 / netcoreapp1.0`
but fails with `netstandard2.0 / netcoreapp2.0` (but same project works on 2.0 if --language is C#).

## Steps to reproduce

/test/lib/lib.fsproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**/*.fs" />
    <Compile Include="Library.fs" />
  </ItemGroup>
</Project>
```
/test/app/app.fsproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../lib/lib.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="**/*.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```
/test/lib/Library.fs:
```
namespace Lib
module Say =
    let hello name = printfn "Hello World from %s!" name
```
/test/app/Program.fs:
```
[<EntryPoint>]
let main argv =
    Lib.Say.hello "F#"
    0
```
## Expected  behavior
`Hello World from F#!`

## Actual behavior
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Lib.Say.hello(System.String)'.
   at Program.main(String[] argv)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.0-preview1-006474)

Product Information:
 Version:            2.1.0-preview1-006474
 Commit SHA-1 hash:  e3d388e82d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-006474\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by ncave** [comment]
@dsyme @KevinRansom @enricosada Is this the same as #6863 or is it just similar?

**Comment by enricosada** [comment]
@ncave probably yes.

As a note, please use the `release/2.0.0` branch for `2.0`, that's the next version who will be released (`master` like your version, is `2.1.0`

**Comment by ncave** [comment]
@enricosada I tried release/2.0.0 before, same thing.

**Comment by enricosada** [comment]
@ncave can you try if @dsyme PR fix that? i am trying lot of combinations but i cannot repro this bug locally...

**Comment by ncave** [comment]
@enricosada What's the easiest way to try that? Do I need to point some target to a custom compiler build?

**Comment by enricosada** [comment]
@ncave i converted your minimal repro in a test case https://github.com/dotnet/cli/pull/6914

**Comment by cartermp** [comment]
@ncave Though I haven't debugged it, I think this is the same as #6863.

**Comment by ncave** [comment]
@cartermp Yes, I tested with a CI build, [visualfsharp#3215](https://github.com/Microsoft/visualfsharp/pull/3215) fixes it.

**Comment by cartermp** [comment]
\m/

**Comment by livarcocc** [comment]
@KevinRansom can you take a look at this?

**Comment by cartermp** [comment]
This is the same issue as #6863 - I think we can close this as use that as the canonical issue.  The fix is in for the compiler, but we need to get that version into the SDK.

**Comment by ncave** [comment]
@livarcocc @cartermp Just tested with 2.0.0-preview2-006494, it's fixed. Closing.
