### ISSUE TITLE
Can dotnet pack include symbols in the same package?

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/cli#6915]
The `--include-symbols` switch creates a separate symbols package. However, a commonly used approach is to include the PDBs (patched with SourceLink or GitLink) directly in the main package. Is there a way to tell `dotnet pack` to include the PDBs in the main package, rather than a separate symbols package?

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#5440
