### ISSUE TITLE
dotnet restore doesn't use installed credential providers

### ISSUE THREAD

**Issue by craigb** [dotnet/cli#6916]
## Steps to reproduce
1. Install the VSO [nuget credential provider](https://www.visualstudio.com/en-us/docs/package/nuget/nuget-exe)
1. Take a dependency on a VSO nuget package feed
1. `dotnet restore`

## Expected  behavior
I would expect it to auth and retrieve information about packages just like `nuget.exe restore`.
```
CredentialProvider.VSS: Getting new credentials for source: ...
Installing ...
```

## Actual behavior
```
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Failed to retrieve information... 
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized).
```

## Environment data
`nuget help`: 
NuGet Version: 4.1.0.2450

`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5447
