### ISSUE TITLE
xproj -> csproj migration, postrestore script hook unsupported

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#6919]
## Steps to reproduce
Open a project.json based solution in vs2017 to trigger the migration, where the project.json has:

```

 "scripts": {
    "postrestore": [ "npm install", "npm run jspm install" ],
    "prepublish": [ "dotnet bundle", "npm run jspm bundle js/site wwwroot/bundle.js" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }

```

The migration fails:

```
DnnManager.Website\DnnManager.Website.xproj: Failed to migrate XProj project DnnManager.Website. 'dotnet migrate --skip-backup -s -x "C:\Users\darre\Source\Repos\dnnmanager.web\src\DnnManager.Website\DnnManager.Website.xproj" "C:\Users\darre\Source\Repos\dnnmanager.web\src\DnnManager.Website" -r "C:\Users\darre\AppData\Local\Temp\gdwdtbic.vqh" --format-report-file-json' exited with error code 1.

DnnManager.Website\DnnManager.Website.xproj: MIGRATE1019::Unsupported Script Event Hook: postrestore is an unsupported script event hook for project migration

DnnManager.Website\DnnManager.Website.xproj: Project DnnManager.Website migration failed (C:\Users\darre\Source\Repos\dnnmanager.web\src\DnnManager.Website). MIGRATE1019::Unsupported Script Event Hook: postrestore is an unsupported script event hook for project migration


## Expected  behavior

Migrates the script to equivalent msbuild?

## Actual behavior

Migration fails. No guidance on how to resolve.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

```

**Comment by livarcocc** [comment]
This is an event that was not supported in preview2.

The reason why we don't handle the postrestore event is because migration was built to support valid preview2 project.json files and do a best effort on pre-preview2, as there as no good set of options available to us to map those project.json to csproj.

I would recommend commenting out (or removing the event) and attempting migration again.

**Comment by dazinator** [comment]
So there is no msbuild based eqivalent hook for post restore? The reason I ask is because my projects have npm as well as jspm dependencies that should also be restored. i'd like to have a dotnet restore restore all my project dependencies not just the nuget ones leaving the developer to also do npm and jspm restores seperately..
