### ISSUE TITLE
dotnet {build,run} should fail gracefully with bad target framework

### ISSUE THREAD

**Issue by jskeet** [dotnet/cli#6927]
## Steps to reproduce

- In a new directory, run `dotnet new console`
- Look at the generated project file to see what framework version it targets, e.g. `netcoreapp1.1`
- Run `dotnet restore`
- Run `dotnet build -f netcoreapp1.0` - or any other *wrong* framework

## Expected  behavior

A single, easily-understood error message saying that the project file doesn't support the specified framework.

## Actual behavior

An error message for every type referenced anywhere. Out of the box for a console app, 29 errors. For Noda Time, 10,000+ errors.

## Environment data
`dotnet --info` output:

```text
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

(Now trying in 2.0 preview 1 to see if it's better)

**Comment by jskeet** [comment]
Just tried with 2.0 preview 1 and it fails in the same way

```text
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by dsplaisted** [comment]
This should be fixed in later builds of the 2.0 SDK, I think.

Sent from my Windows 10 phone

**Comment by wli3** [comment]
![image](https://user-images.githubusercontent.com/6993335/27300621-25e488ea-54e5-11e7-8ae1-1d78453de548.png)

@dsplaisted looks so.

**Comment by livarcocc** [comment]
Yep. Closing this. @jskeet if there is anything else going on with this issue, please, re-activate.
