### ISSUE TITLE
Allow option to skip unsupported frameworks when building a solution

### ISSUE THREAD

**Issue by jskeet** [dotnet/cli#6928]
It's much more convenient to build a solution file than each individual project file.

That's great when all the projects *can* be built in all framework versions, but it fails when some or all projects only work for some environments.

The obvious example of this is when some projects target (say) `net45` and `netstandard1.3` (as Noda Time does). On my Linux CI machine, I'd like to *only* build the .NET Core versions - `net45` isn't going to work because I don't have all the relevant bits installed for desktop reference assemblies. (And even if I did, I wouldn't be able to run them without getting Mono set up.)

As a result, I have to build each individual project, specifying the target framework that will work for that environment - and that gets old really quickly. It would be nice if I could run

```sh
dotnet restore src/NodaTime-All.sln
dotnet build src/NodaTime-All.sln --skip-unsupported-frameworks
```

(or similar)

**Comment by livarcocc** [comment]
The way to do this today is to condition your TFM on OS. Also, we will have cross-platform full framework compilation in 3.0.

```
<TargetFrameworks>netstandard2.0;net46</TargetFrameworks>
<TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard2.0</TargetFrameworks>
```
