### ISSUE TITLE
Corrupted path error after using `dotnet test -l trx -r some\path\`

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#6929]
## Steps to reproduce

    dotnet test -l trx -r ..\..\bin\PCLCrypto.Tests.NETCore\netcoreapp1.0\

Note that auto-completion in powershell automatically adds the trailing backslash to the directory name, which is what triggers the failing behavior. If I remove the trailing backslash, I get a correct test run.

## Expected  behavior

A successful test run.

## Actual behavior

```
Build started, please wait...
Build completed.

Test run for C:\git\PCLCrypto\bin\PCLCrypto.Tests.NETCore\netcoreapp1.0\PCLCrypto.Tests.NETCore.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The path '..\..\bin\PCLCrypto.Tests.NETCore\netcoreapp1.0" C:\git\PCLCrypto\bin\PCLCrypto.Tests.NETCore\netcoreapp1.0\PCLCrypto.Tests.NETCore.dll' specified in the 'ResultsDirectory' is invalid. Error: The given path's format is not supported.
```

Note the bizarre placement of double and single quotes in the error message. I'm pretty sure the trailing backslash in my command line argument that triggers the failure is being misinterpreted as an escape character by something during command line processing.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005842)

Product Information:
 Version:            2.0.0-preview1-005842
 Commit SHA-1 hash:  63832070dd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005842\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#878
