### ISSUE TITLE
dotnet-restore

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#694]
Create a dotnet-restore command that uses NuGet to bring down a project's tools dependencies.

Tools dependencies are listed in a top-level `tools` node in the project.json. The node contains a list of NuGet packages specified with the same language as used by the `dependencies` node. 

Tools are allowed to run with their own dependency closure. As such, they are restored independently of the referencing project. For each tool we create a project.json that references Framework dnxcore50:

````
{
    "frameworks": { "dnxcore50" : {} }
}
````

We then `dnu install` the tool package into that project, resolving the tool along with all of its dependencies. Next, a deps file for the tool is generated and placed next to the tool's entry point assembly in the package cache. Finally, the project.lock.json for the tool is stored in the project's `artifacts/Tools/{Tool Package Name} directory to enable dotnet.exe to find the entry point assembly.

**Comment by brthor** [comment]
Fixed #713
