### ISSUE TITLE
Is there any way to install DNVM DNX to TFS build using powershell script?

### ISSUE THREAD

**Issue by nishant261989** [dotnet/cli#6947]
Below is the powershell script we are using:

`# bootstrap DNVM into this session.
&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://github.com/aspnet/dnvm/tree/dev/src/dnvm.ps1'))}`

`# load up the global.json so we can find the DNX version`
`$globalJson = Get-Content -Path $PSScriptRoot\global.json -Raw -ErrorAction Ignore | ConvertFrom-Json -ErrorAction Ignore`

`if($globalJson)
{
    $dnxVersion = $globalJson.sdk.version
}
else
{
    Write-Warning "Unable to locate global.json to determine using 'latest'"
    $dnxVersion = "latest"
}`

`# install DNX`
`# only installs the default (x86, clr) runtime of the framework.`
`# If you need additional architectures or runtimes you should add additional calls`
`# ex: & $env:USERPROFILE\.dnx\bin\dnvm install $dnxVersion -r coreclr`
`& $env:USERPROFILE\.dnx\bin\dnvm install $dnxVersion -Persistent`

 `# run DNU restore on all project.json files in the src folder including 2>1 to redirect stderr to stdout for badly behaved tools`
`Get-ChildItem -Path $PSScriptRoot -Filter project.json -Recurse | ForEach-Object { & dotnet restore $_.FullName 2>1 }`

But on Run it is throwing below error:

> + </a>        <a href="/business" class="js-selected-navigation-item na ...
+             ~
The '<' operator is reserved for future use.
At line:122 char:13
+ </a>        <a href="/explore" class="js-selected-navigation-item nav ...
+             ~
The '<' operator is reserved for future use.
At line:124 char:17
+ </a>            <a href="/marketplace" class="js-selected-navigation- ...
+                 ~
The '<' operator is reserved for future use.
At line:126 char:13
+ </a>        <a href="/pricing" class="js-selected-navigation-item nav ...
+             ~
The '<' operator is reserved for future use.
At line:128 char:11
+ </a>      </nav>
+           ~
The '<' operator is reserved for future use.
At line:8632 char:227
+ ... g:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
At line:8635 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At line:8665 char:11
+       <li>&copy; 2017 <span title="0.21257s from github-fe-8320e0c.cp ...
+           ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
At line:8665 char:23
+       <li>&copy; 2017 <span title="0.21257s from github-fe-8320e0c.cp ...
+                       ~
The '<' operator is reserved for future use.
At line:8665 char:29
+ ...  2017 <span title="0.21257s from github-fe-8320e0c.cp1-iad.github.net ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unexpected token 'title="0.21257s from github-fe-8320e0c.cp1-iad.github.net">GitHub</span>' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
At D:\a\_temp\63feade6-67e8-49f9-803c-265fd347fb81.ps1:1 char:17
+ ... ranch='dev';iex ((new-object net.webclient).DownloadString('https://g ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : RedirectionNotSupported,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by livarcocc** [comment]
dnmv and dnx are no longer supported. You should move to the .NET Core SDK (CLI). In which case, we do have install scripts that allow you to download the SDK and install it on a machine. Do note that in case, you will have to migrate your dnx project.json to msbuild, which dotnet migrate will not do for you. dotnet migrate only handles CLI 1.0.0-preview2 project.json and onward.
