### ISSUE TITLE
Cannot run dnc v1 C# projects alongside dnc v2 preview 1 install (on Ubuntu)

### ISSUE THREAD

**Issue by arvopartet** [dotnet/cli#6950]
Why is it not possible to run dotnet core version 1 C# projects anymore once you have installed version 2 preview 1 alongside (on Ubuntu)?

## _Steps to reproduce_ Behaviour

_dotnet build_
Microsoft (R) Build Engine version 15.3.117.23532
Copyright (C) Microsoft Corporation. All rights reserved.

  my_app -> path/my_app.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.38

_dotnet run_
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.1.2'.

## Expected  behavior

Hello World!

## Environment data

_my_app.csproj_
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>
```

_dotnet --info output_
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

_dpkg -l dotnet*_
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  dotnet         <none>       <none>       (no description available)
ii  dotnet-dev-1.0 1.0.1-1      amd64        .NET Core SDK 1.0.1
ii  dotnet-dev-2.0 2.0.0-previe amd64        Microsoft .NET Core 2.0.0 - SDK P
ii  dotnet-host    2.0.0-previe amd64        Microsoft .NET Core 2.0.0 Preview
ii  dotnet-hostfxr 1.0.1-1      amd64        Microsoft .NET Core 1.0.0 - Host 
ii  dotnet-hostfxr 1.1.0-1      amd64        Microsoft .NET Core 1.1.0 - Host 
ii  dotnet-hostfxr 2.0.0-previe amd64        Microsoft .NET Core 2.0.0 Preview
un  dotnet-nightly <none>       <none>       (no description available)
ii  dotnet-sharedf 1.0.4-1      amd64        Microsoft .NET Core 1.0.4 - Runti
ii  dotnet-sharedf 1.1.1-1      amd64        Microsoft .NET Core 1.1.1 - Runti
ii  dotnet-sharedf 2.0.0-previe amd64        Microsoft .NET Core 2.0.0 Preview

**Comment by livarcocc** [comment]
Do you have both 1.0 and 2.0 CLI installed in the same location? The reason you are seeing this is because the 2.0 CLI does not bring with it the 1.0 runtimes. If we were doing that, we would have to keep adding runtimes to the CLI and it would grow very fast, very much in size.

Running 1.0 apps with/when 2.0 is installed is very much a supported scenario. What I suspect is going on here is that you may have the two CLIs in different locations and you don't have the 1.1.2 runtime installed in the same location as the 2.0 CLI.

Can you check that? Either put the two CLIs together or install the 1.1.2 runtime next to the shared runtimes in the 2.0 CLI location.

**Comment by livarcocc** [comment]
Closing this issue for now, since we haven't had activity on it in a while. Please, re-active where more info if the explanation above does not help.

**Comment by arvopartet** [comment]
Thanks @livarcocc for replying. 

How would I check the location of where the CLI is installed (please specify CLI instructions) ?

In the dpkg -l output shows that both are installed. But not the locations!

Where would I be able to check the configuration files?

Thanks again.

**Comment by arvopartet** [comment]
What we know so far:
With dotnet 1 & preview 2 installed
dotnet 1 applications that were running before are no longer running.

using `dotnet build` works, the bin/Debug/netcoreapp1.1 folder contains new files.
dotnet run > fails.

Checked folder locations:
When not including man and doc.
using:
`dpkg -L`

Dotnet 1 seems to be mainly in:  ( dotnet-dev-1.0.1 )
- /usr/share/dotnet/sdk/1.0.1

Dotnet 2 preview seems to spread out:  ( dotnet-dev-2.0.0-preview1-005977 )
- /usr/share/dotnet/sdk/2.0.0-preview1-005977
- /usr/share/dotnet/store/x64/netcoreapp2.0
- (/usr/share/dotnet/additionalDeps)

Dotnet software marked in the description as Runtime:  ( software name /n folder )
dotnet-sharedframework-microsoft.netcore.app-1.0.4
/usr/share/dotnet/shared/Microsoft.NETCore.App/1.0.4

dotnet-sharedframework-microsoft.netcore.app-1.1.1
/usr/share/dotnet/shared/Microsoft.NETCore.App/1.1.1

dotnet-sharedframework-microsoft.netcore.app-2.0.0-preview1-002111-00
/usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.0-preview1-002111-00

All the runtime folders contain files (.dll .so ...)

Questions:

How is `dotnet run` configured to check folder locations for different runtime?
@livarcocc 

As build seems to work and produce output run seems unable to go to the correct folder.

There is a file present in the /bin/Debug/netcoreapp1.1 called `<project>.runtimeconfig.json`
this contains the information:
`
{
  "runtimeOptions": {
    "tfm": "netcoreapp1.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.2"
    }
  }
}
`
It seems unable to resolve this information ( 1.1.2 ) into using the correct folder for dotnet framework 1.1.1

Where does it try to resolve this?

Thanks in advance.

**Comment by arvopartet** [comment]
I have compared two dotnet 1 application's `<project>.runtimeconfig.json` files. One build by dotnet framework 1.1 and one by preview 2.

Result of 1.1  ( used to work ):
`{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.1"
    }
  }
}`


Result of dotnet preview 2  ( does not work ): 
`{
  "runtimeOptions": {
    "tfm": "netcoreapp1.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "1.1.2"
    }
  }
}`

I do not suppose it is a simple matter of changing the version number...

**Comment by livarcocc** [comment]
Can you install the 1.1.2 runtime?

The problem here is that in the 2.0 SDK, we updated the implicit runtime version to 1.1.2 from 1.1.1, for security reasons. But you don't have that runtime in the box.

So, you can either install that runtime or pin your runtime version to 1.1.1 by setting `<RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>` in your csproj.

**Comment by arvopartet** [comment]
I have opted for installation of the 1.1.2 runtime and the old 1.1.1 projects I tested `build` and `run` again.

Thanks livarcocc!

P.S. What should I read next time to know beforehand?
