### ISSUE TITLE
Tests results not aggregating result for each targetFrameworks

### ISSUE THREAD

**Issue by bhugot** [dotnet/cli#6951]
## Steps to reproduce

Create a test project with 2 targetFrameworks and 1 Test

run Dotnet Test  --logger "trx;LogFileName=abc.trx"

## Expected  behavior

The file abc.trx should contains 2 lines, one for each target framework

## Actual behavior

There is only one line for the last targetFramework used.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Users\bhugot100316\.dotnet\x64\sdk\2.0.0-preview2-006127\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#880
