### ISSUE TITLE
netstandard and net461

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#6956]
## Steps to reproduce
In my csproj, I am targeting netstandard 1.6

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Gluon.Core Class Library</Description>
    <Authors>Darrell.Tunnell</Authors>
    <TargetFramework>netstandard1.6</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Gluon.Core</AssemblyName>
    <PackageId>Gluon.Core</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <UpdateVersionProperties>true</UpdateVersionProperties>
  </PropertyGroup>

```

I then have another project targeting net 461 that references the first netstandard1.6 project.

dotnet restore on the net 461 project then outputs this:

```
Project Gluon.Core is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x86. Project Gluon.Core supports: netstandard1.6 (.NETStandard,Version=v1.6)
      One or more projects are incompatible with .NETFramework,Version=v4.6.1 (win7-x86).
```

Yet from this table: https://docs.microsoft.com/en-gb/dotnet/standard/net-standard netstandard1.6 should be compatible with net461. What am I missing?

## Expected  behavior
targeting netstandard1.6 library from net461 project should be valid.
## Actual behavior
Not valid.

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
PS C:\Users\darrell.tunnell\Source\Repos\gluon\src>

**Comment by livarcocc** [comment]
net461 is compatible with netstandard1.6 when using the 2.0 tooling. With the 1.0 tooling, net461 is compatible with netstandard1.4.

**Comment by dazinator** [comment]
Ok.. can you clarify what / where is the 2 tooling? Is there a dotnet cli 2? I can only see a dotnet cli 1.1 on the cli sdk download page.

**Comment by livarcocc** [comment]
https://www.microsoft.com/net/core/preview#windowscmd.

Also, https://github.com/dotnet/cli/tree/release/2.0.0.

**Comment by dazinator** [comment]
I should note, I am using vs2017 latest version.

**Comment by dazinator** [comment]
Couple more questions if you don't mind!

If i install this newer tooling, i assume it will be uaed by default and therefore for solutions on older tooling they will now need to be locked down by adding global.json? 

Where can I see about any reaking changes - im thinking of our Team City build process for the solution i.e the command line may now look different than it did for v1 of the the cli.

In terms of running the app that is built with the new v2 tooling, do I need to install a new runtime / hosting msi on our webservers so that the app will run?

Cheers

**Comment by dazinator** [comment]
Thank you, much appreciated. Will give it a shot.
