### ISSUE TITLE
DotNetCliReference causes multiple confusing "Restoring" messages

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#6960]
## Steps to reproduce

With _n_ number of DotNetCliReferences you get _n+1_ "restoring packages" messages. One per tool, plus one for the actual package references.

## Expected behavior

You should get "restoring tools" once and "restoring packages" once.

## Actual behavior

![image](https://user-images.githubusercontent.com/2892/27357136-e16f434e-55c5-11e7-9859-d356c072e880.png)

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview2-006391)

Product Information:
 Version:            2.0.0-preview2-006391
 Commit SHA-1 hash:  ef5d4b47c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16215
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006391\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5462
