### ISSUE TITLE
NU1102 during restoring package

### ISSUE THREAD

**Issue by shimingsg** [dotnet/cli#6966]
## Steps to reproduce
1. have clean Ubuntu 16.04 VM
2. sudo apt-get install **dotnet-sdk-2.1.0-preview1-006491**
3. make a folder and cd to it
4. dotnet new console

## Expected  behavior
project created and restore successfully

## Actual behavior
restore failed

**the output message as following:**
puser@p-shige:~/testp$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/puser/testp/testp.csproj...
  Restoring packages for /home/puser/testp/testp.csproj...
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.netc                  ore.app/index.json'.
  Access to the path '/home/puser/.local/share/NuGet/v3-cache/1ca707a4d90792ce8e42453d4e350886a0fdaa                  4d$ps:_api.nuget.org_v3_index.json/list_Microsoft.NETCore.App.dat-new' is denied.
    Permission denied
/home/puser/testp/testp.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with ver                  sion (>= 2.0.0-preview3-25415-01)
/home/puser/testp/testp.csproj : error NU1102:   - Found 12 version(s) in nuget.org [ Nearest versio                  n: 2.0.0-preview1-002111-00 ]
/home/puser/testp/testp.csproj : error NU1102:   - Found 1 version(s) in CliFallbackFolder [ Nearest                   version: 2.0.0-preview2-25407-01 ]
  Generating MSBuild file /home/puser/testp/obj/testp.csproj.nuget.g.props.
  Generating MSBuild file /home/puser/testp/obj/testp.csproj.nuget.g.targets.
  Restore failed in 37.82 sec for /home/puser/testp/testp.csproj.

Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

## Environment data
`dotnet --info` output:

puser@p-shige:~/testp$ dotnet --info
.NET Command Line Tools (2.1.0-preview1-006491)

Product Information:
 Version:            2.1.0-preview1-006491
 Commit SHA-1 hash:  bd7bd69530

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.0-preview1-006491/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25415-01
  Build    : 0fb328316c72fef971a096d14f93b2474290210e

**Comment by ramon-garcia** [comment]
This seems to be duplicated from #6730

**Comment by livarcocc** [comment]
Yes. it is. Closing this one.
