### ISSUE TITLE
'dotnet new --install Microsoft.AspNetCore.SpaTemplates::*' fails with  'Segmentation fault: 11'

### ISSUE THREAD

**Issue by codeWonderland** [dotnet/cli#6971]
## Steps to reproduce
dotnet new --install Microsoft.AspNetCore.SpaTemplates::*

## Expected  behavior
Installs the new templates into dotnet

## Actual behavior
Segmentation fault: 11
bash-3.2#   Restoring packages for /Users/codeWonderland/.templateengine/dotnetcli/v1.0.4/scratch/restore.csproj...

## Environment data
Running MacOS 10.13 Beta
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#977
