### ISSUE TITLE
Missing argument for unresolvedReference from reference created in CLI

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#6978]
## Steps to reproduce
Use latest d15rel and 2.0.0 CLI preview.

1. In CLI create an empty solution and add a new C# console app to it.
2. Create a C# Class library.
3. Add a reference from the console app to the C# class library
4. Open the solution in VS.
5. In the solution explorer, expand the Dependencies tab to the class library. (Dependencies -> Projects -> (nameof Classlib))
6. Double click on the class library there.

## Actual behavior
A pop up shows up saying "Value cannot be null. Parameter name: unresolvedReference"
![image](https://user-images.githubusercontent.com/10537189/27409880-b2098956-5698-11e7-810e-a4e183704ca4.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006498)

Product Information:
 Version:            2.0.0-preview2-006498
 Commit SHA-1 hash:  a5698110a2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006498\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by livarcocc** [comment]
@srivatsn can you take a look? I am not sure this is an issue with the CLI or the SDK.

**Comment by srivatsn** [comment]
This is https://github.com/dotnet/project-system/issues/403

**Comment by shelland** [comment]
Got the same issue after adding of .NET Standard 2.0 library as a reference to .NET Core 2.0 Web App.

DotNet info:

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

_Visual Studio 2017 v.15.5.0_

Library reference can not be resolved, while there's no any yellow warning sign on the referenced library i still can not use any classes from there.

**Comment by livarcocc** [comment]
@shelland can you share a small repro or share your csproj files that are failing?

**Comment by shelland** [comment]
@livarcocc It looks like ReSharper v.2017.1 caused this issue. After updating to the latest version i don't have any problems anymore. Thanks.
