### ISSUE TITLE
Enable CrossGen of Stage 1

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#698]
A recent build produced the following abbreviated log:
10:56:23	*** Building dotnet tools version 1.0.0-dev-1451933517 - Debug ***
10:56:23	*** Checking Pre-Reqs ***
10:56:23	*** Restoring Tools and Packages ***
10:56:23	*** Installing dotnet stage 0 ***
10:56:31	*** Downloading DNX  ***
10:56:31	*** Restoring packages ***
11:00:18	*** Compiling ***
11:00:32	*** Building corehost ***
11:00:32	*** Building stage1 dotnet using downloaded stage0 ... ***
11:03:56	*** Building stage2 dotnet using just-built stage1 ... ***
11:16:28	*** Crossgenning Roslyn compiler ...
11:17:34	*** Acquiring Native App Dependencies ***
11:18:05	*** Testing stage2... ***
11:21:12	*** Validating Dependencies ***
11:21:29	*** Generating tarball ***
11:21:29	*** Packaging dotnet-ubuntu-x64.1.0.0-dev-1451933517 ***
11:21:47	*** Publishing package ***
11:21:47	*** Skipping packaging ***
11:21:47	*** Building Docker Container ***
11:21:47	*** Launching build in Docker Container ***

Stage 1 compilation takes ~3 minutes. Stage 2 takes ~13 minutes. The only expected difference between stage 0 and stage 1, aside from newly introduced changes, should be crossgen. According to this log, the cost of crossgen is ~1 minute. This suggests that enabling crossgen for Stage 1 should net a win of 12 minutes of build time. On an ~25 minute build, this is a reduction of almost 50%.

**Comment by brthor** [comment]
:+1:

**Comment by piotrpMSFT** [comment]
Resolved by #701
