### ISSUE TITLE
Mac package contains multiple versions of 'com.microsoft.dotnet.sharedhost.component.osx.x64'

### ISSUE THREAD

**Issue by gerardkok** [dotnet/cli#6984]
## Steps to reproduce

- Download 'macOS (x64) PKG' from https://www.microsoft.com/net/download/core, currently this gives you 'dotnet-dev-osx-x64.1.0.4.pkg'.
- expand the downloaded package ('pkgutil --expand dotnet-dev-osx-x64.1.0.4.pkg ~/Downloads/dotnet-1.0.4', for example)
- in the expanded folder, observe that the identifiers in 'com.microsoft.dotnet.sharedhost.1.0.1.component.osx.x64.pkg/PackageInfo' and 'com.microsoft.dotnet.sharedhost.1.1.0.component.osx.x64.pkg/PackageInfo' are both 'com.microsoft.dotnet.sharedhost.component.osx.x64'

## Expected  behavior

The identifiers to be different

## Actual behavior

The identifiers are the same

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

## Background

If you install manually, this is (probably) fine. It appears to become a problem when you try to automate the installer (e.g. through munki), because macOS will overwrite the first installation of 'com.microsoft.dotnet.sharedhost.component.osx.x64' with the second, so after installation you'll find that only one copy of 'com.microsoft.dotnet.sharedhost.component.osx.x64' has been installed.

After initial installation, subsequent checks to see if the entire package has been installed will find that one of the 'com.microsoft.dotnet.sharedhost.component.osx.x64' packages is missing, and try to reinstall. This will again install only one of those packages. This reinstall will then happen over and over again.

In my case it only installed the old version (1.0.1) of 'com.microsoft.dotnet.sharedhost.component.osx.x64' (which I suppose is not what you want, I think you will want the newer version to be installed), but I don't know the underlying mechanisms well enough to explain why that happened.

**Comment by livarcocc** [comment]
This is not incorrect. Both version of the shared runtime (1.0.1 and 1.1.0) do reference the same version of the host.

Closing the issue. Please, re-activate if I misunderstood the issue.
