### ISSUE TITLE
[Question] Any way for CLI app packaging?

### ISSUE THREAD

**Issue by JustArchi** [dotnet/cli#7002]
I plan on distributing command-line application based on .NET Core 2.0 to my users. The problem I'm facing right now is the fact that I have a lot of third-party libraries and resources (localization) in the output folder, making it super hard to navigate, and even harder when I decide to deploy my app in self-contained environment.

In .NET Framework I dealt with this issue by using **[Costura.Fody](https://www.nuget.org/packages/Costura.Fody/)** and **[Resource.Embedder](https://www.nuget.org/packages/Resource.Embedder/)** that together packaged both libraries as well as resources into one final exe file that I could distribute (and update easily).

I'm basically looking for the same with .NET Core now. Is there any way to package everything into one single exe for distribution? Or maybe there is some generally-acceptable approach of installing .NET Core-based app on target system? I'll need this to run on Windows, Linux and OS X, so I definitely don't want to make dedicated installers for each OS.

I googled my way around and the only mention I found was corert, but it seems like the project is about compiling everything into native code - I don't need that, I just need to "package" my managed app into a single file, together with all libraries and resources. I'm kinda stuck right now, and wondering if it's even possible using any available approach.

Thank you in advance for any tips.

**Comment by AlexByte** [comment]
http://druss.co/2016/08/deploy-and-run-net-core-application-without-installed-runtime-self-contained-applications/
To create self-contained application run following command:

`dotnet publish --configuration Release --runtime ubuntu.14.04-x64`
founded from https://stackoverflow.com/questions/39873960/net-core-package-dependencies

**Comment by livarcocc** [comment]
.NET Core does not support producing a single EXE today that contains your entire application. We currently support two distribution models: portable apps and self-contained apps. Portable apps are applications that required the shared runtime in the machines where the application is going to run. They are executable through 'dotnet your_app.dll'. The advantage of this one is that you can publish your app once and it will run on all machines with a shared runtime, independently of the OS.
The other approach, is the one pointed out by @AlexByte above, self-contained apps. This kind of publish scenario, the application is published for a specific OS, which means you would need one of these for each OS that you want your app to target.

**Comment by livarcocc** [comment]
I am closing the issue for now, if there is anything else you need, please, re-activate.

**Comment by JustArchi** [comment]
I know about both publishing methods that I'm using, the question is about producing a single binary in self-contained scenarios where user would have everything in a single binary he's about to run, whether it's e.g. exe on windows or elf on linux.

Anyway, you answered me, there is no way to do that at the moment. Thanks.
