### ISSUE TITLE
dotnet restore at solution-level doesn't follow ProjectReference with ReferenceOutputAssembly of false leading to random build failures

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/cli#7004]
## Steps to reproduce

The attached .zip contains a solution that reproduces the problem intermittently.

## Expected  behavior

dotnet restore on B finishes before C resulting in a good build of C

## Actual behavior

dotnet restore on C sometimes finishes too soon causing nonsense build errors.

## Environment data

Bug is partially mitigated by NTFS; please note that --disable-parallel and NTFS appear to fix the problem but really don't; a different set of names would cause the problem to reappear.

`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## Visual Studio

Visual Studio 2017 can't restore or build this reliably either.

[reduce-build-nasty.zip](https://github.com/dotnet/cli/files/1103276/reduce-build-nasty.zip)

Fixing issue #4781 would permit fixing the build issues in the .csproj files but would make builds much slower by recursively invoking dotnet restore

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5490

**Comment by jhudsoncedaron** [comment]
The reference that's breaking isn't a nuget reference at all.

**Comment by livarcocc** [comment]
restore handles both Package references and project references and restore is owned by NuGet. That's why I moved the bug.
