### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by Miclebrick** [dotnet/cli#7007]
## Steps to reproduce
1. Install dotnet
2. mkdir test
3. cd test
4. dotnet new mvc
5. dotnet restore
6. dotnet run

## Expected  behavior
Running of something

## Actual behavior
I merely get the error in the title.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

**Comment by livarcocc** [comment]
How did you install dotnet? also, can you set COREHOST_TRACE=1 and invoke dotnet run again and share the log file with us.

@karelz This is the host crashing. Can you help take a look?

**Comment by livarcocc** [comment]
@Petermarcu @steveharter can you guys help take a look?

**Comment by karelz** [comment]
@steveharter is the right person to look at it.

**Comment by Petermarcu** [comment]
@Miclebrick , how did you install? Did you use the zip or apt-get?

**Comment by Miclebrick** [comment]
apt-get - Although I ended up just renting a SmarterASP server

**Comment by livarcocc** [comment]
Moving this issue to core-setup for now, if this turns out to be an SDK problem, please re-activate.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2808
