### ISSUE TITLE
dotnet store artifacts.xml file structure nits

### ISSUE THREAD

**Issue by guardrex** [dotnet/cli#7010]
## Steps to reproduce

Use the `dotnet store` command and examine the `artifacts.xml` target manifest file output.

## Expected  behavior

Neat file structure.

## Actual behavior

Little bit messy file structure:

```xml
<StoreArtifacts>
   <Package Id="castle.core"  Version ="4.1.0"/>
   <Package Id="moq"  Version ="4.7.63"/>
   <Package Id="newtonsoft.json"  Version ="10.0.3"/>
</StoreArtifacts>
```

* Three space indent on `Package` lines (instead of 2-spaces)
* Two spaces between `Id` value and `Version` attribute (instead of 1-space)
* Extra space between `Version` and its value (instead no space)
* No space inside of the closing `/>` (instead of 1-space)
* And although the source package store manifest file called for packages with their normal (human-friendly) casing (and I know this is just an aesthetics comment), the file shows all lowercase package names. No biggie, but just say'in.

So hoping for this ...

```xml
<StoreArtifacts>
  <Package Id="Castle.Core" Version="4.1.0" />
  <Package Id="Moq" Version="4.7.63" />
  <Package Id="Newtonsoft.Json" Version="10.0.3" />
</StoreArtifacts>
```

Source *packages.csproj*:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Moq" Version="4.7.63" />
  </ItemGroup>
</Project>
```

## Environment data

```
.NET Command Line Tools (2.0.0-preview3-006597)

Product Information:
 Version:            2.0.0-preview3-006597
 Commit SHA-1 hash:  262c9d9a12

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006597\


Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0-preview3-25419-01
  Build    : 2fab74ca0ab629adfe1291e3f1b5eeae2a57c156
```

**Comment by mikkelbu** [comment]
@guardrex As far as I can tell the problems are not in this project. We just call msbuild with a `/t:ComposeStore` option. The problems reside in the sdk, more precisely in this line.
https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.ComposeStore.targets#L142

All the spacing problems should be easy to solve (I don't know much about msbuild, so I cannot tell whether it is possible to solve the problem about casing).

**Comment by dasMulli** [comment]
@mikkelbu you're right that's where it comes from. Since this was practically done after playing around with that line, I went ahead and opened a PR..

**Comment by guardrex** [comment]
Thanks @mikkelbu. At the time I put this up, I was *insanely busy* and (of course) didn't go looking. This issue could be moved over to that repo. @dasMulli isn't that preferred? If so, I'll close here, open over there, and you can just update ur "Fixes" line to point to the new issue. Let me know.
