### ISSUE TITLE
[.netcore 2 preview 2] dotnet (restore | build | run) does not complete when symlinks are present

### ISSUE THREAD

**Issue by AerisG222** [dotnet/cli#7022]
### First - create a new test website:
````
dotnet new web
dotnet build
````
_This works_

### Next - add a symlink then try to build
````
cd wwwroot
ln -s /tmp images
cd ..
dotnet build
````
_This never completes_

## Expected  behavior
dotnet cli would restore, build or run the project regardless of the presence of symlinks

## Actual behavior
dotnet cli seems to run in an endless loop, consuming lots of CPU when symlinks are in project directories.  Deleting the symlink allows this to work again.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.25-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by livarcocc** [comment]
I just tried this out on OSX and this worked for me. Have you tried this in a different distro or machine. It may help us narrow down why this is happening. Or, how many files do you have under /tmp? How long did you want for this to complete?

**Comment by omajid** [comment]
Another question: where did you run `dotnet new web`? Was it under `/tmp` by any chance?

**Comment by AerisG222** [comment]
Sorry, just getting back from vacation, will try to run some more tests in the next day or two.

In the meantime here are some answers to prior questions:

- different distros / machines: I have not tried other systems
- #files in temp: not sure, will try against a different directory with a single file
- how long: I tried a number of times for a few minutes before killing, then let it just run for ~1hr before killing it
- where did i run `dotnet new web`: in my homedir

A bit more history - I had been running the site on preview 1 just fine.  However, after upgrading to preview 2, I started having this issue.

I am wondering if the tooling is doing more now than it had in the past.  In particular, in earlier versions, my scripts to `dotnet publish` the site would remove the symlinks then perform the publish, as I had run into a similar issue back then.

**Comment by AerisG222** [comment]
OK, after some additional testing, I am also seeing this on preview 1 on another machine.

@livarcocc, as you suspected, the time impact grows as the number of files in the referenced directory grows.  I tried a new test pointing at an empty directory, and dotnet build took ~2.7s.  I then added 3k files to the dir, and the build then jumped to 4.5s.  Adding another 3k took it to 7.7s.   Once I remove the symlink in the wwwroot directory, build is back down to 2.7s.

This certainly had been faster in the past when using dotnet run.  It is easy enough to delete then recreate the symlinks if needed, but is there a better way to configure this in .csproj to avoid this hit?

Thanks for your time/comments.

**Comment by livarcocc** [comment]
I suspect this is related more to the number of files than the fact that they are symlinks or not.

**Comment by livarcocc** [comment]
Closing this issue as I believe we fixed the underlying msbuild bug that was causing poor performance here.

Please, re-activate if this still reproes with the latest 2.0.0 CLI.

**Comment by AerisG222** [comment]
I tried with preview3 over the weekend, and it is still significantly slower when I have the large number of files.  It takes ~52s for `dotnet build` when I have all files, and about 5s when I trim that down significantly.  I am currently running the following version:

## MSBuild (from dotnet build):

Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core

## .NetCLI:

.NET Command Line Tools (2.0.0-preview3-006890)

Product Information:
 Version:            2.0.0-preview3-006890
 Commit SHA-1 hash:  be54917dc4

Runtime Environment:
 OS Name:     fedora
 OS Version:  26
 OS Platform: Linux
 RID:         fedora.26-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview3-006890/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
