### ISSUE TITLE
Didn't get the latest build on Linux

### ISSUE THREAD

**Issue by Sunny-pu** [dotnet/cli#7026]
## Steps to reproduce
Got the latest build is 2.0.0-preview3-006609 in page https://github.com/dotnet/cli/tree/release/2.0.0
1. download the package via wget -O ~/dotnet-dev-linux-x64.latest.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-linux-x64.tar.gz
2. extract the package
3. add the extract path to PATH
4. dotnet --info to check the build number

## Expected  behavior
the correct build number 2.0.0-preview3-006609

## Actual behavior
the build number is 2.0.0-preview3-006607

## Environment data
`dotnet --info` output:
[e2euser@e2e-rhel73 ~]$ dotnet --info
.NET Command Line Tools (2.0.0-preview3-006607)

Product Information:
 Version:            2.0.0-preview3-006607
 Commit SHA-1 hash:  81dd304f72

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /home/e2euser/20170629/sdk/2.0.0-preview3-006607/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25426-01
  Build    : 122309e7e7fb9bb233fe4910f822c28ec73f0957

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/6934.
