### ISSUE TITLE
Cannot install on Linux when Preview1 is present

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7027]
Copied from: https://github.com/dotnet/core/issues/717#issuecomment-312000817

## Steps to reproduce
follow the install instructions on how to install the apt-get package.

## Expected  behavior
install succeeds

## Actual behavior
I have follow both installation instructions in GitHub and the .NET Core Download page. I'm getting the same error message:

`Unpacking dotnet-sdk-2.0.0-preview2-006497 (2.0.0-preview2-006497-1) ...
dpkg: error processing archive /var/cache/apt/archives/dotnet-sdk-2.0.0-preview2-006497_2.0.0-preview2-006497-1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/dotnet/store/x64/netcoreapp2.0/microsoft.identitymodel.protocols/2.1.3/lib/netstandard1.4/Microsoft.IdentityModel.Protocols.dll', which is also in package dotnet-dev-2.0.0-preview1-005977 2.0.0-preview1-005977-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/dotnet-sdk-2.0.0-preview2-006497_2.0.0-preview2-006497-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by livarcocc** [comment]
@wli3 can you take a look at this one when you have a chance?

**Comment by Petermarcu** [comment]
It looks to me like the nuget cache is causing the SDK to no longer be SxS. We are not trying to update some components in place and the design of the installer is such that that is not supposed to happen.

**Comment by livarcocc** [comment]
The conflict above is in the runtime store, not the nuget cache though.

**Comment by Petermarcu** [comment]
Yeah, that would be the other place. :( I guess the Nuget cache doesn't conflict because it's not tracked by the installer but I bet the first run is overwriting or handling the fact that it's already there.

**Comment by Petermarcu** [comment]
@DamianEdwards @steveharter @muratg we probably need to meet to discuss this. I think the runtime store is going to need to go in a versioned folder.

**Comment by DamianEdwards** [comment]
Yeah when this was designed and discussed I believe in the room it was said that if the payloads were identical in the same path it would "just work". Seems that's not the case. I'm curious how *dotnet.exe* and things like that get around this though. Aren't they the same or updated between releases and in the same location on disk? Do we simply need to put the runtime store in its own package and depend on it?

**Comment by Petermarcu** [comment]
I agree, the same thought occurred to me. I'm going to try to talk to some of the folks that know packaging options better as well.

**Comment by Petermarcu** [comment]
I'm guessing its because the identity of the package is changing and not just the version.

**Comment by DamianEdwards** [comment]
It is? Is that because we're putting the "preview2" moniker in the package id/name? Why do we do that?

**Comment by DamianEdwards** [comment]
I'm guessing this is a side-by-side enabling thing?

**Comment by Petermarcu** [comment]
@leecow were discussing this. Apparently this isn't a new problem in preview releases and isn't specific to the runtime store. I'm going to be talking to a bunch of folks about installer options for fixing this. One step in the right direction is definitely to have the SDK depend on a package that is the runtime store. That way the runtime store can version independently of the SDK if needed and you don't need to install the SDK to get the runtime store. Beyond that, we need to look at the identity of the package and how to handle pre-releases better. One option would be to use the same identity but to use separate feeds.

**Comment by wli3** [comment]
2.0 preview SDK’s on Linux to be installed SxS is not supported

**Comment by wli3** [comment]
getting started https://www.microsoft.com/net/core/preview#linuxubuntu
And "2.0.0 Preview 2 Known Issues" https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0-preview2-known-issues.md#ubuntu---uninstall-preview-1-before-attempting-to-install-preview-2
