### ISSUE TITLE
Alternative to "packInclude"

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#703]
In "dnu" there is the `packInclude` option to include extra files when publishing or packing. There doesn't seem to be an alternative in dotnet.

We need this to pack/publish our tests that depend on extra files

**Comment by davidfowl** [comment]
PackInclude exists and works for packages. What specifically do you need?

**Comment by victorhurdugaci** [comment]
Should have been more explicit. It doesn't work when you publish.

Try this:

```
{
  "version": "1.0.0",
  "description": "ClassLibrary1 Class Library",

  "frameworks": {
    "net451": { }
  },
  "packInclude": {
    "/":  "TestFile.txt"
  }
}
```

and create `TestFile.txt` in the root of the project.

- Publish with `dnu` and notice that `TestFile.txt` is in `bin\output\approot\src\ClassLibrary1\TestFile.txt`
