### ISSUE TITLE
Access to path '...\NuGetFallbackFolder\...\dotnet-ef.runtimeconfig.json' is denied

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#7034]
(Copied from internal bug 456961)

## Steps to reproduce
1. File > New Project > ASP.NET Core Web Application (.NET Core) > Web App(Ind Auth) - 2.0.
2. In Solution Explorer, right click the Models folder > Add > Class. Name the class Movie and add the following properties and build.
    ```C#
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set;}
        public decimal Price { get; set; }
    }
    ```
3. Right-click the Controllers folder > Add > Controller, in the Add Scaffold dialog, tap MVC Controller with views, using Entity Framework > Add.
4. Complete the Add Controller dialog.
Model class: Movie(MvcMovie.Models - your namespace)
Data context class: ApplicationDbContext
Views: Keep the default of each option checked
Controller name: Keep the default MoviesController
Tap Add
5. Open Package Manager Console (PMC).
6. Type "Add-Migration AddMovies", it occurs error "The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable".
    ![image](https://user-images.githubusercontent.com/1226749/27706931-4c29ea8c-5cc8-11e7-8ec8-25b1e8908b02.png)
7. Right click the project and click 'Open Folder in File Explorer'. 
8. Run open up a normal Command Prompt.
9. Run cd <project directory> normal to the project directory(eg: cd C:\Users\fwtlaba\source\repos\WebApplication11\WebApplication11).
10. Run following command in the Command Prompt, you get the error:
    ```
    dotnet ef migrations add AddMovies
    ```
    Error Message:
    System.UnauthorizedAccessException: Access to the path 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.entityframeworkcore.tools.dotnet\2.0.0-preview2-final\lib\netcoreapp2.0\dotnet-ef.runtimeconfig.json' is denied.
    ![image](https://user-images.githubusercontent.com/1226749/27706944-64dfd898-5cc8-11e7-9058-f7c7333374ac.png)

## Environment data
Win 10 x64 (RS2 Version 1703) ENU OS
Dev15.3 VSE d15prerel 26626.03
CLI 2.0 RTW [x64 machine] - 2.0.0.6597
Additional NuGet feed: https://dotnet.myget.org/f/dotnet-core/api/v3/index.json

**Comment by bricelam** [comment]
(Copied from comment on internal bug)

Not repro in Dev15.3 Preview 3 + CLI 2.0 Preview 2(2.0.0.6497).
Also repro with  ASP.NET Core Web Application (.NET Core) > Web App(No Auth) - 2.0.

**Comment by livarcocc** [comment]
@bricelam this is weird. we have no read access to that folder? Or are you trying to write to that folder?

**Comment by livarcocc** [comment]
It seems like we are using the wrong constructor when creating the FileStream to read the runtimeconfig.json.

We should try with 

```
public FileStream(
	string path,
	FileMode mode,
	FileAccess access
)
```

**Comment by ajcvickers** [comment]
According to VS testing, this issue is not fixed. It maybe that the fix hasn't flowed through everywhere yet, but I can't see any evidence that this is the case. I assigned the VSO bug to @livarcocc and I am re-opening this issue as well so we can try to figure out what the disconnect is between this issue being fixed and what is getting tested not being fixed.

**Comment by livarcocc** [comment]
What version of the CLI are you using that is still reproing this? Are you doing anything else differently?

**Comment by ajcvickers** [comment]
@livarcocc It's not really me or our team at all--it's the VS testing from @barrytang's team. It would be best to communicate directly with them as to what versions they are using for their testing. (I was not able to repro this when I tried, but according to their reactivation they still can.)

**Comment by livarcocc** [comment]
The issue that has been re-activated is now failing with:
```
Type "Add-Migration AddMovies", it occurs error "The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable", see screenshot1.
```
In that case, the CLI is not in the picture, so I am not sure why we are tracking this in the CLI.
