### ISSUE TITLE
Installer doesn't finish at the end of the install

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7037]
Copied from https://github.com/dotnet/core/issues/721

Thanks for your interest in .NET Core.

Please note that this repo (dotnet/core) is not for filing product issues. Here are some repos where you can file an issue:

dotnet/cli - for CLI tools and questions
dotnet/corefx - for API issues and questions
dotnet/coreclr - for runtime issues
nuget/home - for NuGet questions and issues
Just an FYI as I'm rolling out .NET 2.0 Core Preview 2 on my other Linux demo systems. I notice at the end of the installation it really doesn't end unless you press Enter.

At least it does install and works. But, there's something else happening at the end.

Linux OS: Ubuntu 16.04.2

(See Image)
![dotnet2_wait](https://user-images.githubusercontent.com/19892435/27716376-e9e98280-5d0b-11e7-9149-7ed7fc8e1373.png)

![dotnet2_enter](https://user-images.githubusercontent.com/19892435/27716459-8b7f3cac-5d0c-11e7-9118-9b2e87c9289f.png)

**Comment by Petermarcu** [comment]
@MaximoTrinidad

**Comment by wli3** [comment]
@MaximoTrinidad what is behavior that you did not expect?

1. Having the message print out that doesn't look like installation?
2. The wait after installation? One of the process is priming the cache. This used to be at the first time the user use dotnet command.
3. Need to press something or it won't proceed? It should not happen, I am checking that. Also, your terminal doesn't look like the one from default Ubuntu unity, what is the image you are using? Ubuntu GNOME?

**Comment by wli3** [comment]
@MaximoTrinidad Now I see, there is no clear message saying the installer are doing at the end of the process which Windows and Mac installer has today. The wait is necessary, but the experience is confusing

![deb-install](https://user-images.githubusercontent.com/6993335/27747227-2d6ea788-5d7f-11e7-971e-166c1a60fbcc.gif)
