### ISSUE TITLE
Add option for installing prerelease packages to dotnet add package

### ISSUE THREAD

**Issue by svick** [dotnet/cli#7043]
Currently, when I want to add a prerelease package to a project, I have to explicitly specify its version. For example: `dotnet add package System.Memory` does not work, but `dotnet add package System.Memory -v 4.4.0-preview2-25405-01` does.

This is inconvenient when I want to install the latest version of the package, even if it's prerelease. So I propose that a new `--prerelease` option should be added to `dotnet add package`, which would allow installing prerelease packages without having to explicitly specify package version.

This is similar the the `-IncludePrerelease` option to `Install-Package`.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5517

**Comment by MuiBienCarlota** [comment]
@livarcocc Why did you moved this to nuget? It's only a need of evolution of dotnet cli.

**Comment by MuiBienCarlota** [comment]
After 2 years, this issue should be re openned and handled.

**Comment by livarcocc** [comment]
This is moved to NuGet because the add package code is owned by NuGet, even though it runs through the CLI. Moving it to NuGet makes it easier for that team to see and respond to it.
