### ISSUE TITLE
Execute targets building with dotnet cli

### ISSUE THREAD

**Issue by jdnichollsc** [dotnet/cli#7058]
Hi friends, I can't trigger my building targets using the dotnet cli.

## Steps to reproduce
Execute the following command: 
`dotnet build ./project.json --build-profile --no-incremental`

## Expected  behavior
Execute my following targets with the cli:
```
<Target Name="MyPreCompileTarget" BeforeTargets="Build">
  <Exec Command="npm install" />
</Target>
<Target Name="MyPostCompileTarget" AfterTargets="Build">
  <Exec Command="gulp default" />
</Target>
```

## Actual behavior
The targets doesn't works building with the cli, only with Visual Studio.

## Environment data
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```
Please, include more examples working with *Gulp*! 👍 

Thanks in advance, Nicholls

**Comment by wli3** [comment]
Hi @jdnichollsc The version you are using is pretty old. It is still project json based and it is preview for 1.0.(we just released preview 2 for 2.0 😄  ) And could you give me an minimal version of project you are using? It is project json based, however you are also invoking an msbuild target, I don't know how the target is configured to the project json file.

**Comment by jdnichollsc** [comment]
Hi @wli3, thanks for your quickly response! 
Let me send it to you  later, I would like to know the way to work with Gulp using the last stable version with TeamCity, exist any example? 
Thanks in avance, Nicholls

**Comment by jdnichollsc** [comment]
Fixed with the last version of **.NET Core** using **Visual Studio 2017**.
