### ISSUE TITLE
Using NuGet repository with password encription - Not Supporte on non-Windows Platforms

### ISSUE THREAD

**Issue by aleslash** [dotnet/cli#7062]
## Steps to reproduce
Use local nuget repository that demands password encription
My nuget.config works fine in Windows environment, but on linux OS it doesn't.

## Expected  behavior
Successfully connect with local Nuget repository.

## Actual behavior
  Restoring packages for /opt/apl/testeDotnet/testeDotnet.csproj...
  Retrying 'FindPackagesByIdAsyncCore' for source 'http://<removed>/api/nuget/nuget-remote/FindPackagesById()?id='Microsoft.NETCore.App''.
  Password decryption is not supported on .NET Core for this platform. The following feed uses an encrypted password: 'Artifactory'. You can use a clear text password as a workaround.
    Encryption is not supported on non-Windows platforms.
  Retrying 'FindPackagesByIdAsyncCore' for source 'http:// <removed>/api/nuget/nuget-remote/FindPackagesById()?id='Microsoft.NETCore.App''.
  Password decryption is not supported on .NET Core for this platform. The following feed uses an encrypted password: 'Artifactory'. You can use a clear text password as a workaround.
    Encryption is not supported on non-Windows platforms.
/opt/apl/dotnet/sdk/1.0.4/NuGet.targets(97,5): error : Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'http:// <removed>/api/nuget/nuget-remote/FindPackagesById()?id='Microsoft.NETCore.App''. [/opt/apl/testeDotnet/testeDotnet.csproj]
/opt/apl/dotnet/sdk/1.0.4/NuGet.targets(97,5): error :   Password decryption is not supported on .NET Core for this platform. The following feed uses an encrypted password: 'Artifactory'. You can use a clear text password as a workaround. [/opt/apl/testeDotnet/testeDotnet.csproj]
/opt/apl/dotnet/sdk/1.0.4/NuGet.targets(97,5): error :   Encryption is not supported on non-Windows platforms. [/opt/apl/testeDotnet/testeDotnet.csproj]

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     rhel
 OS Version:  7.2
 OS Platform: Linux
 RID:         rhel.7.2-x64
 Base Path:   /opt/apl/dotnet/sdk/1.0.4

In our case the IT Security Policy cannot be changed, so we must use encripted password.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5526
