### ISSUE TITLE
build issue: dotnet-install points to nonexistent file on azureedget.net on Linux build

### ISSUE THREAD

**Issue by atsushieno** [dotnet/cli#7070]
## Steps to reproduce

Check out the repository and run build.sh.

## Expected  behavior

It should build out of the box.

## Actual behavior

	/sources/dotnet/cli$ ./build.sh 
	+ /sources/dotnet/cli/scripts/obtain/dotnet-install.sh --channel release/2.0.0 --install-dir /sources/dotnet/cli/.dotnet_stage0/x64 --architecture x64 --version 2.0.0-preview3-006628
	dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006628/dotnet-sdk-2.0.0-preview3-006628-linux-x64.tar.gz
	dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006628/dotnet-sdk-2.0.0-preview3-006628-linux-x64.tar.gz
	dotnet-install: Adding to current process PATH: `/sources/dotnet/cli/.dotnet_stage0/x64`. Note: This change will be visible only when sourcing script.
	dotnet-install: Installation finished successfully.
	+ /sources/dotnet/cli/scripts/obtain/dotnet-install.sh --channel master --install-dir /sources/dotnet/cli/.dotnet_stage0PJ/x64 --architecture x64 --version 1.0.0-preview2-1-003177
	dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz
	curl: (22) The requested URL returned error: 404 Not Found
	dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz

	gzip: stdin: unexpected end of file
	tar: Child returned status 1
	tar: Error is not recoverable: exiting now

## Environment data

This issue is about build, not about the installed `dotnet`, but anyways...

/sources/dotnet/cli$ dotnet --info
	.NET Command Line Tools (2.0.0-preview1-005977)

	Product Information:
	 Version:            2.0.0-preview1-005977
	 Commit SHA-1 hash:  414cab8a0b

	Runtime Environment:
	 OS Name:     ubuntu
	 OS Version:  17.04
	 OS Platform: Linux
	 RID:         ubuntu.16.10-x64
	 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

	Microsoft .NET Core Shared Framework Host

	  Version  : 2.0.0-preview2-25407-01
	  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by rizamarhaban** [comment]
Just adding, I got this error from the log when deploying to Azure App Service.

    It was not possible to find any compatible framework version
    The specified framework 'Microsoft.NETCore.App', version '2.0.0-preview2-25407-01' was not found.

      - Check application dependencies and target a framework version installed at:
      \
      - Alternatively, install the framework version '2.0.0-preview2-25407-01'.

Anyway how to resolve this? I believe it was okay previously.

**Comment by livarcocc** [comment]
These are two separate issues.

@atsushieno the 404 is a false alarm. The scripts first try to find the artifact from one location (fails with 404) and it falls back to another location. The issue you saw seems to be some issue with the downloaded file, since tar failed to complete. Did you retry?

@rizamarhaban I believe the preview2 release is still being rolled out to Azure. So, you can either install that shared runtime in your azure VM in order to use it, or publish you app as a self-contained app.

I am going to close this issue since I don't think the original issue reported here really points to a broken install script. If you manage to find a consistent repro that indicates a failure with the script, please re-activate.

**Comment by atsushieno** [comment]
Read the error log agin? There is no fallback downloads afterwards and it seems trying to extract the archive which is nonexistent. No downloads happened. To make sure, here is the simple execution log with `time`:

	/sources/dotnet/cli$ time ./build.sh 
	+ /sources/dotnet/cli/scripts/obtain/dotnet-install.sh --channel release/2.0.0 --install-dir /sources/dotnet/cli/.dotnet_stage0/x64 --architecture x64
	 is already installed.DK version 2.0.0-preview3-006670
	dotnet-install: Adding to current process PATH: `/sources/dotnet/cli/.dotnet_stage0/x64`. Note: This change will be visible only when sourcing script.
	dotnet-install: Installation finished successfully.
	+ /sources/dotnet/cli/scripts/obtain/dotnet-install.sh --channel master --install-dir /sources/dotnet/cli/.dotnet_stage0PJ/x64 --architecture x64 --version 1.0.0-preview2-1-003177
	dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz
	curl: (22) The requested URL returned error: 404 Not Found
	dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz

	gzip: stdin: unexpected end of file
	tar: Child returned status 1
	tar: Error is not recoverable: exiting now

	real	0m1.892s
	user	0m0.124s
	sys	0m0.048s
	/sources/dotnet/cli$ 

No fallback download can handle complete within 2msec.

**Comment by atsushieno** [comment]
It is a real issue that needs to be resolved otherwise the entire .NET things cannot be cross platform anymore because this script is used quite everywhere.

**Comment by vellozzi** [comment]
@atsushieno, did you find a solution to this?  I'm running across the same thing when I build the CLI on Linux.

**Comment by livarcocc** [comment]
Strange, that's how all our builds are done. Our CI simply invokes build.sh. Is that URL reachable from inside the Linux box?

**Comment by vellozzi** [comment]
I'm building on Amazon Linux.  It builds the URL of the download with the RID.  The RID is calculated from values in /etc/os-release.  There's no official build for For Amazon Linux so the resulting URL doesn't exist.
I'll have to find a way to override that value so that it will download the rhel version instead, since I know that works.

**Comment by livarcocc** [comment]
I see. We are also looking into removing the dependency of the CLI on the project.json CLI. We only use it for migration tests and we have a reduced number of them now.

**Comment by vellozzi** [comment]
That will be good.  Until then I'll patch my up the build scripts.  It will be nice once that's gone.

Thanks for the help.

**Comment by atsushieno** [comment]
@vellozzi sadly no, I simply dumped the idea to use dotnet (because this is ignored and the issue does not look to be fixed anytime soon). There'd be some hint at https://github.com/dotnet/cli/pull/7071 .

**Comment by atsushieno** [comment]
Finally there is a usable dotnetcli package to fix build issue. This revision, 2.1.0-preview1-007012, can be used as a build dependency. Changes are https://gist.github.com/atsushieno/b4d52943b8c546b30a8206d553c36e49

**Comment by sstevenkang** [comment]
This is still an issue in v2.1.4 tag.  We have a work around, but would like this to be resolved.
