### ISSUE TITLE
Unable to get JITDisasm with dotnet-run

### ISSUE THREAD

**Issue by am11** [dotnet/cli#7072]
## Description

The CLR configuration knobs documentation suggests that if we set the environment variables, the knobs variables set by the environment shall be abided.

https://github.com/dotnet/coreclr/blob/38a2a69/Documentation/project-docs/clr-configuration-knobs.md

This holds if we build CoreCLR and run the app via corerun, but not when running with dotnet.exe/corehost.exe.

## Steps to reproduce

```powershell
# powershell
mkdir inspectjit
cd inspectjit
dotnet new console

# set env var as per the documentation
$env:COMPLUS_JitDisasm="Main"

dotnet restore
dotnet run
```

## Expected  behavior

Dumps the disassembly for method `Main` on stdout as per the documentation.

Seems like corehost or CLI are clearing output emitted by CoreCLR.

## Actual behavior

Only `Hello World!` is emitted on stdout.

## Environment data
`dotnet --info` output:

```powershell
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2794
