### ISSUE TITLE
Project reference version when packing project

### ISSUE THREAD

**Issue by danielwertheim** [dotnet/cli#7079]
I have a solution with two projects **A** and **B** where **B depends on A** as a project reference.

I've tried packing the csprojs using `dotnet pack` and `msbuild` with target "Pack" passing version. This works fine, how-ever, what I want is to set the passed version on the project reference to A from B. How do I do this? The result should be A.1.0.0.nupkg and B.1.0.0.nupkg where B -> A with fixed version 1.0.0

Previously (.NET classic) and using NuGet to pack with NuSpec, you could inject the `$version` to the dependency. Is that the way I have to go now as well? Using a NuSpec file?

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5540
