### ISSUE TITLE
Dotnet restore fails on project which references another project from the same folder.

### ISSUE THREAD

**Issue by lyuboasenov** [dotnet/cli#7083]
## Steps to reproduce
Have two csproj in the same folder. One of them (projA) references the other (projB).

## Expected  behavior
Expect restore to be run for both project projA and projB

## Actual behavior
When I run dotnet restore projA.csproj restoring is run only for projB.
When I run dotnet restore projA.csproj --no-dependencies restore is run for projA

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\dotnet\dotnet-2.0.0-preview2-006497\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5544
