### ISSUE TITLE
Generating strongly typed resource files not currently supported on .NET Core MSBuild 

### ISSUE THREAD

**Issue by iSazonov** [dotnet/cli#7084]
What is a right repo to ask about ResGen in `dotnet build`?

Currently I try to generate strongly typed resources and get error:
```C:\Users\user\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview2-006502\Microsoft.Common.CurrentVersion.targets(2921,5): error : Generating strongly typed resource files not currently supported on .NET Core MSBuild [C:\Users\user\Documents\GitHub\iSazonov\PowerShell\src\Microsoft.PowerShell.CoreCLR.Eventing\Microsoft.PowerShell.CoreCLR.Eventing.csproj]```

From related Issue https://github.com/dotnet/cli/issues/819:
> dotnet-resgen  got replaced by the  Microsoft.Net.Sdk  implementation, so closing this.

Is strongly typed resources supported?

**Comment by wli3** [comment]
Hi iSazonov,
Could you try to add resx files like this? https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/TestAssets/TestProjects/KitchenSink/TestApp/TestApp.csproj#L24
(This is a part of SDK automatic test asset)

**Comment by iSazonov** [comment]
@wli3 Thanks! Please clarify - I don't see strongly typed config in the csproj.

**Comment by wli3** [comment]
Hi @iSazonov ,
I think I misunderstood you. Looks like your project are from Github, could you share the specific strongly typed config code link?

**Comment by iSazonov** [comment]
@wli3 I'll publish the sample tomorrow from my local branch.

**Comment by iSazonov** [comment]
I published my test. See last <ItemGroup> in  https://github.com/iSazonov/PowerShell/blob/cproj-psversion-from-git-resx/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj

Build command:
```
dotnet msbuild /t:"ResGen" /v:diag /noconsolelogger /fileLogger .\Microsoft.PowerShell.CoreCLR.Eventing.cspro
j
or
dotnet build /t:"ResGen" /v:diag /noconsolelogger /fileLogger .\Microsoft.PowerShell.CoreCLR.Eventing.csproj
```

**Comment by livarcocc** [comment]
I am moving this issue over to MSBuild. FYI @rainersigwald

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/msbuild#2272
