### ISSUE TITLE
'dotnet build' ignores folder structure when copying .shproj content to output [preview2]

### ISSUE THREAD

**Issue by SomeAnon42** [dotnet/cli#7092]
## Steps to reproduce
1. Create a shared project using VS.
2. Inside the project, create a new folder.
3. Place an existing file into that folder, set `Build Action` to `Content` and `Copy to Output Directory` to `Copy if newer`.
4. Create a .NET Core 2.0 project, either using VS or the CLI. Add a reference to the shared project:
 `<Import Project="..\shared\shared.projitems" Label="Shared" />`
5. Build.

## Expected  behavior
The folder structure is preserved. This is how `dotnet build` used to behave.
![preview1](https://user-images.githubusercontent.com/6377116/27933759-6bb3198a-62ab-11e7-80b6-6d1cf4751f5c.png)

## Actual behavior
All the content is placed in the root folder. That's the behavior in 2.0.0-preview2-006497.
![preview2](https://user-images.githubusercontent.com/6377116/27933856-bf2c3d26-62ab-11e7-9cfd-9ffd5df801fe.png)

## Environment data
```
Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by livarcocc** [comment]
@dsplaisted This may be related to your Links change. Can you take a look?

**Comment by dsplaisted** [comment]
Fixed with https://github.com/dotnet/sdk/pull/1432
