### ISSUE TITLE
Publish skips native artifacts from project references

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#710]
cc @victorhurdugaci @divega

Using `dotnet publish` on a project that references another project with native artifacts (e.g. `runtimes/win-x64/native/sqlite3.dll`) does not copy the native artifacts to the publish directory. If I change the reference from a project to a package (by temporarily removing the `project.json` of the dependency) the native artifacts are published.

**Comment by muratg** [comment]
@davidfowl @danroth27

**Comment by piotrpMSFT** [comment]
@davidfowl you wanted to provide design notes on this one.

**Comment by danroth27** [comment]
We are now working around this issue for Kestrel and SQLite using the scripts sections to copy the native binaries as needed.

**Comment by xanather** [comment]
I got this problem too... Pretty important issue if we want to allow third-party managed libraries which make use of native libraries (while directly referencing the source code of said project instead of a package).

**Comment by andschwa** [comment]
@bricelam I've been and I can't find any info on this, but it sounds like you might know. How do you add a native library as an artifact of a CLI project? I have a Linux native library built with CMake, and right now just copy it to the publish folder in a script. Is there a way to build and publish it automatically for certain runtimes via CLI?

**Comment by moozzyk** [comment]
@andschwa - even though I wrote this with dnx in mind I think most of [this](http://blog.3d-logic.com/2015/11/10/using-native-libraries-in-asp-net-5/) still applies (except for Mono). You can also take a look at the [Kestrel package](https://github.com/aspnet/KestrelHttpServer).

**Comment by andschwa** [comment]
@moozzyk Awesome, great resource. Thank you. I've been having quite the time with `project.json` files and CLI... we need more documentation. Cheers :wine_glass:

**Comment by piotrpMSFT** [comment]
@davidfowl mentioned that @pakrym has a spec for this issue. If that is shared, we can find someone to implement...

**Comment by davidfowl** [comment]
https://gist.github.com/pakrym/d9262e46a1d780ce9652

**Comment by dagood** [comment]
The PR I linked to this from doesn't really seem to be this issue--I missed this part from the description:

> If I change the reference from a project to a package (by temporarily removing the project.json of the dependency) the native artifacts are published.

In that PR the reference was already a package reference and doesn't publish native artifacts. (Although there may be more conditions.) @ericstj and I are investigating further into what we're seeing.

**Comment by ericstj** [comment]
The issue we are hitting is different, filed here: https://github.com/dotnet/cli/issues/1528

**Comment by davidfowl** [comment]
This isn't happening for 1.0 /cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
