### ISSUE TITLE
dotnet build of aspnet core on net461 with net461 dependencies don't build

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#7105]
## Steps to reproduce

Create new project in VS
- ASP.NET Core .NET Framework Project
- .NET Framework class library child project
- Reference class lib from web proj
- Add "var foo = new Class1();" and appropriate using to Home controller.
- dotnet run in web project from CLI.

## Expected  behavior

- successful build and run

## Actual behavior

```console
C:\Users\rich\Documents\Visual Studio 2017\Projects\WebApplication3\WebApplication3>dotnet build
Microsoft (R) Build Engine version 15.3.388.41745 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Controllers\HomeController.cs(8,7): error CS0246: The type or namespace name 'ClassLibrary1' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rich\Documents\Visual Studio 2017\Projects\WebApplication3\WebApplication3\WebApplication3.csproj]

Build FAILED.

Controllers\HomeController.cs(8,7): error CS0246: The type or namespace name 'ClassLibrary1' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\rich\Documents\Visual Studio 2017\Projects\WebApplication3\WebApplication3\WebApplication3.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.04
```

Then build wen project in VS 2017 15.3
Then `dotnet run` and everything works.

## Environment data
`dotnet --info` output:

C:\Users\rich\Documents\Visual Studio 2017\Projects\WebApplication3\WebApplication3>dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by livarcocc** [comment]
Are all these SDK based projects?

**Comment by livarcocc** [comment]
@richlander I am closing this since you mentioned that this reproed in one machine but not another and you said you were going to provide a repro repo. When that's available, please re-activate.

**Comment by richlander** [comment]
I just tried on my work machine. I could not repro. I will have to try again at home (where I consistently saw this).

**Comment by richlander** [comment]
[WebApplication8.zip](https://github.com/dotnet/cli/files/1140870/WebApplication8.zip)

I forgot the steps I used before. I remembered them now. Try `dotnet build` from WebApplication8\WebApplication8.

**Comment by livarcocc** [comment]
@richlander, your solution does not contain the ClassLibrary1 project in it. But more importantly, the
 web project has no ProjectReference to it either:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <UserSecretsId>aspnet-WebApplication8-08ACDA49-C3C2-4FFB-9CC9-A04BDD6C3551</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.0-preview2-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0-preview2-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-final" />
  </ItemGroup>

</Project>
```

Once I added the `ProjectReference`, it works:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <UserSecretsId>aspnet-WebApplication8-08ACDA49-C3C2-4FFB-9CC9-A04BDD6C3551</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="2.0.0-preview2-final" PrivateAssets="All" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.0-preview2-final" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="2.0.0-preview2-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0-preview2-final" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
  </ItemGroup>

</Project>
```

Were you expecting this to work without the ProjectReference or was this just a misunderstanding? Please, re-activate if I got this wrong.

**Comment by richlander** [comment]
I see the problem now. VS isn't saving my changes to disk until I build. That's why the project file doesn't have the ritht info.

![image](https://user-images.githubusercontent.com/2608468/28140107-c9f0fcd8-670b-11e7-9f2a-a9da05abc298.png)

**Comment by livarcocc** [comment]
@richlander as we talked, this is an issue with how often VS saves the project file. If we need to change this, we should start with the project-system repo.
