### ISSUE TITLE
Output folder for compile/build should include the RID

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#711]
Because the host is RID specific and so is the output.

```
/bin/dnxcore50/osx.10.10-x64
```

**Comment by livarcocc** [comment]
@davidfowl @piotrpMSFT Should we only add it if it has the emitEntryPoint: true? Does it make sense to include the rid for libraries?

**Comment by davidfowl** [comment]
That's correct. It only makes sense for applications

**Comment by piotrpMSFT** [comment]
What about lobs with native dependencies?

**Comment by davidfowl** [comment]
Different story. We aztuaklt designed something for this today and it's extremely touchy. Wil write something up about that.

**Comment by piotrpMSFT** [comment]
*libs

**Comment by livarcocc** [comment]
/cc @davidfowl @piotrpMSFT can we get the ball rolling on this bug? I am trying to validate the behavior regarding rid in the output path. Can you guys check the table below and tell me what you think?

![image](https://cloud.githubusercontent.com/assets/367554/12670020/d8ba6360-c619-11e5-8d93-1bd7b4ea3493.png)

**Comment by GuardRex** [comment]
Excellent table! When the dust settles on everything, please add a table just like that to the docs.

**Comment by davidfowl** [comment]
Spoke to @livarcocc and @pakrym offline and this is the working spec:

https://gist.github.com/davidfowl/9931f6b9caa69b3b91dd

**Comment by livarcocc** [comment]
This has been done for a while now.

**Comment by GuardRex** [comment]
@blackdwarf I just wanted to mention again that the @livarcocc table ^^ is solid gold. idk where it would fit in best ... maybe https://dotnet.github.io/docs/core-concepts/rid-catalog.html, but I hope you'll have something like that in the CLI docs for reference.
