### ISSUE TITLE
Permission Denied error

### ISSUE THREAD

**Issue by dansiegel** [dotnet/cli#7119]
## Steps to reproduce
```
Dans-MacBook-Air:Demo1 dansiegel$ dotnet --version
2.1.0-preview1-006723
Dans-MacBook-Air:Demo1 dansiegel$ dotnet new
Access to the path '/Users/dansiegel/.templateengine/dotnetcli/v2.1.0-preview1-006723/en-US.templatecache.json' is denied.
Permission denied
```

## Expected  behavior
I should be able to access dotnet new from the cli.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.0-preview1-006723)

Product Information:
 Version:            2.1.0-preview1-006723
 Commit SHA-1 hash:  7e1fe7eba7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-006723/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25502-01
  Build    : bd3f818bad84f1296b4ee53f72ab8837b3caac98
```

**Comment by livarcocc** [comment]
How did you install the CLI? Pkg installer or tar.gz?

**Comment by livarcocc** [comment]
Actually, I know now how this happened. You used the pkg, and in the pkg we were invoking dotnet new with the root user, which was causing this file to get permissions for the root user. We are no longer invoking dotnet new as part of the installer, so, in the latest builds, this should not be a problem.

Please, re-activate if you can repro this in the latest build.

**Comment by dansiegel** [comment]
Yes this was with the pkg installer. It's also with the current build. If this is supposed to be fixed when will there be an updated build available that fixes it?

**Comment by livarcocc** [comment]
We had two legs of our CI fail, which is why we don't have a build out yet. I kicked them off again and I am monitoring, so we should have one soon.

Also, you are working on master (which is our next, next release). If you want to work on 2.0, just take a build out of release/2.0.0.

**Comment by dansiegel** [comment]
Really I was hoping to have the fix in dotnet/templating#1040. I had figured the latest build would have included that. If you suggest I try another version I'm certainly happy to do that

**Comment by dansiegel** [comment]
the problem still exists in the latest build using the pkg installer:

```
.NET Command Line Tools (2.1.0-preview1-006734)

Product Information:
 Version:            2.1.0-preview1-006734
 Commit SHA-1 hash:  5a37290f24

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.0-preview1-006734/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25507-02
  Build    : cb31faee171130d052245748e11e96b27fd8d00c
```

**Comment by livarcocc** [comment]
@mlorbetske can you take a look at this? The error message is access denied, but the file doesn't actually exists on disk. The directory is getting created as belonging to root, but it is not clear to me why. We are no longer running dotnet new as part of the installer, instead we are running our own internal command whose one of its purposes is to prime the offline cache.

**Comment by livarcocc** [comment]
Actually, @mlorbetske ignore this. I noticed now that we are not using the new command on all native installers yet.

**Comment by livarcocc** [comment]
@wli3 we need port the internal-reportinstallsuccess command to the other native installers. Without this change, the CLI installed through native installers is going to fail during dotnet new.

**Comment by julielerman** [comment]
I'm hitting this. I had the problem with 2.0.0-preview3-6694, then just updated to 6736 and still getting it.
I was able to SUDO dotnet new but then I couldn't save changes to any of the files.
Also mac.
So it DOES look like you have a fix merged in. What version should I be looking for? Thanks

**Comment by wli3** [comment]
Hi @julielerman this fix is in 6736, however, since you mentioned update, you need to remove the previous _.templateengine_ folder that is having the wrong permission

``` shell
cd ~
#carefull!!!
sudo rm -rf .templateengine/
```
 
or you can change the permission of the folder to user because the root cause of the problem is the folder is created by root incorrectly

**Comment by wli3** [comment]
also 6736 is not "coherence", you will need https://github.com/dotnet/cli/issues/6581 to walkaround. The latest coherence build don't have the fix yet

**Comment by julielerman** [comment]
Thanks. I forgot to return to say that rm rf'ig templateengine sorted me out. :)
