### ISSUE TITLE
Update License: field for SDK debs and rpms

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#7120]
The License: field for RPM and Deb packages must represent all applicable licenses for binaries contained within the packages. License: field should be `MIT and ASL 2.0 and BSD`

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines

[core-setup/issues/2586](https://github.com/dotnet/core-setup/issues/2586)

/cc @livarcocc

**Comment by richlander** [comment]
Should be MIT.
