### ISSUE TITLE
Can not find compilation library location for package '<project-name>'

### ISSUE THREAD

**Issue by snebjorn** [dotnet/cli#7132]
## Steps to reproduce
> PS C:\Users\XXX\Documents\Repos> dotnet new mvc -o asdf
> PS C:\Users\XXX\Documents\Repos> cd .\asdf\
> PS C:\Users\XXX\Documents\Repos\asdf> dotnet restore
> PS C:\Users\XXX\Documents\Repos\asdf> dotnet run
> Open http://localhost:5000 in a browser

## Expected  behavior
It should open the site.

## Actual behavior
This exception is thrown when opening http://localhost:5000 in a browser.

> PS C:\Users\XXX\Documents\Repos\asdf> dotnet run
> Hosting environment: Production
> Content root path: C:\Users\XXX\Documents\Repos\asdf
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
>       An unhandled exception has occurred: Can not find compilation library location for package 'asdf' System.InvalidOperationException: Can not find compilation library location for package 'asdf'
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>    at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
>    at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
>    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
>    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
>    at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext() fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
>       An exception was thrown attempting to execute the error handler.
> System.InvalidOperationException: Can not find compilation library location for package 'asdf'
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>    at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
>    at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
>    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
>    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
>    at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean&
> isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext() fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HL68VBSD66VC": An unhandled exception was thrown by the application.
> System.InvalidOperationException: Can not find compilation library location for package 'asdf'
>    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
>    at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
>    at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
>    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
>    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
>    at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
>    at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
>    at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

## Environment data

> PS C:\Users\XXX\Documents\Repos\asdf> dotnet --info
> .NET Command Line Tools (1.0.4)
> 
> Product Information:
>  Version:            1.0.4
>  Commit SHA-1 hash:  af1e6684fd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## More weird stuff
If I try to build the project again I get this error

> PS C:\Users\XXX\Documents\Repos\asdf> dotnet build
> Microsoft (R) Build Engine version 15.1.1012.6693
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> CSC : error CS2012: Cannot open 'C:\Users\XXX\Documents\Repos\asdf\obj\Debug\netcoreapp1.1\asdf.dll' for writing -- 'Access to the path 'C:\Users\XXX\Documents\Repos\asdf\obj\Debug\netcoreapp1.1\asdf.dll' is denied.' [C:\Users\XXX\Documents\Repos\asdf\asdf.csproj]
> 
> Build FAILED.
> 
> CSC : error CS2012: Cannot open 'C:\Users\XXX\Documents\Repos\asdf\obj\Debug\netcoreapp1.1\asdf.dll' for writing -- 'Access to the path 'C:\Users\XXX\Documents\Repos\asdf\obj\Debug\netcoreapp1.1\asdf.dll' is denied.' [C:\Users\XXX\Documents\Repos\asdf\asdf.csproj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:03.08

If I try to build it again (the 3rd time) I get a different error, and this one is shown for all future builds
> PS C:\Users\XXX\Documents\Repos\asdf> dotnet build
> Microsoft (R) Build Engine version 15.1.1012.6693
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> C:\Program Files\dotnet\sdk\1.0.4\Microsoft.Common.CurrentVersion.targets(3989,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp1.1\asdf.dll" to "bin\Debug\netcoreapp1.1\asdf.dll". Access to the path 'C:\Users\XXX\Documents\Repos\asdf\bin\Debug\netcoreapp1.1\asdf.dll' is denied. [C:\Users\XXX\Documents\Repos\asdf\asdf.csproj]
> 
> Build FAILED.
> 
> C:\Program Files\dotnet\sdk\1.0.4\Microsoft.Common.CurrentVersion.targets(3989,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp1.1\asdf.dll" to "bin\Debug\netcoreapp1.1\asdf.dll". Access to the path 'C:\Users\XXX\Documents\Repos\asdf\bin\Debug\netcoreapp1.1\asdf.dll' is denied. [C:\Users\XXX\Documents\Repos\asdf\asdf.csproj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:01.78

This makes no sense... I'm on an administrator account and it's inside my home folder.

## Upgrading to Preview 2
I tried upgrading to see if it makes a difference. It did. But didn't fix everything.
Here's my info

> PS C:\Users\XXX\Documents\Repos\asdf> dotnet --info
> .NET Command Line Tools (2.0.0-preview2-006497)
> 
> Product Information:
>  Version:            2.0.0-preview2-006497
>  Commit SHA-1 hash:  06a2093335
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0-preview2-25407-01
>   Build    : 40c565230930ead58a50719c0ec799df77bddee9

After I upgraded I can now build without errors.

> PS C:\Users\XXX\Documents\Repos\asdf> dotnet build
> Microsoft (R) Build Engine version 15.3.388.41745 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   asdf -> C:\Users\XXX\Documents\Repos\asdf\bin\Debug\netcoreapp1.1\asdf.dll
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:01.77

However the error when running the project is still there. That being the `ExceptionHandlerMiddleware` (see Actual behavior)

I have no idea how to troubleshoot this :(

**Comment by snebjorn** [comment]
Deleting

```
C:\Users\XXX\.dnx\
C:\Users\XXX\.dotnet\
C:\Users\XXX\.nuget\
```

Seems to have resolved the issue

**Comment by snebjorn** [comment]
Changing the target framework to `net47` causes it to break again :( with a "Access is denied" error.

csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
  </ItemGroup>
</Project>
```

Output:
> PS C:\Users\XXX\Documents\Repos\asdf> dotnet build
> Microsoft (R) Build Engine version 15.3.388.41745 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   asdf -> C:\Users\XXX\Documents\Repos\asdf\bin\Debug\net47\asdf.exe
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:03.17
> PS C:\Users\XXX\Documents\Repos\asdf> dotnet run
> System.ComponentModel.Win32Exception (0x80004005): Access is denied
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at Microsoft.DotNet.Cli.Utils.Command.Execute()
>    at Microsoft.DotNet.Tools.Run.RunCommand.Start()
>    at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)

This works fine on another machine...

**Comment by snebjorn** [comment]
So it appears that the problem is `.UseIISIntegration()`

If I change `Main` to:

```csharp
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        //.UseIISIntegration() <-------------------------- note 
        .UseStartup<Startup>()
        .Build();

    host.Run();
}
```

It works.

What a roller coaster. Now I need to find out what is wrong with my IIS.

**Comment by livarcocc** [comment]
@muratg @Eilon can you guys help triage this issue?

**Comment by snebjorn** [comment]
I tested this out on 2 different machines. MachineA had the same problem as me, the other (MachineB) didn't.

I tried all kinds of different things. Like what Core SDK was installed, what .NET targeting packs/SDKs where installed.

I was able to _break_ MachineA like this:

1. dotnet new mvc -o asdf
2. cd .\asdf
3. Change target framework to net47 (net47 targeting pack wasn't installed)
4. dotnet restore
5. dotnet run
6. Gives error with targeting pack not installed.
7. Change target framework to net462 (net462 targeting pack installed)
8. dotnet restore
9. dotnet run
10. Throws Access is denied

After this error newly generated projects all failed when targeting net462 (even on first run)

The strange part is that projects that were generated before we got the above error worked fine, and yes they've targeting net462. We even deleted bin and obj folders and rebuild them. They still worked. But the newly generated projected we couldn't fix.

We even deleted these folders, but to no avail.

> C:\Users\XXX\.dnx\
> C:\Users\XXX\.dotnet\
> C:\Users\XXX\.nuget\

MachineB I wasn't able to _break_ no matter what I tried.

Both machines have the same `dotnet --info`

> .NET Command Line Tools (1.0.4)
> 
> Product Information:
>  Version:            1.0.4
>  Commit SHA-1 hash:  af1e6684fd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.4

The ONLY difference I could find was that the machines that were _broken_ had this folder

> C:\Users\XXX\.dotnet\NuGetFallbackFolder\

Where as MachineB didn't have this folder. Perhaps it's related.

**Comment by snebjorn** [comment]
So it turns out that it was my antivirus that was blocking the .exe file and causing all sorts of trouble.
