### ISSUE TITLE
After packing pre-release NuGet packages for .NET 4.5.1, they do not resolve in NuGet

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/cli#7133]
This issue is currently a blocker for us, preventing upgrade to the new `.csproj` format. We have several NuGet packages, all with pre-release versions that exhibit this problem, but only on .NET Framework. On .NET Core, NuGet produces a warning but successfully downgrades the NuGet dependent package to the correct pre-release version.

## Steps to reproduce

Create a solution in Visual Studio 2017 Community with 2 class library projects targeting .NET Framework 4.5.1. Make one project depend on the other (that is, a `<ProjectReference>`) and in the dependency, also target .NET Standard 1.3. Set the `<PackageVersion>` to `4.0.2-alpha00004` in both projects.

Build the solution. Then from the CLI, do a `dotnet pack` on each project.

## Expected  behavior

The NuGet package that *depends upon* the other pre-release package will be generated with the *dependency* version number `4.0.2-alpha00004`.

## Actual behavior

The NuGet package that *depends upon* the other pre-release package will be generated with the *dependency* version number `4.0.2`, cutting off the pre-release version in the `.nuspec` file that is generated and packed by the `dotnet pack` command.

```xml
    <dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="BoboBrowse.Net" version="4.0.2" exclude="Build,Analyzers" />
        <dependency id="Spring.Core" version="2.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

When subsequently installing the package from a MyGet or NuGet feed on a .NET Framework project, Visual Studio (any version) gets the error `Unable to find a version of 'BoboBrowse.Net' that is compatible with 'BoboBrowse.Net.Spring 4.0.2-alpha00004 constraint: BoboBrowse.Net (>= 4.0.2)'.`

It doesn't matter if you use the Package Manger Console via command line or GUI, the result is the same, and I have not found a solution that will allow the NuGet package to be installed (other than changing the version number so it is not a pre-release, but that is not an acceptable solution).

You can see an example of the problem on [this MyGet feed](https://www.myget.org/F/bobobrowse_net/api/v2), by attempting to install the `BoboBrowse.Net.Spring` package into a .NET Framework targeted project.

You can download the packages for inspection as well:

- [BoboBrowse.Net.Spring](https://www.myget.org/feed/bobobrowse_net/package/nuget/BoboBrowse.Net.Spring/4.0.2-alpha00004)
- [BoboBrowse.Net](https://www.myget.org/F/bobobrowse_net/api/v2/package/BoboBrowse.Net/4.0.2-alpha00004)

## Environment data

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## Question

Is there a way to generate the `.nuspec` file based on the `.csproj` settings only, instead of generating the `.nuspec` file and packing in one step?

We are able to work around this in the `project.json` by overwriting these dependent version numbers with the build script. However, this is no longer possible to do with the `.csproj` format because these dependency version numbers are generated automatically.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5593
