### ISSUE TITLE
Lack of description for the dotnet.exe

### ISSUE THREAD

**Issue by Rovastar** [dotnet/cli#7134]
not sure where to post this so posting in multiple locations.

Can we have a description for the dotnet.exe (for Windows)?
Currently it just shows up in Task Manger when running with no description and just displaying the exe name "dotnet"
A more meaningful description would be useful mentioning that this is the Core version and probably the version number in there.
".NET Core runtime" or something.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2817

**Comment by Rovastar** [comment]
Apologies I was told to post it here

**Comment by livarcocc** [comment]
No worries. the dotnet.exe is produced in the dotnet/core-setup repo, which is why I moved there.
