### ISSUE TITLE
AssemblyFileVersion and AssemblyInfromationalVersion not longer set

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#714]
In DNX you could set DNX_BUILD_VERSION and it would set those attributes. In this new world, it doesn't seem to be possible anymore. Here's what gets set on the same assembly compiled with dnx and dotnet:

![untitled](https://cloud.githubusercontent.com/assets/5921642/12126504/6a31cf76-b3a6-11e5-9b87-4b10baa8385f.png)

**Comment by davidfowl** [comment]
Use `DOTNET_ASSEMBLY_FILE_VERSION`

**Comment by pakrym** [comment]
@victorhurdugaci are there any other assembly info related env variables we need support for?

**Comment by davidfowl** [comment]
@pakrym I think this is fine as it works already. Going to close this out. @victorhurdugaci if you can repro after setting those vars reopen.
