### ISSUE TITLE
CLI can only run command in root user

### ISSUE THREAD

**Issue by LGinC** [dotnet/cli#7142]
System: Ubuntu 14.04 x64
install command: sudo apt-get install dotnet-sdk-2.0.0-preview3-006729
I try to run : dotnet new console -o server
Access to the path '/home/linch/.templateengine/dotnetcli/v2.0.0-preview3-006729/zh-CN.templatecache.json' is denied.
Permission denied

and I add "sudo"

and  ....
 dotnet restore server.csproj 
/usr/share/dotnet/sdk/2.0.0-preview3-006729/NuGet.targets(429,5): error : Unable to obtain lock file access on '/tmp/NuGetScratch/lock/19ce3db22471912ecd6515fdca260ac26cad895d' for operations on '/home/linch/.nuget/NuGet/NuGet.Config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/19ce3db22471912ecd6515fdca260ac26cad895d' will allow NuGet to continue. [/home/linch/workspace/VSCode/C#/server/server.csproj]

how can I not use "sudo"?

**Comment by LGinC** [comment]
sudo dotnet restore server/

/usr/share/dotnet/sdk/2.0.0-preview3-006729/NuGet.targets(429,5): warning MSB4220: Waiting for the currently executing task "GetRestoreSettingsTask" to cancel. [/home/linch/workspace/VSCode/netcore2.0/server/server.csproj]
  Restoring packages for /home/linch/workspace/VSCode/netcore2.0/server/server.csproj...
/home/linch/workspace/VSCode/netcore2.0/server/server.csproj : error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.0.0-preview3-25510-01)
/home/linch/workspace/VSCode/netcore2.0/server/server.csproj : error NU1102:   - Found 13 version(s) in nuget.org [ Nearest version: 2.0.0-preview2-25407-01 ]
  Restore failed in 90.63 ms for /home/linch/workspace/VSCode/netcore2.0/server/server.csproj.

**Comment by livarcocc** [comment]
We have fixed already. Can you please try out the latest build of preview3?

Re-activate if this still reproes on the latest build. Make sure you delete /home/linch/.templateengine before installing the new build.
