### ISSUE TITLE
Wrong error message when file can't be found should be raised

### ISSUE THREAD

**Issue by xplicit** [dotnet/cli#7145]
If try to run `dotnet exec` on non-existing file and it shows message that the file is not managed. This wrong message is raised only on Linux, on Windows I see correct message about file not found.

## Steps to reproduce

```
dotnet exec a.dll
dotnet exec needs a managed .dll or .exe extension. The application specified was 'a.dll'
```

## Expected  behavior

message 

```
The application to execute does not exist: '{absolute path}'
```

## Actual behavior

Message:

```
dotnet exec needs a managed .dll or .exe extension. The application specified was 'a.dll'
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2828
