### ISSUE TITLE
Add file content in resources (not same behavior between VS2015 and CLI)

### ISSUE THREAD

**Issue by nathannau** [dotnet/cli#7146]
## Steps to reproduce

- Create new project.
- Add resx file
- Add text file
- Add text file reference in resx
- Display file content by resources

- Compile and execute with VS
- Remove obj and bin folder
- Compile and execute with Cli
`dotnet restore`
`dotnet build`
`dotnet run`

### File1.txt
`Hello Bug !`
### Properties/Resources.resx
```<?xml version="1.0" encoding="utf-8"?>
<root>
  ...
  <assembly alias="System.Windows.Forms" name="System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="TextFile1" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>..\TextFile1.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </data>
</root>
```

### Program.cs
```using System;
namespace BugResource {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine(Properties.Resources.TextFile1);
        }
    }
}
```

## Expected  behavior

Same result with VS2015 and Cli

## Actual behavior

VS2015 : Display file content

> Hello Bug !

dotnet cli : Display file path

> ..\TextFile1.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

To have the probleme you need to remove obj directory between VS build and Cli build 

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview1-005977\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25419-01
  Build    : 2fab74ca0ab629adfe1291e3f1b5eeae2a57c156

**Comment by livarcocc** [comment]
What do you mean by VS 2015? The CLI is actually only supported in VS2017. Could you share your csproj with us?
@rainersigwald and @jaredpar could you guys take a look as well?

**Comment by nathannau** [comment]
Sorry. I meant VS 2017 v15.3 (preview 3).

How can i share file ?

**Comment by nathannau** [comment]
[BugResource.zip](https://github.com/dotnet/cli/files/1145870/BugResource.zip)

**Comment by rainersigwald** [comment]
I believe this is https://github.com/Microsoft/msbuild/issues/308.

**Comment by dasMulli** [comment]
I had a look at sth similar recently - on full framework, MSBuild uses `ResXResourceReader` but the .NET Core build of it has a naive loop over the `<data>` elements (see [code](https://github.com/Microsoft/msbuild/blob/master/src/Tasks/GenerateResource.cs#L2888-L2915)).

Even if it supported the `type=".."` thing, using `System.Resources.ResXFileRef, System.Windows.Forms` surely wouldn't work well on core.

**Comment by livarcocc** [comment]
Closing this issue then. Though it is not clear to me if we need a new MSBuild issue or not.
