### ISSUE TITLE
dotnet-install.sh -c 2.0: Download failed HTTP 404 Not Found

### ISSUE THREAD

**Issue by couven92** [dotnet/cli#7147]
## Steps to reproduce
In `bash` on a Ubuntu 16.04 OS, attempt to install the dotnet SDK Preview 2 using the dotnet-install script
``` bash
curl -sSLOR https://dot.net/v1/dotnet-install.sh
bash dotnet-install.sh --channel 2.0
```

## Expected  behavior
Should install the dotnet 2.0 Preview SDK

## Actual behavior
Fails critically while attempting to download the SDK:
``` bash
$ curl -sSLOR https://dot.net/v1/dotnet-install.sh
$ bash dotnet-install.sh --channel 2.0
dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006497/dotnet-dev-ubuntu.16.04-x64.2.0.0-preview2-006497.tar.gz
dotnet_install: Error: Download failed
$ curl -I https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006497/dotnet-dev-ubuntu.16.04-x64.2.0.0-preview2-006497.tar.gz
HTTP/1.1 404 Not Found
Date: Thu, 13 Jul 2017 11:45:51 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: ea6e6136-0001-003a-30cd-fb2526000000
x-ms-version: 2009-09-19
Content-Length: 0
```
As shown above the URL that dotnet-install uses returns a 404 HTTP status code.

## Environment data
``` bash
$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by livarcocc** [comment]
@johnbeisner We need to update the script at dot.net. Let's do it this morning.

cc @leecow

**Comment by couven92** [comment]
@livarcocc Might I suggest to also create a https://dot.net/v2/dotnet-install.sh resource just for consistency?

**Comment by livarcocc** [comment]
We have updated the scripts in place, given that they are backwards compatible. Please, give it a shot.

If you still run into any problem, please, re-activate this issue.
