### ISSUE TITLE
dotnet run : could not find files

### ISSUE THREAD

**Issue by pquiring** [dotnet/cli#7152]
## Steps to reproduce
md test
cd test
dotnet new console
dotnet restore
dotnet run

## Expected  behavior
Builds EXE file

## Actual behavior
CSC : error CS2001: Source file 'C:\Users\pquiring\obj\Debug\netcoreapp1.1\test.AssemblyInfo.cs' could not be found. [C:\Users\pquiring\test\test.csproj]
CSC : error CS2001: Source file 'C:\Users\pquiring\Program.cs' could not be found. [C:\Users\pquiring\test\test.csproj]

The build failed. Please fix the build errors and run again.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\1.0.4

Very new to this so maybe I'm not understanding the process.  I've also tried with some of the 2.0 previews and get same errors.  Do I need VS2017 installed?

Thanks.

**Comment by pquiring** [comment]
It seems to be looking in the wrong folder for files.

**Comment by livarcocc** [comment]
No, this should work out of the box. Can you paste the contents of your csproj here? There must be something special in your system that is triggering this.

Also, if you can, can you do a `dotnet build /v:diag > log.txt` and share the log.txt file with us?

**Comment by pquiring** [comment]
test.csproj

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

</Project>

[log.txt](https://github.com/dotnet/cli/files/1146766/log.txt)

**Comment by pquiring** [comment]
Found the problem, I have some environment variables that cause it.  I'll find out which one it is and let you know.

**Comment by pquiring** [comment]
`set HOME=%USERPROFILE%`

I use this for some scripts I use but it must confuse dotnet into thinking it's running on Linux instead of Windows.
But even with all my custom environment vars removed I still have to run 'dotnet run' twice.  The first time I always get this error:
```
c:\program files\dotnet\sdk\1.0.4\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "c:\program files\dotnet\sdk\1.0.4\Roslyn\RunCsc.cmd" exited with code 1. [C:\Users\pquiring\test\test.csproj]

The build failed. Please fix the build errors and run again.

```

Thanks.

**Comment by pquiring** [comment]
I was wrong, it's something in my path that conflicts with it.

**Comment by pquiring** [comment]
I have a .bat file called cd~.bat that seems to be the culprit.  Strange.

**Comment by pquiring** [comment]
I still get one error the first time I run 'dotnet run':

```
c:\program files\dotnet\sdk\1.0.4\Roslyn\Microsoft.CSharp.Core.targets(71,5): error MSB6006: "c:\program files\dotnet\sdk\1.0.4\Roslyn\RunCsc.cmd" exited with code 1. [C:\Users\pquiring\test\test.csproj]

The build failed. Please fix the build errors and run again.

```

**Comment by livarcocc** [comment]
Please, share the build /v:diag contents for the failed case.

**Comment by pquiring** [comment]
I got it working, it was my environment.  Thanks.

**Comment by ljgww** [comment]
There is log.txt above, but not the resolution of this issue...
Where to look for solution?
