### ISSUE TITLE
Cli is not using the latest Core-Setup build

### ISSUE THREAD

**Issue by steveharter** [dotnet/cli#7157]
## Steps to reproduce
The PR to update the CLI to the latest version - https://github.com/dotnet/cli/pull/6942 is failing with `D:\j\workspace\debug_windows---8a02d2bd\build\HostInfo.targets(6,5): error MSB4018: The "GetCurrentRuntimeInformation" task failed unexpectedly. [D:\j\workspace\debug_windows---8a02d2bd\build.proj]
10:23:14 D:\j\workspace\debug_windows---8a02d2bd\build\HostInfo.targets(6,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [D:\j\workspace\debug_windows---8a02d2bd\build.proj]
`

It is attempting to use the 2.1 version of `Microsoft.DotNet.PlatformAbstractions` assembly but it was not found.

The cause appears to be that the version specified in https://github.com/dotnet/cli/blob/master/run-build.ps1#L84 and https://github.com/dotnet/cli/blob/master/run-build.sh#L158 are referencing the 2.0 version. If this is changed to 2.1 that should fix the issue, however, it appears we are not currently pushing the 2.1 builds to the CDN so there will be an error regarding not being able to find the 2.1 bits.

## Expected  behavior
CLI using the latest 2.1.0 version of Core-Setup

## Actual behavior
Still using the 2.0.0 version.

**Comment by steveharter** [comment]
@livarcocc since we discussed this issue previously
@nguerrera please take a look

**Comment by nguerrera** [comment]
This is now fixed
