### ISSUE TITLE
No line numbers on exceptions when run on Linux

### ISSUE THREAD

**Issue by KallDrexx** [dotnet/cli#716]
Sorry, not 100% sure if this is the correct repo for this, but since DNX is being obsoleted via the dotnet command I'm assuming so.

I followed the instructions from http://dotnet.github.io/getting-started/ to get the latest version of .net core on an ubuntu server box.  After restoring my application then doing `dotnet run` I get the following output:

```

Unhandled Exception: System.InvalidOperationException: No service for type 'Microsoft.Extensions.PlatformAbstractions.IApplicationEnvironment' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at MyProject.Infrastructure.Web.WebHost.Start(ServiceDescriptor[] additionalServices)
   at MyProject.Program.Main(String[] args)

````

This gives me no line numbers, even for my portion of the code.  I did a quick search but couldn't find if this was a known bug or not.

**Comment by blackdwarf** [comment]
@agocke can you take a look at this?

**Comment by agocke** [comment]
Is there a repro I can take a look at?

**Comment by KallDrexx** [comment]
Unfortunately when I tried to create a reproduction that I could make
public (that wasn't tied to our proprietary code) I encountered other
issues that blocked me from getting to that point.  I had to drop .Net Core
until things are more stable (even for a prototype) so I had to stop
working on it and get back to DNF.

**Comment by andschwa** [comment]
Wait, other platforms get line numbers? No fair! Would definitely like :pray:

**Comment by macgyver76** [comment]
I've got this same issue on Windows running ```dotnet run -f dnx46```. However ```dnx web``` works fine.

.NET CLI Version: 1.0.0-beta-001486

Here's my project.json file:
```json
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "EntityFramework.Core": "7.0.0-rc1-final",
    "EntityFramework.Relational": "7.0.0-rc1-final",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework7.Npgsql": "3.1.0-rc1-3",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef" : "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx46": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ]
}
```

**Comment by singlewind** [comment]
The same issue here. Does dotnet run support website yet? How to specify which command to run in project.json when use dotnet command

**Comment by blackdwarf** [comment]
@singlewind you don't. You just use `dotnet run` in the context of your project.

**Comment by brthor** [comment]
Have a repro here, it would be super nice to get line number on non-windows. Debugging any large function is fun :smile: 

Steps:
1. dotnet new
2. Set Program.CS as below
3. dotnet restore && dotnet run
4. see output below

**Program.cs** 
```
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            throw new Exception("I am failing");
        }
    }
}
```

**Output**
```
bryans-mbp:exc brthor$ dotnet run
Compiling exc for .NETStandard,Version=v1.5

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.1751788


Unhandled Exception: System.Exception: I am failing
   at ConsoleApplication.Program.Main(String[] args)
```

**Comment by agocke** [comment]
Seems likely to be a coreclr or corefx (depending on who generates the stack trace) issue. Does the CoreCLR stack unwinder parse Portable PDBs? That's how you would get line numbers.

**Comment by stephentoub** [comment]
That support doesn't exist yet.  And, IIRC, according to @jkotas that it produces file name / line numbers on Windows is essentially an accident based on it picking up full framework debugger components.

**Comment by agocke** [comment]
@stephentoub Yeah, I guessed so. Do you or CoreCLR have an issue tracking this? If not, do you know which project I should file on?

**Comment by stephentoub** [comment]
CoreCLR.  I'm not sure if there's an issue for it.  If you can't find one, just open one and then it can be closed as a dup if necessary.

**Comment by agocke** [comment]
@stephentoub Thanks!

I'm closing this issue as a dup of https://github.com/dotnet/coreclr/issues/3906
