### ISSUE TITLE
Beta Release Dependencies Change and Standardization

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#718]
For the beta release we will need to make changes to the dependencies in our project.jsons across the repo.

This will need to happen after the beta version of NETStandard.Library is pushed to NuGet.

1. Move all dependencies on NETStandard.Library to the beta version (Including the dotnet new template)
2. Remove NuGet.config workaround (https://github.com/dotnet/cli/issues/656)
3. Resolve any dependency conflicts presented by the MultiProjectValidator, currently we are seeing many of these. `System.Reflection.Metadata` is one such example where different versions are being used in different projects.

As a side note, conflicts presented by the MultiProjectValidator will produce a build failure in our release branch. This ensures we have no dependency stomping: 
https://github.com/dotnet/cli/issues/541

cc @piotrpMSFT @krwq @Sridhar-MS

**Comment by piotrpMSFT** [comment]
This PR will need to be retargetted to https://github.com/dotnet/cli/tree/rel/1.0.0

**Comment by joshfree** [comment]
moving to the 1.0.0-rc2 milestone

**Comment by blackdwarf** [comment]
@brthor this is done?

**Comment by brthor** [comment]
parts are done, others are obsolete, closing this out.
