### ISSUE TITLE
2.0.0-preview3-006770 puts a NuGetFallBackFolder in \dotnet\sdk?

### ISSUE THREAD

**Issue by shanselman** [dotnet/cli#7181]
## Steps to reproduce

I installed 2.0.0-preview3-006770 and now I have a NuGetFallBackFolder in \dotnet\sdk?

## Expected  behavior

Not this. ;) 

It is supposed to be in C:\Users\scott\.dotnet\NuGetFallbackFolder right?

## Actual behavior

![image](https://user-images.githubusercontent.com/2892/28295996-f9c76656-6b19-11e7-83ef-ad188667ee14.png)

## Environment data
`dotnet --info` output:

```
C:\Users\scott\Desktop\raspberrypi1>dotnet --info
.NET Command Line Tools (2.0.0-preview3-006770)

Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16241
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25514-02
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118
```

**Comment by livarcocc** [comment]
No, we have moved the offline cache under folder the dotnet hive so that in the case of native installers (global), it can be shared across the entire machine. Thus, enabling multi-user offline cache scenarios, like the ones required by VS.

**Comment by livarcocc** [comment]
It is there because it is used only by the SDKs and we didn't want to pollute the dotnet hive with more folders. We considered that kept it more localized to where it was actually going to be used.

**Comment by MaherJendoubi** [comment]
What was the previous location?
