### ISSUE TITLE
Need to add Debian 9 packages

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7184]
The runtime is going to start producing Debian 9 packages and we need SDK packages to match.

**Comment by livarcocc** [comment]
And we are doing this for 2.0? Why so late?

cc @wli3

**Comment by Petermarcu** [comment]
Because Debian 9 just released.

**Comment by Petermarcu** [comment]
Talk to @rakeshsinghranchi about how he's doing it for the runtime.

**Comment by tinxx** [comment]
Is there an ETA?

**Comment by wli3** [comment]
package made for debian 8 works on debian 9 since CLI don't have special dependency

**Comment by ffloimair** [comment]
No it doesn't.
Debian 9 uses libicu57 whereas Debian 8 (and the debian.8-x64 dotnet runtime package target) uses libicu52.
Or what are you referring to with "package made for debian 8"?

**Comment by wli3** [comment]
Hi @ffloimair, dotnet runtime does need a different dependency on Debian 9. There will be a package dotnet-runtime-X.deb (from https://github.com/dotnet/core-setup) for debian 9, however, for dotnet-sdk-X.deb package, which this repo produces, there is no special dependency other than dotnet-runtime and aspnetcore-store

**Comment by ffloimair** [comment]
OK, I see. Thanks for the clarification!
