### ISSUE TITLE
Question:  Is it possible to run "dotnet build" from a file share.

### ISSUE THREAD

**Issue by Deren-Liao** [dotnet/cli#7189]
This is a feature request or just a question. The scenario I am looking for is as following:

OS: Linux Ubuntu LTS
Identify the set of files necessary for build dot net core apps.
Check in the files to file share.
On any Linux server, I can simply mount to the file share or copy the files locally. 
Then run dotnet build from the set of .net core installation folder. 

Is it possible?  How to do it?

**Comment by ellismg** [comment]
The `dotnet-sdk.tar.gz` file should have everything you need to build .NET Core applications.  You could extract that to some share and then mount the share and add it to your `$PATH` and invoke `dotnet build`. I would expect that this would "just work".  If it doesn't please open an issue as that's something we'd want to address, I think.

If you want to play around, here's [the latest daily build](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-linux-x64.tar.gz) of what will become .NET Core 2.0, which should be run-able on Ubuntu LTS.

Note that .NET Core has some dependencies on native libraries provided the operating system, so it's possible that if the linux server doesn't have these dependencies then `dotnet` will not run correctly.  We don't have a good story today for including the OS specific dependencies with the toolset, but the long term plan (e.g. post 2.0) is to try to reduce the number of OS dependencies we have.

**Comment by nguerrera** [comment]
The approach outlined by @ellismg should indeed just work. Feel free to open issues if you encounter any problems with it.

**Comment by Deren-Liao** [comment]
I installed libunwind8.   It would be nice if you can include it in the package.
