### ISSUE TITLE
preview3 sdk shown as Preview2 

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#7198]
Is it expected that the latest SDK is marked as "Preview 2"?

Windows: https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview3-006787/dotnet-sdk-2.0.0-preview3-006787-win-x64.exe

![image](https://user-images.githubusercontent.com/1438884/28392682-d2257afa-6c97-11e7-9900-8d573b132110.png)

Linux: `apt-cache search dotnet-sdk`
```
dotnet-sdk-2.0.0-preview3-006719 - Microsoft .NET Core SDK - 2.0.0 Preview 2
dotnet-sdk-2.0.0-preview3-006726 - Microsoft .NET Core SDK - 2.0.0 Preview 2
dotnet-sdk-2.0.0-preview3-006729 - Microsoft .NET Core SDK - 2.0.0 Preview 2
```

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/7204
