### ISSUE TITLE
Running `dotnet run` on a unit test project does not display anything

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#7199]
## Steps to reproduce
```
dotnet new xunit -lang C#
dotnet run
```

## Expected  behavior
Any indicator that tests were actually not run. Possibly an error saying that `dotnet run` does not work on test projects? Anything that says what was happening.

## Actual behavior

```
PS C:\temp\test> dotnet run
PS C:\temp\test>
```

## Environment data
`dotnet --info` output:

```
PS C:\temp\test> dotnet --info
.NET Command Line Tools (2.0.0-preview3-006787)

Product Information:
 Version:            2.0.0-preview3-006787
 Commit SHA-1 hash:  16d7104b36

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006787\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25516-01
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118
```

**Comment by livarcocc** [comment]
Will move this to the vstest repo. I believe this has to do with the fact that a main method is being created by the test SDK.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#946
