### ISSUE TITLE
Add more compilers

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#72]
- [ ] - Add Visual Basic support (`dotnet-compile-vb` or `dotnet-compile-vbc`)
- [x] - Add F# support (`dotnet-compile-fs` or `dotnet-compile-fsc`)

Related to #52
/cc @jaredpar

**Comment by blackdwarf** [comment]
F# is done and in. VB remains. @agocke can you take a look at this?

**Comment by piotrpMSFT** [comment]
This is not in-scope for 1.0.0. We can do this in master so it's in-place for v-next. Better yet, this would be  done as a NuGet dotnet extension and simply get pulled in to projects on-demand!

**Comment by Petermarcu** [comment]
No need to track this here. If VB wants to add as an extension that is totally an option.

**Comment by gulbanana** [comment]
Is support for VB being tracked anywhere else?

**Comment by gulbanana** [comment]
Nevermind, I just saw #587

**Comment by NaxAlpha** [comment]
Anyone working on Visual Basic Compiler?
