### ISSUE TITLE
FirstTimeWelcomeMessage (LocalizableStrings.xlf) contains grammatical issues

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#7222]
I'm in the process of updating the telemetry topic on: https://github.com/dotnet/docs/pull/2706

I noticed that the information provided in [LocalizableStrings.xlf](https://github.com/dotnet/cli/blob/3471d437969ed52d12116f7067b02e6e12a49d03/src/Microsoft.DotNet.Configurer/xlf/LocalizableStrings.xlf) contains a nasty comma splice, minor guidelines adherence problems, and other minor issues:

Generally, one wouldn't expect symbols in the place of words ...

> Learn more about .NET Core @ https://aka.ms/dotnet-docs.

Idk if there's some special reason for it, but I'd expect "at" for the symbol. Because the link might be cut-and-paste into a browser, I recommend using a colon and no period at the end. Using the link with an accidental period lands the MS homepage. I suggest ...

> Learn more about .NET Core: https://aka.ms/dotnet-docs

For ...

> The .NET Core tools collect usage data in order to improve your experience.

... collecting the data doesn't improve the experience. I suggest swapping "help us" for "to" ...

> The .NET Core tools collect usage data in order help us improve your experience.

For ...

> The data is anonymous and does not include ...

Use the contraction per MS guidelines ("does not" :point_right: "doesn't").

> The data is anonymous and doesn't include ...

For ...

> You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.

* Guidelines call for avoiding "you can" language where possible, and this is a good example.
* "opt-out" is hyphenated.
* There's only one env var to set, so I recommend using the definite article "the" over "a" before the var.
* Our topic guidance permits also setting the env var value to `true`.

I suggest ...

> Opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

For ...

> You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Again, I suggest dropping the "you can" lingo, swapping the "@" for "at" the word, and using a colon with no period at the end ...

> Read more about .NET Core tools telemetry: https://aka.ms/dotnet-cli-telemetry

Finally ...

> A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.

* Comma splice after "cache"
* MS guidelines call for avoiding future tense (and mixing tense) when possible
* Use the more specific "run(s)" over "happen(s)"

> A command is running to initially populate your local package cache to improve restore speed and enable offline access. This command takes up to a minute to complete and only runs once.

I would've been happy to address these issues with a PR (still am!), but localization is involved, so I would need more info regarding how the other files are handled before I could assist.

**Comment by livarcocc** [comment]
I would love a PR for this. Though we have are doing our loc hand-off today (already sent it) for 2.0. Would you mind making a PR targeting master for this. for localization, simply run a build passing `/p:UpdateXlfOnBuild=true` and it will update all the necessary files for you. After running the build like that, just submit the PR including the resource files.

**Comment by GuardRex** [comment]
@livarcocc Sure ... that'll be fun to try. I'm not building the repo locally ... YET! :smile: Let me give that a go. I'll get a PR (targeting master) to you shortly.
