### ISSUE TITLE
Assertion failed in `dotnet new` macOS 10.12 (.NET Core 2.0 Preview)

### ISSUE THREAD

**Issue by michaelbartnett** [dotnet/cli#7228]
## Steps to reproduce

Ran pkg installer from https://www.microsoft.com/net/core/preview#macos

Installer appears to finish, and system pops up an error "dotnet quit unexpectedly" .

Try to start a new dotnet roject somewhere (`dotnet new console` per the page instructions)

Starts trying to update the local package cache, fails with:

```log
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 4876 ms
Assertion failed: (false && "Unknown SysConfName"), function SystemNative_SysConf, file pal_io.cpp, line 768.
zsh: abort      dotnet new console
```

## Expected  behavior

No error on package installer finish, be able to create a new project without error.

## Actual behavior

Error noted in context above.

## Environment data
`dotnet --info` output:

```sh
zsh 7 [129] % dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Linux
 OS Version:
 OS Platform: Linux
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```
Crash dump: https://gist.github.com/michaelbartnett/723bb0da52cfab306ada6a01c148c5c3

Is it supposed to think I'm on Linux?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2892
