### ISSUE TITLE
Difference between all donet.exe under SDK/Runtime binary

### ISSUE THREAD

**Issue by TingluoHuang** [dotnet/cli#7235]
I noticed there are few `dotnet.exe` under the SDK/Runtime binary.
 
Ex: I download the netcore 1.1 SDK binary, the layout looks like this
```
..\host
  \sdk
  \shared\Microsoft.NETCore.App\1.1.1\dotnet.exe
  \dotnet.exe
```

Ex: I download the netcore 1.1 runtime binary, the layout looks like this
```
..\host
  \shared\Microsoft.NETCore.App\1.1.1\dotnet.exe
  \dotnet.exe
```

 I am curious about what's the different between them.

**Comment by wli3** [comment]
Hi TingluoHuang,
The difference is... well... whether SDK is concluded.

Runtime is for your app to be run on, and SDK is to help you **develop** as a developer.

In a sense, as a developer you use the SDK to develop an app using commands like dotnet new, restore, build, publish. After you publish your app, if the app is not  [self contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/), runtime is required for your customer/hosting environment to run the app

**Comment by TingluoHuang** [comment]
@wli3 I understand that, but even the Runtime binary has 2 dotnet.exe, what's the different between them?

**Comment by livarcocc** [comment]
In 2.0, we have removed the duplicated dotnet.exe and now there is only one. At the root of the install dir.

**Comment by oliverjanik** [comment]
How is side by side handled? I have Core 1.1 deployed on the server and I'm deploying Core 2 and it seems 1.1 is being picked up all the time

**Comment by livarcocc** [comment]
@oliverjanik is this the runtime or the SDK that is being picked up?

**Comment by oliverjanik** [comment]
Runtime. Should I be installing SDK on the server?

**Comment by oliverjanik** [comment]
I found my actual issue. I installed Core 2 runtime. But my project nuget packages were newer than the one in the dotnet store (the new GAC ?). I had to hunt down what to download and where to update the store packages.

Seems that framework libs are not part of deployment anymore.

**Comment by oliverjanik** [comment]
You might want to mention somewhere that Runtime will not automatically deploy new AspNetCore dlls.

Also your link on this page (https://www.microsoft.com/net/download/windows) for x64 ASP.NET Core Runtime (.zip) downloads 2.0.3 not 2.0.5

**Comment by livarcocc** [comment]
If you are on windows, I think you just need the hosting bundle and you get both the runtime and the store. Also, the links are showing as 2.0.5 for me. I wonder if there is something cached in your case.

Anyways, @joeloff to confirm that the hosting bundle is enough and @leecow is case there is something wrong with the links in the site.

**Comment by oliverjanik** [comment]
Pls hit this url: https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.5-windows-x64-asp.net-core-runtime-binaries

it downloads 2.0.3, does not matter what the url says ;-)

**Comment by oliverjanik** [comment]
I missed the hosting bundle download. Can we have a little description against all downloads to tell us what's needed in what scenarios?

**Comment by joeloff** [comment]
Hosting bundle should be enough I think

@leecow can we update the page with short description around the content, or perhaps a that shows what components ship where split between runtime, SDK, store and ANCM

**Comment by livarcocc** [comment]
@leecow can you check why the URL is still pointing to 2.0.3

**Comment by leecow** [comment]
@livarcocc , @oliverjanik - ASP.NET version referenced updated to 2.0.5. Should be live in a few minutes.

**Comment by leecow** [comment]
@joeloff , @oliverjanik - that part of the download page is kind of terrible and will receive an overhaul before too long.

**Comment by oliverjanik** [comment]
thanks guys, sounds like you have it under control
