### ISSUE TITLE
dotnet clean should say what it does

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7239]
## Steps to reproduce
`dotnet clean --help`

## Expected  behavior
Explanation of what `dotnet clean` does

## Actual behavior
Just a bunch of options but no context

## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25514-02
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118
```

**Comment by livarcocc** [comment]
This is by design. We have removed descriptions to the commands as they were adding very little, if anything at all.

cc @richlander
