### ISSUE TITLE
bin and obj folders keep coming back

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7241]
## Steps to reproduce
`dotnet build`
Have your project open in VS.
Open the folder for your project in explorer. 
delete the bin and obj folder. 

## Expected  behavior
The folder are gone

## Actual behavior
They come back. The bin folder is empty and the obj folder has assembly info and .cache files.
Delete again and they are gone.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview3-006770)

Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25514-02
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118
```

**Comment by livarcocc** [comment]
@Petermarcu please, move this issue to the project-system or Nuget. This happens because VS will restore the project once it seens it does not have a project.assets.json.

**Comment by livarcocc** [comment]
Moving this to Nuget, since I believe this happens because of automatic restore in VS.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5639
