### ISSUE TITLE
Could not resolve CoreCLR path - Raspberry Pi

### ISSUE THREAD

**Issue by janvorli** [dotnet/cli#7248]
@techyian commented on [Wed Jul 05 2017](https://github.com/dotnet/coreclr/issues/12645)

Hi,

I'm trying to run my application under .NET Core on a Raspberry Pi 2. The Pi is running Ubuntu Mate 16.04.2 LTS.

I've built my application under Windows using .NET Core SDK `2.1.0-preview1-006632` using `dotnet publish -r linux-arm` and this builds successfully. All publish files are present, however when I try to run the self-contained file, I receive the following error:

```Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1```

I have seen previous issues raised on StackOverflow/GitHub regarding this issue but that was last year and I hoped the issue may have been resolved. My understanding is that currently the SDK is not available for linux arm and this is why a self-contained application is made when running `dotnet publish`?

To confirm, I've followed the instructions found [here](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md), and all dependencies are installed.

Does anyone have any idea what may be causing this?

Thanks :)

---

@parjong commented on [Thu Jul 06 2017](https://github.com/dotnet/coreclr/issues/12645#issuecomment-313264182)

When I build and publish a self-contained application on Linux (using .NET Core SDK ``2.0.0-preview2-006419``), it works well on Raspberry Pi 3  (running Raspbian).

Could you run your application after setting COREHOST_TRACE  as 1?

---

@techyian commented on [Tue Jul 11 2017](https://github.com/dotnet/coreclr/issues/12645#issuecomment-314534841)

Can confirm a HelloWorld app created using `dotnet console new` works correctly when publishing for linux-arm. However the project I'm having issues with has 3rd party project dependencies. Going to do some more digging and see if I can figure out what's going on.

---

@techyian commented on [Tue Jul 11 2017](https://github.com/dotnet/coreclr/issues/12645#issuecomment-314539015)

It seems to be the following causing the problem in the csproj file:

`<RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>`

The csproj file generated by `dotnet console new` does not include this, but running `dotnet publish -r linux-arm` still works without issue. Removing this from my csproj file fixes the problem.

The instructions found [here](https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md) suggest adding this to the csproj file - are these instructions now outdated?

---

@parjong commented on [Wed Jul 12 2017](https://github.com/dotnet/coreclr/issues/12645#issuecomment-314616346)

I'm not sure, but it seems that [cli repo](https://github.com/dotnet/cli) is better fit for this kind of questions.

---

@jkotas commented on [Wed Jul 12 2017](https://github.com/dotnet/coreclr/issues/12645#issuecomment-314893607)

cc @Petermarcu since he has been maintaining the instructions at https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

---

@Petermarcu commented on [Fri Jul 14 2017](https://github.com/dotnet/coreclr/issues/12645#issuecomment-315386331)

@techyian, that entry in the csproj was made optional recently but it shouldn't have different effects than specifying `-r linux-arm` on the command line. That command line effectively just sets that property. @eerhardt for when you get a chance to look at that. I'm happy to remove that line from the instructions as it is optional now.

**Comment by livarcocc** [comment]
How are you running your application after publishing:

* dotnet app.dll: if you are publishing with -r or without the RuntimeIdentifier set in your project, then your app is a portable app and you need to execute it with dotnet app.dll. Which implies that you need to have appropriate runtime installed in the machine.
* app (executable): If you are publishing with -r or with a RuntimeIdentifier set in your project, then your app is a self-contained app and needs to be executed with the executable.

**Comment by Petermarcu** [comment]
@livarcocc, did you mean "without -r" in your first bullet?

**Comment by livarcocc** [comment]
@Petermarcu Yes. I updated my comment.

**Comment by techyian** [comment]
Hi @livarcocc,

I was publishing as a self-contained application but did also try with runtime and received the same error. Let me know if you need me to test anything else.

**Comment by livarcocc** [comment]
@techyian it is not super clear to me what situations this works for you. But I just noticed that you have `<RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>` in your csproj. Note the plural in the property name. When the property name is plural, you need to pass -r <RID> when publishing.

So, you need to do one of these:

* Have `<RuntimeIdentifiers>linux-arm</RuntimeIdentifiers>` (plural) in your csproj, publish with `dotnet publish -r linux-arm`
* Do not have any extra properties in your csproj,  publish with `dotnet publish -r linux-arm` 
* Have `<RuntimeIdentifier>linux-arm</RuntimeIdentifier>` (singular) and publish with `dotnet publish`

**Comment by livarcocc** [comment]
Given that we haven't had activity here in a while and this seems more like a confusion about experience and documentation then an actual bug in the product, I am closing this issue.

Please, re-activate if I misunderstood something.
