### ISSUE TITLE
runtime args error giving a bad message

### ISSUE THREAD

**Issue by janvorli** [dotnet/cli#7249]
@pynixwang commented on [Sun Jun 25 2017](https://github.com/dotnet/coreclr/issues/12446)

```Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
         http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

when i use dotnet runtime but dll path is error,  `dotnet` show me this bad message, it 's very hard to find the problem. other errors also show this message.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2898
