### ISSUE TITLE
Change tool source directories to match tool name

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#726]
Like dotnet-restore, tools sources should live in directory names that match the tool name. Namespaces for libraries happen to match the output name and output name. For tools, the output name diverges from the namespace name because namespaces are inconvenient for users. The directory should map to the artifact it produces and not implementation details of that artifact.

**Comment by brthor** [comment]
YES :+1: 

Typing those directory names is slow :smile:

**Comment by blackdwarf** [comment]
:+1: Please do this. :)

**Comment by blackdwarf** [comment]
@piotrpMSFT is this done?

**Comment by piotrpMSFT** [comment]
long long ago.
