### ISSUE TITLE
Adding NuGet.Core package to csproj as PackageReference has no any effect in restore/build process

### ISSUE THREAD

**Issue by maestrow** [dotnet/cli#7268]
## Steps to reproduce

1. `dotnet new`
1. Change `TargetFramework` in `csproj` file to `net461`
1. `dotnet add package NuGet.Core`
1. Add `using NuGet;` to `Program.cs` (this namespace is exists in NuGet.Core Assembly, I checked)
1. `dotnet restore`
All above executed successfully. Next:
6. `dotnet build`

## Expected  behavior

Successfull Build

## Actual behavior

Error: "The type or namespace name 'NuGet' could not be found".

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

I'm tried on both versions: 1.0.4 and 2.0.0-preview2-25407-01

**Comment by maestrow** [comment]
[Problem solved with nuget cache clearing](https://stackoverflow.com/questions/45314575/after-i-add-nuget-core-package-to-my-csproj-as-packagereference-i-have-no-any-e). But I think there should be a message, if reference was not created while project build. There **is** `<PackageReference Include="NuGet.Core" Version="2.14.0" />` is csproj, but **no** correnponding reference was created in assembly after build.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5650
