### ISSUE TITLE
Cannot use PAT with dotnet restore on Linux with TFS 2017 Update 2 packages

### ISSUE THREAD

**Issue by sbebrone** [dotnet/cli#7272]
## Steps to reproduce
NuGet.config configured to use a private package feed hosted on a local TFS 2017 Update 2 server with a PAT authentication:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
        <add key="myfeed" value="[feed url]" />
      </packageSources>
      <packageSourceCredentials>
        <myfeed>
            <add key="Username" value="myuser" />
            <add key="ClearTextPassword" value="[PAT]" />
        </myfeed>
      </packageSourceCredentials>
    </configuration>

## Expected  behavior
Restore should authenticate successfully and restore private packages as written in this article:
https://www.visualstudio.com/en-us/docs/package/nuget/nuget-exe#net-core

## Actual behavior
dotnet restore fails with authentication fails (401)

## Environment data
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5651
