### ISSUE TITLE
dotnet add package doesn't preserve csproj whitespace

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7280]
## Steps to reproduce
dotnet new a console app
dotnet add package <any package>

## Expected  behavior
whitespace between itemgroups etc is preserved

## Actual behavior
All blank lines are removed

## Environment data
`dotnet --info` output:

```
Product Information:
 Version:            2.0.0-preview3-006770
 Commit SHA-1 hash:  78e7163819

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview3-006770\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25514-02
  Build    : 1b047a04057cec973cfb890fd21f7a639cfcd118


```

**Comment by mishra14** [comment]
Since NuGet/Dotnet do not directly edit the csproj file, I have moved this issue to msbuild : https://github.com/Microsoft/msbuild/issues/2376

**Comment by mishra14** [comment]
This has been fixed in NuGet. Will go into dotnet cli during the next insertion. :)
