### ISSUE TITLE
How can a use dotnet command 1.0.4 after install dotnet sdk 2.0.0

### ISSUE THREAD

**Issue by blondit** [dotnet/cli#7289]
## Steps to reproduce
I open a command promt, and I run dotnet command:
   Microsoft Windows [Version 10.0.15063]
   (c) 2017 Microsoft Corporation. All rights reserved.

   C:>dotnet --version
   2.0.0-preview2-006497

   C:>
This is Ok.
The question is how can I run version 1.0.4 dotnet command?

This is not working:
   C:\dotnet1

Ok, but how ...?

Sorry for my bad english.

**Comment by omajid** [comment]
Add a `global.json` file ([syntax here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json)) in the project directory. Make that file refer to the sdk version for 1.0.4:


    {
      "sdk": {
        "version": "1.0.1"
      }
    }

Yes, the version corresponding to .NET Core runtime 1.0.4 is SDK 1.0.1.

**Comment by livarcocc** [comment]
We also have a 1.0.4 version of the SDK that ships with VS. So, putting 1.0.4 in there should be ok, if that's the SDK version you have installed and want to run.
