### ISSUE TITLE
Migrate runtime copying from compile-stage script to PublishCommand

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#729]
I was poking around the build scripts and noticed that https://github.com/dotnet/cli/blob/master/scripts/compile/compile-stage.ps1#L63 is using the dummy Microsoft.DotNet.Runtime to copy runtime dlls into the output dir. 
Then I noticed that PublishCommand is copying over the same DLLs (because the projects it's publishing also depend on the same runtime libs): https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L152

I propose we migrate this "Ensure Runtime libs are present"  responsibility from the script into publish. Then, this might be widened to also ensure the runtime libs unique to the project nature (I remember seeing an issue about fsharp projects needing some extra runtime libs, but can't find it)

**Comment by cdmihai** [comment]
Subsumed by #825

**Comment by cdmihai** [comment]
Reopened to track issue separately, as suggested by https://github.com/dotnet/cli/issues/825#issuecomment-171567864. I will also copy paste Peter's response regarding the build script in order to have continuity for this issue.

**Comment by cdmihai** [comment]
Copy pasting @piotrpMSFT's response from #825:

*__Build Scripts__*

_Note that the restore of the runtime is used to generate the Runtime folder which is then used for runtime of CLI-produced apps. Publish copies that same runtime into the Bin directory for use by the CLI tooling. In order to clean this up [and significantly reduce package size] we need to add another probing path to the corehost which will cause it to attempt to use the parent directory as the DOTNET_HOME. I think this is feasible and is being tracked in #451._

**Comment by cdmihai** [comment]
I agree that package size might be an issue, and therefore DOTNET_HOME probing.

However, with this approach it would be good if this approach:
- does not lock users on a certain runtime version and allow them to use different runtime versions for different apps. This means allowing users to specify their runtime version in their project.json and then doing some magic to get restore and load those DLLs from a local cache (although this sounds terribly close to recreating a GAC).

- allows traceability of runtimes. Ideally, the runtime needs to be traced to a nuget package, so incrementality (and maybe the new dotnet watch?) are aware when a version change occurs.

**Comment by piotrpMSFT** [comment]
This is fixed.
