### ISSUE TITLE
.Net Core SDK 2.0 installer - fix name of Runtime Package Store

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/cli#7301]
The correct name is Runtime ~Package~ Store
That is - remove Package from the name. It's  **Runtime Store**

![image](https://user-images.githubusercontent.com/3605364/28644272-c640946a-720d-11e7-924c-70be1b6f2ba0.png)

contacts: [@]DamianEdwards  and [@]richlander

**Comment by richlander** [comment]
Let's take for 2.0.1. Thanks!

/cc @livarcocc 

FYI @Rick-Anderson  -- those @mentions didn't work.
