### ISSUE TITLE
dotnet restore uses different nuget.config location to nuget (on mac)

### ISSUE THREAD

**Issue by macon** [dotnet/cli#7310]
## Steps to reproduce
Add a new package source using nuget CLI e.g.
```
nuget sources add -Name myArtifacts -Source http://myartifacts.com/nuget
```
From a dotnet core project, edit the .csproj and add a reference to a nuget package from that source e.g.
```
<PackageReference Include="MyNugetPackage.Library" Version="1.0.22" />
```
Do a dotnet restore.

## Expected  behavior
The package should be restored from the new Nuget source

## Actual behavior
I get
```
/usr/local/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): error : Unable to resolve 'MyNugetPackage.Library (>= 1.0.22)' for '.NETCoreApp,Version=v1.1'
```
It seems nuget.exe is using the path ~/.config/NuGet/NuGet.config (where it successfully added the new package source). But dotnet restore is using ~/.nuget/NuGet/NuGet.Config. 

Either we need a way of adding package sources via the dotnet CLI or a way to get the dotnet CLI to use the ~/.config/NuGet path for NuGet.config (unless I'm missing something and my installation is corrupted somehow).

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5672
