### ISSUE TITLE
Problem on Debian Buster (Testing)

### ISSUE THREAD

**Issue by matiux** [dotnet/cli#7319]
When I run `dotnet new console -o hwapp` on Debian Buster (Debian Tetsing) I get this:

```
Getting ready...
Segmentation fault
```

$dotnet --info

.NET Command Line Tools (2.0.0-preview2-006391)

Product Information:
 Version:            2.0.0-preview2-006391
 Commit SHA-1 hash:  ef5d4b47c3

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006391/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by matiux** [comment]
Same thing with older version:

$ dotnet --info
.NET Command Line Tools (1.0.4)                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
Product Information:                                                                                                                                                                                                                         
 Version:            1.0.4                                                                                                                                                                                                                   
 Commit SHA-1 hash:  af1e6684fd                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
Runtime Environment:                                                                                                                                                                                                                         
 OS Name:     debian                                                                                                                                                                                                                         
 OS Version:                                                                                                                                                                                                                                 
 OS Platform: Linux                                                                                                                                                                                                                          
 RID:         debian.8-x64                                                                                                                                                                                                                   
 Base Path:   /opt/dotnet/sdk/1.0.4

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2943
