### ISSUE TITLE
dotnet ***.dll - Segmentation fault on Ubuntu ARM 32

### ISSUE THREAD

**Issue by mubavoice** [dotnet/cli#7326]
## Steps to reproduce
1. Install .net Core SDK 2.1.0-preview1-006958
2. add signalR into the project
3. compile the project and deploy to Linux Ubuntu mate running Ubuntu 16.04 in ODroid-xu4 (arm32) ( runtime already installed in Ubuntu with the same version of the runtime).
4. run the dotnet web site with dotnet dlll-name.dll

## Expected  behavior
1. The application is working fine in windows 10 environment.
2. The same code compiled and published with "dotnet publish --runtime ubuntu.16.04-arm" should work

## Actual behavior
1. When we run the dotnet dll-name.dll, it fails in randomly and web site does not load.

Application some  it throws Segmentation fault as soon as we run the 'dotnet Dahlia.dll' command. Some times it executes little futher and throws the segmentation fault. Below are the two scenarion it got failed.

1st Log:
----------------------
droid@odroid:/dotnetprojects/Dahlia$ dotnet Dahlia.dll
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/home/odroid/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file '/home/odroid/.aspnet/DataProtection-Keys/key-f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a.xml'.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file '/home/odroid/.aspnet/DataProtection-Keys/key-2f1f3097-f7ac-419b-abf5-6a5dfd280585.xml'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {2f1f3097-f7ac-419b-abf5-6a5dfd280585}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
      Considering key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a} with expiration date 2017-10-29 11:18:15Z as default key.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory[11]
      Using managed symmetric algorithm 'System.Security.Cryptography.Aes'.
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory[10]
      Using managed keyed hash algorithm 'System.Security.Cryptography.HMACSHA256'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
      Using key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a} as the default key.
dbug: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionStartupFilter[0]
      Key ring with default key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a} was loaded during application startup.
dbug: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Hub method 'updateDeviceState' is bound
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly Dahlia
Hosting environment: Production
Content root path: /dotnetprojects/Dahlia
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HL6OUDOR8B5V" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HL6OUDOR8B60" started.
Segmentation fault
odroid@odroid:/dotnetprojects/Dahlia$
----------

2nd Log
---------
dotnet Dahlia.dll
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/home/odroid/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file '/home/odroid/.aspnet/DataProtection-Keys/key-f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a.xml'.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file '/home/odroid/.aspnet/DataProtection-Keys/key-2f1f3097-f7ac-419b-abf5-6a5dfd280585.xml'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {2f1f3097-f7ac-419b-abf5-6a5dfd280585}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
      Considering key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a} with expiration date 2017-10-29 11:18:15Z as default key.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory[11]
      Using managed symmetric algorithm 'System.Security.Cryptography.Aes'.
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory[10]
      Using managed keyed hash algorithm 'System.Security.Cryptography.HMACSHA256'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
      Using key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a} as the default key.
dbug: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionStartupFilter[0]
      Key ring with default key {f0fe4c62-5cef-46fa-83c5-5bb2d7cd7d4a} was loaded during application startup.
dbug: Microsoft.AspNetCore.SignalR.HubEndPoint[0]
      Hub method 'updateDeviceState' is bound
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[0]
      Loaded hosting startup assembly Dahlia
Hosting environment: Production
Content root path: /dotnetprojects/Dahlia
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HL6OUF6DCMQB" started.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HL6OUF6DCMQA" started.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path / does not match a supported file type
dbug: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[9]
      AuthenticationScheme: Bearer was not authenticated.
dbug: Microsoft.AspNetCore.Builder.RouterMiddleware[1]
      Request did not match any routes.
dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action Dahlia.Controllers.HomeController.Index (Dahlia)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Dahlia.Controllers.HomeController.Index (Dahlia) with arguments ((null)) - ModelState is Valid
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Dahlia.Controllers.HomeController.Index (Dahlia), returned result Microsoft.AspNetCore.Mvc.ViewResult.
dbug: Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine[1]
      View lookup cache miss for view 'Index' in controller 'Home'.
Segmentation fault

## Environment data
`dotnet --info` output:

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-dev-di-25531-02
  Build    : 7a391b9234369c48fe8d809d549e349259be00e5

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2954
