### ISSUE TITLE
Rename ".NET MSBuild Extensions" to "“.NET Standard Support for Visual Studio 2015"

### ISSUE THREAD

**Issue by terrajobst** [dotnet/cli#7328]
We're building an MSI that brings necessary build support for referencing .NET Standard binaries from .NET Framework projects. The current name is **.NET MSBuild Extensions**. However, that name collides with a very popular 3rd party OSS project called [MSBuild Extension Pack](https://www.google.com/search?q=msbuild+extension) that provides additional tasks.

The name we decided on is **“.NET Standard Support for Visual Studio 2015**

**Comment by livarcocc** [comment]
dotnet-standard-support-vs2015-2.0.0-preview3-006908-win-x86.msi

**Comment by terrajobst** [comment]
Can we add a "net-core" in there somewhere? :trollface:
