### ISSUE TITLE
Dotnet add package: don't fail when temp files are exhausted.

### ISSUE THREAD

**Issue by szahn** [dotnet/cli#7331]
When adding a nuget package to a .net core app 1.1, get the following result:

A more useful error which doesn't cause the application to fail would be helpful.

```
PS C:\docker\benchmarks\src> dotnet add package System.Runtime.Serialization.Primitives -v 4.0.10

Unhandled Exception: System.IO.IOException: The file exists
   at System.IO.Path.GetTempFileName()
   at Microsoft.DotNet.Tools.Add.PackageReference.AddPackageReferenceCommand.Run(String fileOrDirectory)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.<>c__DisplayClass10_1.<RunCommand>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Add.AddCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
PS C:\docker\benchmarks\src>
```

```
PS C:\Docker\Benchmarks\src> dotnet add package "System.Runtime.Serialization.Primitives" -version "4.1.0-beta-23516"
Please specify one package reference to add.
```

![dotnet add error](https://user-images.githubusercontent.com/271732/28842028-f365125c-76b0-11e7-9fcf-eadb5162e91f.png)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by mishra14** [comment]
@szahn  I am unable to reproduce the error.  The package does not seem compatible with netcoreapp v1.1 - 

```
F:\validation\test\rest> dotnetlocal new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on F:\validation\test\rest\rest.csproj...
  Restoring packages for F:\validation\test\rest\rest.csproj...
  Generating MSBuild file F:\validation\test\rest\obj\rest.csproj.nuget.g.props.
  Generating MSBuild file F:\validation\test\rest\obj\rest.csproj.nuget.g.targets.
  Restore completed in 129.66 ms for F:\validation\test\rest\rest.csproj.


Restore succeeded.

F:\validation\test\rest> dotnetlocal add package System.Runtime.Serialization.Primitives -v 4.0.10
  Writing C:\Users\anmishr\AppData\Local\Temp\tmpC83B.tmp
info : Adding PackageReference for package 'System.Runtime.Serialization.Primitives' into project 'F:\validation\test\rest\rest.csproj'.
log  : Restoring packages for F:\validation\test\rest\rest.csproj...
error: Package System.Runtime.Serialization.Primitives 4.0.10 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package System.Runtime.Serialization.Primitives 4.0.10 supports:
error:   - dotnet (.NETPlatform,Version=v5.0)
error:   - monoandroid10 (MonoAndroid,Version=v1.0)
error:   - monotouch10 (MonoTouch,Version=v1.0)
error:   - net46 (.NETFramework,Version=v4.6)
error:   - xamarinios10 (Xamarin.iOS,Version=v1.0)
error:   - xamarinmac20 (Xamarin.Mac,Version=v2.0)
error: Package 'System.Runtime.Serialization.Primitives' is incompatible with 'all' frameworks in project 'F:\validation\test\rest\rest.csproj'.
```

Looking at your error message it seems that when the command is trying to get an exception in the net core libraries.

**Comment by mishra14** [comment]
Looking at your error message it seems that when the command is trying to get an exception in the [net core libraries](https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename(v=vs.110).aspx)

Could you clear your temp directory and try. The error doesn't seem specific to this command, it could be a machine state....

**Comment by livarcocc** [comment]
Yeap, this is happening probably due to this:
``
The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files.
``
I agree we should not throw an exception when this happens, but rather, catch it and treat it gracefully. Though, cleaning your temp folder will likely unblock you.

**Comment by livarcocc** [comment]
I believe this has now been addressed as we are catching that exception and bubbling up an appropriate error message.
