### ISSUE TITLE
Why doesn't 'dotnet nuget' support full set of nuget commands on Linux

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/cli#7339]
## Steps to reproduce
Try to add new package feed via CLI, no way to do it

## Expected  behavior
dotnet nuget sources ... , etc, works

## Actual behavior
Have to use editor to manually create nuget.config, get right XML syntax, etc

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview3-006908)

Product Information:
 Version:            2.0.0-preview3-006908
 Commit SHA-1 hash:  38031f6e5c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview3-006908/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by mishra14** [comment]
@AndyAyersMS: Thanks for reporting the request. This is already a part of our backlog - https://github.com/NuGet/Home/issues/4855 

If you are using Windows then you can download `nuget.exe` from [here](https://dist.nuget.org/index.html). On mac/linux, you can try running `nuget.exe` on `mono` which can be downloaded from [here](http://www.mono-project.com/download/)
