### ISSUE TITLE
dotnet sln add should accept directory name

### ISSUE THREAD

**Issue by tmat** [dotnet/cli#7343]
```dotnet sln add``` currently accepts a path to a project file. Given that dotnet CLI generally assumes a single project per directory and its project related commands use the single project in the current directory by default it would make sense to allow to specify ```dotnet sln add DirName```. This command would check if there is a single project in the directory and if so add it into the solution. The same for ```dotnet sln remove```.

```dotnet add reference``` could also take a directory...

**Comment by livarcocc** [comment]
What would you expect when no project is found in the directory? Or when multiples are found?

cc @richlander

**Comment by tmat** [comment]
An error in both cases.

**Comment by peterhuene** [comment]
Hi @tmat, thanks for the feature suggestion!  I'll have a PR up shortly for adding directory support for `sln add`, `sln remove`, `add reference`, and `remove reference`.

Additionally, I noticed that `sln remove` currently outputs a misleading message of "project reference removed"; changing this to be consistent for what we display with `sln add`.
