### ISSUE TITLE
Suggestion: Use the package name from Nuget site instead of the name user enters when running "dotnet add package" command

### ISSUE THREAD

**Issue by RickyLin** [dotnet/cli#7346]
## Steps to reproduce

run the follow commands (I run them on Mac OS):

1. `mkdir demo`
2. `cd demo`
3. `dotnet new console`
4. `dotnet add package microsoft.aspnetcore.mvc.core`
5. `vim demo.csproj`

Look at the `PackageReference` element in demo.csproj

## Expected  behavior
`<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="1.1.3" />`

## Actual behavior
`<PackageReference Include="microsoft.aspnetcore.mvc.core" Version="1.1.3" />`

## Explanation

I typed commands in all lower-case for faster typing speed and commands were run successfully, but in .csproj file, it would better be `Microsoft.AspNetCore.Mvc.Core` instead of `microsoft.aspnetcore.mvc.core`.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by rohit21agrawal** [comment]
CC: @mishra14

**Comment by livarcocc** [comment]
Moving this to NuGet for consideration, but I don't believe there is any technical reason to do that, as it does not influence the package id nor the package folder where NuGet restores that package.

On top of that, with tab completion in the CLI, the right casing would be used if the package name were auto-completed in the command line.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6162
