### ISSUE TITLE
Every project fails to load opening solution

### ISSUE THREAD

**Issue by davkean** [dotnet/cli#7348]
## Steps to reproduce
1. Clone cli
2. Open Microsoft.DotNet.Cli.sln

## Expected  behavior
Solution to open

## Actual behavior
Every project fails to load with:
```
E:\cli\test\msbuild.IntegrationTests\msbuild.IntegrationTests.csproj : error  : The imported project "E:\cli\artifacts\obj\GitCommitInfo.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\cli\dir.props
```
## Environment data
`dotnet --info` output:

**Comment by davkean** [comment]
Maybe I have to build the tree first? I don't a Restore.cmd anywhere.

**Comment by davkean** [comment]
I cancelled build.cmd after about 30 minutes. It feels like i'm missing a quick way to open the solution here - the developer docs don't appear to even mention VS.

**Comment by wli3** [comment]
To get it open in VS you need to run 
```
./build.cmd /p:CLIBUILD_SKIP_TESTS=true
```

after pull clone the repo. We do feel the pain, and we plan to make it work smoothly with VS

**Comment by pazof** [comment]
I really would appreciate a way to simply build your code under else where but MS Windows ...
like under a POSIX system ... your code is open, but closed to any way to use it.

MS killed c#. I think I'll drop all idea to continue with.

**Comment by livarcocc** [comment]
@pazof if you mean the CLI code, it works cross-platform and I myself do the majority of my work on a macbook. You can simply invoke build.sh to build on both OSX and Linux. 

This issue in particular is about being able to open the CLI solution in VS and work with it. We are actually working on making that possible, as well as working on VSCode and VS for Mac, but the change is not available in all our branches just yet.

**Comment by livarcocc** [comment]
We are now following arcade. With it, if you do a build.cmd once and then open the solution, the solution does load correctly.
