### ISSUE TITLE
Implicit RID should not be used when restoring a library targeting netstandard

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#735]
When building a application or publishing the CLI should use an implicit RID.  This RID can be calculated by calling OS APIs and have some fallback to the native RID that the CLI was built with.

1. If the runtimes section exists in the project, the implicit RID should not be used.
1. If the runtimes section exists in the project, the implicit RID should not be used.
1. In the case of restore for an application the implicit RID should be used.
1. In the case of restore for a library targeting something other than netstandard it may be OK to include the implicit RID, however that may be extraneous since the library is not directly runnable.
1. In the case of restore for a library targeting netstandard the implicit RID should not be used.  Including the implicit RID will cause NuGet's compatibility check to do the wrong thing.  We want a library targeting netstandard to have a compatibility error if any of its dependencies do not have NETStandard implementations that are not RID constrained.  In other words the library needs to be completely portable.  This is related to https://github.com/dotnet/cli/issues/733.

/cc @anurse @davidfowl

**Comment by blackdwarf** [comment]
@ericstj if this is still valid, I believe it should be migrated over to Nuget/home since `dotnet restore` uses that under the covers.

**Comment by ericstj** [comment]
This work was cut I believe.  There is no implicit RID.
