### ISSUE TITLE
dotnet new

### ISSUE THREAD

**Issue by foxjazz** [dotnet/cli#7354]
## Steps to reproduce
dotnet new project

## Expected  behavior
creates a folder project and scaffolds a new project called project.

## Actual behavior
saffolds a new project in current folder called project

Windows 10. dos or powershell

**Comment by GuardRex** [comment]
@foxjazz 

You can supply the folder to use (or create) with the `-o|--output` option ...

```
dotnet new console -o project
```
... which should create the console app in the *project* folder. If the folder doesn't exist, it will create it for you.

**Comment by wli3** [comment]
or 

> creates a folder project and scaffolds a new project called project.
```
dotnet new console -n myconsole 
```
