### ISSUE TITLE
[2.0.1] Update NuGet tooling to understand UAP->NS2.0 Mapping

### ISSUE THREAD

**Issue by zamont** [dotnet/cli#7356]
To properly enable project-to-project references from UWP 6.0 projects to .NET Standard 2.0 libraries, the .NET Core SDK needs to understand NuGet's new mapping between UAP,Version=v10.0.RS3 to netstandard2.0. Once NuGet enables that TFM mapping, we need to consume the updated NuGet tooling.

**Comment by dsplaisted** [comment]
This is done.
