### ISSUE TITLE
"Manage User Secrets" in VS context menu for Console Apps?

### ISSUE THREAD

**Issue by alexvy86** [dotnet/cli#7360]
Is there a reason why .NET Core Console Apps don't show the "Manage User Secrets" option in the project context menu (in Visual Studio), like Web Applications do? I was able to use the dotnet user-secrets command to set them, but it'd be nice to have the same experience that Web Application have. I wanted to copy-paste a list of several of secrets and instead had to do them one-by-one in the command line.

If this is just a matter of putting the work into it, I might give it a shot.

**Comment by livarcocc** [comment]
@mlorbetske @vijayrkn is this something that you guys would handle?

**Comment by mlorbetske** [comment]
@eilon any thoughts on the user secrets tool for use in non-web scenarios?

**Comment by Eilon** [comment]
I think the "Manage User Secrets" option in VS needs to go away because it depends on implementation details of the "user-secrets" command - namely, that it's an unencrypted file located in a particular location.

As far as whether someone should use user-secrets in non-ASP.NET Core apps - yeah, sure, why not? 😄

cc @glennc

**Comment by alexvy86** [comment]
Oh, I didn't even think about that... so it's just loading the json file from its location on disk? Yeah, that doesn't sound ideal. I guess there are no current plans to change the way it integrates with VS, otherwise someone would've mentioned them? Off the top of my head I can think of 2 other ways of doing it:
- Have it open a "temporary" json file just as a UI for the user to capture the secrets, which then get piped one by one to the user-secrets tool, and discard the temporary file. Not sure if this way is possible at all without letting the user save the file, which I'd try to avoid so there's no risk of the secrets making it into a repo and getting commited or something.
- Open a custom-made pop-up, maybe as simple as just a text area, and again pipe whatever the user enters there into the tool.

If either of those would be acceptable, I might try to take a dive into how to put it in place. If it's possible in the same/similar way that currently enables the context-menu option for ASP.NET Core, I guess it would be preferable? Otherwise I imagine a VS extension might be the way.

**Comment by Eilon** [comment]
Yeah I would imagine some kind of VS extension that pops up a nice "grid" UI that ultimately just automates what the `dotnet user-secrets XYZ` commands do. I'm not sure how much of the underlying functionality is exposed by APIs, as opposed to actually running the command-line tool. But if APIs need to be added to expose that, that's certainly something we'd consider.

**Comment by alexvy86** [comment]
@Eilon, do you know where's the code that currently adds the context menu option for ASP.NET Core apps? It'd be a good starting point for me to look into alternatives.

**Comment by livarcocc** [comment]
I am going to close this issue since it is unrelated to the CLI.

**Comment by Zonciu** [comment]
I'd made a powershell [script](https://gist.github.com/Zonciu/0b5cf2356b798cd82af1a6e92443b8cb) to do that, add this script to VS external tools to work.
