### ISSUE TITLE
Is dotnet-sdk 2.1 available to apt-get on Ubuntu 17?

### ISSUE THREAD

**Issue by badersur** [dotnet/cli#7361]
I installed the latest dotnet-sdk as described here for Ubuntu 16.10:

```
sudo sh -c 'echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list'

sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

sudo apt-get update
```

After running `apt-cache search dotnet-sdk | grep 2.0.0`, I instaled `dotnet-sdk-2.0.0-preview2-006497`. And I can't find version 2.1 for `dotnet-sdk`. Shouldn't we use `dotnet-dev-2.1.0-preview1-006329`? even though it's not the latest daily build as the name suggests (and it doesn't seem to be replaced with a newer version for more than a day!).

## Expected  behavior

Running `sudo apt-get update; apt-cache search dotnet-sdk | grep 2.0.0` should show new packages (ideally using `| grep 2.1`)

## Actual behavior

I see old packages after 4 days of installing 2.0.0-preview2-006497!

I'm confused a little bit and would like to know if latest daily build of dotnet SDK is available to apt? and how to obtain it? I don't want to build from source or install 4 .deb files..

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by wli3** [comment]
Hi @badersur  
You are using 16.10's feed "**yakkety** main". We don't have Ubuntu 17.04 feed yet. And the feed is currently not healthy. 

https://github.com/dotnet/cli/issues/690

You can use the install script as walk around for now
``` shell
git clone https://github.com/dotnet/cli.git
 ./cli/scripts/obtain/dotnet-install.sh  --channel release/2.0.0
```
I also created back log for ubuntu 17.04 daily feed https://github.com/dotnet/cli/issues/7373

**Comment by badersur** [comment]
Hi @wli3. I'm using 16.10 feeds because I didn't see specific feeds for 17.04 which seems to be fine. I'm using 16.04 feed for MS SQL!

After trying the script, I get **2.0.0-preview3..** when passing **release/2.0.0** and **2.0.0-preview2..** when passing **release/2.0**!! I've tried several channels but couldn't find a way to obtain latest 2.1 bits.

I was upset when I read that the feed is unhealthy so I changed my mind and decided to download the Linux x64 binary and spent my day writing a [script to automate this](https://github.com/badersur/dotnet-manager).

Strangely, I can't run dotnet commands on Travis! It complains about a shared library.. I'll reproduce on Travis if necessary.

**Comment by wli3** [comment]
sorry for the confusion @badersur 

for the past several month, branch **release/2.0.0** is keep syncing with **master** to have latest bites. However, if you can use

```
./cli/scripts/obtain/dotnet-install.sh  --channel master
```

to get master's artifact, which has the branding 2.1.0

Also, there are still some prerequisite packages. I think you will need to run. (how **I** test on my Ubuntu machine).  [Required by](https://github.com/dotnet/core-setup)

```
sudo apt-get install curl libunwind8 gettext liblttng-ust0 libcurl3
```

And I am still working on the feed, latest update https://github.com/dotnet/cli/pull/7384

**Comment by badersur** [comment]
Hello @wli3 and no need to be sorry! I was thinking about writing a script to automate downloading the tarball for a while but I was happy with apt-get preview releases for .NET Core 1.1. After switching to Core 2, I wanted to live on the bleeding edge :)

I was thinking that I need to clone the repo and keep it in sync, but it turn out that I can use curl directly:

```
curl https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh | bash -s -- -c master -verbose
```

I had a look at https://github.com/dotnet/cli/blob/master/Documentation/specs/cli-installation-scenarios.md#installation-script-features but didn't see that I can pass the branch name for the `channel` parameter.

After trying the script again, I was able to get the latest bits but I'm missing some features:

* a progress bar showing my internet speed and how long it will take to download the tarball
* adding dotnet's directory to the PATH in my shell profile (i.e. ~/.bashrc)

Regarding Travis, I think it was complaining about `libunwind8` package..

I like to avoid using apt-get a lot, and I don't think I'll be using the feed because I'll have to run:

```
sudo apt-get update
apt-cache search dotnet | grep 2.1
sudo apt-get install the-new-package
```

I'll be using my script until you figure out how to achieve your goal of downloading several versions of dotnet side-by-side using one command :)
