### ISSUE TITLE
Missing command line option nodeReuse

### ISSUE THREAD

**Issue by GeraldBauerImplan** [dotnet/cli#7363]
According to documentation https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference the switch statement /nodeReuse should be available but is not.

## Steps to reproduce
Go to command line and type in "dotnet msbuild /nodeReuse:False <enter>"

## Expected  behavior
To process and build the project/solution

## Actual behavior
MSBUILD : error MSB1001: Unknown switch.
Switch: /nodeReuse:

## Environment data
`dotnet --info` output:

**Comment by omajid** [comment]
Fwiw, `dotnet msbuild /help` says nothing about `nodeReuse`.

**Comment by dasMulli** [comment]
node reuse is not supported on .NET Core msbuild. For the command line switch see https://github.com/Microsoft/msbuild/issues/1135

**Comment by livarcocc** [comment]
Closing, since this is already tracked in msbuild and needs to be enabled there.
