### ISSUE TITLE
Visual studio publishes project but dotnet publish does not

### ISSUE THREAD

**Issue by timatclout** [dotnet/cli#7366]
I am using Visual Studio community edition 2017 and dotnet 1.0.4 on a machine running Windows Server 2016 Data Center.

## Steps to reproduce

When I publish my project in Visual Studio to C:\TMP\foo, all of the files needed for running the application on another machine are included. 

When, from the command line, I dotnet publish myproject.sln -o C:\TMP\foo, the logo appears on the screen but nothing is written to C:\TMP\foo. Checking the exit status with echo $? returns True.

## Expected  behavior

I am expecting the publication files to be placed in C:\TMP\foo

## Actual behavior

C:\TMP\foo is empty

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
PS C:\Users\Administrator\Documents\Sandbox\clout-v1.5-admin>

**Comment by lampersky** [comment]
@timatclout do you have an example project that reproduces this?

I've checked on my "simple web app" project and everything is working fine, I've found "dotnet publish" products in specified directory.

>  the logo appears on the screen

what do you mean ? This is my output, I can't find any logo.

![screen](https://user-images.githubusercontent.com/6403130/29082717-9f71b5ea-7c66-11e7-838e-2698867066a0.png)

**Comment by timatclout** [comment]
By logo, I referred to the following text:

Microsoft (R) BuildEngine version 15.1.102.6693
Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by lampersky** [comment]
Please double check your solution file.
I've found that this is possible when *.sln file has no project reference.

![capture2](https://user-images.githubusercontent.com/6403130/29164500-dfd40f2a-7dbf-11e7-8e60-f9aaddaf84d4.JPG)

**Comment by timatclout** [comment]
Thanks for the reply, lampersky. The csproj file is too large to paste here, but it begins with the following lines: 

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

And the final line in the file is:

</Project>

**Comment by timatclout** [comment]
Thanks for the reply lampersky. The .csproj file is too large to past here, but here is a screenshot of the first two lines:

![capture](https://user-images.githubusercontent.com/29556946/29197191-6d9d96d6-7dee-11e7-992a-d71fedf29147.PNG)

**Comment by livarcocc** [comment]
I can't repro this either.
Please double check @lampersky's suggestion about making sure that your sln file has project references inside of it before publishing.
Also note that when adding projects in VS to a solution, the solution is not saved automatically, you have to save the solution through the save all file, and then the CLI can see those changes.

**Comment by livarcocc** [comment]
Closing as there hasn't been activity here in a while. If this still repros, please comment with additional information and we will re-activate.
