### ISSUE TITLE
Package reference to NETStandard.Library should be implicit

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#737]
When a project file targets 'netstandardX.Y' we should implicitly include a dependency on NETStandard.Library X.Y.0 (potentially prerelease).

**Comment by blackdwarf** [comment]
@ericstj can you add a sample project.json here that shows how would that look?

**Comment by ericstj** [comment]
Here is the simplest project.json.
```
{
  "frameworks": {
    "netstandard1.3": {},
  }
}
```
There's likely some more design work here.  If less than the minimum version of NETStandard.Library use the minimum version.  If a dependencies section exists should the implicit dependency be added to that section or not used at all.  Etc.

The general feeling is that the following seems redundant:
```
{
  "frameworks": {
    "netstandard1.3": {},
  },
  "dependencies": {
    "NETStandard.Library": "1.0.0-rc2-12345"
  }
}
```

**Comment by ericstj** [comment]
@blackdwarf this should probably go to someone working on NuGet in the CLI.  If we have an implicit package based on TFM that needs to be consistent with NuGet.  I'd like to see this be part of the framework definition file.

/cc @blackdwarf @yishaigalatzer @davidfowl

**Comment by blackdwarf** [comment]
@ericstj is this a nuget cli feature? Should it then go to nuget repo?

**Comment by ericstj** [comment]
I suppose that depends on the implementation.  Ideally this is nuget functionality so you get the same behavior from VS/MSbuild and DotNet-cli.

**Comment by piotrpMSFT** [comment]
This should be done in NuGet. If @yishaigalatzer needs then we can temporarily build it into CLI.

**Comment by yishaigalatzer** [comment]
I don't think we should build it for RTM. "Curb your enthusiasm"

About NuGet or CLI, I believe inferring default dependencies would be nice if the .NET CLI **brought** the standard library with it, and it wasn't a NuGet package that you need to reference at all. Looking at node.js you don't need to pull in anything to get going, I don't get why all the basic stuff is a package?

**Comment by ericstj** [comment]
Many of the packages that are referenced by default in standard library are standalone and can version independently.  In fact, that is one of the primary benefits we are driving towards in .NET core: a modular framework.  Coupling the libraries that are referenced by default with things that **must** come with the CLI is plain wrong and goes against this business goal.

The CLI does bring these packages with it.  If you're running on the platform you're building on you'll use the same packages that the CLI itself runs on.  I've discussed with @piotrpMSFT that we need to make sure that the CLI doesn't hit the internet to download these packages it already has and I believe work is planned. 

The CLI could choose to provide some default set of references if the NETStandard.Library package was missing.  This would likely look like some pre-resolved lock files for each TFM where we wanted this experience. We could come up with some heuristic for using the default like no reference to NETStandard.* nor System.Runtime (explicit ref to S.R tells us you want to go ala-carte).  If we did this do you suppose we could use the same functionality in NuGet that flows project.jsons across project references to unify the default references with the project-local references?  Essentially you can think of it as an implicit project reference to NETStandard.Library.

**Comment by piotrpMSFT** [comment]
This will be fixed in SDK repo via https://github.com/dotnet/sdk/pull/450
