### ISSUE TITLE
dotnet missing versions of GLIBCXX (OpenSuSe 11.3) 

### ISSUE THREAD

**Issue by carlosm2011** [dotnet/cli#7376]
Hi.
This is what I get when running any dotnet command (launching):

[root@user lib64]# dotnet 
dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by dotnet)

These are the lines contained in usr/lib64

[root@user lib64]# strings libstdc++.so.6|grep GLIBC

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH

## Steps to reproduce
run any dot net core

## Expected  behavior
run the app

## Actual behavior
Doesn't run the app

**Comment by omajid** [comment]
https://en.opensuse.org/Archive:Portal:11.3 says:

> The support for openSUSE 11.3 ended January 20th 2012

Do we really want to support something that has been EOL for 5 years?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#2990
