### ISSUE TITLE
List of supported properties

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#7388]
Is there a list of supported properties `/p:key=value` ? I just randomly get some information about what I can supply there. For instance, `/p:Version=value`... which was actually never supported in MSBuild, am I right? Also there is `/p:PackageVersion` (at least in MSBuild)... so it's a bit confusing to me.

**Comment by wli3** [comment]
Hi Matkoch,

Properties are either come from MSBuild or overriding existing property from SDK like this folder (https://github.com/dotnet/sdk/tree/master/src/Tasks/Microsoft.NET.Build.Tasks). 

In this case, it is not recommended to override unless you understand it properly as in the targets file header

```
WARNING:  DO NOT MODIFY this file unless you are knowledgeable about MSBuild and have
          created a backup copy.  Incorrect changes to this file will make it
          impossible to load or build your projects from the command-line or the IDE.
```

**Comment by matkoch** [comment]
@wli3, sorry but this is not exactly what I was asking for. I'm looking for a complete list of meaningful properties, that can be applied from outside. For instance like [Pack with MSBuild](https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target), but this is also rather incomplete.

**Comment by dasMulli** [comment]
@matkoch 

> Am I wrong that those values can also be supplied via dotnet pack ?

Yes `dotnet pack` allows you to specify arbitrary msbuild parameters to override things defined in the project.

> Is there a list […]

There is at least an issue on the docs repo about collecting useful stuff: https://github.com/dotnet/docs/issues/2642

**Comment by matkoch** [comment]
@dasMulli thank you! That's what I was looking for :)
