### ISSUE TITLE
dotnet-1.1.2 doesn't work on Fedora 26

### ISSUE THREAD

**Issue by arrkaye** [dotnet/cli#7391]
## Steps to reproduce
Tried to use the Fedora 24 instructions but 
get the below error.

## Expected  behavior
dotnet should run.

## Actual behavior
Error message:
_Failed to initialize CoreCLR, HRESULT: 0x80131500_

## Environment data
Fedora 26 64bit

**Comment by omajid** [comment]
Probably a variant of https://github.com/dotnet/cli/issues/4865

Some of us Fedora folks are hoping to maintain known good packages (currently 2.0 Preview 2) for Fedora here: https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/

**Comment by arrkaye** [comment]
Thanks for the reply. I've seen that copr repository and have successfully installed that.

Problem is that our code base is on 1.1.2 and doesn't work with Rider on 2.0. Rider doesn't properly support 2.0 either, so its not great.

**Comment by livarcocc** [comment]
I assume we can then close this issue? If I got it wrong, please, re-activate.
