### ISSUE TITLE
dotnet-install.sh prints text out of order (escaping issue?)

### ISSUE THREAD

**Issue by badersur** [dotnet/cli#7392]
## Steps to reproduce
Run the script twice!
`./scripts/obtain/dotnet-install.sh -c master`

## Expected  behavior

A clear message:
```
SDK version 2.1.0-preview1-007018 is already installed.
dotnet-install: Adding to current process PATH: `/home/badersur/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
```

## Actual behavior

```
 is already installed.DK version 2.1.0-preview1-007018
dotnet-install: Adding to current process PATH: `/home/badersur/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Installation finished successfully.
```

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.0-preview1-007018)

Product Information:
 Version:            2.1.0-preview1-007018
 Commit SHA-1 hash:  6a64e17857

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/badersur/Downloads/dotnet/sdk/2.1.0-preview1-007018/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by badersur** [comment]
As usual, I remembered that I've seen a similar behaviour *after* reporting the issue!

It seems like there's an extra carriage return in the variable `specific_version`.

To check and fix this, I added:

```
echo "$specific_version" | od -c
specific_version=$(echo "$specific_version" | sed 's/\r$//')
```

to the first `if` statement inside `install_dotnet` function... and [shellcheck](https://github.com/koalaman/shellcheck/) isn't happy about my echo!

**Comment by johnbeisner** [comment]
@badersur 
The install-scripts have been updated and are available at this location:
https://dot.net/v1/dotnet-install.sh (bash, UNIX)
https://dot.net/v1/dotnet-install.ps1 (powershell, Windows)

**Comment by badersur** [comment]
Hello @johnbeisner and thanks for fixing this issue but I'm trying to test your changes and the script doesn't seem to work!

I tried cloning the repo and running these:
./scripts/obtain/dotnet-install.sh -c master

./scripts/obtain/dotnet-install.sh -c 2.1

./scripts/obtain/dotnet-install.sh

then:
curl https://dot.net/v1/dotnet-install.sh | bash -s -- -c master

curl https://dot.net/v1/dotnet-install.sh | bash

but none of these work! I don't see any output at all. Am I missing something?! I'm using Ubuntu 17
