### ISSUE TITLE
Build produces file names too long to be deleted

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#7395]
Recently enlisted and performed the following:

1. Ran `build.cmd` 
2. Ran `git clean -dxf .`

The latter command failed with the following error message for a number of files:

> warning: Could not stat path 'test/dotnet.Tests/bin/Debug/netcoreapp2.0/.cctor/Dotnet_first_time_experience_tests/nuget_home/.dotnet/NuGetFallbackFolder/system.security.cryptography.x509certificates/4.3.0/ref/netstandard1.3/zh-hant/System.Security.Cryptography.X509Certificates.xml': Filename too long

My enlistment is on a very short path: `e:\code\cli` hence that doesn't seem to be the issue. 

Why is CLI producing these files that can't be deleted? How can I delete these files? At this point my enlistment is pretty much busted.

**Comment by jaredpar** [comment]
The best work around I could find for this is [the following](https://superuser.com/a/467814)

``` cmd
mkdir empty_dir
robocopy empty_dir the_dir_to_delete /s /mir
rmdir empty_dir
rmdir the_dir_to_delete
```

This feels very broken. It means the default experience is I can't use a host of commands I would expect to use:

- git clean
- rm -re -fo 
- rmdir / s

**Comment by livarcocc** [comment]
Have you tried git config --system core.longpaths true? We have in the past, found the descriptive names to be more helpful and that running the command above fixes the clean problem for us.

**Comment by livarcocc** [comment]
Let me know if the git config work around above does not work for you.
