### ISSUE TITLE
The self contained build executable , can only using 1 cpu core 100%

### ISSUE THREAD

**Issue by netroby** [dotnet/cli#7397]
Hello, I am try to benchmark aspnetcore . I tried dotnet run mode, and build the project into self contained executable .

I found the self contained build runs faster than the default dotnet run.

But the cpu usage was not the same .

By running dotnet run , all my cpu core can reach 100%. i have 4 cpu core.

But execute the self contained executable , only 1 cpu can reach 100%. the other 3 not .

the bench result list as following

### Nginx + php with fpm mode
```
$ wrk -t12 -c400 -d30s http://local.domain.com/test.php
Running 30s test @ http://local.domain.com/test.php
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   105.36ms   91.64ms   1.16s    97.57%
    Req/Sec   347.90     53.60     1.82k    87.00%
  123756 requests in 30.10s, 26.31MB read
Requests/sec:   4112.00
Transfer/sec:      0.87MB
```
### ASP .net core
```
$ wrk -t12 -c400 -d30s http://127.0.0.1:5000
Running 30s test @ http://127.0.0.1:5000
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    40.30ms   85.06ms 661.01ms   92.35%
    Req/Sec     1.90k     0.85k    4.63k    73.02%
  671031 requests in 30.09s, 78.71MB read
Requests/sec:  22298.28
Transfer/sec:      2.62MB
```
### ASP .net core self contained build
```
$ wrk -t12 -c400 -d30s http://127.0.0.1:5000               
Running 30s test @ http://127.0.0.1:5000
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    17.79ms   17.43ms 273.90ms   82.50%
    Req/Sec     2.19k   613.12     6.38k    74.39%
  784136 requests in 30.10s, 91.98MB read
Requests/sec:  26054.21
Transfer/sec:      3.06MB
```
To build self contained
```
dotnet publish -f netcoreapp2.0 -r centos.7-x64 --self-contained
```

**Comment by livarcocc** [comment]
@mlorbetske is the web app multi-threaded by default?

I wonder if the multi-cpu usage you see during dotnet run is because of the restore/build process that runs as part of dotnet run itself, rather than your app.

**Comment by mlorbetske** [comment]
+ @eilon

**Comment by netroby** [comment]
i am watching the work load during the benchmark runing. 

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Eilon** [comment]
@netroby can you share your app's code + instructions to run it so that we can take a look? All ASP.NET Core apps are multi-threaded by default and will used pretty much all available resources to run the app.

Though, I should note that regardless of any of that, it looks like you're already getting significantly higher perf from ASP.NET Core than the other frameworks 😄 

cc @davidfowl @mikeharder

**Comment by netroby** [comment]
Ok, i got it .

The benchmark more better now. now .net issue.
