### ISSUE TITLE
dotnet sln add doesn't seem to work with globs

### ISSUE THREAD

**Issue by TB-Andrew** [dotnet/cli#7404]
Hey there! I am having an issue with the `dotnet sln [<SOLUTION_NAME>] add <GLOBBING_PATTERN>` command. While I can add individual projects to the solution by passing the individual csproj files to the add command, it will not work with a glob [as dictated in the docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln).

## Steps to reproduce
1. Create a sln with dotnet cli
1. Create multiple sub projects using dotnet cli
1. Attempt to add projects in sub directories to the CLI using the `dotnet sln CoreTestApi.sln add **/*.csproj` (as I am on Windows, I have also tried **\\*.csproj)

## Expected  behavior

Projects in sub directories should be added to the solution.

## Actual behavior

Cli emits red error text `Project **/*.csproj does not exist`

## Environment data

.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

**Comment by livarcocc** [comment]
I noticed that you are on Windows. Globbing is only supported on Unix based operating systems, because on those systems, the shell itself is expanding the glob and passing that to the application. That is not the CLI evaluating the globbing.
