### ISSUE TITLE
Issues with .NET Native Compiler and UWP Store Ingestion

### ISSUE THREAD

**Issue by CMartino-195** [dotnet/cli#7412]
## Steps to reproduce
When compiling our application with Microsoft.NETCore.UniversalWindowsPlatform target version 5.3.3, it includes as a dependency Microsoft.Net.Native.Compiler version 1.6.3. The application compiles correctly without any issues, can also side-load the application to UWP devices and runs without issue. 

When attempting to submit the application to the store however it fails with the error 1201. If the application is build targeting Microsoft.NETCore.UniversalWindowsPlatform  version 5.2.2 however it will be accepted by the UWP store ingestion process without issue, the issue is with the native compiler version 1.6.3, as the compiler distributed with the UWP SDK allows the package to be submit without error.

## Expected  behavior
Ability to compile solution with package Microsoft.NETCore.UniversalWindowsPlatform (5.3.3) with dependency Microsoft.Net.Native.Compiler version 1.6.3 and submit application package to the store without encountering error 1201.

## Actual behavior
When building with the package Microsoft.NETCore.UniversalWindowsPlatform (5.3.3) with dependency Microsoft.Net.Native.Compiler version 1.6.3 and submit application package to the store it is encountering error 1201, however does not encounter this issue when compiling with 5.2.2 and the ilc compiler supplied with the SDK.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by CMartino-195** [comment]
Update - issue acknowledged by .NET team, will be fixed in next release.

**Comment by livarcocc** [comment]
This issue does not belong on this repo. Given that it is already being handled though, I am closing it.
