### ISSUE TITLE
Chaining `dotnet publish` and `publish-iis`

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#742]
For Asp.Net projects the output of `dotnet publish` needs to be tweaked a little bit to enable the project to run on IIS. The crucial part is to modify (or create) the web.config file. 

The idea is to create a tool (project tool) which will run after dotnet publish. The tool will take the folder where the project was published and the application name as parameters.

Open questions are: 
- how to chain the tool to run after `dotnet publish`
- where to get the parameter values from - (it might be possible to get the application name by parsing project.json file but the output folder can be provided by the user so it needs to be provided)

/cc @glennc

**Comment by davidfowl** [comment]
It's going to be in the post publish script. We need to discuss the context we have at that point though

**Comment by moozzyk** [comment]
IS post publish working yet? I think I tried it a couple day ago and it was not invoked.
