### ISSUE TITLE
Unable to find/add 'System.Web' to .NetCoreApp 1.1 project

### ISSUE THREAD

**Issue by littleKing82** [dotnet/cli#7425]
I migrated my `.Net 4.5 Framework` based Project to `.NetCoreApp 1.1`.
However i am unable to find the following name spaces/assemblies?
I tried to find them at the following path but no success.

**Path:**
`C:\Program Files\dotnet\sdk\1.0.4'

For example, `System.Web` does not exist at above path. 

System.Web.Security    
System.Web

## Environment data
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by davidfowl** [comment]
There is no System.Web in .NET Core.

**Comment by littleKing82** [comment]
@davidfowl thanks, i seem to be so stupid ;)
