### ISSUE TITLE
Incorrect file & folder ownership for Linux binaries

### ISSUE THREAD

**Issue by benscobie** [dotnet/cli#7435]
## Steps to reproduce
Follow the .NET Core 2.0 Debian install instructions here: https://www.microsoft.com/net/core#linuxdebian

> sudo apt-get install curl libunwind8 gettext
> curl -sSL -o dotnet.tar.gz https://aka.ms/dotnet-sdk-2.0.0-linux-x64
> sudo mkdir -p ~/dotnet && sudo tar zxf dotnet.tar.gz -C ~/dotnet
> sudo ln -s ~/dotnet/dotnet /usr/local/bin

## Expected  behavior
I expected the files and folders to be owned by the user that extracted the archive.

> Note, a user-controlled directory must be used when installing from tar.gz on Linux systems. 

This statement makes it sound like they should be owned by the user that extracted the archive. In which case, is there any reason to use sudo for the directory creation and archive extraction? In most cases the users home directory should be owned by themselves, no?

## Actual behavior
The dotnet folder and all objects underneath are owned by an invalid user (1002) and the 'sudo' group. See image: http://i.imgur.com/MhJvISU.png

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/ben/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by wli3** [comment]
Hi @benscobie 
Thank you for the issue. The instruction is incorrect, we are fixing the instruction.

In the meanwhile, you can extract the tar ball in the home directory without sudo and add that directory to path and to your ~/.bashrc or your default shell profile

https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

**Comment by omajid** [comment]
The new instructions on https://www.microsoft.com/net/core#linuxdebian are:

> mkdir -p ~/dotnet && sudo tar zxf dotnet.tar.gz -C ~/dotnet
> export PATH=$PATH:$HOME/dotnet

Which looks much better to me, except the `sudo` serves no purpose.

**Comment by wli3** [comment]
@omajid

you are right, there is no sudo needed

**Comment by wli3** [comment]
The instruction is fixed
