### ISSUE TITLE
Better RPM package versioning to prevent 2.0.0-preview > 2.0.0

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#7438]
Currently yum/dnf update visibility rules are causing the preview package to hide GA. A test with the azlinux folks has shown that updating the epoch field will resolve the issue. 

This needs to be done in release/2.0.0 and master

cc @rakeshsinghranchi, @nguerrera 

Background: 
* https://www.redhat.com/archives/rpm-list/2000-October/msg00075.html
* http://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/

**Comment by omajid** [comment]
Ouch. Sorry about not catching this. Please consider that Epoch is a big hammer that might have longer term consequences too. For example, OpenJDK RPM [has had to keep an epoch for 10 years](http://pkgs.fedoraproject.org/rpms/java-1.8.0-openjdk/blob/master/f/java-1.8.0-openjdk.spec#_804).

**Comment by wli3** [comment]
No longer needed

**Comment by wli3** [comment]
Update name for solving the root cause.

**Comment by wli3** [comment]
http://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/

**Comment by wli3** [comment]
https://github.com/rpm-software-management/rpm/blob/master/lib/rpmvercmp.c

**Comment by wli3** [comment]
@leecow any progress on this issue?

**Comment by leecow** [comment]
Not from my end. We (the engineering team) need to investigate how to enable proper package version representation such that apt-get update / dnf update appropriately determine if updates are available. A random example:

```
sudo dnf list util-linux
Last metadata expiration check: 0:07:01 ago on Mon 25 Sep 2017 04:58:44 PM EDT.
Installed Packages
util-linux.x86_64                                                   2.30.1-1.fc26                                                   @updates
Available Packages
util-linux.i686                                                     2.30.2-1.fc26                                                   updates 
```

We need to fix our package authoring (deb and rpm) such that we are making proper use of the version fields and enable the update scenario. eg after we ship 2.0.n, `sudo dnf check-update dotnet-sdk` on a 2.0.0 machine will report that `2.0.n` is an available package. 
 

/cc @rakeshsinghranchi

**Comment by RheaAyase** [comment]
I'd like to pitch in and suggest a perfect solution, as dotnet-sig lead on Fedora.
Stop building your packages and point to ours instead.
**=)**

---

To install dotnet on Fedora, built on Fedora, by Fedora (RedHat) people:
`$ sudo dnf copr enable @dotnet-sig/dotnet`
`$ sudo dnf install dotnet-sdk-2.0` (or runtime, etc)

Makes everything simple. `dnf update` does it's job, etc...

Note that copr is a temporary solution until source build works properly and we are able to package dotnet _the open-source way._ After we achieve that goal, it will be as simple as `dnf install dotnet` for example.

**Comment by omajid** [comment]
Does this issue also affect other distributions like Ubuntu?

**Comment by wli3** [comment]
We currently mitigated it by not publish preview
