### ISSUE TITLE
dotnet publish failed

### ISSUE THREAD

**Issue by fofewyoung** [dotnet/cli#7443]
## Steps to reproduce
dotnet new console
dotnet publish -r win7-x64

## Expected  behavior
generate bin folder that placed dlls

## Actual behavior
it is just dead. i guess it restore timeout

ps:
1. dotnet build/run  work well
2.when i uninstall  dotnet-sdk-2.0.0-win-x64.exe,   everything is ok (downgrade to .net core sdk 2.0 preview2)

## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by John0King** [comment]
I have the same issure
`C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(102,5): error : Failed to retrieve information about 'runtime.win-x64.Microsoft.NETCore.App' from remote source 'C:\Users\<userName>\.dotnet\NuGetFallbackFolder'. [E:\AllProjects\NetCore\webApp2\webApp2\webApp2.csproj]`

seems like the SDK will always use NugetFallbackFolder ( It is a wrong path , the rigth path is C:\Program Files\dotnet\sdk\NuGetFallbackFolder  ) and not use nuget as second package source.

and even I  use `dotnet restore -s  https://api.nuget.org/v3/index.json`  ( I already put `<RuntimeIdentifier>win10-x64</RuntimeIdentifier>` in my project ), I still can not publish a self-contaned application

**Comment by fofewyoung** [comment]
hi, i fixed this by add a local packageSources in NuGet.Config

**Comment by John0King** [comment]
@fofewyoung Maybe you should reopen it , I can't get it work with VS2017.3  ， I had to use `nuget restore -s <url>` to  restore packages
