### ISSUE TITLE
dotnet new template should not expose public types

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/cli#745]
The "new" template exposes a public type with a public method:

```C#
public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
```
These should not be public. 

Also, maybe we should remove the namespace once there are no public types. it will simplify our "hello world"

**Comment by davidfowl** [comment]
What does that matter for a console app.....

**Comment by KrzysztofCwalina** [comment]
It's bad to expose APIs accidentally from dlls or exes. Our template should not lead people to the wrong thing, i.e. expose accidental APIs.

**Comment by blackdwarf** [comment]
@KrzysztofCwalina what about if we want to drop a library template? `public` by default? I.e.:

```csharp
namespace Bla {
    public class Stuffz {
    }
}
```

**Comment by piotrpMSFT** [comment]
having main be public, or atleast internal, is pretty convenient for testability. We don't have great utilities for testing CLIs... More than one way to address that problem, tho...

**Comment by KrzysztofCwalina** [comment]
@blackdwarf, yeah, for library templates (if we have any), we can do public class.

@piotrpMSFT, I think people test apps not by calling the main, but rather by calling APIs exposed by various types in the app.
