### ISSUE TITLE
There is no way to make an application to run as admin by default

### ISSUE THREAD

**Issue by japm48** [dotnet/cli#7452]
I'm trying to get an always-admin executable with .net Core. I'm new to this, so please bear with me.

---------------

The "published" executable doesn't contain the application manifest I specified in the csproj file, instead that manifest is embedded in the DLL. This means that there is no way to always request elevation via UAC prompt.

This has been checked with the following commands executed in a WSL console:

Command: `strings ConsoleApp1.exe | grep requestedExecutionLevel`
Output: `<requestedExecutionLevel level='asInvoker' uiAccess='false' />`
Command: `strings ConsoleApp1.dll | grep requestedExecutionLevel`
Output: `<requestedExecutionLevel level='requireAdministrator' uiAccess='false' />`

## Reproduced with:

Build command:
`dotnet publish -r win10-x64`

C# code:
```C#
static bool isAdmin()
{
        return new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator);
}
```

.csproj contents:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <ApplicationManifest>app1.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Principal.Windows" Version="4.4.0" />
  </ItemGroup>
</Project>
```

## Environment data:
`dotnet --info` output:
<details>
  <summary>Click to expand</summary>

```
Herramientas de la línea de comandos .NET (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
</details>

**Comment by vcsjones** [comment]
That's an interesting problem.

With .NET Core executables, `dotnet build` does not produce an executable, and `dotnet app.dll` does not use the executable, so I can see why it's going in a DLL and not the published EXE. It would be a bit of a split in behavior where the published EXE has a different behavior than `dotnet run`.

There are two solution that I think can help, for now.

1. Use a program that does require admin access to bootstrap your executable. You could write this boostrapper in .NET Framework, or native code.

1. [Use `al.exe` or `mt.exe`](https://stackoverflow.com/questions/1423492/how-do-i-add-a-manifest-to-an-executable-using-mt-exe) from the .NET Framework SDK to re-embed the manifest in the published executable as a post-publish step in your build process.

I realize the latter step required the .NET Framework SDK, which seems a bit anti-dotnet-core, but given that your task is Windows-specific, it doesn't seem too bothersome.

**Comment by Genbox** [comment]
+1 this is a pretty important feature.

**Comment by jjxtra** [comment]
If you are doing a pre-compiled .net core build for Windows, it seems like it should honor the app.manifest, since it knows the target is Windows. This would be great to have as default behavior.

**Comment by livarcocc** [comment]
This is something that the host would have to honor. I will move it to core-setup for further discussion.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#4654
