### ISSUE TITLE
CLI install documentation points to wrong URL for known issues on MacOS

### ISSUE THREAD

**Issue by rjmiller** [dotnet/cli#7453]
## Steps to reproduce
Visit https://www.microsoft.com/net/core#macos, then click the link that says "known issues page" which sends you to https://github.com/dotnet/core/blob/master/cli/known-issues.md which returns a 404.

## Expected  behavior
Documentation needs to be updated to point to the correct URL, I would do it myself, but this link is on Microsoft.com domain and not in docs.microsoft.com which I could edit with a pull request.

## Environment data
`dotnet --info` output:

**Comment by wli3** [comment]
@leecow could you help me with this? It should update to a document in https://github.com/dotnet/core/tree/d43f4090336cbb3acfec16ae4f20b8cf513b68d2/release-notes

**Comment by leecow** [comment]
Thanks @rjmiller. Fixed - updated the link to point to our release notes toc so that it will be a bit more resilient.
