### ISSUE TITLE
Use SpecialFolder.LocalApplicationData for the "RuntimeDataRoot" directory under Linux

### ISSUE THREAD

**Issue by japm48** [dotnet/cli#7463]
This path is hard-coded here:
https://github.com/dotnet/cli/blob/85ca206d84633d658d7363894c4ea9d59e515c1a/src/dotnet/MulticoreJitProfilePathCalculator.cs#L54

Ideally under Linux, the XDG specification should be followed and use `Environment.GetFolderPath(SpecialFolder.LocalApplicationData)`, as this is already implemented in `corefx`:

https://github.com/dotnet/corefx/blob/76d2ed0bb6d07b4e03cd01c6f1402328ed62f0e1/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L95

Maybe using `SpecialFolder.LocalApplicationData` is also valid on Windows?

If this is considered not acceptable I would like, at least, to be able to specify that location via an environment variable.

**Comment by livarcocc** [comment]
I am going to dup this to https://github.com/dotnet/cli/issues/8053, where we are having a discussion very similar to this one.
