### ISSUE TITLE
Package broken on ubuntu 16.04

### ISSUE THREAD

**Issue by nathanaeljones** [dotnet/cli#7475]
## Steps to reproduce

1. Install key and feed with `curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg` and `sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg` and `sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'`
2. Remove preview packages using `apt list --installed  | grep dotnet` and ` sudo apt-get remove dotnet-dev-1.0.0-preview2-1-003177 sudo apt-get remove dotnet-dev-1.0.0-preview2-1-003177` and  `sudo apt-get remove dotnet-host`
3. Update feeds with `sudo apt-get update`
4. Attempt to install sdk with `sudo apt-get install dotnet-sdk-2.0.0`
5. Attempt to install runtime with `sudo apt-get install dotnet-runtime-2.0.0`
## Expected  behavior

Dependencies should be installable. 

## Actual behavior

```
$sudo apt-get install dotnet-sdk-2.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.0.0 : Depends: dotnet-runtime-2.0.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

```
$sudo apt-get install dotnet-runtime-2.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.0.0 : Depends: liblttng-ust0 (>= 2.5.0) but 2.4.0-4ubuntu1 is to be installed
                        Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
## Environment data
`dotnet --info` output:

N/A, no dotnet installed

`dpkg --get-selections | grep hold` reports no held packages.

**Comment by nathanaeljones** [comment]
It appears that libicu52 and libttng-ust0 2.4.0-4ubuntu1 are standard on Ubuntu 16. Perhaps the wrong build got published?

**Comment by nathanaeljones** [comment]
Oops. I'm running Ubuntu 14.04, not 16.04.

**Comment by polarbit** [comment]
Hi, what was the your problem & solution ? I experienced same issue. But my ubuntu version 16.10. 

I tried to install dotnet-sdk-2.0.0 and received same error with you.
Then tried to install dotnet-runtime-2.0.0 ; this time  apt-get says libicu55 not found or broken .

Then I added below line to /etc/apt/sources.list
deb http://security.ubuntu.com/ubuntu xenial-security main 
W.r.t. package here: https://packages.ubuntu.com/xenial/amd64/libicu55-dbg/download 

And re-run apt-get install dotnet-sdk-2.0.0 and be successful.
But currently, I did not understand what is the reason. Was my system broken, or package itself is broken ?

If anybody can look into outputs below and give some comments, it will be very helpful.

ERRORS & OUTPUTS: 

=== **apt-get update** =====
 sudo apt-get update
Hit:1 http://tr.archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://tr.archive.ubuntu.com/ubuntu yakkety-updates InRelease        
Hit:3 http://tr.archive.ubuntu.com/ubuntu yakkety-backports InRelease   
Hit:4 http://security.ubuntu.com/ubuntu yakkety-security InRelease      
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:6 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease
Hit:8 https://download.docker.com/linux/ubuntu yakkety InRelease
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [356 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [333 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [156 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/main amd64 DEP-11 Metadata [60,0 kB]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [57,0 kB]
Fetched 1.065 kB in 16s (65,9 kB/s)                                            
Reading package lists... Done
====================

=== **apt-get install dotnet-runtime-2.0.0** ====
sudo apt-get install dotnet-runtime-2.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.0.0 : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.
========================================

=== **libicu55 install error**  ===
sudo apt-get install dotnet-runtime-2.0.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-runtime-2.0.0 : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.
=========================================

==== **apt-cache search libicu** =============
sudo apt-cache search libicu
icu-devtools - Development utilities for International Components for Unicode
icu-devtools-dbg - Development utilities for International Components for Unicode (debug symbols)
libicu-dev - Development files for International Components for Unicode
libicu57 - International Components for Unicode
libicu57-dbg - International Components for Unicode (debug symbols)
libicu4j-4.2-java - Library for Unicode support and internationalization
libicu4j-4.4-java - Library for Unicode support and internationalization
libicu4j-49-java - Library for Unicode support and internationalization
libicu4j-java - Library for Unicode support and internationalization
libicu4j-java-doc - Library for Unicode support and internationalization - Docs
=================================================
