### ISSUE TITLE
Add package upgrade, version check

### ISSUE THREAD

**Issue by kjbetz** [dotnet/cli#7483]
Feature request.

Add command to upgrade packages and/or do a version check on packages used in `.csproj`

Suggest: `dotnet package upgrade` and/or `dotnet package check`

Make it interactive to be able to update `.csproj` 

Idea similiar to this: https://www.npmjs.com/package/npm-check

**Comment by kjbetz** [comment]
I was using yarn last night and saw that this is an included feature for them. `yarn upgrade` and `yarn upgrade-interactive` 

https://yarnpkg.com/lang/en/docs/cli/upgrade/

https://yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

Definitely very handy! Very much needed in my opinion for .NET Core CLI users.

**Comment by kjbetz** [comment]
I suggest a `dotnet package upgrade` and `dotnet package upgrade-interactive` or `dotnet package upgrade --interactive`

As well as some of the other features listed in the yarn... we used `--latest` and it was very handy as we use absolute/exact version numbers.

**Comment by livarcocc** [comment]
I believe there is an issue under nuget/home for this already. I will move this issue there and have them close this one as a dup if that's the case.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6054
