### ISSUE TITLE
.NET Core CLI not working if downloaded using steps from Microsoft Website

### ISSUE THREAD

**Issue by sunnystormy** [dotnet/cli#7487]
## Steps to reproduce
Everything works if you download .Net Core CLI from the main github page here. It doesn't work if you download it using the commands from the https://www.microsoft.com/net/core#linuxdebian website. Perhaps the MS website should be updated?

## Expected  behavior
.NET Core CLI should work.

## Actual behavior
It doesn't work and if you check the expected dependencies of the installation, it asks for packages that are several generations old.

## Environment data
`dotnet --info` output:

**Comment by wli3** [comment]
@sunnystormy thank you for the issue! However I cannot repo the problem from a clean Azure debian 8 VM https://azuremarketplace.microsoft.com/en-us/marketplace/apps/credativ.Debian?tab=Overview

![image](https://user-images.githubusercontent.com/6993335/29633527-650196dc-87fb-11e7-9fc7-b4382ae39982.png)

Also could you tell me more detail about "asks for packages that are several generations old". The Debian instruction is extracting an tarball, there is no explicit package requirement

**Comment by sunnystormy** [comment]
@wli3 The commands have been updated. When I first encountered this issue, it was before the official release of v2.0.0. This ticket is no longer valid.
