### ISSUE TITLE
dotnet add installs unlisted version if it is the latest

### ISSUE THREAD

**Issue by richardszalay** [dotnet/cli#7492]
## Steps to reproduce
```
dotnet new console -o hwapp
cd hwapp
dotnet add package RichardSzalay.MockHttp
```

## Expected  behavior
Version 1.5.0 (latest listed version) is installed

## Actual behavior
Version 3.0.0 (unlisted version) is installed

## Environment data
`dotnet --info` output:
```
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by richardszalay** [comment]
FWIW, `Install-Package` works as expected.

**Comment by wli3** [comment]
Hi @richardszalay thank you for the issue.

For the behavior you mentioned, there is an opposite issue https://github.com/NuGet/Home/issues/5069

I am waiting for the "designed behavior" from nuget

**Comment by wli3** [comment]
@richardszalay sorry for the delay, you are right, these 2 issues are the same. I am closing this one and only track it in NuGet/Home#5069
