### ISSUE TITLE
Unable to build .net 4.5 project with .NET Core 2.0 SDK

### ISSUE THREAD

**Issue by f0rt** [dotnet/cli#7494]
I'm using dotnetcli 2.0 (.zip edition) downloaded from here https://www.microsoft.com/net/download/core. I'm trying to build a .net 4.5 project on a clean windows 2016. I got the following error:

> Microsoft.Common.CurrentVersion.targets(1122,5):
 error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

Is this a bug or I should have some prerequisites installed?

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by wli3** [comment]
@f0rt I believe Windows 2016 don't have .NETFramework4.5 out of box. Could you try to install it from https://www.microsoft.com/en-us/download/details.aspx?id=30653

Also, dotnet sdk will not work on non SDK-style projects(the one need to list out all cs files)

**Comment by livarcocc** [comment]
Closing, since @wli3 have addressed the questions in this issue and we haven't had activity here in a while.

**Comment by wjkhappy14** [comment]
me too!

C:\Users\Administrator\Documents\SourceCode\Mvc\test\WebSites\SimpleWebSite>dotn
et test
Build started, please wait...
CSC : error CS1617: 选项“7.2”对于 /langversion 无效；必须是 ISO-1、ISO-2、默认
版本、最新版本或 1 到 7.1 范围内的有效版本。 [C:\Users\Administrator\Documents\S
ourceCode\Mvc\src\Microsoft.AspNetCore.Mvc.Analyzers\Microsoft.AspNetCore.Mvc.An
alyzers.csproj]
CSC : error CS1617: 选项“7.2”对于 /langversion 无效；必须是 ISO-1、ISO-2、默认
版本、最新版本或 1 到 7.1 范围内的有效版本。 [C:\Users\Administrator\Documents\S
ourceCode\Mvc\src\Microsoft.AspNetCore.Mvc.Abstractions\Microsoft.AspNetCore.Mvc
.Abstractions.csproj]
C:\Program Files\dotnet\sdk\2.0.0\Microsoft.Common.CurrentVersion.targets(1122,5
): error MSB3644: 未找到框架“.NETFramework,Version=v4.6.1”的引用程序集。若要解
决此问题，请安装此框架版本的 SDK 或 Targeting Pack，或将应用程序的目标重新指向已
装有 SDK 或 Targeting Pack 的框架版本。请注意，将从全局程序集缓存(GAC)解析程序集
，并将使用这些程序集替换引用程序集。因此，程序集的目标可能未正确指向您所预期的框
架。 [C:\Users\Administrator\Documents\SourceCode\Mvc\test\WebSites\SimpleWebSit
e\SimpleWebSite.csproj]

**Comment by livarcocc** [comment]
Please, file a new issue with repro steps or even better, a repro repo on github that we can clone and try it out.

**Comment by wjkhappy14** [comment]
install  the  dotnet-sdk-2.1.300-win-gs-x64.exe    ,then run the dotnet run   is ok
