### ISSUE TITLE
Install location is not in Ubuntu path

### ISSUE THREAD

**Issue by bassebaba** [dotnet/cli#7496]
## Steps to reproduce
1) Follow steps here: https://www.microsoft.com/net/core#linuxubuntu
2) At step (3), you get a "command not found"

## Expected  behavior
dotnet-binary should run

## Actual behavior
Dotnet is installed in /usr/share/dotnet/

Checking the default path-variable for Ubuntu 16.04, theres no /usr/share/... :
```
echo $PATH
/home/bassebaba/bin:/home/bassebaba/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

```
So running "dotnet" from bash won't work

## Solution
The binary should either be installed in, or symlinked, to one of the default locations in $PATH?

Manual solution is:
`sudo ln -s /usr/share/dotnet/dotnet /usr/local/bin/`

But I think this should be done by the installer?

**Comment by omajid** [comment]
Maybe @wli3 has an idea? He worked on the packages.

**Comment by wli3** [comment]
Hi @bassebaba
I just tried with a fresh Ubuntu 16.04 on Azure VM that is published by canonical. no repo. There is a symlink from /usr/share/dotnet to /usr/bin/dotnet after installation without extra command.

This package of the executable, dotnet-host, is maintained in core-setup. I'll move it there

**Comment by wli3** [comment]
This issue was moved to dotnet/core-setup#3078
