### ISSUE TITLE
dotnet test: filter expression without an operator isn't supported (Incorrect format)

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#7498]
[Documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore2x) for `dotnet test` says that filter can be just a string which is tread as `contains` for FullyQualifiedName property:

> An expression without an <operator> is automatically considered as a contains on FullyQualifiedName property (for example, dotnet test --filter xyz is same as dotnet test --filter FullyQualifiedName~xyz).

But it doesn't work.

## Steps to reproduce
```
dotnet test Tests.csproj --filter Croc.XFW3.Tests.Storage.SimpleCrudTests.CRUD --no-build
```

## Expected  behavior
Executes tests with filter `Croc.XFW3.Tests.Storage.SimpleCrudTests.CRUD` applied to FullyQualifiedName.

## Actual behavior
Error "Incorrect format". No tests are executed.
```
Starting test execution, please wait...
[xUnit.net 00:00:00.7174869]   Discovering: Croc.XFW3.Tests
[xUnit.net 00:00:01.3979244]   Discovered:  Croc.XFW3.Tests
[xUnit.net 00:00:01.4090900] Croc.XFW3.Tests: Exception filtering tests: Incorrect format for TestCaseFilter Error: Invalid Condition 'Croc.XFW3.Tests.Storage.SimpleCrudTests.CRUD'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
[xUnit.net 00:00:01.4605620]   Starting:    Croc.XFW3.Tests
[xUnit.net 00:00:01.5086361]   Finished:    Croc.XFW3.Tests
```

## Environment data
`dotnet --info` output:

D:\Work\R-n-D\XFW3\Sources\Foundation\Repo-netcore\Src\Tests>dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by wli3** [comment]
This issue was moved to Microsoft/vstest#1019
