### ISSUE TITLE
SecurityException: Unable to retrieve security descriptor for this frame.

### ISSUE THREAD

**Issue by blowdart** [dotnet/cli#7502]
_From @valcs007 on August 7, 2017 23:27_

Getting this  below error in my ASP.Net Core 1.1 app/IIS 8.

Tried to impersonate @ middleware level but ran into various issues, so trying to impersonate as a actual windows user instead of IIS app pool user @ the controller level.

Have this below code in my controller
```  c#
 public class SearchController : Controller
    { 
.......
            var winIdent = HttpContext.User.Identity as WindowsIdentity;
            if (winIdent != null)
            {                
                 WindowsIdentity.RunImpersonated(winIdent.AccessToken, () =>
                {
                    numMatches = shim.GetNumMatches(scm);
                });
            }
.................
}
```

**Error:**
SecurityException: Unable to retrieve security descriptor for this frame.

Any help will be appreciated.;

_Copied from original issue: aspnet/Identity#1349_

**Comment by wli3** [comment]
@valcs007 could you share the project or a minimal repro? There is really too little information.

It could be a dll resolving problem, what is the `shim` instance?

**Comment by livarcocc** [comment]
Given the lack of information, I am closing this issue. Besides, this probably belongs in the CoreFX repo.
