### ISSUE TITLE
dotnet sln add <project> throws segfault

### ISSUE THREAD

**Issue by suvl** [dotnet/cli#7505]
## Steps to reproduce
I've ran `dotnet sln Sib.sln add src/Sib.Console.DataLoader/Sib.Console.DataLoader.csproj`
where the csproj is: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <StartupObject>Sib.Console.DataLoader.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="musicians.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

``` 

## Expected  behavior
Well, project gets added to the solution I believe.

## Actual behavior
`$ dotnet sln Sib.sln add src/Sib.Console.DataLoader/Sib.Console.DataLoader.csproj 
Segmentation fault
`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     deepin
 OS Version:  15.4.1
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/jm/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by suvl** [comment]
similar behaviour for `dotnet restore` and `dotnet run`

**Comment by suvl** [comment]
Solved, in a bad way. Had to downgrade libcurl3 from version 7.52.1 to 7.38.0-4 (debian oldstable / jessie). Will keep it open 'cause this is not the optimal solution.

**Comment by wli3** [comment]
This issue was moved to dotnet/core-setup#3094
