### ISSUE TITLE
Allow failures or support conditionals for nuget.config

### ISSUE THREAD

**Issue by dasjestyr** [dotnet/cli#7507]
## Steps to reproduce
Add a windows path and a linux path to Nuget.config in the project directory
From the project directory, run `dotnet restore --configfile Nuget.config`

## Expected  behavior
If a feed produces an error, the restore should be allowed to continue by trying other feeds. For example, if run on linux, the windows path will fail but the restore should succeed when it tries the linux path and vice versa.

## Actual behavior
The restore fails with the following error:

> 
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
>    at System.SZArrayHelper.get_Item[T](Int32 index)
>    at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
>    at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
>    at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
>    at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (2.0.0)
> 
> Product Information:
>  Version:            2.0.0
>  Commit SHA-1 hash:  cdcd1928c9
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  17.04
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /usr/share/dotnet/sdk/2.0.0/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0
>   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

We have development occuring on both linux and windows machines and we use local nuget feeds so that we can modify shared libraries without having to wait for a remote build to push to the remote nuget server. The issue arises when we try to restore nuget packages. If we specify both a windows path and a linux path as package sources, the restore will fail. If I'm on linux, it'll work if i remove the windows path and vice versa.

Optionally, the feature to include a condition like `Condition="'$(OS)'=='Unix'"` (similar to project targets) could help

I'm currently working around this by creating Nuget.nix.config and specifying that on every restore done in linux and Nuget.config on every restore done in windows.

Another option might be to support a standard syntax for environment variables that work cross platform.

**Comment by dasjestyr** [comment]
I found that the windows environment variable syntax `%MyVariable%` is actually working. So I think using that to identify the feed location is probably the best approach. However, it may be worth looking into some suggestions mentioned above. I'm going to leave this open just so that it is seen. Please feel free to close once it is seen.

**Comment by livarcocc** [comment]
There is a --ignore-failed-sources flag that you can use for that.
