### ISSUE TITLE
Re-enable argument forwarding tests

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#7511]
The argument forwarding tests are being disabled as part of #7478, due to https://github.com/dotnet/corefx/issues/23496.  We should re-enable them once that bug is fixed, or when we get a version of MSBuild with https://github.com/Microsoft/msbuild/pull/2467, which also works around the issue.

**Comment by livarcocc** [comment]
This seems to have been fixed on MSBuild.

**Comment by livarcocc** [comment]
These tests have been re-enabled a while ago.
