### ISSUE TITLE
Native rpm packages for openSUSE

### ISSUE THREAD

**Issue by akontsevich** [dotnet/cli#7523]
Please create native dotnet rpm packages for openSUSE. Examples:

- http://download.opensuse.org/repositories/home:/cabelo/openSUSE_Tumbleweed/src/dotnet-1.1.0-64.4.src.rpm
- http://download.opensuse.org/repositories/home:/cabelo/openSUSE_Tumbleweed/src/

Also SUSE have [BuildService](https://build.opensuse.org/) which allows to build packages for any distribution.

**Comment by omajid** [comment]
As a distro package maintainer, I think this is the wrong approach. It would probably be better if the .NET Core project focused on making .NET Core easy to build from source. Then any distro could take it and package it. Advantages:

- Distribution requirements ensure packages are secure, lighter-weight (less bundled dependencies), fewer issues with unexpected dependencies, and so on.
- `yum/apt/dnf/zypper/pacman/whatever install dotnet` will work out of the box. No need to add separate feeds, or anything
- packages will fit in with the rest of the distro and do things the way distro works (install locations, dependencies, supported versions)
- It is the only way any software written in .NET Core will be accepted into a linux distribution.
- .NET Core maintainers will have less work to do maintaining .NET Core for every single Linux/*nix distribution on earth.

**Comment by omajid** [comment]
Oh, and I think if we can get .NET Core build down to just a simple `./build.sh`, it would make it *much* easier to get into any distribution by default.

**Comment by akontsevich** [comment]
Wow! Thanks! Packages already there: https://www.microsoft.com/net/core#linuxopensuse

**Comment by akontsevich** [comment]
However install commands are wrong:

> sudo sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo' 
> sh: /etc/yum.repos.d/dotnetdev.repo: No such file or directory. 

Packages exist in following repo (url): https://packages.microsoft.com/opensuse/42.2/prod/

**Comment by akontsevich** [comment]
Error installing dotnet-sdk-2.0.0:

```
> sudo zypper install dotnet-sdk-2.0.0
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libcurl needed by dotnet-runtime-2.0.0-2.0.0-1.x86_64
 Solution 1: do not install dotnet-sdk-2.0.0-2.0.0-1.x86_64
 Solution 2: break dotnet-runtime-2.0.0-2.0.0-1.x86_64 by ignoring some of its dependencies
```
openSUSE has **libcurl4** package. One more little change remain :)

**Comment by livarcocc** [comment]
@steveharter can you comment? Since the missing dependency is on the runtime?

**Comment by leecow** [comment]
This is a known issue on SUSE/OpenSUSE. I noted it in the getting started steps on dot.net but forgot to include in [2.0.0 Known Issues](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0.0-known-issues.md). 

Choosing solution '2' works as libcurl is already present on the systems. We need to update the native installers for runtime and sdk to account for this.

**Comment by livarcocc** [comment]
@leecow sounded like you were already aware of this issue when we chatted today. But want to make sure you are tagged here. Also, moving this issue to core-setup, where the native installer dependencies will have to be updated.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3264
