### ISSUE TITLE
dotnet-install.ps1 script prints installation drive name (old debugging info?)

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#7526]
## Steps to reproduce
1. Run dotnet-install.ps1 when there's a new version to install (this doesn't work if the requested SDK is already installed)

## Expected  behavior
Clear messages that make sense. Such as the below:

```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.0-preview1-007071/dotnet-sdk-2.1.0-preview1-007071-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.0-preview1-007071/dotnet-sdk-2.1.0-preview1-007071-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\Users\anurse\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
```

## Actual behavior
Those messages, but before them, `C:` is randomly printed to the console:

```
C:
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.0-preview1-007071/dotnet-sdk-2.1.0-preview1-007071-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.0-preview1-007071/dotnet-sdk-2.1.0-preview1-007071-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\Users\anurse\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
```

The culprit seems to be this line, which seems like maybe some debugging code that was left in?

https://github.com/dotnet/cli/blob/1db2d78dd9959073eadac99e30a608913c2784cb/scripts/obtain/dotnet-install.ps1#L473

I'll send a PR to remove it, assuming it is old debugging code as suspected.

**Comment by johnbeisner** [comment]
@anurse 
It appears that you are using an old version of dotnet-install.ps1 - please use the version at: https://dot.net [specifically: https://dot.net/v1/dotnet-install.ps1]

**Comment by johnbeisner** [comment]
@anurse
This has already been addressed: https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1 - line 464

**Comment by anurse** [comment]
:+1:
