### ISSUE TITLE
Find a better way to find libraries

### ISSUE THREAD

**Issue by francipvb** [dotnet/cli#7531]
Hello,

Are there a better way to find libraries in the installer bash script?

Look at this:

```bash
  [ -z "$($LDCONFIG_COMMAND -p | grep libunwind)" ] && say_err "Unable to locate libunwind. Install libunwind to continue" && failing=true
```

This check cannot be done in some scenarios, like Heroku containers due to a write restriction to the `/usr/lib` directories at build-time.

**Comment by francipvb** [comment]
This code is located [here](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh#L194).

Cheers,

**Comment by nguerrera** [comment]
I don't understand why a write restriction would prevent this check from working. Can you elaborate?

**Comment by francipvb** [comment]
Hello,

I'll close this because I found a way to avoid library checking.

Write access is needed when installing other software related to the SDK, such *libunwind* under non-rooted environments like Heroku.

But there is a undocumented environment variable that prevents the check.

Cheers,
