### ISSUE TITLE
dotnet publish --self-contained hanged on Win10-x64

### ISSUE THREAD

**Issue by mazong1123** [dotnet/cli#7533]
## Steps to reproduce
```sh
mkdir testhang
cd testhang
dotnet new console
dotnet restore
dotnet publish --self-contained -c Release -r win10-x64
```

## Expected  behavior
The program can be published correctly.

## Actual behavior
The command hanged without any response.

## Environment data
`dotnet --info` output:
```sh
.NET Command Line Tool(2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by nguerrera** [comment]
This is hanging for you every time?

NOTE: You should be adding `<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>` after the dotnet new console so that restore sees the RID. It should have given you an error about that and not a hang, though.

**Comment by mazong1123** [comment]
@nguerrera I tried again today. After waiting for 30 min, it started to work. Now `dotnet restore` becomes much more faster. It may cause by network issue or something. I'm closing this issue right now. I'll open it if I can fully reproduce this issue.
