### ISSUE TITLE
dotnet build/msbuild does not correctly embed resources like VS2017

### ISSUE THREAD

**Issue by markrendle** [dotnet/cli#7534]
## Steps to reproduce

- Create a `netcoreapp2.0` console application.
- In VS2017 project properties, add a default resource file
- Add a Text File resource
- When building in Visual Studio, strongly-typed resource string property is correctly the text from the file
- `dotnet build` or `dotnet msbuild` and the resource string property is like below:

```
..\Message.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;utf-8
```

Repro project at https://github.com/markrendle/DotnetBuildResourceRepro

## Expected  behavior

`dotnet build` or at least `dotnet msbuild` should produce same output as building in VS2017

## Actual behavior

They don't.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by nguerrera** [comment]
This is tracked by https://github.com/Microsoft/msbuild/issues/2221

**Comment by markrendle** [comment]
Thanks, I'll watch that issue.
