### ISSUE TITLE
openSUSE Leap 42.1 has end-of-life'd - no builds available for 42.2/42.3

### ISSUE THREAD

**Issue by matt-richardson** [dotnet/cli#7550]
## Steps to reproduce

Go to https://www.microsoft.com/net/download/linux

## Expected  behaviour

Builds available for openSUSE Leap 42.2 (released November 2016) and 42.3 (released July 2017).

## Actual behaviour

A build is only available for 42.1, which hit [end-of-life in May 2017](https://lists.opensuse.org/opensuse-announce/2017-05/msg00002.html).

## Background

As 42.1 has hit end-of-life, it's [package repo](http://download.opensuse.org/distribution/leap/) is no longer available, meaning its very difficult to build an openSUSE image to test our net core code against.

Note, this was raised in https://github.com/dotnet/cli/issues/5834, but closed with an incorrect answer (it referred to 42.1, which had already been superseded).

Interestingly, on https://www.microsoft.com/net/core#linuxopensuse, it refers to 42.2, but https://www.microsoft.com/net/download/linux refers to 42.1.

**Comment by wli3** [comment]
@leecow

**Comment by leecow** [comment]
We need to continue to support the current releases of OpenSUSE 42. I'll update the download sites to better reflect this.

**Comment by matt-richardson** [comment]
Does that imply that openSUSE 42.2 and 42.3 are part of the build / test chain already?

The [Build Status](https://github.com/dotnet/cli#build-status) suggests that its not being built/tested on that platform at all, though I suspect thats an oversight.

**Comment by livarcocc** [comment]
We have added CI for opensuse 43.2 using the linux portable version of the CLI.
