### ISSUE TITLE
Netstandard2.0 restore bug

### ISSUE THREAD

**Issue by seancpeters** [dotnet/cli#7574]
The problem I'm seeing from local cli build test results (and from manual testing) is that I can create & restore the relevant templates, but the restore seems incorrect. The F# classlib template won't build, the error being:
```c:\temp\Creation\scratch\F#_Classlib\unknown(1,1): error FS0078: Unable to find the file 'netstandard.dll' in any of C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework� c:\temp\Creation\scratch\F#_Classlib� C:\Program Files\dotnet\sdk\2.1.0-preview1-007099\FSharp\ [c:\temp\Creation\scratch\F#_Classlib\F#_Classlib.fsproj]```
... which is strange, since it apparently restored correctly. This is related to the test: GivenThatIWantANewAppWithSpecifiedType.TemplateRestoresAndBuildsWithoutWarnings(language: "F#", projectType: "classlib", useNuGetConfigForAspNet: False, skipSpaWebpackSteps: False)

But the second test I left un-enabled uses the C# classlib template, which does build. The problem with that test is something different, but the underlying cause may be the same. For projects targeting netstandard2.0, when I run a command like:
```dotnet restore --configfile c:\GitHub\cli\NuGet.Config --packages packages```
the restore process reports success, but it doesn't create the requested packages directory. This is related to the test: 
```GivenThatIWantANewApp.NewProjectRestoresCorrectPackageVersion(type: "classlib", propertyName: "NetStandardImplicitPackageVersion", packageName: "netstandard.library")```

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.0-preview1-007099)

Product Information:
 Version:            2.1.0-preview1-007099
 Commit SHA-1 hash:  735188e023

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-007099\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943

**Comment by nguerrera** [comment]
See https://github.com/dotnet/cli/pull/7554#issuecomment-326492888

**Comment by livarcocc** [comment]
@emgarten is this something that you can help with?

**Comment by emgarten** [comment]
> the restore process reports success, but it doesn't create the requested packages directory. 

This can happen if all packages exist in a fallback folder. Try disabling the `RestoreAdditionalProjectFallbackFolders` property from the SDK. 

For `error FS0078` check the project.assets.json file, the `packageFolders` property contains the folders that NuGet uses for packages. Do one of those folders contain netstandard.dll and is it shown in the targets section?
