### ISSUE TITLE
dotnet test is now executing from a new location

### ISSUE THREAD

**Issue by mbenua-mparticle** [dotnet/cli#7582]
I've just finished an upgrade from project.json to the new csproj format. I'm now debugging a few new xunit test failures. The gist of it seems to be that the test runner is now executing from a different location, and so things like Assembly.GetExecutingAssembly().Location no longer report the same. This wouldn't be a huge issue, except the location it's reporting appears to be siloed one folder per-DLL, so things like appconfigs are not able to be side-loaded.

This is blocking our transition to the new format, which has been unfortunately fraught with other bugs and issues. I have kept all versions the same (or as close as possible) between the project.json and test.csproj.

## Steps to reproduce
Start project using old toolset (dotnet core 1.0.0-preview2-003156 in this case)
Grab xunit test in the debugger
In Immediate window, check: Assembly.GetExecutingAssembly().Location

Start project using new toolset
Grab xunit test in the debugger
In Immediate window, check: Assembly.GetExecutingAssembly().Location

## Expected  behavior
Assembly.GetExecutingAssembly().Location
"C:\\Users\\mbenua\\Documents\\GitHub\\clone-myServer\\myServer\\test\\MP.Test\\bin\\Debug\\net46\\win7-x64\\MP.dll"

## Actual behavior
Assembly.GetExecutingAssembly().Location
"C:\\Users\\mbenua\\AppData\\Local\\Temp\\1705cbcd-4476-4305-8433-31d39beb0222\\1705cbcd-4476-4305-8433-31d39beb0222\\assembly\\dl3\\7a232852\\be8a30c0_6e23d301\\MP.dll"

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by mbenua-mparticle** [comment]
Figured it out - dotnet test for 2 is using xunit 2, which has shadow copy turned on by default. Turning shadow copy off fixed this problem.

**Comment by livarcocc** [comment]
Closing this since a solution has been found.
