### ISSUE TITLE
Dotnet-sdk on Ubuntu 16.04 fails to install any versions?

### ISSUE THREAD

**Issue by wickedlizerd** [dotnet/cli#7584]
## Steps to reproduce
(Little backstory first)
I had just bought my new VPS last night, currently running Ubuntu 16.04 and used https://www.microsoft.com/net/core#linuxubuntu to install dotnet. I have tried creating multiple applications to run on my vps, which none ran.

I then tried to install a preview build, which returned the same issue.

root@wickedlizerd: dotnet Redacted.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.1.1'.

## Expected  behavior
I expected dotnet to run the .net core application

## Actual behavior
Dotnet returned an error saying `The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.`

## Environment data
`dotnet --info` output:
root@wickedlizerd:/home/Redux# dotnet --info
.NET Command Line Tools (2.0.0-preview2-006360)

Product Information:
 Version:            2.0.0-preview2-006360
 Commit SHA-1 hash:  aba0008f05

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006360/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25406-03
  Build    : baa69770c40ce13dcb1a8979b288be8cb23f9c7b

**Comment by wli3** [comment]
Hi @wickedlizerd thank you for your post.

Looks like _Redacted.dll_ is targeted to ,NETcore.App 1.1.1 runtime, You need to install 1.1.1 runtime which is not carried by 2.0.0 SDK by install SDK 1.1.0.

`sudo apt-get install dotnet-dev-1.1.0` 

Note, different version of runtime can be installed side by side

**Comment by wickedlizerd** [comment]
Tried to install it, But I don't think I have the repo.

root@wickedlizerd:/home/Redux# sudo apt-get install dotnet-dev-1.1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-dev-1.1.0
E: Couldn't find any package by glob 'dotnet-dev-1.1.0'
E: Couldn't find any package by regex 'dotnet-dev-1.1.0'

**Comment by wickedlizerd** [comment]
I managed to fix the issue where the package is missing, however now I have this issue

root@wickedlizerd:/# sudo apt-get install dotnet-dev-1.1.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-dev-1.1.0 : Depends: dotnet-sharedframework-microsoft.netcore.app-1.1.2 but it is not going to be installed
Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by wickedlizerd** [comment]
Was able to figure out the issue,
used https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md and fixed the issue easily. Thank you!
