### ISSUE TITLE
dotnet run -v fails

### ISSUE THREAD

**Issue by elw00d** [dotnet/cli#7589]
## Steps to reproduce
`dotnet build --verbosity`

## Expected  behavior
All works correctly.

## Actual behavior
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by mikkelbu** [comment]
I've supplied a PR for #7520 which should also solve this issue.

Ps. The title says "dotnet **run** -v" but Steps to reproduce says "dotnet **build** --verbosity" (but that being said my PR should work for all toplevel commands that accept -v.

**Comment by wli3** [comment]
parser should handle the error case, the command should be valid and not checked anymore after parser. So the fix should be in parser

**Comment by wli3** [comment]
https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-build/BuildCommandParser.cs

fix should be in this file

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/7636

**Comment by evil-shrike** [comment]
the same error for `dotnet restore -v`

**Comment by hickford** [comment]
Anyone know a workaround?

**Comment by gabriellopes** [comment]
Oh... That is so sad!!! I'm also stuck on it! I can't believe that I REALLY need to use Windows in order to develop in .net!! 

Seriously! I'm stuck on "fixing .net issues" since the project I work started. While people, that use Windows, is almost finishing everything, I'm still stuck on .net issues.

**Comment by livarcocc** [comment]
@gabriellopes can you tell me more about what sort of issue you are seeing? I will gladly help you. I develop nearly 100% on OSX using the CLI.

**Comment by gabriellopes** [comment]
Hi @livarcocc, 

Thank you for your reply! First, I was stuck on a "segmentation fault" error, that I have spent some days of work to fix: dotnet cli was giving segmentation fault for Debian distros. After, I have been stuck on this issue, #7589, for 2 or 3 days of work and didnt fix it yet.

In my team, I am the only that is using Linux and, honestly, completely desmotivated with .NET Core. I'm hoping that there is no more issues to resolve so I can **finally** start the development.

Best wishes!

**Comment by jcapellman** [comment]
Seeing this on Debian 9 too:

`root@jcbk01:/opt/dotnet/sdk/2.0.0# dotnet --info output
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
`
For now publishing on Windows and then scp'ing over the files seems to be working ok as a workaround.

**Comment by wli3** [comment]
@jcapellman could you give me more detail on what is expected and what is actual result. I see the issue is diverged." Out of range" error is due to bad error handling, the command is not valid in the first place. The bug is fixed in master. While "segmentation fault" should be a different issue.
