### ISSUE TITLE
Building with multiple frameworks doesn't work correctly

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#760]
I have a project targeting two frameworks. When using dotnet compile and specify an output path the frameworks build, but the second framework build overwrites the first one since they are both going into the same output directory. I would expect the output directory to have the framework appended to it. Here's the command I used and output:
"C:\Program Files\dotnet\bin\dotnet.exe" -v compile "C:\temp\Documents\projects\ConsoleApp1\src\ConsoleApp1" --configuration Debug --output "..\..\artifacts\bin\ConsoleApp1" --temp-output "..\..\artifacts\obj\ConsoleApp1\Debug\
Compiling ConsoleApp1 for DNX,Version=v4.5.1
Running <C:\Program Files\dotnet\bin\dotnet-compile-csc.exe> @"..\..\artifacts\obj\ConsoleApp1\Debug\dotnet-compile.ConsoleApp1.rsp"
Process ID: 27164
Running <C:\Program Files\dotnet\bin\csc.exe> -noconfig @"..\..\artifacts\obj\ConsoleApp1\Debug\dotnet-compile-csc.rsp"
Process ID: 18924

**Comment by piotrpMSFT** [comment]
@cdmihai can you take a look? I'm hitting a similar issue in dotnet-pack. I'll check if they're related.

**Comment by piotrpMSFT** [comment]
It looks like somewhere along the way dotnet-compile stopped creating bin/{config}/{tfm} folders when a custom output path was provided. I have a fix that is being tested as we speak.

**Comment by piotrpMSFT** [comment]
looks like this was somewhat intentional. We'll need to talk about design tomorrow... the current implementation seems wrong.

**Comment by piotrpMSFT** [comment]
even when --output is specified, compile output should go to  {output}/bin/{config}/{tfm}/{rid}. Note, the last element {rid} still needs to get plumbed through the system.

**Comment by BillHiebert** [comment]
I am not sure how much of the path should be appended to by dotnet compile. I would only expect it to append the {tfm} since that is the only piece of the path that can't be controlled by the caller. Typically, the project system would add differentiators for {config} and {rid}.  So the the output would go to {output}/{tfm}.

**Comment by livarcocc** [comment]
@davidfowl @piotrpMSFT @BillHiebert Do we really need rid in the path here? What are the cases where it makes sense to have those? When I compile something, usually just have tfm there will be enough. In which cases will the code be platform specific? It feels to be like just going {Config}/{Tfm} is enough to disambiguate the bits.

**Comment by BillHiebert** [comment]
What about when --arch is set? With your proposal the setter of the output path is required to disambiguate based on this value, if necessary. This is fine by me.

**Comment by livarcocc** [comment]
This piece is tracking the Rid work: https://github.com/dotnet/cli/issues/711
