### ISSUE TITLE
executable with long name fails to work after standalone publish

### ISSUE THREAD

**Issue by jgreene** [dotnet/cli#7600]
## Steps to reproduce
```
mkdir Some_Really_long_Name_That_is_still_going_geez_stop_please_finally_stopping
cd Some_Really_long_Name_That_is_still_going_geez_stop_please_finally_stopping
dotnet new console
dotnet publish -c Release -r win7-x64
cd bin\Release\netcoreapp2.0\win7-x64\publish
./Some_Really_long_Name_That_is_still_going_geez_stop_please_finally_stopping.exe
```

It appears the executable name is being truncated at 64 characters.  This may be related to https://github.com/dotnet/core-setup/blob/master/src/corehost/corehost.cpp but I am unsure. 

## Expected  behavior
Prints 'Hello World'

## Actual behavior

> The managed DLL bound to this executable: 'Some_Really_long_Name_That_is_still_going_geez_stop_please_final', did not match own name 'Some_Really_long_Name_That_is_still_going_geez_stop_please_finally_stopping.dll'.
> A fatal error was encountered. This executable was not bound to load a managed DLL.

## Environment data

> .NET Command Line Tools (2.0.0)
> 
> Product Information:
>  Version:            2.0.0
>  Commit SHA-1 hash:  cdcd1928c9
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.14393
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.0\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0
>   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3150
