### ISSUE TITLE
Can't install dotnet-sdk nightly from debian feed

### ISSUE THREAD

**Issue by bazzilic** [dotnet/cli#7609]
## Steps to reproduce
I am trying to install dotnet SDK nightly build on a clean ubuntu 16.04, so I run this as per README.md:

```
echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list     && \
apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 && apt-get update                                        && \
apt-get install -y $(apt-cache search dotnet-sdk | tail -n 1 | cut -d' ' -f1)
```

## Expected  behavior
Dotnet SDK install nicely.

## Actual behavior
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dotnet-sdk-2.1.0-preview1-007172 : Depends: aspnetcore-store-2.1.0-preview1-26623 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Looking through `apt-cache search asp` shows that there are no packages at all named `aspnetcore-store`. An extensive googling for a debian feed I might be missing resulted in nothing, I couldn't even find what repo this package builds from.

Any ideas? Thanks.

## Environment data
Clean ubuntu 16.04 xenial (in a docker container).

**Comment by wli3** [comment]
Hi @bazzilic thank you for the post. 

Although the upload of package dotnet-sdk-* is stable after recent change, aspnetcore-store is absent from the feed. Move this issue to store repo

**Comment by wli3** [comment]
This issue was moved to aspnet/MetaPackages#231
