### ISSUE TITLE
Lack of clear documentation for running tests with code coverage on MacOS

### ISSUE THREAD

**Issue by a-h** [dotnet/cli#7612]
I'm confused as to how to run unit tests with code coverage on Linux and OSX for .NET Core 2.0 projects using the built-in tools.

## Steps to reproduce

* Create a test project:
   * `dotnet new xunit`
* Run the test command line:
    * `dotnet test`
*  Try and find code coverage in the help (hmm, no instructions).
    * `dotnet test --help | grep cover`
* Google for how to do Code Coverage, find you have to do something with `dotnet vstest` or something.
* Find this page https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md and read coverage
* Add the specified Nuget package to my test project.
    * `dotnet add package Microsoft.CodeCoverage`
* Run the test without coverage:
   * `dotnet vstest ./bin/Debug/netcoreapp2.0/Updater.Tests.dll`
      * Works fine!
* Run it with code coverage:
   * `dotnet vstest --collect:"Code Coverage" --framework:".NETCoreApp,Version=v2.0" ./bin/Debug/netcoreapp2.0/Updater.Tests.dll`

## Expected  behavior

* Run `dotnet test --cover` and code coverage files would be output, and a summary table of results printed to the console.
* vscode would pick this up and highlight covered vs uncovered code.

## Actual behavior

Error message shown:

<img width="944" alt="screen shot 2017-09-07 at 19 26 03" src="https://user-images.githubusercontent.com/1029947/30178890-7f6408b2-9402-11e7-93ab-59138fc14968.png">

Then I find this comment:

https://github.com/Microsoft/vstest/issues/579#issuecomment-305374623

I thought .NET Core was cross platform? I'm confused...

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by wli3** [comment]
This issue was moved to Microsoft/vstest#1053
