### ISSUE TITLE
Powershell Module

### ISSUE THREAD

**Issue by Ayanmullick** [dotnet/cli#7617]
## Expected  behavior
As an IT Pro I've created a lot of Powershell scripts over the years for my personal use and gotten used to the syntax. And it'd be nice to be able to work with .Net Core in the same syntax. Also, a .Net Core Powershell module would enable integrating .Net into the existing Powershell scripts more easily

## Actual behavior

Will there also be a Powershell module equivalent to the dotnet CLI commands for .Net Core 2.0.

**Comment by livarcocc** [comment]
This issue was moved to PowerShell/PowerShell#4810
