### ISSUE TITLE
dotnet-pack should take nuspec style input

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#762]
`dotnet-pack` currently expects a project and builds a folder and packs up the compiled/published output.

What we would like to have is something that NuGet offered which can take a nuspec file that specifies dependencies, source locations and target locations, then the package builder can simply build any arbitrary set of libs and binaries based on this spec file.

This is needed to make corehost into its own package if we are using dotnet-pack in the build scripts and not rely on downloading NuGet.exe. Basically there are two files that need to go into the nupkg in their respective locations from the file path -- `corehost.exe` and `clihost.dll`

The NuSpec format itself can be decided @blackdwarf. I don't think we want to stick to NuSpec XML.

@piotrpMSFT could you please reassign?

@gkhanna79, @davidfowl 

This is needed to package the corehost into its own package: #279

**Comment by davidfowl** [comment]
Why not just use nuget?

**Comment by schellap** [comment]
@piotrpMSFT suggested that we should use dotnet pack. Is there a specific reason?

I assume it is because dotnet pack needs to get there anyway?

**Comment by davidfowl** [comment]
`dotnet pack` will eventually just call `nuget pack`. Right now the value in package a project with `project.json` is that it is for building managed class libraries into packages. It really isn't a nuget replacement for packing random things.

**Comment by gkhanna79** [comment]
@schellap I presume this is accounting for the discussion we had yesterday about clihost piece no longer being statically linked in, right?

**Comment by schellap** [comment]
> Why not just use nuget?

@davidfowl NuGet needs mono to run and CLI repo doesn't use mono. We can make it a requirement to install mono (CI machines already have this) to clone CLI, but this requirement sounds bad.

**Comment by livarcocc** [comment]
I am closing this. If you guys still feel this is needed, please re-activate. And when you do, update the blocking flag. Well, if it is still blocking you, leave it, otherwise, remove it please.
