### ISSUE TITLE
dotnet cli created projects don't work in VS2017 15.3.3.

### ISSUE THREAD

**Issue by codefactorydevelopment** [dotnet/cli#7623]
## Steps to reproduce

Create 2 projects:

 1. `dotnet new webapi` (name: webapiProject)
 2. `dotnet new xunit` (name: testProject)

After that, on `testProject` project:
`dotnet add reference webapiProject`

Now, when opening testProject.csproj in `VS2017 15.3.3.`

## Expected  behavior
Expected to see `testProject` loaded with resolved dependency to `webapiProject`

## Actual behavior

When opening testProj.csproj in VS2017 15.3.3. the following Nuget **NU1105** error occurs:

*Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1105	Unable to find project information for 'webapiProject'. The project file may be invalid or missing targets required for restore.*	

Dependencies & build work as expected when done from `dotnet cli`.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by nguerrera** [comment]
@emgarten

**Comment by emgarten** [comment]
This can happen if the project system does not nominate a project. 

Does the error continue if you wait?
Does activitylog.xml from VS contain any additional errors on why the project failed?
Are you consistently getting this error?

**Comment by codefactorydevelopment** [comment]
hi @emgarten 

 1. Error is there regardless of how many times i try or how long i wait.
 2. Just checked, there is nothing in activitylog.xml
 3. I've tried this scenario a few times and always got that error.

Could i ask, what does 'nominating a project' exactly mean? Not sure i've ever heard that term.

**Comment by nguerrera** [comment]
@davkean Should I move this to project system?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nguerrera** [comment]
@codefactorydevelopment Are the two project files in the same directory?

**Comment by codefactorydevelopment** [comment]
@nguerrera

no, they are each in their own folder:

/parentFolder
    /webapiProject
    /testProject

**Comment by davkean** [comment]
This issue was moved to dotnet/project-system#2812
