### ISSUE TITLE
VS2015 cannot navigate to the symbol under the caret after installing dotnet-standard-support-vs2015-2.0.0-win-x86

### ISSUE THREAD

**Issue by MartyZhou** [dotnet/cli#7626]
## Steps to reproduce
install dotnet-standard-support-vs2015-2.0.0-win-x86
launch a solution in vs2015
press f12 on a class

## Expected  behavior
go to the definition of the class

## Actual behavior
it pops up an alert saying cannot navigate to the symbol under the caret

## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

EXTRA Info
I have vs2017 and dotnet-sdk-2.0.0-win-x64 installed

**Comment by dsplaisted** [comment]
@MartyZhou Can you provide a repro project or information on what type of project this applies to?  IE does it apply to all projects, or only projects that reference a .NET Standard 2.0 NuGet package, or what?

Thanks!

**Comment by livarcocc** [comment]
Given that we haven't had additional information for this issue in the past two months, I am closing it for now.

If a more detailed repro can be provided, please do so and re-activate.
