### ISSUE TITLE
dotnet-build: commandlineparameters (clp) switch is ignored

### ISSUE THREAD

**Issue by dmccaffery** [dotnet/cli#7627]
## Steps to reproduce

The following prints the summary regardless:

```
mkdir dotnet-ignore-clp
cd dotnet-ignore-clp
dotnet new classlib
dotnet build /clp:NoSummary
```

The following does not:

```
mkdir msbuild-doesnt-ignore-clp
cd msbuild-doesnt-ignore-clp
dotnet new classlib
dotnet restore
dotnet msbuild /clp:NoSummary
```

## Expected  behavior

```dotnet-build``` should respect the msbuild /clp argument as indicated in the documentation:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x

>> In addition to its options, the dotnet build command accepts MSBuild options, such as /p for setting properties or /l to define a logger. Learn more about these options in the MSBuild Command-Line Reference.

## Actual behavior

The /clp argument is seemingly ignored (or overridden). Note that this is net new behavior with donet-cli for the 2.0 SDK -- This worked previously in 1.0.4 SDK.

## Environment data
`dotnet --info` output:

NET Command Line Tools (2.0.1-servicing-006955)

Product Information:
 Version:            2.0.1-servicing-006955
 Commit SHA-1 hash:  6734510020

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/deavon/.dotnet/sdk/2.0.1-servicing-006955/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.1
  Build    : 5eb2f9bd659ad2161a8e035ac4bccd8f892caa0a

**Comment by dasMulli** [comment]
Duplicate of https://github.com/dotnet/cli/issues/7009 ?

**Comment by dmccaffery** [comment]
@dasMulli it is indeed a duplicate. My apologies. I just noticed a regression in a build tool that I created and opened a new issue -- I thought I checked to see if one existed by searching for "summary"; but I didn't see #7009.
