### ISSUE TITLE
`dotnet restore` fails with auth'd (VSTS) package source

### ISSUE THREAD

**Issue by Mardoxx** [dotnet/cli#7629]
## Steps to reproduce
1. Create new project and target netstandard (e.g. netcoreapp2.0, netstandard2.0)
2. Nuget.Config with custom package source e.g.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="Common" value="https://mysource.pkgs.visualstudio.com/_packaging/Common/nuget/v3/index.json" />
  </packageSources>
</configuration>
```
3. dotnet restore
4. Restore fails

## Expected  behavior
:)

## Actual behavior
:(

```
C:\Program Files\dotnet\sdk\2.1.0-preview1-006784\NuGet.targets(102,5): error : Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'https://mysource.pkgs.visualstudio.com/_packaging/3df2ef6b-68fa-412c-90fa-bcee06e30045/nuget/v3/flat2/microsoft.netcore.app/index.json'. [.csproj]
C:\Program Files\dotnet\sdk\2.1.0-preview1-006784\NuGet.targets(102,5): error :   Response status code does not indicate success: 401 (Unauthorized). [.csproj]
```

Restore packages works fine in VS2017.

Completely buggers up any `dotnet ef` commands too as these rely on the project building successfully!

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.0-preview1-006784)

Product Information:
 Version:            2.1.0-preview1-006784
 Commit SHA-1 hash:  0b507e68fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-006784\


Microsoft .NET Core Shared Framework Host



  Version  : 2.0.0

  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```
----

Happens with net461 tfm too, so not really sure what the problem is here..

**Comment by Mardoxx** [comment]
I think this is because I'm using a VSTS feed..

**Comment by Mardoxx** [comment]
Similar to https://github.com/dotnet/cli/issues/3977

**Comment by Mardoxx** [comment]
https://www.visualstudio.com/en-us/docs/package/nuget/dotnet-exe

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5874

**Comment by Mardoxx** [comment]
@livarcocc Thanks! Out of curiosity, how come? Does `dotnet restore` just run `nuget restore` so this is a nuget issue?
