### ISSUE TITLE
dotnet publish output directory is missing dlls if target frameworks are mixed

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/cli#7630]
## Steps to reproduce
- Create ASP.NET Core 2.0 Project for .NET Framework (4.6.1 in my case)
- Add all the runtime identifier, binding redirects etc. elements to csproj
```xml
    <TargetFramework>net461</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
```
- Add Library with .NET Standard 2.0
- Reference JSON Serializer Jil in Framework and create class to call it
- Reference Framework in Web project
- Change example controller to call the Serializer from above
- Run dotnet publish -c release -o Published
- Run created website (e.g in command line) from the Published Directory
- open page http://localhost:54303/api/values/5

## Expected  behavior
- Returns value 5

## Actual behavior
- Exception: System.IO.FileNotFoundException: Die Datei oder Assembly "Jil.Core, Version=2.15.4.0, Culture=neutral, PublicKeyToken=null"
- File Jil.Core.dll is missing from the Published Directory

## Additional information
Jil.Core is the dll which is used for .NET Standard, which is apparently not copied into the output directory.
If I use netcoreapp2.0 as my targetframework in the web project jil.core.dll is copied to the published directory. (Doesn't help me much as I currently still need to use the full framework)

Attached Repro:
[JilRepro.zip](https://github.com/dotnet/cli/files/1293061/JilRepro.zip)

- Run dotnet publish -c release -o Published
- Run created website (e.g in command line) from the Published Directory
- open page http://localhost:54303/api/values/5

## Environment data
`dotnet --info` output:
.NET-Befehlszeilentools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by dsplaisted** [comment]
Thanks for the report.

I took a look, and it turns out this is a bug in the Jil NuGet package.  It has different assembly names between the .NET Standard and .NET Framework versions of the library, which causes issues like this.  I've filed a bug for this over at the Jil repo with more details: https://github.com/kevin-montrose/Jil/issues/279

**Comment by swati8008** [comment]
What is the solution to above problem? We are facing the same issue.
Exception: System.IO.FileNotFoundException: Die Datei oder Assembly "Jil.Core, Version=2.15.4.0, Culture=neutral, PublicKeyToken=null"

**Comment by andybn** [comment]
We have the same issue. Is there some workaround?.
