### ISSUE TITLE
Fedora 26 requires compat-openssl10

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#7631]
## Steps to reproduce
Try to install the .NET Core 2.0 SDK in a Fedora 26 container, using the instructions at https://www.microsoft.com/net/core#linuxfedora.

### Dockerfile
```
FROM fedora:26

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc \
    && sh -c 'echo -e "[packages-microsoft-com-prod]\nname=packages-microsoft-com-prod \nbaseurl=https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/dotnetdev.repo'

RUN dnf install -y libunwind libicu

RUN dnf install -y dotnet-sdk-2.0.0

RUN mkdir warmup \
    && cd warmup \
    && dotnet new \
    && cd .. \
    && rm -rf warmup \
```

## Expected  behavior
Install works.

## Actual behavior
Crash during `dnf install dotnet-sdk-2.0.0`:

```
/var/tmp/rpm-tmp.Kob50o: line 26:    15 Aborted                 (core dumped) /usr/share/dotnet/dotnet exec /usr/share/dotnet/sdk/2.0.0/dotnet.dll internal-reportinstallsuccess "rpmpackage" > /dev/null 2>&1
```

And crash during `dotnet new`:

```
No usable version of the libssl was found
```

## Fix
Install `compat-openssl10` in addition to `libunwind` and `libicu`:

```

RUN dnf install -y libunwind libicu compat-openssl10
```

**Comment by omajid** [comment]
Please also take a look at https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet/. We use this for .NET Core 2.0 on Fedora every day.

**Comment by omajid** [comment]
The long term work to support OpenSSL 1.1 is tracked here: https://github.com/dotnet/corefx/issues/9855

**Comment by mikeharder** [comment]
In the meantime, should the docs at https://www.microsoft.com/net/core#linuxfedora be updated to include `compat-openssl10` in addition to `libunwind` and `libicu`?

**Comment by omajid** [comment]
> In the meantime, should the docs at https://www.microsoft.com/net/core#linuxfedora be updated to include compat-openssl10 in addition to libunwind and libicu?

Yes, please! But I don't have the power to do that. Keep in mind this is only for Fedora 26 and later. There is no `compat-openssl10` in Fedora 25.

**Comment by livarcocc** [comment]
@leecow @mairaw @KathleenDollard for updating the documentation.

**Comment by mairaw** [comment]
I'll take care of that page.

**Comment by livarcocc** [comment]
Thanks @mairaw, closing this one since we have an issue tracking the website update already.

**Comment by mairaw** [comment]
The updates are now live at https://www.microsoft.com/net/core#linuxfedora

**Comment by RheaAyase** [comment]
We (the Fedora dotnet sig) were pointing the issue out on Slack and in our meetings, to have the website fixed for 4 months or so. Had given up.

@mikeharder please use our packages, not the Microsoft ones. Ours run on all versions of Fedora and may contain additional fixes for Fedora. http://copr.fedoraloves.net

@mairaw it should really say "Fedora 26 **and higher**" or something... Or on the other hand "Fedora 25 or older" ;)

**Comment by livarcocc** [comment]
@RheaAyase I am sorry, I am not part of your meetings and I don't see messages about it in the dotnet-cli slack channel. Where should we be looking for these communications?

**Comment by mairaw** [comment]
Ok, I'll change it to say Fedora 26 or later versions @RheaAyase.

**Comment by omajid** [comment]
Thanks @mairaw and @livarcocc !

**Comment by RheaAyase** [comment]
@livarcocc RedHat-Microsoft slack and weekly meetings. There was some effort but the communication got stuck a few times and never reached the right people... Communication is always an issue :P

**Comment by mairaw** [comment]
@RheaAyase The PR is created but I'm waiting for an approval. Should go live soon. 

For issues with the docs or the dot.net site, feel free to create an issue at https://github.com/dotnet/docs/issues or reach out directly to me at mairaw at microsoft dot com. If there are any communication issues, we should try to fix that.

**Comment by mairaw** [comment]
The change is live.
