### ISSUE TITLE
on gentoo ,run  dotnet new console  ,generate err : Cannot get required symbol ECDSA_sign from libssl

### ISSUE THREAD

**Issue by availa** [dotnet/cli#7633]
## Steps to reproduce
install gentoo x86_64 
install .net core 2.0 x64 linux sdk,
run dotnet new console

## Expected  behavior
new project created

## Actual behavior
dotnet new console

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Cannot get required symbol ECDSA_sign from libssl
Aborted (core dumped)

## Environment data

(1) gentoo  kernel 4.13.0 x86_64

(2) openssl  1.0.2l

(3) curl 
curl --version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy 

(4) `dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     gentoo
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/availa/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3190
