### ISSUE TITLE
ASP.NET Core 2.1.0: Unable to find package Microsoft.NETCore.App with Version

### ISSUE THREAD

**Issue by manikandan05** [dotnet/cli#7634]
Hi,

Recently i have updated in NetCoreApp1.1 application to NetCoreApp2.0. After this update the model expressions are not working in my entire project. Finally i got, this is known issues in ASP.NET Core 2.0 (based on issue link [#1614](https://github.com/aspnet/Razor/issues/1614)).

Now, i have updated my system into ASP.NET Core 2.1.0 and i have faced some unknown issues in Microsoft.NETCore.App SDK.

![sshot-1](https://user-images.githubusercontent.com/5366630/30322471-3666c4be-97d7-11e7-93de-33beac2fb5c8.png)

How, i can utilize the latest 2.1.0 version SDK to resolve this compilation issues?

My System config:

1. Visual Studio 2017 (Update 15.4)
2. DotNet Core 2.1.0 SDK

Also, follow the steps based on this link and download the daily build to ensure this case.

1. https://github.com/aspnet/Home#builds
2. https://github.com/dotnet/core-setup#daily-builds

Thanks.

**Comment by livarcocc** [comment]
The 2.1.0 SDK is not yet release and is under development. As such, not all its packages are available in NuGet. I would recommend uninstalling the 2.1.0 SDK and instead installing the release 2.0.0 SDK, available at http://dot.net.

If you must use the 2.1.0 SDK and the 2.1.0 runtime, you will need to add a NuGet.Config to your solution with this feed in it:

```
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```

**Comment by manikandan05** [comment]
Hi @livarcocc ,

Thanks for your detailed information. Actually my requirement is using model expressions with tag helpers. But its throws error [#1614](https://github.com/aspnet/Razor/issues/1614).

So, that i will forward to 2.1.0 SDK, its still under development means, how i can resolve my model expression issues in my application with 2.0.0 SDK.

Thanks.
