### ISSUE TITLE
Custom design-time tool, like the EFCore.Tools and EFCore.Tools.DotNet

### ISSUE THREAD

**Issue by PMExtra** [dotnet/cli#7635]
Could I make my custom CLI design-time tool, like the EFCore.Tools and EFCore.Tools.DotNet?

If yes, where can found the documentations about it?
If not yet, has any plan to support it?

**Comment by omajid** [comment]
It is documented at: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility

**Comment by PMExtra** [comment]
@omajid Thanks a lot.
