### ISSUE TITLE
ASP.NET Core 2.0: Model expressions throws error when used with tag helpers

### ISSUE THREAD

**Issue by manikandan05** [dotnet/cli#7638]
Hi,

I have used input tag helper with model expressions in my entire application. But recent update 2.0 will collapse my entire application  and its throws error #1614.

If there is any options to resolve this model expression issues with tag helpers in my application with 2.0 SDK.

Thanks

**Comment by manikandan05** [comment]
I have resolved this issue by work around solution. Move the model expression related code blocks into partial view page. Then utilize that partial view into my rendering section by using @Html.PartialView('viewname')

Now, the issue gets resolved.

Thanks.

**Comment by livarcocc** [comment]
Glad that you found a solution for this problem. In the future, issues like this should probably go to aspnet/home, I think you will get a quicker response time around there.
