### ISSUE TITLE
Figure out the story for pkg upgrade on OSX

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#764]
Our PKG is not an app bundle, so we can't just tell users to install by deleting the app under the applications folder.

We need to figure out a good story for upgrading with PKGs.

**Comment by spencerhakim** [comment]
I'd love it if there was a Homebrew formula, was never clear on why `dnx` has one but `dotnet` doesn't.

**Comment by blackdwarf** [comment]
@spencerhakim it is coming soon-ish.

**Comment by blackdwarf** [comment]
OK, this has been figured out and done.
