### ISSUE TITLE
dotnet-sdk-2.0.0 package dependency error on ubuntu 16.10 

### ISSUE THREAD

**Issue by polarbit** [dotnet/cli#7640]
Hi,

I tried to install dotnet-sdk-2.0.0, after uninstalling preview versions.
And received same error with #7475. 
Which says briefly _"The following packages have unmet dependencies:
 dotnet-sdk-2.0.0 : Depends: dotnet-runtime-2.0.0 but it is not going to be installed"_

Then tried to install dotnet-runtime-2.0.0 ; this time apt-get says libicu55 not found or broken .

Then I added below line to /etc/apt/sources.list
deb http://security.ubuntu.com/ubuntu xenial-security main
W.r.t. package here: https://packages.ubuntu.com/xenial/amd64/libicu55-dbg/download

And re-run apt-get install dotnet-sdk-2.0.0 and be successful.
But currently, I did not understand what is the reason. Was my system broken, or package itself is broken ?

If anybody can look into outputs below and give some comments, it will be very helpful.

## ERRORS & OUTPUTS:

**apt-get update**
> sudo apt-get update
Hit:1 http://tr.archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://tr.archive.ubuntu.com/ubuntu yakkety-updates InRelease
Hit:3 http://tr.archive.ubuntu.com/ubuntu yakkety-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu yakkety-security InRelease
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:6 https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease
Hit:7 https://packages.microsoft.com/repos/vscode stable InRelease
Hit:8 https://download.docker.com/linux/ubuntu yakkety InRelease
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [356 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [333 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [156 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/main amd64 DEP-11 Metadata [60,0 kB]
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [57,0 kB]
Fetched 1.065 kB in 16s (65,9 kB/s)
Reading package lists... Done

**apt-get install dotnet-runtime-2.0.0**
>sudo apt-get install dotnet-runtime-2.0.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
dotnet-runtime-2.0.0 : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.

**libicu55 install error**
> sudo apt-get install dotnet-runtime-2.0.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
dotnet-runtime-2.0.0 : Depends: libicu55 but it is not installable
E: Unable to correct problems, you have held broken packages.

**apt-cache search libicu**
> sudo apt-cache search libicu
icu-devtools - Development utilities for International Components for Unicode
icu-devtools-dbg - Development utilities for International Components for Unicode (debug symbols)
libicu-dev - Development files for International Components for Unicode
libicu57 - International Components for Unicode
libicu57-dbg - International Components for Unicode (debug symbols)
libicu4j-4.2-java - Library for Unicode support and internationalization
libicu4j-4.4-java - Library for Unicode support and internationalization
libicu4j-49-java - Library for Unicode support and internationalization
libicu4j-java - Library for Unicode support and internationalization
libicu4j-java-doc - Library for Unicode support and internationalization - Docs

## Environment data
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"

**Comment by livarcocc** [comment]
@wli3 can you help out here?

**Comment by omajid** [comment]
Do we support Ubuntu 16.10? Our OS support page says we dont: https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#out-of-support-os-versions

**Comment by livarcocc** [comment]
You are absolutely right. We supported that in 1.0 I believe. We support 14.04 and 16.04.

Closing this issue then.

**Comment by polarbit** [comment]
Thank you @livarcocc  and @omajid  for responses, I did not know that. 👍 

I assumed implicitly, if it works with 17.04, 16.04, 14.04;  it works with 16.10  :)

By the way, everything works for now on 16.10 after I installed libicu55. But of course I will move my system to 16.04, or 17.04.

**Comment by nvrnight** [comment]
I get the same problem on 16.04

**Comment by rasik210** [comment]
@livarcocc I'm getting exact same issue on my machine with below OS details:

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

When I try to install .NET core SDK then it shows dependency error on corresponding .NET run time. When I try to install .NET run time then it gives below error:

> The following packages have unmet dependencies:
>  dotnet-runtime-2.0.0 : Depends: libicu55 but it is not installable
>                         Depends: dotnet-hostfxr-2.0.0 but it is not going to be installed

Cache search shows libicu60 which is of no help. I'm not sure from which package source can I get libicu55 ?

**Comment by rasik210** [comment]
I found one resolution from [this](https://github.com/dotnet/core-setup/issues/3435) thread:

> 
>     Download link:
>     https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.0.3-linux-x64-binaries
> 
> mkdir -p $HOME/dotnet
> 
> cd Downloads
> 
> tar zxf dotnet-sdk-2.0.3-linux-x64.tar.gz -C $home/dotnet
> 
> export PATH=$PATH:$home/dotnet

**Comment by livarcocc** [comment]
You need to add the export PATH to your .bashrc file, if that's what you use, so that it gets invoked when you open up your shell.
