### ISSUE TITLE
Can get new package downgrades doing dotnet build -r platform / nuget package resolution does the wrong thing within net core itself

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/cli#7641]
## Steps to reproduce

Have a .NET Core 2.0 project
Don't reference System.Diagnostics.Debug (normally you would not reference this in an MVC project so this is easy)
Have a dependent .NET Core 1.0 DLL that references the 1.0 version of System.IO.Filesystem
observe that dotnet build succeeds
observe that dotnet build -r win7-x64 fails with package depenency problems

## Expected  behavior

build succeeds

## Actual behavior

C:\Users\jhudson\dev\redacted.csproj : error NU1605: Detected package downgrade: System.Diagnostics.Debug from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version. \r [C:\Users\jhudson\dev\redacted.csproj]
C:\Users\jhudson\dev\redacted.csproj : error NU1605:  Redacted2 (>= 1.0.0) -> Cedaron.Common (>= 1.1.2) -> System.IO.FileSystem (>= 4.0.1) -> runtime.win.System.IO.FileSystem (>= 4.3.0) -> System.Diagnostics.Debug (>= 4.3.0) \r [C:\Users\jhudson\dev\redacted.csproj]
C:\Users\jhudson\dev\cento_forms\src\redacted.csproj : error NU1605:  Redacted2 (>= 1.0.0) -> Cedaron.Common (>= 1.1.2) -> System.Diagnostics.Debug (>= 4.0.11) [C:\Users\jhudson\dev\redacted.csproj]

Where Redacted2 is a normal .NET Core 2.0 dll and Cedaron.Common is pinned to .NET Core 1.0 for compatibility reasons (in fact it hasn't been compiled since .NET Core 2.0 came out)

Obviously the runtime.win.* dlls referencing other dlls is causing the problem. I've got no idea what the solution ought to be.

I've got many instances of this error message with different dlls and I think that directly embedding the dependencies of runtime.win.* into my own project files is a terrible idea.

**Comment by joshudson** [comment]
Bisection has repeatedly failed; but we have an additional bug in the tooling:

System.IO.FileSystem (>= 4.0.1) -> runtime.win.System.IO.FileSystem (>= 4.3.0)

Somehow the tooling thinks System.IO.Filesystem 4.0.1 references runtime.win.System.IO.FileSystem 4.3.0. IT DOES NOT!

**Comment by jhudsoncedaron** [comment]
Issue turned out to be some weird garden-of-eaden package that can't even compile that was causing very short reference paths to old old versions of dlls.
