### ISSUE TITLE
dotnet build --no-dependencies tries to build <ReferenceOutputAssembly>false</ReferenceOutputAssembly> references

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/cli#7642]
The project has extra DLLs that need to be copied into its build output to work

    <ProjectReference Include="..\Cedaron.Redacted.Repository.SQL\Cedaron.Redacted.Repository.SQL.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Content</OutputItemType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Targets>Build;DebugSymbolsProjectOutputGroup</Targets>
    </ProjectReference>

And these projects get rebuilt even if --no-dependencies is specified. The dlls have already been built just copy them.

**Comment by livarcocc** [comment]
How did you verify that the project was being rebuilt?

I just tried this and when specifying the --no-dependencies flag to dotnet build, I see that the class library that I reference is not being rebuilt.

I tried this with SDK 2.1.4.

If you can still repro this issue with the SDK I mention above, please comment and I can re-activate this issue. It would also be super helpful to have more details on how to repro the problem, even a small repo where this problem reproes. I just created a console app and a class library where the console referenced the class library using the metadata you shared above.

**Comment by jhudsoncedaron** [comment]
We had a post-build action that was intermittently crashing due to being not reentrant. The build would always go through with --disable-parallel and randomly fail otherwise even if --no-dependencies was specified. We're not using --no-dependencies anymore anyway. It was a workaround for the dotnet restore corruption bug that only existed in 1.1.
