### ISSUE TITLE
Allow dotnet test to override values in runsettings files

### ISSUE THREAD

**Issue by CreepyGnome** [dotnet/cli#7644]
It would be great to be able to have the same functionality that MSTest/VSTest has when it comes ot overriding values at runtime in a runsettings file.

Example of what you can do in normal .NET Framework is here:

https://blogs.msdn.microsoft.com/devops/2015/09/04/supplying-run-time-parameters-to-tests/#comment-132205

That functionality in .NET Core would be great as it is a requirement to secure keys, secrets, passwords etc so they are not checked in to source control with integration test data that is required to run the integration tests in all environments including production.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1085
