### ISSUE TITLE
Encoding problems. Again?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/cli#765]
```
C:\Users\Андрій\Dev\GitHub\dotnetcli-aspnet5\HelloMvc>"C:\Program Files\dotnet\bin\dotnet" run
Unable to resolve project from C:\Users\лаЛњлалЁламЉлАлѓлАРђЊлаРёќ\Dev\GitHub\dotnetcli-aspnet5\HelloMvc
```

```
C:\Temp\dotnetcli-aspnet5\HelloMvc>"C:\Program Files\dotnet\bin\dotnet" run

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.21.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Не вда№┐й№┐й№┐й№┐й №┐йна№┐й№┐й №┐йка№┐йни№┐й №┐й№┐й№┐й№┐й.
```

Does this happen because of Ukrainian (Byelorussian) letter i with code U+0456 in my user profile path?
https://connect.microsoft.com/VisualStudio/feedback/details/808844/msbuild-passes-incorect-string-to-its-task-if-that-string-contains-ukrainian-byelorussian-letter-i-with-code-u-0456

**Comment by blackdwarf** [comment]
So far, we haven't really looked at globalization/localization of the toolset, but we will do that at one point so keeping this issue to track.

**Comment by xperiandri** [comment]
Thanks.

**Comment by krwq** [comment]
Thanks for reporting this!

**Comment by piotrpMSFT** [comment]
CLI successfully handles Unicode characters in the project path since preview2.
