### ISSUE TITLE
dotnet fails with error: api-ms-win-crt-runtime-l1-1-0.dll is missing.

### ISSUE THREAD

**Issue by seancpeters** [dotnet/cli#7654]
## Steps to reproduce
Start with a clean machine configured with: Win 8.1 x64 ESN OS
Install CLI 2.0 RTW

## Expected  behavior
dotnet commands execute properly.

## Actual behavior
Running dotnet with any (or no) options fails, pops up an error dialog containing: "The program can not start because api-ms-win-crt-runtime-l1-1-0.dll is missing on the computer. Try reinstalling the program to correct this problem."

![image](https://user-images.githubusercontent.com/20912881/30446835-26e7846a-993f-11e7-9129-127732ccb614.png)

## Environment data
`dotnet --info` output:

N/A - running `dotnet --info` fails with the same error.

**Comment by livarcocc** [comment]
How did you install the CLI on this box?

**Comment by steveharter** [comment]
Also can you check that you have the [uCRT ](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows)(universal CRT) installed.

**Comment by seancpeters** [comment]
The CLI was installed from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-win-x64.exe

I am not certain about the universal CRT.

This bug was reported by our testing team, so my information is unfortunately a bit limited.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3220
