### ISSUE TITLE
dotnet run with windows authentication and without httpsys or weblistener

### ISSUE THREAD

**Issue by reft** [dotnet/cli#7656]
## Steps to reproduce
1. Start a new dotnet 2.0 project with windows authentication.
2. dotnet run

## Expected  behavior
Should authenticate user.

Is windows authentication not supported without httpsys or weblistener?
How are you supposed to develop locally when you deploy your app in IIS without httpsys or weblistener. Am I forced to use iis express?! :(

## Actual behavior
Should authenticate user! ;)

## Environment data
2.0

**Comment by Eilon** [comment]
This issue was moved to aspnet/Security#1432
