### ISSUE TITLE
Can't specify bitness when running dotnet test with nunit

### ISSUE THREAD

**Issue by damageboy** [dotnet/cli#7673]
## Steps to reproduce
Run dotnet test on a assembly with nunit:
```
dotnet test -- TargetPlatform=x64
```

## Expected  behavior
Be able to specify bitness (x64 / x86)

## Actual behavior
Always runs on x86 in Windows by default

## Environment data
`dotnet --info` output:

```
C:\projects\junk.git\tests\Junk.Tests>dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by dasMulli** [comment]
When you type `where dotnet` in the console, which path to `dotnet.exe` do you get? If you use the 32bit version in `Program Files (x86)`, then you can't run 64 bit tests and vice versa.

**Comment by livarcocc** [comment]
There is no --TargetPlatform option for dotnet test. Am I missing something? Did you mean `/p:TargetPlatform=x64`?

**Comment by wli3** [comment]
``` csharp
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace testvstest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.AreEqual("X86", System.Runtime.InteropServices.RuntimeInformation.OSArchitecture.ToString());
        }
    }
}
```

is the count as a repo of this issue

![image](https://user-images.githubusercontent.com/6993335/30556347-5efee938-9c5f-11e7-87be-e86fc135bde1.png)

**Comment by damageboy** [comment]
I'm not sure I'm understanding this whole thing properly, but I guess the real question is: Are there common configuration switches / parameters shared by all unit test adapters in the dotnet-cli world?

Or is this something that has to get dealt with by every adapter separately?

The [vstest documentation](https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md#overview) seems to specifically specify that the way to do this is:
```
dotnet test -s test.runsettings -- RunConfiguration.Platform=x64
```

As I mentioned before, the real question remains if dotnet-cli has a standard way of doing this, or is this a per-adapter issue...

**Comment by wli3** [comment]
dotnet cli does not have a standard way today. Things after -- is pass-through to vstest.

**Comment by livarcocc** [comment]
Moving this to the vstest repo, where they can answer your questions better than we can.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1296
