### ISSUE TITLE
error: Value cannot be null. error: Parameter name: projectUniqueName

### ISSUE THREAD

**Issue by d223chen** [dotnet/cli#7675]
## Steps to reproduce
`dotnet add package WindowsAzure.Storage --version 1.7.0`

## Expected  behavior
Some success message indicating that the package has been added as a reference to the *.csproj file in the current working directory.

## Actual behavior
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing C:\Users\dchen\AppData\Local\Temp\tmpE349.tmp
info : Adding PackageReference for package 'WindowsAzure.Storage' into project 'C:\Source\dchen\...\...\...\....csproj'.
error: Value cannot be null.
error: Parameter name: projectUniqueName

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by livarcocc** [comment]
@wli3 can you check if this has been addressed in the 2.0 SDK?

**Comment by wli3** [comment]
No repo in 2.0 SDK
![image](https://user-images.githubusercontent.com/6993335/30606789-bdf8885e-9d27-11e7-8276-80aa66f0c76e.png)
