### ISSUE TITLE
dotnet: failed to create a F# project on Debian with SDK 2.0.0

### ISSUE THREAD

**Issue by randomizedthinking** [dotnet/cli#7678]
## Steps to reproduce

    dotnet new console -lang F#

## Expected  behavior

A F# project is created.

## Actual behavior

The following error is received.

    The template "Console Application" was created successfully.                                                                                                                                                                                  
    
    Processing post-creation actions...
    Running 'dotnet restore' on /home/xxx/fsharp/fsharp.fsproj...
      Restoring packages for /home/xxx/fsharp/fsharp.fsproj...
    
    Restore failed.
    Post action failed.
    Description: Restore NuGet packages required by this project.
    Manual instructions: Run 'dotnet restore'

Also, a manual call of `dotnet restore` does nothing. Build and run will fail as well.

## Environment data
`dotnet --info` output:

    .NET Command Line Tools (2.0.0)
    
    Product Information:
     Version:            2.0.0
     Commit SHA-1 hash:  cdcd1928c9
    
    Runtime Environment:
     OS Name:     debian
     OS Version:  9
     OS Platform: Linux
     RID:         linux-x64
     Base Path:   /usr/share/dotnet/sdk/2.0.0/
    
    Microsoft .NET Core Shared Framework Host
    
      Version  : 2.0.0
      Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by svick** [comment]
> a manual call of `dotnet restore` does nothing.

Does it print a more specific error message?

**Comment by randomizedthinking** [comment]
With any further options, the command emits no real useful information. Attached is the output when the option `-v detail` is set. One message caught my eyes is:

    Project file contains ToolsVersion="". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.

Let me know if it is helpful.

[restore-message.txt](https://github.com/dotnet/cli/files/1314876/restore-message.txt)

**Comment by livarcocc** [comment]
It seems to me like a crash is happening, because the logs seem to be interrupted. @steveharter can you take a look? How can we investigate if a crash is indeed happening?

**Comment by randomizedthinking** [comment]
I have two machines both Debian. Just tried, the same problem happened on both of them.

**Comment by livarcocc** [comment]
Are they both Debian 9? Do you have a debian 8 machine to try this at?

**Comment by randomizedthinking** [comment]
Both of machines are Debian 9... sorry that I don't have a Debian 8 to test.

**Comment by wli3** [comment]
I cannot repo it on a Debian 9 Azure VM https://azuremarketplace.microsoft.com/en-us/marketplace/apps/credativ.Debian9?tab=Overview
![image](https://user-images.githubusercontent.com/6993335/30670803-b1573248-9e18-11e7-985f-46249f76fcfc.png)

**Comment by livarcocc** [comment]
@emgarten can you help us debug this? From the logs, it seems like restore simply stops.

@randomizedthinking I wonder if you are hitting https://github.com/dotnet/core/issues/973. We had multiple people hitting seg faults in Debian when using libssl, because they are using an older version of libssl.

Do you have anything special in a NuGet.COnfig somewhere? How did you install the CLI?

**Comment by randomizedthinking** [comment]
@livarcocc @wli3 thanks for the help... now it works after removing the libssl1.0.0 library.

It didn't ring a bell to me at first since the csharp counterpart works. Likely, the dotnet did something slight different on fsharp projects from csharp projects.
