### ISSUE TITLE
"dotnet new mvc -lang f#" failing with switch "-au" on Windows 10 64 bit

### ISSUE THREAD

**Issue by MikeGale** [dotnet/cli#7687]
## Steps to reproduce

1. dotnet new mvc -lang F# -o AspNetCoreFS -au Individual

## Expected  behavior

Generate an F# mvc web site.  (--help says that this can be done.)

## Actual behavior

Fails with error:
```
Invalid input switch:
  -au
  Individual
Run dotnet new mvc --help for usage information.
See https://aka.ms/dotnet-install-templates to learn how to install additional template packs.
```
(CSharp mvc is generated as expected.)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by am11** [comment]
It seems like if any of the user supplied argument is meant for cli's top-level command (`dotnet-new` in this case), the argument parser considers all the rest of the arguments are meant for top-level command as well. In this case `-au Individual` was actually meant for `mvc` sub-command.

In case of `dotnet new mvc -au Individual` (which is supposed to be a shorthand of `dotnet new --language C# mvc -au Individual`), the CLI propagates the argument handling to sub-command nicely.

`dotnet new` without `-lang` == `dotnet new -lang C#`, but args parsing rules that are applied to the shorthand are inconsistent. Would be nice if CLI simply pass-through the unknown arguments to subcommand in all cases or have the consistent behavior one way the other.

@MikeGale, the workaround is to use the argument separator ` -- ` (with spaces around), e.g.

```console
dotnet new mvc -lang F# -- -au Individual --no-restore
```

**Comment by livarcocc** [comment]
@wli3 can you take a look?

@mlorbetske @seancpeters FYI

**Comment by wli3** [comment]
This issue was moved to dotnet/templating#1515
