### ISSUE TITLE
Make it possible to invoke the compiler directly

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/cli#7689]
Not sure whether this belongs in the SDK repo instead.

In the desktop world, most people build with MSBuild on the command line or in VS. But for quick experimentation, learning c#, or custom scripts, one can invoke csc.exe directly. This has the advantage of being very fast, and not needing a project file. In that situation csc adds some default references so you simply run `csc Program.cs`. It is implicit that you are getting no help resolving references, so this is not a good way to make shipping software, unless you really want something custom and know what you're doing. When you are done experimenting, you should make a project file. This scenario has worked well since .NET Framework v1.

Can we support this scenario for .NET Core? This would be a supported shortcut for `dotnet C:\Program Files\dotnet\sdk\...version..\Roslyn\csc` that would also add some basic default references.

cc @ViktorHofer @stephentoub

**Comment by dasMulli** [comment]
Fyi there was a related question on StackOverflow: https://stackoverflow.com/questions/46065777/is-it-possible-to-compile-a-single-file-with-net-core

While using `RunCsc.sh` directly is possible, it would be nice to have a `dotnet csc` command that adds all the reference dlls. A problem here is that AFAIK .NET Core doesn’t include its own reference assemblies so there may be differences to a project build

**Comment by mellinoe** [comment]
If a command was exposed, I don't think it should automatically add any references, or do anything else "special" -- it should just be equivalent to using csc today where you need to provide such things.

**Comment by ViktorHofer** [comment]
I don't think that `dotnet csc` should automatically include required reference assemblies. The point of csc is that you define which assemblies you want to compile against.

**Comment by dasMulli** [comment]
`csc.exe` adds mscorlib.dll automatically AFAIK.. Would it make sense to add `netstandard.dll` on .NET Core?

As I pointed out on SO, the current behaviour is:

```sh
$ /usr/local/share/dotnet/sdk/2.0.0/Roslyn/RunCsc.sh Program.cs
Microsoft (R) Visual C# Compiler version 2.3.2.61921 (ad0efbb6)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(1,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
Program.cs(5,11): error CS0518: Predefined type 'System.Object' is not defined or imported
Program.cs(7,26): error CS0518: Predefined type 'System.String' is not defined or imported
Program.cs(7,16): error CS0518: Predefined type 'System.Void' is not defined or imported
```

**Comment by livarcocc** [comment]
This does not feel like a basic command like build, run, publish, test etc and we have been trying to keep the "native" CLI verbs to a minimum. So, I don't believe we would take building such a command in the CLI. We have been talking quite a bit about global commands and this seems like a good candidate for such a thing.

**Comment by ViktorHofer** [comment]
As you are closing the issue, do you note this request somewhere or can give a timeline for it?

**Comment by dasMulli** [comment]
There are currently two command wish lists that I know of:
https://github.com/dotnet/cli/issues/4672
https://github.com/dotnet/cli/issues/6223
