### ISSUE TITLE
dotnet new creates files with CRLF line endings on linux

### ISSUE THREAD

**Issue by kromatic** [dotnet/cli#7695]
## Steps to reproduce

Run `dotnet new classlib` in new project folder. 

## Expected  behavior

On Linux, this should create Class1.cs and .csproj files with LF line endings.

## Actual behavior

Class1.cs and the .csproj file are both created with CRLF line endings. (Files in bin and obj folders appear to all have the correct LF line endings.)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     fedora
 OS Version:  26
 OS Platform: Linux
 RID:         fedora.26-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1248
