### ISSUE TITLE
dotnet-install.sh fails if LD_LIBRARY_PATH doesn't exist

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/cli#7698]
## Steps to reproduce
```bash
unset LD_LIBRARY_PATH
curl -O https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
chmod +x ./dotnet-install.sh
./dotnet-install.sh
```

## Expected  behavior
dotnet installed

## Actual behavior

```bash
./dotnet-install.sh: line 210: LD_LIBRARY_PATH: unbound variable
```

## Workaround

```bash
export LD_LIBRARY_PATH=
```

It appears on Ubuntu 16.04, this env var doesn't exist.  Script should check if it exists before using.

**Comment by SteveL-MSFT** [comment]
This is breaking PowerShell Core Travis-CI on MacOS.  How quickly can this get fixed?

**Comment by livarcocc** [comment]
We will probably look into it tomorrow.

**Comment by SteveL-MSFT** [comment]
I'll put the workaround in place then.
