### ISSUE TITLE
Create a Microsoft/Docker image on DockerHub for Dotnet CLI

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#77]
Microsoft/Dotnet Docker Images
===========

**NAME** 
microsoft/dotnet Docker Images

**SYNOPSIS**
We intend to get developers from "zero to Dockerized" quickly but we also want a credible presence in the Docker community. We will do so by providing variant images that cater to real-world uses that showcase the versatility of dotnet. With our focus on high-performance microservice scenarios, we will illustrate the ability for developers to build slim, low-overhead containerized apps.

**DESCRIPTION**
	
1. Image Repository.

	Developers will acquire Dotnet images from Docker Hub. Docker Hub establishes public and official repositories:
	
	Official images are curated repositories of images that are promoted in Docker Hub. The Official Repositories is run by a team sponsored by Docker Inc. (not employees of Docker Inc). There is an extensive vetting process for acceptance into the Official repository. Official images must provide a consistent experience and adhere to Dockerfile best practices and documentation standards. https://docs.docker.com/docker-hub/official_repos/
		
	Public images are not promoted in Docker Hub but do not have to pass the Official vetting process and so are more amenable to changing, early release images. Currently ASP.NET publishes their image in the public repository under the Microsoft/dotnet tag. 
		
	For the November release, the Dotnet image will be published in the public repository under the Microsoft tag. As we get community feedback and the Dotnet image matures we will begin the process of moving to the Official repository. 
	
2. Base image - supports in-container building and running of apps. Requires developers to author derived images.
		

	For a full development experience image the dotnet image should be based off of buildpack-deps images (e.g. buildpack-deps:jessie or buildpack-deps:wheezy). These image pre-installs basic build and ancillary tools like curl, git, etc. and is used as a base for many language images (Node, Ruby, Python).
		
	An alternative, less heavy-weight image, the Dotnet image can be based off of debian images.
	
	
		
3. ONBUILD image - supports in-container building and running of apps but does not require authoring of derived images.

	ONBUILD variants are based off of dotnet base images
		
4. -Slim image - supports running of the app but not the build process within the container.

	With this image a dotnet publish output can be copied to the image and run with minimal overhead since there is no need for any build/compiler tooling to be pre-installed in the image.
  
5. Versioning

6. Documentation

7. Security, servicing
	Potentially enable linked builds

**Comment by glennc** [comment]
@dleeapho It doesn't though, there are packages that have to be installed in order for a published coreclr application to work. Unless we are changing that or I am misunderstanding something? I need icu for example in order to run my published app.

**Comment by dleeapho** [comment]
@glennc I think you are right, we still need to think about the packages (like ICU) that are needed for all .net core apps. I'll move the --slim issue to dotnet-docker #16

**Comment by jasonwilliams200OK** [comment]
Since Docker is neither a VM nor a Jail, so it is bit tricky to get stuff out of the machine.
To build corefx and get the `bin` directory out from docker, we can get Docker file have this line `RUN tar -cvzf bins.tar.gz bin/` and then `cat` out the zipped file:

```sh
mkdir build
cd build

# obtain (wget) the Dockerfile for corefx from somewhere
# (say automated build steps for some distro of Linux)

docker build --tag corefx-binaries .
docker run corefx-binaries cat /corefx/bins.tar.gz > bins.tar.gz
tar -zxvf bins.tar.gz

# now distribute the assemblies / binaries!
```

**Comment by blackdwarf** [comment]
@dleeapho can we close this issue?

**Comment by pootow** [comment]
docker run -it microsoft/dotnet
root@a968e82a2801:~# dotnet new

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted (core dumped)

**Comment by blackdwarf** [comment]
@dleeapho can you take a look? Seems like the Dockerfile is not getting the newest bits (the exception means that the "new" command is not found).

@pootow can you try to issue `dotnet init` and see if you get the correct behavior?

**Comment by pootow** [comment]
@blackdwarf dotnet init works，thanks

**Comment by piotrpMSFT** [comment]
Whoa... Those are really old CLI bits, then...

**Comment by blackdwarf** [comment]
Yeah, we should look into this.

**Comment by brthor** [comment]
@dleeapho Are we rebuilding the docker image with cli bits on any schedule or is it a manual step?

If not, should we consider adding this as a publish step to the cli repo?

**Comment by dleeapho** [comment]
@brthor the linking of docker images to cli builds is logged here: https://github.com/dotnet/dotnet-docker/issues/14. But yes, @MichaelSimons we need to freshen the docker images to pickup "new" and other changes.

**Comment by blackdwarf** [comment]
@dleeapho @Petermarcu  seems like the overall work that the issue targets is done for now. Let's open new issues if the Docker image(s) need to be refreshed with bits. Will close this one. If you think it should be reopened, please reopen.
