### ISSUE TITLE
Random build/restore/publish errors on docker. (returned a non-zero code: 139)

### ISSUE THREAD

**Issue by djsowa** [dotnet/cli#7706]
## Steps to reproduce
```
FROM microsoft/dotnet:2.0-sdk

# Set working dir or docker to /app
WORKDIR /app

RUN dotnet --info
# Restore code dependecies - packages will be downloaded.
RUN dotnet new console -o ./src
RUN dotnet restore ./src --disable-parallel -v diag

# publish application(build included) into /app directory

RUN dotnet build ./src -v diag
RUN dotnet publish ./src --output /app -v diag

# run console application on docker.
ENTRYPOINT ["dotnet"]
```

## Expected  behavior

Build succesfully

## Actual behavior

I'm receiving random errors, some times error occur on restore, sometimes on build and sometime on publish step, now(update) occurred even on dotnet new step.

Restore:
> Service 'NAME' failed to build: The command '/bin/sh -c dotnet restore ./src --disable-parallel -v diag' returned a non-zero code: 139

Build:
> Service 'NAME' failed to build: The command '/bin/sh -c dotnet build ./src' returned a non-zero code: 139

New:

> The command '/bin/sh -c dotnet new console -o /app/src' returned a non-zero code: 139

[Diagnostic logs](https://pastebin.com/QdVH1XnR)

## Environment data
```
RUN dotnet --info
 ---> Running in 6b2d67b6fcd6
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by livarcocc** [comment]
@steveharter can you take a look? This is a crash in native code.

**Comment by djsowa** [comment]
Update: similar errors occurred also on:
microsoft/dotnet:latest
microsoft/dotnet:2.0-sdk-jessie

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3233
