### ISSUE TITLE
dotnet restore fails when more than 100 artifacts match the package id

### ISSUE THREAD

**Issue by Andresbu** [dotnet/cli#7707]
Artifactory contains more than 100 packages matching id "Serilog". dotnet restore fails as it seems to read only the first 100 packages and not more. Reason seems to be an invalid GET for fetching the pages after the first one. See below.

## Steps to reproduce
Use any of the docker images (It fails for me with those, I havent tested others)
- microsoft/dotnet:2.0.0-sdk
- microsoft/dotnet:1.1.4-sdk
- microsoft/dotnet:1.1.2-sdk

Create a project
- dotnet new console
- dotnet add package Serilog -v 2.5.0

Configure an own Artifactory (serving as a mirror within our company)
- Make sure that i.e the configured dependency "Serilog" produces more than 100 matches
- See NuGet.Config attached (had to append suffix .txt due to github)
[NuGet.Config.txt](https://github.com/dotnet/cli/files/1333093/NuGet.Config.txt)

Restore dependencies
- dotnet restore

## Expected  behavior
- Dependency Serilog gets restored

## Actual behavior
Restore fails with "Unable to find ...."

```
         /builds/x/devops/ev-dotnet-container/test/test.csproj : error NU1102: Unable to find package Serilog with version (= 2.5.0)
       /builds/x/devops/ev-dotnet-container/test/test.csproj : error NU1102:   - Found 100 version(s) in Z-Artifactory [ Nearest version: 1.3.39 ]
       /builds/x/devops/ev-dotnet-container/test/test.csproj : error NU1102:   - Found 0 version(s) in /usr/share/dotnet/sdk/NuGetFallbackFolder
``` 

A first analysis on my side reveals the following. HTTP calls made:
- GET https://HOST/artifactory/api/nuget/nuget-notcleared-remote/FindPackagesById()?id='Serilog'
- GET https://HOST/artifactory/api/nuget/nuget-notcleared-remote/?id='Serilog'&$skip=100

Observe, that the later one is missing 'FindPackagesById()'! And this actually seems to be the cause.

OK but wrong content!
- GET https://HOST/artifactory/api/nuget/nuget-notcleared-remote/?id='Serilog'&$skip=100

OK and correct content
- GET https://HOST/artifactory/api/nuget/nuget-notcleared-remote/FindPackagesById()?id='Serilog'&$skip=100

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5942
