### ISSUE TITLE
Not able to build .Net Standard Sln file on linux

### ISSUE THREAD

**Issue by ali198** [dotnet/cli#7714]
I am trying to build .Net Standard Sln file on linux. But it fails with below mentioned error.

## Steps to reproduce
1. dotnet build MyProj.sln

## Expected  behavior
Build successfully

## Actual behavior
/MyPath/MyPath.csproj.metaproj : error MSB4025: The project file could not be loaded. Could not find file '/MyPath/MyPath.csproj.metaproj'.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
Are you invoking MyPath.sln or MyProj.sln? What happens for sln files is that MSBuild generates a project for it behind the scenes, but I would expect it to be called after the sln file.

**Comment by livarcocc** [comment]
I just tried this on OSX successfully.

slnfolder
  - lib folder
  - sln file

dotnet build slnfolder.sln and it succeeded.

Closing this issue. Please, comment or re-activate when you can give us more details.
