### ISSUE TITLE
dotnet-pack incorrectly defaults the artifacts source path to the package output path

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#772]
When basePath is not provided, dotnet-pack looks for build artifacts, which should become the contents of the package, in the outputPath. However, when outputPath is provided via the `--output` parameter, this value proves incorrect. Compilation artifacts are placed and left in the package output path. This creates opportunity for parallel build to cause multiple invocations of the pack command to stomp on one-another's intermediary files [the compile output] and also adds confusion by leaving unexpected artifacts in the --output directory.

When performing a dotnet-pack which in turn performs a compilation, we should put the compilation output into a private temporary directory and then clean up after ourselves. The only visible side-effect of a pack operation should be the package itself.

**Comment by davidfowl** [comment]
Noooo, leaving the build artifacts is super useful. I use it like 94% of the time when I want to see what ended up in the package

**Comment by piotrpMSFT** [comment]
Hmm, in that case where should the artifacts go? Putting them in the root of the packages folder assumes no file name collisions across packages, and it doesn't help determine what went into which package. perhaps {packageRoot}/ProjectName/Tfm/Rid/?

Dumping everything into a flat directory structure is pretty dangerous...

**Comment by livarcocc** [comment]
I am not sure this is an issue with pack but maybe with dotnet build. Whenever you specify an output for dotnet build, it does not append the framework folders to it. So, dotnet build will put the contents at bin\Debug\dnxcore50, but dotnet build --output bin\debug will put the contents right there. No folders created for the framework.

Maybe we should do that. Also, we probably should unify the logic to "calculate" these paths and have it shared across the commands. If it is already, please let me know and I will integrate it into the pack command, which wasn't/isn't making use of it.

**Comment by livarcocc** [comment]
Fixed with the addition of basePath parameter and with the fix to add {config}/{tfm} to output path.
