### ISSUE TITLE
Unable to use @angular/cli commands in angular template 

### ISSUE THREAD

**Issue by saurav-sahu** [dotnet/cli#7724]
## Steps to reproduce
dotnet new angular && npm install

## Expected  behavior
angular template

## Actual behavior
angular template with all files except a .angular-cli.json. No ng (@angular/cli) commands work.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```

**Comment by livarcocc** [comment]
@SteveSandersonMS can you take a look? Is there a repo where this issue is more appropriate? Or else, we can just track it here.

**Comment by SteveSandersonMS** [comment]
The current template can be used to a limited extent with Angular CLI if you add your own `.angular-cli.json` file to point the `generate` commands to the correct paths.

Going forwards, we're in the process of [revamping the Angular template significantly](https://github.com/aspnet/JavaScriptServices/issues/1288). The new one is completely based around Angular CLI. We're hoping to ship this with ASP.NET Core 2.1.
