### ISSUE TITLE
Excluding web.config from publish

### ISSUE THREAD

**Issue by petronellius** [dotnet/cli#7727]
## Steps to reproduce
Do not add web.config to Asp.Net Core project. Publish project through VS2017 to folder.
Publish output contains web.config.

Same happens even when web.config is explicitly excluded from publish in project file:
`<None Update="web.config" CopyToPublishDirectory="Never" />`

## Expected  behavior
Publish output will not contain web.config

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by guardrex** [comment]
@petronellius Use ...
```xml
<PropertyGroup>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
</PropertyGroup>
```
... in your project file. See: https://docs.microsoft.com/aspnet/core/publishing/iis#webconfig

**Comment by petronellius** [comment]
@guardrex Fantastic, it's working. Thanks.
