### ISSUE TITLE
dotnet-pack produces empty NuGet packages when used with --output and path to pj

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#773]
This is a new issue since we added --basePath

When calling `dotnet pack --output={somepath} {pjPath} the resultant NuPkg do not include a lib directory.

**Comment by livarcocc** [comment]
Looking.

**Comment by livarcocc** [comment]
PR #791 has a fix for this, however, I believe the discussion going on #772 is extremely relevant this and may lead to a different solution to this problem.
