### ISSUE TITLE
dotnet add package errors out if any source fails to resolve

### ISSUE THREAD

**Issue by cjqed** [dotnet/cli#7740]
## Steps to reproduce
1. Add a nuget source `nuget sources add -Name xxx -Source https://my_local_nuget_server/nuget/...`
2. Take the nuget source offline (in my case, it's locked down behind a VPN I was not connected to)
3. Attempt to add a package that exists from public sources, e.g. `dotnet add package dapper`
4. The add package fails because the previous source is offline:

```
info : Adding PackageReference for package 'dapper' into project 
log  : Restoring packages for 
info :   GET http://my_offline_nuget_server/nuget/FindPackagesById()?id='dapper'
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'http://my_offline_nuget_server/nuget/FindPackagesById()?id='dapper''.
log  : An error occurred while sending the request.
log  :   The server name or address could not be resolved
info :   GET http://my_offline_nuget_server/nuget/FindPackagesById()?id='dapper'
info :   GET https://www.nuget.org/api/v2/FindPackagesById()?id='dapper'
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'http://my_local_nuget_server/nuget/FindPackagesById()?id='dapper''.
log  : An error occurred while sending the request.
log  :   The server name or address could not be resolved
info :   GET http://my_local_nuget_server/nuget/FindPackagesById()?id='dapper'
error: Failed to retrieve information about 'dapper' from remote source 'http://my_local_nuget_server/nuget/FindPackagesById()?id='dapper''.
error:   An error occurred while sending the request.
error:   The server name or address could not be resolved

```

## Expected  behavior
If the package exists in public repositories, warnings should be logged but the package should be downloaded.

## Actual behavior
The package is not downloaded, the command fails to execute.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.1.0)

Product Information:
 Version:            1.1.0
 Commit SHA-1 hash:  d6f4336106

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0
```

Not sure if this is an intentional decision in case a user has a more up-to-date version of a package they are expecting to get from their offline source, but accidentally get a different one. If so, please close this issue. However, I would expect that a warning be logged and the best, available match be downloaded.

Thank you.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5978

**Comment by livarcocc** [comment]
I suggest following the NuGet issue that I created above.
