### ISSUE TITLE
Possible mistake in ProjectInstanceExtensions

### ISSUE THREAD

**Issue by xtmq** [dotnet/cli#7742]
Take a look at src/dotnet/ProjectInstanceExtensions.cs line 26. 
You read a property value for "ProjectTypeGuid". But as far as I know there is only "ProjectTypeGuid**s**". 
My case - dotnet sln add command. You incorrectly retrieve project type guid and write it in a solution file.

**Comment by livarcocc** [comment]
@peterhuene can you take a look?

**Comment by peterhuene** [comment]
Hi @xtmq,

Thank you for reporting this issue.  You are correct that there is a typo in reading this property.  The correct property name is indeed `ProjectTypeGuids`.  I will work on a fix.

**Comment by peterhuene** [comment]
Hi @xtmq.  The fix for this issue should be in the next preview release of the .NET SDK.  Thanks again for reporting this to us!
