### ISSUE TITLE
"dotnet test" works whereas "msbuild /t:VSTest" fails

### ISSUE THREAD

**Issue by pchalamet** [dotnet/cli#7744]
## Steps to reproduce
`dotnet test` works as expected but "msbuild /t:VSTest" does not work:

```
error MSB4057: The target "VSTest" does not exist in the project.
```

## Expected  behavior
Looks like `dotnet test` is just `/t:VSTest` underneath so I just expected this to work.

## Actual behavior
`dotnet /t:VSTest` fails

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

`msbuild /version` output:
```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.3.409.57025
```

**Comment by livarcocc** [comment]
It is just /t:VSTest, however, I am not sure where the test targets/tasks are binplaced for full msbuild.

Can you try dotnet msbuild /t:VSTest, this will invoke the target using the portable MSBuild installed with the SDK. If this works, then I will move this issue to microsoft/vstest where they will be able to answer how to run it using full msbuild.

**Comment by pchalamet** [comment]
dotnet test & dotnet msbuild work OK.
So it's an msbuild related problem - you are probably right.

Will you move the issue to msbuild or should I ?
Thanks !

**Comment by dasMulli** [comment]
What system are you running it on? Maybe full-framework msbuild.exe via a VS 2017 Build Tools installation?

The msbuild distribution (whether it be the `dotnet`, VS / VS build tools or mono) need to contain the necessary VSTest bits.

**Comment by pchalamet** [comment]
Windows 10, Visual Studio Community 2017 (15.3.5), Developer Command Prompt for VS 2017

msbuild /version output:
```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

15.3.409.57025
```

How can I check I have the VSTest bits ?
But not other error in build output but `error MSB4057: The target "VSTest" does not exist in the project.`

**Comment by livarcocc** [comment]
Let me move this to the microsoft/vstest repo.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1155
