### ISSUE TITLE
Add x64 native tools to documentation (for usage)

### ISSUE THREAD

**Issue by factormystic** [dotnet/cli#775]
After `dotnet new` and `dotnet restore` (which appear to work fine, as does `dotnet run`), I get an error doing a native compile:
```
PS C:\users\Public\hello-world> dotnet compile --native
Compiling hello-world for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.8077755
Input Assembly: C:\users\Public\hello-world\bin\Debug\dnxcore50\hello-world.dll
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
Linking of intermediate files failed.
```

And with `-c Release` as suggested here https://github.com/dotnet/cli/issues/633
```
PS C:\users\Public\hello-world> dotnet compile --native -c Release
Compiling hello-world for DNXCore,Version=v5.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.8150396
Input Assembly: C:\users\Public\hello-world\bin\Release\dnxcore50\hello-world.dll
LINK : fatal error LNK1181: cannot open input file 'kernel32.lib'
Linking of intermediate files failed.
```
Installed just now from `https://dotnetcli.blob.core.windows.net/dotnet/dev/Binaries/Latest/dotnet-win-x64.latest.zip`

Environment:
```
PS C:\users\Public\hello-world> dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
```

**Comment by factormystic** [comment]
Related? https://github.com/dotnet/corert/issues/606

**Comment by brthor** [comment]
Are you inside x64 Native Tools Command Prompt?

**Comment by factormystic** [comment]
It was just normal command prompt. Switching to the VS 2015 one as you suggests fixes the error. I suppose this should flow into documentation/wiki somewhere? Or is this behavior expected to change by the final release?

**Comment by brthor** [comment]
This behavior is expected to change (see #301), but indeed this should be in the documentation. I thought it was somewhere but can't seem to find it.

**Comment by blackdwarf** [comment]
We need to document the fact that you need to run the native compilation within a certain context (cmd prompt).
