### ISSUE TITLE
It looks like EFCORE is still useless compared with EF6

### ISSUE THREAD

**Issue by 19317362** [dotnet/cli#7750]
many issues.  migerations, reverse generations, Model  Creating s...

**Comment by livarcocc** [comment]
I am not sure exactly what you are trying to do, but if you provide more details about the issues you are running into, we may be able to help you. Also, there is a separate repo just for EF Core, under aspnet/entityframeworkcore, where it may be possible for you to get better and more timely answers to your questions/issues.

**Comment by livarcocc** [comment]
Closing this issue since it seems some progress has been made on the other issue I moved to aspnet/entityframeworkcore and this issue here is not actionable.
