### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by pichasepongc-tit** [dotnet/cli#7758]
## Environment data
`dotnet --info` output:
![2017-10-04_9-41-34](https://user-images.githubusercontent.com/19162319/31157945-918c2e3e-a8e8-11e7-8c75-46f7a0a8fbb2.jpg)
![2](https://user-images.githubusercontent.com/19162319/31157953-98f6229c-a8e8-11e7-9144-dba2fec9c363.jpg)
![3](https://user-images.githubusercontent.com/19162319/31157955-9cca0186-a8e8-11e7-8a87-2810a83810b8.jpg)

**Comment by davidfowl** [comment]
Can you fill in the bug details?

**Comment by pichasepongc-tit** [comment]
Yes,
The project is Load Fail.
Before Installed DotNetCore.1.0.0-SDK.Preview2-x64 And Add File global.json
It's still a problem.

**Comment by davidfowl** [comment]
There isn't enough information to help you.

**Comment by pichasepongc-tit** [comment]
i open Project Successful ,But 
![2017-10-04_10-58-04](https://user-images.githubusercontent.com/19162319/31159414-02073c12-a8f3-11e7-8657-eb815ee0c981.jpg)

**Comment by davidfowl** [comment]
Sure, but you haven't provided anything but dialogs. Let me try to diagnose your problem with the limited information I have:

- Try uninstalling all versions of .NET Core
- Updated to VS 2017 then install .NET Core 1.0.0, don't use the unsupported preview versions https://www.visualstudio.com/downloads/.
- Delete your global.json

See if that works.

**Comment by pichasepongc-tit** [comment]
if use VS 2015, How to Problme

**Comment by livarcocc** [comment]
This seems like you are trying to use VS2015 with a version of dotnet core that is higher than 1.0.0-preview2. That will not work. The last version of the CLI that supported VS2015 with project.json was 1.0.0-preview2. You cannot move to a higher version while working with the combination above.

**Comment by pichasepongc-tit** [comment]
Thank too @davidfowl  and @livarcocc

**Comment by livarcocc** [comment]
It seems like the issue has been addressed, from your comment above, so I am closing this issue. If that's not the case, please just comment and say so and I will re-activate it.
