### ISSUE TITLE
dotnet new does not consider local nuget.config

### ISSUE THREAD

**Issue by vshapenko** [dotnet/cli#7760]
## Steps to reproduce

1. Configure some nuget sources in visual studio(2015,2017, no matter).
2. Create an empty folder.
3. Create nuget.config with a following content:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
    </config>
    <packageSources>
    <clear /> <!-- ensure only the sources defined below are used -->
    <add key="nuget" value="https://nuget.org/api/v2/" />
    </packageSources>
</configuration>
```

As we see, all other sources except nuget.org should be removed

4. Run, for example , dotnet new -i "giraffe-template::*" in folder.
5. See the message (something like this):

  Retrying 'FindPackagesByIdAsyncCore' for source 'https://mysource/api/FindPackagesById()?id='giraffe-template''.
  Response status code does not indicate success: 404 (Not Found).
  
## Expected  behavior
dotnet new should consider package sources configured in local nuget.config

## Actual behavior

dotnet new ignores local nuget.config

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1266
