### ISSUE TITLE
Merge latest F# bits in 15.5 branch

### ISSUE THREAD

**Issue by cartermp** [dotnet/cli#7761]
This is a tracking bug.  @KevinRansom recently fixed a bug in assembly resolution which was resulting in a StackOverflow exception: https://github.com/Microsoft/visualfsharp/pull/3658

**Comment by cartermp** [comment]
@brettfo will be taking care of this in tandem with our insertion of F# tools for Preview 2

**Comment by livarcocc** [comment]
This should be done now.
