### ISSUE TITLE
nuget push can't handle paths with forward slash on windows

### ISSUE THREAD

**Issue by wojciechrak** [dotnet/cli#7764]
## Steps to reproduce
`nuget push C:\dev/nugets\*.nupkg`

## Expected  behavior
All packages in directory C:\dev\nugets are pushed to nuget repository.

## Actual behavior
Error is returned
`File does not exist (c:\dev/nugets\*.nupkg).`

## Additional notes
`nuget pack -OutputDirectory C:\dev/nugets\` or `nuget pack solutiondir/projectdir/project.csproj` work correctly
I am using standalone nuget.exe
NuGet Version: 4.3.0.4406

## Issue background
In our CI we are fetching feature branches from git and path on disk contains branch name, eg. "feature/123". This branch name is then used in our build scripts.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#5992
