### ISSUE TITLE
MSI installer is not signed

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#777]
(from @bendono in dotnet/coreclr#2589)

Following the .NET Core installation instructions for Windows, I downloaded the MSI installer.
Path: https://dotnet.github.io/getting-started/
OS: Windows 10

Upon installation, SmartScreen will attempt to block installation.
![msi](https://cloud.githubusercontent.com/assets/846533/12213523/f51de5de-b6bc-11e5-8a53-92acbf93c1e8.png)
Likely this is because the Publisher is not defined.

**Comment by piotrpMSFT** [comment]
Thanks @ellismg. @livarcocc is working on a permanent solution for this.

**Comment by livarcocc** [comment]
Yes. We are already tracking this here: #500. Closing this one.
