### ISSUE TITLE
.NET Core 2.0 SDK Build fail

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7774]
@wh1sp3r opened this issue here: https://github.com/dotnet/core/issues/946

Hello,
I updated my SDK to version 2.0 and I am not able to build my project for Framework 4.6.
I am using Microsoft.AspNetCore libraries in version **1.1.3**.

Output:
```
PM> dotnet build
Microsoft (R) Build Engine verze 15.3.409.57025 pro .NET Core
Copyright (C) Microsoft Corporation. Vçechna pr va vyhrazena.

app.config : error MSB3249: Konfiguraźnˇ soubor aplikace app.config je neplatně. Index and count must refer to a location within the string. [C:\Project\Project.csproj]
app.config : error MSB3249: Parameter name: destinationIndex [C:\Project\Project.csproj]

Build failed.

app.config : error MSB3249: Konfiguraźnˇ soubor aplikace app.config je neplatně. Index and count must refer to a location within the string. [C:\Project\Project.csproj]
app.config : error MSB3249: Parameter name: destinationIndex [C:\Project\Project.csproj]
    0 warningsˇ
    Erorr count: 1
```

Well, my app.config is not used and is almost empty
`<configuration>
   <runtime>
      <gcServer enabled="true"/>
   </runtime>
</configuration>
`

Worked fine before installing 2.0 SDK.

**Comment by livarcocc** [comment]
@wh1sp3r Can you share a repro of your issue with us?

**Comment by livarcocc** [comment]
Closing this issue until we can get clearer repro steps. If someone can provide those, please comment and I will re-activate this issue.
