### ISSUE TITLE
Publish dotnet core SDK to Chocolatey

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7779]
@JeffJacobson commented on [Mon Aug 14 2017](https://github.com/dotnet/core/issues/829)

Publish the .NET Core 2.0 SDK to Chocolatey repository.

Responding to [blog](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/) comment by @richlander 

> Chris McKenzie	
> 
> Would it be possible to publish the SDK installer to Chocolatey?
> 
>     23 mins ago
>     Reply
>     Rich Lander [MSFT]	
> 
>     We have been thinking about doing two things:
> 
>     – Publish the SDK to Chocolatey.
>     – Publish the SDK to Homebrew.
> 
>     Whomever wants those, please create an issue at the dotnet/core repo. Whichever one has the most feedback, we’ll do first.

---

@crmckenzie commented on [Tue Aug 15 2017](https://github.com/dotnet/core/issues/829#issuecomment-322503373)

I'd love to see this as a standard part of the release pipeline. Yay!

---

@scullinan commented on [Tue Aug 15 2017](https://github.com/dotnet/core/issues/829#issuecomment-322675837)

+1 for chocolatey

---

@ehouarn-perret commented on [Wed Aug 16 2017](https://github.com/dotnet/core/issues/829#issuecomment-322731328)

+1 for chocolatey

---

@beforan commented on [Wed Aug 16 2017](https://github.com/dotnet/core/issues/829#issuecomment-322811760)

+1 for chocolatey

---

@EdouardM commented on [Wed Aug 16 2017](https://github.com/dotnet/core/issues/829#issuecomment-322813352)

+1 for chocolatey

---

@tomlazelle commented on [Thu Aug 17 2017](https://github.com/dotnet/core/issues/829#issuecomment-323174159)

+1 for chocolatey

---

@chwebdude commented on [Wed Aug 23 2017](https://github.com/dotnet/core/issues/829#issuecomment-324547967)

+1 for chocolatey

---

@navimondo commented on [Wed Sep 13 2017](https://github.com/dotnet/core/issues/829#issuecomment-329345630)

+1 4 chocolatey

**Comment by livarcocc** [comment]
We currently have no plans to support chocolatey ourselves. We encourage the community to do so, in this case.

**Comment by Petermarcu** [comment]
Note that the community already has this: https://chocolatey.org/packages/dotnetcore-sdk
