### ISSUE TITLE
publish command with -o directive creating directories nested recursively

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7782]
@randolfrf commented on [Tue Aug 22 2017](https://github.com/dotnet/core/issues/885)

# Publish command with -o directive creates nested directories at the -o target

I have a brand new asp.net core 2 mvc web project. When I run: 

`$dotnet publish -c release -o ./app/compiled`

App is built in release mode and published to /app/compiled. Everything works fine. I have the following structure:
..
/app
/app/compiled/
/app/wwwroot/
/app/wwwroot/css
/app/wwwroot/images
/app/wwwroot/js
/app/wwwroot/lib
/app/wwwroot/lib/... (a few more inside lib, with lib data)
..

This structured is the intended one, but when trying to run again the command:

`$dotnet publish -c release -o ./app/compiled`

I end up with this structure:

..
/app
/app/compiled/
/app/compiled/app
/app/compiled/app/compiled
/app/compiled/app/compiled/wwwroot
/app/compiled/app/compiled/wwwroot/lib
/app/compiled/app/compiled/wwwroot/lib/... (a few more within lib, one for each package BUT WITHOUT CONTENT)
/app/wwwroot/
/app/wwwroot/css
/app/wwwroot/images
/app/wwwroot/js
/app/wwwroot/lib
/app/wwwroot/lib/... (a few more inside lib with lib data)
..

Every time I run the publish with output command a new /app/compiled/ directory with partial contents is being created in the previous /app/compiled/ directory. After 4 executions I end up having:

/app/compiled/app/compiled/app/compiled/app/compiled/

# General

I'm running .netCore 2, installed SDK from https://www.microsoft.com/net/download/core, on a fresh new machine running macOS 10.12.6. 

I'm running: 

`dotnet new mvc`

As template and that's all. No other nuget package, nor any other extension.

---

@randolfrf commented on [Tue Aug 22 2017](https://github.com/dotnet/core/issues/885#issuecomment-324185318)

Just to be clear, If I try again with another project (of another type) the behavior is the same.

**Comment by dasMulli** [comment]
I believe this came up before but can't find the issue now.

The reason is that when you publish into a sub-directory of a project, the publish output becomes part of the project automatically. So if you publish `foo.json` to `app/foo.json`, then the next publish call will include `app/foo.json` and publish it to `app/app/foo.json` and so on.

**Comment by dsplaisted** [comment]
By default the contents of your project folder are part of your project, which is what's causing the items under `app` to be published.  Some information about this is here: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

To avoid including the published app as source for the next publish of your project, add the following to a `PropertyGroup` in the project file:

```xml
<DefaultItemExcludes>$(DefaultItemExcludes);app/**</DefaultItemExcludes>
```

This will exclude everything in the `app` folder from your project.

**Comment by livarcocc** [comment]
Thanks @dsplaisted , this behavior is expected and we have a way to disable it as explained above. As such, I am closing this issue. If the solution above does not work for you, please comment and I will re-activate the issue and continue the discussion.

**Comment by randolfrf** [comment]
Understood, and it seems logic reasonably indeed. Thanks.
