### ISSUE TITLE
Cannot run application in another machine due to wrong path for dependencies. 

### ISSUE THREAD

**Issue by Leoat12** [dotnet/cli#7787]
## Steps to reproduce

1) Create a project with the following .csproj.

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win10-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="8.0.9-dmr" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="NUnit" Version="3.8.1" />
    <PackageReference Include="TweetinviAPI" Version="2.0.0" />
  </ItemGroup>
</Project>
```

2) Use the following commands:
```
PS> dotnet restore
PS> dotnet publish -c Release -r ubuntu.16.04-x64
```

3) Execute the program on Ubuntu machine.

## Expected  behavior

The applications is run successfully. 

## Actual behavior

It throws an error:
`Error:
  An assembly specified in the application dependencies manifest (Twitter.deps.json) was not found:
    package: 'Autofac', version: '4.6.0'
    path: 'lib/netstandard1.1/Autofac.dll'`

## Environment data

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

## Diagnostic 

It is failing to looking for the dependencies in the right place. On _runtimeconfig.dev.json_ file there is this in all deployments.

```json
{
  "runtimeOptions": {
    "additionalProbingPaths": [
      "C:\\Users\\leoat\\.dotnet\\store\\|arch|\\|tfm|",
      "C:\\Users\\leoat\\.nuget\\packages",
      "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder"
    ]
  }
}
```

These paths exist on my computer, but not in the target Ubuntu machine, of course. I can reproduce the error on my own computer by removing all these paths. As a self-contained deployment, it should be looking for the dependencies on the _publish_ folder, they are all there, but it is looking for them in the wrong place.

**Thanks you for the help!**

**Comment by livarcocc** [comment]
When you publish as a runtime specific app, all your dependencies should be copied to the publish folder: `bin/<configuration>/<target framework>/<runtime identifier>/publish`, for instance `bin/debug/netcoreapp2.0/ubuntu.16.04-x64/publish`. You should copy the whole content of the publish folder in order to run the application and you should invoke it by running <app_name>.

The runtimeconfig.dev.json file is a development file used by dotnet run, it is not present (or needed) for a published application.

Can you give us more details on what exactly you copied to the other machine and how you are running it?

**Comment by Leoat12** [comment]
I copied the entire ubuntu.16.04-x64 folder content as showed in the print below. 
![capture](https://user-images.githubusercontent.com/5158198/31318126-6094cc9e-ac23-11e7-8f69-162d53434a52.PNG)
And then I run it on the Ubuntu machine as normal and the error comes.
![capture2](https://user-images.githubusercontent.com/5158198/31318132-8338a6a8-ac23-11e7-94f6-4235d7462db7.PNG)
Here is the publish folder, all dependencies are there, including Autofac.dll.
![capture3](https://user-images.githubusercontent.com/5158198/31318142-bc3a4e98-ac23-11e7-8afb-a8a47ff28e0a.PNG)

**Thanks for the reply!**

**Comment by livarcocc** [comment]
You need to run it from the publish folder. Also, you just need to copy the publish folder.

For instance, cd into `~/Downloads/ubuntu.16..04-x64/publish`and then run ./Twitter.

**Comment by Leoat12** [comment]
It worked, sorry for the huge mistake, I looked the documentation and other source and didn't find what was going on. Thanks for the help and patience!
