### ISSUE TITLE
[build] Passing a property (/property) with multiple values to msbuild isn't working

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#7791]
I need to pass values for [`NoWarn` option](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nowarn-compiler-option) to C# compiler. Previously with msbuild it was being passed as property:
```
msbuild /p:NoWarn:"1591;1573;3001;3002"
```

But with dotnet cli it doesn't work anymore.
I tried both `build` and `msbuild` commands. 

## Steps to reproduce
```
dotnet.exe msbuild /property:NoWarn=1591;1573;3001;3002 mysolution.sln
```
or
```
dotnet.exe msbuild /property:NoWarn="1591;1573;3001;3002" mysolution.sln
```
or
```
dotnet.exe msbuild "/property:NoWarn=1591;1573;3001;3002" mysolution.sln
```

all result in
```
MSBUILD : error MSB1006: Property is not valid.
Switch: 1573
```
With `dotnet.exe `build` there's the same error.

While if I set these values in csproj:
```
<NoWarn>1591;1573;3001;3002</NoWarn>
```
it works as expected (warning are being ignored)

## Expected  behavior
Pass all warning code to the compiler.

## Actual behavior
Faulting with an error

## Environment data
`dotnet --info` output:
```
D:\>dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by dasMulli** [comment]
As a workaround, you should be able to escape the `;` character:

```
/property:NoWarn=1591%3B1573%3B3001%3B3002
```

**Comment by peterhuene** [comment]
@evil-shrike Thanks for reporting this issue!  I have reproduced this and I have a fix that should both work for your example as well as the workaround @dasMulli provided.  I'll put a PR up for it soon.

**Comment by peterhuene** [comment]
The fix is now in the `release/2.1.4xx` branch, which is slated to ship sometime after 2.1 is released (sorry, we're too close to shipping 2.1 to take a fix in that release).

Thanks again for reporting this issue to us!

**Comment by peterhuene** [comment]
@evil-shrike unfortunately the fix I made regressed the ability to define multiple properties with a single property option, e.g. `/property:First=foo;Second=bar`.  See https://github.com/dotnet/cli/issues/9369.

After discussion with the MSBuild team, we've decided to revert the fix and request that users pass literal quotes on the command line around the property's value to get the desired behavior.  See [this comment here](https://github.com/Microsoft/msbuild/issues/471#issuecomment-183053180) for the decision that was previously made for MSBuild on .NET Core.

So to do what you want, you'll need to pass literal double quotes through to MSBuild.  On most macOS/Linux shells, this can be accomplished by using single quotes surrounding the double quoted value:

```
dotnet msbuild /p:NoWarn='"1591;1573;3001;3002"'
```

The single quotes will treat both the double quotes and semicolons as literal values, so no need to escape either.

On Windows, you'll need to use escaped double quotes:

```
dotnet msbuild /p:NoWarn=\"1591;1573;3001;3002\"
```

Thanks!

**Comment by iskiselev** [comment]
Escaping with %3B at least on cmd will be treated differently and be passed inside msbuild as %3B, which may not work correct after it (see example in #10282).
I still do not fully understand, why msbuild do not require additional escaping, but same from dotnet CLI require it?

**Comment by peterhuene** [comment]
@iskiselev that's indeed the case, which is why the quotes don't transfer through to MSBuild via `dotnet`.

It's an unfortunate side effect of the difference in how each parses command line options.  An attempt for `dotnet` to do the "right thing" automatically is to force a heuristic on what they meant in the option (i.e. multiple properties being set vs. literal semicolons in a single property value).  Not difficult to do, obviously, but it would force semantics on the option with no good way of "opting out".  Thus, we decided on explicitness as the reasonable option.
