### ISSUE TITLE
CLI and the Transport Feed

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/cli#7793]
Four steps to complete moving the CLI to the Transport Feed:
- [x] 1. Use the Transport Feed as the default feed
- [x] 2. Publish the CLI NuGet packages to the Transport Feed
- [ ] 3. use the transport feed exclusively - requirement: all dependencies are publishing to the new feed
- [x] 4. Stop publishing the CLI NuGet packages to MyGet

**Comment by livarcocc** [comment]
Done for 3.0.
