### ISSUE TITLE
Failed to create prime the NuGet cache. new failed with: 5

### ISSUE THREAD

**Issue by rohit21agrawal** [dotnet/cli#7812]
_From @Petermarcu on October 11, 2017 22:49_

@dinjonya opened this here: https://github.com/dotnet/core/issues/1022

on macOs version is 10.13

dotnet core install 1.04 & 2.0 
my prj use .net core 1.04
when restore or build or run    console print

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft andshared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 4866 ms
Expanding 100% 6208 ms
Failed to create prime the NuGet cache. new failed with: 5   

_Copied from original issue: NuGet/Home#6017_

**Comment by livarcocc** [comment]
This is likely a dup of https://github.com/dotnet/cli/issues/6550. Does the first run succeed if you uninstall the 2.0 CLI?

**Comment by dinjonya** [comment]
i tried delete global.json file.
it's ok

**Comment by dinjonya** [comment]
i uesd vscode by yo aspnet build project. the project auto create  global.json file. but  when i used vs for mac create project. the project not create global.json file.

**Comment by livarcocc** [comment]
Yeah, each of these tool has its own templating mechanism. I take it this is working for you now, so I am closing the issue. If that's not the case, just comment and I can re-activate it.
