### ISSUE TITLE
x86 version of dotnet.exe

### ISSUE THREAD

**Issue by weshaggard** [dotnet/cli#783]
Our build environments require that all tools be x86 so we need an x86 version of the dotnet cli. Perhaps there is one already but I didn't see one on the main page. 

As for the reason this is a requirement we do file tracking as part of our official builds and for that to work there is an x86 file driver that gets injected into the process which of course causes that process to crash if it isn't an x86 process.

**Comment by Sridhar-MS** [comment]
x86 version of dotnet CLI is available - https://github.com/dotnet/cli#sdk-installers.
