### ISSUE TITLE
Consolidate file copying between compile and publish

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#784]
Compile and publish use similar copy code but not identical. Consider consolidating some parts of it.

Related https://github.com/dotnet/cli/pull/767#discussion_r49257712

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
