### ISSUE TITLE
dotnet new for --frameworks targeting the .NET Framework

### ISSUE THREAD

**Issue by rendmath** [dotnet/cli#7840]
## Steps to reproduce
dotnet new console --framework net461

## Expected  behavior
dotnet creates a console (or other type of) application targeting the specified version of the .NET Framework.

## Actual behavior
Error message:
Error: Invalid parameter(s):
--framework net461
    'net461' is not a valid value for --framework (Framework).
Run dotnet new console --help for usage information.
See https://aka.ms/dotnet-install-templates to learn how to install additional template packs.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.0-preview1-007363)

Product Information:
 Version:            2.1.0-preview1-007363
 Commit SHA-1 hash:  ee6707ced0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-007363\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943

**Comment by rendmath** [comment]
Current workaround: a PowerShell function to change the <TargetFramework>

```
function ChangeTargetFramework($project, $targetFramework)
{
    [xml]$projectXml = Get-Content $project;
    $projectXml.Project.PropertyGroup.TargetFramework = $targetFramework;
    $projectXml.Save((Join-Path (Get-Location) $project))
}
```

**Comment by wli3** [comment]
This issue was moved to dotnet/templating#1290
