### ISSUE TITLE
Referencing local version of .NET Core CLI tool

### ISSUE THREAD

**Issue by Daniel15** [dotnet/cli#7851]
I have a solution containing two projects: An ASP.NET Core website, and a .NET Core CLI utility that's designed to be ran via the `dotnet` command. The CLI utility uses `DotnetCliTool` as its package type, as per the docs at https://docs.microsoft.com/en-au/dotnet/core/tools/extensibility#per-project-based-extensibility and https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package

Is there a way to reference the .NET Core tool project from the ASP.NET Core website project? These tools normally use `DotNetCliToolReference`, but I can't work out how to make that a local reference. Normally a local reference can be added using `ProjectReference`, but that doesn't seem to allow it to be ran using "dotnet foo".

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16193
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```

**Comment by livarcocc** [comment]
Unfortunately, that's not possible today.

Neither NuGet knows to restore the ProjectReference as a tool nor does the CLI knowns to look for the project reference as a possible tool.

**Comment by livarcocc** [comment]
Closing this issue as this is not really possible and this is not on the roadmap for us at the moment.
