### ISSUE TITLE
Documentation for .deps.json and friends is (wildly) out of date

### ISSUE THREAD

**Issue by bradwilson** [dotnet/cli#7861]
https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md

Despite us being post 2.0, this documentation file is (a) incorrect (see, for example, how `runtimeTarget` shows as a string instead of an object), and (b) talks about `project.json`.

Please update it so those of us who are looking at these configuration files have up to date documentation to consult.

Thanks! 😁

**Comment by tebeco** [comment]
I see the md file has changed since the creation of this issue
anyone got a status of it ?
still obsolete ? mostly ? partially ? up to date ?

**Comment by bradwilson** [comment]
I'm not sure what you're talking about. All my complaints are still present: `runtimeTarget` in the sample `.deps.json` file is wrong, and there are still references to `project.json`.

**Comment by tebeco** [comment]
i was looking for docs on does.json and found a match pointing to this issue

just by reading the issue you created and the fact that i had no idea of the content of that md file (but it seems to speak about .deps.json)
i wanted to be sure of what’s i should or not read

the given context is :

> this documentation file is (a) incorrect (see, for example, how runtimeTarget shows as a string instead of an object), and (b) talks about project.json.

> Please update it so those of us who are looking at these configuration files have up to date documentation to consult

i just wanted to know if anybody else adressed the point and if it’s ok to read it as a reference or not

**Comment by tebeco** [comment]
(and i secretly hopped that some contributor / author / anybody that knows about this file would notice this ticket)

as multiple user actually looks for i fo on t

**Comment by livarcocc** [comment]
@steveharter can you help update this documentation?

**Comment by per-samuelsson** [comment]
Any news here? Some of us are struggling with this as it's kind of essential for anyone that has to go through dynamic assembly loading and resolving references.

**Comment by bradwilson** [comment]
If you're looking for code, xUnit.net has some you can look at/lift: https://github.com/xunit/xunit/tree/master/src/common/AssemblyResolution

Note that we took copies of `Microsoft.DotNet.PlatformAbstractions` and `Microsoft.Extensions.DependencyModel`, as well as a [JSON parser](https://github.com/xunit/xunit/blob/master/src/common/Json.cs), because taking _**any**_ dependencies that don't ship in the framework itself is going to make you (and your users) sad. See [this issue](https://github.com/xunit/xunit/issues/1060) for the many problems we encountered along the way...

We spent a ton of time tracking down issues, and it wasn't until 2.4 beta 1 that I felt confident that we'd nailed them all...not because I could thoroughly reason about the problems, but because people stopped reporting them. /shrug

**Comment by steveharter** [comment]
I'll temporary assign it to myself to clean up the areas I'm familiar with including recent additions for 2.1.
