### ISSUE TITLE
nuget.exe list functionality

### ISSUE THREAD

**Issue by Kemyke** [dotnet/cli#7869]
## Steps to reproduce
There is no substituting functionality for 'nuget.exe list' feature. That would be great if it would be possible to use the dotnet CLI for automation on every platform. Currently the mono should be installed on Ubutnu to run nuget.exe. Is there a plan to add all the missing functionality to the dotnet CLI?

## Expected  behavior
dotnet nuget list <Filter expression>

## Actual behavior
There is no funcionality in the dotnet CLI to list the available packages.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6060
