### ISSUE TITLE
dotnet build continues when restore fails

### ISSUE THREAD

**Issue by forki** [dotnet/cli#7870]
## Steps to reproduce

1) git clone https://github.com/forki/restorebug.git
1) cd restorebug/console
1) dotnet build

## Expected  behavior

process stops after restore error (which we set from MyTargets,targets)

## Actual behavior

![image](https://user-images.githubusercontent.com/57396/31780129-1bf6d822-b4f5-11e7-8250-7706f9c1e602.png)

the build continues after restore. And if you still have the assets file for weird reasons then build even succeeds.

## Environment data
`dotnet --info` output: 2.0.2

**Comment by forki** [comment]
This is really important for Paket since we try to let the build fail from targets file when certain conditions are not met. But instead it just continues. ¯\_(ツ)_/¯

**Comment by livarcocc** [comment]
@forki Is this just a regular restore or are you doing some form of customization? I just tried it out on a project by updating a package reference to a non-existing version and I see that the restore failure is actually stopping the build.

Also, we have this piece of code in place: https://github.com/dotnet/cli/blob/master/src/dotnet/commands/RestoringCommand.cs#L52

So, if restore fails, it should stop the next command from running.

**Comment by forki** [comment]
@livarcocc did you follow the repro steps? This is calling dotnet build on a project that has targets. And the targets have an error task to explicitly stop the build

**Comment by forki** [comment]
But it does not. The error is only shown on command line and then build continuous

**Comment by forki** [comment]
So in other words: it's not the nuget task that fails, but targets along the way in "dotnet restore".

**Comment by livarcocc** [comment]
This may be a regression in 2.0.2:

```
git/restorebug/console
$ dotnet build
git/restorebug/MyTargets.targets(4,5): error : Explcit restore error. [git/restorebug/lib/lib.csproj]
git/restorebug/MyTargets.targets(4,5): error : Explcit restore error. [git/restorebug/console/console.csproj]

/git/restorebug/console
$ dotnet --version
2.0.0
```

Trying that locally with 2.0.2 now.

**Comment by livarcocc** [comment]
Yes, this is a regression in NuGet. So, in 2.0.2 we took in a new version of NuGet. It seems like their targets have changed and now your targets are not causing the restore operation to fail anymore.

I am going to move this issue over to NuGet/Home to have the NuGet team take a look at it.

cc @emgarten @rrelyea

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6061
