### ISSUE TITLE
Simplify consumption of aspnetcore in 2.0.x

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#7871]
Backport the improvements https://github.com/dotnet/cli/pull/7424 (master branch) to the release/2.0.0 branch. This simplifies how the CLI consumes new builds of aspnetcore.

Requires coordination with aspnetcore's build output. cc @joeloff

**Comment by livarcocc** [comment]
cc @johnbeisner and @wli3 since we will have to port some changes from master to release/2.0.0 as well to match the asp.net changes.

**Comment by wli3** [comment]
We should follow master's transition. @JunTaoLuo @joeloff could you port the change on your side first, so there will be package with new convention available. And then, we can consume the package by porting the #7424 change. Following so, there should not be any "down time".

**Comment by JunTaoLuo** [comment]
In fact, the changes have already been made on the asp side. The difficulty for the 2.0.3 patch was actually to manually revert the renames.

**Comment by wli3** [comment]
@JunTaoLuo awesome, so I can start to port then

**Comment by wli3** [comment]
@JunTaoLuo  @joeloff sorry for the delay, what is the version we should use in release/2.0.0 ?

**Comment by JunTaoLuo** [comment]
Towards the end of the 2.0.3 patch, I reverted some of the updated naming to simplify the consumption process and reduce manual renames. I'll let you know when I revert those after I get some clarifications on what's expected for runtime store in the 2.0.x patch releases.

**Comment by natemcmaster** [comment]
Yeah, for now there isn't any action for you @wli3. We likely won't get to this until the next 2.0.x patch

**Comment by livarcocc** [comment]
We are about to do another MSRC. Is this done on your side so that we can integrate the changes on our side?

**Comment by joeloff** [comment]
Should we be doing this for 2.0.x? I thought we'd be doing this for 2.1 (dev) only. Given our history with releases, is it worth risking it by making engineering changes on top of the actual MSRC work?

**Comment by livarcocc** [comment]
My understanding was that ASP.NET had already done that for 2.0.x and they had to manually "undo" it for the last MSRC.

If that's not the case, then you are right, we shouldn't change it.

**Comment by joeloff** [comment]
Agree. I never made any changes to the crossgen build for 2.0.x. I only made changes in the dev branch for 2.1, but I do recall the "undo" that happened for the last 2.0.x release

**Comment by JunTaoLuo** [comment]
Right we had to undo updating the naming in the 2.0.x branch. The current naming scheme in 2.0 will continue to work so if we don't want to make any changes.

**Comment by livarcocc** [comment]
Ok. I would say let's not change it then. If everyone agrees, I will close this issue.

**Comment by natemcmaster** [comment]
Fine w/ me.
