### ISSUE TITLE
MStest.exe via CLI does no work

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [dotnet/cli#7873]
## Steps to reproduce

- create a unit test project named UnitTestProject1;
- build the project will generate file UnitTestProject1.dll;
- Open developer command prompt, run "mstest.exe /testcontainer:UnitTestProject1.dll path",
   Ex: mstest.exe /testcontainer:"C:\Users\ddltd1\source\repos\UnitTestProject1\UnitTestProject1\bin\Debug\UnitTestProject1.dll"

## Expected  behavior
mstest.exe /testcontainer:UnitTestProject1.dll run pass;

## Actual behavior
No tests to execute.

Test on build 27019.00
## Environment data
```
`dotnet --info` output:
.NET Command Line Tools (2.1.1-preview-007094)

Product Information:
 Version:            2.1.1-preview-007094
 Commit SHA-1 hash:  f657648f07

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.1-preview-007094\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1213
