### ISSUE TITLE
cli-tool: adding dynamic dependency

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#7874]
Given a cli-tool installed into a project (via DotNetCliToolReference). The tool has its own dependencies which set up in generated `project.assets.json` in `.tools` folder so that the tool run can and discover needed assemblies. That's fine. But what if we want to add some dynamic dependency for the tool, like a "provider" or "plugin".
That is I want to add an assembly so that the tool can load it.
Just an abstract example:
```
dotnet mygenerator sql -provider:MyProduct.Storage.MsSqlProvider,MyProduct.Storage.MsSql
```
here `MyProduct.Storage.MsSqlProvider,MyProduct.Storage.MsSql` is a fully-quallified class name which I want the cli-tool to load. But it can't because it can't see that assembly even if it's installed besides in `packages` folder.

Does I understand correctly that currently it's not possible to use the mentioned scenario (load a type in cli-tool which wasn't known at compile-time)?

In case I'm correct I'd suggest support something like this:
```
  </ItemGroup>
    <DotNetCliToolReference Include="MyDotnetCliTool" Version="*">
      <PackageReference Include="MyProduct.Storage.MsSql" Version="*" />
    </DotNetCliToolReference>
  </ItemGroup>
```

Then of cause adding references for tools should be supported by `dotnet cli` (but after implemented long awaited https://github.com/NuGet/Home/issues/4901)

**Comment by livarcocc** [comment]
You can use AssemblyLoadContext in your own tool to load random assemblies yourself. For examples of that, see here https://github.com/dotnet/corefx/tree/master/src/System.Runtime.Loader/tests.

We don't really intend to support this sort of feature in CLI tools and this is very specific to one particular type of tool and like I said above, you can write your own code for it.
