### ISSUE TITLE
global.json not enforced on Windows

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#7875]
Recently updated the version of CLI we were using and everything worked fine on Windows but failed when we switched to Linux / Mac. The failure was the new version no longer matched global.json and hence every command we executed failed with the error:

``` txt
The specified SDK version [2.0.0] from global.json [/Users/jaredpar/code/roslyn/global.json] not found; install specified SDK version
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

It appears that global.json is simply not being enforced on Windows. I took care to ensure that I was using the same version of CLI in both cases, that I wasn't accidentally using a different one due to `%PATH%` tricks. 

Repro:

- Clone https://github.com/jaredpar/roslyn on Windows
- Checkout branch rerpo/global-json 
- Run Restore.cmd

Everything will succeed here. 

- Clone https://github.com/jaredpar/roslyn on Linux / Mac
- Checkout branch rerpo/global-json 
- Run cibuild.sh

Everything will fail with errors about global.json being incorrect

**Comment by livarcocc** [comment]
You are likely seeing Multi-level lookup in action on Windows (the only OS where we do this). Multi-level lookup will basically look where you are running dotnet from but will also look at the ProgramFiles folder for a suitable SDK to use. You must have a 2.0.0 SDK installed in ProgramFiles that we are finding and using.

**Comment by jaredpar** [comment]
That could be happening. So essentially even if i'm explicitly running dotnet from say 2.1, if global.json says 2.0 then it will silently divert to the 2.0 version?

**Comment by livarcocc** [comment]
Correct. That's what global.json is for. It pins your version of the SDK. We will rollforward on patch versions though. So, if you say 2.0.0 and we find 2.0.2, we will use that. But we will not rollforward on minor versions.

If you just want to use whatever latest is on the box, then leave global.json out.

**Comment by jaredpar** [comment]
> If you just want to use whatever latest is on the box, then leave global.json out.

Its not so mcuh that i wanted latest, i was just surprised it wasn't using the exact dontet exe that i specified. 

Sounds like it's by design though. I have a 2.0.0 version on my box so it was just downgrading to that.
