### ISSUE TITLE
dotnet pack with `/p` parameters does not work on windows

### ISSUE THREAD

**Issue by arishlabroo** [dotnet/cli#7878]
## Steps to reproduce
From any project directory run
`dotnet pack /p:VersionPrefix=9.1.2
`
## Expected  behavior
_Successfully created package '/Charlie/bin/Debug/Charlie.9.1.2.nupkg'_

### On Mac
_Successfully created package '/Charlie/bin/Debug/Charlie.9.1.2.nupkg'_

### On Windows

_MSBUILD : **error MSB1009**: Project file does not exist.
Switch: p:VersionPrefix=9.1.2_

## Environment data
**Mac** `dotnet --info` output:

> .NET Command Line Tools (2.0.2)
> 
> Product Information:
>  Version:            2.0.2
>  Commit SHA-1 hash:  a04b4bf512
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.13
>  OS Platform: Darwin
>  RID:         osx.10.12-x64
>  Base Path:   /usr/local/share/dotnet/sdk/2.0.2/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0
>   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Windows** `dotnet --info` output:

> .NET Command Line Tools (2.0.2)
> 
> Product Information:
>  Version:            2.0.2
>  Commit SHA-1 hash:  a04b4bf512
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.15063
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.0.2\
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.0
>   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by gulbanana** [comment]
are you using cygwin/mingw? escape the / with another /, or run in powershell or cmd

**Comment by arishlabroo** [comment]
@gulbanana thanks. I am using git bash on windows (mingw).

It does work fine in powershell/cmd.

Also escaping `/` also did the trick in git bash.

Thanks, closing issue.
