### ISSUE TITLE
Bad help "--version"

### ISSUE THREAD

**Issue by HarelM** [dotnet/cli#7881]
## Steps to reproduce
run `dotnet` from command line.
this outputs:
Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help            Display help.
  --version         Display version.

path-to-application:
  The path to an application .dll file to execute.

Then run `dotnet --version`
To receive:
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

## Expected  behavior
Either --version will work or -- version will not appear in the help.

## Actual behavior
Irrelevant error message - turn out I needed to use --info instead of --version

## Environment data
`dotnet --info` output:
Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
@steveharter This help is displayed by the host. I am moving this issue to core-setup.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3332
