### ISSUE TITLE
Cannot get required symbol TLSv1_1_method from libssl

### ISSUE THREAD

**Issue by jafg1222** [dotnet/cli#7882]
## Steps to reproduce
`dotnet new console -o hwapp`  
## Expected  behavior
Create a new application with dotnet cli
## Actual behavior
`Cannot get required symbol TLSv1_1_method from libssl
Aborted (`core' generado)`

## Environment data
`dotnet --info` output:
Herramientas de la línea de comandos .NET (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     fedora
 OS Version:  26
 OS Platform: Linux
 RID:         fedora.26-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
Seems like a native requirement issue. Moving to core-setup.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3333
