### ISSUE TITLE
[Question] 2.1 preview SDK on Ubuntu 16.04?

### ISSUE THREAD

**Issue by chuckries** [dotnet/cli#7885]
Is it possible to put together a full 2.1.0-preview on linux-x64? I am trying to install daily builds from https://github.com/dotnet/core/blob/master/daily-builds.md. I have successfully installed the .deb packages for the daily build of the Core Runtime, but the daily build of the SDK has unmet dependencies. Is there a way I can resolve this?

**Comment by livarcocc** [comment]
I am not sure I follow what is the ask here. The CLI generates builds for all PRs merged, though we are behind builds due to infra-structure problems, there are builds available of the SDK for 2.1.0-preview1, not 2.2.0.

What unresolved dependencies are you hitting?

cc @wli3

**Comment by wli3** [comment]
Hi @chuckries I think the dependency you are talking about are: 
```
dotnet-host
dotnet-hostfxr
dotnet-runtime
aspnetcore-store
```
however, to install it via deb you need to download all of them and install. Maybe install script is a better solution today https://github.com/dotnet/cli/blob/master/Documentation/specs/cli-installation-scenarios.md#installation-script

relate: https://github.com/dotnet/cli/issues/6907

**Comment by chuckries** [comment]
I will try to use the install script for now.

**Comment by g0t4** [comment]
@chunkries would the official docker nightly images work for your use case? 

https://hub.docker.com/r/microsoft/dotnet-nightly

**Comment by chuckries** [comment]
@g0t4 This is a very good idea, and it probably would work. For the time being, I have managed to make the dotnet-install.sh script work for me, as @wli3 suggested.

**Comment by livarcocc** [comment]
@wli3 can you close this issue as a dup of the asp.net issue for publishing the asp.net runtime store to the feed?

**Comment by livarcocc** [comment]
Closing this as a dup of https://github.com/aspnet/MetaPackages/issues/231.
