### ISSUE TITLE
Feature Request: CLI feature update NuGet packages on solution, project, and/or folder level.

### ISSUE THREAD

**Issue by Kritner** [dotnet/cli#7886]
It could potentially be beneficial to have a CLI command that would allow for the updating of NuGet packages from the solution level.

As we add more projects to our solutions, the projects created more recently often (as expected) have more up to date versions of packages.  In our case, we are creating several solutions, some of which depend on some library projects.  We could go into each solution, and update the packages, but this is extremely time consuming.

Part of the way we were getting around this, was to have an "all" solution, that contained all projects.  This would allow the use of the "Manage NuGet packages" dialogue to update all packages at once.  At this point however, VS seems to crash based on the number of projects in the "all" solution (in the neighborhood of 100).

It would be extremely useful if a `dotnet nuget update` command or similar was made available, at either the solution, project, or folder (assuming it could traverse directories) level.  I'm not sure if this is such a special potential use case or not, but thought I'd throw it out there.

I'd imagine certain options would be useful such as:

`-consolidate` (similar to the GUI, determine all packages used, and get them all updated to the same version
`-update` - updates all nuget packages to the latest version
`-update-pre` - updates all nuget packages to the latest version, can use pre-release packages rather than only stable.

* when given a solution file, determine projects in solution, then nuget packages used across projects
* when given a project file, update only packages pertaining to that project file
* when given a folder, determine projects contained within folder, and nuget packages for each project.

Thoughts?  I couldn't imagine I'm the only one where the "Solution manage nuget packages" from Visual Studio sort of bombs out.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6193
