### ISSUE TITLE
error NU1605:   Microsoft.AspNetCore.All (>= 2.0.0) -> Microsoft.EntityFrameworkCore.SqlServer (>= 2.0.0) \r

### ISSUE THREAD

**Issue by Amine-Smahi** [dotnet/cli#7892]
## Steps to reproduce
`dotnet restore`

## Actual behavior

` Restoring packages for C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj...
  Restoring packages for C:\Users\DELL\RiderProjects\LibraryCore\ClassLibrary\ClassLibrary.csproj...
  Restoring packages for C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj...
  Restore completed in 110.05 ms for C:\Users\DELL\RiderProjects\LibraryCore\ClassLibrary\ClassLibrary.csproj.
  Restore completed in 111.51 ms for C:\Users\DELL\RiderProjects\LibraryCore\ClassLibrary\ClassLibrary.csproj.
  Generating MSBuild file C:\Users\DELL\RiderProjects\LibraryCore\ClassLibrary\obj\ClassLibrary.csproj.nuget.g.props.
  Restore completed in 1.18 sec for C:\Users\DELL\RiderProjects\LibraryCore\ClassLibrary\ClassLibrary.csproj.
  Restore completed in 1.89 sec for C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj.
C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj : error NU1102: Unable to find package Microsoft.EntityFrameworkCore.SqlServer.Design with version (>= 2.0.0)\r
C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-final ]\r
C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj : error NU1102:   - Found 1 version(s) in CliFallbackFolder [ Nearest version: 2.0.0-preview1-final ]
  Generating MSBuild file C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\obj\LibraryCore.csproj.nuget.g.props.
  Restore failed in 8.64 sec for C:\Users\DELL\RiderProjects\LibraryCore\LibraryCore\LibraryCore.csproj.`

## Environment data
`dotnet --info` output:

`.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
`

**Comment by livarcocc** [comment]
It seems to me like you might have a stale package somewhere. Microsoft.AspNetCore.All does not depend on Microsoft.EntityFrameworkCore.SqlServer, when looking at its dependencies at NuGet.org.

Can you maybe delete that package from your nuget cache (or empty your NuGet cache entirely) and trying restore again?

cc @emgarten

**Comment by emgarten** [comment]
The title of the bug shows NU1605 (a warning), but it isn't listed in the output in the bug. I only see NU1102. Which is the problem here?

For NU1102:
Does the project reference `Microsoft.EntityFrameworkCore.SqlServer.Design 2.0.0` directly? Everything looks correct to me here, there is no 2.0.0 version of the package, only 2.0.0-preview1-final on nuget.org. The package or project referencing this is likely the problem.

```
error NU1102: Unable to find package Microsoft.EntityFrameworkCore.SqlServer.Design with version (>= 2.0.0)
error NU1102: - Found 14 version(s) in nuget.org [ Nearest version: 2.0.0-preview1-final ]
error NU1102: - Found 1 version(s) in CliFallbackFolder [ Nearest version: 2.0.0-preview1-final ]
```

**Comment by livarcocc** [comment]
And I checked the `Microsoft.AspNetCore.All` package in NuGet and it does not reference `Microsoft.EntityFrameworkCore.SqlServer.Design`.

**Comment by livarcocc** [comment]
We haven't had activity on this issue for  a few days now. Please, this seems like a local issue. The packages are authored correctly. Closing this issue for now.

If that's not the case and there is more information available, please re-activate.
