### ISSUE TITLE
Wrong binary name output for mac/linux binaries

### ISSUE THREAD

**Issue by Fabi** [dotnet/cli#7895]
## Steps to reproduce

1. Download the project: `git clone https://github.com/Arctium-Emulation/WoW-Core --recursive`
2. Use `dotnet restore`
3. Use `dotnet build /p:Platform=mac-x64` or `dotnet build /p:Platform=linux-x64` 
4. The output is created in the `wow-core\build\Debug\<Platform>\bin` directory

## Expected  behavior
Creating binaries for mac/linux named `arctium.aurora` for example or `arctium.api`

## Actual behavior
Actually it creates binaries for mac/linux, but the name is `arctium.aurora.aurora` or `arctium.api.api`
Using `/p:Platform=win-x64` creates the correct exe files for windows, so it seems to be a mac/linux related problem.
Also executing the binary results in:
`./arctium.manager.manager
The managed DLL bound to this executable: 'arctium.manager.dll', did not match own name 'arctium.manager.manager.dll'.
A fatal error was encountered. This executable was not bound to load a managed DLL.`

## Environment data
`dotnet --info` output:

Windows:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Mac:
.NET-Befehlszeilentools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
We have fixed this issue in 2.2.0 already, in our master branch.

**Comment by Fabi** [comment]
yep it is thanks!
