### ISSUE TITLE
[Quesiton] How to run 'dotnet test' without cli?

### ISSUE THREAD

**Issue by chuckries** [dotnet/cli#7898]
I am working on porting the debugger used by the VS Code C# Extension to linux-arm. Today we depend on the 'dotnet test' command to run our unit tests. This will not work for running our unit tests on linux-arm because there is currently no cli available. 

I thought I would be able to build the test project on windows and run it on linux-arm against a private shared framework. This works for console apps, but I can't get it to work for a test app. 

How can I get a test runner in the output of my test project build that I can run on arm against a shared framework? I thought doing a stand-alone publish would include the necessary pieces, but it doesn't have a test runner in the outputs. I took a quick look at 'dotnet-vstest' form the cli, and it looks like the runner is included in the SDK installation, which I do not have on linux-arm. Is there any way to publish 'vstest.console.dll' with the app? Is there a PackageReference I can add to include the test runner in the build/publish output?

**Comment by livarcocc** [comment]
I do not believe that's possible today. The test project is not self reliant. In the sense that it does not contain the runner that knows how to run the tests.

Still, I will move this issue to microsoft/vstest, maybe they will have some idea there.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1224
