### ISSUE TITLE
'dotnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by pankajdmishra** [dotnet/cli#7904]
## Steps to reproduce
I am trying to create a Angular 2 spa template using cmd in Visual studio 2015 update 3

I am trying to run "dotnet new --install Microsoft.AspNetCore.SpaTemplate::*"
But it gives 'dotnet' is not recognized as an internal or external command, operable program or batch file.

I also installed DotNet core (dotnet-sdk-2.0.0-win-gs-x64)

## Expected  behavior
It should run the command successfully and install SPA template

## Actual behavior
'dotnet' is not recognized as an internal or external command, operable program or batch file.

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
How did you install dotnet? To be honest, I am not familiar with a win-gs installer. Where did you obtain it?

Also note that the new csproj format will not work with VS 2015.

What is happening here is that you don't have dotnet.exe on your path.

**Comment by livarcocc** [comment]
Closing since we haven't had activity on this issue for over a week. If this is still happening and you can answer my questions above, please, re-activate.

**Comment by Deshpandenitish** [comment]
>

**Comment by Deshpandenitish** [comment]
'dotnet' is not recognized as an internal or external command,
operable program or batch file.-->am getting this error while installing dotnet on laptop..can anyone help me please?

**Comment by livarcocc** [comment]
How are you installing it? In which OS? At which point do you get the error message?
