### ISSUE TITLE
Allow for a way to map nuget packages to local projects

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/cli#7905]
When I'm working on NPM packages, it has a neat feature where I can map a package to a local directory.  That way, rather than downloading a version that has to be built, I can use a WIP version of a package before publishing it.

Would love to be able to do this with .net.

**Comment by livarcocc** [comment]
This is not possible at all today and I don't think we have plans to enable this scenario any time soon.

You could do this though by publishing your WIP package and putting it into a local folder that you could then add as a feed to your NuGet.Config, then, when running restore, the new package should be picked up.

**Comment by atrauzzi** [comment]
That's a huge hassle and nowhere near as convenient. I think you need to reconsider the priority of something like this.  Working on multi repository applications is such a difficult story in .net. There has to be something to ease the pain without having to deploy every time.

**Comment by livarcocc** [comment]
@atrauzzi can you help me understand this better? So, you are saying that you are fine if these different repositories produce packages to a local folder in your box? If that's the case, you can do so and simply point NuGet to this local folder containing the product of these different repos for consumption. Sounds like that would achieve exactly what you want.

You can set this feed in many different ways:
* You can add this folder to the different NuGet.Config files in your different repos.
* You can add this folder to a user wide NuGet.Config.
* You can add this folder as a parameter to your dotnet restore command.

Wouldn't this achieve your stated goals above?

**Comment by atrauzzi** [comment]
The idea of having to take special steps makes that approach brittle, especially because what you're suggesting changes what version my project references versus simply offering a temporary override by convention.

**Comment by livarcocc** [comment]
This is not something that we have in our plans to change at the moment.

Closing for now.

**Comment by atrauzzi** [comment]
That's not great at all. I really suggest you reconsider.
