### ISSUE TITLE
Debugging very slow build times

### ISSUE THREAD

**Issue by dcarl1** [dotnet/cli#7908]
I apologize that this isn't really a bug report I just didn't know where else to go...

We have a solution of about ~35 projects that is seeing build times in the 3-5 minute range. This is using ASP.Net Core 2.0 targeting net46. Incremental builds seem to be non existent.

I've been following the few performance related issued on here, however now I think it may be something inside our solution.

Does anyone have a general starting point or any advice on how to dig into this? Or maybe this is normal? I've tried a verbose build however the log file is hundreds of megabytes which is not really human parse-able. 

Thanks.

**Comment by livarcocc** [comment]
On the CLI side, we are tracking the brunt of this performance conversation here: https://github.com/dotnet/cli/issues/7610.

However, you did not mention if you are seeing these perf numbers through the command line (CLI) or through VS. That would be a helpful differentiation for us.

Also, what version of the SDK you are using?

**Comment by danmosemsft** [comment]
I don't know how to pass MSBuild parameters through `dotnet build` but if you build with the MSBuild parameter `/clp:performancesummary` it will indicate where the time was spent.

**Comment by dcarl1** [comment]
@livarcocc @danmosemsft Seems to be the resolving references thing that is being tracked already. I thought our build times were insane and it was something with our project, however doesn't look that way.

I restructured things and go us down to about ~15 projects which has sped things up _considerably_ so I'm going to close this for now and just track #7610. 

Thanks.
