### ISSUE TITLE
cli-tool: running a cil-tool via dotnet produces unmanaged unhandler exception

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#7909]
I have a netcoreapp2.0 console project with output "dotnet-xxx" assembly (Exe) for a tool. The tool can run fine (`dotnet dotnet-xxx.dll`). Now I want to use it as CliTool in other projects.

I packed the tool as a nuget package with `<packageType name="DotnetCliTool" />` then installed it in a project via DotNetCliToolReference  reference:

    <DotNetCliToolReference Include="Croc.XFW3.DotnetCliTool" Version="3.0.0" />

But when I try to run it via dotnet I'm getting an unmanaged unhandled exception:

Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.

Windows debug dialog pops up, inside debugger (VS) I only can see this:

Unhandled exception at 0x00007FFB9AE13FB8 (KernelBase.dll) in dotnet.exe: 0xE0434352 (parameters: 0xFFFFFFFF80131534, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x00007FFB3E430000).

Not much.

The tool package installed to a folder specified in `globalPackagesFolder` option in local nuget.config.
There're pdb and all json from build output in that folder.
dotnet-xxx.dll
dotnet-xxx.pdb
dotnet-xxx.deps.json
dotnet-xxx.runtimeconfig.json
dotnet-xxx.runtimeconfig.dev.json

How can I diagnose what's wrong?

p.s. the tool isn't public so I can't share reproducible code unfortunately
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by evil-shrike** [comment]
No ideas?

**Comment by livarcocc** [comment]
Is there anything special in that tool? How are you packaging it up? Could you share the package, or a trimmed down version of that package for us to try to repro the issue here?

Meanwhile, @steveharter can you help us look into the native crash?

**Comment by evil-shrike** [comment]
Nothing fancy. But it depends on other our packages. I packed it via `nuget pack` with my nuspec's.
I can share privately this bunch of packages with you and it will be installable from a folder.
it's about 16Mb.

**Comment by evil-shrike** [comment]
@livarcocc I sent you an email with dropbox link and instructions.

**Comment by evil-shrike** [comment]
I've created a minidump (via WER registry settings), then opened it in VS2017 and now I can see that's happenings:
In my cli-tool (called DotnetCliTool) I'm getting System.TypeInitializationException: 'The type initializer for 'DotnetCliTool.Program' threw an exception.'

FileLoadException: Could not load file or assembly 'System.Text.RegularExpressions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by evil-shrike** [comment]
Finally I found what causes the exception - my cli-tool package had no dependency on `Microsoft.NETCore.App` in its nuspec.

**Comment by livarcocc** [comment]
Ah, that makes sense. And that's why it was running when you ran the app but failing only in the tool.

Any particular reason why you can't use dotnet pack?

Anyways, it seems like this issue can be closed then? I will close it, but if there is anything else, just comment here and I can re-activate it.

Thanks for looking and filling the issue.
