### ISSUE TITLE
cli-tool: dotnet run executes program very slow.

### ISSUE THREAD

**Issue by MFathirIrhas** [dotnet/cli#7912]
## Steps to reproduce
- Create new console app, e.g HelloWorld sample
- Execute `dotnet run`

## Expected  behavior
It should be executed and run within 1 second at most(proportional to the program source size) using `dotnet run` .

## Actual behavior
The command `dotnet run` took around 4 seconds for just simple HelloWorld program. The option using `--no-build` work faster, BUT as its name suggest, no rebuilding process hence your program will be executed its previous state before changes made. 
Using `--no-build` option won't get your changes executed.  
Using execution directly to the `.dll` program binary file in `bin/debug` directory works faster than using `--no-build`, BUT with the same result it won't execute your new changes in source code without doing build/run.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

*note: I'm considering using.net core for developing some project APIs. After experiencing this slowness for simple HelloWorld program, I have my doubts. I've searched through the list of issues regarding to this issue, but with the same suggestions to use `--no-build` option or execute directly to the binary file in `bin/debug` directory. There are no other solutions I found yet. If any other successful workarounds or solutions I might miss regarding to this issue, please redirect me(link) to that. If not, this should be at high priority for performance enhancement. Thanks in advance.*

**Comment by WernerMairl** [comment]
reading this and some linked issue/discussion can be helpful to see the big picture...

https://github.com/dotnet/project-system/issues/2789

**Comment by livarcocc** [comment]
We already have an issue tracking this here: https://github.com/dotnet/cli/issues/7610. There is a long discussion happening there and performance is one of our top priorities right now.

Also, note that dotnet run is not meant as a production command. It is the equivalent of F5 on VS or other IDEs and not the way you should run your application in production.

**Comment by MFathirIrhas** [comment]
@livarcocc I used to debug and run with the apps using that commands before(using json which is faster). But now it's just feel weird to take this long. Thank you btw.

**Comment by livarcocc** [comment]
We are working on making it better/faster. We know it is not ideal right now.

**Comment by MFathirIrhas** [comment]
@livarcocc  again, thank you very much :D
