### ISSUE TITLE
How to pass credentials/password to dotnet publish?

### ISSUE THREAD

**Issue by mariotacke** [dotnet/cli#7916]
We're using `.pubxml` files for deployments to our various environments (Azure). Instead of deploying through Visual Studio, I'm trying to use the `dotnet publish` cli to do the same on our build server. We are using basic auth (username/password).

I can not find any information on credential passing in the docs. I do not want to save the password in our `.pubxml` files, but instead pass it as environment variable or cli option. **Is this possible?**

What I am trying to do:
```
dotnet publish -c Release /p:PublishProfile="Properties\PublishProfiles\<profile name>.pubxml" /p:Password="<password>"
```

If I do that I receive this: 
```
MSDEPLOY : error Code: ERROR_CONNECTION_TERMINATED [<path to project>.csproj]
MSDEPLOY : error : Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 550. [<path to project>.csproj]
MSDEPLOY : error count: 1. [<path to project>.csproj]
```

Not passing a `/p:Password` obviously results in:
```
MSDEPLOY : error Code: ERROR_USER_UNAUTHORIZED [<path to project>.csproj]
Error : The remote server returned an error : (401) Unauthorized. [<path to project>.csproj]
MSDEPLOY : error count: 1. [<path to project>.csproj]
```

## Environment data
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by livarcocc** [comment]
@vijayrkn @mlorbetske is this supported by the Publish SDK?

**Comment by mariotacke** [comment]
Just looked at the docs at https://docs.microsoft.com/en-us/aspnet/core/publishing/web-publishing-vs?tabs=aspnetcore2x, looks like it should be:

> Msdeploy (currently this only works in windows since msdeploy is not cross-platform):
> `dotnet publish WebApplication.csproj /p:PublishProfile=<MsDeployProfileName> /p:Password=<DeploymentPassword>`

**Comment by mariotacke** [comment]
Looks like this is company/firewall related. It works now without changing a thing... This can be closed.

**Comment by livarcocc** [comment]
Thanks for letting us know.

**Comment by vijayrkn** [comment]
@mariotacke - Thanks for confirming. 
The below commandline should also work on xplat systems if mono is installed. Will update the docs. 

>Msdeploy (currently this only works in windows since msdeploy is not cross-platform):
dotnet publish WebApplication.csproj /p:PublishProfile=<MsDeployProfileName> /p:Password=<DeploymentPassword>

**Comment by mariotacke** [comment]
Awesome, thanks for following up!
