### ISSUE TITLE
dotnet build is failing

### ISSUE THREAD

**Issue by harshjain2** [dotnet/cli#7921]
## Steps to reproduce
dotnet build is failing if Product Code targets netstandard1.4 and test project targets netcoreapp1.0/netcoreapp2.0.

1. git clone https://github.com/microsoft/vstest
2. git checkout 347c59f73943921786bf9d5a7e42d2cf011ddd15
3. build.cmd -noloc

## Expected  behavior
1. Build should complete successfully.

## Actual behavior
1. Getting errors like 
```
C:\code\github\vstest\tools\dotnet\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\code\github\vstes
t\src\Microsoft.TestPlatform.Common\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v1.0'. Ensure that restore has run and that you have included 'netcoreapp1.0'
 in the TargetFrameworks for your project. [C:\code\github\vstest\src\Microsoft.TestPlatform.Common\Microsoft.TestPlatform.Common.csproj]
C:\code\github\vstest\tools\dotnet\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\code\github\vstes
t\src\Microsoft.TestPlatform.CommunicationUtilities\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v1.0'. Ensure that restore has run and that you have included
 'netcoreapp1.0' in the TargetFrameworks for your project. [C:\code\github\vstest\src\Microsoft.TestPlatform.CommunicationUtilities\Microsoft.TestPlatform.CommunicationUtilities.csproj]
C:\code\github\vstest\tools\dotnet\sdk\2.2.0-preview1-007460\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'C:\code\github\vstes
t\src\Microsoft.TestPlatform.ObjectModel\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v1.0'. Ensure that restore has run and that you have included 'netcoreap
p1.0' in the TargetFrameworks for your project. [C:\code\github\vstest\src\Microsoft.TestPlatform.ObjectModel\Microsoft.TestPlatform.ObjectModel.csproj]
```
## Environment data
**Not working on this build**
.NET Command Line Tools (2.2.0-preview1-007460)

Product Information:
 Version:            2.2.0-preview1-007460
 Commit SHA-1 hash:  173cc035e4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\code\github\vstest\tools\dotnet\sdk\2.2.0-preview1-007460\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25825-07
  Build    : 4c165c13bd390adf66f9af30a088d634d3f37a9d

**Working on this build:**
.NET Command Line Tools (2.1.0-preview1-007372)

Product Information:
 Version:            2.1.0-preview1-007372
 Commit SHA-1 hash:  a1ecb3bb3f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\code\github\harshjain2\vstest\tools\dotnet\sdk\2.1.0-preview1-007372\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25816-02
  Build    : c5006ff91f92e300b426eb26a9a0fa67192590b1

**Comment by dsplaisted** [comment]
With some help from @nguerrera, I've figured out what's wrong and filed https://github.com/Microsoft/msbuild/issues/2688 for this.

You can work around it by removing the duplicate project references.  Specifically, remove the `ProjectReference` items from `testHost.UnitTests.csproj` which are also included in `TestPlatform.Settings.targets`.

**Comment by harshjain2** [comment]
I will try the workaround and verify if build works.
