### ISSUE TITLE
Add support for the `net40-client` target framework

### ISSUE THREAD

**Issue by Taritsyn** [dotnet/cli#7922]
It would be nice to have support of the .NET Framework 4 Client Profile.

**Comment by livarcocc** [comment]
Hi @Taritsyn, we currently have no plans of adding support to that TFM to the .NET Core SDK. You can try this [package](https://github.com/onovotny/MSBuildSdkExtras/blob/master/README.md) to see if adds support for that. I am not really sure it does.

**Comment by Taritsyn** [comment]
Hello, Livar!

Thanks for information.
