### ISSUE TITLE
dotnet new -i failes with 401 (unauthorized) when using private feed

### ISSUE THREAD

**Issue by tomstreet** [dotnet/cli#7923]
## Steps to reproduce
I have some private feeds setup in my AppData\Roaming\NuGet\NuGet.config.
These work fine with `dotnet restore` no problem (there are no local nuget.config files, just the global one).
I have published a template for dotnet new to one of the private feeds.
I then run `dotnet new -i the_template_package`

## Expected  behavior
I expect the template to install

## Actual behavior
It fails with a 401 unauthorized

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1306
