### ISSUE TITLE
Update the --info output

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/cli#7926]
Update --info to the following scheme:

```bash
$ dotnet --info
.NET Core SDK Information:
  SDK Version:  x.y.z
  SDK Build:    e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Runtime Environment:
  OS Name:      Mac OS X
  OS Version:   10.12
  OS Platform:  Darwin
  RID:          osx.10.12-x64
  Base Path:    /usr/local/share/dotnet/sdk/2.0.0/

.NET Core Host (dotnet) Information:
  Host Version: x.y.z
  Host Build:   fab8861ac7faf042c87a5c2f9f2d04c98b69f297

```

**Comment by rkeithhill** [comment]
Indeed.  The current output makes it hard to determine which "SDK" is being used.

**Comment by tmds** [comment]
A system can have multiple sdks installed.
If info only shows one, probably it's the one that is relevant to the current working directory?
It would be good to add this to the output:

when picking up global.json:
```
.NET Core SDK Information (global.json):
```
when no global.json:
```
.NET Core SDK Information (latest):
```

**Comment by rkeithhill** [comment]
A few other points.  I don't care too much whether the build info is listed as `<mumble> Build: <full sha-1 hash>` or `Commit SHA-1 hash: <short-hash>` as long is you pick one and stick with it for both the SDK and the host.  

Also, if we're going to call it `.NET Core SDK` (instead of just `SDK`) then shouldn't it be `.NET Core Runtime Environment:` to be consistent e.g.:

```
$ dotnet --info
.NET Core SDK Information:
  SDK Version:  x.y.z
  SDK Build:    e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

.NET Core Runtime Environment:
  OS Name:      Mac OS X
  OS Version:   10.12
  OS Platform:  Darwin
  RID:          osx.10.12-x64
  Base Path:    /usr/local/share/dotnet/sdk/2.0.0/

.NET Core Host (dotnet) Information:
  Host Version: x.y.z
  Host Build:   fab8861ac7faf042c87a5c2f9f2d04c98b69f297
```

But when you look at all the repeated ".NET Core" text above and observe that using `dotnet` implies .NET Core, maybe it should just be:
```
$ dotnet --info
SDK Information:
  SDK Version:  x.y.z
  SDK Build:    e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Runtime Environment:
  OS Name:      Mac OS X
  OS Version:   10.12
  OS Platform:  Darwin
  RID:          osx.10.12-x64
  Base Path:    /usr/local/share/dotnet/sdk/2.0.0/

Host (dotnet) Information:
  Host Version: x.y.z
  Host Build:   fab8861ac7faf042c87a5c2f9f2d04c98b69f297
```
I could go either way on that but more important is to be consistent. Either consistently use `.NET Core` or consistently not use it.  :-)

**Comment by KathleenDollard** [comment]
If we can display whether there is a global.json that is a win (like @tmds comment)
If we can display the path to the global.json that is in use, that is a bigger win (like suggested in #7407)

**Comment by KathleenDollard** [comment]
This issue is associated with [a similar issue in dotnet/cores-setup](https://github.com/dotnet/core-setup/issues/3502#issuecomment-362429240).

Both will remain as coordinated action is probable in both repos

**Comment by KathleenDollard** [comment]
OK, I put on my "don't make me think too much about such trivia" hat and came up with this. It needs polish, but let's start by asking if it seems a good idea to explain clearly to the reader what each value means. I think it will come out casual. 

And also: Pick build or hash, don't continue with both. I was told they exist here to help support. I just didn't do that yet as I don't know which is better. 

```
$ dotnet --info
SDK: dotnet version, reflecting any global.json:
  SDK Version:  2.1.300-preview1-002525
  SDK Build:    e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Runtime environment:
  OS Name:      Mac OS X
  OS Version:   10.12
  OS Platform:  Darwin
  RID:          osx.10.12-x64
  Base Path:    /usr/local/share/dotnet/sdk/2.0.0/

dotnet host (useful for support):
  Version  : 2.1.0-preview2-26129-0
  Build    : 5c7b2d33e76ee8052a6941a090fcd21252ce2ea8

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.0.3 [/usr/local/share/dotnet/sdk]
  2.1.3 [/usr/local/share/dotnet/sdk]
  2.1.300-preview1-002525 [/usr/local/share/dotnet/sdk]


.NET Core runtimes installed:
  Microsoft.AspNetCore.All 1.0.1 [C:\Program Files\dotnet\shared]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

If we are able to include global.json presence, then one of the following (desirable, but may not fit the current timeframe):

```
SDK: dotnet version (latest):
SDK: dotnet version (global.json):
SDK: dotnet version ([path]/global.json):
```

Thoughts?

**Comment by livarcocc** [comment]
Fixed by https://github.com/dotnet/cli/pull/8736.
