### ISSUE TITLE
Need command list installed runtimes and SDKs

### ISSUE THREAD

**Issue by rkeithhill** [dotnet/cli#7927]
## Steps to reproduce
Tell a project contributor to find out which versions of the .NET Core SDK they have installed to help you troubleshoot a build problem they are having.  

## Expected  behavior
You tell the user to run `dotnet list` to get a list of installed runtimes and SDKs.  Or perhaps there is a switch to control which is listed.

## Actual behavior
Basically you tell them [this](https://github.com/dotnet/announcements/issues/34) for the runtimes:

Operating System | Location
-- | --
Windows | C:\Program Files\dotnet\shared\Microsoft.NETCore.App\
macOS | /usr/local/share/dotnet/shared/Microsoft.NETCore.App/
Supported Linux platforms | /usr/share/dotnet/shared/Microsoft.NETCore.App/

and to dir another set of directories for the SDKs.  That's a spew.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by tmds** [comment]
`--list-sdks` and `--list-runtimes` have been added here: https://github.com/dotnet/core-setup/pull/3132
These are not yet in a released version.

**Comment by rkeithhill** [comment]
Duplicate of #7701
