### ISSUE TITLE
dotnet is not finding 2.0.0 SDK on system with it installed in the user's AppData dir

### ISSUE THREAD

**Issue by rkeithhill** [dotnet/cli#7928]
## Steps to reproduce
On a clean system (no previous .NET Core installs) Install 2.0.2 SDK from http://dot.net
Git clone the PowerShell repo: `git clone --recursive https://github.com/PowerShell/PowerShell.git`
Open PowerShell prompt and cd to PowerShell repo
Execute: `Import-Module .\build.psm1`, then `Start-PSBootstrap` and finally `Start-PSBuild`.
That will install .NET Core 2.0.0 into the user's AppData folder
Note: we have a global.json file in the repo root that pegs the SDK at 2.0.0
The Start-PSBuild command does a `dotnet --version` check and fails if it isn't `2.0.0`.

## Expected  behavior
global.json set to 2.0.0 should cause `dotnet --version` to return 2.0.0.

## Actual behavior
`dotnet --version` returns 2.0.2 so this particular user can't build even though he has 2.0.0 SDK installed.

## Environment data
`dotnet --info` output:
Not sure.  The original [issue](https://github.com/PowerShell/PowerShell/issues/5260) was filed on the PowerShell repo.

**Comment by johnbeisner** [comment]
@rkeithhill
'dotnet' does not consider versions that were installed to the user's AppData folder; this is by design.
"That will install .NET Core 2.0.0 into the user's AppData folder" - consider changing this installation location.

**Comment by rkeithhill** [comment]
That's good to know. Just out of curiosity, why does `dotnet` ignore SDKs installed under AppData?

**Comment by johnbeisner** [comment]
When multilevel lookup is enabled [please note: multilevel lookup is an opt-out], the behavior is to look in 'Program Files' for additional versions of the SDK.

**Comment by rkeithhill** [comment]
I've been perusing the dotnet CLI docs and I'm not seeing how to "opt-out".  How do you do this?

**Comment by rkeithhill** [comment]
BTW the PowerShell team is using a script from this repo to install dotnet - https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1

And it defaults to installing in %LocalAppData%\Microsoft\dotnet? So why doesn't this script install into a location that is copasetic with global.json?  Does this script need to be updated

**Comment by livarcocc** [comment]
Set the environment variable `MULTI_LEVEL_LOOKUP ` to false to disable it.

The install script is used to download a ZIP and it puts the contents of the ZIP in the path for your current shell session. We don't make any statements regarding the dotnet host being able to find the SDK in the default location that the install script installs the SDK.

Also note that if you use the install script, the expectation is that you will run dotnet.exe from where the script installed the SDK, and the host will find the SDK that is sitting right next to it.

**Comment by rkeithhill** [comment]
Thanks!  That helps.  I think we have an approach now that is a bit more bullet-proof and takes into account the SDK version specified by our global.json file.
