### ISSUE TITLE
dotnet-install.sh fails because the download URL returns 404

### ISSUE THREAD

**Issue by rhtnr** [dotnet/cli#7934]
## Steps to reproduce
Download the installer script - https://dot.net/v1/dotnet-install.sh
Run ./dotnet-install.sh 

## Expected  behavior
Should be able to download the binaries

## Actual behavior
If supplied with no params the installer script fails with the following error message - 

Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-sdk-1.0.4-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404

## Environment data
Debian 9

**Comment by rhtnr** [comment]
Accidentally submitted in the wrong place

**Comment by livarcocc** [comment]
This is the right place for issues with the install script.

**Comment by livarcocc** [comment]
@johnbeisner please take a look.

**Comment by johnbeisner** [comment]
@rhtnr
1.0.4 is the LTS and the default install version for this script. However, Debian 9 is not supported for 1.0.4.
Please consider installing the Linux portable 2.0 SDK:
./dotnet-install.sh --channel 2.0

**Comment by rhtnr** [comment]
Thank you @johnbeisner
