### ISSUE TITLE
Create Single Source of truth for Packaged Commands in Native Installers

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#794]
Right now if we change a command name or add a command, we need to make changes in a number of places:

1. https://github.com/dotnet/cli/blob/master/scripts/compile/compile-stage.sh
2. https://github.com/dotnet/cli/blob/master/scripts/compile/compile-stage.ps1
3. https://github.com/dotnet/cli/blob/master/packaging/debian/debian_config.json
4. https://github.com/dotnet/cli/blob/master/packaging/osx/scripts/postinstall

Ideally we should have only one place which defines what these packaged binaries are.

**Comment by piotrpMSFT** [comment]
This was fixed in MSBuild migration of CLI builds.
