### ISSUE TITLE
Dotnet CLI fails to build SLN with CloudServices

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#7941]
## Steps to reproduce
1) Have SLN with mixed full framework and Core code
2) Have CloudServices project in SLN
3) run `dotnet build` on the SLN

## Expected  behavior
Everything builds

## Actual behavior
Error
error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.0.2\Microsoft\VisualStudio\v10.0\Windows Azure Tools\2.9\Microsoft.WindowsAzure.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
The CLI does not support CloudServices projects, as the SDK (MSBuild files) for this type of project do not exist for the CLI.

For these kinds of projects, I suggest you use msbuild.exe directly to build them.

**Comment by sokket** [comment]
My point was that it *should* support these kinds of projects; it makes Azure attach easier. Otherwise, it is very difficult to utilize Azure resources within .NET Core. Not every company can afford to use Service Fabric, so the CLI should be able to utilize the Azure SDK MSBuild Targets installed in order to build
