### ISSUE TITLE
Developer-guide.md should mention Powershell 3.0 or greater required

### ISSUE THREAD

**Issue by wizofaus** [dotnet/cli#7946]
## Steps to reproduce
On Win 7 SP1 machine with git installed (and on path), attempted to build cli 
## Expected  behavior
Build should succeed

## Actual behavior
Build failed with "Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string".
Almost certainly due to Powershell version (I believe minimum required is 3.0)

After installing PS 3 & restarting the build was able to start.

**Comment by livarcocc** [comment]
@johnbeisner can you take a look at this, seems like the install script itself requires PS3.

**Comment by johnbeisner** [comment]
Machine = jbeisner-w7-1
OS = Windows 7 Enterprise - Service Pack 1
PowerShell = v1.0
Repo = dotnet/CLI
Branch = master

I could not reproduce the failure during the build nor could I reproduce the failure by calling 'dotnet-install.ps1' directly.

Script Output:
PS C:\G\JBcli\scripts\obtain> .\dotnet-install.ps1
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-sdk-1.0.4-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-sdk-1.0.4-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-dev-win-x64.1.0.4.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.4/dotnet-dev-win-x64.1.0.4.zip
dotnet-install: Adding to current process PATH: "C:\Users\jbeisner\AppData\Local\Microsoft\dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

**Comment by wizofaus** [comment]
dotnet-install.ps1 refers to $PsScriptRoot, which isn't defined automatically under PS1. Not sure how it works for you.
