### ISSUE TITLE
.NET Core console application does not find referenced assemblies

### ISSUE THREAD

**Issue by Pilchie** [dotnet/cli#7948]
_From @ioancrisan on October 13, 2017 10:26_

I have a console application that loads dynamically the assemblies found in the deployment folder. This works *after* we publish the app, but in debug mode we do not have any referenced assemblies in the output folder, from where those assemblies should be loaded. Side note: some of those assemblies come from referenced nuget packages. So, when trying to debug the app, no assemblies are loaded simply because they are not there. How should we develop with such a scenario? Thanks!

_Copied from original issue: dotnet/project-system#2890_

**Comment by Pilchie** [comment]
_From @Aaronontheweb on October 14, 2017 16:40_

We've run into this too - silently this week something in the .NET install script changed and our unit tests which depend on dynamically loading DLLs at runtime now fail

**Comment by Pilchie** [comment]
@livarcocc - sounds like differences between `dotnet build` and `dotnet publish`.  Can you answer?

**Comment by Pilchie** [comment]
Ping @livarcocc

**Comment by Pilchie** [comment]
_From @livarcocc on October 23, 2017 23:8_

Yes, sounds like the difference between build and publish. When invoking dotnet build we do not copy package references to the build output in order to safe build time. Instead, these assemblies are loaded from the package cache.

When you publish the application, in that case, we copy those assemblies to the publish output folder. Though keep in mind, that if your app is a portable app, we will not copy shared framework assemblies. If it is a self-contained app, we will copy everything.

@Aaronontheweb I am interested in your comment about the install script changing and breaking your scenario. I don't see how that's possible, unless it started downloading a different version of the CLI, but the behavior I described above has been the behavior since 1.0.0.

**Comment by Pilchie** [comment]
_From @ioancrisan on October 24, 2017 9:56_

@livarcocc I suppose what you described makes sense, however I'm still stuck on trying to debug my .NET Core app. Any ideas, a workaround?

**Comment by Pilchie** [comment]
_From @ioancrisan on October 24, 2017 10:1_

@livarcocc Would it be possible that upon debugging (some setting?), this to be performed from a "debug publish" folder, and not from the folder where it was built?

**Comment by Pilchie** [comment]
_From @ioancrisan on October 24, 2017 10:1_

I mean build is one thing and debug should be another thing.

**Comment by Pilchie** [comment]
@livarcocc should this be moved to either CLI or SDK?

**Comment by Pilchie** [comment]
_From @livarcocc on October 31, 2017 19:34_

Sure, move to the CLI please, we can continue helping @ioancrisan there.

**Comment by dasMulli** [comment]
This behavior can be changed by setting the `CopyLocalLockFileAssemblies` property to `true` in the project file.:

```xml
<PropertyGroup>
  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
</PropertyGroup>
```

This will copy all NuGet assemblies to the output directory and allow for custom path-based reflection to work.
Note that this kind of reflection could also be done by inspecting the dependency closure using `DependencyContext.Default.RuntimeLibraries` (needs `Microsoft.Extensions.DependencyModel` NuGet package) which gives all paths to referenced libraries by inspecting the `deps.json` file.

**Comment by ioancrisan** [comment]
@dasMulli Thanks for the tip, it just worked!

**Comment by livarcocc** [comment]
Closing this as we have a configuration for it.

Thanks for replying @dasMulli.
