### ISSUE TITLE
Add EF Core CLI Tools to default api templates (and more?)

### ISSUE THREAD

**Issue by julielerman** [dotnet/cli#7957]
With ASPNETCore.All in new aspnetcore csproj via the template, we will go forward expecting all of the EF Core tasks to work easily. However, the CLI tools are not included, so users will find out the hard way that they have to go back to csproj and add them in. For experienced EF Core users, it's not a big deal, but for new users it could be a PIA.

## Steps to reproduce
Create an empty folder
run dotnet new API
define a data model (some classes , a dbcontext)
run dotnet ef migrations add init

## Expected  behavior
Becasue CSProj has all of the needed EF Core packages via ASPNET.All package , I woud expect that it would also have the needed migration CLI Tool Reference to EFCore.Tools.DotNet.

Migration should be created

## Actual behavior
Throws "No executable found matching command "dotnet-ef""error
That's because CSproj does not have 
  `<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />`

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This template is actually not maintained in the CLI repo, we are just carriers for it. I am going to move it to the repo where these templates are crafted.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/templating#141
