### ISSUE TITLE
The SDK needs a tool to enable aquiring matching symbols for platforms that are being targeted

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#7959]
We're providing zips for this scenario but we really need to have a tool that can easily get the right zips/tar.gz's that will let you debug through the platform layers.

**Comment by lt72** [comment]
See corresponding issue on [CoreCLR](https://github.com/dotnet/coreclr/issues/14794)

**Comment by Petermarcu** [comment]
Ah. I didn't see that one. I'll leave it to you to decide where you want to track it.

**Comment by livarcocc** [comment]
Seems like yet another perfect example of some global tool.

**Comment by livarcocc** [comment]
Let's assume this will be a global tool for now and track it in the CoreCLR bug. If it turns out it makes more sense as a native verb on the CLI, we can re-activate this.

cc @KathleenDollard
