### ISSUE TITLE
Build produces empty NuPkg's

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#797]
Recent updates designed to enable signing of our libraries before packaging, #734, pointed out some gaps in our build script whereby not all packaged libraries were being built before packing. This meant that when we separated build from pack then these libraries were not being produced and their resultant nupkg's were created as empty. 

We need to update our build scripts to build these missing libraries and put them into the corresponding nupkgs.

/cc @davidfowl @livarcocc

**Comment by krwq** [comment]
I think this is also a good chance to add some warning/error to nuget pack whenever output nuget package is empty

**Comment by davidfowl** [comment]
Sounds good

**Comment by piotrpMSFT** [comment]
Packages are now getting created, though for some reason Microsoft.DotNet.ProjectModel.Workspaces is still empty.

Agreed we should also add warnings when empty nupkgs are generated.

**Comment by piotrpMSFT** [comment]
fixed by #868
