### ISSUE TITLE
Want to migrate on dnx to cli with entity framework core #7956

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/cli#7975]
Hi Livor,
Thanks for updating steps in my previous issue #7956  !!
I have followed your defined steps but found below issue.
I have download again SDK from https://dot.net  url and again its showing older version of CLI as below  
C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Please advice ?

**Comment by ankurjasoria** [comment]
@livarcocc  I am sharing you difference between CLI version in my actual application and test application as below

**Test Application** :

C:\testcli>dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**My Application** : 
C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Please advice ?

**Comment by livarcocc** [comment]
You have to remove or update your global.json, if you have one. Or, make sure that the new SDK is ahead of the old one in your path.

**Comment by ankurjasoria** [comment]
@livarcocc  Thanks all steps work for me succefully and dotnet ef command works fine !!!
Now I am facing issue below build issue

C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform>dotnet ef migrations add testMigration
C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(96,5): error : The TargetFramework value 'dnx451' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform\CenterManagementSystem.Platform.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(96,5): error : The TargetFramework value 'dnx451' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform\CenterManagementSystem.Platform.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.45
Build failed.

C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform>dotnet build
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(96,5): error : The TargetFramework value 'dnx451' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform\CenterManagementSystem.Platform.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(96,5): error : The TargetFramework value 'dnx451' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform\CenterManagementSystem.Platform.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.43

Please advice ?

**Comment by livarcocc** [comment]
That TFM does not exist, as the message suggests. I would recommend moving to something like netcoreapp2.0, if this is an app or netstandard2.0 if this is a library.

**Comment by ankurjasoria** [comment]
@livarcocc Thanks for quick update !!
How can I move to netcoreapp2.0/netstandard2.0 ? Please suggest if there is any simplified steps or any specific reference url ?

Also I am facing issue as below error
1) When opening my VisualStudio then error message as below

"The following error occurred attempting to run the project model server process (2.0.2)
Unable to start the Process
The project model server process provides intellisence,build and reference information to Visual Studio
and without it your experience very limited. Please try opening and reopening Visual Studio to see if that correct the problem. Alternately, check that the .NET Core SDK is properly installed. "   

2) In Solution Explorer, My project Load failed and when I am right click on my project then click on Reload Project then below message showing in Visual Studio.

"The project file 'C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform\CenterManagementSystem.Platform.xproj' has been moved,renamed or is not on your system. "
Or When I am seeing my project folder there is one more folder which is having name "backup" and contain below file 
     a) CenterManagementSystem.Platform
     b) CenterManagementSystem.Platform.xproj.user
     c) project.json
     d) project.lock
 
Please suggest regarding above query ?

**Comment by livarcocc** [comment]
I don't think there are any guides (or at least I don't know of any) that talks about migrating from dnx project.json to the new csproj format. 

Also, the new csproj format only works in VS2017 and forward, you won't be able to open these projects in VS 2015.

Lastly, if something is still referencing a xproj project, that means it needs to be updated to reference the csproj. Depending on how you run migration, it will do that for you, but I don't know how you did it.

The backup folder is there just in case you want to revert back to project.json. It is the place where we move your old artifacts during migration, because we now use a single csproj file instead of those ones under backup.

**Comment by livarcocc** [comment]
I don't think there are any guides (or at least I don't know of any) that talks about migrating from dnx project.json to the new csproj format. 

Also, the new csproj format only works in VS2017 and forward, you won't be able to open these projects in VS 2015.

Lastly, if something is still referencing a xproj project, that means it needs to be updated to reference the csproj. Depending on how you run migration, it will do that for you, but I don't know how you did it.

The backup folder is there just in case you want to revert back to project.json. It is the place where we move your old artifacts during migration, because we now use a single csproj file instead of those ones under backup.

**Comment by livarcocc** [comment]
On your new csproj, look for a property called TargetFramework or TargetFrameworks. If it has dnx in there, replace it with the TFMs I suggested above.

**Comment by ankurjasoria** [comment]
@livarcocc  I am sharing you my complete csproj file. Please check this regarding my build issue

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>CenterManagementSystem.Platform Class Library</Description>
    <Authors>RichardA</Authors>
    <TargetFramework>dnx451</TargetFramework>
    <AssemblyName>CenterManagementSystem.Platform</AssemblyName>
    <PackageId>CenterManagementSystem.Platform</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework.Commands" Version="7.0.0-rc1-final" />
    <PackageReference Include="EntityFramework.MicrosoftSqlServer" Version="7.0.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="3.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileProviderExtensions" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="MailKit" Version="1.10.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'dnx451' ">
    <Reference Include="System.configuration" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>

Please advice ?

**Comment by ankurjasoria** [comment]
@livarcocc  I am sharing you my complete csproj file. Please check this regarding my build issue

<Project Sdk="Microsoft.NET.Sdk>
  <PropertyGroup>"
    <Description>CenterManagementSystem.Platform Class Library</Description>
    <Authors>RichardA</Authors>
    <TargetFramework>dnx451</TargetFramework>
    <AssemblyName>CenterManagementSystem.Platform</AssemblyName>
    <PackageId>CenterManagementSystem.Platform</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework.Commands" Version="7.0.0-rc1-final" />
    <PackageReference Include="EntityFramework.MicrosoftSqlServer" Version="7.0.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="3.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileProviderExtensions" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
    <PackageReference Include="MailKit" Version="1.10.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'dnx451' ">
    <Reference Include="System.configuration" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>
</Project>"

Please advice ?

**Comment by livarcocc** [comment]
I am not sure what is the totality of things that you are going to have to change. Like I said, we have no guidance regarding migration from dnx to csproj. For your package references, I would look for that are the current package versions, maybe using a new template, and then would pull that into your csproj.

As for the TargetFramework, you need to change this `<TargetFramework>dnx451</TargetFramework>` to something like this `<TargetFramework>netcoreapp2.0</TargetFramework>`. Note that the value here depends really on what version of the runtime you are trying to target.

I also think you should be able to delete this piece:

```
<ItemGroup Condition=" '$(TargetFramework)' == 'dnx451' ">
    <Reference Include="System.configuration" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
```

Lastly, I don't know if these packages are correct still, as in, if they are the correct ones or even if they have the correct version:

```
<PackageReference Include="EntityFramework.Commands" Version="7.0.0-rc1-final" />
    <PackageReference Include="EntityFramework.MicrosoftSqlServer" Version="7.0.0-rc1-final" />
    <PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" Version="3.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileProviderExtensions" Version="1.0.0-rc1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.2" />
```

Hope this helps.
