### ISSUE TITLE
Is there a tool like the "resgen.exe" in dotnet-cli?

### ISSUE THREAD

**Issue by WHATSAF** [dotnet/cli#7988]
I have no any version of Visual Studio or .Net Framework installed. And if i want to generate a .resx file, i must install the Visual Studio or .Net Framework. If this is in plans, and when distributing?

**Comment by livarcocc** [comment]
Unfortunately, the CLI does not have any tool for this cross-plat. We have a bug for this already in a separate repo: https://github.com/dotnet/sdk/issues/678.

**Comment by kasper3** [comment]
@livarcocc, in other issue https://github.com/dotnet/cli/issues/7084 you pointed to MSBuild repo. Should SDK issue be closed? Can we get closure on what is missing from us getting resgen and is it not possible to have it by 2.1 milestone? Thanks!

**Comment by livarcocc** [comment]
I believe the MSBuild issue is the right one. I will take a look and probably close the SDK one.
