### ISSUE TITLE
Debian Failed to initialize CoreCLR, HRESULT: 0x80131500

### ISSUE THREAD

**Issue by Frank591** [dotnet/cli#7989]
##  Actual behavior
publish on Windows machine: **dotnet publish --runtime debian.8-x64 --configuration Release**

Starting on debian 9 machine:
**dotnet my.dll** 
failed with error **Failed to initialize CoreCLR, HRESULT: 0x80131500**
##  Expected behavior
dotnet apps should work on debian 9.  

Are there some fixes or workarounds for this problem?

## Environment data
developer@debian:~/monitoring_deploy$ dotnet --info

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**deploy$ sudo strace -o logfile dotnet my.dll output:**
[logfile.txt](https://github.com/dotnet/cli/files/1457508/logfile.txt)

**Comment by livarcocc** [comment]
I don't think you can publish to debian.8 and run it on debian.9. I think in this case you might have more success publishing to linux-x64, our generic linux version.

In any case, I am moving this bug over to core-setup

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3399
