### ISSUE TITLE
cibuild fails on dotnet restore

### ISSUE THREAD

**Issue by benmishkanian** [dotnet/cli#8003]
## Steps to reproduce
./cibuild.sh --target Mono

## Expected  behavior
Build succeeds

## Actual behavior
```
Installing dotnet cli...
Restoring BuildTools version 1.0.27-prerelease-00927-05...
Failed to create prime the NuGet cache. restore failed with: 1
ERROR: Could not restore build tools correctly. See '/home/bmishkania/msbuild-tar/msbuild-15.4.8.50001/init-tools.log' for more details.1
```
Snippet from init-tools.log:
```
log  : Installing Microsoft.NETCore.App 1.0.1.
error: Access to the path '/home/bmishkania/.nuget/packages/microsoft.netcore.jit/1.0.4/rhs2yspr.3a2' is denied.
error:   Bad file descriptor
```
That is a 0-byte file. The permissions on that file are `-rwxr--r--` and I am the owner. When I run cibuild again, it fails on the same issue, but with a different filename (e.g. `232zklpc.su5`).
## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003686)

Product Information:
 Version:            1.0.0-preview3-003686
 Commit SHA-1 hash:  038fb6fbae

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64

**Comment by livarcocc** [comment]
You are using a very old version of the SDK. Can you please update your SDK version and try again?

**Comment by benmishkanian** [comment]
I had the same issue initializing NuGet package cache using dotnet-sdk-2.0.2-linux-x64.

This issue seems to be related somehow to using networked storage. It seems that if I move the SDK and override the NuGet package cache directory to local storage, then it works. But this isn't a very good workaround for our environment, where local storage is only meant to be used for transient temp files.

**Comment by livarcocc** [comment]
In the 2.0 SDK, we no longer perform a NuGet restore to expand the cache. We rather just decompress the archive next to the SDK itself.

Let me know if with the 2.0 SDK you are still getting first run errors or restore issues (after the first run).

**Comment by benmishkanian** [comment]
Thanks. Looks like 2.0 SDK is able to restore the packages that the older one could not. Unfortunately the project I am trying to compile seems to depend on SDK 1.0.0-preview3. (Using SDK 2.0 on the project.json errors with `error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.`) So I guess I will have to ask that project's maintainer for help.

**Comment by livarcocc** [comment]
Yes. We haven't supported project.json for a while now and actually, the 1.0.0-preview2 was the last release we did that supported project.json.

Please, migrate to csproj.

Closing this issue for now since it seems to work on 2.0.
