### ISSUE TITLE
Cordova Plugin Diagnostic Visual Studio 2017 Error

### ISSUE THREAD

**Issue by unixp** [dotnet/cli#8013]
Hello mate
I installed your plugin in my apache cordova app vs2017 and i recived lots of error while build
cordova tools > 6.3.1 platform > 5.2.1 and nodjs > 44.3
min target 14 and max 23
All android sdk and build tools installed
Build Errors :
![32649897-02b71a98-c611-11e7-9fa6-9a756e9d8e9b](https://user-images.githubusercontent.com/33541948/32776300-5b59f7e0-c947-11e7-9b48-78482281b384.png)
![32650156-f559f63a-c611-11e7-8967-9181fcb9a3b3](https://user-images.githubusercontent.com/33541948/32776320-68844db2-c947-11e7-9090-a00e3c6fb04c.png)

![32650101-bf0fb664-c611-11e7-9f28-2e5ac85073cd](https://user-images.githubusercontent.com/33541948/32776309-6212d34a-c947-11e7-845a-cc2da4cc722c.png)

**Comment by livarcocc** [comment]
I am sorry, I don't think this is our plugin.
