### ISSUE TITLE
Why Not Enable Least Building Works

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8036]
@eaglexiang commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096)

Makefile is used for many causes including reduce repeatedly building works. Files not effected by changes needn't to be built again.

But dotnet will build every file each time, which waste our time a lot. Why not build a feature to improve that like command `make`?

---

@Petermarcu commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344959983)

Dotnet build is incremental. There are places where there are bugs or things need improvement but if something hasn't changed, generally, it shouldn't get rebuilt. If you are seeing that it may be a bug in the sdk. Msbuild supports incremental build. Can you give more details on where you see this?

---

@eaglexiang commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344974463)

Thanks for reply, this is my environment:
OS: ArchLinux
dotnet: 2.0.2

BTW, do you mean incremental build is only supported by msbuild but not dotnet? 

I tried `dotnet run` but still happened 'rebuild'.

---

@eaglexiang commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344974481)

Thanks for reply, this is my environment:
OS: ArchLinux
dotnet: 2.0.2

BTW, do you mean incremental build is only supported by msbuild but not dotnet? 

I tried `dotnet run` but still happened 'rebuild'.

---

@Petermarcu commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344977045)

Can you share the console output of `dotnet run`. MSBuild is what is used during dotnet build and dotnet run so both support incremental build. It may say "rebuild" but there may be a bunch of "no-ops" in there. I also know that for the next release of the SDK, there is a lot of focus on finding an fixing bugs that are causing rebuilds even though things haven't changed.

---

@eaglexiang commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344980506)

No output show that files're rebuilt. I judge it with the time `dotnet run` waste. In Visual Studio I can run bin output directly, so 2nd time is quickier than 1st. But time taken in first and second times are same with dotnet core on Linux.

---

@eaglexiang commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344986205)

Sorry I fixed my words.

---

@Petermarcu commented on [Thu Nov 16 2017](https://github.com/dotnet/core/issues/1096#issuecomment-344989622)

Ok, I'm going to move this issue to the dotnet/cli repo where the right people can get engaged to make sure we can address the incremental run scenario.

**Comment by livarcocc** [comment]
This is by design and like @Petermarcu said, the fact that we invoke msbuild does not mean that a build is happening.

We use msbuild to determine if anything has changed and that a new build is needed. In VS, visual studio keeps track of all files in the solution and can determine by itself if something has changed or not.

In the CLI, because we are not a long lasting process, we don't have that opportunity and therefore rely on MSBuild's incremental checks.
