### ISSUE TITLE
cli-test-env.sh cannot run test on macOS

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8039]
There is 2 problem, `uname` is not evaluated, the following can make it work. However the hard part is RID in mac has the version number. Which it should not

```sh
uname=$(uname)
if [ "$(uname)" == "Darwin" ]
then
  RID=osx.10.13-x64
else
  RID=linux-x64
fi
```

**Comment by peterhuene** [comment]
Also, would be nice if we could remove the `==` in favor of `=` for the zsh users among us 😄

**Comment by wli3** [comment]
it was due to osx.10.13 is not in the rid graph and runtime give the full name back. it is in and corrected now https://github.com/dotnet/cli/blob/master/scripts/cli-test-env.sh#L19
