### ISSUE TITLE
Beta Release Documentation

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#804]
We will expand this. For now keeping notes on what is needed:
- Versioning breaking change documentation
- Uninstall instructions for pre-beta

**Comment by blackdwarf** [comment]
Moar needed!!

* Release notes
* Known issues
* Updated install instructions for all paths
* List of all the enviornment variables

**Comment by blackdwarf** [comment]
This is an old issue so closing since we are not tracking beta anymore.
