### ISSUE TITLE
Cannot download runtime from 'Release/1.1.X' channel using dotnet-install.ps1

### ISSUE THREAD

**Issue by hubuk** [dotnet/cli#8043]
## Steps to reproduce
1. Download `dotnet-install.ps1` from https://dot.net/v1/dotnet-install.ps1
2. Run command: `./dotnet-install.ps1 -sharedRuntime -version 1.1.5-servicing-001649-00`

## Expected  behavior
After checking:
Downloading link: `https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-runtime-1.1.5-servicing-001649-00-win-x64.zip`
Downloading legacy link: `https://dotnetcli.azureedge.net/dotnet/Runtime/1.1.5-servicing-001649-00/dotnet-win-x64.1.1.5-servicing-001649-00.zip`
script should also check location:
`https://dotnetcli.azureedge.net/dotnet/release/1.1.0/Binaries/1.1.5-servicing-001649-00/dotnet-win-x64.1.1.5-servicing-001649-00.zip`

## Actual behavior
`release/1.1.0/Binaries` location is not being considered by the script.

## Environment data
```ps1
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.19
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.19
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by johnbeisner** [comment]
@hubuk 
'release/1.1.0/Binaries' is not a supported path
Please use the parameters:
"-sharedRuntime -channel 1.1" or "-sharedRuntime -version 1.1.5"

This will install the latest 1.1 release of the runtime.

**Comment by hubuk** [comment]
@johnbeisner: Maybe this is not a most common use case but I just realized that there are some builds not available to download via dotnet-install scripts. One of them is the latest daily build listed in https://github.com/dotnet/core-setup#daily-builds page for Release/1.1.X which is `1.1.5-servicing-001649-00`. There are more. Probably all 1.1.X servicing builds which versions are listed on this [myget](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App/1.1.5-servicing-001649-00) page.
Is there any reason why these builds are not available on 'dotnet/Runtime' path?

**Comment by johnbeisner** [comment]
@hubuk 
You are correct in the observation that not all the Runtimes are available to install via the dotnet-install scripts. I think this would be a question for the Runtime folks. I will move the issue to the proper place.

**Comment by johnbeisner** [comment]
This issue was moved to dotnet/core-setup#3430
