### ISSUE TITLE
'dotnet build <SLN>' fails if path in the solution file is not case sensitive

### ISSUE THREAD

**Issue by joemey** [dotnet/cli#8048]
## Steps to reproduce

```
mkdir ProjectA
mkdir ProjectB
cd ProjectA
dotnet new classlib
cd ../ProjectB/
dotnet new classlib
cd ..
dotnet new sln
dotnet sln add projecta\projecta.csproj <- this will break the build
dotnet sln add projectb\projectb.csproj
```

Add the following to ProjectB
```xml
<ItemGroup>
    <ProjectReference Include="..\ProjectA\ProjectA.csproj" />
</ItemGroup>
```

And build the solution with

```
dotnet build
```

## Expected  behavior

```
λ  dotnet build
Microsoft (R)-Buildmodul, Version 15.4.8.50001 für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  ProjectA -> C:\temp\test\ProjectA\bin\Debug\netstandard2.0\ProjectA.dll
  ProjectB -> C:\temp\test\ProjectB\bin\Debug\netstandard2.0\ProjectB.dll

Der Buildvorgang wurde erfolgreich ausgeführt.
    0 Warnung(en)
    0 Fehler

Verstrichene Zeit 00:00:03.00
```

## Actual behavior

```
λ  dotnet build
Microsoft (R)-Buildmodul, Version 15.4.8.50001 für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  projecta -> C:\test\projecta\bin\Debug\netstandard2.0\projecta.dll
C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error : Die Projektinformationen für "C:\test\projecta\projecta.csproj" wurden nicht gefunden. Dies ist möglicherweise auf einen fehlenden Projektverweis zurückzuführen. [C:\test\projectb\projectb.csproj]

Fehler beim Buildvorgang.

C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(114,5): error : Die Projektinformationen für "C:\test\projecta\projecta.csproj" wurden nicht gefunden. Dies ist möglicherweise auf einen fehlenden Projektverweis zurückzuführen. [C:\test\projectb\projectb.csproj]
    0 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:00:02.99
```

Running the build with `/v:d` or `/v:diag` did not help as it produced no additional information except
```
Die Ausführung der GenerateDepsFile-Aufgabe ist abgeschlossen -- FEHLER.
```

I had to build my own `Microsoft.NET.Build.Tasks.dll`[*] to be able to debug the `GenerateDepsFile`-Task.

The problem here is that in 
https://github.com/dotnet/sdk/blob/8992a1b11f55b93bea97aa8483de8c85a986c070/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L623-L627
`_referenceProjectInfos` contains a list of the **case sensitive** absolute paths to the referenced projects and for some reason the path from the SLN which is not case sensitive is used to find the referenced project. 

## Environment data
```
λ  dotnet --info
.NET-Befehlszeilentools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

## Workaround

Change the projet references inside the SLN to the correct case sensitive version

[*] On a side note
Debugging the `Microsoft.NET.Build.Tasks.dll` did not work out of the box too.
After adding `Debugger.Launch();` in `GenerateDepsFile.Execute()`, building the project and copying the output to `C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\tools` I could attach Visual Studio to the process but was unable to debug because Visual Stiudio wouldn't load my debug PDB (see dotnet/core-setup#3138).

After some googling and trying the same with VSCode I found the following warning while attaching to the build process
```
WARNING: Could not load symbols for 'Microsoft.NET.Build.Tasks.dll'. 'C:\Program Files\dotnet\sdk\2.0.2\Sdks\Microsoft.NET.Sdk\build\..\tools\netcoreapp1.0/\Microsoft.NET.Build.Tasks.pdb' is a Windows PDB. These are not supported by the cross-platform .NET Core debugger.
```
After adding 
```xml
<DebugType>portable</DebugType>
```
to the `Microsoft.NET.Build.Tasks` project and rebuilding it I was finally able to debug the Task.

**Comment by livarcocc** [comment]
@eerhardt this has come up a few times before. Do you have any suggestions on how to fix this? Do you know why we take the path from the metaproj generated for the solution file instead of the one from the ProjectReference itself?

**Comment by eerhardt** [comment]
One option would be to make that Dictionary use an `IgnoreCase` comparer when running on Windows (or any OS with a case insensitive file system).

This issue is, we need to match up what MSBuild provides (see [here](https://github.com/dotnet/sdk/blob/2c5dd65f7314d80a6db98a80078fdcee88286301/src/Tasks/Microsoft.NET.Build.Tasks/SingleProjectInfo.cs#L61)) with what NuGet's project.assets.json file contains (see [here](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/DependencyContextBuilder.cs#L613-L620).  When they differ, this issue happens.

So potentially another fix would be for the project.assets.json file to embed the full path to the project in the same casing as the MSBuild `MSBuildSourceProjectFile` item metadata for the ProjectReference.  Currently, the project.assets.json file only contains the relative path (with the "incorrect" casing). Ex:

```
    "Microsoft.DotNet.PlatformAbstractions/2.1.0-preview1-25917-0": {
      "type": "project",
      "path": "../Microsoft.DotNet.PlatformAbstractions/Microsoft.DotNet.PlatformAbstractions.csproj",
      "msbuildProject": "../Microsoft.DotNet.PlatformAbstractions/Microsoft.DotNet.PlatformAbstractions.csproj"
    }
```

**Comment by KathleenDollard** [comment]
If we fix by doing an IgnoreCase on the build, moving the project between OS will still break. 

Can add get smarter? Does it check for the file?

**Comment by AngelosP** [comment]
What about @KathleenDollard's suggestion @eerhardt? The operation of adding a project to a solution must already be checking if the path to the project is valid. Retrieving the correct casing at that moment should be possible and in theory without a performance penalty. That would also save as from having to change project.assets.json.

**Comment by eerhardt** [comment]
That would solve these exact repro steps, but it wouldn't solve the case where someone manually updated the `.sln` file, or some other tool updated the `.sln` file with the wrong casing.  Or the case where the project and `.sln` was created with one casing and then the project path changed on disk without updating the `.sln` file.

In general, there are other ways to get into this error situation.

**Comment by peterhuene** [comment]
Currently `dotnet` ignores case when checking for the existence of project references (`dotnet add reference` and `dotnet remove reference`) and when checking for the existence of a project in a solution (`dotnet sln add` and `dotnet sln remove`).  These checks are not platform specific and are currently enforced on case-sensitive file systems.

Finding the "actual casing" of a file path is problematic: as far as I know, there is no way to do so currently in corefx (https://github.com/dotnet/corefx/issues/1086) and the casing can still "go out of sync" through a manual editing of the solution/project files.

Given this, I would propose simply changing the dictionary in question to ignore case as well.

**Comment by KathleenDollard** [comment]
We should be consistent in how we handle this. I agree that we change the dictionary to ignore case. 

Are there any scenarios this could result in problems for users? I am just considering whether this is a minor bug fix or something we need to talk about.

**Comment by peterhuene** [comment]
It would impact users that really do have two package references that differ on case (Linux and case-sensitive APFS users on OSX).  Given our tooling currently prevents users from adding references / projects based on case differences, users would have to have manually modified the solution / project files to add the entries.  I would not be surprised if no one ever runs into this (having `SRC/foo.csproj` and. `src/foo.csproj` in your repo would not be a good practice).
