### ISSUE TITLE
Change the default verbosity for dotnet clean to normal.

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/cli#8049]
The default verbosity level of the tooling is too conservative in my opinion. 

`dotnet clean` shows no indication that is is doing something or that it even had something to do, and what it did took X amount.

![clean](https://user-images.githubusercontent.com/245275/32947937-a7703b82-cb9d-11e7-98ba-77bc279fe2ae.gif)

Now the `restore` is implicit it takes quite some time before anything is displayed in my terminal. 

![with-restore](https://user-images.githubusercontent.com/245275/32947695-82b68d24-cb9c-11e7-9a74-ba1cf9b84efc.gif)

Compare this with `--no-restore`

![without-restore](https://user-images.githubusercontent.com/245275/32947739-c66e9a7a-cb9c-11e7-897b-558dddab53d9.gif)

Similarly if I do 

```
dotnet clean src\Elasticsearch.sln
dotnet restore src\Elasticsearch.sln
dotnet build src\Elasticsearch.sln --no-restore
```

It can take quite a long time before the first project shows up as being build 

![without-restore-full-build](https://user-images.githubusercontent.com/245275/32947871-65bddbcc-cb9d-11e7-8bca-4997de386ab8.gif)

Not particularly bad in the previous gif but I have seen worse.

**Comment by livarcocc** [comment]
We are making a huge push for performance for our next release that will alleviate many of these issues.

We have also changed the verbosity for implicit restore for our 2.1.1 release out of release/15.5.

This is what you will get now with implicit restore:

```
$ dotnet build
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /ef/ef.csproj...
  Restore completed in 32.7 ms for /ef/ef.csproj.
  Generating MSBuild file /ef.csproj.nuget.g.props.
  Generating MSBuild file /ef.csproj.nuget.g.targets.
  Restore completed in 299.3 ms for /ef/ef.csproj.
  ef -> /ef/bin/Debug/netcoreapp2.0/ef.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.03
```

As for dotnet clean, while I am not 100% sure it makes sense to change its default verbosity compared to the other verbs, I agree that waiting a while with no output is not ideal. Plus, the normal clean output seems to be a lot "cleaner" then the normal output for clean, which is below:

```
Microsoft (R) Build Engine version 15.5.179.9764 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 11/17/17 11:25:50 AM.
     1>Project "/ef.csproj" on node 1 (Clean target(s)).
     1>CoreClean:
         Deleting file "/ef/bin/Debug/netcoreapp2.0/ef.deps.json".
         Deleting file "/ef/bin/Debug/netcoreapp2.0/ef.runtimeconfig.json".
         Deleting file "/ef/bin/Debug/netcoreapp2.0/ef.runtimeconfig.dev.json".
         Deleting file "/ef/bin/Debug/netcoreapp2.0/ef.dll".
         Deleting file "/ef/bin/Debug/netcoreapp2.0/ef.pdb".
         Deleting file "/ef/obj/Debug/netcoreapp2.0/ef.csproj.CoreCompileInputs.cache".
         Deleting file "/ef/obj/Debug/netcoreapp2.0/ef.AssemblyInfoInputs.cache".
         Deleting file "/ef/obj/Debug/netcoreapp2.0/ef.AssemblyInfo.cs".
         Deleting file "/ef/obj/Debug/netcoreapp2.0/ef.dll".
         Deleting file "/ef/obj/Debug/netcoreapp2.0/ef.pdb".
     1>Done Building Project "/ef/ef.csproj" (Clean target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.51
```
I will also update the title of this bug to cover only a change to clean verbosity. With the change to implicit restore verbosity, I don't think we need to do any there at the moment.
cc @KathleenDollard what is your opinion on this?
