### ISSUE TITLE
ProjectModelServer - Framework friendly names don't match previous version of the DTH

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#805]
@troyDai

**Comment by troydai** [comment]
/cc @davidfowl 
@BillHiebert how critical is this issue? I assume we use the friendly name for display only, right? In that case, do we have an agreement on what's the friendly name should look like for frameworks?

**Comment by BillHiebert** [comment]
It is pretty important, as it appears in the solution explorer, error list, intellisense context dropdown, etc. The friendly name comes from the frameworklist.xml files for desktop frameworks and I think the old DTH used to extract it from there. Not sure where the one for dnx came from.

**Comment by davidfowl** [comment]
Super critical and easy to do

**Comment by troydai** [comment]
Fixed in ce3e719
