### ISSUE TITLE
DOTNET_PACKAGE_CACHE needs to win over app_local

### ISSUE THREAD

**Issue by glennc** [dotnet/cli#806]
This is a spec and host change. Assembly loading order should be:

   1. Servicing: First so that the serviced assemblies always win
   2. Dotnet_Packages_cache: 2nd so that assemblies can be pre-installed in location in environments like Antares and have the host load assemblies from a faster disk.
   3. App_Local: When I have published most, if not all, dependencies are here so by default this is the location where everything ends up coming from
   4. Packages (i.e. shared location): Allows you to run an app that has been built with `dotnet compile`, in that it does’t have all assemblies local to the binary

@anurse @schellap

**Comment by schellap** [comment]
Will get the PR out soon. @glennc have you already deployed the host. I am asking to gauge how much testing the host has seen.

**Comment by glennc** [comment]
We are spinning up some perf benchmarks at the moment that use the host to run a web application on Azure. So not a great deal of testing yet, just starting to ramp up on things using the host.
