### ISSUE TITLE
dotnet pack doesn't choose the right version for ProjectReferences

### ISSUE THREAD

**Issue by MangelMaxime** [dotnet/cli#8073]
Hello, I have a problem with `dotnet pack` command and `ProjectReferences` resolve version. It was working on dotnet 2.0.0

cc @forki

## Steps to reproduce

Repo used: https://github.com/MangelMaxime/Fulma

* git clone git@github.com:MangelMaxime/Fulma.git
* git checkout repro_nuspec_bug
*  .\build.cmd 
* cd src
* cd Fulma.Extensions
* dotnet pack -c Release /p:Version=0.1.0-beta-007 /p:PackageReleaseNotes="* DOT NOT PUBLISH THIS VERSION IS A TEST FOR NUSPEC BUG REPRODUCTION"

## Expected  behavior

In the nuspec file:
`<dependency id="Fulma" version="1.0.0-beta-005" exclude="Build,Analyzers" />`

## Actual behavior

In the nuspec file:
`<dependency id="Fulma" version="0.1.0-beta-007" exclude="Build,Analyzers" />`

## Environment data

`dotnet --info` output:

Machine 1:
```
Outils en ligne de commande .NET (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

Machine 2:
```
.NET-Befehlszeilentools (2.0.3)

Product Information:
Version: 2.0.3
Commit SHA-1 hash: 12f0c7efcc

Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

Version : 2.0.3
Build : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

This is also failing on my computer under Linux. I don't have access to it ATM.

Edit: Add the repo url

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6209
