### ISSUE TITLE
dotnet publish with "--self-contained" and "--runtime" doesn't respect "--output" parameter

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#8087]
_From @lyze237 on November 20, 2017 10:27_

Hello,

I'm currently trying to publish into the `build/publish` directory but when I run the `dotnet publish` command together with `--self-contained` and `--runtime` it won't respect the `--output` parameter:

    dotnet.exe publish "./Solution.sln" --output "D:/Sources/Solution/build/publish" --runtime win-x64 --self-contained

Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Project-> D:\Sources\Solution\Project\bin\Debug\netcoreapp2.0\win-x64\project.dll
  Project -> D:\Sources\Solution\build\publish\

The directorys content after running the command:

**D:/Sources/Sources/Project/bin/Debug/netcoreapp2.0/win-x64**

    hostpolicy.dll  project.deps.json  project.exe  project.runtimeconfig.dev.json
    hostfxr.dll    project.dll        project.pdb  project.runtimeconfig.json

**D:\Sources\Solution\build\publish**

Literally all dlls of the framework and dependencies but no exe.

Could somebody help?

_Copied from original issue: dotnet/coreclr#15111_

**Comment by livarcocc** [comment]
Does this repro if you build the project directly, rather than the solution?

**Comment by lyze237** [comment]
Sorry for opening it in the wrong repo!

Yeah I get the same result when I run it on the project directly:

```
dotnet publish "Project/Projectcsproj" --output "/home/lyze/Documents/workspace/other/Solution/build/publish" --runtime win-x64 --self-contained

Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Project -> /home/lyze/Documents/workspace/other/Solution/Project/bin/Debug/netcoreapp2.0/win-x64/project.dll
  Project -> /home/lyze/Documents/workspace/other/Project/build/publish/
```

**Comment by livarcocc** [comment]
One last question, is this just a regular console application? Just trying to figure out the minimal repro that I can use to try this out. Want to make sure I won't try something simpler that may mask the existence of the bug.

**Comment by livarcocc** [comment]
What version of the CLI did you try this on?

I just tried this on both windows and OSX and it worked for me. Even had a different out from you.

The version of the CLI I used was the latest from release/15.5 branch.

**Comment by livarcocc** [comment]
Closing this one since I haven't managed to repro it and we need additional information. If this still reproes, please provide additional repro steps and we will re-activate.
