### ISSUE TITLE
dotnet run is slow in directory with many files

### ISSUE THREAD

**Issue by inossidabile** [dotnet/cli#8103]
## Steps to reproduce
Create a .net core project, put some `node_modules` in that has tons of files and directories
Move all sources to `src` subdirectory
Put in `<EnableDefaultItems>false</EnableDefaultItems>` to disable msbuild globbing
Put in `<Compile Include="src/**/*.cs"></Compile>` to actually make it compile
Run `dotnet build`
Run `dotnet run`

## Expected  behavior
Build runs fast (since `EnableDefaultItems` prevents msbuild from slowly checking `node_modules`)
Run runs fast (for the same reason as build)

## Actual behavior
Build runs fast
Run runs SUPER SLOW (30 seconds for big `package.json`)

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

The fact msbuild tries to traverse all the files by default is already super annoying and staying in the way. However it can be avoided as described in reproduction steps. This however doesn't help too much with `dotnet run` and I don't see why it wouldn't. Looks like a bug?

**Comment by inossidabile** [comment]
Now I should add that adding `<DefaultItemExcludes>node_modules\**</DefaultItemExcludes>` solves the problem. Which probably means there's some glob happening at run itself. Not sure if there's a way to rewrite it so it wouldn't check `.` recursively. It's gonna keep shooting people in leg, no?

**Comment by peterhuene** [comment]
Hi @inossidabile.  Thanks for reporting this issue!  I've reproduced the problem.  Currently the default item globs are being evaluated once for build (needed to discover files to compile, resources to embed, etc.) and a second time when evaluating the properties needed to figure out what to "run".  This second glob is entirely unnecessary and can be easily prevented.  The fix I'll have up shortly should be at least a 2x speed-up even without a change to `DefaultItemExcludes` (you will still want to exclude large directories to improve build performance, though).

**Comment by peterhuene** [comment]
The fix has been checked in and will propagate to the CLI repo once we take a new SDK version.  Thanks again for reporting this issue to us!
