### ISSUE TITLE
dotnet store is missing from --help

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8114]
## Steps to reproduce
`dotnet --help`

## Expected  behavior
Expected store command to be shown

## Actual behavior
It's missing. but you can run `dotnet store --help` and get help for the command if you know its there.

I was looking to give this as an option for people to create runtime stores on platforms that we don't support.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by mikkelbu** [comment]
@livarcocc the store command was added in #7480.

**Comment by livarcocc** [comment]
Thanks for pointing it out. Closing this issue now.
