### ISSUE TITLE
Unable to 'dotnet run' 2.0.0 app on 2.1 preview runtime

### ISSUE THREAD

**Issue by piers7** [dotnet/cli#8116]
## Steps to reproduce
- pull [dotnet Alpine images](https://github.com/dotnet/dotnet-docker-samples/tree/master/dotnetapp-prod-alpine-preview), containing 2.1 preview SDK/runtime
- use SDK container from above to build and publish console app targeting 'netcoreapp2.0' into runtime container
- start container containing published app (ie dotnet run 2.0 app on 2.1 preview runtime)

Trivial repro repo here: https://github.com/piers7/FSharpDotNetCore

## Expected behaviour
- Since target framework (2.0.0) not present, 'minor version roll forward' behaviour kicks in and uses the 2.1 preview runtime (as per [.net Core 2 Version Binding design doc](https://github.com/dotnet/designs/issues/3)).
- App runs, says Hello World etc...

## Actual behavior
App fails to run, with following error.
```
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - The .NET framework can be installed from:
      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The following versions are installed:
      2.1.0-preview1-25919-02 at [/usr/share/dotnet/shared]
```

**Has this part of the versioning design just not been implemented yet? I'm finding it very hard to find any definitive doco on this.**

Full build log here: https://travis-ci.org/piers7/FSharpDotNetCore/builds/307411662

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.2.0-preview1-007582)

Product Information:
 Version:            2.2.0-preview1-007582
 Commit SHA-1 hash:  4845efe2ea

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.0-preview1-007582/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25919-02
  Build    : 96a1025de48784825ac61e45ece24a4343e0bf01
```

**Comment by livarcocc** [comment]
This is not currently support. The runtime team is considering adding support for this in 2.1.0.

I will move this issue to core-setup.

cc @Petermarcu @steveharter

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3462
