### ISSUE TITLE
dotnet add package can't be used on private repository on Windows

### ISSUE THREAD

**Issue by NicolasDorier** [dotnet/cli#8117]
## Steps to reproduce

1. Create a feed on myget
2. 'nuget.exe setapikey <API_KEY> -Source https://www.myget.org/F/YOUR_FEED/api/v3/index.json'
3. Add https://www.myget.org/F/YOUR_FEED/api/v3/index.json to nuget config (either local or user scope)
4. Push Foo package using `dotnet nuget push  --source "https://www.myget.org/F/YOUR_FEED/api/v3/index.json"` working fine.
5. `dotnet add package Foo` Error 401

## Expected  behavior

Package Foo is added to the project.

## Actual behavior

Error 401, debugging with Fiddler indicates the API key is not used.

## Environment data

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25816-02
  Build    : c5006ff91f92e300b426eb26a9a0fa67192590b1
```

Workaround: Using Visual Studio to restore.

**Comment by enricosada** [comment]
doesnt work passing `--source` to `dotnet add`?

**Comment by NicolasDorier** [comment]
nop, same result.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6233
