### ISSUE TITLE
dotnet run shouldn't include restore output when framework is specified

### ISSUE THREAD

**Issue by svick** [dotnet/cli#8118]
## Steps to reproduce

1. `dotnet new console`
2. `dotnet run`
3. `dotnet run -f netcoreapp2.1`

## Expected  behavior

Both cases of executing `dotnet run` output only the output of the program.

## Actual behavior

Executing `dotnet run` while specifying framework also seems to output the result of running restore:

```
> dotnet run
Hello World!
> dotnet run -f netcoreapp2.1
Microsoft (R) Build Engine version 15.5.178.35674 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 21,06 ms for C:\code\tmp\hwapp\hwapp.csproj.
Hello World!
```

This is a regression from 2.0: executing `dotnet run -f` using .Net Core SDK 2.0.3 outputs only "Hello World!".

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.2.0-preview1-007582)

Product Information:
 Version:            2.2.0-preview1-007582
 Commit SHA-1 hash:  4845efe2ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007582\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25919-02
  Build    : 96a1025de48784825ac61e45ece24a4343e0bf01
```

**Comment by livarcocc** [comment]
We should set the default verbosity to quiet for restore, just like we are doing for build.

**Comment by nguerrera** [comment]
It's not exactly the same as build (default verbosity there is minimal). Also have to handle /nologo.
