### ISSUE TITLE
`dotnet run` doesn't handle ctrl-c well

### ISSUE THREAD

**Issue by stephentoub** [dotnet/cli#812]
Porting issue https://github.com/dotnet/corefx/issues/5339...

Even if the app being run has a CancelKeyPress handler, the SIGINT generated by typing ctrl-C goes to the `dotnet run` process, killing it.

**Comment by jarroda** [comment]
Any progress on this issue?

**Comment by muratg** [comment]
:eye:

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/corefx/blob/3d3c8602a484d40c7729659525946b9c97a3a003/src/System.Console/tests/CancelKeyPress.cs

@jgoshi let's make sure that any time CLI spins off a process then we wire up passthrough similarly to how it's done in the CoreFx test above.

**Comment by jgoshi** [comment]
@schellap Using the code sample provided in https://github.com/dotnet/corefx/issues/5339, I noticed that just calling dotnet exec directly I see the same problem. It appears that nothing in the app cancel handler gets written out (Console.Writeline doesn't work for some reason). I also notice that Debug.Fail("Attach") causes a crash as well (doesn't let me attach).

Any thoughts or suggestions?

**Comment by jgoshi** [comment]
@schellap Any insights?

**Comment by livarcocc** [comment]
@gkhanna79 @ramarag can you guys help out here?

**Comment by gkhanna79** [comment]
@livarcocc What specific thing are you looking for? This does not appear to be a host issue.

**Comment by Mpdreamz** [comment]
This seems pretty important to the `dotnet run` experience, has there been any update on this ticket or anywhere related?

**Comment by livarcocc** [comment]
I wish I could do a +1 on the close status change here.
