### ISSUE TITLE
dotnet binary showing the wrong version

### ISSUE THREAD

**Issue by mishra14** [dotnet/cli#8126]
## Steps to reproduce
1. download binary from [here](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.3-windows-x64-binaries)
2. run `dotnet --info`

## Expected  behavior
```
.NET Command Line Tools (2.0.3)
```

## Actual behavior
```
F:\validation\test> . "C:\Users\anmishr\Downloads\dotnet-runtime-2.0.3-win-x64\dotnet.exe" --info
.NET Command Line Tools (2.1.1)

Product Information:
 Version:            2.1.1
 Commit SHA-1 hash:  436d56176b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.1\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

I think the exe is picking up the same version on my machine irrespective of the `dotnet.exe` being executed.

**Comment by mishra14** [comment]
cc @livarcocc

**Comment by dasMulli** [comment]
Looks like [multi-level lookup](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/multilevel-sharedfx-lookup.md) discovering a globally installed SDK. Does it change when you set the environment variable `DOTNET_MULTILEVEL_LOOKUP` to `0`/`false`?

**Comment by mishra14** [comment]
That was it. Is it documented? If so I might have missed it. Else it should be.

**Comment by livarcocc** [comment]
I am not sure where you mean to document this. Do you mean docs.microsoft.com? If so, I would file an issue a dotnet/docs to add this there.

**Comment by mishra14** [comment]
Since this does not happen when i download binaries from the readme, we shouldn't need to add this to the repo readme. 
I think having a pointer on the docs page would be nice. I will move this issue there.

**Comment by mishra14** [comment]
This issue was moved to dotnet/docs#3818
