### ISSUE TITLE
Incremental `dotnet build` appears to be 300-400ms slower between release/2.1 and master

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#8130]
## Steps to reproduce
1. `build -Configuration Release` on `release/2.1` branch.  Copy that to a "baseline" folder
2. `build -Configuration Release` on `master` branch.  copy that to a "baseline-master" folder

Using the above two builds, measure the time it takes to incremental `dotnet build` a project.

## Expected  behavior
`master` should either be the same, or faster.

## Actual behavior
`master` is roughly 300-400ms slower on my machine.

From release/2.1:
```
PS F:\git\dotnet-cli-perf\scenarios\classlib\core> Measure-Command { F:\dotnet\baseline\dotnet.exe build }

TotalSeconds      : 2.0646977
```

From master:
```
PS F:\git\dotnet-cli-perf\scenarios\classlib\core> Measure-Command { F:\dotnet\baseline-master\dotnet.exe build }

TotalSeconds      : 2.3639493
```
## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.1-preview-007224)

Product Information:
 Version:            2.1.1-preview-007224
 Commit SHA-1 hash:  68c8639f09

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   F:\dotnet\baseline\sdk\2.1.1-preview-007224\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

## Notes
I compared just invoking `dotnet msbuild.dll` on the same project and I get very comparable results between the two builds.

From release/2.1:
```
PS F:\git\dotnet-cli-perf\scenarios\classlib\core> Measure-Command { F:\dotnet\baseline\dotnet.exe F:\dotnet\baseline\sdk\2.1.1-preview-007224\MSBuild.dll }

TotalSeconds      : 1.4487317
```

From master:
```
PS F:\git\dotnet-cli-perf\scenarios\classlib\core> Measure-Command { F:\dotnet\baseline-master\dotnet.exe F:\dotnet\baseline-master\sdk\2.2.0-preview1-007608\MSBuild.dll }

TotalSeconds      : 1.4202424
```

Which leads me to believe something in the CLI code itself changed to cause this degradation.

/cc @nguerrera @livarcocc @wli3

**Comment by eerhardt** [comment]
even with --no-restore, I still see 200-300ms change

Release/2.1:
```
Measure-Command { F:\dotnet\baseline\dotnet.exe build --no-restore }
TotalSeconds      : 1.6798807
```

Master:
```
Measure-Command { F:\dotnet\baseline-master\dotnet.exe build --no-restore }
TotalSeconds      : 1.9167674
```

**Comment by nguerrera** [comment]
@eerhardt I can't repro this. I thought I saw a big 2 second delta, but it seems it was just incremental restore not being no-op when switching versions.  I am getting nearly identical timings between 2.1 and master.

Would it be possible to collect an ETL trace with PerfView if you still have a repro?

**Comment by wli3** [comment]
Same on my machine

**Comment by eerhardt** [comment]
1. Are you setting `DOTNET_MULTILEVEL_LOOKUP=0` to ensure you are not getting an SDK from `Program Files`?
2. Make sure you use `Measure-Command { command }` and not what MSBuild reports for the time to build.  MSBuild only reports the time it saw to build, not the whole command (which contains other processes like the cli).

I'm not very good with PerfView yet, so I might be doing this wrong.  I'll share the .etl files offline.

**Comment by nguerrera** [comment]
Yes to both questions. I'll check the traces tomorrow.

**Comment by nguerrera** [comment]
@eerhardt Can you try invoking MSBuild.dll with the same args as dotnet build: `/m /v:m /clp:Summary /t:Build` ? 

It is possible that `/m` plays a role and  https://github.com/Microsoft/msbuild/issues/2735 is possibly related.

**Comment by nguerrera** [comment]
Hmm that msbuild  issue repros on 2.0.x so probably not that, but still to see overhead of CLI vs msbuild, we should use same args.

**Comment by nguerrera** [comment]
Managed to figure out how to repro, it's not specific to one branch or the other, but depends if logger is passed. https://github.com/Microsoft/msbuild/issues/2769
