### ISSUE TITLE
Can I reference a cli tool without publish nuget package to nuget sources when develop?

### ISSUE THREAD

**Issue by PMExtra** [dotnet/cli#8138]
Can I direct include the `dotnet-whatewer` project without publish a nuget package?

If not, can I make a `Nuget.config` for this **solution**, that add a source like '$(SourceDir)\\dotnet-whatever\\bin\\$(TargetConfig)'?

I really don't like to copy the package to the local sources dir everytime when develop.

**Comment by livarcocc** [comment]
You could make a nuget.config that adds a feed that points to the output of the project where your nupkg is being generated.

That should work.

**Comment by livarcocc** [comment]
Given that there hasn't been activity on this issue for a while, that this is not something that the tooling support in box and that there is a potential work around, I am closing the issue.

If it does not work, please comment with more details and I can re-activate the issue.
