### ISSUE TITLE
dotnet restore seems to restore references to Windows modules on Linux

### ISSUE THREAD

**Issue by chuck-mitchell** [dotnet/cli#814]
I have a project with the project.json specified at the bottom of this issue.   
Works fine on Windows.  On Linux I do the following then try to run the application.

dotnet restore
dotnet compile
bin/Debug/dnxcore50/app.exe

And get the following:

System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-errorhandling-l1-1-0.dll': The specified module could not be found.

file project.json:

{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "Microsoft.NETCore.Runtime": "1.0.1-beta-*",
        "System.IO": "4.0.11-beta-*",
        "System.IO.FileSystem.Primitives": "4.0.1-beta-*",
        "System.Console": "4.0.0-beta-*",
        "System.Runtime": "4.0.21-beta-*",
        "System.Diagnostics.Process": "4.0.0-beta-*",
        "System.Xml.XDocument": "4.0.11-beta-*",
        "System.Xml.XmlDocument": "4.0.0-*",
        "System.Xml.XPath": "4.0.0-*",
        "System.Xml.XPath.XmlDocument": "4.0.0-*",
        "System.Runtime.Extensions": "4.0.11-beta-*",
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

**Comment by davidfowl** [comment]
You should be referencing the standard library. Try making a new project with `dotnet new` (after making a folder for the application and navigating to that folder). It has the correct references.

**Comment by davidfowl** [comment]
See http://dotnet.github.io/ for more details

**Comment by chuck-mitchell** [comment]
I started out by doing that, and adding the references to other modules required by my program like XML reader, file IO, process control.   This is what "dotnet new" gives you and it is a subset of the my project.json.

{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "Microsoft.NETCore.Runtime": "1.0.1-beta-*",
        "System.IO": "4.0.11-beta-*",
        "System.Console": "4.0.0-beta-*",
        "System.Runtime": "4.0.21-beta-*"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}

**Comment by davidfowl** [comment]
Update your dotnet, that template looks old

**Comment by chuck-mitchell** [comment]
I just re-installed dotnet, "apt-get install dotnet".   "dotnet new" still gives me the same project.json.
Do you see something different?   What?

**Comment by shahid-pk** [comment]
@chuck-mitchell he means install dotnet manually by downloading the .deb from the read me page by first uninstalling the one you get from apt-get.Because The one installed with apt-get is old and will be updated with in the next few weeks.  
Or wait a week or two :smile:

**Comment by chuck-mitchell** [comment]
I am new to Linux.   I uninstalled the old dotnet.    Do I use the Software Center to install the Debian Package?   Or do I save file and install a different way?

**Comment by chuck-mitchell** [comment]
I downloaded manually from the .deb.   I can "dotnet restore" and "dotnet compile",  but when I "dotnet run"   it can't find coreclr.   Shouldn't that get installed?

**Comment by brthor** [comment]
@chuck-mitchell Ran into this as well today. 

This is the result of some versioning and name changes coming through and will be fixed shortly.

As a workaround try this
```
cd /usr/share
sudo ln -s /usr/share/dotnet-dev dotnet
```

**Comment by chuck-mitchell** [comment]
I get a little farther.    My program uses XML, but I don't see any System.Xml* assemblies in there.

**Comment by piotrpMSFT** [comment]
If you need additional dependencies that are not in the standard library, you can pick them up from https://github.com/dotnet/corefx. The [MyGet Gallery](https://www.myget.org/gallery/dotnet-core) will list specific package IDs and versions.

**Comment by piotrpMSFT** [comment]
@chuck-mitchell please reopen if this is still a CLI issue
