### ISSUE TITLE
Getting an error when running dotnet publish

### ISSUE THREAD

**Issue by garthtee** [dotnet/cli#8153]
## Steps to reproduce
ASP.NET Core using the Angular template
Node version: `9.2.0`
NPM version:  `5.5.1`
Linux Ubuntu 16.04
Running command `sudo dotnet publish`

## Expected  behavior

Publish the application to specified path.

## Actual behavior

Error **MSB3073**: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.

ERROR in /home/ubuntu/[solution_name]/[project_name]/$$_gendir/ClientApp/app/components/crypto/crypto.component.ngfactory.ts (22,42): Property 'hash' does not exist on type 'string'.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

## Other information

Using the command `sudo dotnet run` enables the application to run when I manually run npm install **BUT it gives me an error of "The view 'Index' was not found"** . The error seems to be when putting the application into production mode.

**Comment by livarcocc** [comment]
This does not look like a CLI issue. Seems like there is something wrong or missing with your node install.

cc @mlorbetske

**Comment by mlorbetske** [comment]
@stevesandersonms

**Comment by SteveSandersonMS** [comment]
Sorry, I couldn't reproduce any such issue. I installed Node 9.2.0 / NPM 5.5.1 on both Windows and Ubuntu, and for each ran the following steps using the .NET Core 2.0.2 SDK:

```
mkdir myapp
cd myapp
dotnet new angular
npm install
dotnet publish -c Release
cd bin/Release/netcoreapp2.0/publish
dotnet myapp.dll
```

... and the application was published and ran without errors. If there are more specific repro steps that produce the problem, please let us know. If not it appears this is working as expected.

**Comment by livarcocc** [comment]
Closing this issue for now since this seems to not repro and we haven't heard back with a more details set of repro steps.

If you can still repro this, please give us additional details and we will re-activate it.

**Comment by Hang91** [comment]
I got a similar issue. **dotnet run** works well, but dotnet publish has error.

In my perspective, the problem should be related with node module that doesn't belong to the default node_modules in asp.net core framework. So, when you repro this problem, it doesn't happen. @SteveSandersonMS 

Below is the error message

```
ERROR in ./$$_gendir/~/@agm/core/directives/map.ngfactory.ts
      Module parse failed: D:\project\[project name]\$$_gendir\node_modules\@agm\core\directives\map.ngfactory.ts Unexpected token (20:19)
      You may need an appropriate loader to handle this file type.
      | import * as i9 from '@agm/core/services/maps-api-loader/maps-api-loader';
      | import * as i10 from '@agm/core/directives/map';
      | const styles_AgmMap:any[] = ['.agm-map-container-inner[_ngcontent-%COMP%] {\n      width: inherit;\n      height: inherit;\n    }\n    .agm-map-content[_ngcontent-%COMP%] {\n      display:none;\n    }'];
      | export const RenderType_AgmMap:i0.RendererType2 = i0.傻crt({encapsulation:0,styles:styles_AgmMap,
      |     data:{}});
       @ ./$$_gendir/ClientApp/app/components/contact-us/map/map.component.ngfactory.ts 9:0-98
       @ ./$$_gendir/ClientApp/app/components/contact-us/contact-us.component.ngfactory.ts
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts
  Child
      Hash: 5a467178f21c19123e74
      Time: 19366ms
               Asset     Size  Chunks                    Chunk Names
      main-server.js  3.11 MB       0  [emitted]  [big]  main-server

      ERROR in ./$$_gendir/~/@agm/core/directives/map.ngfactory.ts
      Module parse failed: D:\project\[project name]\$$_gendir\node_modules\@agm\core\directives\map.ngfactory.ts Unexpected token (20:19)
      You may need an appropriate loader to handle this file type.
      | import * as i9 from '@agm/core/services/maps-api-loader/maps-api-loader';
      | import * as i10 from '@agm/core/directives/map';
      | const styles_AgmMap:any[] = ['.agm-map-container-inner[_ngcontent-%COMP%] {\n      width: inherit;\n      height: inherit;\n    }\n    .agm-map-content[_ngcontent-%COMP%] {\n      display:none;\n    }'];
      | export const RenderType_AgmMap:i0.RendererType2 = i0.傻crt({encapsulation:0,styles:styles_AgmMap,
      |     data:{}});
       @ ./$$_gendir/ClientApp/app/components/contact-us/map/map.component.ngfactory.ts 9:0-98
       @ ./$$_gendir/ClientApp/app/components/contact-us/contact-us.component.ngfactory.ts
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts
D:\project\[project name]\[project name].csproj(51,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.
```
