### ISSUE TITLE
"Could not load file or assembly 'System.Runtime, Version=4.2.0.0'"

### ISSUE THREAD

**Issue by tyteen4a03** [dotnet/cli#8159]
## Steps to reproduce
1. `dotnet new classlib --framework netcoreapp2.0`
2. `dotnet publish`
3. In PowerShell, `Import-Module` the DLL in bin/Debug/netcoreapp2.0/publish/

## Expected behavior
No errors reported

## Actual behavior

```
Import-Module : Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral,
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-Module .\Test.dll
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```
## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

(I realise that I should use `Add-Type`, but I'm using `Import-Module` because `Add-Type` makes the actual exception hard(er) to reach.)

**Comment by livarcocc** [comment]
I don't know how import module works in powershell and I don't know what are the requirements for a dll to be imported in it either.

But it seems to me like powershell is trying to "run" the dll and as such it need to either understand core, so that it can include the runtime for the library or you should have published an application (netcoreapp2.0, for instance) and not a library.

I would actually ask this question in the powershell repo.

**Comment by tyteen4a03** [comment]
I'm not sure how exactly it works either, but from my understanding importing a full (or adding a type) should make the classes in the fall present in the PowerShell workspace. Not sure which part is at fault here :)

**Comment by livarcocc** [comment]
I will close the issue here, please file one against powershell. If it turns out that we are doing something wrong, please re-activate with more details. Does this sound ok to you?

**Comment by tyteen4a03** [comment]
Sounds alright to me.
