### ISSUE TITLE
Running `dotnet restore --verbosity` (verbosity w/o value) throws an exception

### ISSUE THREAD

**Issue by jainaashish** [dotnet/cli#8160]
Originally from https://github.com/NuGet/Home/issues/6248

Running dotnet restore --verbosity crashes with ArgumentOutOfRangeException.
Yes, --verbosity should have a value, but nuget should not throw.
I'd expect something like 'verbosity value missing (q,m,d)' message.

 ---> Running in c970969c266e
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
The command '/bin/sh -c dotnet restore --verbosity' returned a non-zero code: 1

**Comment by livarcocc** [comment]
@wli3 given that it is throwing the the telemetry code path, can you take a look?

**Comment by wli3** [comment]
this is fixed in master. Closing
```
c:\work\cli\test\Microsoft.DotNet.ToolPackage.Tests>dotnet restore --verbosity
Required argument missing for option: --verbosity
Usage: dotnet restore [options]

Options:
  -h, --help                           Show help information.
  -s, --source <SOURCE>                Specifies a NuGet package source to use during the restore.
  -r, --runtime <RUNTIME_IDENTIFIER>   Target runtime to restore packages for.
  --packages <PACKAGES_DIRECTORY>      Directory to install packages in.
  --disable-parallel                   Disables restoring multiple projects in parallel.
  --configfile <FILE>                  The NuGet configuration file to use.
  --no-cache                           Do not cache packages and http requests.
  --ignore-failed-sources              Treat package source failures as warnings.
  --no-dependencies                    Set this flag to ignore project to project references and only restore the root project.
  -f, --force                          Set this flag to force all dependencies to be resolved even if the last restore was successful. This is equivalent to deleting project.assets.json.
  -v, --verbosity                      Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].


c:\work\cli\test\Microsoft.DotNet.ToolPackage.Tests>dotnet --info
.NET Command Line Tools (2.2.0-preview1-007618)

Product Information:
 Version:            2.2.0-preview1-007618
 Commit SHA-1 hash:  fc82615cc6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\work\cli\bin\2\win10-x64\dotnet\sdk\2.2.0-preview1-007618\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25924-02
  Build    : a44797cf1e972e54c0b3736ba529da75c2bc24e7
```
