### ISSUE TITLE
Question: CLI command that sets env vars xplat

### ISSUE THREAD

**Issue by guardrex** [dotnet/cli#8179]
Was it ever considered/ruled out that there should be a CLI command that sets env vars xplat in a nice, clean, consistent way?

It would make our job explaining how to set them in the docs much simpler.

**Comment by guardrex** [comment]
Closing ... It was pointed out to me that wrapping a lot of OS/platform-specific behaviors would muddy up the tooling that should only pertain to .NET Core functionality. Kind'a too bad tho ... I mean as a convenience in recalling how to set them off of one's primary OS/platform.

**Comment by livarcocc** [comment]
There is nothing preventing you from writing your own tool for it and publishing as a global tool, just saying...

**Comment by guardrex** [comment]
Yeah ... true ... but the reason I asked was that in the ASP.NET Core docs we have to explain it out across platforms/OSes (e.g., setting `ASPNETCORE_ENVIRONMENT`). It would just be sooooo much easier to have one command that's easy to remember and works xplat.

However, @thomascastiglione is correct (after sleeping on it, I agree) ... this isn't a good feature idea in spite of the convenience factor.

**Comment by dasMulli** [comment]
It would also be very complex to get right and still require users to execute a `path_helper`, `env-update`, `source` command or similar depending on the platform. (I don't even know how to do this on windows..)
