### ISSUE TITLE
Enable dotnet-resgen-<lang> support for CLI

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#819]
There is a need to allow dotnet-resgen to generate .NET Core compliant and strongly typed resource access code as part of the CLI infrastructure. The high-level principle is to ensure that there is an extensible way to generate the strongly type code for resource access as CLI is extended to support new languages. In this paradigm:
1.  Each language compiler that supports CLI will also support a dotnet-resgen-<lang> (e.g. Dotnet-resgen-cs) that will generate the language specific source code
2.  Dot net compile/build will support invoking dotnet-resgen-<lang> with the required inputs to generate the code
3.  The generated code will then be fed into the dotnet-compile pipeline where the language compiler is invoked to perform the actual app-source->IL compilation.

This will allow us to keep the model simple, support the scenario and extensible for future language support (e.g. F#).

This issue should be used to track the initial implementation for C#.

CC @piotrpMSFT @davidfowl @weshaggard @Petermarcu @jaredpar

**Comment by andschwa** [comment]
We have an internal blocked issue on this. There is a work-around in place, but it's incredibly bad.

**Comment by davidfowl** [comment]
I'm actually not a fan of generating it on build. I think tools like this should be design time only. Otherwise you have to build just to get intellisense (I know VS does this today but what a horrible thing :smile:).

**Comment by andschwa** [comment]
Man I'm fine with **any** solution that doesn't involve resgen'ing these files on Windows and sticking them in a submodule for use on Linux. You know an alternative?

**Comment by vors** [comment]
Desperately need that

**Comment by gkhanna79** [comment]
@jaredpar @VSadov What do you think we can have an initial implementation?

**Comment by davidfowl** [comment]
How see you authoring the resx file on on Windows? By hand?

**Comment by vors** [comment]
I do it by hands even on windows, it's just an xml. Easy peasy.

**Comment by davidfowl** [comment]
@vors What tools are you using on windows?

**Comment by vors** [comment]
SublimeText. But I may miss the point: do you mean creating a new one by authoring? I can see how creating a new one can be troublesome. But for editing existing resx files, you don't need a tooling support.

**Comment by andschwa** [comment]
Is there any updated status here? I'm getting murdered trying to get CLI to generate a satellite resources assembly from the set of `*.resx` files I have, and the pre-generated `.cs` bindings I had to make on Windows. CLI won't make a satellite assembly unless I rename the `.resx` files to `en-US.resx` etc.; but at that point, the C# bindings (I think) are then out of date, and so unable to find the corresponding `.resource`

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SecretAssemblyClass' threw an exception. ---> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "SecretBlah.resources" was correctly embedded or linked into assembly "SecretAssembly" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at RunspaceInit.get_OutputEncodingDescription()
```

/cc @onovotny @vors

**Comment by andschwa** [comment]
I've got `dotnet-resgen` compiling the resx files for the default culture (all that's available to me) into the assemblies correctly. As @onovotny correctly pointed out in Gitter, CLI's resgen prepends the assembly name to the resources, so I had to manually fix our pre-generated C# bindings to look in the right namespace.

While we still **really** need support to generate the C# bindings from the resx files, I was at least able to remove the pre-generated resources files, which cuts down a lot of our overhead.

I also discovered that we can support localization just fine, since we can generate satellite assemblies for the non-default cultures.

**Comment by piotrpMSFT** [comment]
`dotnet-resgen` got replaced by the `Microsoft.Net.Sdk` implementation, so closing this.

**Comment by vors** [comment]
@piotrpMSFT how can I use it? Can you point to some resource for that?

**Comment by iSazonov** [comment]
> dotnet-resgen  got replaced by the  Microsoft.Net.Sdk  implementation, so closing this.

@piotrpMSFT Please clarify how resgen can be used now in cross-platform environment?

**Comment by vors** [comment]
Polite ping. We want to remove our own resgen implementation, but don't have any pointers. https://github.com/PowerShell/PowerShell/issues/2882
