### ISSUE TITLE
Project is failing to build through the dotnet cli, however compiles fine through VS2017 Community

### ISSUE THREAD

**Issue by TedRussell23** [dotnet/cli#8202]
## Steps to reproduce
Any command that implements a build of the project within the appropriate project directory  (ex: dotnet build). Occurs with all projects.

## Expected  behavior
The project to be built successfully and the web application displayed.

## Actual behavior
Error Codes: 
error MSB3883: Unexpected exception.
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified 
(The file does exist!)

__Failed with 6 build errors. Listed below.__

C:\***\source\repos\learningNetCore\learningNetCore>dotnet build
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.0.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): er
ror MSB3883: Unexpected exception:  [C:\***\source\repos\learningNetCore\l
earningNetCore\learningNetCore.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): er
ror : System.ComponentModel.Win32Exception (0x80004005): The system cannot find
the file specified [C:\***\source\repos\learningNetCore\learningNetCore\le
arningNetCore.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): er
ror : at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo star
tInfo) [C:\***\source\repos\learningNetCore\learningNetCore\learningNetCor
e.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): er
ror : at System.Diagnostics.Process.Start() [C:\***\source\repos\learningN
etCore\learningNetCore\learningNetCore.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): er
ror : at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, Strin
g responseFileCommands, String commandLineCommands) [C:\***\source\repos\l
earningNetCore\learningNetCore\learningNetCore.csproj]
C:\Program Files\dotnet\sdk\2.0.3\Roslyn\Microsoft.CSharp.Core.targets(84,5): er
ror : at Microsoft.CodeAnalysis.BuildTasks.ManagedCompiler.ExecuteTool(String pa
thToTool, String responseFileCommands, String commandLineCommands) [C:\***
\source\repos\learningNetCore\learningNetCore\learningNetCore.csproj]

Build FAILED.

## Environment data
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

If there is an obvious solution I'll happily slap myself but can't locate specifically where the problem rests. 
I'm trying to expand on my knowledge of C# by developing an ASP.NET CORE x2 Web Application but have realized that all my projects are failing to compile through the CMD.

Any help would be greatly appreciated, Thank you!!

**Comment by livarcocc** [comment]
Please, share your csproj. Besides that, if this is a old style csproj, than it will not work in the CLI, as this is not something that we support.

Also, providing a small repro would be very helpful for us to understand the problem and fix/recommend a work around or identify it for sure as something we don't support.

**Comment by TedRussell23** [comment]
Thank you for assigning yourself to this. 

I've been following an up to date tutorial from Pluralsight which I believe to be fairly up-to-date itself having been published at the start of November. 
https://app.pluralsight.com/library/courses/aspdotnet-core-fundamentals/table-of-contents

I believe my csproj file adheres to modern standards following the format: 
<Project Sdk="Microsoft.NET.Sdk">

Here is the repo link for the project: 

https://github.com/TedRussell23/NetCoreFundamentals

**Comment by livarcocc** [comment]
Thanks for the repro repo. Taking a quick look, everything seems simple and direct. I will try building it locally and will reply back.

**Comment by TedRussell23** [comment]
Hey Livarcocc, any luck? I believe the symptoms may be down to my device specific but identifying the conflict is still a concern.

**Comment by livarcocc** [comment]
Sorry, haven't had an opportunity to try this out just yet.

**Comment by livarcocc** [comment]
By the way, I just cloned your project and it built successfully. I used the 2.1.2 SDK that is available with the latest VS 2017 updated. Can you try with that?

Also, if you can run your build with the `/bl`, it will generated a binary log (`.binlog`) file that if you could share with us, we could try and look at what is breaking the build in your case even if we can't repro it ourselves.

**Comment by livarcocc** [comment]
@TedRussell23 can you try to give us the binlog for the failed build?

**Comment by TedRussell23** [comment]
Hey, apologies for the time taken to reply as poor bandwidth has taken me most the day to update Visual Studio. 

I've managed to update the SDK to 2.1.2 and the build is now succeeding. Unfortunately, I haven't got the (.binlog) prior as the SDK was applied before I had the chance. I can however say the problem was conflicting with Version: 2.0.3.

I tried updating previous when the error first occurred but with the latest update it now seems stable once more and has resolved my issues. 

Thank you for all your help, @livarcocc ! If you would like any further logs please let me know.

I've attached the latest binlog for reference anyway.

[msbuild_binlog.zip](https://github.com/dotnet/cli/files/1557653/msbuild_binlog.zip)
