### ISSUE TITLE
Install dotnet core using npm/yarn

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8208]
@aminebizid commented on [Sun Dec 10 2017](https://github.com/dotnet/core/issues/1144)

# Feat Title

use dotnet core as NPM Package in my project

# General
My application is a set of projects with different languages (nodejs, python, dotnet core, etc.) stored on a unique git repo.
The idea is to use a unique package.json file to install all build tools via npm or yarn.
Nowaday, we need to install dotnetcore manually on dev and build machines.
It will be great if we could run such commands:
npm install @microsoft/dotnetcore@latest
this will install dotnetcore locally in my project
npm run dotnet-restore
npm run dotnet-build
npm run dotnet-test

---

@Petermarcu commented on [Mon Dec 11 2017](https://github.com/dotnet/core/issues/1144#issuecomment-350790877)

That would require someone putting .NET Core in NPM.

**Comment by livarcocc** [comment]
We actually have no plans to support additional install vectors for the CLI besides the native installers, the install scripts and the zip/tarballs we already support.

We encourage the community to support additional install experiences, like chocolatey or homebrew.
