### ISSUE TITLE
Issue when building corert

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/cli#822]
I currently cannot build corert if in the cross folder I have build  the rootfs folder. The issue is the dotnet restore command. Even without executing the restore but just querying the help it will fail. For example, in the ```home/Microsoft/corert/``` folder I'm executing the following:

```
./bin/tools/cli/bin/dotnet restore --help

Usage: dnu restore [arguments] [options]

Arguments:
  [root]  List of projects and project folders to restore. Each value can be: a path to a project.json or global.json file, or a folder to recursively search for project.json files.

Options:
  -s|--source <FEED>          A list of packages sources to use for this command
  -f|--fallbacksource <FEED>  A list of packages sources to use as a fallback
  -p|--proxy <ADDRESS>        The HTTP proxy to use when retrieving packages
  --no-cache                  Do not use local cache
  --packages                  Path to restore packages
  --ignore-failed-sources     Ignore failed remote sources if there are local packages meeting version requirements
  --quiet                     Do not show output such as HTTP request/cache information
  --parallel                  Restores in parallel when more than one project.json is discovered.
  --lock                      Creates dependencies file with locked property set to true. Overwrites file if it exists.
  --unlock                    Creates dependencies file with locked property set to false. Overwrites file if it exists.
  --runtime <RID>             List of runtime identifiers to restore for
  -?|-h|--help                Show help information
Access to the path '/home/Microsoft/corert/cross/rootfs/arm64/usr/lib/ssl/private' is denied.
```

As you can see it fails because in the cross folder the path ```/home/Microsoft/corert/cross/rootfs/arm64/usr/lib/ssl/private``` is a folder owned by root.

This is currently blocking my work on corert to cross compile on arm and arm64. 

Thanks for looking into this

**Comment by piotrpMSFT** [comment]
is `/home/Microsoft/corert/cross/rootfs/arm64/usr/lib/ssl/private` the folder you are trying to restore? How is it getting into the picture?

Is the bug that you are running restore from a parent folder of `private`, `/home/Microsoft/corert/` for example, and restore is failing because it is probing for all project.json files under that directory, failing to  probe into the directory in question?

**Comment by manu-silicon** [comment]
Yes, the folder in which I run the ```dotnet restore --help``` is /home/Microsoft/corert. But why would the ```--help``` causes a lookup in subfolder?

**Comment by manu-silicon** [comment]
Any new on this? This is blocking the default instructions for building crossplatform for coreclr and corert. To be more precise on the error, here is the output you get by running ```dotnet restore --help``` in the corert folder when in you have a file for which you do not have access to:

```
> bin/tools/cli/bin/dotnet restore --help

Usage: nuget3 restore [arguments] [options]

Arguments:
  [root]  List of projects and project folders to restore. Each value can be: a path to a project.json or global.json file, or a folder to recursively search for project.json files.

Options:
  -h|--help                       Show help information
  -s|--source <source>            Specifies a NuGet package source to use during the restore.
  --packages <packagesDirectory>  Directory to install packages in.
  --disable-parallel              Disables restoring multiple projects in parallel.
  -f|--fallbacksource <FEED>      A list of packages sources to use as a fallback.
  --runtime <RID>                 List of runtime identifiers to restore for.
  -v|--verbosity <verbosity>      The verbosity of logging to use. Allowed values: Debug, Verbose, Information, Warning, Error.
Access to the path '/Microsoft/corert/cross/rootfs/arm64/var/run/cups/certs' is denied.
```

To reproduce simply create a folder foo under ```corert/cross/foo``` which is own by root and has the following property ```dr-x--x--x```.

**Comment by manu-silicon** [comment]
This is still a blocking issue for cross platform development.

**Comment by blackdwarf** [comment]
I believe this should go to Nuget/home, since `dotnet restore` is using Nuget x-plat client to restore the dependencies.

**Comment by manu-silicon** [comment]
@blackdwarf I've linked this report to an existing issue on Nuget. Closing this now.
