### ISSUE TITLE
.net core code metrics

### ISSUE THREAD

**Issue by EncoderPtd** [dotnet/cli#8228]
As we know there's a useful function for .net projects:
Analyze -> Calculate Code Metrics
It can give out some detailed information of the project.

May i ask if it is now supported for .net core projects? I can't find it. :)
Which repository should this issue be placed in?

**Comment by livarcocc** [comment]
Is this a Code Metric supported in VS?

@jinujoseph is this supported by analyzers?

**Comment by EncoderPtd** [comment]
Yeah, it's in VS, provide calculation of code lines and some code relarion analysis.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/roslyn-analyzers#1499
