### ISSUE TITLE
dotnet run fails on Mac OS X

### ISSUE THREAD

**Issue by stefanoric** [dotnet/cli#823]
Trying to run http://dotnet.github.io/getting-started/ on MacOS, even after circumventing the problem with dotnet restore adding missing links (see https://github.com/dotnet/cli/issues/786) I get the following error:

> Could not find file '/usr/local/bin/libclihost.dylib'.

$ dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 Runtime Id:  osx.10.10-x64

**Comment by blackdwarf** [comment]
@stefanoric will take a look.

**Comment by blackdwarf** [comment]
Yup, this repros. Now, we didn't have to symlink dylib files into /usr/local/bin before. 

@anurse @brthor what changed? The fix is, of course, trivial, but would like to understand what are all the files that we need to symlink to do it in one go.

**Comment by brthor** [comment]
On osx corehost is copied to /usr/local/bin as a workaround to dotnet/coreclr#2128

Seems like this could be the root cause here.
