### ISSUE TITLE
Installation issues on Windows Server 2008 R2 SP1

### ISSUE THREAD

**Issue by gustafl** [dotnet/cli#8232]
My team is developing a Web API service using **ASP.NET Core 2.0**, and we ultimately need to host it on a **Windows Server 2008 R2 SP1** server. I'm following the instructions detailed in

https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#install-the-net-core-windows-server-hosting-bundle

After installation, `dotnet.exe` is in a useless state, which results in an HTTP 502 error when I access the site. I can get it to run from the command-line by manually adding `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.3` to the `PATH` environment variable, but it only runs without arguments. If I run `dotnet --version` or any other command, I get this messagebox:

    dotnet.exe - System Error
    The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

And then this message in the console:

    C:\>dotnet --version
    Failed to load the dll from [?O], HRESULT: 0x8007007E
    The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\2.0.3\hostfxr.dll failed
      - Installing .NET Core prerequisites might help resolve this problem.
        http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

The link leads to .NET SDK. I tried installing the SDK too (even though it shouldn't be necessary in a pure hosting environment) but had the same errors. I have also tried to restarting the machine, uninstalling and repairing the C++ redistributable and the .NET Core hosting bundle, and in the specified order.

One thing that may be useful to know is that the server doesn't have internet access, but according to the installation instructions this is fine as long as you install the C++ Redistributable before the .NET Core hosting bundle.

We'll be very thankful for any advice that helps us pinpoint the problem.

**Comment by livarcocc** [comment]
Moving this to core-setup, as at first, this seems more like a host issue.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3521
