### ISSUE TITLE
dotnet-install --channel Current doesn't work

### ISSUE THREAD

**Issue by sebastienros** [dotnet/cli#8234]
`dotnet-install.sh --channel Current` should install the SDK 2.1.2 right now, but nothing is downloaded.

**Comment by livarcocc** [comment]
@johnbeisner can you please take a look?

**Comment by johnbeisner** [comment]
Thank you for bringing this to our attention "--channel Current" will install SDK 2.1.3

Ensure that you are using the supported 'dotnet-install.sh' version: https://dot.net/v1/dotnet-install.sh
