### ISSUE TITLE
Server GC is not activated with latest runtime/sdk

### ISSUE THREAD

**Issue by sebastienros** [dotnet/cli#8237]
We migrated an app to use a very recent runtime. Since then the server GC is not active anymore.

I forced it in the csproj:

```xml
  <PropertyGroup>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>
```

And I can see this runtimeconfig file generated when the app is published:

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.0-preview1-26008-01"
    },
    "configProperties": {
      "System.GC.Server": true
    }
  }
```

The SDK is ` 2.2.0-preview1-007796`

Then at runtime we display whether the server GC is enabled or not:

```csharp
Console.WriteLine($"Server GC is currently {(GCSettings.IsServerGC ? "ENABLED" : "DISABLED")}");
```

Which displays

```
Server GC is currently DISABLED
```

**Comment by livarcocc** [comment]
This needs to be honored by the runtime, given that it is present in the runtimeconfig. I am moving this issue to core-setup.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3528
