### ISSUE TITLE
Don't put API sets into the bin folder of the dotnet CLI installation when on Win8+

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/cli#824]

**Comment by davidfowl** [comment]
How would you know not to?

**Comment by KrzysztofCwalina** [comment]
If the OS == Win and Ver > 8+, don't put them in. These api sets are not needed on Win 8+, or so I thought.

**Comment by davidfowl** [comment]
We're not going to hardcore anything like that into the cli tools. Maybe the packaging needs to change or the way we infer rids needs to change. I believe we default to win7 if no runtimes are specified

**Comment by KrzysztofCwalina** [comment]
I think it's fine to default to Win7 (when no version is specified) for the software dotnet-cli produces. Possibly I was not clear, I am talking about the bin folder of dotnet-cli itself. When I install dotnet-cli on Win8, I will never need the api sets.

**Comment by davidfowl** [comment]
> I think it's fine to default to Win7 (when no version is specified) for the software dotnet-cli produces. 

The API sets are coming from packages referenced by the application. Because we default the RID to win7 on a windows box, you end up getting the API sets in the runtime graph. 

> When I install dotnet-cli on Win8, I will never need the api sets.

You want to us to produce a dotnet CLI for win7 and win8?

/cc @ericstj

**Comment by ericstj** [comment]
Some API sets are needed on win8 and even some on win8.1.  The packages do have the granularity to distinguish what is needed where.  When resolving for the specific RID you are running on you should get the right set.

**Comment by davidfowl** [comment]
This issue is pretty ambiguous. I'll update the title but I still think it's a bad idea.

**Comment by KrzysztofCwalina** [comment]
Why is it a bad idea? In general, I think we pollute output folders too much with unnecessary api sets.

**Comment by piotrpMSFT** [comment]
Please move this issue to core-setup. That is the repo which owns CoreFx packaging.
