### ISSUE TITLE
Self-contained application for Red Hat 6 - rhel.6-x64 not supported?

### ISSUE THREAD

**Issue by AlexSanseau** [dotnet/cli#8246]
## Steps to reproduce
`dotnet new console`
`dotnet publish -c debug -r rhel.6-x64`

## Expected  behavior
Successful compilation: `rhel.6-x64` is listed as a valid RID for .NET Core 2.0 and later here: [https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md) 

## Actual behavior
error : Project is targeting runtime 'rhel.6-x64' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core. 

(please note `dotnet publish -c debug -r rhel.7-x64` is working fine)

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This error is coming from M.NC.App itself. Moving this to core-setup for comment.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3531
