### ISSUE TITLE
First run experience adds $USERPROFILE/.dotnet/tools to PATH many times on CI machines

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8247]
This is happening most often on CI where we install DOTNET to different paths and clear $USERPROFILE/.dotnet between each build.

## Steps to reproduce
Download and extract .NET Core CLI to a folder.
Run this script
```ps1
$tmpDir = "$PSScriptRoot/tmp"
$env:USERPROFILE = $tmpDir
for ($i = 0; $i -lt 100; $i++) {
    rm -r $tmpDir
    # triggers the first-run experience
    & ./dotnet.exe new console --no-restore -o $tmpDir/
}
```

## Expected  behavior
CLI should only add $USERPROFILE/.dotnet/tools to path if it is not already present

## Actual behavior
It gets add many times.

> $env:PATH = C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Git\cmd;C:\Users\namc\AppData\Local\Microsoft\WindowsApps;.;C:\Program Files\Microsoft VS Code\bin;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools;C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp\.dotnet\tools

In fact, on our CI machines, it got added so many times that the CI machine began to fail because PATH was too long.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.2.0-preview1-007813)

Product Information:
 Version:            2.2.0-preview1-007813
 Commit SHA-1 hash:  a86e59aa5d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64\sdk\2.2.0-preview1-007813\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26013-05
  Build    : 8f81238a2c5e75b2f55d49b7e23ef115d3b5743d

```

cc @ryanbrandenburg @wli3

**Comment by natemcmaster** [comment]
Site note: the adder should probably do `Path.Combine($USERPROFILE, $toolPath)` in case $USERPROFILE doesn't end in a slash.
```
C:\Users\namc\Downloads\dotnet-sdk-latest-win-x64/tmp.dotnet\tools
```

**Comment by wli3** [comment]
working on it

**Comment by wli3** [comment]
for some reason this line is not working https://github.com/dotnet/cli/blob/master/src/dotnet/ShellShim/WindowsEnvironmentPath.cs#L52

**Comment by natemcmaster** [comment]
Thanks @wli3 !
