### ISSUE TITLE
Update dotnet-install to support installing aspnetcore

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8252]
We should update dotnet-install.ps1/sh to support installing the Microsoft.AspNetCore.All shared runtime. 

Possible usage syntax:

**Option 1** 
Option with value: `-Runtime <name>`
```
dotnet-install.ps1 -Runtime dotnet
dotnet-install.ps1 -Runtime aspnetcore

dotnet-install.sh --runtime dotnet
dotnet-install.sh --runtime aspnetcore
```
For compatibility, `--shared-runtime` could just become sugar for `--runtime dotnet`

**Option 2** 
New switch: `-AspNetCoreRuntime`
```
dotnet-install.ps1 -AspNetCoreRuntime
dotnet-install.sh --aspnetcore-runtime
```

Invalid usage: mixing -SharedRuntime and -AspNetCoreRuntime. This would be an error.

@johnbeisner @livarcocc - what would be your usage preference? Is there another syntax that might be better?

cc @JunTaoLuo

**Comment by livarcocc** [comment]
cc @leecow 

I think I like option 1 above, because it is open ended. Ideally, we would come up with a design/name where simply adding new "runtimes" to the blob storage would keep the script working, instead of having to modify it every time.

**Comment by natemcmaster** [comment]
I like option 1 too as the usage doesn't have to change as new runtimes become available, even if the internal details of the script may change.

>  Ideally, we would come up with a design/name where simply adding new "runtimes" to the blob storage would keep the script working, instead of having to modify it every time.

As I've drafted this change, I've done the simplest thing first. I think this is achievable, but requires a little more design. For example, to make `-Runtime <name>` truly abstract, we'd need need to provide a way to map from `<name>` to the `shared/$Folder` so we know whether we can no-op on install or not. At the moment, my draft has hard-coded that "dotnet" = Microsoft.NETCore.App and "aspnetcore" = Microsoft.AspNetCore.All.

**Comment by johnbeisner** [comment]
What are the reasons for these changes? Why should we do this?

**Comment by natemcmaster** [comment]
We're building an ASP.NET Core shared framework. It will be installed to `shared/Microsoft.AspNetCore.All/$version`, next to Microsoft.NETCore.App. The current thinking is to make installers and zip/tar.gz files available from dotnetcli's blob store, debian feeds, etc, rather than making our own distribution feeds.

**Comment by natemcmaster** [comment]
Update. We've decided to split ASP.NET core into two layers. Microsoft.AspNetCore.App (the default experience) and .All (layers on top of .App, includes third-party extensions that we can't source-build). cref https://github.com/aspnet/Universe/issues/721

Install experience:
```
Action                                     -> The runtimes are bundled in the downloaded zip/tarball

dotnet-install.ps1 -Runtime dotnet         -> Microsoft.NETCore.App
dotnet-install.ps1 -Runtime aspnetcore     -> Microsoft.AspNetCore.App + Microsoft.NETCore.App
dotnet-install.ps1 -Runtime aspnetcore-all -> Microsoft.AspNetCore.All +  Microsoft.AspNetCore.App + Microsoft.NETCore.App
```
