### ISSUE TITLE
dotnet new giraffe fails after latest update

### ISSUE THREAD

**Issue by dustinmoris** [dotnet/cli#8257]
## Steps to reproduce

`dotnet new giraffe`

or as @cartermp demo'd in [his blog post](https://blogs.msdn.microsoft.com/dotnet/2017/09/26/build-a-web-service-with-f-and-net-core-2-0/):

`dotnet new giraffe -o GiraffeSample`

## Expected  behavior

The CLI should identify that the `giraffe` template only supports F# as language and therefore successfully create an F# Giraffe application without asking the user to specify the additional `-lang` parameter.

## Actual behavior

The command fails and shows help for `dotnet new`. This is a regression bug as it worked as expected in previous versions.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  eb1d5ee318

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1373
