### ISSUE TITLE
Problems with xUnit

### ISSUE THREAD

**Issue by christianbender** [dotnet/cli#8263]
## Steps to reproduce

I have done the following steps to install .Net Core
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.2-linux-x64-binaries

And the following steps to do a example testcase.
http://xunit.github.io/docs/getting-started-dotnet-core

## Expected  behavior

I want to run the example test.

```C#

using Xunit;

namespace MyFirstUnitTests
{
    public class Class1
    {
        [Fact]
        public void PassingTest()
        {
            Assert.Equal(4, Add(2, 2));
        }

        [Fact]
        public void FailingTest()
        {
            Assert.Equal(5, Add(2, 2));
        }

        int Add(int x, int y)
        {
            return x + y;
        }
    }
}

```
The .csproj file content:

``` xml

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

</Project>

```

## Actual behavior

![screenshot](https://user-images.githubusercontent.com/23243382/34126175-f79cd8f0-e438-11e7-9c49-af9a6a311bd5.png)

## Environment data
`dotnet --info` output:

see screeenshot (above)

**Comment by livarcocc** [comment]
Please, file this issue under the xunit/xunit repo. dotnet xunit is not a native verb of the CLI and is an extension provided through a project tool by xunit.

Having said that, I could not repro this issue on OSX.

I would try deleting the obj folder, running a `dotnet restore` and then `dotnet xunit` again.

**Comment by christianbender** [comment]
OK, thanks for your help.
