### ISSUE TITLE
Global CLI tools creates a orphaned cmd.exe process when CTRL+C is pressed to exit

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8271]
## Steps to reproduce
1. Download this sample build of dotnet-watch:
[dotnet-watch.2.1.0-preview1-t000.nupkg.zip](https://github.com/dotnet/cli/files/1573279/dotnet-watch.2.1.0-preview1-t000.nupkg.zip)
1. Create a nuget.config file (required until #8226 is fixed)
```xml
<configuration>
  <packageSources>
    <clear />
    <add key="local" value="./" />
  </packageSources>
</configuration>
```
1. Install
```
dotnet install tool dotnet-watch --version 2.1.0-preview1-t000 --configfile ./NuGet.config
```
1. Create an app and run dotnet-watch
```
dotnet new console -o app
cd app
dotnet watch run
```
1. Press CTRL+C

## Expected  behavior
This should force-quit the global CLI tool, including any parent processes.

## Actual behavior
The cmd.exe process started to launch %USERPROFILE%/.dotnet/tools/dotnet-watch.cmd is orphaned.

Before CTRL+C:
![image](https://user-images.githubusercontent.com/2696087/34179261-0b5f4950-e4bf-11e7-8714-0cc26b42e868.png)

After:
![image](https://user-images.githubusercontent.com/2696087/34179309-4338423c-e4bf-11e7-9056-d598e26c1ef5.png)

The "Terminate batch job (Y/N) question appears, but I cannot give it a response because the parent dotnet.exe process died.

![image](https://user-images.githubusercontent.com/2696087/34179279-2450b26e-e4bf-11e7-99e3-05c7b030eef9.png)

Process 22736 was orphaned

## Environment data
Shell: Happens using Command Prompt, Powershell 5, or ConEmu + cmd or powershell.

`dotnet --info` output:

```
.NET Command Line Tools (2.2.0-preview1-007796)

Product Information:
 Version:            2.2.0-preview1-007796
 Commit SHA-1 hash:  3ac579997c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17025
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\namc\.dotnet\x64\sdk\2.2.0-preview1-007796\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26008-01
  Build    : 0327161c32d0d6175914521e47d91df3db38ebb4

```

cc @wli3 @anurse

**Comment by wli3** [comment]
I need to dig more on this

**Comment by anurse** [comment]
This is why `bat`/`cmd` files are so annoying as shims on Windows :(. I don't think this is avoidable when using them, but I don't know for sure.

**Comment by natemcmaster** [comment]
Did some quick research. Doesn't look like this avoidable when using cmd.exe. All the suggestions I've seen to get around this is to invoke something other than cmd.exe.

http://h4ck3r.net/2013/07/21/suppress-terminate-batch-job/
https://superuser.com/questions/35698/how-to-supress-terminate-batch-job-y-n-confirmation

**Comment by natemcmaster** [comment]
@livarcocc @wli3 I know time is winding down on preview1, so I'd like to re-emphasize this bug causes the console to become unresponsive, even after repeated CTRL+C presses.

I can't use dotnet-watch myself as a global tool because of this. Please take a look at #8384. I don't know of any other solution than to just not use cmd.exe

![dotnet-watch2](https://user-images.githubusercontent.com/2696087/34901144-9aba69fe-f7bb-11e7-8172-f2f47319b474.gif)

cc @muratg

**Comment by muratg** [comment]
cc @danroth27

**Comment by danroth27** [comment]
cc @KathleenDollard

**Comment by KathleenDollard** [comment]
My apologies for missing this, thanks for the ping @danroth27. 

I will discuss this with @livarcocc this afternoon.

**Comment by wli3** [comment]
https://github.com/dotnet/cli/blob/4343118151b7b72a4472f159c46d0a7ea99d0ab3/src/Microsoft.DotNet.Cli.Utils/CommandResolution/WindowsExePreferredCommandSpecFactory.cs#L72

this line is the real problem. It is not .cmd file alone. It is .cmd + how CLI create "Command" (start a new .cmd process)

If you directly call "dotnet-watch" it will not create the orphan process.
