### ISSUE TITLE
Dotnet sln add using a globbing pattern isn't working within ASP.NET Core Build Docker Image

### ISSUE THREAD

**Issue by dls314** [dotnet/cli#8274]
## Steps to reproduce

Within ASP.NET Core Build Docker Image try to manipulate a solution using `dotnet sln testSln.sln add **/*Test.csproj` to add found test projects to a newly created test solution to work around https://github.com/Microsoft/vstest/issues/1129

## Expected  behavior

Can add projects using globbing within the ASP.NET Core Build Docker Image microsoft/aspnetcore-build:latest as from https://github.com/aspnet/aspnet-docker/blob/master/2.0/stretch/sdk/Dockerfile

## Actual behavior

```
[testProject] Running shell script
+ dotnet new sln -n testSln
The template "Solution File" was created successfully.
[Pipeline] sh
[testProject] Running shell script
+ dotnet sln testSln.sln add **/*Test.csproj
Project `**/*Test.csproj` does not exist.
Usage: dotnet sln <SLN_FILE> add [options] <args>

Arguments:
  <SLN_FILE>   Solution file to operate on. If not specified, the command will search the current directory for one.
  <args>       Add one or more specified projects to the solution.

Options:
  -h, --help   Show help information.
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

**Comment by livarcocc** [comment]
The CLI itself does not expand and understands globs. It relies on the shell that runs it to expand these globs. So, if it is not working for you, I would check on why your shell on docker is not expanding the globs before passing the inputs to the CLI.

**Comment by cwardcode** [comment]
Try running ```shopt -s globstar``` before using your glob. This will allow recursive globbing, introduced in bash 4+.
