### ISSUE TITLE
`dotnet test --no-build` should not restore packages before running tests

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#8275]
## Steps to reproduce

`dotnet test -f netcoreapp1.0 --no-build`

## Expected  behavior

The tests run without a restore or build beforehand.

## Actual behavior

dotnet first restores packages, then immediately runs tests without building.

Restoring without building is pointless. If I specify `--no-build`, it's because I want to run tests on a previous build.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.4-preview-007239)

Product Information:
 Version:            2.1.4-preview-007239
 Commit SHA-1 hash:  8b4773e1d3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4-preview-007239\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

**Comment by livarcocc** [comment]
We may have fixed this in master already. In any case, we will take a look.

**Comment by peterhuene** [comment]
@livarcocc that's correct; `master` already has the fix to make `--no-build` imply `--no-restore`.

**Comment by AArnott** [comment]
Thanks.
