### ISSUE TITLE
XXX depends on Microsoft.NETCore.App (>= 2.1.0-preview1-26015-04) but Microsoft.NETCore.App 2.1.0-preview1-26015-04 was not found

### ISSUE THREAD

**Issue by ssougnez** [dotnet/cli#8280]
## Steps to reproduce

- Install the latest bit from here: https://github.com/dotnet/cli#installers-and-binaries
- Have a ".csproj" that looks like this one:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="1.50.2" />
    <PackageReference Include="Dapper.Mapper" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview1-27884" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="2.1.0-preview1-27884" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
  </ItemGroup>
</Project>
```

- Execute `dotnet restore`
- Execute `dotnet run`

## Expected  behavior

Everything should be restored and the application should run...

## Actual behavior

When I run the `dotnet restore`, I get the following warning:

> C:\Users\...\RobotWar.csproj : warning NU1603: RobotWar depends on Microsoft.NETCore.App (>= 2.1.0-preview1-26015-04) but Microsoft.NETCore.App 2.1.0-preview1-26015-04 was not found. An approximate best match of Microsoft.NETCore.App 2.1.0-preview1-26016-05 was resolved.

Which is pretty weird. Indeed, when I go in "C:\Program Files\dotnet\shared\Microsoft.NETCore.App", I see two folders:

- 2.0.4
- 2.1.0-preview1-26015-04

Apparently, "2.1.0-preview1-26015-04" **is** installed, but if I understand correctly the message above, it says that it's not and also says that it could resolve the version "2.1.0-preview1-26016-05" which is not installed... Note that I checked my PATH variable (via $env:PATH in PowerShell) and "C:\Program Files\dotnet" is in it.

If I execute the `dotnet run`, besides the aforementioned message, I also get:

> Using launch settings from C:\Users\...\RobotWar\Properties\launchSettings.json...
> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.AspNetCore.All', version '2.1.0-preview1-27884' was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Program Files\dotnet\
>   - The .NET framework can be installed from:
>       https://aka.ms/dotnet-download-runtime
>   - The .NET framework and SDK can be installed from:
>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

I tried to install the package located on the page proposed by the message (and I think that's how I got the "2.0.4" folder) but, as you can imagine, this didn't solve anything. 

Moreover, you'll see in the "Environment data" section that `dotnet --info` shows correctly that the installed version is "2.1.0-preview1-26015-04".

I'm using the "aspnetcore-dev" feed ("https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json").

I also noticed that in Visual Studio 2017 15.5.2, when I check "Dependencies > NuGet" in the solution explorer, the meta-package "Microsoft.AspNetCore.All" has a small warning sign on it. I tried to uninstall it and reinstall it via the GUI, the installation went fine but all the rest remains (the warning message and the warning icon in the solution explorer).

For this issue, I tried to install Visual Studio 2017 preview (15.6) and now, I can see the NuGet packages but all the other issue remain.

Finally, in this Visual Studio, I check the path where NuGet DLL are loaded and I got "C:\Users\ssoug\.nuget\packages\microsoft.aspnetcore.all\2.1.0-preview1-27884". When I go there and open the "lib\netcoreapp2.1" folder, I get a file called "_._" which is empty. I'd say it's not normal but I'm not 100% sure :-D However, "C:\Users\ssoug\.nuget\packages\microsoft.aspnetcore\2.1.0-preview1-27884\lib\netstandard2.0" contains a "Microsoft.AspNetCore.dll".

## Environment data
.NET Command Line Tools (2.2.0-preview1-007846)

Product Information:
 Version:            2.2.0-preview1-007846
 Commit SHA-1 hash:  15725d7cac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007846\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26015-04
  Build    : 8485f1ee2416d900d57074e2ae21f287b0c2c3b2

**Comment by livarcocc** [comment]
Do you need to use the 2.2.0 SDK? It uses packages that are not available in nuget.org and because of that, you need to add a nuget feed to your feed list: `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`.

You may need other feeds as well, depending on what ASP.NET is bringing in, but this feed will contain the Microsoft.NETCore.App package in the version above.

The runtime installed in your box is not used for compilation, only for execution, which is why you will need the feed.

**Comment by ssougnez** [comment]
I'm not sure whether I need the 2.2.0 SDK or not. The thing is, few months ago, it was the only way to use SignalR (server and client) as it was only avaialble for aspnet-core 2.1. Therefore, from time to time, I updated the version of my package meaning:

- Update the SDK to the latest bit via the link in the OP
- Update the NuGet & NPM version based on the version in the ci-dev myget feed.
- dotnet restore

It used to work but recently, the ci-dev started to ask me to enter credentials (don't know why), so I switched to the "dev" feed. To be honest, I'm a bit lost in all these versions... The SDK, the runtime, the NuGet packages, it's not really easy to understand it all...

I just want to be able to use SignalR for ASP.NET Core, which requires ASP.NET Core 2.1. Maybe the way I'm doing it is not correct.

By the way, as you can see in the screen below, I added the "dev" feed to the ones of Visual Studio.

![image](https://user-images.githubusercontent.com/10199821/34275342-25819a92-e69d-11e7-8e8e-d2ebc52d80be.png)

**Comment by livarcocc** [comment]
Please, add the feed `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json` as well and give it a try.

**Comment by ssougnez** [comment]
Here is what I did:

- Added the line "<add key="aspnet" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"/>" in my "NuGet.config" file
- Added the feed "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" in the Visual Studio feed lists.
- `dotnet clean`
- `dotnet restore`
- `dotnet run`

The good news is that I no longer see the yellow warning message saying that "2.1.0-preview1-26015-04" could not be found (event though I don't understand why as nothing changed in "C:\Program Files\dotnet\shared\Microsoft.NETCore.App").

The bad news is that the `dotnet run` still outputs the message saying "The specified framework 'Microsoft.AspNetCore.All', version '2.1.0-preview1-27884' was not found." (the `dotnet` command stops after this message so I can't even test the app).

**Comment by livarcocc** [comment]
Like I said, we don't compile against the runtime that you have under `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`. We still need to restore the packages and then use them for compilation. Which is why you got the yellow warning.

As for the failure, ASP.NET has moved to implementing their own shared framework and it seems to me like the packages that you are referencing are already using that, even though it has not been added to the SDK yet.

At this point, I would move this issue to the signalr repo and see if they can provide you with either a version of the package for you to use that does not depend on this new framework or a link to install the asp.net framework.

**Comment by ssougnez** [comment]
I understand but I’m afraid that they will just ping pong me back to here... indeed, the issue here is not really SignalR but more the fact that it seems that I’m unable to use .Net Core 2.1 on my machine.

I’ll ask them and we’ll see.

Thanks for your help

**Comment by livarcocc** [comment]
No, the error you are getting above is not because of .NET Core 2.1 per si. You have the 2.1 net core runtime installed. The error above is indicating that you are missing the asp.net runtime. Which is a new thing we are adding in the 2.1 timeframe.

If you build a 2.1 console app, it will run just fine.

**Comment by natemcmaster** [comment]
> The specified framework 'Microsoft.AspNetCore.All', version '2.1.0-preview1-27884' was not found.

We haven't started publishing the shared runtime that matches the Microsoft.AspNetCore.All package yet. Once #8252 is fixed, you would be able to install the ASP.NET Core shared framework using dotnet-install.ps1/sh.

In the meantime, you can workaround by setting this in your project.

```xml
  <PropertyGroup>
    <MicrosoftNETPlatformLibrary>Microsoft.NETCore.App</MicrosoftNETPlatformLibrary>
  </PropertyGroup>
```
This overrides this: 
https://github.com/aspnet/Universe/blob/143872b52614e741cf7555bf8dfd91be2f1fbcf7/src/Microsoft.AspNetCore.All/build/netcoreapp2.1/Microsoft.AspNetCore.All.props#L3

cc @JunTaoLuo

**Comment by ssougnez** [comment]
Ah aaah, well done :-D

Indeed, it fixed my issue. Wow, I think I will stop upgrading packages until the official release of 2.1 is available ^^ 

Thanks a lot for your support

**Comment by livarcocc** [comment]
Glad it is sorted out. Closing this issue now.
