### ISSUE TITLE
.NET Core SDK doesn't run in globalization invariant mode

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#8290]
I wasn't able to get the .NET Core SDK to run in globalization invariant mode with Alpine.

See https://github.com/dotnet/dotnet-docker-nightly/pull/508

To repro, remove the last three lines of the Dockerfile.

Sample you can use for testing is at https://github.com/dotnet/dotnet-docker-samples/tree/alpine/dotnetapp-prod

**Comment by nguerrera** [comment]
This is going to be fun to investigate.

**Comment by richlander** [comment]
This issue may not be specific to Alpine. That may or may not be clear. Alpine is just the place I found it.

**Comment by nguerrera** [comment]
Duplicate of https://github.com/dotnet/corefx/issues/28021

**Comment by nguerrera** [comment]
This should be fixed now (see corefx duplicate).
