### ISSUE TITLE
dotnet publish does not work with full name parameters (output, runtime)

### ISSUE THREAD

**Issue by AymanGaafar** [dotnet/cli#8298]
## Steps to reproduce
Publishing a project with at least one of `--output` or `--runtime` parameters as fullname.

## Expected  behavior
Publish to work normally like:
`dotnet publish PROJECT_DIR -o PUBLISH_DIR -r linux-x64`

## Actual behavior
When publishing like this

`dotnet publish PROJECT_DIR --output PUBLISH_DIR -r linux-x64`
OR
`dotnet publish PROJECT_DIR -o PUBLISH_DIR --runtime linux-x64`
OR
`dotnet publish PROJECT_DIR --output PUBLISH_DIR --runtime linux-x64`

throws an exception when invoking `dotnet` on the main dll:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Aborted
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

```

**Comment by livarcocc** [comment]
This is working on the latest version of the CLI (2.1.300-preview1).

If this is still reproing for you, just comment and we can re-activate.

By they way, I tried:

`dotnet publish --output PUBLISH_DIR -r linux-x64`
`dotnet publish -o PUBLISH_DIR --runtime linux-x64`
`dotnet publish --output PUBLISH_DIR --runtime linux-x64`
