### ISSUE TITLE
dotnet publish leaves dangling dangling process with open handles

### ISSUE THREAD

**Issue by nategraf** [dotnet/cli#8299]
Between December 19 at 7:32am and December 20 at 7:32 am the [size-on-disk benchmark job](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/sizeondisk_x64/) began to fail.

After some investigation I found that after the main benchmark code finishes it fails to delete the temporary directory because there are open handles to files within. The open handles are held by an orphan `dotnet` process spawned from the `dotnet publish` command.

## Steps to reproduce
0. Confirm there are no `dotnet` processes running
1. Install dotnet with the powershell script using channel 'master'
2. Create a new console application with `dotnet new console`
3. Publish this app with `dotnet publish`
4. Check for any running dotnet processes

Or download and run the [reduced version of the failing benchmark](https://git.io/vbdxI)

## Expected  behavior
No `dotnet` processes should be running and the benchmark should cleanup and exit successfully

## Actual behavior
An orphan `dotnet` process with open handles is running and the benchmark will fail

## Environment data
dotnet version is latest master

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64

**Comment by livarcocc** [comment]
This is likely the vbcscompiler server, that was added two weeks ago in our master branch.

cc @jaredpar. I would expect the vbcscompiler to shutdown after one hour. Is that not the case for core? Should we move this bug to roslyn if the "time to live" is not being respected?

**Comment by nategraf** [comment]
I does shutdown after a certain about of time. Why does the vbcscompiler server start up and outlive the command line process for for this operation?

**Comment by nategraf** [comment]
Is there a way to turn this feature off?

**Comment by livarcocc** [comment]
This is a similar process as exists in the full framework version of msbuild and the compiler. It outlives dotnet so that we can benefit from perf improvements around start-up time.

You can set UseSharedCompilation=true MSBuild property to turn this off and not use the VBCSCompiler server.

If this does not work for you or if there is anything else you need, please comment and I can re-activate this issue.
