### ISSUE TITLE
Add analyzer support

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#83]
We need to put some code in the ProjectModel that surfaces analyzers from the lock file. This also crosses over to development dependencies but that can be solved separately. We can likely port that code from the existing NuGet msbuild task

/cc @agocke

**Comment by NikolayIT** [comment]
@davidfowl Any information when analyzers will be supported?

**Comment by boxofnotgoodery** [comment]
Would really love to see this happen,
Code analysis and unit tests are both two tools I leverage to ensure my code is production ready, or at least qa ready :)

**Comment by blackdwarf** [comment]
@jaredpar @agocke which milestone can we expect something like this to happen in?

**Comment by giggio** [comment]
Yes, RC2! \o/
