### ISSUE TITLE
dotnet build resx error

### ISSUE THREAD

**Issue by tfsjohan** [dotnet/cli#8307]
When building a project from the command line on OSX using the dotnet build tools I get this error:

`error MSB3103: Invalid Resx file. Length cannot be less than zero.`

The resx files are not empty and they do work when building on Visual Studio 2017 on Windows. I can also build on Mac using Mono version of MSBuild without errors, but then the resources doesn't get build.

## Expected  behavior
Successful build and compiled resources.

## Actual behavior
Error MSB3103: Invalid Resx file.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

**Comment by livarcocc** [comment]
@rainersigwald this seems like a msbuild problem. Should we move it there?

**Comment by rainersigwald** [comment]
@livarcocc Yes, moved this to https://github.com/Microsoft/msbuild/issues/2838 (but don't have permission to close this.

@tfsjohan I have some followup questions over there when you get a chance.

**Comment by livarcocc** [comment]
Thanks @rainersigwald
