### ISSUE TITLE
dotnet-install.sh shouldn't require tput

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#8311]
## Steps to reproduce
On the base Alpine3.6 image, run `dotnet-install.sh`.

## Expected  behavior
The script should install `dotnet` as usual, just like on any other Linux distro.

## Actual behavior

`/opt/code/scripts/obtain/dotnet-install.sh: line 27: tput: command not found`

## Environment data
`dotnet --info` output: N/A

## Notes

From my inspection, we are only using `tput` to change the console color during the install.  Printing colors on the console shouldn't be required in order to install use dotnet-install.sh.

This is going to mean that anyone who either a) wants to build the dotnet/cli repo or b) wants to use dotnet-install.sh is going to have to install this utility on their machine.

See https://github.com/dotnet/cli/pull/8227#discussion_r156692376

**Comment by kasper3** [comment]
@eerhardt, can you try adding ncurses package? Run [`pkg add ncurses`](https://pkgs.alpinelinux.org/package/edge/main/x86/ncurses) and you will get tput in Alpine.

**Comment by eerhardt** [comment]
> can you try adding ncurses package?

Yes, that works around the issue, but it shouldn't be required.  Users shouldn't need to add that package in order to install dotnet.

**Comment by kasper3** [comment]
That's right, this https://github.com/dotnet/cli/blob/5044132/scripts/obtain/dotnet-install.sh#L25 can be changed to:

```diff
- if [ -t 1 || command -v tput ]; then
+ if [ -t 1 ] || [ command -v tput ]; then
```
