### ISSUE TITLE
dotnet publish and the ASPNETCORE_ENVIRONMENT 

### ISSUE THREAD

**Issue by dougwittner** [dotnet/cli#8321]
I bet this has been covered but I am stumped as to what the best way to publish to multiple environments. It appears I can update ASPNETCORE_ENVIRONMENT  in the web.config which is the best solution for me, not requiring server env changes or requirements. But there is not transformation support. IS there another best practice way to do this?

I have multiple build configurations and publish configurations... and 1 profile per environment which works great locally. 

## Steps to reproduce
dotnet publish 

## Expected  behavior
expecting the web.config to transform the ASPNETCORE_ENVIRONMENT

## Actual behavior
dotnet publish recreated the web.config 

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#280
