### ISSUE TITLE
dotnet build fails - searches wrong location

### ISSUE THREAD

**Issue by stiano** [dotnet/cli#8331]
## Steps to reproduce
dotnet new classlib
dotnet build

## Expected  behavior
Build as normal

## Actual behavior
It seems like cli looks for files directly on c:\ , insted of the project directory: C:\Perforce\DNVX\DemoSln\

dotnet build:
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

CSC : error CS2001: Source file 'c:\Class1.cs' could not be found. [C:\Perforce\DNVX\DemoSln\DemoSln.csproj]
CSC : error CS2001: Source file 'c:\obj\Debug\netstandard2.0\DemoSln.AssemblyInfo.cs' could not be found. [C:\Perforce\DNVX\DemoSln\DemoSln.csproj]

Build FAILED.

CSC : error CS2001: Source file 'c:\Class1.cs' could not be found. [C:\Perforce\DNVX\DemoSln\DemoSln.csproj]
CSC : error CS2001: Source file 'c:\obj\Debug\netstandard2.0\DemoSln.AssemblyInfo.cs' could not be found. [C:\Perforce\DNVX\DemoSln\DemoSln.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:04.89

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by livarcocc** [comment]
can you run `dotnet build /bl`which will generate a `msbuild.binlog` and then share that binlog with us?

**Comment by stiano** [comment]
thanks for reply, here is the msbuild.binlog.

[msbuild.zip](https://github.com/dotnet/cli/files/1610823/msbuild.zip)

**Comment by livarcocc** [comment]
@rainersigwald @cdmihai can you guys take a look? Is this globbing?

**Comment by rainersigwald** [comment]
The compiler command line looks ok

```
C:\Program Files\dotnet\sdk\2.0.3\Roslyn\RunCsc.cmd /noconfig
...
/deterministic+ Class1.cs "C:\Users\stola\AppData\Local\Temp\.NETStandard,Version=v2.0.AssemblyAttributes.cs" obj\Debug\netstandard2.0\DemoSln.AssemblyInfo.cs /warnaserror+:NU1605
```

assuming the current working directory is the project directory, which it should be . . . but maybe isn't?

@stiano Do you have anything in your registry at `HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun` or `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\AutoRun`? I suspect [a gotcha](https://blogs.msdn.microsoft.com/oldnewthing/20071121-00/?p=24433/) in running `cmd.exe`.

**Comment by stiano** [comment]
Yes, and when removing them, it all worked as expected. Thanks a lot guys!

**Comment by livarcocc** [comment]
thanks @rainersigwald. I have no idea how you did this one out. There is probably a story of staring at the monitor at some point in time for you to know this.

@stiano glad this solved your issue.
