### ISSUE TITLE
Haw to define Major.Minor.Patch version variable in tfs 2017 Build Job  and  increment it after each Build 

### ISSUE THREAD

**Issue by BoubakrEchieb** [dotnet/cli#8332]
i'm using TFS 2017 for CI, Version defined in csproj file as below should be auto-incremented after evry TFS build, I have defined  Major, Minor and Patch viables in TFS Build job, But to do incrementention after each build, the Major.Minor.Patch version will be showed in the footer of my application. 

    <PropertyGroup>
        <Major Condition=" '$(Major)' == '' ">1</Major>
        <Minor Condition=" '$(Minor)' == '' ">0</Minor>
        <Patch Condition=" '$(Patch)' == '' ">0</Patch>
        <VersionPrefix>$(Major).$(Minor).$(Patch)</VersionPrefix>
    </PropertyGroup>

**Comment by livarcocc** [comment]
The MSBuild change looks correct, however, how these properties are defined in TFS (if at all) are not really controlled by the CLI.

I believe TFS defines a BuildNumber, not sure if it defines Major, Minor, Patch in incremental order for you.
