### ISSUE TITLE
Error running CLI on Linux when installed to "$HOME/dotnet"

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#8337]
## Summary
It seems the problem only repros when:
 
1. dotnet is installed at `$HOME/dotnet`
2. The command is run as `dotnet` which loads the file from `$PATH`
3. The command is run from `$HOME`, not any other directory

## Steps to reproduce
1. Ubuntu 16.04 LTS
2. Install dotnet-sdk-2.1.3 using apt-get (https://www.microsoft.com/net/learn/get-started/linuxubuntu)
3. `mkdir ~/dotnet`
4. `cd ~/dotnet`
5. `wget https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.0-preview1-007840/dotnet-sdk-2.2.0-preview1-007840-linux-x64.tar.gz`
6. `tar -zxvf dotnet-sdk-2.2.0-preview1-007840-linux-x64.tar.gz`
7. `cd ~`
8. `nano .profile`
A. Add “$HOME/dotnet” to front of path
9. `source .profile`
10. `which dotnet`
A. Verify the path is `/home/username/dotnet/dotnet`
11. `dotnet -?`
A. Expected: Shows help
B. Actual: `Did you mean to run dotnet SDK commands? Please install dotnet SDK from: http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409`
12. `~/dotnet/dotnet -?`
A. Works fine
13. `mkdir foo`
14. `cd foo`
15. `dotnet -?`
A. Works fine
16. `mv ~/dotnet ~/dotnet-foo`
17. `nano .profile`
A. Change `$HOME/dotnet` to `$HOME/dotnet-foo`
18. `source .profile`
19. `which dotnet`
A. Verify the path is `/home/username/dotnet-foo/dotnet`
20. `dotnet -?`
A. Works fine

**Comment by steveharter** [comment]
This is a core-setup issue; working on fix

**Comment by livarcocc** [comment]
Moving it to core-setup then.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3580
