### ISSUE TITLE
Creating a local CLI tool package

### ISSUE THREAD

**Issue by firelizzard18** [dotnet/cli#8342]
I have a project, `dotnet-mycmd`. I want to use this as a tool in another project via `DotNetCliToolReference`. I've exported a nupkg to a folder and added that folder to the target project's `RestoreSources`. I then added the tool reference and attempted to `dotnet restore`.

This succeeds when the project is named something like `mycmd` but fails in all sorts of ways when its named `dotnet-mycmd`. And of course it doesn't work as a tool when the name isn't prefixed with `dotnet-`.

In my reproduction ([test.zip](https://github.com/dotnet/cli/files/1609495/test.zip)):
  * A is a netstandard lib
  * A2 is a netstandard lib dependent on A
  * B/dotnet-mycmd is a netcoreapp dependent on A and A2
  * C is a netstandard lib dependent on A with a tool reference to B/dotnet-mycmd

Currently, I'm getting these errors (in my reproduction attempt):
```
% dotnet restore C
  Restoring packages for /Users/me/Source/test/C/C.csproj...
  Restore completed in 10.04 ms for /Users/me/Source/test/A/A.csproj.
  Restore completed in 22.78 ms for /Users/me/Source/test/C/C.csproj.
/Users/me/Source/test/C/C.csproj : error NU1101: Unable to find package dotnet-mycmd. No packages exist with this id in source(s): nuget.org
/usr/local/share/dotnet/sdk/2.1.3/NuGet.targets(103,5): error : Value cannot be null. [/Users/me/Source/test/C/C.csproj]
/usr/local/share/dotnet/sdk/2.1.3/NuGet.targets(103,5): error : Parameter name: path [/Users/me/Source/test/C/C.csproj]
```

These are the errors I was getting before I tried to reproduce the issue, translated into the projects I created for the reproduction:
```
/Users/me/Source/test/C/C.csproj : error NU1101: Unable to find package A. No packages exist with this id in source(s): nuget.org
/Users/me/Source/test/C/C.csproj : error NU1101: Unable to find package A2. No packages exist with this id in source(s): nuget.org
```

**Comment by emgarten** [comment]
This issue was moved to NuGet/Home#6402
