### ISSUE TITLE
The dotnet install command help text is missing descriptions of options

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#8367]
The `dotnet install` command help text is missing descriptions of its various options (although they do show up when you use `dotnet install` incorrectly):

```
C:\Users\daroth\Desktop\test>dotnet install --help
Usage: dotnet install [options] [command]

Options:
  -h, --help   Show help information.

Commands:
  tool <packageId>   Install tool

C:\Users\daroth\Desktop\test>dotnet install tool dotnet-dev-certs -v 2.1.0-preview1-28042
Unrecognized command or argument '-v'
Unrecognized command or argument '2.1.0-preview1-28042'
Usage: dotnet install tool [options] <packageId>

Arguments:
  <packageId>   Package Id in NuGet

Options:
  --version         Version of the package in NuGet
  --configfile      NuGet configuration file
  -f, --framework   Target framework to publish for. The target framework has to be specified in the project file.
  -h, --help        Show help information.

C:\Users\daroth\Desktop\test>dotnet --info
.NET Command Line Tools (2.2.0-preview1-007925)

Product Information:
 Version:            2.2.0-preview1-007925
 Commit SHA-1 hash:  ff4299241c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007925\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26110-02
  Build    : 77152705cd56e7d89f52585959ec3559d91084c4
```

**Comment by wli3** [comment]
I am not sure it is a bug. That is the design of parser only show help of one layer. Like `dotnet add -h` will only show `package and reference`. And also, it is invalid to type dotnet install --version (you need `tool` here).

Maybe we should show 2 layer in some case like dotnet install tool. But that change should be in [parser](https://github.com/dotnet/CliCommandLineParser). And we should config in CLI showHelp(layer: 2)

**Comment by peterhuene** [comment]
Agreed that this does not appear to be a bug; the `install` command has no options other than `--help`, which is being displayed along with the sub-command `tool` (which has its own distinct options).

I don't think we should display sub-command options from the parent command as that would be confusing.

**Comment by wli3** [comment]
@danroth27 please reopen if you think the design of showing one level of option need more consideration
