### ISSUE TITLE
Cannot run global tool after installing it, must open new command prompt

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#8368]
After I have successfully installed a global tool I am not able to run it without opening a new command prompt:

```
C:\Users\daroth\Desktop\test>dotnet install tool dotnet-dev-certs --version 2.1.0-preview1-28051

The installation succeeded. If there is no other instruction. You can type the following command in shell directly to invoke: dotnet-dev-certs

C:\Users\daroth\Desktop\test>dotnet dev-certs -h
No executable found matching command "dotnet-dev-certs"

C:\Users\daroth\Desktop\test>dotnet-dev-certs -h
'dotnet-dev-certs' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\daroth\Desktop\test>dotnet dev-certs
No executable found matching command "dotnet-dev-certs"
```

**Comment by wli3** [comment]
Did you just installed SDK? It requires a restart of command prompt in order for PATH in registry to work. However there should be an error message to tell the user to restart.

**Comment by livarcocc** [comment]
@danroth27 can you give us the info @wli3 is asking for above?

**Comment by wli3** [comment]
We could either add [these windows specific code](https://stackoverflow.com/questions/171588/is-there-a-command-to-refresh-environment-variables-from-the-command-prompt-in-w)

or add instruction to reopen cmd

**Comment by danroth27** [comment]
Yes, opening a new command prompt works, but I don't think that's the user experience we want. You should be able to install a global tool and use it immediately. That's how npm global tools work, right?

/cc @KathleenDollard

**Comment by livarcocc** [comment]
This is only a problem for when dotnet is first installed and I believe is a similar behavior as npm actually. It is not a matter of I ran install or not. It is a matter of I just got this CLI.

**Comment by danroth27** [comment]
Oh, so this is a one time thing?

**Comment by wli3** [comment]
one time per user

**Comment by danroth27** [comment]
Ah, ok. I think that's fine then.

**Comment by KathleenDollard** [comment]
Will can you put the new text in this issue? I think it would tidy up this issue prior to closing it. 

We updated that "If there are no further instructions" and I thought it was a but more clear in the install that the restart was needed.

**Comment by wli3** [comment]
I haven't put the change in yet. According to https://github.com/dotnet/cli/issues/8369

We want to use the following

```
The installation succeeded and you can run the tool by typing: dotnet-dev-certs
(If you the tool is not found, try restarting your shell)
```

**Comment by KathleenDollard** [comment]
Cool, that will the new text be in Preview 1?

**Comment by wli3** [comment]
Yes, that's what we decided so far. Do we want to add more to it according to this thread?

**Comment by wli3** [comment]
@KathleenDollard Above is not in preview 1. What in preview 1 is issue description's version.

**Comment by dasMulli** [comment]
could something be done to test if the directory that the shim was written to is already on the current `PATH`?

**Comment by wli3** [comment]
@dasMulli Something similar is added. However, I think it is not working properly due to, in Windows it cannot distinguish between what will be available(in registry) and what is available in the session

**Comment by peterblazejewicz** [comment]
With official preview release (macOS):

```sh
dotnet install tool dotnet-dev-certs -g --version 2.1.0-preview1-final
Since you just installed the .NET Core SDK, you will need to reopen terminal before running the tool you installed.
The installation succeeded. If there are no further instructions, you can type the following command in shell directly to invoke: dotnet-dev-certs
```
and:
```sh
dotnet-dev-certs
command not found: dotnet-dev-certs
```

**Comment by StefH** [comment]
I've the same error when using `dotnet tool install --global ***` in the new **Azure Pipelines** flow.

My command is like:
``` sh
dotnet tool install --global dotnet-sonarscanner
```

This command outputs this:
``` sh
Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.
You can invoke the tool using the following command: dotnet-sonarscanner
Tool 'dotnet-sonarscanner' (version '4.3.1') was successfully installed.
```

And the next step will fail (running the above command in the same step or a different script step make no difference)
``` sh
No executable found matching command "dotnet-sonarscanner"
```

**Comment by KathleenDollard** [comment]
@StefH 

If you just installed the SDK, the path to your global tools you need to restart the shell for the path to global tools to be recognized. 

Are you installing and running via a script? (where this would be quite problematic)

If so @wli3 can he set the path explicitly in the script to avoid the problem?

**Comment by wli3** [comment]
You could add `%UserProfile%/.dotnet/tools/` to your path before running the command.
Although, in script, we recommend using `--too-path` with explicit location instead of install it globally. And call the tool with full path.

**Comment by StefH** [comment]
Hi @dasMulli ; keep seeing you everywhere...
Hi @wli3 : thanks for your solution.

For now I just solved it by providing the full path to the executable, so:
```
%USERPROFILE%\.dotnet\tools\dotnet-sonarscanner
```

See also linked issue https://github.com/Microsoft/vsts-tasks/issues/8291

**Comment by ignatandrei** [comment]
Some problem here . However, in old VSTS pipelines it works. It Azure DevOps it does not.

**Comment by cosmoKenney** [comment]
@ignatandrei Same here. VSTS Pipeline stopped working -- unable to find the tool installed in a previous step.

**Comment by ignatandrei** [comment]
@cosmoKenney  :  After reporting as a bug (https://developercommunity.visualstudio.com/content/problem/340067/install-global-tool.html?childToView=343864#comment-343864 ) , found an workaround until the bug is solved:

See the https://github.com/ignatandrei/stankins/blob/master/azure-pipelines.yml 

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.300'
  inputs:
    version: 2.1.300

- script: |
   dotnet tool install  --tool-path . dotnetsay
   .\dotnetsay 
  displayName: 'Command Line Script'

**Comment by cosmoKenney** [comment]
@ignatandrei I really don't understand the yaml. Did you switch to a CMD task?

**Comment by ignatandrei** [comment]
Yes.

**Comment by bishal-pdMSFT** [comment]
@wli3 in an automated scenario like Azure pipelines(previously VSTS) this is a big problem. There is no way to open a new shell to mitigate this. Also, just adding a better message does not solve this problem. Why does dotnet tool require this extra manual step? Npm works just fine. At the minimum, `dotnet tool install -g` should be adding the location to PATH.
Can we re-activate this issue?

**Comment by cosmoKenney** [comment]
+1 on reopening this issue. Using the CMD step [workaround] to install the tool using --tool-path doesn't work if you install a tool to some arbitrary folder. Then if you use it in a following step in the pipeline, you still don't have access to the tool. If there were a variable you could use with a path in both steps that would help mitigate the issue.

**Comment by wli3** [comment]
I created a new thread for Azure DevOps CI issue https://github.com/dotnet/cli/issues/10059

**Comment by wli3** [comment]
> Does this limitation apply in Linux as well, or are the environment variables available as soon as the tool is installed without having to restart the shell?

This applies to Linux if you install it via package manager like apt-get. You need to re log in your shell in order to _source_ the script we put in `/etc/profile.d` which will append to `$PATH`.

**Comment by dbsanfte** [comment]
Sorry, it's a bit unclear whether the original complaint was ever addressed.

Does dotnet now set the PATH correctly for globally installed tools in the original scenario, or must we add `--tool-path .tools` to get it to work?

**Comment by KathleenDollard** [comment]
@dbsanfte The problem with needing to restart the shell is in how some shell/OS's work. That waste original issue. This only needs to be done once, after installing the .NET SDK. 

I'm not sure that's the issue you're referring to.

**Comment by kwaazaar** [comment]
What if I cannot restart? I'm using a Dockerfile to build an AZP agent...

**Comment by dbsanfte** [comment]
I am facing the same issue: I'm in a Docker image.

It should be trivial to update the PATH of the current shell session on addition to system one.

**Comment by wli3** [comment]
> It should be trivial to update the PATH of the current shell session in addition to the system one.

This is actually not trivial by the design of Unix. PATH like any other environment variable is stored in current shell session. There is no API available to change PATH in an application for the current session.

However, if you are in Docker you could run  `export PATH="$PATH:$HOME/.dotnet/tools"` to make it available. Or relogin bash shell session by command

**Comment by dbsanfte** [comment]
I'm fine with sourcing the .bashrc again if that's where you're updating my PATH.

You'll appreciate, however, that this still sucks. Dotnet should just know to look there anyways, it shouldn't need to rely on the PATH at all.

**Comment by KathleenDollard** [comment]
@dbsanfte We'd love to have a better experience on this and remain open to ideas. But we're also committed to playing nice on all the platforms we support.

**Comment by wli3** [comment]
@dbsanfte we did not add the export to bashrc. it is in `/etc/profile.d/dotnet-cli-tools-bin-path.sh`

**Comment by dbsanfte** [comment]
Can you make a symbolic link in /usr/local/bin? That's in most everyone's PATH, definitely the default PATH in Ubuntu at any rate.

helm, kubectl, tiller, etc put their symbolic links there.

**Comment by wli3** [comment]
That would require `sudo` for every dotnet tool install command. Since /usr/local/bin is not writable by current user

**Comment by dbsanfte** [comment]
For a global install (presumably for all users), sudo would seem to be acceptable.
