### ISSUE TITLE
Run-Build.sh/ps1 does not behave correctly when passing in a target 

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/cli#8375]
Related: https://github.com/dotnet/cli/issues/8358

When passing in a 'target' on the command line from Build.sh/cmd; the target is attempted on the first pass call to "dotnet msbuild build.proj". This causes unpredictable results.

**Comment by livarcocc** [comment]
Let's update the title on the original issue and use that one to track the fix. We can close this one as a dup of the original one.
