### ISSUE TITLE
Incorrect error message when package name is missing for install tool command

### ISSUE THREAD

**Issue by peterhuene** [dotnet/cli#8381]
## Steps to reproduce
```
$ dotnet install tool
```

## Expected  behavior
An error message is printed about the missing tool package name.

## Actual behavior
```
$ dotnet install tool
packageId
Usage: dotnet install tool [options] <packageId>

Arguments:
  <packageId>   Package Id in NuGet

Options:
  --version           Version of the package in NuGet
  --configfile        NuGet configuration file
  -f, --framework     Target framework to publish for. The target framework has to be specified in the project file.
  -h, --help          Show help information.
```
## Environment data
```
$ dotnet --info
.NET Command Line Tools (2.2.0-preview1-007928)

Product Information:
 Version:            2.2.0-preview1-007928
 Commit SHA-1 hash:  0d6f8f9d59

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /Users/peterhuene/src/cli/bin/2/osx-x64/dotnet/sdk/2.2.0-preview1-007928/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26110-02
  Build    : 77152705cd56e7d89f52585959ec3559d91084c4
```

**Comment by peterhuene** [comment]
@wli3 I'd be happy to tackle #8367 at the same time and just do a pass through the command's.

**Comment by wli3** [comment]
I think there is a config problem on the parser, it just says packageId in red.

But note, all the help text other than top level `dotnet --help`, is generated by parser. And the parser should have the knowledge of "it is invalid command, and to make it valid, you need <packageid>" already.

**Comment by peterhuene** [comment]
Looks like it is just missing passing an error message to `ExactlyOneArgument`, like `add package` does it.  Trivial fix, although I'd like to get the `LocalizableStrings` in place before fixing this and the option text.
