### ISSUE TITLE
Easy to parse feed to make automated updating chocolatey packages easier

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8386]
@riezebosch commented on [Thu Jan 11 2018](https://github.com/dotnet/core/issues/1214)

To make maintaining the [chocolatey-packages](https://github.com/jberezanski/dotnetcore-chocolateypackages/) more convenient I would like a stable endpoint to check for latest version of releases with download url's.

I tried to parse to the [download page](https://www.microsoft.com/net/download/windows) and the [releases page](https://github.com/dotnet/core/releases) on github but there are to much hops to go through.

For example I also maintain the [docker-for-windows package](https://github.com/riezebosch/BoxstarterPackages/tree/master/docker-for-windows) and there I found a nice [feed](https://download.docker.com/win/stable/appcast.xml) with version number and download url that was easy to parse and thereby easy to auto update.

**Comment by Petermarcu** [comment]
@MichaelSimons @richlander don't we have something we use for our docker images? Could we make a feed that is public as well to help others get the right things?

**Comment by livarcocc** [comment]
I think @leecow  has a mapping for this in a json file. I believe the runtime is included, if not, should it be? I believe so.

**Comment by leecow** [comment]
https://github.com/dotnet/core/blob/master/release-notes/releases.json

**Comment by riezebosch** [comment]
You guys rock! 🎉

**Comment by martincostello** [comment]
Nice. Two things though:

1.  Some of the download URLs for the SDK use HTTP instead of HTTPS. Is that a mistake?
1. Is it possible to extend this to include the URL and SHA for the Windows Server Hosting MSI as well?

**Comment by leecow** [comment]
@martincostello - updated to https, definitely a mistake. Added Windows Hosting exe and will make additions to the SHA file in a bit.

@riezebosch - Which zips are you looking at? I think I'm seeing each version. As far as the names, yes, that's safe for those particular files though they are now in json so you don't have to guess ;-)

**Comment by martincostello** [comment]
@leecow Nice 😎

**Comment by livarcocc** [comment]
It seems like this issue is ready to be closed. I will go ahead and do it. If that is not the case, please comment and I can re-activate it.

**Comment by riezebosch** [comment]
@leecow 
> @riezebosch - Which zips are you looking at? I think I'm seeing each version. As far as the names, yes, that's safe for those particular files though they are now in json so you don't have to guess ;-)

Look at [this part](https://github.com/dotnetcore-chocolatey/dotnetcore-chocolateypackages/blob/master/dotnetcore-runtime.install/Update.ps1#L20-L21) of the Update.ps1 I created. The `dotnet-runtime-2.0.5-win-x86.zip`, `dotnet-runtime-2.0.5-win-x86.zip`, `dotnet-sdk-2.1.4-win-x86.zip` and `dotnet-sdk-2.1.4-win-x64.zip` are present but the `xxx.exe` counterparts are not.

**Comment by leecow** [comment]
@riezebosch - added exe's to the file and updated field names which reference exe's.
