### ISSUE TITLE
Remove -f myget workaround in dotnet-restore

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#839]
When https://github.com/dotnet/cli/pull/837 goes in, a workaround for #615 will be in place.

This workaround adds "-f https://myget.org/f/dotnet-core" to any restore which is done, so prevent needing to drop a NuGet.config during dotnet new.

Whey stdlib is pushed to Nuget.org we should remove this workaround.

**Comment by davidfowl** [comment]
That change looks like a bad idea. Dropping a nuget.config is much less magic. And you can turn it off. Baking a switch into code like that will cause all sorts of problems.

**Comment by brthor** [comment]
Agreed it's less magic, but what would break?

@ericstj and @piotrpMSFT were not big fans of dropping the NuGet.config, so trying to find a cleaner way.

**Comment by ericstj** [comment]
@davidfowl how did DNX do this in pre-release?  Did it have a Nuget.config in the bin dir?

**Comment by piotrpMSFT** [comment]
We want to avoid folks checking in a NuGet.config that points them to a pre-release feed. This is a workaround for a point-in-time problem since we don't have bits on nuget.org that folks can use yet. I'm also curious, however, about the DNX experience.

**Comment by brthor** [comment]
This never went in.
