### ISSUE TITLE
When running `dotnet test` on a solution, silently ignore non-test projects

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#8393]
When iterating on a project, it's not uncommon to want to run all the unit tests across the solution quickly and with a single command. Running `dotnet test` at the solution level gets close to that, but needs some refinement. In particular, it's a little too grumpy about being told to test projects with no unit tests in them.

## Steps to reproduce
1. `dotnet new sln`
2. `dotnet new classlib --name Library`
3. `dotnet sln add Library/Library.csproj`
4. `dotnet new xunit --name Tests`
5. `dotnet sln add Tests/Tests.csproj`
6. `dotnet test`

## Expected  behavior
Test Projects are built and the tests are executed. Ideally, only the test projects (and their dependencies) would be built, so only build failures in those projects and test failures would be displayed. I'd also be OK with all projects being built, but again, only build failures and test failures should be displayed. A notice about ignoring a project because it has no tests is OK but it should be subtle and certainly not in **red angry text** :).

I think the ideal process here would be to check each project in the solution for tests, find the test projects, and just build those. Then run their tests.

## Actual behavior

The behavior isn't far off, but the `No test is available ...` line is red and angry at me. Why is it so angry? I'm sorry `dotnet test`, I didn't mean to make you angry ;).

```
Build started, please wait...
Build started, please wait...
Build completed.

Test run for /Users/anurse/Code/anurse/silenttestrepro/Library/bin/Debug/netstandard2.0/Library.dll(.NETStandard,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20171211-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in /Users/anurse/Code/anurse/silenttestrepro/Library/bin/Debug/netstandard2.0/Library.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

Test Run Aborted.
Build completed.

Test run for /Users/anurse/Code/anurse/silenttestrepro/Tests/bin/Debug/netcoreapp2.1/Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20171211-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.9000360]   Discovering: Tests
[xUnit.net 00:00:01.0090030]   Discovered:  Tests
[xUnit.net 00:00:01.0250180]   Starting:    Tests
[xUnit.net 00:00:01.2628950]   Finished:    Tests

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.7807 Seconds
```

## Environment data
`dotnet --info` output:

```
zsh› dotnet --info
.NET Command Line Tools (2.2.0-preview1-007796)

Product Information:
 Version:            2.2.0-preview1-007796
 Commit SHA-1 hash:  3ac579997c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/anurse/.dotnet/sdk/2.2.0-preview1-007796/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-25616-02
  Build    : 8aa34a95bad481e1b5e4c8286e5cb2d7cb6ed943
```

**Comment by dasMulli** [comment]
Duplicate of https://github.com/Microsoft/vstest/issues/1129 ?

**Comment by anurse** [comment]
Sounds like it. Wasn't sure where this belonged since it hangs off of `dotnet`
