### ISSUE TITLE
CLI didn't take proper environment

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8398]
@KhaledSMQ commented on [Fri Jan 12 2018](https://github.com/dotnet/core/issues/1215)

# Issue Title
on windows 10 32bit  .NET Core SDK 2.1.2  i am setting the env to Local 
using set ASPNETCORE_ENVIRONMENT=Local and the settings on windows environment variables for system and user both i set the key to Local but still taking Development `MyProject.Host` in my `launchSettings.json`  dotnet core must to take `MyProject.Host.Local` profile
 
launchSettings.json file
```
{
	"iisSettings": {
		"windowsAuthentication": false,
		"anonymousAuthentication": true,
		"iisExpress": {
			"applicationUrl": "http://localhost:5000/",
			"sslPort": 0
		}
	},
	"profiles": {
		"IIS Express": {
			"commandName": "IISExpress",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			}
		},
		"MyProject.Host": {
			"commandName": "Project",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			},
			"applicationUrl": "http://localhost:5000/"
		},
		"MyProject.Host.Local": {  ` <------- targeted profile  `
			"commandName": "Project",
			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Local"
			},
			"applicationUrl": "http://localhost:5000/"
		}
	}
}
```

**Comment by livarcocc** [comment]
@mlorbetske can you take a initial look, since you put the launchSettings.json code in the CLI originaly?

**Comment by mlorbetske** [comment]
Could you try using `dotnet run {your project} --launch-profile MyProject.Host.Local` to see if that helps please?

**Comment by KhaledSMQ** [comment]
@mlorbetske 
I think it's a bug i tried a lot, I have format my laptop and install fresh OS 64bit with same configurations it works fine without change any settings.
any way thank you.

**Comment by livarcocc** [comment]
@KhaledSMQ does this mean this is now working for you? And you don't really know how you got to the broken situation?

if that's the case, I will go ahead and close this issue since it is now working for you and we don't have a repro for the issue.

**Comment by KhaledSMQ** [comment]
@livarcocc 
Thank you for reply,
Yes it's working right now very fine, I face this issue when I was having 32bit windows 10 but after installing fresh 64 bit it's works with same configurations even I didn't change any single line. maybe it's an os problem or something was install on the laptop. I am not sure what was the problem.

**Comment by livarcocc** [comment]
All right. Thanks for letting us know. I will go ahead and close the issue for now, but keep an eye out for similar issues.
