### ISSUE TITLE
BUG LINUX/OSX Error when Building solutions with csproj/fsproj properties due to Permissions

### ISSUE THREAD

**Issue by QuantApp** [dotnet/cli#8411]
## Steps to reproduce
Create a solution with multiple projects. Ensure that one of the base (non-dependent) projects needs a property set in the csproj during building. This will break the building process for the entire solution. C# projects get warnings while F# projects errors.

Sample error:
/usr/share/dotnet/sdk/2.1.4/FSharp/Microsoft.FSharp.Targets(263,9): error MSB6003: The specified task executable "RunFsc.cmd" could not be run. Permission denied [/MYPROJECT.fsproj]

**Comment by livarcocc** [comment]
Can you provide us with a small repro or share the csproj/fsproj that seems to cause the issue? I don't quite follow the repro steps you mentioned above.

What do you mean by `projects needs a property set in the csproj`?

**Comment by livarcocc** [comment]
Closing this issue for the lack of information. If you can provide us with additional information on how to repro this issue, we can re-activate.

**Comment by QuantApp** [comment]
Hello,

The solution I found to this problem was to NOT pass compiler variables to sub projects if compiling under non-windows

Assume a solution structure with 2 projects A and B where A is dependent on B. For example project A is an executable and project B is a library. Also assume that project B requires a variable during compilation. Call this variable OS for the sake of this example.

For example: 
Windows (Works)
dotnet build /p:OS=win
is captured during compilation of project B

Linux / MacOS (NO WORK)
dotnet build /p:OS=Mac
is not captured and it creates the weird error you posted above.

Work around:
Don't compile MacOS solutions where sub-projects require variables passed through compilation.

Hope this helps
