### ISSUE TITLE
Requirement for CLI tool authors to list Microsoft.NETCore.Platforms in nuspec

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8418]
According to current design spec, global CLI tool authors must define the `<dependencies>` section in spec as follows:

```xml
      <dependencies>
        <dependency id="Microsoft.NETCore.Platforms" version="2.0.1" />
      </dependencies>
```

Is this really necessary? From my initial tests, portable .NET Core app tools restore just fine without this in the nuspec. 

IIUC this is only required for rid-specific tools, not portable ones. RID-restores require it because dotnet-install-tool is implemented as a dotnet-restore. Could dotnet-install-tool add Microsoft.NETCore.Platforms to the generated csproj it uses to call dotnet-restore?

cc @wli3 @livarcocc 

cref https://github.com/aspnet/DotNetTools/issues/383

**Comment by wli3** [comment]
Try to list problems on the road: If we want to add Platforms dependency in temp project instead of nupkg. As in today's master. Temp project only allow 1 package reference (to prevent the state of restore multiple tool with one temp project) and package type need to be `DotnetTool` type (to prevent dotnet install tool -g a-library-package-id, although we don't have a good error message return back). This check is in nuget. If we allow platform, we have to find another way to solve the previous 2 problems

**Comment by natemcmaster** [comment]
By the way, this is the error message users will see if they try to install a package that doesn't have M.NC.Platforms in the dependency graph.

```
Install failed. Failed to download package:
NuGet returned:

Failed to restore package.
WorkingDirectory:
Arguments: restore C:\Users\namc\AppData\Local\Temp\xxvuzjml.r2u\tsyuxbkj.kwm.csproj --source .\artifacts\build\ --runtime win10-x64 /p:BaseIntermediateOutputPath=\"C:\Users\namc\.dotnet\tools\dotnet-watch\2.1.0-preview1-t000\"
Output:   Restoring packages for C:\Users\namc\AppData\Local\Temp\xxvuzjml.r2u\tsyuxbkj.kwm.csproj...
  Installing dotnet-watch 2.1.0-preview1-t000.
C:\Users\namc\AppData\Local\Temp\xxvuzjml.r2u\tsyuxbkj.kwm.csproj : error NU1202: Package dotnet-watch 2.1.0-preview1-t000 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / win10-x64. Package dotnet-watch 2.1.0-preview1-t000 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
  Restore failed in 263.85 ms for C:\Users\namc\AppData\Local\Temp\xxvuzjml.r2u\tsyuxbkj.kwm.csproj.
```

**Comment by wli3** [comment]
let me see if directly adding runtime.json to temp project can work. Still sounds hacky. 

need some help cc @nkolev92

**Comment by nkolev92** [comment]
The platforms package is the only package that knows of the " win10-x64" => "any" mapping. As far as NuGet is concerned, we don't do anything fancy there, 

@wli3, Adding it to the project won't work.

**Comment by wli3** [comment]
@nkolev92 hmm any way to squeeze this dependency in temp project restore time? So the producer don't have to add it all the time?

**Comment by nkolev92** [comment]
@wli3 
That would break all the other restrictions.

**Comment by nkolev92** [comment]
You can always consider auto-including the platforms package during pack.

**Comment by wli3** [comment]
> You can always consider auto-including the platforms package during pack.

That's already done tho.

It think there is problems on both side. But no blocking problem

The version of 'Microsoft.NETCore.Platforms` is hard. In a sense, it is fine with any version. But now we need to find the version that packaged with the tool. It is hard for offline scenario. dotnet-watch need to match the Platforms version in offline cache. Also if a package is packed with old runtime.json, it cannot run on newer RID, like osx-10.13.

During pack we had a hard time to find the right version of Platforms. It needs to be the version associated with `Microsoft.NETCore.App` or it will be downgrade error (note: this is producer, making a console app and SDK is adding the implicit Platforms package). But that version if very hard to compute, since SDK know what `Microsoft.NETCore.App` depends on after restore, but there is a packagereference need to be add in before restore.

**Comment by natemcmaster** [comment]
It seems like we're incurring unneeded complexity here. Could we alter NuGet to do a "portable" restore as a workaround for now and only look at `tools/$txm/`. The RID piece in `tools/$txm/$rid/` only applies to support for "native" tools, such as a tool implemented in C++ or as a .NET Core standalone app. These aren't even supported in the current implementation -- only portable .NET Core apps are allowed. 

If someone _really_ needed a RID-specific tool, they could workaround by adding a portable .NET Core app that basically acts as a facade; the facade finds the right binary for the current OS and does Process.Start to forward arguments into the new process.

**Comment by wli3** [comment]
This issue will come again at next major version. And tools can only support one of them even the author take action. Or 2 different packageid

The author in this case can multi targeting, the filtering will find the right asset and use it.

https://github.com/xunit/xunit/issues/1573

**Comment by wli3** [comment]
> the facade finds the right binary for the current OS

We probably will end up doing the same thing as nuget doing today. Use platforms package and select the right asset.

**Comment by natemcmaster** [comment]
> The producer in this case can multi targeting, 

A producer still could do this. For this particular issue, I'm not suggesting we change that. I'm only suggesting NuGet doesn't need to do a RID restore. Just use `tools/$txm/`. NuGet has built-in knowledge of txm's, not RIDs.

**Comment by natemcmaster** [comment]
> This issue will come again at next major version. 

By the way, no matter what you decide on how to use NuGet, RIDs and TFMs, you will still run in the next major version problem. The only way to solve this one is to support (1) detecting required .NET Core runtimes, (2) installing them from dotnet-install, or (3) changing .NET Core 3+ to automatically roll-forward apps build for .NET Core < 3. Target frameworks don't solve (1) (TFM != runtime), and (2) isn't something you can solve with NuGet unless we started publishing the .NET Core runtime itself as a package.

**Comment by dasMulli** [comment]
> You can always consider auto-including the platforms package during pack.

The hard part about that is that tools would need to be re-packed again for every new addition to the platforms package even if there is no change to the tool.
E.g. when `osx.10.14` comes out and https://github.com/dotnet/cli/issues/8436 happens again.

**Comment by dasMulli** [comment]
Would it make sense to have a NuGet feature to provide a fallback RID graph as part of its installation?

That may be helpful for other scenarios as well, e.g. runtime assets in packages consumed by classic .net framework projects.

**Comment by wli3** [comment]
Here is the plan to remove the dependency to `Microsoft.NETCore.Platforms`

- [ ] Pass "any" as RID to nuget during restore of temp project, so there is no need for `Microsoft.NETCore.Platforms`. However that also blocked all RID specific scenarios
- [ ] Remove implicit package reference during pack in SDK
- [ ] Until https://github.com/NuGet/Home/issues/6559 is finished
- [ ] Add `Microsoft.NETCore.Platforms` to temp project restore

**Comment by wli3** [comment]
cc @KathleenDollard @dotnet/dotnet-cli

**Comment by KathleenDollard** [comment]
This is the plan. 

There is a plan for RID specific packages in the future: Will, if you can maintain notes on what we plan on that it would be great, probably a separate issue, which will also call out that they are not supported in this first version. 

For clarity, the user is not expected to be aware of the temp project, so no action will be needed on this issue by either consumer or producer (we removed the need for the producer to include `Microsoft.NETCore.Platforms`)

**Comment by wli3** [comment]
@KathleenDollard created https://github.com/dotnet/cli/issues/8618 for 2.1.3xx
https://github.com/dotnet/cli/issues/8617 is for future.

I am closing this issue in favor of 8618
