### ISSUE TITLE
Cannot install tool on macOS high sierra(temp fix merged)

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#8436]
## Steps to reproduce

* Using `2.2.0-preview1-008000` on high sierra
* Create a console app targeting `netcoreapp2.1` and set `PackAsTool` property to `true`. (`sayhi.csproj`)
* Create a nuget.config file to add `dotnet-core` feed and a local folder for the produced nupkg file.
* Use `dotnet pack` to create a nupkg file from the tool app.
* Use `dotnet install tool -g --configfile $(pwd)/nuget.config sayhi`

## Expected  behavior

Installs the tool

## Actual behavior

Error that the package is not compatible with `netcoreapp2.1 (.NETCoreApp,Version=v2.1) / osx.10.13-x64` but only supports `netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any`:

```
$ dotnet install tool -g --configfile $(pwd)/nuget.config sayhi
Install failed. Failed to download package:
NuGet returned:

Failed to restore package. 
WorkingDirectory: 
Arguments: restore /var/folders/b1/p_sdf_v932sfdvr0ccxt2gd80000gn/T/4zstq4rl.ya5/jaj1vnsm.wf1.csproj --configfile /Users/martin/tmp/toolstest/sayhi/nuget.config --runtime osx.10.13-x64 /p:BaseIntermediateOutputPath=\"/Users/martin/.dotnet/tools/sayhi/tn02uk3w.ykb\"
Output:   Restoring packages for /var/folders/b1/p_sdf_v932sfdvr0ccxt2gd80000gn/T/4zstq4rl.ya5/jaj1vnsm.wf1.csproj...
  Installing Microsoft.NETCore.Platforms 2.1.0-preview1-26116-01.
  Installing sayhi 1.0.0.
/var/folders/b1/p_sdf_v932sfdvr0ccxt2gd80000gn/T/4zstq4rl.ya5/jaj1vnsm.wf1.csproj : error NU1202: Package sayhi 1.0.0 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / osx.10.13-x64. Package sayhi 1.0.0 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
  Restore failed in 1.26 sec for /var/folders/b1/p_sdf_v932sfdvr0ccxt2gd80000gn/T/4zstq4rl.ya5/jaj1vnsm.wf1.csproj.
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.2.0-preview1-008000)

Product Information:
 Version:            2.2.0-preview1-008000
 Commit SHA-1 hash:  02a98d4e63

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.0-preview1-008000/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9
```

cc @wli3

**Comment by wli3** [comment]
runtime.json don't have "osx.10.13-x64" yet

https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json

send PR to support osx.10.13-x64 or do not pass the that specific os version on mac

**Comment by wli3** [comment]
Giving time. I think I should add a extra map from most specific RID to just osx-x64 when it is macOS and pass it to temp project https://github.com/dotnet/cli/blob/master/src/dotnet/commands/dotnet-install/dotnet-install-tool/ProjectRestorer.cs#L41

**Comment by dasMulli** [comment]
Yes I didn't use `10.13` anywhere, it's just the defaults when running the tooling on that version of macOS.

**Comment by wli3** [comment]
The temp fix is merged, keep it on at least until runtime.json is updated

**Comment by wli3** [comment]
This problem will be resolved after https://github.com/dotnet/cli/issues/8617 is done
