### ISSUE TITLE
dotnet pack does not set version suffix if a custom version is provided alongside.

### ISSUE THREAD

**Issue by ditux** [dotnet/cli#8440]
## Expected  behavior
/p:PackageVersion="0.0.0.0097" --version-suffix "alpha"

The above command should set version suffix

## Actual behavior

/p:PackageVersion="0.0.0.0097" --version-suffix "alpha"

The above command does not work. It does not set the suffix. Suffix is only set when no PackageVersion is provided.

## Environment data
`dotnet --info` output:

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by dasMulli** [comment]
PackageVersion overrides the VersionPrefix/VersionSuffix combination (and even Version).

You can pass `/p:VersionPrefix=0.0.0.0097` instead (requires that the csproj file does not contain `Version`)
