### ISSUE TITLE
Adding local packages with no internet connection fails

### ISSUE THREAD

**Issue by RassulYunussov** [dotnet/cli#8451]
The problem is in the addition of local package to project using command 
`dotnet add package` with `-s` flag, where I should provide a local package path. Also I wonder, why not to use a name of local package here instead of full path?
I create a class library and then pack it and copy to local packages folder, to use it later. 
When I don't have live internet connection I can't do it. When I restore the connection everything goes well and I can successfully add package. 

## Steps to reproduce
1. Create new project:
`dotnet new console -o cons`
`cd cons`
`dotnet add package lec2lib -s /PATH_TO_PACKAGES`

## Expected  behavior
The package should be added and .csproj file modified. 

## Actual behavior

`error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Couldn't resolve host name`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6477
