### ISSUE TITLE
Separate package and publish scripts

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#846]
Today the package scripts call the publish scripts after generating the packages.
https://github.com/dotnet/cli/blob/master/scripts/package/package-zip.ps1#L42
https://github.com/dotnet/cli/blob/master/packaging/windows/generatemsi.ps1#L156

Publishing of all the packages must be done as the last part of the build. Otherwise we may end up in a scenario where zips are published but MSI generation fails. This will lead to uneven latest builds between zips and MSIs.

**Comment by Sridhar-MS** [comment]
As a part of fixing this also move MSI version [generation](https://github.com/dotnet/cli/blob/master/scripts/build/generate-version.ps1#L17) to [generatemsi.ps1](https://github.com/dotnet/cli/blob/master/packaging/windows/generatemsi.ps1).

**Comment by brthor** [comment]
:+1: 
This would be a good improvement IMO. Following the codepaths from each package to the publishing of that package can be somewhat confusing.
