### ISSUE TITLE
How does --additional-deps work along with --additionalprobingpath

### ISSUE THREAD

**Issue by hvanbakel** [dotnet/cli#8467]
First of all, what I'm trying to do here is to run an assembly as a container to be reused by multiple other assemblies. So I would like to run something like
> dotnet MyHost.dll MyImplementation.dll

where MyHost.dll is reused and sets up the runtime for MyImplementation.dll (which contains webapi controllers). In order for that to work, the dotnet cli will need to understand what it needs to load. I've been reading [this](http://www.natemcmaster.com/blog/2017/12/21/netcore-primitives/) and I'm able to get it to work by manually crafting the deps.json file. However, I'm trying to use the existing tooling for this and I was under the impression that the --addtional-deps and --additionalprobingpath were to be used for this. However, I cannot get this to work.
[NetCoreLoaderTest.zip](https://github.com/dotnet/cli/files/1661603/NetCoreLoaderTest.zip)

## Steps to reproduce
Use the added solution. 
What I'm trying to find out is what the difference is between running with --additional-deps and having a project reference.

## Expected  behavior
Running with additional-deps is equivalent to merging the deps.json files and/or running with a project reference. I would expect it to be the equivalent of 'merging' the deps.json files together.

## Actual behavior
Having a project reference, building the solution and starting it (in the bin/debug/netcoreapp2.0 folder) using
> dotnet NetCoreLoaderTest.dll

works

Removing the project reference and running it like this (again in the bin/debug/netcoreapp2.0 folder):
> dotnet --additional-deps ..\..\..\..\Dep
endentProject\bin\Debug\netcoreapp2.0\DependentProject.deps.json --additionalprobingpath ..\..\..\..\DependentProject\bi
n\Debug\netcoreapp2.0\ .\NetCoreLoaderTest.dll

does not work. It crashes with:
>Processing TPA for deps entry [DependentProject, 1.0.0, DependentProject.dll]
  Considering entry [DependentProject/1.0.0/DependentProject.dll] and probe dir [C:\Program Files\dotnet\shared\Microsof
t.NETCore.App\2.0.5]
    Skipping... probe in deps json failed
    Skipping... not found in probe dir 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.5'
  Considering entry [DependentProject/1.0.0/DependentProject.dll] and probe dir []
    Local path query did not exist D:\code\sandbox\NetCoreLoaderTest\NetCoreLoaderTest\bin\Debug\netcoreapp2.0\Dependent
Project.dll
    Skipping... probe in deps dir 'D:\code\sandbox\NetCoreLoaderTest\NetCoreLoaderTest\bin\Debug\netcoreapp2.0\' failed
    Skipping... not found in probe dir ''
  Considering entry [DependentProject/1.0.0/DependentProject.dll] and probe dir [C:\Program Files\dotnet\store\x64\netco
reapp2.0]
    Relative path query did not exist C:\Program Files\dotnet\store\x64\netcoreapp2.0\DependentProject\1.0.0\DependentPr
oject.dll
    Skipping... not found in probe dir 'C:\Program Files\dotnet\store\x64\netcoreapp2.0'
  **Considering entry [DependentProject/1.0.0/DependentProject.dll] and probe dir [D:\code\sandbox\NetCoreLoaderTest\Depen
dentProject\bin\Debug\netcoreapp2.0\]
    Relative path query did not exist D:\code\sandbox\NetCoreLoaderTest\DependentProject\bin\Debug\netcoreapp2.0\Depende
ntProject\1.0.0\DependentProject.dll
    Skipping... not found in probe dir** 'D:\code\sandbox\NetCoreLoaderTest\DependentProject\bin\Debug\netcoreapp2.0\'
  Considering entry [DependentProject/1.0.0/DependentProject.dll] and probe dir [C:\Users\jvanbakel\.nuget\packages]
    Relative path query did not exist C:\Users\jvanbakel\.nuget\packages\DependentProject\1.0.0\DependentProject.dll
    Skipping... not found in probe dir 'C:\Users\jvanbakel\.nuget\packages'
  Considering entry [DependentProject/1.0.0/DependentProject.dll] and probe dir [C:\Program Files\dotnet\sdk\NuGetFallba
ckFolder]
    Relative path query did not exist C:\Program Files\dotnet\sdk\NuGetFallbackFolder\DependentProject\1.0.0\DependentPr
oject.dll
    Skipping... not found in probe dir 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder'
Error:
  An assembly specified in the application dependencies manifest (DependentProject.deps.json) was not found:
    package: 'DependentProject', version: '1.0.0'
    path: 'DependentProject.dll'

So from the bold lines, I'm taking that for some reason it thinks it is a package now?

My other solution was to copy all the files into one folder (so the output from both projects) and then run:
> dotnet --additional-deps .\DependentProj
ect.deps.json .\NetCoreLoaderTest.dll

But that crashes with
>Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

so that doesn't seem to load the runtime dependencies?

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3634
