### ISSUE TITLE
ProjectModelServer - Signing options returned by DTH are not quite right

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#847]
The compilation settings returns a bool for the PublicSign option. This option is true if the user has chosen to use OSS signing. The DTH needs to return the hardcoded public key as a byte array (like the previous version did), instead of the bool value.

**Comment by BillHiebert** [comment]
@troydai

**Comment by davidfowl** [comment]
Do we still have a hardcoded `byte[]` in the CLI? I don't think we do..

**Comment by troydai** [comment]
We don't. So should tooling just make their own public key or do we actually want to give them one?

**Comment by troydai** [comment]
If user set the `publishSign` to true without giving a key file the who is assumed to give a publish key?

**Comment by troydai** [comment]
Hi @piotrpMSFT,

We need your input for this issue. When user specify `publicSign` to `true` without gives a `keyFile`, today the error is `CS8102: Public signing was specified and requires a public key, but no public key was specified.`.

It appears to me we will not support the DNX scenario in which when `keyFile` is missing a hardcoded key is used for OSS signing. Could you confirm this is the case?

If so, we don't need to return any hardcoded key to tooling (VS / other IDE).

Thanks,
Troy

**Comment by moozzyk** [comment]
My 2 cents: I guess this feature is gone. It might have been fine in dnx but having a hardcoded key in CLI feels wrong to me. Now users can provide their own .snk which is the right thing to do.
(One of the reasons we had this in DNX was that initially passing snk for oss signing was not supported)

**Comment by troydai** [comment]
Ping @davidfowl @piotrpMSFT

**Comment by davidfowl** [comment]
The feature is gone and this is no longer valid. The user has to pass the keyFile. We just need to match what the cli does m.

**Comment by troydai** [comment]
I'll close this issue then, /cc @BillHiebert
