### ISSUE TITLE
Message from NuGet is not localized

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8471]
“Restoring Packages for” 
“Generating msbuild file” 
“Restore completed in xxx.xx ms for”

**Comment by livarcocc** [comment]
This bug should be file against NuGet, if these messages are coming from them.

**Comment by wli3** [comment]
Agree. Although this is discovered by end to end manual tests. I got the issue yesterday afternoon. I haven't looked at it yet. It could due to CLI not passing some params.

**Comment by mattscheffer** [comment]
Just to note, these were found on a Windows 8.1 ESN machine using the ,NET Core 2.1 signed build given out on Tuesday. Windows x64 version. Found while running dotnet pack and dotnet install tool.

**Comment by nguerrera** [comment]
Looks like we never ingested nuget satellites: https://github.com/dotnet/cli/issues/6114#issuecomment-338414675

This should stay on us, but I've close #6114 which was kept open just for that. The version they gave us before 2.0 RTM had some bugs. Those were fixed but too late to go out with 2.0 and there wasn't follow up on this until now.

**Comment by livarcocc** [comment]
we should pick up nuget satellites for 2.1.300.
