### ISSUE TITLE
Cannot download latest version from channel 1.0 using dotnet-install.sh

### ISSUE THREAD

**Issue by conniey** [dotnet/cli#8474]
## Steps to reproduce
On Ubuntu 17.10, execute:
`curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 1.0 --shared-runtime --install-dir '~/.tools/dotnet`
## Expected  behavior
That it downloads and installs the latest version.

## Actual behavior
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.9/dotnet-runtime-1.0.9-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/1.0.9/dotnet-runtime-1.0.9-linux-x64.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

## Note
I took the channel from this documentation: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script

**Comment by livarcocc** [comment]
Which distro are you trying to use? It seems like we are defaulting to the linux-x64 distro, which is not supported in 1.0, which is why you get a 404 NOT Found.

cc @johnbeisner

**Comment by conniey** [comment]
Ahh, I see now. I'm using Ubuntu 17.10. 
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore1x 
Is there any way to make this error more clear for other users that the distribution is not supported instead of a 404?

The docs I am using as guidance doesn't suggest that I may run into this issue either.
[dotnet-install.sh](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)

**Comment by livarcocc** [comment]
I will let @johnbeisner comment on the possibility of improving this error without incurring in a bunch of engineering debt. Meaning, I don't want the script to have a list of supported distros hard-coded in it for validation.

Maybe adding a message saying, maybe this distro is not supported, see here <link> for a list of supported distros would be good enough?

**Comment by conniey** [comment]
That would be a better experience 👍

**Comment by livarcocc** [comment]
Tagging @johnbeisner on this issue again.
