### ISSUE TITLE
asp.net mvc template app crashes with exceptions on raspian ARM

### ISSUE THREAD

**Issue by Buzze11** [dotnet/cli#8490]
## Steps to reproduce

    1. create example mvc app with "dotnet new mvc -n test"
    2. Disable HttpsRedirect comment out (//app.UseHttpsRedirection();)
    3. Disable Cookie Policies comment out (//app.UseCookiePolicy();)
    4. publish with "dotnet publish -r linux-arm" and deploy it to the raspberry pi
    5. run app on raspberry device with ./test
    6. place a webrequest from any browser to the server

## Expected  behavior
MVC Example App shows up in browser window

## Actual behavior
- Exceptions get thrown.

- Even without modifying the example app (not deactivating https) the app is throwing exceptions on requests.

## Environment data
`dotnet --info` output:
Product Information:
Version: 2.2.0-preview1-007947
Commit SHA-1 hash: e8f7ddd01b

Runtime Environment:
OS Name: Windows
OS Version: 10.0.10586
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\2.2.0-previe

Microsoft .NET Core Shared Framework Host

Version : 2.1.0-preview1-26116-04
Build : eeb3a84e2142aba791fe003564b8afd048c45ff9

[Exception.log](https://github.com/dotnet/cli/files/1670022/Exception.log)

**Comment by livarcocc** [comment]
This issue was moved to aspnet/Home#2831
