### ISSUE TITLE
Understand plan for command line debugging.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#85]
There are many experience to think through with debugging and whether there are commands or switches we need to add to enable attach on run.

**Comment by piotrpMSFT** [comment]
Command line debugging is out of scope for 1.0.0.

**Comment by blackdwarf** [comment]
@piotrpMSFT this is, however, in Backlog and I would keep it in backlog for tracking. Either that, or we create a new milestone called "Planning" or "vNext" and keep things in there.

**Comment by livarcocc** [comment]
Closing this old issue. When this scenario comes to the front of our planning, we can create a new set of issues to track the work.
