### ISSUE TITLE
run `dotnet install tool -g test-global-tools` twice will return error

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8500]
Error "Failed to install tool test-global-tools. A command with the same name already exists. "

Thanks to @yuki233

@KathleenDollard do you think this is a bug at all? It could be 2 different tools with the same name from different feed. And if the consumer really want to install them twice, s/he should use `--force`. If we want to enable install twice, we may need to record checksum, so we know it is really a same package installed twice.

**Comment by livarcocc** [comment]
I would say we should make this by design. If the user is sure he wants to overwrite, use the -f/--force flag to overwrite it. We should though, give a nice error message in this situation. Maybe even add the -f option to the error message.

**Comment by KathleenDollard** [comment]
Does this mean that in all cases, without force, we will give an error if the shim/script already exists? Whether or not the user is reinstalling the same thing, upgrading, or installing a different tool with same name? 

If so,  I agree.

**Comment by wli3** [comment]
> Does this mean that in all cases, without force, we will give an error if the shim/script already exists? Whether or not the user is reinstalling the same thing, upgrading, or installing a different tool with same name?

Correct.

So closing it, by design
