### ISSUE TITLE
How to use daily sdk build with daily ASP.NET Core build

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#8503]
## Steps to reproduce

Download and untar latest sdk from https://github.com/dotnet/cli
```
dotnet new web
dotnet run
```

## Expected  behavior

I can get the application to run based on README info

## Actual behavior

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.All', version '2.1.0-preview1-28124' was not found.
  - Check application dependencies and target a framework version installed at:
      /home/tmds/Downloads/dotnet-sdk-latest/
  - The .NET framework can be installed from:
      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

```

## Environment data

```
.NET Command Line Tools (2.1.300-preview2-008022)

Product Information:
 Version:            2.1.300-preview2-008022
 Commit SHA-1 hash:  71f22a9f37

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.25-x64
 Base Path:   /home/tmds/Downloads/dotnet-sdk-latest/sdk/2.1.300-preview2-008022/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9
```

**Comment by livarcocc** [comment]
@natemcmaster is this due to some mismatch between the templates and the CLI?

**Comment by natemcmaster** [comment]
Possibly. @tmds what's in the generated csproj file? Also what is in `/home/tmds/Downloads/dotnet-sdk-latest/shared/`?
cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
From the error message it looks like there was no aspnetcore shared framework installed at all. Which sdk installer was used? I took a quick look at the OSX tar.gz file and it did include the aspnetcore shared framework.

**Comment by tmds** [comment]
@JunTaoLuo linux-x64 https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz

**Comment by livarcocc** [comment]
Indeed, I don't see the shared framework in the file linked above.

@natemcmaster @JunTaoLuo is this something that you guys can take a look at? Probably something missing in the build files from when we ingested the asp.net shared framework in the SDK.

**Comment by dasMulli** [comment]
Is the `Microsoft.AspNetCore.All` package in the nuget fallback folder or does it need a special nuget feed?

**Comment by JunTaoLuo** [comment]
It should be installed under shared/. There's something wrong with the linux archive. The osx and windows archives contains `Microsoft.AspNetCore.All` under the correct directory.

**Comment by dasMulli** [comment]
Btw the `Microsoft.AspNetCore.App` package that was introduced in the announcement post (https://github.com/aspnet/Announcements/issues/287) also requires a shared framework.

Is this supposed to be a change in an upcoming update or will both packages + shared frameworks be included in an upcoming cli?

**Comment by JunTaoLuo** [comment]
Correct, we have already built that package and shared framework on our side. It will be included in the cli soon.

**Comment by natemcmaster** [comment]
FYI - you can also get installers for the aspnetcore shared framework here: https://github.com/aspnet/universe#daily-builds. The versions linked their may not match with what is bundled in the CLI. There is a lag between when we produce a new build of aspnetcore and when CLI consumes it.

**Comment by JunTaoLuo** [comment]
@livarcocc @johnbeisner I took a look at our builds and it seems like we produced all the required artifacts for the 28124 build that was ingested by the CLI so I'm not sure why the linux archive didn't pick it up. Can you look through the build logs for the 26116-04 build or point me to where the build log is?

**Comment by tmds** [comment]
> Can you look through the build logs for the 26116-04 build or point me to where the build log is?

@livarcocc @johnbeisner ping

**Comment by johnbeisner** [comment]
This is the CLI build for the Linux portable TAR: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1331328&_a=summary 
you should find the download link for the logs near the top

**Comment by JunTaoLuo** [comment]
This dropped off my radar last week. I just took a look at the build log and it seems the aspnetcore-runtime artifacts were being downloaded and extracted. 
```
2018-01-29T21:37:59.9504620Z [39;49m         /bin/tar xf /opt/code/bin/2/linux-x64/packages/aspnetcore-runtime-internal-2.1.0-preview1-28124-linux-x64.tar.gz -C /opt/code/bin/2/linux-x64/intermediate/sharedFrameworkPublish 
```

This suggests that our artifacts were being picked up but I'm not sure why they were not included in the sdk archives. Could this be similar to the issue with the mac pkg installers were outdated builds steps weren't picking up our new shared framework? https://github.com/dotnet/cli/pull/8539

**Comment by natemcmaster** [comment]
cc @Eilon @livarcocc this also seems like also a blocking-release issue. The dotnet-sdk-linux-x64.tar.gz file does not include the aspnetcore runtime. I'm trying to see if #8539 fixes it as well.

**Comment by natemcmaster** [comment]
Assigning myself to take a closer look at this

**Comment by muratg** [comment]
@livarcocc could you also take a look?  This is blocking one of @balachir's scenarios:  Installing the CLI/SDK with tar.gz archive and do a restore locally.

**Comment by livarcocc** [comment]
Looking...

**Comment by natemcmaster** [comment]
It appears to be fixed in the latest prodcon build. I'm double checking other installers now

https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1
https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180205-02/final/assets/Sdk/2.1.300-preview1-008026/dotnet-sdk-2.1.300-preview1-008026-linux-x64.tar.gz

**Comment by natemcmaster** [comment]
I manually verified all .zips and .tar.gz's from product build 20180205-02-1360785 include the aspnetcore shared runtime.

Recommend closing this now once #8539 makes it back to master.

**Comment by johnbeisner** [comment]
NIT: Recommend closing this now once https://github.com/dotnet/cli/pull/8539 & https://github.com/dotnet/cli/pull/8552 makes it back to master.

**Comment by JunTaoLuo** [comment]
Do we know why it was missing in previous builds? I don't know if closing this issue without knowing why the problem occurred in the first place is a good idea.

**Comment by natemcmaster** [comment]
When updating the code from the package runtime store to the shared framework, I missed this required change to redist.csproj: https://github.com/dotnet/cli/commit/8de55145af7724b9af261dec4c4090e98117c4a5#diff-acadc45977478b307ad6d53f23f6e17c

**Comment by natemcmaster** [comment]
The fix should be in master now.
