### ISSUE TITLE
Extensibility Tool search path different between Windows and Linux/OSX systems

### ISSUE THREAD

**Issue by BroadSight** [dotnet/cli#8521]
## Backstory

I was aiming to write a quality of life script to help with the development of a particular project. This script (or rather the pair of scripts) would be included in the project's repository. Basically, I want a per-project based extensibility tool but in script format instead of NuGet package.

## Steps to reproduce

1. Write a pair of scripts `dotnet-hello.cmd` and `dotnet-hello` (contents below) and save them in the root of a project.

```cmd
echo "Hello World"
```

```bash
#!/bin/bash

echo "Hello World"
```

2. Run `dotnet hello` in the project folder in on a Windows system and Linux/OSX system.

## Expected  behavior

`Hello World` should print in both systems

## Actual behavior

`Hello World` only prints on a Windows system

A Linux/OSX system says `No executable found matching command "dotnet-hello"`

The Linux/OSX systems do not look in the CWD for extensibility tools while the Windows system does.

## Environment data

Windows `dotnet --info` output:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

Linux `dotnet --info` output:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by livarcocc** [comment]
This is something that we don't really intend to bridge, these differences in behavior between different OSes, not at the CLI level.

Could you maybe leverage our new feature, global commands, do to something similar to this?

**Comment by livarcocc** [comment]
I believe this has now been fixed by https://github.com/dotnet/cli/pull/8589.
