### ISSUE TITLE
dotnet SomeAssembly.dll not loading appsettings.json

### ISSUE THREAD

**Issue by giridharprakash** [dotnet/cli#8523]
## Steps to reproduce
create new dotnet core web api project
Get some configuration from appsettings.json in Startup.cs like eg connection string
dotnet publish -c Release
Now go to publish directory and run dotnet Assembly.dll

## Expected  behavior
While debugging in visual studio everything working fine
but when i run from command line then it's not loading appsettings.json

## Actual behavior
In startup.cs connection string is coming as null
var connectionString = Configuration["AppSettings:ConnectionString"];

## Environment data
`dotnet --info` output:
 dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment]
This issue was moved to aspnet/Home#2852
