### ISSUE TITLE
Daily download borked (2.1.300-preview2-008042)

### ISSUE THREAD

**Issue by mgravell** [dotnet/cli#8525]
I've been trying for a few days to download the daily from https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries

All of the binaries are failing to download, reporting a network error. This has been seen by multiple browsers on multiple devices by multiple users (see [here](https://gitter.im/dotnet/corefx?at=5a73028cb3c4a0d376c90ea5) and down).

Can it be unborked, please?

**Comment by mgravell** [comment]
Still borked: 2.1.300-preview2-008046

**Comment by livarcocc** [comment]
@mgravell what sort of errors are you seeing? We are not aware of any particular issues and we just put our assets in azure blob storage.

So, if there is any issues with that, I would check for any azure outages. Which, by the way, azure status reports all green.

**Comment by mgravell** [comment]
It fails with "network error" after a few seconds. No other parts of the
internet seem to be affected, so I don't think it is me. An associate of
mine reported it working when it was still failing for me - possibly a CDN
glitch? Has persisted for many days. When first reported, several other
people were seeing the same thing.

**Comment by livarcocc** [comment]
The links in the github page do not point to a CDN, which may be exactly the problem.

Can you try downloading using the CDN? Should be a URL like this for windows: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-preview2-008048/dotnet-sdk-2.1.300-preview2-008048-win-x64.exe

For our download links in the github page, we just update the latest file in place in the blob storage. We don't recommend using the CDN url in this case, because latest will be whatever has been cached by the CDN instead of actual latest.

**Comment by mgravell** [comment]
Here's `curl`, as an example:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  125M    0 1127k    0     0   140k      0  0:15:10  0:00:08  0:15:02 49652
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 0
```

so: it fails after just over 1MB. Vexingly, if I run it through Fiddler, it doesn't break - but it fails in multiple browsers and curl! Trying the CDN url now - at 15MB, so definitely got further...

**Comment by mgravell** [comment]
K; that seemed to complete from the CDN url, so I guess I'm set for now - but: not sure what to say about what to do next. I think there *is* a problem - I just don't know exactly what it is!

**Comment by livarcocc** [comment]
Seems like a problem with Azure. Our solution for that is the CDN.

Let us know if the CDN does not work for you.

**Comment by mgravell** [comment]
@livarcocc  this is still failing; I can hack by guessing the current CDN path, but... that really sucks. There is a problem here. The download **should not be failing**. I'm not the only person affected; still hearing grumbles from others too.

**Comment by livarcocc** [comment]
We have started an internal thread to try to figure out what is going.
