### ISSUE TITLE
How to update referenced package versions from CLI

### ISSUE THREAD

**Issue by AustinWise** [dotnet/cli#8528]
## Steps to reproduce
1) Type `dotnet help`

## Expected  behavior
1) Expect to see `dotnet update` or similar command to update referenced packages. Something equivalent to Visual Studio's GUI that allows upgrading packages.

## Actual behavior
1) After much searching, I can't find any command to update the package version.

## Other thoughts
Currently there is no way that I can tell to update package versions when running on Linux, except to delete the reference and add it back. I can set the the `Version` attribute to equal "`*`", but that does not bind to a predictable version.

Is there a way to list which packages are upgradeable that I missed?

If there is not such a command, is it desired?

**Comment by livarcocc** [comment]
There is no such command today.

I believe this is in the NuGet backlog.

cc @richlander this is a feature request that we had to NuGet for a while:  a dotnet update package command.

I will move this issue to NuGet.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6540

**Comment by JonCanning** [comment]
You might find this useful

https://gist.github.com/JonCanning/a083e80c53eb68fac32fe1bfe8e63c48

**Comment by cdibbs** [comment]
Thanks, @JonCanning. Unfortunately, we use Powershell at work. If I decide to port it over, I'll post link to a gist, here.

**Comment by JonCanning** [comment]
No problem, have added a ps version too!

**Comment by cdibbs** [comment]
Hah! Just circled back, this morning, and you beat me to it. Thanks, again!
