### ISSUE TITLE
NuGet tag convention for dotnet cli tools

### ISSUE THREAD

**Issue by rmcc13** [dotnet/cli#8532]
Hi, first I wanted to say nice job on the extensibility model for the dotnet cli. Being able to install and use small focused tools for project management is awesome. I apologize if this is not the right place for this, but I would like to open up a discussion on defining a standard NuGet tag for dotnet cli tools.

In the JavaScript world, it is common for tools to use a common tag that the community can use when publishing plugins to npm. For example, [Karma](https://karma-runner.github.io/2.0/index.html) plugins use the tag [karma-plugin](https://www.npmjs.com/browse/keyword/karma-plugin) and gulp plugins use the tag [gulp-plugin](https://www.npmjs.com/browse/keyword/gulp-plugin). This makes it easy for people to find existing tools to their problems.

There is a [repository that lists many dotnet cli tools](https://github.com/natemcmaster/dotnet-tools), but I imagine it will eventually become out of date because that type of work can become tedious. When looking at the NuGet pages for many of those tools, their isn't much commonality in the tags that were used. [NuGet supports browsing by tag](https://www.nuget.org/packages?q=Tags%3A%22dotnet%22), so I think this would be very useful.

If the dotnet team and the community can come to an agreement on a tag to use for tools, I think it would be nice to have it mentioned in the [.NET Core CLI tools extensibility model documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility) so others that are looking to build a new tool can see what tag(s) to use for visibility. If this is something others are interested, then I would like to suggest the tag `dotnet-tool`, but I would like to hear what others think.

**Comment by livarcocc** [comment]
Tools packages have a specific PackageType that eventually people can filter by when searching for tools at nuget.org.

Would this solve your main problem: the discoverability of tools?

**Comment by rmcc13** [comment]
Yea, I think that would be good enough. Thanks for the quick response

**Comment by livarcocc** [comment]
No worries. Thanks the interest and for reaching out.
