### ISSUE TITLE
Add command for nuget add [or support hierarchical local folders from nuget push]

### ISSUE THREAD

**Issue by steevcoco** [dotnet/cli#8533]
I would like to see the addition of `nuget add` to the commands. I use it to build a local repository ... And unlike Push, it will create the hierarchical folder structure.

It seems like a very simple addition: the command is just like push ...

Alternatively, could `push` support the folder structure in a local folder?

**Comment by unusual-thoughts** [comment]
Same here. There is no way to use locally built packages without this

**Comment by dasMulli** [comment]
Is your problem consuming packages or pushing built packages to a directory?

Consuming local packages can be done by configuring a folder as package source in nuget.config..
e.g. https://stackoverflow.com/questions/43400069/dotnet-add-package-with-local-package-file

**Comment by steevcoco** [comment]
I believe a problem is that you cannot push multiple targets? I haven't encountered it myself ... I simply would like the option because the local repo is faster ,and better laid out that way ... It is just a better layout and is much preferred. But if you DO have multiple targets, then how could you push both locally?

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6541
