### ISSUE TITLE
Command-line app development and distribution workflow

### ISSUE THREAD

**Issue by arthurwhite** [dotnet/cli#8547]
This is kind of related to #7002.

Is there an easy way to develop, build and distribute command-line apps in .NET Core 2.0?

- In Python, you set [`entry_points`](https://packaging.python.org/tutorials/distributing-packages/#entry-points) in *setup.py* and install app with `pip install -e .` during development.
- In Node.js, you set [`bin`](https://docs.npmjs.com/files/package.json#bin) in *package.json* and install app with `npm link` during development.
- In Go, you write a [`main()`](https://golang.org/doc/code.html#Command) function and install app with `go install`.
- Etc.

So I understand that we can produce either portable (DLL) or self-contained (EXE) builds with `dotnet publish -c <CONFIGURATION> -r <RUNTIME_IDENTIFIER>`, but what happens next?

**Comment by livarcocc** [comment]
cc @KathleenDollard I don't believe this is related only to .NET Core. At least, I can't say so without you saying more about what problem you are trying to address here.

Is your issue the fact that .NET Core Apps are comprissed of multiple files and you are wondering how to distribute them? They were designed to be xcopyable to whatever machine they need to go to.

Is your problem the fact that you are looking for a marketplace like location for your apps? We don't have that for .NET Core.

If your apps are more development centric, we are building a feature called dotnet tools, where you can package your app and distribute it through nuget.org and then install them using the .NET Core SDK through a `dotnet install tool -g <tool_package_id>` command.

**Comment by arthurwhite** [comment]
> Is your issue the fact that .NET Core Apps are comprissed of multiple files and you are wondering how to distribute them? They were designed to be xcopyable to whatever machine they need to go to.

No, the "multiple files" design should not be an issue here.

> Is your problem the fact that you are looking for a marketplace like location for your apps? We don't have that for .NET Core.

OK, that answers part of the question.

But at least, I'd like to easily "install" my console app under a system-wide, custom command during development, like I'd do with a trivial `npm link` for example.

Because actually, to get a custom command:
- When we generate **self-contained** builds, we must manually **move the binary + assets** inside `/usr/local/share/` (on Unix-like, I don't know about Windows) to get our custom command.
- When we generate a **portable** console app, it' impossible because the DLL must be called in conjunction with the **`dotnet <PATH_TO_DLL>` command**.

That's not intuitive at all.

**Comment by KathleenDollard** [comment]
Are you looking for npm -g?

That we are building. dotnet install tool -g <your nuget package>

We will not have a marketplace, we will have NuGet.

Does that help? If so I can give you more information on it.
________________________________

**Comment by arthurwhite** [comment]
Yeah, exactly!

I just searched about these .NET Core Global Tools and I came across the [.NET Core 2.1 Roadmap post](https://blogs.msdn.microsoft.com/dotnet/2018/02/02/net-core-2-1-roadmap/) from last week.

Now I understand that's a WIP.

> We will not have a marketplace, we will have NuGet

Sure, I see.
I misunderstood @livarcocc when he talked about a "marketplace" because NPM-like repositories are kind of falling in my definition of a marketplace. 😅

Thank you both!

**Comment by KathleenDollard** [comment]
I'm glad it fits your needs.

I'm very interested in your experience with it. What's hard, what's easy, what do you need that isn't there.

I'm also interested in how difficult setting up argument management and help is for you to do as you develop your tool.
________________________________

**Comment by arthurwhite** [comment]
#### What's easy

- Almost everything: no major difficulty with NuGet so far.
- Searching and downloading packages directly from Visual Studio (Code|Mac).
The integration is nice!
- Automatical dependency management and cleaning.

#### What's hard

- We only see a short summary of each package description so choosing the best one requires a visit to each project site. Integrating READMEs (when available) like NPM does should ease the process.
- Figuring out the minimal requirements of a package (.NET Core and/or .NET Framework and which version).
- Not hard but boring: the dialog asking for licenses acceptance at every package install.
- Package signing but as I see, [it's also a WIP](https://blog.nuget.org/20170914/NuGet-Package-Signing.html).

#### What isn't there

- Package search from the CLI like [`npm search`](https://docs.npmjs.com/cli/search).
- Sorting search results by total number of downloads rather than "relevance". Thats an [old request](https://github.com/NuGet/Home/issues/1739).
- Convenient CLI helpers like [`npm version`](https://docs.npmjs.com/cli/version) or [`npm outdated`](https://docs.npmjs.com/cli/outdated).
- Interesting stats about the package code (like test coverage, at least).
- Maybe an in-browser playground. But I assume that's a lot of work for little benefit.

#### How difficult is setting up argument management and help

I don't have a definitive opinion about this.
Actually, I'm barely digging in the .NET ecosystem as I decided to learn C# only 2 weeks ago.
Making a CLI was just a pretext. 🤓

I use the [McMaster.Extensions.CommandLineUtils](https://www.nuget.org/packages/McMaster.Extensions.CommandLineUtils/) package and it does the job pretty well so far.
Too bad it's not a Microsoft "official" package anymore, even if it seems (well) maintained by Microsoft employees. Also, the documentation seems poor compared to something like Python's [argparse](https://docs.python.org/3/library/argparse.html).

**Comment by KathleenDollard** [comment]
Thank you for your input.

You're "What's hard" largely aligns with our backlog and we'll keep it in our considerations.

We are working on the argument story. Nate McMaster's library is not a bad place to be right now. We're hoping to do better.

Kathleen
________________________________
