### ISSUE TITLE
portable global tool summary issue

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8551]
- [x] uninstall https://github.com/dotnet/cli/issues/8549
- [x] list https://github.com/dotnet/cli/issues/8548
- [x] update https://github.com/dotnet/cli/issues/8564
- [x] prelease https://github.com/dotnet/cli/issues/8485
- [x] Remove Microsoft.NETCore.Platforms dependency requirement for producer https://github.com/dotnet/cli/issues/8617
- [x] p2p pack tool https://github.com/dotnet/sdk/issues/1998

**Comment by wli3** [comment]
@KathleenDollard update is not required for 2.1.3xx right?

**Comment by KathleenDollard** [comment]
We had planned to delay it when we thought `dotnet install -f` would work for this scenario.

What is our guidance for getting a new version?

**Comment by wli3** [comment]
@KathleenDollard 

I remember update is the replacement of -f.

uninstall and install it is the guidance

**Comment by KathleenDollard** [comment]
Than I feel we need it. Any chance of getting that in?

**Comment by livarcocc** [comment]
Do we really believe that between 300 and 400 there are going to be that many global tools and we can't tell folks for now, do uninstall/install?

Otherwise, I feel like we could wait for 400 to add this in.

@KathleenDollard What do you think?
