### ISSUE TITLE
macOS installer: generate branding versions in conclusion

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8558]
Latest macOS .pkg installers have this on the final page
![image](https://user-images.githubusercontent.com/2696087/35937007-c4a376e6-0bf9-11e8-907a-dfd358f9e42b.png)

These values are hard-coded here: https://github.com/dotnet/cli/blob/5fa558a2ed60104d8e21434b99ee757135d5aadb/packaging/osx/clisdk/resources/en.lproj/conclusion.html#L8-L13

It would be better if the version information was generated from DependencyVersion.props so we have to remember to manually update these values when we start releasing patches for (ASP).NET Core runtimes.

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/8042. We are tracking fixing this for all installers there.
