### ISSUE TITLE
dotnet vstest: how to remotely debug of test runs in Docker?

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#8562]
## Steps to reproduce
I need to remotely debug mstest unit-tests inside a Linux Docker container.
I publish my mstest project, build and run a container with that output and then run [dotnet vstest](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest) in the container which I expect to debug from my Windows host in VS/VSCode. But it turned out to be not very easy, if not possible.

Please see full story in https://github.com/OmniSharp/omnisharp-vscode/issues/2015 (there I provided my full setup to debug in Docker). It seems that the problem is that VSCode cannot attach to an actual process executing tests. So step-by-step debugging doesn't work.

Initially I thought it's a vsdbg or VSCode issue, but it seems to be more related to how `dotnet vstest` works.

Actually it'd nice to debug from VS as well but remote debugging of Docker in VS is just a riddle for me. So let's stick to VSCode.

## Expected  behavior
Run unit tests inside Docker and attach debugger, do step-by-step debugging.

## Actual behavior
Test run (via dotnet vstest) but debugger isn't attached.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1426
