### ISSUE TITLE
update, for dotnet tool

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8564]
Check the packageId is the same, check version number is increasing

do an uninstall the old and install the new tool in order to make sure shims are consistent.

**Comment by wli3** [comment]
@KathleenDollard 
should the command be `dotnet update tool -g my.tool` ?

**Comment by wli3** [comment]
I will not have `--version` opinion. I don't want to make it more complicated. What happen if you have 1.2 and you want to "update" to 1.1? Should we block it? But maybe you don't want sine they could come from different feed. I will simply do uninstall install, whatever the version install get(restore with *)

**Comment by wli3** [comment]
More detail decision made only by me: If there is no package exist on disk. Update will fail (instead of install it)

**Comment by KathleenDollard** [comment]
I agree with not updating a non-existing package. 

But why not allow --version?

**Comment by livarcocc** [comment]
Added through https://github.com/dotnet/cli/pull/8794.
