### ISSUE TITLE
[Feature Request] dotnet nuget version command

### ISSUE THREAD

**Issue by kasper3** [dotnet/cli#8569]
`dotnet nuget version <your version>` - like `npm version <your version>`, it will bump the version in csproj.

Creating a next version today requires us to manually update the version either in csproj or Visual Studio UI. CLI doesn't have any support.

Furthermore with npm, if the project is under git source control:

* it creates a commit with message `<your version>`
* it creates a git-tag for it
* errors out if the tag exists with same name:

>npm ERR! code 128
> npm ERR! Command failed: git -c core.longpaths=true tag v1.5.2 -am 1.5.2
> npm ERR! fatal: tag 'v1.5.2' already exists
> npm ERR!

refs https://docs.npmjs.com/cli/version

**Comment by livarcocc** [comment]
I am not sure I follow your ask here. What do you mean by bump the version? You mean update the version property in the csproj for that particular project?

What if your project is not versioned in the csproj, but rather in a props file somewhere else?

**Comment by kasper3** [comment]
Yes, update the version in csproj. NPM refers it as "Bump a package version".

If the property is calculated value or not in the immediate project file (`--project <csproj path>`), then this command can throw an error.

**Comment by livarcocc** [comment]
Would it bump major, minor or patch? How do you control that? How is this a value add over editing your csproj and editing the number there? We have simplified the csproj for .NET Core a lot, so that it has very little content there. Editing it should be easy.

We did add some project manipulation commands, like dotnet add package, but that's because we felt some of these changes were harder to discover for beginners or involved a lot more typing than editing a number.

I am just trying to understand to evaluate if this would be an interesting thing for us to add for our customers.

**Comment by livarcocc** [comment]
Also, we are building a thing called global commands, where I wonder if this is something that should be done there, maybe by the community?

**Comment by kasper3** [comment]
A typical github release cycle is creating a git-tag per version and [create a release](https://help.github.com/articles/creating-releases/) (optionally mark it as pre-release) with notes and additional artifacts.

`npm-version` command in addition to bumping version in packages.json, creates version commit as well as git-tag with that version. Typically, this is how many npm package authors using git release the next [pre-]release:

```sh
# after committing all changes for v3.1.85:

npm version 3.1.85
git push && git push --tags
npm publish
```

This will create a commit `3.1.85` with diff:

```diff
diff --git a/package.json b/package.json
index 9bc0071..a4df27e 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "my-package",
-  "version": "3.1.84",
+  "version": "3.1.85",
```

and author pushes that as well as the tag. Then goes to releases page (e.g. https://github.com/dotnet/cli/releases) and creates the release from the tag.

This integrates into most common git flow. Besides that, npm allows us to install directly from git-tag or branch or commit (basically any git commit'ish). However, when the project is not under git SC, it just updates the version.

The requirement is to provide full SEMVER2 format, the protocol that NuGet also supports. Providing partial version to `npm-version` command produces an error.

#### "Releasing a new version" in the eyes of npm community warrants to have a top-level, OOTB command.

This helps node.js community to automate their release management in so many interesting ways (from build machines, from third-party apps).

---


Analogous to NPM, if dotnet CLI also provide `dotnet-nuget-version` command OOTB, our command-line-savvy workflow would be:

(Proposed workflow)

```cmd
cd myrepo
dotnet nuget version 3.1.85 -p ExampleProject/
# or
dotnet version 3.1.85 -p ExampleProject/

git push && git push --tags

dotnet pack -c Release
dotnet nuget push ExampleProject/bin/Release/ExampleProject.3.1.85.nupkg -k <your-api-key>
```

Here our diff would look like:

```diff
-    <VersionPrefix>3.1.84</VersionPrefix>
+    <VersionPrefix>3.1.85</VersionPrefix>
```

vs. current workflow

```sh
cd myrepo

# open ExampleProject/ExampleProject.csproj in editor and apply above-mentioned diff

git commit -am "3.1.85"
git tag 3.1.85

git push && git push --tags

dotnet pack -c Release
dotnet nuget push ExampleProject/bin/Release/ExampleProject.3.1.85.nupkg -k <your-api-key>
```

**Comment by livarcocc** [comment]
cc @KathleenDollard 

I think for dotnet lots of folks rely on their CI/CD servers for versioning, rather than hard coded versions in their csproj files. With MSBuild, you can set your version as an Environmnet variable or pass it as a parameter to MSBuild and it gets honored in your build.

Also, not keen on the CLI integration with github. We haven't done this for any other source control system and I would prefer to keep the CLI agnostic to that.

In that sense, your script could be something like this:

```
cd myrepo

git tag 3.1.85

git push && git push --tags

dotnet pack -c Release /p:VersionPrefix=3.1.85
dotnet nuget push ExampleProject/bin/Release/ExampleProject.3.1.85.nupkg -k <your-api-key>
```

And your csproj would then contain something like this":
```
<PropertyGroup>
  <VersionPrefix Condition=" '$(VersionPrefix)' == '' ">1.0.0</VersionPrefix>
</PropertyGroup>
```

**Comment by KathleenDollard** [comment]
Interesting scenario. I agree with Livar that it looks like a great use for global tools. The major reasons I think global tools are a good fit are that it is specific to an external technology (git) and because I can see ways this could be creatively enhanced.

**Comment by livarcocc** [comment]
Going to close this issue since I believe that we have alternatives that are conducive to a nice build experience, even though we don't have the exact commands of npm (which is not the goal).

If folks still feel strongly about this command, I think a global command would fit the scenario nicely.
