### ISSUE TITLE
ProjectModelServer : send References before Dependencies

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#857]
When updating a tree in Solution Explorer we need both references and dependencies, however updates happen after dependencies are sent. It is hard to time them reliably so we want references to be sent before dependencies. 
We do have a throttle to handle cases when references received later, but it would be more reliable if we switch order.

**Comment by davidfowl** [comment]
@abpiskunov Is this new?

**Comment by troydai** [comment]
@davidfowl This is new: https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.DesignTimeHost/ApplicationContext.cs#L729

**Comment by troydai** [comment]
Fixed in 479a81a576a7fb24dce731d48c185af2d4a9edcd
