### ISSUE TITLE
Confusion when tool install a different package with the same PackageId

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#8573]
This doesn't occur always. It happened to be in the initial attempt for this project type, but subsequent attempts work correctly. This also occurred on a shim scenario.

## Steps to reproduce
Install latest .NET Core2.1 preview and latest D15.6
Open cmd prompt
dotnet new console -n multi
Open the .csproj and change the file to:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.1;netcoreapp2.1</TargetFrameworks>
    <PackAsTool>true</PackAsTool>
  </PropertyGroup>

</Project>
```
Navigate to the project folder and run: dotnet pack
Copy the .nupkg file in the bin folder to a local NuGet drop.
dotnet install tool -g multi

## Expected  behavior
The package installs.

## Actual behavior
Package fails to install. Output is the following:

```
c:\Users\v-masche\Documents\multi>dotnet install tool -g multi
C:\Users\v-masche\AppData\Local\Temp\lc012hsr.xw2\trudtbrw.dsa.csproj : warning NU1701: Package 'Multi 1.0.7' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
C:\Users\v-masche\AppData\Local\Temp\lc012hsr.xw2\trudtbrw.dsa.csproj : warning NU1701: Package 'YunkuEntSDK 3.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
C:\Users\v-masche\AppData\Local\Temp\lc012hsr.xw2\trudtbrw.dsa.csproj : error NU1212: Invalid project-package combination for Multi 1.0.7. DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'multi' failed to install.
```
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.300-preview2-008162)

Product Information:
 Version:            2.1.300-preview2-008162
 Commit SHA-1 hash:  5a5a245658

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008162\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c

**Comment by livarcocc** [comment]
@wli3 to comment.

**Comment by wli3** [comment]
It's likely you are actually restoring a existed packaged called _multi_ from nuget.org. Could you make the package ID longer to make it unique like _multi-dotnet-testing-02082018_ ? Or disable nuget.org as a package feed.

**Comment by mattscheffer** [comment]
I think you're on the right track. I ended up getting it to work by adding a source tag pointed at my local nuget source folder. 

That being said there still might be a bug here. This seems like it could be confusing for customers if it doesn't check local files at all if there is a tool online, even if the tool is broken.

**Comment by wli3** [comment]
So let me change the title to make it a discussion

**Comment by wli3** [comment]
@KathleenDollard @peterhuene this need some discussion. If the tool package name conflict with a package existed in NuGet.org, depends on nugetconfig, it could download that instead. Do you think we need to add more guidance? I think normal nuget package have this problem already

**Comment by peterhuene** [comment]
I definitely think this needs to be improved, at the very least with respect to attempting to install a non-tool package.

With the `verbosity` option, you can at least check which source "won" the install by making the output more verbose.  Ideally I'd like us to print out which source we obtained the package from, but I'm not sure if can do that easily.

**Comment by wli3** [comment]
I don't know, if we want to be consistent of "user should aware nuget is underneath", the user should understand the packageId collision. And CLI should do nothing.

**Comment by KathleenDollard** [comment]
Our packages will co-exist with "normal" packages, correct?

So I'm a bit hesitant to make the package look like it's working locally, and then have a name collision with NuGet.org. I wonder if a warning here is in order. 

I'm not sure we can fix it, but one thing I hate about @mattscheffer 's experience is that he had to scroll to the right to see that the package type was not a tool.

**Comment by wli3** [comment]
> Our packages will co-exist with "normal" packages, correct?

correct

> warning here is in order

A warning when there is PackageId when the same name existed in NuGet.org or in all the current feed?

Is this an issue have to be in 2.1300?

**Comment by KathleenDollard** [comment]
I do *not* think we should do the warning on anticipated collisions because we know the package exists on NuGet.org or elsewhere in 2.1.300.

My reasoning is that we have some work regarding feeds in mind in terms of discovery, and doing this work parallel with the discovery work makes sense in my head.

**Comment by wli3** [comment]
Message is added https://github.com/dotnet/cli/pull/9079
