### ISSUE TITLE
Installed global tool cannot be run

### ISSUE THREAD

**Issue by pranavkm** [dotnet/cli#8577]
## Steps to reproduce
* https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180208-05/final/assets/Sdk/2.1.300-preview1-008117/dotnet-sdk-2.1.300-preview1-008117-win-x64.exe
* Execute `dotnet install tool dotnet-dev-certs -g --version 2.1.0-preview1-28257 --source https://dotnet.myget.org/f/dotnet-core/api/v3/index.json`
* Run dotnet-dev-certs
The tool cannot be found: 
```
dotnet-dev-certs : The term 'dotnet-dev-certs' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
```
* Run `dotnet dev-certs`
```
> dotnet dev-certs
No executable found matching command "dotnet-dev-certs"
```

Exepcted:
For the first run after install experience, running `dotnet dev-certs` should fallback to the tools dir to locate the file if it cannot be found.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.300-preview1-008117)

Product Information:
 Version:            2.1.300-preview1-008117
 Commit SHA-1 hash:  60614db20c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-previe

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26208-06
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by livarcocc** [comment]
@wli3 @peterhuene can you guys take a look?

**Comment by peterhuene** [comment]
Need to check if the command resolver is properly probing the tools directory for commands (assuming this is a scenario we want to support).

**Comment by peterhuene** [comment]
Deleted the previous comment since I misread the issue.  Either invocation should be functional.  I can take a look.

**Comment by wli3** [comment]
I think that is the bug that cmd need to reopen cmd after first run

**Comment by peterhuene** [comment]
I'm not sure we'd want to explicitly fallback to the tools directory to support `dotnet <unprefixed-tool-name>` only after the first run experience and without following the instructions printed when the tool was installed.  If no instructions were printed, then that's a bug.

**Comment by wli3** [comment]
Agree on no instruction is the problem

> running dotnet dev-certs should fallback to the tools dir to locate the file if it cannot be found.

We could consider it. But we need to consider if it is worth to add another resolver

**Comment by wli3** [comment]
Dup of this? https://github.com/dotnet/cli/issues/8368

**Comment by pranavkm** [comment]
Yeah seems like a dup. Closing this since the other one is older.
