### ISSUE TITLE
csc.dll exited with code 1

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/cli#8581]
## Steps to reproduce
1. dotnet new mvc
2. Add `.AddFormatterMappings(m => {);` between `.AddMvc()` and `.SetCompatibilityVersion` in 'Startup.cs'.
3. dotnet run

## Expected  behavior
I would expect to get an informative error message about the mistakes I've just made (leaving off a trailing "}" and adding a ";", then trying to call `.SetCompatibilityVersion`.).

## Actual behavior
It returns:
```
/home/rybrande/dotnet/sdk/2.1.300-preview1-008030/Roslyn/Microsoft.CSharp.Core.targets(84,5): error MSB6006: "csc.dll" exited with code 1. [/home/rybrande/functional/src/Fail/Fail.csproj]

The build failed. Please fix the build errors and run again.
```
with no other identifying or helpful information.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.300-preview1-008030)

Product Information:
 Version:            2.1.300-preview1-008030
 Commit SHA-1 hash:  be228a492f

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/rybrande/dotnet/sdk/2.1.300-preview1-008030/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26207-04
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

Ubuntu 16.04

Found while doing aspnet/Release#215.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/roslyn#24736
