### ISSUE TITLE
Can't invoke dotnet-* global tools by tool name on OSX (works on Windows)

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#8593]
## Steps to reproduce
1.  `dotnet new razor`
2. `dotnet install tool dotnet-dev-certs --global --version 2.1.0-preview1-28262`
3. `dotnet dev-certs`

You can even restart your terminal in-between steps 2 & 3.

## Expected  behavior
Help info:
```
Usage: dotnet-dev-certs [options] [command]

Options:
  -h|--help  Show help information

Commands:
  https

Use "dotnet-dev-certs [command] --help" for more information about a command.
```

## Actual behavior
`No executable found matching command "dotnet-dev-certs"`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.300-preview1-008118)

Product Information:
 Version:            2.1.300-preview1-008118
 Commit SHA-1 hash:  82f9d6e530

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300-preview1-008118/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26209-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

```

## Extra

If you try and invoke the tool by its full name `dotnet-dev-certs` all works as expected.

/cc @Eilon @DamianEdwards

**Comment by livarcocc** [comment]
I actually think @wli3 has a fix for this already.

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/8589

**Comment by wli3** [comment]
due with https://github.com/dotnet/cli/issues/8450

**Comment by livarcocc** [comment]
@wli3 we should consider #8589 for preview1. Can you fill out the ask mode template and tag matt for approval?

**Comment by wli3** [comment]
OK, i will address and code review and fill out ask mode template
