### ISSUE TITLE
Add ability to set process Title on "dotnet run"

### ISSUE THREAD

**Issue by thiagolunardi** [dotnet/cli#8610]
It's so annoying to attach a process started by `dotnet run` via Visual Studio, because there is no way to distinguish them when we have more than one netcore application running with `dotnet run`.

There is a `Title` column there, but it's always blank. Will be nice to be possible to use it.

Follow one suggestion to achieve that.

- Me as a `Developer`
- When execute `dotnet run --title="Contoso.Host"`
- Then at `Task Manager` > `Process Tab`, my process MUST BE displayed like:
`dotnet: Contoso.Host`
- Then at `Task Manager` > `Details Tab`, my process MUST BE displayed like:
`dotnet.exe | 12345 | Running | username | 00 | 54.321 K | dotnet: Contoso.Host`
- And at `Visual Studio` > `Attach to Process` > `Available processes`, my process MUST BE displayed like:
`dotnet.exe | 12345 | Contoso.Host | Managed (CoreCLR), x64`

Of course will be WAY BETTER to have it directly from the application itself - `Console.Title` definition., then no need to have an new parameter. But, baby steps.

**Comment by svick** [comment]
Related: https://github.com/dotnet/core-setup/issues/2007

**Comment by livarcocc** [comment]
This is not an issue that should be solved for dotnet run, but rather for dotnet portable applications in general. It is tracked in the issue mentioned above, as such, I will close this one.

**Comment by scratie** [comment]
this will be a good feature, just like in cmd
start "App Name" dotnet run -p project_path
