### ISSUE TITLE
CLI source code build error : Unable to find package Microsoft.AspNetCore.DeveloperCertificates.XPlat

### ISSUE THREAD

**Issue by pkapare** [dotnet/cli#8640]
## Steps to reproduce
1. Clone CLI repo
2. Run Build.cmd to build code

## Expected  behavior
Should build source code without errors.

## Actual behavior
Getting following error.
H:\Github\DotNetCore\cli>build.cmd
H:\Github\DotNetCore\cli\scripts\obtain\dotnet-install.ps1 -version "2.2.0-preview1-007799" -InstallDir H:\Github\DotNetCore\cli\.dotnet_stage0\x64 -Architecture "x64"
dotnet-install: .NET Core SDK version 2.2.0-preview1-007799 is already installed.
dotnet-install: Adding to current process PATH: "H:\Github\DotNetCore\cli\.dotnet_stage0\x64\". Note: This change will not be visible if PowerShell was run as a child process.
Microsoft (R) Build Engine version 15.6.12.27473 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

    Restore completed in 22.91 ms for H:\Github\DotNetCore\cli\build_projects\Microsoft.DotNet.Cli.Build.Framework\Microsoft.DotNet.Cli.Build.Framework.csproj.
    Restore completed in 26.81 ms for H:\Github\DotNetCore\cli\build_projects\shared-build-targets-utils\shared-build-targets-utils.csproj.
    Restore completed in 30.11 ms for H:\Github\DotNetCore\cli\build_projects\dotnet-cli-build\dotnet-cli-build.csproj.
  8215
  787bee7ad3a143c64b677d3cf64c5fb180215c47
Microsoft (R) Build Engine version 15.6.12.27473 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 18-Feb-18 8:38:15 AM.
     1>Project "H:\Github\DotNetCore\cli\build.proj" on node 1 (default targets).
     1>PrintBuildInfo:
         Host info - Rid: win10-x64, OSName: win
         Build info - Rid: win10-x64, Architecture: x64, OSName: win
         If you intended to use a different Rid, Architecture, or OSName run the following command to generate your build state:
         dotnet msbuild build.proj /p:Architecture=Architecture /p:Rid=Rid /p:OSName=OSName /p:GeneratePropsFile=true /t:WriteDynamicPropsToStaticPropsFiles
       MSBuildWorkaroundTarget:
         Dont remove this target
       RestoreDotnetCliBuildFramework:
         H:\Github\DotNetCore\cli\/.dotnet_stage0/x64/dotnet.exe restore  /p:GeneratePropsFile=
           Restore completed in 21.65 ms for H:\Github\DotNetCore\cli\build_projects\Microsoft.DotNet.Cli.Build.Framework\Microsoft.DotNet.Cli.Build.Framework.csproj.
           Restore completed in 23.66 ms for H:\Github\DotNetCore\cli\build_projects\shared-build-targets-utils\shared-build-targets-utils.csproj.
           Restore completed in 26.36 ms for H:\Github\DotNetCore\cli\build_projects\dotnet-cli-build\dotnet-cli-build.csproj.
       BuildDotnetCliBuildFramework:
       Skipping target "BuildDotnetCliBuildFramework" because all output files are up-to-date with respect to the input files.
       CheckPrereqs:
         Using previous stage version:
         H:\Github\DotNetCore\cli\/.dotnet_stage0/x64/dotnet.exe --version
         2.2.0-preview1-007799
       RestoreSrcPackages:
         > [DotNetTool] restore    "H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj"
         > H:\Github\DotNetCore\cli\/.dotnet_stage0/x64\dotnet.exe restore    "H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj"
           Restoring packages for H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj...
           Restore completed in 32.43 ms for H:\Github\DotNetCore\cli\src\tool_launcher\tool_launcher.csproj.
           Restore completed in 49.29 ms for H:\Github\DotNetCore\cli\src\Microsoft.DotNet.InternalAbstractions\Microsoft.DotNet.InternalAbstractions.csproj.
           Restore completed in 59.98 ms for H:\Github\DotNetCore\cli\src\Microsoft.DotNet.Configurer\Microsoft.DotNet.Configurer.csproj.
           Restore completed in 58.11 ms for H:\Github\DotNetCore\cli\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj.
           Restore completed in 59.35 ms for H:\Github\DotNetCore\cli\src\Microsoft.DotNet.Cli.Sln.Internal\Microsoft.DotNet.Cli.Sln.Internal.csproj.
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.DeveloperCertificates.XPlat with version (>= 2.1.0-preview2-30106) [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 7 version(s) in cli-deps [ Nearest version: 2.1.0-preview1-28275 ] [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 5 version(s) in BlobFeed [ Nearest version: 2.1.0-preview1-28275 ] [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in nuget.org [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in dotnet-corefxlab [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in websdkfeed [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in nuget-build [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in roslyn [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in symreader-native [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in templating [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in vstest [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in container-tools [H:\Github\DotNetCore\cli\build.proj]
     1>H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in xunit [H:\Github\DotNetCore\cli\build.proj]
           Restore failed in 1.08 sec for H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj.
     1>Done Building Project "H:\Github\DotNetCore\cli\build.proj" (default targets) -- FAILED.

Build FAILED.

       "H:\Github\DotNetCore\cli\build.proj" (default target) (1) ->
       (RestoreSrcPackages target) ->
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.DeveloperCertificates.XPlat with version (>= 2.1.0-preview2-30106) [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 7 version(s) in cli-deps [ Nearest version: 2.1.0-preview1-28275 ] [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 5 version(s) in BlobFeed [ Nearest version: 2.1.0-preview1-28275 ] [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in nuget.org [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in dotnet-corefxlab [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in websdkfeed [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in nuget-build [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in roslyn [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in symreader-native [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in templating [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in vstest [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in container-tools [H:\Github\DotNetCore\cli\build.proj]
         H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 0 version(s) in xunit [H:\Github\DotNetCore\cli\build.proj]

    0 Warning(s)
    13 Error(s)

Time Elapsed 00:00:04.29
Failed to build
At H:\Github\DotNetCore\cli\run-build.ps1:105 char:31
+     if($LASTEXITCODE -ne 0) { throw "Failed to build" }
+                               ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to build:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to build

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.100-preview-007363)

Product Information:
 Version:            2.1.100-preview-007363
 Commit SHA-1 hash:  0468da6ada

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100-preview-007363\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment]
@javiercn is this the developer cert package? Any idea why it is not found?

**Comment by javiercn** [comment]
Yes. I have no Idea. @natemcmaster will know better. But I'll take a quick look right now to see if I figure out.

**Comment by javiercn** [comment]
@livarcocc Seems to me that its checking the preview1 feeds. 
https://dotnet.myget.org/feed/aspnetcore-release/package/nuget/Microsoft.AspNetCore.DeveloperCertificates.XPlat <- This is the latest version on the preview1 package feed which is the one the build log mentions it can find.

> H:\Github\DotNetCore\cli\src\dotnet\dotnet.csproj : error NU1102: - Found 7 version(s) in cli-deps [ Nearest version: 2.1.0-preview1-28275 ] [H:\Github\DotNetCore\cli\build.proj]

**Comment by javiercn** [comment]
Ok, seems like it's picking up the package from https://dotnet.myget.org/feed/cli-deps/package/nuget/Microsoft.AspNetCore.DeveloperCertificates.XPlat which is not up to date

Seems like the aspnetcore-dev feed is defined in
https://github.com/dotnet/cli/blob/fbc76ea5f659aed90f793bdf8b03eb01f9289b44/build/NugetConfigFile.targets#L23

but I can't see it being taken into account in the build log.

**Comment by natemcmaster** [comment]
The package it should be picking up exists: https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.DeveloperCertificates.XPlat/2.1.0-preview2-30106

https://github.com/dotnet/cli/blob/787bee7ad3a143c64b677d3cf64c5fb180215c47/build/DependencyVersions.props#L4
https://github.com/dotnet/cli/blob/787bee7ad3a143c64b677d3cf64c5fb180215c47/build/NugetConfigFile.targets#L23

Since it appears the NuGet.config file is generate on the fly, try running `git clean` and re-try.

**Comment by pkapare** [comment]
After git clean and unchecking aspnetcore-release feed from nuget configuration it worked without any errors.

**Comment by pkapare** [comment]
closing issue.
