### ISSUE TITLE
Error on dotnet run

### ISSUE THREAD

**Issue by marono** [dotnet/cli#865]
Guys,

I'm getting an error when running dotnet run or dotnet build:
_An item with the same key has already been added. Key: (log4net, neutral, 669e0ddf0bb1aa2a)_

Not sure how to proceed.

Thank you!

A bit more context:
My project.lock.json contains the following bits:

```
"Log4Net/2.0.5": {
        "type": "package",
        "compile": {
          "lib/net45-full/log4net.dll": {}
        },
        "runtime": {
          "lib/net45-full/log4net.dll": {}
        }
      },
      "log4net.Ext.Json.1.2.13/1.2.13.20140804": {
        "type": "package",
        "dependencies": {
        "log4net": "2.0.3"
        },
        "compile": {
          "lib/net35-full/log4net.Ext.Json.dll": {}
        },
        "runtime": {
          "lib/net35-full/log4net.Ext.Json.dll": {}
        }
      }
```

Notice the log4net dependency of log4net.Ext.Json has different casing than the root Log4Net dependency. Could this be the issue?

UPDATE2:
Changed the cached nuspec file for log4net.Ext.Json to say Log4Net and it made the error go away. At this point I think this is a bug. I'll try and have a look at the code.

**Comment by piotrpMSFT** [comment]
@marono not sure what the CLI bug might be here. What does your project.json look like? It seems this might be an issue with the log4net nuspec?

**Comment by marono** [comment]
Hi @piotrpMSFT ,
When building the project.lock.json, it will consider log4net and Log4Net as two different packages and would try to bring them both; the model (dependencies model) would then reject the second package as being already added (hence the key collision error). At least that's my understanding without looking at the code...

Here's my dependencies spec (only global dependencies for this project):

```
"dependencies": {
    "System.Runtime": "4.0.21-*",
    "log4net.Ext.Json.1.2.13": "1.2.13.20140804",
    "Topshelf": "3.3.1",
    "Topshelf.Log4Net": "3.3.1"
  },
```

**Comment by piotrpMSFT** [comment]
@davidfowl this one is in your wheelhouse :)

**Comment by davidfowl** [comment]
Is it a casing problem?

**Comment by marono** [comment]
Here's a gist which will hopefully highlight the issue:
https://gist.github.com/marono/f4934cf81249c0cb700c


It seems the issue is slightly more involved than originally thought. It will only show itself when using the option to emit the entry point.

Let me know if you need more context.

**Comment by marono** [comment]
Guys,

I've identified the root cause of this being the binding redirects generation.
Some packages include more files than just their compilation output (like referenced assemblies). When the ``BindingRedirectGenerator`` tries to figure out the overall list of assemblies to compile the list of require redirects it will look at ``LibraryExport.RuntimeAssemblies``, which may contain overlapping assemblies from different packages, causing a key conflict in a dictionary.

The fix I'm proposing is to include an assembly in the overall assembly list only if it's not in the ``LibraryExport.CompilationAssemblies`` of another dependency, which would make it the 'primary' output for that other library. This way, I'm stating that if a library has a certain assembly as its primary output, that version should prevail over any other version added by other dependencies as references. It also results that assemblies in the (``Compilation`` list aka primary outputs) take higher priority when generating binding redirects than assemblies specified in the ``Runtime`` list.

I've spent a bit of time trying to understand how it all works together, hopefully I got everything right. Please have a look and let me know!

**Comment by blackdwarf** [comment]
@piotrpMSFT is this still valid? Is this something that is mitigated with the move to MSBuild?

**Comment by piotrpMSFT** [comment]
@krwq is making some Binding Redirects fixes. It'd be good to hear that this is fixed.

**Comment by blackdwarf** [comment]
@krwq is this done? Do we still need it?

**Comment by blackdwarf** [comment]
@krwq is this done?
