### ISSUE TITLE
Cant build/run dnx452 projects

### ISSUE THREAD

**Issue by marono** [dotnet/cli#866]
Guys,

I can't build or run dnx452 projects. It works fine for dnx451 and dnx46, the only difference being I'm missing the Microsoft .NET Framework 4.5.2 SDK when checking the installed programs.

I haven't been able to find the setup for it. Is there one?

**Comment by piotrpMSFT** [comment]
@marono can you provide more details? Failure msg, etc?

**Comment by marono** [comment]
Hi, the error message is:
```
Framework not installed: DNX,Version=v4.5.2 in C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework
```

**Comment by davidfowl** [comment]
Do you have .NET Framework 4.5.2 reference assemblies in that folder?

**Comment by marono** [comment]
Hi,
I've got a bunch of folders under ``C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework``:
```
.NETCore
.NETFramework
.NETPortable
v3.0
v3.5
WindowsPhone
WindowsPhoneApp
```

``.NETCore`` will contain ``v4.5`` and ``v4.5.1``
``.NETFramework`` has all versions from 3.5 to 3.6.

Are these details enough ?

**Comment by marono** [comment]
@davidfowl switched to net452 for now. It seems dnx452 was available in one of the betas but has been dropped/forgotten. Probably there's not many people complaining because they had beta6 (I think) installed and they still have the ``.NETCore`` version there as a leftover.

I'll close the issue and keep an eye on it for RC2.

Thanks,
