### ISSUE TITLE
Add aspnetcore tools to `dotnet help` output

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#8666]
Follow-up to https://github.com/dotnet/cli/pull/8665 and https://github.com/dotnet/cli/pull/8606

The CLI will bundle several aspnetcore tools, but they don't appear in the output of `dotnet --help`. To make it more visible to users, it would be nice to add these.

Text might look like this:
```
$ dotnet --help
.NET Command Line Tools
Usage: dotnet [runtime-options] [path-to-application]
Usage: dotnet [sdk-options] [command] [arguments] [command-options]

path-to-application:
  The path to an application .dll file to execute.

SDK commands:
  (...existing ones here like "build"...)
  watch           Starts a project watcher that re-starts a command when files change
  user-secrets    Provides commands to control ASP.NET Core user secret data
  dev-certs       Provides commands to control the ASP.NET Core developer HTTPS certificate
  sql-cache       Provides a command for creating an MSSQL database for ASP.NET Core caching
```

cc @KathleenDollard @danroth27 for wording

**Comment by livarcocc** [comment]
@danroth27 already expressed that he does not think it is necessary, as these tools have very specific needs and this would pollute an already big text blob. I do think watch should be moved into the general help, as it has a more general purpose, but not the other ones. Also, we already have an issue tracking making this better somehow.

Closing this issue in favor of https://github.com/dotnet/cli/issues/8633.
