### ISSUE TITLE
Dotnet install tool doesn't throw an error when a tool with the same name is already instaled

### ISSUE THREAD

**Issue by mattscheffer** [dotnet/cli#8668]
Appears to be a regression of #8479
## Steps to reproduce
Create 2 projects to be used with different names
```
dotnet new console -n sametool1
dotnet new console -n sametool2
```
Edit the project file for each and add the following
```
<PackAsTool>True</PackAsTool>
<ToolCommandName>sametool3</ToolCommandName>
```
Should be the same command name for each.
Run dotnet pack in each project file folder
Copy the package to your local NuGet feed (or run the next commands with --source tags)
Attempt to install both
```
dotnet install tool -g sametool1
dotnet install tool -g sametool2
```

## Expected  behavior
The 2nd tool fails to install.

## Actual behavior
The 2nd tool is allowed to install.
![image](https://user-images.githubusercontent.com/10537189/36562841-0c05b196-17cd-11e8-8917-55557b0d9f8b.png)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Comment by mattscheffer** [comment]
D15.7stg 27422.3001 was installed on this machine as well.

**Comment by livarcocc** [comment]
cc @wli3 and @peterhuene

**Comment by wli3** [comment]
This is dotnet-sdk-2.1.300-preview1-008174 from branch 2.1.3XXX for preview1 it is fixed in master.

**Comment by livarcocc** [comment]
Closing since this is fixed in master. Re-activate if this repros with a 2.1.3-preview2 (currently, master) build.
