### ISSUE TITLE
restore dependencies without the project

### ISSUE THREAD

**Issue by avoidik** [dotnet/cli#8679]
Hi,

Could you please give me a hint on how can I download all dependencies defined in dependency manifest file (*.deps.json) without the project (solution)? Like "self-contained deployment (SCD)" does this with `dotnet publish`, but manually on target server.

**Comment by livarcocc** [comment]
That's not possible.

How would you know that these dependencies are available online? What if they were all project to project references? What if they were on a custom nuget feed that has not been setup in your target server? There are many missing pieces of the puzzle here.

Why can't you just copy the contents of the publish folder to your server and execute it? That's how it was designed to work?

In any case, I am going to close this issue.
