### ISSUE TITLE
The dotnet install tool fails if a feed can't be reached, even if the package is available in the offline cache. 

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8690]
For example, this might happen when the machine is offline

Due to by default nuget will throw if the a feed cannot reach.

**Comment by wli3** [comment]
PR in progress

**Comment by wli3** [comment]
conclusion of meeting this Monday. Try out `dotnet add package`, disable internet, and have localfeed on the top. And see if it still fails.

As long as the the `install tool` and `add package` have the same behavior it is good.

**Comment by livarcocc** [comment]
We are not shipping any tools of off the NuGetFallbackFolder anymore. Closing this issue. We can re-activate of file a new one if we start doing that again.
