### ISSUE TITLE
Cannot update to 2.1.0-preview1-final

### ISSUE THREAD

**Issue by mhosman** [dotnet/cli#8694]
## Steps to reproduce
Update from 2.0.5 to 2.1.0-preview-final using NuGet Administrator (Preview releases included).

## Expected  behavior
Update to 2.1.0-preview-final

## Actual behavior
Error: Restore package failed (no inner errors, no extra information)

## Environment data
`dotnet --info` output:

Herramientas de la línea de comandos .NET (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5

  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6617
