### ISSUE TITLE
Cannot load hostpolicy.dll on Win2012R2

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#870]
dotnet.exe crashes on startup on Windows 2012 Server.

``Failed to load the dll from C:\dotnet\bin\hostpolicy.dll, HRESULT:0x8007007E``

Running from cmd prompt displays an error dialog:

`The pgoram can't start because MSVCP140.dll is missing from your computer`

Error started with changes in 262274b9681b6586e01d715703a13e1098c0be1e

**Comment by piotrpMSFT** [comment]
#835 seems to be the culprit here. @natemcmaster can you verify that installing the CRT fixes this issue?

**Comment by natemcmaster** [comment]
@piotrpMSFT installing CRT changes the error to 
![image](https://cloud.githubusercontent.com/assets/2696087/12363904/5357a096-bb80-11e5-8c02-f65619ea54f2.png)

**Comment by natemcmaster** [comment]
Install CRT 2015 + reboot fixes this problem.

**Comment by schellap** [comment]
CRT shouldn't be required for at least the first step. 

https://github.com/schellap/cli/blob/master/src/corehost/cli/dll/CMakeLists.txt#L8-L10 should all be MT and not MD
