### ISSUE TITLE
Add a space when instructing people how to call dotnet global tools

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/cli#8709]
# Steps to reproduce

Install a global tool that is prefixed with dotnet.

## Expected  behavior

The installation succeeded. If there are no further instructions, you can type the following command
in shell directly to invoke: dotnet user-secrets

## Actual behavior

The installation succeeded. If there are no further instructions, you can type the following command
in shell directly to invoke: dotnet-user-secrets

Note that there is a dash following dotnet instead of a space, although the user should type with a space. 
 
## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
Should we really be doing this?

The fact that it works without the `dotnet-` is a idiosyncrasy of one of our resolvers in the CLI, where if you type dotnet foo, we will try to find a command named dotnet-foo. We did this in order to support project tools, which had to be named dotnet-foo for things to work.

I am not sure we want to advertise that and encourage people to build tools off of the dotnet command. Do we?

**Comment by KathleenDollard** [comment]
If someone installs a tool with dotnet-foo, we designed for them to run this via `dotnet foo` 

Shouldn't we tell them run it that way?

I'm not a fan of dotnet-, but it's out there so I don't know that there is much we can do about it.

**Comment by peterhuene** [comment]
I also prefer users not to install dotnet-prefixed tools this way, but users will undoubtably do so (not taking into account we're doing this for watcher and other ASP.NET tools for preview1 anyway).

Given how easy it is and how it does lead to a better UX, I'm :+1: with implementing this fix.

**Comment by wli3** [comment]
if we want to do that, at least we need to come up with guide line and reserve words.

**Comment by wli3** [comment]
Today, it is not advertised and there is no guarantee their word won't be taken in the future. Say I create my dotnet-install

**Comment by KathleenDollard** [comment]
Ok, but it's still on the extensibility page in docs last I checked.

Is our resolution that because this is a Preview 1 only we'll ignore the problem as by the time we fixed it, we would not need the fix?

I'm cool with that.
________________________________

**Comment by KathleenDollard** [comment]
Closed as won't fix
