### ISSUE TITLE
Unable to run dotnet on Windows after MSI installation

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#871]
> C:\dotnet\bin>dotnet
Failed to load the dll from C:\dotnet\bin\hostpolicy.dll, HRESULT: 0x8007007E
Error loading the host library from own dir: C:\dotnet\bin; Status=00000041

@schellap I think its because of your recent changes - https://github.com/dotnet/cli/pull/843

/cc @piotrpMSFT @gkhanna79

**Comment by gkhanna79** [comment]
@Sridhar-MS Is hostpolicy.dll not present next to the host?

**Comment by schellap** [comment]
This is weird. It is present. So I am looking at why Windows is not picking up.

**Comment by schellap** [comment]
Could you please paste the repro steps, I am not able to repro on my Windows 10 box with the latest MSI.

**Comment by schellap** [comment]
See similar issue:
https://github.com/dotnet/cli/issues/871#issuecomment-172072816

**Comment by natemcmaster** [comment]
Duplicate of #870? I installed the C++ Redistributable 2015 and rebooted and the error went away.

**Comment by Sridhar-MS** [comment]
Duplicate of #870
