### ISSUE TITLE
dotnet store command fails when --output path has whitespace 

### ISSUE THREAD

**Issue by rakeshsinghranchi** [dotnet/cli#8714]
## Steps to reproduce
1. Create manifest csproj file as below : ( packages.csproj)
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Moq" Version="4.7.63" />
  </ItemGroup>
</Project>
2. Run command : 
dotnet store --manifest packages.csproj --runtime win10-x64 --framework netcoreapp2.1 --framework-version 2.1.0-preview1-26216-03 --output "C:\**Program Files**\dotnet\store"

## Expected  behavior
dotnet store command executes successfully and provisions the nuget packages under c:\program files\dotnet\

## Actual behavior
dotnet store command fails to execute : 
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.ComposeStore.targets(269,5): error MSB3191: Unable to create directory "C:\Program Files\dotnet\store\x64\netcoreapp2.1\". Access to the path 'C:\Program Files\dotnet\store\x64\netcoreapp2.1\' is denied. [C:\Users\raksingh\packages.csproj]

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Comment by livarcocc** [comment]
I am not so sure this is a white space problem, but rather that as a regular user, you can't write to the program files folder. You need to do that with elevated permissions. Can you try writing to a different folder with white space? One that you create?

If that works, it confirms my theory above and in that case, there really isn't anything we can do.

**Comment by rakeshsinghranchi** [comment]
Works fine with whitespace when run as admin. Closing the issue now.
