### ISSUE TITLE
dotnet host should log fatal application errors to Windows Event Log (when on Windows)

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/cli#8719]
.NET Framework on Windows today will log an error from the source ".NET Runtime", including the offending stack trace and application name, to the "Application" Windows Event Log whenever a .NET app crashes, e.g.:

```
Application: VSIXAutoUpdate.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at Microsoft.VisualStudio.Telemetry.TelemetryComplexProperty..ctor(System.Object)
   at VSIXAutoUpdate.AutoUpdate.LogAutoUpdateCompletedTelemetry()
   at VSIXAutoUpdate.AutoUpdate.Main()

```

![image](https://user-images.githubusercontent.com/249088/36924946-7e797768-1e25-11e8-907a-7dd92f560d29.png)

This information is very useful in many scenarios, including servers, where many existing systems collect Windows Event Log information and use it to report and diagnose problem applications.

We'd very much like this feature to be replicated in the .NET Core host for Windows, such that any faulting .NET Core application logs a similar error.

@davidfowl

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#3765
