### ISSUE TITLE
Installing a final version of an SDK should remove preview versions

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8720]
@onovotny commented on [Fri Mar 02 2018](https://github.com/dotnet/core-setup/issues/3770)

See this thread:

https://twitter.com/DamianEdwards/status/969762795926429696

Issue is that after a while, users wind up with tons of preview SDK's (either due to direct install or by being chained into a VS Preview channel update). They never get uninstalled.

Installing the final version of an SDK should remove the corresponding preview versions as it's very unlikely that a user would intend on having the older previews alongside.

/cc @nickcraver

**Comment by nguerrera** [comment]
I don't think we should do it this way.

Instead, build to build upgrades of vs should uninstall (more accurately decrement ref count and install if no refs remain) the version bundled with last build and install version coming with new build. This is how other msis chained into VS work. The bug for doing that is https://github.com/dotnet/cli/issues/6896

**Comment by livarcocc** [comment]
Also, isn't this true for runtime install as well? I mean, it will be less common, because people don't usually install the runtime separately, but I wonder if we should keep parity here.

Also, I think we should track it at #6896, as @nguerrera suggests.

**Comment by nguerrera** [comment]
Agreed. If this really is the semantic we want, then the runtime should do it too. If VS previews are the only real issue, then #6896 is the right fix.

@onovotny @NickCraver would you be satisfied by #6896? If so, let's close this.

**Comment by onovotny** [comment]
I'd say that it's not about the runtime, but it shouldn't be only about VS Previews either. I may have installed a random nightly build to try out a fix as well. That won't be ref-counted by the VS Installer, but it should still be cleaned up once the final version of that release comes out.

**Comment by nguerrera** [comment]
Why do would that reasoning not apply to runtime installs? You could have installed previews of those too.

There have been times where folks have clung to previews to buy time dealing with rtm design change fallout. (Cough, project.json) I don't think we should assume that we canr remove something designed to work SxS (preview or not) if we weren't the ones to install it.

If you run the installer yourself, you should be responsible for uninstalling it. Why is that unreasonable?

The issue of too many preview builds has come up a lot, but every time, it traces back to being on the VS preview train. Twitter thread here was no exception. #6896 would fix that and I think we should stop there.

**Comment by stajs** [comment]
I had to go read the Twitter thread, where it seemed it was only talking about preview SDK's installed by VS. If that is the intent of this issue, can someone edit the title/opening comment to be make that clear?

I was nervous when I first saw this issue. There have been times when I (and my company) have clung to the previews until we were ready to move to RTM. As @nguerrera and @livarcocc are suggesting, it seems that #6896 would be the better fix for VS installed previews, and if a user-installed ref count still counts then it could leave me happily (!) clinging on to previews without them being removed underneath me.

**Comment by NickCraver** [comment]
I agree Visual Studio removing what it installs would remove 95% of the annoyance from my use case - I'd certainly start there and look at it if it's still a problem. I think nightly builds may still be a problem, but would re-evaluate after removing the VS noise.

+1 on merging with #6896 and opening another issue for nightly builds if it remains and issue

**Comment by nguerrera** [comment]
Closing in favor of #6896 and we can revisit if necessary after that is done, but I suspect it will be enough.
