### ISSUE TITLE
Installed template is not listed in dotnet new

### ISSUE THREAD

**Issue by AdrienTorris** [dotnet/cli#8723]
I installed the Blazor template to create a Blazor project. It worked fine the first time but now, the template is not listed anymore in the dotnet new templates.
I try to uninstall, reinstall or other things but nothing worked, I can't create a blazor app anymore.

## Steps to reproduce
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.0.5-* --nuget-source https://dotnet.myget.org/F/blazor-dev/api/v3/index.json
dotnet new --list

```

## Expected  behavior
Have the Blazor templates in the list, and can create a new blazor app with the _[dotnet new]_ command.
![getting-started-blazor-dotnet-cli-cmd-03](https://user-images.githubusercontent.com/1014357/36967378-d9c581ca-205f-11e8-9450-47313a88274a.png)
_(This screenshot was taken the first time)_

## Actual behavior
The blazor templates are not available.
![blazor-template-pb](https://user-images.githubusercontent.com/1014357/36967340-be31b168-205f-11e8-9dca-beacbac96777.png)

## Environment data
`dotnet --info` output:
Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1447
