### ISSUE TITLE
Daily builds fail to restore hello world

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/cli#8725]
## Steps to reproduce
Used Linux daily build 2.1.300-preview2-008293 on x64 Ubuntu 16.04
 ```
   cd dotnetcli
   tar -zxf ../dotnet-sdk-2.1.300-preview2-008293.tar.gz .
   cd -

    mkdir hw
    cd hw
    ../dotnetcli/dotnet new console
    if [[ "$?" != "0" ]]
    then
        echo dotnet new console failed
        exit 1
    fi

    ../dotnetcli/dotnet restore
    if [[ "$?" != "0" ]]
    then
        echo dotnet restore failed
        exit 1
    fi
```

## Expected  behavior

Failed new console does not set exit code to 0
Restore succeeds.  Hello world builds and runs

## Actual behavior

`dotnet new console` fails to restore runtime, and sets exit code to 0
`dotnet restore` fails sets exit code to non-zero

## Environment data
x64 Ubuntu 16.04
build 2.1.300-preview2-008293

@janvorli @jkotas FYI

**Comment by sdmaclea** [comment]
This problem also existed in dotnet-sdk-2.1.300-preview2-008281-linux-x64.  As diagnosed by @janvorli in https://github.com/dotnet/source-build/issues/328

@steveharter FYI

**Comment by livarcocc** [comment]
The failure to restore is expected. Preview2 is a nightly build and as such targets nightly builds of the runtime and its packages that are not available in NuGet.org.

For restore to work for you, you will need to add a nuget feed to myget pointing to a feed that contains those packages, likely the dotnet-core feed.

**Comment by livarcocc** [comment]
As for dotnet new returning 0 when restore fails, you should file an issue at dotnet/templating for that.

**Comment by sdmaclea** [comment]
See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md 
```
<packageSources>
    <add key="myget.dotnetcore" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    ...
```

or 

See https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/UsingDotNetCli.md
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />

    <add key="local CoreCLR" value="C:\coreclr\bin\Product\Windows_NT.x64.Debug\.nuget\pkg" /> <!-- CHANGE THIS PATH to your local output path -->
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> <!-- link to corefx NuGet feed -->
  </packageSources>
</configuration>
```
