### ISSUE TITLE
Unexpected results when filtering installed templates by type "project"

### ISSUE THREAD

**Issue by scottaddie** [dotnet/cli#8727]
## Steps to reproduce
1. Run the following command: `dotnet new --type project`

## Expected  behavior
I'd expect to only see project templates listed.

## Actual behavior
In addition to project templates, I see the following item templates listed:
1. Solution File
1. Razor Page
1. MVC ViewImports
1. MVC ViewStart

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.2.0-preview1-007866)

Product Information:
 Version:            2.2.0-preview1-007866
 Commit SHA-1 hash:  a99154ed46

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\scaddie\.dotnet\x64\sdk\2.2.0-preview1-007866\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26103-03
  Build    : 1d51767c35cb879c2388adf3d76722c6ad658c72

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1450
