### ISSUE TITLE
What happens when a new era is added in Japanese Calendar?

### ISSUE THREAD

**Issue by tanaka-takayoshi** [dotnet/cli#8733]
I wonder this might not a suitable repo for this issue. Please let me know the right repo and then I'll move.

A new era will be added in Japanese Calendar, which is planned to start at May 1st 2019. I'd like to clarify how Japanese Calendar will be updated.

Here are my understanding about a new era. I would appreciate .NET Core team confirm it. I also want a dedicated document explaining a new era and help creating it.

- At present Japanese Calendar is the only Calendar which a new era could be added. https://github.com/dotnet/coreclr/blob/v2.0.5/src/mscorlib/shared/System/Globalization/CalendarData.Unix.cs#L269
- For Windows, Japanese era info is obtained from registry. Once registry is updated to the new era, .NET Core on WIndows can get a new era info. https://msdn.microsoft.com/ja-jp/library/windows/desktop/dd317805%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
- For Unix (Linux and Mac), Japanese era info is obtained from lib-icu. Once a new version of icu is installed to the machine, .NET Core on Unix can get a new era info.
https://github.com/dotnet/coreclr/blob/v2.0.5/src/mscorlib/shared/Interop/Unix/System.Globalization.Native/Interop.Calendar.cs
- In the case .NET Core can't get a era info from registry on Windows and lib-icu on Unix, .NET Core uses [a hard-coded era info](https://github.com/dotnet/coreclr/blob/v2.0.5/src/mscorlib/shared/System/Globalization/JapaneseCalendar.cs#L97-L120). I'm not sure when this hard-coded era info is used actually. However in this case, upgrading .NET Core CLR is required to update a new era info. Also, if the application is built as a Self Contained Application, I wonder we can't update the a new era info in this application.

Are these issues related?
https://github.com/dotnet/corefx/issues/27506
https://github.com/dotnet/corefx/pull/27617

## Steps to reproduce
N/A

## Expected  behavior
N/A

## Actual behavior
N/A

## Environment data
N/A

**Comment by livarcocc** [comment]
@tanaka-takayoshi It does seem like dotnet/corefx is a better repo for this question. Would you mind moving it? Or do you want us to move it for you?

**Comment by tanaka-takayoshi** [comment]
@livarcocc thanks. I moved the issue and close this one.
