### ISSUE TITLE
The specified framework version '2.0' could not be parsed...

### ISSUE THREAD

**Issue by cgountanis** [dotnet/cli#8735]
The global.json with 2.1.4 does not help when using dotnet ef commands in a classlib. You still have to manually add the RuntimeFrameworkVersion to the CSPROJ file on all projects in the solution. If you only add to one NUGET wants to consolidate because some projects are using 2.0.0 and only the ones specified with RuntimeFrameworkVersion use 2.0.5. I only have SDK 2.1.4 installed why does it just not use Runtime 2.0.5 by default?

Why do I have to specify this in ever CSPROJ, what good is the global.json then?

`
<RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
`

![2018-03-07 09_42_50-sso - microsoft visual studio](https://user-images.githubusercontent.com/14899817/37101772-f400a726-21eb-11e8-8a7d-646342aa179e.png)

![2018-03-07 09_42_56-sso - microsoft visual studio](https://user-images.githubusercontent.com/14899817/37101774-f661469c-21eb-11e8-95bb-5d08addc9a9f.png)

![2018-03-07 09_42_24-core - programs and features](https://user-images.githubusercontent.com/14899817/37101719-dd0615ba-21eb-11e8-920d-d9e36017bea4.png)

**Comment by cgountanis** [comment]
The strange part is if you do not add the RuntimeFrameworkVersion all the projects use a lower not even installed Microsoft.NETCore.App version 2.0.0. How is this even possible, this a bug?

**Comment by livarcocc** [comment]
cc @bricelam 

I believe in here, you need a newer version of the `Microsoft.EntityFrameworkCore.Tools.DotNet` package. A fix went in on that package to handle this situation.

**Comment by cgountanis** [comment]
Well I am on SDK 2.1.4 and you can't even use NUGET to install that without the RuntimeFrameworkVersion set manually. Something is just not right. Maybe it is fixed in the newer preview version of the SDK? Trying to get away from having to hard code the RuntimeFrameworkVersion in every sub project. Like I said the global.json SDK does nothing for me in this situation as I only have 2.1.4 installed anyway which comes with runtime 2.0.5.

**Comment by cgountanis** [comment]
Without the RuntimeFrameworkVersion you get error: 

Error NU1605 Detected package downgrade: Microsoft.NETCore.App from 2.0.3 to 2.0.0. Reference the package directly from the project to select a different version.

I just want to get rid of the requirement of the RuntimeFrameworkVersion, hoping the next version fixes this?

**Comment by livarcocc** [comment]
You should not reference `Microsoft.EntityFrameworkCore.Tools.DotNet` as a `PackageReference`. You need to reference is as a `DotNetCliToolReference`.

Here is a project that I used:

```
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
  
</Project>
```

`Microsoft.EntityFrameworkCore.Tools.DotNet` is a project tool and is the thing that allows you to run `dotnet ef` when in the same folder as the csproj. It needs to be referenced as `DotNetCliToolReference` in order for this to work.

**Comment by cgountanis** [comment]
I did switch that back, thanks. Still having the issue of having to specify the runtime and having to add the DotNetCliToolReference manually. Can the DotNetCliToolReference be added with NUGET?

**Comment by livarcocc** [comment]
The DotNetCliToolReference needs to be added manually. As for the 2.0 issue, I was under the impression it had been fixed by EF already, which is why I cc @bricelam above.

There was an issue in EF tracking that but I don't have it handy. Let's see what Brice says about this.

Also, what command are you trying to run, can you share that?

**Comment by cgountanis** [comment]
**Package Manager (within VS)**
Update-Database
Add-Migration Intital

**DOTNET (withing CMD)**
dotnet ef database update
dornet ef migration add Intital

So on and so forth... really not the issue, the issue is more of the error runtime 2.0 can not be found unless you have the runtime specified in CSPROJ. You do not even get the error when doing it withing VS, so you have to do both before you get a clue on what is going wrong.

**Comment by livarcocc** [comment]
I would file an issue for this under aspnet/entityframework. I couldn't find the original one. The issue here is that EF is passing 2.0.0 directly to the runtime and I remember we discussed using a runtime.config.json in those cases.

If you want to not set `RuntimeFrameworkVersion` directly in your csprojs as a work-around for this issue, you can create a `Directory.Build.props` file in the root of your repo/solution and set this property there. It will then be applied to all projects in a folder under the folder where that file is.

**Comment by bricelam** [comment]
The fix will ship in EF Core 2.0.2. We're hoping it finally ships this month. 🤞 You can the [patch preview feed](https://dotnet.myget.org/gallery/aspnet-2018-feb-patch-public).

**Comment by cgountanis** [comment]
This actually worked better than having it in every single CSPROJ. This what you meant @livarcocc ?

```
<Project>
    <PropertyGroup>
        <Version>1.0.0</Version>
        <Authors>X</Authors>
        <Company>X</Company>
        <Product>X</Product>
        <Description>X</Description>
        <Copyright>X</Copyright>
        <PackageLicenseUrl></PackageLicenseUrl>
        <PackageProjectUrl></PackageProjectUrl>
        <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
    </PropertyGroup>
</Project>
```

**Comment by livarcocc** [comment]
Yep. Ok, given that you have a workaround and that the bug is being fixed in EF, I am going to close this issue.

@cgountanis Glad to see you are unblocked.

**Comment by cgountanis** [comment]
Thanks for the help guys!
