### ISSUE TITLE
dotnet watch test doesn't work on .NET Core 2.1 preview 2

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#8740]
`dotnet watch test` doesn't restart upon file changes. `dotnet watch run` works as expected.

**Comment by livarcocc** [comment]
@natemcmaster what is the appropriate repo for `dotnet watch` bugs?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/DotNetTools

**Comment by natemcmaster** [comment]
@richlander try adding --verbose so we can get more details. `dotnet watch --verbose test`

**Comment by MichaelSimons** [comment]
FWIW - I've successfully used `dotnet watch test` in my Windows using Linux Containers environment.  @richlander can you provide details on which configuration you are using?

**Comment by livarcocc** [comment]
Closing this now since it does not seem to repro anymore.

@richlander let us know if you ran into this again.
