### ISSUE TITLE
The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.

### ISSUE THREAD

**Issue by DebolaAdedapo** [dotnet/cli#8743]
have tried upgrading to the professional version of visual studio 2017 v 15.6.0 (Preview 7.0)

and installed aspnetcore-runtime-2.1.0-preview1-final-win-x64 and .net core SDK 2.1.4.

When I created a new web application I get an error saying

"The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."

When I try to build an existing project I get an error

"The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1."

I don't see ".net core 2.1" in my target framework

I don't have global.json file in my computer

When I try dotnet --info, I get this

c:\source\dnacloud\testapp>dotnet --info
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by DebolaAdedapo** [comment]
so i resolved the problem.
the cause of the problem was that i installed aspnetcore-runtime-2.1.0-preview1-final-win-x64 and .net core SDK 2.1.4-x64 versions. the installation placed the sdk files in 'c:\Program Files\dotnet' but VS2017 was 32bit and was looking for the sdk files in 'c:\Program Files(x86)\dotnet'. 

to resolved installed the x86 version of the sdk and aspnetcore runtime. 

i also set the MSBuildSDKsPath environmental variable to point to the new installation path.

all obsolete sdks were also deleted from control panel

**Comment by dmitry-pavlov** [comment]
Installing .NET Core SDK 2.1.300-preview2 did the trick:
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview2

**Comment by LyalinDotCom** [comment]
@dmitry-pavlov thanks for the tip, I was having trouble building on my dev machine as well, kept saying 2.1 wasn't a supported target even though I seemed to have SDK 2.1.2 installed, but installing 2.1.3 as you indicated above fixed the issue.

**Comment by jjxtra** [comment]
I am getting this issue with yesterdays (May 30) release. I have latest .NET SDK and .NET core SDK installed. Suggestions?

**Comment by livarcocc** [comment]
what is the output of dotnet --info from the folder where you are trying to build from? You may have a global.json file somewhere that is pinning your SDK version to an older one that does not support .NET Core 2.1

**Comment by jjxtra** [comment]
Removing netstandard2.1 from my dll framework resolved the issue. It now just has netcoreapp2.1 and net471. Does that seem odd?

**Comment by livarcocc** [comment]
There is no netstandard2.1 TFM. The latest version of netstandard is netstandard2.0.

**Comment by jjxtra** [comment]
That explains it then. Is a .dll / class library with only netcoreapp2.1 going to cause issues linking to other .dll?

**Comment by livarcocc** [comment]
You will only be able to reference it from other netcoreapp2.1 projects.

**Comment by jjxtra** [comment]
Ok it seems that .net standard 2.1 is a little more tricky. I don't think it's super critical right now. Hopefully it will be formalized and released soon.

**Comment by livarcocc** [comment]
there is no netstandard2.1. The TFM does not exist and I am not aware of plans for it.

**Comment by jjxtra** [comment]
Ah interesting. Is there any guidance on class libraries / nuget packages that want to support .net core 2.1, other than just supporting netcoreapp2.1?

**Comment by livarcocc** [comment]
Projects targetting netcoreapp2.1 can reference netstandard2.0, as netcore2.1 is a super set of it.

**Comment by livarcocc** [comment]
No worries. Glad I could help.

**Comment by mjariwal** [comment]
Upgrade Azure SDK worked for me, I updated  SDK 2.1.400. And before update i seen my current Azure SDK by command (go to command prompt & type command (dotnet --info). after install it got changed & i could able to resolved this error.

URL for download azure SDK: - https://www.microsoft.com/net/download/dotnet-core/2.1#sdk-2.1.300-preview2

**Comment by Ma-XX-oN** [comment]
Had to install the dotnet core.  I don't know why when I upgraded from 15.6.7 to 15.9.6 the .NET Core wasn't upgraded, but it wasn't.  Had to install it from here:

https://dotnet.microsoft.com/download/dotnet-core/2.1

Something broken?  Or is this the case of the left hand not knowing what the right is doing?

**Comment by StefH** [comment]
In my case this issue was solved by removing the `global.json` file in the parent directory from the project.

Apparently, this file targeted an older = uninstalled version from the SDK.

**Comment by nhathoang989** [comment]
In my case, I resolved by installing version compatible with visual studio ( below .Net Core sdk). 
https://dotnet.microsoft.com/download

**Comment by mwpowellhtx** [comment]
Help us understand the decoder ring configuring our side by side environment supporting a VS2017 build pipeline? Specifically we are targeting things like `netstandard2.0` and `netcoreapp2.1`. Since installing VS2019, this is superseding what was once a healthy VS2017 environment. Seems like we need to introduce a `global.json` with an appropriate `sdk.version`, but we need help with the table.

We've got the following `dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by livarcocc** [comment]
@mwpowellhtx to target 2.1, you need at least a 2.1 SDK. An SDK is always capable of targeting all the TFMs that came with it. So, 2.1 can target 2.1, 2.0, 1.1 and 1.0.

**Comment by mwpowellhtx** [comment]
Thanks. We are actually tracking [a separate issue here](https://github.com/dotnet/sdk/issues/3746).

**Comment by saviour123** [comment]
When it happens like this- i use the nightly builds. They work well especially for containers. I have this issue in my ci with `mcr.microsoft.com/dotnet/sdk:3.0`. I change to this `mcr.microsoft.com/dotnet/core-nightly/sdk:3.0` and everything is fine.

**Comment by mwpowellhtx** [comment]
@saviour123 @livarcocc We are not tracking with nightly builds. We want to be on the LTS, best case, preferred. Let others cut themselves on the edges, if you will. We want to be on the best possible stable releases.

**Comment by marian-gheorghe** [comment]
I encouter the same problem with a F# project, after installing latest VS2019

My dotnet environment:
 
```
C:\Users\Marian Gheorghe>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by mwpowellhtx** [comment]
We ended up resolving our issue, or at least overcoming the immediate obstacle, by engaging with the [`Microsoft.Build.Locator` package](https://www.nuget.org/packages/Microsoft.Build.Locator/). That gets us past this issue, we think, but there's [a whole other can of worms](https://github.com/microsoft/MSBuildLocator/issues/62) which could potentially be addressed in the locator itself, topic for another forum, however.

**Comment by jzabroski** [comment]
@mwpowellhtx Can you please provide some color on what you did to fix this issue?  Just installed .net core 3.0 sdk last night and Visual Studio refuses to use it for some reason.

I tried:
* Clean solution
* Closing the solution and re-opening it
* Verifying `C:\Program Files\dotnet\` is in my PowerShell `$env:PATH` variable
* Verifying Visual Studio is x64
* Verifying `dotnet --list-sdks` lists at least one version with 3.0 or higher (3.0.100)

**Comment by mwpowellhtx** [comment]
@jzabroski We ran with the clue that `Microsoft.Build.Locator` is the way to identify the SDK properly. With that, dropped any other package references to `Microsoft.Build`, etc (sans `Locator` itself). The API is fairly self-explanatory, we think, but for it the run-time target caveats. That's via code. Not sure what that means for actual Visual Studio confusion under the hood, however.

**Comment by jzabroski** [comment]
@mwpowellhtx Sorry, I'm confused and tired of dealing with .NET SDK issues.  What did you do to solve the problem?

**Comment by mwpowellhtx** [comment]
@jzabroski I told you. Follow the bread crumbs. Out here.

**Comment by jzabroski** [comment]
Sorry, explicitly, _what did you do to solve this problem?_  Do you have a sample project on GitHub with a sha1 commit hash I can look at?  Is it something machine specific?  Are you saying you monkey-patched some files in the `C:\Program Files\` directory or elsewhere?  Saying Microsoft.Build.Locator is the breadcrumb to go fix the problem is so vague.

I don't really want to spend hours on bread crumbs.

**Comment by mwpowellhtx** [comment]
@jzabroski Welcome to the dues you have to pay for subscribing to the `dotnet` paradigm.

**Comment by jzabroski** [comment]
I have no words for your approach.  Good luck starting up your business.

**Comment by livarcocc** [comment]
@jzabroski what version of VS are you using? .NET Core 3 is only supported in VS 16.3 and up.

**Comment by jzabroski** [comment]
@livarcocc Thank you very much! That was the problem, with a slight twist: I had two versions of Visual Studio 2019 installed.  One for work and one for open source software.  I use Community Edition for open source software since I'm an extreme stickler for separation of concerns / following rules.  In this case, it seems like something doesn't work right in this scenario.  I'm not going to spend time investigating, but worth mentioning in case anyone else does something as weird as me.

**Comment by vrjaroslav** [comment]
Thank you @jzabroski  => In Visual Studio, going into Options -> Environment -> Preview features .. this helped.

**Comment by TheBoneJarmer** [comment]
Experiencing the same issue too. However, in my case it is on a TeamCity build agent. And that sucks because the agent needs to build projects using all sorts of sdk versions. Literally ranging from dotnet core 2.0 to 3.1.

For now I decided to not go for the installers but download the binaries instead and copy them to C:\Dotnet\#VERSION NUMBER#\. Have to modify some build configs but I can live with that.
