### ISSUE TITLE
Unable to find package Microsoft.DotNet.Watcher.Tools with version (>= 2.1.0-preview1-27567)

### ISSUE THREAD

**Issue by halcwb** [dotnet/cli#8744]
## Steps to reproduce
Follow the guideline as described in: https://www.natemcmaster.com/blog/2017/11/13/dotnet-watch-and-docker/

## Expected  behavior
Being able to build a docker image

## Actual behavior

> Step 7/8 : RUN dotnet restore
>  ---> Running in 2b155fd4d3ea
>   Restoring packages for /src/GiraffeDocker/GiraffeDocker.fsproj...
>   Restoring packages for /src/GiraffeDocker/GiraffeDocker.fsproj...
> /src/GiraffeDocker/GiraffeDocker.fsproj : error NU1102: Unable to find package Microsoft.DotNet.Watcher.Tools with version (>= 2.1.0-preview1-27567)
> /src/GiraffeDocker/GiraffeDocker.fsproj : error NU1102:   - Found 14 version(s) in nuget.org [ Nearest version: 2.0.0 ]
> /usr/share/dotnet/sdk/2.1.300-preview1-008174/NuGet.targets(114,5): error : Value cannot be null. [/src/GiraffeDocker/GiraffeDocker.fsproj]
> /usr/share/dotnet/sdk/2.1.300-preview1-008174/NuGet.targets(114,5): error : Parameter name: path [/src/GiraffeDocker/GiraffeDocker.fsproj]
> The command '/bin/sh -c dotnet restore' returned a non-zero code: 1
> 

## Environment data
`dotnet --info` output:
root@7e4b9e4d18ae:/src/GiraffeDocker# dotnet --info
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview1-008174/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

@natemcmaster

**Comment by dasMulli** [comment]
Did you include the nuget.config changes? You may need to add a COPY step for it to the Dockerfile so that restore will find and use it.

**Comment by natemcmaster** [comment]
@dasMulli is right. The package was a pre-release build that is available here: https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.DotNet.Watcher.Tools/2.1.0-preview1-27567

Now that 2.1.0-preview1-final is out though, I recommend using the globally installed version of dotnet-watch.

    dotnet install tool -g dotnet-watch --version 2.1.0-preview1-final

FYI - this command is only necessary in 2.1.300-preview1. In 2.1.300-preview2, dotnet-watch will be bundled by default in the CLI. See https://github.com/aspnet/Announcements/issues/290

**Comment by livarcocc** [comment]
Closing the issue since it seems to be understood and expected, in this case. If I got it wrong, just comment and I can re-activate it.
