### ISSUE TITLE
dotnet restore on 2.1 preview1 throws error instead of warning when project files are "missing"

### ISSUE THREAD

**Issue by christiansparre** [dotnet/cli#8747]
I was playing around with 2.1 preview 1 and trying to get a simple ASP.NET Core 2.1 preview1 app up and running on docker using the VS docker tools. But my `docker-compose build` failed because `dotnet restore` on 2.1 throws error `MSB3202: The project file "/src/SomeApp.SomeLib/SomeApp.SomeLib.csproj" was not found.`

But it is not isolated to docker, see the repo below where there is also a repro for 2.0 and 2.1 outside docker. And they behave very differently. Yes this is not really "normal" restore behavior, but all dotnet docker examples and the VS tooling does it this way with multistage builds and they explicitly suppress MSB3202 using `-nowarn:msb3202,nu1503`

I have not been able to find any known issues by searching the different dotnet repos. Is `dotnet restore` throwing errors, instead of warnings, a new expected behavior?

Also this is the most correct place I could find to post the issue, please redirect me elsewhere if there is a better place for it :)

## Steps to reproduce

Code to reproduce can be found here: https://github.com/christiansparre/DotNet2.1RestoreBehavior

* Create ASP.NET Core 2.1 web site
  * with Docker support (I used Linux)
* Add another project, and reference in web app (does not really matter)
* Change the Dockerfile to use the correct image versions (defaults to 2.1 that does not exist yet)
* Run `docker-compose build`

## Expected  behavior

Expected `dotnet restore` to complete with out errors or warnings because of `-nowarn:msb3202,nu1503` arguments

## Actual behavior

Restore failed with

`
/usr/share/dotnet/sdk/2.1.300-preview1-008174/NuGet.targets(239,5): error MSB3202: The project file "/src/SomeApp.SomeLib/SomeApp.SomeLib.csproj" was not found. [/src/SomeApp.sln]
/usr/share/dotnet/sdk/2.1.300-preview1-008174/NuGet.targets(239,5): error MSB3202: The project file "/src/docker-compose.dcproj" was not found. [/src/SomeApp.sln]
ERROR: Service 'someapp' failed to build: The command '/bin/sh -c dotnet restore -nowarn:msb3202,nu1503' returned a non-zero code: 1
`

## Environment data
`dotnet --info` output:
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Comment by livarcocc** [comment]
I am not sure if this has changed from warning to error. Moving it to NuGet for them to confirm.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6651
