### ISSUE TITLE
dotnet publish does not correctly implement MsDeploySkipRules

### ISSUE THREAD

**Issue by guitarzan** [dotnet/cli#8758]
I have a *.pubxml file that I use to publish my project to a web server. Doing so from within Visual Studio 2017 works flawlessly, but doing so with `dotnet publish` from the command line gives errors. I've reproduced the generated output below (but replaced personal information with "...").

## Skip rules in *.pubxml

```xml
  <ItemGroup>
    <MsDeploySkipRules Include="SkipAppSettings">
      <SkipAction>Delete</SkipAction>
      <ObjectName>filePath</ObjectName>
      <AbsolutePath>appsettings.[A-Za-z]*.json</AbsolutePath>
    </MsDeploySkipRules>
  </ItemGroup>
```
## Visual Studio steps and output

Build -> Publish; select desired profile and click "Publish"

Generated Output:

C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe -source:manifest='C:\Users\...\obj\Debug\netcoreapp2.0\PubTmp\....SourceManifest.xml' -dest:auto,ComputerName="https://...:8172/msdeploy.axd?site=...",UserName='...',Password='...',IncludeAcls='False',AuthType='Basic' -verb:sync -enableRule:AppOffline -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -skip:skipaction='Delete',objectname='filePath',absolutepath="appsettings.[A-Za-z]*.json" -setParamFile:"C:\Users\...\obj\Debug\netcoreapp2.0\PubTmp\....Parameters.xml" -useChecksum -retryAttempts=10 -retryInterval=2000 -userAgent="VSCmdLine:WTE1.0.0.0" 

## Command line steps and output

`dotnet publish -c Debug /p:PublishProfile=DevPublish /p:Username=... /p:Password=...`

Generated Output:

C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe -source:manifest='C:\Users\...\obj\Debug\netcoreapp2.0\PubTmp\....SourceManifest.xml' -dest:auto,ComputerName="https://...:8172/msdeploy.axd?site=...",UserName='...',Password='...',IncludeAcls='False',AuthType='Basic' -verb:sync -enableRule:AppOffline -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -skip:skipaction,objectname,absolutepath -setParamFile:"C:\Users\...\obj\Debug\netcoreapp2.0\PubTmp\....Parameters.xml" -useChecksum -retryAttempts=10 -retryInterval=2000 -userAgent="VSCmdLine" 

## The bug

As you can see, the generated output is nearly identical except `dotnet publish` does not correctly implement the skip rule properties:

`-skip:skipaction='Delete',objectname='filePath',absolutepath="appsettings.[A-Za-z]*.json"`
vs.
`-skip:skipaction,objectname,absolutepath`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#320
