### ISSUE TITLE
Support ProjectModel for dnx451

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#876]
Currently ProjectModel, ProjectModel.Loader and ProjectModel.Workspaces are supporting only dnxcore50. 

Are there any plans to support dnx451? (or any Full .Net framework)?

**Comment by prafullbhosale** [comment]
Ping

**Comment by bricelam** [comment]
:+1: EF will eventually also need them to support `net451`.

**Comment by muratg** [comment]
@troydai @pakrym is this still not supported?

**Comment by pakrym** [comment]
@muratg it only targets `dnxcore50`

**Comment by muratg** [comment]
Do we plan to add net451?

**Comment by pakrym** [comment]
I think we would need to, because people want it

**Comment by troydai** [comment]
I just want to clear the air here: "not supporting" `dnx451` here actually means the `ProjectModel` packages were compiled against `dnxcore50` only, right? Cause they surely can load and analyze the information of a `net451` project.

**Comment by prafullbhosale** [comment]
@troydai you're right. The packages were compiled against dnxcore50 only.

Also to give more context on why its an issue for scaffolding: 
Since scaffolding takes a dependency on ProjectModel and ProjectModel.Workspaces packages, scaffolding can be compiled against dnxcore50 only for now.

And for scaffolding to work, users need to add the scaffolding package as a dependency, which in turn restricts these project to dnxcore50 only.

**Comment by bricelam** [comment]
This could also be resolved if it simply targeted `netstandard1.2` instead...

**Comment by davidfowl** [comment]
There's an open issue to move all libraries to dotnet aka netstandard

**Comment by pranavkm** [comment]
Switching to `netstandard` is a bit more involved. I'm going to add `net451` for now.

**Comment by troydai** [comment]
Actually project __OmniSharp-Roslyn__ needs this, too.

**Comment by prafullbhosale** [comment]
@pranavkm  Just noticed that #1357 addresses only ProjectModel. Any plans for ProjectModel.Loader and ProjectModel.Workspaces?
