### ISSUE TITLE
Better error message to guide user when there is only preview version in the feed

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8762]
It is hard for user to take the right action -- 
`dotnet install tool -g t-rex --version 1.0.0-preview1-002`

Current experience:
![image](https://user-images.githubusercontent.com/6993335/37232747-265a2520-23a5-11e8-9f24-d4217bbc9a49.png)

**Comment by wli3** [comment]
@KathleenDollard

**Comment by nkolev92** [comment]
Note that each feed might have a nearest version there.

**Comment by KathleenDollard** [comment]
How about: 

```
The tool package was not found. You may need to specify the version using 

   dotnet install tool -g <packageName> --version <version>

Tool <packageName> failed to install
```

Can we put the name, like 't-rex', in both of the locations that say "<packageName>"? (you're already doing the second)

**Comment by wli3** [comment]
@KathleenDollard sorry I was late to this, we cannot parse nuget error. So we can only know failure.

CLI's error message from `Tool 't-rex' failed to install`

so is the following better?

```
Tool 't-rex' failed to install. You may need to specify the version using 

   dotnet install tool -g <packageName> --version <version>
```

**Comment by KathleenDollard** [comment]
Can we make that 

`
Tool 't-rex' failed to install. You may need to specify the version using 

   dotnet tool install -g t-rex --version <version>
`

Are there any other super common reasons an install will fail?

**Comment by wli3** [comment]
not unique name. But it is more likely to happen when the user is a producer and s/he is testing the tools.

Say I just create my tool with command `show`. I install `show`, and I will get a nuget package called show instead.
