### ISSUE TITLE
dotnet publish in Development Server - not Local Machine

### ISSUE THREAD

**Issue by gitfortee** [dotnet/cli#8766]
Hi, 

With dotnet core and it's CLI tools, is there any significance or difference in doing dotnet publish in local machine when compared to dotnet publish in a development server? 

I tend to prefer dotnet publish in the dev server - this understanding is in accordance with practices in my previous projects that you do your builds in server as opposed to your local machine. 

Kindly advise.

**Comment by livarcocc** [comment]
No. There should be no difference and the same results should reproduce in both cases. Of course, this will depend on how you handle your dependencies. If you have starred dependencies and different feeds across the machines, different packages may be found.

I CCed some folks to comment on your npm question in the other issue you filled.

**Comment by gitfortee** [comment]
@livarcocc Thanks for the response. could you please help me understand what you mean by "starred dependencies" ?

**Comment by livarcocc** [comment]
Dependencies that versions are not pinned with a specific version, like `1.0.0`, but rather, have an open version, like `*`.

**Comment by gitfortee** [comment]
@livarcocc May i take this opportunity to ask if you use specific versions or semver notations for dependencies in your projects(dependencies in package.json i mean).? Also do you upgrade your dependencies periodically or set the versions once and leave it there..? 

thanks!

**Comment by livarcocc** [comment]
I, personally, meaning for my own personal projects, use specific versions for everything. Having my dependencies being rolled forward has broken me many times.
