### ISSUE TITLE
Possible to use non-crossgen netcore app?

### ISSUE THREAD

**Issue by Genbox** [dotnet/cli#8769]
We distribute an application that is very sensitive to changes in size, and we recently updated from netcoreapp1.0 to netcoreapp2.0 - unfortunately, the size of the distribution more than tripled in size. It looks to be because the runtime.win-x86.microsoft.netcore.app package contains already compiled images for Windows, instead of the shared versions (Ref: #2541 as noted by @livarcocc). This is not the issue, just our observation.

- Is it possible to publish a version that uses the non-crossgenned version of the libraries?
- When the JIT compilation happens on client machines, can we disable any caching such that it does not save the compiled libraries on disk?

**Comment by livarcocc** [comment]
You want a self-contained app that runs against non-crossgenned libraries?
Would a framework dependent app work for you? Meaning, it would run against the installed shared framework on the machine and be executed through `dotnet app.dll` instead of `app.exe`?

Or are you asking for a `app.exe` that runs against the shared framework installed on the machine?

**Comment by Genbox** [comment]
A self-contained app with non-crossgenned libraries is essentially what we are looking for. Not exactly the most common use-case I guess since speed is often preferred over size, but in our case, we need it the other way around.

.NET Core is not installed beforehand, and it is not possible for us to install it, so we are using self-contained applications, which are already tremendously big (53 MB for a hello world). We need assemblies to be as small as possible.

**Comment by livarcocc** [comment]
I don't believe that is possible today, as I don't think we publish these packages non-crossgenned. In this case, I think it might be worth looking at https://github.com/dotnet/corert/.

The repo contains a native compiler that produces a single exe that is much reduced in size. However, I don't believe it is production ready/recommended yet. For you to try it out, you just need to add a package reference to https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.DotNet.ILCompiler and run dotnet publish.

**Comment by livarcocc** [comment]
cc @ahsonkhan

**Comment by ahsonkhan** [comment]
cc @sergiy-k, @jkotas, @KrzysztofCwalina

**Comment by jkotas** [comment]
You should look at ILLinker https://github.com/dotnet/announcements/issues/30 . It allows stripping precompiled code as well as other unnecessary bits for self-contained apps.

**Comment by jkotas** [comment]
.NET Core does not have anything like NGen service in .NET Framework that creates and maintains cache of native compiled code in the background.

**Comment by livarcocc** [comment]
I am going to close this issue as this is not something we intend to support.
