### ISSUE TITLE
File Access Error on watch run

### ISSUE THREAD

**Issue by jdenekat** [dotnet/cli#8773]
## Steps to reproduce
Checkout a project that uses "watch" on a new computer, type "dotnet watch run"

## Expected  behavior
It should build and run

## Actual behavior
The first thing it does is try to populate a local package cache at the same time it watches, leading to a file contention error.

Work-around:

First, just do "dotnet run".  It will build the local package cache.  Afterwards you can use "dotnet watch run" without file contention.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by livarcocc** [comment]
This issue was moved to aspnet/DotNetTools#406
