### ISSUE TITLE
Packing a NuSpec file

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#8775]
I'm converting a part of our build which depended on using `nuget pack` on a nuspec file directly to use `dotnet pack`. I've read a number of threads on this, including #2170, and none seem to fit the scenario I have here.

The nupkg I'm trying to build is for the Roslyn compiler tools. This is a collection of projects which are built separately. There is no single project that builds the entire set of binaries that I can attach a `<NuspecFile>` entry too. 

I've tried creating a dummy csproj file just to drive the NuSpec file argument but that's not working:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <NuspecFile>Microsoft.NETCore.Compilers.nuspec</NuspecFile>
  </PropertyGroup>
  <Target Name="Build" />
</Project>
```

Attempting to run `dotnet pack` on this project still tries to build the project. That's a huge step backwards for us. Particularly because there are ~30 nuspec files we need to migrate. Adding 30 new dummy builds is excessive here. 

How can I use a nuspec file for a project that has no reasonable build story?

**Comment by jaredpar** [comment]
Offline another user pointed out I can avoid the build by specifying `--no-build`. That gets me a step closer but now I hit the following:

/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.2.0-preview1-007622/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(204,5): error : Value cannot be null or an empty string. [/Users/jaredpar/code/roslyn/src/NuGet/Dummy.csproj]
/Users/jaredpar/code/roslyn/Binaries/Tools/dotnet/sdk/2.2.0-preview1-007622/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(204,5): error : Parameter name: value [/Users/jaredpar/code/roslyn/src/NuGet/Dummy.csproj]

Unfortunately there is no parameter named `value` at that location in the targets file.

**Comment by dasMulli** [comment]
I've had success using

```xml
<NoBulid>true</NoBuild>
```
(equivalent of `--no-build`)

Note that instead of a .nuspec, you could also use `<None>` / `<Content>`msbuild  items to specify the items to pack, giving more control over the properties that flow into the nupkg form the csproj file instead of needing to define additional `<NuspecProperties>` (msbuild property). Example: https://github.com/dasMulli/SimpleGitVersion/blob/master/DasMulli.SimpleGitVersion/DasMulli.SimpleGitVersion.csproj

Note that 2.2.0-* versions aren't recent ones (https://github.com/dotnet/announcements/issues/57) and it may be more actionable to investigate from a binlog (`/bl` argument to build/pack/*) than a stack trace.

**Comment by jaredpar** [comment]
Turns out the previous error was thrown by the NuGet task. The stack is truncated by default (why?). Can enable it by defining `%NUGET_SHOW_STACK%` 

```
Value cannot be null or an empty string. [E:\code\roslyn\src\NuGet\Dummy.csproj]
Parameter name: value [E:\code\roslyn\src\NuGet\Dummy.csproj]
System.ArgumentException: Value cannot be null or an empty string. [E:\code\roslyn\src\NuGet\Dummy.csproj]
Parameter name: value [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Versioning.NuGetVersion.Parse(String value) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Packaging.ManifestReader.ReadMetadataValue(ManifestMetadata manifestMetadata, XElement element, HashSet`1 allElements) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Packaging.ManifestReader.ReadMetadata(XElement xElement) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Packaging.ManifestReader.ReadManifest(XDocument document) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Commands.PackCommandRunner.BuildPackage() [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner) [E:\code\roslyn\src\NuGet\Dummy.csproj]
   at NuGet.Build.Tasks.Pack.PackTask.Execute() [E:\code\roslyn\src\NuGet\Dummy.csproj]
```

Looks like I don't have the version of the package specified. Probably could use a better error message here.

**Comment by jaredpar** [comment]
@dasMulli I've tried both of the no build approaches and I still end up with errors like this:

error : The file 'E:\code\roslyn\Binaries\Debug\Dlls\Bootstrap\Bootstrap.dll' to be packed was not found on disk. [E:\code\roslyn\src\NuGet\Bootstrap.csproj]

> Note that 2.2.0-* versions aren't recent ones

Understood. Have a [PR out](https://github.com/dotnet/roslyn/pull/25388) to move us to 2.1.300.

**Comment by jaredpar** [comment]
Eventually got this file working

https://github.com/dotnet/roslyn/pull/25440/files#diff-2516ac947c1fcde05dc55e774d5b343b

Can't find a way to avoid building this project though. The pack operation seems to require the DLL being on disk before it will proceed.

**Comment by dasMulli** [comment]
```xml
<IncludeBuildOutput>false</IncludeBuildOutput>
```

could help here

**Comment by tannergooding** [comment]
Yes. If you are just creating a wrapper project that is only used to pack a nuspec, you should specify: IncludeBuildOutput=false.

**Comment by tannergooding** [comment]
Additional info about the Metadata properties available can be seen here: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties

**Comment by livarcocc** [comment]
This has come up before: supporting nuspec directly without a csproj file. I suggest filling an issue on nuget/home for that.

**Comment by livarcocc** [comment]
Moving this issue to NuGet.

The ask is to have support for packing based on a nuspec file independent of a msbuild project file.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6672
