### ISSUE TITLE
Ensure the delivery of communication on "preview1 SDK packed dotnetTool cannot work on next preview or release"

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8779]
Due to preview runtime will not move forward. The conclusion of this Monday's (3/12/2018 ) meeting -- No change on product side, but make sure this message is delivered via a blog post.

**Comment by wli3** [comment]
cc @dsplaisted

**Comment by dsplaisted** [comment]
I'm concerned that people will be excited about global tools and end up publishing a bunch of them that target a preview of .NET Core 2.1.  Then when the next preview, or the RTM version is released, those packages will be more or less broken.

We could try to mitigate this with guidance that global tools should target .NET Core 2.0 until 2.1 is released.  I suspect the guidance wouldn't reach a majority of the tool authors though.

**Comment by KathleenDollard** [comment]
I am authoring a blog post that will have the following


  *   Target runtime 2.0 or expect to break at 2.1 RTM (has someone tested that this works fine, it should).
  *   Do not have a command name for your tool of "dn". We are going to block this command.
  *   Do not name your tool dotnet-. We reserve the right to take any following word, although not any brand. dotnet-xunit will still work.

Anything else?
________________________________

**Comment by wli3** [comment]
After Apphost shim, targeting netcoreapp2.0 will fail to start

**Comment by livarcocc** [comment]
@KathleenDollard Can we close this issue now?

**Comment by KathleenDollard** [comment]
Summary (to clear up changes to what I said I would do), then close:

- You can move between previews. You cannot move to RTM. 
   - In proto-preview 2 notes for cli-tools-discuss and will be in Release Notes after review
- cli-tools-discuss will have a proposal for discussion on dn, dx, dotnet- and many reserved words

Now, close :)

**Comment by livarcocc** [comment]
Closing then.
