### ISSUE TITLE
.net core framework broken after updating VS to 15.6.2

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/cli#8790]
## Steps to reproduce
* Have a project that uses `2.1.0-preview1-26216-03` and works
* Update VS to 15.6.2, with `.NET Core runtime` as an installed workflow. 
  *  .Net Core is broken after the update

.csproj excerpt from project that previously worked. This file was generated either from command line or from previous version on VS.
```
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeFrameworkVersion>2.1.0-preview1-26216-03</RuntimeFrameworkVersion>
    <NETStandardImplicitPackageVersion>2.1.0-preview1-26216-03</NETStandardImplicitPackageVersion>
```
Now it only builds, but does not run:
`dotnet run`: (`dotnet build` says that build succeeded)
```

It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview1-26216-03' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - The .NET framework can be installed from:
      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The following versions are installed:
      2.0.0 at [C:\Program Files\dotnet\shared]
      2.0.3 at [C:\Program Files\dotnet\shared]
      2.0.5 at [C:\Program Files\dotnet\shared]
      2.0.6 at [C:\Program Files\dotnet\shared]
      2.1.0-preview1-25929-02 at [C:\Program Files\dotnet\shared]
```
Sure, I'll listen to the suggestion and use a framework version installed on my system.
Modified .csproj:
```
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeFrameworkVersion>2.1.0-preview1-25929-02</RuntimeFrameworkVersion>
    <NETStandardImplicitPackageVersion>2.1.0-preview1-25929-02</NETStandardImplicitPackageVersion>
```
`dotnet run` (`dotnet buld` also shows the first two lines)
```
C:\src\sterling\src\core\Sterling.Core.csproj : warning NU1603: Sterling.Core depends on Microsoft.NETCore.App (>= 2.1.0-preview1-25929-02) but Microsoft.NETCore.App 2.1.0-preview1-25929-02 was not found. An approximate best match of Microsoft.NETCore.App 2.1.0-preview1-26216-03 was resolved.
C:\src\sterling\src\core\Sterling.Core.csproj : warning NU1603: Sterling.Core depends on Microsoft.NETCore.App (>= 2.1.0-preview1-25929-02) but Microsoft.NETCore.App 2.1.0-preview1-25929-02 was not found. An approximate best match of Microsoft.NETCore.App 2.1.0-preview1-26216-03 was resolved.
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview1-26216-03' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - The .NET framework can be installed from:
      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The following versions are installed:
      2.0.0 at [C:\Program Files\dotnet\shared]
      2.0.3 at [C:\Program Files\dotnet\shared]
      2.0.5 at [C:\Program Files\dotnet\shared]
      2.0.6 at [C:\Program Files\dotnet\shared]
      2.1.0-preview1-25929-02 at [C:\Program Files\dotnet\shared]
```

## Expected  behavior
Code builds and runs. Updating VS does not break the workflow.

## Actual behavior
.net core framework is missing.
Nuget gives misleading errors

## Environment data

`dotnet --version` output:
```
2.2.0-preview1-007622
```

`dotnet --info` output:
```
.NET Command Line Tools (2.2.0-preview1-007622)

Product Information:
 Version:            2.2.0-preview1-007622
 Commit SHA-1 hash:  045e2b7bf7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.0-preview1-007622\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-25929-02
  Build    : 328fbf0657c4e3bab243460660583c429eaae001
```
Note that I have restarted computer after updating VS

**Comment by AmadeusW** [comment]
I followed the link from the error message and downloaded `dotnet-sdk-2.1.101-win-gs-x64.exe` 
It gave me option to repair or uninstall. I repaired.
The behavior is exactly the same as outlined above, including `dotnet --info` output.

**Comment by AmadeusW** [comment]
The same errors happen when I run `dotnet new console` and `dotnet run`. How do I restore my machine to a working state?

**Comment by livarcocc** [comment]
You have 2.2.0-preview1-007622 SDK installed. That's a not supported SDK anymore given that we changed our version schemes. So, I would first suggesting that you remove that SDK from your machine.

Second, you should not pin the `RuntimeFrameworkVersion` or the `NETStandardImplicitPackageVersion` in your csproj. We used to do that in the templates and the fact you have an old 2.2.0 version is probably why that's still happening to you.

Third, because you are targeting netcoreapp2.1, you need to use our latest 2.1.300 preview version of the SDK. That's the only released version so far of the SDK that support netcore2.1.

Lastly, because you have the RuntimeFrameworkVersion pinned to a version that is not on nuget.org, you need to add a nuget feed to the list of feeds with those packages. For instance, you can use https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

I hope this helps.

**Comment by AmadeusW** [comment]
Thank you! There is no way I would have figured out all these issues by myself.
Now that I uninstalled 2.2.0 SDK and removed `*Version` entries from the csproj, the simple console app works. 

There is an issue when I add these lines to the csproj - let me know if there is an easy fix for this, or if I should create an issue about this. Looks like a regression from previous version of SDK that supported this custom output paths.
```
    <BaseOutputPath>C:\customDir\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>C:\customDir\obj\</BaseIntermediateOutputPath>
```
```
C:\src\sterling\src\test [master +4 ~6 -1 !]> dotnet build
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\src\sterling\src\test\test.csproj...
  Generating MSBuild file C:\customDir\obj\test.csproj.nuget.g.props.
  Generating MSBuild file C:\customDir\obj\test.csproj.nuget.g.targets.
  Restore completed in 1.26 sec for C:\src\sterling\src\test\test.csproj.
  test -> C:\customDir\bin\Debug\netcoreapp2.0\test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.04
C:\src\sterling\src\test [master +4 ~6 -1 !]> dotnet run

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at test.Program.Main(String[] args)
```

**Comment by livarcocc** [comment]
@dsplaisted can you comment on setting the properties above?

**Comment by dsplaisted** [comment]
@AmadeusW Can you try setting `BaseIntermediateOutputPath` in a `Directory.Build.props` file instead of in the project file itself?  I think you may be hitting the issue described in https://github.com/Microsoft/msbuild/issues/1603.

**Comment by AmadeusW** [comment]
Thank you @dsplaisted and @livarcocc , this did the trick. 
It's a huge shame that I need to add another file to get it to work. I chose .NET core in the first place to have less boilerplate than in the full .NET framework

**Comment by dsplaisted** [comment]
@AmadeusW If you don't want an additional file, you can also put it in your .csproj, see the issue I linked for how to do this.  It does make it more verbose though.

Instead of having a Directory.Build.props for each project, you can also put it in the root of your repo.  That can help make things less verbose by avoiding repeating things in each project file.  See here for more info: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build
