### ISSUE TITLE
dotnet-install.sh doesn't work on Alpine Linux v3.7

### ISSUE THREAD

**Issue by kasper3** [dotnet/cli#8792]
## Steps to reproduce

```sh
docker run -it alpine:latest

# in container
apk update
apk add curl bash

curl -O https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
chmod 777 dotnet-install.sh
./dotnet-install.sh

# errors
dotnet_install: Error: Unable to locate libunwind. Install libunwind to continue
dotnet_install: Error: Unable to locate libssl. Install libssl to continue
dotnet_install: Error: Unable to locate libicu. Install libicu to continue
dotnet_install: Error: Unable to locate libcurl. Install libcurl to continue

apk add libunwind-dev openssl-dev icu-libs curl-dev
./dotnet-install.sh


# same errors
dotnet_install: Error: Unable to locate libunwind. Install libunwind to continue
dotnet_install: Error: Unable to locate libssl. Install libssl to continue
dotnet_install: Error: Unable to locate libicu. Install libicu to continue
dotnet_install: Error: Unable to locate libcurl. Install libcurl to continue
```

## Expected  behavior
it installs dotnet.

## Actual behavior
it doesn't install dotnet.
Reason is we are using /sbin/ldconfig, which on alpine does not locate the installed libs (although i can find all of these under /usr/bin). According to maintainers in alpine's IRC channel (cc @ncopa), this script is not meant to locate the libs reliably (but its purpose is to create some symlinks). The correct way is to use ` scanelf -qS /usr/lib | grep libunwind` etc.

## Workaround

Manually install dotnet from tarball as described here: https://github.com/PowerShell/PowerShell/pull/6367#issuecomment-372765035

## Environment data
alpine linux 3.7

**Comment by kasper3** [comment]
Here is a script that was added for Julia to find system libraries: https://github.com/alpinelinux/aports/blob/334b8c94e41740b90599364f110c418ebe09dc02/community/julia/find-syslibs

Should we add the same kind of helper script next to `dotnet-install.sh` and use it in alpine? 

```sh
curl -O https://raw.githubusercontent.com/alpinelinux/aports/334b8c94e41740b90599364f110c418ebe09dc02/community/julia/find-syslibs
chmod 777 find-syslibs

./find-syslibs | grep libunwind
      libunwind-setjmp.so.0 (libc,x86-64) => /usr/lib/libunwind-setjmp.so.0.0.0
      libunwind-x86_64.so.8 (libc,x86-64) => /usr/lib/libunwind-x86_64.so.8.0.1
      libunwind.so.8 (libc,x86-64) => /usr/lib/libunwind.so.8.0.1
      libunwind-ptrace.so.0 (libc,x86-64) => /usr/lib/libunwind-ptrace.so.0.0.0
      libunwind-coredump.so.0 (libc,x86-64) => /usr/lib/libunwind-coredump.so.0.0.0
echo $?
0
```

with unavailable lib, it returns non-zero code. Note that `/sbin/ldconfig` is also a script..

**Comment by livarcocc** [comment]
dup of https://github.com/dotnet/cli/issues/8738.

**Comment by omajid** [comment]
(Not speaking on behalf of anyone but myself)

> Reason is we are using /sbin/ldconfig, which on alpine does not locate the installed libs

Perhaps we should add a flag to `dotnet-install.sh` to not check for pre-requisites, or only warn, not abort, if they are not found. Or maybe we can try both approaches in `dotnet-install.sh`: see if scanelf is around and prefer that, then fall back to `ldconfig`.

> Should we add the same kind of helper script next to dotnet-install.sh and use it in alpine?

That makes sense, at least in the short term.

One note on `scanelf` vs `ldconfig`: On most Linux distributions, `ldconfig` is part of the `libc` package, so it is very very likely to be installed by default on those systems. `scanelf` is part of `pax`, which is much less likely to be already installed. So switching from `ldconfig` to `scanelf` will break those use cases because `dotnet-install.sh` will fail on those systems because `scanelf` will not be found.

**Comment by kasper3** [comment]
ldconfig is available on alpine, but that does not return the list of installed packages. Its purpose is to create symlink to those libs. This is why Julia port in alpine is using a separate script, and julia it self is moved to using [libwhich](https://github.com/vtjnash/libwhich)

**Comment by kasper3** [comment]
@janvorli, for your info. I spent sometime chatting with Alpine packaging folks to know how they see ldconfig, they gave me the above mentioned pointers (with explanation from me). The proposal in the linked / duplicated issue can work, but IMO can be revised a bit based on how other products requiring ldconfig have managed to support Alpine. Thanks!

**Comment by johnbeisner** [comment]
@omajid 
"Perhaps we should add a flag to dotnet-install.sh to not check for pre-requisites" - try "export DOTNET_INSTALL_SKIP_PREREQS=1"
