### ISSUE TITLE
dotnet restore should skip unsupported projects

### ISSUE THREAD

**Issue by paulvanbrenk** [dotnet/cli#8793]
Copied from here: https://github.com/Microsoft/nodejstools/issues/1492#issuecomment-373016358

```
dotnet restore
/opt/atlassian/pipelines/agent/build/src/Company.Project.Client/Company.Project.Client.njsproj

(81,3): error MSB4019: The imported project "/usr/share/dotnet/sdk/2.1.101/Microsoft/VisualStudio/v15.0/Node.js Tools/Microsoft.NodejsTools.targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.
```

>But instead of crashing shouldn't it just ignore .nsproj files then? I'm justing running dotnet restore in the root of my folder. And it will not finish because there are .nsproj files there.

Thoughts, or is @starquake missing an option?

**Comment by livarcocc** [comment]
We can't ignore projects we don't know because we don't know which projects we actually don't know about. For instance, natively, the CLI does not support UAP projects, however, with the addition of a PackageReference, everything works.

We don't whitelist supported projects because there is no way for that list to be authoritative.

**Comment by paulvanbrenk** [comment]
Maybe adding a `PackageReference` would be an option for the `njsproj` too? Where can I find docs for UAP?

**Comment by livarcocc** [comment]
https://github.com/onovotny/MSBuildSdkExtras

**Comment by livarcocc** [comment]
The NuGet restore failure is being tracked here: https://github.com/NuGet/Home/issues/6651.

Also, for the reasons I stated above, this is not something that we are currently planing to change, as such I am going to close this issue.

**Comment by mdg1019** [comment]
Wow, typical attitude. You've broken VSTS builds and you're just going to ignore the issue.

**Comment by livarcocc** [comment]
@mdg1019 There is an issue filed on NuGet for this already and I have pointed to it in my comment above.
