### ISSUE TITLE
global.json tooling around sdk versions

### ISSUE THREAD

**Issue by niemyjski** [dotnet/cli#8798]
I'm not sure the best place to post this but would it be possible that when you update the nuget package to the latest version of the sdk that it could also suggest updating your global.json sdk version? It seems like everytime I update visual studio / the App/All meta package I have to go to this repo and figure out the exact sdk version and then update it. It kind of a pain.

**Comment by livarcocc** [comment]
What nuget package are yo referring to? Also, why do you need a global.json file if you are just moving to latest? The point of the SDK version in the global.json file is actually to pin you to an older version of the SDK when you also have new ones installed in your box.

Also, automatically updating it may be problematic, as we don't necessarily know which versions you may have installed in the box.

**Comment by livarcocc** [comment]
If you want to run against a specific version, then the correct way is really for you to maintain that version and update it yourself.

It is not clear to me though why updating the asp.net metapackage is forcing you to update the SDK. That should not be the case. Can you share what error you see when that happens?

**Comment by niemyjski** [comment]
I haven't come across any errors, Just wasn't sure if there was compatibility issues running older versions of the sdk with much newer versions of asp.net :-). Which is one of the reasons I opened this, I didn't know if updating say the meta package would cause issues with an older tools version and if so, should that prompt a warning banner?

**Comment by livarcocc** [comment]
We try very hard not to cause that. Specially on patch updates. So, if it is ok with you, I would like to go ahead and close this issue.

**Comment by dasMulli** [comment]
> I run nightlies as well and I want to be on an exact version.

I've been proposing a switch for global.json to limit version selection to non-preview versions. For us, this is the only reason for setting sdk versions in global.json.
https://github.com/dotnet/core-setup/issues/3623

**Comment by niemyjski** [comment]
Yeah, I'll go a head and close this, the pinning to latest stable would be great :)
