### ISSUE TITLE
Add back the LZMA for 'arm*' SDKs

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/cli#8800]
Currently, 'arm*' SDK's do not include the LZMA for performance upon extraction of the NuGet archive.

Once we have good design for opt-in/acquisition of the LZMA, it will be added back into to all 'arm*' SDKs packages.

**Comment by livarcocc** [comment]
We are actually removing the lzma in 3.0 and we believe that the real fix for this issue. So closing this one.
