### ISSUE TITLE
Add the ability to dotnet.exe to download the actual runtime

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8801]
@redknightlois commented on [Thu Mar 15 2018](https://github.com/dotnet/core-setup/issues/3837)

Probably it does exist, but I couldn't find it. 

I have been working lately with bleeding edge runtimes because I have been prototyping with hardware intrinsics. I figured out that I could use the moniker with * to force the newer runtimes, but restore is not downloading and installing the proper runtime (which can be done with xcopy).

I propose to have a ```--download-runtime ``` to ```dotnet restore``` so that it will download the appropriate daily build or even something like ```dotnet install-runtime 2.1.0-preview2-26314-02``` to download specific ones. 

---

@Petermarcu commented on [Thu Mar 15 2018](https://github.com/dotnet/core-setup/issues/3837#issuecomment-373425577)

@KathleenDollard we've talked about this before as an added action on `dotnet install`. We should get this into the next round of planning.

**Comment by livarcocc** [comment]
I was using https://github.com/dotnet/cli/issues/5594 to track that. I updated the title to make it clearer. Closing this issue as a dup.
