### ISSUE TITLE
Hash Sum mismatch on Ubuntu Trusty Packages.gz

### ISSUE THREAD

**Issue by pnc** [dotnet/cli#8804]
Super super sorry, I know y'all are mopping up after the CVE earlier this week and I bet this is just collateral damage from that. Thanks so much for all that you do.

tl;dr I'm guessing Release.gpg at <https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/dists/trusty/> didn't get updated when the new packages went out? It has an older mtime than all the other files.

## Steps to reproduce
1. Follow the instructions here to install the Microsoft GPG key and add the Microsoft apt source for Ubuntu Trusty (14.04): <https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#install-net-core-for-ubuntu-1404-ubuntu-1604-ubuntu-1610--linux-mint-17-linux-mint-18-64-bit>
2. Install dotnet-sdk-2.0.0:

         sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dotnet-sdk-2.0.0

## Expected  behavior
Package installs!

## Actual behavior
```
sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dotnet-sdk-2.0.0
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package dotnet-sdk-2.0.0
E: Couldn't find any package by glob 'dotnet-sdk-2.0.0'
E: Couldn't find any package by regex 'dotnet-sdk-2.0.0'
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign:1 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 InRelease
Hit:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:6 http://dl.google.com/linux/chrome/deb stable Release
Ign:3 http://toolbelt.heroku.com/ubuntu ./ InRelease
Hit:7 http://toolbelt.heroku.com/ubuntu ./ Release
Hit:9 https://dl.hhvm.com/ubuntu trusty InRelease
Hit:11 http://apt.postgresql.org/pub/repos/apt trusty-pgdg InRelease
Hit:12 http://ppa.launchpad.net/chris-lea/redis-server/ubuntu trusty InRelease
Hit:13 http://security.ubuntu.com/ubuntu trusty-security InRelease
Get:15 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty InRelease
Ign:16 http://ppa.launchpad.net/couchdb/stable/ubuntu trusty InRelease
Get:17 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty/main amd64 Packages [28.8 kB]
Err:17 https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty/main amd64 Packages
  Hash Sum mismatch
Hit:18 http://ppa.launchpad.net/git-core/ppa/ubuntu trusty InRelease
…
Fetched 3,168 B in 3s (795 B/s)
Reading package lists...
…
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/dists/trusty/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Environment data
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

`dotnet --info` output:
Not available, can't install. 😬

**Comment by livarcocc** [comment]
@leecow did we miss this update?

**Comment by leecow** [comment]
I don't see this on 14.04 using @pnc 's commandline. Will need to set up a Mint 17 VM to see if anything is different.

**Comment by pnc** [comment]
Hmm, I made a clean Ubuntu 14.04 EC2 instance and it does indeed install fine. The output from `apt-get update` is a little different when it lists the Microsoft sources:

```
Get:1 https://packages.microsoft.com trusty InRelease               
Get:2 https://packages.microsoft.com trusty/main amd64 Packages          
Get:3 https://packages.microsoft.com trusty/main Translation-en_US   
```

Checking to see why this is. The previous pastes are from Travis CI, so there may be something else going on in that (containerized) environment.

**Comment by pnc** [comment]
Oh, the repository files all got updated at 20:48, including Release.gpg. I think that did the trick, the package installs fine now on the original machine!

**Comment by pnc** [comment]
Before:
<img width="845" alt="screen shot 2018-03-15 at 16 43 13" src="https://user-images.githubusercontent.com/108524/37492245-09d74fe6-2877-11e8-88fb-78f797109c6b.png">

After:
<img width="785" alt="screen shot 2018-03-15 at 17 32 06" src="https://user-images.githubusercontent.com/108524/37492255-10463df6-2877-11e8-8959-50cea1ef7fc1.png">
