### ISSUE TITLE
Run WebApp inside IIS Test Scenario

### ISSUE THREAD

**Issue by kkurni** [dotnet/cli#881]
In DNX, we have issue with publishing website inside IIS & Debuging Code in VS 
https://github.com/dotnet/corefx/issues/5252

Hopefully this scenario will be covered by CLI as well.

Here is the summary in RC1 using wen publishing website to IIS.

When you publish your web project, you will get AppRoot/web.cmd
This AppRoot/web.cmd will get executed on IIS and fire DNX.exe.When publishing web project, it will create AppRoot/web.cmd
IIS will execute this Web.cmd and it will execute DNX.exe.

Unfortunately this web.cmd doesn't register your runtime (which should be on your current publish package). So it will use any runtime that you installed in your user profile.

In IIS, by default it will run your web application with "ApplicationPoolIndentiy" user, But your DNX runtime was installed under your local user. This is the root cause why you get sni.dll loader exception. Because it is depend on api-ms-win-core-stringansi-l1-1-0.dll which should be located inside your runtime.

In other cases, this will lead to the different runtime version.
E.g you published x64 version, but you set your current dnvm environment with x86.
When you run this using approot/web.cmd, this will use x86 runtime which will cause exception to load native dll

For workaround, you can modify web.cmd to add your runtime into your path.
SET "PATH=%PATH%;%~dp0runtimes\%DNX_FOLDER%\bin\;"

**Comment by natemcmaster** [comment]
+1 for testing SqlClient more. On EF7 we've continually seen sni.dll bug reports

**Comment by kkurni** [comment]
I just verified that dotnet CLI publish won't have this issue like DNX.
It will use the published runtime.
