### ISSUE TITLE
Fix help text in `dotnet remove` and 'dotnet add' commands

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/cli#8816]
## Steps to reproduce

```
dotnet add -h
```

## Expected  behavior

```
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show help information.

Commands:
  package <PACKAGE_NAME>   Add a NuGet package to the project.
  reference <PROJECT_PATH>         Add a Project to Project reference to the project.

```

similar for remove

## Actual behavior

```
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show help information.

Commands:
  package <PACKAGE_NAME>   .NET Add Package reference Command
  reference <args>         .NET Add Project to Project reference Command

```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.300-preview2-008260)

Product Information:
 Version:            2.1.300-preview2-008260
 Commit SHA-1 hash:  4f2e060ef3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300-preview2-008260/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview2-26131-06
  Build    : b13a0d5c331f374afd35ded57b9a4b4ab128864c
```

**Comment by livarcocc** [comment]
I imagine you are referring to reference <args> being the difference here? I had to practically do a diff to find it!

**Comment by KathleenDollard** [comment]
Didn't mean to be difficult 

<args> -> something more specific

Text on both reference and package improvements suggested

**Comment by peterhuene** [comment]
In summary:

`AppFullName` in `src/dotnet/commands/dotnet-add/dotnet-add-package/LocalizableStrings.resx` should change to `Add a NuGet package to the project.`

`AppFullName` in `src/dotnet/commands/dotnet-add/dotnet-add-reference/LocalizableStrings.resx` should change to `Add a project-to-project reference to the project.` (@KathleenDollard this differs from what you have above; we use 'project-to-project' in other resource strings; feel free to push back to say yours is what's best).

**Comment by KathleenDollard** [comment]
@peterhuene You are correct, thank you for catching that.
