### ISSUE TITLE
Cannot update Microsoft.NETCore.App (Implicit reference by a SDK)

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8818]
@lkfr commented on [Fri Mar 16 2018](https://github.com/dotnet/core/issues/1354)

Hi,

I am working on an Asp.Net Core 2.0 application and I cannot upgrade the Microsoft.NETCore.App package (2.0.0) to a newer version. NuGet tells me that this version is implicitely referenced by a SDK and I should update the SDK.

I am a bit puzzled as I have the last version of the SDK installed (2.1.101) and that is the one used in the build process. I cannot find any reference to an older SDK.

Am I missing something or is there some kind of problem?

The project file contains the following:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="dotnet --version" />
  </Target>

</Project>
```

Thanks!

LK

**Comment by dasMulli** [comment]
If you are building a framework-dependent application (default), there should not be a need to update the package.

Only if you are building a self-contained application - using `dotnet publish -r win-x64` or similar - creates the need to update this package.

If you do so, you can set
```xml
  <PropertyGroup>
    <RuntimeFrameworkVersion>2.0.6</RuntimeFrameworkVersion>    
  </PropertyGroup>
```
in the project file.

**Comment by Petermarcu** [comment]
There is a feature underway to fix this for self-contained applications. Is this a self-contained application? If so, the workaround above will work but you will want to remove it once the fix is in to roll forward to the latest so you keep getting all the updates.

**Comment by lkfr** [comment]
This is framework-dependent application so I will not touch this package.
Thanks for the swift answers and the clarifications, much appreciated!

**Comment by jiimaho** [comment]
> There is a feature underway to fix this for self-contained applications. Is this a self-contained application? If so, the workaround above will work but you will want to remove it once the fix is in to roll forward to the latest so you keep getting all the updates.

What's the fix and when will it be released?

**Comment by livarcocc** [comment]
The fix is to automatically roll self-contained apps forward during publishing time to the latest runtime version that the SDK knows off. The feature went out with SDK 2.1.300. Anything after that should have it.
