### ISSUE TITLE
dotnet restore exists with error code 1 instead of warning, breaks Docker multi-stage build

### ISSUE THREAD

**Issue by joergjo** [dotnet/cli#8823]
## Steps to reproduce

1. Create an ASP.NET Core project (any kind) in Visual Studio 2017 15.6.2
2. Enable Docker support
3. Build the ASP.NET Core app for Docker in **Release** mode (so that docker-compose build is being run)  

## Expected  behavior
During the Docker multi-stage build, dotnet restore will create warning MSB3202 and NU1503, but _not_ exit with an error code. The build succeeds.

```
/usr/share/dotnet/sdk/2.1.4/NuGet.targets(227,5): warning MSB3202: The project file "/src/SportsStore.Tests/SportsStore.Tests.csproj" was not found. [/src/SportsStoreOnContainers.sln]
/src/SportsStore.Tests/SportsStore.Tests.csproj : warning NU1503: Skipping restore for project 
```

## Actual behavior
dotnet restore reports MSB3202 as error, which fails the entire Docker build. 

```
/usr/share/dotnet/sdk/2.1.101/NuGet.targets(229,5): error MSB3202: The project file "/src/SportsStore.Tests/SportsStore.Tests.csproj" was not found. [/src/SportsStoreOnContainers.sln]
ERROR: Service 'sportsstore-web' failed to build: The command '/bin/sh -c dotnet restore' returned a non-zero code: 1
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```
## Remarks
This causes _all_ Docker multi-stage builds that follow this approach to fail:
```
FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY WebApplication1.sln ./
COPY WebApplication1/WebApplication1.csproj WebApplication1/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/WebApplication1
RUN dotnet build -c Release -o /app
```

So if any project file referenced in the solution file is not available when `docker build` runs, like .dcproj or any unit test project that doesn't need to be part of the container image, `docker build` will now suddenly fail with the SDK 2.1.101.

Note that the latest templates for ASP.NET Core Docker support even suppress warnings MSB3202 and NU1503...

**Comment by livarcocc** [comment]
Dup of https://github.com/NuGet/Home/issues/6651.

**Comment by joergjo** [comment]
Thanks for the pointer! 
`dotnet restore -p:RestoreUseSkipNonexistentTargets=false -nowarn:msb3202,nu1503`
works fine as workaround.

**Comment by livarcocc** [comment]
Sorry for regression. This is hitting quite a few people and we are talking about ways to mitigate this without losing the gains we had from the features that caused it. It is convoluted.

Glad the workaround unblocked you.
