### ISSUE TITLE
.NET Core application name does not change in taskbar?

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8832]
@mudasir111 commented on [Wed Mar 14 2018](https://github.com/dotnet/core/issues/1351)

.NET Core application name does not change in taskbar?

Even after the self contained publishing the process name doesn't change, the assembly name property seems to work only on changing the .dll file name.

I have four applications running, but for each process it shows dotnet as shown in the picture

![attachment](https://user-images.githubusercontent.com/25227248/37447441-223afbf2-2848-11e8-99af-5f4ae191a37a.PNG)

---

@svick commented on [Thu Mar 15 2018](https://github.com/dotnet/core/issues/1351#issuecomment-373345760)

I think this is a duplicate of https://github.com/dotnet/core-setup/issues/2007.

---

@Petermarcu commented on [Thu Mar 15 2018](https://github.com/dotnet/core/issues/1351#issuecomment-373487316)

@steveharter @nguerrera is this something for the host or something that needs to be fixed in publish. Host doesn't know the name of the app until publish.

---

@Petermarcu commented on [Thu Mar 15 2018](https://github.com/dotnet/core/issues/1351#issuecomment-373490032)

I think the different here is that for a self-contained application or any application where the host is renamed to match the program name, we should be able to give something better in task manager.

---

@Petermarcu commented on [Sat Mar 17 2018](https://github.com/dotnet/core/issues/1351#issuecomment-373938344)

@nguerrera @livarcocc I'm going to move this to the CLI repo because I think this is about what happens when the apphost exe is renamed and updated to "look like the app".

**Comment by livarcocc** [comment]
This is not what I see at all. Below you can see that executing the Self-contained .NET Core application results in it showing up with the appropriate name under Task manager.

![capture3](https://user-images.githubusercontent.com/367554/37618369-4b7dcc78-2b73-11e8-9db3-b917f5669bee.PNG)

Please, confirm that you are executing your self-contained app through the generated exe and not through ` dotnet <path_to_app_dll>`.

Lastly, I attempted this with the latest 2.1.300-preview1 SDK available at dot.net.

If you can still repro this issue using the SDK above and the steps I described above, then comment with additional information and we can re-activate this issue.

**Comment by mudasir111** [comment]
I achieved the goal, by using a third party tool to change name in taskbar of a core exe application after the  self-contained publishing. Now the question is  it the right way to do it and does it effect the functionality of the application. I just tried it a little sample application, it seems to work fine.

**Comment by mudasir111** [comment]
The issue was in core 1.0 and 1.1, the Core 2 works as we want to be.
