### ISSUE TITLE
Used in the DOCKER dotnet restore error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/cli#8834]
_From @Loongle on September 6, 2017 14:3_

I built Jenkins in docker container, then entered the container to install the dotnet core 2.0 SDK, and when I used the dotnew new console - o hwapp in container, there was an error: 
`Running 'dotnet restore' on hwapp/hwapp.csproj...
Segmentation fault (core dumped)
`

_Copied from original issue: dotnet/coreclr#13809_

**Comment by livarcocc** [comment]
@RussKeldorph I am not sure this is a CLI issue. The CLI is entirely IL and it should not seg fault. This issue is happening in the runtime layer, not on the CLI layer.

Should I re-activate the original issue?

**Comment by RussKeldorph** [comment]
@livarcocc My thinking was that since the user was interacting with a CLI builtin, the issue should start in this repo.  If it is determined that the scenario is supported, the behavior still repros, and it's a bug in another layer, we can move it to the appropriate repo with more details.

Feel free to re-open the original issue if you're confident it represents a runtime bug.  I wasn't certain the scenario was supported or that the CLI couldn't be misconfiguring the runtime given the target environment. 

@janvorli FYI

**Comment by janvorli** [comment]
@Loongle did you have all the required dependencies installed in the docker container?

**Comment by Loongle** [comment]
@janvorli The problem is that when building Jenkins Dockerfile, I didn't give the right permissions.

**Comment by Loongle** [comment]
但是我最后解决的方式是通过 visual studio 建立 Docker 支持项目。利用 yml 构建才得以成功.原来的方法是不行

**Comment by Loongle** [comment]
But my final solution was to build a Docker support project through visual studio.Using the yml build is successful. The original method is not good.

**Comment by Loongle** [comment]
It doesn't matter. It's an experience.Please choose to close the problem.

**Comment by RussKeldorph** [comment]
@Loongle Thanks for following up.
