### ISSUE TITLE
Webapi template - logging set up incorrectly for Development

### ISSUE THREAD

**Issue by jankalfus** [dotnet/cli#8835]
There's a problem with the webapi template when it comes to logging. It sets up the json settings in a way a programmer does not expect - info and debug messages don't get logged in Development environment.

## Steps to reproduce
run `dotnet new webapi`
Then put some logging using `ILogger.LogInformation()` in the app.
run `dotnet run`

## Expected  behavior
Debug- and higher-level log messages from project get logged. Information- and higher-level System and Microsoft log messages get logged.

## Actual behavior
Since `appsettings.Development.json` and `appsettings.json` files get merged in Development environment and the settings from `appsettings.json` for Logging take precedence (more specific) over those in `appsettings.Development.json` (less specific), **only Warning- and higher-level messages in Development environment get logged**.

This is the content of `Logging` section in `appsettings.Development.json`:
```
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
```
and this is the content of `Logging` section in `appsettings.json`:
```
"IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by livarcocc** [comment]
This issue was moved to aspnet/templating#373
