### ISSUE TITLE
crossgen_roslyn.sh needs to use -readytorun option

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#884]
Same as crossgen_roslyn.bat for Windows. This option is needed to allow servicing.

**Comment by jkotas** [comment]
Related: #90

**Comment by jkotas** [comment]
Blocked by: https://github.com/dotnet/coreclr/issues/2710

**Comment by davidfowl** [comment]
@jkotas It's so much slower though..

**Comment by janvorli** [comment]
Unblocked by https://github.com/dotnet/coreclr/pull/2716

**Comment by blackdwarf** [comment]
@davidfowl @jkotas @janvorli what is the status of this?

**Comment by jkotas** [comment]
crossgen was changed to generate readytorun images by default, so the best way to get this fixed is to pickup a new coreclr build that has the change in defaults.

BTW: Do not forget to remove `ComPlus_ReadyToRun=0` workaround when you pick up the new coreclr build.

**Comment by livarcocc** [comment]
We run crossgen with -readytorun.
