### ISSUE TITLE
How to use Microsoft.DotNet.Build.Tasks in csproj (or CLI) such as ZipFileCreateFromDirectory?

### ISSUE THREAD

**Issue by jarrettv** [dotnet/cli#8847]
## Steps to reproduce

  ```<UsingTask TaskName="ZipFileCreateFromDirectory" AssemblyName="Microsoft.DotNet.Build.Tasks"/>
<Target Name="Zip"><ZipFileCreateFromDirectory/></Target>```

## Expected  behavior

Fail asking for SourceDirectory and DestinationArchive

## Actual behavior
error MSB4062: The "ZipFileCreateFromDirectory" task could not be loaded from the assembly Microsoft.DotNet.Build.Tasks. Could not load file or assembly 'Microsoft.DotNet.Build.Tasks, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.


## Environment data
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Comment by livarcocc** [comment]
I imagine you mean the task from the Microsoft.DotNet.Cli.Tasks.dll? That's a tasks assembly used by the CLI build itself and not distributed as part of the SDK.

We have no plans at the moment to make the CLI's own build tasks part of the product. Maybe you can just take the code and make your own task assembly containing this task you want? Of course, at that point, this will not really be supported by us, you will just be "forking" that piece of the code.

**Comment by nguerrera** [comment]
We should probably give that assembly a less official sounding name. It's nearly the same as the sdk tasks dll. I got confused for a second.

**Comment by livarcocc** [comment]
I think the error message above is giving the SDK build tasks name, not the CLI one actually. Not sure why that's happening though.

**Comment by nguerrera** [comment]
Guessing there's a usingtask with that name in the part of the repro not shown. That isn't the SDK name: there's DotNet vs. NET.Sdk.

**Comment by jarrettv** [comment]
Can I suggest `dotnet publish --zip` option? I'll look into a task, project tool, or perhaps even a global tool.

**Comment by livarcocc** [comment]
I don't think it makes that much sense. We would need to support both a Zip and a TarBall as well. I think I would rather leave that to other parts of your build system to take care of.
