### ISSUE TITLE
`dotnet publish` leaves a dangling process even with "/p:UseSharedCompilation=false"

### ISSUE THREAD

**Issue by nategraf** [dotnet/cli#8849]
On the newest dotnet client (2.1.300-preview3-008384), when I publish certain templates, it leaves a dangling process. I am using `/p:UseSharedCompilation=false` to prevent the shared compiler from starting and it works for most templates. The template I have been able to confirm this issue with is "mvc"

Based on the ["size on disk" Jenkins build](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/sizeondisk_x64/), this issue was introduced between March 6th and March 15th

## Steps to reproduce
1. `dotnet new mvc`
2. `dotnet restore`
3. `dotnet publish /p:UseSharedCompilation=false`
4. `ps dotnet`

## Expected  behavior
`ps dotnet` should not identify any dotnet processes running on the system

## Actual behavior
`ps dotnet` identifies a single dotnet process running

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview3-008384
 Commit:    4343118151

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Temp\sod257e8f47-5ab3\.dotnet\sdk\2.1.300-preview3-008384\

Host (useful for support):
  Version: 2.1.0-preview3-26319-04
  Commit:  939333dbc8

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4-preview-007239 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007354 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007363 [C:\Program Files\dotnet\sdk]
  2.1.100-preview-007391 [C:\Program Files\dotnet\sdk]
  2.1.300-preview3-008384 [C:\Temp\sod257e8f47-5ab3\.dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30338 [C:\Temp\sod257e8f47-5ab3\.dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30338 [C:\Temp\sod257e8f47-5ab3\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26313-01 [C:\Temp\sod257e8f47-5ab3\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26319-04 [C:\Temp\sod257e8f47-5ab3\.dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
This is likely the Razor server.

cc @rynowak to confirm. If so, I will move the issue to aspnet.

**Comment by rynowak** [comment]
This is almost certainly us. Hadn't thought of it until now, but we should respect `UseSharedCompilation` since people already know about that setting.

**Comment by nategraf** [comment]
Is this something that is tested for in an automated way?

**Comment by livarcocc** [comment]
@rynowak do you want to move this issue somewhere?

**Comment by nategraf** [comment]
@rynowak This is currently breaking our [size-on-disk "benchmark"](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/sizeondisk_x64/) runs. Could I get some idea of how quickly this can be fixed?
