### ISSUE TITLE
An assembly specified in the application dependencies manifest was not found

### ISSUE THREAD

**Issue by wh1t3cAt1k** [dotnet/cli#8851]
## Steps to reproduce

- Unpack the following project in VS Code: [CoreRestaurants.zip](https://github.com/dotnet/cli/files/1830653/CoreRestaurants.zip)
- `cd` into the directory
- `dotnet build`
- `dotnet ef dbcontext list`

## Expected  behavior

I see the dbcontexts list or a meaningful error.

## Actual behavior

I see an obscure error
```
Error:
  An assembly specified in the application dependencies manifest (CoreRestaurants.deps.json) was not found:
    package: 'CoreRestaurants', version: '1.0.0'
    path: 'CoreRestaurants.dll'
```
## Workaround

It took me 2 days to figure out that the problem might be in access rights, and running the above stuff with `sudo` fixes the issue.

In hindsight it is surprising how I didn't guess it from the outset, but hey, everything is obvious in hindsight.

My point is that the error could be more descriptive so that people spend less time figuring out what went wrong. Perhaps there should be additional explicit checks made by the tool.

*Note*: the same issue with `dotnet ef migrations list`.

## Environment data

I into the `~/Projects/CoreRestaurants` folder.

I run Mac OS 10.13.2 (17C88).

`dotnet --info` output:

```
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by livarcocc** [comment]
It is not clear to me if this is coming from EF trying to load the assemblies in the deps.json or if this is the host trying to load assemblies from the deps.json. If the latter, please, move the issue to core-setup.

Assuming it is the former, I am moving this to EF.

**Comment by livarcocc** [comment]
This issue was moved to aspnet/EntityFrameworkCore#11367
