### ISSUE TITLE
How to create a .net framework class library in new .csproj formate

### ISSUE THREAD

**Issue by Varorbc** [dotnet/cli#8857]
How to create a .net framework class library in new .csproj formate？

**Comment by akamsteeg** [comment]
Just create a netstandard library from the "new project" menu and replace the value of <Target framework> in the .csproj with a full .NET framework TFM like "net45" or "net47". You can do that by right-clicking the project in Visual Studio and choose "Edit *.csproj".

**Comment by akamsteeg** [comment]
I missed that this is in the CLI repo, but most of my comment still applies. Just edit the . csproj as described in an editor and that's it. :)
