### ISSUE TITLE
dotnet run fails when directory contains spaces (Windows)

### ISSUE THREAD

**Issue by dburriss** [dotnet/cli#886]
When running a dotnet application from command line with the "run" command it fails with "Unrecognized command or argument 'xxx' where xxx is the 2nd work in the folder name.

*Repro:*
1. md "A Test"
2. cd "A Test"
3. dotnet new
4. dotnet restore
5. dotnet run
Result: Unrecognized command or argument 'Test'

dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by piotrpMSFT** [comment]
@brthor has an incoming fix for this issue!

**Comment by brthor** [comment]
#525

**Comment by piotrpMSFT** [comment]
This was fixed by #525

**Comment by dburriss** [comment]
Is the msi DL a nightly build or will this only be available in February?

**Comment by brthor** [comment]
@dburriss The msi will build after every commit
