### ISSUE TITLE
Fedora 26 executable not in the package

### ISSUE THREAD

**Issue by lassade** [dotnet/cli#8868]
## Steps to reproduce
1. Install dotnet cli for fedora following the instructions in [here](https://www.microsoft.com/net/learn/get-started/linux/fedora26)
2. Try to run the `dotnet` command

I Also downloaded the .rpm package to inspect its contents, there is no dotnet executable inside only a dll with the same name.

## Environment data
`dotnet --info` output:
`bash: dotnet: command not found`

`# dnf install dotnet-sdk-2.1.101` output:
`Last metadata expiration check: 0:47:55 ago on Thu 22 Mar 2018 11:18:16 AM -03.`
`Package dotnet-sdk-2.1.101-2.1.101-1.x86_64 is already installed, skipping.`
`Dependencies resolved.`
`Nothing to do.`
`Complete!`

**Comment by omajid** [comment]
Can you tell us the output of the following commands:

- `echo $PATH`
- `which dotnet`
- `dnf list --installed 'dotnet*'`
- `rpm -ql dotnet-host-2.0.6` (or whatever the name of the latest `dotnet-host` package is)
- `ls /usr/share/dotnet`

**Comment by lassade** [comment]
Thanks for the reply `/usr/share/dotnet` wasn't in `$PATH`, adding soves it.

**Comment by omajid** [comment]
Um. `/usr/share/dotnet` isn't supposed to be in $PATH. If you have to add it, it sounds like a bug.

This looks like https://github.com/dotnet/core-setup/pull/3578, actually.

**Comment by lassade** [comment]
Oh. reinstalling by doing `sudo dnf reinstall dotnet-host` create the symlink once again, `which dotnet
` outputs: `/usr/bin/dotnet`. Guess I will have to wait until the next update to see if the link will be deleted.
