### ISSUE TITLE
Visual Studio Build Issue

### ISSUE THREAD

**Issue by Fosol** [dotnet/cli#887]
More and more often I'm running into this issue when attempting to build my projects.

When I build it fails and displays the following error.
```
Error		Could not find a part of the path 'C:\Users\[username]\.dnx\packages\LIS.DAL.Models\1.0.1.2\lib\dnx451\LIS.DAL.Models.dll'.
```
I can run the dnu build command myself and it all works fine.

I've noticed some kind of relationship between within Visual Studio checking off the project property "Produce outputs on build" within Visual Studio and the creation of a "/lib/" folder.  I do not want this checked on.  It causes other problems I've already solved by turning it off.  Related to this "/lib/" folder issue is that when I publish my libraries manually they do not include that folder in the output.

**Comment by Fosol** [comment]
Looks like an issue with "dnu pack" running for multiple projects within a single open solution within Visual Studio - while you are doing an MsBuild...  Just a few variables...  

I think it boils down to something related to Visual Studio locking folders and files.

**Comment by piotrpMSFT** [comment]
Does this repro on CLI or only DNU? For CLI build we recently decoupled pack from compile. This enables us to sign once and ship the same binaries everywhere. By default, pack will recompile each dependency for each target, so there can be concurrency issues if doing pack in parallel.

**Comment by Fosol** [comment]
dnu only - sorry!

**Comment by piotrpMSFT** [comment]
Okie! As you transition to CLI please let us know if this creeps up again!
