### ISSUE TITLE
[ARM32 SDK] Profiling NetCore apps

### ISSUE THREAD

**Issue by raffaeler** [dotnet/cli#8873]
Please provide a way to measure performance of a NetCore app on ARM platform running Linux.
The best resource I am aware of is Sasha Goldshtein blog: [http://blogs.microsoft.co.il/sasha/2017/02/27/profiling-a-net-core-application-on-linux/]()

Please improve the developer experience by:
- giving guidance and tooling for doing perf measurements (on both local and remote machines)
- enable perf measurement when remote debugging from Windows on the remote device

**Comment by livarcocc** [comment]
We have no plans to add any kind of tooling support to the .NET Core SDK for this at the moment. As for guidance, I don't believe this issue does not belong in this repo, though I am not sure where it should go. Maybe dotnet/coreclr

**Comment by Petermarcu** [comment]
@valenis do you know where we should have an issue tracking profiling and performance tools and guidance. Over time, I would imagining them getting into the SDK if they integrate well with the CLI.
