### ISSUE TITLE
Restore fails in restrictive environments

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/cli#8874]
## Steps to reproduce
Upload a 2.1.300 version of the SDK to an Azure Web App
Change the deploy script to use your dotnet for restore
Git deploy a 2.1 app

## Expected  behavior
Restore and publish to work and site to be functioning as expected

## Actual behavior
remote: Handling ASP.NET Core Web Application deployment.
remote: Failed exitCode=1, command=dotnet restore "D:\home\site\repository\testapp.csproj"
remote: An error has occurred during web site deployment.
remote: System.Security.SecurityException: Requested registry access is not allowed.
remote:    at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
remote:    at System.Environment.SetEnvironmentVariableCore(String variable, String value, EnvironmentVariableTarget target)
remote:    at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
remote:    at Internal.Runtime.Augments.EnvironmentAugments.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
remote:    at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
remote:    at Microsoft.DotNet.ShellShim.WindowsEnvironmentPath.AddPackageExecutablePathToUserPath()
remote:    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.AddPackageExecutablePath()
remote:    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
remote:    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNotice
Sentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, CliFolderPathCalculator cliFolderPathCalculator, Boolean hasSuperUserAccess)
remote:    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
remote:    at Microsoft.DotNet.Cli.Program.Main(String[] args)
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.

## Environment data
SDK 2.1.300-preview2-008367
Azure Web App

**Comment by wli3** [comment]
We need to catch that specific exception at this line

https://github.com/dotnet/cli/blob/495630fe9782ae70db2547b2474ba332352cfd1d/src/dotnet/ShellShim/WindowsEnvironmentPath.cs#L36

I don't know if we need to add a different sentinel(empty file as a flag) just for windows path. Currently it relies on first run's sentinel file, if there is no, it will try to add to path it everytime. And in this case we should write one and stop the trying.

`dotnet install` will display manual adding instruction if tools path is not in env:path. So there is back up plan.

**Comment by peterhuene** [comment]
I think the first-run sentinel is fine.  We should only attempt this once, and if it fails in this manner, warn the user and move on.

I'll have a PR for this up today.

**Comment by peterhuene** [comment]
Fixed with #8886.
