### ISSUE TITLE
Dotnet add dont autocomplete like Nuget in VS Communite.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8879]
@ucavalcante commented on [Thu Mar 22 2018](https://github.com/dotnet/core/issues/1374)

Dotnet add cant do autocomplete like git or nuget when we type tab button.

I'm believe this will be a very valiable resource for improve speed up our coding without search whats wrong when we install packages.

**Comment by livarcocc** [comment]
We already have support for auto-complete in the CLI.

See here for more information on how to enable it: https://github.com/dotnet/cli/blob/master/Documentation/general/tab-completion.md

From the issue, it seems you are asking for the functionality, which exists as described above. If you are already using and what a difference in behavior, please let us know.

**Comment by ucavalcante** [comment]
Tks for this solution its worked but very nicely if this thing will be native without edit any file.
