### ISSUE TITLE
Question to help understand the purpose of the tools using a real scenario

### ISSUE THREAD

**Issue by AdamDotNet** [dotnet/cli#888]
In my company, we have performance critical portions of our code that are getting a little old, they are COM C++. The desire is to update the API to be more modern, both the algorithms and to get off COM. The GUI of the application is currently WinForms, with hopes to move to WPF, full .Net framework 4.6.1.

Performance is still key, but in the best case scenario, we could still write it in C#. So I thought, what about .Net Native?

So my question is, am I able to use the dotnet cli tools to compile a class library to
* target net461 or dotnet5.4 in project.json
* use the --native compiler option
* reference the result in a .Net 4.6.1 WPF application

In toying with the current release of the cli, I found that it always errored out when I removed "emit entry point" in my project.json, but only during the native compilation phase. Is it even intended to make a .dll instead of .exe using the .Net Native toolchain? Would such a .dll be reference-able in a managed application, perhaps using [DllImport]?

**Comment by piotrpMSFT** [comment]
@blackdwarf

**Comment by piotrpMSFT** [comment]
@AdamDotNet 
- yes, you can target net461
- --native is not yet available. We don't have a published timeline.
- yes, you can reference net461 libs from net461 apps.
