### ISSUE TITLE
Cannot dotnet pack a .NET Standard library referencing xunit

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/cli#8891]
## Steps to reproduce

1. Create a .NET Standard Library (2.0)
2. Add a package reference to xunit (the testing framework)
3. Try to create a package either with `dotnet pack` or using the "Pack" menu from Visual Studio

## Expected  behavior

The package (nupkg) is generated

## Actual behavior

Nothing is created.

## Environment data
`dotnet --info` output:

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17127
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by livarcocc** [comment]
This is by design.

The `xunit` package sets a property called `IsTestProject` to true and that causes the Pack targets to, in turn, set `IsPackable` to false.

If you need to get around this you can have your project file look like this or something similar:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.3.1" />
  </ItemGroup>

</Project>
```
