### ISSUE TITLE
.Net Core SDK is not able to install it in Ubuntu 16.04

### ISSUE THREAD

**Issue by sch0bert** [dotnet/cli#8903]
## Steps to reproduce
I followed the instructions given in the next microsoft web page:
https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current

- curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
- sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
- sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
- sudo apt-get install apt-transport-https
- sudo apt-get update
- sudo apt-get install dotnet-sdk-2.1.101
## Expected  behavior
Successful .Net Core SDK

## Actual behavior
After running the next command:
sudo apt-get install dotnet-sdk-2.1.101
I get the next messages:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1.101
E: Couldn't find any package by glob 'dotnet-sdk-2.1.101'
E: Couldn't find any package by regrex 'dotnet-sdk-2.1.101'

## Environment data
`dotnet --info` output:
dotnet: command not found

![image](https://user-images.githubusercontent.com/26800631/37927071-458c410e-30f6-11e8-97dd-81cd9d86e72d.png)

**Comment by livarcocc** [comment]
I believe we are in the process of pushing these packages.

@leecow

**Comment by leecow** [comment]
@sch0bert - there have been a few changes to the product feeds over the last few releases and updates need to be made to the feed set up instructions. 

Replace

`deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main`

with

`deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main`

in you /etc/apt/sources.list.d/dotnetdev.list and you should be good to go for 2.1.101.

**Comment by sch0bert** [comment]
@leecow I did what you said and I got the same fail result.

**Comment by leecow** [comment]
Sorry about that, got in a hurry and typed something that made no sense ;-)

dotnetdev.list should point to `deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main`

Here is mine to double-check

```
$ cat /etc/apt/sources.list.d/microsoft-prod.list 
deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
```

... and output of apt search after running apt-get update.

```
$ apt search dotnet-sdk-2.1
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1.100/xenial 2.1.100-1 amd64
  Microsoft .NET Core SDK - 2.1.100

dotnet-sdk-2.1.101/xenial 2.1.101-1 amd64
  Microsoft .NET Core SDK - 2.1.101

dotnet-sdk-2.1.102/xenial 2.1.102-1 amd64
  Microsoft .NET Core SDK - 2.1.102

dotnet-sdk-2.1.2/xenial 2.1.2-1 amd64
  Microsoft .NET Core SDK - 2.1.2

dotnet-sdk-2.1.3/xenial 2.1.3-1 amd64
  Microsoft .NET Core SDK - 2.1.3

dotnet-sdk-2.1.300-preview1-008174/xenial 2.1.300-preview1-008174-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.4/xenial 2.1.4-1 amd64
  Microsoft .NET Core SDK - 2.1.4
```

**Comment by sch0bert** [comment]
Is still failing after changing that...

**Comment by leecow** [comment]
Odd - files are clearly visible at https://packages.microsoft.com/ubuntu/16.04/prod/pool/main/d/. 

Short of re-confirming the contents of your .list file, you could just rename it and use the .deb config file which is what the updated instructions will use.

```
wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
````

**Comment by sch0bert** [comment]
I'm still getting the same error,

I'm running the next steps now with your directions and I get the same result:

curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg &&
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg &&
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'  &&

sudo apt-get update -y 
sudo apt-get install dotnet-sdk-2.1.101

I even downloaded the .deb file from the address given and after trying to run it, I get the next result:

![image](https://user-images.githubusercontent.com/26800631/37937230-04131c50-3116-11e8-8de3-ff4944530045.png)

**Comment by sch0bert** [comment]
Hello, this is a friendly reminder.

**Comment by omajid** [comment]
.NET Core is not supported on i386 platforms: https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md#linux. We only support x86_64/amd64/x64.

**Comment by sch0bert** [comment]
oohh... that's sad... then we can close it.
