### ISSUE TITLE
Enable bash autocompletion on CLI install

### ISSUE THREAD

**Issue by stevedesmond-ca** [dotnet/cli#8911]
I only just learned about the .NET CLI having bash autocomplete from @shanselman's blog post today (see [this Twitter thread](https://twitter.com/shanselman/status/978712127476088833)).

It would be great if this were enabled by default when installing the CLI. Not sure if that would mean appending to `~/.profile`/`~/.bashrc`/etc. or if there's a better system- or app-centric way to do it (e.g. hook into the more official [bash-completion](https://github.com/scop/bash-completion) project for Linux)...

**Comment by livarcocc** [comment]
I bit hidden, but this is a dup of https://github.com/dotnet/cli/issues/620.
