### ISSUE TITLE
With .zip installer, message is not localized when install global tool succeed

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#8918]
## Steps to reproduce
1. Prepare a windows 10 OS with language SC
2. Download zip installer and unzip, add this path to system path
3. run dotnet new console -n test-global-tools. 
4. edit project file, add line <PackAsTool>true</PackAsTool> in PropertyGroup session. 
5. run dotnet pack 
6. setup local nuget feed and copy paste result bin/Debug/test-global-tools.1.0.0.nupkg in to it 
7. run dotnet install tool -g test-global-tools 
8. observe the instruction printed on the screen 

## Expected  behavior
1. Message should be localized normally

## Actual behavior
1. Message still shows in English
![image](https://user-images.githubusercontent.com/1578239/38005802-f2e1bc1a-3274-11e8-9812-9e345ecad063.png)

##Note
1. This issue is not reproduced when using .exe installer.
![image](https://user-images.githubusercontent.com/1578239/38005479-5afaa05c-3273-11e8-890a-a68d2e194dff.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008396
 Commit:    400e670faa

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\dotnet-sdk-2.1.300-preview2-008396-win-x64\sdk\2.1.300-preview2-008396\

Host (useful for support):
  Version: 2.1.0-preview2-26325-03
  Commit:  95f1b0b97f

.NET Core SDKs installed:
  2.1.300-preview2-008396 [C:\dotnet-sdk-2.1.300-preview2-008396-win-x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30457 [C:\dotnet-sdk-2.1.300-preview2-008396-win-x64\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30457 [C:\dotnet-sdk-2.1.300-preview2-008396-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26325-03 [C:\dotnet-sdk-2.1.300-preview2-008396-win-x64\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by wli3** [comment]
@nguerrera did we have all the loc for zip installation? I remember "pay to play" it is about different installers at all?

**Comment by livarcocc** [comment]
I had missed this to being with. In order to save space, the decision that was made by Scott back when we were shipping 2.0 was that the tarballs/zips where going to be English only and folks needed to acquire a second file (language pack) to localize their xcopy installs. Given that, this behavior is by design.

**Comment by livarcocc** [comment]
@yuki233 one last question, other pieces of the CLI should be unlocalized as well, not just tools. Can you confirm that?
