### ISSUE TITLE
Warning message indicating that format version is missing should not occur if the installation tool was packed with preview 2

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#8924]
## Steps to reproduce
1.	run dotnet new console -n test-global-tools. 
2.	edit project file, add line <PackAsTool>true</PackAsTool> in PropertyGroup session. 
3.	run dotnet pack 
4.	setup local nuget feed and copy paste result bin/Debug/test-global-tools.1.0.0.nupkg in to it 
5.	run dotnet install tool -g test-global-tools 
6.	Observe the instruction printed on the screen 

## Expected  behavior
Installation succeed without any warning message

## Actual behavior
Warning message is displayed  indicating that format version is missing
![image](https://user-images.githubusercontent.com/1578239/38071877-69b3d2e2-3356-11e8-83f0-6a391341e4c9.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008407
 Commit:    5a5e35cf02

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview2-008407/

Host (useful for support):
  Version: 2.1.0-preview2-26326-03
  Commit:  01c8d79c6a

.NET Core SDKs installed:
  2.1.300-preview2-008407 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26326-03 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by wli3** [comment]
@yuki233 I tried but I cannot repo it.  There is no error message. And there is version property in the setttings.xml which will trigger the warning when missing. Maybe there is an old package with the same name? Or maybe the code did not flow to CLI when the test was performed.

Please reopen it if you see it again.

![image](https://user-images.githubusercontent.com/6993335/38582659-595602ee-3cc5-11e8-9005-2586ea165b0d.png)

**Comment by yuki233** [comment]
@wli3  This warming message is still shown when run "dotnet tool install -g doTNetsay". Please help to confirm if it is expected.
![image](https://user-images.githubusercontent.com/1578239/38592812-d00bbb3a-3d70-11e8-8081-2a4d466bff29.png)

**Comment by wli3** [comment]
Yes, this is expected. dotnetsay haven't been updated yet. https://github.com/dotnet/core/issues/1382
