### ISSUE TITLE
The error text should not indicating version issue when conflicting shim exists

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#8927]
## Steps to reproduce
1. Setup tools local feed. 
2. Prepare 2 tools that have different package ID but same command name. Add <ToolCommandName>mytool2</ToolCommandName> after <PackAsTool>true</PackAsTool> to customize nameSetup tools local feed. Prepare 2 tools that have different package ID but same command name. Add <ToolCommandName>mytool2</ToolCommandName> after <PackAsTool>true</PackAsTool> to customize name
3. Run dotnet tool install -g mytool1 
4. Run dotnet tool install -g mytool2

## Expected  behavior
Tool mytool2 installation failed with clear error indicates "tool with the same name already existed". 

## Actual behavior
Tool mytool2 installation failed with error indicating version issue. 
![image](https://user-images.githubusercontent.com/1578239/38072375-8ba3aa2e-3358-11e8-81c0-4687affc91b7.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008407
 Commit:    5a5e35cf02

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview2-008407/

Host (useful for support):
  Version: 2.1.0-preview2-26326-03
  Commit:  01c8d79c6a

.NET Core SDKs installed:
  2.1.300-preview2-008407 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26326-03 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by wli3** [comment]
We've talked about this trade off. Either never preview version guide or always preview version guide since the nuget error is transparent for SDK. All SDK get is a return code that is not 0.

Maybe add an extra line like "Trouble shooting suggestions" can mitigate it a bit? To indicate the message is generic

**Comment by peterhuene** [comment]
We can easily do better than what we're doing now, just limit this message to handling ToolPackageException.

**Comment by wli3** [comment]
that is true, at least it will only show when restore failed

**Comment by wli3** [comment]
That means, the error message will still show, say when internet is down

**Comment by peterhuene** [comment]
Not ideal, but best we can do unless we want to check the NuGet error code 🤷‍♂️
