### ISSUE TITLE
Two restore meesages are displayed when run dotnet restore for Xunit project

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#8928]
## Steps to reproduce
1. Create Xunit Project
2. Run dotnet restore

## Expected  behavior
Only one restore message is displayed

## Actual behavior
Two restore meesages are displayed 
![image](https://user-images.githubusercontent.com/1578239/38072639-db61a308-3359-11e8-8a44-6fceeea10c55.png)

## Environment data
`dotnet --info` output:
dotnet --info output:
.NET Core SDK (reflecting any global.json):
Version: 2.1.300-preview2-008407
Commit: 5a5e35c
Runtime Environment:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /usr/share/dotnet/sdk/2.1.300-preview2-008407/
Host (useful for support):
Version: 2.1.0-preview2-26326-03
Commit: 01c8d79c6a
.NET Core SDKs installed:
2.1.300-preview2-008407 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.0-preview2-26326-03 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This is by design.

One restore is for your project while the other restore is for the DotnetCliToolReference. The tool gets restored separately.
