### ISSUE TITLE
It should return error when run dotnet tool list using non-exist tool path

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#8931]
## Steps to reproduce
Run dotnet tool list --tool-path "~/non-exist-path"

## Expected  behavior
It should return error path

## Actual behavior
The output shows the table header with package id, version, and commands. 
![image](https://user-images.githubusercontent.com/1578239/38074117-42602538-3360-11e8-9ad5-d33b4fac4ef9.png)

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
Version: 2.1.300-preview2-008407
Commit: 5a5e35c
Runtime Environment:
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64
Base Path: /usr/share/dotnet/sdk/2.1.300-preview2-008407/
Host (useful for support):
Version: 2.1.0-preview2-26326-03
Commit: 01c8d79c6a
.NET Core SDKs installed:
2.1.300-preview2-008407 [/usr/share/dotnet/sdk]
.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0-preview2-30478 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.0-preview2-26326-03 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
@peterhuene @KathleenDollard can you take a look? Is that true? Should it return an error code or just return empty as we are already doing?

**Comment by peterhuene** [comment]
I'm in agreement that we should probably throw `GracefulException` if the given path doesn't exist.

For install, there shouldn't be an error because it creates the directory.

For uninstall, it will error because it can't find the tool package to uninstall (although, it should probably have the same error as list).

**Comment by peterhuene** [comment]
```
$ dotnet tool list --tool-path does-not-exist
Tool path 'does-not-exist' does not exist.
Usage: dotnet tool list [options]

Options:
  -g, --global   List user wide tools.
  --tool-path    Location where the tools are installed.
  -h, --help     Show help information.
```

**Comment by KathleenDollard** [comment]
LGTM
