### ISSUE TITLE
Install global tools described in csproj

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#8934]
It would be interesting to be able to specify a list of global tools in csproj.
This makes it easy for anyone working on the project to install those tools.
This is similar to csproj DotNetCliToolReference and npm devDependencies.

**Comment by livarcocc** [comment]
This is not something that we are looking at. Instead, we have been talking about what we have been calling repo tools. Which is basically a "manifest" file sitting at the root of you repo where you can invoke any of the tools there through dotnet <tool>. You would also get a gesture to install these tools locally to your repo.

For tools based on your csproj, the recommendation is to continue using DotNetCliToolReference. I understand that you would want to produce one single package and use it both ways, but that's not possible, as it would have serious performance implications on NuGet side. It is explicitly not allowed.

**Comment by tmds** [comment]
> This is not something that we are looking at. Instead, we have been talking about what we have been calling repo tools. Which is basically a "manifest" file sitting at the root of you repo where you can invoke any of the tools there through dotnet . You would also get a gesture to install these tools locally to your repo.

ok, this 'manifest' will support global tools then?

> I understand that you would want to produce one single package and use it both ways, but that's not possible, as it would have serious performance implications on NuGet side. It is explicitly not allowed.

I doubt tool-owners will make their tools available both a 'global' and as 'DotNetCliToolReference' packages. So, this is manifest is deprecating 'DotNetCliToolReference'?

**Comment by tmds** [comment]
Answered in https://github.com/dotnet/cli/issues/9782#issuecomment-410033494
