### ISSUE TITLE
Right bracket is missing in text when tool installation succeed with SC language 

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#8964]
## Steps to reproduce
1. Install global tool on windows with SC language

## Expected  behavior
All the text is translated and displayed normally

## Actual behavior
Right bracket is missing in text when tool installation succeed
![image](https://user-images.githubusercontent.com/1578239/38190747-3c218032-3698-11e8-9183-a6628595d9d3.png)

## Environment data
`dotnet --info` output:
.NET Core SDK（反映任何 global.json）:
 Version:   2.1.300-preview2-008510
 Commit:    abcdeba455

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008510\

Host (useful for support):
  Version: 2.1.0-preview2-26330-03
  Commit:  632536fb4b

.NET Core SDKs installed:
  2.1.300-preview2-008510 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30520 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30520 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26330-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
@peterhuene @wli3 please take a look.

**Comment by wli3** [comment]
This is strange. It is missing a unicode bracket and a unicode comma but it is not in xlf text. 

https://github.com/dotnet/cli/blob/release/2.1.3xx/src/dotnet/commands/dotnet-tool/install/xlf/LocalizableStrings.zh-Hans.xlf#L9

@yuki233 does it repo constantly? 

@nguerrera have you seen this before?

**Comment by yuki233** [comment]
Yes, It is always repro. And this issue is also reproduced with build 2.1.300-preview2-008530.

**Comment by nguerrera** [comment]
Very odd. No, I have not seen this. Maybe an issue with the console font? If so, and that's the default font for this locale, we should get loc folks to spell comma and paren differently.

**Comment by nguerrera** [comment]
@janbaltus

**Comment by janbaltus** [comment]
Hi Nick,
from our point of view there is not much we can do.
Double quotes are present in the string "已成功安装工具“{1}”（版本“{2}”）。" and first pair is visible with no issue.
Can this issue be tested on more langauges? Especially CHS,CHT,KOR,JPN and RUS?

**Comment by kasper3** [comment]
In a shell called Hyper (https://hyper.is) on windows 10, using PowerShell (inside hyper) with chcp 430, I get 

![image](https://user-images.githubusercontent.com/33230602/38625721-c4f9f07a-3db3-11e8-914d-f7cb42935008.png)

In cmder with `set LANG=C.UTF-8`, it looks correct

![image](https://user-images.githubusercontent.com/33230602/38625858-0c26c5c2-3db4-11e8-8127-428433f4ded2.png)

with cmd and regular powershell, it shows boxes and ?? as my OS language is en_US.

Test program:

```c#
class Program
{
    static void Main(string[] args)
    {
        System.Console.OutputEncoding = System.Text.Encoding.UTF8;
        System.Threading.Thread.CurrentThread.CurrentUICulture = new System.Globalization.CultureInfo("zh-Hans");
        System.Console.WriteLine(@"如果没有其他说明，可键入以下命令来调用该工具: {0}
已成功安装工具“{1}”（版本“{2}”）。", "test", "test2", "test3");
    }
}
```

netcoreapp2.1 with latest nightly cli.

**Comment by wli3** [comment]
I tried it on dev test lab _Windows-10-Enterprise-RS3-ZH-CN_ image. No repo in full ZH-CN image. Please reopen if you think more need to be addressed

![image](https://user-images.githubusercontent.com/6993335/38646595-7306162e-3d9d-11e8-919f-8f7ab38e7526.png)

**Comment by yuki233** [comment]
This issue is due to the displayed font.
![image](https://user-images.githubusercontent.com/1578239/38925452-3a53c21e-4332-11e8-95ea-ed2243d91bc9.png)
