### ISSUE TITLE
Improve design of the buildserver shutdown command.

### ISSUE THREAD

**Issue by peterhuene** [dotnet/cli#8968]
See related discussion [here](https://github.com/dotnet/cli/pull/8950#discussion_r178253999).

Currently the `buildserver shutdown` command uses three different mechanisms for shutting down build servers:

* Using a well-defined API we link against that knows how to shut down the server (*MSBuild*)
* Using an executable to run to shut down the server from a well-defined location (*VBCSCompiler*)
* Searching for the executable to run to shut down the server because it exists in a NuGet package (*Razor*)

Unlike the first two mechanisms, the third mechanism above requires the context of an MSBuild project to locate the appropriate package containing the executable to use to shut down the build server.  This might be confusing to users because the command now depends on *where* you run it for it to work.

This issue is intended to discuss a better, general design for shutting down build servers so that we don't keep adding additional servers requiring project context.

A possible solution to get the discussion started:

* All build servers write a *pid file* to a well-known location.  The pid file would contain the pid, a description of the server process (i.e. `MSBuild`, `VB/C# Compiler`, etc.), and the name of a pipe to connect to issue a shutdown command to.  The `buildserver shutdown` command would then become more generic and issue shutdown commands to all running build servers, regardless of the current directory.

**Comment by peterhuene** [comment]
@rainersigwald @rynowak @jaredpar @nguerrera I've created this as a discussion issue to talk about improving the design of how we shutdown build servers for the 2.1 release.

My goal is to make this a unified design between our different server implementations so that `dotnet` doesn't have to have specific implementations for each build server we want to support.  Additionally, I'd like this design to also be *discoverable* from dotnet's perspective so that we can also have some visibility into what's currently running (imagine a `buildserver list` command in the future, for example).

I'll send out a meeting request soon to discuss this.

**Comment by AndyGerlicher** [comment]
We're already in escrow for MSBuild (Visual Studio escrow bar) so I think this will need to be pushed to 15.8 time-frame. If there's strong push back we can reconsider, but given this works it doesn't seem critical for release.

**Comment by peterhuene** [comment]
Closing this issue as we have a design in place for Razor that hopefully we can extend to Roslyn and MSBuild in a future release.
