### ISSUE TITLE
Cannot express skip-compilation option in project.json

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#897]
DNX supported wrapping pre-build library and would not attempt to compile the library when it was present. https://github.com/aspnet/Home/wiki/Project.json-file#bin-syntax-wrapping-a-dll

```json
  "frameworks": {
      "netcore50": {
         "bin": { "assembly": "something.dll" }
      }
  }
```

EntityFramework.Commands used this feature to prevent compilation but still produce a nupkg with `netcore50` support.

`dotnet compile` compiles even if the wrapping syntax is present.

**Comment by davidfowl** [comment]
We're going to be doing over the wrapping feature and general csproj integration support. Are you using it to pack?

**Comment by natemcmaster** [comment]
> ...produce a nupkg with netcore50 support.

Yes, we primarily used this to get pack to work correctly.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
