### ISSUE TITLE
CI error Retrying X for source - Could not load file or assembly 'Microsoft.Win32.Primitives - Too many open files

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#8972]
Relate to 

https://github.com/NuGet/Home/issues/2004
https://github.com/dotnet/cli/issues/809

Failed CI build
https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/release_rhel7.2_x64_prtest/187/testReport/junit/(root)/(empty)/Microsoft_DotNet_New_Tests_GivenThatIWantANewAppWithSpecifiedType_TemplateRestoresAndBuildsWithoutWarnings_language___C____projectType___mvc___skipSpaWebpackSteps__False_/

https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/debug_centos7.1_x64_prtest/195/testReport/junit/(root)/(empty)/Microsoft_DotNet_New_Tests_GivenThatIWantANewAppWithSpecifiedType_TemplateRestoresAndBuildsWithoutWarnings_language___C____projectType___mvc___skipSpaWebpackSteps__False_/

**Comment by wli3** [comment]
https://ci.dot.net/job/dotnet_cli/job/release_2.1.3xx/job/debug_centos7.1_x64_prtest/196/

**Comment by wli3** [comment]
I added $FILE_DESCRIPTOR_LIMIT like last time. See if it can help

**Comment by wli3** [comment]
$FILE_DESCRIPTOR_LIMIT

**Comment by wli3** [comment]
Previews fix https://github.com/NuGet/NuGet.Client/commit/f5f67f6da8d8c34be14017a88a08b9f13c78e65a

**Comment by wli3** [comment]
Doesn't work

**Comment by wli3** [comment]
Creating a vm and see  try to repo.

**Comment by wli3** [comment]
I pumped the ulimit to 65536, but it still won't resolve the issue. ulimit should not be the real cause

**Comment by wli3** [comment]
ulimit: open files: cannot modify limit: Operation not permitted

Error on pump to 65535

**Comment by wli3** [comment]
https://github.com/dotnet/corefx/issues/28662

**Comment by wli3** [comment]
get repo on local. But it does not help much. But it still points to ulimit

```  

The SSL connection could not be established, see inner exception.
    Could not load file or assembly 'System.Runtime.Numerics, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a
3a'. The system cannot open the file.
     (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-web/nuget/v3/flatco
ntainer/microsoft.aspnetcore.app/index.json'.
  The SSL connection could not be established, see inner exception.
    Could not load file or assembly 'System.Runtime.Numerics, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a
3a'. The system cannot open the file.
     (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.e
xtensions.configuration/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50
a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnet.myget.org/F/templating/api/v3/flatcontainer/microsoft.aspnetcor
e.app/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50
a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-web/nuget/v3/flatco
ntainer/microsoft.aspnetcore.app/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50
a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
  Retrying 'FindPackagesByIdAsync' for source 'https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-corefxlab/nuget/v3/
flatcontainer/microsoft.extensions.configuration/index.json'.
  Could not load file or assembly 'Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50
a3a'. The system cannot open the file.
   (Exception from HRESULT: 0x80070004)
```

**Comment by wli3** [comment]
Improve ulimit solved the problem on my local repo

**Comment by livarcocc** [comment]
Good to know. Let's go through the process of setting this for our machines.

**Comment by wli3** [comment]
blocking checking is resolved. Close this issue and only track on nuget
