### ISSUE TITLE
I cannot create a .NET Core 2.0 console app with `dotnet new console`

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#8973]
I want to do this:

````
dotnet new console -f netcorapp2.0
```

I cannot. How do I specify the TFM for a new app?

**Comment by livarcocc** [comment]
This is currently not supported by dotnet new console and it is actually on the list of work items we need to do to support our LTS plan of having only a current version of the SDK. This was one of the things you, me and @leecow discussed. In any case, I will move this issue to dotnet/templating.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1495
