### ISSUE TITLE
[Arm] crossgen cli tools

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/cli#8998]
Arm64 & Arm crosscomponent crossgen tools are available and are being consumed by coreclr core-setup to crossgen the runtime.

They are not yet being used by cli to crossgen the SDK (done for x64).

One of the issues is that the crosscomponent crossgen tool is contained in a private coreclr package which is enacapsulated by core-setup.  ClI does not seem to have the necessary version info to reference the correct package.

Options:
+ Core-setup redistribute the crosscomponent crossgen tool(s)
+ Create a mechanism to determine the correct coreclr package version.

For arm64 the crosscomponent crossgen tool is here 
```
transport.runtime.linux-arm64.microsoft.netcore.runtime.coreclr/*/tools/x64_arm64/crossgen
```

**Comment by kasper3** [comment]
@BruceForstall, could you mention someone who may be able help bringing up ARM32 crossgen? aarch64 changes are in.

**Comment by BruceForstall** [comment]
also, @RussKeldorph

**Comment by RussKeldorph** [comment]
@Petermarcu Has anybody already figured out how the "cross" crosstools will flow between repos?  I'd assume coreclr can continue to maintain a private/sloppy package interface and everybody else consumes via core-setup, but I haven't thought it through.

**Comment by sdmaclea** [comment]
Right now the crosscomponent x86_arm & x64_arm64 tools are being published with core-setup runtime

**Comment by RussKeldorph** [comment]
@sdmaclea Ok, sorry, I missed the time difference between you opening this issue and @kasper3's question.  Sounds like this is mostly settled.

**Comment by sdmaclea** [comment]
The remaining work is using a x86 docker image to call crossgen for arm in cli

**Comment by sdmaclea** [comment]
Editted the title because the arm64 crossgen is merged in cli master branch

**Comment by eerhardt** [comment]
>> Has anybody already figured out how the "cross" crosstools will flow between repos? 

> Right now the crosscomponent x86_arm & x64_arm64 tools are being published with core-setup runtime

This is correct.  Just like the "regular" crossgen executables are being packaged in the `runtime.RID.Microsoft.NETCore.App` packages, we are now packaging the "cross component" crossgen executables in the same packages, in a separate folder.  So all the runtime components are available for both the CLI and ASP.NET repos to crossgen the ARM binaries.

**Comment by echesakovMSFT** [comment]
@livarcocc We are publishing the Linux x64-hosted ARM32-targeting crossgen from core-setup (https://github.com/dotnet/core-setup/pull/4621) 

As far as I understood, to get remaining assemblies crossgen-d I need to enable CrossGen for Linux/ARM32 in cli. I believe I need to do the same what @sdmaclea did in #9011. However there is no build/CrossGen.props file in current master and there is no CrossgenPublishDir target in src/redist/redist.csproj. Can you please suggest how can I approach this task?

/cc @RussKeldorph

**Comment by livarcocc** [comment]
That code has since moved to dotnet/core-sdk. Take a look there.

**Comment by echesakovMSFT** [comment]
Thanks

**Comment by am11** [comment]
Was it resolved by https://github.com/dotnet/core-sdk/pull/108?

**Comment by livarcocc** [comment]
Yes.
