### ISSUE TITLE
Add Nuget source commands to cli?

### ISSUE THREAD

**Issue by mattcbaker** [dotnet/cli#8999]
The cli has some nuget commands that can be used, [ref](https://docs.microsoft.com/en-us/nuget/tools/dotnet-commands).

What does everyone think about adding more? I'm specifically interested in being able to add nuget sources using the cli. 

My use case is in AWS CodePipeline. CodePipeline uses an Ubuntu image to run dotnet builds, and I cannot access that image (AFAIK). The image has the dotnet cli installed, but it does not have the nuget cli installed. I'd like to add a private nuget source before running the build, but I can't without the nuget cli. I might be able to install nuget via apt-get at the start of the build, but it would be nice to use the dotnet cli to add a nuget source since I use it for every other step of the build.

Thoughts?

**Comment by livarcocc** [comment]
Ultimately, the NuGet team owns these commands for NuGet itself, so it might be worth filling an issue at nuget/home for this instead.

However, NuGet does support passing these options through MSBuild properties, so you could pass to your build, I believe it is `RestoreAdditionalProjectSources` with the feed you are trying to use. This should be able to unblock you.

I am going to close this issue as you have a workaround and nuget/home is a more appropriate repo for it. But do let us know if the workaround above works for you.

I am assuming that the feed is dynamic and that you can't add a NuGet.Config file to your repo or set the property above in a Directory.Build.props file. But in any case, you should be able to `/p:RestoreAdditionalProjectSources=<feed_url>` when invoking `dotnet build`.

**Comment by mattcbaker** [comment]
I think I found a simple solution, based on the advice from @livarcocc above. You can pass sources to the `dotnet restore` command.

```
dotnet restore --source https://your-nuget-source
```

**Comment by lextm** [comment]
This feature request is still valid, for enterprise scenarios such as,

1. An internal NuGet feed with authentication enabled.
1. Restore a .NET Core project on Linux based machines against such a feed.

`dotnet restore --source FEED_URL` does not handle authentication properly, so it is not really a solution.
