### ISSUE TITLE
dotnet install command not available

### ISSUE THREAD

**Issue by saviour123** [dotnet/cli#9003]
## Steps to reproduce
`$ dotnet new console`
`$ dotnet pack -c Release`
`$ dotnet install tool -g sayhi`

## Expected  behavior
run successfully. 
`>sayhi` 
`his saviour`

## Actual behavior
No executable found matching command "dotnet-install"

## Environment data
dotnet sdk 2.1.4, ubuntu 17.10

Is `dotnet install` not supported for installing builiding commandline tools?

**Comment by livarcocc** [comment]
It is only available starting on .NET Core SDK 2.1.300, which preview1 is the only official version available.

Please note that in preview2, we have changed the command from `dotnet install tool` to `dotnet tool install`.

**Comment by onionhammer** [comment]
This should be re-opened. I'm getting this and I have 2.1.300 installed

```
.NET Core SDK (reflecting any global.json): Version:   2.1.300 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin RID:         osx.10.13-x64 Base Path:   /usr/local/share/dotnet/sdk/2.1.300/
Host (useful for support):  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.2 [/usr/local/share/dotnet/sdk]
  2.1.3 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.105 [/usr/local/share/dotnet/sdk]
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by Andrea** [comment]
Just to note I nearly missed this solution because it seems  dotnet *2.1.4 * is < than `2.1.300-rc1-008673`. it might be obvious to some, I am noting this to make it more explicit

**Comment by saviour123** [comment]
Interesting, how can __2.1.4__ be less than __2.1.300..__

**Comment by Andrea** [comment]
no idea, if anyone has anything that I should test to help make this clearer let me know

**Comment by livarcocc** [comment]
We compare the numbers on each of the parts of the version numerically and as such 4 < 300.
