### ISSUE TITLE
ASP.NET Core HTTPs first run experience disclaimer is misleading for Linux users

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#9008]
Today the text for the ASP.NET Core HTTPs bits is:
![image](https://user-images.githubusercontent.com/2008729/38388681-c8c5565a-38d0-11e8-9aaf-df632b22ff1c.png)

The problem with this is it makes it seem that for Linux the trust has already been trusted in some fashion; however, in reality it's up to the user to determine how to trust the cert on their flavor of Linux. Should update the wording to be more explicit about that expectation.

/cc @danroth27 @javiercn 

## Environment data
`dotnet --info` output:

![image](https://user-images.githubusercontent.com/2008729/38388741-f22d86b6-38d0-11e8-9b43-1d1472a85416.png)

**Comment by danroth27** [comment]
Thanks for the feedback, @NTaylorMullen.

We could append some text to clarify that Linux will require manual steps:

To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms please refer to the platform specific documentation.

**Comment by Eilon** [comment]
Agreed the wording could be clearer.

**Comment by livarcocc** [comment]
@danroth27 Can we get confirmation of the new message we should use here?

**Comment by danroth27** [comment]
Here you go:

To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms please refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
