### ISSUE TITLE
corehost causes segfault sometimes?

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#901]
On the Ubuntu build agent, we got a segfault trying to run dotnet restore: 

> *** Error in `/home/ubuntu-vm/vsoagent.0228/_work/build/af6794afc2479f8f91739a6a1a9c8e6ffe69ed9ca4bce97edbe796fec01b1dae/repo/artifacts/ubuntu.14.04-x64/stage1/bin/corehost': double free or corruption (out): 0x00007f2e040008c0 ***

As far as I can tell, this isn't an issue in the application being run. We are going to work around this by using `corerun` instead, but this should probably be investigated.

**Comment by schellap** [comment]
@anurse, are you able to repro on a VM reliably? Just dotnet restore causes this?

**Comment by anurse** [comment]
I haven't been able to isolate a repro yet, but it was on the Ubuntu VSO agent when running dotnet-restore

**Comment by schellap** [comment]
@anurse, can we undo the workaround in the daily builds now, so we can see it more often and get it tracked down? I tried on the VSO machine by using corehost and it seems to be fine (this time.)

**Comment by schellap** [comment]
It would be as simple as getting the stack trace.

**Comment by anurse** [comment]
I think that should be OK, as long as it's only in the `master` branch. `rel/1.0.0` needs to stay as stable as possible in the short-term. But @piotrpMSFT should make the final call.

**Comment by schellap** [comment]
Yes. Ofcourse, note the word `daily` builds :)

I have a PR out for @anurse, could you PTAL?

**Comment by gkhanna79** [comment]
> We are going to work around this by using corerun instead, but this should probably be investigated.

@anurse Are you still working around using CoreRun? If so, what scenarios are using the workaround? Workaround will not allow the hostimpl.dll to kickin using the policy implementation we have got in there, so it maybe help to remove the workaround from the RC2 Release branch too.

**Comment by schellap** [comment]
Only `dotnet restore` is being worked around AFAIK.
