### ISSUE TITLE
Conclusion page in the installer has multiple issues to address.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#9022]
Feel free to split this up as neccessary:

![image](https://user-images.githubusercontent.com/8228359/38511088-d52b01ac-3bdb-11e8-80df-66496df67ca1.png)

I installed the Preview 2 SDK and noticed a few things on the conclusion page that should be addressed.

@KathleenDollard 

1. There is nothing that tells me its preview 2. I was juggling preview 1 uninstalls and preview 2 installs and the installer didn't give me any hints which one I was on. Branding for the previews should be in the installer UI's. 

2. The resources section has a set of issues:
- The Release notes point to 2.0.
- The tutorials point to instructions on how to use the CLI and other projects that all talk about the .NET Core 1.0 SDK. https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-with-xplat-cli
- The "Core Documentation" should be ".NET Core documentation"
- The "SDK documentation" points to a Command Line Interface page and not the "SDK page".

**Comment by livarcocc** [comment]
I agree on all the changes.

cc @leecow on issue 1, as if I remember correctly, that was the branding that him and @richlander landed on a while ago.

As for issue 2, I will update the text, but I don't know how to update the aka.ms links.

**Comment by leecow** [comment]
We can update the fwlinks. 

- Tutorials is just top level tutorials doc location. Let us know if there's a better target. 
- Release notes link will be updated to 2.1 P2 release notes. 
- I don't have access to the 'dotnet-cli-docs' link. We can make a new one if needed. Let us know where to target it. 

cc/ @preetikr

**Comment by KathleenDollard** [comment]
@mairaw to help with links.

**Comment by mairaw** [comment]
Gave you access to the dotnet-cli-docs link @leecow and @KathleenDollard.

**Comment by nguerrera** [comment]
"20-p2-rel-notes" is an unfortunate name for the release notes perma-link. Not high importance, but can we create a new one without a version in the link?

**Comment by nguerrera** [comment]
I realize that we can't just update a single perma-link for release notes unless we have a page with release notes for all versions.

**Comment by johnbeisner** [comment]
@mairaw 
@leecow 
@KathleenDollard 

Have the resources links been updated at the endpoint to contain the correct documentation?

If not, please advise the new perma-links and I will update the SDK bundle installer:
Core Documentation=
SDK documentation=
Release Notes=
Tutorials=

**Comment by mairaw** [comment]
I think the current perma-links for the docs links are still good. So perhaps the only one left to be defined is the release notes?

**Comment by johnbeisner** [comment]
@mairaw
@leecow
@KathleenDollard

The "SDK documentation" still points to a Command Line Interface page and not the "SDK page".
I need a updated perma-link for SDK documentation
SDK documentation=

**Comment by leecow** [comment]
Release Notes could point to https://github.com/dotnet/core/blob/master/release-notes/download-archive.md which maintains links to release notes and download pages for all release versions.

**Comment by mairaw** [comment]
But that link is called dotnet-cli-docs @johnbeisner and that's where the link is going, to the CLI docs.
The SDK link should go to https://docs.microsoft.com/dotnet/core/sdk instead. 

Do we need a new link or should I just update that aka to go to the sdk topic instead?

That SDK article had some low CSAT so I just opened a PR to try to improve that article a bit as well:
https://github.com/dotnet/docs/pull/12325

**Comment by livarcocc** [comment]
@johnbeisner are these addressed?

**Comment by johnbeisner** [comment]
SDK documentation:
@mairaw
May I have the aka-link to "https://docs.microsoft.com/dotnet/core/sdk"

Release Notes:
@leecow
The release notes aka-link is broken: "https://aka.ms/netcore3releasenotes"
Should we be using a different link?

**Comment by mairaw** [comment]
I've just created https://aka.ms/dotnet-sdk-docs

**Comment by johnbeisner** [comment]
"https://aka.ms/netcore3releasenotes" is active now
