### ISSUE TITLE
Unify EmbedAppNameInHost in CLI and SDK

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#9027]
https://github.com/dotnet/cli/blob/56c10f65c71e070116ca92f55598015a7f7713c1/src/Microsoft.DotNet.Cli.Utils/EmbedAppNameInHost.cs

https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/EmbedAppNameInHost.cs

This logic is duplicated in both CLI and SDK. It should be unified.

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/8893#discussion_r176923641 was introduced there

**Comment by livarcocc** [comment]
@wli3 Is this fixed now?

**Comment by wli3** [comment]
@livarcocc no, not yet. This requires repo merge for the complete fix.

**Comment by wli3** [comment]
@nguerrera could you link the new work that will unify them in one place?

**Comment by wli3** [comment]
Done along with https://github.com/dotnet/cli/issues/11300
