### ISSUE TITLE
dotnet pack generates wrong nuspec

### ISSUE THREAD

**Issue by Doomblaster** [dotnet/cli#9038]
## Steps to reproduce
Create project and pack it in nuget package A with version 2.0.0.0. Create another project dependant on nuget package A and change the PackageReference Version attribute to *. Use dotnet pack and create version 3.0.0.0.

## Expected  behavior
Nuget package B to be dependant on nuget package A v2.0.0.0

## Actual behavior
Nuget package B is dependant on nuget package A v3.0.0.0

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.200-preview-007474)

Product Information:
 Version:            2.1.200-preview-007474
 Commit SHA-1 hash:  06ce7628d3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200-preview-007474\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6803
