### ISSUE TITLE
Framework-Dependent Deployment not loading assemblies on linux-arm

### ISSUE THREAD

**Issue by pierslawson** [dotnet/cli#9039]
I original posted this in dotnet/coreclr#17438 but it was suggested it was better here.

## Steps to reproduce
On a Windows machine with .Net Core 2.1 Preview 1 installed create a console application to target a Raspberry Pi (Linux-arm) as described in [omnisharp guidelines for remote debugging](https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm).  It is possible to successfully step into code using the Framework-Dependent Deployment approach if I have a simple console application. Brilliant!

Add a reference to the project to a nuget package e.g. Add the following to the `csproj` file, restore and build (from the Windows machine).
```
   <PackageReference Include="System.Text.Encoding.CodePages" Version="4.4.0" />
```
Try to debug remotely from the Windows machine (again using the Framework Dependent approach)... or run the code directly on the Raspberry Pi using `sudo dotnet MyConsoleApp.dll` from a command prompt.

## Expected  behavior

Can step into my code running on the Raspberry Pi if debugging or run my application if running directly on the Raspberry Pi.

## Actual behavior

A missing assembly message is displayed and either the debugger fails to attach or in the case of running directly, the process exits. In both cases a message along the lines of this is shown:
```
Error:
An assembly specified in the application dependencies manifest (MyConsoleApp.deps.json) was not found:
package: 'System.Text.Encoding.CodePages', version: '4.4.0'
path: 'lib/netstandard2.0/System.Text.Encoding.CodePages.dll'
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
```

NB If I publish the project, the published version does execute when I run `sudo ./MyConsoleApp` (i.e. when following the Self-Contained Deployment approach).

## Environment data
`cat /etc/os-release` on the Raspberry Pi output:
```
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

using `dotnet --info` on the Raspberry Pi output:
```
  Microsoft .NET Core Shared Framework Host
  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

using `dotnet --info` on the Windows machine used for development and build output:
```
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153
```

**Comment by livarcocc** [comment]
I don't know about debugging, does it fail with the same error code as when you run the dll?

Also, how are you copying the FDD app to the pie? Are you copying the contents of the build output `bin/debug/netcoreapp2.1` or the contents of the publish folder `bin/debug/netcoreapp2.1/publish`? The contents of the build are not xcopyable and runnable. If you want to deploy your app you need to publish and then copy the publish contents in order to run it.

**Comment by pierslawson** [comment]
My code actually resides on the RPi and the Windows machine can see it through a samba share (so I don't have to copy files around). I have tried both FDD and SCD.

For FDD:

1. I build the project using VSCode on my Windows machine
1. Open a terminal on the Raspberry Pi
1. Change directory to the `bin/Debug/netcoreapp2.1`
1. Run `sudo dotnet MyConsoleApp.dll`. 

That runs fine with a straight out of the box "Hello World" console application. I can also debug this using the right entries in launch.json from VSCode. If I change that console application to reference the assembly mentioned above and then run through the same steps I get the error mentioned above. I get the same error if I try to debug the new version of the console application.

For SCD:

1. I run `dotnet publish -r linux-arm` on my Windows machine
1. Open a terminal on the Raspberry Pi
1. Change directory to the `bin/Debug/netcoreapp2.1/Linux-arm/publish`
1. Run `sudo ./MyConsoleApp`

This runs fine, with or without the extra reference to the assembly. However, there seems to be an issue with the debugger that means I can't debug the published version (see OmniSharp/omnisharp-vscode#2150).

So I'm close, but held back from doing any decent remote debugging because I'm having different problems with the to two ways (FDD and SCD) of achieving it :-( Ideally I would get the FDD approach working because it is much lighter weight. 

I was wondering if the problem was the particular assembly (`System.Text.Encoding.CodePages`) I had chosen. I have seen it mentioned as one that is stripped out automatically because it is expected to be installed on the host machine, but is only installed if you deploy the ASP.Net support as well.

**Comment by livarcocc** [comment]
Step 4 in the FDD scenario is wrong. You can't run your application like that. You need to either use dotnet run or you need to publish your application and `sudo dotnet MyConsoleApp.dll` from `bin/debug/netcoreapp2.1/publish` folder. The build output is not runnable directly, like you are trying to do.

**Comment by pierslawson** [comment]
Apologies... I just re-read your comment and saw the publish step. Running in the sub-directory does work correctly. I guess what fooled me is that running in the `bin/Debug/netcoreapp2.1` directory does work until you reference assemblies that are not part of .Net Core itself... so a Hello World application can be debugged!

**Comment by pierslawson** [comment]
It appears the instructions I followed at the OmniSharp/omnisharp-vscode repository were wrong:

[Remote Debugging On Linux Arm](https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm#build-and-deploy)

For FDD it does not say to use dotnet publish or run using the DLL in the publish sub-directory. I'll raise an issue there.

**Comment by livarcocc** [comment]
Thanks for following up and filling an issue to update the instructions.
