### ISSUE TITLE
CLI Repo build should use "dotnet restore" with NuGet not dnu

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#904]
The build is currently using DNU still. Now that we have NuGet xplat in, we should use that.

https://github.com/dotnet/cli/blob/master/scripts/build/restore-packages.ps1#L21
https://github.com/dotnet/cli/blob/master/scripts/build/restore-packages.sh#L21

**Comment by brthor** [comment]
Part 2 of:
https://github.com/dotnet/cli/issues/421

**Comment by brthor** [comment]
This is currently blocking #875

**Comment by piotrpMSFT** [comment]
This PR should target https://github.com/dotnet/cli/tree/rel/1.0.0
