### ISSUE TITLE
dotnet pack crashes with NullReferenceException with missing Nuspecfile property

### ISSUE THREAD

**Issue by yizhang82** [dotnet/cli#9043]
## Steps to reproduce

1. dotnet new library
2. dotnet pack
This succeeds
3. Add following section to the csproj file

```
  <Target Name="SetNuspecProperties" BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <NuspecProperties>$(NuspecProperties);id=$(AssemblyName)</NuspecProperties>
    </PropertyGroup>
    <Message Importance="high" Text="NuspecProperties: $(NuspecProperties)" />
  </Target> 
```
4. dotnet pack

This crashes. 

Adding expected   <NuspecFile>$(MSBuildThisFileDirectory)$(MSBuildProjectName).nuspec</NuspecFile> reference will give a proper error message that the .nuspec file is not found.

## Expected  behavior

Don't crash and give better diagnostic error message

## Actual behavior

Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 95.72 ms for E:\var\t\t.csproj.
  t -> E:\var\t\bin\Debug\netstandard2.0\t.dll
  NuspecProperties: ;id=t
C:\Program Files\dotnet\sdk\2.1.103\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(194,5): error : Object reference not set to an instance of an object. [E:\var\t\t.csproj]

## Callstack

2:045> k
 Child-SP          RetAddr           Call Site
00 000000e1`bd17b250 00007ff7`afd6badf NuGet_Build_Tasks_Pack!NuGet.Commands.PackCommandRunner.BuildFromProjectFile(System.String)+0x187
01 000000e1`bd17b350 00007ff7`afd604dc NuGet_Build_Tasks_Pack!NuGet.Commands.PackCommandRunner.BuildPackage()+0x4f
02 000000e1`bd17b380 00007ff8`2257042f NuGet_Build_Tasks_Pack!NuGet.Build.Tasks.Pack.PackTask.Execute()+0xec
03 000000e1`bd17b3e0 00007ff8`225e7373 Microsoft_Build!Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()+0x7f
04 000000e1`bd17b420 00007ff7`af91cab9 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__25.MoveNext()+0x3d3
05 000000e1`bd17b4d0 00007ff8`225695a9 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.CommonlyUsedGenericInstantiations+<AsyncHelper2>d__4`1[[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]](<AsyncHelper2>d__4`1<System.__Canon> ByRef)+0xffffffff`aa2db5e9 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 465] 
06 000000e1`bd17b530 00007ff8`225e6dc1 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(Microsoft.Build.BackEnd.ITaskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext, Microsoft.Build.BackEnd.TaskHost, Microsoft.Build.BackEnd.ItemBucket, Microsoft.Build.BackEnd.TaskExecutionMode)+0x99
07 000000e1`bd17b5f0 00007ff7`af91c449 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder+<InitializeAndExecuteTask>d__23.MoveNext()+0x131
08 000000e1`bd17b660 00007ff8`225692b0 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.CommonlyUsedGenericInstantiations+<AsyncHelper2>d__4`1[[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]](<AsyncHelper2>d__4`1<System.__Canon> ByRef)+0xffffffff`aa2daf79 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 465] 
09 000000e1`bd17b6c0 00007ff7`af918797 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder.InitializeAndExecuteTask(Microsoft.Build.BackEnd.Logging.TaskLoggingContext, Microsoft.Build.BackEnd.ItemBucket, System.Collections.Generic.IDictionary`2<System.String,System.String>, Microsoft.Build.BackEnd.TaskHost, Microsoft.Build.BackEnd.TaskExecutionMode)+0x90
0a 000000e1`bd17b760 00007ff7`af917f89 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder+<ExecuteBucket>d__19.MoveNext()+0x337
0b 000000e1`bd17b860 00007ff8`22568df8 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.CommonlyUsedGenericInstantiations+<AsyncHelper2>d__4`1[[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]](<AsyncHelper2>d__4`1<System.__Canon> ByRef)+0xffffffff`aa2d6ab9 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 465] 
0c 000000e1`bd17b8c0 00007ff8`225e6931 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder.ExecuteBucket(Microsoft.Build.BackEnd.TaskHost, Microsoft.Build.BackEnd.ItemBucket, Microsoft.Build.BackEnd.TaskExecutionMode, System.Collections.Generic.Dictionary`2<System.String,System.String>)+0x88
0d 000000e1`bd17b970 00007ff7`af917e79 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder+<ExecuteTask>d__18.MoveNext()+0x361
0e 000000e1`bd17ba50 00007ff8`22568d45 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.CommonlyUsedGenericInstantiations+<AsyncHelper2>d__4`1[[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]](<AsyncHelper2>d__4`1<System.__Canon> ByRef)+0xffffffff`aa2d69a9 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 465] 
0f 000000e1`bd17bab0 00007ff8`225e647e Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.TaskExecutionMode, Microsoft.Build.BackEnd.Lookup)+0x75
10 000000e1`bd17bb60 00007ff7`af917d69 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder+<ExecuteTask>d__13.MoveNext()+0x2ce
11 000000e1`bd17bbd0 00007ff8`225687b6 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.CommonlyUsedGenericInstantiations+<AsyncHelper2>d__4`1[[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]](<AsyncHelper2>d__4`1<System.__Canon> ByRef)+0xffffffff`aa2d6899 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 465] 
12 000000e1`bd17bc30 00007ff8`225e5ee6 Microsoft_Build!Microsoft.Build.BackEnd.TaskBuilder.ExecuteTask(Microsoft.Build.BackEnd.Logging.TargetLoggingContext, Microsoft.Build.BackEnd.BuildRequestEntry, Microsoft.Build.BackEnd.ITargetBuilderCallback, Microsoft.Build.Execution.ProjectTargetInstanceChild, Microsoft.Build.BackEnd.TaskExecutionMode, Microsoft.Build.BackEnd.Lookup, Microsoft.Build.BackEnd.Lookup, System.Threading.CancellationToken)+0xc6
13 000000e1`bd17bcf0 00007ff7`af917849 Microsoft_Build!Microsoft.Build.BackEnd.TargetEntry+<ProcessBucket>d__52.MoveNext()+0x146
14 000000e1`bd17bd90 00007ff8`22564f75 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.CommonlyUsedGenericInstantiations+<AsyncHelper2>d__4`1[[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]](<AsyncHelper2>d__4`1<System.__Canon> ByRef)+0xffffffff`aa2d6379 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 465] 
15 000000e1`bd17bdf0 00007ff8`225e51b9 Microsoft_Build!Microsoft.Build.BackEnd.TargetEntry.ProcessBucket(Microsoft.Build.BackEnd.ITaskBuilder, Microsoft.Build.BackEnd.Logging.TargetLoggingContext, Microsoft.Build.BackEnd.TaskExecutionMode, Microsoft.Build.BackEnd.Lookup, Microsoft.Build.BackEnd.Lookup)+0x95
16 000000e1`bd17bea0 00007ff7`af917739 Microsoft_Build!Microsoft.Build.BackEnd.TargetEntry+<ExecuteTarget>d__45.MoveNext()+0x6a9
17 000000e1`bd17bfe0 00007ff8`22564869 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib]](System.__Canon ByRef)+0xffffffff`aa3a6ea9 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 308] 
18 000000e1`bd17c040 00007ff8`225e3f94 Microsoft_Build!Microsoft.Build.BackEnd.TargetEntry.ExecuteTarget(Microsoft.Build.BackEnd.ITaskBuilder, Microsoft.Build.BackEnd.BuildRequestEntry, Microsoft.Build.BackEnd.Logging.ProjectLoggingContext, System.Threading.CancellationToken)+0x89
19 000000e1`bd17c130 00007ff8`0549b5be Microsoft_Build!Microsoft.Build.BackEnd.TargetBuilder+<ProcessTargetStack>d__21.MoveNext()+0x684
1a 000000e1`bd17c1d0 00007ff8`05565a61 System_Private_CoreLib!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x6e [E:\A\_work\2723\s\src\mscorlib\shared\System\Threading\ExecutionContext.cs @ 145] 
1b 000000e1`bd17c240 00007ff8`0552af7c System_Private_CoreLib!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)+0x61 [E:\A\_work\2723\s\src\mscorlib\src\System\Threading\Tasks\TaskContinuation.cs @ 760] 
1c 000000e1`bd17c290 00007ff8`05595235 System_Private_CoreLib!System.Threading.Tasks.Task.RunContinuations(System.Object)+0x12c [E:\A\_work\2723\s\src\mscorlib\src\System\Threading\Tasks\Task.cs @ 3238] 
1d 000000e1`bd17c380 00007ff8`05571699 System_Private_CoreLib!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+0x2afa5 [E:\A\_work\2723\s\src\mscorlib\src\System\Threading\Tasks\future.cs @ 425] 
1e 000000e1`bd17c3c0 00007ff8`0557162c System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib]].SetExistingTaskResult(Int32)+0x55fedf09 [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 605] 
1f 000000e1`bd17c400 00007ff8`225e58e9 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetResult(System.Threading.Tasks.Task`1<System.__Canon>)+0xffffffff`fff304ec [E:\A\_work\2723\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 646] 
20 000000e1`bd17c430 00007ff8`0549b5be Microsoft_Build!Microsoft.Build.BackEnd.TargetEntry+<ExecuteTarget>d__45.MoveNext()+0xdd9

and more

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.103)

Product Information:
 Version:            2.1.103
 Commit SHA-1 hash:  60218cecb5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.103\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#6805
