### ISSUE TITLE
.NET Core 2.0, MSBuild, RuntimeIdentifier - how to specify output directory?

### ISSUE THREAD

**Issue by Krakean** [dotnet/cli#9046]
Hello.
I have this csproj for my application executable: https://pastebin.com/N60prKm3
How can I specify there output directory for files produced by RuntimeIdentifier?

A bit more details.
I have Directory.Build.props with settings for all projects within my solution like:
<BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)!objs\$(MSBuildProjectName)\$(Configuration)\</BaseIntermediateOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

...
    <NuGetPackageRoot>$(MSBuildThisFileDirectory)!nuget\</NuGetPackageRoot>
    <RestorePackagesPath>$(NuGetPackageRoot)</RestorePackagesPath>
...
    <OutputPath>..\..\EngineBinaries\Debug\Win64\</OutputPath>
...

Everything is fine in context of files orderliness, the way **I** want it. But then, when you want to produce .exe when working with .net core, you add runtimeidentifier, and then dotnet do things way it wants, not me. Specifically, how to get rid of this folder - https://i.imgur.com/InSbHRd.png - and force to produce exe either within Output path that I set (...EngineBinaries\Debug\), or change win-x64 output dir to the path that I find appropriate within my folders structure (lets say ...\EngineBinaries\Debug-winx64-published\)? But not as a self-produced sub-folder (with dublicated content) within my main Output path.

**Comment by livarcocc** [comment]
You can set `AppendRuntimeIdentifierToOutputPath` to `false` to turn this off. Be careful though, as it may cause your files to stomp on each other.

**Comment by Krakean** [comment]
@livarcocc then why not just add ability to msbuild to specify separate runtime output dir path thus not have problems with files "stomp on each other"? Obvious thing, isn't?

**Comment by livarcocc** [comment]
I believe MSBuild already has that capability. Just condition your output path based on your RIDs.

**Comment by Krakean** [comment]
@livarcocc can you please point me to this capability? Didn't found in msbuild docs.
Plus, can't understand how can I condition my output path basing on my RIDs, because rids output path cannot be controlled without overwrite content that is already produced in output path.
