### ISSUE TITLE
Include SOS in Windows packages

### ISSUE THREAD

**Issue by ellismg** [dotnet/cli#905]
It would be helpful if SOS was included in the windows packages so you don't need to figure out where to get a corresponding version from when you want to debug the run-time.

**Comment by moozzyk** [comment]
:+1:

**Comment by Raviuppa** [comment]
Yes  @ellismg , this is the same issue.

**Comment by weshaggard** [comment]
@ellismg which packages are you thinking this should go into? It is already in the runtimes.win7-x64-Microsoft.NETCore.Runtime.CoreCLR package under the tools folder.

**Comment by ellismg** [comment]
It should be in the .zip and msi that the CLI produces.  I understand it's in the nuget packages, but I believe it should be SxS with coreclr in both the bin and runtime folders within CLI so I can debug the runtime CLI runs (and anything that runs on the runtime in the CLI runtime folder).

**Comment by piotrpMSFT** [comment]
CLI is just an instance of an app. If it's useful here then we should add it to the runtime nupkg and deployed as a runtime dependency. That's a runtime packaging issue and not a CLI issue.

**Comment by blackdwarf** [comment]
@piotrpMSFT do we now have a plan to deal with this?

**Comment by piotrpMSFT** [comment]
sos.dll ships in the shared framework already.
