### ISSUE TITLE
Dotnet publish ends up with appsettings.Development.json from wrong project

### ISSUE THREAD

**Issue by nuzelac** [dotnet/cli#9050]
We have two .NET Core API projects in our solution. Project B has a project reference on Project A. Both contain their own `appsettings.*.json` files. 

If we run `dotnet publish` for Project B two times, on the 1st run everything is fine, but on the 2nd run we end up with `appsettings.Development.json` file from the Project A, which is really strange. 

We do not clear bin/ or obj/ folders in between `dotnet publish` runs and we started seeing this on our CI on Monday.

Reproducible on plain new sample solution.

## Steps to reproduce
```bash
git clone https://github.com/nuzelac/DotnetPublishRepro
cd DotnetPublishRepro
```
Run dotnet publish 2 times:
```bash
dotnet publish Project2 -c Release
dotnet publish Project2 -c Release
```

Display appsettings.Development.json
```bash
cat Project2/bin/Release/netcoreapp2.0/publish/appsettings.Development.json
```
## Expected  behavior
```json
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```
## Actual behavior
```json
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "ThisShouldntEndUpInOtherProject": true
}
```

## Environment data
`dotnet --info` output:
```
$ dotnet --info
.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by nuzelac** [comment]
Actually this seems non-deterministic so you might not reproduce the issue...

**Comment by livarcocc** [comment]
This issue was moved to aspnet/websdk#327
