### ISSUE TITLE
CLI no longer gets auto PRs for core-setup in the master branch

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#9051]
## Steps to reproduce
Look at the auto PRs in dotnet/cli master branch.

## Expected  behavior
There should be a recent one for the core-setup repo.

## Actual behavior
There is only a PR to update Roslyn.

## Notes

I believe https://github.com/dotnet/cli/pull/8940 broke this.

**Comment by mmitche** [comment]
Should be fixed by https://github.com/dotnet/versions/pull/288

**Comment by livarcocc** [comment]
Yep. Fixed. Thanks @mmitche.

We got a pr: https://github.com/dotnet/cli/pull/9044.
