### ISSUE TITLE
Change name of buildserver command to build-server

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/cli#9075]
## Expected  behavior

`dotnet build-server shutdown`

## Actual behavior

`dotnet buildserver shutdown`

(Sorry I missed this earlier :-(

**Comment by DustinCampbell** [comment]
FWIW, I'm not sure I get the need to mention "build" at all. Wouldn't it be fine to just call the command `server`? `dotnet server shutdown` seems reasonable and easy to type. Also, I suspect this might eventually be used to shutdown more servers than just "build" servers (perhaps a "project system" server?).

**Comment by livarcocc** [comment]
there is a `dotnet server` global command already. I think using build-server to shutdown a `project system` server sounds all right.
