### ISSUE TITLE
Prerelease option in GitHub releases

### ISSUE THREAD

**Issue by kasper3** [dotnet/cli#9085]
<img width="30%" src="https://user-images.githubusercontent.com/33230602/38854373-ea235cc8-4228-11e8-9967-5306ba868ef9.png" />

This helps downstream in a build automation etc. when using GitHub APIs. For example currently `v2.1.300-preview2-008530` is not showing up in https://api.github.com/repos/dotnet/cli/releases with `"prerelease": true`, but only showing up as a tag https://api.github.com/repos/dotnet/cli/tags.

**Comment by leecow** [comment]
Yep, sorry, I just missed publishing the CLI release. Done now.
