### ISSUE TITLE
2.1.105 SDK package isn't installing aspnetcore-store packages

### ISSUE THREAD

**Issue by bording** [dotnet/cli#9095]
I installed the dotnet-sdk-2.1.105 package on an Ubuntu 16.04 machine and then removed the 2.1.104 package, and I noticed that the aspnetcore-store packages were eligible for auto-removal.

It looks like the 2.1.105 package doesn't have the correct dependency to bring in the runtime store packages like previous SDKs do.

Looking at the tarball version of the 2.1.105 SDK, I see that the store files are still in there, so I suspect this change isn't intentional.

@natemcmaster

**Comment by natemcmaster** [comment]
Looks like there are similar problems in both debian and rpm packages.

![image](https://user-images.githubusercontent.com/2696087/38969755-b0782318-4346-11e8-99f5-8304340b231b.png)

![image](https://user-images.githubusercontent.com/2696087/38969844-06d37d7a-4347-11e8-9ac9-005bc710c220.png)

**Comment by livarcocc** [comment]
@johnbeisner @wli3 can one of you check our linux native installers?

**Comment by livarcocc** [comment]
nvm, @natemcmaster has a PR for it already.

**Comment by bording** [comment]
@natemcmaster @livarcocc Given that this breaks the existing public release, what's the plan for fixing 2.1.105?

**Comment by livarcocc** [comment]
@leecow @preetikr for servicing 2.1.100. I will go ahead and bump the patch version on the CLI in preparation for this servicing. Though, keep in mind that 2.1.200 is coming out soon and will become the latest of the CLI.
