### ISSUE TITLE
Remove -f short hand in dotnet tool install

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#9103]
`--framework` usage in `dotnet tool install` and `update` is uncommon, it is not necessary to take the shorthand `-f`. And  `-f` can be used for future commands

https://github.com/dotnet/cli/issues/9073#issuecomment-382138783
https://github.com/dotnet/cli/issues/9064#issuecomment-382240361

**Comment by wli3** [comment]
cc @KathleenDollard

**Comment by spboyer** [comment]
This leads to confusion, all long commands should have a short version. This is pretty much a standard style for CLI.

if you intend to use `-f` for another command, please add `-fw` for `--framework`

**Comment by omajid** [comment]
>  please add -fw for --framework

I would strongly recommend against that. It is very common for two one-word arguments to be combined. If I saw `-fw` anywhere, I would assume it was a shortcut to specify `-f -w`. That's the whole point of two-dash arguments so we can have arbitrarily long arugument names. It really should be `--fw`.

But that aside, I agree: we should keep `-f` as `--framework` everwhere possible. Perhaps `-F` or some such can be used instead?

**Comment by livarcocc** [comment]
The reason we decided to remove -f from tool install is that we felt users would associated it much more strongly with --force in this context than with --framework if/when we add --force option to tool install.

**Comment by KathleenDollard** [comment]
--framework is a niche switch right now. 

I don't think we should use the -f now.

**Comment by spboyer** [comment]
>  if/when we add --force option to tool install.
Is there a roadmap item that discusses why we would need to **force** install a tool?

> --framework is a niche switch right now.
How can we say that this is niche? Is this going away? The point of the switch is to target a framework when [creating a classlib](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore2x#template-options). Is there not a need to declare TFM in the future.

**Comment by livarcocc** [comment]
It is not on the roadmap, but something that we are trying to leave our options free for.

As for niche, it is niche in the context of global tools and this is being changed only for the tool command. Restore, build, run, publish, test, etc, are all maintaining the -f option, as in the context of those commands, -f is very intuitive in its meaning.
