### ISSUE TITLE
dotnet build exception if project.json doesnt exists

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#912]
at 6a5a220

After successful `dotnet restore` in `test\TestProjects`.
If i run `dotnet build` in a directory without `project.json`, i get the expection. 
Expected is an error message

```
PS D:\github\cli\test\TestProjects> dotnet compile
System.IO.FileNotFoundException: Could not find file 'D:\github\cli\test\TestProjects\project.json'.
File name: 'D:\github\cli\test\TestProjects\project.json'
   at System.IO.Win32FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, F
ileOptions options, SECURITY_ATTRIBUTES secAttrs)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSiz
e, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOp
tions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectFile, ICollection`1 diagnostics, ProjectReade
rSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectReader.GetProject(String projectFile, ProjectReaderSettings settings)
   at Microsoft.DotNet.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__28.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.<>c__DisplayClass70_0.<Execute>b__0()
   at Microsoft.Dnx.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Compiler.CompilerCommandApp.Execute(OnExecute execute, String[] args)
   at Microsoft.DotNet.Tools.Compiler.Program.Main(String[] args)
```

**Comment by cdmihai** [comment]
Should the ProjectContextBuilder catch this, or the code that calls it?

If it's the code that calls it, then I can add the check when resolving the arguments: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Compiler/CompilerCommandApp.cs#L100

That will make both Build and Compile resistant to this invalid input.

**Comment by cdmihai** [comment]
The publish command also appears to not sanitize against missing project.json: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L232

Now that we have 2 places that need to duplicate this sanitization, I propose that the `project.json is present` sanitization is done once, by ProjectContextBuilder.

**Comment by cdmihai** [comment]
@davidfowl @piotrpMSFT

**Comment by cdmihai** [comment]
Any inputs on this?

**Comment by blackdwarf** [comment]
On the Preview 2 tooling when I run `dotnet build` I get the following error and not an exception: `Couldn't find 'project.json' in current directory`. Also, given the move to msbuild this seems like something that will change. 

Do we want to close this issue?

**Comment by enricosada** [comment]
Fixed already in `preview2`

```
mkdir emptydir
cd emptydir
dotnet build
```

exit code is `1` and the error is:

```
Couldn't find 'project.json' in current directory
```

**Comment by Jackberry12** [comment]
Cześć wszystkim Jestem jack berry po imieniu i jestem bardzo prostym człowiekiem. Pracuję w firmie o nazwie aseiamicrofanance, w tej firmie rozdajemy
pożyczki o bardzo niskim oprocentowaniu 3%. Rozdajemy wszelkiego rodzaju
Pożyczka, w której potrzebujesz. Potrzebujemy tylko poważnych kandydatów, więc nie przychodź
tutaj i baw się z naszą firmą. Skontaktuj się z nami już dziś
nasz adres e-mail poniżej: e-mail: (aseiamicrofanance@gmail.com)****

**Comment by Jackberry12** [comment]
Przekazaliśmy ponad 1 miliard USD kredytów biznesowych dla ponad 15 000 właścicieli firm, takich jak Ty. Używamy własnej technologii wyznaczania ryzyka, aby zapewnić Ci odpowiedni kredyt na działalność gospodarczą, dzięki czemu możesz rozwijać swój biznes. Nasze usługi są szybkie i niezawodne, pożyczki są zatwierdzane w ciągu 24 godzin od pomyślnego zastosowania. Oferujemy pożyczki o minimalnym zakresie od 5000 do maksymalnie 300 milionów dolarów, możesz nam przeciwdziałać za pośrednictwem naszego adresu e-mail (aseiamicrofanance@gmail.com)

**Comment by Jackberry12** [comment]
Hello All I am jack berry by name, and am a very simple man. I work in a company called aseiamicrofanance, in this company we give out
loans with a very low interest rate of  3%. We give out all kinds of
loan in which you need. We need only serious applicants, so don't come
here and play with our business. Feel free to contact us today through
our email address Below: Email: (aseiamicrofanance@gmail.com)

**Comment by Jackberry12** [comment]
We have provided over $1 Billion in business loans to over 15,000 business owners just like you. We use our own designated risk technology to provide you with the right business loan so you can grow your business. Our services are fast and reliable, loans are approved within 24 hours of successful application. We offer loans from a minimum range of $5,000 to a maximum of $300 million,you can counteract us through our email address(aseiamicrofanance@gmail.com)
