### ISSUE TITLE
Need better warning/error message when ASP.NET Core 1.1 project is opened using CLI for .NET Core 2.1

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#9120]
## Steps to reproduce
With VS 15.7 + CLI for .NET Core 2.1 (CLI 2.1.300 or higher) installed,

1. Open ASP.NET Core 1.1 project that was created using a previous version of the CLI
2. View Error list 

## Actual behavior
You see the warnings below
![image](https://user-images.githubusercontent.com/8246794/39138907-a150cbaa-46d5-11e8-8300-340e4835f48b.png)

For the ASP.NET Core 1.1 / 1.0 cases, the warning shows the incorrect message. Removing the tool from csproj as suggested by the message will not put you in a working state. 

## Expected  behavior
- Warning/Error should not say that the tools "can be removed from this project"
- It should point to an fwlink where we explicitly ask the user to drop a global.json and pin their CLI version, assuming other places such as the build server will also have that pinned version of the CLI installed

**Comment by livarcocc** [comment]
Closing this one in favor of https://github.com/dotnet/cli/issues/9119

**Comment by balachir** [comment]
After discussing with Kathleen, we agreed that for this ASP.NET Core 1.1 case, users should see ***an error*** rather than a warning.

Here is the proposed text for the error message:
```DotNetCliToolReference in .NET Core 1.1 or earlier are not supported by this version of the .NET Core SDK. Projects targeting NET Core 1.1 or earlier versions should pin the SDK in global.json. See [[]]```

@KathleenDollard, can you review the text and provide a new fwlink?

Including @jimmylewis @mairaw

**Comment by livarcocc** [comment]
I need the actual "more documentation link" in order to be able to close this issue.

**Comment by KathleenDollard** [comment]
https://aka.ms/sdk1-1-fails-on-sdk2-1

**Comment by natemcmaster** [comment]
Can this be scoped to only produce an error for Microsoft.EntityFrameworkCore.Tools.DotNet? This is the only one that is not backwards compatible with .NET Core 1.1. All others should still work just fine.

cc @divega @ajcvickers @bricelam

**Comment by KathleenDollard** [comment]
After further discussion, there will be a single error message for all cases - #9119. 

This is because the problem does not relate to the version of .NET Core being targeted, but the version of EF that is in use. 

We cannot be accurate in when this warning message is displayed and it may inaccurately suggest a global.json file, so we will expand the #9119 message to include a link for EF that will explain the scenario. 

 @divega @ajcvickers @bricelam this somewhat increases the probability that users will see the warning/error message that users see when using the new tools with the older versions of EF.

**Comment by livarcocc** [comment]
Me, @natemcmaster and @KathleenDollard got together again and decided not do do anything special for a particular TFM, because the TFM is not really the best pivot for this. Instead, we will massage the message a little bit and add more details about pinning if you have EF in the more details page.

**Comment by livarcocc** [comment]
I should have read @KathleenDollard's comment above before writing mine above. Oh, well.

**Comment by ajcvickers** [comment]
@KathleenDollard @livarcocc  What are the conditions that trigger this warning?
