### ISSUE TITLE
dotnet test doesn't discover the runner when the project targets dnx451 as the first framework

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#913]
Take the sample [here](https://github.com/piotrpMSFT/dotnet-test-samples/) and change the project.json to:

```
{
  "version": "1.0.0-*",
  "dependencies": {
    "xunit": "2.1.0"
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Runtime": ""  
      },
      "dependencies": {
        "xunit.runner.console": "2.1.0"
      }
    },
    "dnxcore50": {
      "imports": "portable-net45+win8",
      "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23714",
        "dotnet-test-xunit": "1.0.0-dev-*"   
      }
    }
  },
  "testRunner":"xunit"
}
```

Then restore, build and test:

```
E:\temp\x\dotnet-test-samples>dotnet test
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, String args, NuGetFramework framework) in D:\vsoagent\_work\11\s\src\Microsoft.DotNet.Cli.Ut
ils\Command.cs:line 53
   at Microsoft.DotNet.Tools.Test.Program.RunConsole(ProjectContext projectContext, CommandLineApplication app, String testRunner) in D:\vsoagent\_work\11\s\src
\Microsoft.DotNet.Tools.Test\Program.cs:line 98
   at Microsoft.DotNet.Tools.Test.Program.<>c__DisplayClass0_0.<Main>b__0() in D:\vsoagent\_work\11\s\src\Microsoft.DotNet.Tools.Test\Program.cs:line 49
```

Remove `dnx451` and everything works.

cc @piotrpMSFT

**Comment by victorhurdugaci** [comment]
This is funny. It might be caused by this line: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Test/Program.cs#L57

If you change the order of the TFMs (put dnxcore50 first and then dnx451), it seem to work.

**Comment by piotrpMSFT** [comment]
At the moment, the behavior will be to skip 451 [or any TFM for which we don't have a runner handy].

Can you re-order to get unblocked, @victorhurdugaci ?

**Comment by victorhurdugaci** [comment]
Yes, I can reorder. I still think this should be fixed for rc2. It's confusing and very hard to figure out what's wrong.

**Comment by victorhurdugaci** [comment]
It is not really blocking for us

**Comment by piotrpMSFT** [comment]
totally agree, just want to keep you unblocked.

**Comment by andschwa** [comment]
It also doesn't work if you target `netstandardapp1.5`, but fortunately you can target `dnxcore50` and import the former framework to get things working happily.

**Comment by piotrpMSFT** [comment]
This has been fixed.
