### ISSUE TITLE
Different CLI syntax for --source

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#9131]
## Steps to reproduce

```console
>dotnet restore --help
Usage: dotnet restore [options]

Options:
  -h, --help                           Show help information.
  -s, --source <SOURCE>                Specifies a NuGet package source to use during the restore.
```

Emphasis on last line.

```console
C:\git\PowerShell\src\powershell-win-core>dotnet tool install --help
Usage: dotnet tool install [options] <PACKAGE_ID>

Arguments:
  <PACKAGE_ID>   NuGet Package Id of the tool to install.

Options:
  -g, --global                  Install user wide.
  --tool-path                   Location where the tool will be installed.
  --version                     Version of the tool package in NuGet.
  --configfile                  The NuGet configuration file to use.
  --source-feed <SOURCE_FEED>   Adds an additional NuGet package source to use during installation.
```

Emphasis on last line.

## Expected  behavior

Same syntax for NuGet feeds across CLI. Also, the help text suggests different semantics. Is that true?

## Environment data
dotnet --version
2.1.300-preview2-008530

**Comment by livarcocc** [comment]
This was a conscious decision we made because we felt like --source had little meaning on the context of tool when referring to source feed and there was a high likely hood with it being confused with some sort of build from source tool experience, like the one we talked about a while ago. 

Also, we couldn't change the restore parameter as that would be a breaking change.

So, right now, this is by design.

**Comment by richlander** [comment]
Just want to register that I think this is the wrong decision. It's one confusion vs another. Also, I don't think this choice lines up well a CLI design philosophy.

Folks reading this ... do you want status-quo or alignment of syntax for NuGet sources across the CLI syntax?

**Comment by omajid** [comment]
There is also concern about the differences between the two options here: https://github.com/dotnet/cli/issues/9062
