### ISSUE TITLE
Add numbers ("Preview 1" vs "Preview 2") back into the branding strings in installers

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#9136]
I cannot tell Preview 1 vs Preview 2 installers apart in Windows ARP. I can only differentiate them by install date. Please add numbers so we can tell previews / RCs apart.

**Comment by livarcocc** [comment]
@leecow this was the design that both you and Lee asked us to do. Though, in ARP, you should see a version on the right side of the program list.

Once I have an agreement from @leecow, we can make the change, assuming it will get approved.

cc @KathleenDollard

**Comment by richlander** [comment]
Yes, we did. Someone asked us to go this direction. We now realize that it is unworkable.

**Comment by KathleenDollard** [comment]
Agree with "Preview 1" etc.

We should use the same words here we would use in Release Notes, blog posts or on stage, which is what was decided.
________________________________

**Comment by leecow** [comment]
Livar, can the Window title carry the full version string but the banner only 'Preview N', 'RC N', etc? 

 eg

* Window title: `Microsoft .NET Core SDK 2.2.100-008530 - Preview 1 (x64) Installer'
* Banner title: `Microsoft .NET Core SDK 2.2.100 - Preview 1'

**Comment by livarcocc** [comment]
Given that our next release is going to be RC1, could we just punt this issue to 2.2? Just so that we can clear on priorities?

If so, I would feel more comfortable in making the installer changes.

**Comment by livarcocc** [comment]
@leecow is this something that we still want to do, now that we have all decided that our branding will only say preview in the files, etc?

cc @johnbeisner

**Comment by leecow** [comment]
I believe we have decided to have all branding and file version strings *preview-[buildnumber]*. @richlander - any objections or argument to make the Windows ARP entry different?

**Comment by livarcocc** [comment]
The preview branding is back on the installers, like preview6. I am going to close this issue.
