### ISSUE TITLE
Uninstalling .NET Core removes dotnet directory from path

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#9138]
I had nearly 20 versions of .NET Core installed. I decided to uninstall them all but one (2.1.300-preview2). After that, "dotnet" didn't work anymore since the PF directory was removed from the path. Do we have any testing on this?

I decided to uninstall this last version, too, to see what was left. I assume that the 1.0.0 folder was a bug that is no longer interesting. It does seem like there is no automatic cleanup mechanism for the NuGetFallbackFolder. It seems like there should be. Thoughts?

```console
C:\Users\rlander>dir "\Program Files"\dotnet\sdk
 Volume in drive C is Windows
 Volume Serial Number is 384B-0B6E

 Directory of C:\Program Files\dotnet\sdk

04/25/2018  08:59 AM    <DIR>          .
04/25/2018  08:59 AM    <DIR>          ..
04/24/2018  02:47 PM    <DIR>          1.0.0
04/25/2018  08:50 AM    <DIR>          NuGetFallbackFolder
               0 File(s)              0 bytes
               4 Dir(s)  151,898,918,912 bytes free
```

**Comment by livarcocc** [comment]
For the fallback folder, we have a bug here in the CLI tracking that already. For the PATH, we have not seen this issue before. Are you sure that there was not something else going on here? I just tried this a couple of times and dotnet continues to work and point to my program files installation.

**Comment by livarcocc** [comment]
Closing as in 3.0 we won't have the lzma and we are not doing anything for it until then. Also, I couldn't repro the other part of your issue.
