### ISSUE TITLE
Design time facades should be auto-ref'ed for any framework that has them

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#914]
For any classic framework that contains design-time facades (EG: desktop) all of those facades should be automatically referenced to match the behavior of MSBuild.

Folks were trying to workaround this by manually adding the framework assemblies to their project: https://github.com/dotnet/cli/issues/579
Which would work in DNX, but then fail in Visual Studio.

Similarly NuGet is trying to make a change to workaround the fact that these packages have done this: https://github.com/NuGet/Home/issues/1855

Seems to me like the path of least resistance here would be to get the CLI to match the behavior of MSBuild.  That behavior can be seen in the ImplicitlyExpandDesignTimeFacades target in Microsoft.NETFramework.CurrentVersion.targets.

**Comment by yishaigalatzer** [comment]
@ericstj would removing the reference from the package just make it work in visual studio msbuild based projects? In that case wouldn't a simpler fix would be to remove the reference for the desktop TFMs?

**Comment by ericstj** [comment]
@yishaigalatzer yes that will work for VS Msbuild based projects and should be done regardless.

For the package to work in CLI as well, CLI needs to do this work.

If this work is done by CLI then the NuGet work would just be "nice to have" it wouldn't be blocking anything.

**Comment by bricelam** [comment]
Dupe of #164

**Comment by davidfowl** [comment]
Closing this as its a dupe. I'm more ok doing this but doing it that way msbuild does seems a bit horrible. Can we do something s little less bad? Another thing I dislike is the fact that it happens so late. Today the solution explorer shows the entire depends graph including facades but msbuild applies them at compile time which means you don't really know what you're referencing
