### ISSUE TITLE
Build failures in 'prodcon/cli/release/2.1.3xx/' - '20180425.02'

### ISSUE THREAD

**Issue by jcagme** [dotnet/cli#9145]
@dotnet-mc-bot commented on [Wed Apr 25 2018](https://github.com/dotnet/core-eng/issues/3368)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629756
  - **Agent:** DDVSOLINUXAGE003
  - **Error log:** An error occurred while sending the request....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629755
  - **Agent:** DDVSOLINUXAGE002
  - **Error log:** The previous error was converted to a warning because the task was called with ContinueOnError=true....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629759
  - **Agent:** DDVSOMACAGE006
  - **Error log:** 15:07:00.114     1>/Users/buildagent/agent/_work/0/s/test/MsBuildScript.Tests/runtests.target(0,0): error MSB4018: The "EnsureFileExistsOnAzureBlobStorage" task failed unexpectedly....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629762
  - **Agent:** DDVSOWINAGE015
  - **Error log:** 15:20:09.537     1>E:\A\_work\0\s\test\MsBuildScript.Tests\runtests.target(0,0): error MSB4018: The "EnsureFileExistsOnAzureBlobStorage" task failed unexpectedly....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629763
  - **Agent:** DDVSOWINAGE018
  - **Error log:** 15:19:57.764     1>E:\A\_work\0\s\test\MsBuildScript.Tests\runtests.target(0,0): error MSB4018: The "EnsureFileExistsOnAzureBlobStorage" task failed unexpectedly....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629894
  - **Agent:** DDVSOLINUXAGE002
  - **Error log:** An error occurred while sending the request....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629895
  - **Agent:** DDVSOLINUXAGE003
  - **Error log:** An error occurred while sending the request....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629898
  - **Agent:** DDVSOMACAGE006
  - **Error log:** 15:42:45.819     1>/Users/buildagent/agent/_work/0/s/test/MsBuildScript.Tests/runtests.target(0,0): error MSB4018: The "EnsureFileExistsOnAzureBlobStorage" task failed unexpectedly....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629901
  - **Agent:** DDVSOWINAGE012
  - **Error log:** 15:52:06.258     1>E:\A\_work\0\s\test\MsBuildScript.Tests\runtests.target(0,0): error MSB4018: The "EnsureFileExistsOnAzureBlobStorage" task failed unexpectedly....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1629902
  - **Agent:** DDVSOWINAGE015
  - **Error log:** 15:48:28.932     1>E:\A\_work\0\s\test\MsBuildScript.Tests\runtests.target(0,0): error MSB4018: The "EnsureFileExistsOnAzureBlobStorage" task failed unexpectedly....

@jcagme, @markwilkie, @mmitche

**Comment by livarcocc** [comment]
What is this and is this being filed in the CLI? From what I can see in the logs, a bunch of these failed because the ASP.NET runtime we were being told to target could not be found in the blob storage.

**Comment by mmitche** [comment]
@livarcocc We turned on issue filing due to error classification.  I am pretty sure that this is a result of the build definition changes I made.  I think PB_AssetRootUrl was expected to be in the ambient environment in addition to the command line.

**Comment by livarcocc** [comment]
Ok to close this one then? Or do you want to use it to track something?

**Comment by mmitche** [comment]
Okay to close
