### ISSUE TITLE
Dotnet publish => The 'Publish' target is not supported without specifying a target framework

### ISSUE THREAD

**Issue by mszymankiewicz** [dotnet/cli#9149]
## Steps to reproduce
When I use command:
`dotnet publish /p:Configuration=Release`

I get error:
`C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\buildCrossTargeting\Microsoft.NET.Sdk.targets(31,5): error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application.`

I try execute with params:
` --runtime="ubuntu.16.10-x64"` 
or
`-f="netcoreapp2.0"`

and not working.

## Environment data
`dotnet --info` output:
`Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54`

**Comment by peterhuene** [comment]
Hi @mszymankiewicz,

Thank you for your issue.  The `--framework/-f` option is required when your project targets multiple frameworks.

When you run `dotnet publish` with `-f netcoreapp2.0`, what error are you encountering?

**Comment by livarcocc** [comment]
Closing because we don't have a repro for it.

**Comment by Muchaszewski** [comment]
Repro steps:
**Paths may differ in your solution**
```
dotnet new console -o Console
dotnet new classlib -o Library
```

Edit Console.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>

</Project>
```

Edit Library.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>

</Project>
```

Add Console.sln file for the solution
```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.28010.2026
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Console", "Console\Console.csproj", "{DE799C97-38D3-4EC5-B78F-B680AF154F6B}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Library", "Library\Library.csproj", "{AC7D8A30-76B0-4D76-8541-DB9C59DB9883}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{DE799C97-38D3-4EC5-B78F-B680AF154F6B}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{DE799C97-38D3-4EC5-B78F-B680AF154F6B}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{DE799C97-38D3-4EC5-B78F-B680AF154F6B}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{DE799C97-38D3-4EC5-B78F-B680AF154F6B}.Release|Any CPU.Build.0 = Release|Any CPU
		{AC7D8A30-76B0-4D76-8541-DB9C59DB9883}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{AC7D8A30-76B0-4D76-8541-DB9C59DB9883}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{AC7D8A30-76B0-4D76-8541-DB9C59DB9883}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{AC7D8A30-76B0-4D76-8541-DB9C59DB9883}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {722BBE42-30AA-447B-9236-791FA26CB3E3}
	EndGlobalSection
EndGlobal
```

Run:
`dotnet publish Console.sln -c Release`

Notice the error while:
```
C:\Program Files\dotnet\sdk\2.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.CrossTargeting.targets(31,5): error : The 'Publish' target is not supported without specifying a target framework. The current project targets multiple frameworks, please specify the framework for the published application. [...\Library\Library.csproj]
```

Please remove the issue or provide solution to this problem as this error causes console to return ERRORCODE = 1 thus breaking our CI script.

Thank you in advance
