### ISSUE TITLE
'not possible to find any compatible framework version' error when running OpenChain project

### ISSUE THREAD

**Issue by wyang41** [dotnet/cli#9170]
## Steps to reproduce
I was following the steps given by OpenChain platform (https://docs.openchain.org/en/latest/general/running-openchain.html), and I downloaded .NET from your website, not from Git. The APP source files are provided by OpenChain, after I ran 'dotnet run' command in the directory with OC source files, it failed. 

Have to mention,  the version of .NET I installed might be quite different from what OpenChain team had when editing the tutorial doc. Since the step before run, 'dotnet restore', also failed. And I used 'dotnet migrate' as a replacement. Before this command, the source files are 'Program.cs, data, project.json'. After 'dotnet migrate', they changed into 'Openchain.csproj, backup, data, Program.cs, bin, obj'.

I have tried to change the code in Openchain.csproj, where described the .NET version. I changed '1.0.4' to '2.0.7', but 'Unhandled Exception: System.IO.FileLoadException' happened.

Openchain.csproj:

<Project Sdk="Microsoft.NET.Sdk.Web">                                           
                                                                                
<PropertyGroup>                                                               
<TargetFramework>netcoreapp1.0</TargetFramework>                                             
<PreserveCompilationContext>true</PreserveCompilationContext>               
<AssemblyName>Openchain</AssemblyName>                                      
<OutputType>Exe</OutputType>                                                
<PackageId>Openchain</PackageId>                                            
<RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion>                    
<PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;dnxcore50;portable-net45+win+wpa81+    wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10</PackageTargetFallback>           
</PropertyGroup> 

## Expected  behavior

The OpenChain APP runs well and then I would do the configuration.

## Actual behavior

$ dotnet run
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by AArnott** [comment]
@wyang41 I do not work on this repo, and I'd appreciate you not mentioning me here unless you have something in particular to say to me or need my input on a matter by phrasing a question with the mention.

**Comment by livarcocc** [comment]
Your application targets version 1.0.4 of the runtime. If you want to run it, you need to go and acquire that runtime. You can do that here: https://www.microsoft.com/net/download/all. You can install rutime 1.0.11 and your application will automatically rollforward from 1.0.4 to 1.0.11.

Also, I do not believe this is the right repo for this issue either. If there had been some problem with the migration command or some other specific issue with the tooling, we could help out, but this is a project that seems to still be using project.json, which we stopped supporting since 1.0.0-preview2 and the repo itself may need some work to be pulled into the new tooling.
