### ISSUE TITLE
Remove source-build patches in cli

### ISSUE THREAD

**Issue by dseefeld** [dotnet/cli#9176]
In preview2, 11 patches were added to source-build to enable cli to build in source-build.  These patches should be incorporated into the cli code and removed from the source-build repo.  The patches are here: https://github.com/dotnet/source-build/tree/dev/release/2.1/patches/cli

**Comment by livarcocc** [comment]
I believe this has now been addressed with the exception of the crossgen issue for ProjectJsonMigration.dll.
