### ISSUE TITLE
ExitCode of ConsoleApp on Linux is not preserved

### ISSUE THREAD

**Issue by joepeer** [dotnet/cli#918]
On Ubuntu, when I run a small sample that changes the exit code to a value different than 0, doing "$?" will return 1 instead of the actual exit code returned.

```csharp
       public static int Main(string[] args)
       {
           Console.WriteLine("Running child process , will exit with 0x4001");
            return 0x4001;
       }
```

On windows it correctly gives back the exit code that was set.

**Comment by moozzyk** [comment]
On non-windows "exit takes only integer args in the range 0 - 255" - http://tldp.org/LDP/abs/html/exitcodes.html

**Comment by joepeer** [comment]
Well take explain it.  Thanks
