### ISSUE TITLE
Nuget Dependency Insanity - Conflicting Dependency resolved yet still gives an error.

### ISSUE THREAD

**Issue by rob123456** [dotnet/cli#9181]
## Steps to reproduce

- Create two distinctly named nuget packages which contain the same old version of a Newtonsoft.Json DLL in the lib folder.
- Create a new project which references both of the previously created nuget packages.
- Add a reference to the latest Newtonsoft.Json package in the newly created project.
- Use that reference for something. e.g. serialize something  `string stuff = JsonConvert.SerializeObject("world");`
- Build

## Expected  behavior
- I expect it to use the latest version of Newtonsoft.Json and automatically redirect references to previous versions.
- I expect it to successfully build.

## Actual behavior
- Build fails with a warning followed by a seemingly paradoxical error:
`C:\Program Files\dotnet\sdk\2.1.105\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3243: No way to resolve
conflict between "Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" and "Newtonsoft.J
son, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". Choosing "Newtonsoft.Json, Version=11.0.0.0, Cu
lture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" arbitrarily. [E:\Projects\crsl\Standard.Service\Standard.Service.csproj]

SiteSettingsService.cs(156,20): error CS0433: The type 'JsonConvert' exists in both 'Newtonsoft.Json, Version=9.0.0.0, C
ulture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' and 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken
=30ad4fe6b2a6aeed' [E:\Projects\crsl\Standard.Service\Standard.Service.csproj]`

Important to note: 
- If I remove a reference to either one of the packages the project then successfully builds. It doesn't matter which one I select as long as I remove one of them. 
- If I downgrade one of the packages so it's using an even older version of Newtonsoft.Json the project successfully builds. It only seems to fail when there are two nuget packages referenced containing the same version of a Newtonsoft.Json dll in the lib folder.
- If I reference the same version of Newtonsoft.Json in the afforementioned project as is inside both nuget packages the build succeeds.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.105\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by livarcocc** [comment]
When you say that these packages contain a reference to newtonsoft.json, is that as a package reference itself or is it the dll packaged up with the other assemblies in the package?

cc @dsplaisted to take a look at this.

**Comment by dsplaisted** [comment]
> Create two distinctly named nuget packages which contain the same old version of a Newtonsoft.Json DLL in the lib folder.

Generally you aren't supposed to do this.  Instead, each of the packages should have a package dependency on Newtonsoft.Json.  Is there some reason this doesn't work?

**Comment by rob123456** [comment]
@dsplaisted Unfortunately the nuget packages are third party dependencies. I suspect they've been generated in Teamcity using Octopack. I believe that Octopack tends to bundle everything together that would be necessary for immediate deployment.

So @livarcocc it's a dll in the lib folder of the nuget package.

**Comment by dsplaisted** [comment]
@rob123456 I'm not very familiar with Octopack but I think that the packages it creates are probably not meant to be referenced like normal NuGet packages.  It probably uses NuGet as a convenient format to zip a bunch of files together and include metadata, but you can't necessarily reference them as packages in order to use the APIs from the libraries in them.

Whether created by Octopack or not, two packages that include (possibly different versions of) the same assembly in their lib folders are generally not going to be compatible with each other.

**Comment by livarcocc** [comment]
@rob123456 not really. The issue here is that one package is carrying one assembly as one version and dependency. The other is doing the same, but at a different version. When someone tries to use said packages together, one of them will lose, as the wrong reference assembly version will be used from the perspective of the losing package.
