### ISSUE TITLE
Can't install dotnet sdk on Ubuntu 16.04 xenial from repo feed

### ISSUE THREAD

**Issue by willianns** [dotnet/cli#9183]
I'm trying to install dotnet sdk on a fresh install of Ubuntu 16.04 based OS following the steps on (https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current) but it's fail on `apt-get update` 

As described on 'actual behavior' it seems the repo is down as we can see through the link below 
(https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/dists/xenial/main/binary-amd64/)

O another hand Artful is ok
(https://packages.microsoft.com/repos/microsoft-ubuntu-artful-prod/dists/artful/main/binary-amd64/)

maybe the feed URL has changed?

## Steps to reproduce

On a Ubuntu 16.04 based distro follow the instructions at https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current

`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`
`sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg`
`sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'`

`sudo apt-get install apt-transport-https`
`sudo apt-get update`
`sudo apt-get install dotnet-sdk-2.1.105`

## Expected  behavior

.NET SDK 2.1.105 installation with success

## Actual behavior

Fail to run `sudo apt-get update`

W: The repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod/dists/xenial/main/binary-amd64/Packages  404  Not Found

**Comment by leecow** [comment]
I can browse the feed and just successfully installed 2.1.105 on a green 16.04 container. 

Give this a try - Delete  the `dotnetdev.list` you created (or rename to something other then *.list) and register the feed with the following. 

```
wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
```

**Comment by leecow** [comment]
Hang on before you try, I am seeing something different further along in the process. 

```
Err:1 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 dotnet-runtime-deps-2.1.0-preview2-26406-04 amd64 2.1.0-preview2-26406-04-1
  404  Not Found
Get:2 http://archive.ubuntu.com/ubuntu xenial/universe amd64 liburcu4 amd64 0.9.1-3 [47.3 kB]
Err:3 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 dotnet-host amd64 2.1.0-preview2-26411-07-1
  404  Not Found
Err:4 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 dotnet-hostfxr-2.0.7 amd64 2.0.7-1
  404  Not Found
Err:5 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 dotnet-runtime-2.0.7 amd64 2.0.7-1
  404  Not Found
Err:6 https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 dotnet-sdk-2.1.105 amd64 2.1.105-1
  404  Not Found
```

... investigating.

**Comment by leecow** [comment]
There's an ongoing outage in the service which is being worked on. Repo is partly up now and the rest should follow shortly.

**Comment by willianns** [comment]
Everything is ok Up and running again. Thank you guys!
