### ISSUE TITLE
NuGet parameters like "--configfile" and "--no-cache" apply to many commands but are only shown in "restore --help"

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#9186]
NuGet parameters like `--configfile` and `--no-cache` apply to many commands (e.g. restore, build, and publish), but they are only shown in the help text for `restore`.  I think these parameters should be shown in the help text for all commands to which they apply.

## Steps to reproduce
Note the "file does not exist" errors are expected and mean the command-line parameter is working.

```
> dotnet new classlib --no-restore

> dotnet restore --help | findstr -i configfile
  --configfile <FILE>                  The NuGet configuration file to use.

> dotnet restore --configfile foo
NuGet.targets(497,5): error : File 'D:\Temp\classlib\foo' does not exist. [D:\Temp\classlib\classlib.csproj]

> dotnet build --help | findstr -i configfile

> dotnet build--configfile foo
NuGet.targets(497,5): error : File 'D:\Temp\classlib\foo' does not exist. [D:\Temp\classlib\classlib.csproj]
```

## Environment data
`dotnet --info` output:
```
Version:   2.1.300-rc1-008671
```

**Comment by livarcocc** [comment]
This is by design.

We considered it and thought it was actually going to pollute the help content for the other commands. So, we kept it out.

**Comment by livarcocc** [comment]
It is called out in the document pages, where we have space for more details.
