### ISSUE TITLE
dotnet restore fails: 401 Unauthorized

### ISSUE THREAD

**Issue by SGStino** [dotnet/cli#9196]
## Infrastructure:
- vsts-agent running in docker
- vsts agent running on windows machine
- tfs 2018 on-premise 

## Steps to reproduce
- Create a Nuget feed on the TFS server.
- Create ASP.NET Core project, reference one nuget package from Internal feed
- Build on Windows based agent
- Build on Docker image

## Expected  behavior
Both builds should succeed by using the OAuth token from VSTS?
## Actual behavior
Docker based build fails: 401 Unauthorized.
```
NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://<tfsserver>/tfs/DefaultCollection/_packaging/<packagesource>/nuget/v3/index.json. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at NuGet.Protocol.HttpSource.<>c__DisplayClass12_0`1.<<GetAsync>b__0>d.MoveNext()
```

The difference between the windows and the linux machine is that the windows machine runs as a service user that is known in TFS, and as such is authenticated via NTLM?

And the linux container is outside of the domain, and as such, not authenticated
However, specifying a PAT as "Credentials for feeds outside this account/collection" doesn't seem to help:

![image](https://user-images.githubusercontent.com/5156315/39619429-1649a0d4-4f88-11e8-93f7-50fdd3a5a77e.png)

I'm guessing this is becuase it is not "Outside of this account/collection" and as such doesn't use the credentials?

## Environment data
`dotnet --info` output: (official docker image)
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6902
