### ISSUE TITLE
dotnet tool install --source-feed doesn't support relative local paths

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#9209]
As described in the headline. On Windows this would work. On UNIX an absolute path is required.

**Comment by livarcocc** [comment]
I believe this has actually been fixed in our nightlies already.

@peterhuene to confirm.

**Comment by peterhuene** [comment]
This is fixed for 2.1.300 RTM with #9137.

**Comment by peterhuene** [comment]
I'm closing this issue.  If you see this problem persist out of the `release/2.1.3xx` branch or when 2.1.300 ships, please reactivate this issue.  Thank you!
