### ISSUE TITLE
--list-sdks is broken

### ISSUE THREAD

**Issue by jnm2** [dotnet/cli#9210]
I'm positive I remember --list-sdks working before, but I can't get it to work now:
```
> dotnet --list-sdks
Unknown option: --list-sdks
.NET Command Line Tools (2.1.105)
```

Ironically:
```
> dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information..
  --list-sdks       Display the installed SDKs.
```

Also, there is a double period after `Display .NET Core information` which should be fixed.

What information do you need? I have only SDKs 1.1.8 x64 and 2.1.105 x64 installed.

**Comment by livarcocc** [comment]
You need CLI 2.1.300-preview1 and forward for this to work. The command is not supported on older versions of the CLI.

**Comment by jnm2** [comment]
@livarcocc Ah, my mistake. Why was it still advertising `--list-sdks` then, since I had uninstalled the preview? This seems wrong.

**Comment by livarcocc** [comment]
That's actually a great question. This command is actually supported in the runtime itself and not in the SDK.

Can you tell us what version of the runtime you have installed?

@steveharter any chance this is happening because the runtime was uninstalled but the hostfxr is still there?

**Comment by jnm2** [comment]
At the time, I had only SDKs 1.1.8 and 2.1.105 installed, and I assume only whatever runtime versions come with those.

**Comment by steveharter** [comment]
The basic help is from running "dotnet.exe" will show `--list-sdks` and `--list-runtimes` but those commands will not work on < 2.1. This will be the case unless we create and issue and move the help to hostfxr.dll (or add that functionality to < 2.1).
