### ISSUE TITLE
Fails to invoke custom global tool when it claims to have multiple project files

### ISSUE THREAD

**Issue by fubar-coder** [dotnet/cli#9219]
## Steps to reproduce

```
git clone https://github.com/fluentmigrator/fluentmigrator.git
dotnet tool install -g FluentMigrator.DotNet.Cli
dotnet fm
```

## Expected  behavior

It should've started the `dotnet-fm` tool.

## Actual behavior

It complains about problems with multiple proejct files, which it shouldn't check when it can invoke a custom tool.

## Environment data
`dotnet --info` output:

```
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17661
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  1.0.0-preview5-004232 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005051 [C:\Program Files\dotnet\sdk]
  1.1.0-preview1-005077 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0-preview1-005977 [C:\Program Files\dotnet\sdk]
  2.0.2-vspre-006949 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview1-002111-00 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
Can you tell us exactly which error message you are seeing? During the tool invocation, we don't do these checks, could the tool itself be doing this?

**Comment by fubar-coder** [comment]
The tool `dotnet-fm` definitely isn't doing this.

The error message:

```
Specify which project file to use because this 'C:\Users\fubar\Source\Repos\fluentmigrator' contains more than one project file.
```

**Comment by livarcocc** [comment]
Ah, I see what is going on here. When you invoke the tool using dotnet, it goes through the CLI resolvers. One of the resolvers we use is for the old DotnetCLIToolReference, which is throwing the error above because you have more than one csproj in the folder. In this case, I would suggest invoking your tool directly through dotnet-fm or removing one of the csprojs from the folder.

We can change the order of execution here as it would qualify as a breaking change.

**Comment by fubar-coder** [comment]
Funny thing is, there aren't multiple csproj files, just additional "proj" files.

**Comment by livarcocc** [comment]
We look at *proj I believe. We support fsharp, csharp and vb on the CLI!

**Comment by dasMulli** [comment]
Question is if it is better to change the precedence or not error out on multiple *proj files but just return no results (giving the next resolvers a chance).
May be better so the deprecated feature can still be used with the same resolution behaviour where it has worked before but not cause errors for scenarios in which it hasn't worked before anyway.

**Comment by livarcocc** [comment]
We can't change the precedence as that would block project tools from working when you have a global tool with the same name. Given that project tools would be physically closer, I believe that is the wrong choice.

We could not error out and give a chance to the other resolvers, but that would be a breaking change from the point of view of project tools.

**Comment by livarcocc** [comment]
I am going to close this bug for now as won't fix. This does not seem to hit many people and the work around is to not have multiple projects in a single folder.
