### ISSUE TITLE
dotnet publish --output turns on self-contained mode?

### ISSUE THREAD

**Issue by winzig** [dotnet/cli#9223]
I've read the documentation for `dotnet publish` and it has notes in there that --self-contained mode is set to true if you are doing a runtime-specific publish. But I am not, and it still appears to be producing a self-contained release, when I specify an output directory. At least I assume that is why I am seeing what appears to be all the Microsoft.* DLLs copied into the output folder?

## Steps to reproduce

`dotnet publish -c Release -o ~/myapp`

## Expected  behavior

dotnet should publish a non-self-contained app to ~/myapp.

## Actual behavior

dotnet publishes a self-contained app to ~/myapp

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     amzn
 OS Version:  2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by livarcocc** [comment]
I cannot repro this problem. How are you establishing that your app is being published as self-contained?

Could you share your csproj with us? Also notice that if you have RuntimeIdentififer specified in your project, we will infer your app as self-contained.

**Comment by winzig** [comment]
@livarcocc I've never created a self-contained dotnet app, but based on the volume of Microsoft.* DLLs in the output directory, I was assuming that is what was happening? (I don't get these DLLs in the output directory when I don't explicitly set the output directory.)

I don't think I've specified RuntimeIdentifier anywhere, but where should I look?

Our solution has 2 .csproj files, Library.csproj is our class library, and Web.csproj is for the web app that uses the library:

Library.csproj

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudSearch" Version="3.3.0.27"/>
    <PackageReference Include="AWSSDK.CloudSearchDomain" Version="3.3.0.27"/>
    <PackageReference Include="HtmlSanitizer" Version="4.0.185"/>
    <PackageReference Include="Sendgrid" Version="9.9.0"/>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.5"/>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.7"/>
    <PackageReference Include="Slack.Webhooks" Version="1.0.4"/>
    <PackageReference Include="Stripe.net" Version="15.7.0"/>
    <PackageReference Include="SharpRaven" Version="2.3.2"/>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Utils\"/>
    <Folder Include="Exceptions\"/>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data.SqlClient">
      <HintPath>..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\system.data.sqlclient\4.4.0\ref\netstandard2.0\System.Data.SqlClient.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

Web.csproj 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>aspnet-Web-121380B8-73D1-41A2-83C2-B45619EA5C46</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="2.6.375" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
	  <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Registration\" />
    <Folder Include="Models\RegistrationViewModels\" />
  </ItemGroup>
</Project>
```

**Comment by livarcocc** [comment]
When you there are more dlls in your publish folder than when you build. The reason being, when you just build, we reference your dependencies from nuget, instead of copying them to the build output folder.

For publish, we copy all the things you need that won't be in the framework.

You mentioned output above for this, if you just publish, do you get a reduced set of assemblies? Also notice that your publish folder is different from your build folder, normally, bin/Debug/netcoreapp2.1/publish/ for a framework dependent app.

For instance, these are the contents of a published framework dependent app that is just a regular console app:

```
myApp.deps.json          myApp.dll                myApp.pdb                myApp.runtimeconfig.json
```

This is my csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

</Project>
```

**Comment by winzig** [comment]
Sorry for the confusion, I am only talking about `publish` right now. I think I've figured out (sort of) what's happening. When I specify the -o command, I am providing a specific directory. It is then publishing all projects in the solution (the third is a UnitTest project). That UnitTest project seems to be the one that results in a ton of files (e.g. seemingly all of the Microsoft.* libraries). 

It's csproj looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".DS_Store" />
    <None Remove="TestLibrary\.DS_Store" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.6.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="1.2.0" />
    <PackageReference Include="MSTest.TestFramework" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library\Library.csproj" />
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestLibrary\Utils\" />
    <Folder Include="TestLibrary\Models\" />
  </ItemGroup>
</Project>
```

**Comment by livarcocc** [comment]
Could you instead publish the specific project to the output folder? Publishing multiple projects to the same output folder is dangerous, as dependencies may stomp on each other and lead to runtime failures.

**Comment by dasMulli** [comment]
The test sdk converts projects to console apps behind the scenes which could also be an issue, but to be clear: is it actually self contained (e.g. .exe file, clrjit.dll, mscorlib.dll and friends) or just a lot of files?

**Comment by livarcocc** [comment]
Closing this issue because we haven't had activity here in over ten days.
