### ISSUE TITLE
dotnet-install.sh Installs wrong version of the RC1 runtime causing Build failures

### ISSUE THREAD

**Issue by parekhkb** [dotnet/cli#9231]
We are using the obtain script `dotnet-install.sh` to install dotnetcore in CodeShip CI. However, this script installs the wrong version of the runtime when pointing to rc1. 

We then see build errors such as 
`error NU1102: Unable to find package Microsoft.NETCore.App with version (>= 2.1.0-rc1-26428-03)`

## Steps to reproduce
`curl -Lsfo ./dotnet-install.sh https://dot.net/v1/dotnet-install.sh`
`./dotnet-install.sh --verbose --version 2.1.300-rc1-008673`
`dotnet --info`

## Expected  behavior
Following would be installed
`Microsoft.AspNetCore.App 2.1.0-rc1-final`
`Microsoft.NETCore.App 2.1.0-rc1`

## Actual behavior
Following are installed:
`Microsoft.AspNetCore.App 2.1.0-rc1-30682`
`Microsoft.NETCore.App 2.1.0-rc1-26428-03`

## Environment data
`dotnet --info` output:
```
.NET CLI version info:
.NET Core SDK (reflecting any global.json):
Version:   2.1.300-rc1-008673
Commit:    f5e3ddbe73

Runtime Environment:
OS Name:     ubuntu
OS Version:  14.04
OS Platform: Linux
RID:         ubuntu.14.04-x64
Base Path:   /home/rof/cache/.dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
Version: 2.1.0-rc1-26428-03
Commit:  2c36b039fd

.NET Core SDKs installed:
2.1.300-rc1-008673 [/home/rof/cache/.dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.0-rc1-30682 [/home/rof/cache/.dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.0-rc1-30682 [/home/rof/cache/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.0-rc1-26428-03 [/home/rof/cache/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
Hi @parekhkb, this is actually an issue that we had where one of our builds was re-spun and overwrote the first one. Two builds with the same version.

The first build was wrong and had the wrong dependencies. The second one was correct. However, in between the two builds, the first one got pushed to our CDN, which is what the install script uses. So, you ended up installed the first build (wrong) cached by the CDN.

It is a timing problem where the CDN will eventually be flushed.

If you want, you can install the build directly from our blob URL here: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.300-rc1-008673/dotnet-sdk-2.1.300-rc1-008673-linux-x64.tar.gz

**Comment by parekhkb** [comment]
@livarcocc Thanks! Until the CDN is flished I will use the following for now. I tested it and it worked.
`./dotnet-install.sh --verbose --version 2.1.300-rc1-008673 --azure-feed https://dotnetcli.blob.core.windows.net/dotnet`

**Comment by parekhkb** [comment]
@martincostello the CDN appears flushed now. I removed the `--azure-feed` option in order to switch it to use the default, and it works.

**Comment by martincostello** [comment]
@parekhkb Yep, thanks. I tried this again last night after you linked me through to this and my macOS build is fine now.

**Comment by parekhkb** [comment]
Ugh, few hours later it's installing the wrong build again. Seems the CDNs aren't completely flushed...
