### ISSUE TITLE
dotnet-install.ps1 -Version 2.1.200 does not work on Ubuntu (also applies to Version 2.1.105)

### ISSUE THREAD

**Issue by bergmeister** [dotnet/cli#9234]
## Steps to reproduce

As part of the [PSScriptAnalyzer ](https://github.com/PowerShell/PSScriptAnalyzer)AppVeyor build, it installs the required version of the dotnet SDK. This has worked fine so far but when upgrading from 21.101 to 2.1.200, it does not work any more on AppVeyor Ubuntu image. The installation code is [here](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/tools/appveyor.psm1#L34) but effectively it is:

```powershell
$dotNetCoreSDKVersion = '2.1.200' # 2.1.105 also does not work but 2.1.101 works
Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1
.\dotnet-install.ps1 -Version $dotNetCoreSDKVersion
```

The corresponding PR with build is [here](https://github.com/PowerShell/PSScriptAnalyzer/pull/992)
Note that this also repoes on my local Ubuntu 16.04 VM

## Expected  behavior

It installs fine, as it does for version 2.1.101

## Actual behavior

Error being thrown:

```powershell
Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
At /home/appveyor/projects/psscriptanalyzer/dotnet-install.ps1:139 char:19
+ ...   default { throw "Architecture not supported. If you think this is a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Architecture no...tnet/cli/issues:String) [], RuntimeException
+ FullyQualifiedErrorId : Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
```

## Environment data

- AppVeyor Ubuntu image
- private Ubuntu 16.04 VM with PowerShell Core 6.1.0-preview.1

**Comment by bergmeister** [comment]
Just for FYI @IlyaFinkelshteyn

**Comment by livarcocc** [comment]
This is by design. Right now, the ps1 script only works on Windows. We have a bash script that works for all Unix based distros.

**Comment by bergmeister** [comment]
@livarcocc Just because this is the current state does not mean it should stay like that. Since PowerShell Core is fully supported on Unix systems, this feature should definitely be considered since PowerShell is the future that Microsoft promises us to manage ANYTHING from ANY SERVER.
Let's try running `dotnet-install.sh` from the [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) using the syntax from the [examples](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#examples):
```
$ ./dotnet-install.sh -h
bash: ./dotnet-install.sh: Permission denied
$ sudo dotnet-install.sh -h
sudo: dotnet-install.sh: command not found
```
Ok. Because I know a bit of Linux, I tried:
```sh
$ sh dotnet-install.sh -h
dotnet-install.sh: 12: set: Illegal option -o pipefail
```
What a helpful error message, now I have to look at the actual code and scratch my head. On most Unix systems, sh and bash are the same and I never had sh/bash compatibility problems. Last attempt is to use bash then, which finally works
```
$ sh dotnet-install.sh -h
````
I am running a standard Ubuntu VM version 16.04 (LTS) btw.
Linux shells might be better than cmd.exe but are still way inferior than PowerShell. Would you like to give a Linux Admin a batch script? No, so please add Unix support to the PowerShell script, even a minimalistic 'if we are on Linux, then lets try downloading and running the bash script' would help since there is usually an Internet connection. Here is a simple starter:
```powershell
if ($IsLinux -or $IsMacOS) {
   Invoke-WebRequest 'https://dot.net/v1/dotnet-install.sh' -OutFile dotnet-install.sh
   try {
   .\dotnet-install.sh -Version $dotNetCoreSDKVersion
   }
   finally {
      Remove-Item .\dotnet-install.sh
   }
}
```

**Comment by livarcocc** [comment]
There is an issue open for this here: https://github.com/dotnet/cli/issues/8278.
