### ISSUE TITLE
[loc][Query][Cli] Localizability of "Shutting down {0} (process \{1\})..."

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#9236]
Hi,
we have a question from a translator. Could you help please?

Source:
Shutting down {0} (process \{1\})...
{0} (process \{1\}) shut down successfully.
{0} (process \{1\}) failed to shut down: \{2\}

File Name:
LocalizableStrings.es.xlf

==========================================
Query:
Could you, please, define what will replace placeholder 1? 
We need to know whether "process" is a verb or a name in following strings
Shutting down {0} (process \{1\})...
{0} (process \{1\}) shut down successfully.
{0} (process \{1\}) failed to shut down: \{2\}

**Comment by livarcocc** [comment]
@peterhuene can you please provide the necessary information here and close this issue?

**Comment by peterhuene** [comment]
Hi @PDostalek:

`{0}` is the server name, such as `MSBuild server` (localized in the same .resx).
`{1}` is the process id (a numeric value).
`{2}` is an exception message (should already be localized).

"Process" in this context is a noun.

Thanks!

Peter

**Comment by PDostalek** [comment]
Perfect, thanks for needed info!
