### ISSUE TITLE
dotnet list --list-sdks command is unknown

### ISSUE THREAD

**Issue by phillipsj** [dotnet/cli#9237]
I am running version 2.1.105 on Ubuntu 18.04. 

## Steps to reproduce
When I run 

```
$ dotnet 
```

I get the following output:

```
Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET Core information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.

```
I then run 

```
$ dotnet --list-sdks
```

That is when I get the "Unknown option: --list-sdks".

## Expected  behavior

To list the SDKs.

## Actual behavior
```
Unknown option: --list-sdks
.NET Command Line Tools (2.1.105)
Usage: dotnet [runtime-options] [path-to-application]
Usage: dotnet [sdk-options] [command] [arguments] [command-options]
```

## Environment data

.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by jnm2** [comment]
Same as https://github.com/dotnet/cli/issues/9210?

**Comment by phillipsj** [comment]
@jnm2 yep it does. The answer you got was that it had to be greater than 2.1 to work. Which it is.

**Comment by jnm2** [comment]
@phillipsj Is it? Your text says the SDK version is 2.1.105 (runtime version 2.0), same as my question. The answer I got was that I needed a minimum of SDK 2.1.300-preview1 (runtime version 2.1). That answer would apply here to, wouldn't it?

**Comment by phillipsj** [comment]
Ah, yes it would.
