### ISSUE TITLE
Suggestion: Story for local development of NuGet packages as interdependent local projects

### ISSUE THREAD

**Issue by joelday** [dotnet/cli#9238]
As a developer, I want to be able to work on multiple projects that are ultimately published as interdependent NuGet packages without having to temporarily reconfigure projects to use ProjectReference instead of PackageReference and back and without having to publish in-progress work that has not been committed or merged yet.

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/4997.

**Comment by joelday** [comment]
Thanks @livarcocc!
