### ISSUE TITLE
Can't install global tool

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#9245]
## Steps to reproduce
`$ dotnet tool install -g Nuke.GlobalTool --source-feed C:\code\nuke\output --version 1.0.0`

Package file exists as `Nuke.GlobalTool.1.0.0.nupkg`.

## Actual behavior
```
Failed to install tool package 'nuke.globaltool': Access to the path 'C:\Users\matthias.koch\.dotnet\tools\.store\.stage\fpn34yfr.xj2' is denied.
Tool 'nuke.globaltool' failed to install. This failure may have been caused by:
* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  1.1.8 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by matkoch** [comment]
I'm also curious why the error cannot be a little more specific. If you find a package, and it's not marked as tool, why not say so? If a certain NuGet source couldn't be reached, why not say so? At least as a warning.

**Comment by livarcocc** [comment]
@peterhuene @wli3

**Comment by wli3** [comment]
As the error suggested. the stage file is not accessable.  (it is straight from lower level error).

We did see the error from manual test. But there is no repo after reboot.

**Comment by matkoch** [comment]
Console was started elevated. Just to let you know.

**Comment by matkoch** [comment]
Rebooted. Same error.

**Comment by peterhuene** [comment]
I'm having a hard time reproducing this.

@matkoch can you run `tree C:\Users\matthias.koch\.dotnet\tools`?  Are there any directories currently there other than `.store` and `.stage`?

**Comment by matkoch** [comment]
```
C:\USERS\MATTHIAS.KOCH\.DOTNET\TOOLS
└───.store
    └───.stage
```

**Comment by matkoch** [comment]
Not sure if it's relevant, but here is the csproj from which the tool was built:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>nuke</ToolCommandName>

    <!-- Remove when 2.1 was released -->
    <NETCorePlatformsImplicitPackageVersion>2.0.1</NETCorePlatformsImplicitPackageVersion>
  </PropertyGroup>

  <Import Project="..\Package.props" />
  <Import Project="..\..\shared\Configuration.props" />

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nuke.Common\Nuke.Common.csproj" />
  </ItemGroup>

</Project>
```

**Comment by wli3** [comment]
> I'm also curious why the error cannot be a little more specific. If you find a package, and it's not marked as tool, why not say so? If a certain NuGet source couldn't be reached, why not say so? At least as a warning.

This is due to the communication between CLI and nuget is stream. CLI cannot get fine-grained error from nuget. We have a on going discussion for a better protocol.

**Comment by wli3** [comment]
Let me use exact version to repo

**Comment by wli3** [comment]
no repo for me :(

**Comment by wli3** [comment]
@matkoch is your project open source? let me see if install the package can help

**Comment by wli3** [comment]
@matkoch since it is an access deny problem. Maybe remove .stage folder can unblock you for now

**Comment by matkoch** [comment]
Alright, problem solved. I've tested my tool also with preview1 and preview2, and there were still some left overs in `.dotnet/tools` and `.dotnet/toolspkgs`. Deleting them fixed the issue. Thanks!

**Comment by wli3** [comment]
:)
