### ISSUE TITLE
dotnet install for preview/rc versions

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#9247]
I'm not really sure what values I should pass to install for instance `2.1.300-rc1`... How do I find a valid channel/version combination? My guess was `-channel 2.1 -version 2.1.300-rc1` but this fails.

**Comment by livarcocc** [comment]
Use channel 2.1.300 for the CLI.

However, if you are specifying the version, you don't need to pass the channel.

Do note that there is not 2.1.300-rc1 version of the SDK. The rc1 we released is 2.1.300-rc1-008673.

**Comment by matkoch** [comment]
@livarcocc the question is still, where do I get these values from?

**Comment by livarcocc** [comment]
you could use the channel 2.1.300 (it is confusing now because of different versions schemes we had).

Once we have 2.2, it will just be release/2.2 as the channel. For the exact versions of previews/rcs, I am not sure we explicitly publish that anywhere. cc @leecow for that.

I know that if you go to get.dot.net, you can download the rc version from there.

**Comment by matkoch** [comment]
I really need something lightweight like the dotnet-install script. Also, I can't install dotnet sdks on a build server (especially not preview/rc versions). So for people working on "bleeding edge" stuff (like global tools in my case), it's really necessary to be able to download those via dotnet-install. I would really appreciate if you could publish such a list. Otherwise I would need to come back from time to time here :)

**Comment by livarcocc** [comment]
There is a json file that @leecow can point to that would solve this.

Or, in this case, you can use the release/2.1.3xx to be on the latest from the release/2.1.3xx branch. These channels usually match the branches from where the builds come from.

**Comment by leecow** [comment]
https://github.com/dotnet/core/blob/master/release-notes/releases.json
