### ISSUE TITLE
Standard output redirection hides current line

### ISSUE THREAD

**Issue by bricelam** [dotnet/cli#925]
The way stdout (and stderr) is redirected from chained commands prevents the last line from being show until after an end-of-line character. This causes weird interactions.

```C#
Console.WriteLine();
Console.Write("Press any key to continue . . . ");
Console.ReadKey(intercept: true);
```

With a tool containing the above code, invoking it (e.g. via `dotnet mytool`) will...

1. Print a blank line
2. Wait for a keypress
3. Print `Press any key to continue . . . `

The expected behavior would be...

1. Print a blank line
3. Print `Press any key to continue . . . `
2. Wait for a keypress

**Comment by bricelam** [comment]
This could also be related to the color getting out of sync from time to time...

**Comment by brthor** [comment]
@bricelam 
I'm not able to repro this with the code as provided, but I do see the behavior when  doing this:

```
            Console.WriteLine("hello world");
            Console.Write("Press any key to continue . . . ");
            Console.ReadKey(intercept: true);
            
            Console.Write("I am writing a bunch of things");
            Console.WriteLine("more things");
            Console.Write("even more things.");
            throw new Exception("woot");
```

**Comment by brthor** [comment]
Digging into this further, I'm able to get interesting behavior with the following program.

```
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static int Main(string[] args)
        {
            for (int i=0;i<300;++i)
            {
                Console.Write(i);
                Console.Write(',');
            }

            Console.ReadLine();
            return 1;
        }
    }
}
```

Output will hang at 283, until the readline resolves.
This seems be a problem with the method we use to read the streams as well as the line buffering logic.

**Comment by brthor** [comment]
#1240 fixes this with the caveat that

```
Console.WriteLine();
Console.Write("Press any key to continue . . . ");
Console.ReadKey(intercept: true);
```

Will still exhibit the same behavior, but 
```
Console.Write("Press any key to continue . . . ");
Console.WriteLine();
Console.ReadKey(intercept: true);
```
Will not, whereas it would have previously.

**Comment by bricelam** [comment]
I'm personally fine with the limitation. We just need to be careful that no sub-command prompts for input in this way. For example:

    Username: _

**Comment by brthor** [comment]
I will add an entry to the developer guide with my PR.

I found it very difficult to prevent async streams from the child process interleaving character by character without buffering by line. So that's why we are creating the contract that child commands should use WriteLine in all cases where it expects immediate output through the driver.
