### ISSUE TITLE
Ansi Color On Linux

### ISSUE THREAD

**Issue by abk-x** [dotnet/cli#9250]
Looking for some guidance on how to debug this issue. How is dotnet cli determining if Ansi support is available? (Edit: I have seen https://github.com/dotnet/cli/issues/1977, but this was a very long time ago and I believe that this was resolved)

## Steps to reproduce
1. `dotnet new console`
2. `dotnet add package Microsoft.DotNet.Cli.Utils --version 2.0.0` (this is what dotnet build/run uses)
3. Following code:

```
using System;
using Microsoft.DotNet.Cli.Utils;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            var console = AnsiConsole.GetOutput();
            console.WriteLine("\x1b[31mRedText");

            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine("RedText2");
        }
    }
}
```
4. `dotnet run`

## Expected  behavior
Both RedText and RedText2 should appear red.

## Actual behavior
Both text appear white.
Additionally:

`$ script -q -c "dotnet run" out.txt && cat -A out.txt` produces:
```
Script started on 2018-05-10 13:53:40+1000$
^[[?1h^[=^[[?1h^[=^[[?1h^[=^[[39;49mRedText^M$
^[[39;49mRedText2^M$
$
Script done on 2018-05-10 13:53:42+1000$
```

Which doesn't appear to contain the correct ANSI escape chars for the correct colors (red is 31, 39 is default console color) , furthermore, dotnet build does not seem to output colors, unless I specify `/clp:ForceConsoleColor` (which is only possible for dotnet build, not dotnet run). I have also tried setting DOTNET_CLI_CONTEXT_ANSI_PASS_THRU=1 in the environment, but this does not change the result.

## Environment data

$TERM is xterm-256color
$SHELL is bash

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
I am not 100% sure I understand the question, sorry. In any case, You can look at the Write method to see how we honor the colors: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Cli.Utils/AnsiConsole.cs#L100.

Also, I would not recommend using this library for this sort of thing. It was originally publish as a way to share APIs helpful in build project tools, which have since lost their utility with the move from project.json to msbuild.

We have also stopped publishing updates to this library and the last one we pushed was 2.0.0.

As for build and run, the output there is controlled directly by MSBuild.

**Comment by abk-x** [comment]
Right, so lets remove that library from the discussion. The following:

```
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("RedText2");
```

Combined with `dotnet run`, does not produce colors at all, I am convinced it must be something to do with my environment, as I have other systems where this produces color, I am trying to work out what the cause could be :(

**Comment by rainersigwald** [comment]
This issue was moved to dotnet/corefx#29648
