### ISSUE TITLE
The "https://dot.net/v1/dotnet-install.sh" script doesn't work on Fedora or OpenSuse

### ISSUE THREAD

**Issue by mikem8361** [dotnet/cli#9255]
Download the above script and run it on Fedora or OpenSuse to install a version of .NET Core. It fails with "find" or "tput" not found. It seems that not all of the Linux distros have these common utilities.

**Comment by livarcocc** [comment]
@johnbeisner can you take a look and comment?

**Comment by johnbeisner** [comment]
@mikem8361 
The version @ https://raw.githubusercontent.com/dotnet/cli/release/2.1.4xx/scripts/obtain/dotnet-install.sh is the most current & has the 'tput' issue addressed. We will publish this version to 'https://dot.net/v1/dotnet-install.sh' after a 'bake-in' period.

**Comment by omajid** [comment]
Is installing find (`dnf install findutils`) not an option?

**Comment by mikem8361** [comment]
Yes, that works. I was testing this on the MS internal docker files we use for building/testing. I’ll have to add that to the docker file build for Fedora and create some new images.

**Comment by mikem8361** [comment]
When will this new script get pushed to https://dot.net/v1/dotnet-install.sh<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdot.net%2Fv1%2Fdotnet-install.sh&data=02%7C01%7Cmikem%40microsoft.com%7C6e46eb520e5e4b7a1d9a08d5c028474b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636626201640354689&sdata=pJjgJszZq6M0F21AWsa8vpxC67V%2Br26Lk0cto%2BXv74w%3D&reserved=0>? It looks like alpine also doesn’t have “tput” and I can’t find any package that does.

**Comment by johnbeisner** [comment]
@mikem8361 
The 'tput' issue is addressed - line 25 - 'https://dot.net/v1/dotnet-install.sh':
`if [ -t 1 ] && command -v tput > /dev/null; then`
