### ISSUE TITLE
dotnet-install.ps1 should work on linux with Powershell core

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [dotnet/cli#9257]
## Steps to reproduce

- Call `dotnet-install.ps1` from linux with Powershell Core installed

## Expected  behavior

- dotnet SDK gets installed

## Actual behavior

- fails with the following message: 

<pre>
Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
At /home/.../dotnet-install.ps1:159 char:19
+ ...   default { throw "Architecture not supported. If you think this is a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Architecture no...tnet/cli/issues:String) [], RuntimeException
+ FullyQualifiedErrorId : Architecture not supported. If you think this is a bug, please report it at https://github.com/dotnet/cli/issues
</pre>

## Possible cause

At line 155 there is a `switch` on `$Architecture.ToLower()`.  When not passing a value it defaults to `"<auto>"` which makes a recursive call to `Get-CLIArchitecture-From-Architecture` this time with the value returned from the function `Get-Machine-Architecture`.

This function calls: `$ENV:PROCESSOR_ARCHITECTURE` which returns an empty string in Powershell Core, so the next time it goes through the `switch` it goes to the `default` clause causing the `throw`

## Environment data
`dotnet --info` output:

<pre>
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
</pre>

**Comment by livarcocc** [comment]
Dup of https://github.com/dotnet/cli/issues/8278.
