### ISSUE TITLE
.NET core sdk 2.0.0 zip archive is not downloadable

### ISSUE THREAD

**Issue by rasik210** [dotnet/cli#9268]
I want to install .NET core SDK 2.0.0 using zip archive on Ubuntu 18.04:
## Steps to reproduce

1. Go to [this](https://www.microsoft.com/net/download/dotnet-core/sdk-2.0.0) link to download the SDK.
2. Go to Linux > File downloads section.
3. click the link "x64 binaries" 

It takes you to "Thanks for downloading" page to download the .gz zip archive. 

## Expected  behavior

Zip archive should get downloaded.

## Actual behavior

Page loads with file not found error. Below URL is seen in the address bar of the browser:

https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-linux-x64.tar.gz

Screeshot is as below:

![image](https://user-images.githubusercontent.com/6450001/39953097-a3df84c4-55c1-11e8-966a-ebc3be843af3.png)

## Environment data

- I'm using Mozilla Firefox browser for the download.

**Comment by livarcocc** [comment]
@leecow @rowanmiller can one of you double check the page/link above?

**Comment by leecow** [comment]
Will update the page - URL should be https://download.microsoft.com/download/1/B/4/1B4DE605-8378-47A5-B01B-2C79D6C55519/dotnet-sdk-2.0.0-linux-x64.tar.gz

**Comment by rowanmiller** [comment]
Created PR to fix https://github.com/dotnet/core/pull/1559

**Comment by rowanmiller** [comment]
Change is live and I've tested the downloads.

@rasik210 many thanks for reporting the issue!
