### ISSUE TITLE
Global tool not found on path after install

### ISSUE THREAD

**Issue by phil-harmoniq** [dotnet/cli#9273]
## Steps to reproduce

My repo: https://github.com/phil-harmoniq/vInject

I'm trying to use a global tool in my CI builds, but it seems that global tools do not get properly added to `$PATH`. Installing global tools locally on my Mac does work however.

This CI build passes if I use the full path to the tool: https://travis-ci.org/phil-harmoniq/vInject/builds/378115714

This CI build fails when trying to call the tool from `$PATH`: https://travis-ci.org/phil-harmoniq/vInject/builds/378116656

## Expected  behavior

The tool is installed and can be called directly from `$PATH`

## Actual behavior

`git-status: command not found`

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-rc1-008673/

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment]
Hi @phil-harmoniq.  Thanks for reporting this to us.  There was an issue in the installer that prevented `PATH` from being updated to include the tools directory.  This was first reported to us with #9208.  This should be fixed for the macOS and Linux installers for RTM.

A possible workaround would be to configure Travis to add `/home/travis/.dotnet/tools` to PATH.  Once RTM ships you should be able to remove the workaround.
