### ISSUE TITLE
dotnet sdk support on RHEL 6.x

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#9282]
@AmeetShinde commented on [Tue May 15 2018](https://github.com/dotnet/coreclr/issues/17999)

It seems that dotnet core runtime is supported on RHEL 6.x with version 2.0.3 (with preview marker) but not the dotnet core SDK. We can certainly build the binaries for RHEL 6.x from other platforms but we also have requirement to run the test suite with dotnet test command on RHEL 6.x platform. For this, we need dotnet driver to be invoked on this platform. So how can we make dotnet tooling work on RHEL 6.x. If not, what is the workaround to run the tests on this platform.

---

@jkotas commented on [Tue May 15 2018](https://github.com/dotnet/coreclr/issues/17999#issuecomment-389192961)

Related https://github.com/dotnet/core/issues/1260

cc @Petermarcu 

---

@Petermarcu commented on [Tue May 15 2018](https://github.com/dotnet/coreclr/issues/17999#issuecomment-389199275)

@livarcocc

**Comment by livarcocc** [comment]
RHEL6 is currently supported by 2.1.300 SDK which has RC1 build out. We currently don't have any plans to add support to RHEL6 back to our 2.0 based SDK (2.1.200 and lower).

**Comment by AmeetShinde** [comment]
We installed 2.1.300 RC1 build from below location on RHEL 6.7, but still getting GLIBC errors
https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1

dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by dotnet)
dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by dotnet)
dotnet: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by dotnet)
dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by dotnet)
dotnet: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by dotnet)

**Comment by livarcocc** [comment]
I believe these are native requirements by the runtime. cc @leecow @steveharter

**Comment by AmeetShinde** [comment]
can you guys please help answer what all dependencies needs to be resolved and from where we can get it (or do we need to build it ourselves)?

**Comment by steveharter** [comment]
Assuming 2.0.3 runtime and 2.1.300 RC1 SDK: 

Can you do a simple `dotnet` command on RHEL6? If so, does `dotnet --info` work? (wondering if this is a host issue)

**Comment by AmeetShinde** [comment]
the errors mentioned earlier (related to GLIBCXX not found) precludes running any dotnet commands (like dotnet --info) and seen even after invoking simple dotnet command (without any arguments to it).

Can you please help on how to confirm the runtime version included with the sdk?

**Comment by AmeetShinde** [comment]
can we get some update on this?

**Comment by janvorli** [comment]
It seems the SDK you are trying to use is not for RHEL 6. Please note that the portable Linux version is not intended to be used on RHEL 6 as it is too old to be compatible with it. We have a special RHEL 6 version.

Looking at the site with SDK downloads mentioned above, the RHEL 6 version is missing there. 
@steveharter / @livarcocc can we fix that?

**Comment by leecow** [comment]
I don't believe the runtime included with the 2.1.300 SDK will work on RHEL6 and I think and SDK + Runtime install will need to be hacked together. The RHEL6 runtime can be found [here](https://download.microsoft.com/download/D/0/B/D0B7F62D-9C5D-4CF3-AB6C-88F56B4FC1A9/dotnet-runtime-2.1.0-rc1-rhel.6-x64.tar.gz). 

I would try unpacking this runtime, then copy the sdk/ directory over and give it a whirl.

**Comment by janvorli** [comment]
@leecow why do you think so? I've enabled RHEL 6 builds of CLI more than 6 months ago and the latest RHEL 6 sdk package from https://github.com/dotnet/cli main page works just fine (tried just now to make sure). I just needed to add a NuGet.config like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>

```

**Comment by livarcocc** [comment]
Yeah, it seems like we just need to update the download page with new links @leecow

**Comment by leecow** [comment]
Added to the [RC1 download page](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-rc1-download.md)

**Comment by livarcocc** [comment]
Closing this issue then.
