### ISSUE TITLE
dotnet-install.ps1 fails to download aspnetcore runtime with default channel

### ISSUE THREAD

**Issue by tonycoelho** [dotnet/cli#9314]
## Steps to reproduce
Run the dotnet-install.ps1 posh script for aspnetcore with default Channel and Version params
`dotnet-install.ps1 -Architecture "x64" -Runtime aspnetcore -NoPath -Verbose`

Also tried specifying Channel as "2.0" and "2.1", which did not work as well.
`dotnet-install.ps1 -Channel "2.0" -Architecture "x64" -Runtime aspnetcore -NoPath -Verbose `
`dotnet-install.ps1 -Channel "2.1" -Architecture "x64" -Runtime aspnetcore -NoPath -Verbose `

Are the Channels documented somewhere? Without knowing the structure of the dotnetcli.blob.core.windows.net Storage Account, it is impossible to know what values are valid for this parameter.

## Expected  behavior
The ASP.NET Core runtime is installed in the default directory. For example, %LocalAppData%\Microsoft\dotnet

## Actual behavior
Script throws the following errors:

`Exception calling "Invoke" with "0" argument(s): "Failed to download https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/LTS/latest.version.  StatusCode: 404, ReasonPhrase: 'The specified blob does not exist.', Version: 1.1, Content: 
System.Net.Http.StreamContent, Headers:
{
  x-ms-request-id: 42fa8ab8-701e-010a-346b-eef717000000
  x-ms-version: 2009-09-19
  Date: Fri, 18 May 2018 05:47:04 GMT
  Server: Windows-Azure-Blob/1.0
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 215
  Content-Type: application/xml
}"
At D:\Users\gzadmin\Desktop\dotnet-install.ps1:129 char:20`

`Exception calling "Invoke" with "0" argument(s): "Failed to download https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/2.0/latest.version.  StatusCode: 404, ReasonPhrase: 'The specified blob does not exist.', Version: 1.1, Content: 
System.Net.Http.StreamContent, Headers:
{
  x-ms-request-id: 42f9d99e-701e-010a-376b-eef717000000
  x-ms-version: 2009-09-19
  Date: Fri, 18 May 2018 05:45:36 GMT
  Server: Windows-Azure-Blob/1.0
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 215
  Content-Type: application/xml
}"
At D:\Users\gzadmin\Desktop\dotnet-install.ps1:129 char:20`

`Exception calling "Invoke" with "0" argument(s): "Failed to download https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/2.1/latest.version.  StatusCode: 404, ReasonPhrase: 'The specified blob does not exist.', Version: 1.1, Content: 
System.Net.Http.StreamContent, Headers:
{
  x-ms-request-id: 42fa4298-701e-010a-7c6b-eef717000000
  x-ms-version: 2009-09-19
  Date: Fri, 18 May 2018 05:46:27 GMT
  Server: Windows-Azure-Blob/1.0
  Server: Microsoft-HTTPAPI/2.0
  Content-Length: 215
  Content-Type: application/xml
}"
At D:\Users\gzadmin\Desktop\dotnet-install.ps1:129 char:20`

**Comment by tonycoelho** [comment]
After further evaluation, it looks like the param `-Runtime aspnetcore` is only supported for version 2.1 and later. Since 2.1 is not released yet, that would explain why the default channel and version options don't work yet. Is this assumption correct? Also, it would be nice to know if the options for the -Version param are documented somewhere?

**Comment by johnbeisner** [comment]
@tonycoelho 
From: https://dot.net/v1/dotnet-install.ps1
.PARAMETER Channel
    Default: LTS
    Download from the Channel specified. Possible values:
    - Current - most current release
    - LTS - most current supported release
    - 2-part version in a format A.B - represents a specific release
          examples: 2.0; 1.0
    - Branch name
          examples: release/2.0.0; Master
.PARAMETER Version
    Default: latest
    Represents a build version on specific channel. Possible values:
    - latest - most latest build on specific channel
    - coherent - most latest coherent build on specific channel
          coherent applies only to SDK downloads
    - 3-part version in a format A.B.C - represents specific version of build
          examples: 2.0.0-preview2-006120; 1.1.0

**Comment by johnbeisner** [comment]
@natemcmaster 
Could you provide @tonycoelho with an appropriate branch channel or a specific version of an aspnetcore runtime that he could use.

**Comment by natemcmaster** [comment]
Channels are documented here:

https://github.com/aspnet/universe#aspnet-core-shared-framework

At the moment, there are only two. `release/2.1` and `master`.

**Comment by tonycoelho** [comment]
Thanks @natemcmaster, that helps. For others that come across this thread, below is the command to use for the release/2.1 ASP.NET Core channel:

dotnet-install.ps1 -Channel "release/2.1" -Runtime aspnetcore -Verbose

**Comment by natemcmaster** [comment]
Heads up `release/2.1` may give you 2.1.x nightly builds of the ASP.NET Core. This is a "bleeding" edge channel. I recommend using `-Version 2.1.0` instead of `-Channel release/2.1` if you want stable versions.

**Comment by tonycoelho** [comment]
@natemcmaster When using `-Version 2.1.0`, what channel should I use? Using the default throws the exception:

`Cannot download: https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.1.0/aspnetcore-runtime-2.1.0-win-x64.zip 
Could not download ASP.NET Core Runtime version 2.1.0
At E:\Scripts\DotNetCore\dotnet-install.ps1:560 char:3
+         throw "Could not download $assetName version $SpecificVersion ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not downl...e version 2.1.0:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not download ASP.NET Core Runtime version 2.1.0`

**Comment by natemcmaster** [comment]
`-Channel` has no effect when `-Version` is specified. `-Channel` is used as a way to fetch a value for `-Version`.

I'm not seeing issues with the endpoint you specified. Which region are you in? It's possibly an issue with the CDN. 

```
$ curl -I https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/2.1.0/aspnetcore-runtime-2.1.0-win-x64.zip
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: application/octet-stream
Date: Wed, 30 May 2018 20:59:00 GMT
Etag: 0x8D5C1A8E06E8A23
Last-Modified: Thu, 24 May 2018 19:02:20 GMT
Server: ECAcc (sec/977E)
X-Cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 0d09c250-c01e-0071-306d-f7daf2000000
x-ms-version: 2009-09-19
Content-Length: 61233536
```

**Comment by tonycoelho** [comment]
@natemcmaster Running the script on a Cloud Service instance in East US generates that error. Downloading from my local machine works, so yes it does appear to be an issue with the CDN...

**Comment by natemcmaster** [comment]
I'll use my internal email powers to see if we can get someone to look at this. I don't have access to this CDN, so I can't say when this will be fixed.

**Comment by natemcmaster** [comment]
@johnbeisner Re-opening so we can track investigating CDN issues in East US.

**Comment by natemcmaster** [comment]
@tonycoelho as a workaround, you can try pulling from this endpoint instead: https://download.microsoft.com/download/9/1/7/917308D9-6C92-4DA5-B4B1-B4A19451E2D2/aspnetcore-runtime-2.1.0-win-x64.zip

**Comment by splatteredbits** [comment]
Please fix this. The dotnet-install.ps1 script should be able to download old versions of ASP.NET. We have deployment automation that downloads and installs the version of .NET Core at deployment/install time. Right now, we can't do that. I'd prefer not to reverse-engineer all the ZIP file download URLs.

**Comment by natemcmaster** [comment]
@splatteredbits what issues are you seeing? So far, "2.1.0" is the only stable version supported by dotnet-install.ps1.

By the way @tonycoelho, does downloading in East US work for you now?

**Comment by splatteredbits** [comment]
@natemcmaster The script fails to download any 2.0.* version, even though they are available on the [.NET downloads page](https://www.microsoft.com/net/download/all).

```
foreach( $version in @( '2.0.3','2.0.5','2.0.6','2.0.7','2.0.8') )
{
    $installDir = Join-Path -Path $env:TEMP -ChildPath ('aspnetcore-{0}' -f $version)
    try
    {
        .\dotnet-install.ps1 -Version $version -Runtime 'aspnetcore' -InstallDir $installDir -NoPath -ErrorAction Continue
        Write-Host ('Successfully downloaded ASP.NET Core {0}.' -f $version) -ForegroundColor Green
    }
    catch
    {
        Write-Error -ErrorRecord $_
    }
}
```

I would expect `dotnet-install.ps1` to download any/all versions that can be downloaded from the downloads page. It looks like there are no 1.* versions of ASP.NET Core available.

**Comment by natemcmaster** [comment]
ASP.NET Core 2.0.* and 1.* are not supported by dotnet-install.ps1. This capability is something we added for ASP.NET Core 2.1 and up. If you want the script to support older version, please open a separate issue to request that.

I'm going to close this as I believe the original issue was resolved and I'm not aware of any more CDN issues.

**Comment by splatteredbits** [comment]
@natemcmaster Thanks. I entered https://github.com/dotnet/cli/issues/9438 to get this functionality added to `dotnet-install.ps1`. Hopefully its as "easy" as uploading the ZIP files to same location as the other downloads.

**Comment by tonycoelho** [comment]
@natemcmaster Yes, the feeds work from EAST US now. Thanks!

**Comment by tonycoelho** [comment]
Hey @natemcmaster, now the 2.1 is RTM, shouldn't the following command work?

`dotnet-install -Channel 2.1 -Architecture "x64" -Runtime aspnetcore -NoPath -Verbose`

It throws the error: **Failed to download https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/2.1/latest.version.  StatusCode: 404, ReasonPhrase: 'The specified blob does not exist.'**

**Comment by natemcmaster** [comment]
We haven't implemented stable channels yet for dotnet-install and the aspnetcre runtime. I've opened https://github.com/aspnet/Universe/issues/1283 to follow up on this.
