### ISSUE TITLE
No Dotnet CLI release with SDK 2.1.300-RC1

### ISSUE THREAD

**Issue by tylerphelan** [dotnet/cli#9326]
Will a release of the dotnet CLI repo with SDK 2.1.300-RC1 and runtime 2.1.0-RC1 be released? They appear to be released on microsoft.com but not on github:
- https://www.microsoft.com/net/download/dotnet-core/runtime-2.1.0-rc1
- https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1

We are trying to compile the SDK from source and can't find the source for version 2.1.300-RC1.

Thanks!

**Comment by peterhuene** [comment]
Hi @tylerphelan.  Thanks for the reminder to publish the tag and release notes.  I'll see what I can do to move this along.

**Comment by peterhuene** [comment]
I've created a tag for `v2.1.300-rc1-008673`.  I'll ping the release notes owner to see if we can publish them.

**Comment by peterhuene** [comment]
@tylerphelan There should now be a release and tag for RC1.  Thank you!
