### ISSUE TITLE
Update project.json schema on schemastore

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#933]
The JSON editor in VS uses http://schemastore.org/ to locate JSON schemas in order to show IntelliSense. There is already a schema up there for project.json, but we have made changes since it was last updated and neglected to update the schema. All we need to do to update it is send a PR to https://github.com/SchemaStore/schemastore (specifically for schemas/json/project.json and the associated release-tagged versions).

A likely incomplete list of changes to update with:

* `testRunner` property added for `dotnet-test`
* `preserveCompilationContext` in `compilationOptions`
* `imports` property in `framework.[fxname]` (from NuGet v3)
* `tools` property
* Probably more!

/cc @Petermarcu @piotrpMSFT @davidfowl @muratg

**Comment by piotrpMSFT** [comment]
Chatted with @davidfowl about this last night. We need to review recent additions to pj schema and make sure we are happy with the shape before doing this. TestRunner should probably be converted to a testOptions mode with a runner property, for example.

**Comment by anurse** [comment]
Agreed. I would rather we just kept the schema up-to-date with the current status regardless of future throughts though. It's a minor thing and it ensure that wherever we land, we are always in sync.

**Comment by anurse** [comment]
Ideally we'd have the schema in our own repo and synced with schemastore somehow (so our PRs can include changes), but that's a more complicated process than we have time to set up :)

**Comment by muratg** [comment]
Agreed with @anurse.  We should keep a copy in this repo, and keep it up to date as project.json changes.  And we can update the copy in schemastore as we do releases.

**Comment by muratg** [comment]
@piotrpMSFT Is someone keeping the schema up to date?

**Comment by mlorbetske** [comment]
Looping myself in. Any updates on getting an RC2 project.json schema on schemastore?

**Comment by piotrpMSFT** [comment]
@muratg the project.json schema has been evolved by your team. I expected the schema updates to be handled the same way.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
