### ISSUE TITLE
Msi 995 installs broken CLI

### ISSUE THREAD

**Issue by dburriss** [dotnet/cli#934]
Myself and a colleague both downloaded the msi 995 and installed it on Windows 8.1 (each of us downloaded seperately a few hours apart).
We both received error when running **dotnet restore** on a **dotnet new** Hello World app:
*Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Program.cs'*
We tried uninstalling and reinstalling.
Using an msi (973) I had downloaded a few days earlier we both reinstalled and **dotnet restore** ran successfully.

**Comment by blackdwarf** [comment]
@dburriss can you try to install the CLI in a path that does not contain spaces and retry?

**Comment by dburriss** [comment]
@blackdwarf  ok will try c:\dotnet

**Comment by dburriss** [comment]
Uninstalled 973 and installed 992 to c:\dotnet
Can run **dotnet restore**

**Comment by blackdwarf** [comment]
OK, we have #525 and others to track this, so I will close this issue as a duplicate. @brthor has a fix incoming for this issue.
