### ISSUE TITLE
TargetFramworks build question

### ISSUE THREAD

**Issue by mcm-ham** [dotnet/cli#9340]
## Steps to reproduce
```
dotnet new web -o ProjectA
dotnet new classlib -o ProjectB
dotnet new sln
dotnet sln add .\ProjectA\ProjectA.csproj
dotnet sln add .\ProjectB\ProjectB.csproj
dotnet add .\ProjectA\ProjectA.csproj reference .\ProjectB\ProjectB.csproj
# replace metapackage with individual because metapackage doesn't support net461
dotnet remove .\ProjectA\ProjectA.csproj package Microsoft.AspNetCore.App
dotnet add .\ProjectA\ProjectA.csproj package Microsoft.AspNetCore
dotnet add .\ProjectA\ProjectA.csproj package Microsoft.AspNetCore.Diagnostics
dotnet add .\ProjectA\ProjectA.csproj package Microsoft.AspNetCore.Hosting
# modify .\ProjectA\ProjectA.csproj targetframeworks to netcoreapp2.0;net461
```

## Expected  behavior
Expected all these to work
- dotnet build projects.sln -f net461
- dotnet build projecta.csproj -f net461
- dotnet build projects.sln /p:TargetFramework=net461

I'm expecting if the library targets netstandard2.0 that it should work for net461 without me needing to add it explicitly.

## Actual behavior
- dotnet build projects.sln -f net461
_Error_
```
C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(197,5): error : Assets file 'C:\ProjectB\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.6.1'. Ensure that restore has run and that you have included 'net461' in the TargetFrameworks for your project. [C:\ProjectB\ProjectB.csproj]
```
- dotnet build projecta.csproj -f net461
_Works_
- dotnet build projects.sln /p:TargetFramework=net461
_Works_

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  1.1.9 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by dasMulli** [comment]
The issue here is that the `-f` parameter defines a global `TargetFramework` property that will override all projects.
While `dotnet build -f foo` will filter it correctly so that restore doesn't see it but the build does (so you restore correctly when multi-targeting), it is currently broken for `/p:TargetFramework=foo`.

Best to only use `-f` or similar when building a multi-targeting project of which the target framework is part of the plural `TargetFrameworks` property.

Another option would be to define a custom property to use for overriding the target framework when needed.

e.g. you could modify your ProjectA.csproj to define:

```xml
<PropertyGroup>
  <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>
  <TargetFramework Condition="'$(AppTargetFramework)' != ''">$(AppTargetFramework)</TargetFramework>
</PropertyGroup>
```

Then build using
```
$ dotnet build -p:AppTargetFramework=net461
```

**Comment by livarcocc** [comment]
@dasMulli is correct. While for the -f parameter we have the option to intercept it and do the right thing, we decided that when using the /p values we should let it pass through as is. As a escape hatch that users can use.

Also, given that there is an issue tracking excluding this for /restore on msbuild already open, I am going to close this issue.
