### ISSUE TITLE
dotnet cli doesn't rebuild the project when we use different msbuild arguments

### ISSUE THREAD

**Issue by JustArchi** [dotnet/cli#9349]
Let's assume that you have a C# project similar to below:

```csharp
#if CUSTOM_PUBLISH
public static readonly CustomPublish = true;
#else
public static readonly CustomPublish = false;
#endif
```

With proper `DefineConstants` in csproj:

```xml
  <PropertyGroup Condition="'$(CUSTOM_PUBLISH)' != ''">
    <DefineConstants>$(DefineConstants);CUSTOM_PUBLISH</DefineConstants>
  </PropertyGroup>
```

If you execute following two commands:

```
dotnet build
dotnet publish -o out /p:CUSTOM_PUBLISH=true
```

Then execute `out\Program.dll`, `CustomPublish` will still be `false` as `dotnet publish` did not trigger project rebuild done previously by `dotnet build` which didn't use the switch. This will not happen if you execute `dotnet publish` command on the clean tree, without executing `dotnet build` firstly.

My first question, is this intended? If yes, what is the recommended way to go about this? `dotnet clean`, or maybe something else? I can understand the rationale behind that, but I'm not entirely sure if `dotnet` should act in this way.

Thank you in advance.

**Comment by livarcocc** [comment]
I don't think this is an issue in the SDK. I tried on a non-sdk style project and I got the same results. This may be MSBuild's incremental check.

@rainersigwald are you aware of any such issues on MSBuild's side?

**Comment by rainersigwald** [comment]
This is a general problem with the MSBuild incrementality model, but in this case we have already developed a mechanism to solve it. I'll move this to MSBuild and elaborate there.

**Comment by rainersigwald** [comment]
This issue was moved to Microsoft/msbuild#3350
