### ISSUE TITLE
Can I use source control path as reposityPath? If yes any example

### ISSUE THREAD

**Issue by chilakamarthi** [dotnet/cli#9356]
I would like to use Source control path as repositoryPath instead of local path. Can I do that? Any sample code?

**Comment by livarcocc** [comment]
In which context are you asking this question? Sorry, I am not sure what these refer to.

**Comment by chilakamarthi** [comment]
I added NuGet.Config to my solution and set it like below:
<configuration>
  <config>
    <add key="repositoryPath" value="../../../../Test/Test/Packages" />
  </config>
</configuration>

Here repository path is relative path to solution file location. can I make it source control path instead of local path is the Q.
