### ISSUE TITLE
Running 'dotnet new' with  2.1.400-preview-008942 on Ubuntu 16.04 Arm64 causes illegal instruction

### ISSUE THREAD

**Issue by bbusacker** [dotnet/cli#9361]
## Steps to Reproduce
run dotnet new 

## Expected Behaviour

Creates console project

## Actual Behaviour

illegal instruction error message printed to the screen

## Environment data
ufs@dmx-yic1:~/vsts-agent-users-tihuang-linuxarm64/_dotnetsdk/2.1$ ./dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400-preview-008942
 Commit:    de407deff0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-arm64
 Base Path:   /home/ufs/vsts-agent-users-tihuang-linuxarm64/_dotnetsdk/2.1/sdk/2.1.400-preview-008942/

Host (useful for support):
  Version: 2.1.0-rtm-26515-03
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.400-preview-008942 [/home/ufs/vsts-agent-users-tihuang-linuxarm64/_dotnetsdk/2.1/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.0-rtm-26515-03 [/home/ufs/vsts-agent-users-tihuang-linuxarm64/_dotnetsdk/2.1/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment]
I think this may be a duplicate of https://github.com/aspnet/Universe/issues/1117. @natemcmaster, is that correct?

**Comment by livarcocc** [comment]
@bbusacker what message is being printed to the screen?

**Comment by bbusacker** [comment]
@livarcocc I believe my issue may be that some system calls needed by dotnet cli are not compiled into the kernel I am using.  I will close this for now and reopen if I still have issues after getting the kernel supporting all the system calls.
