### ISSUE TITLE
Publish doesn't honor working dir

### ISSUE THREAD

**Issue by ericstj** [dotnet/cli#9367]
@safern and I noticed this when hacking around.  It looks like publish always assumes project relative rather than working directory relative.

## Steps to reproduce
1. mkdir test
2. cd test
3. dotnet new console
4. cd ..
5. dotnet publish test\test.csproj -o pub\

## Expected  behavior
test is published to pub directory

## Actual behavior
test is published to test\pub directory

## Environment data
`dotnet --info` output:
NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008673
 Commit:    f5e3ddbe73

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008673\

Host (useful for support):
  Version: 2.1.0-rc1
  Commit:  eb9bc92051

.NET Core SDKs installed:
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
This is a dup of https://github.com/dotnet/cli/issues/4765.
