### ISSUE TITLE
`dotnet test` exit code should return number of failures

### ISSUE THREAD

**Issue by sidshetye** [dotnet/cli#9368]
`dotnet test` is documented [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21) but there isn't any documentation on the exit code.

With test runners like nunit3 (e.g. `nunit3-console.exe`) the exit code is the number of failed tests, which is indeed very handy. `dotnet test` simply return 0 if all pass and 1 if any failures.

**Comment by livarcocc** [comment]
This issue was moved to Microsoft/vstest#1624
