### ISSUE TITLE
Install on Linode Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by ChicagoDave** [dotnet/cli#9370]
## Steps to reproduce
Normal install steps

## Expected  behavior
Should install?

## Actual behavior
Fails

## Environment data
dave@planetfall:~$ uname -a
Linux planetfall 4.15.13-x86_64-linode106 #1 SMP Tue Mar 27 14:42:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
dave@planetfall:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
dave@planetfall:~$ sudo apt-get install dotnet-sdk-2.1.4
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1.4
E: Couldn't find any package by glob 'dotnet-sdk-2.1.4'
E: Couldn't find any package by regex 'dotnet-sdk-2.1.4'
dave@planetfall:~$ sudo apt search dotnet-sdk-2.1.4
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1.4/xenial,xenial 2.1.4-1 amd64
  Microsoft .NET Core SDK - 2.1.4

**Comment by livarcocc** [comment]
Can you share what error you see? Also, what commands exactly are you using to install the SDK?

cc @leecow

**Comment by leecow** [comment]
Does your .list file look like `deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main`?

Just gave it a whirl to make sure nothing happened and the feed seems good. 

```
leecow@lbc-1604:~$ sudo apt-get install dotnet-sdk-2.1.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  dotnet-runtime-deps-2.1 linux-headers-4.13.0-39
  linux-headers-4.13.0-39-generic linux-image-4.13.0-39-generic
  linux-image-extra-4.13.0-39-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  aspnetcore-store-2.0.0 aspnetcore-store-2.0.3 aspnetcore-store-2.0.5
  dotnet-host dotnet-hostfxr-2.0.5 dotnet-runtime-2.0.5
The following NEW packages will be installed:
  aspnetcore-store-2.0.0 aspnetcore-store-2.0.3 aspnetcore-store-2.0.5
  dotnet-host dotnet-hostfxr-2.0.5 dotnet-runtime-2.0.5 dotnet-sdk-2.1.4
0 upgraded, 7 newly installed, 0 to remove and 56 not upgraded.
Need to get 93.6 MB/119 MB of archives.
After this operation, 347 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

**Comment by SilentCC** [comment]
I have the same problem . And I add 
 
  `deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main` 

to /etc/apt/sources.list .Then it work! Thank you! @leecow

**Comment by ChicagoDave** [comment]
I'm using the standard Ubuntu 16.04 install from:
https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current

The package is definitely downloaded:
$ sudo apt search dotnet-sdk-2.1.4
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1.4/xenial,xenial 2.1.4-1 amd64
  Microsoft .NET Core SDK - 2.1.4

But when I try to install:
$ sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'

And yes, the sources.list is correct:
$ cat /etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main

**Comment by livarcocc** [comment]
@ChicagoDave 2.1.4 is not the same as 2.1. 2.1.4 is actually a much older version. The equivalent of 2.1 is actually 2.1.300.

**Comment by ChicagoDave** [comment]
Whoa!

So this still doesn't explain why the install doesn't work. I did everything based on the installation instructions.

wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.1

I still get the same error.

This is a basic search for 2.1 and as you can see, 2.1.3 is downloaded too:

$ sudo apt search dotnet-sdk-2.1
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1/xenial 2.1.300-1 amd64
  Microsoft .NET Core SDK 2.1.300

dotnet-sdk-2.1.100/xenial 2.1.100-1 amd64
  Microsoft .NET Core SDK - 2.1.100

dotnet-sdk-2.1.101/xenial 2.1.101-1 amd64
  Microsoft .NET Core SDK - 2.1.101

dotnet-sdk-2.1.102/xenial 2.1.102-1 amd64
  Microsoft .NET Core SDK - 2.1.102

dotnet-sdk-2.1.103/xenial 2.1.103-1 amd64
  Microsoft .NET Core SDK - 2.1.103

dotnet-sdk-2.1.104/xenial 2.1.104-1 amd64
  Microsoft .NET Core SDK - 2.1.104

dotnet-sdk-2.1.105/xenial 2.1.105-1 amd64
  Microsoft .NET Core SDK - 2.1.105

dotnet-sdk-2.1.2/xenial 2.1.2-1 amd64
  Microsoft .NET Core SDK - 2.1.2

dotnet-sdk-2.1.200/xenial 2.1.200-1 amd64
  Microsoft .NET Core SDK - 2.1.200

dotnet-sdk-2.1.3/xenial 2.1.3-1 amd64
  Microsoft .NET Core SDK - 2.1.3

dotnet-sdk-2.1.300-preview1-008174/xenial 2.1.300-preview1-008174-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.300-preview2-008533/xenial 2.1.300-preview2-008533-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.300-rc1-008673/xenial 2.1.300-rc1-008673-1 amd64
  Microsoft .NET Core SDK 2.1.300 - rc1

dotnet-sdk-2.1.4/xenial 2.1.4-1 amd64
  Microsoft .NET Core SDK - 2.1.4

**Comment by livarcocc** [comment]
Can you paste the error you get when you run `sudo apt-get install dotnet-sdk-2.1`?

**Comment by ChicagoDave** [comment]
It's in my second post, but also below (can't find the downloaded package, even though it's there:

Unless this is a platform mismatch?

$ sudo apt-get install dotnet-sdk-2.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.1
E: Couldn't find any package by glob 'dotnet-sdk-2.1'
E: Couldn't find any package by regex 'dotnet-sdk-2.1'

**Comment by livarcocc** [comment]
@leecow can you think of anything else for us to do here? By the way, I could not repro this either. Not sure why apt-get would fail to find a package that it is actually listing above.

**Comment by ChicagoDave** [comment]
Same error.

**Comment by leecow** [comment]
Thanks @ChicagoDave - this one has me scratching my head. I've started a thread with the repo owners to see if there's something on their side that might be going on.

**Comment by ChicagoDave** [comment]
Cool. I'm not crazy. Good to know.

**Comment by leecow** [comment]
Unfortunately no great ideas have been discovered. It almost seems like something is preventing the apt cache from being updated though I have no idea how that would happen. As an alternative, you can use the tarball to install - links at https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md

**Comment by ChicagoDave** [comment]
Got it. This server was a linode 32-bit VM. They upgraded all of their servers to 64-bit at some point, but it's still stuck with 32-bit libraries. I did some research and this is fugly. I'm going to create a fresh 18.04 VM and move plover over, which solve the problem. Let's leave this open until I get that done (few days) and I'll verify that was the problem.

**Comment by ChicagoDave** [comment]
Installs fine on a new 18.04 </obvious>. Sorry for the trouble.

**Comment by livarcocc** [comment]
@ChicagoDave thanks for insisting on the issue and getting to the bottom of it. I am sure this issue will be helpful to other people as well. This was awesome.

**Comment by MissyElliotSmith** [comment]
@leecow Thanks, your steps did the trick. But I had to add '-get' after 'sudo apt install'.

**Comment by leecow** [comment]
Thanks @MissyElliotSmith - yeah, `apt install` isn't quite universal ... fixed!

**Comment by jmeliodas96** [comment]
at end or start of list ?
