### ISSUE TITLE
dotnet --info show incorrect versions of SDK installed on Windows

### ISSUE THREAD

**Issue by EdiWang** [dotnet/cli#9372]
## Steps to reproduce
run "dotnet --info"

## Expected  behavior
List all the SDKs installed on Windows

## Actual behavior
List the SDKs that has been uninstalled, but have an empty folder with SDK version numbers still in "C:\Program Files\dotnet\sdk"

![image](https://user-images.githubusercontent.com/3304703/40758582-9caa72e6-64c0-11e8-94e2-2a44d76cbfc9.png)

And you can actually try create a new folder and name it: 2.0.233333, it will show up:

![image](https://user-images.githubusercontent.com/3304703/40758587-a2ffe496-64c0-11e8-99b0-fad627ed51fb.png)

**Comment by yanxiaodi** [comment]
That's interesting...haha. 😄

**Comment by livarcocc** [comment]
This issue was moved to dotnet/core-setup#4179
