### ISSUE TITLE
dotnet core RHEL-x64 publish output doesn't work with RHEL 6.x versions

### ISSUE THREAD

**Issue by AmeetShinde** [dotnet/cli#9375]
When we build and publish self contained application with runtime identifier rhel-x64 and tried to use it on RHEL 6.x platform, we get following error

"dlopen failed to open the libcoreclr.so with error /lib64/libc.so.6: version `GLIBC_2.14' not found"

If we publish with rhel.6-x64 identifier and use these published binaries, then it works correctly on RHEL 6.x platform.

We are using dotnet core SDK 2.1.3 RC1 build with runtime version 2.0.4 (which supports RHEL 6.x platform as per below link)
https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md

We expect binaries published with portable runtime identifier to work for all versions of that specific platform.

**Comment by livarcocc** [comment]
@tmds is this a dup of https://github.com/dotnet/cli/issues/9359?

**Comment by omajid** [comment]
As I understand it, the cli artifacts for the `rhel-x64` RID are built on RHEL 7 (or similar) and require features in newer glibc. The cli artifacts for the `rhel.6-x64` RID are built on RHEL 6 (or similar) and do not require the newer features from glibc. Something built on a newer glibc is just not going to work on an older glibc.

The flips side would be to build everything on RHEL 6 and use that as the base. Perhaps CoreCLR experts can explain why they didn't do it that way - I am sure there are issues.

**Comment by livarcocc** [comment]
Closing this as this does not sound like an issue.

Tagging @janvorli in case he can add more details on why it was implemented like this.

**Comment by janvorli** [comment]
@AmeetShinde the RHEL 6 is too old for our portable build. It is missing some features that we can take advantage of if we build on newer distros and that we would loose if we build our portable build on RHEL 6. E.g. monotonic clock, functional robust mutexes, getting affinity of the current thread, accessing extended SIMD registers in processor context, etc. We can live without these, but it has performance consequences.
We originally weren't planning to support it at all, but based on the feedback from our users, we have decided to create a non-portable special version for RHEL 6 as a best effort thing.

**Comment by AmeetShinde** [comment]
@janvorli  Thanks for the detailed explanation. I am assuming that publish output bianries of our application with RID rhel.6-x64 wouldn't work with RHEL 7.x, can you please confirm the same?
