### ISSUE TITLE
Why internal-reportinstallsuccess has to be executed as an elevated user in postinstall

### ISSUE THREAD

**Issue by slavanap** [dotnet/cli#9377]
Commands in postinstall scripts: [one](https://github.com/dotnet/cli/blob/6a64e17857971af2019bb455de676b2dc987ada9/packaging/deb/postinst#L22), [two](https://github.com/dotnet/cli/blob/8189d72e062b138eeae25050735c892613b39b81/packaging/osx/clisdk/scripts/postinstall#L12)
 -- are executed with root privileges on target system. I can't figure out a reason for such approach to execute that after successful installation (and as a root!) and not after successful usage.

**Comment by livarcocc** [comment]
internal-reportinstallsuccess will trigger the cache expansion as part of the native installer. The cache is expanded next to the SDK itself and as such will be in a user protected location. Because of that, this command needs to run with elevated user.
