### ISSUE TITLE
Concurrent invocations of Build / Compile race on common intermediary output

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#938]
When running tests in parallel, I had failures due to races on the common csc response file in the intermediary output (csc failed with an unhandled exception). This was because dotnet-compile-csc creates a global response file that is not project specific, so during concurrent builds it happens for one project to end up using the response file of another project.

To fix the issue I had to manually specify a project specific intermediary output directory when invoking build: https://github.com/cdmihai/cli/commit/45c305e5a2f566611d18480b3356c53f895e8417

Forcing clients to manually disambiguate the intermediary output seems wrong.

**Comment by blackdwarf** [comment]
@cdmihai what is the status of this?

**Comment by cdmihai** [comment]
I think it got mitigated with the change of having each project have its own intermediate path: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L33

compile-csc still uses a unique looking filename for the response file: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile-csc/Program.cs#L111

I'll close the issue
