### ISSUE TITLE
dotnet new template source

### ISSUE THREAD

**Issue by axdiamond** [dotnet/cli#9383]
This likely isn't the correct place for this question, but I can't find what I'm looking for.

I can't find the source for the templates preinstalled with dotnet, specifically I am looking for the webapi template. I have found a number of resources talking about how to create new templates, and directories of non-preinstalled  templates, but none that show where the preinstalled templates are.

Where can I find them? And what should I have looked for to find them, because it seems non-obvious.

**Comment by livarcocc** [comment]
@natemcmaster for a pointer to where the asp.net templates are produced.

**Comment by natemcmaster** [comment]
Templates are scattered between two repos. ASP.NET Core templates are in https://github.com/aspnet/Templating. Most other templates come from https://github.com/dotnet/Templating.
