### ISSUE TITLE
Tag v2.1.300 of the CLI doesn't include the correct versions of Microsoft.AspNetCore.All Microsoft.AspNetCore.App and Microsoft.NETCore.App

### ISSUE THREAD

**Issue by vellozzi** [dotnet/cli#9388]
## Steps to reproduce
git clone https://github.com/dotnet/cli
cd cli
git checkout v2.1.300
./build.sh --linux-portable --configuration Release

## Expected  behavior
After the build is complete the directory structure should look like:
bin/2/linux-x64/dotnet/shared/Microsoft.AspNetCore.All/2.1.0
bin/2/linux-x64/dotnet/shared/Microsoft.AspNetCore.App/2.1.0
bin/2/linux-x64/dotnet/shared/Microsoft.NETCore.App/2.1.0

## Actual behavior
After the build is complete the directory structure is actually:
bin/2/linux-x64/dotnet/shared/Microsoft.AspNetCore.All/2.1.0-rtm-30752
bin/2/linux-x64/dotnet/shared/Microsoft.AspNetCore.App/2.1.0-rtm-30752
bin/2/linux-x64/dotnet/shared/Microsoft.NETCore.App/2.1.0-rtm-26515-03

**Comment by livarcocc** [comment]
This happens because of our build system where dependency flows does not count as commits in it. This commit matches exactly the ProdCon build that generated our 2.1.300 build. We updated the dependency version afterwards (just changing the numbers in the repo) but the 2.1.300 build with this SHA was already referencing the 2.1.0 bits for runtime.

@leecow what do you prefer here? To match the exact commit in the ProdCon bits or to match the spirit of the bits in the ProdCon build.

**Comment by leecow** [comment]
If what @vellozzi is trying should work, then we need to publish the tag that makes that happen.

**Comment by vellozzi** [comment]
I need to be able to run the CLI build.  Then I need to be able to use it to build and run a projects that reference Microsoft.NETCore.App 2.1.0 and Microsoft.AspNetCore.App 2.1.0.

Is there a way I can patch the repo at the v2.1.300 tag to achieve that in my build?  

What do you mean by "just changing the numbers in the repo"?  Is that something I could do that would that help me out?

**Comment by vellozzi** [comment]
@livarcocc , If I cherry pick https://github.com/dotnet/cli/commit/aeae506fa8d3571d8b5f75f81389003e0fb0273e will that solve my problem?

**Comment by livarcocc** [comment]
@vellozzi Yes.

**Comment by livarcocc** [comment]
Closing as this seems to be solved and I would rather keep the tag on the exact commit that was shipped for 2.1.300.

**Comment by vellozzi** [comment]
It hasn't been solved really.  We worked around it for this version.  But we really need to know that when we check out a tag we're building what the tag says it is.

**Comment by vellozzi** [comment]
Can you explain what ProdCon means and how that works?
Could you adpot a tagging convention like vX.Y.Z-prodcon for your internal use, then commit the dependency changes to the public repo and tag that vX.Y.Z ?  That would solve both our problems and make the public repo more friendly to use.
