### ISSUE TITLE
SDK installation on Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by lecoque** [dotnet/cli#9390]
I somehow couldn't install dotnet sdk on Ubuntu 18.04 LTS

I followed exactly this: https://www.microsoft.com/net/download/linux-package-manager/rhel/sdk-current

Can you confirm that it works?

**Comment by livarcocc** [comment]
What error are you running into? Yes, this is supported, however, without knowing more about your issue, it will be hard to help you work through it.

cc @leecow

**Comment by leecow** [comment]
Install definitely works on 18.04 so let us know more details.

**Comment by lecoque** [comment]
It works. It didn't work on Live USB when I tried it. It works with a normal installation. Sorry for false alarm :)
