### ISSUE TITLE
No executable found matching command "dotnet-script"

### ISSUE THREAD

**Issue by ahdung** [dotnet/cli#9396]
## Steps to reproduce
1. dotnet tool install -g dotnet-script
2. dotnet script init

## Expected  behavior
use [dotnet-script](https://github.com/filipw/dotnet-script) init a csx project

## Actual behavior
the command `dotnet script init` report error:
`No executable found matching command "dotnet-script"`

## Environment data
    .NET Core SDK（反映任何 global.json）:
     Version:   2.1.300
     Commit:    adab45bf0c
    
    运行时环境:
     OS Name:     Windows
     OS Version:  6.1.7601
     OS Platform: Windows
     RID:         win7-x64   【Actually My OS is WINDOWS SERVER 2008 R2 x64】
     Base Path:   C:\Program Files\dotnet\sdk\2.1.300\
    
    Host (useful for support):
      Version: 2.1.0
      Commit:  caa7b7e2ba
    
    .NET Core SDKs installed:
      1.0.0 [C:\Program Files\dotnet\sdk]
      1.0.3 [C:\Program Files\dotnet\sdk]
      1.0.4 [C:\Program Files\dotnet\sdk]
      1.1.0 [C:\Program Files\dotnet\sdk]
      2.0.0 [C:\Program Files\dotnet\sdk]
      2.0.2 [C:\Program Files\dotnet\sdk]
      2.0.3 [C:\Program Files\dotnet\sdk]
      2.1.2 [C:\Program Files\dotnet\sdk]
      2.1.4 [C:\Program Files\dotnet\sdk]
      2.1.100 [C:\Program Files\dotnet\sdk]
      2.1.101 [C:\Program Files\dotnet\sdk]
      2.1.102 [C:\Program Files\dotnet\sdk]
      2.1.103 [C:\Program Files\dotnet\sdk]
      2.1.104 [C:\Program Files\dotnet\sdk]
      2.1.200 [C:\Program Files\dotnet\sdk]
      2.1.201 [C:\Program Files\dotnet\sdk]
      2.1.300 [C:\Program Files\dotnet\sdk]
    
    .NET Core runtimes installed:
      Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    
    To install additional .NET Core runtimes or SDKs:
      https://aka.ms/dotnet-download

## Other info
`dotnet tool list -g` can see the `dotnet-script` additional tool

**Comment by ahdung** [comment]
And I tried other tool like `dotnet-serve`, get same issue, so I think this isn't tool's wrong.

**Comment by natemcmaster** [comment]
Can you run the following two commands in PowerShell and share console output?

```PS1
echo $env:PATH
& $env:USERPROFILE\.dotnet\tools\dotnet-script.exe
```

**Comment by ahdung** [comment]
@natemcmaster sure
`>echo $env:PATH`
```   
%SystemRoot%\system32\WindowsPowerShell\v1.0\;C:\ProgramData\IMP2POcx\;C:\Progr
am Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\P
rogram Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;D:\
Embarcadero\Studio\14.0\bin;C:\Users\Administrator\Documents\Embarcadero\Studio
\14.0\Bpl;D:\Embarcadero\Studio\14.0\bin64;C:\Users\Administrator\Documents\Emb
arcadero\Studio\14.0\Bpl\Win64;d:\Embarcadero\RAD Studio\9.0\bin;C:\Users\Admin
istrator\Documents\RAD Studio\9.0\Bpl;C:\ProgramData\IMP2POcx;C:\Program Files
(x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Windows\system32;C:\Wi
ndows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\T
ool\Universal Extractor SYS2;D:\Tool\Universal Extractor SYS2\bin;d:\ToolMedia\
QT Lite\QTSystem;D:\Microsoft SQL Server SYS2\ShareFuncx86\100\Tools\Binn\;D:\M
icrosoft SQL Server SYS2\ShareFunc\100\Tools\Binn\;D:\Microsoft SQL Server SYS2
\ShareFunc\100\DTS\Binn\;D:\Microsoft SQL Server SYS2\ShareFuncx86\100\Tools\Bi
nn\VSShell\Common7\IDE\;D:\Microsoft SQL Server SYS2\ShareFuncx86\100\DTS\Binn\
;C:\Users\Administrator\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Progra
m Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Windows Kits\8
.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScrip
t\1.0\;C:\Users\Public\Documents\Embarcadero\Studio\14.0\Bpl;C:\Users\Public\Do
cuments\RAD Studio\9.0\Bpl;d:\ToolDev\Microsoft VS Code\bin;D:\Microsoft SQL Se
rver 2014\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Windows\System32\WindowsP
owerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130
\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Pro
gram Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Micr
osoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Windows\System32\WindowsPo
werShell\v1.0\;d:\tooldev\Git\cmd
```
`>echo $env:USERPROFILE\.dotnet\tools\dotnet-script.exe`
`C:\Users\Administrator\.dotnet\tools\dotnet-script.exe`

looks like the `$env:PATH` no contains `c:\users\administrator\.dotnet\tools`, BUT, the `sysdm.cpl > Advanced > Envionment variables > administrator User variables > Path` contains, and `System variables > Path` no contains. 
And, if I use mstsc.exe to connect this PC with same account(administrator) from other PC, in the remote session can run `dotnet script` command.
of course, I tried restart PC.

I guess the Envionment variables is reason, but I have no idea.

**Comment by ahdung** [comment]
I think the reason is EnvVars too much, so I deleted some items, it's work now, Thank you.
