### ISSUE TITLE
Add tests for implicit aspnet package version

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#9403]
Follow-up to https://github.com/dotnet/cli/pull/9374

For Microsoft.NETCore.App, there is a [hard-coded list](https://github.com/dotnet/cli/blob/80d542b8f4eff847a0f72dc8f2c2a29851272778/build/MSBuildExtensions.targets#L174-L176) of latest patch versions, and then [tests](https://github.com/dotnet/cli/blob/master/test/EndToEnd/GivenSelfContainedAppsRollForward.cs) to verify this. We should add similar infrastructure for Microsoft.AspNetCore.App/All.

cc @dsplaisted @JunTaoLuo

**Comment by livarcocc** [comment]
Is this something that you or @JunTaoLuo can make a PR for?

**Comment by natemcmaster** [comment]
Yes. We won't get to this before the cutoff for 2.1.301 though

**Comment by natemcmaster** [comment]
It looks like [these tests](https://github.com/dotnet/cli/blob/release/2.1.3xx/test/EndToEnd/GivenAspNetAppsResolveImplicitVersions.cs) were already in place, but were just broken. @johnbeisner fixed them in https://github.com/dotnet/cli/pull/9592.

Closing as I'm not planning to take any further action here. The test coverage is sufficient for now.
