### ISSUE TITLE
dotnet tool install detect not existing tool installed

### ISSUE THREAD

**Issue by tebeco** [dotnet/cli#9408]
## Steps to reproduce
```
>  dotnet tool install fake-cli ^
     --tool-path ./foobar ^
     --version 5.0.0-rc*
> cd foobar
> rm -rf *
> ls -alh 
(empty)
> cd ..
> dotnet tool list --tool-path ./foobar
Package Id      Version              Commands
---------------------------------------------
fake-cli        5.0.0-rc015.196      fake
```

## Expected  behavior
it should have printed an empty list
```
>dotnet tool list --tool-path .
Package Id      Version      Commands
-------------------------------------
>
```

## Environment data
```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17677
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by livarcocc** [comment]
@peterhuene this seems like a question for `dotnet tool list`

**Comment by peterhuene** [comment]
Hi @tebeco.  I'm unable to reproduce this on Windows and macOS.

```
> dotnet tool list --tool-path ./foobar
Tool path './foobar' does not exist.
Usage: dotnet tool list [options]

Options:
  -g, --global   List user wide tools.
  --tool-path    Location where the tools are installed.
  -h, --help     Show help information.
```

Plus, following your repro steps, I would expect an error at `cd foobar` since the directory should no longer exist.  Is there something I'm missing from the steps?  Thanks!

**Comment by tebeco** [comment]
will double check the repro step to be more consistent
i might have forgot something in the repro

**Comment by peterhuene** [comment]
Running `rm -rf *` won't delete the hidden `.store` directory in `./foobar`.  The `.store` directory contains the tool packages and it is the directory that `dotnet tool list` uses to print out the installed tools.  However, the shim (the executable `dotnet tool install` generates to run your tool) is deleted by `rm -rf`, but `dotnet tool list` doesn't currently take that into account when printing out whats "installed".

If you delete the `.store` directory, you'll get the desired behavior:

```
$ dotnet tool list --tool-path ./foobar
Package Id      Version      Commands
-------------------------------------
```

**Comment by tebeco** [comment]
You are right about `.store` but i cannot even it,
I'm using Win10, with GIT SCM installing `rm`, `ls` and put their containing folder in the `%PATH%` so i can use few of them in any terminal

also `ls -alh` list nothing so there should not be any hidden artifact (with `-a`)

**Comment by peterhuene** [comment]
`.store` is a directory created by `dotnet` and is not related to macOS' `.DS_Store` file.

When a tool is installed with `dotnet tool install`, it downloads and installs the NuGet package to `<tool-path>\.store`.  It then creates what we call a "shim" (a native executable that loads your tool) at `<tool-path>`.

By default, `<tool-path>` is `~\.dotnet\tools`, where `~` denotes your user directory.

Thus, to uninstall a tool, use `dotnet tool uninstall`.  To delete **all** tools, you can just delete the `<tool-path>` folder.

**Comment by tebeco** [comment]
yes it makes sense, now i understand what’s happening ;)
thx a lot for all that clarification
