### ISSUE TITLE
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime

### ISSUE THREAD

**Issue by haf** [dotnet/cli#9411]
This is a real issue and there's no known workaround. The question I'm asking is this; what versions do you support compiling for mono and .net framework on? Why? Because e.g. EventStore is not yet a .net core-only server and I use it. Beyond that; there are many frameworks out there that haven't been updated. Or: why? Because I produce a lot of open source for people for free and if I can't compile that OSS, you're breaking your community. Take e.g. DotNetZip with millions of downloads; you're making it infeasible for me to work for you for free when you don't answer properly to bugs like this one.

Furthermore, it seems you're not testing your tooling properly for F#; instead leaving it up to the users to discover; when reported in this issue tracker you close it with "workaround available" without specifying what workaround.

You have no way to communicate with those not in your own organisation; what happens over github-issues is not enough when each message takes 5 days to be replied to with a "just go away" response. With that reply, it's not enough even if messages would take 1 hour to be replied to.

You keep pushing out patch releases with breaking changes and there's no good way to ask anyone at MSFT what is going on; asking will at best get your issue closed, at worst get you banned from the repo. Your .Net Core release notes don't mention the critical issues like these or the F# SDK, so from them I don't know whether to upgrade or if it's another red herring; more performance fixes when your compilation system is broken.

So I'm filing this issue again; hoping to get a good answer. I'm on macOS and not Windows and I'm never going back to a telemetry- and ad-riddled OS. I'm trying to compile a C# library and I have a repro with your so-called workaround in place, so now please take it seriously.

## Steps to reproduce on macOS

```
git clone https://github.com/masroore/CurlSharp.git
cd CurlSharp
export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api
dotnet restore
dotnet build
... =>
NativeMethods.cs(49,36): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [/Users/h/dev/logibit/CurlSharp/CurlSharp/CurlSharp.csproj]
```

## Expected  behavior

.Net Core was supposed to be cross platform.

## Actual behavior

It's crashing when trying to compile very simple things.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

```

```
» mono --version
Mono JIT compiler version 5.12.0.226 (2018-02/9824e260f56 Mon Apr 30 18:45:52 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
------------------------------------------------------------
```

### Workaround

Don't use .net core to build (not a workaround, this is the bug itself)

**Comment by dasMulli** [comment]
Is this different from https://github.com/dotnet/cli/issues/9337?
cc @livarcocc

**Comment by haf** [comment]
Yes, it's not closed.

**Comment by dasMulli** [comment]
The tracking issue would still https://github.com/dotnet/sdk/issues/335
Is there any aspect not covered by this or your previous issue? it would become hard for the team to monitor duplicates just for the sake of having open duplicate issues

**Comment by livarcocc** [comment]
This will continue to be tracked by dotnet/sdk#335.
