### ISSUE TITLE
dotnet-install.ps1 doesn't report SDK version 2.1.300 as latest version

### ISSUE THREAD

**Issue by sandermvanvliet** [dotnet/cli#9412]
## Steps to reproduce
* .NET SDK version 2.1.101 is installed
* Download `dotnet-install.ps1`
* Run `.\dotnet-install.ps1 -Channel 2.0 -Version latest`

## Expected  behavior
.NET SDK version 2.1.300 is installed.

## Actual behavior
Script output is `dotnet-install: .NET SDK version 2.1.101 is already installed`

## Analysis
When I check the URL the script uses (`https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version`) to get the latest version, the data I receive is indicating `2.1.101` is the latest version. Therefore the script works correctly but the behaviour is unexpected.

**Comment by livarcocc** [comment]
2.1.300 is no the lastest version for channel 2.0. Channel 2.0 corresponds to the latest SDK with the 2.0 runtime.

@leecow @johnbeisner I don't see a 2.1 channel in the blob storage. Should we have one?

**Comment by leecow** [comment]
Added 2.1 blob storage entries. @johnbeisner - any corresponding changes needed in dotnet-install.*?

**Comment by johnbeisner** [comment]
@leecow is this correct?
2.0 = 2.1.200
2.1 = 2.1.300

.\dotnet-install.ps1 -Channel 2.0 -Version latest
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/**2.1.200**/dotnet-sdk-2.1.200-win-x64.zip

.\dotnet-install.ps1 -Channel 2.1 -Version latest
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/**2.1.300**/dotnet-sdk-2.1.300-win-x64.zip
