### ISSUE TITLE
dotnet global tool for composed projects

### ISSUE THREAD

**Issue by leecow** [dotnet/cli#9428]
@Evangelink commented on [Mon May 28 2018](https://github.com/dotnet/core/issues/1604)

Hi there,

I am one of the developer of the [Sonar Scanner for MSBuild](https://github.com/SonarSource/sonar-scanner-msbuild) and some of our users have expressed an interest in having our standalone tool as a [global tool](https://github.com/SonarSource/sonar-scanner-msbuild/issues/417).

I have looked at the following links:

- https://github.com/dotnet/core/blob/master/samples/dotnetsay/README.md

- https://natemcmaster.com/blog/2018/05/12/dotnet-global-tools/

- https://github.com/natemcmaster/dotnet-tools

And I haven't been able to understand if I can (and how) create a global tool out of my setup. I have a [PackageNetCore.csproj](https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/src/Packaging/PackageNetCore/PackageNetCore.csproj) project (and a [target](https://github.com/SonarSource/sonar-scanner-msbuild/tree/master/src/Packaging)) which is only responsible of packing the right files together and creating a zip out of that (I need to download some other non dotnet tool that I embed).

As far as I have understood the global tool project needs to be an exe project targeting netcoreapp2.1 (2.0 is not working) and it needs to already contain all the required dependencies. Could you confirm?

Side question, is it possible to somehow create a nuspec which would result in the same tool?

Cheers,
Amaury

**Comment by livarcocc** [comment]
@peterhuene @wli3 @KathleenDollard

**Comment by wli3** [comment]
Hi @Evangelink 

> it needs to already contain all the required dependencies. Could you confirm?

Yes, the result package should have all the dependency dlls. The package could be able to be copy-pasted to another machine with the same dotnet core runtime.

First I want to make sure, could your app can be run as a portable (dotnet core framework dependent) app?

If so, I have 2 options that I can think of.
1. Utilize dotnet pack -- Make a similar project like _PackageNetCore.csproj_. Mark all files in _ScannerFiles_ to copy local. And set appropriate entry point and set _PackAsTool_. The result of dotnet pack should be a nupkg with all _ScannerFiles_

2. Write nuspc to create a Global tool package. Here is the “spec” of a global tool package format:
Tool nupkg format

- Tool Nupkg does not have anything other folder under root like /lib, /content, it only has /tools folder.

- Under /tools folder, the subfolders are structured with pattern target framework short version/RID. For example, tool assets targeting .NET core framework V2.1 and portable should be under tools/netcoreapp2.1/any. Let's call assets under every tools/target framework short version/RID combination per TFM-RID assets.

- There is a DotnetToolSettings.xml for every per TFM-RID assets.

- The package type is DotnetTool

-Per TFM-RID assets should have all the dependency the tool required to run. TFM-RID assets should be able to run using xcopy to another machine with correct runtime version and RID environment. For portable app, there is runtimeconfig.json for every per TFM-RID assets.
Remark:
•	Only portable app is supported.
•	Only one tool per tool package.
DotnetToolSettings.xml:
Example:
``` xml
<?xml version="1.0" encoding="utf-8" ?>
<DotNetCliTool>  
<Commands>
    <Command Name="%sayhello%" EntryPoint="%console.dll%" Runner="dotnet" />
</Commands>
</DotNetCliTool>
```

Currently only configurable part is command name: sayhello and entry point: console.dll. Command Name is what the user will type in their shell to invoke the command. Entry point is the relative path to the entry dll with main.

**Comment by livarcocc** [comment]
I am going to close this issue as I believe @wli3 has answered the questions above and we haven't had new activity here.

**Comment by Evangelink** [comment]
Hi guys,

Sorry I had a few days off end of last week so I didn't had time to test your answers but I will do so today and will post back right after!

Thanks for your time and answers!
