### ISSUE TITLE
Constrain `dotnet test` to run on specific runtime version

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#9429]
How can I use `dotnet test my.csproj` and force the test runner to use a particular .NET Core runtime version?

When I use the `-f .netcoreapp2.0` switch, it builds the right framework version for my test project, but then it runs on a somewhat arbitrary version of the .NET Core 2.x runtime. It could be 2.0.x, or it could be 2.1.x if 2.0.x isn't installed, as I understand it. When I have several 2.0.x versions installed, I can't control which is used. 

In my case, I need to run my tests on these runtimes: 2.1.300, 2.0.7, 1.1.8, 1.0.11.
My test project targets .netcoreapp1.0, .netcoreapp2.0, .netcoreapp2.1.

Also, I notice that the test runner will claim it's running `netcoreapp2.0` even if it's running on the 2.1.300 runtime. There should be a way to log what the actual runtime version is that was used to execute the test.

I tried `dotnet --fx-version 2.0.7 test my.csproj` but it doesn't like mixing runtime switches with sdk commands.

**Comment by livarcocc** [comment]
@steveharter what is the property we can use to prevent the host from rolling forward?

@AArnott you can set the RuntimeFrameworkVersion to specify exactly version of the runtime you want to use and then set the property that I asked Steve about to indicate to the host that you do not want to be rolled forward to the latest patch version.

**Comment by AArnott** [comment]
Thanks, @livarcocc. What is `RuntimeFrameworkVersion`? Is that an environment variable?

**Comment by livarcocc** [comment]
It is an MSBuild property. As such, you could set it as an env variable.

**Comment by steveharter** [comment]
>> @steveharter what is the property we can use to prevent the host from rolling forward?

You can set `%DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX% =0`

There are also runtimeconfig and command line support too: https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/roll-forward-on-no-candidate-fx.md

**Comment by AArnott** [comment]
Thank you, both!

**Comment by livarcocc** [comment]
When I suggested the mechanisms above, they were intended to force you to use a particular runtime (and not be rolled-forward on patch version) but within the TFM boundaries as well.

They were not meant to allow you to cross the major version barrier. What you are trying to do is simply not supported. We don't support rolling forward across major versions. Even for minor version roll forward, it was a feature just recently added for 2.1 and we recommend using it very carefully.

Given that this is not supported, I am going to close this issue again.

**Comment by AArnott** [comment]
How should I test how my .netstandard1.x library performs when in the context of a .netcoreapp2.x app when my library also offers a .netstandard2.x version?
