### ISSUE TITLE
Update dotnet-install.ps1 to download 2.0.* versions of ASP.NET runtime

### ISSUE THREAD

**Issue by splatteredbits** [dotnet/cli#9438]
There are several versions of the ASP.NET 2.0 runtime available on the [.NET downloads page](https://www.microsoft.com/net/download/all). Unfortunately, `dotnet-install.ps1` fails to download any of them. I would expect that `dotnet-install.ps1` can install any version available on the downloads page.

We have a deployment process that downloads and installs the version of .NET Core an apps needs. With the current version of the script, we can only 2.1.* versions and are dev teams aren't ready to start using 2.1

## Steps to reproduce
```
# These are all the 2.0.* versions of ASP.NET available on the downloads page.
foreach( $version in @( '2.0.3','2.0.5','2.0.6','2.0.7','2.0.8') )
{
    $installDir = Join-Path -Path $env:TEMP -ChildPath ('aspnetcore-{0}' -f $version)
    try
    {
        .\dotnet-install.ps1 -Version $version -Runtime 'aspnetcore' -InstallDir $installDir -NoPath -ErrorAction Continue
        Write-Host ('Successfully downloaded ASP.NET Core {0}.' -f $version) -ForegroundColor Green
    }
    catch
    {
        Write-Error -ErrorRecord $_
    }
}
```

## Expected  behavior
I expect that all versions of ASP.NET available on the downloads page would be download-able by `dotnet-install.ps1`.

## Actual behavior
The `dotnet-install.ps1` script throws a terminating exception when attempting to download any `2.0.*` version.

## Environment data
`dotnet --info` output:

n/a

**Comment by natemcmaster** [comment]
To make this work, we would need to 

* restructure the layout of the blob store for all 2.0.x downloads. I'm not opposed to doing this...it would be good to clean this up anyways. 
* update the script to understand the ways in which aspnet changed between 2.0. and 2.1. For aspnetcore `[2.0.0, 2.1.0)`, it should download a runtime store, and for `[2.1.0, )`, it needs to download a shared framework.

cc @leecow @livarcocc for thoughts on how to prioritize this

**Comment by leecow** [comment]
Nate, I presume the restructuring would only be for the aspnetcore storage? Given that we are shifting the runtime acquisition emphasis to the core+asp bundle, this should certainly get on the schedule before too long.

**Comment by natemcmaster** [comment]
Yes. We could retroactively find the 2.0.x bits and put them in to dotnetcli blob storage in a format consumable by the script.

**Comment by livarcocc** [comment]
@leecow I believe the re-structuring here would only impact 2.0 assets (the asp.net runtime store). Why is it needed before too long for the runtime acquisition changes?

**Comment by natemcmaster** [comment]
At this point, we are no longer servicing .NET Core 2.0. I'm closing this as 'wontfix' and recommend updating to .NET Core 2.1 or 2.2 which as a fix for this issue.
