### ISSUE TITLE
dotnet run (2.1.1300) refers to the command "dotnet tool install dotnet-dev-certs -g --version 2.1.0-preview1-final" instead of release version

### ISSUE THREAD

**Issue by kastwey** [dotnet/cli#9448]
## Steps to reproduce
1. Create a project.
2. run dotnet run.

## Expected  behavior
When dotnet run informs us that the development https certificate has been installed, the command to install the tool dotnet-dev-certs  should refers the final version, not preview.

## Actual behavior
The message regarding dotnet-dev-certs installation refers to preview version.

> "The ASP.NET Core HTTPS development certificate has been successfully installed.
> To trust the certificate (Windows and macOS only), first install the dev-certs tool by running "dotnet tool install dotnet-dev-certs -g --version 2.1.0-preview1-final" and then run "dotnet-dev-certs https --trust".
> 
> 

## Environment data
`dotnet --info` output:

SDK de .NET Core (reflejando cualquier global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment]
Hi @kastwey.  This is a result of missing localization for your language, as https://github.com/dotnet/cli/pull/8957 removed the string, but the localized versions didn't make it into the release correctly.

@livarcocc I think we should have the current LOC PR retargeted for 2.1.3xx so that we update loc appropriately for the next service release.  Thoughts?

**Comment by kastwey** [comment]
OK, thanks!

**Comment by livarcocc** [comment]
We can take it to shiproom and see what they say, otherwise, we should fix it in 2.1.4xx.

Also, let's continue the conversation at https://github.com/dotnet/cli/issues/9379.

I will close this one as a dup.
