### ISSUE TITLE
--runtime didn't work, while -r does

### ISSUE THREAD

**Issue by sebastienros** [dotnet/cli#9452]
I managed to do `--self-contained -r win-x64` but `--self-contained --runtime win-x64` fails stating I either need to no use `--self-contained` or specify a runtime id.

Full command:
`dotnet publish -c Release -o c:\temp\publish5 --self-contained --runtime win-x64`

Error message:
```
C:\Users\sebros\AppData\Local\Microsoft\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. 
```

SDK 2.1.300

**Comment by peterhuene** [comment]
Hi @sebastienros.  I'm unable to reproduce this on Windows or macOS with 2.1.300.  The `--runtime` option is being respected properly by the `publish` command.

Could you provide a full repro that demonstrates the problem?  Thanks!

**Comment by sebastienros** [comment]
```
PS C:\temp> cd \temp
PS C:\temp> git clone https://github.com/OrchardCMS/OrchardCore
Cloning into 'OrchardCore'...
remote: Counting objects: 49469, done.
remote: Total 49469 (delta 0), reused 0 (delta 0), pack-reused 49468
Receiving objects: 100% (49469/49469), 33.85 MiB | 27.25 MiB/s, done.
Resolving deltas: 100% (35186/35186), done.
Checking out files: 100% (3144/3144), done.
PS C:\temp> cd .\OrchardCore\
PS C:\temp\OrchardCore> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba
...
PS C:\temp\OrchardCore> cd .\src\OrchardCore.Cms.Web\
dotnet publish -c Release -o c:\temp\publish5 --self-contained --runtime win-x64
...
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. [C:\temp\OrchardCore\src\OrchardCore.Cms.Web\OrchardCore.Cms.Web.csproj]
PS C:\temp\OrchardCore> cd .\src\OrchardCore.Cms.Web\
dotnet publish -c Release -o c:\temp\publish5 --self-contained --runtime "win-x64"
...
C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(116,5): error : It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.  Please either specify a RuntimeIdentifier or set SelfContained to false. 
```

Note that `dotnet publish -c Release -o c:\temp\publish5 --runtime win-x64` without `--self-contained` worked in that case.

I am on Skype for Business if you want to see it for yourself.

**Comment by peterhuene** [comment]
I was able to reproduce it with `OrchardCore.Cms.Web`.  I'll see if I can determine the problem.

**Comment by peterhuene** [comment]
It looks like Razor is building the project again with an empty `RuntimeIdentifier`:

https://github.com/aspnet/MvcPrecompilation/blob/94e0ecca732e3eb9bbe9094d3db6c356e65d2f36/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets#L74

@rynowak thoughts on this?

**Comment by rynowak** [comment]
@sebastienros is this Razor SDK or MvcPrecompilation? Let's sync up tomorrow if it's not clear.

**Comment by sebastienros** [comment]
It looks like it's missing the `$(RuntimeIdentifier)` that it's checking right before the line you pointed to. But I am not an expert, so I'll check with the team tomorrow.

**Comment by livarcocc** [comment]
@rynowak Should we move this issue over to Razor?

**Comment by pranavkm** [comment]
Sure. Could you move it to https://github.com/aspnet/MvcPrecompilation?

**Comment by livarcocc** [comment]
This issue was moved to aspnet/MvcPrecompilation#276
