### ISSUE TITLE
The command 'cmd /S /C dotnet restore -nowarn:msb3202,nu1503' returned a non-zero code: 1

### ISSUE THREAD

**Issue by jesaremi** [dotnet/cli#9454]
Running docker-compose on Windows 10 to build an aspnet core 2.1 app

Here's my DockerFile:

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 11001

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY MyAppPipeline.sln ./
COPY MyAppRestApi/MyAppRestApi.csproj MyAppRestApi/
RUN dotnet restore -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/MyAppRestApi
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MyAppRestApi.dll"]
```

My docker-compose.yaml file:

```
version: '3.4'

services:
  myapprestapi:
    image: myapprestapi
    build:
      context: .
      dockerfile: MyAppRestApi/Dockerfile
```

Execution trace:

> 
> D:\repos\MyApp\Dotnet>docker-compose -f docker-compose.yml build
> Building myapprestapi
> Step 1/17 : FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
>  ---> 8b0c58279084
> Step 2/17 : WORKDIR /app
>  ---> Using cache
>  ---> 7054c8eb06d0
> Step 3/17 : EXPOSE 11001
>  ---> Using cache
>  ---> 88b9acb75524
> 
> Step 4/17 : FROM microsoft/dotnet:2.1-sdk AS build
> 2.1-sdk: Pulling from microsoft/dotnet
> e46172273a4e: Already exists
> 3670e54633da: Already exists
> 6475262e5a38: Pull complete
> fdb91c5a810a: Pull complete
> 799543dd76f3: Pull complete
> 328f4d0fb467: Pull complete
> 00f1d7e3a3cb: Pull complete
> 23bcd24523f5: Pull complete
> Digest: sha256:44459326186d8d8c7e4124e36a09e553e662b6f1d71bbe242daf1bf4720a8b91
> Status: Downloaded newer image for microsoft/dotnet:2.1-sdk
>  ---> db94c80c7c4b
> Step 5/17 : WORKDIR /src
> Removing intermediate container f2a73eed76a8
>  ---> e047725195dd
> Step 6/17 : COPY MyAppPipeline.sln ./
>  ---> 73272b5f010b
> Step 7/17 : COPY MyAppRestApi/MyAppRestApi.csproj MyAppRestApi/
>  ---> 63bd72fbb1dd
> Step 8/17 : RUN dotnet restore -nowarn:msb3202,nu1503
>  ---> Running in d339754a2636
> C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(239,5): error MSB3202: The project file "C:\src\mylib.Tests\mylib.Tests.csproj" was not found. [C:\src\MyAppPipeline.sln]
> C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(239,5): error MSB3202: The project file "C:\SomePipeline\SomePipeline.scopeproj" was not found. [C:\src\MyAppPipeline.sln]
> C:\Program Files\dotnet\sdk\2.1.300\NuGet.targets(239,5): error MSB3202: The project file "C:\src\docker-compose.dcproj" was not found. [C:\src\MyAppPipeline.sln]
> ERROR: Service 'myapprestapi' failed to build: The command 'cmd /S /C dotnet restore -nowarn:msb3202,nu1503' returned a non-zero code: 1

**Comment by livarcocc** [comment]
I am not sure it is possible to suppress MSBuild warnings, which are those that start with MSB.

I will let @rainersigwald confirm before closing the issue.

**Comment by rainersigwald** [comment]
It is possible to suppress warnings with this MSBuild command-line option:

```
  /warnasmessage[:code[;code2]]
                     List of warning codes to treats as low importance
                     messages.  Use a semicolon or a comma to separate
                     multiple warning codes.
                     (Short form: /nowarn[:c;[c2]])

                     Example:
                       /warnasmessage:MSB3026
```

But I don't think that's relevant here; this is an error that arises because you're running restore on a `.sln` file, but haven't made all of its projects available in the container.

I can see two ways to avoid this:

* Copy all projects into your `build` container
* Move `WORKDIR /src/MyAppRestApi` above the `dotnet restore` call.

The latter is trivial, but note that it may result in subtly different behavior from a solution restore: without the context of the solution, it's possible that different versions of packages will be restored.
