### ISSUE TITLE
Build succeeds, test fail due to Nuget cache hit/miss?

### ISSUE THREAD

**Issue by SGStino** [dotnet/cli#9462]
## Steps to reproduce
Having an existing .NET core project:
1. Create a private nuget repository with an assembly in it that isn't in any cache
2. include the nuget repository in nuget.config next to solution
3. use the assembly from the private repository in solution
4. build solution with msbuild /t:restore (putting it in the cache that msbuild uses)
5. remove nuget repository from nuget.config (or create new solution without nuget.config)
6. add unit tests
7. build solution with msbuild
8. run unit tests with msbuild
9. run "dotnet test"
10. run "dotnet restore"

## Expected  behavior
- either second build (in step 7) should fail, or unit test in 8. should run
- step 9 and 10 should also run or fail.

## Actual behavior
- build in step 7 succeeds, unit test in step 8 fails
- step 9 and 10 also fail

### Suspected reason/summary
I suspect msbuild uses a different nuget cache for restoring and building than .NET Core uses for execution.

- msbuild /t:restore succeeds in restoring
- msbuild /t:test fails at runtime with `System.IO.FileNotFoundException: Could not load file or assembly X`
- dotnet restore fails with :  `Unable to find package X with version (>= Y)`
- dotnet test fails with :  `Unable to find package X with version (>= Y)`

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
## Extra remarks:
dotnet core 2.1 sdk was installed, builds began failing completly.
so visual studio 2017 was updated from 15.3.1 to 15.7.3 on build server.

**Comment by livarcocc** [comment]
Can you share the project.assets.json that is generated for the first msbuild /t:Restore command? They should be the same. There are not separate caches for one restore and then the other.

**Comment by livarcocc** [comment]
Closing this issue due to lack and activity and to the fact that we need more info.
