### ISSUE TITLE
[loc][Query][Cli] Localizability of "RemoveProjectPathArgumentDescription"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/cli#9463]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The paths to the projects to from from the solution.

File Name:
LocalizableStrings.xlf

==========================================
Query:
We have found double occurrences of "from" 
Would you clarify the structure of this string? Is it supposed to be "The paths to the projects to remove from the solution."? 

Our translator translated it assuming the first "from" should be replaced with "remove".

**Comment by livarcocc** [comment]
Which branch is this from? Could you add a link to the LocalizableStrings.xlf?

**Comment by PDostalek** [comment]
It´s coming from this path (**https://github.com/dotnet/cli/tree/master/src/dotnet/commands/dotnet-sln/xlf**).

**Comment by livarcocc** [comment]
Then your assumption above is correct. I also have a PR to fix the original english string.

**Comment by PDostalek** [comment]
Thanks for the correction.
