### ISSUE TITLE
Restore of DotNet.exe is not working

### ISSUE THREAD

**Issue by bruceyclee** [dotnet/cli#948]
I downloaded the latest build of CLI at https://dotnetcli.blob.core.windows.net/dotnet/dev/Installers/Latest/dotnet-win-x64.latest.msi which is showed on the homepage of CLI.

Then I input "dotnet new" to create a sample console project. Three files will be generated as shown below,

Directory of C:\temp\WebApplication-dotnet

01/21/2016  11:42 AM    <DIR>          .
01/21/2016  11:42 AM    <DIR>          ..
01/21/2016  11:42 AM               392 NuGet.Config
01/21/2016  11:42 AM               214 Program.cs
01/21/2016  11:42 AM               244 project.json
               3 File(s)            850 bytes

And then I input "dotnet restore", I got a warning popup window about CoreCLR and the following text.

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Program' or one of its dependencies. The system cannot find the file specified.

So, restore is not working.

**Comment by GuardRex** [comment]
Had this this morning. Install dot net cli at the root of your hd to avoid spaces in the path ("Program FIles"). Install at c:\dotnet

**Comment by GuardRex** [comment]
Also get on ci nuget feed and grab -16401 runtime. I'm close to working, but all of this is necessary to reach even my current state of "almost" ,there.

**Comment by GuardRex** [comment]
... and I'm having to allow VS `dnu` restore the packages to `.dnx` packages and manually move them to `.nuget` packages folder until I figure it out. Oh, man.

**Comment by bruceyclee** [comment]
dnu resotres packages to ".dnx" folder and "dotnet restore" restores packages to ".nuget" folder. So in the meantime, copying packages from ".dnx" to ".nuget" looks like a temporary workaround.

**Comment by piotrpMSFT** [comment]
Fixes for most of these issues are incoming today
#525 
#421 
#967  <-- this is further out

**Comment by GuardRex** [comment]
@piotrpMSFT That's wonderful news! :beers: I said (in frustration yesterday) that I was going to wait a few weeks, but I **really** don't want to do that. We've have some huge company happenings here, and I want our apps on `dotnet cli` and Nano Server ASAP.

**Comment by piotrpMSFT** [comment]
We are making some huge changes this week and there has been a lot of turbulence. Thanks for hanging in there with us! After this push we are focusing on stabilization!

**Comment by brthor** [comment]
This should be resolved via #985, please reopen if you are still hitting this issue.

**Comment by Thorium** [comment]
If you delete dotnet.exe how do you get it back?

**Comment by GuardRex** [comment]
@Thorium If you're a 7th level Cleric and have some holy water and diamonds, you can cast a Resurrection spell to bring it back. :smile:

If not, you'll have to get a new [.NET Core SDK Installer](https://github.com/dotnet/cli/tree/rel/1.0.0).

**Comment by Thorium** [comment]
Thanks, for some reason these repairs didn't bring it back, but after installing and uninstalling about 5 times I got it back...

**Comment by GuardRex** [comment]
The installers are better these days. They used to (perhaps in some limited cases still do) leave bits lying around that can break new installs. I usually only keep one installed SDK on my system at a time. I download/install the new SDK, then I immediately go to `Programs & Features` and uninstall the prior SDK. You can also execute a `nuget locals all -clear` to nuke package caches ... also great to recover massive drive space from old cached preview packages. If you still have very old bits lying around, you'll have to manually purge them, as I had to do once here: https://github.com/dotnet/cli/issues/2948
