### ISSUE TITLE
Request: Add a param to emit structured data (for third-party tooling)

### ISSUE THREAD

**Issue by Phrohdoh** [dotnet/cli#9486]
This is a very general, wide-reaching request.

I envision an invocation similar to the following:

```shell
$ dotnet build --message-format json
```

Which, upon error CS0539 (for example), would emit such a structure:

```json
{
    "status": "error",
    "errors": [{
        "code": "CS0539",
        "message": "The type or namespace 'Foo' could not be found",
        "notes": [{
            "message": "Are you missing a using directive or an assembly reference?",
            "span": null,
        }],
        "origin": {
            "file": "rel/path/to/file.cs",
            "span": { // a byte range
                "start": 123,
                "end": 456
            }
        }
    }]
}
```

The resulting structured data could be used by foundation- and community-built tooling for many things (one example is error messages that include source code).

This request is inspired by [`cargo`](https://github.com/rust-lang/cargo) `--message-format` functionality.

I fully realize that this is a *very large* request and the above structure is a minimal, illustrative example.

**Comment by livarcocc** [comment]
I feel like this request is much more appropriate to Roslyn or MSBuild than to the CLI itself. We don't actually build the project and I don't believe we would ever get into the business of parsing build results to transform it.
