### ISSUE TITLE
`dotnet new react ...`  generates a JavaScript React project instead of TypeScript after updating to 2.1.300 (.NET Core 2.1)

### ISSUE THREAD

**Issue by Nufflee** [dotnet/cli#9489]
I'm opening this issue because that command would generate a TypeScript project in SDK version 2.1.200 (.NET Core version 2.0.8). In the changelog it states that you've switched over to create-react-app but it, by default, generates a JavaScript React project. I'm not sure if this change was intended as I couldn't find anything about that in the change log, but if so, you should probably provide an option to switch to TypeScript (you can use [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) to generate a typescript project). 

## Steps to reproduce
Run `dotnet new -o MyProject` and observe that code in ClientApp directory is JavaScript not TypeScript.

## Expected  behavior
Code in ClientApp directory should be TypeScript.

## Actual behavior
Code ub ClientApp directory is JavaScript.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
This issue was moved to aspnet/templating#572
