### ISSUE TITLE
Allow for custom assembly/package name in the CLI, instead of always matching folder name

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#949]
@davidfowl @piotrpMSFT @KrzysztofCwalina @mgravell Today, we are facing issues in Corefxlab and it is actually broken due to the lack of Project to Project dependencies in the CLI with a custom folder structure. This is also blocking corefx to move over to the CLI as seen in https://github.com/dotnet/corefx/issues/4544.

Our current folder structure in corefxlab is as follows:

System.Slices
                Src
                                Project.json
                Test
                                Project.json

This repeats itself through all the other libraries in there and it mimics the structure from CoreFx.  P2P outside of the project.json folder is not possible because all projects are “called”  src from the CLI point of view.

A possible solution would be for the CLI to look inside the project.json for the name property in there and use that as the name of the dependency (as a precedence, if it not is provided, we would fall back to the folder name). One drawback of that would be perf issues, as we would have to open all the different project.json files when scanning for dependencies. If that turns out to be an issue, we could do that only for P2P projects, say, when the type of the dependency is build.

Any concerns with this approach.

**Comment by mgravell** [comment]
If it turns out that this is a perf problem, I wonder if there is some kind of global lock file (like the project lock files for nuget) that could live alongside global.json and track - per path - the resolved project name and the hash/whatever for the corresponding project.json. just update the global lock file when building anything that has changed, or perhaps when running dnu restore.

Just a thought

**Comment by brthor** [comment]
Is this not already possible using the "name" parameter in project.json?

https://github.com/dotnet/cli/blob/master/src/dotnet-restore/project.json
Outputs to dotnet-restore.exe

**Comment by livarcocc** [comment]
@brthor Well, the name in project.json sets the name that the assembly will be created with, but it does not change the way that we find project to project dependencies.

Today, if I have a project.json under a src folder directly with name set to A, if another project B wants to depend on A, B to write src as the dependency. And this leads to even more problems when we have multiple projects under a src folder, like we do in corefx and corefxlab.

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
