### ISSUE TITLE
Suggestion: Implement StyleCop file on CLI repo

### ISSUE THREAD

**Issue by JonKohler** [dotnet/cli#9490]
Recently, upstream Microsoft PowerShell has implemented StyleCop on their primarily C# repo. Given that there is such a tight interaction between PowerShell core and dotnet, I think it would be worthwhile to align the two projects on style guidance.

You can see the two relevant PR's for PowerShell master, here: 
https://github.com/PowerShell/PowerShell/pull/6930
https://github.com/PowerShell/PowerShell/pull/6986

Ultimately resulting in this file, here: 
https://github.com/PowerShell/PowerShell/blob/master/stylecop.json

We're aligning our latest C# PowerShell core project with this same guidance, and have seen great benefit.

This is one of those "one file" type of easy implementations; however, style guidance is always a hot topic. As such, check out the PR's I mentioned, where the PowerShell community went back and forth on exactly how to tune this. As a result, I think (honestly) we could just pull that single file from the PowerShell stream, and implement it here with ease.

This will ultimately result in similarly stylized code, which should help the overall community working in both code bases.

cc @TravisEz13 and @iSazonov and @SteveL-MSFT for context from the PoSh side.

Note: I've filed a matching suggestion for the SDK project as well. It would be great if we could align here: https://github.com/dotnet/sdk/issues/2335

**Comment by sharwell** [comment]
I would suggest not adding a StyleCop.Settings file, and instead add only a stylecop.json file for use with StyleCop Analyzers. The two products do not have exact feature parity and are not meant to be used together.

**Comment by JonKohler** [comment]
@sharwell and of course you'd be the guy to know :) Thanks. Sure, I dont have a problem with that, my apologies, I wasn't aware of the difference between the two.

Do you have any suggestions/hints on moving from the old to new in a sane way?

**Comment by JonKohler** [comment]
@sharwell - I've amended both of the issues that I've filed to point to 
https://github.com/PowerShell/PowerShell/blob/master/stylecop.json

which came in the same aforementioned PR. Did this edit at the top level issue so that it doesn't get buried in comments

**Comment by sharwell** [comment]
Sure, changes fall into two main categories:

1. Changes to rules present in both StyleCop "Classic" and StyleCop Analyzers are documented here: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/KnownChanges.md
2. Rules unique to StyleCop Analyzers (and thus have no corresponding rule in StyleCop "Classic" that would have been followed in the past) are called out in the Table of Analyzers accompanying each release. I haven't completed the table for 1.1.0-beta008, but it should be the same as [1.1.0-beta007](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.1.0-beta007).

**Comment by JonKohler** [comment]
Great! Thanks for the guidance here.

**Comment by TravisEz13** [comment]
cc @daxian-dbw

**Comment by livarcocc** [comment]
We have no plans for adopt stylecop at the moment.
