### ISSUE TITLE
Dotnet build fails on VSTS when targeting the .netcoreapp2.1 framework using the 2.1.300 SDK

### ISSUE THREAD

**Issue by amvi88** [dotnet/cli#9493]
## Steps to reproduce
Update an existent project, whose build is generated using VSTS, so that it now uses .netcoreapp2.1,
instead of  .netcoreapp2.0

`<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>`

Change the build definition so it uses the latest SDK that's compatible with the target framework
![image](https://user-images.githubusercontent.com/5505626/41431746-2eb852b4-6fd1-11e8-8caa-d352e12a1c07.png)

## Expected  behavior
Project builds fine, using either a Hosted or Hosted Linux Preview

## Actual behavior
Unable to completed the build process due to an issue

[error]Error: D:\a\_tool\dncs\2.1.300\x64\dotnet.exe failed. spawn D:\a\_tool\dncs\2.1.300\x64\dotnet.exe ENOENT

![image](https://user-images.githubusercontent.com/5505626/41432130-5325827e-6fd2-11e8-9dd7-3f510c2fd464.png)

## Environment data
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
Version      : 2.135.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)

**Comment by amvi88** [comment]
This only happened when upgrading, it seems it was related to the Working Directory having reference to an older version of the SDK instead of the new one, once we cleared the directory we were able to build again sans issues.

**Comment by hanssens** [comment]
+1 for what @amvi88 mentioned: after upgrading a single project from `netcoreapp2.0` => `netcoreapp2.1`, all builds for that project failed. We're running a custom build agent and although the latest SDK was installed, basically every dotnet command failed.

By deleting everything from `_work\*` on our build agent the problem was solved.
