### ISSUE TITLE
After installing 2.1.300, dotnet new no longer creates instances of templates

### ISSUE THREAD

**Issue by simmdan** [dotnet/cli#9499]
## Steps to reproduce
dotnet new console (or any other template name)

## Expected  behavior
New console project created.

## Actual behavior
No error, but no files created.  Command just returns to the console with no message.
Executable exit code is: 2097158

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## Other Info:
One of my computers works fine.  This one, however, does not.  I have tried uninstalling and reinstalling the dotnet sdk.  Rebooting the computer.  Uninstalling all other versions of the dotnet sdk, etc.  Same results.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1584
