### ISSUE TITLE
NuGet just changed Machine wide feed location

### ISSUE THREAD

**Issue by zhili1208** [dotnet/cli#951]
we just changed machine wide feed location. file a bug here in case the change might break cli.

https://github.com/NuGet/Home/issues/1899

Linux: /etc/opt/nuget/Config

OS X: /Library/Application Support/NuGet/Config
no changes on windows.

**Comment by blackdwarf** [comment]
@piotrpMSFT @davidfowl is this valid for us? I would think that it is not, given the timeframe when it was file, but better to check. If its not, we should close.
