### ISSUE TITLE
NuGetFallbackFolder created by Installer (.exe) contains more package versions than folder created by Binaries (.zip)

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#9511]
The customer impact may be minimal, but I was surprised to find the NuGetFallbackFolder created by the installer (.exe) contains more package versions than the NuGetFallbackFolder created by the binaries (.zip).  I assumed the folders would be identical.

## Steps to reproduce
1. Install SDK 2.1.300, both the "x64 Installer" (.exe) and "x64 Binaries" (.zip)
2. Run `dotnet new --list` for the "x64 Binaries" installation to create the NuGetFallbackFolder
3. Compare the contents of the two NuGetFallbackFolders

## Expected  behavior
Same content

## Actual behavior
The NuGetFallbackFolder created by the installer (.exe) contains more versions of many packages.  For example, here are the versions of `microsoft.netcore.app` in each:

```
Installer: microsoft.netcore.app 2.0.0, 2.0.3, 2.1.0
Binaries: microsoft.netcore.app 2.1.0
```

CC: @JunTaoLuo, @joeloff

**Comment by joeloff** [comment]
Were there previous SDKs installed using the EXE or is this a clean install?

**Comment by mikeharder** [comment]
@joeloff : Clean install on Win10.

**Comment by livarcocc** [comment]
This issue needs to be moved to ASP.NET, where the lzma archive is generated. @mikeharder do you want to do that?

**Comment by mikeharder** [comment]
@livarcocc: When I spoke with @JunTaoLuo last night, he didn't think the issue was related to how ASP.NET is generating the lzma archive.

@JunTaoLuo: Can you elaborate?

**Comment by JunTaoLuo** [comment]
The 2.0.0 and 2.0.3 are not coming from the LZMA. We have confirmed that they do not come from the first time experience. The 2.0 packages do not show up when installing via zip files but they show up when using the .exe installer.

**Comment by livarcocc** [comment]
This is not happening on 2.1.403. Also, in 3.0, we won't have the lzma anymore.
