### ISSUE TITLE
Proper fix Use a unchanging version for 'Microsoft.NETCore.App'

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#9512]
https://github.com/dotnet/cli/pull/8448

That means CLI has 3 runtime versions in one build. And we have to keep update this version. A practical reason. I cannot test  dotnet-cli-build anymore because stage2 cannot run on it

**Comment by livarcocc** [comment]
Closing as I believe this is now handled. @wli3 just re-activate if that's not the case.
