### ISSUE TITLE
Please return an errorlevel when template not found

### ISSUE THREAD

**Issue by aplocher** [dotnet/cli#9513]
## Steps to reproduce
`dotnet new some_template_that_doesnt_exist -l`

## Expected  behavior
Checking the `%ERRORLEVEL%` after searching for a template that isn't installed should result in something greater than 0 (error)

## Actual behavior
`%ERRORLEVEL%` is 0 (success) when searching for a non-existent template

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.201)

Product Information:
 Version:            2.1.201
 Commit SHA-1 hash:  7932dc6179

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17692
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.201\

Microsoft .NET Core Shared Framework Host                                >

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

```

**Example Scenario:** I would like to have a basic .bat or .ps1 script that would be used by my dev team when they need to generate some code based on our templates.  It could check for existence of the template and if not found, it would install them and then generate an interactive prompt with the necessary parameters before calling "dotnet new".

Naturally, doing a search for the template (using `dotnet new <name> -l`) was the first thing I tried to do, but without a meaningful errorlevel, it's not easy to determine if it's installed.

**Comment by peterhuene** [comment]
This issue was moved to dotnet/templating#1589
