### ISSUE TITLE
For .net core xunit projects, dotnet new succeeded when offline

### ISSUE THREAD

**Issue by YunWeiaa** [dotnet/cli#9528]
## Steps to reproduce

1. Create a new .net core xunit project via CLI,
2. dotnet restore

## Expected  behavior

xunit to fail to restore when offline (both for dotnet new and dotnet restore).

## Actual behavior

![dotnetnewsucceeded](https://user-images.githubusercontent.com/33921754/41703883-5748b17e-7567-11e8-9030-9a33f5e6d668.png)

## Environment data

D15.8/27820.00 (15.8 Preview 3) + CLI/SDK [2.1.302-preview-008945
`dotnet --info` output:
](https://github.com/dotnet/testimpact/issues/%5Cmmitche1%5Cnetcore2.1%5C2.1.2%5C20180618-01-stabilized%5Cassets%5CSdk%5C2.1.302-preview-008945%5Cdotnet-sdk-2.1.302-win-x64.exe)![data](https://user-images.githubusercontent.com/33921754/41703885-5a42f6e6-7567-11e8-8949-fadacdf31eed.PNG)

**Comment by YunWeiaa** [comment]
Moved to [#9528](https://github.com/dotnet/cli/issues/9528)

**Comment by peterhuene** [comment]
Hi @YunWeiaa.  This is by design.  The restore step is expected to fail, but the creation of the `xunit` project should succeed.  I don't see anything in the output that is unexpected.  Thanks!
