### ISSUE TITLE
'dotnet ef database update' errors when sub-minor version is not 0

### ISSUE THREAD

**Issue by lfshr** [dotnet/cli#9548]
## Steps to reproduce
```bash
apt-get install dotnet-sdk-2.1=2.1.301-1
cd <path/to/database/proj>
dotnet ef database update
```

## Expected  behavior
Database update is run using dotnet-runtime-2.1.x (latest installed on box)

## Actual behavior
dotnet falls back to 2.1.0 instead of finding 2.1.x

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.0.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      2.0.7 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      2.1.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Extra Details
This is not an issue on Windows as the dotnet installer does not clean up old versions of the runtime. apt-get will cleanup all old files contained in the older versions.

**Comment by peterhuene** [comment]
@wli3 this is unexpected.  Is the packaged `ef` tool targeting the wrong runtime or the apphost not rolling forward for some reason?

**Comment by wli3** [comment]
@peterhuene agree, this should not happen. We should see if we can repo it. I remember there is a env flag to not allow moving forward. maybe that is set?

**Comment by lfshr** [comment]
Hey guys. I think my colleague found the offending line in the csproj file.
```
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.0-rc1-final" />
```
Hold off on this and I'll figure out whether changing it to 2.1.0 fixed the issue tomorrow.
Should the apt package for 2.1.1-runtime remove the 2.1.0-runtime?

**Comment by wli3** [comment]
It is a bug that apt package would remove 2.1.1 runtime (I think there is one already). However, even it is removed, 2.1.1 is compatible with 2.1.0 and I should be used to run `ef`

**Comment by wli3** [comment]
I cannot repo on windows tho. In fact, the bundled `ef` is asking 2.1.1 
`C:\Program Files\dotnet\sdk\2.1.301\DotnetTools\dotnet-ef\2.1.1\tools\netcoreapp2.1\any\dotnet-ef.runtimeconfig`
```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.1"
    }
  }
}
```

**Comment by wli3** [comment]
There should not be any move forward happening. There is an exact runtime matches.

Maybe there is something like `--fx-version` used. 2.1.0 is pinned by it.

**Comment by lfshr** [comment]
This was an issue with the `Pomelo.EntityFrameworkCore.MySql` package. Adding a reference to `Microsoft.AspNetCore.All:2.1.0` fixed this issue.

```
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />
```

**Comment by lprichar** [comment]
I'm seeing this exact issue on Windows:

```
> dotnet ef database update
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

and --info:

```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Any thoughts on how to diagnose?

**Comment by peterhuene** [comment]
@wli3 can you investigate when you get a chance?

**Comment by lfshr** [comment]
@lprichar As a workaround if you download and install the 2.1.0 runtime from here: https://www.microsoft.com/net/download/dotnet-core/runtime-2.1.0

Does this workaround your issue?

**Comment by wli3** [comment]
@lprichar could you paste the content of this file `C:\Program Files\dotnet\sdk\2.1.301\DotnetTools\dotnet-ef\2.1.1\tools\netcoreapp2.1\any\dotnet-ef.runtimeconfig`

SDK 2.1.301's ef should default to 2.1.1 right in the beginning, I try to figure out where 2.1.0 get in to the picture.

**Comment by lprichar** [comment]
Sure, it's:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.1.1"
    }
  }
}
```

Actually I verified that before my workaround of installing 2.1.0, so I know that hasn't changed.

**Comment by wli3** [comment]
This is strange... the above runtime config means it should ask for 2.1.1 from the beginning. Maybe the problem is at the resolver.

**Comment by pmeems** [comment]
Any progress on this?
I'm working on my first .NET Core application using EF.Core. Just to test if it is all working. If not I'll restart with .NET v4.7 and EF6.
So far I'm mostly fighting with EF.Core

I've got the same error:

    >dotnet ef migrations add InitialCreate
    It was not possible to find any compatible framework version
    The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
      - Check application dependencies and target a framework version installed at:
          C:\Program Files\dotnet\
      - Installing .NET Core prerequisites might help resolve this problem:
          http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
      - The .NET Core framework and SDK can be installed from:
          https://aka.ms/dotnet-download
      - The following versions are installed:
          2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
          2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

My `dotnet-ef.runtimeconfig`:

    {
      "runtimeOptions": {
        "tfm": "netcoreapp2.1",
        "framework": {
          "name": "Microsoft.NETCore.App",
          "version": "2.1.1"
        }
      }
    }

**Comment by livarcocc** [comment]
@bricelam is ef doing something to prefer a particular runtime over another?

**Comment by pmeems** [comment]
I solved this issue as well by installing 2.1.0, like @lprichar suggested.
Of course this should not be necessary since I already had v2.1.2 installed.

**Comment by bricelam** [comment]
If dotnet-ef doesn't see a `*.runtimeconfig.json` file for the project, we specify `--fx-version` using the value of `$(RuntimeFrameworkVersion)`. But that shouldn't be happening here...

**Comment by LuisduardoLanfredi** [comment]
@lprichar solution also worked for me. I agree that it should not be necessary since I already have the most recent .net core version installed.

**Comment by lfshr** [comment]
@wli3 did you manage to make any progress on this?

**Comment by wli3** [comment]
Sorry I don't have any progress. Although dotnet-ef is [no long built-in to sdk](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#the-ef-core-command-line-tool-dotnet-ef-is-no-longer-part-of-the-net-core-sdk)

**Comment by wli3** [comment]
Close as there is no further report
