### ISSUE TITLE
Dotnet build error MSB4062: The "Microsoft.Build.Tasks.ResolveComReference"

### ISSUE THREAD

**Issue by Johnz86** [dotnet/cli#9558]
## Steps to reproduce
- create console app
- add com reference for example: FirewallAPI.dll
```
    <COMReference Include="NetFwTypeLib.dll">
      <Guid>58fbcf7c-e7a9-467c-80b3-fc65e8fcca08</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>false</Isolated>
    </COMReference>
```
- dotnet build
- dotnet publish -c Release -r win-x64

## Expected  behavior
Console application will produce .exe file

## Actual behavior
```
C:\GIT\ImgPoolCS>dotnet.exe publish -c Release -r win-x64 -f netcoreapp2.0
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\GIT\ImgPoolCS\LiCS.csproj...
  Installing Microsoft.NETCore.DotNetAppHost 2.0.7.
  Installing Microsoft.NETCore.DotNetHostResolver 2.0.7.
  Installing Microsoft.NETCore.DotNetHostPolicy 2.0.7.
  Installing Microsoft.NETCore.App 2.0.7.
  Installing Microsoft.NETCore.Platforms 2.0.2.
  Installing runtime.win-x64.Microsoft.NETCore.DotNetAppHost 2.0.7.
  Installing runtime.win-x64.Microsoft.NETCore.DotNetHostResolver 2.0.7.
  Installing runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy 2.0.7.
  Installing runtime.win-x64.Microsoft.NETCore.App 2.0.7.
  Generating MSBuild file C:\GIT\ImgPoolCS\obj\LiCS.csproj.nuget.g.props.
  Generating MSBuild file C:\GIT\ImgPoolCS\obj\LiCS.csproj.nuget.g.targets.
  Restore completed in 57,42 sec for C:\GIT\ImgPoolCS\LiCS.csproj.
C:\Program Files\dotnet\sdk\2.1.301\Microsoft.Common.CurrentVersion.targets(2725,5): error MSB4062: The "Microsoft.Build.Tasks.ResolveComReference" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0
, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Bui
ld.Framework.ITask. [C:\GIT\ImgPoolCS\LiCS.csproj]
```
Same error is produced by ```dotnet build```
If I run this project in ```Visual Studio 2017``` and build a release and debug, everything is fine. No error is produced. But this unfortunately does not produce ```.exe``` file.

## Environment data
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.105 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
@rainersigwald 

I don't believe this is supported in core.

**Comment by Johnz86** [comment]
Then it is strange, that build steps under ````visual studio 2017``` work without any error.  I am able to lunch the program from IDE. Only execution of dotnet build/publish commands produces these errors.

**Comment by Johnz86** [comment]
Ok my bad, visual studio builds the project, without error, unfortunately, when the code is called it is not able to find the reference.

**Comment by livarcocc** [comment]
I believe it builds successfully on MSBuild because full framework MSBuild has the tasks necessary to build it. However, dotnet core does not understand this type of reference and we currently don't have plans to add support for it.

**Comment by rainersigwald** [comment]
That's correct; we don't build `ResolveCOMReference` for core. You can use it when you build with `msbuild.exe`, but not `dotnet build` or similar. If it's not supported at runtime, we probably shouldn't add it at build time (though producing a better error might be nice).

**Comment by livarcocc** [comment]
What is the appropriate layer to add the error message?

**Comment by solidcloudio** [comment]
Why make a featureless version of MSBuild that can't load Build Task Assemblies?

**Comment by rainersigwald** [comment]
@solidcloudio That's not what's happening here. The assembly is loadable (other tasks from it were used during the build) but the specific task `ResolveCOMReference` is not part of it.

@livarcocc The right layer is probably MSBuild. I filed Microsoft/msbuild#3499 to track this generally.

**Comment by livarcocc** [comment]
Closing this as a follow up bug has been filed in a separate repo.

**Comment by jhudsoncedaron** [comment]
So I'm going to leave this here because searching for the error yields this page.

COM References don't work when building with the .NET Core 3.1 LTS Toolchain. Use <A HREF="https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-generate-primary-interop-assemblies-using-tlbimp-exe">tlbimp</A> to make a PIA dll and link against that instead.

We're opting to use a specific version of the .NET Core toolchain for building .NET Framework projects to keep installed updates from breaking the build tools anymore and we want to be able to build the product a decade from now.
