### ISSUE TITLE
Add package: specify dependency resolution strategy

### ISSUE THREAD

**Issue by shatl** [dotnet/cli#9560]
Add option to specify dependency resolution strategy ```dotnet add package```

* Exact - install dependency version specified in nuspec file;
* HighestPatch - install highest available minor version for major version specified in nuspec;
* HighestMinor - install highest available minor and patch version for major version specified in nuspec;
* HighestMajor (Latest) - install latest version.

E.g. nuspec dependency version is *1.1.1*, nuget has *1.1.10*, *1.2.1*, and *2.1.1*

* `Exact` should install 1.1.1;
* `HighestPatch` should install 1.1.10;
* `HighestMinor` should install 1.2.1;
* `HighestMajor` should install 2.1.1

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7064
