### ISSUE TITLE
Mac OS .NET CLI: not contains Identity files

### ISSUE THREAD

**Issue by agiletuan** [dotnet/cli#9561]
## Steps to reproduce
run the following command at the command line:

`dotnet new mvc --auth Individual`

## Expected  behavior
Project will contains Asp.Net Identity module.
- File: Controllers/AccountController.cs
- File: Controllers/ManageController.cs
- File: Models/ApplicationUser.cs
- Folders: AccountViewModels (and files), ManageViewModels (and files)

## Actual behavior
Project not contains Asp.Net Identity module.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1594
