### ISSUE TITLE
Add switch to disable implicit fallback folder for 1.x apps only

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/cli#9563]
Currently there is the switch `DisableImplicitNuGetFallbackFolder` that can turn off the fallback folder for all apps. However, due to the differences in how fallback folders are used by the CLI, we would like to have a new switch so we can disable fallback for 1.x apps only but leave the fallback folder turned on for 2.x apps.

**Comment by livarcocc** [comment]
@wli3 would you like to handle this issue? It should be a small change on the SDK.
