### ISSUE TITLE
Docker publish image is broken in VS.net 15.7.4 + ASP.NET Core site

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/cli#9564]
## Steps to reproduce
1. Create an empty ASP.NET Core website
2. Select the project
3. From the Project Menu choose Docker Support
4. Choose Linux.
5. Note standard build doesn't work until you change the docker-compose.yml to have context: <Project Name> and dockerfile: Dockerfile.
6. Right click on the project and choose publish.
7. Choose Container Source/Azure and click publish.

## Expected  behavior
At this point it should build the docker container the same as it does during debug and then publish it to Auzre's Container Store.

## Actual behavior
failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder436813243/...

##Environment
Docker 18.05.0

Note also that errors aren't properly parsed from the docker commands so you only get the last one which is about Docker_Registry not being set, which isn't really an error and should just show up as a warning. So you have to go digging in the logs.

Also there is no docker_compose.override.yml for ci created with any settings.

And with the default files, there is nothing that sets the /app and /src folders so there's no way that this could work.

Hence Docker is effectively useless in VS.NET as it stands right now because you can never get your stuff out of it into VSTS or Azure or anywhere else.

**Comment by livarcocc** [comment]
@MichaelSimons can you take care of this issue?

**Comment by MichaelSimons** [comment]
@livarcocc - for future reference, I don't work on/own the VS Docker tooling experience.  Issues related to the VS Docker tooling experience should get logged at https://github.com/Microsoft/dockertools.

Copied to https://github.com/Microsoft/DockerTools/issues/125
