### ISSUE TITLE
dotnet build and custom target with a depenedency on Json.Net: File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

### ISSUE THREAD

**Issue by maririos** [dotnet/cli#9578]
@abatishchev commented on [Thu Jun 21 2018](https://github.com/dotnet/buildtools/issues/2074)

Hi,
I have a project (Service Fabric if that matters) which uses a custom props and targets files which call a DLL winch has a dependency on Newtonsoft.Json.dll which is shipped alongside.
When I build inside VS2017 I have no errors.
But when I run `dotnet build` I'm getting this:

> BuildLayout.targets(21,5): error MSB4018: The "GenerateArmTemplateTask" task failed unexpectedly. [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): **error MSB4018: File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'** [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at BuildLayout.Generators.TemplateGenerator.Generate(BuildLayoutOptions args, ApplicationManifestType appManifest) [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at BuildLayout.Generators.BuildLayoutGenerator.Generate(BuildLayoutOptions args) in e:\bt\921388\repo\src\product\buildlayout\Generators\BuildLayoutGenerator.cs:line 23 [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at BuildLayout.Tasks.GenerateArmTemplateTask.Execute() in e:\bt\921388\repo\src\product\buildlayout\Tasks\GenerateArmTemplateTask.cs:line 46 [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [DeploymentAgent.sfproj]
BuildLayout.targets(21,5): error MSB4018:  [DeploymentAgent.sfproj]

Please help me to understand how it works and why i'm getting it.

---

@abatishchev commented on [Tue Jun 26 2018](https://github.com/dotnet/buildtools/issues/2074#issuecomment-400416479)

Ping.

**Comment by livarcocc** [comment]
Please, provide us with repro steps or a small github repo with a repro on it.

**Comment by livarcocc** [comment]
It is possible that what is happening here is that you are referencing a different newtonsoft.json than the one shipped with the CLI. Given that a MSBuild task runs within the context of the CLI dependencies, you need to make the version match. We ship version 9.0.1. Can you try referencing that version and re-running your scenario?

**Comment by abatishchev** [comment]
hi, yes, that's likely the cause. Does this mean that all projects that produce a build target with a dependency  on Json.Net and want be compatible with .NET Core/dotnet.exe have to use the same version of Json.Net? What if a project is used by both Core 2.0 and 2.1 and they depends on different versions? Or let's say Core 2.2 in the near future is getting shipped with Json.Net 11?

**Comment by abatishchev** [comment]
Do you need a repro repo? I'm constantly getting this error and pretty sure that the reason you've described is indeed what happens here.

**Comment by livarcocc** [comment]
Right, if you want to be a task, because we don't have different Assembly Contexts for tasks, your dependencies that are the same as the CLI, need to match exactly what we have in the CLI. As for multitargetting, that should be fine, the latest CLI, say 2.2, can build 2.2, 2.1 and 2.0 and for all three of them, the tasks all share the same dependency closure. So, just target the newtonsoft version used by the CLI you are going to use to build your project and this should work.

**Comment by abatishchev** [comment]
Is the information about which version of Json.Net which version of .NET Core CLI uses published anywhere?

**Comment by livarcocc** [comment]
https://github.com/dotnet/cli/blob/master/src/dotnet/dotnet.csproj#L58

**Comment by abatishchev** [comment]
Means it isn't documented anywhere, I need to go to the source code of particular version and find that out, I see.

**Comment by abatishchev** [comment]
> I'm not sure why it's trying to find 11.0.0.0 since that isn't what the package is requiring.

Because `Mobile.BuildTools.dll` was built with binary reference to version `11.0.0.0`.

I see two options:

- have it built against the same version as your current version of ,NET Core build tools use (apparently now this is [10.0.3](https://github.com/dotnet/cli/blob/master/src/dotnet/dotnet.csproj#L62) now)
- try to add assembly binding redirect to whatever version you'd like in `dotnet.exe.config`

**Comment by shwanton** [comment]
> Because Mobile.BuildTools.dll was built with binary reference to version 11.0.0.0

I was confused since it looked like `Mobile.BuildTools` was using version [11.0.2](https://github.com/dansiegel/Mobile.BuildTools/blob/ce909af4beb8b3e39b8adfe9e07c0812d583c441/Mobile.BuildTools/Mobile.BuildTools.csproj#L16)

> try to add assembly binding redirect to whatever version you'd like in dotnet.exe.config
It doesn't seem like dotnetcore supports binding redirects.

> have it built against the same version as your current version of ,NET Core build tools use 
I'll give that a try, thanks!

**Comment by abatishchev** [comment]
I think the source of confusing was that AssemblyVersion for all releases in 11.x.x is 11.0.0. Give it a try and please let me know.

**Comment by shwanton** [comment]
Looks like I can't actually rebuild this package with my current configuration (mono on macOS):
`The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.`

I opened up an [issue](https://github.com/dansiegel/Mobile.BuildTools/issues/53) on the Mobile.BuildTools repo so I can take it up there.

**Comment by abatishchev** [comment]
Suggestion them to take a look at RoslynCodeTaskFactory, see [the doc](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017).
