### ISSUE TITLE
Tools 2.2.0-preview1-02829-01 require presence of `~/.dotnet/NuGetFallbackFolder`

### ISSUE THREAD

**Issue by maririos** [dotnet/cli#9579]
@janvorli commented on [Fri Jun 01 2018](https://github.com/dotnet/buildtools/issues/2055)

I have found that the init-tools.sh fails for me in coreclr repo after the build tools version was updated to Tools 2.2.0-preview1-02829-01. The issue is that it requires presence of `~/.dotnet/NuGetFallbackFolder` folder, which I don't have. I believe build tools should not depend on such external dependencies.

I get this error message during init-tools.sh:
```
Running: /home/janvorli/git/coreclr/init-tools.sh
Installing 'https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300-rtm-008820/dotnet-sdk-2.1.300-rtm-008820-linux-x64.tar.gz' to '/home/janvorli/git/coreclr/Tools/dotnetcli/dotnet.tar'
Running: /home/janvorli/git/coreclr/Tools/dotnetcli/dotnet restore "/home/janvorli/git/coreclr/init-tools.msbuild" --no-cache --packages /home/janvorli/git/coreclr/packages --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json /p:BuildToolsPackageVersion=2.2.0-preview1-02829-01 /p:ToolsDir=/home/janvorli/git/coreclr/Tools

Configuring...
--------------
A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.
Decompressing .......... 9546 ms
Expanding .......... 30509 ms
  Restoring packages for /home/janvorli/git/coreclr/init-tools.msbuild...

/home/janvorli/git/coreclr/Tools/dotnetcli/sdk/2.1.300-rtm-008820/NuGet.targets(114,5): error : The local source '/home/janvorli/.dotnet/NuGetFallbackFolder' doesn't exist. [/home/janvorli/git/coreclr/init-tools.msbuild]
```

Creating an empty `~/.dotnet/NuGetFallbackFolder` fixes the issue.

---

@dagood commented on [Thu Jun 07 2018](https://github.com/dotnet/buildtools/issues/2055#issuecomment-395519497)

This looks more like a CLI or NuGet issue to me. The error occurs in the downloaded CLI's `sdk/2.1.300-rtm-008820/NuGet.targets` after init-tools has handed off control to `dotnet restore`.

How sure are you about the timing of the break? Could it have started when CLI was upgraded in https://github.com/dotnet/coreclr/pull/17925?

**Comment by janvorli** [comment]
> How sure are you about the timing of the break?

I am not sure at all. I have just updated to the latest master after some time and I've hit this. So it could have been some older change.

**Comment by livarcocc** [comment]
It seems to me like you have an entry to `'/home/janvorli/.dotnet/NuGetFallbackFolder'` in a NuGet config somewhere and the folder does not exist. It might have been an error that NuGet was resilient to before and now it fails. Can you check that?

**Comment by janvorli** [comment]
Where can I look for such a NuGet.config file? I definitely didn't have it in the coreclr repo root where I have started the init-tools.sh from

**Comment by wli3** [comment]
it should be just called nuget.config. Maybe a global search can find it. Also, it apples when it presents in parents directories. So, if there is not too much folders above, you can look for it from parent directories.

And also global location is the following. Nuget restore log should also have it.

%appdata%\NuGet\nuget.config
 ~/.nuget/NuGet/NuGet.Config

**Comment by livarcocc** [comment]
Closing this issue since we haven't had activity here in a long time and haven't heard back if there is an entry for the bad folder anywhere in a nuget.config file in the machine or not.
