### ISSUE TITLE
VSTS build agent dotnet restore not using configfile argument correctly

### ISSUE THREAD

**Issue by tommorganshaw** [dotnet/cli#9587]
## Steps to reproduce
VSTS build agent running on an on-premise server behind a corporate firewall and proxy server, so the NuGet config needs define the proxy settings.

The build definition uses the .Net Core template. The dotnet restore step uses the default settings, except for defining "Feeds in my NuGet config" which points to NuGet.config that includes proxy settings.

The complete command that the build step executes is:

`"2018-06-26T14:10:02.2401648Z [command]"C:\Program Files\dotnet\dotnet.exe" restore D:\BuildAgents\1\_work\27\s\MyDotNetCoreWebsite\MyDotNetCoreWebsite.csproj --configfile D:\BuildAgents\1\_work\27\Nuget\tempNuGet_43655.config --verbosity Detailed"`

It appears that when the build runs, it takes a copy of the NuGet.config file, renames it a and drops it in a temp directory:

`"D:\BuildAgents\1\_work\38\Nuget\tempNuGet_43654.config"`

This file does include the correct proxy settings:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="http_proxy" value="http://10.1.0.10:8080" />
  </config>
  <packageSources>
    <add key="NuGet official package source" value="http://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

## Expected  behavior

Dotnet restore should use the `tempNuGet_43654.config` file when running the restore operation.

## Actual behavior

Dotnet restore is _always_ using the User-level NuGet.config in the following location:

`"C:\Users\USERNAME\AppData\Roaming\NuGet\NuGet.config"`

This file does not include the necessary proxy settings and, consequently, the restore operation fails saying "A connection with the server could not be established".

```
2018-06-29T16:16:09.3058376Z          C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Unable to load the service index for source http://api.nuget.org/v3/index.json. [d:\BuildAgents\1\_work\38\s\MyDotNetCoreWebsite\MyDotNetCoreWebsite.csproj]
2018-06-29T16:16:09.3058625Z        C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   An error occurred while sending the request. [d:\BuildAgents\1\_work\38\s\MyDotNetCoreWebsite\MyDotNetCoreWebsite.csproj]
2018-06-29T16:16:09.3058895Z        C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   A connection with the server could not be established [d:\BuildAgents\1\_work\38\s\MyDotNetCoreWebsite\MyDotNetCoreWebsite.csproj]
```

Some additional notes:

- Running the dotnet restore command from the command prompt has the same issue.

- Placing NuGet.config files with the proxy setting the project directory, or in various places in the directory hierarchy makes no difference.

- Other NuGet restore operations using .NET Framework on the build server complete correctly without the same issue. They appear to be using their own NuGet.config files with proxy settings and not relying on the APPDATA NuGet.config.

- Putting the proxy settings into the NuGet.config in AppData works and the restore operation can complete. However, there are other operations that fail so this can't be the resolution.

## Environment data
`dotnet --info` output:

C:\>dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7210
