### ISSUE TITLE
dotnet restore dose not work on Mac OS X 10.11.2

### ISSUE THREAD

**Issue by hunter-xue** [dotnet/cli#959]
"dotnet new" is working well but "dotnet restore" looks like did nothing, there are no any packages downloaded from NuGet. Thus "dotnet run" and other subsequence commands cannot working.

**Comment by blackdwarf** [comment]
@hunter-xue the commands are invoked properly? What it the version that you installed?

**Comment by hunter-xue** [comment]
@blackdwarf I downloaded the latest version 3 hours before. Yes, the command invoked correctly but nothing displayed and nothing done.

**Comment by blackdwarf** [comment]
@hunter-xue can you do dotnet -v and send the output?

**Comment by hunter-xue** [comment]
@blackdwarf 
.NET Command Line Tools (1.0.0)
Usage: dotnet [common-options] [command] [arguments]

**Comment by piotrpMSFT** [comment]
https://github.com/dotnet/cli/issues/1065

**Comment by piotrpMSFT** [comment]
This should already be fixed. Can you confirm @hunter-xue ?

**Comment by hunter-xue** [comment]
@piotrpMSFT yes, it worked for me, but get another error when execute "dotnet restore": 

info : Restoring packages for /Users/xuehaitao/Coding/dnx/p2/project.json...
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection/4.1.0-rc3-23727/system.reflection.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.handles/4.0.1-rc3-23727/system.runtime.handles.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.extensions/4.0.10/system.runtime.extensions.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.text.encoding.extensions/4.0.11-rc3-23727/system.text.encoding.extensions.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection/4.0.10/system.reflection.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.debug/4.0.11-rc3-23727/system.diagnostics.debug.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.io.filesystem.primitives/4.0.1-rc3-23727/system.io.filesystem.primitives.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection.extensions/4.0.1-rc3-23727/system.reflection.extensions.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
Too many open files
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.netcore.platforms/1.0.1-rc3-23727/microsoft.netcore.platforms.1.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.collections/4.0.11-rc3-23727/system.collections.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.globalization/4.0.11-rc3-23727/system.globalization.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.text.encoding/4.0.11-rc3-23727/system.text.encoding.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.net.primitives/4.0.11-rc3-23727/system.net.primitives.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.resources.resourcemanager/4.0.0/system.resources.resourcemanager.4.0.0.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.extensions/4.1.0-rc3-23727/system.runtime.extensions.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.interopservices/4.1.0-rc3-23727/system.runtime.interopservices.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.console/4.0.0-rc3-23727/system.console.4.0.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.text.regularexpressions/4.0.11-rc3-23727/system.text.regularexpressions.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection.typeextensions/4.1.0-rc3-23727/system.reflection.typeextensions.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.io/4.1.0-rc3-23727/system.io.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading/4.0.10/system.threading.4.0.10.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.tracing/4.0.20/system.diagnostics.tracing.4.0.20.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading/4.0.11-rc3-23727/system.threading.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime/4.0.20/system.runtime.4.0.20.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.globalization/4.0.10/system.globalization.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.tools/4.0.1-rc3-23727/system.diagnostics.tools.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.tracing/4.0.21-rc3-23727/system.diagnostics.tracing.4.0.21-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.netcore.runtime/1.0.1-rc3-23727/microsoft.netcore.runtime.1.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading.timer/4.0.1-rc3-23727/system.threading.timer.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.collections/4.0.10/system.collections.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.debug/4.0.10/system.diagnostics.debug.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.win32.primitives/4.0.1-rc3-23727/microsoft.win32.primitives.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.linq/4.0.1-rc3-23727/system.linq.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading.tasks/4.0.10/system.threading.tasks.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime/4.1.0-rc3-23727/system.runtime.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.io.filesystem.primitives/4.0.1-rc3-23727/system.io.filesystem.primitives.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection/4.1.0-rc3-23727/system.reflection.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection/4.0.10/system.reflection.4.0.10.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection.extensions/4.0.1-rc3-23727/system.reflection.extensions.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.debug/4.0.11-rc3-23727/system.diagnostics.debug.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.handles/4.0.1-rc3-23727/system.runtime.handles.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Retrying 'FindPackagesByIdAsync' for source https://api.nuget.org/v3-flatcontainer/.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.extensions/4.0.10/system.runtime.extensions.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.interopservices.runtimeinformation/4.0.0-rc3-23727/system.runtime.interopservices.runtimeinformation.4.0.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading.tasks/4.0.11-rc3-23727/system.threading.tasks.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.collections/4.0.11-rc3-23727/system.collections.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.collections/4.0.10/system.collections.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.console/4.0.0-rc3-23727/system.console.4.0.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.win32.primitives/4.0.1-rc3-23727/microsoft.win32.primitives.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
error: Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection/4.0.10/system.reflection.4.0.10.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.tracing/4.0.21-rc3-23727/system.diagnostics.tracing.4.0.21-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.netcore.platforms/1.0.1-rc3-23727/microsoft.netcore.platforms.1.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.globalization/4.0.11-rc3-23727/system.globalization.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/microsoft.netcore.runtime/1.0.1-rc3-23727/microsoft.netcore.runtime.1.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime/4.0.20/system.runtime.4.0.20.nupkg'.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.runtime.extensions/4.1.0-rc3-23727/system.runtime.extensions.4.1.0-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.diagnostics.tracing/4.0.20/system.diagnostics.tracing.4.0.20.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.text.encoding/4.0.11-rc3-23727/system.text.encoding.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.globalization/4.0.10/system.globalization.4.0.10.nupkg'.
An error occurred while sending the request.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.threading/4.0.11-rc3-23727/system.threading.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
info : Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.net.primitives/4.0.11-rc3-23727/system.net.primitives.4.0.11-rc3-23727.nupkg'.
An error occurred while sending the request.
error: Failed to download package from 'https://www.myget.org/F/dotnet-core/api/v3/flatcontainer/system.reflection.extensions/4.0.1-rc3-23727/system.reflection.extensions.4.0.1-rc3-23727.nupkg'.
An error occurred while sending the request.
error: Unable to load package 'System.Reflection'.
error: Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/'.
An error occurred while sending the request.

**Comment by blackdwarf** [comment]
@hunter-xue for the "too many open files" you can check out [this SuperUser article](http://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1) that can help you increase the limit. See if that helps.

**Comment by blackdwarf** [comment]
@hunter-xue does this still repro for you?

**Comment by hunter-xue** [comment]
@blackdwarf  though this issue is resolved but others, seems .net cannot work well on mac ox x 10.11.2 right now.
