### ISSUE TITLE
add package foundation-sites gives error

### ISSUE THREAD

**Issue by Miclebrick** [dotnet/cli#9594]
## Steps to reproduce
dotnet new razor
dotnet add package foundation-sites

## Expected  behavior
installs  package

## Actual behavior
miclebrick@micles-workshop:~/Web/starlegacy.net$ dotnet add package foundation-sites
  Writing /tmp/tmp74iiKh.tmp
info : Adding PackageReference for package 'foundation-sites' into project '/home/miclebrick/Web/starlegacy.net/starlegacy.net.csproj'.
log  : Restoring packages for /home/miclebrick/Web/starlegacy.net/starlegacy.net.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/foundation-sites/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/foundation-sites/6.4.3/foundation-sites.6.4.3.nupkg
log  : Installing foundation-sites 6.4.3.
error: Access to the path '/home/miclebrick/.nuget/packages/foundation-sites/6.4.3/foundation-sites.nuspec' is denied.
error:   Permission denied

## Environment data
`dotnet --info` output:
miclebrick@micles-workshop:~$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     zorin
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment]
Hi @Miclebrick.  Thanks for reporting this to us!

Are you having this issue only with this particular package?  Could you check to see if `~/.nuget` or ` '~/.nuget/packages` has some weird permissions, such as having `root` as the owner rather than `miclebrick`?

**Comment by Miclebrick** [comment]
Huh, it seems to. But I tried it with a new folder and it still didn't work. I'll try fixing the permissions and then doing it.

**Comment by Miclebrick** [comment]
```
miclebrick@micles-workshop:~/Documents/starlegacy.net$ sudo chown miclebrick ~/.nuget -R
miclebrick@micles-workshop:~/Documents/starlegacy.net$ dotnet add package foundation-sites
  Writing /tmp/tmpuHj4Ut.tmp
info : Adding PackageReference for package 'foundation-sites' into project '/home/miclebrick/Documents/starlegacy.net/starlegacy.net.csproj'.
log  : Restoring packages for /home/miclebrick/Documents/starlegacy.net/starlegacy.net.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/foundation-sites/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/foundation-sites/6.4.3/foundation-sites.6.4.3.nupkg
log  : Installing foundation-sites 6.4.3.
error: Access to the path '/home/miclebrick/.nuget/packages/foundation-sites/6.4.3/content/Scripts' is denied.
error:   Permission denied
```
Using chown didn't work. The permissions for the folder it can't access seem fine https://i.snag.gy/b69nBt.jpg

**Comment by Miclebrick** [comment]
I tried it with nhibernate, and it worked fine, so it only happens with this package

**Comment by Miclebrick** [comment]
I ended up using bootstrap anyway, so I don't really need help with this anymore, but I will leave the issue open in case someone else has the issue... unless nobody else can reproduce it and it's just on my end

**Comment by ChrisK91** [comment]
I'm experiencing the exact same issue on Windows, running Visual Studio 2017. Might be something funky with the package, as other packages install fine:

```
PM> Install-Package foundation-sites
Restoring packages for d:\Daten\Dokumente\Visual Studio 2017\Projects\Memelyzer\Memelyzer\Memelyzer.csproj...
  GET https://api.nuget.org/v3-flatcontainer/foundation-sites/index.json
  OK https://api.nuget.org/v3-flatcontainer/foundation-sites/index.json 558ms
  GET https://api.nuget.org/v3-flatcontainer/foundation-sites/6.4.3/foundation-sites.6.4.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/foundation-sites/6.4.3/foundation-sites.6.4.3.nupkg 455ms
Installing foundation-sites 6.4.3.
Install-Package : Access to the path 'C:\Users\USERNAME\.nuget\packages\foundation-sites\6.4.3\content\Scripts' is denied.
At line:1 char:1
+ Install-Package foundation-sites
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7239

**Comment by DanielRuf** [comment]
Is this still relevant for 6.5.3?
