### ISSUE TITLE
Mystery 255 exit code from dotnet restore

### ISSUE THREAD

**Issue by MattGal** [dotnet/cli#9603]
@dotnet-mc-bot commented on [Thu Jun 28 2018](https://github.com/dotnet/core-eng/issues/3789)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1810583
  - **Agent:** DDVSOWINAGE059
  - **Error log:** ERROR: An error occured when trying to initialize the tools. ...

@jcagme, @markwilkie

---

@MattGal commented on [Mon Jul 02 2018](https://github.com/dotnet/core-eng/issues/3789#issuecomment-401875700)

I haven't gotten this precise repro but it's clear from trying this out on the same agent it ran on that dotnet.exe can leak and cause problems.  I'm experimenting to get a better repro since the log is mostly useless.

E:\A\_work\40\s>handle.exe Tools\

Nthandle v4.1 - Handle viewer
Copyright (C) 1997-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

dotnet.exe         pid: 4608   type: File            34: E:\A\_work\40\s\Tools\dotnetcli\sdk\2.1.301\Roslyn\bincore
dotnet.exe         pid: 4608   type: File           248: E:\A\_work\40\s\Tools\dotnetcli\sdk\2.1.301\Roslyn\bincore\VBCSCompiler.dll
dotnet.exe         pid: 4608   type: File           268: E:\A\_work\40\s\Tools\dotnetcli\sdk\2.1.301\Roslyn\bincore\Microsoft.CodeAnalysis.dll
dotnet.exe         pid: 4608   type: File           3BC: E:\A\_work\40\s\Tools\dotnetcli\sdk\2.1.301\Roslyn\bincore\Microsoft.CodeAnalysis.CSharp.dll
dotnet.exe         pid: 4608   type: File           3C0: E:\A\_work\40\s\Tools\dotnetcli\sdk\2.1.301\Roslyn\bincore\Microsoft.CodeAnalysis.VisualBasic.dll

**Comment by MattGal** [comment]
I spent a long time experimenting looking for a repro for this with no luck.  

The command it was trying to run was:

```"E:\A\_work\40\s\Tools\dotnetcli\dotnet.exe" restore "E:\A\_work\40\s\Tools\generated\project.csproj" --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json  --packages "E:\A\_work\40\s\Tools\." ```

There isn't much actionable here so I mostly moved the issue in the hopes that the error experience here (return code 255 is pretty useless) could possibly be improved.  Otherwise, feel free to close the issue.

**Comment by nguerrera** [comment]
The compiler server sticking around is expected. It does this to speed up subsequent builds. There is a command to stop it `dotnet build-server shutdown`

**Comment by nguerrera** [comment]
The exit code here would come from what our shell out to `msbuild /t:restore` returned. It's hard to say how the error experience could be improved without some repro to understand what actually happened, and the build logs linked seem to be deleted so I'm going to close this out.
