### ISSUE TITLE
Change Project.json files not to use * dependencies

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#961]
I am proposing that we remove all * dependencies in the repo. 

It opens us to situations where upgraded dependencies break our build (it has happened a few times in the history of CLI) without any changes on our side.

It's also pretty difficult to diagnose when this happens.

thoughts? @Sridhar-MS @livarcocc @piotrpMSFT @anurse

**Comment by anurse** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by piotrpMSFT** [comment]
Please add a check to the validator.

**Comment by livarcocc** [comment]
Please do. It bit us so much last week. Can you follow Peter's suggestion and add a check to the validator? Could we have that check fail the build?

**Comment by brthor** [comment]
@livarcocc @piotrpMSFT I can build off of @dagood 's work in corefx to make this happen.

**Comment by piotrpMSFT** [comment]
Fixed long ago....
