### ISSUE TITLE
my MVC core app to Azure doesn't run on Azure 

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/cli#9614]
## Steps to reproduce

- take existing aspnet core mvc application
- run fine in localhost
- publish on Azure with extension ASP.NET Core Extensions (2.1.0-preview2-final)

## Expected  behavior
working

## Actual behavior
get an error:

> [2018-07-06 11:57:06.2613912] | [Fatal] | Application startup exception
> Could not load type 'System.Buffers.IMemoryOwner`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
> Method 'Rent' in type 'System.Buffers.SlabMemoryPool' from assembly 'Microsoft.AspNetCore.Server.IISIntegration, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.|
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load type 'System.Buffers.IMemoryOwner`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
> Method 'Rent' in type 'System.Buffers.SlabMemoryPool' from assembly 'Microsoft.AspNetCore.Server.IISIntegration, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
>    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    at System.Reflection.RuntimeAssembly.get_DefinedTypes()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
>    at CNote.Web.Startup.ConfigureServices(IServiceCollection services) in D:\Work\Vmmlog\CNoteV2\CNote.Web\Startup.cs:line 115
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

fyi:
my csporj settings are:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
    <!--<PreserveCompilationContext>true</PreserveCompilationContext>-->
    <AssemblyName>CNote.Web</AssemblyName>
    <PackageId>CNote.Web</PackageId>
    <RootNamespace>CNote.Web</RootNamespace>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier> 
    <UserSecretsId>aspnet-CNote.WebTemp-578D9585-4C3A-4FF8-8B4E-986120CC7745</UserSecretsId>
    <ApplicationInsightsResourceId>/subscriptions/99a5a2db-df8a-4693-8495-0847a1b6cb38/resourcegroups/CNoteV2Web/providers/microsoft.insights/components/%28Project Name%29</ApplicationInsightsResourceId>
    <ApplicationInsightsAnnotationResourceId>/subscriptions/99a5a2db-df8a-4693-8495-0847a1b6cb38/resourceGroups/CNoteV2Web/providers/microsoft.insights/components/%28Project Name%29</ApplicationInsightsAnnotationResourceId>
    <TypeScriptToolsVersion>2.9</TypeScriptToolsVersion> 
    
    <NETCoreAppMaximumVersion>99.9</NETCoreAppMaximumVersion>
    <RuntimeFrameworkVersion>2.1.0-preview3-26317-01</RuntimeFrameworkVersion>
    </PropertyGroup>
```

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview1-009020
 Commit:    95c6eff6da

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17686
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview1-009020\

Host (useful for support):
  Version: 2.2.0-preview1-26620-03
  Commit:  2ad3de577c

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.2.100-preview1-009013 [C:\Program Files\dotnet\sdk]
  3.0.100-preview1-009017 [C:\Program Files\dotnet\sdk]
  3.0.100-preview1-009019 [C:\Program Files\dotnet\sdk]
  3.0.100-preview1-009020 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30475 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rtm-30752 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview1-34355 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30475 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rtm-30752 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview1-34355 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview3-26411-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rtm-26515-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview1-26609-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview1-26620-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by nguerrera** [comment]
You have *nightly* builds of 2.2.100 and 3.0.100 SDKs installed and they will be preferred over the supported 2.1.3xx RTM SDK unless you pin the SDK using global.json. 2.2 are in very early alpha stage. Try uninstalling them via Add/Remove programs.

**Comment by livarcocc** [comment]
Closing this issue since this seems like a nightly build issue and since we haven't had activity here in a while.
