### ISSUE TITLE
Getting SSL error in dotnet command line

### ISSUE THREAD

**Issue by edmBernard** [dotnet/cli#9618]
I got this issu recently.
I was not able anymore to restore/build/publish/add package from dotnet command line.

## Actual behavior

I got the following error : 

    » dotnet build
    Microsoft (R) Build Engine version 15.7.179.6572 pour .NET Core
    Copyright (C) Microsoft Corporation. Tous droits réservés.
    
      Restauration des packages pour /home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj...
    /usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error : Impossible de charger l'index de service pour la source https://api.nuget.org/v3/index.json. [/home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj]
    /usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   The SSL connection could not be established, see inner exception. [/home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj]
    /usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   error:2006D080:BIO routines:BIO_new_file:no such file [/home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj]
    
    ÉCHEC de la build.
    
    /usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error : Impossible de charger l'index de service pour la source https://api.nuget.org/v3/index.json. [/home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj]
    /usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   The SSL connection could not be established, see inner exception. [/home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj]
    /usr/share/dotnet/sdk/2.1.301/NuGet.targets(114,5): error :   error:2006D080:BIO routines:BIO_new_file:no such file [/home/ebernard/Documents/python/test_dotnet_console/retard-cli/retard-cli.csproj]
        0 Avertissement(s)
        1 Erreur(s)
    
    Temps écoulé 00:00:01.53

I don't thing it a direct issu from dotnet-cli. it seem to come from ssl but I was not able to fix it.
I try to reinstall dotnet-sdk, openssl, it change nothing.
Have you an idea where this can come from ?
I try dotnet build from inside a Docker and it works so I think the issu come from my installation.

## Environment data
`dotnet --info` output:
```
SDK .NET Core (reflétant tous les global.json) :
 Version:   2.1.301
 Commit:    59524873d6

Environnement d'exécution :
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by omajid** [comment]
Some possibly related issues:

- https://github.com/dotnet/corefx/issues/29942
- https://github.com/dotnet/corefx/issues/30385
- https://github.com/dotnet/corefx/issues/30388

Can you reproduce this in a brand new project, like `dotnet new console`? Can you use an `strace` (eg `strace -fo strace.log dotnet restore`) to see what file openssl is trying to open that fails with some sort of error?

**Comment by edmBernard** [comment]
On new projet I need to add new package to get the error. 

For issues you link me:
- I try in sudo and I got the same error.
- I try on a fresh install (inside a docker with alpine and ubuntu) with same dotnet version and i got no error

**Comment by edmBernard** [comment]
I found the issue, it come from snakeoil certificate:

In my `/etc/ssl/certs` I notice some link to snakeoil certificate in red. so it seem these certificates are missing in my computer. 
```
lrwxrwxrwx 1 root root     21 mars  29  2017 0c31d5ce -> ssl-cert-snakeoil.pem
```

I recreate them and everything work again.
```
sudo make-ssl-cert generate-default-snakeoil --force-overwrite 
```

Thank for your help
