### ISSUE TITLE
Feature Request: Add dotnet nuget list cli

### ISSUE THREAD

**Issue by divinebovine** [dotnet/cli#9623]
This is a feature request to add the listing capability from the nuget cli. Currently there is no way to use the dotnet cli to query a nuget server for a list of available packages with their versions. It would be nice to be able to do this so CI tools can check to make sure a push won't overwrite existing packages.

**Comment by peterhuene** [comment]
This issue was moved to NuGet/Home#7121

**Comment by peterhuene** [comment]
Hi @divinebovine.  Thanks for requesting this feature.  I've moved the issue to the NuGet/Home repro that tracks issues related to NuGet (NuGet also owns the `dotnet nuget` command).

Thank you!
