### ISSUE TITLE
Could not find exe from dependency package after dotnet publish

### ISSUE THREAD

**Issue by schellap** [dotnet/cli#964]
Repro steps:
1. Clear the NuGet cache (not for first run) or the cached \*ILCompiler\* folders for subsequent run.
2. Unzip the **[temp.zip](https://github.com/dotnet/cli/files/100270/temp.zip)** file to say `H:\`
3. Issue dotnet restore as specified in command.txt (change the local paths as per your env)
4. Issue dotnet publish as specified in command.txt (change the local paths as per your env)
5. Open the `H:\temp\publish` directory.

The ILC.exe is missing which comes from the dependency of the packages declared in `H:\temp\project\project.json`

**Comment by schellap** [comment]
Cc @davidfowl

It is not clear to me if I am doing something wrong... please advise.

**Comment by brthor** [comment]
Taking a look at the project.lock.json 

I see "runtimes/any/lib/dotnet/ilc.exe" is not longer an export, it only exists under the 'files' object.

@anurse Do you know if NuGet treats ".exe" files under lib differently?

@schellap ILC.exe is really an IL application right? You could just rename it ILC.dll and we can make the corresponding changes. Alternatively you could put it under the native piece and it will probably get picked up correctly again.

**Comment by schellap** [comment]
@brthor, basically, does this mean, `dotnet compile --native` is not possible in the `rel/1.0.0` branch?

**Comment by brthor** [comment]
@schellap We still use dnu for restore currently so that's probably why we haven't seen this issue.

I think this means we need to make changes to make dotnet compile --native work right once we are using NuGet.

**Comment by schellap** [comment]
In general, what is the recommended layout to package this exe file? I believe changing to `ilc.dll` requires CLI changes as well.

**Comment by anurse** [comment]
It looks like NuGet does not consider `.exe` a valid assembly. I'll submit a PR there to fix that.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Client/ManagedCodeConventions.cs#L35

**Comment by anurse** [comment]
https://github.com/NuGet/NuGet.Client/pull/220

**Comment by anurse** [comment]
In the case of all our other "executables" (NuGet, Csc, Fsc, etc.), the packages contain the managed executable as a `dll` and then the build script copies `corehost` in and renames as appropriate to make it runnable.

**Comment by piotrpMSFT** [comment]
@schellap looks like this got merged. Can  you validate and reopen if this is still an issue?
