### ISSUE TITLE
latest.version files still point to runtime 2.1.1/sdk 2.1.301 and not to 2.1.2/sdk 2.1.302

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/cli#9643]
## Steps to reproduce
Download https://dot.net/v1/dotnet-install.ps1 from https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
Execute: .\dotnet-install.ps1 -Channel Current -Version Latest -Verbose

## Expected  behavior
The script downloads SDK 2.1.302
(the file is https://dotnetcli.azureedge.net/dotnet/Sdk/Current/latest.version)

## Actual behavior
The script downloads SDK 2.1.301

It would be nice if you would update the files at the same time as you publish the new sdks etc. on the sdk download page.

## Environment data
.NET Core SDK (gemäß "global.json"):
 Version:   2.1.302
 Commit:    9048955601

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

(VS installed it)

**Comment by peterhuene** [comment]
I'm not sure, actually. It hasn't been part of our release workflow in the past, at least from my checklist. @leecow who owns this in the tick tock normally?

**Comment by leecow** [comment]
I've been taking care of these. Updating 2.1.3xx slid off the radar when the tag publishing slipped to the next day. latest.version files are now updated.
