### ISSUE TITLE
Feature Request: Add options for patching csproj for nuget packages

### ISSUE THREAD

**Issue by dasjestyr** [dotnet/cli#9660]
When running `dotnet pack` or  `dotnet build` (when csproj is set to package on build) it would be helpful to have the ability to include a version number that will be auto-patched into the nuspec. The use case being CI/CD systems where I want packages to be pushed as part of the automated deployment step. So for example, my build script would call something like 

`dotnet pack --package-version 4.3.2.${bamboo.buildNumber}` 

or something to that effect.

At the moment, to my knowledge anyway, I would have to write an executable or script that would modify the csproj for me before attempting to pack or build the project.

**Comment by nguerrera** [comment]
Does `dotnet pack /p:PackageVersion=4.3.2${bamboo.buildNumber}` not work?

**Comment by nguerrera** [comment]
This issue was moved to NuGet/Home#7117
