### ISSUE TITLE
`dotnet script` making C# / f# a script language

### ISSUE THREAD

**Issue by John0King** [dotnet/cli#9664]
```C# 
dotnet script --lang c# --langversion 7.2
C#>Console.WriteLine("hello world")
"hello world"
C#> import "./myCSharpScript.csx"; // or require("./myCSharpScript.csx")   or import {MyStaticFunctions} from "./myCSharpScript";
C#> MyStaticFuntions.Sayhello("john")
"hello,john"
```

Making C# a script language and give it a environment

## Other feature need in script environment

1. Definition file  (like  typescript   for example "Cake.csd") [editor feature]
2. import/require  to import a script
3. nuget and dll file suport ("`#r`  `#nuget` better to use an keywork making it more like scripting")

I really hope that I can easily run C# scripts outside visual studio

**Comment by dasMulli** [comment]
fyi https://github.com/filipw/dotnet-script already implements C# scripting and even has a few more features than roslyn's `csi`

**Comment by nguerrera** [comment]
cc @tmat

**Comment by tmat** [comment]
See https://github.com/dotnet/roslyn/issues/17666

> Definition file (like typescript for example "Cake.csd") [editor feature]

What would be definition file needed for?

> import/require to import a script

You can import scripts by using `#load` directive:

`#load "foo.csx"`

> nuget and dll file suport ("#r #nuget better to use an keywork making it more like scripting")

https://github.com/dotnet/roslyn/issues/6900

**Comment by John0King** [comment]
@tmat 
> What would be definition file needed for?

To write scripts without the actual .`dll` file or provide a assembly list(nuget) the environment already have, since there no project file to tell the Ide what assembly it loaded.
and scripts are dynamic , and if we want all c# script named "*. csx" instead of `*.cake,*.other` , I think it better to create a  "header file“ to tell the language server what class,method,assembly it already have.

----------------------
>You can import scripts by using #load directive:
#load "foo.csx"
```C#
> var file = "myscript.csx";
> #load file // not allowed

//just to point out that directives are not same as script it self . classic asp developers jealousy php's `require() and require_once()` a very long time ago, and those 2 functions and `__File__ , __DIR__`  give php a very flexible environment
```

**Comment by KexyBiscuit** [comment]
`fsi` is already there, when'll `csi` being included?

**Comment by livarcocc** [comment]
I would say ask on the roslyn issue: dotnet/roslyn#17666.

Actually, I am going to close this issue against that one.
