### ISSUE TITLE
Question: Where is the HTTP CLI for .NET Core WebApi Projects?

### ISSUE THREAD

**Issue by eluchsinger** [dotnet/cli#9665]
I was looking forward to trying out that HTTP CLI demonstrated at Build 2018, but I can not find it anywhere. I have not found any documentation on it either. Does it exist?

You can see it here:
https://youtu.be/KAIJ3ezQb3c?t=19m27s

**Comment by nguerrera** [comment]
Adding @danroth27 to answer that.

(The video link doesn't work for me.)

**Comment by danroth27** [comment]
The HTTP CLI is being developed for [ASP.NET Core 2.2](https://github.com/aspnet/Announcements/issues/307), which isn't available quite yet. @glennc @mlorbetske
