### ISSUE TITLE
Comments in Microsoft.Extensions.DependencyModel

### ISSUE THREAD

**Issue by psibernetic** [dotnet/cli#9668]
I, along with many others, have been diving into runtime assembly loading in .NET Core for various reasons. I absolutely love that the library was published on NuGet, so thanks for that, but no XML comments makes it hard to navigate the library.

**Comment by psibernetic** [comment]
Maybe this belongs in Core-Setup? Please advise.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/core-setup#4372
