### ISSUE TITLE
DNX Visual Studio Support for CLI projects Broken after migration to NuGet v3

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#967]
The  move of the NuGet package store from .dnx to .nuget broke VS's ability to provide Intellisense and other IDE services for CLI projects. We expect this to be fixed with the next release of Visual Studio tools but for the time being folks will experience a regression.

@livarcocc pointed out that you can re-enable Visual Studio experiences by manually duplicating  the .nuget directory as .dnx in your user directory.

### Original Text

I deleted the packages folder under .dnx when I was trying things up. Then, when I switched to Visual Studio, nothing was working, none of the dependencies were resolving.

The only way I got it to work again was by copying all packages from the .nuget folder (restored through the CLI build command) over to the .dnx packages folder and restart VS.

I am not really sure of what is going on here. VS worked just fine for other xproj solutions (although, dummy ones that I created to test this).

So, maybe there is something incompatible with our dependencies that dnu does not like.

**Comment by livarcocc** [comment]
This has been fixed by switching to a newer version of dnx.

set DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/api/v2/
dnvm upgrade -u

**Comment by xperiandri** [comment]
Tried this with https://github.com/aspnet/cli-samples
For projects targeting full .NET it works. For Core it does not.
Is it possible to enable debug on IIS Express?
