### ISSUE TITLE
Support globs as parameter to dotnet sln add

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#9670]
Something like `dotnet sln add src\**\*.fsproj` should work.  It generally does on Unix-like systems because the shell will expand the glob, but it doesn't on Windows.

See https://github.com/dotnet/cli/issues/8274 and https://github.com/dotnet/docs/issues/6293

**Comment by livarcocc** [comment]
This is not something that we are looking to do. Globing is owned by the shell on which the CLI runs and the CLI will not start doing globing by itself.
