### ISSUE TITLE
Can't load System.Runtime.Extensions, Version=4.1.0.0

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#968]
[The publish-iis](https://github.com/aspnet/IISIntegration/tree/dev/src/dotnet-publish-iis) tool worked fine in the morning but now suddenly it started failing with: 

"Could not load file or assembly 'System.Runtime.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The loc
ated assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

It seems to be similar to this https://github.com/dotnet/cli/issues/954 which was supposed to be fixed in https://github.com/dotnet/cli/pull/957 but I guess the fix is only for the cli repo. 

I installed the latest cli using (the script from obtain folder) and, just in case, removed all the packages and git clean'd -xdf the repo but it did not help.

**Comment by piotrpMSFT** [comment]
We see this when publishing multiple projects to the same directory. Dependency graph is not unified across projects so order of publishing can cause project2 to downgrade project1. See what in your solution is pulling in the 4.1.0 version of this package, and similarly see what is stomping on it with an earlier version.

**Comment by moozzyk** [comment]
The issue fixed by itself. Closing.

**Comment by nabokov-ef** [comment]
Could you explain how to change the order of publishing? I have this overriding:
Copying file from "[skipped]\packages\System.Runtime.Extensions.4.3.0\lib\net462\System.Runtime.Extensions.dll" to "[azure project]\obj\Debug\[worker project]\System.Runtime.Extensions.dll".
Copying file from "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Runtime.Extensions.dll" to "[azure project]\obj\Debug\[worker project]\System.Runtime.Extensions.dll".
A package assembly is overridden by the GAC assembly, which is wrong.
