### ISSUE TITLE
[source-build] DownloadPackageVersionsProps target is no longer run

### ISSUE THREAD

**Issue by crummel** [dotnet/cli#9680]
I think this must have gotten lost in the refactoring - the `DownloadPackageVersionProps` target still [exists](https://github.com/dotnet/cli/blob/master/build/DownloadPackageVersions.targets#L2) but nothing like [InitRepo](https://github.com/dotnet/core-sdk/blob/master/build/InitRepo.targets) depends on it any more, so it is never run.  Additionally, the destination for the props, `OrchestratedPackageVersionsProps` is no longer defined and, in core-sdk, depends on `GeneratedPropsDir`, which also no longer exists.  I tried to prep a PR for this but ended up not know where you would want all of it - let me know if I can help at all.

cc @nguerrera @dsplaisted

**Comment by dsplaisted** [comment]
It looks like core-sdk uses `bin/obj` for generated props files.  I think it would be fine to use that path for the cli repo.
