### ISSUE TITLE
Building cli fails for v2.0.3

### ISSUE THREAD

**Issue by tylerphelan** [dotnet/cli#9691]
## Steps to reproduce

1. `docker run library/ubuntu:14.04`
1. Checkout this repo at the `v2.0.3` tag
1. `apt-get '-y' 'install' 'clang' 'devscripts' 'debhelper' 'libunwind8' 'libpython2.7' 'liblttng-ust0' 'liburcu1' 'libllvm3.6' 'liblldb-3.6'`
2. Run `./build.sh /t:Compile`

## Expected  behavior

The build succeeds.

## Actual behavior

The build fails due to a failed download:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/1.0.0-preview2-1-003177/dotnet-sdk-1.0.0-preview2-1-003177-linux-x64.tar.gz
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by nguerrera** [comment]
This is a downside of a build that acquires things from the cloud. The stage0 bits are 404. Id on't know why they've gone missing though, we generally keep everything in blob storage. @johnbeisner 

I am curious why you are needing to build the 2.0.3 SDK.

**Comment by tylerphelan** [comment]
@nguerrera we are rebuilding some LTS versions of the SDK for Ubuntu 18.04

**Comment by nguerrera** [comment]
Is this in some official capacity for Ubuntu 18.04? I see in an older thread that you are also trying to build SDK 1.0.x.

I would like to point out that newer SDKs support older runtimes and I would generally not recommend SDK 1.0.x or 2.0.x for anything. These are missing tooling fixes and bundle runtimes with missing fixes (including to security issues) as well.

If possible, I would suggest at the oldest, you use these:

SDK 2.1.202, which bundles runtime 2.0.9 
SDK 1.1.10 that includes runtimes 1.0.12 and 1.1.9

See top lines here:
https://www.microsoft.com/net/download/dotnet-core/2.0
https://www.microsoft.com/net/download/dotnet-core/1.1
https://www.microsoft.com/net/download/dotnet-core/1.0

I would also like to point out that if you just build this repo, only the code for the dotnet command-line-interface will actually build from source. This is a small fraction of everything that ends up in the resulting installer. The rest (runtime, framework, compilers, nuget, msbuild, etc.) all pulled down binaries from nuget feeds that were built elsewhere.

You may be interested in looking at https://github.com/dotnet/source-build, which does build a full .NET Core SDK from source.

cc @leecow

**Comment by tylerphelan** [comment]
Thanks for all the help! We'll use the later versions of the SDK/CLI.
