### ISSUE TITLE
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\2.0.9\hostfxr.dll] , HRESULT: 0x7D4A8

### ISSUE THREAD

**Issue by mindtech2014** [dotnet/cli#9717]
Getting Error when running dotnet --help or other dotnet command
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\2.0.9\hostfxr.dll]
, HRESULT: 0x7D4A8
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\h
ost\fxr\2.0.9\hostfxr.dll failed

Environment: 
OS: Windows 7 Ultimate SP1  (32 bit)

Following things installed 

dotnet-sdk-2.1.202-win-x86
KB2999226
KB2533623
Microsoft Visual C++ 2015 Redistributable Update 3

**Comment by nguerrera** [comment]
This issue was moved to dotnet/core-setup#4390
