### ISSUE TITLE
Runtime resolution to more recent for FDD published apps broken in some circumstances (e.g. 2.1.0-preview2 -> 2.1.1)

### ISSUE THREAD

**Issue by mirkogeffken** [dotnet/cli#9718]
## Steps to reproduce
1) Make sure no runtimes/sdks/shared frameworks are installed (in my case I had a 1.0.0 installed still, but that I did not expect to be used)
2) Install 2.1.0-preview2 SDK Install on Win x64 in my case (URL: https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.300-preview2-windows-x64-installer) (<-- others may fail too, but 2.1.1 e.g. -> 2.1.2 does not)
3) Create a new console app with "dotnet new console" in a folder called myapp
4) Publish an FDD version with "dotnet publish"
5) Confirm this runs by doing "dotnet bin/Debug/netcoreapp2.1/publish/myapp.dll" (You should see "Hello World"
6) Uninstall SDK just installed from add/remove programs
7) Install 2.1.1 (2.1.301 SDK) from https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.301-windows-x64-installer (2.1.2 will also have the same issue)
8) run "dotnet --info" and confirm that 2.1.1 is the only one installed (remove (if necessary) shared frameworks from Program Files\dotnet\shared\{folders}\version (as listed by info other than 2.1.1 (or 2.1.2 if you chose that in step 7
9) go back to myapp folder and run "dotnet bin/Debug/netcoreapp2.1/publish/myapp.dll"

## Expected  behavior
See "Hello World" as in step 5 as 2.1.1 is clearly a more recent (more supported and more secure) version than 2.1.0-preview2

I have been unable to find any statement anywhere that preview versions (while unsupported) would not support resolution to a more recent version.

## Actual behavior
(To be clear I had 1.0.0 installed also despite my steps, which is why it is listed below and used 2.1.2 in this case, but have tried without 1.0.0 and tried with 2.1.1 from preview2 also)

Error Output:
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26406-04' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nguerrera** [comment]
This issue was moved to dotnet/core-setup#4391
