### ISSUE TITLE
SDK build fails for v1.0.4 on ubuntu 18.04

### ISSUE THREAD

**Issue by tylerphelan** [dotnet/cli#9740]
## Steps to reproduce

1. `docker run library/ubuntu:18.04`
1. Checkout this repo at the `v1.0.4` tag
1. `apt-get '-y' 'install' 'clang' 'devscripts' 'debhelper' 'libunwind8' 'libpython2.7' 'liblttng-ust0' 'liburcu6' 'libllvm3.9' 'liblldb-3.9'`
2. Run `./build.sh /t:Compile`

## Expected  behavior

The build succeeds.

## Actual behavior

The build fails due to a failed download:
```
dotnet_install: Error: OS name could not be detected: ubuntu.18.04
```

Is this expected?

**Comment by nguerrera** [comment]
See https://github.com/dotnet/cli/issues/9691#issuecomment-411437005
