### ISSUE TITLE
Unable to load the service index (issues with additional feeds?)

### ISSUE THREAD

**Issue by JBoothUA** [dotnet/cli#9741]
## Steps to reproduce
I am playing around with dotnet tool install and very stuck.  I get the "Unable to load the service index" error, but the ROOT cause I believe is that it's attempting to look (for some reason) at my company's nuget feed..  

No idea why, or how to change it?  Installing a tool should have nothing to do with this nuget feed, but I guess I'm somehow pointing to the wrong feed?

If I remove our feed from the Nuget.config it works as expected but I would rather not have to do that of course.

## Expected  behavior
I can install dotnet tools

## Actual behavior
Unable to load the service index
error : Unable to load the service index for source ----[C:\Users\jbooth1\AppData\Local\Temp\mz02lxyw.emb\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.302\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized).

** I replaced the path to the nuget feed with ---- but it should be noted that it's pointing to my company nuget feed, which has nothing to do with installing this tool...

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by nguerrera** [comment]
@wli3

**Comment by nguerrera** [comment]
@nkolev92

**Comment by nkolev92** [comment]
The root cause here is that tool install uses restore under the covers. 

Restore does not failing sources in order to have consistent resolution. 
The same resolution problems could happen for tools but they're not as likely due to the dependency structure of tools package (or lack thereof). 

2 options here:
- [ ] Keep the consistency, and require that all feeds are accessible. In this case, one needs to authenticate that feed, which currently is only possible with clear text password. This **will** be made better by - https://github.com/NuGet/Home/issues/6486 in 2.1.400. 
- [ ] Ignore the failed sources during tool restore. The overall experience change needs to be discussed here. It's easily achievable by setting the correct property.

**Comment by nguerrera** [comment]
This came up before and now I forget the conclusion...

**Comment by nkolev92** [comment]
Yeah, same...found the duplicate issues after some digging. 
https://github.com/dotnet/cli/issues/9586

**Comment by wli3** [comment]
action item is we need to pass though ignore failure flag

**Comment by JBoothUA** [comment]
I am also getting the exact same scenario when trying to run NuKeeper on my projects with another source..  not sure if it is an issue with NuKeeper or here, but it is the same issue and I can solve it with the same workaround (temporarily remove my company's NuGet feed from the nuget.config)  but i would much rather not have to do that, and that it would actually allow NuKeeper to work on my company's feed.  Hope that helps!
Thanks for everything!!!

**Comment by wli3** [comment]
https://github.com/dotnet/cli/pull/9830

**Comment by JBoothUA** [comment]
@wli3 i'm a complete noob here but trying to get more into the open source community..  i would love to verify that this is working better, I actually have been having multiple problems that I think might be related...  I also see you closed the task, my only real question is:  how do I know I'm testing with the right version??  should I be looking to download a dotnet/cli 2.2.1 ??    Thank you very much!!  even if you don't see this last question, but just for working on my issue!!!!!

**Comment by wli3** [comment]
@JBoothUA sorry for the delay. You could use https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script to download the latest 2.2.1xx branch's build. And add `--ignore-failed-sources` when you run `dotnet install -g ...`. Another solution is to see which feed is erroring out.

You can find your nuget.config and the source feeds in 

```
windows: %appdata%\NuGet\nuget.config 
mac:  ~/.nuget/NuGet/NuGet.Config
```
