### ISSUE TITLE
dotnet test does not appear to respect nologo

### ISSUE THREAD

**Issue by chamons** [dotnet/cli#9745]
## Steps to reproduce
Unlike dotnet build, dotnet test when used with xunit does not appear to respect nologo.
```
dotnet test /v:q /nologo
Build started, please wait...
Build completed.

Test run for /Users/donblas/tmp/foo/bin/Debug/netcoreapp2.1/foo.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
 ```

## Expected  behavior
These lines not shown:
```
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.
```

## Actual behavior
https://gist.github.com/chamons/032eddcceecdecef97216e9ffc8aa1ff

## Environment data
`dotnet --info` output: https://gist.github.com/chamons/bd96b104e88a0fd15a36f2bf0975e5c9

**Comment by wli3** [comment]
This issue was moved to Microsoft/vstest#1701
