### ISSUE TITLE
Global tools not in default path in Makefiles when installed unless ToolCommandName with dotnet- prefix

### ISSUE THREAD

**Issue by chamons** [dotnet/cli#9747]
## Steps to reproduce

- Download https://github.com/chamons/filed-bug-test-cases/tree/master/dotnet-tool-path
- make
- make test
- Note lack of pathtest working
- Run pathtest directly in prompt. Note it working
- make clean to uninstall
- Modify to have tool with ToolCommandName prefix (or apply https://gist.github.com/chamons/6a72b0bf48d7474a0887660731e5b401 patch)
- make test and notice it working

## Expected  behavior
Global tools with dotnet prefix and without should both behave correctly in Makefiles on macOS

## Actual behavior
One works and one does not

## Environment data
https://gist.github.com/fe78f21b3ea6dd9b7b7f1176769e5f4d

**Comment by wli3** [comment]
https://github.com/dotnet/cli/issues/8466

**Comment by chamons** [comment]
Changing the command to ```PATH=$$PATH:$$HOME/.dotnet/tools pathtest
``` is a workaround

**Comment by wli3** [comment]
Due to #8466, the feasible solution would only be abandon pathhelper approach and CLI will always require user to manually edit rc file. This is also "idiomatic" unix way but more cumbersome. I'll close it as won't fix for now.
