### ISSUE TITLE
Auto-update PR (Maestro) builds failing with incompatible framework version

### ISSUE THREAD

**Issue by crummel** [dotnet/cli#9752]
@crummel commented on [Fri Jul 27 2018](https://github.com/dotnet/core-eng/issues/3950)

This has been happening since Wednesday (https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build%2Fresults?buildId=1889485&_a=summary).  Latest failure is https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build%2Fresults?buildId=1895972&_a=summary:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      D:\a\1\s\.dotnet_stage0\x64\
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.0.0-preview1-26710-03 at [D:\a\1\s\.dotnet_stage0\x64\shared\Microsoft.NETCore.App]
Build failed
At D:\a\1\s\build_projects\update-dependencies\update-dependencies.ps1:58 char:27
+ if($LASTEXITCODE -ne 0) { throw "Build failed" }
+                           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Build failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Build failed
 ```

---

@crummel commented on [Fri Jul 27 2018](https://github.com/dotnet/core-eng/issues/3950#issuecomment-408481938)

@dagood Do you know if anyone is looking at this?

---

@dagood commented on [Fri Jul 27 2018](https://github.com/dotnet/core-eng/issues/3950#issuecomment-408490432)

It's actually been failing for longer than that: it was fixed in `release/2.1.4xx` specifically by https://github.com/dotnet/cli/pull/9684, and other branches continue to fail. I suggest moving this issue to the CLI repo to let the team know in case they want to port that change and fix this.

**Comment by crummel** [comment]
These Maestro builds are failing with the above error - from Davis, this seems to be a fix that just needs to be ported from release/2.1.4xx to fix these builds.

**Comment by nguerrera** [comment]
I'll look at this further. I need to change how things work at master. We should be inserting runtime into core-sdk, not cli. And roslyn need to go into toolset. But right now, all the dependency versions are in all the repos and their may be incorrect usage of versions that shouldn't even be in a given repo. It's going to take me a bit of time to sort it out.

**Comment by peterhuene** [comment]
@nguerrera @dsplaisted is this still a relevant issue or can it be closed?

**Comment by nguerrera** [comment]
This was fixed a long while ago.
