### ISSUE TITLE
Update dotnet/Runtime/$channel/latest.version

### ISSUE THREAD

**Issue by sebastienros** [dotnet/cli#9765]
`https://dotnetcli.blob.core.windows.net/dotnet/Runtime/Current/latest.version` is not up to date and returns `2.1.1` instead of `2.1.2`. It makes `dotnet-install` get an older version.

**Comment by peterhuene** [comment]
@leecow Is this something that is also owned by you or is it the runtime team when they publish?

**Comment by leecow** [comment]
I've been keeping them updated. Sorry for the miss! 2.1 associated files are updated.

**Comment by peterhuene** [comment]
Thanks, @leecow!
