### ISSUE TITLE
Code coverage tests failing in master

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#9773]
These tests are failing when integrating from 2.2.1xx to master. Disabling them to unblock the merge.

.Microsoft.DotNet.Cli.Test.Tests.GivenDotnettestBuildsAndRunsTestfromCsproj.ItCreatesCoverageFileWhenCodeCoverageEnabledByRunsettings
.Microsoft.DotNet.Cli.Test.Tests.GivenDotnettestBuildsAndRunsTestfromCsproj.ItCreatesCoverageFileInResultsDirectory
.Microsoft.DotNet.Cli.Test.Tests.GivenDotnetTestBuildsAndRunsTestFromCsprojForMultipleTFM.ItCreatesTwoCoverageFilesForMultiTargetedProject
.Microsoft.DotNet.Cli.Test.Tests.GivenDotnettestBuildsAndRunsTestfromCsproj.ItShouldShowWarningMessageOnCollectCodeCoverage

**Comment by nguerrera** [comment]
@smadala

**Comment by smadala** [comment]
@nguerrera 
As long as we have [MicrosoftNETTestSdkPackageVersion to 15.8.0](https://github.com/dotnet/cli/blob/master/build/DependencyVersions.props#L50), it should not fail. Can you please share PR to look into this?

**Comment by smadala** [comment]
Okay. I will checkout master and finds what happening.

**Comment by smadala** [comment]
I'm able to repro the issue locally. Looks like issue with `vstest.console.dll`(`C:\Users\samadala\src\cli\bin\2\dotnet\sdk\3.0.100-alpha1-00000001-01\vstest.console.dll`) version. 
Expected: 15.8.0 Actual 15.8.0-preview-20180510-03

![image](https://user-images.githubusercontent.com/4337332/43642689-2b3700ee-9746-11e8-8068-6257f2be0860.png)

@nguerrera Can you help me to figure out why 3.0.100-xxx not picking [vstest 15.8.0](https://github.com/dotnet/cli/blob/master/build/DependencyVersions.props#L50)?

**Comment by nguerrera** [comment]
Thanks. It might have been a merge issue. I'll take a look. And sorry if I just merged versions wrong.

**Comment by nguerrera** [comment]
Oh, it's because this is coming from the lkg. It has to do with the repo split at master. Vstest will insert into dotnet/toolset for 3.0 and the tests should probably move there. For now, we can just update the lkg. I'll take care of it.

**Comment by smadala** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
