### ISSUE TITLE
dotnet pack is ignoring documented metadata fields in nuspec file

### ISSUE THREAD

**Issue by glezalex** [dotnet/cli#9777]
I'm trying to pack a DotNet Core console app - target framework is netcoreapp2.1 - using the command 'dotnet pack -c release -o nupkg' and I've noticed several documented metadata fields are apparently ignored.

I'm having a look at https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#nuget-metadata-properties and properties like IsTool, IncludeBuildOutput, IncludeContentInPack, BuildOutputTargetFolder or PackageOutputPath seem to be ignored by the pack command. In fact it only packs properly If I don't specify the property NuspecFile in the csproj. If I do specify NuspecFile, many default values seem to be set different and the result is a nuget package that contains just a copy of my project folder.

`dotnet --info` output:

SDK de .NET Core (reflejando cualquier global.json):
 Version:   2.1.302
 Commit:    9048955601

Entorno de tiempo de ejecución:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7165
