### ISSUE TITLE
dotnet restore

### ISSUE THREAD

**Issue by davevans** [dotnet/cli#9790]
## Steps to reproduce
Updated visual studio to 15.7.6.
Run 'dotnet restore' in solution root
Get error

C:\Program Files\dotnet\sdk\2.1.302\NuGet.targets(114,5): error : Data at the root level is invalid. Line 1, position 1. [C:\git\myproject\mySolution.sln]

## Expected  behavior

expected packages to be restored without error

## Actual behavior
Looks like dotnet restore is treating my solution file as if its an XML file which of course it isnt.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
Could you share a small repro repo with us? Or your sln file? There is a chance that there is something corrupted in your sln file.

**Comment by davevans** [comment]
Turned out this was caused by a corrupt Nuget package referenced in a csproj within the solution. Clearing my cache caused a fresh version to be downloaded into my cache and the issue was resolved.
