### ISSUE TITLE
restore private feed on docker

### ISSUE THREAD

**Issue by iceoz** [dotnet/cli#9813]
## Steps to reproduce
Create a simple .net core 2.1 console application with docker linux container support.
Add a simples package from a external feed, doesn't need authentication, only url
The application will run like a charm in visual studio, restore works fine, etc.
Then open a powershell a try run a docker build, package restore fail, because the build container don't  know the private feed.
dotnet nuget cli can list sources but can't add source
i make a litle change in my docker file to install nuget from apt-get, but nuget restore don't work because .net core 2 doesn't have a packages.config

## Expected  behavior
dotnet cli should have a option to add a private feed

## Actual behavior
dotnet cli can't restore package from private feed
only by mono i can add a private feed, but mono can't restore packages on .net core 2

## Environment data
Step 6/15 : RUN dotnet --info
 ---> Running in f1fa0b3a368c
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
You can add feeds to the CLI through NuGet.Config. `dotnet restore` itself also has a `-s/--source` that let's you list feeds to use.

**Comment by iceoz** [comment]
thanks works fine
