### ISSUE TITLE
Network build failures in 'prodcon/cli/release/2.1.4xx/' - '20180809.01'

### ISSUE THREAD

**Issue by dseefeld** [dotnet/cli#9817]
@dotnet-mc-bot commented on [Thu Aug 09 2018](https://github.com/dotnet/core-eng/issues/4040)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1933292
  - **Agent:** DDVSOLINUXAGE012
  - **Error log:** [?1h=         Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

@jcagme, @markwilkie

---

@dseefeld commented on [Fri Aug 10 2018](https://github.com/dotnet/core-eng/issues/4040#issuecomment-412210292)

This seems to be a product issue.  Moving to cli.

**Comment by livarcocc** [comment]
There has been no other instance of this failure since, so I am going to close this issue.
