### ISSUE TITLE
dotnet tool install -g fails with nuget v2 api on case sensitivity issues

### ISSUE THREAD

**Issue by damageboy** [dotnet/cli#9826]
## Steps to reproduce
Upload a dotnet global tool with mixed case in its name into a v2 feed

Try `dotnet install -g "Some.Mixed.Case.Tool"`

Changing the tool name to be PACKAGED as an all lowercase name, resolves the issue.

This seems to be a v2 API issue where case is actually repspected by the v2 server?

## Expected  behavior

It should install

## Actual behavior
```
The tool package could not be restored.
Tool 'some.mixed.case.tool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

## Environment data
`dotnet --info` output:

```

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
@wli3 @peterhuene can one of you comment? Is this something that we should discuss with NuGet?

**Comment by peterhuene** [comment]
@damageboy thanks for reporting this!

We can look into this before discussing it with NuGet.  We have test cases for this, but perhaps they aren't sufficient.

**Comment by wli3** [comment]
I think it is on the service side. Nuget package is case in sensitive should be expected, that's why we make it lower in the beginning.

**Comment by damageboy** [comment]
@wli hmm, OK.
I'm using Inedo Proget in the reported case, the weird thing is that when I do dotnet restore, I never encounter case sensitivity issues, (e.g. with `<PackageReference Include="Some.Mixed.Case.Tool" ... />`), so there is a change in the actual string being used in the `FindPackgesById()` rest call being actually made in the dotnet restore implementation...

I've reported this to Inedo and waiting for their response.
Is this considered a closed issue as far as you are concerned, or do you want me to keep it open in the meanwhile...?

**Comment by damageboy** [comment]
@wli hmm, OK.
I'm using Inedo Proget in the reported case, the weird thing is that when I do dotnet restore, I never encounter case sensitivity issues, (e.g. with `<PackageReference Include="Some.Mixed.Case.Tool" ... />`), so there is a change in the actual string being used in the `FindPackgesById()` rest call being actually made in the dotnet restore implementation...

I've reported this to Inedo and waiting for their response.
Is this considered a closed issue as far as you are concerned, or do you want me to keep it open in the meanwhile...?

**Comment by peterhuene** [comment]
@damageboy let's not close this issue yet, as this is still a demonstrable problem with tool installation, even if we suspect the NuGet server API should not be treating the package id as case-sensitive.

**Comment by livarcocc** [comment]
@damageboy did you hear back from Inedo Project and their feed?

**Comment by damageboy** [comment]
Not yes, I've brought it up with in their user forum...

**Comment by livarcocc** [comment]
Closing this issue since we haven't heard back from @damageboy in a while.

I see there is a separate issue already for the WSL interaction. We will investigate this scenario there.
