### ISSUE TITLE
Running a dotnet tool from a subdirectory of / fails

### ISSUE THREAD

**Issue by logankp** [dotnet/cli#9827]
When running a dotnet tool, the tool fails to execute if not located in a direct child of /.

## Steps to reproduce
- From a directory (ex. /home/user), run dotnet tool install --tool-path tools <tool>
- Attempt to run the tool (ex. tools/dotnet-cowsay)

## Expected  behavior
The tool runs successfully

## Actual behavior
The tool fails with error: "The application to execute does not exist: '/root/tools/..//root/tools/.store/dotnet-cowsay/1.1.0/dotnet-cowsay/1.1.0/tools/netcoreapp2.1/any/dotnet-cowsay.dll'."

## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by wli3** [comment]
I think i see it before, let me find it

**Comment by wli3** [comment]
@logankp this code fix is in 2.1.4xx and will be fixed in 2.1.4xx release. However it will not be in 2.1.3xx. https://github.com/dotnet/cli/pull/9330  I am sorry for the bad experience.

**Comment by peterhuene** [comment]
@logankp the workaround for now is to pass an absolute path.  As @wli3 stated, this will be fixed in a soon to be released 2.1.400 version of the SDK, but the fix was not included for recent servicing of the 2.1.3xx series.

**Comment by logankp** [comment]
No problem, thanks for the quick responses! I've worked around it so not a huge issue at all.
