### ISSUE TITLE
Modify the CLI build to be less similar to the SDK build

### ISSUE THREAD

**Issue by johnbeisner** [dotnet/cli#9832]
Modify the CLI build to be less similar to the SDK build

To include but not limited to:
1) change the variable name "SDKVersion" to CLIVersion"

2) Change the directory structure of the 'CliOutputDirectory' to appear less like the SDK structure; ie: "SDK" + the product version

3) other...

**Comment by livarcocc** [comment]
I agree with 1. I disagree with 2. The structure is similar to make it easier for it to be consumed in the toolset repo.

**Comment by nguerrera** [comment]
My thing with CliOutputDirectory was about the variable names. IIRC, OutputDirectory ends in /cli and CliOutputDirectory has an sdk structure. The variable names had me reading everything backwards.

**Comment by johnbeisner** [comment]
no longer viable given repo consolidations...
