### ISSUE TITLE
dotnet restore fails with dotnet 2.1.302

### ISSUE THREAD

**Issue by myermian** [dotnet/cli#9833]
## Steps to reproduce
Run dotnet restore on a solution or csproj, utilizing a nuget.config and TFS package management.

## Expected  behavior
The tool restores all of the NuGet packages without any issue.

## Actual behavior
An error occurs:

C:\Program Files\dotnet\sdk\2.1.302\NuGet.targets(114,5): error : Failed to retrieve information about '{package}' from remote source '{tfs_uri}/_packaging/c813af9a-8ce1-439f-aac2-bb906c3bbe0d/nuget/v3/flat2/{package}/index.json'. [{csproj_file}]
C:\Program Files\dotnet\sdk\2.1.302\NuGet.targets(114,5): error :   The target principal name is incorrect [{csproj_file}]

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.302\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

Some projects work without a problem, some projects work when I use the `--ignore-failed-sources` argument (I don't think this is a good fix), and some projects don't work at all in either scenario because the source that is failing is our private package management feed, so it can't rely on nuget.org to get the correct packages.

Additionally, I'm not sure if this is a NuGet/Home issue or a dotnet issue, so I posted it in here because the problem started when we moved from NetCore 2.0 to NetCore 2.1 for our SDK/Runtime. Even netstandard and netcore 2.0 applications are failing when using the netcore 2.1.302 sdk.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7204
