### ISSUE TITLE
Suggestion: Publish Nuget Packages for Base Functionality

### ISSUE THREAD

**Issue by antoinne85** [dotnet/cli#9841]
This repository contains many useful foundational classes for reading/manipulating/writing solution and project files.

These implementations contain much more functionality than what is found in, for example, `SolutionFile` from `Microsoft.Build`.

As such, it would be very useful for those of us attempting to extend the CLI to have a simple way to access and build upon classes such as `SlnFile` and it's friends without having to pull the source down, carve it up, and attempt to bake it into our extension.

I propose that, in as much as is possible, the classes to read/edit/write project and solution files be broken out into a separate assembly and published as a Nuget package.

I'm happy to devote some time to this (or some variant of it) if the repository maintainers think it's worthwhile work and could provide some direction on how they'd like it to proceed.

**Comment by livarcocc** [comment]
I am sorry @antoinne85, while interesting and useful, I don't believe this would be productive to our team.

Maintaining a set of APIs is a very different endeavor from what we usually do by maintaining the SDK. I don't think that this is something we would do in the short or medium term, however, given that this is open source, you are more than welcome to carve the APIs out and to produce your own nupkgs for people to consume.

**Comment by antoinne85** [comment]
I appreciate the speedy response, @livarcocc.

I think I'll give that a go.
