### ISSUE TITLE
dotnet new with no cache

### ISSUE THREAD

**Issue by jnevins-gcm** [dotnet/cli#9856]
## Steps to reproduce
run dotnet new -i MyTemplate::1.2.*

## Expected  behavior
Installs latest 1.2.* of MyTemplate

## Actual behavior
Uses cache and doesn't resolve latest version (sometimes). Have to clear %localappdata%\NuGet\v3-cache and re-run install of template to get latest.

Is there a way of forcing dotnet new -i to not use the cache? Like --no-cache with other dotnet commands?

**Comment by livarcocc** [comment]
This issue was moved to dotnet/templating#1645
