### ISSUE TITLE
Ability to search package with dotnet cli

### ISSUE THREAD

**Issue by John0King** [dotnet/cli#9859]
Current there are `dotnet add package <package name>`, but there no ability to search the package name .

some ideas:
```
dotnet package search newtonsoft.* 
dotnet package search *json*
dotnet package search -tag json
-------------

dotnet package info newtonsoft.json  // show version info
~~dotnet package install  mynugetpackage.nupkg~~
```

or add thos command to `dotnet nuget`

----------------------------------------------

and [another proposal](https://github.com/dotnet/cli/issues/9860#issue-351786550) is to  add a `<PackageFileReference Include="../../privatepackags/myapp.nupkg" />` in project file.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#7217

**Comment by Mizux** [comment]
duplicate of #7869 ?
