### ISSUE TITLE
Proposal: add <PackageFileReference /> in project file

### ISSUE THREAD

**Issue by John0King** [dotnet/cli#9860]
`<PackageFileReference Include="../../privatepackags/myapp.nupkg" />`  as an alternative to `<Reference />` , `Reference` point to `.dll`  , and `PackageFileReference ` point to `.nupkg` .

Reasons for not use use myget or self deployed nuget server.
- myget is slow.
- deploy and configurate  an nuget server  costing time.
- `.dll` file is bad for dependency and for multi-target .
-  private nuget package that has same name and version on nuget or myget

**Comment by dasMulli** [comment]
At the moment, you should be able to do

```
<PropertyGroup>
  <RestoreAdditionalProjectSources>../../privatepackags/</RestoreAdditionalProjectSources>
</PropertyGroup>
```

and then use the normal `<PackageReference />` to reference that package.

**Comment by John0King** [comment]
@dasMulli   What's the order ?   
Will dotnet restore the `RestoreAdditionalProjectSources` first ?

**Comment by dasMulli** [comment]
no idea tbh
@livarcocc who in the nuget team might know which feed is used to fetch the packages?

@John0King if the package is only in that dir, it shouldn't matter.
But NuGet needs to query all feeds to be correct anyway

**Comment by John0King** [comment]
I have a clone of a public nuget package (has some different feature) , right now I'm using `<ProjectReference />` , and I have to copy that project to every new project, that's why I ask for this.

**Comment by antiufo** [comment]
You can add a plain, normal folder to your NuGet.config, it doesn't have to be the URL of a nuget server. Just put your nuget files there.

**Comment by dasMulli** [comment]
I recommended adding a feed using nuget.conf:

https://stackoverflow.com/questions/43400069/dotnet-add-package-with-local-package-file/44463578#44463578

The feed will also be picked up by VS and should also affect 3rd party tools. The property was implemented by NuGet since then.

**Comment by livarcocc** [comment]
I am going to close this issue as we believe there are good alternatives today, as suggested above, without a new feature.

However, if you feel strongly about it, I suggest filling a new issue at nuget/home to discuss it further.

**Comment by John0King** [comment]
Thank you all, I will try the @antiufo suggestion .
and I'll fill a issue at nuget/home for discussion purpose.
