### ISSUE TITLE
Slow initial and consecutive builds with large web solution (Core 2.1.400)

### ISSUE THREAD

**Issue by zuckerthoben** [dotnet/cli#9864]
## Steps to reproduce

We have a large web solution that contains 20 (mostly .NET Core 2.1.X) projects (some are .NET Standard 2.0 libraries). Initial builds (after clean) are really slow and consecutive builds are not as fast as I think they should be after recent performance improvements. 
The project started with Core 1.1, migrated to 2.0 for the most time and got updated to 2.1 days after release. In general we dont feel a big improvement in build times with the recent versions, compared to prior versions. 

As advised in https://github.com/dotnet/cli/issues/7590#issuecomment-413214988 here are the results of the performance summaries.

~~Build solution after clean https://pastebin.com/P0Y0bu8v (4 minutes 32 seconds)
Consecutive Build solution after minor changes in one project https://pastebin.com/aPRXQVVu (48 seconds)
Consecutive build after changes in multiple projects https://pastebin.com/NzUASmMY (4 minutes, 28 seconds)~~
1. Initial build (after clean) (~4 minutes)
https://gist.github.com/zuckerthoben/d1d2caa1f86f8c1ff15396803fc7c397
2.  Consecutive build without any changes (~ 10 seconds)
https://gist.github.com/zuckerthoben/9e4c21d3bc4d236f812b99426ca7db5e
3. Consecutive build with small changes in one big project (~45 seconds)
https://gist.github.com/zuckerthoben/a83deeb549d1a6c164737611788e10c2
4. Consecutive build with multiple small changes in multiple projects (~3 minutes 10 seconds)
https://gist.github.com/zuckerthoben/b975151f279d5584b261236876faa188

## Expected  behavior
- acceptable initial build times
- quick consecutive builds

## Actual behavior
- initial builds are really slow
- consecutive builds are relatively slow

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
@dsplaisted can you take an initial look at where the time is going?

**Comment by zuckerthoben** [comment]
Can you share any insights yet? @dsplaisted @livarcocc

**Comment by papatoob** [comment]
Is there any progress on this issue? I'm working on the same project and build times slow us down significantly.

Thanks in advance.

**Comment by dsplaisted** [comment]
@zuckerthoben @papatoob Unfortunately it looks like the pastebin links from the original report are no longer available.  Can you re-share them?  (Personally I like to use https://gist.github.com/).

Thanks!

**Comment by zuckerthoben** [comment]
Thank you for your answer, dsplaited. I re-did all the measurements: 

1. Initial build (after clean) (~4 minutes)
https://gist.github.com/zuckerthoben/d1d2caa1f86f8c1ff15396803fc7c397
2.  Consecutive build without any changes (~ 10 seconds)
https://gist.github.com/zuckerthoben/9e4c21d3bc4d236f812b99426ca7db5e
3. Consecutive build with small changes in one big project (~45 seconds)
https://gist.github.com/zuckerthoben/a83deeb549d1a6c164737611788e10c2
4. Consecutive build with multiple small changes in multiple projects (~3 minutes 10 seconds)
https://gist.github.com/zuckerthoben/b975151f279d5584b261236876faa188

fyi @papatoob

**Comment by dsplaisted** [comment]
@zuckerthoben Thanks for the performance summaries.

It looks like the build times are mostly taken up by the compilers.  @jaredpar @agocke Can you take a look and comment on whether these compile times look normal and what could be done to investigate them or speed them up?  Is there a way to check if the compiler server is being used?

@zuckerthoben @papatoob One thing you can try doing is setting the `ProduceReferenceAssembly` property to true for all projects.  This should help speed things up when you make a change to the implementation of an assembly but not to the public surface area, as projects that depend on it won't need to be re-compiled.

**Comment by zuckerthoben** [comment]
Thanks a lot @dsplaisted! 
I inserted ProduceReferenceAssembly, together with Deterministic in all projects of the solution and will keep an eye on the build behavior with this new configuration. 

I look forward to an answer of @jaredpar  and @agocke.

**Comment by zuckerthoben** [comment]
Unfortunately the solution is a closed source business solution that I am not allowed to share. Can I do some kind of analysis that gives you the information you need? Like count of projects, dependencies, SLOC or other indicators?

**Comment by jaredpar** [comment]
>Like count of projects, dependencies, SLOC or other indicators?

The size of your project, or the dependencies list, isn't likely to be a factor here. If it's truly a compiler issue it's likely to be specific to a particular pattern of code in your project. 

Can you collect a binary log of the builds instead of a summary log?

Also can you collect a perf trace during the build? That will narrow down what the issue is here.

**Comment by zuckerthoben** [comment]
If you link me to the documentation on how to do these things, I can deliver the logs and traces you need. @jaredpar

**Comment by jaredpar** [comment]
In order to grab a binary log just pass `/bl` at the command line for `dotnet build`. That will produce a file in the current directory, believe default name is msbuild.binlog.

Here is a guide on getting a performance trace: https://github.com/dotnet/roslyn/wiki/Recording-performance-traces-with-PerfView

**Comment by dsplaisted** [comment]
@zuckerthoben Be aware that a binary log also captures a lot of detail about your projects and your build.  See [Providing Binary Logs](https://gist.github.com/dsplaisted/b256d7804672a6f6375476a5f5658b7b) for more details.  Thanks!

**Comment by zuckerthoben** [comment]
I have gathered the binary log of the solution. Whats the best way to privately share the file with you guys?  
@dsplaisted @jaredpar @agocke

**Comment by agocke** [comment]
If it's not too large you can just email it to me at `angocke` @ microsoft

**Comment by zuckerthoben** [comment]
Thank you for your answer. I have sent the file via e-mail to @agocke .
We are looking forward to your analysis.

**Comment by zuckerthoben** [comment]
By request I have gathered a performance trace via PerfView and shared it with @agocke and @jaredpar via mail.

**Comment by zuckerthoben** [comment]
So far we came to the following conclusions:
- The SonarAnalyzer.CSharp package (https://www.nuget.org/packages/SonarAnalyzer.CSharp/) we use for code analysis is the main source of the slow build times. In my performance tests the initial build went from 4 minutes to 1 minute.
- The CSharp Compiler Server seems to not being used, although it should. Currently I have trouble gathering the roslyn log to troubleshoot the compiler server usage. I followed the guide at https://github.com/dotnet/roslyn/blob/master/docs/compilers/Compiler%20Server.md#troubleshooting, without success. I need some further assistance.

**Comment by zuckerthoben** [comment]
We managed to solve the issue. As I said earlier, the SonarAnalyzer slowed down our builds extremely. 
Secondly, we forced the use of the Compiler Server which seemed to not work before with a 
<UseSharedCompilation>true</UseSharedCompilation> inside all csproj files.

**Comment by dsplaisted** [comment]
@zuckerthoben Glad to hear you were able to resolve this!

**Comment by zuckerthoben** [comment]
Thanks a lot for the support @dsplaisted @agocke @jaredpar!
