### ISSUE TITLE
Download for SDK 2.1.401 windows binaries?

### ISSUE THREAD

**Issue by EnricoReich** [dotnet/cli#9869]
Hello,

today I could update linux/ubuntu .net core sdk from 2.1.400 to 2.1.401 but I can not find any download for windows binaries.
Is a download for windows binaries already available and if so could someone point me to the download location, please?

Thanks!

**Comment by livarcocc** [comment]
Where are you looking for these binaries? They are available in the link below.

https://www.microsoft.com/net/download
