### ISSUE TITLE
Microsoft.NETCore.App not using latest runtime version in Visual Studio

### ISSUE THREAD

**Issue by groogiam** [dotnet/cli#9879]
## Steps to reproduce
Following the Visual Studio 15.8.1 it appears the Microsoft.NETCore.App implicit package does not use the latest runtime installed on the machine. I have 2.1.3 installed but all my applications are stuck at 2.1.0 even though 2.1.3 is installed. This is causing numerous nuget package downgrade issues.

It appears you can add the following to the project file but this seems like it should not be required on a framework dependent .net core project.

<RuntimeFrameworkVersion>2.1.2</RuntimeFrameworkVersion>

## Expected  behavior
It seems like the implicit package should use the latest version on the machine.

**Comment by dasMulli** [comment]
You only need >2.1.0 packages(!) for self-contained applications.
If you are deploying framework-dependent applications, 2.1.0 is enough as it will run on the latest patch runtime available by default.

About the downgrade issues: you'd need to be more specific about them.
You may need to set `TargetLatestRuntimePatch` to `true` in a `PropertyGroup` of some of the .csproj files to fix it depending on the specific issue.
A good read is https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection

Some of the underlying problems causing downgrade issues may be fixed as part of the upcoming 2.2 release (`2.2.100`+ CLI versions)
