### ISSUE TITLE
Build failures:  Unable to find package Microsoft.DotNet.Test.ProjectTemplates.2.2 

### ISSUE THREAD

**Issue by MattGal** [dotnet/cli#9890]
@dotnet-mc-bot commented on [Thu Aug 23 2018](https://github.com/dotnet/core-eng/issues/4101)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974073
  - **Agent:** DDVSOLINUXAGE009
  - **Error log:** [?1h=         Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974068
  - **Agent:** DDVSOLINUXAGE005
  - **Error log:** [?1h=         Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974067
  - **Agent:** DDVSOLINUXAGE004
  - **Error log:** Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974074
  - **Agent:** DDVSOWINAGE020
  - **Error log:** Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974069
  - **Agent:** DDVSOLINUXAGE006
  - **Error log:** [39;49m[36m    11>[39;49m[39;49m[31m/opt/code/build/templates/templates.csproj : error NU1102: Unable to find package Microsoft.DotNet.Test.ProjectTemplates.2.2 with version (>= 1.0.2-beta4-20180822-1972211) [/opt/code/build/...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974070
  - **Agent:** DDVSOLINUXAGE007
  - **Error log:** [?1h=         Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974075
  - **Agent:** DDVSOWINAGE021
  - **Error log:** Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974071
  - **Agent:** DDVSOMACAGE011
  - **Error log:** Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1974072
  - **Agent:** DDVSOLINUXAGE008
  - **Error log:** [?1h=         Error 2147500037 (Exception from HRESULT: 0x80004005 (E_FAIL)) while compiling method BuildServerConnection.CreateMonitorDisconnectTask...

@jcagme, @markwilkie

---

@MattGal commented on [Fri Aug 24 2018](https://github.com/dotnet/core-eng/issues/4101#issuecomment-415845245)

Moving this one to CLI, @livarcocc please close if you're already tracking this.  All these failures are:

```
/opt/code/build/templates/templates.csproj : error NU1102: Unable to find package Microsoft.DotNet.Test.ProjectTemplates.2.2 with version (>= 1.0.2-beta4-20180822-1972211) [/opt/code/build/BundledTemplates.proj]
/opt/code/build/templates/templates.csproj : error NU1102: - Found 2 version(s) in templating [ Nearest version: 1.0.2-beta4-20180821-1966911 ] [/opt/code/build/BundledTemplates.proj]
```

**Comment by livarcocc** [comment]
@MattGal @mmitche why isn't prodcon finding package Microsoft.DotNet.Test.ProjectTemplates.2.2 with the version currently inserted? Do we need to add dotnet/templating to prodcon for 2.2?

**Comment by mmitche** [comment]
@livarcocc Yeah it needs to be added.

**Comment by livarcocc** [comment]
@mmitche should we keep this issue open until then?

**Comment by mmitche** [comment]
Actually, it is in there, MC just isn't showing it.

**Comment by mmitche** [comment]
There is a 2.2 package for microsoft.dotnet.common.projecttemplates, but not one for the test.projecttemplates.  This is probably an issue in dotnet/templating.

**Comment by mmitche** [comment]
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=1975523&view=logs

**Comment by livarcocc** [comment]
Actually, the test templates were moved to a new repo and that one is not in ProdCon, that's the issue.

@mlorbetske what is the new repo where the test templates live?

**Comment by mmitche** [comment]
oh, it's dotnet-testtemplates.  I am surprised it was moved for 2.2 though.  I thought that was a 3.0 thing

**Comment by MattGal** [comment]
@livarcocc can you comment on what the outcome was?   i.e. is this fixed now, won't-fixed, etc?

**Comment by livarcocc** [comment]
This is the PR that fixed this: https://github.com/dotnet/cli/pull/9902. I forgot to link it.
