### ISSUE TITLE
Improvement: Add ability to generate runtime specific deps files at build time. 

### ISSUE THREAD

**Issue by johanste** [dotnet/cli#990]
Today, deps files are generated by either dotnet-build or dotnet-restore. Since dotnet-build doesn't take a runtime parameter, however, it is not possible to target a platform other than the one that you are currently executing dotnet-build on.

If you generate the deps file on the install target (which is what dotnet-restore does), it will require a custom tool to run on the target machine to install the package. To the best of my knowledge, the only tool that does that today is dotnet-restore. 

As having the dotnet cli installed on the target machine is not a viable requirement for an arbitrary coreclr based application, the deps file creation logic would have to move somewhere else. 

While the core nuget client libraries could be that "somewhere else", it would be preferrable to add the ability to do so at build time, since that would enable a developer to create fully x-copy deployable application targeting any runtime from his favorite box as opposed to having to build the application targeting osx on his favorite Mac etc. 

 Ex. dotnet build --runtime osx.10.10-x64 --framework dnxcore50

would produce a deps file corresponding to osx assembly locations even when executed on windows/Ubuntu.

**Comment by davidfowl** [comment]
You'd need to first restore for those platforms. Instead of command line arguments it should be persisted in the `project.json` so that all tools don't need to be coordinated with the right args:

```
{
   "dependencies": {
   },
   "frameworks": {
      "dnxcore50": { }
   },
   "runtimes": {
       "osx.10.10-x64": { },
       "win7-x64": { }
   }
}
```

Then you'd run dotnet restore and dotnet build. Maybe we need a way to enumerate all runtimes on compile (like we do for publish). If specified in the project file.

**Comment by livarcocc** [comment]
both build and publish support framework and runtime.

In MSBuild world, you still need to have the RuntimeIdentifiers set in the csproj, but then restoring the project restores them all.

After that, you can simply run dotnet publish --runtime win7-x64 for instance, even on a non-windows machine and the application will be published for windows.
