### ISSUE TITLE
Remove dotnetfeed from bundledversions.props once we bundle targeting pack packages in the SDK

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#9908]
In [this commit](https://github.com/dotnet/core-sdk/pull/63/commits/703ba2399974255175872812a284f3dc2a41da02), I added an additional package restore source for the dotnetfeed blob feed.  This meas projects targeting .NET Core 3 can build without adding the feed to NuGet.config.

Once we have targeting packs bundled with the .NET Core SDK, we should remove this.

**Comment by livarcocc** [comment]
I believe this is now done, correct @dsplaisted?

**Comment by dsplaisted** [comment]
Yes, this was done in https://github.com/dotnet/core-sdk/pull/1561
