### ISSUE TITLE
Remove LZMA from core-sdk

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#9910]
For .NET Core 3.0, we are going to get rid of the LZMA file that expands into the NuGetFallbackFolder.  Instead, we are going to have targeting packs which are bundled in the installer.

The LZMA doesn't currently add any value for the 3.0 builds, because it's "incoherent" - ie it doesn't have the right preview packages.  So we should go ahead and remove it now.

**Comment by dasMulli** [comment]
any chance to get rid of / clean the `NuGetFallbackFolder`?
my problem with it always was that you cannot reasonably clean certain versions of it (ie remove all 1.* packages)

**Comment by livarcocc** [comment]
@dsplaisted is this issue now done?

**Comment by dsplaisted** [comment]
@livarcocc No, we still need to remove it from core-setup

**Comment by livarcocc** [comment]
@dsplaisted did you mean core-sdk?

**Comment by dsplaisted** [comment]
@livarcocc Oops, yes

**Comment by dasMulli** [comment]
about repo confusion:
is there still any work being done for merging sdk/cli repos? or was the effort halted?

**Comment by dsplaisted** [comment]
> is there still any work being done for merging sdk/cli repos? or was the effort halted?

We still plan to do it eventually.  I'm not sure if we ever started working on it so far though.

**Comment by dasMulli** [comment]
just checking, only saw the wiki document last year that had very specific steps and version names https://github.com/dotnet/cli/wiki/CLI-&-SDK-repo-merge
