### ISSUE TITLE
Consider adding retry logic to download() function in scripts/obtain/dotnet-install.sh

### ISSUE THREAD

**Issue by MattGal** [dotnet/cli#9912]
@dotnet-mc-bot commented on [Wed Aug 29 2018](https://github.com/dotnet/core-eng/issues/4127)

There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1987783
  - **Agent:** DDVSOLINUXAGE008
  - **Error log:** [31mdotnet_install: Error: Could not download .NET Core SDK version 2.1.300(B[m...

@jcagme, @markwilkie

---

@MattGal commented on [Wed Aug 29 2018](https://github.com/dotnet/core-eng/issues/4127#issuecomment-417036024)

This is indeed a transient network failure attempting to download https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-rhel.6-x64.tar.gz from the CLI's "dotnet-install.sh" script, which only makes one try.  The error message: `curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104` indicates a server-side disconnection.   

As this represents an Azure VM talking to an Azure storage account via an Azure CDN, we don't have anywhere on the dnceng team we can help out.  I feel that these lines should be updated to retry the download at least once:
https://github.com/dotnet/cli/blob/release/2.1.4xx/scripts/obtain/dotnet-install.sh#L642-L664 , so am moving the issue over to the CLI repo for consideration there.

**Comment by MattGal** [comment]
@johnbeisner FYI, you seem to touch this file a bit.

**Comment by wli3** [comment]
@livarcocc different issue? I was confused as well. I addressed msbuild task retry. https://github.com/dotnet/cli/pull/10073

But this issue is retry in install script

**Comment by livarcocc** [comment]
ah, true. I will leave it assigned to @johnbeisner then.

**Comment by johnbeisner** [comment]
Curl and wget do indeed retry 10 times:
https://github.com/dotnet/cli/blob/release/2.1.4xx/scripts/obtain/dotnet-install.sh#L675-L679
https://github.com/dotnet/cli/blob/release/2.1.4xx/scripts/obtain/dotnet-install.sh#L696-L700

Closing in favor of: https://github.com/dotnet/cli/issues/10215
