### ISSUE TITLE
dotnet build fails with System.ArgumentException after upgrading from 2.0 to 2.1 SDK

### ISSUE THREAD

**Issue by shueybubbles** [dotnet/cli#9916]
## Steps to reproduce
This is one of the projects in Sql Server Management Objects. We have a Vs2013-compatible .proj file that invokes dotnet.exe using <Exec>

F:\src\SSMS\tools\netcore\2.1_rtm\dotnet.exe build --configuration Debug /p:BuildProjectReferences=false /p:MSBuildAllProjects=F:\src\SSMS\Sql\ssms\shared\CrossPlat\CrossPlatBuild.proj --version-suffix xplat F:\src\SSMS\Sql\ssm
s\shared\BatchParser\Microsoft.Data.Tools.Sql.BatchParser\Microsoft.Data.Tools.Sql.BatchParser.csproj

## Expected  behavior
The project should build as it does with the 2.0 SDK.

## Actual behavior
System.ArgumentException: Item has already been added. Key in dictionary: 'TRACKER_TOOLCHAIN'  Key being added: 'TRACKER_TOOLCHAIN'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Environment.ToHashtable(IEnumerable`1 pairs)
   at System.Environment.GetEnvironmentVariables()
   at System.Diagnostics.ProcessStartInfo.get_Environment()
   at Microsoft.DotNet.Cli.Utils.ForwardingAppImplementation.GetProcessStartInfo()
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.GetProcessStartInfo()
   at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.GetProcessStartInfo()
   at Microsoft.DotNet.Tools.RestoringCommand.Execute()
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

## Environment data
`dotnet --info` output:
NET Core SDK (reflecting any global.json):
Version:   2.1.401
Commit:    91b1c13032

untime Environment:
OS Name:     Windows
OS Version:  10.0.17134
OS Platform: Windows
RID:         win10-x64
Base Path:   F:\src\SSMS\tools\netcore\2.1_rtm\sdk\2.1.401\

ost (useful for support):
 Version: 2.1.3
 Commit:  124038c13e

NET Core SDKs installed:
 2.1.2 [F:\src\SSMS\tools\netcore\2.1_rtm\sdk]
 2.1.2 [C:\Program Files\dotnet\sdk]
 2.1.104 [F:\src\SSMS\tools\netcore\2.1_rtm\sdk]
 2.1.104 [C:\Program Files\dotnet\sdk]
 2.1.200 [F:\src\SSMS\tools\netcore\2.1_rtm\sdk]
 2.1.200 [C:\Program Files\dotnet\sdk]
 2.1.202 [F:\src\SSMS\tools\netcore\2.1_rtm\sdk]
 2.1.202 [C:\Program Files\dotnet\sdk]
 2.1.400 [F:\src\SSMS\tools\netcore\2.1_rtm\sdk]
 2.1.400 [C:\Program Files\dotnet\sdk]
 2.1.401 [F:\src\SSMS\tools\netcore\2.1_rtm\sdk]
 2.1.401 [C:\Program Files\dotnet\sdk]

NET Core runtimes installed:
 Microsoft.AspNetCore.All 2.1.2 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.AspNetCore.All]
 Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
 Microsoft.AspNetCore.All 2.1.3 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.AspNetCore.All]
 Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
 Microsoft.AspNetCore.App 2.1.2 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.AspNetCore.App]
 Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.AspNetCore.App 2.1.3 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.AspNetCore.App]
 Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
 Microsoft.NETCore.App 2.0.3 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.6 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.7 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.9 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.1.2 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.1.3 [F:\src\SSMS\tools\netcore\2.1_rtm\shared\Microsoft.NETCore.App]
 Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by livarcocc** [comment]
This only happens to this project? We have seen this in the past when the user has repeated env variables declared in his environment, with different casing perhaps? Perhaps your build is setting these environment variables?

**Comment by shueybubbles** [comment]
my build environment is...complicated. That variable is not defined in the cmd shell from which I launch the build, so it would be coming from a tool somewhere in the build process. 
If I set SDK version to 2.1.202 in global.json, that project works just fine (it targets netstandard2.0) but it won't let my netcoreapp2.1 project build: 

1>F:\src\SSMS\tools\netcore\2.1_rtm\sdk\2.1.202\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0
   or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [F:\src\SSMS\Test\NetCoreSmoTests\Microsoft.SqlServer.Test.NetCoreSmo.csproj] [F:\src\SSMS\Sql\ssms\shared\CrossPlat\CrossPlatBuild.proj]
1>F:\src\SSMS\Sql\ssms\shared\CrossPlat\CrossPlatBuild.proj(181,5): error MSB3073: The command "F:\src\SSMS\tools\netcore\2.1_rtm\dotnet.exe publish --configuration Debug --no-dependencies -o E:\src\ssms\Debug\x86\netcore\\NetCoreS
  moTests F:\src\SSMS\Test\NetCoreSmoTests" exited with code 1.
1>Done Building Project "F:\src\SSMS\Sql\ssms\shared\CrossPlat\CrossPlatBuild.proj" (default targets) -- FAILED.

So I suppose I can use 2.1.202 to build my netstandard projects and 2.1.401 for my netcoreapp2.1 projects for now.

**Comment by shueybubbles** [comment]
though this is going to complicate my life, as I have one .proj file to execute the dotnet publish commands for my projects: 
.NET Core SDK looks for a global.json file in the current working directory (**which isn't necessarily the same as the project directory)** or one of its parent directories.

**Comment by livarcocc** [comment]
It seems like you are actually hitting this issue: https://github.com/dotnet/corefx/issues/30341. I knew I remembered seeing something like that in the past. It would be interesting to find out where the double env variable is being created. That's your best change at having a clean build.

**Comment by shueybubbles** [comment]
well I'll try, but it's coming from somewhere in the msbuild toolset. My proposed workaround of using 2.1.401 for only the netcoreapp2.1 project doesn't help, it gives me the same error but only when I execute the build from the <Exec> task in the msbuild project. I can run dotnet build from the command line just fine.

**Comment by livarcocc** [comment]
Closing the issue for now since this is an issue in corefx's API and we talked about a potential workaround.

**Comment by danmosemsft** [comment]
Environment variables should never have duplicate names. In a very quick look at the source of tracker.exe/filetracker.dll (which is internal) TRACKER_TOOLCHAIN is always set with SetEnvironmentVariable, which should never create duplicates. There is a bug somewhere in there. However I agree it's fine to close this in favor of making .NET not choke in that situation.

**Comment by shueybubbles** [comment]
my hacky workaround is to create dotnet.cmd which unsets the 2 variables then invokes dotnet.exe with same args

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
