### ISSUE TITLE
dotnet tool install/uninstall <--local> dotnetsay packageID

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#9917]
Experience to create/edit manifest file for local tools

**Comment by vchirikov** [comment]
2 month we can't run `dotnet tool install -g`.
Any news?

**Comment by livarcocc** [comment]
@vchirikov I don't believe this is the right issue for you to comment on, this issue is tracking new work: adding a manifest for a local tool feature we are building.

Have you filed a separate issue for your case already?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by vchirikov** [comment]
@livarcocc  :
#8368 -> #10059 -> #9924 -> #9917
Where I turned the wrong way?

**Comment by livarcocc** [comment]
10059 -> 9924 were linked for a different issue than I can't install global tools.

If installing global tools is failing for you, I suggest you file a new issue with details about how to repro and what is happening in your case.

**Comment by vchirikov** [comment]
Sorry, I'm confused between the azure-pipelines repository issues and the cli.
My problem well described here  https://github.com/Microsoft/azure-pipelines-tasks/issues/8291 but it's closed, (won't fix in azure-pipeline team as I understand).
