### ISSUE TITLE
The type or namespace name 'Math' does not exist in the namespace 'System'

### ISSUE THREAD

**Issue by hynguyen2610** [dotnet/cli#992]
Hi,
We knew that Math is a child of namespace "System". But if I change HelloWorld.cs example code, add a line in Main:
> Console.WriteLine(System.Math.Sin(4));
When compiling, it will throw an error:
>  error CS0234: The type or namespace name 'Math' does not exist in the namespace 'System' (are  
>  you  missing an assembly reference?)
It's not working with Console.WriteLine(Math.Sin(4)); too
How could I import something that imported before? (namespace System used)

**Comment by piotrpMSFT** [comment]
Check out the https://github.com/dotnet/corefx repo which produces the Framework packages. It looks like System.Math is in System.Runtime.Extensions. You can add this to the dependencies in your project.json:

````
    "System.Runtime.Extensions": "*"
````
