### ISSUE TITLE
2.1.401 CLI contains 2.1.1 EF tools, causing warnings about outdated tools

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#9938]
## Steps to reproduce
* Install 2.1.401 CLI (from website, since VS installer installs a preview at the moment)
* Use `dotnet ef dbcontext list` on a netcorapp2.1 web+ef project with versionless M.A.App reference (or reference 2.1.3)

## Expected  behavior
Command lists the available DbContext without warning.

## Actual behavior
Prints a warning:

```
> dotnet ef dbcontext list
The EF Core tools version '2.1.1-rtm-30846' is older than that of the runtime '2.1.2-rtm-30932'. Update the tools for the latest features and bug fixes.
```

This is probably because the `DependencyVersion.props` file of the release/2.1.4xx branch still points to the 2.1.1 EF tools.

cc @natemcmaster @livarcocc 

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
@mmitche shouldn't this have come from ProdCon?

**Comment by natemcmaster** [comment]
Yes, the DotnetEfPackageVersion version variable should have been overridden in a ProdCon build by https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180725-02/cli-inputs/orchestration-metadata/PackageVersions.props. Can we look at the build logs to see whether this import happened or not?

**Comment by mmitche** [comment]
We think this is just the warning, not the actual version.  @dasMulli What happpens when you do `dotnet ef --version`?

**Comment by natemcmaster** [comment]
I assume `dotnet ef --version` will be '2.1.1-rtm-30846', as the warning in the original issue indicates. @dasMulli by chance, did you get the 2.1.401 SDK via Visual Studio installers? You might be seeing a side effect of https://github.com/dotnet/cli/issues/9897. There are a few different builds of "2.1.401" floating around, and one of those would have EF 2.1.1 and the other (the right one) would have 2.1.2.

By the way, I recommend moving to aspnet/EntityFrameworkCore. From my local testing, the real 2.1.401 has the correct EF version, as does 2.1.402. We discussed this warning with @ajcvickers and others a few weeks ago. There were some ideas about how to make this warning better, but I'm not sure what the EF team decided.

**Comment by ajcvickers** [comment]
@natemcmaster We're not planning to do anything for the patch release since we don't have a way of shipping the new tools package. At least, that was what I thought we had concluded.

**Comment by dasMulli** [comment]
so I re-downloaded from the dot.net URL and it contains the right tools version now. I though I had re-downloaded this on the machine it initially repro'd already but I have have just deleted the 2.1.3-servicing* version and run the installer again since I thought just the installer package had a problem in VS. Or I re-downlaeded too early and a bad version was on the ms download CDN?

**Comment by natemcmaster** [comment]
@ajcvickers My recollection is also fuzzy, but I thought you were considering changing the warning to ignore patch version.

**Comment by dasMulli** [comment]
(closing since the vs issue is already known and there is at least another issue here for the 2.1.3 shared fx version)

**Comment by dasMulli** [comment]
> We think this is just the warning, not the actual version. @dasMulli What happpens when you do dotnet ef --version

at least on the machine I'm working on today the VS version showed the 2.1.1-rtm-* version for `dotnet ef --version` but it shows the 2.1.2-rtm-* version now after re-installing from the dot.net URL. can't reach the initial repro machine now (work remotely today and the machine is shut down).

**Comment by ajcvickers** [comment]
@natemcmaster Yes, we're considering that for 2.2.

**Comment by dasMulli** [comment]
Any chance to at least distribute a 2.1.402 via VS so all machines get a proper update?

**Comment by dasMulli** [comment]
Do you still do manual validation work vor VS releases? If so, running `dotnet ef --version` seems like an easy enough thing to run for checking expected tooling versions of a dotnet-sdk build. At least since there's now a known risk of getting bad builds.
