### ISSUE TITLE
dotnet publish should expose --framework-dependent

### ISSUE THREAD

**Issue by terrajobst** [dotnet/cli#9949]
## Steps to reproduce

Publish using a RID without specifying `--self-contained`:

```
dotnet publish --runtime win-x86
```

## Expected  behavior

You get a framework-dependent application with an executable to launch.

## Actual behavior

You get a self-contained application.

## Desired change

As soon as `--runtime` is specified, the default for `publish` assumes `--self-contained`. The developer can in fact get a framework dependent application by specifying `--self-contained:false`:

```
dotnet publish --runtime win-x86 --self-contained:false
```

However passing an explicit value for flag-based options is not intuitive, because it doesn't follow regular conventions for GNU-style options.

We don't believe we can change of the default ` --self-contained` when publishing with a RID due to backwards compatibility concerns, so we should at least expose a flag that allows to produce runtime-specific, but framework-dependent outputs without crazy syntax:

```
dotnet publish --runtime win-x86 --framework-dependent
```

<details>
 <summary>Environment data</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.401\

Host (useful for support):
  Version: 2.1.3-servicing-26724-03
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by peterhuene** [comment]
Thanks, @terrajobst!

**Comment by kkm000** [comment]
`--no-self-contained` is the GNU-ish style of negating flag options. Does not sound quite grammatical in this particular case, but I would still prefer it rather than having to remember that `--self-contained` means `--framework-dependent:false` while `--framework-dependent` means `--self-contained:false`. :)
