### ISSUE TITLE
dotnet run/test failed as .NETCore 1.1.2 was not found on sdk 1.1.11

### ISSUE THREAD

**Issue by yuki233** [dotnet/cli#9955]
## Steps to reproduce
1. Install sdk 1.1.11-msrc-fnl-005292
2. dotnet new console or mstest
3. dotnet run/test to observe

## Expected  behavior
dotnet run/test works normally

## Actual behavior
dotnet run/test failed with as .NETCore 1.1.2 was not found
c:\nicole-test\myconsole>dotnet run
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.13-servicing-005091-00
      1.1.10-servicing-001782-00
  - Alternatively, install the framework version '1.1.2'.

## Environment data
`dotnet --info` output:
c:\nicole-test\myconsole>dotnet run
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.13-servicing-005091-00
      1.1.10-servicing-001782-00
  - Alternatively, install the framework version '1.1.2'.

**Comment by livarcocc** [comment]
@peterhuene can you take a look, since this seems to be for the MSRC.

**Comment by peterhuene** [comment]
Closing issue in favor of email discussion.
