### ISSUE TITLE
Build Scripts: Seperate Test Restore from Product Restore

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#997]
Today, all package dependencies in the cli repo are restored in a single pass at the beginning of the build. This has a number of undesirable side effects:
* Restore is done through Stage0 bits, not Stage2 for the full build
* Projects, particularly test projects, that require test-specific NuPkgs must play games [project.json.template, for example], to keep out of the way of product restore until their dependencies are built.

We should separate product restore from test restore to address these concerns.

**Comment by piotrpMSFT** [comment]
#999

**Comment by brthor** [comment]
@piotrpMSFT What did you have in mind here? Restoring tests after the build of stage2, or just removing the restore inside the tests themselves?
