### ISSUE TITLE
On WSL Ubuntu 18.04 dotnet tool install -g Cake.Tool and Octopus.DotNet.Cli fails

### ISSUE THREAD

**Issue by devlead** [dotnet/cli#9974]
The combination of WSL and Ubuntu 18.04 seems to cause issues with .NET global tools.

## Steps to reproduce
```bash
dotnet tool install -g Cake.Tool
```
```bash
dotnet tool install -g Octopus.DotNet.Cli
```

## Expected  behavior

```diff
+ You can invoke the tool using the following command: dotnet-cake
+ Tool 'cake.tool' (version '0.30.0') was successfully installed.
```
```diff
+ You can invoke the tool using the following command: dotnet-octo
+ Tool 'octopus.dotnet.cli' (version '4.41.0') was successfully installed.
```
## Actual behavior
```diff
- The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
- Tool 'cake.tool' failed to install. Please contact the tool author for assistance.
```
```diff
- The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
- Tool 'octopus.dotnet.cli' failed to install. Please contact the tool author for assistance.
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

I've successfully installed `Cake.Tool` and `Octopus.DotNet.Cli` using 2.1.401 on

* Docker
  - microsoft/dotnet:2.1-sdk
  - ubuntu:18.04
  - ubuntu:16.04
  - fedora:28
  - centos:centos7
* WSL
  - Ubuntu 16.04
  - openSuse Leap 42
  - Debian 9
* Windows
* Mac

So doesn't seem package related but rather a specific environment issue.

**Comment by devlead** [comment]
NuGet targets Generated project file looks like this
```xml
<Project>
  <PropertyGroup>
    <MsBuildProjectExtensionsPath>/home/matkar/test/.store/.stage/0xdks0fe.ejw</MsBuildProjectExtensionsPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RestorePackagesPath>/home/matkar/test/.store/.stage/0xdks0fe.ejw</RestorePackagesPath>
    <RestoreProjectStyle>DotnetToolReference</RestoreProjectStyle>
    <RestoreRootConfigDirectory>/home/matkar</RestoreRootConfigDirectory>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <RestoreFallbackFolders>clear</RestoreFallbackFolders>
    <RestoreAdditionalProjectSources>/usr/share/dotnet/sdk/NuGetFallbackFolder</RestoreAdditionalProjectSources>
    <RestoreAdditionalProjectFallbackFolders></RestoreAdditionalProjectFallbackFolders>
    <RestoreAdditionalProjectFallbackFoldersExcludes></RestoreAdditionalProjectFallbackFoldersExcludes>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="cake.tool" Version="*" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```

Checking the  `cake.tool/0.30.0/tools/netcoreapp2.1/any/`  temp folder in stage reveals package is fetched and unzipped
![image](https://user-images.githubusercontent.com/1647294/45350997-63085a80-b5b5-11e8-9646-cef114ce2778.png)

DotnetToolSettings.xml is present and looks ok
```xml
<?xml version="1.0" encoding="utf-8"?>
<DotNetCliTool Version="1">
  <Commands>
    <Command Name="dotnet-cake" EntryPoint="Cake.dll" Runner="dotnet" />
  </Commands>
</DotNetCliTool>
```

If I do a ` dotnet restore restore.csproj` 
```
  Restoring packages for /home/matkar/test/restore.csproj...
  Installing Cake.Tool 0.30.0.
  Restore completed in 938.48 ms for /home/matkar/test/restore.csproj.
```
But it's still in `.stage` and not `.store` which would indicate something went wrong.

If I check the global tool folder I see the same issue in `.store/` is empty / no shim, but the package could be found in `.store/.stage/0xdks0fe.ejw/cake.tool/0.30.0/`

And `dotnet .store/.stage/0xdks0fe.ejw/cake.tool/0.30.0/tools/netcoreapp2.1/any/Cake.dll --version` executes fine so it's not a zip integrity or network issue at least.

**Comment by YakhontovYaroslav** [comment]
I'll add my 50 cents:
[Fake CLI](https://www.nuget.org/packages/fake-cli/) and [Sonar Scanner](https://www.nuget.org/packages/dotnet-sonarscanner/) tools are installing just fine. One common note: this packages are published with lowercase id's and without dots there, when packages causing problems uses camel-case naming with dots, but there is no such restrictions in [tool nuget package format documentation](https://github.com/dotnet/cli/blob/master/Documentation/general/tool-nuget-package-format.md).
I did a little research just renaming and repacking Cake.Tool and it did the trick:
```
cd ~
mkdir test
cd test
wget https://www.nuget.org/api/v2/package/Cake.Tool/0.30.0 -O Cake.Tool.0.30.0.nupkg
unzip Cake.Tool.0.30.0.nupkg -d repack
cd repack/
rm _rels/ -r 
rm package/ -r
rm \[Content_Types\].xml
rm .signature.p7s
sed -i 's/Cake.Tool/cake-tool/g' Cake.Tool.nuspec
nuget pack
mv cake-tool.0.30.0.nupkg ../
cd ..
dotnet tool install cake-tool -g --add-source ./
```
Since renaming to lowercase worked for me i tend to think that this problems is somehow related to #9870 and #9826.

**Comment by devlead** [comment]
What's interesting is that it only fails on WSL Ubuntu 18.04, it works on a container and virtual machine running Ubuntu 18.04. It works all other WSL distros including Ubuntu 16.04.

**Comment by mholo65** [comment]
Re renaming and repacking:

Remember that repacking the tool also removes any package signatures. The Cake.Tool package you get from NuGet is both a) repository signed by NuGet.org and b) package signed by .NET foundation.

We have seen issues in the past regarding package signing (and repo signing) and this might be equally related.

**Comment by livarcocc** [comment]
@wli3 @peterhuene can one of you take a look?

**Comment by peterhuene** [comment]
This is the same issue as one discussed previously.  Let me see if I can find it.

**Comment by AnthonySteele** [comment]
We  are seeing a very similar issue here: https://github.com/NuKeeperDotNet/NuKeeper/issues/433

Install on Ubuntu 18.04 fails, hosted on WSL on on a cloud VM. Error is:

> The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.

The error is not correct, that file exists. This night be a capitalisation issue - the tool name is "NuKeeper" or it might be signing. We can't tell since the error message is lying to us.

**Comment by wli3** [comment]
Closing in favor of issue https://github.com/dotnet/cli/issues/10101
