### ISSUE TITLE
gpg:keyserver timed out 

### ISSUE THREAD

**Issue by raunakpandya** [dotnet/cli#9975]
To install dotnet on the ubuntu 16.04 box, we add the new GnuPG key to the apt key ring using the following command.. 

sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893

We have seen on one of our customer setup that this call consistently returns time out. 

Output: Executing: /tmp/tmp.JM5OfV6PjC/gpg.1.sh --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 Error: gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net gpg: keyserver timed out gpg: keyserver receive failed: keyserver error 2018-09-08 05:44:38,262 [ERROR] - Command List: sudo ./install_required.sh Status: 2 Output: Executing: /tmp/tmp.JM5OfV6PjC/gpg.1.sh --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 Error: gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net gpg: keyserver timed out gpg: keyserver receive failed: keyserver error 2018-09-08 05:45:09,295 [INFO] - Executing: sudo ./install_required.sh 2018-09-08 05:47:09,483 [DEBUG] - Command List: sudo ./install_required.sh Status: 2 Output: Executing: /tmp/tmp.tRrz63POgh/gpg.1.sh --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 Error: gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net gpg: keyserver timed out gpg: keyserver receive failed: keyserver error 2018-09-08 05:47:09,484 [ERROR] - Command List: sudo ./install_required.sh Status: 2 Output: Executing: /tmp/tmp.tRrz63POgh/gpg.1.sh --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 Error: gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net gpg: keyserver timed out gpg: keyserver receive failed: keyserver error

Are there any known cases when such behavior could happen?

**Comment by livarcocc** [comment]
See https://github.com/dotnet/core/issues/1817.

Also, I would suggest the instructions from https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.402
