### ISSUE TITLE
Windows Support and Help links are http.

### ISSUE THREAD

**Issue by blowdart** [dotnet/cli#9977]
## Steps to reproduce
Install SDK or runtime, go to Add/Remove programs, cry.

## Expected  behavior

Help and Support links should be https

## Actual behavior

![dm1y5jwuyaa3qek](https://user-images.githubusercontent.com/796298/45380760-55a09f80-b5b8-11e8-91cd-ce3f63525eb8.jpg)

See https://github.com/dotnet/core-setup/issues/4559 for parent issue. @leecow wanted 3 issues :)

**Comment by Eilon** [comment]
Dup of https://github.com/dotnet/core-setup/issues/4379, but maybe a fix needs to be backported?
