### ISSUE TITLE
Simplify first run experience flags

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#9978]
When DOTNET_CLI_TELEMETRY_OPTOUT is set to 1 or true, SDK should not print the telemetry message notice.  When this behavior is corrected, the SDK no longer needs the DOTNET_PRINT_TELEMETRY_MESSAGE environmental variable, and it will no longer be checked or used. 

The reason of the flag is added: https://github.com/dotnet/cli/pull/6869#discussion_r122033436

**Comment by wli3** [comment]
@omajid Is this ok for you? From the original discussion, the above plan could resolve the problem without the extra flag. We try to reduce the count of flags that affects the first run experience.

cc @KathleenDollard

**Comment by omajid** [comment]
Going back and reading #6869, your new suggestion makes perfect sense to me.

**Comment by wli3** [comment]
thanks!
