### ISSUE TITLE
AsyncLocal<> reference works on Windows, but not Linux (netstandard2.0)

### ISSUE THREAD

**Issue by kierenj** [dotnet/cli#9993]
Hi! Is there anything I can do to diagnose this one?  I'm not confident this is the correct repo either, please correct me!

Project file:
```c#
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Redacted</Description>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Redacted</AssemblyName>
    <PackageId>Redacted</PackageId>
  </PropertyGroup>
</Project>
```

Code:
```c#
using System.Threading;
// ...
_context = new AsyncLocal<SomeClass>();
```

Building locally, .NET SDK 2.1.401, Windows 10, from dotnet build commandline or VS 2017, no problem. Couple of warnings about async methods with no awaits (not related).

Building on Travis CI, .NET SDK 2.1.401, Ubuntu Trusty:

```c#
error CS0246: The type or namespace name 'AsyncLocal<>' could not be found (are you missing a using directive or an assembly reference?)
```

Edit: for ref, build command was `dotnet msbuild "/t:Restore;Pack" my-project.csproj "/p:VersionSuffix=alpha1-999000722" "/p:IncludeSource=true"`

**Comment by kierenj** [comment]
I don't have a recreation of the Travis environment, so it takes a while to set up/run each time.
I created https://github.com/kierenj/repro-dotnet-cli-9993, but that builds fine on the Linux server I have (newer version of Ubuntu).

I'll try to recreate the project in question step-by-step with CI builds each time.

Is there anything in particular I could be looking out for? - case-sensitive paths I'll keep an eye on for one.

**Comment by kierenj** [comment]
An update, `dotnet build /t:Restore;Pack` etc fails, `dotnet pack` works.  I don't remember why I was using the former.  I don't have much time to burn on getting down to a minimal repro, though I'm happy to drop a little if someone on this thread has something simple I can do to help others in the future?

**Comment by dasMulli** [comment]
@kierenj never build `Restore` and other targets in the same invocation. `dotnet build` will do a restore pass anyway so hopefully the second restore doesn't try to do something different.
If you're using raw msbuild, use the `-restore` switch: `dotnet msbuild -restore -t:Pack`

**Comment by livarcocc** [comment]
as usual, @dasMulli is right. You should never do `/t:Restore;SomeOtherTarget`. In this case, msbuild does not have the right opportunities to load the appropriate things. Assuming that doing your operation without /t:Restore works, I am going to close this issue.
